### ISSUE TITLE
After releasing touch control (camra move),left click is triggered.

### ISSUE THREAD

**Issue by emelin2004** [PojavLauncherTeam/PojavLauncher#10]
As I have said in the tittle,when moving camera around and then releasing,it triggers left click.

btw. i would also like to say that i is by far the best version of all i have tried. On my low-end j530f it runs almost constant 30-40fps.

**Comment by khanhduytran0** [comment]
It has been fixed preview6. Wait for few days.

**Comment by emelin2004** [comment]
Thanks! Also, I'm not sure if i should create new report for this but events for keys get fired twice. Gor example when i Open chat an press r once,in chat i see "rr",same goes for back key.

**Comment by khanhduytran0** [comment]
Are you using external keyboard?

**Comment by emelin2004** [comment]
> Are you using external keyboard?

No, I'm using Androids built in keyboard. Touch. 
Device: Samsung Galaxy J5 2017

**Comment by emelin2004** [comment]
> Are you using external keyboard?

On older versions of boardwalk the keyboard works okay,no double letters being entered.

**Comment by khanhduytran0** [comment]
With me, the problem appear when using external keyboard (preview6) but built-in keyboard works fine. Not sure if that problem can be fixed for you in preview 6.

**Comment by emelin2004** [comment]
I will wait and see 😂,if problem still exists in preview6 I will tel you.

**Comment by emelin2004** [comment]
> With me, the problem appear when using external keyboard (preview6) but built-in keyboard works fine. Not sure if that problem can be fixed for you in preview 6.

I just notices something,i tested the keyboard on 1.7.10 and it works fine,but on 1.9 it produces double letters.

**Comment by khanhduytran0** [comment]
Same as in 1.11. Preview6 is almost complete. Wait a bit...

**Comment by khanhduytran0** [comment]
OptiFine works a bit then crash, you can try as yourself
EDIT: you can download official Optifine installer jar then select it from the launcher

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview6

**Comment by emelin2004** [comment]
> https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview6

Wow,that was fast! Keep up the good work.
I will test it right away and tell you the results.

**Comment by emelin2004** [comment]
> https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview6

Ok,so my built in samsung game recorder doesn't want to record anything but game,keyboard is not visible for some reason.

Problem still exists,double letters are being put in and now also I'm unable to close chat after oppening it.

I recorded my screen and put it on youtube so you can see it.
https://youtu.be/NXOtuHRmZdg

**Comment by khanhduytran0** [comment]
Some next fix could happend on next several days. Because my device work, I will do some tests/builds on Android-x86 to attempt to fix.

**Comment by khanhduytran0** [comment]
While wait for fixing, did you test OptiFine?

**Comment by emelin2004** [comment]
> While wait for fixing, did you test OptiFine?

I'm unable to run 1.7.10.
It outputs some errors. 

![Screenshot_20200327-143459_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/49245188/77761668-aeb81300-7038-11ea-9901-d3f06221465d.jpg)

![Screenshot_20200327-143438_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/49245188/77761879-fdfe4380-7038-11ea-8b8a-6eb60434c44d.jpg)


I'm running your launcher with this configuration.
Android: 9 ARM32
Ram:2GB

**Comment by khanhduytran0** [comment]
Preview6.1 fixed all bugs here. Closing
