### ISSUE TITLE
Application/game exited with code 1. Error

### ISSUE THREAD

**Issue by Installator** [PojavLauncherTeam/PojavLauncher#1000]
![Screenshot_20210303_120411_net kdt pojavlaunch](https://user-images.githubusercontent.com/48353606/109766957-b1dc5b80-7c18-11eb-9833-f8b796491d42.jpg)
I press the start button, a few seconds pass, and a closing notice comes out with code 1.

**Comment by CriticalRange** [comment]
1000, wow, also can you send the latestlog.txt file so we can understand what's the problem.(The devs need it but maybe i can find it problem)

**Comment by Installator** [comment]
> 1000, wow, also can you send the latestlog.txt file so we can understand what's the problem.(The devs need it but maybe i can find it problem)

Latest log:
--------- beggining with launcher debug
Info: LWJGL3 directory: [ClassWrapper.jar, lwjgl-tinyfd.jar, lwjgl-jemalloc.jar, lwjgl.jar, lwjgl-stb.jar, lwjgl-openal.jar, lwjgl-opengl.jar, jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-glfw-converted.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms450m -Xmx700m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
Minecraft Args: [--fullscreen]
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!

**Comment by artdeell** [comment]
Update to the latest development build from Actions

**Comment by Installator** [comment]
> Update to the latest development build from Actions

How i can do it?

**Comment by artdeell** [comment]
Go to the actions tab of the github repository

**Comment by Installator** [comment]
> Go to the actions tab of the github repository

Thank you very much. 
But I have new problem. I can only see the back of all the textures.
![Screenshot_20210303_215831_net kdt pojavlaunch](https://user-images.githubusercontent.com/48353606/109843665-2345f980-7c6d-11eb-879f-8d62fd7e99d8.jpg)
![Screenshot_20210303_215842_net kdt pojavlaunch](https://user-images.githubusercontent.com/48353606/109843693-29d47100-7c6d-11eb-9250-e697ad92dedd.jpg)

What can this be related to?
