### ISSUE TITLE
[BUG] Can't look around at all

### ISSUE THREAD

**Issue by maggster165** [PojavLauncherTeam/PojavLauncher#1003]
Can't move camera at all

When i start the game, I can't look around at all.

To Reproduce:
1. Start PojavLauncher
 2. Open a world

Expected behavior:
I expected to be able to look around

Platform:
 - Device Model: Samsung Galaxy A12
 - CPU architecture: aarch64
 - Android Version: 10
 - PojavLauncher Version: Latest

**Comment by Mathias-Boulay** [comment]
The bug isn't reproducible on the latest google play release.
Closing the issue.
