### ISSUE TITLE
[BUG] <optifine not installing>

### ISSUE THREAD

**Issue by VanshModi1998** [PojavLauncherTeam/PojavLauncher#1004]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I can not install any of the optifine version I download all my optifines from www.optifine.net/download and when I open pojav launcher and install the optifine it says game exitied with code 1

**Add a log file if you want to see your bug fixed !*
LogFile Link-->
https://drive.google.com/file/d/1-KkqC2_zOztBN3t4FPgqMtr8WlqUIQmg/view?usp=drivesdk

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:

Screen shot of this bug -->
https://drive.google.com/file/d/1-4SFzt6qob5QamnY2qQpxaQJtOTYtyJm/view?usp=drivesdk

**Platform:**
 - Device Model [Resmi note 7 pro 6/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [10]
 - PojavLauncher Version [Latest Vesion]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Access denied.

**Comment by Derman447** [comment]
Same thing but with fabric 😔

**Comment by Mathias-Boulay** [comment]
We still cannot access the log files, and optifine installs properly on the google play version
