### ISSUE TITLE
Wont let me join friends private server

### ISSUE THREAD

**Issue by Eutamashi** [PojavLauncherTeam/PojavLauncher#1005]
1. Start PojavLauncher
2. Launch 1.16.5
3. Go into multilayer
4. add server "mund.serv.gs"
5. get the error "io.netty.channel.connecttimeoutexception: connection time out"

I expected to join the server with my friends

**Platform:**
 - samsung galaxy s10+
 - CPU architecture  Exynos: Octa-core (2x2.73 GHz Mongoose-M4, 2x2.31 GHz Cortex-A75 and 4x1.95 GHz Cortex-A55) 
 - Android Version 10
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 !
 - [Screenshot_20210304-213232_PojavLauncher_Minecraft_Java_Edition_for_Android](https://user-images.githubusercontent.com/80073316/110040378-a2edca00-7d3a-11eb-8729-15c36b7762e2.jpg)

**Comment by AutumnVN** [comment]
download latest build 
https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk

**Comment by VanshModi1998** [comment]
Bro add the port like this.    example.aternos.me:25565
Like this and it will join

**Comment by LanceAldrei04** [comment]
> 1. Start PojavLauncher
> 2. Launch 1.16.5
> 3. Go into multilayer
> 4. add server "mund.serv.gs"
> 5. get the error "io.netty.channel.connecttimeoutexception: connection time out"
> 
> I expected to join the server with my friends
> 
> **Platform:**
> 
> * samsung galaxy s10+
> * CPU architecture  Exynos: Octa-core (2x2.73 GHz Mongoose-M4, 2x2.31 GHz Cortex-A75 and 4x1.95 GHz Cortex-A55)
> * Android Version 10
> * PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 !
> * [Screenshot_20210304-213232_PojavLauncher_Minecraft_Java_Edition_for_Android](https://user-images.githubusercontent.com/80073316/110040378-a2edca00-7d3a-11eb-8729-15c36b7762e2.jpg)

Add Port like this

mcadventurej.aternos.me:28245

**Comment by LanceAldrei04** [comment]
> Bro add the port like this. example.aternos.me:25565
> Like this and it will join

Are you playing Aternos Server can I join

**Comment by ghost** [comment]
This ''io.netty.channel'' always causing problems with servers :/

**Comment by khanhduytran0** [comment]
@Eutamashi Get latest build
