### ISSUE TITLE
[F-REQ] What's shaders support in Pojavlauncher?

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1007]
What shaders supported in Pojavlauncher?

**Comment by LanceAldrei04** [comment]
If you want shader play java edition on pc 😁👍👍

**Comment by OwzygZawg** [comment]
:/

**Comment by ghost** [comment]
Only open4es shaders support pojav and they currently private and working on it to fix bugs and release it perfectly soon so wait for it

**Comment by OwzygZawg** [comment]
Not link in moment?

**Comment by OwzygZawg** [comment]
In progress?

**Comment by PeterScorPioN** [comment]
> In progress?

Yes. These shaders are currently under a closed beta, which means that they cannot be shared yet. 
Patience my friend.

**Comment by LANCECRAFT1104** [comment]
> > In progress?
> 
> Yes. These shaders are currently under a closed beta, which means that they cannot be shared yet.
> Patience my friend.

Closed?

**Comment by PeterScorPioN** [comment]
> Closed?

By saying "closed" i mean that they are not available for everyone, only for shader's developers.

**Comment by LanceAldrei04** [comment]
Why many people like shader?

**Comment by matt995** [comment]
O4es is free now
