### ISSUE TITLE
Failed to log in to an aternos server

### ISSUE THREAD

**Issue by Palotops** [PojavLauncherTeam/PojavLauncher#1008]
Hello, I can not enter a server, I have the last compilation that was recommended in another post for a bug, can someone help me ... thanks 
![Screenshot_2021-03-05-17-36-41-400_net kdt pojavlaunch](https://user-images.githubusercontent.com/79231717/110181283-6fae4800-7dd9-11eb-8701-6a79a5a32c5f.jpg)

**Comment by Google61** [comment]
Simply enable hotspot and reconnect.

**Comment by Palotops** [comment]
Thanks, I already managed to solve it, I just had to go to server options in the atoms page and enable the option that says "cracked" and it let me enter c:
