### ISSUE TITLE
[BUG] Dropz mod not working

### ISSUE THREAD

**Issue by Druxelite** [PojavLauncherTeam/PojavLauncher#1009]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6094384/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Install the dropz mod and fabricapi
2. Install optifabric and optifine
3. Boot up PojavLauncher
4. Select a version containing fabric
5. Press the "Play" button
6. Wait

### Expected behavior:
I expected the dropz mod to work on PojavLauncher with optifabric, and not crash

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Mode: Redmi Note 9s Pro
 - CPU architecture: aarch64
 - Android Version: Android 10
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210303

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Dropz mod is like item physics mod but more realistic
</pre> 
</details>

**Comment by khanhduytran0** [comment]
Check if .minecraft/libraries/org/lwjgl exists?

**Comment by artdeell** [comment]
Namespace issue, again

**Comment by Druxelite** [comment]
> Check if .minecraft/libraries/org/lwjgl exists?

It does

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
