### ISSUE TITLE
Crashes while running on Samsung Dex mode

### ISSUE THREAD

**Issue by aminkh17** [PojavLauncherTeam/PojavLauncher#1011]
Steps to reproduce 
- Start Dex mode
- Open the Launcher
- Click on play button

**Comment by RadiatedExodus** [comment]
PojavLauncher has not been tested on Samsung DeX yet, however it should still work. Try enabling use freeform window (as DeX uses it) and try reinstallating Pojav completely (by deleting the PojavLauncher folder at the "games" folder and uninstall Pojav and then install it again).

**Comment by aminkh17** [comment]
I have tried to proposed solution, however, unfortunately, it didn't work. It reopen itself and asking for login.

**Comment by khanhduytran0** [comment]
@aminkh17 and fill the template.

**Comment by Mathias-Boulay** [comment]
@aminkh17 Does the issue still happens on the current google play release ?

**Comment by aminkh17** [comment]
Yes, it works well, thanks for the update.
