### ISSUE TITLE
[F-REQ] Controller support because I hate touch screen.

### ISSUE THREAD

**Issue by badge059** [PojavLauncherTeam/PojavLauncher#1012]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RadiatedExodus** [comment]
If I remember this was planned but for now you should use a controller to keyboard mapper (as a alternative solution)

**Comment by badge059** [comment]
Ok thanks very much for telling me:) have a good day!

**Comment by Mathias-Boulay** [comment]
Duplicate from #80
Closing.
