### ISSUE TITLE
[BUG] im not start minecraft in my device

### ISSUE THREAD

**Issue by diamondswor** [PojavLauncherTeam/PojavLauncher#1014]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
@diamondswor fill da template

**Comment by AutumnVN** [comment]
> Read before submit
and u submitted it without fill the template

**Comment by diamondswor** [comment]
This my log
--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version, META-INF, org]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms52m -Xmx80m"
Headless version detected! (20140514)
--------- beginning of main
I/jrelog  (13588): Starting logging STDIO as jrelog:V
I/jrelog  (13588): WARNING: linker: libjli.so: unused DT entry: type 0x1d arg 0x3a8
I/jrelog  (13588): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libverify.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x478
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libverify.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6ffffffe
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0xba4
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libverify.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6fffffff
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x1
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (13588): WARNING: linker: libjava.so: unused DT entry: type 0x1d arg 0x34ad
I/jrelog  (13588): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (13588): WARNING: linker: libjava.so: unused DT entry: type 0x6ffffffe arg 0x64fc
I/jrelog  (13588): WARNING: linker: libjava.so: unused DT entry: type 0x6fffffff arg 0x2
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (13588): WARNING: linker: libnet.so: unused DT entry: type 0x1d arg 0x13f9
I/jrelog  (13588): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (13588): WARNING: linker: libnet.so: unused DT entry: type 0x6ffffffe arg 0x2850
I/jrelog  (13588): WARNING: linker: libnet.so: unused DT entry: type 0x6fffffff arg 0x2
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libnio.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x2303
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libnio.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6ffffffe
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x43d8
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libnio.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6fffffff
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x2
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libawt.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x732a
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libawt.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6ffffffe
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0xe4fc
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libawt.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6fffffff
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x1
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libawt_headless.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x52e
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libawt_headless.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6ffffffe
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0xd04
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libawt_headless.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6fffffff
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x1
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libfontmanager.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x1010
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libfontmanager.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6ffffffe
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x2248
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libfontmanager.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6fffffff
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x2
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libhprof.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x27f
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libj2pcsc.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x30e
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libdt_socket.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x1f5
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): liblcms.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x5bb
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): liblcms.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6ffffffe
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x1174
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): liblcms.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6fffffff
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x1
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libmanagement.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x178c
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libmanagement.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6ffffffe
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x27cc
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libmanagement.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x6fffffff
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x2
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libmlib_image.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x1df
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so success
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): libjsdt.so
I/jrelog  (13588): : unused DT entry: type 
I/jrelog  (13588): 0x1d
I/jrelog  (13588):  arg 
I/jrelog  (13588): 0x161
I/jrelog  (13588): WARNING: linker: 
I/jrelog  (13588): Unsupported flags DT_FLAGS_1=
I/jrelog  (13588): 0x81
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
I/jrelog  (13588): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (13588): WARNING: linker: libj2pkcs11.so: unused DT entry: type 0x1d arg 0xf42
I/jrelog  (13588): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (13588): dlopen /data/data/net.kdt.po

**Comment by diamondswor** [comment]
Close

**Comment by khanhduytran0** [comment]
So... what’s your device RAM? 512MB?

**Comment by diamondswor** [comment]
@Khanhduytran0 No my ram 2gb I'm trying to get into the game by changing the argument jvm

**Comment by khanhduytran0** [comment]
You need set to 256mb or 512mb. Under 100mb is too low to Minecraft to start

**Comment by Mathias-Boulay** [comment]
Ram amount too low, not related to the launcher itself.
Closing the issue.
