### ISSUE TITLE
[BUG] Small GUI

### ISSUE THREAD

**Issue by jeffrey1233** [PojavLauncherTeam/PojavLauncher#1016]
help how to make this big because its hard to press
![Screenshot_20210307_184515](https://user-images.githubusercontent.com/51091629/110238091-7aeca980-7f7a-11eb-8d17-206924945392.jpg)
![Screenshot_20210307_184520](https://user-images.githubusercontent.com/51091629/110238093-7e803080-7f7a-11eb-9c40-6916a2241541.jpg)

**Comment by jeffrey1233** [comment]
its become more smaller when i use oftipine

**Comment by artdeell** [comment]
change it in minecraft gui settings
or use virtual mouse to point

**Comment by jeffrey1233** [comment]
nothing happened when  im changing it

**Comment by jeffrey1233** [comment]
i think installing optifine make this bug

**Comment by khanhduytran0** [comment]
Try increase your screen downscale ration (will make game a bit more pixelated...)
