### ISSUE TITLE
Aaaaaa I can't install labymod

### ISSUE THREAD

**Issue by sreyaspopz** [PojavLauncherTeam/PojavLauncher#1018]
Hi

<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6098550/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Install labymod 
3. Keep saying mod not dictated

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [Mi 7 Pro 8/128]
 - CPU architecture [aarch64] 
 - Android Version [10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by sreyaspopz** [comment]
Brooo I can't install labymod😵😔

**Comment by WesleyVanNeck** [comment]
Plz follow the template

**Comment by WesleyVanNeck** [comment]
NVM am not awake yet

**Comment by artdeell** [comment]
LabyMod is not supported in 3.3.1.1 release
Grab an action build - https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/596100929

**Comment by sreyaspopz** [comment]
Ok

**Comment by sreyaspopz** [comment]
Thanks for Reply 😝
