### ISSUE TITLE
[BUG] LabyMod 1.8.9 crashes

### ISSUE THREAD

**Issue by LosVocelos** [PojavLauncherTeam/PojavLauncher#1020]
### Describe the bug
The instalation of LabyMod ran successfully, but when I started the game, it freezes with this error:

[crash-2021-03-08_10.22.36-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6100768/crash-2021-03-08_10.22.36-client.txt)
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6100771/latestcrash.txt)

One of them is from Labymod vanilla (I don't remember which one), the second is from forge, with Labymod mod.
*Also, I hope these files are enough, 'cause I accidentally deleted logs.* 

### To Reproduce:

1. Install LabyMod (Vanilla or forge, I tried both)
2. Start LabyMod
3. It freezes

**Platform:**
 - Motorola e5 plus
 - ARM
 - Android Version 8.0.0
 - PojavLauncher Version: Automatic build #2225

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
I've just started using this app, so I don't know if this is just
temporary bug in this version, or it's 'cause of my mobile...
</pre>
</details>

**Comment by LosVocelos** [comment]
### Oh! And it was LabyMod 1.8.9, I didn't try 1.12.2.

**Comment by LosVocelos** [comment]
So, 1.12.2 works fine, so the error occurres only with version 1.8.9

**Comment by AlexParker574** [comment]
Same with me

**Comment by Mathias-Boulay** [comment]
Yeah labymod 1.8.9 is known to crash.

**Comment by Mathias-Boulay** [comment]
Sadly we cannot fix it, it comes packaged with some PC discord integration, which is known no to work
