### ISSUE TITLE
[F-REQ] Open URL links

### ISSUE THREAD

**Issue by LosVocelos** [PojavLauncherTeam/PojavLauncher#1021]
### Make possible to open url links from minecraft in browser

**Comment by LosVocelos** [comment]
I read that it was allready added, dut it doesn't work (at least) for me.

**Comment by accoyc** [comment]
this function does not work for me either.  just nothing happens

**Comment by Neftalicruz** [comment]
Es vdd estaría muy bueno si agregan eso

**Comment by ghost** [comment]
It doesn't work for me, Any URL I try to open does not open.

**Comment by Mathias-Boulay** [comment]
URL opening works for 1.13+ for the moment. Work has yet to be done for 1.12.2-

**Comment by artdeell** [comment]
Implemented in latest update
