### ISSUE TITLE
[BUG] Bruh no such a file or directory

### ISSUE THREAD

**Issue by NotStolenTotally** [PojavLauncherTeam/PojavLauncher#1022]
### Describe the bug
no file yes or directory

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_2021-03-08-19-30-17-23](https://user-images.githubusercontent.com/79393331/110323898-d46eda00-8047-11eb-921d-eeea91cca343.png)

i downloaded the Google play version (because i was searching something then i found pojav launcher on Google playstore)

**Comment by artdeell** [comment]
fix was already made, now waiting for google play to roll it
