### ISSUE TITLE
Game exited with code 1

### ISSUE THREAD

**Issue by DominicFranzese** [PojavLauncherTeam/PojavLauncher#1023]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Game Crash while loading.

HAVE TO PASTE LOGS BECAUSE IT WONT LET ME ADD THE FILE
--------- beggining with launcher debug
Info: LWJGL3 directory: [version, lwjgl-tinyfd.jar, lwjgl.jar, lwjgl-opengl.jar, lwjgl-glfw-classes.jar, jsr305.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-stb.jar]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms384m -Xmx768m"
Headless version detected! (20151203)
full args: [-cp, /storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-tinyfd.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-opengl.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-glfw-classes.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/jsr305.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-jemalloc.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-openal.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-stb.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.8.9/1.8.9.jar, net.minecraft.client.main.Main, --username, aaaa, --version, 1.8.9, --gameDir, /storage/emulated/0/games/PojavLauncher/.minecraft, --assetsDir, /storage/emulated/0/games/PojavLauncher/.minecraft/assets, --assetIndex, 1.8, --uuid, 0, --accessToken, 0, --userProperties, {}, --userType, mojang, --fullscreen]
--------- beginning of main
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
I/jrelog  (24733): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (24733):  (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
I/jrelog  (24733): WARNING: linker: 
I/jrelog  (24733): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success
I/jrelog  (24733): WARNING: linker: Warning: "
I/jrelog  (24733): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (24733):  (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so
I/jrelog  (24733): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (24733): 
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success
I/jrelog  (24733): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success
S/LaunchJVM(24733): dlopen /data/user/0/net.kdt.pojavlaunch/jre_r

### To Reproduce:
Try to start a version of minecraft that isn't an rd version.

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected it to load

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model Samsung Galaxy Tab A
 - CPU architecture aarch32
 - Android Version 10
 - PojavLauncher Version  Latest Release || version 3.3.1.1_rel_20210206 

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Update your launcher
https://play.google.com/store/apps/details?id=net.kdt.pojavlaunch
