### ISSUE TITLE
[BUG] Minecraft crash when I try to enter in a server (again)

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#1024]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
When I try to enter in a server, like Hypixel for example, the game simply crash.

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.
Logs:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6101869/latestlog.txt)

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6101871/latest.log)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Open the game (1.12.2 or 1.16.5, with the latest OptiFine)
3. Try to enter in a server.
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected to enter in the server ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model: Moto G6 play
 - CPU architecture: aarch32] 
 - Android Version: 9
 - PojavLauncher Version: Latest Release on play store

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
Aarch32 doesn't have a ought ram to play on servers

**Comment by MateusL13** [comment]
> Aarch32 doesn't have a ought ram to play on servers

This makes no sense, because, if I put the same amount of RAM on my pc, I'll be able to play.
And I can play on severs on another launcher on Android.

**Comment by MichaelBest01** [comment]
> Aarch32 doesn't have a ought ram to play on servers

Does PojavLauncher support aarch64 since more phones are using that and minecraft would be more stable on it. I also encounter the same problem when trying to join hypixel. When I joined mineplex I could play minegames just fine.

**Comment by MateusL13** [comment]
> > Aarch32 doesn't have a ought ram to play on servers
> 
> Does PojavLauncher support aarch64 since more phones are using that and minecraft would be more stable on it. I also encounter the same problem when trying to join hypixel. When I joined mineplex I could play minegames just fine.

Thank you, I will try this.

**Comment by MichaelBest01** [comment]
> > > Aarch32 doesn't have a ought ram to play on servers
> > 
> > 
> > Does PojavLauncher support aarch64 since more phones are using that and minecraft would be more stable on it. I also encounter the same problem when trying to join hypixel. When I joined mineplex I could play minegames just fine.
> 
> Thank you, I will try this.

Just a heads up when I move around too much or swing my hand a lot in either singleplayer or multiplayer. My game crashes and takes me back to the launcher.

**Comment by WesleyVanNeck** [comment]
> > Aarch32 doesn't have a ought ram to play on servers
> 
> This makes no sense, because, if I put the same amount of RAM on my pc, I'll be able to play.
> And I can play on severs on another launcher on Android.

it does make sense as aarch32 only can get 300 on mb

**Comment by WesleyVanNeck** [comment]
> > > > Aarch32 doesn't have a ought ram to play on servers
> > > 
> > > 
> > > Does PojavLauncher support aarch64 since more phones are using that and minecraft would be more stable on it. I also encounter the same problem when trying to join hypixel. When I joined mineplex I could play minegames just fine.
> > 
> > 
> > Thank you, I will try this.
> 
> Just a heads up when I move around too much or swing my hand a lot in either singleplayer or multiplayer. My game crashes and takes me back to the launcher.

because your out of ram...

**Comment by WesleyVanNeck** [comment]
and yes aarch64 is suported so get a device that use that bam it fixed

**Comment by WesleyVanNeck** [comment]
also try to get this for me /storage/emulated/0/games/PojavLauncher/.minecraft/hs_err_pid31481.log

**Comment by WesleyVanNeck** [comment]
`java.lang.IllegalStateException: Invalid entity data item type for field 18 on entity bab['Cat'/553, l='ClientLevel', x=799.34, y=49.75, z=68.66]: old=2(class java.lang.Integer), new=false(class java.lang.Boolean)
	at uv.a(EntityDataManager.java:320) ~[uv.class:?]
	at uv.a(EntityDataManager.java:307) ~[uv.class:?]
	at dwu.a(SourceFile:568) ~[dwu.class:?]
	at ra.a(SourceFile:42) ~[ra.class:?]
	at ra.a(SourceFile:11) ~[ra.class:?]
	at ol.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[ol.class:?]
	at aob.c(ThreadTaskExecutor.java:191) [aob.class:?]
	at aof.c(SourceFile:23) [aof.class:?]
	at aob.y(ThreadTaskExecutor.java:153) [aob.class:?]
	at aob.bl(ThreadTaskExecutor.java:130) [aob.class:?]
	at djz.e(SourceFile:1015) [djz.class:?]
	at djz.e(SourceFile:681) [djz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]`

**Comment by MichaelBest01** [comment]
I have 8gb of ram on my phone I don't think I run out of ram. I am using 4 gb of ram right now.

**Comment by artdeell** [comment]
This looks like a Minecraft bug

**Comment by MichaelBest01** [comment]
![Screenshot_20210317-114520_My Files.jpg](https://user-images.githubusercontent.com/60488290/111496105-c2172f00-871e-11eb-8eb6-01ad32ee5cec.jpg)
There is no .minecraft

**Comment by MichaelBest01** [comment]
> `java.lang.IllegalStateException: Invalid entity data item type for field 18 on entity bab['Cat'/553, l='ClientLevel', x=799.34, y=49.75, z=68.66]: old=2(class java.lang.Integer), new=false(class java.lang.Boolean) at uv.a(EntityDataManager.java:320) ~[uv.class:?] at uv.a(EntityDataManager.java:307) ~[uv.class:?] at dwu.a(SourceFile:568) ~[dwu.class:?] at ra.a(SourceFile:42) ~[ra.class:?] at ra.a(SourceFile:11) ~[ra.class:?] at ol.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[ol.class:?] at aob.c(ThreadTaskExecutor.java:191) [aob.class:?] at aof.c(SourceFile:23) [aof.class:?] at aob.y(ThreadTaskExecutor.java:153) [aob.class:?] at aob.bl(ThreadTaskExecutor.java:130) [aob.class:?] at djz.e(SourceFile:1015) [djz.class:?] at djz.e(SourceFile:681) [djz.class:?] at net.minecraft.client.main.Main.main(SourceFile:215) [Main.class:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2] at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]`

What do I do with this?

**Comment by WesleyVanNeck** [comment]
> ![Screenshot_20210317-114520_My Files.jpg](https://user-images.githubusercontent.com/60488290/111496105-c2172f00-871e-11eb-8eb6-01ad32ee5cec.jpg)
> There is no .minecraft

1 that means you use aarch64 so get away from here two enebble hiden folders

**Comment by WesleyVanNeck** [comment]
> > `java.lang.IllegalStateException: Invalid entity data item type for field 18 on entity bab['Cat'/553, l='ClientLevel', x=799.34, y=49.75, z=68.66]: old=2(class java.lang.Integer), new=false(class java.lang.Boolean) at uv.a(EntityDataManager.java:320) ~[uv.class:?] at uv.a(EntityDataManager.java:307) ~[uv.class:?] at dwu.a(SourceFile:568) ~[dwu.class:?] at ra.a(SourceFile:42) ~[ra.class:?] at ra.a(SourceFile:11) ~[ra.class:?] at ol.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[ol.class:?] at aob.c(ThreadTaskExecutor.java:191) [aob.class:?] at aof.c(SourceFile:23) [aof.class:?] at aob.y(ThreadTaskExecutor.java:153) [aob.class:?] at aob.bl(ThreadTaskExecutor.java:130) [aob.class:?] at djz.e(SourceFile:1015) [djz.class:?] at djz.e(SourceFile:681) [djz.class:?] at net.minecraft.client.main.Main.main(SourceFile:215) [Main.class:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2] at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]`
> 
> What do I do with this?

not for you its for guy thate made this issue

**Comment by MichaelBest01** [comment]
> 1 that means you use aarch64 so get away from here two enebble hiden folders

I am also having the same problem and should I get the log?

**Comment by WesleyVanNeck** [comment]
> > 1 that means you use aarch64 so get away from here two enebble hiden folders
> 
> I am also having the same problem and should I get the log?

not the smae i belive as you can walk around so make a other issue

**Comment by WesleyVanNeck** [comment]
> > > 1 that means you use aarch64 so get away from here two enebble hiden folders
> > 
> > 
> > I am also having the same problem and should I get the log?
> 
> not the smae i belive as you can walk around so make a other issue

**Comment by MateusL13** [comment]
> > > Aarch32 doesn't have a ought ram to play on servers
> > 
> > 
> > This makes no sense, because, if I put the same amount of RAM on my pc, I'll be able to play.
> > And I can play on severs on another launcher on Android.
> 
> it does make sense as aarch32 only can get 300 on mb

You are wrong, my phone is aarch32 and I can play with 990 MB of RAM.

**Comment by WesleyVanNeck** [comment]
> > > > Aarch32 doesn't have a ought ram to play on servers
> > > 
> > > 
> > > This makes no sense, because, if I put the same amount of RAM on my pc, I'll be able to play.
> > > And I can play on severs on another launcher on Android.
> > 
> > 
> > it does make sense as aarch32 only can get 300 on mb
> 
> You are wrong, my phone is aarch32 and I can play with 990 MB of RAM.

not on latest dev build with auto ram  also you 2 guys are micing issue so i closed i didnt say your phone is aarch32 thats for other guy that repsonded

**Comment by MateusL13** [comment]
> > > > > Aarch32 doesn't have a ought ram to play on servers
> > > > 
> > > > 
> > > > This makes no sense, because, if I put the same amount of RAM on my pc, I'll be able to play.
> > > > And I can play on severs on another launcher on Android.
> > > 
> > > 
> > > it does make sense as aarch32 only can get 300 on mb
> > 
> > 
> > You are wrong, my phone is aarch32 and I can play with 990 MB of RAM.
> 
> not on latest dev build with auto ram also you 2 guys are micing issue so i closed i didnt say your phone is aarch32 thats for other guy that repsonded

Ok, but I have the latest build, I just deactivated the auto ram, anyway, thank you for try help me.
