### ISSUE TITLE
[F-REQ] Hello, in any next update there would be no way to make my device not get too hot and the battery drains less quickly?

### ISSUE THREAD

**Issue by Palotops** [PojavLauncherTeam/PojavLauncher#1025]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
Well, you should know, forcing to launch a program that was not intended for mobile should always do that.

**Comment by PeterScorPioN** [comment]
@Palotops i see that you don't khow how everything works, right? Which phone do you have?

**Comment by PeterScorPioN** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > **Describe the solution you'd like**
> > A clear and concise description of what you want to happen.
> > **Describe alternatives you've considered**
> > A clear and concise description of any alternative solutions or features you've considered.
> > **Additional context**
> > Add any other context or screenshots about the feature request here.
> 
> Well, i see that you don't how how everything works, right? Which phone do you have?

**Comment by rscAvePlex** [comment]
@Palotops Here are some few reason why your phone gets "hot" when playing

1. PojavLauncher uses ram, and so it updates the allocation in real-time
(For example, if you allocated 400MB, it updates real-time ranging from below 400mb and abovr 400mb.)

2. ~~It's not the phone getting hot nor the battery, the one's 'hot' is the CPU~~.

3. If you would sometimes say 'bruhh why pojav drains so quickly', the cpu also has a part of using the battery. ~~No cpu's have been reported yet to have a feature where it doesn't affect the device's battery~~
