### ISSUE TITLE
[BUG] PojavLauncher don't appear in Google Play

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1027]
### Describe the bug
When you search ''PojavLauncher or artdeell'' in Google Play don't appear nothing

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start Google Play
2. Search ''PojavLauncher or artdeell''

### Expected behavior:
I expected that the app should appear to donwload normaly

### Screenshots or videos:
No needed, just appear nothing related to PojavLauncher

**Platform:**
 - Device Model [Xiaomi Redmi]
 - CPU architecture [aarch32] 
 - Android Version [9]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by CriticalRange** [comment]
Type pub:artdeell, it will pop-up

**Comment by ghost** [comment]
But isn't supposed to be found more easily? I don't know, maybe more tags. If continues like this, will remain hidden in the store and greatly decrease the visibility of the app

**Comment by ghost** [comment]
I tested again and now appear, is fixed for now I think. Anyway good keep a eye in this problem
