### ISSUE TITLE
[F-REQ] VIVECRAFT SUPPORT FOR OCULUS QUEST 1/2

### ISSUE THREAD

**Issue by AWVR** [PojavLauncherTeam/PojavLauncher#1028]
the ability to use vivecraft with an modded apk of the app with an sdk like steamVR to run it natively on the quest 

could use an sdk such as open composite as an alternative to steamVR but only really need the modding part down to start with

would work with quest 1/2 

If interested in this my discord is AWVR #1010 so drop me a dm there if u can :)

**Comment by LionZXY** [comment]
This is idea really crazy... And awesome!

**Comment by Toothyy** [comment]
There can probably be a way to do this like how they got impact running all they need to do is put the set up launcher for vivecraft

**Comment by khanhduytran0** [comment]
This is very big task. Need to wrap everything at API.

**Comment by Toothyy** [comment]
Hmm Merde ok

**Comment by Toothyy** [comment]
Problem vivecraft is a exe file does that mean needing a laptop to set it up?

**Comment by tom300z** [comment]
AFAIK Vivecraft uses the OpenVR (SteamVR) Api, wich is not available for aarch64. This would probably require a vr compatible launcher that simulates the openvr api

**Comment by khanhduytran0** [comment]
Anyways this is not in our dev roadmap. Closing
