### ISSUE TITLE
Typing bug in chat, naming, etc.

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#103]
-When pressing @, [, ], etc. on the chat, it deletes the previous letter.

-When pressing _ on the chat, it deletes the previous letter, but if you press space, it doesn't delete

**Comment by FranzelDamasco909** [comment]
i found this bug while i was typing cheats on the chat

**Comment by Azapru** [comment]
Me too

**Comment by FranzelDamasco909** [comment]
It make me feel uncomfortable

**Comment by FranzelDamasco909** [comment]
please reply

**Comment by khanhduytran0** [comment]
> -When pressing @, [, ], etc. on the chat, it deletes the previous letter.
> -When pressing _ on the chat, it deletes the previous letter, but if you press space, it doesn't delete

Fixing.

**Comment by FranzelDamasco909** [comment]
sorry i thought you was offline... Take your time!

**Comment by khanhduytran0** [comment]
I'm unable to reproduce these in Minecraft 1.9. Could you tell me what version you got this problem?

**Comment by khanhduytran0** [comment]
It works fine on me (Gboard)

**Comment by khanhduytran0** [comment]
Let me check again...

**Comment by FranzelDamasco909** [comment]
It doesn't work properly when i use the keyboard on the phone

**Comment by khanhduytran0** [comment]
Checked in MC 1.9 still work normal. What version are you getting problem?

**Comment by khanhduytran0** [comment]
Already in chat and rename world still works as normal.

**Comment by FranzelDamasco909** [comment]
I'm using 1.11.2 and it doesn't work properly try not to use the external keyboard

**Comment by khanhduytran0** [comment]
I can't test in 1.11.2 since my device is not enough storage to install. Try use other keyboard...

**Comment by pedrosouzabrasil** [comment]
1.11.2 same bug.Tested on my note 10.Keyboard dont work.

**Comment by FranzelDamasco909** [comment]
> I can't test in 1.11.2 since my device is not enough storage to install. Try use other keyboard...

all of my keyboards is only supported on laptop and pc

**Comment by FranzelDamasco909** [comment]
and you need to clean your space

**Comment by issuereporter292** [comment]
> It doesn't work properly when i use the keyboard on the phone

Same when i use the keyboard none of the letters show up and i have to close out the keybosrd for every single letter. I use v1.9

**Comment by khanhduytran0** [comment]
> Same when i use the keyboard none of the letters show up and i have to close out the keybosrd for every single letter. I use v1.9

Try Gboard.

**Comment by FranzelDamasco909** [comment]
Oh wait i tried it in 1.11 but it doesn't work properly as same as 1.11.2

**Comment by khanhduytran0** [comment]
OK, but idk where to fix...

**Comment by khanhduytran0** [comment]
Try v3
