### ISSUE TITLE
[BUG] Silently cant login using Microsoft

### ISSUE THREAD

**Issue by cheloveg** [PojavLauncherTeam/PojavLauncher#1031]
### Cant login using Microsoft
When I logging with Microsoft account after login in browser account doesn't appear(btw i cant use offline account).

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Press "Microsoft Login"
3. Sing in Microsoft(browser closes and sends you back to launcher)
4. Nothing happens

**Comment by artdeell** [comment]
Try to:
1. download Firefox
2. Log in with it
3. When your page becames empty and URL changes to ms-xal-.... press "Open with an associated application"

**Comment by cheloveg** [comment]
I managed to login, i was using firefox, but when you logging in, you should press "..." > Open in browser and when in opens as tab in browser you should login
