### ISSUE TITLE
Hitting a mob losing texture 😭

### ISSUE THREAD

**Issue by sreyaspopz** [PojavLauncherTeam/PojavLauncher#1032]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Hit a mob los texture

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6115841/latestlog.txt)

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Loading world
3. Hitting A mob lost texture
4. Lol
.

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
@sreyaspopz fill da template

**Comment by khanhduytran0** [comment]
(Send latestlog.txt)

**Comment by sreyaspopz** [comment]
[Uploading latestlog.txt…]()

**Comment by khanhduytran0** [comment]
You’re too fast. It was not yet uploaded.

**Comment by sreyaspopz** [comment]
[Uploading latestlog.txt…]()

**Comment by sreyaspopz** [comment]
That file not uploading 😔

**Comment by sreyaspopz** [comment]
I edited bug report

**Comment by khanhduytran0** [comment]
You need to wait until “Uploading” disappears.

**Comment by sreyaspopz** [comment]
Ok

**Comment by khanhduytran0** [comment]
You need to go back to GL4ES 1.1.4 as noted in README.md.

**Comment by khanhduytran0** [comment]
Also, using email for username is not a good idea.

**Comment by sreyaspopz** [comment]
[Uploading latestlog.txt…]()

**Comment by sreyaspopz** [comment]
> You need to go back to GL4ES 1.1.4 as noted in README.md.

What's that

**Comment by sreyaspopz** [comment]
Please solve that bro

**Comment by khanhduytran0** [comment]
Try add to jvm arguments
`-Dorg.lwjgl.opengl.libname=libgl4es_114.so`

**Comment by sreyaspopz** [comment]
Ok bro

**Comment by sreyaspopz** [comment]
Nothing happens 😔

**Comment by khanhduytran0** [comment]
Try remove the banner fix argument.

**Comment by sreyaspopz** [comment]
Nothing happens 😔 i tried first but not work

**Comment by khanhduytran0** [comment]
but it should work, remove all arguments..

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer from author
Closing
