### ISSUE TITLE
[F-REQ] + Tags for PojavLauncher (Google Play)

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1033]
**Is your feature request related to a problem? Please describe.**

Kind that yes, because decreases very much the visibility

**Describe the solution you'd like**

A more detailed description, more prints and tags can help the app be more engaged into the store

**Describe alternatives you've considered**

Perhaps the use of key tags, as most searched can help

**Additional context**

My suggestions of tags:
Pojav, MC Launcher, MC, MC PC, MC Java, Launcher, Mine, Craft, Java and MC Mods

**Comment by khanhduytran0** [comment]
It will probably gives a reject as usual.
