### ISSUE TITLE
[BUG] PojavLauncher (Google Play) Broken

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1034]
### Describe the bug
I can download and install the app normally in the store, but after install a version in the launcher and press 'Play' a black screen appear, a box with how many memory have allocated too and then crash (don't have a crash log in the folder)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Keep all standard configs
3. Download a version (1.12.2)
4. Press Play

### Expected behavior:
I expected that could load and play normally

**Platform:**
 - Device Model [Redmi]
 - CPU architecture [aarch32] 
 - Android Version [9]
 - PojavLauncher Version [Latest Release in Google Play]

**Comment by khanhduytran0** [comment]
Send latestlog.txt
