### ISSUE TITLE
[BUG] Not download sounds! 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1038]
The launcher is not downloading sounds to `games/PojavLauncher/.minecraft/resources` the game appears without sounds, music, any type of audio the game does not emit, it is muted! 

My Configs:
- Phone: Samsung Galaxy A01
- OS: Android 10
- Memory: 2 GB RAM/Storage: 32 GB 
- Processor:4x 1.95 GHz Cortex-A53 + 4x 1.45 GHz Cortex-A53
- Chipset: Snapdragon 439 Qualcomm SDM439 
- GPU: Adreno 505

**Comment by heroic-br** [comment]
Use

**Comment by OksmaWarez** [comment]
The Old versions sounds don't work because the resources were moved to another server. If you still want sounds, go [here](https://betacraft.pl/en-US/serverproxy.html)

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
