### ISSUE TITLE
I can't install impact keep Crashing 😔

### ISSUE THREAD

**Issue by sreyaspopz** [PojavLauncherTeam/PojavLauncher#1039]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6127165/latestlog.txt

1. Start PojavLauncher
2. Open mod install
3. Select impact.jar file
4. Crashing pojavluncher
5. Lol😔

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Impact installer keep Crashing 😔 please fix that bro
</pre>
</details>

**Comment by sreyaspopz** [comment]
Please someone solve that 😭

**Comment by CriticalRange** [comment]
Try putting the impact folder into sdcard/games/PojavLauncher

**Comment by khanhduytran0** [comment]
Closed because of no response from @sreyaspopz
