### ISSUE TITLE
fps decreased when I started Launcher

### ISSUE THREAD

**Issue by ShiromcID** [PojavLauncherTeam/PojavLauncher#104]
pojav launcher menjalankan 2fps saat saya memainkan peluncur minecraft di android saya

**Comment by artdeell** [comment]
English please

**Comment by artdeell** [comment]
@ShiromcID 
ni adalah alasan mengapa fps rendah:
1. Ponsel Anda sudah tua
2. Ponsel Anda adalah Samsung baru dengan CPU Exynos (ada beberapa masalah optimisasi)
3. Anda baru saja menemukan cacat peluncur baru.

Silakan kirim model ponsel Anda, versi Android, nama GPU dan versi OpenGL ES, dan (jika Anda memiliki akses root)  logcat log dari PojavLauncher.

**Comment by artdeell** [comment]
Anda memeriksa versi OpenGL ES Anda dalam aplikasi bernama AIDA64, Logcat log dapat diperiksa menggunakan aplikasi yang disebut Logcat Extreme. Keduanya dapat diunduh di Play Market.

**Comment by khanhduytran0** [comment]
> pojav launcher menjalankan 2fps saat saya memainkan peluncur minecraft di android saya

Check your cpu.
