### ISSUE TITLE
[F-REQ] 21w10a play fixed in Pojavlauncher soon?

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1040]
21w10a fix soon in Pojavlauncher?

**Comment by ENDERMANYK** [comment]
Please be patient bro, it will take a lot of time, if it can be fixed then a few PC Shader will works on your phone.

**Comment by OwzygZawg** [comment]
Thanks for your information!

**Comment by OwzygZawg** [comment]
Thanks for your information!

**Comment by OwzygZawg** [comment]
Thanks for your information!

**Comment by WesleyVanNeck** [comment]
There is no eta for it also don't spam the issue tracker
