### ISSUE TITLE
[BUG] <Game crashes as soon as i click play

### ISSUE THREAD

**Issue by GreenNinja00** [PojavLauncherTeam/PojavLauncher#1041]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
The game crashes as soon as i click on play

**Add a log file if you want to see your bug fixed !**

[Log.txt file](https://drive.google.com/file/d/1fXetSSwU1eWgXndg9uxdIcNWW-heYXMh/view?usp=drivesdk) 

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2.Install 1.8.9
3.Click on play
4.see the error

### Expected behavior:
game should run

### Screenshots or videos:

https://user-images.githubusercontent.com/76276190/110910544-843d9380-8337-11eb-9c92-37b40af48e92.mp4

**Platform:**
 - Device Model Lg stylus 3
 - CPU architecture aarch32
 - Android Version 7
 - PojavLauncher Version 3.3.1.1

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by EXPress-016** [comment]
Delete 1.8.9 folder from versions folder

**Comment by GreenninjaGamingyt** [comment]
> Delete 1.8.9 folder from versions folder
Already tried

**Comment by GreenNinja00** [comment]
> Delete 1.8.9 folder from versions folder

Already tried

**Comment by SpheeresX** [comment]
Same issue here. The app works just fine on my phone but not on my Chromebook.

**Comment by khanhduytran0** [comment]
@GreenninjaGamingyt 32bit can’t allocate too much ram
