### ISSUE TITLE
[BUG] Sensitivity is too low

### ISSUE THREAD

**Issue by chfwd** [PojavLauncherTeam/PojavLauncher#1042]
When I entered the game, the sensitivity of the mouse was too low.  Even if I set the sensitivity setting in Minecraft to the maximum.  , It is still very difficult to rotate the angle. Please fix it, thanks.

(Use Google Translate to translate, if there is something wrong, please forgive me. Thank you.)

**Comment by 88HeilHitler** [comment]
Use the game settings, there is a config for u to change the sensitivity of the mouse.

**Comment by WesleyVanNeck** [comment]
> When I entered the game, the sensitivity of the mouse was too low. Even if I set the sensitivity setting in Minecraft to the maximum. , It is still very difficult to rotate the angle. Please fix it, thanks.
> 
> (Use Google Translate to translate, if there is something wrong, please forgive me. Thank you.)

use the setings in the launcher it self

**Comment by WesleyVanNeck** [comment]
also follow the issue template

**Comment by Amongboy** [comment]
I cant launch snapshot 21w10a cause i need opengl 3.2

**Comment by CriticalRange** [comment]
@Amongboy wait for it

**Comment by sougugao** [comment]
hi, in my pojav there is a problem with the mouse and the camera, i will try to move the camera and it keeps locking even though i have about 60 fps, i have already left the sensitivity at maximum and it didn’t work, With mouse same thing, please correct this error.

**Comment by Mathias-Boulay** [comment]
Mouse sensitivity is now a setting on google play.
Closing

**Comment by kimsmith65** [comment]
the sensitivity is too low can't play pvp properly...

**Comment by rscAvePlex** [comment]
wtf

**Comment by kimsmith65** [comment]
This is the worst, they cant fix the problem this suckss......

**Comment by khanhduytran0** [comment]
> This is the worst, they cant fix the problem this suckss......

@kimsmith65 we aren't rich enough to buy a device just to fix a bug!

**Comment by khanhduytran0** [comment]
@kimsmith65 reply? Do you have money?

**Comment by rscAvePlex** [comment]
> This is the worst, they cant fix the problem this suckss......

can you shut the fuck up
if they can't fix it then fix it yourself ffs
