### ISSUE TITLE
[BUG] a lot of problem with recent versions (1.13+)

### ISSUE THREAD

**Issue by Derman447** [PojavLauncherTeam/PojavLauncher#1043]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I have two problems with recent Minecraft versions (1.13+) 1. I cannot launch the game with fabric otherwise my game crashes with code 1 ... 2. There are massive lags with these versions so I have to play on 1.12- and I find that a real shame ... 

**Platform:**
 - Model: Alcatel
 - CPU architecture: ARMv7
 - Android Version: 10
 - PojavLauncher Version: version 3.3.1.1_rel_20210206

**Comment by WesleyVanNeck** [comment]
reason your using a Alcatel phone those are pure trash also about fabric without latest log file no help

**Comment by khanhduytran0** [comment]
inactivity
