### ISSUE TITLE
[BUG] 1.13+ Worked but 1.7.10 Crashed

### ISSUE THREAD

**Issue by Nintendomakell** [PojavLauncherTeam/PojavLauncher#1044]
### Describe the bug
Well I played 1.7.10 and it was working i was getting 100+ FPS and it seems to be fine. but once I played for a while it crashed. so I try 1.16.5 and it was not crashing.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6134338/latestlog.txt)

### To Reproduce:
1. Start PojavLauncher
2. Play 1.7.10 and start world
3. Play for a while
4. Crash

### Expected behavior:
idk Maybe GLFW stub worked better for me? (Also I try mcinabox and it seems that 1.7.10 work and it not crashing)

**Platform:**
 - Device Model KFMAWI (maverick)
 - CPU architecture armv8I
 - Android Version 9
 - PojavLauncher Version [Google Play version]

**Comment by Nintendomakell** [comment]
Maybe GLFW stub worked better for me?

**Comment by Nintendomakell** [comment]
Can someone help me?

**Comment by khanhduytran0** [comment]
Can you send /storage/emulated/0/games/PojavLauncher/.minecraft/hs_err_pid9834.log?

**Comment by Nintendomakell** [comment]
Sorry for the waiting. But no log in .minecraft. it just takes me back to the pojavlauncher login in screen.

**Comment by khanhduytran0** [comment]
Enable VBO :eyes:

**Comment by RiDDeR31** [comment]
> Enable VBO 👀

What's vbo? I have the same problem and can't find a way to fix it

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build BY THE POWER OF HOLY4ES
