### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BigBotoDaddy** [PojavLauncherTeam/PojavLauncher#1045]
Dont work GUI litematica fabric 1.16.5/1.16.4
Video: https://www.mediafire.com/file/jceyo1lvllx27lg/SVID_20210313_103047_1.mp4/file
Please help me open GUI litematic

**Comment by pablodz** [comment]
Video re-uploaded to Github to easy read

https://user-images.githubusercontent.com/28235457/112706299-5e54da80-8e71-11eb-8a21-db97e025b3ee.mp4

But, fill the template. Devs can't just guess the error, fill the template XD
