### ISSUE TITLE
[BUG] Can't type @

### ISSUE THREAD

**Issue by TrixTM** [PojavLauncherTeam/PojavLauncher#1047]
### Describe the bug
When I type @ the twitch broadcast appears on the screen and I can't type that symbol
**Add a log file if you want to see your bug fixed !**
Nothing helpful appears on the logs

### To Reproduce:
1. Start PojavLauncher on version 1.8.9 and type @ in chat but you can't because it will appear on the screen the twitch broadcast thing

### Expected behavior:
I expected to type @ in chat but I can't

### Screenshots or videos:
**Platform:**
 - Device Model [s10 plus 8/128]
 - CPU architecture [aarch64] 
 - Android Version [11]
 - PojavLauncher Version [Latest Release version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
So what’s your using keyboard?

**Comment by TrixTM** [comment]
Default samsung keyboard. The problem is the minecraft twitch broadcast, not my keyboard

**Comment by khanhduytran0** [comment]
Try gboard...

**Comment by TrixTM** [comment]
ok, the keyboard was the problem. I used hacker keyboard and it worked. But can you fix the problem with samsung keyboard?

**Comment by khanhduytran0** [comment]
But why you need Samsung keyboard?

**Comment by TrixTM** [comment]
Because it's the default keyboard. and i tried another keyboard and i can press @ but i still can't type it in chat and i can't log into servers

**Comment by ghost** [comment]
just write dog no @

**Comment by mchnjt** [comment]
> Because it's the default keyboard. and i tried another keyboard and i can press @ but i still can't type it in chat and i can't log into servers

~~weak asf don't use those~~

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
