### ISSUE TITLE
[BUG] when I connect a mouse and keyboard the keyboard does not work for example when I press the W A S and D keys I do not move at all. So hopefully you can make this keyboard compatible

### ISSUE THREAD

**Issue by Blaine7845** [PojavLauncherTeam/PojavLauncher#1048]
[BUG] when I connect a mouse and keyboard the keyboard does not work for example when I press the W A S and D keys I do not move at all. So hopefully you can make this keyboard compatible

**Comment by EnderBrine99FOX** [comment]
> [BUG] when I connect a mouse and keyboard the keyboard does not work for example when I press the W A S and D keys I do not move at all. So hopefully you can make this keyboard compatible

You Need To Change Your Keyboard To A Keyboard That Support Mouse And Keyboard I Use Sixaxis Controller Keyboard To Play Pojavlauncher If You Need More Help Watch This Video Maybe It Will Help You https://youtu.be/RSCFoP_2Fy0

**Comment by Mathias-Boulay** [comment]
Duplicate from #783 
Closing the issue.
