### ISSUE TITLE
[BUG] w[BUG] when I connect a mouse and keyboard the keyboard does not work for example when I press the W A S and D when are you say connected Mouse sometimes I cannot stop left clicking and it's not because of the mouse because when I disconnect the game still left clicks

### ISSUE THREAD

**Issue by Blaine7845** [PojavLauncherTeam/PojavLauncher#1049]
[BUG] when I connect a mouse and keyboard the keyboard does not work for example when I press the W A S and D when are you say connected Mouse sometimes I cannot stop left clicking and it's not because of the mouse because when I disconnect the game still left clicks

**Comment by OksmaWarez** [comment]
dupe #1048
