### ISSUE TITLE
[Question] PRI/SEC button behaviour

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#105]
Since Boardwalk ( thinked that buttons are equivalent to left and right mouse buttons, and they're triggering that mouse events on controls settings and in-game, but for some reason i can't click on ingame GUI buttons using this.. buttons???
If you know how to fix that, please fix it. It would be really cool if users will be able to scroll bars by holding PRI and moving mouse!

**Comment by khanhduytran0** [comment]
> It would be really cool if users will be able to scroll bars by holding PRI and moving mouse!

I know how to fix, OK! Current you can temporary use this method https://youtu.be/wzkVMtp7SBw

**Comment by khanhduytran0** [comment]
I tried 
```
case R.id.control_secondary:
				if (AndroidDisplay.grab) {
					sendMouseButton(1, isDown);
				} else {
					if (!isDown) {
						AndroidDisplay.putMouseEventWithCoords(/* right mouse */ (byte) 1, (byte) 0, AndroidDisplay.mouseX, AndroidDisplay.mouseY, 0, System.nanoTime());
						AndroidDisplay.putMouseEventWithCoords(/* right mouse */ (byte) 1, (byte) 1, AndroidDisplay.mouseX, AndroidDisplay.mouseY, 0, System.nanoTime());
					}
					setRightOverride(isDown);
				} break;
```

But seems like not work.
