### ISSUE TITLE
[BUG] <I Can't ignore Notch On My Device😑>

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#1052]
Notch Is Very Annoying Me And I Can't Disable it Form Pojavlauncher

My Pojavlauncher POV:
![Screenshot_20210309_002339_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/111054912-785de880-8481-11eb-9ae7-bd6418e0bc3f.jpg)

![Screenshot_20210312_101233_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/111054939-af33fe80-8481-11eb-92e6-18b66053ef4f.jpg)

My Device INFO:
Android 9
Huawei Nova 3i
4RAM

**Comment by Slapp13** [comment]
do you not have this feature?
![Screenshot_20210315-070533](https://user-images.githubusercontent.com/79562074/111089117-03f87780-855d-11eb-9baa-c64bc8306360.png)

**Comment by EnderBrine99FOX** [comment]
> do you not have this feature?
> ![Screenshot_20210315-070533](https://user-images.githubusercontent.com/79562074/111089117-03f87780-855d-11eb-9baa-c64bc8306360.png)

No, This Option Not Showing On My Device

**Comment by OksmaWarez** [comment]
> > do you not have this feature?
> > ![Screenshot_20210315-070533](https://user-images.githubusercontent.com/79562074/111089117-03f87780-855d-11eb-9baa-c64bc8306360.png)
> 
> No, This Option Not Showing On My Device

Update PojavLauncher from [here](https://github.com/PojavLauncherTeam/PojavLauncher/actions/)

**Comment by khanhduytran0** [comment]
@EnderBrine99FOX

**Comment by Mathias-Boulay** [comment]
@EnderBrine99FOX future builds are now fixed

**Comment by WesleyVanNeck** [comment]
clsoing this as fixed

**Comment by EnderBrine99FOX** [comment]
![Screenshot_20210413_183240_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/114579974-16162480-9c87-11eb-8893-417d569f3605.jpg)
@khanhduytran0  Thank You For Taking Care About That! Now Its Work Probably

**Comment by ProWillSting** [comment]
How do I get ignore notch please

**Comment by khanhduytran0** [comment]
> How do I get ignore notch please

@ProWillSting Update to latest v3 dev build. On play store build, there is a bug causes ignore notch option hidden on android 9.

**Comment by Jagger24x24** [comment]
I don't have ignore notch option on Google pixel 6 with android 13

**Comment by NotAHero04** [comment]
> I don't have ignore notch option on Google pixel 6 with android 13

Your phone doesn't have a notch lmfao 🤣

**Comment by mchnjt** [comment]
> 

@Jagger24x24 Punchole displays aren't considered notches...
