### ISSUE TITLE
[BUG] Tatar localization files

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [PojavLauncherTeam/PojavLauncher#1054]
In [Crowdin project](https://crowdin.com/project/pojavlauncher) PojavLauncher has Tatar language, but that language didn't added in GitHub files.
Lang code: tt_RU

**Comment by bot432** [comment]
Oh

**Comment by khanhduytran0** [comment]
@Amirhan-Taipovjan-Greatest-I new translation is at `l10n-v3-openjdk` branch.
