### ISSUE TITLE
[BUG] i cant play Minecraft 1.12 forge 

### ISSUE THREAD

**Issue by bot432** [PojavLauncherTeam/PojavLauncher#1055]
it keeps exiting with code 1 

-->I tried it again many times but it failed (using forge on the official website)
>http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.html
-I click "Installer" Recommended
**Platform:**
 - Device Model [Nokia 5.1 Plus]
 - CPU architecture [ aarch64] 
 - Android Version [9.0]
 - PojavLauncher Version [3.3.1.1_rel_20210314]

**Comment by bot432** [comment]
> it keeps exiting with code 1
> 
> -->I tried it again many times but it failed (using forge on the official website)
> 
> **Platform:**
> 
> * Device Model [Nokia 5.1 Plus]
> * CPU architecture [ aarch64]
> * Android Version [9.0)
> * PojavLauncher Version []

**Comment by khanhduytran0** [comment]
> Fill the template
