### ISSUE TITLE
[F-REQ] Keyboard support

### ISSUE THREAD

**Issue by Azkun** [PojavLauncherTeam/PojavLauncher#1056]
**Is your feature request related to a problem? Please describe.**
I think yes, i'm using a program that is "local" hosting a my pc keyboard to use it on my phone

**Describe the solution you'd like**
It's like a basic Android Keyboard but it doesn't work, it's work only with the special keys (i tryed like ESPACE = back and it worked, but other things like WASD doesnt work at all)

**Describe alternatives you've considered**
idk 

**Additional context**
i'm actually french so i didnt tape all correctly so sorry for my bad english

**Comment by khanhduytran0** [comment]
So, try go to control settings

**Comment by Mathias-Boulay** [comment]
Stale issue, for something that already works (physical keyboard works, although with some bugs, see respective issues for that)

Closing the issue.
