### ISSUE TITLE
Every time the game freeze the game keep crashing.

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#1057]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I'm playing Vic's Modern Warfare Mod then suddenly the game freeze and crashed

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6136774/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Choose 1.12.2-forge-14.23.5.2854
3. Loading...
4. Create a World
5. Open inv choose a gun
6. The game freeze
7. Last it crashed

### Expected behavior:
I expected the game will run smoothly, no freezing and no crashing.

**Platform:**
 - Device Model OPPO A12e/CPH1853
 - CPU architecture 64-bit
 - Android Version 8.1
 - PojavLauncher Version latest build
 - RAM Used 1000MB
 - RAM 3GB
 - GPU Andreno 506/Qualcomm SDM 450 Octa-Core

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by LanceAldrei04** [comment]
Is Vic's Modern Warfare Mod is a Big ModPack that cause the game freezing?

**Comment by khanhduytran0** [comment]
The mod is likely corrupted..
