### ISSUE TITLE
[BUG] Unable to Launch Fabric Instance

### ISSUE THREAD

**Issue by LePichu** [PojavLauncherTeam/PojavLauncher#1058]
### Description:
Pojav Launcher is unable to launch any Fabric Instances and just says "Game Exited" on unable to launch game.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Make a Fabric Instance
3. Launch the Fabric Instance

Expected Behavior: 
The game should remap the jar and launch without any issues.

Logs: https://gist.github.com/LePichu/2e7c6766f52ece182477771aae8f8dd0

**Platform:**
 - Device Model: Nubia Z11 Mini 
 - CPU architecture: Kyro Architecture (Snapdragon 625)
 - Android Version: 6/Marshmallow
 - PojavLauncher Version: Latest Release on Play Store

**Comment by khanhduytran0** [comment]
Known issue. However there is a workaround:
- Go to `/storage/emulated/0/games/PojavLauncher/.minecraft/.fabric/remappedJars/minecraft-1.16.5/`
- Rename `zipfstmp2471543556987845158.tmp` to `intermediary-fabric-loader-0.11.3-1.16.5.jar`
- Launch Fabric again.

**Comment by LePichu** [comment]
> Known issue. However there is a workaround:
> 
> * Go to `/storage/emulated/0/games/PojavLauncher/.minecraft/.fabric/remappedJars/minecraft-1.16.5/`
> * Rename `zipfstmp2471543556987845158.tmp` to `intermediary-fabric-loader-0.11.3-1.16.5.jar`
> * Launch Fabric again.

Thank you, it works like a charm now.
![Uploading IMG_20210315_085249.jpg…]()
