### ISSUE TITLE
[BUG] Chlorine mod keep crashing when it enters the world.

### ISSUE THREAD

**Issue by Slapp13** [PojavLauncherTeam/PojavLauncher#1059]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Yeah you know Chlorine mod is the same as Sodium but for forge. When it entered the world, it was force close.

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6137861/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Open 1.16.5 forge version
3. Enter the world
4. Crashing!

### Expected behavior:
I expected i can use this mod, so give more fps for the forge loader.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

https://user-images.githubusercontent.com/79562074/111088126-43709500-8558-11eb-83d6-38705db1a9af.mp4

**Platform:**
 - Device Sony Xperia XZ2
 - CPU aarch64 Snapdragon 845
 - Android 10
 - PojavLauncher [GooglePlay Version]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by PeterScorPioN** [comment]
Yes, same for me.

**Comment by khanhduytran0** [comment]
Maybe try on latest build?

**Comment by Slapp13** [comment]
> Maybe try on latest build?

I already v3.3.1.1 is that the latest build?

**Comment by Mateus13000** [comment]
> Read before submit
> ### Describe the bug
> Yeah you know Chlorine mod is the same as Sodium but for forge. When it entered the world, it was force close.
> 
> **Add a log file if you want to see your bug fixed !**
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6137861/latestlog.txt)
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> 2. Open 1.16.5 forge version
> 3. Enter the world
> 4. Crashing!
> 
> ### Expected behavior:
> I expected i can use this mod, so give more fps for the forge loader.
> 
> ### Screenshots or videos:
> _Upload here screenshots or videos of the buggy behavior, if possible._
> 
>  Tak.berjudul.162_540p.mp4 
> **Platform:**
> 
> * Device Sony Xperia XZ2
> * CPU aarch64 Snapdragon 845
> * Android 10
> * PojavLauncher [GooglePlay Version]
> 
> Additional context

Same to me, even with the original sodium on fabric, this happens

**Comment by MateusL13** [comment]
Same to me, even with the original sodium on fabric, this happens

**Comment by Slapp13** [comment]
Please, how to fix it?

**Comment by PeterScorPioN** [comment]
> Same to me, even with the original sodium on fabric, this happens

In sodium the bug is in video settings, at least for me. If your minecraft starts normally with sodium and crashes when you enter a world, then try flicking some options in the video settings and select OpenGl 2.0

**Comment by khanhduytran0** [comment]
Haven't you disabled these?
- [ ] Compact vertex format
- [ ] Fog occlusion

**Comment by Slapp13** [comment]
![Screenshot_20210319-193455](https://user-images.githubusercontent.com/79562074/111780903-9ba5ef00-88ea-11eb-8334-d8d02f1ef5af.png)
chlorine setting is different with sodium setting. its like normal vanilla setting.

**Comment by PeterScorPioN** [comment]
> ![Screenshot_20210319-193455](https://user-images.githubusercontent.com/79562074/111780903-9ba5ef00-88ea-11eb-8334-d8d02f1ef5af.png)
> chlorine setting is different with sodium setting. its like normal vanilla setting.

What about Chlorine, i think it is not supported by our mobile graphics cards, or maybe it needs a higher OpenGl. These may be the reasons...

**Comment by Blobanium** [comment]
So I'm having the same issue, I looked further into this and it seems to be something to do with the OS as it looks like crashes are being reported from the app (as you can see below)

![Screenshot_20210330-220053_Device care.png](https://user-images.githubusercontent.com/45613796/113092804-9034ac80-91a3-11eb-914a-b5b705b032e1.png)

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
