### ISSUE TITLE
[Request] Transferrable files

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#106]
Add a feature that makes launcher files transfer to the other path of a folder

**Comment by khanhduytran0** [comment]
Maybe OK.

**Comment by khanhduytran0** [comment]
But not yet implemented in v3.

**Comment by Mathias-Boulay** [comment]
Given the path android is going (restricting path with scoped storage), we won't work on this feature.
