### ISSUE TITLE
[BUG] <No crash information flashback>

### ISSUE THREAD

**Issue by myxiaomo** [PojavLauncherTeam/PojavLauncher#1061]
Can the official repair the loophole of flash back without any error! The same flaw lies in version 1.7.10. I flashed back after 23 seconds when I entered the archive, and I crashed after 3 seconds when I became a vampire. This is very annoying. Please fix it

**Comment by khanhduytran0** [comment]
@myxiaomo please fill da template.

**Comment by myxiaomo** [comment]
> @myxiaomo请填写da模板。

？？？

**Comment by ENDERMANYK** [comment]
> > @myxiaomo请填写da模板。
> 
> ？？？

用那个模板格式把你的问题写清楚，如果不清楚那就把sdcard/0/games/Pojavlauncher/latestlog.txt发过来

**Comment by myxiaomo** [comment]
> > > @myxiaomo请填写da模板。
> > 
> > 
> > ？？？
> 
> 用那个模板格式把你的问题写清楚，如果清楚那就把sdcard / 0 / games / Pojavlauncher / latestlog.txt发过来

I can't do it

**Comment by myxiaomo** [comment]
> > > @myxiaomo请填写da模板。
> > 
> > 
> > ？？？
> 
> 用那个模板格式把你的问题写清楚，如果清楚那就把sdcard / 0 / games / Pojavlauncher / latestlog.txt发过来

You're the last little shadow, right

**Comment by myxiaomo** [comment]
> > > @myxiaomo请填写da模板。
> > 
> > 
> > ？？？
> 
> 用那个模板格式把你的问题写清楚，如果清楚那就把sdcard / 0 / games / Pojavlauncher / latestlog.txt发过来

https://wws.lanzous.com/iXTjZmzwy3g

Password: eb8j

**Comment by myxiaomo** [comment]
> > > @myxiaomo请填写da模板。
> > 
> > 
> > ？？？
> 
> 用那个模板格式把你的问题写清楚，如果清楚那就把sdcard / 0 / games / Pojavlauncher / latestlog.txt发过来

https://wws.lanzous.com/iXTjZmzwy3g

Password: eb8j

**Comment by khanhduytran0** [comment]
@myxiaomo your phone does not hold a PC GPU to run shaders, you know....
Use open4es instead
