### ISSUE TITLE
[BUG] <game crash>

### ISSUE THREAD

**Issue by RayaneMC** [PojavLauncherTeam/PojavLauncher#1062]
Hi i tried to play the version down of 1.10 and if i do a New world the game crash and the snapshots up from 21w08b the game crash at mojang studios logo please can you fix that

**Comment by khanhduytran0** [comment]
@RayaneMC Fill da template :eyes:

**Comment by Mathias-Boulay** [comment]
Stale issue with no template filled.
Closing the issue.
