### ISSUE TITLE
[BUG] MrCrayfish's Gun Mod 1.16.5

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#1063]
MrCrayfish's Gun Mod aim problem on 1.16.5. I click and hold on sec button but it did not aim.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6141623/latestlog.txt)

**Comment by khanhduytran0** [comment]
Fill the template :eyes:

**Comment by LanceAldrei04** [comment]
Your template is too hard to understand because I can't full understand English. I am Filipino I can't understand some english words sorry.

**Comment by LanceAldrei04** [comment]
Do you understand Filipino/Tagalog? If you can I will fill the template with Filipino words.

**Comment by Druxelite** [comment]
> Your template is too hard to understand because I can't full understand English. I am Filipino I can't understand some english words sorry.

Imagine not listening to english lectures

**Comment by khanhduytran0** [comment]
> Do you understand Filipino/Tagalog? If you can I will fill the template with Filipino words.

@lalalalalalalalalalalalalalalalalala000 no devs understand Filipino. So if we create one, we can't help anyways.

**Comment by netkv** [comment]
there is one nice website called "google translate", so if you dont know english, you can use that

**Comment by Mathias-Boulay** [comment]
#1948
