### ISSUE TITLE
[BUG] Dosen't let make a world and join servers

### ISSUE THREAD

**Issue by nooxgaming21** [PojavLauncherTeam/PojavLauncher#1066]
When i press create a new world nothing happens
When i add a server it shows that it's not online and can't join

**Comment by ebuild-1** [comment]
Might be invalid server, try adding this server (play.mine-smp.me) it works for me. and other servers too.

**Comment by khanhduytran0** [comment]
@nooxgaming21 fill da template
> When i press create a new world nothing happens

as your device probably too slow
