### ISSUE TITLE
banners problem

### ISSUE THREAD

**Issue by XTUG25** [PojavLauncherTeam/PojavLauncher#1067]
banners is not showing colors just white

**Comment by khanhduytran0** [comment]
@XTUG25 haven't you read README.md?
https://github.com/PojavLauncherTeam/PojavLauncher#known-issues

**Comment by khanhduytran0** [comment]
> - in 1.16 and up spawn eggs banners are white (you can fix this by adding this to your JVM flags 
> `-Dorg.lwjgl.opengl.libname=libgl4es_115.so`, only works on 1.16 and up, do not use under this version)
