### ISSUE TITLE
Older versions than 1.4 are broken

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#107]
The older versions are broken i don't know what to do

**Comment by khanhduytran0** [comment]
Send F11 keycode.

**Comment by khanhduytran0** [comment]
Full screen will solve the problem.

**Comment by FranzelDamasco909** [comment]
okay it worked! thank you

**Comment by FranzelDamasco909** [comment]
1.3 doesn't work it's just blank screen

**Comment by khanhduytran0** [comment]
> 1.3 doesn't work it's just blank screen

1.3 to 1.5 will not run.

**Comment by Azapru** [comment]
Why?

**Comment by khanhduytran0** [comment]
Idk, it didn't leave any logs about error, so I can't fix it.

**Comment by khanhduytran0** [comment]
> okay it worked! thank you

Closing!
