### ISSUE TITLE
1.16.5 Forge (game exit with code 1)

### ISSUE THREAD

**Issue by Anseryde** [PojavLauncherTeam/PojavLauncher#1072]
Every time I try to install a 1.16.5 version of Forge, it gets stuck on the log, and when I force close then look at latestlog.txt, "install successful" cannot be seen. When I attempt to open Minecraft forge version 1.16.5, it almost immediately crashes with the message "game exit with code 1".
Device: Oppo Reno Z
Version: Pojavlauncher 3.3.1.1
Forge version: forge-1.16.5-36.1.0

**Comment by khanhduytran0** [comment]
@Anseryde send latestlog.txt

**Comment by khanhduytran0** [comment]
> e, it gets stuck on the log, and when I force close then look at latestlog.txt

You need to wait until installer crashes or dialog “install successful” appears.
