### ISSUE TITLE
[BUG] FORGE NOT INSTALLING

### ISSUE THREAD

**Issue by ASGAMING009** [PojavLauncherTeam/PojavLauncher#1073]
Whenever i install forge for 1.12.2 its crashes and main menu pops up.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6157694/latestlog.txt)

**Comment by Eutamashi** [comment]
Happend to me too

**Comment by khanhduytran0** [comment]
Who forced you to use **universal** instead of **installer**?

**Comment by khanhduytran0** [comment]
@ASGAMING009 @Eutamashi ?
