### ISSUE TITLE
[F-REQ] Actions Playable

### ISSUE THREAD

**Issue by gabbosta** [PojavLauncherTeam/PojavLauncher#1074]
Hello, I really like the Launcher and version 3.3.1.1 is not very up to date, and so I often download only the Actions versions, but some don't work, so I would like to suggest to you in every action that you can play with a name like "playable update [and here what was added]" or something like that, please

**Comment by artdeell** [comment]
actions are added as soon as a piece of code gets updated
so you never really know if it's playable or not

чт, 18 мар. 2021 г., 01:42 gabbosta ***@***.***>:
