### ISSUE TITLE
[BUG] screen is white when u playing on 1.12.2 dynamic surroundings 

### ISSUE THREAD

**Issue by hanhtoogg** [PojavLauncherTeam/PojavLauncher#1076]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
@hanhtoogg fill da template

**Comment by hanhtoogg** [comment]
every time i run dynamic surroundings mod on 1.12.2 play screen is white

**Comment by khanhduytran0** [comment]
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> <br>
> - Make sure there was not duplicated issues.<br>
> - Make sure you have filled this issue template, or this will get rejected.
> </details>
> 
> ### Describe the bug
> A clear and concise description of what the bug is.
> 
> **Add a log file if you want to see your bug fixed !**
> 
> The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> ... *(your set of actions to reproduce the bug)*
> 
> ### Expected behavior:
> I expected ...
> 
> ### Screenshots or videos:
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> 
> **Platform:**
>  - Device Model [e.g. Mi 8 Pro 8/128]
>  - CPU architecture [e.g. aarch64] 
>  - Android Version [e.g. 10]
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> <details> <summary><b>Additional context</b></summary>
> <br>
> <pre>
> Add any other context about the problem here.
> </pre>
> </details>
> 

Read and fill into this, else we won't help.

**Comment by EXPress-016** [comment]
> every time i run dynamic surroundings mod on 1.12.2 play screen is white

What is the dynamic surroundings mod version?

**Comment by Ella594YT** [comment]
Yeah same on me
