### ISSUE TITLE
[BUG] Chat (Keyboard) 1.16.5

### ISSUE THREAD

**Issue by realGJBRO** [PojavLauncherTeam/PojavLauncher#1078]
When I play online servers on 1.16.5 and I want to chat I press (Keyboard and Chat) but no text pops up in chat and only sometimes it allows (Some letters in a sentence to be typed)

**Comment by pablodz** [comment]
On which device model are you trying to run keyboard?
Some devices are slow to charge the keyboard and handle them in real time.

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
