### ISSUE TITLE
Make You Can Change Skin

### ISSUE THREAD

**Issue by Beam195** [PojavLauncherTeam/PojavLauncher#1079]
Make an skin inporting button to make player easy change skin plz

**Comment by khanhduytran0** [comment]
Go to https://minecraft.net/en-us/profile/skin :eyes:

**Comment by kickturn** [comment]
Maybe he's playing on offline mode, on offline mode you can't change it

**Comment by EnderBrine99FOX** [comment]
> Maybe he's playing on offline mode, on offline mode you can't change it

If You Playing In offline Account Than You Two Chooses
1-Change Your Skin Form The Version File (jar File)
2-Download Texture Pack With Skin Only

**Comment by EXPress-016** [comment]
> > Maybe he's playing on offline mode, on offline mode you can't change it
> 
> If You Playing In offline Account Than You Two Chooses
> 1-Change Your Skin Form The Version File (jar File)
> 2-Download Texture Pack With Skin Only

3-use offlineskins mod

**Comment by Ella594YT** [comment]
Pog

**Comment by Harsh-bot-beep** [comment]
just close This Bruh
If They Manage To Create It 
It will only show to you not others

**Comment by matt995** [comment]
No account, no change skin 
ANTI PIRACY PIRACY SUX
