### ISSUE TITLE
Way to run Forge

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#108]
I tried to install Forge by copying libraries just like i did before OptiFine installer was properly implemented. But I ran into an issue: Forge attempts to install its own SecurityManager for "better security", but Android docs says that you can only set `null` security manager or SecurityException will be thrown. Do you know the way to pass that?
![image](https://user-images.githubusercontent.com/45949002/79575762-eb70aa80-80ca-11ea-99a3-4b9a3b0ba0a6.png)

**Comment by khanhduytran0** [comment]
Forge also implements many things that Android doesn't support:
- [`getClass().getProtectionDomain()` always return null](https://stackoverflow.com/questions/27790348/getclass-getprotectiondomain-getcodesource-getlocation-getpath-throw-a), it is used by OptiFine too..
- `URCLassLoader` in Android is broken.

So a custom Forge build from source is required for a working Forge:
- Replace `URLClassLoader` with `DexClassLoader`.
- Replace `getClass().getProtectionDomain()` with path to Forge.
- Idea: Run DX dexer at runtime???

**Comment by khanhduytran0** [comment]
Or If have something like custom BOOTCLASSPATH then everything can be solved!

**Comment by khanhduytran0** [comment]
Without modify OptiFine or Forge.

**Comment by khanhduytran0** [comment]
I'm trying to hack EGL over processes to make GL4ES send GL commands from `dalvikvm` or `app_process` process without success. If it success, the launcher can able to custom memory heap and solve incompatible issues.

**Comment by khanhduytran0** [comment]
This including solve without custom Forge. My attempt is at branch `dalvikvm_gl4es`.

**Comment by khanhduytran0** [comment]
This is possible in v3, but can't load to Minecraft main screen and Installer are font size = 0 so not sure if completely work.

**Comment by khanhduytran0** [comment]
> This is possible in v3, but can't load to Minecraft main screen 

Due to libGL.
