### ISSUE TITLE
[F-REQ] Hello, I was wondering if you can add support for magic keyboard and or PS4 controller? Is this something you are considering, or is this not possible? Thanks!

### ISSUE THREAD

**Issue by etstorm** [PojavLauncherTeam/PojavLauncher#1081]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EnderBrine99FOX** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

Will You Can Play With Mouse and keyboard But Java Edition Not Support Controller But Only With Mods

**Comment by OksmaWarez** [comment]
You can play with Mouse & Keyboard, but **Controller Support will NOT be added.**

**Comment by kedrick021** [comment]
Yeah plsss make supported on bluetooth controller 🎮

**Comment by OksmaWarez** [comment]
Never going to happen.

**Comment by lomnom** [comment]
[...Unless you do it yourself](sololearn.com)

**Comment by WesleyVanNeck** [comment]
> You can play with Mouse & Keyboard, but **Controller Support will NOT be added.**

It's in the work so don't spread fake news

**Comment by WesleyVanNeck** [comment]
Also this is a dublicated issue
