### ISSUE TITLE
How to zoom keys

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#1082]

**Comment by Slapp13** [comment]
if you use optifine, just click the C button

**Comment by yanluol** [comment]
What I mean is how to zoom the control buttons

**Comment by AutumnVN** [comment]
![Screenshot_2021-03-21-07-29-57-30](https://user-images.githubusercontent.com/77253698/111889900-474c5d80-8a17-11eb-8ef8-5d230acac23c.png)
control buttons scaling

**Comment by yanluol** [comment]
How to zoom a single key

**Comment by AutumnVN** [comment]
![Screenshot_2021-03-21-07-44-45-94](https://user-images.githubusercontent.com/77253698/111890142-5502e280-8a19-11eb-8bc1-87d376188b97.png)

**Comment by yanluol** [comment]
Is this the latest version? I don't have this setup



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 21, 2021 08:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PojavLauncherTeam/PojavLauncher] How to zoom keys (#1082)

**Comment by yanluol** [comment]
---Original---
From: ***@***.***&gt;
Date: Sun, Mar 21, 2021 08:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PojavLauncherTeam/PojavLauncher] How to zoom keys (#1082)

**Comment by khanhduytran0** [comment]
Or move the blue pointer, if if not working, you have an old build.
