### ISSUE TITLE
[BUG] Mccrayfish Gun mod 1.16.5

### ISSUE THREAD

**Issue by Bruh-coder439** [PojavLauncherTeam/PojavLauncher#1083]
### Describe the bug
Mccrayfish gun mod works fine but can't aimimg
To Reproduce:
Indicate steps to reproduce the buggy behavior:
1.install forge 1.16.5
2.download mccrayfish gun mod
3.download obfuscate(to make mccrayfish gun mod work)
Expected behavior:
works fine but it can't aiming

**Platform:**
 - Device Model [Xiaomi Note 4X 32x3]
 - CPU architecture [aarch64] 
 - Android Version [7]
 - PojavLauncher Version [e.g Latest Build||

**Comment by khanhduytran0** [comment]
Duplicate #1063. Always search for issue before create one plz.

**Comment by Bruh-coder439** [comment]
ok
