### ISSUE TITLE
It's me 

### ISSUE THREAD

**Issue by Gjbcujv** [PojavLauncherTeam/PojavLauncher#1086]
How i can add microsoft account

**Comment by Gjbcujv** [comment]
How i can add microsoft account

**Comment by tom300z** [comment]
Duh there is litteraly a big green button that says "MICROSOFT-LOGIN" when you first open the app

**Comment by matt995** [comment]
He prob ain’t have an acc

**Comment by pablodz** [comment]
You can check youtube tutorials for that

**Comment by ghost** [comment]
you foxy?, "it's me" lol

**Comment by tom300z** [comment]
> 
> 
> you foxy?, "it's me" lol

Wasn't that golden freddy?
