### ISSUE TITLE
[BUG] Lagnuage list

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [PojavLauncherTeam/PojavLauncher#1090]
Some names of languages change (and to not correct) because I'm changing my current lang.
For the example, in Russian language Tatar renames as «Татар», that's incorrect because this word is adjective, but not is noun (must be «Татарский»).

So I think that the best solution is adding language and their region names as stings for Crowdin.

**Comment by ebuild-1** [comment]
Agreed, but not all translations are perfect, there's some minor mistakes on my language too.
