### ISSUE TITLE
[BUG] <I Can't ignore Notch In My Pojavlauncher Options>

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#1092]
I Have Notch In My Device And I Can't Ignore it,
Ignore Notch Option Is Not Visible In On My Pojavlauncher Why? 

https://user-images.githubusercontent.com/79517194/111907018-894fc080-8a64-11eb-8afb-fd976b77bb11.mp4

I Already Ignored Notch In The Device Settings But Its Useless Cuz But Button Go Inside Notch

![Screenshot_20210321_164351_com android settings](https://user-images.githubusercontent.com/79517194/111907080-d2077980-8a64-11eb-8e76-d96dba0b4763.jpg)

Is There Any Way To Make This Option Visible On My Device
![111089117-03f87780-855d-11eb-9baa-c64bc8306360](https://user-images.githubusercontent.com/79517194/111907172-2c083f00-8a65-11eb-9f1f-7b1f24e0a315.png)

**Comment by Druxelite** [comment]
Update to the latest version

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: EnderBrine99FOX ***@***.***>
Sent: Sunday, March 21, 2021 9:48:35 PM
To: PojavLauncherTeam/PojavLauncher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PojavLauncherTeam/PojavLauncher] [BUG] <I Can't ignore Notch In My Pojavlauncher Options> (#1092)


I Have Notch In My Device And I Can't Ignore it
Ignore Notch Option Is Not Visible In On My Pojavlauncher Why?

https://user-images.githubusercontent.com/79517194/111907018-894fc080-8a64-11eb-8afb-fd976b77bb11.mp4

I Already Ignored Notch In The Device Settings But Its Useless Cuz But Button Go Inside Notch

[Screenshot_20210321_164351_com android settings]<https://user-images.githubusercontent.com/79517194/111907080-d2077980-8a64-11eb-8e76-d96dba0b4763.jpg>

Is There Any Way To Make This Option Visible On My Device
[111089117-03f87780-855d-11eb-9baa-c64bc8306360]<https://user-images.githubusercontent.com/79517194/111907172-2c083f00-8a65-11eb-9f1f-7b1f24e0a315.png>

**Comment by EnderBrine99FOX** [comment]
If You Mean  Update Pojavlauncher This Is Literally The Latest Version (Update gradle buildfiles)

**Comment by Mathias-Boulay** [comment]
Please fill the bug template, else we can't really help you.

**Comment by khanhduytran0** [comment]
Duplicate #1052 bruh @EnderBrine99FOX 
![38CC2C03-6B80-4258-9B83-A8826BEA75FE](https://user-images.githubusercontent.com/40482367/112770927-653b4300-9053-11eb-8a19-b33bbd13ca7e.jpeg)

**Comment by EnderBrine99FOX** [comment]
@khanhduytran0  I Know It's Duplicate But I Still Can't Ignore Notch

**Comment by khanhduytran0** [comment]
Show us your installed version :eyes:

**Comment by EnderBrine99FOX** [comment]
> Show us your installed version 👀

Its The Latest Build (QoL UI updates)

**Comment by khanhduytran0** [comment]
[❌] Is it come from `v3_openjdk` branch?

**Comment by EnderBrine99FOX** [comment]
> [❌] Is it come from `v3_openjdk` branch?

Yep

**Comment by khanhduytran0** [comment]
> Yep

![image](https://user-images.githubusercontent.com/40482367/112790628-01803c80-908a-11eb-9921-5e8483f58e2b.jpeg)
