### ISSUE TITLE
[BUG] The custom keyboard disappears when it restarts

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#1093]
The custom keyboard disappears when the app reboots

**Platform:**
 - Device Model honor 9c 
 - CPU architecture aarch64
 - Android Version  10
 - PojavLauncher version 3.3.1

**Comment by OksmaWarez** [comment]
Did you set it as default control.json?

**Comment by khanhduytran0** [comment]
@Iarkont

**Comment by Harsh-bot-beep** [comment]
Rip
