### ISSUE TITLE
[F-REQ] Me have question!

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1096]
Hello I came here to see if developer's are working on the new Open GL for Pojavlauncher! to support 21w10a + snapshots?  please don't be rude to me .. I'm just asking a question!

**Comment by CriticalRange** [comment]
You can join to discord and watch the development phase live on #development 😄

**Comment by OwzygZawg** [comment]
Thanks

**Comment by OwzygZawg** [comment]
Can pass me link?

**Comment by WesleyVanNeck** [comment]
> Can pass me link?

its in readme so read the readme

**Comment by WesleyVanNeck** [comment]
> Can pass me link?

https://discord.com/invite/6RpEJda
