### ISSUE TITLE
Can you fix emersive portal mod 1.16.0 is full of white portal when I use emersive portal mod in better portal mod for 1.12.2 full of Glitch can see though the ground when I used better portal mod 1.12.2 plsss fix

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1100]
Can you fix emersive portal mod 1.16.0 is full of white portal when I use emersive portal mod in better portal mod for 1.12.2 full of Glitch can see though the ground when I used better portal mod 1.12.2 plsss fix

My phone : xiaomi mi 9t pro

**Comment by WesleyVanNeck** [comment]
fill in the template and give us the latest log

**Comment by Slapp13** [comment]
#983

**Comment by WesleyVanNeck** [comment]
> #983

that does mean you got file the info here to

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/983#issuecomment-787647671
