### ISSUE TITLE
[BUG] no .minecraft folder

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1102]
I am trying to mod my game, and i cannot find any .minecraft folder on my phone. from what ive seen to use mods you need to put them in that folder. I have also looked in the pojav folder, and it looks like most of that is just the java installation.

I have no idea how to recreate this issue
[latestlog[1].txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6192366/latestlog.1.txt)

**Comment by WesleyVanNeck** [comment]
enable hiden folder in your chsen file manager

**Comment by ghost** [comment]
> enable hiden folder in your chsen file manager

i have

**Comment by WesleyVanNeck** [comment]
there should be one or it wont run minecraft

**Comment by ghost** [comment]
So i can see the folder in a seperate folder viewer app on my phone, but not on the built in one or on windows at all. is there a way i can view it on windows? i have my hidden folder view turned on

**Comment by ebuild-1** [comment]
> So i can see the folder in a seperate folder viewer app on my phone, but not on the built in one or on windows at all. is there a way i can view it on windows? i have my hidden folder view turned on

To find .minecraft in Windows, go type %appdata% and go to .minecraft

**Comment by ghost** [comment]
> > So i can see the folder in a seperate folder viewer app on my phone, but not on the built in one or on windows at all. is there a way i can view it on windows? i have my hidden folder view turned on
> 
> To find .minecraft in Windows, go type %appdata% and go to .minecraft

Issues closed and also we aren't talking about pc.
