### ISSUE TITLE
[F-REQ]can u pls make auto ram back 

### ISSUE THREAD

**Issue by hanhtoogg** [PojavLauncherTeam/PojavLauncher#1103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hanhtoogg** [comment]
i have issues with out auto ram i need help

**Comment by WesleyVanNeck** [comment]
Fill the template also wrong tag choosen as this is a bug report rather an enhancement
