### ISSUE TITLE
Samsung Galaxy Tab s7 keyboard support

### ISSUE THREAD

**Issue by nickthekidNL** [PojavLauncherTeam/PojavLauncher#1104]
On Samsung galaxy tab s7 there is a keyboard that can be connected to it to use as a laptop. Unfortunately, it seems to not register keys or touchpad input from this attachable keyboard.

keyboard link:
https://www.samsung.com/us/mobile/mobile-accessories/tablets/galaxy-tab-s7-plus-bookcover-keyboard-ef-dt970ubeguj/

**Comment by Mathias-Boulay** [comment]
@nickthekidNL can you try if the bug still occurs with this dev build ? 
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/901821231

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer.
Closing
