### ISSUE TITLE
Wont let me join servers like muchymc, invadedlands, or socks.gg

### ISSUE THREAD

**Issue by Mr-Axolotl** [PojavLauncherTeam/PojavLauncher#1105]
Plz fix this or if it is possible then how do I do it, I've been trying to join munchymc but couldn't :(

**Comment by Druxelite** [comment]
Have you tried using an account that ISN'T offline?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mr-Axolotl ***@***.***>
Sent: Thursday, March 25, 2021 9:22:31 AM
To: PojavLauncherTeam/PojavLauncher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PojavLauncherTeam/PojavLauncher] Wont let me join servers like muchymc, invadedlands, or socks.gg (#1105)


Plz fix this or if it is possible then how do I do it, I've been trying to join munchymc but couldn't :(

**Comment by matt995** [comment]
Yea

**Comment by Druxelite** [comment]
> Yea

Idk what's wrong with your pojav, are you using latest dev build?

**Comment by WesleyVanNeck** [comment]
Fill the issue template

**Comment by WesleyVanNeck** [comment]
Ang give a log and more info like are running the latest dev build

**Comment by gamerboy82yt** [comment]
Dude even a crack server like twerion.net i can't join i have mojang account but it said invalid ip

**Comment by Mr-Axolotl** [comment]
I apparently had to turn on my mobile hotspot
