### ISSUE TITLE
Memory allocation scaler is too fast.

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#1113]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Memory allocation scaler is too fast.

**Describe alternatives you've considered**

Remove Memory Allocation scaler change it to custom memory allocation like MCinaBox.

**Additional context**

https://user-images.githubusercontent.com/75970303/112719408-cf5cc680-8f33-11eb-83ce-577a234c7b68.mp4

**Comment by LANCECRAFT1104** [comment]
I can't put exactly 750 MB

**Comment by khanhduytran0** [comment]
Does 749MB or 751MB causes game crashes?

**Comment by khanhduytran0** [comment]
@LANCECRAFT1104 ?

**Comment by khanhduytran0** [comment]
> Remove Memory Allocation scaler change it to custom memory allocation like MCinaBox.

Well, this is __not__ a good idea, some persons actually messed up with JVM arguments and complain about game crashes just because of setting RAM.

**Comment by LANCECRAFT1104** [comment]
> @LANCECRAFT1104 ?

Sorry im offline.

**Comment by LANCECRAFT1104** [comment]
> Does 749MB or 751MB causes game crashes?

No

**Comment by khanhduytran0** [comment]
So, why you need a correct number?

**Comment by Eddie02345** [comment]
Lmao. Then close this issue

**Comment by LANCECRAFT1104** [comment]
> So, why you need a correct number?

So that JVM and the memory allocation is same.

**Comment by ebuild-1** [comment]
> > So, why you need a correct number?
> 
> So that JVM and the memory allocation is same.

That doesn't make sense bro XD, putting it in 750 mb will crash your game often,
It still crashes in 2000 mb but not often XD.

**Comment by LANCECRAFT1104** [comment]
> > > So, why you need a correct number?
> > 
> > 
> > So that JVM and the memory allocation is same.
> 
> That doesn't make sense bro XD, putting it in 750 mb will crash your game often,
> It still crashes in 2000 mb but not often XD.

No
