### ISSUE TITLE
Change image in google play

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1115]
Your images in google play is black. Fix it to attract new users.
![Screenshot_2021-03-27-21-54-31-766_com android vending](https://user-images.githubusercontent.com/48925787/112733206-2e780680-8f47-11eb-8976-3b8c1b32d425.jpg)

**Comment by IronWolf2003** [comment]
> Your image in google play is black. Fix it to attract new users.
> ![Screenshot_2021-03-27-21-54-31-766_com android vending](https://user-images.githubusercontent.com/48925787/112733206-2e780680-8f47-11eb-8976-3b8c1b32d425.jpg)

**Comment by WesleyVanNeck** [comment]
its on purpus or google wont allow us to uplaud the apk
