### ISSUE TITLE
[BUG] Crash on 1.12 and up

### ISSUE THREAD

**Issue by ado1928** [PojavLauncherTeam/PojavLauncher#1116]
### Describe the bug
Launching Minecraft 1.12 and up causes it to crash with "Application/Game exited with code 1"

[Crash log](https://cdn.discordapp.com/attachments/825415495938998273/825416526319452260/latestlog.txt)

I have also dedicated 2GB RAM to it: `-Xms768m -Xmx2048m`
### To Reproduce:
1. Start PojavLauncher
2. Launch any version that's 1.12 or above
3. Crash

### Expected behavior:
No crash

### Screenshots or videos:
https://cdn.discordapp.com/attachments/825415495938998273/825415916283363368/Screenshot_2021-03-27-18-07-05-523_net.kdt.pojavlaunch.jpg

**Platform:**
 - Device Model: Xiaomi Redmi 9 Prime (4 / 64)
 - CPU architecture: aarch64
 - Android Version: Android 10 / MIUI 12
 - PojavLauncher Version: Latest Release

**Comment by khanhduytran0** [comment]
You should enable "Check libraries" on launcher settings.

**Comment by ado1928** [comment]
I don't have such an option.

**Comment by ado1928** [comment]
It seems like I did not have the latest version of the launcher. Fixed
