### ISSUE TITLE
[BUG] 当我使用最新版本时游戏将崩溃https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/693439875

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#1118]
**Platform:**
 - Device Model [e.g. redmi note 7 4/64]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210327 ]

 I can't upload the file because of the network problem.

--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl-jemalloc.jar, lwjgl-opengl.jar, lwjgl.jar, lwjgl-glfw-classes.jar, lwjgl-tinyfd.jar, lwjgl-openal.jar, version, lwjgl-stb.jar, jsr305.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms2048m -Xmx2048m -Dorg.lwjgl.opengl.libname=libgl4es_115.so"
Headless version detected! (20210326)
--------- beginning of system
--------- beginning of crash
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" unused DT entry: DT_RPATH (type 0xf arg 0x361) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
--------- beginning of main
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" unused DT entry: DT_RPATH (type 0xf arg 0x450) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" unused DT entry: DT_RPATH (type 0xf arg 0x33c0) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x13b8
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
" unused DT entry: 
DT_RPATH (type 0xf arg 0x2196) (ignoring)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" unused DT entry: DT_RPATH (type 0xf arg 0x6a68) (ignoring)

WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: DT_RPATH
 (type 0xf arg 0x4d9) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" unused DT entry: DT_RPATH (type 0xf arg 
0xda0) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" unused DT entry: DT_RPATH (type 0xf arg 0x3f1) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" unused DT entry: 
DT_RPATH (type 0xf arg 0x103) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" unused DT entry: DT_RPATH (type 0xf arg 0x364
) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" unused DT entry: DT_RPATH (type 0xf arg 0x158) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" unused DT entry: 
DT_RPATH (type 0xf arg 0x23a) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" unused DT entry: DT_RPATH (type 0xf arg 0xe6) (ignoring)

WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" unused DT entry: DT_RPATH (type 0xf arg 0x119) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsig.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 0x1c7) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x77
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsunec.so success
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" unused DT entry: DT_RPATH (type 0xf arg 0x8ff) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so success
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" unused DT entry: DT_RPATH (type 0xf arg 0x1c1) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
I/jrelog  (28970): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" unused DT entry: DT_RPATH (type 
0xf arg 0x1

**Comment by khanhduytran0** [comment]
There is no Chinese dev there. __**English or Russian or Vietnamese only**__
![_20210328_074204](https://user-images.githubusercontent.com/40482367/112738830-28ab1100-8f99-11eb-94da-16b002246d76.jpg)
This is *not* for normal users.

**Comment by T-CATHOME** [comment]
@khanhduytran0 Is there a way to shut it down?

**Comment by khanhduytran0** [comment]
wtfman
