### ISSUE TITLE
[F-REQ] (Can I Change The Ui Background?) 

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#1119]
I Already Changed The App Png To The Latest Nether Update Picture
![Screenshot_20210328_041452_com huawei android launcher](https://user-images.githubusercontent.com/79517194/112739346-5d5c9f80-8f7c-11eb-8b7b-06d85de33f9e.jpg)

It Will Be Super Cool if Could Replace The Background Picture With This Picture
![nether-header](https://user-images.githubusercontent.com/79517194/112739338-4f0e8380-8f7c-11eb-88e5-c6e782e9c4b5.jpg)

**Comment by LANCECRAFT1104** [comment]
Thats my F-Req last time but........

**Comment by khanhduytran0** [comment]
> Change The App Png To The Latest Nether Update Picture

Do you want us get a copyright strike?...

**Comment by LANCECRAFT1104** [comment]
![images](https://user-images.githubusercontent.com/75970303/112740723-f8bc3780-8fb1-11eb-94e6-084a7f85bb07.jpeg)

This is the original background.

**Comment by khanhduytran0** [comment]
Setting app background is fine, but setting to app icon will just take the app down from google play.

**Comment by EnderBrine99FOX** [comment]
> > Change The App Png To The Latest Nether Update Picture
> 
> Do you want us get a copyright strike?...

I Didn't Mean The Hole App In Google Play What I Mean is How To Change The Background Picture in Pojavlauncher Just That

**Comment by EnderBrine99FOX** [comment]
> Setting app background is fine, but setting to app icon will just take the app down from google play.

Plz Can You tell Me How To change The Background Plz

**Comment by khanhduytran0** [comment]
~~Also, you should make Shift-At-The-First-Char as optional.~~

**Comment by LANCECRAFT1104** [comment]
Why did you change the app icon.

**Comment by EnderBrine99FOX** [comment]
> Why did you change the app icon.

I don't Care About The App Icon What I Mean i Want To Change The Background Picture In Huawei Device You can Change Any App Icon To What Ever You Want So I Just Changed it To Make Defrant Between Bedrock Edition Png And Pojavlauncher Png

**Comment by EnderBrine99FOX** [comment]
> Why did you change the app icon.

And Don't Worry That's Just In My Phone

**Comment by artdeell** [comment]
With that icon Pojav looks like a shitty Minecraft clone that you can see on Google play

**Comment by EnderBrine99FOX** [comment]
> With that icon Pojav looks like a shitty Minecraft clone that you can see on Google play

That's What I Mean
![Screenshot_20210329_014730_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/112770733-c0a80980-9030-11eb-9077-f8a4c97b760c.jpg)
