### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by issuereporter292** [PojavLauncherTeam/PojavLauncher#112]
Whenever i try to join a cracked server it always says that its an invalid session. Also i can only add one server on an acct. What i mean is if i want to add another server i have to make a new acct.

**Comment by khanhduytran0** [comment]
> Also i can only add one server on an acct. What i mean is if i want to add another server i have to make a new acct.

Why? servers ip addresses are global and shared between account.

**Comment by issuereporter292** [comment]
> > Also i can only add one server on an acct. What i mean is if i want to add another server i have to make a new acct.
> 
> Why? servers ip addresses are global and shared between account.

Idk it wont let me type if i want to add another server.

**Comment by khanhduytran0** [comment]
What keyboard are you using?

**Comment by khanhduytran0** [comment]
@issuereporter292 please reply, use GBoard.
