### ISSUE TITLE
[BUG] Invalid session error on realms

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1122]
When I click on realms it gives me a message saying Invalid Session Try Restarting Minecraft I have restarted the game and pojav launcher and i have bought an account. Does anyone know how to fix this?
Android Version

**Comment by khanhduytran0** [comment]
So, can you join premium server?

**Comment by ghost** [comment]
yes i can

**Comment by khanhduytran0** [comment]
Check latestlog.txt

**Comment by khanhduytran0** [comment]
Also, fill the template :eyes:

**Comment by ghost** [comment]
oops
