### ISSUE TITLE
[BUG] Can't  join realms

### ISSUE THREAD

**Issue by MasterGalaxyBoy** [PojavLauncherTeam/PojavLauncher#1124]
So When you try going to the realms Its going to show you 
The text saying "Invalid Session Please try restarting minecraft 
![Screenshot_20210328-182848_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/81526303/112760030-d77d3a80-8ff5-11eb-9389-6e841271f9d1.jpg) 
Please fix this bug I can't  play any realms.

**Comment by khanhduytran0** [comment]
Duplicate #1122
