### ISSUE TITLE
[BUG] On some launches for 1.16.5, I am unable to click interface buttons in-game.

### ISSUE THREAD

**Issue by GoldenFurredFox** [PojavLauncherTeam/PojavLauncher#1125]
### Describe the bug
When I launch 1.16.5, it seems that the on-screen buttons sometimes don't work. From my experience, keeping a cursor active or tapping the screen while the splash screen is open might cause it.

Sadly, I do not have a log that would help describe what's wrong. I have kept looking at every log the game produces when it does and doesn't work and there are NO lines that change.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Sign into an online account (have not reproduced with offline)
3. Launch 1.16.5 (modded or vanilla doesn't matter)
4. When the game loads, there's a random chance that you can't click anything.

### Expected behavior:
I expected the game to load and allow me to use the interface.

### Screenshots or videos:
Once I figure out how to record my phone, this is my top priority.

**Platform:**
 - Device Model Moto g7 Power
 - CPU architecture aarch64 
 - Android Version 10
 - PojavLauncher Version Latest Release

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Seems to be the same as #1123 but sadly that user didn't use the correct format so it's bound to get closed soon.
</pre>
</details>

**Comment by GoldenFurredFox** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6217847/latestlog.txt)
game seemed to not accept input, but i waited instead of closing the game and after a minute or two it accepted input again. i was able to join a server but ended up losing control while underwater and dying to drowning, then losing control in flight and having pojavlauncher close

might be related to #1126

**Comment by khanhduytran0** [comment]
Get latest build :eyes:
