### ISSUE TITLE
[BUG] Game randomly closes while playing, no crash is reported

### ISSUE THREAD

**Issue by GoldenFurredFox** [PojavLauncherTeam/PojavLauncher#1126]
### Describe the bug
While playing the game and actually inside a server, PojavLauncher abruptly closed without Minecraft reporting a crash.

Sadly, the game's logs don't display a crash, so my logs wouldn't be helpful in this case.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Log in using an online account (have not tried to repro with an offline account)
3. Launch 1.16.5 with Fabric and OptiFabric and OptiFine (have not tried to repro with other versions)
4. Join a multiplayer survival server that is vanilla with data packs (have not tried to repro with public servers or local worlds)
5. While playing, the PojavLauncher will close after some minutes.

### Expected behavior:
I expected PojavLauncher not to close so I could continue to enjoy playing with my friend.

### Screenshots or videos:
Once I figure out how to record my phone, I will try to record this for the bug report.

**Platform:**
 - Device Model Moto g7 Power
 - CPU architecture aarch64 
 - Android Version 10
 - PojavLauncher Version Latest Release

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
N/A
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
how much ram did located to pojav

**Comment by WesleyVanNeck** [comment]
as i expect this ro be a ram issue plz provide the latestlog.txt

**Comment by GoldenFurredFox** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6217693/latestlog.txt)
i'm tellin' ya, no change was reported and no crash happened

**Comment by WesleyVanNeck** [comment]
again how much ram did you give it

**Comment by GoldenFurredFox** [comment]
the automatic amount

**Comment by WesleyVanNeck** [comment]
1.16.5 is ram heavy

**Comment by GoldenFurredFox** [comment]
how much ram do you recommend?

**Comment by GoldenFurredFox** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6217844/latestlog.txt)
might be related to #1125 since input acceptance halted and left my character flying forward for a straight minute before pojavlauncher closed

**Comment by khanhduytran0** [comment]
1.16.5 requires at least 512mb ram to work properly.

**Comment by ebuild-1** [comment]
> 1.16.5 requires at least 512mb ram to work properly.

512? And yet my mc managed to crash at 2000 mb

**Comment by khanhduytran0** [comment]
> > 1.16.5 requires at least 512mb ram to work properly.
> 
> 512? And yet my mc managed to crash at 2000 mb

*"your"* mc run out of your phone memory :eyes:

**Comment by ebuild-1** [comment]
> > > 1.16.5 requires at least 512mb ram to work properly.
> > 
> > 
> > 512? And yet my mc managed to crash at 2000 mb
> 
> _"your"_ mc run out of your phone memory

Lol, maybe it's that god damn lag machines that did this.

**Comment by Harsh-bot-beep** [comment]
Well I Recomded Giving All Your Presitge To 1.16.5 To Male It Run

**Comment by ebuild-1** [comment]
Duplicated.

**Comment by Pochi336** [comment]
> ### Describe the bug
> While playing the game and actually inside a server, PojavLauncher abruptly closed without Minecraft reporting a crash.
> 
> Sadly, the game's logs don't display a crash, so my logs wouldn't be helpful in this case.
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> 2. Log in using an online account (have not tried to repro with an offline account)
> 3. Launch 1.16.5 with Fabric and OptiFabric and OptiFine (have not tried to repro with other versions)
> 4. Join a multiplayer survival server that is vanilla with data packs (have not tried to repro with public servers or local worlds)
> 5. While playing, the PojavLauncher will close after some minutes.
> 
> ### Expected behavior:
> I expected PojavLauncher not to close so I could continue to enjoy playing with my friend.
> 
> ### Screenshots or videos:
> Once I figure out how to record my phone, I will try to record this for the bug report.
> 
> **Platform:**
> 
> * Device Model Moto g7 Power
> * CPU architecture aarch64
> * Android Version 10
> * PojavLauncher Version Latest Release
> 
> Additional context

Its more likely to crash if your having a fabric client/Version. (only based on my experience)
Having an optifabric giving it more likely to crash, even trying fabric with sodium. Crashes more early than expected.
