### ISSUE TITLE
[BUG] Newest dev build crashes

### ISSUE THREAD

**Issue by Lilith-Crimeow** [PojavLauncherTeam/PojavLauncher#1127]
Newest dev build with Mesa crashes on launch

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Download newest dev build (Missing")
2. Start Pojavlauncher
3. Open any version (I tried 1.16.3)
4. Wait a few seconds
5. Crash

### Expected behavior:
I expected it to launch, and it didn't even go to the Mojang screen

**Platform:**
 - Device Model : Samsung Galaxy Tab s5e
 - CPU architecture : AARCH64
 - Android Version : 10
 - PojavLauncher Version : Latest development build
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6217950/latestlog.txt)

**Comment by Lilith-Crimeow** [comment]
To be specific, the newest dev build is this one:
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/695017165

**Comment by khanhduytran0** [comment]
Duplicate #1121
