### ISSUE TITLE
Can't install wurst client for 1.12.2

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1128]
It just said **_no mod detected_** and it instantly restarts the game after a couple of seconds, wurst 1.12 doesn't require fabric (I think wurst doesn't require forge too idk)
![Screenshot_2021-03-29-13-30-18-85_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/80798103/112791081-55dbea00-9093-11eb-9085-a08861549bbc.jpg)

**Comment by AutumnVN** [comment]
what version?

**Comment by khanhduytran0** [comment]
@SamSam759 yep it said *no mod detected* but it did not says *crashing/exiting*.

**Comment by khanhduytran0** [comment]
Also bruh, Wurst does not have an installer, it is just a mod. read carefully
> Launch a <ins>mod installer</ins>

**Comment by SamSam759** [comment]
Please help I want to play in anarchy server

**Comment by ebuild-1** [comment]
> what pojav version? (or where do you download it?)

It's latest version.i downloaded it on GitHub

**Comment by khanhduytran0** [comment]
Nvm, wurst have installer, but fill the template.

**Comment by ebuild-1** [comment]
> Also bruh, Wurst does not have an installer, it is just a mod. read carefully
> 
> > Launch a mod installer

How do I run it then? Thanks.

**Comment by khanhduytran0** [comment]
At least send latestlog.txt

**Comment by khanhduytran0** [comment]
Also, `Memory set to xxxxM` told us that your using version is old :eyes:

**Comment by ebuild-1** [comment]
> At least send latestlog.txt

How? Where do I find latest.log

**Comment by AutumnVN** [comment]
it seems you are using release version, this is very old (jan 25th).
use latest build from action tab but only use which have V3_OPENJDK branch (or it wont work)

**Comment by ebuild-1** [comment]
> At least send latestlog.txt

Found it
![Uploading Screenshot_2021-03-29-13-46-49-08.jpg…]()

**Comment by khanhduytran0** [comment]
latest.log ≠ latestlog<ins>.txt</ins>

**Comment by ebuild-1** [comment]
> it seems you are using release version, this is very old (jan 25th).
> use latest build from action tab but only use which have V3_OPENJDK branch (or it wont work)

Link please? Thanks.

**Comment by AutumnVN** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk

**Comment by ebuild-1** [comment]
> latest.log ≠ latestlog.txt

I found it, how do I open it? It's sending me to zoom buddies.

**Comment by ebuild-1** [comment]
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6219565/latest.log)
I found a way to send it ok

**Comment by khanhduytran0** [comment]
Wtfman we are expecting latestlog.txt, you sent latest.log

**Comment by ebuild-1** [comment]
> Wtfman we are expecting latestlog.txt, you sent latest.log

Bruh I already sent the screen shot bro 😂

**Comment by ebuild-1** [comment]
> At least send latestlog.txt
> 
> Found it

This is the latestlog.txt screenshot

**Comment by khanhduytran0** [comment]
You didn’t even let GitHub to upload screenshot.

**Comment by khanhduytran0** [comment]
> `![Uploading Screenshot_2021-03-29-13-46-49-08.jpg…]()`

it says Uploading and you press comment right away

**Comment by ebuild-1** [comment]
Ok 
![IMG_20210329_135933](https://user-images.githubusercontent.com/80798103/112792995-11524d80-9097-11eb-808f-5651915ae781.jpg)

**Comment by ebuild-1** [comment]
Oops

**Comment by AutumnVN** [comment]
just use latest v3_openjdk and it will work xd

**Comment by ebuild-1** [comment]
> just use latest v3_openjdk and it will work xd

Ok sure thank you. Big thanks.
![download](https://user-images.githubusercontent.com/80798103/112793246-845bc400-9097-11eb-8285-97b247ab256f.jpeg)

**Comment by ebuild-1** [comment]
> just use latest v3_openjdk and it will work xd

Uhh so I just need to download no runtime app to all of them then install?

**Comment by ebuild-1** [comment]
What do I need to pick there

**Comment by AutumnVN** [comment]
app-debug

**Comment by SamSam759** [comment]
@AutumnVN ????

**Comment by ebuild-1** [comment]
Oh okay, do I need to download it all?

**Comment by AutumnVN** [comment]
just one app-debug

**Comment by SamSam759** [comment]
Do I need to download all the debug apps to get all updates?

**Comment by ebuild-1** [comment]
Okay thanks, lovelots <3 8========D--
