### ISSUE TITLE
Question: What is a Controller Mod? 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1129]
I was wondering what this means because in the known bugs it says that controller mods don't work. I also had a issue where I couldn't install a mod. Even though the file was a Installer and a Jar file. I hope I could have this Question answered or/and a fix to my issue.

**Comment by khanhduytran0** [comment]
Controller mod is related to add support for external controller (PSN / Xbox / etc...) which map them to Minecraft keycodes, by default a Minecraft java does not support playing with a controller.
