### ISSUE TITLE
[BUG] <Fabric won't run and stuck on black screen>

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1130]
<Its stuck on black screen> <stuck on black screen and not loading forever>

### Describe the bug
It's just stuck on loading screen

**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6221711/latestlog.txt)
I CANT FOUND LAST LOG

**

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(its stuck on black screen even restarting the app doesn't work)*

### Expected behavior:
I expected it to run fabric ...

### Screenshots or videos:
*Not possible*

**Platform:**
 - Oppo A12 (4/64)
 - mediatek p35
 - Android version 9 (pie)
 - PojavLauncher Version 
![Screenshot_2021-03-29-20-49-53-43](https://user-images.githubusercontent.com/80798103/112839368-b63d4c80-90d0-11eb-8287-d5e20352297f.jpg)

**Comment by ebuild-1** [comment]
> ### Describe the bug
> It's just stuck on loading screen
> 
> **
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6221711/latestlog.txt)
> I CANT FOUND LAST LOG
> 
> **
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
>    ... _(its stuck on black screen even restarting the app doesn't work)_
> 
> ### Expected behavior:
> I expected it to run fabric ...
> 
> ### Screenshots or videos:
> _This is what I meant, its stuck in black screen with controls_
> 
![Screenshot_2021-03-29-23-09-00-19_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/80798103/112857953-f954eb00-90e3-11eb-8e56-f7989bc22622.jpg)

> **Platform:**
> 
> * Oppo A12 (4/64)
> * mediatek p35
> * Android version 9 (pie)
> * PojavLauncher Version
>   ![Screenshot_2021-03-29-20-49-53-43](https://user-images.githubusercontent.com/80798103/112839368-b63d4c80-90d0-11eb-8287-d5e20352297f.jpg)

**Comment by khanhduytran0** [comment]
`
[12:17:25] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'wurst': [v7.14-MC1.16.5 at /storage/emulated/0/games/PojavLauncher/.minecraft/mods/Wurst-Client-v7.14-MC1.16.5.jar], [v7.12.1-MC1.16.5 at /storage/emulated/0/games/PojavLauncher/.minecraft/mods/Wurst-Client-v7.12.1-MC1.16.5.jar]
`

:eyes:

**Comment by ebuild-1** [comment]
> `[12:17:25] [main/FATAL]: A critical error occurred net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'wurst': [v7.14-MC1.16.5 at /storage/emulated/0/games/PojavLauncher/.minecraft/mods/Wurst-Client-v7.14-MC1.16.5.jar], [v7.12.1-MC1.16.5 at /storage/emulated/0/games/PojavLauncher/.minecraft/mods/Wurst-Client-v7.12.1-MC1.16.5.jar]`

Yeah I removed the wurst,ctm,and optifine g7 and changed optifine to g6, it works fine now, I'm gonna close this.
