### ISSUE TITLE
[BUG] [F-REQ] <There's no clipboard thing in the g keyboard>

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1131]
<No clipboard and the other stuff> <you can't paste things since there's no paste button and that is a hassle especially when your joining a server>

### Describe the bug:
I don't really know if this is a bug, might be a request but hey I want to paste stuffs.

**I don't think there's a log file for this one.**

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(Restarting the laucher doesn't do anything, since my g keyboard was part of the system)*

### Expected behavior:
I expected the clipboard to pop up ...

### Screenshots or videos:
*This is my problem (no clipboard and other stuff)*
![IMG_20210329_233246](https://user-images.githubusercontent.com/80798103/112861354-4d150380-90e7-11eb-81bb-ab2709c75c43.jpg)

*This is what I need to be added, which is helpful.*
![IMG_20210329_233233](https://user-images.githubusercontent.com/80798103/112861211-2ce54480-90e7-11eb-9cdc-5b037779cef2.jpg)

**Platform:**
 - Oppo A12 (4/64)
 - Mediatek p35
 - Android Version 9 (pie)
 - Version 3.3.1.1_rel_20210321

Thanks in advance.

**Comment by EXPress-016** [comment]
Use control+v to paste and control+c to copy

**Comment by ebuild-1** [comment]
Thanks

**Comment by ebuild-1** [comment]
Does it mean I can only paste one up at a time?

**Comment by ebuild-1** [comment]
@Atifexpress

**Comment by EXPress-016** [comment]
> Does it mean I can only paste one up at a time?

Yes

**Comment by ebuild-1** [comment]
Thanks.
