### ISSUE TITLE
[BUG] <Short description>Unable to open/run jarfile any fix?

### ISSUE THREAD

**Issue by ahmedisgamet** [PojavLauncherTeam/PojavLauncher#1132]
Keeps saying unable to open jarfile when trying to install optifine or fabric installer tried a lot of methods none of them work I heard someone say rename but I don’t know what to rename

**Comment by ebuild-1** [comment]
Bro where is latestlog.txt so they can fix your issue?

**Comment by ebuild-1** [comment]
@ahmedisgamet latestlog.txt is in Pojavlaucher> .Minecraft

**Comment by ebuild-1** [comment]
> @ahmedisgamet latestlog.txt is in games> Pojavlaucher> .Minecraft

**Comment by khanhduytran0** [comment]
@ahmedisgamet any reply?

**Comment by ahmedisgamet** [comment]
Never mind I fixed it

**Comment by ahmedisgamet** [comment]
You need to install sqlite 3 on your iPad/iphone I got a new android anyway
better bye bye ios

**Comment by Harsh-bot-beep** [comment]
Close this issue?
