### ISSUE TITLE
[BUG] 1.8.9 upon launching, the game crashed.

### ISSUE THREAD

**Issue by kirk33120** [PojavLauncherTeam/PojavLauncher#1134]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Upon launching the game, the game crashed.
similar to #974 
**Add a log file if you want to see your bug fixed !**

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6226159/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Play
3. Wait for it to launch the game

### Expected behavior:
I expected it would launch the game perfectly fine

### Screenshots or videos:

https://youtube.com/shorts/YInsYzryy2Y

**Platform:**
 - Device Model : Infinix hot 10 play (x688c)
 - CPU architecture : ARMv7
 - Android Version : 10
 - PojavLauncher Version : latest release and the play store version

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
You don't have a anough free ram
