### ISSUE TITLE
The update _ libs _ mesa _ test version crashed.

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#1136]
--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl-jemalloc.jar, lwjgl-opengl.jar, lwjgl.jar, lwjgl-glfw-classes.jar, lwjgl-tinyfd.jar, lwjgl-openal.jar, version, lwjgl-stb.jar, jsr305.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms2048m -Xmx2048m"
--------- beginning of system
--------- beginning of crash
--------- beginning of main
Headless version detected! (20210114)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x361
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x450
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
" unused DT entry: 
DT_RPATH
 (type 
0xf arg 0x33c0) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=
0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" unused DT entry: DT_RPATH (type 0xf arg 0x13b8) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x2196
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x6a68
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: DT_RPATH (type 0xf arg 0x4d9) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=
0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0xda0
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x3f1
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
 arg 
0x103
) (ignoring)
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" unused DT entry: DT_RPATH (type 
0xf arg 0x364) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" unused DT entry: DT_RPATH
 (type 0xf arg 0x158) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x23a
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsig.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" unused DT entry: DT_RPATH
 (type 0xf arg 0xe6) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
" unused DT entry: DT_RPATH (type 0xf arg 0x119) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x1c7
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so success
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x77
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsunec.so success
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" unused DT entry: DT_RPATH (type 0xf arg 0x8ff) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x1c1
) (ignoring)

WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x16fe
) (ignoring)

WARNING: linker: 
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so
" unused DT entry: 
DT_RPATH
 (type 0xf arg 0x1d2) (ignoring)

WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" unused DT entry: DT_RPATH (type 0xf arg 0x139) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_xawt.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" unused DT entry: DT_RPATH (type 0xf arg 0xf13) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" unused DT entry: DT_RPATH (type 0xf arg 0x6c1) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so success
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so" unused DT entry: DT_RPATH (type 0xf arg 0x3ed) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so success
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" unused DT entry: DT_RPATH (type 0xf arg 0x2e6) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" unused DT entry: DT_RPATH (type 0xf arg 0x6af) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (27496): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so success
I/jrelog  (27496): dlopen /data/app/net.kdt.pojavlaunch-Z094bcO-W6dGk5QRZG2SbQ==/lib/arm64/libopenal.so success
I/LIBGL   (27496): Initialising gl4es
I/LIBGL   (27496): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   (27496): Using GLES 2.0 backend
I/LIBGL   (27496): loaded: libGLESv2.so
I/LIBGL   (27496): loaded: libEGL.so
I/LIBGL   (27496): Using GLES 2.0 backend
I/LIBGL   (27496): Hardware Full NPOT detected and used
I/LIBGL   (27496): FBO are in core, and so used
I/LIBGL   (27496): PointSprite are in core, and so used
I/LIBGL   (27496): CubeMap are in core, and so used
I/LIBGL   (27496): BlendColor is in core, and so used
I/LIBGL   (27496): Blend Substract is in core, and so used
I/LIBGL   (27496): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (27496): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (27496): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (27496): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (27496): Extension GL_OES_depth24  detected and used
I/LIBGL   (27496): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (27496): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (27496): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (27496): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (27496): Extension GL_OES_texture_float  detected and used
I/LIBGL   (27496): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (27496): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (27496): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (27496): high precision float in fragment shader available and used
I/LIBGL   (27496): Max vertex attrib: 32
I/LIBGL   (27496): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (27496): Max texture size: 16384
I/LIBGL   (27496): Max Varying Vector: 31
I/LIBGL   (27496): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (27496): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (27496): Max Anisotropic filtering: 16
I/LIBGL   (27496): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   (27496): Hardware vendor is Qualcomm
I/LIBGL   (27496): GLSL 300 es supported
I/LIBGL   (27496): GLSL 310 es supported and used
I/LIBGL   (27496): sRGB surface supported
I/LIBGL   (27496): EGLImage to Texture2D supported
I/LIBGL   (27496): EGLImage to RenderBuffer supported
I/LIBGL   (27496): ignore MipMap
I/LIBGL   (27496): Targeting OpenGL 2.1
I/LIBGL   (27496): NPOT texture handled in hardware
I/LIBGL   (27496): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (27496): try to use VBO
I/LIBGL   (27496): glX Will try to recycle EGL Surface
I/LIBGL   (27496): Current folder is:/
I/jrelog  (27496): dlopen /data/app/net.kdt.pojavlaunch-Z094bcO-W6dGk5QRZG2SbQ==/lib/arm64/libgl4es_114.so success
I/jrelog  (27496): Done processing args
I/jrelog  (27496): Found JLI lib
I/jrelog  (27496): Calling JLI_Launch
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

[22:24:50] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:24:54] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at djz.a(SourceFile:625) [1.16.5.jar:?]
	at djz.<init>(SourceFile:409) [1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:177) [1.16.5.jar:?]
[22:24:54] [Render thread/INFO]: Setting user: ttt
[22:24:54] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[22:24:55] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[22:24:55] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[22:24:55] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[22:24:55] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
OSMDroid: using built-in libOSMesa_8.so
OSMDroid: unable to load: dlopen failed: library "libOSMesa_8.so" wasn't loaded and RTLD_NOLOAD prevented it
[0331/062457.093058:ERROR:elf_dynamic_array_reader.h(61)] tag not found

**Comment by khanhduytran0** [comment]
Don't try it

**Comment by khanhduytran0** [comment]
@LegacyGamerHD here is the result

**Comment by WesleyVanNeck** [comment]
> @LegacyGamerHD here is the result

duy it fucking works fine
