### ISSUE TITLE
[Request] Customizable button location

### ISSUE THREAD

**Issue by issuereporter292** [PojavLauncherTeam/PojavLauncher#114]
A way to move your controls around. For example i could move the hit button to the top so i can use my pointer finger to hit and my thumb to look around.

**Comment by khanhduytran0** [comment]
It's a part of custom control while I'm doing.

**Comment by artdeell** [comment]
> A way to move your controls around. For example i could move the hit button to the top so i can use my pointer finger to hit and my thumb to look around.

In progress

**Comment by khanhduytran0** [comment]
@issuereporter292 you can take a look at 2.5 although it is not finished yet.

**Comment by khanhduytran0** [comment]
It have more amazing features.
![_20200427_060144](https://user-images.githubusercontent.com/40482367/80322081-b2fc6980-884c-11ea-8649-43c62db169da.jpg)

**Comment by khanhduytran0** [comment]
This is added on Custom controls.
