### ISSUE TITLE
[BUG] The game crashes with Scannable mod

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1147]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
The game crashes when I use Scannable to scan blocks

**Add a log file if you want to see your bug fixed !**

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6245443/latestlog.txt)
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6245444/latestcrash.txt)
[crash-2021-04-01_17.28.06-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6245460/crash-2021-04-01_17.28.06-client.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2.Start 1.16.4 forge 35.1.37
3.Use the scanner with "Scanner Module: Rare Ores" in the game

### Expected behavior:
Display scan results normally

### Screenshots or videos:
not thing

**Platform:**
 - Device Model [Huawei Honor play3]
 - CPU architecture [aarch64] 
 - Android Version [9]
 - PojavLauncher Version [3.3.1.1_rel_20210330]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
It’s likely that there was conflicts in rendering. (maybe mod conflicts?)

**Comment by PTALTS-LK** [comment]
It has nothing to do with other mods, the game still crashes
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6251619/latest.log)
[crash-2021-04-02_23.37.11-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6251620/crash-2021-04-02_23.37.11-client.txt)


> 渲染中可能存在冲突。（也许mod冲突？）

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
