### ISSUE TITLE
[BUG] the bug was on 1.12.2 forge and 1.12.2 vanilla it was like any equipment was like bugged it was like one layer

### ISSUE THREAD

**Issue by notpvpking** [PojavLauncherTeam/PojavLauncher#1150]
![IMG_20210402_225023](https://user-images.githubusercontent.com/78834688/113426618-4bf51680-9406-11eb-9fe7-faed0b3cead0.jpg)
 The bug was make a sword look like a Toy so I hope you fix it.

**Comment by leetmussc** [comment]
They aren't bothering with this...

**Comment by khanhduytran0** [comment]
@notpvpking fill the template

**Comment by leetmussc** [comment]
Is that my RLCraft Lite modpack?
