### ISSUE TITLE
[错误] discord-rpc doesn't work

### ISSUE THREAD

**Issue by canyue-rgb** [PojavLauncherTeam/PojavLauncher#1152]
![Screenshot_20210403_105615_net kdt pojavlaunch_edit_105335136474030](https://user-images.githubusercontent.com/54691377/113466074-7d53fd80-946b-11eb-9ca7-0a9a13bf9e29.jpg)

Why can't I use the mod with discord-rpc

**Comment by canyue-rgb** [comment]
I will crash when using this mod with discord-rpc

**Comment by Lilith-Crimeow** [comment]
Discord RPC is unsupported

**Comment by SavagePy10** [comment]
> I will crash when using this mod with discord-rpc

It tries to load a .so file that requires glibc.

**Comment by SavagePy10** [comment]
I don't think pojav devs will add glibc to pojav for this reason:
1) It would require alot of work.
2) If u want to use glibc, u need to use proot to avoid bad syscall. It would decrease performance by A LOT.

**Comment by khanhduytran0** [comment]
Discord Android client doesn’t supports RPC.
