### ISSUE TITLE
[F-REQ]Can You Guys Make a Android 5.1.1  Of Pojav?

### ISSUE THREAD

**Issue by helloimziana** [PojavLauncherTeam/PojavLauncher#1153]
**Describe the solution you'd like**
A clear and concise description of what you want to happen:
I want to play Pojav on my older Devices

**Comment by khanhduytran0** [comment]
Minimum is Android 5.0, isn’t it *even below 5.1*?

**Comment by helloimziana** [comment]
what does that mean?

**Comment by pablodz** [comment]
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen:
> I want to play Pojav on my older Devices

PojavL is compatible with android 5.0+
However, there are other requirements to play fluent.

**Comment by CriticalRange** [comment]
> > **Describe the solution you'd like**
> > A clear and concise description of what you want to happen:
> > I want to play Pojav on my older Devices
> 
> PojavL is compatible with android 5.0+
> However, there are other requirements to play fluent.

Playing fluently is hard even on android 8 phone (my phone, 32-bit) which is definitely 32 bit and can't give more than 800mb, so 1.12.2 may be ok with 30fps on lowest settings but 1.13-1.17 can't be fully optimized

**Comment by FadingxNesto** [comment]
Minimum requirements: Android™ 5.0; 1GB RAM (only 1.12.2 or less)
Recommended requirements: Android™ 8.1; 4GB RAM (most of the versions) See

**Comment by FadingxNesto** [comment]
Well I Mean My Phone Is 64 Bits Soooo.... I Had No Problem
