### ISSUE TITLE
I can't play Minecraft 1.16.5 with fabric

### ISSUE THREAD

**Issue by XIAYM-gh** [PojavLauncherTeam/PojavLauncher#1154]
Log file:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6251951/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Setup fabric 1.16.5
3. download full assets
4. start fabric
5. Loading game
6. Crashed with code 1

**Platform:**
 - Device Model OPPO A57
 - CPU architecture  aarch64
 - Android Version 6.0.1
 - PojavLauncher Version latest release

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
It’s known issue, but there is a workaround:
- Go to `/storage/emulated/0/games/PojavLauncher/.minecraft/.fabric/remappedJars/minecraft-1.16.5`
- Rename `zipfstmp2400570136315251506.tmp` to `intermediary-fabric-loader-0.11.3-1.16.5.jar`

**Comment by XIAYM-gh** [comment]
Oh, thanks, I am going to rename it.

**Comment by XIAYM-gh** [comment]
Thanks!
