### ISSUE TITLE
[BUG] Game instantly crashes when pressing F3+ESC button!

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1156]
<it crashed> <I was just testing world edit and then when I pressed the shortcut it instantly crashes>
### Describe the bug

**Here: 
[crash-2021-04-03_07.56.33-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6252202/crash-2021-04-03_07.56.33-client.txt)
And this is latest log:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6252206/latestlog.txt)
**
### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(The crash log says render issue, I think restarting and doing it again would result in a crash.)*

### Expected behavior:
I expected invisible menu ...

**Platform:**
 - Oppo A12 (4/64)
 - Mediatek p35
 - Android Version 9 (pie)
 - Version 3.3.1.1_rel_20210321

**Comment by ebuild-1** [comment]
Bruh it deleted the summary :/

**Comment by Mathias-Boulay** [comment]
Perfectly works on the crocus gplay update.
Closing
