### ISSUE TITLE
[BUG] The game cannot be loaded using create3.1, and it is invalid after repeated loading several times

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1157]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
When the game is about to load, forge throws a "Description: Rendering overlay" error

**Add a log file if you want to see your bug fixed !**
[crash-2021-04-03_10.35.31-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6252390/crash-2021-04-03_10.35.31-client.txt)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6252392/latest.log)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6252398/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. start minecraft forge-35.1.37

### Expected behavior:
Start the game normally

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [Huawei honor play 3]
 - CPU architecture [aarch64] 
 - Android Version [9]
 - PojavLauncher Version [3.3.1.1_rel_20210330]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by T-CATHOME** [comment]
The zink beta is available.

**Comment by WesleyVanNeck** [comment]
> The zink beta is available.

Zink isn't beta but pre pre pre alpha

**Comment by WesleyVanNeck** [comment]
Also just don't use zink
