### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by Vadim27272727** [PojavLauncherTeam/PojavLauncher#1158]
Advise Shaders who will work at 60 frames per second or at least will work)

**Comment by Lilith-Crimeow** [comment]
https://github.com/Open4Es/Open4Es-Shader-Android

**Comment by Lilith-Crimeow** [comment]
Most likely won't run at 60 FPS, but they 100% work on SnapDragon CPUs

**Comment by ebuild-1** [comment]
> Most likely won't run at 60 FPS, but they 100% work on SnapDragon CPUs

Why my phone overheat much and has these weird dot things my chip is mediatek
![2021-04-04_02 03 40](https://user-images.githubusercontent.com/80798103/113502735-cd60bc00-9560-11eb-9546-7cd3c22f1877.png)
