### ISSUE TITLE
[BUG] black sky when using shaders on 32bits device

### ISSUE THREAD

**Issue by NickyisSneaking** [PojavLauncherTeam/PojavLauncher#1159]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>
Bug about the shaders on 32bits device
### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
2. Turn on the shaders
### Expected behavior:
I expected that would be no bug but when I turn on the shader the sky turns black and in a minute it crashes the game

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. MRD-LX2 (MRD-L22) ]
 - CPU architecture [e.g. armv8l ] 
 - Android Version [e.g. 9]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210321 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
not our issue

**Comment by ebuild-1** [comment]
Turn on the sky option in optifine, and also shaders doesn't work. But a shader converted for Android will work 
![2021-04-04_02 17 22](https://user-images.githubusercontent.com/80798103/113502612-fc2a6280-955f-11eb-84dd-103ebb6a7794.png)
![2021-04-04_02 04 05](https://user-images.githubusercontent.com/80798103/113502628-15331380-9560-11eb-80a4-57bf78764cd9.png)


The link of the converted shaders: https://github.com/Open4Es/Open4Es-Shader-Android
