### ISSUE TITLE
Minecraft crash 1.10.2 / redmi note 7 android 10

### ISSUE THREAD

**Issue by monleak** [PojavLauncherTeam/PojavLauncher#116]
---- Minecraft Crash Report ----
// My bad.

Time: 20/04/2020 22:31
Description: Rendering Block Entity

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bxk.a(SourceFile:126)
	at bqn.a(SourceFile:81)
	at bqn.a(SourceFile:43)
	at bqn.a(SourceFile:22)
	at bqf.a(SourceFile:129)
	at bqf.a(SourceFile:117)
	at boh.a(SourceFile:662)
	at bnz.a(SourceFile:1266)
	at bnz.b(SourceFile:1171)
	at bnz.a(SourceFile:1018)
	at bcx.av(SourceFile:991)
	at bcx.a(SourceFile:396)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at bxk$1.a(SourceFile:47)
	at bxk$1.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bxk.a(SourceFile:126)
	at bqn.a(SourceFile:81)
	at bqn.a(SourceFile:43)

-- Block Entity Details --
Details:
	Name: Skull // ard
	Block type: ID #144 (tile.skull // aoy)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-137,5,52), Chunk: (at 7,0,4 in -9,3; contains blocks -144,0,48 to -129,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #144 (tile.skull // aoy)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at b.a(SourceFile:245)
	at bqf.a(SourceFile:132)
	at bqf.a(SourceFile:117)
	at boh.a(SourceFile:662)
	at bnz.a(SourceFile:1266)
	at bnz.b(SourceFile:1171)
	at bnz.a(SourceFile:1018)
	at bcx.av(SourceFile:991)
	at bcx.a(SourceFile:396)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bnn['testchat'/23315089, l='MpServer', x=-149,81, y=4,00, z=95,58]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-152,8,61), Chunk: (at 8,0,13 in -10,3; contains blocks -160,0,48 to -145,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1580309771 game time, 4748787023 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 49 total; [bnn['testchat'/23315089, l='MpServer', x=-149,81, y=4,00, z=95,58], xx['§d§l§oDùng kit gopy để lấy sách!'/7, l='MpServer', x=-205,50, y=3,72, z=72,47], xx['§f§l§oViết xong thả vào phiến sắt, cảm ơn!'/8, l='MpServer', x=-205,50, y=3,47, z=72,47], xx['§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩'/11, l='MpServer', x=-163,50, y=9,72, z=61,44], xx['§d§lHƯỚNG DẪN §f§lBÁO LỖI§d§l & §f§lGÓP Ý'/12, l='MpServer', x=-163,50, y=9,47, z=61,44], xx['§3===================================================='/13, l='MpServer', x=-163,50, y=9,22, z=61,44], xx['§eTrong máy chủ minecraft lầy lội người chơi có thể'/14, l='MpServer', x=-163,50, y=8,97, z=61,44], xx['§egóp ý hoặc báo lỗi mọi lúc. Để báo lỗi hoặc góp ý'/15, l='MpServer', x=-163,50, y=8,72, z=61,44], xx['§evui lòng nhấn §f/kit baoloi§e hoặc §f/kit gopy§e sau đó'/16, l='MpServer', x=-163,50, y=8,47, z=61,44], xx['§eđiền nội dung ký tên và đóng dấu rùi dùng lệnh'/17, l='MpServer', x=-163,50, y=8,22, z=61,44], xx['§f/warp baoloi §ehoặc §f/warp gopy§e ném sách vào phiến'/18, l='MpServer', x=-163,50, y=7,97, z=61,44], xx['§eNgoài ra các bạn có thể báo lội và góp ý trực tiếp'/19, l='MpServer', x=-163,50, y=7,72, z=61,44], xx['§eở Group minecraft lầy lội hoặc Fanpage của máy chủ'/20, l='MpServer', x=-163,50, y=7,47, z=61,44], xx['§elà: §fminelayloi.com §e. Admin rất mong nhận được góp'/21, l='MpServer', x=-163,50, y=7,22, z=61,44], xx['§eý và báo lỗi nếu có để server ngày càng phát triển.'/22, l='MpServer', x=-163,50, y=6,97, z=61,44], xx['§3============================================================='/23, l='MpServer', x=-163,50, y=6,72, z=61,44], xx['§d§lChúc§f testchat §d§lchơi game vui vẻ <3 !'/24, l='MpServer', x=-163,50, y=6,47, z=61,44], xx['§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩'/25, l='MpServer', x=-163,50, y=6,22, z=61,44], xx['§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩'/26, l='MpServer', x=-151,31, y=9,72, z=49,81], xx['§d§lLƯU Ý CỞ BẢN TRONG MÁY CHỦ'/27, l='MpServer', x=-151,31, y=9,47, z=49,81], xx['§3===================================================='/28, l='MpServer', x=-151,31, y=9,22, z=49,81], xx['§eNếu mất laban bạn có thể dùng §f/kit tools §elấy lại'/29, l='MpServer', x=-151,31, y=8,97, z=49,81], xx['§eDùng lệnh §f/warp §eđể xem danh sách warp máy chủ'/30, l='MpServer', x=-151,31, y=8,72, z=49,81], xx['§eDùng lệnh §f/kit §eđể xem danh sách KIT có thể SD'/31, l='MpServer', x=-151,31, y=8,47, z=49,81], xx['§eDùng lệnh §f/menu §eđể xem menu của server bạn chơi'/32, l='MpServer', x=-151,31, y=8,22, z=49,81], xx['§eNạp thẻ tại website minelayloi.com'/33, l='MpServer', x=-151,31, y=7,97, z=49,81], xx['§eDùng lệnh §f/pshop §eđể mua Point donate trade đồ'/34, l='MpServer', x=-151,31, y=7,72, z=49,81], xx['§eDùng lệnh §f/help §eđể xem lệnh khác trong máy chủ'/35, l='MpServer', x=-151,31, y=7,47, z=49,81], xx['§3===================================================='/36, l='MpServer', x=-151,31, y=7,22, z=49,81], xx['§d§lChúc§f testchat §d§lchơi game vui vẻ <3 !'/37, l='MpServer', x=-151,31, y=6,97, z=49,81], xx['§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩'/38, l='MpServer', x=-151,31, y=6,72, z=49,81], xx['§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧'/39, l='MpServer', x=-139,53, y=9,72, z=61,63], xx['§d§lHƯỚNG DẪN §f§lTHÊM EMAIL §d§l&§f§l KHÔI PHỤC MẬT KHẨU'/40, l='MpServer', x=-139,53, y=9,47, z=61,63], xx['§3===================================================='/41, l='MpServer', x=-139,53, y=9,22, z=61,63], xx['§eDùng lệnh §f/email add <email> <nhaplaiemail> §eđể thêm email'/42, l='MpServer', x=-139,53, y=8,97, z=61,63], xx['§evd: §f/email add shinichi1234@gmail shinichi1234@gmail'/43, l='MpServer', x=-139,53, y=8,72, z=61,63], xx['§eDùng lệnh §f/email recover <email> §ekhi bạn quên mật khẩu'/44, l='MpServer', x=-139,53, y=8,47, z=61,63], xx['§evd: §f/email recover shinichi1234 §e(Hệ thống sẻ gữi code tới)'/45, l='MpServer', x=-139,53, y=8,22, z=61,63], xx['§eSau đó mở hộp thư email của bạn và làm theo đúng hướng dẫn.'/46, l='MpServer', x=-139,53, y=7,97, z=61,63], xx['§3===================================================='/47, l='MpServer', x=-139,53, y=7,72, z=61,63], xx['§d§lChúc§f testchat §d§lchơi game vui vẻ <3 !'/48, l='MpServer', x=-139,53, y=7,47, z=61,63], xx['§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧§9✩§e✧'/49, l='MpServer', x=-139,53, y=7,22, z=61,63], xx['§fDùng lệnh /maychu §fhoặc /kit tools §fnếu bị mất la bàn!'/50, l='MpServer', x=-151,50, y=8,00, z=65,50], xx['§3█§f███§3█§f█§3█§f█§3██§f██§3█§f█§3███§f███§3█§f█████§3█§f██§3█§f█§3█§f███§3█§f████§3██§f██§3█'/51, l='MpServer', x=-149,81, y=9,75, z=80,94], xx['§3██§f█§3██§f█§3█§f█§3███§f█§3█§f█§3█§f█████§3█§f████§3█§f█§3█§f█§3█§f█§3█§f███§3█§f███§3█§f██§3█§f█§3█'/52, l='MpServer', x=-149,81, y=9,50, z=80,94], xx['§3█§f█§3█§f█§3█§f█§3█§f█§3█§f█§3███§f█§3███§f███§3█§f████§3███§f██§3█§f████§3█§f███§3█§f██§3█§f█§3█'/53, l='MpServer', x=-149,81, y=9,25, z=80,94], xx['§3█§f███§3█§f█§3█§f█§3█§f██§3██§f█§3█§f█████§3█§f███§3█§f███§3█§f█§3█§f████§3█§f███§3█§f██§3█§f█§3█'/54, l='MpServer', x=-149,81, y=9,00, z=80,94], xx['§3█§f███§3█§f█§3█§f█§3█§f███§3█§f█§3███§f███§3███§f█§3█§f███§3█§f█§3█§f████§3███§f██§3██§f██§3█'/55, l='MpServer', x=-149,81, y=8,75, z=80,94], bno['Koz'/23339637, l='MpServer', x=-151,53, y=7,00, z=64,91]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.15-SNAPSHOT:a3ab2bf:1473) <- Spigot
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (armv8l) version 4.14.81-perf+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (Xiaomi Redmi Note 7 Pro, Android 9), The Android Project
	Memory: 23805776 bytes (22 MB) / 307802992 bytes (293 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.2
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 14 (v8l)

**Comment by artdeell** [comment]
This issue occurs on some servers because of plugin, that allows users to use /skin command, because (i think) skin is sent inside the protocol packet in Base64 format, and game fails to decode it. 

Also, this issue is duplicated, please close it.

**Comment by monleak** [comment]
> This issue occurs on some servers because of plugin, that allows users to use /skin command, because (i think) skin is sent inside the protocol packet in Base64 format, and game fails to decode it.
> 
> Also, this issue is duplicated, please close it.

how to fix this

**Comment by artdeell** [comment]
It tries to decode skull's skin sent inside the package
`Details:
Name: Skull // ard
Block type: ID #144 (tile.skull // aoy)
Block data value: 1 / 0x1 / 0b0001
Block location: World: (-137,5,52), Chunk: (at 7,0,4 in -9,3; contains blocks -144,0,48 to -129,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Actual block type: ID #144 (tile.skull // aoy)
Actual block data value: 1 / 0x1 / 0b0001`

**Comment by artdeell** [comment]
> > This issue occurs on some servers because of plugin, that allows users to use /skin command, because (i think) skin is sent inside the protocol packet in Base64 format, and game fails to decode it.
> > Also, this issue is duplicated, please close it.
> 
> how to fix this

There's no way for user to fix this. Try to play on less-featured server.

**Comment by artdeell** [comment]
Also, I said it's duplicate. Please close it.

**Comment by khanhduytran0** [comment]
> There's no way for user to fix this. Try to play on less-featured server.

Replace Java Google Guava with android version one will fix (not tested yet)
