### ISSUE TITLE
[Question] I have a question with fabric

### ISSUE THREAD

**Issue by XIAYM-gh** [PojavLauncherTeam/PojavLauncher#1161]
Today I tried playing fabric with optifine and optifabric, but optifine cannot load.

I'm using optifine version OptiFine_1.16.5_HD_U_G6
and folder /.minecraft/.optifine/ have these files:
Optifine-jarofthefree.jar
Optifine-mod.jar
zipfstmp7416631382762987334.tmp

So what's "zipfstmp7416631382762987334.tmp"'s correct name?

**Comment by khanhduytran0** [comment]
We might find it’s name but requires latestlog.txt
> fill the template

**Comment by XIAYM-gh** [comment]
oh ok
here is it
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6254528/latestlog.txt)

**Comment by XIAYM-gh** [comment]
wait, I found a message in the log file
[12:26:56] [ForkJoinPool-1-worker-4/WARN]: Non-Fabric mod JAR at "/storage/emulated/0/games/PojavLauncher/.minecraft/mods/OptiFine_1.16.5_HD_U_G6.jar", ignoring

Why it not is a fabric mod? In fact, when I play it on my computer, I sometimes have this problem, too, but when I restart the game, It works... But it is not available on Pojav Launcher...

**Comment by XIAYM-gh** [comment]
I think optifabric might not write any message about it into log files... I can't find them by myself.

**Comment by XIAYM-gh** [comment]
I think I can use Sodium mod. XD

**Comment by AutumnVN** [comment]
[OptiFine_1.16.5_HD_U_G6.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/6254558/OptiFine_1.16.5_HD_U_G6.zip)
unzip then paste these file to that folder, i have got this error before xd

**Comment by XIAYM-gh** [comment]
oh thanks, i tried to run minecraft JE in termux to get these files, but it do not have JavaFX XD

**Comment by XIAYM-gh** [comment]
Well, How to get them?
I cannot get them from any way.

**Comment by AutumnVN** [comment]
i got them from... random guy on youtube xd

**Comment by XIAYM-gh** [comment]
oh really? Can You give me his video's link pls?
