### ISSUE TITLE
There is a bug with zink(vulkan) opengl 4.6

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#1162]
I use the version in https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/711445039.The screen is tilted,and it is only black and white.
My device is HuaWei nova3,  cpu:kirin 970
![Screenshot_20210404_195651_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/113511527-bb2a5200-954f-11eb-84d9-e7158d571963.jpg)
![Screenshot_20210404_211354_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/113511529-bd8cac00-954f-11eb-9303-409c788ccc64.jpg)
![Screenshot_20210404_204848_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/113511532-bebdd900-954f-11eb-9093-f7a0b93a86eb.jpg)

**Comment by yejunjie10311031** [comment]
There is the latestlog.txt:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6254696/latestlog.txt)

**Comment by OwzygZawg** [comment]
Known issue! Did you change anything before playing? if not, it must be that it is not yet 100% the zink version

**Comment by WesleyVanNeck** [comment]
It's a dev build what do you expect

**Comment by yejunjie10311031** [comment]
Now I change the resolving power to 70%,and it is normal now!Now I can load PC shaders.
![Screenshot_20210405_074041_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/113524770-67942480-95a0-11eb-8ff3-5ed8992a6769.jpg)
![Screenshot_20210405_074429_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/113524774-6bc04200-95a0-11eb-9dc1-273a19664f62.jpg)

**Comment by OwzygZawg** [comment]
Os mesa Devs tests not is conpatible to my device! 😞

**Comment by jumperli** [comment]
Can u give me the debug link?

**Comment by yejunjie10311031** [comment]
@jumperli  https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/711445039

**Comment by yejunjie10311031** [comment]
@jumperli  Then choose zink(vulkan) there,and add -Dorg.lwjgl.opengl.libname=libOSMesa_8.so to jvm argument.
![Screenshot_20210405_081817](https://user-images.githubusercontent.com/62139629/113525526-08f29900-95e8-11eb-9e49-d15e4ea4e94d.jpg)

**Comment by yejunjie10311031** [comment]
Almost all PC shaders can run with it.
![Screenshot_20210405_082255_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525604-625ac800-95e8-11eb-8487-5be31d674b7f.jpg)
![Screenshot_20210405_082259_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525605-625ac800-95e8-11eb-9840-672437d9d1b0.jpg)
![Screenshot_20210405_082301_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525610-6686e580-95e8-11eb-856b-9333fc2cf5b6.jpg)

**Comment by OwzygZawg** [comment]
> @jumperli  Then choose zink(vulkan) there,and add -Dorg.lwjgl.opengl.libname=libOSMesa_8.so to jvm argument.
> ![Screenshot_20210405_081817](https://user-images.githubusercontent.com/62139629/113525526-08f29900-95e8-11eb-9e49-d15e4ea4e94d.jpg)
> 

Thank you

**Comment by OwzygZawg** [comment]
> Can u give me the debug link?

Os mesa Devs tests is Only for 64 bits

**Comment by jumperli** [comment]
> @jumperli https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/711445039

You are a totally helpful bro,

**Comment by OwzygZawg** [comment]
for now we still have the mesa devs test for arm7! i've seen it before ..

**Comment by jumperli** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/5/21 12:40 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: Failed to locate library: liblibOSMesa_8.so
	at org.lwjgl.system.Library.loadNative(Library.java:324)
	at org.lwjgl.system.Library.loadNative(Library.java:222)
	at org.lwjgl.system.Library.loadNative(Library.java:203)
	at org.lwjgl.system.Library.loadNative(Library.java:402)
	at org.lwjgl.system.Library.loadNative(Library.java:378)
	at org.lwjgl.opengl.GL.create(GL.java:108)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:90)
	at dew.<init>(SourceFile:106)
	at eam.a(SourceFile:21)
	at djw.<init>(SourceFile:447)
	at net.minecraft.client.main.Main.main(SourceFile:177)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.system.Library.loadNative(Library.java:324)
	at org.lwjgl.system.Library.loadNative(Library.java:222)
	at org.lwjgl.system.Library.loadNative(Library.java:203)
	at org.lwjgl.system.Library.loadNative(Library.java:402)
	at org.lwjgl.system.Library.loadNative(Library.java:378)
	at org.lwjgl.opengl.GL.create(GL.java:108)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:90)
	at dew.<init>(SourceFile:106)
	at eam.a(SourceFile:21)
	at djw.<init>(SourceFile:447)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1462802304 bytes (1395 MB) / 2192572416 bytes (2091 MB) up to 2192572416 bytes (2091 MB)
	CPUs: 8
	JVM Flags: 3 total; -Xms2186M -Xmx2186M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	Launched Version: 1.16.3
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.GL
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: <unknown>





Yeah maybe im the only one who has this

**Comment by jumperli** [comment]
> ---- Minecraft Crash Report ----
> // Uh... Did I do that?
> 
> Time: 4/5/21 12:40 AM
> Description: Initializing game
> 
> java.lang.UnsatisfiedLinkError: Failed to locate library: liblibOSMesa_8.so
> at org.lwjgl.system.Library.loadNative(Library.java:324)
> at org.lwjgl.system.Library.loadNative(Library.java:222)
> at org.lwjgl.system.Library.loadNative(Library.java:203)
> at org.lwjgl.system.Library.loadNative(Library.java:402)
> at org.lwjgl.system.Library.loadNative(Library.java:378)
> at org.lwjgl.opengl.GL.create(GL.java:108)
> at org.lwjgl.opengl.GL.(GL.java:90)
> at dew.(SourceFile:106)
> at eam.a(SourceFile:21)
> at djw.(SourceFile:447)
> at net.minecraft.client.main.Main.main(SourceFile:177)
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- Head --
> Thread: Render thread
> Stacktrace:
> at org.lwjgl.system.Library.loadNative(Library.java:324)
> at org.lwjgl.system.Library.loadNative(Library.java:222)
> at org.lwjgl.system.Library.loadNative(Library.java:203)
> at org.lwjgl.system.Library.loadNative(Library.java:402)
> at org.lwjgl.system.Library.loadNative(Library.java:378)
> at org.lwjgl.opengl.GL.create(GL.java:108)
> at org.lwjgl.opengl.GL.(GL.java:90)
> at dew.(SourceFile:106)
> at eam.a(SourceFile:21)
> at djw.(SourceFile:447)
> 
> -- Initialization --
> Details:
> Stacktrace:
> at net.minecraft.client.main.Main.main(SourceFile:177)
> 
> -- System Details --
> Details:
> Minecraft Version: 1.16.3
> Minecraft Version ID: 1.16.3
> Operating System: Linux (aarch64) version Android-10
> Java Version: 1.8.0-internal, Oracle Corporation
> Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
> Memory: 1462802304 bytes (1395 MB) / 2192572416 bytes (2091 MB) up to 2192572416 bytes (2091 MB)
> CPUs: 8
> JVM Flags: 3 total; -Xms2186M -Xmx2186M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
> Launched Version: 1.16.3
> Backend library: LWJGL version 3.2.3 SNAPSHOT
> Backend API: ~ERROR~ NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.GL
> GL Caps:
> Using VBOs: Yes
> Is Modded: Probably not. Jar signature remains and client brand is untouched.
> Type: Client (map_client.txt)
> CPU:
> 
> Yeah maybe im the only one who has this

Ps: I didnt reinstall the runtime

**Comment by OwzygZawg** [comment]
Not only are you,another friend of mine too!

**Comment by LANCECRAFT1104** [comment]
> Almost all PC shaders can run with it.
> ![Screenshot_20210405_082255_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525604-625ac800-95e8-11eb-8487-5be31d674b7f.jpg)
> ![Screenshot_20210405_082259_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525605-625ac800-95e8-11eb-9840-672437d9d1b0.jpg)
> ![Screenshot_20210405_082301_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525610-6686e580-95e8-11eb-856b-9333fc2cf5b6.jpg)

You are about to burn your GPU. Thatsy Ray Tracing rigth?

**Comment by ebuild-1** [comment]
> > Almost all PC shaders can run with it.
> > ![Screenshot_20210405_082255_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525604-625ac800-95e8-11eb-8487-5be31d674b7f.jpg)
> > ![Screenshot_20210405_082259_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525605-625ac800-95e8-11eb-9840-672437d9d1b0.jpg)
> > ![Screenshot_20210405_082301_com huawei himovie](https://user-images.githubusercontent.com/62139629/113525610-6686e580-95e8-11eb-856b-9333fc2cf5b6.jpg)
> 
> You are about to burn your GPU. Thatsy Ray Tracing rigth?

Yeah it's gonna be hot but that's depending on the cpu

**Comment by PeterScorPioN** [comment]
> Now I change the resolving power to 70%,and it is normal now!Now I can load PC shaders.
> ![Screenshot_20210405_074041_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/113524770-67942480-95a0-11eb-8ff3-5ed8992a6769.jpg)
> ![Screenshot_20210405_074429_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/113524774-6bc04200-95a0-11eb-9dc1-273a19664f62.jpg)

So what fps do you play with? And which phone do you have?

**Comment by PeterScorPioN** [comment]
Can a SD 845 handle a Chocapic medium for example?
