### ISSUE TITLE
[F-REQ] Me have a question!

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1163]
When will the mesas devs tests be available for 32-bit devices?

**Comment by WesleyVanNeck** [comment]
Not going to be 32 bit get a new device

**Comment by OwzygZawg** [comment]
> Not going to be 32 bit get a new device

It's easy for you to talk that way when you have a good cell phone! but do you think it's really easy to get all the money to buy a new device?

**Comment by Druxelite** [comment]
Do you really think it's that easy to add 32bit support on the osmesa build? I get 7 fps on my snapdragon 845, 8gb ram phone, how'd you expect a 32bit device to run it?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
