### ISSUE TITLE
[F-REQ]controllable mod compatibility

### ISSUE THREAD

**Issue by Minecrafterr1244** [PojavLauncherTeam/PojavLauncher#1164]
my problem is the touch buttons are very uncomfortable and I would like there to be compatibility with a mod called controllable.

my solution would be to add compatibility with that mod would be great

Another alternative would be to add control compatibility without the need for the mod, although I know you don't feel like that ...

not only do I demand compatibility with the controller, many users also want that is something that is needed at least to make compatibility with the controllable mod https://mrcrayfish.com/mods?id=controllable
Thanks for your attention

![Screenshot_20210404-132938](https://user-images.githubusercontent.com/81926121/113518127-e9a52e80-9549-11eb-9e7d-5fc10b5c624b.png)

**Comment by Minecrafterr1244** [comment]
And I'm sorry, my English is very bad

**Comment by ebuild-1** [comment]
I don't think that's gonna work with Android

**Comment by WesleyVanNeck** [comment]
this is in the works wayback and its not finised

**Comment by WesleyVanNeck** [comment]
also this is dublicated
