### ISSUE TITLE
[BUG] keyboard doesnt work properly in servers

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1165]
<IT POPS AND THEN IT DISAPPEARS IN SECONDS> <I WAS SOLVING A CAPTCHA AND THAT KEYBOARD DOESN'T WORK PROPERLY><b>Read before submit</b></summary>

### Describe the bug
AS I said its not working properly.

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6255834/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(IT ALWAYS HAPPENS EVERYTIME AND IM DONE)*

### Expected behavior:
I expected IT TO WORK...

### Screenshots or videos:
*Not possible*

**Comment by khanhduytran0** [comment]
@SamSam759 and nobody know what's your using __keyboard__.

**Comment by ebuild-1** [comment]
I'm using g board.

**Comment by ebuild-1** [comment]
@khanhduytran0

**Comment by SamSam759** [comment]
@khanhduytran0

**Comment by ebuild-1** [comment]
> @SamSam759 and nobody know what's your using **keyboard**.

This is what I meant about that keyboard 😠


https://user-images.githubusercontent.com/80798103/113547737-0d877380-9621-11eb-9c5d-36fada2fa234.mp4

**Comment by WesleyVanNeck** [comment]
> > @SamSam759 and nobody know what's your using **keyboard**.
> 
> This is what I meant about that keyboard 😠
> 
>  VID_20210405150930.mp4

jesus chill mate

**Comment by WesleyVanNeck** [comment]
also use latest build

**Comment by ebuild-1** [comment]
This is the latest build, I found it in the actions if not latest please
give me the link.

**Comment by ebuild-1** [comment]
@LegacyGamerHD

**Comment by khanhduytran0** [comment]
Out of memory 👀

**Comment by ebuild-1** [comment]
> Out of memory

Yeah I guess so, since it always happens when I'm in the middle of the game.
