### ISSUE TITLE
I try open4es shaders with vic modern warfare when I try to right click it's it's super zoom that I don't see the gun 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1167]
Normal
![Screenshot_2021-04-05-14-04-45-588_net kdt pojavlaunch](https://user-images.githubusercontent.com/76839710/113543023-1aec3000-9618-11eb-9e4b-f2108779f384.jpg)

When right click
![Screenshot_2021-04-05-14-04-57-471_net kdt pojavlaunch](https://user-images.githubusercontent.com/76839710/113542997-0d36aa80-9618-11eb-985f-ebf671dbe1cb.jpg)

**Comment by WesleyVanNeck** [comment]
not our issue
