### ISSUE TITLE
[BUG] pojav crashing on the latest Google Play release

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1168]
Bug

<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Whenever I click play the pojavlauncher crashes

**Add a log file if you want to see your bug fix**
#
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6256812/latestlog.txt)

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected to work properly

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model Samsung galaxy A30s
 - CPU architecture aarch64
 - Android Version 10
 - PojavLauncher Version Latest Release 

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
Please unban me on discord

**Comment by ebuild-1** [comment]
Why did you get banned lmfao

**Comment by ebuild-1** [comment]
Your reason of ban must've been bad

**Comment by ghost** [comment]
I just ad to dev mistakenly and I didn't knew

**Comment by ebuild-1** [comment]
> I just ad to dev mistakenly and I didn't knew

Wdym?

**Comment by ebuild-1** [comment]
@Avngrarnabgaming

**Comment by ghost** [comment]
I was actually getting invites for a server and tried dming all the ones I have on dms and mistakenly dmed the invites to Dev's so plzzz forgive me and unban

**Comment by ebuild-1** [comment]
Seems reasonable , I'm not a Dev tho.

**Comment by Harsh-bot-beep** [comment]
Imagine getting unbanned
This post was made by
MINECRAFTERHARS

**Comment by Tejas-Mahajan** [comment]
Pojavlauncher need more  ram

**Comment by Mathias-Boulay** [comment]
Incomplete logs, from a banned user.
Closing.

**Comment by kai-X-Gammi** [comment]
How to fix recentlog.txt check

**Comment by Duong662** [comment]
Tui bị ứng dụng trò chơi đã thoát với 1 mã kiểm tra nhật kí trình khởi chạy mong ad fit

**Comment by jddnbvfnndxznxxsbbzn** [comment]
Kkjrjejhehehdhfg

**Comment by Hao030100** [comment]
![Screenshot_20230727_052735_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140662702/e72564ba-1a48-466e-86ed-61c15ff2048f)

**Comment by Hao030100** [comment]
Giúp toi=))

Uploading XRecorder_27072023_053848.mp4…

**Comment by Duong662** [comment]
:))))

Vào 5:39, Th 5, 27 thg 7, 2023 Hao030100 ***@***.***> đã viết:
