### ISSUE TITLE
Weird entity and item textures in old alphas/betas

### ISSUE THREAD

**Issue by PeterScorPioN** [PojavLauncherTeam/PojavLauncher#1169]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
In the old alphas and betas the entity, player and item textures have a weird shadowy line. I don't actually know if this can be found on newer versions, but at least i found them in these pre-releases...

**Add a log file if you want to see your bug fixed !**

I don't think that this requires log.... Let me know if you need it.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Launch any old beta, or old alpha
3. Create a world
4. See all the entities and items having this weird shadow on them.

### Screenshots or videos:
![IMG_20210405_202838](https://user-images.githubusercontent.com/73193067/113605437-522a0380-964f-11eb-9746-9457a9057e35.jpg)
![IMG_20210405_202857](https://user-images.githubusercontent.com/73193067/113605454-59e9a800-964f-11eb-9a15-a1f00020e1c6.jpg)
![IMG_20210405_202909](https://user-images.githubusercontent.com/73193067/113605472-5f46f280-964f-11eb-9f8d-3a317b4467c5.jpg)

**Platform:**
 - Device Model [Xiaomi Pocophone F1 6/64]
 - CPU architecture [aarch64] 
 - Android Version [10]
 - PojavLauncher Version [Latest Release || Play store version]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by OwzygZawg** [comment]
Maybe Gl4es have bugs in old alphas!

**Comment by ebuild-1** [comment]
Bruh all you need to do is put the ***log*** file why don't you just put it? I'm having the same issues but it's not that harming so who cares anyway?

**Comment by PeterScorPioN** [comment]
> Bruh all you need to do is put the _**log**_ file why don't you just put it? I'm having the same issues but it's not that harming so who cares anyway?

It may not be that bad to play, i agree, but it needs to be fixed anyway. What about the log, i said that if devs will need the log, i will put it here. Also, since this glitch appears to be in every device, everyone can get the game's log.

**Comment by ebuild-1** [comment]
> > Bruh all you need to do is put the _**log**_ file why don't you just put it? I'm having the same issues but it's not that harming so who cares anyway?
> 
> It may not be that bad to play, i agree, but it needs to be fixed anyway. What about the log, i said that if devs will need the log, i will put it here. Also, since this glitch appears to be in every device, everyone can get the game's log.

**Just put the log man, it literally says "put lastlog if you want your big fixed!"**
I'm having issues with the shaders too but I'm not reporting it since it will be fixed if I restart the shader.

**Comment by Harsh-bot-beep** [comment]
Instead Of Bug Fix Sam Is Doing Big Fix Nice

**Comment by ebuild-1** [comment]
Yeah I need to restart the shader to fix the shadows. A bit annoying but it works.

**Comment by Harsh-bot-beep** [comment]
> Yeah I need to restart the shader to fix the shadows. A bit annoying but it works.

*Confused Screaming*

**Comment by SprainedSpark89** [comment]
same issue

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build by auto selection
