### ISSUE TITLE
[BUG] Forge 1.12.2 FTB Direwolf20 doesn't load

### ISSUE THREAD

**Issue by Lilith-Crimeow** [PojavLauncherTeam/PojavLauncher#1170]
### 1.12.2 FTB Direwolf20 doesn't load.

**Add a log file if you want to see your bug fixed !**

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Load Forge 1.12.2 and the FTB Direwolf20 modpack
3. It won't load past the Mojang Logo and log line shown in the Screenshot

### Expected behavior:
I expected it to load.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model : Samsung Galaxy Tab s5e
 - CPU architecture : aarch64
 - Android Version : 10
 - PojavLauncher Version : Latest non OSMesaDev Build :(https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/684880890)
![Screenshot_20210403-202136_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/80209203/113621422-4563da80-9664-11eb-9726-896c31f15df0.jpg)
[latestlog-FTB-Direwolf-20.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6260419/latestlog-FTB-Direwolf-20.txt)

**Comment by khanhduytran0** [comment]
> java.lang.OutOfMemoryError: Java heap space
>    at com.google.common.collect.Lists.newArrayListWithCapacity(Lists.java:190)

Try set higher RAM 👀

**Comment by Lilith-Crimeow** [comment]
I set the JVM launch argument to -Xms1G -Xmx4G, set the RAM slider to 1.5GB (it assigned 1.2~GB on launch), and it crashed again
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6271927/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
Only the slider matters but it will eat more than 1.5GB to launch such a modpack
Maybe push to 2-2.5GB ?

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
