### ISSUE TITLE
[Bug] Can't login with Microsoft login

### ISSUE THREAD

**Issue by Git-North** [PojavLauncherTeam/PojavLauncher#1172]
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
When I try to login with my Microsoft account it redirects me to Microsoft I login then nothing happens

**Add a log file if you want to see your bug fixed !**

_It didn't generate any logs file_

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Press Login with Microsoft
3. Login

### Expected behavior:
I expected it to log in

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [Mi 8 lite 6/128]
 - CPU architecture [aarch64] 
 - Android Version [10]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210321]

<details> <summary><b>Yes I have bought the game in minecraft.net I can login in my computer aswell.

<details> <summary><b>
After the first login because I checked the stay signed in while entering my Microsoft info it just redirects me to Microsoft for a split second and opens the launcher again</b></summary>
<br>
</b></summary>
<br>
<pre>

</pre>
</details>

**Comment by LegacyGamerHD** [comment]
grat bug next time report your issue and fill the template

**Comment by khanhduytran0** [comment]
@LegacyGamerHD wasn't he filled??

But I’m confusing at this
> Device Model [Mi 8 lite 8/128]
CPU architecture [aarch64]
Android Version [10]
PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by Git-North** [comment]
Yes I did fill it

**Comment by khanhduytran0** [comment]
But is it your device (mi 8 lite)?

**Comment by Git-North** [comment]
Yes

**Comment by LegacyGamerHD** [comment]
> Yes I did fill it

well name is blank  and  it no details about the bug

**Comment by khanhduytran0** [comment]
> Yes

So maybe try this... https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/720086194

**Comment by WesleyVanNeck** [comment]
> > Yes I did fill it
> 
> well name is blank and  no log

**Comment by Git-North** [comment]
> > Yes I did fill it
> 
> well name is blank and it has no details about the bug

While filling the form I forgot to fill the title

**Comment by khanhduytran0** [comment]
> > Yes I did fill it
> 
> well name is blank and no log

nah does login screen gives log?

**Comment by Git-North** [comment]
> > > Yes I did fill it
> > 
> > 
> > well name is blank and no log
> 
> nah does login screen gives log?

İt didn't have me any log file as I stated above

**Comment by WesleyVanNeck** [comment]
> > > Yes I did fill it
> > 
> > 
> > well name is blank and no log
> 
> nah does login screen gives log?

it had a launcher log right  i know there were logs for it some point

**Comment by khanhduytran0** [comment]
> > Yes
> 
> So maybe try this... https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/720086194

What about this?

**Comment by khanhduytran0** [comment]
> it had a launcher log right i know there were logs for it some point

@LegacyGamerHD nah^2

- latestlog.txt: Ingame log and crashes, but this issue is on login stage.
- latestcrash.txt: launcher crashes, but he said it was not crashes.

**Comment by Git-North** [comment]
> it had a launcher log right i know there were logs for it some point

I checked the file directory the only txt file there is options.txt

**Comment by Git-North** [comment]
> > it had a launcher log right i know there were logs for it some point
> 
> @LegacyGamerHD nah^2
> 
> * latestlog.txt: Ingame log and crashes, but this issue is on login stage.
> * latestcrash.txt: launcher crashes, but he said it was not crashes.

İts in the .Minecraft right?

**Comment by Git-North** [comment]
> > > Yes
> > 
> > 
> > So maybe try this... https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/720086194
> 
> What about this?

Can't install the APK files

**Comment by Git-North** [comment]
The file that didn't do anything

> > > Yes
> > 
> > 
> > So maybe try this... https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/720086194
> 
> What about this?

**Comment by LANCECRAFT1104** [comment]
Did you buy minecraft?

**Comment by Git-North** [comment]
> Did you buy minecraft?

Yes
From minecraft.net

**Comment by Git-North** [comment]
It was because of Miui's bad browser the app works fine

**Comment by ebuild-1** [comment]
Huh so you successfully logged in to the minecraft account or what I'm confused????
