### ISSUE TITLE
OpenGL

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#1173]
![Screenshot_2021-04-06-18-32-40-13](https://user-images.githubusercontent.com/75970303/113698054-a17f3b00-9706-11eb-9246-699fa5332dd4.png)

This is wrong I have OpenGL ES 3.1+.

**Comment by khanhduytran0** [comment]
@LANCECRAFT1104 bruh Minecraft Java does not use OpenGL ES.

**Comment by khanhduytran0** [comment]
Well, just for you know, OpenGL ES does not have version 4.x.
![image](https://user-images.githubusercontent.com/40482367/113706962-70543a00-9709-11eb-9b62-b87ddc0ca8ff.jpeg)

**Comment by ebuild-1** [comment]
> Well, just for you know, OpenGL ES does not have version 4.x.
> ![image](https://user-images.githubusercontent.com/40482367/113706962-70543a00-9709-11eb-9b62-b87ddc0ca8ff.jpeg)

Sheeeeeeeeesssshhhhh 3 fps looking hot 🥵🥵🥵🥴🥴🥴🥴🥴🥵🥵🥵🥶🥶🥶😵😵😵😩😩

**Comment by LANCECRAFT1104** [comment]
> Well, just for you know, OpenGL ES does not have version 4.x.
> ![image](https://user-images.githubusercontent.com/40482367/113706962-70543a00-9709-11eb-9b62-b87ddc0ca8ff.jpeg)

OS Mesa Dev Test don't work on my phone.
