### ISSUE TITLE
[BUG] infinite loading 

### ISSUE THREAD

**Issue by calex112** [PojavLauncherTeam/PojavLauncher#1175]
When i load forge it has an infinite loading screen after selecting play. I use version 1.0 of pojavlauncher because when i use the latest it crashes. I’m following the tutorial made by LAZZA MCPE I can do every other version except for forge please help me

Specs

iphone: Iphone SE (2020)

IOS: Ios 14.3

I use unc0ver jailbreak

**Comment by OwzygZawg** [comment]
Hey You can't report on the Pojavlauncher IOS here! here is just for the Android Pojavlauncher!

**Comment by OwzygZawg** [comment]
Report to ios here: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues

**Comment by Harsh-bot-beep** [comment]
Lol

**Comment by OwzygZawg** [comment]
Not is funny!
