### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by ceifadorK0** [PojavLauncherTeam/PojavLauncher#1176]
![Screenshot_2021-04-06-19-46-27-293_net kdt pojavlaunch](https://user-images.githubusercontent.com/82063986/113787624-bdd4a500-9711-11eb-92da-05bf28386584.jpg)

<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by ceifadorK0** [comment]
I'm not able to log in

**Comment by ebuild-1** [comment]
You need to check both of it :/

**Comment by khanhduytran0** [comment]
@ceifadorK0 nothing filled, **fill da template**
