### ISSUE TITLE
[BUG] Mouse Being Bugged Often

### ISSUE THREAD

**Issue by Harsh-bot-beep** [PojavLauncherTeam/PojavLauncher#1178]
### Describe the bug
Mouse DoesNot Work At All

### Expected behavior:
I expected it to work

### Screenshots or videos:
Mouse DONOT Affect Game Click Donot Get Accesssed 

**Platform:**
 - Device Model: Redmi 9 `power
` - CPU architecture: probably aarch64
 - Android Version:10
 - PojavLauncher Version:Play Store Latest
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6269181/latestlog.txt)
I donot know how to attach :/

**Comment by Harsh-bot-beep** [comment]
@artdeell  Fix This Pls

**Comment by khanhduytran0** [comment]
@Harsh-bot-beep enable da fullscreen plz

**Comment by Harsh-bot-beep** [comment]
Ok Let Me Try

**Comment by Harsh-bot-beep** [comment]
Donot Close This Issue For Now
Also My FullScreen Is Alwyas On. To Improve Performance

**Comment by Harsh-bot-beep** [comment]
It Is Working For Now

**Comment by khanhduytran0** [comment]
So why you want keep this open and trigger Shift At The First Of Character?

**Comment by Harsh-bot-beep** [comment]
Shift? This May Happen Agian So I Can Tell Without Making a New Issue
Also How To Disable Notifications For Issue I Am Getting 100 emails per month

**Comment by Harsh-bot-beep** [comment]
@khanhduytran0  how to disable this notification 😐🙃

**Comment by khanhduytran0** [comment]
Just close this issue :)

**Comment by Harsh-bot-beep** [comment]
I AM Getting Notifications from every issue :|

**Comment by khanhduytran0** [comment]
Maybe you mean this...
![image](https://user-images.githubusercontent.com/40482367/113817472-97117f80-97a0-11eb-9d5b-a15a21670943.jpeg)

**Comment by Harsh-bot-beep** [comment]
@everyone help plz

**Comment by Harsh-bot-beep** [comment]
Ohhh

**Comment by Harsh-bot-beep** [comment]
Where is notifications button bruh

**Comment by khanhduytran0** [comment]
> @everyone help plz

Bruh GitHub is not a discord server

**Comment by khanhduytran0** [comment]
Bruh^2 go to the main repo page
https://github.com/PojavLauncherTeam/PojavLauncher

**Comment by Harsh-bot-beep** [comment]
Me dumb

**Comment by Harsh-bot-beep** [comment]
> > @everyone help plz
> 
> Bruh GitHub is not a discord server

Well I am 12 and I am banned :( This Sucks

**Comment by khanhduytran0** [comment]
Just wait for another year when you enough 13 and come back :)

**Comment by Harsh-bot-beep** [comment]
Pls UnBan :( sed noises in india its rated for 12+

**Comment by Harsh-bot-beep** [comment]
> Just wait for another year when you enough 13 and come back :)

I will be in my boarding school
Novadya 
Because I Have Given Exam Among 15000 Students to pass this in 2nd as a reward we get 6th-12th free hostel :l after cornoa I will be in there.

**Comment by Harsh-bot-beep** [comment]
Sed Life :/ This Life Is Hard Without Pojav Server

**Comment by Harsh-bot-beep** [comment]
FunFact: if you open #pojav in youtube my video will be in second psoition approve me

**Comment by Harsh-bot-beep** [comment]
If it was discord I would probably see me banned for off topic

**Comment by Harsh-bot-beep** [comment]
Pls UnBan I OtherWise I Do More Offtopic :)

**Comment by Harsh-bot-beep** [comment]
Plot Twsit: I am Gonna Do A Feature Request 
/UnBan @MINECRAFTERHARS because he help :) Xd
