### ISSUE TITLE
[Ban Appeal] I AM Banned For Wrong Reason

### ISSUE THREAD

**Issue by Harsh-bot-beep** [PojavLauncherTeam/PojavLauncher#1179]
Pls UnBan SINCE ITS RATED FOR 12+ IN INDIA

**Comment by Harsh-bot-beep** [comment]
Do it

**Comment by Harsh-bot-beep** [comment]
@artdeell 
@LegacyGamerHD 
@khanhduytran0 
I request

**Comment by WesleyVanNeck** [comment]
Sure thing I wont unban Am not Available rn

**Comment by WesleyVanNeck** [comment]
> Pls UnBan SINCE ITS RATED FOR 12+ IN INDIA

Also 12+ india I don't believe so
