### ISSUE TITLE
[Request] Can someone give me a java alt or something

### ISSUE THREAD

**Issue by TheCloudGaming** [PojavLauncherTeam/PojavLauncher#118]
I think i can connect to hypixel but i need a java account
![Screenshot_20200420-172808_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/64049894/79812173-fb87c480-832c-11ea-8275-13f66559ffcf.jpg)

**Comment by khanhduytran0** [comment]
If your device is Android 5 you can connect premium servers. ~~Alt account... there's some in Google.~~ piracy! buy the game.

**Comment by TheCloudGaming** [comment]
nvm i got my hands on a friends and I tested it it said "Disconnected"

**Comment by khanhduytran0** [comment]
> nvm i got my hands on a friends and I tested it it said "Disconnected"

Because your device is android > 5
