### ISSUE TITLE
[Proof] Ban Appeal 2

### ISSUE THREAD

**Issue by Harsh-bot-beep** [PojavLauncherTeam/PojavLauncher#1180]
![Screenshot_2021-04-07-12-04-52-247_com android vending](https://user-images.githubusercontent.com/76815433/113821519-d4264380-9799-11eb-8617-05a07785e193.jpg)

**Comment by Harsh-bot-beep** [comment]
Now?

**Comment by Harsh-bot-beep** [comment]
I Give Up......

**Comment by Harsh-bot-beep** [comment]
I AM Sorry For Making 2 Issues But Just UnBan Nothing Will Wring Happen To Me :|

**Comment by WesleyVanNeck** [comment]
Tos is 13+
