### ISSUE TITLE
[QUESTION] how do I paste in Minecraft Java using Ctrl?

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1182]
There's no Ctrl button in the custom controls, I want to paste my stuff, all it had is Ctrl+left and right. How do I paste it?????? I know the paste combination is Ctrl + c+v

**Comment by AutumnVN** [comment]
hacker's keyboard on play store

**Comment by ebuild-1** [comment]
i will search it, but what's the advantage **"hackers"** keyboard do?

**Comment by ebuild-1** [comment]
Oh so it acts like a mobile pc keyboard thanks!

**Comment by ebuild-1** [comment]
Bruh ctrl doesn't work on minecraft java man are you kidding me?
Ctrl + c + v works fine in other apps but it doesnt work in minecraft java i tried it so many times man......

**Comment by khanhduytran0** [comment]
Isn’t control in key combination?

**Comment by ebuild-1** [comment]
> Isn’t control in key combination?

Can you please show me how? Thanks.

**Comment by Harsh-bot-beep** [comment]
How To Do It:
Step1:Go To Discord Pojav
Step2: Type *UnBan (MY-ID)
STEPO30- done

**Comment by khanhduytran0** [comment]
> How To Do It:
> Step1:Go To Discord Pojav
> Step2: Type *UnBan (MY-ID)
> STEPO30- done

Step 4: ban u from GitHub...

**Comment by khanhduytran0** [comment]
> > Isn’t control in key combination?
> 
> Can you please show me how? Thanks.

You can discover it in custom controls settings :eyes:

**Comment by ebuild-1** [comment]
> > > Isn’t control in key combination?
> > 
> > 
> > Can you please show me how? Thanks.
> 
> You can discover it in custom controls settings

Ik but I tried it and it didn't work I tried Ctrl+c on one button and Ctrl+v on the other one.

**Comment by khanhduytran0** [comment]
You need version 1.13+

**Comment by ghost** [comment]
how does it work i can probably paste a word or phrase by copying it outside of the game then paste it on the game but in in-game i cant copy
