### ISSUE TITLE
[F-REQ] [FIX CHAT]

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#1185]
**Is your feature request related to a problem? Please describe.**

>Problem: Chat Issue

`More Info: Please Fix The Chat Location `
`Why: Since In Minecraft Java, The Chat Is Located At Bottom. And When You Type Anything In Chat In Pojav,  The Keyboard Hides It, Making It Difficult For You To See What You Have Typed`

**Describe the solution you'd like**

>Make The Chat To Appear On The Middle Of The Screen When We Open Chat Or Type Anything 

**Describe alternatives you've considered**

>Maybe A Chat Location Adjuster In Launcher Settings

**Additional context**

>Currently None

**Comment by AutumnVN** [comment]
use gboard, it can be floating on screen and dont hide the chat

**Comment by WesleyVanNeck** [comment]
Cant be changed because it's in game
