### ISSUE TITLE
[BUG] crash after a while

### ISSUE THREAD

**Issue by PastMC** [PojavLauncherTeam/PojavLauncher#1187]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

crash after a while in a forge
Log: https://pastebin.com/52zs5R1D

**Platform:**
 - Device Model meizu m6s/32
 - CPU architecture aarch64
 - Android Version 7.1.2
 - PojavLauncher Version version 3.3.1.1_rel_20210305

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
This was not at first, but now it has appeared
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
Give it more ram

**Comment by PastMC** [comment]
No work I launch default version too crash

**Comment by khanhduytran0** [comment]
Very likely you have outdated version :eyes:

**Comment by PastMC** [comment]
I'm install last dev build and too crash i'm use 1.12.2 version

**Comment by PastMC** [comment]
And by the way, I noticed that if you delete the .minecraft folder and download the default version 1.12.2 without forge, there will be no crash after installing the forge, it crashes

**Comment by Pochi336** [comment]
@khanhduytran0 

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6291892/latestlog.txt)

I also has an experience i notice that the crash occurs when we are rendering while running , i almost stayed for an hour? on my recent chunks but when i explore further . It crashes
I also read the logs it seems similar with my experience.

This was the line that i was talking about :
[FATAL:crashpad_client_linux.cc(552)] Render process (13226)'s crash wasn't handled by all associated  webviews, triggering application crash.

Device : Vivo V11i
Ram : 4gb
Rom : 128
Android : 10
Kernel Arch. aarch64
Ram Allocated : 1538mb
Renderer : Opengl ES 3.0
Client : 1.16.5 Optifine_HD_U_G7 (Not Forged)

**Comment by LedyBacer** [comment]
Same bug. For me all fine without optifine, with optifine game random crash without errors in log file. With jvm arg "-Dorg.lwjgl.opengl.libname=libgl4es_115.so" and with optifine game works ok, but have very poor performanse.

**Comment by khanhduytran0** [comment]
> [FATAL:crashpad_client_linux.cc(552)] Render process (13226)'s crash wasn't handled by all associated webviews, triggering application crash.

@Pochi336 just ignore it. It was crash on web viewer and so unrelated to the game crash.

**Comment by khanhduytran0** [comment]
And also is setting 3/4 memory size is good?

**Comment by khanhduytran0** [comment]
Closing until further response.
