### ISSUE TITLE
[F-REQ] Optimize The Launcher!

### ISSUE THREAD

**Issue by Harsh-bot-beep** [PojavLauncherTeam/PojavLauncher#1190]
Damn Whenever I Play With a Decent Settings 
It Lags at 48fps and Heats Up A Lot!

Try Focusing On Optimization Instead Of Crodwin/Laungage.

Average Fps While Playing- 
Optifine- 45-50
Sodium- 45-50
:|

**Comment by Harsh-bot-beep** [comment]
Specs:
Redmi 9 Power
64Gb 4Gb
662snap
604 aderno
64 Bit

**Comment by khanhduytran0** [comment]
:nah:
we are not openjdk developer so we know nothing around optimizing openjdk.
also don't use zink renderer or you will just get bad fps

**Comment by khanhduytran0** [comment]
Also bruh crowdin is community translation, Do you mean stop translation and focus on optimization?? Wtfman

**Comment by Harsh-bot-beep** [comment]
Zink Is Relased?
Btw I Just Know Crowdin SomeWhat Generates Laungage Or Somethibg :/

**Comment by khanhduytran0** [comment]
Also if you are not on Zink, make sure vsync turned off and max fps is unlimited.

**Comment by Harsh-bot-beep** [comment]
Ok I Use Google Play Version What Should I Do?

**Comment by khanhduytran0** [comment]
> Btw I Just Know Crowdin SomeWhat Generates Laungage Or Somethibg :/

No, Crowdin is place to contribute translation from everyone.

**Comment by Harsh-bot-beep** [comment]
:| ok well

**Comment by Harsh-bot-beep** [comment]
Pls Help I Cannot Play Java Like 45 Fps

**Comment by Harsh-bot-beep** [comment]
SO HOT PHONE MY PHONE IS READY TO COOK BEEEFFFFFFF

**Comment by Harsh-bot-beep** [comment]
I Have Tryed Game Driver It Seemed Unstable
While I Tryed System Driver IT Was Preety Stable For Some Time Now IT Again Lags

**Comment by Harsh-bot-beep** [comment]
@khanhduytran0  help what should I do

**Comment by Harsh-bot-beep** [comment]
Rip
KhanDuyTran
2018-2021

**Comment by khanhduytran0** [comment]
:facepalm:

**Comment by khanhduytran0** [comment]
Get Da Better Phone

**Comment by DR4GEND** [comment]
😂

**Comment by ghost** [comment]
😂

**Comment by khanhduytran0** [comment]
@Harsh-bot-beep 

<details> <summary><b> also you said play java but not Minecraft java, sound like invalid issue  </b></summary>
<br>
:trollface: 
</details>
Also fill da template

**Comment by Harsh-bot-beep** [comment]
> Get Da Better Phone

DA DUCK I PURCHASED NEW ONE LAST TWO WEEKS AGO

**Comment by Harsh-bot-beep** [comment]
> Also

Duy Trolling For 24 Hours Straight

**Comment by LANCECRAFT1104** [comment]
Use my pro JVM Args

**Comment by LANCECRAFT1104** [comment]
If you have 4GB RAM divide it into 4.
Use this:

-Xms1000M -Xmx1000M

And set your memory allocation exactly 1000.

Play 1.12.2 and below your FPS will run 50+.

**Comment by LANCECRAFT1104** [comment]
I have 3GB Ram I use 750MB I run 40+ PFS

**Comment by LANCECRAFT1104** [comment]
-Xmx1G -Xms1G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10

Try this and set your memory allocation exactly to 1000. If you are playing 1.16+ 
Add this
-Dorg.lwjgl.opengl.libname=libgl4es_115.so

**Comment by LANCECRAFT1104** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/668

**Comment by WesleyVanNeck** [comment]
> > Get Da Better Phone
> 
> DA DUCK I PURCHASED NEW ONE LAST TWO WEEKS AGO

next time look at specs before you buy a phone

**Comment by OwzygZawg** [comment]
Buy new phone better

**Comment by OwzygZawg** [comment]
> Damn Whenever I Play With a Decent Settings
> It Lags at 48fps and Heats Up A Lot!
> 
> Try Focusing On Optimization Instead Of Crodwin/Laungage.
> 
> Average Fps While Playing-
> Optifine- 45-50
> Sodium- 45-50
> :|

Correction * whenever I change the settings to make them decent
It lags at 48fps and heat a lot!

Try to focus on optimization, instead of crodwin update language!

Average fps during the game-
Optifine- 45 and 50 fps
Sodium- 45 and 50 fps *

**Comment by OwzygZawg** [comment]
In fact, it is not the problem of the Pojavlauncher developers if your phone is potato!

**Comment by EnderBrine99FOX** [comment]
> Damn Whenever I Play With a Decent Settings
> It Lags at 48fps and Heats Up A Lot!
> 
> Try Focusing On Optimization Instead Of Crodwin/Laungage.
> 
> Average Fps While Playing-
> Optifine- 45-50
> Sodium- 45-50
> :|

Your Guys Actually Doing Something With Your Mobiles I Can Run Minecraft 1.16.5 optifine With 120fps
![Screenshot_20210408_211950_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/114251278-2ab59c80-99a9-11eb-9b9e-5e034ee097ad.jpg)

My Device Info:
Huawei Nova 3i
Rom:128Gb
Ram:4Gb
CPU:Kirin 710

I Use 1300 Mb of Ram For Pojavlauncher

**Comment by OwzygZawg** [comment]
> > Damn Whenever I Play With a Decent Settings
> > It Lags at 48fps and Heats Up A Lot!
> > 
> > Try Focusing On Optimization Instead Of Crodwin/Laungage.
> > 
> > Average Fps While Playing-
> > Optifine- 45-50
> > Sodium- 45-50
> > :|
> 
> Your Guys Actually Doing Something With Your Mobiles I Can Run Minecraft 1.16.5 optifine With 120fps
> ![Screenshot_20210408_211950_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/114251278-2ab59c80-99a9-11eb-9b9e-5e034ee097ad.jpg)
> 
> My Device Info:
> Huawei Nova 3i
> Rom:128Gb
> Ram:4Gb
> CPU:Kirin 710
> 
> I Use 1300 Mb of Ram For Pojavlauncher

I can't even get half of that!

**Comment by OwzygZawg** [comment]
> > Damn Whenever I Play With a Decent Settings
> > It Lags at 48fps and Heats Up A Lot!
> > 
> > Try Focusing On Optimization Instead Of Crodwin/Laungage.
> > 
> > Average Fps While Playing-
> > Optifine- 45-50
> > Sodium- 45-50
> > :|
> 
> Your Guys Actually Doing Something With Your Mobiles I Can Run Minecraft 1.16.5 optifine With 120fps
> ![Screenshot_20210408_211950_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/114251278-2ab59c80-99a9-11eb-9b9e-5e034ee097ad.jpg)
> 
> My Device Info:
> Huawei Nova 3i
> Rom:128Gb
> Ram:4Gb
> CPU:Kirin 710
> 
> I Use 1300 Mb of Ram For Pojavlauncher

Remember 1300 mb of RAM for Pojavlauncher is Only for devices 64 bits guys!

**Comment by LANCECRAFT1104** [comment]
> > Damn Whenever I Play With a Decent Settings
> > It Lags at 48fps and Heats Up A Lot!
> > Try Focusing On Optimization Instead Of Crodwin/Laungage.
> > Average Fps While Playing-
> > Optifine- 45-50
> > Sodium- 45-50
> > :|
> 
> Your Guys Actually Doing Something With Your Mobiles I Can Run Minecraft 1.16.5 optifine With 120fps
> ![Screenshot_20210408_211950_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/114251278-2ab59c80-99a9-11eb-9b9e-5e034ee097ad.jpg)
> 
> My Device Info:
> Huawei Nova 3i
> Rom:128Gb
> Ram:4Gb
> CPU:Kirin 710
> 
> I Use 1300 Mb of Ram For Pojavlauncher

If you look at the sky your FPS will run 60+FPS

**Comment by EnderBrine99FOX** [comment]
@LANCECRAFT1104 No Even With The Gameplay I Get 120-70 Fps With 12 Render Distance

**Comment by cseanx** [comment]
mine also heats up like a microwave, but idrc

**Comment by EnderBrine99FOX** [comment]
> mine also heats up like a microwave, but idrc

LOL Me 2😔

**Comment by ghost** [comment]
Now we don't need microwave 
Our Phone is good to warn foods

**Comment by LANCECRAFT1104** [comment]
What are you talking about?

**Comment by OwzygZawg** [comment]
> Agora não precisamos de microondas
> Nosso telefone é bom para avisar os alimentos

"WTF"

**Comment by Pochi336** [comment]
I Have a mediatek but PojavLauncher doesnt cook my phone. Why is that. i use @LANCECRAFT1104 JVM args for 4gb ram and it runs the game too smooth.
Thanks to Him!!

**Comment by Harsh-bot-beep** [comment]
Closing This Because Opened In anger

**Comment by Harsh-bot-beep** [comment]
@LANCECRAFT1104  Thx Let Me Try

**Comment by Harsh-bot-beep** [comment]
> > > Get Da Better Phone
> > 
> > 
> > DA DUCK I PURCHASED NEW ONE LAST TWO WEEKS AGO
> 
> next time look at specs before you buy a phone

This is india we are Bankrupcted 😂 it's not bad though

**Comment by Harsh-bot-beep** [comment]
> If you have 4GB RAM divide it into 4.
> Use this:
> 
> -Xms1000M -Xmx1000M
> 
> And set your memory allocation exactly 1000.
> 
> Play 1.12.2 and below your FPS will run 50+.

My ONLY Problem Is 1.16 It's so HECKIN Unplayable
