### ISSUE TITLE
[BUG] Can't install Labymod3

### ISSUE THREAD

**Issue by AzarinMC** [PojavLauncherTeam/PojavLauncher#1191]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Exit With Code 1

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
![Screenshot_20210409-175010](https://user-images.githubusercontent.com/80149777/114170243-d4bb0780-995c-11eb-948b-a218854ed3ab.png)
![Screenshot_20210409-175000](https://user-images.githubusercontent.com/80149777/114170249-d84e8e80-995c-11eb-86d7-74f3a756f460.png)

**Platform:**
 - Device Model XIAOMI A1
 - CPU architecture aarch64
 - Android Version 9
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by CriticalRange** [comment]
Have you tried putting the installation file into sdcard/games/PojavLauncher ? It fixes this problem on me

**Comment by AzarinMC** [comment]
> Have you tried putting the installation file into sdcard/games/PojavLauncher ? It fixes this problem on me

Ok got it wait

**Comment by AzarinMC** [comment]
> Have you tried putting the installation file into sdcard/games/PojavLauncher ? It fixes this problem on me

Sorry it didnt work


This log

No mod detected. Starting JVM
I/jrelog  (27451): [11:13:46 INFO] Resolved addon ItemPhysics 1 by CreativeMD
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon OptiFine 1.16.5 HD U G7 1 by sp614x
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Custom Main Menu 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon DamageIndicator 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Resourcepacks24 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon ToggleSneak 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Laby's Minimap 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Settings Profile Mod 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Laby's Keystrokes 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon VoiceChat 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Resourcepacks24 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Custom Main Menu 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Laby's Keystrokes 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Laby's Minimap 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon VoiceChat 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon MotionBlur 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon CustomCrosshair 1 by Sparkless101
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon MoreParticles 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon DamageIndicator 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon WorldEditCUI 1 by lahwran
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon ToggleSneak 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon DirectionHUD 1 by bspkrs
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Settings Profile Mod 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon ItemPhysics 1 by CreativeMD
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon OptiFine 1.8.9 HD U L5 1 by sp614x
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Resourcepacks24 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Custom Main Menu 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Laby's Keystrokes 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Laby's Minimap 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon VoiceChat 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon MotionBlur 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon MoreParticles 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon DamageIndicator 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon WorldEditCUI 1 by lahwran
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon ToggleSneak 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon Settings Profile Mod 1 by LabyMod
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon ItemPhysics 1 by CreativeMD
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon DirectionHUD 1 by bspkrs
I/jrelog  (27451): 
I/jrelog  (27451): [11:13:46 INFO] Resolved addon OptiFine 1.12.2 HD U F5 1 by sp614x
I/jrelog  (27451): 
I/jrelog  (27451): Exception in thread "main" 
I/jrelog  (27451): java.lang.ExceptionInInitializerError
I/jrelog  (27451): 
I/jrelog  (27451): 	at net.labymod.installer.LabyModInstaller.<init>(LabyModInstaller.java:64)
I/jrelog  (27451): 
I/jrelog  (27451): 	at net.labymod.installer.LabyModInstaller.main(LabyModInstaller.java:41)
I/jrelog  (27451): 
I/jrelog  (27451): Caused by: java.awt.HeadlessException: 
I/jrelog  (27451): No X11 DISPLAY variable was set, but this program performed an operation which requires it.
I/jrelog  (27451): 
I/jrelog  (27451): 	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
I/jrelog  (27451): 
I/jrelog  (27451): 	at java.awt.Window.<init>(Window.java:536)
I/jrelog  (27451): 
I/jrelog  (27451): 	at java.awt.Frame.<init>(Frame.java:420)
I/jrelog  (27451): 
I/jrelog  (27451): 	at java.awt.Frame.<init>(Frame.java:385)
I/jrelog  (27451): 
I/jrelog  (27451): 	at javax.swing.JFrame.<init>(JFrame.java:189)
I/jrelog  (27451): 
I/jrelog  (27451): 	at net.labymod.installer.gui.GuiFrame.<clinit>(GuiFrame.java:17)
I/jrelog  (27451): 
I/jrelog  (27451): 	... 2 more
I/jrelog  (27451): 
Java Exit code: 1
Pemasangan berhasil
I/jrelog  (27451): Going to free args
I/jrelog  (27451): Free done
--------- beginning of system

**Comment by artdeell** [comment]
Outdated launcher version

**Comment by AzarinMC** [comment]
> Outdated launcher version

Hmmmmm ok thank maybe this help me

**Comment by AzarinMC** [comment]
> Outdated launcher version

ITS still Can't

**Comment by AzarinMC** [comment]
Can anyone help me??
![Screenshot_20210414-103839](https://user-images.githubusercontent.com/80149777/114651215-bf076280-9d0d-11eb-9066-8dfb188a9a8e.png)

**Comment by AzarinMC** [comment]
@artdeell

**Comment by khanhduytran0** [comment]
@AzarinMC update to latest play store build

**Comment by AzarinMC** [comment]
> @AzarinMC update to latest play store build 

Thanks 🙏 You Help me so much
