### ISSUE TITLE
[F-REQ] can you guys add the april fools builds

### ISSUE THREAD

**Issue by hardcaz** [PojavLauncherTeam/PojavLauncher#1193]
just wondering

**Comment by CriticalRange** [comment]
Which april fools builds ?

**Comment by OwzygZawg** [comment]
NOT IS NECESSARY! TODAY IS 9 APRIL NOT 1 APRIL FOOLS DAY 1.

**Comment by khanhduytran0** [comment]
Too late.

**Comment by hardcaz** [comment]
> Which april fools builds ?

all of them including the different version of 2.0

**Comment by CriticalRange** [comment]
Most of them are available, join to discord, go to #announcements, scroll up you'll see some, if you can't find, go to #general-en, go to pins, and scroll down, there are other versions there

**Comment by khanhduytran0** [comment]
You need enable snapshot version in launcher settings :eyes:

**Comment by Harsh-bot-beep** [comment]
> You need enable snapshot version in launcher settings 👀

I love duy's :eyes: meme ngl
