### ISSUE TITLE
Not rendering some parts and whole chunks in 1.15

### ISSUE THREAD

**Issue by DCSanyain** [PojavLauncherTeam/PojavLauncher#1194]
When playing 1.15 some parts of chunks and even whole chunks aren't shown. My device is a Galaxy Tab A (2019),2GB of RAM, aarch32. When checking the logs I found no logs.

**Comment by WesleyVanNeck** [comment]
weell there are logs in /sdcard/pojavlauncher/

**Comment by WesleyVanNeck** [comment]
fille template also

**Comment by WesleyVanNeck** [comment]
clsoing this for now
