### ISSUE TITLE
[F-REQ] and zink opengl 4.6 test shaders for devices 32 bits soon?

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1197]
I can't wait for zink Opengl 4.6 to be 32-bit ready! I really want to test the shaders

**Comment by OwzygZawg** [comment]
And please don't be rude to me!

**Comment by WesleyVanNeck** [comment]
Never gone happen 32 bit is to slow

**Comment by WesleyVanNeck** [comment]
Even on modern device it has 1 fps

**Comment by WesleyVanNeck** [comment]
> And please don't be rude to me!

Am rude to you because your spamming issue tracker with dum questions a might remove 32 bit support because 64 bit is much better

**Comment by OwzygZawg** [comment]
No problem

**Comment by OwzygZawg** [comment]
> > And please don't be rude to me!
> 
> Am rude to you because your spamming issue tracker with dum questions a might remove 32 bit support because 64 bit is much better

I promise that this will not be repeated!
