### ISSUE TITLE
[BUG] [Solved] BOOT/BLACKSCREEN LOAD TAKES FOREVER WITH FABRIC - megane-3.1.5+1.16.5.jar

### ISSUE THREAD

**Issue by Pochi336** [PojavLauncherTeam/PojavLauncher#1198]
### Describe the bug
The game wont boot or Stuck on the blacksceen when having themegane-3.1.5+1.16.5.jar on mods directory. 

Heres the Log .[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6291994/latest.log)
Log Directory (.minecraft/logs)

I cant provide any crashlog ,i dont see it crash with the mod yet.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Pasting the mod on the mods folder
2. Start Pojav Launcher
3. Launch Fabric Client 1.16.5
4. Bug occurrs it wont boot anymore.

### Expected behavior:
I expected to see the mojang loading screen but no.

### Screenshots or videos:
*I Will follow up videos or images.*

**Platform:**
 - Device Model [Vivo v11i 4/128]
 - CPU architecture [aarch64] 
 - Android Version [10]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210206 ](3.3.1.1 GPlay Version)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Any other fabric mods loads normally but when i join the megane-3.1.5+1.16.5 mod. On the directory its breaking the game. I tried adding it Alone on the mods folder still dont work.
</pre>
</details>

**Comment by nabiloi** [comment]
You need the "wthit" mod to run it

**Comment by Pochi336** [comment]
> You need the "wthit" mod to run it

Ty bro

**Comment by Pochi336** [comment]
![Screenshot_20210412_083730_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/67196343/114327146-6ea3cf80-9b6a-11eb-9295-a88f5727dbf6.jpg)

Thanks !! It was my fault afterall haha
