### ISSUE TITLE
[BUG] Mouse Speed resets on every launch

### ISSUE THREAD

**Issue by Lilith-Crimeow** [PojavLauncherTeam/PojavLauncher#1199]
### Mouse Speed slider resets to 100% every launch

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Change the Mouse Speed slider to any amount
3. Launch the game
4. Close the launcher
5. It should be reset to 100%

### Expected behavior:
I expected it to stay at my chosen value (150%)

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model : Samsung Galaxy Tab s5e
 - CPU architecture : aarch64 
 - Android Version : 10
 - PojavLauncher Version : Latest Pre-OSMesa Dev Build

(Note: I see no reason for the latestlog.txt file, so i won't add it)

**Comment by khanhduytran0** [comment]
Does it happen after restart launcher (without play)?

**Comment by Lilith-Crimeow** [comment]
Yes

**Comment by Harsh-bot-beep** [comment]
Hallo Guys

**Comment by Harsh-bot-beep** [comment]
> Yes

Yes

**Comment by Harsh-bot-beep** [comment]
Yes IT also Happens on my phoen
@khanhduytran0

**Comment by Harsh-bot-beep** [comment]
Vortex/sprirtfarer/discord man what can we do wait for Devs to fix it 

¯\_(ツ)_/¯

**Comment by Lilith-Crimeow** [comment]
Yep, just wait ig

**Comment by Mathias-Boulay** [comment]
The bug is indeed still present on recent builds, I'll look into this.

**Comment by Mathias-Boulay** [comment]
The issue has been fixed via a new commit.
it has yet to be pushed on release though.

**Comment by khanhduytran0** [comment]
Still no reply from @Vortex-sky, closing

**Comment by Lilith-Crimeow** [comment]
Just checked my emails, saw this. So far,  it seems to be fixed, as it didn't reset on this build:
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/986083769

**Comment by Mathias-Boulay** [comment]
Yeah I fixed it after all 👀
