### ISSUE TITLE
Unable to close chat on the latest version (preview6)

### ISSUE THREAD

**Issue by emelin2004** [PojavLauncherTeam/PojavLauncher#12]
After opening chat with the "chat" button I'm unable to close or even send the message. Enter key does not work neither does the back key.

**Comment by khanhduytran0** [comment]
Also back button on while not playing is ignored, FIXED in pre7?
A more problem do you have:
- Can't pick block/item from inventory (chest, dispenser,...?)

**Comment by emelin2004** [comment]
> Also back button on while not playing is ignored, FIXED in pre7?
> A more problem do you have:
> - Can't pick block/item from inventory (chest, dispenser,...?)

I disabled touchscreen mode in controls of Minecraft and thus it made item picking from inventory possible.

**Comment by emelin2004** [comment]
> > Also back button on while not playing is ignored, FIXED in pre7?
> > A more problem do you have:
> > - Can't pick block/item from inventory (chest, dispenser,...?)
> 
> I disabled touchscreen mode in controls of Minecraft and thus it made item picking from inventory possible. 

I should mention that I'm playing on 1.9

**Comment by khanhduytran0** [comment]
Also fixed `Trouble writing output`. Wait a bit...

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.6.1

**Comment by emelin2004** [comment]
> https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.6.1

Man You Are Fast. I will test it rn and tell you the results.

**Comment by khanhduytran0** [comment]
Double key might not be fixed since I am not using Android-x86 or PC at the moment.

**Comment by emelin2004** [comment]
> Double key might not be fixed since I am not using Android-x86 or PC at the moment.

Minecraft 1.7.10 now works yaaay,and chat also works now! Double keys are however still present as you have said. But optifine installer gives some weird errors,although I have no need to use it i just tested it. 

![Screenshot_20200328-001326_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/49245188/77808007-0468db80-708a-11ea-9701-92d346332a33.jpg)
![Screenshot_20200328-001029_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/49245188/77808015-0c288000-708a-11ea-9cd8-d0dacbecb2a3.jpg)

**Comment by khanhduytran0** [comment]
launcher_profiles.json is not yet supported. You can create a simple launcher_profiles.json then try again.
```
{
  "profiles": {
    "(Default)": {
      "name": "(Default)",
      "lastVersionId": "Unknown"
    }
  }
}
```
Save to /storage/emulated/0/games/minecraft/launcher_profiles.json

**Comment by khanhduytran0** [comment]
Re-install optifine first then run.

**Comment by emelin2004** [comment]
> Re-install optifine first then run.

I did,i fully deleted optifine from game directory but now it gives me this
![Screenshot_20200328-003452_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/49245188/77808597-4f83ee00-708c-11ea-9743-a06873f95b3e.jpg)

Maybe you should skip optifine for now,right now to be honest game runs very well under default minecraft video settings.

**Comment by khanhduytran0** [comment]
Ok, so now this issue was resolved. Closing, thanks for reporting bug.

**Comment by khanhduytran0** [comment]
To keep remember, you can create a new issue about double key triggered.
