### ISSUE TITLE
Unable to fix rsapadding, unable to play premium servers

### ISSUE THREAD

**Issue by harshal11041** [PojavLauncherTeam/PojavLauncher#120]
Pls I just wanna play hypixel, plz tell me on how to fix RSAPadding :(

**Comment by khanhduytran0** [comment]
Try run in VMOS app.

**Comment by harshal11041** [comment]
Still in vmos app says unable to fix RSAPadding,  can't play premium servers :(

**Comment by khanhduytran0** [comment]
Are you using latest preview?

**Comment by SakiNawak** [comment]
I have the same problem too using the lastest previews I just got Logging in

**Comment by harshal11041** [comment]
Going to try latest preview in vmos app

**Comment by khanhduytran0** [comment]
Try v3, premium will work
