### ISSUE TITLE
[BUG] every minecraft version not launching after using dev build

### ISSUE THREAD

**Issue by jumperli** [PojavLauncherTeam/PojavLauncher#1200]
I am using a 6gb ram android phone and after using a dev build, i can't launch any minecraft versions anymore cuz all i need to do is to delete all the files, is there any other solutions on this?

There is no "crash-report" or "latestlog" giving us to me, and my ram is 6gb ram and i allocated 3gb only

**Comment by khanhduytran0** [comment]
See #1201
