### ISSUE TITLE
[BUG] Not Launching After Using Dev Version

### ISSUE THREAD

**Issue by jumperli** [PojavLauncherTeam/PojavLauncher#1201]
I am using a 6gb ram android phone and after using a dev build, i can't launch any minecraft versions anymore cuz all i need to do is to delete all the files, is there any other solutions on this?

There is no "crash-report" or "latestlog" giving us to me, and my ram is 6gb ram and i allocated 3gb only

**Comment by khanhduytran0** [comment]
@jumperli what about filling the template? :eyes: we simply didn't know which Dev build you are on

**Comment by khanhduytran0** [comment]
Also duplicated your own issue

**Comment by khanhduytran0** [comment]
#1200
