### ISSUE TITLE
[F-REQ] In the settings, add the ability to remove screen clicks instead of Right mouse button so that there are no accidental clicks 

### ISSUE THREAD

**Issue by Mehoxar** [PojavLauncherTeam/PojavLauncher#1202]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zeyrox1090** [comment]
already added bruh

**Comment by ENDERMANYK** [comment]
There isn't a setting called **Disable gesture** does the thing?🤔

**Comment by EXPress-016** [comment]
> There isn't a setting called **Disable gesture** does the thing?🤔

But it will disable all gesture
