### ISSUE TITLE
I am unable to login to pojavlauncher no matter WHAT it always gives me a error

### ISSUE THREAD

**Issue by NightmareYT46** [PojavLauncherTeam/PojavLauncher#1204]
Respone error
code: 403
message {"error":"ForbiddenOperationExcetion"
"errorMessage":"Forbidden"}
### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Enter my email and password
3. Error

### Expected behavior:
I expected it to log me in normally

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model Samsung Galaxy A20
 - CPU architecture [e.g. aarch64] 
 - Android Version 10
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
Buy minecraft
