### ISSUE TITLE
[BUG] no sound on old versions (alpha, rd and 1.0 and 1.1

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1205]
There's no sound 

Start pojavlaucher

Play apha version or 1.0 and 1.1

No sounds when playing.

And how to use commands in older versions I can't open chat.

**Comment by ebuild-1** [comment]
No sound when clicking, walking, no sound for everything.
This is alpha 1.1.0
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6295249/latestlog.txt)

Proof this is really alpha 1.1.0
![Screenshot_2021-04-12-16-57-31-74_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/80798103/114369024-8ef67d00-9bb0-11eb-8307-1588e0f1365b.jpg)

**Comment by gamerbg33** [comment]
its on so mini screen

**Comment by ebuild-1** [comment]
> its on so mini screen

Press F11

**Comment by SprainedSpark89** [comment]
i am wondering how did you launch rd i can't it will just crash

**Comment by GoneSubject** [comment]
did you skip while downloading the version?

**Comment by GoneSubject** [comment]
ok first that alpha 1.1 is not working the sound because it is an alpha or something, can you play the release version because the sounds it works for me in the release version and the rd there's like no button to place or break so I don't know is there sounds

**Comment by SprainedSpark89** [comment]
it is not a bug they used to have a check to check if the sounds and textures are correct through minecraft.net but in a update made it so it used a indirect route.

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
