### ISSUE TITLE
[BUG] <Short description>Rendering mode zink snapdragon mobile phone does not support, click play after a period of time simply can not enter the game will flash back

### ISSUE THREAD

**Issue by jjj273** [PojavLauncherTeam/PojavLauncher#1208]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by jjj273** [comment]
Officials hope you can solve the problem of adapting to the snapdragon mobile phone.

**Comment by CriticalRange** [comment]
Fill da template, no one can read the title easily, also zink will be unstable for some time so use gl4es1.1.5 for 1.16

**Comment by jjj273** [comment]
Zink is stable. Zink does not apply to snapdragon cell phone

**Comment by WesleyVanNeck** [comment]
> Zink is stable. Zink does not apply to snapdragon cell phone

Zink is not stable i got a snapdragon cpu and it works fine  also fill the template
