### ISSUE TITLE
Right click (placeing blocks) not working.

### ISSUE THREAD

**Issue by golimonkey** [PojavLauncherTeam/PojavLauncher#1211]
Device: Pocophone F1
SDM 845
MIUI 11.0.6
Android 10

Pojav 3.1.1 with java integrated

Right mouse button doesn't work at all. Usb keyboard works, and all other functions work great.
Btw mouse is bluetooth. Performance is amazing 8x rendering, fancy.

Ty

**Comment by khanhduytran0** [comment]
Did you enable “Treat back button as right click”?

**Comment by jumperli** [comment]
Enable the treat back button

**Comment by golimonkey** [comment]
I didnt know that was a thing. Where can i find the setting? I cant see it in launcher settings. Funny thing is that it works by default on my Samsung Tab S6 Lite, and it also performs very good. You guys are wizards.

**Comment by Harsh-bot-beep** [comment]
Does it work now?

**Comment by khanhduytran0** [comment]
> I didnt know that was a thing. Where can i find the setting? I cant see it in launcher settings. Funny thing is that it works by default on my Samsung Tab S6 Lite, and it also performs very good. You guys are wizards. 

Maybe update to latest play store build :eyes:
