### ISSUE TITLE
[BUG] Game stuck at Mojang splash [Modded 1.8.9]

### ISSUE THREAD

**Issue by GoldenFurredFox** [PojavLauncherTeam/PojavLauncher#1212]
### Describe the bug
My game starts to load but stops or severely slows down when the Mojang logo appears.

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6298906/latest.log)
.minecraft/latestlog.txt doesn't exist so I'm providing .minecraft/logs/latest.log

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Install Forge 11.15.1.2318 for 1.8.9
3. Add mods specific for Hypixel Skyblock (SBA, SBP, NEU, Danker's, etc.)
4. Run the game
The game gets stuck on the Mojang splash for at least 2 hours, if not more.

### Expected behavior:
I expected the game to start properly within about 5 minutes or less.

**Platform:**
 - Device Model Moto g7 Power (RET-LA ocean)
 - CPU architecture aarch64
 - Android Version 10
 - PojavLauncher Version Latest GPlay Release

**Comment by ebuild-1** [comment]
No u need to provide latestlog.txt not latest.log! Those aren't the same! 
It's on games/pojavlaucher/

**Comment by WesleyVanNeck** [comment]
We need the latestlog.txt or we can't do notting

**Comment by stacode123** [comment]
its becouse you got a lot off mods try reducing the amount of mods you have

**Comment by stacode123** [comment]
and the phone your using isint the newest
(ignore spelling)

**Comment by GoldenFurredFox** [comment]
> We need the latestlog.txt or we can't do notting

My pojavlauncher didn't even generate the file!

**Comment by khanhduytran0** [comment]
@DekuHecku Bruh look at `PojavLauncher/latestlog.txt` not `PojavLauncher/.minecraft/latestlog.txt`
> Also if it’s “your pojavlauncher”, fix it yourself :\)
