### ISSUE TITLE
[BUG] Inv not opens

### ISSUE THREAD

**Issue by hamid0740** [PojavLauncherTeam/PojavLauncher#1220]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
When I press the default "INV" button, or press E in the keyboard, or send the custom key "E" or even create a new button for Inventory, it never opens and is really annoying.

**Platform:**
 - Device Model: Samsung Galaxy A51
 - CPU architecture: aarch64
 - Android Version: 11
 - PojavLauncher Version: latest release

**Comment by Google61** [comment]
Check your keyboard setup in-game...
![Screenshot_20210414-132054~2](https://user-images.githubusercontent.com/25458773/114695467-54155600-9d24-11eb-8a4c-49ffa7bcb9d7.png)
