### ISSUE TITLE
[F-REQ] Changing the game directory.

### ISSUE THREAD

**Issue by imishine** [PojavLauncherTeam/PojavLauncher#1223]
Hello. I use Pojav Launcher for both Fabric and Forge, thus I have multiple "profiles" of mods. That means everytime when I want to use a different "profile" I have to move the mod files to another folder and replace them with those which I want to use.

**I think it would be very useful to be able to create multiple profiles of the same version and changing the game directory for each one.**

Also a separate JVM arguments for each profile would be nice too.

A example from Minecraft Launcher how it could look like.
![Screenshot_32](https://user-images.githubusercontent.com/82535619/114757053-ae7dd900-9d5b-11eb-92ca-e90677659f12.png)

**Comment by CriticalRange** [comment]
You can try profiles build, it's old because it's not continued due to serious lag issues
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/562993220

**Comment by khanhduytran0** [comment]
But you can also hold to a version, “Per-version config” dialog will appear so you can customize both.

**Comment by imishine** [comment]
> “Per-version config” dialog will appear so you can customize both.

I'm little confused. When does that pre-version dialog appear?

**Comment by CriticalRange** [comment]
> > “Per-version config” dialog will appear so you can customize both.
> 
> I'm little confused. When does that pre-version dialog appear?

If you hold a version (in versions spinner) you will get a menu like "Per-version config"

**Comment by imishine** [comment]
Oh, thank you so much! That did the trick.
