### ISSUE TITLE
[BUG] will not launch

### ISSUE THREAD

**Issue by ProtatoPlus** [PojavLauncherTeam/PojavLauncher#1226]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Pojav launches minecraft controls show up then go back to launcher

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
Launch any version
### Expected behavior:
I expected ...
it to launch

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Samsung galaxy s5
 - arm64
 - android marshmallow 6.0
 - latest release
[pojavlog.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/6319034/pojavlog.zip)
Options and logs are in the .zip file
<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by AutumnVN** [comment]
u allocated too many ram

**Comment by ProtatoPlus** [comment]
> u allocated too many ram

how much should be allocated? i have 2gb of ram.

**Comment by ProtatoPlus** [comment]
Nevermind i tinkered a bit with it and managed to get it stable at 256 mb max and 10mb min
