### ISSUE TITLE
[BUG] <Shader Capped At 30fps>

### ISSUE THREAD

**Issue by Harsh-bot-beep** [PojavLauncherTeam/PojavLauncher#1228]
### Describe the bug
If You Think You Cannot Yet 60fps in latest version because its laggy but I Tryed 1.12.2 and it's stucks at 30fps no matter what happens.also drops but does not  go to 40fps

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2.Launch a Stable Smooth Version(in which you get 60fps)
3.apply "es" shader
4.It Will Be Stuck At 30fps

### Expected behavior:
I expected To Have Not 30fps cap

### Screenshots or videos:
(*Insert 30fps picture here*)

**Platform:**
 - Device Model- Redmi 9. power
 - CPU-64×
 - Android Version- 10
 - PojavLauncher Version- latest play store

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6323596/latestlog.txt)

**Comment by Harsh-bot-beep** [comment]
Question- Why GitHub Attached A MineCraft Cat To My Pfp Lol

**Comment by WesleyVanNeck** [comment]
Get a better device

**Comment by Harsh-bot-beep** [comment]
Bruh LIKE WTF WHY ITS STUCK AT 30FPS THOUGH LIKE IT CANNOT GO ABOVE LIKE SOMEONE CAPPED MY FPS AT 30

**Comment by WesleyVanNeck** [comment]
> Bruh LIKE WTF WHY ITS STUCK AT 30FPS THOUGH LIKE IT CANNOT GO ABOVE LIKE SOMEONE CAPPED MY FPS AT 30

Not our doing
