### ISSUE TITLE
help i can not download versions. I re-downloaded and installed. But it still doesn't work. Internet is on for me

### ISSUE THREAD

**Issue by Tol561** [PojavLauncherTeam/PojavLauncher#1229]

**Comment by Tol561** [comment]
![Screenshot_2021-05-02-13-19-29-481_net kdt pojavlaunch](https://user-images.githubusercontent.com/73465141/115003389-8e6b2880-9ec7-11eb-9bd5-6aa18f8c3c82.jpg)

**Comment by WesleyVanNeck** [comment]
Use the template I will close for now
