### ISSUE TITLE
[BUG] <Middle Mouse Doesn't Scroll The Menu Up or Down>

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#1230]
This Thing Is Really Annoying Me, Middle Mouse Can Scroll In The Hotbar But Doesn't Scroll Anything Else

PojavLauncher Version: Latest Crowdin Update (l10n_v3_openjdk2) 

My Device Info:
Huawei Nova 3i
4Gb Ram
Rom 128 Gb

**Comment by EnderBrine99FOX** [comment]
@khanhduytran0

**Comment by khanhduytran0** [comment]
@EnderBrine99FOX Bruh Latest crowdin update is __Latest Translation update__

**Comment by khanhduytran0** [comment]
And so if you aren’t going to test new translation then don’t touch it
