### ISSUE TITLE
[BUG] Game crashing (osmesa-dev-tests)

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#1232]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
The game is crashing with both OpenGL ES 3 and Zink.

**Add a log file if you want to see your bug fixed !**

Minecraft 1.16.5 with OpenGL ES 3 :  [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6327394/latestlog.txt)

Minecraft 1.16.5 with Zink:  [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6327398/latestlog.txt)

### To Reproduce:
     Start PojavLauncher
1- Minecraft 1.16.5 with OpenGL ES 3 (Shows the Mojang studios screen, and crash)
2- Minecraft 1.16.5 with Zink (Nothing shows, just crash after some seconds)

**Platform:**
 - Device Model: Motorola Moto G6 play
 - CPU architecture: aarch32 
 - Android Version: 9
 - PojavLauncher Version: Latest Release (osmesa-dev-tests) || version 3.3.1.1_rel_20210416

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
This happens with 1.12.2 too.
</pre>
</details>

**Comment by OwzygZawg** [comment]
--------- beggining with launcher debug
Info: Launcher version: 3.3.1.1_rel_20210416
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Dorg.lwjgl.opengl.libname=libgl4es_115.so -Xms512m -Xmx800m -Dorg.lwjgl.opengl.libname=libOSMesa_8.so"
--------- beginning of crash
--------- beginning of main
Headless version detected! (20210416)
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so
" has unsupported flags DT_FLAGS_1=0x81

I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so" has unsupported flags DT_FLAGS_1=
0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so
" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so" has unsupported flags DT_FLAGS_1=
0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  (12045): dlopen /data/app/net.kdt.pojavlaunch-tGuWXPMZLqY8BGAoYrkUMA==/lib/arm/libopenal.so success
I/jrelog  (12045): dlopen libOSMesa_8.so success
I/jrelog  (12045): Done processing args
I/jrelog  (12045): Found JLI lib
I/jrelog  (12045): Calling JLI_Launch
OpenJDK Client VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
[19:47:27] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[19:47:27] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[19:47:27] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions

OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer

OptiFine ZIP file: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/optifine/OptiFine/1.16.5_HD_U_G8_pre12/OptiFine-1.16.5_HD_U_G8_pre12.jar

OptiFineTweaker: getLaunchArguments

OptiFineTweaker: getLaunchTarget

[19:47:29] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:47:32] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[19:47:33] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[19:47:33] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[19:47:33] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[19:47:33] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[19:47:38] [main/INFO]: [OptiFine] (Reflector) Method not present: aeg.createOptional

**Comment by OwzygZawg** [comment]
Same

**Comment by OwzygZawg** [comment]
> --------- beggining with launcher debug
> Info: Launcher version: 3.3.1.1_rel_20210416
> Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
> Architecture: arm/aarch32
> Info: Custom Java arguments: "-Dorg.lwjgl.opengl.libname=libgl4es_115.so -Xms512m -Xmx800m -Dorg.lwjgl.opengl.libname=libOSMesa_8.so"
> --------- beginning of crash
> --------- beginning of main
> Headless version detected! (20210416)
> WARNING: linker:
> "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so
> " has unsupported flags DT_FLAGS_1=0x81
> 
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
> " has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
> WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
> WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
> WARNING: linker:
> "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
> WARNING: linker:
> "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so" has unsupported flags DT_FLAGS_1=
> 0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
> WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so
> " has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success
> WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so" has unsupported flags DT_FLAGS_1=0x81
> WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
> WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so" has unsupported flags DT_FLAGS_1=
> 0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success
> WARNING: linker:
> "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success
> WARNING: linker: "
> /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so" has unsupported flags DT_FLAGS_1=0x81
> I/jrelog (12045): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
> I/jrelog (12045): dlopen /data/app/net.kdt.pojavlaunch-tGuWXPMZLqY8BGAoYrkUMA==/lib/arm/libopenal.so success
> I/jrelog (12045): dlopen libOSMesa_8.so success
> I/jrelog (12045): Done processing args
> I/jrelog (12045): Found JLI lib
> I/jrelog (12045): Calling JLI_Launch
> OpenJDK Client VM warning:
> No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
> [19:47:27] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
> [19:47:27] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
> [19:47:27] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
> OptiFineTweaker: acceptOptions
> 
> OptiFineTweaker: injectIntoClassLoader
> OptiFine ClassTransformer
> 
> OptiFine ZIP file: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/optifine/OptiFine/1.16.5_HD_U_G8_pre12/OptiFine-1.16.5_HD_U_G8_pre12.jar
> 
> OptiFineTweaker: getLaunchArguments
> 
> OptiFineTweaker: getLaunchTarget
> 
> [19:47:29] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
> [19:47:32] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
> [19:47:33] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
> [19:47:33] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
> [19:47:33] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
> [19:47:33] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
> [19:47:38] [main/INFO]: [OptiFine] (Reflector) Method not present: aeg.createOptional

This is my Lastelog

**Comment by OwzygZawg** [comment]
My Platform:

. Samsung J5 Prime
. Android 9
. CPU Architecture: Aarch 32
. Laste Build Version: Osmesas devs tests

**Comment by OwzygZawg** [comment]
@khanhduytran0 help!!

**Comment by GabudPeople** [comment]
How to use zink in pojav 🤔

**Comment by AutumnVN** [comment]
that is why dev didn't release osmesa build and called it "osmesa-dev-tests" lol

**Comment by OwzygZawg** [comment]
@khanhduytran0 !!! Help

**Comment by khanhduytran0** [comment]
> @khanhduytran0 !!! Help

Stop. My Gmail inbox is almost 3k now

**Comment by khanhduytran0** [comment]
@Mateus13000 you’ve missed `-Dorg.lwjgl.opengl.libname=libOSMesa_8.so`

**Comment by khanhduytran0** [comment]
@OwzygZawg And so why u duplicated argument?
> Info: Custom Java arguments: "-Dorg.lwjgl.opengl.libname=libgl4es_115.so -Xms512m -Xmx800m -Dorg.lwjgl.opengl.libname=libOSMesa_8.so"

**Comment by OwzygZawg** [comment]
> @OwzygZawg E então por que você duplicou o argumento?
> 
> > Informações: Argumentos Java personalizados: "-Dorg.lwjgl.opengl.libname = libgl4es_115.so -Xms512m -Xmx800m -Dorg.lwjgl.opengl.libname = libOSMesa_8.so"

Oh sorry

**Comment by OwzygZawg** [comment]
> @ Mateus13000 você perdeu`-Dorg.lwjgl.opengl.libname=libOSMesa_8.so`

Work only with gl4es 1.1.4?

**Comment by OwzygZawg** [comment]
the crash affects Aarch 32 too!

**Comment by OwzygZawg** [comment]
> the crash affects Aarch 32 too!

And Aarch 64

**Comment by OwzygZawg** [comment]
> How to use zink in pojav 🤔

Bruh

1 actions
2 search= osmesas devs tests
3 install the App Debug
4 Extract the file App Debug to name
5 Click Install
6 Open The App
7 settings<rendering< and select Zink GL 4.6

**Comment by jumperli** [comment]
Why -Dorg.lwjgl.opengl.libname=libOSMesa_8.so

libOSMesa like from ios you know, is there any from lile libAndroidMesa lol im just kidding srry

**Comment by WesleyVanNeck** [comment]
Duh this is why it's a test

**Comment by MateusL13** [comment]
> @Mateus13000 you’ve missed `-Dorg.lwjgl.opengl.libname=libOSMesa_8.so`

Thank you!!! Now the game opens with Zink!!!!

**Comment by GlazyCode** [comment]
My zink pojav version works  but
My shader don't have shadow it only have realistic water and lighting how to fix it
