### ISSUE TITLE
[BUG] Sodium always crashes

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1234]
<it crashes when joining a server/opening a world> <keeps crashing Everytime>

### Describe the bug
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6328488/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2.join server or open a world
3.crash

### Expected behavior:
I expected it to not crash...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [Oppo a12 4/64]
 - CPU architecture [aarch64] 
 - Android Version [9]
 - PojavLauncher Version [Version 3.3.1.1_rel_20210405 ]

**Comment by AutumnVN** [comment]
disable 
compact vertex format 
fog occlusion

**Comment by EnderBrine99FOX** [comment]
Me 2 When I Tried To Join My World it Says
Joining World
Saving World
And Crash The Game!

**Comment by khanhduytran0** [comment]
@EnderBrine99FOX and you **haven’t** said you’ve disabled both options.

**Comment by ebuild-1** [comment]
> disable
> compact vertex format
> fog occlusion

How???!!?!?!?!!!! @AutumnVN

**Comment by AutumnVN** [comment]
video settings > advanced

**Comment by EnderBrine99FOX** [comment]
> @EnderBrine99FOX and you **haven’t** said you’ve disabled both options.
@khanhduytran0 
I Already Disabled Both Options And Its Still Not Working


https://user-images.githubusercontent.com/79517194/115142348-fa759a00-a049-11eb-8932-4b39f9346214.mp4

**Comment by ebuild-1** [comment]
That means ur phone not compatible, my 120$ phone runs sodium fine at a
stable 35 fps.

**Comment by ebuild-1** [comment]
![2021-04-18_11 03 07](https://user-images.githubusercontent.com/80798103/115143716-8653ea00-a07b-11eb-8548-c5d219d7a5d5.png)

**Comment by SamSam759** [comment]
![2021-04-18_11 03 07](https://user-images.githubusercontent.com/80798103/115143716-8653ea00-a07b-11eb-8548-c5d219d7a5d5.png)

**Comment by ebuild-1** [comment]
> > @EnderBrine99FOX and you **haven’t** said you’ve disabled both options.
> > @khanhduytran0
> > I Already Disabled Both Options And Its Still Not Working
> 
>  Untitled.59_720p.mp4

BRUH, Don't change opengl it's gonna crash your game lmao

**Comment by EnderBrine99FOX** [comment]
> > > @EnderBrine99FOX and you **haven’t** said you’ve disabled both options.
> > > @khanhduytran0
> > > I Already Disabled Both Options And Its Still Not Working
> > 
> > 
> > Untitled.59_720p.mp4
> 
> BRUH, Don't change opengl it's gonna crash your game lmao

I Tried Without Changing Opengl And Its Still Crashing

**Comment by ebuild-1** [comment]
> > > > @EnderBrine99FOX and you **haven’t** said you’ve disabled both options.
> > > > @khanhduytran0
> > > > I Already Disabled Both Options And Its Still Not Working
> > > 
> > > 
> > > Untitled.59_720p.mp4
> > 
> > 
> > BRUH, Don't change opengl it's gonna crash your game lmao
> 
> I Tried Without Changing Opengl And Its Still Crashing

That's mod fault, or your phones not good enough to run it.

**Comment by ebuild-1** [comment]
Set opengl to 3.0 one shot, and itll work fine. If not I can't do anything about it.
