### ISSUE TITLE
[BUG] libOSMesa_8.so not work osmesa-devs-tests on arm32

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1239]
--------- beggining with launcher debug Info: Launcher version: 3.3.1.1_rel_20210416 Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version] Architecture: arm/aarch32 Info: Custom Java arguments: "-Dorg.lwjgl.opengl.libname=libgl4es_115.so -Xms512m -Xmx800m -Dorg.lwjgl.opengl.libname=libOSMesa_8.so" Headless version detected! (20210416) --------- beginning of crash WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so" has unsupported flags DT_FLAGS_1= 0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so" has unsupported flags DT_FLAGS_1=0x81 --------- beginning of main WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so " has unsupported flags DT_FLAGS_1= I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success 0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1= 0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so " has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so " has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so " has unsupported flags DT_FLAGS_1= 0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so" has unsupported flags DT_FLAGS_1= 0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so" has unsupported flags DT_FLAGS_1= 0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so " has unsupported flags DT_FLAGS_1= 0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so " has unsupported flags DT_FLAGS_1= 0x81 I/jrelog (30100): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success I/jrelog (30100): dlopen /data/app/net.kdt.pojavlaunch-jkqodoefqW66FN3p1F2tEA==/lib/arm/libopenal.so success I/jrelog (30100): dlopen libOSMesa_8.so success I/jrelog (30100): Done processing args I/jrelog (30100): Found JLI lib I/jrelog (30100): Calling JLI_Launch OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes [18:42:05] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker [18:42:05] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker [18:42:05] [main/INFO]: Calling tweak class optifine.OptiFineTweaker OptiFineTweaker: acceptOptions OptiFineTweaker: injectIntoClassLoader OptiFine ClassTransformer OptiFine ZIP file: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/optifine/OptiFine/1.13.2_HD_U_G5/OptiFine-1.13.2_HD_U_G5.jar OptiFineTweaker: getLaunchArguments OptiFineTweaker: getLaunchTarget [18:42:06] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main} [18:42:09] [main/INFO]: Setting user: Henlog [18:42:27] [main/INFO]: [OptiFine] *** Reflector Forge *** [18:42:27] [main/INFO]: [OptiFine] *** Reflector Vanilla *** [18:42:28] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext [18:42:28] [main/WARN]: Skipping bad option: lastServer: [18:42:28] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier [18:42:28] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result [18:42:28] [main/INFO]: [OptiFine] (Reflector) Method not present: blc.hasTileEntity [18:42:28] [main/INFO]: LWJGL Version: 3.2.3 SNAPSHOT [18:42:30] [main/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions: 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath. 	b) Add the JAR that contains the shared library to the classpath. [18:42:30] [main/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics. [18:42:30] [main/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics. OSMDroid: using built-in libOSMesa_8.so OSMDroid: width=1280;height=720, reserving 3686400 bytes for frame buffer OSMDroid: created frame buffer OSMDroid: generating context ../src/gallium/drivers/zink/zink_screen.c:778: VkPhysicalDevice choose_pdev(const VkInstance): assertion "pdev_count > 0" failed

**Comment by OwzygZawg** [comment]
Heey

**Comment by CriticalRange** [comment]
I have the same issue, we'll have to wait for a fix

**Comment by khanhduytran0** [comment]
Bruh duplicated 
> -Dorg.lwjgl.opengl.libname=libgl4es_115.so -Xms512m -Xmx800m -Dorg.lwjgl.opengl.libname=libOSMesa_8.so

also zink doesn’t supports several 32bit GPU

**Comment by OwzygZawg** [comment]
> Bruh duplicado
> 
> > -Dorg.lwjgl.opengl.libname = libgl4es_115.so -Xms512m -Xmx800m -Dorg.lwjgl.opengl.libname = libOSMesa_8.so
> 
> também o zink não suporta várias GPUs de 32 bits

I'know

**Comment by OwzygZawg** [comment]
> I have the same issue, we'll have to wait for a fix

Yup.

**Comment by khanhduytran0** [comment]
> > I have the same issue, we'll have to wait for a fix
> 
> 
> 
> Yup.

Fix your phone GPU :eyes:

**Comment by CriticalRange** [comment]
> > > I have the same issue, we'll have to wait for a fix
> > 
> > 
> > Yup.
> 
> Fix your phone GPU 👀

Any tips ?

**Comment by OwzygZawg** [comment]
> > > Eu tenho o mesmo problema, vamos ter que esperar por uma correção
> > 
> > 
> > Sim.
> 
> Consertar a GPU do seu telefone 👀

How?

**Comment by OwzygZawg** [comment]
> > > > Eu tenho o mesmo problema, vamos ter que esperar por uma correção
> > > 
> > > 
> > > Sim.
> > 
> > 
> > Consertar a GPU do seu telefone 👀
> 
> Alguma dica?

🙏

**Comment by khanhduytran0** [comment]
Try a Vulkan test. Some phone does not supports Vulkan even Android 8+

**Comment by OwzygZawg** [comment]
> Try a Vulkan test. Some phone does not supports Vulkan even Android 8+

Link? Or any tips? My Android is 9

**Comment by khanhduytran0** [comment]
https://play.google.com/store/apps/details?id=com.realtechvr.glview

**Comment by OwzygZawg** [comment]
> https://play.google.com/store/apps/details?id=com.realtechvr.glview

And after?

**Comment by OwzygZawg** [comment]
?

**Comment by CriticalRange** [comment]
> Try a Vulkan test. Some phone does not supports Vulkan even Android 8+

I just looked up, mine doesn't support, sadge

**Comment by OwzygZawg** [comment]
> > Try a Vulkan test. Some phone does not supports Vulkan even Android 8+
> 
> I just looked up, mine doesn't support, sadge

Sad

**Comment by EnderBrine99FOX** [comment]
> Try a Vulkan test. Some phone does not supports Vulkan even Android 8+

![Screenshot_20210418_031552_com realtechvr glview](https://user-images.githubusercontent.com/79517194/115142526-e0888700-a04a-11eb-8c9e-2be1e715f0e2.jpg)
Does My Phone Support It?

**Comment by CriticalRange** [comment]
> > Try a Vulkan test. Some phone does not supports Vulkan even Android 8+
> 
> ![Screenshot_20210418_031552_com realtechvr glview](https://user-images.githubusercontent.com/79517194/115142526-e0888700-a04a-11eb-8c9e-2be1e715f0e2.jpg)
> Does My Phone Support It?

Yours does support vulkan, otherwise it would say "unavailable".
