### ISSUE TITLE
Pojavlauncher Kills accu fast and hot Huawei P40 Pro

### ISSUE THREAD

**Issue by NightOwl2021** [PojavLauncherTeam/PojavLauncher#1240]
Pojavlauncher Kills accu fast and make the Smartphone unser a minute very hot 

And pls add Mouse wheel Up and Down Buttons 

Huawei P40 Pro pls fix this

**Platform:**
 - Device Model [ Huawei P40 Pro 8/256GB]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1]

**Comment by khanhduytran0** [comment]
@NightOwl2021 

> Pojavlauncher Kills accu fast and make the Smartphone unser a minute very hot

bruh forcing a game that was designed for PC to run on phone always do that.

> Kill accu fast

Invalid! I don’t understand.

> And pls add Mouse wheel Up and Down Buttons

Check `SPECIAL_SCROLLUP` and `SPECIAL_SCROLLDOWN`

**Comment by NightOwl2021** [comment]
The Launcher Kills the battery very fast

**Comment by rscAvePlex** [comment]
ok

**Comment by khanhduytran0** [comment]
> The Launcher Kills the battery very fast

@NightOwl2021 get a pc and measure it’s power usage when running game :trollface:
