### ISSUE TITLE
[F-REQ] where i can download osmesa-dev-build

### ISSUE THREAD

**Issue by AzarinMC** [PojavLauncherTeam/PojavLauncher#1241]
I Can't search

ITS Notting say osmesa-dev-build

**Comment by OwzygZawg** [comment]
1 actions
2 click on search
3 search> osmesa-devs-tests

**Comment by AzarinMC** [comment]
> 1 actions
> 2 click on search
> 3 search> osmesa-devs-tests

Can you send link🙏

**Comment by AzarinMC** [comment]
> 1 actions
> 2 click on search
> 3 search> osmesa-devs-tests

Oh ok ty

**Comment by OwzygZawg** [comment]
> > 1 actions
> > 2 click on search
> > 3 search> osmesa-devs-tests
> 
> Can you send link🙏

https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/754545371
