### ISSUE TITLE
[BUG] pojav Launcher discharges the battery very fast 

### ISSUE THREAD

**Issue by NightOwl2021** [PojavLauncherTeam/PojavLauncher#1242]
the pojav launcher discharges the battery very quickly by 30-45% in about 30-40 mins

![Screenshot_20210418_021342_com.trendygames.DutyDriverCityLITE_edit_27133264058879.jpg](https://user-images.githubusercontent.com/82728931/115130000-de431000-9feb-11eb-9cd9-288be5303edd.jpg)

**Platform:**
 - Device Model [Huawei P40 Pro 8/256GB]
 - CPU architecture ARMv7 VFPv3 NEON 
 - Android Version 10]l
 - PojavLauncher Version Latest Release version 3.3.1.1

**Comment by khanhduytran0** [comment]
I've already explained!
> bruh forcing a game that was designed for PC to run on phone always do that.

**Comment by khanhduytran0** [comment]
As Minecraft java which was designed for PC use unlimited power source from it (idk about laptop).

**Comment by ebuild-1** [comment]
My low end crap can run pojavlaucher in 5 hours lol

**Comment by Xtrolomentplays** [comment]
My Samsung galaxy A9pro pojav launcher drained 73percent of my battery in 1h 24min can you fix

**Comment by Ipostvids** [comment]
Yeah my battery went from 33 to 0 in less than a minute when I use pojavlauncher but when I put it on the charger it says it's 33 again so I take it off the charger then it dies in 30 seconds everytime and does it over and over again until I just gave up and waited til 100 then it doesn't do it again until my device is 30 again.

**Comment by GaucovyAero** [comment]
> Yeah my battery went from 33 to 0 in less than a minute when I use pojavlauncher but when I put it on the charger it says it's 33 again so I take it off the charger then it dies in 30 seconds everytime and does it over and over again until I just gave up and waited til 100 then it doesn't do it again until my device is 30 again.

thats an issue with your phone, not pojav lol

**Comment by supr10** [comment]
mine takes 1 percent per 10 sec when plugged in. I wish that was a joke...

**Comment by artdeell** [comment]
> mine takes 1 percent per 10 sec when plugged in. I wish that was a joke...

are you using the charger originally supplied with your phone? because my phone does the same thing when you use an old charger and play any game that's more demanding than a web browser
