### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by Harsh-bot-beep** [PojavLauncherTeam/PojavLauncher#1243]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. I'm always frustrated when I Have To Hold For Attack And What I Was Planning To Attack.
Ex- I AM Killing A Sheep But When I Hold To Attack IT Usally Goes Away Or I Keep Missing Hits.

**Describe the solution you'd like**
A clear and concise description of what I want to happen Is That Do Something Like I Can Attack Like Pe.But I Know Pc And Mobile Mechanics Work Different.I Know ITs Very Hard To Combat Especially With Cooldown Making It Worse With Waiting 100ms To Attack.

**Describe alternatives you've considered**
Any Mod That Will Make IT Easier Without Chnaging Vanilla?
Maybe A Mod+New Feature Would Be Great

I Have Tried Making Right And Left Opposite But IT Makes Tap To Attack But Need To Hold To Place AND End Up Breaking Blocks...
Try Make A Feature That Makes It Similar To Pe Combat/Clicking System?

**Comment by Harsh-bot-beep** [comment]
Ngl It Would Be Hard To MAKE This 
Or 
It Would Hard To Think A Feature To Remove This Annoying Combat
I CANNOT Also Decide

**Comment by khanhduytran0** [comment]
> A clear and concise description of what I want to happen Is That Do Something Like I Can Attack Like Pe.But I Know Pc And Mobile Mechanics Work Different.I Know ITs Very Hard To Combat Especially With Cooldown Making It Worse With Waiting 100ms To Attack

Minecraft 1.9+ has a built in combat countdown. So set left mouse duration match it and live with it. 1.8.9 and below use custom controls to place left mouse button at where you want.

**Comment by Harsh-bot-beep** [comment]
Duy I Know This But
But I/We Have To CLICK Where Button Is.Then We Have To Move Camera Angle By Moving Where Is Not A Button Also Need To Lift Your Finger While In Pe Yoy Can Continue Moving Camera...

WAIT I GOT AN IDEA MATE MAKE A BUTTON OPTION THAT IT UNABLE TO PERFORM THE KEYCODE THAT IT SUPPOSED AFTER A SPEFIC TIME!!! 
FOR EXAMPLE 
If I Attack I Usally Hold 0.25sec or less To Perform(Because Every Human is not a computer)
So If I Perform hold for 2 Sec It Should Be Disabled Until I Lift MY All Fingers From Screen 
What about that
That Would Not Be Hard To Make 
Hope You Understand What I Wanna Say :).

**Comment by Harsh-bot-beep** [comment]
Let Me Make A Video Appeal Request

**Comment by khanhduytran0** [comment]
Just Make An In-Screen Button Which Will Do The LefT Mouse
