### ISSUE TITLE
You cannot click to play on PojavLauncher

### ISSUE THREAD

**Issue by Danivelgamer90** [PojavLauncherTeam/PojavLauncher#1245]
This bug is horrible because you can't click on anything, you can see that we are still in the game but the mouse does not work

**Comment by Danivelgamer90** [comment]
![Uploading Screenshot_20210418-192451.jpg…]()

**Comment by Danivelgamer90** [comment]
![Uploading Screenshot_20210418-192459.jpg…]()

**Comment by Danivelgamer90** [comment]
![Uploading Screenshot_20210418-192513.jpg…]()

**Comment by ebuild-1** [comment]
Don't click the mouse button while the game is loading, it's not gonna work for some reason. Also  let GitHub upload your screenshot man.

**Comment by khanhduytran0** [comment]
@Danivelgamer90 You cannot fill the template, but RIP it instead.

**Comment by REYASKANNAN** [comment]
I can't click any of the single player or multiplayer even I can't click quit game the mouse is working but couldn't click even I click the home button on mobile and clear on the minimize and again went to pohavlanchur multipletimes but still I won't work

But that problem in fabric 1.16.5 but I can use normal vinnila 1.16.5 I can click on 1.16.5 also I really need the fabric
![Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…]()
