### ISSUE TITLE
Glitching in better portal mod plsss help

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1246]
Better portal mod can see through the blocks 1.12.2
![Screenshot_2021-04-19-08-55-15-179_net kdt pojavlaunch](https://user-images.githubusercontent.com/76839710/115168439-7aa10b80-a0ed-11eb-8d5a-3266ef5f26bb.jpg)

Emersive portal mod only white portal 1.16.3
![Screenshot_2021-04-19-08-38-27-192_net kdt pojavlaunch](https://user-images.githubusercontent.com/76839710/115168478-9efce800-a0ed-11eb-8cbc-42a10748f2a5.jpg)

Plsss help

**Comment by Blimyst** [comment]
Its the mod problem, not this launcher

**Comment by kedrick021** [comment]
So you can't help?

**Comment by ebuild-1** [comment]
> So you can't help?

Yes they can't help. This is probably some mod bug or your phones not compatible enough.

**Comment by kedrick021** [comment]
Ok thanks

**Comment by EnderBrine99FOX** [comment]
Increase Your Render Distance To Make The Portal Reload Properly

**Comment by kedrick021** [comment]
Did that working on you?

**Comment by EnderBrine99FOX** [comment]
Yep Its Worked But If You Phone Can't Handle it then it Will Shutdown Your Phone Cuz I Tested And My Hole Phone Restart The System

**Comment by kedrick021** [comment]
1.12.2 or 1.16.3 I already try I change the render distance to 48 but nothing change 1.12.2 my phone xiaomi 9t pro
