### ISSUE TITLE
[<How Can I Use Spigot.jar?>]

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#1248]
I Want To Install Fundy Cursed Differently And The File Use Spigot.jar And When I Tried To Install It Force Stop The Launcher And I Tried To Put it On Mods File And Its Still Not Working If There Anyway To Use This Let Me Know!

https://user-images.githubusercontent.com/79517194/115170469-6a773500-a0c9-11eb-830c-386174d0b401.mp4

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6332701/latestlog.txt)

**Comment by Zeyrox1090** [comment]
idk update?

**Comment by WesleyVanNeck** [comment]
Spigot is not supported and spigot is not mod

**Comment by khanhduytran0** [comment]
@EnderBrine99FOX bruh read what it says
![3A9B57A1-08AE-4591-9001-4A58EF73DA0B](https://user-images.githubusercontent.com/40482367/115204187-66c3cc80-a122-11eb-8d95-2893e56f229f.jpeg)
