### ISSUE TITLE
1.5.2 is broken 

### ISSUE THREAD

**Issue by Tryhardbro** [PojavLauncherTeam/PojavLauncher#125]
1.5.2 is broken
![Screenshot_20200422-163648](https://user-images.githubusercontent.com/64164767/80025766-8dbbd400-84b7-11ea-8d00-46ef76a69105.png)

**Comment by khanhduytran0** [comment]
Minecraft 1.3 to 1.5.2 will not launch.

**Comment by ghost** [comment]
> Minecraft 1.3 to 1.5.2 will not launch.

wont fix issue?
