### ISSUE TITLE
The fabric installer not working 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1251]
It says "if you have enabled significant logging, look into using the -G option to increase log buffer sizes.
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.
ERROR: Unable to get more log" like this then when I click play it crashes

**Comment by WesleyVanNeck** [comment]
fill the template
