### ISSUE TITLE
Jvm proxy argument isn't working right

### ISSUE THREAD

**Issue by meetioss** [PojavLauncherTeam/PojavLauncher#1252]
So, pojav allows to add jvm launch arguments. One of those allows setting a proxy. For old minecraft versions (especially indev and infdev) this is crucial to get the game running. This worked till seemingly recently, when both proxies i know of stopped working, rendering indev and infdev unplayable in pojavlauncher

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Go into "Jvm Launch Arguments" and add "-Dhttp.proxyHost=mineonline.codie.gg (or Betacraft.pl, but that one never worked for some reason)
3. Add a custom indev or infdev version
4. Launch it. It will freeze and the log will show a crash.

### Expected behavior:
I expected indev to load normally. Instead, it freezes

**Platform:**
 - Device Model Redmi Note 8 pro
 - CPU architecture aarch64
 - Android Version 10
 - PojavLauncher version 3.3.1.1_rel_20210418
 

Betacraft is a commonly used proxy for running old minecraft versions, but it doesn't work with pojav for some reason. Mineonline did work before but now stopped working.

**Comment by khanhduytran0** [comment]
Send latestlog.txt :eyes:

**Comment by meetioss** [comment]
https://pastebin.com/Ab1B7hMV

**Comment by Mathias-Boulay** [comment]
From #1540 
```
Start PojavLauncher
... (your set of actions to reproduce the bug)
Add the jvm arguments "-Dhttp.proxyHost=betacraft.pl
-Djava.util.Arrays.useLegacyMergeSort=true"
Go in minecraft beta 1.7 or 1.8 and place a door
Open it. It will not have a sound, sign of the proxy not working correctly
```

**Comment by SprainedSpark89** [comment]
i have the same issue

**Comment by Mathias-Boulay** [comment]
As of current dev builds, it has been proven to work
