### ISSUE TITLE
[BUG] Gl4es 1.1.5 bug in 1.14- 

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1255]
1 play 1.14 or 1.13
2 kill mob in gl4es 1.1.5
3 broken textures

**Comment by OwzygZawg** [comment]
There must be some way that 1.14- doesn't break textures when using gl4es 1.1.5 and it is annoying to change from gl4es 1.1.5 to 1.1.4 just because a texture broke when hitting a mob and I play on the PC this doesn't happen in Java on my PC then there must be some way to fix it, nothing is impossible but possible!

**Comment by OwzygZawg** [comment]
> There must be some way that 1.14- doesn't break textures when using gl4es 1.1.5 and it is annoying to change from gl4es 1.1.5 to 1.1.4 just because a texture broke when hitting a mob and I play on the PC this doesn't happen in Java on my PC then there must be some way to fix it, nothing is impossible but possible!

And I know that it still may not be possible

**Comment by EnderBrine99FOX** [comment]
There Is A Way To Fix This Just Plz Don't Spam Issues Like This (Talk To Me in Discord To Show You How To Fix This)

**Comment by khanhduytran0** [comment]
@OwzygZawg bruh we aren't graphics developer. Wait for @ptitSeb

**Comment by khanhduytran0** [comment]
Already listed in known issue, read it?
