### ISSUE TITLE
[BUG] Labymod installer doesn't work

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1256]
### Describe the bug
So when I download the lastest Pojav version from github (3.3.1.1) and then download the lastest labymod installer, and then execute it on Pojav's app, it will say "No mod detected. Starting JVM". When I tried it but using the app store's version (not sure what Pojav version it is but it is the one uploaded by "artdeell") I'm able to execute the labymod installer, and after I install it, and select to play with the Labymod version, when the Mojang loading screen completes, it crashes, giving this crash report: https://mcpaste.io/7c74e4ae606150d2

**[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6339703/latestlog.txt)** (PojavLauncher 3.3.1.1)
**[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6339844/latestlog.4.txt)** (PojavLauncher App Store "artdeell")

### To Reproduce:

1. Download PojavLauncher 3.3.1.1
2. Download Labymod from https://www.labymod.net/en/download
3. Start PojavLauncher
4. Go to "Options"/"Launch a mod installer (Forge, Labymod, Fabric, etc...)" and select the downloaded Labymod's installer.
5. You will get "No mod detected. Starting JVM" message on the Log Output and PojavLauncher will stop working.

### Expected behavior:
To launch the Labymod installer properly and detect it as a Minecraft modification.

### Screenshots or videos:
![Screenshot_20210419-210903_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/43190931/115318183-9ccd7480-a153-11eb-8c61-e5855ac249bc.jpg)

**Platform:**
 - Galaxy J7 Prime
 - CPU architecture aarch64
 - Android Version 8.1.0
 - PojavLauncher version 3.3.1.1_rel_20210206

**Comment by AutumnVN** [comment]
https://play.google.com/store/apps/details?id=net.kdt.pojavlaunch or https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk
release version is outdated

**Comment by ghost** [comment]
Hi @AutumnVN !! Thanks for answering.
The App Store link you gave is the one I tried before. Now I've tried using the last artifact (https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/764335734) and the labymod installer was detected as a mod, but some seconds after getting downloaded, PojavLauncher crashes. This is the [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6340385/latestlog.5.txt) of it. Also now I'm having issues when registering an online account and then selecting it when I join Pojav again 
![Screenshot_20210419-235511_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/43190931/115331872-1f166280-a16d-11eb-97c0-a41098c37647.jpg)
This is the full error https://mcpaste.io/c0509b6c5116c25b

**Comment by ghost** [comment]
Nevermind, the account issue is not happening on @khanhduytran0 last artifact. Though it is still happening the same with the Labymod installer.

**Comment by AutumnVN** [comment]
i just read your log, laby cant be used in 1.8.9 for everyone, only solution is play laby 1.12.2

**Comment by ghost** [comment]
Alright, I will try with that version on the AppStore Pojavs that can actually run the labymod installer

**Comment by ghost** [comment]
@AutumnVN  Thank you!! 1.12.2 worked perfectly fine only on the AppStore Pojav's version.

**Comment by TomiGHG** [comment]
Hey how can i become Help
