### ISSUE TITLE
Cheats in server

### ISSUE THREAD

**Issue by sahil12347** [PojavLauncherTeam/PojavLauncher#1257]
I can't use cheats in aternos server

**Comment by AutumnVN** [comment]
even god cant help you with these information

**Comment by khanhduytran0** [comment]
@sahil12347 *bruh, enable cheat on server side first.*

**Comment by sahil12347** [comment]
I enabled

**Comment by EXPress-016** [comment]
> I enabled

Make yourself operator in console
