### ISSUE TITLE
[BUG] <Forge Not Able To Download>

### ISSUE THREAD

**Issue by Harsh-bot-beep** [PojavLauncherTeam/PojavLauncher#1258]
PLS HELP I AM NOT ABLE TO INSTALL LIBARIES IN FORGE ANY VERSION HELP HELP HELP
PSL I WANNA PLAY MINECRAFT
[forge-1.12.2-14.23.5.2854-installer.jar.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6340668/forge-1.12.2-14.23.5.2854-installer.jar.log)

**Comment by Harsh-bot-beep** [comment]
Pls help

**Comment by Harsh-bot-beep** [comment]
@everyone

**Comment by Harsh-bot-beep** [comment]
![Screenshot_2021-04-20-10-20-25-381_net kdt pojavlaunch](https://user-images.githubusercontent.com/76815433/115339311-2025af00-a1c2-11eb-844b-d7762a5a66b6.jpg)

**Comment by Harsh-bot-beep** [comment]
@khanhduytran0

**Comment by Harsh-bot-beep** [comment]
@LegacyGamerHD

**Comment by Harsh-bot-beep** [comment]
@artdeell

**Comment by stacode123** [comment]
Gez just wait a second stop doing @ 
and @ ing does not work

**Comment by stacode123** [comment]
oh and stop spamming at 6 am

**Comment by ySrWindohz** [comment]
> PLS HELP NÃO POSSO INSTALAR BIBLIOTECAS NO FORGE NENHUMA VERSÃO HELP HELP HELP
> PSL QUERO JOGAR MINECRAFT
> [forge-1.12.2-14.23.5.2854-installer.jar.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6340668/forge-1.12.2-14.23.5.2854-installer.jar.log)

delete 1.12.2 json and try again
Redownload 1.12.2

**Comment by ySrWindohz** [comment]
> PLS HELP I AM NOT ABLE TO INSTALL LIBARIES IN FORGE ANY VERSION HELP HELP HELP
> PSL I WANNA PLAY MINECRAFT
> [forge-1.12.2-14.23.5.2854-installer.jar.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6340668/forge-1.12.2-14.23.5.2854-installer.jar.log)

delete 1.12.2 json and try again
Redownload 1.12.2

**Comment by Harsh-bot-beep** [comment]
> Gez just wait a second stop doing @
> and @ ing does not work

NO I AM PANIC I CANNIT LIVE WITHOUT MINECRAFT

**Comment by Harsh-bot-beep** [comment]
It someone download but not showing code 1

**Comment by Harsh-bot-beep** [comment]
😔🖕

**Comment by Harsh-bot-beep** [comment]
It's working now

**Comment by WesleyVanNeck** [comment]
> 😔🖕

I will ban you from this repo any last words kido
