### ISSUE TITLE
[Question] Premium Compatibility

### ISSUE THREAD

**Issue by issuereporter292** [PojavLauncherTeam/PojavLauncher#126]
Will it ever be possible to play on premium servers with Android 6 and up?

**Comment by khanhduytran0** [comment]
You can't at the moment.

**Comment by issuereporter292** [comment]
> You can't at the moment.

Will it be possible though?

**Comment by khanhduytran0** [comment]
> Will it be possible though?

Not sure if possible in the future or soon...

**Comment by JCDURAN7** [comment]
Brother dropped me by to see if there will be any way to get into the premium servers. my android is version 9 So I was wondering when you can make that happen for us?

**Comment by khanhduytran0** [comment]
The problem is at encryption. Once I made changes of encryption in Android 6.0 or above the launcher can join to premium servers.

**Comment by CloserPopcorn20** [comment]
You can enter premium servers only in VMOS pojavlauncher, but if you wanna to launch premium servers on android 9, you can install MCinaBox, prepare for play with it, and...enjoy?
(So sorry, bad English)

**Comment by khanhduytran0** [comment]
> but if you wanna to launch premium servers on android 9, you can install MCinaBox

My device is Android 5. Android-x86 is 9.0, before I tried one time in 9.0 but crash and a different crash in Android 5.

**Comment by issuereporter292** [comment]
> You can enter premium servers only in VMOS pojavlauncher, but if you wanna to launch premium servers on android 9, you can install MCinaBox, prepare for play with it, and...enjoy?
> (So sorry, bad English)

I just wanted to say that vmos doesn't work for premium servers.

**Comment by khanhduytran0** [comment]
Both v2 and v3 have support for premium servers now.
