### ISSUE TITLE
[F-REQ]can you make it run on lower end ios devices

### ISSUE THREAD

**Issue by liamvmorar** [PojavLauncherTeam/PojavLauncher#1260]
Im annoyed that it only run with devices with an a12 processer and all my devices dont have them 

Could you please make a version that runs on lower end devices because i jailbroke my phpne and ipad just to try and use this

Or if its to hard then could you please make a remote desktop that doesnt require turning on your pc

thank you for taking times to read this request and do hope you have this idea in mind

**Comment by WesleyVanNeck** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher_iOS

**Comment by khanhduytran0** [comment]
A8 devices should run well.
A9 runs well at ~30fps.
