### ISSUE TITLE
[BUG] i can't install forge 1.7.10

### ISSUE THREAD

**Issue by ySrWindohz** [PojavLauncherTeam/PojavLauncher#1261]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6345992/latestlog.txt)

**Comment by ySrWindohz** [comment]
Pls help me

**Comment by crtvxxx** [comment]
Dude, you have a installed Runtime?

**Comment by WesleyVanNeck** [comment]
Fill the templat
