### ISSUE TITLE
[BUG] The Game alway's crash on Osmesas-Devs-Tests 

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1263]
--------- beggining with launcher debug Info: Launcher version: 3.3.1.1_rel_20210418 Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version] Architecture: arm/aarch32 Info: Custom Java arguments: "-Dorg.lwjgl.opengl.libname=libgl4es_115.so -Xms768m -Xmx800m -Dorg.lwjgl.opengl.libname=libOSMesa_8.so -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy" --------- beginning of crash --------- beginning of main Headless version detected! (20210317) WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so" has unsupported flags DT_FLAGS_1= 0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so" has unsupported flags DT_FLAGS_1= 0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so" has unsupported flags DT_FLAGS_1= 0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so " has unsupported flags DT_FLAGS_1= 0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so " has unsupported flags DT_FLAGS_1= 0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so " has unsupported flags DT_FLAGS_1= 0x81 WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so" has unsupported flags DT_FLAGS_1=0x81 WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success WARNING: linker: I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so " has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so" has unsupported flags DT_FLAGS_1=0x81 I/jrelog ( 2590): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success I/jrelog ( 2590): dlopen /data/app/net.kdt.pojavlaunch-svPpOWSwBTgj1QbHv-zzrQ==/lib/arm/libopenal.so success I/jrelog ( 2590): dlopen libOSMesa_8.so success I/jrelog ( 2590): Done processing args I/jrelog ( 2590): Found JLI lib I/jrelog ( 2590): Calling JLI_Launch OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes OpenJDK Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release [03:01:12] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' [03:01:24] [Render thread/ERROR]: Failed to verify authentication com.mojang.authlib.exceptions.AuthenticationUnavailableException: null 	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?] 	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?] 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?] 	at dsp.a(SourceFile:643) [21w11a.jar:?] 	at dsp.<init>(SourceFile:414) [21w11a.jar:?] 	at net.minecraft.client.main.Main.main(SourceFile:178) [21w11a.jar:?] [03:01:24] [Render thread/INFO]: Setting user: HenLogMC [03:01:25] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions: 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath. 	b) Add the JAR that contains the shared library to the classpath. [03:01:25] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics. [03:01:25] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics. [03:01:27] [Render thread/WARN]: Invalid floating point value for option textBackgroundOpacity = java.lang.NumberFormatException: empty String 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:1.8.0-internal] 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0-internal] 	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0-internal] 	at dst$2.a(SourceFile:402) [21w11a.jar:?] 	at dst.a(SourceFile:280) [21w11a.jar:?] 	at dst.a(SourceFile:360) [21w11a.jar:?] 	at dst.<init>(SourceFile:218) [21w11a.jar:?] 	at dsp.<init>(SourceFile:444) [21w11a.jar:?] 	at net.minecraft.client.main.Main.main(SourceFile:178) [21w11a.jar:?] [03:01:28] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT OSMDroid: using built-in libOSMesa_8.so OSMDroid: width=1280;height=720, reserving 3686400 bytes for frame buffer OSMDroid: created frame buffer OSMDroid: generating context ../src/gallium/drivers/zink/zink_screen.c:778: VkPhysicalDevice choose_pdev(const VkInstance): assertion "pdev_count > 0" failed

**Comment by jumperli** [comment]
Use only this -Dorg.lwjgl.opengl.libname=libOSMesa_8.so

**Comment by jumperli** [comment]
Not this -Dorg.lwjgl.opengl.libname=libgl4es_115.so

**Comment by WesleyVanNeck** [comment]
Fill the template

**Comment by khanhduytran0** [comment]
@OwzygZawg your phone doesn't support vulkan and it's likely you are spamming issue ⚠️

**Comment by khanhduytran0** [comment]
Duplicate of #1239
