### ISSUE TITLE
Osmesa dev test pojavlauncher with Zink is crash on my phone when I click play button it is crash plz fix the bug I installed pojavlauncher for shaders but it is not working

### ISSUE THREAD

**Issue by Tejas-Mahajan** [PojavLauncherTeam/PojavLauncher#1266]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Tejas-Mahajan** [comment]
This is a video of crash problem

**Comment by AzarinMC** [comment]
> This is a video of crash problem

Where??

**Comment by AzarinMC** [comment]
> This is a video of crash problem

What Is your phone device and gpu

**Comment by Tejas-Mahajan** [comment]
My phone is redmi note 8 4gb ram , 64 gb internal storage , Snapdragon 665 processor

**Comment by AzarinMC** [comment]
> My phone is redmi note 8 4gb ram , 64 gb internal storage , Snapdragon 665 processor

Upgrade your gpu to mali

**Comment by Tejas-Mahajan** [comment]
What ! How to upgrade our gpu

**Comment by AzarinMC** [comment]
Maybe this can help you
>#162

**Comment by AzarinMC** [comment]
Maybe this can help you

> What ! How to upgrade our gpu

>#1262

**Comment by AzarinMC** [comment]
@LegacyGamerHD

**Comment by khanhduytran0** [comment]
@AzarinMC mobile GPU is not upgradable.

**Comment by khanhduytran0** [comment]
@Tejas-Mahajan fill into the template.

**Comment by AzarinMC** [comment]
> @AzarinMC mobile GPU is not uogradable
Iknow i just want he know upgrade his phone
