### ISSUE TITLE
Có thể thêm nút pvp được không

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1273]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Joakdnhio** [comment]
Mong nhà phát triển cho thêm nút pvp vào

**Comment by khanhduytran0** [comment]
Được chứ. Bạn vào "tùy chọn" -> "tuỳ chỉnh điều khiển" rồi chỉnh các nút theo ý muốn.

**Comment by Joakdnhio** [comment]
Ok

**Comment by Joakdnhio** [comment]
Những phím gì

**Comment by AutumnVN** [comment]
thích thêm phím gì thì thêm

**Comment by Joakdnhio** [comment]
Chọn phím nào

**Comment by Joakdnhio** [comment]
Mà sao lại có phím kana

**Comment by Joakdnhio** [comment]
Tại sao không thể pvp 8LMB
