### ISSUE TITLE
Osmesa dev test pojavlauncher with Zinc is not working when clicking play button it may be crash

### ISSUE THREAD

**Issue by Tejas-Mahajan** [PojavLauncherTeam/PojavLauncher#1277]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Redmi note 8 4 gb ram 64 gb storage
 - CPU architecture aarch64] 
 - Android Version  10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Tejas-Mahajan** [comment]
Plz make the Zink comptable with androino gpu plz I like to play with java shader plz plz

**Comment by Tejas-Mahajan** [comment]
Why you are closed this bug

**Comment by khanhduytran0** [comment]
Your phone probably don't support Vulkan.

**Comment by khanhduytran0** [comment]
Also fill da template
