### ISSUE TITLE
I download Zink tested pojavlauncher but only chocapic V7 shader run and other shader like bsl and chocapic V6 is not working

### ISSUE THREAD

**Issue by Tejas-Mahajan** [PojavLauncherTeam/PojavLauncher#1280]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6364973/latest.log)

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. redmi note 8 4 gb ram 64 gb internal storage]
 - CPU architecture [e.g. aarch64] 
 - Android Version [ 10]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210422]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Tejas-Mahajan** [comment]
architecture 64 bit

**Comment by Tejas-Mahajan** [comment]
What I do to work all shader

**Comment by khanhduytran0** [comment]
latest.log ≠ latestlog.txt
Also please don't expect all shaders will work, **remember that you are on phone GPU, not PC GPU.**

**Comment by Tejas-Mahajan** [comment]
But I see in youtube chocapic V6 lite shader and BSL shader is also work on mobile

**Comment by Tejas-Mahajan** [comment]
This is link of the video https://youtu.be/09HdSxCZvTg

**Comment by ENDERMANYK** [comment]
Does your phone processor is same to the guy make the video? if not stop asking this

**Comment by Tejas-Mahajan** [comment]
My phone have Snapdragon 665 processor

**Comment by Tejas-Mahajan** [comment]
In this video a man say processor does not take matter

**Comment by ENDERMANYK** [comment]
Is he the Java shader developer? If not there's no need to believe him, also Pojavlauncher only support launcher instead of graphic things, for more SOC support spam in zink(Mesa) GitHub
