### ISSUE TITLE
Plz make the Zink compatible with all mobile because we do not run shader 

### ISSUE THREAD

**Issue by Tejas-Mahajan** [PojavLauncherTeam/PojavLauncher#1282]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WesleyVanNeck** [comment]
stop flooding our issue tracker with zink spam

**Comment by ebuild-1** [comment]
> stop flooding our issue tracker with zink spam

Just block him for posting here on GitHub ez
