### ISSUE TITLE
Nhà phát triển Trần Thánh Duy có thể thêm nút tự động  click không???

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1283]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Joakdnhio** [comment]
Mong Nhà phát triển Thêm được nút

**Comment by Joakdnhio** [comment]
Lí do vì pvp Minecraft phải nhấn liên tục vào nút PRI

**Comment by AutumnVN** [comment]
thì cài mod auto click gì đấy vào, ko thì cài hack luôn đi ._.

**Comment by Joakdnhio** [comment]
Cài mod auto bị ban sever hack cũng thế

**Comment by khanhduytran0** [comment]
Thì autoclick cũng bị ban thôi. Họ chỉ việc code mấy cái check là dính liền.

**Comment by Joakdnhio** [comment]
Bây giờ auto click phím Như kiểu ứng dụng key mapper được không
