### ISSUE TITLE
Can we play modpacks Like Rlcraft or pixelmon in future without curseforge launcher?

### ISSUE THREAD

**Issue by FitTurkoglu** [PojavLauncherTeam/PojavLauncher#1284]
Can we play modpacks without curseforge launcher?

**Comment by Adam0530** [comment]
> Can we play modpacks without curseforge launcher?

yes you can, if I am not wrong.. But it maybe little complicated for you to use modpack on pojav.... Maybe.... Cause I have not test it yet

**Comment by FitTurkoglu** [comment]
> > Can we play modpacks without curseforge launcher?
> 
> yes you can, if I am not wrong.. But it maybe a little complicated for you to use modpack on pojav.... Maybe.... Cause I have not test it yet

Can you make a video about this? 
If you can

**Comment by Adam0530** [comment]
> > > Can we play modpacks without curseforge launcher?
> > 
> > yes you can, if I am not wrong.. But it maybe a little complicated for you to use modpack on pojav.... Maybe.... Cause I have not test it yet
> 
> Can you make a video about this? 
> If you can
Lazy :/

**Comment by mchnjt** [comment]
> Can we play modpacks without curseforge launcher?

I tested botania with the required dependency, and it works. The only problem is it eats up the entire allocation in 4 seconds

**Comment by ghost** [comment]
Yes work 
But my phone potato _- 

Min Spec maybe :  allocated ram 2gb+

**Comment by FitTurkoglu** [comment]
I tried it works but game instantly crashes after 5 minutes you join the world.

**Comment by FitTurkoglu** [comment]
> Yes work 
> But my phone potato _- 
> 
> Min Spec maybe :  allocated ram 2gb+

I tried it works but game instantly crashes after 5 minutes you join the world.

**Comment by ghost** [comment]
> > Ya bekerja 
> > Tapi kentang ponsel saya _-
> > Min Spec mungkin: ram yang dialokasikan 2gb+
> 
> Saya mencobanya berfungsi tetapi game langsung macet setelah 5 menit Anda bergabung dengan dunia.

if the game wants to work with modpack 
You can choose this answer


1. Buy PC
2. Buy PC
3. Buy PC

**Comment by SprainedSpark89** [comment]
just download the mods one by one

**Comment by Mathias-Boulay** [comment]
Technically, yes
