### ISSUE TITLE
To legacygamerhd - am using your zink app but it's lagging even I didn't use shader my phone xiaomi 9t pro adreno processor 855 can I help me I try to search in youtube they not lagging in kirin phone but andreno phone is super lagg 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1286]
To legacygamerhd - am using your zink app but it's lagging even I didn't use shader my phone xiaomi 9t pro adreno processor 855 can I help me I try to search in youtube they not lagging in kirin phone but andreno phone is super lagg

**Comment by WesleyVanNeck** [comment]
Stop spamming the issue tracker zink is not ready for daily use

**Comment by WesleyVanNeck** [comment]
It lags on Kirin to am 100% sure about it
