### ISSUE TITLE
Không chạy được mods fabric khi cài mod optifabric-1.9.6

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1289]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Joakdnhio** [comment]
Mong nhà phát triển giúp

**Comment by AutumnVN** [comment]
"không chạy được" là crash hay đứng hay lỗi như nào, mô tả thế ai mà giúp được -_- , ít ra cũng phải up cái latestlog.txt với screenshots nữa, đằng này không điền một tí thông tin nào hết.

**Comment by Joakdnhio** [comment]
Cứ bị đứng

**Comment by khanhduytran0** [comment]
> Cứ bị đứng 

Có thánh cũng không hiểu được bị sao nếu để cái phiếu báo cáo lỗi trống rỗng.

**Comment by Joakdnhio** [comment]
https://youtu.be/DZW_m6Mo3Â

**Comment by Joakdnhio** [comment]
lỗi video

**Comment by Joakdnhio** [comment]
https://youtu.be/DZW_m6Mo3AA
