### ISSUE TITLE
[BUG] Unable To Play On Servers On 1.8.9

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#1290]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

While Playing With 1.8.9 Minecraft Crashes And Opens Launcher Automatically, While Playing On 1.16.5 I have Experienced No Crash But In 1.8.9 The Crash Is Insane Since I Don't Get Any Crash On Crash Log On Launcher Console

**Add a log file if you want to see your bug fixed !**

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6371416/latestlog.txt)

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Open Minecraft 1.8.9 vanilla or forge
3. Play On Any Cracked Server [mc.crackpixel.net]
4. After 2-5 mins : Crash

### Expected behavior:
I expected Game would run normally

### Screenshots or videos:
*None Available *

**Platform:**
 - Device Model [vivo V5]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 7]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by nabiloi** [comment]
change your version of pojavlauncher to non (osmesa-dev-tests / zink_test)

**Comment by khanhduytran0** [comment]
@AgaricaGamer enable VBO
