### ISSUE TITLE
[BUG] cài mod optifabric-1.9.6 vào không thể chơi được

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1291]
Mod này dành cho fabric.
Khi mình cài mod này xong rồi chơi thì cứ bị đứng.
Video https://youtu.be/DZW_m6Mo3AA 
Mong nhà phát triển giúp đỡ.
😀😀😀

**Comment by Joakdnhio** [comment]
Mong mọi người giúp đỡ.😚😚😚

**Comment by AutumnVN** [comment]
sao lại cài sodium với optifine, 1 trong 2 thôi

**Comment by Joakdnhio** [comment]
Tôi không biết

**Comment by Joakdnhio** [comment]
Những tôi bây giờ chỉ cài optifabric-1.9.6 thôi

**Comment by Joakdnhio** [comment]
Những vẫn thế

**Comment by AutumnVN** [comment]
![Screenshot_2021-04-25-17-23-14-63](https://user-images.githubusercontent.com/77253698/115989946-07b2fb80-a5eb-11eb-93e4-4e2a3e35cc37.png)
chữ sodium to đùng ngay đầu dòng 4

**Comment by Joakdnhio** [comment]
Xin lỗi xoá latestlog.txt rồi cài lại thì được

**Comment by Joakdnhio** [comment]
Những nó lại bảo there was an Loading  opitpfabric.

**Comment by AutumnVN** [comment]
screenshots hoặc ghi hết chữ ra

**Comment by Joakdnhio** [comment]
https://youtu.be/qvqec9p_Sz8

**Comment by Joakdnhio** [comment]
Mạng yếu

**Comment by Joakdnhio** [comment]
Vậy có cách nào sử lý không

**Comment by khanhduytran0** [comment]
Có optifabric mà không có optifine :facepalm:

**Comment by AutumnVN** [comment]
bạn phải bỏ optifine vào trong mods nữa

**Comment by Mathias-Boulay** [comment]
Stale issue from an old version, and optifcabric seems to work
