### ISSUE TITLE
Lỗi không chơi được vào máy chủ ATERNOS

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1292]
Nó cứ thiện lên ở chỗ đo ping là chữ cũ
Mong nhà phát triển giúp đỡ 😄😄😄

**Comment by khanhduytran0** [comment]
Bạn cứ "RIP" luôn cái mẫu báo cáo lỗi là sao?

**Comment by AutumnVN** [comment]
dùng dynamic ip

**Comment by Joakdnhio** [comment]
YouTube video https://youtu.be/NdFXv0UVQV8

**Comment by Joakdnhio** [comment]
Bây giờ sửa lỗi kiểu gì

**Comment by AutumnVN** [comment]
tắt online mode chưa

**Comment by EnderBrine99FOX** [comment]
> YouTube video https://youtu.be/NdFXv0UVQV8

Enable Cracked Version To Make It Work With You
![Screenshot_20210426_080312_com android chrome](https://user-images.githubusercontent.com/79517194/116031279-04108a80-a666-11eb-9886-026f561bf904.jpg)

**Comment by Joakdnhio** [comment]
Rồi

**Comment by Mathias-Boulay** [comment]
duplicate from #923
