### ISSUE TITLE
[BUG] 1.8 always crashes!!!

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1294]
Always crashes every single time and I am F## PISSED😠
### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
2. Join world or server
3. Crash in 15 sec 😠😠👎👎
### Expected behavior:
I expected to not CRASH ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [OPPO A12 4/64]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 9]
 - PojavLauncher Version [ Version 3.3.1.1_rel_20210417 ]

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6374417/latestlog.txt)

**Comment by AutumnVN** [comment]
turn on vbo

**Comment by ebuild-1** [comment]
> turn on vbo

?

**Comment by AutumnVN** [comment]
vbo in video settings

**Comment by ebuild-1** [comment]
Ok

**Comment by ebuild-1** [comment]
> vbo in video settings

It works but for some reason it still crashes in 10 min? 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6374470/latestlog.txt)

**Comment by WesleyVanNeck** [comment]
intresting `[0426/131913.464926:ERROR:elf_dynamic_array_reader.h(61)] tag not found`

**Comment by WesleyVanNeck** [comment]
@khanhduytran0

**Comment by WesleyVanNeck** [comment]
he is using gl4es

**Comment by AutumnVN** [comment]
i saw a guy has that elf error too on discord, and khanhduytran told him enable vbo 👀
https://discord.com/channels/724163890803638273/724163890803638277/835827237286313994

**Comment by khanhduytran0** [comment]
> elf_dynamic_array_reader.h(61)] tag not found

I’ve said no need to take care of it. If you still, go and fix the Android linker. Google it, that print everywhere **after a native crash**.

**Comment by khanhduytran0** [comment]
Stills need to extract the native crash report.

**Comment by ebuild-1** [comment]
Pls fix tnx

**Comment by khanhduytran0** [comment]
Also
```
[04:50:55] [Client thread/INFO]: [CHAT] Kicked whilst connecting to factions: You are not whitelisted on this server!
```

**Comment by ebuild-1** [comment]
> Also
> 
> ```
> [04:50:55] [Client thread/INFO]: [CHAT] Kicked whilst connecting to factions: You are not whitelisted on this server!
> ```

Yeah you need to be whitelisted for that, but pls I need to bug to be fixed 🙏🙏

**Comment by zezayne** [comment]
What version of 1.8 are u playing (eg . 1.8.9)

1.8.9 works smoothly on my old Samsung Galaxy A7

**Comment by ebuild-1** [comment]
I'm using 1.8.9

**Comment by zezayne** [comment]
It looks like your phone's specs are slightly better than mine 
My Samsung Galaxy A7 2017 :
GPU 0.6Ghz , yours GPU : 0.65 -0.66 Ghz
You have 64 GB of storage while I have only 32GB
My phone runs Android 8 , yours run Android 9 

So I cannot see why your phone cannot run the game even your hardware is better than me . 
Question :  1) Did you download it from the Google Play Store ?
                   2) Is there any updates for PojavLauncher that you haven't installed ?
                   
Try :  1) reinstalling PojavLauncher (it won't uninstall the current version you have installed )

**Comment by Ultrasonic1209** [comment]
Or try setting renderer to OpenGL ES 2, worked for me with my Samsung Galaxy S21+.

**Comment by SergueiKhadirov** [comment]
How much ram u give ?
Also how much storage space is left in ur phone?

**Comment by Irsplayer1** [comment]
> vbo in video settings

Bro thank you so much

**Comment by khanhduytran0** [comment]
Perhaps disabling VBO (in the launcher settings) should do something with this.
