### ISSUE TITLE
Lỗi không thể cài thêm forge ?

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1298]
Nó ở bị lỗi phiên bản 1.8 
Cứ bị đứng

**Comment by Joakdnhio** [comment]
Khi mình chạy file này thì có đòng lệnh này.
Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=2280x1080, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /storage/emulated/0/Download/forge-1.8-11.14.4.1577-installer.jar]
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" unused DT entry: DT_RPATH (type 0xf arg 0x361) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" unused DT entry: DT_RPATH (type 0xf arg 0x450) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" unused DT entry: DT_RPATH
 (type 0xf arg 0x33c0) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x13b8
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" unused DT entry: DT_RPATH (type 0xf arg 0x2196) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" unused DT entry: DT_RPATH (type 0xf arg 0x6a68) (ignoring)

WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: DT_RPATH (type 0xf arg 0x4d9) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0xda0
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
" unused DT entry: 
DT_RPATH (type 0xf arg 
0x16fe) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" has unsupported flags DT_FLAGS_1=
0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" unused DT entry: DT_RPATH (type 0xf arg 0x6af) (ignoring)

WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so
" unused DT entry: DT_RPATH (type 0xf arg 0xf13) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)

WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" unused DT entry: DT_RPATH (type 
0xf arg 0x103) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" unused DT entry: DT_RPATH (type 0xf arg 0x2e6) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so
" unused DT entry: 
DT_RPATH
 (type 0xf arg 0x158) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" unused DT entry: DT_RPATH (type 0xf arg 0x23a) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x77) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" has unsupported flags DT_FLAGS_1=0x81
 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0xe6
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so" unused DT entry: DT_RPATH (type 0xf arg 
0x3ed) (ignoring)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" unused DT entry: DT_RPATH (type 0xf arg 0x1d2) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" unused DT entry: 
DT_RPATH (type 0xf arg 0x139) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x3f1
) (ignoring)

WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x364
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" unused DT entry: DT_RPATH (type 0xf arg 0x119) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x1c1
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" unused DT entry: DT_RPATH (type 0xf arg 0x8ff) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" unused DT entry: DT_RPATH (type 0xf arg 0x6c1) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so
" unused DT entry: 
DT_RPATH
 (type 
0xf arg 
0x5e6) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x1c7
) (ignoring)

WARNING: linker: 
Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

Policy policy.url.2=file:/storage/emulated/0/games/PojavLauncher/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/games/PojavLauncher/.java.policy (No such file or directory)

Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/*

Setting up logger: /storage/emulated/0/games/PojavLauncher/.minecraft/forge-1.8-11.14.4.1577-installer.jar.log

Exception in thread "main" 
java.lang.ExceptionInInitializerError
	at net.minecraftforge.installer.ClientInstall.getSponsorMessage(ClientInstall.java:326)
	at net.minecraftforge.installer.InstallerAction.getSponsorMessage(InstallerAction.java:59)
	at net.minecraftforge.installer.InstallerPanel.updateFilePath(InstallerPanel.java:236)
	at net.minecraftforge.installer.InstallerPanel.<init>(InstallerPanel.java:217)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:153)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:40)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at net.minecraftforge.installer.MirrorData.buildMirrorList(MirrorData.java:84)
	at net.minecraftforge.installer.MirrorData.<init>(MirrorData.java:63)
	at net.minecraftforge.installer.MirrorData.<clinit>(MirrorData.java:17)
	... 6 more

**Comment by Joakdnhio** [comment]
https://youtu.be/kldIJXfQeA8

**Comment by khanhduytran0** [comment]
Forge hiện ai cũng bị vậy hết
