### ISSUE TITLE
Unable to write space in the game

### ISSUE THREAD

**Issue by jrxohan** [PojavLauncherTeam/PojavLauncher#13]
I have been seeing that in every version that the same error occurs when pressing the keyboard button it does not allow me to write space, but rather that it press the buttons on the screen such as "debug" and others, and I say that it is an error since in the old version  this did not happen, here is a video to understand
https://youtu.be/e-aPFMUAKKM

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.6.2

**Comment by jrxohan** [comment]
> https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.6.2

Thanks now the issue is solved
