### ISSUE TITLE
Optifine Shaders Menu Not working. 

### ISSUE THREAD

**Issue by GeraldBalingcasag** [PojavLauncherTeam/PojavLauncher#130]
In an 8gb ram phone I could run minecraft and the fps never drops less than 100.

But the Shaders Menu doesn't seem to work, it just freezes and I had to close the PojavLauncher tab. 

Unfortunately, It doesn't show any error code so I'm screwed.

**Comment by artdeell** [comment]
> In an 8gb ram phone I could run minecraft and the fps never drops less than 100.
> 
> But the Shaders Menu doesn't seem to work, it just freezes and I had to close the PojavLauncher tab.
> 
> Unfortunately, It doesn't show any error code so I'm screwed.

You just need to wait REALLY long before shader program loads.

**Comment by khanhduytran0** [comment]
You need wait a bit while OptiFine load shader if select, but will crash after load world/join server.

**Comment by khanhduytran0** [comment]
Arount 2~5min

**Comment by artdeell** [comment]
> The Shader Conversion is really crude, so only simple shaders will work (especialy, the implicit conversion float <-> int is not handled)

This is the issue

**Comment by GeraldBalingcasag** [comment]
It can't be too laggy?
Also I wanna see an example of one shader I can use

**Comment by artdeell** [comment]
> It can't be too laggy?
> Also I wanna see an example of one shader I can use

Now attempting to find one

**Comment by khanhduytran0** [comment]
> > The Shader Conversion is really crude, so only simple shaders will work (especialy, the implicit conversion float <-> int is not handled)
> 
> This is the issue
