### ISSUE TITLE
[ASK-F]ITS ZINK SUPPORT??

### ISSUE THREAD

**Issue by AzarinMC** [PojavLauncherTeam/PojavLauncher#1300]
**ITS ZINK Support my device??**

*My Device Spec:
>Xiaomi A1
OS  : Android 7.1.2 (Nougat), upgradable to Android 9.0 (Pie), Android One
Chipset : Qualcomm MSM8953 Snapdragon 625 (14 nm)
CPU  : Octa-core 2.0 GHz Cortex-A53
GPU  : Adreno 506*

**Comment by AzarinMC** [comment]
Why did you closed this?? @LegacyGamerHD

**Comment by LegacyGamerHD** [comment]
> Why did you closed this?? @LegacyGamerHD

because zink isnt ready and it should not be used

**Comment by CriticalRange** [comment]
> **ITS ZINK Support my device??**
> 
> *My Device Spec:
> 
> > Xiaomi A1
> > OS  : Android 7.1.2 (Nougat), upgradable to Android 9.0 (Pie), Android One
> > Chipset : Qualcomm MSM8953 Snapdragon 625 (14 nm)
> > CPU  : Octa-core 2.0 GHz Cortex-A53
> > GPU  : Adreno 506*

you can check if your device supports it via this app: https://play.google.com/store/apps/details?id=com.realtechvr.glview

**Comment by AzarinMC** [comment]
> > **ITS ZINK Support my device??**
> > *My Device Spec:
> > > Xiaomi A1
> > > OS  : Android 7.1.2 (Nougat), upgradable to Android 9.0 (Pie), Android One
> > > Chipset : Qualcomm MSM8953 Snapdragon 625 (14 nm)
> > > CPU  : Octa-core 2.0 GHz Cortex-A53
> > > GPU  : Adreno 506*
> 
> you can check if your device supports vulkan via this app: https://play.google.com/store/apps/details?id=com.realtechvr.glview
