### ISSUE TITLE
Can you make java 8 support for 64 bit users because when i use any mods in forge/fabric it crash

### ISSUE THREAD

**Issue by Po-arch** [PojavLauncherTeam/PojavLauncher#1301]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AgaricaGamer** [comment]
Bruh, Fill The Template Correctly First

**Comment by Po-arch** [comment]
Bro what template im jealous about 32 bit users have java 8 in pojav

**Comment by WesleyVanNeck** [comment]
fill the template and java 8 is supported by 64bit devices
