### ISSUE TITLE
zink test crashing problem

### ISSUE THREAD

**Issue by Po-arch** [PojavLauncherTeam/PojavLauncher#1303]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Po-arch** [comment]
--------- beggining with launcher debug
Info: Launcher version: 3.3.1.1_rel_20210422
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms768m -Xmx800m"
Headless version detected! (20210426)
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
: unused DT entry: type 0xf arg 0x361
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so: unused DT entry: type 
0xf arg 0x450
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so: unused DT entry: type 
0xf arg 0x33c0
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so: unused DT entry: type 
0xf arg 0x13b8
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so: unused DT entry: type 0xf arg 0x2196
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so: unused DT entry: type 
0xf arg 0x6a68
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so: unused DT entry: type 
0xf arg 0x4d9
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so: unused DT entry: type 0xf arg 
0xda0
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so: unused DT entry: type 0xf arg 0x5e6
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so: unused DT entry: type 
0xf arg 0x77
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so: unused DT entry: type 0xf arg 
0x1c7
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so: unused DT entry: type 0xf arg 0x8ff
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so: unused DT entry: type 0xf arg 0x16fe
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so: unused DT entry: type 0xf arg 0x2e6
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so
: unused DT entry: type 0xf arg 0xe6
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so: unused DT entry: type 0xf arg 0x119
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so: unused DT entry: type 0xf arg 0x364
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so: unused DT entry: type 0xf
 arg 0x139
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so: unused DT entry: type 0xf arg 0xf13
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so: unused DT entry: type 0xf arg 0x3f1
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so: unused DT entry: type 0xf arg 0x158
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so: unsupported flags DT_FLAGS_1=0x81
--------- beginning of main
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so: unused DT entry: type 0xf arg 
0x6af
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so
: unused DT entry: type 0xf arg 0x1c1
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so
: unused DT entry: type 0xf arg 0x6c1
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so: unused DT entry: type 0xf arg 0x23a
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so
: unused DT entry: type 0xf arg 0x103
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so: unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so: unused DT entry: type 0xf arg 0x1d2
WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so: unsupported flags DT_FLAGS_1=0x81
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
[14:46:15] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[14:46:15] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[14:46:15] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions

OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer

OptiFine ZIP file: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/optifine/OptiFine/1.16.5_HD_U_G7/OptiFine-1.16.5_HD_U_G7.jar

OptiFineTweaker: getLaunchArguments

OptiFineTweaker: getLaunchTarget
[14:46:16] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[14:46:17] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[14:46:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[14:46:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[14:46:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[14:46:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[14:46:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[14:46:40] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:46:45] [main/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[YggdrasilSocialInteractionsService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[YggdrasilSocialInteractionsService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[YggdrasilAuthenticationService.class:?]
	at djz.a(SourceFile:625) [djz.class:?]
	at djz.<init>(SourceFile:409) [djz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:177) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
[14:46:45] [main/INFO]: Setting user: Sajid
[14:46:46] [main/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[14:46:46] [main/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[14:46:46] [main/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[14:46:46] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[14:46:47] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier
[14:46:47] [main/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
OSMDroid: using built-in libOSMesa_8.so
OSMDroid: unable to load: dlopen failed: library "libOSMesa_8.so" wasn't loaded and RTLD_NOLOAD prevented it

it crashes everytime before the splash of mojang

**Comment by Po-arch** [comment]
Platform:

Device Model:CPH1723
CPU architecture:aarch 64
Android Version:7.1.1
PojavLauncher Version:dev build

**Comment by WesleyVanNeck** [comment]
> Platform:
> 
> Device Model:CPH1723
> CPU architecture:aarch 64
> Android Version:7.1.1
> PojavLauncher Version:dev build

vulkan is not suported on your device

**Comment by Po-arch** [comment]
iys supported i looked up for Vulkancapsviewer its supported my vulkan version 1.0 so why did it crash

**Comment by WesleyVanNeck** [comment]
> iys supported i looked up for Vulkancapsviewer its supported my vulkan version 1.0 so why did it crash

You don't support right vulkan 1.1 or higher and you miss some extension

**Comment by khanhduytran0** [comment]
@Po-arch
- you haven't set zink jvm argument **or haven't** updated to latest zink build.
- Android 8 and newer is required for Mesa3D.
