### ISSUE TITLE
[BUG]I cant look around using samsung a12 

### ISSUE THREAD

**Issue by happywarrior73** [PojavLauncherTeam/PojavLauncher#1306]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Im using samsung a12 and i cant look around and move the mouse the mouse speed is in default and ive tried using older versions it doesnt seem to work i dont know what to do can anyone help 

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2.play
3.mouse cant move and theres nothing i can do

### Expected behavior:
I expected ...
The mouse to move and to look around
### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [Samsung galaxy a12]
 - CPU architecture [aarch64] 
 - Android Version [10]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by TDTSUNFANS** [comment]
same for me,I'm using Samsung Galaxy A12

**Comment by WesleyVanNeck** [comment]
Get a better phone

**Comment by TDTSUNFANS** [comment]
But I don't have enough money :(

**Comment by khanhduytran0** [comment]
@happywarrior73 you knew there was one, don't duplicate issue!

**Comment by khanhduytran0** [comment]
Duplicate of #1235
