### ISSUE TITLE
[java internal version 1.8 problem] <i have some problem in the new pojav with java 8 the log says java internal v1.8 and not using java 8 i think its a bug or device problem>

### ISSUE THREAD

**Issue by Po-arch** [PojavLauncherTeam/PojavLauncher#1308]
this new pojav says it is using java 8 but i looked up in log i see is java internal v1.8

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model OPPO F5/CPH1723/MT6763CT
 - CPU architecture aarch64/ARMv8
 - Android Version 7.1.1
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Bruh you don’t know how Java version name works?
https://softwareengineering.stackexchange.com/questions/175075/why-is-java-version-1-x-referred-to-as-java-x

**Comment by khanhduytran0** [comment]
Remember this version naming rule:
- Java 1.X = Java X

**Comment by khanhduytran0** [comment]
![DB7C94FF-6E08-41F3-988F-424F383C85BD](https://user-images.githubusercontent.com/40482367/116518883-017a9300-a8fb-11eb-89c6-960cae150e22.jpeg)
