### ISSUE TITLE
[BUG] <can't login Microsoft account>plz fix the bug i can't login my Microsoft acc :(

### ISSUE THREAD

**Issue by gamerboy82yt** [PojavLauncherTeam/PojavLauncher#1309]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by gamerboy82yt** [comment]
I can't login Microsoft account plz fix it

**Comment by khanhduytran0** [comment]
@gamerboy82yt plz **fill the template**!

**Comment by khanhduytran0** [comment]
@gamerboy82yt plz reply!

**Comment by gamerboy82yt** [comment]
I'm here i need to login my Microsoft account but error

**Comment by khanhduytran0** [comment]
So please copy that error. Errors are not same you know.

**Comment by gamerboy82yt** [comment]
java.lang.RuntimeException: Can't login a demo account!

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request
URI",
  "developerMessage" : "The server has not found anything matching the
request URI"
}
 at
net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:312)
 at
net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:276)
 at
net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:208)
 at
net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
 at
net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
 at
net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
 at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
 at
net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
 at
net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
 at android.os.AsyncTask$2.call(AsyncTask.java:333)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
 at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)

**Comment by khanhduytran0** [comment]
Have you bought Minecraft Java on it? :eyes:

**Comment by gamerboy82yt** [comment]
No, I haven't.

**Comment by gamerboy82yt** [comment]
But the old java launcher can connect to any server

**Comment by khanhduytran0** [comment]
@gamerboy82yt nah, Microsoft acc doesn’t give you free premium account

**Comment by gamerboy82yt** [comment]
How I'm i get online account?
