### ISSUE TITLE
1.12.2 not functional.

### ISSUE THREAD

**Issue by RealTriassic** [PojavLauncherTeam/PojavLauncher#131]
On PojavLauncher, 1.12.2 does not launch, i am using Android 8.0.0 without VMOS, but on MCinaBox, 1.12.2 does work, why don't you ask them how did they get it working, so you can fix it on PojavLauncher?

**Comment by khanhduytran0** [comment]
MCinaBox use built-in OpenJDK 8 Runtime, which support latest version, but PojavLauncher use Android Runtime. Minecraft 1.12 and above requires Java 8. So if I do something similar like MCinaBox (Get OpenJDK 8, build LWJGL 3), Minecraft 1.12 or above will work.

**Comment by RealTriassic** [comment]
> MCinaBox use built-in OpenJDK 8 Runtime, which support latest version, but PojavLauncher use Android Runtime. Minecraft 1.12 and above requires Java 8. So if I do something similar like MCinaBox (Get OpenJDK 8, build LWJGL 3), Minecraft 1.12 or above will work.

Then why don't you do that?

**Comment by khanhduytran0** [comment]
> Then why don't you do that?

So I'm planning to be in v3, will be different a bit, OpenJDK may run in an minimal Linux rootfs so Minecraft and any installer (OptiFine, Forge, LabyMod,...) can be launched in graphical mode.

**Comment by khanhduytran0** [comment]
Also will use X11 and some codes from XServer XSDL app from `pelya` to support setting min/max RAM usage.

**Comment by RealTriassic** [comment]
> > Then why don't you do that?
> 
> So I'm planning to be in v3, will be different a bit, OpenJDK may run in an minimal Linux rootfs so Minecraft and any installer (OptiFine, Forge, LabyMod,...) can be launched in graphical mode.

You said no planning, but hey that's cool!

**Comment by khanhduytran0** [comment]
> You said no planning, but hey that's cool!

But I said:
> So I'm ***planning*** to be in v3

**Comment by FranzelDamasco909** [comment]
I need OpenJDK 8 Runtime

**Comment by khanhduytran0** [comment]
> I need OpenJDK 8 Runtime

It may not OpenJDK 8, but I found an OpenJDK 10 work with graphical.

**Comment by FranzelDamasco909** [comment]
Ok mayba that

**Comment by FranzelDamasco909** [comment]
Ok maybe that

**Comment by khanhduytran0** [comment]
Openjdk will be released for test and in-app download right now.

**Comment by FranzelDamasco909** [comment]
Ok thanks maybe i can test playing 1.12 and up

**Comment by khanhduytran0** [comment]
V3 is not yet finished.

**Comment by RealTriassic** [comment]
> V3 is not yet finished.

Bad System Call :)

**Comment by khanhduytran0** [comment]
> Bad System Call :)

So use VMOS :)

**Comment by RealTriassic** [comment]
> > Bad System Call :)
> 
> So use VMOS :)

So your saying it won't get fixed?

**Comment by khanhduytran0** [comment]
> > > Bad System Call :)
> > 
> > So use VMOS :)
> 
> So your saying it won't get fixed?

Only enable root can fix.

**Comment by RealTriassic** [comment]
> > > > Bad System Call :)
> > > 
> > > 
> > > So use VMOS :)
> > 
> > 
> > So your saying it won't get fixed?
> 
> Only enable root can fix.

MCinaBox has it fully working though, if it didn't have a garbage user interface and it wasn't hard to use then I'd probably use that.

**Comment by khanhduytran0** [comment]
> MCinaBox has it fully working though, if it didn't have a garbage user interface 

If you don't know, it's UI based from `Hello! Minecraft Launcher`.

**Comment by FranzelDamasco909** [comment]
It's just because when i use VMOS, the storage keeps fulling

**Comment by khanhduytran0** [comment]
> It's just because when i use VMOS, the storage keeps fulling

May need some hacks to bypass Bad system call...
