### ISSUE TITLE
Forge 1.5.2

### ISSUE THREAD

**Issue by GilbertoKPL** [PojavLauncherTeam/PojavLauncher#1310]
add support for forge in version 1.5.2 as it is one of the best versions of several mods and a good optimization for weak devices.

**Comment by GilbertoKPL** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6416129/latestlog.txt)

**Comment by mchnjt** [comment]
> add support for forge in version 1.5.2 as it is one of the best versions of several mods and a good optimization for weak devices.

:trollface:

**Comment by oxota74** [comment]
i have the same problem

**Comment by oxota74** [comment]
i want to play on Hexxit client, but i can't

**Comment by khanhduytran0** [comment]
This is being tracked in #2468
