### ISSUE TITLE
[BUG] <Short description> idont know ts this a bug or something but 1.16.5,1. 16.3 is exiting to the home screen of launcher without any crash report or any notification my phone specs vivo y19 arch64 ram 3gb 3.3.1 version of pojav laucher , my android version is 11

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1312]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
@vineet12344 but **pls send latestlog.txt**

**Comment by khanhduytran0** [comment]
Also title is not a place to fill the template.

**Comment by khanhduytran0** [comment]
Ah so you are going to comment by changing the title?

**Comment by khanhduytran0** [comment]
@vineet12344 so are you going to reply?

**Comment by ghost** [comment]
I don't know how to do that I'm using GitHub for the first time  sorry for
trouble 🙏

**Comment by khanhduytran0** [comment]
So, please send latestlog.txt :eyes:

**Comment by ghost** [comment]
I don't know how to send it

**Comment by WesleyVanNeck** [comment]
Then we close as we can't fix it without a log
