### ISSUE TITLE
more stable fps and increase performance in osmesa build [F-REQ]

### ISSUE THREAD

**Issue by Dave1027** [PojavLauncherTeam/PojavLauncher#1313]
**Is your feature request related to a problem? Please describe.**
ans:is more like it, now that were using vulkan to deliver opengl 4.6, it got laggy like so much, i hope you guys the dev can stablelize the performance in tge osmesa build

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by artdeell** [comment]
Template is not filled. Also, you know, that's literaly why osmesa builds are not released, so wait

**Comment by khanhduytran0** [comment]
Also, you know, we are not Mesa3D developers, nor Zink. So just wait for their improvements.
