### ISSUE TITLE
[BUG] I found some weird black texture when the effects or when i hit a mob the textures became black and square texture minecraft version 1.12.2

### ISSUE THREAD

**Issue by Po-arch** [PojavLauncherTeam/PojavLauncher#1314]
i found some problem with minecraft 1.12.2 with or without mods the textures became black is there any solution im annoyed at these black and square textures

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]    you already know my platform
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by AutumnVN** [comment]
delete -Dorg.lwjgl.opengl.libname=libgl4es_115.so from your jvm argument, it is for 1.16+

**Comment by Po-arch** [comment]
thanks i was searching some solutions for this and someone replied

**Comment by ghost** [comment]
> delete -Dorg.lwjgl.opengl.libname=libgl4es_115.so from your jvm argument, it is for 1.16+

Ummm I didn't understand and that bug happened to me too
