### ISSUE TITLE
Nhà phát triển có thể làm cho 1 click=4 click

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1317]
Bởi vì mình muốn pvp lên 10LMB
Những kiểu MCinaBox
Video https://youtu.be/KhB5rvb0PKs

**Comment by Joakdnhio** [comment]
Vậy có thể thêm được ko?

**Comment by Joakdnhio** [comment]
Nhà phát triển có thể thêm được không

**Comment by axty666** [comment]
Có phải bạn muốn các nhà phát triển thêm tổ hợp mở màn, một hàm phản ứng bốn nhắp?Điều này có thể nghe như một chức năng lừa đảo. Bạn có thể thử trợ lý nút (sau cùng, chức năng mở màn đêm là một chức năng phím tắt khó thêm vào điện thoại di động). Trang web của nút Wizard: anjian.com

**Comment by Joakdnhio** [comment]
Không thiểu lắm ???

**Comment by Joakdnhio** [comment]
Vậy có cách nào pvp lên 10LMB không

**Comment by mchnjt** [comment]
wanna speedrun?

**Comment by Joakdnhio** [comment]
Có

**Comment by Mathias-Boulay** [comment]
![image](https://user-images.githubusercontent.com/24864674/131662936-9d307c99-6677-417a-96ba-3c50cd237f18.png)
