### ISSUE TITLE
[BUG] Failed to start 1.16.4

### ISSUE THREAD

**Issue by axty666** [PojavLauncherTeam/PojavLauncher#1318]
### Describe the bug
After downloading 1.16.4, click the start game button to display the white game screen (with control button), and then it will flash back to the main interface of the starter after a short time
I suspect that the wrong architecture may lead to the download of the wrong runtime (because it seems to be decompressing the runtime of arm32, while the architecture of my mobile phone is arm64)
![Screenshot_2021-05-01-16-10-50-67](https://user-images.githubusercontent.com/76648930/116777960-eac27080-aaa1-11eb-9c32-3f929f7ee281.png)
![Screenshot_2021-05-01-16-15-46-89](https://user-images.githubusercontent.com/76648930/116777972-fca41380-aaa1-11eb-970d-e0ed716d942c.png)

[logs:](
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6409279/latestlog.txt)
https://raw.githubusercontent.com/axty666/-/main/latestlog.txt)
### To Reproduce:
1. Start PojavLauncher
2. Select minecraft 1.16.4, click to start the game
3. Start downloading 1.16.4
4. After downloading, click to start the game
5. Pop up game screen (white screen)
6. Then flash back to the main interface of the starter
### Expected behavior:
I expected able to play 1.16.4 multiplayer server
### Screenshots or videos:
![Screenshot_2021-05-01-17-50-08-96](https://user-images.githubusercontent.com/76648930/116778662-d2eceb80-aaa5-11eb-8072-2e999c69773a.png)
![Screenshot_2021-05-01-17-50-21-10](https://user-images.githubusercontent.com/76648930/116778669-d8e2cc80-aaa5-11eb-8cef-bbd59538b067.png)
![Screenshot_2021-05-01-17-50-15-21](https://user-images.githubusercontent.com/76648930/116778673-dd0eea00-aaa5-11eb-949d-ea12d0d80d1a.png)

**Platform:**
 - Device Model:oppo a37m
 - CPU architecture:aarch64
 - Android Version:5.1
 - ColorOS Version:V3.0
 - PojavLauncher Version:version 3.3.1.1_rel_20210125

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
@axty666 no. Our app have architecture before start Java VM. Also android 5.x has known issue that will crash randomly.

**Comment by axty666** [comment]
> @ axty666没有 我们的应用在启动Java VM之前具有体系结构。此外，Android 5.x已知会随机崩溃的问题。

But why is it released from a file displayed as arm32（And what I encounter is not a random crash, but a constant crash)

**Comment by khanhduytran0** [comment]
> > @ axty666没有 我们的应用在启动Java VM之前具有体系结构。此外，Android 5.x已知会随机崩溃的问题。
> 
> 
> 
> But why is it released from a file displayed as arm32（And what I encounter is not a random crash, but a constant crash)

Again, you have outdated version. So update it :eyes:

**Comment by axty666** [comment]
> > > @ axty666没有我们的应用在启动Java VM之前具有体系结构。转换，Android 5.x已知会随机崩溃的问题。
> > 
> > 
> > 但是为什么要从显示为arm32的文件中释放它（我遇到的不是随机崩溃，而是持续崩溃）
> 
> 同样，您已经过时了。所以更新它
So where is the newer version（ Do I need to pack straight by myself)

**Comment by XIAYM-gh** [comment]
感觉是内存过小的问题吧
我感觉542MB不足以运行1.13以后的改版版本吧，毕竟mc是吃内存很多的（）

I think the memory you set is too low..
542MB maybe too low for running 1.16.x

**Comment by XIAYM-gh** [comment]
对了，最新构建在Actions里面,对了，一定要下载opengl_v3版本!!!其他的版本跑不起来1.13及以后的版本!!!

Also，the newest build is in the actions page.
Please download openGL_v3 version.
(OTHER VERSIONS CANNOT RUN 1.13+)

**Comment by XIAYM-gh** [comment]
啊这 对不起，脑子出了点问题，应该是v3_openjdk

Sorry, it's v3_openjdk not is opengl_v3

**Comment by SergueiKhadirov** [comment]
I can easily run 1.16.x optifine (some lags) with about 550Mb so i don't thinks its a ram problem

**Comment by SergueiKhadirov** [comment]
@axty666 try install pojav from playstore
