### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by MinecraftSuperFan** [PojavLauncherTeam/PojavLauncher#132]
![Screenshot_2020-04-25-12-24-29-79](https://user-images.githubusercontent.com/64300089/80272466-e081cf80-86f3-11ea-8292-2c4fdc811f9b.png)
I'm so stupid so how to fix this

**Comment by khanhduytran0** [comment]
Please copy errors to here.
(So what's you language? Maybe something like language issue, press `Sao chép` button at the bottom left to copy).

**Comment by MinecraftSuperFan** [comment]
Tiếng việt nó hiện lên r đơ 1 lúc r game thoát luôn ram thì vẫn còn ko bấm copy đc T-T

**Comment by khanhduytran0** [comment]
Máy chạy android mấy vậy?

**Comment by MinecraftSuperFan** [comment]
5.1 bạn ơi

**Comment by MinecraftSuperFan** [comment]
3g

**Comment by MinecraftSuperFan** [comment]
Ram

**Comment by khanhduytran0** [comment]
Android 5.1 không cài được OptiFine 1.8.9 trở lên đâu. Thử 1.7.10, 1.8, 1.8.8

**Comment by MinecraftSuperFan** [comment]
Oh okay

**Comment by monleak** [comment]
😂😂

**Comment by MinecraftSuperFan** [comment]
Ad làm sao fix lỗi vào game r bấm nút home r vào lại game thì màn hình đen mặc dù Gui vs mouse vẫn hiển thị vs chạy mượt v

**Comment by khanhduytran0** [comment]
> Ad làm sao fix lỗi vào game r bấm nút home r vào lại game thì màn hình đen mặc dù Gui vs mouse vẫn hiển thị vs chạy mượt v 

Cái đó do máy chứ không phải phần mềm, không fix được, trên android 9 thoát ra vào lại không bị vậy.

**Comment by khanhduytran0** [comment]
> Android 5.1 không cài được OptiFine 1.8.9 trở lên đâu.
