### ISSUE TITLE
[BUG] It's almost useless to stay logged in

### ISSUE THREAD

**Issue by axty666** [PojavLauncherTeam/PojavLauncher#1320]
### Describe the bug
When I check keep login status and re open the launcher again, when I enter the game ID with the original name, I will be prompted that the user name already exists, but there is no game ID with the original name in the switching account
(I'm quite sure it can be reproduced, so I didn't upload the log.)
### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Log in to an offline account (for example, axxx)(Remember to check the keep login option)
3. Restart pojavlauncher
4. Enter the name of the game with the option of keep login checked in the pop-up window (for example, enter axxx mentioned above)
5. Prompt user name already exists
6. Check the switch account page and find that there is no game nickname (such as axxx)

### Expected behavior:
I expected After checking the keep login option, you don't have to re-enter the game account with that option checked

### Screenshots or videos:
It's too expensive to forget the screenshots and reproduce them to get back to normal

**Platform:**
 - Device Model [oppo a37m 2/16]
 - CPU architecture [aarch64] 
 - Android Version [5.1]
 - PojavLauncher Version [version 3.3.1.1_rel_20210125]

<details> <summary><b>Solutions (for now)</b></summary>
<br>
<pre>
Refitting pojavlauncher
</pre>
</details>

**Comment by khanhduytran0** [comment]
And so why don't you check "select account" before attempt to duplicate account?

**Comment by khanhduytran0** [comment]
> It's too expensive to forget the screenshots and reproduce them to get back to normal

nah. Just take a video instead of a bunch of screenshots.

**Comment by axty666** [comment]
> > 忘记截图并复制它们以使其恢复正常状态太昂贵了
> 
> 不。只是拍摄视频而不是一堆屏幕截图。



https://user-images.githubusercontent.com/76648930/116781728-67ac1500-aab7-11eb-8d2d-1c98bcaeb3db.mp4

**Comment by axty666** [comment]
> 那么，为什么在尝试复制帐户之前不选中“选择帐户”呢？

Because this is a normal offline account, after checking this option, it will show that the user name already exists

**Comment by khanhduytran0** [comment]
It looks like that select account dialog has incorrectly sized.

**Comment by khanhduytran0** [comment]
> ~~update to latest version on google play~~

**Comment by khanhduytran0** [comment]
> update to latest build on GitHub (v3_openjdk)

**Comment by khanhduytran0** [comment]
@ãty666 reply?

**Comment by khanhduytran0** [comment]
@axty666 reply?

**Comment by axty666** [comment]
> @axty666 reply?

我十分抱歉以至于现在才看见您的回复，十分感谢您的支持，祝您生活愉快
I'm so sorry that I just saw your reply now. Thank you very much for your support. I wish you a happy life
