### ISSUE TITLE
[BUG] <Can not play>

### ISSUE THREAD

**Issue by CT-52** [PojavLauncherTeam/PojavLauncher#1322]
![11A0402D-8E77-4D74-88FB-E83A16F19F04](https://user-images.githubusercontent.com/83521689/116798429-47696e00-ab2a-11eb-9dfe-68ff3200ed65.png)

My English is not good. Sorry.

I tapped the ''Play'' button, but the Launcher doesn't load any more.
Please tell me how to fix it 🙇🏼‍♂️

Device：iPad Pro 4Gen
iOS：14.2
Jailbreak tool：unc0ver 6.1.2
PojavLauncher version：1.2
Login：Microsoft

**Comment by khanhduytran0** [comment]
Wrong repository

**Comment by khanhduytran0** [comment]
Please go to https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues

**Comment by CT-52** [comment]
Oh, I'm sorry. Thank you.
