### ISSUE TITLE
Lỗi không chơi được forge

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1324]
Video https://youtu.be/5KgVSetX0sg

**Comment by Joakdnhio** [comment]
Mong nhà phát triển giúp đỡ

**Comment by Joakdnhio** [comment]
File latestlog.txt https://www.mediafire.com/download/abkh5fuh6in2x1u

**Comment by khanhduytran0** [comment]
Mod bị thiếu các thành phần :eyes:

**Comment by Joakdnhio** [comment]
![Screenshot_20210503-170942.png](https://user-images.githubusercontent.com/82981880/116864661-694e1800-ac32-11eb-8487-ccf5a39cb2f8.png)

**Comment by Joakdnhio** [comment]
![Screenshot_20210503-125937.png](https://user-images.githubusercontent.com/82981880/116864706-7d921500-ac32-11eb-8d2d-4b5467164de8.png)

**Comment by Joakdnhio** [comment]
Tải được Minecraft rồi

**Comment by Joakdnhio** [comment]
Mình xoá forge đi rồi cài lại thì được
