### ISSUE TITLE
Can my device run it? It's realme 7

### ISSUE THREAD

**Issue by shraman10000** [PojavLauncherTeam/PojavLauncher#1325]
My device is Realme 7 and I am trying to run Zink version from last 2 days but it's not playing at all.
My game opens, I downlaods 1.16.5 try to run with suggested settings , controls appears with black screen, and it sucks .
Or else it sends me crash report I can even use optifine . Please help me out 
I want to try shaders pls.

**Comment by Joakdnhio** [comment]
Send the pictures to see Come on

**Comment by Joakdnhio** [comment]
Or send a video to watch

**Comment by Joakdnhio** [comment]
Your device can run

**Comment by khanhduytran0** [comment]
@shraman10000 and you didn't fill the template
