### ISSUE TITLE
Can you add crafting recipe to the crafting table ?

### ISSUE THREAD

**Issue by zezayne** [PojavLauncherTeam/PojavLauncher#1330]
I am loving the app I have some problems with it . I mainly play on 1.8.9 but I cannot craft like I cannot split the blocks . So I thought there was the crafting recipe bar so I can just press to craft what I want but there wasn't . Is this a bug or a feature that haven't been done ? Hope you can consider develop / fix this problem @PojavLauncherTeam . Thanks .

**Comment by aren215** [comment]
If you wanna split the blocks hold sec while dragging the block or item

**Comment by zezayne** [comment]
Ok 
That solves the problem 
Thanks @aren215
