### ISSUE TITLE
[BUG] <failed to start 1.14 >

### ISSUE THREAD

**Issue by Gpe20190** [PojavLauncherTeam/PojavLauncher#1333]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
![Screenshot_2021-05-04-23-18-37-617_net kdt pojavlaunch](https://user-images.githubusercontent.com/83686579/117096718-87e60900-ad2f-11eb-9de8-0a77b8238a52.jpg)

![Screenshot_2021-05-04-23-18-44-175_net kdt pojavlaunch](https://user-images.githubusercontent.com/83686579/117096753-97655200-ad2f-11eb-8a75-78b89c39d322.jpg)

![Screenshot_2021-05-04-23-21-13-138_net kdt pojavlaunch](https://user-images.githubusercontent.com/83686579/117096765-9d5b3300-ad2f-11eb-9c12-e3229343aaab.jpg)

![Screenshot_2021-05-04-23-21-39-227_com cpuid cpu_z](https://user-images.githubusercontent.com/83686579/117096773-a0eeba00-ad2f-11eb-82f8-c97bc8675fae.jpg)

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
fill the template amd give latestlog.txt
