### ISSUE TITLE
[BUG] Crash on Samsung Note 10+ on all minecraft versions

### ISSUE THREAD

**Issue by pablodz** [PojavLauncherTeam/PojavLauncher#1335]
<details> <summary><b>Read before submit</b></summary>
<br>
[X] Make sure there was not duplicated issues.<br>
[X] Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

App crashes after a while and restarts (video)

**Add a log file if you want to see your bug fixed !**

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6430206/latestlog.txt)

### To Reproduce:

(Video)

### Screenshots or videos:

*Upload here screenshots or videos of the buggy behavior, if possible.*

https://user-images.githubusercontent.com/28235457/117208539-db516900-adba-11eb-94fd-e07d813ae7f4.mp4

**Platform:**
 - Device Model: Samsung Note 10+
 - CPU architecture: aarch64
 - Android Version: 11
 - PojavLauncher Version: Latest stable release

**Comment by pablodz** [comment]
Could be this part of `latestlog.txt`?

```
I/jrelog  (11650): Calling JLI_Launch
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.

```

**Comment by YurielMGV2** [comment]
The same thing is happening on my Samsung Galaxy S20 FE 5G, has anyone managed to fix this?

**Comment by khanhduytran0** [comment]
> Could be this part of `latestlog.txt`?
> 
> 
> 
> ```
> 
> I/jrelog  (11650): Calling JLI_Launch
> 
> [LWJGL] Failed to load a library. Possible solutions:
> 
> 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
> 
> 	b) Add the JAR that contains the shared library to the classpath.
> 
> 
> 
> ```

That's libjemalloc which is optional.

**Comment by khanhduytran0** [comment]
Also, does "latest stable release" mean latest play store release or somewhere?

**Comment by pablodz** [comment]
> Also, does "latest stable release" mean latest play store release or somewhere?

v3.3.1.1 hosted here on Github

**Comment by khanhduytran0** [comment]
v3.3.1.1 on releases tab is outdated.

**Comment by pablodz** [comment]
> v3.3.1.1 on releases tab is outdated.

New releases are uploaded directly to GPlay?
Where can I find the releases? on Github actions builds of each commit (which branch)?

**Comment by WesleyVanNeck** [comment]
https://play.google.com/store/apps/details?id=net.kdt.pojavlaunch
