### ISSUE TITLE
Make an option prior to disabling OpenGL ES Render

### ISSUE THREAD

**Issue by mchnjt** [PojavLauncherTeam/PojavLauncher#1339]
Yep, it's just annoying when you can't see an option for turning off OpenGL ES render.

![Screenshot_20210506-173959~2.png](https://user-images.githubusercontent.com/83752061/117277760-b92b1a00-ae92-11eb-9272-a04a72fa23fa.png)

**Comment by ENDERMANYK** [comment]
So you want your game empty and doesn't render?

**Comment by khanhduytran0** [comment]
@rscDoesMoreTrolling then you gonna create another issue for game crashing?

**Comment by khanhduytran0** [comment]
No renderer = no game

**Comment by mchnjt** [comment]
Oh

ok

**Comment by SavagePy10** [comment]
This is so funny lol

**Comment by Migol10** [comment]
What about OpenGL ES 1? xd

**Comment by khanhduytran0** [comment]
> What about OpenGL ES 1? xd

So you want drop support for shaders and Minecraft 1.15+? :trollface:
