### ISSUE TITLE
Không click được

### ISSUE THREAD

**Issue by MinecraftSuperFan** [PojavLauncherTeam/PojavLauncher#1341]
![Screenshot_2021-05-06-18-24-45-08](https://user-images.githubusercontent.com/64300089/117291476-43767c80-ae99-11eb-88b9-94968f177f9a.jpg)
Mình không thể click được dù bật hay tắt chuột
Phiên bản 1.16 
Oppo a15s

**Comment by khanhduytran0** [comment]
~~bạn không thể gửi latestlog.txt và điền vào mẫu~~
