### ISSUE TITLE
Can't click

### ISSUE THREAD

**Issue by MinecraftSuperFan** [PojavLauncherTeam/PojavLauncher#1342]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Can't click
**Add a log file if you want to see your bug fixed !**

> 

>[https://drive.google.com/file/d/1-9SpjPL3voUBkyK7v3lBkpXUPpSkATzk/view?usp=drivesdk]() 

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_2021-05-06-18-24-45-08](https://user-images.githubusercontent.com/64300089/117294678-1cba4500-ae9d-11eb-91d7-aea45822455a.jpg)

**Platform:**
 - Device Model oppo a15s
 - CPU architecture me helio p35
 - Android Version 10
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by AgaricaGamer** [comment]
1• > Please Fill The Log Correctly Next Time
2• > It Is A Bug Many Users Are Experiencing I Have Experienced It Too Sometimes When You Try To Use Button When The Screen Is Black And Minecraft Launches It. But If You restart The Application It May Fix

**Comment by khanhduytran0** [comment]
@MinecraftSuperFan Bật fullscreen lên và đừng skip tải tài nguyên
