### ISSUE TITLE
[BUG] <1.13 won't launch.>

### ISSUE THREAD

**Issue by mchnjt** [PojavLauncherTeam/PojavLauncher#1343]
I just recently downloaded 1.13, and it just crashed.

Latestlog and latestcrash

https://www.mediafire.com/file/mivaq7i54wadmfh/fix_my_prob_pls.zip/file

pls fix I just wanna swim in lava in 2p2j

**Comment by khanhduytran0** [comment]
Please delete 1.13, enable libraries checker and try again.

**Comment by mchnjt** [comment]
ok thx
