### ISSUE TITLE
Having issue in Use of java shaders 

### ISSUE THREAD

**Issue by Nishandey12** [PojavLauncherTeam/PojavLauncher#1346]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Sir,please help me when I choice and Start game then my game exit and show pojavlauncher run time out plz sir help me all youtubers run all java shader in ther mobile but i cannot run a single shader my phone is 8gb ram abd 128gb rom and 665snapdragon vivo Y50 plz sir help me plz sir or tell me how to run all java shader in pojavlauncher plz help me sir

**Comment by WesleyVanNeck** [comment]
Its not a pc it cant run all shaders
