### ISSUE TITLE
[BUG] <Don't working mod "Sodium" >

### ISSUE THREAD

**Issue by MikSiDe** [PojavLauncherTeam/PojavLauncher#1348]
My device:
Huawei P40 lite E
aarch 64 bit
Android 10

Bug in mod Sodium
Version minecraft 1.16.4 - 1.16.5
Help!

**Comment by 2894638479** [comment]
me too

**Comment by 2894638479** [comment]
HUAWEI nova5i
64bit
Android 10
sodium 1.16.5

**Comment by khanhduytran0** [comment]
bruhs disable Compact vertex format and Fog occlusion
