### ISSUE TITLE
error Samsung  j2 primera 

### ISSUE THREAD

**Issue by cibusaxter** [PojavLauncherTeam/PojavLauncher#135]
Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar", zip file "/storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/versions/1.9/1.9.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by cibusaxter** [comment]
That its

**Comment by khanhduytran0** [comment]
Try other versions

**Comment by FranzelDamasco909** [comment]
@khanhduytran0 , can you tell me how to use the source.zip

**Comment by FranzelDamasco909** [comment]
and what MB is the source.zip

**Comment by khanhduytran0** [comment]
> @khanhduytran0 , can you tell me how to use the source.zip

Import to Android studio and build.

**Comment by FranzelDamasco909** [comment]
Can i use the other apps like Apk Editor on android? because i don't have any laptop

**Comment by khanhduytran0** [comment]
Apk editor does not build apk. Use AIDE 
.

**Comment by khanhduytran0** [comment]
@FranzelDamasco909 https://github.com/khanhduytran0/PojavLauncher/releases/download/v2.5.0-preview1/PojavLauncher-2.5.0-20200427-preview1.apk

**Comment by cibusaxter** [comment]
I continue with problem with other version

**Comment by khanhduytran0** [comment]
> I continue with problem with other version

Try to run in VMOS.

**Comment by khanhduytran0** [comment]
> > I continue with problem with other version
> 
> Try to run in VMOS.

@cibusaxter please reply
