### ISSUE TITLE
Mouse Capture for Android 8.0+

### ISSUE THREAD

**Issue by Codyjames34526** [PojavLauncherTeam/PojavLauncher#1351]
Any chance you guys could implement the mouse capture supported by Android versions above Oreo? This application is perfect with keyboard and mouse except for this one nitpick. Thanks.

**Comment by mchnjt** [comment]
android 8

why?

**Comment by Codyjames34526** [comment]
> android 8
> 
> why?

Mouse capture isn't supported by Android versions below Oreo (8.0)

**Comment by khanhduytran0** [comment]
already added for a long time

**Comment by Codyjames34526** [comment]
It doesn't seem to work for me, are there specific system requirements? I'm using a Galaxy Tab S7+ on Android 11 with the Book Cover Keyboard. Could the problem be that I'm using the included trackpad instead of a USB mouse? Thanks.

**Comment by khanhduytran0** [comment]
Android mouse capture does not support trackpad.

**Comment by Codyjames34526** [comment]
> Android mouse capture does not support trackpad.

Thank you so much, I'll try it with my mouse and see if it works.

**Comment by Codyjames34526** [comment]
Works perfectly, wasn't aware that the touchpad wouldn't work. Thank you.
