### ISSUE TITLE
Skin Related Issue

### ISSUE THREAD

**Issue by SMOKIEisBack** [PojavLauncherTeam/PojavLauncher#1352]
Please add an option in Pojavlauncher in that we can change skin It will be really great if you add this feature in next update:-)

**Comment by mchnjt** [comment]
then why not officially get a Java acc bruh

**Comment by khanhduytran0** [comment]
@SMOKIEisBack Please buy Minecraft Java then change skin.

**Comment by SMOKIEisBack** [comment]
Why don't you understand that everyone can't afford a acc.In tlauncher we can change skin without buying a acc so why not in Pojavlauncher?It will be great option

**Comment by CriticalRange** [comment]
> Why don't you understand that everyone can't afford a acc.In tlauncher we can change skin without buying a acc so why not in Pojavlauncher?It will be great option

Then use offline mod and use mods to change your skin if you can't buy Minecraft.

**Comment by SMOKIEisBack** [comment]
Ok

**Comment by SMOKIEisBack** [comment]
Can you suggest me one?
