### ISSUE TITLE
[BUG] 不兼容神秘时代6

### ISSUE THREAD

**Issue by EikoocS** [PojavLauncherTeam/PojavLauncher#1354]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

[crash-2021-05-10_11.11.51-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6451602/crash-2021-05-10_11.11.51-client.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6451603/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

装载神秘时代6无法的游戏正常加载
移除后可以加载
电脑Java无此问题

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Android Version 10
 - PojavLauncher Version version 3.3.1.1_rel_20210206 

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
希望可以修复一下，毕竟也算比较经典的模组，不能加载比较难受
第一次提交Issue，如有问题请告知
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
English pls
