### ISSUE TITLE
Add authlib-injector[F-REQ]

### ISSUE THREAD

**Issue by zhangjing-GitHub-Code** [PojavLauncherTeam/PojavLauncher#1355]
## Can you add `authlib-injector` ?
From `https://blessing.netlify.app/`:
>This plug-in is only based on the original user system of the Blessing Skin skin site, and has fully implemented a set of APIs that comply with the Yggdrasil API specification (this set of specifications is the official Mojang API for Minecraft genuine login authentication), and we must use authlib- injector (opens new window)This program replaces the "Mojang genuine login API address" in the game with the "Yggdrasil API address provided by the skin station" at runtime to realize an external login system.

From mcbbs.net(translate by bing):

>It is well known that if the MC server side does not turn on theonline-mode, then it is not possible to authenticate the player (anyone can enter the server in any capacity), but not all service owners are willing to turn on the online-mode (if turned on, your player must be genuine users), which has spawned a number of non-Mojng official login systems.

If add this, we can login like a genuine player ~~without buying minecraft~~ and have custom skins. In a short word, it's useful so I want add this feature.
说了这么多其实就是想加一个authlib-injector外置登录。

**Comment by khanhduytran0** [comment]
Have you searched the issue list before make this?

**Comment by khanhduytran0** [comment]
Duplicate of #824
