### ISSUE TITLE
[BUG] Crash on Android 11

### ISSUE THREAD

**Issue by rpu5** [PojavLauncherTeam/PojavLauncher#1358]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
The game crashes immediately after I launch Minecraft (video).

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6446198/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher;
2. Login in or start an offline account;
3. Launch Minecraft of any versions. 

### Expected behavior:
The app should have opened Minecraft. 

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

https://user-images.githubusercontent.com/81773752/117546899-6d64a600-b035-11eb-9b73-90db8b4bdc76.mp4

**Platform:**
 - Device Model: ROG Phone 5;
 - CPU architecture: Aarch64;
 - Android Version: Android 11;
 - PojavLauncher Version: Latest Release for Android 11 taken from GitHub.

**Comment by pablodz** [comment]
Seeing the latestlog.txt file we can found that there is a fatal error on Java Rountime

```

I/LIBGL   (29629): glX Will try to recycle EGL Surface
I/LIBGL   (29629): Current folder is:/
I/jrelog  (29629): dlopen /data/app/~~m4-x1WkGCbo0MNnHKk4-eA==/net.kdt.pojavlaunch-27huSKWYQwQ3wz5P3ZFXqw==/lib/arm64/libgl4es_114.so success
I/jrelog  (29629): Done processing args
I/jrelog  (29629): Found JLI lib
I/jrelog  (29629): Calling JLI_Launch
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:237), pid=29629, tid=0x000000748eff6cc0
#  guarantee(val < (1U << nbits)) failed: Field too big for insn
#
# JRE version:  (8.0) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.71-b00 mixed mode linux-aarch64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/hs_err_pid29629.log
fdsan: attempted to close file descriptor 112, expected to be unowned, actually owned by FILE* 0x7671f5ee20

```

**Comment by HaznRe** [comment]
me too always force close in Android 11

**Comment by WesleyVanNeck** [comment]
Is not a android 11 issues use the one of playstore

**Comment by mchnjt** [comment]
> me too always force close in Android 11

when there's nothing popping out a text like that in my dad's phone (android 11)

**Comment by SergueiKhadirov** [comment]
try uninstall jvm in settings

**Comment by lapius** [comment]
Same phone, a bit different problem. Adding log, I got app restart few seconds after being in game. 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6733128/latestlog.txt)
Like this is the end of log file:
`2021-06-29 11:29:23 [SERVER] [INFO] Starting integrated minecraft server version 1.6.1
2021-06-29 11:29:23 [SERVER] [INFO] Generating keypair
2021-06-29 11:29:23 [SERVER] [INFO] Preparing start region for level 0
2021-06-29 11:29:24 [SERVER] [INFO] Preparing spawn area: 14%
2021-06-29 11:29:25 [SERVER] [INFO] Preparing spawn area: 38%
2021-06-29 11:29:26 [SERVER] [INFO] Preparing spawn area: 64%
2021-06-29 11:29:27 [SERVER] [INFO] Preparing spawn area: 85%
2021-06-29 11:29:28 [SERVER] [INFO] aad[/127.0.0.1:0] logged in with entity id 159 at (-81.5, 64.0, 252.5)
2021-06-29 11:29:28 [SERVER] [INFO] aad joined the game
Setting up custom skins
Grab: true
[0629/142933.567921:ERROR:elf_dynamic_array_reader.h(61)] tag not found`

Seems like

**Comment by Mathias-Boulay** [comment]
android is supported on the latest crocus gplay update.
closing.

**Comment by Efedogan987** [comment]
Benim telefonum android 11 ve mod yükledim hata oluştu hatayı düzeltin lütfen
