### ISSUE TITLE
[BUG] Incompatible with Thaumcraft 6

### ISSUE THREAD

**Issue by EikoocS** [PojavLauncherTeam/PojavLauncher#1359]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

[crash-2021-05-10_11.11.51-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6458537/crash-2021-05-10_11.11.51-client.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6458538/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Add thaumcraft 6 in MODS folder

### Expected behavior:
I expected ....Software crash

### Screenshots or videos:
Crash directly, so there is no valid screenshot

**Platform:**
 - Device Model vivo Y50
 - CPU architecture 64-bit
 - Android Version 10
 - PojavLauncher Version version 3.3.1.1_rel_20210206

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
After removing thaumcraft 6, it can start normally
Thaumcraft 6 can be started normally in Java version

*Content from the network translation, because my English level is bad
</pre>
</details>

**Comment by nabiloi** [comment]
"Optifine is installed. This is NOT supported. " in the crash report

**Comment by EikoocS** [comment]
> 崩溃报告中的“已安装optifine。不支持。”

but when I remove Thaumcraft 6 ， I can start game as usual
![Screenshot_20210511_202554](https://user-images.githubusercontent.com/80829508/117814821-65a43c00-b297-11eb-91a3-4c5175a988c6.jpg)

**Comment by bawansaman313** [comment]
bawan

**Comment by bawansaman313** [comment]
Hi

**Comment by mchnjt** [comment]
> Hi 

this ain't discord

**Comment by khanhduytran0** [comment]
@Yummy-Cookie-S bruh it means that "thaumcraft" is conflicts with optifine

**Comment by EikoocS** [comment]
> @Yummy-Cookie-S bruh it means that "thaumcraft" is conflicts with optifine

But I can start thaumcraft with optifine on the computer
I hope I can start thaumcraft with optifine on the pojav too.
