### ISSUE TITLE
Mouse not shake

### ISSUE THREAD

**Issue by daviMINE977** [PojavLauncherTeam/PojavLauncher#1365]

**Comment by mchnjt** [comment]
(where's the description lmoa)

If i'm right, did you set the mouse speed to 0%, or you forgot to tap the mouse tab

(Normal mouse when opening first time[MOUSE]
Mouse when activated [MOUSE:ON]
mouse when deactivated [MOUSE:OFF])

**Comment by daviMINE977** [comment]
Mouse 100% speed my mobile j5 prime 8.0

Em Qua, 12 de mai de 2021 07:09, LegacyGamerHD ***@***.***>
escreveu:
