### ISSUE TITLE
Phone overheating quickly when playing. 

### ISSUE THREAD

**Issue by Octol1ng** [PojavLauncherTeam/PojavLauncher#1366]
Everything is said in the name.
Phone Details:
Honor 10i
EMUI version: 10
Android version: 10
Model: HRY-LX1T
Pojavlauncher (downloaded from Google Play) version: 3.3.1.1_rel_20210321
Hopefully you will fix overheating.

**Comment by WesleyVanNeck** [comment]
Its a PC game what do you expect
