### ISSUE TITLE
[BUG] <Can't play infdev and below versions>

### ISSUE THREAD

**Issue by only-surviv-cre-cant-need-save-worlds** [PojavLauncherTeam/PojavLauncher#1367]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Can't play the infdev and below versions, i can  only play infdev and below versions in some seconds, nothing in log tab and crash tab, when i play infdev and below versions, after some seconds, screen change to launcher menu or login menu, but i can play other versions.

**Add a log file if you want to see your bug fixed ! 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6471022/latestlog.txt)
**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
What that mean? 

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
(Not enough memory to record a video or capture a screenshot)

**Platform:**
 - Device Model [e.g. Samsung Galaxy J2 Prime]
 - CPU architecture [e.g. arm32] 
 - Android Version [e.g. 6.0.1]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
Bonus: i think infdev and below versions cant save world file

**Comment by mchnjt** [comment]
uhh what really is your problem sir

**Comment by only-surviv-cre-cant-need-save-worlds** [comment]
I can only play versions that can save worlds

**Comment by mchnjt** [comment]
Hmmm

**Comment by mchnjt** [comment]
try to improve your ram allocation I guess

**Comment by mchnjt** [comment]
oh wait no really

**Comment by mchnjt** [comment]
> I can only play versions that can save worlds

Don't play versions below aX.X.X

**Comment by WesleyVanNeck** [comment]
then dont play those versions

**Comment by only-surviv-cre-cant-need-save-worlds** [comment]
But i want play sime classic versions, what i can do to play older versions?
