### ISSUE TITLE
[BUG] <1.12.2 forge crashes after a while>

### ISSUE THREAD

**Issue by Nanify69** [PojavLauncherTeam/PojavLauncher#1368]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

When I was playing in my hardcore world for a while the launcher crashes randomly yet no crash were reported.

**Add a log file if you want to see your bug fixed !**

https://pastebin.com/Hhfj7V3M

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start 1.12.2
2. Create a world
3. Now start playing
4. After a while the launcher crashes randomly

### Expected behavior:
I expected to play peacefully without this fricking strange bug....

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Samsung j4+ 2/16]
 - CPU architecture [e.g. aarch32] 
 - Android Version [e.g. 9]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by rscAvePlex** [comment]
ram allocation maybe?

**Comment by Nanify69** [comment]
I did allocate some ram it didnt work...

**Comment by rscAvePlex** [comment]
hmm

what could be wrong

**Comment by WesleyVanNeck** [comment]
to weak device you need minuim phone 3 gb or more

**Comment by khanhduytran0** [comment]
@Nanify69 disable connected texture

**Comment by Nanify69** [comment]
Still crashing imma just switch to mcinabox :(
