### ISSUE TITLE
[BUG] zink test not working on my phone

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#1369]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I want to play minecraft 1.8.9 with zink but it crashed.
**Add a log file if you want to see your bug fixed !**

--------- beggining with launcher debug
Info: Launcher version: 3.3.1.1_rel_20210512
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms750m -Xmx750m -Dorg.lwjgl.opengl.libname=libOSMesa_8.so"
Headless version detected! (20151203)
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.

[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.

[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.

[05:32:30] [Client thread/INFO]: Setting user: PlayerLancE
[05:32:31] [Client thread/INFO]: (Session ID is token:0:00000000-0000-0000-0000-000000000000)
[05:32:40] [Client thread/INFO]: LWJGL Version: 3.2.3 SNAPSHOT
OSMDroid: using built-in libOSMesa_8.so
OSMDroid: unable to load: dlopen failed: library "libOSMesa_8.so" wasn't loaded and RTLD_NOLOAD prevented it
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/13/21 5:32 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
Caused by: java.lang.IllegalStateException: Unable to initialize GLFW
	at org.lwjgl.Sys.initialize(Sys.java:27)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:73)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-8.1.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 698999568 bytes (666 MB) / 756023296 bytes (721 MB) up to 756023296 bytes (721 MB)
	JVM Flags: 3 total; -Xms751M -Xmx751M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: ~~ERROR~~ UnsatisfiedLinkError: Failed to dynamically load library: /data/app/net.kdt.pojavlaunch-YWV-I1GrTDqiqSIzhXX0Pw==/lib/arm64/libOSMesa_8.so(error = dlopen failed: cannot locate symbol "getrandom" referenced by "/data/app/net.kdt.pojavlaunch-YWV-I1GrTDqiqSIzhXX0Pw==/lib/arm64/libOSMesa_8.so"...)
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	
Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/games/PojavLauncher/.minecraft/crash-reports/crash-2021-05-13_05.32.40-client.txt

[05:32:40] [Client Shutdown Thread/INFO]: Stopping server

**Crash Report↓**

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/13/21 5:32 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
Caused by: java.lang.IllegalStateException: Unable to initialize GLFW
	at org.lwjgl.Sys.initialize(Sys.java:27)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:73)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-8.1.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 698999568 bytes (666 MB) / 756023296 bytes (721 MB) up to 756023296 bytes (721 MB)
	JVM Flags: 3 total; -Xms751M -Xmx751M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: ~~ERROR~~ UnsatisfiedLinkError: Failed to dynamically load library: /data/app/net.kdt.pojavlaunch-YWV-I1GrTDqiqSIzhXX0Pw==/lib/arm64/libOSMesa_8.so(error = dlopen failed: cannot locate symbol "getrandom" referenced by "/data/app/net.kdt.pojavlaunch-YWV-I1GrTDqiqSIzhXX0Pw==/lib/arm64/libOSMesa_8.so"...)
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Thats all**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Play 1.8.9
### Expected behavior:
I expected it will work.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model CPH1853 (OPPO A12e)
 - CPU architecture arm64/aarch64
 - Android Version 8
 - PojavLauncher Version 3.3.1.1_rel_20210512

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
I want to play PC Shaders on 1.8.9 but it did not work on my phone.
</pre>
</details>

**Comment by LANCECRAFT1104** [comment]
Time to buy a new phone???

**Comment by mchnjt** [comment]
it is too **long**

**Comment by WesleyVanNeck** [comment]
dont use zink
