### ISSUE TITLE
Scroll in Minecraft 1.11.2 still malfunctioning

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#137]
I tested the scroll in Minecraft 1.11.2 and it still not working

**Comment by khanhduytran0** [comment]
Try Hold SEC button, long click on scrollbar and move.

**Comment by FranzelDamasco909** [comment]
Still not functioning

**Comment by khanhduytran0** [comment]
Or try repeat click SEC and hold scrollbar.

Also need try with virtual mouse!

**Comment by FranzelDamasco909** [comment]
I tried it with virtual mouse but it still not

**Comment by khanhduytran0** [comment]
> Or try repeat click SEC and hold scrollbar.

**Comment by FranzelDamasco909** [comment]
i did anything but stills not working

**Comment by khanhduytran0** [comment]
Or try v3. Reopen if still
