### ISSUE TITLE
Werid xray on note 8 

### ISSUE THREAD

**Issue by xenoblade3** [PojavLauncherTeam/PojavLauncher#1371]
The launcher works well outside of the fact that some blocks are see through at a certain distance and some areas of the ground just don't appear until you're close to them 
![Screenshot_20210513-221602_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/74432409/118216353-fa926b00-b438-11eb-94b9-9c602441e8ba.jpg)
![Screenshot_20210513-221540_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/74432409/118216355-fb2b0180-b438-11eb-8e6a-b1e1380b3611.jpg)
![Screenshot_20210513-221629_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/74432409/118216359-fbc39800-b438-11eb-91d6-b8276766e79a.jpg)
![Screenshot_20210513-221624_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/74432409/118216362-fbc39800-b438-11eb-885c-b9e669f856bc.jpg)

**Comment by WesleyVanNeck** [comment]
1 fill the template second enable full screen

**Comment by rscAvePlex** [comment]
troll science (you need help edition)

1. Send latestlog.txt
2. Send latestlog.txt
3. Wait lmao
4. ok
