### ISSUE TITLE
Minecraft cứ bị văng liên tục

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1372]
Mình chơi 1.16.5 sau 1đên 2 phút thì bị văng game 
Mong nhà phát triển giúp đỡ 😘😘😘

**Comment by Joakdnhio** [comment]
Vậy có cách nào để khắc phục không

**Comment by Joakdnhio** [comment]
Cài optifine rồi vẫn bị văng

**Comment by khanhduytran0** [comment]
1. Cái template vẫn bị >>RIP<<.
2. Chỉ có mỗi "thông tin" là game bị văng, ai biết tại sao? 1000 người nói y chang vậy mà không cung cấp thêm bất cứ thứ gì hết, ai biết ở đâu?
