### ISSUE TITLE
[BUG] <can't open 1.16+ games>

### ISSUE THREAD

**Issue by Wenz-jam** [PojavLauncherTeam/PojavLauncher#1375]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
1.16+ only
when I try to open 1.16+ , it reports an error and exits
![Screenshot_20210515_090745_net kdt pojavlaunch](https://user-images.githubusercontent.com/81887980/118343810-ad5be980-b55d-11eb-9ea9-39802866c00c.jpg)
![Screenshot_20210515_090654_net kdt pojavlaunch](https://user-images.githubusercontent.com/81887980/118343812-b0ef7080-b55d-11eb-9504-018637fdd69c.jpg)

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
Fill the template
