### ISSUE TITLE
[Question] client side support

### ISSUE THREAD

**Issue by issuereporter292** [PojavLauncherTeam/PojavLauncher#138]
Will hacked client support ever be added to this?

**Comment by khanhduytran0** [comment]
Already have custom versions, why not hacked client?

**Comment by issuereporter292** [comment]
> Already have custom versions, why not hacked client?

I just didn't think it would be possible to add client support

**Comment by khanhduytran0** [comment]
Just rename `.jar` to `_orig.jar`, put version json,... then you can see custom versions at the bottom of versions.

**Comment by issuereporter292** [comment]
> Just rename `.jar` to `_orig.jar`, put version json,... then you can see custom versions at the bottom of versions.

Wdym by "put version json,..."?

**Comment by khanhduytran0** [comment]
```
1.7.10
 '-> 1.7.10.json
 '-> 1.7.10_orig.jar
```

**Comment by issuereporter292** [comment]
> ```
> 1.7.10
>  '-> 1.7.10.json
>  '-> 1.7.10_orig.jar

So something like this?
https://www.mediafire.com/view/z2miap66eza3y4s/Screenshot_20200426-223113_RAR.jpg/file

**Comment by khanhduytran0** [comment]
Yes

```
/sdcard/games/minecraft
 '-> versions
     '-> SkillClient1.11
           '-> SkillClient1.11_orig.jar
           '-> SkillClient1.11.json
```

**Comment by issuereporter292** [comment]
> Yes
> 
> ```
> /sdcard/games/minecraft
>  '-> versions
>      '-> SkillClient1.11
>            '-> SkillClient1.11_orig.jar
>            '-> SkillClient1.11.json
> ```

Ohhh ok thank you

**Comment by khanhduytran0** [comment]
If version not working reopen.

**Comment by issuereporter292** [comment]
> If version not working reopen.

Someones gotta make a yt video on this or something.
