### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by DirectiveTaurus** [PojavLauncherTeam/PojavLauncher#1385]
Can you add a hide button /touch controls (including gui) for keyboard and mouse users I know theres already a option to Hide it with that Gui and we can also transparent that button but it's also need to be this option in settings menu 
Just add it in the settings as = Hide buttons
Thank you in advance

**Comment by EnderBrine99FOX** [comment]
> Can you add a hide button /touch controls (including gui) for keyboard and mouse users I know theres already a option to Hide it with that Gui and we can also transparent that button but it's also need to be this option in settings menu
> Just add it in the settings as = Hide buttons
> Thank you in advance

You don't need to add buttons or hide it, i Play with mouse and keyboard all you need is delete all the buttons and the mouse and keyboard will function perfectly fine, or download my control map for mouse and keyboard only
https://www.mediafire.com/download/8ht9b2csgw39ynm

**Comment by mchnjt** [comment]
Fill the template.
