### ISSUE TITLE
[Issue] crash

### ISSUE THREAD

**Issue by issuereporter292** [PojavLauncherTeam/PojavLauncher#139]
Head --
Thread: Client thread
Stacktrace:
	at tk.skillclient.aiR.SkillClient(Unknown Source:8)
	at tk.skillclient.aiP.do(Unknown Source:23)

-- Initialization --
Details:
Stacktrace:
	at tk.skillclient.xu.SkillClient(Unknown Source:5)
	at tk.skillclient.ej.SkillClient(Unknown Source:32)
	at net.minecraft.client.main.Main.main(Unknown Source:1389)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:939)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:628)
	at java.lang.Thread.run(Thread.java:919)

-- System Details --
Details:
	SkillClient Version: Minecraft 1.11 | SkillClient b2.3
	Minecraft Version: 1.11
	Operating System: Linux (armv8l) version 4.9.186-17655189
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-G960U [Android 29]), The Android Project
	Memory: 0 bytes (0 MB) / 181697016 bytes (173 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: SkillClient1.11
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 12 (v8l)
	OptiFine Version: OptiFine_1.11_HD_U_A1_pre
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
May not solvable, so try other versions.

**Comment by issuereporter292** [comment]
> May not solvable, so try other versions.

Ok

**Comment by issuereporter292** [comment]
> May not solvable, so try other versions.

I tried 13 different clients and none worked. One has to be custom made for this probably. Theres also no way to actually use these if they worked because you usually need to press shift or some other key.
