### ISSUE TITLE
[BUG] Multiple errors in Huawei Y5

### ISSUE THREAD

**Issue by pablodz** [PojavLauncherTeam/PojavLauncher#1392]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

Can't open minecraft inside phone

**Add a log file if you want to see your bug fixed !**

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6497540/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Run any minecraft version
3. App crashes and reboot to login

**Platform:**
 - Device Model: Huawei Y5
 - CPU architecture aarch64 (kirin655)
 - Android Version  Android 8.0 
 - PojavLauncher Version latest from Google Play

**Comment by mchnjt** [comment]
'latests'

**Comment by artdeell** [comment]
So, that's how you "delegate" support from your Telegram channel to us. Btw this guy just didn't install Forge as intended.
