### ISSUE TITLE
[BUG] CRASH ON CHROMEBOOK

### ISSUE THREAD

**Issue by SergueiKhadirov** [PojavLauncherTeam/PojavLauncher#1396]
I installed PojavLauncher 3.3.1.1_rel_20210321 on my x86_64 HP Chromebook (latest version of Chrome OS). When I open the launcher and install a minecraft version, everything goes well, but when I click on "play" button, the game starts to load with a black screen and then it closes itself and brings me back to the launcher's main menu. I tried with 1.16.5 and 1.7.10 and I had the same problem. There's no error logs and no error message. I tried to uninstall JVM through the launcher's settings but still the same problem. I also tried OpenGL ES 2 and OpenGL ES 3 but didn't solve the problem. I give about 800 Mb to the launcher so I don't think it's a RAM problem, and I have about 2 Gb free storage so I don't think that's the problem. Can you help me please ?
Have a nice day ;)

**Comment by WesleyVanNeck** [comment]
just fill template give us a latestlog.txt without it no help

**Comment by WesleyVanNeck** [comment]
i will close this and will open it if you fileld the tamplate and given the latestlog.txt
