### ISSUE TITLE
[BUG] runtime 32 inconpatible with aarch 64, but my device is 32 bits 

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1398]
1 install the laste build in your device 32
2 play the game
3 Aarch 32 is inconpatible with Aarch 64

**Comment by OwzygZawg** [comment]
@khanhduytran0

**Comment by WesleyVanNeck** [comment]
Happens also with x86.64

**Comment by WesleyVanNeck** [comment]
It says it needs arm64

**Comment by OwzygZawg** [comment]
> It says it needs arm64

Yep

**Comment by ghost** [comment]
"runtime 32 inconpatible with aarch64 , but my device 32 bits"

aarch64 ≠ arm32
Bruh _-

**Comment by mchnjt** [comment]
Why would you get a jre for 32bit if your device is 64bit

**Comment by OwzygZawg** [comment]
My device is 32

**Comment by mchnjt** [comment]
THEN GET THE 32 BIT FOR YOUR DEVICE
