### ISSUE TITLE
Pojav crashes on 1.8.9

### ISSUE THREAD

**Issue by WesleyVanNeck** [PojavLauncherTeam/PojavLauncher#1399]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2 open 1.8.9 
3 play any server

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Motorola g 5g
 -  aarch64
 - Android 11
 - latest

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6505790/latestlog.txt)

**Comment by khanhduytran0** [comment]
tf is going on with @LegacyGamerHD why don't u post in development?

**Comment by WesleyVanNeck** [comment]
> tf is going on with @LegacyGamerHD why don't u post in development?

I did no one is listing
