### ISSUE TITLE
Motorola one vision (android 10)

### ISSUE THREAD

**Issue by TarikBR** [PojavLauncherTeam/PojavLauncher#140]
![Screenshot_20200426-230841](https://user-images.githubusercontent.com/64391349/80330535-cfcc7900-881b-11ea-8ede-e2fe42bd95d9.png)

Motorola one vision (android 10)

**Comment by khanhduytran0** [comment]
Because Android 10 does not allow to run native binaries, so try to run in VMOS. But why you download v3?

**Comment by TarikBR** [comment]
Yes, I downloaded v3, on vmos say this error: (at the vmos I couldn't
install the v3 so I installed the v2.5 preview 1)

**Comment by khanhduytran0** [comment]
Uninstall V2.5 and install v3 in vmos

**Comment by TarikBR** [comment]
V3 on vmos:

Em seg, 27 de abr de 2020 02:33, khanhduytran0 <notifications@github.com>
escreveu:

**Comment by khanhduytran0** [comment]
I'm found a way to fix Bad System Call. Wait for v3 preview2.
