### ISSUE TITLE
[BUG] Help me please I am facing a problem in pojav launcher that if I download any version it's working but after 1 day its saying when i click play file not found everytime please help me.

### ISSUE THREAD

**Issue by DRONZER7212** [PojavLauncherTeam/PojavLauncher#1403]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I am facing a problem that if I download any version but after 1 day its saying file not found.

Log----

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model  Samsung Galaxy M30s [4/64]
 - CPU architecture I dont know
 - Android Version 10
 - PojavLauncher Version [playstore version]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6510070/latestlog.txt)   
    

Note!!!--  I didn't download full version.

**Comment by WesleyVanNeck** [comment]
Fill template and give latestlog.txt

**Comment by DRONZER7212** [comment]
> Fill template and give latestlog.txt

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6512898/latestlog.txt)
Done

**Comment by Nishu-max** [comment]
Are you are playing on samsung devices. I faced the same issue on my samsung device. On COD mobile and pojavlauncher. I will give if u are playing on samsung device

**Comment by khanhduytran0** [comment]
> Cannot contact authentication server

**Comment by DRONZER7212** [comment]
> > Cannot contact authentication server

What this mean please help me.

**Comment by mchnjt** [comment]
it means the auth server is down

**Comment by DRONZER7212** [comment]
> it means the auth server is down

This can be fix or not.

**Comment by DRONZER7212** [comment]
> it means the auth server is down

Please tell i want to play minecraft java with shaders in my mobile.

**Comment by mchnjt** [comment]
Wanna play with shaders?

(***Do you have an Intel, snapdragon, or an nVidia processor?***)

**Comment by DRONZER7212** [comment]
> Wanna play with shaders?
> 
> (_**Do you have an Intel, snapdragon, or an nVidia processor?**_)

I have an exynos 9611 processor with mali g72

**Comment by WesleyVanNeck** [comment]
> > Wanna play with shaders?
> > (_**Do you have an Intel, snapdragon, or an nVidia processor?**_)
> 
> I have an exynos 9611 processor with mali g72

Then you cant

**Comment by DRONZER7212** [comment]
> > > Wanna play with shaders?
> > > (_**Do you have an Intel, snapdragon, or an nVidia processor?**_)
> > 
> > 
> > I have an exynos 9611 processor with mali g72
> 
> Then you cant

Please fix this issue. I want to play.

**Comment by DRONZER7212** [comment]
> > > Wanna play with shaders?
> > > (_**Do you have an Intel, snapdragon, or an nVidia processor?**_)
> > 
> > 
> > I have an exynos 9611 processor with mali g72
> 
> Then you cant

I also have a snapdragon mobile with snapdragon 662 but it only gives me 1-5 fps.

**Comment by mchnjt** [comment]
> > > > Wanna play with shaders?
> > > > (_**Do you have an Intel, snapdragon, or an nVidia processor?**_)
> > > 
> > > 
> > > I have an exynos 9611 processor with mali g72
> > 
> > Then you cant
> 
> I also have a snapdragon mobile with snapdragon 662 but it only gives me 1-5 fps.

:Trollface: just use an shader-illusionating texture pack

**Comment by khanhduytran0** [comment]
@rscDoesMoreTrolling :trollface:

**Comment by khanhduytran0** [comment]
> > Wanna play with shaders?
> > (_**Do you have an Intel, snapdragon, or an nVidia processor?**_)
> 
> I have an exynos 9611 processor with mali g72

*then get zink*

**Comment by khanhduytran0** [comment]
> Please fix this issue. I want to play.

It is not an issue. It is about the GPU. Your phone is not using a PC GPU, so running java shader will crashes.

**Comment by DRONZER7212** [comment]
> > Please fix this issue. I want to play.
> 
> It is not an issue. It is about the GPU. Your phone is not using a PC GPU, so running java shader will crashes.

Hey duytrankhanh sorry for sending wrong latestlog. I send you latestlog without downloading full version this is the latestlog of that I downloaded the version 1.16.5 yesterday and today the version file is gone this is latestlog.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6525796/latestlog.txt)

**Comment by DRONZER7212** [comment]
Please help me as fast as can

**Comment by mchnjt** [comment]
The devs aren't **the flash.**

just wait

**Comment by Nishu-max** [comment]
It can happen because your device is thinking that are trash files and is clearing them. It happened to me on my samsung device and I fixed it by disabling clear files.And see they will clear at night 12:00 pm

**Comment by khanhduytran0** [comment]
> It can happen because your device is thinking that are trash files and is clearing them. It happened to me on my samsung device and I fixed it by disabling clear files.And see they will clear at night 12:00 pm

probably adding `.nomedia` file will prevent it? :thinking:

**Comment by DRONZER7212** [comment]
> It can happen because your device is thinking that are trash files and is clearing them. It happened to me on my samsung device and I fixed it by disabling clear files.And see they will clear at night 12:00 pm

Thanks bro for helping me. Thank you so much !!!!

**Comment by Nishu-max** [comment]
The files will disappear only on versions above 3.3 testing

**Comment by mchnjt** [comment]
> The files will disappear only on versions above 3.3 testing

It doesn't.

**Comment by EXPress-016** [comment]
It's actually samsung cleaner problem
This can help I think https://youtu.be/AlcQqSs6Kq8

**Comment by mchnjt** [comment]
praise Samsung for improving 'security' and making an a.i that triggers simps
