### ISSUE TITLE
helllo khanhduytran0 i have a problem i write anything in pojavlauncher option launch a mod installer(with custom argument)  then press ok then i see tomorrow in /pojavlauncher/.minecraft folders are ok but file are no more in /.minecraft in any folder what shall i do now ?

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#1407]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Nishu-max** [comment]
Same with me one month ago

**Comment by Nishu-max** [comment]
It's not a big its device creating the files

**Comment by mchnjt** [comment]
dupe issues tfw

**Comment by Nishu-max** [comment]
Just use 3.3 testing the files will be secured

**Comment by mchnjt** [comment]
> It's not bug its device clearing the files

maybe he/she forgot to install anything so that he/she can't see any files

or he/she cleared the data from the settings (but look, I have no significance that tapping clear data from settings deletes the pojav folder)

**Comment by khanhduytran0** [comment]
> what should i do now
fill the template or i will block u
