### ISSUE TITLE
hello khanhduytran0 i have a problem the i write anything in pojav launcher launch a mod installer(with custom argument) then press ok then tomorrow i see in /pojavlauncher/.minecraft folder  i see folders are ok but in .minecraft folder in any folder file are no more what shall i do now?

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#1409]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
> what shall i do now?

fill the template is primary thing to do before get here.

**Comment by Sazedzahan** [comment]
this is a launcher problem i made so please help me

**Comment by khanhduytran0** [comment]
But you only provide these how I know your problem?

**Comment by khanhduytran0** [comment]
We don't implement auto logger or anything about log/crash uploader on launcher so we don't know anything to fix, so you need provide here.

**Comment by Sazedzahan** [comment]
you go to pojav launcher go to option  then go to mod installer with custom argument then write anything then press ok then see tomorrow to folder pojavlauncher/.minecraft then go to any folder in .minecraft then 
you see there are no file

**Comment by mchnjt** [comment]
:Trauma:

**Comment by mchnjt** [comment]
> you go to pojav launcher go to option  then go to mod installer with custom argument then write anything then press ok then see tomorrow to folder pojavlauncher/.minecraft then go to any folder in .minecraft then 
> you see there are no file

Are you sure? It looks like you forgot to install anything

**Comment by Sazedzahan** [comment]
i am sure

**Comment by Sazedzahan** [comment]
make sure you install any version of minecraft like 1.16.4 any version

**Comment by mchnjt** [comment]
no not 1.16.4

his/her data allowance will drain quickly :Trollface:

install 1.8 instead
