### ISSUE TITLE
Aristos client sigma and meteor crashing

### ISSUE THREAD

**Issue by Nishu-max** [PojavLauncherTeam/PojavLauncher#1410]
Pojavlauncher crashing when using aristos client
When I use aristos client on the latest Google play release it loads to the mojang screen but it crashes and a screen appears 
(Saving world)
I am using a offline account
I will add latest log soon.
Please fix this 
I wanna use hacks instead of impact and wurst
No other client like meteor,aristos,sigma doesn't work.☹☹☹☹☹☹

**Platform:**
 - Device Model [Samsung Galaxy M31]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

**Comment by Nishu-max** [comment]
When using sigma 5.0 beta it takes ages to load and meteor with latest fabric version and api crashes instantly
Is there another dependency and what can I do with sigma

**Comment by mchnjt** [comment]
👏Nice! You didn't filled the template!

(*Bruh I can't even run it*)

**Comment by Nishu-max** [comment]
I tried running sigma it crashes always after 3to4 minutes

**Comment by khanhduytran0** [comment]
Most clients aren’t supported. They are designed for Windows, Linux, macOS and not for Android, iOS.

**Comment by Nishu-max** [comment]
Ok thanks

**Comment by ARYAARYA72** [comment]
Link
