### ISSUE TITLE
[BUG] CRASH ON CHROMEBOOK

### ISSUE THREAD

**Issue by SergueiKhadirov** [PojavLauncherTeam/PojavLauncher#1411]
I installed PojavLauncher 3.3.1.1_rel_20210321 on my x86_64 HP Chromebook (latest version of Chrome OS) from PlayStore. When I open the launcher and install a minecraft version, everything goes well, but when I click on "play" button, the game starts to load with a black screen and then it closes itself and brings me back to the launcher's main menu. I tried with 1.16.5 and 1.7.10 and I had the same problem. There's no error logs and no error message. I tried to uninstall JVM through the launcher's settings but still the same problem. I also tried OpenGL ES 2 and OpenGL ES 3 but didn't solve the problem. I give about 800 Mb to the launcher so I don't think it's a RAM problem, and I have at least 3 Gb free storage so I don't think that's the problem. Can you help me please ?

How to recreate the bug :
Download a Minecraft version and click play button

**Comment by khanhduytran0** [comment]
We don’t have a chromebook to reproduce, you don’t have latestlog.txt :eyes:

**Comment by SergueiKhadirov** [comment]
how can i get it ?

**Comment by mchnjt** [comment]
:ULTIMATEEROFEL:

**Comment by khanhduytran0** [comment]
@SergueiKhadirov and well you’ve duplicated issue **without following the rules: fill the template**

**Comment by khanhduytran0** [comment]
/sdcard/games/PojavLauncher or idk

**Comment by WesleyVanNeck** [comment]
cant reproduce this on chrome os with playstore build

**Comment by WesleyVanNeck** [comment]
tested on chromeos r80 r90 and r92 (dev build of chrome os)

**Comment by SergueiKhadirov** [comment]
i'm on stable version 90.0.4430.218 of chrome  os 64 bit

**Comment by WesleyVanNeck** [comment]
> i'm on stable version 90.0.4430.218 of chrome os 64 bit

i tested on r90 r90 is 90.0.4430.218 and i cant reproduce it

**Comment by SergueiKhadirov** [comment]
Here is latestlog.txt
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6528277/latestlog.txt)

When the bug happens there is nothing in the crash log or the dev console. I recorded a video (it's .webm format).
[Screen recording 2021-05-23 16.28.07.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/6528252/Screen.recording.2021-05-23.16.28.07.zip)

**Comment by matt995** [comment]
Theres a problem with jvm

**Comment by SergueiKhadirov** [comment]
so what's the problem exactly plz, and can I solve it ?

**Comment by SergueiKhadirov** [comment]
ah ok LegacyGamer i'm not used to call this version r90 XD

**Comment by SergueiKhadirov** [comment]
So what's the problem with jvm?
How can I solve it?

**Comment by SergueiKhadirov** [comment]
> Theres a problem with jvm

so... what should I do?

**Comment by khanhduytran0** [comment]
@SergueiKhadirov you need somehow enable 64bit for android user space.

**Comment by SergueiKhadirov** [comment]
@khanhduytran0  i'm on a 64 bit intel chromebook so I don't clearly understand what you mean

**Comment by khanhduytran0** [comment]
@SergueiKhadirov No matter if your chromebook is 32bit or 64bit, but android userspace is 32bit. See these for more info:
- [32 bit Android on 64 bit Chromebook?](https://www.reddit.com/r/chromeos/comments/hqmeb2/32_bit_android_on_64_bit_chromebook)
- [Android in ChromeOS: Could we get 64-bit?](https://www.reddit.com/r/chromeos/comments/6yfwry/android_in_chromeos_could_we_get_64bit/)
- [Chrome OS 64 bit but Android states 32 bit](https://www.reddit.com/r/chromeos/comments/anymyt/chrome_os_64_bit_but_android_states_32_bit)

**Comment by SergueiKhadirov** [comment]
@khanhduytran0 it's weird because it works well on my 32 bit amd android  phone

**Comment by khanhduytran0** [comment]
Don’t confuse between arm32/aarch32 with x86/i386, they are completely different.

**Comment by SergueiKhadirov** [comment]
@khanhduytran0 i went to your links and they all conclude by saying it's impossible. I asked in discord they said the same thing.

**Comment by SergueiKhadirov** [comment]
@LegacyGamerHD man how you just managed to run pojav ?

**Comment by SergueiKhadirov** [comment]
so what could i do ?

**Comment by SergueiKhadirov** [comment]
@LegacyGamerHD i'll try a thing can u plz do the command uname -a in crosh in your chrome os r90 and send me screenshot plz

**Comment by netkv** [comment]
also instead of using pojav, you can try run java minecraft in chromeos's linux support thingy

**Comment by SergueiKhadirov** [comment]
@Pan00Pernicek good idea but my chromebook is still school managed so i can't

**Comment by SergueiKhadirov** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6648690/latestlog.txt)
There r a lot of "unsupported flags". What could that mean ?

**Comment by khanhduytran0** [comment]
32bit can't allocate more than 900MB of RAM.

**Comment by netkv** [comment]
isnt there bug in pojav's runtime which makes x86 able to alocate only 128 mb of ram, or it was fixed and i am living under rock?

**Comment by SergueiKhadirov** [comment]
@khanhduytran0  i was allocating 800Mb

**Comment by SergueiKhadirov** [comment]
@Pan00Pernicek i'll try some versions with 128Mb and less in my chromebook as soon as I can insha'Allah

**Comment by SergueiKhadirov** [comment]
@Pan00Pernicek for me minimum allocable ram is 256mb

**Comment by Leonardoanisman** [comment]
My friend is having the same problem and minimal alacation is 256

**Comment by SergueiKhadirov** [comment]
All versions of mc i tried with 128mb dont work

**Comment by SergueiKhadirov** [comment]
@Leonardoanisman good thing to know that i'm not the only one to have this problem :D

**Comment by SprainedSpark89** [comment]
turn down the memory

**Comment by SprainedSpark89** [comment]
here is how to get latest log on chromebook https://github.com/PojavLauncherTeam/PojavLauncher/issues/2537

**Comment by GAOCentral** [comment]
i created a video on how to fix it 
hope it helps 
[https://www.youtube.com/watch?v=A6eSpOJqPAI](url)

**Comment by GAOCentral** [comment]
https://www.youtube.com/watch?v=A6eSpOJqPAI
this should fix it

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
