### ISSUE TITLE
[F-REQ] Browser Support

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1412]
Add Browser Support

Open link in minecraft and direct to browser maybe chrome or edge (android)

Describe alternatives you've considered
Maybe some people need this :)

I need for register labymod and login lunar client using Microsoft Account

**Comment by mchnjt** [comment]
> Add Browser Support
> 
> 
> Open link in minecraft and direct to browser maybe chrome or edge (android)
> 
> 
> Describe alternatives you've considered
> Maybe some people need this :)
> 
> I need for register labymod and login lunar client using Microsoft Account 

:trollface:

**Comment by ghost** [comment]
looks like it won't be added
