### ISSUE TITLE
[BUG] Mojang account doesn't works

### ISSUE THREAD

**Issue by Byllfighter** [PojavLauncherTeam/PojavLauncher#1416]
My mojand account doesn't works

Error:

```
Respone error

code: 403

message: {"error":"ForbiddenOperationException" "errorMessage":"Invalid credentials. Invalid username or password."}
```

When I write email it writes:

`Frequently used email`

**Comment by mchnjt** [comment]
send __latestlog.txt__ please.

:trollface:

**Comment by mchnjt** [comment]
and fill the template

**Comment by khanhduytran0** [comment]
> Frequently used email

@Byllfighter you’ve tried logged in too much with wrong password

**Comment by mchnjt** [comment]
> My mojand account doesn't works
> 
> Error:
> 
> ```
> Respone error
> 
> code: 403
> 
> message: {"error":"ForbiddenOperationException" "errorMessage":"Invalid credentials. Invalid username or password."}
> ```
> 
> When I write email it writes:
> 
> `Frequently used email`

PS: you forgot that you didn't bought Java. @Byllfighter

**Comment by Byllfighter** [comment]
Sorry, I wrote big letters in password, but now it writes
`This account already exist!`

Now I using ReAuth mod

**Comment by khanhduytran0** [comment]
> Sorry, I wrote big letters in password, but now it writes
> 
> `This account already exist!`
> 
> 
> 
> Now I using ReAuth mod

nah. Check the account list and remove it before login.
