### ISSUE TITLE
[F-REQ]How can I add Resource Packs or Mods or Versions to the launcher?

### ISSUE THREAD

**Issue by Lambholl** [PojavLauncherTeam/PojavLauncher#1422]
Hello there, I want to add some resource packs to the game, and also cmpack to the launcher. But now I found that I cannot find ".minecraft" folder or any folder that is similar to it. So how can I do that?
Thanks.

**Comment by Lambholl** [comment]
> Hello there, I want to add some resource packs to the game, and also cmpack to the launcher. But now I found that I cannot find ".minecraft" folder or any folder that is similar to it. So how can I do that?
> Thanks.

Sorry now I found that folder. 
But problem is that I can't launch cmpack

**Comment by mchnjt** [comment]
What's a cmpack?@Lambholl
