### ISSUE TITLE
Forge on 1.16.5

### ISSUE THREAD

**Issue by njat500** [PojavLauncherTeam/PojavLauncher#1423]
When I try to install forge for 1.16.5, the launcher restarts. On Internet I was saw similar problems. Any solution for me and those people? :)

**Comment by ghost** [comment]
Log?

**Comment by rscAvePlex** [comment]
> When I try to install forge for 1.16.5, the launcher restarts. On Internet I was saw similar problems. Any solution for me and those people? :)

bruh

**Comment by khanhduytran0** [comment]
@njat500 any solution for avoid ripping the template? :)

**Comment by khanhduytran0** [comment]
closed for: did_not_reply() and fill_the_template()
