### ISSUE TITLE
[BUG] Instant Crash

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#1424]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

>Instant Crash

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6529996/latestlog.txt)

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Wait For Game To Load On Logo 
3. Join Any Server In 3-4 sec
4. Crash?! 

### Expected behavior:
I expected to run the game normally

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 7]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
1.8.9 is currently unstable, please play other versions. Also duplicated.

**Comment by mchnjt** [comment]
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> <br>
> - Make sure there was not duplicated issues.<br>
> - Make sure you have filled this issue template, or this will get rejected.
> </details>
> 
> ### Describe the bug
> A clear and concise description of what the bug is.
> 
> >Instant Crash
> 
> **Add a log file if you want to see your bug fixed !**
> 
> The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6529996/latestlog.txt)
> 
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> 2. Wait For Game To Load On Logo 
> 3. Join Any Server In 3-4 sec
> 4. Crash?! 
> 
> ### Expected behavior:
> I expected to run the game normally
> 
> ### Screenshots or videos:
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> 
> **Platform:**
>  - Device Model [e.g. Mi 8 Pro 8/128]
>  - CPU architecture [e.g. aarch64] 
>  - Android Version [e.g. 7]
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> <details> <summary><b>Additional context</b></summary>
> <br>
> <pre>
> Add any other context about the problem here.
> </pre>
> </details>
> 

how are you crashing?

**Comment by mchnjt** [comment]
cuz i don't crash
