### ISSUE TITLE
How to add world generation datapacks[F-REQ]

### ISSUE THREAD

**Issue by Nishu-max** [PojavLauncherTeam/PojavLauncher#1426]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.I wanna know how to add world gen Datapacks in minecraft and I know that world gen datapacks can 
only be added during world generation. Every time I try to add datapacks before world generation started and there is the way i tried to add create new world>datapacks>open datapack folder and it doesn't work.
**Describe the solution you'd like**
Maybe add like file manager support in game.

**Describe alternatives you've considered**

**Additional context**
Nope.

**Comment by WesleyVanNeck** [comment]
like woeld on any minecraft java
