### ISSUE TITLE
OpedJdk Runtime Bad System Call Preview 3.0.0

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#143]
Hey Admin My is give error bad system call opedjdk! Help me im is not play minecraft :(
![Screenshot_20200427-142223_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/47820634/80344948-93882f80-8892-11ea-8892-2cbd0d9336b0.jpg)

**Comment by khanhduytran0** [comment]
V3 is very very experimental why you install it?

**Comment by khanhduytran0** [comment]
Try in vmos...

**Comment by ghost** [comment]
No im is install no vmos

**Comment by ghost** [comment]
![Uploading Screenshot_20200427-142528_Chrome.jpg…]()
My is download

**Comment by khanhduytran0** [comment]
Is your Android 10?

**Comment by ghost** [comment]
Yes

**Comment by khanhduytran0** [comment]
Android 10 is not supported due to prevent execution. Do you have root?

**Comment by ghost** [comment]
No

**Comment by ghost** [comment]
Im have Device Android 9.0

**Comment by ghost** [comment]
My is install android 9.0 is....
![Screenshot_20200427-145848_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/47820634/80348283-c2ed6b00-8897-11ea-98e8-de7ae01f2a50.jpg)

**Comment by khanhduytran0** [comment]
32-bit is not supported.

**Comment by khanhduytran0** [comment]
Bad system call have a way to solve!

**Comment by khanhduytran0** [comment]
What's your architecture?

**Comment by ghost** [comment]
My is downloads is not read my is play minecraft pc no use vortex
