### ISSUE TITLE
Hello, how do i install a modified version like melon client or something like that

### ISSUE THREAD

**Issue by bonkxd1234** [PojavLauncherTeam/PojavLauncher#1432]
Im new to pojavlauncher, i really want to use modified version but i dont know how please tell me i appreciate it if u do

**Comment by rscAvePlex** [comment]
> Im new to pojavlauncher, i really want to use modified version but i dont know how please tell me i appreciate it if u do

First, are you *lazy* enough to __even ***fill the template?***__

**Comment by CriticalRange** [comment]
> Im new to pojavlauncher, i really want to use modified version but i dont know how please tell me i appreciate it if u do

1-) This is a bug report section for issues
2-)Give a visit to discord server, we can help you there
3-)Watch YouTube videos, some of them explain it very good
