### ISSUE TITLE
Pojavchaunher khi nào có phiên bản mới

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1433]
Khi nào có phiên bản pojavchaunher mới vậy

**Comment by rscAvePlex** [comment]
> Khi nào có phiên bản pojavchaunher mới vậy

Pong kang ching chong chang sthu i dont know vietnamese

**Comment by rscAvePlex** [comment]
> Khi nào có phiên bản pojavchaunher mới vậy

[ENG: When will there be a new version of pojavchaunher]

As far as development goes, nobody has known yet on when will the new version get released.

*Theo như quá trình phát triển, vẫn chưa ai biết khi nào phiên bản mới sẽ được phát hành.*

@Joakdnhio

**Comment by Joakdnhio** [comment]
Thank you
