### ISSUE TITLE
[BUG] <Short description> devia entrar em todas as contas, Microsoft e etc,esse bug já tá chato/should enter all accounts, Microsoft and etc., this bug is already boring

### ISSUE THREAD

**Issue by arrumaissoae** [PojavLauncherTeam/PojavLauncher#1434]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
#509

**Comment by mchnjt** [comment]
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> <br>
> - Make sure there was not duplicated issues.<br>
> - Make sure you have filled this issue template, or this will get rejected.
> </details>
> 
> ### Describe the bug
> A clear and concise description of what the bug is.
> 
> **Add a log file if you want to see your bug fixed !**
> 
> The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> ... *(your set of actions to reproduce the bug)*
> 
> ### Expected behavior:
> I expected ...
> 
> ### Screenshots or videos:
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> 
> **Platform:**
>  - Device Model [e.g. Mi 8 Pro 8/128]
>  - CPU architecture [e.g. aarch64] 
>  - Android Version [e.g. 10]
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> <details> <summary><b>Additional context</b></summary>
> <br>
> <pre>
> Add any other context about the problem here.
> </pre>
> </details>
> #509 

did you just referenced #509 onto your problem?

**Comment by mchnjt** [comment]
@arrumaissoae it is not a bug.

Try enabling **both login as offline and keep account**, that maybe helps you

**Comment by khanhduytran0** [comment]
@arrumaissoae you're ~~boring~~ bothering us as well because of template not filled and did not buy minecraft.
