### ISSUE TITLE
[BUG] MOUSE POINTER DOES NOT DISAPPEAR 

### ISSUE THREAD

**Issue by Dryxorz** [PojavLauncherTeam/PojavLauncher#1435]
**Describe the bug**
I play with a physical keyboard and mouse and when I want to play, the mouse pointer does not disappear and when I press left click or the mouse wheel does not move the screen.

**To Reproduce**
1. Start PojavLauncher
2. Plug in a mouse
3. Play
4. Move mouse

**Expected behavior**
I was expecting the mouse pointer to disappear when gaming, as well as on the PC version.

**Screenshots:**
https://m.youtube.com/watch?v=RLIzPbiAgG8&feature=youtu.be
**Platform:**
- Redmi 4x
- aarch64
- Android 7.1.2

**Additional context** I tried editing options.txt's height and width (like mentioned on some other issues), but they get automatically reset on launch every time.

**Comment by khanhduytran0** [comment]
Mouse capture which hides the mouse is only supported since android 8.
