### ISSUE TITLE
Architecture x86_64/amd64 is incompatible with Java Runtime aarch64 on chromebook

### ISSUE THREAD

**Issue by JML6305** [PojavLauncherTeam/PojavLauncher#1436]
java.lang.RuntimeException: Architecture x86_64/amd64 is incompatible with Java Runtime aarch64. at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:45) at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:899) at net.kdt.pojavlaunch.BaseMainActivity.access$2600(BaseMainActivity.java:27) at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:707) at java.lang.Thread.run(Thread.java:764)

well i installed an apk on my chromebook with developer mode (Latest New Crowdin Updates) on https://github.com/PojavLauncherTeam/PojavLauncher/actions

**Comment by khanhduytran0** [comment]
New crowdin updates are translation updates, not launcher updates.

**Comment by JML6305** [comment]
> New crowdin updates are translation updates, not launcher updates.

oh thanks anyway but

New crowdin updates only work on my phone has no error, my chromebook only i get an error "Architecture x86_64/amd64 is incompatible with Java Runtime aarch64". i guess

**Comment by rscAvePlex** [comment]
> > New crowdin updates are translation updates, not launcher updates.
> 
> oh thanks anyway but
> 
> New crowdin updates only work on my phone has no error, my chromebook only i get an error "Architecture x86_64/amd64 is incompatible with Java Runtime aarch64". i guess

wdym crowdin? The translatiob update isn't touching the app's manifest.xml

**Comment by khanhduytran0** [comment]
bruh, translation updates are in `res/values-LANG`. I mean you should only try them if you are a language translator and want to check your translated strings.

**Comment by khanhduytran0** [comment]
And they are outdated, not upstream with main branch.

**Comment by JML6305** [comment]
im using lunar client for no crash on pojavlancher.
i watched on youtube updated tutorial.

**Comment by JML6305** [comment]
well never mind i just gonna redownload pojavlauncher again on play store.

**Comment by rscAvePlex** [comment]
bruh
