### ISSUE TITLE
Another dream not come true

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1437]
I try to play pojavlauncher zink in 1.12.2 but I don't see my hero and mobs I only heard sound of them 💭💭💭

**Comment by khanhduytran0** [comment]
Your unexpected dream is a block. Yes, you may be blocked because of zink issues spam. ~~Once you insert a RTX 3090 to your phone, we will help you about zink~~.

**Comment by khanhduytran0** [comment]
For replying to problem, zink is buggy on 1.12.2 and below.

**Comment by rscAvePlex** [comment]
:trollface: dood cant afford rtx3080 eksdee
