### ISSUE TITLE
World generationdatapacks [F-REQ]

### ISSUE THREAD

**Issue by Nishu-max** [PojavLauncherTeam/PojavLauncher#1438]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. It does not let me add world generation datapacks.

**Describe the solution you'd like**
Maybe add file manager support to pojavlauncher. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rscAvePlex** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. It does not let me add world generation datapacks.
> 
> **Describe the solution you'd like**
> Maybe add file manager support to pojavlauncher. 
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 

@Nishu-max are you lazy enough to check your file manager?
