### ISSUE TITLE
I can't play any version! (3.0.0 Preview1)

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#144]
When I start any version, I see this:
![Screenshot_20200427_094543_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/80347258-5dd05000-886c-11ea-82cb-0f075c382b96.jpg)
(Screenshot from launching minecraft 1.11.2) I am waiting and waiting and nothing happens... Fix this pls

Info:
Android: 9.1
VMOS: no
Huawei: yes
EMUI: yes
Root: I am trying to get but I don't know how. No

**Comment by khanhduytran0** [comment]
So I found a solution!
https://github.com/MasterDevX/Termux-Java/issues/3#issuecomment-548679532

**Comment by khanhduytran0** [comment]
May fix in next version!

**Comment by ghost** [comment]
Omg?

**Comment by khanhduytran0** [comment]
> Omg?

Fix Bad System Call but may not launch right now.

**Comment by khanhduytran0** [comment]
Fixed, duplicate with #140.
