### ISSUE TITLE
my game keeps closing

### ISSUE THREAD

**Issue by LorranSf** [PojavLauncherTeam/PojavLauncher#1440]
please someone help me when i enter a server the game closes alone when i walk or need to walk whenever q i enter some server the game closes and goes to the login screen i already got it in all config but none works

**Comment by khanhduytran0** [comment]
please someone help you to fill the template

**Comment by khanhduytran0** [comment]
@LorranSf

**Comment by khanhduytran0** [comment]
So you didn't reply. Closing.

**Comment by rscAvePlex** [comment]
indian on the old days: 👍

indians nowadays: oK StHu iMmA uNiNsTaLl tHis tRaSh bRb i wIlL mAkE mY lAuNcHeR mYsElF oK
