### ISSUE TITLE
[All versions] Scrolling doesnt work

### ISSUE THREAD

**Issue by AustizzTDS** [PojavLauncherTeam/PojavLauncher#1443]
Hi, i have conected a mouse on my chromebook (yes i downloaded projavlauncher on chromebook)  and i does work but the scrolling doesnt seem to work is this a issue or is it just the mouse??

**Comment by mchnjt** [comment]
> Hi, i have conected a mouse on my chromebook (yes i downloaded projavlauncher on chromebook)  and i does work but the scrolling doesnt seem to work is this a issue or is it just the mouse??
> 

k

**Comment by EnderBrine99FOX** [comment]
> Hi, i have conected a mouse on my chromebook (yes i downloaded projavlauncher on chromebook) and i does work but the scrolling doesnt seem to work is this a issue or is it just the mouse??

I have the same problem

**Comment by khanhduytran0** [comment]
Mouse scrolling is only available on dev build, which is experimental, you may try go to [github actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk)
Also
> any solution for not ripping the template?

**Comment by mchnjt** [comment]
:flushed:

**Comment by SergueiKhadirov** [comment]
@nadir070 man plz tell me how you managed to run minecraft on pojav chromebook because i can't

**Comment by WesleyVanNeck** [comment]
> @nadir070 man plz tell me how you managed to run minecraft on pojav chromebook because i can't

i maneged with brunch a modifide chrome os

**Comment by SergueiKhadirov** [comment]
@LegacyGamerHD ok so i'm on a real chromebook you think i can run brunch on it?

**Comment by AustizzTDS** [comment]
> @nadir070 man plz tell me how you managed to run minecraft on pojav chromebook because i can't

just on the play store

**Comment by RealitySplitter95** [comment]
You know how to fix the fps mouse when you download a forge or optifine?

**Comment by Mathias-Boulay** [comment]
#648 already exists, and as stated the scrolling is not in the play store release.
Closing the issue.
