### ISSUE TITLE
Todo va lento

### ISSUE THREAD

**Issue by GroundGustavo** [PojavLauncherTeam/PojavLauncher#1445]
Porqué todos los animales van lento, también la tnt,y también el mapa carga lento,no se si habría una solución para mi problema

**Comment by mchnjt** [comment]
> Porqué todos los animales van lento, también la tnt,y también el mapa carga lento,no se si habría una solución para mi problema

k

**Comment by khanhduytran0** [comment]
@GroundGustavo no english
