### ISSUE TITLE
[BUG] (zink)unable to enter the game

### ISSUE THREAD

**Issue by VhiVhi789** [PojavLauncherTeam/PojavLauncher#1447]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
When I tried to launch the game with the Zink renderer, it didn't seem to load properly.
Please watch the video

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Click to start the game
3. Flash back to the main screen

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

https://user-images.githubusercontent.com/84970164/120025944-f8790080-c023-11eb-9757-9db5a0cde2a8.mp4

**Platform:**
 - Device Model Mi 11
 - CPU architecture aarch64 (64-bit)
 - Android Version andruid 11
 - PojavLauncher Version 3.3.1.1(zink)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by CriticalRange** [comment]
Zink is not supported for issues, this will definitely close. You would have knew it.

**Comment by WesleyVanNeck** [comment]
Don't use zink

**Comment by VhiVhi789** [comment]
But I want to experience it, so how can I use Zink correctly?

Please help me.

**Comment by WesleyVanNeck** [comment]
> But I want to experience it, so how can I use Zink correctly?
> 
> Please help me.

No support

**Comment by VhiVhi789** [comment]
sad...
So are you going to give up the project?

**Comment by CriticalRange** [comment]
> sad...
> So are you going to give up the project?

Just be patient, you don't have to play the newest version.

**Comment by VhiVhi789** [comment]
OK,I always support updates to the PoJavLauncher version.

**Comment by mchnjt** [comment]
> But I want to experience it, so how can I use Zink correctly?
> 
> Please help me.

get your vram/cpu a vulkan layer

**Comment by khanhduytran0** [comment]
@VhiVhi789 you think the bug is reproducible on any devices? **fill the template**.

**Comment by secrecy4** [comment]
How can I support zink in my device.

**Comment by WesleyVanNeck** [comment]
> How can I support zink in my device.

You cant
