### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by MinecraftSuperFan** [PojavLauncherTeam/PojavLauncher#145]
Android 5.1

https://drive.google.com/file/d/1xcYnmRcBb49oifzyYAx0DRZLfrdrdyKw/view?usp=drivesdk

**Comment by khanhduytran0** [comment]
> Bạn cần có quyền truy cập

**Comment by MinecraftSuperFan** [comment]
?

**Comment by khanhduytran0** [comment]
I don't have access to link.

**Comment by MinecraftSuperFan** [comment]
https://drive.google.com/file/d/1xcYnmRcBb49oifzyYAx0DRZLfrdrdyKw/view?usp=drivesdk

**Comment by MinecraftSuperFan** [comment]
[https://drive.google.com/file/d/1xcYnmRcBb49oifzyYAx0DRZLfrdrdyKw/view?usp=drivesdk](123)
