### ISSUE TITLE
Unban

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1451]
Unban 798539000838619136 please, im very sorry. I promise i wont do bad things again. Thanks

**Comment by mchnjt** [comment]
Haha wtf this ain't a discord repo

**Comment by ebuild-1** [comment]
@LegacyGamerHD unban me please

**Comment by WesleyVanNeck** [comment]
No

**Comment by ebuild-1** [comment]
Please bro

**Comment by sasuke573** [comment]
Hey i have ban on the server you can unban me pls? I didn't notice the boomalts a friend gave me so I said let's see what you say

**Comment by GoneSubject** [comment]
> Hey i have ban on the server you can unban me pls? I didn't notice the boomalts a friend gave me so I said let's see what you say

1 accept it
2 this is still not a discord repo
