### ISSUE TITLE
Texture issues in order version

### ISSUE THREAD

**Issue by kianoii** [PojavLauncherTeam/PojavLauncher#1452]
How to fix this 
![Screenshot_2021-05-30-12-29-28-18_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/82488941/120092071-f0fc4900-c142-11eb-84ef-f81941b16758.jpg)

![Screenshot_2021-05-30-12-29-27-30_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/82488941/120092073-f22d7600-c142-11eb-8ece-ab59c3d8d8e2.jpg)
![Screenshot_2021-05-30-12-29-15-39_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/82488941/120092074-f2c60c80-c142-11eb-963e-9708642fd006.jpg)
![Screenshot_2021-05-30-12-29-10-11_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/82488941/120092075-f35ea300-c142-11eb-812a-9d0dcf9aefb0.jpg)
When I hit a mob

**Comment by rscDoesMoreTrolling** [comment]
It's an aarch64 bug. Redownload the version.

**Comment by kianoii** [comment]
What version

**Comment by rscDoesMoreTrolling** [comment]
~~any version you want.~~

**Comment by kianoii** [comment]
Pojavlauncher version or Minecraft version?

**Comment by rscDoesMoreTrolling** [comment]
Minecraft.

**Comment by kianoii** [comment]
It's not working

**Comment by kianoii** [comment]
😭😭😭😭😭

**Comment by rscDoesMoreTrolling** [comment]
**mf can't delete a (specific version) folder inside the version folder**

**Comment by khanhduytran0** [comment]
don't use gl4es 1.1.5 on 1.12.2 and below

**Comment by kianoii** [comment]
:(

**Comment by LegacyGamerHD** [comment]
Don't use gl4es 1.1.5
