### ISSUE TITLE
[Failed to login invalid session (try restart your game and launcher)] <2days ago before it happens i tried to enter blockmania server and it happened to me it's said failed to login invalid session restart your game i also have and mojang account but it's error plz fix>

### ISSUE THREAD

**Issue by gamerboy82yt** [PojavLauncherTeam/PojavLauncher#1453]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>Failed to login invalid session (restart your game and launcher)

**Comment by khanhduytran0** [comment]
@gamerboy82yt bruh it's not a cracked server

**Comment by khanhduytran0** [comment]
also if you have logged in using Mojang but enable offline then your email will be leaked as it's used as username since it's not actually login to account.

**Comment by khanhduytran0** [comment]
also you didn't filled the template, **we don't have an automatic log uploader**

**Comment by gamerboy82yt** [comment]
How to filled the template plz?

**Comment by mchnjt** [comment]
:trollface: 5 year old kids be like:

**Comment by khanhduytran0** [comment]
> 
> 
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> 
> <br>
> 
> - Make sure there was not duplicated issues.<br>
> 
> - Make sure you have filled this issue template, or this will get rejected.
> 
> </details>
> 
> 
> 
> ### Describe the bug
> 
> A clear and concise description of what the bug is.
> 
> 
> 
> **Add a log file if you want to see your bug fixed !**
> 
> 
> 
> The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
> 
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> 
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> 
> 
> ### To Reproduce:
> 
> Indicate steps to reproduce the buggy behavior:
> 
> 
> 
> 1. Start PojavLauncher
> 
> ... *(your set of actions to reproduce the bug)*
> 
> 
> 
> ### Expected behavior:
> 
> I expected ...
> 
> 
> 
> ### Screenshots or videos:
> 
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> 
> 
> 
> **Platform:**
> 
>  - Device Model [e.g. Mi 8 Pro 8/128]
> 
>  - CPU architecture [e.g. aarch64] 
> 
>  - Android Version [e.g. 10]
> 
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> 
> 
> 
> <details> <summary><b>Additional context</b></summary>
> 
> <br>
> 
> <pre>
> 
> Add any other context about the problem here.
> 
> </pre>
> 
> </details>Failed to login invalid session (restart your game and launcher)
> 
> 


@gamerboy82yt how to read this :trollface:
