### ISSUE TITLE
I connect physical keyboard and when ever I press ctrl+space+w my player stop moving And when ever I press shift+w it just floting window I can't see anything pls fix

### ISSUE THREAD

**Issue by Amanjat** [PojavLauncherTeam/PojavLauncher#1455]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

![Screenshot_20210530-122035](https://user-images.githubusercontent.com/83133507/120095094-88609c80-c141-11eb-9639-fc5d7c4d5de6.jpg)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

> `
![Screenshot_20210530-122018](https://user-images.githubusercontent.com/83133507/120095089-7ed73480-c141-11eb-9ae8-55ecae455b11.jpg)
`

**Comment by mchnjt** [comment]
that doesn't make any sense

**Comment by khanhduytran0** [comment]
Duplicate of #982

**Comment by Amanjat** [comment]
Bro I figured it out it becz of keyboad assistant my mobile is one puls 7t and I can't turn it off like some mobile treat right button as a back button same as that same problem with Samsung pls fix

**Comment by khanhduytran0** [comment]
>  I can't turn it off like some mobile treat right button as a back button

@Amanjat have you checked the opposite option on launcher settings?

**Comment by Amanjat** [comment]
@khanhduytran0 where is opposite option on launcher?
I can't find
