### ISSUE TITLE
[BUG] the screen can not be moved and also the cursor

### ISSUE THREAD

**Issue by kwrydd** [PojavLauncherTeam/PojavLauncher#1457]
### Describe the bug
So in all versions of minecraft it can't be moved at all, I've tried various methods that I know ... but the results can't, can you fix this.

**Add a log file if you want to see your bug fixed !**https://pastebin.com/raw/Xc24Gb5n

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

-open pojavlauncher
-select the version
-There is a mojang logo display
-The cursor cannot be moved
-In the game, the screen cannot be moved

### Screenshots or videos:
Can not

**Platform:**0
 - Device Model [e.g. samsung A12/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by mchnjt** [comment]
> 
> 
> ### Describe the bug
> So in all versions of minecraft it can't be moved at all, I've tried various methods that I know ... but the results can't, can you fix this.
> 
> **Add a log file if you want to see your bug fixed !**https://pastebin.com/raw/Xc24Gb5n
> 
> The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> -
> 
> ### Screenshots or videos:
> Can not
> 
> **Platform:**0
>  - Device Model [e.g. samsung A12/128]
>  - CPU architecture [e.g. aarch64] 
>  - Android Version [e.g. 10]
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> <details> <summary><b>Additional context</b></summary>
> <br>
> <pre>
> Add any other context about the problem here.
> </pre>
> </details>
> 

@kwrydd pastebin :trollface:

**Comment by khanhduytran0** [comment]
bruh duplicate

**Comment by mchnjt** [comment]
remove E.G

**Comment by khanhduytran0** [comment]
@kwrydd 
> ##Screenshots or videos:
Can not

why?

**Comment by khanhduytran0** [comment]
> PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

is it?

**Comment by kwrydd** [comment]
> @kwrydd
> 
> > ##Screenshots or videos:
> > Can not
> 
> why?

My phone button is broken

**Comment by khanhduytran0** [comment]
Then can you still record a video?

**Comment by kwrydd** [comment]
> Then can you still record a video?

Yes,brb

**Comment by khanhduytran0** [comment]
also enable mouse debug and see

**Comment by khanhduytran0** [comment]
> > PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> is it?

is it installed version?????

**Comment by kwrydd** [comment]
> > > PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> > 
> > 
> > is it?
> 
> is it installed version?????

Yes

**Comment by kwrydd** [comment]
From gplay

**Comment by khanhduytran0** [comment]
Are you sure? go to device settings and check :eyes:

**Comment by kwrydd** [comment]
> Are you sure? go to device settings and check 👀
That version is correct

**Comment by kwrydd** [comment]
> also enable mouse debug and see

where do i activate it

**Comment by mchnjt** [comment]
> @kwrydd 
> > ##Screenshots or videos:
> Can not
> 
> why?

imagine 'i can't screenshot'

**Comment by mchnjt** [comment]
> > also enable mouse debug and see
> 
> where do i activate it

![Screenshot_20210531-191754~2.png](https://user-images.githubusercontent.com/83752061/120185648-11acc780-c245-11eb-8be9-70789660483c.png)

**Comment by mchnjt** [comment]
![Screenshot_20210531-192053~2.png](https://user-images.githubusercontent.com/83752061/120186169-b7603680-c245-11eb-86ab-eb5437067348.png)

*virtual mouse

**Comment by kwrydd** [comment]
> ![Screenshot_20210531-192053~2.png](https://user-images.githubusercontent.com/83752061/120186169-b7603680-c245-11eb-86ab-eb5437067348.png)
> 
> *virtual mouse

Ok,thanks

**Comment by Mathias-Boulay** [comment]
Closing this duplicate, since the original issue have more useful data to work with.
Original : #1235
