### ISSUE TITLE
error unicode. because of the, mod create

### ISSUE THREAD

**Issue by nolil** [PojavLauncherTeam/PojavLauncher#1458]
![Screenshot_2021-05-31-21-51-52-812_net kdt pojavlaunch](https://user-images.githubusercontent.com/71793723/120235407-96f2a500-c262-11eb-84fe-6e8eee77dad9.jpg)
how to fix it, tell me if you know

**Comment by khanhduytran0** [comment]
> how to fill the template instead of rip it

**Comment by nolil** [comment]
log: https://drive.google.com/file/d/11gOtw0pw7YZldQrDMuQb8MT0hIeZBQrq/view?usp=drivesdk

**Comment by nolil** [comment]
I checked several versions of the mod, and forge 1.15.2-1.16.5. without mods, but crashes.

**Comment by khanhduytran0** [comment]
Create mod uses shaders, which is not supported currently.

**Comment by nolil** [comment]
ok, how long to wait
