### ISSUE TITLE
[BUG] <Can't Install Forge 1.12.2 14.23.4.2759>

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#1459]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

Can't install forge 1.12.2 - 14.23.4.2759

**Add a log file if you want to see your bug fixed !**

[forge-1.12.2-14.23.4.2759-installer.jar.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6572890/forge-1.12.2-14.23.4.2759-installer.jar.log)

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Install forge

### Expected behavior:
I expected that i can install forge with no problems.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

https://user-images.githubusercontent.com/78906627/120256811-86254c00-c2c1-11eb-968f-243880f47fe9.mp4

**Platform:**
 - Device Model: CPH1853/OPPO A12e
 - CPU architecture: aarch64
 - Android Version: 8.1
 - PojavLauncher Version: version 3.3.1.1_rel_20210530

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Plz solve my problem 🙏🙏🙏.
</pre>
</details>

**Comment by LanceAldrei04** [comment]
### Hey, someone can solve this freaking bug?

**Comment by mchnjt** [comment]
Duplicate of #1465.
