### ISSUE TITLE
Unable to connect to servers

### ISSUE THREAD

**Issue by XDLang** [PojavLauncherTeam/PojavLauncher#146]
I am on a Samsung Galaxy s20 and can't seem to get the app to connect to servers. I have tried many builds of the app and still nothing... also, when you try to type in a server IP, nothing happens. I had to copy my servers.dat file from my pc just so Pojav can see it but can't connect...

**Comment by khanhduytran0** [comment]
> can't seem to get the app to connect to servers.

Some servers with encryption may not connected.

> when you try to type in a server IP, nothing happens.

Try GBoard, key input will work.

**Comment by WesleyVanNeck** [comment]
use up to 1.13

**Comment by ssaagamemer** [comment]
Or use a right ip server (can play a offline server only at now)

**Comment by khanhduytran0** [comment]
Use v3.
