### ISSUE TITLE
Ko thể chơi SV mcfamily

### ISSUE THREAD

**Issue by Joakdnhio** [PojavLauncherTeam/PojavLauncher#1460]
Mình đã hỏi amin SV rồi thì bảo lỗi mạng  mình chuyển mạng Theo amin nói rồi nhưng không được

**Comment by Joakdnhio** [comment]
https://youtu.be/L_3fJchhjBs

**Comment by khanhduytran0** [comment]
Cũng không chịu sửa đổi cái tật RIP cái mẫu lỗi là sao

**Comment by khanhduytran0** [comment]
> Cũng không chịu sửa đổi cái tật RIP cái mẫu lỗi là sao

@Joakdnhio

**Comment by Joakdnhio** [comment]
RIP là gì

**Comment by Joakdnhio** [comment]
Máy chủ : SV.mcfamily.vn

**Comment by Joakdnhio** [comment]
Trần Thánh Duy ơi có cách nào để vào được sv mcfamily không vậy
