### ISSUE TITLE
[BUG] i can't type "@"

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1462]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I can't type "@" help :l

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6575758/latestlog.txt)

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Login to lunar.gg server
3. And i type "@" in chat
4. And don't work

... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_2021-06-01-18-04-14-65_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/70785472/120313331-02408380-c304-11eb-8802-964d70a70f35.jpg)

**Platform:**
 - Device Model Oppo A1K 2/32 [e.g. Mi 8 Pro 8/128]
 - CPU architecture Aarch64[e.g. aarch64] 
 - Android Version 9 [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by ghost** [comment]
Dev help me
@everyone ehe :3

**Comment by khanhduytran0** [comment]
bruh duplicate of #1047

**Comment by khanhduytran0** [comment]
Duplicate of #1047

**Comment by mchnjt** [comment]
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> <br>
> - Make sure there was not duplicated issues.<br>
> - Make sure you have filled this issue template, or this will get rejected.
> </details>
> 
> ### Describe the bug
> I can't type "@" help :l
> 
> **Add a log file if you want to see your bug fixed !**
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6575758/latestlog.txt)
> 
> The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> 2. Login to lunar.gg server
> 3. And i type "@" in chat
> 4. And don't work
> 
> 
> ... *(your set of actions to reproduce the bug)*
> 
> ### Expected behavior:
> I expected ...
> 
> ### Screenshots or videos:
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> ![Screenshot_2021-06-01-18-04-14-65_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/70785472/120313331-02408380-c304-11eb-8802-964d70a70f35.jpg)
> 
> **Platform:**
>  - Device Model Oppo A1K 2/32 [e.g. Mi 8 Pro 8/128]
>  - CPU architecture Aarch64[e.g. aarch64] 
>  - Android Version 9 [e.g. 10]
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> <details> <summary><b>Additional context</b></summary>
> <br>
> <pre>
> Add any other context about the problem here.
> </pre>
> </details>
> 

1.8 keybinds /shrug
