### ISSUE TITLE
[F-REQ] Add support for physical keyboard and mouse

### ISSUE THREAD

**Issue by shadichy** [PojavLauncherTeam/PojavLauncher#1463]
**Is your feature request related to a problem? Please describe.**
Oneday, i had a usb type c - multiports converter, and i plugged my keyboard and mouse in, how can i make them work in pojav? 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WesleyVanNeck** [comment]
already inplemented

**Comment by WesleyVanNeck** [comment]
also fill the template
