### ISSUE TITLE
[BUG] forge not install on 1.12.2

### ISSUE THREAD

**Issue by kinsley12** [PojavLauncherTeam/PojavLauncher#1465]
I cant install forge 1.12.2 on your App
[Yere is the vidéo](https://youtu.be/pCmVdDE0YOE)

**Comment by mchnjt** [comment]
> I cant install forge 1.12.2 on your App
> [Yere is the vidéo](https://youtu.be/pCmVdDE0YOE) 

First, fill the template.

In my case, i **can't install some old version of Forge 1.12.2**, and yes it is painful for me cuz i can't use optifine, but there's some alternatives. As of right now, **you can only install latest forge versions in PojavLauncher**.
