### ISSUE TITLE
no controller support ADD PLEASE

### ISSUE THREAD

**Issue by drybones64** [PojavLauncherTeam/PojavLauncher#1466]
WTF WTF JUST ADD IT ALREADY LIKE WTF BRO MY 2GB RAM PHONE ALSO HAS ISSUE RAMING THE GAME PLZ HELP

**Comment by rscDoesMoreTrolling** [comment]
> WTF WTF JUST ADD IT ALREADY LIKE WTF BRO MY 2GB RAM PHONE ALSO HAS ISSUE RAMING THE GAME PLZ HELP

Can you:
- redefine your context
- rephrase your question
- repost the fixed question
- fill the template
- grammar

**Comment by CriticalRange** [comment]
> > WTF WTF JUST ADD IT ALREADY LIKE WTF BRO MY 2GB RAM PHONE ALSO HAS ISSUE RAMING THE GAME PLZ HELP
> 
> Can you:
> 
> * redefine your context
> * rephrase your issue
> * repost the fixed issue
> * fill the template
> * grammar

They never will, but a good try !

**Comment by CriticalRange** [comment]
> WTF WTF JUST ADD IT ALREADY LIKE WTF BRO MY 2GB RAM PHONE ALSO HAS ISSUE RAMING THE GAME PLZ HELP

"ADD IT ALREADY" they say. If it's easy, then you add it!
