### ISSUE TITLE
ERROR - Unable to fix RSAPadding. You can't play premium servers.

### ISSUE THREAD

**Issue by XDLang** [PojavLauncherTeam/PojavLauncher#147]
When I launch any version of Minecraft, I get this. I cant join any server because it thinks I am a cracked user even though I logged in with my Minecraft account. Also, You can only connect to servers with a numberd IP... I am using a Galaxy s20 android 10

**Comment by khanhduytran0** [comment]
This is a warning you can ignore if you don't play premium servers.

**Comment by ZH-XiJun** [comment]
I have same error, either

**Comment by khanhduytran0** [comment]
It's warning!
