### ISSUE TITLE
how did I add ram to phone 1 or 4 GB ram idk[BUG] <Short description>

### ISSUE THREAD

**Issue by drybones64** [PojavLauncherTeam/PojavLauncher#1475]
OK so imma legit 20 year old how did I know how much ram I have

**Comment by rscDoesMoreTrolling** [comment]
> OK so imma legit 20 year old how did I know how much ram I have

:trollface: take your computer classes, man.

**Comment by rscDoesMoreTrolling** [comment]
> OK so imma legit 20 year old how did I know how much ram I have

:trollface: take your computer classes, man.

**Comment by LegacyGamerHD** [comment]
Stop spamming the issue tracker
