### ISSUE TITLE
[F-REQ] Add Java 16 For Android

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1476]
**Is your feature request related to a problem? Please describe.**
For Minecraft 1.17 Pre Release And Optimize To Games

**Describe the solution you'd like**
I can't use Android CI dude

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
First, we need OpenGL 3.2, java 16 is planned.

**Comment by ghost** [comment]
Bruh opengl es 3.2 ≠ opengl 3.2

**Comment by khanhduytran0** [comment]
> Bruh opengl es 3.2 ≠ opengl 3.2

bruhhhh I said OpenGL 3.2 not ES

**Comment by khanhduytran0** [comment]
yeah mesa Zink is an option but it's very buggy and slow

**Comment by ghost** [comment]
But Mesa zink only work in Mali cpu
And i'm using mediatek

**Comment by ghost** [comment]
Bruh reopen

**Comment by subhu2008** [comment]
Hey when OpenJDK 16 and Open gl 3.2 for 1.17 will be released for pojav launcher

**Comment by mchnjt** [comment]
> Hey when OpenJDK 16 and Open gl 3.2 for 1.17 will be released for pojav launcher

Exact Date: JanCember 31, 2077

**Comment by ghost** [comment]
Ok close issue

**Comment by khanhduytran0** [comment]
lmao

**Comment by ghost** [comment]
Me : Close

Dev : open

Me : close again

Dev : open again

Stop fk

**Comment by Dhyan10** [comment]
> yeah mesa Zink is an option but it's very buggy and slow

But In my mobile it works perfectly

**Comment by dolphin-cat** [comment]
u sure we dont have opengl 16 yet? cuz if we didnt then mc 1.17 on pc java wouldn't work either right?

**Comment by ajit850** [comment]
> > yeah mesa Zink is an option but it's very buggy and slow
> 
> But In my mobile it works perfectly

How

**Comment by Abdulhadi5692HDI** [comment]
Well you can download java 17 jre for your device (CHECK YOU ARCHUITURS)
