### ISSUE TITLE
Zink

### ISSUE THREAD

**Issue by Epoy266** [PojavLauncherTeam/PojavLauncher#1478]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
A clear and concise description of what the bug is. Crashing When you click play, Using Zink Renderer

**Add a log file if you want to see your bug fixed !** https://drive.google.com/file/d/1Kl7h2DO1VMYvZcgBynLvcpLbq32jMvDm/view?usp=drivesdk

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [Vivo V7+ (4/64)]
 - CPU architecture [aarch64] 
 - Android Version [8.1.0]
 - PojavLauncher Version [Zink version 3.3.1.1 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
My Phone Is Vulkan Supported
### 

- ****

**Comment by mchnjt** [comment]
gay.
