### ISSUE TITLE
Still not work (3.0.0 Preview 3)

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#148]
![Screenshot_20200427_151739_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/80376670-76575f00-889a-11ea-8616-d1dbb6e0817f.jpg)
Bad system call again! :(

**Comment by khanhduytran0** [comment]
Why not re-open old one?

**Comment by Azapru** [comment]
> Why not re-open old one?

What?

**Comment by Azapru** [comment]
Idk

**Comment by khanhduytran0** [comment]
Why don't you re-open #144 instead of create a new issue?

**Comment by khanhduytran0** [comment]
Or track #140 because duplicate.

**Comment by Azapru** [comment]
I don't know. :/

**Comment by khanhduytran0** [comment]
Do you have Close/Reopen issue button under the text box?

**Comment by Azapru** [comment]
I see only "close issue"

**Comment by khanhduytran0** [comment]
@artdeell I added `proot -0` to fake root to fix `Bad system call`, but anything wrong?

**Comment by CosineMath** [comment]
"Bad system call" error is related to the security restirction on Android 8.0 and above :

> Android 8.0 (API level 26) applies a Secure Computing (SECCOMP) filter to all apps. The list of allowed syscalls is restricted to those exposed through bionic. Although there are several other syscalls provided for backwards compatibility, we recommend against their use. 


That's why MCinabox don't use any packages built with glibc.

**Comment by khanhduytran0** [comment]
> "Bad system call" error is related to the security restirction on Android 8.0 and above :

But what about https://github.com/MasterDevX/Termux-Java/issues/3#issuecomment-548679532?
May I set `targetSdkVersion` down to 25...?

**Comment by CosineMath** [comment]
Setting the `targetSdkVersion` seems to not work around the security filter. 

Zhuowei has tried to work around the filter by hooking up the syscalls (https://github.com/zhuowei/Boardwalk/commit/f4401018182867502edcff2ace8cfcfe1427fed3). (But may not work fine, so Zhuowei abandoned Boardwalk 1.9 and developed Boardwalk 2.0 using openjdk-9-mobile rather than oracle jdk used in 1.9)

**Comment by Azapru** [comment]
I found next errors in preview 3:
![Screenshot_20200428_071917_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/80449943-aa756300-8920-11ea-8062-02fe4fc8c448.jpg)
** Delete leaked account!!!! **
![Uploading Screenshot_20200428_071934_net.kdt.pojavlaunch.jpg…]()

**Comment by khanhduytran0** [comment]
> I found next errors in preview 3:
> ![Screenshot_20200428_071917_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/80449943-aa756300-8920-11ea-8062-02fe4fc8c448.jpg)
** Delete leaked account **
> ![Uploading Screenshot_20200428_071934_net.kdt.pojavlaunch.jpg…]()
> 

Still `Bad system call` so you can't install Forge or anything.

**Comment by khanhduytran0** [comment]
Your image containing some account ID which someone can access to, so I deleted.

**Comment by Azapru** [comment]
Ok :0

**Comment by Azapru** [comment]
What is this?
![Screenshot_20200428_073145_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/80450655-4bb0e900-8922-11ea-898e-015a98adc089.jpg)

**Comment by khanhduytran0** [comment]
... Can you press back?

**Comment by Azapru** [comment]
Yes

**Comment by khanhduytran0** [comment]
@CosineMath I see on https://github.com/termux/proot/issues/22 that say Termux's PRoot has SECCOMP patch with just use `proot -0` to bypass SECCOMP.

**Comment by khanhduytran0** [comment]
Use v3.2
