### ISSUE TITLE
For the feature

### ISSUE THREAD

**Issue by romeoga05** [PojavLauncherTeam/PojavLauncher#1480]
Plsssss make Controller Support or a Mod With Controller Support

**Comment by rscDoesMoreTrolling** [comment]
The team will NEVER, EVER make it, as in minecraft, you can move using WASD keys.

**Comment by WesleyVanNeck** [comment]
> The team will NEVER, EVER make it, as in minecraft, you can move using WASD keys.

it s in works stop spreading fake news

**Comment by mchnjt** [comment]
oh, sorry

**Comment by WesleyVanNeck** [comment]
proof https://github.com/Mathias-Boulay/PojavLauncher/blob/virtual_controller_revamp/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/customcontrols/gamepad/Gamepad.java

**Comment by drybones64** [comment]
Will this be a thing before July?

**Comment by romeoga05** [comment]
and how do i get that?
