### ISSUE TITLE
Textures are bugged in my modpack I built

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#1482]
The textures are bugged for some things in my modpack, is there a way to fix this?

![Screenshot_20210604-193417](https://user-images.githubusercontent.com/63871578/120849991-c0ffdc00-c56e-11eb-8e4f-edf1ca194f8a.jpg)
![Screenshot_20210604-193340](https://user-images.githubusercontent.com/63871578/120850008-c52bf980-c56e-11eb-8e0a-ea0a4c3f0a3a.jpg)
![Screenshot_20210604-193404](https://user-images.githubusercontent.com/63871578/120850017-c9581700-c56e-11eb-9ecb-382c721dface.jpg)

**Comment by khanhduytran0** [comment]
Fill the template first. screenshot provide nothing other than bug itself. Do we have __your modpack__ to reproduce the bug?
