### ISSUE TITLE
GUYS WE SHOULD ALL SHUT TF UP WITH THE USELESS SUGGESTIONS LIKE CONTROLLER SUPPORT SO THEY HAVE MORE TIME TO MAKE IT INSTEAD OF WASTEING TIME HERE

### ISSUE THREAD

**Issue by drybones64** [PojavLauncherTeam/PojavLauncher#1483]
GUYS WE SHOULD ALL SHUT TF UP WITH THE USELESS SUGGESTIONS LIKE CONTROLLER SUPPORT SO THEY HAVE MORE TIME TO MAKE IT INSTEAD OF WASTEING TIME HERE

**Comment by Mathias-Boulay** [comment]
And yet I'm here wasting my time closing issues that aren't issues.
*I mean the intention was nice, the execution leave to be desired.*
