### ISSUE TITLE
[BUG] Item textures are pixelated and bugged

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#1487]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
The textures for the tools are broken and are pixelated

Log file:
In comments

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Run forge with my modpack

### Expected behavior:
I expected the textures to look like normal Minecraft 

### Screenshots or videos:
In comments

**Platform:**
 - Device Model [Huawei Y7 2019]
 - CPU architecture [aarch64] 
 - Android Version [8.1.0]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by leetmussc** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6602264/latestlog.txt)

**Comment by leetmussc** [comment]
![Screenshot_20210604-193340](https://user-images.githubusercontent.com/63871578/120886407-b16faa00-c5e5-11eb-8794-1c8d7d0824a9.jpg)

**Comment by khanhduytran0** [comment]
these info aren’t enough. look at issue template, it still empty

**Comment by khanhduytran0** [comment]
once you filled I will reopen

**Comment by khanhduytran0** [comment]
ok

**Comment by khanhduytran0** [comment]
but stills, what’s your modpack?

**Comment by khanhduytran0** [comment]
we don’t have your modpack, so unable to reproduce

**Comment by khanhduytran0** [comment]
@leetmussc hello?

**Comment by leetmussc** [comment]
Hi

**Comment by leetmussc** [comment]
I've filled the template...

**Comment by khanhduytran0** [comment]
but how we reproduce if we don't have your modpack
Also graphical problems may not be fixed as we are not graphics developer.

**Comment by Mathias-Boulay** [comment]
The issue is device specific, it is due to a lack of VRAM
