### ISSUE TITLE
[BUG] <BlackScreen on Osmesadevtest>

### ISSUE THREAD

**Issue by Epoy266** [PojavLauncherTeam/PojavLauncher#1489]
<> <><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

Not Crashing but Its Black Screen I wait for about 5mins but its still black 

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6602678/latestlog.txt)

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [Vivo V7+]
 - CPU architecture [aarch64] 
 - Android Version [8.1.0]
 - PojavLauncher Version [OSMesadevtest ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
I took a screenshot of the log file and its says that using vulkan Renderer

> 
![Screenshot_2021_0605_215136](https://user-images.githubusercontent.com/85331172/120895009-b2d4bd00-c64d-11eb-9d0b-0a4cc03f2e52.jpg)

**Comment by WesleyVanNeck** [comment]
No support
