### ISSUE TITLE
Opengl 3.2

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1490]
Hey,pojav Dev's plse add the option of opengl 3.2 as u have done with Zink.

The reason-The reason is simple,my mobile device only supports opengl upto 3.2 and I wanna play mc java 1.17 without crash but the Zink version which exports opengl 4.6 is not supported by my device and opengl 2.1 is too low for 1.17 to run,I think this could help a lot of people who wanted to run 1.17 without Zink and would also help me a lot,so plse add this feature to pojav launcher.

I would be glad if u add this🤗🤗

If u had added it plse tell me so that I can get it

**Comment by WesleyVanNeck** [comment]
i don't think you understand what your your phone suppurts opengl es not opengl
