### ISSUE TITLE
Could you add some new control to make easy to move like this?

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1491]
Could you add some new control to make easy to move like this?
![IMG_20210606_123552](https://user-images.githubusercontent.com/76839710/120912705-27e2d980-c6c4-11eb-9357-302f43908f98.jpg)

Full
![Screenshot_2021-06-06-12-34-51-905_com google android youtube](https://user-images.githubusercontent.com/76839710/120912710-3204d800-c6c4-11eb-8fe0-266b344c48b1.jpg)

**Comment by mchnjt** [comment]
fuckin' mcinabox

**Comment by WesleyVanNeck** [comment]
were not gone copy mcinabox
