### ISSUE TITLE
 [F-REQ] pls add back "profile version"

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1492]
**Is your feature request related to a problem? Please describe.**
I need "profile versions" it was very good but you guys didn't continue that build

**Describe the solution you'd like**
I can't use Android CI 🗿.

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
Pls add or

https://c.tenor.com/yGvz_rGv1lIAAAAM/stickroll-rickroll.gif

**Comment by ghost** [comment]
![stickroll-rickroll](https://user-images.githubusercontent.com/70785472/120913439-6e830480-c6c1-11eb-81d2-2b9aa6718f76.gif)

**Comment by khanhduytran0** [comment]
![image](https://user-images.githubusercontent.com/40482367/120913476-a8540b00-c6c1-11eb-9790-990e557f911a.jpeg)

bruh

**Comment by ghost** [comment]
Add profile build?

**Comment by rscAvePlex** [comment]
wdym profile build

**Comment by CriticalRange** [comment]
> Add profile build?

It had so many problems, that's why it got removed. If you want it to come back you can! Just clone the repo and switch the branch to "profiles" and build. Though the priority of devs is in Zink Mesa so don't expect in near future

**Comment by ghost** [comment]
I cant use Android ci
And i can't use java

Bruh
