### ISSUE TITLE
crash while installing mod in the jvm (forge wurst and fabric API)

### ISSUE THREAD

**Issue by friendcraft500** [PojavLauncherTeam/PojavLauncher#1493]
well it crash when I installing mod

<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms900m -Xmx900m"
AWT-enabled version detected! (20100729)
--------- beginning of main
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (14629): WARNING: linker: Warning: "
I/jrelog  (14629): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): 
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): 
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so
I/jrelog  (14629): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (14629):  (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so" has unsupported flags DT_FLAGS_1=
I/jrelog  (14629): 0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so
I/jrelog  (14629): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
I/jrelog  (14629): WARNING: linker: Warning: "
I/jrelog  (14629): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so" has unsupported flags DT_FLAGS_1=
I/jrelog  (14629): 0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success
I/jrelog  (14629): WARNING: linker: Warning: "
I/jrelog  (14629): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
I/jrelog  (14629): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so
I/jrelog  (14629): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14629): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success
I/jrelog  (14629): dlopen /data/app/net.kdt.pojavlaunch-RGOHBFM1uuTmSvXILjNMWw==/lib/arm/libopenal.so success
I/jrelog  (14629): dlopen /data/app/net.kdt.pojavlaunch-RGOHBFM1uuTmSvXILjNMWw==/lib/arm/libgl04es.so success
I/jrelog  (14629): Done processing args
I/jrelog  (14629): Found JLI lib
I/jrelog  (14629): Calling JLI_Launch
I/jrelog  (14629): OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/jrelog  (14629): 
I/jrelog  (14629): May 23, 2021 5:15:53 AM net.minecraft.launchwrapper.LogWrapper log
I/jrelog  (14629): INFO: Using tweak class name net.minecraft.launchwrapper.VanillaTweaker
I/jrelog  (14629): May 23, 2021 5:15:54 AM net.minecraft.launchwrapper.LogWrapper log
I/jrelog  (14629): INFO: Launching wrapped minecraft
I/jrelog  (14629): CacioComponentPeer::setZOrder: NOT YET IMPLEMENTED
I/jrelog  (14629): 
I/jrelog  (14629): 28
I/jrelog  (14629): 
I/jrelog  (14629): Turning of ImageIO disk-caching
I/jrelog  (14629): 
I/jrelog  (14629): Loading current icons for window from: /storage/emulated/0/games/PojavLauncher/.minecraft/assets/icons/icon_16x16.png and /storage/emulated/0/games/PojavLauncher/.minecraft/assets/icons/icon_32x32.png
I/jrelog  (14629): 
I/jrelog  (14629): javax.imageio.IIOException: Can't read input file!
I/jrelog  (14629): 
I/jrelog  (14629): 	at javax.imageio.ImageIO.read(ImageIO.java:1302)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.loadIcon(VanillaTweakInjector.java:130)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.loadIconsOnFrames(VanillaTweakInjector.java:107)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.inject(VanillaTweakInjector.java:94)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.client.Minecraft.main(SourceFile:1364)
I/jrelog  (14629): 
I/jrelog  (14629): 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
I/jrelog  (14629): 
I/jrelog  (14629): 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
I/jrelog  (14629): 
I/jrelog  (14629): 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
I/jrelog  (14629): 
I/jrelog  (14629): 	at java.lang.reflect.Method.invoke(Method.java:498)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
I/jrelog  (14629): 
I/jrelog  (14629): Setting gameDir to: /storage/emulated/0/games/PojavLauncher/.minecraft
I/jrelog  (14629): 
I/jrelog  (14629): [LWJGL] Failed to load a library. Possible solutions:
I/jrelog  (14629): 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
I/jrelog  (14629): 	b) Add the JAR that contains the shared library to the classpath.
I/jrelog  (14629): 
I/jrelog  (14629): [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
I/jrelog  (14629): 
I/jrelog  (14629): [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
I/jrelog  (14629): 
I/jrelog  (14629): EGLBridge: Initializing
I/jrelog  (14629): EGLBridge: Initialized!
I/jrelog  (14629): EGLBridge: ThreadID=14791
I/jrelog  (14629): EGLBridge: EGLDisplay=0x1, EGLSurface=0xb171f8a0
I/jrelog  (14629): Created CTX pointer = 0xb172d2c0
I/jrelog  (14629): java.lang.Exception: Trace exception
I/jrelog  (14629): 
I/jrelog  (14629): 	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:948)
I/jrelog  (14629): 
I/jrelog  (14629): 	at org.lwjgl.opengl.Display.create(Display.java:416)
I/jrelog  (14629): 
I/jrelog  (14629): 	at org.lwjgl.opengl.Display.<clinit>(Display.java:89)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.client.Minecraft.a(SourceFile:149)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.client.Minecraft.run(SourceFile:556)
I/jrelog  (14629): 
I/jrelog  (14629): 	at java.lang.Thread.run(Thread.java:748)
I/jrelog  (14629): 
I/jrelog  (14629): Making current on window 0xffffffff
I/jrelog  (14629): Making current on window 0xffffffff
I/jrelog  (14629): Grab: false
I/jrelog  (14629): 
I/jrelog  (14629): Created CTX pointer = 0xb17b32c0
I/jrelog  (14629): java.lang.Exception: Trace exception
I/jrelog  (14629): 
I/jrelog  (14629): 	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:948)
I/jrelog  (14629): 
I/jrelog  (14629): 	at org.lwjgl.opengl.Display.create(Display.java:416)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.client.Minecraft.a(SourceFile:165)
I/jrelog  (14629): 
I/jrelog  (14629): 	at net.minecraft.client.Minecraft.run(SourceFile:556)
I/jrelog  (14629): 
I/jrelog  (14629): 	at java.lang.Thread.run(Thread.java:748)
I/jrelog  (14629): 
I/jrelog  (14629): Making current on window 0xffffffff
I/jrelog  (14629): 
I/jrelog  (14629): Starting up SoundSystem...
I/jrelog  (14629): 
I/jrelog  (14629): Initializing LWJGL OpenAL
I/jrelog  (14629): 
I/jrelog  (14629):     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
I/jrelog  (14629): 
I/jrelog  (14629): [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
I/jrelog  (14629): OpenAL initialized.
I/jrelog  (14629): 
I/jrelog  (14629): 
I/jrelog  (14629): Toggle fullscreen!
I/jrelog  (14629): 
I/jrelog  (14629): Created CTX pointer = 0xd75ab040
I/jrelog  (14629): LWJGLX: switch fullscreen to true
I/jrelog  (14629): 
I/jrelog  (14629): Grab: true
I/jrelog  (14629): Grab: false
I/jrelog  (14629): Size: 1545, 720**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:https://youtu.be/tDzF6nGifWE
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by friendcraft500** [comment]
This is proof video:https://youtu.be/tDzF6nGifWE
Fabric:https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by WesleyVanNeck** [comment]
> This is proof video:https://youtu.be/tDzF6nGifWE

Copy the full log also a video isn't helpful

**Comment by EXPress-016** [comment]
> This is proof video:https://youtu.be/tDzF6nGifWE

Paste that in mods folder and that is for fabric
