### ISSUE TITLE
Клавиатура при включении сама просто берёт и выключается

### ISSUE THREAD

**Issue by Recasat** [PojavLauncherTeam/PojavLauncher#1494]
Когда я нажимаю на кнопку KEYBOARD ⌨️ ,она у меня включается, но где-то через секунды 3-4 она резко пропадает, и так каждый раз

**Comment by nolil** [comment]
> Когда я нажимаю на кнопку KEYBOARD ⌨️ ,она у меня включается, но где-то через секунды 3-4 она резко пропадает, и так каждый раз

подержываю

**Comment by ghost** [comment]
try turning off log output and try again

**Comment by nolil** [comment]
> try turning off log output and try again

I don't use it, but I tried it and it didn't work

**Comment by ghost** [comment]
I don't know how to fix it maybe it's in the ram because the keyboard stops or something

**Comment by nolil** [comment]
> I don't know how to fix it maybe it's in the ram because the keyboard stops or something

yes, it stops when you don't select a recording location, it disappears

**Comment by nolil** [comment]
@IceCreamUwU maybe @Recasat it's different for him

**Comment by Millisnt** [comment]
Texture are glitched help

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
