### ISSUE TITLE
keeps crashing when trying to load world, using any forge 1.13.+ versions 

### ISSUE THREAD

**Issue by natenmdemon** [PojavLauncherTeam/PojavLauncher#1497]
my game keeps crashing when im using a forge 1.13-1.16.5 versions I cant really give u a crash log, i cant find it neither is one created. the lastest one is 3 days ago.

**Comment by WesleyVanNeck** [comment]
No log no help

**Comment by WesleyVanNeck** [comment]
Also you ignored the template
