### ISSUE TITLE
The display is bad

### ISSUE THREAD

**Issue by Smolbeans2** [PojavLauncherTeam/PojavLauncher#1498]
I play PojavLauncher on my tablet, but the display dosent fit my screen. so i have to use a magnify tool or something

**Comment by khanhduytran0** [comment]
oh so we have your tablet to reproduce? fill the template!

**Comment by Smolbeans2** [comment]
no the apps display is bad and dosent fit my screen when i launch an old
version of minecraft on the pojavlauncher.

**Comment by khanhduytran0** [comment]
@zachybee123 bruh press f11

**Comment by Smolbeans2** [comment]
im not on a computer and im talking about pojavlauncher not how to
fullscreeen on a computer.

**Comment by khanhduytran0** [comment]
But isn't this launcher means running a **computer** game on mobile? yeah, the input pipe is available.
![Screenshot_2021-06-07-05-59-14](https://user-images.githubusercontent.com/40482367/120942877-d125e000-c755-11eb-955b-6b0203e839a8.png)

**Comment by Smolbeans2** [comment]
and the game displays into a really ssmall screen and i have to use
magnifier and its annoying

**Comment by Smolbeans2** [comment]
i mean it shows the game in like a small size in the bottom left corner of
my screen.



please tell me how to send image

**Comment by khanhduytran0** [comment]
> please tell me how to send image

You're replying using email so you can't.

If this still not what you mean, we can't help. You didn't provide anything, ripped the issue template.

https://user-images.githubusercontent.com/40482367/120943649-6c20b900-c75a-11eb-8e88-002f647e3a5a.mp4

**Comment by Smolbeans2** [comment]
look at the image here ths is what i mean: https://ibb.co/LrK3Fqbn

**Comment by khanhduytran0** [comment]
@zachybee123 bruh plz stop reply using email
