### ISSUE TITLE
[BUG] Meteor client crashes when I open it

### ISSUE THREAD

**Issue by ChoMametchi** [PojavLauncherTeam/PojavLauncher#1499]
### Describe the bug
So I just wanted to use Meteor Client on my favorite anarchy server, I installed it, opened it.
It greets me with a crash.

**Add a log file if you want to see your bug fixed !**

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6606264/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Install meteor client
2. Start PojavLauncher
3. Open fabric 1.16.5 with Meteor installed

### Expected behavior:
I expected it to run.

**Platform:**
 - Device Model LG Stylo 6
 - CPU architecture aarch64
 - Android Version 10
 - PojavLauncher Version Latest Release

**Comment by ghost** [comment]
Interesting you use custom jvm for optimize but dont Optimize

**Comment by khanhduytran0** [comment]
> Interesting you use custom jvm for optimize but dont Optimize

~~#starboard moment~~

**Comment by khanhduytran0** [comment]
@gitscop try switch to OpenGL ES 3 renderer

**Comment by ghost** [comment]
> > Interesting you use custom jvm for optimize but dont Optimize
> 
> ~#starboard moment~

don't remind me again

**Comment by khanhduytran0** [comment]
Also JVM settings is messed up
`-Xms256m -Xmx512m -Xmx1G -Xms1G`
You’ve set 256-512MB limit, then set again 1GB limit

**Comment by ghost** [comment]
you can use virtual ram but needed root phone

**Comment by ghost** [comment]
You can use labymod 1.16.5 this work with optifine or sodium
And min ram allocated 512 MB 

(not sponsor)

**Comment by ChoMametchi** [comment]
Uh hold on I made an error on the issue
I meant Meteor client not future
Im facepalming so hard right now

**Comment by ChoMametchi** [comment]
> @gitscop try switch to OpenGL ES 3 renderer

Alright I'll try later

**Comment by ghost** [comment]
why are so many people disliking my words

Because using jvm it has no effect on performance 

If you want to get high performance, buy a PC

**Comment by ghost** [comment]
![815611289186467841](https://user-images.githubusercontent.com/70785472/120989570-e0367d80-c7a9-11eb-986b-7ce6889c1570.png)

**Comment by WesleyVanNeck** [comment]
> why are so many people disliking my words
> 
> Because using jvm it has no effect on performance
> 
> If you want to get high performance, buy a PC

you think that but it does impact it but on difrent level

**Comment by ghost** [comment]
> @gitscop try switch to OpenGL ES 3 renderer

Tried it out and it did not work
