### ISSUE TITLE
Error starting the game

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#15]
Error when you start Minecraft 1.14.4
![Screenshot_2020-03-28-11-40-02-349_net kdt pojavlaunch](https://user-images.githubusercontent.com/45615426/77829679-3a897800-70e9-11ea-895c-4c69e75cbf9d.jpg)

**Comment by emelin2004** [comment]
> Error when you start Minecraft 1.14.4
> ![Screenshot_2020-03-28-11-40-02-349_net kdt pojavlaunch](https://user-images.githubusercontent.com/45615426/77829679-3a897800-70e9-11ea-895c-4c69e75cbf9d.jpg)
> 

I don't think that you can at the moment run anything above 1.12

**Comment by khanhduytran0** [comment]
Use v3
