### ISSUE TITLE
Not support 32-bit devices

### ISSUE THREAD

**Issue by anton2007** [PojavLauncherTeam/PojavLauncher#150]
Please fix i using a Digma plane 1585S tablet i have issue new pojavlauncher not starting :(
![Screenshot_20200428-095150](https://user-images.githubusercontent.com/37032392/80442305-cf74d080-8936-11ea-92da-48599b9c5009.png)

**Comment by khanhduytran0** [comment]
Use v2.5 instead of v3.

**Comment by khanhduytran0** [comment]
V3 is in development and will not work.
