### ISSUE TITLE
[BUG] screen is glitched when I switched to zink

### ISSUE THREAD

**Issue by stayinOp69** [PojavLauncherTeam/PojavLauncher#1500]
![Screenshot_20210607_151206_net kdt pojavlaunch](https://user-images.githubusercontent.com/85477239/120995566-23d9b900-c7a3-11eb-9f9c-7fd018a7ae44.jpg)

**Comment by rscAvePlex** [comment]
fair

**Comment by WesleyVanNeck** [comment]
No support for zink
