### ISSUE TITLE
Server help

### ISSUE THREAD

**Issue by Collierson** [PojavLauncherTeam/PojavLauncher#1502]
The server IP is correct, but the server name cannot be resolved. The IP: mc.nagiasu.xyz cannot be accessed by the mobile phone, but can be accessed by the computer

**Comment by WesleyVanNeck** [comment]
i think you use a outdated build use the one on the playstore also fill the template

**Comment by Collierson** [comment]
> 我認為您使用的是過時的版本，使用 Playstore 上的版本也可以填寫模板

The latest version I downloaded from the Playstore
