### ISSUE TITLE
[BUG] Minecraft Crash on Android 8.1

### ISSUE THREAD

**Issue by SNWCreations** [PojavLauncherTeam/PojavLauncher#1503]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
2. Login my Microsoft account.
3. Press "PLAY" button.
4. Wait...
5. Minecraft crashed!

### Expected behavior:
Minecraft crash report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 21-6-8 上午4:15
Description: Initializing game

java.lang.NoClassDefFoundError: com/ibm/icu/text/ArabicShapingException
	at dmv.a(SourceFile:160)
	at djz.<init>(SourceFile:507)
	at net.minecraft.client.main.Main.main(SourceFile:177)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.text.ArabicShapingException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 3 more

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Render thread
Stacktrace:
	at dmv.a(SourceFile:160)
	at djz.<init>(SourceFile:507)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (aarch64) version Android-8.1.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 675062288 bytes (643 MB) / 872415232 bytes (832 MB) up to 872415232 bytes (832 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms835M -Xmx835M
	Launched Version: 1.16.4
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: 9x null

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

No screenshots or videos. The crash report is all.

**Platform:**
 - Device Model Redmi 5 Plus
 - CPU architecture aarch64
 - Android Version 8.1
 - PojavLauncher Version 3.3.1.1_rel_20210206

**Comment by mchnjt** [comment]
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> <br>
> - Make sure there was not duplicated issues.<br>
> - Make sure you have filled this issue template, or this will get rejected.
> </details>
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> ... *(your set of actions to reproduce the bug)*
> 2. Login my Microsoft account.
> 3. Press "PLAY" button.
> 4. Wait...
> 5. Minecraft crashed!
> 
> ### Expected behavior:
> Minecraft crash report:
> 
> ---- Minecraft Crash Report ----
> // Why did you do that?
> 
> Time: 21-6-8 上午4:15
> Description: Initializing game
> 
> java.lang.NoClassDefFoundError: com/ibm/icu/text/ArabicShapingException
> 	at dmv.a(SourceFile:160)
> 	at djz.<init>(SourceFile:507)
> 	at net.minecraft.client.main.Main.main(SourceFile:177)
> Caused by: java.lang.ClassNotFoundException: com.ibm.icu.text.ArabicShapingException
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 3 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at dmv.a(SourceFile:160)
> 	at djz.<init>(SourceFile:507)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.client.main.Main.main(SourceFile:177)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.4
> 	Minecraft Version ID: 1.16.4
> 	Operating System: Linux (aarch64) version Android-8.1.0
> 	Java Version: 1.8.0-internal, Oracle Corporation
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 675062288 bytes (643 MB) / 872415232 bytes (832 MB) up to 872415232 bytes (832 MB)
> 	CPUs: 8
> 	JVM Flags: 2 total; -Xms835M -Xmx835M
> 	Launched Version: 1.16.4
> 	Backend library: LWJGL version 3.2.3 SNAPSHOT
> 	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
> 	GL Caps: Using framebuffer using ARB_framebuffer_object extension
> 	Using VBOs: Yes
> 	Is Modded: Probably not. Jar signature remains and client brand is untouched.
> 	Type: Client (map_client.txt)
> 	CPU: 9x null
> 
> ### Screenshots or videos:
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> 
> No screenshots or videos. The crash report is all.
> 
> **Platform:**
>  - Device Model Redmi 5 Plus
>  - CPU architecture aarch64
>  - Android Version 8.1
>  - PojavLauncher Version 3.3.1.1_rel_20210206
> 

~~welp i guess no 1.16 for u~~

**Comment by khanhduytran0** [comment]
~~So crash is your expected behavior?~~

Enable check libraries and try again.

**Comment by SNWCreations** [comment]
> ~So crash is your expected behavior?~
> 
> Enable check libraries and try again.

How can I enable check libraries?

**Comment by khanhduytran0** [comment]
You can check in launcher settings :eyes:

**Comment by ghost** [comment]
Reinstall (recommend)

**Comment by ghost** [comment]
Wait

**Comment by ghost** [comment]
Use English language don't use arabic

**Comment by ghost** [comment]
maybe that's the problem

**Comment by SNWCreations** [comment]
> Use English language don't use arabic

What? How can I change the language in Modified Android OS???
@NekoIceCream

**Comment by SNWCreations** [comment]
Oops, My phone is strange and interesting..
Today, I want to launch Fabric 1.16.4..
But game crashed again.
Minecraft throws a NoClassDefFoundError exception.
This error makes me unable to play Minecraft. Any version of Minecraft cannot be started on my phone.

**Comment by Mathias-Boulay** [comment]
Seems to be device specific, on a very old version.
Closing
