### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by YTL1mon41kYT** [PojavLauncherTeam/PojavLauncher#1504]
Вылетает, не знаю почему но начало именно сейчас, вылетает форж и другие версии с читами без щас посмотрю но думаю будет тоже самое. 

Телефон 
Redmi 9c nfc 
Android 10

**Comment by Mathias-Boulay** [comment]
Invalid.
Fill the template or the issue will be terminated.

**Comment by ghost** [comment]
Bruh what you issue? You can ask on discord

**Comment by SergueiKhadirov** [comment]
@YTL1mon41kYT какая версия Forge?

**Comment by SergueiKhadirov** [comment]
@YTL1mon41kYT Я могу помочь вам

**Comment by Mathias-Boulay** [comment]
Still no answer from the author.
Closing, we don't need real issues to be clogged up because of ones like this.

**Comment by YTL1mon41kYT** [comment]
@0SergueiKhadirov 1.12.2 я пробовал удалять файлы и это помогало какое то время, потом уже появились код ошибки 1...

**Comment by YTL1mon41kYT** [comment]
@Mathias-Boulay, I'm sorry I didn't notice anyone was answering me.
