### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 5aldgz** [PojavLauncherTeam/PojavLauncher#1505]
hello 
[mods.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/6615480/mods.zip)
♥️🌹
first i love your work guys thank you ♥️.
my issue is when i play with sodium mod my game crashs i tried everything i know but nothing works i tried with and without fabric abi and it still crashing hope you understand me comment because
also i am not that very good at English . I'm sorry if i say something wrong ♥️ and I'm not a progarmer 💔
thanks for reading my comment ♥️.
my phone is 
Lenovo k12 note 
4g ram / 128g / 
I play on 1.16.5

**Comment by jeremy985** [comment]
Try to delete your sodium mod then if you want to remove lag on your PojavLauncher then watch the settings set-up in optifine

**Comment by mchnjt** [comment]
> hello 
> [mods.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/6615480/mods.zip)
> ♥️🌹
> first i love your work guys thank you ♥️.
> my issue is when i play with sodium mod my game crashs i tried everything i know but nothing works i tried with and without fabric abi and it still crashing hope you understand me comment because
> also i am not that very good at English . I'm sorry if i say something wrong ♥️ and I'm not a progarmer 💔
> thanks for reading my comment ♥️.
> my phone is 
> Lenovo k12 note 
> 4g ram / 128g / 
> I play on 1.16.5

fill template when you open issue again. If you don't, die.

**Comment by nabiloi** [comment]
try deleting "fabric installer" in mods file

**Comment by 5aldgz** [comment]
thanks guys 🌹
