### ISSUE TITLE
[BUG] <i download pillow client and my all client died plz help me>

### ISSUE THREAD

**Issue by gamerboy82yt** [PojavLauncherTeam/PojavLauncher#1506]
<Pillow client download> <bug error><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by gamerboy82yt** [comment]
![Screenshot_20210608-180604](https://user-images.githubusercontent.com/83387245/121167933-ff560d80-c884-11eb-857a-de390090010c.png)
Here screenshot

**Comment by mchnjt** [comment]
> ![Screenshot_20210608-180604](https://user-images.githubusercontent.com/83387245/121167933-ff560d80-c884-11eb-857a-de390090010c.png)
> Here screenshot

I've detected 2 shits that is strange.

First, the account name. ***Is that your own, bought, unbanned from hypixel account*** or you got those nfa shit

Second, why the fck the news didn't load anything

**Comment by khanhduytran0** [comment]
And this is worldwide problem. See https://www.xda-developers.com/internet-down-2021

**Comment by gamerboy82yt** [comment]
When i didn't download pillow client it's everything okay but when i
download its everything error

**Comment by gamerboy82yt** [comment]
That acc is mine
