### ISSUE TITLE
mouse and keyboard

### ISSUE THREAD

**Issue by 5aldgz** [PojavLauncherTeam/PojavLauncher#1512]
hello 🌹
does the game support the mouse and keyboard? 
Because I want to buy them and I am afraid that the game will not support them ♥️ Thank you

**Comment by Mathias-Boulay** [comment]
Not an actual issue.
Furthermore, there is support for both starting android 8, but not all devices are perfectly compatible.

Next time, read the current issues instead of clogging the system up with your question.
