### ISSUE TITLE
[Bug] Labymod Crash

### ISSUE THREAD

**Issue by shadersarelegit** [PojavLauncherTeam/PojavLauncher#1514]
I launched labymod 1.8.9 ,then when it loads until 75%,the log said game crashed.

 - Device Model [Samsung Galaxy S8+(SM-G955F)]
 - CPU architecture [aarch64] 
 - Android Version [Android 9]
 - Java VM [ART 2.1.0]
 - OpenGL ES [OpenGL ES 3.2]
 - PojavLauncher Version [Latest Version(Avalible on Google Play)]

**Comment by Mathias-Boulay** [comment]
Duplicate from #1020  and template not filled.
Closing.
