### ISSUE TITLE
[BUG] Minecraft 1.17 doesn't start

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#1516]
Minecraft 1.17 doesn't start but my device supports OpenGl 3.2 

**Platform:**
 - Device Model honor 9c 4/64
 - CPU architecture  aarch64
 - Android Version 10
 - PojavLauncher Version  Latest Release || version 3.3.1.1_rel_20210206

**Comment by khanhduytran0** [comment]
Haven’t you ever read #1035 which is pinned?

**Comment by khanhduytran0** [comment]
Duplicate of #1035

**Comment by rscAvePlex** [comment]
~~Hello People! We are now starting a manhunt for those who need help for '1.17 doesn't work! If you can't wait and just sitting there, you can help devs to make it work before the deadline which annoys new users! If you keep asking for this somehow (or in discord), then the mods know what to do to y'all now.~~

**Comment by rscAvePlex** [comment]
> Minecraft 1.17 doesn't start but my device supports OpenGl 3.2 
> 
> 
> **Platform:**
>  - Device Model honor 9c 4/64
>  - CPU architecture  aarch64
>  - Android Version 10
>  - PojavLauncher Version  Latest Release || version 3.3.1.1_rel_20210206
> 
> 
> 

OpenGLES 3.2 ≠ OpenGL 3.2

**Comment by Spider9326** [comment]
Hi Minkraft version crashes for me I tried to follow all the steps uploaded by khanhduytran0 even though I speak Hebrew and did not understand what he said and I am not on a discord server and still does not work

**Comment by killianmeys3333** [comment]
You need to download java 17 click this link https://met.game.blog/2021/09/17/jdk17-aarch64/

**Comment by CriticalRange** [comment]
> You need to download java 17 click this link https://met.game.blog/2021/09/17/jdk17-aarch64/

It looks pretty sussy ngl

**Comment by 1493028** [comment]
I have a problem why when I play survival in PojavLauncher 1.17 it suddenly crashes

Device type 
Vivo y50
Architecture aarch64
Ram 8 GB

**Comment by khanhduytran0** [comment]
> You need to download java 17 click this link https://met.game.blog/2021/09/17/jdk17-aarch64/

@killianmeys3333 why jdk? Pojav isn't a Java development environment.

**Comment by khanhduytran0** [comment]
> I have a problem why when I play survival in PojavLauncher 1.17 it suddenly crashes
> 
> Device type Vivo y50 Architecture aarch64 Ram 8 GB

Please open a new issue that includes complete information.

**Comment by FreakyMood** [comment]
> > I have a problem why when I play survival in PojavLauncher 1.17 it suddenly crashes
> > Device type Vivo y50 Architecture aarch64 Ram 8 GB
> 
> Please open a new issue that includes complete information.



> > You need to download java 17 click this link https://met.game.blog/2021/09/17/jdk17-aarch64/
> 
> @killianmeys3333 why jdk? Pojav isn't a Java development environment.

You can use jdk too for PojavLauncher. And it's my site.

**Comment by FreakyMood** [comment]
> I have a problem why when I play survival in PojavLauncher 1.17 it suddenly crashes
> 
> Device type Vivo y50 Architecture aarch64 Ram 8 GB

Please select OpenGl 3.0 or 4.6
If you get popup, click to ok. And If your phone is 32bit please select 32 or if your phone is 64bit please select 64bit download

**Comment by FreakyMood** [comment]
> > You need to download java 17 click this link https://met.game.blog/2021/09/17/jdk17-aarch64/
> 
> It looks pretty sussy ngl

Lol why?
You can download java 17 with it.
