### ISSUE TITLE
[BUG] The game crashes with sodium mod

### ISSUE THREAD

**Issue by DioEgizio** [PojavLauncherTeam/PojavLauncher#1518]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Game not starting with sodium stable or alpha mod.

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6633152/latest.log)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Install fabric loader
3. Install sodium mod in mods folder
4. Start that game and join a world

### Expected behavior:
It shouldn't crash

**Platform:**
 - Device Model [Mi 10 8/256]
 - CPU architecture [arm64]
 - Android Version [11]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210321]

**Comment by mchnjt** [comment]
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> <br>
> - Make sure there was not duplicated issues.<br>
> - Make sure you have filled this issue template, or this will get rejected.
> </details>
> 
> ### Describe the bug
> Game not starting with sodium stable or alpha mod.
> 
> **Add a log file if you want to see your bug fixed !**
> 
> The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> [latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6633152/latest.log)
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> 2. Install fabric loader
> 3. Install sodium mod in mods folder
> 4. Start that game and join a world
> 
> ### Expected behavior:
> It shouldn't crash
> 
> **Platform:**
>  - Device Model [e.g. Mi 10 8/256]
>  - CPU architecture [e.g. arm64]
>  - Android Version [e.g. 11]
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210321]
> 
> 
> 
> <details> <summary><b>Additional context</b></summary>
> <br>
> <pre>
> Add any other context about the problem here.
> </pre>
> </details>
> 

~~i would like to laugh why some of y'all don't remove the `e.g.`~~

**Comment by CriticalRange** [comment]
> > Read before submit
> > 
> > - Make sure there was not duplicated issues.
> > - Make sure you have filled this issue template, or this will get rejected.
> > 
> > ### Describe the bug
> > Game not starting with sodium stable or alpha mod.
> > **Add a log file if you want to see your bug fixed !**
> > The log file called _latestlog.txt_ is located under "_Android/data/net.kdt.pojavlaunch/files_", "_games/PojavLauncher/_" or "_games/PojavLauncher/.minecraft_" .
> > You may need to activate an option in your file explorer to see hidden files and folders.
> > Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> > [latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6633152/latest.log)
> > ### To Reproduce:
> > Indicate steps to reproduce the buggy behavior:
> > 
> > 1. Start PojavLauncher
> > 2. Install fabric loader
> > 3. Install sodium mod in mods folder
> > 4. Start that game and join a world
> > 
> > ### Expected behavior:
> > It shouldn't crash
> > **Platform:**
> > 
> > * Device Model [e.g. Mi 10 8/256]
> > * CPU architecture [e.g. arm64]
> > * Android Version [e.g. 11]
> > * PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210321]
> > 
> >  Additional context
> > 
> > Add any other context about the problem here.
> 
> ~i would like to laugh why some of y'all don't remove the `e.g.`~

They don't fill the template, they create the template :D

**Comment by DarkLord555625** [comment]
In the option menu go to video setting and click on advanced setting then turn off fog occulsion and vector one

**Comment by DarkLord555625** [comment]
This might work

**Comment by DioEgizio** [comment]
> In the option menu go to video setting and click on advanced setting then turn off fog occulsion and vector one

Nope, it doesn't work

**Comment by DarkLord555625** [comment]
Then trying deleting all mod file and resinstall fabric and then do the
setting I told and turn render to 3-4

**Comment by creyes200** [comment]
im no expert but maybe with fabric api

**Comment by khanhduytran0** [comment]
latestlog.txt ≠ latest.log 👀

**Comment by JustAMinecrafter** [comment]
> In the option menu go to video setting and click on advanced setting then turn off fog occulsion and vector one

Compact vertex format

**Comment by Zeyrox1090** [comment]
If it doesn't work reinstall pojav works for me ¯\_(ツ)_/¯

**Comment by wackycreeper** [comment]
On OpenGL 4.3 zink renderer sodium does not crash but still very laggy

**Comment by Pgabrielmnecraft** [comment]
> No OpenGL 4.3, o processador zink de sódio não trava, mas ainda está muito lento

what does a person want sodium for? to solve the lag, right? SO WHY USE A THING THAT GIVES MORE LAG?

**Comment by DioEgizio** [comment]
> > No OpenGL 4.3, o processador zink de sódio não trava, mas ainda está muito lento
> 
> what does a person want sodium for? to solve the lag, right? SO WHY USE A THING THAT GIVES MORE LAG?

On every pc Sodium solves lags and make a lot more fps, but in pojav for some reason isn't working at all

**Comment by CriticalRange** [comment]
> > > No OpenGL 4.3, o processador zink de sódio não trava, mas ainda está muito lento
> > 
> > 
> > what does a person want sodium for? to solve the lag, right? SO WHY USE A THING THAT GIVES MORE LAG?
> 
> On every pc Sodium solves lags and make a lot more fps, but in pojav for some reason isn't working at all

It might not be working due to java version (afaik java 11 is the best version to launch sodium with) and OpenGL ES to OpenGL converter (gl4es is the one pojav uses)
Not sure though
0.1 version of sodium works perfectly

**Comment by DioEgizio** [comment]
> > > > No OpenGL 4.3, o processador zink de sódio não trava, mas ainda está muito lento
> > > 
> > > 
> > > what does a person want sodium for? to solve the lag, right? SO WHY USE A THING THAT GIVES MORE LAG?
> > 
> > 
> > On every pc Sodium solves lags and make a lot more fps, but in pojav for some reason isn't working at all
> 
> It might not be working due to java version (afaik java 11 is the best version to launch sodium with) and OpenGL ES to OpenGL converter (gl4es is the one pojav uses)
> Not sure though
> 0.1 version of sodium works perfectly

idk, I used sodium with java 8 and worked just fine on my PC, but sodium 0.1.0 and sodium 0.2.0 didn't work on pojav for me

**Comment by DioEgizio** [comment]
> > > > > No OpenGL 4.3, o processador zink de sódio não trava, mas ainda está muito lento
> > > > 
> > > > 
> > > > what does a person want sodium for? to solve the lag, right? SO WHY USE A THING THAT GIVES MORE LAG?
> > > 
> > > 
> > > On every pc Sodium solves lags and make a lot more fps, but in pojav for some reason isn't working at all
> > 
> > 
> > It might not be working due to java version (afaik java 11 is the best version to launch sodium with) and OpenGL ES to OpenGL converter (gl4es is the one pojav uses)
> > Not sure though
> > 0.1 version of sodium works perfectly
> 
> idk, I used sodium with java 8 and worked just fine on my PC, but sodium 0.1.0 and sodium 0.2.0 didn't work on pojav for me

Oh, I tried also iris on pojav because it fixes lwjgl 3.2.3 but it still crashes

**Comment by khanhduytran0** [comment]
Sodium 0.1 is the only supported version at the moment after disable **Vertex Compact Format** and **Fog Occlusion**. I tried to fix Sodium 0.3 (1.17.1) shader files but it crashes for unknown reason after it rendered just one frame.

**Comment by CriticalRange** [comment]
@Mathias-Boulay you can close this issue #forthehunt

**Comment by LUCIFErr6690cc** [comment]
@khanhduytran0 you have to patch 1.17 fabric

**Comment by NotAHero04** [comment]
Patching the game/Sodium shader files doesn't bring OpenGL 3.x features to gl4es, which is why it crashes.
