### ISSUE TITLE
[ASK] Do my device support zink vulkan?

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1519]
My device are:
Redmi note 4x (mido)
Snapdragon 625
Android 7 MIUI 11

**Comment by mchnjt** [comment]
> My device are:
> Redmi note 4x (mido)
> Snapdragon 625
> Android 7 MIUI 11
> 

What do you think of PojavLauncher, an app that can detect your OpenGLES/Vulkan status? ~~Close this one~~

**Comment by DarkLord555625** [comment]
It will cause you have minimum requirements that is 3gb ram and Snapdragon 600 It would be better if you had Mali Gpu

**Comment by ghost** [comment]
Uh,@DarkLord,are you sure and you're not joking?

**Comment by DarkLord555625** [comment]
No Im not
