### ISSUE TITLE
1.17 Not Loading on Chromebook 

### ISSUE THREAD

**Issue by ValenJ06** [PojavLauncherTeam/PojavLauncher#1520]
Hi! So I’ve had Pojavlauncher on my Samsung chromebook for a while and it’s always worked fine. With the update for 1.17, now when ever I try and hit play for 1.17, it goes to load and then says “game exited”. Every other version works fine, just not 1.17. I’ve tried to Uninstall Pojav and reinstall it, I’ve also tried to uninstall Java Runtime and redownload it, but it still isn’t working. I’ve also tried changing around the JVM and it still doesn’t work. Any thoughts or ways to fix this? Any help is appreciated.

**Comment by mchnjt** [comment]
Can you check the issues tab if it has any issues like this?

**Comment by mchnjt** [comment]
Also, 1.17 is NOT supported at the moment.

**Comment by ValenJ06** [comment]
> Also, 1.17 is NOT supported at the moment.

Okay, thanks! That’s all I was wondering. Is there any idea when 1.17 will be supported?

**Comment by ValenJ06** [comment]
> Can you check the issues tab if it has any issues like this?

I just saw the pinned issue saying it’s not operational. Thank you for the help!
