### ISSUE TITLE
GAME DIRECTORY

### ISSUE THREAD

**Issue by kareemnew2019** [PojavLauncherTeam/PojavLauncher#1521]
WARNING IT IS LITTLE BIG REAQUEST

Please just add game directory for modpacks
And different versions like minecraft launcher
And mcinabox it will be game changer
And last small THING ENHANCE 64 bit gameplay

Just there are mods crash every minute
And any large lag crash the game and sound go and back and it crash with no log just in 1.7.10 If am I correct

Additional questions why all 1.16.5 - 1.16.1 modpacks ( medium modpacks )
GIVE weird screen and sound is normal and it run I can hear buttons I can create work but no screen just minecraft logo and it is blacke in 64 bit
But 10 - 30 personal made modpack work just fine
Maybe it is not compatible mods

BUT I REALLY APPRECIATE ALL YOUR WORK
JUST DON'T ABANDED LIKE MCINABOX
OR I WILL HATE YOU  🤣

**Comment by Mathias-Boulay** [comment]
Let's clear certain points.

1- We don't really care about you hating us for not providing a free service.

2- Game directory is a thing, it is even per version.
Just long press the version slider.

3- bugs related to modpack are known, please read other issues before adding yours next time.

Closing the issue.

**Comment by WesleyVanNeck** [comment]
@kareemnew2019  eneable hiden folderd there is dir

**Comment by kareemnew2019** [comment]
SORRY IF YOU THING I HATE YOU I REALLY APPRECIATE
YOUR WORK I WAS JUST PULLING FEATURE
BUT MY BAD ENGLISH YOU THINK I HATE YOU
I KNOW YOUR MIND I WILL DO THE SAME
BUT I REALLY APPRECIATE YOU WORK WITH NO PAY
😀 are we OK I don't want you to hate me

**Comment by kareemnew2019** [comment]
![changing-game-directory-4](https://user-images.githubusercontent.com/78564582/121730382-e69d6000-caef-11eb-8d79-78dd2c0efbfe.png)

THAT'S MY FEATURE REAQUEST
SORRY FOR ENGLISH

**Comment by CriticalRange** [comment]
So you want the old profiles update ? You can try it by compiling profiles branch of PojavLauncher repo (this repo) and installing it to your device (it's old so many features weren't added that time)
