### ISSUE TITLE
so I have a nice idea let's make java food low end 

### ISSUE THREAD

**Issue by drybones64** [PojavLauncherTeam/PojavLauncher#1526]
Sol twchnacly with my brain we could optimize java then port it over with ram passageways 
I saw this in a movie BTW its where you steal the java ram and port it to your ram so technically  a samsiung note 1 could run 1.71 at 60fps

**Comment by rscDoesMoreTrolling** [comment]
:trollface: what

**Comment by drybones64** [comment]
Ram passageways is where your take ram from tje phone and transplant to a served Minecraft you just have to back minecrfds ram  to optimixe themmfor a phone its easy I can do it now but I'm busy proramimng minecrsft jave for the TV its hard work to RSM passageway

**Comment by drybones64** [comment]
Stop fun of me in yor dicod imm in there but you would ban before I give out ram passagewahs to debs and TV java minecrsft

**Comment by drybones64** [comment]
So the thing is I got TV done for java think me latar now I will ram passage reaserch and tell you my findings on dicodr then yu will gibe me Dev rol

**Comment by rscDoesMoreTrolling** [comment]
ok

**Comment by drybones64** [comment]
Thank I for acknolged me Mr Eccles more trolling here's ram paageway https://youtu.be/j7BVMYcdPxs I now its about hacking but same applys you just do the code swap and hack minecrafts server to steal there RAM

**Comment by drybones64** [comment]
Or this https://youtu.be/K7Hn1rPQouU just copy bad guys to crack minecrsfts firewall the no me Slater

**Comment by drybones64** [comment]
Actually I'm artdell I wanted tltell you but u sold ban me food telling you became java on a low end is bad news Flor pojav so ikm gonna make a new java for phone called pojavinabox by I will food yoall

**Comment by khanhduytran0** [comment]
Yeah I believe you're `artdell`, not @artdeell.

**Comment by drybones64** [comment]
It was a tyo sorry Mr khan I lobe you but I hate you for making pojav real ram and not tranplanting Minecraft ram to your phone ram it so easy bro I lobe you but in also hate your for not listening to me

**Comment by rscDoesMoreTrolling** [comment]
> Yeah I believe you're `artdell`, not @artdeell.

@khanhduytran0 ~~prob the owner of 'dell computers inc.'~~

**Comment by drybones64** [comment]
Well eater way watch the video tapes I  lliks bro they got me ram swap so now I will ram steal pojav server say GOODBYE unless you pay me 1 dollar rupee

**Comment by khanhduytran0** [comment]
hahaha you think you can do that? ""oh no my server got stolen :(((""

**Comment by khanhduytran0** [comment]
@drybones64 your grammar doesn't like artdeell at all.

**Comment by rscDoesMoreTrolling** [comment]
> Well eater way watch the video tapes I  lliks bro they got me ram swap so now I will ram steal pojav server say GOODBYE unless you pay me 1 dollar rupee

k wtf

**Comment by khanhduytran0** [comment]
You don't even know what is sky.

**Comment by khanhduytran0** [comment]
> Well eater way watch the video tapes I lliks bro they got me ram swap so now I will ram steal pojav server say GOODBYE unless you pay me 1 dollar rupee

oh Indian k1d detected

**Comment by drybones64** [comment]
You don't poop became you afraid of the fdark hahahahha say goodbye to pojav and hello there okay okay TO POJAVINABOX JAJAJAJAJAJAJ

**Comment by rscDoesMoreTrolling** [comment]
> You don't poop became you afraid of the fdark hahahahha say goodbye to pojav and hello there okay okay TO POJAVINABOX JAJAJAJAJAJAJ

you're just wasting dev's time.

**Comment by drybones64** [comment]
No pay me know or else I will hack into your CPU core and extract ALL of the ram that's a lot of money lost

**Comment by rscDoesMoreTrolling** [comment]
whatever imma play 21w-i mean 1.17

**Comment by drybones64** [comment]
Also I not am trolling I'm arttt remember we did stuff together join me bot thirty j needed to know if you wanna pagme dome rupee to prove your love to me dady

**Comment by dashboarder** [comment]
> > Well eater way watch the video tapes I lliks bro they got me ram swap so now I will ram steal pojav server say GOODBYE unless you pay me 1 dollar rupee
> 
> oh Indian k1d detected

Indian kid as @drybones64 can just say and cannot do what they say

**Comment by dashboarder** [comment]
> Also I not am trolling I'm arttt remember we did stuff together join me bot thirty j needed to know if you wanna pagme dome rupee to prove your love to me dady

Prove us that you're playing sky right now!

**Comment by dashboarder** [comment]
If you're "arttt"

**Comment by drybones64** [comment]
Dont lie only i ha e 1.17 and 1.18 i can hacm the ram of minecrsft server  so i stole there ram report om 1.18 pay me uip for the ram extraction

**Comment by dashboarder** [comment]
> Dont lie only i ha e 1.17 and 1.18 i can hacm the ram of minecrsft server so i stole there ram report om 1.18 pay me uip for the ram extraction

Ye I will hack your brain to delete your account

**Comment by dashboarder** [comment]
Russian doesn't accept Indian rupe bruh

**Comment by rscDoesMoreTrolling** [comment]
> Dont lie only i ha e 1.17 and 1.18 i can hacm the ram of minecrsft server  so i stole there ram report om 1.18 pay me uip for the ram extraction 

![2021-06-11_04.12.30.png](https://user-images.githubusercontent.com/83752061/121764156-51907a80-cb74-11eb-9d90-867aad7e404e.png)

**Comment by drybones64** [comment]
Your joking I'm gonna send my Minecraftsquad to nuke your house I'm a crazy hcker I can hack nukes and send them too seat the data for video tapes

**Comment by drybones64** [comment]
thats so fake bro i got 1.19 and 1.10 at 60 fps on mh low end 1 ram

**Comment by JustAMinecrafter** [comment]
> Your joking I'm gonna send my Minecraftsquad to nuke your house I'm a crazy hcker I can hack nukes and send them too seat the data for video tapes

Imagine wanting attention kid

**Comment by dashboarder** [comment]
@drybones64 ok gonna hack your own bra1n to su1c1d3

**Comment by drybones64** [comment]
#1518 hack-send-mouse-destroycumpueter@self

**Comment by JustAMinecrafter** [comment]
> #1518 hack-send-mouse-destroycumpueter@self

Omg I am laughing 🤣🤣🤣

**Comment by Frank000XD** [comment]
> Also I not am trolling I'm arttt remember we did stuff together join me bot thirty j needed to know if you wanna pagme dome rupee to prove your love to me dady

ooga booga AAAAAAAHHHHH AHHHHHHH OOGA *screeching monkey noises * OOH OOH AAAAHHHH OOGA BOOGA

**Comment by drybones64** [comment]
That's my hack commander

**Comment by dashboarder** [comment]
> thats so fake bro i got 1.19 and 1.10 at 60 fps on mh low end 1 ram

💩💩💩💩💩

**Comment by drybones64** [comment]
Once I say enter it will explode the data base and I will stealk the ram

**Comment by JustAMinecrafter** [comment]
> Once I say enter it will explode the data base and I will stealk the ram

Yo u got any friends in school?

**Comment by dashboarder** [comment]
> Once I say enter it will explode the data base and I will stealk the ram

steal your own brain first

**Comment by JustAMinecrafter** [comment]
Mf got no friends

**Comment by rscDoesMoreTrolling** [comment]
> Your joking I'm gonna send my Minecraftsquad to nuke your house I'm a crazy hcker I can hack nukes and send them too seat the data for video tapes 

do it. I'm calling the FBI now.

**Comment by drybones64** [comment]
STOP PLEASE

**Comment by JustAMinecrafter** [comment]
> STOP PLEASE
No kid

**Comment by JustAMinecrafter** [comment]
Clown failed english

**Comment by drybones64** [comment]
IM SORRY DONTR CALL THE PATROL ON ME

**Comment by JustAMinecrafter** [comment]
We are here to improve yours

**Comment by JustAMinecrafter** [comment]
Lmao just close this issue

**Comment by Frank000XD** [comment]
@drybones64  yes me gonna calk police ooga booga

**Comment by drybones64** [comment]
No I'm sorry goodbyep

**Comment by JustAMinecrafter** [comment]
This attention seeking dude is going to haunt us 😨😨😨😨 😨

**Comment by dashboarder** [comment]
> STOP PLEASE

dumb@zz moment

**Comment by drybones64** [comment]
sont call potrol on me

**Comment by JustAMinecrafter** [comment]
Lmao no

**Comment by JustAMinecrafter** [comment]
Mf got brain cancer

**Comment by drybones64** [comment]
stoop it

**Comment by Frank000XD** [comment]
@drybones64 police comin to your house ooga




booga

**Comment by dashboarder** [comment]
> sont call potrol on me

Indian language be like

**Comment by drybones64** [comment]
ban @pojav X-DDHACJ-LMINECRAFT- RAMSWAP=TRUE

**Comment by drybones64** [comment]
say goodbye

**Comment by Frank000XD** [comment]
@drybones64 now me send fbi to house ooga




they kill and arrest booga

**Comment by JustAMinecrafter** [comment]
Lmao

**Comment by drybones64** [comment]
No don't killme

**Comment by JustAMinecrafter** [comment]
> stoop it

U wanted attention, we gave it to you so stfu

**Comment by rscDoesMoreTrolling** [comment]
![Screenshot_20210612-115802.png](https://user-images.githubusercontent.com/83752061/121764309-8224e400-cb75-11eb-9788-fcf9d2c5fe9b.png)

**Comment by dashboarder** [comment]
@drybones64 [come to this](https://m.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by drybones64** [comment]
My bar say in 2 mins pojav will explode and I will consume ram

**Comment by JustAMinecrafter** [comment]
> My bar say in 2 mins pojav will explode and I will consume ram

Ok attention seeking kid

**Comment by Frank000XD** [comment]
> ![Screenshot_20210612-115802.png](https://user-images.githubusercontent.com/83752061/121764309-8224e400-cb75-11eb-9788-fcf9d2c5fe9b.png)

@drybones64 this mean they goin kill u with guns

guns go pew pew booga ooga

**Comment by drybones64** [comment]
cmake pojavinabox cpu=true ram=true

**Comment by JustAMinecrafter** [comment]
We got a solution

**Comment by dashboarder** [comment]
> My bar say in 2 mins pojav will explode and I will consume ram

Ok bro [visit this hack tutorial first](https://m.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by drybones64** [comment]
Nigger

**Comment by drybones64** [comment]
1 more min

**Comment by drybones64** [comment]
im gonna miss you freijnd im artdeel just remidjjnb yiu

**Comment by rscDoesMoreTrolling** [comment]
> Nigger

😱😱😱

**Comment by Frank000XD** [comment]
> Nigger

omg nword, me sending millitary for racist nuke goin to ur house 

booga
ooga

**Comment by drybones64** [comment]
10 more secs

**Comment by drybones64** [comment]
doreon joined me why dont you

**Comment by drybones64** [comment]
he gave me all ruppes was well

**Comment by Frank000XD** [comment]
@drybones64 joe mama 😎 me pro

**Comment by drybones64** [comment]
Oh wow legacy is also joinig

**Comment by drybones64** [comment]
Hi im lagacy i joied pojavinabox more ram cpu

**Comment by Frank000XD** [comment]
clown language?oh me bad ooga booga D:

**Comment by rscDoesMoreTrolling** [comment]
> Hi im lagacy i joied pojavinabox more ram cpu

DAMN F0CK IF I AM A MOD IN THIS REPO I WOULD CLOSE THIS SH1TE

**Comment by dashboarder** [comment]
oh no FBI is joining to arrest @drybones64

**Comment by dashboarder** [comment]
dumbass @SteveGo2Work alt

**Comment by JustAMinecrafter** [comment]
> Hi im lagacy i joied pojavinabox more ram cpu

Ok attention seeker

**Comment by dashboarder** [comment]
ok gonna find ur discord and tell devs to ban u @drybones64

**Comment by Frank000XD** [comment]
@drybones64 u bad me pro noob noob noob 😎😎😎

**Comment by rscDoesMoreTrolling** [comment]
@drybones64 hello i am ram eater and we all here to let u knoe that we are giving free mod rol in our descord and we piced you so tel us ur discord name

**Comment by drybones64** [comment]
I give you hint I like anime### 
Duplicate of #

**Comment by drybones64** [comment]
Oh ummm it starts with a c or a k I'm bad with letters

**Comment by dashboarder** [comment]
@drybones64 look at ur dumb issue
> OK so imma legit 20 year old how did I know how much ram I have

**Comment by rscDoesMoreTrolling** [comment]
> Oh ummm it starts with a c or a k I'm bad with letters

Ok uh pls tel us complete nam maybe just 3 letters and we'll do rest

**Comment by dashboarder** [comment]
@drybones64 16 mins already Didnot see you hacked

**Comment by drybones64** [comment]
Idk

**Comment by drybones64** [comment]
Andyes its hackded

**Comment by drybones64** [comment]
i give hintf you  all me a f word clown and you promised to unban me 2 momthsago on my main accountr i just joined on nee account j think or idk

**Comment by khanhduytran0** [comment]
<details> <summary><b>this acc hacked password here</b></summary>
<br>
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give, never gonna give
(Give you up)
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
</details>

**Comment by drybones64** [comment]
Bro not gunny

**Comment by drybones64** [comment]
you shoukd rememeber me

**Comment by drybones64** [comment]
U say you unbanm BUT NOPe so I alt spam and I just alt a new account

**Comment by JustAMinecrafter** [comment]
> i give hintf you all me a f word clown and you promised to unban me 2 momthsago on my main accountr i just joined on nee account j think or idk

I am the clown dude

**Comment by JustAMinecrafter** [comment]
Ah yes

**Comment by JustAMinecrafter** [comment]
Bastards don't get a second chance

**Comment by JustAMinecrafter** [comment]
Stfu bipro

**Comment by drybones64** [comment]
I'mbrpoi

**Comment by JustAMinecrafter** [comment]
Stfu bipro

**Comment by JustAMinecrafter** [comment]
I knew it

**Comment by JustAMinecrafter** [comment]
U and ur Pakistan gang

**Comment by rscDoesMoreTrolling** [comment]
@drybones64 So, you're bpoir? Closing this issue now.

**Comment by drybones64** [comment]
Unban me PLS I already have 10 alt on ur server

**Comment by drybones64** [comment]
dont clozsd

**Comment by rscDoesMoreTrolling** [comment]
> Unban me PLS I already have 10 alt on ur server

No.

**Comment by drybones64** [comment]
i changed :((((((((((

**Comment by JustAMinecrafter** [comment]
> Unban me PLS I already have 10 alt on ur server

I know all ur alts

**Comment by drybones64** [comment]
UNABN ME PLEASE ILL SEND CHILD PORN

**Comment by JustAMinecrafter** [comment]
I have been alt checking

**Comment by drybones64** [comment]
Some are old ACCC

**Comment by drybones64** [comment]
im a good guy j was addicted tok chikld porn but i stoped

**Comment by JustAMinecrafter** [comment]
"old" mf thinks old is 1 week

**Comment by khanhduytran0** [comment]
we brought you to starboard![image](https://user-images.githubusercontent.com/40482367/121765078-a0d5ab80-cb72-11eb-970e-d853c96174d8.png)

**Comment by drybones64** [comment]
Ummm

**Comment by drybones64** [comment]
ill spam dirty pics of my momif donf hnabn

**Comment by drybones64** [comment]
and dirty ppics of underage bkoys

**Comment by rscDoesMoreTrolling** [comment]
> and dirty ppics of underage bkoys

We would like to see poop pics of yourself, not others.

**Comment by drybones64** [comment]
Pls sir

**Comment by drybones64** [comment]
also im 19

**Comment by luckyboy2705** [comment]
You will not get unbanned.

**Comment by drybones64** [comment]
I quite being a dumbass

**Comment by luckyboy2705** [comment]
And what's the reason you want an unban?

**Comment by drybones64** [comment]
I'm smart I can overthrow the chancaler

**Comment by luckyboy2705** [comment]
that you*

**Comment by luckyboy2705** [comment]
yep I can see that from your grammer

**Comment by drybones64** [comment]
Why won't u unban

**Comment by drybones64** [comment]
#936 what did I ever do

**Comment by luckyboy2705** [comment]
Duykhantran close this issue

**Comment by khanhduytran0** [comment]
~~wait for 4 years and we will unban you~~

**Comment by ITZPGDYT** [comment]
Hm
