### ISSUE TITLE
EXPOSING POJAV

### ISSUE THREAD

**Issue by drybones64** [PojavLauncherTeam/PojavLauncher#1527]
POJAV HAVE nonresistance for people like me all I do is little things and they go gger mode SIGHHHHH WTFFFF UNBAN ME I DID NOTHINGG BITRCH

**Comment by drybones64** [comment]
Unabn now

**Comment by JustAMinecrafter** [comment]
> Unabn now

Show urself

**Comment by drybones64** [comment]
/ban @pojav DDDSTRNG FROM BIPRO ENTER BYEBYBEHEYEBEHBEYEBEYEN

**Comment by JustAMinecrafter** [comment]
Imagine wanting attention

**Comment by drybones64** [comment]
jskksksehheheheheeheehehhe now unban hehehehehhehehehehehehe

**Comment by JustAMinecrafter** [comment]
He said he no need this server

**Comment by drybones64** [comment]
UNABN PLSPSLSPLSPSLSPSP PLSSSSSSSSSSSS

**Comment by JustAMinecrafter** [comment]
Clown be lying

**Comment by JustAMinecrafter** [comment]
Brain cancer

**Comment by drybones64** [comment]
i have10 alts

**Comment by JustAMinecrafter** [comment]
Someone close this

**Comment by drybones64** [comment]
with 50 more on the way

**Comment by JustAMinecrafter** [comment]
This guy wants attention

**Comment by drybones64** [comment]
Last night in made a ton of alts xdxdxd

**Comment by JustAMinecrafter** [comment]
> with 50 more on the way

Lmao alt checker checked almost all ur alts alr

**Comment by drybones64** [comment]
like 50 have fun with bipro alts

**Comment by JustAMinecrafter** [comment]
Ok

**Comment by JustAMinecrafter** [comment]
Kid

**Comment by drybones64** [comment]
Nooo

**Comment by drybones64** [comment]
Tell me why I sshpuod unban you frommkh server kirby

**Comment by Hackergamergaming** [comment]
cant wait to ban all of them

**Comment by drybones64** [comment]
I'm circumcised

**Comment by Hackergamergaming** [comment]
good

**Comment by drybones64** [comment]
imagine having foreskim

**Comment by Hackergamergaming** [comment]
hypocrite

**Comment by drybones64** [comment]
No u

**Comment by drybones64** [comment]
hqhahahahahahaaahhahahahahhaloser

**Comment by drybones64** [comment]
btw doregon said he will unban

**Comment by drybones64** [comment]
and legacy

**Comment by Hackergamergaming** [comment]
so scary

**Comment by drybones64** [comment]
they told me fo tell duy fhat he ned to unban me bc there fogot hoe tooo unban

**Comment by drybones64** [comment]
So yeah

**Comment by JustAMinecrafter** [comment]
> they told me fo tell duy fhat he ned to unban me bc there fogot hoe tooo unban

No way he begged for a ban. Also u kept spamming

**Comment by Hackergamergaming** [comment]
i unbanned you

**Comment by Hackergamergaming** [comment]
now shut the fuck up

**Comment by drybones64** [comment]
thanks

**Comment by JustAMinecrafter** [comment]
Stfu

**Comment by Hackergamergaming** [comment]
remove all of you're fucking alts before i unban you

**Comment by drybones64** [comment]
Liar

**Comment by drybones64** [comment]
im kira btw but dont ban i wanna talk

**Comment by drybones64** [comment]
Ok

**Comment by drybones64** [comment]
im horny

**Comment by drybones64** [comment]
XD

**Comment by drybones64** [comment]
Hello

**Comment by Hackergamergaming** [comment]
u gonna remove all of ur alts or no unban

**Comment by drybones64** [comment]
Kira was not my alt coolguy is hahahaahah

**Comment by Hackergamergaming** [comment]
liar coolguy is minion alt

**Comment by Hackergamergaming** [comment]
u probably dont know him

**Comment by drybones64** [comment]
I do know him he sent me death threats

**Comment by drybones64** [comment]
i have 100 alts to kazy

**Comment by Hackergamergaming** [comment]
proof?

**Comment by drybones64** [comment]
99% of people you ban are me for advertising

**Comment by Hackergamergaming** [comment]
> I do know him he sent me death threats

proof

**Comment by drybones64** [comment]
No. Brooooo

**Comment by Hackergamergaming** [comment]
ahh yes lying

**Comment by drybones64** [comment]
im gonna flood you wifh alts right now unkess u give pay day

**Comment by Hackergamergaming** [comment]
no proof

**Comment by Hackergamergaming** [comment]
mf lyin

**Comment by drybones64** [comment]
Die in heck mustard

**Comment by drybones64** [comment]
I'mevery where

**Comment by drybones64** [comment]
ok

**Comment by Hackergamergaming** [comment]
i wont unban ur main then

**Comment by drybones64** [comment]
Anyways I got 1.17 to work

**Comment by drybones64** [comment]
i made pojaavinaboox

**Comment by drybones64** [comment]
its faster and butter keweed

**Comment by drybones64** [comment]
You have to ban 10 more of my alts an me wiwill do res just don't screwdriver 1 civ up

**Comment by drybones64** [comment]
Sorry

**Comment by drybones64** [comment]
i love ypu

**Comment by drybones64** [comment]
jeew

**Comment by drybones64** [comment]
STOP BANNUNG

**Comment by Hackergamergaming** [comment]
you have a problem?

**Comment by khanhduytran0** [comment]
blocked

**Comment by Hackergamergaming** [comment]
thanks duy

**Comment by PojavIauncherTeam** [comment]
> so scary

Why he got banned anyway?

**Comment by Snivyer1910** [comment]
I

> > so scary
> 
> Why he got banned anyway?

he seems very childish but yeah why he ban?

**Comment by khanhduytran0** [comment]
He is under 13.

**Comment by rscDoesMoreTrolling** [comment]
damn underaged
