### ISSUE TITLE
Can't launch fabric

### ISSUE THREAD

**Issue by kimsmith65** [PojavLauncherTeam/PojavLauncher#1528]
Can't launch fabric 1.16.4 on pojavlauncher... Why?
Why I can't launch fabric, but forge can? 
What the heck dude..

**Comment by Mathias-Boulay** [comment]
Invalid, fill the template or the issue will be terminated.

**Comment by khanhduytran0** [comment]
@kimsmith65 still no respond from you even dev responded as soon as you open this issue. **Iazy**. Closing.

**Comment by PrinceNetam** [comment]
Wait I also can't run both 🥺forge and fabric
