### ISSUE TITLE
[BUG] <Zink finally worked But have minor bug>

### ISSUE THREAD

**Issue by Epoy266** [PojavLauncherTeam/PojavLauncher#1529]
**Describe the solution you'd like**

Try to set the NativeWindow to RGBA instead of RGBX, maybe that fixed the bug on other devices
@khanhduytran0 

**Describe alternatives you've considered**

**Additional context**

**Comment by kedrick021** [comment]
Working on adreno any shader now?

**Comment by kedrick021** [comment]
Or fix lag?

**Comment by khanhduytran0** [comment]
> Try to set the NativeWindow to RGBA instead of RGBX, maybe that fixed the bug on other devices

@Epoy266 this will eat more VRAM and performance since it has to render extra alpha channel which is unnecessary.

**Comment by kedrick021** [comment]
Nostalgia on adreno is not working anymore
In 1.12.2 invisible everything even me
