### ISSUE TITLE
Error 3 preview 3

### ISSUE THREAD

**Issue by Statzar** [PojavLauncherTeam/PojavLauncher#153]
***Leaking account!!!***
![Screenshot_20200428-093554](https://user-images.githubusercontent.com/64459276/80455056-bae30900-8933-11ea-9010-7e65def8cfaf.png)
![Screenshot_20200428-093546](https://user-images.githubusercontent.com/64459276/80455058-bb7b9f80-8933-11ea-9cee-18cecc181af3.png)
Another request: you, as I understand it, have a colleague from Russia? Maybe this will be too impudent a request, but could you add a choice of language to the launcher? In particular, Russian.
In the new version, I can’t install either optifine or forge.
Sorry for my bad english, translated through google

**Comment by khanhduytran0** [comment]
Deleted leaked image account.

**Comment by khanhduytran0** [comment]
> Another request: you, as I understand it, have a colleague from Russia? Maybe this will be too impudent a request, but could you add a choice of language to the launcher? In particular, Russian.

Ask @artdeell

**Comment by khanhduytran0** [comment]
Duplicate with #148
