### ISSUE TITLE
Cant write to gBuffers

### ISSUE THREAD

**Issue by jebbyk** [PojavLauncherTeam/PojavLauncher#1530]
### Describe the bug
I cant write to additional buffers (for example I wanna pass normals and depth from gbuffers_terrain into composite shader). On my phone with Optifine HD G6 Ultra Im getting error (without any details). On my PC with Optifine HD G8_pre2 Ultra it works fine. Is it a limitation of Oprifine G6 or a limitation of Pojav?

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6641784/latest.log)

### To Reproduce:

1. Start PojavLauncher
2. Install Minecraft 1.16.5 + Optifine U G6
3. place Open4Es shader in shaderpacks folder
4. change /* DRAWBUFFERS:0 */ to /* DRAWBUFFERS:02 */
5. add line "gl_FragData[1] = vec4(1.0, 0.0, 0.0, 1.0);" in the end of main() method
6. start minecraft
7. reload the sahder
8. see the error in chat

### Expected behavior:
no errors on step 8
gbuffers can be used to transfer data between shader files

### Screenshots or videos:
unavailable

**Platform:**
 - Device Model [mi5 with sanpdragon 820 and adreno 530 GPU ]
 - CPU architecture [aarch64] 
 - Android Version [7.1.2]
 - PojavLauncher Version [version 3.3.1.1_rel_20210125]

**Comment by khanhduytran0** [comment]
> On my phone with Optifine HD G6 Ultra Im getting error (without any details). On my PC with Optifine HD G8_pre2 Ultra it works fine.

Remember that phone does not have a PC GPU such as RTX. You are limited to use OpenGL ES shader language.

**Comment by khanhduytran0** [comment]
Multiple `gl_FragData` are not supported on most devices.

**Comment by khanhduytran0** [comment]
May I transfer this to Open4ES repository?

**Comment by jebbyk** [comment]
how can I know if Multiple gl_FragData is supported on my phone? Is it some kind of specific openGL extension?  My phone runs OpenGL ES 3.2 and openGL ES GLSL 3.20

**Comment by jebbyk** [comment]
this question was born while Im trying to contribute to Open4Es btw

**Comment by khanhduytran0** [comment]
I'm not good at GLSL, but `gl_FragData` is only available on GLES 2. On GLES 3, it was replaced by something idk...

**Comment by WesleyVanNeck** [comment]
> this question was born while Im trying to contribute to Open4Es btw

Can you try adding better water like waving

**Comment by jebbyk** [comment]
I read some thing about it. it says it was replaced with a varying out variables. but I don't know how exactly to write to specific buffer. well gonna research it a bit

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
