### ISSUE TITLE
[BUG] Can't run forge 1.7.10-

### ISSUE THREAD

**Issue by Forever2397** [PojavLauncherTeam/PojavLauncher#1535]
me and my friends love to play Pojav Launcher version 1.16.5 forge and but problem Forge 1.7.10- Not Support in PojavLauncher Even black screen Can you fix this problem?
My Device:
Oppo a5s
Ram:3Gb
Rom:32 GB
processor:mediatek

**Comment by khanhduytran0** [comment]
new bug: can’t fill the template...
