### ISSUE TITLE
[BUG] My PojavLauncher can't use shader if I use shader my game screen goes black

### ISSUE THREAD

**Issue by Raden1** [PojavLauncherTeam/PojavLauncher#1536]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
[Sheders] Error' : Invalid program "Shadow"
[Sheders] Error' : Invalid program "gbuffers_basic"
[Sheders] Error' : Invalid program "gbuffers_textured"
[Sheders] Error' : Invalid program "gbuffers_block"
[Sheders] Error' : Invalid program "gbuffers_entities"
[Sheders] Error' : Invalid program "gbuffers_armor_glint"
[Sheders] Error' : Invalid program "gbuffers_hand"
[Sheders] Error' : Invalid program "deferred"
[Sheders] Error' : Invalid program "composite"
### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. realme 3/32]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 1.16.5_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
@Raden1 
~~""your PojavLauncher? fix it yourself.""~~

Do your phone have a RTX graphics card?

**Comment by khanhduytran0** [comment]
Do you think your phone has a PC GPU?
