### ISSUE TITLE
[BUG] <texture but 1.8.9>

### ISSUE THREAD

**Issue by LostandFoundOwner** [PojavLauncherTeam/PojavLauncher#1538]
so when I play 1.8.9 bedwars the textures get bu
Duplicate of #ggy my skin turns black the swords have a square

<the 1.8.9 textures are buggy> <summary><b>Read before submit</b></summary>
<br> 
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details> bedwars 1.8.9 texture not working

### Describe the bug
So I'm playing hypixel bedwars on 1.8.9 then the textures become all weird the swords have a square around them the skins are black and glitchy
**Add a log file if you want to see your bug fixed !**
It's only a texture bug
The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected 1.8.9 texture to not be buggy

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

> ``

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by LostandFoundOwner** [comment]
![Screenshot_20210613-171010.png](https://user-images.githubusercontent.com/85341933/121802003-d78fec80-cc6c-11eb-969f-b508c7f3173f.png) there's the screenshot

**Comment by WesleyVanNeck** [comment]
Dont use gl4es 1.1.5 on 1.8.9

**Comment by LostandFoundOwner** [comment]
> Dont use gl4es 1.1.5 on 1.8.9

How do I turn off

**Comment by CriticalRange** [comment]
> > Dont use gl4es 1.1.5 on 1.8.9
> 
> How do I turn off

Delete it from jvm arguments (which is in settings)

**Comment by LostandFoundOwner** [comment]
How

**Comment by LostandFoundOwner** [comment]
Ohhh i disable the colors???
