### ISSUE TITLE
[F-REQ] Reset everything

### ISSUE THREAD

**Issue by KTibow** [PojavLauncherTeam/PojavLauncher#1539]
**Is your feature request related to a problem? Please describe.**
Whenever I try to launch 1.16, it only has a black screen and crashes (returns to launcher). I have a feeling that this could be resolved with a reset, because 1.16.4 works fine but 1.16.5 doesn't. However, when I choose "Clear data" in the app settings, it still has it saved somewhere.

**Describe the solution you'd like**
A button in the settings to reset everything; the downloaded installations, Java, etc.

**Describe alternatives you've considered**
Put out some clear information about where the installed versions are located.

**Additional context**
I can upload a video if you want.

**Comment by Mathias-Boulay** [comment]
indeed the data isn't entirely reset with this action
the folder you're looking for is located under games>PojavLauncher
enable hidden files to see the .minecraft
