### ISSUE TITLE
(Pojavlauncher 3.0.0 Preview3) 1.11.2 Don't work

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#154]
OpenJDK Runtime
proot info: pid 30456: terminated with signal 31
/bin/bash: line 3: 30456 Bad system call         java -Duser.home=/storage/emulated/0/games/.minecraft -Xmx512M -classpath /storage/emulated/0/games/.minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar:/storage/emulated/0/games/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/storage/emulated/0/games/.minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar:/storage/emulated/0/games/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/storage/emulated/0/games/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/storage/emulated/0/games/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:/storage/emulated/0/games/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/storage/emulated/0/games/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/storage/emulated/0/games/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/storage/emulated/0/games/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/storage/emulated/0/games/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/storage/emulated/0/games/.minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar:/storage/emulated/0/games/.minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar:/storage/emulated/0/games/.minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:/storage/emulated/0/games/.minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/storage/emulated/0/games/.minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/storage/emulated/0/games/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/storage/emulated/0/games/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/storage/emulated/0/games/.minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/storage/emulated/0/games/.minecraft/libraries/com/mojang/authlib/1.5.24/authlib-1.5.24.jar:/storage/emulated/0/games/.minecraft/libraries/com/mojang/realms/1.10.16/realms-1.10.16.jar:/storage/emulated/0/games/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/storage/emulated/0/games/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/storage/emulated/0/games/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/storage/emulated/0/games/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/storage/emulated/0/games/.minecraft/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar:/storage/emulated/0/games/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar:/storage/emulated/0/games/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar:/storage/emulated/0/games/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar:/storage/emulated/0/games/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar:/storage/emulated/0/games/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209.jar:/storage/emulated/0/games/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar:/storage/emulated/0/games/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar:/storage/emulated/0/games/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar:/storage/emulated/0/games/.minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5.jar:/storage/emulated/0/games/.minecraft/versions/1.11.2/1.11.2.jar net.minecraft.client.main.Main --fullscreen --username Franzel909 --version 1.11.2 --gameDir /storage/emulated/0/games/.minecraft --assetsDir /storage/emulated/0/games/.minecraft/assets --assetIndex 1.11 --uuid 00000000-0000-0000-0000-000000000000 --accessToken 0 --userType mojang --versionType release

**Comment by khanhduytran0** [comment]
There are too many duplicate...

**Comment by khanhduytran0** [comment]
Duplicate #148

**Comment by khanhduytran0** [comment]
Just bad system call which have many duplicate.
