### ISSUE TITLE
[BUG] <Short description> Java proxy support is still broken

### ISSUE THREAD

**Issue by meetioss** [PojavLauncherTeam/PojavLauncher#1540]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
So, jvm offers a feature allowing a proxy server to be set up. For minecraft, this can override the servers it uses to look for resources, allowing some versions to work correctly. With Pojav, the feature is broken.

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
2. Add the jvm arguments "-Dhttp.proxyHost=betacraft.pl
-Djava.util.Arrays.useLegacyMergeSort=true"
3. Go in minecraft beta 1.7 or 1.8 and place a door
4. Open it. It will not have a sound, sign of the proxy not working correctly

### Expected behavior:
I expected some old sounds in alpha and beta versions, and some older versions loading correctly

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128] Redmi note 8 pro
 - CPU architecture [e.g. aarch64] aarch 64
 - Android Version [e.g. 10] 10
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ] latest version from actions

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details> 
A latestlog isn't required as it adds no further info regarding the issue. It appears to be a bug with the java emulation not handling proxies correctly. Please look into it.

**Comment by Mathias-Boulay** [comment]
duplicate from #1252 
Closing.
