### ISSUE TITLE
Android versión on iOS?

### ISSUE THREAD

**Issue by creyes200** [PojavLauncherTeam/PojavLauncher#1542]
sorry for not filling the template but there wasn't a template for asking questions.
i came across a YouTube video that installed povajlauncher for Android on iOS, i want to know if its real and if it is why is it not available in the iOS GitHub paige.

link to video:

https://youtu.be/Uik3FjlhrkM

**Comment by khanhduytran0** [comment]
bruh, I've left a comment on that video 3 weeks ago, it's fake, Android ≠ iOS.

**Comment by creyes200** [comment]
ok thanks (then that Guy must have a Lot of fake accounts because a Lot of comments said it worked)

thanks

**Comment by creyes200** [comment]
just chekin

**Comment by WesleyVanNeck** [comment]
i just left a commit to that its fake

**Comment by khanhduytran0** [comment]
report it then

**Comment by WesleyVanNeck** [comment]
> report it then

already did that
