### ISSUE TITLE
[F-REQ] please give me jvm arguments my pojav launcher still crash

### ISSUE THREAD

**Issue by Swaraj664** [PojavLauncherTeam/PojavLauncher#1544]
Developer's please give me best jvm arguments for pojav launcher my pojav launcher works properly on 512mb but I can't play survival world please give me lag and crash fixing jvm arguments and tell me how much I should have to resolve ram

Phone Redmi 8A daul
Ram 3gb
Architecture 32 bit
Android version 10
Pojav launcher version leatest

**Comment by mchnjt** [comment]
> Developer's please give me best jvm arguments for pojav launcher my pojav launcher works properly on 512mb but I can't play survival world please give me lag and crash fixing jvm arguments and tell me how much I should have to resolve ram
> 
> Phone Redmi 8A daul
> Ram 3gb
> Architecture 32 bit
> Android version 10
> Pojav launcher version leatest
> 

Please fill the template. No fix.

**Comment by khanhduytran0** [comment]
devs are “overtaged” because of ur issues

**Comment by khanhduytran0** [comment]
devs are “overloaded” because of ur issues

**Comment by khanhduytran0** [comment]
~~Also, you’ve said “pojav launcher” is yours, fix it yourself :trollface:~~
