### ISSUE TITLE
[BUG] <I don't see my resource pack

### ISSUE THREAD

**Issue by LostandFoundOwner** [PojavLauncherTeam/PojavLauncher#1546]
I tried adding dynamic duo and purpled default edit 

<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
<my resource packs do not show up4>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected my resource packs to show up but they don't 

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_20210615-223710.png](https://user-images.githubusercontent.com/85341933/122072551-423a5700-ce2a-11eb-80ba-b3c880ceb52c.png)![Screenshot_20210615-223717.png](https://user-images.githubusercontent.com/85341933/122072565-46ff0b00-ce2a-11eb-8ae8-ad28e824fbc3.png)

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details> pls fix it

**Comment by WesleyVanNeck** [comment]
Unzip them

**Comment by LostandFoundOwner** [comment]
I tried
