### ISSUE TITLE
[BUG] <crash>

### ISSUE THREAD

**Issue by LostandFoundOwner** [PojavLauncherTeam/PojavLauncher#1547]
my game crash when i add color pls help

<details> <summary><b>Read before submit</b></summary>
<br>i put -Dorg.lwjgl.opengl.libname=libgl4es_115.so
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</i put -Dorg.lwjgl.opengl.libname=libgl4es_115.so and it crashes
### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_20210616-001401.png](https://user-images.githubusercontent.com/85341933/122088159-145c0f00-ce38-11eb-9f93-05a655fa07e4.png)
**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
you made a typo
