### ISSUE TITLE
Supported 1.17 and supported Harmony OS on mobile

### ISSUE THREAD

**Issue by cyans-nya** [PojavLauncherTeam/PojavLauncher#1548]

**Comment by rscAvePlex** [comment]
> 

dude what the fuck

**Comment by khanhduytran0** [comment]
> Support ripping the template.

**Comment by XnimaPRO** [comment]
support Android and Android forks

**Comment by WeirdCoding123** [comment]
Officially Support Android and other Android forks，1.17 support is TBA

**Comment by cyans-nya** [comment]
Harmony OS is not change by Android
it use Android Runtime to run Android Apps

**Comment by rscAvePlex** [comment]
> Harmony OS is not change by android
> it use android runtime to run android apps

the fck are you saying now?

**Comment by cyans-nya** [comment]
...

**Comment by khanhduytran0** [comment]
So why would you request to support although it's Android without Google services?

**Comment by cyans-nya** [comment]
Not Android
It's Harmony OS
See this: https://www.harmonyos.com/en/home/

**Comment by rscAvePlex** [comment]
> Not Android
> It's Harmony OS
> See this: https://www.harmonyos.com/en/home/

DUDE ITS JUST BASICALLY ANDROID BUT PROVIDED FOR AN SPECIFIC PHONE

**Comment by cyans-nya** [comment]
If I start Pojav in Harmony OS
show the version list, It no version, and throw error

**Comment by JustAMinecrafter** [comment]
Lmao I saw those Chinese characters

**Comment by cyans-nya** [comment]
> Lmao I saw those Chinese characters

Because I using translate

**Comment by rscAvePlex** [comment]
> > Lmao I saw those Chinese characters
> 
> Because I using translate
> 

yeah we can't really 'sus' your grammar

**Comment by WeirdCoding123** [comment]
it's stupid for you to show the different opinion of harmony OS you have at here,this is devs community not Chinese sh1t social networks like weibo. Btw Pojav works in my huawei Mate 30 with harmony Android 2

**Comment by cyans-nya** [comment]
> it's stupid for you to show the different opinion of harmony OS you have at here,this is devs community not Chinese sh1t social networks like weibo. Btw Pojav works in my huawei Mate 30 with harmony Android 2

But I just see no versions

**Comment by cyans-nya** [comment]
> > it's stupid for you to show the different opinion of harmony OS you have at here,this is devs community not Chinese sh1t social networks like weibo. Btw Pojav works in my huawei Mate 30 with harmony Android 2
> 
> But I just see no versions

When I use Android, I can saw versions

**Comment by khanhduytran0** [comment]
~~because you haven't connected to internet?~~

**Comment by khanhduytran0** [comment]
*internet

**Comment by khanhduytran0** [comment]
Also, copy the error you see. We don't have HarmonyOS to reproduce ~~although taking an emulator would be option~~

**Comment by cyans-nya** [comment]
I was check the internet
And the next day it was still not work

**Comment by cyans-nya** [comment]
> 此外，复制您看到的错误。我们没有和谐OS复制~，虽然采取模拟器将是选项~

Just the version list show no versions

**Comment by cyans-nya** [comment]
I try to delete game folder
And it still show no versions

**Comment by WeirdCoding123** [comment]
mojang asset server may got blocked on your region,you may need an VPN to download the file, netease or bmcapi stuff is not (and never gonna) supported

**Comment by ENDERMANYK** [comment]
> > 此外，复制您看到的错误。我们没有和谐OS复制~，虽然采取模拟器将是选项~
> 
> Just the version list show no versions

在sdcard/0/games/Pojavlauncher下有个latestlog.txt，能不能发过来？不过我感觉应该是网的问题无法显示版本？

**Comment by cyans-nya** [comment]
![image](https://user-images.githubusercontent.com/68551684/122176904-b0792b00-ceb7-11eb-8ba0-4a93c8bc3151.png)
I can get the version

**Comment by cyans-nya** [comment]
> > > 此外，复制您看到的错误。我们没有和谐OS复制~，虽然采取模拟器将是选项~
> > 
> > 
> > Just the version list show no versions
> 
> 在sdcard/0/games/Pojavlauncher下有个latestlog.txt，能不能发过来？不过我感觉应该是网的问题无法显示版本？

/games/Pojavlauncher 找不到东西，不知道是不是隐藏了？
但是我看着有大小

**Comment by ENDERMANYK** [comment]
> > > > 此外，复制您看到的错误。我们没有和谐OS复制~，虽然采取模拟器将是选项~
> > > 
> > > 
> > > Just the version list show no versions
> > 
> > 
> > 在sdcard/0/games/Pojavlauncher下有个latestlog.txt，能不能发过来？不过我感觉应该是网的问题无法显示版本？
> 
> /games/Pojavlauncher 找不到东西，不知道是不是隐藏了？
> 但是我看着有大小

我没用过鸿蒙但听说为了兼容安卓所以应该和安卓路径一样？这个是安卓的路径

**Comment by mchnjt** [comment]
> ![image](https://user-images.githubusercontent.com/68551684/122176904-b0792b00-ceb7-11eb-8ba0-4a93c8bc3151.png)
> I can get the version

Dude that ain't our launcher

**Comment by cyans-nya** [comment]
> > > > > 此外，复制您看到的错误。我们没有和谐OS复制~，虽然采取模拟器将是选项~
> > > > 
> > > > 
> > > > Just the version list show no versions
> > > 
> > > 
> > > 在sdcard/0/games/Pojavlauncher下有个latestlog.txt，能不能发过来？不过我感觉应该是网的问题无法显示版本？
> > 
> > 
> > /games/Pojavlauncher 找不到东西，不知道是不是隐藏了？
> > 但是我看着有大小
> 
> 我没用过鸿蒙但听说为了兼容安卓所以应该和安卓路径一样？这个是安卓的路径

我看它是com.XXXXXX.XXXXXX然后pojavlauncher啥的?

**Comment by cyans-nya** [comment]
> > > > > > 此外，复制您看到的错误。我们没有和谐OS复制~，虽然采取模拟器将是选项~
> > > > > 
> > > > > 
> > > > > Just the version list show no versions
> > > > 
> > > > 
> > > > 在sdcard/0/games/Pojavlauncher下有个latestlog.txt，能不能发过来？不过我感觉应该是网的问题无法显示版本？
> > > 
> > > 
> > > /games/Pojavlauncher 找不到东西，不知道是不是隐藏了？
> > > 但是我看着有大小
> > 
> > 
> > 我没用过鸿蒙但听说为了兼容安卓所以应该和安卓路径一样？这个是安卓的路径
> 
> 我看它是com.XXXXXX.XXXXXX然后pojavlauncher啥的?

不是Pojavlauncher，我当时觉得是版本更新的原因
我在某B站，某达baka，看到了

**Comment by WesleyVanNeck** [comment]
> > > > > > 此外，复制您看到的错误。我们没有和谐OS复制~，虽然采取模拟器将是选项~
> > > > > 
> > > > > 
> > > > > Just the version list show no versions
> > > > 
> > > > 
> > > > 在sdcard/0/games/Pojavlauncher下有个latestlog.txt，能不能发过来？不过我感觉应该是网的问题无法显示版本？
> > > 
> > > 
> > > /games/Pojavlauncher 找不到东西，不知道是不是隐藏了？
> > > 但是我看着有大小
> > 
> > 
> > 我没用过鸿蒙但听说为了兼容安卓所以应该和安卓路径一样？这个是安卓的路径
> 
> 我看它是com.XXXXXX.XXXXXX然后pojavlauncher啥的?

English or you get baned

**Comment by WesleyVanNeck** [comment]
Also that's not our launcher for sure

**Comment by ghost** [comment]
Bruh

**Comment by ghost** [comment]
when someone doesn't read the announcement

Be like :

**Comment by cyans-nya** [comment]
Oh, If you think open a Issue were wrong
I can close!
I didn't want quarrel...
