### ISSUE TITLE
[BUG] <game won't staer>

### ISSUE THREAD

**Issue by LostandFoundOwner** [PojavLauncherTeam/PojavLauncher#1549]
I put in the color code for pojav and my game just crashes on startup

<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected my game to open 

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
- [ ] https://user-images.githubusercontent.com/85341933/122180691-3d71b380-cebb-11eb-9958-e0e0a2d62c94.mp4
**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
no, we don't have permission to remote your device to get the log.

**Comment by khanhduytran0** [comment]
Also, **video doesn't help at all, it doesn't contain log!** And you have an outdated launcher build, use this instead, then set renderer to `gl4es 1.1.5 (OpenGL ES 3)`: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/938939284

**Comment by LostandFoundOwner** [comment]
Dude

**Comment by LostandFoundOwner** [comment]
I beed color

**Comment by LostandFoundOwner** [comment]
Need
