### ISSUE TITLE
[F-REQ] Add OpenCL support in pojav launcher 

### ISSUE THREAD

**Issue by scihi** [PojavLauncherTeam/PojavLauncher#1550]
I was thinking about the devices which doesn't support vulkan so can openCL be an replacement for it ? Because openCL is having much supported devices than vulkan.

**Comment by scihi** [comment]
And for more improvement in performance

**Comment by khanhduytran0** [comment]
Bruh, OpenCL is not a rendering engine, **it's computing engine** and Minecraft doesn't use it, so adding support would just increase app size but do nothing.
