### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#1554]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

I am playing then I add open4es shader then after that the game crashed.

**Add a log file if you want to see your bug fixed !**

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/17/21 9:40 AM
Description: Unexpected error

java.lang.NoSuchMethodError: org.lwjgl.opengl.ARBVertexShader.glVertexAttribPointerARB(IIZZILjava/nio/ShortBuffer;)V
	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
	at bmh.a(Tessellator.java:169)
	at bno.a(Render.java:304)
	at blo.a(WorldRenderer.java:205)
	at bma.a(RenderGlobal.java:2382)
	at blt.a(EntityRenderer.java:1657)
	at blt.b(EntityRenderer.java:1392)
	at bao.ak(SourceFile:801)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
	at bmh.a(Tessellator.java:169)
	at bno.a(Render.java:304)
	at blo.a(WorldRenderer.java:205)
	at bma.a(RenderGlobal.java:2382)
	at blt.a(EntityRenderer.java:1657)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bjk['PlayerLancE'/739, l='MpServer', x=279.32, y=65.62, z=289.19]]
	Chunk stats: MultiplayerChunkCache: 35, 44
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (252,64,252), Chunk: (at 12,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 851 game time, 851 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 48 total; [yq['Zombie'/1046, l='MpServer', x=241.50, y=15.00, z=328.50], ya['Enderman'/2605, l='MpServer', x=270.75, y=40.33, z=230.31], yn['Spider'/1073, l='MpServer', x=247.42, y=34.05, z=336.39], yl['Skeleton'/1076, l='MpServer', x=319.50, y=29.00, z=250.50], yl['Skeleton'/1077, l='MpServer', x=319.50, y=29.00, z=252.50], yq['Zombie'/1081, l='MpServer', x=259.50, y=41.00, z=305.50], we['Bat'/832, l='MpServer', x=256.53, y=46.55, z=302.27], ws['Squid'/833, l='MpServer', x=250.50, y=60.97, z=333.91], ws['Squid'/834, l='MpServer', x=245.81, y=60.91, z=334.47], yq['Zombie'/837, l='MpServer', x=269.50, y=35.61, z=236.50], ws['Squid'/839, l='MpServer', x=245.19, y=61.31, z=317.31], ws['Squid'/840, l='MpServer', x=240.50, y=61.28, z=313.47], ws['Squid'/841, l='MpServer', x=242.59, y=60.69, z=318.56], ws['Squid'/842, l='MpServer', x=243.50, y=58.97, z=315.78], we['Bat'/847, l='MpServer', x=269.75, y=38.14, z=224.16], yn['Spider'/1103, l='MpServer', x=246.29, y=34.35, z=339.32], yl['Skeleton'/1104, l='MpServer', x=246.29, y=34.53, z=339.32], xk['item.item.seeds'/1106, l='MpServer', x=281.19, y=63.13, z=276.88], yl['Skeleton'/1109, l='MpServer', x=227.50, y=44.00, z=288.50], yq['Zombie'/1110, l='MpServer', x=257.00, y=44.00, z=299.44], yq['Zombie'/1111, l='MpServer', x=264.50, y=41.00, z=303.50], yq['Zombie'/1112, l='MpServer', x=264.50, y=34.16, z=228.50], we['Bat'/2648, l='MpServer', x=314.54, y=29.00, z=278.54], yq['Zombie'/1118, l='MpServer', x=263.50, y=34.16, z=229.50], yq['Zombie'/2663, l='MpServer', x=240.50, y=48.00, z=301.50], yq['Zombie'/2664, l='MpServer', x=235.50, y=48.00, z=301.50], yq['Zombie'/2665, l='MpServer', x=235.50, y=48.00, z=298.50], yq['Zombie'/1133, l='MpServer', x=224.50, y=9.35, z=236.50], yq['Zombie'/1135, l='MpServer', x=228.50, y=9.35, z=237.50], yq['Zombie'/1136, l='MpServer', x=224.50, y=13.00, z=240.50], ya['Enderman'/1222, l='MpServer', x=273.47, y=39.33, z=233.34], yl['Skeleton'/986, l='MpServer', x=287.50, y=34.91, z=227.50], yq['Zombie'/740, l='MpServer', x=237.50, y=51.00, z=303.50], bjk['PlayerLancE'/739, l='MpServer', x=279.32, y=65.62, z=289.19], xz['Creeper'/743, l='MpServer', x=291.56, y=28.42, z=238.22], xz['Creeper'/1255, l='MpServer', x=232.50, y=25.00, z=305.50], xz['Creeper'/744, l='MpServer', x=281.56, y=31.00, z=244.69], xz['Creeper'/745, l='MpServer', x=281.72, y=31.42, z=231.84], xz['Creeper'/1257, l='MpServer', x=230.50, y=25.00, z=307.50], xz['Creeper'/746, l='MpServer', x=291.50, y=28.42, z=235.50], xz['Creeper'/1258, l='MpServer', x=224.34, y=25.00, z=309.50], xz['Creeper'/1259, l='MpServer', x=236.50, y=25.00, z=305.50], we['Bat'/1004, l='MpServer', x=266.91, y=35.66, z=226.44], we['Bat'/1014, l='MpServer', x=282.58, y=12.61, z=311.40], wg['Chicken'/248, l='MpServer', x=318.50, y=63.00, z=259.50], wg['Chicken'/249, l='MpServer', x=316.50, y=64.00, z=257.50], wg['Chicken'/250, l='MpServer', x=317.50, y=63.00, z=257.50], yl['Skeleton'/1023, l='MpServer', x=269.50, y=16.00, z=244.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bjf.a(WorldClient.java:425)
	at bao.b(SourceFile:1972)
	at bao.f(SourceFile:742)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version Android-8.1.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 730896320 bytes (697 MB) / 979369984 bytes (934 MB) up to 979369984 bytes (934 MB)
	JVM Flags: 3 total; -Xms1000M -Xmx1000M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.7.10
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Open4Es-Shader-Android-1.1-Beta2.zip
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 4
The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .

You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
2. Launch 1.7.10
3. Play
4. I add shader to make my world beautiful.
5. the game crashed

### Expected behavior:
I expected when I add shaders in my world it will not crash.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128] CPH1853
 - CPU architecture [e.g. aarch64] aarch64
 - Android Version [e.g. 10] 8.1
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Why thers so many problems?
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
shaders are not combatible hook a rtx 3090 on your phone

**Comment by rscAvePlex** [comment]
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> <br>
> - Make sure there was not duplicated issues.<br>
> - Make sure you have filled this issue template, or this will get rejected.
> </details>
> 
> ### Describe the bug
> A clear and concise description of what the bug is.
> 
> I am playing then I add open4es shader then after that the game crashed.
> 
> **Add a log file if you want to see your bug fixed !**
> 
> ---- Minecraft Crash Report ----
> // Who set us up the TNT?
> 
> Time: 6/17/21 9:40 AM
> Description: Unexpected error
> 
> java.lang.NoSuchMethodError: org.lwjgl.opengl.ARBVertexShader.glVertexAttribPointerARB(IIZZILjava/nio/ShortBuffer;)V
> 	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
> 	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
> 	at bmh.a(Tessellator.java:169)
> 	at bno.a(Render.java:304)
> 	at blo.a(WorldRenderer.java:205)
> 	at bma.a(RenderGlobal.java:2382)
> 	at blt.a(EntityRenderer.java:1657)
> 	at blt.b(EntityRenderer.java:1392)
> 	at bao.ak(SourceFile:801)
> 	at bao.f(SourceFile:728)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
> 	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
> 	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
> 	at bmh.a(Tessellator.java:169)
> 	at bno.a(Render.java:304)
> 	at blo.a(WorldRenderer.java:205)
> 	at bma.a(RenderGlobal.java:2382)
> 	at blt.a(EntityRenderer.java:1657)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [bjk['PlayerLancE'/739, l='MpServer', x=279.32, y=65.62, z=289.19]]
> 	Chunk stats: MultiplayerChunkCache: 35, 44
> 	Level seed: 0
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (252,64,252), Chunk: (at 12,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 851 game time, 851 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Forced entities: 48 total; [yq['Zombie'/1046, l='MpServer', x=241.50, y=15.00, z=328.50], ya['Enderman'/2605, l='MpServer', x=270.75, y=40.33, z=230.31], yn['Spider'/1073, l='MpServer', x=247.42, y=34.05, z=336.39], yl['Skeleton'/1076, l='MpServer', x=319.50, y=29.00, z=250.50], yl['Skeleton'/1077, l='MpServer', x=319.50, y=29.00, z=252.50], yq['Zombie'/1081, l='MpServer', x=259.50, y=41.00, z=305.50], we['Bat'/832, l='MpServer', x=256.53, y=46.55, z=302.27], ws['Squid'/833, l='MpServer', x=250.50, y=60.97, z=333.91], ws['Squid'/834, l='MpServer', x=245.81, y=60.91, z=334.47], yq['Zombie'/837, l='MpServer', x=269.50, y=35.61, z=236.50], ws['Squid'/839, l='MpServer', x=245.19, y=61.31, z=317.31], ws['Squid'/840, l='MpServer', x=240.50, y=61.28, z=313.47], ws['Squid'/841, l='MpServer', x=242.59, y=60.69, z=318.56], ws['Squid'/842, l='MpServer', x=243.50, y=58.97, z=315.78], we['Bat'/847, l='MpServer', x=269.75, y=38.14, z=224.16], yn['Spider'/1103, l='MpServer', x=246.29, y=34.35, z=339.32], yl['Skeleton'/1104, l='MpServer', x=246.29, y=34.53, z=339.32], xk['item.item.seeds'/1106, l='MpServer', x=281.19, y=63.13, z=276.88], yl['Skeleton'/1109, l='MpServer', x=227.50, y=44.00, z=288.50], yq['Zombie'/1110, l='MpServer', x=257.00, y=44.00, z=299.44], yq['Zombie'/1111, l='MpServer', x=264.50, y=41.00, z=303.50], yq['Zombie'/1112, l='MpServer', x=264.50, y=34.16, z=228.50], we['Bat'/2648, l='MpServer', x=314.54, y=29.00, z=278.54], yq['Zombie'/1118, l='MpServer', x=263.50, y=34.16, z=229.50], yq['Zombie'/2663, l='MpServer', x=240.50, y=48.00, z=301.50], yq['Zombie'/2664, l='MpServer', x=235.50, y=48.00, z=301.50], yq['Zombie'/2665, l='MpServer', x=235.50, y=48.00, z=298.50], yq['Zombie'/1133, l='MpServer', x=224.50, y=9.35, z=236.50], yq['Zombie'/1135, l='MpServer', x=228.50, y=9.35, z=237.50], yq['Zombie'/1136, l='MpServer', x=224.50, y=13.00, z=240.50], ya['Enderman'/1222, l='MpServer', x=273.47, y=39.33, z=233.34], yl['Skeleton'/986, l='MpServer', x=287.50, y=34.91, z=227.50], yq['Zombie'/740, l='MpServer', x=237.50, y=51.00, z=303.50], bjk['PlayerLancE'/739, l='MpServer', x=279.32, y=65.62, z=289.19], xz['Creeper'/743, l='MpServer', x=291.56, y=28.42, z=238.22], xz['Creeper'/1255, l='MpServer', x=232.50, y=25.00, z=305.50], xz['Creeper'/744, l='MpServer', x=281.56, y=31.00, z=244.69], xz['Creeper'/745, l='MpServer', x=281.72, y=31.42, z=231.84], xz['Creeper'/1257, l='MpServer', x=230.50, y=25.00, z=307.50], xz['Creeper'/746, l='MpServer', x=291.50, y=28.42, z=235.50], xz['Creeper'/1258, l='MpServer', x=224.34, y=25.00, z=309.50], xz['Creeper'/1259, l='MpServer', x=236.50, y=25.00, z=305.50], we['Bat'/1004, l='MpServer', x=266.91, y=35.66, z=226.44], we['Bat'/1014, l='MpServer', x=282.58, y=12.61, z=311.40], wg['Chicken'/248, l='MpServer', x=318.50, y=63.00, z=259.50], wg['Chicken'/249, l='MpServer', x=316.50, y=64.00, z=257.50], wg['Chicken'/250, l='MpServer', x=317.50, y=63.00, z=257.50], yl['Skeleton'/1023, l='MpServer', x=269.50, y=16.00, z=244.50]]
> 	Retry entities: 0 total; []
> 	Server brand: vanilla
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at bjf.a(WorldClient.java:425)
> 	at bao.b(SourceFile:1972)
> 	at bao.f(SourceFile:742)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Operating System: Linux (aarch64) version Android-8.1.0
> 	Java Version: 1.8.0-internal, Oracle Corporation
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 730896320 bytes (697 MB) / 979369984 bytes (934 MB) up to 979369984 bytes (934 MB)
> 	JVM Flags: 3 total; -Xms1000M -Xmx1000M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
> 	Launched Version: 1.7.10
> 	LWJGL: 3.2.3 SNAPSHOT
> 	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
> 	GL Caps: Using GL 1.3 multitexturing.
> Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
> Anisotropic filtering is supported and maximum anisotropy is 16.
> Shaders are available because OpenGL 2.1 is supported.
> 
> 	Is Modded: Very likely; Jar signature invalidated
> 	Type: Client (map_client.txt)
> 	Resource Packs: []
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	Anisotropic Filtering: Off (1)
> 	OptiFine Version: OptiFine_1.7.10_HD_U_E7
> 	Render Distance Chunks: 2
> 	Mipmaps: 0
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: Open4Es-Shader-Android-1.1-Beta2.zip
> 	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
> 	OpenGlRenderer: GL4ES wrapper
> 	OpenGlVendor: ptitSeb
> 	CpuCount: 4
> The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
> 
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> ... *(your set of actions to reproduce the bug)*
> 2. Launch 1.7.10
> 3. Play
> 4. I add shader to make my world beautiful.
> 5. the game crashed
> 
> ### Expected behavior:
> I expected when I add shaders in my world it will not crash.
> 
> ### Screenshots or videos:
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> 
> **Platform:**
>  - Device Model [e.g. Mi 8 Pro 8/128] CPH1853
>  - CPU architecture [e.g. aarch64] aarch64
>  - Android Version [e.g. 10] 8.1
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> <details> <summary><b>Additional context</b></summary>
> <br>
> <pre>
> Why thers so many problems?
> </pre>
> </details>
> 

damn why copy paste the latestlog problemo if u could just upload it

**Comment by LanceAldrei04** [comment]
> shaders are not combatible hook a rtx 3090 on your phone

what are you talking about?

**Comment by khanhduytran0** [comment]
> shaders are not combatible hook a rtx 3090 on your phone

@LegacyGamerHD ~~bruh~~ why need RTX for Open4ES

**Comment by khanhduytran0** [comment]
@lalalalalalalalalalalalalalalalalala000 you shouldn’t run shader on 1.11 and below(?)

**Comment by WesleyVanNeck** [comment]
> @lalalalalalalalalalalalalalalalalala000 you shouldn’t run shader on 1.11 and below(?)

Wait open4es

**Comment by ENDERMANYK** [comment]
> > shaders are not combatible hook a rtx 3090 on your phone
> 
> what are you talking about?

Pojavlauncher can't run shader in 1.7.10 version, its a known issue #642

**Comment by LanceAldrei04** [comment]
> > > shaders are not combatible hook a rtx 3090 on your phone
> > 
> > 
> > what are you talking about?
> 
> Pojavlauncher can't run shader in 1.7.10 version, its a known issue #642

What versions can run this shader?

**Comment by mchnjt** [comment]
> > > > shaders are not combatible hook a rtx 3090 on your phone
> > > 
> > > 
> > > what are you talking about?
> > 
> > 
> > Pojavlauncher can't run shader in 1.7.10 version, its a known issue #642
> 
> What versions can run this shader?

It can (possibly) run on 1.8 above. Don't forget about the version's optifine.
