### ISSUE TITLE
V3 Preview 3 error (VMOS)

### ISSUE THREAD

**Issue by Pawoog** [PojavLauncherTeam/PojavLauncher#156]
![20200428_153740](https://user-images.githubusercontent.com/63868443/80487902-378edb00-8966-11ea-9540-b6d5bf148df6.png)

**Comment by khanhduytran0** [comment]
Try delete data and launch again.

**Comment by Pawoog** [comment]
I deleted all data and reinstalled the app and it gives me the same error

**Comment by khanhduytran0** [comment]
Duplicate with #148

**Comment by WesleyVanNeck** [comment]
maby fixed
