### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1560]
What zink working all shader on adreno processor?

**Comment by GamerYTofficial** [comment]
maybe??? I don't know!!?

**Comment by GamerYTofficial** [comment]
I am curious??!!

**Comment by WesleyVanNeck** [comment]
Ask such thing on discord not here

**Comment by WesleyVanNeck** [comment]
Also zink is laggy slow and we don't provide support for it
