### ISSUE TITLE
[BUG] if open the game, game not open

### ISSUE THREAD

**Issue by ProPlayer889** [PojavLauncherTeam/PojavLauncher#1561]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by NotAHero04** [comment]
No latestlog.txt so I can’t know your problem. Some possible things that can happen to your game:
using unsupported or false JVM arguments -> JVM crashes
playing 1.17 or later -> game crashes

**Comment by Mathias-Boulay** [comment]
Fill the template or the issue will be terminated.

**Comment by ProPlayer889** [comment]
Ok

Il Ven 18 Giu 2021, 18:31 Boulay Mathias ***@***.***> ha
scritto:

**Comment by pinox14xd** [comment]
Simplemente descarge la vesion mas actual y cuando lo abro solo me aparecen los  botones  y la pantalla esta en negro y dice el juego se a cerrado con codigo 1

**Comment by khanhduytran0** [comment]
@ProPlayer889 template is still not filled. Closing
