### ISSUE TITLE
Increase maximum memory allocation

### ISSUE THREAD

**Issue by LemonSquare121307** [PojavLauncherTeam/PojavLauncher#1565]
I have 4gb ram and installed the playstore version of pojav launcher but the maximum memory allocation is only upto 800 mb. If possible, how can I increase the maximum memory allocation to 1gb or more?

**Comment by rscAvePlex** [comment]
> I have 4gb ram and installed the playstore version of pojav launcher but the maximum memory allocation is only upto 800 mb. If possible, how can I increase the maximum memory allocation to 1gb or more? 

laugh about that, ur device is 32bit
