### ISSUE TITLE
[BUG] Bad virtual keyboard

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#1568]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I have a very big problem with the keyboard
**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6681845/latestlog.txt)

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
2. Launch MC 1.16.5
3. Select a world
4. Tap "Keyboard" button
### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

https://user-images.githubusercontent.com/75970303/122664890-a23c4f00-d1d6-11eb-822f-db1eb475de38.mp4

**Platform:**
 -Phone Specs (FULL)

https://www.gsmarena.com/oppo_a12e-10173.php

 - PojavLauncher Version  version 3.3.1.1_rel_20210819

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
The only question is how can I fix it.
</pre>
</details>

**Comment by nabiloi** [comment]
So what's the bug?

**Comment by LANCECRAFT1104** [comment]
> So what's the bug?

Watch the video.

**Comment by Mathias-Boulay** [comment]
The keyboard is unsupported.
Use a better one like gboard 🤔 @LANCECRAFT1104

**Comment by LANCECRAFT1104** [comment]
> The keyboard is unsupported.
> Use a better one like gboard 🤔 @LANCECRAFT1104

I am using GBOARD

**Comment by LANCECRAFT1104** [comment]
Yeah i am using GBOARD

**Comment by WesleyVanNeck** [comment]
> Yeah i am using GBOARD

use it wihout a skin and update it as its clearly outdated

**Comment by ghost** [comment]
use hackers keyboard

**Comment by VII002** [comment]
Install a different keyboard or Update your current one. I use Yandex Keyboard and it works fine.

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
