### ISSUE TITLE
[BUG] Sodium Mod Crashing

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#1570]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I installed sodium mod but when I select a world the game crashing.
**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6682325/latestlog.txt)
[crash-2021-06-20_12.39.26-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6682328/crash-2021-06-20_12.39.26-client.txt)

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
2. Launch fabric 1.16.5
3. Modify video settings
4. Select a world
5. the game crashed (THE END)
### Expected behavior:
I expected sodium mod will not crashed.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
https://m.gsmarena.com/oppo_a12e-ampp-10173.php
 - Device Model [e.g. Mi 8 Pro 8/128] CPH1853
 - CPU architecture [e.g. aarch64] aarch64
 - Android Version [e.g. 10] 8.1
 - PojavLauncher Version Latest Actions || version 3.3.1.1_rel_20210619 

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Why sodium mod not working on my phone?
</pre>
</details>

**Comment by LANCECRAFT1104** [comment]
Like #1518. I turned off vertex and fog on video settings but still crashing. Ey

**Comment by Zeyrox1090** [comment]
fog occlusion something idk turn it off

**Comment by Animenoyuusha19** [comment]
[DOC-20240605-WA0000..txt](https://github.com/user-attachments/files/15570709/DOC-20240605-WA0000.txt)
Everytime I join the game it says sodium issues
