### ISSUE TITLE
The Modpacks crash

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1577]
Describe the bug
When I play the Modpacks for 2-3m my game hung and crash

Modpacks server pack link:
https://www.curseforge.com/minecraft/modpacks/zombie-apocalypse-slow-zombies-by-forge-labs/files/3249213

Add a log file if you want to see your bug fixed !

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6698495/latestlog.txt)

[debuglog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6698496/debuglog.txt)

[betterfoliagelog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6698498/betterfoliagelog.txt)

The log file called latestlog.txt is located under "Android/data/net.kdt.pojavlaunch/files", "games/PojavLauncher/" or "games/PojavLauncher/.minecraft" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

Platform:
https://www.google.com/amp/s/m.gsmarena.com/xiaomi_mi_9t-ampp-9738.php

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*
2. Launch forge 1.12.2
3. Modified the setting
4. Select the world
5. Walking 2 - 3m
6. Game hung and crash

### Expected behavior:
I expected modpack will not crashed

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128] mi 9t
 - CPU architecture [e.g. aarch64] aarch64
 - Android Version [e.g. 10] 10
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by nabiloi** [comment]
Latest.log ≠ Latestlog.txt

**Comment by kedrick021** [comment]
> Latest.log ≠ Latestlog.txt

Why it's same download and same text?

**Comment by rscAvePlex** [comment]
> > Latest.log ≠ Latestlog.txt
> 
> Why it's same download and same text?

Fucktard

~~Latest.log is from shitinabox

Pojav's log is latestlog.txt~~

**Comment by kedrick021** [comment]
> > > Latest.log ≠ Latestlog.txt
> > 
> > 
> > Why it's same download and same text?
> 
> Fucktard
> 
> ~~Latest.log is from shitinabox
> 
> Pojav's log is latestlog.txt~~

Are you right in your mind right now
This is pojavlauncher site not shitinabox your talking
Go to log folder you will get knowledge

**Comment by khanhduytran0** [comment]
@kedrick021 **bruh**
> The log file called latestlog.txt is located under "Android/data/net.kdt.pojavlaunch/files", "games/PojavLauncher/" or "games/PojavLauncher/.minecraft" .
You may need to activate an option in your file explorer to see hidden files and folders.

Haven't you read this?

**Comment by khanhduytran0** [comment]
**No log folder is listed!**

**Comment by kedrick021** [comment]
> **No log folder is listed!**

Ok I edit ........again
