### ISSUE TITLE
Modpacks crash in 1.12.2

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1579]
Describe the bug

When I  play for 2 - 3m the game hung and crash

Add a log file if you want to see your bug fixed !

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6703523/latestlog.txt)

The log file called latestlog.txt is located under "Android/data/net.kdt.pojavlaunch/files", "games/PojavLauncher/" or "games/PojavLauncher/.minecraft" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

To Reproduce:
Indicate steps to reproduce the buggy behavior:

Start PojavLauncher
... (your set of actions to reproduce the bug)
Launch forge 1.12.2
Modify video settings
Select a world
Walking for 2 - 3m the game hung and crash

Expected behavior:
I expected the modpack will not crash

Screenshots or videos:
Upload here screenshots or videos of the buggy behavior, if possible.

Platform:
https://www.google.com/amp/s/m.gsmarena.com/xiaomi_mi_9t-ampp-9738.php

Phone specs
6gbram - 128gbrom

Device Model [e.g. Mi 8 Pro 8/128] mi 9t
CPU architecture [e.g. aarch64] aarch64
Android Version [e.g. 10] 10
PojavLauncher Version Latest Actions || version 3.3.1.1_rel_20210619

**Comment by kedrick021** [comment]
Plsss help always crash when render is added to 3,4,5,6,7,8 in 1.12.2 when add render 8 in 1.15 - 1.16+
Is not crash in that version with mods

**Comment by khanhduytran0** [comment]
So, maybe the game ran out of memory.

**Comment by kedrick021** [comment]
> So, maybe the game ran out of memory.

I try add only one mod but is crashed to i only add 3,4 render even 2 is crashed

**Comment by kedrick021** [comment]
I have 6gb ram only 3gb ram I using to play

**Comment by kedrick021** [comment]
Smooth play in 1.15 - 1.16+ without crash with 11 mods only 1.12.2 always crash

**Comment by kedrick021** [comment]
I try the fix render crash update 2/3 in 1.12.2 and you know what happen .



Is not crash anymore I add mods that always crash in 1.12.2 smooth play without crash even add shader thx☺️

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
