### ISSUE TITLE
3.0 preview 3 launch bug

### ISSUE THREAD

**Issue by limeisgood9** [PojavLauncherTeam/PojavLauncher#158]
When i launch it says:

OpenJDK Runtime
sh: <stdin>[3]: /data/data/net.kdt.pojavlaunch/jre/usr/bin/java: not executable: 64-bit ELF file

My device: Xiaomi Redmi 6, Android 9.
And on VMOS same.

**Comment by khanhduytran0** [comment]
You are on a 32-bit device and not supported. Go back to v2.5.

**Comment by limeisgood9** [comment]
My processor is 64 bit, i found it in phone specs. And if my phone really 32 bit, 32 bit be supported?

**Comment by khanhduytran0** [comment]
> And if my phone really 32 bit, 32 bit be supported?

No, also if your CPU is 64bit and your Android is 32bit also can't run v3.

**Comment by limeisgood9** [comment]
32 bit will be supported?

**Comment by khanhduytran0** [comment]
May not, if I make support for 32-bit, it requires root.

**Comment by limeisgood9** [comment]
Root not problem, vmos help me.

**Comment by khanhduytran0** [comment]
Ok, but it takes lots of times to change to armv7. So I will do later.

**Comment by limeisgood9** [comment]
Optifine doesn’t work for me, but once it somehow started and worked fine.  Why doesn’t it work for me now?

**Comment by khanhduytran0** [comment]
> Optifine doesn’t work for me, but once it somehow started and worked fine.  Why doesn’t it work for me now?

In v2, there are some devices can't run OptiFine due to many weird errors, other works fine even zoom or graphics settings like me.

In v3, there are in development and installers working without font like below, not only Forge installer.
![Screenshot_2020-04-30-15-41-41](https://user-images.githubusercontent.com/40482367/80690602-3e018c00-8af9-11ea-8c37-e4a9a37a41d3.png)

**Comment by khanhduytran0** [comment]
Minecraft won't start in v3 so can't sure if OptiFine work on it.

**Comment by limeisgood9** [comment]
There is a way to allocate more memory for Minecraft? I want to do this because I have permanent lags due to lack of RAM.

**Comment by khanhduytran0** [comment]
> There is a way to allocate more memory for Minecraft? I want to do this because I have permanent lags due to lack of RAM.

Yes with v3 but I'm not added that option yet.

**Comment by limeisgood9** [comment]
I have 4 gb of ram on my phone but Minecraft uses only 384 mb
