### ISSUE TITLE
[BUG] Optifabric Fails to load with pojavlauncher

### ISSUE THREAD

**Issue by Blobanium** [PojavLauncherTeam/PojavLauncher#1581]
Before i start explaining this is extended from https://github.com/Chocohead/OptiFabric/issues/253.

### Describe the bug
Optifabric doesnt work....

latest.log should be in the comments

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher with optifabric installed
2. Error Loading into optifabric!!

### Expected behavior:
I expected it to load optifine properly

**Platform:**
 - Device Model: Samsung Galaxy A51 5G UW
 - CPU architecture: arm64
 - Android Version 11
 - PojavLauncher Version: latest

**Comment by Blobanium** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6706226/latestlog.txt)

**Comment by Dark-Lord-Pro** [comment]
Use fabric API and put specific optifine version the optifabric requires in mod folder

**Comment by renz99999** [comment]
[Uploading latestlog.txt…]()

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by YALGAROP** [comment]
I am also facing this problem plss tell the solution device redmi note 8 pro processor arm 64

**Comment by hasangamse** [comment]
![Screenshot_2024-01-28-14-18-41-47](https://github.com/PojavLauncherTeam/PojavLauncher/assets/157950732/5884a6be-a818-4d9a-b68b-35dbd7c2f989)
