### ISSUE TITLE
Always crash in 1.12.2 forge

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1583]
Describe the bug

Always crash in 1.12.2 forge even only 2 mods insert

Add a log file if you want to see your bug fixed !

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6708084/latestlog.txt)

The log file called latestlog.txt is located under "Android/data/net.kdt.pojavlaunch/files", "games/PojavLauncher/" or "games/PojavLauncher/.minecraft" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

To Reproduce:
Indicate steps to reproduce the buggy behavior:

Start PojavLauncher
... (your set of actions to reproduce the bug)
Launch forge 1.12.2
Modify video settings
Select a world
Play for 3 - 4m
Game hung and crash always crash

Expected behavior:
I expected the game not crashed

Screenshots or videos:
Upload here screenshots or videos of the buggy behavior, if possible.

Platform:
https://www.google.com/amp/s/m.gsmarena.com/xiaomi_mi_9t-ampp-9738.php

Spec: 6gb ram and 64gb rom

Device Model [e.g. Mi 8 Pro 8/128]Mi 9t
CPU architecture [e.g. aarch64] aarch64
Android Version [e.g. 10] 10
PojavLauncher Version Latest Actions || version 3.3.1.1_rel_20210619

**Comment by Nanify69** [comment]
Bro turn vbos on

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
