### ISSUE TITLE
[pixelmon texture error] <pixelmon texture error >

### ISSUE THREAD

**Issue by Saffronpvp** [PojavLauncherTeam/PojavLauncher#1584]
<Details> <summary><b>Pixelmon texture error if I play pixelmon it looks kind of texture error it also occurs when I play server they provide some kind of texture pack it make the texture error

</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I really don't know how it occurs when some kind a mod install it look like that. but it not occurs when install this mods optifine,forge,and fabric.
And mostly occurs when I play pixelmon but 
Some texture look normal like chest armour when u wear .but Pokémon looks perfect without any change and my brother also play pixelmon but it work obsoletely perfect I don't know the reason

**I don't have log because of the texture error !**

The log file called *latestlog.txt* is loc
![Screenshot_2021-06-24-17-41-46-552_net kdt pojavlaunch](https://user-images.githubusercontent.com/86413485/123264948-287acd00-d518-11eb-9cd8-0b555987868b.jpg)
ated under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
I don't know how to reduce but :

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
![Screenshot_2021-06-24-17-40-00-990_net kdt pojavlaunch](https://user-images.githubusercontent.com/86413485/123265084-4cd6a980-d518-11eb-9b64-58d8d30c4600.jpg)

I expected ...

### Screenshots or videos:
![Screenshot_2021-06-24-17-41-46-552_net kdt pojavlaunch](https://user-images.githubusercontent.com/86413485/123261983-09c70700-d515-11eb-9d2c-a72de8fa42b3.jpg)
![Screenshot_2021-06-24-17-40-50-040_net kdt pojavlaunch](https://user-images.githubusercontent.com/86413485/123264730-f10c2080-d517-11eb-99cc-4e03a8e55bd6.jpg)

*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [redmi y3 4/64]
 - CPU architecture [Adreno 506 ] 
 - Android Version [9]
 - PojavLauncher Version [ 1.12.2-forge-14.23.5.2855]

<details> <summary><b>texture error for pixelmon</b></summary>
<br>
<pre>
Add any other context about the problem here
.
</pre>
</details>

**Comment by Saffronpvp** [comment]
Can u plz anyone help me

**Comment by Mathias-Boulay** [comment]
It is a VRAM issue, and is already known.
It cannot be fixed, aside from having a better phone.

**Comment by Saffronpvp** [comment]
There is any other I can fix this

**Comment by Mathias-Boulay** [comment]
Nope, aside from modding pixelmon to use lower resolution textures.

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by Isaac22Mora** [comment]
The same thing happens to me too, can you fix it for me please?

**Comment by Isaac22Mora** [comment]
![Cargando r2{fb7a5d} (8dd9b97b-6129-466e-9474-768f226d2359 id=0x7f0a03b3 tag=BaseCommentFragment) …]()

**Comment by Isaac22Mora** [comment]
![Cargando r2{fb7a5d} (8dd9b97b-6129-466e-9474-768f226d2359 id=0x7f0a03b3 tag=BaseCommentFragment) …]()

**Comment by Isaac22Mora** [comment]
![Cargando r2{fb7a5d} (8dd9b97b-6129-466e-9474-768f226d2359 id=0x7f0a03b3 tag=BaseCommentFragment) …]()

**Comment by Isaac22Mora** [comment]
![Screenshot_2022-04-15-09-50-43-273_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/99103359/163593009-55d404bc-ad4a-4512-8055-43530d750925.jpg)

**Comment by Isaac22Mora** [comment]
![Screenshot_2022-04-15-09-50-22-355_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/99103359/163593070-53bc736e-6883-4c79-b6c5-2856257cdadc.jpg)

**Comment by Isaac22Mora** [comment]
![IMG_20220415_095404.jpg](https://user-images.githubusercontent.com/99103359/163593126-6cd9a745-3094-42cd-a6b5-44d43a06a582.jpg)

**Comment by Isaac22Mora** [comment]
but i have a POCO x3 pro
