### ISSUE TITLE
[BUG] i cant add resourcepacks

### ISSUE THREAD

**Issue by LostandFoundOwner** [PojavLauncherTeam/PojavLauncher#1588]
<my purpled default edit wont show> <when i put the resourcepacks in the folder><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
My bug is that my resourcepack for 1.8.9 doesnt show up i tried unzipping it and it still doesnt work
**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.
Its not a log thing
### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...
My purpledsdefaulteditv1 to work but it didnt pls fix 1.8.9 the resourcepacks dont work
### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by mchnjt** [comment]
> Read before submit
> 
> 
> * Make sure there was not duplicated issues.
> * Make sure you have filled this issue template, or this will get rejected.
> 
> ### Describe the bug
> A clear and concise description of what the bug is.
> My bug is that my resourcepack for 1.8.9 doesnt show up i tried unzipping it and it still doesnt work
> **Add a log file if you want to see your bug fixed !**
> 
> The log file called _latestlog.txt_ is located under "_Android/data/net.kdt.pojavlaunch/files_", "_games/PojavLauncher/_" or "_games/PojavLauncher/.minecraft_" .
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> Its not a log thing
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
>    ... _(your set of actions to reproduce the bug)_
> 
> ### Expected behavior:
> I expected ...
> My purpledsdefaulteditv1 to work but it didnt pls fix 1.8.9 the resourcepacks dont work
> 
> ### Screenshots or videos:
> _Upload here screenshots or videos of the buggy behavior, if possible._
> 
> **Platform:**
> 
> * Device Model [e.g. Mi 8 Pro 8/128]
> * CPU architecture [e.g. aarch64]
> * Android Version [e.g. 10]
> * PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> Additional context

Not enough.

**Comment by mchnjt** [comment]
Please refill/review what u wrote on template.

**Comment by LostandFoundOwner** [comment]
In simple words 1.8.9 resourcepacks wont install

**Comment by khanhduytran0** [comment]
We don't own your device, you know:)

**Comment by khanhduytran0** [comment]
__fill da template bruh__

**Comment by mchnjt** [comment]
> In simple words 1.8.9 resourcepacks wont install

The resourcepack (maybe) isn't for 1.8.9

Solutions:

Check `pack.mcmeta`, then send screenshot (either here or on discord, specifically #general-android) on what u see.

**Comment by LostandFoundOwner** [comment]
Jsut answer how do i install 1.8.9 resource pack

**Comment by mchnjt** [comment]
> > In simple words 1.8.9 resourcepacks wont install
> 
> The resourcepack (maybe) isn't for 1.8.9
> 
> Solutions:
> 
> Check `pack.mcmeta`, then send screenshot (either here or on discord, specifically #general-android) on what u see.

@SlayerOnPpl

**Comment by LostandFoundOwner** [comment]
Im using purpleds default edit

**Comment by mchnjt** [comment]
SMH JUST DO WHAT I SAID

**Comment by khanhduytran0** [comment]
> Im using purpleds default edit 

~~but it's your pack as what you've said, so we can't reproduce~~

**Comment by LostandFoundOwner** [comment]
How do i join discord

**Comment by khanhduytran0** [comment]
~~without your pack~~

**Comment by LostandFoundOwner** [comment]
Its a youtubers pack

**Comment by LostandFoundOwner** [comment]
You guys dont know purpled?

**Comment by khanhduytran0** [comment]
https://discord.gg/pojavlauncher
