### ISSUE TITLE
(Pojavlauncher 2.5.0Prev1) Hotbar Slots don't select properly in other gui mode

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#159]
When i put the GUI setting in Normal Size, the hotbar slots don't select the right slot properly(Small GUI is included too)

**Comment by FranzelDamasco909** [comment]
this is why i confused what i was gonna select

**Comment by khanhduytran0** [comment]
There's no way to detect gui scale change so can't scale hotbar at runtime.

**Comment by khanhduytran0** [comment]
If something like custom hotbar scale may solve the problem.

**Comment by FranzelDamasco909** [comment]
i wanna get my gui turn to Normal Size because i can't scroll to the controls when i turn it to large size
