### ISSUE TITLE
Some Questions About libGL.so and libgl4es114.so

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1598]
Hi, if I write a function implementation of the OpenGL API in C,
And the structure is very simple, like this:
uint glCreateShader(...) {... }.

It contains the OpenGL header file,
But just an implementation of the GL library,
There is nothing about the "X11" display library and GLFW library.

And I just packaged it like this as libgl.so,
Then directly replace libgl4es114. so in POJAV,
So when we start the MC with POJAV,
Can MC still start and render graphics properly?

I would like to know some details (because I am learning OpenGL and GL4ES recently).
Such as LWJGL rendering, OpenGL and GL4ES and GLFW relationship,
What does libgl4es.so(libzink.so/libOSMesa8.so) provide to LWJGL,

If I need to provide a graphics renderer for my MC in pojav, what do I need to provide in libGL.so?
thank you

**Comment by artdeell** [comment]
Pojav doesn't call into gl4es specific functions and provides the EGL context on itself, so you can just swap it with your library that calls into GLES functions.

However, with Zink pojav uses a completely different context management (OSMesa) and renderer.

**Comment by luo9674** [comment]
What is "on itself"？

**Comment by luo9674** [comment]
> Pojav 不会调用特定于 gl4es 的函数，而是在其自身上提供 EGL 上下文，因此您只需将其与调用 GLES 函数的库交换即可。
> 
> 然而，与 Zink pojav 使用完全不同的上下文管理 (OSMesa) 和渲染器。

Where the EGL build up？glfw？
