### ISSUE TITLE
Can You Fix 1.5.2?

### ISSUE THREAD

**Issue by Tryhardbro** [PojavLauncherTeam/PojavLauncher#160]
Downloading 1.5.2 configuration...
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl.lwjgl:lwjgl:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.1-nightly-20130708-debug3
Ignored net.java.jinput:jinput-platform:2.0.5
Ignored net.java.jinput:jinput-platform:2.0.5
Downloading Minecraft %s1.5.2
Cleaning cache files
Prepaping to download resources
Downloading 1.5.2 configuration...
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl.lwjgl:lwjgl:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.1-nightly-20130708-debug3
Ignored net.java.jinput:jinput-platform:2.0.5
Ignored net.java.jinput:jinput-platform:2.0.5
Downloading Minecraft %s1.5.2
Cleaning cache files
Prepaping to download resources

**Comment by khanhduytran0** [comment]
Why v3?

**Comment by khanhduytran0** [comment]
Anything more details?

**Comment by khanhduytran0** [comment]
@Tryhardbro please reply

**Comment by khanhduytran0** [comment]
Re-open if reply.
