### ISSUE TITLE
[BUG] Crash after few seconds of gameplay

### ISSUE THREAD

**Issue by lapius** [PojavLauncherTeam/PojavLauncher#1603]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
The game crashes few seconds after gameplay and app restarts

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6733165/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Login in or start an offline account;
3. Launch Minecraft of any versions.
4. Make world and start it

### Expected behavior:
I expected normal gameplay

### Screenshots or videos:
I dont know what I should screenshot

**Platform:**
 - Device Model: ROG Phone 5
 - CPU architecture: Aarch64
 - Android Version: 11
 - PojavLauncher Version: latest from google play || 3.3.1.1_rel_20210321

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
I tried reinstalling java runtime and allocated memory to 4096 MB.

I found similar bug, he used the same phone. But somehow I can go farther than him: https://github.com/PojavLauncherTeam/PojavLauncher/issues/1358
</pre>
</details>

**Comment by Nanify69** [comment]
@lapius turn vbos on it should probably work

**Comment by Irsplayer1** [comment]
I have the same problem but with the Samsung A01

**Comment by w123456w30w** [comment]
same problem my device is OnePlus7Pro

**Comment by Kapideveloper** [comment]
Same is happening on Xiaomi Pocophone F1

**Comment by ghost** [comment]
The same is happening on Xiaomi Pocophone F1 (Android 11, dotOS ROM). It crashes when i use any of the GL4ES renderer options.
But if i swap to zink(Vulkan) it doesn't crash, but it runs at 5FPS

**Comment by GoneSubject** [comment]
> The same is happening on Xiaomi Pocophone F1. It crashes when i use any of the GL4ES renderer options.
> But if i swap to zink(Vulkan) it doesn't crash, but it runs at 5FPS

pls send the latestlog.txt

**Comment by ghost** [comment]
Here's the Log
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7796666/latestlog.txt)

**Comment by GoneSubject** [comment]
> Here's the Log
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7796666/latestlog.txt)
> 
> 

change your render to gl4es 1.1.4 and try again

**Comment by ghost** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7796716/latestlog.txt)
Stills crashing

**Comment by cherepavel** [comment]
I have the same problem! On all renders, except for zink (Vulkan), it crashes almost immediately after loading the world
Log on gl4es 1.1.4 render:
[latestlog (2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7833850/latestlog.2.txt)
![123](https://user-images.githubusercontent.com/24592649/148657120-ed5c406f-c01a-40d9-bafc-3baa18fdc689.gif)
.

**Comment by GoneSubject** [comment]
> I have the same problem! On all renders, except for zink (Vulkan), it crashes almost immediately after loading the world
> Log on gl4es 1.1.4 render:
> [latestlog (2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7833850/latestlog.2.txt)
> ![123](https://user-images.githubusercontent.com/24592649/148657120-ed5c406f-c01a-40d9-bafc-3baa18fdc689.gif)
> .

you must enable VBO

**Comment by GoneSubject** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7796716/latestlog.txt)
> Stills crashing

you enable VBO too

**Comment by khanhduytran0** [comment]
> > I have the same problem! On all renders, except for zink (Vulkan), it crashes almost immediately after loading the world
> > Log on gl4es 1.1.4 render:
> > [latestlog (2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7833850/latestlog.2.txt)
> > ![123](https://user-images.githubusercontent.com/24592649/148657120-ed5c406f-c01a-40d9-bafc-3baa18fdc689.gif)
> > .
> 
> you must enable VBO

VBO isn't available in 1.7.10

**Comment by GoneSubject** [comment]
> > > I have the same problem! On all renders, except for zink (Vulkan), it crashes almost immediately after loading the world
> > > Log on gl4es 1.1.4 render:
> > > [latestlog (2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7833850/latestlog.2.txt)
> > > ![123](https://user-images.githubusercontent.com/24592649/148657120-ed5c406f-c01a-40d9-bafc-3baa18fdc689.gif)
> > > .
> > 
> > you must enable VBO
> 
> VBO isn't available in 1.7.10

maybe enable it in option.txt?

**Comment by Jouni4** [comment]
I have the same problem. anybody have solution?

**Comment by Comy112** [comment]
Enable VBO, and put everything to fast (disable clouds and others). Allocate about 1 GB ram and use right renderer (Zink and vgpu are for shaders).

**Comment by Jouni4** [comment]
> Enable VBO, and put everything to fast (disable clouds and others). Allocate about 1 GB ram and use right renderer (Zink and vgpu are for shaders).
im trying to play 1.12.2 optifine and it still crashes

**Comment by Comy112** [comment]
> > Enable VBO, and put everything to fast (disable clouds and others). Allocate about 1 GB ram and use right renderer (Zink and vgpu are for shaders).
> > im trying to play 1.12.2 optifine and it still crashes

Your device is absolute garbage then. 
Try other renderers or lower down ram usage.

**Comment by Jouni4** [comment]
> > > Enable VBO, and put everything to fast (disable clouds and others). Allocate about 1 GB ram and use right renderer (Zink and vgpu are for shaders).
> > > im trying to play 1.12.2 optifine and it still crashes
> 
> Your device is absolute garbage then. 
> Try other renderers or lower down ram usage. 

i found what was the problem. the problem was setting called render regions that i had on

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
