### ISSUE TITLE
Respone errorcode: 403message

### ISSUE THREAD

**Issue by VanshModi1998** [PojavLauncherTeam/PojavLauncher#1605]
I am facing this problem many time while loging in my premium account I have chacked my I'd and password several times it is correct but it shows this problem again and again.

![Screenshot_2021-06-29-22-40-49-349_net kdt pojavlaunch](https://user-images.githubusercontent.com/80061341/123840118-97e32900-d92b-11eb-9962-eb009cf61e03.jpg)

Pojav Launcher info :-- 
Download from = play store

Phone Info :--

![Screenshot_2021-06-29-22-47-15-046_com android settings](https://user-images.githubusercontent.com/80061341/123840545-117b1700-d92c-11eb-899c-d080dcd51b1b.jpg)

![IMG_20210629_224728](https://user-images.githubusercontent.com/80061341/123840561-16d86180-d92c-11eb-9117-ca215f7530a2.jpg)

Pls fix it...

**Comment by NekoIceCream** [comment]
Invalid username or password

check again whether the username or password is correct?

**Comment by NekoIceCream** [comment]
You can check it at https://minecraft.net

**Comment by khanhduytran0** [comment]
@VanshModi1998 
> Template has been ripped :eyes:

Have you typed username instead of email?

**Comment by khanhduytran0** [comment]
@VanshModi1998 or did you get it from NFA/SFA?

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer from author
Closing
