### ISSUE TITLE
[BUG] can't install forge1.16.5

### ISSUE THREAD

**Issue by IndefiniteCalculus** [PojavLauncherTeam/PojavLauncher#1608]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Can't install forge1.16.5.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6747671/latestlog.txt)

### To Reproduce:
I'm not sure if it can be reproduced or not, because seems like it's something about my installation file
1. Download PojavLauncher in APKpure, because I'm using Huawei, and google store stop supporting my device
2. download forge
3. install forge in Pojavlauncher and stuck in the command window
4. Navigate to the URL in the error message, and find the .java.policy file is not here
5. try to run the original Mc 1.16.5 and it runs smoothly

### Expected behavior:
I expected to install forge in Pojavlaucher. 

#### forge version
![image](https://user-images.githubusercontent.com/55014395/124113483-14961480-da9e-11eb-8c8b-34d53285ef04.png)
![image](https://user-images.githubusercontent.com/55014395/124113542-24155d80-da9e-11eb-9d26-eb18ffab4faf.png)
#### error message
![image](https://user-images.githubusercontent.com/55014395/124113717-545cfc00-da9e-11eb-9e20-4dcb518a68b4.png)
#### navigate to where the url in the error message point to
![image](https://user-images.githubusercontent.com/55014395/124113792-6b035300-da9e-11eb-8c2a-12f572ef7ce4.png)

**Platform:**
 - Device Model Huawei M6 
 - CPU architecture ARM A76
 - Android Version 10
 - PojavLauncher Version version 3.3.1.1_rel_20210321

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Did you see that the **installer** is behind the log? 
![](https://user-images.githubusercontent.com/55014395/124113717-545cfc00-da9e-11eb-9e20-4dcb518a68b4.png)

**Comment by khanhduytran0** [comment]
See #1953
