### ISSUE TITLE
I can't sign in with the Microsoft account

### ISSUE THREAD

**Issue by Mudryyy** [PojavLauncherTeam/PojavLauncher#1611]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mudryyy** [comment]
I can't sign in with the Microsoft account

**Comment by Mudryyy** [comment]
Eu não consigo entrar com a conta Microsoft

**Comment by Mudryyy** [comment]
Eu não consigo entrar com a conta Microsoft

**Comment by khanhduytran0** [comment]
@Mudryyy
- you can’t fill the template and pick one properly.
- you expect to get <ins>**free premium account**</ins> with Microsoft login?

**Comment by khanhduytran0** [comment]
Go and buy Minecraft first.
