### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BYWled** [PojavLauncherTeam/PojavLauncher#1614]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
After I set up the PojavLauncher according to the tutorial in Wiki, I still can't open the high version of the game. There's no problem below 21w08b

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6757773/latest.log)

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model Mi 6 6/64
 - CPU architecture aarch64
 - Android Version 9
 - PojavLauncher Version v3.3.1.1-912-7a7ffb83-

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
read th page 1.17 isnt suported yet
