### ISSUE TITLE
[BUG] forge 1.12.2 Turns on but turns off immediately after 2 seconds

### ISSUE THREAD

**Issue by SlurpyReal** [PojavLauncherTeam/PojavLauncher#1616]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details

**Comment by NotAHero04** [comment]
No logs again... Why does so many people do not fill the template?

**Comment by SlurpyReal** [comment]
--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms384m -Xmx768m"
Headless version detected! (20201219)
WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x361
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x450
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x33c0
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x13b8
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x2196
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x6a68
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x4d9
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0xda0
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x5e6
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x77
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x1c7
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x8ff
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x16fe
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x2e6
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0xe6
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x119
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x364
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x139
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0xf13
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x3f1
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x158
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x6af
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x1c1
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x6c1
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x23a
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x103
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so
" unused DT entry: 
DT_RPATH
 (type 
0xf
 arg 
0x1d2
) (ignoring)

WARNING: linker: 
Warning: "
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so
" has unsupported flags DT_FLAGS_1=
0x81
 (ignoring unsupported flags)

OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
--------- beginning of system
--------- beginning of main
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsunec.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so in namespace classloader-namespace
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so in namespace classloader-namespace
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsig.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_xawt.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so success
I/jrelog  ( 5510): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so success
I/jrelog  ( 5510): dlopen /data/app/~~2eyeoRwD4XmslQRzuWuYvg==/net.kdt.pojavlaunch-ZurrkAGP3rDit7Ak7Ghixg==/lib/arm64/libopenal.so success
I/LIBGL   ( 5510): Initialising gl4es
I/LIBGL   ( 5510): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   ( 5510): Using GLES 2.0 backend
I/LIBGL   ( 5510): loaded: libGLESv2.so
I/LIBGL   ( 5510): loaded: libEGL.so
I/LIBGL   ( 5510): Using GLES 2.0 backend
I/LIBGL   ( 5510): Hardware Full NPOT detected and used
I/LIBGL   ( 5510): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   ( 5510): FBO are in core, and so used
I/LIBGL   ( 5510): PointSprite are in core, and so used
I/LIBGL   ( 5510): CubeMap are in core, and so used
I/LIBGL   ( 5510): BlendColor is in core, and so used
I/LIBGL   ( 5510): Blend Substract is in core, and so used
I/LIBGL   ( 5510): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 5510): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 5510): Extension GL_OES_mapbuffer  detected
I/LIBGL   ( 5510): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 5510): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 5510): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 5510): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 5510): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 5510): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 5510): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   ( 5510): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   ( 5510): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 5510): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 5510): high precision float in fragment shader available and used
I/LIBGL   ( 5510): Max vertex attrib: 16
I/LIBGL   ( 5510): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 5510): Max texture size: 8192
I/LIBGL   ( 5510): Max Varying Vector: 31
I/LIBGL   ( 5510): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   ( 5510): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 5510): Max Anisotropic filtering: 16
I/LIBGL   ( 5510): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   ( 5510): Hardware vendor is ARM
I/LIBGL   ( 5510): GLSL 300 es supported
I/LIBGL   ( 5510): GLSL 310 es supported and used
I/LIBGL   ( 5510): sRGB surface supported
I/LIBGL   ( 5510): EGLImage to Texture2D supported
I/LIBGL   ( 5510): EGLImage to RenderBuffer supported
I/LIBGL   ( 5510): ignore MipMap
I/LIBGL   ( 5510): Targeting OpenGL 2.1
I/LIBGL   ( 5510): NPOT texture handled in hardware
I/LIBGL   ( 5510): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 5510): try to use VBO
I/LIBGL   ( 5510): glXMakeCurrent FBO workaround enabled
I/LIBGL   ( 5510): FBO workaround for using binded texture enabled
I/LIBGL   ( 5510): glX Will try to recycle EGL Surface
I/LIBGL   ( 5510): Current folder is:/
I/jrelog  ( 5510): dlopen /data/app/~~2eyeoRwD4XmslQRzuWuYvg==/net.kdt.pojavlaunch-ZurrkAGP3rDit7Ak7Ghixg==/lib/arm64/libgl4es_114.so success
I/jrelog  ( 5510): Done processing args
I/jrelog  ( 5510): Found JLI lib
I/jrelog  ( 5510): Calling JLI_Launch
Error: Could not find or load main class DSR

**Comment by SlurpyReal** [comment]
> No logs again... Why does so many people do not fill the template?

Wdym by "logs" and do u know how to fix it 😔 🥺

**Comment by WesleyVanNeck** [comment]
Error: Could not find or load main class DSR

**Comment by SlurpyReal** [comment]
cap
