### ISSUE TITLE
[BUG] Pojavlauncher crash for an unknown reason

### ISSUE THREAD

**Issue by XOCX404** [PojavLauncherTeam/PojavLauncher#1617]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
The launcher used to work fine before now it never does.

**Add a log file if you want to see your bug fixed !**
https://pastebin.pl/view/5d6db9d4

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Pick any renderer
3. Crash
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ... The game to start?

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
https://youtu.be/SJwkFMJOXpw

**Platform:**
 - Device Model: Infinix note 7
 - CPU architecture: i think its 32 not sure
 - Android Version: 10
 - PojavLauncher Version [Latest Release action]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Can you try [this build](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/996849232) :eyes:

**Comment by XOCX404** [comment]
Its what im using atm

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer from author
Closing
