### ISSUE TITLE
[BUG] <Minecraft 1.17 doesn't work even with OpenGL 3.2>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1621]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
My phone have OpenGL 3.2 on, and Minecraft still doesn't work. Tested on Fabric, logs are clear and Minecraft doesn't even work lol.

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected that it would launch

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model: Zenfone Max Pro M1 4/64
 - CPU architecture: aarch64
 - Android Version: 10 (Q)
 - PojavLauncher Version: Latest Release || version 3.3.1.1_rel_20210321

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Add any other context about the problem here. what's the point of it
</pre>
</details>

**Comment by ghost** [comment]
![Screenshot_20210704-134706~2](https://user-images.githubusercontent.com/75259535/124382175-c025ab80-dcce-11eb-9027-61471dbe3ee9.png)
for screenshot

**Comment by WesleyVanNeck** [comment]
Opengl es is not the same as opengl
