### ISSUE TITLE
[BUG] Forge opens but turns off immediately after 2 seconds⁸

### ISSUE THREAD

**Issue by SlurpyReal** [PojavLauncherTeam/PojavLauncher#1622]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
FORGE 1.12.2 Keeps failing.

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior: 

1. Unknown, waiting for someone to figure it out
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected to launch it easily but it keeps failing.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
[Latestlog.txt](content://com.sec.android.app.myfiles.FileProvider/device_storage/0/games/PojavLauncher/latestlog.txt) 

https://user-images.githubusercontent.com/86888806/124382415-fc0d4080-dccf-11eb-9630-34a9ffbbb763.mp4

**Comment by khanhduytran0** [comment]
@SlurpyReal fill the template or this will be closed without help.
> content://com.sec.android.app.myfiles.FileProvider/device_storage/0/games/PojavLauncher/latestlog.txt

bruh it’s in your device

**Comment by SlurpyReal** [comment]
> @SlurpyReal fill the template or this will be closed without help.
> 
> > content://com.sec.android.app.myfiles.FileProvider/device_storage/0/games/PojavLauncher/latestlog.txt
> 
> bruh it’s in your device
I actualy added latestlog.txt but I can't find anywhere where isn't filled templates.

**Comment by khanhduytran0** [comment]
This part is incomplete.
> Platform:
> - Device Model [e.g. Mi 8 Pro 8/128]
> - CPU architecture [e.g. aarch64]
> - Android Version [e.g. 10]
> - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by khanhduytran0** [comment]
I think you should not add latestlog.txt from within default file manager (that called as "Documents" app or "Files" app) but from 3rd party file managers (ES file explore, zarchiver, etc in play store...)

**Comment by khanhduytran0** [comment]
@SlurpyReal hello? ~~without reply in 24hrs this will be closed.~~
