### ISSUE TITLE
[BUG] Cannot login with Microsoft account

### ISSUE THREAD

**Issue by maruwtc** [PojavLauncherTeam/PojavLauncher#1624]
Hello everyone, I tried login with my Microsoft account, but nothing happened like the video. Plzz help🙏 Thank you!

https://user-images.githubusercontent.com/86964487/124471287-46291b80-ddcf-11eb-9f5c-5c8addf63a20.mp4

**Comment by khanhduytran0** [comment]
@mARUwTC please fill the template. You may have outdated version.

**Comment by maruwtc** [comment]
Sorry here is the platform detail

 - Device Model - S20 FE
 - CPU architecture - aarch64
 - Android Version - 11
 - PojavLauncher Version - version 3.3.1.1_rel_20210321

I can't find any log, may be due to even not been logged in. And the launcher is installed though Google Play, so I think it is the latest version.

Thank you!

**Comment by ghost** [comment]
wait is your acc in microsoft is for bedrock or java migrated acc

**Comment by maruwtc** [comment]
My acc is java version 
Thanks!

**Comment by ghost** [comment]
so you migrated it to microsoft? if its not then just type it in the "username or gmail" and then pass

**Comment by maruwtc** [comment]
no, I bought the java version Minecraft key and login to minecraft.net by Microsoft and reedom it. so it is not migration, but only Microsoft acc

**Comment by ghost** [comment]
ohh ok but did you try what i said up there

**Comment by maruwtc** [comment]
yes, but it said invalid username or password

**Comment by maruwtc** [comment]
same as what I did on pc client. only can login by "sign in with Microsoft"

**Comment by ghost** [comment]
> yes, but it said invalid username or password

so u type ur username then try the gmail

**Comment by ghost** [comment]
> same as what I did on pc client. only can login by "sign in with Microsoft"

try the dev app in the action đownload the latest release(but download the no runtime)

**Comment by ghost** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/1620#issuecomment-873560931 go in here then follow the "1.17 is not working?"

**Comment by maruwtc** [comment]
It's straight!
I can login with OnePlus 7 Pro!

**Comment by maruwtc** [comment]
But no work in S20 FE!

**Comment by ghost** [comment]
> But no work in S20 FE!

i think the browser itself

**Comment by maruwtc** [comment]
yes, I mainly use firefox. seem to cause the problem
Thank you!

**Comment by ghost** [comment]
no problem its ok

**Comment by maruwtc** [comment]
Maybe you can add this to readme :) Hope you have a good day!
