### ISSUE TITLE
Does 1.17 support 32bits?

### ISSUE THREAD

**Issue by GroundGustavo** [PojavLauncherTeam/PojavLauncher#1625]
I did the whole process to play 1.17, but it takes me out instantly when it enters, I am 32bits, android 8,4gb RAM, will there be a solution to my problem?

**Comment by ghost** [comment]
Wdym? You mean 32 arch there is 32 arch there

**Comment by ghost** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/1620#issuecomment-873560931 here get the jre 32 but first download the no runtime thingy apk

**Comment by ghost** [comment]
"1.17 is not working?"

**Comment by khanhduytran0** [comment]
> I did the whole process to play 1.17, but it takes me out instantly when it enters, I am 32bits, android 8,4gb RAM, will there be a solution to my problem?

@GroundGustavo 
You just didn't fill the template.
