### ISSUE TITLE
[BUG] why when i install optifine 1.17, it crashes..

### ISSUE THREAD

**Issue by nabiloi** [PojavLauncherTeam/PojavLauncher#1626]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6766820/latestlog.txt)

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
!
This is my device
[Screenshot_20210706-090440](https://user-images.githubusercontent.com/75988498/124531804-72798200-de39-11eb-8d5d-357969015901.png)
![Screenshot_20210706-090450](https://user-images.githubusercontent.com/75988498/124531836-858c5200-de39-11eb-8051-272c7fd661be.png)
![Screenshot_20210706-090503](https://user-images.githubusercontent.com/75988498/124531846-89b86f80-de39-11eb-9f1d-73ca0ced61a0.png)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by ghost** [comment]
Yeah it is , it crashes cause optifine did not rendered something that need to work it

**Comment by khanhduytran0** [comment]
@nabiloi 
- outdated launcher version
- do you see that we had to use a patched shader in order to get 1.17 works? The same thing applies on OptiFine and probably a lot of mods.
