### ISSUE TITLE
1.17 does not work with aarch32

### ISSUE THREAD

**Issue by GroundGustavo** [PojavLauncherTeam/PojavLauncher#1629]
Leer antes de enviar </b></summary>
 <br>
 - asegúrese de que no había problemas duplicados.
 - asegúrese de que ha llenado esta plantilla problema, o esto será rechazado.
 
 ### describa el error
 Una descripción clara y concisa de lo que es el error.

Every time I give it to play, it comes in and in a second, it takes me out, it also happens with the other versions, I think almost all

 ** ¡Añada un archivo de registro si quiere ver corregido su error!**
 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6767302/latestlog.txt)

 El archivo de registro llamado *latestlog. TXT * se encuentra en "*Android/data/net.kdt. Pojavlaunch /files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/. Minecraft *".
 Puede que necesite activar una opción en su explorador de archivos para ver archivos y carpetas ocultos.
 
 ¡No pegue el texto completo del registro! En su lugar, agregarlo como un archivo sobre este problema.
 
 ### para reproducir:
 Indicar pasos para reproducir el comportamiento de los buggy:
 
 1.  Iniciar PojavLauncher
 2.  Select the second option of the renderer
 3.  Select 1.17
 4.  Run 1.17
 
 Comportamiento esperado:
 Esperaba...The normal enter the version
 
 ### capturas de pantalla o vídeos:
 * subir aquí capturas de pantalla o vídeos del comportamiento de los buggy, si es posible.*
![Screenshot_2021-07-05-21-39-31](https://user-images.githubusercontent.com/84538345/124536496-b76fcb00-dddd-11eb-921c-b3a1c0710f67.png)
![Screenshot_2021-07-05-21-40-05(1)](https://user-images.githubusercontent.com/84538345/124536715-0cabdc80-ddde-11eb-910a-0a5db86b60e5.png)
Video:
https://youtu.be/E_9sKIg9YXo

 ** plataforma :**
 - modelo de dispositivo [LG Q7+]
 - arquitectura de la CPU [aarch32]
 - versión Android [8]
 - versión PojavLauncher [v3.3.1.1-811-c0034126-v3_openjdk]
 
 
 < detalles >< resumen ><b> contexto adicional </b></summary>
 <br>
 <pre>
 Agregue cualquier otro contexto sobre el problema aquí.
 </pre>
 </ detalles >

**Comment by khanhduytran0** [comment]
@GroundGustavo why did you translate the whole template..
__You have outdated jre17 runtime build.__
