### ISSUE TITLE
1.17 crash

### ISSUE THREAD

**Issue by GroundGustavo** [PojavLauncherTeam/PojavLauncher#1630]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Every time I give it to play it enters, and the moment comes out of nowhere
**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6767404/latestlog.txt)

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. I select the second option of the renderer
3. I select 1.17
4. I give him to play

### Expected behavior:
I expected ...To enter the version

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_2021-07-05-21-40-05(1)](https://user-images.githubusercontent.com/84538345/124545298-6caa7f00-ddee-11eb-9859-98fe3011b3e4.png)
![Screenshot_2021-07-05-21-39-31](https://user-images.githubusercontent.com/84538345/124545347-81871280-ddee-11eb-9b30-da1ed487203d.png)
Video:
https://youtu.be/E_9sKIg9YXo

**Platform:**
 - Device Model [LG Q7+]
 - CPU architecture [aarch32] 
 - Android Version [8]
 - PojavLauncher Version [v3.3.1.1-811-c0034126-v3_openjdk]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
⚠️ spam issues detected

**Comment by GroundGustavo** [comment]
> ⚠️ problemas de spam detectados
I just want an answer
😭

**Comment by khanhduytran0** [comment]
But I've said that you have **outdated runtime**.

**Comment by rscAvePlex** [comment]
wtf who uses es f~~uck~~ile explorer nowadays

**Comment by GroundGustavo** [comment]
> Pero he dicho que tienes un **tiempo de ejecución desactualizado** .

Where can I get it?

**Comment by Dark-Lord-Pro** [comment]
U select renderer to vulkan and then go to resource pack in options and then select it and wait to load it and then quit and then select renderer to gles1.11.5 let's seee will it solve cuz I did the same process and it works now still lag

**Comment by Mathias-Boulay** [comment]
Spam issue, and #1035 isn't here for nothing.
