### ISSUE TITLE
[BUG] <Cursor does not move in game>

### ISSUE THREAD

**Issue by Megametal1** [PojavLauncherTeam/PojavLauncher#1632]

**Comment by mchnjt** [comment]
:trollface:

**Comment by mchnjt** [comment]
where did da templato go my guy

**Comment by CriticalRange** [comment]
> _No description provided._

Yes. Understood. You don't want to give info (laziness possibly) but no one can tell you "do this", "do that" if you don't fill the template.

**Comment by Dark-Lord-Pro** [comment]
When the game starts don't touch the mouse or just install pojav launcher again without deleting the game files

**Comment by Mathias-Boulay** [comment]
Duplicate from #1235
