### ISSUE TITLE
Please Fix 1.17, I really Want to Use It...........

### ISSUE THREAD

**Issue by Future-spec** [PojavLauncherTeam/PojavLauncher#1635]
Its Showing like game exited with code 1. Please, a humble request to solve it...........

**Comment by ghost** [comment]
wait where did you download it?

**Comment by ghost** [comment]
> Its Showing like game exited with code 1. Please, a humble request to solve it...........

hey where did you download it

**Comment by Future-spec** [comment]
> > Its Showing like game exited with code 1. Please, a humble request to solve it...........
> 
> hey where did you download it

Well , Official And Latest Version Of Play Store

**Comment by Future-spec** [comment]
Hope you will investigate deep about it, Well, It showed Unable to launch 1.17 due to OpenGL 2.3+

**Comment by WesleyVanNeck** [comment]
known issue there is a workaround for but you need the latest dev build and texture pack from artdev

**Comment by WesleyVanNeck** [comment]
you can fid the steps here https://github.com/PojavLauncherTeam/PojavLauncher/issues/1035#issuecomment-873561502
