### ISSUE TITLE
Better controls

### ISSUE THREAD

**Issue by davidii12** [PojavLauncherTeam/PojavLauncher#1636]
**Is your feature request related to a problem? Please describe.**
The controls are painfull.

**Describe the solution you'd like**
Replace the d-pad with a joystick or change the settings of the d-pad so that you can swipe for exampel W to D so that that I don't need to press the button .

**Describe alternatives you've considered**
Idk

**Additional context**
Nope

**Comment by ghost** [comment]
lol

**Comment by Dark-Lord-Pro** [comment]
U can edit it according to you in options

**Comment by davidii12** [comment]
How?

**Comment by Mathias-Boulay** [comment]
> How?

Options > custom controls.
Next time, learn to use the launcher before posting a useless issue, empty of any constructive criticism.

**Comment by davidii12** [comment]
I already know that.
You didn't understand it

**Comment by Dark-Lord-Pro** [comment]
Did your country ban YouTube or u don't know to use Google stupid

**Comment by davidii12** [comment]
What a friendly community

**Comment by CriticalRange** [comment]
> What a friendly community

You're not funny.
You want bedrock controls and it'll (probably) not gonna happen near future.
