### ISSUE TITLE
[BUG] Screen size small or zoomed in on versions older than 1.6.1

### ISSUE THREAD

**Issue by D3MONSLAY3R101** [PojavLauncherTeam/PojavLauncher#1639]
### Describe the bug
 
Any Minecraft version before 1.6.1 has this weird screen size bug.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher

2. Choose any version before 1.6.1 (e.g 1.5.1)

3.The game screen size will be small or zoomed in

### Expected behavior:
I expected the game to be in full screen or not zoomed in

### Screenshots or videos:
![Screenshot_2021-07-08-20-32-54.png](https://user-images.githubusercontent.com/54100283/124892161-be8d1800-e02d-11eb-9500-256b3a2714d5.png)

**Platform:**
 - Device Model: Huawei P8
 - CPU architecture: aarch64
 - Android Version: EMUI 4.0 (Android 6.0)
 - PojavLauncher Version: version 3.3.1.1_rel_20210321

**Comment by khanhduytran0** [comment]
Do you have resolution scaler set to 100%?

**Comment by D3MONSLAY3R101** [comment]
> Do you have resolution scaler set to 100%?

No. I have it set to 25%.

**Comment by ghost** [comment]
you should set it on 100%

**Comment by D3MONSLAY3R101** [comment]
> you should set it on 100%

I did that but this happens 

![Screenshot_2021-07-09-19-29-03.png](https://user-images.githubusercontent.com/54100283/125040687-0ecaaf80-e0ec-11eb-8813-8c5bd3138136.png)

**Comment by wackycreeper** [comment]
> > you should set it on 100%
> 
> I did that but this happens
> 
> ![Screenshot_2021-07-09-19-29-03.png](https://user-images.githubusercontent.com/54100283/125040687-0ecaaf80-e0ec-11eb-8813-8c5bd3138136.png)

Go to send custom keycode and press F11, this will be in fullscreen

**Comment by SprainedSpark89** [comment]
There is a setting to go full screen and some versions just can't do it

**Comment by wackycreeper** [comment]
> There is a setting to go full screen and some versions just can't do it

It works on all versions, ngl.

**Comment by AngeNimus320** [comment]
increase the f11 button :v

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
