### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jennocool** [PojavLauncherTeam/PojavLauncher#164]
Trying to use 1.15.2
Unable to convert library org.lwjgl:lwjgl:3.2.1
processing archive /storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/INDEX.LIST...
writing META-INF/INDEX.LIST; size 554...
processing META-INF/MANIFEST.MF...
processing META-INF/versions/...
writing META-INF/versions/; size 0...
processing META-INF/versions/10/...
writing META-INF/versions/10/; size 0...
processing META-INF/versions/10/org/...
writing META-INF/versions/10/org/; size 0...
processing META-INF/versions/10/org/lwjgl/...
writing META-INF/versions/10/org/lwjgl/; size 0...
processing META-INF/versions/10/org/lwjgl/system/...
writing META-INF/versions/10/org/lwjgl/system/; size 0...
processing META-INF/versions/10/org/lwjgl/system/MathUtil.class...

PARSE ERROR:
unsupported class file version 54.0
...while parsing META-INF/versions/10/org/lwjgl/system/MathUtil.class
1 error; aborting
Exiting with code 1

**Comment by khanhduytran0** [comment]
In v2.5 you can only install up to 1.12.2 and launch up to 1.11.2.

In v3 you can install any versions but `Bad system call` is a big problem.

**Comment by khanhduytran0** [comment]
I tested Minecraft 1.13 in v3: seems like it couldn't find native libraries and crash.

**Comment by khanhduytran0** [comment]
PojavLauncher don't support 1.13 or above at the moment!
