### ISSUE TITLE
[F-REQ]Seria bom se pudéssemos entrar em servidores online sem conta original premium.

### ISSUE THREAD

**Issue by Techboy2021** [PojavLauncherTeam/PojavLauncher#1642]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CriticalRange** [comment]
English only please 🥺

**Comment by JML6305** [comment]
translate

[F-REQ]It would be nice if we could get online servers without premium original account

**Comment by Mathias-Boulay** [comment]
LMAO NO.
