### ISSUE TITLE
Optifine 1.17 Always crash

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1644]
Describe the bug
When I click the start bottom in 1.17 optifine always crash

To Reproduce:
Indicate steps to reproduce the buggy behavior:

Chosen 1.17 optifine
Start the pojavlauncher
Game crash

Expected behavior:
I expected the game to be in full screen or not zoomed in

Platform:

Device Model: xiaomi 9t pro
CPU architecture: aarch64
Android Version: EMUI 4.0 (Android 10)
PojavLauncher Version: version 3.3.1.1_rel_20210321

**Comment by ghost** [comment]
its bot gonna work

**Comment by ghost** [comment]
not*

**Comment by khanhduytran0** [comment]
Optifine and ALL other mods are probably not supported on 1.17. They all use OpenGL 3 shaders ~~which requires you to insert RTX 3090 to get them work~~ :trollface:

**Comment by ghost** [comment]
Duplicate of #1626
