### ISSUE TITLE
[F-REQ] change WASD to analog

### ISSUE THREAD

**Issue by AlucardYT** [PojavLauncherTeam/PojavLauncher#1647]
Note: I'm using a translator

It would be good to use an analog instead of WASD, to give you better mobility when playing a PVP for example, without this function you need to take your finger off one button to go to another.

**Comment by ghost** [comment]
ye cool (im not a dev)

**Comment by prokage7237** [comment]
ye cool (im not a dev)

**Comment by karpiuk599** [comment]
good idea

**Comment by mchnjt** [comment]
> Note: I'm using a translator
> 
> It would be good to use an analog instead of WASD, to give you better mobility when playing a PVP for example, without this function you need to take your finger off one button to go to another.

@AlucardYT You know what? Why don't you fucking suggest that to the Minecraft devs instead

**Comment by ghost** [comment]
devs can see it dum dum

**Comment by WesleyVanNeck** [comment]
Well I think your dum as you don't know how to code and it has to compatible with lwjgl

**Comment by prokage7237** [comment]
you said that "why dont you fyckibg suggest that to the minecraft devs instead" so i answer you

**Comment by WesleyVanNeck** [comment]
> you said that "why dont you fyckibg suggest that to the minecraft devs instead" so i answer you

I did not say that

**Comment by Mathias-Boulay** [comment]
This cannot be done
Minecraft doesn't natively support analog controls
Please don't clog up the issue system, you're wasting devs' time.
Closing.
