### ISSUE TITLE
Optifine Error

### ISSUE THREAD

**Issue by owenraihan** [PojavLauncherTeam/PojavLauncher#165]
when my optifine installing the application restarted and didnt install.

**Comment by khanhduytran0** [comment]
What version?

**Comment by owenraihan** [comment]
1.7.10 n 1.8

**Comment by khanhduytran0** [comment]
And PojavLauncher version?

**Comment by owenraihan** [comment]
2.5.0 preview 1

**Comment by khanhduytran0** [comment]
So what step you got to?
<checkbox> Eg something like Step Patching
<checkbox> ? Or after you select jar the launcher crashed now?

**Comment by owenraihan** [comment]
yes after I select jar it stuck at Preparing and the application restarted.

**Comment by khanhduytran0** [comment]
Ok fixing, go back to previous preview while waiting.

**Comment by khanhduytran0** [comment]
This issue may not get fixed right now due to little broken of v2.5.

One temporary way: go back to v2.4.2 install OptiFine then update to v2.5

**Comment by khanhduytran0** [comment]
Use v3
