### ISSUE TITLE
[BUG] a strange bug on a12

### ISSUE THREAD

**Issue by Nanify69** [PojavLauncherTeam/PojavLauncher#1651]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

(Since the mouse bug has been fixed pls fix this bug)
The bug is giving me insane speed and the texture particles stretch? im bad at explaining 

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6795048/latestlog.txt)

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Play any world
3. a few seconds it is gonna give me insane speed 
4. textures about to stretch
5. Game crashed

### Expected behavior:
I expected to play normally

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

https://youtu.be/GZp0KroetRE

**Platform:**
 - Device Model [e.g. samsung galaxy a12 6/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210321 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Nanify69** [comment]
Fixed the bug on my own lmao it was the mods causing it

**Comment by khanhduytran0** [comment]
Actually, mouse bug is fixed after updating to Android 11. See #1235 for more information.
