### ISSUE TITLE
Hi I Asking About Code 1 Crash 

### ISSUE THREAD

**Issue by THOBY555** [PojavLauncherTeam/PojavLauncher#1654]
![Screenshot_2021-07-11-03-40-48-695_net kdt pojavlaunch](https://user-images.githubusercontent.com/71563419/125179892-fba70500-e1fb-11eb-92c4-b535fe59905b.jpg)
How To Fix It And What Its Mean Im Useing Lasted Version Of Minecraft 1.17.1

**Comment by khanhduytran0** [comment]
~~1. How to fill the template instead of RIP it.
2. How to read issue #1035~~

**Comment by khanhduytran0** [comment]
@THOBY555

**Comment by khanhduytran0** [comment]
Duplicate of #1035

**Comment by khanhduytran0** [comment]
@THOBY555 how do you expect that 1.17.1 can be run on Java 8 and OpenGL 2.

then you will reply:
> I have OpenGL ES 3.2

**Comment by THOBY555** [comment]
> @THOBY555 how do you expect that 1.17.1 can be run on Java 8 and OpenGL 2.
> 
> then you will reply:
> 
> > I have OpenGL ES 3.2

Now Its Crash Without Reason Bruh

**Comment by mchnjt** [comment]
Bruh What
