### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -1 	at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:207) 	at java.lang.StringBuilder.setLength(StringBuilder.java:77) 	at net.kdt.pojavlaunch.Tools.getLWJGL3ClassPath(Tools.java:324) 	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:126) 	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:914) 	at net.kdt.pojavlaunch.BaseMainActivity.access$2600(BaseMainActivity.java:28) 	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709) 	at java.lang.Thread.run(Thread.java:919)  BUG] <Short description>

### ISSUE THREAD

**Issue by Vs54** [PojavLauncherTeam/PojavLauncher#1655]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
1. Fill the template.
2. The title is not a place to paste the error.

**Comment by Vs54** [comment]
This is my problem but I don't know how to write bug

**Comment by khanhduytran0** [comment]
> 
> 
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> 
> <br>
> 
> - Make sure there was not duplicated issues.<br>
> 
> - Make sure you have filled this issue template, or this will get rejected.
> 
> </details>
> 
> 
> 
> ### Describe the bug
> 
> A clear and concise description of what the bug is.
> 
> 
> 
> **Add a log file if you want to see your bug fixed !**
> 
> 
> 
> The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
> 
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> 
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> 
> 
> ### To Reproduce:
> 
> Indicate steps to reproduce the buggy behavior:
> 
> 
> 
> 1. Start PojavLauncher
> 
> ... *(your set of actions to reproduce the bug)*
> 
> 
> 
> ### Expected behavior:
> 
> I expected ...
> 
> 
> 
> ### Screenshots or videos:
> 
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> 
> 
> 
> **Platform:**
> 
>  - Device Model [e.g. Mi 8 Pro 8/128]
> 
>  - CPU architecture [e.g. aarch64] 
> 
>  - Android Version [e.g. 10]
> 
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> 
> 
> 
> <details> <summary><b>Additional context</b></summary>
> 
> <br>
> 
> <pre>
> 
> Add any other context about the problem here.
> 
> </pre>
> 
> </details>
> 
> 

Please take a look at this

**Comment by Vs54** [comment]
I can't understand it
