### ISSUE TITLE
When will the new official version be upda（Non betated）

### ISSUE THREAD

**Issue by doubijunNB** [PojavLauncherTeam/PojavLauncher#1656]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
Why do you want? ~~The only different are just BETA and RELEASE STABLE text.~~

**Comment by khanhduytran0** [comment]
Or do you want us to rename BETA to RELEASE and release as stable then get a lot of bugs from?
