### ISSUE TITLE
[BUG] not work skyfactory 4 

### ISSUE THREAD

**Issue by karpiuk599** [PojavLauncherTeam/PojavLauncher#1661]
### Describe the bug
when i try to run "sky factory 4" openGL throws an error

log: https://pastebin.com/p9f6vbi3

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
download from crystal launcher modpack skyfactory run skyfactory on crystal how to start close and copy the .minecraft file to pojav launcher
### Expected behavior:

shutdown minecraft without crash information

**Platform:**
 - Device Model [Xiaomi Poco f3 8/256]
 - CPU architecture [Kryo 585] 
 - Android Version [android 11]
 - PojavLauncher Version [v3.3.1.1-944-07c2eb44- ]

**Comment by khanhduytran0** [comment]
OpenGL go brrrr..

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
