### ISSUE TITLE
[BUG] Colormatic mod does not work at all

### ISSUE THREAD

**Issue by wackycreeper** [PojavLauncherTeam/PojavLauncher#1663]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I was having a recent issue with the Colormatic mod not loading properly on the fabric loader even if it was made compatible for 1.16.5. This mod can be used for the Classic Skies resource pack on PlanetMinecraft.

**Add a log file if you want to see your bug fixed !**

[https://pastebin.com/ecuRj6ui](https://pastebin.com/ecuRj6ui) 

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Click Fabric Loader 1.16.5 and play
3. Go to the log output
4. Game exited

### Expected behavior:
I expected no errors on step 4

### Screenshots or videos:
None, the log is the evidence

**Platform:**
 - Device Model Xiaomi POCO M3
 - CPU architecture aarch64
 - Android Version 10
 - PojavLauncher Version 3.3.1.1_rel_20210321

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
A lot of injection failures :eyes: ~~maybe you haven't downloaded vanilla?~~

**Comment by wackycreeper** [comment]
@khanhduytran0 Users had reported similar issues on the curseforge page of this mod

**Comment by khanhduytran0** [comment]
So... it's mod issue, right?

**Comment by wackycreeper** [comment]
Maybe, pojav works fine if the mod is just taken out of the mods folders, lol 😂😂

**Comment by khanhduytran0** [comment]
:trollface: moment
