### ISSUE TITLE
[BUG] <In the latest build of pojav launcher available in play store has a feature called right click option who uses external mouse ok now i use external mouse so i enabled the option when i right click entites blocks it doesnt work we need to long click to use or open the block i request pojav team to solve this problem as soon as possible>

### ISSUE THREAD

**Issue by REKTGETREKT** [PojavLauncherTeam/PojavLauncher#1664]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
I request you to buy a new device that runs on Android 8 or newer AND <ins>Fill Da Template</ins>

**Comment by REKTGETREKT** [comment]
Hi sir i have android 10 device samsung  model tablet
