### ISSUE TITLE
[F-REQ] how to boost fps without optifine / jvm argument

### ISSUE THREAD

**Issue by Bertdurant** [PojavLauncherTeam/PojavLauncher#1666]
https://m.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by khanhduytran0** [comment]
1. ripped the template
2. ~~advertising~~
3. not a request
4. misleading information
5. everyone is too familiar with that link
6. ![bruh](https://cdn.discordapp.com/emojis/696116942259617802.png) ![fruhh](https://cdn.discordapp.com/emojis/855473275265220629.png)
