### ISSUE TITLE
[BUG] Blazingpack Client Crash

### ISSUE THREAD

**Issue by JML6305** [PojavLauncherTeam/PojavLauncher#1667]
### Describe the bug
when i run blazingpack client it just "Game Exited"

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6800115/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(Downloading blazingpack client copy to .minecraft --> version)*

### Expected behavior:
I expected No crash information

### Screenshots or videos:

https://user-images.githubusercontent.com/84659033/125265443-6dd03480-e337-11eb-9455-037110ecf641.mp4

**Platform:**
 - Device Model [Acer Chromebook 714]
 - CPU architecture [x86-64] 
 - Android Version [9]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210321 ]

**Comment by khanhduytran0** [comment]
> Downloading blazingpack client copy to .minecraft --> saves

~~how did you install a client into world saves?~~

**Comment by khanhduytran0** [comment]
Bruh, the vanilla version was not installed.

**Comment by JML6305** [comment]
Oh wait my bad .minecraft - -> version

**Comment by JML6305** [comment]
I updated my comment

**Comment by khanhduytran0** [comment]
> Bruh, the vanilla version was not installed.

Did you install?

**Comment by Mathias-Boulay** [comment]
Stale issue, old version, no answer from author
Closing

**Comment by kacorvixon1337** [comment]
blazingpack support only windows cuz blazingpack have anticheat which need hwid, or smth like that
