### ISSUE TITLE
Not Able To Join Any Server....

### ISSUE THREAD

**Issue by Future-spec** [PojavLauncherTeam/PojavLauncher#1668]
I am using Minecraft 1.17.1 and it Runs Perfect On My Device, But When I Go To Multiplayer, When I Try To Join Any Server, It Comes "Connecting To Server" For 2 Minutes and Then Comes Timed Out. Tried 10 Times but Of No Use. Please Help Me As By Telling The Solution........

**Comment by WesleyVanNeck** [comment]
Fill the template and give latest log

**Comment by khanhduytran0** [comment]
~~You are RipIng The TempLate. Join Our DisCord SerVer To Find Out How To Fix That And At Least RepLy Here.~~

**Comment by Future-spec** [comment]
io.netty.channel.ConnectionTimeoutException:connection timed out: (Server Address)/185.116.158.231:25565

**Comment by Future-spec** [comment]
> io.netty.channel.ConnectionTimeoutException:connection timed out: (Server Address)/185.116.158.231:25565

This happens everytime I try To Join......
