### ISSUE TITLE
very bruh

### ISSUE THREAD

**Issue by 121291** [PojavLauncherTeam/PojavLauncher#167]
don't comment on my vids asking 4 credit please, im just 8 yrs old tryna get monei

**Comment by khanhduytran0** [comment]
What is your video dude?

**Comment by 121291** [comment]
the str6fe vid, this isn't anger or salt btw im just politely asking for u not to ask, my notifications r filled sometimes btw im adding some credits to the vid

**Comment by khanhduytran0** [comment]
What money? I'm asking to add my **name** to your description, this called ***credits***, I don't ask for money dude.

**Comment by 121291** [comment]
ok i meant like monetization if i were to have on that vid id disable

**Comment by 121291** [comment]
nvm the issue
