### ISSUE TITLE
[BUG] <Isn't Possible Play on the 1.18 Snapshot Test>

### ISSUE THREAD

**Issue by rad1914** [PojavLauncherTeam/PojavLauncher#1671]
When trying to install, and test the trial version of Minecraft 1.18 after using the preliminary support tutorial, PojavLauncher stops with the attached error
[Crash Report](https://pastebin.com/ETXg8tE1)

**Comment by WesleyVanNeck** [comment]
1.17 doesn't even work properly yet and you wanna run 1.18 😒
