### ISSUE TITLE
[BUG] <The 1.17 Pojavlauncher application cannot be installed after deletion 

### ISSUE THREAD

**Issue by ThatSpecialBenN** [PojavLauncherTeam/PojavLauncher#1672]
So I accidentally installed the wrong jdk17 aarch  in Pojavlauncher and I wanted to replace it, so I had to delete Pojavlauncher and reinstall it, however when I tried installing it, it kept saying "App not installed"

**Comment by Future-spec** [comment]
> So I accidentally installed the wrong jdk17 aarch  in Pojavlauncher and I wanted to replace it, so I had to delete Pojavlauncher and reinstall it, however when I tried installing it, it kept saying "App not installed" 

You might try clearing everything, Data which is left ..... Your device must have detected them.....

**Comment by khanhduytran0** [comment]
> So I accidentally installed the wrong jdk17 aarch in Pojavlauncher and I wanted to replace it, so I had to delete Pojavlauncher and reinstall it

So you didn't know the existence of "Uninstall Java Runtime" option in launcher settings. :fruhh:

**Comment by khanhduytran0** [comment]
*also, ripped the template*

**Comment by khanhduytran0** [comment]
*also, no reply*
