### ISSUE TITLE
1.17 and 1.17.1 Unable to launch[BUG]

### ISSUE THREAD

**Issue by VII002** [PojavLauncherTeam/PojavLauncher#1673]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Minecraft Java 1.17 and 1.17.1 Unable to launch(Temporary method to play was followed step by step)

**Add a log file if you want to see your bug fixed !**

 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6817572/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Put in Default arguments( -Xms768m -Xmx800m)
3. Choose renderer (OpenGL 2)
4. Allocated the right amount of ram to the game.
5. Start Download process( 1.17.jar assets)
6. Launch(Play)
7. Screen fades to black and crashes.

### Expected behavior:
I expected the app to launch the 1.17 version of the game because I've followed every step on how to run Minecraft Java 1.17, Even though I did everything step by step, The game still crashed.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [OPPO A31]
 - CPU architecture [aarch64] 
 - Android Version [ Android 9.0]
 - PojavLauncher Version [Latest Release || version 3.3.1.1-821-7d00a2ae-v3_openjdk]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
read the info there is no work around for 1.17.1 yet
