### ISSUE TITLE
[BUG] <Dont running with Sodium Extra>

### ISSUE THREAD

**Issue by QuasyStellar** [PojavLauncherTeam/PojavLauncher#1674]
<details> <summary><b>Read before submit</b></summary>
<br>
Whe i starting Pojav with Sodium Extra it stack on black screen
</details>

Sodium is working, but with sodium extra it does not. Vertex, fog, are disabled. I trying full reinstall, but it still dont work.

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
ripped the template.
sodium 0.2 is not supported
