### ISSUE TITLE
[BUG] Java 8 incompatible

### ISSUE THREAD

**Issue by Pgabrielmnecraft** [PojavLauncherTeam/PojavLauncher#1676]
### Describe the bug

I was wanting to log into my Minecraft server on 1.16.5 using Java 8 (supposedly supported by the version), but when I logged in, the game closed with code 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6826318/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojavlauncher dev build
2. Select 1.16.5 optifine
3. Select Java 8 using the new multi runtime dev build
4. Start Minecraft
5. application closes with code 1
```

### Expected Behavior

1. start pojavlauncher dev build
2. Select 1.16.5 optifine
3. Select Java 8 using the new multi runtime dev build
4. Start Minecraft
5. Operate normally

### Platform

```markdown
- Device model: Samsung a31 / 128 gb
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 3.3.1.1-823-7d183507-v3_openjdk
```

**Comment by mchnjt** [comment]
uhh

the runtime i gave you ain't broken

**Comment by ghost** [comment]
he or she pick the java 8 not java 17

**Comment by khanhduytran0** [comment]
You have picked jre8 instead of jre17, according to the log :eyes:

**Comment by ghost** [comment]
yep

**Comment by Pgabrielmnecraft** [comment]
> Você escolheu jre8 em vez de jre17, de acordo com o log 👀

I know I chose Java 8, but I was trying to get into 1.16.5, not 1.17
