### ISSUE TITLE
[I can't select the jre17 in the latest build] (and I can't change the file manager)

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#1677]
### Describe the bug

I Can't Select jre17 in The latest build

https://user-images.githubusercontent.com/79517194/125867457-88dad47e-e564-432e-a4ca-265a7b1b27d4.mp4
(This window should appear instead of this window above)
![Screenshot_20210715_195958_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/79517194/125867533-6208b6f5-816c-4be7-a577-1bc4f07ec5e6.jpg)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Select the jre17
3.Enjoy playing
```

### Expected Behavior

I Suppose to Select the jre17

### Platform

```markdown
- Device model: Huawei Nova 3i Rom 128g Ram 4g
- CPU architecture: kirin710
- Android version: 9
- PojavLauncher version: Latest build [Android bundle thing]
```

**Comment by ghost** [comment]
download the jre 17

**Comment by ghost** [comment]
then unzip it

**Comment by ghost** [comment]
and click it when opening

**Comment by ghost** [comment]
the pojav

**Comment by EnderBrine99FOX** [comment]
> and click it when opening

I literally did all that and nothing happened I Can't even click on it

**Comment by karpiuk599** [comment]
me too

**Comment by karpiuk599** [comment]
me too

**Comment by WesleyVanNeck** [comment]
use a difrent file manager

**Comment by EnderBrine99FOX** [comment]
> use a difrent file manager

I Can't that's why I reported its automatically put me in this file manager and I can't change it

**Comment by 666NM** [comment]
I'm the same as you, I can't click on the runtime.

**Comment by EnderBrine99FOX** [comment]
it's fixed now!
