### ISSUE TITLE
[BUG] Pojavlauncher Crash

### ISSUE THREAD

**Issue by nabiloi** [PojavLauncherTeam/PojavLauncher#1678]
### Describe the bug

the application exits suddenly

### The log file and images/videos

https://user-images.githubusercontent.com/75988498/125869877-c077c0e1-7c77-4d7b-8e15-c5d5828b15f1.mp4

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.crash
```

### Expected Behavior

i can install jre-17 runtime

### Platform

```markdown
- Device model: Infinix X650C
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: latest build on the action "https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1031140435"
```

**Comment by mchnjt** [comment]
face reveal imoooooooooooa

**Comment by mchnjt** [comment]
Anyways, looks like you installed a broken build. Get the latest one (not android.yml or bug report.yml, since those are partly related to Pojav)

**Comment by khanhduytran0** [comment]
Is the new crowdin update come from v3_openjdk branch or l10n_v3_openjdk?

**Comment by nabiloi** [comment]
l10n_v3_openjdk

**Comment by khanhduytran0** [comment]
> l10n_v3_openjdk

Bruh that’s only **translation update**, not **feature updates**

**Comment by nabiloi** [comment]
started crashing in action version"https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1031140435"

**Comment by artdeell** [comment]
This instant crashing was already reported by other people and fixed in later builds

**Comment by nabiloi** [comment]
Pls help
