### ISSUE TITLE
render issue

### ISSUE THREAD

**Issue by 121291** [PojavLauncherTeam/PojavLauncher#168]
basically im on 1.8.9 and there's some sort of render issue on play.randomcraft.org, am using an account that's premium too

**Comment by 121291** [comment]
btw android 9 huawei mate 10 pro

**Comment by khanhduytran0** [comment]
This may caused by OpenGL or GL4ES. Because GL4ES is wrapper to OpenGL ES 2 so will have bug. Can you provide a screenshot?

**Comment by 121291** [comment]
if i can then yes

**Comment by khanhduytran0** [comment]
Check mipmap level, try change or set to 0.

**Comment by 121291** [comment]
if possible will send a crash log

**Comment by 121291** [comment]
it's on 2.4.2 preview 11 which is a fine version for me rn anyway so are you gonna fix it or fix newer versions instead? this does happen on other versions too

**Comment by khanhduytran0** [comment]
Put Github paget into desktop mode
![Screenshot_2020-05-05-13-03-32](https://user-images.githubusercontent.com/40482367/81038621-d4a2c400-8ed0-11ea-8d6b-599a5ec9af74.png)

**Comment by khanhduytran0** [comment]
> it's on 2.4.2 preview 11 which is a fine version for me rn anyway so are you gonna fix it or fix newer versions instead? this does happen on other versions too

It is depends on GL4ES.

**Comment by khanhduytran0** [comment]
> if possible will send a crash log

Provide the screenshot about render bug, it's not crash log...

**Comment by 121291** [comment]
im not like a dev or have coding experience so idrk what gl4es is but ill show

**Comment by khanhduytran0** [comment]
[This is gl4es](https://github.com/ptitSeb/gl4es)

**Comment by 121291** [comment]
ok, i joined the server and didn't see a render issue but or anything, i think was patched

**Comment by 121291** [comment]
it happens to tlauncher users too..

**Comment by 121291** [comment]
imma go now

**Comment by khanhduytran0** [comment]
> ok, i joined the server and didn't see a render issue but or anything, i think was patched

Seems like caused by server...
