### ISSUE TITLE
Game exited on latest action

### ISSUE THREAD

**Issue by MansaceBall** [PojavLauncherTeam/PojavLauncher#1682]
### Describe the bug

Latest action release crashes with game exited everytime I try to play. I even install java 8 runtime

### The log file and images/videos
free done
### Steps To Reproduce

```markdown
1. Fix the app so that it doesn't crash
```

### Expected Behavior

I expected for the game to launch normally

### Platform

```markdown
- Device model: Acer Chromebook 315
- CPU architecture: x86_64
- Android version: 10
- PojavLauncher version: Update bug_report.yml
```

**Comment by khanhduytran0** [comment]
@MansaceBall 
1. No log provided
2. Invalid step to reproduce: "Fix the app so that it doesn't crash". ~~you aren't ceo of pojav~~

**Comment by khanhduytran0** [comment]
3. We aren't rich enough to buy one just for test the game exited.

**Comment by khanhduytran0** [comment]
4. Still no reply about the log file.

**Comment by MansaceBall** [comment]
Why are you being smart saying "You aren't the ceo of pojav"?

**Comment by khanhduytran0** [comment]
~~*why are you being smart saying "Fix  the app so it doesn't crash"?*~~ we don't own your device to get the log manually

**Comment by MansaceBall** [comment]
I forgot to add the log i'm sorry

**Comment by khanhduytran0** [comment]
*you still didn't add the log, did you?*

**Comment by Zeyrox1090** [comment]
Bruh moment
