### ISSUE TITLE
[BUG] game closes immediately

### ISSUE THREAD

**Issue by tanfu9** [PojavLauncherTeam/PojavLauncher#1683]
### Describe the bug

When ever I press play pojav will immediately send me back to the screen with the play button 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6834100/latestlog.txt)

### Steps To Reproduce

```markdown
None
```

### Expected Behavior

I expected the game to load and run

### Platform

```markdown
- Device model: Pixel 5
- CPU architecture: arch64
- Android version: 11
- PojavLauncher version: playstore
```

**Comment by khanhduytran0** [comment]
It’s likely that the game has not been fully installed? Did you try other versions?

**Comment by tanfu9** [comment]
Yes none of them worked

**Comment by tanfu9** [comment]
> It’s likely that the game has not been fully installed? Did you try other versions?

Yes, none of them worked

**Comment by khanhduytran0** [comment]
~~Yes, you didn’t enable internet on all of them~~

**Comment by khanhduytran0** [comment]
~~*yes, still no reply*~~

**Comment by Inmumumn** [comment]
Same here I use LG fiesta with like 400 mb of ram left(I've tried to free some more up but it won't work) the game doesn't load then crashes

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer from author
Closing
