### ISSUE TITLE
[BUG] No background panorama

### ISSUE THREAD

**Issue by CTMagz** [PojavLauncherTeam/PojavLauncher#1684]
### Describe the bug

When I entered minecraft there is no panorama behind I have an image of it
![Screenshot_20210717-135627_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/87559343/126027440-039184c5-ecb9-433b-9477-3c5e21b2a5ab.jpg)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6834251/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Play 1.16.5
3. Download
4. Enter play
5. No panorama appearing
```

### Expected Behavior

I expect panorama to appear

### Platform

```markdown
- Device model: Samsung Galaxy A51
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210321
```

**Comment by khanhduytran0** [comment]
Basically, you have skipped downloading assets, that's why.

**Comment by CTMagz** [comment]
But how to fix not appearing panorama? Will download minecraft again ?

**Comment by khanhduytran0** [comment]
> Basically, you have <ins>skipped downloading assets</ins>, that's why.

**Comment by CTMagz** [comment]
How to fix minecraft lag to @khanhduytran0

**Comment by khanhduytran0** [comment]
> How to fix minecraft lag to @khanhduytran0 

It's a PC game.

**Comment by CTMagz** [comment]
I got 1 fps why?

**Comment by khanhduytran0** [comment]
> But how to fix not appearing panorama? Will download minecraft again ?

@CTMagz now let the launcher download the rest part of assets

**Comment by CTMagz** [comment]
OK @khanhduytran0

**Comment by CTMagz** [comment]
But my minecraft still lagging only 1-3 fps on debug @khanhduytran0

**Comment by mchnjt** [comment]
smh get a pc
