### ISSUE TITLE
[BUG] start up bug in. 1.17 to 1.17.1

### ISSUE THREAD

**Issue by Kian0909** [PojavLauncherTeam/PojavLauncher#1685]
### Describe the bug

https://user-images.githubusercontent.com/87556845/126032616-2169c194-ece8-4855-8214-6c45ac91c88c.mp4

Pls help me 🥺😭😭😭

### Steps To Reproduce

```markdown
😭🥺
```

### Expected Behavior

🥺😭

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by rscDoesMoreTrolling** [comment]
This issue will be invalid, as you didn't:
- fill the template
- didn't provide a latestlog.txt

**Comment by prokage7237** [comment]
oh welp if you pick openGL es 2 or 3 it will not work it will crash everytime your gonna play its only works with zink

**Comment by Kian0909** [comment]
It work but the start is is going to kick you

**Comment by LegacyGamerHD** [comment]
Is not a bug there is a workaround you can look here it's tempery solution and can break any time 

you can find the steps here https://github.com/PojavLauncherTeam/PojavLauncher/issues/1035#issuecomment-873561502

**Comment by Kian0909** [comment]
:(

**Comment by LegacyGamerHD** [comment]
We're working on a proper solution still
