### ISSUE TITLE
[BUG] Application/exited with code 1

### ISSUE THREAD

**Issue by AdGamer54** [PojavLauncherTeam/PojavLauncher#1687]
### Describe the bug

When tap to play 
I see controlers but after I see a message that tells application/exited with code 1

### Steps To Reproduce

```markdown
Start Pojav Launcher
Select version 1.17
Download every resources it need or skip
Tap on play
```

### Expected Behavior

I expect the mojang screen comes and I start to play

### Platform

```markdown
- Device model: Redmi 7 3/32
- CPU architecture: Kyro 260
- Android version: 10
- PojavLauncher version:[Latest Release || version 3.3.1.1_rel_2020206
```

**Comment by WesleyVanNeck** [comment]
Dublicated of #1685
