### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by Ivyjunsy** [PojavLauncherTeam/PojavLauncher#1691]
I suggest a skin feature:
What I mean by that is that you can change your skin just by uploading a custom skin to the launcher and play it to your world other than just using steve and alex skin...
( ╹▽╹ )

I think that would be so helpful for some youtuber that plays minecraft using Pojavlauncher.... And so that they can show off their preferred skin other than just showing off the steve/alex skin.... ( ꈍᴗꈍ)

I know that would be a lot of work... But think about it.. You can change your skin in Pojavlauncher.. And that would be a great improvement on the game.. (≧▽≦)

:
If there are any disabilities that do not allow that to happen, then that would still be ok, you can just tell me.. 
 (｡•̀ᴗ-)✧

**Comment by artdeell** [comment]
Skins show in-game perfectly if you bought it on minecraft.net and logged in with that account in Pojav.

**Comment by khanhduytran0** [comment]
I suggest buying Minecraft and go to https://minecraft.net/en-us/profile/skin to change skin.

**Comment by Ivyjunsy** [comment]
Do you really have to rub it on my face??
You can just tell that theres no chance of having that feature...

**Comment by Ivyjunsy** [comment]
> Skins show in-game perfectly if you bought it on minecraft.net and logged in with that account in Pojav.

Do you really have to rub it on my face??
You can just tell that theres no chance of having that feature...

**Comment by khanhduytran0** [comment]
~~*You can just tell that theres no chance of buying Minecraft...*~~

**Comment by Zeyrox1090** [comment]
Close :trollface:

**Comment by wackycreeper** [comment]
@Ivyjunsy you can actually change your skin even offline by downloading this 
[Skin_Changer.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/6839781/Skin_Changer.zip) resource pack and unzip, add a custom skin, rename it to steve.png and move it to games/Pojavlauncher/.minecraft/resourcepacks folder.

**Comment by FeedbackWither** [comment]
> @Ivyjunsy you can actually change your skin even offline by downloading this [Skin_Changer.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/6839781/Skin_Changer.zip) resource pack and unzip, add a custom skin, rename it to steve.png and move it to games/Pojavlauncher/.minecraft/resourcepacks folder.

can u do this with custom name?
