### ISSUE TITLE
About my library and gl4es

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1694]
Hello, I have built a custom GLES translation library, which only calls GLES without EGL, and it can print custom OpenGL information in the output log of POJAV (such as printing OpenGL4.4). However, I found that the maximum size of the printed texture was always -1x-1, whereas for this device it was 16384x16384. I tried to change the function to query the texture size, but it didn't work, and the MC startup screen didn't render. I then went to check the output log of GL4ES and it loaded EGL and printed the Eglimage2D support and then its texture calls were fine and it rendered the MC startup screen. I even saw GLX recycling the EGL surface. I'd like to know some reasons and details.

**Comment by artdeell** [comment]
You can check the GL4ES banner message implementation to check how it reads texture size

**Comment by ghost** [comment]
> 您可以检查 GL4ES 横幅消息实现以检查它如何读取纹理大小

Yes, now I'm looking at its implementation. (It also seems to return some value directly.)
