### ISSUE TITLE
[BUG] Preliminary support for 1.17 doesn't work 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#1699]
### Describe the bug

I can't send videos, I'll do it with screenshots
![Screenshot_20210719_163133_com lenovo anyshare gps](https://user-images.githubusercontent.com/75908293/126167881-27e5ed14-fa81-4435-9529-23426789278e.jpg)
![Screenshot_20210719_163144_com lenovo anyshare gps](https://user-images.githubusercontent.com/75908293/126167887-60cf3d4a-907d-4aba-ba69-5c8ef0343188.jpg)
![Screenshot_20210719_163155_com lenovo anyshare gps](https://user-images.githubusercontent.com/75908293/126167892-5b0c1f04-8a0e-4de0-95e6-4a144d6c5fad.jpg)
![Screenshot_20210719_163234_com duapps recorder](https://user-images.githubusercontent.com/75908293/126167895-186a5177-4023-496a-8664-1cdaaa5456cd.jpg)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6842108/latestlog.txt)

### Steps To Reproduce

```1.Opened pojavlauncher v3.3.1.1-875-93f6c685-v3_openjdk noruntime
2.Downloaded and installed jre 17
3. Opened the file manager and went to the path: pojavlauncher/.minecraft. I edited "options.txt" changed the path to the resource pack there (resourcePacks:["assets-v0.zip"]) 
4. Opened pojavlauncher, chose renderer gl4es 1.1.5 (OpenGl es 2)
5. Launched minecraft 1.17 and this crash occurred 

ㅤ
```

### Expected Behavior
I expected the game to start, but there was an error 

ㅤ

### Platform

```markdown
- Device model:honor 9c 4/64G
- CPU architecture:aarch64 
- Android version:10 
- PojavLauncher version:3.3.1.1-875-93f6c685-v3_openjdk
```

**Comment by khanhduytran0** [comment]
> The log file and images/videos
> Steps To Reproduce
> Expected Behavior

These are empty.

**Comment by Iarkont** [comment]
> > Файл журнала и изображения/видео
> > Шаги Для Воспроизведения
> > Ожидаемое поведение
> 
> Они пусты.

I filled everything out.

**Comment by Iarkont** [comment]
I figured out what the error is: just through txt editing does not install texturepack, you have to run minecraft 1.17 through zink and go to the settings and turn on the textures then go out and run through gl4es and then everything will work.

**Comment by mchnjt** [comment]
FUCK NO

**Comment by mchnjt** [comment]
ok go use zink you retard

**Comment by mchnjt** [comment]
Just don't ask 'why lag'

**Comment by khanhduytran0** [comment]
> Just don't ask 'why lag'

You didn't read carefully? He said he used zink just for setting the resource pack, bruh.
