### ISSUE TITLE
Error downloading version

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#17]
java.lang.RuntimeException: Unable to convert library org.lwjgl:lwjgl:3.2.1
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
processing archive /storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/INDEX.LIST...
writing META-INF/INDEX.LIST; size 554...
processing META-INF/MANIFEST.MF...
processing META-INF/versions/...
writing META-INF/versions/; size 0...
processing META-INF/versions/10/...
writing META-INF/versions/10/; size 0...
processing META-INF/versions/10/org/...
writing META-INF/versions/10/org/; size 0...
processing META-INF/versions/10/org/lwjgl/...
writing META-INF/versions/10/org/lwjgl/; size 0...
processing META-INF/versions/10/org/lwjgl/system/...
writing META-INF/versions/10/org/lwjgl/system/; size 0...
processing META-INF/versions/10/org/lwjgl/system/MathUtil.class...

PARSE ERROR:
unsupported class file version 54.0
...while parsing META-INF/versions/10/org/lwjgl/system/MathUtil.class
1 error; aborting
Exiting with code 1

**Comment by khanhduytran0** [comment]
You are trying to run Minecraft above 1.12 which not supported by PojavLauncher.
