### ISSUE TITLE
question

### ISSUE THREAD

**Issue by owenraihan** [PojavLauncherTeam/PojavLauncher#170]
if I download a forge from MCinaBox and put the forge version here will it worked?

**Comment by artdeell** [comment]
Nope. Java methods required by Forge  is cropped off for some reason. Also: Dalvik is not Java, so maybe this copied folder will just not launch.

**Comment by khanhduytran0** [comment]
It may work in v3, even installer in GUI mode but no font working.

**Comment by CastusMike** [comment]
Pojavlauncher 2.5.0 preview 2 ?

**Comment by khanhduytran0** [comment]
> Pojavlauncher 2.5.0 preview 2 ?

Chắc chưa do đang ở v3...

**Comment by Mikar9** [comment]
> > Pojavlauncher 2.5.0 preview 2 ?
> 
> Chắc chưa do đang ở v3...

2.5.0 preview 2 ? I cant wait it

**Comment by khanhduytran0** [comment]
> > > Pojavlauncher 2.5.0 preview 2 ?
> > 
> > Chắc chưa do đang ở v3...
> 
> 2.5.0 preview 2 ? I cant wait it

Still very busy in v3, sorry.

**Comment by Mikar9** [comment]
Chắc sẽ rất lâu đây , haizzz

Vào 01:51 PM, T.5, 21 Th5, 2020 Tran Khanh Duy <notifications@github.com>
đã viết:

**Comment by Mikar9** [comment]
Hey , Boardwalk 2.0 only download version.json not download version.jar to play. Fix it

**Comment by khanhduytran0** [comment]
> Hey , Boardwalk 2.0 only download version.json not download version.jar to play. Fix it

Boardwalk 2 will not work.
