### ISSUE TITLE
[BUG] <I can't log in through microsoft>

### ISSUE THREAD

**Issue by MrSwellestFlame** [PojavLauncherTeam/PojavLauncher#1700]
### Describe the bug

I installed the latest version of pojavlauncher, I'm trying to log in to my microsoft account on which the minecraft java license was purchased, I enter my email and password, but it takes me to the main page and does not log in to the account. please help me (I am Russian so if there are mistakes when writing, please forgive me)

### The log file and images/videos

games/PojavLauncher/.minecraft

### Steps To Reproduce

```markdown
1. Launched pojavlaucher 
2. Clicked log in via microsoft 
3. I entered mail 
4. I entered the password 
5. I clicked log in 
6. Nothing happened
```

### Expected Behavior

I was expecting that I would log in to the account

### Platform

```markdown
- Device model: STK-LX1
- CPU architecture: 
- Hisilicon Kirin 710F
- Android version: 10
- PojavLauncher version: 
- 3.3.1.1_rel_20210206
```

**Comment by artdeell** [comment]
If you are using Firefox, you should click ... -> Open in application and Pojav will start to log in

**Comment by Mathias-Boulay** [comment]
Fixed via using a custom webview instead of intents
