### ISSUE TITLE
[BUG] flag and sheep colors are not displayed. 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#1701]
### Describe the bug

Flag and sheep colors are not displayed (game version: 1.16.5) 

### The log file and images/videos

![Screenshot_20210720_152718_net kdt pojavlaunch](https://user-images.githubusercontent.com/75908293/126328153-41c030d9-46b0-49cf-a420-1f35f0b44365.jpg)
![Screenshot_20210720_153102_net kdt pojavlaunch](https://user-images.githubusercontent.com/75908293/126328967-cbb4eed9-db34-4fa4-9cd8-8527357cfd0a.jpg)

### Steps To Reproduce

```markdown
1. Launched pojavlauncher 
2. Launched minecraft 1.16.5
3. Created a new world
```

### Expected Behavior

I expected to see the colors of the flags and sheep but didn't see their

### Platform

```markdown
- Device model: honor 9c 4/64 
- CPU architecture:aarch64 
- Android version:10 
- PojavLauncher version:3.3.1.1
```

**Comment by artdeell** [comment]
Set your renderer to gl4es 1.1.5

**Comment by Iarkont** [comment]
> Set your renderer to gl4es 1.1.5

Which version of pojavlauncher is needed for this? I'm just playing on the 3.3.1.1_rel_20210125 version, it automatically allocates ram that allows you not to load the phone

**Comment by artdeell** [comment]
Latest one from GitHub Actions
