### ISSUE TITLE
[F-REQ]  function avto RAM in new versions of pojavlauncher 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#1702]
when playing with a version where this function is present, the smartphone does not heat up, but in new versions of pojavlauncher where this function is not available, the smartphone gets very hot because of which the lags begin

here's one option for what this feature might look like in newer versions:
![Polish_20210720_191325871](https://user-images.githubusercontent.com/75908293/126361018-80efcead-64ca-4613-885b-f128af49a480.jpg)
![Polish_20210720_191420130](https://user-images.githubusercontent.com/75908293/126361031-74b96bb7-d0de-47a0-a724-890b941788c2.jpg)

**Comment by NotAHero04** [comment]
Brruuuhhhh, you want less heat from your phone? Put it TO A FRIDGE

**Comment by Iarkont** [comment]
> Brruuuhhhh, you want less heat from your phone? Put it TO A FRIDGE

When the CPU temperature during the game reaches 70 °  becomes not very Ok

**Comment by CriticalRange** [comment]
> > Brruuuhhhh, you want less heat from your phone? Put it TO A FRIDGE
> 
> When the CPU temperature during the game reaches 70 ° becomes not very Ok

Just buy a PC or a better device (maybe add liquid cooling too :D )

**Comment by khanhduytran0** [comment]
> When the CPU temperature during the game reaches 70 ° becomes not very Ok

**It's a PC game, which is designed for PC hardware**. Auto RAM may be problematic, especially when you put the launcher to background and run other applications, out of memory will occur and game crashes, then you submit a new issue.
