### ISSUE TITLE
100 mods crash in 2mins

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1705]
### Describe the bug

Can't keep up! Did the system time change, or is the server overloaded? Running 2850ms behind, skipping 57 tick(s)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6851701/latestlog.txt)

### Steps To Reproduce

```markdown
1. Add mods
2. Start the pojavlauncher
3. Off all setting
4. Start the game
5. Crash after 2mins of play
```

### Expected Behavior

Overloaded running need to fix

### Platform

```markdown
- Device model: mi 9t pro
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest updates on github action
```

### Anything else?

The problem

Can't keep up! Did the system time change, or is the server overloaded? Running 2850ms behind, skipping 57 tick(s)

**Comment by khanhduytran0** [comment]
Why would you have to use email on offline login?

**Comment by khanhduytran0** [comment]
bruh

**Comment by kedrick021** [comment]
Yes?

**Comment by khanhduytran0** [comment]
You can just use username instead when login offline.

**Comment by khanhduytran0** [comment]
And what’s amount of RAM set?

**Comment by kedrick021** [comment]
Why I can't do that?

**Comment by kedrick021** [comment]
6ram 64 rom

**Comment by khanhduytran0** [comment]
> Why I can't do that?

But why do you want put email into <ins>offline account</ins>? It’s just like leaking your email.

**Comment by khanhduytran0** [comment]
Turn off offline mode and login if you have bought Minecraft

**Comment by khanhduytran0** [comment]
> 6ram 64 rom

I mean the amount of RAM being given to the game

**Comment by kedrick021** [comment]
3gb ram

**Comment by kedrick021** [comment]
I try to play in Mcinabox there no crash but the texture the bug I need to use shader to fix the texture bug but so lag

**Comment by kedrick021** [comment]
> > Why I can't do that?
> 
> But why do you want put email into offline account? It’s just like leaking your email.

Oh right I didn't think I only want to apply the problem

**Comment by khanhduytran0** [comment]
1. It's a big modpack. No launcher handles it correctly.
2. Phone is not a PC.

**Comment by kedrick021** [comment]
I just saying this don't be mad but I try in Mcinabox there no crash on that Minecraft

**Comment by khanhduytran0** [comment]
nah

**Comment by khanhduytran0** [comment]
both "Minecraft" are same

**Comment by kedrick021** [comment]
> nah

Yeah I already try it but the texture is the problem in Mcinabox Minecraft I play for 30mins no crash

**Comment by kedrick021** [comment]
Can you plsss try it 😭

**Comment by kedrick021** [comment]
If you don't believe ican make a video if you want

**Comment by artdeell** [comment]
If you use GL4ES 1.1.5, **don't use it**. It's unstable.

**Comment by rscAvePlex** [comment]
get rickrolled

**Comment by kedrick021** [comment]
> If you use GL4ES 1.1.5, **don't use it**. It's unstable.

Yeah I using it because 1.1.4 have texture bug only 1.1.5 working with no texture bug

**Comment by khanhduytran0** [comment]
> > If you use GL4ES 1.1.5, **don't use it**. It's unstable.
> 
> 
> 
> Yeah I using it because 1.1.4 have texture bug only 1.1.5 working with no texture bug

Aren't you playing 1.12.2? It doesn't have white banner/sheep/egg bug, then why use gl4es 1.1.5?

**Comment by kedrick021** [comment]
> > > If you use GL4ES 1.1.5, **don't use it**. It's unstable.
> > 
> > 
> > Yeah I using it because 1.1.4 have texture bug only 1.1.5 working with no texture bug
> 
> Aren't you playing 1.12.2? It doesn't have white banner/sheep/egg bug, then why use gl4es 1.1.5?

There no bug on sheep and egg but banner I don't know I didn't use it and yeah is 1.12.2 the renderer is the second 1.1.5

**Comment by khanhduytran0** [comment]
> If you use GL4ES 1.1.5, **don't use it**. It's unstable.

**Comment by kedrick021** [comment]
> > If you use GL4ES 1.1.5, **don't use it**. It's unstable.

Ok why when I using 1.1.4 have texture glitch do you have a solution? When I attacking all mobs and flower become a box of rainbow full of color

**Comment by kedrick021** [comment]
Can I ask a question I can play any shader on zink using adreno phone?

**Comment by kedrick021** [comment]
> If you use GL4ES 1.1.5, **don't use it**. It's unstable.

I try  your pojavlauncher update and I use 1.1.4 there no texture bug there 

> If you use GL4ES 1.1.5, **don't use it**. It's unstable.

I using your pojavlauncher update in action and I using 1.1.4 there no texture bug anymore but crash always because of this 
Can't keep up! Did the system time change, or is the server overloaded? Running 2850ms behind, skipping 57 tick(s)

**Comment by SprainedSpark89** [comment]
Or it is raining in the world that sounds crazy but I was trying to p!at every version of Minecraft and when it started raining lots of crashing I had to skip alot of versions to just play the world

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
