### ISSUE TITLE
[BUG] Pojavlauncher automatically closes when pressing home screen button

### ISSUE THREAD

**Issue by CTMagz** [PojavLauncherTeam/PojavLauncher#1706]
### Describe the bug

The game immediately closing when pressing home screen button when typing a long seed for world creation, i screenshot a seed from youtube and I want to copy it for my world so I press home screen to go to gallery but when going back to game force close immediately, this not occur in Minecraft bedrock edition

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Create new world
3. Type seed
4. I screenshot the seed for copy
5. When I typing, game automatically closing when I get back
```

### Expected Behavior

I expect the game to 

### Platform

```markdown
- Device model: Samsung galaxy a51
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: play store version
```

**Comment by WesleyVanNeck** [comment]
I don't have this issue

**Comment by WesleyVanNeck** [comment]
Also no latestlog.txt

**Comment by khanhduytran0** [comment]
Minecraft bedrock edition ≠ Minecraft Java Edition.

Minecraft Java Edition is a PC game, so **RAM usage** is **not optimized**. Minecraft bedrock edition is a game that supports mobile platform, so **RAM usage** is **optimized**, so it doesn't close on background.
Make sure to give Android system enough free RAM amount to let it breathe instead of killing background apps.

**Comment by CTMagz** [comment]
Pls add copy paste to pojav because i do not know all of the seed numbers @LegacyGamerHD @khanhduytran0

**Comment by Mathias-Boulay** [comment]
Welp, we can't help much if android instantly decides to kill the app in the background 😆 
We could try to reduce memory usage of the launcher side, but it would account for 5% at best

**Comment by khanhduytran0** [comment]
> when pressing home screen button when typing a long seed for world creation

Writing to a paper first is always another option. Additionally, you can use gboard with the latest build for their built-in clipboard usage.
