### ISSUE TITLE
[BUG] i can't use zink

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1708]
### Describe the bug

PojavLauncher just force close when im change the renderer to zink

### The log file and images/videos

[Uploading latestlog.txt…]()

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Go to settings
3. Press renderer
4. Change to zink
```

### Expected Behavior

I expect the game was exit

### Platform

```markdown
- Device model: Samsung Galaxy A01 2/16G
- CPU architecture: aarch32
- Android version: 11
- PojavLauncher version: Dev Build || v3.3.1.1-877-61dfaf0c-v3_openjdk
```

**Comment by khanhduytran0** [comment]
latestlog.txt is not uploaded

**Comment by ghost** [comment]
I can't upload the lateslog.txt

**Comment by khanhduytran0** [comment]
So
- You didn't reply
- Your device doesn't support Vulkan.

Closing as invalid.
