### ISSUE TITLE
Server resource pack is crash ing

### ISSUE THREAD

**Issue by SpacyBenGnu** [PojavLauncherTeam/PojavLauncher#171]
When i join to a server its logging and crash

**Comment by SpacyBenGnu** [comment]
![Screenshot_2020-05-06-16-09-43-37](https://user-images.githubusercontent.com/64892710/81153133-34729b00-8fb5-11ea-9ede-fa4a30538303.jpg)

**Comment by khanhduytran0** [comment]
Can you turn off resourcepack in server?

**Comment by SpacyBenGnu** [comment]
I cant . Even on omegacraft.cl i cant join.. that servers doesn't need resoucepack i think not the resourcr packnis the problem because i can login intoserver but if i enter to skyblock or other that things always showed

**Comment by khanhduytran0** [comment]
Use v3
