### ISSUE TITLE
It keeps logging me off

### ISSUE THREAD

**Issue by crimemannn** [PojavLauncherTeam/PojavLauncher#1710]
### Describe the bug

The second I click play it says memory set to 300 mb then says game exited then logs me off

### The log file and images/videos

![Screenshot_20210722-113510](https://user-images.githubusercontent.com/87805758/126619738-58b023c0-771d-4aee-8d35-f7bff5b781df.png)

### Steps To Reproduce

```markdown
Start pojav luancher
log into your account
Click play
```

### Expected Behavior

Playing pojav luancher without logging of against my will

### Platform

```markdown
Infinix hot 10
2x 2.0 GHz cortex_A75,6x 1.8 GHz A55
Android 10
the android one on google play
```

### Anything else?

I tried to play on 1.17.1

**Comment by crimemannn** [comment]
I hope this is informative enough

**Comment by NotAHero04** [comment]
1. You don’t need and **mustn’t** create a new issue with the same problem. Instead, reopen your old issue.
2. Go to PojavLauncher website -> Preliminary support for 1.17 to know the way to play 1.17.x.

**Comment by crimemannn** [comment]
Last time it was closed cuz it wasn't informative enough so I tried with a bit more info

**Comment by crimemannn** [comment]
hmmm now there is a new issue
