### ISSUE TITLE
[BUG] forge installer won't work with jre17

### ISSUE THREAD

**Issue by Zeyrox1090** [PojavLauncherTeam/PojavLauncher#1712]
### Describe the bug

The installer closes

### The log file and images/videos

Log:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6862368/latestlog.txt)

### Steps To Reproduce

```markdown
1 start pojav
2 press mod installer
3 select the installer (forge 1.12)
4 closes
```

### Expected Behavior

Expected for it to show something lol

### Platform

```markdown
- Device model: Realme C3
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest action
```

### Anything else?

It works on jre8

**Comment by dachisao** [comment]
Get trolled

**Comment by Zeyrox1090** [comment]
> Get trolled

Unfunni 👎🏻

**Comment by dachisao** [comment]
Dumbass why would you launch a mod installer with java 17

**Comment by dachisao** [comment]
And yes, the devs already knows about this

**Comment by Zeyrox1090** [comment]
> Dumbass why would you launch a mod installer with java 17

Are you blind I closed right why are people so mean to dumb people why not just teach em

**Comment by Zeyrox1090** [comment]
> Dumbass why would you launch a mod installer with java 17

For testing stuff
