### ISSUE TITLE
Can't look around in infdev and old versions crash

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#1713]
### Describe the bug

I have started playing the version inf-20100618 I wanted to find cool structures and win the game but I can't because I CAN'T LOOK AROUND!!! when I try it changes the slots in the hot bar and I am  not touching the hot bar please fix this I can't even cut down a tree
and older than infdev crashes
!

### Steps To Reproduce

```markdown
You just try to look around without a mouse
```
launch a version older than infdec

### Expected Behavior

You be able to look around
and older than infdev to not crash
### Platform

```markdown
- Device model:Idk 
- CPU architecture:idk
- Android version: it thinks it is 9 but it's a kindle
- PojavLauncher version: latest version for Appstore Google play
```

### Anything else?

In version before it has weird behavior trying to look around
this also happens on my samsung

**Comment by SprainedSpark89** [comment]
Yes I do have the Google play store on my On kindle

**Comment by ghost** [comment]
Ehh did you download the app in playstore? download the latest and cool app in the action thingy

**Comment by SprainedSpark89** [comment]
I just searched pojavlaucher

**Comment by netkv** [comment]
can replicate on my phone, but a1.0.4 works fine so maybe play that, its practically same as late infdev versions

**Comment by SprainedSpark89** [comment]
I thought that a1.0.0 was the last infdev

**Comment by SprainedSpark89** [comment]
And they removed the pyramids made of brick by then

**Comment by netkv** [comment]
if you wanted pyramids, then why inf-20100618? only inf-20100227 have it

**Comment by SprainedSpark89** [comment]
I didn't know i just want to take the pyramid and upgrade the version then go to creative and play with it

**Comment by SprainedSpark89** [comment]
I want to play old version of minecraft

**Comment by SprainedSpark89** [comment]
this is being continued here with another issue on bug #2371

**Comment by SprainedSpark89** [comment]
and still issue after years

**Comment by SprainedSpark89** [comment]
@Pan00Pernicek now i have the correct version of infdev but it crashes before i even get to look around and the versions that crash even before infdev you can look around.

**Comment by SprainedSpark89** [comment]
pls help me

**Comment by BitBlitObviMormon** [comment]
> @Pan00Pernicek now i have the correct version of infdev but it crashes before i even get to look around and the versions that crash even before infdev you can look around.

The launcher .json files are outdated on minecraft.fandom.com. I reckon it would also crash if you tried it on the current launcher on PC (I had to modify my .json files before they would work on the current launcher). I can confirm the mouse-look issue, though.
