### ISSUE TITLE
[BUG] Game closes after starting on Chromebook

### ISSUE THREAD

**Issue by xperyi** [PojavLauncherTeam/PojavLauncher#1717]
### Describe the bug

After loading the game, it immediately closes and the launcher restarts afterwards. There were no errors after it happened.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6867414/latestlog.txt)

[My post from reddit,](https://www.reddit.com/r/PojavLauncher/comments/opt8ai/anyone_knows_why_this_keeps_happening_no_errors/?utm_source=share&utm_medium=web2x&context=3)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select any version
3. Select 'play'
```

### Expected Behavior

My game should expect to launch.

### Platform

```markdown
- Device model: Samsung Chromebook 3
- CPU architecture: x86/i*86
- Android version: 9
- PojavLauncher version: Latest version from Google Play
```

**Comment by Mathias-Boulay** [comment]
duplicate from #1411
