### ISSUE TITLE
Installing the latest build...

### ISSUE THREAD

**Issue by Ivyjunsy** [PojavLauncherTeam/PojavLauncher#1718]
### Describe the bug

The problem isn't really in-game, its about the installing process of the latest build...
:
I tried to install the latest apk which is the: [CONTROLERS V2] but when i tried to install the CONTROLERS V2 apk the installation keeps failing and it keeps on saying "There was a problem parsing the package"

Idk if it's because I did something wrong or it's just my phone..

### The log file and images/videos

Example:
![Screenshot_2021-07-23-15-59-22-73](https://user-images.githubusercontent.com/87071336/126753950-ef88844d-9373-40de-9659-d99ad1b4f6ce.jpg)

### Steps To Reproduce

```markdown
1. Download the zip file
2. Open the zip file 
3. (Tried to) Install Pojavlauncher
4. (Installation failed) says: There was a problem parsing the package.
```

### Expected Behavior

I expect to install it in easily

### Platform

```markdown
- Device model: Realme RMX2020/32G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: [CONTROLERS V2 || version 3.3.1.1_rel_20210206]
(Not sure cuz i didn't see the version)
```

### Anything else?

:
And the apk is "480.01GB" ram or something
![IMG_20210723_163913](https://user-images.githubusercontent.com/87071336/126757702-3fc60a28-1453-4178-a8b0-9502087809d2.jpg)
(It's the same as the "Android C1" apk)

[Can someone help me??..]

**Comment by ghost** [comment]
download the green one 
![Screenshot_20210723_174047](https://user-images.githubusercontent.com/79198391/126764673-e47499a8-8d4d-4e89-8e35-e2a4a7af9b19.jpg)

**Comment by nabiloi** [comment]
re-download that build

**Comment by khanhduytran0** [comment]
The zip file is damaged. I think you should try other file downloaders or other connections.
