### ISSUE TITLE
Crash report when right-clicking compass to open server menu

### ISSUE THREAD

**Issue by Mickalebc** [PojavLauncherTeam/PojavLauncher#172]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 5/6/20 3:21 PM
Description: Rendering item

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bnp.a(SourceFile:126)
	at bhk.a(SourceFile:76)
	at bfi.a(SourceFile:52)
	at bjh.a(SourceFile:122)
	at bjh.a(SourceFile:323)
	at bjh.b(SourceFile:359)
	at ayl.a(SourceFile:249)
	at ayl.a(SourceFile:107)
	at bfk.a(SourceFile:1039)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at bnp$1.a(SourceFile:47)
	at bnp$1.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bnp.a(SourceFile:126)
	at bhk.a(SourceFile:76)
	at bfi.a(SourceFile:52)
	at bjh.a(SourceFile:122)

-- Item being rendered --
Details:
	Item Type: aat@d6f1966
	Item Aux: 3
	Item NBT: {HideFlags:63,SkullOwner:{Id:"1ecb9a6f-36ed-45b7-bb50-84a2b5ce147c",Properties:{textures:[0:{Signature:"pJoB74yAbgiHcWSRDRpcr/rLJu89GhHEpB80KJMdDudeXexBvJ0HMil7d8hh6WGB4YrwIvptaUtAV5Lt2G7P4+O5VkKWZsk0vNIAFI/Z8h5g5P7gIip0HG2iSB4WAno6AdJuLBj494r8It44V2mHcwTnTOOfOHsGz/y4E2FhNTRvmgi93esYn/60gOr6vC5pwAuWhg5yGhMBElJZUQBhFr1H/ergAT6zXjZWALzASpBk2cPuyymDI5Bzct0qBgzaH0Ksrohdm+F0/aoe/BDfZMck/QIrRnFT9ojViPEN1JpTuxKh3p6VrJ8UTAAjX6tNcVXSxNsIyJCtnr2yAr4vpkHaBCwTMiEFOfRJ3tVYAQNkTFjCKKPzLkUzOwrHnDoisrcJIGDzZucQtyBSYeq2rnNoLL/qLg7cLYkTkjDAB2kpRK7MnmehO7adzlnmhSa4KsFn2uzlKojGv7LEhwOTCEnThhYkghlNfVy9NYReQO1e7yWVv5gB2Gjd5/cEhjKFS6e5FYTlHgCLbvydvVErQEsPmdtTCEN85s9VIM0vTG66YBx7IRsmlcnr4geUOtz7ZrWwRbCQfgnOo3B/VaewfGmc9YVytf58RWdDkcQbkehfzGitOZLDrr6kJ1q9KdtAXlJGrNwSaQJ3HS21CRtjgd6Lr8XRicCf/98c3azczvo=",Value:"ewogICJ0aW1lc3RhbXAiIDogMTU4ODc0OTExMjA1OSwKICAicHJvZmlsZUlkIiA6ICIxZWNiOWE2ZjM2ZWQ0NWI3YmI1MDg0YTJiNWNlMTQ3YyIsCiAgInByb2ZpbGVOYW1lIiA6ICJHcjRzcyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kNWZkOWJiMmNlM2NiMjgwYmIwYzk5NDFkNzY4NGQwZGU4MzhjMmUxYzY4YzIyNWY2ZDkxMTAwNGNiYzA2MjI5IgogICAgfQogIH0KfQ=="}]},Name:"Gr4ss"},display:{Lore:[0:"",1:"§7§6➢ §e§nDescripción:",2:"§7Créeme, el mejor Survival que",3:"§7jamás hayas visto. No te lo pierdas!",4:"",5:"§7§6➢ §e§nCaracterísticas:",6:"§7§c ◆ §7Parcelas",7:"§7§c ◆ §7Economía",8:"§7§c ◆ §7Kits OP",9:"§7§c §7§o...y mucho más.",10:"",11:"§7§6➢ §e§nInformación:",12:"§7§c ◆ §7Jugadores: §f23",13:"§7§c ◆ §7Versión: §f1.15.2",14:""],Name:"§f§6>> §a§lMegaSurvival §6<<"}}
	Item Foil: false
Stacktrace:
	at b.a(SourceFile:244)
	at bjh.b(SourceFile:362)
	at ayl.a(SourceFile:249)
	at ayl.a(SourceFile:107)
	at bfk.a(SourceFile:1039)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)

-- Screen render details --
Details:
	Screen name: ayr
	Mouse location: Scaled: (465, 249). Absolute: (1397, 332)
	Screen size: Scaled: (720, 360). Absolute: (2160, 1080). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 10 total; [bew['Maverick6567'/1086, l='MpServer', x=21.26, y=100.00, z=4.32], bex['WassaaaaaxD'/97658, l='MpServer', x=14.22, y=101.00, z=9.50], bex['SebasGF'/97725, l='MpServer', x=14.22, y=101.00, z=9.50], bex['SpawnGaming'/97724, l='MpServer', x=11.16, y=100.00, z=3.88], bex['§bAYUDANTE'/97523, l='MpServer', x=48.38, y=12.00, z=5.53], bex['§9CONSTRUCTOR'/97525, l='MpServer', x=51.50, y=4.00, z=7.34], bex['§4YOU§fTUBER'/97527, l='MpServer', x=54.38, y=4.00, z=9.50], bex['agustinxx20'/97739, l='MpServer', x=11.84, y=100.00, z=3.81], bex['ZombiesBite'/97741, l='MpServer', x=14.16, y=101.00, z=9.50], bex['Zamandriel'/97742, l='MpServer', x=14.22, y=101.00, z=9.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -28.00,4.00,56.00 - World: (-28,4,56), Chunk: (at 4,0,8 in -2,3; contains blocks -32,0,48 to -17,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 232327325 game time, 120000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 151 total; [uo['entity.ItemFrame.name'/97281, l='MpServer', x=1.03, y=100.50, z=16.50], uo['entity.ItemFrame.name'/97280, l='MpServer', x=1.03, y=101.50, z=16.50], um['§fGestiona tus amigos'/97283, l='MpServer', x=-13.50, y=102.22, z=18.22], um['§a§l§nPARTY & AMIGOS'/97282, l='MpServer', x=-13.50, y=102.47, z=18.22], um['Armor Stand'/97285, l='MpServer', x=-13.50, y=101.72, z=18.22], um['§fcon: §a/friends'/97284, l='MpServer', x=-13.50, y=101.97, z=18.22], um['§fcon: §a/party'/97287, l='MpServer', x=-13.50, y=101.22, z=18.22], um['§fCrea tus partys'/97286, l='MpServer', x=-13.50, y=101.47, z=18.22], um['§cNOTA: §eEsto sirve'/97289, l='MpServer', x=-13.50, y=100.72, z=18.22], um['Armor Stand'/97288, l='MpServer', x=-13.50, y=100.97, z=18.22], um['§fen toda la Network :D'/97290, l='MpServer', x=-13.50, y=100.47, z=18.22], bex['Zamandriel'/97742, l='MpServer', x=14.22, y=101.00, z=9.50], um['§6§lEstado: §a§l✔'/97301, l='MpServer', x=-36.59, y=93.72, z=13.59], um['§f§l22/§f§l60'/97303, l='MpServer', x=-36.59, y=93.22, z=13.59], um['§71.15.2'/97302, l='MpServer', x=-36.59, y=93.47, z=13.59], bew['Maverick6567'/1086, l='MpServer', x=21.26, y=100.00, z=4.32], um['§71.8 - 1.15.2'/97305, l='MpServer', x=-36.59, y=93.47, z=5.56], bex['WassaaaaaxD'/97658, l='MpServer', x=14.22, y=101.00, z=9.50], um['§6Estado: §a§l✔'/97304, l='MpServer', x=-36.59, y=93.72, z=5.56], um['§6Estado: §a§l✔'/97307, l='MpServer', x=-32.47, y=93.72, z=14.59], um['§f§l21/§f§l100'/97306, l='MpServer', x=-36.59, y=93.22, z=5.56], um['§f§l14/§f§l50'/97309, l='MpServer', x=-32.47, y=93.22, z=14.59], um['§71.8 - 1.15.2'/97308, l='MpServer', x=-32.47, y=93.47, z=14.59], um['§71.8 - 1.15.2'/97311, l='MpServer', x=-32.53, y=93.47, z=4.34], um['§6Estado: §c§l✕'/97310, l='MpServer', x=-32.53, y=93.72, z=4.34], um['§6Consigue dinero en nuestros'/97313, l='MpServer', x=-37.59, y=93.97, z=9.53], um['§f§l0/§f§l0'/97312, l='MpServer', x=-32.53, y=93.22, z=4.34], um['§6por Misterios y adquirir'/97315, l='MpServer', x=-37.59, y=93.47, z=9.53], um['§6minijuegos para cambiarlo'/97314, l='MpServer', x=-37.59, y=93.72, z=9.53], um['§6cosméticos!'/97316, l='MpServer', x=-37.59, y=93.22, z=9.53], bex['SebasGF'/97725, l='MpServer', x=14.22, y=101.00, z=9.50], um['§a§lRECOMPENSAS'/97333, l='MpServer', x=-37.50, y=93.97, z=25.50], bex['SpawnGaming'/97724, l='MpServer', x=11.16, y=100.00, z=3.88], um['§7Clic para abrir tus'/97335, l='MpServer', x=-37.50, y=93.47, z=25.50], um['Armor Stand'/97334, l='MpServer', x=-37.50, y=93.72, z=25.50], um['§7conseguir más en:'/97337, l='MpServer', x=-37.50, y=92.97, z=25.50], um['§7recompensas! Puedes'/97336, l='MpServer', x=-37.50, y=93.22, z=25.50], um['Armor Stand'/97339, l='MpServer', x=-37.50, y=92.47, z=25.50], um['§6shop.worldcrafteros.net'/97338, l='MpServer', x=-37.50, y=92.72, z=25.50], um['Armor Stand'/97341, l='MpServer', x=-37.50, y=92.03, z=25.50], bex['ZombiesBite'/97741, l='MpServer', x=14.16, y=101.00, z=9.50], bex['agustinxx20'/97739, l='MpServer', x=11.84, y=100.00, z=3.81], bex['WassaaaaaxD'/97658, l='MpServer', x=14.22, y=101.00, z=9.50], uo['entity.ItemFrame.name'/97185, l='MpServer', x=1.03, y=104.50, z=15.50], uo['entity.ItemFrame.name'/97187, l='MpServer', x=1.03, y=102.50, z=15.50], uo['entity.ItemFrame.name'/97186, l='MpServer', x=1.03, y=103.50, z=15.50], uo['entity.ItemFrame.name'/97189, l='MpServer', x=1.03, y=100.50, z=15.50], uo['entity.ItemFrame.name'/97188, l='MpServer', x=1.03, y=101.50, z=15.50], uo['entity.ItemFrame.name'/97191, l='MpServer', x=1.03, y=103.50, z=3.50], uo['entity.ItemFrame.name'/97190, l='MpServer', x=1.03, y=104.50, z=3.50], uo['entity.ItemFrame.name'/97193, l='MpServer', x=1.03, y=101.50, z=3.50], uo['entity.ItemFrame.name'/97192, l='MpServer', x=1.03, y=102.50, z=3.50], uo['entity.ItemFrame.name'/97195, l='MpServer', x=1.03, y=104.50, z=2.50], uo['entity.ItemFrame.name'/97194, l='MpServer', x=1.03, y=100.50, z=3.50], uo['entity.ItemFrame.name'/97197, l='MpServer', x=1.03, y=102.50, z=2.50], uo['entity.ItemFrame.name'/97196, l='MpServer', x=1.03, y=103.50, z=2.50], uo['entity.ItemFrame.name'/97199, l='MpServer', x=1.03, y=100.50, z=2.50], uo['entity.ItemFrame.name'/97198, l='MpServer', x=1.03, y=101.50, z=2.50], uo['entity.ItemFrame.name'/97201, l='MpServer', x=1.03, y=103.50, z=1.50], uo['entity.ItemFrame.name'/97200, l='MpServer', x=1.03, y=104.50, z=1.50], uo['entity.ItemFrame.name'/97203, l='MpServer', x=1.03, y=101.50, z=1.50], uo['entity.ItemFrame.name'/97202, l='MpServer', x=1.03, y=102.50, z=1.50], uo['entity.ItemFrame.name'/97205, l='MpServer', x=1.03, y=104.50, z=0.50], uo['entity.ItemFrame.name'/97204, l='MpServer', x=1.03, y=100.50, z=1.50], uo['entity.ItemFrame.name'/97207, l='MpServer', x=1.03, y=102.50, z=0.50], uo['entity.ItemFrame.name'/97206, l='MpServer', x=1.03, y=103.50, z=0.50], uo['entity.ItemFrame.name'/97209, l='MpServer', x=1.03, y=100.50, z=0.50], bex['§bAYUDANTE'/97523, l='MpServer', x=48.38, y=12.00, z=5.53], uo['entity.ItemFrame.name'/97208, l='MpServer', x=1.03, y=101.50, z=0.50], bex['§9CONSTRUCTOR'/97525, l='MpServer', x=51.50, y=4.00, z=7.34], um['§6§lSHOP WORLDCRAFTEROS'/97211, l='MpServer', x=-13.47, y=102.47, z=0.50], bex['§4YOU§fTUBER'/97527, l='MpServer', x=54.38, y=4.00, z=9.50], um['§aPlaying §aFlappyBird'/97210, l='MpServer', x=12.16, y=103.97, z=9.50], bex['SebasGF'/97725, l='MpServer', x=14.22, y=101.00, z=9.50], um['§e¡Consigue los mejores rangos'/97213, l='MpServer', x=-13.47, y=101.97, z=0.50], bex['SpawnGaming'/97724, l='MpServer', x=11.16, y=100.00, z=3.88], um['Armor Stand'/97212, l='MpServer', x=-13.47, y=102.22, z=0.50], um['Armor Stand'/97215, l='MpServer', x=-13.47, y=101.47, z=0.50], um['§edel servidor! :D'/97214, l='MpServer', x=-13.47, y=101.72, z=0.50], uo['entity.ItemFrame.name'/97217, l='MpServer', x=1.03, y=104.50, z=-0.50], um['§ashop.worldcrafteros.net'/97216, l='MpServer', x=-13.47, y=101.22, z=0.50], uo['entity.ItemFrame.name'/97219, l='MpServer', x=1.03, y=102.50, z=-0.50], uo['entity.ItemFrame.name'/97218, l='MpServer', x=1.03, y=103.50, z=-0.50], uo['entity.ItemFrame.name'/97221, l='MpServer', x=1.03, y=100.50, z=-0.50], uo['entity.ItemFrame.name'/97220, l='MpServer', x=1.03, y=101.50, z=-0.50], uo['entity.ItemFrame.name'/97223, l='MpServer', x=1.03, y=103.50, z=-1.50], uo['entity.ItemFrame.name'/97222, l='MpServer', x=1.03, y=104.50, z=-1.50], uo['entity.ItemFrame.name'/97225, l='MpServer', x=1.03, y=101.50, z=-1.50], uo['entity.ItemFrame.name'/97224, l='MpServer', x=1.03, y=102.50, z=-1.50], bex['§aFACTIONS'/97293, l='MpServer', x=-32.59, y=91.00, z=4.47], uo['entity.ItemFrame.name'/97227, l='MpServer', x=1.03, y=104.50, z=-2.50], bex['§aSKYBLOCK'/97297, l='MpServer', x=-32.50, y=91.00, z=14.56], bex['agustinxx20'/97739, l='MpServer', x=11.84, y=100.00, z=3.81], uo['entity.ItemFrame.name'/97226, l='MpServer', x=1.03, y=100.50, z=-1.50], uo['entity.ItemFrame.name'/97229, l='MpServer', x=1.03, y=102.50, z=-2.50], bex['ZombiesBite'/97741, l='MpServer', x=14.16, y=101.00, z=9.50], uo['entity.ItemFrame.name'/97228, l='MpServer', x=1.03, y=103.50, z=-2.50], uo['entity.ItemFrame.name'/97231, l='MpServer', x=1.03, y=100.50, z=-2.50], uo['entity.ItemFrame.name'/97230, l='MpServer', x=1.03, y=101.50, z=-2.50], bex['Zamandriel'/97742, l='MpServer', x=14.22, y=101.00, z=9.50], uo['entity.ItemFrame.name'/97233, l='MpServer', x=1.03, y=103.50, z=-3.50], uo['entity.ItemFrame.name'/97232, l='MpServer', x=1.03, y=104.50, z=-3.50], uo['entity.ItemFrame.name'/97235, l='MpServer', x=1.03, y=101.50, z=-3.50], uo['entity.ItemFrame.name'/97234, l='MpServer', x=1.03, y=102.50, z=-3.50], uo['entity.ItemFrame.name'/97237, l='MpServer', x=1.03, y=104.50, z=-4.50], uo['entity.ItemFrame.name'/97236, l='MpServer', x=1.03, y=100.50, z=-3.50], uo['entity.ItemFrame.name'/97239, l='MpServer', x=1.03, y=102.50, z=-4.50], uo['entity.ItemFrame.name'/97238, l='MpServer', x=1.03, y=103.50, z=-4.50], uo['entity.ItemFrame.name'/97241, l='MpServer', x=1.03, y=100.50, z=-4.50], uo['entity.ItemFrame.name'/97240, l='MpServer', x=1.03, y=101.50, z=-4.50], uo['entity.ItemFrame.name'/97243, l='MpServer', x=1.03, y=103.50, z=23.50], uo['entity.ItemFrame.name'/97242, l='MpServer', x=1.03, y=104.50, z=23.50], uo['entity.ItemFrame.name'/97245, l='MpServer', x=1.03, y=101.50, z=23.50], uo['entity.ItemFrame.name'/97244, l='MpServer', x=1.03, y=102.50, z=23.50], uo['entity.ItemFrame.name'/97247, l='MpServer', x=1.03, y=104.50, z=22.50], uo['entity.ItemFrame.name'/97246, l='MpServer', x=1.03, y=100.50, z=23.50], uo['entity.ItemFrame.name'/97249, l='MpServer', x=1.03, y=102.50, z=22.50], uo['entity.ItemFrame.name'/97248, l='MpServer', x=1.03, y=103.50, z=22.50], uo['entity.ItemFrame.name'/97251, l='MpServer', x=1.03, y=100.50, z=22.50], uo['entity.ItemFrame.name'/97250, l='MpServer', x=1.03, y=101.50, z=22.50], uo['entity.ItemFrame.name'/97253, l='MpServer', x=1.03, y=103.50, z=21.50], uo['entity.ItemFrame.name'/97252, l='MpServer', x=1.03, y=104.50, z=21.50], uo['entity.ItemFrame.name'/97255, l='MpServer', x=1.03, y=101.50, z=21.50], uo['entity.ItemFrame.name'/97254, l='MpServer', x=1.03, y=102.50, z=21.50], uo['entity.ItemFrame.name'/97257, l='MpServer', x=1.03, y=104.50, z=20.50], uo['entity.ItemFrame.name'/97256, l='MpServer', x=1.03, y=100.50, z=21.50], uo['entity.ItemFrame.name'/97259, l='MpServer', x=1.03, y=102.50, z=20.50], uo['entity.ItemFrame.name'/97258, l='MpServer', x=1.03, y=103.50, z=20.50], uo['entity.ItemFrame.name'/97261, l='MpServer', x=1.03, y=100.50, z=20.50], uo['entity.ItemFrame.name'/97260, l='MpServer', x=1.03, y=101.50, z=20.50], uo['entity.ItemFrame.name'/97263, l='MpServer', x=1.03, y=103.50, z=19.50], uo['entity.ItemFrame.name'/97262, l='MpServer', x=1.03, y=104.50, z=19.50], uo['entity.ItemFrame.name'/97265, l='MpServer', x=1.03, y=101.50, z=19.50], uo['entity.ItemFrame.name'/97264, l='MpServer', x=1.03, y=102.50, z=19.50], uo['entity.ItemFrame.name'/97267, l='MpServer', x=1.03, y=104.50, z=18.50], bex['§bAYUDANTE'/97523, l='MpServer', x=48.38, y=12.00, z=5.53], uo['entity.ItemFrame.name'/97266, l='MpServer', x=1.03, y=100.50, z=19.50], uo['entity.ItemFrame.name'/97269, l='MpServer', x=1.03, y=102.50, z=18.50], bex['§9CONSTRUCTOR'/97525, l='MpServer', x=51.50, y=4.00, z=7.34], uo['entity.ItemFrame.name'/97268, l='MpServer', x=1.03, y=103.50, z=18.50], uo['entity.ItemFrame.name'/97271, l='MpServer', x=1.03, y=100.50, z=18.50], bex['§4YOU§fTUBER'/97527, l='MpServer', x=54.38, y=4.00, z=9.50], uo['entity.ItemFrame.name'/97270, l='MpServer', x=1.03, y=101.50, z=18.50], uo['entity.ItemFrame.name'/97273, l='MpServer', x=1.03, y=103.50, z=17.50], uo['entity.ItemFrame.name'/97272, l='MpServer', x=1.03, y=104.50, z=17.50], uo['entity.ItemFrame.name'/97275, l='MpServer', x=1.03, y=101.50, z=17.50], uo['entity.ItemFrame.name'/97274, l='MpServer', x=1.03, y=102.50, z=17.50], uo['entity.ItemFrame.name'/97277, l='MpServer', x=1.03, y=104.50, z=16.50], uo['entity.ItemFrame.name'/97276, l='MpServer', x=1.03, y=100.50, z=17.50], uo['entity.ItemFrame.name'/97279, l='MpServer', x=1.03, y=102.50, z=16.50], uo['entity.ItemFrame.name'/97278, l='MpServer', x=1.03, y=103.50, z=16.50]]
	Retry entities: 0 total; []
	Server brand: FlameCord (0.2.1 SNAPSHOT) <- Spigot
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (armv8l) version 4.9.112-perf+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (LGE LM-Q720, Android 9), The Android Project
	Memory: 0 bytes (0 MB) / 238986680 bytes (227 MB) up to 402653184 bytes (384 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 4 (v8l)

**Comment by artdeell** [comment]
That's a thing: currently Minecraft inside PojavLauncher cant receive Base64-encoded skull data.

**Comment by khanhduytran0** [comment]
Only Android versions which remove `org.apache.commons.codec` will work, eg on Android 9.

**Comment by Mickalebc** [comment]
> Only Android versions which remove `org.apache.commons.codec` will work, eg on Android 9.

I am on Android 9

**Comment by khanhduytran0** [comment]
> > Only Android versions which remove `org.apache.commons.codec` will work, eg on Android 9.
> 
> I am on Android 9

May need setting classpath...

**Comment by khanhduytran0** [comment]
Try 1.11+ or v3.
