### ISSUE TITLE
optimization for low end devices

### ISSUE THREAD

**Issue by LightestMC** [PojavLauncherTeam/PojavLauncher#1722]
it's very annoying that the launcher doesn't work when the memory is allocated to more than 310. it makes it impossible for me to play. it would be cool if there are heavy optimization or an option to force the launcher to use the allocated memory without crashing. i'm not sure if force allocation is the solution/is a thing but i'm just giving this a shot

also my device has 2GB of ram

**Comment by khanhduytran0** [comment]
**It's a PC game**. We can't do anything unless we decompile Minecraft and optimize ourself, but we aren't Mojang, so getting sued is on the way if we do that.

**Comment by khanhduytran0** [comment]
32bit has very limited amount of RAM given to app. also, fill the template.

**Comment by khanhduytran0** [comment]
Also, remember that you can't allocate **more than** device free RAM, unless you have RAM swapper, or your phone will be frozen or restart due to out of memory.
