### ISSUE TITLE
Problem on Realme 5i

### ISSUE THREAD

**Issue by harispoppylatip** [PojavLauncherTeam/PojavLauncher#1723]
### Describe the bug

My android version 10 ram 4gb but why i cant run 1.16.5?

After I press play the application comes out

### The log file and images/videos

Uploading Record_2021-07-23-19-29-00.mp4…

### Steps To Reproduce

```markdown
No crash error detected
```

### Expected Behavior

I tried 1.12.2 and it runs normally

### Platform

```markdown
- Device model: Realme 5i
- CPU architecture: Snapdragon 664
- Android version: 10
- PojavLauncher version: 3.3.1.1_rel_20210321
```

### Anything else?

No

**Comment by khanhduytran0** [comment]
latestlog.txt is missing and the video isn't finished uploading.

**Comment by Zeyrox1090** [comment]
Lol

**Comment by khanhduytran0** [comment]
@harispoppylatip *please reply or this issue will be closed for missing required information*
