### ISSUE TITLE
[Thankz]Its can run Minecraft server 😱🙏

### ISSUE THREAD

**Issue by Geruays** [PojavLauncherTeam/PojavLauncher#1724]
'''look this'''

![Screenshot_20210723-185834](https://user-images.githubusercontent.com/84316160/126778819-e63d4492-aae4-484f-80c1-ed9179a14d84.png)

Thanks pojav now i can host my server with pojavlauncher

Il try with 5.1.2 official server

**Comment by khanhduytran0** [comment]
but it was mainly designed for running the client lmao

**Comment by mchnjt** [comment]
why did he add the enhancement label 😆

**Comment by Geruays** [comment]
> but it was mainly designed for running the client lmao

XD but thank idk its can run server smoothly without lag

**Comment by Geruays** [comment]
Btw you cant intsall instantly the server.jar

**Comment by WesleyVanNeck** [comment]
its not made for hosting a server
