### ISSUE TITLE
Ошибка приложение/игры с кодом один

### ISSUE THREAD

**Issue by idkwhattosay0** [PojavLauncherTeam/PojavLauncher#1725]
### Describe the bug

Почему ,учитывая что версия была скаченна с самого лаунчера  
Названия версий: 1.17.1 ; 1.18experimental (не с лаунчера) и 1.7.10 учитывая что все версии были без модов и прочих паков.

### Steps To Reproduce

```markdown
???
```

### Expected Behavior

Пожалуйста исправьте эту ошибку иди скажите в чем беда.

### Platform

```markdown
- Device model:lenovo mt 10 plus /128g 2020г
- CPU architecture:aarch64
- Android version:10
- PojavLauncher version: последняя версия (3.3.1.1)
```

**Comment by artdeell** [comment]
Если версия есть в лаунчере - это не значит, что она работает. В следующем обновлении будет добавлена поддержка этих версий.

**Comment by Mathias-Boulay** [comment]
The update has landed, so closing
