### ISSUE TITLE
[BUG] 1.17 doesn't work at all

### ISSUE THREAD

**Issue by Zelot14235** [PojavLauncherTeam/PojavLauncher#1728]
### Describe the bug

I gave it a lot of memory and it still says game crashes 
Why and pls fix it

### Steps To Reproduce

```markdown
1. Start the launcher 
2. Choose version 1.17 
3. Hit the button play 
.4 the game crashes
```

### Expected Behavior

I expect that I will be able to play 1.17 without crashing thx

### Platform

```markdown
- Device model: Samsung 10 
- CPU architecture: idk sry
- Android version: 11
- PojavLauncher version: v3
```

**Comment by khanhduytran0** [comment]
*the log file no response at all*

**Comment by khanhduytran0** [comment]
Also, what does "Samsung 10" means?
- note 10?
- a10?
- s10?

**Comment by WesleyVanNeck** [comment]
> Also, what does "Samsung 10" means?
> 
> * note 10?
> * a10?
> * s10?

j10

**Comment by Zelot14235** [comment]
Samsung s10e

**Comment by Mathias-Boulay** [comment]
fixed in the gplay crocus update
