### ISSUE TITLE
Bug(Zink) 

### ISSUE THREAD

**Issue by Danielgamer90** [PojavLauncherTeam/PojavLauncher#1730]
### Describe the bug

Whenever I try to enter the game's home screen, the words disappear and there's a white screen in the background. 

### The log file and images/videos

![Screenshot_20210725-080018](https://user-images.githubusercontent.com/87927415/126892301-b3111f6a-437f-41bd-a49f-414789f559ec.jpg)

### Steps To Reproduce

```markdown
Activate Zink and enter the game a white screen will appear in the background and all words will disappear.
```

### Expected Behavior

I really wish this bug didn't exist

### Platform

```markdown
- Device model: Huawei Y7 Prime 2019/32G
- CPU architecture: aarch64
- Android version: 8.1.0
- PojavLauncher version:
```

### Anything else?

I hope it will be fixed soon.

**Comment by mchnjt** [comment]
your phone doesn't properly support zink :sniffballs:

**Comment by khanhduytran0** [comment]
The GPU comes with your phone is likely to be outdated and doesn’t powerful enough for Zink, also we are not Zink developers, so we can’t do anything about rendering glitches, also missing latestlog.txt :)

**Comment by Danielgamer90** [comment]
> The GPU comes with your phone is likely to be outdated and doesn’t powerful enough for Zink, also we are not Zink developers, so we can’t do anything about rendering glitches, also missing latestlog.txt :)

It's weird because if I try version 1.17 with Zink it works

**Comment by khanhduytran0** [comment]
~~it's not since it uses OpenGL 3.2~~
