### ISSUE TITLE
[F-REQ] please add it to the App Store as fast as possible please 😄

### ISSUE THREAD

**Issue by Dathed1** [PojavLauncherTeam/PojavLauncher#1731]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
dont make this nonsense its not an enhancement or even an issue

**Comment by khanhduytran0** [comment]
- Fill the template.
- Wrong repo.
- PojavLauncher will never come to App Store because it is considered as an “emulator” - dynamic generate code and if it ever come, it will very slow. Also, pushing to App Store requires $99 per year to maintain, do you have money?

**Comment by mchnjt** [comment]
I am blind moment

**Comment by ghost** [comment]
Lmao
