### ISSUE TITLE
Version 1.16.4 Sheep problem[BUG] <Short description>

### ISSUE THREAD

**Issue by pg-anim** [PojavLauncherTeam/PojavLauncher#1732]
### Describe the bug

During the game, in absolutely any worlds, sheep of the same color (white), even the dye does not help

### The log file and images/videos

![Screenshot_2021-07-25-21-18-02-903_net kdt pojavlaunch](https://user-images.githubusercontent.com/87704375/126909210-ee5df665-71e4-407c-ad4c-9479865575fe.jpg)
![Screenshot_2021-07-25-21-17-53-237_net kdt pojavlaunch](https://user-images.githubusercontent.com/87704375/126909220-6d35cde8-563c-4e3e-9ba4-a7ea7a914eea.jpg)

### Steps To Reproduce

```markdown
I just go into the game, create a world and see ONLY WHITE SHEEP
```

### Expected Behavior

Ability to see other colors on sheep besides WHITE

### Platform

```markdown
- Device model: Xiaomi Mi9T 6/64G
- CPU architecture: idk(, but my cpu Qualcomm Snapdragon 730 (SM7150)
- Android version: 10
- PojavLauncher version: 
3.3.1.1_rel_20210125
```

**Comment by ghost** [comment]
no log file

**Comment by khanhduytran0** [comment]
Did you read README.md?
> switch to gl4es 1.1.5
