### ISSUE TITLE
[BUG] <Forge 1.6.4 can't be installed>

### ISSUE THREAD

**Issue by NicoleFox785** [PojavLauncherTeam/PojavLauncher#1733]
### Describe the bug

I'm not sure it's a bug, but when I try to install Forge 1.6.4, it immediately closes at the beginning of the process, and doesn't let me install it, I don't know why, but I would appreciate some kind of response to that, I have tried various versions of Forge 1.6.4

### Steps To Reproduce

```markdown
Try to install forge 1.6.4
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Zeyrox1090** [comment]
Are you using jre17? Use jre8 I think it will work

**Comment by Zeyrox1090** [comment]
Not sure

**Comment by wackycreeper** [comment]
No, I tried running forge 1.6.x and below on Pojav and it didnt open with jre8, so it is not compatible with Pojav Launcher.

**Comment by wackycreeper** [comment]
> Are you using jre17? Use jre8 I think it will work

No, I tried running forge 1.6.x and below on Pojav and it didnt open with jre8, so it is not compatible with Pojav Launcher. My recommendation is Risugami's Modloader, which works with any versions below 1.6.2, but unless if you know how to make a custom .json file you will not be able to run it.

**Comment by artdeell** [comment]
Forge 1.2.5 works though

**Comment by tencentgamer2345** [comment]
No Forge 1.6.4 Not working in jre 8 You Must Use Jre 7 But Jre 7 Is Not Available

**Comment by ChaLcos0ma** [comment]
stupid

**Comment by Mathias-Boulay** [comment]
Forge 1.6.4 can be installed now
