### ISSUE TITLE
[BUG] version 1.7.10 crashes

### ISSUE THREAD

**Issue by Minecraftter123** [PojavLauncherTeam/PojavLauncher#1734]
### Describe the bug

I try to play version 1.7.10 but 10 to 20 seconds after entering the world it closes I have tried with optifine also with forgue and it always closes at 10 to 20 seconds and sorry if it is not understood well I am in google translator I also tried raising and lowering the ram but nothing works 
:(

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6881569/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav launcher
2.select version 1.7.10
3.I create a new world
4.After loading the world, 10 to 20 seconds pass and it closes or sometimes closes immediately after entering the world
```

### Expected Behavior

that the game continue normal

### Platform

```markdown
- Device model: LG k51s
- CPU architecture: 64 bits (32 bits mode)
- Android version: 10
- PojavLauncher version: play store
```

### Anything else?

Help pls :(

**Comment by mchnjt** [comment]
RETAAAAAAAAAAARD

**Comment by mchnjt** [comment]
32bit sux bro

**Comment by Minecraftter123** [comment]
> Sux hermano de 32 bits

Ok thanks

**Comment by CriticalRange** [comment]
> RETAAAAAAAAAAARD

Can't you just be try to chill against these guys ?

**Comment by WesleyVanNeck** [comment]
enable vbo

**Comment by Minecraftter123** [comment]
I couldn't solve it

**Comment by Minecraftter123** [comment]
> habilitar vbo

@LegacyGamerHD still not working
