### ISSUE TITLE
[F-REQ] I am asking for you (aka) App Devs To ask Apple if you (aka) App Devs if You (u know) if you can Add The App to the APPSTORE

### ISSUE THREAD

**Issue by Dathed1** [PojavLauncherTeam/PojavLauncher#1735]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mchnjt** [comment]
the fuck

**Comment by mchnjt** [comment]
when will you realize that this is android repo

**Comment by NotAHero04** [comment]
Assume that PojavLauncher can be in App Store for an amount of time, then it will be very laggy because jailed iOS doesn’t come with JIT. Don’t you want 0fps even with rd-132211? Then SHUT UP please.

**Comment by khanhduytran0** [comment]
Duplicate of #1731

**Comment by khanhduytran0** [comment]
@Dathed1 then can you give us $99 per year?

**Comment by mchnjt** [comment]
> Duplicate of #1731

when same author

**Comment by khanhduytran0** [comment]
> App Devs To ask Apple

~~We aren’t Apple employees so there’s no “special case” to push this to App Store for free.~~
