### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by FiremasterGG** [PojavLauncherTeam/PojavLauncher#1737]
### Describe the bug

the bug is when i open minecraft java ver 1.17.1 the game says the Game Exited even if i downloaded everything without skipping anything
I tried on version 1.7.10 and everything work fine

### The log file and images/videos

![Screenshot_2021-07-27-15-51-09-12_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/88038824/127157808-c28ebf03-83b8-4342-9aee-0baa6d2d90f8.jpg)

### Steps To Reproduce

```markdown
Idk u work on it
```

### Expected Behavior

I expected the game to work fine after downloading everything

### Platform

```markdown
- Device model:Realme C25
- CPU architecture:G70
- Android version:11
- PojavLauncher version:3.3.1.1_rel_20210321
```

**Comment by ghost** [comment]
wheres the log file?

**Comment by FiremasterGG** [comment]
I dunno how to add log file and from where to view it

**Comment by FiremasterGG** [comment]
Oh I understand u mean the crash log file but no there's no log file for a crash

**Comment by CriticalRange** [comment]
> ### Describe the bug
> the bug is when i open minecraft java ver 1.17.1 the game says the Game Exited even if i downloaded everything without skipping anything
> I tried on version 1.7.10 and everything work fine
> 
> ### The log file and images/videos
> ![Screenshot_2021-07-27-15-51-09-12_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/88038824/127157808-c28ebf03-83b8-4342-9aee-0baa6d2d90f8.jpg)
> 
> ### Steps To Reproduce
> ```gfm
> Idk u work on it
> ```
> 
> ### Expected Behavior
> I expected the game to work fine after downloading everything
> 
> ### Platform
> ```gfm
> - Device model:Realme C25
> - CPU architecture:G70
> - Android version:11
> - PojavLauncher version:3.3.1.1_rel_20210321
> ```
> 
> ### Anything else?
> _No response_

1. It's not a bug, it's caused by OpenGL core version being low
2. You probably don't know what "Reproducing" means, it means show us how did you get that error.
3. There is a way to get 1.17 working, just tap to "Preliminary Support for 1.17" in the news page when you start the launcher.

**Comment by FiremasterGG** [comment]
> > ### Describe the bug
> > the bug is when i open minecraft java ver 1.17.1 the game says the Game Exited even if i downloaded everything without skipping anything
> > I tried on version 1.7.10 and everything work fine
> > ### The log file and images/videos
> > ![Screenshot_2021-07-27-15-51-09-12_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/88038824/127157808-c28ebf03-83b8-4342-9aee-0baa6d2d90f8.jpg)
> > ### Steps To Reproduce
> > ```
> > Idk u work on it
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > I expected the game to work fine after downloading everything
> > ### Platform
> > ```
> > - Device model:Realme C25
> > - CPU architecture:G70
> > - Android version:11
> > - PojavLauncher version:3.3.1.1_rel_20210321
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > _No response_
> 
> 1. It's not a bug, it's caused by OpenGL core version being low
> 2. You probably don't know what "Reproducing" means, it means show us how did you get that error.
> 3. There is a way to get 1.17 working, just tap to "Preliminary Support for 1.17" in the news page when you start the launcher.

What to do next I downloaded jre17-aarch64 & assets-v0

**Comment by Mathias-Boulay** [comment]
Works since the crocus update
