### ISSUE TITLE
[BUG] Wrong viewing angle in the latest build

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1739]
### Describe the bug

In this version, trying to use a button with a mouse pass will cause the viewing angle to rise to the top

### Steps To Reproduce

```markdown
1.Download this version https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1072072891
2.Use the control layout with mouse pass to start any version of minecraft
3.Use keys with mouse pass
4.see the bug
```

### Expected Behavior

There shouldn't be any problems

### Platform

```markdown
- Device model: honor play 3
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: v3.3.1.1-1084-a916a528-vgpu
```

**Comment by Mathias-Boulay** [comment]
Hey @CPXMC , thanks for reporting this.
Video footage would be greatly appreciated if we want to accurately reproduce the bug 👀

**Comment by CPXMC** [comment]
> Hey @CPXMC , thanks for reporting this.
> Video footage would be greatly appreciated if we want to accurately reproduce the bug 👀

**Comment by PTALTS-LK** [comment]
> > Hey @CPXMC , thanks for reporting this.
> > Video footage would be greatly appreciated if we want to accurately reproduce the bug 👀

Can you tell me your email address, it is inconvenient for me to upload video files

**Comment by Mathias-Boulay** [comment]
If you have trouble uploading video files, you can upload them somewhere else and put the link here once the upload is done 😄

**Comment by PTALTS-LK** [comment]
> If you have trouble uploading video files, you can upload them somewhere else and put the link here once the upload is done 😄

https://drive.google.com/file/d/1ZYPFxL8nNxBMVEH1je4E95uI9iyZ6ydf/view?usp=drivesdk

**Comment by Mathias-Boulay** [comment]
The bug is reproducible, I'll work on a fix.

**Comment by mchnjt** [comment]
max sensitivity is a real hyperspeed man

**Comment by mchnjt** [comment]
nice for pvp

**Comment by Mathias-Boulay** [comment]
Damn, I didn't have the time to say I fixed the bug 😂 
If only people closed their issues so quickly

**Comment by PTALTS-LK** [comment]
> Damn, I didn't have the time to say I fixed the bug 😂
> If only people closed their issues so quickly

When I saw the hotfix action you sent, I closed it((((😅
