### ISSUE TITLE
help please don't open version 1.14

### ISSUE THREAD

**Issue by JonathanG12** [PojavLauncherTeam/PojavLauncher#174]
At the moment of giving version 1.14 and giving it to play, some files are downloaded to me and when I complete all that, then it takes me out of the application and sends me to another one like that and in that many code and all that appear, but the game does not start me  , is there a problem?

![Screenshot_2020-05-09-02-41-00-484_net kdt pojavlaunch](https://user-images.githubusercontent.com/65064232/81467521-ba056f00-919e-11ea-9f69-19ead72e3b92.jpg)
![Screenshot_2020-05-09-02-40-50-329_net kdt pojavlaunch](https://user-images.githubusercontent.com/65064232/81467523-bb369c00-919e-11ea-9f65-f3fa552ea3e0.jpg)

**Comment by khanhduytran0** [comment]
It will be fixed in next version.

**Comment by khanhduytran0** [comment]
But Minecraft 1.13 or above require LWJGL ARM builds.

**Comment by khanhduytran0** [comment]
Minecraft versions use LWJGL 3.2.1 - 3.2.2 can change to 3.2.3 which have ARM64 prebuilt and will work a bit.

**Comment by JonathanG12** [comment]
Entonces todavía no puedo jugar en la 1.14 en Android?

**Comment by JonathanG12** [comment]
So I still can't play 1.14 on Android?

**Comment by khanhduytran0** [comment]
> So I still can't play 1.14 on Android?

Not only 1.14, almost all version because v3 is not completed.

**Comment by JonathanG12** [comment]
Ok, I hope and they update soon to be able to play in 1.14 on Android servers, it is wonderful everything they have achieved

**Comment by Doxelix** [comment]
Lol

**Comment by khanhduytran0** [comment]
Try v3.0.1 but only very legacy versions worked, 1.7.10 and above show Mojang logo then crash (my test).

**Comment by khanhduytran0** [comment]
Duplicate #156

**Comment by khanhduytran0** [comment]
Duplicate #161
