### ISSUE TITLE
[BUG] <Short description> Minecraft Alpha 1.1.1 doesn't work correctly

### ISSUE THREAD

**Issue by meetioss** [PojavLauncherTeam/PojavLauncher#1740]
### Describe the bug

Alpha 1.1.1 has a gray screen fix that requires it to use its own lwjgl, but it gets overwritten by pojav's lwjgl, which breaks the game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6893222/latestlog.txt)
![Screenshot_2021-07-28-15-36-22-136_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/77941826/127326194-adc590f1-7928-42ee-a7d3-ce0a2f2d80b4.jpg)

### Steps To Reproduce

```markdown
1. Grab the alpha 1.1.1 jar and normal or grayscreen fix .json from archive.org
2. load alpha 1.1.1 in pojav, like any other custom version
3. watch it get stuck at the blue loading screen
```

### Expected Behavior

I expect the game to either load normally or throw me a gray screen (a well known issue with a1.1.1)

### Platform

```markdown
- Device model: Redmi Note 8 pro
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: v3.3.1.1-937-7ab675e0-
```

### Anything else?

Usually Alpha 1.1.1 loads in a gray screen on some graphics cards, reason why it was up for such a short time and why it was so hard to find. A grayscreen patch json was made but it doesn't work because read above

**Comment by mchnjt** [comment]
wen eta alpha 1.1.2

**Comment by Mathias-Boulay** [comment]
Duplicate from #1612 
Additional info transferred to this previously cited issue to keep duplicates.
