### ISSUE TITLE
يقولون بني غير متصل ولكنني متصل[F-REQ]

### ISSUE THREAD

**Issue by TOMS1045** [PojavLauncherTeam/PojavLauncher#1743]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TOMS1045** [comment]
متي سوف ينزل اخر تحديث؟

في الأربعاء، ٢٨ يوليو ٢٠٢١ ٥:٥٣ م LegacyGamerHD ***@***.***>
كتب:

**Comment by EnderBrine99FOX** [comment]
@TOMS1045 يا حبيبي هنا محد يتكلم عربي لكن اقدر اساعدك في مشكلتك إذا عندك شي نتواصل فيه ارسل لي
