### ISSUE TITLE
[BUG] couldnt hear sound in game.

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#1745]
### Describe the bug

Application exited with code 1 in loading 2 second later

And i cant hear sound in game like UI sound,mob sound,walking sound,and others (all) i couldnt download assets file. So i need assets file???  Then sounds come on game? 

Sometime mouse not work

If i optifine game identify crash 

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Log in
3. Renderer
```

### Expected Behavior

I need help

### Platform

```markdown
- Device model:samsung M21 4/64 gb
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: 3.3.1.1
```

### Anything else?

How to fix these

**Comment by NotAHero04** [comment]
Please send latestlog.txt here. We don’t have any information about what Minecraft version you are playing, and the state of the sound files.

**Comment by Ewjjai** [comment]
What is for assets file? 
I deleted app 
Im using 1.17.1
Im using 1.16.5
Not work all of them
Play store version is still good but cant play 1.17

**Comment by NotAHero04** [comment]
> I deleted app
>
???

**Comment by Ewjjai** [comment]
Uninstalled. And i just carefully see lastest log in 2 days ago like



Sound missing at --------------------

**Comment by khanhduytran0** [comment]
Why are you asking for help when uninstalled?

**Comment by khanhduytran0** [comment]
> So i need assets file??? 

Why not? Didn't you read the client jar size? It's under 20mb.

**Comment by khanhduytran0** [comment]
If you think assets are useless, then don't expect to hear sound.

**Comment by Ewjjai** [comment]
It cause i tried i downloaded this game 59 times i try to fix them
Others said assets file download needed
Others said its  beta version of pojavLauncher

**Comment by RadiatedExodus** [comment]
> It cause i tried i downloaded this game 59 times i try to fix them
> Others said assets file download needed
> Others said its beta version of pojavLauncher

Minecraft assets are normally big and they are seperate from the jar itself, you need to have patience and not to skip when it's downloading them

**Comment by Ewjjai** [comment]
Ok i will install again
And i have some problem like mouse not work, game crashed on few version and few version not crash but i want lastest action

**Comment by khanhduytran0** [comment]
> Application exited with code 1 in loading 2 second later

you cannot except to run 1.17 with java8 aswell..

**Comment by Ewjjai** [comment]
But im follow all steps 😑😑

**Comment by Ewjjai** [comment]
When playstore version will be Updated?  I still wait for this

**Comment by khanhduytran0** [comment]
then send latestlog.txt, cuz we don't have an automatic log uploader

**Comment by Ewjjai** [comment]
Ok im downloading this game again
I send lastest log later if i use game as completely

**Comment by Ewjjai** [comment]
Hey theres are resource packs,runtime are removed from action:automaticly added resoures pack and renderer for open gles 2.0    ??????
