### ISSUE TITLE
When can forge and optifine be supported in version 1.17 and above

### ISSUE THREAD

**Issue by doubijunNB** [PojavLauncherTeam/PojavLauncher#1748]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Heima945** [comment]
I don't know if the official will withdraw it, but your question format seems to be wrong

**Comment by khanhduytran0** [comment]
why are you asking for eta all day?

**Comment by khanhduytran0** [comment]
I’m pretty sure after this you will ask 
> when will sodium 0.3 be supported?

and then
> when will SEUS PTGI E12 be supported?

**Comment by khanhduytran0** [comment]
fill the template
