### ISSUE TITLE
Scroll Bar for settings pages malfunctioning

### ISSUE THREAD

**Issue by glitchedmc** [PojavLauncherTeam/PojavLauncher#175]
Sometime the scrollbar doesnt work other time it is inverted so up is down and down is up

**Comment by khanhduytran0** [comment]
This looks like scrolling outside scrollbar. Try triple click on scrollbar then hold and move it.

**Comment by glitchedmc** [comment]
Doesnt work. Still buggy. I use a stylus to scroll so i am positive im hitting the scrollbar every time

**Comment by khanhduytran0** [comment]
Make sure virtual mouse is disabled?

**Comment by khanhduytran0** [comment]
Is scrolling outside work?

**Comment by khanhduytran0** [comment]
You could also toggle `Touchscreen mode` then try again.

**Comment by glitchedmc** [comment]
Scrolling outside the app?
Or not on the scroll bar? cause i cant scroll anywhere

**Comment by glitchedmc** [comment]
Ill try the touchscreen mode and let you know

**Comment by khanhduytran0** [comment]
> Scrolling outside the app?
> Or not on the scroll bar? cause i cant scroll anywhere

Scroll outside the scrollbar.

**Comment by khanhduytran0** [comment]
If still have issue, reopen it.
