### ISSUE TITLE
[BUG] i can't use vgpu

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1750]
### Describe the bug

PojavLauncher just force close after i use vgpu

### The log file and images/videos

![Screenshot_20210729-204036_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/87899358/127503073-706c8344-35ce-4c44-b00a-86f0ccc8af91.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Go to settings
3. Press renderer
4. Change to vgpu
```

### Expected Behavior

I expect the game just closing

### Platform

```markdown
- Device model: Samsung Galaxy A01
- CPU architecture: aarch32
- Android version: 11
- PojavLauncher version: [Dev Build || version v3.3.1.1-1087-608c7d76-
```

**Comment by WesleyVanNeck** [comment]
well it seems only aarch64 works also no support for it its eperimental
