### ISSUE TITLE
[ARM 32-bit] Crash on 1.17 boot with JRE17

### ISSUE THREAD

**Issue by CJFC01** [PojavLauncherTeam/PojavLauncher#1752]
### Describe the bug

Crash when starting version 1.17

### The log file and images/videos

latest log: 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6906085/latestlog.txt)

Video: https://youtu.be/1OsT9gIuuRA

### Steps To Reproduce

```markdown
1.select version 1.17 and start.
```

### Expected Behavior

Crash after "memory set to (number set)" message

### Platform

```markdown
- Device model: Samsung Galaxy J6(SM-J600GT)
- CPU architecture: Arm
- Android version: 10
- PojavLauncher version: 3.3.1.1-1080-e899e636-vgpu
- RAM: 2GB
- OpenGL: 3.2
```

**Comment by khanhduytran0** [comment]
Can you send latestlog.txt?
Also, please talk in English if possible.

**Comment by CJFC01** [comment]
done

> Você pode enviar latestlog.txt?
> Além disso, fale em inglês, se possível.

**Comment by CJFC01** [comment]
> Can you send latestlog.txt?
> Also, please talk in English if possible.

Done,sorry the previous latest.log wasn't right, this one is right.

**Comment by khanhduytran0** [comment]
Looks like java 17 stills somehow broken on 32bit..
