### ISSUE TITLE
[F-REQ] a easier way to install modpacks

### ISSUE THREAD

**Issue by DoubleShotgun** [PojavLauncherTeam/PojavLauncher#1753]
I know there is a way to install modpacks but it's too tedious and sometime doesn't work.

But I'm asking you guys, are you working on our way to make it easier?

What I would imagine the way it would work is basically the same way how you would install forge but you use multimc, so you add the modpack in multimc, the you can play it Ig. I never used multimc before lol.

Of course, that was a suggestion but I'm sure that you guys already figured that out and does probably something wrong but I hope you guys figured out another way.

**Comment by Mathias-Boulay** [comment]
A similar issue exists.
#701
Please don't clog up the issue system, you're wasting devs' time.
Closing.
