### ISSUE TITLE
Lunching game

### ISSUE THREAD

**Issue by Ivyjunsy** [PojavLauncherTeam/PojavLauncher#1756]
### Describe the bug

The problem is when I lunch the ver. 1.16.5 (and other versions) it crashes...
And when i lunch Minecraft it keeps saying "String index out of range"
Screenshot:
![Screenshot_2021-07-30-19-06-10-63_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/87071336/127646704-3de894f0-0d3d-4526-a0b1-aff918330fbb.jpg)
I wouldn't consider it as a crash cause there's no crash log...

Every version of Pojavlauncher do the same thing...
Why??

### The log file and images/videos

Here's the log (I think, I just copied it):
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:207)
	at java.lang.StringBuilder.setLength(StringBuilder.java:77)
	at net.kdt.pojavlaunch.Tools.getLWJGL3ClassPath(Tools.java:324)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:126)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:914)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2600(BaseMainActivity.java:28)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)

### Steps To Reproduce

```markdown
1. Open Pojavlauncher
2. Select version Minecraft
3. Lunch Minecraft
4. Crash...
```

### Expected Behavior

I expected it to run normally...

### Platform

```markdown
- Device model: Realme RMX2020/32G
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version: [Latest Release || Version v3.3.1.1-1078-ff49d5a2-v3_openjdk]
```

### Anything else?

I wish there's a way to fix this...
HELPP....

**Comment by Ivyjunsy** [comment]
Rude... Why didn't you answer me

**Comment by Ivyjunsy** [comment]
I want some answer... Why can't i lunch minecraf???

**Comment by Ivyjunsy** [comment]
Open this issue

**Comment by khanhduytran0** [comment]
Minecraft isn't a food. you need to add latestlog.txt and check the LWJGL3 folder.

**Comment by WesleyVanNeck** [comment]
> Rude... Why didn't you answer me

btw try latest

**Comment by Ivyjunsy** [comment]
That's the latest version when i tried it

**Comment by WesleyVanNeck** [comment]
> That's the latest version when i tried it

not realy

**Comment by Ivyjunsy** [comment]
Every version do that, that's why i don't play Pojavlauncher for now...

**Comment by khanhduytran0** [comment]
that's why you aren't gonna do a clean install

**Comment by Ivyjunsy** [comment]
Then tell me what to do..
How to fix it..

**Comment by khanhduytran0** [comment]
then delete lwjgl3 and caciocavallo folder in PojavLauncher folder...

**Comment by WesleyVanNeck** [comment]
> then delete lwjgl3 and caciocavallo folder in PojavLauncher folder...

Not Worth our time tbh if he doesn't know how to clean install

**Comment by Ivyjunsy** [comment]
And how am i suppose to know how to clean install by my self?? Huh??

**Comment by Ivyjunsy** [comment]
> then delete lwjgl3 and caciocavallo folder in PojavLauncher folder...

Then?? What's next??

**Comment by khanhduytran0** [comment]
Then you just have to restart the launcher and play...

**Comment by WesleyVanNeck** [comment]
> And how am i suppose to know how to clean install by my self?? Huh??

I guess you never touched a phone files before

**Comment by Ivyjunsy** [comment]
> > And how am i suppose to know how to clean install by my self?? Huh??
> 
> I guess you never touched a phone files before

No I've touched the phone files before and still, but i never fiddle with the files...

**Comment by Ivyjunsy** [comment]
> Then you just have to restart the launcher and play...

Ok thank you very much..

**Comment by CriticalRange** [comment]
> > > And how am i suppose to know how to clean install by my self?? Huh??
> > 
> > 
> > I guess you never touched a phone files before
> 
> No I've touched the phone files before and still, but i never fiddle with the files...

That's where the problem is
Imagine if only people with rooted device would able to play with pojav so we wouldn't have issues like this
