### ISSUE TITLE
Code 1

### ISSUE THREAD

**Issue by R0C1S** [PojavLauncherTeam/PojavLauncher#1757]
### Describe the bug

It doesn't let you in 1.17 and always the thing people pops Code 1 and not even previous version work because it doesn't open the menus! Fix it now! 

### The log file and images/videos

-

### Steps To Reproduce

```markdown
Just the thing shows up 4065mb and then next is Code 1
```

### Expected Behavior

To work of course! 

### Platform

```markdown
- Device model: Samsung galaxy A51
- CPU architecture:- 
- Android version: - 
- PojavLauncher version: 1.17
```

### Anything else?

*

**Comment by Pgabrielmnecraft** [comment]
discord #faq-en

**Comment by NotAHero04** [comment]
Hmm, we actually fixed that. Follow the instructions here: https://pojavlauncherteam.github.io/updates/117.html

**Comment by Mathias-Boulay** [comment]
Should be fixed with the crocus update
