### ISSUE TITLE
Android 10 and 2 GB RAM is supported up to which version?

### ISSUE THREAD

**Issue by CJFC01** [PojavLauncherTeam/PojavLauncher#1758]
### Describe the bug

This is not a bug, but I want to know what version of Minecraft Android 10 with 2GB RAM is compatible with.

I want to know not to download incompatible version and not to end up with my internal storage.

### The log file and images/videos

I think it's not necessary

### Steps To Reproduce

```markdown
I think it's not necessary
```

### Expected Behavior

I think it's not necessary

### Platform

```markdown
- Device model: Samsung Galaxy J6(SM-J600GT)
- CPU architecture: Arm
- Android version: 10
- PojavLauncher version: all
- RAM: 2GB
- OpenGL Version: 3.2
```

**Comment by Zeyrox1090** [comment]
1.8 now close this issue
