### ISSUE TITLE
[BUG] Unable to load randompatches mod

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1759]
### Describe the bug

Application exited with code 1
When i try to start the game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6910635/latestlog.txt)
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6910636/latestcrash.txt)

### Steps To Reproduce

```markdown
1.Download randompatches-1.12.2-1.22.1.10.jar
2.Install and start 1.12.2-forge-14.23.5.2855
```

### Expected Behavior

I hope the game should start normally

### Platform

```markdown
- Device model: Honor play 3
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: v3.3.1.1-1078-ff49d5a2-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
