### ISSUE TITLE
[BUG] Unable To Run LiteLoader (World Downloader Mod) 1.8

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#1761]
### Describe the bug

Automatically Closes On Mojang Logo Automatically Close Message:"Game Exited"

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6910840/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start Pojav LiteLoader 1.8[With World Downloader Mod]

2.  Wait To Load On For Mojang Logo

3.Get Message "Game Exited"
```

### Expected Behavior

Expected To Run The Game Normally
Still Thought That Installation Wont Complete

### Platform

```markdown
- Device model: Vivo V5/64G
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: Latest Action
```

### Anything else?

Really Need It Fix ASAP

**Comment by hari-ded** [comment]
Can I know your mobile RAM pls

**Comment by AgaricaGamer** [comment]
> Can I know your mobile RAM pls

I don't think RAM is the problem, cauz i have tested it with giving upto 3gb ram

[crash-2021-07-31_07.52.26-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6914129/crash-2021-07-31_07.52.26-client.txt)


`However, Its 4GB RAM`

**Comment by Minecrafter11231** [comment]
Bruh its already not working for me because
Liteloader always crashes

**Comment by Mathias-Boulay** [comment]
#1948
