### ISSUE TITLE
[BUG] Application/game exited

### ISSUE THREAD

**Issue by Glasslive** [PojavLauncherTeam/PojavLauncher#1762]
### Describe the bug

Application/game exited with code 1 for 1.17.2 even if I don't skip and finish downloading

### The log file and images/videos

![Screenshot_2021-07-31-22-11-47-052_net kdt pojavlaunch](https://user-images.githubusercontent.com/88246454/127746597-fde9c421-e6bc-42d2-a9d4-9eeb7b867880.jpg)

### Steps To Reproduce

```markdown
Pls look into that and solve the problems
```

### Expected Behavior

I expect to launc the game properly

### Platform

```markdown
- Device model: Redmi Y2
- CPU architecture: Octa Core Max 2.00 GHz
- Android version: 9
- PojavLauncher version:Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by CriticalRange** [comment]
https://pojavlauncherteam.github.io/updates/117.html
