### ISSUE TITLE
[BUG] help me :(

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#1764]
### Describe the bug

Why i cant Scroll up/down? 

And sometime mouse point wont work 
Its really annoying 

### The log file and images/videos

![Screenshot_20210801-122635_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/87809448/127762249-7eebfe15-8563-4630-95a3-6fbc559fdbd3.jpg)

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

....

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by WesleyVanNeck** [comment]
Is not a bug use 3 fingers

**Comment by Ewjjai** [comment]
What?  How to?

**Comment by LegacyGamerHD** [comment]
if dont know anyting just dont use it

**Comment by CriticalRange** [comment]
> What? How to?

Hold slider and go down ⬇️
