### ISSUE TITLE
I can not login

### ISSUE THREAD

**Issue by SuchyYT** [PojavLauncherTeam/PojavLauncher#1765]
### Describe the bug

I cannot log into the Microsoft I cannot log into the Microsoft account in the PojavLauncher application

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I thought I would play on my server :(

### Platform

```markdown
- Device model:SM-A600FM
- CPU architecture:???
- Android version:Android 10
- PojavLauncher version:???
```

**Comment by Geruays** [comment]
> ### Describe the bug
> I cannot log into the Microsoft I cannot log into the Microsoft account in the PojavLauncher application
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> .
> ```
> 
> ### Expected Behavior
> I thought I would play on my server :(
> 
> ### Platform
> ```gfm
> - Device model:SM-A600FM
> - CPU architecture:???
> - Android version:Android 10
> - PojavLauncher version:???
> ```
> 
> ### Anything else?
> _No response_

Where The SS XD

**Comment by khanhduytran0** [comment]
Please send what it gives and verify these:
- [ ] You have bought Minecraft, very likely not since you didn’t say that.
- [ ] The account is above 18.
- [ ] If the account is under 18, link it to your parent account.
