### ISSUE TITLE
Problem > redownloading after offline

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#1770]
### Describe the bug

I have some problem with pojav thats are really annoying. Tomworrow i downloaded 1.17.1 and 1.7.10 version but today i going to play as offline then it show me redownload and then i turn on my internet they are again again downloading (assets file too).  So im not play this longer as offline?????  This is why im downloaded 1.7.10 cause of error and such file 

Amd the yes where is my reward from easter egg?      

### The log file and images/videos

Not now

### Steps To Reproduce

```markdown
All is well
```

### Expected Behavior

I need solution or i start to play bedrock?

### Platform

```markdown
- Device model: samsung21
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: 3.3.1.1
```

**Comment by AgaricaGamer** [comment]
The easter egg reward was nothing, 

I m too experiencing this it just says Preparing To Download Resources And Then Launches The Game Normally

Weird Bug

**Comment by mchnjt** [comment]
> The easter egg reward was nothing,
> 
> I m too experiencing this it just says Preparing To Download Resources And Then Launches The Game Normally
> 
> Weird Bug

If you are experiencing problems about the new 'news' page, please don't talk about it. It is not a huge bug, it's just a coder's common code fails.
