### ISSUE TITLE
[BUG] When I start the game with "-Dfile.encoding=GB2312", the game will crash

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#1771]
### Describe the bug

When I start the game with "-Dfile.encoding=GB2312", the game will crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6915031/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start pojav
2.Enter -Dfile.encoding=GB2312 to the JVM startup parameters
3.Start any game version
4.Game crash
```

### Expected Behavior

I expect the game to launches

### Platform

```markdown
- Device model: redmi note7 4/64
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by khanhduytran0** [comment]
Did you look at what you’ve typed? :eyes:
> Info: Custom Java arguments: "-Dfile.encoding=GB2312â€‹"

**Comment by T-CATHOME** [comment]
I entered -Dfile.encoding=GB2312 in mcinabox, and the game can be started without crashing.

When I enter -Dfile.encoding=UTF-8, pojav will not crash and the game can be started
@khanhduytran0

**Comment by mchnjt** [comment]
when

**Comment by mchnjt** [comment]
btw does it give you free 10000 fps?

**Comment by artdeell** [comment]
@tttghkg You've seem to typed the argument in incorrectly. In your log, there are some strange unicode characters at the and of the argument, and I've managed to start minecraft up without any issues with this argument in place.

**Comment by T-CATHOME** [comment]
I only entered -Dfile.encoding=GB2312 and did not enter anything else, and I asked others, and they could not start it.

@artdeell

**Comment by artdeell** [comment]
Try the latest good action build then

**Comment by tttghkg** [comment]
I am using the latest good action build
@artdeell

**Comment by tttghkg** [comment]
Still can't start the game

**Comment by T-CATHOME** [comment]
I have been using the latest good action build. 
@artdeell

**Comment by khanhduytran0** [comment]
Then can you screenshot JVM arguments screen?

**Comment by khanhduytran0** [comment]
Actually, the “latest” you are using come from vgpu branch, not main one.

**Comment by T-CATHOME** [comment]
![Screenshot_2021-08-02-17-27-44-892_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/73945464/127838698-a42c1a40-e7e5-48d4-96a5-8cc0323f4e5d.jpg)
@khanhduytran0

**Comment by T-CATHOME** [comment]
> 实际上，您使用的“最新”来自 vgpu 分支，而不是主要分支。

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6915950/latestlog.txt)

**Comment by tttghkg** [comment]
> > 纽约，您使用的“最新”来自 vgpu 分支，而不是主要分支。
> 
> [最新日志.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6915950/latestlog.txt)

Still crumbling

**Comment by T-CATHOME** [comment]
> 你看你输入的东西了吗？ 
> 
> > 信息：自定义 Java 参数：“-Dfile.encoding=GB2312â€‹”


I didn't see it

![Screenshot_2021-08-02-17-40-34-690_bin mt plus](https://user-images.githubusercontent.com/73945464/127840682-30ee3436-4f04-4618-87ce-142987bb97ea.jpg)
![Screenshot_2021-08-02-17-40-30-707_bin mt plus](https://user-images.githubusercontent.com/73945464/127840692-e126b56c-ce2a-43b7-bc9d-f6a43929ed58.jpg)
![Screenshot_2021-08-02-17-40-19-043_bin mt plus](https://user-images.githubusercontent.com/73945464/127840697-184fda3f-4c19-4c43-9baa-32ae870d5119.jpg)
![Screenshot_2021-08-02-17-40-06-596_bin mt plus](https://user-images.githubusercontent.com/73945464/127840709-df6e6f6b-b766-4a84-8503-7fb54edb5a08.jpg)

**Comment by Mathias-Boulay** [comment]
Stale issue on an branch that doesn't exist anymore
Closing
