### ISSUE TITLE
I cant join a server :( [BUG] <Short description>

### ISSUE THREAD

**Issue by WanFirash** [PojavLauncherTeam/PojavLauncher#1772]
### Describe the bug

Help

### The log file and images/videos

Help

### Steps To Reproduce

```markdown
Help
```

### Expected Behavior

Help

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
Help you filling into the form correctly @WanFirash

**Comment by khanhduytran0** [comment]
![sendLogs](https://media.discordapp.net/attachments/724163890803638277/818210183468810263/unknown.png)

~~btw why don't you replace the title with "help" word as well instead of saying can't join server?~~
