### ISSUE TITLE
[BUG] JUST COME AND LOOK

### ISSUE THREAD

**Issue by Geruays** [PojavLauncherTeam/PojavLauncher#1773]
### Describe the bug

`HEH`

### The log file and images/videos

![Screenshot_20210730-122114](https://user-images.githubusercontent.com/84316160/127951181-d2b518a4-d0bc-447a-bb73-9a7f55f0688b.png)
![Screenshot_20210730-122125](https://user-images.githubusercontent.com/84316160/127951184-bd9f6d5b-485f-4c58-bc92-185fb8a76a6f.png)

### Steps To Reproduce

```markdown
Just Look At Screenshot
```

### Expected Behavior

Can u fix it😓

### Platform

```markdown
- Device model: Xiaomi Mi A1
- CPU architecture: aarch64
- Android version: pie 9.0
- PojavLauncher version: Zinc
```

### Anything else?

Just that and thank you

**Comment by Geruays** [comment]
** **

**Comment by mchnjt** [comment]
vram go brr

**Comment by khanhduytran0** [comment]
*expect to get ~~SEUS PTGI E12~~ shaders works on Zink running in Adreno GPU?**

**Comment by khanhduytran0** [comment]
Unfortunately, we are not Zink developers. We only develop the launcher part of this app.

**Comment by khanhduytran0** [comment]
Also no latestlog.txt provided

**Comment by khanhduytran0** [comment]
@Geruays

**Comment by Geruays** [comment]
> @Geruays
` https://wakemyheroku.glitch.me/latestlog.txt `

**Comment by Geruays** [comment]
> > @Geruays
> > `https://wakemyheroku.glitch.me/latestlog.txt`

@khanhduytran0

**Comment by khanhduytran0** [comment]
Zink is known to be broken on Minecraft 1.12.2 and older.

**Comment by Geruays** [comment]
> Zink is known to be broken on Minecraft 1.12.2 and older.

Iya only support 1.13 +?

**Comment by Mathias-Boulay** [comment]
Shaders are known not to work.
Closing
