### ISSUE TITLE
[BUG] The actions build breaks right click

### ISSUE THREAD

**Issue by terrified9** [PojavLauncherTeam/PojavLauncher#1775]
### Describe the bug

Right click is now broken.
So there was a previous build that "should" fix right click (why? it was already fixed) so now the problem is that it removed the "Treat Right Click..."  button, and yes; this new build fixes right click BUT only when placing blocks, in the inventory, pause menu and etc it now acts as Back button.
I hope the devs bring back the old function for right click.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6925396/latestlog.txt)

### Steps To Reproduce

```markdown
1. Get a mouse (and keyboard) via OTG.
2. Launch 1.12.2 (Didn't test with other versions).
3. Go onto a server/world.
4. Open inventory.
5. Press right click, you'll see it acts like back.
```

### Expected Behavior

Left click should work like before with the right click function enabled 

### Platform

```markdown
- Device model: Xiaomi Mi A2 4/64GB
- CPU architecture: aarch64
- Android version: Android 10 
- PojavLauncher version: Actions Build #3052
```

**Comment by terrified9** [comment]
The build that broke it is #3044

**Comment by Mathias-Boulay** [comment]
@timof121 thanks for the report, I'll investigate the issue.
Video footage would be appreciated, since we can't properly debug every hardware device.

**Comment by Mathias-Boulay** [comment]
Here:
https://github.com/PojavLauncherTeam/PojavLauncher/runs/3285497831
MISSION COMPLEEEEEEEEEEEEETE !
Anyway, thanks for reporting again.
