### ISSUE TITLE
[BUG] <Microsoft Login Doesnt work>

### ISSUE THREAD

**Issue by Tigerrrrrrrrrrrrrr** [PojavLauncherTeam/PojavLauncher#1779]
### Describe the bug

Unable to log in via Microsoft. Gives me some error about addchildtofamily.msa.error. Please fix as I have been unable to play multiplayer.

### Steps To Reproduce

```markdown
1. Start pojavlauncher app
2. Login via Microsoft
3. Expect to get redirected further even though this doesn't happen at all. That's how I encountered it.
```

### Expected Behavior

I expect to be redirected further and be able to login via Microsoft

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
Clearly, it says: AddChildToFamily -> Add Child To Family

**Comment by khanhduytran0** [comment]
> The account is a child (under 18) and cannot proceed unless the account is added to a Family by an adult.

**Comment by Farhan11217** [comment]
STOP GIVE THIS FUCK

Pada tanggal Rab, 4 Agt 2021 07.40, Duy Tran Khanh ***@***.***>
menulis:

**Comment by khanhduytran0** [comment]
> STOP GIVE THIS FUCK Pada tanggal Rab, 4 Agt 2021 07.40, Duy Tran Khanh ***@***.***> menulis:
> […](#)

@Farhan11217 literally nobody forced you to watch the repo.
