### ISSUE TITLE
3.0.1 Preview 1-2, some errors

### ISSUE THREAD

**Issue by nicknickeryt** [PojavLauncherTeam/PojavLauncher#178]
I tried to start Minecraft rd-132211 on Android 10.

These errors showed up after pressing "Play" button:
![Screenshot_20200509-152125](https://user-images.githubusercontent.com/37023408/81475063-fa4e0700-9209-11ea-90f2-9b9f20e028fe.png)
![Screenshot_20200509-152130](https://user-images.githubusercontent.com/37023408/81475069-033ed880-920a-11ea-8e97-52d525779df5.png)

And these just after downloading OpenJDK V3. I think it's just a problem with one quote, as it says.
![Screenshot_20200509-152648](https://user-images.githubusercontent.com/37023408/81475072-06d25f80-920a-11ea-8e42-f018ec18a2f8.png)
![Screenshot_20200509-152653](https://user-images.githubusercontent.com/37023408/81475075-0934b980-920a-11ea-89cf-dda50d4a45fa.png)

**Comment by khanhduytran0** [comment]
Ok, know problem.

**Comment by khanhduytran0** [comment]
Try preview2!

**Comment by nicknickeryt** [comment]
Now it throws another error:

![Screenshot_20200510-112413](https://user-images.githubusercontent.com/37023408/81495508-f88b4e80-92b0-11ea-9be3-b06b61b70d69.png)
![Screenshot_20200510-112417](https://user-images.githubusercontent.com/37023408/81495512-fe812f80-92b0-11ea-9dd7-01a7c87b6619.png)

Tried to run in VMOS, there's another error:
![Screenshot_20200510-112428~2](https://user-images.githubusercontent.com/37023408/81495546-443df800-92b1-11ea-8b32-4d2f4900f087.png)
![Screenshot_20200510-112438~2](https://user-images.githubusercontent.com/37023408/81495563-63d52080-92b1-11ea-995d-3d962633dc7b.png)

**Comment by nicknickeryt** [comment]
Preview 4 fixed it. However, there's another error, but it's the same one as in #198, so closing
