### ISSUE TITLE
[BUG] 24 hours later game couldnt play with offline

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#1780]
### Describe the bug

 I download 1.17.1 and 1.7.10 tomorrow. But yesterday the game went well but this morning I woke up and saw that the game was not started and the game was downloaded again. If i play as offline then this is show me 

Java.io.FileNotfoundException:/storage/emulated/0/games/pojavlauncher/.minecraft/version/1.17.1/1.17.1/json:open failed EXONENT (Not a such file or direction) 

### The log file and images/videos

I want play as offline for forever with no download.  By the way i downloaded assets file too and 1.7.10 

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.runtime set arrch 64
3.renderer set open gles 1.1.5 2.0
4.download versions 1.17.1
5.assets set to resourcespack
6.start game
7.game is work well in 24 hours later i woke up and play as offline it told me for Download version again and assets too in all version
```

### Expected Behavior

I need help plz i experience lot of problems  

### Platform

```markdown
- Device model: samsung M21
- CPU architecture: arrch 64
- Android version: 11
- PojavLauncher version: action builds
```

### Anything else?

I need full solution from original developer

**Comment by Mathias-Boulay** [comment]
Files cleaners have to be disabled
But this won't be an issue since the crocus update
