### ISSUE TITLE
[F-Req] OptiFine 1.5.2 and below works without the mod installer

### ISSUE THREAD

**Issue by wackycreeper** [PojavLauncherTeam/PojavLauncher#1782]
### Describe the request.

Before 1.6.2, OptiFine can be downloaded as a zip file, however, to work, you need to place its .class files into the minecraft.jar file. I tried downloading older OptiFine versions from this forum: [[b1.4-1.9] OptiFine History](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1286605-b1-4-1-9-optifine-history) and tested it on Pojav, it fully works even without the mod installer! Sometimes crashes can occur, but at least it works!

Steps to install OptiFine 1.5.x or below in Pojav:
1. Go to the forum link above
2. Select a version 1.5.x or below
3. Every version has a spoiler, click it to view each version and download
4. Extract the OptiFine .zip file
5. Cut all of its .class files inside.
6. Navigate to the /games/PojavLauncher/.minecraft/versions folder
7. Use ZArchiver to paste the .class files into the .jar file of that version (must be 1.5.x or below or else it will not work)
8. Delete the META-INF folder (recommended)
9. Done, OptiFine is installed! 

OptiFine running on the first official Minecraft release:
![2021-08-04_06 23 41](https://user-images.githubusercontent.com/84388583/128137387-4f93bb2f-8dce-461f-957d-f092c6be02c1.png)
OptiFine running on 1.5.2:
![2021-08-04_07 15 52](https://user-images.githubusercontent.com/84388583/128139220-75a5b004-9d2d-4c70-bd22-aceb7c4c1a3d.png)

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
