### ISSUE TITLE
[BUG] 1.17 crashes 

### ISSUE THREAD

**Issue by frostyyyy1** [PojavLauncherTeam/PojavLauncher#1784]
### Describe the bug

Soooo I was trying to play Minecraft 1.17.1 on my Google pixel 5 and it's just crashes everytime I try to play 1.17.1

### Steps To Reproduce

```markdown
Just start 1.17.1 on Google pixel 5 its not working
```

### Expected Behavior

That it's starting up not crashing with the error code 1

### Platform

```markdown
- Device model: Google pixel 5 
- CPU architecture: Qualcomm, Octa-Core (64 Bit)
1. CPU: Snapdragon 765G (Cortex-A76), 1 x 2,40 GHz
2. CPU: Snapdragon 765G (Cortex-A76), 3 x 2,20 GHz
3. CPU: Snapdragon 765G (Cortex-A55), 4 x 1,80 GHz
Speicher	8,0 GB RAM
128,00 GB Speicher
- Android version: 11
- PojavLauncher version: version 3.3.1.1_rel_20210321
```

**Comment by frostyyyy1** [comment]
![Screenshot_20210804-120200](https://user-images.githubusercontent.com/88431649/128162655-3cca3bae-14a2-4261-b2d2-b925427c276f.png)

**Comment by NotAHero04** [comment]
You need to use the latest GitHub build to be able to install Java 17, which is a dependency for 1.17.

**Comment by frostyyyy1** [comment]
> You need to use the latest GitHub build to be able to install Java 17, which is a dependency for 1.17.

Ohhhh but I need to find it I'm too dumb

**Comment by frostyyyy1** [comment]
> You need to use the latest GitHub build to be able to install Java 17, which is a dependency for 1.17.

Could you send the link can't find it

**Comment by ghost** [comment]
here https://github.com/PojavLauncherTeam/PojavLauncher/actions

**Comment by crutchcorn** [comment]
Apologize for asking: but where can we find builds of Java 17 for ARM64 Android?

**Comment by foxy7300** [comment]
could you explain to me how to use the GitHub

**Comment by Mathias-Boulay** [comment]
duplicate.
Closing.
