### ISSUE TITLE
[BUG] <Version 1.17.1 crushed with code 1>

### ISSUE THREAD

**Issue by Charizzy** [PojavLauncherTeam/PojavLauncher#1785]
### Describe the bug

Application exited with code 1

### The log file and images/videos

--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms256m -Xmx512m"
Headless version detected! (20210706)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" unused DT entry: DT_RPATH (type 0xf
 arg 0x361) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
--------- beginning of system
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" unused DT entry: 
DT_RPATH (type 0xf arg 0x450) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" unused DT entry: DT_RPATH (type 0xf arg 0x33c0) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" unused DT entry: DT_RPATH (type 0xf arg 0x13b8) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
" unused DT entry: DT_RPATH (type 0xf arg 0x2196) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" unused DT entry: DT_RPATH (type 0xf arg 0x6a68) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
--------- beginning of main
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: DT_RPATH (type 0xf arg 0x4d9) (ignoring)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" unused DT entry: DT_RPATH (type 0xf arg 0xda0) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" unused DT entry: DT_RPATH (type 0xf arg 
0x5e6) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" unused DT entry: DT_RPATH (type 0xf arg 0x77) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" unused DT entry: DT_RPATH (type 0xf arg 0x1c7) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" unused DT entry: DT_RPATH (type 0xf arg 0x8ff) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" unused DT entry: DT_RPATH (type 0xf arg 0x16fe) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" unused DT entry: DT_RPATH (type 0xf arg 0x2e6) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" unused DT entry: DT_RPATH (type 0xf arg 0xe6
) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" unused DT entry: DT_RPATH (type 0xf arg 0x119) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" unused DT entry: DT_RPATH (type 0xf arg 0x364) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" unused DT entry: DT_RPATH (type 0xf arg 0x139) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" unused DT entry: DT_RPATH (type 0xf arg 0xf13) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" unused DT entry: DT_RPATH (type 0xf arg 0x3f1) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" unused DT entry: DT_RPATH (type 
0xf arg 0x158) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" unused DT entry: DT_RPATH (type 0xf arg 0x6af) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" unused DT entry: DT_RPATH (type 0xf arg 0x1c1) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" unused DT entry: DT_RPATH (type 0xf arg 0x6c1) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" unused DT entry: DT_RPATH (type 0xf arg 0x23a) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" unused DT entry: DT_RPATH (type 0xf arg 0x103
) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so
" unused DT entry: DT_RPATH (type 0xf arg 0x1d2) (ignoring)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (17010): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so success
I/jrelog  (17010): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so success
I/jrelog  (17010): dlopen /data/app/net.kdt.pojavlaunch-hBVRnbHwZ--y9fl7fo_CZA==/lib/arm64/libopenal.so success
I/LIBGL   (17010): Initialising gl4es
I/LIBGL   (17010): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   (17010): Using GLES 2.0 backend
I/LIBGL   (17010): loaded: libGLESv2.so
I/LIBGL   (17010): loaded: libEGL.so
I/LIBGL   (17010): Using GLES 2.0 backend
I/LIBGL   (17010): Hardware Full NPOT detected and used
I/LIBGL   (17010): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (17010): Extension GL_EXT_draw_buffers  detected and used
I/LIBGL   (17010): FBO are in core, and so used
I/LIBGL   (17010): PointSprite are in core, and so used
I/LIBGL   (17010): CubeMap are in core, and so used
I/LIBGL   (17010): BlendColor is in core, and so used
I/LIBGL   (17010): Blend Substract is in core, and so used
I/LIBGL   (17010): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (17010): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (17010): Extension GL_OES_mapbuffer  detected
I/LIBGL   (17010): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (17010): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (17010): Extension GL_OES_depth24  detected and used
I/LIBGL   (17010): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (17010): Extension GL_EXT_multi_draw_arrays  detected
I/LIBGL   (17010): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (17010): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (17010): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (17010): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (17010): Extension GL_OES_texture_float  detected and used
I/LIBGL   (17010): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (17010): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (17010): Extension GL_OES_fragment_precision_high  detected and used
I/LIBGL   (17010): Extension GL_EXT_shader_texture_lod detected and used
I/LIBGL   (17010): Max vertex attrib: 16
I/LIBGL   (17010): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (17010): Max texture size: 4096
I/LIBGL   (17010): Max Varying Vector: 15
I/LIBGL   (17010): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (17010): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (17010): Hardware vendor is Imagination Technologies
I/LIBGL   (17010): GLSL 300 es supported
I/LIBGL   (17010): GLSL 310 es supported and used
I/LIBGL   (17010): sRGB surface supported
I/LIBGL   (17010): EGLImage to Texture2D supported
I/LIBGL   (17010): EGLImage to RenderBuffer supported
I/LIBGL   (17010): ignore MipMap
I/LIBGL   (17010): Targeting OpenGL 2.1
I/LIBGL   (17010): NPOT texture handled in hardware
I/LIBGL   (17010): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (17010): try to use VBO
I/LIBGL   (17010): FBO workaround for using binded texture enabled
I/LIBGL   (17010): glX Will try to recycle EGL Surface
I/LIBGL   (17010): Current folder is:/
I/jrelog  (17010): dlopen /data/app/net.kdt.pojavlaunch-hBVRnbHwZ--y9fl7fo_CZA==/lib/arm64/libgl4es_114.so success
I/jrelog  (17010): Done processing args
I/jrelog  (17010): Found JLI lib
I/jrelog  (17010): Calling JLI_Launch
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

	at java.lang.ClassLoader.defineClass1(Native Method)

	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)

	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

Java Exit code: 1
I/jrelog  (17010): Going to free args
I/jrelog  (17010): Free done

### Steps To Reproduce

```markdown
1. Launch PojavLauncher
2. Login in account
3. Choose version
4. Start
```

### Expected Behavior

I expect the game to launches

### Platform

```markdown
- Device model: BQ 6630L
- CPU architecture: arm64-v8a
- Android version: 10
- PojavLauncher version: 1.17.1
```

**Comment by mchnjt** [comment]
WTF MAN

PLEASE UPLOAD THE LATESTLOG AS A FILE, NOT A COPY-PASTED TEXT YOU SON OF A-

**Comment by Charizzy** [comment]
Sorry, how to upload files here?

**Comment by NotAHero04** [comment]
You are using an older version of Java (in this case, Java 8)

**Comment by Charizzy** [comment]
I download all from Google Play Market😅

**Comment by NotAHero04** [comment]
Switch to the latest GitHub build, then download and install Java 17 to play

**Comment by Charizzy** [comment]
How switch to GitHub build?

**Comment by ghost** [comment]
here download the openjdk only https://github.com/PojavLauncherTeam/PojavLauncher/actions

**Comment by Charizzy** [comment]
Sorry, I'm not very good at GitHub.  There are many topics and I don't know where to go

**Comment by CriticalRange** [comment]
> Sorry, I'm not very good at GitHub. There are many topics and I don't know where to go

Go here and do things said. 1.17 and up works that way https://pojavlauncherteam.github.io/updates/117.html

**Comment by Charizzy** [comment]
It worked! Thx)
