### ISSUE TITLE
[F-Req] <Invisible buttons>

### ISSUE THREAD

**Issue by BigBotoDaddy** [PojavLauncherTeam/PojavLauncher#1786]
### Is this request related to a bug?

Is there some way to make the buttons transparent?  if so, how?

**Comment by ghost** [comment]
![Screenshot_20210808_180307](https://user-images.githubusercontent.com/79198391/128628276-f21e00ca-e6de-4c96-9467-5d9b531edbe2.jpg)

**Comment by ghost** [comment]
the button opacity

**Comment by ednellbasilio** [comment]
Any keyboard pojavalauncher team like the keys on the mods setting

**Comment by CriticalRange** [comment]
> Any keyboard pojavalauncher team like the keys on the mods setting

Huh ?
Try to be clearer please

**Comment by BigBotoDaddy** [comment]
> > Любая клавиатура pojavalauncher team понравится клавишам на настройках модов
> 
> Хм ?
> Попытайтесь быть понятнее, пожалуйста

+

**Comment by BigBotoDaddy** [comment]
> Любая клавиатура pojavalauncher team понравится клавишам на настройках модов
