### ISSUE TITLE
[BUG] MENU GLITCH WITH MODS ON CHROMEBOOK

### ISSUE THREAD

**Issue by Coolboy118** [PojavLauncherTeam/PojavLauncher#1788]
On my 32bit chromebook before I started Pojav launcher everything was alright but when it loads to the menu it was glitchy but almost all of the mods that I downloaded have this effect. I downloaded at least 10-20 mods and it still doesn't go back to normal. I tried older versions but it had the same problem. Is their any way to fix this problem?
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6932826/latestlog.txt)

image of the problem.

![Screenshot 2021-08-04 8 34 11 AM](https://user-images.githubusercontent.com/86877988/128236503-6a2a9b91-9446-47a9-86af-8d00adaadba1.png)

**Comment by ghost** [comment]
ehh wth happened

**Comment by Coolboy118** [comment]
sorry about that.

**Comment by Coolboy118** [comment]
have this ever happend to you?

**Comment by scihi** [comment]
Did you used any shader

**Comment by Coolboy118** [comment]
No I only used mods

**Comment by Coolboy118** [comment]
but it never happend on my Samsung A01

**Comment by scihi** [comment]
At this moment Chromebook is not fully supported

**Comment by scihi** [comment]
I hope you will understand the restrictions at this moment

**Comment by Mathias-Boulay** [comment]
#1948
