### ISSUE TITLE
Game crash(pics included)

### ISSUE THREAD

**Issue by glitchedmc** [PojavLauncherTeam/PojavLauncher#179]
Game crashed during singleplayer world. Not sure what happened

![Capture+_2020-05-09-17-07-44](https://user-images.githubusercontent.com/64292901/81484983-0214a800-9218-11ea-818b-2611998f348d.png)
![Capture+_2020-05-09-17-07-51](https://user-images.githubusercontent.com/64292901/81484987-0a6ce300-9218-11ea-8e17-abb1118a683e.png)

**Comment by khanhduytran0** [comment]
Looks like you clicked Exit button.

**Comment by glitchedmc** [comment]
Oof ok thanks
