### ISSUE TITLE
[BUG] Game suddenly closes without a crash report while playing

### ISSUE THREAD

**Issue by BannedExperiment** [PojavLauncherTeam/PojavLauncher#1790]
### Describe the bug

So while im playing on 1.12.2 ,game suddenly closes without any reports or something else,it puts me on either menu of PojavLauncher or Home Screen of my phone. I also use the JMV Launcher Argument for 3gb rams which i found from GitHub Page of PojavLauncher. If there is any solution or am i doing something wrong, please help.Thanks!

### Steps To Reproduce

```markdown
1. Start the Launcher
2. Open the World
3. Playing for a few minutes
4. Game suddenly closes without a report
```

### Expected Behavior

I expect to play the game without closing without a crash report in minutes.

### Platform

```markdown
- Device model: Huawei P Smart 2019
- RAM: 3gb
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: version 3.3.1.1_rel_20210321 (Play Store)
```

### Anything else?

I also have Forge 1.12.2 (Latest) , OptiFine 1.12.2 (Latest), Refined Storage, FTB Ultimine, MegaQuarry ,Just Enough Items installed. All mods work perfectly without any problem OptiFine aswell.

I ussualy have about 1gb free ram so i give 1gb ram to Launcher (basically all of it).

**Comment by BannedExperiment** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6933652/latestlog.txt)
 Here are my logs.

**Comment by Jatin-st** [comment]
Bro same problem

**Comment by omkar447** [comment]
Same

**Comment by BannedExperiment** [comment]
> Same

I dont know does it works or not but i tried lowering RAM to 700-800 from 1000mb i havent played for a long time but try that. Also 800mb ram is enough to play

**Comment by BannedExperiment** [comment]
Guys i tried a bit but try lowering your RAM dont max it what i mean is if your free ram is 1gb dont make it 1gb try like 700 or 800gb, i didnt play for a long time but it looks like it kind of works. Also its enough to play vanilla with that amount of RAM. Not modded though if you try your phone would probably turn into fried chips. Also dont forget to install OptiFine/Sodium with best settings for FPS (i was getting like 80 fps with 800mb of RAM!). There is tons of videos about that on YouTube also OptiFine worked better for me. I didnt have a problem when i lowered the RAM so i closed it. Thanks for reading hope i can help!
