### ISSUE TITLE
[BUG] Launcher process id: 15070

### ISSUE THREAD

**Issue by Airistak** [PojavLauncherTeam/PojavLauncher#1795]
### Describe the bug

I have installed pojav with runtime according to my mobile architecture and when i launch minecraft 1.17.1 an error code appears as in the title and the game not launched.

### The log file and images/videos

![IMG_20210805_123021](https://user-images.githubusercontent.com/64631783/128296239-d598b830-56d3-430e-a951-5694a7ebf7c4.png)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Launch Minecraft 1.17.1
3. And there's the problem
```

### Expected Behavior

I expected the game launched

### Platform

```markdown
- Device model: Huawei Y6 II Cam-L21
- CPU architecture: aarch64
- Android version: 6.0
- PojavLauncher version: version 3.3.1.1_rel_20210125
```

**Comment by khanhduytran0** [comment]
Do you think 1.17+ can be run on Java 8?

**Comment by khanhduytran0** [comment]
Also, you didn't send latestlog.txt

Do you see that "Launcher process ID" thingy also appears after login? So it's unrelated to 1.17 not working.

**Comment by khanhduytran0** [comment]
*Also, another person login with an email when offline account is enabled* :facepalm:

**Comment by Mathias-Boulay** [comment]
Known issue.
Closing.
