### ISSUE TITLE
Adult Microsoft account don't do anything

### ISSUE THREAD

**Issue by kylianpl** [PojavLauncherTeam/PojavLauncher#1799]
After clicking the Microsoft login, it open "do you want co connect to Minecraft Launcher", but when I click continue it just redirect me to pojav login

**Comment by khanhduytran0** [comment]
*there's no sign about the form being filled*

**Comment by kylianpl** [comment]
i did it on phone with the github app i will redo it on my computer, sorry

**Comment by kylianpl** [comment]
#1800
