### ISSUE TITLE
optifine menu?

### ISSUE THREAD

**Issue by glitchedmc** [PojavLauncherTeam/PojavLauncher#180]
i got optifine installed but isnt there supposed to be a menu or settings area for me to change optifine's settings??
If so it isnt showing up anywhere inside minecraft...

**Comment by khanhduytran0** [comment]
What launcher version?

**Comment by khanhduytran0** [comment]
Go to Video Settings.

**Comment by glitchedmc** [comment]
I did nothing shows up thats related to optifine
And the 2.4.2 version mcpe version1.8, 1.11, and 1.12

**Comment by khanhduytran0** [comment]
Try latest v2. Reopen if you still there to reply and got same problem.
