### ISSUE TITLE
[BUG] Adult Microsoft Login doesn't do anything

### ISSUE THREAD

**Issue by kylianpl** [PojavLauncherTeam/PojavLauncher#1800]
### Describe the bug

After clicking on Microsoft login and Continue, It redirect me to the login page.

### The log file and images/videos

https://user-images.githubusercontent.com/66625058/128478735-c0c40156-bc1e-4fb3-920d-d23a339d5603.mp4

### Steps To Reproduce

```markdown
1. go to PojavLauncher Login
2. enter Email and Password of Microsoft account
3. click "Microsoft login"
4. click "Continue"
```

### Expected Behavior

Got logged in with my microsoft account and can play Minecraft

### Platform

```markdown
- Device model: Mi 9T
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Version 3.3.1.1_rel_20210321
```

### Anything else?

My Microsoft account is an adult account and i have buy Minecraft java edition.

**Comment by khanhduytran0** [comment]
```
1. go to PojavLauncher Login
2. enter Email and Password of Microsoft account
3. click "Microsoft login"
4. click "Continue"
```

It's not exactly how to login with Microsoft. You need to enter email and password after press "Microsoft login" (if you have Microsoft account logged in on the browser, you will be immediately asked for continue)

**Comment by kylianpl** [comment]
If after the Microsoft login I use the login button it says:
`Response error
code: 403
message: {"error":"ForbiddenOperationException"
"errorMessage":"Invalid credentials. Invalid username or password."}`
but I tried 1 minute ago on the minecraft launcher with the same password and it worked
If I put my informations before and use Microsoft login,  it does the same thing as in the video.

**Comment by Ivyjunsy** [comment]
Did you bought mimecraft??

**Comment by kylianpl** [comment]
yes, as marked in the "Anything else" section

**Comment by khanhduytran0** [comment]
> If after the Microsoft login I use the login button it says:
> 
> `Response error
> 
> code: 403
> 
> message: {"error":"ForbiddenOperationException"
> 
> "errorMessage":"Invalid credentials. Invalid username or password."}`
> 
> but I tried 1 minute ago on the minecraft launcher with the same password and it worked
> 
> If I put my informations before and use Microsoft login,  it does the same thing as in the video.

Still, that's the wrong place to login. The right place to login is the screen pops up **after** you click Microsoft Login button.

**Comment by khanhduytran0** [comment]
![image](https://user-images.githubusercontent.com/40482367/128524069-b82838ae-bdc4-486f-8bcd-243c7940fbe6.png)

**Comment by ghost** [comment]
i think u need to logout ur acc in mojang login site where u use ur microsoft acc to login in java pc

**Comment by kylianpl** [comment]
I think the problem was Firefox, when doing exactly the same thing with Chrome, i could connect.
