### ISSUE TITLE
[BUG] Fabric mod not launching 

### ISSUE THREAD

**Issue by scihi** [PojavLauncherTeam/PojavLauncher#1802]
### Describe the bug

I installed fabric mod for version 1.16.5 but when i launched the game it was showing black screen i've waited for 20 minutes but still nothing happned.

### The log file and images/videos

![Screenshot_20210806-213657_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/83114809/128540056-85c1e429-baa3-4e4f-acd6-46c8a79b2df7.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6946720/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start pojav launcher 
2. Installed fabric for 1.16.5 
3. Put fabric API in mods folder
4. Launched the game 
5. It was showing black screen
```

### Expected Behavior

I expected that it will launch

### Platform

```markdown
- Device model: Samsung M31
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: zink
```

**Comment by nabiloi** [comment]
[16:04:56] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'iris': [1.1.0+rev.6ad325a at /storage/emulated/0/games/PojavLauncher/.minecraft/mods/iris-mc1.16.5-1.1.0.jar], [1.0.0-rc1 at /storage/emulated/0/games/PojavLauncher/.minecraft/mods/iris-mc1.16.5-1.0.0-standalone.jar]

there are two mods of the same "iris"

**Comment by scihi** [comment]
> [16:04:56] [main/FATAL]: A critical error occurred
> net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'iris': [1.1.0+rev.6ad325a at /storage/emulated/0/games/PojavLauncher/.minecraft/mods/iris-mc1.16.5-1.1.0.jar], [1.0.0-rc1 at /storage/emulated/0/games/PojavLauncher/.minecraft/mods/iris-mc1.16.5-1.0.0-standalone.jar]
> 
> there are two mods of the same "iris"

I removed one but still it is showing black screen

**Comment by khanhduytran0** [comment]
*send latestlog.txt moment again*

**Comment by scihi** [comment]
[Uploading latestlog.txt…]()

**Comment by scihi** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6951187/latestlog.txt)

**Comment by CriticalRange** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6951187/latestlog.txt)

You installed fabric API for minecraft version `1.17.1-rc1`, but you are running minecraft `1.16.5`. install the correct version and it will work.

**Comment by scihi** [comment]
> > [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6951187/latestlog.txt)
> 
> You installed fabric API for minecraft version `1.17.1-rc1`, but you are running minecraft `1.16.5`. install the correct version and it will work.

Yes!! Now it launched thanks to telling me but when i tried to enter the world with iris mod it crashed
