### ISSUE TITLE
[BUG] Cannot start Pojav with Risugami Modloader

### ISSUE THREAD

**Issue by wackycreeper** [PojavLauncherTeam/PojavLauncher#1803]
### Describe the bug

The Risugami Modloader beta 1.8.1 did not start in Pojav as expected, it gets stuck at Initializing... in the log output. The alpha 1.2.6 version of the modloader worked in the launcher very well.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6948721/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download Modloader b1.8.1.zip here: https://mcarchive.net/mods/modloader (this is the only available archive of this version)
2. Use ZArchiver to extract the .zip file and move all its .class files to the b1.8.1.jar in games/PojavLauncher/.minecraft/versions
3. Start Pojav and click play
4. See log output
5. Log stops at Initializing...
```

### Expected Behavior

Expected the game to launch normally

### Platform

```markdown
- Device model: Xiaomi POCO M3
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Current Play Store version
```

**Comment by wackycreeper** [comment]
Found a fix to this error: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/1291855-a-custom-tweaker-for-using-older-modloaders-in-the.
Modloader now works fine again, closing.

**Comment by mink90778** [comment]
Delete the META-INF like in a normal setup on a pc
