### ISSUE TITLE
[BUG] Keyboard any tap key but its crash

### ISSUE THREAD

**Issue by WITHERPROWER** [PojavLauncherTeam/PojavLauncher#1804]
### Describe the bug

PojavLauncher has unexpectedly crashed
I try keyboard tap any key but i crash but please fix

### The log file and images/videos

> 
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6949027/latestcrash.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Play Launch
3. Tap Singleplayer
4. Play World
5. Tap Chat
6. Tap Keyboard
7. Tap Any Key
8. Its Crash
```

### Expected Behavior

PojavLauncher has unexpectedly crashed

### Platform

```markdown
- Device model: Samsung Galaxy A7 2018
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: v3.3.1.1-1098-c09b80e5-v3_openjdk
```

**Comment by khanhduytran0** [comment]
Can you try [this build](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1108044511)?

**Comment by Mathias-Boulay** [comment]
Why the actual fuck the keyboard returns null device ?

**Comment by WITHERPROWER** [comment]
Ok thanks

**Comment by Mathias-Boulay** [comment]
> Ok thanks

So I guess it worked, right ?
If so, the issue must be closed.
