### ISSUE TITLE
When I can play 1.17 and upper version optifine

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#1806]
### Describe the request.

I want to play 1.17 and upper version optifine

**Comment by mchnjt** [comment]
First, let's take a look at these infos:

Pojav's default runtime is Java 8, and Pojav's default renderer is set to gl4es 1.1.4 (OpenGL 2)
(Java 17 is also available)

You don't really see much of the renderer options when using the PlayStore build, so if you want to play 1.17, get the latest **v3_openjdk/vgpu** action build.

artDev made a shader patch for 1.17, and sadly, it doesn't work on optifine

On the other hand, there's these renderers: vGPU and Zink

vGPU is on OpenGL 3, and Zink is on 4.6 (you must have Vulkan device library)

You can either:
Increase ram allocation for performance.
