### ISSUE TITLE
[BUG] I can't login into PojavLauncher

### ISSUE THREAD

**Issue by Adiixyz** [PojavLauncherTeam/PojavLauncher#1808]
### Describe the bug

I try to login in PojavLauncher but it says [ Can't login into Demo Account ]

### The log file and images/videos

no response

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. I enter email and password
3. I click login but doesn't work
```

### Expected Behavior

no response

### Platform

```markdown
- Device model: OPPO CPH1715
- CPU architecture: aarch64
- Android version: 6.0
- PojavLauncher version: latest
```

### Anything else?

no response

**Comment by khanhduytran0** [comment]
Demo mode is not yet supported. *go to Minecraft.net and buy the game, then it will be fixed.*

**Comment by Adiixyz** [comment]
> Demo mode is not yet supported. _go to Minecraft.net and buy the game, then it will be fixed._

ok
