### ISSUE TITLE
[BUG] crash when starting 1.14.3

### ISSUE THREAD

**Issue by hinum** [PojavLauncherTeam/PojavLauncher#1809]
### Describe the bug

while attempting to start 1.14.3 and 1.14.2 the game will crash

### The log file and images/videos

---- Minecraft Crash Report ----
// Don't do that.

Time: 8/8/2021, 10:31 น.
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cud.u(SourceFile:225)
	at cud.c(SourceFile:264)
	at org.lwjgl.glfw.GLFWWindowSizeCallback$Container.invoke(GLFWWindowSizeCallback.java:80)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1154)
	at cud.l(SourceFile:425)
	at cud.c(SourceFile:283)
	at cvk.b(SourceFile:1023)
	at cvk.e(SourceFile:976)
	at cvk.b(SourceFile:411)
	at net.minecraft.client.main.Main.main(SourceFile:154)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1658929976 bytes (1582 MB) / 2044198912 bytes (1949 MB) up to 2044198912 bytes (1949 MB)
	JVM Flags: 3 total; -Xms1989M -Xmx1989M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	Launched Version: 1.14.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 9x null

### Steps To Reproduce

```markdown
1.start pojavluncher
2.do as usual
3.switch to 1.14.3 or 1.14.2
4.play
5.wait

6.done

*Note* this also happens to optiFine
```

### Expected Behavior

game will start as normal unit the mojang bar rach half full then the game will crash

### Platform

```markdown
- Device model: oppo a31
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: 3.3.1.1_rel_20210321
```

### Anything else?

as i said this also happens on modded version of the game (ex. optiFine)

**Comment by Mathias-Boulay** [comment]
The launcher version seems really old
Last gplay release: 3.3.1.1_rel_20210321

**Comment by hinum** [comment]
@Mathias-Boulay sorry, i wrote the wrong version. the template says that the most recent gplay is that version.

**Comment by Mathias-Boulay** [comment]
This issue is still relevant with the crocus gplay update

**Comment by Theprozz** [comment]
I cant open 1.14 it crashes still

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
