### ISSUE TITLE
Custom Controls not opening..

### ISSUE THREAD

**Issue by glitchedmc** [PojavLauncherTeam/PojavLauncher#181]
Not sure if this is duplicate issue.
Im running 1.11
On the 2.4.2 version of the launcher

I have tried opening custom controls but it doesnt do anything...

**Comment by khanhduytran0** [comment]
V2.4.2 disabled custom control. V2.5 is can custom but can't apply to game. V3.0.1 can apply.

**Comment by khanhduytran0** [comment]
> V2.4.2 disabled custom control.

In v2.4.2 the custom controls is disabled due to not yet completed.
