### ISSUE TITLE
Every time I join Minecraft 3D it makes me get out of the app

### ISSUE THREAD

**Issue by Riotlong** [PojavLauncherTeam/PojavLauncher#1810]
### Describe the bug

...
😭😭😭😭

### The log file and images/videos

🙁🙁🙁

### Steps To Reproduce

```markdown
🍊😭😭😭😭😭
```

### Expected Behavior

Help!!!

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version
:
```

### Anything else?

Fix this can you fix it tomorrow please🐰🐰🐰

**Comment by scihi** [comment]
> ### Describe the bug
> ...
> 😭😭😭😭
> 
> ### The log file and images/videos
> 🙁🙁🙁
> 
> ### Steps To Reproduce
> ```gfm
> 🍊😭😭😭😭😭
> ```
> 
> ### Expected Behavior
> Help!!!
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version
> :
> ```
> 
> ### Anything else?
> Fix this can you fix it tomorrow please🐰🐰🐰

No latest.txt

**Comment by scihi** [comment]
Invalid issues

**Comment by CriticalRange** [comment]
> ### Describe the bug
> ...
> 😭😭😭😭
> 
> ### The log file and images/videos
> 🙁🙁🙁
> 
> ### Steps To Reproduce
> ```gfm
> 🍊😭😭😭😭😭
> ```
> 
> ### Expected Behavior
> Help!!!
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version
> :
> ```
> 
> ### Anything else?
> Fix this can you fix it tomorrow please🐰🐰🐰

Fill the template first
Also how old are you bruh

**Comment by khanhduytran0** [comment]
@Riotlong do you think these sad emojis contains information? 
```
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version
:
```

well, you think we can read your device info through mind..

**Comment by khanhduytran0** [comment]
Basically, that version use some strange piece of shaders
[Modified shader resource pack](https://cdn.discordapp.com/attachments/782924421177278464/809926216723202052/3DShareware4Pojav_resourcepack.zip)
Extract and put to /sdcard/games/PojavLauncher/.minecraft/resourcepacks folder.
On options.txt modify
```
resourcePacks:["vanilla", "3DShareware4Pojav"]
```
Change renderer to OpenGL ES 3

**Comment by WITHERPROWER** [comment]
Wait can i try 3d shareware Duy

**Comment by WITHERPROWER** [comment]
But its crash maybe
I gonna zink but WORK THANKS DUY

**Comment by khanhduytran0** [comment]
Zink = lag
gl4es = ~~69fps~~

**Comment by Riotlong** [comment]
![Screenshot_20210813-100730](https://user-images.githubusercontent.com/88624225/129478627-9c7da65e-3223-479b-842a-4583dcd860b5.png)
