### ISSUE TITLE
[BUG] Crashing when I select"Select Account"

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#1814]
### Describe the bug

Crashing when I select the "select account" button.

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6951952/latestcrash.txt)

### Steps To Reproduce

```markdown
1. Launch PojavLauncher
2. Select Account
3. Crashed
```

### Expected Behavior

I expected that this will not crash.

### Platform

```markdown
- Device model:CPH1853
- CPU architecture:aarch64
- Android version:8.1
- PojavLauncher version:[Latest Actions || version 3.3.1.1-1103-e874fe23-v3_openjdk]
```

### Anything else?

Just crashing when I tap this button.
![Screenshot_2021-08-09-11-08-27-18](https://user-images.githubusercontent.com/75970303/128656590-d9f01505-ecf0-4038-92cc-5c81139ae423.png)

**Comment by scihi** [comment]
Try the latest build in action menu

**Comment by Mathias-Boulay** [comment]
This sometimes happen with dev builds
A fresh installation is advised, meaning you need to delete the pojavLauncher folder
