### ISSUE TITLE
[BUG] Unable start 1.7.10-10.13.4.1564-forge-installer

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1816]
### Describe the bug

Unable to start forge installer

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6954655/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.use this jre8-aarch64 runtime https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/1086220179
3.start forge-1.7.10-10.13.4.1564-1.7.10-installer.jar
```

### Expected Behavior

Start the forge installer normally

### Platform

```markdown
- Device model: honor play 3
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: v3.3.1.1-1103-e874fe23-v3_openjdk
```

**Comment by CriticalRange** [comment]
Looks like there was a problem in mirror downloads of the forge
Also can you reproduce it on latest google play build (crocus-v3_openjdk ) ?

**Comment by NotAHero04** [comment]
No response. :fr:
A simple workaround is disabling the internet until the Forge installation screen shows, then turn the internet back on.
