### ISSUE TITLE
[F-Req] Add customizable textures for control bar

### ISSUE THREAD

**Issue by scihi** [PojavLauncherTeam/PojavLauncher#1818]
### Describe the request.

Can you add an option to add custom textures for control bar in pojav launcher?which will even make the control slook beautiful.

**Comment by Mathias-Boulay** [comment]
The control bar ?
Textures will bloat the device RAM though, making it unable to deal with anything texture heavy.
Like a resource pack 👀

**Comment by scihi** [comment]
> The control bar ?
> Textures will bloat the device RAM though, making it unable to deal with anything texture heavy.
> Like a resource pack 👀

Yes!! I'm talking about the control bar. Now it is up to the user to add texture or not in the control bar because i've seen many people who says that the controls aren't look great

**Comment by scihi** [comment]
Sorry but i don't want to disrespect anyone i like the control bar of POJAVLAUNCHER

**Comment by scihi** [comment]
It won't be a problem to those who have good amount of RAM just add a board to inform them that it will took some amount of your RAM

**Comment by Mathias-Boulay** [comment]
> It won't be a problem to those who have good amount of RAM just add a board to inform them that it will took some amount of your RAM

Actually, no.
Since VRAM is allocated by the hardware with and no control over how much it gives, even high end phones will suffer.
The RAM allocation of Minecraft is a totally different thing 😅

**Comment by scihi** [comment]
😅

**Comment by scihi** [comment]
Ok then but can you add an joystick in the control bar just as the Chinese version of mcpe

**Comment by Mathias-Boulay** [comment]
We cannot do that easily, else it would have been done.

**Comment by scihi** [comment]
> We cannot do that easily, else it would have been done.

That means that you are planning for it

**Comment by PTALTS-LK** [comment]
> We cannot do that easily, else it would have been done.

You can refer to this project, it has a joystick for controlling movement
https://github.com/AOF-Dev/MCinaBox

**Comment by scihi** [comment]
> > We cannot do that easily, else it would have been done.
> 
> You can refer to this project, it has a joystick for controlling movement
> https://github.com/AOF-Dev/MCinaBox

Oh man, I really hate this App but the joystick idea isn't that bad

**Comment by PTALTS-LK** [comment]
> > > We cannot do that easily, else it would have been done.
> > 
> > 
> > You can refer to this project, it has a joystick for controlling movement
> > https://github.com/AOF-Dev/MCinaBox
> 
> Oh man, I really hate this App but the joystick idea isn't that bad

Why hate it

**Comment by scihi** [comment]
Because of bugs

**Comment by PTALTS-LK** [comment]
> Because of bugs

😅😅😅

**Comment by scihi** [comment]
😅

**Comment by scihi** [comment]
So @Mathias-Boulay will you took the idea of joystick from McinaBox?(Man! i really hate that box app)

**Comment by scihi** [comment]
It is open source so i think you'll get the source code for the joystick isn't it?

**Comment by Mathias-Boulay** [comment]
Our codebase is vastly different since it has been tailored with performance in mind, it doesn't make the joystick idea easy.

**Comment by scihi** [comment]
I have an idea 💡

**Comment by scihi** [comment]
You can't add a joystick right but you can make something identical to it. Like, make the sneak button movable, when you took that button on up, down, left and right button like overlay the sneak button on them. So it will work as the button. Did you get it

**Comment by scihi** [comment]
![16286843551495947866422073036228](https://user-images.githubusercontent.com/83114809/129027345-e19be356-cfbd-4a29-927e-450a90d5b268.jpg)
 Ignore my bad drawing, just look into the concept which I am trying to show you

**Comment by scihi** [comment]
@Mathias-Boulay ?

**Comment by scihi** [comment]
So are you going to implement my idea @Mathias-Boulay

**Comment by Mathias-Boulay** [comment]
Nope.
