### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 121291** [PojavLauncherTeam/PojavLauncher#182]
When do you plan to add Hypixel support, as in making premium servers playable on premium accounts, and how do you feel about PatarHD showcasing this?

**Comment by khanhduytran0** [comment]
Premium support
- V2: Android 5.x only
- V3 may support premium servers.

**Comment by 121291** [comment]
Ok

**Comment by 121291** [comment]
Does this mean I can download an emulator for Android 5.0 and join premium servers?
