### ISSUE TITLE
[BUG] some of the games keep stopping

### ISSUE THREAD

**Issue by Riotlong** [PojavLauncherTeam/PojavLauncher#1820]
### Describe the bug

The bug might be stuck forever

### The log file and images/videos

Oh no that means it's going to be stuck forever I have an Android it might not be stuck on forever on Samsung or stuff

### Steps To Reproduce

```markdown
If you do for tomorrow I'll give you a billions of dollars not for real I would just give you a present
```

### Expected Behavior

I'm not happy

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

It's so annoying fix it

**Comment by scihi** [comment]
Devs aren't god who can read your mind and find the bug

**Comment by scihi** [comment]
No latestlog.txt provided

**Comment by scihi** [comment]
Invalid!! fill the template

**Comment by CriticalRange** [comment]
> ### Describe the bug
> The bug might be stuck forever
> 
> ### The log file and images/videos
> Oh no that means it's going to be stuck forever I have an Android it might not be stuck on forever on Samsung or stuff
> 
> ### Steps To Reproduce
> ```gfm
> If you do for tomorrow I'll give you a billions of dollars not for real I would just give you a present
> ```
> 
> ### Expected Behavior
> I'm not happy
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:
> ```
> 
> ### Anything else?
> It's so annoying fix it

Aaaaand you don't provide any log/information
Nice
`Wait a billion years and you'll get your issue fixed`
