### ISSUE TITLE
[BUG] Rendering error

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1821]
### Describe the bug

When I try to attack any creature, everything that should be transparent will be completely opaque

### The log file and images/videos

video
https://drive.google.com/file/d/10uYhl83L-bPhoZDOVBAJEWgIceo_XHb9/view?usp=drivesdk

log file
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6960630/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.install 1.12.2 and forge14.23.5.2854
3.start game
4.Use anything to attack any mob
5.see the error
```

### Expected Behavior

No error should occur

### Platform

```markdown
- Device model: horon play 3
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: v3.3.1.1-1105-3983c2a7-v3_openjdk
```

### Anything else?

This is the mod package I use
https://drive.google.com/file/d/10XPI74kp3sbc4ZEnmqLtMcJQU7XFFYxm/view?usp=drivesdk
I tried to remove all mods, but this error still appears

**Comment by Mathias-Boulay** [comment]
sounds like a known issue tbh

**Comment by PTALTS-LK** [comment]
> sounds like a known issue tbh

oooops(

**Comment by PTALTS-LK** [comment]
> sounds like a known issue tbh

So will this problem be solved?

**Comment by Mathias-Boulay** [comment]
you can hope so 🤔

**Comment by PTALTS-LK** [comment]
> you can hope so 🤔

😂😅

**Comment by ghost** [comment]
in 1.16 up, the egg and grass block become white even if you select the openjdk 8 or in other means jre 8
