### ISSUE TITLE
[BUG] 1.17.1 not downloading or launching

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#1823]
### Describe the bug

No Compatible java runtime? 

### The log file and images/videos

No log file available

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select version 1.17.1
3. Attempt to download 1.17.1
4. Error will appear (see screenshot for error)
```

### Expected Behavior

I expected the launcher to download and launch 1.17.1

### Platform

```markdown
- Device model: Huawei Y7 2019
- CPU architecture: Snapdragon 440
- Android version: 8.1.0
- PojavLauncher version: Latest Action version
```

### Anything else?

![Screenshot_20210810-142157](https://user-images.githubusercontent.com/63871578/128877873-919f1e0e-8dc5-45a0-8242-89b560cbc023.jpg)

**Comment by leetmussc** [comment]
CPU: aarch64

**Comment by HeinIsTaken** [comment]
You cant run snapshots 21w10a up because of the new 3.2 opengl and jre 16

**Comment by HeinIsTaken** [comment]
tho u can if u follow the instructions from pojavlauncher

**Comment by WesleyVanNeck** [comment]
use java 17
