### ISSUE TITLE
[BUG]  Keyboard tap key not showing in chat server

### ISSUE THREAD

**Issue by WITHERPROWER** [PojavLauncherTeam/PojavLauncher#1824]
### Describe the bug

I trying join server tap chat tap keyboard  tap any key and not shwing in chat server but i can' t register in crackpixel
Please fix

### The log file and images/videos

https://user-images.githubusercontent.com/86912937/128952999-48a8a1b1-631d-4347-aca6-3819b009edd0.mp4

### Steps To Reproduce

```markdown
1: Tap Multiplayer
2: Join Server In Crackpixel
3: Tap Chat
4: Tap Keyboard
5: Tap any keyboard
6: its not showing in chat server
```

### Expected Behavior

Keyboard any key Not showing in chat server

### Platform

```markdown
- Device model: Samsung Galaxy A7 2018
- CPU architecture: aarch64
- Android version: Android 10
- PojavLauncher version: v3.3.1.1-1139-847cc1e3e-v3_openjdk
```

**Comment by AgaricaGamer** [comment]
Where Is Your Chat Button?
Also Typing /(Slash) from keyboard dosent work.
Either Add The Chat Button Yourself Or Switch It To Default Controlmap

**Comment by WITHERPROWER** [comment]
> Where Is Your Chat Button?
> Also Typing /(Slash) from keyboard dosent work.
> Either Add The Chat Button Yourself Or Switch It To Default Controlmap

Hmm I gonna old bulid v3 openjdk but work thanks

**Comment by ednellbasilio** [comment]
![Port-Vance-Map-Thumbnail](https://user-images.githubusercontent.com/87942910/129143506-bc3ac65a-cef8-4d05-a5d2-7fbbdf240b92.jpg)
Port Vance city set your render distance to 10 it will lag before you walk then becarfule don't walk speed up in 100 don't jump 10 times If you spot some mobs Don't attack them

**Comment by ednellbasilio** [comment]
Here is my log render distance

**Comment by ednellbasilio** [comment]
The tap your music sounds

**Comment by Mathias-Boulay** [comment]
Does the bug happen in single player as well @WITHERPROWER ?

**Comment by Mathias-Boulay** [comment]
@WITHERPROWER I would like to study the keyEvent that comes from your trash phone.
Can you contact me via the official discord server ?

**Comment by khanhduytran0** [comment]
> @WITHERPROWER I would like to study the keyEvent that comes from your trash phone.
> 
> Can you contact me via the official discord server ?

He was banned for "pirating bedrock".

**Comment by Mathias-Boulay** [comment]
bruh, what do we do now ?

**Comment by khanhduytran0** [comment]
~~maybe unban or idk~~

**Comment by Mathias-Boulay** [comment]
Nah, he was banned for a reason.
I'll ping testers in the discord, I hope they have some trashy devices like his

**Comment by dxcvvxd** [comment]
what keyboard are u using?

**Comment by qulgentle** [comment]
is it external or virtual?

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
