### ISSUE TITLE
[F-Req] Minecraft Changelogs Page/Patch Notes Of Minecraft

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#1825]
### Is this request related to a bug?

Nope

### Describe the request.

It Would Be So Good If You Can Add A New Page Of Patch Notes Of Minecraft 
Ex:
Features Added In Various Versions Of Minecraft

Players Can Simply Read Them While Their Minecraft Is Downloading And 

### Anything else?

Don't Close It Please...

**Comment by NotAHero04** [comment]
Ask @rscDoesMoreTrolling for this, but a full changelog for just one major version will still take much time.

**Comment by Mathias-Boulay** [comment]
I'm pretty sure this won't be implemented.

**Comment by CriticalRange** [comment]
It might be separated like 
-PojavLauncher Changelog
-Minecraft Changelog
-PojavLauncher website (currently https://pojavlauncherteam.github.io but it'll be changed to https://pojav.ml ) 
-And Account Generator (I still believe like it should be changed to My Account, but the time will show)
