### ISSUE TITLE
Помогите не могу скачать фордж 

### ISSUE THREAD

**Issue by GrowScripts** [PojavLauncherTeam/PojavLauncher#1828]
### Describe the request.

help please i can not install the forge i download the launcher in two or three seconds my launcher crashes if there is a working link to 1.8.9 please

**Comment by scihi** [comment]
No latest.txt provided

**Comment by GrowScripts** [comment]
> Не предоставлен файл latest.txt

thanks

**Comment by WesleyVanNeck** [comment]
this is a issue not a enhencement open new issue with right format
