### ISSUE TITLE
[BUG] game don't want to load 

### ISSUE THREAD

**Issue by PolishPigeon21** [PojavLauncherTeam/PojavLauncher#1829]
### Describe the bug

After clicking the start button The controls appear and then throw me to the menu with options, the RAM is correct. Lenovo yoga tab 3

### Steps To Reproduce

```markdown
Login. Set up everything in options. Click start. Wait until everything download. And bug happens
```

### Expected Behavior

I expected to show me game menu 

### Platform

```markdown
- Device model: Lenovo yoga tab 3/64G
- CPU architecture:aarch64 
- Android version:8 
- PojavLauncher version: Latest realese of 11th September
```

**Comment by NotAHero04** [comment]
Where is the log? 😞

**Comment by scihi** [comment]
I don't understand why people don't share the latest log.txt

**Comment by ghost** [comment]
maybe they dont want to put it or they doesnt have any care about it
