### ISSUE TITLE
[BUG] Can't type "." symbol

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1830]
### Describe the bug

When I am adding a server to my list, I cannot type a ".", which means that I can't type any IPs. I'm using Gboard.

### Steps To Reproduce

```markdown
1. Have Gboard active
2. Launch Minecraft from PojavLauncher
3. Go to the server list and try adding a server.
4. Try typing a dot
```

### Expected Behavior

I expect the "." symbol to appear

### Platform

```markdown
- Device model: Xiaomi Mi 9
- CPU architecture: 
- Android version: MIUI 12 (Android 10)
- PojavLauncher version: Latest dev build
```

**Comment by WITHERPROWER** [comment]
All keyboard is doesn't work man

**Comment by ghost** [comment]
I think pojav Launcher should fix it I also want to write § symbol to color code but this too doesn't work I think until it gets fixed we should use hackers keyboard with some small settings I can write "."with hackers keyboard

**Comment by IrigoGamer** [comment]
> I think pojav Launcher should fix it I also want to write § symbol to color code but this too doesn't work I think until it gets fixed we should use hackers keyboard with some small settings I can write "."with hackers keyboard

> Man It's Java Not Bedrock You Can't Type That Symbol

**Comment by ghost** [comment]
It's too inconvenient to use hackers keyboard tho

**Comment by Mathias-Boulay** [comment]
"latest dev build" is not a version.
State the version or be **terminated**

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
