### ISSUE TITLE
[BUG] PojavLauncher Crashed

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1832]
### Describe the bug

PojavLauncher Crash while playing

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6974840/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Start game
```

### Expected Behavior

The game just close while playing

### Platform

```markdown
- Device model: Samsung Galaxy A01
- CPU architecture: aarch32
- Android version: 11
- PojavLauncher version: v3.3.1.1-1170-ad7fff575-clean_vgpu
```

**Comment by WesleyVanNeck** [comment]
do not use vgpu

**Comment by ghost** [comment]
Im using gl4es

**Comment by WesleyVanNeck** [comment]
> Im using gl4es

but your using the vgpu branch

**Comment by ghost** [comment]
Oh
