### ISSUE TITLE
[BUG] vgpu BUG

### ISSUE THREAD

**Issue by GiovaneFGC** [PojavLauncherTeam/PojavLauncher#1833]
A bug in vgpu 1.4.0 in the latest build of LegacyGamerHD, several chunks of the world are invisible, the performance with the renderer is better, I feel less drops, but the bug...

![Screenshot_20210812-111931_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/69176083/129214814-fad98550-85e6-4b45-ac80-288c50fcd43b.jpg)

![Screenshot_20210812-112046_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/69176083/129214855-a1c056b9-1498-42f1-b360-6565e4dc2c1e.jpg)

**Comment by WesleyVanNeck** [comment]
Do not use it it's not ready yet
