### ISSUE TITLE
[BUG] bug with vgpu

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1834]
### Describe the bug

bug:
water color bug 
![Screenshot_2021-08-12-18-11-56-511_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75588714/129223534-3ba9cae4-c394-4cd0-81d2-fd6d268278ee.jpg)
![Screenshot_2021-08-12-18-12-16-158_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75588714/129223548-7c7bf3ba-32d1-4942-9132-3ea2473d055f.jpg)

### Steps To Reproduce

```markdown
1: play any version mc with vgpu
```

### Expected Behavior

no.

### Platform

```markdown
- Device model: redmi note 8 pro
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: latest vgpu commin action build
```

### Anything else?

no

**Comment by WesleyVanNeck** [comment]
stop testing vgpu it isnt ready yet
