### ISSUE TITLE
[BUG] vgpu BUG

### ISSUE THREAD

**Issue by GiovaneFGC** [PojavLauncherTeam/PojavLauncher#1835]
### Describe the bug

Several chunks of the world are "invisible" or not render on vgpu 1.4.0

- CPU: Snapdragon 439 (12nm - 8x2Ghz - aarch32)
- GPU: Adreno 505 (650Mhz)

### The log file and images/videos

![Screenshot_20210812-111931_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/69176083/129227596-13f8ece3-1a32-463c-a6e4-7057932ab6d8.jpg)

![Screenshot_20210812-112046_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/69176083/129227641-e2f1d30f-70df-4b0f-9d54-5d045865826f.jpg)

### Steps To Reproduce

```markdown
1. Start Launcher

2. Use vgpu render

3. Launch minecraft

4. Open World

5. BUG
```

### Expected Behavior

Only bug i saw...

### Platform

```markdown
- Device model: Galaxy A01 
- CPU architecture: aarch32
- Android version: 11
- PojavLauncher version: 3.3.1.1-1170ad7fff575-clean_vgpu
```

**Comment by WesleyVanNeck** [comment]
again vgpu isnt ready for testing so stop posting issues about it

**Comment by jeremy985** [comment]
Turn all settings to fancy and make the tree to smart and chunk's to 8 chunks
