### ISSUE TITLE
[BUG] Keyboard Not Working

### ISSUE THREAD

**Issue by Farhansaja12** [PojavLauncherTeam/PojavLauncher#1836]
### Describe the bug

Why my keyboard not working even I use gboard but its still didnt working

### Steps To Reproduce

```markdown
1.Gboard Active
2.When typing doesnt work
3.i change keyboard is same. 
```

### Expected Behavior

I expect the keyboard working 

### Platform

```markdown
- Device model: Mi Note 10 6/64G
- CPU architecture:aarch64
- Android version: 11
- PojavLauncher version: Latest Build
```

**Comment by AgaricaGamer** [comment]
> ### Describe the bug
> Why my keyboard not working even I use gboard but its still didnt working
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> 1.Gboard Active
> 2.When typing doesnt work
> 3.i change keyboard is same. 
> ```
> 
> ### Expected Behavior
> I expect the keyboard working
> 
> ### Platform
> ```gfm
> - Device model: Mi Note 10 6/64G
> - CPU architecture:aarch64
> - Android version: 11
> - PojavLauncher version: Latest Build
> ```
> 
> ### Anything else?
> _No response_

No latestlog.txt also send image/video it can fix the issue faster

**Comment by WITHERPROWER** [comment]
Use hacker keyboard

**Comment by Farhansaja12** [comment]
> Use hacker keyboard

Did it work

**Comment by Farhansaja12** [comment]
> > ### Describe the bug
> > Why my keyboard not working even I use gboard but its still didnt working
> > ### The log file and images/videos
> > _No response_
> > ### Steps To Reproduce
> > ```
> > 1.Gboard Active
> > 2.When typing doesnt work
> > 3.i change keyboard is same. 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > I expect the keyboard working
> > ### Platform
> > ```
> > - Device model: Mi Note 10 6/64G
> > - CPU architecture:aarch64
> > - Android version: 11
> > - PojavLauncher version: Latest Build
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > _No response_
> 
> No latestlog.txt also send image/video it can fix the issue faster

Wait iam sending the video to u

**Comment by WITHERPROWER** [comment]
But Hacker keyboard doesn't work

**Comment by Farhansaja12** [comment]
> > ### Describe the bug
> > Why my keyboard not working even I use gboard but its still didnt working
> > ### The log file and images/videos
> > _No response_
> > ### Steps To Reproduce
> > ```
> > 1.Gboard Active
> > 2.When typing doesnt work
> > 3.i change keyboard is same. 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > I expect the keyboard working
> > ### Platform
> > ```
> > - Device model: Mi Note 10 6/64G
> > - CPU architecture:aarch64
> > - Android version: 11
> > - PojavLauncher version: Latest Build
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > _No response_
> 
> No latestlog.txt also send image/video it can fix the issue faster

Here 

>

**Comment by Mathias-Boulay** [comment]
Duplicate, so I'll close the issue.
