### ISSUE TITLE
Hosting Java Server From Your Device

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#1837]
### Is this request related to a bug?

Requirements:

A Device Having Atleast 6GB Ram(4GB Will Work Too But Not Recommended.)

>Two Phones Are Recommended

Applications: `Termux`,`Anlinux`,`Files(To Access Storage Of Termux)`

Termux: https://play.google.com/store/apps/details?id=com.termux

Anlinux:
https://play.google.com/store/apps/details?id=exa.lnx.a

Files(Important):
https://play.google.com/store/apps/details?id=com.marc.files

### Describe the request.

1. Open Anlinux And Goto Dashboard Tab
2. Select The Ubuntu Distro,Copy It And Tap On Launch
3. It Will Open Termux 
4. Paste The Command In There
5. Type "y" if it prompts
6. After The Installation type "./start-ubuntu.sh" this is the startup script.
7. Type `apt-get update`
8. Now copy and paste these commands 1-by-1
9. `apt-get install software-properties-common`
10. `add-apt-repository ppa:openjdk-r/ppa`
11. `apt-get update`
12. `apt-get install openjdk-8-jre`
_You Need Java 16 To Host Minecraft 1.17 Server_
13. *If It Prompts Type "y"*
14. >We Have Setup The Base Now Lets Get Into Minecraft Server
15. Now Select Your Server Software From The Below List:

`Vanilla`
`Paper`
`Spigot`

>Currently These Three Software Has Been Tested

_I Use Paper(It Is Recommended)_

16. Paper 1.16 Link: https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/786/downloads/paper-1.16.5-786.jar
17. Now Open the `Files` App (Documents) You Downloaded Before

18. ***You Need To Download These In Your Mobile Or Create A Folder For Easy Access***
19. Hold The File And Rename It To Paper
20. After Renaming Copy The File From It 
21. Goto `Termux->Ubuntu-fs->root`
22. Paste The File In There
23. Open Termux **Use Start Script(6th Step) If "root@localhost:" dosent show**
24. Type This Command `java -Xmx1024M -Xms1024M -jar paper.jar nogui` 
25. It Will Crash On First Try Because Of _EULA_
26. Type This Command `apt-get install nano`
27. Then This `nano eula.txt`
28. It isn't easy to edit file in eula you need to tap the down arrow 3 times for it to work

![Screenshot_20210813_103602](https://user-images.githubusercontent.com/69802631/129307488-85a217ef-5bc6-4345-8dd8-d12f73c8130d.png)

29. Change it to `true`
30. Now Again Type The Command(24th Step)
31. Now It Will Start The Server

[To Join Server Goto Multi-player On Direct-Connect type the ip: `localhost` ]

### Anything else?

You Need To Type Two Commands To Run Them
1. `./start-ubuntu.sh` 

2. `java -Xmx1024M -Xms1024M -jar paper.jar nogui`

>For Any Other Queries Please Comment 👇 Down Below

Source:
https://www.google.com/amp/s/beebom.com/how-host-minecraft-server-android/amp/

**Comment by WITHERPROWER** [comment]
I want try it

**Comment by ghost** [comment]
bad way, i know easier:)

**Comment by IrigoGamer** [comment]
> bad way, i know easier:)

However It Wont Lagg Out I Liked It

**Comment by Zeyrox1090** [comment]
I recommend using the termux from github

**Comment by NotAHero04** [comment]
*Launch a mod installer* exists for that purpose.

**Comment by Zeyrox1090** [comment]
I know but for fun

**Comment by Zeyrox1090** [comment]
Lol

**Comment by atharvabhilare** [comment]
Way not new version pojavlaunhet

**Comment by netkv** [comment]
but why issue in pojav github when its termux thing

**Comment by ghost** [comment]
Bro use proot in termux no ubuntu installation and can also edit the server files using file manager

**Comment by SprainedSpark89** [comment]
well i don't recommend that your just pressing a button that says do you want to risk crashing your device?

**Comment by Mathias-Boulay** [comment]
Closing, as it is not an issue.
Could be a separate application though
