### ISSUE TITLE
[BUG] every time I join on beefy computer it takes so long wait until you see the video

### ISSUE THREAD

**Issue by Riotlong** [PojavLauncherTeam/PojavLauncher#1838]
### Describe the bug

It happened sometimes oh my gosh it takes forever

### The log file and images/videos

https://user-images.githubusercontent.com/88624225/129380655-e93d2c2f-6850-43a2-a76c-55b1103e59ae.mp4

### Steps To Reproduce

```markdown
Number one go to 1.7.1 create a new word and don't choose the beefy computer that's all the lessons
```

### Expected Behavior

I was in 1.7.1 in the first time it logged me out of the war when I first joined and it takes a long time on you when you are in a beefy computer

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

![Screenshot_20210813-100730](https://user-images.githubusercontent.com/88624225/129381427-dd028087-6f75-44a0-a779-c770fea1d074.png)

**Comment by Mathias-Boulay** [comment]
Looks almost like a spam issue.
Closing.
