### ISSUE TITLE
V3.0.1 preview 1/2

### ISSUE THREAD

**Issue by TarikBR** [PojavLauncherTeam/PojavLauncher#184]
Moto one vision (android 10)
when it starts, gives this error

note: I put openjdk in the .minecraft folder. And in vmos 

![Screenshot_20200510-072706](https://user-images.githubusercontent.com/64391349/81498169-57d96680-9291-11ea-90cc-c91a1ffa02b4.png)
![Screenshot_20200510-072714](https://user-images.githubusercontent.com/64391349/81498173-590a9380-9291-11ea-85f0-35a918bec820.png)

In vmos:

![Screenshot_20200510-074556](https://user-images.githubusercontent.com/64391349/81498358-6e33f200-9292-11ea-9670-1e2dbb0d8c4b.png)
![Screenshot_20200510-074607](https://user-images.githubusercontent.com/64391349/81498359-6f651f00-9292-11ea-8e22-1f43a3772a7c.png)

**Comment by khanhduytran0** [comment]
You don't need to put OpenJDK by hand. Just leave for install automatically.

**Comment by TarikBR** [comment]
if I do not put openjdk, give this error and do not download

![Screenshot_20200510-081226](https://user-images.githubusercontent.com/64391349/81499005-3cbd2580-9296-11ea-9832-e7f97d985631.png)
![Screenshot_20200510-081234](https://user-images.githubusercontent.com/64391349/81499006-3dee5280-9296-11ea-9228-016ad15ddcf2.png)
![Screenshot_20200510-081300](https://user-images.githubusercontent.com/64391349/81499007-3e86e900-9296-11ea-82b4-d8dc6f4371ff.png)

**Comment by khanhduytran0** [comment]
It's go different error in preview 3 and you are not checked preview4.
