### ISSUE TITLE
Mouse Issues [BUG] <Short description>

### ISSUE THREAD

**Issue by EGAMatsu** [PojavLauncherTeam/PojavLauncher#1840]
### Describe the bug

So, i downloaded this on my old samsung phone (it only has like 256 MB LMAO but can play ROBLOX and shite fine)
But when i loaded into any version, there were mouse issues, now i remember boardwalk having mouse issues in alpha, but in 1.0+ it was fine there, but it just is not working here at all.

### Steps To Reproduce

```markdown
Load any version of the game and try too look
```

### Expected Behavior

Using finger to look about

### Platform

```markdown
- Samsung J3 Prime
- ARMx86
- 7.0
- Latest
```

**Comment by khanhduytran0** [comment]
> ## Platform
> - Samsung J3 Prime
> - x86

There were no Samsung phone that has an Intel CPU.

**Comment by Mathias-Boulay** [comment]
PojavLauncher version not stated.
FIll the missing info, or be **terminated**

**Comment by EGAMatsu** [comment]
> PojavLauncher version not stated.
> FIll the missing info, or be **terminated**

Latest google play.

**Comment by Mathias-Boulay** [comment]
Latest isn't a version 😂
