### ISSUE TITLE
[BUG] <keyboard not work at 1.17.1 

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#1841]
### Describe the bug

Keyboard issue founded on many version like 1.17+. Keycode is important for commands and more but i dont have keypad problem on 1.7.10.  Hacker keyboard not work 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6985936/latestlog.txt)

### Steps To Reproduce

```markdown
1.........
```

### Expected Behavior

I hope it will be fixed

### Platform

```markdown
- Device model: Samsung m21 
- CPU architecture: arrch 64
- Android version: 11
- PojavLauncher version: openjdk
```

### Anything else?

Please fix this

**Comment by Mathias-Boulay** [comment]
Please.
Video footage is missing
Steps to reproduce the bug is missing
PojavLauncher version is missing.
Fill them or the issue will be **terminated**

**Comment by Ewjjai** [comment]
It cause i deleted the game and wait for fixing sorry i forgot but many people have this problems

**Comment by Ewjjai** [comment]
It cause i deleted the game and wait for fixing sorry i forgot but many people have this problems

**Comment by WesleyVanNeck** [comment]
> It cause i deleted the game and wait for fixing sorry i forgot but many people have this problems

yes so use latest build of of main branch not vgpu

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
