### ISSUE TITLE
[BUG] Abnormal FPS

### ISSUE THREAD

**Issue by doubijunNB** [PojavLauncherTeam/PojavLauncher#1842]
### Describe the bug

FPS is very low when playing 1.17.1. This is not the FPS snapdragon 865SOC should have, including 1.16 and previous versions. This is a recent bug. I had no problem returning the official version

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6985958/latestlog.txt)
![Screenshot_2021-08-14-13-47-51-42_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/67856576/129435698-61b23a75-f36c-4e17-8da1-a5a236671dae.jpg)

### Steps To Reproduce

```markdown
1. Start the pojavlauncher 
2. Import jer17 runtime, download 1.17.1, and select renderer 
3. Start the game and enter the save
```

### Expected Behavior

I want frames to be normal, not 2fps

### Platform

```markdown
- Device model: OPPO ACE2
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: v3.3.1.1-1141-a89b77c13-v3_ openjdk
```

**Comment by artdeell** [comment]
How much RAM did u allocate?

**Comment by doubijunNB** [comment]
> 你分配了多少内存？

2GB

**Comment by hsragi** [comment]
Why doesn't the keyboard work.

**Comment by Mathias-Boulay** [comment]
Ew, android 11
Many devices just experience really bad performance with android 11 🤔 
At any rate, can you send the fps you get with a version that doesn't have this bug ?

**Comment by doubijunNB** [comment]
> 呃，android 11
> 许多设备在使用 android 11 时性能真的很差🤔
> 无论如何，您能否使用没有此错误的版本发送您获得的 fps？

![IMG_20210814_221217](https://user-images.githubusercontent.com/67856576/129449073-30fc3fd5-52bd-41f3-8e4e-d0050ecbdd57.jpg)
这个版本有100-200fps

**Comment by west-shell** [comment]
My device is 11 too.
I met the same problem whith Recent biuld.

![Screenshot_2021-08-15-04-57-50-460_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/50977607/129459869-7d9e96d9-fbf1-49b9-baf6-ec082ac8959d.jpg)
This version performs well.
The versions  builded after that time  almost all meet the same problem。

**Comment by prokage7237** [comment]
my phone is android 11 too but i cant play in 1.17.1

**Comment by prokage7237** [comment]
heres my log

**Comment by prokage7237** [comment]
content://media/external/file/109100

**Comment by Pgabrielmnecraft** [comment]
> conteúdo: // mídia / externo / arquivo / 109100

Myes

**Comment by WesleyVanNeck** [comment]
> my phone is android 11 too but i cant play in 1.17.1

offtopic create your own issue

**Comment by hsragi** [comment]
@doubijunNB My device is Android 10, but I can run 1.17 and FPS can reach 40 ~ 130.(doge)

**Comment by GiovaneFGC** [comment]
I also witnessed this fps problem, on 1.12.2 and 1.16.5, both versions running at 0~1 fps, I only got good fps using optifine (I got 30 fps+), my device is a Galaxy A01, before updating for Android 11 I didn't have this problem.

**Comment by pojavluncher2021** [comment]
@doubijunNB Use sodium mod, I will call a dev to close this issue

**Comment by Mathias-Boulay** [comment]
it should be fixed on the gplay crocus update
Closing
