### ISSUE TITLE
[BUG] keyboard not working on 1.17.1

### ISSUE THREAD

**Issue by Pgabrielmnecraft** [PojavLauncherTeam/PojavLauncher#1844]
### Describe the bug

I was trying to issue a command in chat and also search for an item in the inventory, but the keyboard doesn't write anything

I'm using a vgpu version that exports opengl 4.6

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6986613/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Start 1.17.1
3. Enter a random map or create one
4. Open inventory or chat and try to write something
5. Bug
```

### Expected Behavior

4. Open inventory or chat and enter write something
5. function normally

### Platform

```markdown
- Device model: Samsung a31 / 128 GB
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: 3.3.1.1-1177-f551c1317-clean_vgpu
```

**Comment by Ewjjai** [comment]
Use the freakin lastest build from mathias

**Comment by WesleyVanNeck** [comment]
dont use vgpu

**Comment by WesleyVanNeck** [comment]
vgpu isnt upstreamed most of the times
