### ISSUE TITLE
[BUG] Why Forge 1.16.5 Says Game Exited

### ISSUE THREAD

**Issue by DhairyaXDD** [PojavLauncherTeam/PojavLauncher#1847]
### Describe the bug

Why Forge 1.16.5 Says Game Exited

### The log file and images/videos

Why forge 1.16.5 says game exited

### Steps To Reproduce

```markdown
Why forge 1.16.5 says game exited
```

### Expected Behavior

Why forge 1.16.5 says game exited

### Platform

```markdown
- Device model: Vivo 1714 3/32
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210321 ]
```

### Anything else?

Why Forve 1.16.5 says game exited

**Comment by NotAHero04** [comment]
Why didn’t you send log?
Also, your build isn’t the latest one, even from Google Play.

**Comment by DhairyaXDD** [comment]
Log? What Is Logs I Am New Here :D

**Comment by WesleyVanNeck** [comment]
no logs no help
