### ISSUE TITLE
[BUG] External mouse bug on 1.16.x

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1848]
### Describe the bug

When I use an external mouse in version 1.16.1 or 1.16.5 it doesn't work, the mouse doesn't have a problem when I play on an old version it works perfectly, it only happens in 1.16

### Steps To Reproduce

```markdown
Open minecraft
Join in a world/server
Connect external keyboard/mouse
```

### Expected Behavior

Mouse working normal

### Platform

```markdown
- Device model: a30
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: Latest Release
```

**Comment by Mathias-Boulay** [comment]
Please, provide video footage of the issue.

**Comment by ghost** [comment]
> Please, provide video footage of the issue.

Ok! I will record now

PS: This account I made the issue is an old account, I deleted it but I still own it

**Comment by ghost** [comment]
> Please, provide video footage of the issue.

https://drive.google.com/file/d/1-r3sQuEiP-oOtAia5anV38rHjvyZpBBi/view?usp=drivesdk
video link

**Comment by Mathias-Boulay** [comment]
@D4yv1dKK can you try the newest action builds ?
Some work have been done, maybe it works for you now

**Comment by ghost** [comment]
> @D4yv1dKK can you try the newest action builds ?
> Some work have been done, maybe it works for you now

Actions builds are also buggy, but I found a way to solve

**Comment by Mathias-Boulay** [comment]
Oh, and what is this way ?  @D4yv1dKK

**Comment by ghost** [comment]
> Oh, and what is this way ? @D4yv1dKK

I edited the file "x.x.x.json" and put it to download the lib "net.java.jinput:2.0.5" that wasn't downloading I don't know why else it worked

**Comment by Mathias-Boulay** [comment]
Hmmm, thanks for reporting that
