### ISSUE TITLE
Immersive Vehicles not compatible?

### ISSUE THREAD

**Issue by RandomModderJDK** [PojavLauncherTeam/PojavLauncher#1849]
I know Forge and Forge Mods are pretty experimential but i want to ask if there is a solution to this problem.
 I have a "modpack" self created, with cars and roads. I found out, that Immersive Vehicles can not init. I dont know why net.java.games.input.ControllerEnviroment doesnt exist/ isnt loaded. 

Here is my crash report:
https://pastebin.com/EPHEd9iz

I have a oneplus nord running android 10

**Comment by RandomModderJDK** [comment]
And also how do i asign a label to this issue  on my phone?

**Comment by WesleyVanNeck** [comment]
first of all use the template second thiss issue will be terminates for not anough info soon

**Comment by khanhduytran0** [comment]
> And also how do i asign a label to this issue  on my phone?

GitHub app is limited. Use web instead. Also forms are not supported in GitHub app.

**Comment by RandomModderJDK** [comment]
Ok i will edit my issue

**Comment by RandomModderJDK** [comment]
New Issue at: https://github.com/PojavLauncherTeam/PojavLauncher/issues/1850
