### ISSUE TITLE
[BUG] Immersive Vehicles(Forge mod) not working?

### ISSUE THREAD

**Issue by RandomModderJDK** [PojavLauncherTeam/PojavLauncher#1850]
### Describe the bug

 I have a "modpack" self created, with cars and roads. I found out, that Immersive Vehicles can not init. I dont know why net.java.games.input.ControllerEnviroment doesnt exist/ isnt loaded (this says at least the log)

### The log file and images/videos

Crash report
https://pastebin.com/EPHEd9iz

Complete Log from PoJav launcher
https://pastebin.com/qgFEBiJn

### Steps To Reproduce

```markdown
1. Install Forge 1.12.2 latest
2. Install Immersive Vehicles V13
3. Press play
```

### Expected Behavior

I expect the game to launch and that the mod is working correctly

### Platform

```markdown
- Device model: Oneplus Nord
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest stable release
```

### Anything else?

If you say it isnt your problem, its the modders problem, at least try to give an workaround. Thanks

**Comment by ednellbasilio** [comment]
Try the immersive vehicle missing mods

**Comment by RandomModderJDK** [comment]
What missing mods? The class net/java/games/input/ControllerEnvironment isnt from a mod.

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
