### ISSUE TITLE
BUG with Optifine, GL4ES and VGPU

### ISSUE THREAD

**Issue by GiovaneFGC** [PojavLauncherTeam/PojavLauncher#1852]
### Describe the bug

When I activate the "Render Region" option the chunks bug, I used vgpu and in version 1.12.2 (I also tested on 1.16.5), unfortunately with GL4ES 1.1.4 and 1.1.5 the game crashes when opening with Optifine (on 1.12.2) and if you don't open it with Optifine the game runs on the base of 0~1 FPS (Already that in all versions with all renderers)

### The log file and images/videos

i had previously posted about the bug, but I didn't know where it came from, unfortunately I don't have an image or video at the moment.

### Steps To Reproduce

```markdown
I start the Launcher and use vgpu

I open 1.12.2 with optifine (Also on 1.16.5)

open a world

in the settings: Render Regions OFF (Ok)
Render Regions ON (Bug Chunks)

obs: In 1.16.5 I can play with gl4es 1.1.4 or 1.1.5 then I can activate the Render Regions option
```

### Expected Behavior

I just hope I can activate this option with the vgpu renderer or maybe use gl4es 1.1.5 on 1.12.2 with optifine without the game crashing.

### Platform

```markdown
- Device model: Galaxy A01
- CPU architecture: aarch32
- Android version: 11
- PojavLauncher version: v3.3.1.1-1149ab569fa21-v3_openjdk
```

**Comment by scihi** [comment]
Latestlog.txt,  Please!

**Comment by GiovaneFGC** [comment]
> Latestlog.txt,  Please! 

how do i send the file?

**Comment by WesleyVanNeck** [comment]
the issue is already send to vgpu dev

**Comment by L1v3p** [comment]
I have the same bug

**Comment by ghost** [comment]
Pojav launcher creator says render region don,t work on android and ios

**Comment by L1v3p** [comment]
Então Ele Vai Arrumar o Erro?
