### ISSUE TITLE
[F-Req] My Acc still got banned even if I made a new one

### ISSUE THREAD

**Issue by MrProPeeveepee** [PojavLauncherTeam/PojavLauncher#1853]
### Is this request related to a bug?

I don't really sure whats happening but I was playing pojavlauncher luckynetwork and suddenly i got banned because my ping jumped from 70-300 and back to normal which makes my hitreg weird,and i got banned for 24 hours,I make a new offline acc and I still got banned but Its a new acc I just made,can you explain whats happening?

**Comment by Mathias-Boulay** [comment]
Your ip was banned.
Not related to pojav.
