### ISSUE TITLE
Version are not downloadable  [BUG] <Short description>

### ISSUE THREAD

**Issue by Opdfb** [PojavLauncherTeam/PojavLauncher#1856]
### Describe the bug

When I download any version I will get error code 
"Unabble to resolve host libraries.minecraft.net" No adress is located with host name
Pls help me with this thing

### The log file and images/videos

![Screenshot_2021-08-17-10-52-54-742_net kdt pojavlaunch](https://user-images.githubusercontent.com/89061403/129668180-f3c199b4-6d2f-4639-a9fc-c622efcba8d2.jpg)

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: Mi 7 Pro
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
The form is not properly filled, and so will be closed.

**Comment by Minecrafter11231** [comment]
You might not have internet connection

**Comment by Opdfb** [comment]
No i dont have internet issues
