### ISSUE TITLE
How to Play With Mouse and Keyboard In Pojav

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#1859]
### Is this request related to a bug?

You Want to Play Pojav With mouse and keyboard but WASD doesn't work with you? Will I can help!

### Describe the request.

1.First You Need to download Sixaxis Controller From This link:https://sixaxis-controller.ar.uptodown.com/android/download

2.Open Sixaxis and change your keyboard to sixaxis keyboard (if you change your keyboard to sixaxis controller keyboard than it will work in bedrock edition too!)
![Screenshot_20210817_183548_com dancingpixelstudios sixaxiscontroller](https://user-images.githubusercontent.com/79517194/129756592-fb0a0d4d-d161-4701-8f27-880cdb5e95ba.jpg)

3.open Pojav And make new Controls

![Screenshot_20210817_183604_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/129756644-084d3be5-0de7-4280-8f63-42acd54c1684.jpg)

4. Delete all buttons to make the keyboard Function correctly

![Screenshot_20210817_183608_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/129756669-9647f7c5-3996-41e5-bdbc-702c441d6279.jpg)

5. there you go now you can play with mouse and keyboard

![Screenshot_20210817_183835_com mxtech videoplayer ad](https://user-images.githubusercontent.com/79517194/129756958-124795c8-9ad2-478b-baa3-0fda133df6cd.jpg)

### Anything else?

You can easily change your keyboard method form your keyboard by pressing windows button and space at the same time!

enjoy playing Bedrock and Java with mouse and keyboard!

**Comment by Mathias-Boulay** [comment]
Does this really work ?
I thought this app was only for ps3 controllers

**Comment by SolomoEudor143** [comment]
Also doesn't it require a rooted device to work?

**Comment by Mathias-Boulay** [comment]
For PS3 controller I think that yes, but it seems that sixaxis poses itself as an input method in this example, which might work

**Comment by Mathias-Boulay** [comment]
@EnderBrine99FOX Maybe you could do a wiki page instead of an issue ?
The issue is doomed to be removed here 🤔

**Comment by SuperTopGamers** [comment]
On my new cell phone, an A32, I'm going to play with an external keyboard and mouse using otg, and when I move the character's view inside the game, it doesn't work very well, it costs turning around. But I tested it on my old cell phone, an A20, and it worked perfectly.... what do I do?

**Comment by myavkat** [comment]
This did work for my Huawei Matepad11 and magnetic keyboard (no root!). Thanks! IMO this should be added to the FAQ or some other place.

**Comment by Mathias-Boulay** [comment]
Closing, as it is not an issue
