### ISSUE TITLE
[BUG] runtime error

### ISSUE THREAD

**Issue by GiovaneFGC** [PojavLauncherTeam/PojavLauncher#1860]
### Describe the bug

I used Java Runtime aarch32 in past versions, but after the last update "Android CI" onwards it gives error saying "Arm architecture is not compatible with aarch32", and automatic download downloads aarch64, which also says to be incompatible.

### The log file and images/videos

![Screenshot_20210817-134019_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/69176083/129767115-dac75741-38a2-4919-831a-9212e2786e16.jpg)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Play
3. Java Runtime error (with aarch32 and aarch64)
```

### Expected Behavior

I hope it works

### Platform

```markdown
- Device model: Galaxy A01
- CPU architecture: aarch32
- Android version: 11
- PojavLauncher version: v3.3.1.1-1188-536d920c0-v3_openjdk
```

### Anything else?

No

**Comment by Pgabrielmnecraft** [comment]
Instale a versão sem runtime e baixe um runtime arm ;)

**Comment by Pgabrielmnecraft** [comment]
Where is latestlog.txt?
