### ISSUE TITLE
[BUG] About independent version settings

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1861]
### Describe the bug

On this page, the renderer settings are not conspicuous

### The log file and images/videos

![Screenshot_20210818_100559_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/62936489/129825372-5fe65a02-7383-49d9-bada-013925dacc12.jpg)

### Steps To Reproduce

```markdown
1.start pojav
2.Long press version selection
```

### Expected Behavior

Normally see the renderer settings

### Platform

```markdown
- Device model: honor play 3
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: v3.3.1.1-1189-a30ad5177-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
Pretty sure it is the intended behavior though.

**Comment by CriticalRange** [comment]
![Screenshot_20210819-023029_PojavLauncher_(Minecraft_Java_Edition_for_Android)](https://user-images.githubusercontent.com/29708696/129985080-3ef10240-69f0-483c-88ac-528801594562.png)
Might be related to screen size/DPI, i can clearly see all of them at once
Or you are using an older version ? Maybe ?

**Comment by NotAHero04** [comment]
> Might be related to screen size/DPI, i can clearly see all of them at once
>
@CPXMC Try scrolling down the popup.

**Comment by Mathias-Boulay** [comment]
I just pushed a commit to fix this issue, thanks for reporting

**Comment by pojavluncher2021** [comment]
Can I make a commit too?, I have a repository called PojavLaunch, It's for
JSONs, not APKs so please watch my repo by clicking on all things like when
I do a commit or make a new workflow, thanks, Also. Thank you for pushing
that one commit
