### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Naturaly11580** [PojavLauncherTeam/PojavLauncher#1863]
### Describe the bug

Often exits alone when loading the world

### Steps To Reproduce

```markdown
i load the world
```

### Expected Behavior

Hopefully it can be fixed

### Platform

```markdown
- Device model: Redmi 5
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: 3.3.1.1_rel_2210206
```

**Comment by wackycreeper** [comment]
Where is the latestlog.txt and what version are you playing on?

**Comment by wackycreeper** [comment]
Where is the latestlog.txt and what version are you playing on?

**Comment by wackycreeper** [comment]
Can you join Pojav's discord server https://discord.gg/cs3gmjvx2r ?

**Comment by khanhduytran0** [comment]
*no latestlog.txt moment*

**Comment by Mathias-Boulay** [comment]
won't even bother asking for log this time.
