### ISSUE TITLE
[F-Req] New major Release for 1.17

### ISSUE THREAD

**Issue by Pro-Fessional18** [PojavLauncherTeam/PojavLauncher#1865]
### Is this request related to a bug?

Setting up 1.17 is too complicated 

### Describe the request.

Permanent solution for 1.17

**Comment by khanhduytran0** [comment]
Permanent solutions:
- ~~Get a PC~~
- ~~Insert RTX 3090 into your phone so you won't have to apply patch shader.~~

Putting JRE17 into app is not ready, 32bit support is broken.

**Comment by khanhduytran0** [comment]
> Setting up 1.17 is too complicated

If you have a PC, you would know, come back to 2015, when you had to install Java separately.

Adding patch zip file is just adding resource pack (which was automated)
