### ISSUE TITLE
[BUG] <World is bugged>

### ISSUE THREAD

**Issue by TheKiindred** [PojavLauncherTeam/PojavLauncher#1869]
### Describe the bug

I created worlds in different versions but i keep getting this bug, which is ruining the whole world.

### The log file and images/videos

![Screenshot_20210820-014317_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88246458/130154238-a9ab82b6-5397-4180-80d7-1d9035fb126b.jpg)

### Steps To Reproduce

```markdown
1. Staring PojavLauncher
2. Selecting the game's version
3. Launch the game
4. Create a world
```

### Expected Behavior

I expect the game to run properly

### Platform

```markdown
- Device model: Samsung galaxy A30
- CPU architecture: Octa-core (2x1.8 GHz Cortex-A73 & 6x1.6 GHz Cortex-A53)
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210206 ]
```

### Anything else?

It happens in every world i create, no matter what version I'm using.

**Comment by khanhduytran0** [comment]
Toggling fullscreen should do the trick.

**Comment by Fauzi345** [comment]
try turning on fast render
