### ISSUE TITLE
[F-Req] remove the update that moved the pojav directory 

### ISSUE THREAD

**Issue by Pgabrielmnecraft** [PojavLauncherTeam/PojavLauncher#1873]
### Is this request related to a bug?

I want them to go back to the old directory, in the games folder, since I don't have access to the new directory 

### Describe the request.

I can't find my textures or my versions because of the new directory 
![Screenshot_20210820-101556_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/85260889/130238912-9582269e-6c4b-4d28-ade4-7f4a9fa75b80.jpg)

### Anything else?

No

**Comment by wackycreeper** [comment]
Sorry to interrupt you but what? The directory is no longer in the games folder?? Where is the new directory now? I have not come across an issue like this before.

**Comment by Zeyrox1090** [comment]
In the root derictory where people who doesn't have root cant access 😂

**Comment by wackycreeper** [comment]
> In the root derictory where people who doesn't have root cant access 😂

Why? Not all phones are rooted. Such a shame.

**Comment by wackycreeper** [comment]
The .minecraft directory in the Minecraft Launcher did not even change?

**Comment by Zeyrox1090** [comment]
Maybe
Not sure i think it changed too

**Comment by wackycreeper** [comment]
> Maybe
> Not sure i think it changed too

I have a Windows computer and the .minecraft directory still stayed the same, %appdata%\.minecraft

**Comment by scihi** [comment]
It moved to android data folder

**Comment by scihi** [comment]
Android/data

**Comment by Mathias-Boulay** [comment]
Changed in newer builds, but not back to where it was before.
Google forces this, so deal with it.
