### ISSUE TITLE
I hear about update move pojav files to android/data folder (android 11 problem)

### ISSUE THREAD

**Issue by Hilma23** [PojavLauncherTeam/PojavLauncher#1874]
### Is this request related to a bug?

If you know android 11 you can't open 0/storage/emulated/android/data please change the update this is bad for android 11 user we can't put our custom controller / instal client&mod anymore please

**Comment by Hilma23** [comment]
sorry for putting the explanation wrong

**Comment by Pgabrielmnecraft** [comment]
Use zarchiver

**Comment by Pgabrielmnecraft** [comment]
it has a little compatibility, i use it to modify my .minecraft folder

**Comment by LivingCodeX** [comment]
Just use the default Files app. In the menu on the left, scroll down to PojavLauncher (Minecraft: Java Edition for Android) and click on it. From there, you can access the .minecraft folder just as easy as before.

**Comment by Mathias-Boulay** [comment]
Sadly, it is required by google itself.

**Comment by Hilma23** [comment]
If i use zarchiver or whatever files editor access will still be denied

**Comment by Hilma23** [comment]
LivingCodeX Wdym original file manager from my phone? They are no different from any other file managers, the results will be the same, data folder is gone/invisible
