### ISSUE TITLE
vk : Failed to CreateGraphicsPipeline

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1875]
### Describe the bug

I try to load the shader with Zink, but every time the program crashes, the log prints a Failed to CreateGraphicsPipeline.

But actually I want to know how pojav can make zink output image to pojav's window.
Still using the EGL bridge?

### Steps To Reproduce

```markdown
Start MC1.12.2 with pojav and zink, and compile the shader with OptiFine F5.
```

### Expected Behavior

I want it to load some simple shaders.

### Platform

```markdown
- Device model: LG v35
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: (zink newest)
```

**Comment by khanhduytran0** [comment]
> I try to load the shader with Zink, but every time the program crashes, the log prints a Failed to CreateGraphicsPipeline.

Loading shaders with Zink only works correctly on Mali GPUs for unknown reasons.

> But actually I want to know how pojav can make zink output image to pojav's window.

It just have to redirect stdio to log output.

**Comment by ghost** [comment]
> It just have to redirect stdio to log output.

Sorry, I think I misphrased it, I should have said: how does zink work on pojav? And how some of the rendering and context modules are wired together.

**Comment by WesleyVanNeck** [comment]
@luo9674  you can take look here https://github.com/PojavLauncherTeam/mesa/commits/release-21.0.0

**Comment by khanhduytran0** [comment]
> > It just have to redirect stdio to log output.
> 
> Sorry, I think I misphrased it, I should have said: how does zink work on pojav? And how some of the rendering and context modules are wired together.

~~oof I didn’t understand correctly~~ actually it uses OSMesa and manually refresh the window by rendering pixels data.
