### ISSUE TITLE
add gamepad support

### ISSUE THREAD

**Issue by NOM425378** [PojavLauncherTeam/PojavLauncher#1876]
### Describe the request.

pls add all gamepad support.i sick of using hand to play.i dont want my non-mfi gamepad to be useless in this launcher

**Comment by WesleyVanNeck** [comment]
it already hase gamepad support withoud a mod

**Comment by NOM425378** [comment]
ok

**Comment by rscAvePlex** [comment]
github on gmail

wtf

**Comment by NOM425378** [comment]
how
