### ISSUE TITLE
Black screen appears

### ISSUE THREAD

**Issue by AhsanChaudhary127** [PojavLauncherTeam/PojavLauncher#1877]
Alocatted 900 mbs of ram. If i open any minecraft version above 1.13 game shows black screen. I have huawei y9 2019 with 64 gbs of rom and 4 gb of ram
**Steps to reproduce**
`
1.Run any minecraft version above imcluding 1.12`

**Device:**
```
1. Huawei y9 2019
2. Ram = 4gb
3.Allocated to launcher 900 mbs
```

**Comment by WesleyVanNeck** [comment]
fill the tamplate and provide latestlog.txt or it will be terminated

**Comment by WesleyVanNeck** [comment]
also on 1.13 and up be pateint its a pc game

**Comment by ednellbasilio** [comment]
Me too my screen appear black when optifine +forge

**Comment by NotAHero04** [comment]
🥺 at least could you give us the launcher info and latestlog.txt?

**Comment by Mathias-Boulay** [comment]
no template
termination time

**Comment by pojavluncher2021** [comment]
Yup, I guess that issue is childish, Pfffft,
