### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by jianlin-15** [PojavLauncherTeam/PojavLauncher#1879]
### Describe the bug

Why does my mouse cursor appear in the upper left corner and so does uninstall and reinstall？😭😭😭

Uploading Screenrecording_20210822_135658.mp4…

### Steps To Reproduce

```markdown
My external mouse can still be used the day before yesterday, until I downloaded a version yesterday, and that's it
```

### Expected Behavior

I hope this is a BUG, which means you can fix it.

### Platform

```markdown
- Device model:IQOO Z3 8/128
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: v3.3.1.1-1216-7f2303123-v3_openjdk
```

**Comment by ghost** [comment]
uploading cancelled

**Comment by jianlin-15** [comment]
> 上传取消

I don't understand what you mean

**Comment by ghost** [comment]
your video uploading was cancelled

**Comment by jianlin-15** [comment]
> 您的视频上传被取消

I'm sorry, I don't know 😖，How can I continue to upload? I don't really know how to use github

**Comment by jianlin-15** [comment]
Uploading Screenrecording_20210822_135658.mp4…

**Comment by jianlin-15** [comment]
> 您的视频上传被取消

Well, I uploaded the video to Twitter, I hope you can check it out sometime.

https://twitter.com/hunuMadq71jOCaz/status/1429350559509884954?s=19

**Comment by ghost** [comment]
@khanhduytran0

**Comment by ghost** [comment]
wheres the latest log  i mean

**Comment by jianlin-15** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7028609/latestlog.txt)

**Comment by jianlin-15** [comment]
> 我的意思是最新的日志在哪里

I'm sorry. I don't know. I sent it out
