### ISSUE TITLE
[BUG] 1.17.1 crashes

### ISSUE THREAD

**Issue by 1kclouds** [PojavLauncherTeam/PojavLauncher#1881]
### Describe the bug

1.17.1 is crashing and saying "Game Exited" I've given it 2000 RAM and I'm running on a Samsung s20

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7028135/latestlog.txt)

### Steps To Reproduce

```markdown
1. Choose version 1.17
2. Press play
3. Black screen will appear and a message saying "Game exited" will appear
4. No crash log
```

### Expected Behavior

I expected the game to launch so I can play on my server

### Platform

```markdown
- Device model: Samsung Galaxy s20
- CPU architecture: ? 
- Android version: 11
- PojavLauncher version: Latest
```

**Comment by khanhduytran0** [comment]
Even if your phone has Intel Core i9, RTX 3090 and 1TB of RAM, you still can’t get 1.17.x to run on Java 8.

**Comment by khanhduytran0** [comment]
**1.17 requires Java 16**
https://pojavlauncherteam.github.io/updates/117.html
