### ISSUE TITLE
About the 3.3.1.1 version of the mouse will disappear after using the mouse and keyboard to enter the game Even if you open your backpack, you don't have a mouse  bug   [BUG] <Short description>

### ISSUE THREAD

**Issue by yx-storehouse** [PojavLauncherTeam/PojavLauncher#1884]
### Describe the bug

The main interface mouse of the game is still there. After entering the world, the mouse will disappear. After that, the software can only be restarted, and the mouse will recover .There is no mouse inside the backpack when you open it.The mouse cannot control the viewing angle rotation. I have several friends who have the same problem 

### Steps To Reproduce

```markdown
Connect the mouse and keyboard to enter the software and enter the 1.12.2 game. At this time, the mouse can still work normally. After creating the world and entering the world, the mouse fails. My mouse is moving in the video screen, and the backpack mouse cannot be summoned normally.
```

### Expected Behavior

I hope to be able to fix the bug that the mouse does not work properly. This is very important for us mouse and keyboard players. Finally, thank you to the developers for bringing us such a useful piece of software. 

### Platform

```markdown
- Device model: Redmi K30 Pro
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 
[Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by yx-storehouse** [comment]
After entering the game, the mouse cannot control the viewing angle. There is no mouse when opening the backpack, and there is no mouse in the settings

**Comment by paulopvw** [comment]
I have this problem too

**Comment by Mathias-Boulay** [comment]
it may be better with the crocus update.
Depends for people

**Comment by pojavluncher2021** [comment]
I agree with you, Crocus changed Pojavlauncher forever
