### ISSUE TITLE
And again, problem with Create

### ISSUE THREAD

**Issue by crtvxxx** [PojavLauncherTeam/PojavLauncher#1886]
### Describe the bug

after launch minecraft crashes

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7034772/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Wait, before game Loads
3. Minecraft crashes
```

### Expected Behavior

i expect game launch, but it not happen

### Platform

```markdown
- Device model: Honor 8X 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: v3.3.1.1-1217-8a44a9688-v3_openjdk
```

**Comment by crtvxxx** [comment]
UPD: The error appear on all renderers, and i mean, the problem occured by mod, but not sure

**Comment by khanhduytran0** [comment]
Duplicate of #1649

**Comment by khanhduytran0** [comment]
Have you ever used the issue search tool?
