### ISSUE TITLE
[BUG] <Game code 1 crashes, external mouse disappears>

### ISSUE THREAD

**Issue by jianlin-15** [PojavLauncherTeam/PojavLauncher#1887]
### Describe the bug

  Today I opened the game and it crashed with code 1. I didn't do anything 😭😭😭……
  I have tried to download the resource again, but the result is the same. I have downloaded it 3/4 times, and I have tried to delete [options. txt], but the result is the same
  Looks like these bugs, it only exists in Android 11, not just me

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7036123/latestlog.txt)

### Steps To Reproduce

```markdown
Start PojavLauncher——>Start game，In this way
```

### Expected Behavior

I hope the developer team can fix it soon. I really like playing PojavLauncher

### Platform

```markdown
- Device model: IQOO z3 8+3/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: [v3.3.1.1-1222-f8c124814-v3_openjdk]
```

**Comment by NotAHero04** [comment]
Try downgrading to [#3170](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1157935124).

**Comment by jianlin-15** [comment]
> 尝试降级到[#3170](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1157935124)。

All right, I'll try.

**Comment by jianlin-15** [comment]
> 尝试降级到[#3170](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1157935124)。

Still the same.

**Comment by Mathias-Boulay** [comment]
This build is buggy, and fixes have been deployed.
Closing
