### ISSUE TITLE
[BUG] Using sodium MOD on VGPU will render no blocks

### ISSUE THREAD

**Issue by qiouwag** [PojavLauncherTeam/PojavLauncher#1888]
### Describe the bug

Select VGPU in renderer to open na 1.16.5 version and enter the world will not see blocks only see entities request a solution

### Steps To Reproduce

```markdown
1.Start the PojavLauncher
2.Select "VGPU" from "Settings" - "Renderer"
3.Start Minecraft1.16.5 with the "sodium" MOD
4.In the world
5.Found unable to render block
```

### Expected Behavior

I hope to be able to fix this

### Platform

```markdown
- Device model: OPPO RENO 3 PRO
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-65-91c8921d2-v3_openjdk
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/7192156/latest.log)

```

**Comment by NotAHero04** [comment]
Send latestlog.txt please...

**Comment by qiouwag** [comment]
> Send latestlog.txt please...
Since the same problem occurred in VGPU3.0, I re-opened this issues，latest.log and it has been sent

**Comment by WesleyVanNeck** [comment]
simply dont use vgpu
