### ISSUE TITLE
Loading screen Pojavalauncher launcher android fix bug 

### ISSUE THREAD

**Issue by ednellbasilio** [PojavLauncherTeam/PojavLauncher#1889]
### Describe the bug

The stuck loading of Minecraft java on Android can't fix the loading screen when I download mods and you will see the loading issue was stopped and crash again anything else why the nether update is slower loading when you download mods 1.16.5 

### The log file and images/videos

My photo picture on my YouTube channel 
![minecraft_avatar___squid_by_superjenbot_d8bjgnc-pre](https://user-images.githubusercontent.com/87942910/130569754-cc2b73e5-ddb0-4dd3-a91e-434ca2a97667.jpg)

### Steps To Reproduce

```markdown
1.start your pojavalauncher 
2.you see the red screen
3.look at the white loading screen 
4.now if you see the stuck loading go here
5.create world flat may fast loading 
6.create world infinite now wait it until the loading 
7.now is finished now download mods 1.16.5
8.after download mods 1.16.5 look at your stuck loading screen
```

### Expected Behavior

For more stuck loading on your pojavalauncher when installing mods subscribe to my channel 
For pc are not stuck loading screen but in mobile java edition is crash again 

### Platform

```markdown
- Device model:oppo  
- CPU architecture:876
- Android version: 6245
- PojavLauncher version:1.16.5 and 1.12.2 mods
```

### Anything else?

Anyone did you fix the screen of pojavalauncher 
Seems crash after you intall all mods

**Comment by ednellbasilio** [comment]
Now everyone seems crash loading screen when you create infinite slower loading after to 1minutes seems crash

**Comment by WesleyVanNeck** [comment]
well the info is invalid

**Comment by WesleyVanNeck** [comment]
about your phone no latestlog.txt

**Comment by ednellbasilio** [comment]
Yeah but I download the latest log

**Comment by WesleyVanNeck** [comment]
> Yeah but I download the latest log

1 you dont download the latestlog.txt

**Comment by khanhduytran0** [comment]
Download ≠ Upload

**Comment by khanhduytran0** [comment]
> ## The log file and images/videos
> My photo picture on my YouTube channel

*this looks more advertising than a log file*

**Comment by pojavluncher2021** [comment]
HAHAHAHAHAHAHAHAHAH!
