### ISSUE TITLE
[BUG] <Login crashes> 

### ISSUE THREAD

**Issue by DeimoNF** [PojavLauncherTeam/PojavLauncher#1892]
### Describe the bug

 game crash when trying to log in with saved accounts

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7038346/latestcrash.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Click on login
3.Game crash
```

### Expected Behavior

?

### Platform

```markdown
- Device model: Redmi S2
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: latest build
```

**Comment by NotAHero04** [comment]
Did you try to re-login your account?

**Comment by Mathias-Boulay** [comment]
un-install the launcher, remove the games>pojavLauncher files if it exists then re-install

**Comment by pojavluncher2021** [comment]
Amazing deduplication!
