### ISSUE TITLE
[BUG] Mouse doesn't work in-game

### ISSUE THREAD

**Issue by CCShakeCat** [PojavLauncherTeam/PojavLauncher#1893]
### Describe the bug

When I am not screen recording, my mouse works in the menus, but in the game itself, it doesn't work half of the time and just snaps the vision in one direction. I have tried this with AND without **Labymod** and the same thing still happens, so it's not the client, and it's definitely the app.

### Steps To Reproduce

```markdown
1. Connect a mouse (🖱️) via Bluetooth
2. Open Pojav Launcher
3. Launch any Minecraft version
4. Open any world
5. Try to look around the world with the mouse
```

### Expected Behavior

I expect the mouse to look around as I move the mouse

### Platform

```markdown
- Device model: Samsung Galaxy Note 10 Ultra 5G*
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210321

* EDIT: I meant Note 20
```

### Anything else?

The only ways around this are to start recording your screen or use thhe touchscreen

**Comment by Mathias-Boulay** [comment]
The version used for reporting is too old.

**Comment by CCShakeCat** [comment]
That is the version from my Google Play though

**Comment by Mathias-Boulay** [comment]
I know.

**Comment by CCShakeCat** [comment]
Will this issue be fixed in the future (if not soon, anyway)?

**Comment by CriticalRange** [comment]
You can always try GitHub actions to see if your problem is fixed 👍

**Comment by CCShakeCat** [comment]
Where can I find that?

**Comment by yx-storehouse** [comment]
我也是这样

**Comment by NotAHero04** [comment]
> Where can I find that?

Could you try the updated build from Google Play?

**Comment by Mathias-Boulay** [comment]
This should be better with the crocus update

**Comment by pojavluncher2021** [comment]
-_- I'm very very sick and tired of mouse issues
