### ISSUE TITLE
[BUG] <glitchi shaders on vgpu>

### ISSUE THREAD

**Issue by puTz11** [PojavLauncherTeam/PojavLauncher#1894]
### Describe the bug

i used the ssr test shader and tested on vgpu renderer
but its buggy, the reflection and the shadows is glitching

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/f
![Screenshot_20210824_221415](https://user-images.githubusercontent.com/85058860/130654334-ba952ae6-e1fa-40a1-943d-1b42c3fde4c1.jpg)
iles/7040658/latestlog.txt)

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

i hope you know the problem:>

### Platform

```markdown
- Device model: vivo y12s
- CPU architecture: Octa-core (4x2.35 GHz Cortex-A53 & 4x1.8 GHz Cortex-A53)
- Android version: 11
- PojavLauncher version:v3.3.1.1-1232-27e762544-v3_openjdk
```

**Comment by GamerYTofficial** [comment]
what name the shaders?

**Comment by puTz11** [comment]
SSR test shader

Pada tanggal Rab, 25 Agu 2021 9.59 AM, GamerYTofficial <
***@***.***> menulis:

**Comment by WesleyVanNeck** [comment]
Not our issue
