### ISSUE TITLE
[BUG] Keyboard not working

### ISSUE THREAD

**Issue by FoxxoOwO** [PojavLauncherTeam/PojavLauncher#1895]
### Describe the bug

Keybord closes when I touch it. Only first row works.

### The log file and images/videos

https://user-images.githubusercontent.com/89482938/130679403-89368eb5-2580-4af0-8cf1-874ef6090132.mp4

### Steps To Reproduce

```markdown
1. Open the game
2. Use keyboard
```

### Expected Behavior

Normally using keyboard

### Platform

```markdown
- Device model: Redmi Note 8T
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210321 ]
- Keyboard: Emoji Keyboard 2.4.1 (com.facemoji.lite.xiaomi)
```

**Comment by Mathias-Boulay** [comment]
Bug fixed in dev builds
