### ISSUE TITLE
[BUG] Scrolling is not available in latest action builds

### ISSUE THREAD

**Issue by scihi** [PojavLauncherTeam/PojavLauncher#1896]
### Describe the bug

In some older versions of the pojav launcher, the scrolling was used to support but in the latest build, it is not working\available 

### Steps To Reproduce

```markdown
1. Start pojav 
2. Tried to change shader pack 
3. Scrolling wasn't working
```

### Expected Behavior

I thought the scrolling will work

### Platform

```markdown
- Device model: Samsung M31
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest action build
```

**Comment by Mathias-Boulay** [comment]
it is available, just with two fingers 🤔
