### ISSUE TITLE
No outline

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#1899]
### Describe the bug

I can't see outline around blocks

### The log file and images/videos

[12:18:29] [Render thread/WARN]: Shader rendertype_text could not find sampler named Sampler2 in the specified shader program.
[12:18:29] [Render thread/WARN]: Shader rendertype_text_intensity could not find sampler named Sampler2 in the specified shader program.

### Steps To Reproduce

```markdown
I don't know
```

### Expected Behavior

I want outline around blocks

### Platform

```markdown
- Device model: Samsung galaxy m31
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: pojavlauncher v3.3.1.1-1145-44a3d03ce-v3_openjdk
```

**Comment by khanhduytran0** [comment]
Looks like 1.17+, it was already listed in **Known issues** section.

**Comment by ajit850** [comment]
What I do to get outline

**Comment by khanhduytran0** [comment]
~~get RTX 3090
also you may want to notice that crosshair is missing~~

**Comment by ajit850** [comment]
What is problem in asset pack?

**Comment by Mathias-Boulay** [comment]
#1972
