### ISSUE TITLE
Doesn't work on dex

### ISSUE THREAD

**Issue by PopGTN** [PojavLauncherTeam/PojavLauncher#19]
When multi tasking mode is on in dex the launcher/game crashes

**Comment by khanhduytran0** [comment]
Disable and try again.

**Comment by khanhduytran0** [comment]
Please reply. Disable freeform or DeX.

**Comment by PopGTN** [comment]
That doesn`t work lol

**Comment by PopGTN** [comment]
Sorry i forgot about this

**Comment by khanhduytran0** [comment]
Still crash?

**Comment by khanhduytran0** [comment]
Try latest v2.5. Reopen if same thing happend.
