### ISSUE TITLE
[BUG] All Sheeps and Banners are white

### ISSUE THREAD

**Issue by iLikeMCBedrock** [PojavLauncherTeam/PojavLauncher#1902]
### Describe the bug

Banners, Sheeps and other things are white other than different color.

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Launch 1.16.5
```

### Expected Behavior

I expect the game to have all colors.

### Platform

```markdown
- Device model: Redmi Note 4x
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: 3.3.1.1-1103-1212914d-vgpu
```

**Comment by Sazedzahan** [comment]
Paste this in the pojavlauncher jvm argument

-Dorg.lwjgl.opengl.libname=libgl4es_115.so

**Comment by NotAHero04** [comment]
He uses the development version, so that method will not work. Instead, change the renderer to gl4es 1.1.5 in the launcher settings.
