### ISSUE TITLE
I didnt found pojavlauncher file

### ISSUE THREAD

**Issue by ZhakiThePro** [PojavLauncherTeam/PojavLauncher#1903]
### Describe the bug

when I want to put shaders in the file, there is no file

Vgpu

### Steps To Reproduce

```markdown
1.Open ZArchiver
2.Open games file
3.And nothing on there
```

### Expected Behavior

I can't use shader

### Platform

```markdown
- Device model: Vivo Y19 6/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest Vgpu cuz i didnt see version😅
```

**Comment by WesleyVanNeck** [comment]
Version isn't right

**Comment by ZhakiThePro** [comment]
> Version isn't right

Fine,here v3.3.1.1-1238-7aadde90c-v3_openjdk

**Comment by khanhduytran0** [comment]
The path is changed to `/sdcard/Android/data/net.kdt.pojavlaunch.debug`.

**Comment by ZhakiThePro** [comment]
lol how did you get there? 
🤣🤣

**Comment by ZhakiThePro** [comment]
But thanks

**Comment by ZhakiThePro** [comment]
![Screenshot_20210826_153706](https://user-images.githubusercontent.com/78971591/130921403-ca54001c-0d10-4d62-8855-708cefe904d2.jpg)
Guess the vgpu problem is still Do you think the vgpu problem is still an experiment or I'm the potato opengl 🤔

**Comment by CriticalRange** [comment]
> ![Screenshot_20210826_153706](https://user-images.githubusercontent.com/78971591/130921403-ca54001c-0d10-4d62-8855-708cefe904d2.jpg)
> Guess the vgpu problem is still Do you think the vgpu problem is still an experiment or I'm the potato opengl 🤔

I think it's still experimental-like, use gl4es for shaders :D

**Comment by ZhakiThePro** [comment]
> > ![Screenshot_20210826_153706](https://user-images.githubusercontent.com/78971591/130921403-ca54001c-0d10-4d62-8855-708cefe904d2.jpg)
> > Guess the vgpu problem is still Do you think the vgpu problem is still an experiment or I'm the potato opengl 🤔
> 
> I think it's still experimental-like, use gl4es for shaders :D

Oh ok
