### ISSUE TITLE
[BUG] Can't join some server on latest development build with1.17.1

### ISSUE THREAD

**Issue by fengyec2** [PojavLauncherTeam/PojavLauncher#1904]
### Describe the bug

I can't join some server (like mc.guapishijie.online),it shows "unknown host",but I can join it successfully on my computer.Anyway,I can join other server like "wdsj.net",the same WLAN,the different result!!!!!!!!!!!!

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Launch the game(1.17.1)
3.Choose mutiplayer
4.join mc.guapishijie.online
```

### Expected Behavior

I EXPECT JOIN THIS SERVER SUCCESSFULLY !!!

### Platform

```markdown
- Device model: HUAWEI_MATEPAD 10.4    6/128GB
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest
```

**Comment by YPSPlays** [comment]
I'm unable to join any server, does anyone know how to fix it

**Comment by Slapp13** [comment]
This is from PojavLauncher discord.

**Can’t join some servers on Java 16 (iOS) / Java 17 (Android, iOS)?
- Create /sdcard/games/PojavLauncher/resolv.conf (on Android) or /etc/resolv.conf (on iOS) with contents below. This is setting DNS
 + If you want to use Google DNS:
nameserver 8.8.8.8
nameserver 8.8.4.4

 + If you want to use Cloudflare DNS:
nameserver 1.1.1.1

• Additional steps required on Android:
- Download and install this runtime build. You may notice that it’s same as other, but it was rebuilt.
- Add this to JVM argument:
-Dext.net.resolvPath=/sdcard/games/PojavLauncher/resolv.conf

- Enjoy playing servers with Java 16+!**

**Comment by Slapp13** [comment]
This is from PojavLauncher discord.

**Can’t join some servers on Java 16 (iOS) / Java 17 (Android, iOS)?
- Create /sdcard/games/PojavLauncher/resolv.conf (on Android) or /etc/resolv.conf (on iOS) with contents below. This is setting DNS
 + If you want to use Google DNS:
nameserver 8.8.8.8
nameserver 8.8.4.4

 + If you want to use Cloudflare DNS:
nameserver 1.1.1.1

• Additional steps required on Android:
- Download and install this runtime build. You may notice that it’s same as other, but it was rebuilt.
- Add this to JVM argument:
-Dext.net.resolvPath=/sdcard/games/PojavLauncher/resolv.conf

- Enjoy playing servers with Java 16+!**

**Comment by NotAHero04** [comment]
> Download and install this runtime build...
>
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/1165988189

**Comment by Mathias-Boulay** [comment]
The fix has been auto deployed on the latest crocus gplay update 😄

**Comment by pojavluncher2021** [comment]
Minecraft didn't release 1.17.2 lol 😂😂😂😂😂😆😅

**Comment by pojavluncher2021** [comment]
Also on the crocus update, You now get how many MB is downloaded from the
assets e.g. I I am downloading 21w16a rn and it's 329.50MB which is good
that it doesn't put it in the Internal Storage,

**Comment by pojavluncher2021** [comment]
Oops the asset size was 329.05MB
