### ISSUE TITLE
[BUG] Please fix this

### ISSUE THREAD

**Issue by Isan1736** [PojavLauncherTeam/PojavLauncher#1907]
### Describe the bug

![Screenshot_20210827_092658](https://user-images.githubusercontent.com/84948958/131062389-72bc2e91-29c4-4920-a87a-852dfdd1ec72.jpg)

### The log file and images/videos

White screen vgpu

### Steps To Reproduce

```markdown
1.start pojavlauncher with renderer vgpu play white screen
```

### Expected Behavior

rd

### Platform

```markdown
- Device model:Vivo 1814(y93) 3/32
- CPU architecture:aarch64
- Android version:8
- PojavLauncher version:[Latest release version 3.3.1.1-1149-ab569fa21-v3_openjdk
```

### Anything else?

No

**Comment by NotAHero04** [comment]
VGPU is not very stable, it could cause white screen for some devices. Also, your launcher seems to be old, try updating to see if your problem has been fixed.

**Comment by Isan1736** [comment]
Thanks bro
