### ISSUE TITLE
Game Exited Message

### ISSUE THREAD

**Issue by MarcoHandresClayton** [PojavLauncherTeam/PojavLauncher#1912]
### Describe the bug

When i load versions (1.13+)
After downloading it says (Game Exited)
So i have to play the older versions

### The log file and images/videos

![Screenshot_20210827-193003](https://user-images.githubusercontent.com/89194836/131158239-b397cb2d-cbbf-425b-b1aa-42794f564198.png)

### Steps To Reproduce

```markdown
1.Open The Launcher
2.Select Versions 1.13 and up
3.Download the said version
4.It automatically enters you in and says "Game Exited"
5.It closes the game without any reason
```

### Expected Behavior

I expect the game to be loaded but it just gives me a message then quits me

### Platform

```markdown
- Device model: Cherry Mobile Magnum A890
- CPU architecture: 8x ARM Cortex-A55 @ 1.20 GHz
- Android version: 10
- PojavLauncher version: Latest Release
```

### Anything else?

This occurs in every of the latest versions

**Comment by WesleyVanNeck** [comment]
give latestlog.txt or the issue will be terminated
