### ISSUE TITLE
[BUG] editing controls crash the pojavlauncher

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#1914]
### Describe the bug

Custom controls crash the pojavlauncher

### Steps To Reproduce

```markdown
1. Start the pojavlauncher
2.open custom controls then edit SEC.
3.then crash
```

### Expected Behavior

- Device model: Galaxy-j2
- CPU architecture: aarch32
- Android version: 5.1.1
- PojavLauncher version:  v3.3.1.1_rel_3db1eec

### Anything else?

_No response

**Comment by Sazedzahan** [comment]
Please fix this.😭😭😭😭😭😭😭

**Comment by WesleyVanNeck** [comment]
Get a newer device with a better android version as far as I know android 5.1 got some issues

**Comment by Sazedzahan** [comment]
Thanks

**Comment by khanhduytran0** [comment]
latestcrash.txt is not attached.

**Comment by Mathias-Boulay** [comment]
Old version moment
