### ISSUE TITLE
[BUG] Black screen when I restart Pojav

### ISSUE THREAD

**Issue by peasoft** [PojavLauncherTeam/PojavLauncher#1915]
### Describe the bug

When I start the game, back to the desktop, and back to Pojav, I get a black screen. I can only exit Pojav and restart it, but this will make my game data lost.

### The log file and images/videos

[log.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7070739/log.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start the game
3. Go to desktop(home screen)
4. Back to PojavLauncher
5. Black screen
```

### Expected Behavior

I want to back to the game, not the black screen.

### Platform

```markdown
- Device model: OPPO A37m
- CPU architecture: aarch64
- Android version: 5.1
- PojavLauncher version: version 3.3.1.1_rel_20210321
```

**Comment by artdeell** [comment]
This is caused by your device not having enough memory/processor resources to keep the app running in the background

**Comment by peasoft** [comment]
Now I test the bug again, and I get some logs.
[log.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7070739/log.txt)

**Comment by CHECK-12345** [comment]
> This is caused by your device not having enough memory/processor resources to keep the app running in the background

Im having the same issue on LG V40 sdm845 with 6gb ram where when i enter the home screen and go back, the game restarts.

I did not have this issue on older pojav builds. The older pojav launchers have a notification whenever the game is running and the game does not restart when i enter home screen.

Maybe putting back the notification when the game is running could solve this issue.

**Comment by artdeell** [comment]
Xiaomi Mi 8. SD845. 8GB RAM. The game only shuts down if i start some other game. It's either resources or settings.

**Comment by wackycreeper** [comment]
Yeah I am having this issue on my Xiaomi POCO M3, the game instantly restarts when pressing the home screen button. It annoys me especially when typing world seeds.

**Comment by wackycreeper** [comment]
Yeah I am having this issue on my Xiaomi POCO M3, the game instantly exits when pressing the home screen button.

**Comment by Dai2k9hihipro** [comment]
Reducing ram to 256M is working

**Comment by Dai2k9hihipro** [comment]
Adjust ram and it works
4GDRam=1024mb
2ram=750md or 512mb
