### ISSUE TITLE
[BUG] White Screen when play in Pojavlauncher Vgpu

### ISSUE THREAD

**Issue by ilham577** [PojavLauncherTeam/PojavLauncher#1916]
### Describe the bug

![Screenshot_2021-08-27-23-37-33-78](https://user-images.githubusercontent.com/83561245/131217915-4d75b284-cfcf-4dc6-8851-989e2a8cb116.jpg)

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/7070704/latest.log)

### Steps To Reproduce

```markdown
1.start pojav launcher
2.choose version
3.play
4.in loading screen is white (when using vgpu)
```

### Expected Behavior

I hope the game runs normally

### Platform

```markdown
- Device model: oppo a5s
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: [Latest Release || Version 3.3.1.1-1149-ab569fa21-v3_open jdk
```

**Comment by WesleyVanNeck** [comment]
Don't report vgpu bugs here

**Comment by WesleyVanNeck** [comment]
Also wrong log

**Comment by ilham577** [comment]
> Don't report vgpu bugs here

How to fix it?
