### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by AndreLaunch** [PojavLauncherTeam/PojavLauncher#1917]
### Describe the bug

On my PojavLauncher, it keeps freezing the screen, it's been a while, I wanted to know how to solve it.

### Steps To Reproduce

```markdown
1. Delete PojavLauncher files.
2. Download everything again and play.
```

### Expected Behavior

I thought I would solve it.

### Platform

```markdown
- Device model: Moto G7 Polar/64G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: 3.3.1.1_rel_20210321
```

### Anything else?

I really wanted your help.

**Comment by Mathias-Boulay** [comment]
old version, no logs.
Use the latest crocus update
