### ISSUE TITLE
[BUG] Control + Middle Mouse Button isn't working

### ISSUE THREAD

**Issue by molor** [PojavLauncherTeam/PojavLauncher#1918]
### Describe the bug

Control + Middle Mouse Button isn't giving me a block with it NBT data — probably CTRL checkbox isn't working?

### Steps To Reproduce

```markdown
1. Create a custom controls layout and add a button that does SPECIAL_MID + CTRL checkbox
2. Place a sign in any world with text on it
3. Focus on it and click the created button
```

### Expected Behavior

I'm received the block with it's NBT data instead of raw block

### Platform

```markdown
- Device model: Sony Xperia XZ1
- CPU architecture: 64-bit
- Android version: 9
- PojavLauncher version: 3.3.1.1
```

### Anything else?

This problem happens on vanilla Minecraft 1.16.5

**Comment by Mathias-Boulay** [comment]
Known and duplicate
