### ISSUE TITLE
[F-R] Add ability to use F3+Key shortcuts via custom controls

### ISSUE THREAD

**Issue by molor** [PojavLauncherTeam/PojavLauncher#1919]
### Is this request related to a bug?

No.

### Describe the request.

There are many useful command in Minecraft, for example reload all chunks (F3+A, reduces CPU & GPU usage), creative <-> spectator toggle (F3+N) or fast game mode switcher (F3+F4) — but it's cannot be accessed if I don't have keyboard plugged in.. Adding an ability to create button with this shortcut in custom controls can solve this.

### Anything else?

Thanks

**Comment by Mathias-Boulay** [comment]
Already exists on latest
