### ISSUE TITLE
[BUG] The external mouse doens't works in game

### ISSUE THREAD

**Issue by LeLeeo1456** [PojavLauncherTeam/PojavLauncher#1921]
### Describe the bug

when i'm in the menu it works but in a map not, the external keyboard works. I only can move the screen with the touch.
i enter in a map, everything is right until a move the mouse which turns the screen bright. apparentely nothing more to report.

### Steps To Reproduce

```markdown
use a usb adapter in the smartphone to use the mouse, and enter in a map
```

### Expected Behavior

to i can use the mouse to move the screen in game

### Platform

```markdown
- Device model: Moto G9 Play/ 64GB 4GB Ram
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version:v3.3.1.1-1252-f454a6edb-v3_openjdk
```

**Comment by WesleyVanNeck** [comment]
Can not reproduce

**Comment by khanhduytran0** [comment]
Duplicate of #1884

**Comment by paulopvw** [comment]
Can you tell if this problem will be solved?

Em dom, 29 de ago de 2021 10:21, Duy Tran Khanh ***@***.***>
escreveu:
