### ISSUE TITLE
(my friend request) fix vgpu bug

### ISSUE THREAD

**Issue by SteveAlexM** [PojavLauncherTeam/PojavLauncher#1926]
### Describe the bug

shaders vgpu not working on one of my friend's cellphone

### The log file and images/videos

![FB_IMG_16302308880749344](https://user-images.githubusercontent.com/83632207/131246314-325e2d61-6c32-42b2-980e-adb4659015a5.jpg)

### Steps To Reproduce

```markdown
1. start pojav launcher 
2. select vgpu renderer 
3. select "play" 
4. wait for a moment 
5.C MOJANG 
6. select shaders 
7. shaders not working
```

### Expected Behavior

he hopes it gets fixed before the end of September

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: aarch 64
- Android version: 9
- PojavLauncher version: 3.3.1.1-1235-27e762544-v3_openjdk
```

**Comment by WesleyVanNeck** [comment]
were not a vgpu dev just like mesa and gl4es so its a big no

**Comment by SteveAlexM** [comment]
Oh ok

**Comment by WesleyVanNeck** [comment]
also only a one good shaderes work and that open4es

**Comment by SteveAlexM** [comment]
@LegacyGamerHD so it's not a vgpu problem, it's a gl4es problem

**Comment by CHECK-12345** [comment]
> @LegacyGamerHD so it's not a vgpu problem, it's a gl4es problem

You should use this: https://github.com/Open4Es/Open4Es-Exprimental

This is the open4es shaders experimental version that you could use with vgpu. I tried it and it works on sdm845 using vgpu.

**Comment by SteveAlexM** [comment]
@CHECK-1234  my friend has mediatek helio p35 processor
