### ISSUE TITLE
[BUG] Can't launch 1.17.1 Vanilla/1.17.1 Fabric

### ISSUE THREAD

**Issue by Metal-666** [PojavLauncherTeam/PojavLauncher#1928]
### Describe the bug

When I try to launch version 1.17.1 I get a black screen and a dialog saying "Game exited" with an OK button (clicking it returns me to launcher)
When I try to launch version fabric-loader-0.11.6-1.17.1 I get the same black screen but without any dialogs

### The log file and images/videos

When trying to launch 1.17.1
![image](https://user-images.githubusercontent.com/50769245/131251721-fe871c6d-8028-4ef7-a7d4-d3fba4d67df6.png)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7072557/latestlog.txt)
When trying to launch 1.17.1 Fabric
![image](https://user-images.githubusercontent.com/50769245/131251735-c071523d-215a-4b09-82c9-a96b27b66c2a.png)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7072561/latestlog.2.txt)

### Steps To Reproduce

```markdown
Vanilla:
1. Install and launch PojavLauncher (from Google Play)
2. Select 1.17.1 in versions list
3. Hit Play
4. Observe the error
Fabric:
1. Install and launch PojavLauncher (from Google Play)
2. Follow all instructions on this wiki page (https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Install-Fabric) except the second one in "Preparing and setup" (the link is broken)
3. Observe the error
```

### Expected Behavior

Successful Minecraft launch (both Vanilla and Fabric versions)

### Platform

```markdown
- Device model: POCO F3 8/256G
- CPU architecture: ARM 64bit (that's what google told me)
- Android version: 11 (MIUI 12.5.2)
- PojavLauncher version: 3.3.1.1_rel_20210321 (from Google Play)
```

### Anything else?

Older versions 1.16.5 and 1.14 are working fine
I saw a wiki page about fixing something in 1.17+, but I wasn't able to follow the steps (the latest build is marked as "expired", I can't download it)
The second log file that I attached mentioned something about Java 8 and 16, and coincidentally I had issues running Fabric 1.17.1 on PC with Java 8, and updating to Java 16 fixed them

**Comment by khanhduytran0** [comment]
> The second log file that I attached mentioned something about Java 8 and 16, and coincidentally I had issues running Fabric 1.17.1 on PC with Java 8, and updating to Java 16 fixed them

So, I see your attempt to run 1.17 on Java 8.

**Comment by khanhduytran0** [comment]
The latest build is available at "Actions" tab.![image](https://user-images.githubusercontent.com/40482367/131252622-489c30b4-4a8c-4128-99ec-854d406b9330.jpeg)

**Comment by Metal-666** [comment]
Okay, I downloaded and installed the latest build
I see an option in settings to "manage installed Java VMs"
But where do I download a Java 16 VM for Android?

**Comment by khanhduytran0** [comment]
We only ported Java 17 instead of 16, it can be downloaded [here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/suites/3589896095/artifacts/86459862).

**Comment by Metal-666** [comment]
Yep, that worked, thank you
