### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by TheSafeBoi** [PojavLauncherTeam/PojavLauncher#1933]
### Describe the bug

I wanted to play Minecraft with forge and create mod. Create mod requires flywheel and so i put the create mod and flywheel jar into mods folder. When i push the start button play Minecraft (1.16.5 w forge mod) it didn't crash but when it finished loading it crashed

### Steps To Reproduce

```markdown
1. Load PojavLauncher
2. Download the 1.16.5 Forge mod jar and install the mod
3. Download the 1.16.5 Create mod and the 1.16 flywheel mod and put the 2 mods into the mods folder
4. Choose version as 1.16.5 Forge
5. Push start button
```

### Expected Behavior

I expected it to not crash

### Platform

```markdown
- Device model: Redmi 9a 32Gb
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: 3.3.1.1
```

**Comment by NotAHero04** [comment]
Create doesn’t work with PojavLauncher.
