### ISSUE TITLE
Modify java 8 to 16

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1936]
### Describe the request.

I dont really know how this does work, but as i can see the app debug (not the norruntime) uses java 8 instead of 16, should be nice to dont need to install another jre.

### Anything else?

No

**Comment by WesleyVanNeck** [comment]
Not gone happen

**Comment by WesleyVanNeck** [comment]
For now at least

**Comment by OEMunlag** [comment]
Ok thanks for that fast answer, im new to this, i have to close this, and how i do that?
