### ISSUE TITLE
[F-Req] IPA File

### ISSUE THREAD

**Issue by TheBalkanDev** [PojavLauncherTeam/PojavLauncher#1937]
### Is this request related to a bug?

No

### Describe the request.

Can you please offer an .ipa file?
Because for the newer iOS Versions (14.5-14.7.1) there are no Jailbreaks.
It would be nice, users can Install it without Jailbreaking trough AltStore.

### Anything else?

No

**Comment by artdeell** [comment]
Pojav is made as a JB-only thing for a reason

Also, this is the android repository

**Comment by ghost** [comment]
[ios repo](https://github.com/PojavLauncherTeam/PojavLauncher_iOS)
