### ISSUE TITLE
[F-Req] Free floating drawer

### ISSUE THREAD

**Issue by Zelioz273** [PojavLauncherTeam/PojavLauncher#1938]
### Is this request related to a bug?

The drawer button allows you to hide buttons inside of it, but you can't change where these buttons are, you're limited to up/down/left/right, without any option for padding. This makes it weird to use to hide any buttons that you want in a specific places, like how i have my 1-9 buttons in a zig zag on the top right.

### Describe the request.

I suggest there should be a fifth option for orientation, or an option that you can tick with disables orientation. This option would allow the hidden buttons to be anywhere on screen, which would even allow you to hide random buttons on the screen that you can't group right next to eachother. 

### Anything else?

This might be too much to add or ask but maybe even add an option that makes the drawer switch from toggling a couple buttons off/on, to toggling between two different groups of buttons. This isn't completely needed but wondering if that could be added or not. I just thought of this while messing around with the drawer button.

**Comment by khanhduytran0** [comment]
~~Did you mean grid buttons?~~

**Comment by Zelioz273** [comment]
Oh i haven't been keeping up with the updates, i only recently checked the latest and tested stuff out. Was that something that was a feature but removed or something that's going to be added? And how did that work?

**Comment by Mathias-Boulay** [comment]
I could add a free placement "orientation" but it may be the start of chaos if I do this
I'm already scared by the creations of some members from the discord server

**Comment by Zelioz273** [comment]
How bad would that chaos be? No clue as to what they've made

**Comment by pojavluncher2021** [comment]
Heh!, Can you add a additional forge and optifine version so it can fix lag

**Comment by Zelioz273** [comment]
Oh right. I didn't add that you can't even change the button sizes, with the current button drawer, it's really constricted. And it's on them if they create something weird that lags their own game right? Or is it something else you're scared of?

**Comment by netkv** [comment]
> How bad would that chaos be? No clue as to what they've made

for example
https://media.discordapp.net/attachments/779322558339088384/881521399435509790/Screenshot_20210829-194707_PojavLauncher_Minecraft_Java_Edition_for_Android.jpg?

**Comment by Mathias-Boulay** [comment]
http://twitter.com/PLaunchTeam/status/1434930538176040970
