### ISSUE TITLE
Version 1.17.1 not downloading or launching

### ISSUE THREAD

**Issue by arnavarote** [PojavLauncherTeam/PojavLauncher#1939]
### Describe the bug

No Compatible Java Runtime?

### The log file and images/videos

-

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select version 1.17.1
3. Attempt to download 1.17.1
4. Error will appear (see screenshot for error)
```

### Expected Behavior

I expected the launcher to download and launch 1.17.1

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

![128877873-919f1e0e-8dc5-45a0-8242-89b560cbc023](https://user-images.githubusercontent.com/88587545/131455162-f161ed15-159e-4267-8fed-79287af4155d.jpg)

**Comment by NotAHero04** [comment]
I see your attempt to run 1.17.1 on Java 8.
Meanwhile, its requirement has been changed to Java 16.
