### ISSUE TITLE
[BUG] Connected Account Error 403

### ISSUE THREAD

**Issue by arnavarote** [PojavLauncherTeam/PojavLauncher#1940]
### Describe the bug

When I Clicked On Keep Me Logged In It Always Show the Error

### Steps To Reproduce

```markdown
Steps To Reproduce
1. Start PojavLauncher
2. Make Account
3. Select Keep Me Logged In
4. Error will appear (see screenshot for error)
```

### Expected Behavior

PLS FIX THIS ERROR 
AFTER 30 AUGUST 2021 UPDATE ALSO ITS SHOWING THAT ERROR 403

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

![Screenshot (376)](https://user-images.githubusercontent.com/88587545/131456512-c455b25b-2bf3-44ae-bbbb-bcef8a7e5e01.png)

**Comment by arnavarote** [comment]
ERROR SCREENSHOT 

![Screenshot (376)](https://user-images.githubusercontent.com/88587545/131456452-32ee6926-5457-4553-be62-5d09824e5c52.png)

**Comment by khanhduytran0** [comment]
So you logged in on other devices?

**Comment by khanhduytran0** [comment]
bruh

**Comment by arnavarote** [comment]
What Are You Saying?

**Comment by arnavarote** [comment]
ITS SHOWING THAT ERROR
I WANT TO PLAY IN SERVER LIKE HYPIXEL AND OTHERS

**Comment by arnavarote** [comment]
REPLY ME!! khanhduytran0

**Comment by khanhduytran0** [comment]
> REPLY ME!! khanhduytran0

I’m not a robot that can instant reply, OK?

**Comment by khanhduytran0** [comment]
What account generator are you using?

**Comment by arnavarote** [comment]
I Am Not Using Any Account Generator

**Comment by khanhduytran0** [comment]
Your attitude make me think that you don’t have enough money to buy the game.

**Comment by arnavarote** [comment]
Once I Tried But Account Generator Its Showing That error too!!

**Comment by arnavarote** [comment]
> > REPLY ME!! khanhduytran0
> 
> I’m not a robot that can instant reply, OK?

Ya Ok

**Comment by khanhduytran0** [comment]
Because why? It **logged out**. Access Tokens are NOT permanent.

**Comment by arnavarote** [comment]
> Your attitude make me think that you don’t have enough money to buy the game.

Why Should I Buy It?

**Comment by khanhduytran0** [comment]
Reason of logged out?
- you logged in on other devices

**Comment by khanhduytran0** [comment]
> > Your attitude make me think that you don’t have enough money to buy the game.
> 
> Why Should I Buy It?

So, why are you expecting to be able to play premium servers?

**Comment by arnavarote** [comment]
> > > Your attitude make me think that you don’t have enough money to buy the game.
> > 
> > 
> > Why Should I Buy It?
> 
> So, why are you expecting to be able to play premium servers?

Means I Had To Buy It Then I Can Make Connected Account?

**Comment by arnavarote** [comment]
??

**Comment by khanhduytran0** [comment]
Buy Minecraft with price of $26.95.

**Comment by khanhduytran0** [comment]
Don’t buy account.

**Comment by arnavarote** [comment]
> Buy Minecraft with price of $26.95.

Okay I Will See It Later
There Is No Way That I Can make connected account for pojav launcher?

**Comment by arnavarote** [comment]
other way

**Comment by khanhduytran0** [comment]
One way: buy the game.

**Comment by InfiniXDerg** [comment]
lol

**Comment by arnavarote** [comment]
> One way: buy the game.

Okay Thanks For Your Help
Can You Tell Me That Why Its Showing This Error And How To Fix It
![128877873-919f1e0e-8dc5-45a0-8242-89b560cbc023](https://user-images.githubusercontent.com/88587545/131458723-5f083304-5557-4026-8258-a38d3977da06.jpg)

**Comment by arnavarote** [comment]
> lol

What lol?

**Comment by khanhduytran0** [comment]
> > One way: buy the game.
> 
> Okay Thanks For Your Help
> Can You Tell Me That Why Its Showing This Error And How To Fix It
> ![128877873-919f1e0e-8dc5-45a0-8242-89b560cbc023](https://user-images.githubusercontent.com/88587545/131458723-5f083304-5557-4026-8258-a38d3977da06.jpg)

Install java 17

**Comment by arnavarote** [comment]
> > > One way: buy the game.
> > 
> > 
> > Okay Thanks For Your Help
> > Can You Tell Me That Why Its Showing This Error And How To Fix It
> > ![128877873-919f1e0e-8dc5-45a0-8242-89b560cbc023](https://user-images.githubusercontent.com/88587545/131458723-5f083304-5557-4026-8258-a38d3977da06.jpg)
> 
> Install java 17

How?

**Comment by arnavarote** [comment]
Give Me Link

**Comment by InfiniXDerg** [comment]
Now go to download **ANY** executable in **TAR.XZ** then put runtime into configuración

**Comment by khanhduytran0** [comment]
> Give Me Link

https://nightly.link/PojavLauncherTeam/android-openjdk-build-multiarch/workflows/build/buildjre16/jre17-aarch64.zip

**Comment by khanhduytran0** [comment]
32bit is not supported at the moment.
Move to #1939

**Comment by arnavarote** [comment]
> 32bit is not supported at the moment.
> Move to #1939

Mine Is 64 bit
how to install it means same process know

**Comment by khanhduytran0** [comment]
> Now go to download **ANY** executable in **TAR.XZ** then put runtime into configuración

**Comment by arnavarote** [comment]
Ok I Understand Thanks

**Comment by arnavarote** [comment]
It Will 100% Fix This Error?

**Comment by arnavarote** [comment]
Bye Thanks
:)
