### ISSUE TITLE
[BUG] <Cant update>

### ISSUE THREAD

**Issue by lentas1** [PojavLauncherTeam/PojavLauncher#1942]
### Describe the bug

Cant update (device is lenovo tab m10 fhd plus)

### Steps To Reproduce

```markdown
1: i go to google play
2: i searched pojavlauncher
3: i clicked "update"
4: it says "installation failed"
```

### Expected Behavior

WHen i try install it on google play, it says "install failed"

### Platform

```markdown
- Device model: Lenovo tab m10 fhd plus
- CPU architecture: Arm64
- Android version: 10
- PojavLauncher version: 3.3.1.1-1141-a89b77c13-v3_openjdk by tran khanh duy
```

**Comment by Mathias-Boulay** [comment]
Uninstall the app, then re-install
Gplay and github aren't compatible between each other

**Comment by lentas1** [comment]
i tired and still not work

**Comment by lentas1** [comment]
tried

**Comment by Mathias-Boulay** [comment]
Maybe your device doesn't meet the requirements then, or corrupted download 🤔
