### ISSUE TITLE
Mouse not Showing/working [BUG]

### ISSUE THREAD

**Issue by Deckedgamer23** [PojavLauncherTeam/PojavLauncher#1943]
### Describe the bug

I can get in to the launcher and load up minecraft just fine but as soon as i join a world or server mouse just goes away and i cant move screen I will show you in this video

This is on a Chromebook and Arch 64 

### The log file and images/videos

https://user-images.githubusercontent.com/80975495/131520756-8b666866-12e9-405b-a0bc-11240fb20cb7.mp4

### Steps To Reproduce

```markdown
just get into mine craft and play on a world/server on pc
```

### Expected Behavior

The mouse will not work.

### Platform

```markdown
- Device model: lenovo N23 yoga chromebook
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by ALIGAMINGXII** [comment]
Same

**Comment by Mathias-Boulay** [comment]
Fixed with the latest update, thanks for reporting
