### ISSUE TITLE
can no longer play realms after account migration

### ISSUE THREAD

**Issue by Soarope** [PojavLauncherTeam/PojavLauncher#1946]
### Describe the bug

I was able to play realms using my mojang account. After the account migration I can log in to the game but when I try to play realms it says "invalid session, please try restarting minecraft".

### The log file and images/videos

![Screenshot_20210901-190334_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/89455994/131660758-4bf28d88-f793-4779-a627-8b9703decb6d.jpg)

### Steps To Reproduce

```markdown
After account migration
1. Start pojavlauncher
2. Log in with microsoft account
3. Select realms
```

### Expected Behavior

I expect seeing a list of worlds on different servers I can enter and play with friends

### Platform

```markdown
- Device model: Samsung Galaxy A42 5G (SM-A426B/DS)
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: v3.3.1.1-1833-9680ba11b-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
DUPLICATE FROM #965 
CLOSING
*seems like I forgot the all caps*
