### ISSUE TITLE
[BUG] No JRE9/8 runtime for crocus gplay build.

### ISSUE THREAD

**Issue by pojavluncher2021** [PojavLauncherTeam/PojavLauncher#1947]
### Describe the bug

No compatible java runtime for 1.17.1, JRE17 runtime didn't work on non main builds, What will I do, Please make another JRE9 runtime

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Wait for it to unpack the runtime
And boom, No JRE9/8 runtime compatible
```

### Expected Behavior

I expect that it could be because JRE8 is outdated

### Platform

```markdown
- Device model: Redmi 9C
- CPU architecture: armv8 rev4 I believe
- Android version: 10
- PojavLauncher version: crocusgplay v3 openjdk
```

### Anything else?

None

**Comment by pojavluncher2021** [comment]
Hey!, This issue is on crocus gplay bruh, Stop closing this issue. This is
regarding JRE8 lock, I can't play any version it says: "Can't find any
compatible java runtime" God dammit

**Comment by Mathias-Boulay** [comment]
Oops my bad I closed the wrong one 😂 
I'm deduplicating issues rn
But you just need to download java 17 from github and install it.

**Comment by pojavluncher2021** [comment]
It's okay Mathias, I'll download JRE17 maybe soon, but I love your
deduplication of issues, Can I do it too?

**Comment by CriticalRange** [comment]
You wanna help him deduplicate the issues ? Join the discord server and join us the hunt :D (it will be Monday probably)

**Comment by pojavluncher2021** [comment]
Sorry :(, I wanna be a contributor instead

**Comment by khanhduytran0** [comment]
> It's okay Mathias, I'll download JRE17 maybe soon, but I love your deduplication of issues, Can I do it too?

You love deduplicating meanwhile you was duplicating. :trollface:
