### ISSUE TITLE
1.17+optifine crash

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#1952]
### Describe the bug

Game exit

### Steps To Reproduce

```markdown
1open mod installer
2select optifine 1.17.1
3some logs and game exit
```

### Expected Behavior

I expect to play Minecraft with optifine

### Platform

```markdown
- Device model: Samsung galaxy m31
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: pojavlauncher v3.3.1.1-1145-44a3d03ce-v3_openjdk
```

**Comment by artdeell** [comment]
1. OptiFine 1.17.1 kinda doesn't work
2. Your launcher version: v3.3.1.1-1145-44a3d03ce
Latest: crocus-v3_openjdk

Your launcher is outdated

**Comment by ajit850** [comment]
Which version support optifine 1.17.1

**Comment by CriticalRange** [comment]
There are none, for Android at least
Not sure about iOS
