### ISSUE TITLE
[BUG] I don't know how to solve this or what it is

### ISSUE THREAD

**Issue by Haribo-shiba** [PojavLauncherTeam/PojavLauncher#1953]
### Describe the bug

I can't download forge for my Pojavlauncher. I'm playing on my chromebook, but everytime I try to download forge from the app, it says "read:unexpected E0F". 

### The log file and images/videos

![Screenshot 2021-09-01 11 35 13 PM](https://user-images.githubusercontent.com/88736481/131690782-e86c5233-dd0e-443a-b36a-afd33dda5807.png)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Press Options
3. Press "Launch a mode installer"
4. Launch the recommended version for 1.12.2 Forge (If you downloaded it)
5. Launch it
```

### Expected Behavior

I expected it to be launched properly and forge getting downloaded.

### Platform

```markdown
- Device model: Acer Chromebook CP311 2H Series
- CPU architecture: Intel Inside (Don't know specifically)
- Android version: Chrome OS: 92.0.4515.162 Version - 64 bit
- PojavLauncher version: Highest Version in Google Play Store (Don't know specifically)
```

**Comment by Mathias-Boulay** [comment]
You can just press X and continue the install 😄
