### ISSUE TITLE
[F-Req] Allow Microsoft account under 18 able to login in without parent account?

### ISSUE THREAD

**Issue by TWTommyee** [PojavLauncherTeam/PojavLauncher#1954]
### Describe the request.

Cuz it want me to add a parent account to let me login
But i am already 16 and 7yrs old child won't even able to login themselves so there is no need to prevent them from logging in
No offend

**Comment by WesleyVanNeck** [comment]
tell microsoft that

**Comment by TWTommyee** [comment]
Lol ok
