### ISSUE TITLE
[Bug]Can't login

### ISSUE THREAD

**Issue by sajwin-code** [PojavLauncherTeam/PojavLauncher#1957]
### Describe the bug

Always showing error while trying to login or signup using ms account

### Steps To Reproduce

```markdown
1. START pojav launcher
2. Login
```

### Expected Behavior

I expect to login

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by WesleyVanNeck** [comment]
Did you buy Minecraft java

**Comment by WesleyVanNeck** [comment]
If not you can't login with a bedrock account or demo

**Comment by Mathias-Boulay** [comment]
Fill the template or be terminated

**Comment by khanhduytran0** [comment]
@SSJ12 You have a Microsoft account doesn't mean you have Minecraft Java **premium** for free.

**Comment by khanhduytran0** [comment]
If you have already bought the game, check if you're under 18? if so, link to your parent account.
