### ISSUE TITLE
Can't play 1.17+

### ISSUE THREAD

**Issue by sajwin-code** [PojavLauncherTeam/PojavLauncher#1958]
### Describe the bug

Couldn't find any compatible java runtime

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Select v1.17+
3. click play
```

### Expected Behavior

I expect game to open

### Platform

```markdown
- Device model: Realme 6
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by WesleyVanNeck** [comment]
Known issue

**Comment by sajwin-code** [comment]
How to fix it

> Known issue

**Comment by WesleyVanNeck** [comment]
> How to fix it
> 
> > Known issue

installing the java 17 runtime

**Comment by WesleyVanNeck** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/1165988189

**Comment by KonozDOD** [comment]
> https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/1165988189

How guide on how too ?
