### ISSUE TITLE
Không thể chơi được  pojavlauncher

### ISSUE THREAD

**Issue by Dai2k9hihipro** [PojavLauncherTeam/PojavLauncher#1959]
### Describe the bug

Tôi đang vào  gam như  ko được  bị màn hình  tối  rồi  quay lại  hình  nền pojavlauncher

### Steps To Reproduce

```markdown
1 Vào  pojavlaucher 
2 khởi động  một phiên bản  kì  (Minecraft)
3quay về  màn hình  nền  pojavlaucher
```

### Expected Behavior

Mong nhà  phát triển xửa lỗi

### Platform

```markdown
- Device model: Ohio A37f
- CPU architecture: 32
- Android version: 5.1.1
- PojavLauncher version:3.3.1.1 (chplay)
```

### Anything else?

Ko

**Comment by Dai2k9hihipro** [comment]
https://youtu.be/PB_qAQic0Vw

**Comment by Mathias-Boulay** [comment]
old launcher version, unsupported.
If it happens with the current play update (crocus) make a new issue and fill the template properly.
