### ISSUE TITLE
Very big bug! Secret versions?

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#196]
I found this versions while testing PojavLauncher on VMOS!
![Screenshot_20200511_160622_com vmos web](https://user-images.githubusercontent.com/62551802/81571164-e0dfc300-93a1-11ea-856b-2276fed34fe3.jpg)
![Screenshot_20200511_160636_com vmos web](https://user-images.githubusercontent.com/62551802/81571189-e63d0d80-93a1-11ea-812c-52e4c0f94ec8.jpg)
![Screenshot_20200511_160915_com vmos web](https://user-images.githubusercontent.com/62551802/81571203-e9d09480-93a1-11ea-81e9-96758e1129c0.jpg)
Look at the User nickname!
[Last screenshot: testing without internet]
PS. I can't play. :(

**Comment by khanhduytran0** [comment]
> I found this versions while testing PojavLauncher on VMOS!
> ![Screenshot_20200511_160622_com vmos web](https://user-images.githubusercontent.com/62551802/81571164-e0dfc300-93a1-11ea-856b-2276fed34fe3.jpg)
> ![Screenshot_20200511_160636_com vmos web](https://user-images.githubusercontent.com/62551802/81571189-e63d0d80-93a1-11ea-812c-52e4c0f94ec8.jpg)

It's error, not versions!!!!

> ![Screenshot_20200511_160915_com vmos web](https://user-images.githubusercontent.com/62551802/81571203-e9d09480-93a1-11ea-81e9-96758e1129c0.jpg)
> Look at the User nickname!
> [Last screenshot: testing without internet]
> PS. I can't play. :(

```
The webpage ... could not be loaded because...
```
This means you are offline.

**Comment by khanhduytran0** [comment]
Try latest preview?

**Comment by Azapru** [comment]
Ok

**Comment by khanhduytran0** [comment]
> Ok
