### ISSUE TITLE
[BUG] FORGE CRASH

### ISSUE THREAD

**Issue by sevenzn** [PojavLauncherTeam/PojavLauncher#1960]
### Describe the bug

FORGE 1.7.10 CRASHES WHEN IT STARTS

### Steps To Reproduce

```markdown
1. STARTING LAUNCHER... ( START VERSION FORGE 1.7.10 )
```

### Expected Behavior

START GAME

### Platform

```markdown
- DEVICE MODEL: REDMI NOTE 8 / 64G
- CPU ARCHITECTURE: AARCH64
- AANDROID VERSION: 10
- POJAVLAUNCHER VERSION: VERSION 3.3.1.1_REL_20210206
```

### Anything else?

ANY MOD CRASHES, EXCEPT OPTFINE

**Comment by Mathias-Boulay** [comment]
old version, unsupported.
If it happens with the newer launcher version, make a new issue and fill the template properly.
