### ISSUE TITLE
Add skin Change Option

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#1961]
### Is this request related to a bug?

You should add skin Change Option because some players want to change there skin

### Describe the request.

Add skin edit or download option

**Comment by GamerYTofficial** [comment]
I agree!...

**Comment by RangCraft** [comment]
I agree!!!

**Comment by WesleyVanNeck** [comment]
Use minecraft.net to change your skin

**Comment by ajit850** [comment]
How to get skin from Minecraft.net

**Comment by netkv** [comment]
use brain, minecraft.net, login → profile → change skin somewhere is

**Comment by itzgreenhaha** [comment]
But what if your account is cracked?

**Comment by khanhduytran0** [comment]
![<:frpirate:871497846686355458>](https://cdn.discordapp.com/emojis/871497846686355458.png)

**Comment by khanhduytran0** [comment]
first, it's piracy
second, there's no way to inject skin for offline/cracked account
