### ISSUE TITLE
[64 bits only] ONLY VANILLA (and optifine) 1.17.X WORK

### ISSUE THREAD

**Issue by elyesgmzboi** [PojavLauncherTeam/PojavLauncher#1963]
so i followed a tutorial on youtube of how to play 1.17 in pojavlauncher, it worked on vanilla but, it didn't work when i use the optifine version of 1.17

and here's the screenshot
![Screenshot_20210903-143338.png](https://user-images.githubusercontent.com/72686414/132014116-d31045fe-f747-4b9a-a13d-c4b0827cba87.png)

(sorry if the image is sideways, i cannot fix it)

**Comment by CriticalRange** [comment]
Afaik optifine 1.17.1 doesn't work

**Comment by Mathias-Boulay** [comment]
Indeed, we never said optifine 1.17 worked.

**Comment by GamerYTofficial** [comment]
Will it Be fixed? Now?

**Comment by GamerYTofficial** [comment]
> Indeed, we never said optifine 1.17 worked.

Will it Be fixed? Now?

**Comment by orocraftHub** [comment]
Crashed on 1.17.1 on optifine pls fix

**Comment by WesleyVanNeck** [comment]
> Crashed on 1.17.1 on optifine pls fix

plz fix your self

**Comment by InfiniXDerg** [comment]
Use optifine 1.16.5 (lol)

**Comment by khanhduytran0** [comment]
See [this](https://pojavlauncherteam.github.io/updates/117.html#optifine) for OptiFine.
