### ISSUE TITLE
[BUG] <downloaded all versions crashed>

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#1964]
### Describe the bug

I install pojavlauncher lastest build from action but if i download 1.17,1.17.10(all version) keep crashing when start game 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7106300/latestlog.txt)

### Steps To Reproduce

```markdown
1.download versions with assets
2.start game and then crash and put me on main menu of pojavlauncher
```

### Expected Behavior

I use artdeel update egl_bridge.c from action build

### Platform

```markdown
- Device model: samsung m21
- CPU architecture: arrch 64
- Android version: 11
- PojavLauncher version: 3.3.1.1 dl-everything
```

### Anything else?

Plz fix this i never experience this on old versions of pojav

**Comment by artdeell** [comment]
dl-everything builds are for developer debugging, not for practical usage

**Comment by Ewjjai** [comment]
So what should i do now?  Get older?
