### ISSUE TITLE
[BUG] I can't get into any version with a build released at a time 

### ISSUE THREAD

**Issue by Pgabrielmnecraft** [PojavLauncherTeam/PojavLauncher#1965]
### Describe the bug

I can't get into any version in the first dl-everything build, I don't know how to solve it, I downgraded 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7106822/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojav 
2. Run an aleatory version
3. Bug
```

### Expected Behavior

1. Start pojav
2. Run an aleatory version
3. Work

### Platform

```markdown
- Device model: Samsung a31 / 128gb
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: first dl-everything build
```

### Anything else?

No

**Comment by Mathias-Boulay** [comment]
not main branch
