### ISSUE TITLE
1.17 doesnt load includes fabric and forge

### ISSUE THREAD

**Issue by Debob54** [PojavLauncherTeam/PojavLauncher#1967]
### Describe the bug

Can't find any compatible runtime 

### The log file and images/videos

![Screenshot_20210903-164421_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86144916/132052620-fb986555-dac4-4a51-b75e-cfbe7babab33.jpg)

### Steps To Reproduce

```markdown
Don't know
```

### Expected Behavior

I expect it to load

### Platform

```markdown
No
```

**Comment by NotAHero04** [comment]
Grab the latest Java 17 build [here.](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions)
Be sure to check your phone’s architecture before downloading.
Then unzip the file, back to the launcher and add the runtime.

**Comment by Debob54** [comment]
Thanks

**Comment by Mathias-Boulay** [comment]
Since the solution has been said, time for closing
