### ISSUE TITLE
I know its spamming but plz read its important  

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#1968]
### Describe the bug

I heard about arch hacked many many most famous accounts on famous games like FNAF and FNF.  But he killed gamebanana (friday night funkin) official game and Scott chawton account in gamejolt (aka five nights at freddys creator)
Stay alert if you have gamejolt, gamebanana accounts. 

Probarly he try to do in this github     

### Steps To Reproduce

```markdown
.....
```

### Expected Behavior

Do not download anything from these websites due to unsafe

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Stay alert

**Comment by GamerYTofficial** [comment]
I not understand?

**Comment by GamerYTofficial** [comment]
> ### Describe the bug
> I heard about arch hacked many many most famous accounts on famous games like FNAF and FNF. But he killed gamebanana (friday night funkin) official game and Scott chawton account in gamejolt (aka five nights at freddys creator)
> Stay alert if you have gamejolt, gamebanana accounts.
> 
> Probarly he try to do in this github
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> .....
> ```
> 
> ### Expected Behavior
> Do not download anything from these websites due to unsafe
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:
> ```
> 
> ### Anything else?
> Stay alert

I not understand?

**Comment by wackycreeper** [comment]
> ### Describe the bug
> I heard about arch hacked many many most famous accounts on famous games like FNAF and FNF. But he killed gamebanana (friday night funkin) official game and Scott chawton account in gamejolt (aka five nights at freddys creator)
> Stay alert if you have gamejolt, gamebanana accounts.
> 
> Probarly he try to do in this github
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> .....
> ```
> 
> ### Expected Behavior
> Do not download anything from these websites due to unsafe
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:
> ```
> 
> ### Anything else?
> Stay alert

I don't understand. Who is arch and what is his relation to this website?

**Comment by Ewjjai** [comment]
> > ### Describe the bug
> > I heard about arch hacked many many most famous accounts on famous games like FNAF and FNF. But he killed gamebanana (friday night funkin) official game and Scott chawton account in gamejolt (aka five nights at freddys creator)
> > Stay alert if you have gamejolt, gamebanana accounts.
> > Probarly he try to do in this github
> > ### The log file and images/videos
> > _No response_
> > ### Steps To Reproduce
> > ```
> > .....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > Do not download anything from these websites due to unsafe
> > ### Platform
> > ```
> > - Device model: 
> > - CPU architecture: 
> > - Android version: 
> > - PojavLauncher version:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > Stay alert
> 
> I don't understand. Who is arch and what is his relation to this website



Arch is famous hacker.  He can hack gamejolt,gamebananas,github accounts in a minute and bank card's money too and he gives virus in all package.  I hope github has safe security
