### ISSUE TITLE
Dynamic sarounding mod bug

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1969]
### Describe the bug

Dynamic sarounding mod have white texture 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1.use the mods
2.start a game
3.create a world
4.white texture everything
```

### Expected Behavior

I expected to work properly

### Platform

```markdown
- Device model: mi 9t pro
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest in action github
```

### Anything else?

Anyone know how to fix this white texture in dynamic sarounding mod

**Comment by Mathias-Boulay** [comment]
#1948
