### ISSUE TITLE
[BUG] Microsoft account cant login on

### ISSUE THREAD

**Issue by nanash1miraa** [PojavLauncherTeam/PojavLauncher#1970]
### Describe the bug

I touch the Microsoft account login
And  login.live.com is broken

### Steps To Reproduce

```markdown
Open pojavlauncher
Touch Microsoft account login
Cant connect login.live.con
```

### Expected Behavior

I wish can login pls

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

I know I'm bad at english

**Comment by nanash1miraa** [comment]
Oh btw is solved
But it  always go the original version
Instead debug(i login with debug version)

**Comment by Mathias-Boulay** [comment]
If it solved, close the issue 😂

**Comment by nanash1miraa** [comment]
> 如果解決了，關閉問題 😂

No longer login
