### ISSUE TITLE
Sampler2 program

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#1972]
### Is this request related to a bug?

You should add Sampler0 named specific program in asset pack

### Describe the request.

Sampler2 program for outline

**Comment by Mathias-Boulay** [comment]
What does this mean in proper English ?

**Comment by ajit850** [comment]
There is no Sampler2 named program

**Comment by Mathias-Boulay** [comment]
But what is this program or where should we find it ?
We aren't mind readers

**Comment by ajit850** [comment]
This program is not in asset pack this cause there is no outline

**Comment by ajit850** [comment]
Open render_text_intensity.json,FSH,vsh

**Comment by ajit850** [comment]
[05:35:37] [Render thread/WARN]: Shader rendertype_text could not find sampler named Sampler2 in the specified shader program.
[05:35:37] [Render thread/WARN]: Shader rendertype_text_intensity could not find sampler named Sampler2 in the specified shader program
This is my log

**Comment by NotAHero04** [comment]
I can find Sampler2 in rendertype_text_intensity.vsh and rendertype_text.vsh. Not sure where the problem is.

**Comment by artdeell** [comment]
@ajit850 First of all, these samplers were removed because they are practically useless during their use
Second of all, lines are not available because GLESv2 does not allow vertex indexing, not because of a missing sampler

**Comment by ajit850** [comment]
What I do to get outline

**Comment by ajit850** [comment]
When outline will come in game

**Comment by artdeell** [comment]
On the texture pack: never

**Comment by ajit850** [comment]
Default texture pack ?

**Comment by ajit850** [comment]
What is error occurred by sampler
