### ISSUE TITLE
[BUG] <no find . Minecraft folder

### ISSUE THREAD

**Issue by Greeiden** [PojavLauncherTeam/PojavLauncher#1976]
### Describe the bug

Hi how The new update and changes folder for this app, and new rute in Android/etc...in My device not Samsung A21s not found in. And not install mod's for this.

### Steps To Reproduce

```markdown
Hi how The new update and changes folder for this app, and new rute in Android/etc...in My device not Samsung A21s not found in. And not install mod's for this.
```

### Expected Behavior

Hi how The new update and changes folder for this app, and new rute in Android/etc...in My device not Samsung A21s not found in. And not install mod's for this.

### Platform

```markdown
- Device model: A21s
- CPU architecture:aarch64
- Android version: 9
- PojavLauncher version: Last Udate
```

**Comment by CHECK-12345** [comment]
> ### Describe the bug
> Hi how The new update and changes folder for this app, and new rute in Android/etc...in My device not Samsung A21s not found in. And not install mod's for this.
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> Hi how The new update and changes folder for this app, and new rute in Android/etc...in My device not Samsung A21s not found in. And not install mod's for this.
> ```
> 
> ### Expected Behavior
> Hi how The new update and changes folder for this app, and new rute in Android/etc...in My device not Samsung A21s not found in. And not install mod's for this.
> 
> ### Platform
> ```gfm
> - Device model: A21s
> - CPU architecture:aarch64
> - Android version: 9
> - PojavLauncher version: Last Udate
> ```
> 
> ### Anything else?
> _No response_

The new directory is in /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug

I recommand using ZArchiver android app

**Comment by Mathias-Boulay** [comment]
That's not a bug, you just don't know how to use a file manager.
Activates "show hidden files"
