### ISSUE TITLE
[F-Req] Add game assets mirror download

### ISSUE THREAD

**Issue by fengyec2** [PojavLauncherTeam/PojavLauncher#1978]
### Is this request related to a bug?

Not a bug,just the game assets download speed too slow in China

### Describe the request.

Could pojav add game assets mirror download like "MCBBS" or "Bangbang 93" so that the download speed will be much faster in China

### Anything else?

no

**Comment by Mathias-Boulay** [comment]
Another fucking duplicate I see
I wish people could learn to read or even think sometimes.
#1573
