### ISSUE TITLE
[BUG] Microsoft account login will not going to debug version

### ISSUE THREAD

**Issue by nanash1miraa** [PojavLauncherTeam/PojavLauncher#1979]
### Describe the bug

Yesterday i login pojavlauncher (debug version)with my Microsoft account and it will not going to debug version it will going 
to the normal version

### Steps To Reproduce

```markdown
Launch pojavlauncher
Login with Microsoft account
Success login
But it always going normal version
```

### Expected Behavior

I wish i can launch my 1.17.1 version

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

My English bad

**Comment by ajit850** [comment]
Use asset v0 pack

**Comment by ajit850** [comment]
And 1.17 jre

**Comment by nanash1miraa** [comment]
Not debug version

**Comment by nanash1miraa** [comment]
> 使用資產 v0 包

It's automatically installed

**Comment by ajit850** [comment]
Please send Pojavlauncher version

**Comment by nanash1miraa** [comment]
> 請發送 Pojavlauncher 版本

Latest

**Comment by nanash1miraa** [comment]
Latest will automatically installed

**Comment by ajit850** [comment]
Play store version or GitHub version

**Comment by nanash1miraa** [comment]
> Play 商店版本或 GitHub 版本

All latest

**Comment by khanhduytran0** [comment]
Launcher version is not provided.

**Comment by khanhduytran0** [comment]
```
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```
empty

**Comment by nanash1miraa** [comment]
> ```
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:
> ```
> 
> 空的

Pixel 3a
CPU:i don't know
Android version:11
Pojavlauncher version:google play veraion

**Comment by Mathias-Boulay** [comment]
Ah yes GoOgLe PlAy VeRsIOn

**Comment by netkv** [comment]
i dont get if this is login issue or another copy of "1.17 no work pls fix"

**Comment by ajit850** [comment]
Can Google play version support 1.17

**Comment by nanash1miraa** [comment]
> 谷歌播放版能支持1.17嗎

No it can’t only debug version

**Comment by khanhduytran0** [comment]
~~What do you mean by debug here? This "debug" screen?~~
![image](https://user-images.githubusercontent.com/40482367/132128173-f30c3e96-11a5-4b4a-8a8c-cb8a9e98fdfd.png)

**Comment by CriticalRange** [comment]
> > 谷歌播放版能支持1.17嗎
> 
> No it can’t only debug version

Take a look at your PojavLauncher version.
Is it crocus-v3_openjdk ? If it is like that, i wanna say that i have not experienced any problem with opening 1.17 on that version
