### ISSUE TITLE
Invalid java app? 

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#198]
![Screenshot_20200512-143209](https://user-images.githubusercontent.com/63871578/81698270-a2a7d980-945d-11ea-9d2b-7b89a5f190a5.jpg)

**Comment by leetmussc** [comment]
How do I fix this?

**Comment by leetmussc** [comment]
3.0 preview 5

**Comment by khanhduytran0** [comment]
This is because v3 is unusable in Android 8 and above (not sure).

**Comment by khanhduytran0** [comment]
And VMOS will get a bit different error.

**Comment by khanhduytran0** [comment]
Use v3.2
