### ISSUE TITLE
[BUG] Microsoft account cant login(repost)

### ISSUE THREAD

**Issue by nanash1miraa** [PojavLauncherTeam/PojavLauncher#1980]
### Describe the bug

Unable to connect to this website, please check login.live.com for typos.
DNS_PROBE_FINISHED_NXDOMAIN

### The log file and images/videos

![Screenshot_2021-09-05-12-00-11](https://user-images.githubusercontent.com/87407875/132114761-f73280f7-1d20-4e5a-9449-70d0fa6a7d10.jpg)
Translate
Unable to connect to this website, please check login.live.com for typos.
DNS_PROBE_FINISHED_NXDOMAIN

### Steps To Reproduce

```markdown
launch pojavlauncher
Press use Microsoft account login
and this happens
```

### Expected Behavior

I wosh i can login

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No

**Comment by khanhduytran0** [comment]
Please don't mess up our issue tracker with duplicates! Use VPN to login.
