### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by BG6HMJ** [PojavLauncherTeam/PojavLauncher#1981]
### Describe the bug

无法安装forge

### Steps To Reproduce

```markdown
安装forge
```

### Expected Behavior

请尽快

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
Thanks for reporting, however the issue in **invalid and incomplete**. We don't know your device, android version, launcher version, even you language.

Possibility because you have only Java 17 installed. Install Java 8 before run the installer.

**Comment by khanhduytran0** [comment]
> We don't know your device, android version, launcher version, even you language.

Even no log is provided.
