### ISSUE TITLE
[BUG] Fix Texture Bug

### ISSUE THREAD

**Issue by Isan1736** [PojavLauncherTeam/PojavLauncher#1983]
### Describe the bug

Hit Mob Texture Error

### The log file and images/videos

![Screenshot_20210905_204823](https://user-images.githubusercontent.com/84948958/132130015-6666a241-1943-4cad-ae88-8734caa40d6c.jpg)

### Steps To Reproduce

```markdown
1.Start Pojav With 1.8-1.14
2.Play a world 
3.Hit a mob
4.then the texture was bug
```

### Expected Behavior

I don't use Any Texture Pack

### Platform

```markdown
- Device model:vivo 1814(y93) 3/32 mediatek helio P22
- CPU architecture:aarch64
- Android version:8
- PojavLauncher version: 
Latest Build
```

### Anything else?

Please fix this

**Comment by NotAHero04** [comment]
BRUH why making duplicates?

**Comment by Mathias-Boulay** [comment]
Pojav launcher version not stated.
Try setting the renderer to GLES 1.1.5

**Comment by NotAHero04** [comment]
Try every renderer until you find one that’s not buggy on your phone.
||Spoiler: gl4es 1.1.4.||
