### ISSUE TITLE
[BUG] The application / game crashed with code 1 when launching the Lunar Client

### ISSUE THREAD

**Issue by AN1KO** [PojavLauncherTeam/PojavLauncher#1984]
### Describe the bug

When launching the Lunar Client on a new assembly of PojavLauncher, the game crashes with the inscription "The application / game crashed with code 1" (sorry if there is a mistake somewhere, I don't speak English myself "

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: v3.3.1.1-1249-3db1eec99-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: "-Xms812m -Xmx1800m"
Info: Selected Minecraft version: LC
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch.debug-Yd21vEKisoUorBMy6yUhdw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_vgpu
Added custom env: LIBGL_ES=3_vgpu
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/jrelog  ( 1100): Going to free args
I/jrelog  ( 1100): Free done
I/jrelog  ( 6705): dlopen libxhook.so success
--------- beginning of system
I/LIBGL   ( 6705): Initialising vgpu gl4es
I/LIBGL   ( 6705): vgpu 1.3.6 gl4es 1.1.4 built on Aug 25 2021 09:26:59
I/LIBGL   ( 6705): Using GLES 3.0 backend
I/LIBGL   ( 6705): LIBGL:loaded: libGLESv3.so
I/LIBGL   ( 6705): loaded: libEGL.so
I/LIBGL   ( 6705): Using GLES 3.0 backend
I/LIBGL   ( 6705): 
I/LIBGL   ( 6705): ========
I/LIBGL   ( 6705): GL_EXTENSIONS is :
I/LIBGL   ( 6705): GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sampl
I/LIBGL   ( 6705): Hardware Full NPOT detected and used
I/LIBGL   ( 6705): FBO are in core, and so used
I/LIBGL   ( 6705): PointSprite are in core, and so used
I/LIBGL   ( 6705): CubeMap are in core, and so used
I/LIBGL   ( 6705): BlendColor is in core, and so used
I/LIBGL   ( 6705): Blend Substract is in core, and so used
I/LIBGL   ( 6705): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 6705): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 6705): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 6705): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 6705): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 6705): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 6705): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 6705): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 6705): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   ( 6705): Extension GL_OES_texture_float  detected and used
I/LIBGL   ( 6705): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   ( 6705): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 6705): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 6705): high precision float in fragment shader available and used
I/LIBGL   ( 6705): Max vertex attrib: 32
I/LIBGL   ( 6705): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 6705): Max texture size: 16384
I/LIBGL   ( 6705): Max Varying Vector: 31
I/LIBGL   ( 6705): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   ( 6705): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 6705): Max Anisotropic filtering: 16
I/LIBGL   ( 6705): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   ( 6705): Hardware vendor is Qualcomm
I/LIBGL   ( 6705): Hardware renderer is Adreno (TM) 618
I/LIBGL   ( 6705): GLSL 300 es supported
I/LIBGL   ( 6705): GLSL 310 es supported and used
I/LIBGL   ( 6705): GLSL 320 es supported and used
I/LIBGL   ( 6705): sRGB surface supported
I/LIBGL   ( 6705): EGLImage to Texture2D supported
I/LIBGL   ( 6705): EGLImage to RenderBuffer supported
I/LIBGL   ( 6705): ignore MipMap
I/LIBGL   ( 6705): Targeting OpenGL 3.0
I/LIBGL   ( 6705): NPOT texture handled in hardware
I/LIBGL   ( 6705): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 6705): try to use VBO
I/LIBGL   ( 6705): glX Will try to recycle EGL Surface
I/LIBGL   ( 6705): Current folder is:/
I/jrelog  ( 6705): dlopen libvgpu.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 6705): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 6705): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  ( 6705): dlopen /data/app/net.kdt.pojavlaunch.debug-Yd21vEKisoUorBMy6yUhdw==/lib/arm64/libopenal.so success
I/jrelog  ( 6705): Done processing args
I/jrelog  ( 6705): Found JLI lib
I/jrelog  ( 6705): Calling JLI_Launch
LUNARCLIENT_STATUS_INIT
[Bridge] Setting Bridge Implementation to lunar.da.IlllIIIIIlllllllIIIIIllIl
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" 
java.lang.ExceptionInInitializerError
	at lunar.ar.IlllIIIIIlllllllIIIIIllIl.<clinit>(Unknown Source)
	at net.minecraft.client.main.Main.redirect$zzg000$impl$main$parse(SourceFile:560)
	at net.minecraft.client.main.Main.main(SourceFile:53)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at lunar.aB.lIlIIIIIIlllIIIIIlIIIllIl.<init>(Unknown Source)
	at lunar.aB.lllIIIIlIIllIIllIIllIIIll.<init>(Unknown Source)
	at lunar.aB.lllIIIIlIIllIIllIIllIIIll.<clinit>(Unknown Source)
	... 3 more
Java Exit code: 1
I/jrelog  ( 6705): Going to free args
I/jrelog  ( 6705): Free done

### Steps To Reproduce

```markdown
1. Launching PojavLauncher
2. Selecting the version of the Lunar Client
3. Launching the game
```

### Expected Behavior

I expect the Lunar Client to start

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Mathias-Boulay** [comment]
Whaou, an old version of the launcher

**Comment by khanhduytran0** [comment]
Also, Java 17 is only used to play Minecraft 1.17+, if older Minecraft version, it must be vanilla.

**Comment by AN1KO** [comment]
Thanks

**Comment by H0wAway** [comment]
> 谢谢

How to solve ？
