### ISSUE TITLE
[BUG] Texture glitch

### ISSUE THREAD

**Issue by qni320** [PojavLauncherTeam/PojavLauncher#1985]
### Describe the bug

When I hit something, like a pig or a creeper, most of the textures like torches, grass, lanterns and flowers then a lot more. I've tried changing renderers and all of them have this issue.

### The log file and images/videos

![Screenshot_20210906-014408_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65363992/132143530-2eb7b886-73cc-4afb-a91a-69ec0c62923e.jpg)

### Steps To Reproduce

```markdown
1. Launch Minecraft
2. Join any game, singleplayer or multiplayer
3.Hit any entity like an animal or a mob
```

### Expected Behavior

I expected it to not become blacked out and be normal.

### Platform

```markdown
- Device model: Samsung Galaxy A71
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by wackycreeper** [comment]
known bug in gl4es 1.1.5, use 1.1.4

**Comment by qni320** [comment]
> known bug in gl4es 1.1.5, use 1.1.4

Yes, but in 1.1.4, this thing happens, which is why i preferably use the others ![Screenshot_20210906-045335_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/65363992/132149797-e872630e-a3a6-4999-ad5c-31f3e1577d40.jpg)

It's like every block is transparent

**Comment by Mathias-Boulay** [comment]
what about vgpu then ? @qni320

**Comment by qni320** [comment]
> what about vgpu then ? @qni320 

Same thing

**Comment by Mathias-Boulay** [comment]
Argh

**Comment by CidNotRyan** [comment]
I had that bug but its 1.8.9

**Comment by Neftalicruz** [comment]
Ami también me pasa pensé que solo era el único y resetie el teléfono y pensé que se arregló jugué bedwars en un server y se buguearon todas las texturas como si fueran 1×1 y los personajes oh skins se pusieron negras incluyendo la mia

**Comment by rscDMTalt** [comment]
> Ami también me pasa pensé que solo era el único y resetie el teléfono y pensé que se arregló jugué bedwars en un server y se buguearon todas las texturas como si fueran 1×1 y los personajes oh skins se pusieron negras incluyendo la mia

English only, please

**Comment by Neftalicruz** [comment]
JAJA xd Entonces escribe en inglés Bro

**Comment by GDHatdaug1992** [comment]
> > known bug in gl4es 1.1.5, use 1.1.4
> 
> Yes, but in 1.1.4, this thing happens, which is why i preferably use the others ![Screenshot_20210906-045335_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/65363992/132149797-e872630e-a3a6-4999-ad5c-31f3e1577d40.jpg)
> 
> It's like every block is transparent

I experienced the same, you have to turn on fast render

**Comment by Rahman661** [comment]
![Screenshot_2021-09-28-12-20-12-148_net kdt pojavlaunch](https://user-images.githubusercontent.com/90732933/135022828-0a21b694-e393-454a-9838-584040aa645d.jpg)

**Comment by OhCauXanh** [comment]
> ![Screenshot_2021-09-28-12-20-12-148_net kdt pojavlaunch](https://user-images.githubusercontent.com/90732933/135022828-0a21b694-e393-454a-9838-584040aa645d.jpg)

Use 1.1.4 gl4es

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
