### ISSUE TITLE
[BUG] Crashed when starting game

### ISSUE THREAD

**Issue by Adiixyz** [PojavLauncherTeam/PojavLauncher#1986]
### Describe the bug

Game crashed

### The log file and images/videos

![Screenshot_2021-09-06-09-14-45-36](https://user-images.githubusercontent.com/82200440/132147622-24f677e9-5dc6-402b-ba8d-ed234652c3a7.png)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Select Account
3. Select Version
4. Start Game
5. Crashed
```

### Expected Behavior

nothing

### Platform

```markdown
- Device model: OPPO A77
- CPU architecture: aarch64
- Android version: 6.0
- PojavLauncher version: Latest
```

### Anything else?

nothing

**Comment by Mathias-Boulay** [comment]
Lmao #1948

**Comment by ZIONJADEHD505** [comment]
Lmao man
