### ISSUE TITLE
[BUG] Unable to handle hostname

### ISSUE THREAD

**Issue by Namdz1221** [PojavLauncherTeam/PojavLauncher#1987]
### Describe the bug

I try to connect server heromc but error: cannot handle hostname 

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I hope the publisher fixes it

### Platform

```markdown
- Device model:Oppo_a1k 
- CPU architecture:aarch64
- Android version: 9
- PojavLauncher_version: crocus-v3_openjdk
``


### Anything else?

_No response_

**Comment by Mathias-Boulay** [comment]
Launcher version not stated

**Comment by Namdz1221** [comment]
Latest release on Ch Play

**Comment by Mathias-Boulay** [comment]
latest isn't a version name 😂

**Comment by Namdz1221** [comment]
Version: crocus-v3_openjdk 😂

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
