### ISSUE TITLE
I can't create Minecraft worlds, can't play online , Can't play forge Minecraft and Minecraft fabric

### ISSUE THREAD

**Issue by Dai2k9hihipro** [PojavLauncherTeam/PojavLauncher#1988]
### Describe the bug

I entered the game version 1.8.9 and went into multiplayer mode, but the game crashed And so is the survival mode
Forge and fabric While in the game, it crashed

### Steps To Reproduce

```markdown
1Launch pojavlauncher 
2Enter the game with version 1.8.9 
3Create a Minecraft World
4Flashed out Pojavlauncher screen
```

### Expected Behavior

Mong nhà phát triển  hỗ trợ

### Platform

```markdown
- Device model: Oppo A37f
- CPU architecture: aarch64
- Android version: 5.1.1
- PojavLauncher version: crocus-3_opejdk
```

### Anything else?

Ko

**Comment by Dai2k9hihipro** [comment]
https://youtu.be/PB_qAQic0Vw

**Comment by Mathias-Boulay** [comment]
Fill the template or be terminated

**Comment by Dai2k9hihipro** [comment]
file:///storage/emulated/0/games/PojavLauncher/latestlog.txt

**Comment by Dai2k9hihipro** [comment]
https://mega.nz/file/nvg0nZjR#zkZWhXE1x2H-Oml2Us6o8bvOGuak31_zcl768s6RAUE

**Comment by khanhduytran0** [comment]
Enable VBO.
||Bật VBO||

**Comment by Dai2k9hihipro** [comment]
Bật kiểu gì

**Comment by Dai2k9hihipro** [comment]
???

**Comment by Dai2k9hihipro** [comment]
😐

**Comment by Dai2k9hihipro** [comment]
Bật kiểu gì vậy @khanhduytran0 mình ko biết

**Comment by khanhduytran0** [comment]
![vbo](https://i.stack.imgur.com/zzSnf.png)

**Comment by Dai2k9hihipro** [comment]
Còn  forge và fabric phải làm thế nào

**Comment by Dai2k9hihipro** [comment]
fabric tôi không thể chơi được

**Comment by Dai2k9hihipro** [comment]
Tôi vẫn ko vào được thế giới Minecraft

**Comment by NotAHero04** [comment]
Still no log bruh...
(Vẫn chưa gửi nhật kí...)

**Comment by Dai2k9hihipro** [comment]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
	at android.app.ActivityThread.access$1000(ActivityThread.java:164)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:5541)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by: java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference
	at net.kdt.pojavlaunch.Tools.dpToPx(Tools.java:386)
	at net.kdt.pojavlaunch.BaseMainActivity.<init>(BaseMainActivity.java:53)
	at net.kdt.pojavlaunch.MainActivity.<init>(MainActivity.java:18)
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.Class.newInstance(Class.java:1606)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
	... 10 more

**Comment by Dai2k9hihipro** [comment]
để tôi gửi video Youtube

**Comment by Dai2k9hihipro** [comment]
https://youtu.be/95jM0Jy-VW8

**Comment by Dai2k9hihipro** [comment]
vừa lẫy tôi vào game bị văng

**Comment by NotAHero04** [comment]
Delete the old control map.
(Xoá bản đồ điều khiển cũ.)

**Comment by Dai2k9hihipro** [comment]
https://youtu.be/owOgYQo4OJM

**Comment by Dai2k9hihipro** [comment]
nhưng phiên bản 1.7.10 chơi được

**Comment by Dai2k9hihipro** [comment]
:(

**Comment by Dai2k9hihipro** [comment]
tôi xóa file lại chơi được mỗi fabric tôi không thể chơi được

**Comment by Mathias-Boulay** [comment]
we still need the latestlog.txt file 🤔

**Comment by Dai2k9hihipro** [comment]
Latestlog.txt https://mega.nz/file/rmYFxagK#wNbe_Yk7wWhJ7hle-9gExch8a08N0ngLmUV7H8i9cAQ

**Comment by Dai2k9hihipro** [comment]
--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: "-Xmx1G -Xms1G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10"
Info: Selected Minecraft version: fabric-loader-0.11.6-1.16.5 (1.16.5)
--------- beginning of system
--------- beginning of main
Added custom env: TMPDIR=/data/data/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1280
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/data/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/data/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-1/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/data/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
WARNING: linker: libgl4es_114.so: unused DT entry: type 0x6ffffef5 arg 0x2660
WARNING: linker: libgl4es_114.so: unused DT entry: type 0x6ffffffe arg 0x126d0
WARNING: linker: libgl4es_114.so: unused DT entry: type 0x6fffffff arg 0x3
I/LIBGL   (32122): Initialising gl4es
I/LIBGL   (32122): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   (32122): Using GLES 2.0 backend
I/LIBGL   (32122): loaded: libGLESv2.so
I/LIBGL   (32122): loaded: libEGL.so
I/LIBGL   (32122): Using GLES 2.0 backend
I/LIBGL   (32122): Hardware Full NPOT detected and used
I/LIBGL   (32122): FBO are in core, and so used
I/LIBGL   (32122): PointSprite are in core, and so used
I/LIBGL   (32122): CubeMap are in core, and so used
I/LIBGL   (32122): BlendColor is in core, and so used
I/LIBGL   (32122): Blend Substract is in core, and so used
I/LIBGL   (32122): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (32122): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (32122): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (32122): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (32122): Extension GL_OES_depth24  detected and used
I/LIBGL   (32122): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (32122): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (32122): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (32122): Extension GL_OES_texture_float  detected and used
I/LIBGL   (32122): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (32122): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (32122): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (32122): Extension GL_OES_fragment_precision_high  detected and used
I/LIBGL   (32122): Max vertex attrib: 16
I/LIBGL   (32122): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (32122): Max texture size: 4096
I/LIBGL   (32122): Max Varying Vector: 16
I/LIBGL   (32122): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (32122): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (32122): Max Anisotropic filtering: 16
I/LIBGL   (32122): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   (32122): Hardware vendor is Qualcomm
I/LIBGL   (32122): GLSL 300 es supported and used
I/LIBGL   (32122): EGLImage to Texture2D supported
I/LIBGL   (32122): EGLImage to RenderBuffer supported
I/LIBGL   (32122): ignore MipMap
I/LIBGL   (32122): Targeting OpenGL 2.1
I/LIBGL   (32122): NPOT texture handled in hardware
I/LIBGL   (32122): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (32122): try to use VBO
I/LIBGL   (32122): glX Will try to recycle EGL Surface
I/LIBGL   (32122): Current folder is:/
I/jrelog  (32122): dlopen libgl4es_114.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
referenceTable GDEF length=670 1
referenceTable GSUB length=7186 1
referenceTable GPOS length=24560 1
referenceTable head length=54 1
I/jrelog  (32122): dlopen libjvm.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success
WARNING: linker: /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so: unused DT entry: type 0x6ffffef5 arg 0x380
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
WARNING: linker: /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so: unused DT entry: type 0x6ffffffe arg 0xec8
WARNING: linker: /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so: unused DT entry: type 0x6fffffff arg 0x1
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (32122): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
WARNING: linker: /data/app/net.kdt.pojavlaunch-1/lib/arm64/libopenal.so: unused DT entry: type 0x6ffffef5 arg 0x4628
WARNING: linker: /data/app/net.kdt.pojavlaunch-1/lib/arm64/libopenal.so: unused DT entry: type 0x6ffffffe arg 0x303b0
WARNING: linker: /data/app/net.kdt.pojavlaunch-1/lib/arm64/libopenal.so: unused DT entry: type 0x6fffffff arg 0x3
I/jrelog  (32122): dlopen /data/app/net.kdt.pojavlaunch-1/lib/arm64/libopenal.so success
I/jrelog  (32122): Done processing args
I/jrelog  (32122): Found JLI lib
I/jrelog  (32122): Calling JLI_Launch
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
OpenJDK 64-Bit Server VM warning: Can't detect primordial thread stack location - find_vma failed
[10:40:33] [main/INFO]: Loading for game Minecraft 1.16.5
[10:40:33] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[10:40:34] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...

**Comment by Dai2k9hihipro** [comment]
Ram 2gd mà arm 64 vô lý

**Comment by Dai2k9hihipro** [comment]
vậy có cách nào ko

**Comment by Dai2k9hihipro** [comment]
:(
