### ISSUE TITLE
[BUG] Zink renderer appears to be using entirely software rendering

### ISSUE THREAD

**Issue by maximumsomething** [PojavLauncherTeam/PojavLauncher#1994]
### Describe the bug

When Zink renderer is used, CPU usage is 100% across all eight cores, GPU usage is near zero, and FPS is very low, leading me to believe it is using software rendering.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7130902/latestlog.txt)

### Steps To Reproduce

Change renderer to zink in settings then launch the game (I was testing using 1.16.5). Then observe high CPU and low GPU usage (I used https://play.google.com/store/apps/details?id=com.razorlabs.cpumeter). Minecraft is a mostly single-threaded game; it is not using every core by itself.

### Expected Behavior

The GPU is used

### Platform

```markdown
- Device model: Galaxy S10e
- CPU architecture: aarch64 (Snapdragon 855)
- Android version: 11
- PojavLauncher version: Latest release (crocus-v3_openjdk)
```

### Anything else?

From what I can gather online, OSMesa can only be used with software rendering. See https://docs.mesa3d.org/osmesa.html :

> The OSMesa interface may be used with the gallium software renderers:
> 1. llvmpipe - this is the high-performance Gallium LLVM driver
> 2. softpipe - this it the reference Gallium software driver

**Comment by artdeell** [comment]
If you try to use softpipe by using the Mesa driver override env variable, you will see that the actual software rendering speed is in the 1 frame per minute region.
The thing is: OSMesa is not optimized to be used like we use it. It does a lot of framebuffer copying (on the CPU). But at the same time, we can't use DRM card management because it would mean linking against system libraries (not good)

**Comment by maximumsomething** [comment]
There's still something strange going on here. Copying ~3 frames per second does not take several CPU cores. Perhaps it is using llvmpipe or lavapipe (which would be much faster than softpipe but still much slower than the GPU)?

**Comment by artdeell** [comment]
No way it would be using llvmpipe because we didn't compile the llvm deps

**Comment by maximumsomething** [comment]
Is there a build of the launcher with debug symbols for Mesa? Alternatively, are there instructions somewhere for how to build Pojav's mesa libs? I feel like doing some profiling.

**Comment by artdeell** [comment]
Android always strips the symbols, and we also strip them because full git clone of the launcher repo is a bit too big.
https://github.com/PojavLauncherTeam/mesa/actions - mesa builds, but i forgot which commit is actually used in the launcher

**Comment by maximumsomething** [comment]
I've learned a few things:
1. It isn't actually using all CPU cores; that was a bug in the application I was using to monitor CPU usage.
2. Most of the overhead is inside a single function within Mesa that translates vertex buffer formats.
3. You guys are using a version of zink that's nearly a year old. A LOT of performance improvement has been made since then. You should update to mesa 21.2 or perhaps even [zink-wip](https://gitlab.freedesktop.org/zmike/mesa/) and actually include the new builds of mesa in the launcher.

**Comment by WesleyVanNeck** [comment]
> I've learned a few things:
> 
> 1. It isn't actually using all CPU cores; that was a bug in the application I was using to monitor CPU usage.
> 2. Most of the overhead is inside a single function within Mesa that translates vertex buffer formats.
> 3. You guys are using a version of zink that's nearly a year old. A LOT of performance improvement has been made since then. You should update to mesa 21.2 or perhaps even [zink-wip](https://gitlab.freedesktop.org/zmike/mesa/) and actually include the new builds of mesa in the launcher.

We couldnt get latest mesa working and we don't got a lot of time

**Comment by WesleyVanNeck** [comment]
its opensource if you can fix it go ahead

**Comment by khanhduytran0** [comment]
> 3. You guys are using a version of zink that's nearly a year old. A LOT of performance improvement has been made since then. You should update to mesa 21.2 or perhaps even [zink-wip](https://gitlab.freedesktop.org/zmike/mesa/) and actually include the new builds of mesa in the launcher.

Looking at the requirements since Mesa 21.1, you will see that a lot of extensions are missing on most devices:
### OpenGL 2.1
- VkPhysicalDeviceFeatures: [logicOp](http://vulkan.gpuinfo.org/listdevicescoverage.php?feature=logicOp&platform=android), [wideLines](http://vulkan.gpuinfo.org/listdevicescoverage.php?feature=wideLines&platform=android)
- [VK_EXT_custom_border_color](http://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_EXT_custom_border_color&platform=android)
- [VK_EXT_provoking_vertex](http://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_EXT_provoking_vertex&platform=android)
- VkPhysicalDeviceLineRasterizationFeaturesEXT: [smoothLines](http://vulkan.gpuinfo.org/listdevicescoverage.php?extensionname=VK_EXT_line_rasterization&extensionfeature=smoothLines&platform=android), [stippledBresenhamLines](http://vulkan.gpuinfo.org/listdevicescoverage.php?extensionname=VK_EXT_line_rasterization&extensionfeature=stippledBresenhamLines&platform=android), stippledRectangularLines and stippledSmoothLines are unlisted in gpuinfo.

### OpenGL 3.0
- ~~[VK_EXT_conditional_rendering](http://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_EXT_conditional_rendering&platform=android)~~ Minecraft doesn’t use conditional rendering.

**Comment by artdeell** [comment]
My device is basically missing all of them

**Comment by khanhduytran0** [comment]
From @LegacyGamerHD after updated to Mesa 21.2.1:
```
OSMDroid: width=1260;height=540, reserving 2721600 bytes for frame buffer
OSMDroid: created frame buffer
OSMDroid: generating context
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Adreno (TM) 620) doesn't support base Zink requirements: 
feats.features.logicOp feats.features.wideLines have_EXT_custom_border_color line_rast_feats.smoothLines line_rast_feats.stippledRectangularLines line_rast_feats.stippledBresenhamLines line_rast_feats.stippledSmoothLines 
OSMESA_TARGET: screen=0x7384d446b0
OSMESA: stmgr=0x71e4e9e250; stapi=0x7121104d30
OSMDroid: context=0x7214d2e490OSMDroid: making current
OSMDroid: vendor: Collabora Ltd
OSMDroid: renderer: zink (Adreno (TM) 620)
--------- beginning of crash
```

**Comment by dachisao** [comment]
my brain is hurting

**Comment by khanhduytran0** [comment]
Notice that these listed extensions are NOT even available in Adreno 660 (inside Snapdragon 888) when looking into gpuinfo. How do we get it to work then? @maximumsomething

**Comment by artdeell** [comment]
@khanhduytran0 we might as well just hope that they ae not really required by minecraft

**Comment by khanhduytran0** [comment]
> @khanhduytran0 we might as well just hope that they ae not really required by minecraft

By looking into the game, it has several logicOp calls, which is only available in PowerVR GPUs (?).
~~Emulating missing things by borrowing stuff from gl4es may also an option~~

**Comment by artdeell** [comment]
> > @khanhduytran0 we might as well just hope that they ae not really required by minecraft
> 
> By looking into the game, it has several logicOp calls, which is only available in PowerVR GPUs (?).
> ~Emulating missing things by borrowing stuff from gl4es may also an option~

I wonder why older Zink versions didn't use these exts

**Comment by maximumsomething** [comment]
I doubt the extensions are the problem, as according to messages on the discord it's crashing in OSMesa code not Zink. I might be able to help if I had the full stacktrace.

**Comment by zekyupanda** [comment]
java.lang.RuntimeException: Vulkan Zink renderer is not supported on this device!
	at net.kdt.pojavlaunch.BaseMainActivity.checkVulkanZinkIsSupported(BaseMainActivity.java:757)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:720)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
pls how to fix it

**Comment by RuggedScarab** [comment]
> java.lang.RuntimeException: Vulkan Zink renderer is not supported on this device! at net.kdt.pojavlaunch.BaseMainActivity.checkVulkanZinkIsSupported(BaseMainActivity.java:757) at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:720) at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36) at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552) at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2) at java.lang.Thread.run(Thread.java:764) pls how to fix it

Your device doesn't support the renderer

**Comment by sa1672ndo** [comment]
> java.lang.RuntimeException: Vulkan Zink renderer is not supported on this device!

The first line tells u everything u need to know, there's nothing else to say.
