### ISSUE TITLE
[F-Req] Add Keyboard Button On Mod Installer

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#1995]
### Is this request related to a bug?

Nope

### Describe the request.

There Is No Keyboard Button On Mod Installer GUI So Making It Difficult To Name Profiles Also Changing Version Name Manually From File Managers Make The Version Invalid 

![Screenshot_20210909_084607](https://user-images.githubusercontent.com/69802631/132616670-25e38f62-f70e-4d8c-826e-482ca479bea5.png)

This One Is For Forge(No Naming On Forge), But Pls Add The Keyboard Button 

### Anything else?

_No response from Devs_

**Comment by ZIONJADEHD505** [comment]
Just stick with it😒

**Comment by Abdulhadi5692HDI** [comment]
Well fork it and make the keybord button. `:)`

**Comment by khanhduytran0** [comment]
~~will you request for controller input support for mod installer?~~ :trollface:

**Comment by Mathias-Boulay** [comment]
DOOOOOOOOOOOONE
