### ISSUE TITLE
About Zink renderer

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#1996]
### Is this request related to a bug?

You should make this renderer less laggy

### Describe the request.

Make Zink renderer less laggy

### Anything else?

This renderer can run 1.17+ version without asset v0 pack

**Comment by ajit850** [comment]
Zink renderer also give crosshair which are missing in asset v0 pack

**Comment by ghost** [comment]
If it would get true then I think we will be able to run mods in 1.17?

**Comment by ghost** [comment]
Yeah plse make it less laggy I wanna play sodium on it

**Comment by matt995** [comment]
How do you expect them to make “zink less laggy”, also they are not paid so don’t demand.

**Comment by Ewjjai** [comment]
I could give money for zink

**Comment by khanhduytran0** [comment]
Giving money doesn't mean give us OpenGL and Vulkan knowledge. We are not Zink developers, that's all.

**Comment by ajit850** [comment]
This renderer also support optifine 1.17.1

**Comment by Mathias-Boulay** [comment]
We can't do shit zink wise since we aren't the devs behind it.
I'll close the issue.
