### ISSUE TITLE
1.17.1 optifine is laggy on open gles 3.2

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#1997]
### Describe the bug

1.17.1 optifine is worked on my phone but its very laggy

### The log file and images/videos

![Screenshot_20210909-120027_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/87809448/132631709-82b9954d-1cd3-44f4-b5e4-eea0cf940014.jpg)

### Steps To Reproduce

```markdown
1.start pojav
2.download JDKarrch 64
3.open game
```

### Expected Behavior

I hope like this will be fixed for permanent solutions  

### Platform

```markdown
- Device model: samsung m21
- CPU architecture: 64
- Android version: 11
- PojavLauncher version:crocus openjdk (playstore)
```

**Comment by Ewjjai** [comment]
Runtime used JDK arrch 64 
Renderer: open gles 3.2 (not 1.17 suppoerted yet)

**Comment by Mathias-Boulay** [comment]
wrong runtime though
Aren't you using zink ?
If not that's impressive

**Comment by Mathias-Boulay** [comment]
But as you said, you're using an unsupported renderer.

**Comment by Ewjjai** [comment]
Sorry im not pay to attention on renderer, im using zink but i checked minecraft 1.17.1 run without assets v0 and option.txt
. i just deleted them and check but works well
