### ISSUE TITLE
Bad idea for Pojav v3

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#2]
ExaGear Windows emulator is FAR too slow to run Minecaft at acceptable framerate, so it's a bad idea to use ExaGear for launching Minecraft.

**Comment by khanhduytran0** [comment]
Yes, I cancelled using Exagear Windows Emulator. Now I'm looking for other ways.

**Comment by artdeell** [comment]
Thhanks. Now the problem is resolved.

**Comment by ebuild-1** [comment]
Hiii <3
