### ISSUE TITLE
Bug when writing in game (1.9 onwards) 

### ISSUE THREAD

**Issue by jrxohan** [PojavLauncherTeam/PojavLauncher#20]
I see that many possibly happens to them and that is that at the time of writing they put the key that one press twice, this occurs in 1.9, 1.10 and 1.11, and the truth is quite annoying and there is no fix, a video in case  do not understand
https://youtu.be/NPBfB0Wc7LU

**Comment by emelin2004** [comment]
I have the same problem,would be nice if this could be put to the primary bug fix list.

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.7.2

**Comment by khanhduytran0** [comment]
Get https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.7.3 instead.

**Comment by jrxohan** [comment]
> Get https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.7.3 instead.

Thanks now the issue is solved
