### ISSUE TITLE
V3.0.1 pre4

### ISSUE THREAD

**Issue by reply7251** [PojavLauncherTeam/PojavLauncher#200]
![Screenshot_20200513-103508](https://user-images.githubusercontent.com/24792782/81765128-9f682880-9505-11ea-9ab9-8fa5557cba43.jpg)
It shows this but dev console and crash report shows nothing

**Comment by khanhduytran0** [comment]
I'm fixing.

**Comment by khanhduytran0** [comment]
Try Preview5.

**Comment by khanhduytran0** [comment]
Try preview5

**Comment by reply7251** [comment]
I don't know if it's because I'm using Android 10 or what, but pre5 has the same problem.
