### ISSUE TITLE
[F-Req] A help menu for some features

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher#2000]
### Is this request related to a bug?

No.

### Describe the request.

...like how to install Java Runtimes in the ‘Runtime Manager’ feature, how to customize controls...

### Anything else?

I think we could have a user guide in the launcher, which works best for inexperienced users.

**Comment by Mathias-Boulay** [comment]
You'll be more than welcome to design the whole thing 🤔

**Comment by rscDMTalt** [comment]
hey hey
