### ISSUE TITLE
(happens again) white screen pojavlauncher vgpu[BUG] <Short description>

### ISSUE THREAD

**Issue by SteveAlexM** [PojavLauncherTeam/PojavLauncher#2001]
### Describe the bug

White screen

### The log file and images/videos

![FB_IMG_16305493606063189](https://user-images.githubusercontent.com/83632207/132657946-45aa7c20-36c7-420b-aba8-1739a8617285.jpg)

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Select vgpu renderer
3. Push "play"
4. bugs happen
```

### Expected Behavior

I hope this can be fixed

### Platform

```markdown
- Device model: vivo y12
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

No

**Comment by khanhduytran0** [comment]
*Also select how your PR is constructed.*

**Comment by khanhduytran0** [comment]
also select send log

**Comment by SteveAlexM** [comment]
Oh ok

**Comment by WesleyVanNeck** [comment]
Post the latestlog.txt not in massage box

**Comment by SteveAlexM** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7142000/latestlog.txt)

**Comment by SteveAlexM** [comment]
that's the latest log txt

**Comment by SteveAlexM** [comment]
![Screenshot_20210911_145243](https://user-images.githubusercontent.com/83632207/132940813-cedf3076-3636-4a5b-80b9-1f8a25b51a25.jpg)
this is on my friend's cellphone (his cellphone specifications are the same as mine)

**Comment by WesleyVanNeck** [comment]
dont use vgpu

**Comment by SteveAlexM** [comment]
but i want to try vgpu
