### ISSUE TITLE
[BUG] Bluetooth mouse hardly working in-game

### ISSUE THREAD

**Issue by LivingCodeX** [PojavLauncherTeam/PojavLauncher#2002]
### Describe the bug

In-game, rotating is very difficult and practically impossible if you want to play the game normally.

It's working perfectly fine in menus like in the title screen menu, ESC menu and inventory.
Also, while a screen recorder is active, scrolling with the mouse or pressing any mouse button (left or right click), it appears to update the rotation more often. It seems like the mouse updates 20-40 times a second with a screen recorder and every 3-5th mouse click (tested without a screen recorder active).
Scrolling through hotbar slots works just fine; the only issue is rotating.

Notes: Rotating by touching the screen is still working. It seems to work better when there's more CPU load (?) because of the screen recorder thing and after the world is loaded it works acceptable but after a few seconds, it's like in the video I recorded.

### The log file and images/videos

[Video of me trying to rotate without an active screen recorder, mouse scrolling or clicking](https://youtu.be/sMcGOOWuv_c)
Bad quality because I wanted to demonstrate the issue without using a screen recorder to capture the screen.

### Steps To Reproduce

```markdown
1. Connect a bluetooth mouse
2. Launch the game
3. Enter any world
4. Move the mouse
```

### Expected Behavior

I expect to be able to change my player's rotation fluently.

### Platform

```markdown
- Device model: Samsung Galaxy Tab S7+ 8/256G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-22-344ec0158- (actions build Android CI #3239)
```

### Anything else?

Mouse: Logitech Pebble M350 (connected via Bluetooth)

**Comment by Mathias-Boulay** [comment]
I never thought we could encounter a case where the device is so powerful we aren't even CPU limited 🤔 
If you could, it would be nice to try with a wired mouse to see if the issue is mouse or device specific

**Comment by SuperTopGamers** [comment]
Ola tudo bem? Eu tenho um A32, e jogo com mouse de fio... o problema é o mesmo... pelo que parece vocês estão tentando consertar já eu acho..

**Comment by LivingCodeX** [comment]
I've now tested the same mouse with a USB receiver. The results are significantly better, but the game is still not really playable.
But I've found a work-around: If I combine the USB receiver with the screen recorder, it is actually playable. And now the interesting part: It still works when the screen recorder is PAUSED but not stopped. That means that there will just be a tiny video file that I can delete after my session + the frame rate doesn't drop as much.

**Comment by SuperTopGamers** [comment]
Thank you! The old version of pojav works perfectly fine with the mouse,
there's no way to put the same setting back in the app?

**Comment by Mathias-Boulay** [comment]
The thing is that we did optimizations and now the cpu doesn't seem to go as fast frequency wise.
This is weird, I'll investigate later if I can

**Comment by SuperTopGamers** [comment]
Awesome, thanks!

Em sáb., 11 de set. de 2021 10:08, Boulay Mathias ***@***.***>
escreveu:

**Comment by Deckedgamer23** [comment]
Mathias Boulay, I have the same problem but I'm on Chromebook with a wired mouse that can barely move my view so you are unable to PVP or play bedwars skywars or any PVP related game

**Comment by LivingCodeX** [comment]
Closing this issue since it will be fixed soon.
