### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Szymon64** [PojavLauncherTeam/PojavLauncher#2004]
### Describe the bug

Hello, I would like to report such a problem that I am kicked out of the game and I did not do it before, I think it is due to the fact that I updated android to 11 and I had 10 before before that, Minecraft worked very well until I updated to Android 11 Now it even can't move to do anything in Minecraft

### The log file and images/videos

https://drive.google.com/file/d/1324Bi_IWaBq9SYwLVRYS2NNZxrxe-JZV/view?usp=drivesdk

### Steps To Reproduce

```markdown
cannot find the error
```

### Expected Behavior

the game starts normally but when I'm in the world it crashes me

### Platform

```markdown
- Device model: oppo a53
- CPU architecture: Qualcomm SM4250 Ośmiordzeniowy
- Android version: 11
- PojavLauncher version crocus-v3_openjdk
```

### Anything else?

_No response

**Comment by artdeell** [comment]
No log and no device/version info.

**Comment by Szymon64** [comment]
> No log and no device/version info.

android version 11 before i had 10

**Comment by Szymon64** [comment]
> No log and no device/version info.

Już wszystko poprawione
