### ISSUE TITLE
4-10 FPS on optifine 1.17.1

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#2007]
### Is this request related to a bug?

![Uploading Screenshot_20210910-090029_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

### Describe the request.

![Screenshot_20210910-090355_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/87809448/132793005-4f654fa0-a75e-4ee0-b928-1b53d7b7026d.jpg)

### Anything else?

Which java agruaments gives better fps on 4 gb ram?

**Comment by Mathias-Boulay** [comment]
zink isn't suppoorted rn

**Comment by dachisao** [comment]
> __Which java agruaments gives better fps on 4 gb ram?__

lmao

**Comment by ZIONJADEHD505** [comment]
Change to other renderer
