### ISSUE TITLE
[F-Req] <希望添加外置登录>

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2012]
### Describe the request.

如果不添加的话，在服务器里只能使用史蒂夫皮肤，建议添加。并把外置登录按钮和微软登录按钮放在一旁。
[谷歌翻译]  If you don't add it, you can only use the Steve skin in the server, and it is recommended to add it. And put the external login button and the Microsoft login button aside.

**Comment by aaaapai** [comment]
顺便把1.17的那个安装包也弄一下

**Comment by aaaapai** [comment]
添加外置登录功能主要目的，为了可以更换皮肤。这个电脑端启动器实现了。给你看个视频样本就知道了。
为了你更快更新，某个启动器下载链接准备好了：https://hmcl.huangyuhui.net/

这是电脑端的启动器，拿来研究！













At 2021-09-11 14:53:17, "LegacyGamerHD" ***@***.***> wrote:

Closed #2012.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

从网易yeah邮箱发来的超大附件
1631620619708.mp4 (22.85M, 2021年9月29日 21:13 到期)
在线预览 | 下载

**Comment by aaaapai** [comment]
The main purpose of adding external login function is to change the skin. This computer starter is implemented. Just show you a video sample. For faster updates, a starter download link is ready: https://hmcl.huangyuhui.net/ This is the starter on the computer side. Let's study it!



在 2021-09-14 21:17:44，"mcnb66666" ***@***.***> 写道：

添加外置登录功能主要目的，为了可以更换皮肤。这个电脑端启动器实现了。给你看个视频样本就知道了。
为了你更快更新，某个启动器下载链接准备好了：https://hmcl.huangyuhui.net/

这是电脑端的启动器，拿来研究！













At 2021-09-11 14:53:17, "LegacyGamerHD" ***@***.***> wrote:

Closed #2012.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

从网易yeah邮箱发来的超大附件
1631620619708.mp4 (22.85M, 2021年9月29日 21:13 到期)
在线预览 | 下载

**Comment by khanhduytran0** [comment]
> If you don't add it, you can only use the Steve skin in the server, and it is recommended to add it. And put the external login button and the Microsoft login button aside.

Buy Minecraft and go to https://minecraft.net/en-us/profile/skin to change skin. The offline mode is going to be removed soon. Because of this, changing skin for offline account won't be added.
