### ISSUE TITLE
PLS ADD CONTROL MOVING

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#2013]
### Describe the request.

Plss add joystick for moving it's hard to move back and forth left and right

**Comment by khanhduytran0** [comment]
There's an option called **Swipeable** that exists in Custom Control since crocus update.

**Comment by kedrick021** [comment]
> There's an option called **Swipeable** that exists in Custom Control since crocus update.

In edit?
