### ISSUE TITLE
Hope to support the login account of "authlib injector"

### ISSUE THREAD

**Issue by HIM049** [PojavLauncherTeam/PojavLauncher#2014]
### Describe the request.

I hope that the launcher can log in using "authlib injector". Many servers are using this account.
This is the github page of "authlib injector": https://github.com/yushijinhun/authlib-injector/

### Anything else?

No others

**Comment by khanhduytran0** [comment]
Duplicate of #824

**Comment by HIM049** [comment]
OK, I know. Thanks
