### ISSUE TITLE
[BUG] Forge 1.12.2_14.23.5.2855 keyboard doesn't working! 

### ISSUE THREAD

**Issue by ZuVEnO** [PojavLauncherTeam/PojavLauncher#2015]
### Describe the bug

After last update keyboard is bugged! When I'm click on letter she's hide. But on anothers versions this bug is fixed. 

### Steps To Reproduce

```markdown
1. Launching PojavLauncher
2. Launching 1.12.2_forge-14.23.5.2855
3. Opening keyboard
4. Write a letter
5. After 4 step keyboard is switching on!
```

### Expected Behavior

Keyboard will be turned on after wrote a letter. 

### Platform

```markdown
- Device model: Redmi Note 8 Pro/64GB
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3
```

**Comment by Mathias-Boulay** [comment]
Fixed on newer versions, it will come to Gplay at some point 🤔
