### ISSUE TITLE
[BUG] I can't join servers

### ISSUE THREAD

**Issue by ZIONJADEHD505** [PojavLauncherTeam/PojavLauncher#2019]
### Describe the bug

I can't join servers for some reasons

### Steps To Reproduce

```markdown
1.start PojavLauncher
2.go to servers example my server
3. This error comes out
```

### Expected Behavior

I expect I can join servers 

### Platform

```markdown
- Device model:Huawei Matepad T8
- CPU architecture:32bits
- Android version:android 10
- PojavLauncher version:vgpu tests
```

**Comment by ZIONJADEHD505** [comment]
It's saying> (invalid session) try restarting your game or launcher

**Comment by khanhduytran0** [comment]
Yes, I know you were trying to play Hypixel with an **offline** account.
~~offline account removal eta sooner 🤔~~

**Comment by ZIONJADEHD505** [comment]
No I wanna play on my server

**Comment by ZIONJADEHD505** [comment]
OK then I'll make an online acc then😔

**Comment by ZIONJADEHD505** [comment]
Bruh I can't get an online acc

**Comment by ZIONJADEHD505** [comment]
It seems I cant play on this launcher after offline acc removal

**Comment by Mathias-Boulay** [comment]
unsupported build is used.

**Comment by ZIONJADEHD505** [comment]
OK
