### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by yaseel** [PojavLauncherTeam/PojavLauncher#202]
All I need is to connect to servers

**Comment by khanhduytran0** [comment]
It's
- Partial possible with nothing changes.
- Almost possible with VMOS or Android 5.

**Comment by artdeell** [comment]
> All I need is to connect to servers

just... connect
it may error on non-premium servers, but definitely should work on some.

**Comment by khanhduytran0** [comment]
@notaseel please reply
