### ISSUE TITLE
[Add 1.18 experimental snapshot] sex

### ISSUE THREAD

**Issue by RyanTheCoder10038** [PojavLauncherTeam/PojavLauncher#2021]
### Describe the request.

get 1.18 experimental punjabi sex sex

**Comment by dachisao** [comment]
the Jenny Mod is **NOT** available for 1.18.

**Comment by dachisao** [comment]
Also, sex is bad. Don't get addicted by it.

**Comment by RyanTheCoder10038** [comment]
> Also, sex is bad. Don't get addicted by it.

i like sex what do you think
and yes i did a little.trolling in Afghanistan

**Comment by RyanTheCoder10038** [comment]
> the Jenny Mod is **NOT** available for 1.18.

what the fuck is Jenny mod

**Comment by dachisao** [comment]
what the fuck

> > Also, sex is bad. Don't get addicted by it.
> 
> i like sex what do you think
> and yes i did a little.trolling in Afghanistan

**Comment by RyanTheCoder10038** [comment]
> what the fuck
> 
> > > Also, sex is bad. Don't get addicted by it.
> > 
> > 
> > i like sex what do you think
> > and yes i did a little.trolling in Afghanistan

<:wtfman:781816589557301258> now SHUT

**Comment by retroXolotl** [comment]
||![Screenshot_20210912_202245](https://user-images.githubusercontent.com/87068881/132987397-01a4a0c1-9879-481d-83ea-831696e7521e.jpg)||

**Comment by ghost** [comment]
> > Also, sex is bad. Don't get addicted by it.
> 
> i like sex what do you think
> and yes i did a little.trolling in Afghanistan

lol wtf

**Comment by RyanTheCoder10038** [comment]
DONT SEND ME YOUR DICK PICS

**Comment by dachisao** [comment]
![IMG_20210912_202404](https://user-images.githubusercontent.com/87068881/132987430-ec91e8cd-0d01-429b-9093-240e37415e7a.jpg)
This is Jenny Mod.

**Comment by RyanTheCoder10038** [comment]
> ![IMG_20210912_202404](https://user-images.githubusercontent.com/87068881/132987430-ec91e8cd-0d01-429b-9093-240e37415e7a.jpg)
> This is Jenny Mod.

then why do you ask jenny mod
sex is trolling
are you horny or what 🗿

**Comment by dachisao** [comment]
> > ![IMG_20210912_202404](https://user-images.githubusercontent.com/87068881/132987430-ec91e8cd-0d01-429b-9093-240e37415e7a.jpg)
> > This is Jenny Mod.
> 
> then why do you ask jenny mod
> sex is trolling
> are you horny or what 🗿

WHAT THE FUCK?
YOU SAID:
> ### Describe the request.
> **get 1.18 experimental punjabi sex sex**

**Comment by ghost** [comment]
> ### Is this request related to a bug?
> 
> _No response_
> 
> ### Describe the request.
> 
> get 1.18 experimental punjabi sex sex
> 
> ### Anything else?
> 
> _No response_

wtf![Screenshot_2021-09-12-19-26-25-662_com.github.android.jpg](https://user-images.githubusercontent.com/86137443/132987546-b87a35e5-2af2-466b-a63b-3e1b3339c20f.jpg)

**Comment by dachisao** [comment]
> > ### Is this request related to a bug?
> > _No response_
> > ### Describe the request.
> > get 1.18 experimental punjabi sex sex
> > ### Anything else?
> > _No response_
> 
> wtf![Screenshot_2021-09-12-19-26-25-662_com.github.android.jpg](https://user-images.githubusercontent.com/86137443/132987546-b87a35e5-2af2-466b-a63b-3e1b3339c20f.jpg)

you want the hd one?

**Comment by dachisao** [comment]
@RyanTheCoder10038 here's the mod link

https://www.thisworldthesedays.com/get-118-experimental-punjabi-sex-sex2.html

**Comment by WITHERPROWER** [comment]
Wtf

**Comment by ZIONJADEHD505** [comment]
FINALLY IT'S CLOSE DON'T GET ADDICTED

**Comment by ZIONJADEHD505** [comment]
Wtf were not devs of that mod
