### ISSUE TITLE
Game Exited With Code 1 | Samsung Galaxy A02

### ISSUE THREAD

**Issue by 0x0byalix** [PojavLauncherTeam/PojavLauncher#2023]
### Describe the bug

![Screenshot_20210913-134808_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/87875299/133054354-233db136-d192-46f1-8c22-8cbe46d3a48d.jpg)

### Steps To Reproduce

```markdown
IDK
```

### Expected Behavior

-----

### Platform

```markdown
- Device model: A02
- CPU architecture: arm
- Android version: 10
- PojavLauncher version: openjdk 3
```

**Comment by artdeell** [comment]
No log. Can't tell anything.

**Comment by 0x0byalix** [comment]
I got it as a dev

My device is armhf/32 and it does not support i.
