### ISSUE TITLE
[BUG] pojavlaucher crash com mais de 300 MB de ram

### ISSUE THREAD

**Issue by AranhaGamerOF** [PojavLauncherTeam/PojavLauncher#2024]
### Describe the bug

Pojavlaucher crash quando coloco mais de 300 MB de ram mais meu celular tem 1G liberado

Meu celular e 32 bits

Espero que resolvam esse bug pfvr😞

### Steps To Reproduce

```markdown
Entro no pojavlaucher coloco 400 MB de ram (meu celular aguenta) entro na versão e o pojavlaucher crasha
```

### Expected Behavior

Espero que eu consiga jogar com mais de 300 MB de ram

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by WesleyVanNeck** [comment]
english or we dont help

**Comment by AranhaGamerOF** [comment]
my pojavlaucher is crashing when I put more than 300 mb of ram

**Comment by WesleyVanNeck** [comment]
> my pojavlaucher is crashing when I put more than 300 mb of ram

32 bit not our problem if you run it on low and phone

**Comment by AranhaGamerOF** [comment]
crashing*

**Comment by AranhaGamerOF** [comment]
but in the old versions it didn't close by itself

**Comment by AranhaGamerOF** [comment]
my pojavlaucher closes when I put more than 300 mb of ram but that didn't happen before

**Comment by ZIONJADEHD505** [comment]
Yeah same at my old phone that happen too

**Comment by Mathias-Boulay** [comment]
Lack of info
