### ISSUE TITLE
Application/game exited with code 1 |SAMSUNG galaxy m01s

### ISSUE THREAD

**Issue by bobbyiscool123** [PojavLauncherTeam/PojavLauncher#2025]
### Describe the bug

Application/game exited with code 1

### The log file and images/videos
#
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7155656/latestlog.txt)

![Screenshot_20210913-205205_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/90083064/133117271-fa13e19f-2b6d-4142-8c2c-908fca11b228.jpg)

### Steps To Reproduce

```markdown
1.dowloaded pojavlauncher from playstore
2.Opened pojavlauncher
3.signed with offline account.
4.dowloaded 1.16.5
5.skipping asserts files
6.loading game...?(black screen)
7.Application/game exited with code 1
```

### Expected Behavior

1.dowloaded pojavlauncher from playstore
2.Opened pojavlauncher
3.signed with offline account.
4.dowloaded 1.16.5
5.skipping asserts files
6.loading game...?(black screen)
8.controllers will come
7. (few seconds later) it say MOJANG STUDIOUS... and its gonna load up minecraft

### Platform

```markdown
- Device model: Samsung galaxy m01s
- CPU architecture: arch:32
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

![Screenshot_20210913-205205_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/90083064/133113770-2fa53e39-3de4-4cee-b12b-007a6b09a504.jpg)

**Comment by WesleyVanNeck** [comment]
alocated less ram

Could not reserve enough space for 958464KB object heap
