### ISSUE TITLE
CALL OF DUTY MODERN WARFARE MOD crashing on all versions can this be resolved?

### ISSUE THREAD

**Issue by SorkAfk** [PojavLauncherTeam/PojavLauncher#2026]
### Describe the bug

Application exited with code -1

### The log file and images/videos

https://user-images.githubusercontent.com/90634767/133114278-f218e3a3-266b-40e6-95eb-a1d4c30dcd66.mp4

### Steps To Reproduce

```markdown
I don't really know what this area is but I just go into forge 1.8.9 I go into my world and try to use the mod and the launcher crasha (I can't describe this area)
```

### Expected Behavior

https://user-images.githubusercontent.com/90634767/133115534-0d2345d2-8166-4b3d-a239-1e842d5040b4.mp4

(this video is not mine) 

### Platform

```markdown
- Device model: Moto g8 power/64G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3_opengjdk
```

**Comment by khanhduytran0** [comment]
#1948

**Comment by ZIONJADEHD505** [comment]
It's the same just install other gun mod if u try it like that it will just crash
