### ISSUE TITLE
[BUG] litematic is not work

### ISSUE THREAD

**Issue by VinTeRuS** [PojavLauncherTeam/PojavLauncher#2027]
### Describe the bug

The litematic menu does not appear

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Redmi 8t 4/64
- CPU architecture: ARM 
- Android version:10 
- PojavLauncher version: last.
```

### Anything else?

.

**Comment by rscDMTalt** [comment]
Dismissed.

1. No __latestlog.txt__.
2. your statement is too short

**Comment by khanhduytran0** [comment]
#1948
