### ISSUE TITLE
[F-Req] <download skin

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#2028]
### Is this request related to a bug?

For change the skin you should add skin Change Option and your new link to download the skin and change like tlauncher

### Describe the request.

Add skin Change Option and your new link to download skins

**Comment by Faked4070** [comment]
yee new skins

**Comment by Faked4070** [comment]
you are change a skin with mod iffline skins

**Comment by AgaricaGamer** [comment]
100% closable

**Comment by CriticalRange** [comment]
As a wise man once said

> For skins go to minecraft.net
No account ? No skin change
Fuck you
