### ISSUE TITLE
Minecraft old alpha version a1.0.16 no working

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#2031]
### Describe the bug

Game exited 

### The log file and images/videos

![Screenshot_20210914-173513_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/79654338/133254481-191f9eb1-f950-4f5f-9cf2-dd01cc03ec7c.jpg)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.select Minecraft a1.0.16 old alpha version
3.game exited
```

### Expected Behavior

I expect to play Minecraft A1.0.16

### Platform

```markdown
- Device model: Samsung galaxy m31
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: pojavlauncher crocus-62-9fc987f13-v3_openjdk
```

**Comment by tencentgamer2345** [comment]
maybe you are using Jre 17 Try Jre 8 it will definitely work

**Comment by ajit850** [comment]
![Screenshot_20210914-175948_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/79654338/133257764-da1c2e11-dba1-49c4-958a-6502305fe015.jpg)

**Comment by ajit850** [comment]
It is not working

**Comment by tencentgamer2345** [comment]
Oh No Jdk 8 Will Not Work To Run This Version Try Using Jre 8

**Comment by ajit850** [comment]
I can't find jre 8 please give like to download

**Comment by tencentgamer2345** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/1086220179

**Comment by tencentgamer2345** [comment]
If It Doesn't Work Delete Jdk 8 Inside Runtime Manager

**Comment by ajit850** [comment]
It is not working

**Comment by tencentgamer2345** [comment]
https://youtu.be/T8D6LrVw1L8 See This Video

**Comment by tencentgamer2345** [comment]
I'm in this version working but unfortunately the game is very laggy

**Comment by ajit850** [comment]
I am sorry it works but screen size is too small

**Comment by tencentgamer2345** [comment]
if the screen size is small, try pressing F11 on the keyboard

**Comment by ajit850** [comment]
game not working there is no render loading

**Comment by Ewjjai** [comment]
Use playstore version and download JDK17 arrch 64 and play all versio.  I played all version
