### ISSUE TITLE
Nothing but need a help

### ISSUE THREAD

**Issue by Ewjjai** [PojavLauncherTeam/PojavLauncher#2032]
### Describe the bug

How to properly scroll up down/left to right in advancement page?  

Not working with specialscrollup/down

What should i do?  

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model:. 
- CPU architecture:.... 
- Android version:..... 
- PojavLauncher version:.
```

**Comment by tiziodcaio** [comment]
I agree, I didn't found a mode to scroll neither

**Comment by Mathias-Boulay** [comment]
two fingers scroll up/down, for right and left I dunno maybe used the virtual mouse

**Comment by Ewjjai** [comment]
> two fingers scroll up/down, for right and left I dunno maybe used the virtual mouse

I didnt understan?

**Comment by Anant132** [comment]
Turn on mouse and press Pri and use virtual mouse to scroll up and down
