### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Szymon64** [PojavLauncherTeam/PojavLauncher#2033]
### Describe the bug

You can't have fashion when I do fashion, it crashes me 

### The log file and images/videos

https://drive.google.com/file/d/1833h3fIdV3dIpnm_EqRmeDPEIGF6J-QP/view?usp=drivesdk

### Steps To Reproduce

```markdown
I have installed the mod. I turned on the pojav launcher and chose the option and install resources, I chose the file and it kicked me
```

### Expected Behavior

I expected it to work and everything would turn out well 

### Platform

```markdown
- Device model: oppo a53
- CPU architecture: Qualcomm SM4250 Ośmiordzeniowy
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
which java runtime is used ?
Also, latestlog.txt is required.

**Comment by Szymon64** [comment]
> which java runtime is used ?
> Also, latestlog.txt is required.

I am already, what is the problem, the problem is rendering the world as I have the field of view set to the minimum, it all works well and if I set one field of view larger, it throws me out of the game 

And the lauchner version is 1.8
