### ISSUE TITLE
Entrar no mundo e crashar

### ISSUE THREAD

**Issue by Kaurhy** [PojavLauncherTeam/PojavLauncher#2036]
### Describe the bug

Toda vez que eu entro num mundo meu jogo crasha pfv resolvam esse erro meu celular é Android 11 sansung a01

### Steps To Reproduce

```markdown
Início um mundo e o jogo fecha
```

### Expected Behavior

Espero que resolvam isso grato:)

### Platform

```markdown
- Device model: a01
- CPU architecture: octa core
- Android version:11 
- PojavLauncher version: mais recente
```

**Comment by ZIONJADEHD505** [comment]
If u don't speak English we can't help😒

**Comment by Irsplayer1** [comment]
In english: my game crash every time i join a world my phone a01 Samsung

**Comment by WesleyVanNeck** [comment]
No latest log this issue will be closed if no response
