### ISSUE TITLE
[BUG] Minecraft Forge 1.17.1 Not Support On PojavLauncher

### ISSUE THREAD

**Issue by tencentgamer2345** [PojavLauncherTeam/PojavLauncher#2037]
### Describe the bug

when I try to play Minecraft Forge 1.17.1 the Game Exited Happens

### The log file and images/videos

![Screenshot_2021-09-16-12-04-07-66](https://user-images.githubusercontent.com/90538355/133552941-b440e341-44ee-4884-8080-9a5a4fd89a7a.jpg)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Launching Minecraft 1.17.1 Forge
3.Game Exited
```

### Expected Behavior

Game Exited

### Platform

```markdown
- Device model:Realme 5
- CPU architecture:aarch64 
- Android version:9
- PojavLauncher version:crocus-v3_openjdk
```

### Anything else?

Hope Can Run Minecraft Forge 1.17.1

**Comment by artdeell** [comment]
No log.

**Comment by tencentgamer2345** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7175186/latestlog.txt)
