### ISSUE TITLE
[NOT A BUG] the moving pad are not the same thing as Minecraft what Android

### ISSUE THREAD

**Issue by Riotlong** [PojavLauncherTeam/PojavLauncher#2040]
### Describe the bug

Got a BUUUUUUUUUUUG AAAAAAAAAAAAH

### The log file and images/videos

![Miles__Tails__Prower_Sonic_and_All-Stars_Racing_Transformed](https://user-images.githubusercontent.com/88624225/133865632-87f905e9-7ce9-4274-b9c2-48a3e5c487fd.png)

### Steps To Reproduce

```markdown
No tips today
```

### Expected Behavior

No

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Starting Windows...

**Comment by khanhduytran0** [comment]
*looks like you think we can read your brain*

**Comment by herzokun** [comment]
Wtf

**Comment by ghost** [comment]
Invalid issue moment

**Comment by herzokun** [comment]
Riotlong who are you my copy pfp man

**Comment by ghost** [comment]
![Adobe_Post_20210918_0731530 8283329992238021](https://user-images.githubusercontent.com/46363050/133866058-508571e7-ea23-4b06-b553-a9def1984a6d.jpg)

**Comment by ghost** [comment]
> Riotlong who are you my copy pfp man

Imagine its u alt

**Comment by herzokun** [comment]
Nope I'm not alt

**Comment by ghost** [comment]
> Nope I'm not alt

:ban:

**Comment by ghost** [comment]
Lock conversation eta when? @khanhduytran0

**Comment by ghost** [comment]
> Lock conversation eta when? @khanhduytran0

*Creates new issue to talk about tails*
