### ISSUE TITLE
[BUG] migrate account cant login

### ISSUE THREAD

**Issue by nanash1miraa** [PojavLauncherTeam/PojavLauncher#2041]
### Describe the bug

Migrate account cant login

### The log file and images/videos

![Screenshot_2021-09-18-11-22-24](https://user-images.githubusercontent.com/87407875/133870914-d470d98a-575e-42e0-830d-702b6c990752.jpg)

### Steps To Reproduce

```markdown
Launch pojavlauncher
Login account
And this happen
```

### Expected Behavior

I wish i can login 

### Platform

```markdown
- Device model: pixel 3a
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

No

**Comment by ghost** [comment]
Check ur internet connection

**Comment by nanash1miraa** [comment]
> 檢查您的互聯網連接

Always connected

**Comment by Henryminecraft101** [comment]
https://login.live.com/oauth20_authorize.srf?client_id=00000000402b5328&response_type=code&scope=service%3A%3Auser.auth.xboxlive.com%3A%3AMBI_SSL&redirect_url=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf  why it always wrong

**Comment by Henryminecraft101** [comment]
HTTPS..://login.live.com/oauth20_authorize.srf?client_id=00000000402b5328&response_type=code&scope=service%3A%3Auser.auth.xboxlive.com%3A%3AMBI_SSL&redirect_url=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf

**Comment by mestremario3** [comment]
Eu migrei e deu certo. olhe a sua conexao

**Comment by nanash1miraa** [comment]
@LegacyGamerHD  why???

**Comment by nanash1miraa** [comment]
> Eu migrei e deu certo。olhe a sua conexao

It always  appear this 
![Screenshot_2021-09-19-12-35-42](https://user-images.githubusercontent.com/87407875/133915632-35ebe638-03a7-4998-8e3c-3852cb92f2ee.jpg)
![Screenshot_2021-09-19-12-35-37](https://user-images.githubusercontent.com/87407875/133915633-bbc180d8-8c4f-49e9-bd1b-ad347ea36acc.jpg)
![Screenshot_2021-09-19-12-35-30](https://user-images.githubusercontent.com/87407875/133915634-815f5941-44f0-46ba-be40-6eb6f9a4d803.jpg)

**Comment by khanhduytran0** [comment]
~~maybe China blocked Microsoft server, VPN moment~~

**Comment by nanash1miraa** [comment]
> ~也許中國封鎖了微軟服務器，VPN時刻~

Sorry? I live in Taiwan
