### ISSUE TITLE
Game crashes if i allocate more than 256mb

### ISSUE THREAD

**Issue by Pplover123** [PojavLauncherTeam/PojavLauncher#2042]
### Describe the bug

Whenever i try to load pojav launcher on any version my game crashes if i allocate more ram than 300 mb it took me 2 weeks to fighure out why my game was crashing everytime it was because default is 938 mb this makes mh game lag so much i even tried different JVM agreements but it does not increase fps 

### Steps To Reproduce

```markdown
I dont really know if its just with my device but on my other phone pojav launcher does not crash with full ram allocated but i would like if this bug gets fixed
```

### Expected Behavior

I expected the game to run minecraft instead of saying game exited

### Platform

```markdown
- Device model: Vivo Y55s
- CPU architecture: ARMv7 processor rev4 (v7l)
- Android version: 6.0.1
- PojavLauncher version: crocus-63-eb24f052e-v3_openjdk
```

**Comment by nanash1miraa** [comment]
Ur Android version is not latest

**Comment by Pplover123** [comment]
> Ur Android version is not latest

It is i havent got any updates my other phone is android 5 but it works smoothly without crashing even if i allocate all the ram

**Comment by nanash1miraa** [comment]
> > 你的安卓版本不是最新的
> 
> 我沒有得到任何更新，我的另一部手機是 android 5，但即使我分配了所有內存，它也能順利運行而不會崩潰

sell the phone

**Comment by Pplover123** [comment]
> > > 你的安卓版本不是最新的
> > 
> > 
> > 我沒有得到任何更新，我的另一部手機是 android 5，但即使我分配了所有內存，它也能順利運行而不會崩潰
> 
> sell the phone

Uhmmmm why? It was bought on 2019 december its not even old and it works fine

**Comment by Mathias-Boulay** [comment]
Device specific issue that cannot be solved 🤔
