### ISSUE TITLE
[F-Req] Ely.by Accounts

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2043]
### Is this request related to a bug?

No, this isn't related to a bug.

### Describe the request.

I would want ely.by account support.

About ely.by:

Ely.by is an alternative authorization for minecraft.

Ely.by information:
Website: https://ely.by
Documentation: (Maybe usefull)
[Skin System](https://docs.ely.by/en/skins-system.html)
[Authorization for minecraft](https://docs.ely.by/en/minecraft-auth.html)
[Authorization for sites](https://docs.ely.by/en/oauth.html)
[API (russian)](https://docs.ely.by/en/api.html)

### Anything else?

No, nothing else.

**Comment by ajit850** [comment]
It is safe or not?

**Comment by CriticalRange** [comment]
It supports piracy and thus, it will not be supported by PojavLauncherTeam

**Comment by netkv** [comment]
yeah piracy bad

**Comment by saintmaximus1** [comment]
piracy good

**Comment by alexytomi** [comment]
> piracy good

Please pay us $200k in legal fees then

**Comment by AzafeTailscale** [comment]
i want the ely.by 👍
