### ISSUE TITLE
1.15.2 with OptiFine crash (2 gb ram phone)

### ISSUE THREAD

**Issue by BladeTGP** [PojavLauncherTeam/PojavLauncher#2044]
### Describe the bug

This bug is sh!t 

### Steps To Reproduce

```markdown
1- I cleaned my memory but still crash
2- I tried change the ram
3- bullsh!t
```

### Expected Behavior

Everything worked fine, until it started to crash

### Platform

```markdown
- Device model: Samsung J7 neo
- CPU architecture: 32bits
- Android version: 9
- PojavLauncher version: latest
```

### Anything else?

When I play ANY VERSION with OptiFine,wow crash

**Comment by BladeTGP** [comment]
This is my log ---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 18-09-2021 15:07
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cub.u(SourceFile:225)
	at cub.c(SourceFile:264)
	at org.lwjgl.glfw.GLFWWindowSizeCallback$Container.invoke(GLFWWindowSizeCallback.java:80)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1196)
	at cub.l(SourceFile:425)
	at cub.c(SourceFile:283)
	at cvi.b(SourceFile:1023)
	at cvi.d(SourceFile:976)
	at cvi.b(SourceFile:411)
	at net.minecraft.client.main.Main.main(SourceFile:154)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14
	Operating System: Linux (arm) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 172250984 bytes (164 MB) / 375062528 bytes (357 MB) up to 375062528 bytes (357 MB)
	JVM Flags: 3 total; -Xms369M -Xmx369M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar
	Launched Version: 1.14
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 8x null

**Comment by netkv** [comment]
so its 1.15 or 1.14 bruh, issue name says 1.15 but log 1.14
iirc 1.14 is known for having some issues idk

**Comment by netkv** [comment]
also send latestlog.txt, not that minecraft log thing you sended

**Comment by ZIONJADEHD505** [comment]
Bruhhhh it works fine for me on 2gb ram and 32bits

**Comment by ZIONJADEHD505** [comment]
Bruh your ram try allocating more

**Comment by BladeTGP** [comment]
So the problem is that all versions 1.12+ crash, including OptiFine, I'll send my latest log with 1.15.2

**Comment by BladeTGP** [comment]
I try,but pojavlauncher eat all of my memory XD

**Comment by ZIONJADEHD505** [comment]
Me too

**Comment by ZIONJADEHD505** [comment]
I just downloaded Mc on my laptop

**Comment by ZIONJADEHD505** [comment]
Cause pojav eats all of my ram

**Comment by WesleyVanNeck** [comment]
Get at least a 4 gb phone

**Comment by ZIONJADEHD505** [comment]
Ok
