### ISSUE TITLE
[BUG] crash in version minecraft 1.13.2

### ISSUE THREAD

**Issue by ABtreawoptis23** [PojavLauncherTeam/PojavLauncher#2046]
### Describe the bug

I choose video settings and it crashes

### The log file and images/videos

https://user-images.githubusercontent.com/90324849/133911803-16b84ffc-7523-4dd1-a722-83f6b26355ae.mp4

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7190814/latestlog.txt)

### Steps To Reproduce

```markdown
1.start PojavLauncher 
2.start minecraft 1.13.2
3.I choose Java 8 default
4.I choose renderer vgpu
5.I choose video settings and
6.crash :(
```

### Expected Behavior

Please fix :(

### Platform

```markdown
- Device model:Oppo A5 2020
- CPU architecture:aarch64
- Android version:10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I just want to play Minecraft version 1.13.2 please:(

**Comment by GamerYTofficial** [comment]
yes please fix :)

**Comment by WesleyVanNeck** [comment]
works fine for me
