### ISSUE TITLE
[BUG] <渲染错误  Rendering error>

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2047]
### Describe the bug

游玩我的世界1.17.1的时候，变成了这样！以前还不会。
When I visited minecraft 1.17.1, it became like this! Not before.

### The log file and images/videos

![Screenshot_20210918_233802_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/89151134/133914830-218a18d5-215b-4407-88c5-17253eed61f4.jpg)

### Steps To Reproduce

```markdown
1.打开pojavLauncher open pojavLauncher
2.进入游戏 Enter the game
3.进入创建的地图 Enter the created map
4.神奇的一幕发生了！ A magical scene happened！
```

### Expected Behavior

恢复正常Return to normal

### Platform

```markdown
- Device model: HONOR 30 youth
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1248342206
了解更多手机配置请到For more phone configurations, please visit https://www.hihonor.com/cn/products/mobile-phones/honor30lite/spec/
```

**Comment by ZIONJADEHD505** [comment]
What renderer did u use?

**Comment by aaaapai** [comment]
> 您使用了什么渲染器？

最后一个的，不过解决了The last one, but it's solved

**Comment by aaaapai** [comment]
> 您使用了什么渲染器？

现在我使用第三个恢复正常Now I like the third to return to normal
