### ISSUE TITLE
[BUG] Can't change gui scale

### ISSUE THREAD

**Issue by AvionMc** [PojavLauncherTeam/PojavLauncher#2048]
### Describe the bug

I can't change gui scale when im clicking on it when i delete options.txt it says the gui is Large when i click it stuck at Auto and i can't change it (The gui Large is the same to Auto)

### The log file and images/videos

https://youtu.be/bS3w1dwHr14

### Steps To Reproduce

```markdown
1.Launch Minecraft on any versions
2.Go to Videos Settings
3.Click on Gui Scale
```

### Expected Behavior

I tried to click on gui scale it don't change

### Platform

```markdown
- Device model: Redmi 9C NFC 2/32G
- CPU architecture: ARMv8
- Android version:10
- PojavLauncher version: Lastest
```

**Comment by rscDMTalt** [comment]
Hmm.... Try disabling the "Force Unicode font" in the language settings. That might help

**Comment by Mathias-Boulay** [comment]
Resolution too low for minecraft.
