### ISSUE TITLE
[BUG] Can't find .minecraft in games folder

### ISSUE THREAD

**Issue by GlitchyIsTrash** [PojavLauncherTeam/PojavLauncher#2049]
### Describe the bug

Yes, hidden files are on, i tried on every file manager i could find but i still can't find it.

### Steps To Reproduce

```markdown
1. Start launcher
2. Log in with Microsoft account
3. Launching game for a few times in 
 1.16.5 and with optifine (same version)
4. Launch file manager and toggleing on 
 hidden files
5. Try to find .minecraft in games folder to install some resource packs
6. **Fails**
7. Try to find it with search option of the file manager again
8. **Still fails**
```

### Expected Behavior

I expect to find the .minecraft 

### Platform

```markdown
- Device model: Galaxy A70/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release
```

**Comment by ghost** [comment]
Omg bhai

**Comment by thegarykun** [comment]
turn on Hidden Files in your File Browser.

**Comment by ghost** [comment]
Maybe you should use zarchiver

**Comment by QuadSoda69** [comment]
Bruh its not a bug :HYPERROFEL:

**Comment by netkv** [comment]
Due to Google's new scoped storage enforcements added in Android 10 and higher, we are required to move the game directory into an app-private folder.
You can find the new location of the folders in sdcard/Android/data/net.kdt.pojavlaunch/files/ (don't forget to enable "Show hidden folders" in the file manager).

**Comment by QuadSoda69** [comment]
Just turn on show hidden files

**Comment by ghost** [comment]
E

**Comment by thegarykun** [comment]
__and its clearly not a bug__

**Comment by GlitchyIsTrash** [comment]
> turn on Hidden Files in your File Browser.
> Just turn on show hidden files


Did you read properly?

**Comment by ghost** [comment]
The path of pojav on android 10+ is changed

**Comment by netkv** [comment]
> Due to Google's new scoped storage enforcements added in Android 10 and higher, we are required to move the game directory into an app-private folder.
> You can find the new location of the folders in sdcard/Android/data/net.kdt.pojavlaunch/files/ (don't forget to enable "Show hidden folders" in the file manager).

@GlitchyIsTrash read

**Comment by GlitchyIsTrash** [comment]
> > Due to Google's new scoped storage enforcements added in Android 10 and higher, we are required to move the game directory into an app-private folder.
> > You can find the new location of the folders in sdcard/Android/data/net.kdt.pojavlaunch/files/ (don't forget to enable "Show hidden folders" in the file manager).
> 
> @GlitchyIsTrash read

Already read and don't have any sdcard i don't know if i'm just dum please explain jow if i don't have a sd card

**Comment by netkv** [comment]
ok and? its sdcard/Android/data/net.kdt.pojavlaunch/files/  anyways

**Comment by NotAHero04** [comment]
/sdcard is a symlink to /storage/emulated/0 if you didn’t know.

**Comment by netkv** [comment]
~~also why is this labeled as bug when it isnt bug bruh~~

**Comment by GlitchyIsTrash** [comment]
there was two options i between bug and feature i chose bug leave me alone
![Screenshot_20210919-155349_My Files](https://user-images.githubusercontent.com/54434871/133930138-b4cfc6ef-b2c6-4b97-b44a-c9fabfcafa9c.png)
 I don't  use github often idk what to use sorry if i'm stupid

**Comment by GlitchyIsTrash** [comment]
Thanks for trying to help i guess i'll just go fuck myself then

**Comment by netkv** [comment]
lmao use total commander

**Comment by GlitchyIsTrash** [comment]
Found it thank you for all the help guys
