### ISSUE TITLE
Salwyrr Client

### ISSUE THREAD

**Issue by SMOKIEisBack** [PojavLauncherTeam/PojavLauncher#2051]
### Is this request related to a bug?

I want to use salwyrr client in Pojavlauncher i can't pls solve this issue

**Comment by ghost** [comment]
Stupid. Salwyrr is launcher. Not client

**Comment by ghost** [comment]
You CANT launch launcher on pojav

**Comment by SMOKIEisBack** [comment]
Bruhhh k what else can i do

**Comment by ghost** [comment]
Find other client might work

**Comment by ghost** [comment]
Like labymod or lunar

**Comment by rscDMTalt** [comment]
yo holdup

**Comment by rscDMTalt** [comment]
you can't even install lunar u dumbass

**Comment by ghost** [comment]
> you can't even install lunar u dumbass

Maybe you can. Hehe

**Comment by rscDMTalt** [comment]
HAHAHA DUMBASS 

HOW CAN YOU RUN AN .EXE APPLICATION IN POJAVLAUNCHER 😂😂😂😂😂

**Comment by QuadSoda69** [comment]
Wtf man..

**Comment by ghost** [comment]
Install it to windows and copy the data to android :chillsun:

**Comment by Axoloski** [comment]
:HYPERROFEL:

**Comment by CriticalRange** [comment]
![Screenshot_20210815-163422_PojavLauncher_Minecraft_Java_Edition_for_Android](https://user-images.githubusercontent.com/29708696/133982566-130c2bc0-2663-4929-afe8-d4cb847983e0.png)
It works though...
Join discord server if you can't get it working.

**Comment by CriticalRange** [comment]
> You CANT launch launcher on pojav

Check upper comment
*Laughs demonically*

**Comment by ghost** [comment]
But you cannot play the game right?

**Comment by CriticalRange** [comment]
> But you cannot play the game right?

The aim to run the launcher is to install the files
At least I know it like that

**Comment by SMOKIEisBack** [comment]
Gimme ur discord server link

**Comment by CriticalRange** [comment]
https://discord.gg/pMj6xzsZ here
(Vanity link got expired due to lack of boosts)

**Comment by SMOKIEisBack** [comment]
I am banned from Pojavlauncher server reason because i am 10 i said i was kidding that i am 10 but they banned me😔

**Comment by WesleyVanNeck** [comment]
> I am banned from Pojavlauncher server reason because i am 10 i said i was kidding that i am 10 but they banned me😔

then dont joke about your age

**Comment by herzokun** [comment]
Lmao

**Comment by ghost** [comment]
10yrs old? Seems sus

**Comment by SMOKIEisBack** [comment]
Will u unban me?

**Comment by herzokun** [comment]
:ban:

**Comment by SMOKIEisBack** [comment]
It means u will not

**Comment by CriticalRange** [comment]
Of course they won't

**Comment by Fauzi345** [comment]
> ![Tangkapan Layar_20210815-163422_PojavLauncher_Minecraft_Java_Edition_for_Android](https://user-images.githubusercontent.com/29708696/133982566-130c2bc0-2663-4929-afe8-d4cb847983e0.png) Ini berfungsi ... Bergabunglah dengan server perselisihan jika Anda tidak bisa membuatnya berfungsi

i can't install salwyrr client how to fix this?

**Comment by InfiniXDerg** [comment]
> 
> 
> > ![Tangkapan Layar_20210815-163422_PojavLauncher_Minecraft_Java_Edition_for_Android](https://user-images.githubusercontent.com/29708696/133982566-130c2bc0-2663-4929-afe8-d4cb847983e0.png) Ini berfungsi ... Bergabunglah dengan server perselisihan jika Anda tidak bisa membuatnya berfungsi
> 
> i can't install salwyrr client how to fix this?
just use a PC and copy jar files (IDK if will work, just try)

**Comment by Fauzi345** [comment]
> > > ![Tangkapan Layar_20210815-163422_PojavLauncher_Minecraft_Java_Edition_for_Android](https://user-images.githubusercontent.com/29708696/133982566-130c2bc0-2663-4929-afe8-d4cb847983e0.png) Ini berfungsi ... Bergabunglah dengan server perselisihan jika Anda tidak bisa membuatnya berfungsi
> > 
> > 
> > i can't install salwyrr client how to fix this?
> > just use a PC and copy jar files (IDK if will work, just try)

Can you give me salwyrr client file not jar

**Comment by S0rk-jpg** [comment]
> ![Screenshot_20210815-163422_PojavLauncher_Minecraft_Java_Edition_for_Android](https://user-images.githubusercontent.com/29708696/133982566-130c2bc0-2663-4929-afe8-d4cb847983e0.png) It works though... Join discord server if you can't get it working.

how did you do that mine is in a looping
