### ISSUE TITLE
Error of the mouse 

### ISSUE THREAD

**Issue by AngeNimus320** [PojavLauncherTeam/PojavLauncher#2053]
### Describe the bug

the mouse appears but I do not know how to move even if I press it 

### Steps To Reproduce

```markdown
I don't know what happened I just installed the latest update and when I tried to play I couldn't move the mouse
```

### Expected Behavior

I was hoping to just play but I can't because the mouse doesn't work for me

### Platform

```markdown
- Device model: galaxy j2 core 8.0.1
- PojavLauncher version:crocus_v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
latest release isn't a version. State the version
show video footage of the issue please.

**Comment by AngeNimus320** [comment]
The versión is crocus_v3_openjdk

**Comment by Mathias-Boulay** [comment]
What about the video footage ?

**Comment by Mathias-Boulay** [comment]
Also, the hardware mouse is broken on this version, it has been fixed on dev builds 🤔

**Comment by Mathias-Boulay** [comment]
Still no footage, closing I guess
