### ISSUE TITLE
Pls fix this

### ISSUE THREAD

**Issue by HeinIsTaken** [PojavLauncherTeam/PojavLauncher#2054]
### Describe the bug

Cannot not run latest iris version. 

### Steps To Reproduce

```markdown
1.Download iris shader
2.Iris Shader crashes.
```

### Expected Behavior

I expect the installation to work smoothly. 

### Platform

```markdown
- Device model: OPPO a31 (2015)
- CPU architecture: arm64-v8a armeabi-v7a armeabi
- Android version: 9
- PojavLauncher version: Latest version
```

### Anything else?

Nope

**Comment by khanhduytran0** [comment]
If it’s a mod, see #1948
If it’s a shader, remember that your phone doesn’t have a RTX 3090 GPU to run shaders.
