### ISSUE TITLE
"Cant find any compatible java runtime"

### ISSUE THREAD

**Issue by CobraTecCasper** [PojavLauncherTeam/PojavLauncher#2060]
### Describe the bug

Message is displayed after pressing play.

### The log file and images/videos

![Screenshot_2021-09-22-08-59-31](https://user-images.githubusercontent.com/91207030/134368671-834f0fc0-7ff5-44e5-b9bd-df95e7254a1c.png)
![Screenshot_2021-09-22-08-59-45](https://user-images.githubusercontent.com/91207030/134370783-40178915-0ee2-4123-9f9c-ca626a03a167.png)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Click Play
3. Error occurs
```

### Expected Behavior

I expect to play?

### Platform

```markdown
- Device model: LML713DL
- CPU architecture: ARMv7 Processor rev 4 (v7l)
- Android version: 8.1.0
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

Lol i just wanna play

**Comment by ajit850** [comment]
Use openjdk 17 runtime  you .use jre 8 runtime

**Comment by CobraTecCasper** [comment]
> Use openjdk 17 runtime  you .use jre 8 runtime 

Will try

**Comment by ajit850** [comment]
It is works?

**Comment by ajit850** [comment]
Close this issue

**Comment by CobraTecCasper** [comment]
> It is works?

Installing jdk now

**Comment by ajit850** [comment]
Ok

**Comment by CobraTecCasper** [comment]
> It is works?

How do you turn a .gz file into an executable runtime.

**Comment by ajit850** [comment]
https://pojavlauncherteam.github.io/updates/117.html#known-issues

**Comment by ajit850** [comment]
Go to this website and get jre 17

**Comment by ajit850** [comment]
Get Jre 17 32 bits

**Comment by CobraTecCasper** [comment]
> https://pojavlauncherteam.github.io/updates/117.html#known-issues

Downloading now. Hope this works

**Comment by CobraTecCasper** [comment]
Success. Tysm

**Comment by CobraTecCasper** [comment]
Now running into this issue after game booted up and crashed. No crash logs.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by ajit850** [comment]
Download assest v0 file and change resources in . minecraft file as shown in link
