### ISSUE TITLE
[BUG] No more than two gigabytes of RAM can be added

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2061]
### Is this request related to a bug?

My phone has twelve gigabytes of RAM, but the game only uses two gigabytes of RAM, while the other four gigabytes are free, and this has caused a lot of crashes and lag in the game.

**Comment by ghost** [comment]
![IMG_۲۰۲۱۰۹۲۳_۱۲۵۵۴۷](https://user-images.githubusercontent.com/90418723/134484003-480ffdd8-9ae2-4d5c-ba1c-f7c54aa3ea82.jpg)

**Comment by rscDMTalt** [comment]
First, i think you have a 32BIT device

Second, it's impossible that you have 12GB of RAM. That 12GB of RAM you're talking about is probably ROM, your internal storage.

**Comment by WesleyVanNeck** [comment]
open issue and fill the template

**Comment by CriticalRange** [comment]
> First, i think you have a 32BIT device
> 
> Second, it's impossible that you have 12GB of RAM. That 12GB of RAM you're talking about is probably ROM, your internal storage.

32bit devices can't allocate more than a gigabyte, if so game will crash
And yeah i agree the fact that he thinks he has 12gb ram :pepekek:

**Comment by khanhduytran0** [comment]
@MohammadRTX state your device model moment ![kekw_troll](https://cdn.discordapp.com/emojis/886458189711831120.png)
