### ISSUE TITLE
1.17 optifine patches doesn't work with me

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#2062]
### Describe the bug

it's says this access denied idk why?
also if I tried to do the same thing in 1.17 build its crash the app so I used the Google play build

### The log file and images/videos

![Screenshot_20210923_132546_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/134492456-21b2670d-eaaa-48db-b51b-5318f36f4d6c.jpg)

### Steps To Reproduce

```markdown
1.start Pojav
2.Install optifine for 1.17.1
3. install the patch 1. 17 thing
4.it's should say patch 1.17!
```

### Expected Behavior

it's should work

### Platform

```markdown
- Device model: Huawei Nova 3i
- CPU architecture: 8
- Android version: 9
- PojavLauncher version: Google Play Build
```

**Comment by EnderBrine99FOX** [comment]
I deleted the Pojavlauncher folder and did the same thing and it's still happening
@khanhduytran0

**Comment by khanhduytran0** [comment]
You need to update to latest Play Store release or move the patcher to PojavLauncher directory before run it.

**Comment by EnderBrine99FOX** [comment]
I updated My Pojav but 

https://user-images.githubusercontent.com/79517194/134495007-5593c2c4-1bf8-4a4e-8a34-0adf088fabf1.mp4

can I modify it by myself?

**Comment by khanhduytran0** [comment]
Java 8 needs to be set as default for mod installer.

**Comment by ghost** [comment]
Where to get the download link bruh

**Comment by EnderBrine99FOX** [comment]
![Screenshot_20210923_142339_net kdt pojavlaunch](https://user-images.githubusercontent.com/79517194/134498911-8014a899-8e6e-4c7a-9c00-70c1eade7c22.jpg)
Thank you! now it's work!

**Comment by tencentgamer2345** [comment]
how come let me know?

**Comment by ajit850** [comment]
How to install optifine 1.17.1
