### ISSUE TITLE
One questions

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#2063]
### Is this request related to a bug?

No

### Describe the request.

What is optifine patch
I see this in this issue
https://github.com/PojavLauncherTeam/PojavLauncher/issues/2062

**Comment by CriticalRange** [comment]
You can find about patching 1.17+ optifine in discord server!

**Comment by ajit850** [comment]
Give me like

**Comment by CriticalRange** [comment]
https://discord.gg/bqbG6ReS

> Give me like

**Comment by ZIONJADEHD505** [comment]
OK ima discord
