### ISSUE TITLE
[BUG] Optifine 1.17.1 Cannot Be Installed

### ISSUE THREAD

**Issue by tencentgamer2345** [PojavLauncherTeam/PojavLauncher#2064]
### Describe the bug

When I try to install Optifine 1.17.1 Cannot Install Patch Error

### The log file and images/videos

![Screenshot_2021-09-23-23-48-34-97](https://user-images.githubusercontent.com/90538355/134605408-0978d0e9-260c-4f08-9430-0cd4e71b6f19.jpg)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Install Optifine 1.17.1
3.Optifine Cannot Be Installed
4.Patch Error No Such File
```

### Expected Behavior

Hopefully Optifine Can Run

### Platform

```markdown
- Device model: Realme 5
- CPU architecture:aarch64
- Android version:9
- PojavLauncher version:crocus-v3_openjdk
```

**Comment by tencentgamer2345** [comment]
Please Help @khanhduytran0

**Comment by khanhduytran0** [comment]
Make sure that you have installed OptiFine correctly. Check if the client jar is corrupt or not.

**Comment by ajit850** [comment]
I also have this question

**Comment by tencentgamer2345** [comment]
https://user-images.githubusercontent.com/90538355/134607955-be6cb7b7-a39f-4d72-a22d-c42a44c3287b.mp4 @khanhduytran0

**Comment by ZIONJADEHD505** [comment]
Bruh always crash on me
