### ISSUE TITLE
The File Isnt Showing Up In Android/Data Or Games

### ISSUE THREAD

**Issue by elsplash** [PojavLauncherTeam/PojavLauncher#2065]
### Describe the bug

No

### The log file and images/videos

It's Not Showing Up How Should I Put It Though.

### Steps To Reproduce

```markdown
Just Put It With A . In First Or Try Again Please.
```

### Expected Behavior

File Shows Up

### Platform

```markdown
- Device model: SM-T295
- CPU architecture: Intol
- Android version: Android 11
- PojavLauncher version: Latest Version
```

### Anything else?

I Already Said It The File Isnt Showing Up

**Comment by WesleyVanNeck** [comment]
Intol isn't a architecture
