### ISSUE TITLE
Cant find .minecraft folder

### ISSUE THREAD

**Issue by MCorange99** [PojavLauncherTeam/PojavLauncher#2068]
Ive looked in games/pojavlauncher, in android/data/net.pojavlaucher/

And ive turned on show hidden files.
Ive even tried a 3rd party file browser.

Im using samsung A71 phone.

**Comment by khanhduytran0** [comment]
fill the template moment <a:frvibecheck:866254426850721804>

how to access:
https://media.discordapp.net/attachments/824307242533781514/888286642874499122/video0.mp4
