### ISSUE TITLE
Can't join servers

### ISSUE THREAD

**Issue by skandabhairava** [PojavLauncherTeam/PojavLauncher#207]
I am not able to join servers (hosted on server.pro/stereos/etc)

Also I seem to be running on offline mode... I can't view my skin...

Wait... Does this support only till MC 1.11?? 
It's still good for
...

![Screenshot_20200516-214633_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/58636952/82126371-eb4af400-97c9-11ea-938e-4b3aa673e569.jpg)

- release 2.5 preview 1
- Minecraft version 1.8.8
- CPU : 8x ARMv8 Processor rev 4
- Android 9

**Comment by khanhduytran0** [comment]
> I am not able to join servers (hosted on server.pro/stereos/etc)

Some server with encryption that not supported by Android/ART can't be pinged and joined. 

> Also I seem to be running on offline mode... I can't view my skin...

I can't fix it but some other users see their skin.

> Wait... Does this support only till MC 1.11?? 

Yes only with v2.

**Comment by skandabhairava** [comment]
> > I am not able to join servers (hosted on server.pro/stereos/etc)
> 
> Some server with encryption that not supported by Android/ART can't be pinged and joined.
> 
> > Also I seem to be running on offline mode... I can't view my skin...
> 
> I can't fix it but some other users see their skin.
> 
> > Wait... Does this support only till MC 1.11??
> 
> Yes only with v2.

Ok then :)... Go ahead with the project... I would love more updates
