### ISSUE TITLE
[BUG] <Short description>Android 11 no use mod

### ISSUE THREAD

**Issue by Siejhebehc7** [PojavLauncherTeam/PojavLauncher#2070]
### Describe the bug

Android 11 10 not wroking use mod?bug

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: samsung as10
- CPU architecture: pvr
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

.

**Comment by khanhduytran0** [comment]
Fill the template or this issue will be rejected.
