### ISSUE TITLE
[BUG] Unable to resolve host login.live.com  associated with hostname

### ISSUE THREAD

**Issue by nanash1miraa** [PojavLauncherTeam/PojavLauncher#2071]
### Describe the bug

sometimes i can't login but today it always can't login and show this

### The log file and images/videos

![Screenshot_2021-09-25-10-19-58](https://user-images.githubusercontent.com/87407875/134754686-4e708208-22b0-4074-83e9-0846130014ae.jpg)
![Screenshot_2021-09-25-10-19-51](https://user-images.githubusercontent.com/87407875/134754688-7e302339-6101-4029-8671-a82b033b2fab.jpg)

### Steps To Reproduce

```markdown
Launch pojavlauncher
Click Microsoft login 
And it say
Error
Unable to resolve host login.live.com  associated with hostname
```

### Expected Behavior

I wish i can login and play 

### Platform

```markdown
- Device model:pixel 3a
- CPU architecture:aarch64
- Android version:11
- PojavLauncher version:crocus_v3_openjdk
```

### Anything else?

No

**Comment by nanash1miraa** [comment]
unable to resolve host login.live.com 
no address associated with hostname
Is full and i write wrong

**Comment by ZIONJADEHD505** [comment]
I can't login too with my tlauncher acc

**Comment by khanhduytran0** [comment]
> I can't login too with my tlauncher acc

We have never said that PojavLauncher supports TLauncher account.

**Comment by khanhduytran0** [comment]
> unable to resolve host login.live.com 
> 
> no address associated with hostname
> 
> Is full and i write wrong

Check your internet connection and your internet provider.

**Comment by nanash1miraa** [comment]
> > 無法解析主機 login.live.com
> > 沒有與主機名關聯的地址
> > 已滿，我寫錯了
> 
> 檢查您的互聯網連接和您的互聯網提供商。

Always connected

**Comment by nanash1miraa** [comment]
![Screenshot_2021-09-25-10-55-47](https://user-images.githubusercontent.com/87407875/134755622-c1ab1cfa-20b2-4232-8b5f-a6c545e8a792.jpg)
![Screenshot_2021-09-25-10-56-07](https://user-images.githubusercontent.com/87407875/134755624-d0bcbae8-ea30-4beb-967b-1893b7ed2f01.jpg)
Edge and chrome

**Comment by nanash1miraa** [comment]
> 供 
All check no problems

**Comment by khanhduytran0** [comment]
you know, china banned stuff, so use vpn or offline moment.

**Comment by nanash1miraa** [comment]
> 你知道，中國禁止的東西，所以使用 vpn 或離線時刻。

Thanks bro it work 🙂
