### ISSUE TITLE
[BUG] Unknown Crash

### ISSUE THREAD

**Issue by Pro-Fessional18** [PojavLauncherTeam/PojavLauncher#2072]
### Describe the bug

After pressing play button it immediately crashed

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7229125/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start pojav launcher
2.Press play button
```

### Expected Behavior

I expect the game to lunch

### Platform

```markdown
- Device model: Huawei Med-L29
- CPU architecture: 32-bit/x86
- Android version: Android 10
- PojavLauncher version: crucus-70-103aba6f6-v3_openjdk
```

**Comment by nanash1miraa** [comment]
Download the new version
Or ur cpu not support

**Comment by nanash1miraa** [comment]
Download the crocus_v3_openjdk version

**Comment by Mathias-Boulay** [comment]
we have quite a a lot of random issues with x86 processors.

**Comment by JohnPrinceDugan** [comment]
Its because your phone is aarch32 it only works on aarch64

**Comment by khanhduytran0** [comment]
> Its because your phone is aarch32 it only works on aarch64

You didn’t know that you just self-replied to your issue (#2077)

**Comment by khanhduytran0** [comment]
> we have quite a a lot of random issues with x86 processors.

actually not, the log says that 
> <ins>jdk17</ins>-<ins>arm</ins>-20210821-release.tar.xz

- jdk is installed instead of jre, this just eat more storage but do no more thing. Pojav isn’t a Java IDE. jdk: java <ins>development kit</ins>; jre: java **<ins>runtime</ins>** environment
- java 17 support for 32bit support is broken at the moment, stated in the known issue note.

**Comment by khanhduytran0** [comment]
~~or maybe he runs with houdini translation layer?~~
