### ISSUE TITLE
Game Crashing In Start

### ISSUE THREAD

**Issue by elsplash** [PojavLauncherTeam/PojavLauncher#2074]
### Describe the bug

Application/Game Exited Code 1

### The log file and images/videos

--------- beggining with launcher debug Info: LWJGL3 directory: [lwjgl-tinyfd.jar, lwjgl-jemalloc.jar, lwjgl.jar, lwjgl-stb.jar, lwjgl-glfw-classes.jar, lwjgl-openal.jar, version, lwjgl-opengl.jar, jsr305.jar] Architecture: arm64/aarch64 Info: Custom Java arguments: "-Xms384m -Xmx768m" Headless version detected! (20210706) --------- beginning of main I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" unused DT entry: DT_RPATH (type 0xf arg 0x361) (ignoring) I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags) I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x450 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" unused DT entry: DT_RPATH (type 0xf arg 0x33c0) (ignoring) I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags) I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x13b8 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x2196 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" unused DT entry: DT_RPATH (type 0xf arg 0x6a46) (ignoring) I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags) I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x4d9 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" unused DT entry: DT_RPATH (type 0xf arg 0xda0) (ignoring) I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags) I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0xf13 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x2e6 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0xe6 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x119 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsunec.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" unused DT entry: DT_RPATH (type 0xf arg 0x5e6) (ignoring) I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags) I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so success I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" unused DT entry: DT_RPATH (type 0xf arg 0x1c7) (ignoring) I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags) I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" unused DT entry: DT_RPATH (type 0xf arg 0x364) (ignoring) I/jrelog (27042): WARNING: linker: Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags) I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x1d2 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x139 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x1c1 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so in namespace classloader-namespace I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so in namespace classloader-namespace I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x16fe I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success I/jrelog (27042): WARNING: linker: Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" unused DT entry: DT_RPATH (type 0xf arg 0x103) (ignoring) I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags) I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x23a I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsig.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" unused DT entry: DT_RPATH (type 0xf arg 0x6c1) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_xawt.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf arg I/jrelog (27042): 0x6af) (ignoring) I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" unused DT entry: DT_RPATH (type 0xf arg 0x158) (ignoring) I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x8ff I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so I/jrelog (27042): " unused DT entry: I/jrelog (27042): DT_RPATH I/jrelog (27042): (type I/jrelog (27042): 0xf I/jrelog (27042): arg I/jrelog (27042): 0x3f1 I/jrelog (27042): ) (ignoring) I/jrelog (27042): I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so I/jrelog (27042): " has unsupported flags DT_FLAGS_1= I/jrelog (27042): 0x81 I/jrelog (27042): (ignoring unsupported flags) I/jrelog (27042): I/jrelog (27042): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so success I/jrelog (27042): WARNING: linker: I/jrelog (27042): Warning: " I/jrelog (27042): /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so I/jrelog (27042): OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes I/jrelog (27042): Error: A JNI error has occurred, please check your installation and try again I/jrelog (27042): Exception in thread "main" I/jrelog (27042): java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0 I/jrelog (27042): I/jrelog (27042): 	at java.lang.ClassLoader.defineClass1(Native Method) I/jrelog (27042): I/jrelog (27042): 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) I/jrelog (27042): I/jrelog (27042): 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) I/jrelog (27042): I/jrelog (27042): 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) I/jrelog (27042): I/jrelog (27042): 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) I/jrelog (27042): I/jrelog (27042): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) I/jrelog (27042): I/jrelog (27042): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) I/jrelog (27042): I/jrelog (27042): 	at java.security.AccessController.doPrivileged(Native Method) I/jrelog (27042): I/jrelog (27042): 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) I/jrelog (27042): I/jrelog (27042): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) I/jrelog (27042): I/jrelog (27042): 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) I/jrelog (27042): I/jrelog (27042): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) I/jrelog (27042): I/jrelog (27042): 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601) I/jrelog (27042): I/jrelog (27042): Going to free args I/jrelog (27042): Free done Java Exit code: 1

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

What The Normal Game Goes

### Platform

```markdown
- Device model:I Already Told You 
- CPU architecture: Intol
- Android version: 11
- PojavLauncher version: 3.3.1.1
```

### Anything else?

Shut The F*** Up

**Comment by WesleyVanNeck** [comment]
Outdated launcher also intol isn't a architecture also you shut the fuck up

**Comment by WesleyVanNeck** [comment]
Also trying to run Minecraft 1.17 and older on java 8
