### ISSUE TITLE
[BUG] “Can’t login a demo Account!”

### ISSUE THREAD

**Issue by xRyannn** [PojavLauncherTeam/PojavLauncher#2076]
### Describe the bug

I have owned minecraft since 2013, tried logging in on my chrome book (since my PC broke) with Pojav however I can’t log in. No matter what the launcher insists that my account is a demo account. It definitely  isn’t. What do I do? 

### Steps To Reproduce

```markdown
Log in
```

### Expected Behavior

I expect the game to mf log me in 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by CriticalRange** [comment]
Maybe you have the bedrock edition instead of Java ?

**Comment by xRyannn** [comment]
> Maybe you have the bedrock edition instead of Java ?

I do not have the bedrock edition.

**Comment by EnderBrine99FOX** [comment]
> ### Describe the bug
> I have owned minecraft since 2013, tried logging in on my chrome book (since my PC broke) with Pojav however I can’t log in. No matter what the launcher insists that my account is a demo account. It definitely isn’t. What do I do?
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> Log in
> ```
> 
> ### Expected Behavior
> I expect the game to mf log me in
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:
> ```
> 
> ### Anything else?
> _No response_

try to link your account with Microsoft account since now every Java Edition account is Microsoft account

**Comment by Zennn123** [comment]
Huh

**Comment by Chicken-676** [comment]
Please add Gmail account in pojavLauncher .Thank you

**Comment by khanhduytran0** [comment]
> Please add Gmail account in pojavLauncher .Thank you

Unfortunately, we aren’t Microsoft, so basically we can’t do that. You may contact Microsoft for your “add Gmail account” request to Minecraft Launcher first. :trollface:
