### ISSUE TITLE
[BUG] лаунчер не устанавливается 

### ISSUE THREAD

**Issue by ivan2282-i28** [PojavLauncherTeam/PojavLauncher#2079]
### Describe the bug

Пишет программа не установлина

### Steps To Reproduce

```markdown
Запускают инсталлятор устанавливается и пишет не установлено
```

### Expected Behavior

Основан должен установится

### Platform

```markdown
- Device model: ASUS ZenPad p001
- CPU architecture: 
- Android version: 5.0
- PojavLauncher version: последний рилиз
```

**Comment by ajit850** [comment]
Please tell in English

**Comment by Mathias-Boulay** [comment]
Version not stated, last release isn't a version.
Also, outdated android device 🤔
