### ISSUE TITLE
versions from 1.15 onwards error occurs

### ISSUE THREAD

**Issue by antonio6669** [PojavLauncherTeam/PojavLauncher#208]
I pasted the error in del.dog for better viewing

https://del.dog/Minecraft1152error.txt
This error occurs in V2 preview 1 

My device is a:
Redmi note 6 pro

**Comment by khanhduytran0** [comment]
V2 does not support 1.12 and above.

**Comment by antonio6669** [comment]
Okay thanks I'll try to use the V3  ^^

**Comment by khanhduytran0** [comment]
```
Better to put in
``` code ```

Instead of upload file.
```

**Comment by antonio6669** [comment]
Okay, I will do this next time

**Comment by khanhduytran0** [comment]
V3 will not work anything, it is still in development.

**Comment by antonio6669** [comment]
Okay, thanks for the info and help

I hope the project continues ^^
