### ISSUE TITLE
[BUG] No Sound And No Menu

### ISSUE THREAD

**Issue by okebahsv** [PojavLauncherTeam/PojavLauncher#2080]
### Describe the bug

The Menu Is Blank And Volume is 100 But no Sounds

### The log file and images/videos

Hb

### Steps To Reproduce

```markdown
Pleaseeeee fix thisss
```

### Expected Behavior

The pojav launcher is gone

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No

**Comment by WesleyVanNeck** [comment]
Not a anough info

**Comment by okebahsv** [comment]
> Not a anough info

Fuckkk youuu bitchhhh

**Comment by khanhduytran0** [comment]
@okebahsv *imagine expecting everything to work without fully download assets*

**Comment by WesleyVanNeck** [comment]
> > Not a anough info
> 
> Fuckkk youuu bitchhhh

Baned of repo have fun

**Comment by CriticalRange** [comment]
> > > Not a anough info
> > 
> > 
> > Fuckkk youuu bitchhhh
> 
> Baned of repo have fun

You did the best thing (not arguing and simply banning)
