### ISSUE TITLE
I can't login on 1.17.1

### ISSUE THREAD

**Issue by 19383829298338** [PojavLauncherTeam/PojavLauncher#2083]
### Describe the bug

![Screenshot_20211001-195409_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/91743379/135637295-7447cc26-1a9d-4baf-b22c-93912589ac51.jpg)

### Steps To Reproduce

```markdown
1. Start the game with Microsoft login.
2. I try to join with 1.17.1 then the bug appears and not letting me join.
```

### Expected Behavior

I except for the game to launch in 1.17.1

### Platform

```markdown
- Device model: Samsung
- CPU architecture: 
- Android version: latest
- PojavLauncher version: latest
```

**Comment by ajit850** [comment]
This is not login problem your cpu architecture not supported to runtime pack .

**Comment by 19383829298338** [comment]
I am on mobile?

**Comment by 19383829298338** [comment]
@ajit850 ?

**Comment by khanhduytran0** [comment]
@LegacyGamerHD bruh again closing without explain why

**Comment by khanhduytran0** [comment]
@19383829298338 *are you expecting 1.17+ to work with just java 8?*

**Comment by 19383829298338** [comment]
@khanhduytran0 how do I know my version.
And if it's below is there a way to upgrade it or play 1.17?

**Comment by LegacyGamerHD** [comment]
> @LegacyGamerHD bruh again closing without explain

**Comment by khanhduytran0** [comment]
follow https://pojavlauncherteam.github.io/updates/117.html
Minecraft 1.17+ requires Java 16 or higher.

**Comment by Mathias-Boulay** [comment]
Since the answer has been given, we can safely close the issue
