### ISSUE TITLE
[BUG] <Short description> Why can't my Pojav launcher scroll down?

### ISSUE THREAD

**Issue by HafizGan** [PojavLauncherTeam/PojavLauncher#2084]
### Describe the bug

Why exit with code 1

### The log file and images/videos

[BUG] <Short description> Why can't my Pojav launcher scroll down?

### Steps To Reproduce

```markdown
Yes, where is it?
```

### Expected Behavior

So that I can scroll down again

### Platform

```markdown
- Device model: Vivo y12s 3/32
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus3D_opendjk
```

### Anything else?

Nothing, that's just a bug, that's why can't Scroll down
Pojav launcher, please ### _****_

**Comment by HafizGan** [comment]
Help

**Comment by HafizGan** [comment]
Help

**Comment by HafizGan** [comment]
I'm also like that

**Comment by ajit850** [comment]
Please send video

**Comment by ajit850** [comment]
I don't have this problem

**Comment by Blimyst** [comment]
Yeah, it is just happened on me too (on any direction)

**Comment by Mathias-Boulay** [comment]
It can, just use two fingers.
We might revert the change in the future
