### ISSUE TITLE
I cannot login an online account it shows error 403 [BUG] <Short description>

### ISSUE THREAD

**Issue by MINJA762** [PojavLauncherTeam/PojavLauncher#2086]
### Describe the bug

When I know that we will login as online but when I tried it shows error 403 so Pls fix this  #problem. #2085 

### Steps To Reproduce

```markdown
Start pojav launcher and put email and password and login it shows error 403
```

### Expected Behavior

I request that this bug is fixed as fastest as can

### Platform

```markdown
- Device model: android 
- CPU architecture: Mali 350
- Android version: 11
- PojavLauncher version:3.3.1
```

### Anything else?

No but fix it fast

**Comment by WesleyVanNeck** [comment]
How about we don't fix it fast also no error or latestlog.txt

**Comment by WesleyVanNeck** [comment]
This issues will be terminated if no log or error or no respond

**Comment by khanhduytran0** [comment]
@MINJA762 do you use NFA/SFA?

**Comment by khanhduytran0** [comment]
@MINJA762 *you tell to fix it fast but you don't respond fast?*

**Comment by Protokollll** [comment]
Hmm

**Comment by nullAmar** [comment]
CAN I GET AN ACCOUNT

**Comment by khanhduytran0** [comment]
> CAN I GET AN ACCOUNT 

You can create unlimited Microsoft accounts for free, then you can play the demo mode **for free** aswell.

**Comment by nullAmar** [comment]
how


في الثلاثاء، ٩ نوفمبر، ٢٠٢١ ١:٣٩ ص Duy Tran Khanh ***@***.***>
كتب:

**Comment by herzokun** [comment]
Wtf man

**Comment by nullAmar** [comment]
استغفر الله


في الثلاثاء، ٩ نوفمبر، ٢٠٢١ ١:٥٥ ص Izzat ***@***.***> كتب:

**Comment by herzokun** [comment]
Bruh u fucking scammed me

**Comment by herzokun** [comment]
Huh so your a Arab talking

**Comment by nullAmar** [comment]
ماشي

في الثلاثاء، ٩ نوفمبر، ٢٠٢١ ٢:٠٣ ص Izzat ***@***.***> كتب:

**Comment by GlossyPiglan** [comment]
Pls support pojav launcher for fa account

**Comment by ghost** [comment]
What's your discord username?

**Comment by nullAmar** [comment]
I don't have one yet.

‫في الأربعاء، 8 ديسمبر 2021 في 1:42 م تمت كتابة ما يلي بواسطة ‪Agent‬‏ <‪
***@***.***‬‏>:‬

**Comment by Jeet9898** [comment]
I can't login from nfa acc error code 403

**Comment by InfiniXDerg** [comment]
> I can't login from nfa acc error code 403

Pirate huh?
Go and buy One, is Not fucking expensive
https://minecraft.net

**Comment by Shisuuus** [comment]
> 

Mejor compro 2 hrs de tu mama es mas barato

**Comment by InfiniXDerg** [comment]
Translation for the english Users
Better buy 2 hours of your mom is cheaper

My response to you is this:  
![you-are-idiot](https://user-images.githubusercontent.com/75786233/161685938-9bf4a460-1232-4335-a921-722263b102da.gif)

**Comment by MRGAMERZ01** [comment]
Respond error 404 kyu ha rha ha
