### ISSUE TITLE
1.17 cant find complement java runtime 

### ISSUE THREAD

**Issue by Aadarsh731** [PojavLauncherTeam/PojavLauncher#2087]
### Describe the bug

The thing is that I can't play 1.17 it says can't find complement java runtime I have searched on YouTube but it didn't work.!!

### The log file and images/videos

...

### Steps To Reproduce

```markdown
..
```

### Expected Behavior

I expected to launch the game

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ZIONJADEHD505** [comment]
Bro what phone/tablet do you have
What aarch is your phone/tablet

**Comment by khanhduytran0** [comment]
@Aadarsh731 *i see your attempt to play 1.17 with java 8*
