### ISSUE TITLE
Hi everyone i want to disable some mods on one of my mapp please tell me how to do it my version is 1.16.1

### ISSUE THREAD

**Issue by darksoulq** [PojavLauncherTeam/PojavLauncher#2089]
Legacy gamer hd since only u reply please tell me how to disable or enable mods noT using templlates i dont think templates are posible anyway in java 1.16.1

**Comment by khanhduytran0** [comment]
What we mean is <ins>issue template</ins>, not “mod template”. Use GitHub web to fill into it.
