### ISSUE TITLE
3.0.1 pre5

### ISSUE THREAD

**Issue by MansaceBall** [PojavLauncherTeam/PojavLauncher#209]
It kept on giving me error when I tried open a version.

**Comment by khanhduytran0** [comment]
V3 is not usable at the moment.

**Comment by MansaceBall** [comment]
Could you update it so it would work properly with not as many errors?
That'd be great:)

**Comment by khanhduytran0** [comment]
Fixing may takes a lot of times so you may need to wait and back to v2.

**Comment by MansaceBall** [comment]
OK. I'll wait. just remind me for an update. Thank you.
