### ISSUE TITLE
Maybe A Better Controller

### ISSUE THREAD

**Issue by JohnPrinceDugan** [PojavLauncherTeam/PojavLauncher#2090]
### Describe the request.

The Controller Is not Very styilish and its very hard to control and where is the zoom button see what I Mean

### Anything else?

Very Hard to Control

**Comment by khanhduytran0** [comment]
> Controller Is not Very styilish

By making it more "stylish", it will gonna eat more VRAM (read: Video RAM, not memory RAM) which will affect the game performance a lot.

> where is the zoom button

*custom control exists for a reason*

> see what I Mean

~~we can't 100% read your brain~~

**Comment by Mathias-Boulay** [comment]
Given our straight stance in it, let's close the issue
