### ISSUE TITLE
1.17.x Optifine doesn't work with fabric even if you patch it

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#2091]
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7286999/latestcrash.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7287000/latestlog.txt)
### Describe the bug

Optifine with fabric loader doesn't work

### The log file and images/videos

![Screenshot_20211005_173631_com mxtech videoplayer ad](https://user-images.githubusercontent.com/79517194/136049590-8698898c-7054-4a84-acac-265bfe5e1a03.jpg)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Play 1.17.1 Fabric
3.Its Should Work?
```

### Expected Behavior

Since the 1.17 OF is patched its should work I guess? 

### Platform

```markdown
- Device model: Huawei Nova 3i
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Latest GP build
```

### Anything else?

No

**Comment by ajit850** [comment]
You need to paste optifine jar in mods folder to run optifine

**Comment by ZIONJADEHD505** [comment]
Bruhhhh choose the latest optifine don't download the preview
That happened to me on my pc

**Comment by EnderBrine99FOX** [comment]
it's actually the latest release G9 and it's still not working

**Comment by NotAHero04** [comment]
I’m looking for a solution. Meanwhile, did you try the **unpatched** fabric with zink?

**Comment by NotAHero04** [comment]
So basically this error is from here (you can find this file at ~/.minecraft/.optifine/<your_optifine_version>
it’s a broken jar file
![A8F918C2-6FA5-47AA-BDCB-AAA5FD90D5B1](https://user-images.githubusercontent.com/84689840/136238910-aabd0922-b224-490d-8f57-a82a6d31daf8.png)

**Comment by NotAHero04** [comment]
it may be fixed by replacing the problematic file with a normal one, which only generates in a normal client

**Comment by Mathias-Boulay** [comment]
#1963 though
Also gplay build has no support for it.
