### ISSUE TITLE
[BUG] Pojavlauncher terminating after joining server

### ISSUE THREAD

**Issue by nosewad** [PojavLauncherTeam/PojavLauncher#2092]
### Describe the bug

application terminates without any errors after joining a server

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7287536/latestlog.txt)

### Steps To Reproduce

```markdown
1. start Pojavlauncher
2. select version (optifine 1.8.9 HD_U_M5)
3. join server
```

### Expected Behavior

I expect Pojavlauncher to not terminate

### Platform

```markdown
- Device model: Oneplus 7t
- CPU architecture: aarch64
- Android version: OxygenOS 11.0.3.1.HD65AA (android 11)
- PojavLauncher version:  crocus-v3_openjdk (latest google play release)
```

**Comment by khanhduytran0** [comment]
didn’t you enable vbo?

**Comment by nosewad** [comment]
> didn’t you enable vbo?

I may have in the past, but currently "use VBOs" is set to off.

**Comment by Mathias-Boulay** [comment]
Pretty sure it has to be enabled 🤔

**Comment by nosewad** [comment]
> Pretty sure it has to be enabled 🤔

OH, all right. i'll enable it and see if that fixes it. Thanks! :D

**Comment by nosewad** [comment]
enabling "use VBOs" has fixed my issue. Thanks, everyone!
