### ISSUE TITLE
[ERROR CODE 1] ERROR WHEN LOGGING IN MINECRAFT

### ISSUE THREAD

**Issue by xxtimurvav** [PojavLauncherTeam/PojavLauncher#2093]
### Describe the bug

Every time i install version there is an error under code 1 on the new version, in no case does it not go to any version! Can you help me?
![Screenshot_2021-10-05-23-17-08-281_net kdt    ###pojavlaunch](https://user-images.githubusercontent.com/91982887/136081182-beff4f59-4363-4a3d-81ac-207cf952e976.jpg)

### Steps To Reproduce

```markdown
I come in PoJavLuncher and launch Minecraft and there is this error!
```

### Expected Behavior

Help would come in handy!If you know how to fix it, please tell me!

### Platform

```markdown
- Device model: Redmi 8A
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest release 3.3.1.1_rel
```

### Anything else?

If you know the answer to this question, please tell me how to solve it, I would be very happy for this help!

**Comment by Mathias-Boulay** [comment]
Unsupported old version
