### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2094]
### Describe the bug

So, I am on a chromebook, and I have been able to sign with the microsoft login button before, so now when I click on it everything works for the most part, but when I click on ANY of the text boxes and start typing, no text appears for some reason. It has worked in the past, but I can only use an offline account for now. Nothing else breaks, the only problem is I can't type in my username and password.

### Steps To Reproduce

```markdown
1 start app
2 click Microsoft Login
3 click on any text box and start typing
nothing will happen
```

### Expected Behavior

I expect text to appear, and the computer to recognize the fact I am typing  

### Platform

```markdown
- Device model: mediatek chromebook
- CPU architecture: I don't know sorry :(
- Android version: 10
- PojavLauncher version: 3.3.1.1_rel_20210206
```

**Comment by ZIONJADEHD505** [comment]
You don't know your arch/bits ill find it for you or

**Comment by Mathias-Boulay** [comment]
Old version, unsupported

**Comment by ghost** [comment]
No, I am in the current version. I am sure of it.
