### ISSUE TITLE
[BUG] No Sound 

### ISSUE THREAD

**Issue by RayZxyo** [PojavLauncherTeam/PojavLauncher#2095]
### Describe the bug

I don't want to talk much.  after i downloaded 1.17.1 there is indeed a sound but the next day the minecraft has no background and no sound has anyone ever experienced this?

### The log file and images/videos

![Screenshot_20211005-184550_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/91876145/136139917-05e548c4-e311-45e1-8368-a96b9daa872c.png)

### Steps To Reproduce

```markdown
Empty
```

### Expected Behavior

Empty

### Platform

```markdown
- Device model: Samsung A50
- CPU architecture: aarch64 
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210206
```

### Anything else?

no

**Comment by ZIONJADEHD505** [comment]
Bro dowdload the full assets before playing the game

**Comment by RayZxyo** [comment]
I did but it's working af

**Comment by RayZxyo** [comment]
I reinstalled and it didn't work ... Delete the launcher data and
reinstall. It worked

**Comment by ZIONJADEHD505** [comment]
OK good

**Comment by RayZxyo** [comment]
What the fuck do you mean bro
