### ISSUE TITLE
Microsoft login won't work

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2096]
### Describe the bug

So basically when I try to login through Microsoft login, I click on a text box and start typing, but no text appears, meaning it is impossible to login. I do have minecraft payed for on another device though. (this is my chromebook) Microsoft login HAS worked in the past on the same device using pojavlauncher.

### Steps To Reproduce

```markdown
1 start app
2 click microsoft login
3 click on a text box
4 type
```

### Expected Behavior

The game should start typing so text can appear and I can login

### Platform

```markdown
- Device model: google mediatek MT8173 chromebook
- CPU architecture: x86_64
- Android version: 10
- PojavLauncher version: Latest
```

**Comment by Mathias-Boulay** [comment]
Latest isn't a version.
State the version or get terminated

**Comment by ghost** [comment]
Never mind I figured it out sorry for wasting your time. ;)

**Comment by Mathias-Boulay** [comment]
Maybe tell how you solved it, so we can keep this as a reference ?
