### ISSUE TITLE
[BUG] Why in 32bit device always lag everytime even it is lower graphics and optifine mode

### ISSUE THREAD

**Issue by NickyisSneaking** [PojavLauncherTeam/PojavLauncher#2097]
### Describe the bug

Can't keep up the processor 

### The log file and images/videos

![Screenshot_20210713_202759_net kdt pojavlaunch](https://user-images.githubusercontent.com/78867050/136297114-81092efc-df62-4bc8-b960-f4bbfc1ed329.jpg)

It runs 6 to 10 fps

### Steps To Reproduce

```markdown
1.start PojavLauncher
2.play any version in optifine or forge and fabric optimizer
3.its still lagging even it is low render distance even with optimizers
```

### Expected Behavior

I expected to play smooth on aarch32 but it is always lagging but in aarch64 it plays smooth please fixed this problem on aarch32 devices

### Platform

```markdown
- Device model:HUAWEI Y6 Pro 2019
- CPU architecture:aarch32
- Android version:9
- PojavLauncher version:3.3.1.1_rel_20210321
```

### Anything else?

Can you please fixed this problem in aarch32 devices

**Comment by khanhduytran0** [comment]
it's a pc game, why do you expect to work at 69fps?

**Comment by NickyisSneaking** [comment]
I expect to 32fps like aarch64 do

**Comment by khanhduytran0** [comment]
but 32bit isnt 64bit

**Comment by khanhduytran0** [comment]
it has limit

**Comment by khanhduytran0** [comment]
check jvm arguments (#668) and check latestlog.txt

**Comment by NickyisSneaking** [comment]
I used the 3gb jvm argument and this happens
![Screenshot_20211007_074252_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/78867050/136298441-5f4ae25b-e8f8-4f90-9d0f-97fa164fdb9b.jpg)

**Comment by Mathias-Boulay** [comment]
Old launcher version, unsupported.
