### ISSUE TITLE
Keyboard and mouse support

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2098]
### Is this request related to a bug?

Not related to a bug

### Describe the request.

It would be marvelous if you guys add a keyboard and mouse support, using an otg connector! I hope you guys would add this feature someday!❤️🥰

**Comment by khanhduytran0** [comment]
I wonder if you have ever
- ~~read the source code~~
- searched for duplicate issue (oldest: #401)
- tried it yourself
![<:woeisfruhh:879989696770486312>](https://cdn.discordapp.com/emojis/879989696770486312.png)

**Comment by CriticalRange** [comment]
What duy meant: There is already support for mouse and keyboard via otg
Pepelaugh

**Comment by ghost** [comment]
Ahh yes there is. But, the mouse movement is laggy, it like... Skips frame rate
