### ISSUE TITLE
我要i want opengl3.2！

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2099]
### Is this request related to a bug?

yes

### Describe the request.

就算不完全兼容openGL3.2，我也要尝试！因为我想用optifine...🤔不过我在optifine那里发出问题，并且有人回答：
Even if it is not fully compatible with OpenGL 3.2, I will try! Because I want to use optifine... But I asked a question at optifine and someone answered:
![Screenshot_20211008_201602_com huawei browser](https://user-images.githubusercontent.com/89151134/136557198-df33c418-03ae-4778-8a71-29504b6c7424.jpg)

我看不明白😓
I don't understand😓      ----------此英文由百度翻译
                   ------This English is translated by Baidu

**Comment by aaaapai** [comment]
别注意我回复他（她）时，却变中文，这是浏览器翻译功能导致的
Don't notice that when I reply to him (her), I change into Chinese, which is caused by the browser translation function

**Comment by NotAHero04** [comment]
When you installed OptiFine, use this tool in the mod installer to get it work.
[PojavOF117AssetsPatcher.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7311288/PojavOF117AssetsPatcher.zip)

**Comment by aaaapai** [comment]
> 安装 OptiFine 时，请在模组安装器中使用此工具使其工作。 [波雅夫夫117资产帕特赫.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7311288/PojavOF117AssetsPatcher.zip)

怎么用？How to use it?

**Comment by NotAHero04** [comment]
The zip file contains a jar file, which can be used on the mod installer to directly modify the OptiFine client.

**Comment by aaaapai** [comment]
> Zip 文件包含一个罐子文件，可用于模组安装器直接修改 OptiFine 客户端。

谢谢thank you

**Comment by aaaapai** [comment]
> When you installed OptiFine, use this tool in the mod installer to get it work. [PojavOF117AssetsPatcher.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7311288/PojavOF117AssetsPatcher.zip)

进入多人游戏时，又崩溃了，我选择的是第三个渲染器，当我用optifabric把fabric和optifine合并，仍然崩溃When I entered the multiplayer game, it crashed again. I chose the third renderer. When I combined fabric and optifine with optifabric, it still crashed
[crash-2021-10-08_15.11.31-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7315515/crash-2021-10-08_15.11.31-client.txt)

**Comment by ENDERMANYK** [comment]
......optfine patch完才可以运行，直接运行不崩才怪

**Comment by aaaapai** [comment]
> ......optfine patch完才可以运行，直接运行不崩才怪

问题又来了，optifine和fabric，一起使用又崩溃，仍然第三个渲染器The problem comes again. Optifine and fabric, used together, crash and still the third renderer
[crash-2021-10-09_12.29.02-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7315577/crash-2021-10-09_12.29.02-client.txt)

**Comment by aaaapai** [comment]
> > ......optfine patch完才可以运行，直接运行不崩才怪
> 
> 问题又来了，optifine和fabric，一起使用又崩溃，仍然第三个渲染器The problem comes again. Optifine and fabric, used together, crash and still the third renderer [crash-2021-10-09_12.29.02-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7315577/crash-2021-10-09_12.29.02-client.txt)

**Comment by Mathias-Boulay** [comment]
#1963 is here due to the lack of OG 3.2

**Comment by aaaapai** [comment]
> #1963 is here due to the lack of OG 3.2

那总不能让optifine启动缓慢吧Then you can't let optifine start slowly

**Comment by aaaapai** [comment]
等你说得来，我已经自己解决了When you can say it, I've solved it myself发自我的荣耀手机-------- 原始邮件 --------发件人： Boulay Mathias ***@***.***>日期： 2021年10月10日周日 凌晨1:18收件人： PojavLauncherTeam/PojavLauncher ***@***.***>抄送： aaaapai ***@***.***>, State change ***@***.***>主    题： Re: [PojavLauncherTeam/PojavLauncher] 我要i want opengl3.2！ (#2099)
#1963 is here due to the lack of OG 3.2
