### ISSUE TITLE
About 1.17 Optifine

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#2100]
### Is this request related to a bug?

I want 1.17 Optifine I don't want 1.17.1 Optifine If Pojavlauncherteam can't make so I don't use the Pojavlauncher I can't see crosshair outline and I can't play with Optifine seens 2 months so please develop fast pleaseeeeeee😈😈😈😈

**Comment by NotAHero04** [comment]
1. OptiFine 1.17 is now obsolete. You can only find some beta builds of it, which is not proven to be stable and can break any time.
2. The fix for OptiFine is in #2099, please check it for more info.
3. Crosshair issue is a common one. Don’t report it because it won’t be fixed soon.

**Comment by Axoloski** [comment]
You are a stupid 12yo kid
