### ISSUE TITLE
添加自定义渲染器组合Add a custom renderer combination

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2101]
### Is this request related to a bug?

是的，选择vgpu opengl3.0时岀现渲染错误。
Yes, selecting vgpu opengl3.0 shows a rendering error.

### Describe the request.

添加自定义渲染器，启动器内置什么渲染器核心文件，才可以选什么渲染器。界面这样可自定义：设置→渲染器→左下角的"自定义渲染器"→点击"➕"选择渲染器（再点击"➕"可以继续添加渲染器）完成选择的组合→新建→返回，就新建成功。
Add custom renderer, launcher built-in renderer core file, can choose what renderer. The interface can be customized like this: Settings → Renderer → "custom renderer" in the lower left corner → click "➕" to select renderer (click "➕" to continue to add renderer) to complete the selection of combination → New → return, the new success.

### Anything else?

添加这个后，可能不需要一些资源包或者其它修复工具，免去了一些麻烦。对了，选择渲染器有版本供选择，也可以尝试opengl3.2和opengl ES3.2。例如：
After adding this, you may not need some resource packs or other repair tools to avoid some trouble. By the way, there are versions to choose from. You can also try OpenGL 3.2 and OpenGL es3.2. For example:
![IMG_20211009_185900](https://user-images.githubusercontent.com/89151134/136655567-d7e5befb-3483-4629-acbf-ce3ab27bdd10.jpg)

**Comment by NotAHero04** [comment]
After choosing version, hold the version selector, probably that’s what you need.

**Comment by khanhduytran0** [comment]
> renderer combination

~~how does it even work then? Like half of the game is rendered with Zink and half other is rendered with VGPU?~~

**Comment by khanhduytran0** [comment]
@aaaapai you know, Minecraft doesn't use multiple GPUs/threads to render and Android has just 1 GPU

**Comment by khanhduytran0** [comment]
like how can we even make the half part of game (GUI) renders with just gl4es/vgpu and in-game+shader part renders with zink?

**Comment by aaaapai** [comment]
> 比如我们怎么能用 gl4es / vgpu 和游戏中的阴影部分渲染 zink 来渲染游戏的一半呢？

不用VPN，太拥堵了，来迟了No VPN. It's too crowded. It's late

**Comment by khanhduytran0** [comment]
I'm not talking about VPN, I'm talking about VGPU.

**Comment by aaaapai** [comment]
> 比如我们怎么能用 gl4es / vgpu 和游戏中的阴影部分渲染 zink 来渲染游戏的一半呢？

当我使用vgpu或zink启动1.17.1optifine时，进入多人游戏时帧数太低了，只有1fps，不使用很流畅，但optifine进入多人游戏仍然崩溃。不使用optifine在很多npc也才大概6~12帧。When I use vgpu or Zink to start 1.17.1 optifine, the number of frames when entering the multiplayer game is too low, only 1fps. It is very smooth when I don't use it, but optifine still crashes when entering the multiplayer game. Without optifine, it is only about 6 ~ 12 frames in many NPCs.

**Comment by khanhduytran0** [comment]
but the how does "combination" even works then? Minecraft doesn't use multiple graphical libraries at once. that's the point.

**Comment by aaaapai** [comment]
> 但是， "组合" 是如何工作的呢？Minecraft 不会同时使用多个图形库。这就是重点。

要不不要这个功能了？Why not use this function?

**Comment by aaaapai** [comment]
> but the how does "combination" even works then? Minecraft doesn't use multiple graphical libraries at once. that's the point.

因为第三个渲染器有一个opengl es和opengl版本不同，导致optifine崩溃，别人说的Because the third renderer has a different version of OpenGL es and OpenGL, optifine crashes, as others say

**Comment by ENDERMANYK** [comment]
~~有一个opengl es 和opengl 版本不同~~，问题是opengl es 和 opengl 原本就是不同的东西

> 因为第三个渲染器有一个opengl es和opengl版本不同，导致optifine崩溃，别人说的Because the third renderer has a different version of OpenGL es and OpenGL, optifine crashes, as others say

**Comment by aaaapai** [comment]
> ~有一个opengl es 和opengl 版本不同~，问题是opengl es 和 opengl 原本就是不同的东西
> 
> > 因为第三个渲染器有一个opengl es和opengl版本不同，导致optifine崩溃，别人说的Because the third renderer has a different version of OpenGL es and OpenGL, optifine crashes, as others say

可是当我选择那两个时，optifine进入游戏才1帧...But when I chose those two, optifine entered the game only 1

**Comment by ENDERMANYK** [comment]
说简单点，啥时候电脑可以自定义选择输出的opengl版本了，一般都是直接输出支持的最大值

**Comment by aaaapai** [comment]
> 说简单点，啥时候电脑可以自定义选择输出的opengl版本了，一般都是直接输出支持的最大值

我只是想用第三个来启动optifine，可是进入游戏时崩溃了I just wanted to start optifine with the third one, but I crashed when I entered the game

**Comment by ENDERMANYK** [comment]
1.17至少要OpenGL3.2你拿OpenGL 3.0不崩才怪
> 我只是想用第三个来启动optifine，可是进入游戏时崩溃了I just wanted to start optifine with the third one, but I crashed when I entered the game

**Comment by ENDERMANYK** [comment]
如果你用了那个1.17的optifine patch。记得在设置里把Render Regions给关了

**Comment by aaaapai** [comment]
> 1.17至少要OpenGL3.2你拿OpenGL 3.0不崩才怪
> 
> > 我只是想用第三个来启动optifine，可是进入游戏时崩溃了I just wanted to start optifine with the third one, but I crashed when I entered the game

渲染器里又没有openGL3.2，我也想用呀

**Comment by aaaapai** [comment]
> 如果你用了那个1.17的optifine patch。记得在设置里把Render Regions给关了

你所说的Render Regions在哪？我没有找到

**Comment by ENDERMANYK** [comment]
语言换成英语，打开video settings

> 你所说的Render Regions在哪？我没有找到

**Comment by ENDERMANYK** [comment]
> 渲染器里又没有openGL3.2，我也想用呀

~~所以用发的那个optifine patch更改OpenGL 版本运行~~

**Comment by aaaapai** [comment]
> > 渲染器里又没有openGL3.2，我也想用呀
> 
> ~所以用发的那个optifine patch更改OpenGL 版本运行~

成功了
