### ISSUE TITLE
[BUG] Cannot Login Using Microsoft Account

### ISSUE THREAD

**Issue by theamazing0** [PojavLauncherTeam/PojavLauncher#2102]
### Describe the bug

I own minecraft java edition thru a microsoft account. I installed PojavLauncher from the Releases section of Github because my device is a Kindle Fire and Play Store doesn't work perfectly. After transfering the apk file to the Fire and running it, I opened the launcher and selected "Microsoft Login" I completed the sign-in but when I click continue on the microsoft page it just brings me back to the screen where it asks for the login.

### The log file and images/videos

I'm on a Kindle Fire and no Log Files seem to have generated.

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Select Microsoft Login
3. Login With A Microsoft Account
4. Click "Continue"
```

### Expected Behavior

The expected behavior is to sign in with the microsoft account.

### Platform

```markdown
- Device model: Kindle Fire 5th Gen
- CPU architecture: I have no idea
- Android version: FireOS?
- PojavLauncher version: The Latest One From Github Releases
```

**Comment by theamazing0** [comment]
Note: I can Access The Launcher If I Use An Offline Account

**Comment by theamazing0** [comment]
Ok Now After I did That, Whenever I launch the game, it opens for 2 seconds and then crashes, but i cant seem to find any sort of crash report.

**Comment by theamazing0** [comment]
Is this anything to do with me using a kindle fire?

**Comment by Mathias-Boulay** [comment]
if by "github releases" you mean 3.3.1.1, close this issue, as it is an old unsupported version

**Comment by theamazing0** [comment]
Yeah I mean that one, ok I will, but you guys should update the github releases for kindle fires and stuff without play store. I guess kindle fires don't have much specs anyways so thanks anyway.

**Comment by khanhduytran0** [comment]
There’s nightly builds in the actions tab, if you want latest, [go there](https://github.com/PojavLauncherTeam/PojavLauncher/actions).
