### ISSUE TITLE
Respone error 

### ISSUE THREAD

**Issue by JACk75974** [PojavLauncherTeam/PojavLauncher#2104]
### Describe the bug

Code 403
Invalid username or password

### Steps To Reproduce

```markdown
I fill my email and password and it is showing error I so use this with 
Mc java account generator but nothing happen
```

### Expected Behavior

Why this is always showing error

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by dachisao** [comment]
lmao wtf

**Comment by Py10lolz** [comment]
~~cutie just watch this tutorial => https://youtu.be/iik25wqIuFo~~

**Comment by rscDMTalt** [comment]
> ### Describe the bug
> Code 403 Invalid username or password
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> I fill my email and password and it is showing error I so use this with 
> Mc java account generator but nothing happen
> ```
> 
> ### Expected Behavior
> Why this is always showing error
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:
> ```
> 
> ### Anything else?
> _No response_

Which generator? The one in the news page?

**Comment by khanhduytran0** [comment]
> I fill my email and password and it is showing error

@JACk75974 
Is it “your account” or you have borrowed/generated from someone/somewhere?

![<:frpirate:871497846686355458>](https://cdn.discordapp.com/emojis/871497846686355458.png)

**Comment by herzokun** [comment]
pircay moment

**Comment by akask11** [comment]
![Screenshot_20220504-205740](https://user-images.githubusercontent.com/104918040/166716167-33f7659c-dae3-487e-982a-aad5203f2d83.jpg)
 New
