### ISSUE TITLE
[BUG] VietNamese keyboard not work properly

### ISSUE THREAD

**Issue by bot432** [PojavLauncherTeam/PojavLauncher#2105]
### Describe the bug

Bug occurs when I enter the world, I click open chat bar and click open keyboard press 1 word it will turn off (it's hard to describe) 

### Steps To Reproduce

```markdown
Same the first
```

### Expected Behavior

I hope u can fix this bug

### Platform

```markdown
- Device model: Nokia X5
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: croccus-80-4152a0011-v3_openjdk
```

### Anything else?

#

**Comment by bot432** [comment]
> ### Describe the bug
> Bug occurs when I enter the world, I click open chat bar and click open keyboard press 1 word it will turn off (it's hard to describe)
> 
> ### The log file and images/videos
> 

Uploading 20211010_163416_es_edited.mp4…


> 
> ### Steps To Reproduce
> ```gfm
> Same the first
> ```
> 
> ### Expected Behavior
> I hope u can fix this bug
> 
> ### Platform
> ```gfm
> - Device model: Nokia X5
> - CPU architecture: aarch64
> - Android version: 9
> - PojavLauncher version: croccus-80-4152a0011-v3_openjdk
> ```
> 
> ### Anything else?

**Comment by bot432** [comment]
> > ### Describe the bug
> > Bug occurs when I enter the world, I click open chat bar and click open keyboard press 1 word it will turn off (it's hard to describe)
> > ### The log file and images/videos
> 
> 
> 
> > ### Steps To Reproduce
> > ```
> > Same the first
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > I hope u can fix this bug
> > ### Platform
> > ```
> > - Device model: Nokia X5
> > - CPU architecture: aarch64
> > - Android version: 9
> > - PojavLauncher version: croccus-80-4152a0011-v3_openjdk
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?

**Comment by WesleyVanNeck** [comment]
> > > ### Describe the bug
> > > Bug occurs when I enter the world, I click open chat bar and click open keyboard press 1 word it will turn off (it's hard to describe)
> > > ### The log file and images/videos
> > 
> > 
> > > ### Steps To Reproduce
> > > ```
> > > Same the first
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Expected Behavior
> > > I hope u can fix this bug
> > > ### Platform
> > > ```
> > > - Device model: Nokia X5
> > > - CPU architecture: aarch64
> > > - Android version: 9
> > > - PojavLauncher version: croccus-80-4152a0011-v3_openjdk
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Anything else?

queting your own isuee wont make in fact it slower as am not respond to it

**Comment by WesleyVanNeck** [comment]
also no log

**Comment by bot432** [comment]
Log cant help here

**Comment by bot432** [comment]
> also no log

Bruh

**Comment by khanhduytran0** [comment]
> also no log

Game log has nothing to do with soft keyboard.

**Comment by bot432** [comment]
M

**Comment by WesleyVanNeck** [comment]
> > also no log
> 
> Game log has nothing to do with soft keyboard.

Latest txt does i believe

**Comment by bot432** [comment]
latestlog unrelated

**Comment by bot432** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7322990/latestlog.txt)

**Comment by WesleyVanNeck** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7322990/latestlog.txt)

Right i said latest.txt not latestlog.txt listen for one God dam time

**Comment by Mathias-Boulay** [comment]
This bug was solved on the discord, it was a version specific gboard bug.
