### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by ale8002** [PojavLauncherTeam/PojavLauncher#2107]
### Describe the bug

I cant log in via microsoft, when I try to open the microsoft login screen it just stays blank or there is an error code and it says cant find proxy or something

### Steps To Reproduce

```markdown
I start microsoft
```

### Expected Behavior

It doesnt work and i get an error

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: newest
- PojavLauncher version: 
Newest
```

### Anything else?

Im sorry this is my first time on github, thanks for helping!

**Comment by rscDMTalt** [comment]
> I start microsoft
holy shit ur the one who started microsoft?
