### ISSUE TITLE
[F-Req] Use API for Microsoft accounts

### ISSUE THREAD

**Issue by Madis0** [PojavLauncherTeam/PojavLauncher#2111]
### Is this request related to a bug?

1. Signed into Pojav with a Microsoft account
2. Checked for 3rd-party app access by this tutorial https://www.makeuseof.com/tag/revoke-access-microsoft-account/ 
3. Did not find Pojav in it

### Describe the request.

Please use the official Microsoft APIs for logging users into the launcher. Direct sign-in is dangerous because it gives the app the full account access, while it only needs to access Minecraft.

### Anything else?

Other third-party launchers like MultiMC and GDLauncher already do it, you may have a look at their implementation

**Comment by Mathias-Boulay** [comment]
Hmm, maybe I should take a look at it

**Comment by Mathias-Boulay** [comment]
Although even multimc implementation isn't mature yet, we'll surely wait a bit for it to mature before implementing it

**Comment by artdeell** [comment]
Pojav already uses the APIs documented at wiki.vg, and uses the official Minecraft Launcher app ID/secret

**Comment by Madis0** [comment]
Is it allowed to use the same ID/secret though? I did not find it listed in wiki.vg either, only API itself and a placeholder of the secret is described.

**Comment by Mathias-Boulay** [comment]
Is it forbidden though ?

**Comment by Madis0** [comment]
Well, Minecraft Launcher is not open source so it seems weird to have access to the same ID and secret (as if you decompiled it). Perhaps this answer will explain it better: https://softwareengineering.stackexchange.com/a/395130

Disclaimer: not an expert in this area, just suggesting to avoid any legal troubles with your project.

**Comment by khanhduytran0** [comment]
> Minecraft Launcher is not open source so it seems weird to have access to the same ID and secret (as if you decompiled it). 

~~If you didn't know, their official launcher is written in HTML + JavaScript so it is very easy to extract stuff~~ anyways, how do we achieve under 18 account authorization without link to parent account when use custom ID?
> 2148916238: The account is a child (under 18) and cannot proceed unless the account is added to a Family by an adult. This only seems to occur when using a custom Microsoft Azure application. When using the Minecraft launchers client id, this doesn't trigger.

**Comment by Madis0** [comment]
Alright, thanks for the explanation.
