### ISSUE TITLE
I cant install mods/datapacks

### ISSUE THREAD

**Issue by BUNGEEGUMHASBOTHTHEPROPIERTIESOFRUBERAN** [PojavLauncherTeam/PojavLauncher#2112]
### Describe the bug

Well this is probably casued beacuse i have Android 11 ( or thats what i think) and the title says it all i cant install anything besides from mod installers/optifine

### Steps To Reproduce

```markdown
i try to install a mod
fails
```

### Expected Behavior

no

### Platform

```markdown
- Device model: Redmi note 8
- CPU architecture:x64 
- Android version: 11
- PojavLauncher version: 3
```

**Comment by Riotlong** [comment]
Hi

**Comment by Riotlong** [comment]
![Uploading 51aa8b572ec8a614d2f65dda75d0c9e1.gif…]()

**Comment by khanhduytran0** [comment]
Looks like you have ignored reading this dialog
![i](https://images-ext-1.discordapp.net/external/FZB_r1mZlwiKpDai7vy4cUy6sTDLbC7JP2XMapcs38g/https/media.discordapp.net/attachments/724163890803638277/887518864836001802/Screenshot_2021-09-15-09-26-45-429_net.kdt.pojavlaunch.jpg)
also, no latestlog.txt

**Comment by khanhduytran0** [comment]
Since #1948 exists, this is going to be closed.
