### ISSUE TITLE
[BUG] I CANT PLAY MY MODS ALL THE MODS

### ISSUE THREAD

**Issue by LuskaZueiro** [PojavLauncherTeam/PojavLauncher#2114]
### Describe the bug

PLEASE I CANT PLAY MY MODS
 ALL THE MODS DONT WORK IN MY PHONE, I MADE EVERYTHING RIGHT BUT DON WORK
DONT WORK (A10S)
BUT THE PHONE OF MY MOM (A30) WORK 
WHAT HAPPENING??!?!

### Steps To Reproduce

```markdown
1.I made all right, install the mods and the forge
2.And start the forge but dont work
```

### Expected Behavior

I expect the mods load but dont load.

### Platform

```markdown
- Device model: A10s
- CPU architecture: aarch64
- Android version: 1p
- PojavLauncher version: Latest version v3 but all the versions dont work
```

### Anything else?

FIIIIIIIIIIXXXX
PLEASEEEEE

**Comment by khanhduytran0** [comment]
First, did you read this dialog?
![i](https://images-ext-1.discordapp.net/external/FZB_r1mZlwiKpDai7vy4cUy6sTDLbC7JP2XMapcs38g/https/media.discordapp.net/attachments/724163890803638277/887518864836001802/Screenshot_2021-09-15-09-26-45-429_net.kdt.pojavlaunch.jpg)

Second, no latestlog.txt

Third, “Latest version v3 but all the versions dont work” is not a valid version name.

**Comment by khanhduytran0** [comment]
Duplicate of #2112

**Comment by khanhduytran0** [comment]
You know, we can’t read your brain. You didn’t even **specify** Minecraft version, Forge/Fabric version and the mod list.

**Comment by khanhduytran0** [comment]
> I CANT PLAY <ins>**MY MODS**</ins>

Also, fix it yourself since you claimed to be the creator of mods.
