### ISSUE TITLE
[BUG] <white homescreen>

### ISSUE THREAD

**Issue by Yashjbk17** [PojavLauncherTeam/PojavLauncher#2115]
### Describe the bug

Whenever i start the game the game starts correctly buttons are also visible but the background homescreen in white only

### The log file and images/videos

![Screenshot_20211012_154333](https://user-images.githubusercontent.com/91838599/136937416-1e6e8c10-d590-4382-a298-b33a03044f68.jpg)

### Steps To Reproduce

```markdown
1.launch 1.16.5
2.loading compelete
3.white homescreen
```

### Expected Behavior

I expects the game to have a colourfull background screen but it is always white

### Platform

```markdown
- Device model: vivo y81 4/32gb
- CPU architecture:aarch64
- Android version: 8
- PojavLauncher version:3.3.1.1
```

**Comment by Yashjbk17** [comment]
Help me

**Comment by khanhduytran0** [comment]
bruh, don’t skip downloading assets, just let the launcher download everything

**Comment by Yashjbk17** [comment]
> bruh, don’t skip downloading assets, just let the launcher download everything

Bro it takes so much data

**Comment by Yashjbk17** [comment]
Ohh it is working now thank you

**Comment by Yashjbk17** [comment]
The problem is solved for 1.16.5 but how to download assests of 1.17.1 there are no assests but still white screen

**Comment by khanhduytran0** [comment]
> there are <ins>no</ins> assests but <ins>still white screen</ins>

**Comment by Yashjbk17** [comment]
Yes there is a white screen

**Comment by Mathias-Boulay** [comment]
Assets have to be downloaded first.
Case and point.

**Comment by Yashjbk17** [comment]
> Assets have to be downloaded first. Case and point.

Why you closed it
