### ISSUE TITLE
Micrlsoft login

### ISSUE THREAD

**Issue by EnjoyTheHype** [PojavLauncherTeam/PojavLauncher#2117]
### Describe the bug

If i click on Microsoft login it opens  the website and i sign in the website close and a window pops up: please wait a momente, and then it stucks on 33% 2/6 und after a few seconds it says Error: connection reset so i cant login this happens every time i try it

### The log file and images/videos

nothing

### Steps To Reproduce

```markdown
Dont know what to write here
```

### Expected Behavior

i want to login

### Platform

```markdown
- Device model: samsung galaxy a 10
- CPU architecture: 
- Android version: 11
- PojavLauncher version: latest
```

**Comment by ajit850** [comment]
Letest isn't version

**Comment by EnjoyTheHype** [comment]
how can i find the version?Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: ajit850 ***@***.***> Datum: 14.10.21  05:11  (GMT+01:00) An: PojavLauncherTeam/PojavLauncher ***@***.***> Cc: EnjoyTheHype ***@***.***>, Author ***@***.***> Betreff: Re: [PojavLauncherTeam/PojavLauncher] Micrlsoft login (#2117) 
Letest isn't version

**Comment by ghost** [comment]
Micrlsoft not exist

**Comment by Mathias-Boulay** [comment]
Yep, latest isn't a version.
We can't help you if the version isn't stated
