### ISSUE TITLE
1.17+ won't launch

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2119]
### Describe the bug

when i try to launch 1.17 it says it can't find the version of java runtime when i try put java runtime 17 says it is corrupted i used the xz extension on it like it said 

### The log file and images/videos

[Screenshot_20211014-060227](https://user-images.githubusercontent.com/87820585/137322723-503d0dc2-ae38-478d-901b-72e3fd60d58e.jpg)

### Steps To Reproduce

```markdown
by trying to run 1.17 using the default java 8.
```

### Expected Behavior

to not launch

### Platform

```markdown
- Device model: samsung tab e
- CPU architecture: idk
- Android version: 7.11
- PojavLauncher version: playstore
```

### Anything else?

i can't add a new version of java runtime please fix that it might fix 1.17 not launching

**Comment by EnderBrine99FOX** [comment]
download the latest Google play build and add Java 17 and it's will work

**Comment by SprainedSpark89** [comment]
i did i installed it recently on a different device

**Comment by ghost** [comment]
use java 17 (32 bit not supported)

**Comment by Mathias-Boulay** [comment]
Seems to be a 32 bit device

**Comment by SprainedSpark89** [comment]
Did but it says crupted

**Comment by SprainedSpark89** [comment]
![Screenshot_20211016-204406](https://user-images.githubusercontent.com/87820585/137610107-deabd417-de01-42fd-b0a2-009185ff5549.jpg)
Here is some more info i just download a app that gives me device info that it doesn't show in settings

**Comment by SprainedSpark89** [comment]
![Screenshot_20211016-204721](https://user-images.githubusercontent.com/87820585/137610234-55ba5b7f-f73b-493f-927f-184123a2f31a.jpg)

**Comment by Mathias-Boulay** [comment]
Yep, 32 bits device

**Comment by SprainedSpark89** [comment]
Is there a download for java 17 for 32 bit

**Comment by ghost** [comment]
> Is there a download for java 17 for 32 bit

Not available. (Yet)

**Comment by Mathias-Boulay** [comment]
I'm going to add the lack of 32 bits support in the pinned issue list as it is becoming a recurring theme

**Comment by SprainedSpark89** [comment]
@Mathias-Boulay could you look at my issue need help with using versions infdev and older it has old issues that will give some more info

**Comment by mchnjt** [comment]
L :HYPERROFEL:
