### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by glancist** [PojavLauncherTeam/PojavLauncher#212]
Java application exited then it tells me to go log then /data/data/net.kdt.pojavlaunch.jre.usr.bin.jre.sh[41]: /data/data/net.kdt.pojavlaunch.jre.usr.bin.proot. not executable: magic 7F45 in log output
Android 5
Version 1.7.10
gave me the file not error too but I saw another bug in here and went to settings custom controls then restarted now I'm getting this error

**Comment by khanhduytran0** [comment]
What's your architecture?

**Comment by PeppaThePigMC** [comment]
@khanhduytran0 idk I have Lenovo Tab a2 30hc idk how to find it

**Comment by khanhduytran0** [comment]
Check in CPU Z app or similar app.

**Comment by khanhduytran0** [comment]
Looks like original Android 4.4 so arm32...

**Comment by PeppaThePigMC** [comment]
it was 4.4 like 2 years ago but got updated to 5.0.1

**Comment by glancist** [comment]
so arm 32 work?

**Comment by khanhduytran0** [comment]
> so arm 32 work?

No.

**Comment by glancist** [comment]
So will it ever work in the new updates?

**Comment by khanhduytran0** [comment]
If you another device with stock is Android 5 or higher, it's definitely arm64.

**Comment by glancist** [comment]
i have a android 6 phone too 
Samsung Galaxy Grand Prime Plus

**Comment by khanhduytran0** [comment]
It will work on Android 5 - 7.1.

**Comment by glancist** [comment]
Ok brb I'll try and tell you if it works.

**Comment by khanhduytran0** [comment]
> i have a android 6 phone too 
> Samsung Galaxy Grand Prime Plus

So you may try on it.

**Comment by glancist** [comment]
/data/data/net.kdt.pojavlaunch/jre/usr/bin/jre.sh[41]: /data/data/net.kdt.pojavlaunch/jre/usr/bin/proot: not executable: 64-bit ELF file

**Comment by glancist** [comment]
im getting this error now @khanhduytran0

**Comment by khanhduytran0** [comment]
> /data/data/net.kdt.pojavlaunch/jre/usr/bin/jre.sh[41]: /data/data/net.kdt.pojavlaunch/jre/usr/bin/proot: not executable: 64-bit ELF file

Hmm still 32bit?

**Comment by PeppaThePigMC** [comment]
still no answer oof

**Comment by glancist** [comment]
Samsung Galaxy Grand Prime + I don't think it's 32x as it comes with stock android 6

**Comment by khanhduytran0** [comment]
Grand Prime G350?

**Comment by khanhduytran0** [comment]
I googled and see it come with android 4.4... again.

**Comment by Sprtcrnbry** [comment]
Some Samsung devices are running 32-bit Android userspace instead of 64-bit even if the SOC/CPU supports 64-bit.

**Comment by glancist** [comment]
@khanhduytran0 Its android 6 LOL and it's SM-G532F

**Comment by glancist** [comment]
And I think it's 32bit too OOF

**Comment by khanhduytran0** [comment]
Just do a test in CPU Z.

**Comment by glancist** [comment]
F
