### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by DiNoXtReX** [PojavLauncherTeam/PojavLauncher#2120]
### Describe the bug

i am not able to use mt wireless keyboard and mouse for minecraft 1.16+

### Steps To Reproduce

```markdown
this is very big issue according to me because i have tried amny diffrent mouse and keyboard none them works correctly
```

### Expected Behavior

i does not respond to my mouse 

### Platform

```markdown
Device model: Moto G40 Fusion
CPU architecture: aarch64
Android version: 11
PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

it does not respond to my mouse

**Comment by artdeell** [comment]
Did you fill out the version? If you did, then it's too old.

**Comment by Mathias-Boulay** [comment]
Yeah, state your pojav launcher version please

**Comment by DiNoXtReX** [comment]
My version is - crocus-v3_openjdk
I accidentally typed that

**Comment by Mathias-Boulay** [comment]
Basic questions time:
- Does the mouse/keyboard work with other programs?
- Does it work with other minecraft versions ?

Also, some video footage may be appreciated to help with the issue. You're the first one with this one

**Comment by DiNoXtReX** [comment]
Yes, it work with Lower versiona

**Comment by mchnjt** [comment]
omfg stop github-ing in your email app

**Comment by DiNoXtReX** [comment]
Got it, thanks!

**Comment by Mathias-Boulay** [comment]
Maybe try to upload video footage for us to see

**Comment by DiNoXtReX** [comment]
Uploading 20211022_1080p.mp4…

**Comment by DiNoXtReX** [comment]
i am able to use keyboard and mouse in minecraft 1.12.2 and below but when i tried to use them in 1.16.5 it doesn't respond

**Comment by Mathias-Boulay** [comment]
Not the same issue there, we'll close this one.
As for the controls issue, contact me on the official pojav discord if you want it to be fixed asap
