### ISSUE TITLE
关于安卓11存储权限兼容的问

### ISSUE THREAD

**Issue by hyplant** [PojavLauncherTeam/PojavLauncher#2122]
安卓11确实对存储权限进行了一些修改，但是在release页面中下载的稳定版。仍然可以把游戏目录设为/storage/emulated/0/games/PojavLauncher

但是后来的 Action中下载的测试版 版本游戏目录就被迫改到了/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/
而且不再具有访问/storage/emulated/0/games/PojavLauncher的能力，在系统设置中也无法在数据存储权限![Screenshot_20211015-214756_Permission controller.jpg](https://user-images.githubusercontent.com/86937725/137497731-d7ab700d-c58d-4640-83b8-a206c5f158c1.jpg)

这对于导入及导出存档时分不方便，毕竟只能使用十分不顺手的Mt管理器，才能在安卓11中访问/storage/emulated/0/Android/data
希望以后可以尽快修改，例如把游戏目录设为/storage/emulated/0/games/PojavLauncherDev
下面这个页面可能有所帮助
[https://developer.android.google.cn/about/versions/11/privacy/storage?hl=cn#all-files-access](https://developer.android.google.cn/about/versions/11/privacy/storage?hl=cn#all-files-access)

**Comment by artdeell** [comment]
Just putting the "All files access" permission into AndroidManifest.xml requires to go through 3 rounds of bureaucratic hell with Google to explain them how we will use that permission, if we want to keep the app up in Google Play.

**Comment by khanhduytran0** [comment]
and it’s only approved for file managers (ZArchiver, ES File Explorer, etc...)


look, even Google forced Minecraft Bedrock to move too (see: https://help.minecraft.net/hc/en-us/articles/4411299967629)
