### ISSUE TITLE
Play the game with the handle and move the view card

### ISSUE THREAD

**Issue by jiuhui0415** [PojavLauncherTeam/PojavLauncher#2125]
### Describe the bug

When playing games with the Xbox handle, the mobile view is stuck at 200fps, but the mobile view is stuck. I suspect it may be a mapping problem

### The log file and images/videos

![1634359455040](https://user-images.githubusercontent.com/86163887/137574050-81aa1fa7-bc69-4519-8202-41a6c044d6bd.jpg)
![1634359591779](https://user-images.githubusercontent.com/86163887/137574097-5c9e94a4-9d86-42bc-bf65-63d49fa8678f.jpg)
When playing games with the Xbox handle, the mobile view is stuck at 200fps, but the mobile view is stuck. I suspect it may be a mapping problem #2120 # @Google61 @LegacyGamerHD @Moresteck @Mathias-Boulay @

### Steps To Reproduce

```markdown
When playing games with the Xbox handle, the mobile view is stuck at 200fps, but the mobile view is stuck. I suspect it may be a mapping problem
```

### Expected Behavior

I hope to improve the mapping, which will make the mobile perspective smoother  I hope to improve it as much as possible. It's still very convenient to play with the Xbox handle on the mobile device

### Platform

```markdown
－设备型号：redmi－CPU架构：－Android版本：－PojavLauncher版本：
```

### Anything else?

I hope to improve the mapping, which will make the mobile perspective smoother    I hope to improve it as much as possible. It's still very convenient to play with the Xbox handle on the mobile device

**Comment by mchnjt** [comment]
Dude

**Comment by mchnjt** [comment]
Mentioning devs is illegal

**Comment by mchnjt** [comment]
Ok I Guess It's Time To Add Rules
