### ISSUE TITLE
21w41a 

### ISSUE THREAD

**Issue by Debob54** [PojavLauncherTeam/PojavLauncher#2126]
### Describe the bug

Application exceeded with code -1

### The log file and images/videos

![Screenshot_20211016-080528_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86144916/137577554-fb22619d-a7bb-4d4d-b8f7-df35eace492d.jpg)
![20211016_080756](https://user-images.githubusercontent.com/86144916/137577622-3b0500c7-60d6-4c5d-9835-10a47a5b79be.jpg)

### Steps To Reproduce

```markdown
Fgcgb
```

### Expected Behavior

fvxfvvcc

### Platform

```markdown
- CPU architecture:
- Android version: 
- PojavLauncher version:
```

**Comment by rscDMTalt** [comment]
No latestlog.txt

**Comment by rscDMTalt** [comment]
Fuck off
