### ISSUE TITLE
[BUG] Unable to enter realms

### ISSUE THREAD

**Issue by doubijunNB** [PojavLauncherTeam/PojavLauncher#2129]
### Describe the bug

Invalid ID

### The log file and images/videos

![Screenshot_2021-10-16-20-07-22-14_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/67856576/137586777-08cf313b-4863-4b3c-b4c2-57b657495c23.jpg)

### Steps To Reproduce

```markdown
1.Log in to Microsoft account
2.play 1.17.1
3.realms
```

### Expected Behavior

Normal entry

### Platform

```markdown
- Device model: oppo ace2
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210206
```

**Comment by Pgabrielmnecraft** [comment]
This also happens to me, but I don't know how to solve

**Comment by ajit850** [comment]
Outdated pojavlauncher version

**Comment by doubijunNB** [comment]
> 过时的 pojavlauncher 版本

Any version is the same

**Comment by WesleyVanNeck** [comment]
> > 过时的 pojavlauncher 版本
> 
> Any version is the same

Wrong the latest version is on the Playstore  the one in the release tab is very outdated
