### ISSUE TITLE
Fix errors and changes, please help me!

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#213]
khanhduytran0, Please make arm32 or armv7 supported back. Pretty please. I am begging you. (I gonna subscribe you!)
![20200525_110143](https://user-images.githubusercontent.com/65865186/82777172-8b161b00-9e77-11ea-9f6e-c73ab1fd830b.jpg)

**Comment by khanhduytran0** [comment]
With your modern device why don't have arm64?

**Comment by ghost** [comment]
Mine is ARM64 but only support 32bit mode.

**Comment by khanhduytran0** [comment]
Where did you checked?

**Comment by khanhduytran0** [comment]
Because current v3 is not working, so I only go on debugging only arm64 which available on my phone. Once v3 completely worked I may do arm32.

**Comment by ghost** [comment]
![Screenshot_20200525-111014_AIDA64](https://user-images.githubusercontent.com/65865186/82777442-59ea1a80-9e78-11ea-8182-c91e9b28c1ee.jpg)
AIDA64

**Comment by khanhduytran0** [comment]
If I release **unusable** more arm32 and x86, I need to more hard work to debug every architecture.

**Comment by ghost** [comment]
Then make that architecture supported back!

**Comment by ghost** [comment]
Becuase i really want Minecraft PC back!

**Comment by khanhduytran0** [comment]
And what's your device?

**Comment by ghost** [comment]
Some people has been exchanged new Minecraft PC, such as : MCinaBox and BoatApp

**Comment by khanhduytran0** [comment]
Look statusbar like Samsung.

**Comment by ghost** [comment]
Samsung Galaxy J7 Prime (SM-G610F/DS)

**Comment by khanhduytran0** [comment]
> Some people has been exchanged new Minecraft PC, such as : MCinaBox and BoatApp

My v3 completely different with MCinabox or BoatApp, and my v3 is very early unusable release due to in development.

**Comment by ghost** [comment]
Then fix that up!

**Comment by ghost** [comment]
You have to make the version app better again just like **v2.4.2** but different this time!

**Comment by ghost** [comment]
Please! I begging at you!

**Comment by khanhduytran0** [comment]
> You have to make the version app better again just like **v2.4.2** but different this time!

My time is huge limited to back on v2.
**But** why don't you go back on v2?

**Comment by ghost** [comment]
The issue closed! Be right back!

**Comment by ghost** [comment]
I gonna reopen this issue later!

**Comment by khanhduytran0** [comment]
Until the current development go worked I will do. At the moment even arm64 Android8 is stucked at `Bad system call` and OpenGL is still rendered by `llvmpipe Mesa / software renderer` and with me only very classic version will work so If I put into arm32 right now then it is useless and unusable. You need to understand that fixing takes lots of times.

**Comment by khanhduytran0** [comment]
Also only me and @ artdeell are in development so only two developers on PojavLauncher while MCinabox has many contributors on so they dev so fast.

**Comment by khanhduytran0** [comment]
Finally, I will bring arm32 back but arm64 must be worked first.

**Comment by ghost** [comment]
Just ignore the ARM64! Do the ARM32 back first before ARM64 fix!

**Comment by khanhduytran0** [comment]
Arm32 is so slow. Once Google deprecates 32-bit then any hard working go to lava.

Arm32 is not future. If you can, buy a new device. **The v3 is COMPLETELY NOT WORKING** so porting to ARM32 at the moment is **USELESS** because most of daily use phones are 64-bit.

**Comment by khanhduytran0** [comment]
>  **The v3 is COMPLETELY NOT WORKING** so porting to ARM32 at the moment is **USELESS**

And it waste my time.

**Comment by ghost** [comment]
Wait a minute. The app still supported ARM32.

**Comment by ghost** [comment]
![Screenshot_20200525-163219_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82800109-56b95380-9ea5-11ea-81c6-e1fdfef9b4f2.jpg)
And i found new errors.

**Comment by khanhduytran0** [comment]
> ![Screenshot_20200525-163219_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82800109-56b95380-9ea5-11ea-81c6-e1fdfef9b4f2.jpg)
> And i found new errors.
> 

Go to custom controls.

**Comment by ghost** [comment]
Other errors?!?!?!?!?!?!
![Screenshot_20200525-164008_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82800817-83219f80-9ea6-11ea-97f8-2c2881019465.jpg)

**Comment by khanhduytran0** [comment]
Swipe Right to Left -> Log Output. Will you see something similar to below?
```
...: not executable (64-bit ELF file).
```

**Comment by ghost** [comment]
![Screenshot_20200525-164546_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82801278-44401980-9ea7-11ea-9550-f826f81e6ef6.jpg)

**Comment by khanhduytran0** [comment]
Uh! Looks like your device can run 64-bit executable!
Did you Installed latest preview?

**Comment by ghost** [comment]
Maybe install OpenJDK corrupted....

**Comment by ghost** [comment]
Yes

**Comment by khanhduytran0** [comment]
Try do a data delete?

**Comment by ghost** [comment]
I try but i also got the samed error!
Maybe the problem is OpenJDK.

**Comment by ghost** [comment]
You maybe have lost OpenJDK files.
Try to fix corrupted OpenJDK and upgrade your version of OpenJDK v.3.1.5 including PojavLauncher v3.0.1 preview 5 to preview 6!

**Comment by ghost** [comment]
But where do you get the sources of PojavLauncher, all of them that includes credits?

**Comment by khanhduytran0** [comment]
> But where do you get the sources of PojavLauncher, all of them that includes credits?

Most is Boardwalk.

**Comment by ghost** [comment]
![Screenshot_20200525-170001_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802754-997d2a80-9ea9-11ea-9e7c-a4a19c771d80.jpg)
![Screenshot_20200525-170145_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802802-ad289100-9ea9-11ea-87b2-b3cbececa867.jpg)
![Screenshot_20200525-170150_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802821-b4e83580-9ea9-11ea-9a8e-8a0086a8f23a.jpg)


![Screenshot_20200525-165942_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802695-80747980-9ea9-11ea-848f-7ee520902d71.jpg)
![Screenshot_20200525-165952_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802708-84080080-9ea9-11ea-9d6e-666da6d92222.jpg)

**Comment by khanhduytran0** [comment]
Any third party included with link to license.

**Comment by khanhduytran0** [comment]
> 
> ![Screenshot_20200525-170001_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802754-997d2a80-9ea9-11ea-9e7c-a4a19c771d80.jpg)
> ![Screenshot_20200525-170145_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802802-ad289100-9ea9-11ea-87b2-b3cbececa867.jpg)
> ![Screenshot_20200525-170150_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802821-b4e83580-9ea9-11ea-9a8e-8a0086a8f23a.jpg)
> 
> 
> ![Screenshot_20200525-165942_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802695-80747980-9ea9-11ea-848f-7ee520902d71.jpg)
> ![Screenshot_20200525-165952_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/65865186/82802708-84080080-9ea9-11ea-9d6e-666da6d92222.jpg)
> 

Links on it is unclickable...

**Comment by ghost** [comment]
Give that sources instead!

**Comment by khanhduytran0** [comment]
> Give that sources instead!

Just google these.

Hmm... are you picking these code to me and get arm32???

**Comment by khanhduytran0** [comment]
> > Give that sources instead!
> 
> Just google these.
> 
> Hmm... are you picking these code to me and get arm32???

But arm64 is working for you.

**Comment by ghost** [comment]
No, i mean to fix OpenJDK  corrupted!

**Comment by khanhduytran0** [comment]
Any links go to GitHub license then you will get link to code.

**Comment by ghost** [comment]
But how?

**Comment by khanhduytran0** [comment]
> No, i mean to fix OpenJDK  corrupted!

It's not OpenJDK problem, but it's corrupted Linux rootfs.

**Comment by ghost** [comment]
Try to fix full Linux rootfs that comes from AnLinux or AndroNix, and update PojavLauncher.

**Comment by ghost** [comment]
Fix : proot qnd qemu with lost Linux required files!

**Comment by khanhduytran0** [comment]
> Try to fix full Linux rootfs that comes from AnLinux or AndroNix, and update PojavLauncher.

May not, but I'm planning to use Termux + Ubuntu script to get a stable Linux rootfs.

**Comment by khanhduytran0** [comment]
Yes: it support any architectures.

**Comment by khanhduytran0** [comment]
> Fix : proot qnd qemu with lost Linux required files!

May missing `/bin/bash` or `/lib/ld-linux-aarch64.so`.

**Comment by ghost** [comment]
Fix : proot qnd qemu with lost Linux required files!

**Comment by ghost** [comment]
Try to fix that. And then tell me when it's done.

**Comment by ghost** [comment]
Remember : Updates app from PojavLauncher v3.0.1 preview 6!

**Comment by ghost** [comment]
I gonna closing this issue. Bye!

**Comment by ghost** [comment]
Are you done yet?

**Comment by khanhduytran0** [comment]
> Are you done yet?

No, because I will switch to Termux which takes lots of times to complete.
