### ISSUE TITLE
When playing games with the Xbox handle, it is not smooth when controlling the game perspective[BUG] <Short description>

### ISSUE THREAD

**Issue by jiuhui0415** [PojavLauncherTeam/PojavLauncher#2136]
### Describe the bug

When playing games with the Xbox handle, it is not smooth when controlling the game perspective           Although the number of game frames is 200fps, the viewing angle is not smooth when controlling the game. I suspect it is a mapping problem

### Steps To Reproduce

```markdown
When playing games with the Xbox handle, it is not smooth when controlling the game perspective 
Although the number of game frames is 200fps, the viewing angle is not smooth when controlling the game. I suspect it is a mapping problem
```

### Expected Behavior

I hope to improve the mapping so that the control perspective will be more smooth         It's easy to play games on your mobile device using the Xbox handle

### Platform

```markdown
－设备型号：－CPU架构：aarch64－Android版本：10－PojavLauncher版本：
```

### Anything else?

I hope to improve the mapping so that the control perspective will be more smooth       It's easy to play games on your mobile device using the Xbox handle

**Comment by Mathias-Boulay** [comment]
Currently, the system only updates 60 times per second the gamepad state

**Comment by Mathias-Boulay** [comment]
What is your device ?

**Comment by jiuhui0415** [comment]
> 你的设备是什么？

All devices are the same. The bedrock version handle control is very smooth

**Comment by jiuhui0415** [comment]
> 你的设备是什么？

All devices are the same. The bedrock version handle control is very smooth

**Comment by jiuhui0415** [comment]
> 你的设备是什么？


> 你的设备是什么？

All devices are the same. The bedrock version handle control is very smooth

**Comment by jiuhui0415** [comment]
> 目前，该系统每秒只更新60次gamepad状态



> 60gamepad



> 60gamepad



> 60gamepad



> 目前，该系统每秒只更新60次gamepad状态

The handle control of bedrock version is very smooth. When playing pojav launcher, the number of frames is 200fps, which is actually the same as 60fps of bedrock version, but the handle control of bedrock version is very smooth, and the handle control of pojav launcher is not smooth

**Comment by Mathias-Boulay** [comment]
*sigh* I see you are far from well versed in english.
I'm asking you what is your android device, so I can check the specification associated to it

**Comment by jiuhui0415** [comment]
> 我问你你的android设备是什么，所以我可以检查它的规格

My device is redmi note7pro

**Comment by jiuhui0415** [comment]
> 安卓系统

My device is redmi note7pro Android 10

**Comment by jiuhui0415** [comment]
> 目前，该系统每秒只更新60次gamepad状态

The handle control of bedrock version is very smooth. When playing pojav launcher, the number of frames is 200fps, which is actually the same as 60fps of bedrock version, but the handle control of bedrock version is very smooth, and the handle control of pojav launcher is not smooth

**Comment by jiuhui0415** [comment]
> 安卓系统

I used someone else's client, named cmpack, with a high number of frames. The single world flat map is 280fps. There is no doubt about my fluency, which is the problem of your handle mapping

**Comment by Mathias-Boulay** [comment]
I feel like you should use another machine translator.
Anyway, the bug is fixed and will arrive in a future update

**Comment by jiuhui0415** [comment]
> 无论如何，这个bug已经修复，并将在以后的更新中出现

Thanks, but it has nothing to do with my device. My FPS is very high. When I play the bedrock version, the handle control is very smooth, but no matter how you can fix the mapping and improve the mapping, it is good

**Comment by jiuhui0415** [comment]
> 无论如何，这个bug已经修复，并将在以后的更新中出现

If you have fixed the mapping, or have improved the mapping, and will appear in future updates, you are the best and the best 😘

**Comment by Mathias-Boulay** [comment]
#2211
