### ISSUE TITLE
When playing games with the Xbox handle, the viewing angle is not smooth[BUG] <Short description>

### ISSUE THREAD

**Issue by jiuhui0415** [PojavLauncherTeam/PojavLauncher#2137]
### Describe the bug

When playing games with the Xbox handle, the viewing angle is not smooth    Even if the game frame number is 200fps, the control of the game perspective is still not smooth. I suspect it is a mapping problem

### Steps To Reproduce

```markdown
When playing games with the Xbox handle, the viewing angle is not smooth   Even if the game frame number is 200fps, the control of the game perspective is still not smooth. I suspect it is a mapping problem
```

### Expected Behavior

I hope to improve the mapping so that the control perspective will be more smooth   It's easy to play games on your mobile device using the Xbox handle

### Platform

```markdown
－设备型号：－CPU架构：aarch64－Android版本：10－PojavLauncher版本：
```

### Anything else?

When playing games with the Xbox handle, the viewing angle is not smooth      Even if the game frame number is 200fps, the control of the game perspective is still not smooth. I suspect it is a mapping problem

**Comment by khanhduytran0** [comment]
@jiuhui0415 
![AA32828F-5BF3-4132-BFB1-BBD44BADC82D](https://user-images.githubusercontent.com/40482367/137603358-fe0f7be7-5b38-4f62-be0d-25aec9c8747b.png)
