### ISSUE TITLE
Too many crashes

### ISSUE THREAD

**Issue by Andy-s353** [PojavLauncherTeam/PojavLauncher#2139]
### Describe the bug

I recently started playing on hypixel using this Launcher (with my Premium account) and even though it's pretty useful for quickly dell'ing stuff, there is one problem: the amount of times this thing crashes in just 3 minutes! 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7358873/latestlog.txt)

here's the log

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Go on Hypixel (or probably any other server) 
3. Go in skyblock and try going to the hub by going through the portal
4. You'll probably crash (if not Replay this a few times)
```

### Expected Behavior

I expect the game to run smoothly

### Platform

```markdown
- Device model: Mi 8 Pro/128gb
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: version 3.3.1.1
```

### Anything else?

It is also possible that my device is just not good enough to run Pojavlauncher but i dont think this is the case

**Comment by Andy-s353** [comment]
Also sorry for the strange grammatical errors but the autocorrector is really annoying

**Comment by khanhduytran0** [comment]
1.8.9 requires VBO to be enabled.

**Comment by WesleyVanNeck** [comment]
Outdated version
