### ISSUE TITLE
[BUG] <servers crash on 1.12.2 optifine>

### ISSUE THREAD

**Issue by Yashjbk17** [PojavLauncherTeam/PojavLauncher#2140]
### Describe the bug

Whenever i enter a server on 1.12.2 with 1.1.4 renderer the pojav launcher crashes(this bug only happens on 1.12.2 )

### Steps To Reproduce

```markdown
1.start 1.12.2 optifine
2.join a server
3.launcher crashes
```

### Expected Behavior

I expects the launcher to do not crash on servers 

### Platform

```markdown
- Device model: vivo 1804
- CPU architecture: aarch32
- Android version: 8
- PojavLauncher version:latest
```

**Comment by WesleyVanNeck** [comment]
latest isnt a version

**Comment by WesleyVanNeck** [comment]
no log

**Comment by Mathias-Boulay** [comment]
Still no log, and no update regarding other renderers

**Comment by Yashjbk17** [comment]
> Still no log, and no update regarding other renderers

How do i upload a photo or a vedio i don't know when it is going to crash

**Comment by Yashjbk17** [comment]
I have changed the JVM argument now it dosen't crash
