### ISSUE TITLE
[BUG] <Pojavlauncher>

### ISSUE THREAD

**Issue by Wantz982** [PojavLauncherTeam/PojavLauncher#2141]
### Describe the bug

The game is giving drops, kicking it out of the game please fix it and auto ram will come

### The log file and images/videos

The game is giving drops, kicking it out of the game please fix it and auto ram will come

### Steps To Reproduce

```markdown
The game is giving drops, kicking it out of the game please fix it and auto ram will come
```

### Expected Behavior

The game opens late, because it is a mod, let auto ram come 

### Platform

```markdown
- Device model: Huawei P Smart Z
- CPU architecture: 
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

auto ram come

**Comment by Mathias-Boulay** [comment]
Something in the background kills pojav.
Try to disable battery optimization in your android settings ?

**Comment by Paquitogamer** [comment]
Ay un bug que es que no me puedo meter a optifine 1.16.5 ni a forge 1.16.5 lo pueden arreglar a mí me dice un mensaje       no protocol:
