### ISSUE TITLE
Some suggestions about crosshair cannot be rendered

### ISSUE THREAD

**Issue by plotaa** [PojavLauncherTeam/PojavLauncher#2142]
### Is this request related to a bug?

Yes.(And this is my suggestion about it)
(It's about crosshair cannot be render)

### Describe the request.

Original shaders/core/rendertype_lines.(vsh,json and fsh) replace assets-v0.zip to the same name in assets/minecraft/shaders/core(resourcepack)
This is my suggestion to fix that bug.

### Anything else?

I tested and that works.
Here is screenshot
![Screenshot_20211019_124712_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/79216627/137846462-28ab4602-89d8-46c6-9afc-0713cb15da58.jpg)

**Comment by ajit850** [comment]
This is bug or request?

**Comment by NotAHero04** [comment]
This bug is listed as a known issue. The developers will do their best to fix it.

**Comment by plotaa** [comment]
> This is bug or request?

It's a request

**Comment by plotaa** [comment]
> This bug is listed as a known issue. The developers will do their best to fix it.

But now this is a way

**Comment by tipnsp** [comment]
hey plotaa
（doge）

**Comment by plotaa** [comment]
> hey plotaa （doge）

Hey tipnsp😄

**Comment by plotaa** [comment]
@khanhduytran0 Execuse me. Can I send what'm i using of resourcepack to here? (It fixed that crosshair cannot be rendered. But it still can't run in optifine)

**Comment by Mathias-Boulay** [comment]
Won't be fixed, since it is a workaround and not a permanent solution
