### ISSUE TITLE
[BUG] How to fix this

### ISSUE THREAD

**Issue by Isan1736** [PojavLauncherTeam/PojavLauncher#2143]
### Describe the bug

Texture pack bugged

### The log file and images/videos

![Screenshot_20211018_203939](https://user-images.githubusercontent.com/84948958/137743244-3cc8369d-e833-447a-afa0-66ff20c78b02.jpg)

### Steps To Reproduce

```markdown
1.start pojavlaucnher 1.8.9 version
2.play in a world
3.when i see the sword is bugged
```

### Expected Behavior

Bug

### Platform

```markdown
- Device model:vivo y93
- CPU architecture:aarch64  mediatek helio p22
- Android version:8
- PojavLauncher version:crocus_v3
```

### Anything else?

When i see on youtube there pojavlauncher texture didn't bug

**Comment by Paquitogamer** [comment]
Ay un bug de la aplicación que es que me saca aunque tenga más de la memoria ram asignada y eso me enfada en beidgead en universocraft ya que se llena muy rápido

**Comment by Isan1736** [comment]
English please

**Comment by Mathias-Boulay** [comment]
Not the first time I see this vivo doing shit, am I wrong ?
