### ISSUE TITLE
Will this work with Xbox Gamepass?

### ISSUE THREAD

**Issue by MysticAx0lotl** [PojavLauncherTeam/PojavLauncher#2145]
Hello! I read that MC Java will be coming to Xbox Gamepass. How will that work with PoJav? Will I log in with the account that's subscribed to Gamepass, or will there be a way to directly copy the .jar to my Android device (similar to how the Raspbian MC Launcher works)? Thank you!

Edit: If Gamepass/PoJav compatibilty is account-based, will it work with Family Sharing?

**Comment by Mathias-Boulay** [comment]
We don't do the authentication server, microsoft does.
So if it works, it means your account get some sort of privilege from buying gamepass
