### ISSUE TITLE
Thêm lưu dữ liệu trên thẻ SD đi ad ơi

### ISSUE THREAD

**Issue by tuongtacdao** [PojavLauncherTeam/PojavLauncher#2146]
### Anything else?

Thêm lưu dữ liệu trên thẻ SD đi ad ơi

**Comment by Mathias-Boulay** [comment]
Ah yes,definitely english.

**Comment by Mathias-Boulay** [comment]
This could be added though, I may take a proper look at it.

**Comment by only-surviv-cre-cant-need-save-worlds** [comment]
Dùng tiếng Anh đi bạn

**Comment by Mathias-Boulay** [comment]
Technically available through the adoptable storage
