### ISSUE TITLE
Microsoft login on quest not working

### ISSUE THREAD

**Issue by Day4y3** [PojavLauncherTeam/PojavLauncher#2147]
### Describe the bug

when i press on microsoft login the program crashes

### Steps To Reproduce

```markdown
start pojav.
press on microsoft login
```

### Expected Behavior

login with microsoft acc

### Platform

```markdown
oculus quest 2
```

**Comment by Mathias-Boulay** [comment]
hmmm
maybe tell use the pojav version ?
Get some video footage ?
You know, basic stuff

**Comment by khanhduytran0** [comment]
Closing until further response.
