### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Vghggggjgjb** [PojavLauncherTeam/PojavLauncher#2148]
### Describe the bug

Departure

### The log file and images/videos

The file does not rush for chrome, I threw the file on Google disk here is the linkhttps://drive.google.com/file/d/1FW89iNz2S64De7B3oLts6wFspF2Rn9Sh/view?usp=drivesdk

### Steps To Reproduce

```markdown
I launch the launcher, I choose. the version is launched then instantly crashes
```

### Expected Behavior

....

### Platform

```markdown
- Device model: Dexp k18/32
- CPU architecture: Xz
- Android version: 9
- PojavLauncher version: the last
```

**Comment by rscDMTalt** [comment]
Uhh.... since when did `xz` exist?
iirc the ONLY cpu architecture as of now are `x64, x32, x86, and x86_64`
Also, "the last" is NOT a version.

**Comment by Vghggggjgjb** [comment]
found out 32-bit ARMv7

чт, 21 окт. 2021 г., 8:54 rscDMTalt ***@***.***>:

**Comment by Vghggggjgjb** [comment]
what should I do?

**Comment by asdfugil** [comment]
> Uhh.... since when did `xz` exist?
> iirc the ONLY cpu architecture as of now are `x64, x32, x86, and x86_64`
> Also, "the last" is NOT a version.

don't think PojavLauncher support the x32 abi, so no x32

**Comment by khanhduytran0** [comment]
> > Uhh.... since when did `xz` exist?
> > iirc the ONLY cpu architecture as of now are `x64, x32, x86, and x86_64`
> > Also, "the last" is NOT a version.
> 
> don't think PojavLauncher support the x32 abi, so no x32

also, x64 is duplicated with x86_64 :trollface:

**Comment by Heckervar** [comment]
The subject issue if mouse moves it crashes
