### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Vghggggjgjb** [PojavLauncherTeam/PojavLauncher#2149]
### Describe the request.

Do 1. launch arguments
2. make a mod installer so that you can specify the mod and he copies it to the folder
3.Make delay start somewhat. Versions simultaneously
4.Make support Android 7

**Comment by WesleyVanNeck** [comment]
Android 7 is suported

**Comment by WesleyVanNeck** [comment]
Launch arguments is just a no

**Comment by WesleyVanNeck** [comment]
About the 3rd one not pasible as we're not going mod the client

**Comment by khanhduytran0** [comment]
> 1. launch arguments

just modify the json file to add additional arguments.
> 2. make a mod installer so that you can specify the mod and he copies it to the folder

Mod installer is not used to copy, it’s used to launch the installer. In case you want specify mod for specific versions, per-version config exists, simply long-press the version selector then config it.

> 3.Make delay start somewhat. Versions simultaneously

Why delay? I see no point doing here. Launch multiple versions at the same time? java doesn’t support that
