### ISSUE TITLE
In custom control some files are not working like failed to load

### ISSUE THREAD

**Issue by Raspinder102** [PojavLauncherTeam/PojavLauncher#2151]
### Describe the bug

Help me please

### The log file and images/videos

Help

### Steps To Reproduce

```markdown
Help
```

### Expected Behavior

Help

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
Help
```

### Anything else?

Help

**Comment by herzokun** [comment]
Tf man

**Comment by NotAHero04** [comment]
I’d say that some old controls don’t work with the current control implementation, but it will be easier for us to diagnose if you can send the error you encountered here.

**Comment by InfiniXDerg** [comment]
- Device model: your device
- CPU architecture: go to AIDA64 and check CPU
- Android version: go about phone
- PojavLauncher version: Github, Debug or Playsotre

**Comment by Mathias-Boulay** [comment]
Send logs, screen footage and fucking context.
Or get terminated
