### ISSUE TITLE
No more cracked only servers!

### ISSUE THREAD

**Issue by Noahgamez2009** [PojavLauncherTeam/PojavLauncher#2152]
### Describe the request.

I really want to go on Hypixel and other servers can you guys please cracked servers only?

### Anything else?

remove the thing

**Comment by InfiniXDerg** [comment]
If cracked servers disapears i Will cant enter to my Friends server with my premium acc lul

**Comment by khanhduytran0** [comment]
> No more cracked only servers!

That means you want to remove cracked servers support ~~with the power of the upcoming local mode~~.

> I really want to go on Hypixel and other servers can you guys please cracked servers only?

We don’t own Hypixel to make it cracked. Buy the game to play it. If you have money for a powerful enough phone and an internet connection, why not for a game?
