### ISSUE TITLE
[BUG] <not accessing my phone's storage>

### ISSUE THREAD

**Issue by Phantomishant303** [PojavLauncherTeam/PojavLauncher#2153]
### Describe the bug

When I installed it after uninstalling it coz I have to take my ram is not to go down from  4gb so I remember that I watched a video in which the user was telling the reasons why your phone's ram go's low and  and the best thing is that do not update any app just  uninstall it and download again with this the ram will not go's low and my phone's ram was 4gb as I said so I downloaded it from Google Play Store but the page named 'PojavLauncher wants to acces your storage ' is not coming I tried by uninstall it again and again but the page was not coming so how I can install custom keyboard and forge optifine labymod luner client and any mod. Plz make a solution on this 

### The log file and images/videos

When I installed it after uninstalling it coz I have to take my ram is not to go down from  4gb so I remember that I watched a video in which the user was telling the reasons why your phone's ram go's low and  and the best thing is that do not update any app just  uninstall it and download again with this the ram will not go's low and my phone's ram was 4gb as I said so I downloaded it from Google Play Store but the page named 'PojavLauncher wants to acces your storage ' is not coming I tried by uninstall it again and again but the page was not coming so how I can install custom keyboard and forge optifine labymod luner client and any mod. Plz make a solution on this 

### Steps To Reproduce

```markdown
1.start pojav launcher after nwewly installing it give it permission to access storage
```

### Expected Behavior

I thought it will access my phone's storage
But it not

### Platform

```markdown
- Device model: M2004J19C(lancelot_in)
- CPU architecture: aarch 64
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

When I installed it after uninstalling it coz I have to take my ram is not to go down from  4gb so I remember that I watched a video in which the user was telling the reasons why your phone's ram go's low and  and the best thing is that do not update any app just  uninstall it and download again with this the ram will not go's low and my phone's ram was 4gb as I said so I downloaded it from Google Play Store but the page named 'PojavLauncher wants to acces your storage ' is not coming I tried by uninstall it again and again but the page was not coming so how I can install custom keyboard and forge optifine labymod luner client and any mod. Plz make a solution on this

**Comment by NotAHero04** [comment]
The new file directory is in /sdcard/Android/data/net.kdt.pojavlaunch[.debug]/files. You need to use a 3rd party file manager (like ZArchiver) to have access to it.

**Comment by Mathias-Boulay** [comment]
You didn't read the fucking message upon the first launch, did you ?
You can move the old folder content to the new public app directory.

An app private/public data directory don't need your permission to write stuff

**Comment by Phantomishant303** [comment]
I did the folder was showing but after files no folder was there and also I
maked a world and played on it but no files there
