### ISSUE TITLE
bugs list wsa windows 11 

### ISSUE THREAD

**Issue by WesleyVanNeck** [PojavLauncherTeam/PojavLauncher#2154]
bugs on wsa

- zink doesnt work
- no mouse capture (workaround use a controller)
- vgpu doesnt work
- its kinda slow
- hard to install
- some version fullscreen is broken

**Comment by Mathias-Boulay** [comment]
Are we supposed to fix what Microsoft broke ?

**Comment by WesleyVanNeck** [comment]
> Are we supposed to fix what Microsoft broke ?

thats why i set it as wont fix

**Comment by khanhduytran0** [comment]
There’s no point to run Pojav on WSA unless for testing purpose.
