### ISSUE TITLE
BUG?idk

### ISSUE THREAD

**Issue by Rrrrr0000r** [PojavLauncherTeam/PojavLauncher#2155]
### Describe the bug

Why I cant login
![_20211023_183221](https://user-images.githubusercontent.com/93035884/138552778-054d037e-5f50-4d04-82a0-75aa67173dfb.JPG)

### The log file and images/videos

Help

### Steps To Reproduce

```markdown
I can't log in since October 19th but I haven't moved anything
```

### Expected Behavior

I hope I can log in to this game again

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by EnderBrine99FOX** [comment]
You Don't Have Java Account

**Comment by Rrrrr0000r** [comment]
> 您沒有 Java 帳戶

I have

**Comment by WesleyVanNeck** [comment]
you didnt migrate your account

**Comment by WesleyVanNeck** [comment]
mojang to microsoft

**Comment by khanhduytran0** [comment]
> you didnt migrate your account

In this case, he did, it literally said "Migrated"

**Comment by khanhduytran0** [comment]
@Rrrrr0000r why do you still use Mojang login after migrated to Microsoft?
