### ISSUE TITLE
Premium account login failed

### ISSUE THREAD

**Issue by RayZxyo** [PojavLauncherTeam/PojavLauncher#2156]
### Describe the bug

can anyone explain how this can happen?

### The log file and images/videos

![Screenshot_20211023-192021_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/91876145/138553909-7cc3d411-0546-4844-95d0-54d3ac8b9bbc.png)
![Screenshot_20211023-192027_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/91876145/138553912-6fbb4b1c-9f5e-454c-bf80-c4cbfcad5357.png)

### Steps To Reproduce

```markdown
empty
```

### Expected Behavior

empty

### Platform

```markdown
- Device model: Samsung A50
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210206
```

### Anything else?

RayZxyo#1219 Discord

**Comment by WesleyVanNeck** [comment]
outdated launcher

**Comment by RayZxyo** [comment]
I have updated Pojav (Latest Release) is there anything else I can do?

**Comment by WesleyVanNeck** [comment]
latest release isnt a version

**Comment by WesleyVanNeck** [comment]
its says your login info is wrong

**Comment by VijuGamer** [comment]
empty

**Comment by VijuGamer** [comment]
VijuGamer

**Comment by VijuGamer** [comment]
Priya makaan 3
