### ISSUE TITLE
Key repair reminder

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2157]
### Describe the bug

Key failure

### The log file and images/videos

[Forced card bug log](https://www.laogoupan.com/b28613) 

### Steps To Reproduce

```markdown
1.Enter the game
2.Enter map
3.Accidentally made an operation
4.Left / right key failure
```

### Expected Behavior

I hope it won't go wrong again

### Platform

```markdown
- Device model: HONOR 30 青春版
- CPU architecture: MediaTek MT6873 5G
- Harmony version: Harmony 2.0.0.185
- PojavLauncher version: crocus-88-fca386ca6-v3_openjdk
```

### Anything else?

I don't know if I can open this link to download？

**Comment by Mathias-Boulay** [comment]
Oh, people using up to date versions of the launcher are rare right now.
Can you provide us video footage to help us reproduce the bug ?

**Comment by Mathias-Boulay** [comment]
I mean, you seem to have provided a video but I can't to download it (maybe restrictions from my end)

**Comment by aaaapai** [comment]
> I mean, you seem to have provided a video but I can't to download it (maybe restrictions from my end)

Mobile phone point＂电信下载＂，Computer Click＂普通下载＂，

**Comment by aaaapai** [comment]
> I mean, you seem to have provided a video but I can't to download it (maybe restrictions from my end)

Try it

**Comment by aaaapai** [comment]
> I mean, you seem to have provided a video but I can't to download it (maybe restrictions from my end)

This bug can be triggered by carelessness without your knowledge

**Comment by aaaapai** [comment]
> I smell 69 commits of not doing English
> 
> Please, speak English.

No way, with a translator

**Comment by aaaapai** [comment]
> I smell 69 commits of not doing English
> 
> Please, speak English.

Machine translation
