### ISSUE TITLE
My game eventually crashes or few seconds after the world has loaded

### ISSUE THREAD

**Issue by FortiethSwing61** [PojavLauncherTeam/PojavLauncher#2161]
I hate this bug that when this happens, I had to wait another 2 minutes to open it again 

       My specs
                      Android 8.1.0
                      RAM 2GB
                      ROM 16GB
                      Snapdragon 450
                      Adreno 506
                      64 bit
                      Model CPH1853
                      Brand  OPPO

**Comment by khanhduytran0** [comment]
Nothing more? Who knows what Minecraft version were you running? Log? Where’s the form? <Ins>Please use GitHub web in order to fill into the form.</ins>

**Comment by FortiethSwing61** [comment]
> Nothing more? Who knows what Minecraft version were you running? Log? Where’s the form? <Ins>Please use GitHub web in order to fill into the form.</ins>

I'm playing on 1.14.4 with Optifine, it doesn't leave any messages when it crashes

**Comment by NotAHero04** [comment]
@FortiethSwing61 where is the log bro

**Comment by FortiethSwing61** [comment]
> @FortiethSwing61 where is the log bro

The latestlog.txt file doesn't leave anything related to the crash
