### ISSUE TITLE
[BUG]there a bug where I can't download Forge 36.2.0

### ISSUE THREAD

**Issue by gogetaBlueGod** [PojavLauncherTeam/PojavLauncher#2164]
### Describe the bug

There a bug where I can't download Forge 36.2.0 it is very annoying please no hate I'm just confuse with this

### The log file and images/videos

#bug

https://user-images.githubusercontent.com/85514221/138621539-067ba2fa-cffc-4292-8690-5239ed675ec3.mp4

### Steps To Reproduce

```markdown
1.it can't me download the Forge 36.2.0 it is somehow not show the version in version I'm getting annoying by this
```

### Expected Behavior

There no bug with launch

### Platform

```markdown
- Device model:Oppo f9 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: 3.3.1.1
```

### Anything else?

GOD HELP ME

**Comment by gogetaBlueGod** [comment]
Does anyone happen this thing?

**Comment by ajit850** [comment]
Which runtime you use

**Comment by gogetaBlueGod** [comment]
I don't know I use APK one I download from Pojav Launcher web it self

**Comment by gogetaBlueGod** [comment]
It is java 8 the runtime

**Comment by khanhduytran0** [comment]
Bruh, you have a ~~damn :trollface:~~ outdated build, please go to Play Store to get latest, or go to GitHub Actions.

**Comment by gogetaBlueGod** [comment]
Oh thx!
