### ISSUE TITLE
1.17.10 not working.

### ISSUE THREAD

**Issue by Noahgamez2009** [PojavLauncherTeam/PojavLauncher#2166]
### Describe the bug

for some reason ever time i try to play 1.17.1 or 1.17.10 it always says in error?

### The log file and images/videos

![Screenshot 2021-10-25 6 23 26 AM](https://user-images.githubusercontent.com/84477315/138679536-035e9b2e-d928-46e1-850f-46a03f20f37b.png)

### Steps To Reproduce

```markdown
so I go on Pojav launcher and change the version to 1.17.10 and i kicks me off?
```

### Expected Behavior

i expect the game to go on for 1.17

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 1.8.9
```

### Anything else?

please tell me what to do to fix this?
![Screenshot 2021-10-25 6 23 26 AM](https://user-images.githubusercontent.com/84477315/138679749-9164c0e9-f038-42d1-aeac-9647afec0d32.png)

**Comment by WesleyVanNeck** [comment]
Get java 17

**Comment by Noahgamez2009** [comment]
how and whats java 17

**Comment by khanhduytran0** [comment]
> how and whats java 17
> […](#)

the whole instruction was put in #2162 (https://pojavlauncherteam.github.io/updates/117.html)
<ins>please read the whole of them before opening any issues related to 1.17</ins>
