### ISSUE TITLE
1.17.1 and 1.17.10 not working?🤔

### ISSUE THREAD

**Issue by Noahgamez2009** [PojavLauncherTeam/PojavLauncher#2167]
### Describe the bug

so every time on PojavLauncher I try to change my Minecraft Version to 1.17.1 and 1.17.10 it always say's and Error?
I have no clue why this is happening for me.

### The log file and images/videos

![Screenshot 2021-10-25 6 23 26 AM](https://user-images.githubusercontent.com/84477315/138688767-7a112555-8986-4601-bf21-9b9e39139b21.png)

### Steps To Reproduce

```markdown
I have no clue how to Reproduce this bug or Glitch.
```

### Expected Behavior

I Expect it to go on 1.17.10 or 1.17.1.

![Screenshot 2021-10-25 6 23 26 AM](https://user-images.githubusercontent.com/84477315/138688915-257a2fa5-4fbc-4d1b-b697-32372e85209b.png)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Please tell me what I need to do to fix this

**Comment by khanhduytran0** [comment]
I told you what to do in the previous issue
> the whole instruction was put in #2162 (https://pojavlauncherteam.github.io/updates/117.html)
please read the whole of them before opening any issues related to 1.17
@Noahgamez2009

**Comment by khanhduytran0** [comment]
Read it. We have no time to deal with your repost.
