### ISSUE TITLE
[BUG] <when I increase ram to more than 277 it crash And say exite code 1  >

### ISSUE THREAD

**Issue by AliMaazKhan** [PojavLauncherTeam/PojavLauncher#2169]
### Describe the bug

when I increase ram to more than 277 it crash And say exite code 1

### Steps To Reproduce

```markdown
1 start pojavlauncher
2 start game
```

### Expected Behavior

Game needs to start I haven't enough ram but it should  start when I  give ram to 300 or 400 or more

### Platform

```markdown
- Device model: Samsung galaxy tab A
- CPU architecture: 32bit
- Android version: 7
- PojavLauncher version: jdk_crouks_3
```

### Anything else?

I know spelling  And some information is wrong but plz help

**Comment by WesleyVanNeck** [comment]
thats a limitation of 32 bit
