### ISSUE TITLE
[F-Req] When will render zink be optimized? 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2170]
### Is this request related to a bug?

Render zink has very few fps unlike other renders:
![Screenshot_20211026_202158_net kdt pojavlaunch](https://user-images.githubusercontent.com/75908293/138931381-c88201e4-d965-42ec-bf9d-75c5197bd21d.jpg)
![Screenshot_20211026_201742_net kdt pojavlaunch](https://user-images.githubusercontent.com/75908293/138931399-de6a8041-b0c3-497f-9984-4fdd78837f6a.jpg)

### Describe the request.

Is render zink optimization possible in the near future? Since only it supports opengl 4.6 and with it you can fully run mods such as immesive portals and shaders.

**Comment by InfiniXDerg** [comment]
Better buy a PC...

**Comment by Iarkont** [comment]
> Лучше купите компьютер...



> Better buy a PC...

I don't have the money for it...

**Comment by Mathias-Boulay** [comment]
We don't develop the renderer, it is only meant for testing 😅

**Comment by CosineMath** [comment]
You may have a look on [virglrenderer](https://github.com/AOF-Dev/virglrenderer-android), which make fps a bit higher (~4 fps on my device) and almost no rendering error for MC 1.17.1 with GL 3.2 core.

**Comment by ghost** [comment]
> You may have a look on [virglrenderer](https://github.com/AOF-Dev/virglrenderer-android), which make fps a bit higher (~4 fps on my device) and almost no rendering error for MC 1.17.1 with GL 3.2 core.

How to add it on pojavlauncher

**Comment by CriticalRange** [comment]
> > You may have a look on [virglrenderer](https://github.com/AOF-Dev/virglrenderer-android), which make fps a bit higher (~4 fps on my device) and almost no rendering error for MC 1.17.1 with GL 3.2 core.
> 
> HOLY SHIT IT'S HIM

OMG HE'S BACK ?????
