### ISSUE TITLE
[F-Req] Add SD card support 

### ISSUE THREAD

**Issue by scihi** [PojavLauncherTeam/PojavLauncher#2172]
### Is this request related to a bug?

No! This is to add support

### Describe the request.

Add SD card support for storing data, this might solve the storage issue in some low-end devices.

### Anything else?

No! Nothing to elaborate. But ya this will decrease the performance of the PL but I still think 🤔 this support should be added

**Comment by ghost** [comment]
Google : no

**Comment by scihi** [comment]
> Google : no

What?????

**Comment by netkv** [comment]
sd cards dont have filesystem which supports permissions so stuff cant be executed from them

**Comment by scihi** [comment]
> sd cards dont have filesystem which supports permissions so stuff cant be executed from them

We can store it in external folder 📂 not in filesystem

**Comment by netkv** [comment]
good luck storing anything without filesystem

**Comment by mchnjt** [comment]
Funny how I can execute my games from an SDcard, guess windows and Android is different

**Comment by mchnjt** [comment]
*different

**Comment by netkv** [comment]
> Funny how I can execute my games from an SDcard, guess windows and Android is different

well yeah because windows doesnt have file permission at all, or atleast it doesnt uses them iirc

**Comment by asdfugil** [comment]
Nah, it's not because of the sdcard but rather the filesystem it is formatted with.

**Comment by asdfugil** [comment]
Ext4 sdcard moment, also it must not be written via sdcardfs then it could work.
