### ISSUE TITLE
21w43a Crashing

### ISSUE THREAD

**Issue by CharredMist** [PojavLauncherTeam/PojavLauncher#2173]
### Describe the bug

When I launch 21w43a, it crashes and says "Application exited with code 1" I tried to change renderer and jvm arguments, it still not working.
And yes i have assets-v0.zip
(I dunno it s a bug)

### The log file and images/videos

Crash log:

---- Minecraft Crash Report ---- // Surprise! Haha. Well, this is awkward. Time: 28.10.2021 15:40 Description: Rendering overlay java.lang.RuntimeException: could not reload shaders 	at eor.b(SourceFile:496) 	at eor.a(SourceFile:384) 	at aek.a(SourceFile:15) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:207) 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:194) 	at drd.e(SourceFile:310) 	at dxc.f(SourceFile:1139) 	at dxc.e(SourceFile:730) 	at net.minecraft.client.main.Main.main(SourceFile:238) Caused by: xj: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (Default, rendertype_solid) : ERROR: 1:16: '/' : wrong operand types no operation '/' exists that takes a left-hand operand of type 'in 2-component vector of int' and a right operand of type 'const float' (or there is no acceptable conversion) ERROR: 1:16: 'clamp' : no matching overloaded function found ERROR: 1:16: 'texture' : no matching overloaded function found ERROR: 1:16: 'return' : function return is not matching type: ERROR: 4 compilation errors. No code generated. 	at xj.a(SourceFile:48) 	at epj.<init>(SourceFile:197) 	at eor.b(SourceFile:452) 	... 118 more Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_solid) : ERROR: 1:16: '/' : wrong operand types no operation '/' exists that takes a left-hand operand of type 'in 2-component vector of int' and a right operand of type 'const float' (or there is no acceptable conversion) ERROR: 1:16: 'clamp' : no matching overloaded function found ERROR: 1:16: 'texture' : no matching overloaded function found ERROR: 1:16: 'return' : function return is not matching type: ERROR: 4 compilation errors. No code generated. 	at drm.b(SourceFile:72) 	at drm.a(SourceFile:54) 	at epj.a(SourceFile:237) 	at epj.<init>(SourceFile:179) 	... 119 more A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Stacktrace: 	at eor.b(SourceFile:496) 	at eor.a(SourceFile:384) 	at aek.a(SourceFile:15) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at aeo.a(SourceFile:71) 	at atg.execute(SourceFile:101) 	at aeo.a(SourceFile:70) 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) 	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:207) 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:194) -- Overlay render details -- Details: 	Overlay name: ebs Stacktrace: 	at eor.a(SourceFile:866) 	at dxc.f(SourceFile:1114) 	at dxc.e(SourceFile:730) 	at net.minecraft.client.main.Main.main(SourceFile:238) -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: No 	Packs: Default -- System Details -- Details: 	Minecraft Version: 21w43a 	Minecraft Version ID: 21w43a 	Operating System: Linux (aarch64) version Android-11 	Java Version: 17-internal, N/A 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 1906835456 bytes (1818 MiB) / 3342860288 bytes (3188 MiB) up to 3342860288 bytes (3188 MiB) 	CPUs: 8 	Processor Vendor: 0x51 	Processor Name: AArch64 Processor rev 14 (aarch64) 	Identifier: 0x51 Family 8 Model 0x804 Stepping r0xdp14 	Microarchitecture: unknown 	Frequency (GHz): -0,00 	Number of physical packages: 1 	Number of physical CPUs: 1 	Number of logical CPUs: 8 	Graphics card #0 name: unknown 	Graphics card #0 vendor: unknown 	Graphics card #0 VRAM (MB): 0,00 	Graphics card #0 deviceId: unknown 	Graphics card #0 versionInfo: unknown 	Virtual memory max (MB): 5507,88 	Virtual memory used (MB): 6633,23 	Swap memory total (MB): 2048,00 	Swap memory used (MB): 976,05 	JVM Flags: 2 total; -Xms3188M -Xmx3188M 	Launched Version: 21w43a 	Backend library: LWJGL version 3.2.3 SNAPSHOT 	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb 	Window size: 2400x1080 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is Modded: Probably not. Client jar signature and brand is untouched 	Type: Client (map_client.txt) 	Graphics mode: fast 	Resource Packs: 	Current Language: TÃ¼rkÃ§e (TÃ¼rkiye) 	CPU: 8x AArch64 Processor rev 14 (aarch64)

### Steps To Reproduce

```markdown
1:Start PojavLauncher and select user.
2:Activate snapshots (in settings)
3:install and run 21w43a
```

### Expected Behavior

It crashes

### Platform

```markdown
- Device model: Samsung A71 / 128GB
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Version
```

**Comment by CharredMist** [comment]
Pls help _me_

**Comment by Pgabrielmnecraft** [comment]
you're using the wrong assets-v0, I remember it looks like artDev created a new resource pack for 1.18

**Comment by CharredMist** [comment]
> you're using the wrong assets-v0, I remember it looks like artDev created a new resource pack for 1.18

Where can I get can u giveme link

**Comment by NotAHero04** [comment]
You can [join the PojavLauncher Discord server](https://discord.gg/zTaPmhu2) to get the patch. 21w43a is confirmed to work with it.
![7264AD90-7E3A-4F06-8F83-F341412C0CED](https://user-images.githubusercontent.com/84689840/139349720-55f958f8-06ef-47d7-aabd-acecdb9d7493.jpeg)

**Comment by CharredMist** [comment]
> You can [join the PojavLauncher Discord server](https://discord.gg/zTaPmhu2) to get the patch. 21w43a is confirmed to work with it.
> ![7264AD90-7E3A-4F06-8F83-F341412C0CED](https://user-images.githubusercontent.com/84689840/139349720-55f958f8-06ef-47d7-aabd-acecdb9d7493.jpeg)

Ok i joined but i cant see the message 
Can you send me message s link

**Comment by NotAHero04** [comment]
@ERENPROO ping me moment
