### ISSUE TITLE
1.8.9 Crash

### ISSUE THREAD

**Issue by 8SamPSH9** [PojavLauncherTeam/PojavLauncher#2174]
### Describe the bug

When i go to servers with 1.8.9 it's going to freeze and go back into pojavlauncher login page , without crash loghow to fix it😭😭😭🤔

### Steps To Reproduce

```markdown
1.Go to pojav
2.Launch 1.8.9 ver
3.Go in the server
4.Crash :|
```

### Expected Behavior

1.8.9 craaaaaaaaaaaaash

### Platform

```markdown
- Device model: Samsung galaxy a71/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher ver: 3.3.1.1 latest ver
```

**Comment by WesleyVanNeck** [comment]
Enable vbo also outdated version

**Comment by khanhduytran0** [comment]
> ### Expected Behavior
1.8.9 craaaaaaaaaaaaash

That’s what you expected :trollface:

**Comment by 8SamPSH9** [comment]
> Enable vbo also outdated version

It doesn't work☹

**Comment by Akashkakak** [comment]
> ### Describe the bug
> When i go to servers with 1.8.9 it's going to freeze and go back into pojavlauncher login page , without crash loghow to fix it😭😭😭🤔
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> ```gfm
> 1.Go to pojav
> 2.Launch 1.8.9 ver
> 3.Go in the server
> 4.Crash :|
> ```
> 
> ### Expected Behavior
> 1.8.9 craaaaaaaaaaaaash
> 
> ### Platform
> ```gfm
> - Device model: Samsung galaxy a71/128G
> - CPU architecture: aarch64
> - Android version: 11
> - PojavLauncher ver: 3.3.1.1 latest ver
> ```
> 
> ### Anything else?
> _No response_

I am also that problem 1.15 wasn't below versions is crashing. Fix that...._

**Comment by WesleyVanNeck** [comment]
> > ### Describe the bug
> > When i go to servers with 1.8.9 it's going to freeze and go back into pojavlauncher login page , without crash loghow to fix it😭😭😭🤔
> > ### The log file and images/videos
> > _No response_
> > ### Steps To Reproduce
> > ```
> > 1.Go to pojav
> > 2.Launch 1.8.9 ver
> > 3.Go in the server
> > 4.Crash :|
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > 1.8.9 craaaaaaaaaaaaash
> > ### Platform
> > ```
> > - Device model: Samsung galaxy a71/128G
> > - CPU architecture: aarch64
> > - Android version: 11
> > - PojavLauncher ver: 3.3.1.1 latest ver
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > _No response_
> 
> I am also that problem 1.15 wasn't below versions is crashing. Fix that...._

Stop commenting on a old issue also show latest log because only 1.8.9 has VBO issues

**Comment by CyanShulkerBox** [comment]
Mine too... Its started when I downloaded and activated some PVP texturepacks... And then I downloaded a CRACKED Badlion Client but its just a non-ending BLACK SCREEN... HELP

**Comment by ghost** [comment]
Yes

**Comment by CyanShulkerBox** [comment]
> Yes

**"YES"**!? Is the answer!?... Bruh im serious.

**Comment by ghost** [comment]
Play store pojav have one problem like old version are crashing in apk pojav I mean github pojav not have problem to old version but is have one problem render lag  so this apk pojav is under development

**Comment by ghost** [comment]
If you want to play old versions download the apk pojav or if you want to play smooth gameplay on Rander 10 between download the play store pojav but in play store pojav have one problem old versions are crashing okay

**Comment by CyanShulkerBox** [comment]
> Play store pojav have one problem like old version are crashing in apk pojav I mean github pojav not have problem to old version but is have one problem render lag so this apk pojav is under development

I wish i can play server on my phone that i am using now😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by ghost** [comment]
> > Play store pojav have one problem like old version are crashing in apk pojav I mean github pojav not have problem to old version but is have one problem render lag so this apk pojav is under development
> 
> I wish i can play server on my phone that i am using now😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

I don't understand

**Comment by CyanShulkerBox** [comment]
Pojavlauncher needs a Android 11 support

**Comment by CyanShulkerBox** [comment]
> 

What u dont understand?

**Comment by CyanShulkerBox** [comment]
> > > Play store pojav have one problem like old version are crashing in apk pojav I mean github pojav not have problem to old version but is have one problem render lag so this apk pojav is under development
> > 
> > 
> > I wish i can play server on my phone that i am using now😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭
> 
> I don't understand

What do u mean u dont understand??

**Comment by CyanShulkerBox** [comment]
> If you want to play old versions download the apk pojav or if you want to play smooth gameplay on Rander 10 between download the play store pojav but in play store pojav have one problem old versions are crashing okay

ooooooooooooo.... Can i have a old pojavlauncher?... Cause it has an autoram feature... And i cant find it anywhere😞

**Comment by CyanShulkerBox** [comment]
> > If you want to play old versions download the apk pojav or if you want to play smooth gameplay on Rander 10 between download the play store pojav but in play store pojav have one problem old versions are crashing okay
> 
> ooooooooooooo.... Can i have a old pojavlauncher?... Cause it has an autoram feature... And i cant find it anywhere😞

Thats why im crashing... I dont know how many is the specific Memory Allocation.

**Comment by ghost** [comment]
Keep it on 1000

**Comment by CyanShulkerBox** [comment]
> Keep it on 1000

Ok ill try TY

**Comment by CyanShulkerBox** [comment]
> Keep it on 1000

Ok ill try TY
