### ISSUE TITLE
[BUG] Texture glitch

### ISSUE THREAD

**Issue by Vincentheitzdi** [PojavLauncherTeam/PojavLauncher#2175]
### Describe the bug

this glitch make the texture like you are using xray glitch
version i used 1.14.4
I have tried all renderers but nothing works

### The log file and images/videos

#
![2021-10-28_14 44 26](https://user-images.githubusercontent.com/93362512/139370827-d1d8bc1f-f912-4361-9912-9a05bf1133fe.png)

### Steps To Reproduce

```markdown
I still can't tell you how to reproduce this bug
```

### Expected Behavior

I expect it's will be normal again

### Platform

```markdown
- Device model: Realme C3
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest realease crocus c3 openjdk
```

### Anything else?

nothing

**Comment by 1493028** [comment]
Turn on Fast Render In video settings -> performance -> Fast rendering:On

**Comment by khanhduytran0** [comment]
Closing until further response.
