### ISSUE TITLE
[BUG] Modular Powersuit for 1.12.2 Menu Bug

### ISSUE THREAD

**Issue by everclearecct** [PojavLauncherTeam/PojavLauncher#2176]
### Describe the bug

Open up the Tinker Table or entering any menus provided by this mod, the Menu won't display. if "Use Custom Font" option (provided by OptiFine) is enabled, White screen instead.

### The log file and images/videos

Due to the word limitation, here's the log file:
https://anonfiles.com/17w3kfRcuc/latest.log_txt
And here's the screenshot:
https://imgur.com/a/zVjHRtq

### Steps To Reproduce

```markdown
1.Start Pojav launcher
2.Launch the game
3.Open a World
4.Open up the Tinker table
```

### Expected Behavior

I expect the Menu shows up.

### Platform

```markdown
- Device model: Google Pixel 2 XL
- CPU architecture: aarch64
- Android version: 11 (DotOS 5.2 with GAPPS)
- PojavLauncher version: Latest Debug version
```

### Anything else?

Mod list:
> Forge 1.12.2 14.23.5.2855
> OptiFine HD U G5
> Buildcraft 7.99.24.8
> Energy Converter 1.3.7.30
> Industrial Foregoing 1.12.13-237
> Tesla CoreLib 1.10.18
> ForgeLin 1.8.4
> Future MC 0.2.7.3
> Forestry 5.8.4-422
> Applied Energetics 2 rv6-stable-7
> Numina 1.0.38
> Modular Powersuit 1.0.46
> Redstone Flux 2.1.1.1
> CoFHCore 4.6.6.1
> CoFHWorld 1.4.0.1
> Thermal Foundation 2.6.7.1
> Thermal Expansion 5.5.7.1
> CodeChickenLib 3.2.3.358
> Thermal Dynamics 2.5.6.1
> Thermal Cultivation 0.3.6.1
> Thermal Innovation 0.3.6.1
> BetterFPS 1.4.8
> FoamFix 0.9.4 Anarchy

I tried to delete OptiFine, BetterFPS and Foamfix, even changing the render engine, but it just won't show up the menu.

Latest version of mod fixed this issue, but it requires Minecraft version 1.16.5 and it's alpha stage

**Comment by khanhduytran0** [comment]
I have ~~69~~ things to tell you.
- Files and images can be uploaded to issue/comment through this option
![B18F1A73-2BE5-4B11-9AD1-B3FFBFB288D7](https://user-images.githubusercontent.com/40482367/139374598-b262b3ed-0153-4652-9e95-8d1b57446e85.jpeg)
- latestlog.txt ≠ latest.log. Renaming latest.log to latestlog.txt doesn’t make it to include launcher-specific informations (such as JVM arguments, launch directory, OpenGL rendering errors, etc...)
- Did you check pinned issues? If so, go to #1948 and describe mods problems there.
- Custom ROM drivers could be the issue.
