### ISSUE TITLE
[BUG] <mouse error>

### ISSUE THREAD

**Issue by Redpega123** [PojavLauncherTeam/PojavLauncher#2178]
### Describe the bug

when i enter the game my mouse does not hide to work

### The log file and images/videos

![image](https://user-images.githubusercontent.com/92668687/139398670-6a15f7d4-1aff-4e84-927c-4f73ba8fda9b.png)

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

idk

### Platform

```markdown
- Device model: j7 2016
- CPU architecture: 
- Android version: 7
- PojavLauncher version:
```

**Comment by LightestMC** [comment]
Have you tried click the [Mouse] button?

**Comment by LightestMC** [comment]
also what Minecraft version were you running?

**Comment by Redpega123** [comment]
I tried anything and I use 1.8.9

Vào 29 Th10, 2021 15:28, "A888" ***@***.***> đã viết:

**Comment by Mathias-Boulay** [comment]
Old pojav launhcer version, not supported
