### ISSUE TITLE
[F-Req] ffmpeg support for replay mod 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2179]
### Describe the request.

For full operation of replay mod you need ffmpeg but replay mod does not see ffmpeg even if it is installed. I know that ffmpeg works on Windows OC but on the phone worked with replay recording is also convenient. Is it possible to support ffmpeg on Pojavlauncher? If so, please add.

**Comment by khanhduytran0** [comment]
> For full operation of replay mod you need ffmpeg but replay mod does not see ffmpeg even if it is installed. 

Pojav doesn’t see FFmpeg installed from other places (such as Termux), it may work if you have root and copy FFmpeg into `/system/bin`. Built-in FFmpeg can be added, but still idk how to correctly add it.

**Comment by Iarkont** [comment]
> One question: why record your "gameplay" via minecraft itself when you can just record it externally (i.e XRecorder, that recorder that's built in with your phone, etc)

Replay mod gives more options than the built-in recording for example, it is necessary to record video from the side that is impossible with the built-in screen recording program

**Comment by Iarkont** [comment]
> Pojav doesn’t see FFmpeg installed from other places (such as Termux), it may work if you have root and copy FFmpeg into `/system/bin`. Built-in FFmpeg can be added, but still idk how to correctly add it.

Many will have problems with root as many users have Android 10+ and even more problems arise for users with smartphones huawei / honor (I just honor) to get root on huawei / honor you need to unlock the bootloader and to unlock it you need a special code to get almost impossible.

**Comment by WesleyVanNeck** [comment]
> > Pojav doesn’t see FFmpeg installed from other places (such as Termux), it may work if you have root and copy FFmpeg into `/system/bin`. Built-in FFmpeg can be added, but still idk how to correctly add it.
> 
> Many will have problems with root as many users have Android 10+ and even more problems arise for users with smartphones huawei / honor (I just honor) to get root on huawei / honor you need to unlock the bootloader and to unlock it you need a special code to get almost impossible.

then dont choose huawei or honor

**Comment by ajit850** [comment]
But it works in my mobile

**Comment by InfiniXDerg** [comment]
> But it works in my mobile

send proof or say goodbye

**Comment by ghost** [comment]
Make it work cause Vivo phones too can't get rooted easily please team also add redirection to certain in game link(like visit website in mod menu)

**Comment by Mathias-Boulay** [comment]
#2572
