### ISSUE TITLE
stretch screen option (1280x780) 

### ISSUE THREAD

**Issue by S0rk-jpg** [PojavLauncherTeam/PojavLauncher#2180]
### Is this request related to a bug?

Stretched screen gives better performance

### Describe the request.

I wish I could add a stretched canvas option

**Comment by S0rk-jpg** [comment]
I'm using a translator sorry anything

**Comment by Mathias-Boulay** [comment]
You will have to explain how using a stretched screen gives better performance.

**Comment by S0rk-jpg** [comment]
> Você terá que explicar como o uso de uma tela esticada proporciona um melhor desempenho.
as in other games it only reduces the resolution and the pixels (pojav already has a resolution option but it doesn't stretch the screen)

**Comment by S0rk-jpg** [comment]
> Você terá que explicar como o uso de uma tela esticada proporciona um melhor desempenho.

To be honest I would just like to have a stretched canvas

**Comment by Mathias-Boulay** [comment]
but the game is supposed to be fullscreen already
If you have a notch and have a device on android 9+ you can ignore the notch in settings

**Comment by S0rk-jpg** [comment]
> mas o jogo já deve estar em tela cheia Se você tiver um entalhe e tiver um dispositivo com Android 9+ vocêpoderá ignorar o entalhe nas configurações

It's this way 
![Screenshot_20211101-175405](https://user-images.githubusercontent.com/82401412/139740975-eb665dc2-2c71-44f9-84f9-339c6632eedd.png)


-

**Comment by S0rk-jpg** [comment]
> mas o jogo já deve estar em tela cheia Se você tiver um entalhe e tiver um dispositivo com Android 9+ vocêpoderá ignorar o entalhe nas configurações

Can this be added to pojav? I would really like to play with stretched screen

**Comment by Mathias-Boulay** [comment]
Check out the settings menu
