### ISSUE TITLE
Support single level.dat save

### ISSUE THREAD

**Issue by only-surviv-cre-cant-need-save-worlds** [PojavLauncherTeam/PojavLauncher#2183]
### Is this request related to a bug?

Support versions use single level.dat file to save world, when i play those version, the app crash

### Describe the request.

Added

### Anything else?

Pls don't reply with "Just Don't play those versions" or anything like that :(

**Comment by ajit850** [comment]
Wrong tamplate

**Comment by netkv** [comment]
what versions are that?

**Comment by WesleyVanNeck** [comment]
we dont modify the client
