### ISSUE TITLE
Get freeze after spam click with external mouse

### ISSUE THREAD

**Issue by Fauzi345** [PojavLauncherTeam/PojavLauncher#2184]
### Describe the bug

my game freezes when spam click and move camera
but, when i spam without an external mouse or with a pojav controller my game doesn't freeze

### The log file and images/videos

More detail
https://drive.google.com/file/d/1735WcVugCOA-GgBkJRFUwA05Mtpdn4FC/view?usp=drivesdk

### Steps To Reproduce

```markdown
1.Start Pojav
2.Open Minecraft
3.Open world 
4.spam click and move camera
```

### Expected Behavior

Plsss fix or is it just my phone like this?

### Platform

```markdown
- Device model: RMX2129 4/64G
- CPU architecture: 
- Android version:11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

or is it just my phone like this?

**Comment by Mathias-Boulay** [comment]
playstore version isn't a version

**Comment by Mathias-Boulay** [comment]
State the precise launcher version

**Comment by Fauzi345** [comment]
> Nyatakan versi peluncur yang tepat

How?

**Comment by Fauzi345** [comment]
> Nyatakan versi peluncur yang tepat

this?
https://drive.google.com/file/d/17FA4Sk5vDzgVS97JNPsotcAMxBof8OGc/view?usp=drivesdk

**Comment by Fauzi345** [comment]
> versi playstore bukan versi

version : crocus-v3_openjdk

**Comment by Fauzi345** [comment]
Plssssssssss fix

**Comment by WesleyVanNeck** [comment]
> Plssssssssss fix

No

**Comment by Mathias-Boulay** [comment]
@Fauzi345 Contact me on the pojavlauncher discord for more in depth debugging of the issue

**Comment by Fauzi345** [comment]
> @Fauzi345 Contact me on the pojavlauncher discord for more in depth debugging of the issue

What you discord name

**Comment by Mathias-Boulay** [comment]
On the pojav discord, you'll find me under the name of "The Lonely Control Guy" :)
