### ISSUE TITLE
[BUG] Crash on the starting mojang screen 1.17.1

### ISSUE THREAD

**Issue by UnclearNeo** [PojavLauncherTeam/PojavLauncher#2187]
### Describe the bug

I hit start, game launches the red mojang loading screen appears and loads to maybe like 90% and then crashes without any message on the screen. On relaunch a crash report is displayed with discription: rendering overlay. 
Is there something I can do to start the game?

### The log file and images/videos

- [x]  [
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7450856/latestlog.txt)
](@[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/7450786/latest.log))

### Steps To Reproduce

```markdown
1.start pojav launcher and launch 1.17.1
```

### Expected Behavior

I hit the start for 1.17.1 and game crashes after loading to like 90% on the red mojang studios screen. No message appears on the screen. Game crashes and launcher is exited.

### Platform

```markdown
- Device model: Oppo CPH1823 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version:[Latest Release
```

**Comment by khanhduytran0** [comment]
latest.log is not latestlog.txt
also, did you press "Play Anyway" on this screen? 
![t](https://cdn.discordapp.com/attachments/724163890803638277/877232058982866944/Screenshot_2021-08-17-22-16-42-81.png)

**Comment by UnclearNeo** [comment]
I'm dumb sorry for wasting your time.

**Comment by UnclearNeo** [comment]
I was probably half dead or drunk when I tried to play and didn't read stuff correctly.

**Comment by RajveerBeast** [comment]
Pls I have the same prob help me out 😭
