### ISSUE TITLE
Crash with code 1

### ISSUE THREAD

**Issue by only-surviv-cre-cant-need-save-worlds** [PojavLauncherTeam/PojavLauncher#2188]
### Describe the bug

The game crash and a pop-up appear say :ứng dụng/trò chơi đã thoát với mã 1",  you can read the log for more information, this happen to all minecraft version i played in new pojav version, the old version dont  this bug, i tried write something in jvm like xmx but dont work

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7453295/latestlog.txt)
![Screenshot_2021-11-01-22-41-58](https://user-images.githubusercontent.com/84064984/139699220-6f4cb4b4-1eb8-4f4c-89cf-a753407e8f43.png)

### Steps To Reproduce

```markdown
What? Sorry idk what is this
```

### Expected Behavior

I can play minecraft java again, too simple?

### Platform

```markdown
- Device model: Samsung galaxy j2 prime
- CPU architecture: 4x arm cortex a-53 @ 1,44 GHz
- Android version: 6.0.1
- PojavLauncher version: lastest (19:47 1/11/2021, d1m11y2021CE, UTC+7)
API level: 23
```

**Comment by Mathias-Boulay** [comment]
First and foremost.
You don't have the latest version

Second:
You don't have enough free RAM as stated by the file
```
Error occurred during initialization of VM
Could not reserve enough space for 460800KB object heap
```

**Comment by only-surviv-cre-cant-need-save-worlds** [comment]
Thanks
