### ISSUE TITLE
Keyboard in mod installer mode please

### ISSUE THREAD

**Issue by adsewse2015** [PojavLauncherTeam/PojavLauncher#2189]
![Screenshot_2021-11-01-23-28-17-02_67a64f1fc1b88908dad3392f76c1969b.jpg](https://user-images.githubusercontent.com/57057027/139706156-07d3bdc9-17fb-4e0d-b5e2-83f50d08f0f6.jpg) i can't type the modpack id so some type of keyboard pls

**Comment by Mathias-Boulay** [comment]
Will be added in a future update
Who knows when though

**Comment by Mathias-Boulay** [comment]
#1995
