### ISSUE TITLE
[F-Req] Controller Button Remapping

### ISSUE THREAD

**Issue by delipunch** [PojavLauncherTeam/PojavLauncher#2190]
### Is this request related to a bug?

Currently controller mappings appear to be hard-coded. My controller lacks L2R2 and L3R3 buttons, so I can't break, place, or use blocks because L1R1 is hard coded to scroll wheel.

### Describe the request.

A menu of some sort to change the controller to mouse and keyboard mappings would fix this problem. Failing that, a config file to edit manually would suffice.

### Anything else?

This will also allow for people to change other things on the controller. I do prefer jump to be the right face button (as in Circle on a Playstation controller) instead of the down face button (as in Cross).

**Comment by Mathias-Boulay** [comment]
It seems you have the gamepad mapped to the same android button.
I'll close issue since we have a duplicate already

**Comment by delipunch** [comment]
> It seems you have the gamepad mapped to the same android button. 

Can you clarify what that statement means? Do you mean I have to change the bindings in the Android OS rather than PojavLauncher?

> I'll close issue since we have a duplicate already

What issue is this a duplicate of? Can you link to it? I didn't find it when I searched before making this issue.

**Comment by Mathias-Boulay** [comment]
Actually, you did well by looking for issues before posting.
Someone posted the same as yours a few hours later, which I bumped in first 😅
Maybe for controls revision 2.6 ?

**Comment by RiDDeR31** [comment]
You can remap the buttons of the controller by changing the controls on the minecraft settings and controls but changing it for pc keymaps for example for now all I know is that on ps4 controller the left arrow is "J" but I don't know more and I don't think you can map the sticks so sorry

**Comment by RiDDeR31** [comment]
I explain like shīt so if you didn't understand tell me
