### ISSUE TITLE
While dowloand lastest version of pojav on google play in file manager is not showing pojav launcher file with oder files

### ISSUE THREAD

**Issue by Vinkovci** [PojavLauncherTeam/PojavLauncher#2191]
### Describe the bug

If having old version of pojav file Will show in file manager and you can dowloand clients and mods easy but if you update the pojav files Will not upgrade

### The log file and images/videos

If having old version of pojav file Will show in file manager and you can dowloand clients and mods easy but if you update the pojav files Will not upgrade

### Steps To Reproduce

```markdown
If having old version of pojav file Will show in file manager and you can dowloand clients and mods easy but if you update the pojav files Will not upgrade
```

### Expected Behavior

If having old version of pojav file Will show in file manager and you can dowloand clients and mods easy but if you update the pojav files Will not upgradeIf having old version of pojav file Will show in file manager and you can dowloand clients and mods easy but if you update the pojav files Will not upgrade

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

If having old version of pojav file Will show in file manager and you can dowloand clients and mods easy but if you update the pojav files Will not upgrade

**Comment by khanhduytran0** [comment]
The issue template isn't filled properly.
I wonder if you have ever read this dialog at the startup.
![IMG](https://media.discordapp.net/attachments/724163890803638277/887518864836001802/Screenshot_2021-09-15-09-26-45-429_net.kdt.pojavlaunch.jpg)
