### ISSUE TITLE
Also in older versions of pojav sensitivity and mouse speed are broken does not matter how high you put i does not work

### ISSUE THREAD

**Issue by Vinkovci** [PojavLauncherTeam/PojavLauncher#2193]
### Describe the bug

.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

....

**Comment by Vinkovci** [comment]
....

**Comment by Vinkovci** [comment]
..

**Comment by khanhduytran0** [comment]
@Vinkovci bruh stop spamming, you made one at #2192 <ins>and didn't fill into the form</ins>.
comment exist, so don't make more that duplicates other one

Old launcher versions are not supported. Please go back to your first issue #2191.

**Comment by Vinkovci** [comment]
I spam it beacuse i didint want put picture i without filling all that does
not let me send bug

uto, 2. stu 2021. 01:11 Duy Tran Khanh ***@***.***> je
napisao:

**Comment by InfiniXDerg** [comment]
> ### Describe the bug
> 69
> 
> ### The log file and images/videos
> 69
> 
> ### Steps To Reproduce
> ```
> 69
> ```
> 
> ### Expected Behavior
> 69
> 
> ### Platform
> ```gfm
> - Device model: Samsung 69
> - CPU architecture: ARM69
> - Android version: 69
> - PojavLauncher version:crocusv69
> ```
> 
> ### Anything else?
> where TF is the bug
