### ISSUE TITLE
[BUG] pojav launcher 1.17 crashing 

### ISSUE THREAD

**Issue by 1493028** [PojavLauncherTeam/PojavLauncher#2194]
### Describe the bug

I have a problem when I play survival 1.17 it crashes and then there is no crash record

### Steps To Reproduce

```markdown
1 enter my survival world
2 Minutes later it crashes!!
```

### Expected Behavior

Crash itself when I play survival

### Platform

```markdown
- Device model: Vivo y50 8/128G
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version:[Latest Release || version crocus V3 jdk
```

**Comment by khanhduytran0** [comment]
Please send latestlog.txt. it's missing.

**Comment by 1493028** [comment]
> Please send latestlog.txt. it's missing.

There is no latestlog.txt!!

**Comment by khanhduytran0** [comment]
The log location is already specified at the time you fill the form
> The log file called latestlog.txt is located under Android/data/net.kdt.pojavlaunch/files, games/PojavLauncher/ or games/PojavLauncher/.minecraft. You may need to activate an option in your file explorer to see hidden files and folders.

**Comment by 1493028** [comment]
> The log location is already specified at the time you fill the form
> 
> > The log file called latestlog.txt is located under Android/data/net.kdt.pojavlaunch/files, games/PojavLauncher/ or games/PojavLauncher/.minecraft. You may need to activate an option in your file explorer to see hidden files and folders.

I know but there is no latestlog.txt

**Comment by wackycreeper** [comment]
> > The log location is already specified at the time you fill the form
> > > The log file called latestlog.txt is located under Android/data/net.kdt.pojavlaunch/files, games/PojavLauncher/ or games/PojavLauncher/.minecraft. You may need to activate an option in your file explorer to see hidden files and folders.
> 
> I know but there is no latestlog.txt

Can you send a photo of your PojavLauncher folder?

**Comment by 1493028** [comment]
> > > The log location is already specified at the time you fill the form
> > > > The log file called latestlog.txt is located under Android/data/net.kdt.pojavlaunch/files, games/PojavLauncher/ or games/PojavLauncher/.minecraft. You may need to activate an option in your file explorer to see hidden files and folders.
> > 
> > 
> > I know but there is no latestlog.txt
> 
> Can you send a photo of your PojavLauncher folder?

I can't

**Comment by netkv** [comment]
why

**Comment by ghost** [comment]
just use app that can share it

**Comment by khanhduytran0** [comment]
Still no log provided. Closing until further response.
