### ISSUE TITLE
[BUG] <Zhor battery!>

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2197]
### Describe the bug

Please make sure that the java minecraft does not consume the charge!  So that it uses the charge just like minecraft bedrock!

### Steps To Reproduce

```markdown
After launching and playing Minecraft Java, after 20 minutes of playing, 37% went away! And so it is on every version!
```

### Expected Behavior

I want minecraft java not to consume so much charge! I want him to use a charge like Minecraft Java!

### Platform

```markdown
- Device model: Redmi 6
- CPU architecture: armeabi-v7a
- Android version: 11
- PojavLauncher version: latest debug version
```

**Comment by WesleyVanNeck** [comment]
not our issue

**Comment by khanhduytran0** [comment]
@AndroMaster436 you know, you’re forcing a PC game to run on mobile. It consumes stuff since **it has never been designed for mobile**.
