### ISSUE TITLE
[BUG] No sound in Minecraft

### ISSUE THREAD

**Issue by StandPlay** [PojavLauncherTeam/PojavLauncher#2198]
### Describe the bug

when i press buttons in minecraft or break/put blocks then there is no sound.
but there are sounds in the launcher folders.
this problem occurs in all versions of minecraft.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7463629/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Launcher
2. Choice of any version
3. Launching Minecraft
```

### Expected Behavior

I was expecting the launch of minecraft
it started but without sound...

### Platform

```markdown
- Device model: SM-G925F
- CPU architecture: aarch64
- Android version: 7.0
- PojavLauncher version: v3
```

### Anything else?

Replacing sounds with a resource pack does not help
there is still no sound

**Comment by khanhduytran0** [comment]
Can you explain why did you press “Skip” while assets were downloading?

**Comment by StandPlay** [comment]
> Can you explain why did you press “Skip” while assets were downloading?

I may have accidentally pressed the skip button. I reinstalled minecraft. the sound is back but not in all versions. reinstalled all versions and deleted game files. they reinstalled. I just can't understand one thing, why is there no sound in 1.12.2?

**Comment by Mathias-Boulay** [comment]
V3 version ?
Doesn't seem right

**Comment by dxcvvxd** [comment]
super idol chan chen
