### ISSUE TITLE
[BUG] broken texture

### ISSUE THREAD

**Issue by Braydy** [PojavLauncherTeam/PojavLauncher#2199]
### Describe the bug

1.kinda looks like roblox

### The log file and images/videos

![Screenshot_20211104_120157](https://user-images.githubusercontent.com/93697405/140260897-370ccf15-ec24-42e0-bb1e-ff0e758abfeb.jpg)

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: vivo 1904
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 3.3.1.1
```

**Comment by WesleyVanNeck** [comment]
outdated launcher + dont use gl4es on older versions only 1.16.X and up
