### ISSUE TITLE
Error when installing optifine for 1.7.10 and 1.9.0

### ISSUE THREAD

**Issue by MCredbear** [PojavLauncherTeam/PojavLauncher#22]
![Screenshot_2020-03-30-11-21-30-795_net kdt pojavlaunch](https://user-images.githubusercontent.com/40625974/77879553-431ab380-728d-11ea-8f9b-6f174cff6123.jpg)
also,when I install optifine for 1.9.0,if reported:
![Screenshot_2020-03-30-11-17-46-234_net kdt pojavlaunch](https://user-images.githubusercontent.com/40625974/77879623-62b1dc00-728d-11ea-9b6b-2a142a9c4145.jpg)

**Comment by MCredbear** [comment]
Don't care about the window upside,I was having class online.

**Comment by khanhduytran0** [comment]
Did you installed latest preview?
(Can I send message or wait until you finish learn?)

**Comment by MCredbear** [comment]
> Did you installed latest preview?
> (Can I send message or wait until you finish learn?)

Yes,I did.(It's OK to send message to me,the subjects weren't difficult)

**Comment by khanhduytran0** [comment]
It's a bug that other and me got, current has no solution other than install 1.7.10 meanwhile OptiFine target other version.

**Comment by MCredbear** [comment]
> It's a bug that other and me got, current has no solution other than install 1.7.10 meanwhile OptiFine target other version.

So,I used to install another version of MCL,did that caused the error in the first picture?

**Comment by khanhduytran0** [comment]
An unmodified version?

**Comment by MCredbear** [comment]
> An unmodified version?

No....Acturually,it's a version which was made by Longjunyu,he fixed some errors of lwjgl and other errors....

**Comment by khanhduytran0** [comment]
### You can install custom version but:
- Not Minecraft 1.12 or above.
- No LWJGL 3
- Not require Forge. ~~or OptiFine~~
(OptiFine is experimental, might not worked and crash)
### To install custom version:
- Rename any unconverted libraries/versions from `[NAME].jar` to [NAME]**_orig**.jar

**Comment by MCredbear** [comment]
> ### You can install custom version but:
> 
>     * Not Minecraft 1.12 or above.
> 
>     * No LWJGL 3
> 
>     * Not require Forge or OptiFine.
> 
> 
> ### To install custom version:
> 
>     * Rename any unconverted libraries/versions from `[NAME].jar` to [NAME]**_orig**.jar

I see.....So even 1.7.10 can't install OptiFine?

**Comment by khanhduytran0** [comment]
> I see.....So even 1.7.10 can't install OptiFine?

You can install OptiFine (oops, I'm wrong at the previous)

**Comment by khanhduytran0** [comment]
Some OptiFine will error `Trucanted source file... aborting` but current has no workaround.

**Comment by khanhduytran0** [comment]
Forgot about `launcher_profiles.json`. Create a simple `/storage/sdcard0/games/minecraft/launcher_profiles.json` with content:
```
{
  "profiles": {
    "(Default)": {
      "name": "(Default)",
      "lastVersionId": "Unknown"
    }
  },
  "selectedProfile": "Default"
}
```
Then try run OptiFine again (1.7.10 more chance to success)

**Comment by MCredbear** [comment]
> Forgot about `launcher_profiles.json`. Create a simple `/storage/sdcard0/games/minecraft/launcher_profiles.json` with content:
> 
> ```
> {
>   "profiles": {
>     "(Default)": {
>       "name": "(Default)",
>       "lastVersionId": "Unknown"
>     }
>   },
>   "selectedProfile": "Default"
> }
> ```
> 
> Then try run OptiFine again (1.7.10 more chance to success)

OK,it works well.Thanks!(My phone is Redmi K20 pro)

**Comment by khanhduytran0** [comment]
If you have any bugs with same issue, reopen this.
