### ISSUE TITLE
Android 10, Java 

### ISSUE THREAD

**Issue by Victor2748-dev** [PojavLauncherTeam/PojavLauncher#220]
Java Application exited with error code 1! This may caused by a corrupted OpenJDK install, an invalid Java App, a Minecraft crash,... See Log output for more details.
 `
Error: Attempt to read from field 'java.lang.String net.kdt.pojavlaunch.value.MinecraftClientInfo.url' on a null object reference
Downloading library net.java.jinput:jinput-platform:2.0.5
Error: Attempt to read from field 'java.lang.String net.kdt.pojavlaunch.value.MinecraftClientInfo.url' on a null object reference
Downloading library tv.twitch:twitch:5.16
Downloading library tv.twitch:twitch-platform:5.16
Error: Attempt to read from field 'java.lang.String net.kdt.pojavlaunch.value.MinecraftClientInfo.url' on a null object reference
Downloading library tv.twitch:twitch-external-platform:4.5
Error: Attempt to read from field 'java.lang.String net.kdt.pojavlaunch.value.MinecraftClientInfo.url' on a null object reference
`

**Comment by khanhduytran0** [comment]
The v3 is unusable at the moment. Did you carefully read the warning?

**Comment by Victor2748-dev** [comment]
Yes i did.

**Comment by Victor2748-dev** [comment]
But i need to join 2b2t now. We got to do a raid, my laptops at my office.

I need to join asap.

**Comment by Victor2748-dev** [comment]
Oops, my hand just slipped.

**Comment by Victor2748-dev** [comment]
Can you dm me on discord?

Victor the developer#0296

**Comment by khanhduytran0** [comment]
Use the new v3 @Victor2748-dev
