### ISSUE TITLE
[F-Req] Hi-Res scroll slow.

### ISSUE THREAD

**Issue by KuroNoSeiHai** [PojavLauncherTeam/PojavLauncher#2201]
### Is this request related to a bug?

No. 

### Describe the request.

I'm using tablet, maybe it because the high resolution. Although the mouse sensitivity has been adjust to very fast, the screen scroll still very slowly. So it is difficult to change direction. Hope can fix it. 
BTW, in my phone performs well.

**Comment by Mathias-Boulay** [comment]
This will be fixed in later updates, it has yet to be pushed

**Comment by Mathias-Boulay** [comment]
The scroll behavior is now fixed with Controls Revision 2.5 #2211
