### ISSUE TITLE
This mod cannot be installed

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2202]
### Describe the bug

When installing, ask me for java11+
erection sequence:[●](https://aerialworks.ddns.net/cyan/Downloads.java.html) 

### The log file and images/videos

![Screenshot_20211104_225003_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/89151134/140338139-7ae0eea9-9393-44e9-99b2-bb3dd854d2ae.jpg)

### Steps To Reproduce

```markdown
1.Download installer
2.start-up
3.To java11+
```

### Expected Behavior

Java17 can start this program

### Platform

```markdown
- Device model: 荣耀30青春版
- CPU architecture: 天玑800
- Harmony OS version: Harmony OS 2
- PojavLauncher version: crocus-93-14dcf9993-v3_openjdk
```

### Anything else?

If you don't want to do it, close it!
Using machine translation。

**Comment by artdeell** [comment]
What's KickStart?

**Comment by aaaapai** [comment]
> 什么是启动？

机器翻译不准确

**Comment by aaaapai** [comment]
> What's KickStart?

I don't understand. Why don't you go to the official website of the program I downloaded? The website I gave is this official website
Click the blue symbol: "●" to go

**Comment by aaaapai** [comment]
> 什么是启动？

2021.11.5 12:41:48，I can't open this website right now

**Comment by NotAHero04** [comment]
@artdeell it seems to be a mod loader installer <:ULTIMATEROFEL:905334444355883028>

**Comment by artdeell** [comment]
@aaaapai while Pojav doesn't support mod installers for Java 9+, you can use the Java 17 JRE provided [here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/1352687193) together with Termux X11 libraries to unpack the modloader and later copy into Pojav

**Comment by Mathias-Boulay** [comment]
#1948
