### ISSUE TITLE
[F-Req] Microsoft offline login

### ISSUE THREAD

**Issue by Muvkina** [PojavLauncherTeam/PojavLauncher#2203]
### Is this request related to a bug?

I would like to be able to play mc in situations without a network connection however due to microsoft account migration it seems to no longer work?

### Describe the request.

Someway to be able to play offline if youve migrated.

**Comment by ajit850** [comment]
> I would like to be able to play mc in situations without a network connection however due to microsoft account migration it seems to no longer work?
How you play Minecraft multiplayer without internet connection

**Comment by Mathias-Boulay** [comment]
This is being worked on
Because I suffer from the same issue

**Comment by SprainedSpark89** [comment]
why not make a offline account you will still have the same worlds

**Comment by Mathias-Boulay** [comment]
added in a future PR soon, can be closed
