### ISSUE TITLE
[F-Req] x86_64 environment

### ISSUE THREAD

**Issue by gyojalal** [PojavLauncherTeam/PojavLauncher#2205]
### Is this request related to a bug?

yes mcef 1.31 is x86_64. 1.31 verion is linux x64 suppot version. arm64 is not working

### Describe the request.

please x86_64 is possible box64 thought.

### Anything else?
box64 link:https://github.com/ptitSeb/box64
mcef 1.31 link:https://github.com/Ruinscraft/mcef

**Comment by khanhduytran0** [comment]
Since chromium is open source, it could just be recompiled for arm64. Also, Android doesn't provide a full Linux environment, so it wouldn't work without the whole Linux libraries. Putting box64 into PojavLauncher is also not our plan.
