### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by cello540** [PojavLauncherTeam/PojavLauncher#2206]
### Describe the bug

crash 1.8.9 very annoying please fix this bug, and if you play using Lunar Client 1.8.9

### The log file and images/videos

crash 1.8.9 very annoying please fix this bug, and if you play using Lunar Client 1.8.9

### Steps To Reproduce

```markdown
crash
```

### Expected Behavior

vgpu

### Platform

```markdown
- Device model:Asus ROG Phone 3 12/256
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
We aren't officially supporting third party client
