### ISSUE TITLE
[F-Req] <please add opengl 3.2 or higher>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2207]
### Is this request related to a bug?

No

### Describe the request.

please add opengl 3.2 or higher cause Zink is too laggy and also it will allow mods to run in 1.17 and it probably can be the permanent fix. Although it's totally upto the team and I don't know any kind of coding, so I will not be angry if you cant add it cause I know how hard it can be.
Still I like your incredible works. I wish that I could have bought your patreon

### Anything else?

No

**Comment by Mathias-Boulay** [comment]
Actually, we don't develop zink.
Renderer aren't developed by us and we don't have the knowledge to fix their issues

**Comment by ghost** [comment]
> Actually, we don't develop zink. Renderer aren't developed by us and we don't have the knowledge to fix their issues

Actually I asked to add gl 3.2 not to decrease lag of Zink

**Comment by khanhduytran0** [comment]
> Actually I asked to add gl 3.2 not to decrease lag of Zink

Actually, we aren’t Nvidia RTX developers neither.

**Comment by InfiniXDerg** [comment]
> > Actually I asked to add gl 3.2 not to decrease lag of Zink
> 
> Actually, we aren’t Nvidia RTX developers neither.

Hmmm, add a hidden ZINK called GeForce RTX 2060 TEST

**Comment by ghost** [comment]
> > Actually I asked to add gl 3.2 not to decrease lag of Zink
> 
> Actually, we aren’t Nvidia RTX developers neither.
 
There is code for opengl 3.2 (android) available in the internet so you can use that (think so) and wtf we talk like this😂like-actually,then start our thing🤣

**Comment by WesleyVanNeck** [comment]
> > > Actually I asked to add gl 3.2 not to decrease lag of Zink
> > 
> > 
> > Actually, we aren’t Nvidia RTX developers neither.
> 
> There is code for opengl 3.2 (android) available in the internet so you can use that (think so) and wtf we talk like this😂like-actually,then start our thing🤣

OpenGL es is not opengl

**Comment by InfiniXDerg** [comment]
> > > Actually I asked to add gl 3.2 not to decrease lag of Zink
> > 
> > 
> > Actually, we aren’t Nvidia RTX developers neither.
> 
> There is code for opengl 3.2 (android) available in the internet so you can use that (think so) and wtf we talk like this😂like-actually,then start our thing🤣

Share It and we Will do that (well, im not a dev :trollface: )

**Comment by ghost** [comment]
> > > > Actually I asked to add gl 3.2 not to decrease lag of Zink
> > > 
> > > 
> > > Actually, we aren’t Nvidia RTX developers neither.
> > 
> > 
> > There is code for opengl 3.2 (android) available in the internet so you can use that (think so) and wtf we talk like this😂like-actually,then start our thing🤣
> 
> Share It and we Will do that (well, im not a dev :trollface: )

https://www.khronos.org/opengles/   the link think it helps the Devs 😀

**Comment by khanhduytran0** [comment]
bruh, OpenGL ≠ OpenGL ES
However, Minecraft 1.17.x use most of OpenGL ES 3 calls :trollface:

**Comment by ghost** [comment]
> bruh, OpenGL ≠ OpenGL ES However, Minecraft 1.17.x use most of OpenGL ES 3 calls :trollface:

Thanks for the info but the link is of opengl es
