### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by GSSB3322** [PojavLauncherTeam/PojavLauncher#2208]
### Describe the bug

Yo tengo un error que es de la aplicación a finalizado con el código 1 estaría chido que solucionaran también eso pero con eso podríamos mejorar mejor

### The log file and images/videos

Arreglen esooooooooooo

### Steps To Reproduce

```markdown
Checar los archivos y el open gl y el java  8 y el java 17
```

### Expected Behavior

Espero que el juego se inicie de forma correctamente y no me marca ningún error

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Espero no se demoren mucho en eso por favor

**Comment by InfiniXDerg** [comment]
Me puede decir lo siguiente?
Modelo del dispositivo:
arquitectura del procesador:
Versión de Android
Versión de la App:

**Comment by Mathias-Boulay** [comment]
no information given despite demands, closing the issue
