### ISSUE TITLE
[F-Req] Controller Remapping

### ISSUE THREAD

**Issue by letsgoawaydev** [PojavLauncherTeam/PojavLauncher#2209]
### Is this request related to a bug?

Its related to a bug because the playstation 5 controls are all messed up

### Describe the request.

A controller keybind changer or remapper

### Anything else?

This is for older devices that dont have new android and can remap the ps5 buttons to not be messed up

**Comment by Mathias-Boulay** [comment]
True, this would be a worthy addition

**Comment by Mathias-Boulay** [comment]
*Better late than never I guess*
Hey there @letsgoawaydev , there is an experimental build on the actions page that allows you to remap the controls. Try it out !

**Comment by letsgoawaydev** [comment]
cool! ill try it out
