### ISSUE TITLE
Left and Right Click

### ISSUE THREAD

**Issue by GabubuAvailable** [PojavLauncherTeam/PojavLauncher#2210]
Please add Left and Right Click buttons. It would be much easier for peoples like me.

**Comment by NotAHero04** [comment]
If you didn’t know, the PRI button acts like a left mouse click, and the SEC button acts like a right mouse click.

**Comment by WesleyVanNeck** [comment]
Invalid

**Comment by InfiniXDerg** [comment]
> Please add Left and Right Click buttons. It would be much easier for peoples like me.

Bruh, Use buttons PRI & SEC
Youre now a meme on the Pojavlauncher discord

**Comment by GabubuAvailable** [comment]
WAIT WUT?

**Comment by GabubuAvailable** [comment]
I thought you deleted those buttons :(
