### ISSUE TITLE
[BUG] Crash with code 1

### ISSUE THREAD

**Issue by ereker1** [PojavLauncherTeam/PojavLauncher#2212]
### Describe the bug

Application exited with code 1

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.16.5
--------- beginning of main
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=480
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/bin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-1/lib/arm
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=270
I/LIBGL   ( 1269): Initialising gl4es
I/LIBGL   ( 1269): v1.1.4 built on Jul 19 2020 08:24:33
I/LIBGL   ( 1269): Using GLES 2.0 backend
I/LIBGL   ( 1269): loaded: libGLESv2.so
I/LIBGL   ( 1269): loaded: libEGL.so
I/LIBGL   ( 1269): Using GLES 2.0 backend
I/LIBGL   ( 1269): Hardware Full NPOT detected and used
I/LIBGL   ( 1269): FBO are in core, and so used
I/LIBGL   ( 1269): PointSprite are in core, and so used
I/LIBGL   ( 1269): CubeMap are in core, and so used
I/LIBGL   ( 1269): BlendColor is in core, and so used
I/LIBGL   ( 1269): Blend Substract is in core, and so used
I/LIBGL   ( 1269): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 1269): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 1269): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 1269): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 1269): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 1269): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 1269): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 1269): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 1269): Extension GL_OES_texture_float  detected and used
I/LIBGL   ( 1269): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   ( 1269): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 1269): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 1269): Extension GL_OES_fragment_precision_high  detected and used
I/LIBGL   ( 1269): Max vertex attrib: 16
I/LIBGL   ( 1269): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 1269): Max texture size: 4096
I/LIBGL   ( 1269): Max Varying Vector: 16
I/LIBGL   ( 1269): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   ( 1269): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 1269): Max Anisotropic filtering: 16
I/LIBGL   ( 1269): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   ( 1269): Hardware vendor is Qualcomm
I/LIBGL   ( 1269): GLSL 300 es supported and used
I/LIBGL   ( 1269): EGLImage to Texture2D supported
I/LIBGL   ( 1269): EGLImage to RenderBuffer supported
I/LIBGL   ( 1269): ignore MipMap
I/LIBGL   ( 1269): Targeting OpenGL 2.1
I/LIBGL   ( 1269): NPOT texture handled in hardware
I/LIBGL   ( 1269): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 1269): try to use VBO
I/LIBGL   ( 1269): glX Will try to recycle EGL Surface
I/LIBGL   ( 1269): Current folder is:/
I/jrelog  ( 1269): dlopen libgl4es_114.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  ( 1269): dlopen libjvm.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
referenceTable GDEF length=808 1
referenceTable GSUB length=11364 1
referenceTable GPOS length=47320 1
referenceTable head length=54 1
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsound.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjpeg.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsdt.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pcsc.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmanagement.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libunpack.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjaas_unix.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libhprof.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_xawt.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsig.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2gss.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsunec.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnpt.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libtinyiconv.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pkcs11.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libdt_socket.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjdwp.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libzip.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsctp.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmlib_image.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/liblcms.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjawt.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  ( 1269): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  ( 1269): dlopen /data/app/net.kdt.pojavlaunch-1/lib/arm/libopenal.so success
I/jrelog  ( 1269): Done processing args
I/jrelog  ( 1269): Found JLI lib
I/jrelog  ( 1269): Calling JLI_Launch
OpenJDK Client VM warning: 
Can't detect primordial thread stack location - find_vma failed

Error occurred during initialization of VM
Could not reserve enough space for 792576KB object heap

### Steps To Reproduce

```markdown
1 - start pojav launcher
2 - select 1.16.5
3 - click play
```

### Expected Behavior

I expected game to launch

### Platform

```markdown
- Device model: xiaomi mi 4
- CPU architecture: arm (i guess)
- Android version: 6.0.1
- PojavLauncher version: Latest play store release
```

**Comment by ajit850** [comment]
State the version of launcher

**Comment by WesleyVanNeck** [comment]
you allocated to much ram for your device
