### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by hehe233hehe** [PojavLauncherTeam/PojavLauncher#2213]
### Describe the bug

There is no version after downloading. Forge cannot be used.

### Steps To Reproduce

```markdown
1.启动
2。登录
3.打开版本
4.显示错误和无版本
```

### Expected Behavior

我希望能改进

### Platform

```markdown
- Device model: 华为navo 6/64
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: 3.3.1.1
```

**Comment by Mathias-Boulay** [comment]
Pojav launcher version too old, unsupported
