### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by KioEdits** [PojavLauncherTeam/PojavLauncher#2214]
### Describe the bug

Response error code: 403 
message: {"error":"ForbiddenOperationExecption"}

### Steps To Reproduce

```markdown
I can't add accounts anymore except for an offline/cracked account. Even if i reinstall it it still won't work. I'll rate the app 5 stars IF this stupid/annoying bug is fixed. Please someone help me😭
```

### Expected Behavior

I expect this to be fixed PLEASE

### Platform

```markdown
- Device model:Oppo A3s 
- CPU architecture:aarch64 
- Android version:8.1 
- PojavLauncher version: Latest version from playstore
```

### Anything else?

PLEASE FIX THIS BUG QUICK BEFORE I GET ANNOYED.

**Comment by InfiniXDerg** [comment]
If you migrated to Microsoft use Microsoft Button

**Comment by KioEdits** [comment]
I'll try give me a sec

**Comment by KioEdits** [comment]
I need a real premium acc bro,but im poor. My dad just died last week from 2nd stage cancer. 😭

**Comment by KioEdits** [comment]
Can someone gift me a Minecraft account? Please? I really need it for my career. I want to be a YouTuber since I was a kid. PLEASE SOMEONE 😭😭

**Comment by InfiniXDerg** [comment]
> Can someone gift me a Minecraft account? Please? I really need it for my career. I want to be a YouTuber since I was a kid. PLEASE SOMEONE 😭😭

We cant give you a premium account so.the unic form for get a genuine one is, working

**Comment by khanhduytran0** [comment]
> this stupid/annoying bug is fixed

This is your problem, not our problem. Don’t expect to get a premium account for free.
~~also how old are you?~~

**Comment by khanhduytran0** [comment]
Also, if you have a powerful enough device for PojavLauncher, why not the game? :trollface:
