### ISSUE TITLE
[BUG] <VirGL>

### ISSUE THREAD

**Issue by InfiniXDerg** [PojavLauncherTeam/PojavLauncher#2218]
### Describe the bug

seems like crashes on any version but not 1.7.10

### The log file and images/videos

IDK what to put so

### Steps To Reproduce

```markdown
1. Start launcher
2. set VirGL
3. Launch 1.16.5
4. crashes
5. Launch 1.7.10
6. open as nothing happened
```

### Expected Behavior

game launches on 1.7.10 with VirGL but not on others versions

### Platform

```markdown
- Device model: NX659J 
- CPU architecture: Arm64
- Android version: 11 root
- PojavLauncher version: crocus-126-48cf6ca69-v3-virgl (Duy, you put 69 at final?)
```

### Anything else?

again, IDK what to put

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you

**Comment by CriticalRange** [comment]
> ### Describe the bug
> seems like crashes on any version but not 1.7.10
> 
> ### The log file and images/videos
> IDK what to put so
> 
> ### Steps To Reproduce
> ```gfm
> 1. Start launcher
> 2. set VirGL
> 3. Launch 1.16.5
> 4. crashes
> 5. Launch 1.7.10
> 6. open as nothing happened
> ```
> 
> ### Expected Behavior
> game launches on 1.7.10 with VirGL but not on others versions
> 
> ### Platform
> ```gfm
> - Device model: NX659J 
> - CPU architecture: Arm64
> - Android version: 11 root
> - PojavLauncher version: crocus-126-48cf6ca69-v3-virgl (Duy, you put 69 at final?)
> ```
> 
> ### Anything else?
> again, IDK what to put
> 
> Never gonna give you up Never gonna let you down Never gonna run around and desert you

Imagine not using #community-development unpog

**Comment by InfiniXDerg** [comment]
> > ### Describe the bug
> > seems like crashes on any version but not 1.7.10
> > ### The log file and images/videos
> > IDK what to put so
> > ### Steps To Reproduce
> > ```
> > 1. Start launcher
> > 2. set VirGL
> > 3. Launch 1.16.5
> > 4. crashes
> > 5. Launch 1.7.10
> > 6. open as nothing happened
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > game launches on 1.7.10 with VirGL but not on others versions
> > ### Platform
> > ```
> > - Device model: NX659J 
> > - CPU architecture: Arm64
> > - Android version: 11 root
> > - PojavLauncher version: crocus-126-48cf6ca69-v3-virgl (Duy, you put 69 at final?)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > again, IDK what to put
> > Never gonna give you up Never gonna let you down Never gonna run around and desert you
> 
> Imagine not using #community-development unpog

Ask to nguyen to unmute me
