### ISSUE TITLE
[BUG] <latest dev build seems to be buggy>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2219]
### Describe the bug

1st bug - you cant start any version of Minecraft with virgl. [The log is here ](https://drive.google.com/file/d/1ArYtPIugjAO9yL8tt-nf3rEbFz0IpWzi/view?usp=drivesdk) it is modded fabric 1.16.5

2nd bug- seems like you broke the mod installer(log is pasted beneath cause I don't have the text for it).
It says this error for every mod.

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.utils.JREUtils.setJavaEnvironment(JREUtils.java:213)
	at net.kdt.pojavlaunch.utils.JREUtils.launchJavaVM(JREUtils.java:284)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.launchJavaRuntime(JavaGUILauncherActivity.java:346)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.doCustomInstall(JavaGUILauncherActivity.java:311)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.access$700(JavaGUILauncherActivity.java:20)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity$6.run(JavaGUILauncherActivity.java:214)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
1. Open mod installer in the latest dev build
2. Says error

3.select virgl
4. Click start with any mc version
5. Crashes after some time
```

### Expected Behavior

1.Allow me to launch mod installer

2.start Minecraft normally with virgl

### Platform

```markdown
- Device model: Vivo y12
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: version crocus-126-48cf6ca69-v3-virgl
```

### Anything else?

Nope

**Comment by Mathias-Boulay** [comment]
Reports for a non supported branch.
Closing.

**Comment by ghost** [comment]
> Reports for a non supported branch. Closing.

Ok but where do i report those bugs cause they are meant to be fixed

**Comment by khanhduytran0** [comment]
> Ok but where do i report those bugs cause they are meant to be fixed

They’re not bugs, they’re expected behaviors from an **experimental branch**.

**Comment by khanhduytran0** [comment]
You can’t expect everything to work and can be fixed by just reporting it to us.

**Comment by ghost** [comment]
> You can’t expected everything to work and can be fixed by just reporting it.

Ok thanks for the info 👍
