### ISSUE TITLE
[BUG] <Short description>java.lang.RuntimeException: LWJGL3 tidak terpasang! 	at net.kdt.pojavlaunch.BaseMainActivity.checkLWJGL3Installed(BaseMainActivity.java:745) 	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:722) 	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36) 	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552) 	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(lambda) 	at java.lang.Thread.run(Thread.java:761)

### ISSUE THREAD

**Issue by Kuaciii** [PojavLauncherTeam/PojavLauncher#2222]
### Describe the bug

Leaps Dia tulis Lwjgl3 ralat

### The log file and images/videos

![Screenshot_2021-11-10-10-34-05-96](https://user-images.githubusercontent.com/94028225/141039157-1d8b9fbe-9028-4351-a6df-572a0bee3d47.png)

### Steps To Reproduce

```markdown
Need repair
```

### Expected Behavior

Please repair fastest

### Platform

```markdown
- Device model:Redmi 6A
- CPU architecture:Helio
- Android version:9
- PojavLauncher version:new
```

### Anything else?

Tidak Ada apa aa

**Comment by WesleyVanNeck** [comment]
Use English

**Comment by Kuaciii** [comment]
Pada Rab, 10 Nov 2021, 13:00 LegacyGamerHD ***@***.***>
menulis:

**Comment by grekzorna** [comment]
Im having the same problem, but i don't see any answers, what do i need to do and where do i install the thing i need
