### ISSUE TITLE
[BUG] virglenderer does not start 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2225]
### Describe the bug

Minecraft 1.17/1.16.5/1.16.5 optifine/1.16.5 forge does not run on virglenderer. There are no errors just doesn't show up the mojang splash screen and the game doesn't start. 

### The log file and images/videos

![Screenshot_20211110_200244_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/141158806-dbfdb3bb-2809-4f97-b390-5fefa1d0b8b3.jpg)

### Steps To Reproduce

```markdown
1.Launched Pojavlauncher version crocus-151-c3e23548e-v3-virgl
2.Selected render on virglenderer 
3. Tried to run versions on it: 1.16.5/1.16.5 optifine/1.16.5 forge/1.17 (also tried to run on java 17) 
4. Black screen (as in the screenshot)
5. Then the black screen nothing happens waiting 30 minutes until the game starts nothing came out
```

### Expected Behavior

I expected the game to start 

### Platform

```markdown
- Device model: honor 9c AKA-L29 4/64
- CPU architecture:aarch 64
- Android version: 10
- PojavLauncher version: crocus-151-c3e23548e-v3-virgl
```

### Anything else?

No

**Comment by ghost** [comment]
who told you virgl is released?

**Comment by WesleyVanNeck** [comment]
Known also no support for that branch

**Comment by Iarkont** [comment]
> Known also no support for that branch

So why did you add it? And on the latest beta version of Pojavlauncher virglenderer launches minecraft but no image just black screen

**Comment by WesleyVanNeck** [comment]
> > Known also no support for that branch
> 
> So why did you add it? And on the latest beta version of Pojavlauncher virglenderer launches minecraft but no image just black screen

well not my problem you that pick blind a action build

**Comment by ghost** [comment]
bruh really?

**Comment by artdeell** [comment]
> > Known also no support for that branch
> 
> So why did you add it? And on the latest beta version of Pojavlauncher virglenderer launches minecraft but no image just black screen

@Iarkont Well, we are obligated to publish the sources since Pojav is open-source, but if we publish them, it does not mean that they are usable.
