### ISSUE TITLE
Cant play debug

### ISSUE THREAD

**Issue by noobimpostor** [PojavLauncherTeam/PojavLauncher#2226]
### Describe the bug

Btw i can't launch debug version latest auto build,  but Play store version working

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I expect game to launches

### Platform

```markdown
- Device model: mi note 8
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest
```

**Comment by LegacyGamerHD** [comment]
Latest isn't a version

**Comment by khanhduytran0** [comment]
> i can't launch debug version latest auto build

Expected behavior. Probably you reached the virgl build which is WIP.
