### ISSUE TITLE
[F-Req] Can you make the creepypasta Minecraft version like the alpha 1.2.7 installation pls

### ISSUE THREAD

**Issue by Ella594YT** [PojavLauncherTeam/PojavLauncher#2227]
### Is this request related to a bug?

I've been looking online that some versions of Minecraft has weird things on it i was wondering to try it out if its real but unfortunately i can't install the version, Pls can you add the feature?

**Comment by Mathias-Boulay** [comment]
Meh, no.
I you can install it on PC, should be easy enough to transfer the jar files for you

**Comment by Ella594YT** [comment]
I don't have pc tho :/
