### ISSUE TITLE
1.8.9 & LC(LunarClient) crash

### ISSUE THREAD

**Issue by 8SamPSH9** [PojavLauncherTeam/PojavLauncher#2229]
### Describe the bug

It's go into menu , when i go to my world it's crash , i enabled VBO it doen't work for me☹
I can't play on hypixel 1.8.9

### Steps To Reproduce

```markdown
1.open 1.8.9 or Lunar Client 
2.go to world , GAME EXITED
```

### Expected Behavior

Plssssssss fix it , it's my dreeeaam

### Platform

```markdown
- Device model: Samsung galaxy A71
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

Don't say use VBO i use it , doesn't work😑☹☹

**Comment by Mathias-Boulay** [comment]
Pojav version not stated.
If latest was a version, it wouldn't be yours.

**Comment by Mathias-Boulay** [comment]
Also, *unsupported client* moment

**Comment by notstackgb** [comment]
well when i choose to play LC 1.8.9, my pojav just show Minecraft 1.0 in my screen.. not lunar client..
