### ISSUE TITLE
Java Application exited

### ISSUE THREAD

**Issue by SpaghettoSensei** [PojavLauncherTeam/PojavLauncher#223]
**Java Application exited with error code 1! This may caused by a corrupted OpenJDK install, an invalid Java App, a Minecraft crash,... See Log output for more details..**
Well. I have a Samsung A50 with Android 10. I try to use version 1.15. But without success. Should I use the extra download file called "PojavLauncher-3.0.1-preview5"? In that case. Where could I place it?

**Comment by khanhduytran0** [comment]
Duplicate, read #220

**Comment by khanhduytran0** [comment]
> The v3 is unusable at the moment. Did you carefully read the warning?

**Comment by SpaghettoSensei** [comment]
Oh. I just wanted to check and have that little hope of being able to use it. About the previous article, I know little about English. Thanks for the reply.

**Comment by khanhduytran0** [comment]
I will close due to duplicate.
