### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Bones369** [PojavLauncherTeam/PojavLauncher#2231]
### Describe the bug

When you right click on the door it won't open. I have touch screen off. This is in the ingame settings. Using a Samsung galaxy s9, Logitech m100 mouse. 

### Steps To Reproduce

```markdown
Right click on a door with the previous description.
```

### Expected Behavior

It should open properly

### Platform

```markdown
- Device model:Samsung Galaxy S9               
- CPU architecture: Octa-Core, 2 processors: 2.7GHz Quad-Core Mongoose M3 1.8GHz Quad-Core ARM Cortex-A55
- Android version: Android 10
- PojavLauncher version:crocus-103-21f6b166a-v3_openjdk
```

**Comment by andteklin** [comment]
I can attest to this issue. To reproduce this issue, open up Minecraft 1.16.1 using the Update README.md Android CI #3316 version of the app debug. Using OptiFine HD U G9 as well. Go to in-game Minecraft settings, options --> controls --> mouse settings --> Touchscreen mode should say OFF. Place a door down and the door will immediately open then close, rendering opening doors broken.

**Comment by ErrorBot1122** [comment]
@smartmonkey3042 Why don't you just **Edit** the bug report, *ALSO* Add a title, please... (Not trying to be rude here ;) )
