### ISSUE TITLE
resolution changes 

### ISSUE THREAD

**Issue by S0rk-jpg** [PojavLauncherTeam/PojavLauncher#2232]
### Is this request related to a bug?

Why can't we change the resolution within Minecraft in the settings Is there any reason to stop this?

### Describe the request.

Wish we could change the resolution within Minecraft

**Comment by ghost** [comment]
you can change the resolution in the setting in pojav bruh

**Comment by S0rk-jpg** [comment]
>I know but not this kind of change I prefer 1280x780 and 1440x1080,

**Comment by ghost** [comment]
you just can only change the quality not the resolution and your phone is not a computer

**Comment by S0rk-jpg** [comment]
> você só pode alterar a qualidade, não a resolução, e seu telefone não é um computador

I don't know if I can talk about other launchers around here but there is a launcher that is working

**Comment by S0rk-jpg** [comment]
> você só pode alterar a qualidade, não a resolução, e seu telefone não é um computador

https://youtu.be/Mt48bTYkxAE

**Comment by ghost** [comment]
that one is for android 9 and lower i think

**Comment by ghost** [comment]
and pojav have a gif mcinatrash

**Comment by S0rk-jpg** [comment]
> aquele é para android 9 e inferior, eu acho
So the resolution change is only for Android 9? 🙁 Or below?

**Comment by ghost** [comment]
no

**Comment by S0rk-jpg** [comment]
> e pojav tem um gif mcinatrash

I prefer pojav but what was missing was the resolution change but I don't think it's possible...🙁

**Comment by ghost** [comment]
welp your phone i so small and dev can't help you this(sorry for replying too long)

**Comment by WesleyVanNeck** [comment]
Wrong template here with no info
