### ISSUE TITLE
[BUG] Cannot open

### ISSUE THREAD

**Issue by Silverhoft** [PojavLauncherTeam/PojavLauncher#2233]
### Describe the bug

Every time I play, it closes right after it opens.

### Steps To Reproduce

```markdown
1. Start Pojav
2. Choose user
3. Choose 1.17.1
4. Press play
5. Game closes right after opening
```

### Expected Behavior

I expect the game to open

### Platform

```markdown
- Device model: kindle fire v7 gen7
- CPU architecture: arm32
- Android version: I don't know how to see this
- PojavLauncher version: 3
```

### Anything else
Please help me

**Comment by ghost** [comment]
hmm

**Comment by ghost** [comment]
so this is like a crash or something

**Comment by ghost** [comment]
welp you should watch the tutorial and make sure you do right

**Comment by Silverhoft** [comment]
I watched it, I made sure to use the right runtime and me allowance.

**Comment by ghost** [comment]
did you use the right render?

**Comment by ghost** [comment]
and are you in the Pojavlauncher discord we can talk in there and i can help

**Comment by Silverhoft** [comment]
That was not in the tutorial that I watched

**Comment by ghost** [comment]
oh

**Comment by Silverhoft** [comment]
I not in discor, but I can join it

**Comment by Silverhoft** [comment]
Discord*

**Comment by ghost** [comment]
so join it so i can help you

**Comment by Silverhoft** [comment]
K what is the server link?

**Comment by ghost** [comment]
https://discord.com/invite/6RpEJda
here i guess

**Comment by Silverhoft** [comment]
Ty

**Comment by ghost** [comment]
join and find pojav-android i will wait in there to help you

**Comment by WesleyVanNeck** [comment]
1.17 can't be runned on arm yet

**Comment by Silverhoft** [comment]
I need to do you, I do not have phone, so I can't verify number on discord

**Comment by Silverhoft** [comment]
Dm  not do, auto correct

**Comment by Silverhoft** [comment]
Oh, can I use 1.16.5?

**Comment by ghost** [comment]
yes

**Comment by Silverhoft** [comment]
Ok, thank u so much

**Comment by ghost** [comment]
ok

**Comment by Silverhoft** [comment]
U all are so amazing, I can't believe you made this thing!

**Comment by ghost** [comment]
im not the devlopment im just helping people

**Comment by Silverhoft** [comment]
I am talking about the program in general

**Comment by ghost** [comment]
oh ok then

**Comment by Silverhoft** [comment]
Alright well I am going to try 1.@6.5 to see what happens

**Comment by ghost** [comment]
welp you just need to change your runtime to java 8

**Comment by ghost** [comment]
i got crash when playing 1.16.5 with java 17 tho

**Comment by Silverhoft** [comment]
How can I run that on my device?

**Comment by Silverhoft** [comment]
Me too

**Comment by ghost** [comment]
what do you mean?

**Comment by Silverhoft** [comment]
It tells me that the architecture is incompatible with arm 32

**Comment by ghost** [comment]
i think if you want to play 1.16.5 just download the Pojavlauncher from playstore and when open just choose render 1.1.5

**Comment by ghost** [comment]
and idk what is incompatible with arm 32 tho

**Comment by Silverhoft** [comment]
I can't download from appstore, I have amozon

**Comment by ghost** [comment]
:/

**Comment by ghost** [comment]
welp it's not my problem so yea

**Comment by Silverhoft** [comment]
I will try the fender thing though

**Comment by ghost** [comment]
ok

**Comment by Silverhoft** [comment]
Render

**Comment by ghost** [comment]
welp i recommend render 1.1.5(opengles 3)
