### ISSUE TITLE
Why my 1.8.9 CRASH

### ISSUE THREAD

**Issue by 8SamPSH9** [PojavLauncherTeam/PojavLauncher#2234]
### Describe the bug

I go to my world in 1.8.9 version , CRASH (game exited)
Don't say enable VBO , it doesn't work. 

### Steps To Reproduce

```markdown
1. go to pojav
2. select 1.8.9
3. go to world or server
4. crash (game exited)
```

### Expected Behavior

i want to play 1.8.9 , pls fix it

### Platform

```markdown
- Device model: samsung galaxy A71
- CPU architecture: aarch 64
- Android version: 11
- PojavLauncher version: Latest , you guys made
```

### Anything else?

Pls fix it , don't say enable VBO it doesn't work for me . 
Pls don't close this so fast.

**Comment by khanhduytran0** [comment]
"Latest , you guys made" is not a valid version. Seriously, latest may point to either Latest Play Store Release or Latest GitHub Actions Build. Please specify the version name and latestlog.txt.

**Comment by 8SamPSH9** [comment]
> "Latest , you guys made" is not a valid version. Seriously, latest may point to either Latest Play Store Release or Latest GitHub Actions Build. Please specify the version name and latestlog.txt.

3.3.1.1 version

**Comment by WesleyVanNeck** [comment]
Outdated

**Comment by 8SamPSH9** [comment]
Pls fiiiiix😭😭

**Comment by khanhduytran0** [comment]
> 3.3.1.1 version

 incomplete. accepted format: `<version>_<build date>` or `<build codename>-<branch name>`, or just send latestlog.txt

**Comment by NotAHero04** [comment]
Based on what I see in #2229, you are using Lunar Client. It includes OptiFine, but in many cases it’s pretty unstable. My advice is to use a client without OptiFine.

**Comment by GoneSubject** [comment]
oh same person
