### ISSUE TITLE
严重bug，什么都启动不了

### ISSUE THREAD

**Issue by hyplant** [PojavLauncherTeam/PojavLauncher#2235]
现在最新的action版本什么都打不开，点击启动游戏后，短时间内启动器就会崩溃。

**Comment by aaaapai** [comment]
我们俩也用pojavLauncher，实在不行就降一个版本，还有，标签错了

**Comment by aaaapai** [comment]
建议选择openjdk版本

**Comment by aaaapai** [comment]
我要下线了，可以在苦力怕论坛跟我聊

**Comment by ENDERMANYK** [comment]
actions里是啥测试版都有，你要正常使用下载带v3_openjdk的

**Comment by aaaapai** [comment]
> actions里是啥测试版都有，你要正常使用下载带v3_openjdk的

我下载了openjdk，却没想到我进入游戏滑动一下屏幕就给我崩了

**Comment by aaaapai** [comment]
> actions里是啥测试版都有，你要正常使用下载带v3_openjdk的

你英语好吗？不好的话，我就去用翻译器翻译了哦

**Comment by aaaapai** [comment]
> actions里是啥测试版都有，你要正常使用下载带v3_openjdk的

要不我先替你们试一下别的openjdk版本？

**Comment by ENDERMANYK** [comment]
> > actions里是啥测试版都有，你要正常使用下载带v3_openjdk的
> 
> 要不我先替你们试一下别的openjdk版本？

那些已知都有问题，没必要试

**Comment by aaaapai** [comment]
> > > actions里是啥测试版都有，你要正常使用下载带v3_openjdk的
> > 
> > 
> > 要不我先替你们试一下别的openjdk版本？
> 
> 那些已知都有问题，没必要试

那好吧

**Comment by ENDERMANYK** [comment]
> > actions里是啥测试版都有，你要正常使用下载带v3_openjdk的
> 
> 你英语好吗？不好的话，我就去用翻译器翻译了哦

你觉得我英语好还是不好

**Comment by aaaapai** [comment]
> > > actions里是啥测试版都有，你要正常使用下载带v3_openjdk的
> > 
> > 
> > 你英语好吗？不好的话，我就去用翻译器翻译了哦
> 
> 你觉得我英语好还是不好

这个我就不知道了

**Comment by aaaapai** [comment]
> > > actions里是啥测试版都有，你要正常使用下载带v3_openjdk的
> > 
> > 
> > 你英语好吗？不好的话，我就去用翻译器翻译了哦
> 
> 你觉得我英语好还是不好

我觉得好吧

**Comment by ENDERMANYK** [comment]
~~你接受消息这么快吗~~

**Comment by aaaapai** [comment]
> > > actions里是啥测试版都有，你要正常使用下载带v3_openjdk的
> > 
> > 
> > 你英语好吗？不好的话，我就去用翻译器翻译了哦
> 
> 你觉得我英语好还是不好

换了一次版本，终于正常运行了
第一个版本是

> ~你接受消息这么快吗~

我家网络好，不需要挂VPN

**Comment by aaaapai** [comment]
> ~你接受消息这么快吗~

还有，因为我换版本成功了，回来看一下

**Comment by aaaapai** [comment]
> ~你接受消息这么快吗~

换了一次版本

**Comment by ENDERMANYK** [comment]
~~我是天天在github上嫖代码~~

**Comment by aaaapai** [comment]
> ~你接受消息这么快吗~

一个是最新版的openjdk，第二个是第二个的openjdk版本

**Comment by ENDERMANYK** [comment]
> 我家网络好，不需要挂VPN
~~原本就不需要挂啊~~

**Comment by aaaapai** [comment]
> ~我是天天在github上嫖代码~

你这个字的代码保熟吗？还是在此网站里保熟的

**Comment by aaaapai** [comment]
> > 我家网络好，不需要挂VPN
> > ~原本就不需要挂啊~

不挂VPN呢，就是容易访问不了，我多按刷新就刷出来了

**Comment by ENDERMANYK** [comment]
上面那个人还没回复

**Comment by aaaapai** [comment]
> > 我家网络好，不需要挂VPN
> > ~原本就不需要挂啊~

你经常用的是什么文件管理器呢？

**Comment by aaaapai** [comment]
> 上面那个人还没回复

他估计是...不会和我一样，有的时候连接挂掉了吧？

**Comment by aaaapai** [comment]
> 上面那个人还没回复

只要我不在这网站挂机太久，我就不用魔法

**Comment by ENDERMANYK** [comment]
估计是没想到回复这么快
![%NNO{R5{K{VD90{{R5{((P9](https://user-images.githubusercontent.com/64646658/141647715-25f5af14-18b7-44d3-81e0-c8f310d0b7f1.png)

**Comment by aaaapai** [comment]
> 估计是没想到回复这么快 ![%NNO{R5{K{VD90{{R5{((P9](https://user-images.githubusercontent.com/64646658/141647715-25f5af14-18b7-44d3-81e0-c8f310d0b7f1.png)

哈哈，你这网图哪来的？

**Comment by aaaapai** [comment]
> 估计是没想到回复这么快 ![%NNO{R5{K{VD90{{R5{((P9](https://user-images.githubusercontent.com/64646658/141647715-25f5af14-18b7-44d3-81e0-c8f310d0b7f1.png)

那么你经常上什么中国mc论坛呢？我先来，苦力怕论坛

**Comment by aaaapai** [comment]
> 估计是没想到回复这么快 ![%NNO{R5{K{VD90{{R5{((P9](https://user-images.githubusercontent.com/64646658/141647715-25f5af14-18b7-44d3-81e0-c8f310d0b7f1.png)

等一下发现有人回复了，然后进不去，要么多次刷新，要么需要神奇的魔法

**Comment by ENDERMANYK** [comment]
> 那么你经常上什么中国mc论坛呢？我先来，苦力怕论坛

大陆的其实真不咋上，自己研究的东西都没有
![%NNO{R5{K{VD90{{R5{((P9](https://user-images.githubusercontent.com/64646658/141647862-740efe96-d8d5-4b7b-b7a1-fe9a48177431.png)

**Comment by CosineMath** [comment]
你们何不留个邮箱聊天呢（雾

**Comment by aaaapai** [comment]
> 估计是没想到回复这么快 ![%NNO{R5{K{VD90{{R5{((P9](https://user-images.githubusercontent.com/64646658/141647715-25f5af14-18b7-44d3-81e0-c8f310d0b7f1.png)

对了，我在那论坛发现有人鸿蒙启动pojavLauncher失败，我得提供好的版本给他

**Comment by aaaapai** [comment]
> 你们何不留个邮箱聊天呢（雾

要不我们邮箱聊天？

**Comment by aaaapai** [comment]
> > 那么你经常上什么中国mc论坛呢？我先来，苦力怕论坛
> 
> 大陆的其实真不咋上，自己研究的东西都没有 ![%NNO{R5{K{VD90{{R5{((P9](https://user-images.githubusercontent.com/64646658/141647862-740efe96-d8d5-4b7b-b7a1-fe9a48177431.png)

mcnb66666@yeah.net

**Comment by aaaapai** [comment]
> 你们何不留个邮箱聊天呢（雾

mcnb66666@yeah.net

**Comment by aaaapai** [comment]
正好可以试一下鸿蒙的邮件功能，可以变成微信似的功能试一下

**Comment by CosineMath** [comment]
> > 你们何不留个邮箱聊天呢（雾
> 
> [mcnb66666@yeah.net](mailto:mcnb66666@yeah.net)

github个人页面放邮箱是基本操作吧（

**Comment by aaaapai** [comment]
aaaa派 已退出github，请邮箱回复：mcnb66666@yeah.net

**Comment by aaaapai** [comment]
> > > 你们何不留个邮箱聊天呢（雾
> > 
> > 
> > [mcnb66666@yeah.net](mailto:mcnb66666@yeah.net)
> 
> github个人页面放邮箱是基本操作吧（

反正我不会[滑稽]

**Comment by ENDERMANYK** [comment]
> github个人页面放邮箱是基本操作吧（

~~*反正我是用discord*~~

**Comment by aaaapai** [comment]
> > github个人页面放邮箱是基本操作吧（
> 
> ~_反正我是用discord_~

开玩笑，反正没有魔法进不去

**Comment by hyplant** [comment]
> > actions里是啥测试版都有，你要正常使用下载带v3_openjdk的
> 
> 我下载了openjdk，却没想到我进入游戏滑动一下屏幕就给我崩了

我那个更不得了，基本上就是闪过游戏启动时的红色界面，然后就崩溃了。
就算启动mod安装程序，也只在日志输出中出现没几行以后就崩溃了。

**Comment by Mathias-Boulay** [comment]
Fixed now
