### ISSUE TITLE
[Request] FireTV support I guess

### ISSUE THREAD

**Issue by iNahilC** [PojavLauncherTeam/PojavLauncher#2236]
### Is this request related to a bug?

 Today I downloaded the Launcher for my FireTV to be able to play it with keyboard and mouse, the game menu works "fine" but in a world it becomes completely useless, the keyboard and mouse do not work.

### Describe the request.

It would be great if it had FireTV support (keyboard and mouse).

**Comment by WesleyVanNeck** [comment]
Open a issue

**Comment by Mathias-Boulay** [comment]
Nah, it might be fun to explore a bit, as I have a fire tv for myself.
@iNahilC We'll need some info though.
The exact model of FireTV, the pojav launcher version and obviously video footage

**Comment by Errorbot1122** [comment]
Since Fire TV uses a slightly modified version of the **Android TV OS**, It would be cool to port it to **Android TV** for it to work on **Nvidia Shield**

**Comment by dxcvvxd** [comment]
try using Super1dolOS extension for your firetv

**Comment by ErrorBot1122** [comment]
Also, you can add the controller support *via: [Controllable (Forge)](https://www.curseforge.com/minecraft/mc-mods/controllable) or [LabdaControls (Fabric)](https://www.curseforge.com/minecraft/mc-mods/lambdacontrols)*

**Comment by iNahilC** [comment]
→ **Device**: Toshiba 32LF221U21 31.5-inch Smart HD 720p TV - Fire TV, Released 2020

→ **PojavLauncher Version**: [GitHub Release v3.3.1.1 (app-debug.apk)](https://github.com/PojavLauncherTeam/PojavLauncher/releases/tag/v3.3.1.1)

**Comment by khanhduytran0** [comment]
> Since Fire TV uses a slightly modified version of the **Android TV OS**, It would be cool to port it to **Android TV** for it to work on **Nvidia Shield**

Why porting anymore? Android TV is Android already. We just need to get it to work with their own OpenGL 4 driver instead of going through the OpenGL-to-ES translator.

**Comment by khanhduytran0** [comment]
> → **Device**: Toshiba 32LF221U21 31.5-inch Smart HD 720p TV - Fire TV, Released 2020
> 
> → **PojavLauncher Version**: [GitHub Release v3.3.1.1 (app-debug.apk)](https://github.com/PojavLauncherTeam/PojavLauncher/releases/tag/v3.3.1.1)

Outdated version

**Comment by khanhduytran0** [comment]
Please get the latest build at https://github.com/PojavLauncherTeam/PojavLauncher/actions
