### ISSUE TITLE
[BUG] Crash Pojavlauncher while playing (no code error message 1)

### ISSUE THREAD

**Issue by UzakaZinnMCYTB** [PojavLauncherTeam/PojavLauncher#2238]
### Describe the bug

Hi. My name is UzakaZinnMC (Huỳnh Xuân Phúc), I live in Vietnam. When I was playing Pojavlauncher with a very high fps: 190 fps, after a while, it dropped fps, froze then was thrown into the lobby of Pojavlauncher. [Sorry for the poor English]

### Steps To Reproduce

```markdown
1. Launch Pojavlauncher 
2. go to Minecraft map 
3. Fps drop
4. Crash Pojavlauncher
```

### Expected Behavior

I hope Pojavlauncher releases this fix update

### Platform

```markdown
- Device model: Vivo Y21s
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Lastest Release in CH Play
```

**Comment by UzakaZinnMCYTB** [comment]
Trình độ Tiếng Anh của tôi rất kém. Xin lỗi
Nếu có thể hãy trả lời tôi bằng Tiếng Việt :(((

**Comment by WesleyVanNeck** [comment]
What do you expect it a PC game on a mobile
