### ISSUE TITLE
[BUG] (Chromebook) I Can't Type In Microsoft Login Text Boxes!!!

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2239]
### Describe the bug

When I click the *sign-In with Microsoft* button and try and click the Email box, nothing go inside, no matter what i do

### The log file and images/videos

I would have put something here but i cant record it rn

### Steps To Reproduce

```markdown
1. Open ProJevlancher on Chromebook (Maybe with external keyboard???)
2. Click the "Login with Microsoft" bottom
3. Try to type in the box
```

### Expected Behavior

I expected for me to be able to type in it

### Platform

```markdown
- Device model: ???
- CPU architecture: ??? 
- Android version: ???
- PojavLauncher version: ??? (I think latest, idk)
```

### Anything else?

I was able to type for like a frame while it was loading...

**Comment by Mathias-Boulay** [comment]
Let's start by filling the minimum info, then we'll take a look at the issue

**Comment by Mathias-Boulay** [comment]
Or get terminated.
Your choice

**Comment by khanhduytran0** [comment]
> 2. Click the "Login with Microsoft" bottom
> 3. Try to type in the box

Then how do you type without clicking into the box first? Does the cursor blink and the box highlight in the first place?

**Comment by Errorbot1122** [comment]
@Mathias-Boulay ! did!!! What else do I need to add?

P.S: I cant type the device spec thing because its hard to find that out on **chrome OS**...

**Comment by Errorbot1122** [comment]
> Then how do you type without clicking into the box first?

Yes i clicked to box but i wont let me type on the "Email box" for some reason...

> Does the cursor blink and the box highlight in the first place?

Yes it blinks...

**Comment by Errorbot1122** [comment]
**OH MY, IT JUST LET ME TYPE IN THE BOX!!!!!!!!!!!!!!**

Some how, when I typed in the box, it did not work, then when i focused my cursor somewhere else to remove the cursor, then click the box again, **IT LET ME TYPE IN IT,** and all the other boxes *(Just the password one too...)*

I think this works because when you click on the button, you are still it technically focused on *Projav Launcher*, not the sign in window. So you need to tell the app that you want to focus on the sign in window to let you type in it! I'm not sure if I'm right or not, but just putting it out there for the Devs to fix...

***I hope this helps anyone with the same issue...***
