### ISSUE TITLE
Can't use left mouse click when open inventory

### ISSUE THREAD

**Issue by truong0235** [PojavLauncherTeam/PojavLauncher#224]
I can't use left click (pri button) when open inventory (mouse mode on)
Maybe you didn't add that feature ?

**Comment by khanhduytran0** [comment]
You should try disable Touchscreen mode in game settings.

**Comment by truong0235** [comment]
I just have done it
And it close inventory instead :v

**Comment by truong0235** [comment]
That 's when i enable touch screen :v
When i disable it, the left click doesn't work when open inventory

**Comment by truong0235** [comment]
> I just have done it
> And it close inventory instead :v

**Comment by truong0235** [comment]
Are u there bro?

**Comment by truong0235** [comment]
Did u sovle the problem?

**Comment by khanhduytran0** [comment]
I'm very busy to solving it...

**Comment by truong0235** [comment]
Hope you finish the exam :b

**Comment by khanhduytran0** [comment]
Maybe try new build or v3?

**Comment by khanhduytran0** [comment]
Re-open if you still get.
