### ISSUE TITLE
I cant access 1.13 and above

### ISSUE THREAD

**Issue by john124343** [PojavLauncherTeam/PojavLauncher#2240]
### Describe the bug

I can't access 1.13 or above, they just aren't there

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

I expected to be able to play all versions

### Platform

```markdown
- Device model:oppo a5 2020
- CPU architecture:idk
- Android version:idk
- PojavLauncher version:idk
```

**Comment by NotAHero04** [comment]
So after 3 hours, have you managed to fill all the missing info or nah?

**Comment by artdeell** [comment]
Vsrsion not stated. Closing untill it will be stated.
