### ISSUE TITLE
lag spikes when placing blocks

### ISSUE THREAD

**Issue by NoNamestave** [PojavLauncherTeam/PojavLauncher#2242]
### Describe the bug

i got lag spike when im placing blocks with optifine i get 80 fps but when i place blocks i getting lag and ended up freezing the screen for 10 seconds 

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

i expect that this bug fix emmidiately

### Platform

```markdown
- Device model: Cherry mobile flare s7
- CPU architecture: MTK mt6739WA
- Android version: 8.1
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by artdeell** [comment]
your cpu is just shit, that's why it happens

**Comment by dxcvvxd** [comment]
to stop lags you can try mod SuperIdol.jar
