### ISSUE TITLE
[BUG] (Chromebook) Mouse Disappears Over "Emulated" Projev Window

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2244]
### Describe the bug

Whenever you try to hover your mouse over the "Emulated" (In equation marks because I'm not sure if Chromebooks really *Emulate* the app) window, the mouse disappears and you can't interact with anything inside the ProjavLauncher. **(Only tested  when I opened the log-in screen )**

### Steps To Reproduce

```markdown
1. Reinstall Projev Launcher
2. log in to an account (WITHOUT checking the "Remember Me" checkbox) 
3. Install 1.17.1
4. Click play
5. Crash the game somehow
6. Try and move your mouse over the new Instance
```

### Expected Behavior

For it to let me see my mouse and interact with buttons

### Platform

```markdown
- Device model: ??? (IDK)
- CPU architecture: ??? (IDK)
- Android version: ??? (It's a Chromebook)
- PojavLauncher version: Latest??? (IDK How to find out...)
```

### Anything else?

**THIS WILL PROBABLY ONLY HAPPEN ON CHROMEBOOKS**

The curse moves like normal, as in it is only invisible and can still move the mouse itself, BUT you can interact with anything SPECIFICALLY on the ProjevLauncher.

After the bug happens, all new instances of the launcher are affected.

**Quick Fix:** Restart your computer, **BUT** as I said it's only a *Quick* fix and gets really annoying after a while.

***DISCLAIMER: ALTHO I KNOW JAVASCRIPT, I HAVE NEVER CODED AN APP IN MY LIFE, SO PLEASE TAKE MY CLAMS WITH A GRAIN OF SALT!!!!***

**What  I Suspect:** I think this happens because, since a crash is very abrupt, the launcher does not have enough time to clear all the "window's settings." (especially the "`No Cursor`" setting on the window) And since right after a crash a new window (the launcher) is opened, all the old settings are automatically carried over to the new one.

**Again I could be completely wrong here because I have no background in android app coding or `C++`, but I do code a lot of `Javascript` so take my words with a grain of salt**

**Comment by mchnjt** [comment]
god there's no "projev launcher"

**Comment by khanhduytran0** [comment]
> - PojavLauncher version: <ins>Latest???</ins> (IDK How to find out...)

“Latest???” is not a valid version.

**Comment by khanhduytran0** [comment]
Also, there’s nothing called <ins>Projev Instance</ins>

**Comment by Errorbot1122** [comment]
@rscDoesMoreTrolling 
> god there's no "Projev launcher"
‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎👇  👀 
[PojavLauncherTeam / PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher)
🤦‍♂️ 

---
@khanhduytran0 
> “Latest???” is not a valid version.

I literally said:
> ... (IDK How to find out...)

---
@khanhduytran0 
> Also, there’s nothing called Projev Instance

It's my name for the window that pops, but ill rename it to fit it better

**Comment by WesleyVanNeck** [comment]
Am gone close this till you state your version

**Comment by khanhduytran0** [comment]
> ... (IDK How to find out...)

it's in the app info bruh
