### ISSUE TITLE
[F-Req] Viewing Max Available RAM

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2245]
### Is this request related to a bug?

No, Not yet...

### Describe the request.

I want to be able to view the max available ram when setting the allocated *RAM* so you won't get *RAM* errors when 
accidentally allocating too much RAM or too little.

### Anything else?

It would also be nice if there would be an option to **automatically** allocate by percent. (eg. You have **1GB** of *RAM* available and you chose **75%** of allocation, then it would be **1024MB *x* 0.75** or **768MB** of allocated *RAM*, and if it changes, it will update accordingly **UNLESS,** you check the "Fixed option" (Automatically **checked** by default))

**Comment by moha0116** [comment]
me too

**Comment by Mathias-Boulay** [comment]
Android lies about how much ram is available.
Also, if we take the lowest number we can get, you would be hovering at 1GB, even with a 6GB device

**Comment by jethro527** [comment]
Yeah me too I have 2gb ram but 300mb only I can use

**Comment by Errorbot1122** [comment]
@Mathias-Boulay also, what is the recommended ram usage

**Comment by ghost** [comment]
> @Mathias-Boulay also, what is the recommended ram usage

1gb ram: 300 mb
2gb ram: 512 mb
3-4gb ram: 800mb-1gb
6gb: 1gb-2gb
8gb or more: any you like
it just my opinion

**Comment by dachisao** [comment]
recommended ram don't matter... just overallocate ram and watch your phone explode

**Comment by ghost** [comment]
> recommended ram don't matter... just overallocate ram and watch your phone explode

oh yea

**Comment by Mathias-Boulay** [comment]
> @Mathias-Boulay also, what is the recommended ram usage

It actually depends from the mc version and the ram available on the phone
For new users, the ram amount set is the most likely amount to be allocated without a crash

**Comment by ghost** [comment]
> > @Mathias-Boulay also, what is the recommended ram usage
> 
> It actually depends from the mc version and the ram available on the phone
> For new users, the ram amount set is the most likely amount to be allocated without a crash

with me i just gonna allocate 1gb ram and got 30+ fps on all version

**Comment by Errorbot1122** [comment]
> > @Mathias-Boulay also, what is the recommended ram usage
> 
> 1gb ram: 300 
> mb 2gb ram: 512 mb
> 3-4gb ram: 800mb-1gb
> 6gb: 1gb-2gb 
> 8gb or more: any you like it just my opinion

@GoneSubject okay so, how would I check my ram (On Chromebook...)

> > @Mathias-Boulay also, what is the recommended ram usage
> 
> It actually depends from the mc version and the ram available on the phone For new users, the ram amount set is the most likely amount to be allocated without a crash

@Mathias-Boulay I'm using 1.17.1 rn (I like using the newest version, so make us be able to change our default on startup...)

**Comment by moha0116** [comment]
i have 2gb ram, he show i can use 1100 mb if i use 901+ mb game crash

**Comment by Mathias-Boulay** [comment]
32 bits devices I see

**Comment by ghost** [comment]
> > > @Mathias-Boulay also, what is the recommended ram usage
> > 
> > 1gb ram: 300 
> > mb 2gb ram: 512 mb
> > 3-4gb ram: 800mb-1gb
> > 6gb: 1gb-2gb 
> > 8gb or more: any you like it just my opinion
> 
> @GoneSubject okay so, how would I check my ram (On Chromebook...)
> 
welp uh there's lot of ways but you can find it yourself

**Comment by SprainedSpark89** [comment]
it would help it would just a calculation that the app can do so it would tell you how much ram=to memory

**Comment by Errorbot1122** [comment]
@Mathias-Boulay **I FOUND SOMETHING THAT COULD MAKE IT WORK**

Um so Today, I did was looking around some stuff and found this app called **[Cog System Info Veiwer](https://chrome.google.com/webstore/detail/cog-system-info-viewer/difcjdggkffcfgcfconafogflmmaadco?hl=en)** I thought it was cool, so I found it's [github repo](https://chrome.google.com/webstore/detail/cog-system-info-viewer/difcjdggkffcfgcfconafogflmmaadco?hl=en) and look at the readme, and found APIS!!!!! :). There are official [google APIs](https://developer.chrome.com/docs/extensions/mv3/declare_permissions/#system.cpu) out there that tell you the **CURRENT INFO** of your **ANDROID DEVICE!!** (Chromebooks work also)

I guess dead dreams do come true...

**P.S: I only just learned about the API, and I don't know if it works or not for IOS, but probably not...**

**Comment by SprainedSpark89** [comment]
Here is something i made to help people on chromebook https://github.com/PojavLauncherTeam/PojavLauncher/issues/2537

**Comment by SprainedSpark89** [comment]
And that app is not official it's not by google

**Comment by Errorbot1122** [comment]
no, the **APIs ARE**

**Comment by SprainedSpark89** [comment]
just be careful with the app and is a little useless in some ways like press search and esc for task manager and ctrl search esc brings up diagnostics.

**Comment by SprainedSpark89** [comment]
and do ctrl alt t to bring up crosh

**Comment by Errorbot1122** [comment]
OOOOFFFF, crosh is blocked :(

**Comment by SprainedSpark89** [comment]
is there a issue still?

**Comment by Errorbot1122** [comment]
Its not an issue, its a F-Request

**Comment by Errorbot1122** [comment]
I will close it when they add it

**Comment by Errorbot1122** [comment]
or if I just want to close it 😜

**Comment by artdeell** [comment]
Or we will close it. But not now.
Btw, all Android APIs lie about how much memory could be actually allocated. Because Java uses system memory not only for heap, but also for individual thread stacks, JIT code cache, profiling info, et cetera et cetera and we can't predetermine how much will it actually use.

**Comment by SprainedSpark89** [comment]
yah

**Comment by Errorbot1122** [comment]
@artdeell and @Mathias-Boulay 

> Btw, all Android APIs lie about how much memory could be actually allocated.

Okay, even if it does lie about the RAM it should be fine. If it tells you less memory than actually is left the Projav can use it like normal since no one would really care, it's only bad if it goes over.

**Comment by SprainedSpark89** [comment]
close this there is no more issue

**Comment by Errorbot1122** [comment]
okay? but thay did not add it did that?

**Comment by SprainedSpark89** [comment]
sometimes you have to deal with things

**Comment by Errorbot1122** [comment]
:(

**Comment by SprainedSpark89** [comment]
yah i know how it feels
