### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by 1493028** [PojavLauncherTeam/PojavLauncher#2248]
### Is this request related to a bug?

Not

### Describe the request.

Lag

### Anything else?

Laggg

**Comment by 1493028** [comment]
Lagg in minecraft 1.17

**Comment by khanhduytran0** [comment]
"Lag” is an invalid request.
Does your **phone** have Intel Core i9 and RTX 3090 to play 1.17.1 with SEUS PTGI E13 at 4K 144fps?

**Comment by 1493028** [comment]
lag when I play minecraft 1.17 optifine my cellphone Vivo y50 ram 8gb Rom 128 GB Pojav launcher latest release crocus V3 openjdk

**Comment by 1493028** [comment]
> lag when I play minecraft 1.17 optifine my cellphone Vivo y50 ram 8gb Rom 128 GB Pojav launcher latest release crocus V3 openjdk

Snapdragon665

**Comment by khanhduytran0** [comment]
That’s about 1.9 GHz, but [Minecraft minimum requirements](https://help.minecraft.net/hc/en-us/articles/4409225939853-Minecraft-Java-Edition-Installation-Issues-FAQ) specified 3.1 GHz. Now you should know why. We aren’t Mojang nor Microsoft so don’t ask us for improving performance. We just develop the launcher, not the game.

**Comment by 1493028** [comment]
My pojav settings

Graphics:fancy
Smooth lighting:off
Smooth lighting level:off 
GUI scale:2
Brightness:100%
Dynamic light:off 
Shader:off 

Details

Clouds:off
Trees:default (fancy)
Sky:off
Sun and moon:off
Fog:off
Translucent block:fast
Dropped item:fast
Vignette:fast
Rain and snow:off 
Stars:off
Show cape:on
Fog stars:0.8
Swamp color:off
Alternate block:off
Biome bland:5×5 

Quality

Mipmap:off
Mipmap type:nearest
Anistropic filtering:off
Antialiasing:off
Emmisive texture:off
Better grass:off
Custom fornts:off
Connected texture:off
Custom sky:off
Custom entity models:off 
Random entities:off 
Better snow:off 
Custom color:off 
Natural texture:off 
Custom items:on
Custom GUI:on

Performance

Render region:off
Smart animation:off
Smooth fps:off
Chunk updates:1
Lazy chunk loading:on
Fast render:off
Fast math:off
Smooth world:off
Dynamic updates:off

Other 

Lagomater:off
Show fps:on
Weather: off
Fullscreen:on
Debug profiler:off
Advanced tooltip:off 
Time:default
Auto save:12min
Show gl errors:off

**Comment by NotAHero04** [comment]
You can't expect having 69 fps with 1.17.1 on just an **entry-level** chipset designed for **mobile**.
