### ISSUE TITLE
最新版本Android ci玩不了了 The latest version of Android CI can't play anymore

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2250]
### Describe the bug

 最新版本Android ci玩不了了
The latest version of Android CI can't play anymore

### Steps To Reproduce

```markdown
1.
```

### Expected Behavior

1.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ajit850** [comment]
Why?

**Comment by netkv** [comment]
fill the template bruh

**Comment by T-CATHOME** [comment]
我能用啊？

**Comment by aaaapai** [comment]
> 我能用啊？

我启动1.17，它崩了

**Comment by aaaapai** [comment]
> > 我能用啊？
> 
> 我启动1.17，它崩了

按正常来说是能启动的，自从更新了之后就崩了
