### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Duy2511** [PojavLauncherTeam/PojavLauncher#2253]
### Describe the bug

Tôi bị 1 lỗi đó là : Ứng dụng/Trò chơi đã thoát với mã 1.

### The log file and images/videos

![Screenshot_20211118_175718](https://user-images.githubusercontent.com/94611096/142402860-3cf51fcd-c775-496a-8ab9-489130882874.jpg)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

Tôi mong nhà phát hành sớm khắc phục lỗi này

### Platform

```markdown
- Device model:Vivo 21s/ 128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: [Bản phát hành mới nhất || phiên bản 3.3.1.1_rel_20210206]
```

**Comment by InfiniXDerg** [comment]
English please

**Comment by Duy2511** [comment]
> English please

I got 1 error which is : Application/Game exited with code 1.

**Comment by khanhduytran0** [comment]
It means almost  #<ins>everything</ins>, including but not limited to:
- attempt to launch Minecraft 1.18 without a changing assets-v0
- ram amount too high or low
- mod error
- OpenGL error
- etc..

<ins>We don’t access your log through the internet without you first upload it.</ins>
`The log file and images/videos`: missing required component: latestlog.txt
`Steps To Reproduce`: invalid (empty).
