### ISSUE TITLE
[F-Req] Add a mouse toggle as an option in Controll customization 

### ISSUE THREAD

**Issue by Sumrak-Sumarokov** [PojavLauncherTeam/PojavLauncher#2255]
### Describe the request.

Add a new button for toggle mouse. It's really annojing that every time when you start the game, you should press SPECIAL_mouse button

**Comment by Mathias-Boulay** [comment]
You can toggle the mouse and bind this to a controlButton

**Comment by Sumrak-Sumarokov** [comment]
No, this is not what i ment. Not like on screen button, like an option in launcher settings
