### ISSUE TITLE
Pojavlauncher latest version:  3e5f04a v3_openjdk crash in 1.7.10

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#2256]
### Describe the bug

Example: Application exited with code 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7571073/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.launch minecraft 1.7.10
3.play for 1-10 minute
```

### Expected Behavior

Example: I launch the game then play and then crash in 1-10 minute 

### Platform

```markdown
- Device model: galaxy j2
- CPU architecture: areech 32
- Android version: 5.1.1
- PojavLauncher version: 
 3e5f04a
v3_openjdk
```

### Anything else?

Please fix this problem as soon as possible

**Comment by Sazedzahan** [comment]
Please help me

**Comment by Mathias-Boulay** [comment]
Known, useless to create an issue for it
