### ISSUE TITLE
Please hibernate the launcher when the device goes into sleep mode!

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2257]
### Describe the request.

Make hibernation in sleep mode, when the game does not use the battery, and when the phone wakes up from sleep mode, the hibernation will turn off and the game will consume resources again!

### Anything else?

Please! I will be grateful if you implement this!

**Comment by Mathias-Boulay** [comment]
As much as I would like to have such a feature, I'm pretty sure it cannot be made
