### ISSUE TITLE
Eror[BUG] <Short description>

### ISSUE THREAD

**Issue by skyVGZ** [PojavLauncherTeam/PojavLauncher#2259]
### Describe the bug

You clik ap

### The log file and images/videos

Get stars

### Steps To Reproduce

```markdown
Pojav no eror link 
Distoryi
```

### Expected Behavior

Get to rednaut pojav to login

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Get to no eror

**Comment by khanhduytran0** [comment]
Form is not properly filled, closing as invalid.
~~are you too lazy to fill it?~~
