### ISSUE TITLE
New version for pojavlauncher 2.5 pre1 ?

### ISSUE THREAD

**Issue by CastusMike** [PojavLauncherTeam/PojavLauncher#226]
I use device android 32bit , i want play new version 2.5

**Comment by khanhduytran0** [comment]
But v2 still support 32-bit.

**Comment by CastusMike** [comment]
> Nhưng v2 vẫn hỗ trợ 32-bit.

I don't have 64 bit device , i want a new version 2.5

**Comment by khanhduytran0** [comment]
(Still using Google Dịch?)
Hỗ trợ 32-bit cho v3 đang được lên kế hoạch.

**Comment by CastusMike** [comment]
> (Still using Google Dịch?)
> Hỗ trợ 32-bit cho v3 đang được lên kế hoạch.

Sao lại nói tôi sài gg dịch tôi biết chút về english xíu chứ 1 số từ tôi k bt ms xài gg dịch , khi nào v3 sẽ hỗ trợ 32 bit ?

**Comment by khanhduytran0** [comment]
> Sao lại nói tôi sài gg dịch tôi biết chút về english xíu chứ 1 số từ tôi k bt ms xài gg dịch

Tại thấy cái trích dẫn bị dịch sang tiếng việt...

> khi nào v3 sẽ hỗ trợ 32 bit ?

Khi bản v3 tiếp theo ra mắt sẽ hỗ trợ 32bit nha. Mà bản tiếp theo thì hơi bị lâu mới xong.

**Comment by CastusMike** [comment]
Đợi lâu rồi bây h lại phải đợi lâu :(( hỗ trợ cả 32 lẫn 64 thì quá ok như
MCinaBox

Vào 16:36, T.6, 5 Th6, 2020 Tran Khanh Duy <notifications@github.com> đã
viết:

**Comment by khanhduytran0** [comment]
Bên MCInaBox đi từ 32-bit giờ mới lên 64-bit. V3 bên này hoàn toàn khác MCInaBox và không sử dụng mã nguồn của bên đó nên thời gian code lâu hơn và bên MCInaBox được cộng đồng hỗ trợ rất nhiều nên làm gì cũng nhanh mà ở đây chỉ vỏn vẹn 2 người (bao gồm mình).

**Comment by khanhduytran0** [comment]
Cho dù mình có mã nguồn mở cũng ít ai quan tâm :v

**Comment by CastusMike** [comment]
Có lí , mình ko biết lập trình gì cả nên k giúp đc

Vào 16:44, T.6, 5 Th6, 2020 Tran Khanh Duy <notifications@github.com> đã
viết:

**Comment by truong0235** [comment]
Eyyyyyy
 Vietnamese :)))))

**Comment by Doxelix** [comment]
Yyyyyy

**Comment by Mikar9** [comment]
> Eyyyyyy
> Vietnamese :)))))

Hey bro :))))

**Comment by Mikar9** [comment]
> Bên MCInaBox đi từ 32-bit giờ mới lên 64-bit. V3 bên này hoàn toàn khác MCInaBox và không sử dụng mã nguồn của bên đó nên thời gian code lâu hơn và bên MCInaBox được cộng đồng hỗ trợ rất nhiều nên làm gì cũng nhanh mà ở đây chỉ vỏn vẹn 2 người (bao gồm mình).

V3 hỗ trợ 32bit xong chưa ad

**Comment by khanhduytran0** [comment]
> > Bên MCInaBox đi từ 32-bit giờ mới lên 64-bit. V3 bên này hoàn toàn khác MCInaBox và không sử dụng mã nguồn của bên đó nên thời gian code lâu hơn và bên MCInaBox được cộng đồng hỗ trợ rất nhiều nên làm gì cũng nhanh mà ở đây chỉ vỏn vẹn 2 người (bao gồm mình).
> 
> V3 hỗ trợ 32bit xong chưa ad

Chưa do là cái phần quan trọng nhất của v3 vẫn chưa xong: OpenGL. Việc đưa qua 32 bit theo hiện tại là dễ dàng.

**Comment by Mikar9** [comment]
Vậy ad biết khi nào xong không ?

Vào 11:49 AM, CN, 21 Th6, 2020 Tran Khanh Duy <notifications@github.com> đã
viết:

**Comment by khanhduytran0** [comment]
> Vậy ad biết khi nào xong không ?

Chưa biết nữa! Hiện tại một đống lỗi...

**Comment by khanhduytran0** [comment]
Thì hiện tại V3 đã gần xong, hỗ trợ 1.7+. Và cũng có 64bit.
