### ISSUE TITLE
[BUG] Cannot change language to Zh-CN again.

### ISSUE THREAD

**Issue by peasoft** [PojavLauncherTeam/PojavLauncher#2260]
### Describe the bug

I change app's language to English or other languages, then change back to zh-cn, but in fact the language is English.

### The log file and images/videos

![Screenshot_2021-11-21-11-09-35-22](https://user-images.githubusercontent.com/55051861/142748045-72a84d24-3779-447a-83e3-19be0cff783f.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Change the language to English or others
3. Change back the language to zh-cn
4. The language is zh-cn, but the buttons, texts are English
```

### Expected Behavior

Change back the language.

### Platform

```markdown
- Device model: 
- CPU architecture: arm64
- Android version: 5
- PojavLauncher version: Latest version on Github Action
```

**Comment by maulxz** [comment]
Try to delete options file
Or change it

**Comment by peasoft** [comment]
> 

Where is the option file?

**Comment by Skyinthesky** [comment]
> > 
> 
> Where is the option file?

sd card/games/PojavLauncher/.minecraft(make sure to turn on hidden file)/option.txt

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
