### ISSUE TITLE
Hot to fix Sodium & Dynamic Surrounding bugs

### ISSUE THREAD

**Issue by maulxz** [PojavLauncherTeam/PojavLauncher#2261]
### **Mod List :**
1. Sodium (not the newest version)
2. Dynamic Surrounding 1.12

### **Known Bug :**
**Sodium**
- Crashes; Chunks bug; etc

**Dynamic Surrounding**
- Effect bug (white textures)

### **How To Fix :** 

**Sodium**

- turn off `Compact Vertex Format` (caused crash `if on`)
- turn off `Fog  Occlusion` (chunks will glitch `if on`)
- use `open gl 3.0` (in sodium's settings)

**Dynamic Surrounding**

- turn off all effect `fireflies` `footsteps` `etc`

**Comment by maulxz** [comment]
I don't think it 100% works, it depends on your devices

**Comment by SameerRaza69** [comment]
Which version of sodium to download

**Comment by ghost** [comment]
> Which version of sodium to download
> 

use 1.0.0 and below, it crashed for higher

**Comment by maulxz** [comment]
> > Which version of sodium to download
> 
> use 1.0.0 and below, it crashed for higher

**It  won't, if you turn off `compact vertex format` in old version 1.0.0 or 1.1.0, and then upgrade to the latest.**
(according to my experience)

and sorry my english is bad lol

**Comment by ghost** [comment]
> 



> > > Which version of sodium to download
> > 
> > 
> > use 1.0.0 and below, it crashed for higher
> 
> **It won't, if you turn off `compact vertex format` in old version 1.0.0 or 1.1.0, and then upgrade to the latest.** (according to my experience)
> 
> and sorry my english is bad lol

hmm i didn't know that

**Comment by adroslice** [comment]
> It won't, if you turn off `compact vertex format` in old version 1.0.0 or 1.1.0, and then upgrade to the latest.

Doesn't work for 1.16.5

**Comment by Mathias-Boulay** [comment]
#1948
