### ISSUE TITLE
Oppo phones problem

### ISSUE THREAD

**Issue by maulxz** [PojavLauncherTeam/PojavLauncher#2262]
If you're using an **Oppo phones**, **you can not** allocated more than **1 GB ram**.

Why?, In Oppo system if you're have application that 
use more than 1Gb ram, your system will force close it.

Especially if u just have 1/2/3 Gb of ram.

**Comment by khanhduytran0** [comment]
Why did you get rid of the form? Does it look like nothing to you?
I assume that your device is <ins>32bit</ins> and so it’s not supposed to allocate too much.

**Comment by maulxz** [comment]
No i just write my friends opinion
And my sistem is 6Gb 64bit

**Comment by khanhduytran0** [comment]
> And my sistem is 6Gb 64bit

Invalid. It doesn’t match what you said.

> Especially if u just have 1/2/3 Gb of ram.

**Comment by mchnjt** [comment]
I can run pojav with an oppo phone. No problems at all

**Comment by maulxz** [comment]
6gb ram not storage

**Comment by mchnjt** [comment]
I remember installing an old version and i can allocate more than 1GB

**Comment by mchnjt** [comment]
N

> 6gb ram not storage

Did I specifically say storage?

**Comment by mchnjt** [comment]
Let me make it clear for you.

I have an oppo phone (A71). It has 3GB of RAM.
> I remember installing an old version and i can allocate more than 1GB

**Comment by maulxz** [comment]
> N
> Did I specifically say storage?

I'm not talking to u

**Comment by maulxz** [comment]
> > And my sistem is 6Gb 64bit
> 
> Invalid. It doesn’t match what you said.
> 
> > Especially if u just have 1/2/3 Gb of ram.

I'm talking to him

**Comment by mchnjt** [comment]
God, how rude.

**Comment by maulxz** [comment]
> God, how rude.

Sorry i live in asian so idk that word is rude

**Comment by maulxz** [comment]
It's normal in my language

**Comment by mchnjt** [comment]
Welp, I can't do anything more if you don't need me. All I can do here is just to say that I can allocate more than 1GB of RAM, according to what you said
> If you're using an Oppo phones, you can not allocated more than 1 GB ram.

**Comment by maulxz** [comment]
> Welp, I can't do anything more if you don't need me. All I can do here is just to say that I can allocate more than 1GB of RAM, according to what you said
> 
> > If you're using an Oppo phones, you can not allocated more than 1 GB ram.

Okay, so its just wrong information

**Comment by maulxz** [comment]
I'm gonna delete it

**Comment by maulxz** [comment]
Wait i can't lol

**Comment by NotAHero04** [comment]
> Welp, I can't do anything more if you don't need me. All I can do here is just to say that I can allocate more than 1GB of RAM, according to what you said
> 
> > If you're using an Oppo phones, you can not allocated more than 1 GB ram.
>
I tested on a 32-bit Oppo phone with 1.1GB RAM allocated, and hadn't seen a single crash.
