### ISSUE TITLE
[F-Req] random stash of unordered ideas

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2266]
### Is this request related to a bug?

No

### Describe the request.

Ideas for control revision 4.6-
1. **Add a customisable controller**( _we should be able to change the button codes for North, South, East, West and north-east etc if we want_ )**don't know how hard it would be but it would be cool**
2. **Flip the install jar and custom controls button**( I know the actions tab things have no support but I have seen many who click the _custom controls button_ instead of _install jar_ even me is mistaken by it )
3. **Add a in-game button to delete versions fully from the game files**( _i mean it sucks to always go to z archiver to delete those files_ )
4. **Add a button in settings to _skip assets_ download or not**( I mean mistakes are done by everyone right? )

### Anything else?

I know that it's hard to pull off those things but still these are just ideas which you can add 

Thank you for reading

**Comment by ghost** [comment]
I just noticed that the issue number is 2266 lol 😆

**Comment by Mathias-Boulay** [comment]
Aside from the first idea, nothing is related to control revisions.

**Comment by ghost** [comment]
> Aside from the first idea, nothing is related to control revisions.

But it would be helpful if it is added

**Comment by Mathias-Boulay** [comment]
*modified the title to be more accurate*
