### ISSUE TITLE
About pojavlauncher account log in 

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#2269]
### Describe the request.

Please add login system like minecraft launcher . Means you only login one's. it will be for permanently.you don't have to log in to your account again when you reopen the launcher and you can also remove or add account like minecraft launcher

**Comment by mchnjt** [comment]
haha clown 🤡

**Comment by mchnjt** [comment]
fuck off

**Comment by mchnjt** [comment]
Wait no

**Comment by mchnjt** [comment]
Sorry lmao, I accidentally misread it as tlauncher

**Comment by mchnjt** [comment]
Well, Minecraft login exist in pojav

**Comment by mchnjt** [comment]
email/username, password tab, and login tab exists :frwoe:

**Comment by khanhduytran0** [comment]
@Sazedzahan does this look like anything to you?
![Không có tiêu đề1 (3)](https://user-images.githubusercontent.com/40482367/142794327-1c342547-e73a-44d5-bd6a-af03e2ff4f0d.png)
![Screenshot_2021-11-22-09-45-35](https://user-images.githubusercontent.com/40482367/142794331-9c74a7c7-d0f5-41d6-b99f-9a5037128d9a.png)

**Comment by khanhduytran0** [comment]
>  it will be for permanently.you don't have to log in to your account again when you reopen the launcher

Did you mean selecting an account as default? ~~how does it compared to 2 more clicks?~~

**Comment by Sazedzahan** [comment]
yes selecting an account as default
