### ISSUE TITLE
Java. Attempt to invoke virtual...

### ISSUE THREAD

**Issue by SpaghettoSensei** [PojavLauncherTeam/PojavLauncher#227]
Hi. Now I have this problem, in addition to the screen being gray.
![Screenshot_20200606-083556_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/66449669/83945939-715bc880-a7d3-11ea-97e6-8f023683bcf7.jpg)
Pruebo el Lancher 2.5.0 y la versión 1.15.2.

**Comment by khanhduytran0** [comment]
You can't start 1.12 or above in v2

**Comment by khanhduytran0** [comment]
Wontfix in v2.

**Comment by khanhduytran0** [comment]
> You can't start 1.12 or above in v2
