### ISSUE TITLE
Sodium Extra Not Working

### ISSUE THREAD

**Issue by JohnPrinceDugan** [PojavLauncherTeam/PojavLauncher#2270]
### Describe the bug

I Installed the sodium extra mod then when i open the video setting it crash bruhhhhhh

### Steps To Reproduce

```markdown
Install sodium extra mod
Open video settings
Then It Crash
```

### Expected Behavior

I expected to boost my fps

### Platform

```markdown
- Device model: Oppo A5s
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by Mathias-Boulay** [comment]
latest release isn't a version.
#1948
