### ISSUE TITLE
about pojavlauncher account log in( this is a feature request with video clip )

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#2271]
### Describe the bug

This is not a bug this is a feature request with a video clip

### The log file and images/videos

https://user-images.githubusercontent.com/79019908/142858449-e65c1a0e-8fa2-4b74-bbe9-d3b65243733c.mp4

### Steps To Reproduce

```markdown
This is not a bug this is a feature request with a video clip
```

### Expected Behavior

(This is not a bug this is a feature request with a video clip) Please add login system like minecraft launcher . Means you only login one's. it will be for permanently.you don't have to log in to your account again when you reopen the launcher and you can also remove or add account like minecraft launcher (if you don't understand please see the video clip)

### Platform

```markdown
This is not a bug this is a feature request with a video clip
```

**Comment by ghost** [comment]
welp Pojavlauncher have that login system but you don't know

**Comment by Mathias-Boulay** [comment]
but once you're logged in it is permanent, I don't see where your issue is.
