### ISSUE TITLE
Minecraft gui does not work. (Play store app)

### ISSUE THREAD

**Issue by dabombdgdzjr** [PojavLauncherTeam/PojavLauncher#2274]
### Describe the bug

Hello.

I just recently got this on the play store as a little experiment, and tried launching.
Obviously, minecraft 1.17 doesn't work so I tried 1.14. The buttons like "options" or "Singleplayer" or any of the other ones didn't work. I don't currently have a mouse with me. I tried the mouse option, and when hovering, the buttons don't highlight. I tried double clicking, triple clicking, and just clicking, but to no avail.

Anyone know why this might be happening, and a fix for it? I'm on Samsung galaxy s10.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch any version of minecraft
3. You're there. Clicking doesn't work.
```

### Expected Behavior

I expected the buttons to be able to press.

### Platform

```markdown
- Device model: Samsung Galaxy S10
- CPU architecture: I don't know.
- Android version: 11
- PojavLauncher version: latest, so v3 I think.
```

**Comment by khanhduytran0** [comment]
> minecraft 1.17 doesn't work

*I see your attempt to play Minecraft 1.17 with java 8*. You need to install java 17 first. Follow [this](https://pojavlauncherteam.github.io/updates/117.html) for more details.

> 1.14. The buttons like "options" or "Singleplayer" or any of the other ones didn't work.

Minecraft versions in range of 1.13-1.14.4 may not work properly at the moment. Check if you have fullscreen enabled.

**Comment by Mathias-Boulay** [comment]
V3 isn't latest version

**Comment by dabombdgdzjr** [comment]
> _I see your attempt to play Minecraft 1.17 with java 8_. You need to install java 17 first. Follow [this](https://pojavlauncherteam.github.io/updates/117.html) for more details.

Yeah I already knew that lol. I kinda figured since 1.17 needed java 17 and I had to upgrade on my PC, but I tested it anyway.

**Comment by dabombdgdzjr** [comment]
> V3 isn't latest version

Well thats kinda the latest update in the news tab :/

**Comment by khanhduytran0** [comment]
Closing as of inactivity issue.
