### ISSUE TITLE
The pojav background cannot be started because it is not deleted

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2275]
### Describe the bug

我刚去打电动（进入游戏）休息（退出）了之后，休息够了继续打电动（重新进入），发现无法再启动，需要重新安装运行库；删掉pojav后台，重新打开pojav启动器即可继续，但退出了游戏，不删一次再次启动会崩溃！I just went to play video game (enter the game) rest (exit), rest enough to continue to play video game (re-enter), found no restart, need to reinstall the runtime; Delete pojav background, restart pojav launcher can continue, but quit the game, do not delete a restart will crash!

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7602656/latestlog.txt)
[crash-2021-11-23_13.53.52-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7602780/crash-2021-11-23_13.53.52-client.txt)

### Steps To Reproduce

```markdown
1.Open game
2.Exit the game
3.Open game
4.Collapsed!

Solution, but trouble:
1.Delete vms
2.Add vms
3.Enter the game
4.success

or

1.Delete pojav background
2.Restart
3.success
```

### Expected Behavior

Can you fix it?

### Platform

```markdown
- Device model: 
- CPU architecture: MediaTek 天玑800
- Android version: 10（Harmony OS 2）
- PojavLauncher version: crocus-228-2ec6c4d18-v3_openjdk
```

### Anything else?

Solution operation. After entering the game, exit and carry out a solution again
It's not as convenient as before. Quit. You don't need to delete the background. You can start it again

**Comment by Mathias-Boulay** [comment]
Unsupported os, we don't have any harmony os device to debug with

**Comment by aaaapai** [comment]
应该一样的，这个系统提供给安卓应用版本号是安卓十，想下windows11如何兼容安卓的，大概提供给安卓应用的也是安卓十It should be the same. This system is provided for android applications with the version number of android 10. I want to think about how windows11 is compatible with android发自我的荣耀手机

**Comment by aaaapai** [comment]
> Unsupported os, we don't have any harmony os device to debug with

Can hongmeng system be compatible with Android applications? How about compatibility? What is so different about HarmonyOS? The following small series to introduce.
How is the compatibility of Hongmeng system and Android applications
Huawei's Hongmeng system works well with all Android apps and improves performance by more than 60% when recompiled.
So why is Hongmeng compatible with Android applications?
Hongmeng is developed based on Aosp, which is open source, or white box in the jargon. For a white box operating system, once you understand its principle, even if you completely rebuild a new operating system, as long as there is enough time and talent, there will be no big problem to support the above APP to run.
For example, Windows WSL completely implements Linux operating system primitives from the kernel layer, which is equivalent to Windows NT kernel becoming a Compatible Linux kernel, so the corresponding applications are installed.
Look AT Huawei's Fang Zhou compiler, the system above the Java execution environment AT+JIT+ parsing execution way out. Directly compile the Android app into machine instructions to run. That is to say, technically speaking, Hongmeng can make the native Android app run in the same way as the original Android VIRTUAL machine, or it can be compiled into machine code to run through the Ark compiler.
What is so different about HarmonyOS
HarmonyOS is an interconnected system that is committed to distribution. It's not just a cell phone system, it can be a TV system, it can be a refrigerator system or a microwave system. So HarmonyOS is a system that can be applied to all electronic devices. It excels in multi-device collaboration.
HarmonyOS isn't just an operating system for mobile phones, it's an operating system for electronic devices, making it easier to switch between devices or collaborate with them. This is the advantage of distributed systems.
来自

**Comment by aaaapai** [comment]
Can hongmeng system be compatible with Android applications? How about compatibility? What is so different about HarmonyOS? The following small series to introduce.How is the compatibility of Hongmeng system and Android applicationsHuawei's Hongmeng system works well with all Android apps and improves performance by more than 60% when recompiled.So why is Hongmeng compatible with Android applications?Hongmeng is developed based on Aosp, which is open source, or white box in the jargon. For a white box operating system, once you understand its principle, even if you completely rebuild a new operating system, as long as there is enough time and talent, there will be no big problem to support the above APP to run.For example, Windows WSL completely implements Linux operating system primitives from the kernel layer, which is equivalent to Windows NT kernel becoming a Compatible Linux kernel, so the corresponding applications are installed.Look AT Huawei's Fang Zhou compiler, the system above the Java execution environment AT+JIT+ parsing execution way out. Directly compile the Android app into machine instructions to run. That is to say, technically speaking, Hongmeng can make the native Android app run in the same way as the original Android VIRTUAL machine, or it can be compiled into machine code to run through the Ark compiler.What is so different about HarmonyOSHarmonyOS is an interconnected system that is committed to distribution. It's not just a cell phone system, it can be a TV system, it can be a refrigerator system or a microwave system. So HarmonyOS is a system that can be applied to all electronic devices. It excels in multi-device collaboration.HarmonyOS isn't just an operating system for mobile phones, it's an operating system for electronic devices, making it easier to switch between devices or collaborate with them. This is the advantage of distributed systems.

**Comment by aaaapai** [comment]
> Unsupported os, we don't have any harmony os device to debug with

要不先看一下我发的视频是怎么崩的？Why don't you watch my video crash first?

**Comment by ENDERMANYK** [comment]
~~no log moment~~

**Comment by aaaapai** [comment]
> ~no log moment~

蓝色字，蓝色字

**Comment by ENDERMANYK** [comment]
log have more informantion than a video, ~~*you know?*~~, also seems the video was taken down

**Comment by aaaapai** [comment]
> log have more informantion than a video, ~_you know?_~, also seems the video was taken down

Blue word, this is China website, Kwai Fu.
Besides, I can see it

**Comment by khanhduytran0** [comment]
Can't even open the video, it just display for a second, then force me to download the app, but the app is not available in my country.

and why if this option exists? 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/40482367/143381334-294df7cf-cf53-4abb-805b-31be8343e26c.png">

Now video doesn't matter, send the log instead.

**Comment by aaaapai** [comment]
> Can't even open the video, it just display for a second, then force me to download the app, but the app is not available in my country.
> 
> and why if this option exists? <img alt="image" width="508" src="https://user-images.githubusercontent.com/40482367/143381334-294df7cf-cf53-4abb-805b-31be8343e26c.png">

Why don't you download the video? You'd better download it on your mobile phone and click the third one

**Comment by aaaapai** [comment]
> Can't even open the video, it just display for a second, then force me to download the app, but the app is not available in my country.
> 
> and why if this option exists? <img alt="image" width="508" src="https://user-images.githubusercontent.com/40482367/143381334-294df7cf-cf53-4abb-805b-31be8343e26c.png">
> 
> Now video doesn't matter, send the log instead.

稍等

**Comment by aaaapai** [comment]
> Can't even open the video, it just display for a second, then force me to download the app, but the app is not available in my country.
> 
> and why if this option exists? <img alt="image" width="508" src="https://user-images.githubusercontent.com/40482367/143381334-294df7cf-cf53-4abb-805b-31be8343e26c.png">
> 
> Now video doesn't matter, send the log instead.

[I'm a video](https://www.laogoupan.com/b32291)

**Comment by aaaapai** [comment]
> 

It crashes directly without logs

**Comment by khanhduytran0** [comment]
> > Can't even open the video, it just display for a second, then force me to download the app, but the app is not available in my country.
> > and why if this option exists? <img alt="image" width="508" src="https://user-images.githubusercontent.com/40482367/143381334-294df7cf-cf53-4abb-805b-31be8343e26c.png">
> > Now video doesn't matter, send the log instead.
> 
> [I'm a video](https://www.laogoupan.com/b32291)

Can you just directly attach here? or github doesn't allow?

**Comment by khanhduytran0** [comment]
> It crashes directly without logs

We're talking about latestlog.txt, not crash log.

**Comment by aaaapai** [comment]
> Can't even open the video, it just display for a second, then force me to download the app, but the app is not available in my country.
> 
> and why if this option exists? <img alt="image" width="508" src="https://user-images.githubusercontent.com/40482367/143381334-294df7cf-cf53-4abb-805b-31be8343e26c.png">
> 
> Now video doesn't matter, send the log instead.

After entering the game, exit, and then enter the game. Go directly through the black screen to the login main interface

> > It crashes directly without logs
> 
> We're talking about latestlog.txt, not crash log.

After entering the game, exit, and then enter the game. Go directly through the black screen to the login main interface

**Comment by aaaapai** [comment]
> > It crashes directly without logs
> 
> We're talking about latestlog.txt, not crash log.

I reinstall Java VMS to enter a game

**Comment by aaaapai** [comment]
> > It crashes directly without logs
> 
> We're talking about latestlog.txt, not crash log.

![d13c66dfd949672aa3614c1cad04a148](https://user-images.githubusercontent.com/89151134/143383147-69c25349-abc1-40c1-a027-efef15698b7a.gif)

**Comment by aaaapai** [comment]
> > It crashes directly without logs
> 
> We're talking about latestlog.txt, not crash log.

![d13c66dfd949672aa3614c1cad04a148_1](https://user-images.githubusercontent.com/89151134/143383481-fe1d5fb8-e0b3-4f49-acbf-6d8ff3c3572c.gif)

**Comment by aaaapai** [comment]
--------- beggining with launcher debugInfo: Launcher version: crocus-228-2ec6c4d18-v3_openjdkInfo: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]Architecture: arm64Info: Custom Java arguments: ""Info: Selected Minecraft version: fabric-loader-0.11.7-1.17.1 (1.17.1)--------- beginning of crash

**Comment by mchnjt** [comment]
ah yes. github on emails. how cringe

**Comment by mchnjt** [comment]
also send it as a file, not copy paste text

**Comment by aaaapai** [comment]
> also send it as a file, not copy paste text

Can you fix it?

**Comment by aaaapai** [comment]
> also send it as a file, not copy paste text

I'm lazy. I'm lazy to send files and copy and paste them directly

**Comment by netkv** [comment]
if you are lazy, devs can be lazy too right?

**Comment by ghost** [comment]
just send the latestlog.txt it's not that hard

**Comment by Mathias-Boulay** [comment]
Your huge unformatted argument doesn't change my statement. *and yes we can't access the video but I'm not surprised there*

**Comment by ghost** [comment]
welp i can watch the video it just you in the main screen of minecraft 1.17 and you just press quit and get in again the PojavLauncher and press play but it takes you to the login screen(i just tell what i saw)

**Comment by aaaapai** [comment]
> just send the latestlog.txt it's not that hard

Next time

**Comment by ghost** [comment]
> > just send the latestlog.txt it's not that hard
> 
> Next time

what? it just send a small file it's not a big deal

**Comment by aaaapai** [comment]
> 

I see. The log will be changed next time

**Comment by ghost** [comment]
why would you play while we trying to help you?

**Comment by artdeell** [comment]
He literally asks for support for modded Pojav bruh

Note the login screen background.

чт, 25 нояб. 2021 г., 12:59 Skyinthesky ***@***.***>:

**Comment by ghost** [comment]
oh ok, my bad

**Comment by netkv** [comment]
> He literally asks for support for modded Pojav bruh Note the login screen background. 

LMAO

**Comment by Mathias-Boulay** [comment]
Well maybe close the issue then
