### ISSUE TITLE
How to fix this please help

### ISSUE THREAD

**Issue by Jonathan192168** [PojavLauncherTeam/PojavLauncher#2276]
### Describe the bug

When I lunch the game and play little bit din this happen please help me 😔😔😔

### The log file and images/videos

![Screenshot_20211124-131623](https://user-images.githubusercontent.com/94950904/143182628-7561878f-1b68-4041-b63f-63a06071115b.png)

### Steps To Reproduce

```markdown
😔😔😔😔😔😔
```

### Expected Behavior

What do I do

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 11
- PojavLauncher version: 1.14.4
```

**Comment by WesleyVanNeck** [comment]
By using gl4es 1.1.4

**Comment by WesleyVanNeck** [comment]
Or vgpu

**Comment by khanhduytran0** [comment]
~~*fake hotbar moment*~~
<img width="100" alt="image" src="https://user-images.githubusercontent.com/40482367/143190485-5ed39fa9-8252-46c7-82fe-860dfb264bbb.png">
