### ISSUE TITLE
[BUG] <Incorrect mouse operation>

### ISSUE THREAD

**Issue by UnexaZ** [PojavLauncherTeam/PojavLauncher#2278]
### Describe the bug

During the game, almost no mouse capture occurs, while everything works fine in the menu and inventory.

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

-

### Platform

```markdown
- Device model: Poco F3
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release version 3.3.1.1_rel_20210206
```

### Anything else?

-

**Comment by andteklin** [comment]
Potentially try making sure in PojavLauncher settings that Disable Gestures is set to the OFF position and that Touchscreen Mode is ON in the in-game Minecraft settings which can be found through Options --> Controls --> Mouse Settings.

**Comment by Mathias-Boulay** [comment]
That's an awfully old version.
No support for this

**Comment by Mathias-Boulay** [comment]
Use the crocus update from gplay or more recent dev builds
