### ISSUE TITLE
[F-Req] Please add "[", "]" and "~" into mappings

### ISSUE THREAD

**Issue by buzzcola3** [PojavLauncherTeam/PojavLauncher#2281]
### Is this request related to a bug?

Some mods have no way to modify control mappings, and require these obscure characters.

[ , ] And ~ are used in morph mod

It would be nice to be able to possibly even use the android keyboard to input button controls

### Describe the request.

Add the characters into mappings

**Comment by Skyinthesky** [comment]
welp we does have [ and ]![Screenshot_2021-11-25-15-49-49-610_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/93042353/143409540-9860dbd6-8489-4fb5-88bf-002ce230556f.jpg)

**Comment by ghost** [comment]
you can change the button with another button in the control setting in minecraft
