### ISSUE TITLE
[BUG] some texture are error/black

### ISSUE THREAD

**Issue by Supeerstone** [PojavLauncherTeam/PojavLauncher#2282]
### Describe the bug

There are new renderer called virglrenderer that make some texture turn into black/error

### Steps To Reproduce

```markdown
1. Open pojav
2. Set renderer into virglrenderer
3. Launch 1.17 - 1.18 snapshot
4. Create a world
5. Open inventory
6. You might relize that some of the texture are black
```

### Expected Behavior

I expect all texture are normal

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: aarch64 
- Android version: 9 
- PojavLauncher version: version crocus 228 2ec6c4d18 v3 openjdk
```

**Comment by Supeerstone** [comment]
feel free to leave a comment about this bug :)

**Comment by ghost** [comment]
welp uh i don't think virgl is released for 1.17+

**Comment by ghost** [comment]
and the PojavLauncher version you told us is not virgl

**Comment by WesleyVanNeck** [comment]
Virgl is Just like zink aka buggy render dont use it

**Comment by WesleyVanNeck** [comment]
Also this is already known by the devs
