### ISSUE TITLE
TLauncher Auth login

### ISSUE THREAD

**Issue by TERMZJosh** [PojavLauncherTeam/PojavLauncher#2283]
### Describe the request.

I want the launcher support tlauncher accounts

### Anything else?

Thats it

**Comment by Mathias-Boulay** [comment]
Let's not do this.

**Comment by dachisao** [comment]
hey let's do that
let's speedrun "getting sued by microsoft"

**Comment by khanhduytran0** [comment]
@ImNathanPlayz 
Perhaps you didn’t know what happened to the iOS version recently. We don’t want to get risk getting DMCA from Microsoft. For this reason, offline account will also be removed **soon**.
![18F61BB2-6E87-4F3C-B8E1-4B46E531B6A6](https://user-images.githubusercontent.com/40482367/143586629-949a12c6-0b31-49da-86ba-cbc363b777c6.jpeg)
![E69965ED-2929-46C4-8CB8-7877D913A147](https://user-images.githubusercontent.com/40482367/143586644-5a3a9c85-58c9-438f-a7ed-03ae19952184.jpeg)

**Comment by mchnjt** [comment]
fix: steal $27 from your parents and buy minecraft

**Comment by mchnjt** [comment]
and delete this repository after no more offline mode

**Comment by ghost** [comment]
we can't use tlauncher accounts in the pay minecraft launcher so how can we do exact thing with PojavLauncher bro
