### ISSUE TITLE
add control buttons like in minecraft bedrock 

### ISSUE THREAD

**Issue by ExtinctDrift19** [PojavLauncherTeam/PojavLauncher#2285]
### Describe the request.

buttons control like in minecraft bedrock the problem of the old control buttons, they are ugly and do not match the style of minecraft. new control buttons from minecraft bedrock match the style of minecraft

**Comment by ghost** [comment]
welp you can edit your own button control and PojavLauncher just make the button control that they think is best to use

**Comment by Mathias-Boulay** [comment]
You can fully edit the style of your buttons and clone them.
