### ISSUE TITLE
[BUG] 1.18 Release Candidate renderer problem

### ISSUE THREAD

**Issue by kl1024** [PojavLauncherTeam/PojavLauncher#2286]
### Describe the bug

Pojavlauncher crashed when joined the world in 1.18-rc3 with gl4es 1.1.5 renderer.

### The log file and images/videos

![Screenshot_20211127-141126483](https://user-images.githubusercontent.com/57281140/143670368-6233cfcf-eb48-4560-a39f-41959ae1618c.jpg)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Start 1.18-rc3
```

### Expected Behavior

I expect to join the world

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ghost** [comment]
i tested and it seems pretty normal(i used zink so yea)![Screenshot_2021-11-27-10-14-13-865_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/93042353/143673425-775eb94c-227d-43ba-a83b-de0337872f0d.jpg)

**Comment by ghost** [comment]
same with 1.18-rc2![Screenshot_2021-11-26-21-02-10-375_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/93042353/143673443-66962a54-164c-4452-a017-9ebdc306f6bf.jpg)

**Comment by kl1024** [comment]
> same with 1.18-rc2![Screenshot_2021-11-26-21-02-10-375_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/93042353/143673443-66962a54-164c-4452-a017-9ebdc306f6bf.jpg)

maybe there's something wrong with my device

**Comment by kl1024** [comment]
> i tested and it seems pretty normal(i used zink so yea)![Screenshot_2021-11-27-10-14-13-865_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/93042353/143673425-775eb94c-227d-43ba-a83b-de0337872f0d.jpg)

Anyway, thank you for replying.
Maybe 1.18-rc3 doesn't support lower version of OpenGL.
1.18-rc3 with virgl is fine,but it has some rendering problems.

**Comment by kl1024** [comment]
> i tested and it seems pretty normal(i used zink so yea)![Screenshot_2021-11-27-10-14-13-865_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/93042353/143673425-775eb94c-227d-43ba-a83b-de0337872f0d.jpg)

Anyway, thank you for replying.
Maybe 1.18-rc3 doesn't support lower version of OpenGL.
1.18-rc3 with virgl is fine,but it has some rendering problems.

**Comment by dachisao** [comment]
remember: virgl is a dumbass
praise zink

**Comment by kl1024** [comment]
> remember: virgl is a dumbass praise zink

so...why there is no zink in GitHub actions version
I think you don't know this either

**Comment by dachisao** [comment]
haha clown 🤡🎪👍
go download old action builds

**Comment by kl1024** [comment]
> haha clown 🤡🎪👍 go download old action builds

maybe u r right dude

**Comment by ghost** [comment]
> > i tested and it seems pretty normal(i used zink so yea)![Screenshot_2021-11-27-10-14-13-865_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/93042353/143673425-775eb94c-227d-43ba-a83b-de0337872f0d.jpg)
> 
> Anyway, thank you for replying.
> Maybe 1.18-rc3 doesn't support lower version of OpenGL.
> 1.18-rc3 with virgl is fine,but it has some rendering problems.
> 

welp i runned 1.18-rc3 with gl4es render but still not crash so it's not because the render

**Comment by ghost** [comment]
> > haha clown 🤡🎪👍 go download old action builds
> 
> maybe u r right dude

welp there's no reply of the PojavLauncher version so i have no idea but i recommend to use PojavLauncher from play store

**Comment by ghost** [comment]
> remember: virgl is a dumbass
> praise zink

that's why the pic of 1.18-rc3 is black

**Comment by kl1024** [comment]
> > > haha clown 🤡🎪👍 go download old action builds
> > 
> > 
> > maybe u r right dude
> 
> welp there's no reply of the PojavLauncher version so i have do idea but i recommend to use PojavLauncher from play store

thank u but accessing to play store is hard in my region

**Comment by ghost** [comment]
> > > > haha clown 🤡🎪👍 go download old action builds
> > > 
> > > 
> > > maybe u r right dude
> > 
> > welp there's no reply of the PojavLauncher version so i have do idea but i recommend to use PojavLauncher from play store
> 
> thank u but accessing to play store is hard in my region

why?
