### ISSUE TITLE
[BUG] Multiplayer Server Can't Resolve Hostname Error

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2288]
### Describe the bug

When Connecting To Multiplayer Server Some Server Error With Can't Resolve Hostname Please Help.

### Steps To Reproduce

```markdown
After Entering Server IP There Is Can't Resolve Hostname Error
```

### Expected Behavior

I Want To Join Server

### Platform

```markdown
- Device model: Realme 7 Pro
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Play Store Version
```

**Comment by ghost** [comment]
i think it's because of the ip server have something wrong and minecraft cant resolve it so it's not PojavLauncher problem

**Comment by ghost** [comment]
I tried same ip on PC and it's working fine that's why i posted this as bug

**Comment by ghost** [comment]
> I tried same ip on PC and it's working fine that's why i posted this as bug

but why would you make issue to us i said that this is not PojavLauncher problem :)

**Comment by ajit850** [comment]
I also have this problem to connect kgo.world

**Comment by ghost** [comment]
> I also have this problem to connect kgo.world

hm i've been this on my computer so im sure it's minercaft problem not PojavLauncher problem

**Comment by ghost** [comment]
welp i have a way to fix you will need a computer, you open cmd and type "nslookup [server ip]" and press enter it will show the ip server and something calls "address" then you copy the numbers and put it in the server ip then the problem should be fixed

**Comment by GoneSubject** [comment]
> welp i have a way to fix you need a computer, you open cmd and type "nslookup <server ip>" and press ender it will show the ip server and something calls "address" then you use it like the server ip

**Comment by Mathias-Boulay** [comment]
duplicate from #1747 , although I believe creating a better resolv.conf file could solve the issue

**Comment by ghost** [comment]
> duplicate from #1747 , although I believe creating a better resolv.conf file could solve the issue

can't resolve host nam and unknow host is diffrent! unknown host is like the ip address doesn't exist and the can't resolve is like minecraft can't figure out what is it but the ip is still exist

**Comment by GoneSubject** [comment]
> > duplicate from #1747 , although I believe creating a better resolv.conf file could solve the issue
> 
> can't resolve host name and unknown host is diffrent! unknown host is like the ip address doesn't exist and the can't resolve is like minecraft can't figure out what is it but the ip is still exist

**Comment by Mathias-Boulay** [comment]
#1987

**Comment by ghost** [comment]
How can I create better resolv.conf file Plz tell i have this from from long time

**Comment by ghost** [comment]
> How can I create better resolv.conf file Plz tell i have this from from long time

find it yourself or just do like this ._,

>welp i have a way to fix you will need a computer, you open cmd and type "nslookup [server ip]" and press enter it will show the ip server and something calls "address" then you copy the numbers and put it in the server ip then the problem should be fixed

**Comment by ghost** [comment]
> #1987 

it still diffriend but ok

**Comment by GoneSubject** [comment]
> > #1987 
> 
> it still diffriend but ok

**Comment by ghost** [comment]
> duplicate from #1747 , although I believe creating a better resolv.conf file could solve the issue

Plz tell me how to create better.config

**Comment by ghost** [comment]
>duplicate from #1747 , although I believe creating a better resolv.conf file could solve the issue

>Plz tell me how to create better.config

i reply it here bro it may fix

> How can I create better resolv.conf file Plz tell i have this from from long time
>it yourself or just do like this ._, 
>i have a way to fix you will need a computer, you open cmd and type \"nslookup [server ip]\" and press enter it will show the ip server and something calls \"address\" then you copy the numbers and put it in the server ip then the problem should be fixed

**Comment by ghost** [comment]
> >duplicate from #1747 , although I believe creating a better resolv.conf file could solve the issue
> 
> >Plz tell me how to create better.config
> 
> i reply it here bro it may fix
> 
> > How can I create better resolv.conf file Plz tell i have this from from long time

> >it yourself or just do like this ._, 

> >i have a way to fix you will need a computer, you open cmd and type \"nslookup [server ip]\" and press enter it will show the ip server and something calls \"address\" then you copy the numbers and put it in the server ip then the problem should be fixed
> 
>

**Comment by ghost** [comment]
I Am getting 4 different ip numbers from this and also words are involved what to do?

**Comment by NotAHero04** [comment]
@GoneSubject I don't think it will work
![Screenshot_20211128-110211](https://user-images.githubusercontent.com/84689840/143729076-6aa7a856-a521-4a72-8520-ddced417cf36.png)
This is a server that suffers this kind of issue with PojavLauncher. I tried the **direct** IP which can be obtained from the launcher log, still no hope.

**Comment by ghost** [comment]
> @GoneSubject I don't think it will work
> ![Screenshot_20211128-110211](https://user-images.githubusercontent.com/84689840/143729076-6aa7a856-a521-4a72-8520-ddced417cf36.png)
> This is a server that suffers this kind of issue with PojavLauncher. I tried the **direct** IP which can be obtained from the launcher log, still no hope.

you copied the address line?

**Comment by NotAHero04** [comment]
yep

**Comment by NotAHero04** [comment]
Also tried the IPs above, and what I received is a connect failure simulator.

**Comment by ghost** [comment]
> yep

welp still have another way

**Comment by ghost** [comment]
Plz tell any way if you know

**Comment by NotAHero04** [comment]
Uhh... What is the Minecraft server address again?

**Comment by mchnjt** [comment]
> Plz tell any way if you know

If the server has a plugin called "GeyserMC", you can try joining via bedrock.

**Comment by ghost** [comment]
welp um the another way that i know is type the address server with it's port, the dafault port is 25565 so you can try that

**Comment by ghost** [comment]
Server has geyser mc plugin but I don't like to play in pe

**Comment by NotAHero04** [comment]
@Aryan1084 Give me the IP of your Minecraft server bruh

**Comment by ghost** [comment]
> @Aryan1084 Give me the IP of your Minecraft server bruh

yea

**Comment by ghost** [comment]
Ip- play.adispot.xyz or hyperion-mc.net

**Comment by ghost** [comment]
> Ip- play.adispot.xyz or hyperion-mc.net

with hyperion you will type in the server ip is:
hyperion-mc.net:19333
i have no idea with adispot

**Comment by ghost** [comment]
Adispot and Hyperion are same servers with multiple ip address

**Comment by ghost** [comment]
I am trying thanks for help

**Comment by ghost** [comment]
It's not working brother sad

**Comment by ghost** [comment]
._,

**Comment by ajit850** [comment]
kgo.world can't connect

**Comment by ghost** [comment]
> kgo.world can't connect

can you join normally and see what it said so we can help

**Comment by ajit850** [comment]
![Screenshot_20211128-132259_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/79654338/143734440-2eaab3a4-605c-4de5-90a4-c74e2c8f264d.jpg)

**Comment by ghost** [comment]
> ![Screenshot_20211128-132259_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/79654338/143734440-2eaab3a4-605c-4de5-90a4-c74e2c8f264d.jpg)

the server doesn't exist i think

**Comment by ajit850** [comment]
But search on Google kgo Minecraft server it shows that this is exist

**Comment by ghost** [comment]
> But search on Google kgo Minecraft server it shows that this is exist

hmmm idk
