### ISSUE TITLE
[BUG] 1.17 it's not working 

### ISSUE THREAD

**Issue by PVPlunar1** [PojavLauncherTeam/PojavLauncher#2289]
### Describe the bug

When I click on play at 1.17 there saying game exited

### The log file and images/videos

#1912 
![Screenshot_2021-11-27-20-55-40-230_net kdt pojavlaunch](https://user-images.githubusercontent.com/95146644/143720569-82a9ed7c-cc1a-4dd9-b9c4-dedc5f5aef2a.jpg)

### Steps To Reproduce

```markdown
Click on version 1.17
Click play
Ure game exited
```

### Expected Behavior

I expect U help me

### Platform

```markdown
- Device model: Redmi note 9 64gb/3ram
- CPU architecture: 64
- Android version: minui 12
- PojavLauncher version: 1.17
```

### Anything else?

Help me!!!!! PLS just send me a help

**Comment by ghost** [comment]
did you follow [this](https://pojavlauncherteam.github.io/updates/117.html) to play 1.17?

**Comment by ghost** [comment]
and the infos you tell us is not like we needed

**Comment by PVPlunar1** [comment]
Like what

**Comment by PVPlunar1** [comment]
I got my runtime for 1.17 and when I join the game there saying game exited

**Comment by ghost** [comment]
> I got my runtime for 1.17 and when I join the game there saying game exited

welp send the logs
find it in sd card/Android/data/ndk.kdt.pojavlaunch/files or sd card/games/PojavLauncher there must be a file call "latestlog.txt" send it here

**Comment by Mathias-Boulay** [comment]
Lmao miui 12 is like 3 to 4 different android versions

**Comment by ghost** [comment]
> Lmao miui 12 is like 3 to 4 different android versions

I'm android 10 and good with it ._, (going to update to android 11)

**Comment by NotAHero04** [comment]
1.17 is not a valid PojavLauncher version. We recommend you to update to the latest PojavLauncher build (either GitHub or Play Store) to get better support.

**Comment by ghost** [comment]
> 1.17 is not a valid PojavLauncher version. We recommend you to update to the latest PojavLauncher build (either GitHub or Play Store) to get better support.

recommend play store cuz im very normal with it(last time crashed like months ago)

**Comment by khanhduytran0** [comment]
Still no log provided. Closing until further response.
