### ISSUE TITLE
[BUG] <Can't find mod in games>

### ISSUE THREAD

**Issue by HenryChoiLKSC** [PojavLauncherTeam/PojavLauncher#2290]
### Describe the bug

I think it's because I had installed minecraft PE before

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.install all file explorer and find pojavlauncher flie
3.failed
```

### Expected Behavior

I think that minecraft pe file was covered the pojavlauncher file

### Platform

```markdown
- Device model: Samsung galaxy A70
- CPU architecture: Qualcomm snapdragon 675
- Android version: android 11
- PojavLauncher version: newest ver.
```

**Comment by ghost** [comment]
PojavLauncher files can be find in:
 sd card/Android/data/net.kdt.pojavlaunch(debug)/files 
or
sd card/games/PojavLauncher

**Comment by Mathias-Boulay** [comment]
The answer has been given, closing the issue

**Comment by HenryChoiLKSC** [comment]
Thanks, This help me a lot!

「Boulay Mathias ***@***.***>」在 2021年11月28日 週日，下午5:20 寫道：
