### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#2293]
### Is this request related to a bug?

1.17 and above version lags with virgl

### Describe the request.

Make some less lag

**Comment by ghost** [comment]
welp virgl is sucks use gl4es 1.1.5

**Comment by ajit850** [comment]
Ok

**Comment by ajit850** [comment]
I can't connect to kgo.world server it says unknown host

**Comment by ajit850** [comment]
In Version 3.3.1.1 it works

**Comment by ghost** [comment]
> In Version 3.3.1.1 it works

so use it then, that's the latest version btw

**Comment by ajit850** [comment]
But this is old version

**Comment by ghost** [comment]
> But this is old version

oh

**Comment by ghost** [comment]
welp accept the risk

**Comment by Mathias-Boulay** [comment]
Virgl is experimental
And we don't develop mesa
