### ISSUE TITLE
Topicraft

### ISSUE THREAD

**Issue by zzasami** [PojavLauncherTeam/PojavLauncher#2295]
### Describe the bug

Haide pe topicraft
 Ffcfcdccf

### The log file and images/videos

 Dvd cd cc

### Steps To Reproduce

```markdown
D ed e d.
```

### Expected Behavior

 C cf. C f

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
1.17.1
```

### Anything else?

Dfdfdcdcdcc

**Comment by zzasami** [comment]
fcfffdtbdtbftbfdb@mail.com

**Comment by ajit850** [comment]
What is topicraft

**Comment by ghost** [comment]
is this a language?

**Comment by Mathias-Boulay** [comment]
spam reported

**Comment by ghost** [comment]
._,
