### ISSUE TITLE
[BUG] Pojav Launcher can't resolve my server's hostname

### ISSUE THREAD

**Issue by CreeperboyMCVN** [PojavLauncherTeam/PojavLauncher#2296]
### Describe the bug

I have a server with IP address mineviet.com. When I use the PC version of Minecraft, I access that server normally. But on PojavLauncher it cannot resolve hostname, please help me.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login and do blah blah...
3. Go to Multiplayer and enter server's IP address
4. Can't reslove host name
```

### Expected Behavior

I expect it to connect to the server

### Platform

```markdown
- Device model: VSmart Joy 3 4GB RAM/64GB ROM
- CPU architecture: Snapdragon 632
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by ghost** [comment]
a

**Comment by ghost** [comment]
duplicate from #2288

**Comment by Mathias-Boulay** [comment]
duplicate, closing.
Polluting with duplicate issues only slows down development
