### ISSUE TITLE
Optifine 1.13.2 Other Crash

### ISSUE THREAD

**Issue by MassiveBeefJrky** [PojavLauncherTeam/PojavLauncher#2297]
### Describe the bug

I am using the optifine 1.13.2 version on a Chromebook that handles the game very well, however, when I press other on video settings, it crashes the game, I have no coding experience, but I know one thing, ya'll are doing a mighty fine job for this launcher.

### Steps To Reproduce

```markdown
1. Use optifine 1.13.2
2. Go to Video Settings
3. Click other
4. Game crash
```

### Expected Behavior

I expected it to go into other video settings to enable fps count.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ghost** [comment]
so can you join your world?

**Comment by artdeell** [comment]
No log, no platform info.

**Comment by ghost** [comment]
> No log, no platform info.

i see ._,

**Comment by NotAHero04** [comment]
Known issue at the moment.

**Comment by ghost** [comment]
hm

**Comment by NotAHero04** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7616012/latestlog.txt)
This is the error log I produced.

**Comment by ghost** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7616012/latestlog.txt) This is the error log I produced.

cool

**Comment by ghost** [comment]
is it ok if we use java 17 on that?

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
