### ISSUE TITLE
My Launcher Always Crashing When Play Online

### ISSUE THREAD

**Issue by SimpleMinecraftPlayer** [PojavLauncherTeam/PojavLauncher#2298]
### Describe the bug

I just Play PojavLauncher and i play a multiplayer server 10 minutes after that my Launcher crashed
Im Using google play version

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7616665/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Login With Online Account
3.Playing 1.8.8 Multiplayer Server
4.10 Minutes Playing And My Launcher Crashed
```

### Expected Behavior

Crashed everytime playing

### Platform

```markdown
- Device model:Redmi Note 9 6/128G 
- CPU architecture:aarch64
- Android version:10 
- PojavLauncher version:crocus v3 openjdk
```

**Comment by ghost** [comment]
the JVM launch argument should be empty

**Comment by SimpleMinecraftPlayer** [comment]
No i just filling it

**Comment by SimpleMinecraftPlayer** [comment]
GoneSubject Jvm launch argument code pls
Original

**Comment by ghost** [comment]
> GoneSubject Jvm launch argument code pls Original

just delete all the things in there you don't need to fill the JVM launch argument

**Comment by SimpleMinecraftPlayer** [comment]
Ok thanks
