### ISSUE TITLE
[BUG] Can't Resolve Hostname But Same IP Works On PC

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2299]
### Describe the bug

Can't Resolve Hostname Problem On Pojav Launcher As The Same IP Works On PC 

And Please Don't Close This Bug As This Duplicate Give Solution First You Are Only Closing These Reports As Duplicate But Didn't Give Solution

Server IP- play.adispot.xyz OR Hyperion-mc.net

### Steps To Reproduce

```markdown
Can't Resolve Hostname After Entering IP
```

### Expected Behavior

IP Should Work

### Platform

```markdown
- Device model: Realme 7 Pro
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Google Play Release
```

**Comment by ghost** [comment]
another duplicate from #2288

**Comment by ghost** [comment]
First Give Solution Of It Then Say It Duplicate

**Comment by ghost** [comment]
Never Got Solution Of This Problem Therefore All Are Duplicating This Problem

**Comment by ghost** [comment]
> Never Got Solution Of This Problem Therefore All Are Duplicating This Problem

just watch in the #2288 i tagged it in bro

**Comment by khanhduytran0** [comment]
> First Give Solution Of It Then Say It Duplicate

And why would you duplicate issues? It’s like polluting the issue tracker.

**Comment by khanhduytran0** [comment]
Also, your phone is definitely not a windows PC.

**Comment by khanhduytran0** [comment]
Some servers decline connect from Linux/Mac clients, therefore only windows client can connect to.

**Comment by ghost** [comment]
yea ._,

**Comment by Mathias-Boulay** [comment]
If we had the solution it would be deployed.
Case and point.
