### ISSUE TITLE
What will happen to PojavLauncher v3?

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#23]
WARNING: there are too many "and"!

Questions:
Will the third version ever be available?
And what will be in the next updates?
And one more thing!
I have android 9 and I can't play version larger than 1.7.10. Will this be fixed? and will version 1.12.2 ever work?

**Comment by khanhduytran0** [comment]
> ### Will the third version ever be available?
Not because v3 must something very big changes like Boardwalk 2.

> ### **And** what will be in the next updates?
In 2.4.2 already add many features, cause I ran out of idea, so next updates will fix bugs.

> ### **And** one more thing! I have android 9 and I can't play version larger than 1.7.10. Will this be fixed?

Can you copy error log?

> ### **and** will version 1.12.2 ever work?

1.12 or above will not work **and** not yet planned for that.

**Comment by Azapru** [comment]
Versions larger than 1.7.10 now works!
