### ISSUE TITLE
controlmap/default.json missing

### ISSUE THREAD

**Issue by domkab16** [PojavLauncherTeam/PojavLauncher#230]
When launching it crashes saying that .Minecraft/controlmap/default.jsom is missing. I created a empty file in that path with the right name, it still crashes giving a null object reference, I'm assuming it because it's empty. Have attached screenshot
![Screenshot_20200609-013503](https://user-images.githubusercontent.com/48944532/84037127-3f747d00-a9f2-11ea-82a6-7e863fea0651.jpg)

**Comment by khanhduytran0** [comment]
You need go to Options -> Custom controls. This will generate a default control json.

**Comment by khanhduytran0** [comment]
Then you may start again.
