### ISSUE TITLE
[BUG][fixed]optifine G9 1.17.1 texture bug

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2301]
### Describe the bug

When I load a world it's textures doesn't  load

### The log file and images
![Screenshot_20211129-211255_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/95124798/143898599-b173a8f4-f891-4443-ba5b-c1f736ddb99c.jpg)

### Steps To Reproduce

```markdown
2. Create a world in 1.17.1 optifine
3. blank texture's
```

### Expected Behavior

I expected  it to be loaded with textures

### Platform

```markdown
- Device model: Samsung galaxy tab a
- CPU architecture: armv8l
- Android version: 11
- PojavLauncher version: latest?
- ram: 2gb
- allocated ram: 600 mb
```

### Anything else?

I need the fix so I can continue  my survival world

**Comment by ghost** [comment]
did you fill anything in the JVM launch argument?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
-Xms800m -Xmx1300m

**Comment by ghost** [comment]
Ummmmm can problem be solved?

**Comment by ghost** [comment]
> Ummmmm can problem be solved?

yes remove everything in the JVM launch argument

**Comment by ghost** [comment]
Empty?

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
and send logs in the next time not the crash log, found it in 
sd card/Android/net.kdt.pojavlaunch(debug) or sd card/games/PojavLauncher and there will be a file call "latestlog.txt"

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
I'll try now

**Comment by ghost** [comment]
_Game exited <crashed> here's the latest log_
_[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7618522/latestlog.txt)_

**Comment by ghost** [comment]
> _Game exited <crashed> here's the latest log_
> _[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7618522/latestlog.txt)_
> 

did you used the patch from duy?

**Comment by ghost** [comment]
Nope

**Comment by ghost** [comment]
[here](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa2xZblVUdk5hMWFoQzBobnRNUWd4Qld3bVVLd3xBQ3Jtc0tsRS1RVUxwZFBaYU1fTmhFdjA2SkxCcEMzbzl1ZkRuM25sQktQWENIbEJhdXdiWlJWbXlCNVlOYzNja2s2S0tqeEpFa0RqbnVlakVUa3pmLWgyV0pmc2NmejY5OXdvbTByaHRjdHNncm9jU21pd2I0aw&q=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F724163890803638277%2F888992640819925032%2FPojavOF117AssetsPatcher.jar&v=acgJSgzVZyw&html_redirect=1) if you didn't download it and use it like a mod installer to patch the version

**Comment by ghost** [comment]
I installed Java 17

**Comment by ghost** [comment]
Ok?

**Comment by ghost** [comment]
Do I have to install it like optifine installation?

**Comment by ghost** [comment]
> Do I have to install it like optifine installation? 

yes

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
Directly over optifine version?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
It game exited

**Comment by ghost** [comment]
just use it like a mod installer bro

**Comment by ghost** [comment]
> It game exited

use java 8 when using it

**Comment by ghost** [comment]
I used it as a mod installer

**Comment by ghost** [comment]
-_-

**Comment by ghost** [comment]
> I used it as a mod installer 

use java 8

**Comment by ghost** [comment]
Ohhhjava 8

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
_it works closing this issue_

**Comment by ghost** [comment]
> _it works closing this issue_

good happy to help ._,

**Comment by ghost** [comment]
Ummmm crash on villager seed lol 
Minecraft  version  1.17.1 optifine
Latest log: 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7619211/latestlog.txt)
And I accidentally deleted  latestlog and I copy latestlog before I upload. Hope _this is correct `latestlog`_

And I have smooth lighting  on too ill trun it off and try again

**Comment by ghost** [comment]
I forgot to mention the old bug. The mouse sometimes cannot click buttons

**Comment by ghost** [comment]
> Ummmm crash on villager seed lol 
> Minecraft  version  1.17.1 optifine
> Latest log: 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7619211/latestlog.txt)
> And I accidentally deleted  latestlog and I copy latestlog before I upload. Hope _this is correct `latestlog`_
> 
> And I have smooth lighting  on too ill trun it off and try again

hmm

**Comment by ghost** [comment]
it's my bedtime sorry bye

**Comment by ghost** [comment]
NEW BUG
_and pls don't care about the upper text_

**Comment by ghost** [comment]
>  NEW BUG
> _and pls don't care about the upper text_

what is it?

**Comment by mchnjt** [comment]
> ### Describe the bug
> When I load a world it's textures doesn't load
> 
> ### The log file and images
> ![Screenshot_20211129-211255_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/95124798/143898599-b173a8f4-f891-4443-ba5b-c1f736ddb99c.jpg)
> 
> ### Steps To Reproduce
> ```gfm
> 2. Create a world in 1.17.1 optifine
> 3. blank texture's
> ```
> 
> ### Expected Behavior
> I expected it to be loaded with textures
> 
> ### Platform
> ```gfm
> - Device model: Samsung galaxy tab a
> - CPU architecture: armv8l
> - Android version: 11
> - PojavLauncher version: latest?
> - ram: 2gb
> - allocated ram: 600 mb
> ```
> 
> ### Anything else?
> I need the fix so I can continue my survival world

1. `latest???` isn't a version
2. omg can't wait world loading/rendering textures
3. omg you didn't tell us your renderer

**Comment by ghost** [comment]
yea i answered in there

**Comment by ghost** [comment]
Lol wth is going onnn

**Comment by ghost** [comment]
idk ._,
