### ISSUE TITLE
[BUG] blank textures 1.17.1

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2302]
### Describe the bug

The textures is blank

### The log file and images/videos

![Screenshot_20211129-211255_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/95124798/143902825-9b1a00a5-58b0-49b0-a097-2e19eb789abb.jpg)

### Steps To Reproduce

```markdown
2.create new world
```

### Expected Behavior

I expected to load with textures

### Platform

```markdown
- Device model: galaxy tab a
- CPU architecture: armv8l 
- Android version: 11
- PojavLauncher version: latest ?
```

### Anything else?

I want to get this bug fixed

**Comment by ghost** [comment]
@khanhduytran0  what is this blank

**Comment by ghost** [comment]
Help

**Comment by GoneSubject** [comment]
first that you haven't turn the fast render on

**Comment by ghost** [comment]
> Help

first that make sure the fast render has been turned off

**Comment by ROBLOXstudioDev** [comment]
What? Send screenshot

**Comment by ghost** [comment]
_do you mean optifine fast renderer?_

**Comment by ghost** [comment]
> _do you mean optifine fast renderer?_

yes in options/video settings/perfomance and there will be fast render option turn it off

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
I turned  it off and when I load my world it crashed
And renderer is `gl4es 1.1.5 + partial 3.2`
And runtime is `java 17`

**Comment by ghost** [comment]
hmm send log

**Comment by ghost** [comment]
let me ask for help

**Comment by ghost** [comment]
_can I send a screenshot of my performance settings?_  here's my settings
![Screenshot_20211130-085318_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/95124798/143980197-cd1846f9-59fd-4b4c-a69d-06ae247de6e2.jpg)

**Comment by ghost** [comment]
Ok loggg

**Comment by ghost** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7622684/latestlog.txt)

**Comment by ghost** [comment]
pictures and videos never help

> _can I send a screenshot of my performance settings?_ here's my settings ![Screenshot_20211130-085318_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/95124798/143980197-cd1846f9-59fd-4b4c-a69d-06ae247de6e2.jpg)

**Comment by ghost** [comment]
oh wait

**Comment by ghost** [comment]
i know the problemn here

**Comment by ghost** [comment]
I have send  latestlog above

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
turn off the render region

**Comment by ghost** [comment]
What is problem

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
you must turn off the render region

**Comment by NotAHero04** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7622684/latestlog.txt)

Bruh this is not your gameplay

**Comment by ghost** [comment]
It works and I have a update and enhancement for you
Update is MINECRAFT 1.18 PART II RELEASED and lol this bug fixed
Enhancement is can you add option that changes where latestlog saves
Edit: does release 1.18 work?

**Comment by ghost** [comment]
> It works and I have a update and enhancement for you Update is MINECRAFT 1.18 PART II RELEASED and lol this bug fixed Enhancement is can you add option that changes where latestlog saves Edit: does 1.18 work?

yes it works

**Comment by ghost** [comment]
we got the things to play 1.18 like weeks ago

**Comment by ghost** [comment]
I meant release  1.18 bruh
I'll continue  my world  now and thanks

**Comment by ghost** [comment]
> I meant release 1.18 bruh I'll continue my world now and thanks

1.18 will release today

**Comment by ghost** [comment]
Yea

**Comment by ghost** [comment]
Is version  automatically appear in selection when it released?

**Comment by ghost** [comment]
> Is version automatically appear in selection when it released?
yes of course

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
Does 1.18 requires  to update jre runtime

**Comment by ghost** [comment]
nah

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
just use java 17 it the latest

**Comment by ghost** [comment]
and get the assets-v0 type 2

**Comment by GoneSubject** [comment]
and join duyism fortress for Hung's voice :)

**Comment by ghost** [comment]
And I have a cool feature that needs to be quickly released for me bc in my file manager if I go to sdcard/android/data it appears  as blank :( I have to download  an 3rd party file manager to get latestlog.txt  :(

**Comment by ghost** [comment]
welp accept the risk

**Comment by ghost** [comment]
Can you add a option  to change where latestlog is saved? And give the build of it or release  it.

**Comment by ghost** [comment]
hm welp because the thingy(i forgot) updated so the file changed for android 10+

**Comment by ghost** [comment]
> Can you add a option to change where latestlog is saved? And give the build of it or release it.

and no

**Comment by ghost** [comment]
Im android 11

**Comment by ghost** [comment]
Ok fine

**Comment by GoneSubject** [comment]
join duyism fortress

**Comment by ghost** [comment]
What

**Comment by ghost** [comment]
What is server ip

**Comment by ghost** [comment]
welp nvm

**Comment by ghost** [comment]
Is this issue a discord when closed lol

**Comment by ghost** [comment]
forgot what i said

**Comment by ghost** [comment]
> Is this issue a discord when closed lol

**Comment by ghost** [comment]
> > Is this issue a discord when closed lol

wdym

**Comment by ghost** [comment]
This issue chat is like chatting on discord

**Comment by ghost** [comment]
> This issue chat is like chatting on discord

welp yea it got 52 comments now

**Comment by ghost** [comment]
###now 53

**Comment by ghost** [comment]
join PojavLauncher server btw you can get help in there and chat

**Comment by ghost** [comment]
And in github or minecraft  java

**Comment by ghost** [comment]
https://discord.gg/6RpEJda

**Comment by ghost** [comment]
here PojavLauncher discord server

**Comment by ghost** [comment]
I'm 9 years

**Comment by ghost** [comment]
oh.. then don't join

**Comment by ghost** [comment]
Discord = 13+

**Comment by ghost** [comment]
yea ik

**Comment by ghost** [comment]
Do you have a mincraft 1.17.1 server?

**Comment by ghost** [comment]
> Do you have a mincraft 1.17.1 server?

no

**Comment by ghost** [comment]
find it yourself

**Comment by ghost** [comment]
I have a 1.12.2 server

**Comment by ghost** [comment]
Ip is...

**Comment by ghost** [comment]
TheCube4x49999server.aternos.me

**Comment by ghost** [comment]
I'll start the server if you want to join

**Comment by ghost** [comment]
Can you join pls

**Comment by ghost** [comment]
welp i don't have time sorry

**Comment by ghost** [comment]
i need to go btw

**Comment by ghost** [comment]
Ok bye

**Comment by ghost** [comment]
I'll be on my server

**Comment by ghost** [comment]
And server is cracked

**Comment by ghost** [comment]
https://discord.gg/Neqs3ekfZu

**Comment by ghost** [comment]
here's a server join it

**Comment by ghost** [comment]
I'm 9 years

**Comment by ghost** [comment]
I mean I have a minecraft  serevr

**Comment by ghost** [comment]
> I mean I have a minecraft serevr

i just send the discord link you can join

**Comment by ghost** [comment]
> > I mean I have a minecraft serevr
> 
> i just send the discord link you can join

I'm 9 years -_-

**Comment by ghost** [comment]
nvm then

**Comment by ghost** [comment]
i'll gone bye

**Comment by ghost** [comment]
Can you join my 1.12.2 server?

**Comment by ghost** [comment]
Oh bye

**Comment by ghost** [comment]
> i'll gone bye

> > > > > >Where you gone 
```markdown 
 if you have time then
1. Open pojavlauncher 
2. launch 1.12.2
3. Click multiplayer
4. click add server
5. type "TheCube4x49999server.aternos.me" in ip section
6. click add server
7. Click play on thecube4x4999server
8. You successfully joined my server
```

**Comment by ghost** [comment]
> > i'll gone bye
> 
> > > > > > > Where you gone
> 
> ```gfm
>  if you have time then
> 1. Open pojavlauncher 
> 2. launch 1.12.2
> 3. Click multiplayer
> 4. click add server
> 5. type "TheCube4x49999server.aternos.me" in ip section
> 6. click add server
> 7. Click play on thecube4x4999server
> 8. You successfully joined my server
> ```

**Comment by ROBLOXstudioDev** [comment]
86 comments WE ARE NEAR TO 100 AND THIS ISSUE HAS THE RECORD COMMENTS

**Comment by ghost** [comment]
Hello  -_- @GoneSubject

**Comment by ghost** [comment]
> Hello -_- @GoneSubject

?

**Comment by ghost** [comment]
can we don't chat in here?

**Comment by ghost** [comment]
Where u gone

**Comment by ghost** [comment]
> i'll gone bye

**Comment by ghost** [comment]
So where we chat

**Comment by ghost** [comment]
idk

**Comment by ghost** [comment]
Hello

**Comment by ghost** [comment]
im just helping

**Comment by ghost** [comment]
so i dont have time to chat with you ok?

**Comment by ghost** [comment]
Oh when u have time?

**Comment by ghost** [comment]
and this is github not discord or something

**Comment by ghost** [comment]
And I opened a issue again -_-

**Comment by ghost** [comment]
Issue is enhancement

**Comment by ghost** [comment]
> Issue is enhancement

yea i see that

**Comment by ghost** [comment]
Do comment  in there to confirm

**Comment by ghost** [comment]
wdym?

**Comment by ghost** [comment]
Comment I'm my new issue

**Comment by ghost** [comment]
I mean enhancement
