### ISSUE TITLE
[BUG] Compiled jre 17 for aarch32 cannot find libjli.so

### ISSUE THREAD

**Issue by BXXD101** [PojavLauncherTeam/PojavLauncher#2303]
### Describe the bug

This may not be directly related to the app but using the precompiled jre 17 binaries from CI for aarch32 gives an error that it cannot find libjli.so.

This error doesn't happen when using aarch64 binaries

LD_LIBRARY_PATH is set.

### Steps To Reproduce

```markdown
cd /bin
chmod +x java
./java
```

### Expected Behavior

Binary should load fine and be able to find shared libs with path set.

### Platform

```markdown
- Device model: Pixel 3a
- CPU architecture: armv7
- Android version: 8
- PojavLauncher version: 3.3.1.1
```

### Anything else?

i had to ask here because i could not find any other places for solution and i think it is an issue with compiling

**Comment by artdeell** [comment]
Android linker does not support LD_LIBRARY_PATH, try to set JAVA_HOME instead

**Comment by BXXD101** [comment]
> Android linker does not support LD_LIBRARY_PATH, try to set JAVA_HOME instead

Thank you
