### ISSUE TITLE
[F-Req]  change where latestlog would be saved

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2304]
### Describe the request.

I think a option which let's us to choose where the latestlog will be saved
.
1.button named reset location 
2. Button named choose location 
```markdown 
Reset location Button function is to reset location of the latest log
```
```markdown
Choose  location Button will be used to choose where the latest log will be saves
```

### Anything else?

Problem  is with current latestlog saves system that I'm android  11 and I can't access the latestlog. So this button will be usefull

**Comment by ghost** [comment]
@GoneSubject

**Comment by khanhduytran0** [comment]
> Problem is with current latestlog saves system that I'm android 11 and I can't access the latestlog.

That's the reason why even the game directory can't be changed. Please properly follow this video for how to access it.

https://user-images.githubusercontent.com/40482367/144009358-338a3791-d6e5-469c-a092-70a341731265.mp4

**Comment by ghost** [comment]
ah thanks duy

**Comment by ghost** [comment]
Ohhhhh
