### ISSUE TITLE
[BUG] Release 1.18 does not start 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2306]
### Describe the bug

When running 1.18 on any of the renders, the game crashes and gives an error: code -1 or render overlay (java 17 selected and a special resource pack included other resource packs are missing) 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7627343/latestlog.txt)

### Steps To Reproduce

```markdown
1. Launched by Pojavlauncher
2. Enabled java 17 
3. I chose the zink render (tried to run on other renders) 
4.Selected from the list of versions minecraft 1.18 release 
5. Launched the game 
6. Game crashed
```

### Expected Behavior

I was expecting the game to start 

### Platform

```markdown
- Device model: honor 9c 4/64
- CPU architecture: aarch 64 
- Android version: 10 
- PojavLauncher version: latest release
```

### Anything else?

No

**Comment by Mathias-Boulay** [comment]
Latest release is not a version, but I'm surprised zink isn't up to the task here

**Comment by Ilhamghd** [comment]
Me too

**Comment by Moonlight045** [comment]
Same

**Comment by GoneSubject** [comment]
![Screenshot_2021-12-01-05-58-05-959_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/95298052/144141642-62e01525-87de-4bd1-98da-4eb3277a677e.jpg) ._,

**Comment by GoneSubject** [comment]
it just working normally

**Comment by GoneSubject** [comment]
welp there's a thing that will help you play 1.18 normal with any render(except gl4es 1.1.4 and 1.1.5(open gl 3) and sometimes can crash if you see the warn) but you didn't know to to do that

**Comment by ghost** [comment]
Yea 1.18 work with zink/java17.
I tried it now it was laggy but worked

**Comment by GoneSubject** [comment]
> Yea 1.18 work with zink/java17. I tried it now it was laggy but worked

you must use java 17 to play 1.18 and it's work with gl4es

**Comment by pozhiloy-enotik** [comment]
You can use this instruction to get it working https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04

**Comment by LolexIsALazyPotato** [comment]
I mean like sure 1.17.1 will start but 1.18 still crashes.

**Comment by GoneSubject** [comment]
> I mean like sure 1.17.1 will start but 1.18 still crashes.

send the log

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build

**Comment by ghost** [comment]
> Fixed with the release candidate build

Link ?
