### ISSUE TITLE
[BUG] 1.18 is not working

### ISSUE THREAD

**Issue by Andre643** [PojavLauncherTeam/PojavLauncher#2307]
### Describe the bug

The Game Altomatically closes

Error -1

### The log file and images/videos

![Screenshot_20211130-133415_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/93351407/144094323-2c110841-be83-4f41-9d43-baf6486ad8bd.jpg)

https://user-images.githubusercontent.com/93351407/144097137-4d17bf0d-646d-4d6e-b2b5-a963c5ca0945.mp4

### Steps To Reproduce

```markdown
1-First Download A 1.18

2-Second Enter 1.18

3-Now wait a while

4-That's it, you made the bug.
```

### Expected Behavior

Tried To Play In Version 1.18.

### Platform

```markdown
- Device model: SM-A207M (a20sub)
- CPU architecture: 8x ARM Cortex-A53 @ 1,80 GHz
- Android version: 11
- PojavLauncher version: Crocus-v3_openjdk
```

### Anything else?

When I enter the app and select 1.18 it crashes on the loading bar

**Comment by WesleyVanNeck** [comment]
known issue

**Comment by InfiniXDerg** [comment]
Buy a new phone for Vulkan

**Comment by Mathias-Boulay** [comment]
Thanks for the video but the release is really old and the bug is known and duplicate.
