### ISSUE TITLE
[BUG] <Short description>My game keep saying game erorr exist -1 on 1.18 i even using jre 17 and zink

### ISSUE THREAD

**Issue by Agamer10290** [PojavLauncherTeam/PojavLauncher#2314]
### Describe the bug

My game keep saying game erorr exist -1 on 1.18 i even using jre 17 and zink can u guys plz give me link of pojav and jre using if u can play on 1.18 thx

### The log file and images/videos

My game keep saying game erorr exist -1 on 1.18 i even using jre 17 and zink can u guys plz give me link of pojav and jre using if u can play on 1.18 thx

### Steps To Reproduce

```markdown
My game keep saying game erorr exist -1 on 1.18 i even using jre 17 and zink can u guys plz give me link of pojav and jre using if u can play on 1.18 thx
```

### Expected Behavior

My game keep saying game erorr exist -1 on 1.18 i even using jre 17 and zink can u guys plz give me link of pojav and jre using if u can play on 1.18 thx

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

My game keep saying game erorr exist -1 on 1.18 i even using jre 17 and zink can u guys plz give me link of pojav and jre using if u can play on 1.18 thx

**Comment by GoneSubject** [comment]
no latestlog and platform info

**Comment by GoneSubject** [comment]
and keep said 1 thing in the whole issue

**Comment by GoneSubject1** [comment]
but did you used the the right assets-v0.zip?

**Comment by GoneSubject** [comment]
can you send log?

**Comment by ghost** [comment]
Same here

**Comment by GoneSubject1** [comment]
dude send the log

**Comment by GoneSubject** [comment]
send log or no support

**Comment by GoneSubject** [comment]
here's where to find it if you don't know:
> latestlog.txt can be found in sd card/Android/data/net.ndt.pojavlaunch(debug)/files or sd card/games/PojavLauncher and there must have a file call "latestlog.txt"

**Comment by Agamer10290** [comment]
How shoul i send log im new here 😂

**Comment by dachisao** [comment]
https://user-images.githubusercontent.com/87068881/144230835-b66e6a80-fab8-47e5-b470-00fa1ccbb4dc.mp4

**Comment by GoneSubject** [comment]
> How shoul i send log im new here 😂

._,

**Comment by GoneSubject** [comment]
and now this person close this issue? bruh

**Comment by GoneSubject** [comment]
> 
> https://user-images.githubusercontent.com/87068881/144230835-b66e6a80-fab8-47e5-b470-00fa1ccbb4dc.mp4
> 
> 

thanks too btw
