### ISSUE TITLE
How to download mantle on chromebook

### ISSUE THREAD

**Issue by MassiveBeefJrky** [PojavLauncherTeam/PojavLauncher#2317]
### Is this request related to a bug?

Is there possibly a way, to download mantle onto a Chromebook, the problem is that Chromebook being the horrible os that it is, it cannot run .exe files. Is there a way to run the mantle setup?

### Describe the request.

Someway to run mantle setup

**Comment by khanhduytran0** [comment]
Chromebook doesn’t run Windows. Alternatively, if your chromebook is x86, use [CrossOver](https://play.google.com/store/apps/details?id=com.codeweavers.cxoffice). But then how do you launch the game? PojavLauncher doesn’t emulate a Windows environment.
