### ISSUE TITLE
[F-Req] <option to chose a customized button setup>

### ISSUE THREAD

**Issue by francium96** [PojavLauncherTeam/PojavLauncher#2318]
### Is this request related to a bug?

maybe it's a bug. bc everytime I set up a layout I was told it's been saved but next time I start up the launcher it all gods back to defalt setup

### Describe the request.

every time I start a game I need to set up the layout and mapping for the buttons. that's really tedious. would you add a new feature that allows player to save a favoured layout and mapping?

**Comment by GoneSubject** [comment]
welp uh after you save the button control you must go in the place that you customized the button control and press "Select default Contron json" and choose the name of the control that you named and after that press save but this time you must press exit and there you go

**Comment by francium96** [comment]
> welp uh after you save the button control you must go in the place that you customized the button control and press "Select default Contron json" and choose the name of the control that you named and after that press save but this time you must press exit and there you go

But I cannot find the but you told. here is the screen shot 
![Screenshot_20211203_113203_net kdt pojavlaunch](https://user-images.githubusercontent.com/95456848/144540770-7430d916-480e-402b-8ace-74944c0c3fb1.jpg)
![Screenshot_20211203_113159_net kdt pojavlaunch](https://user-images.githubusercontent.com/95456848/144540771-a9baf8ea-8b90-4bb3-973f-ffa6f6fa9291.jpg)
I'm playing on release 3.3.1.1. maybe the but you mean is available on latest pre release?

**Comment by GoneSubject** [comment]
you must swipe from the right to left

**Comment by GoneSubject** [comment]
https://user-images.githubusercontent.com/95298052/144541164-09c20d5f-2c1b-4e47-bfe7-f9975d7c3f6f.mp4

here if you don't understand

**Comment by francium96** [comment]
> you must swipe from the right to left
it's solved and I was just so stupid not to realize that the swipe gesture is conflict to my Android control gesture which maps to back. I Changed Android setting and it's now solved. Thank you so much and your reply is helpful!

**Comment by GoneSubject** [comment]
> > you must swipe from the right to left
> > it's solved and I was just so stupid not to realize that the swipe gesture is conflict to my Android control gesture which maps to back. I Changed Android setting and it's now solved. Thank you so much and your reply is helpful!

ok close the issue by the way
