### ISSUE TITLE
[BUG] Error when entering the map with Virglrender OpenGL 4.5

### ISSUE THREAD

**Issue by UzakaZinnMCYTB** [PojavLauncherTeam/PojavLauncher#2319]
### Describe the bug

I opened Pojavlauncher's website, Pojavlauncher CH Play's interface is too familiar, I downloaded @Khanhduytran's openjdk v3 and downloaded Pojavlauncher. Well, a new interface. Pojavlauncher added virglrender, it's awesome. But when into the map ... It is a light flash map and the number is 100%. Cannot to map :(

### The log file and images/videos

https://youtu.be/TRiyrAFglIk

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Select virglrender opengl 4.5 
3. Enter Minecraft world 
4. Got an error (watch video ^^^)
```

### Expected Behavior

Fix lỗi nhanh nha team Pojavlauncher

### Platform

```markdown
- Device model: Vivo Y21s
- CPU architecture: aarch64
- Android version:11 
- PojavLauncher version: Android CI#3436. v3 openjdk
```

### Anything else?

And the error code 1 1.18 even if installed Jdk17 or jre17

**Comment by GoneSubject** [comment]
know this: virgl suck

**Comment by GoneSubject** [comment]
btw almost forgot put the logs not videos in the future

**Comment by Nahdjwdn** [comment]
That sucks

**Comment by khanhduytran0** [comment]
@UzakaZinnMCYTB @Nahdjwdn virgl doesn’t emulate what a RTX 3090 do, so please don’t expect much from it.

**Comment by khanhduytran0** [comment]
Actually, the latest build comes with updated virgl (arm64) which should be capable of playing with a few shaders.
