### ISSUE TITLE
Is "Pojav Launcher" V3 is closed for some maintenance?

### ISSUE THREAD

**Issue by vovamod** [PojavLauncherTeam/PojavLauncher#232]
Sorry for disturbing Tran Khanh Duy, but wanted to ask if there will be support for Mi 9T Pro? 'Cause I can't play minecraft version 1.11.2 if playing on Pojav Launcher Previem 2.5 version and 3 version. Just wanted to know if there will be support, thanks if you respond) (I read that this version is NOT working right) Is this version is getting the biggest update? (support for normal use?)

**Comment by khanhduytran0** [comment]
I still leave code of v3 but because some components takes huge time to done so I temporary stop working on v3.

**Comment by vovamod** [comment]
Thanks for answer! I am really glad that development is still in progress in curtains)

**Comment by vovamod** [comment]
`question`

**Comment by khanhduytran0** [comment]
@vovamod v3 is active development and now support 1.7+(?), so i will gonna close.
