### ISSUE TITLE
A list of working shaders with it's corresponding working renderer

### ISSUE THREAD

**Issue by mchnjt** [PojavLauncherTeam/PojavLauncher#2322]
We know that all "Open4ES" shaders are guaranteed to work, so let's see if real shaders work as well

I (or me and my- i mean duy's onlyfans discord server) decided to test real shaders within a month, so that we can see if that one specific real shaders work in PojavLauncher

So far, i tested these shaders myself
- PotatoShaders
- Chocapic (extreme)
- ~~SEUS PTGI E12~~

If the corresponding shader name has an ✔️, it determines that it is working with that specific renderer. if ✅ , it is working but not properly. If ❌, the shader don't work.
For example: 
- (shader name) ✔️ | Zink 
- shader name) ✅ | VGPU
- (shader name) ❌ | Zink

If you wanna help testing shaders, feel free to submit your findings in this issue

Also include your phone's CPU and GPU details, and a screenshot with the debug panel (F3, in-game)

**Comment by NotAHero04** [comment]
Did you just try some of them? Maybe push your results here.

**Comment by GoneSubject** [comment]
cool

**Comment by mchnjt** [comment]
![Screenshot_20211203-211831~2](https://user-images.githubusercontent.com/83752061/144609222-e2170ebb-423d-4a58-947d-9abb7008a8dc.png)
(posted from duy's onlyfans discord)
(Don't mind the "smooth format". I ain't gonna let you do a smooth format)

**Comment by GoneSubject** [comment]
nice

**Comment by dachisao** [comment]
cool

**Comment by dachisao** [comment]
this is worthy of being pinned and adding "documentary" label

**Comment by TRHLoofi** [comment]
Huwaei y7 adreno how to work zink shader 4gb ram 64 memory not work is error and so logg but vgpu working vgpu shader how to work zink please help me to injoy the game

**Comment by NotAHero04** [comment]
Bruh. This issue is not for help, please make a new issue or join the Discord server to get help.

**Comment by GoneSubject** [comment]
yea in here just to tell the shaders that's real or something and it's works or not

**Comment by Yashjbk17** [comment]
Zink renderer is crashing on my mobile
4gb ram
32gb rom
64bits
Android version=8

**Comment by Yashjbk17** [comment]
OpenES4 shaders are also crashing

**Comment by GoneSubject** [comment]
> Bruh. This issue is not for help, please make a new issue or join the Discord server to get help.

can you see this?

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/folder/cp87zpb3ichj7/Open4ES
Open4ES archive here, works on GL4ES + OptiFine, mc 1.8-1.16.5, only for Snapdragon CPUs

**Comment by GaucovyAero** [comment]
zink (opengl 4.6 over vulkan) is now available in the zink branch on github actions, a lot of shaders do work with it

**Comment by GaucovyAero** [comment]
zink is now in mainline github actions, closing this issue as completed, because zink supports almost all shaders out there
