### ISSUE TITLE
Why this is happening to me i followed all the step

### ISSUE THREAD

**Issue by kavyansh-glitch** [PojavLauncherTeam/PojavLauncher#2323]
### Describe the bug

![Screenshot_2021-12-01-18-33-21-428_net kdt pojavlaunch](https://user-images.githubusercontent.com/74851491/144623320-c9dbae7a-055c-4d2e-becf-416d84bdbd4f.jpg)

Please fix it i wanna play optifine 
Thanx

### Steps To Reproduce

```markdown
1.start pojav
2 select the optifine 1.18 pre5
3.option-) launch mod 
4. Select the pojav117OF assets latest
5. Select the optifine version 
6.press ok 
It happens
```

### Expected Behavior

I expect it to patch the optifine 1.18 version

### Platform

```markdown
- Device model: mi note 6 pro
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version:corocus-v3 openJdk
```

### Anything else?

I followed the latest step on faq-en on pojav discord server

**Comment by GoneSubject** [comment]
can you try to delete that version file in sd card/Android/data/net.ndt.pojavlaunch(debug)/files/.minecraft/versions and find the version that you want to patch and delete it then install it again and use the patch it may fix

**Comment by kavyansh-glitch** [comment]
I

**Comment by kavyansh-glitch** [comment]
I did what you said 
I deleted the new optifine version 1.18 pre5 version
Reinstalled it 
Tried to patch it but the same issue happened again

**Comment by kavyansh-glitch** [comment]
Btw my 1.18 worked but , I can't install optifine .

**Comment by NotAHero04** [comment]
@kavyansh-glitch Did you get a patched OptiFine 1.18 (not pre1) before?

**Comment by kavyansh-glitch** [comment]
Yeah i did

**Comment by GoneSubject** [comment]
strange

**Comment by kavyansh-glitch** [comment]
Let me try to reinstall everything

**Comment by kavyansh-glitch** [comment]
I Didn't reinstalled but followed the latest faq-en information and it worked thanx
