### ISSUE TITLE
1.18 Bug

### ISSUE THREAD

**Issue by 8SamPSH9** [PojavLauncherTeam/PojavLauncher#2324]
### Describe the bug

when i go to 1.18 normal (without optifine) it doesn't have any text , what can i do ?

### The log file and images/videos

![Screenshot_20211203-202151_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88630012/144641522-53c2fcfe-4490-40e1-974e-98b428ee0f4d.jpg)

### Steps To Reproduce

```markdown
1.start pojav
2.go to 1.18 normal
3.it bugs , and it doesn't have any text:(
```

### Expected Behavior

Pls fix

### Platform

```markdown
- Device model: Samsung galaxy A71
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest build github
```

**Comment by GoneSubject** [comment]
latest build in github?

**Comment by GoneSubject** [comment]
bro use the play store

**Comment by 8SamPSH9** [comment]
Tnx

**Comment by ghost** [comment]
Use the given resource pack for 1.18 and activate it in options.txt .Then text will appear

**Comment by GoneSubject** [comment]
> Use the given resource pack for 1.18 and activate it in options.txt .Then text will appear

welp uh you don't need to do that
