### ISSUE TITLE
[BUG] 1.17 didn't work

### ISSUE THREAD

**Issue by JustGame1186** [PojavLauncherTeam/PojavLauncher#2325]
### Describe the bug

Minecraft and the launcher always crash when i try to join world. Is my device doesn't support latest version?

### The log file and images/videos

[2021-12-03-3.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/7652480/2021-12-03-3.log)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Select version 1.17
3. Select singleplayer mode
4. Open new world
5. The launcher crash
```

### Expected Behavior

Need solution

### Platform

```markdown
- Device model: Vivo Y95 4/64
- CPU architecture: aarch64
- Android version: 8
- PojavLauncher version: [Playstore release||version crocus-v3_openjdk]
```

**Comment by khanhduytran0** [comment]
> 2021-12-03-3.log

That’s not what we need. The issue template has already specified which file to send. It’s called `latestlog.txt`, not the latest `.log` file.

> The log file called `latestlog.txt` is located under `Android/data/net.kdt.pojavlaunch/files`, `games/PojavLauncher/` or `games/PojavLauncher/.minecraft`. You may need to activate an option in your file explorer to see hidden files and folders.

**Comment by JustGame1186** [comment]
> > 2021-12-03-3.log
> 
> That’s not what we need. The issue template has already specified which file to send. It’s called `latestlog.txt`, not the latest `.log` file.
> 
> > The log file called `latestlog.txt` is located under `Android/data/net.kdt.pojavlaunch/files`, `games/PojavLauncher/` or `games/PojavLauncher/.minecraft`. You may need to activate an option in your file explorer to see hidden files and folders.

Oh, sorry
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7652545/latestlog.txt)
Here

**Comment by khanhduytran0** [comment]
> Selected Minecraft version: 1.16.5-forge-36.2.0 (1.16.5)

The log for 1.17 has been lost. Please reproduce the problem then send the log right after crash happens.

**Comment by JustGame1186** [comment]
> > Selected Minecraft version: 1.16.5-forge-36.2.0 (1.16.5)
> 
> The log for 1.17 has been lost. Please reproduce the problem then send the log right after crash happens.

Here's the new one
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7652603/latestlog.txt)

**Comment by khanhduytran0** [comment]
How much memory did you set?
Does it crash with 1.17.1?

**Comment by JustGame1186** [comment]
> 



> How much memory did you set? Does it crash with 1.17.1?

1850, i try to lower it but still crash, also all the latest version (1.17+) doesn't work

**Comment by GoneSubject** [comment]
strange again

**Comment by SprainedSpark89** [comment]
did you download the resouce pack from https://pojavlauncherteam.github.io/updates/117.html
if you did and selcted it and still crashes you may have to find a resouce pack that increases fps maybe you run out of fps

**Comment by Nahdjwdn** [comment]
I don't know why my phone do not crash also you need a resource pack

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
