### ISSUE TITLE
[BUG] Interface issues

### ISSUE THREAD

**Issue by BlackPistol** [PojavLauncherTeam/PojavLauncher#2326]
### Describe the bug

To describe the issue according to the title above:

- Scrolling to search for the items I want is impossible prior to versions 1.13 - 1.16.5. This issue isn't applied to versions 1.17.10 - 1.12.2. I have to manually search for items using the search toolbar or by using commands to get them.
- Typing using my Android keyboard is laggy, unlike in versions 1.7.10 - 1.12.2. This applies to versions 1.13 - 1.16.5.
- The biggest issue by far: The file directory "versions" where I installed the versions of Minecraft is empty, even though I have versions (for example, 1.15.2) installed.

### The log file and images/videos

![Screenshot_2021-12-04-10-23-22-416_ru zdevs zarchiver](https://user-images.githubusercontent.com/84720161/144694116-2930f02b-643d-443b-8141-dd219dd534cb.jpg)
This screenshot shows that the "versions" file is empty, even though I have versions installed.

### Steps To Reproduce

```markdown
First bug:
- Start up a Minecraft version (any version, for example 1.13 - 1.16.5. Any version below 1.13 won't have this bug happen).
- Open up the Creative menu.
- Try scrolling using your finger without the Mouse input turned on.

Second bug:
- Press "Keyboard" on the top screen.
- Type something in chat or when searching for items.

Third bug:
- Download a Minecraft version (Release, Alpha, Beta, Snapshot, etc..)
- Exit out of PojavLauncher after downloading.
- Go to the files (games > PojavLauncher > .minecraft > versions)
```

### Expected Behavior

First bug:
- Scrolling works as expected.

Second bug:
- Typing is as smooth as a smoothened stone block.

Third bug:
- A version that's been downloaded (whether it be with or without Forge / Fabric / Optifine installed) would appear in the "versions" folder.

### Platform

```markdown
- Device model: POCO M3
- CPU architecture: Octa-core Max 2.0GHz
- Android version: Android 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

You guys are bad at managing your own app. Nuff said.

**Comment by GoneSubject** [comment]
first you can do it but you must hold the pri button if you just touch without the pri button it's like 1 click not hold click
> First bug:- Start up a Minecraft version (any version, for example 1.13 - 1.16.5. Any version below 1.13 won't have this bug happen).- Open up the Creative menu.- Try scrolling using your finger without the Mouse input turned on.

**Comment by dachisao** [comment]
This is not a bug at all, as i can scroll the item search menu by hovering the pointer on the scroll bar and holding "PRI" button

Second, the PojavLauncher directory is moved to Android/data/`net.kdt.pojavlaunch(.debug)`
(for devices android 10 up)

Third, your statement " the devs are bad at managing Pojav" is not true at all, so go fuck your own brain up, not sue the devs

**Comment by GoneSubject1** [comment]
welp idk why the keyboard kinda laggy but just type slowly or something cause to that
Second bug:- Press "Keyboard" on the top screen.- Type something in chat or when searching for items

**Comment by GoneSubject** [comment]
> This is not a bug at all, as i can scroll the item search menu by hovering the pointer on the scroll bar and holding "PRI" button
> 
> Second, the PojavLauncher directory is moved to Android/data/`net.kdt.pojavlaunch(.debug)`
> (for devices android 10 up)
> 
> Third, your statement " the devs are bad at managing Pojav" is not true at all, so go fuck your own brain up, not sue the devs

ah thanks

**Comment by dachisao** [comment]
I can't believe this repo's issue reports has dumbass authors

**Comment by GoneSubject** [comment]
yea

**Comment by GoneSubject** [comment]
he/she just too dumb and didn't look at news or something

**Comment by khanhduytran0** [comment]
> Try scrolling using your finger without the Mouse input turned on.

**Minecraft Java has never been designed for touch devices so what do you expect?**. We have already added a way for it: scrolling with 2 fingers just like scrolling with a touchpad on a laptop.

**Comment by ghost** [comment]
> You guys are bad at managing your own app. Nuff said.

Just migrate to mcinabox and dont come here

**Comment by GoneSubject** [comment]
> > You guys are bad at managing your own app. Nuff said.
> 
> Just migrate to mcinabox and dont come here

yeeeee right

**Comment by GoneSubject** [comment]
> > Try scrolling using your finger without the Mouse input turned on.
> 
> Minecraft Java has never been designed for touch devices so. We have already added a way for it: scrolling with 2 fingers just like scrolling with a touchpad on a laptop.

oh thanks i need that too

**Comment by khanhduytran0** [comment]
> You guys are bad at managing your own app. Nuff said.

**We aren't paid to do this job**, you know.

**Comment by khanhduytran0** [comment]
> Go to the files (games > PojavLauncher > .minecraft > versions)

@BlackPistol another thing: have you ever seen this dialog pops up, or just not gonna read it?
![Android10filelocation](https://user-images.githubusercontent.com/40482367/144695243-7008d909-7285-4dc0-940c-46c1485f5d14.png)

**Comment by dachisao** [comment]
when you don't know shit, you disregard it ¯\_(ツ)_/¯

**Comment by khanhduytran0** [comment]
> Typing using <ins>my Android keyboard</ins> is laggy, unlike in versions 1.7.10 - 1.12.2. This applies to versions 1.13 - 1.16.5.

*Oh yeah, you just said that it's your keyboard, so that means you developed that keyboard, and now it lags*

**Comment by GoneSubject** [comment]
mine kinda laggy a bit but im good with it

**Comment by khanhduytran0** [comment]
Also, do you know what are you running? It's a **PC** game. How do you expect 100% stuff to work correctly and smoothly? Yeah, your *phone* doesn't have an Intel Core i9.

**Comment by Py10lolz** [comment]
Pro tip: add -Xint to your JVM args
