### ISSUE TITLE
[BUG] Changing to a custom skin crashes the game entirely

### ISSUE THREAD

**Issue by BlackPistol** [PojavLauncherTeam/PojavLauncher#2327]
### Describe the bug

So, I have read the comments on my last bug report (currently closed) that the "versions" I've downloaded has been migrated to a new directory.
(Android > data > android.kdt.pojavlauncher > files > minecraft > versions)
But the problem is, when I tried to change to a custom skin I have, why does PojavLauncher crash on me?

### The log file and images/videos

![Screenshot_2021-12-04-12-34-46-129_ru zdevs zarchiver](https://user-images.githubusercontent.com/84720161/144697311-aa10e0c0-d902-4091-b47f-4e2d7a36a3b4.jpg)

![Screenshot_2021-12-04-12-47-46-502_ru zdevs zarchiver](https://user-images.githubusercontent.com/84720161/144697465-1c169c57-e879-44ff-9de7-994ee374cb41.jpg)

![Screenshot_2021-12-04-12-47-54-979_ru zdevs zarchiver](https://user-images.githubusercontent.com/84720161/144697486-95a5da88-c981-424c-ab26-1fec6b60da92.jpg)

### Steps To Reproduce

```markdown
How it started:
1. Download a skin.
2. Open up ZArchiver (the file explorer I used to change to my custom skin).
3. Duplicate the skin as a copy.
4. Rename them "steve.png" and "alex.png" respectively.
5. Copy them both and paste them in the version (in my case, 1.16.5) according to the file directory: (Android > data > android.kdt.pojavlauncher > files > minecraft > versions > 1.16.5 > 1.16.5.jar > assets > minecraft > entity) (There are two image files called "steve.png" and "alex.png". I just pasted the two (of the same) renamed custom skins here by overriding the Steve and Alex skins.
```

### Expected Behavior

I was able to open up the world on the version that my custom skin was in and roam freely.

### Platform

```markdown
- Device model: POCO M3
- CPU architecture: Octa-core Max 2.0GHz
- Android version: Android 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

Sorry, guys.
Just had a rough temper in terms of issues with game mechanics.

**Comment by GoneSubject1** [comment]
welp uh there's 2 ways to see your skin:
1 use a resource pack but no one can see your skin
2 use a mod (i forgot what is it)

**Comment by BlackPistol** [comment]
> welp uh there's 2 ways to see your skin: 1 use a resource pack but no one can see your skin 2 use a mod (i forgot what is it)

I have to use a resource pack??? There are tutorials on how to input a custom skin without the need of a resource pack, and it worked, though... (Note that I tried this method for 1.7.10 - 1.12.2).

This time, I'm trying the same thing but on 1.13 - 1.16.5.

**Comment by GoneSubject** [comment]
> > welp uh there's 2 ways to see your skin: 1 use a resource pack but no one can see your skin 2 use a mod (i forgot what is it)
> 
> I have to use a resource pack??? There are tutorials on how to input a custom skin without the need of a resource pack, and it worked, though... (Note that I tried this method for 1.7.10 - 1.12.2).
> 
> This time, I'm trying the same thing but on 1.13 - 1.16.5. 

uh there's a mod that can help you and other see your skin i think above 1.13 btw

**Comment by khanhduytran0** [comment]
There's a method that works for all versions: go to https://minecraft.net/en-us/profile/skin

**Comment by dachisao** [comment]
Pircay

**Comment by GoneSubject** [comment]
._,

**Comment by BlackPistol** [comment]
Anyone knows which version of the CustomSkinLoader mod I should download? I always rely on Forge instead of Fabric.

**Comment by dachisao** [comment]
CUSTOMSKINLOADER :cringe:
BRO JUST BUY THE GAME

**Comment by GoneSubject** [comment]
yea

**Comment by BlackPistol** [comment]
Please guys... Just help me out a bit here.
Also, PojavLauncher is free on Google Play Store.

**Comment by GoneSubject** [comment]
> Please guys... Just help me out a bit here.
> Also, PojavLauncher is free on Google Play Store.

who said we need paid for it

**Comment by BlackPistol** [comment]
That's not what 

> > Please guys... Just help me out a bit here.
> > Also, PojavLauncher is free on Google Play Store.
> 
> who said we need paid for it

That's not what I meant...

**Comment by GoneSubject** [comment]
nvm im gone here

**Comment by ghost** [comment]
Just buy the game and open
https://minecraft.net

No acc = no skin change

Also no pirate support

Just close the issue

**Comment by Mathias-Boulay** [comment]
No piracy support, thanks.

**Comment by BlackPistol** [comment]
> No piracy support, thanks.

Who told you to close this issue??

**Comment by NotAHero04** [comment]
> > No piracy support, thanks.
> 
> Who told you to close this issue??

Microsoft, okay?

**Comment by WesleyVanNeck** [comment]
> > No piracy support, thanks.
> 
> Who told you to close this issue??

He is a dev and piracy isn't allowed

**Comment by InfiniXDerg** [comment]
> > > No piracy support, thanks.
> > 
> > 
> > Who told you to close this issue??
> 
> He is a dev and piracy isn't allowed

Also he disrespect Mathias saying that :trollface:

**Comment by Mathias-Boulay** [comment]
> > No piracy support, thanks.
> 
> Who told you to close this issue??

I told it to myself, and that's enough

**Comment by NotAHero04** [comment]
Drop support for #2329 then? 🤣

**Comment by Mathias-Boulay** [comment]
*This dude is going DOWN*

**Comment by GoneSubject** [comment]
I'm so dumb in here ._.

**Comment by WesleyVanNeck** [comment]
> _This dude is going DOWN_

another one bites the dust

**Comment by GoneSubject** [comment]
ight nvm this issue closed and that guy got blocked so ima gone

**Comment by InfiniXDerg** [comment]
Gay
