### ISSUE TITLE
There's no .minecraft in my "pojavlauncher" folder

### ISSUE THREAD

**Issue by yok939** [PojavLauncherTeam/PojavLauncher#2328]
### Describe the bug

there's nothing in my pojavlauncher folder
I enabled hidden folders and nothing change

I can't do anything about it, can't load sodium
since 1.18 is causing lag in my A51 5G
please help 

### The log file and images/videos

![With ZArchiver](https://user-images.githubusercontent.com/95528357/144708174-fe9356f7-9de9-4a8d-85cc-1b6a35f8c4c5.jpg)
![With File Manager +](https://user-images.githubusercontent.com/95528357/144708177-7159a5fd-3e3d-4ca3-9a0c-ce9911909d98.jpg)

both games/PojavLauncher

### Steps To Reproduce

```markdown
1. Start PojavLauncher then start up fabric  1.18
2. force close after fully open
3. go any file manager then go games/PojavLauncher
```

### Expected Behavior

I expect there's .minecraft folder show up in PojavLauncher folder

### Platform

```markdown
- Device model: Galaxy A51 5G 6/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by GoneSubject** [comment]
did you turned on the "show hidden files" ?

**Comment by yok939** [comment]
> 

I did that and nothing happened

**Comment by GoneSubject** [comment]
you must find it in sd card/Android/data/net.ndt.pojavlaunch(debug)/files/.minecraft

**Comment by GoneSubject** [comment]
only for android 10+

**Comment by yok939** [comment]
> 

same
![Screenshot_20211204-205954_ZArchiver](https://user-images.githubusercontent.com/95528357/144710344-1a6c96ad-50e4-4b0c-96ee-f2c391eebe3c.jpg)

**Comment by yok939** [comment]
> you must find it in sd card/Android/data/net.ndt.pojavlaunch(debug)/files/.minecraft


I also don't know why there's only one data folder in my device
or I gonna download it from github?

**Comment by GoneSubject** [comment]
> > 
> 
> same
> ![Screenshot_20211204-205954_ZArchiver](https://user-images.githubusercontent.com/95528357/144710344-1a6c96ad-50e4-4b0c-96ee-f2c391eebe3c.jpg)
> 

turn on "show hidden files"

**Comment by GoneSubject** [comment]
> > you must find it in sd card/Android/data/net.ndt.pojavlaunch(debug)/files/.minecraft
> 
> 
> I also don't know why there's only one data folder in my device
> or I gonna download it from github?
> 

no you can't

**Comment by GoneSubject** [comment]
but you can add the file to favorite

**Comment by yok939** [comment]
> but you can add the file to favorite

hmm what's that mean

**Comment by GoneSubject** [comment]
> > but you can add the file to favorite
> 
> hmm what's that mean

nvm accept it

**Comment by GoneSubject** [comment]
it just take some secs to go in there so

**Comment by Yashjbk17** [comment]
There is a seeting "show hidden folders" turn that on

**Comment by GoneSubject** [comment]
> There is a seeting "show hidden folders" turn that on

yes

**Comment by yok939** [comment]
> There is a seeting "show hidden folders" turn that on

do you guys know there's still nothing after I turn on that

**Comment by yok939** [comment]
bruh I found it

**Comment by GoneSubject** [comment]
> > There is a seeting "show hidden folders" turn that on
> 
> do you guys know there's still nothing after I turn on that

did you go to sdcard/Android/data/net.ndt.pojavlaunch/files?

**Comment by GoneSubject** [comment]
> bruh I found it

really

**Comment by MercuryYen** [comment]
So....where did you find it? I encountered a same problem on my A52s.

**Comment by MercuryYen** [comment]
Ok I found it. Using a native file browser is not a good choice to find a folder beginning with ".".  (Even on PC), so I downloaded another file browser (ZArchiver) and enabled something like "showing "." folder". Then I can find .minecraft under /Android/data/net.ndt.pojavlaunch/files/.

**Comment by Tacosmeow** [comment]
If you read this thread and it still doesn't work check internalstorage/Android/data/net.ndt.pojavlaunch/files

**Comment by 13chandrasnataa** [comment]
Actually... I can't find the files folder in net.ndt.pojavlaunch. It's only showing me Sdcard/Android/data/net.ndt.pojavlaunch
Do you guys have any clue pls

**Comment by 13chandrasnataa** [comment]
![Screenshot_20231217_211953_ZArchiver](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154076117/c9f7fa10-11cc-4523-8a1f-878921f40733)

**Comment by 13chandrasnataa** [comment]
My mobile is Samsung galaxy

**Comment by GaucovyAero** [comment]
> My mobile is Samsung galaxy

what android version?

**Comment by Alcatone** [comment]
i have the same problem with my A55 and i try with pc with ZArchiver and more and more and when i push select the folder android make a popup to for my private life select oter folder...

**Comment by Alcatone** [comment]
is a god idea to create a import menu on the aplication for the mods and shader and resourcepacks i sink

**Comment by Alcatone** [comment]
im on android 14

**Comment by helveticafedora** [comment]
Alright so the fix for this is using zarchiver and shizuku

Let me walk you thru the steps and potential suggestions to prevent this:
1. You can either be rooted or not.
2. For non rooted you may use shizuku and wireless debugging in developer options(https://www.androidpolice.com/how-to-use-shizuku-for-adb-rootless-mods-on-any-android-device/)
3. Give zarchiver access of shizuku and go to the settings > file list > show hidden files

There.
As for my suggestion for the developer, please do add a file system built into the app to navigate to your minecraft installation to easily import mods
