### ISSUE TITLE
Is this project still active? 

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#233]

**Comment by artdeell** [comment]
It is. We just moved onto Discord instead of talking thru Issues. Hovewer, we still read the bug reports from here.

**Comment by artdeell** [comment]
Do you want some more info about what's going on?

**Comment by leetmussc** [comment]
Yes.

**Comment by khanhduytran0** [comment]
Join https://discord.gg/wfpRTy

**Comment by reply7251** [comment]
Is there a new link?

**Comment by leetmussc** [comment]
I need a new link aswell.

**Comment by khanhduytran0** [comment]
https://discord.gg/zgHCCp
Just expire after 1 day.

**Comment by the-n1n** [comment]
I have just got this and I was wondering if there was a way I could join the discord also?  - Off-topic but are premium servers ever going to get support?

**Comment by khanhduytran0** [comment]
Ok I will do a permanetly link @the-n1n https://discord.gg/yCVRHrG
