### ISSUE TITLE
No X11 DISPLAY variable was set

### ISSUE THREAD

**Issue by End3r27** [PojavLauncherTeam/PojavLauncher#2330]
### Describe the bug

Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

### Steps To Reproduce

```markdown
start pojavlauncher
start minecraft forge 1.12.2
```

### Expected Behavior

basically, a popup window should appear, and you should click it, but the game crashes after the minecraft loading screen.

### Platform

```markdown
- Device model: pixel 2 XL 
- Android version: 11
- PojavLauncher version: latest
```

**Comment by BlackusPL** [comment]
I have same problem

**Comment by GoneSubject** [comment]
im asking for help

**Comment by BlackusPL** [comment]
I solved it. Download PoJavLauncher from Actions https://github.com/PojavLauncherTeam/PojavLauncher/actions
For me work.

**Comment by GoneSubject** [comment]
> I solved it. Download PoJavLauncher from Actions https://github.com/PojavLauncherTeam/PojavLauncher/actions For me work.

oh ok

**Comment by GoneSubject** [comment]
with me play store version is best

**Comment by BlackusPL** [comment]
> with me play store version is best

For me google play version fix this problem too.

**Comment by GoneSubject** [comment]
> > with me play store version is best
> 
> For me google play version fix this problem too.

hm ok

**Comment by khanhduytran0** [comment]
@End3r27 perhaps you have an outdated build which didn’t support launching graphical java programs.
