### ISSUE TITLE
Optifine crashes on the actions [Fix scroll crashing 1.13+]

### ISSUE THREAD

**Issue by MansaceBall** [PojavLauncherTeam/PojavLauncher#2332]
### Describe the bug

Installing or opening Optifine caused any version of Minecraft to crash with the message "Game exited"

### The log file and images/videos

Game exited

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Open Optifine
3. Have game launch
```

### Expected Behavior

I expected the game to launch like normal

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

b

**Comment by GoneSubject** [comment]
no platform info?

**Comment by MansaceBall** [comment]
Oh yeah. My bad.

Device Model: Acer Chromebook 315
CPU Architecture: x86_64 Intel Celeron N4020
Android version: Chrome OS
ojavlauncher version: Action release: Fix scroll crashing 1.13+

**Comment by GoneSubject** [comment]
hmm

**Comment by GoneSubject** [comment]
can you send the log?

**Comment by Rajveerja** [comment]
The snapshot is to much lage

**Comment by GoneSubject** [comment]
wdym

**Comment by zekyupanda** [comment]
Giw

**Comment by GoneSubject** [comment]
what?
