### ISSUE TITLE
Could you add older versions of java runtime

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2335]
### Is this request related to a bug?

This is maybe related to a bug

### Describe the request.

Could you add older versions of java because i really want to run old versions of minecraft but if i use java 8 it crashes almost immediately and using java 17 it will not work will not boot it up.
like really old before infdev
### Anything else?

That it is upsetting that it would just crash.

**Comment by GoneSubject** [comment]
uh i think it because the render that you use, if you want to play old version you must use 1.1.4 render but if you ewant to use newer version i recommended you to use 1.1.5 render, java 17 only let you play versions like 1.17 or 1.18 you can run it with 1.16 too

**Comment by SprainedSpark89** [comment]
Did

**Comment by GoneSubject** [comment]
so it's worked? if it's not send the log
> The log file called latestlog.txt is located under Android/data/net.kdt.pojavlaunch/files, games/PojavLauncher/ or games/PojavLauncher/.minecraft. You may need to activate an option in your file explorer to see hidden files and folders

**Comment by SprainedSpark89** [comment]
Just to let you know i haven't used 1.1.4 render on the older versions i have been using 1.1.5 i will try 1.1.4 ok

**Comment by GoneSubject** [comment]
hm ok

**Comment by SprainedSpark89** [comment]
Same result

**Comment by GoneSubject** [comment]
send log (sorry for long reply)

**Comment by SprainedSpark89** [comment]
What do you mean by that

**Comment by GoneSubject** [comment]
> What do you mean by that

send the logs bro
> The log file called latestlog.txt is located under Android/data/net.kdt.pojavlaunch/files, games/PojavLauncher/ or games/PojavLauncher/.minecraft. You may need to activate an option in your file explorer to see hidden files and folders

**Comment by SprainedSpark89** [comment]
They are and i installed a debug version of it and the playstore just saying`
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7655247/latestlog.txt)
`

**Comment by GoneSubject** [comment]
uhhh

**Comment by GoneSubject** [comment]
at least i can get the link

**Comment by GoneSubject** [comment]
did you turn off the fullscreen and turn it on again?

**Comment by shadichy** [comment]
could you add openj9 vm support?

**Comment by GoneSubject** [comment]
what ._.

**Comment by shadichy** [comment]
yes, openj9

**Comment by GoneSubject** [comment]
ok

**Comment by khanhduytran0** [comment]
> Could you add older versions of java beacause i really want to run old versions of minecraft but if i use java 1.8.0 it crashes almost atmedietly

It's not about the Java, it's about the rendering library

**Comment by shadichy** [comment]
openj9 as [described by eclipse](https://www.eclipse.org/openj9/)

**Comment by GoneSubject** [comment]
> openj9 as [described by eclipse](https://www.eclipse.org/openj9/)

cool

**Comment by SprainedSpark89** [comment]
> did you turn off the fullscreen and turn it on again?

they only for some reason start as not fullscreen and the only thing that makes them fullsreen is a f11 button pressed in the menu no where else

**Comment by SprainedSpark89** [comment]
'-' could this not go off topic

**Comment by GoneSubject** [comment]
> > did you turn off the fullscreen and turn it on again?
> 
> they only for some reason start as not fullscreen and the only thing that makes them fullsreen is a f11 button pressed in the menu no where else

ah ok

**Comment by SprainedSpark89** [comment]
the older versions
