### ISSUE TITLE
[F-Req] mouse pointer

### ISSUE THREAD

**Issue by ihsanharh** [PojavLauncherTeam/PojavLauncher#2337]
### Is this request related to a bug?

no

### Describe the request.

is it possible to make the physical mouse cursor compatible with built-in cursor? like make the black big cursor disappear and replace with the built-in one

so we can change the cursor size to small not big and black one

**Comment by GoneSubject** [comment]
you mean like changing the cursor smaller or what?

**Comment by ihsanharh** [comment]
like changing the black cursor from external mouse with built-in cursor

**Comment by GoneSubject** [comment]
idk

**Comment by SprainedSpark89** [comment]
do you mean like a chromebook where there is already a mouse

**Comment by ihsanharh** [comment]
no I mean like this so I have physical mouse and keyboard connected to phone, a mouse cursor will show up by default, i want the default android black cursor replaced by built-in pojav cursor whenever playing pojav, so make that default cursor disappear by replacing it with the built-in pojav cursor(the white mouse cursor)

so it's like RDP app

**Comment by GoneSubject** [comment]
oh

**Comment by GoneSubject** [comment]
welp im dumb in this so bye

**Comment by Mathias-Boulay** [comment]
hmmmm... meh.
It can be done.

**Comment by Mathias-Boulay** [comment]
> is it possible to make the physical mouse cursor compatible with built-in cursor? like make the black big cursor disappear and replace with the built-in one

Some devices have a delay between the mouse cursor and when the image can be moved.
So it won't be done
