### ISSUE TITLE
1.18 dosen't works

### ISSUE THREAD

**Issue by Yashjbk17** [PojavLauncherTeam/PojavLauncher#2338]
### Describe the bug

1.18 is not starting although i have a (jre17) runtime and the new 1.18 resourcepack

### Steps To Reproduce

```markdown
1.launch 1.18
2.mojang screen comes 
3.it crashes
```

### Expected Behavior

I expect the game to run properly

### Platform

```markdown
- Device model: vivo y81
- CPU architecture: 64bit
- Android version: 8
- PojavLauncher version: playstore one
```

### Anything else?

Plz help

**Comment by GoneSubject** [comment]
send log

**Comment by Yashjbk17** [comment]
It is fixed

**Comment by GoneSubject** [comment]
oh ok

**Comment by GoneSubject** [comment]
trick that i used when i got 1.17 warn: press cancel and press play again and tap ok and no crash(except if there's like wrong things)
