### ISSUE TITLE
Lunar Client CRASH😭

### ISSUE THREAD

**Issue by 8SamPSH9** [PojavLauncherTeam/PojavLauncher#2340]
![Screenshot_20211205-184909_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/88630012/144752835-129f9f0c-1432-4869-956e-cfde89c4b56e.jpg)
Dont say enable VBO It doesn't work😭😭🥱
- Pojav Version : latest in play store
- Android : 11
-  CPU : aarch64
- Model : Samsung galaxy A71

**Comment by ghost** [comment]
Not help about remastering client

**Comment by ghost** [comment]
If still not agree just come here

https://discord.gg/lunarclient

**Comment by 8SamPSH9** [comment]
> Not help about remastering client
> 
> 

Its 1.8.9 , if i go to 1.8.9 normal it crash too😭

**Comment by GoneSubject** [comment]
hm i guess send log? maybe it's help

**Comment by 8SamPSH9** [comment]
> hm i guess send log? maybe it's help

![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7669412/latestlog.txt)

**Comment by GoneSubject** [comment]
> > hm i guess send log? maybe it's help
> 
> ![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7669412/latestlog.txt)

ok why it is 1.18 optifine i thought it must like lunar cluent bro

**Comment by GoneSubject** [comment]
> > Not help about remastering client
> > 
> > 
> 
> Its 1.8.9 , if i go to 1.8.9 normal it crash too😭

hm it must be something that you do wrong

**Comment by NotAHero04** [comment]
Duplicate of #2234. There will be no support for unofficial copies of clients that have their own launchers.

**Comment by GoneSubject** [comment]
._,
