### ISSUE TITLE
[BUG] external mouse is not hiding

### ISSUE THREAD

**Issue by PastMC** [PojavLauncherTeam/PojavLauncher#2341]
### Describe the bug

external mouse is not hiding in game

### The log file and images/videos

https://imgur.com/a/c6D8WWJ

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Launch version
3.Join to World
```

### Expected Behavior

external mouse is not hiding

### Platform

```markdown
- Device model: meizu m6s
- CPU architecture: aarch64
- Android version: 7.1.2
- PojavLauncher version: crocus-281-e896229e4-v3_openjdk (9938285)
```

**Comment by GoneSubject1** [comment]
where's log?

**Comment by GoneSubject** [comment]
that external mouse is not from PojavLauncher so you must try to hide it

**Comment by Mathias-Boulay** [comment]
android's fault here and we can't do anything about it. Maybe pick an android version that supports mouse capture next time ?
