### ISSUE TITLE
403

### ISSUE THREAD

**Issue by Emre15955** [PojavLauncherTeam/PojavLauncher#2343]
### Describe the bug

I write the information of my microsoft envy to play multiplayer but it does not happen error code:403 says all the information is not understood down to my phone correctly

### Steps To Reproduce

```markdown
I write down my information and log in says errorcode:403
```

### Expected Behavior

error while waiting for it to enter

### Platform

```markdown
- Device model
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
- Did you buy the game?
- Are you 18+?

*I suppose not at both, as the form is incomplete, and you didn’t say that you bought the game for $26.95*

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
