### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by jcax23** [PojavLauncherTeam/PojavLauncher#2344]
### Describe the bug

I decided that I wanted to play 1.0 Minecraft for nostalgia, but the game wasn't fitting with my screen perfectly and the game crashes when I get into a world. It's most likely the render, but I'm not entirely sure.

### Steps To Reproduce

```markdown
1. Lower Resolution so the game fits my screen (which kind of worked, but didn't fit the whole screen).
2. Change Render and GUI scale (Helped me be able to run and see the game).
3. Change how much storage is used on the game for it to run (went from 1200-1250 to 900-980).
```

### Expected Behavior

I expected the game to load properly and hope the game runs smooth.

### Platform

```markdown
- Device model: Moto G Play
- CPU architecture: Don't knoww how to lood at the CPU architecture)
- Android version: 11
- PojavLauncher version: Latest (hit update on google play this morning.
```

**Comment by khanhduytran0** [comment]
> 1. Lower Resolution so the game fits my screen (which kind of worked, but didn't fit the whole screen).
> 2. Change Render and GUI scale (Helped me be able to run and see the game).

Have you ever thought about pressing F11? :eyes:

> the game crashes when I get into a world

Looks like a renderer bug. `latestlog.txt`is not sent. Try creating file `/sdcard/Android/data/net.kdt.pojavlaunch(.debug)/files/custom_env.txt` with the following content: `LIBGL_USEVBO=0` then launch the game.

**Comment by jcax23** [comment]
🤦‍♂️ forgot about that, I had my keyboard connected too... Thanks!

**Comment by Mathias-Boulay** [comment]
@khanhduytran0 If some env variables are needed for some versions, maybe we should auto-enable them 🤔

**Comment by jcax23** [comment]
That's sounds like a good idea to me!

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
