### ISSUE TITLE
[F-Req] Code Explanation

### ISSUE THREAD

**Issue by pikachub2005** [PojavLauncherTeam/PojavLauncher#2345]
### Is this request related to a bug?

No.

### Describe the request.

Can you explain how packets are sent to the server, and what the different packets are? Thanks.

**Comment by artdeell** [comment]
We don't make a minecraft client. It's called Pojav**Launcher** for a reason. It's a **launcher**. It **launches** real JVM, set up to run real Minecraft, with all necessities translated.

**Comment by artdeell** [comment]
You better check this out: https://github.com/GeyserMC/MCProtocolLib

**Comment by pikachub2005** [comment]
> You better check this out: https://github.com/GeyserMC/MCProtocolLib

Okay, I will. (I don't know java, but I guess I'll have to learn eventually)
