### ISSUE TITLE
【bug】Renderer error

### ISSUE THREAD

**Issue by xlive2233** [PojavLauncherTeam/PojavLauncher#2346]
### Describe the bug

No log files, using the Google version of the Zink renderer is very catchy, so it's easy to use debug New renderer inside. But there was an error in the image. As shown in the figure.

### The log file and images/videos

![Screenshot_2021-12-07-08-44-33-686_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/28977537/144945712-fee80070-2687-4ae8-8808-8489224f50e0.jpg)
![Screenshot_2021-12-07-08-40-53-743_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/28977537/144945716-2e1279ac-a98b-40f7-8181-9a7d925df560.jpg)
![Screenshot_2021-12-07-08-41-23-933_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/28977537/144945717-f3e94a22-e780-4b0a-91da-b27486b1ac1d.jpg)
![Screenshot_2021-12-07-08-44-09-947_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/28977537/144945719-7a4739fa-f128-49d0-9ad3-dac808cb1793.jpg)

### Steps To Reproduce

```markdown
1.Start the game normally
```

### Expected Behavior

Fix the above errors and bugs

### Platform

```markdown
- Device model: dipper/xiaomi8
- CPU architecture: 845
- Android version: Android10
- PojavLauncher version: debug crocus-284-4219779ce-v3_openjdk
```

**Comment by xlive2233** [comment]
1.18

**Comment by GoneSubject** [comment]
ok.. why did you use virgl render?

**Comment by khanhduytran0** [comment]
> Actually, we don't develop virglrenderer
> Renderers aren't developed by us and we don't have the knowledge to fix their issues

**Comment by NotAHero04** [comment]
Meanwhile, try running [this file](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar) on the mod installer and use gl4es 1.1.5, the text can render just fine.

**Comment by GoneSubject** [comment]
yea

**Comment by xlive2233** [comment]
> > 实际上，我们不开发 virglrenderer
> > 渲染器不是我们开发的，我们也没有解决他们问题的知识

OK, but except for this renderer, other renderers don't seem to run 1.18. The FPS of Zink renderer on my phone is very low.

**Comment by xlive2233** [comment]
> 同时，尝试在 mod 安装程序上运行[此文件](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar)并使用 gl4es 1.1.5，文本可以呈现得很好。

OK, I'll test it

**Comment by xlive2233** [comment]
> 同时，尝试在 mod 安装程序上运行[此文件](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar)并使用 gl4es 1.1.5，文本可以呈现得很好。

It can run. I wonder if it is needed in all subsequent versions? I hope it can be integrated into the starter

**Comment by GoneSubject** [comment]
> > 同时，尝试在 mod 安装程序上运行[此文件](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar)并使用 gl4es 1.1.5，文本可以呈现得很好。
> 
> It can run. I wonder if it is needed in all subsequent versions? I hope it can be integrated into the starter

yes it will be need for 1.17 and later

**Comment by xlive2233** [comment]
> > > 同时，尝试在[此修改](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar)安装程序上运行[文件](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar)并使用 gl4es 1.1.5，文本可以呈现得很好。
> > 
> > 
> > 它可以运行。不知道以后的所有版本都需要吗？希望可以集成到starter中
> 
> 是的，1.17 及更高版本需要

In my latest test, I found that forge mod is still not supported. The version is 1.18-forge-38.0.15。Log not found

**Comment by GoneSubject** [comment]
welp yes 1.18 forge and fabric is not supported but you can play 1.18 optifine

**Comment by xlive2233** [comment]
> welp 是 1.18 forge 和 fabric 不受支持，但你可以玩 1.18 optifine

Will you consider supporting them in the future?

**Comment by GoneSubject** [comment]
> > welp 是 1.18 forge 和 fabric 不受支持，但你可以玩 1.18 optifine
> 
> Will you consider supporting them in the future? 

1 that I'm not 1 of the developers
2 developers will try to support them so wait

**Comment by xlive2233** [comment]
> > welp 是 1.18 forge 和 fabric 不受支持，但你可以玩 1.18 optifine
> 
> The mod server has been upgraded to 1.18. This support is necessary,

**Comment by GoneSubject** [comment]
what do you mean?

**Comment by aaaapai** [comment]
> > > welp 是 1.18 forge 和 fabric 不受支持，但你可以玩 1.18 optifine
> > 
> > 
> > The mod server has been upgraded to 1.18. This support is necessary,

特别是vgpu，但是，我在旧版本中成功运行了原版1.17，可是后来高一点版本就变成了渲染那么一点区域

**Comment by aaaapai** [comment]
> > > welp 是 1.18 forge 和 fabric 不受支持，但你可以玩 1.18 optifine
> > 
> > 
> > The mod server has been upgraded to 1.18. This support is necessary,

你用的也是华为浏览器吗？不过我现在用via了

**Comment by GoneSubject** [comment]
*confused*
