### ISSUE TITLE
[BUG] assets-v0.zip options not working

### ISSUE THREAD

**Issue by Bluebob9** [PojavLauncherTeam/PojavLauncher#2347]
### Describe the bug

so basically my log says 1.18 that assets-v0.zip is no longer compatible  btw when i im offline i launch PojavLauncher it crashes

### The log file and images/videos

file is options.txt i located in /SAF/AndroidData/net.kdt.pojavlaunch.debug/files

### Steps To Reproduce

```markdown
i launch pojavlauncher and i play 1.18 i have the runtime running and after that i see a assets-v0.zip is no compatable in options anymore in log after of that launch after minecraft almost done it crash
```

### Expected Behavior

i thought its working but it crash

### Platform

```markdown
- Device model:Samsung Galaxy A11/32GB
- CPU architecture:8x ARM Cortex-A53 @ 1.80 GHz/32 bits
- Android version:11 
- PojavLauncher version:crocus-284-4219779ce-v3_openjdk
```

### Anything else?

_btw when im offline i launch pojavlauncher it crashes_

**Comment by GoneSubject** [comment]
> file is options.txt i located in /SAF/AndroidData/net.kdt.pojavlaunch.debug/files

we not like asking do you know where the latestlog we need you to send the log

**Comment by GoneSubject** [comment]
> so basically my log says 1.18 that assets-v0.zip is no longer compatible btw when i im offline i launch PojavLauncher it crashes

yes because you get the old assets-v0, [here](https://cdn.discordapp.com/attachments/724163890803638277/892912425366589460/assets-v0.zip) the new one replace it with the old one in the resources pack folder
if you don't know where follow the steps bellow
> The resource pack folder is located under Android/data/net.kdt.pojavlaunch/files/PojavLauncher/.minecraft/resourcepack or games/PojavLauncher/.minecraft/resourcepack. You may need to activate an option in your file explorer to see hidden files and folders

**Comment by Bluebob9** [comment]
thanks

**Comment by GoneSubject** [comment]
ok
