### ISSUE TITLE
[BUG] <Cài optifine bị lỗi>

### ISSUE THREAD

**Issue by MAXIMUM796** [PojavLauncherTeam/PojavLauncher#2348]
### Describe the bug

The mouse can't move and it's the same a erro of app ( when I install optifine)

### Steps To Reproduce

```markdown
I don't know
```

### Expected Behavior

I hope who can help me about this erro!

### Platform

```markdown
- Device model: samsung A12
- CPU architecture: 
- Android version: 11
- PojavLauncher version:
```

### Anything else?

không

**Comment by NotAHero04** [comment]
Update your launcher to the latest GitHub build.

**Comment by MAXIMUM796** [comment]
> Update your start up up the new GitHub version.

How to do it?, please

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
