### ISSUE TITLE
2000 closed issues!

### ISSUE THREAD

**Issue by PastMC** [PojavLauncherTeam/PojavLauncher#2351]

**Comment by PastMC** [comment]
2000

**Comment by GoneSubject** [comment]
cool

**Comment by NotAHero04** [comment]
bruh 😦

**Comment by GoneSubject** [comment]
welp uh at least this person closed this

**Comment by khanhduytran0** [comment]
> 2000

This issue tracker is not a counter. You have been warned <img src="https://cdn.discordapp.com/emojis/855474693208014879.png?size=22">

**Comment by GoneSubject** [comment]
oof
