### ISSUE TITLE
[Stop cursed] <Someone is bad>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2355]
### Describe the bug

Why is there no manners  You should be courteous to others, not insults.  What are you cursing for?  What did you insult?  Do you know how to help others? Foolish bastards, have your parents ever taught you manners?  Do you know the help?  Why do you have to bully other people, be courteous.  People will ask for help, what will help him?  Why should you be racist that he's stupid, he's not smart, is it you who's stupid like a buffalo?, learn to understand other people's feelings too.  ,You guys are idiots, racist idiots, your parents don't teach you.  ,You guys shouldn't be born human, God shouldn't have sent you to be born

### The log file and images/videos

![Screenshot_2021-12-08-11-14-15-49](https://user-images.githubusercontent.com/93668117/145200109-ce709a6b-4726-4c04-8bc6-e6ce87aba8a1.jpg)
![Screenshot_2021-12-08-11-14-08-81](https://user-images.githubusercontent.com/93668117/145200129-bbeb3f1e-712c-4931-baea-930700192d27.jpg)
![Screenshot_2021-12-08-11-09-29-68](https://user-images.githubusercontent.com/93668117/145200152-51f86cd5-8394-4cde-a051-2544b1c9cef9.jpg)
![Screenshot_2021-12-08-11-12-14-66](https://user-images.githubusercontent.com/93668117/145200167-14068e2a-4175-4c00-965a-949061f00856.jpg)

### Steps To Reproduce

```markdown
You are look like a shit
```

### Expected Behavior

No, You guys are idiot

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: .
```

**Comment by NotAHero04** [comment]
off-topic goes brrr

**Comment by NotAHero04** [comment]
And you really have a slow brain to be honest. Most of the people I helped can, at least, have enough brain power to just follow what I told him to do. And you are under them, so what do you expect?

**Comment by khanhduytran0** [comment]
*your attitude is weirder everyday. tell your age to continue*

**Comment by GoneSubject** [comment]
oof

**Comment by khanhduytran0** [comment]
wtf, did they just delete their account?

**Comment by khanhduytran0** [comment]
hey, did they just delete their account?

**Comment by NotAHero04** [comment]
ghost haha

**Comment by GoneSubject** [comment]
hm

**Comment by dachisao** [comment]
> hey, did they just delete their account?

angry moment

**Comment by GoneSubject** [comment]
wait who made this issue bruh

**Comment by dachisao** [comment]
these mfs can't use even a single IQ
a helper's job is to help people, but they should help theirselves aswell

**Comment by khanhduytran0** [comment]
![9977BEFD-F481-4431-986C-5F5805941AD9](https://user-images.githubusercontent.com/40482367/145201288-3202dfb8-8577-4f1d-852c-8bc999546d96.jpeg)

**Comment by dachisao** [comment]
they can't just depend on a helper's mouth

**Comment by GoneSubject** [comment]
> these mfs can't use even a single IQ a helper's job is to help people, but they should help theirselves aswell

yea..

**Comment by GoneSubject** [comment]
i tried but that person is like too dumb that i don't know how to help bruh

**Comment by dachisao** [comment]
> ### Describe the bug
> Why is there no manners You should be courteous to others, not insults. What are you cursing for? What did you insult? Do you know how to help others? Foolish bastards, have your parents ever taught you manners? Do you know the help? Why do you have to bully other people, be courteous. People will ask for help, what will help him? Why should you be racist that he's stupid, he's not smart, is it you who's stupid like a buffalo?, learn to understand other people's feelings too. ,You guys are idiots, racist idiots, your parents don't teach you. ,You guys shouldn't be born human, God shouldn't have sent you to be born
> 
> ### The log file and images/videos
> ![Screenshot_2021-12-08-11-14-15-49](https://user-images.githubusercontent.com/93668117/145200109-ce709a6b-4726-4c04-8bc6-e6ce87aba8a1.jpg) ![Screenshot_2021-12-08-11-14-08-81](https://user-images.githubusercontent.com/93668117/145200129-bbeb3f1e-712c-4931-baea-930700192d27.jpg) ![Screenshot_2021-12-08-11-09-29-68](https://user-images.githubusercontent.com/93668117/145200152-51f86cd5-8394-4cde-a051-2544b1c9cef9.jpg) ![Screenshot_2021-12-08-11-12-14-66](https://user-images.githubusercontent.com/93668117/145200167-14068e2a-4175-4c00-965a-949061f00856.jpg)
> 
> ### Steps To Reproduce
> ```gfm
> You are look like a shit
> ```
> 
> ### Expected Behavior
> No, You guys are idiot
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version: .
> ```
> 
> ### Anything else?
> _No response_

YOURE THE ONE WHO IS AN IDIOT
YOU CANT EVEN FUCKING BACKREAD
YOU DON'T HAVE A FINGER
AND YOU SAY IM A FUCKING RACIST? HUH? WELL FIRST USE YOUR BRAIN ON COMPLEX SHIT BECAUSE THIS WHOLE "POJAVLAUNCHER" THING IS A COMPLETE FUCKING COMPLEXITY
HOW OLD ARE YOU
IF INCASE YOU HAVE A FUCKING ALT PLEASE COMMENT SO THAT I CAN IMPLANT IQ TO YOUR BRAIN

**Comment by GoneSubject** [comment]
the google translate can't translate for me ._.

**Comment by InfiniXDerg** [comment]
> ### Describe the bug
> 
> Why is there no manners You should be courteous to others, not insults. What are you cursing for? What did you insult? Do you know how to help others? Foolish bastards, have your parents ever taught you manners? Do you know the help? Why do you have to bully other people, be courteous. People will ask for help, what will help him? Why should you be racist that he's stupid, he's not smart, is it you who's stupid like a buffalo?, learn to understand other people's feelings too. ,You guys are idiots, racist idiots, your parents don't teach you. ,You guys shouldn't be born human, God shouldn't have sent you to be born
> ### The log file and images/videos
> 
> ![Screenshot_2021-12-08-11-14-15-49](https://user-images.githubusercontent.com/93668117/145200109-ce709a6b-4726-4c04-8bc6-e6ce87aba8a1.jpg) ![Screenshot_2021-12-08-11-14-08-81](https://user-images.githubusercontent.com/93668117/145200129-bbeb3f1e-712c-4931-baea-930700192d27.jpg) ![Screenshot_2021-12-08-11-09-29-68](https://user-images.githubusercontent.com/93668117/145200152-51f86cd5-8394-4cde-a051-2544b1c9cef9.jpg) ![Screenshot_2021-12-08-11-12-14-66](https://user-images.githubusercontent.com/93668117/145200167-14068e2a-4175-4c00-965a-949061f00856.jpg)
> ### Steps To Reproduce
> 
> ```gfm
> You are look like a shit
> ```
> 
> ### Expected Behavior
> 
> No, You guys are idiot
> ### Platform
> 
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version: .
> ```
> 
> ### Anything else?
> 
> _No response_

Shut the fuck up Deleted User

**Comment by GoneSubject** [comment]
bruh
