### ISSUE TITLE
The launcher crashes when I'm offline

### ISSUE THREAD

**Issue by ZIONJADEHD505** [PojavLauncherTeam/PojavLauncher#2356]
### Describe the bug

When open in offline it crashes 

### The log file and images/videos

Uploading SVID_20211208_191604_1.mp4…

### Steps To Reproduce

```markdown
1.Open the launcher
2.Select account 
3.Thn it crashes
```

### Expected Behavior

How to fix this? 

### Platform

```markdown
- Device model: Huawei MatePad T
- CPU architecture: armv7 32bit
- Android version: 10
- PojavLauncher version: crocus-291-095b62a10-profiles-2-electric-boogaloo
```

**Comment by GoneSubject** [comment]
1 we need the log not video
2 i think you should't use this version 
> PojavLauncher version: crocus-291-095b62a10-profiles-2-electric-boogaloo

**Comment by ZIONJADEHD505** [comment]
Kk

**Comment by GoneSubject** [comment]
welp uh i recommend you to use play store version
