### ISSUE TITLE
[BUG] I hate this because of the memory. when I have 2gb ram and select 600mb of memory it crash when i play all version. And when I use 300mb memory its not crash

### ISSUE THREAD

**Issue by jethro527** [PojavLauncherTeam/PojavLauncher#2357]
### Describe the bug

Bug

### The log file and images/videos

Bug

### Steps To Reproduce

```markdown
Bug
```

### Expected Behavior

Bug

### Platform

```markdown
- Device model: Itel p36
- CPU architecture: armv7/aarch32
- Android version: 9.0
- PojavLauncher version: 3.3.1.1
```

### Anything else?

Bug

**Comment by GoneSubject** [comment]
dude it crash because you put the ram that over the ram you having if you keep trying that your phone can explode

**Comment by mchnjt** [comment]
haha clown 
why 32bit

**Comment by SprainedSpark89** [comment]
i think if you turn it to the minimum it should help

**Comment by GoneSubject** [comment]
just allocate less ram 32 bits have problem with that

**Comment by Mathias-Boulay** [comment]
Hey.
Android and you other apps takes a huge part of the RAM already.
We can't do anything about this
