### ISSUE TITLE
[BUG] The mobs are very slow when I hit the mobs it will nock back very slow in all version of game the mobs are allways slow

### ISSUE THREAD

**Issue by jethro527** [PojavLauncherTeam/PojavLauncher#2358]
### Describe the bug

Slow

### The log file and images/videos

Slow

### Steps To Reproduce

```markdown
Slow bug
```

### Expected Behavior

Slow mobs bug

### Platform

```markdown
- Device model: Itel p36
- CPU architecture: armv7/aarch32
- Android version: 9.0
- PojavLauncher version: 3.3.1.1
```

### Anything else?

Mobs are very slow

**Comment by khanhduytran0** [comment]
Invalid/Incomplete information.

**Comment by GoneSubject** [comment]
bruh

**Comment by LightestMC** [comment]
This is not a bug, this has to do with your device's performance. (to be more exact, low memory)

**Comment by khanhduytran0** [comment]
> This is not a bug, this has to do with your device's performance. (to be more exact, low memory)

True. Slow CPU is also a problem.

@jethro527 your device doesn’t even meet the game minimum requirements.
> Processor SC7731E 1.3GHz Quad-core
> Memory 1GB RAM
