### ISSUE TITLE
Khi tôi vô thế giới tầm 1phut thì nó bị văng ra và tôi dùng forge 1.8.9 1.12.2 1.16.5 và các client khác nó cũng bị tình trạng văng game và còn nếu tôi chỉnh ram lên 1100 ram thì chơi các phiên bản tôi vừa liệt kê lên đều bị thoát mã 1

### ISSUE THREAD

**Issue by trankhanhhiep123** [PojavLauncherTeam/PojavLauncher#2359]
### Describe the bug

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7681584/latestlog.txt)
Khi tôi chouw game và vô thế giới thì bị văng game và khi chỉnh ram lên 1100 thì bị thoát mã 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7681601/latestlog.txt)

### Steps To Reproduce

```markdown
Tôi mong trò chơi sẽ fix các lỗi văng game và thoát mã 1
```

### Expected Behavior

Tôi mong sẽ fix văng game và thoát mã 1

### Platform

```markdown
- Device model:Samsung Galaxy A02s/64G 
- CPU architecture:aarch32
- Android version: 11
- PojavLauncher version: phiên bản mớ nhất trên chplay
```

**Comment by khanhduytran0** [comment]
- VBO phải được bật cho 1.8.9/1.12.2
- 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
- ~~English eta when~~

**Comment by trankhanhhiep123** [comment]
> - VBO phải được bật cho 1.8.9/1.12.2
> - 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> - ~~English eta when~~

Vậy mấy client 1.12.2 trở xuống phải bật VBO hả bro

**Comment by trankhanhhiep123** [comment]
> - VBO phải được bật cho 1.8.9/1.12.2
> - 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> - ~~English eta when~~

Vậy bn ram là ổn định vậy admin

**Comment by GoneSubject** [comment]
> > * VBO phải được bật cho 1.8.9/1.12.2
> > * 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > * ~English eta when~
> 
> Vậy mấy client 1.12.2 trở xuống phải bật VBO hả bro

đứng rồi

**Comment by GoneSubject** [comment]
> > * VBO phải được bật cho 1.8.9/1.12.2
> > * 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > * ~English eta when~
> 
> Vậy bn ram là ổn định vậy admin

chắc tầm 800 trở xuống nếu vẫn không được thì giảm thêm

**Comment by trankhanhhiep123** [comment]
> > > * VBO phải được bật cho 1.8.9/1.12.2
> > > * 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > > * ~English eta when~
> > 
> > Vậy bn ram là ổn định vậy admin
> 
> chắc tầm 800 trơe xuống

Ok cảm ơn 2 admin nhiều ạ

**Comment by GoneSubject** [comment]
> > > > * VBO phải được bật cho 1.8.9/1.12.2
> > > > * 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > > > * ~English eta when~
> > > 
> > > 
> > > Vậy bn ram là ổn định vậy admin
> > 
> > 
> > chắc tầm 800 trơe xuống
> 
> Ok cảm ơn 2 admin nhiều ạ

mình không phải admin mình chỉ là 1 thằng không biết code, coi mình là 1 thằng idiot đi

**Comment by trankhanhhiep123** [comment]
> > > > > * VBO phải được bật cho 1.8.9/1.12.2
> > > > > * 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > > > > * ~English eta when~
> > > > 
> > > > 
> > > > Vậy bn ram là ổn định vậy admin
> > > 
> > > 
> > > chắc tầm 800 trơe xuống
> > 
> > Ok cảm ơn 2 admin nhiều ạ
> 
> mình không phải admin mình chỉ là 1 thằng không biết code, coi mình là 1 thằng idiot đi

Ok bro

**Comment by trankhanhhiep123** [comment]
> - VBO phải được bật cho 1.8.9/1.12.2
> - 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> - ~~English eta when~~

Mà admin ơi em bật use VBOs rồi mà vẫn bj văng?

**Comment by GoneSubject** [comment]
> > - VBO phải được bật cho 1.8.9/1.12.2
> > - 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > - ~~English eta when~~
> 
> Mà admin ơi em bật use VBOs rồi mà vẫn bj văng?

gửi latestlog đê
> latestlog.txt thường sẽ được tìm thấy ở sdcard/Android/data/net.ndt/pojavlaunch/files hoặc là sdcard/games/PojavLauncher và bạn phải bật "hiện tiệp ẩn"

**Comment by trankhanhhiep123** [comment]
> > > - VBO phải được bật cho 1.8.9/1.12.2
> > > - 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > > - ~~English eta when~~
> > 
> > Mà admin ơi em bật use VBOs rồi mà vẫn bj văng?
> 
> gửi latestlog đê
> > latestlog.txt thường sẽ được tìm thấy ở sdcard/Android/data/net.ndt/pojavlaunch/files hoặc là sdcard/games/PojavLauncher và bạn phải bật "hiện tiệp ẩn"

Wtf lại phải gửi hả pro

**Comment by GoneSubject** [comment]
> > > > * VBO phải được bật cho 1.8.9/1.12.2
> > > > * 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > > > * ~English eta when~
> > > 
> > > 
> > > Mà admin ơi em bật use VBOs rồi mà vẫn bj văng?
> > 
> > 
> > gửi latestlog đê
> > > latestlog.txt thường sẽ được tìm thấy ở sdcard/Android/data/net.ndt/pojavlaunch/files hoặc là sdcard/games/PojavLauncher và bạn phải bật "hiện tiệp ẩn"
> 
> Wtf lại phải gửi hả pro

chứu sao

**Comment by trankhanhhiep123** [comment]
> > > - VBO phải được bật cho 1.8.9/1.12.2
> > > - 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > > - ~~English eta when~~
> > 
> > Mà admin ơi em bật use VBOs rồi mà vẫn bj văng?
> 
> gửi latestlog đê
> > latestlog.txt thường sẽ được tìm thấy ở sdcard/Android/data/net.ndt/pojavlaunch/files hoặc là sdcard/games/PojavLauncher và bạn phải bật "hiện tiệp ẩn"

![Screenshot_20211209-202313_GitHub.jpg](https://user-images.githubusercontent.com/67538943/145404333-21341ccd-a427-47b5-ba28-925ddc913d1c.jpg)

**Comment by trankhanhhiep123** [comment]
> > > > > * VBO phải được bật cho 1.8.9/1.12.2
> > > > > * 32bit không hỗ trợ thêm quá nhiều dung lượng RAM
> > > > > * ~English eta when~
> > > > 
> > > > 
> > > > Mà admin ơi em bật use VBOs rồi mà vẫn bj văng?
> > > 
> > > 
> > > gửi latestlog đê
> > > > latestlog.txt thường sẽ được tìm thấy ở sdcard/Android/data/net.ndt/pojavlaunch/files hoặc là sdcard/games/PojavLauncher và bạn phải bật "hiện tiệp ẩn"
> > 
> > Wtf lại phải gửi hả pro
> 
> chứu sao

Gồi pro

**Comment by GoneSubject** [comment]
phải chờ nó load chứ bro làm gì vội thế

**Comment by trankhanhhiep123** [comment]
> phải chờ nó load chứ bro làm gì vội thế

À tôi tưởng

**Comment by trankhanhhiep123** [comment]
> phải chờ nó load chứ bro làm gì vội thế

![Screenshot_20211209-202617_GitHub.jpg](https://user-images.githubusercontent.com/67538943/145404832-628026b3-905b-4b26-8081-66564da1682a.jpg)
 
Nó ra như v đó

**Comment by trankhanhhiep123** [comment]
> phải chờ nó load chứ bro làm gì vội thế

![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7685387/latestlog.txt)

**Comment by GoneSubject** [comment]
ok

**Comment by trankhanhhiep123** [comment]
> ok 
> 

Có bị làm sao ko bro

**Comment by trankhanhhiep123** [comment]
> ok 
> 

Xog chưa bro

**Comment by trankhanhhiep123** [comment]
> ok 
> 

Bro xog chưa

**Comment by GoneSubject** [comment]
> > ok
> 
> Bro xog chưa

ko bik nữa

**Comment by trankhanhhiep123** [comment]
> > > ok
> > 
> > Bro xog chưa
> 
> ko bik nữa

Là sao vậy bro

**Comment by GoneSubject** [comment]
> > > > ok
> > > 
> > > 
> > > Bro xog chưa
> > 
> > 
> > ko bik nữa
> 
> Là sao vậy bro

chờ anh duy

**Comment by trankhanhhiep123** [comment]
> > > > > ok
> > > > 
> > > > 
> > > > Bro xog chưa
> > > 
> > > 
> > > ko bik nữa
> > 
> > Là sao vậy bro
> 
> chờ anh duy

Ảnh làm j vậy bro

**Comment by GoneSubject** [comment]
> > > > > > ok
> > > > > 
> > > > > 
> > > > > Bro xog chưa
> > > > 
> > > > 
> > > > ko bik nữa
> > > 
> > > 
> > > Là sao vậy bro
> > 
> > 
> > chờ anh duy
> 
> Ảnh làm j vậy bro

bận mà có thể là do dùng lunar client mới không chơi được nên tui nghĩ ông nên dùng client khác đi

**Comment by trankhanhhiep123** [comment]
> > > > > > > ok
> > > > > > 
> > > > > > 
> > > > > > Bro xog chưa
> > > > > 
> > > > > 
> > > > > ko bik nữa
> > > > 
> > > > 
> > > > Là sao vậy bro
> > > 
> > > 
> > > chờ anh duy
> > 
> > Ảnh làm j vậy bro
> 
> bận mà có thể là do dùng lunar client mới không chơi được nên tui nghĩ ông nên dùng client khác đi
> 

À ok bro

**Comment by trankhanhhiep123** [comment]
> > > > > > > ok
> > > > > > 
> > > > > > 
> > > > > > Bro xog chưa
> > > > > 
> > > > > 
> > > > > ko bik nữa
> > > > 
> > > > 
> > > > Là sao vậy bro
> > > 
> > > 
> > > chờ anh duy
> > 
> > Ảnh làm j vậy bro
> 
> bận mà có thể là do dùng lunar client mới không chơi được nên tui nghĩ ông nên dùng client khác đi
> 

S lâu v bro

**Comment by GoneSubject** [comment]
thì ông phải không dùng clunar client đó hoặc là dùng client khác

**Comment by trankhanhhiep123** [comment]
> thì ông phải không dùng clunar client đó hoặc là dùng client khác

Tôi dùng pb nào cx bị văng bro à

**Comment by GoneSubject** [comment]
> > thì ông phải không dùng clunar client đó hoặc là dùng client khác
> 
> Tôi dùng pb nào cx bị văng bro à

là sao

**Comment by trankhanhhiep123** [comment]
> > > thì ông phải không dùng clunar client đó hoặc là dùng client khác
> > 
> > Tôi dùng pb nào cx bị văng bro à
> 
> là sao

Phiên bản hay client nào cz bị

**Comment by GoneSubject** [comment]
> > > > thì ông phải không dùng clunar client đó hoặc là dùng client khác
> > > 
> > > Tôi dùng pb nào cx bị văng bro à
> > 
> > là sao
> 
> Phiên bản hay client nào cz bị

thế thì dùng optifine đi

**Comment by trankhanhhiep123** [comment]
> > > > > thì ông phải không dùng clunar client đó hoặc là dùng client khác
> > > > 
> > > > Tôi dùng pb nào cx bị văng bro à
> > > 
> > > là sao
> > 
> > Phiên bản hay client nào cz bị
> 
> thế thì dùng optifine đi

Cx bị °-°

**Comment by GoneSubject** [comment]
vậy dừng bản thường được không?

**Comment by trankhanhhiep123** [comment]
> vậy dừng bản thường được không?

No bro

**Comment by GoneSubject** [comment]
ủa không dùng được bản thường gì dùng được bản gì

**Comment by trankhanhhiep123** [comment]
> ủa không dùng được bản thường gì dùng được bản gì

Xóa gem thôi :((

**Comment by GoneSubject** [comment]
> > ủa không dùng được bản thường gì dùng được bản gì
> 
> Xóa gem thôi :((

để nhờ anh @khanhduytran0 chứ thế này

**Comment by bot432** [comment]
Mua máy khác😭🤣

**Comment by bot432** [comment]
Vua nhóm pojav rồi gửi latestlog

**Comment by GoneSubject** [comment]
yea trong đó sẽ có nhiều trợ giúp hơn á

**Comment by bot432** [comment]
Đóng bug đi

**Comment by trankhanhhiep123** [comment]
> Đóng bug đi

Nhóm nào vậy mấy bro

**Comment by GoneSubject** [comment]
> > Đóng bug đi
> 
> Nhóm nào vậy mấy bro

nhóm này nè https://discord.gg/6RpEJda

**Comment by trankhanhhiep123** [comment]
> > > Đóng bug đi
> > 
> > Nhóm nào vậy mấy bro
> 
> nhóm này nè https://discord.gg/6RpEJda

Vô rồi bro

**Comment by GoneSubject** [comment]
> > > > Đóng bug đi
> > > 
> > > 
> > > Nhóm nào vậy mấy bro
> > 
> > 
> > nhóm này nè https://discord.gg/6RpEJda
> 
> Vô rồi bro

tìm channel tên android-others rồi xin trợ giúp rồi chờ

**Comment by trankhanhhiep123** [comment]
> > > > > Đóng bug đi
> > > > 
> > > > 
> > > > Nhóm nào vậy mấy bro
> > > 
> > > 
> > > nhóm này nè https://discord.gg/6RpEJda
> > 
> > Vô rồi bro
> 
> tìm channel tên pojav-others rồi xin trợ giúp rồi chờ

Ko có bro

**Comment by OhCauXanh** [comment]
> > > > > > Đóng bug đi
> > > > > 
> > > > > 
> > > > > Nhóm nào vậy mấy bro
> > > > 
> > > > 
> > > > nhóm này nè https://discord.gg/6RpEJda
> > > 
> > > 
> > > Vô rồi bro
> > 
> > 
> > tìm channel tên pojav-others rồi xin trợ giúp rồi chờ
> 
> Ko có bro

> > > > > > Đóng bug đi
> > > > > 
> > > > > 
> > > > > Nhóm nào vậy mấy bro
> > > > 
> > > > 
> > > > nhóm này nè https://discord.gg/6RpEJda
> > > 
> > > 
> > > Vô rồi bro
> > 
> > 
> > tìm channel tên pojav-others rồi xin trợ giúp rồi chờ
> 
> Ko có bro

server Pojav launcher > Other languages > android-other

**Comment by OhCauXanh** [comment]
> > > > > > > Đóng bug đi
> > > > > > 
> > > > > > 
> > > > > > Nhóm nào vậy mấy bro
> > > > > 
> > > > > 
> > > > > nhóm này nè https://discord.gg/6RpEJda
> > > > 
> > > > 
> > > > Vô rồi bro
> > > 
> > > 
> > > tìm channel tên pojav-others rồi xin trợ giúp rồi chờ
> > 
> > 
> > Ko có bro
> 
> > > > > > > Đóng bug đi
> > > > > > 
> > > > > > 
> > > > > > Nhóm nào vậy mấy bro
> > > > > 
> > > > > 
> > > > > nhóm này nè https://discord.gg/6RpEJda
> > > > 
> > > > 
> > > > Vô rồi bro
> > > 
> > > 
> > > tìm channel tên pojav-others rồi xin trợ giúp rồi chờ
> > 
> > 
> > Ko có bro
> 
> Pojav launcher > Other languages > android-other



> > > > > > > Đóng bug đi
> > > > > > 
> > > > > > 
> > > > > > Nhóm nào vậy mấy bro
> > > > > 
> > > > > 
> > > > > nhóm này nè https://discord.gg/6RpEJda
> > > > 
> > > > 
> > > > Vô rồi bro
> > > 
> > > 
> > > tìm channel tên pojav-others rồi xin trợ giúp rồi chờ
> > 
> > 
> > Ko có bro
> 
> > > > > > > Đóng bug đi
> > > > > > 
> > > > > > 
> > > > > > Nhóm nào vậy mấy bro
> > > > > 
> > > > > 
> > > > > nhóm này nè https://discord.gg/6RpEJda
> > > > 
> > > > 
> > > > Vô rồi bro
> > > 
> > > 
> > > tìm channel tên pojav-others rồi xin trợ giúp rồi chờ
> > 
> > 
> > Ko có bro
> 
> Pojav launcher > Other languages > android-other

![Uploading 20211215_085328.jpg…]()

**Comment by OhCauXanh** [comment]
20211215_085328.jpg

**Comment by khanhduytran0** [comment]
Lunar Client không được hỗ trợ.
Thử:
- Tắt VBO trong cài đặt của PojavLauncher
- Bật VBO trong game.
