### ISSUE TITLE
[BUG] <Short description> 1.17 doesn't work 

### ISSUE THREAD

**Issue by Planet52** [PojavLauncherTeam/PojavLauncher#2362]
### Describe the bug

APPLICATION EXIT WITH CODE 1 in 1.17

### Steps To Reproduce

```markdown
Open minecraft java in 1.17
```

### Expected Behavior

Close app with code 1

### Platform

```markdown
- Device model: s10 plus Samsung  512gb 
- CPU architecture: snapdragon 
- Android version: last 
- PojavLauncher version last
```

**Comment by mchnjt** [comment]
holy fuck
this dude is trying to launch 1.17 while half of the smartasses is playing 1.18

**Comment by GoneSubject** [comment]
bruh

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
