### ISSUE TITLE
[F-Req]  No lags in 1.18

### ISSUE THREAD

**Issue by Braydy** [PojavLauncherTeam/PojavLauncher#2363]
### Is this request related to a bug?

1.18

### Describe the request.

Want to improve gameplay in 1.18

### Anything else?

Can't register click in 1.18

**Comment by GoneSubject** [comment]
what?

**Comment by NotAHero04** [comment]
Don't touch the screen until the game fully loads.

**Comment by Braydy** [comment]
I already

**Comment by Mathias-Boulay** [comment]
ask mojang to optimize the game I guess
