### ISSUE TITLE
[BUG] <Always Force Close>

### ISSUE THREAD

**Issue by ZyraXen89** [PojavLauncherTeam/PojavLauncher#2366]
### Describe the bug

The app is always force closed. When I played on the server, it was immediately forced to close.

### The log file and images/videos

*None, because the application closed suddenly.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select version 1.9.4
3. Play Multiplayer
4. Enter to the server
5. Suddenly forced to stop.
```

### Expected Behavior

Hoping not to be forced closed.

### Platform

```markdown
- Device model: OPPO A15 3/32 GB
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I hope that nothing like this happens.

**Comment by GoneSubject** [comment]
so like it crashed?

**Comment by NotAHero04** [comment]
I smell VBO not enabled.

**Comment by GoneSubject** [comment]
bruh

**Comment by ZyraXen89** [comment]
> 

Really? How to enable?

**Comment by ZyraXen89** [comment]
> so like it crashed?

Yes

**Comment by ZyraXen89** [comment]
> I smell VBO not enabled.

Really? How to enable?

**Comment by LightestMC** [comment]
> > I smell VBO not enabled.
> 
> Really? How to enable?

Launch Minecraft, open Settings, click Video Settings and there you will see "Enable VBO"

**Comment by ZyraXen89** [comment]
> > > I smell VBO not enabled.
> > 
> > 
> > Really? How to enable?
> 
> Launch Minecraft, open Settings, click Video Settings and there you will see "Enable VBO"

Yes. I've tried it, and now it doesn't always force stop. Thank You!
