### ISSUE TITLE
Screen lag while hitting or placing block 

### ISSUE THREAD

**Issue by TizFacts** [PojavLauncherTeam/PojavLauncher#2368]
### Describe the bug

So before many weeks i left pojavlauncher becuase when i hit or place block my screen become choppy and start lag or start stucking although my fps is 100-160 
Tried everything not even finding any thread or issue why its getting to me only not while looking here only while hitting please fix it i bought a new account to play bedwars on hypixel but this happened and i thought it was my mouse problem but no becuase i triend pvping in mcinabox everything was fine but i love pojavlauncher please dont disappoint me😶😢😭

### Steps To Reproduce

```markdown
1.Start launcher
2.Go on hypixel and start playing bedwars
3.when i try to hit someone my game lags while my fps is 100
```

### Expected Behavior

Expected to play bedwars as god

### Platform

```markdown
- Device model: Samsung A51 6/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest also tried older version but no fix
```

**Comment by GoneSubject** [comment]
> i triend pvping in mcinabox everything was fine

😐

**Comment by GoneSubject** [comment]
i think this is not a bug

**Comment by TizFacts** [comment]
See this

**Comment by TizFacts** [comment]
#

>  @``
