### ISSUE TITLE
minecraft 1.18.1 crashes (1.18 works fine)

### ISSUE THREAD

**Issue by beetrootpotatocarrot** [PojavLauncherTeam/PojavLauncher#2369]
### Describe the bug

but it works on another phone i testet (samsung galaxy s5)
And my phone is a samung galaxy s9+

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7694993/latestlog.txt)
![20211210_153235](https://user-images.githubusercontent.com/81223029/145629594-0b7bf661-d4ea-4cb7-87a0-b52027277e32.jpg)

### Steps To Reproduce

```markdown
Start 1.18 on pojavlauncher.
```

### Expected Behavior

I experted the game to launch

### Platform

```markdown
- Device model: samsung galaxy  s9 plus and s5
- CPU architecture: arm64 s9 plus and arm s5
- Android version: 10 on s9 plus and android 11 on s5
- PojavLauncher version: latest google play version
```

**Comment by GoneSubject** [comment]
you must patch the version so you can play it i think, [here](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar) the patch download it anh use  as a jar file

**Comment by beetrootpotatocarrot** [comment]
but why does it work on the other phone then

**Comment by GoneSubject** [comment]
> but why does it work on the other phone then

wdym

**Comment by NotAHero04** [comment]
Please provide a valid log.

**Comment by beetrootpotatocarrot** [comment]
I have already posted a log

**Comment by NotAHero04** [comment]
OK. Try this: create a file named `custom_env.txt` in PojavLauncher's `files` folder, and then write
> LIBGL_NOINTOVLHACK=1
>
into it.

**Comment by Aaron102108** [comment]
Where can i put the patch file

**Comment by Aaron102108** [comment]
> you must patch the version so you can play it i think, [here](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar) the patch download it anh use as a jar file

Where do i put it

**Comment by GoneSubject** [comment]
> > you must patch the version so you can play it i think, [here](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar) the patch download it anh use as a jar file
> 
> Where do i put it

use it like a mod installer

**Comment by khanhduytran0** [comment]
The latest build should already fixed this bug. Closing.
