### ISSUE TITLE
[BUG] 1.18.1 crashes

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2370]
### Describe the bug

runs only on zink with strong lags. On Gl4es 1.1.5 (opengl 3) does not start at all. i know this will be a duplicate problem but i am writing this so you know with on which device the game fails to start. 
![Screenshot_20211210_224917_net kdt pojavlaunch](https://user-images.githubusercontent.com/75908293/145633615-ccfa9146-b191-4a39-aa2a-740db279c69b.jpg)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7695153/latestlog.txt)

### Steps To Reproduce

```markdown
1. Downloaded the resource assets_v0 for new versions of minecraft! (Followed the instructions for starting snapshots 21w37a)
2. Opened Pojavlauncher 
3. Chose java 17 
4. I chose render gl4es 1.1.5 (opengl 3) (on others too tried) 
5. Launched minecraft 1.18.1
6. The game crashed (read more in latestlog)
```

### Expected Behavior

. 

### Platform

```markdown
- Device model: huawei honor 9c AKA-L29 4/64
- CPU architecture: aarch64 kirin 710a
- Android version: 10 
- PojavLauncher version: Latest Release
```

**Comment by GoneSubject1** [comment]
ight duplicate

**Comment by GoneSubject** [comment]
> i am writing this so you know with on which device the game fails to start

we have like a tester so we know which works and which doesn't work and the reason you crash when using the gl4es is because you didn't follow this [website](https://pojavlauncherteam.github.io/updates/117.html)

**Comment by Iarkont** [comment]
> >  is because you didn't follow this [website](https://pojavlauncherteam.github.io/updates/117.html)
but i followed all the steps point by point on this site to run 1.18

**Comment by GoneSubject** [comment]
> > > is because you didn't follow this [website](https://pojavlauncherteam.github.io/updates/117.html)
> > > but i followed all the steps point by point on this site to run 1.18

you used the patch right?

**Comment by NotAHero04** [comment]
> but i followed all the steps point by point on this site to run 1.18
>
The website simply doesn't tell you to use Zink. If you use Zink, **no further patching is needed**.

**Comment by khanhduytran0** [comment]
The latest build should have fixed the overload function problem.
