### ISSUE TITLE
[BUG] <can't launch old versions of minecraft>

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2371]
### Describe the bug

When i try to launch versions older than some infdev versions they crash almost instantly and and the version of infdev you can't look around the earliest version that you can look around in is alpha 1.01 and some older versions that crash almost instantly in the moments before the crash so please fix this!!!

### Steps To Reproduce

```markdown
launch the oldest version of minecraft and launch infdev
```

### Expected Behavior

the oldest version of minecraft will crash and indev you can't look around

### Platform

```markdown
- Device model: samsung tab e and kindle hd 7 i forgot the number
- CPU architecture: unknown
- Android version: samsung=7? kindle=9 at least the apps think:-)
- PojavLauncher version: playstore
```

### Anything else?

nothing

**Comment by GoneSubject** [comment]
send log i guess?

**Comment by LightestMC** [comment]
To be fair, old versions also crash in the official minecraft launcher.

**Comment by GoneSubject** [comment]
oh so i guess it's like outdated

**Comment by NotAHero04** [comment]
Please provide a valid log.

**Comment by SprainedSpark89** [comment]
> To be fair, old versions also crash in the official minecraft launcher.

it doesn't send a crash log the only time it will that i know of is if i go to a different app with 1.12.2 open

**Comment by SprainedSpark89** [comment]
i also have a debug version of pojav installed i think i might delete it the log will say log debug and do you mean latest log?

**Comment by GoneSubject** [comment]
> i also have a debug version of pojav installed i think i might delete it the log will say log debug and do you mean latest log?
> 

yes the latest log
> The log file called latestlog.txt is located under sdcard/Android/data/net.kdt.pojavlaunch/files or sdcard/games/PojavLauncher/. You may need to activate an option in your file explorer to see hidden files and folders

**Comment by SprainedSpark89** [comment]
i know and the file path for me is storage/emulated/0/games/pojavlauncher/
and hidden files are on

**Comment by GoneSubject** [comment]
> i know and the file path for me is storage/emulated/0/games/pojavlauncher/ and hidden files are on

yes so send the log here

**Comment by NotAHero04** [comment]
Is your log too long to upload? It's been two days.

**Comment by GoneSubject** [comment]
> Is your log too long to upload? It's been two days.

maybe got error

**Comment by SprainedSpark89** [comment]
i will do it i forgot

**Comment by SprainedSpark89** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7791552/latestlog.txt)

**Comment by GoneSubject** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7791552/latestlog.txt)
> 

i see you using mods can you tell us what mod you using?

**Comment by SprainedSpark89** [comment]
i am on 1.12.2 for mods but there is no issue there and i thought that 1.12 didn't have a recipe book so just enough items and optifine on forge but i will not really use forge so i am using optifine not with forge

**Comment by ghost** [comment]
yes when i try to play 1.8.9 with optifine or cmpack cilent it crash , but sometimes it doesn't crash but takes more than 5 minutes to load , so i switched on 1.12.2 it also take time to launch but works

**Comment by SprainedSpark89** [comment]
try rd

**Comment by ghost** [comment]
> 

what????

**Comment by SprainedSpark89** [comment]
try rd indev and some infdev versions on pojavlauncher. these versions are what i am talking about.

**Comment by SprainedSpark89** [comment]
and i am using 1.12.2 is i good version to play while having the older versions fixed i would use 1.16 but it takes to long to generate a world i have not used 1.15 or 1.14 so 1.12.2 is what i am using for now.

**Comment by GoneSubject** [comment]
> i am on 1.12.2 for mods but there is no issue there and i thought that 1.12 didn't have a recipe book so just enough items and optifine on forge but i will not really use forge so i am using optifine not with forge

i think you should remove a mod, maybe try move the just enough items mod to another place and try again?

**Comment by SprainedSpark89** [comment]
There is no problem with 1.12.2. The version i am talking about are old before alpha

**Comment by SprainedSpark89** [comment]
> > i am on 1.12.2 for mods but there is no issue there and i thought that 1.12 didn't have a recipe book so just enough items and optifine on forge but i will not really use forge so i am using optifine not with forge
> 
> i think you should remove a mod, maybe try move the just enough items mod to another place and try again?

could you help me or have the bug fixed that indev and older versions crash and that infdev you can't look around?
this was the original problem/bug i needed help with after infdev there are no issues other than the alpha 1.0 but it is infdev. could you help?

**Comment by SprainedSpark89** [comment]
and also part of this was reported about a year ago here https://github.com/PojavLauncherTeam/PojavLauncher/issues/1713

**Comment by SprainedSpark89** [comment]
:-|

**Comment by SprainedSpark89** [comment]
it's a issue still

**Comment by SprainedSpark89** [comment]
@GoneSubject1 could you help with new issue or not?

**Comment by khanhduytran0** [comment]
@SprainedSpark89 why would you duplicate issues? it’s just ~~flooding and cause more stress to us while~~ help no more thing. Fully supporting Beta/Alpha version is not actually our main priority. **These are known to be buggy**, taking every version to work would take like forever since every works differently, certain versions doesn’t use LWJGL for handling camera movement, not to mention these may have never been tested on Linux.
See [l.java](https://cdn.discordapp.com/attachments/724164160761626624/807206224403759134/l.java) for more info.

**Comment by mchnjt** [comment]
block from repo moment eta wen

**Comment by mchnjt** [comment]
jk

**Comment by SprainedSpark89** [comment]
this issue has been going on for so long

**Comment by SprainedSpark89** [comment]
> @SprainedSpark89 why would you duplicate issues? it’s just ~flooding and cause more stress to us while~ help no more thing. Fully supporting Beta/Alpha version is not actually our main priority. **These are known to be buggy**, taking every version to work would take like forever since every works differently, certain versions doesn’t use LWJGL for handling camera movement, not to mention these may have never been tested on Linux. See [l.java](https://cdn.discordapp.com/attachments/724164160761626624/807206224403759134/l.java) for more info.

beta and alpha work fine older versions older than beta and alpha are having trouble

**Comment by khanhduytran0** [comment]
Yeah, I mean `old-alpha` and `old-beta`

**Comment by SprainedSpark89** [comment]
and i did report it but people look at the first things but not the stuff far back

**Comment by SprainedSpark89** [comment]
if you want to close them all fine :-( https://github.com/PojavLauncherTeam/PojavLauncher/issues/2639
