### ISSUE TITLE
The flip?

### ISSUE THREAD

**Issue by Zeyrox1090** [PojavLauncherTeam/PojavLauncher#2373]
### Describe the bug

its english but backwards 

### The log file and images/videos

![Screenshot_2021-12-11-14-19-40-36](https://user-images.githubusercontent.com/73925046/145666591-58fabc55-45b6-4a61-99f0-3671ac0972c6.jpg)

### Steps To Reproduce

```markdown
1.install pojav latest working action
2.open pojav
```

### Expected Behavior

i expect normal english lmao

### Platform

```markdown
- Device model: ¯\_(ツ)_/¯
- CPU architecture: ¯\_(ツ)_/¯
- Android version: ¯\_(ツ)_/¯
- PojavLauncher version: ¯\_(ツ)_/¯
```

**Comment by Zeyrox1090** [comment]
![Screenshot_2021-12-11-14-24-13-78_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/73925046/145666698-3a3ab6b1-8dbd-445a-b57b-820c626cbabb.jpg)
and if you exit pojav and come back while holding your phone on portrait mode it will look like this

**Comment by GoneSubject** [comment]
no platform info?

**Comment by Zeyrox1090** [comment]
![Screenshot_2021-12-11-15-01-34-09_c42fd5307ad0c723935554bc80c21421](https://user-images.githubusercontent.com/73925046/145667717-f0f4aec1-44fd-445e-96ee-2cbbcc340316.jpg)

**Comment by GoneSubject** [comment]
can i know the pojavlauncher version

**Comment by Zeyrox1090** [comment]
latest action

**Comment by Zeyrox1090** [comment]
![Screenshot_2021-12-11-15-10-46-39](https://user-images.githubusercontent.com/73925046/145667985-12e4b1ca-cf54-4efb-8e1a-914d3407e3d1.jpg)

**Comment by GoneSubject** [comment]
> ![Screenshot_2021-12-11-15-10-46-39](https://user-images.githubusercontent.com/73925046/145667985-12e4b1ca-cf54-4efb-8e1a-914d3407e3d1.jpg)

bro why use playstore version bro

**Comment by NotAHero04** [comment]
Changing language moment

**Comment by GoneSubject** [comment]
> Changing language moment

wdym
