### ISSUE TITLE
[BUG] <Resolution Scaler full screen plss help me

### ISSUE THREAD

**Issue by Kinerosales** [PojavLauncherTeam/PojavLauncher#2374]
### Describe the bug

![Screenshot_2021-12-11-14-51-06-57_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/92142150/145667450-3e118d2c-f3de-4af5-af0c-16b299d3c322.jpg)
When i get to 30% that happens to the screen plss help

### Steps To Reproduce

```markdown
1.i set my resolution scaler to 30% for more fps
2.start pojavlaunher
3.that happened
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: oppoa92020
- CPU architecture: 
- Android version: 11
- PojavLauncher version: play store
```

**Comment by GoneSubject1** [comment]
welp if you see a little button under the screen can you click there i mean the options then go to video settings and then there will be a setting call "GUI scale" you can change the gui to fit your screen

**Comment by NotAHero04** [comment]
Why 30% bruh

**Comment by NotAHero04** [comment]
Expected behavior

**Comment by SprainedSpark89** [comment]
you might have to turn up the resolution scale and equip a texture pack and if you set it to low the game is unplayable
