### ISSUE TITLE
[BUG] Error save replay on replay mod

### ISSUE THREAD

**Issue by PastMC** [PojavLauncherTeam/PojavLauncher#2375]
### Describe the bug

Replay mod can't save replay

### The log file and images/videos

java.nio.file.FileSystemException: /storage/emulated/0/games/PojavLauncher/.minecraft/replay_recordings/recording/2021_12_11_08_22_48.mcpr: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:283)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:471)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at com.replaymod.replaystudio.replay.ZipReplayFile.save(ZipReplayFile.java:323)
	at com.replaymod.core.files.DelegatingReplayFile.save(DelegatingReplayFile.java:70)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$6(PacketListener.java:297)
	at java.lang.Thread.run(Thread.java:748)

### Steps To Reproduce

```markdown
1.Start Pojav
2.Launch Minecraft
3.Join to world
4.Leave world
5.Error save replay
```

### Expected Behavior

Save replay

### Platform

```markdown
- Device model: meizu m6s
- CPU architecture: aarch64
- Android version: 7.1.2
- PojavLauncher version: Latest Debug Release
```

### Anything else?

No

**Comment by NotAHero04** [comment]
Because Android lacks a thing called `ffmpeg` in `/system/bin`, which is needed for Replay to function, currently you can only make it work with a rooted device/VM. You can use VMOS for it.

**Comment by PastMC** [comment]
I have root

**Comment by PastMC** [comment]
> 

how to make this?
I have root

**Comment by NotAHero04** [comment]
If you have Termux, try this: run
> pkg install ffmpeg
>
then find and symlink the `ffmpeg` executable to `/system/bin`.

**Comment by PastMC** [comment]
Not fix he don't save the replay file java.nio.file.FileSystemException: /storage/emulated/0/games/PojavLauncher/.minecraft/replay_recordings/recording/2021_12_11_08_22_48.mcpr: Operation not permitted

**Comment by PastMC** [comment]
https://youtu.be/HNE1RXXBUjM video

**Comment by PastMC** [comment]
I fix this by change apk PojavLauncher with APK Editor and change minecraft path to sdk 29 
old path:
![S11212-17110774](https://user-images.githubusercontent.com/52322048/145718042-6f6d4ecd-2a78-40f3-854e-03dd4939f7eb.jpg)
New Path:
![S11212-17104522](https://user-images.githubusercontent.com/52322048/145718059-8acb1e88-1396-4038-8287-387070100b8b.jpg)
And in game:
![S11212-17100792](https://user-images.githubusercontent.com/52322048/145718078-8d6cf137-cf5d-4dfc-bc6b-9f2af8388331.jpg)

**Comment by PastMC** [comment]
Link for apk (if who need): https://www.mediafire.com/file/mhq05p5b06sm7pu/PojavLauncher+(Minecraft_+Java+Edition+для+Android)_crocus-289-755148746-v3_openjdk.apk/file

**Comment by ProGamers1664** [comment]
> commented

Can you send a apk of the newer version of pojavlauncher that fixes this problem? Pls do it i cant just use replay mod pls.
