### ISSUE TITLE
[BUG] No outline in blocks in optifine 1.17.1 HD G9

### ISSUE THREAD

**Issue by Sculk** [PojavLauncherTeam/PojavLauncher#2376]
### Describe the bug

Jsbd

### Steps To Reproduce

```markdown
Bshbdvffb
```

### Expected Behavior

Hdhbfufbf

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Jdhbfhfbf

**Comment by GoneSubject1** [comment]
welp uh the outline blocks or the crosshair render thing when you press f3 is not working on 1.17 and higher
