### ISSUE TITLE
[BUG] no outline in 1.17.1 optifine HD G9

### ISSUE THREAD

**Issue by Sculk** [PojavLauncherTeam/PojavLauncher#2377]
### Describe the bug

It doesn't have an outline when look at the block which is hard when ur building cause u don't know how many blocks u placed

### The log file and images/videos

![Screenshot_2021-12-01-23-19-59-93_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95663470/145681368-bb347388-82ad-4707-bd03-a818e1f68669.jpg)

### Steps To Reproduce

```markdown
Step 1 I don't know
And step to I don't know either
```

### Expected Behavior

I expected that there would be a outline selection

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Pls can u fix this

**Comment by GoneSubject** [comment]
welp the outline blocks or the crosshair render thing when you press f3 is currently not working on 1.17 and higher

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build

**Comment by Sculk** [comment]
thank you☺️
