### ISSUE TITLE
VNC Connection Failed!?

### ISSUE THREAD

**Issue by SHADOWZXCV** [PojavLauncherTeam/PojavLauncher#238]
![Screenshot_20200629-184711_PojavLauncher_(Minecraft_Java_Edition_for_Android)](https://user-images.githubusercontent.com/34347098/86033364-1f583c80-ba39-11ea-9d85-7aa321b4040a.png)

Just downloaded v3.0.1 preview 5 and preview 4 , both of them don't launch any version of the game it just says failed to connect to port 5900 something...
I didn't install mods or anything it's the first time seeing your project and was curious to test it.

**Comment by khanhduytran0** [comment]
V3 is broken at the moment...

**Comment by TSaltedfishKing** [comment]
?!

**Comment by khanhduytran0** [comment]
V3 is unusable. I will close...
A new v3 may coming (not soon)
