### ISSUE TITLE
[BUG] 1.18 and 1.18.1

### ISSUE THREAD

**Issue by weekly71** [PojavLauncherTeam/PojavLauncher#2380]
### Describe the bug

1.17 works fine. When i try to start 1.18 it says Application exitet with code -1

### The log file and images/videos

![Screenshot_2021-12-11-17-59-39-556_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/66445346/145683306-486f4868-20c3-4e2f-a600-f6d12c121200.jpg)
![Screenshot_2021-12-11-17-40-05-558_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/66445346/145683311-a31cfc52-d6b6-40c3-836d-c8eb59a53389.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7697319/latestlog.txt)

`

### Steps To Reproduce

```markdown
1.Start PojavLauncher.
2.Select 1.18 and start the game.
3. Wait when it craches.
```

### Expected Behavior

It says Application exitet with error code -1

### Platform

```markdown
- Device model: Redmi Note 8
- CPU architecture: arm64
- Android version: 11, Miui 12.5
- PojavLauncher version: last
```

**Comment by GoneSubject** [comment]
did you followed [this website](https://pojavlauncherteam.github.io/updates/117.html)

**Comment by weekly71** [comment]
> did you followed [this website](https://pojavlauncherteam.github.io/updates/117.html)

Yes. Without this, 1.17 would not work either

**Comment by GoneSubject** [comment]
> > did you followed [this website](https://pojavlauncherteam.github.io/updates/117.html)
> 
> Yes. Without this, 1.17 would not work either
> 
> 

welp yes 1.17 will not worked, we sorry because this inconvenience

**Comment by beetrootpotatocarrot** [comment]
I have had the same problem but it has worked if I have used 1.18 but crashes in 1.18.1. I have tested on a 32bit phone (arm) and it worked. @d-idea Have you tried using the new assets-v0.zip for 1.18

**Comment by GoneSubject** [comment]
> I have had the same problem but it has worked if I have used 1.18 but crashes in 1.18.1. I have tested on a 32bit phone (arm) and it worked. @d-idea Have you tried using the new assets-v0.zip for 1.18

you need to use the new patch

**Comment by west-shell** [comment]
no no no .just install fabric . then they work well both

**Comment by west-shell** [comment]
use the latest version with virglerender

**Comment by GoneSubject** [comment]
> use the latest version with virglerender

why virgl

**Comment by west-shell** [comment]
other render all fail

**Comment by GoneSubject** [comment]
hmm you installed the new assets-v0 and you can play 1.18 but can't play 1.17?

**Comment by YoussefAhmedDev** [comment]
I was facing the same problem, but after I installed optifine every thing alright

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build
