### ISSUE TITLE
I have an error installing Forge [error -1]

### ISSUE THREAD

**Issue by AyderProgramic** [PojavLauncherTeam/PojavLauncher#2381]
### Describe the bug

Forge installations are fast, and when I want to go to the installed forge, Minecraft crashes with an error of -1

### The log file and images/videos
Erorr 
https://youtu.be/O7HJu5pd-bM
### Steps To Reproduce

```markdown
1.run pojav
2.installed forge
3.Logged into Minecraft Forge
```

### Expected Behavior

I expected that I would start playing Minecraft with mods!

### Platform

```markdown
- Device model: Poco x3 pro
- CPU architecture: 
- Android version: 12.5.5
- PojavLauncher version: Latest from google play
```

### Anything else?

Help pls

**Comment by SprainedSpark89** [comment]
can you run the non forge version?

**Comment by GoneSubject** [comment]
> can you run the non forge version?
> 

he did because we must run the non forge then he can install maybe

**Comment by GoneSubject** [comment]
and can you send the latest log?
> The log file called latestlog.txt is located under sdcard/Android/data/net.kdt.pojavlaunch/files or sdcard/games/PojavLauncher/. You may need to activate an option in your file explorer to see hidden files and folders

**Comment by Bruhwww** [comment]
I also have an error but it happens immediately when i try to install forge and sends me back to where you log in to your account. i think it said that it was error 1

**Comment by SprainedSpark89** [comment]
Try changing render or java i recently tried to install 1.18.2 optifine with the things that make 1.17+  work but i had to switch back to the settings before
