### ISSUE TITLE
[BUG] can't move cursor and screen 

### ISSUE THREAD

**Issue by SamirJosan** [PojavLauncherTeam/PojavLauncher#2382]
### Describe the bug

can't move cursor and screen

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: samsung galaxy A32
- CPU architecture: 
- Android version: 11
- PojavLauncher version: 3.3.1.1
_rel_20210125
```

### Anything else?

.

**Comment by SprainedSpark89** [comment]
more info?

**Comment by GoneSubject** [comment]
bruh

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build
