### ISSUE TITLE
Can't use 1.18

### ISSUE THREAD

**Issue by daguy2023** [PojavLauncherTeam/PojavLauncher#2386]
### Describe the bug

When i use pojavlauncher and try opening 1.17 or 1.18 it tells me that there is no compatible java runtime

### Steps To Reproduce

```markdown
1. Start pojavlauncher and sign in
2. Try opening 1.17
3. Get told that you can't play it
```

### Expected Behavior

The game to start normally

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GoneSubject** [comment]
yes because you didn't get java 17, [here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz) download it and go in PojavLauncher setting and find "runtime manager" then press add new and find that file and set it as default then you can play or just follow this [website](https://pojavlauncherteam.github.io/updates/117.html)

**Comment by Tarandeep001** [comment]
Not work

**Comment by GoneSubject** [comment]
> Not work

send the log then

**Comment by daguy2023** [comment]
It doesn't give me a log

**Comment by GoneSubject** [comment]
> It doesn't give me a log
.

with you i only i need you do this

> yes because you didn't get java 17, [here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz) download it and go in PojavLauncher setting and find "runtime manager" then press add new and find that file and set it as default then you can play or just follow this [website](https://pojavlauncherteam.github.io/updates/117.html)

**Comment by west-shell** [comment]
the latest version with virglerender works well

**Comment by JagdishPlayz9586** [comment]
java.lang.RuntimeException: Architecture arm is incompatible with Java Runtime x86.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)



Same issue here is log

**Comment by GaucovyAero** [comment]
> java.lang.RuntimeException: Architecture arm is incompatible with Java Runtime x86. at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43) at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725) at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36) at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552) at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2) at java.lang.Thread.run(Thread.java:919)
> 
> Same issue here is log

Install x86_64 runtime maybe?

**Comment by JagdishPlayz9586** [comment]
> 

Already tried it few days back but it didn't worked.
It says architecture arm is incompatible with Java runtime x84_64

**Comment by ghost** [comment]
> java.lang.RuntimeException: Architecture arm is incompatible with Java Runtime x86. at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43) at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725) at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36) at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552) at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2) at java.lang.Thread.run(Thread.java:919)
> 
> Same issue here is log

Ur using lambda hack client thats why it is crashing and also you have to use lambda as a forge mod i dont know if you were using lambda if you were using lambda try contacting the lambda development team

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build
