### ISSUE TITLE
[F-Req] Make other game directory

### ISSUE THREAD

**Issue by PastMC** [PojavLauncherTeam/PojavLauncher#2387]
### Is this request related to a bug?

You should to add in setings the change game directory this can fix problem: Operation not permitted
Change directory to this for all androids not with sdk29
![S11212-17104522](https://user-images.githubusercontent.com/52322048/145731032-3d9f767b-9fc0-4cce-8ead-e224843b6ff1.jpg)

 

### Describe the request.

Make custom setting to change standart game directory

### Anything else?

No.

**Comment by khanhduytran0** [comment]
This will break Play Store updates, as they require to set the target SDK level to almost (30) latest (31). Also, that’s how [scoped storage](https://developer.android.com/about/versions/11/privacy/storage) works. Not sure about the second directory.

**Comment by PastMC** [comment]
I modded apk PojavLauncher to second storage and he work stabile

**Comment by PastMC** [comment]
I make work example this
![S11213-16181867](https://user-images.githubusercontent.com/52322048/145828975-da41ccac-6873-4c2b-9759-8a46c8e3fa8b.jpg)

**Comment by ghost** [comment]
> I make work example this ![S11213-16181867](https://user-images.githubusercontent.com/52322048/145828975-da41ccac-6873-4c2b-9759-8a46c8e3fa8b.jpg)
Can you upload this apk file .

**Comment by khanhduytran0** [comment]
@PastMC If you want, per-version-config (PVC) existed for it already, just long-press onto the version selector.
