### ISSUE TITLE
[BUG] i cant play 1.18.1

### ISSUE THREAD

**Issue by Agamer10290** [PojavLauncherTeam/PojavLauncher#2389]
### Describe the bug

Application/Game exited with code -1

### The log file and images/videos

![Screenshot_20211213-085421_Text Editor](https://u
![Screenshot_20211213-085220_Text Editor](https://user-images.githubusercontent.com/89959453/145758369-bb700159-250a-49dc-a6cc-1de16b93d818.jpg)
ser-images.githubusercontent.com/89959453/145758193-70882059-e287-4a10-b641-9a7565c30bd5.jpg)
![Screenshot_20211213-085429_Text Editor](https://user-images.githubusercontent.com/89959453/145758257-7c586fc7-1770-4a70-82fb-a24f087af55c.jpg)
![Screenshot_20211213-085437_Text Editor](https://user-images.githubusercontent.com/89959453/145758312-05bb6855-9ce1-4b67-a16c-5e250c4c02dd.jpg)
![Screenshot_20211213-085157_Text Editor](https://user-images.githubusercontent.com/89959453/145758313-419d4377-fe99-409f-94d6-719be9cf4b35.jpg)
![Screenshot_20211213-085445_Text Editor](https://user-images.githubusercontent.com/89959453/145758384-88a13d33-1ad7-4c67-bb3c-7030741e0556.jpg)
![Screenshot_20211213-085404_Text Editor](https://user-images.githubusercontent.com/89959453/145758400-2ebb5c96-dc65-45f4-a4ef-7e2d9a698bd5.jpg)
![Screenshot_20211213-085455_Text Editor](https://user-images.githubusercontent.com/89959453/145758415-e5f3e698-3f35-45de-809a-b0522e3ca67d.jpg)
![Screenshot_20211213-085412_Text Editor](https://user-images.githubusercontent.com/89959453/145758432-e9b62ddc-3c93-43ec-a405-66ad72c98482.jpg)
![Screenshot_20211213-085632_Text Editor](https://user-images.githubusercontent.com/89959453/145758456-4db3d2f4-a824-4dc1-82dd-c774ae223da6.jpg)
![Screenshot_20211213-085421_Text Editor](https://user-images.githubusercontent.com/89959453/145758482-c09bac7b-9b2b-40be-848d-1e116fb67a20.jpg)
![Screenshot_20211213-085644_Text Editor](https://user-images.githubusercontent.com/89959453/145758491-dd8c7563-1ec0-42af-90db-624461dad407.jpg)
![Screenshot_20211213-085429_Text Editor](https://user-images.githubusercontent.com/89959453/145758610-7e01f565-b43b-44ff-a0a3-58d60d67803b.jpg)
![Screenshot_20211213-085437_Text Editor](https://user-images.githubusercontent.com/89959453/145758735-b83b0862-8a3b-499d-aedc-400446b62282.jpg)
![Screenshot_20211213-085445_Text Editor](https://user-images.githubusercontent.com/89959453/145758779-7bc4ae3b-7898-4b44-aff6-f0076474b740.jpg)
![Screenshot_20211213-085455_Text Editor](https://user-images.githubusercontent.com/89959453/145758812-23a4a23a-0d61-4288-9fd9-0d670d4f813c.jpg)
![Screenshot_20211213-085632_Text Editor](https://user-images.githubusercontent.com/89959453/145758845-93c7598a-5dae-4b3c-b2ab-9dc78ebab74d.jpg)
![Screenshot_20211213-085644_Text Editor](https://user-images.githubusercontent.com/89959453/145758908-4fc3a1df-5d0c-4288-b258-a6d0a5b96882.jpg)
![Screenshot_20211213-085652_Text Editor](https://user-images.githubusercontent.com/89959453/145758950-dafb7421-c012-4e0e-8d9e-20725398dabb.jpg)

### Steps To Reproduce

```markdown
I started 1.18.1 and downloaded it then chose java 17 and it wasent working
```

### Expected Behavior

1.18.1 work

### Platform

```markdown
- Device model: SM-A307FN
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: google play
```

### Anything else?

No

**Comment by Agamer10290** [comment]
Can sombody help me fix it?

**Comment by drehMC** [comment]
> Alguém pode me ajudar a consertar?

I also have this bug

**Comment by west-shell** [comment]
ignore it.just install fabric.then they work both.

**Comment by Agamer10290** [comment]
> ignore it.just install fabric.then they work both.
It dident work

**Comment by GoneSubject** [comment]
> > ignore it.just install fabric.then they work both.
> > It dident work

you should send the latestlog not just screenshots because they maybe missing some stuff

**Comment by khanhduytran0** [comment]
@Agamer10290 hey, why did you screenshot every piece of log? Why don't you just send the raw file here? Screenshots take a lot more storage than a raw txt file, also no dark mode if needed. Imagine if the latestlog.txt is 1mb, how long will you screenshot the whole of them?

**Comment by GoneSubject** [comment]
> @Agamer10290 hey, why did you screenshot every piece of log? Why don't you just send the raw file here? Screenshots take a lot more storage than a raw txt file, also no dark mode if needed. Imagine if the latestlog.txt is 1mb, how long will you screenshot the whole of them?

the screenshots was loading and i try to read your text but everytime i scroll down to the text another screenshot loaded

**Comment by west-shell** [comment]
use the latest version with virglrwnder.other.renders all fail

**Comment by GoneSubject** [comment]
> use the latest version with virglrwnder.other.renders all fail

why virgl

**Comment by khanhduytran0** [comment]
> use the latest version with virglrwnder.<ins>other.renders all fail</ins>

> why virgl

**Comment by GoneSubject** [comment]
> > use the latest version with virglrwnder.other.renders all fail
> 
> > why virgl

yea i know

**Comment by khanhduytran0** [comment]
`+118android` moment
https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04
