### ISSUE TITLE
Is that because jar2dex haven't updated for a long time?

### ISSUE THREAD

**Issue by MCredbear** [PojavLauncherTeam/PojavLauncher#239]
Unable to convert library org.lwjgl:lwjgl:3.2.1
processing archive /storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/INDEX.LIST...
writing META-INF/INDEX.LIST; size 554...
processing META-INF/MANIFEST.MF...
processing META-INF/versions/...
writing META-INF/versions/; size 0...
processing META-INF/versions/10/...
writing META-INF/versions/10/; size 0...
processing META-INF/versions/10/org/...
writing META-INF/versions/10/org/; size 0...
processing META-INF/versions/10/org/lwjgl/...
writing META-INF/versions/10/org/lwjgl/; size 0...
processing META-INF/versions/10/org/lwjgl/system/...
writing META-INF/versions/10/org/lwjgl/system/; size 0...
processing META-INF/versions/10/org/lwjgl/system/MathUtil.class...

PARSE ERROR:
unsupported class file version 54.0
...while parsing META-INF/versions/10/org/lwjgl/system/MathUtil.class
1 error; aborting
Exiting with code 1

(by the way,I can't convert minecraft's .jar above 1.8.x with dx.jar on my system.QAQ)

**Comment by khanhduytran0** [comment]
It's LWJGL3 meaning it's Minecraft 1.13 or above.

**Comment by MCredbear** [comment]
> It's LWJGL3 meaning it's Minecraft 1.13 or above.

I know that,so what caused it?Can I fix it by compiling lwjgl with ndk toolchain?

**Comment by khanhduytran0** [comment]
Not easy as you said, porting is required.

**Comment by khanhduytran0** [comment]
So i ported, it's in v3.
