### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by ja477** [PojavLauncherTeam/PojavLauncher#2391]
### Describe the bug

I can't install optifajna

### The log file and images/videos

![Screenshot_2021-12-13-22-47-21-421_net kdt pojavlaunch](https://user-images.githubusercontent.com/84819012/145894670-5539c8e0-05e3-4ec7-9762-78b459b22022.jpg)

### Steps To Reproduce

```markdown
H
```

### Expected Behavior

H

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

H

**Comment by NotAHero04** [comment]
It looks like a very old build. Update your launcher.

**Comment by InfiniXDerg** [comment]
How old are u, due the typing
