### ISSUE TITLE
[Skin system in pojav] 

### ISSUE THREAD

**Issue by LopZinX** [PojavLauncherTeam/PojavLauncher#2392]
### Is this request related to a bug?

it's not about bugs but a feature they could add would be the system to choose skins for offline accounts and original accounts.

### Describe the request.

the skin system for pojav could be added for offline and original accounts could also be added and the installation of jar feature Iris and sodium why when i try to install the bug

### Anything else?

not only these things that I pointed out above

**Comment by GoneSubject** [comment]
welp some servers can show the skin of offline accounts but some not

**Comment by LightestMC** [comment]
For premium accounts, you can change the skin on [minecraft.net](https://www.minecraft.net/en-us/profile) 

For offline accounts, you can rename your current skin image to `steve.png`, go to the version jar file you want the skin to be in, put it on `assets/minecraft/textures/entity` 

Note: **This only applies to the version you've put the skin image in. Mods/Users that uses the steve skin may look like the skin you use.**

**Comment by LightestMC** [comment]
It is currently possible to use your own skin on both account types but yeah, it would be cool if you can just change it through the launcher easily.

**Comment by khanhduytran0** [comment]
Offline mode is planned to be removed in the near future. For "premium" accounts, just go to https://minecraft.net/en-us/profile/skin
Adding a built-in skin changer for online account requires the following things:
- Security Questions validation
- ~~Optional:~~ A 3D Skin Viewer; which then many people will request for it.

**Comment by Lolplays112** [comment]
I WANT SKIN POJAV

**Comment by Lolplays112** [comment]
Lol
