### ISSUE TITLE
[F-Req] SD-Card support

### ISSUE THREAD

**Issue by RaydanOMGr** [PojavLauncherTeam/PojavLauncher#2394]
### Is this request related to a bug?

People sometimes don't have enough storage space to use pojav fully

### Describe the request.

SD-Card support
For example: A button in the settings which would allow to switch between Internal and External Storage

### Anything else?

Nothing else.

**Comment by WesleyVanNeck** [comment]
that would be indeed nice

**Comment by artdeell** [comment]
Just use Android's own settings menu to move the app to SD

**Comment by CriticalRange** [comment]
> Just use Android's own settings menu to move the app to SD

Portable storage better, change my mind
(Via APPS2SD)

**Comment by RaydanOMGr** [comment]
> Just use Android's own settings menu to move the app to SD

Fun fact: The option isn't available to pojav for some reason

**Comment by WesleyVanNeck** [comment]
@artdeell  not all phone have that issue also the data like obb and data on some app dont get on the sdcard

**Comment by OG-GaryYT** [comment]
![Screenshot_20211215-100439_AppMgr III](https://user-images.githubusercontent.com/86944088/146123898-e0b86363-43da-43c9-8df8-162abee4f836.png)

currently not possible i guess ¯\_(ツ)_/¯

**Comment by RaydanOMGr** [comment]
when

**Comment by Mathias-Boulay** [comment]
Adoptable storage is now supported codebase wise, closing
