### ISSUE TITLE
Black Text/Textures bug In Labymod

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#2395]
### Describe the bug

The Game Turn Suddenly Black!

https://user-images.githubusercontent.com/79517194/146104345-be73a74b-490d-44c9-996b-53aba64a4243.mp4

### Steps To Reproduce

```markdown
1-Start Pojavlauncher
2-Play The Game Normally
```

### Expected Behavior

The Game Should Be Normal

### Platform

```markdown
- Device model: Huawei Nova 3i
- CPU architecture: 8
- Android version: 9
- PojavLauncher version: Latest GP build
```

**Comment by GoneSubject** [comment]
fast render should be turn off i think

**Comment by ghost** [comment]
use 1.12 instead of 1.16.5

**Comment by khanhduytran0** [comment]
Lacks of latestlog.txt moment.

**Comment by Mathias-Boulay** [comment]
Either fixed, either impossible to fix
