### ISSUE TITLE
[BUG] Mouse stuck when installing forge

### ISSUE THREAD

**Issue by StxllarPlanes** [PojavLauncherTeam/PojavLauncher#2396]
### Describe the bug

When attempting to install forge, the mouse is stuck and unable to move to select any options.

### Steps To Reproduce

```markdown
1. Attempt to install any forge version
2. The bug is reproduced
```

### Expected Behavior

I expect to be able to move my mouse to install forge.

### Platform

```markdown
- Device model: Samsung Galaxy A32 
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

I checked my mouse speed and it is NOT set to 0.

**Comment by GoneSubject1** [comment]
i think you should update your pojavlauncher to the latest i think

**Comment by StxllarPlanes** [comment]
Update: For some strange reason, I can move the mouse for a very brief moment when I turn on the screen recorder.

**Comment by GoneSubject** [comment]
hm i think update your launcher to the latest build?

**Comment by StxllarPlanes** [comment]
> hm i think update your launcher to the latest build?

I have the playstore version of this, which seems to be stated as the latest version.

**Comment by khanhduytran0** [comment]
This is known to be an issue on Samsung devices. Try using latest build, if still not working, disable mouse.

**Comment by StxllarPlanes** [comment]
> This is known to be an issue on Samsung devices. Try using latest build, if still not working, disable mouse.

Where can I find the latest build?

**Comment by khanhduytran0** [comment]
The latest build can be found in the Actions tab.

**Comment by StxllarPlanes** [comment]
Thank you! The latest build no longer has this issue!
