### ISSUE TITLE
[F-Req] Add toggle for mouse cursor befor the outset of the game

### ISSUE THREAD

**Issue by Sumrak-Sumarokov** [PojavLauncherTeam/PojavLauncher#2399]
### Is this request related to a bug?

No

### Describe the request.

Add specific button for mouse toggle to Controll Customization. I know that mouse toggle button already exists as on screen button, but it would be much much more comfortable if there was an option for mouse toggle before the outset of the game

### Anything else?

Brub

**Comment by GoneSubject** [comment]
uh it just launch the game and turn on the mouse it's not a big deal

**Comment by Sumrak-Sumarokov** [comment]
Yes, but it would be more convenient

**Comment by GoneSubject** [comment]
idk maybe they will add it

**Comment by Mathias-Boulay** [comment]
Done.
Like, right now.
