### ISSUE TITLE
the icons of the worlds makes them unplayable (1.11)

### ISSUE THREAD

**Issue by jrxohan** [PojavLauncherTeam/PojavLauncher#24]
A new bug I have found because when playing or creating a world when playing it for a certain time, it creates as a miniature that, after all, is the icon because when it is created, I do not know that when it enters that world again, it does not load  new and it is a bug that makes the game little enjoyable and a little annoying and I don't know if it can be fixed, if you don't understand a video here
https://youtu.be/QBlvnN1NoiA

**Comment by khanhduytran0** [comment]
I found a crash report in you video, that is the problem made you stuck at **empty dirt screen**
![Screenshot_2020-03-31-05-37-09](https://user-images.githubusercontent.com/40482367/77968672-21174480-7312-11ea-9a77-7a9589b4eb0a.png)

**Comment by khanhduytran0** [comment]
For some reasons, crash dialog didn't show after Minecraft complete create a crash report.

**Comment by jrxohan** [comment]
> I found a crash report in you video, that is the problem made you stuck at **empty dirt screen**
> ![Screenshot_2020-03-31-05-37-09](https://user-images.githubusercontent.com/40482367/77968672-21174480-7312-11ea-9a77-7a9589b4eb0a.png)

This is the full crash report


---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 30/3/20 4:47 p. m.
Description: Exception in server tick loop

java.lang.NoSuchMethodError: No static method write(Ljava/awt/image/RenderedImage;Ljava/lang/String;Ljava/io/OutputStream;)Z in class Ljavax/imageio/ImageIO; or its super classes (declaration of 'javax.imageio.ImageIO' appears in base.apk)
	at net.minecraft.server.MinecraftServer.a(SourceFile:520)
	at net.minecraft.server.MinecraftServer.run(SourceFile:443)
	at java.lang.Thread.run(Thread.java:784)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Linux (aarch64) version 4.9.148
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (null), The Android Project
	Memory: 14502272 bytes (13 MB) / 136924840 bytes (130 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'

**Comment by khanhduytran0** [comment]
Wait a bit

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.8b1

**Comment by jrxohan** [comment]
> https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.8b1

Thanks now the issue is solved...
