### ISSUE TITLE
[BUG] Can't Run Minecraft 1.4.6

### ISSUE THREAD

**Issue by 1493028** [PojavLauncherTeam/PojavLauncher#2400]
### Describe the bug

The Mojang logo doesn't appear. I've waited 10 minutes but it still doesn't appear

### Steps To Reproduce

```markdown
1. start my Pojav launcher
2. I install version 1.4.6 (i not skip the download)
3. Mojnag logo not apprears
```

### Expected Behavior

The game not start

### Platform

```markdown
- Device model: Oppo A54
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version:(github) fix moment
```

### Anything else?

Nothing

**Comment by NotAHero04** [comment]
Please provide a valid log.

**Comment by khanhduytran0** [comment]
It's been 2 weeks, still no log provided. Assuming that you've set Java 17 as default, 1.5.2 and below won't work. Closing.
