### ISSUE TITLE
[F-Req] old controls backing option

### ISSUE THREAD

**Issue by gyojalal** [PojavLauncherTeam/PojavLauncher#2401]
### Is this request related to a bug?

No

### Describe the request.

Please old controls rollbacking options
Example controls keyboard:
![Screenshot_2021-12-15-21-48-22-658_com google android youtube](https://user-images.githubusercontent.com/72719597/146189624-cfedbb2e-9106-4fb4-b171-1bea93ec71f7.jpg)

**Comment by gyojalal** [comment]
Old controls including version is pojavlauncher 3.2

**Comment by GoneSubject** [comment]
welp i think the new control is better

**Comment by Mathias-Boulay** [comment]
You can personalise controls on the custom controls menu
