### ISSUE TITLE
Osmesa-dev-tests

### ISSUE THREAD

**Issue by Indiandream26** [PojavLauncherTeam/PojavLauncher#2402]
### Is this request related to a bug?

This issue is of shaders not working. 

### Describe the request.

Please give the app which can run shader like:- bsl shaders, complementary shaders, chopaic shaders, etc. And please fix the render zink vulkan in the app that which is not supported, fix the error of crashing the game when the world starts.

**Comment by khanhduytran0** [comment]
> Please give the app which can run shader like:- bsl shaders, complementary shaders, chopaic shaders, etc.

What about SEUS PTGI E12?

**Comment by Indiandream26** [comment]
What about 'etc'

**Comment by khanhduytran0** [comment]
What about inserting RTX 3090 into your phone? Yeah, that’s the problem. Your phone doesn’t have a RTX 3090, Intel (U)HD GPU, or AMD Radeon GPU for running Desktop shaders.

**Comment by khanhduytran0** [comment]
**Limit is limit**. Zink has never been designed for mobile GPUs. Luckily, only Mali GPUs are known to compatible with most shaders; Adreno is known to be compatible with [Nostalgia shader](https://www.curseforge.com/minecraft/customization/nostalgia-shader).
Therefore, think about the limit first.
