### ISSUE TITLE
[BUG] <Items bug>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2403]
### Describe the bug

this bug has been found on versions 1.8 to 1.10  

When we hit a mob or break a block it will automatically change the blocks and items like flowers with a square  background with the color of the block (look in the picture)

This only happens when we hit a block or a mob.

I have tested it on other minecraft launcher this bug was not found there.

### The log file and images/videos

![2021-12-16_04 28 14](https://user-images.githubusercontent.com/92659252/146308901-f4068f70-5b6c-43a8-8df3-e001a17af4ea.png)

### Steps To Reproduce

```markdown
1 if you launcher version 1.8 to 1.12 on minecraft launcher
```

### Expected Behavior

https://user-images.githubusercontent.com/92659252/146309757-6bafb9f4-4ad9-4b7d-a30d-a54772ac3af9.mp4

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GoneSubject** [comment]
no platform info

**Comment by NotAHero04** [comment]
Use gl4es 1.1.4 renderer for those versions.

**Comment by ghost** [comment]
> no platform info
chromebook  8gb of ram intel i3
