### ISSUE TITLE
[Error] Error : could not find libjava.so

### ISSUE THREAD

**Issue by raj-extremegamerz** [PojavLauncherTeam/PojavLauncher#2404]
### Describe the bug

When i am launching minecraft 1.18.1 jre 17 
I face this error

Error : Could not find libjava.so
Error : Could not find Java SE Runtime Environment.

Please help me to fix this.

### Steps To Reproduce

```markdown
Launching minecraft 1.18.1
```

### Expected Behavior

Crash every time

### Platform

```markdown
- Device model: Oppo
- CPU architecture: arm
- Android version: 5.1.1
- PojavLauncher version: crocus-v3_openjdk
- Ram: 2GB
```

**Comment by aaaapai** [comment]
Reload Java?

**Comment by GoneSubject** [comment]
> Reload Java?

you mean redownload runtime?

**Comment by aaaapai** [comment]
yes发自我的荣耀手机-------- 原始邮件 --------发件人： GoneSubject ***@***.***>日期： 2021年12月16日周四 晚上10:50收件人： PojavLauncherTeam/PojavLauncher ***@***.***>抄送： aaaapai ***@***.***>, Comment ***@***.***>主    题： Re: [PojavLauncherTeam/PojavLauncher] [Error] Error : could not find libjava.so (Issue #2404)

Reload Java?

you mean redownload runtime?

**Comment by GoneSubject** [comment]
idk try it then

**Comment by raj-extremegamerz** [comment]
I tried reload java 17 and many ways but not works.

**Comment by tigerbrocode** [comment]
Send latest log

**Comment by GoneSubject** [comment]
> Send latest log

i don't think the log can help

**Comment by khanhduytran0** [comment]
> > Send latest log
> 
> i don't think the log can help

The log contains everything needed for debugging, not just the game log.

**Comment by GoneSubject** [comment]
> > > Send latest log
> > 
> > i don't think the log can help
> 
> The log contains everything needed for debugging, not just the game log.

oh ok

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build
