### ISSUE TITLE
[F-Req] Dragging in guis

### ISSUE THREAD

**Issue by Blue-Beaker** [PojavLauncherTeam/PojavLauncher#2405]
### Is this request related to a bug?

Can't drag mouse in GUIs

### Describe the request.

Add mode switch button for touchscreen in gui: click, drag, hover, LMB/RMB
the click mode behaves like now
In the drag mode the launcher will translate every touchscreen drags to LMB drags like playing MCJE on a windows device with touchscreen
In the hover mode the LMB click only happens when the player press the Pri button.
The LMB/RMB button switches between the mouse button simulated on touchscreen click. Can also be bounded to another keys.

**Comment by khanhduytran0** [comment]
There’s no need for a switch. We can just implement the hold-mode when the finger is long-pressed.

**Comment by Mathias-Boulay** [comment]
I couldn't agree more on this, I'll look into it once I get all those duplicate issues removed

**Comment by artdeell** [comment]
Fixed in latest action builds. Now touchscreen is dragging by default.
