### ISSUE TITLE
Hacer funcione simple voice chat[F-Req] <Short description>

### ISSUE THREAD

**Issue by Nsnndndndndjfj** [PojavLauncherTeam/PojavLauncher#2409]
### Describe the request.

Que habiliten l si pueden hacer algo para que pueda usarse simple voice chat para que se pueda hablar por micrófono o por algo parecido

**Comment by ghost** [comment]
i think  you need voice chat support 
Use labbymod along with pojavlauncher .

Labby mod provides voice chat support.  (use version 1.12 on labbymod)

toutorial
https://youtu.be/xb768MDnYsI
