### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Catts1** [PojavLauncherTeam/PojavLauncher#241]
I just want to run java 1.14.4, I Have a rooted android 9. What do i need for it?

**Comment by Catts1** [comment]
I tried all day but i just got crashes and errors

**Comment by khanhduytran0** [comment]
Did you read description carefully???
> Support up-to Minecraft 1.11.2
(Also replied on Discord)

**Comment by khanhduytran0** [comment]
> Is this project still alive?

Still, but we moved development to Discord #development channel.

**Comment by khanhduytran0** [comment]
@MatthewXTR use v3 so 1.14.4 will work.
