### ISSUE TITLE
[F-Req] resume support for vgpu opengl 4

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2410]
### Is this request related to a bug?

. 

### Describe the request.

Resume support for vgpu opengl 4

### Anything else?

.

**Comment by EncryptedLeaFy** [comment]
You can use virgl or zink if you want opengl 4.3 (virgl) or 4.6 (zink)

**Comment by Iarkont** [comment]
> You can use virgl or zink if you want opengl 4.3 (virgl) or 4.6 (zink)

Zink lags a lot, VirGL does not launch shaders and some necessary mods

**Comment by NotAHero04** [comment]
VirGL's shader support is nearly done

**Comment by WesleyVanNeck** [comment]
Not up to us to get vgpu for opengl 4.0

**Comment by khanhduytran0** [comment]
You can’t expect these stuff from us, as we have never said that we were vgpu developers.
