### ISSUE TITLE
[BUG] Game crashes with error code -1 when opening 1.18

### ISSUE THREAD

**Issue by NidaleNieve** [PojavLauncherTeam/PojavLauncher#2412]
### Describe the bug

Whenever I try to launch Minecraft 1.18 or 1.18.1 The game opens shows me the Mojang logo for a short time and then crashes with the error code -1
![Screenshot_2021-12-17-17-47-30-950_net kdt pojavlaunch](https://user-images.githubusercontent.com/62642672/146587054-2669f796-8b26-4cb7-ab99-85f1d8d69d8e.jpg)
Note: I downloaded Java 17 and the resource pack trough your Got Hub page. Previous version work just fine

This also happens when trying to install optifine 1.18 or 1.18.1
![Screenshot_2021-12-17-17-47-56-896_net kdt pojavlaunch](https://user-images.githubusercontent.com/62642672/146587252-90a457e4-83a0-4909-a659-39b4b03fca15.jpg)
It works just fine when trying to Install older versions though

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7736918/latestlog.txt)

### Steps To Reproduce

```markdown
Open Minecraft 1.18
```

### Expected Behavior

It opens the game and shows me the title screen

### Platform

```markdown
- Device model: Poco F3
- CPU architecture: Arm64
- Android version: Android 11
- PojavLauncher version: Latest Version from play store
```

### Anything else?

I've tried uninstalling and reinstalling but still, nothing :(

**Comment by GoneSubject** [comment]
look like you didn't follow this: https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04

**Comment by NidaleNieve** [comment]
> look like you didn't follow this: https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04

I followed this, I even triple checked if I did something wrong. But still, I get the same error: -1

**Comment by NidaleNieve** [comment]
> look like you didn't follow this: https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04

It worked, I changed my rendered after what I did, and bamm it works

**Comment by GoneSubject** [comment]
> > look like you didn't follow this: https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04
> 
> It worked, I changed my rendered after what I did, and bamm it works

ok

**Comment by tigerbrocode** [comment]
Close this now
