### ISSUE TITLE
[BUG] Crash and no crash report

### ISSUE THREAD

**Issue by eriiknn** [PojavLauncherTeam/PojavLauncher#2414]
### Describe the bug

Hey,
I am experiencing a bug in any Minecraft Version. When I start the game and its loading the chunks my game just crashes. No Error Code, nothing. It just crashes in the Login Screen. 
 The Phone i am using is the Samsung Galaxy S10e.

I hope someone has an idea :). 
Have a nice day! 

### Steps To Reproduce

```markdown
1. Start the PojavLauncher
2. Start any Game Version
3. Load into a World
4. Crash
```

### Expected Behavior

Just a crash with no crash report that sends you back to the Login Menu.

### Platform

```markdown
- Device model: Samsung Galaxy S10e
- CPU architecture: 64 bit (i dont know what aarch really is)
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by khanhduytran0** [comment]
Please send latestlog.txt

**Comment by NdraaGaminz** [comment]
Maybe you try to use OptiFine or sodium or somethin' or your runtime is java17 and try to launch 1.7-1.13, and renderer doenst support your device?...OR, you import some minecraft version file into the versions pojav data file so its gonna crash, i tried like that (importing some random Minecraft file, like LunarClient and labymod) it crash when i try to launch it

**Comment by NdraaGaminz** [comment]
If all of that is not Helping you, your device is not support 

> Maybe you try to use OptiFine or sodium or somethin' or your runtime is java17 and try to launch 1.7-1.13, and renderer doenst support your device?...OR, you import some minecraft version file into the versions pojav data file so its gonna crash, i tried like that (importing some random Minecraft file, like LunarClient and labymod) it crash when i try to launch it

**Comment by Illia24** [comment]
why minecraft crashing on forge 1.17.1/1.18.1??

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build
