### ISSUE TITLE
[BUG] virglrenderer incorrectly places the game

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2415]
### Describe the bug

![Screenshot_20211218_160044_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/146642180-a74051c3-0639-4c4d-96b8-534d0b1769b6.jpg)

### The log file and images/videos

The game is turned upside down when you run on virglrenderer. There is no error on other renderings. 

### Steps To Reproduce

```markdown
1. Launched by Pojavlauncher 
2. Chose version 1.16.5 optifine 
3. Selected Java 1.8.0
4. Chose virglrenderer
5. Launched minecraft
```

### Expected Behavior

. 

### Platform

```markdown
- Device model: honor 9c AKA-L29 4/64
- CPU architecture: aarch 64 
- Android version: 10
- PojavLauncher version: a530e72 v3_openjdk
```

### Anything else?

.

**Comment by GoneSubject** [comment]
why virgl render

**Comment by WesleyVanNeck** [comment]
know issue

**Comment by GoneSubject** [comment]
i think turn off Fbo?
