### ISSUE TITLE
[BUG] Incompatible Java Runtime

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2418]
### Describe the bug

Every time I use the `fabric-loader-0.12.12-1.18.1` a pop-up tells me: **Can't find any compatible Java Runtime**

### The log file and images/videos

[Mods.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7740094/archive.zip)
[Droid Info Report.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7740122/Droid.Info.Report.txt)

### Steps To Reproduce

```markdown
1. Download fabric installer.
2. Open ProjevLancher.
3. Click options and install fabric on version 0.12.12 and in 1.18.1.
4. Unzip the mods and put the in the mods folder.
5. Try to run the profile.
```

### Expected Behavior

I expected the game to launch.

### Platform

```markdown
- Device model: V350C (v350c)
- CPU architecture: AArch64 Processor rev 2 (aarch64)
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

[Tutorial](https://m.youtube.com/watch?v=qQ-eRB3Css8)

**Comment by GoneSubject** [comment]
you must download [jre17](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz)

**Comment by Errorbot1122** [comment]
What do I do now...

**Comment by GoneSubject** [comment]
> What do I do now...

go to PojavLauncher setting and find runtime manager press that and then add new then find the file that you downloaded and then set it as default then play

**Comment by khanhduytran0** [comment]
No response moment.

**Comment by ghost** [comment]
> No response moment.
