### ISSUE TITLE
Error. PojavLauncher 2.5 preview 1

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#242]
When I get on minecraft there is such a error
"Unable to fix RSAPadding. You can't play premium servers.

**Comment by artdeell** [comment]
That's just a warning, not an error.

**Comment by Doxelix** [comment]
Okk

**Comment by martiparti** [comment]
When I try to download 1.16.1 it says
Unable to convert library org.lwjgl:lwjgl:3.2.1
processing archive /storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/INDEX.LIST...
writing META-INF/INDEX.LIST; size 554...
processing META-INF/MANIFEST.MF...
processing META-INF/versions/...
writing META-INF/versions/; size 0...
processing META-INF/versions/10/...
writing META-INF/versions/10/; size 0...
processing META-INF/versions/10/org/...
writing META-INF/versions/10/org/; size 0...
processing META-INF/versions/10/org/lwjgl/...
writing META-INF/versions/10/org/lwjgl/; size 0...
processing META-INF/versions/10/org/lwjgl/system/...
writing META-INF/versions/10/org/lwjgl/system/; size 0...
processing META-INF/versions/10/org/lwjgl/system/MathUtil.class...

PARSE ERROR:
unsupported class file version 54.0
...while parsing META-INF/versions/10/org/lwjgl/system/MathUtil.class
1 error; aborting
Exiting with code 1

**Comment by nicknickeryt** [comment]
@martiparti PojavLauncher (V2) supports Minecraft up to 1.11.2. It's clearly written on readme page...

**Comment by khanhduytran0** [comment]
@dawid5635 use @.LegacyGamerHD changed API level build or v3 for join premium server.

@martiparti use v3.
