### ISSUE TITLE
[BUG] Class File Major Version

### ISSUE THREAD

**Issue by kl1024** [PojavLauncherTeam/PojavLauncher#2420]
### Describe the bug

I tried to run 1.18.1 with fabric loader 0.12.2 and it reported "java.lang.IllegalArgumentException: Unsupported class file major version 21845" when initializing game

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.start fabric-loader-0.12.2-1.18
3.exited with code 1
```

### Expected Behavior

i expect the game launches

### Platform

```markdown
- Device model: Mi Note 3
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-296-a530e7250-v3_openjdk
```

**Comment by NotAHero04** [comment]
Please provide a valid log.

**Comment by khanhduytran0** [comment]
It’s been 2 weeks and still no log provided, closing until further response.

**Comment by kl1024** [comment]
> Please provide a valid log.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7833191/latestlog.txt)

**Comment by Henry-Hiles** [comment]
I have exactly the same problem. Log: 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7859261/latestlog.txt)

**Comment by khanhduytran0** [comment]
I wonder why there’s class major version 21845..

anyways, what about the mod list?


#1948 moment

**Comment by Henry-Hiles** [comment]
No mods for me.

**Comment by Henry-Hiles** [comment]
Tried on a recent debug version, same error.

**Comment by Henry-Hiles** [comment]
BTW you can reach me in the pojav discord server if I don't respond quickly, QuadRadical#0001

**Comment by Henry-Hiles** [comment]
Could the issue stem from this when installing fabric? 
![Screenshot_20220114-091048879 (1)](https://user-images.githubusercontent.com/71790868/149530025-7d51e35c-708a-4b59-90d8-e5900e908ca3.jpg)


Or possibly this when i run fabric? 
![Screenshot_20220114-091440682 (1)](https://user-images.githubusercontent.com/71790868/149530095-06a465b6-4082-4398-81aa-4a4cf2fd1831.jpg)

**Comment by Henry-Hiles** [comment]
Just found this: https://stackoverflow.com/questions/68108265/java-lang-illegalargumentexception-unsupported-class-file-major-version-59 . Maybe it's the same problem?

**Comment by khanhduytran0** [comment]
That's about version 59, not 21845.

**Comment by Henry-Hiles** [comment]
Yes, i just thought it might be somewhat related.

**Comment by kl1024** [comment]
It repaired magically after I flashed my system...maybe there is something wrong with crdroid.

**Comment by Henry-Hiles** [comment]
Could this please be reopened? It is still a problem to people who cannot flash a new rom. (Btw if it helps im on CorvusOS)

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build

**Comment by Rasyamb** [comment]
> It repaired magically after I flashed my system...maybe there is something wrong with crdroid.

what y flashing?
the rom update/down or smting else?
