### ISSUE TITLE
Auto show control!

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2421]
### Describe the request.

I suggest adding a mechanic to the launcher that will show the controls when the player enters the world! And if you are in the game in the main menu, then the controls will not be shown(Even the button gui and a show mouse button!) Please implement this!

**Comment by GoneSubject** [comment]
some people may need to show the control in the menu

**Comment by andr0d1v** [comment]
Do it as a special option! Which will be in the launcher settings

**Comment by GoneSubject** [comment]
idk i think it kinda useless to me

**Comment by andr0d1v** [comment]
How you want, everyone has their own opinion

**Comment by NotAHero04** [comment]
As I said, pressing GUI button will not take much of your energy. And it will give more control over the control system, so it can be useful for some cases like screenshoting.

**Comment by GoneSubject1** [comment]
for me i'm good with the current control

**Comment by aaaapai** [comment]
Looks like the other starters did it
