### ISSUE TITLE
[F-Req] Fabric or Forge built in

### ISSUE THREAD

**Issue by UniqueName12345** [PojavLauncherTeam/PojavLauncher#2422]
### Is this request related to a bug?

It is not a bug, but I am too lazy to download a jar file, and do all that. 

### Describe the request.

I think you can go the ATlauncher route and when downloading a version, say "Install with Fabric, Forge or Vanilla?". Also include the mod "Mod Menu", and a mod selector for both Curseforge mods, and Modrinth mods. (sans the incompatible mods, ofc). 

### Anything else?

Maybe make it an option in the settings bar.

**Comment by khanhduytran0** [comment]
With Forge, there's a problem
> Please do not automate the download and installation of Forge.
> Our efforts are supported by ads from the download page.
> If you MUST automate this, please consider supporting the project through https://www.patreon.com/LexManos/

**Comment by UniqueName12345** [comment]
> With Forge, there's a problem
> > Please do not automate the download and installation of Forge.
> > Our efforts are supported by ads from the download page.
> > If you MUST automate this, please consider supporting the project through https://www.patreon.com/LexManos/

Just do Fabric then.

**Comment by Mathias-Boulay** [comment]
let's not make pojav fat as fuck

**Comment by UniqueName12345** [comment]
Okay then.
