### ISSUE TITLE
[BUG] Controller Attacking and Placing

### ISSUE THREAD

**Issue by IlFANGlI** [PojavLauncherTeam/PojavLauncher#2423]
### Describe the bug

I cannot attacker place using the triggers on my controller, but everything else works completely fine. Please fix.

### Steps To Reproduce

```markdown
Start PoJavLauncher
Connect controller (bluetooth)
Try to punch or place
```

### Expected Behavior

I expect it to punch or place using the triggers.

### Platform

```markdown
- Device model: Samsung A42 5G
- CPU architecture: ARM
- Android version: 11, OneUI 3.1
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by LightestMC** [comment]
Java Edition doesn't support controller directly, install the [Controllable mod](https://www.curseforge.com/minecraft/mc-mods/controllable)

**Comment by artdeell** [comment]
Pojav doesn't support all controller mods

ср, 22 дек. 2021 г., 04:58 LightestMC ***@***.***>:

**Comment by Mathias-Boulay** [comment]
> Please fix.
Fixed on dev builds
