### ISSUE TITLE
Cuando pongo mod se ve pantalla negra[BUG] <Short description>

### ISSUE THREAD

**Issue by Nsnndndndndjfj** [PojavLauncherTeam/PojavLauncher#2425]
### Describe the bug

Cuando pongo mod la pantalla se ve negra y si pongo optifine se crashea si junto tal mod

### Steps To Reproduce

```markdown
-1
```

### Expected Behavior

Juegos se cerró -1

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by InfiniXDerg** [comment]
Necesitamos más información, en este caso el caso del problema será cerrado y etiquetado como inválido e incompleto
