### ISSUE TITLE
Que no se ponga pantalla negra con mods[F-Req] <Short description>

### ISSUE THREAD

**Issue by Nsnndndndndjfj** [PojavLauncherTeam/PojavLauncher#2426]
### Is this request related to a bug?

Cuando pones 1 solo mod algunos te ponen la pantalla negra pero el juego sigue funcionando

### Describe the request.

Que puedan solucionar ese error que describí anteriormente

### Anything else?

Que se crashea en veces optifine y otros mods

**Comment by InfiniXDerg** [comment]
Necesitamos más información como el dispositivo móvil, versión del Launcher, versión de Android, etc
Este caso será cerrado y etiquetado como inválido e incompleto, también como repetido

**Comment by khanhduytran0** [comment]
Invalid. Please fill into the bug form.
