### ISSUE TITLE
Microsoft login error

### ISSUE THREAD

**Issue by kaicryptx** [PojavLauncherTeam/PojavLauncher#2428]
### Describe the bug

Pojavlauncher team I got a hypixel account but i tried to Microsoft login but it's not working

### The log file and images/videos

![Screenshot_2021-12-20-10-04-43-73_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/89289445/146712606-7d7f69e4-242b-4a96-a63c-d607728d197e.jpg)
![Screenshot_2021-12-20-10-04-36-96_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/89289445/146712611-786d4680-968b-4be7-9c6e-aa39d9b1e0e4.jpg)

### Steps To Reproduce

```markdown
Please tell how I can solve
```

### Expected Behavior

Pojavlauncher team I got a hypixel account but i tried to Microsoft login but it's not working

### Platform

```markdown
- Device model: Realme C3
- CPU architecture: MT6769V/CB
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

Please tell me how I can solve

**Comment by kaicryptx** [comment]
@khanhduytran0

**Comment by ghost** [comment]
purchase minecraft

**Comment by InfiniXDerg** [comment]
Bhai NFA, invalid, close

**Comment by kaicryptx** [comment]
Thnx
