### ISSUE TITLE
Device randomly reboots

### ISSUE THREAD

**Issue by azequer** [PojavLauncherTeam/PojavLauncher#2429]
### Describe the bug

The device reboots after a few minutes of playing 1.16

### Steps To Reproduce

```markdown
1. Open Pojavlauncher
2. Download 1.16.5
3. Create a super flat world and play until your device reboots
```

### Expected Behavior

I expected that I could play it normally

### Platform

```markdown
- Device model: moto g (10) 
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

.

**Comment by khanhduytran0** [comment]
**Hey, you just opened the issue in the iOS repo. It is now transferred to the correct place**

Please describe more
- Is your device rooted? are you using any overclock app
- Does the RAM amount overflow?
- Check latestlog.txt

**Comment by azequer** [comment]
1.No, it's not rooted
2.No
3.--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.16.5
--------- beginning of main
--------- beginning of crash
I/jrelog  (12456): dlopen libxhook.so success
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1040
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~pjyd-lZBZt669fNyoCVt2g==/net.kdt.pojavlaunch-mfUylrNpaBxg8mVPxQGKSA==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=468
I/LIBGL   (12456): Initialising gl4es
I/LIBGL   (12456): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   (12456): Using GLES 2.0 backend
I/LIBGL   (12456): loaded: libGLESv2.so
I/LIBGL   (12456): loaded: libEGL.so
I/LIBGL   (12456): Using GLES 2.0 backend
I/LIBGL   (12456): Hardware Full NPOT detected and used
I/LIBGL   (12456): FBO are in core, and so used
I/LIBGL   (12456): PointSprite are in core, and so used
I/LIBGL   (12456): CubeMap are in core, and so used
I/LIBGL   (12456): BlendColor is in core, and so used
I/LIBGL   (12456): Blend Substract is in core, and so used
I/LIBGL   (12456): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (12456): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (12456): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (12456): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (12456): Extension GL_OES_depth24  detected and used
I/LIBGL   (12456): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (12456): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (12456): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (12456): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (12456): Extension GL_OES_texture_float  detected and used
I/LIBGL   (12456): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (12456): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (12456): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (12456): high precision float in fragment shader available and used
I/LIBGL   (12456): Max vertex attrib: 16
I/LIBGL   (12456): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (12456): Max texture size: 16384
I/LIBGL   (12456): Max Varying Vector: 31
I/LIBGL   (12456): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (12456): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (12456): Max Anisotropic filtering: 16
I/LIBGL   (12456): Max Color Attachments: 1 / Draw buffers: 1
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/LIBGL   (12456): Hardware vendor is Qualcomm
I/LIBGL   (12456): GLSL 300 es supported
I/LIBGL   (12456): GLSL 310 es supported and used
I/LIBGL   (12456): sRGB surface supported
I/LIBGL   (12456): EGLImage to Texture2D supported
I/LIBGL   (12456): EGLImage to RenderBuffer supported
I/LIBGL   (12456): ignore MipMap
I/LIBGL   (12456): Targeting OpenGL 2.1
I/LIBGL   (12456): NPOT texture handled in hardware
I/LIBGL   (12456): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (12456): try to use VBO
I/LIBGL   (12456): glX Will try to recycle EGL Surface
I/LIBGL   (12456): Current folder is:/
I/jrelog  (12456): dlopen libgl4es_114.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (12456): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (12456): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (12456): dlopen /data/app/~~pjyd-lZBZt669fNyoCVt2g==/net.kdt.pojavlaunch-mfUylrNpaBxg8mVPxQGKSA==/lib/arm64/libopenal.so success
I/jrelog  (12456): Done processing args
I/jrelog  (12456): Found JLI lib
I/jrelog  (12456): Calling JLI_Launch
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=12619
EGLBridge: EGLDisplay=0x1, EGLSurface=0x72fec1d4a0
EGLBridge: Created CTX pointer = 0x72fec20590
LWJGLX: ready-handle context created
java.lang.Exception: Trace exception
	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:1004)
	at org.lwjgl.opengl.ContextGL.makeCurrent(ContextGL.java:197)
	at org.lwjgl.opengl.Display.create(Display.java:419)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:91)

	at com.mojang.rubydung.RubyDung.init(RubyDung.java:62)

	at com.mojang.rubydung.RubyDung.run(RubyDung.java:104)

	at java.lang.Thread.run(Thread.java:748)
EGLBridge: Comparing: thr=12619, this=0x72fec20590, curr=0x0
EGLBridge: Making current on window 0x72fec20590 on thread 12619
EGLBridge: eglMakeCurrent() succeed!
72fec20590

LWJGLX: GL caps init
EGLBridge: Comparing: thr=12619, this=0x72fec20590, curr=0x72fec20590
Grab: false

GLFW: Set size for window 493900400016, width=1024, height=768

EGLBridge: Created CTX pointer = 0x72fec249a0
LWJGLX: ready-handle context created

java.lang.Exception: Trace exception

	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:1004)
	at org.lwjgl.opengl.ContextGL.makeCurrent(ContextGL.java:197)
	at org.lwjgl.opengl.Display.create(Display.java:419)
	at com.mojang.rubydung.RubyDung.init(RubyDung.java:65)
	at com.mojang.rubydung.RubyDung.run(RubyDung.java:104)
	at java.lang.Thread.run(Thread.java:748)

EGLBridge: Comparing: thr=12619, this=0x72fec249a0, curr=0x72fec20590
72fec20590

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.
java.io.FileNotFoundException: level.dat (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.mojang.rubydung.level.Level.load(Level.java:82)
	at com.mojang.rubydung.level.Level.<init>(Level.java:75)
	at com.mojang.rubydung.RubyDung.init(RubyDung.java:84)
	at com.mojang.rubydung.RubyDung.run(RubyDung.java:104)
	at java.lang.Thread.run(Thread.java:748)
--------- beginning of main
Grab: true

[1220/131133.367537:ERROR:elf_dynamic_array_reader.h(64)] tag not found
--------- beginning of crash

**Comment by tigerbrocode** [comment]
It's the ERROR:elf_dynamic_array_reader.h(64)] tag not found

**Comment by azequer** [comment]
Oh ok

**Comment by Mathias-Boulay** [comment]
Does the **WHOLE DEVICE** reboot ?

**Comment by HenryVV** [comment]
Quando início mundo ele cracha um pouco e volta para a página inicial do jogo

**Comment by azequer** [comment]
> Does the **WHOLE DEVICE** reboot ?

Yes

**Comment by Mathias-Boulay** [comment]
That's a first

**Comment by SprainedSpark89** [comment]
how much memory is allocated?

**Comment by azequer** [comment]
2gb

**Comment by SprainedSpark89** [comment]
try turning it down

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build
