### ISSUE TITLE
Forge on Pojav Launcher???

### ISSUE THREAD

**Issue by Malaska678** [PojavLauncherTeam/PojavLauncher#243]
I want forge for better for performance.
But forge is not supported. I know optifine 
Is Supported But it Don't Work On Some Device.
Pls add support for forge..☺️☺️☺️

**Comment by khanhduytran0** [comment]
Forge and many mods support are planned in v3. With v2 it will not easy to support for all mods and Forge.

**Comment by khanhduytran0** [comment]
We have a `Mod installer` option preview as in v3 Options menu.

**Comment by khanhduytran0** [comment]
> We have a `Mod installer` option preview as in v3 Options menu.

**Comment by Malaska678** [comment]
V3 is still Very Unstable. I try to install minecraft but it didnt work.

**Comment by khanhduytran0** [comment]
V3 will not work at the moment. If you want to see any news, development. Come to my discord server

**Comment by Malaska678** [comment]
Ok

**Comment by khanhduytran0** [comment]
https://discord.gg/YK76Wn

**Comment by BryleHelll** [comment]
What
