### ISSUE TITLE
[BUG] Game crash on 1.18

### ISSUE THREAD

**Issue by Kxsumi** [PojavLauncherTeam/PojavLauncher#2431]
### Describe the bug

The launcher won't launch 1.18 / 1.18.1

### The log file and images/videos
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7746545/latestlog.txt)

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7746544/latestcrash.txt)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Click on 1.18
3. Click Play
4. Wait for it to load.
5. It will crash before fully loading into menu.
```

### Expected Behavior

I expect for it to exist and load into the game.

### Platform

```markdown
- Device model: Lenovo S330
- CPU architecture: ARM64
- Android version: None?
- PojavLauncher version: Latest
```

### Anything else?

_No response

**Comment by GoneSubject** [comment]
pls send the log don't send the crash log and at least send the file don't send the whole things in the file

**Comment by Kxsumi** [comment]
> pls send the log don't send the crash log and at least send the file don't send the whole things in the file

Fixed

**Comment by GoneSubject** [comment]
did you followed [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)?

**Comment by Kxsumi** [comment]
> did you followed [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)?

That document file is inaccessible

**Comment by GoneSubject** [comment]
> > did you followed [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)?
> 
> That document file is inaccessible 

what do you mean?

**Comment by Kxsumi** [comment]
> > > did you followed [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)?
> > 
> > 
> > That document file is inaccessible
> 
> what do you mean?

Nevermind. It was because im running a VPN

**Comment by GoneSubject** [comment]
> > > > did you followed [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)?
> > > 
> > > 
> > > That document file is inaccessible
> > 
> > what do you mean?
> 
> Nevermind. It was because im running a VPN

oh ok
