### ISSUE TITLE
The screen flip issue is not perfectly resolved

### ISSUE THREAD

**Issue by Vera-Firefly** [PojavLauncherTeam/PojavLauncher#2432]
### Describe the bug

When using the virgl renderer to enter either version, press F2 to flip the screen

### Steps To Reproduce

```markdown
1.start PojavLauncher
2.Login Account
3.Select virgl renderer
4.Enter the game
5.Press F2
```

### Expected Behavior

The screen flips after pressing F2

### Platform

```markdown
- Device model: IQOO U3X 4/128
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-299-f1bd70996-v3_openjdk
```

**Comment by GoneSubject** [comment]
i think turn Fbo off?

**Comment by khanhduytran0** [comment]
No response moment.

**Comment by GoneSubject** [comment]
> No response moment.

it's been 1 week ._.

**Comment by notstackgb** [comment]
is that work on android 11?

**Comment by Koijiro** [comment]
having this issue too
