### ISSUE TITLE
Easy installer

### ISSUE THREAD

**Issue by mechameega** [PojavLauncherTeam/PojavLauncher#2433]
### Describe the request.

I wish to request a easier way to install new versions of java on the launcher, or at least a tutorial on how to do it

**Comment by GoneSubject** [comment]
>  or at least a tutorial on how to do it

just download the java you want and go to PojavLauncher setting and find runtime manager and press it and then "add new" then find the file java you downloaded and if you want to use it press "set default"

**Comment by matt995** [comment]
Use brain 
*If you have one
