### ISSUE TITLE
[BUG] It can't launch the game

### ISSUE THREAD

**Issue by youki81** [PojavLauncherTeam/PojavLauncher#2434]
### Describe the bug

I downloaded the latest version of the auto-build. After I run minecraft1.18.1, there was an error. It tells me it can't find a compressible Java runtime.
![Screenshot_20211221-143750](https://user-images.githubusercontent.com/95841100/146883376-1348ed63-e4a1-4282-8467-a24e251c9245.jpg)

### Steps To Reproduce

```markdown
1.Start Pojavluncher
2.Set the game version to 1.18.1
3.Crash
```

### Expected Behavior

I expect mincraft1.18.1 can launch normally

### Platform

```markdown
-设备模型：n-CPU体系结构：n-Android版本：n-PojavLauncher版本：
```

**Comment by GoneSubject** [comment]
you must follow [this](https://pojavlauncherteam.github.io/updates/117.html) and after you follow it you must follow [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04) to sure that you can play normally
