### ISSUE TITLE
Minecraft 1.18.1 doesn't launch

### ISSUE THREAD

**Issue by tigerbrocode** [PojavLauncherTeam/PojavLauncher#2435]
### Describe the bug

So when I launch Minecraft 1.18.1 with Java arm64 renderer gl4es 1.1.5 i crash without any error pop up

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7750321/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Select renderer gl4es 1.1.5
3. Select runtime Java 17 arm 64
```

### Expected Behavior

I expect the game to launch successfully

### Platform

```markdown
- Device model: Samsung M51 
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest release
```

**Comment by GoneSubject** [comment]
the log seems normal, it didn't crash when launch

**Comment by tigerbrocode** [comment]
Turns out I was using render regions

**Comment by GoneSubject** [comment]
> 



> Turns out I was using render regions

really
