### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by HoaiAnhVN** [PojavLauncherTeam/PojavLauncher#2436]
### Describe the bug

Thoát ra với mã 1

### Steps To Reproduce

```markdown
Mong admin sửa lỗi
```

### Expected Behavior

Tôi thấy trò chơi rất hay cảm ơn admin

### Platform

```markdown
- Device model: vivo y66
- CPU architecture: 8
- Android version: 6.0.1
- PojavLauncher version: 1.17.10
```

### Anything else?

Cảm ơn admin

**Comment by GoneSubject** [comment]
không gửi latestlog.txt?
> mục latestlig.txt có thể tìm thấy ở sdcard/games/PojavLauncher hoặc là sdcard/Android/data/net.ndt.pojavlaunch(debug)

**Comment by tigerbrocode** [comment]
Send latestlog

**Comment by GoneSubject** [comment]
> Send latestlog 

yes i told him to do that

**Comment by khanhduytran0** [comment]
@HoaiAnhVN it’s been over 1 week
hơn 1 tuần rồi, vẫn chưa thấy latestlog.txt đâu.

**Comment by HoaiAnhVN** [comment]
Ok

Vào 18:23 Th 4, 29 thg 12 2021 Duy Tran Khanh ***@***.***> đã
viết:

**Comment by GoneSubject** [comment]
> Ok

rồi chừng nào mới gửi

**Comment by HoaiAnhVN** [comment]
Thank you!

Vào 19:00 Th 4, 29 thg 12 2021 GoneSubject ***@***.***> đã
viết:

**Comment by HoaiAnhVN** [comment]
Gửi cái gì vậy admin


Vào 19:08 Th 4, 29 thg 12 2021 Hoài anh Nguyễn trọng <
***@***.***> đã viết:

**Comment by GoneSubject** [comment]
> Gửi cái gì vậy admin

gửi cái file latestlog.txt và tôi không phải admin, tôi chỉ là 1 thằng hề đi lòng vòng thôi ._.

**Comment by HoaiAnhVN** [comment]
À thôi bye tôi khắc phục đc sự cố mã 1 rồi.

Vào 19:41 Th 4, 29 thg 12 2021 GoneSubject ***@***.***> đã
viết:

**Comment by HoaiAnhVN** [comment]
Đây

Vào 23:42 Th 3, 04 thg 1 2022 Hoài anh Nguyễn trọng <
***@***.***> đã viết:

>
