### ISSUE TITLE
[BUG] game crashes with code 1 when trying to install forge

### ISSUE THREAD

**Issue by Ugur2007** [PojavLauncherTeam/PojavLauncher#2437]
### Describe the bug

Game/app crashes with code 1 when trying to install Forge

### Steps To Reproduce

```markdown
1.Trying to install Forge mod installer
2.İt crashing
Not:i am using Java 8
```

### Expected Behavior

Successful forge installation 

### Platform

```markdown
- Device model: GM 20
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I'm just having trouble installing forge

**Comment by GoneSubject** [comment]
which runtime you choose?

**Comment by Ugur2007** [comment]
Java 8

**Comment by GoneSubject** [comment]
> Java 8

send log i think

**Comment by Ugur2007** [comment]
![Screenshot_20211222-083230.png](https://user-images.githubusercontent.com/96493869/147041024-19937f25-e8db-46e1-b932-3f454ef28645.png)

**Comment by GoneSubject** [comment]
i mean send the log not the screenshot

**Comment by Ugur2007** [comment]
how can i send logs

**Comment by GoneSubject1** [comment]
> how can i send logs

https://user-images.githubusercontent.com/95298052/147115835-fd963386-42f8-42f2-9668-d59a6dbfd827.mp4

**Comment by GoneSubject** [comment]
> how can i send logs

https://user-images.githubusercontent.com/95298052/147116222-c05a811b-6b76-4a90-b3e2-3c0acd1183a6.mp4

**Comment by Ugur2007** [comment]
![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7763594/latestlog.txt)

**Comment by NdraaGaminz** [comment]
Don't use Java 17 when you try to instak forge, OptiFine, labymod etc...use Java 8 to make it work, idk why but i tried its work but if you wanna instal some OptiFine etc, switch the runtime to Java 8😁👍

**Comment by GoneSubject** [comment]
> Don't use Java 17 when you try to instak forge, OptiFine, labymod etc...use Java 8 to make it work, idk why but i tried its work but if you wanna instal some OptiFine etc, switch the runtime to Java 8grin+1

welp uh 

> Java 8

**Comment by Ugur2007** [comment]
> Don't use Java 17 when you try to instak forge, OptiFine, labymod etc...use Java 8 to make it work, idk why but i tried its work but if you wanna instal some OptiFine etc, switch the runtime to Java 8😁 


I'm already using Java 8 and it just doesn't install forge

**Comment by GoneSubject** [comment]
> > Don't use Java 17 when you try to instak forge, OptiFine, labymod etc...use Java 8 to make it work, idk why but i tried its work but if you wanna instal some OptiFine etc, switch the runtime to Java 8😁 
> 
> 
> I'm already using Java 8 and it just doesn't install forge

can you send me a video about how you install it?

**Comment by Ugur2007** [comment]
> > > Don't use Java 17 when you try to instak forge, OptiFine, labymod etc...use Java 8 to make it work, idk why but i tried its work but if you wanna instal some OptiFine etc, switch the runtime to Java 8😁 
> > 
> > 
> > I'm already using Java 8 and it just doesn't install forge
> 
> can you send me a video about hiw you install it?

https://user-images.githubusercontent.com/96493869/147497145-3844fbeb-171a-4f9d-a588-ae5c462f3f62.mp4

**Comment by GoneSubject** [comment]
> > > > Don't use Java 17 when you try to instak forge, OptiFine, labymod etc...use Java 8 to make it work, idk why but i tried its work but if you wanna instal some OptiFine etc, switch the runtime to Java 8grin
> > > 
> > > 
> > > I'm already using Java 8 and it just doesn't install forge
> > 
> > 
> > can you send me a video about hiw you install it?
> 
>  YouCut_20211227_211111707.mp4

maybe the file is corrupted? try download the file and try again

**Comment by Ugur2007** [comment]
> > > > > Don't use Java 17 when you try to instak forge, OptiFine, labymod etc...use Java 8 to make it work, idk why but i tried its work but if you wanna instal some OptiFine etc, switch the runtime to Java 8grin
> > > > 
> > > > 
> > > > I'm already using Java 8 and it just doesn't install forge
> > > 
> > > 
> > > can you send me a video about hiw you install it?
> > 
> >  YouCut_20211227_211111707.mp4
> 
> maybe the file is corrupted? try download the file and try again

Nothing has change

**Comment by khanhduytran0** [comment]
@Ugur2007 what you chose is the universal, not installer. Use the installer instead.
