### ISSUE TITLE
[BUG] <MC Forge for 1.6.4 and 1.5.2 doesn't launch>

### ISSUE THREAD

**Issue by Fehrstix** [PojavLauncherTeam/PojavLauncher#2438]
### Describe the bug

Greetings. I want to use Minecraft Forge for Minecraft 1.6.4 and 1.5.2. But after I installed and launched it, it shows me the infinite black screen with PoJav's joystick and gameplay buttons. Could you please help me fix this? My phone cant make it to play with 15 mods on 1.7.10

### Steps To Reproduce

```markdown
1. Start the launcher. 
2. Install the latest Forge versions for 1.6.4 and 1.5.2
3. Run one of them.
```

### Expected Behavior

I wanted it to launch

### Platform

```markdown
- Device model: Huawei Can L 11
- CPU architecture: 8 core 2HHz
- Android version: 7.0
- PojavLauncher version: crocus v3
```

**Comment by khanhduytran0** [comment]
> ### The log file and images/videos
*No response*

Please send latestlog.txt.

**Comment by khanhduytran0** [comment]
Closing until further response.
This is being tracked in #2468

**Comment by Fehrstix** [comment]
Greetings. Thanks for your willing to help. Here are the logs, I tried to launch it today. And I've noticed your mention in the similar issue, so deleting the "version" file didn't help, unfortunatelly.

**Comment by Fersteax** [comment]
content://media/external/file/291739

**Comment by Fehrstix** [comment]
https://pastebin.com/V9XAgf1m
