### ISSUE TITLE
[BUG] Android Tablet Mouse very laggy

### ISSUE THREAD

**Issue by JanW69** [PojavLauncherTeam/PojavLauncher#2439]
### Describe the bug

Hello,

im using the pojav launcher on my Android Tablet on 1.17.2 from the Playstore.
Ingame i have more than 100 FPS and if i move my charakter with my fingers while using the touch screen everything is fine.

I have bought a bluetooth mouse and turned on the "mouse mode" ingame. But its very laggy (jerky), either i have enough FPS and the touchpad is working fine. I also tried to change the sensitiviy. Can anyone help me please?

Thanks

### Steps To Reproduce

```markdown
1. Start Pojav Launcher and enable Mouse mode
2. Mouse is laggy
```

### Expected Behavior

I expect that my mouse will work

### Platform

```markdown
- Device model: Android
- PojavLauncher version: Playstore (newest)
```

**Comment by Mathias-Boulay** [comment]
Fixed on dev builds, else your phone is trash since it cannot deliver events without the delay you're suffering
