### ISSUE TITLE
Mod Web Displays In Minecraft 1.12.2 Not Working

### ISSUE THREAD

**Issue by AnikyMX** [PojavLauncherTeam/PojavLauncher#2442]
### Describe the bug

Can it be fixed?

### The log file and images/videos

Can you guys help?

### Steps To Reproduce

```markdown
Can't install Displays web mod
```

### Expected Behavior

I Wish I Could Use Web Displays Mod

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GoneSubject** [comment]
no platform info and no log?

**Comment by Hadbrinenotcool** [comment]
> no platform info and no log?

Let me just do the uh screenie if this dude lazy af

**Comment by khanhduytran0** [comment]
Web won't work anyways. It uses a huge thing called Chromium (the whole web browser) which the mod author didn't compile for mobile.

**Comment by Hadbrinenotcool** [comment]
> Web won't work anyways. It uses a huge thing called Chromium (the whole web browser) which the mod author didn't compile for mobile.

ahhhhhh i see
