### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by routhing** [PojavLauncherTeam/PojavLauncher#2445]
### Is this request related to a bug?

我在服务器里使用，会经常使用到聊天栏。我是玩了McinaBox一年过来的玩家，如果每一个按钮都可以设置游戏内/外布局，那么玩家在自定义操作布局中，既可以让聊天栏不被虚拟按钮挡住，还可以减少游戏内的按钮数量而流畅操作，并且无需切换显隐控制按钮而快速直观的使用更多的按钮。
I operating in MCservers,often use the chat bar.I am a player of longjunyu's “McinaBox.apk” for one year,I think if every customizable button can be set“IN/OUT of the game（The IN-game is pojav-virtual Shortcut-Bar appears automatically,that talking about the state of IN/OUT）,So player is in the customizable virtualbutton,no only that the CHATBAR is not Blocked by VirtualButtons,but also reduce the number of VirtualButtons in the game to facilitate the operation,There is no need to switching All-in-one_Buttons frequently, and more buttons can be used more Quickly&Intuitively~

I am Chinese player,The translation is not accurate, please understand.

I hope customizable button functions has in-game and out-of-game options in the future~
![Uploading Screenshot_2021-12-24-09-59-45-511_com.aof.mcinabox.jpg…]()

### Describe the request.

I hope customizable button functions has in-game and out-of-game options in the future~
![Uploading Screenshot_2021-12-24-09-59-45-511_com.aof.mcinabox.jpg…]()

### Anything else?

You can also add one more setting option,the mouse click mode can be switched to a simple machine, which is convenient for Double-clicks and hi-speed frequent operation.

**Comment by routhing** [comment]
![Screenshot_2021-12-24-09-59-45-511_com aof mcinabox](https://user-images.githubusercontent.com/71493668/147318174-cf4c7299-27f7-4b1a-9d1b-f7218e684b89.jpg)

**Comment by routhing** [comment]
![Screenshot_2021-12-22-17-48-29-328_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/71493668/147318270-70bea673-6c31-4801-8b05-d9630294e2c7.jpg)
![Uploading Screenshot_2021-12-21-20-40-25-467_com.aof.mcinabox.jpg…]()

**Comment by routhing** [comment]
![Screenshot_2021-12-18-16-07-18-956_com aof mcinabox](https://user-images.githubusercontent.com/71493668/147318377-8f0a98ca-a922-469a-9cc0-e9da64f22efb.jpg)

![Screenshot_2021-12-06-07-54-20-384_com aof mcinabox](https://user-images.githubusercontent.com/71493668/147318498-006f5a9b-d05d-49f2-bdfd-238d227cd34d.jpg)

**Comment by routhing** [comment]
These are the Materials I Recorded Before,it has only an ornamental effect~qwq

**Comment by Mathias-Boulay** [comment]
You can use drawers to hide buttons you don't need

**Comment by routhing** [comment]
em, Thank you for your reply

**Comment by aaaapai** [comment]
> em, Thank you for your reply

要不试一下澪启动器？但是效果不怎么好，可以暂时代替...

**Comment by CosineMath** [comment]
有人打算在未来重写MCinaBox，时间会解决许多问题。

**Comment by routhing** [comment]
龙总摸鱼了，软件确实很不错。澪作者的软件的bug还有很多，虽然我成功在澪启动1.17，但是目前pojavlauncher有更好更稳定的操作布局，而且在骁龙765g上的渲染速度在高版本普遍比澪更快。

At now Longjunyu's McinaBox is abandoned, although his software is really good. But there are still many bugs in MioLauncher software, although I was able to launch the 1.17 on the MioLauncher, But now the PojavLauncher has a better and more stable operating layout, And the shades-speed on the Snapdragon-765G is generally faster than the MioLauncher in MC-1.13+.

At present I play the Survivial-Redstone server in the 1.18.1.

**Comment by routhing** [comment]
My controlmap link:

https://pan.baidu.com/s/11thcZXe_7Hjt5X5IQmY4Gg 

Password:4218

**Comment by routhing** [comment]
controlmap resolution of screen: 2400*1080

**Comment by Mathias-Boulay** [comment]
controls map don't make use of the screen resolution @routhing 
_I almost implemented this in MCinabox a year ago but gave up seeing the codebase_

**Comment by routhing** [comment]
I know it has nothing to do with resolution, but it is designed with this screen ratio, 2400*1080(20:9) is a reference. 😄

**Comment by Mathias-Boulay** [comment]
Newer controls are also aspect ratio independent
