### ISSUE TITLE
[BUG] Advanced Compass mod started removing "assets-v0.zip" from settings, although it worked fine before.

### ISSUE THREAD

**Issue by Fl414r** [PojavLauncherTeam/PojavLauncher#2446]
### Describe the bug

I have been playing with the Advanced Compass mod (Fabric 1.17.1) for a very long time and everything worked fine, but today it started crashing the game.
I haven't changed anything.
After some tests, it turned out that it disables "assets-v0.zip", with any set of mods. A bunch of mods or just only "fabric api" doesn't change anything.
(Google Translate)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7773476/latestlog.txt)

### Steps To Reproduce

```markdown
idk but mod .jar name AdvancedCompass-fabric-1.2.5-1.17.1.jar
```

### Expected Behavior

I expected to play quietly, and not try to understand why a perfectly working mod suddenly began to turn off all my resource packs.

### Platform

```markdown
- Device model: Honor 9C (AKA-L29)
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: crocus-299-f1bd70996-v3_openjdk
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1598242529
```

### Anything else?

Oh, sorry, I first created a post about this problem and only then noticed about the post "Mod" X "doesn't work"

**Comment by khanhduytran0** [comment]
The log stated a different story
> Reloading ResourceManager: Default, **assets-v0.zip**, Fabric Mods...

**Comment by Fl414r** [comment]
> The log stated a different story
> 
> > Reloading ResourceManager: Default, **assets-v0.zip**, Fabric Mods...

See down. ResourceManager reload again and remove assets-v0.zip

**Comment by khanhduytran0** [comment]
Oh well, there's seems to be a race issue while querying the list(?)
Does it happen all the time (even after re-added assets-v0) or sometimes?

**Comment by Fl414r** [comment]
> Oh well, there's seems to be a race issue while querying the list(?) Does it happen all the time (even after re-added assets-v0) or sometimes?

idk... Yesterday I played and everything was fine, but now I have never been able to launch Minecraft with it. Without Advansed Compass, everything works as usual.
upd. I include assets-v0.zip by editing options.txt

**Comment by Fl414r** [comment]
Okay, looks like this is a case of magic outside of Hogwarts. I just started using VirGL and every launch I turn on resource packs again (fortunately, the "Unable to load resource packs" error is triggered only when Minecraft starts)
