### ISSUE TITLE
[BUG] Can't switch to other Microsoft Account

### ISSUE THREAD

**Issue by seelenverwandter1** [PojavLauncherTeam/PojavLauncher#2447]
### Describe the bug

If you click on "Microsoft Login" you will be logged into the previously logged-in account and you cannot change it.

### Steps To Reproduce

```markdown
1. Start Pojav Launcher 
2. Login with an Microsoft Account
3. Try to login with another Microsoft Account.
4. Get loggedin to previously used Account.
```

### Expected Behavior

Login into another Microsoft Account. 

### Platform

```markdown
- Device model: Samsung s10+
- CPU architecture: 
- Android version: Android 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by GoneSubject** [comment]
so this thing is useless?![IMG_20211224_171808.jpg](https://user-images.githubusercontent.com/95298052/147345136-7d56c6cc-3ff3-4dd4-b1dd-dab6c78b7534.jpg)

**Comment by seelenverwandter1** [comment]
> so this thing is useless?![IMG_20211224_171808.jpg](https://user-images.githubusercontent.com/95298052/147345136-7d56c6cc-3ff3-4dd4-b1dd-dab6c78b7534.jpg)


https://user-images.githubusercontent.com/7594455/147345290-2e6268f5-4be8-4fa4-a525-eb2d5fc01011.mp4

It works for Mojang Accounts but not for Microsoft.

**Comment by GoneSubject** [comment]
> > so this thing is useless?![IMG_20211224_171808.jpg](https://user-images.githubusercontent.com/95298052/147345136-7d56c6cc-3ff3-4dd4-b1dd-dab6c78b7534.jpg)
> 
> 
> https://user-images.githubusercontent.com/7594455/147345290-2e6268f5-4be8-4fa4-a525-eb2d5fc01011.mp4
> 
> It works for Mojang Accounts but not for Microsoft. 

try this then ![IMG_20211224_173639.jpg](https://user-images.githubusercontent.com/95298052/147345524-a23edb07-a0fb-4ddc-af5a-a4fc285d50ce.jpg)

**Comment by seelenverwandter1** [comment]
> > > so this thing is useless?![IMG_20211224_171808.jpg](https://user-images.githubusercontent.com/95298052/147345136-7d56c6cc-3ff3-4dd4-b1dd-dab6c78b7534.jpg)
> > 
> > 
> > 
> >   
> >     
> >     
> > 
> >     Screen_Recording_20211224-113208_PojavLauncher.Minecraft.Java.Edition.for.Android.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > It works for Mojang Accounts but not for Microsoft.
> 
> try this then ![IMG_20211224_173639.jpg](https://user-images.githubusercontent.com/95298052/147345524-a23edb07-a0fb-4ddc-af5a-a4fc285d50ce.jpg)

This login is only for Mojang Accounts. 
![Screenshot_20211224-114120_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/7594455/147345869-1351bff4-5374-4ffb-acd1-ef1f1c87211e.jpg)

**Comment by GoneSubject** [comment]
> > > > so this thing is useless?![IMG_20211224_171808.jpg](https://user-images.githubusercontent.com/95298052/147345136-7d56c6cc-3ff3-4dd4-b1dd-dab6c78b7534.jpg)
> > > 
> > > 
> > > ```
> > > Screen_Recording_20211224-113208_PojavLauncher.Minecraft.Java.Edition.for.Android.mp4
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It works for Mojang Accounts but not for Microsoft.
> > 
> > 
> > try this then ![IMG_20211224_173639.jpg](https://user-images.githubusercontent.com/95298052/147345524-a23edb07-a0fb-4ddc-af5a-a4fc285d50ce.jpg)
> 
> This login is only for Mojang Accounts. ![Screenshot_20211224-114120_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/7594455/147345869-1351bff4-5374-4ffb-acd1-ef1f1c87211e.jpg)

i guess wait the dev to fix this then

**Comment by Nahdjwdn** [comment]
oh i sped 10 hores of my lijfe on nothing

**Comment by Mathias-Boulay** [comment]
> If you click on "Microsoft Login" you will be logged into the previously logged-in account and you cannot change it.
Oh yeah, maybe we should clear cookies

**Comment by seelenverwandter1** [comment]
> > If you click on "Microsoft Login" you will be logged into the previously logged-in account and you cannot change it.
> > Oh yeah, maybe we should clear cookies

Thats not a fix.. And where should I delete my cookies? I am not signed in to my Microsoft account in any browser. Already reinstalled pojav and i got logged in into my old Account.

**Comment by wonkywonks** [comment]
> 

and the same happened to me reinstalled, removed cache and everything

**Comment by Enestrupi** [comment]
Why pojav launcher is not working a try 5 account but is not working
