### ISSUE TITLE
[BUG] VirGL renderer 

### ISSUE THREAD

**Issue by NdraaGaminz** [PojavLauncherTeam/PojavLauncher#2449]
### Describe the bug

When i play pojav 1.15.2-1.16.4 on my own world, when i move my phone scree rotates to left and upside down, like left-handed but upside down, i feel this is a bug for VirGL renderer. Can it be fixed? It's not good if you play the screen upside down and can't flip back to normal again😄

### The log file and images/videos

#bug(VirGL)
Image:
![IMG_20211224_205317](https://user-images.githubusercontent.com/95620914/147354083-ee8b1f72-ccbe-4ebf-b2e5-d058fb59ee34.jpg)
My screen while play with VirGL 4.3:
![IMG_20211224_211621](https://user-images.githubusercontent.com/95620914/147355475-35226f58-5c0d-4e41-8b0c-4752fe583c25.jpg)
And one more:
IMG_20211224_211556](https://user-images.githubusercontent.com/95620914/147355512-a084cde8-96d1-4e31-933e-4b35d6aa3f1a.jpg)

### Steps To Reproduce
Walking on my own world and then screen got rotated on my realme c12

```


### Expected Behavior

Bug fixed

### Platform

```markdown
- Device model: Realme C12
- CPU architecture: Mediatek Helio G35
- Android version: 10
- PojavLauncher version: [crocus-299-f1bd70996-v3_openjdk]
```

### Anything else?

Help

**Comment by WesleyVanNeck** [comment]
Bah poeple keep reporting a known issues over and over again read the issues before your reporting a issue

**Comment by aaaapai** [comment]
Listen to me, the only favorite thing I know is gl4es. I don't know what renderer to replace gl4es on the road

**Comment by GoneSubject** [comment]
> Listen to me, the only favorite thing I know is gl4es. I don't know what renderer to replace gl4es on the road

the gl4es is the stable render but it can't use shaders so maybe that's the reason we have zink and virgl render

**Comment by Neftalicruz** [comment]
Which shader is the one you use, I have a OnePlus Nord n100 and the game closes when putting a shader with the VirGl Rendering

**Comment by GoneSubject** [comment]
> Which shader is the one you use, I have a OnePlus Nord n100 and the game closes when putting a shader with the VirGl Rendering

welp the reason the screen flip is not because the shader it's because the render

**Comment by Fl414r** [comment]
This bug works for me only in singleplayer. Everything is fine on the servers.
(It's a shame that because of this bug you can't play singleplayer with Sodium or 1.18.1)

**Comment by Fl414r** [comment]
> Listen to me, the only favorite thing I know is gl4es. I don't know what renderer to replace gl4es on the road

umm... with gl4es/vgpu in 1.18.1 there is no light. Sodium (1.17.1) only works with VirGL. Advanced Compass Mod crashes resource packs (assets-v0.zip) in every launch.

**Comment by NdraaGaminz** [comment]
Ok GUYS.... Im gonna close this, Pojav Dev gas been fixed this, on Action > Fixed Flipped Screen. Thanks for your participation...good bye😁
