### ISSUE TITLE
Lag on 1.10+. And in future chunk rendering issue on 1.13+

### ISSUE THREAD

**Issue by Malaska678** [PojavLauncherTeam/PojavLauncher#245]
I think that the game is laggy And world generation is slow. I Try To Play Sutvival 1.10 But It lag When I Break Block. It Would become more laggy on 1.13+.

**Comment by khanhduytran0** [comment]
(V2) The lag problem may be because RAM memory is limited by Android.

(V3) Chunk rendering issue may be already fixed in GL4ES 1.1.4. (Maybe you tried 1.13 in another launcher so know that chunk issue?)

**Comment by Malaska678** [comment]
Most launcher(ex:mcinabox,boat) need sd Card which i dont have.
I cant Find Launcher that dont need sd card.
