### ISSUE TITLE
[BUG] Class file major version 21845

### ISSUE THREAD

**Issue by kl1024** [PojavLauncherTeam/PojavLauncher#2450]
### Describe the bug

![Screenshot_20211225-100556603](https://user-images.githubusercontent.com/57281140/147376238-f3242c1d-5b82-4d33-8213-4c642074f636.jpg)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Start fabric-loader-1.18.1-0.12.12
```

### Expected Behavior

I expect the game launches

### Platform

```markdown
- Device model: Mi Note 3
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-299-f1bd70996-v3_openjdk
```

**Comment by GoneSubject** [comment]
send latestlog

**Comment by NotAHero04** [comment]
You just tried launching it with Java 8, did you?

**Comment by kl1024** [comment]
> You just tried launching it with Java 8, did you?

no I launch it with java 17

**Comment by kl1024** [comment]
--------- beggining with launcher debug
Info: Launcher version: crocus-299-f1bd70996-v3_openjdk
Info: LWJGL3 directory: [version, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl.jar, lwjgl-glfw-classes.jar, jsr305.jar]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.1
--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=1920
Added custom env: POJAV_NATIVEDIR=/data/app/~~xmanzGZEA1vAjafA92Iucg==/net.kdt.pojavlaunch.debug-dzc6qTQGT3NJn92N1HoLmQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: LIBGL_SHRINK=0
Added custom env: LIBGL_USEVBO=0
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~xmanzGZEA1vAjafA92Iucg==/net.kdt.pojavlaunch.debug-dzc6qTQGT3NJn92N1HoLmQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_virgl
Added custom env: LIBGL_ES=3_virgl
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=430
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.3
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
I/jrelog  (31563): dlopen libOSMesa_8.so success
I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjli.so success
I/jrelog  (31563): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libverify.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjava.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libnet.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libnio.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libawt.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libfreetype.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/librmi.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjava.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libj2gss.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libdt_socket.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libnio.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjaas.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjavajpeg.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libfreetype.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/liblcms.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libsctp.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libverify.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libj2pcsc.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjawt.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libnet.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libawt.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libzip.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libj2pkcs11.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libprefs.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libmanagement.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libmanagement_agent.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libinstrument.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libmanagement_ext.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjimage.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/server/libjsig.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libattach.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libsyslookup.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjli.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjsig.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libmlib_image.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libjdwp.so success

I/jrelog  (31563): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20211018-release.tar.xz/lib/libextnet.so success

I/jrelog  (31563): dlopen /data/app/~~xmanzGZEA1vAjafA92Iucg==/net.kdt.pojavlaunch.debug-dzc6qTQGT3NJn92N1HoLmQ==/lib/arm64/libopenal.so success

I/jrelog  (31563): Done processing args

I/jrelog  (31563): Found JLI lib
I/jrelog  (31563): Calling JLI_Launch

  <log4j:Event logger="FabricLoader/GameProvider" timestamp="1640523641437" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading Minecraft 1.18.1 with Fabric Loader 0.12.12]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader" timestamp="1640523642001" level="ERROR" thread="main">
    <log4j:Message><![CDATA[Uncaught exception in thread "main"]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.IllegalArgumentException: Unsupported class file major version 21845
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
	at net.fabricmc.loader.impl.game.patch.GameTransformer.lambda$locateEntrypoints$0(GameTransformer.java:80)
	at net.fabricmc.loader.impl.game.minecraft.patch.EntrypointPatch.process(EntrypointPatch.java:62)
	at net.fabricmc.loader.impl.game.patch.GameTransformer.locateEntrypoints(GameTransformer.java:87)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:505)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
]]></log4j:Throwable>
  </log4j:Event>
Java Exit code: 1
I/jrelog  (31563): Going to free args
I/jrelog  (31563): Free done

**Comment by Fl414r** [comment]
Um... you can send .txt  files via the send images menu

**Comment by kl1024** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7780671/latestlog.txt)

**Comment by NotAHero04** [comment]
Not sure why it requires **Java version 21801**, you may want to reinstall Fabric again.

**Comment by khanhduytran0** [comment]
Closing until further response.

**Comment by kl1024** [comment]
> Not sure why it requires **Java version 21801**, you may want to reinstall Fabric again.

I reinstalled it for several times and it always appears
