### ISSUE TITLE
PojavLauncherTeam If you're reading this I'd have this this very unusual bug it's that the the pojavlauncher file doest show up in the games folder please help.

### ISSUE THREAD

**Issue by Sulfurix3273** [PojavLauncherTeam/PojavLauncher#2453]
### Describe the bug

The PojavLauncher file where I can paste my skin or If I just want to paste a resource pack I can't do do that because the file does not appear when I try to import a texture pack

### The log file and images/videos

The PojavLauncher file where I can paste my skin or If I just want to paste a resource pack I can't do do that because the file does not appear when I try to import a texture pack

### Steps To Reproduce

```markdown
The PojavLauncher file where I can paste my skin or If I just want to paste a resource pack I can't do do that because the file does not appear when I try to import a texture pack
```

### Expected Behavior

The PojavLauncher file where I can paste my skin or If I just want to paste a resource pack I can't do do that because the file does not appear when I try to import a texture pack

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No

**Comment by GoneSubject** [comment]
turn on "show hidden files" or go in sdcard/Android/data/net.ndt.pojavlaunch(debug)/files if your phone is android 10 and higher

**Comment by khanhduytran0** [comment]
We don’t support pirating, like that.
Also, invalid:
- The log file and images/videos
- Steps To Reproduce
- Expected Behavoir
- Platform: empty
