### ISSUE TITLE
[F-Req] Auto open keyboard

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2454]
### Describe the request.

Make it so that when I click on the input field and when I open a chat, so that the keyboard automatically opens and closes when I click on an empty space!

**Comment by GoneSubject** [comment]
welp you can do that, just edit the button that open the chat and add the keyboard mapping![Screenshot_2021-12-26-00-18-02-180_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/95298052/147390178-b90009b6-949d-4186-83c6-7bb5d2ce4ea4.jpg)

**Comment by andr0d1v** [comment]
I'm not a launcher developer! I can't do this!

**Comment by GoneSubject** [comment]
> I'm not a launcher developer! I can't do this!

yea i know(i was uploading the screenshot)

**Comment by andr0d1v** [comment]
And how to make the keyboard close when you click on any empty space?

**Comment by GoneSubject** [comment]
> And how to make the keyboard close when you click on any empty space?

hm this one can't but just press go back 1 time and the keyboard is closed

**Comment by GoneSubject** [comment]
> And how to make the keyboard close when you click on any empty space?

hm this one can't but just press go back 1 time and the keyboard is closed

**Comment by andr0d1v** [comment]
Thanks
