### ISSUE TITLE
The resource pack not open for 1.18

### ISSUE THREAD

**Issue by BottomotPH29** [PojavLauncherTeam/PojavLauncher#2456]
### Describe the bug

.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Samsung 
- CPU architecture: arch 64
- Android version: 11
- PojavLauncher version: new
```

### Anything else?

.

**Comment by khanhduytran0** [comment]
Invalid information.
Follow https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04
