### ISSUE TITLE
skin

### ISSUE THREAD

**Issue by kaicryptx** [PojavLauncherTeam/PojavLauncher#2459]
### Is this request related to a bug?

Pojavlauncher team I need a option like Tlauncher need a skin option

**Comment by InfiniXDerg** [comment]
Buy a fking account bruh

**Comment by ghost** [comment]
Buy the game 
No pirate in here

**Comment by ghost** [comment]
@khanhduytran0 close momebt

**Comment by ghost** [comment]
Pirate bhai

**Comment by OhCauXanh** [comment]
@nanajiiiiii pirate legit
