### ISSUE TITLE
Question for V3

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#246]
I have a question? With the release of the V3 version and enabling "the first time" it will be loading, unpacking, whether it will start and that's it

**Comment by khanhduytran0** [comment]
So it looks like not a question...

**Comment by xXFrostXx1** [comment]
When will the update? <3

**Comment by khanhduytran0** [comment]
I can't sure about an eta, but currently you may get v3 autobuild in releases/Actions workflows, althought it does not work...

**Comment by khanhduytran0** [comment]
So it work, but I can't understand the question. I will close...
