### ISSUE TITLE
[F-Req] FDroid Repo

### ISSUE THREAD

**Issue by myxxmikeyxx** [PojavLauncherTeam/PojavLauncher#2460]
### Is this request related to a bug?

Do you guys have an FDroid repo? In the latest release you say to use the google play store version but on my phone I have rooted and installed a DeGoogled Android and use the FDorid store. In FDroid you can add repos. I would like to install the latest of this since the release says to use the playstore version.

**Comment by artdeell** [comment]
You can use aurora store if you want. https://auroraoss.com

вс, 26 дек. 2021 г., 21:04 myxxmikeyxx ***@***.***>:

**Comment by myxxmikeyxx** [comment]
I did not know this. Thank you @artdeell! I will have to check that out.

**Comment by GaucovyAero** [comment]
nope
