### ISSUE TITLE
I cant add texture packs

### ISSUE THREAD

**Issue by lordasg** [PojavLauncherTeam/PojavLauncher#2461]
### Describe the bug

When I try to use Zarchiver there simply isn't a game folder like in the tutorial

### The log file and images/videos

![Screenshot_20211226-235654](https://user-images.githubusercontent.com/89625757/147416941-c00f2226-2d74-410c-9839-dbbe9a3bab2d.jpg)

### Steps To Reproduce

```markdown
None
```

### Expected Behavior

None

### Platform

```markdown
- Device model: OnePlus Nord
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest release
```

**Comment by GoneSubject** [comment]
because your android is 10 and higher so go to sacard/Android/net.ndt.pojavlaunch(debug)/files

**Comment by Nahdjwdn** [comment]
just make a games folder

**Comment by Nahdjwdn** [comment]
also just go to android and go ontil you see pojav and bam you can get resorces pack

**Comment by GoneSubject** [comment]
ok?
