### ISSUE TITLE
puting a real minecraft account is not working to login[BUG] <Short description>

### ISSUE THREAD

**Issue by Nahdjwdn** [PojavLauncherTeam/PojavLauncher#2462]
### Describe the bug

put in real account not login in

### The log file and images/videos

https://myoctocat.com/assets/images/base-octocat.svg)

### Steps To Reproduce

```markdown
put in real account then login and thare you go
```

### Expected Behavior

to login but nope it did not login

### Platform

```markdown
- Device model: moto g play
- CPU architecture: aarch64
- Android version: 8
- PojavLauncher version: [latest ll release verstion 3.3.1.1_rel_20210206]
```

**Comment by khanhduytran0** [comment]
Where did you get your “real” account?
Where’s the error message?

**Comment by Nahdjwdn** [comment]
I'm so sry I thot it was that but I can't edit the Gmail out sry also I can't make a video il try puting a screenshot

**Comment by Nahdjwdn** [comment]
> Where did you get your “real” account? Where’s the error message?

Sry I got it in a Mojang account but it didn't login also I'm this was by my little brother he doesn't know how to screenshot also he was on my accoun

**Comment by Nahdjwdn** [comment]
> Where did you get your “real” account? Where’s the error message?

**Comment by Nahdjwdn** [comment]
> Where did you get your “real” account? Where’s the error message?
![Screenshot_20211230-185132](https://user-images.githubusercontent.com/95057478/147797243-a72a7733-fb2a-4b7e-aed4-e7b5bda8df81.png)
