### ISSUE TITLE
[F-Req] Add toggle keyboard in the installation screen

### ISSUE THREAD

**Issue by LightestMC** [PojavLauncherTeam/PojavLauncher#2463]
### Is this request related to a bug?

-

### Describe the request.

I would like the toggle keyboard button to be added as I am trying to log into a launcher (PlumePack Launcher) and it requires me to log into my minecraft account. Right now, I am unable to do so since I cannot type as there is no toggle keyboard option. 

### Anything else?

-

**Comment by Fl414r** [comment]
try Hacker's Keyboard (set "Use permanent notification" on in keyboard settings)
![Screenshot_20211227_135723](https://user-images.githubusercontent.com/74704475/147465211-4c118f6a-ac70-415f-91e0-871f01e9b066.jpg)

**Comment by artdeell** [comment]
Will not work. Mod installer does not accept keyboard input

пн, 27 дек. 2021 г., 13:57 Fl414r ***@***.***>:

**Comment by Mathias-Boulay** [comment]
MISSION COMPLEEEEEEEEEEEETE
