### ISSUE TITLE
Vgpu white screen [BUG]

### ISSUE THREAD

**Issue by vasu123432141** [PojavLauncherTeam/PojavLauncher#2466]
### Describe the bug

Vgpu white screen 

### The log file and images/videos

Fix plz
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7780900/latestlog.txt)

### Steps To Reproduce

```markdown
Open pojav launcher 
Select vgpu renderer 
Launch Minecraft 
White screen appears 
Please fix
```

### Expected Behavior

I excepted 60 fps gameplay with vgpu shader 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 8
- PojavLauncher version: latest
```

### Anything else?

No

**Comment by WesleyVanNeck** [comment]
i think this is happning because of your opengl es version isnt suported

**Comment by WesleyVanNeck** [comment]
also fill the dam tamplate

**Comment by vasu123432141** [comment]
Dam template what is this idk

**Comment by GoneSubject** [comment]
> Dam template what is this idk

just fill your phone model and CPU
> Device model:
CPU architecture:

**Comment by vasu123432141** [comment]
Model:Vivo 1820
CPU arm-64

**Comment by vasu123432141** [comment]
Hi fix please

**Comment by GoneSubject** [comment]
> Hi fix please 

hmm i have no idea

**Comment by vasu123432141** [comment]
what now how I will ebjoy6

**Comment by vasu123432141** [comment]
Please tell

**Comment by GoneSubject** [comment]
> what now how I will ebjoy6

umm can you change the render to gl4es?

**Comment by vasu123432141** [comment]
Phone renderer?

**Comment by vasu123432141** [comment]
I want to play in vgpu

**Comment by vasu123432141** [comment]
I want to play in vgpu

**Comment by GoneSubject** [comment]
> I want to play in vgpu 

why?

**Comment by GoneSubject** [comment]
> Phone renderer?

no this render![Screenshot_2021-12-28-16-44-06-018_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/95298052/147552993-ea787b7e-0538-493c-8af0-54b1ef144348.jpg)

**Comment by vasu123432141** [comment]
It boost fps please tell

**Comment by GoneSubject** [comment]
> It boost fps please tell

uh the gl4es is the recommend render so pls change your render to gl4es it doesn't make you lag

**Comment by vasu123432141** [comment]
ok

**Comment by vasu123432141** [comment]
K
