### ISSUE TITLE
[BUG] "Microsoft Login" Button Not Loading Microsoft Login Page

### ISSUE THREAD

**Issue by Sophilocity** [PojavLauncherTeam/PojavLauncher#2467]
### Describe the bug

I recently migrated my Mojang account to Microsoft and now when I try to login to PojavLauncher with Microsoft it shows me an error screen reading:

Webpage not available
The webpage at https://login.live.com/oauth20_authorize.srf?client_id=00000000402b5328&response_type=code&scope=service%3A%3Auser.auth.xboxlive.com%3A%3AMBI_SSL&redirect_url=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf could not be loaded because:

net::ERR_NO_SUPPORTED_PROXIES

That URL works in my browser perfectly fine. I don't have a PC for the time being and Pojav was the only way I could use Minecraft until I get one, the subreddit was no help and now I can't play Minecraft. I normally use Pojav on my laptop (Asus Chromebook) and not phone but I'm not sure if that matters because the Microsoft login worked before. I tried using Linux Beta to use the official launcher but that runs like trash to the point where its practically unplayable. Any help would really be appreciated. 

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Press "MICROSOFT LOGIN"
```

### Expected Behavior

I expected it to open the Microsoft login page and allow me to login with my Microsoft account with no issues.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
Please check if you have anything that affect network connection (VPN/Proxy/etc..)

**Comment by khanhduytran0** [comment]
Closing until further response.

**Comment by Sophilocity** [comment]
> 

It started working again a while ago, not sure why but to answer your question, at the time I didn't have a VPN on or anything.
