### ISSUE TITLE
[BUG] Issues with older Forge versions

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher#2468]
### Describe the bug
- Forge 1.3.2 (same as 1.4.2)

I was addressing the weird behavior of Forge 1.3.2 that prevents itself from launching. Here's what I did:
Step 1: Add the correct libraries to `.minecraft/lib/`. It didn't complain about the missing libraries anymore, but the loading process just stopped at
> [INFO] [ForgeModLoader] Forge Mod Loader version 3.1.50.400 for Minecraft client:1.3.2, server:1.3.2 loading
>
Step 2: Change the minecraft main class argument to `net.minecraft.client.Minecraft`. This time it returned
> [INFO] [STDERR] Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
>
which indicates that LWJGL library is missing (?)

- Forge 1.5.2

The game just exits with Java code 0.

- Forge 1.6.4/1.7.2

The game calls the wrong class (`net.minecraft.client.Minecraft`, expected `net.minecraft.client.main.Main`), which then Java throws a `java.lang.NoClassDefFoundError`.

### The log file and images/videos
- Forge 1.3.2:

After step 1: 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7782878/latestlog.txt)
After step 2:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7782885/latestlog.txt)

- Forge 1.5.2

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7793658/latestlog.txt)

- Forge 1.6.4

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7793654/latestlog.txt)

### Steps To Reproduce

```markdown
See above.
```

### Expected Behavior

These Forge versions should be able to launch.

### Platform

```markdown
- Device model: Vsmart Star 5
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-299-f1bd70996-v3_openjdk
```

### Anything else?

No.

**Comment by artdeell** [comment]
I tested forge for 1.2.5, and it works nicely.
Looks like the reason why it doesn't start is that the forge attempts to reload itself in a different classloader which does not read the default classpath. Which leads LWJGL not to be found because Pojav uses its own one, not the Minecraft one.

**Comment by NotAHero04** [comment]
I keep digging and finally find more issue with older versions of Forge. So...

**Comment by khanhduytran0** [comment]
As of the missing class was added, could you try them? (delete `lwjgl3/version` file if you are still getting missing class)

**Comment by NotAHero04** [comment]
> As of the missing class was added, could you try them? (delete `lwjgl3/version` file if you are still getting missing class)

Still doesn't work

**Comment by NotAHero04** [comment]
The log is the same as above. I tried deleting the entire lwjgl3 folder and then get a new installation.

**Comment by NotAHero04** [comment]
Forge 1.6.4 (and 1.7.2) works after switching the ASM library version to 5.2. Needs more testing on older ones.

**Comment by NotAHero04** [comment]
I took a look back at the logs, and there's a `java.lang.IllegalArgumentException` which pointed to the ASM library (1.3.2). To make it run with other libraries, I must directly patch the bytecode (since I have no IDEs available), but, let me test it.
Edit: Never mind, it can be compiled with a single `javac` command.
Edit 2: It doesn't work.

**Comment by NotAHero04** [comment]
@Aerolome seems to get most of the remaining Forge versions work with "changing ASM library" method. This will be the ultimate workaround until further notice.
![Screenshot_20220209-063440~2](https://user-images.githubusercontent.com/84689840/153093717-e13a4d04-33c7-4668-b861-3f8a980cee84.png)

**Comment by Forever2397** [comment]
> @Aerolome seems to get most of the remaining Forge versions work with "changing ASM library" method. This will be the ultimate workaround until further notice. ![Screenshot_20220209-063440~2](https://user-images.githubusercontent.com/84689840/153093717-e13a4d04-33c7-4668-b861-3f8a980cee84.png)

I want your files Can I download files from you

**Comment by GaucovyAero** [comment]
> > @Aerolome seems to get most of the remaining Forge versions work with "changing ASM library" method. This will be the ultimate workaround until further notice. ![Screenshot_20220209-063440~2](https://user-images.githubusercontent.com/84689840/153093717-e13a4d04-33c7-4668-b861-3f8a980cee84.png)
> 
> I want your files Can I download files from you

the ones on notahero's repo are only semi-working, i can fix one for you, which one do you want?

**Comment by Forever2397** [comment]
Aerolome I want you to fix this

**Comment by Forever2397** [comment]
> > > @Aerolome seems to get most of the remaining Forge versions work with "changing ASM library" method. This will be the ultimate workaround until further notice. ![Screenshot_20220209-063440~2](https://user-images.githubusercontent.com/84689840/153093717-e13a4d04-33c7-4668-b861-3f8a980cee84.png)
> > 
> > 
> > I want your files Can I download files from you
> 
> the ones on notahero's repo are only semi-working, i can fix one for you, which one do you want?

for more details you can see my problem here #3511

**Comment by AjTheOpsuGamer** [comment]
Please Download java runtime or only play normal mc.
