### ISSUE TITLE
[BUG] Chromebook [octopus], if  you use optifine, the mouse stays on the screen even when not in crafting tables, furnaces, etc.

### ISSUE THREAD

**Issue by KyuketsuXDD** [PojavLauncherTeam/PojavLauncher#2469]
### Describe the bug

 [octopus], if  you use optifine, the mouse stays on the screen even when not in crafting tables, furnaces, etc.

### The log file and images/videos

None.

### Steps To Reproduce

```markdown
Open optifine on a chromebook, [i used 1.15.2] join a world, an your mouse stays there
```

### Expected Behavior

Mouse to not stay on the screen

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GoneSubject** [comment]
fill the platform info

**Comment by khanhduytran0** [comment]
Closing until further response.
