### ISSUE TITLE
Helpful Feature that i want

### ISSUE THREAD

**Issue by BryleHelll** [PojavLauncherTeam/PojavLauncher#247]
Its Ram Expander. It will decrease lag. The ram expander don't need sd card and it will be optional. Is it possible or not?

**Comment by khanhduytran0** [comment]
Yes, it will be possible in v3.

**Comment by BryleHelll** [comment]
Thanks for answering my question.

**Comment by khanhduytran0** [comment]
If you have any other questions, join https://discord.gg/6RpEJda.

**Comment by CosineMath** [comment]
Note that on old PC allocating more ram for Minecraft increases lags.

**Comment by BryleHelll** [comment]
@CosineMath So Ram Expander is Bad Idea?

**Comment by khanhduytran0** [comment]
Old PC meaning 32bit PC (maybe)

**Comment by khanhduytran0** [comment]
And also 32bit runtime (not sure)

**Comment by CosineMath** [comment]
I just mean expanding ram is not bound to make performance better. However, it is worth trying.

**Comment by BryleHelll** [comment]
I see that pc need 4gb of ram to play minecraft java smoothly.

**Comment by khanhduytran0** [comment]
So it's possible in v3, closing
