### ISSUE TITLE
[BUG] VirGL Bug, cant render godrays and clouds on all shaders

### ISSUE THREAD

**Issue by NdraaGaminz** [PojavLauncherTeam/PojavLauncher#2470]
### Describe the bug

My clouds and godrays can't render on all shader, i tested: chocapic13 lite-extreme, sildurs,kuda shaders, seus shader, all of it cant render clouds and godrays. Even though the clouds and godrays is on, on the shader setting...
I hope this is gettiny fixed

### The log file and images/videos
Before VirGL (zink but laggy):
![Screenshot_2021-12-14-20-43-54-00_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95620914/147534305-10dc88f6-b89d-4816-a9a2-64bd3d0e2931.jpg)

Like this:
![Screenshot_2021-12-27-21-01-26-41_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/95620914/147533298-c923f7dd-b3be-4fe7-a49d-1f33a464f071.jpg)

### Steps To Reproduce

```markdown
1.set the renderer to VirGL 4.3
2.set the runtime to 17
3.start pojav launcher
4.go to setting>video setting>shaders> toggle the shader on
5.joining my own world and then i realized the godrays and clouds not rendered
```

### Expected Behavior

Godrays and clouds can be rendered on shaders while using VirGL 4.3

### Platform

```markdown
- Device model: Realme C12
- CPU architecture: Helio G35 | Aarch 64
- Android version: 10
- PojavLauncher version: crocus-298-1603206f34-v3_openjdk
```

**Comment by GoneSubject** [comment]
PojavLauncher doesn't support all shaders

**Comment by NdraaGaminz** [comment]
> 

Yea...but before VirGL released...im using a zink renderer 4.6, theres no bugs while using shader even though using a high resolution shaders its gonna bug because the device not support that resolution, but this...theres no error logs on the shaders, maybe its because 4.3, not 4.6 huh?

**Comment by NdraaGaminz** [comment]
> PojavLauncher doesn't support all shaders

Look at the "before VirGL" picture... Theres godrays and clouds

**Comment by NdraaGaminz** [comment]
![Screenshot_2021-12-14-20-09-23-96_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95620914/147535172-31ad9ac8-893b-49c4-b825-482ee1be1402.jpg)
Old ss

**Comment by NdraaGaminz** [comment]
![Screenshot_2021-11-20-07-26-11-91](https://user-images.githubusercontent.com/95620914/147535251-86e3c547-3566-4137-ad60-e494cc77784b.jpg)
Old ss...

**Comment by GoneSubject** [comment]
welp i think because the update so it get some errors

**Comment by GoneSubject** [comment]
> > 
> 
> Yea...but before VirGL released...im using a zink renderer 4.6, theres no bugs while using shader even though using a high resolution shaders its gonna bug because the device not support that resolution, but this...theres no error logs on the shaders, maybe its because 4.3, not 4.6 huh?

zink can run alot of stuff

**Comment by khanhduytran0** [comment]
> > PojavLauncher doesn't support all shaders
> 
> Look at the "before VirGL" picture... Theres godrays and clouds

VirGL isn’t developed by us. Zink is currently unavailable since the newer version just render nothing for unknown reasons.
