### ISSUE TITLE
[F-Req] Profiles

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2471]
### Describe the request.

Add profiles function like in the original minecraft launcher!

### Anything else?

It is desirable that profiles are used by default!

**Comment by GoneSubject** [comment]
PojavLauncher has its own profiles already

**Comment by andr0d1v** [comment]
Then tell me how can I turn them on? The latest build is installed!

**Comment by GoneSubject** [comment]
> Then tell me how can I turn them on? The latest build is installed!

for android 9 and below go in sdcard/games/PojavLauncher
for android 10 and higher go in sdcard/Android/data/net.ndt.pojavlaunch(debug)/files make sure you have turned on "show hidden files"

**Comment by andr0d1v** [comment]
What to do next?
![Screenshot_20211228-094459121](https://user-images.githubusercontent.com/87223939/147536680-863a96a7-f3ae-4d34-acda-0e57a8734f7a.jpg)

**Comment by GoneSubject** [comment]
> What to do next? ![Screenshot_20211228-094459121](https://user-images.githubusercontent.com/87223939/147536680-863a96a7-f3ae-4d34-acda-0e57a8734f7a.jpg)

go to .minecraft and there's minecraft's files

**Comment by andr0d1v** [comment]
Give full instructions on how to enable profiles in the launcher!
![Screenshot_20211228-095034609](https://user-images.githubusercontent.com/87223939/147537254-312d69c3-db63-4fdc-84f6-aae1458f8413.jpg)

**Comment by GoneSubject** [comment]
> Give full instructions on how to enable profiles in the launcher! ![Screenshot_20211228-095034609](https://user-images.githubusercontent.com/87223939/147537254-312d69c3-db63-4fdc-84f6-aae1458f8413.jpg)

can you example? i don't understand what you need

**Comment by andr0d1v** [comment]
Profiles are used in the official Minecraft launcher!
![Minecraft-Launcher-3_11_2021-5_09_44-PM](https://user-images.githubusercontent.com/87223939/147540126-d1a78d54-9282-4e77-a0fc-3d1cee65a653.png)

**Comment by andr0d1v** [comment]
This is how I want my profiles to work in the pojav launcher!

**Comment by GoneSubject** [comment]
> Profiles are used in the official Minecraft launcher! ![Minecraft-Launcher-3_11_2021-5_09_44-PM](https://user-images.githubusercontent.com/87223939/147540126-d1a78d54-9282-4e77-a0fc-3d1cee65a653.png)

oh then cut it into sdcard/Android/data/net.ndt.pojavlaunch(debug)/files/.minecraft/versions or sdcard/games/PojavLauncher/versions

**Comment by andr0d1v** [comment]
These are just versions of minecraft! And I need exactly the profiles where you can sign in your versions as you want! (For example: profile "Favorite version", version: 1.16.5)

**Comment by GoneSubject** [comment]
> These are just versions of minecraft! And I need exactly the profiles where you can sign in your versions as you want! (For example: profile "Favorite version", version: 1.16.5)

you can rename the version you want

**Comment by andr0d1v** [comment]
Nevermind! We released an assembly where the profiles were returned! 
THIS IS THIS I HAVE SEEED:
![Screenshot_20211228-115658211](https://user-images.githubusercontent.com/87223939/147548476-23424996-e237-4a12-a0ba-0047d09b9e88.jpg)

**Comment by GoneSubject** [comment]
ok
