### ISSUE TITLE
[BUG] <can't install mod>

### ISSUE THREAD

**Issue by DarkRiz** [PojavLauncherTeam/PojavLauncher#2474]
### Describe the bug

_can't install the mod, when I select the file optifine or labymod to install the mod, suddenly I come to the login menu, can anyone help?_  **[Android 10]**

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

Cant install mod :'(

### Platform

```markdown
- Device model: Vivo V2029
- CPU architecture:aarch64
- Android version: 10
- PojavLauncher version: 1.18
```

**Comment by GoneSubject** [comment]
what runtime you choose? if you choose runtime java 17 pls change back to runtime java 8

**Comment by DarkRiz** [comment]
OMG THANK YOU SO MUCH (GoneSubject1)

**Comment by DarkRiz** [comment]
> what runtime you choose? if you choose runtime java 17 pls change back to runtime java 8



> what runtime you choose? if you choose runtime java 17 pls change back to runtime java 8

Omg thank you it's working

**Comment by InfiniXDerg** [comment]
> > what runtime you choose? if you choose runtime java 17 pls change back to runtime java 8
> 
> > what runtime you choose? if you choose runtime java 17 pls change back to runtime java 8
> 
> Omg thank you it's working

Try to uninstall Java8 for force to use Java17

**Comment by DarkRiz** [comment]
java 8 when installing the mod, after installing the mod I changed it to
java 17

Pada tanggal Sel, 28 Des 2021 17:03, GoneSubject ***@***.***>
menulis:

**Comment by DarkRiz** [comment]
but i already know the solution

Pada tanggal Sel, 28 Des 2021 17:03, GoneSubject ***@***.***>
menulis:

**Comment by DarkRiz** [comment]
> > > what runtime you choose? if you choose runtime java 17 pls change back to runtime java 8
> > 
> > 
> > > what runtime you choose? if you choose runtime java 17 pls change back to runtime java 8
> > 
> > 
> > Omg thank you it's working
> 
> Try to uninstall Java8 for force to use Java17

Ok! thanks for telling the solution :)
