### ISSUE TITLE
[BUG] cannot launch 1.18.1 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2475]
### Describe the bug

When I launch 1.18.1 it crashes

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7784213/latestlog.txt)

### Steps To Reproduce

```markdown
2. Launch 1.18.1
3. Crash
```

### Expected Behavior

You know •_• I expected it to launch

### Platform

```markdown
- Device model:galaxy tab a 
- CPU architecture: armv8l 
- Android version: 11
- PojavLauncher version: crouscrus-v3_openjdk
___extras___
- jre: 17
```

### Anything else?

Nope ._.

**Comment by ghost** [comment]
Ummmmmm

**Comment by Suvambb** [comment]
Stop

**Comment by ghost** [comment]
WHAT

**Comment by ghost** [comment]
Can someone fix this

**Comment by ghost** [comment]
@Gonesubject1

**Comment by NotAHero04** [comment]
Create a file named `custom_env.txt` and write
> LIBGL_NOINTOVLHACK=1
>
into it.

**Comment by ghost** [comment]
> Create a file named `custom_env.txt` and write
> 
> > LIBGL_NOINTOVLHACK=1
> 
> into it.

??? Please give where to save a file???

**Comment by NotAHero04** [comment]
Oh, I didn't provide where to put the file lol
It should be in the launcher's folder (which contains `.minecraft`)

**Comment by NdraaGaminz** [comment]
Try this steps:
1.set the jre runtime to Jre17
2.set the renderer to Zink 4.6 or if you using Vtest crocus you can use VirGL 4.3 (if you use or) if not using Vtest Pojav, you can use zink 4.6 because you can't find VirGL 4.3 on crocus playstore
3.Instal and Launch Minecraft 1.18.0/1.18.1 (do not use 1.18 OptiFine if your device is not supporting it)
4.have fun playing 1.18

**Comment by NdraaGaminz** [comment]
> Can someone fix this

Try this steps:
1.set the jre runtime to Jre17
2.set the renderer to Zink 4.6 or if you using Vtest crocus you can use VirGL 4.3 (if you use or) if not using Vtest Pojav, you can use zink 4.6 because you can't find VirGL 4.3 on crocus playstore
3.Instal and Launch Minecraft 1.18.0/1.18.1 (do not use 1.18 OptiFine if your device is not supporting it)
4.have fun playing 1.18
Theres some steps that you need to launch 1.18
If it crash again, try download pojav launcher Vtest Pojav on Action menu and select "Vtest Fixed Flipped Screen" OR "Vtest Fixed Blackscreen on 1.13>" and if you already installed the app open the Vtest Pojav that you installed and select option and search for renderer, select the renderer to VirGL 4.3, and set the runtime to java17 and then launch 1.18.1, i've been tried this on my potato device realme c12 its working perfectly altought im lagging hehehe....

**Comment by ghost** [comment]
Ok and my lights went out so I'll try now
Edit: zink doesn't work for me
Edit again its impossible for me to create a .txt file in .minecraft bc I'm android 11 so I can't access it
Editttt I found a way now ._.
_IT CRASHED_

**Comment by ghost** [comment]
> Oh, I didn't provide where to put the file lol It should be in the launcher's folder (which contains `.minecraft`)

The game crashed

**Comment by ghost** [comment]
> > Can someone fix this
> 
> Try this steps: 1.set the jre runtime to Jre17 2.set the renderer to Zink 4.6 or if you using Vtest crocus you can use VirGL 4.3 (if you use or) if not using Vtest Pojav, you can use zink 4.6 because you can't find VirGL 4.3 on crocus playstore 3.Instal and Launch Minecraft 1.18.0/1.18.1 (do not use 1.18 OptiFine if your device is not supporting it) 4.have fun playing 1.18 Theres some steps that you need to launch 1.18 If it crash again, try download pojav launcher Vtest Pojav on Action menu and select "Vtest Fixed Flipped Screen" OR "Vtest Fixed Blackscreen on 1.13>" and if you already installed the app open the Vtest Pojav that you installed and select option and search for renderer, select the renderer to VirGL 4.3, and set the runtime to java17 and then launch 1.18.1, i've been tried this on my potato device realme c12 its working perfectly altought im lagging hehehe....

I'll try this

**Comment by NdraaGaminz** [comment]
> Ok and my lights went out so I'll try now Edit: zink doesn't work for me Edit again its impossible for me to create a .txt file in .minecraft bc I'm android 11 so I can't access it Editttt I found a way now ._. _IT CRASHED_

You can access the files by using zarchiever apk, download it on playstore for adding the file

**Comment by ghost** [comment]
_CRASH AGAINNNNNNNNNNN_
```markdown
1. Run 1.18.1
2. I'm using zink 4.6
3. CRASH
4. I'm Samsung galaxy tab a and cpu is armv8l
```

**Comment by ghost** [comment]
> > Ok and my lights went out so I'll try now Edit: zink doesn't work for me Edit again its impossible for me to create a .txt file in .minecraft bc I'm android 11 so I can't access it Editttt I found a way now ._. _IT CRASHED_
> 
> You can access the files by using zarchiever apk, download it on playstore for adding the file

Ik

**Comment by NdraaGaminz** [comment]
> Ok and my lights went out so I'll try now Edit: zink doesn't work for me Edit again its impossible for me to create a .txt file in .minecraft bc I'm android 11 so I can't access it Editttt I found a way now ._. _IT CRASHED_

Hmmm why zink 4.6 doesnt work for you? *YOUR DEVICE IS HIGH END*

**Comment by NdraaGaminz** [comment]
Thats not even makes any sense, his device is literaly high end but cant launch 1.18

**Comment by ghost** [comment]
> > Ok and my lights went out so I'll try now Edit: zink doesn't work for me Edit again its impossible for me to create a .txt file in .minecraft bc I'm android 11 so I can't access it Editttt I found a way now ._. _IT CRASHED_
> 
> Hmmm why zink 4.6 doesnt work for you? _YOUR DEVICE IS HIGH END_

I THINK MY DEVICE IS MED END BC WHEN I PLAY ROBLOX JAILBREAK IT CRASHED LOL

**Comment by ghost** [comment]
_this dosnt make sense_

**Comment by NdraaGaminz** [comment]
> > > Ok and my lights went out so I'll try now Edit: zink doesn't work for me Edit again its impossible for me to create a .txt file in .minecraft bc I'm android 11 so I can't access it Editttt I found a way now ._. _IT CRASHED_
> > 
> > 
> > Hmmm why zink 4.6 doesnt work for you? _YOUR DEVICE IS HIGH END_
> 
> I THINK MY DEVICE IS MED END BC WHEN I PLAY ROBLOX JAILBREAK IT CRASHED LOL

Then why i can launch 1.18.1... *EVEN WITH SHADER ON IT*

**Comment by ghost** [comment]
so how to fix can I use gl4es 1.1.5 with partial 3.2?

**Comment by NdraaGaminz** [comment]
> > > Ok and my lights went out so I'll try now Edit: zink doesn't work for me Edit again its impossible for me to create a .txt file in .minecraft bc I'm android 11 so I can't access it Editttt I found a way now ._. _IT CRASHED_
> > 
> > 
> > Hmmm why zink 4.6 doesnt work for you? _YOUR DEVICE IS HIGH END_
> 
> I THINK MY DEVICE IS MED END BC WHEN I PLAY ROBLOX JAILBREAK IT CRASHED LOL

Med end is enough to run everything on your phone

**Comment by NdraaGaminz** [comment]
> so how to fix can I use gl4es 1.1.5 with partial 3.2?

*USE ZINK 4.6 WHY YOU USING OPENGL 3.2*

**Comment by ghost** [comment]
so how to fix can I use gl4es 1.1.5 with partial 3.2?
My wifi and its raining  so delay

**Comment by NdraaGaminz** [comment]
> so how to fix can I use gl4es 1.1.5 with partial 3.2?

Hmmm, maybe you can fix it for using pojav launcher with VirGL 4.3 on it, because i can launch 1.18 because i use that version of pojav

**Comment by ghost** [comment]
BRUH ZINK CRASHES 1.18 ON MY DEVICE

**Comment by ghost** [comment]
Ok so how to get vir edition of pojav

**Comment by NdraaGaminz** [comment]
> BRUH ZINK CRASHES 1.18 ON MY DEVICE

Pojav launcher on playstore ia trash, it only can use the renderer that all of the phones cant support, so try use Vtest pojav to play 1.18

**Comment by ghost** [comment]
Hello how to get virgl32 edition of pojav

**Comment by ghost** [comment]
> > BRUH ZINK CRASHES 1.18 ON MY DEVICE
> 
> Pojav launcher on playstore ia trash, it only can use the renderer that all of the phones cant support, so try use Vtest pojav to play 1.18

HOW TO GET THAT

**Comment by ghost** [comment]
Hellllllo

**Comment by ghost** [comment]
how to get v test pojav

**Comment by NdraaGaminz** [comment]
> Ok so how to get vir edition of pojav

Download the app on pojav website and select Action menu, select Vtest Lib: Fixes Flipped Screen 
This maybe helped:
![Screenshot_2021-12-29-00-00-00-72](https://user-images.githubusercontent.com/95620914/147584381-f2ae0803-fec2-43ba-9e96-adde0cd726f4.jpg)
Go to Action menu and then select Vtest Lib: Fixes Flipped Screen
![Screenshot_2021-12-29-00-00-08-77](https://user-images.githubusercontent.com/95620914/147584446-738db327-43ce-45f3-be83-6cac0eccb3d2.jpg)

**Comment by ghost** [comment]
- ok

**Comment by NdraaGaminz** [comment]
> * ok

If you instal that pojav, you need to reinstal the versions, is it okay?

**Comment by ghost** [comment]
Download will take a lot of time for some reason so bye :)

**Comment by NdraaGaminz** [comment]
> Download will take a lot of time for some reason so bye :)

Ok see you tomorrow

**Comment by ghost** [comment]
OO

> > * ok
> 
> If you instal that pojav, you need to reinstal the versions, is it okay?

Wait

**Comment by ghost** [comment]
If you say reinstall  all versions? Lol I'll backup my versions folder :)

**Comment by NdraaGaminz** [comment]
> If you instal that pojav, you need to reinstal the versions, is it okay?

Because its a different version and app

**Comment by ghost** [comment]
Install done lol

**Comment by ghost** [comment]
So I can have two same apps? Or it will overwrite?

> > If you instal that pojav, you need to reinstal the versions, is it okay?
> 
> Because its a different version and app

**Comment by NdraaGaminz** [comment]
> If you say reinstall all versions? Lol I'll backup my versions folder :)

Yea, that maybe helpfull, but if it crash while you launch that version you've been backup, that says you need to instal again the version

**Comment by NdraaGaminz** [comment]
> So I can have two same apps? Or it will overwrite?
> 
> > > If you instal that pojav, you need to reinstal the versions, is it okay?
> > 
> > 
> > Because its a different version and app

Maybe you can if you have some app that can clone apps

**Comment by ghost** [comment]
> So I can have two same apps? Or it will overwrite?
> 
> > > If you instal that pojav, you need to reinstal the versions, is it okay?
> > 
> > 
> > Because its a different version and app

Pls answer

**Comment by ghost** [comment]
Ok

**Comment by NdraaGaminz** [comment]
> Ok

Already

**Comment by ghost** [comment]
Do my world's be deleted !!?

**Comment by NdraaGaminz** [comment]
> Do my world's be deleted !!?

Yes😁

**Comment by NdraaGaminz** [comment]
Backup it first

**Comment by ghost** [comment]
I'll backup MY 1GB OR LESS WORLDS _lol I'll just cut and paste so ez_

**Comment by ghost** [comment]
I'll let them deleted bc it will take a long time

**Comment by NdraaGaminz** [comment]
> I'll backup MY 1GB OR LESS WORLDS _lol I'll just cut and paste so ez_

Lol, ok

**Comment by ghost** [comment]
I HAVE MY IMPORTANT PVP KEUYBOARD SO KEYBOARDS GET DELETED??!

**Comment by ghost** [comment]
I'll backup them too

**Comment by ghost** [comment]
I'll install version now

**Comment by NdraaGaminz** [comment]
> I'll let them deleted bc it will take a long time

Hmmm, maybe my connection is even worst than you my download speed is just 2MB/S-7MB/S

**Comment by NdraaGaminz** [comment]
> I'll install version now

Okay...

**Comment by NdraaGaminz** [comment]
> I HAVE MY IMPORTANT PVP KEUYBOARD SO KEYBOARDS GET DELETED??!

Yes...backup the keyboard on pojav data>control key

**Comment by ghost** [comment]
PHEW I GOT TWO DIFFERENT  APPS WITHOUT  CLONE APP!

**Comment by ghost** [comment]
no need to backup it didn't  overwrite

**Comment by NdraaGaminz** [comment]
> PHEW I GOT TWO DIFFERENT APPS WITHOUT CLONE APP!

Wow, thats sick, i cant even do that

**Comment by ghost** [comment]
It will be hard time to identify which pojav is vtest lol

**Comment by NdraaGaminz** [comment]
> It will be hard time to identify which pojav is vtest lol

The version info is numbers

**Comment by NdraaGaminz** [comment]
> It will be hard time to identify which pojav is vtest lol

![Screenshot_2021-12-29-00-17-54-84](https://user-images.githubusercontent.com/95620914/147585847-d160e8ab-48f9-4002-a199-bb98e565f7f0.jpg)
Thats the version info

**Comment by ghost** [comment]
Ok and both apps same directory soo let's see if my crouscrus-v3_openjdk version did overwrite

**Comment by ghost** [comment]
I NOTICED THE ICON SIZE IS DIFFERENT

**Comment by ghost** [comment]
Bruh
YAY

**Comment by ghost** [comment]
MY DATA IS SAVED

**Comment by NdraaGaminz** [comment]
> MY DATA IS SAVED

Thats sick, 2 apps 1 data..even doesnt get overwrite

**Comment by NdraaGaminz** [comment]
Do you already tested the 1.18?, Is it work?

**Comment by ghost** [comment]
Bruh new settings screen and has the old launcher process id

**Comment by ghost** [comment]
> Do you already tested the 1.18?, Is it work?

I'll test soon

**Comment by ghost** [comment]
Bruh I can do crossplay java on 1 device my special pop-up window feature

**Comment by NdraaGaminz** [comment]
![Screenshot_2021-12-29-00-22-17-82_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/95620914/147586239-79327d20-bf73-4cd6-84f2-99a617d78b33.jpg)
This is what its looks like when you wanna select a renderer
And don't forget to use *Java17*
![Uploading Screenshot_2021-12-29-00-22-24-64_67a64f1fc1b88908dad3392f76c1969b.jpg…]()

**Comment by NdraaGaminz** [comment]
> Bruh I can do crossplay java on 1 device my special pop-up window feature

Damn

**Comment by ghost** [comment]
First I'll setup mykeyboard wait

**Comment by NdraaGaminz** [comment]
> First I'll setup mykeyboard wait

Ok

**Comment by ghost** [comment]
Lol I noticed that dir name of vtest pojav is net.kdt.pojavlaunch.debug

**Comment by NdraaGaminz** [comment]
> First I'll setup mykeyboard wait

Btw, im playing some bedwars using an otg connection keyboard and mouse

**Comment by ghost** [comment]
Wait

**Comment by NdraaGaminz** [comment]
> Lol I noticed that dir name of vtest pojav is net.kdt.pojavlaunch.debug

Yea, its changed to debug on the last name

**Comment by ghost** [comment]
Do you have time to join my minecraft server java 1.12.2?

**Comment by ghost** [comment]
My server ip is Cube4x49999.aternos.me:58848
I'll start server if you want to join with me plsssss

**Comment by ghost** [comment]
Can you join my server?

**Comment by ghost** [comment]
I'll see you tomorrow  bye :1st_place_medal:

**Comment by NdraaGaminz** [comment]
> My server ip is Cube4x49999.aternos.me:58848 I'll start server if you want to join with me plsssss

Ok i'll join but tomorrow ok?

**Comment by NdraaGaminz** [comment]
> Do you have time to join my minecraft server java 1.12.2?

Oh sure i can join it

**Comment by ghost** [comment]
> My server ip is Cube4x49999.aternos.me:58848 I'll start server if you want to join with me plsssss

This is issue pages not ads

**Comment by NdraaGaminz** [comment]
> This is issue pages not ads

Try scroll up if its not an issue lol

**Comment by ghost** [comment]
> > This is issue pages not ads
> 
> Try scroll up if its not an issue lol

Ik but why the issue become be a ads

**Comment by ghost** [comment]
Also about 1.18.1 crash 
Use this assest 
[assets-1.18.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7785610/assets-1.18.zip)
And edit options.txt 

And use gl4es 1.1.5 and try launch

**Comment by ghost** [comment]
For more information join Official PojavLauncher Discird Server https://discord.gg/nhyx2K4Q

**Comment by NdraaGaminz** [comment]
> > > This is issue pages not ads
> > 
> > 
> > Try scroll up if its not an issue lol
> 
> Ik but why the issue become be a ads

Because the issue is already Fixed, hes just need to instal VirGL bacause he cant use zink and the important thing is, 1.17 to 1.18.1 cant use GL renderer less than 4

**Comment by NdraaGaminz** [comment]
You can see that renderer (OpenGL 3) 3.2 (not even supported 1.17)

**Comment by ghost** [comment]
> > > > This is issue pages not ads
> > > 
> > > 
> > > Try scroll up if its not an issue lol
> > 
> > 
> > Ik but why the issue become be a ads
> 
> Because the issue is already Fixed, hes just need to instal VirGL bacause he cant use zink and the important thing is, 1.17 to 1.18.1 cant use GL renderer less than 4

If fixed just close the issue
Also about virgl just download pojavlauncher from latest build

**Comment by ghost** [comment]
I'm doing 1.18 now

**Comment by NdraaGaminz** [comment]
> If fixed just close the issue Also about virgl just download pojavlauncher from latest build

Im not the creator of this issue, talk to the person who Made this issue

**Comment by ghost** [comment]
1.18 is installing

**Comment by NdraaGaminz** [comment]
> 1.18 is installing

Ok

**Comment by ghost** [comment]
With virgl it crashed And I gtg

**Comment by NdraaGaminz** [comment]
> Also about 1.18.1 crash Use this assest [assets-1.18.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7785610/assets-1.18.zip) And edit options.txt
> 
> And use gl4es 1.1.5 and try launch

*WHY I CAN RUN 1.18 WOTHOUT THAT ASSETS*

**Comment by NdraaGaminz** [comment]
> With virgl it crashed And I gtg

Welp the problem, maybe your device cant run 1.18

**Comment by NdraaGaminz** [comment]
Wait i'll try to launch it

**Comment by NdraaGaminz** [comment]
The logs
![Uploading Screenshot_2021-12-29-00-50-45-44_67a64f1fc1b88908dad3392f76c1969b.jpg…]()
The menu screen:
![Uploading Screenshot_2021-12-29-00-52-34-24_67a64f1fc1b88908dad3392f76c1969b.jpg…]()
Servers (im already add your server)
![Uploading Screenshot_2021-12-29-00-53-36-98_67a64f1fc1b88908dad3392f76c1969b.jpg…]()

**Comment by ghost** [comment]
> > Also about 1.18.1 crash Use this assest [assets-1.18.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7785610/assets-1.18.zip) And edit options.txt
> > And use gl4es 1.1.5 and try launch
> 
> _WHY I CAN RUN 1.18 WOTHOUT THAT ASSETS_

What rendering u use?

**Comment by NdraaGaminz** [comment]
> With virgl it crashed And I gtg

Sorry for not Helping...i've been try

**Comment by NdraaGaminz** [comment]
> > > Also about 1.18.1 crash Use this assest [assets-1.18.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7785610/assets-1.18.zip) And edit options.txt
> > > And use gl4es 1.1.5 and try launch
> > 
> > 
> > _WHY I CAN RUN 1.18 WOTHOUT THAT ASSETS_
> 
> What rendering u use?

![Screenshot_2021-12-29-00-22-17-82_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/95620914/147589402-284c1240-4170-4984-87c9-4fd0f7bb8afc.jpg)
VirGL 4.3

**Comment by NekoIceCream** [comment]
So i will say it 


Gl4es cant run 1.18 coz 1.18 need opengl 3.2+ and gl4es use opengl 2.0
Q : So how 1.18 its work in gl4es? Nah 
A : nah we make shader patch and make gl4es work to lauch 1.18

Q : so why i can run 1.18 without assest file?
A : nah maybe u use zink or virgl (like I said earlier "1.18 need opengl 3.2+

Zink use opengl 4.6
And virgl use opengl 4.3
But i dont recomended run 1.18 with virgl (for yet)

**Comment by ghost** [comment]
> > > > Also about 1.18.1 crash Use this assest [assets-1.18.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7785610/assets-1.18.zip) And edit options.txt
> > > > And use gl4es 1.1.5 and try launch
> > > 
> > > 
> > > _WHY I CAN RUN 1.18 WOTHOUT THAT ASSETS_
> > 
> > 
> > What rendering u use?
> 
> ![Screenshot_2021-12-29-00-22-17-82_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/95620914/147589402-284c1240-4170-4984-87c9-4fd0f7bb8afc.jpg) VirGL 4.3

So i will say it 


Gl4es cant run 1.18 
coz 1.18 need opengl 3.2+ and 
gl4es use opengl 2.0

Q : So how 1.18 its work in gl4es?  
A : Nah we make shader patch (assest file) and make gl4es work to lauch 1.18

Q : so why i can run 1.18 without assest file?
A : nah maybe u use zink or virgl (like I said earlier "1.18 need opengl 3.2+

Zink use opengl 4.6
And virgl use opengl 4.3
But i dont recomended run 1.18 with virgl (for yet)

**Comment by khanhduytran0** [comment]
> 1.17 to 1.18.1 <ins>cant</ins> use GL renderer <ins>less than</ins> 4

@NdraaGaminz 
1.18.1 still uses OpenGL 3.2 Core Profile as **minimum**, which most used functions already existed in OpenGL ES 3.0 or emulated in gl4es. 
`no 1.17 supported yet` specifies that it **doesn’t natively support** it, but requires an external component, which is the `assets-v0.zip`

For 1.18.x, virglrenderer is recommended in case of crashing after joining world for a few seconds (by setting high render distance) on Adreno GPU with gl4es. However, it has a transparency bug on textures.

**Comment by khanhduytran0** [comment]
> Pojav launcher on playstore ia trash, it only can use the renderer that all of the phones cant support

Are you expecting to run SEUS PTGI E12 on a 6-years-old device technology? That’s probably what iOS devices can do, but not Android devices at that time. *Also read the big line at the bottom*.

> Hmmm why zink 4.6 doesnt work for you? YOUR DEVICE IS HIGH END

\<Any\> end doesn’t matter, it’s just Zink is slow (new version can change my mind but rendering doesn’t work for some reasons) *and the big line at the bottom*.

> USE ZINK 4.6 WHY USING OPENGL 3.2

**Why?** There’s no point to use Zink, unless you’re going to play with shaders. *Also read the line below*

## Zink is experimental after all and has never been designed for mobile GPU, please don’t expect much!

**Comment by ghost** [comment]
> Virgl crashes on my devicee is there any patch for 1.18.1??

I don't care bc it's fixed

**Comment by ghost** [comment]
> Oh, I didn't provide where to put the file lol It should be in the launcher's folder (which contains `.minecraft`)

Fixed and  I put txt file inside .minecraft and now I put where .minecraft is located

**Comment by ghost** [comment]
I didn't load  a world ill load a world soon

**Comment by ghost** [comment]
Thanks @NotAHero04

**Comment by GoneSubject** [comment]
> Thanks @NotAHero04

there's like 3 helpers in here and you just thanks to 1 person and mentions them

**Comment by ghost** [comment]
Lol

**Comment by ghost** [comment]
### something off-topic
```markdown
Local helper ={
"Helpers name"
}
Local solver 
Issue.helpers.bestHelper:connect(function(helper)
   For I,v in pairs(helper) do
      If helper.name == notahero04 then
         Solver = notahero04
      End
   End
End)
```
### Roblox studio skilz on issuepage lel
I'm just felling to display my game https://web.roblox.com/games/4901926257/hard-obby
### _PLEASE REPLY OR ADD REACTION_

**Comment by ghost** [comment]
I'll test 1.18.1 world

**Comment by ghost** [comment]
### THE BUG IS NOT FIXED!
### HERES THE LATESTLOG
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7787469/latestlog.txt)

**Comment by ghost** [comment]
> ### THE BUG IS NOT FIXED!
> ### HERES THE LATESTLOG
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7787469/latestlog.txt)

BUG found

**Comment by ghost** [comment]
I'll try this on vtest pojav now

**Comment by ghost** [comment]
Crash on vtest too

**Comment by GoneSubject** [comment]
> ### THE BUG IS NOT FIXED!
> ### HERES THE LATESTLOG
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7787469/latestlog.txt)

use the right assets-v0 and the patcher
> [05:31:20] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible

**Comment by ghost** [comment]
i doing minecraft pc now ill do it later ._.

**Comment by ghost** [comment]
> > ### THE BUG IS NOT FIXED!
> > ### HERES THE LATESTLOG
> > [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7787469/latestlog.txt)
> 
> use the right assets-v0 and the patcher
> 
> > [05:31:20] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible

btw give link to right patcher and right assets-v0

**Comment by GoneSubject** [comment]
> > > ### THE BUG IS NOT FIXED!
> > > ### HERES THE LATESTLOG
> > > [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7787469/latestlog.txt)
> > 
> > use the right assets-v0 and the patcher
> > 
> > > [05:31:20] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible
> 
> btw give link to right patcher and right assets-v0

[here](https://cdn.discordapp.com/attachments/724163890803638277/892912425366589460/assets-v0.zip) is the assets-v0 [here](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar) is the patcher

**Comment by ghost** [comment]
### _thanks_
thx and im making a game now ._.
### IF YOU HAVE ROBLOX
if you have roblox heres the game
https://web.roblox.com/games/4901926257/hard-obby
and my acc name is computerph1

**Comment by GoneSubject** [comment]
> ### _thanks_
> thx and im making a game now ._.
> ### IF YOU HAVE ROBLOX
> if you have roblox heres the game
> https://web.roblox.com/games/4901926257/hard-obby
> and my acc name is computerph1

ok?

**Comment by ghost** [comment]
> [here](https://cdn.discordapp.com/attachments/724163890803638277/892912425366589460/assets-v0.zip) is the assets-v0 [here](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar) is the patcher

### does this work on tlauncher/minecraft pc?
### pls quick reply

**Comment by ghost** [comment]
> > [here](https://cdn.discordapp.com/attachments/724163890803638277/892912425366589460/assets-v0.zip) is the assets-v0 [here](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar) is the patcher
> 
> ### does this work on tlauncher/minecraft pc?
> ### pls quick reply

@GoneSubject1 can you reply quickly??! pls
or your connection is worst lol

**Comment by GoneSubject** [comment]
> > [here](https://cdn.discordapp.com/attachments/724163890803638277/892912425366589460/assets-v0.zip) is the assets-v0 [here](https://cdn.discordapp.com/attachments/724163890803638277/917260054086955028/Pojav117AssetsPatcher.jar) is the patcher
> 
> ### does this work on tlauncher/minecraft pc?
> ### pls quick reply
> 

no

**Comment by khanhduytran0** [comment]
@ROBLOXstudioDev *I smell Markdown abusing*
# like this

**Comment by ghost** [comment]
ok ._.

**Comment by ghost** [comment]
@khanhduytran0 WHAT?

**Comment by ghost** [comment]
what is difference between pojav playstore and pojav vtest??

**Comment by GoneSubject** [comment]
> what is difference between pojav playstore and pojav vtest??

hm alot vtest is like just testing some enhancement requests from people in PojavLauncher github i think the playstore version is the stable version so we recommend you to use that

**Comment by ghost** [comment]
ok
### if you got this message put on tick on box

- [x] you got this message

**Comment by ghost** [comment]
what is difference between gl4es 1.1.5 and gl4es 1.1.5 + partial 3.2?

**Comment by ghost** [comment]
ill do 1.18.1 patch now...

**Comment by GoneSubject** [comment]
> what is difference between gl4es 1.1.5 and gl4es 1.1.5 + partial 3.2?

wdym?

**Comment by ghost** [comment]
Can you resend assets v0 bc I can't download it :(

**Comment by ghost** [comment]
> Can you resend assets v0 bc I can't download it :(


### RESEND QUICKKK

**Comment by khanhduytran0** [comment]
> ### _thanks_
> thx and im making a game now ._.
> 
> ### IF YOU HAVE ROBLOX
> if you have roblox heres the game https://web.roblox.com/games/4901926257/hard-obby and my acc name is computerph1

# *nothing to do with this issue*

**Comment by khanhduytran0** [comment]
> > Can you resend assets v0 bc I can't download it :(
> 
> ### RESEND QUICKKK

Can't you just scroll up?

**Comment by GoneSubject** [comment]
> > > Can you resend assets v0 bc I can't download it :(
> > 
> > 
> > ### RESEND QUICKKK
> 
> Can't you just scroll up?

i don't have time bro

**Comment by khanhduytran0** [comment]
If it gives access denied, head to the instruction page.

Also
> ### RESEND QUICKKK

~~You act like today is the final day that you can use PojavLauncher.~~

**Comment by ghost** [comment]
THE DOWNLOAD LINK DOSNT WORKKKK

**Comment by ghost** [comment]
Where is instruction page do you mean
Https://PojavLauncherTeam.github.io

**Comment by GoneSubject** [comment]
> Where is instruction page do you mean pojavlauncher.github.io ?

full instructions is [here](https://pojavlauncherteam.github.io/updates/117.html), follow [here](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04) too to have the patch

**Comment by ghost** [comment]
Thx got it 
# do I need to put assets v0 on .minecraft/resourcepacks?
# and install patch like a .jar install?

[High qualati](https://Pojavlauncherteam.github.io)

**Comment by ROBLOXstudioDev** [comment]
#### Can someone
### make a video to how to do this 
# please I have problems if I do in my own ._.
**HERES THE LOG FILE**
# [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7789676/latestlog.txt)

**Comment by ghost** [comment]
#### Can someone
 ### make a video to how to do this
 # please I have problems if I do in my own ._.
 **HERES THE LOG FILE**

 # [latestlog.txt](https://www.youtube.com/watch?v=IVYM_0oYnKU)
REPLY QUICKKK

**Comment by GoneSubject** [comment]
> Thx got it 
> # do I need to put assets v0 on .minecraft/resourcepacks?
> # and install patch like a .jar install?
> 
> [High qualati](https://Pojavlauncherteam.github.io)
> 

answer both question: yes

**Comment by ghost** [comment]
PLSSS HELPPP ^

**Comment by ghost** [comment]
> #### Can someone
> ### make a video to how to do this
> # please I have problems if I do in my own ._.
> **HERES THE LOG FILE**
> 
> # [latestlog.txt](https://www.youtube.com/watch?v=IVYM_0oYnKU)
> REPLY QUICKKK

Thissss

**Comment by GoneSubject** [comment]
>  #### Can someone
>  ### make a video to how to do this
>  # please I have problems if I do in my own ._.
>  **HERES THE LOG FILE**
> 
>  # [latestlog.txt](https://www.youtube.com/watch?v=IVYM_0oYnKU) this is the real one
> REPLY QUICKKK 

welp there some video how to play 1.18 on youtube

**Comment by ghost** [comment]
Lel rickroll

**Comment by GoneSubject** [comment]
> > #### Can someone
> > ### make a video to how to do this
> > # please I have problems if I do in my own ._.
> > **HERES THE LOG FILE**
> > 
> > # [latestlog.txt](https://www.youtube.com/watch?v=IVYM_0oYnKU)
> > REPLY QUICKKK
> 
> Thissss

send the log bro why a video

**Comment by ghost** [comment]
Ok

**Comment by ROBLOXstudioDev** [comment]
[Latestlog.txt](https://www.youtube.com/watch?v=IVYM_0oYnKU)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7789709/latestlog.txt)
[Latestlog.txt](https://www.youtube.com/watch?v=IVYM_0oYnKU)

**Comment by ROBLOXstudioDev** [comment]
Rep.y pls

**Comment by GoneSubject** [comment]
> [Latestlog.txt](https://www.youtube.com/watch?v=IVYM_0oYnKU)
> [Latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7789709/latestlog.txt)
> [Latestlog.txt](https://www.youtube.com/watch?v=IVYM_0oYnKU)
> 

hm i think wait for others to help because it's looks strange to me

**Comment by ROBLOXstudioDev** [comment]
Bruh

**Comment by ROBLOXstudioDev** [comment]
BYE

**Comment by WesleyVanNeck** [comment]
YOU HAVE TO UPDATE THE  assets-v0.zip MANUELY

**Comment by LegacyGamerHD** [comment]
the default  assets-v0.zip is compatible with 1.18 and 1.18 one isnt backwards compatible

**Comment by WesleyVanNeck** [comment]
the default assets-v0.zip is not compatible with 1.18 and 1.18 one isnt backwards compatible

**Comment by khanhduytran0** [comment]
Blocked for spamming.
What you have to do:
- Carefully follow the instruction.
- Delete/move per-version-config.json elsewhere if you pressed OK instead of Play Anyways.
- Additionally, follow instructions on YouTube.
