### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Agghio** [PojavLauncherTeam/PojavLauncher#2476]
### Describe the bug

For start 1.18,I need to download a resuource pack as said,but the link don't work

### Steps To Reproduce

```markdown
Open pojavlauncher,tap news in news selection,and where it says click here for download the resource pack
```

### Expected Behavior

I expected to the page to open and make me download the resource pack

### Platform

```markdown
- Device model: Huawei p9
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: [Latest Release|| version 3.3.1.1_rel_20210206
```

**Comment by GoneSubject** [comment]
welp uh the full instructions to play 1.18 is [here](https://pojavlauncherteam.github.io/updates/117.html) then [here](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)

**Comment by ghost** [comment]
@GoneSubject1 what is your server invite again

**Comment by GoneSubject** [comment]
> @GoneSubject1 what is your server invite again

what server 👀

**Comment by ghost** [comment]
Ur discord

**Comment by ghost** [comment]
And did your acc got  deleted?
Hello? Plsssss replyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

> l
L
L

**Comment by ghost** [comment]
@GoneSubject1 hello send invitation of discord server and did you delete your old acc?

- [x]  is your old acc deleted?

**Comment by GoneSubject** [comment]
> @GoneSubject1 hello send invitation of discord server and did you delete your old acc?
> 
> - [ ]  is your old acc deleted?
> 
> 

wdym?

**Comment by ghost** [comment]
Your discord server invite
And I mean you old gonesubject acc and now it's gonesubject
Helllllooooooooooo pls replyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by GoneSubject** [comment]
> Your discord server invite
> And I mean you old gonesubject acc and now it's gonesubject1

first I don't have my own server discord second yes somehow i delete my old account but i can't name my new account to GoneSubject so i change the name to GoneSubject1

**Comment by ghost** [comment]
HOW YOU DID IT SO QUICK REPLY

**Comment by GoneSubject** [comment]
> HOW YOU DID IT SO QUICK REPLY

idk fast hand i guess

**Comment by ghost** [comment]
And btw you know you invited me to a discord server you know
_and nobodys know my open issue yet ._._
Oof thunderstorm in my area ://
Pls reply again ._.

**Comment by GoneSubject** [comment]
> And btw you know you invited me to a discord server you know
> _and nobodys know my open issue yet ._._
> Oof thunderstorm in my area ://
> Pls reply again ._.

welp uh that invite is not my server

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
I HAVE A ISSUE LINK IS WAIT
OOF THUNDERSTORM AAAAAAAAAAAAAAAA

**Comment by ghost** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/2475

**Comment by ghost** [comment]
`AAAAAAAAAAAAAAA`

**Comment by ghost** [comment]
BYEEE

**Comment by NotAHero04** [comment]
No log provided. If your issue is the same as #2475, you may want to take a look at it.

**Comment by NotAHero04** [comment]
Also update your launcher. 1.18 requires Java 17 which can only be installed in newer versions of the launcher.

**Comment by ghost** [comment]
> No log provided. If your issue is the same as #2475, you may want to take a look at it.

R u helper?

**Comment by ghost** [comment]
I HAVE JRE 17 LOL

**Comment by ghost** [comment]
Oh this is not my issue sorry lol

**Comment by GoneSubject** [comment]
> > No log provided. If your issue is the same as #2475, you may want to take a look at it.
> 
> R u helper?

yes he's like android helper's god

**Comment by NdraaGaminz** [comment]
Close this fucking issue,  this is not even a bug.

**Comment by khanhduytran0** [comment]
Fixed dead link
