### ISSUE TITLE
[F-Req] VirGL shader support?

### ISSUE THREAD

**Issue by NdraaGaminz** [PojavLauncherTeam/PojavLauncher#2477]
### Is this request related to a bug?

No

### Describe the request.

If VirGL is fully support the shaders thats will be so amazing because, its gonna have a lot of fun using a shader with no lag's using a VirGL renderer, different from Zink 4.6 support but laggy

**Comment by NotAHero04** [comment]
Oh, it did! You can try some shaders now like BSL ~~or SEUS PTGI E12~~

**Comment by NdraaGaminz** [comment]
> Oh, it did! You can try some shaders now like BSL ~or SEUS PTGI E12~

Ah yes, he said its support now but...
![Screenshot_2021-12-27-20-59-21-02_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/95620914/147587078-3d82a211-ec8f-4c81-9278-5055d0fff647.jpg)
The godrays doesnt renderer

**Comment by NotAHero04** [comment]
Well, the shaders are all written with PC targets in mind, so they may not bring all the features to unsupported GPUs on mobile.

**Comment by Iarkont** [comment]
You can try "makeup ultra-fast" shaders. They work almost perfectly and give a good fps at low-to-medium shader graphics settings.

**Comment by imjustpenguin** [comment]
![Screenshot_20220131_190431](https://user-images.githubusercontent.com/96688215/152183704-a35c4dc5-f320-4b69-8304-77e2aac335a9.jpg)
😃

**Comment by Mathias-Boulay** [comment]
We don't make virgl, as such we cannot support it
