### ISSUE TITLE
[Game Exited error when starting 1.18.1] 

### ISSUE THREAD

**Issue by Akshay-303** [PojavLauncherTeam/PojavLauncher#2479]
### Describe the bug

The error says : Game Exited 
I have installed the runtime java 17 and tried all the renders

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7787370/latestlog.txt)
![Screenshot_2021-12-29-10-20-13-323_net kdt pojavlaunch](https://user-images.githubusercontent.com/96807848/147628696-88babe19-668d-442d-99e3-87618baef676.jpg)

### Steps To Reproduce

```markdown
Start Pojav launcher

Select version 1.18.1

Clicks Play 

The buttons and a black screen appears for sometime

After sometime game exited error happens
```

### Expected Behavior

I expected the game to open

### Platform

```markdown
- Device model: Poco m2 (india) 
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest version on play store
```

### Anything else?

pls help

**Comment by Akshay-303** [comment]
PLS HELP

**Comment by GoneSubject** [comment]
> PLS HELP

wow you want help while you didn't send send the log? send or no help

**Comment by Akshay-303** [comment]
> > PLS HELP
> 
> wow you want help while you didn't send send the log? send or no help

I don't know what's that so i didnot

**Comment by GoneSubject** [comment]
> > > PLS HELP
> > 
> > wow you want help while you didn't send send the log? send or no help
> 
> I don't know what's that so i didnot

send the latestlog.txt
> The log file called latestlog.txt is located under sdcard/Android/data/net.kdt.pojavlaunch/files or sdcard/games/PojavLauncher. You may need to activate an option in your file explorer to see hidden files and folders

**Comment by Akshay-303** [comment]
> > > > PLS HELP
> > > 
> > > 
> > > wow you want help while you didn't send send the log? send or no help
> > 
> > 
> > I don't know what's that so i didnot
> 
> send the latestlog.txt
> 
> > The log file called latestlog.txt is located under sdcard/Android/data/net.kdt.pojavlaunch/files or sdcard/games/PojavLauncher. You may need to activate an option in your file explorer to see hidden files and folders

Ok wait

**Comment by Akshay-303** [comment]
> > > > PLS HELP
> > > 
> > > 
> > > wow you want help while you didn't send send the log? send or no help
> > 
> > 
> > I don't know what's that so i didnot
> 
> send the latestlog.txt
> 
> > The log file called latestlog.txt is located under sdcard/Android/data/net.kdt.pojavlaunch/files or sdcard/games/PojavLauncher. You may need to activate an option in your file explorer to see hidden files and folders

Hey i have edited it and sent the log file as well as the screen shot of the issue

**Comment by Akshay-303** [comment]
Update : I installed 1.18 version on pojav and was crashing with game exited after the mojang screen appeared 

When changed the renderer to zink then the game opened completely but was lagging like hell. 

1.18.1 still shows game exited when at black screen
Pls help

**Comment by GoneSubject** [comment]
> Update : I installed 1.18 version on pojav and was crashing with game exited after the mojang screen appeared
> 
> When changed the renderer to zink then the game opened completely but was lagging like hell.
> 
> 1.18.1 still shows game exited when at black screen Pls help

sorry for replying long but look like you need to follow [this](https://pojavlauncherteam.github.io/updates/117.html) then [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)
> [04:51:02] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible

**Comment by Akshay-303** [comment]
> > Update : I installed 1.18 version on pojav and was crashing with game exited after the mojang screen appeared
> > When changed the renderer to zink then the game opened completely but was lagging like hell.
> > 1.18.1 still shows game exited when at black screen Pls help
> 
> sorry for replying long but look like you need to follow [this](https://pojavlauncherteam.github.io/updates/117.html) then [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)
> 
> > [04:51:02] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible

Thanks man for sure gonna try this

**Comment by khanhduytran0** [comment]
Closing until further response.

**Comment by MarcyIgop** [comment]
still not working 2 me :/
