### ISSUE TITLE
[BUG] Server data compromised

### ISSUE THREAD

**Issue by Pojavuser1979** [PojavLauncherTeam/PojavLauncher#2481]
### Describe the bug

Hey, i made a server for my friends to play on, i started the server and then logged off but when i returned my inventory was empty and the skin changed anyone know how to fix

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Join a server
3. Get something in your inv and log off
4. Return in 1 or 2 hours
```

### Expected Behavior

I expect the game to launches

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by vasu123432141** [comment]
Maybe u logged in from other account or u play only for 5 or 10 mins

**Comment by khanhduytran0** [comment]
Server data isn’t stored in the client side. It should be stored in the server side. Check your server’s database, also check if the inventory data lost when playing on PC **with a valid online account**.
