### ISSUE TITLE
[F-Req] Proper physical mouse support (Bluetooth / USB-OTG)?

### ISSUE THREAD

**Issue by ggmoritz** [PojavLauncherTeam/PojavLauncher#2483]
### Describe the request.

You can connect mouse and keyboard via USB-OTG or via Bluetooth. Actually, Pojav perfectly supports my keyboard already. The mouse also kinda works, but it is very jerky and updates rarely. So I was wondering if the current "support" is intentional and I of course would wish for smooth mouse movements :)
 

### Anything else?

Huge respect for this project! even the performance is amazing on my tablet

**Comment by Mathias-Boulay** [comment]
Well, we basically update as soon as android sends us data
But the gplay builds may be a little sluggish compared to dev builds
