### ISSUE TITLE
[BUG] ram problem

### ISSUE THREAD

**Issue by efeakdag** [PojavLauncherTeam/PojavLauncher#2485]
### Describe the bug

i have a tablet with 4gb ram but i can open up to 2835mb ram

### Steps To Reproduce

```markdown
1. I download pojavlahuncer from play store
2. I turn on the memory allocation option max
3. only goes up to 2835mb
```

### Expected Behavior

I want the ram settings to be fixed, this was not available in old versions

### Platform

```markdown
- Device model: Casper Via s30
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk and sürüm crocus-301-7df8559ad-v3_openjdk (debug no recuntime)
```

**Comment by artdeell** [comment]
You probably didn't know:
Other applications on your device, Android itself and the Linux kernel which Android runs on take some RAM for themselves, so you can't just allocate all of your device's memory
