### ISSUE TITLE
[BUG] <Short description> error code -1

### ISSUE THREAD

**Issue by fand1l** [PojavLauncherTeam/PojavLauncher#2486]
### Describe the bug

Application exited with code -1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7794462/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download JRE17
2. Starting pojav launcher
3. Choose a manager runtime JRE17
4. Choose a Minecraft version 1.18.1
5. Starting game
```

### Expected Behavior

I expect the game to launched

### Platform

```markdown
- Device model: Motorola e7 plus 4/64G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest release
```

**Comment by GoneSubject** [comment]
make sure to follow [this](https://pojavlauncherteam.github.io/updates/117.html) then [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04), send the latestlog.txt if still crash
> [19:54:26] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible

**Comment by khanhduytran0** [comment]
No response moment.
