### ISSUE TITLE
 Bug de mause[BUG] <Short description>

### ISSUE THREAD

**Issue by Sebasleve** [PojavLauncherTeam/PojavLauncher#2487]
### Describe the bug

Hola hay un bug no muy molesto pero si llega a fastidiar cuando conectas un mause externo cuando muevo el mause y el juego la la mira o la cámara xd se mueve muy raro como un poco travada como si estuviera lageada  pero el juego va a 100 fpsy cuando muevo el mause el juego no detecta muy bien ese movimiento  espero que se lea vien esque lo traduci por Google Hello there is a bug that is not very annoying but it does get annoying when you connect an external mause when I move the mause and the game looks at it or the camera xd moves very strange as a bit stuck as if it were lagged but the game goes to 100 fpsy When I move the mouse the game does not detect that movement very well I hope it is read well, I translated it by Google

### The log file and images/videos

.

### Steps To Reproduce

```markdown
Entrar al pojavlauncher 
Juegar o entrar una partida y mover el mause hacia lo lado
```

### Expected Behavior

Que la mira o la caramara valla bien y sin lag 

### Platform

```markdown
- no me acuerdo xd 
- CPU architecture: arm
- Android version: 10
- PojavLauncher version: play store
```

### Anything else?

Si no se tradujo  bien pues xd

**Comment by Mathias-Boulay** [comment]
Ah yes, english.

**Comment by Mathias-Boulay** [comment]
Such problems aren't reproducible on dev builds though.
And if they still happen, we can't make anything since we treat them as fast as android sends them to us
