### ISSUE TITLE
[BUG] I hate ptrace

### ISSUE THREAD

**Issue by kl1024** [PojavLauncherTeam/PojavLauncher#2488]
### Describe the bug

Application crashed when loaded a world in vanilla/optifine version of 1.18.x

### The log file and images/videos

[latestlog_1181of.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7796435/latestlog_1181of.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start 1.18.1-OptiFine_HD_U_H4
3. Load a World
4. Crash
```

### Expected Behavior

I expect the game running as normal

### Platform

```markdown
- Device model: Mi Note 3
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-300-c1de44dd1-v3_openjdk
```

**Comment by Shromeyy** [comment]
To me the game didn't crash when I launch 1.18.1 optifine, everything just look black

**Comment by GoneSubject** [comment]
> To me the game didn't crash when I launch 1.18.1 optifine, everything just look black

it is loading the game so pls wait at least 5 minutes if it still black pls wend the latestlog.txt

**Comment by GoneSubject** [comment]
> The log file and images/videos
latestlog_1181of.txt

the log4j messed up

**Comment by khanhduytran0** [comment]
@kl1024 the ptrace that you're taking about: https://chromium.googlesource.com/crashpad/crashpad/+/refs/heads/main/util/linux/scoped_ptrace_attach.cc#27
It has nothing to do with the crash.

.
--
Try lowering render distance.
