### ISSUE TITLE
Cant download forge or anything 

### ISSUE THREAD

**Issue by Hothead1** [PojavLauncherTeam/PojavLauncher#2489]
### Describe the bug

Doesnt let me drag the mouse to click install of forge

### The log file and images/videos

Doesnt let me drag the mouse to click install on forge

### Steps To Reproduce

```markdown
When i click options and then launch a mod installer i find forge i click it and it does all the log stuff i click the x, but i cant drag the mouse on this part to click install, i can drag the mouse actually in game
```

### Expected Behavior

Im not really sure because i haven't been able to use forge because of the issue stated above however, without any mods it runs just fine with no issues

### Platform

```markdown
- Device model : 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Anonimusmasked** [comment]
Doesnt let me drag the mouse to click install of forge

**Comment by GoneSubject** [comment]
fill the platform info

**Comment by khanhduytran0** [comment]
Incomplete info. Closing until further response.
