### ISSUE TITLE
[BUG] Minecraft 1.12.2 Crash

### ISSUE THREAD

**Issue by 1493028** [PojavLauncherTeam/PojavLauncher#2490]
### Describe the bug

I played Pojav launcher for 2 To 5 minutes then it crashes by itself

### Steps To Reproduce

```markdown
1. Open Pojav launcher
2. Play on version 1.12.2 
3. Crash
```

### Expected Behavior

Crash itself When I play for 2 to 5 minutes

### Platform

```markdown
- Device model: Vivo y50
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version: playstore version crocus V3 jdk
```

**Comment by 1493028** [comment]
Only on version 1.12.2 btw

**Comment by khanhduytran0** [comment]
The log file is missing.

**Comment by 1493028** [comment]
> The log file is missing.

No log bro It crashes as soon as I play for 2 to 5 minutes I've used optifine it still crashes

**Comment by khanhduytran0** [comment]
> > The log file is missing.
> 
> No log bro It crashes as soon as I play for 2 to 5 minutes I've used optifine it still crashes

I’m not talking about crash log, I’m talking about latestlog.txt.

> Imagine someone reports a crash in your app like this, without a log file or a stack trace, what will you do?

**Comment by 1493028** [comment]
> > > The log file is missing.
> > 
> > 
> > No log bro It crashes as soon as I play for 2 to 5 minutes I've used optifine it still crashes
> 
> I’m not talking about crash log, I’m talking about latestlog.txt.
> 
> > Imagine someone reports a crash in your app like this, without a log file or a stack trace, what will you do?

I know that

**Comment by khanhduytran0** [comment]
> I know that

Then could you send it, or keep being silent?

**Comment by khanhduytran0** [comment]
Still no log being received. Closing until further response.
