### ISSUE TITLE
[BUG] <can't run farbic>

### ISSUE THREAD

**Issue by BlueParrot789** [PojavLauncherTeam/PojavLauncher#2491]
### Describe the bug

I use farbic and farbic sodium but i stuck on black screen

### The log file and images/videos

games/PojavLauncher/.minecraft

### Steps To Reproduce

```markdown
Start pojav launcher and play fabric-installer-0.10.2
```

### Expected Behavior

I wating to open farbic and run immersive portal mod

### Platform

```markdown
- Device model: Lenovo Tab 3 a 8/ 2gb ram , 16gb rom
- CPU architecture: aarch64
- Android version: 6.0
- PojavLauncher version: crocus-v3_openjdk (play store)
```

### Anything else?

When i run oceano 2.0 shader is kick me out

**Comment by GoneSubject** [comment]
we don't need this we need you to send the latestlog.txt
> games/PojavLauncher/.minecraft

**Comment by BlueParrot789** [comment]
java.lang.RuntimeException: Unable to instantiate activity
ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.MainActivity}:
java.lang.NullPointerException: Attempt to read from field 'float
android.util.DisplayMetrics.density' on a null object reference
 at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2488)
 at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
 at android.app.ActivityThread.-wrap11(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
 at android.os.Handler.dispatchMessage(Handler.java:111)
 at android.os.Looper.loop(Looper.java:207)
 at android.app.ActivityThread.main(ActivityThread.java:5765)
 at java.lang.reflect.Method.invoke(Native Method)
 at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: java.lang.NullPointerException: Attempt to read from field
'float android.util.DisplayMetrics.density' on a null object reference
 at net.kdt.pojavlaunch.Tools.dpToPx(Tools.java:386)
 at net.kdt.pojavlaunch.BaseMainActivity.<init>(BaseMainActivity.java:53)
 at net.kdt.pojavlaunch.MainActivity.<init>(MainActivity.java:18)
 at java.lang.Class.newInstance(Native Method)
 at android.app.Instrumentation.newActivity(Instrumentation.java:1072)
 at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2478)
 ... 9 more

**Comment by BlueParrot789** [comment]
--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar,
lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar,
lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: fabric-loader-0.12.12-1.14.4 (1.14.4)
--------- beginning of main
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1280
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env:
PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env:
LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-1/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_vgpu
Added custom env: LIBGL_ES=3_vgpu
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env:
JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=800
I/LIBGL   (21640): Initialising vgpu gl4es
I/LIBGL   (21640): vgpu 1.3.6 gl4es 1.1.4 built on Aug 25 2021 09:26:59
I/LIBGL   (21640): Using GLES 3.0 backend
I/LIBGL   (21640): LIBGL:loaded: libGLESv3.so
I/LIBGL   (21640): loaded: libEGL.so
I/LIBGL   (21640): Using GLES 3.0 backend
I/LIBGL   (21640):
I/LIBGL   (21640): ========
I/LIBGL   (21640): GL_EXTENSIONS is :
I/LIBGL   (21640): GL_EXT_debug_marker GL_ARM_rgba8
GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture
GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8
GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture
GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives
GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync
GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat
GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888
GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV
GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers
GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr
GL_KHR_texture_compression_astc_hdr GL_KHR_debug
GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query
GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary
GL_OES_texture_3D GL_EXT_texture_storage
GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_t
I/LIBGL   (21640): Hardware Full NPOT detected and used
I/LIBGL   (21640): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (21640): FBO are in core, and so used
I/LIBGL   (21640): PointSprite are in core, and so used
I/LIBGL   (21640): CubeMap are in core, and so used
I/LIBGL   (21640): BlendColor is in core, and so used
I/LIBGL   (21640): Blend Substract is in core, and so used
I/LIBGL   (21640): Blend Function and Equation Separation is in core, and
so used
I/LIBGL   (21640): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (21640): Extension GL_OES_mapbuffer  detected
I/LIBGL   (21640): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (21640): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (21640): Extension GL_OES_depth24  detected and used
I/LIBGL   (21640): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (21640): Extension GL_EXT_texture_format_BGRA8888  detected and
used
I/LIBGL   (21640): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (21640): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (21640): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (21640): high precision float in fragment shader available and
used
I/LIBGL   (21640): Max vertex attrib: 16
I/LIBGL   (21640): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (21640): Max texture size: 8192
I/LIBGL   (21640): Max Varying Vector: 15
I/LIBGL   (21640): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max
planes: 6
I/LIBGL   (21640): Max Color Attachments: 4 / Draw buffers: 4
I/LIBGL   (21640): Hardware vendor is ARM
I/LIBGL   (21640): Hardware renderer is Mali-T720
I/LIBGL   (21640): GLSL 300 es supported
I/LIBGL   (21640): GLSL 310 es supported and used
I/LIBGL   (21640): EGLImage to Texture2D supported
I/LIBGL   (21640): EGLImage to RenderBuffer supported
I/LIBGL   (21640): ignore MipMap
I/LIBGL   (21640): Targeting OpenGL 3.0
I/LIBGL   (21640): NPOT texture handled in hardware
I/LIBGL   (21640): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (21640): try to use VBO
I/LIBGL   (21640): glXMakeCurrent FBO workaround enabled
I/LIBGL   (21640): FBO workaround for using binded texture enabled
I/LIBGL   (21640): glX Will try to recycle EGL Surface
I/LIBGL   (21640): Current folder is:/
I/jrelog  (21640): dlopen libvgpu.so success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so
success
I/jrelog  (21640): dlopen libjvm.so success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so
success
referenceTable GDEF length=808 1
referenceTable GSUB length=11364 1
referenceTable GPOS length=47320 1
referenceTable head length=54 1
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so
success
I/jrelog  (21640): dlopen
/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so
success
I/jrelog  (21640): dlopen
/data/app/net.kdt.pojavlaunch-1/lib/arm64/libopenal.so success
I/jrelog  (21640): Done processing args
I/jrelog  (21640): Found JLI lib
I/jrelog  (21640): Calling JLI_Launch
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed
services may be adversely affected if the time-of-day clock changes
[05:26:12] [main/INFO]: Loading Minecraft 1.14.4 with Fabric Loader 0.12.12
[05:26:14] [main/INFO]: Fabric is preparing JARs on first launch, this may
take a few seconds...￼

**Comment by NotAHero04** [comment]
You need to have more patience, the game is still preparing stuffs...

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build
