### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Akashkakak** [PojavLauncherTeam/PojavLauncher#2492]
### Describe the bug

1.8 not working any servers fix that fast some times I start the game in 1.8 and automatically code one comes and back going fix that fast #2491 

### The log file and images/videos

1.8 not working any servers fix that fast some times I start the game in 1.8 and automatically code one comes and back going fix that fast #2491 

### Steps To Reproduce

```markdown
1.8 not working any servers fix that fast some times I start the game in 1.8 and automatically code one comes and back going fix that fast #2491
```

### Expected Behavior

1.8 not working any servers fix that fast some times I start the game in 1.8 and automatically code one comes and back going fix that fast #2491 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

1.8 not working any servers fix that fast some times I start the game in 1.8 and automatically code one comes and back going fix that fast #2491

**Comment by GoneSubject** [comment]
fill the platform info

**Comment by GoneSubject** [comment]
and send the latestlog.txt

**Comment by khanhduytran0** [comment]
VBO needs to be enabled.
