### ISSUE TITLE
[BUG] 1.18.1 could not preload shader position

### ISSUE THREAD

**Issue by IndefiniteCalculus** [PojavLauncherTeam/PojavLauncher#2493]
### Describe the bug

I don't know what happend when I launch 1.18.1, I had VM installed java17VM

### The log file and images/videos

---- Minecraft Crash Report ----
// Oops.

Time: 2022/1/1 上午4:42
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at epe.a(SourceFile:423)
	at epe.a(SourceFile:407)
	at dxo.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:199)
Caused by: yk: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7: S0054: Overloading built-in function 'max' not allowed
	at yk.a(SourceFile:48)
	at epw.<init>(SourceFile:200)
	at epe.a(SourceFile:419)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7: S0054: Overloading built-in function 'max' not allowed
	at dry.b(SourceFile:72)
	at dry.a(SourceFile:54)
	at epw.a(SourceFile:241)
	at epw.<init>(SourceFile:182)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at epe.a(SourceFile:423)
	at epe.a(SourceFile:407)
	at dxo.<init>(SourceFile:617)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:199)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 665258304 bytes (634 MiB) / 1203765248 bytes (1148 MiB) up to 1203765248 bytes (1148 MiB)
	CPUs: 8
	Processor Vendor: 0x48
	Processor Name: AArch64 Processor rev 0 (aarch64)
	Identifier: 0x48 Family 8 Model 0xd40 Stepping r0x1p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4140.84
	Virtual memory used (MB): 5332.52
	Swap memory total (MB): 2240.00
	Swap memory used (MB): 1914.96
	JVM Flags: 2 total; -Xms1148M -Xmx1148M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 0 (aarch64)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. install java17 vm
3. download 1.18.1
4. launch 1.18.1 and crash
```

### Expected Behavior

launch 1.18.1 on my device

### Platform

```markdown
- Device model: HUAWEI M6
- CPU architecture: 8x AArch64 Processor rev 0 (aarch64)
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk(9938053)
```

**Comment by GoneSubject** [comment]
can you send the latestlog.txt?

**Comment by IndefiniteCalculus** [comment]
> can you send the latestlog.txt?

Sorry, I just realized  I missed your reply.
Here is my latestlog
[latestlog(1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7798522/latestlog.1.txt)

**Comment by GoneSubject** [comment]
> > can you send the latestlog.txt?
> 
> Sorry, I just realized I missed your reply. Here is my latestlog [latestlog(1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7798522/latestlog.1.txt)

can you reproduce and send the log again?

**Comment by IndefiniteCalculus** [comment]
> > > can you send the latestlog.txt?
> > 
> > 
> > Sorry, I just realized I missed your reply. Here is my latestlog [latestlog(1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7798522/latestlog.1.txt)
> 
> can you reproduce and send the log again?

sure
[latestlog(1)(1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7798687/latestlog.1.1.txt)

**Comment by GoneSubject** [comment]
> > > > can you send the latestlog.txt?
> > > 
> > > 
> > > Sorry, I just realized I missed your reply. Here is my latestlog [latestlog(1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7798522/latestlog.1.txt)
> > 
> > 
> > can you reproduce and send the log again?
> 
> sure [latestlog(1)(1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7798687/latestlog.1.1.txt)

you may need to follow [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)

**Comment by IndefiniteCalculus** [comment]
Well, I usually search for the most recent latestlog.txt in my file system, to identify where my latestlog is.

I can't navigate to /sdcard/Android/data/net.kdt.pojavlaunch[.debug]/files, there is no such file on my device.  

But found this logfile in /Android/data/net.kdt.pojavlaunch/files, and it has been modified 45min ago. So I think this log was produced by the crushed game.
[latestlog(2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7798710/latestlog.2.txt)
![Screenshot_20220102_153522_com huawei filemanager](https://user-images.githubusercontent.com/55014395/147869250-5e2ecff3-1422-4a78-8fd1-623421e1a3cb.jpg)

**Comment by GoneSubject** [comment]
> Well, I usually search for the most recent latestlog.txt in my file system, to identify where my latestlog is.
> 
> I can't navigate to /sdcard/Android/data/net.kdt.pojavlaunch[.debug]/files, there is no such file on my device.
> 
> But found this logfile in /Android/data/net.kdt.pojavlaunch/files, and it has been modified 45min ago. So I think this log was produced by the crushed game. [latestlog(2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7798710/latestlog.2.txt) ![Screenshot_20220102_153522_com huawei filemanager](https://user-images.githubusercontent.com/55014395/147869250-5e2ecff3-1422-4a78-8fd1-623421e1a3cb.jpg)

to know the file net.ndt.pojavlaunch or net.ndt.pojavlaunch.debug is depends on what debug of pojavlauncher if you choose debug-runtime it will show net.ndt.pojavlaunch.debug if you use playstore or debug-noruntime it will show net.ndt.pojavlaunch

**Comment by GoneSubject** [comment]
and the problem i see in the log is this so i think you should follow the instuctions in [here](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)
> [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible

**Comment by IndefiniteCalculus** [comment]
> and the problem i see in the log is this so i think you should follow the instuctions in [here](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)
> 
> > [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible

oh, I see. I'll try it.

**Comment by IndefiniteCalculus** [comment]
> and the problem i see in the log is this so i think you should follow the instuctions in [here](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)
> 
> > [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible

But there is no /.minecraft/resourcepacks inside of /Android/data/net.kdt.pojavlaunch/files. Do I need to create this path?

**Comment by GoneSubject** [comment]
> > and the problem i see in the log is this so i think you should follow the instuctions in [here](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)
> > > [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible
> 
> But there is no /.minecraft/resourcepacks inside of /Android/data/net.kdt.pojavlaunch/files. Do I need to create this path?

welp you will need to turn on "show hidden file"

**Comment by IndefiniteCalculus** [comment]
> 

I'll try this instruction again later. Thanks for your help.
