### ISSUE TITLE
[BUG] sodium 0.1.0 crashed randomly or idk

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2494]
### Describe the bug

My sodium crashing randomly when changing render distance or idk

~~prolly bcz I watched Hindi tutorial for the sodium~~

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7797394/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher blablabla
```

### Expected Behavior

I want to play sodium without crash

### Platform

```markdown
- Device model: Redmi note 4x
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: on the log
```

**Comment by NotAHero04** [comment]
Make sure you have these options **disabled**:
- Compact Vertex Format
- Fog Occlusion

**Comment by ghost** [comment]
Forgor💀

**Comment by iamSlightlyWind** [comment]
@NotAHero04 Sorry, but do you happen to know a workaround for crashes upon running ~~sodium on 1.17.1 or 1.16.5~~ 0.2.0+ sodium?
