### ISSUE TITLE
Blackscreen when using kuda shaders & water not reflection in bsl shaders (Virgl)

### ISSUE THREAD

**Issue by PutuDesca** [PojavLauncherTeam/PojavLauncher#2495]
When I use kuda shader my world goes black and when I use bsl shaders it works fine but no reflection in water (virglrenderer)

![IMG_20220101_141344.JPG](https://user-images.githubusercontent.com/93461649/147845074-b82cb5ed-5587-461b-a837-6c9eeb511dc3.JPG)

![IMG_20220101_141325.JPG](https://user-images.githubusercontent.com/93461649/147845077-b06b5079-83fd-4a83-a0ab-6bb80fb547bd.JPG)

But the makeup ultrafast shader and chocapic shader went well and smoothly

![IMG_20220101_141405.JPG](https://user-images.githubusercontent.com/93461649/147845090-a58faca9-628c-4aea-a106-39f977c385ec.JPG)

![IMG_20220101_141358.JPG](https://user-images.githubusercontent.com/93461649/147845092-2528dcbf-8b2b-4296-b94a-fcbc56ae5e3d.JPG)

Thank you for making this cool application, I'm still waiting for virglrenderer opengl 4.6

**Comment by NotAHero04** [comment]
Could you provide us a log for each problematic shader?

**Comment by PutuDesca** [comment]
Yep, maybe because virglrenderer is still using opengl 4.3 but after I tried the shaders in zink (vulkan) opengl 4.6 there is no problem whatsoever, because most java shaders require opengl 4.6,
There are only a few java shaders that support opengl 4.3 most require opengl 4.6

**Comment by NotAHero04** [comment]
About KUDA: I looked at the log (well, I tried it myself), there are 3 shader programs that failed to compile. Did you see
> [Shaders] Invalid program: ...
>
in the chat history when you join the game?

**Comment by NotAHero04** [comment]
Or better, you could just send the launcher log.

**Comment by PutuDesca** [comment]
![IMG_20220101_163237.JPG](https://user-images.githubusercontent.com/93461649/147847017-a1547962-12c2-4f30-87f9-f6637255f991.JPG)

**Comment by PutuDesca** [comment]
![IMG_20220101_163357.JPG](https://user-images.githubusercontent.com/93461649/147847032-4feb7706-b7ef-424e-865d-2ab36b2b24b0.JPG)

**Comment by NotAHero04** [comment]
Just send the log, bruh

**Comment by irice7** [comment]
Zamn.
VirGL renderer doesn't work with BSL.
Just accept that, or try older versions.
EDIT: Kuda too.

**Comment by khanhduytran0** [comment]
Since VirGL doesn’t emulate RTX 3090, you couldn’t expect SEUS PTGI E12 (or any other shaders) to work on it without issues. VirGL is experimental after all.

Please consider reporting to #2322 (no help in that issue btw).
