### ISSUE TITLE
[BUG] <Disable gestures hold to drop item>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2496]
### Describe the bug

I turn on disable gestures but I can still drop item (same when it's off) pls fix it

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Login
3. Turns on disable gestures
4. Plays 1.18
```

### Expected Behavior

Hold to drop item  should be disabled

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GoneSubject** [comment]
welp you see here it didn't said that it will turn off hold to drop ![Screenshot_2022-01-01-18-04-51-368_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/95298052/147849179-df287a6e-53fa-443f-814b-6e22ad23dd07.jpg)

**Comment by GoneSubject** [comment]
maybe the default control doesn't have the drop button so devs don't disable it

**Comment by Shromeyy** [comment]
I'm annoyed that they didn't add it cause I customize the controls and added drop button and sometime hold to drop item bugs and keeps dropping the item if I tap on the inventory slot a little long then it will think that it's a hold to drop

**Comment by GoneSubject** [comment]
> I'm annoyed that they didn't add it cause I customize the controls and added drop button and sometime hold to drop item bugs and keeps dropping the item if I tap on the inventory slot a little long then it will recognize it as a hold to drop

this should be an enhancement request to set more time for the hold to drop

**Comment by khanhduytran0** [comment]
> this should be an enhancement request to set more time for the hold to drop

This option exists for a reason. 1 second is already long.
![_20220101_195441](https://user-images.githubusercontent.com/40482367/147851000-3a62752b-cf8b-4d37-b2c6-b425b39d5573.jpg)

**Comment by GoneSubject** [comment]
> > this should be an enhancement request to set more time for the hold to drop
> 
> This option exists for a reason. 1 second is already long.
> ![_20220101_195441](https://user-images.githubusercontent.com/40482367/147851000-3a62752b-cf8b-4d37-b2c6-b425b39d5573.jpg)
> 

yea ik but this guy hold like for 5 seconds

**Comment by Shromeyy** [comment]
Just add disable hold to drop item 😭

**Comment by GoneSubject** [comment]
> Just add disable hold to drop item 😭

the devs maybe will but you must wait
