### ISSUE TITLE
[F-Req] <hold to drop option>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2497]
### Is this request related to a bug?

Sometimes tapping your inventory slot a little long you'll drop the item

### Describe the request.

Disable hold to drop item option

### Anything else?

 you accidentally tap your diamond pickaxe a little long that has efficiency 5, fortune 3, unbreaking 3, and mending near lava

**Comment by Mathias-Boulay** [comment]
that's a feature already 😂

**Comment by Shromeyy** [comment]
No I wanted to turn it off not trigger press duration

**Comment by LightestMC** [comment]
pretty sure turning on "Disable Gestures" will do the job

**Comment by GoneSubject** [comment]
> pretty sure turning on "Disable Gestures" will do the job

it's not it just disable hold to break and tap to place

**Comment by Shromeyy** [comment]
It didn't work I can still hold to drop

**Comment by Mathias-Boulay** [comment]
Values adjusted
