### ISSUE TITLE
Error 403 when logging into mc account

### ISSUE THREAD

**Issue by Fance1** [PojavLauncherTeam/PojavLauncher#2498]
### Describe the bug

So, i have a chromebook and decided to use pojavlauncher on there. I downloaded it. Microsoft loging doesn't work. I did manual login and it  gave me error 403.

### Steps To Reproduce

```markdown
Logged in manually because Microsoft login didnt work.
```

### Expected Behavior

I expected the game to log me in.

### Platform

```markdown
- Device model: 11a-Nb chromebook
- CPU architecture: 
- Android version: (CHROME OS)
- PojavLauncher version: Playstore newest version
```

**Comment by Fance1** [comment]
Note, I DO have a minecraft account

**Comment by khanhduytran0** [comment]
Just the error code tells us almost nothing. We don’t have access to Mojang server, you know. So please at least copy the error message there. To confirm that you own the game, screenshot the profile page.

**Comment by Fance1** [comment]
> Just the error code tells us almost nothing. We don’t have access to Mojang server, you know. So please at least copy the error message there. To confirm that you own the game, screenshot the profile page.

"Respone error
code: 403 
message: {"error":"ForbiddenOperationException"
"errorMessage":"Invalid credentials. Invalid username or password."}

**Comment by Fance1** [comment]
![Screenshot_20220101-222919_Chrome](https://user-images.githubusercontent.com/96968178/147867145-41997e1d-3f4b-4166-a695-178db2a654c6.jpg)

**Comment by khanhduytran0** [comment]
> Invalid credentials. Invalid username or password.

It’s invalid since you’re trying to login a Microsoft account to Mojang.
**Are you under 18?** If so, link it to your parent account first.

**Comment by Fance1** [comment]
> > Invalid credentials. Invalid username or password.
> 
> It’s invalid since you’re trying to login a Microsoft account to Mojang. **Are you under 18?** If so, link it to your parent account first.

I can do that, but how do i log in if i can't use the Microsoft login?

**Comment by khanhduytran0** [comment]
> but how do i log in if i can't use the Microsoft login?

> **Are you under 18?** If so, link it to your parent account first.

https://support.microsoft.com/en-us/account-billing/add-people-to-your-family-group-4a07b974-8103-16ad-6ea2-46549ca19e03

**Comment by Fance1** [comment]
> > but how do i log in if i can't use the Microsoft login?
> 
> > **Are you under 18?** If so, link it to your parent account first.
> 
> https://support.microsoft.com/en-us/account-billing/add-people-to-your-family-group-4a07b974-8103-16ad-6ea2-46549ca19e03

It says my email is invalid. (I'm on an alt  trying to add my main to the family).

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
