### ISSUE TITLE
[BUG] Camera bug on pre-1.13

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher#2500]
### Describe the bug

The in-game camera will jump if you use the virtual mouse. I can only observe this behavior on 1.12.2 or older.

### The log file and images/videos

Demonstration of the bug in 1.12.2: [here](https://streamable.com/mmcux1)

### Steps To Reproduce

```markdown
1. Start Minecraft 1.12.2 and join a world
2. Do anything that can make the virtual mouse appear, such as open the inventory.
3. Move the mouse a bit and then hide it (by closing the inventory)
4. Move the camera.
```

### Expected Behavior

The camera should move normally

### Platform

```markdown
- Device model: Vsmart Star 5
- CPU architecture: aarch64 
- Android version: 11
- PojavLauncher version: crocus-301-7df8559ad-v3_openjdk
```

**Comment by Shromeyy** [comment]
This why I stop playing 1.13 or below

**Comment by Mathias-Boulay** [comment]
Reproducible, I'll fix this NOW.
_Although I judge everyone for making the bad decision of using the virtual mouse_

**Comment by Mathias-Boulay** [comment]
Done, tested on 1.7.10
