### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by gustavogba859** [PojavLauncherTeam/PojavLauncher#2501]
### Describe the bug

Aplicativo/ jogo fechou com código 1

### The log file and images/videos

![Screenshot_20220103-000618_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/97007912/147897484-2f58249a-ae29-4889-a463-3845a84e807a.jpg)

### Steps To Reproduce

```markdown
Bugs
```

### Expected Behavior

Espero que o jogo seja iniciado 

### Platform

```markdown
- Device model: J4 Samsung 
- CPU architecture: não sei 
- Android version: não  sei 
- PojavLauncher?
```

**Comment by khanhduytran0** [comment]
Incomplete information.

**Comment by gustavogba859** [comment]
Ajeitem  isso tá dando toda hora Aplicativo/jogo fechou com código 1eu já desinstalei mais tá a mesma coisa

**Comment by gustavogba859** [comment]
Modelo do celular J4 Samsung
