### ISSUE TITLE
[BUG] <Can't install assets-v0>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2502]
### Describe the bug

Can't install assets-v0 for 1.18 it shows an error message saying This XML file does not appear to have any style information associated with it. The document tree is shown below.

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Login
3. Download resource pack
4. Error message
```

### Expected Behavior

The Download link

### Platform

```markdown
- Device model: Galaxy a31
- CPU architecture: aarch64
- Android version: Android 11
- PojavLauncher version: croucus-305-d54bfa656-v3_openjdk
```

### Anything else?

**Comment by NotAHero04** [comment]
This has nothing to do with PojavLauncher, it's just a broken link.

**Comment by khanhduytran0** [comment]
The assets-v0 you found in the launcher news is for 1.17.x, not 1.18.x.
Follow [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04) for 1.18.x.

**Comment by Shromeyy** [comment]
Guess I'm dumb
