### ISSUE TITLE
Pojav launcher vgpu white screen [BUG] 

### ISSUE THREAD

**Issue by vasu123432141** [PojavLauncherTeam/PojavLauncher#2503]
### Describe the bug

Vgpu white screen 

### The log file and images/videos

[Uploading latestlog.txt…]()

### Steps To Reproduce

```markdown
Start pojav launcher 
Select vgpu renderer 
Launch the game white screen appears
```

### Expected Behavior

I think game will launch 

### Platform

```markdown
- Device model: Vivo1820 
- CPU architecture: arm 64
- Android version: 8
- PojavLauncher version: app debug
```

### Anything else?

No

**Comment by andr0d1v** [comment]
Version 1.16.5?

**Comment by NotAHero04** [comment]
When you didn't wait for your internet...
Send the log again.

**Comment by vasu123432141** [comment]
[Uploading latestlog.txt…]()

**Comment by vasu123432141** [comment]
Yes 1.16.5

**Comment by andr0d1v** [comment]
Instead vgpu use gl4es 1.1.5

**Comment by vasu123432141** [comment]
Wut are u saying why I opened this bug report

**Comment by khanhduytran0** [comment]
> Uploading latestlog.txt…

*When you have no patience to wait for this to be uploaded.*

**Comment by vasu123432141** [comment]
I waited it is not uploading

**Comment by vasu123432141** [comment]
[Uploading latestlog.txt…]()

**Comment by vasu123432141** [comment]
[Uploading latestlog.txt…]()

**Comment by vasu123432141** [comment]
latestlog.txt

**Comment by GoneSubject** [comment]
wow this guy have no patience

**Comment by vasu123432141** [comment]
I'm waiting

**Comment by vasu123432141** [comment]
It's still uploading

**Comment by vasu123432141** [comment]
5 min done

**Comment by vasu123432141** [comment]
10 min x
Done xd

**Comment by NotAHero04** [comment]
It literally says [Uploading latestlog.txt...]()
Could you just wait while it is **being uploaded**?

**Comment by vasu123432141** [comment]
Already waited 10 mins

**Comment by NotAHero04** [comment]
I mean, when you see [Uploading something...], **don't tap "Comment" immediately.**

**Comment by vasu123432141** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7812258/latestlog.txt)

**Comment by vasu123432141** [comment]
Finally

**Comment by vasu123432141** [comment]
![Screenshot_20220105_111602](https://user-images.githubusercontent.com/96738174/148166885-d0a9d8fb-bb98-44f2-be6d-a000ba1327ea.jpg)

**Comment by NotAHero04** [comment]
Looks like the shader conversion of VGPU is being dumb. You can't do anything to fix it, so use gl4es 1.1.5.

**Comment by vasu123432141** [comment]
Wt

**Comment by vasu123432141** [comment]
Wait the developer to reply

**Comment by NotAHero04** [comment]
They are not developers of VGPU, bruh

**Comment by vasu123432141** [comment]
Duy Tran he's a developer

**Comment by GoneSubject** [comment]
> Duy Tran he's a developer

but not a VGPU developer

**Comment by vasu123432141** [comment]
So what I can do

**Comment by GoneSubject** [comment]
> So what I can do

use gl4es 1.1.5

**Comment by vasu123432141** [comment]
What's the solution

**Comment by GoneSubject** [comment]
> What's the solution

just use gl4es 1.1.5 stop asking the same question

**Comment by vasu123432141** [comment]
F u

**Comment by GoneSubject** [comment]
> F u

hm?

**Comment by NotAHero04** [comment]
> F u
> 
If you really want it to be fixed, ask the creator of VGPU.

**Comment by vasu123432141** [comment]
How to tell to him

**Comment by NotAHero04** [comment]
[here](https://github.com/luo9674/VGPU)

**Comment by irice7** [comment]
omg moment oh well ye mine doesnt work too

**Comment by Mathias-Boulay** [comment]
vgpu is no more
