### ISSUE TITLE
[BUG] Salwyrr closing

### ISSUE THREAD

**Issue by JalajTNT** [PojavLauncherTeam/PojavLauncher#2506]
### Describe the bug

Whenever i use salwyrr it closes automatically. I tried updating java but didnt work. pls tell me what to do :(

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

I expect it to not close

### Platform

```markdown
- Device model: Lenovo ideapad 330s
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GoneSubject** [comment]
you can't use a launcher in a launcher

**Comment by NotAHero04** [comment]
Given that you did have a fully working copy of it, send log moment.

**Comment by Mathias-Boulay** [comment]
We won't bother to support such bullshit clients tbh
