### ISSUE TITLE
[BUG] <1.15 virglrenderer lag>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2507]
### Describe the bug

I change virglrenderer to vgpu because it was lagging and the game is now looks broken

### The log file and images/videos

https://drive.google.com/file/d/1HuvrnfJlSogVQBMoAzaW-T5KsNsDnG4i/view?usp=drivesdk

### Steps To Reproduce

```markdown
No
```

### Expected Behavior

Joe

### Platform

```markdown
- Device model: Galaxy a31
- CPU architecture: aarch64
- Android version: Android 11
- PojavLauncher version: croucus-305-d54bfa656-v3_openjdk
```

### Anything else?

Nope

**Comment by GoneSubject** [comment]
i can't access that can you send it here?
> The log file and images/videos
https://drive.google.com/file/d/1HuvrnfJlSogVQBMoAzaW-T5KsNsDnG4i/view?usp=drivesdk

**Comment by Shromeyy** [comment]
> i can't access that can you send it here?
> > The log file and images/videos
> https://drive.google.com/file/d/1HuvrnfJlSogVQBMoAzaW-T5KsNsDnG4i/view?usp=drivesdk

![Screenshot_20220105-101026_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/94804069/148180301-79c51479-e213-4935-8147-fea67406a4b7.jpg)

**Comment by GoneSubject** [comment]
can you use gl4es?

**Comment by Shromeyy** [comment]
It's fixed thanks :D
