### ISSUE TITLE
[BUG] Aiming when i dont swipe the screen but just touch it

### ISSUE THREAD

**Issue by AveragePojavEnjoyer** [PojavLauncherTeam/PojavLauncher#2508]
### Describe the bug

When i go to Inventory, Crafting table, Furnace and etc. and i touch the screen, it aims at places

### The log file and images/videos

https://user-images.githubusercontent.com/96653294/148184016-21eb8fc5-3ea5-41a3-bd1c-ab2b2b927854.mp4

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Realme
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Action on github
```

### Anything else?

.

**Comment by GoneSubject** [comment]
you are opening and closing too fast

**Comment by AveragePojavEnjoyer** [comment]
It's the same even if i open and close longer, happens on bw item shop too

**Comment by khanhduytran0** [comment]
Duplicate of #2500
