### ISSUE TITLE
Forge Install Unsuccessful 

### ISSUE THREAD

**Issue by Meadows0524** [PojavLauncherTeam/PojavLauncher#2509]
### Describe the bug

I've watched countless tutorials on how to install forge into minecraft pojavlauncher version 1.16.5 on chromebook, and all were unsuccessful, ending up with a screen pop up either saying "Game has exited" or the app crashing. I've tried typing in the file name as an option as well, and it's been the same. This also happens when I try to install Optifi on 1.16.5, I'm not sure what i'm doing wrong. 

### Steps To Reproduce

```markdown
1. start pojavlauncher 
2. sign in using microsoft account 
3. click on the minecraft update type
4. choose 1.16.5 
5. click "options" 
6. scroll through files and click on downloaded forge file being: "forge-1.16.5-36.2.22-installer.jar" 
7. click next

personally for me: 
8. watch as the installation fails.
```

### Expected Behavior

After clicking on the forge file, I expected the application to run and pop up a new update option, being "1.16.5 forge" or something similar. However, the application ended up crashing, and after trying over and over, it keeps doing so. 

### Platform

```markdown
- Device model: Version 96.0.4664.111
- CPU architecture: 
- Android version: 
- PojavLauncher version: java 8
```

**Comment by khanhduytran0** [comment]
Lacks of latestlog.txt.

**Comment by SprainedSpark89** [comment]
do you not know the way to get to pojavlauncher folder

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
