### ISSUE TITLE
[BUG] Game crashes on 1.17-1.18.1 when trying to move.

### ISSUE THREAD

**Issue by simonjonnemeth** [PojavLauncherTeam/PojavLauncher#2510]
### Describe the bug

I've met the requirements for 1.17 and up to run and the game starts but as soon as I'm in the game and the FPS has settled I try to move and the game always crashes pretty much immediately. This is not an issue prior to 1.17 and the game is relatively stable. I am advised on the Discord to lower my graphics settings despite getting decent FPS in all versions of the game with my current settings although I don't think I should have to if it worked correctly. This happens with or without mods such as Optifine or Sodium, Lithium, Phosphor etc.

### The log file and images/videos

For reference using Optifine although it happens without: [https://youtu.be/bm_9g9hwe6A](url)
![Screenshot_20220105-215747_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/1496797/148296101-33a7f73d-fe4d-4dd9-a14c-3b290f4eefc9.jpg)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/7818055/latest.log)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7822389/latestlog.txt)

### Steps To Reproduce

```markdown
There a no steps to reproduce other than running the game.
```

### Expected Behavior

```markdown
Working fine.
```

### Platform

```markdown
- Device model: Samsung Galaxy Tab S7+
- CPU architecture: Qualcomm Snapdragon 865 Plus
- Android version: Android 11 (stock)
- PojavLauncher version: Latest GPlay version and up.
```

**Comment by khanhduytran0** [comment]
Please send the correct file. latest.log is not latestlog.txt, which was explicitly stated in the issue form.

**Comment by simonjonnemeth** [comment]
> Please send the correct file. latest.log is not latestlog.txt, which was explicitly stated in the issue form.

I have.

**Comment by khanhduytran0** [comment]
Known issue on Adreno GPU. Try lowering render distance.

**Comment by simonjonnemeth** [comment]
> Known issue on Adreno GPU. Try lowering render distance.

No, I shouldn't have to compromise my graphics settings if this is a problem elsewhere. This should be fixed by who ever is responsible for what is causing it.

**Comment by khanhduytran0** [comment]
> No, I shouldn't have to compromise my graphics settings if this is a problem elsewhere.

Hey, you should know the fact that it is a PC game. **Mobile has its limit.**

> This should be fixed by who ever is responsible for what is causing it.

This makes sense, but we aren’t developers of these parts (game, renderer, GPU), so I guess you reported in a wrong place. We could redirect to one of these, but we haven’t gotten a backtrace of the GL driver crash anywhere, which only advanced users know how to get it.

**Comment by simonjonnemeth** [comment]
> > No, I shouldn't have to compromise my graphics settings if this is a problem elsewhere.
> 
> Hey, you should know the fact that it is a PC game. **Mobile has its limit.**
> 
> > This should be fixed by who ever is responsible for what is causing it.
> 
> This makes sense, but we aren’t developers of these parts (game, renderer, GPU), so I guess you reported in a wrong place. We could redirect to one of these, but we haven’t gotten a backtrace of the GL driver crash anywhere, which only advanced users know how to get it.

Why is this not an issue with all versions of Minecraft? Why is this exclusive to Pojavlauncher?

**Comment by khanhduytran0** [comment]
> Why is this not an issue with all versions of Minecraft?

Simple answer: 1.17+ use OpenGL 3.2.

> Why is this exclusive to Pojavlauncher?

Could you find any more launchers that can run 1.17+ on **mobile**? You may find Boat, but they have never made 1.17+ support release to public, only the source code is public. Also, if you’re talking about why it works on PC, simple answer: if it doesn’t work on PC, Mojang would already fixed it, as PC is their primary supported platform. Mobile has never been a supported platform for the Java Edition.

Additionally, virglrenderer could get 1.17+ to run with any graphical settings, but there’s transparency bug.

**Comment by simonjonnemeth** [comment]
I'm using virglrenderer and it crashes just the same. Have you even explored this issue?

**Comment by simonjonnemeth** [comment]
I don't get nearly as good FPS with virglrenderer either.

**Comment by simonjonnemeth** [comment]
Could this be down to the excessive ram usage of 1.17-1.18.1 compared to 1.16.4 and prior? Why doesn't this affect everybody? https://www.minecraftforum.net/forums/support/java-edition-support/2477759-minecraft-crashes-when-i-start-moving-in-game-help

**Comment by simonjonnemeth** [comment]
> > Why is this not an issue with all versions of Minecraft?
> 
> Simple answer: 1.17+ use OpenGL 3.2.
> 
> > Why is this exclusive to Pojavlauncher?
> 
> Could you find any more launchers that can run 1.17+ on **mobile**? You may find Boat, but they have never made 1.17+ support release to public, only the source code is public. Also, if you’re talking about why it works on PC, simple answer: if it doesn’t work on PC, Mojang would already fixed it, as PC is their primary supported platform. Mobile has never been a supported platform for the Java Edition.
> 
> Additionally, virglrenderer could get 1.17+ to run with any graphical settings, but there’s transparency bug.

Could this be down to the excessive ram usage of 1.17-1.18.1 compared to 1.16.4 and prior? Why doesn't this affect everybody? https://www.minecraftforum.net/forums/support/java-edition-support/2477759-minecraft-crashes-when-i-start-moving-in-game-help

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
