### ISSUE TITLE
[F-Req] Pojav Team please don't Abandoned 32bit device I want to make more ram but 300mb only,  it will crach if you make to 310-1100mb ram, please make this like 64bit is freely use more ram please Pojavlauncher team Im always supporting 

### ISSUE THREAD

**Issue by jethro527** [PojavLauncherTeam/PojavLauncher#2515]

**Comment by ghost** [comment]
32bit have limited for allocated ram also check u free ram

**Comment by ghost** [comment]
Buy new device

**Comment by NotAHero04** [comment]
https://play.google.com/store/apps/details?id=me.empirical.android.application.fillmemory

**Comment by Mathias-Boulay** [comment]
Java has a low limit for 32 bits devices.
That's why the max 32 bits memory limit is 1100MB, can be tuned in the settings.
