### ISSUE TITLE
[BUG] Can't reach .minecraft (on samsung tab s7+) without root and add Asset-0 fix

### ISSUE THREAD

**Issue by lostallmymoney** [PojavLauncherTeam/PojavLauncher#2516]
### Describe the bug

There is no way I am able to reach the folder. Maybe add a way to move the install folder or edit files from pojav launcher because without root I cannot reach into the folder and copy anything.

### Steps To Reproduce

```markdown
Try launching 1.18.1,
Try applying patch Asset-0.zip
Fail
```

### Expected Behavior

Can reach into .minecraft folder to add mods and resourcepacks.

### Platform

```markdown
- Device model: Tab S7+
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: Aug 31, 2021
```

**Comment by GoneSubject** [comment]
you can find them in sdcard/Android/data/net.kdt.pojavlaunch(.debug)/files/.minecraft make sure you turned on "show hidden files"

**Comment by lostallmymoney** [comment]
No i cannot. In log file the .minecraft is at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft but even with different file managers the further I got was into user where i cannot go deeper. With termux I was able to move inside the folder but without any permission to read anything. The only net.kdt.pojavlaunch (s) I can find are either empty (on sd card) or contains only executables (internal storage). Inside .minecraft folder there is write protection.

________________________________

**Comment by GoneSubject** [comment]
i said that you must turn on "show hidden files" to see the .minecraft folder

**Comment by lostallmymoney** [comment]
First thing i did 
![Screenshot_20220106-025922_Termux](https://user-images.githubusercontent.com/6634309/148349211-c5fa8133-cdc3-4e52-92ce-81c942c26f4f.jpg)
![Screenshot_20220106-025822_Files by Google](https://user-images.githubusercontent.com/6634309/148349228-87884f6a-d589-4ca7-81a9-57a8e01c7f60.jpg)
![Screenshot_20220106-025811_Files by Google](https://user-images.githubusercontent.com/6634309/148349235-c84d9c71-0278-4f76-ac11-8a40387efc26.jpg)
![Screenshot_20220106-025757_Files by Google](https://user-images.githubusercontent.com/6634309/148349244-25f73fb2-31d8-4134-8fb7-40764d40449c.jpg)
But I can see this folder only from pc :
![20220106_025724~2](https://user-images.githubusercontent.com/6634309/148349424-67a359eb-ed13-46b8-a791-173973404b4c.jpg)

**Comment by lostallmymoney** [comment]
What's your file manager?On Jan. 6, 2022 2:51 a.m., NotGoneSubject ***@***.***> wrote:
i said that you must turn on "show hidden files" to see the .minecraft folder

**Comment by tigerbrocode** [comment]
My man how da f do you know that shit and don't know show hidden folders

**Comment by NotAHero04** [comment]
If you want to access it in Termux, you must execute `termux-setup-storage` first, but you will not be able to `ls` anyway, so...
Just use ZArchiver.

**Comment by lostallmymoney** [comment]
![Screenshot_20220106-032206_ZArchiver](https://user-images.githubusercontent.com/6634309/148352719-f7ce757f-6d74-459b-84b1-509fb58aa870.jpg)
![Screenshot_20220106-032009_ZArchiver](https://user-images.githubusercontent.com/6634309/148352726-39b6b62d-fa2d-4d13-b087-4ab83d8c4411.jpg)
Still nothing lol

**Comment by lostallmymoney** [comment]
Also cannot transfer app to sdcard

**Comment by GoneSubject** [comment]
> ![Screenshot_20220106-032206_ZArchiver](https://user-images.githubusercontent.com/6634309/148352719-f7ce757f-6d74-459b-84b1-509fb58aa870.jpg)
> ![Screenshot_20220106-032009_ZArchiver](https://user-images.githubusercontent.com/6634309/148352726-39b6b62d-fa2d-4d13-b087-4ab83d8c4411.jpg)
> Still nothing lol

you turned on "show hidden files"?

**Comment by lostallmymoney** [comment]
Thought it was by default on ZArchiver, it now works thanks ! My other file managers couldnt pull it off it seems..
