### ISSUE TITLE
Im not reporting a bug i just wanna show the 2 version of pojav launcher can multiplayer

### ISSUE THREAD

**Issue by imjustpenguin** [PojavLauncherTeam/PojavLauncher#2517]
### Describe the bug

![Screenshot_20220106_204058](https://user-images.githubusercontent.com/96688215/148384544-26486ea6-cdb2-4660-8858-1e378eebe842.jpg)

### The log file and images/videos

![Screenshot_20220106_204058](https://user-images.githubusercontent.com/96688215/148384670-734fa7e3-035b-494c-ad53-dacbdb95c683.jpg)

### Steps To Reproduce

```markdown
Play play store version of ojav launcher and create world open lan  then open the chrome version of pojav laun her find hes world and done but its little bit laggy when 2 pojav launcher running
```

### Expected Behavior

Its run good but lag in playstore version

### Platform

```markdown
- Device model: vivo y20
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: 
Chrome can cook
```

### Anything else?

Pls add new renderer
So i can use shader
And run smooth when i have 128 gb and 8gb ram
And the opengl 5.00
Fix the microsoft account bug
And @$@$@$@$@$@$@$@$
And tyyyyy6yyyyyyyyyyyyyyyyyyyyyy
Yyyyyyyyyyyyyyyyyyyy thank you.
:))

>

**Comment by imjustpenguin** [comment]
I dont report bug i just want to show that man calm down

**Comment by GoneSubject** [comment]
> Pls add new renderer
So i can use shader

you can use zink just to play the game with shader but you will get lag

**Comment by imjustpenguin** [comment]
Its not working for me in my old phone

**Comment by imjustpenguin** [comment]
But ty i use virgl

**Comment by khanhduytran0** [comment]
> Pls add new renderer
> So i can use shader

More like "Pls add RTX 3090 renderer"

> And the opengl 5.00

Oh so do you want this?
![image](https://user-images.githubusercontent.com/40482367/148391080-83bf2115-86bb-4def-8071-ba44930c7920.jpeg)

**Comment by WesleyVanNeck** [comment]
> ### Describe the bug
> ![Screenshot_20220106_204058](https://user-images.githubusercontent.com/96688215/148384544-26486ea6-cdb2-4660-8858-1e378eebe842.jpg)
> 
> ### The log file and images/videos
> ![Screenshot_20220106_204058](https://user-images.githubusercontent.com/96688215/148384670-734fa7e3-035b-494c-ad53-dacbdb95c683.jpg)
> 
> ### Steps To Reproduce
> ```gfm
> Play play store version of ojav launcher and create world open lan  then open the chrome version of pojav laun her find hes world and done but its little bit laggy when 2 pojav launcher running
> ```
> 
> ### Expected Behavior
> Its run good but lag in playstore version
> 
> ### Platform
> ```gfm
> - Device model: vivo y20
> - CPU architecture: arm64
> - Android version: 10
> - PojavLauncher version: 
> Chrome can cook
> ```
> 
> ### Anything else?
> Pls add new renderer So i can use shader And run smooth when i have 128 gb and 8gb ram And the opengl 5.00 Fix the microsoft account bug And @$@$@$@$@$@$@$@$ And tyyyyy6yyyyyyyyyyyyyyyyyyyyyy Yyyyyyyyyyyyyyyyyyyy thank you. :))
> 
> >

there is no opengl 5.0

**Comment by imjustpenguin** [comment]
Um yes?

**Comment by imjustpenguin** [comment]
Ok 

im just gonna still in normal

**Comment by WesleyVanNeck** [comment]
@khanhduytran0 just close this this is spam in my opinian

**Comment by Mathias-Boulay** [comment]
Well, nice to know this can work
I'll close the issue nonetheless
