### ISSUE TITLE
[BUG]curseforge/masa's mods can't enter menu

### ISSUE THREAD

**Issue by routhing** [PojavLauncherTeam/PojavLauncher#2519]
### Describe the bug

In the Survival-Redstone Server play.islet.world, The auxiliary Mods of Masa's shoes is important. There is a well-known problem with the Mods he wrote, it was unable to enter the main interface normally for a while.

At first, it can be operated, but after a while, I don't know why it can't be operated.

![Screenshot_2022-01-07-22-57-03-480_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/71493668/148565701-8b66131e-5ce3-4be9-a192-8c249550e8c9.jpg)
![Screenshot_2022-01-07-23-21-07-842_com microsoft emmx](https://user-images.githubusercontent.com/71493668/148565702-d2bbc2b7-9056-4d8b-8d32-008cd4611204.jpg)
https://user-images.githubusercontent.com/71493668/148565765-82aa6a15-7293-468e-8b26-9db8fd5ac2b3.mp4

### Steps To Reproduce

```markdown
Simply speaking, there is no response when pressing the M key.
```

### Expected Behavior

Report an error and fix it if you have time.

### Platform

```markdown
- Device model: redmi k30 5g
- CPU architecture: sdm765g(sm7250)
- Android version: 10
- PojavLauncher version: The picture above, the version updated a few days ago.
- Game Version: 1.17.1-fabric(能力整合）
（能力整合 Simple translation：The integration package is published at MinecraftChineseForum）
downloadlink：https://cloud.vlssu.com/s/WkIA?path=%2F20-1.17.1-Fabric
```

**Comment by GoneSubject1** [comment]
Lúc đầu thì mổ được nhưng sau một thời gian không hiểu sao lại không mổ được.

**Comment by GoneSubject** [comment]
sorry accident comment

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by routhing** [comment]
Switching input methods within the game will cause Masa's mods to fail to open the main menu. On the computer side, the problem can be solved by switching the background window. But at present, you can only relaunch the game on the PojavlauncherAPP.

**Comment by routhing** [comment]
This is obtained through the computer test of netizens.

**Comment by routhing** [comment]
I didn't notice you gave me the #1948 link, I'm so sorry I don't know the “mod 'X' ” mean, until then I think the “X” is a mod name. It won't happen again.

**Comment by GoneSubject** [comment]
> I didn't notice you gave me the #1948 link, I'm so sorry I don't know the “mod 'X' ” mean, until then I think the “X” is a mod name. It won't happen again.

the mod "X" his mean is the list of mods that working or not
