### ISSUE TITLE
Will it work?

### ISSUE THREAD

**Issue by BryleHelll** [PojavLauncherTeam/PojavLauncher#252]
Install minecraftforge on other launcher and transfer it pojav launcher. Will it work??? I need your answer.

**Comment by BryleHelll** [comment]
*transfer to pojav

**Comment by BryleHelll** [comment]
@khanhduytran0

**Comment by BryleHelll** [comment]
@artdeell

**Comment by BryleHelll** [comment]
@MCUmbrella

**Comment by khanhduytran0** [comment]
No

**Comment by khanhduytran0** [comment]
@ MCUmbrella is not in our team. He is only contribute OptiFine work status.

**Comment by khanhduytran0** [comment]
@BryleHelll

**Comment by BryleHelll** [comment]
Why it wont work 😞😞😞

**Comment by BryleHelll** [comment]
???

**Comment by BryleHelll** [comment]
Make your answer simple

**Comment by BryleHelll** [comment]
@khanhduytran0 Apk of 2.5.1 unstable 1. Pls...

**Comment by khanhduytran0** [comment]
It's another unplayable version

**Comment by khanhduytran0** [comment]
You can't launch Minecraft in.

**Comment by khanhduytran0** [comment]
> Install minecraftforge on other launcher and transfer it pojav launcher. Will it work??? I need your answer.

No, at the moment. But you don't need install on other launcher. Our launcher will provide a way to launch the installer directly in GUI and you can customize your install mod process.
