### ISSUE TITLE
[BUG] Physical keyboard keys are detected as space

### ISSUE THREAD

**Issue by Nowa-Ammerlaan** [PojavLauncherTeam/PojavLauncher#2521]
### Describe the bug

I have a device with a physical keyboard (an FxTec Pro1). When playing Minecraft, all the keys on the keyboard are detected as space, this makes it impossible to move Steve using WASD etc. All he does is jump around. Interestingly enough, when opening the chat the keyboard functions as expected, e.g. I get the correct letters in the chatbox.

I tried both the latest version from the Google Play store, and the latest apk from GitHub Actions (10e4187). Both have the same issue. I'm launching Minecraft version 1.7.10 (in the latest build the launcher seems to launch that version regardless of which version you have selected, but that is a separate issue.) I tried removing the move buttons from the on screen overlay, but that didn't help.

### Steps To Reproduce

```markdown
1. Press play and load a new world
```

### Expected Behavior

- Keys on the keyboard are correctly mapped. Enabling the use of WASD etc.

### Platform

```markdown
- Device model: Fxtec Pro1
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: Latest build from GitHub Actions (10e4187) and Latest from Play Store (3.3.1.1)
```

**Comment by Mathias-Boulay** [comment]
play store build isn't 3.3.1.1 but you tested with action builds anyway.
Can you get in touch with me in the pojav launcher discord ? (Mathias-Boulay, I should be easy to find)
I'll need you to do some testing of custom debug builds since you're the first one to report this

**Comment by Mathias-Boulay** [comment]
Bug resolved on discord, patches from the custom build scheduled for later
