### ISSUE TITLE
[BUG] Texture Bug

### ISSUE THREAD

**Issue by L0n3F0x** [PojavLauncherTeam/PojavLauncher#2522]
### Describe the bug

Exactly like I remember all the textures become jpg after a killing a chicken.

### Steps To Reproduce

```markdown
Start The game version 1.14.4 (Optifine) enter a survival world and kill/punch a chicken
```

### Expected Behavior

I expect to kill a chicken and don’t have the jpeg bug so I can play without resetting every time

### Platform

```markdown
- Device model: Samsung A10s
- CPU architecture: ARM
- Android version: Android 11
- PojavLauncher version: latest on the playstore
```

### Anything else?

idk if it’s on my cellphone or happens on other phones/tablets

**Comment by GoneSubject** [comment]
use gl4es 1.1.4 not 1.1.5

**Comment by L0n3F0x** [comment]
Oh. Thank you, so that bug is provoke by gl4es 1.1.5?

**Comment by GoneSubject** [comment]
> Oh. Thank you, so that bug is provoke by gl4es 1.1.5?

yes gl4es is for old version and gl4es 1.1.5 is for newer version

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
