### ISSUE TITLE
[BUG] <3D shareware v1.34 crash>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2523]
### Describe the bug

The game crashes to game exited when launching 3D shareware

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. login
3. launch 3D shareware v1.34
4. crash
```

### Expected Behavior

3D shareware launch successful

### Platform

```markdown
- Device model: galaxy a31
- CPU architecture: aarch64
- Android version: android 11
- PojavLauncher version: crocus-309-10e4187a7-v3_openjdk
```

### Anything else?

(づ￣ ³￣)づ

**Comment by Mathias-Boulay** [comment]
most likely shader issue.
Did you try virgl renderer, assuming your device isn't garbage ?

**Comment by Shromeyy** [comment]
still crash

**Comment by NotAHero04** [comment]
Send log moment

**Comment by Shromeyy** [comment]
`
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7833666/latestlog.txt)

**Comment by NotAHero04** [comment]
Looks like your Minecraft JAR has broken. Delete the file and try again.

**Comment by SprainedSpark89** [comment]
if you don't know how to delete your broken version go to the pojavlauncher folder go to .minecraft then versions then go to the version in the folder delete the folder then go to pojavlauncher app launch the version if it is still broken you may have to download it from the minecraft fandom.

**Comment by SprainedSpark89** [comment]
is it still happening

**Comment by Mathias-Boulay** [comment]
iirc current dev builds can handle it now
