### ISSUE TITLE
[BUG] Game freezing when i go to the nether.

### ISSUE THREAD

**Issue by Zolser228** [PojavLauncherTeam/PojavLauncher#2524]
### Describe the bug

when i play on pojav laucher and go to the nether my screen just starting freezing from 40-50 fps to 1 for some time and its happening every 3-5 second. whats the problem?
using mc 1.12.2 forge- 14.23.5.2860

### The log file and images/videos

im writing from pc not the phone i dont have screenshots or videos

### Steps To Reproduce

```markdown
i dont know how to fix it
```

### Expected Behavior

i dont know why its happening

### Platform

```markdown
- Device model: samsung galaxy a51
- CPU architecture: idk
- Android version: 11
- PojavLauncher version: newest
```

### Anything else?

its super annoying bug.

**Comment by GaucovyAero** [comment]
It's not a bug, just your CPU is loading new chunks. Buy a faster phone if you want to get better performance.
You can try:

1. Switching renderer to VGPU (may crash at start! If it crashes, switch to the renderer you were using before)
2. Allocating more RAM
3. Using Memory Booster (RAM Booster) to turn off background applications before you start pojav.
4. Quitting the world when you're in the Nether and joining back in.

- Final: Try to use OptiFine (may crash!) or other FPS boosting mod for 1.12.2. Also try vanilla 1.12.2 and see if it runs better.
- Verdict: Use what works the best (self-explained)

**Comment by Zolser228** [comment]
ok i will try

**Comment by Mathias-Boulay** [comment]
Fixed (or at least works better) in the release candidate build
