### ISSUE TITLE
[BUG] Crash with all renders on 1.7.10 (except vulkan, but with it 5-10 fps)

### ISSUE THREAD

**Issue by cherepavel** [PojavLauncherTeam/PojavLauncher#2526]
### Describe the bug

Minecraft 1.7.10 crashes after loading the world in 3-5 seconds on all renders except vulkan. But with it fps 5-10, everything lags.

### The log file and images/videos

1. gl4es 1.1.4 (OpenGL ES2) - crash after loading world
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7834080/latestlog.txt)

2. gl4es 1.1.5 (OpenGL ES 2) - crash after loading world
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7834088/latestlog.txt)

3. gl4es 1.1.5 (OpenGL ES 3) - crash after loading world
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7834093/latestlog.txt)

4. **zlink (Vulkan) - playable, but very low fps 5-10**

5. vgpu (OpenGL ES 3)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7834095/latestlog.txt)

gif crash
![123](https://user-images.githubusercontent.com/24592649/148661490-0925c59b-36a8-4c10-a22f-d21823f1eaa5.gif)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Select minecraft 1.7.10 version
3. Play
4. Loading world
5. ???
6. After 5 sec - crash
```

### Expected Behavior

I expect the game to launches

### Platform

```markdown
- Device model: Asus Zenfone 7 Pro
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: from google play || 3.3.1.1_rel_20210321
```

**Comment by cherepavel** [comment]
Everywhere at the end of the logs - **ERROR: elf_dynamic_array_reader.h (64)]** tag not found

**Comment by khanhduytran0** [comment]
gl4es's VBO needs to be disabled for 1.7.10. It can be found in the launcher settings.

**Comment by khanhduytran0** [comment]
Since the latest Play Store release isn’t updated, head to the [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk) tab for it.

**Comment by cherepavel** [comment]
> gl4es's VBO needs to be disabled for 1.7.10. It can be found in the launcher settings.

VBO has appeared since 1.8.9? I do not see this parameter in the minecraft settings, as well as in the pojavlauncher settings

**Comment by cherepavel** [comment]
Yes, its working! Thanks!

**Comment by SmileBoy45** [comment]
Cómo lo solucionaste??
