### ISSUE TITLE
Shader and packs glitch

### ISSUE THREAD

**Issue by imjustpenguin** [PojavLauncherTeam/PojavLauncher#2528]
### Describe the bug

![Screenshot_20220109_193616](https://user-images.githubusercontent.com/96688215/148680910-cda62d5b-bb8b-46ed-8570-291479aa20a5.jpg)

### The log file and images/videos

![Screenshot_20220109_193635](https://user-images.githubusercontent.com/96688215/148680930-cd967b27-7faf-4d46-b154-76cd2babf221.jpg)

### Steps To Reproduce

```markdown
1.Go on shaders and use packs it glitch
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: 
- CPU architecture: aarch64
- Android version: 
- PojavLauncher version:Debug
```

### Anything else?

Nothing

Read
![Screenshot_20220109_193523](https://user-images.githubusercontent.com/96688215/148680981-da847ec0-5b14-437c-9379-209b6d21dba8.jpg)
more....

**Comment by WesleyVanNeck** [comment]
Not enough details aka no latest log also do you have a rtx 3090 on you phone? I think not so don't expect shaders to work
