### ISSUE TITLE
[BUG] Repair VirGL eta when

### ISSUE THREAD

**Issue by InfiniXDerg** [PojavLauncherTeam/PojavLauncher#2531]
### Describe the bug

VirGL old bug went off
![Screenshot_PojavLauncher (Minecraft_ Java Edition para Android)_2022-01-09-20-12-20-818](https://user-images.githubusercontent.com/75786233/148697111-8dc5ce99-bb41-4995-9f77-6fdea6a70fca.png)

### The log file and images/videos

Image is already up
Also i cant upload the log There lol

### Steps To Reproduce

```markdown
Start
Go to 1.16.5
Set any shader
VirGL old bug went off
```

### Expected Behavior

The Game executes

### Platform

```markdown
- Device model: NX679J (Prototype of RM7)
- CPU architecture: ARM64
- Android version: 12
- PojavLauncher version: idk literally
```

### Anything else?

_Unban from Discord eta when_

**Comment by GoneSubject** [comment]
enable FBO when

**Comment by irice7** [comment]
what build is that?

**Comment by Mathias-Boulay** [comment]
We cannot fix virgl tbh

**Comment by Mathias-Boulay** [comment]
We don't make it
