### ISSUE TITLE
[BUG] Why does Timeless and Classics Mod Crash

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#2532]
### Describe the bug

So I just downloaded a New Version of this mod called Timeless and Classics for those who dont know what this mod is this is a gun mod for 1.16.5 But suddenly its just crash

### The log file and images/videos

[crash-2022-01-10_02.04.01-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7836496/crash-2022-01-10_02.04.01-client.txt)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Launch the 1.16.5 Forge
3..
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture:8x ARM Cortex-A53 @ 2.30 GHz
- Android version: 9
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

.

**Comment by GoneSubject** [comment]
#1948 and fixed in github builds

**Comment by NotAHero04** [comment]
But apparently the log says different. These mods are not tested **correctly**.

**Comment by Jamespoxdxdxd** [comment]
Oh Ok Ok Thanks guys sorry for late reply
