### ISSUE TITLE
[BUG] 1.18 crashing at red home screen (need support for opengl3.2)

### ISSUE THREAD

**Issue by wonkywonks** [PojavLauncherTeam/PojavLauncher#2533]
### Describe the bug

Description: Rendering overlay

This is what i see everytime i try to load 1.18 and 1.18.1. everything is fine with 1.17 but idk why 1.18 doesn't work and it keeps asking for opengl 3.2, so can we get some support on that. 

### Steps To Reproduce

```markdown
1. Start Launcher, select 1.18 or 1.18.1 with any renderer
```

### Expected Behavior

I expect the game to launch

### Platform

```markdown
- Device model: OnePlus A6003
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest from play store
```

**Comment by GoneSubject** [comment]
can you send the latestlog.txt?

**Comment by wonkywonks** [comment]
Can you guide where to find it, cause i didn't find it in mentioned area.

**Comment by GoneSubject** [comment]
> Can you guide where to find it, cause i didn't find it in mentioned area.

you can find it in sdcard/Android/data/net.ndt.pojavlaunch(debug)/files

**Comment by wonkywonks** [comment]
nvm found it
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7845797/latestlog.txt)

**Comment by smaska007** [comment]
I have the same problem
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7848156/latestlog.txt)

**Comment by GoneSubject** [comment]
> nvm found it
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7845797/latestlog.txt)
>  

the assets-v0 is not compatible you may need ti check [here](https://pojavlauncherteam.github.io/updates/117.html)

**Comment by GoneSubject** [comment]
> I have the same problem
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7848156/latestlog.txt)
> 

yes just fix like the same 
> > nvm found it
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7845797/latestlog.txt)
>  the assets-v0 is not compatible you may need to check [here](https://pojavlauncherteam.github.io/updates/117.html)

**Comment by wonkywonks** [comment]
@GoneSubject1 where do we copy this file?

**Comment by GoneSubject** [comment]
> @GoneSubject1 where do we copy this file?

if the file assets-v0 you must copy/cut it to sdcard/Android/data/net.ndt.pojavlaunch(debug)/files/.minecraft/resourcepacks or sdcard/games/PojavLauncher/.minecraft/resourcepacks and make sure you turned in "show hidden files"

**Comment by wonkywonks** [comment]
i tried it like that but didn't word had to try 2 different file managers to fix it but thanks for your help, it's much appreciated.

**Comment by GoneSubject** [comment]
> i tried it like that but didn't word had to try 2 different file managers to fix it but thanks for your help, it's much appreciated. 

i recommend you to use ZAchiver
