### ISSUE TITLE
how to get latest log on chromebook

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2537]
### Is this request related to a bug?

no it is to help

### Describe the request.

you go to play files this is where android app folders go so there maybe a games folder or you need to go to the android folder and find the app.

### Anything else?

i want to help

![Screenshot 2022-01-10 10 39 04 AM](https://user-images.githubusercontent.com/87820585/148820708-2453b27c-b9d4-42bc-b82d-23cf30631736.png)
https://user-images.githubusercontent.com/87820585/151851980-d53f12a5-97b1-4d7d-ae70-f1a8038b5648.mp4

**Comment by ghost** [comment]
install zarchiver from playstore

**Comment by SprainedSpark89** [comment]
there is no issue i just want to help people that don't know how

**Comment by IwatchTVallot** [comment]
Idkbut I have same problem

**Comment by SprainedSpark89** [comment]
no problem here this is how you do it read the Describe the request and look at the screen shot

**Comment by SprainedSpark89** [comment]
this was to help people but i am fine with this closed
