### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by GodRragon** [PojavLauncherTeam/PojavLauncher#2539]
### Describe the bug

This renderer updated by pojavlauncher has rendering errors in 1.18.1, and the frame rate is not very high，And I installed Assets-v0.zip，There will be a situation of up and down, disappears after restarting
(I don't know if I have sent this, it can make people feel clear because I use the translation software to translate, I don't speak English.)

### Steps To Reproduce

```markdown
Rendering error
```

### Expected Behavior

I hope that the game will start normally and can play normal.

### Platform

```markdown
- Device model:Xiaomi RedmiK20Pro Exclusive version
- CPU architecture: Snapdragon 855
- Android version: 11
- PojavLauncher version：3.3.1.1
```

**Comment by GodRragon** [comment]
Because I was first feedback on Github, some questions also please forgive

**Comment by irice7** [comment]
Okay but wtf you mean 
> this renderer ?

**Comment by GodRragon** [comment]
Installed assets-v0.zip can go in, but there will be a display error in the game

**Comment by irice7** [comment]
Log?

**Comment by GodRragon** [comment]
![Screenshot_2022-01-12-00-00-46-810_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978083-50002712-b015-464a-98a3-91ab52039458.jpg)
![Screenshot_2022-01-12-00-02-25-318_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978123-8f6be529-6bfc-4fea-83ea-bb86141e15f5.jpg)
![Screenshot_2022-01-12-00-02-49-743_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978129-322a4e14-fa9a-4129-81c1-1cd2e1231922.jpg)
![Screenshot_2022-01-12-00-04-29-867_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978142-ac69707c-6b61-41cb-be93-d1c685e0ae63.jpg)
![Screenshot_2022-01-12-00-04-40-424_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978149-601c6de8-0db7-43d0-a365-f66e6c5bbeba.jpg)

**Comment by GodRragon** [comment]
I just took a screenshot

**Comment by GodRragon** [comment]
The first one is the display effect without assets-v0.zip installed

**Comment by GodRragon** [comment]
As you can see, there will be black textures after entering the map, and the frame rate is very low

**Comment by irice7** [comment]
Bruh, use gl4es 1.1.5????
VirGL are kinda unoptimized so use that.

**Comment by GodRragon** [comment]
![Screenshot_2022-01-12-00-10-08-334_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148979323-e77f2299-67dc-4dc0-8b10-c48501be0a43.jpg)
![Screenshot_2022-01-12-00-09-37-495_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148979331-4b45a726-9680-4332-b0dc-cb420731b2c4.jpg)

**Comment by irice7** [comment]
Ok im stupid so basically wait someone answers.
Nice

**Comment by GodRragon** [comment]
A prompt appears that the selection is still the same as the beginning, and the selection of OK is also the same

**Comment by GoneSubject** [comment]
> ![Screenshot_2022-01-12-00-00-46-810_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978083-50002712-b015-464a-98a3-91ab52039458.jpg)
> ![Screenshot_2022-01-12-00-02-25-318_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978123-8f6be529-6bfc-4fea-83ea-bb86141e15f5.jpg)
> ![Screenshot_2022-01-12-00-02-49-743_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978129-322a4e14-fa9a-4129-81c1-1cd2e1231922.jpg)
> ![Screenshot_2022-01-12-00-04-29-867_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978142-ac69707c-6b61-41cb-be93-d1c685e0ae63.jpg)
> ![Screenshot_2022-01-12-00-04-40-424_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148978149-601c6de8-0db7-43d0-a365-f66e6c5bbeba.jpg)
> 

why use virgl render

**Comment by GoneSubject** [comment]
> ![Screenshot_2022-01-12-00-10-08-334_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148979323-e77f2299-67dc-4dc0-8b10-c48501be0a43.jpg)
> ![Screenshot_2022-01-12-00-09-37-495_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148979331-4b45a726-9680-4332-b0dc-cb420731b2c4.jpg)
> 

ok why opengl 2? i mean better use opengl 3 and follow [these](https://pojavlauncherteam.github.io/updates/117.html) instructions

**Comment by GodRragon** [comment]
![Screenshot_2022-01-12-00-19-44-677_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148980850-e3d2187b-6115-403e-ab4b-aefd91440938.jpg)
![Screenshot_2022-01-12-00-18-46-817_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148980863-1ffd34e0-3456-4105-abae-7963c2b9fb51.jpg)
![Screenshot_2022-01-12-00-16-42-178_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148980876-5e851f77-1657-475a-8858-a8785c38ea36.jpg)

**Comment by GoneSubject** [comment]
> ![Screenshot_2022-01-12-00-19-44-677_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148980850-e3d2187b-6115-403e-ab4b-aefd91440938.jpg)
> ![Screenshot_2022-01-12-00-18-46-817_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148980863-1ffd34e0-3456-4105-abae-7963c2b9fb51.jpg)
> ![Screenshot_2022-01-12-00-16-42-178_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57678105/148980876-5e851f77-1657-475a-8858-a8785c38ea36.jpg)
> 

use the [patcher](https://cdn.discordapp.com/attachments/724163890803638277/922043517860212736/Pojav117AssetsPatcher.) then

**Comment by GodRragon** [comment]
assets-v0.zip？

**Comment by GodRragon** [comment]
link can't be opened

**Comment by GoneSubject** [comment]
> link can't be opened

it will downlaod something when you press it

**Comment by shenshi-shenshi** [comment]
![Uploading Screenshot_2022-01-12-00-56-37-761_com.android.chrome.jpg…]()

**Comment by GodRragon** [comment]
![Screenshot_2022-01-12-00-56-37-761_com android chrome](https://user-images.githubusercontent.com/57678105/148987091-760857fe-ca92-408d-ad0a-f5234eefcef2.jpg)

**Comment by MakaronPlay** [comment]
Bruh use vpn tho

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
