### ISSUE TITLE
Optifine 1.7.10 and 1.8

### ISSUE THREAD

**Issue by Statzar** [PojavLauncherTeam/PojavLauncher#254]
Good day! A couple of months ago, on version 2.4.2 pre 1, I tried a lot of ways to run optifine, and I finally got it. But after a week I had to "clear" my phone. When I downloaded pojav launcher again, I was unable to install optifine so far. What I mean by this is: my device supports optifine. But I again faced the problem of installing it. Please try to help me. Sorry for my English, I translated via google translator

**Comment by khanhduytran0** [comment]
So what about your device?

**Comment by Statzar** [comment]
Sorry, the site translates a little strange. If I understand correctly, are you asking about my device? If so, then this is Huawei Honor 7a model DUA-L22

**Comment by khanhduytran0** [comment]
Try on v3
