### ISSUE TITLE
Make sure you can run a server as well

### ISSUE THREAD

**Issue by beetrootpotatocarrot** [PojavLauncherTeam/PojavLauncher#2540]

**Comment by NotAHero04** [comment]
Run the server JAR on the mod installer.

**Comment by 1493028** [comment]
No it does't work

**Comment by 1493028** [comment]
Эта заметка не работает

**Comment by Mathias-Boulay** [comment]
This won't be the focus on the launcher, also it can technically be done via the mod installer
