### ISSUE TITLE
[BUG]  Forge is not working

### ISSUE THREAD

**Issue by XavierErrorLog** [PojavLauncherTeam/PojavLauncher#2541]
### Describe the bug

Every time I select options and forge download and crashes or says Game Exited plus the versions I have are forge-1.12.2-14.23.5.2859, and runtime file jdk17-arm64-20210825

### Steps To Reproduce

```markdown
1. Start Pojavlancher 
2. Clicks Options 
3. Crashes or Game Exited Pops Up
```

### Expected Behavior

I expect the game to let me add forge to the game 

### Platform

```markdown
- Device model: Lenovo Chromebook duet
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by GoneSubject** [comment]
you must use java 8 to download it... and use jre17 btw

**Comment by XavierErrorLog** [comment]
Where can i download Jave 8 ?

**Comment by GoneSubject** [comment]
> Where can i download Jave 8 ?

[here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions)

**Comment by XavierErrorLog** [comment]
Where can i download Jave 8?

**Comment by GoneSubject** [comment]
> 
> Where can i download Jave 8?
> 

can you see what to choose?

**Comment by XavierErrorLog** [comment]
Oh i see it thank you mate!

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
