### ISSUE TITLE
[F-Req] CAN (oppo A12 android 9)can use keyboard and mouse ?

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2542]
### Is this request related to a bug?

Just to be sure

### Describe the request.

Because im planning to buy a keyboard and mouse

### Anything else?

Can it?

**Comment by khanhduytran0** [comment]
This is not a valid Pojav issue.
~~We don’t own your device, so how do we know?~~
You just have to check if
- it runs android 8+
- it has OTG support
