### ISSUE TITLE
1.16.5 forge Pojav do not sees the Mods HELP

### ISSUE THREAD

**Issue by MakaronPlay** [PojavLauncherTeam/PojavLauncher#2544]
### Describe the bug

PojavLauncher doesnt sees the mods for the directory because of java.security.privilegedactionexception null forge is the last version.
Please help

### The log file and images/videos

![Screenshot_20220113_003200_net kdt pojavlaunch](https://user-images.githubusercontent.com/97637579/149229633-4897fc90-5f83-440f-8d77-48fa45cc47cd.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7858252/latestlog.txt)

### Steps To Reproduce

```markdown
java.security.privilegedactionexception null
```

### Expected Behavior

Mods are loaded succesfuly

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
The “Open Directory” operation hasn’t been implemented.

**Comment by MakaronPlay** [comment]
And how do i implement It?

**Comment by MakaronPlay** [comment]
![Screenshot_20220113_131127](https://user-images.githubusercontent.com/97637579/149310484-905b1ce7-c9b2-4a88-bbb7-5f377d9fcdc1.jpg)
