### ISSUE TITLE
[BUG] LabyMod Freaked Out

### ISSUE THREAD

**Issue by TERMZJosh** [PojavLauncherTeam/PojavLauncher#2545]
### Describe the bug

when i use GL4ES with labymod at first is crashes
and then run labymod at the seccond time....there is some missing textures and it freaked out for some reason

### The log file and images/videos

![Screenshot_20220112_190445](https://user-images.githubusercontent.com/88063332/149230609-843d402c-d93b-44f1-a089-4cdac8380fd3.jpg)

### Steps To Reproduce

```markdown
1. Start Labymod 1.16.5
2. Go to MultiPlayer
3. Click addon
4. Click (trending,top,fetured,etc)
5. Enjoy
```

### Expected Behavior

GL4ES

### Platform

```markdown
- Device model: vivo y11 3/32G
- CPU architecture: aarch54
- Android version: 11
- PojavLauncher version: "electric boogaloo"
```

### Anything else?

bring back zink and recompile it for better performance

**Comment by GoneSubject** [comment]
> The log file and images/videos
[Screenshot_20220112_190445
](https://user-images.githubusercontent.com/88063332/149230609-843d402c-d93b-44f1-a089-4cdac8380fd3.jpg)

that's look normal

**Comment by Cube5x59999** [comment]
gonesubject can you help me bc virgl crashes on my device samsung tab a cpu armv8l
