### ISSUE TITLE
[BUG] I Cant Install A Mod(mod installer) cause its keep crashing

### ISSUE THREAD

**Issue by Vons10498** [PojavLauncherTeam/PojavLauncher#2546]
### Describe the bug

I cant install a mod(mod installer) cause it was crashing
I dont know how to make a agruments for installing it

### The log file and images/videos

![20220113_111945](https://user-images.githubusercontent.com/94052160/149260018-18c2a0e2-d975-4751-aa18-df249fd9892d.jpg)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Click Options
3. Click "Launch A Mod Installer(Forge etc.)"
4. It crashed
```

### Expected Behavior

It will crashed

### Platform

```markdown
- Device model: Samsung a10s
- CPU architecture: armeabi-v7a
- Android version: 9
- PojavLauncher version: latest
```

**Comment by NotAHero04** [comment]
> PojavLauncher version: latest
>
There are at least 3 "latest": latest release, latest GitHub build, latest Google Play internal build. With only "latest", we couldn't know which advice is best for you.
~~Please provide the crash log, which can be accessed in /sdcard/PojavLauncher/latestcrash.txt.~~ It seems no file manager was found to handle your request, so try installing one (like ZArchiver).

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
