### ISSUE TITLE
[BUG] <can't install fabric installer

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2548]
### Describe the bug

this is what it looks like when i try to install it

### The log file and images/videos

![Screenshot_20220112-102834_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/94804069/149281832-a7a011eb-92d2-4d2b-a535-d7c2fe93a51c.jpg)

### Steps To Reproduce

```markdown
1. start pojavlauncher
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

nope

**Comment by MakaronPlay** [comment]
Try scaling down

**Comment by SprainedSpark89** [comment]
it is in the corner

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
