### ISSUE TITLE
[BUG] <1.18.1 keeps crashing>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2549]
### Describe the bug

Everytime i launch 1.18.1 it crashes

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7860873/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. login
3. launch 1.18.1
4. Crash
```

### Expected Behavior

You know what i expect

### Platform

```markdown
- Device model: Galaxy A31
- CPU architecture: aarch64
- Android version: android 11
- PojavLauncher version: crocus-327-6d2295d46
```

### Anything else?

nope

**Comment by MakaronPlay** [comment]
Have you done the assets and java runtime and patch thing?

**Comment by ajit56** [comment]
I use optifine 1.18.1

**Comment by MakaronPlay** [comment]
https://pojavlauncherteam.github.io/updates/117.html

**Comment by khanhduytran0** [comment]
> You know what i expect

Now we expect you to response.

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
