### ISSUE TITLE
can't connect to the server in local area network

### ISSUE THREAD

**Issue by hbyonly1** [PojavLauncherTeam/PojavLauncher#2550]
### Describe the bug

all the configs are right(I promise) but I still can't use pojav to connect to the server in local area network,it keep shows "connection refused",I believe that there is something wrong with the internal client

### Steps To Reproduce

```markdown
1.start a server in local area network in computer(ip:localhost host:25565)(it is able to connect in the computer and there's no problem with the server)
2.use pojav(it's in the same network) to connect to the computer's ip with the right host
```

### Expected Behavior

connect to the server successfully

### Platform

```markdown
- Device model: iQOO neo 5
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by ajit56** [comment]
Which server ?

**Comment by hbyonly1** [comment]
> Which server ?

em you mean the version?paper 1.12.2 I also tried spigot 1.16,none of them can be connected with pojav

**Comment by khanhduytran0** [comment]
> it keep shows "connection refused"

Have you tried with another computer?

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build

**Comment by yubunus** [comment]
I have the same issue going on right now, I am using an ipad 5. It worked yesterday but is not working anymore today

**Comment by artdeell** [comment]
Because you are on the wrong repo. This is the Android repo, with Android
issues

чт, 6 июл. 2023 г., 05:50 sunuy192 ***@***.***>:
