### ISSUE TITLE
Permission denied to load mods 1.16.5 pojav

### ISSUE THREAD

**Issue by MakaronPlay** [PojavLauncherTeam/PojavLauncher#2551]
### Describe the bug

Minecraft loads succesfully without loading mods,  but mods are in the folder. Saw in console that permission is denied, how to give the permission? 

### The log file and images/videos

![Screenshot_20220113_131127](https://user-images.githubusercontent.com/97637579/149469591-277fff11-7b1e-499e-aa3b-335283fa0b32.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7868654/latestlog.txt)

### Steps To Reproduce

```markdown
Loading mods storage/emulated/0/Android/data/net.ndk.pojavlaunch/.minecraft/mods
java.oe.Exxeption: Permission denied
```

### Expected Behavior

20 mods loaded

### Platform

```markdown
- Device model: Huawei P30 lite LX2
- CPU architecture: aarch64
- Android version: last
- PojavLauncher version: last
```

### Anything else?

I said what i need

**Comment by khanhduytran0** [comment]
Literally duplicated of #2544

**Comment by khanhduytran0** [comment]
Can you explain why did you press the “Open \<somewhere\> directory” button? Is it really necessary for importing a configuration file or something like that?

**Comment by MakaronPlay** [comment]
Maybe you mean that i clicked Open The Mod Folder buton in minecraft? I Just tried to understand why there are no mods in folder, and i saw in console that permission is denied.

**Comment by wujinjun-MC** [comment]
Maybe you are running on Android 10 or upper, which has a strict permission control in /storage/emulated/0/Android/data folder, and you are using a file manager like MT manager that copy files into it and set permission 700. Try to set permission to 777 to fix it.

**Comment by Shadowsovereign24** [comment]
> Maybe you are running on Android 10 or upper, which has a strict permission control in /storage/emulated/0/Android/data folder, and you are using a file manager like MT manager that copy files into it and set permission 700. Try to set permission to 777 to fix it.

How do I set the permision to 777?
