### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#2552]
### Is this request related to a bug?

You should add datapack Installer 

### Describe the request.

This will helpful to add datapack before generate world

**Comment by GoneSubject** [comment]
image you are in PojavLauncher and go to another app for 1 second and go back to PojavLauncher and it restart

**Comment by ajit56** [comment]
I want when we click on datapack option,it redirect as jar Installer

**Comment by ajit56** [comment]
@Mathias-Boulay help

**Comment by NotAHero04** [comment]
Data pack is not a .JAR file anyway.

**Comment by ajit56** [comment]
Data pack is .zip

**Comment by ghost** [comment]
There is no built in file opener so at the moment it is impossible.

**Comment by ajit56** [comment]
@Mathias-Boulay
