### ISSUE TITLE
Replay Mod support

### ISSUE THREAD

**Issue by yzf12346** [PojavLauncherTeam/PojavLauncher#2553]
### Is this request related to a bug?

Want to support ffmpeg or terminal
(this paragraph is machine translation)

**Comment by NotAHero04** [comment]
You can watch [this video](https://youtu.be/Bk73xXXiZtM) for replay exporting on rooted devices. If you don't have root, use an APK editor and put the executable to the app libraries, then install it.

**Comment by west-shell** [comment]
ffmpeg or ffmpeg.so ?

**Comment by west-shell** [comment]
> 

could you share a patched apk with ffmpeg inside
