### ISSUE TITLE
[BUG] <Import settings crash>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2554]
### Describe the bug

when clicking on import settings the game crashes to game exited text

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7870153/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojavlauncher
```

### Expected Behavior

e

### Platform

```markdown
- Device model: Galaxy a31
- CPU architecture: aarch64
- Android version: android 11
- PojavLauncher version: crocus-327-6d2295d46-
```

### Anything else?

:)

**Comment by khanhduytran0** [comment]
Incomplete information moment.
- Lacks of latestlog.txt
- There’s no settings importing in vanilla.

**Comment by khanhduytran0** [comment]
Too few info were provided. I had to look at the mapping. Is custom world generation what you’re talking about?
Well, I have yet an idea about implementing a file picker for the game, but one would work by replacing TinyFD :thinking:

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
