### ISSUE TITLE
[BUG] I Set my Renderer to Virglrenderer (Opengl ES 3 ) Exports Opengl 4.3

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#2558]
### Describe the bug

I Set my Renderer to Virglrenderer (Opengl ES 3 ) 
Exports Opengl 4.3 To Play Forge 1.12.2 but This what happened Someone Help me pls
All Mods in my Mod Folder:
SecurityCraft 1.12.2
Currency 1.12.2
Decocraft 1.12.2
Jade 1.12.2
Jei 1.12.2
Optifine 1.12.2
Ptrlib 1.12.2
Worldedit 1.12.2

### The log file and images/videos

![Screenshot_2022-01-15-14-24-25-85](https://user-images.githubusercontent.com/87040006/149612833-732efe7d-e987-4bef-9ed9-e21e15cb852a.jpg)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Launch Forge 1.12.2
3..
```

### Expected Behavior

I Expect to Get a Normal Play

### Platform

```markdown
- Device model: Oppo A12 
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Crocus-310-bb9d2eaf9-v3_openjdk
```

### Anything else?

.

**Comment by Gabbyph12** [comment]
Me too Virgl Is broken plss fix it

**Comment by HansCydric** [comment]
Pls fix this bug 🙏 
![Uploading Screenshot_2022-06-15-20-38-49-89_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

**Comment by GaucovyAero** [comment]
You can fix this by turning off Fast Render in Video Settings -> Performance

**Comment by BroLoveKh** [comment]
LOVE

**Comment by mchnjt** [comment]
> LOVE

~~DETERMINATION~~

**Comment by sofiyanlove** [comment]
Hi

**Comment by sofiyanlove** [comment]
Where is downloaded link please help me
