### ISSUE TITLE
[BUG] When Set Virgl Renderer on 15 and older Title Screen Will Become Broken

### ISSUE THREAD

**Issue by Gabbyph12** [PojavLauncherTeam/PojavLauncher#2559]
### Describe the bug

Title Screen Image Bug and Black Sky When I was using Shaders

### Steps To Reproduce

```markdown
1.Start Pojav launcher
2.Set Virgl Renderer
3.Shader Not Work
```

### Expected Behavior

Example:I expect normal gameplay

### Platform

```markdown
- Device model: Realme C12
- CPU architecture:Octa Core
- Android version: 11
- PojavLauncher version:I dunno
```

**Comment by khanhduytran0** [comment]
If you already knew #2558, why open another one?

**Comment by Gabbyph12** [comment]
Plss Make New Pojav launcher Version And Plss Fix Mouse Bug And Shader Bug

**Comment by khanhduytran0** [comment]
Since VirGL doesn’t emulate RTX 3090, you couldn’t expect SEUS PTGI E12 to work on it without issues. VirGL is experimental after all.

All shader-related issues will be moved to #2322

**Comment by MICDAD100** [comment]
Can anyone create a code like mobile glues to help you because it forces shade approves right but the frame rate will drop so can anyone create the mod that Rashid has run but the performance goes well
