### ISSUE TITLE
[F-Req] Plss Add Joystick

### ISSUE THREAD

**Issue by Gabbyph12** [PojavLauncherTeam/PojavLauncher#2560]
### Is this request related to a bug?
No

Plss add Joystick Like Other Games

**Comment by Henry-Hiles** [comment]
This is actually a good idea

**Comment by Shromeyy** [comment]
what about the sneak button?

**Comment by GoneSubject** [comment]
> what about the sneak button?

put it to right side maybe

**Comment by Shromeyy** [comment]
jump button?

**Comment by GoneSubject** [comment]
> jump button?

yes like how im using ![Screenshot_2022-01-15-22-58-27-327_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/95298052/149628548-3b5be00f-c543-4a41-9e9a-e5cb6e46115f.jpg)

**Comment by Henry-Hiles** [comment]
Or even just an option to create a joystick in custom controls

**Comment by GoneSubject** [comment]
> Or even just an option to create a joystick in custom controls

image add 10 of them

**Comment by Henry-Hiles** [comment]
Wdym 'image add 10 of them'?

**Comment by GoneSubject** [comment]
> Wdym 'image add 10 of them'?

because you said you want an option to create a joystick that mean you can create as much as you like

**Comment by thegarykun** [comment]
![Screenshot_20220116-232328_Discord-Beta](https://user-images.githubusercontent.com/86944088/149671765-f6402c74-12c7-4b39-a6e8-811da279e0c6.png)

someone made a functional joystick (kinda)

**Comment by Gabbyph12** [comment]
It's hard to make that joystick can you add an easy functional joystick

**Comment by Gabbyph12** [comment]
Can I participate to design pojav launcher?

**Comment by Errorbot1122** [comment]
I would really want this

**Comment by ghost** [comment]
No

**Comment by ghost** [comment]
![911370441082429511](https://user-images.githubusercontent.com/70785472/150470708-c00939f1-6dc1-4c10-9d70-f8a11b62762a.png)

**Comment by Mathias-Boulay** [comment]
I have a pretty ready to go library now to implement this. Maybe one day

**Comment by Mathias-Boulay** [comment]
*cough*, That's done with the mainline latest dev version

**Comment by Montivillon** [comment]
> Or even just an option to create a joystick in custom controls

It has on android not even Pojav iOS

**Comment by Montivillon** [comment]
I’m pretty sure you can ask someone to add a mod to add a joystick for those iOS joystick lovers like me

**Comment by Montivillon** [comment]
> ![Screenshot_20220116-232328_Discord-Beta](https://user-images.githubusercontent.com/86944088/149671765-f6402c74-12c7-4b39-a6e8-811da279e0c6.png)
> 
> someone made a functional joystick (kinda)

How do you do that on iOS?
