### ISSUE TITLE
[BUG] <I can't install Minecraft forge 1.12.2>

### ISSUE THREAD

**Issue by GabryBRUH** [PojavLauncherTeam/PojavLauncher#2561]
### Describe the bug

When I try to install Minecraft forge version 1.12.2 - 14.23.5.2860 the app crash and show me a error 1 messages

### The log file and images/videos

https://user-images.githubusercontent.com/94447669/149616718-3aa504ce-859c-4c61-855d-7cd520870117.mp4

### Steps To Reproduce

```markdown
1.start pojavluncher
2. Enter with your account
3. Tap on the setting button under the versions slot
4. Select The first option
5. Choose the forge version you downloaded
6. Wait
7. The app crashes
```

### Expected Behavior

I expect the game will start with forge 

### Platform

```markdown
- Device model: cph2135 oppo a53 s
- CPU architecture: AArch64 processor rev 2
- Android version: v 11.1
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by khanhduytran0** [comment]
You need to set back Java 8 to default, and **leave it Java 8**. Running 1.17+ will just override the selected Java version with the compatible one.

*Don't forget to send logs later*

**Comment by khanhduytran0** [comment]
Also, make sure that you choose Installer instead of Universal.

**Comment by GabryBRUH** [comment]
> You need to set back Java 8 to default, and **leave it Java 8**. Running 1.17+ will just override the selected Java version with the compatible one.
> 
> *Don't forget to send logs later*

How can I do this?

**Comment by GabryBRUH** [comment]
> You need to set back Java 8 to default, and **leave it Java 8**. Running 1.17+ will just override the selected Java version with the compatible one.
> 
> *Don't forget to send logs later*

How can I do this?

**Comment by khanhduytran0** [comment]
> How can I do this?

wait, if you don’t know how, how did you switch to java 17? :eyes:

**Comment by GabryBRUH** [comment]
> > How can I do this?
> 
> wait, if you don’t know how, how did you switch to java 17? :eyes:

I Don't know I didn't switch I just download the app and a few weeks later I try to lunch forge
