### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by EgorBro918** [PojavLauncherTeam/PojavLauncher#2562]
### Describe the bug

Hello dear developers please tell me how to fix, error 1Hello dear developers please tell me how to fix, error 1 malyu.😭

### The log file and images/videos

Пажалуйста 

### Steps To Reproduce

```markdown
Пожалуйста
```

### Expected Behavior

Пожалуйста 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
Пожалуйста
```

### Anything else?

Пожалуйста

**Comment by MakaronPlay** [comment]
Егор, бро ну хоть бы сказал на какой версии пытаешься играть
