### ISSUE TITLE
[BUG] whenever i login app crashes

### ISSUE THREAD

**Issue by Asalt8** [PojavLauncherTeam/PojavLauncher#2564]
### Describe the bug

I couldn't join servers so I installed testing v3. It required java runtime arm/aarch32 (.tar.xz) and I choose the one that came with MCinabox. I even tried other versions, erased app data, even deleted pojavlauncher folders, still the same 

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7875856/latestcrash.txt)

### Steps To Reproduce

```markdown
1. Open MCinabox 
2. Login offline account
3. App crashes
```

### Expected Behavior

Game crashes after login

### Platform

```markdown
- Device model: Samsung galaxy v3 2017 SM-J330F
- CPU architecture:
 Quad-Core, 1 processor: 1.4GHz Quad-Core ARM Cortex-A53
- Android version: 9
- PojavLauncher version: 3.3.1 (edit)
```

### Anything else?

My phone is rooted with magisk and before pojavlauncher worked just fine

**Comment by Asalt8** [comment]
Plz help

**Comment by khanhduytran0** [comment]
Did you know that `Testing V3` was 16 months ago?
The latest with built-in Java was already in Play Store for a year.
PojavLauncher's JRE structure isn’t same as Mcinabox one.

**Comment by khanhduytran0** [comment]
By looking at latestcrash.txt, lacks of Chrome browser/WebView moment.

**Comment by Asalt8** [comment]
Ik I messed up but what do I do now? It just keeps crashing. Also I have v3 on other phone and it works well

**Comment by Asalt8** [comment]
So I need to install chrome?

**Comment by Asalt8** [comment]
Because I debloated my phone completely

**Comment by Asalt8** [comment]
Tysm I installed chrome and it works now :)
