### ISSUE TITLE
[BUG] Microsoft Login not working.

### ISSUE THREAD

**Issue by MynLlama** [PojavLauncherTeam/PojavLauncher#2565]
### Describe the bug

I'm trying to use this on my quest2, I can't tell if it's a software issue or quest2 issue, but I recently migrated my Mojang account to a micrsoft account, and so when I'm trying to log in on the pojav launcher and select micrsoft and go through all the prompts. Once I put in my password it will either just load forever, or give me an error. Usually the first option. Like I said I don't know if this is hardware or software, but any help is appreciated. And yes, I own Minecraft Java on this micrsoft account. 

### Steps To Reproduce

```markdown
1. Sart Pojav
2. Select log in with micrsoft 
3. log in
4. wait forever
```

### Expected Behavior

So like, yeah I don't really know what to put here except that it should launch the game as far as I know

### Platform

```markdown
- Device model: Oculus Quest 2
- CPU architecture: *le shrug*
- Android version: (idk)
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by windows715** [comment]
are you dumb?

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
