### ISSUE TITLE
[BUG] Press W change scale

### ISSUE THREAD

**Issue by GiantTheNOOB** [PojavLauncherTeam/PojavLauncher#2567]
### Describe the bug

when i press W it changes the game scale pls help me its very annoying in pvping and bridging

### Steps To Reproduce

```markdown
nothing
```

### Expected Behavior

it moves forward

### Platform

```markdown
- Device model: infinix zero 8
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: newest
```

**Comment by SprainedSpark89** [comment]
well that's weird are you using any mods?

**Comment by GaucovyAero** [comment]
just change the fullscreen bind to F12 in controls settings

**Comment by Mathias-Boulay** [comment]
What is the minimal setup to reproduce the issue ?

**Comment by GaucovyAero** [comment]
this is a hard android shortcut unfortunately, you cant really fix it other than bind fullscreen to another button
