### ISSUE TITLE
[BUG] <@, # cant be written>

### ISSUE THREAD

**Issue by JAYESHTWADASDAWD** [PojavLauncherTeam/PojavLauncher#2568]
### Describe the bug

hi, 
I came with a bug in which i cant write '@, #' in minecraft chat please help me

### The log file and images/videos

@, # cant be written

### Steps To Reproduce

```markdown
@, # cant be written
```

### Expected Behavior

@, # cant be written

### Platform

```markdown
- Device model: Realme 8s 8/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

@, # cant be written

**Comment by WesleyVanNeck** [comment]
Outdated release go to the Playstore and download it there or use actions build

**Comment by JAYESHTWADASDAWD** [comment]
email ID :- ***@***.*** ***@***.***>*

i am using latest version only

**Comment by khanhduytran0** [comment]
> i am using latest version only

> version 3.3.1.1_rel_<ins>20210206</ins>

But it’s 11 months ago.

**Comment by JAYESHTWADASDAWD** [comment]
email ID :- ***@***.*** ***@***.***>*
does we can write @ in that versoin

**Comment by NotAHero04** [comment]
I couldn't reproduce this issue on the version `crocus_v3-openjdk`. (using Baritone)

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
