### ISSUE TITLE
[BUG] Minecraft version 1.18.1 does not work.

### ISSUE THREAD

**Issue by Starmoon0** [PojavLauncherTeam/PojavLauncher#2570]
### Describe the bug

When it is time to load, the game has crashed because it is rendering overlay.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7882706/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login account
3. Select Minecraft version 1.18.1
4. Download and launch the game
5. Show MOJANG loading GUI
6. Game crashes: app/game exited with code 1
```

### Expected Behavior

Can successfully enter the main menu, and successfully run the game.

### Platform

```markdown
- Device model: Mi 10 Lite Zoom
- CPU architecture: AArch64 Processor rev 14 (aarch64)
- Android version: 12
- PojavLauncher version: crocus-327-6d2295d46-
```

**Comment by MakaronPlay** [comment]
https://pojavlauncherteam.github.io/updates/117.html have you did IT

**Comment by Starmoon0** [comment]
> https://pojavlauncherteam.github.io/updates/117.htmlhave you did IT

Java version 1.17. I just follow these steps. Now I can't make minecraft 1.18.1 work in any way.

**Comment by Starmoon0** [comment]
> https://pojavlauncherteam.github.io/updates/117.htmlhave you did IT

Minecraft version 1.17 works, but version 1.18 does not work. Is there a solution? If there is no solution I can continue to wait to fix this bug.

**Comment by khanhduytran0** [comment]
> Minecraft version 1.17 works, but version 1.18 does not work. Is there a solution? If there is no solution I can continue to wait to fix this bug.

There’s literally category for it
> https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
