### ISSUE TITLE
Help Minecraft loads and at 95% It is Just Black screen

### ISSUE THREAD

**Issue by MakaronPlay** [PojavLauncherTeam/PojavLauncher#2571]
### Describe the bug

I try to load minecraft 1.16.5 with mods, It says that everything  is okay but then It Just shows Black screen

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7880665/latestlog.txt)
[crash-2022-01-17_09.24.02-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7880667/crash-2022-01-17_09.24.02-client.txt)

### Steps To Reproduce

```markdown
¯\(-_-)/¯
```

### Expected Behavior

I see the menu of minecraft with all mods

### Platform

```markdown
- Device model: Huawei P30 lite LX2 
- CPU architecture: aarch6
- Android version: 10
- PojavLauncher version: last
```

### Anything else?

Nope

**Comment by khanhduytran0** [comment]
A mod is using shader and so it isn’t supported. Try switching renderer to VGPU, ~~Zink~~ or virglrenderer 
Also #1948
