### ISSUE TITLE
fps limit when using zink renderer

### ISSUE THREAD

**Issue by EtiLB7** [PojavLauncherTeam/PojavLauncher#2573]
### Describe the bug

my fps usually have 150-200 fps, when using zink, my fps limited to 20 fps, that's a bug or my phone can't handle the renderer? my phone spec is helio g85 mali g52 mc2

### The log file and images/videos

![Screenshot_20220117-203853](https://user-images.githubusercontent.com/97726075/149779082-846004da-6e1b-4289-ba19-10d6f30f7331.jpg)

### Steps To Reproduce

```markdown
Set Renderer To Zink
```

### Expected Behavior

I Can Get Atleast More Than 30 Fps With Zink Renderer

### Platform

```markdown
- Device model: Infinix Hot 10s 4/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release
```

### Anything else?

When I Using Zink Renderer, My Fps Loss Significantly, Also, In Debug Pie, It Show Display Update Has More Percentage More Than Game Renderer, Whatever I Doesn't Using Shaders

**Comment by ajit56** [comment]
Zink is now removed by developers

**Comment by Mathias-Boulay** [comment]
Cannot be solved, we don't make zink

**Comment by Aioowijh** [comment]
Zink Mediatek G85, Mali-G52 MC2 😍😍
