### ISSUE TITLE
1.18.1 Optifine keeps crashing without a bug report

### ISSUE THREAD

**Issue by sometingrandom-MC** [PojavLauncherTeam/PojavLauncher#2575]
### Describe the bug

Application crashes once playing Minecraft for about 2 minutes and doesn't give a bug report when I use Optifine with the Optifine 1.18 Patch.

### The log file and images/videos

![Screenshot_20220117-101340_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/84082592/149795173-2d110901-a485-4aee-b46f-a00ffee60f49.jpg)

### Steps To Reproduce

```markdown
1. Follow this guide (the bottom shows how to use optifine) https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04

2. Start Minecraft

3. Join server

4. Wait for crash
```

### Expected Behavior

It doesn't crash or makes a crash report.

### Platform

```markdown
- Device model: Samsung Tab S7
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Google Play Version
```

**Comment by khanhduytran0** [comment]
> doesn't give a bug report 

At least there should be latestlog.txt right? As described in the form.

> The log file called `latestlog.txt` is located under `Android/data/net.kdt.pojavlaunch/files`, `games/PojavLauncher/` or `games/PojavLauncher/.minecraft`. You may need to activate an option in your file explorer to see hidden files and folders.

**Comment by sometingrandom-MC** [comment]
Ok, here is latestlog.txt
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7918430/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
