### ISSUE TITLE
No puedo entrar con mods

### ISSUE THREAD

**Issue by TikTok-hugoguh76** [PojavLauncherTeam/PojavLauncher#2577]
### Describe the bug

Cuando entre al minecraft, me salió una ventana que ponia "La aplicacion/juego ha terminado con el código 1"

Mods los cuales llebaba:

Neat, doggy talents y ItemPhisycs
![Screenshot_2022-01-17-22-25-39](https://user-images.githubusercontent.com/97919116/149839299-50275be8-aba2-48de-9eea-1277de55a291.jpg)

### Steps To Reproduce

```markdown
Primero entro en ProJav launcher y inicio el juego
Después de esperar un rato me salta el error
```

### Expected Behavior

Espero a que cargue para poder jugar

### Platform

```markdown
- Device model: Huawei bah (tablet) 
- CPU architecture: no lo se
- Android version: 10
- PojavLauncher version: Última versión || versión 3.3.1.1_rel_20210206
```

**Comment by khanhduytran0** [comment]
Lacks of latestlog.txt moment

**Comment by SprainedSpark89** [comment]
do you type english?

**Comment by SprainedSpark89** [comment]
and do you know where latest log is on you device

**Comment by SprainedSpark89** [comment]
and what mods and version of minecraft

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
