### ISSUE TITLE
problem starting version

### ISSUE THREAD

**Issue by Charles7770** [PojavLauncherTeam/PojavLauncher#2578]
### Describe the bug

When starting any version already downloaded before, the app closes with an error that says: the game ended with code 1 and I can never start again every time I want to start one Version always the same thing happens and my device has 2GB of ram I hope they fix it or if there is already a solution, what do I do?

### Steps To Reproduce

```markdown
Start the launcher selected a version and start it and the error appears
```

### Expected Behavior

*I hope they start the versions correctly without errors

### Platform

```markdown
- Device model: gametab/16G
- CPU architecture: aarch32
- Android version: Android 10 Q
- PojavLauncher version: last
```

**Comment by khanhduytran0** [comment]
Lacks of latestlog.txt moment

**Comment by Charles7770** [comment]
--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.7.10
--------- beginning of main
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1024
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-bfsxURNQ2waqCNum50uznQ==/lib/arm
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=600
I/LIBGL   (17035): Initialising gl4es
I/LIBGL   (17035): v1.1.4 built on Jul 19 2020 08:24:33
I/LIBGL   (17035): Using GLES 2.0 backend
I/LIBGL   (17035): loaded: libGLESv2.so
I/LIBGL   (17035): loaded: libEGL.so
I/LIBGL   (17035): Using GLES 2.0 backend
I/LIBGL   (17035): Hardware Full NPOT detected and used
I/LIBGL   (17035): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (17035): FBO are in core, and so used
I/LIBGL   (17035): PointSprite are in core, and so used
I/LIBGL   (17035): CubeMap are in core, and so used
I/LIBGL   (17035): BlendColor is in core, and so used
I/LIBGL   (17035): Blend Substract is in core, and so used
I/LIBGL   (17035): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (17035): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (17035): Extension GL_OES_mapbuffer  detected
I/LIBGL   (17035): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (17035): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (17035): Extension GL_OES_depth24  detected and used
I/LIBGL   (17035): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (17035): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (17035): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (17035): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (17035): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (17035): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (17035): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (17035): high precision float in fragment shader available and used
I/LIBGL   (17035): Max vertex attrib: 16
I/LIBGL   (17035): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (17035): Max texture size: 8192
I/LIBGL   (17035): Max Varying Vector: 15
I/LIBGL   (17035): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (17035): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   (17035): Hardware vendor is ARM
I/LIBGL   (17035): GLSL 300 es supported
I/LIBGL   (17035): GLSL 310 es supported and used
I/LIBGL   (17035): sRGB surface supported
I/LIBGL   (17035): EGLImage to Texture2D supported
I/LIBGL   (17035): EGLImage to RenderBuffer supported
I/LIBGL   (17035): ignore MipMap
I/LIBGL   (17035): Targeting OpenGL 2.1
I/LIBGL   (17035): NPOT texture handled in hardware
I/LIBGL   (17035): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (17035): try to use VBO
I/LIBGL   (17035): glXMakeCurrent FBO workaround enabled
I/LIBGL   (17035): FBO workaround for using binded texture enabled
I/LIBGL   (17035): glX Will try to recycle EGL Surface
I/LIBGL   (17035): Current folder is:/
I/jrelog  (17035): dlopen libgl4es_114.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  (17035): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsound.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjpeg.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsdt.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pcsc.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmanagement.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libunpack.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjaas_unix.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libhprof.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_xawt.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsig.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2gss.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsunec.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libtinyiconv.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pkcs11.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libdt_socket.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjdwp.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libzip.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsctp.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmlib_image.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/liblcms.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjawt.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  (17035): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  (17035): dlopen /data/app/net.kdt.pojavlaunch-bfsxURNQ2waqCNum50uznQ==/lib/arm/libopenal.so success
I/jrelog  (17035): Done processing args
I/jrelog  (17035): Found JLI lib
I/jrelog  (17035): Calling JLI_Launch
Error occurred during initialization of VM
Could not reserve enough space for 1126400KB object heap
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xa7373210)
process killed with signal 6 code 0xffffffff addr 0x428b
--------- beginning of crash

**Comment by SprainedSpark89** [comment]
how much memory

**Comment by SprainedSpark89** [comment]
don't use vbo and use playstore

**Comment by Charles7770** [comment]
![Screenshot_20220204-172439.png](https://user-images.githubusercontent.com/94718463/152616304-cf96540e-c111-47dc-9d8f-1cd856b1e73a.png)

**Comment by Charles7770** [comment]
![Screenshot_20220204-172358.png](https://user-images.githubusercontent.com/94718463/152616325-d00e7cae-7e43-4364-baf9-8c4a4b2c309d.png)

**Comment by Charles7770** [comment]
start version 1.7 and when you start it closes the app with that message

**Comment by khanhduytran0** [comment]
> Could not reserve enough space for 1126400KB object heap

Too much memory. 32bit doesn’t allow setting much.

**Comment by Charles7770** [comment]
¿Should I lower the level of memory it uses?

**Comment by khanhduytran0** [comment]
Try lowering to 512mb.

**Comment by Charles7770** [comment]
I already tried it, the same thing comes out

**Comment by Charles7770** [comment]
![Screenshot_20220204-174154.png](https://user-images.githubusercontent.com/94718463/152617585-d536b624-a336-48cc-90d7-dac32453c081.png)

**Comment by SprainedSpark89** [comment]
set it as low as it goes then every time it works turn up the memory a little

**Comment by Charles7770** [comment]
I did it, it worked for me up to 256mb and I'm going to upload it to see how far it works for me

**Comment by Charles7770** [comment]
hello now there is this forge of 1.12.2 I don't know what happens if I can do something could you notify me thanks

**Comment by Charles7770** [comment]
![Screenshot_20220205-024827.png](https://user-images.githubusercontent.com/94718463/152635176-b4290db2-40c1-4777-bc57-c7cf8139b042.png)

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
