### ISSUE TITLE
Optifine 1.11.2 not working

### ISSUE THREAD

**Issue by MacOS-9** [PojavLauncherTeam/PojavLauncher#258]
hi guys i did everything in the optifine tutorial and it crashes :( anyone help?

**Comment by khanhduytran0** [comment]
Note that *not all devices* can run OptiFine.

**Comment by MacOS-9** [comment]
yes i know but give me a sec

**Comment by MacOS-9** [comment]
my phone has 3,7 GB ram is it enough?

**Comment by khanhduytran0** [comment]
Yes

**Comment by khanhduytran0** [comment]
But it give you 512mb heap only ...

**Comment by MacOS-9** [comment]
you mean minecraft uses only 512 mb?

**Comment by MacOS-9** [comment]
i tried changing a setting and it just made it crash instantly (it crashed after a few seconds before)

**Comment by WesleyVanNeck** [comment]
@MacOS-9 whats your android version

**Comment by khanhduytran0** [comment]
Try on v3...
