### ISSUE TITLE
[Forge 1.18.1] Crashes when launched

### ISSUE THREAD

**Issue by SerialCookie** [PojavLauncherTeam/PojavLauncher#2581]
### Describe the bug

When I start the game, a Windows pops up : "Application exited with code 1". I then inspected the latestlog.txt and noticed an error (this may not be the actual one, but I think it is) : java.lang.module.FindException: Module cpw.mods.securejarhandler not found

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.1-forge-39.0.36 (1.18.1)
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2294
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~eyiTqxDkwW_fw2cHh_96Qg==/net.kdt.pojavlaunch-2AA3Thue_7Qhfo9BC0i24g==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3
Added custom env: LIBGL_ES=3
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Aug 18 2021 16:47:47
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_draw_buffers is in core ES3, and so used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Max Color Attachments: 8 / Draw buffers: 8
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
Targeting OpenGL 2.1
NPOT texture handled in hardware
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
--------- beginning of system
I/jrelog  ( 7505): dlopen libgl4es_115.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjli.so success
I/jrelog  ( 7505): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/server/libjvm.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libverify.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjava.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libnet.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libnio.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libawt.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libawt_headless.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libfreetype.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libfontmanager.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libawt.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/server/libjvm.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/server/libjsig.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libattach.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjavajpeg.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libsyslookup.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libfontmanager.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libj2pcsc.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libmanagement.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjaas.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libfreetype.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjli.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjimage.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjsig.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libj2gss.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libnet.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjava.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libnio.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libprefs.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libmanagement_ext.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libj2pkcs11.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libdt_socket.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjdwp.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libzip.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libsctp.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libmlib_image.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libextnet.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libinstrument.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libmanagement_agent.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/librmi.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/liblcms.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libjawt.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libverify.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libawt_headless.so success
I/jrelog  ( 7505): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(1).xz/lib/libawt_xawt.so success
I/jrelog  ( 7505): dlopen /data/app/~~eyiTqxDkwW_fw2cHh_96Qg==/net.kdt.pojavlaunch-2AA3Thue_7Qhfo9BC0i24g==/lib/arm64/libopenal.so success
I/jrelog  ( 7505): Done processing args
I/jrelog  ( 7505): Found JLI lib
I/jrelog  ( 7505): Calling JLI_Launch
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.
--------- beginning of main
Exception in thread "main" 
java.lang.module.FindException: Module cpw.mods.securejarhandler not found, required by cpw.mods.bootstraplauncher
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:492)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:83)
Java Exit code: 1
I/jrelog  ( 7505): Going to free args
I/jrelog  ( 7505): Free done
--------- beginning of system

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start Minecraft 1.18.1
3. Install Forge 1.18.1
4. Start Forge 1.18.1
5. It crashes
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: Oppo Reno 4 Pro 5G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest on PlayStore
```

**Comment by Kaan1O1** [comment]
bc you cant use forge on new versions now

**Comment by 23msowee** [comment]
> bc you cant use forge on new versions now

Why not??

**Comment by GoneSubject** [comment]
forge 1.17+ is not supported yet

**Comment by khanhduytran0** [comment]
> > bc you cant use forge on new versions now
> 
> Why not??

Due to Java changes.

> java.lang.module.FindException: Module cpw.mods.securejarhandler not found, required by cpw.mods.bootstraplauncher

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.
