### ISSUE TITLE
forge1.12.2装上[动态环境]DynamicSurroundings会出现材质错误

### ISSUE THREAD

**Issue by mcxyx** [PojavLauncherTeam/PojavLauncher#2582]
![Screenshot_2022_0119_145220](https://user-images.githubusercontent.com/98008362/150079229-716852ca-f3fe-49c3-bc24-0230a4be3dd6.png)
### Describe the bug

![Screenshot_2022_0119_142418](https://user-images.githubusercontent.com/98008362/150076473-74012b80-4938-4319-82af-c5e7f1dc014e.png)
离水近就出现，前置也装了，用vgpu渲染器玩，还有除了zink其他的渲染器都会这样

### The log file and images/videos

12333

### Steps To Reproduce

```markdown
遇到水会产生材质错误。代码不知道是什么
```

### Expected Behavior

我希望能够修复

### Platform

```markdown
- Device model: vivo y5s
- CPU architecture: 联发科Helio P65
- Android version: Android9.0
- PojavLauncher version: 
crocus-v3_openjdk



### Anything else?

vgpu渲染器，出现闪退问题！ 

- [ ]

**Comment by TWTommyee** [comment]
已知問題

**Comment by kedrick021** [comment]
Use Virglrender

**Comment by Mathias-Boulay** [comment]
#1948
