### ISSUE TITLE
Someone know how can i use Optifabric or Sodium for 1.17.1 fabric

### ISSUE THREAD

**Issue by Kaan1O1** [PojavLauncherTeam/PojavLauncher#2583]

**Comment by ghost** [comment]
the same question when will support for sodium appear on 1 17 1
or at least optifine

**Comment by GoneSubject** [comment]
> the same question when will support for sodium appear on 1 17 1
> or at least optifine

optifine 1.17+ is fully supprted idk about the sodium just know you must download something i think

**Comment by Fl414r** [comment]
You can use Virglrenderer but only in multiplayer. In singleplayer screen mirrored ather 1-5mins.
P.S. You can also run 1.18.1 this way if the light does not work on other renders. Moreover (for me, maybe it will be different for you) on this version the screen is not mirrored

**Comment by 23msowee** [comment]
I successfully run 1.18.1 fabric w/ sodium.. but when i load up the save file or create a new one it flips everything up.. i mean it became inverted..  upside down FOV, spelling are inverted (e.g. Advancement turn into tnemecnavdA) ... it's kinda bug tho...

**Comment by Fl414r** [comment]
> I successfully run 1.18.1 fabric w/ sodium.. but when i load up the save file or create a new one it flips everything up.. i mean it became inverted.. upside down FOV, spelling are inverted (e.g. Advancement turn into tnemecnavdA) ... it's kinda bug tho...

hmm try this version
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1597512067

**Comment by Mathias-Boulay** [comment]
optifabric runs now, sodium requires a version of openGL too high I believe
