### ISSUE TITLE
[BUG] Any Action build apk to Play Rlcraft modpack?

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2584]
### Is this request related to a bug?

.

### Describe the request.

.

### Anything else?

.

**Comment by khanhduytran0** [comment]
Not a Pojav issue.
> #1948
> Getting every mod to work is a huge job, and we don’t have much time for it.

**Comment by khanhduytran0** [comment]
~~Please join our Discord server instead of asking random stuff in this **issue** tracker.~~
