### ISSUE TITLE
Xbox controller settings !

### ISSUE THREAD

**Issue by NotEvent98** [PojavLauncherTeam/PojavLauncher#2585]
### Is this request related to a bug?

Hi .. so i am using Xbox controller  
About the sittings i thought i will change attack button to (LB) but it's not working its never Change ..  
I thought maybe its a button in keyboard in pojavlaunch , And i never Found it .. 
I hope if you can do something about it so i can play even better xd 
And thanks sry for bothering u.

### Describe the request.

Its like if I pressed button (X) change to the something i want in sitting

### Anything else?

I hope you can help

**Comment by SprainedSpark89** [comment]
hey go to setting in minecraft and then go to control then see what the controls on the controller is mapped to

**Comment by felixlechatchat** [comment]
me, my LB RB button doesn't work

**Comment by SprainedSpark89** [comment]
oh yah hey maybe there is a new build or update that will fix this bug

**Comment by GaucovyAero** [comment]
**This issue has been resolved.**

Make sure to update your launcher. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`
