### ISSUE TITLE
[BUG] keeps on crashing when trying to install forge 1.8.9

### ISSUE THREAD

**Issue by StormyRiley1** [PojavLauncherTeam/PojavLauncher#2586]
### Describe the bug

Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=1555x720, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/forge-1.8.9-11.15.1.2318-1.8.9-universal.jar] Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache Added custom env: AWTSTUB_WIDTH=1555 Added custom env: REGAL_GL_VERSION=4.5 Added custom env: REGAL_GL_VENDOR=Android Added custom env: LIBGL_MIPMAP=3 Added custom env: allow_higher_compat_version=true Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin Added custom env: force_glsl_extensions_warn=true Added custom env: LIBGL_NORMALIZE=1 Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~fgNic97meYz1y-DTLyNGbQ==/net.kdt.pojavlaunch-WAZW3Sv4bftj2oaACngoyA==/lib/arm64 Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink Added custom env: MESA_GLSL_VERSION_OVERRIDE=460 Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal Added custom env: MESA_GL_VERSION_OVERRIDE=4.6 Added custom env: allow_glsl_extension_directive_midshader=true Added custom env: REGAL_GL_RENDERER=Regal Added custom env: AWTSTUB_HEIGHT=720 OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes --------- beginning of main I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success I/jrelog ( 3390): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success I/jrelog ( 3390): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success I/jrelog ( 3390): dlopen /data/app/~~fgNic97meYz1y-DTLyNGbQ==/net.kdt.pojavlaunch-WAZW3Sv4bftj2oaACngoyA==/lib/arm64/libopenal.so success I/jrelog ( 3390): Done processing args I/jrelog ( 3390): Found JLI lib I/jrelog ( 3390): Calling JLI_Launch Policy policy.url.2=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy (No such file or directory) Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/* We appear to be missing one or more essential library files. You will need to add them to your server before FML and Forge will run successfully. java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:25) 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7f9053db18) process killed with signal 6 code 0xffffffff addr 0x282a00000d3e --------- beginning of crash FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7f8f33a1c8) process killed with signal 6 code 0xffffffff addr 0x282a00000d3e FORTIFY: pthread_mutex_trylock called on a destroyed mutex (0x2004fb150) process killed with signal 6 code 0xffffffff addr 0x282a00000d3e

### The log file and images/videos

The log file called latestlog.txt is located under Android/data/net.kdt.pojavlaunch/files, games/PojavLauncher/

### Steps To Reproduce

```markdown
1. Start pojav
2. Login
3. Click options 
4. Launch mod installer 
5. Choose forge 1.8.9 file
6. Crashes
```

### Expected Behavior

I expect it to install and run

### Platform

```markdown
- Device model: Samsung a12
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest version on play store
```

**Comment by khanhduytran0** [comment]
> forge-1.8.9-11.15.1.2318-1.8.9-universal.jar

Look at what you ran. It’s universal and not installer.

**Comment by khanhduytran0** [comment]
Pojav expects installer to be selected, but you didn’t think about it :eyes:, as you didn’t try running the installer before submitting this bug report.

**Comment by forestthe29** [comment]
I get a problem when I try to enter or create a world in minecraft 1.18 with optifine I don't know what it is but the pojav launcher crashes my device is a chromebook it has android 9 and it's AMD
