### ISSUE TITLE
Mouse not working

### ISSUE THREAD

**Issue by shadowee0002** [PojavLauncherTeam/PojavLauncher#2587]
### Describe the bug

![Screenshot_2022_0120_093111](https://user-images.githubusercontent.com/97771883/150271064-862b8d47-4e05-40ae-8194-a4212231de72.jpg)
Pojav devs
I have an error mean my mouse or touch not working on 1.14.4 it is sometime mean when i open 1.14.4 sometime mouse work but sometime not 
Can you tell me how to fix this 

### The log file and images/videos

![Uploading Screenshot_2022_0120_093111.jpg…]()

### Steps To Reproduce

```markdown
Please fix this bug
```

### Expected Behavior

It not occured every time but sometime 
Then i need to restart 

### Platform

```markdown
- Device model: vivo y71
- CPU architecture:aarch 64 
- Android version: 8
- PojavLauncher version [Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by ajit56** [comment]
Restart Minecraft bug will solve.I have also this problem but i restart Minecraft

**Comment by shadowee0002** [comment]
I found temporary solution ,we need to click mouse on off when game start and then don't click screen until game open

**Comment by notstackgb** [comment]
Control spin?

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.
