### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by SevenIsNotNumber** [PojavLauncherTeam/PojavLauncher#259]
Is it possible to Run minecraft on secondary OS(Like VMOS but based on windows and/or linux)? If yes, will it make performance better on "some" device???And Give me a "test" apk? +Im jealous on mcinabox/boat users because mcinabox/boat worked them + They can install forge and mods in 1.12-1.12.2.. It would be nice if we can play mods for 1.12-1.12.2 on pojav launcher v2... In boat , mod installation is easy ,
Just put the {mod name}.jar in boat/gamedir/mods.. Make it work on pojav plssss

**Comment by SevenIsNotNumber** [comment]
Not added custom controls on mcinabox

**Comment by khanhduytran0** [comment]
>  Run minecraft on secondary OS(Like VMOS but based on windows and/or linux)?
- ????

> MCinabox or Boat
- They use OpenJDK runtime so easy to add mod support, I may try port Forge to PojavLauncher later.
