### ISSUE TITLE
bear bug

### ISSUE THREAD

**Issue by behdydhs** [PojavLauncherTeam/PojavLauncher#2591]
### Describe the bug

Hello Dear Administration, can you help me, the bear doesn’t work for me, well, how it doesn’t work, the screen trembles when I drive the bear, you can somehow bring it please, I want to shoot on YouTube and it doesn’t work

### The log file and images/videos

Hello Dear Administration, can you help me, the bear doesn’t work for me, well, how it doesn’t work, the screen trembles when I drive the bear, you can somehow bring it please, I want to shoot on YouTube and it doesn’t work

### Steps To Reproduce

```markdown
Hello Dear Administration, can you help me, the bear doesn’t work for me, well, how it doesn’t work, the screen trembles when I drive the bear, you can somehow bring it please, I want to shoot on YouTube and it doesn’t work
```

### Expected Behavior

Hello Dear Administration, can you help me, the bear doesn’t work for me, well, how it doesn’t work, the screen trembles when I drive the bear, you can somehow bring it please, I want to shoot on YouTube and it doesn’t work

### Platform

```markdown
- Device model: Xiaomi poco x3 pro
- CPU architecture:the same: one maximum performance Kryo 485 Gold core with a frequency of 2.96 GHz, three Kryo 485 Gold cores with a frequency of 2.42 GHz and four energy-efficient Kryo 485 Silver cores with a frequency of 1.78 GHz;  graphics subsystem Adreno 640;  manufacturing process - 7 nm;  5G modem is optional
- Android version:12
- PojavLauncher version:last
```

### Anything else?

Hello Dear Administration, can you help me, the bear doesn’t work for me, well, how it doesn’t work, the screen trembles when I drive the bear, you can somehow bring it please, I want to shoot on YouTube and it doesn’t work

**Comment by khanhduytran0** [comment]
Invalid.
