### ISSUE TITLE
[BUG] Attempt to install 32bit Java on 64bit device

### ISSUE THREAD

**Issue by Whydoesthishappen** [PojavLauncherTeam/PojavLauncher#2593]
### Describe the bug

Java runtime incompatible

### The log file and images/videos

`
 java.lang.RuntimeException: La arquitectura arm64 es incompatible con Java Runtime arm. at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43) at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725) at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36) at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552) at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2) at java.lang.Thread.run(Thread.java:923)
 `

### Steps To Reproduce

```markdown
1 play 2 error 3 retry 4 error
```

### Expected Behavior

I expected it to launch

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No

**Comment by WesleyVanNeck** [comment]
Fill the tamplate

**Comment by Errorbot1122** [comment]
First of all, FILL IN THE TEMPLET BRO

Second of all, What version are you playing on. Is it 1.18 or 1.17?

Both versions need JRE 17 which you can download [here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559) (Download `arm64` version for your device)

After that follow these [instructions](https://pojavlauncherteam.github.io/updates/117.html#known-issues) (Be sure to ignore the ~~strikethroughs~~!)

**Comment by Errorbot1122** [comment]
Also @Whydoesthishappen, PLEASE add a SHORT DESCRIPTION in the title, and put your error in the "**The log file and images/videos**" section.

**Comment by khanhduytran0** [comment]
> La arquitectura arm64 es incompatible con Java Runtime arm

I think you didn’t even read this @Whydoesthishappen. Translate:
> Architecture arm64 <- device architecture is ARM, with 64bit.
> is incompatible with
> Java Runtime arm <- ARM but without 64, so it’s 32bit.

**Comment by Errorbot1122** [comment]
Oh, that means you probably have a 64-bit OS. You need to download JRE 17 [here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz)
