### ISSUE TITLE
[BUG] I Cant install a different instance with Fabric Installer (Chromebook???)

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2594]
### Describe the bug

Every time try to install a second instance of fabric installer, it either exits or just does not work at all...

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7906331/latestlog.txt)

https://user-images.githubusercontent.com/65428515/150410213-f3d39c22-5ebb-42e6-9631-544baf73604a.mp4

### Steps To Reproduce

```markdown
1. Download Fabric Launcher 10.12
2. Open ProjavLauncher and Sign-In
3. Click options
4. Click the top-most option
5. Chose the newly installed fabric lancher
6. Install 1.18 like normal
7. Now do steps 2 - 6 again
8. It will crash...
```

### Expected Behavior

I expected it to open the window for the fabric installer so I can get a 1.17 instance of fabric.

### Platform

```markdown
- Device model: R96-14268.67.0
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I try using fabric 1.18 but it give me `render overlay` error. (the error you see in the background) I learned that this happens because Mojang changed the pack version to 8 and broke the `assets-v0` pack as [seen on the website](https://pojavlauncherteam.github.io/updates/117.html#platform-specific-instruction) but I can't download the pack because discord is blocked on this computer. (don't ask why...) After that, I gave in and tried to download fabric 1.17. Keyword **TRIED,** because every time I tried to install it, it crashes.

After reviewing the footage, it seems that its reviewing words are: **`I/jrelog ( 4226): Calling JLI Lauch`** but I don't know java, so IDK what this means...

**ALSO** on big thing is that I'm on a ***Chromebook...***

**Comment by khanhduytran0** [comment]
Looks like you forgot to switch back to Java 8 before installing.
Also, why did you set Java 17 as default? It’s unnecessary, as **PVC is doing its job**.

**Comment by Errorbot1122** [comment]
OH, thnx :)
