### ISSUE TITLE
[BUG] <Fabric 0.12.12, mc 1.18.1 not working>

### ISSUE THREAD

**Issue by lostallmymoney** [PojavLauncherTeam/PojavLauncher#2595]
### Describe the bug

After applying the patch it seems like fabric alone without any mods is not working. 

### The log file and images/videos

https://pastebin.com/W8gqgf2R

### Steps To Reproduce

```markdown
Install patch 117.jar, vanilla works,
install fabric 0.12.12, game doesn't work.
```

### Expected Behavior

Fabric works

### Platform

```markdown
- Device model: S21
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: 31 august 2021
```

**Comment by Errorbot1122** [comment]
Oh, looks like you are having the same problem as me.

Go to there's [instructions](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04) (Make sure you follow the instructions for **Minecraft 21w37a+** as that is for 1.18+)

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
else #1948
