### ISSUE TITLE
[BUG] argument -Xbootclasspath/p is no longer supported (when installing mods)

### ISSUE THREAD

**Issue by Brickalist** [PojavLauncherTeam/PojavLauncher#2596]
### Describe the bug

When trying to install optifine using the install option in options, the installation crashes with exit code 1.

### The log file and images/videos

Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=2204x1080, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/OptiFine_1.18_HD_U_H3.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2204
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~UuJo0TGGn3xWDfItxec2Jw==/net.kdt.pojavlaunch-rSLOyPESVM8dTXKRs2vIpg==/lib/arm64
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 9206): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  ( 9206): dlopen /data/app/~~UuJo0TGGn3xWDfItxec2Jw==/net.kdt.pojavlaunch-rSLOyPESVM8dTXKRs2vIpg==/lib/arm64/libopenal.so success
I/jrelog  ( 9206): Done processing args
I/jrelog  ( 9206): Found JLI lib
I/jrelog  ( 9206): Calling JLI_Launch
-Xbootclasspath/p is no longer a supported option.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7464f3bd60)
process killed with signal 6 code 0xffffffff addr 0x272c000023f6
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7464f3bcf8)
process killed with signal 6 code 0xffffffff addr 0x272c000023f6 

### Steps To Reproduce

```markdown
No fresh pojav install: what I did before:
1. Follow steps to get pojav to work on 1.18: (new texture pack and installed jre17)
2. Confirmed game is working without mods.


To reproduce error:
1. Start pojavlauncher
2. Options->install a mod(first option without custom arguments)
3. Select Optifine_1.18_HD_U_H3.jar
4. Installation crashes almost immediately. The Java vm
```

### Expected Behavior

I expect the installation to succeed

### Platform

```markdown
- Device model: Pixel 4a 
- CPU architecture: Arm64
- Android version: 12
- PojavLauncher version: latest gPlay (31 August)
```

**Comment by Brickalist** [comment]
So I just found out error is purely related to jre17 since they removed the Xbootclasspath/p option in that version. If i go to settings->Runtime Manager->internal(java8), the installation succeeds (but we cannot play that since it needs to be installed with jre17 in order to work on jre17?)

The xbootclasspath is given to the JVM at initialization, so we as users cannot modify that argument.

**Comment by Brickalist** [comment]
After scrolling through the code, I found that the classpath argument is added here:

from [launchJavaRuntime()](https://github.com/PojavLauncherTeam/PojavLauncher/blob/658c937d73a50ff7b7292832d4573fc7b7a72437/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/JavaGUILauncherActivity.java#L278) to [Tools.getCacioJavaArgs()](https://github.com/PojavLauncherTeam/PojavLauncher/blob/658c937d73a50ff7b7292832d4573fc7b7a72437/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/JavaGUILauncherActivity.java#L292) in [this](https://github.com/PojavLauncherTeam/PojavLauncher/blob/658c937d73a50ff7b7292832d4573fc7b7a72437/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/Tools.java#L178) line.

I am not any more familiar with this, so I do not know if the /p is totally neccesarry. maybe replacing it with /a is a solution?

/a means append to the path instead of prepend to the path. The /a option appears to still exist in jre17

**Comment by khanhduytran0** [comment]
> After scrolling through the code, I found that the classpath argument is added here:
> 
> from [launchJavaRuntime()](https://github.com/PojavLauncherTeam/PojavLauncher/blob/658c937d73a50ff7b7292832d4573fc7b7a72437/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/JavaGUILauncherActivity.java#L278) to [Tools.getCacioJavaArgs()](https://github.com/PojavLauncherTeam/PojavLauncher/blob/658c937d73a50ff7b7292832d4573fc7b7a72437/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/JavaGUILauncherActivity.java#L292) in [this](https://github.com/PojavLauncherTeam/PojavLauncher/blob/658c937d73a50ff7b7292832d4573fc7b7a72437/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/Tools.java#L178) line.
> 
> I am not any more familiar with this, so I do not know if the /p is totally neccesarry. maybe replacing it with /a is a solution?
> 
> /a means append to the path instead of prepend to the path. The /a option appears to still exist in jre17

Actually, launching mod installer is only intended for Java 8, since [Caciocavallo](https://openjdk.java.net/projects/caciocavallo) is no longer updated so we are aware of breaking changes when running with Java 17 (such as private classes access or API breaking changes).

**Comment by Brickalist** [comment]
Right, so there are no plans as of yet to have this work on jre17?

I'd not, are there perhaps any other ways in which it is possible to install mods for 1.18?

**Comment by khanhduytran0** [comment]
> Right, so there are no plans as of yet to have this work on jre17?
> 
> I'd not, are there perhaps any other ways in which it is possible to install mods for 1.18?

Did you just think that any installer targets 1.17+ requires Java16/17? Nah, just use java 8.

**Comment by Brickalist** [comment]
That is one of the first things I did, but that did not work for me: Installed with Java 8:

1 choose internal Java 8 vm as default
2 install optifine1.18.1
3 install the patch to make it work in 1.17+
4 switch back to Arm64 jre17.
5 message: architecture Arm64 is not compatible with architecture Arm. When launching the optifine profile.

I am 100% sure that Arm64 is correct, because I can play non-modded versions fine.

**Comment by khanhduytran0** [comment]
> I am 100% sure that Arm64 is correct, because I can play non-modded versions fine.

What’s inside the runtime manager?

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
