### ISSUE TITLE
[BUG] i can't play

### ISSUE THREAD

**Issue by moha0116** [PojavLauncherTeam/PojavLauncher#2597]
### Describe the bug

Pojavlauncher restart after loading world on 1.7.10-1.12.2 forge and another problems:
Game can't launching on forge 1.13+

### The log file and images/videos

I have a problem of connexion i can't share a video
And log file does not record

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Choose 1.12.2 forge
3. Create world
4. Pojavlauncher restart after loading world
```

### Expected Behavior

Pojavlauncher restart after loading world

### Platform

```markdown
- Device model: Samsung galaxy a12
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Lasted Release
```

### Anything else?

Thas is my problem

**Comment by ajit56** [comment]
Send a log or say goodbye

**Comment by SprainedSpark89** [comment]
try not using forge or install optifine with forge

**Comment by flexVDIDesktop** [comment]
When I try to open PojavLauncher,
The app crashes. It happens on my Fire Tablet, so I use the phone and it does not crash on the phone, on Fire.. It did work now and not now. BUGS!!!

**Comment by ghost** [comment]
Please send the latestlog.txt to help debug.

**Comment by NotAHero04** [comment]
> When I try to open PojavLauncher, The app crashes. It happens on my Fire Tablet, so I use the phone and it does not crash on the phone, on Fire.. It did work now and not now. BUGS!!!

You'd better make a new issue and provide enough informations there.

**Comment by SprainedSpark89** [comment]
try the playstore version if you have installed playstore on kindle

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.
