### ISSUE TITLE
[BUG] <Too small pls help>

### ISSUE THREAD

**Issue by Tony1711** [PojavLauncherTeam/PojavLauncher#2598]
### Describe the bug

Its too small

### The log file and images/videos

![Screenshot_20220122_084423](https://user-images.githubusercontent.com/98197173/150620168-da3d91be-44f8-46d5-9268-cf3e7e84a1c2.png)

### Steps To Reproduce

```markdown
I just pressing tab button and it become like that
Already try uninstall and reinstall
```

### Expected Behavior

Its supposed to be mobile size

### Platform

```markdown
- Device model: Vinsmart Joy3
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version:[Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by NotAHero04** [comment]
Change: Setting -> Video Setting... -> GUI Scale option.
(Unless you are playing with a specific resolution that locks the scale at 1)
