### ISSUE TITLE
Join to server (mode) & install labymod/optifine

### ISSUE THREAD

**Issue by MaksymilianOr-9928** [PojavLauncherTeam/PojavLauncher#26]
hello, please help me with install labymod/optifine.
And the next question is:
How to select a server (mode)?
![Screenshot_20200331_054658](https://user-images.githubusercontent.com/59124900/77985260-42793000-7314-11ea-85ad-4151d8c3c308.jpg)
Thanks!

**Comment by khanhduytran0** [comment]
**Install OptiFine:** https://youtu.be/73Gzo2tZBW0
**Install LabyMod** ~~(it's complicated to implement)~~ going some test

**If you are getting problem on pick item/craft/server mode/...** goto Settings -> Controls -> Touchscreen **toggle to off**

Then double/triple click to item/server mode.

**Comment by MaksymilianOr-9928** [comment]
Ok, thanks.
But I have a new problem with this
![Screenshot_20200331_064303_net kdt pojavlaunch](https://user-images.githubusercontent.com/59124900/77987791-0c8b7a00-731b-11ea-9a10-a80d6e3af382.jpg) (I have a Minecraft premium )

**Comment by khanhduytran0** [comment]
Knew it, going to fix.

**Comment by MaksymilianOr-9928** [comment]
Hello, I have a problem with join to the server (nonpremium account) because when I try connecting server kick me 
![Screenshot_20200401_022755](https://user-images.githubusercontent.com/59124900/78087274-d6a0d100-73c0-11ea-9857-b94d068e33fc.jpg)
With information "wrong ip server adress, join with using..." The server owner has a 2 servers, I trying connect to number one, but server please me to join to server number two. On pc it work normal.

**Comment by khanhduytran0** [comment]
Check if:
- Are you using right version to connect?
- Are you getting the latest preview?
- Are you connecting to a premium server?

**Comment by MaksymilianOr-9928** [comment]
> Check if:
> 
> * Are you using right version to connect?
Yes
> * Are you getting the latest preview?
Yes
> * Are you connecting to a premium server?
No

**Comment by khanhduytran0** [comment]
Have you tried with preview8b1?

**Comment by MaksymilianOr-9928** [comment]
Yes

**Comment by khanhduytran0** [comment]
So what happend when you join second server?

**Comment by MaksymilianOr-9928** [comment]
> So what happend when you join second server?

Normal, when join to another server (not same)

**Comment by khanhduytran0** [comment]
I thought because Android has different API structure with standard Java so little things will be different. Java URL API also different with Android URL API.
For example:
In PC, with `play.invadedlands.net` you can ping and connect with premium account.
But in Android there is something like: Unable to resolve host.


 Or in Boardwalk code has some fix RSA padding.

**Comment by MaksymilianOr-9928** [comment]
True, but how to fix it?

**Comment by khanhduytran0** [comment]
You can go back to preview8b1 (but you will lost accounts because they are stored in private data)

**Comment by MaksymilianOr-9928** [comment]
I back, but it still this is

**Comment by MaksymilianOr-9928** [comment]
On premium it work but, I can't connect because premium join not working (server have a premium verification and support premium and nonpremium)

**Comment by MaksymilianOr-9928** [comment]
When I have my own server I saw in permissionsex uuid (nonpremium have too!)

**Comment by khanhduytran0** [comment]
**premium** account mode has been broken in this launcher but works fine in Boardwalk.

**Comment by MaksymilianOr-9928** [comment]
why has broken?

**Comment by khanhduytran0** [comment]
Because fix RSA padding is not available since Android 7.0

**Comment by MaksymilianOr-9928** [comment]
Have you a discord server?

**Comment by khanhduytran0** [comment]
No

**Comment by MaksymilianOr-9928** [comment]
> **premium** account mode has been broken in this launcher but works fine in Boardwalk.

But boardwalk not working on my device 
![Screenshot_20200402_015818](https://user-images.githubusercontent.com/59124900/78197434-a0795500-7485-11ea-913e-58757fbcc016.jpg)
Boardwalk faq: 
![Screenshot_20200402_030342](https://user-images.githubusercontent.com/59124900/78200394-d53dda00-748e-11ea-8b7c-b45910622088.jpg)

**Comment by khanhduytran0** [comment]
Know it, try boardwalk 2.

**Comment by khanhduytran0** [comment]
If not working try my modified Boardwalk 2 https://drive.google.com/file/d/12Ro2CwGc-OODJKYah9aUzf8D4aw_zVNQ/view?usp=drivesdk

**Comment by khanhduytran0** [comment]
Also you can run 1.13 or above in Boardwalk 2, my modified version has a chance to success.

UPD: The modified replace glshim by gl4es

**Comment by MaksymilianOr-9928** [comment]
![Screenshot_20200402_152325](https://user-images.githubusercontent.com/59124900/78254338-0dc4ce80-74f6-11ea-8357-1df4c4793c98.jpg)
😬

**Comment by khanhduytran0** [comment]
# WHAT THE TRYING PREVIEW9b5 HAS Went to release but going to be unknown.

**Comment by khanhduytran0** [comment]
Download 1.12.2 json manually

**Comment by MaksymilianOr-9928** [comment]
> Download 1.12.2 json manually

How to convent .jar to .JSON (I downloaded 1.12.2.jar - for playing)

**Comment by khanhduytran0** [comment]
https://launchermeta.mojang.com/v1/packages/6e69e85d0f85f4f4b9e12dd99d102092a6e15918/1.12.2.json
Put this json as error say

**Comment by khanhduytran0** [comment]
.json store info about libraries, version, argument, so you can't going to convert jar to json

**Comment by MaksymilianOr-9928** [comment]
![Screenshot_20200402_154721](https://user-images.githubusercontent.com/59124900/78256783-4a45f980-74f9-11ea-8a01-9cc7a6dc6b2c.jpg)
😬😬

**Comment by artdeell** [comment]
Try to allow storage manually in settings.

**Comment by MaksymilianOr-9928** [comment]
> Spróbuj ręcznie zezwolić na przechowywanie w ustawieniach.
But i done it

**Comment by MaksymilianOr-9928** [comment]
Please add this 
![Screenshot_20200403_010448](https://user-images.githubusercontent.com/59124900/78413206-ae121480-7616-11ea-9a4b-12a3f7df68ed.jpg)

**Comment by khanhduytran0** [comment]
Joystick?

**Comment by MaksymilianOr-9928** [comment]
> Joystick?

Yes!!!

**Comment by Azapru** [comment]
> Joystick?

Please no.....

**Comment by MaksymilianOr-9928** [comment]
> > Joystick?
> 
> Please no.....

Why?

**Comment by artdeell** [comment]
Joystick for the game when motion is only digital...
Sounds like a bad idea. Even Mojang and Microsoft understand this.

**Comment by MaksymilianOr-9928** [comment]
> Joystick for the game when motion is only digital...
> Sounds like a bad idea. Even Mojang and Microsoft understand this.

But mojang and Microsoft made a good system.

**Comment by khanhduytran0** [comment]
Try v3 for mods
