### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DarkLord063** [PojavLauncherTeam/PojavLauncher#260]
Hi, I thought that this update fixed crashing when joining servers/cracked servers

This is the crash log

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2020/08/02 2:04 AM
Description: Rendering entity in world

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at cvw.a(SourceFile:124)
	at cnw.a(SourceFile:76)
	at csh.a(SourceFile:86)
	at cqv.a(SourceFile:411)
	at cqv.a(SourceFile:170)
	at cqv.a(SourceFile:30)
	at cpt.a(SourceFile:294)
	at cpt.a(SourceFile:259)
	at cpt.a(SourceFile:226)
	at ckn.a(SourceFile:583)
	at cji.a(SourceFile:1225)
	at cji.a(SourceFile:1130)
	at cji.b(SourceFile:983)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1015)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:780)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at cvx.a(SourceFile:47)
	at cvx.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at cvw.a(SourceFile:124)
	at cnw.a(SourceFile:76)
	at csh.a(SourceFile:86)
	at cqv.a(SourceFile:411)
	at cqv.a(SourceFile:170)

-- Entity being rendered --
Details:
	Entity Type: ArmorStand (adi)
	Entity ID: 171
	Entity Name: Armor Stand
	Entity's Exact location: -79,50, 64,94, -124,50
	Entity's Block location: -80,00,64,00,-125,00 - World: (-80,64,-125), Chunk: (at 0,4,3 in -5,-8; contains blocks -80,0,-128 to -65,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'java.lang.String wv.toString()' on a null object reference
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'java.lang.String wv.toString()' on a null object reference
Stacktrace:
	at b.a(SourceFile:244)
	at cpt.a(SourceFile:319)
	at cpt.a(SourceFile:259)
	at cpt.a(SourceFile:226)
	at ckn.a(SourceFile:583)
	at cji.a(SourceFile:1225)
	at cji.a(SourceFile:1130)
	at cji.b(SourceFile:983)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1015)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:780)

-- Renderer details --
Details:
	Assigned renderer: cpe@a32f52c
	Location: -38,95,-4,06,-40,69 - World: (-39,-5,-41), Chunk: (at 9,-1,7 in -3,-3; contains blocks -48,0,-48 to -33,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -180.0
	Delta: 0.94194627

-- Affected level --
Details:
	Level name: MpServer
	All players: 32 total; [cio['DarkLord063'/780120, l='MpServer', x=-40,55, y=69,00, z=-83,81], cip['§a§lTownyEarth'/780009, l='MpServer', x=-48,34, y=65,02, z=-121,47], cip['§6§lMeggiKari'/569626, l='MpServer', x=-53,50, y=65,02, z=-96,53], cip['AstralNocturne'/569614, l='MpServer', x=-63,63, y=66,52, z=-55,53], cip['Sakoi3'/569751, l='MpServer', x=-60,22, y=66,02, z=-51,50], cip['Russsy'/569623, l='MpServer', x=-60,47, y=66,02, z=-61,66], cip['Obl1v1os'/569599, l='MpServer', x=-63,66, y=66,52, z=-57,38], cip['NampaiKid007'/569617, l='MpServer', x=-59,41, y=66,02, z=-42,53], cip['Destial'/569587, l='MpServer', x=-59,41, y=-67108863,98, z=-37,13], cip['ConfidentTepos'/569602, l='MpServer', x=-63,56, y=66,02, z=-37,34], cip['SilverTSM'/569584, l='MpServer', x=-60,50, y=66,02, z=-41,44], cip['harleydog9'/780044, l='MpServer', x=-34,83, y=71,80, z=-82,33], cip['§4§lSurvival'/780015, l='MpServer', x=-40,41, y=65,02, z=-127,53], cip['§c§lKitPvP'/780021, l='MpServer', x=-32,72, y=65,02, z=-121,50], cip['§b§lSkyblock'/780024, l='MpServer', x=-46,50, y=65,02, z=-127,47], cip['§6§l Vanilla'/780018, l='MpServer', x=-34,47, y=65,02, z=-127,41], cip['§d§lBedwars'/780012, l='MpServer', x=-46,34, y=65,02, z=-115,53], cip['samixshady'/569569, l='MpServer', x=-40,47, y=102,52, z=-50,56], cip['ycxy_'/569596, l='MpServer', x=-40,47, y=102,52, z=-51,19], cip['Skythem'/569605, l='MpServer', x=-24,44, y=66,02, z=-65,66], cip['ConfidentTepos'/569581, l='MpServer', x=-26,38, y=66,02, z=-65,38], cip['ycxy_'/569644, l='MpServer', x=-24,44, y=66,02, z=-49,47], cip['Destial'/569611, l='MpServer', x=-16,53, y=66,02, z=-56,53], cip['minatozakijihyo'/569593, l='MpServer', x=-18,41, y=66,02, z=-61,59], cip['Gilford'/569557, l='MpServer', x=-17,44, y=66,02, z=-54,44], cip['obl1v1os'/569638, l='MpServer', x=-17,50, y=66,02, z=-52,56], cip['Elmo_Buzz'/569560, l='MpServer', x=-17,31, y=66,02, z=-58,59], cip['9G39'/569554, l='MpServer', x=-22,47, y=66,02, z=-49,63], cip['Jamielailailai'/569590, l='MpServer', x=-17,56, y=66,02, z=-60,38], cip['samixshady'/569641, l='MpServer', x=-20,38, y=66,02, z=-43,50], cip['Singapore'/569575, l='MpServer', x=-17,66, y=66,02, z=-36,47], cip['Ahysahys'/569572, l='MpServer', x=-17,72, y=66,02, z=-39,44]]
	Chunk stats: MultiplayerChunkCache: 73, 73
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -41,00,72,00,77,00 - World: (-41,72,77), Chunk: (at 7,4,13 in -3,4; contains blocks -48,0,64 to -33,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 22931 game time, 7638000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 89 total; [cio['DarkLord063'/780120, l='MpServer', x=-40,55, y=69,00, z=-83,81], cip['Destial'/569611, l='MpServer', x=-16,53, y=66,02, z=-56,53], cip['AstralNocturne'/569614, l='MpServer', x=-63,63, y=66,52, z=-55,53], cip['§a§lTownyEarth'/780009, l='MpServer', x=-48,34, y=65,02, z=-121,47], cip['harleydog9'/780044, l='MpServer', x=-34,83, y=71,80, z=-82,33], cip['§6§lMeggiKari'/569626, l='MpServer', x=-53,50, y=65,02, z=-96,53], cip['AstralNocturne'/569614, l='MpServer', x=-63,63, y=66,52, z=-55,53], cip['Sakoi3'/569751, l='MpServer', x=-60,22, y=66,02, z=-51,50], cip['ConfidentTepos'/569602, l='MpServer', x=-63,56, y=66,02, z=-37,34], cip['Russsy'/569623, l='MpServer', x=-60,47, y=66,02, z=-61,66], cip['Obl1v1os'/569599, l='MpServer', x=-63,66, y=66,52, z=-57,38], cip['NampaiKid007'/569617, l='MpServer', x=-59,41, y=66,02, z=-42,53], cip['Skythem'/569605, l='MpServer', x=-24,44, y=66,02, z=-65,66], cip['Destial'/569587, l='MpServer', x=-59,41, y=-67108863,98, z=-37,13], cip['ConfidentTepos'/569602, l='MpServer', x=-63,56, y=66,02, z=-37,34], cip['SilverTSM'/569584, l='MpServer', x=-60,50, y=66,02, z=-41,44], cip['harleydog9'/780044, l='MpServer', x=-34,83, y=71,80, z=-82,33], cip['§6§lMeggiKari'/569626, l='MpServer', x=-53,50, y=65,02, z=-96,53], cip['§4§lSurvival'/780015, l='MpServer', x=-40,41, y=65,02, z=-127,53], cip['§c§lKitPvP'/780021, l='MpServer', x=-32,72, y=65,02, z=-121,50], cip['§b§lSkyblock'/780024, l='MpServer', x=-46,50, y=65,02, z=-127,47], cip['§6§l Vanilla'/780018, l='MpServer', x=-34,47, y=65,02, z=-127,41], cip['§d§lBedwars'/780012, l='MpServer', x=-46,34, y=65,02, z=-115,53], cip['NampaiKid007'/569617, l='MpServer', x=-59,41, y=66,02, z=-42,53], cip['samixshady'/569569, l='MpServer', x=-40,47, y=102,52, z=-50,56], cip['ycxy_'/569596, l='MpServer', x=-40,47, y=102,52, z=-51,19], cip['Skythem'/569605, l='MpServer', x=-24,44, y=66,02, z=-65,66], cip['ConfidentTepos'/569581, l='MpServer', x=-26,38, y=66,02, z=-65,38], cip['Sakoi3'/569751, l='MpServer', x=-60,22, y=66,02, z=-51,50], cip['Russsy'/569623, l='MpServer', x=-60,47, y=66,02, z=-61,66], cip['ycxy_'/569644, l='MpServer', x=-24,44, y=66,02, z=-49,47], cip['Destial'/569611, l='MpServer', x=-16,53, y=66,02, z=-56,53], cip['minatozakijihyo'/569593, l='MpServer', x=-18,41, y=66,02, z=-61,59], cip['samixshady'/569641, l='MpServer', x=-20,38, y=66,02, z=-43,50], cip['Gilford'/569557, l='MpServer', x=-17,44, y=66,02, z=-54,44], cip['obl1v1os'/569638, l='MpServer', x=-17,50, y=66,02, z=-52,56], cip['ycxy_'/569644, l='MpServer', x=-24,44, y=66,02, z=-49,47], cip['Elmo_Buzz'/569560, l='MpServer', x=-17,31, y=66,02, z=-58,59], cip['9G39'/569554, l='MpServer', x=-22,47, y=66,02, z=-49,63], cip['Jamielailailai'/569590, l='MpServer', x=-17,56, y=66,02, z=-60,38], cip['samixshady'/569641, l='MpServer', x=-20,38, y=66,02, z=-43,50], cip['Singapore'/569575, l='MpServer', x=-17,66, y=66,02, z=-36,47], adi['CMIArmorStandForSit'/169, l='MpServer', x=-59,41, y=68,28, z=-124,94], cip['Ahysahys'/569572, l='MpServer', x=-17,72, y=66,02, z=-39,44], adi['CMIArmorStandForSit'/170, l='MpServer', x=-70,50, y=63,78, z=-127,50], adi['Armor Stand'/171, l='MpServer', x=-79,50, y=64,94, z=-124,50], adi['Armor Stand'/174, l='MpServer', x=-81,50, y=65,50, z=-125,50], cip['obl1v1os'/569638, l='MpServer', x=-17,50, y=66,02, z=-52,56], adi['Armor Stand'/175, l='MpServer', x=-82,50, y=67,00, z=-125,50], adi['Armor Stand'/176, l='MpServer', x=-80,50, y=64,94, z=-123,50], adi['CMIArmorStandForSit'/50, l='MpServer', x=-42,25, y=66,78, z=-111,25], adi['CMIArmorStandForSit'/51, l='MpServer', x=-42,50, y=69,28, z=-104,53], adi['CMIArmorStandForSit'/199, l='MpServer', x=-25,78, y=63,78, z=-128,59], adi['CMIArmorStandForSit'/200, l='MpServer', x=-26,50, y=63,78, z=-128,50], cip['Elmo_Buzz'/569560, l='MpServer', x=-17,31, y=66,02, z=-58,59], adi['§d§l/register <password> <retype password>'/780123, l='MpServer', x=-40,53, y=71,91, z=-87,44], adi['§bRegister your account to start playing'/780122, l='MpServer', x=-40,53, y=72,19, z=-87,44], adi['§bWelcome to §c§lSG§f§lCraft!'/780121, l='MpServer', x=-40,53, y=72,44, z=-87,44], adi['§c§l/fourinarow <player>'/780127, l='MpServer', x=-34,00, y=66,25, z=-102,50], adi['§eBored at Lobby? Play connect 4 with another player!'/780126, l='MpServer', x=-34,00, y=66,50, z=-102,50], adi['§c§l/rules §6to read the rules'/780125, l='MpServer', x=-40,53, y=71,41, z=-87,44], adi['§c§l/help §r§6for all the commands'/780124, l='MpServer', x=-40,53, y=71,66, z=-87,44], cip['9G39'/569554, l='MpServer', x=-22,47, y=66,02, z=-49,63], cip['Gilford'/569557, l='MpServer', x=-17,44, y=66,02, z=-54,44], cip['§a§lTownyEarth'/780009, l='MpServer', x=-48,34, y=65,02, z=-121,47], adi['§6§l1 §eplayers online now!'/780136, l='MpServer', x=-6,59, y=67,22, z=-130,47], cip['§4§lSurvival'/780015, l='MpServer', x=-40,41, y=65,02, z=-127,53], cip['ConfidentTepos'/569581, l='MpServer', x=-26,38, y=66,02, z=-65,38], cip['§d§lBedwars'/780012, l='MpServer', x=-46,34, y=65,02, z=-115,53], adw['item.item.dyePowder.lightBlue'/780131, l='MpServer', x=-73,16, y=65,00, z=-130,50], cip['samixshady'/569569, l='MpServer', x=-40,47, y=102,52, z=-50,56], adi['§e1.8 - 1.15.2'/780130, l='MpServer', x=-73,16, y=67,22, z=-130,50], adi['§4§lEarth Wars'/780129, l='MpServer', x=-73,16, y=67,44, z=-130,50], adw['item.item.emerald'/780128, l='MpServer', x=-34,00, y=65,00, z=-102,50], cip['Ahysahys'/569572, l='MpServer', x=-17,72, y=66,02, z=-39,44], adw['item.item.swordDiamond'/780135, l='MpServer', x=-6,59, y=65,00, z=-130,47], adi['§e1.8 - 1.15.2'/780134, l='MpServer', x=-6,59, y=68,16, z=-130,47], adi['§b§l EragonMC KitPVP Server'/780133, l='MpServer', x=-6,59, y=68,38, z=-130,47], cip['Singapore'/569575, l='MpServer', x=-17,66, y=66,02, z=-36,47], adi['§6§l0 §eplayers online now!'/780132, l='MpServer', x=-73,16, y=66,25, z=-130,50], cip['minatozakijihyo'/569593, l='MpServer', x=-18,41, y=66,02, z=-61,59], cip['§b§lSkyblock'/780024, l='MpServer', x=-46,50, y=65,02, z=-127,47], cip['ycxy_'/569596, l='MpServer', x=-40,47, y=102,52, z=-51,19], cip['Obl1v1os'/569599, l='MpServer', x=-63,66, y=66,52, z=-57,38], cip['SilverTSM'/569584, l='MpServer', x=-60,50, y=66,02, z=-41,44], cip['§6§l Vanilla'/780018, l='MpServer', x=-34,47, y=65,02, z=-127,41], cip['Destial'/569587, l='MpServer', x=-59,41, y=-67108863,98, z=-37,13], cip['§c§lKitPvP'/780021, l='MpServer', x=-32,72, y=65,02, z=-121,50], cip['Jamielailailai'/569590, l='MpServer', x=-17,56, y=66,02, z=-60,38]]
	Retry entities: 0 total; []
	Server brand: Travertine <- Paper
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (armv8l) version 4.4.95+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (HUAWEI DRA-LX2, Android 8.1.0), The Android Project
	Memory: 0 bytes (0 MB) / 254373912 bytes (242 MB) up to 402653184 bytes (384 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by khanhduytran0** [comment]
You need join in 1.11 to avoid render entity crash.

**Comment by khanhduytran0** [comment]
Duplicate with your own issue #236
