### ISSUE TITLE
[BUG] Flip the screen

### ISSUE THREAD

**Issue by doubijunNB** [PojavLauncherTeam/PojavLauncher#2600]
### Describe the bug

Play with the VirGL renderer to flip the screen

### The log file and images/videos

![Uploading -1d2878288d1c5417.jpg…]()

### Steps To Reproduce

```markdown
1. Start the pojav 
2. Select the VirGL renderer 
3. Start 1.16.5 and enter the archive 
4. The screen flipped
```

### Expected Behavior

The screen won't flip

### Platform

```markdown
- Device model: oppo ace2
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-298-163206f34-v3. openjdk
```

**Comment by ghost** [comment]
Update pojav launcher
Its fixed in latest build

**Comment by doubijunNB** [comment]
> 

It's a fixed version. There's still a probability of reversal

**Comment by doubijunNB** [comment]
![Uploading -1d2878288d1c5417.jpg…]()

**Comment by Mathias-Boulay** [comment]
virgl bugs cannot be fixed
