### ISSUE TITLE
Anyone make a shader for Virglrender no lag

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#2602]
### Describe the bug

The shader are so laggy

### The log file and images/videos

Non no bug just lag.txt

### Steps To Reproduce

```markdown
1. Change to Virglrender
2. Start the Pojavlauncher
3. Play Minecraft
4. Use shader
5. Then lagg on 6gb ram
```

### Expected Behavior

So laggy when using PC shader

### Platform

```markdown
- Device model: umidigi bison
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest on github
```

### Anything else?

Plss make a shader for Virglrender like gl4es for Mali gpu thx

**Comment by GoneSubject** [comment]
just buy a better phone and ram doesn't boost fps

**Comment by kedrick021** [comment]
6gb ram already good phone no lag on 2 render distance but when add more

**Comment by GoneSubject** [comment]
> 6gb ram already good phone no lag on 2 render distance but when add more

like i said ram doesn't boost your fps

**Comment by khanhduytran0** [comment]
> PC shader

Yeah, it’s designed for PC, not mobile devices, so what do you expect? ~~Ability to run SEUS PTGI E12 or raytracing without lag/issues?~~

**Comment by kedrick021** [comment]
> > PC shader
> 
> Yeah, it’s designed for PC, not mobile devices, so what do you expect? ~Ability to run SEUS PTGI E12 or raytracing without lag/issues?~

Why open4es shader dev not making anymore shader?

**Comment by ghost** [comment]
> > > PC shader
> > 
> > 
> > Yeah, it’s designed for PC, not mobile devices, so what do you expect? ~Ability to run SEUS PTGI E12 or raytracing without lag/issues?~
> 
> Why open4es shader dev not making anymore shader?

U think u have rtx 3090 to run opengl 4.6? 
Also ur phone only have opengl es 3.2

And u think u can run seus ptgi e12 with 69420 fps?
This pc game not design for mobile

**Comment by NotAHero04** [comment]
~~Did you know that Minecraft already has built-in shaders since 1.7? And it's kinda smooth :)~~

**Comment by kedrick021** [comment]
Omg what you're all problem did you read the tittle? Plss READDDDDD

**Comment by khanhduytran0** [comment]
> Omg what you're all problem did you read the tittle? Plss READDDDDD

You know, we aren’t shader developers.

**Comment by NotAHero04** [comment]
> Omg what you're all problem did you read the tittle? Plss READDDDDD

Did you even know what are **shaders**?

**Comment by kedrick021** [comment]
I mean all here not only dev in the chat

**Comment by khanhduytran0** [comment]
@artdeell:
> Shader is *not* a zipfile that makes your game look like it's 69420k rtx
> Shader is a program for your graphics unit that lets GPU know how to draw stuff

**Comment by kedrick021** [comment]
> > Omg what you're all problem did you read the tittle? Plss READDDDDD
> 
> Did you even know what are **shaders**?

Did you drink a coffee before reading this?

**Comment by kedrick021** [comment]
> > > Omg what you're all problem did you read the tittle? Plss READDDDDD
> > 
> > 
> > Did you even know what are **shaders**?
> 
> Did you drink a coffee before reading this?

You have to much coffee

**Comment by NotAHero04** [comment]
> @artdeell:
> 
> > Shader is _not_ a zipfile that makes your game look like it's 69420k rtx
> > Shader is a program for your graphics unit that lets GPU know how to draw stuff

@kedrick021 you may want to read this.

**Comment by khanhduytran0** [comment]
> I mean all here not only dev in the chat

Nobody will make one for you unless they’re paid, or make for global (like Open4ES) since they have a life too.

**Comment by ENDERMANYK** [comment]
~~virgl is enough to run shaders, why you still need Open4ES which intend running on GL4ES?~~

**Comment by TWTommyee** [comment]
Sir you only have a MediaTek P60 what do you expect

**Comment by khanhduytran0** [comment]
> Sir you only have a MediaTek P60 what do you expect

yeah it’s not AMD Ryzen™ 9 5900X CPU with RTX 3090 GPU

**Comment by tigerbrocode** [comment]
> ~Did you know that Minecraft already has built-in shaders since 1.7? And it's kinda smooth :)~

Thx for the tip :)

**Comment by kedrick021** [comment]
> ~virgl is enough to run shaders, why you still need Open4ES which intend running on GL4ES?~

Because PC shader not playable than open4es

**Comment by kedrick021** [comment]
> > ~virgl is enough to run shaders, why you still need Open4ES which intend running on GL4ES?~
> 
> Because PC shader not playable than open4es
If I use vgpu there a black line in shader but if I use Virglrender there no black line in shader but some open4es are not support for Virglrender

**Comment by kedrick021** [comment]
> 

I play 1.18.1 with shader that smooth but only 2render distance that boring

**Comment by kedrick021** [comment]
> > ~Did you know that Minecraft already has built-in shaders since 1.7? And it's kinda smooth :)~
> 
> Thx for the tip :)

I play 1.18.1 with shader and that smooth but only 2 render distance and that's boring

**Comment by kedrick021** [comment]
> > > ~virgl is enough to run shaders, why you still need Open4ES which intend running on GL4ES?~
> > 
> > 
> > Because PC shader not playable than open4es
> > If I use vgpu there a black line in shader but if I use Virglrender there no black line in shader but some open4es are not support for Virglrender



> > > ~virgl is enough to run shaders, why you still need Open4ES which intend running on GL4ES?~
> > 
> > 
> > Because PC shader not playable than open4es
> > If I use vgpu there a black line in shader but if I use Virglrender there no black line in shader but some open4es are not support for Virglrender

Can you make for Virglrender shader plsss 🥺🥺

**Comment by NotAHero04** [comment]
You have:
> 2x big ARM Cortex-A76 cores with up to 2.05 GHz and 6x small and power efficient ARM Cortex-A55 cores (max. 2 GHz) in two clusters (bigLITTLE).
>
Minimum requirements:
> Intel Core i3-3210 [2x2x]3.2 GHz / AMD A8-7600 APU [2x2x]3.1 GHz or equivalent
>
Unless Minecraft is multi-threaded, your phone will perform waaaaaaay slower than these processors. Please stop comparing phones with computers!

**Comment by mchnjt** [comment]
> You have:
> 
> > 2x big ARM Cortex-A76 cores with up to 2.05 GHz and 6x small and power efficient ARM Cortex-A55 cores (max. 2 GHz) in two clusters (bigLITTLE).
> 
> Minimum requirements:
> 
> > Intel Core i3-3210 [2x2x]3.2 GHz / AMD A8-7600 APU [2x2x]3.1 GHz or equivalent
> 
> Unless Minecraft is multi-threaded, your phone will perform waaaaaaay slower than these processors. Please stop comparing phones with computers!

and even slower than running in a nokia brickphone toaster

**Comment by kedrick021** [comment]
> > @artdeell:
> > > Shader is _not_ a zipfile that makes your game look like it's 69420k rtx
> > > Shader is a program for your graphics unit that lets GPU know how to draw stuff
> 
> @kedrick021 you may want to read this.

Omg your imagination are far away I only what's shader like open4es not rtx

**Comment by kedrick021** [comment]
> > > @artdeell:
> > > > Shader is _not_ a zipfile that makes your game look like it's 69420k rtx
> > > > Shader is a program for your graphics unit that lets GPU know how to draw stuff
> > 
> > 
> > @kedrick021 you may want to read this.
> 
> Omg your imagination are far away I only what's shader like open4es not rtx


I always play open4es shader on my old phone but is dead now and they saying Mali is good for shader Zink that's why I buying it but not good for open4es because of bug and glitch

**Comment by irice7** [comment]
sadge it doesnt emulate nvidia rtx 6900 :(

**Comment by irice7** [comment]
shader is a fucking text file with a lot of math in it.

**Comment by NotAHero04** [comment]
> > > @artdeell:
> > > > Shader is _not_ a zipfile that makes your game look like it's 69420k rtx
> > > > Shader is a program for your graphics unit that lets GPU know how to draw stuff
> > 
> > 
> > @kedrick021 you may want to read this.
> 
> Omg your imagination are far away I only what's shader like open4es not rtx

But I see you are understanding the concept of "shaders" in a wrong way.

**Comment by irice7** [comment]
> > > > @artdeell:
> > > > > Shader is _not_ a zipfile that makes your game look like it's 69420k rtx
> > > > > Shader is a program for your graphics unit that lets GPU know how to draw stuff
> > > 
> > > 
> > > @kedrick021 you may want to read this.
> > 
> > 
> > Omg your imagination are far away I only what's shader like open4es not rtx
> 
> But I see you are understanding the concept of "shaders" in a wrong way.

hey bro did u know shader its so sadge

**Comment by irice7** [comment]
close issue eta wen
