### ISSUE TITLE
[BUG] RL CRAFT CRASH WHEN MOJANG SCREEN

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2603]
### Describe the bug

The game just force close in mojang screen idk why

### The log file and images/videos

.

### Steps To Reproduce

```markdown
Start pojav launcher
Select 1.12.2forge
Game force close
```

### Expected Behavior

..

### Platform

```markdown
- Device model: Oppo A12 3/32G
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version:[Latest Release ||version crocus-v3_openjdk
```

### Anything else?

.

**Comment by NotAHero04** [comment]
No log...

**Comment by GoneSubject** [comment]
why just dot

**Comment by TWTommyee** [comment]
Also what version of RLcraft?
V2.8 or V2.9?

**Comment by Cube5x59999** [comment]
Link to Jre 17 please be im new to pojav

**Comment by Cube5x59999** [comment]
The log file is at android/data/net.kdt.pojavlaunch/files/latest log.txt
(Use Zarchiver)

**Comment by MARnelPH12** [comment]
HOW TO PASTE THE LOG FILE HERE?

**Comment by Cube5x59999** [comment]
Use attach file option

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by MARnelPH12** [comment]
> 

Where ?
