### ISSUE TITLE
[BUG] Failed to run processor: java.io.FileNotFoundException:/data/user/0/net.kdt.pojavlaunch/cache/forge_installer8193332305929816707/data/client.Izma (No such file or directory) See log for more details.

### ISSUE THREAD

**Issue by NozomuAkuma** [PojavLauncherTeam/PojavLauncher#2605]
### Describe the bug

I was installing forge 1.15.2 - 31.2.57 when it ended this popped.

### The log file and images/videos

![Screenshot_2022-01-23-17-32-08-94](https://user-images.githubusercontent.com/69977371/150673179-c0d64283-4a14-4e38-8d57-aaf3d54c6b9d.png)

### Steps To Reproduce

```markdown
I installed Forge 1.15.2 - 31.2.57
```

### Expected Behavior

I thought it was nothing and I selected the play button but the game exited with code 1

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Cube5x59999** [comment]
Ummm is forge installer corrupt? Try re-download forge installer

**Comment by NozomuAkuma** [comment]
I did! It didn't work with the other versions too.

**Comment by tigerbrocode** [comment]
I deleted the version (for me) 1.12.2 by going to android/data/pojavlauncher/.Minecraft/versions
And deleted the 1.12.2 folder and opened pojav launcher again and installed the jar file again and it worked try using this

**Comment by NozomuAkuma** [comment]
Didn't work

**Comment by Cube5x59999** [comment]
Do you use Java 8 while doing installation?

**Comment by SprainedSpark89** [comment]
is the file path games/pojavlauncher/.minecraft/versions?

**Comment by Cube5x59999** [comment]
Delete 1.12.2 by going to android/data/net.kdt.pojavlaunch/.minecraft/versions/1.12.2 (android 11 only)
(Use Zarchiver if android 11)

**Comment by SprainedSpark89** [comment]
hey what is the 
device your using and what version of android if you don't know how you go to settings system info or about device

**Comment by DemonGirl2001** [comment]
I'm having the same issue. I have never downloaded forge before and have no previous versions. A youtube recommended downloading openjdk and that should help but I still have the same issue popping up. I am using a relatively new Lenovo laptop. Any tips or recommendations would be greatly appreciated!

**Comment by SprainedSpark89** [comment]
what version of minecraft

**Comment by NozomuAkuma** [comment]
Uh. 1.15.2 i think

**Comment by NozomuAkuma** [comment]
Android version 7.1.1 it's very old.

**Comment by NozomuAkuma** [comment]
Sorry i didn't think this would get solved so i didn't look at this all month.

**Comment by NozomuAkuma** [comment]
What is java 8? I don't know aeugh. 😥😥

**Comment by NozomuAkuma** [comment]
I checked and it looks like i do? Is there any problems with Java8?

**Comment by SprainedSpark89** [comment]
no

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
