### ISSUE TITLE
1.17.1 Not Working

### ISSUE THREAD

**Issue by Abhishek3111** [PojavLauncherTeam/PojavLauncher#2607]
### Describe the bug

I am trying to run 1.17.1 but it shows - can't find compatible Java runtime please tell me what to do and please give me a solution I really want to play. 

### The log file and images/videos

![Screenshot_20220123_184534](https://user-images.githubusercontent.com/71537611/150680316-be28e4e5-d61e-45bd-8e83-0bfc898d0e0f.jpg)

### Steps To Reproduce

```markdown
I do it again and again and it happens again and again
```

### Expected Behavior

I expect it to launch

### Platform

```markdown
- Device model: VIVO Y30 4/128GB
- CPU architecture: 
- Android version: 10
- PojavLauncher version: 
Latest
```

### Anything else?

No

**Comment by khanhduytran0** [comment]
> I expect it to launch

With just java 8 installed? :eyes:

What you need to know is 1.17 requires Java 16, 1.18 requires Java 17.
Follow [this](https://pojavlauncherteam.github.io/updates/117.html) for getting Java 17 and additionally 1.18 workaround.
