### ISSUE TITLE
[BUG] Unable to find the files for PojavLauncher

### ISSUE THREAD

**Issue by NettrGaming** [PojavLauncherTeam/PojavLauncher#2608]
### Describe the bug

I was planning on playing some modded Minecraft Java, but when I tried looking for the main files for the PojavLauncher in my games folder, the files weren't there.
![Screenshot_20220123-123307_My Files](https://user-images.githubusercontent.com/98278527/150690770-a349f0cc-924f-418d-aee7-4c6226a1784e.jpg)
So I just thought that the app didn't install correctly, so I uininstalled the PojavLaunncher and downloaded it again. When I opened the app, it said how the file location will be changing places to "Android/data/net.kdt.pojavlaunch/files," so I naturally thought that I was just looking at an old tutorial video. So I tried looking in that location, and I still didn't find the files for the PojavLauncher. 
![Screenshot_20220123-123314_My Files](https://user-images.githubusercontent.com/98278527/150691056-329619c4-219a-453c-9887-fb9d04419cae.jpg)
So now I don't really have a clue where the files could even be. I tried searching in my files for "PojavLauncher," and nothing showed up, even with hidden files shown. And the weird thing is that I can still open my Minecraft Forge world normally, and my test world is still saved exactly how I left it, which means the files are saved _somewhere_, but I don't know where. My only guess is that it is somewhere in that ".spstorage" file, but I'm not sure that is normally where the files for PojavLauncher are saved.
I will attach more photos showing what my hidden files look like, how none of the PojavLauncher files are showing up I'm my Games and my Android/data folders, how PojavLauncher is still saving my in-game Minecraft progress meaning there has to be saving files somewhere, and me wondering if that ".spstorage" file is where my PojavLauncher files are. I'm just a little confused and maybe this is some sort of bug, but I have no idea so I will post this issue, just in case it is a bug because it is making impossible for me to put my mods in my Minecraft folder.
![Screenshot_20220123-133207_Gallery](https://user-images.githubusercontent.com/98278527/150692906-52224f16-5749-4478-b47c-4d5e3ae4f2c4.jpg)
![Screenshot_20220123-133245_Gallery](https://user-images.githubusercontent.com/98278527/150692907-a2eb8e25-104c-4a61-b800-5d34da164672.jpg)
![Screenshot_20220123-133303_Gallery](https://user-images.githubusercontent.com/98278527/150692908-890873cc-bc5e-4f3d-9771-48a593db8b3f.jpg)
![Screenshot_20220123-133541_Gallery](https://user-images.githubusercontent.com/98278527/150692910-655d17ff-9625-4487-bd04-98f70184d381.jpg)
![Screenshot_20220123-133642_Gallery](https://user-images.githubusercontent.com/98278527/150692911-7fc26dfa-e107-4c42-b4a4-997349d95d23.jpg)
And here is the final picture showing that ".spstorage" file, maybe this is where I can find the PojavLauncher files? Also, the gray lines over the file icon is what my hidden files look like:
![Screenshot_20220123-133739_Gallery](https://user-images.githubusercontent.com/98278527/150692988-e9f1424d-6874-4468-b6f5-8daf014883b5.jpg)

### The log file and images/videos

_I tried to attach a video here but apparently it was too big, so I screenshoted the video and used it in my pictures above._

### Steps To Reproduce

```markdown
1. Install PojavLauncher

2. Go to Internal Storage

3. Check the "Games" folder to see if the PojavLauncher files exists or not. If so, then it is working fine and there is no problem.

4. Check the "Android/data" folders to see if the PojavLauncher files exists or not. If so, then it is working fine and there is no problem.

5. Open PojavLauncher

6. Launch a Minecraft instance that is a Forge instance

7. Create a new Minecraft world and then quit the game

8. Relaunch PojavLauncher and go back into the Minecraft Forge instance. If the world was exactly the way you left it, but you still can't find the PojavLauncher files, you recreated the bug.
```

### Expected Behavior

I expected to find the PojavLauncher game files so that I can install some mods I wanted.

### Platform

```markdown
- Device model: Galaxy S10 5G
- CPU architecture: Kyro 485
- Android version: 12
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

If the PojavLauncher files happen to be in the ".spstorage" file, how do I open the file?

**Comment by GoneSubject** [comment]
the PojavLauncher's file is in sdcard/Android/data/net.kdt.pojavlaunch(.debug)
