### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Dontdoclap** [PojavLauncherTeam/PojavLauncher#2609]
### Describe the bug

i sellect 1.18.1 and then its go 1.7.10????

### The log file and images/videos

https://user-images.githubusercontent.com/98183958/150693859-c0b71c62-2d7b-4808-be75-a33a3e455c1a.mp4

### Steps To Reproduce

```markdown
1 start pojavlauncher
2 sellect 1.18.1
3 play
4 it open 1.7.10
```

### Expected Behavior

i dowland all files and i do perfectly with pdf.

### Platform

```markdown
- Device model: huawei matepad 11
- CPU architecture: snapdragon 865 aarch64
- Android version: 10
- PojavLauncher version: lalest
```

**Comment by GoneSubject** [comment]
did you have all requirements? [here](https://pojavlauncherteam.github.io/updates/117.html) is the instructions (can work for 1.18)

**Comment by Cube5x59999** [comment]
If it's your first time launching app it happens because when I first time launch the app when I select 1.17 it does 1.7.10 so relaunch game

_I'll play older versions because the 1.18 is not soo stable_

**Comment by Dontdoclap** [comment]
> did you have all requirements? [here](https://pojavlauncherteam.github.io/updates/117.html) is the instructions (can work for 1.18)

Yeah, the mod send me an pdf. İ do all perfect

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
