### ISSUE TITLE
Fps drop when using external control's.

### ISSUE THREAD

**Issue by Kroko300** [PojavLauncherTeam/PojavLauncher#2610]
### Describe the bug

When opening minecraft using external keyboard and mouse,the fps drop and the phone or internal keyboard is pop uping in no time when using external controls.

### The log file and images/videos

......

### Steps To Reproduce

```markdown
-Open the settings go to more settings
-On the otg
-go to pojav launcher
-set all your settings for your acc then play.
-select your world
-Play in a short of time using your external controls(keyboard and mouse)
*It will automatically drop its fps and the internal keyboard will pop up*
-tap the right botton of mouse
*then the bug repeating,until the game quited and your world haven't save automatic*
```

### Expected Behavior

I expect the game next update to be more improvements.

### Platform

```markdown
- Device model: Vivo 1906
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

The only peoblem in the external control and fps drop in no time.

**Comment by SprainedSpark89** [comment]
I think devices use cpu to process and the app may have to also process the controls to remap to keyboard keys. Most likely

**Comment by SprainedSpark89** [comment]
but a wired keyboard and mouse may be the fastest

**Comment by Sazedzahan** [comment]
update to the latest action release

**Comment by Sazedzahan** [comment]
of pojavlauncher

**Comment by SprainedSpark89** [comment]
last time i looked it said that the playstore version is more up to date

**Comment by RaydanOMGr** [comment]
> last time i looked it said that the playstore version is more up to date

It never is actually

**Comment by SprainedSpark89** [comment]
i would recommend the playstore ver still

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
