### ISSUE TITLE
[BUG] Sodium 1.16.5 crashes without explanation

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2611]
### Describe the bug

When you enter the world/server, the game simply crashes. I used mods: sodium, fabric api, fabric 1.16.5. I downloaded mods from the official website. I set the graphics settings to low

### The log file and images/videos

. 

### Steps To Reproduce

```markdown
1. Downloaded fabric 1.16.5 
2. Installed fabric api, sodium 
3. Launched fa
4.Went into a single world (tried to log in to the servers) 
5.The game instantly crashed out without errors
```

### Expected Behavior

I expected to be able to go into the world or the server

### Platform

```markdown
- Device model: honor 9c
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version:Latest Beta and Latest Release
```

### Anything else?

I treat this project with great respect and want it to develop further.

**Comment by GoneSubject** [comment]
you must turn off the compact vetex format so the game doesn't crash but you should turn off the fog occlusion so the game can look normal![IMG_20220124_221849.jpg](https://user-images.githubusercontent.com/95298052/150810740-5d0a0431-17bc-4b56-b128-55a5991cf5d2.jpg)

**Comment by Iarkont** [comment]
> you must turn off the compact vetex format so the game doesn't crash but you should turn off the fog occlusion so the game can look normal![IMG_20220124_221849.jpg](https://user-images.githubusercontent.com/95298052/150810740-5d0a0431-17bc-4b56-b128-55a5991cf5d2.jpg)

Didn't help anyway crashes

**Comment by NotAHero04** [comment]
Could you send the launcher log? It would help us on diagnosing the error

**Comment by Iarkont** [comment]
> Could you send the launcher log? It would help us on diagnosing the error

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7926719/latestlog.txt)
