### ISSUE TITLE
The pri and sec button is not working properly

### ISSUE THREAD

**Issue by Aldrin2185** [PojavLauncherTeam/PojavLauncher#2612]
### Describe the bug

1.the pri and sec is not working properly it cant select the blocks and item in my inventory

### The log file and images/videos

https://user-images.githubusercontent.com/98380004/150928072-d1be6f80-ea3a-4a63-92f4-65dfb7f59097.mp4

Pls help :(

### Steps To Reproduce

```markdown
1.when i try to get item or select an item in my inventory it just dont work i need to hold it and drag it on the slots to get it
2.Shift right click is also not working
```

### Expected Behavior

I expected it to just press the pri button and it will automatically select the item and wear armor much more faster

### Platform

```markdown
- Device model:CPH2083
- CPU architecture:aarch64
- Android version:9
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

Nope

**Comment by GoneSubject** [comment]
you turned on touchscreen mode(see the screenshot below) in the mouse settings so you must drag the item to use so turn it off
![z3137671083209_8e8abd9a95d31a8cb5741c24f4e28aff](https://user-images.githubusercontent.com/95298052/150929549-456da61d-98b2-49c8-8582-0ff69727f600.jpg)

**Comment by Aldrin2185** [comment]
Ohhh thank you ill try it :D

**Comment by Aldrin2185** [comment]
It works tysm 😊

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
