### ISSUE TITLE
[BUG] VGPU Only shows white screen...

### ISSUE THREAD

**Issue by irice7** [PojavLauncherTeam/PojavLauncher#2613]
### Describe the bug

It shows nothing, I'm using VGPU (because people says it has better performance, which good for pvp.)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7933274/latestlog.txt)

Btw i decided to force crashing it after it shows the white screen.

### Steps To Reproduce

```markdown
Use VGPU renderer then start any versions.
```

### Expected Behavior

It should work fine (or my device has issues with it?)

### Platform

```markdown
- Device model: Oppo A5s 3/32G
- CPU architecture: aarch64
- Android version: 8.1.0
- PojavLauncher version: profiles-2-electric-boogaloo. https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1677959713
```

### Anything else?

Nope

**Comment by irice7** [comment]
bhai no answer kekw

**Comment by Mathias-Boulay** [comment]
vgpu is no more

**Comment by irice7** [comment]
No thanks late answer
