### ISSUE TITLE
1.17.1 doesn't work

### ISSUE THREAD

**Issue by Balqees2010** [PojavLauncherTeam/PojavLauncher#2614]
### Is this request related to a bug?

1.17.1 forge is not working

**Comment by GoneSubject** [comment]
forge 1.17+ is not supported

**Comment by Dorabotmaster** [comment]
There is a temporary solution

**Comment by Illia24** [comment]
> Есть временное решение

Какое?

**Comment by Illia24** [comment]
> > Есть временное решение
> 
> Какой?



> Есть временное решение

How?

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
