### ISSUE TITLE
1.18.1 java.lang.IllegalStateException: could not preload shader position

### ISSUE THREAD

**Issue by HyperBlaze456** [PojavLauncherTeam/PojavLauncher#2615]
### Describe the bug

Application exited with code -1.

### The log file and images/videos

---- Minecraft Crash Report ----
// Oops.

Time: 22. 1. 26. 오전 5:44
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at epe.a(SourceFile:423)
	at epe.a(SourceFile:407)
	at dxo.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:199)
Caused by: yk: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7: S0054: Overloading built-in function 'max' not allowed
	at yk.a(SourceFile:48)
	at epw.<init>(SourceFile:200)
	at epe.a(SourceFile:419)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7: S0054: Overloading built-in function 'max' not allowed
	at dry.b(SourceFile:72)
	at dry.a(SourceFile:54)
	at epw.a(SourceFile:241)
	at epw.<init>(SourceFile:182)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at epe.a(SourceFile:423)
	at epe.a(SourceFile:407)
	at dxo.<init>(SourceFile:617)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:199)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-9
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 420625864 bytes (401 MiB) / 1203765248 bytes (1148 MiB) up to 1203765248 bytes (1148 MiB)
	CPUs: 8
	Processor Vendor: 0x53
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x001 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3887.81
	Virtual memory used (MB): 4709.88
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1616.02
	JVM Flags: 2 total; -Xms1148M -Xmx1148M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x 

### Steps To Reproduce

```markdown
Start launcher

Using jdk 17 for Arm64, maded by u guys

Used vulkan renderer

And played 1.18.1
```

### Expected Behavior

I expected too launch well, since before this, it worked fine.

### Platform

```markdown
- Device model: Samsung s8
- CPU architecture: aarch 64
- Android version: Idk, but about 10
- PojavLauncher version: newst gplay version
```

### Anything else?

Nah

**Comment by khanhduytran0** [comment]
> jdk 17

Why did you pick JDK? It’s heavier than JRE but does no more thing, unless you’re going to import an IDE to Pojav for compiling mod.

> Vulkan

Why did you pick it? It’s 10x slower than gl4es. Actually, your crash report stated that gl4es is used instead. **Don't forget to send latestlog.txt instead later.**

[Follow this for 1.18](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04)
