### ISSUE TITLE
[F-Req]Can 1.17 physics mod work?

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2617]
### Is this request related to a bug?

.

### Describe the request.

That would be awesome if its compatible :)

**Comment by khanhduytran0** [comment]
#1948

Have you tried it yourself before submitting this? :eyes:
[physx-jni](https://github.com/fabmax/physx-jni) and [PhysX](https://github.com/NVIDIAGameWorks/PhysX) must be recompiled for Android for this mod.

**Comment by MARnelPH12** [comment]
Is this compatible with the new physics mod?

**Comment by MARnelPH12** [comment]
And how do i use this i dont even know :/
