### ISSUE TITLE
mouse stops working for no reason

### ISSUE THREAD

**Issue by LU5ive** [PojavLauncherTeam/PojavLauncher#2619]
### Describe the bug

so im playing bedwars and suddenly the mouse stops working and i cant walk cuz its walking automaticly for some reason then when i open the exit the menu and go back into the game everything works fine till i get the same problem

### The log file and images/videos

had nothing its a ingame bug

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. go ingame
3. few seconds
4. the bug happens
```

### Expected Behavior

idk what do put here so ill leave it blank

### Platform

```markdown
- Device model: Google Chrome Os/64GB
- CPU architecture: arm32
- Android version: 9
- PojavLauncher version: 3.3.1.1
```

**Comment by SprainedSpark89** [comment]
are you using the touchpad touch screen if you have one or external mouse?
