### ISSUE TITLE
Error during startup 1.16.1

### ISSUE THREAD

**Issue by chapple01** [PojavLauncherTeam/PojavLauncher#262]
GPLv3
![Screenshot_2020-08-02-11-05-04-811_net kdt pojavlaunch](https://user-images.githubusercontent.com/65114293/89118684-3c58b300-d4b0-11ea-8d21-049203dfbe4e.jpg)
![Screenshot_2020-08-02-11-05-12-477_net kdt pojavlaunch](https://user-images.githubusercontent.com/65114293/89118685-3d89e000-d4b0-11ea-8248-145f171a3fb6.jpg)
![Screenshot_2020-08-02-11-05-16-205_net kdt pojavlaunch](https://user-images.githubusercontent.com/65114293/89118687-3e227680-d4b0-11ea-8706-0a2176782e0d.jpg)

**Comment by chapple01** [comment]
Android 10
Xiaomi redmi note 8 pro

**Comment by Doxelix** [comment]
@chapple01 Minecraft 1.11.2 and below is supported.

**Comment by chapple01** [comment]
@dawid563, and 1.16.1? Will there be support? And if it doesn't work, why is it in the selection menu?

**Comment by WesleyVanNeck** [comment]
> @dawid563, and 1.16.1? Will there be support? And if it doesn't work, why is it in the selection menu?

yes were working on it why its in the list why not

**Comment by khanhduytran0** [comment]
Didn't you read the description and README?

**Comment by khanhduytran0** [comment]
@chapple01 @protectoryt use v3.2
