### ISSUE TITLE
[F-Req] Custom path for folders like .minecraft

### ISSUE THREAD

**Issue by BlockyTheDev** [PojavLauncherTeam/PojavLauncher#2620]
### Is this request related to a bug?

Add an option to set a custom path for folders like the `jdk` or `jre` (I don't know which one is used by minecraft) and `.minecraft`.

### Describe the request.

It is useful because my android device only has 64 GB internal storage and because of that I can't use the app. So I want to set the path to my 256 GB SDCard, which has enough space for the app.

**Comment by SprainedSpark89** [comment]
there is a way to do that but you need a folder that takes you to the folder that you want in this case sd card idk how to do it or if it will work on mobile.

**Comment by khanhduytran0** [comment]
Use JRE instead of JDK, as you can’t use Pojav for compiling Java mod.
You may want to take a look at PVC (per-version-config) or the wip profiles changes.

**Comment by BlockyTheDev** [comment]
> Use JRE instead of JDK, as you can’t use Pojav for compiling Java mod. You may want to take a look at PVC (per-version-config) or the wip profiles changes.

IK. I don't want to compile it or mods. I wrote jdk because I din't know which java sort is used in the minecraft environment. The feature request is to set a custom path in the pojav launcher app for folders like .minecraft ..., where they are saved and loaded from.

**Comment by Mathias-Boulay** [comment]
Done.

**Comment by BlockyTheDev** [comment]
Thanks. I will test it when it is available in Google-PlayStore
