### ISSUE TITLE
[BUG] <Dark World on 1.18.1 with Optifine>

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2621]
### Describe the bug

When entering the world on 1.18.1 with Optifine and the Optifine patcher installed: the world is completely dark, the items and the skin in the inventory are also dark!

### The log file and images/videos

![Screenshot_2022-01-13-16-16-20-814_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87223939/151191055-1f738ecf-6f65-4491-906b-695663a3597c.jpg)
![Screenshot_2022-01-13-16-16-11-751_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87223939/151191062-b100996d-d820-47d5-a711-3d9b180075cf.jpg)
![Screenshot_2022-01-13-16-13-24-688_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87223939/151191064-d17d0a0f-1ae3-420e-9991-692ecb39c4b3.jpg)
![Screenshot_2022-01-13-15-47-48-619_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87223939/151191067-bbf03a52-04e0-497d-a1f3-9092128b1394.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start minecraft 1.18 with optifine
3. Join to the server or local world
```

### Expected Behavior

I expect the world to load now and the colors to be normal!

### Platform

```markdown
- Device model: Redmi 10 4/128
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest github version
```

### Anything else?

Renderer: Virgl (on other renders, when entering the world, the game crashes)

**Comment by GoneSubject** [comment]
wait did you put "-Xint" in the jvm argument, look kinda like that

**Comment by andr0d1v** [comment]
My Java arguments are empty!

**Comment by SprainedSpark89** [comment]
Hey try to make the brightness bright but i had that issue but all entities and items in the inventory but half of them like half of one item or entity is dark but it is the older versions.

**Comment by andr0d1v** [comment]
I have the maximum brightness! My version: 1.18.1

**Comment by khanhduytran0** [comment]
Lacks of latestlog.txt moment.

**Comment by SprainedSpark89** [comment]
try reinstalling 1.18 and optifine by going to the .minecraft folder versions
then delete 1.18 and optifine then play normal 1.18 then get optifine 
and get playstore version

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build

**Comment by andr0d1v** [comment]
Where this build!?
