### ISSUE TITLE
[BUG] 1.18 Crashes with GL4ES if VBO enabled

### ISSUE THREAD

**Issue by kl1024** [PojavLauncherTeam/PojavLauncher#2622]
### Describe the bug

Application suddenly crashed with no crash log

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7946873/latestlog.txt)

### Steps To Reproduce

```markdown
1.start Pojavlauncher
2.start 1.18.x with VBO on
3.load a world or join a server
4.PojavLauncher Crashed
```

### Expected Behavior

I expect the game running normally

### Platform

```markdown
- Device model: Mi Note 3 6/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-314-658c937d7-v3_openjdk
```

**Comment by WesleyVanNeck** [comment]
1.18 doesn't need vbo

**Comment by kl1024** [comment]
> 1.18 doesn't need vbo

But it will be laggy without vbo

**Comment by NotAHero04** [comment]
VBO was forced to be enabled since 1.14.

**Comment by kl1024** [comment]
> VBO was force to be enabled since 1.14.

But I can run 1.18 normally without VBO enabled.

**Comment by NotAHero04** [comment]
> But I can run 1.18 normally without VBO enabled.
>
The in-game VBO takes place of the gl4es one when enabled.

**Comment by kl1024** [comment]
> > But I can run 1.18 normally without VBO enabled.
> 
> The in-game VBO takes place of the gl4es one when enabled.

So...the gl4es VBO leads the game to crash?

**Comment by kl1024** [comment]
Sometimes it leaves 'ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)' at the end of latestlog.txt.

**Comment by NotAHero04** [comment]
> So...the gl4es VBO leads the game to crash?
>
How could it make crash when it isn't even enabled at all?

**Comment by NotAHero04** [comment]
Turns out that you are using OptiFine, please check if "Render Regions" (and additionally, "Fast Render") options are enabled.

**Comment by kl1024** [comment]
> Turns out that you are using OptiFine, please check if "Render Regions" (and additionally, "Fast Render") options are enabled.

I disabled them all but it still crashes.

**Comment by SprainedSpark89** [comment]
what happens when you try to disable vbo?

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
