### ISSUE TITLE
[F-Req] Install exes like Minecraft clients iris,badlion client,Lunar client

### ISSUE THREAD

**Issue by Gabbyph12** [PojavLauncherTeam/PojavLauncher#2623]
### Describe the request.

Install functional exe launchers

**Comment by khanhduytran0** [comment]
It is gonna run out of the original scope. **Pojav doesn’t emulate Windows 10!** ~~How do you feel if the launcher takes more gigabytes of storage just for ability to run PC installers?~~. Also x86 ≠ ARM.

**Comment by mchnjt** [comment]
> It is gonna run out of the original scope. **Pojav doesn’t emulate Windows 10!** ~How do you feel if the launcher takes more gigabytes of storage just for ability to run PC installers?~. Also x86 ≠ ARM.

user name: @Gabbyph12 
@Gabby__ph__(WHERE THE FUCK IS UNDERLINE!!!!)12 

ah yes how i love the brain of filipinos

**Comment by Henry-Hiles** [comment]
What?

> > It is gonna run out of the original scope. **Pojav doesn’t emulate Windows 10!** ~How do you feel if the launcher takes more gigabytes of storage just for ability to run PC installers?~. Also x86 ≠ ARM.
> 
> user name: @Gabbyph12 @Gabby__ph__(WHERE THE FUCK IS UNDERLINE!!!!)12
> 
> ah yes how i love the brain of filipinos

**Comment by Gabbyph12** [comment]
Am I look Filipino to you?!

**Comment by mchnjt** [comment]
My bad. You have PH in your name. Sorry

**Comment by Gabbyph12** [comment]
:( nope
