### ISSUE TITLE
[BUG] Red Screen When Joining 1.17 servers

### ISSUE THREAD

**Issue by Gabbyph12** [PojavLauncherTeam/PojavLauncher#2624]
### Describe the bug

Red screen on 1.17 1.18 crashing on servers and can't install exe clients:Badlion,Lunar,Iris

### The log file and images/videos

:(

### Steps To Reproduce

```markdown
:(
```

### Expected Behavior

:(

### Platform

```markdown
- Device model:Realme C12
- CPU architecture:Aarch64
- Android version:11
- PojavLauncher version:Crocus V3 Open3djk
```

**Comment by khanhduytran0** [comment]
> Red screen on 1.17 1.18 crashing on servers 

**We know nothing**. ~~What you provided is repeated BSOD emoji.~~ There’s no data in a single emoji. Please follow the form instruction properly.

> can't install exe clients:Badlion,Lunar,Iris

**Your phone is not a PC.** You should know its limit. It’s like you’re requesting for ability to run SEUS PTGI E12 and ray tracing on your mobile device.
