### ISSUE TITLE
Plss make open4es support for Virglrender

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#2626]
### Describe the bug

Plsss make open4es support for Virglrender because open4es have no lag than PC shader

### The log file and images/videos

Non

### Steps To Reproduce

```markdown
1. Change to Virglrender
2. Start Pojavlauncher
3. Start the game
4. Use open4es shader not working
```

### Expected Behavior

PC shader lag than open4es if have a support for Virglrender

### Platform

```markdown
- Device model: bison umidigi
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest on github
```

### Anything else?

Plss make open4es support for Virglrender

**Comment by NotAHero04** [comment]
Duplicate of #2602.

**Comment by NotAHero04** [comment]
First, Open4Es is obviously designed for gl4es, which will give you more performance than VirGL.
Second, we are not shader developers.

**Comment by WesleyVanNeck** [comment]
how about no

**Comment by mchnjt** [comment]
lmao just put the open4es shaders file in the shaders folder, run minecraft with virgl and select shader, done

**Comment by Mathias-Boulay** [comment]
we don't make virgl, so not really possible
