### ISSUE TITLE
[F-Req] Please Don't use [Caciocavallo] use Wined ((thats the best) >UI< ,And ,>DPI<)

### ISSUE THREAD

**Issue by jethro527** [PojavLauncherTeam/PojavLauncher#2628]

**Comment by khanhduytran0** [comment]
Wine is 1000x heavier than Caciocavallo (160mb vs 160kb). So what’s the use of it? @jethro527

**Comment by CosineMath** [comment]
> Wine is 1000x heavier than Caciocavallo (160mb vs 160kb). So what’s the use of it? @jethro527

(I guess he means window system rather than winehq

**Comment by mchnjt** [comment]
~~lets make pojav bloated with useless size :pogr_moment:~~

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.
