### ISSUE TITLE
New idea!!!

### ISSUE THREAD

**Issue by Malaska678** [PojavLauncherTeam/PojavLauncher#263]
Not About Pojav but About Bedrock edition.. Can you make launcher for mcpe that allows you to run mc bedrock scripts.. It can also allow you to convert mod from java mod to bedrock mod...Can you make it pls :) . (Useful because java mods are better)....

**Comment by Malaska678** [comment]
@khanhduytran0

**Comment by Crandow785** [comment]
This is idea a super!

**Comment by Malaska678** [comment]
@Crandow785

**Comment by Malaska678** [comment]
maybe not

**Comment by WesleyVanNeck** [comment]
not passable
