### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SeNioRHqdi** [PojavLauncherTeam/PojavLauncher#2632]
### Describe the bug

i can't use multiple microsoft accounts in the launcher and we need skin changer in the launcher but when i click at microsoft login it shows up my friends account only 

### The log file and images/videos

 there is no logs

### Steps To Reproduce

```markdown
huh
```

### Expected Behavior

i have wrote it up

### Platform

```markdown
- Device model: chromebook
- CPU architecture: idk
- Android version: idk 
- PojavLauncher version: idk tbh
```

**Comment by mchnjt** [comment]
wheeze

**Comment by SprainedSpark89** [comment]
hey go to settings about chrome os and you can check android version by settings go to where it says google play store press arrow manage android preference go down to system about device and look under android version

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.
