### ISSUE TITLE
I can't load littletiles mod[BUG] <Short description>

### ISSUE THREAD

**Issue by pro14812345** [PojavLauncherTeam/PojavLauncher#2633]
### Describe the bug

Littletiles mod crashes my game and when I put creativecore on my mods folder it blacks my screen

### The log file and images/videos

https://user-images.githubusercontent.com/91519709/151458099-47faabf6-6bc4-4429-a138-47de23772293.mp4

### Steps To Reproduce

```markdown
‌
```

### Expected Behavior

i expected that it loads up normall like how the PC players load it

### Platform

```markdown
- Device model: A12pro 
- CPU architecture: aarch64 
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by pro14812345** [comment]
I saw another people play it on pojav launcher but I can't pls fix this

**Comment by pro14812345** [comment]
Wait, I didn't saw littletiles be on that list, do I get reported?

**Comment by NotAHero04** [comment]
No log file attached

**Comment by mchnjt** [comment]
nice editing 🤡

**Comment by pro14812345** [comment]
> nice editing 🤡
thx

**Comment by pro14812345** [comment]
> No log file attached

Where is log file

**Comment by pro14812345** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7954847/latestlog.txt)
Is it this?

**Comment by pro14812345** [comment]
Also I cut some parts on the vid because it was near 1 minutes, but it's not fake

**Comment by NotAHero04** [comment]
Try using gl4es 1.1.4

**Comment by pro14812345** [comment]
Ok

**Comment by pro14812345** [comment]
It's the same

**Comment by pro14812345** [comment]
is littletiles not supported anymore?

**Comment by pro14812345** [comment]
Only zink is showing the screen but it's on 1 fps

**Comment by NotAHero04** [comment]
Maybe try out the new experimental option in GitHub builds?

**Comment by khanhduytran0** [comment]
Try updating to latest build.

**Comment by khanhduytran0** [comment]
*#1948 seems getting ignored*

**Comment by khanhduytran0** [comment]
> Maybe try out the new experimental option in GitHub builds?

gl4es's overloaded function hack was set to disabled by default in the latest build.

**Comment by pro14812345** [comment]
where do I update to latest build?

**Comment by NotAHero04** [comment]
No, I mean the OpenGL 1 one. This thing worked quite well with some black screen scenarios

**Comment by pro14812345** [comment]
> No, I mean the OpenGL 1 one. This thing worked quite well with some black screen scenarios

how do i get it, is it in the launcher or it's something that I gotta download?

**Comment by pro14812345** [comment]
I'm new to mc java and pojav launcher I just know some things

**Comment by NotAHero04** [comment]
Put the following file to the directory as specified in the picture.
[custom_env.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7955074/custom_env.txt)
![Screenshot_20220128-084558](https://user-images.githubusercontent.com/84689840/151472853-d94c96b2-b886-49b1-9a75-4c711480f12b.png)

**Comment by pro14812345** [comment]
I finally found it, I was searching for that and I realized that for me it was android/data/net.kdt.pojavlaunch/files

**Comment by pro14812345** [comment]
Now I'm gonna try it

**Comment by pro14812345** [comment]
Oh my god u r a genius, bro it's been couple months that I'm just sad and thinking that I never can load it but you helped me thank you so much
