### ISSUE TITLE
when sodium support appears 1 17 1

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2638]
### Is this request related to a bug?

In version 1 17 1 sodium does not work

### Anything else?

when can we expect sodium support at 1 17 1

**Comment by NotAHero04** [comment]
Just use OptiFine for now.

**Comment by ghost** [comment]
optifine and
optifabric
flies to the fabric 1 17 1

**Comment by offbeat-stuff** [comment]
you can use sodium with virglrender for 1.18

**Comment by SprainedSpark89** [comment]
are you using fabric?

**Comment by ghost** [comment]
> are you using fabric?

Yes

**Comment by SprainedSpark89** [comment]
ok
