### ISSUE TITLE
[BUG] <Need help with using versions infdev and older>

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2639]
### Describe the bug

When i try to launch some versions of infdev you can't move the camera other infdev versions you can't play because of crashing and other versions that are older than infdev like indev, and rd they crash almost immediately.
the new issue is you can't use betacraft on pojavlauncher
### The log file and images/videos
i will add it soon
### Steps To Reproduce

```markdown
select a old version like old old example a rd version or indev p.s. indev and infdev are different

indev is in development and infdev is infinite development and these are old versions of minecraft
```

### Expected Behavior

when i start a old version it would behave like it came out (other than the sound)

### Platform

```markdown
- Device model: samsung galaxy tab e
- CPU architecture: idk but the images might help
- Android version: 7.1.1
- PojavLauncher version: play store
- https://user-images.githubusercontent.com/87820585/137610107-deabd417-de01-42fd-b0a2-009185ff5549.jpg
- https://user-images.githubusercontent.com/87820585/137610234-55ba5b7f-f73b-493f-927f-184123a2f31a.jpg
```

### Anything else?

i wonder if pojavlauncher and beta craft could team up to get a mobile port of beta craft.

links to every time i reported these issues

https://github.com/PojavLauncherTeam/PojavLauncher/issues/2371
https://github.com/PojavLauncherTeam/PojavLauncher/issues/2335
https://github.com/PojavLauncherTeam/PojavLauncher/issues/1713

**Comment by mchnjt** [comment]
> i wonder if pojavlauncher and beta craft could team up to get a mobile port of beta craft.

try downloading betacraft's jar and launch it to mod installer, it works ~~just like F3 + C~~

**Comment by SprainedSpark89** [comment]
huh ok?

**Comment by SprainedSpark89** [comment]
but it is a whole different launcher
uh there is a jar?
well that may be a problem
another problem can't launch because can't have a blank username
was it going to launch in the installer window?
checked files there is now a .betecraft folder
renamed accounts.json to accounts.txt 
found username
put in new accounts.json
username there
well that is the problem that i was expecting it tried to launch the game in installer window and when i went to log output pojavlauncher denied it to use java it's kind of close. :-( but so far
