### ISSUE TITLE
[F-Req] <import render>

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2640]
### Is this request related to a bug?

no

### Describe the request.

could you make it so you can import renders like you would java?

**Comment by khanhduytran0** [comment]
How can renderer be imported? ~~like inserting RTX 3090 into a PCI slot and install appropriate driver?~~ and if so, where’s your renderer?

**Comment by SprainedSpark89** [comment]
I thought you could download render i found a link in a old issue that is still a issue https://www.eclipse.org/openj9/

**Comment by mchnjt** [comment]
L

**Comment by mchnjt** [comment]
use native opengles :HYPERROFEL:

**Comment by NotAHero04** [comment]
> I thought you could download render i found a link in a old issue that is still a issue https://www.eclipse.org/openj9/

That's another JVM.

**Comment by SprainedSpark89** [comment]
oh that is jvm my bad
