### ISSUE TITLE
[FFMPEG] FFMPEG binary files to Pojav?

### ISSUE THREAD

**Issue by mchnjt** [PojavLauncherTeam/PojavLauncher#2641]
### Is this request related to a bug?

This has been a hot topic lately but someone got Replay Mod running in Pojav. Wouldn't it be more convenient if binary library files of it are added?

### Describe the request.

Due to how GP removed that so-called "APK Editor", it's hard to find a working one. Others even take this advantage of clickbaiting you and puts you to danger (malware, trojan), and the only current way to run "Replay Mod", is to manually add the FFMPEG library. Kinda a convenience of it has it ready/on-the-go to be used.

### Anything else?

no more.

**Comment by NotAHero04** [comment]
hmm, would be nice to see ~~it being added~~ the app size rises

**Comment by NotAHero04** [comment]
maybe make an option for this?

**Comment by JoeyTheGamer5670** [comment]
Hey, i Have a APK Editor Pro i can send it to you.

**Comment by SprainedSpark89** [comment]
if you edit the app if there is a bad bug you are on your own.

**Comment by NotAHero04** [comment]
@SprainedSpark89 we are not modifying launcher code.

**Comment by SprainedSpark89** [comment]
if your editing minecraft you would not need a apk editor

**Comment by Mathias-Boulay** [comment]
#2572
