### ISSUE TITLE
[BUG] <Game keeps automatically closing>

### ISSUE THREAD

**Issue by Nuska666** [PojavLauncherTeam/PojavLauncher#2642]
### Describe the bug

I hit "play" and no matter how many times I try it keeps automatically closing the game. No error code or anything.

### The log file and images/videos

![image](https://user-images.githubusercontent.com/98632080/151647693-301b8edb-3dc6-4f07-8599-9ff6cfda20b0.png)

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Login with Microsoft
3. Hit play
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: Intel Braswell Chromebook
- Minecraft version: 1.7.10
```

**Comment by mchnjt** [comment]
Insufficient info. How can we fix this while it lacks info?

**Comment by khanhduytran0** [comment]
> ### The log file and images/videos
> ![image](https://user-images.githubusercontent.com/98632080/151647693-301b8edb-3dc6-4f07-8599-9ff6cfda20b0.png)

This image can’t be used to replace latestlog.txt.

**Comment by mchnjt** [comment]
> > ### The log file and images/videos
> > ![image](https://user-images.githubusercontent.com/98632080/151647693-301b8edb-3dc6-4f07-8599-9ff6cfda20b0.png)
> 
> This image can’t be used to replace latestlog.txt.

L

**Comment by SprainedSpark89** [comment]
hey go to the files app then go to the 3 dots then press show all play folders if there is not a check next to it click it then go to play folders you will see it has a android folder or games folder then go find the pojavlauncher folder then go upload the latest log

**Comment by SprainedSpark89** [comment]
i have made a issue to help get latest log on chromebook link https://github.com/PojavLauncherTeam/PojavLauncher/issues/2537

**Comment by Mathias-Boulay** [comment]
most likely fixed in the release candidate
