### ISSUE TITLE
[F-Req] Plss Make pojav launcher android like iOS Ui And iOS pojav launcher control

### ISSUE THREAD

**Issue by Gabbyph12** [PojavLauncherTeam/PojavLauncher#2643]
### Describe the request.

iOS pojav Launcher Ui and Control and touch gestures

**Comment by mchnjt** [comment]
iOS ui interface is simplistic ~~and shit~~, also why tho

**Comment by Gabbyph12** [comment]
Cauze its cool

**Comment by mchnjt** [comment]
> Cauze its cool
Have a look at it
![IMG_20220129_181024](https://user-images.githubusercontent.com/83752061/151656967-5c38a4d2-ccea-4f3d-9e67-6b0a2f68221d.jpg)

**Comment by mchnjt** [comment]
![IMG_20220129_181032](https://user-images.githubusercontent.com/83752061/151656978-f50ed154-d1cf-4c0d-9e75-ff10824e871e.jpg)

**Comment by mchnjt** [comment]
try to cry at how simplistic it is

**Comment by khanhduytran0** [comment]
@rscDoesMoreTrolling The UI for PojavLauncher iOS didn’t end here. It’s currently made simple to eat **as less VRAM as possible**. as I don’t have a proper app to check for it.

It’s like you want to revert PojavLauncher design to 2/3 years ago. What do you think? @Gabbyph12

**Comment by Gabbyph12** [comment]
Yes, I agree.

**Comment by khanhduytran0** [comment]
> Yes, I agree.

How do you even agree to revert our work?

**Comment by Gabbyph12** [comment]
What do you mean?

**Comment by mchnjt** [comment]
> @rscDoesMoreTrolling The UI for PojavLauncher iOS didn’t end here. It’s currently made simple to eat **as less VRAM as possible**. as I don’t have a proper app to check for it.
> 
> It’s like you want to revert PojavLauncher design to 2/3 years ago. What do you think? @Gabbyph12

L for me then

**Comment by Mathias-Boulay** [comment]
Won't be done

**Comment by Gabbyph12** [comment]
Why?

**Comment by Gabbyph12** [comment]
Make joystick

**Comment by khanhduytran0** [comment]
> Make joystick

iOS version doesn't have a joystick ~~till iOS 14 but it isn't used by the launcher~~. Use the `Swipeable` toggle in the button for it.

Also, how does Minecraft properly support joystick? There's no way to do both movements (such as go left + go forward) at the same time but with different speed.

**Comment by mchnjt** [comment]
> Won't be done

thank you

**Comment by Gabbyph12** [comment]
It's hard so plsss make joystick

**Comment by mchnjt** [comment]
> It's hard so plsss make joystick

@Gabbyph12 
Minecraft uses WASD movement, not multidirectional movement. W for forward, A for left, S for backward, and D for right. You can do left-forward, right-forward, left-backward(?), and right-backward(?). However, the naturity of joysticks won't probably apply due to joystick movements based on movement speed, which Minecraft doesn't (probably, again) use. Crouch movement and speed-up(running) movement(forward movement only) doesn't also apply.

Note that this is only based on my theory, and i do not condone anyone to stop hoping for joystick in pojav.

**Comment by NotAHero04** [comment]
These are just brainless requests. If you really want joystick, ask Mojang for proper support first.
