### ISSUE TITLE
[BUG] <white screen appears while playing forge mods>

### ISSUE THREAD

**Issue by Sukhman2022** [PojavLauncherTeam/PojavLauncher#2645]
### Describe the bug

White screen appears while selecting or playing forge mods with optifine. I am playing immersive railroading.

### The log file and images/videos

![Screenshot_2022-01-29-17-44-15-719_net kdt pojavlaunch](https://user-images.githubusercontent.com/98396777/151662603-c240fd20-1908-4ddb-8e82-024f3ef851ee.jpg)

### Expected Behavior

I expected that it would work perfectly but it stucked

### Platform

```markdown
- Device model: Redmi note 5 pro
- CPU architecture: octa core max 1.80ghz
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

No able place anything of mod

**Comment by Sukhman2022** [comment]
![Uploading Screenshot_2022-01-29-18-57-53-725_com.android.settings.jpg…]()

**Comment by khanhduytran0** [comment]
Log file was not found. An image cannot be used to replace the log file.
Steps to Reproduce is invalid.

**Comment by Sukhman2022** [comment]
How I send the file tell

**Comment by Sukhman2022** [comment]
Please tell i want to play immersive railroading

**Comment by khanhduytran0** [comment]
> How I send the file tell
> […](#)

It’s literally the place that you used to send image, but it accept files aswell.

**Comment by Sukhman2022** [comment]
What do you mean?
Tell properly
Do I have to send all log files or image of the bug log files

**Comment by Sukhman2022** [comment]
Sorry for disturbance. I am really sorry

**Comment by khanhduytran0** [comment]
> What do you mean? Tell properly Do I have to send all log files or image of the bug log files

The issue form told everything already, just because you didn't read them completely+carefully.

**Comment by Sukhman2022** [comment]
![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7975542/latestlog.txt)

**Comment by Sukhman2022** [comment]
Hey developer I have sent the log

**Comment by SprainedSpark89** [comment]
that is a lot of mods

android 9?

lol sorry the latest log has a funny error

"
[20:34:18] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.ModCore:info:358]: INFO: Attempting to detect optifine...
[20:34:18] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.ModCore:warn:370]: WARN: ===========================================================================
[20:34:18] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.ModCore:warn:370]: WARN:              DETECTED OPTIFINE, PATCHING CRAP THAT IT BROKE...             
[20:34:18] [Render thread/INFO] [STDOUT/]: [cam72cam.mod.ModCore:warn:370]: WARN: 
"
you should take all of the mods off other than OPTIFINE if it doesn't launch take optifine or redownload it

**Comment by Sukhman2022** [comment]
It is caused by the mods or optifine

**Comment by khanhduytran0** [comment]
There might be improperly handled shader. Try switching renderer.

**Comment by Sukhman2022** [comment]
Which renderer

**Comment by Sukhman2022** [comment]
![Screenshot_2022-02-02-09-51-15-272_net kdt pojavlaunch](https://user-images.githubusercontent.com/98396777/152092634-aab3727a-87d0-4bc2-b8bd-a977d3a705c4.jpg)

**Comment by khanhduytran0** [comment]
Try VGPU.

**Comment by Sukhman2022** [comment]
Not worked

![Screenshot_2022-02-02-11-02-35-078_net kdt pojavlaunch](https://user-images.githubusercontent.com/98396777/152098566-9e529432-ce4c-42da-95ce-0932a62c6c2c.jpg)

**Comment by Sukhman2022** [comment]
Including all mods

**Comment by Sukhman2022** [comment]
![Screenshot_2022-02-02-11-04-05-466_com mi android globalFileexplorer](https://user-images.githubusercontent.com/98396777/152098618-884242a1-8a07-4e15-8642-70df4e3944fc.jpg)

**Comment by Sukhman2022** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7983806/latestlog.txt)

Sending you again if you could help then please help me

**Comment by Sukhman2022** [comment]
The problem is with track api mod or immersive railroading mod

**Comment by Sukhman2022** [comment]
Hey  spraind spark I am having these specs in my phone

![Screenshot_2022-02-02-16-29-57-335_com android settings](https://user-images.githubusercontent.com/98396777/152141597-405db365-0f14-4b93-b655-cd24a28e129a.jpg)

**Comment by SprainedSpark89** [comment]
ok try uninstall all but optifine

**Comment by Sukhman2022** [comment]
It means I can't play any mod

**Comment by Sukhman2022** [comment]
I have only download this pojav launcher to play mods

**Comment by Sukhman2022** [comment]
I have deleted performant and mcmt mod

**Comment by Sukhman2022** [comment]
Do i have to delete all

**Comment by SprainedSpark89** [comment]
just move them for now to a folder like downloads then open forge see if it works if it does equip another mod then see if it works if it does then put it back in the folder and repeat until you find the problem if there is no problems you may have at least 2 mods that don't work together and make sure that the packs are up to date

**Comment by Sukhman2022** [comment]
The forge is working properly

**Comment by Sukhman2022** [comment]
With optifine

**Comment by Sukhman2022** [comment]
Now it is craving i uninstalled all now I have to install latest

![Screenshot_2022-02-04-08-31-28-553_net kdt pojavlaunch](https://user-images.githubusercontent.com/98396777/152466013-594defc2-ca0a-4b18-99ef-fdbe1f055623.jpg)

**Comment by Sukhman2022** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7999846/latestlog.txt)



Please chech is there any problem in this

**Comment by Sukhman2022** [comment]
Ok I will try

**Comment by Sukhman2022** [comment]
By using this method it starts crashing

**Comment by Sukhman2022** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8000679/latestlog.txt)

**Comment by Sukhman2022** [comment]
[crash-2022-02-04_06.17.01-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8000687/crash-2022-02-04_06.17.01-client.txt)

**Comment by SprainedSpark89** [comment]
do it on a new world

**Comment by Sukhman2022** [comment]
Ok

**Comment by Sukhman2022** [comment]
Nothing happened

**Comment by Sukhman2022** [comment]
Crashing again

**Comment by Sukhman2022** [comment]
Nothing happened

**Comment by Sukhman2022** [comment]
Remaining same

**Comment by SprainedSpark89** [comment]
ok try downloading and installing new optifine

**Comment by Sukhman2022** [comment]
Now I uninstalled and again reinstall the pojav launcher

**Comment by Sukhman2022** [comment]
[crash-2022-02-10_06.24.42-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8038638/crash-2022-02-10_06.24.42-client.txt)


Now the game is crashing with code -1

**Comment by Sukhman2022** [comment]
![IMG20220210204214](https://user-images.githubusercontent.com/98396777/153438148-b3e6726e-994c-4177-8ae9-bd9b2d556180.jpg)
![IMG20220210204118](https://user-images.githubusercontent.com/98396777/153438168-2557510c-7bd2-4c6c-a364-a8c3aeff53b9.jpg)
![IMG20220210204020](https://user-images.githubusercontent.com/98396777/153438178-4dc2a96f-ee40-4384-b474-c6b1f7e2ffdb.jpg)

**Comment by Sukhman2022** [comment]
Why it showing that name and I'd not be blank

**Comment by Sukhman2022** [comment]
It is issue with what

**Comment by SprainedSpark89** [comment]
well realms i don't know how it works but i guess it loads it and are you using a emulator?

**Comment by Sukhman2022** [comment]
No emulator is used by me. i am playing in pojav launcher

**Comment by Sukhman2022** [comment]
Android

**Comment by mchnjt** [comment]
> 

buy Minecraft you dumbass

**Comment by khanhduytran0** [comment]
> Why it showing that name and ID not be blank

Basically, Mojang is trying to stop you from playing the full game for free. Buy the game to fix it. Check #2679 for more info.

**Comment by mchnjt** [comment]
close issue moment

**Comment by khanhduytran0** [comment]
Report broken mods in #1948

**Comment by Sukhman2022** [comment]
Thanks for your support i buyed the game now all mods are working fine. I
am playing in Mac Book pro
