### ISSUE TITLE
[F-Req] Assets redownload 

### ISSUE THREAD

**Issue by Veldia08** [PojavLauncherTeam/PojavLauncher#2646]
### Describe the request.

Hi i have a request, if possible can you make it so assets can be redownloaded as earlier i was downloading the assets when suddenly my internet gone and the download stopped i can't redownload it as the launcher just play the game, resulting the game always crash in the loading screen, i know i can just reinstall the launcher to fix it though it would be more fast if there are assets redownload button

**Comment by mchnjt** [comment]
L

**Comment by Veldia08** [comment]
lmao

**Comment by SprainedSpark89** [comment]
just delete the version and then play and it should download the assets

**Comment by Veldia08** [comment]
> just delete the version and then play and it should download the assets

Thanks never know that, though it know done so i probably need to close this issue

**Comment by Veldia08** [comment]
But then again it would be faster

**Comment by SprainedSpark89** [comment]
not all of the time
