### ISSUE TITLE
[BUG] Fabric Loader 1.17.1 Stuck on Loading Screen

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#2647]
### Describe the bug

Yes Ik Videos or Photos does nothing but i want to show this bug 
Mods in my Mod Folder
1.Adorn 1.17.1 Fabric.jar
2.fabric api 1.17.1 jar
3. Fabric Language Kotlin 1.17.1 jar
4. Modmenu 1.17.1 jar

### The log file and images/videos

https://user-images.githubusercontent.com/87040006/151668613-f1e9a59c-ece2-4a6a-9966-33eaa0da670f.mp4

### Steps To Reproduce

```markdown
1.Open Pojavlauncher
2. Set Runtime To Jre 17
3. set renderer to gl4es 1.1.5(OpenGl ES 3)exports OpenGL 2.1+ Partial 3.2 (no 1.17 supported yet)
4.Launch Pojavlauncher
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: Latest from Github Build
```

### Anything else?

.

**Comment by khanhduytran0** [comment]
> Yes Ik Videos or Photos does nothing but i want to show this bug

Then do you know what does the log do?

**Comment by Jamespoxdxdxd** [comment]
> > Yes Ik Videos or Photos does nothing but i want to show this bug
> 
> Then do you know what does the log do?

ummm to know and to fix whats the problem??

**Comment by Jamespoxdxdxd** [comment]
pls how do i fix this

**Comment by khanhduytran0** [comment]
Log file can be attached through the send image button.

**Comment by Jamespoxdxdxd** [comment]
> Log file can be attached through the send image button.
Yes Ik that

**Comment by Jamespoxdxdxd** [comment]
but how do i fix this?

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
