### ISSUE TITLE
[BUG] 1.18.1 infinity load fabric and optifine

### ISSUE THREAD

**Issue by 51nya51** [PojavLauncherTeam/PojavLauncher#2655]
### Describe the bug

i can’t do anything because minecraft optifine and fabric always try to load the menu at startup 

### The log file and images/videos

nothing, it's just that he constantly tries to load the menu and so on endlessly 

### Steps To Reproduce

```markdown
1.start launcher
2.running minecraft 1.18.1 optifine or fabric 
3.menu endless loading
```

### Expected Behavior

I do not know 

### Platform

```markdown
- Device model: samsung galaxy note 10 lite
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: latest debug
```

### Anything else?

i dont know how to fix it

**Comment by 51nya51** [comment]
with the regular version 1.18.1 exactly the same

**Comment by SprainedSpark89** [comment]
try a older version

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.
