### ISSUE TITLE
[BUG] newest debug version always reverts to 1.7.10

### ISSUE THREAD

**Issue by screret** [PojavLauncherTeam/PojavLauncher#2658]
### Describe the bug

When i start the game on the newest debug version, it always reverts back to starting 1.7.10.

### The log file and images/videos

![Screenshot_20220131-115211](https://user-images.githubusercontent.com/68943070/151772487-684353f7-39f1-4721-b50c-bd532f3c9ff8.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7969765/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Download 1.18.1
3. Run 1.18.1
4. It either throws an error or launches 1.7.10, depending on if you have it installed.
```

### Expected Behavior

It would run 1.18.1

### Platform

```markdown
- Device model: oneplus nord N10 5G
- CPU architecture: aarch64
- Android version: android 11
- PojavLauncher version: latest debug release
```

**Comment by screret** [comment]
Turned out this just suddently doesn't happen anymore.

**Comment by jojos38** [comment]
Only happens when you don't press the "Keep login info" on the login page

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.
