### ISSUE TITLE
[BUG] <Pojav app debug crash versions 1.18.1

### ISSUE THREAD

**Issue by Mohammmed12323** [PojavLauncherTeam/PojavLauncher#2659]
### Describe the bug

Application Exited With Game Code 1

### The log file and images/videos

![Screenshot_20220131-115413~2](https://user-images.githubusercontent.com/98740463/151772948-03efd9e5-96aa-40aa-bca6-768f2af626a7.png)

### Steps To Reproduce

```markdown
1 start pojav
2 login
3choose 1.18.1
4prees play
5 game crashes
```

### Expected Behavior

I expect it to work 

### Platform

```markdown
- Device model: Nokia 6.2
- CPU architecture: aarch64
- Android version:10 
- PojavLauncher version: lastest
```

### Anything else?

Please help

**Comment by offbeat-stuff** [comment]
follow official guide:
https://pojav.ml/index.php/Running_1.17_and_above

**Comment by h266579110** [comment]
> follow official guide: https://pojav.ml/index.php/Running_1.17_and_above

I have same issue, but official guide website is down.

**Comment by ghost** [comment]
Please look at the other issues and solutions for this issue. 
https://pojavlauncherteam.github.io/updates/117.html 

Read "Note for Minecraft 21w37a+ on Android (thanks to NotAHero04)".

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.
