### ISSUE TITLE
U Need to know this little Success!!!

### ISSUE THREAD

**Issue by Malaska678** [PojavLauncherTeam/PojavLauncher#266]
@khanhduytran0 I See that the first 1.12 snapshot worked. I modify ..json file to make it look like 1.12 Also Rename File for that version to 1.12 and also rename .jar. 😈😈😈 Install optifine 1.12 and it improved the performance 😁😁😁. Work with all device....

**Comment by Malaska678** [comment]
Here the proofb
![Screenshot_2020-08-03-23-20-04-89](https://user-images.githubusercontent.com/68141607/89198594-0286ca00-d5e0-11ea-9632-347978245d1e.jpg)

**Comment by Malaska678** [comment]
@khanhduytran0 pls read it

**Comment by WesleyVanNeck** [comment]
do lying to poeple and say its 1.12 isnt good do

**Comment by khanhduytran0** [comment]
Well the full 1.12.2 even worked here https://youtu.be/x4NqraSAOmI

**Comment by khanhduytran0** [comment]
It's one of success
![image](https://user-images.githubusercontent.com/40482367/89243846-2de4d580-d62f-11ea-9933-c516be2654cc.png)

**Comment by khanhduytran0** [comment]
I will close now

**Comment by khanhduytran0** [comment]
Also 1.11+ only works in Android 7+(?)
