### ISSUE TITLE
No virtual ram support

### ISSUE THREAD

**Issue by JoeyTheGamer5670** [PojavLauncherTeam/PojavLauncher#2660]
### Is this request related to a bug?

No

### Describe the request.

I want it support virtual ram for those who have low ram like me

### Anything else?

.

**Comment by NotAHero04** [comment]
Does your device support swapping then?

**Comment by SprainedSpark89** [comment]
i think it does but it uses memory

**Comment by mchnjt** [comment]
how to swap 🥶🥶🥶🥶
