### ISSUE TITLE
[BUG] Virgl glitching menu

### ISSUE THREAD

**Issue by imjustpenguin** [PojavLauncherTeam/PojavLauncher#2662]
### Describe the bug

When i use Virgl renderer it error and not working but yesterday i playing in virg lwith shader but now i cant use  virgl anymore :(

### The log file and images/videos

![Screenshot_20220201_154759](https://user-images.githubusercontent.com/96688215/151930997-cf7261b6-a34b-4aef-ae76-d6492b50d4b7.jpg)
Thats the bug

### Steps To Reproduce

```markdown
1.start pojav launcher use virgl open minecraft but theres no mojang screen and glitching menu
```

### Expected Behavior

nope

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: chrome
```

### Anything else?

no

**Comment by imjustpenguin** [comment]
![Screenshot_20220131_190357](https://user-images.githubusercontent.com/96688215/151931584-5a599395-fdd5-4fba-bf97-ff56e8f72a8a.jpg)
This is me playing with shader:)

**Comment by imjustpenguin** [comment]
![Screenshot_20220201_154759](https://user-images.githubusercontent.com/96688215/151931634-9456e27b-7e13-47a3-91a8-70e8b9ec0b25.jpg)
This is me now :(

**Comment by imjustpenguin** [comment]
I cant play when i press play its freezing

**Comment by imjustpenguin** [comment]
Pls help

**Comment by SprainedSpark89** [comment]
Hey delete 1.12.2 then play it and it will redownload it and if it happens again tell me.
The render shouldn't affect the textures and is there a texture pack if so unequip it.

**Comment by imjustpenguin** [comment]
Ok thanks 😃

**Comment by imjustpenguin** [comment]
My 1.12.2 is fine :) but my optifine 1.12.2 is still glitching

**Comment by imjustpenguin** [comment]
Oh

**Comment by imjustpenguin** [comment]
Thankd

**Comment by imjustpenguin** [comment]
Its working

**Comment by imjustpenguin** [comment]
![Screenshot_20220202_120515](https://user-images.githubusercontent.com/96688215/152091498-e153723f-2e8c-408f-9303-fda7b8ad9f6c.jpg)
Yay i can play :) thanksss

**Comment by imjustpenguin** [comment]
![Screenshot_20220202_125332](https://user-images.githubusercontent.com/96688215/152095922-96a07a68-9ac1-4736-b25e-670b01c34190.jpg)
Thank you so much :)))

**Comment by SprainedSpark89** [comment]
welcome and also the back arrow does the same thing as esc and your device must be a beast how much fps?

**Comment by SprainedSpark89** [comment]
and turn off vbos last time i looked pojavlauncher didn't support it

**Comment by SprainedSpark89** [comment]
you can close this now :-)

**Comment by imjustpenguin** [comment]
Ok i have 10 fps with shader and with no shader i have 135fps

**Comment by SprainedSpark89** [comment]
well my device must be garbage for java i can't run 1.16.5 that well but optifine won't boot

**Comment by SprainedSpark89** [comment]
but it doesn't matter i just want to play alpha 1.0 and older they will not run :-(

**Comment by imjustpenguin** [comment]
I have only 1gb

**Comment by imjustpenguin** [comment]
And my second phone is 2gb

**Comment by imjustpenguin** [comment]
My 2gb phone is working with shaders yay

**Comment by SprainedSpark89** [comment]
ok

**Comment by SprainedSpark89** [comment]
had you played a alpha version?

**Comment by imjustpenguin** [comment]
No

**Comment by SprainedSpark89** [comment]
try a old version go to settings then go down check snapshots old beta and old alpha go to versions go to the bottom then find rd-132211 then play it

**Comment by imjustpenguin** [comment]
![Screenshot_20220203_191056](https://user-images.githubusercontent.com/96688215/152446012-1ef05d06-a714-4ceb-b310-c841f3035928.jpg)
Im not lagging im fine

**Comment by imjustpenguin** [comment]
And if you want my keyboard you can get it

**Comment by imjustpenguin** [comment]
Here https://www.mediafire.com/download/m6ryrh2u8j8m4j2 the button size must be 115

**Comment by imjustpenguin** [comment]
I just copy the keyboard in ios version of pojav launcher https://youtu.be/JbZPIcBQooE
And this 
![Uploading Screenshot_20220131_190335.jpg…]()

**Comment by LuisReyes234723** [comment]
Donde consigo la textura?
