### ISSUE TITLE
Batmod crashes 

### ISSUE THREAD

**Issue by tigerbrocode** [PojavLauncherTeam/PojavLauncher#2668]
### Describe the bug

It just crashes

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7994473/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install 1.8.9
2. Install batmod
3. run it
```

### Expected Behavior

I expect it to launch

### Platform

```markdown
- Device model: samsung M51 6/128g
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest release
```

**Comment by khanhduytran0** [comment]
```
Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
```
We have gotten a lot of reports about this error recently. They said it worked before but then it crashed with the same error (but on Forge with Pixelmon). Please let us know what account type are you using.

**Comment by NotAHero04** [comment]
BatMod will crash anyway because of Discord RPC integration.

**Comment by khanhduytran0** [comment]
#2679
