### ISSUE TITLE
game kept crashing when joining world

### ISSUE THREAD

**Issue by MistyStory1** [PojavLauncherTeam/PojavLauncher#2669]
### Describe the bug

I installed halogen mod(forge version of sodium),game kept crashing when joining world,I turned off the compact vertex format and fog occlusion,but the game still kept crashing when joining world,I.also tried to change video renderer,still didn't work,then I uninstalled pojavlauncher,reinstall pojavlauncher,then redownloaded mc 1.16.5 and its forge(I deleted all mods),still kept crashing,but the game works fine if  I play 1.16.5 vanilla

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/7995127/latest.log)

### Steps To Reproduce

```markdown
1. open pojavlauncher
2.select 1.16.5-forge
3.launch mc
4.click single player
5.join a world
6.wait for world load
6.game crashes
```

### Expected Behavior

I expected I can join the world successfully

### Platform

```markdown
- Device model: huawei nova 6 s 8/128G
- CPU architecture: i don't know
- Android version: 10
- PojavLauncher version: crocus-317-fb7a4b240-v3_oprnjdk
```

**Comment by MistyStory1** [comment]
I also tried to restart my phone but it didn't work

**Comment by khanhduytran0** [comment]
`Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank`
We have gotten a lot of reports about this error recently. Please let us know what account type are you using.

> Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null

This look like you were playing with offline account. Try switching to Mojang/Microsoft account.

**Comment by SprainedSpark89** [comment]
sodium is for fabric https://www.curseforge.com/minecraft/mc-mods/sodium this is the version you used https://www.curseforge.com/minecraft/mc-mods/sodium-reforged
that is Magnesium

**Comment by Sleepylkelvin** [comment]
I tried to log in with Microsoft but still don't work and I also have the same issue with mods and forge also I'm using SamsungA20

**Comment by Sleepylkelvin** [comment]
I install epic fight mod and when going into the world it just popped *game exit*

**Comment by khanhduytran0** [comment]
#2679
