### ISSUE TITLE
add more versions of java

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2672]
### Is this request related to a bug?

ya kind of

### Describe the request.

could you add older versions of java so people can run old versions of minecraft

### Anything else?

this would help a lot

**Comment by khanhduytran0** [comment]
Running alpha/beta in old Java version doesn’t mean it would work without issues. These were made for PC and these had a lot of PC-dependent at that time, also how these are tagged **alpha/beta**, which were never stable.

**Comment by khanhduytran0** [comment]
Duplicate of #2335

**Comment by SprainedSpark89** [comment]
'-'
Looks like i need to get betacraft working just need it to launch the game

**Comment by khanhduytran0** [comment]
We may consider looking at betacraft integration then 🤔

**Comment by SprainedSpark89** [comment]
hey there is no issue with alpha and beta what the problem is that older versions older than alpha and beta the older java and maybe add a older java 8 they talk about it in discord they have to use a older version https://betacraft.uk/

**Comment by SprainedSpark89** [comment]
and some versions i downloaded from omiarchive, and minecraft fandom
the links to omiarchive are on bugmancx how to run old versions of minecraft

**Comment by SprainedSpark89** [comment]
and betacraft works fine in the launcher https://github.com/PojavLauncherTeam/PojavLauncher/issues/2663

**Comment by SprainedSpark89** [comment]
@khanhduytran0
also could you look at the old issue i made like a year ago? https://github.com/PojavLauncherTeam/PojavLauncher/issues/1713
