### ISSUE TITLE
[BUG] Forge MouseEventHandler Crash

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#2674]
### Describe the bug

This doesnt make any sense i just Launch my Forge 1.16.5 36.20 then i make a new world and its just crash its always saying MouseEventHandler I played this mods like 1 day ago and its completely fine but now its just crashes repeatedly:(
My Mods in my Mods Folder:
1.cfm-7.0pre22-1.16.3.jar (Mrcrayfish Furniture Mod 1.16.5)
2.modernlife-1.16.5-1.20.jar
3.obfuscate-0.6.2-1.16.3.jar
4.Optifine_1.16.5_HD_U_G8.jar
5.worldedit-mod-7.2.5-dist.jar

### The log file and images/videos

[crash-2022-02-04_00.07.40-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7999082/crash-2022-02-04_00.07.40-client.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Launch Forge 1.16.5
3. Make a New World
4. Its just Crashes
```

### Expected Behavior

I expect to get a normal play just like 1 day ago

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: latest from Play store
```

### Anything else?

.

**Comment by khanhduytran0** [comment]
`Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank`
We have gotten a lot of reports about this error recently. Please let us know what account type are you using. Also, please send latestlog.txt.

**Comment by Jamespoxdxdxd** [comment]
> `Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank` We have gotten a lot of reports about this error recently. Please let us know what account type are you using. Also, please send latestlog.txt.

im using a offline acc

**Comment by Jamespoxdxdxd** [comment]
> `Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank` We have gotten a lot of reports about this error recently. Please let us know what account type are you using. Also, please send latestlog.txt.

[Uploading crash-2022-02-04_00.07.40-client.txt…]()

**Comment by Jamespoxdxdxd** [comment]
there

**Comment by NotAHero04** [comment]
The upload process hasn't been finished. Also send latestlog.txt instead.

**Comment by khanhduytran0** [comment]
#2679
