### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by hongnan01** [PojavLauncherTeam/PojavLauncher#2678]
### Describe the bug

If you run forge 1.18.x. You always get game software exit with code 1
But,I read log when running I find main error when running.Like this''java.lang.module.FindException: Module cpw.mods.securejarhandler not found, required by cpw.mods.bootstraplauncher''
It meaning we lost a lib when make java runtime cow.mods.securejarhandler
This make can't running forge1.18

### The log file and images/videos

![Uploading Screenshot_20220204_092042_net.kdt.pojavlaunch.debug.jpg…]()

### Steps To Reproduce

```markdown
1.start Pojavluncher
2.select forge 1.18.1
3.run forge 1.18.1 using runtime jre17
4.before the code watch the log 
5.bug find
```

### Expected Behavior

forge 1.18.x running 

### Platform

```markdown
- Device model: HUAWEI SCW-W09
- CPU architecture: Krlin 980
- Android version: 10
- Harmony OS version :2.0.0.225(c00e160R1P160)
- PojavLauncher version: crocus -317-fb7a4b240-v3_ openjdk
```

**Comment by khanhduytran0** [comment]
Forge 1.17+ are currently unsupported. Closing due to duplicated issue.

**Comment by hongnan01** [comment]
So why can't Running Forge 1.18

**Comment by hongnan01** [comment]
It very clear about runtime
