### ISSUE TITLE
[BUG] Crashes on joining world with Fabric/Forge + Offline account

### ISSUE THREAD

**Issue by khanhduytran0** [PojavLauncherTeam/PojavLauncher#2679]
### Describe the bug

We have got a lot of reports about getting crash while joining world with Forge + offline account recently (see #2668, #2669, #2674):
- `Shutting down internal server` might displays before crash.
- `java.lang.IllegalArgumentException: Name and ID cannot both be blank` is found in the latestlog.txt and the crash report.
- Game exited with code 1(?)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8000615/latestlog.txt)
Tested version: 1.16.5 Forge 36.2.26
Highlighted point:
```
java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:192)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:179)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1799)
```

As the stack trace says, it seems that the authentication server returned an empty profile when an invalid access token is sent to the server. In this case, offline account doesn’t hold a valid access token.

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Install Forge (any versions?)
3. Login with an offline/local account.
4. Launch the installed Forge.
5. Enter a world.
```

### Expected Behavior

The game should launch with an offline account.

### Platform

```markdown
- Device model: Any
- CPU architecture: Any (mine: x86_64)
- Android version: Any (mine: Android 9)
- PojavLauncher version: Any (mine: commit fb7a4b2)
```

### Anything else?

It seems Mojang authentication system has changed as explained above, lead to broken offline account support as expected (probably they are trying to stop people playing full Minecraft for free). There are some ways to get around this ~~bug~~:
- *[Removed solution]*
- Login with an online account <- **recommended**

~~Note that I haven’t tried with joining server, please let me know below if the problem happens while joining server.~~
**Update**: the problem doesn’t happen in multiplayer.

Anyways, this is another reason for the offline account to be replaced with local account soon. **You should buy the game before playing it** (unless you’re going to play demo mode).

**Comment by RadiatedExodus** [comment]
:+1: Buy an online account! Stop relying on offline account because it's gonna get replaced eventually.

**Comment by MistyStory1** [comment]
thanks!problem solved!

**Comment by Jamespoxdxdxd** [comment]
Oh i see but you guys are going to replace the offline acc as local acc? Is this means that we have to pay to play this game? To play it fully or not?

**Comment by KEN66I** [comment]
I don't understand how to do a solution for crash forge 1.16.5 when I enter the world.

**Comment by mchnjt** [comment]
THIS is what a real bug report should look like, not those brainless stupid "help me" issues

**Comment by peigenxiansheng** [comment]
emm，所以老子不能愉快游玩pojav了？

**Comment by NotAHero04** [comment]
> Oh i see but you guys are going to replace the offline acc as local acc? Is this means that we have to pay to play this game? To play it fully or not?

Always has been.

**Comment by NotAHero04** [comment]
UPDATE: Fabric is now known to be affected by this change. It's still unknown whether this change targets 1.17+ or not.
[Sample log file](https://cdn.discordapp.com/attachments/724163890803638277/940621453315944498/latestlog.txt)

**Comment by mchnjt** [comment]
Bhai. Pirates 👌😂

**Comment by kedrick021** [comment]
Fuck turn off all your data or wifi and try again stupid

**Comment by Voiasis** [comment]
![frpirate](https://cdn.discordapp.com/emojis/779430630857244712.png) ![frmad](https://cdn.discordapp.com/emojis/904894017865674812.gif)

**Comment by XavierErrorLog** [comment]
This seems very dumb to pay for an app that it's very likely to crash 88% of the time and I have a Samsung galaxy tablet which literally is a beast so unless you guys are going broke. I see no reason for this change might as well move to an older version just to play the game smh.

**Comment by khanhduytran0** [comment]
> This seems very dumb to pay for an app that it's very likely to crash 88% of the time and I have a Samsung galaxy tablet which literally is a beast so unless you guys are going broke. I see no reason for this change might as well move to an older version just to play the game smh.

You’re paying for Mojang/Microsoft, not us. Also, it’s a PC game running on mobile after all, so what do you expect? Stability is a thing, but it depends on user settings.

> I see no reason for this change might as well move to an older version just to play the game smh.

Do you want Microsoft to sue us? If so, go ahead. As I said, offline account will be removed, **closing the door for pirates**. Support for pirates will also be dropped then.

**Comment by XavierErrorLog** [comment]
I just decide to get an account having which was probably for the best I agree I would not want to get sued by Microsoft I am in no way mad at you guys more on the way the sudden change happen at a not so good time but this is Microsoft we're talking about and they don't care about us anyways assuming if you already brought an account you just turn of your wifi if you're still having the same situation or problem? Plus I'm using the new version not the play store I think it was called CI something I forgot sorry.In other words, I'm sorry

**Comment by namcring** [comment]
my problem has been solved

**Comment by BeJohnsonSentosa12** [comment]
> 

I Don't have online Account

**Comment by sbgigapsec** [comment]
then  play minecraft pocket edition

**Comment by huoguo520** [comment]
> 👍购买一个在线帐户！停止依赖离线帐户，因为它最终会被替换。

No💵😧

**Comment by huoguo520** [comment]
> 👍购买一个在线帐户！停止依赖离线帐户，因为它最终会被替换。

No💵😧

> 👍购买一个在线帐户！停止依赖离线帐户，因为它最终会被替换。

No💵😧

**Comment by Thollp** [comment]
> 👍 Buy an online account! Stop relying on offline account because it's gonna get replaced eventually.

No

**Comment by huoguo520** [comment]
Mainly because it is too expensive and has no money.😂












爆炒火锅
***@***.***


---Original---
From: ***@***.***&gt;
Date: Sun, Apr 3, 2022 14:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PojavLauncherTeam/PojavLauncher] [BUG] Crashes on joining world with Fabric/Forge + Offline account (Issue #2679)




  
👍 Buy an online account! Stop relying on offline account because it's gonna get replaced eventually.
  
No

**Comment by Kelvin10858** [comment]
Maybe can turn off your wifi.

**Comment by Forever-Qinghui** [comment]
Can you make a Yggdrasil-logging-in?Perhaps it will solve this problem in a better way.

**Comment by Forever-Qinghui** [comment]
I have a question, if Mojang really changed the login mode, then why don't the other launchers, such as Mio-Ultimate, not have that problem?

**Comment by EnderPluser** [comment]
i have the same problem, just crash in Forge 1.12.2 and i do have an Minecraft account

**Comment by Tiger56c** [comment]
And 1.12.2 it crash at offline account

**Comment by Tiger56c** [comment]
Forge

**Comment by Mathias-Boulay** [comment]
offline accounts don't work anymore. No fix will be provided

**Comment by KentangGG121** [comment]
Fabric 1.18.1 crashing using new renderer holy gl4es

**Comment by kingsmen1234** [comment]
does anyone have help no matter what version i play the only way the game works is with optifine and i would like to play using forge but it always say game closed with the error code 1(?)

**Comment by SAPUTRAZZ** [comment]
Access permissions on GitHub
In this article
About access permissions on GitHub
Personal accounts
Organization accounts
Enterprise accounts
Further reading
With roles, you can control who has access to your accounts and resources on GitHub and the level of access each person has.

About access permissions on GitHub
To perform any actions on GitHub, such as creating a pull request in a repository or changing an organization's billing settings, a person must have sufficient access to the relevant account or resource. This access is controlled by permissions. A permission is the ability to perform a specific action. For example, the ability to delete an issue is a permission. A role is a set of permissions you can assign to individuals or teams.

Roles work differently for different types of accounts. For more information about accounts, see "Types of GitHub accounts."

Personal accounts
A repository owned by a personal account has two permission levels: the repository owner and collaborators. For more information, see "Permission levels for a personal account repository."

Organization accounts
Organization members can have owner, billing manager, or member roles. Owners have complete administrative access to your organization, while billing managers can manage billing settings. Member is the default role for everyone else. You can manage access permissions for multiple members at a time with teams. For more information, see:

"Roles in an organization"
"Project board permissions for an organization"
"Repository roles for an organization"
"About teams"
Enterprise accounts
Enterprise accounts are available with GitHub Enterprise Cloud and GitHub Enterprise Server. For more information, see "About enterprise accounts" in the GitHub Enterprise Cloud documentation.

For more information about permissions for enterprise accounts, see the GitHub Enterprise Cloud documentation.

Further reading
"Types of GitHub accounts"

**Comment by Felix14-v2** [comment]
> Do you want Microsoft to sue us?

Misrosoft has been successfully turning a blind eye to the largest pirate launcher project owned by TLauncher Incorporated for more than 7 years. Moreover, this is not just a pirate launcher — it is a whole complex of legal and illegal software that allows its owners to make a profit of millions of dollars every year. And microsoft just doesn't do anything with them! Do you really think that they will care about a relatively small project that is not even monetized in any way?

However, I understand that you really should have done that. As for me, it's just inconvenient for me now to constantly wait for the authorization process to complete before each new launch of the game, because the launcher constantly logs me out when it closes.

**Comment by Fl414r** [comment]
You really blocks offline accounts..?
Something tells me that after a bunch of bans for no reason, you will have much fewer users...
(I strongly disapprove of this policy, as I myself have been playing without a license for a long time, since I simply did not have the opportunity to buy it. But damn it, I IMMEDIATELY bought this game when I had the opportunity to do so. This game cannot be damaged by pirates. After piracy, 90% will eventually buy it. The only ones that can hurt this game are Microsoft itself and its reporting system 1.19.1)

**Comment by Felix14-v2** [comment]
> after a bunch of bans for no reason, you will have much fewer users.

What do you mean? PojavLauncher does not ban anyone. The only limitation for offline accounts is the inability to download versions from the Mojang repository, and this is the Mojang requirement justified in the EULA. But even this can be circumvented by downloading the archive with the version separately from the launcher.

Let me remind you that the decision to stop supporting offline accounts without a license is not the desire of the development team, but the requirement of the Minecraft EULA.

**Comment by Fl414r** [comment]
`What do you mean? PojavLauncher does not ban anyone. `
I about 1.19.1 reporting system and 2 bugs in reports system. If you got banned you can't play Multiplayer and Rearms in 1.6(or 1.16...)-1.19.1
upd. oh and this
`offline accounts don't work anymore. No fix will be provided.
Mathias-Boulay closed this as [completed] `

**Comment by Felix14-v2** [comment]
> `What do you mean? PojavLauncher does not ban anyone. ` I about 1.19.1 reporting system and 2 bugs in reports system. If you got banned you can't play Multiplayer and Rearms in 1.6(or 1.16...)-1.19.1

But how does this apply to PojavLauncher? In your previous message, you blame the Pojav team for this...?

**Comment by Fl414r** [comment]
By the way, about TLauncher... At the beginning of TLauncher (after being stolen from the original creator) it was have part with virus that changed the hosts file. And in general, they have a dirty history, take at least a moment where they can remove servers that did not pay them from the list of servers in the game...
But... it still alive.

**Comment by Felix14-v2** [comment]
> By the way, about TLauncher... At the beginning of TLauncher (after being stolen from the original creator) it was have part with virus that changed the hosts file. And in general, they have a dirty history, take at least a moment where they can remove servers that did not pay them from the list of servers in the game... But... it still alive.

Okay, you say this to a person who personally communicates with the developer of the original TL Legacy and respects their position to provide a launcher for demonstration purposes with a call to buy the game in the future, and I am very well aware of its entire tragedy... but how does this relate to PojavLauncher and the topic?

**Comment by Fl414r** [comment]
`but how does this relate to PojavLauncher and the topic?`
this not relate...
Either way, I'm outraged by this.
![Screenshot_20220809_025420](https://user-images.githubusercontent.com/74704475/183533954-f26a5431-6ba6-495f-8dc3-a94d1aa45d88.jpg)

**Comment by Felix14-v2** [comment]
> Either way, I'm outraged by this.

Again, 

> Let me remind you that the decision to stop supporting offline accounts without a license is not the desire of the development team, but the requirement of the Minecraft EULA.

And yeah, offline accounts still work:
![Screenshot_20220809-030332](https://user-images.githubusercontent.com/75726196/183534980-252ed3da-62f0-406a-ad26-e1d3c32290c9.jpg)
![Screenshot_20220809-030340](https://user-images.githubusercontent.com/75726196/183534984-7b7272b7-bc46-4f2a-9258-babf9d6cbbc3.jpg)

**Comment by khanhduytran0** [comment]
> This game cannot be damaged by pirates

@Fl414r This game isn’t “victim”, but we are.

One of our devs who live in US got this email. What would you do in this case?

> This Subscriber should understand clearly that there are serious consequences for infringement.
The Copyright Act in the United States provides for statutory damages of up to $30,000 per work infringed, and up to $150,000 per work for willful infringement.
17 U.S.C. section 504(c).

**Comment by khanhduytran0** [comment]
Another thing to remind you: GitHub has now been owned by Microsoft, which means they can takedown this project anytime, if offline mode is kept. Since TLauncher devs do not come from US and its source code is closed, they are not affected.

**Comment by khanhduytran0** [comment]
If you want to avoid the use of 1.19.1+ chat reporting, use local account.
