### ISSUE TITLE
[BUG] <can't run Minecraft1.18.1>

### ISSUE THREAD

**Issue by lava114514** [PojavLauncherTeam/PojavLauncher#2681]
### Describe the bug

Application exited with code -1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8001266/latestlog.txt)

### Steps To Reproduce

```markdown
1. start PojavLauncher
2. install jre17-arm64-20210825-release.tar.xz
3. Launch Minecraft1.18.1
```

### Expected Behavior

I hope I can launch Minecraft 1.18.1

### Platform

```markdown
- Device model: 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
