### ISSUE TITLE
[BUG] download bug

### ISSUE THREAD

**Issue by Darkstrikerr** [PojavLauncherTeam/PojavLauncher#2684]
### Describe the bug

Able to download the main file but Not able to download the sound and etc 

### The log file and images/videos

![20220205_083813](https://user-images.githubusercontent.com/99060262/152626690-513677fb-ca1e-4e2e-bd66-f809b33789ae.jpg)

### Steps To Reproduce

```markdown
Start pojav launcher

Download any verson

And it will only download the main file
```

### Expected Behavior

A game bug

### Platform

```markdown
- Device model: redme 10 prime
- CPU architecture: idk
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

No

**Comment by Darkstrikerr** [comment]
Plz fix

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
Also don't skip assets
