### ISSUE TITLE
1.18 and 1.18.1 refuse to work.

### ISSUE THREAD

**Issue by Sophilocity** [PojavLauncherTeam/PojavLauncher#2685]
### Describe the bug

I did everything I could to get these versions to work but nothing works, I changed the java runtime to the correct architecture of my device, I changed the renderer to the correct opengl and I put the asset patch thingy with the assets but they still dont work. 1.18 will load the Mojang screen but crash as its loading and 1.18.1 will crash before it even gets to the Mojang screen. Help is really appreciated

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8007313/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav (On an Asus Chromebook)
2. Change the Java Runtime to jre17 x86_64
3. Change renderer to OpenGL Partial 3.2
4. Open 1.18 or 1.18.1
```

### Expected Behavior

I expected them both to launch and work fine.

### Platform

```markdown
- Device model: Asus Chromebook (Google Chrome 97.0.4692.102 Platform 14324.80.0-22.01.21 SN:L6NXCV19W95026D)
- CPU architecture: x86_64
- Android version: not sure
- PojavLauncher version: Latest release (I think?)
```

**Comment by khanhduytran0** [comment]
The log you provided tells a different story: you tried to run the patcher with Java 17 selected as default. Why? Internal code has already set Java 17 if 1.17+ is selected. So just set default Java back to Java 8, additionally set Java 17 in the PVC (per-version-config) by long-pressing on the version spinner.

**Comment by Sophilocity** [comment]
> The log you provided tells a different story: you tried to run the patcher with Java 17 selected as default. Why? Internal code has already set Java 17 if 1.17+ is selected. So just set default Java back to Java 8, additionally set Java 17 in the PVC (per-version-config) by long-pressing on the version spinner.

Long pressing the version spinner?

**Comment by Iarkont** [comment]
![Screenshot_20220205_165249_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/152644864-aa5eb762-699a-47e0-ae82-a2dacd437725.jpg)
Everything works perfectly

**Comment by Sophilocity** [comment]
cool bro glad it works for you but I kinda sorta need it to work for _me_

**Comment by Sophilocity** [comment]
> The log you provided tells a different story: you tried to run the patcher with Java 17 selected as default. Why? Internal code has already set Java 17 if 1.17+ is selected. So just set default Java back to Java 8, additionally set Java 17 in the PVC (per-version-config) by long-pressing on the version spinner.

Can you specify everything you say because I honestly dont understand a lot about this, is the version spinner the thingy that lets me choose the version?

**Comment by Sophilocity** [comment]
@khanhduytran0 The crash report is saying its a Java Runtime exception involving shaders if that helps, I tried changing the runtime back to java 8 like you said but it still didnt work, idk what else to do so I hope that helps and help is appreciated

**Comment by khanhduytran0** [comment]
You need to follow [this](https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04), carefully, don’t confuse between `assets-v0.zip` and `Pojav117AssetsPatcher.jar`.

**Comment by Sophilocity** [comment]
I did what it said but the versions still crash when I try to play them. I replaced the assets with the correct file and edited options.txt to what I renamed it but the versions still crash and give the same crash report

**Comment by Sophilocity** [comment]
Still keeps crashing

**Comment by JohnPrincePoggi31** [comment]
Buy a new phone 😂

**Comment by Sophilocity** [comment]
bruh I dont play on my phone, I use a chromebook

**Comment by Sophilocity** [comment]
@khanhduytran0 any update?

**Comment by khanhduytran0** [comment]
> @khanhduytran0 any update?

Any updates on the log file?

**Comment by Sophilocity** [comment]
@khanhduytran0 ok so I got 1.17.1 to work with the patch file but I read about a like weird bug thingy with the .jar file where it only patches 1.17.1, any way to fix that so it patches 1.18 and 1.18.1 so those work?

**Comment by Sophilocity** [comment]
> @khanhduytran0 ok so I got 1.17.1 to work with the patch file but I read about a like weird bug thingy with the .jar file where it only patches 1.17.1, any way to fix that so it patches 1.18 and 1.18.1 so those work?

@khanhduytran0 ???

**Comment by NotAHero04** [comment]
Remove all the versions (above 1.17) except for the one you tend to patch.

**Comment by Sophilocity** [comment]
how

**Comment by Sophilocity** [comment]
@khanhduytran0 I got the versions to work but before you close the bug, is there a way to get Fabric to work with the patched version?

**Comment by Sophilocity** [comment]
Anyone????

**Comment by khanhduytran0** [comment]
> but I read about a like weird bug thingy with the .jar file where it only patches 1.17.1

The latest patcher has already fixed it

**Comment by Sophilocity** [comment]
I know I already fixed it, I got Fabric for 1.18 but when I add any mods it crashes, can I use mods with Fabric?

**Comment by GoneSubject** [comment]
> I know I already fixed it, I got Fabric for 1.18 but when I add any mods it crashes, can I use mods with Fabric?

what mods you using?

**Comment by Sophilocity** [comment]
I tried to use Origins and get the Fabric API but it just crashes Pojav when I try to open Minecraft after applying them

**Comment by mchnjt** [comment]
> I tried to use Origins and get the Fabric API but it just crashes Pojav when I try to open Minecraft after applying them

Does the log say `Name and ID cannot be blank`?
Well, we have a simple fix for it.
BUY MINECRAFT :trollface:

**Comment by Sophilocity** [comment]
Do you seriously think after looking for answers this entire thread I didnt already have Minecraft?

**Comment by NotAHero04** [comment]
@rscDoesMoreTrolling I can 99% confirm that the authentication change doesn't affect 1.17+.

**Comment by NotAHero04** [comment]
Back to the main topic: [this nice article](https://pojavlauncherteam.github.io/updates/117.html) would help you.

**Comment by Sophilocity** [comment]
I already read that article, 1.18.1 now works but I need to know if Fabric mods will work

**Comment by ghost** [comment]
no answer moment

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
