### ISSUE TITLE
[BUG] Microsoft Login stuck at “logging in”

### ISSUE THREAD

**Issue by NoDa75** [PojavLauncherTeam/PojavLauncher#2686]
### Describe the bug

When I select Microsoft account under “sign in” and then click continue on the Microsoft page, PojavLauncher just says “logging in” and nothing happens. I have left my phone for 10 minutes and it still says logging in.

### The log file and images/videos

![AAE6A151-A7CD-48E8-B932-6D7936D4B49F](https://user-images.githubusercontent.com/84991444/152644999-58fcdc0f-a832-423e-872f-73524e183334.png)
![8ED74463-8786-44BA-8210-1DC4DA7BDC69](https://user-images.githubusercontent.com/84991444/152645000-bf183861-7ae0-47cc-bd0c-8eedef5c44b3.jpeg)

### Steps To Reproduce

```markdown
1. Click the sign in button.
2. Select “Microsoft account.”
3. A browser will open in the app, press continue in that browser.
```

### Expected Behavior

The login would succeed and I would be able to play the game.

### Platform

```markdown
- Device model: iPhone SE 2020
- CPU architecture: Apple A13
- Android version: 
- PojavLauncher version: Dev 2.1~beta 1
```

### Anything else?
This issue happens with “demo account” as well
_No response_

**Comment by artdeell** [comment]
Wrong repository. You should file PojavLauncher_iOS issues in the [PojavLauncher_iOS repository](https://github.com/PojavLauncherTeam/PojavLauncher_iOS)

**Comment by NoDa75** [comment]
Ok, just posted the issue there.
