### ISSUE TITLE
So okay how to fix this?

### ISSUE THREAD

**Issue by Malaska678** [PojavLauncherTeam/PojavLauncher#269]
I install every single libraries that forge needed and its too hard... And This happen
java.lang.RuntimeException: FML was unable to install the security manager. The game will not start

Can i force it to work :(

**Comment by khanhduytran0** [comment]
Forge need to be patched to get rid of the security manager.

**Comment by Malaska678** [comment]
Seen this problem on pc users :(

**Comment by Malaska678** [comment]
They said that forge is installed twice for some reason..

**Comment by khanhduytran0** [comment]
But Android does not support SecurityManager

**Comment by khanhduytran0** [comment]
So it's why Forge not load

**Comment by Malaska678** [comment]
Is it the reason why its hard to have forge installer on pojav launcher?

**Comment by khanhduytran0** [comment]
It may not hard because Forge is open source, so a patcher can be made not hard.

**Comment by khanhduytran0** [comment]
> It may not hard because Forge is open source, so a patcher can be made not hard.

**Comment by khanhduytran0** [comment]
I may look at that exception

**Comment by Malaska678** [comment]
But You say that forge is hard to support on v2 so focus first on v3 development..

**Comment by Malaska678** [comment]
Closing
