### ISSUE TITLE
[BUG] <the app can't install forge installer for 1.16.5>

### ISSUE THREAD

**Issue by Ku-rumi-666** [PojavLauncherTeam/PojavLauncher#2691]
### Describe the bug

When i click the file of forge installer for 1.16.5 it makes the app crash, and if you look on the list of versions it's not in the list.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8009484/latestlog.txt)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I expect the app can install the forge installer 1.16.5

### Platform

```markdown
- Device model: Vivo s1
- CPU architecture: 
- Android version: 11
- PojavLauncher version: 3.3.1.1 20210125
```

**Comment by Ku-rumi-666** [comment]
CPU ARCHITECTURE: MediaTek Helio P65 (MT6768)

**Comment by artdeell** [comment]
Update your launcher.

**Comment by Ku-rumi-666** [comment]
where is the latest one? can i have the link?

**Comment by moxisuki** [comment]
> where is the latest one? can i have the link?

googleplay has it

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
