### ISSUE TITLE
Hey When i use bsl shader in virgl render the shader works but the world is getting full black only water showing

### ISSUE THREAD

**Issue by Emperormode** [PojavLauncherTeam/PojavLauncher#2692]
### Describe the bug

![Screenshot_2022-02-06-13-03-58-83_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/99115154/152671803-df85df1d-2914-4692-938f-43ee1353e0b5.jpg)

### The log file and images/videos

![Screenshot_2022-02-06-13-03-58-83_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/99115154/152671823-5041c5fb-e981-4d34-acd4-6ab54caa5b0f.jpg)
This is the photo of that bug

### Steps To Reproduce

```markdown
Pls do this
```

### Expected Behavior

I think that it is very bad bug

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Pls fix this

**Comment by khanhduytran0** [comment]
Incomplete info.

> Pls fix this

That’s how shader works with your GPU. ~~**If you want fully-functional, insert RTX 3090 into your phone**.~~ Actually, renderer has already did its best to make it work. Shader support is incomplete, except Zink renderer.

**Comment by khanhduytran0** [comment]
For virgl, only Chocapic is known to work best with.

**Comment by Emperormode** [comment]
Before this its works not now

**Comment by khanhduytran0** [comment]
Still, incomplete info. We cannot extract stuff from a single screenshot.

**Comment by Emperormode** [comment]
What you need more i will give tell

**Comment by imjustpenguin** [comment]
![Uploading Screenshot_20220205_003641.jpg…]()
