### ISSUE TITLE
[BUG] Virgl black screen

### ISSUE THREAD

**Issue by imjustpenguin** [PojavLauncherTeam/PojavLauncher#2693]
### Describe the bug

When you play the game when you using virgl there is a minecraft sound but black pls fix this bug and thank you :) 

### The log file and images/videos

![Screenshot_20220206_161726](https://user-images.githubusercontent.com/96688215/152672874-c28bfcca-174d-4602-bdd2-9ed2ba8c609a.jpg)
Its only black screen but theres stil sound 

### Steps To Reproduce

```markdown
1. Start pojav launcher 
2. Select virgl 
3. Go play minecraft
4. Black screen
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:Fixed upside down pojav launcher version
```

### Anything else?

no

**Comment by mchnjt** [comment]
racist entities? no problem, just use gl4es 1.1.4 and you should be fine :trollface:

**Comment by mchnjt** [comment]
black screen? no problem, just use some gl4es 1.1.4 and you should be fine :trollface:

**Comment by imjustpenguin** [comment]
Ok

**Comment by imjustpenguin** [comment]
But i want virgl

**Comment by imjustpenguin** [comment]
The loding screen is done but black screen :(

**Comment by imjustpenguin** [comment]
Idk what happend to my minecraft files

**Comment by imjustpenguin** [comment]
Cuz i try textures packs and shader

**Comment by imjustpenguin** [comment]
![Screenshot_20220205_161229](https://user-images.githubusercontent.com/96688215/152673149-f09c8888-473d-42ba-b6e0-390f21631efd.jpg)

**Comment by imjustpenguin** [comment]
![Uploading Screenshot_20220205_160427.jpg…]()

**Comment by notstackgb** [comment]
> black screen? no problem, just use some gl4es 1.1.4 and you should be fine :trollface:

Lol

**Comment by notstackgb** [comment]
:trollface:

**Comment by notstackgb** [comment]
🤨

**Comment by notstackgb** [comment]
> ![Screenshot_20220205_161229](https://user-images.githubusercontent.com/96688215/152673149-f09c8888-473d-42ba-b6e0-390f21631efd.jpg)

change ur resolution

**Comment by Mathias-Boulay** [comment]
Virgl related issues cannot really be fixed, as we don't make the renderer

**Comment by H270-del** [comment]
> ### Describe the bug
> When you play the game when you using virgl there is a minecraft sound but black pls fix this bug and thank you :)
> 
> ### The log file and images/videos
> ![Screenshot_20220206_161726](https://user-images.githubusercontent.com/96688215/152672874-c28bfcca-174d-4602-bdd2-9ed2ba8c609a.jpg) Its only black screen but theres stil sound
> 
> ### Steps To Reproduce
> ```gfm
> 1. Start pojav launcher 
> 2. Select virgl 
> 3. Go play minecraft
> 4. Black screen
> ```
> 
> ### Expected Behavior
> Nothing
> 
> ### Platform
> ```gfm
> - Device model: 
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:Fixed upside down pojav launcher version
> ```
> 
> ### Anything else?
> no

same
