### ISSUE TITLE
When I play minecraft with optifine but exit the game at few moments

### ISSUE THREAD

**Issue by saurabhris** [PojavLauncherTeam/PojavLauncher#2695]
### Describe the bug

When I play minecraft with optifine but exit the game at few moments

### The log file and images/videos

When I play minecraft with optifine but exit the game at few moments

### Steps To Reproduce

```markdown
When I play minecraft with optifine but exit the game at few moments
```

### Expected Behavior

When I play minecraft with optifine but exit the game at few moments

### Platform

```markdown
- Device model: iq z3
- CPU architecture: SD 768G
- Android version: 11
- PojavLauncher version: play store
```

**Comment by NotAHero04** [comment]
> When I play minecraft with optifine but exit the game at few moments
>
is not a valid log file.

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
