### ISSUE TITLE
[LabyMod 1,8,9] <Game Exited>

### ISSUE THREAD

**Issue by SeNioRHqdi** [PojavLauncherTeam/PojavLauncher#2696]
### Describe the bug

when i downloaded 1.8.9 labymod i got an issue when i load the game it just says game exited and i tried multiple devices

### The log file and images/videos

i deleted the game and install it again hopfully it opens 

### Steps To Reproduce

```markdown
when i start the client it  just exit me out of the client and says Game Exited
```

### Expected Behavior

i expected to launch cause labymod my favorite client tbh and im now playing on just optifine

### Platform

```markdown
- Device model: chromebook
- CPU architecture: idk
- Android version: 10
- PojavLauncher version: the latest one
```

### Anything else?

pls fix it i want to play with labymod im tired of just optifine

**Comment by moha0116** [comment]
Try labymod 1.12.2

**Comment by SeNioRHqdi** [comment]
> Try labymod 1.12.2

it works but i want to pvp

**Comment by GaucovyAero** [comment]
**If you want to pvp, do this:**

- **a)** Download Forge 1.8.9, 1.7.10 or 1.7.2 with these mods: bsprksCore, PlayerAPI, ToggleSneak, OldAnimationsMod, StatusEffectHUD, ArmorStatusHUD and Optifine
- **b)** Download Cracked Lunar Client 1.8.9 (might casually crash after 3 mins with elf_dynamic_array_reader_ [h(64)] tag not found)
- **c)** Download cmpack 1.8.8 (not sure if it works fine)
- **d)** Go on your computer.

**Comment by mchnjt** [comment]
> **If you want to pvp, do this:**
> 
> * **a)** Download Forge 1.8.9, 1.7.10 or 1.7.2 with these mods: bsprksCore, PlayerAPI, ToggleSneak, OldAnimationsMod, StatusEffectHUD, ArmorStatusHUD and Optifine
> * **b)** Download Cracked Lunar Client 1.8.9 (might casually crash after 3 mins with elf_dynamic_array_reader_ [h(64)] tag not found)
> * **c)** Download cmpack 1.8.8 (not sure if it works fine)
> * **d)** Go on your computer.

you forgot one more thing: buy minecraft :trollface:

**Comment by SeNioRHqdi** [comment]
i want to use labymod cause its better


‫في الثلاثاء، 8 فبراير 2022 في 10:04 ص تمت كتابة ما يلي بواسطة ‪Jet‬‏ <‪
***@***.***‬‏>:‬

**Comment by Mathias-Boulay** [comment]
cannot be fixed without a patch on the client itself.
