### ISSUE TITLE
[F-Req] <add Virgl (OpenGL ES) exports  opengl 4.4

### ISSUE THREAD

**Issue by imjustpenguin** [PojavLauncherTeam/PojavLauncher#2697]
### Is this request related to a bug?

no i just wanted virgl 4.4

### Describe the request.

I love virgl 4.3 but i wanna try virgl 4.4

### Anything else?

Pls add virgl opengl 4.4 pls or you cant add virgl 4.4 thats fine i still in 4.3 thanks
![Screenshot_20220205_003641](https://user-images.githubusercontent.com/96688215/152680906-a5843630-bb33-4cbc-b759-a0b231eb1333.jpg)

**Comment by NotAHero04** [comment]
What will you do with features from OpenGL 4.4?

**Comment by imjustpenguin** [comment]
Play with shaders and upload the virgl in yt vid 
Not the link vid only

**Comment by khanhduytran0** [comment]
virglrenderer doesn’t fully support OpenGL 4.4 at the moment. See https://github.com/freedesktop/virglrenderer/blob/master/docs/GL-status.txt#L94-L104 for more info.

**Comment by imjustpenguin** [comment]
Ok thanks
