### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by AyHa1810** [PojavLauncherTeam/PojavLauncher#270]
I have some issues. First of all, it uses dalvik/ART vm, which is not very good or efficient for Minecraft. Because the Minecraft gets patched after downloading, sometimes, some functions may not work. I can't play any version. Sometimes, the game defaults to Russian after getting patched, and I can't even change it back. Even if I tried to, it crashes. 

I recommend to use OpenJDK for the java runtime, because it has arm and arm64 variant, and it's open source. And the game should be original, not patched. Also, it should use arm or arm64 compiled native libraries.

If Minecraft Java Edition can run on arm or arm64 linux, then why not on Android? Because Android has the capability of working java. Just one problem of Android, it has a limited number of usable ram for each app.

**Comment by khanhduytran0** [comment]
Yep I tried before with my attempt port OpenJDK mobile to arm64 but not success.

Also some users reported about MCinabox it very lag, because it handle OpenJDK, so put to PojavLauncher may decrease FPS also (althought different port)

**Comment by khanhduytran0** [comment]
There's prebuilt OpenJDK for ARM32/64 but it's for GNU/Linux not for LibC Bionic/Android.

**Comment by khanhduytran0** [comment]
The patch part was only remove Mojang signature and that's all so will not affect game at all.

**Comment by AyHa1810** [comment]
Still, I can't play Minecraft Java Edition on my phone :( . And why the launcher removes Mojang signature? I can't get it.

**Comment by AyHa1810** [comment]
Also, I found this https://github.com/openjdk/mobile

**Comment by khanhduytran0** [comment]
> And why the launcher removes Mojang signature?
- Without remove, when launch you will get signature verification failed and prevent you launch.

**Comment by khanhduytran0** [comment]
As now, v3 is available use JDK9 which possible with mods. We also have 64-bit java but not working about framebuffer.
