### ISSUE TITLE
Sky factory 3 Modpacks have a bug

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#2701]
### Describe the bug

Sky factory 3 only half screen and flipped screen

### The log file and images/videos

![Screenshot_20220207-122710](https://user-images.githubusercontent.com/76839710/152725104-f43a55dd-9db5-4627-a1e1-3f4d96dbbe27.png)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8012370/latestlog.txt)

### Steps To Reproduce

```markdown
1. Paste all sky factory 3 Modpacks to Pojavlauncher file
2. Change render to Virglrender 4.3
3. Start Pojavlauncher
4. Flipped screen and only half screen
```

### Expected Behavior

Only half screen and flipped screen Minecraft version 1.10.3

### Platform

```markdown
- Device model: bison umidigi 6gb/128gb
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest on github
```

### Anything else?

Plss help me I want to play this Modpacks with shader Virglrender 4.3

**Comment by NotAHero04** [comment]
> latest on github

Please provide the full version string.
~~VirGL is expected to not work well with older Minecraft versions.~~

**Comment by kedrick021** [comment]
> > latest on github
> 
> Please provide the full version string. ~VirGL is expected to not work well with older Minecraft versions.~
How to get that Version string?

**Comment by NotAHero04** [comment]
Hold the application icon, tap "Info" and scroll to the bottom.

**Comment by kedrick021** [comment]
> Hold the application icon, tap "Info" and scroll to the bottom.

version crocus-299-f1bd70996-v3_openjdk

**Comment by NotAHero04** [comment]
It's [over two months ago](https://github.com/PojavLauncherTeam/PojavLauncher/commit/f1bd70996c8caf9e9e80376d53e6b5c1f9eb9ca5). Update your launcher.

**Comment by kedrick021** [comment]
> It's [over two months ago](https://github.com/PojavLauncherTeam/PojavLauncher/commit/f1bd70996c8caf9e9e80376d53e6b5c1f9eb9ca5). Update your launcher.

No I already try a new one and try to change the old one if is working

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by vanlinhss** [comment]
link skyfactory 3??
