### ISSUE TITLE
I can't scroll page with middle mouse button

### ISSUE THREAD

**Issue by MistyStory1** [PojavLauncherTeam/PojavLauncher#2702]
### Describe the bug

I can't scroll page with middle mouse button,some pages added by mods can only scroll with middle mouse button and have no scroll bar

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

The page should be able to scroll by using middle mouse button

### Platform

```markdown
- Device model: huawei nova 6s 8/128G
- CPU architecture: i don't know
- Android version: 10
- PojavLauncher version: latest release,crocus-3190a3385acd-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
