### ISSUE TITLE
[BUG] Clicking on "Launch a mod installer" does not work on google tv.

### ISSUE THREAD

**Issue by letsgoawaydev** [PojavLauncherTeam/PojavLauncher#2703]
### Describe the bug

When I click the `Launch a mod installer (Forge, LabyMod, Fabric, etc...` button, it says No application can handle this action. I know this is most likely an android bug, but is there any way to fix it? I've researcher everywhere on google and even tried using the custom arguments button and instailling from my pc versions.
Also when i installed from my pc version of Optifine M5 under C:\Users\u\AppData\Roaming\.minecraft\versions to my .minecraft folder on the pojav launcher folder it crashed.

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-stb.jar, lwjgl.jar, version, lwjgl-tinyfd.jar, lwjgl-glfw-classes.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-jemalloc.jar]
Architecture: arm
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9 (1.8.9)
--------- beginning of main
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1920
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-A5IkJ-RZaCNaGHQzIofJgg==/lib/arm
Added custom env: POJAV_RENDERER=opengles2_5
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Aug 18 2021 16:48:22
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Max texture size: 8192
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Max Color Attachments: 1 / Draw buffers: 1
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
Targeting OpenGL 2.1
NPOT texture handled in hardware
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  ( 8647): dlopen libgl4es_115.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  ( 8647): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsdt.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmlib_image.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libunpack.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/liblcms.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libzip.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_xawt.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjdwp.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsunec.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libdt_socket.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsig.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pcsc.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjawt.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjaas_unix.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2gss.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsound.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsctp.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libhprof.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libtinyiconv.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjpeg.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmanagement.so success
I/jrelog  ( 8647): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pkcs11.so success
I/jrelog  ( 8647): dlopen /data/app/net.kdt.pojavlaunch-A5IkJ-RZaCNaGHQzIofJgg==/lib/arm/libopenal.so success
I/jrelog  ( 8647): Done processing args
I/jrelog  ( 8647): Found JLI lib
I/jrelog  ( 8647): Calling JLI_Launch
[10:24:35] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:24:35] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0-internal]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0-internal]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0-internal]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xf2c6c210)
process killed with signal 6 code 0xffffffff addr 0x21c7
--------- beginning of crash

### Steps To Reproduce

```markdown
Open pojavlauncher on google tv. 
Click on  `Launch a mod installer (Forge, LabyMod, Fabric, etc...` under options.
Get: No application can handle this action.
```

### Expected Behavior

I excpect to see a file sorter of some sorts.

### Platform

```markdown
- Device model: Google Chromecast with Google TV
- CPU architecture: arm
- Android version: 10
- PojavLauncher version: in the about section it says crocus-v3_openjdk
```

**Comment by khanhduytran0** [comment]
> No application can handle this action
> Device model: Google Chromecast with Google TV

You know, Android TV doesn’t have a file picker installed by default.

**Comment by letsgoawaydev** [comment]
yes i know. but i have installed files by google AND x-plore by sideloading. if they arent file pickers, do you know of any ones that may work?

**Comment by letsgoawaydev** [comment]
sorry, xplore is by google play and not by sideloading

**Comment by khanhduytran0** [comment]
You may want to take a look at ZArchiver, although its main function is to archive/extract stuff.

**Comment by letsgoawaydev** [comment]
ok ill try that and let you know how it goes

**Comment by letsgoawaydev** [comment]
YOOO THANKS SO MUCH!!!!!!

**Comment by letsgoawaydev** [comment]
IT WORKED
