### ISSUE TITLE
[BUG] <VGPU SHADER BUG ON MEDIATEK P35>

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2704]
### Describe the bug

Its smooth but not working perfectly

### The log file and images/videos

![Screenshot_2022-02-07-19-13-33-21](https://user-images.githubusercontent.com/96860972/152778582-cdd28c21-b09e-47b6-99b8-68cf5c0814ec.jpg)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Oppo A12 3/32
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Virgl build
```

### Anything else?

Can you fix it?

**Comment by kedrick021** [comment]
No

**Comment by Mathias-Boulay** [comment]
vgpu is no more.
