### ISSUE TITLE
Forge 1.17.1 doesn't open[BUG] <Short description>

### ISSUE THREAD

**Issue by Ragebugk** [PojavLauncherTeam/PojavLauncher#2705]
### Describe the bug

I have use jrch17 and other stuff but it's says that Java runtime is incompatible

### The log file and images/videos

None

### Steps To Reproduce

```markdown
M
```

### Expected Behavior

I expect the game to run nicely

### Platform

```markdown
- Device model: redmi note 9
- CPU architecture: 
- Android version: 10
- PojavLauncher version: up to date
```

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
