### ISSUE TITLE
Crashes[BUG] <Short description>

### ISSUE THREAD

**Issue by manikamboj748** [PojavLauncherTeam/PojavLauncher#2706]
### Describe the bug

Game crashes alot when play on any big server even I play on 2 chunks unlimited fps still crash pojav fix it!!!!!!

### The log file and images/videos

Idk

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
