### ISSUE TITLE
[BUG] Most Annoying BUG

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#2707]
### Describe the bug

The Fullscreen Mode Changes As You Type "W" On Your Keyboard 

And Its Really Annoying! 

### The log file and images/videos

Not Implemented 

### Steps To Reproduce

```markdown
[1]  Start Pojav On Any Version

[2]  Wait For The Game To Load

[3]  Either Use Your keyboard or Keyboard + Chat To Type "W" (CAPITAL 'W')

[4]   The Annoying Bug!!!!!!!!!
```

### Expected Behavior

It Should Work Fine While Typing "W"

### Platform

```markdown
- Device model: vivo V5s
- CPU architecture: Can't Say (Kindly Check My Older Issues)
- Android version: 7.0
- PojavLauncher version: 

[Link: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1677959713]
```

### Anything else?

Please Fix It ASAP Its Very Annoying!!!!

**Comment by mchnjt** [comment]
It's your bug, not ours. You prolly binded Fullscreen to W. Go fuck yourself

**Comment by SprainedSpark89** [comment]
i have seen a different issue with the same problem and how could you bind fullscreen to w?

**Comment by mchnjt** [comment]
> i have seen a different issue with the same problem and how could you bind fullscreen to w?

bruh moment
![2022-02-09_23 01 48](https://user-images.githubusercontent.com/83752061/153305240-a3ade8e3-4276-49a9-b621-4e2b08a48c03.png)

**Comment by SprainedSpark89** [comment]
Why is that a option '-'

**Comment by SprainedSpark89** [comment]
But if you press w do you move to?

**Comment by GoneSubject** [comment]
> But if you press w do you move to?

yeah except you change it

**Comment by AgaricaGamer** [comment]
First of all its not binded with W so it dosent happens and it only runs when i press W from keyboard so stop saying anything

**Comment by mchnjt** [comment]
oh keyboard 😂😂😂
bruh your bug report is shit you should've said "physical keyboard" at the start :trollface:

**Comment by SprainedSpark89** [comment]
i think that is the same bug that makes a xbox controller have the weirdest controls

**Comment by Mathias-Boulay** [comment]
#2567
