### ISSUE TITLE
[BUG] Per Version Config Game Directory does not work on Android 10+

### ISSUE THREAD

**Issue by dvdcd** [PojavLauncherTeam/PojavLauncher#2708]
### Describe the bug

Due to the storage permissions changes with Android 10+, the Per Version Config Game Directory setting accessible by long tapping the version number doesn't request write access to folders outside of the app's secure data store, and thus doesn't work

My use case for this would be using Syncthing to synchronize world saves across devices, and to do so Pojav launcher needs to be loading the world files from a storage location that is mutually accessible by both apps.  

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8022025/latestlog.txt)

### Steps To Reproduce

```markdown
1. Set the game directory to  /storage/emulated/0/Minecraft or anything outside of the app's secure storage
2. Launch the game
3. The game will launch fine, but if you try to create a world, the game crashes due to not having write permissions to the specified directory. It does have permission to write folders, and it will have done so, but no files will be written in /storage/emulated/0/Minecraft
```

### Expected Behavior

I would expect Pojav launcher to request access to this folder, or have some means for identifying and not allowing the user to specify a game directory that Pojav Launcher is unable to request write permissions from the user for. Currently as far as I can tell, on Android 10+, the game directory feature is totally useless because the app doesn't properly request permissions to use this folder.

Currently, as far as I can tell there's no way to grant this permission to Pojav launcher without it being requested in the app's manifest at least. I know that `android.permission.MANAGE_EXTERNAL_STORAGE` would work, however due to the Play Store's restrictions on this permission, other options, Including the [Media Store API](https://developer.android.com/training/data-storage/shared/media), might need to be explored.

### Platform

```markdown
- Device model: Oneplus 8T 12gb/256gb
- CPU architecture: aarch64 (Snapdragon 865)
- Android version: 11, Kernel 4.19.110-perf+
- PojavLauncher version: Latest Play Store Release, Crocus
```

**Comment by artdeell** [comment]
Media Store API is slow as hell. Even if we manage to route all file operation calls to it (which is NOT easy) the performance would be very low.

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
