### ISSUE TITLE
I[F-Req] Option to get rid of the side bar when in game.

### ISSUE THREAD

**Issue by ItsCyberBush** [PojavLauncherTeam/PojavLauncher#2709]
### Is this request related to a bug?

No, but the way it appears while tapping is very annoying since it makes your controls paused.

### Describe the request.

I would like you to get rid of this area.
![Screenshot_2022-02-08-17-41-58-842](https://user-images.githubusercontent.com/81066878/152989278-4adc5576-5c04-4e0e-a2a5-e918e68c4cbf.jpeg)
I hope you will add this option, I will not force the Devs to do since it is their choice.

### Anything else?

Is this option available in other PojavLauncher builds?

**Comment by ItsCyberBush** [comment]
I hope I am not causing any trouble

**Comment by ItsCyberBush** [comment]
Also I am a very offline person so I may not answer as soon as replied.

**Comment by SprainedSpark89** [comment]
swipe right

**Comment by ItsCyberBush** [comment]
No no I am asking for a option so that this thing won't appear at all

**Comment by SprainedSpark89** [comment]
then how do you force close i had discovered that if you swipe the minecraft it doesn't close

**Comment by ItsCyberBush** [comment]
There is a possibility I can't close pojav? ok then
