### ISSUE TITLE
How to allocate more ram?

### ISSUE THREAD

**Issue by Malaska678** [PojavLauncherTeam/PojavLauncher#271]
Can i allocate more ram because u said that the launcher only using 512MB.

**Comment by Malaska678** [comment]
Manually

**Comment by khanhduytran0** [comment]
If discover into Android a bit, yes but ADB *or* Root is required, but I not sure if it work...

**Comment by Malaska678** [comment]
Dont want to root my device. What is adb?

**Comment by pablodz** [comment]
> Dont want to root my device. What is adb?

ADB is driver to connect Android devices to PC and see the log of what's happening on the smartphone

**Comment by khanhduytran0** [comment]
So v3 will break 512mb limit but
- arm32/aarch32 java limit to 950mb
- arm64/aarch64 java unlimited memory or max 16gb
