### ISSUE TITLE
[F-Req] Enhance the installation experience of other clients / mods

### ISSUE THREAD

**Issue by 2019Z2** [PojavLauncherTeam/PojavLauncher#2711]
### Is this request related to a bug?

No.

### Describe the request.

Allowing to install a jar file without a JSON file attached to the folder (as a requirement) and adding a screen that says:" Are you sure you want to execute this file?
It seems like some files are missing / corrupted." 
And 2 buttons: "cancel" , and "I know what I'm doing" )

### Anything else?

I tried to install a client and failed because of this.
(And I don't expect for assistance)

**Comment by artdeell** [comment]
JAR execution can be done through the "Install .JAR" button on the main screen. Why would you  need other ways of running .JAR files?

**Comment by 2019Z2** [comment]
Personally, it's not as easily accessible to open the file using this method because I have plenty of files in my phone, and I think it's easier to be able to select a .JAR file from there (as an additional option , because some .JAR files aren't accessible there after installation, even though the installation succeeded)

**Comment by khanhduytran0** [comment]
> Allowing to install a jar file without a JSON file attached to the folder 

Did you just put the jar file into the `versions` folder?

> I have plenty of files in my phone

Search bar exists for a reason...

**Comment by 2019Z2** [comment]
> 

Indeed.

**Comment by artdeell** [comment]
You won't get anything from running the jar from the versions folder, mainly because the jar installer and regular run are not the same. In the installer, Java's window toolkit output is rendered, while in a regular run ony Minecraft's OpenGL window is rendered.

**Comment by 2019Z2** [comment]
I see.
