### ISSUE TITLE
[BUG] Internal Exceptiom: io.netty.timeout.ReadTimeoutException

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2713]
### Describe the bug

I'm trying to play **Hypixle Turbo Cart Races** on 1.8 but, when I try to download the resource pack it freezes and kicks me from the game.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8029103/latestlog.txt)

https://user-images.githubusercontent.com/65428515/153118657-2486eb78-4b91-4256-885e-97b062b91247.mp4

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Sign-in to an account
3. Select 1.8 as Minecraft version
4. Click Play
5. Once Minecraft loads, click Multiplayer
6. Now click "Add Server"
7. In the Server Address slot set it as "www.hypicel.net"
8. Now join the newly added server
9. Once in server, right-click the compass to open the game menu
10. Now look and click the enchanted jukebox to go to the Classic Games (Near the bottom left)
11. Once teleported, you go to the square slime blocks that say "TCR" (Turbo Cart Racers) above it. This will move you to the "TCR" Section
12. Once there, click the character in front of you (This will bring up the TCR menu)
13. Click the Minecart Icon on the top as this will join you in the lobby
14. FINALLY, in the chat type "/resource" to open the resource pack book
15. Now click the Resource Pack link and it will crash :)
```

### Expected Behavior

For the resource pack to download

### Platform

```markdown
- Device model: R96-14268.67.0
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

Just so you know, once you do this, hypixle will keep trying to lad the resource pack until you leave the game lobby, but since you crash, you can never, so you will get **soft blocked** from hypixel if you do this!!!

🤷

**Comment by NotAHero04** [comment]
Did you try using Forge with Random Patches mod?

**Comment by Errorbot1122** [comment]
I dont have to forge mod installer yet, can you give me the download links for both items?

**Comment by SprainedSpark89** [comment]
it doesn't have a connection

**Comment by Errorbot1122** [comment]
???

**Comment by SprainedSpark89** [comment]
the bars have x over them

**Comment by Errorbot1122** [comment]
oh it does, I think it is because hypixel works in multiple versions and it is currently on 1.17/1.18 so 1.8 thinks that it can connect when I somehow can

IDK then

**Comment by SprainedSpark89** [comment]
ok try 1.8.9
it says hypixel recommends it
https://support.hypixel.net/hc/en-us/articles/360019634940-Changing-Minecraft-Versions

**Comment by Errorbot1122** [comment]
okay ill try that, tnx
