### ISSUE TITLE
Pojav Launcher for PC

### ISSUE THREAD

**Issue by shubhamp2007** [PojavLauncherTeam/PojavLauncher#2715]
### Is this request related to a bug?

I am big fan of PojavLauncher because it enables us to play Java Edition on Mobile. But I would request the team if they could make Pojav Launcher for PC.

### Describe the request.

I am playing Minecraft since 1.16.5 on PC but with 1.17 I was not able to play. So I did some research and found about PojavLauncher and I was able to play on mobile. But It would be very greatful if you make PojavLauncher for PC. As you have some files which can run 1.17, and 1.18 on OpenGl 3.2 which is a very good feature. Please make it for PC also.

### Anything else?

Or If you could, make some files for Tlauncher enabling it to run 1.17 and 1.18 on OpenGl. Millions of person would be very greatful to you. Because all people are not rich, that they have latest PC with OpenGl 4.6.

So, I request your team to make files which can run 1.18 on OpenGl 3.6 or Make PojavLauncher for PC.

Thanking You
One of your efforts fan

**Comment by NotAHero04** [comment]
PojavLauncher doesn't target PCs in the first place, yet you can still download an Android emulator to use it.

**Comment by mchnjt** [comment]
tlauncher

**Comment by khanhduytran0** [comment]
> As you have some files which can run 1.17, and 1.18 on OpenGl 3.2 which is a very good feature. Please make it for PC also.

Minecraft's actual minimum requirement is OpenGL 3.2. But what you see in their official page is OpenGL 4.5. Do you know why? They don’t want to deal with rendering issues on outdated GPUs, therefore define OpenGL 4.5 as minimum (probably some OpenGL 4.x features are used optionally), but
- OpenGL 3.2 is the actual minimum for 1.17+
- OpenGL 2.0 is the actual minimum for 1.15+
