### ISSUE TITLE
Black screen when using virgl in 1.12.2

### ISSUE THREAD

**Issue by imjustpenguin** [PojavLauncherTeam/PojavLauncher#2716]
### Describe the bug

When you play 1.12.2 with virgl is just a black screen i wait 1 hour to load up but still black screen 

### The log file and images/videos

![Screenshot_20220209_170323](https://user-images.githubusercontent.com/96688215/153162324-7551b661-424a-41d5-9c3b-3ea30dfd2ef6.jpg)
I wait 1 hour but still black

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Play 1.12.2 with virgl 
3. Black screen
```

### Expected Behavior

nothing

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:Fixed up side down version apk
```

### Anything else?

pls fix the bug ty 🤗

**Comment by SprainedSpark89** [comment]
looks like there issues with that render

**Comment by imjustpenguin** [comment]
ya

**Comment by imjustpenguin** [comment]
But if i play 1.13.2 to 1.16.5 its fine

**Comment by imjustpenguin** [comment]
But 1.12.2 and 1.8.9 is black

**Comment by GoneSubject** [comment]
maybe use f11? it seem normal to me but when i press f11 it's black

**Comment by mchnjt** [comment]
very straightforward

> `maybe use f11`? it seem normal to me but `when i press f11 it's black`

**Comment by imjustpenguin** [comment]
Still black

**Comment by imjustpenguin** [comment]
:(

**Comment by imjustpenguin** [comment]
But im happy 1.13.2  is not black

**Comment by RzdPai** [comment]
先使用别的渲染器进入，将快速渲染，区块渲染和缓慢区块加载关闭，然后再换回virgl并进入即可

**Comment by imjustpenguin** [comment]
Still not working

**Comment by parallelmindstate** [comment]
See the debug log, if it eventually loops spitting "VIRGL_TEXTURE_ID is not set" then I have the same problem as you. 1.12.2 and 1.16.5 stuck in black screen, dunno the other versions

**Comment by parallelmindstate** [comment]
I just have updated my Pojav launcher build to crocus-327-6d2295d46 now Minecraft 1.16.5 is working properly

**Comment by imjustpenguin** [comment]
Pls send me the crocus-327-6d2295d46

**Comment by imjustpenguin** [comment]
Pls

**Comment by imjustpenguin** [comment]
> I just have updated my Pojav launcher build to crocus-327-6d2295d46 now Minecraft 1.16.5 is working properly

Link pls

**Comment by imjustpenguin** [comment]
Yoo its working now i can play shaders again in 1.12.2 

Uploading video_20220213_205629.mp4…

**Comment by parallelmindstate** [comment]
Oof I'm too late but here it is: 

https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1677959713


Glad now pojav virgl is working for you tho.

**Comment by imjustpenguin** [comment]
👍
