### ISSUE TITLE
[BUG] Scoped storage causing crashes?

### ISSUE THREAD

**Issue by Nitrocosm** [PojavLauncherTeam/PojavLauncher#2717]
### Describe the bug

Running Minecraft with Forge works well, and I've had no problems with it so far. However, upon installing Labymod, things break and it just crashes every time the game tries to load.

Attached will be the crash log and lastestlog.

### The log file and images/videos

[crash-2022-02-09_15.50.55-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8034093/crash-2022-02-09_15.50.55-client.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8034094/latestlog.txt)

### Steps To Reproduce

```markdown
1. Run 1.8.9
2. Close game, don't make any worlds
3. Install Forge using the lastest installer and run Forge 1.8.9, then close
4. Run Labymod installer with the following settings:
  a. 1.8.9 Forge Install
  b. Toggle sneak, Optifine, Keystrokes, DMG indicator, Skyblock add-ons, and settings profiles
5. Attempt to run Forge, but crashes
```

### Expected Behavior

The game should launch with Labymod installed and add-ons working as expected.

### Platform

```markdown
- Device model: Mi 10T
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release
```

### Anything else?

A line that caught my attention was when the log said Permission Denied. With Android 10 came Scoped Storage, and it might be as a result of that that the game doesn't run for some reason.

**Comment by artdeell** [comment]
1.8.9 LabyMod does not work due to problems with the JNA library, please use LabyMod 1.12.2 instead or switch to other clients

**Comment by Nitrocosm** [comment]
So is this a Pojav-specific problem? I was initially gonna use Laby for Skyblock mods, but if it's the case I'll figure something out
