### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by KentuckyFriedBeef** [PojavLauncherTeam/PojavLauncher#2718]
### Describe the bug

it just says this.

### The log file and images/videos

![Screenshot_20220210_005410](https://user-images.githubusercontent.com/85325129/153252351-69594a6f-48b1-412e-a4c7-fd18a71e6a39.jpg)

### Steps To Reproduce

```markdown
Just tried logging in
```

### Expected Behavior

Well for me to be able to log in

### Platform

```markdown
- Device model: VIVO V15
- CPU architecture: Mediatek Helio P70 2.11GHz
- Android version: 11
- PojavLauncher version: Latest Release
```

**Comment by ghost** [comment]
Try updating to the latest actions build and try again.

**Comment by khanhduytran0** [comment]
Your account is under 18 and needs to be linked to your parent's account.
