### ISSUE TITLE
[BUG] clients crashes

### ISSUE THREAD

**Issue by 5182008** [PojavLauncherTeam/PojavLauncher#2721]
### Describe the bug

Clients crashes everytime i launch it
Pixel linar cmpack wind optifine client crashes everytime i lainch

Except vanilla minecraft it works perfectly

### The log file and images/videos

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/6/22 2:20 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Yr.p(Unknown Source)
	at nt.q(Unknown Source)
	at fR.dT(Unknown Source)
	at fR.run(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at pl.cmpack.Main.main(Main.java:25)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Yr.p(Unknown Source)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [gP['asianboiii'/75, l='MpServer', x=-347.69, y=68.00, z=-451.76]]
	Chunk stats: MultiplayerChunkCache: 41, 41
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -181.00,64.00,-376.00 - World: (-181,64,-376), Chunk: (at 11,4,8 in -12,-24; contains blocks -192,0,-384 to -177,255,-369), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 17097 game time, 17097 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 24 total; [Bx['Squid'/258, l='MpServer', x=-295.09, y=61.78, z=-474.75], Bx['Squid'/259, l='MpServer', x=-294.53, y=61.00, z=-467.63], Bx['Squid'/709, l='MpServer', x=-289.78, y=57.84, z=-426.09], Bd['Bat'/902, l='MpServer', x=-384.25, y=15.10, z=-418.25], AV['Zombie'/76, l='MpServer', x=-301.66, y=68.00, z=-461.66], Ae['Creeper'/664, l='MpServer', x=-336.50, y=65.00, z=-470.50], Ae['Creeper'/665, l='MpServer', x=-337.77, y=65.00, z=-469.73], Ae['Creeper'/155, l='MpServer', x=-364.47, y=64.00, z=-421.47], AI['Skeleton'/987, l='MpServer', x=-418.81, y=64.00, z=-448.47], gP['asianboiii'/75, l='MpServer', x=-347.69, y=68.00, z=-451.76], AI['Skeleton'/29, l='MpServer', x=-345.16, y=40.00, z=-406.66], AV['Zombie'/989, l='MpServer', x=-380.00, y=23.00, z=-487.59], AV['Zombie'/670, l='MpServer', x=-299.75, y=67.00, z=-499.78], Ae['Creeper'/287, l='MpServer', x=-341.47, y=64.00, z=-473.66], Ae['Creeper'/1188, l='MpServer', x=-332.50, y=65.00, z=-470.50], Ae['Creeper'/487, l='MpServer', x=-334.42, y=63.00, z=-476.55], AI['Skeleton'/1191, l='MpServer', x=-326.47, y=70.00, z=-463.16], AQ['Spider'/1064, l='MpServer', x=-345.50, y=63.00, z=-483.50], AI['Skeleton'/1192, l='MpServer', x=-313.97, y=70.00, z=-454.59], AQ['Spider'/1065, l='MpServer', x=-347.50, y=63.00, z=-484.50], AQ['Spider'/1193, l='MpServer', x=-322.38, y=70.00, z=-452.69], AI['Skeleton'/1066, l='MpServer', x=-349.50, y=63.00, z=-486.50], AI['Skeleton'/302, l='MpServer', x=-348.50, y=39.00, z=-406.50], Bd['Bat'/1083, l='MpServer', x=-417.44, y=55.09, z=-447.16]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at kR.r(Unknown Source)
	at fR.q(Unknown Source)
	at fR.run(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at pl.cmpack.Main.main(Main.java:25)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Linux (aarch64) version Android-8.1.0
	CPU: 9x null
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 219447416 bytes (209 MB) / 571473920 bytes (545 MB) up to 571473920 bytes (545 MB)
	JVM Flags: 3 total; -Xms607M -Xmx607M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	Launched Version: cmpack_1.8.8
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'cmclient'
	Type: Client (map_client.txt)
	Resource Packs: fruitberries official pack - short swords.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x null

### Steps To Reproduce

```markdown
1. I launch a client
2. It crashes 17 or something seconds after loading
```

### Expected Behavior

I expected the clients to launch smoothly

### Platform

```markdown
- Device model: oppo a3s
- CPU architecture: unknown
- Android version: 8
- PojavLauncher version: latest google play version
```

### Anything else?

Would like the clients to not crash thats alk

**Comment by NotAHero04** [comment]
Maybe try a new world?

**Comment by 5182008** [comment]
Its not about the world i think its the launcher cause everytime i launch a
client it just crashes 100%

**Comment by moha0116** [comment]
Try gl4es 1.1.5 + partial 3.2 if its 1.12.2-

**Comment by 5182008** [comment]
Tried it on optifine 1.9.2_HD_U_E3
and it crashed again :(

**Comment by 5182008** [comment]
Ill send a crash report log if needed.

**Comment by Mathias-Boulay** [comment]
custom client, not really our problem.
maybe fixed on the release candidate
