### ISSUE TITLE
How to play forge 1.17 - 18 + ?

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#2722]
### Is this request related to a bug?

No

### Describe the request.

How to install forge 1.17 - 18+

### Anything else?

How to install forge 1.17 - 18+

**Comment by NotAHero04** [comment]
They are not yet supported.

**Comment by villager1314** [comment]
它们尚不受支持，最高正式版可以用1.16.5

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
