### ISSUE TITLE
[BUG] Pojav Launcher has stopped unexpectedly

### ISSUE THREAD

**Issue by Siyey** [PojavLauncherTeam/PojavLauncher#2725]
### Describe the bug

![1644594167594](https://user-images.githubusercontent.com/99494182/153622183-5f52c1ea-1074-4d58-9cd3-83919e83c3c7.jpg)
How I resolve this?

### The log file and images/videos

What i do?

### Steps To Reproduce

```markdown
I start Pojav,I click on Log in bit It kicks me
```

### Expected Behavior

Game dont launch

### Platform

```markdown
- Device model: Idk
- CPU architecture: idk
- Android version: idk
- PojavLauncher version: latest
```

**Comment by InfiniXDerg** [comment]
Missing things
Device model
CPU Arch (today is ARM64 but can be ARM32)
Android version: go to about this phone :trollface:  (Also phone model Will appear)

**Comment by Siyey** [comment]
Device model i dont know. Cpu i think os arm32. Version is chromebook

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
