### ISSUE TITLE
Forge 1.17+

### ISSUE THREAD

**Issue by CharredMist** [PojavLauncherTeam/PojavLauncher#2726]
### Is this request related to a bug?

Launching forge 1.17 and up just crashes

### Describe the request.

Can PojavLauncher developers work for Forge 1.17 and up?

I want to play on my friends' server but I can't.

### Anything else?

Plz.

**Comment by CharredMist** [comment]
Actually
Nobody minds that
In gonna delete this tomorrow ._.

**Comment by NotAHero04** [comment]
The problem still needs more investigation and development.

**Comment by CharredMist** [comment]
> The problem still needs more investigation and development.

Ok
