### ISSUE TITLE
[BUG] Essentials causes crashes everytime

### ISSUE THREAD

**Issue by Nitrocosm** [PojavLauncherTeam/PojavLauncher#2727]
### Describe the bug

Whenever you install Essentials or a mod that requires it on Forge, the game will crash after a few seconds. This is not the case when it's not present.

### The log file and images/videos

[fml-client-latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052140/fml-client-latest.log)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052141/latest.log)

### Steps To Reproduce

```markdown
1. Install Forge and run it.
2. Install any mod with Essentials built in, such as Scrollable Tooltips
3. Run Forge again.
4. Crash
```

### Expected Behavior

The game should not be crashing with Essentials installed.

### Platform

```markdown
- Device model: Mi 10T
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release
```

**Comment by mchnjt** [comment]
Log says `Name and ID cannot be blank`? Buy Minecraft

**Comment by khanhduytran0** [comment]
> [fml-client-latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052140/fml-client-latest.log)
> [latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052141/latest.log)

These aren’t `latestlog.txt`

**Comment by Nitrocosm** [comment]
> Log says `Name and ID cannot be blank`? Buy Minecraft

I have Minecraft, Tiz3n is my name and I migrated.



> > [fml-client-latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052140/fml-client-latest.log)
> > [latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052141/latest.log)
> 
> These aren’t `latestlog.txt`

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052452/latestlog.txt)
here's latestlog.txt, modcore is not the issue as I've run it alongside Essentials on other systems.

**Comment by khanhduytran0** [comment]
> > Log says `Name and ID cannot be blank`? Buy Minecraft
> 
> I have Minecraft, Tiz3n is my name and I migrated.
> 
> > > [fml-client-latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052140/fml-client-latest.log)
> > > [latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052141/latest.log)
> > 
> > 
> > These aren’t `latestlog.txt`
> 
> [latestlog.txt](), modcore is not the issue as I've run it alongside Essentials on other systems.

Looks like you need to enable VBO.

**Comment by Nitrocosm** [comment]
I have now tried that, and the same result of the game crashing happens.
[latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8052483/latestlog.1.txt)

Everything else in Pojav is the same, and 3GB of RAM is more than enough for Minecraft to run.

**Comment by khanhduytran0** [comment]
Got it. There’s likely a missing OpenGL function. Maybe try switching to other renderers? (gl4es 1.1.5 or VGPU)

**Comment by Nitrocosm** [comment]
The crashing happened earlier when using any other renderer than gl4es 1.1.4.

I removed optifine as well, and same thing still happened.

[latestlog (2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8053240/latestlog.2.txt)

**Comment by Mathias-Boulay** [comment]
Essentials has a fix on their end, wait for it to get released.
