### ISSUE TITLE
maybe add gyro controls for the camera(as a toggle in the settings)

### ISSUE THREAD

**Issue by USMP-lancer** [PojavLauncherTeam/PojavLauncher#2728]
### Describe the request.

most phones have a gyroscope, perhaps use that to move the camera when a special setting is enabled

### Anything else?

if possible, add a button or a special keybind that can toggle ingame(obviously one not used by minecraft, like ctrl+shift+alt+g), so it can be toggled, and also consider making the touch controls not move camera when its active

**Comment by mchnjt** [comment]
> ### Is this request related to a bug?
> _No response_
> 
> ### Describe the request.
> most phones have a gyroscope, perhaps use that to move the camera when a special setting is enabled
> 
> ### Anything else?
> if possible, add a button or a special keybind that can toggle ingame(obviously one not used by minecraft, like ctrl+shift+alt+g), so it can be toggled, and also consider making the touch controls not move camera when its active

Camera what?

**Comment by khanhduytran0** [comment]
Looks like they want Pojav VR Edition

**Comment by mchnjt** [comment]
> if possible, add a button or a special keybind that can toggle ingame(obviously one not used by minecraft, like ctrl+shift+alt+g), 

![Screenshot_20220212-105916](https://user-images.githubusercontent.com/83752061/153694157-bee00113-0021-4db5-a692-3f339be3c708.png)

**Comment by ajit56** [comment]
> Looks like they want Pojav VR Edition

Nice Idea

**Comment by SprainedSpark89** [comment]
get a oculus last time i checked it was free on oculus idk why

**Comment by USMP-lancer** [comment]
> > ### Is this request related to a bug?
> > _No response_
> > ### Describe the request.
> > most phones have a gyroscope, perhaps use that to move the camera when a special setting is enabled
> > ### Anything else?
> > if possible, add a button or a special keybind that can toggle ingame(obviously one not used by minecraft, like ctrl+shift+alt+g), so it can be toggled, and also consider making the touch controls not move camera when its active
> 
> Camera what?

i meant camera as in controlling where your character faces, which yes, it essentailly pojav vr lmao

**Comment by winnerscdik** [comment]
> > > ### Is this request related to a bug?
> > > _No response_
> > > ### Describe the request.
> > > most phones have a gyroscope, perhaps use that to move the camera when a special setting is enabled
> > > ### Anything else?
> > > if possible, add a button or a special keybind that can toggle ingame(obviously one not used by minecraft, like ctrl+shift+alt+g), so it can be toggled, and also consider making the touch controls not move camera when its active
> > 
> > 
> > Camera what?
> 
> i meant camera as in controlling where your character faces, which yes, it essentailly pojav vr lmao

The fuck

**Comment by USMP-lancer** [comment]
funny gyro go brrrt

**Comment by SprainedSpark89** [comment]
'-'

**Comment by Mathias-Boulay** [comment]
Ngl I kinda want to implement gyro controls, really good for casual players I think

**Comment by artdeell** [comment]
implemented

**Comment by Felix14-v2** [comment]
Works... buggy.
https://youtu.be/E6pwO_YSZBY

**Comment by artdeell** [comment]
> Works... buggy. https://youtu.be/E6pwO_YSZBY

@Felix14-v2 don't see the problem, tilt phone down = look down

**Comment by Felix14-v2** [comment]
> @Felix14-v2 don't see the problem, tilt phone down = look down

Take a closer look – when the phone tilts down, camera doesn't actually move exactly down,but at a strange angle.
Also, when I tilt to the left, the camera moves to the ≈right (also at weird angle).
