### ISSUE TITLE
shutting down internal server bug

### ISSUE THREAD

**Issue by HypnoGreen** [PojavLauncherTeam/PojavLauncher#2731]
### Describe the bug

i downloaded the forge version of minecraft and i get an error when creating the world and the world crashes even without the mod

this pops up when the world is created: shutting down internal server

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8054213/latestlog.txt)

### Steps To Reproduce

```markdown
1. I launched minecraft without mods on the forge version
2. I create the world
3. It ends up crashing with an error shutting down internal server, And the game closes
```

### Expected Behavior

I expected the world to be normal

### Platform

```markdown
- Device model: HUAWEI STK-LX1
- CPU architecture: 4x ARM Cortex-A53
- 1709MHz, 4x ARM Cortex-A73 2189MHz
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

Reinstalling the app didn't help.

**Comment by Yusufbsk2** [comment]
Yes

**Comment by khanhduytran0** [comment]
Please login with an online account to continue. See #2679 for more info.
