### ISSUE TITLE
[BUG] i can't install optifine 1.17.1

### ISSUE THREAD

**Issue by warmrecord** [PojavLauncherTeam/PojavLauncher#2732]
### Describe the bug

application exited with code 1

### The log file and images/videos

![Uploading Screenshot_2022-02-13-17-28-51-29_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

### Steps To Reproduce

```markdown
install optifine and out the app with application exited with code 1
```

### Expected Behavior

i wish you can help me

### Platform

```markdown
- Device model: Q3 Pro 5G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by GoneSubject** [comment]
send log?

**Comment by Yashjbk17** [comment]
You need to download a patcher

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
