### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by rhhf9** [PojavLauncherTeam/PojavLauncher#2733]
### Is this request related to a bug?

最新安卓12玩1.12.2老是崩溃求更新。

### Describe the request.

1,进入游戏 2,玩一会就崩溃 版本号，1.12.2

### Anything else?

没了

**Comment by SprainedSpark89** [comment]
latest log?

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
