### ISSUE TITLE
Close those stupid issues and tag them

### ISSUE THREAD

**Issue by zhenchao** [PojavLauncherTeam/PojavLauncher#2734]
they don't provide any useful information (eg log, platform), only unreasonable requests, and I think any mod requests should be ignored at this stage

**Comment by SprainedSpark89** [comment]
what?

**Comment by ghost** [comment]
why close them many people play java edition from mods

**Comment by SprainedSpark89** [comment]
and the enhancement is to improve pojavlauncher

**Comment by SprainedSpark89** [comment]
and there is a bug report to help with the issues

**Comment by Mathias-Boulay** [comment]
Closing this stupid issue among other ones
