### ISSUE TITLE
[BUG] Forge Issues

### ISSUE THREAD

**Issue by NatickYT** [PojavLauncherTeam/PojavLauncher#2735]
### Describe the bug

Forge 1.16.5 36.2.20 Woked Then A While Later Didn't Work Anymore

### The log file and images/videos

None

### Steps To Reproduce

```markdown
Unsure How It Happened
```

### Expected Behavior

The Game To Have No Issues Loading

### Platform

```markdown
- Device model: Samsung Galaxy S20 Ultra
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Latest Release On Google Play (crocus-v3_openjdk)
```

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8078904/latestlog.txt)

**Comment by khanhduytran0** [comment]
Since the log is not provided, we assume that you didn't login with an online account. See #2679 for more info.

**Comment by NatickYT** [comment]
> Since the log is not provided, we assume that you didn't login with an online account. See #2679 for more info.

I Don't Remember If I Was Then But I Am Now I Just Don't Know How To Get A Log From A Few Months Ago

**Comment by SprainedSpark89** [comment]
are you using mods or just optifine?

**Comment by NatickYT** [comment]
> are you using mods or just optifine?

No Mods Just Trying To Get It To Load Before I Add Any Mods

**Comment by NatickYT** [comment]
> > are you using mods or just optifine?
> 
> No Mods Just Trying To Get It To Load Before I Add Any Mods

Also No Optifine

**Comment by SprainedSpark89** [comment]
load the mods at start

**Comment by NatickYT** [comment]
> load the mods at start

Thing Is The Only Time It Worked Was Without Mods And Now Its Not Working At All

**Comment by NatickYT** [comment]
I Added The Log

**Comment by SprainedSpark89** [comment]
are you using a offline account?

**Comment by SprainedSpark89** [comment]
i don't want people to be angry at you

**Comment by NatickYT** [comment]
> are you using a offline account?

No I'm Using A Microsoft Account

**Comment by SprainedSpark89** [comment]
then idk

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
