### ISSUE TITLE
Fabric Issue

### ISSUE THREAD

**Issue by NatickYT** [PojavLauncherTeam/PojavLauncher#2736]
### Describe the bug

When I Try To Install Fabric Installer It Doesn't Work And The App Crashes/Reloads

### The log file and images/videos

GitHub Isn't Letting Me Upload The Screen Recording Or Log

### Steps To Reproduce

```markdown
1. Download fabric-installer-1.10.2.jar
2. Do Steps In Video
```

### Expected Behavior

Fine Intallation Without Issues

### Platform

```markdown
- Device model: Samsung Galaxy S20 Ultra
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Latest Release On Google Play (crocus-v3_openjdk)
```

**Comment by ghost** [comment]
It's difficult to debug this without a log. Try to upload the latestlog.txt again.

**Comment by NatickYT** [comment]
> It's difficult to debug this without a log. Try to upload the latestlog.txt again.

It Only Lets Me Import Photos

**Comment by SprainedSpark89** [comment]
click or press "Attach files by dragging & dropping, selecting or pasting them." if on mobile then press files then browse to the pojavlauncher folder then click latest log and if you press hold it press open

**Comment by NatickYT** [comment]
> click or press "Attach files by dragging & dropping, selecting or pasting them." if on mobile then press files then browse to the pojavlauncher folder then click latest log and if you press hold it press open

That Isn't A Thing On The GitHub App

**Comment by SprainedSpark89** [comment]
then use web
