### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by NatickYT** [PojavLauncherTeam/PojavLauncher#2738]
### Describe the bug

I Set Custom Controls Saved As default.json That Would Show Up Fine On 1.18.1 And rd-160052 But Once I Load 1.6.1 The Controls Reset To Default

### The log file and images/videos

I Don't Have Logs From 1.18.1, rd-160052 Or 1.6.1

### Steps To Reproduce

```markdown
Set Custom Controls On 1.18.1 And rd-160052 Then Load 1.6.1
```

### Expected Behavior

Controls Not To Reset

### Platform

```markdown
- Device model: Samsung Galaxy S20 Ultra
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Latest Release On Google Play
```

### Anything else?

I Was Logged In A Microsoft Account If That Affects Anything

**Comment by GoneSubject** [comment]
you can just choose default control in control setting in the game

**Comment by NatickYT** [comment]
> you can just choose default control in control setting in the game

The Default Is Universal And Resets

**Comment by SprainedSpark89** [comment]
hey swipe left from the right then click custom controls
and if your using the custom controls on minecraft it will not work
in rd there is no custom controls

**Comment by NatickYT** [comment]
> hey swipe left from the right then click custom controls and if your using the custom controls on minecraft it will not work in rd there is no custom controls

1 Is Stone
2 Is Dirt
3 Is Cobble
4 Is Wood
And G Is Summon A Steve

**Comment by khanhduytran0** [comment]
You saved it as `default`, that’s why, `default.json` gets overwritten every launch. Please use a different name.
