### ISSUE TITLE
[F-Req] <Controls>

### ISSUE THREAD

**Issue by NatickYT** [PojavLauncherTeam/PojavLauncher#2740]
### Is this request related to a bug?

No

### Describe the request.

Custom Controls Able To Be Set For Multiple Versions Or One Version

### Anything else?

Eg: 1.18.1 And 1.18.0 Share Controls rd-160052 And 1.12.2 Have Seperate But All Versions Share Movement Controls

**Comment by Mathias-Boulay** [comment]
Won't be done, as default control can be set via settings
