### ISSUE TITLE
[BUG] Fix My Minecraft...

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2743]
### Describe the bug

I'm trying to use **1.18** for the second time **AFTER** fixing the `assets-v0` but when I clicked *"Play Anyways"* the game exits. When I click okay instead, it showed me the *Storage Permission Required* error a few times, and then it just exits after that.

### The log file and images/videos

```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3376) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3612) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7737) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) Caused by: java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference at net.kdt.pojavlaunch.Tools.dpToPx(Tools.java:386) at net.kdt.pojavlaunch.BaseMainActivity.<init>(BaseMainActivity.java:53) at net.kdt.pojavlaunch.MainActivity.<init>(MainActivity.java:18) at java.lang.Class.newInstance(Native Method) at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) at android.app.Instrumentation.newActivity(Instrumentation.java:1267) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3364) ... 11 more
```

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8076244/latestlog.txt)

### Steps To Reproduce

```markdown
I'm not sure if this is how to do it...

1. Open pojavLauncher and sign-in
2. Do the 1.18 fix
3. Get fabric
4. Install fabric 1.18
5. Select OK on the pop-up as Play Anyway still brake
5. Error
```

### Expected Behavior

I expect the game to launch and  not insta-crash

### Platform

```markdown
- Device model: R96-14268.67.0
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I'm using fabric 1.18 on version 12.12 with VGPU render, ill try ZLink tho

EDIT: ZLink dose not work

**Comment by khanhduytran0** [comment]
The log has already told what to do, have you read it first? :eyes:
```
A potential solution has been determined:
	 - Replace mod 'DCCH' (dcch) 1.0 (/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/DCCH-1.17.x.jar) with any version that is compatible with:
		 - minecraft 1.18.1
Unmet dependency listing:
	 - Mod 'DCCH' (dcch) 1.0 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
```

**Comment by khanhduytran0** [comment]
For `Storage Permission Required`, it only happen on crash report, which is no longer required.

For `java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference`, were you resizing the launcher window while ingame? PojavLauncher currently doesn’t handle it properly.

**Comment by Errorbot1122** [comment]
Um, no, I was just launching the game

here is a newer version of [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8076473/latestlog.txt) if you want it...

**Comment by NotAHero04** [comment]
You still didn't remove the incompatible mod

>>> Unmet dependency listing:
	 - Mod 'DCCH' (dcch) 1.0 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!

**Comment by Errorbot1122** [comment]
oh, lol, I forgot to check the latest log myself 🤦 

I removed DCCH from my mods folder and it still crashes...

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8080749/latestlog.txt)

**Comment by SprainedSpark89** [comment]
go to settings apps then manage your apps go to pojavlauncher then turn on storage permission.
i had this issue but with minecraft education edition

**Comment by Errorbot1122** [comment]
![image](https://user-images.githubusercontent.com/65428515/154325447-2bb2d678-2367-4dd7-8745-aa8ad39d0811.png)

It wont let me...

**Comment by SprainedSpark89** [comment]
click more settings and permissions

**Comment by Errorbot1122** [comment]
I did, that's is the window in the left

**Comment by SprainedSpark89** [comment]
idk then

**Comment by NotAHero04** [comment]
> oh, lol, I forgot to check the latest log myself 🤦
> 
> I removed DCCH from my mods folder and it still crashes...
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8080749/latestlog.txt)

Try making a file called `custom_env.txt` and write `LIBGL_NOINTOVLHACK=1` to it.

**Comment by Errorbot1122** [comment]
where do i put it @NotAHero04 ?

**Comment by NotAHero04** [comment]
It should be in the outermost folder of the PojavLauncher directory

**Comment by Errorbot1122** [comment]
Do you mean the files folder or the .minecraft

![ProjavLauncher folder](https://user-images.githubusercontent.com/65428515/154399923-eb443f6f-c17e-4c53-866e-dd3b6f7d1f65.png)

**Comment by NotAHero04** [comment]
Yes, that's it

**Comment by Errorbot1122** [comment]
uh...

it insta-crashes still...

But it does not report game exited

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8091992/latestlog.txt)
[custom_env.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8091995/custom_env.txt)
[per-version-config.json.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8092013/per-version-config.json.txt)

**Comment by NotAHero04** [comment]
Dynamic FPS mod is the problem.

**Comment by Errorbot1122** [comment]
IT WORKS, but Minecraft keeps trying to load forever...

https://user-images.githubusercontent.com/65428515/154738888-a9b4b0bc-a79d-49f2-9af0-a020a6da1ca0.mp4

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8099447/latestlog.txt)
[per-version-config.json.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8099449/per-version-config.json.txt) *(I changed my render)*

**Comment by Errorbot1122** [comment]
@NotAHero04 ?

**Comment by SprainedSpark89** [comment]
sometimes mods don't work correctly

**Comment by Errorbot1122** [comment]
so what happend?

**Comment by SprainedSpark89** [comment]
the mod maybe on a issue that lists mods that don't work

**Comment by Errorbot1122** [comment]
I removed sodium and the sameting happens :(

**Comment by SprainedSpark89** [comment]
any other mods not all of them are listed and sometimes you may have to change settings

**Comment by Errorbot1122** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8143330/latestlog.txt)

**Comment by SprainedSpark89** [comment]
full log

**Comment by Errorbot1122** [comment]
isn't that the full log?
