### ISSUE TITLE
[BUG] Right click act like back button

### ISSUE THREAD

**Issue by FaeyzaNursandy** [PojavLauncherTeam/PojavLauncher#2744]
### Describe the bug

When I plug external mouse, and then press right click it act like back button

### The log file and images/videos

https://youtu.be/fQNJC-x1SPk

### Steps To Reproduce

```markdown
1. Plug external mouse
2. Open PojavLauncher
3. Play Minecraft
4. Click right click button
```

### Expected Behavior

I expect it's working like right click button (place block)

### Platform

```markdown
- Device model: Realme C17 6/256G
- CPU architecture: 64-bit ARMv8-A
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by SprainedSpark89** [comment]
yah it's weird like my xbox controller the weirdest controls

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
