### ISSUE TITLE
[BUG] When i go to graphics settings, the game is crashing

### ISSUE THREAD

**Issue by TheDanikReal** [PojavLauncherTeam/PojavLauncher#2745]
### Describe the bug

When i go to settings the game is crashing

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8079971/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PoJavLauncher
2. Choose 1.13.0
3. Go to settings
4. Go to graphics settings
5. Game is crashed
```

### Expected Behavior

I except to game to launch settings

### Platform

```markdown
- Device model: Xiaomi 9C 3/64G
- CPU architecture: 
- Android version: 10
- PojavLauncher version:
```

**Comment by NotAHero04** [comment]
This is a known bug. You can (kinda) avoid this by using OptiFine.

**Comment by TheDanikReal** [comment]
> This is a known bug. You can (kinda) avoid this by using OptiFine.

Thanks! Im gonna install optifine next day and test it

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
