### ISSUE TITLE
[BUG] <El Mundo no carga con forge y finaliza con el codigo -1 >

### ISSUE THREAD

**Issue by VXYZ666** [PojavLauncherTeam/PojavLauncher#2746]
### Describe the bug

Al utilizar el forge de la versión 1.12.2 e intentar crear un mundo ya sea con mods o sin ellos el mundo no carga y sale "Shutting down internal server.." y termina cerrándose el juego diciendo " la aplicación/juego a finalizado con el código -1" ...no sé si habrá una solución ...

### The log file and images/videos

![Screenshot_20220211-141825](https://user-images.githubusercontent.com/79683597/154367365-c5dbfe18-667a-42a1-998a-a413ed889041.png)
![Screenshot_20220211-140630](https://user-images.githubusercontent.com/79683597/154367367-3455b4b8-cc36-4c18-82e6-5f70ef5cb23a.png)
![Screenshot_20220211-135702](https://user-images.githubusercontent.com/79683597/154367370-89a94de4-1c0f-4e90-b0cd-29b759a76965.png)
![Screenshot_20220211-132257](https://user-images.githubusercontent.com/79683597/154367372-98d91087-e42b-4e10-b6a7-44d91f26924c.png)
Estos son el registro de errores que ocurren al cerrarse el juego...

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

Debería de poder abrir el mundo sin ninguna inconveniente ....

### Platform

```markdown
- Device model: Motorola one macro
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: última versión (play store)
```

### Anything else?

Nada más solo pido una solución para que pueda cargarme el mundo por favor ....

**Comment by GaucovyAero** [comment]
**Buy Minecraft.**

https://www.youtube.com/shorts/qb-kraUPORY

**Comment by SprainedSpark89** [comment]
buy minecraft

**Comment by SprainedSpark89** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/2679

**Comment by Mathias-Boulay** [comment]
buy minecraft
