### ISSUE TITLE
Clouds?[F-Req] <Short description>

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#2748]
### Is this request related to a bug?

Idk

### Describe the request.

You should optimize the cloud so it won't  crash every time I put them on

### Anything else?

My spec are:
Samsung s20 fe
6gb of ram
120 storage
Snapdragon 823

Pls fix

**Comment by SprainedSpark89** [comment]
we don't make minecraft

**Comment by kuzy21** [comment]
Wdum

**Comment by NatickYT** [comment]
PojavLauncher Doesn't Make Minecraft It Just Loads It

**Comment by SprainedSpark89** [comment]
try optifine and i forgot if clouds fast is vanilla or not

**Comment by kuzy21** [comment]
I have optifine on and with fast, or regular clouds the game still crashes

**Comment by SprainedSpark89** [comment]
well maybe it crashes because the cloud texture is very big

**Comment by kuzy21** [comment]
Is there a way to fix it?

**Comment by SprainedSpark89** [comment]
well you can do other things here is ways you can optimize minecraft you can do some of these
https://help.minecraft.net/hc/en-us/articles/4410246518669-Optimizing-Performance-in-Minecraft
https://www.google.com/search?q=how+to+optimize+minecraft+optifine&rlz=1CAXGER_enUS970&sxsrf=APq-WBuYjvCeiPzl6AjpV9gr4YSdDCDIaQ%3A1645560507919&ei=u0IVYtG9N5a-kPIPiZKUcA&oq=how+to+optimize+minecraft+op&gs_lcp=Cgdnd3Mtd2l6EAMYADIFCAAQgAQyBggAEBYQHjIFCAAQhgM6BwgAEEcQsAM6BwgAELADEEM6BAgAEENKBQg8EgExSgQIQRgASgQIRhgAUO4EWKgKYOYfaAFwAHgAgAHRAYgBpQSSAQUwLjIuMZgBAKABAcgBCsABAQ&sclient=gws-wiz&safe=active&ssui=on
some things may change

**Comment by kuzy21** [comment]
Here let Me show you a video k

**Comment by kuzy21** [comment]
Here:
https://youtu.be/AAytRSszWMs

**Comment by SprainedSpark89** [comment]
it does it because when you turn it on it displays it

**Comment by kuzy21** [comment]
What do you mean

**Comment by SprainedSpark89** [comment]
when you turn on a setting in game it will equip it in game

**Comment by kuzy21** [comment]
It also crashes when I turn it on before joining a world watch

**Comment by kuzy21** [comment]
I am going to send a video rn

**Comment by kuzy21** [comment]
Here: https://youtu.be/sT7M_XFw1U4

**Comment by SprainedSpark89** [comment]
does it happen when you make a world?

**Comment by kuzy21** [comment]
No but when I join it crashes like 10 seconds later

**Comment by SprainedSpark89** [comment]
with clouds or without?

**Comment by kuzy21** [comment]
With clouds

**Comment by SprainedSpark89** [comment]
ok

**Comment by kuzy21** [comment]
So how can I fix it

**Comment by kuzy21** [comment]
hello anyone there!?

**Comment by SprainedSpark89** [comment]
Yes

**Comment by kuzy21** [comment]
Nvm it's fixed with the new github release
