### ISSUE TITLE
[BUG] <Betacraft proxy not working on Pojavlauncher>

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2750]
### Describe the bug

when i put the betacraft proxy java arguments in it doesn't work

### The log file and images/videos

none

### Steps To Reproduce

```markdown
put the betacraft proxy java arguments in the java arguments open a old version then it doesn't work
```

### Expected Behavior

old versions to have sound again

### Platform

```markdown
- Device model: samsung galaxy tab e
- CPU architecture: 
- Android version: 7.1.1
- PojavLauncher version: playstore
```

### Anything else?

wishes for older versions of minecraft to work properly

**Comment by GaucovyAero** [comment]
i think you should try a newer version of pojav

**Comment by SprainedSpark89** [comment]
i have latest i think

**Comment by GaucovyAero** [comment]
> i have latest i think

**Latest from** `v3_openjdk` **branch now works, the issue has been resolved.** 

To update your launcher, check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`

To use the Betacraft proxy, use this JVM argument as follows:
`-Dhttp.proxyHost=betacraft.uk -Djava.util.Arrays.useLegacyMergeSort=true`
Also make sure to NOT use the ports (like shown in the picture below), they don't work even on PC as of now, as they aren't relevant anymore.

![image](https://user-images.githubusercontent.com/85581164/188155873-3ab9d0e3-33af-4d29-b4b8-183a3185e98f.png)

**Comment by Mathias-Boulay** [comment]
it has been shown to work with current dev builds, so the issue will be closed

**Comment by SprainedSpark89** [comment]
> > i have latest i think
> 
> **Latest from** `v3_openjdk` **branch now works, the issue has been resolved.**
> 
> To update your launcher, check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`
> 
> To use the Betacraft proxy, use this JVM argument as follows: `-Dhttp.proxyHost=betacraft.uk -Djava.util.Arrays.useLegacyMergeSort=true` Also make sure to NOT use the ports (like shown in the picture below), they don't work even on PC as of now, as they aren't relevant anymore.
> 
> ![image](https://user-images.githubusercontent.com/85581164/188155873-3ab9d0e3-33af-4d29-b4b8-183a3185e98f.png)

thx but it could of been because i was using an offline account at the time
