### ISSUE TITLE
[BUG] External Keyboard and mouse

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2751]
### Describe the bug

I can right click but When i left click its not working it doesn't brake block :/

### The log file and images/videos

Nothing.

### Steps To Reproduce

```markdown
Start pojav launcher
Play any version
Left click not working
```

### Expected Behavior

Whats the problem?

### Platform

```markdown
- Device model: Oppo A12 3/32G
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Virgl build
```

### Anything else?

No.

**Comment by LastCleanShirt** [comment]
Yeah Same As Mine, it only works on certain gui like menu and settings,

Also did you try to reinstall it?

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
