### ISSUE TITLE
[Documentary] [Bug] 1.19 snapshots are not working

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher#2753]
### Describe the bug

Even with 1.18 patch, the game will still not able to load properly.

### The log file and images/videos

latestlog.txt with my current work:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8097776/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download 1.19 experimental snapshot 1 on the official website.
2. Apply the assets-v0 patch for 1.18.x.
3. Open the game.
It will bootloop once then crashes.
```

### Why the game crashes

The underlying cause of the issue is because of a new shader program, called `rendertype_entity_translucent_emissive`. This was definitely not covered in any patch, so it's expected to not work.

### Expected behavior

The game should be able to launch.

### Platform

```markdown
This issue should affect every device. However, here's my information for reference.
- Device model: Vsmart Star 5
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by ghost** [comment]
I also tried it and it didn't work with any renderer. Looks to be yet another shader reload problem.

**Comment by NotAHero04** [comment]
Zink/VirGL should work. Did you try one of these?

**Comment by ghost** [comment]
I tried both with no success.

**Comment by ghost** [comment]
I could always try it again to see if I can make it run, but for now nothing worked.

**Comment by NotAHero04** [comment]
@Smokeybear12 Could you try this patch?
[assets-v0.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8098212/assets-v0.zip)

**Comment by ghost** [comment]
Is this the 1.18 one?

**Comment by NotAHero04** [comment]
It also includes the new patched shader program.

**Comment by ghost** [comment]
Alright when I get the chance I will try it.

**Comment by ghost** [comment]
Sorry for the delayed response. Everything seems to work just fine with the patcher.

**Comment by NickyisSneaking** [comment]
But in 32 bit device it's still bugged it keep bootloop

**Comment by NatickYT** [comment]
It Works Fine On Android 12, Samsung Galaxy S20 Ultra

**Comment by WesleyVanNeck** [comment]
> It Works Fine On Android 12, Samsung Galaxy S20 Ultra

s20 aint 32 bit

**Comment by PugBroKid** [comment]
now im getting the reloads once anybody know how to fix?

**Comment by ghost** [comment]
Please send the latestlog.txt if you have an issue.

**Comment by PugBroKid** [comment]
ok

**Comment by PugBroKid** [comment]
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8271450/latestcrash.txt)

**Comment by PugBroKid** [comment]
Do Di Doo Da Do Di Doo DA! Da do da do di dad do

**Comment by NotAHero04** [comment]
22w11a somehow reverted this change, but the pack above is still able to work. (by changing the pack version to 9)
