### ISSUE TITLE
 <Short description>

### ISSUE THREAD

**Issue by vasu1234321** [PojavLauncherTeam/PojavLauncher#2754]
### Describe the bug

I want  pojav launcher vgpu  link 

### The log file and images/videos

Pls

### Steps To Reproduce

```markdown
Pls
```

### Expected Behavior

Pls

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Pls

**Comment by Mathias-Boulay** [comment]
vgpu is no more
