### ISSUE TITLE
Не могу открыть мир

### ISSUE THREAD

**Issue by N3vPr0** [PojavLauncherTeam/PojavLauncher#2756]
### Describe the bug

Когда я захожу в мир с Forge 1.12.2, то сначало у меня пишет Shutting down internal server, а потом лаунчер закрывается с ошибкой с кодом -1.
Это происходит на последней версии лаунчера. (из play market)

### The log file and images/videos

![Screenshot_20220219_083815](https://user-images.githubusercontent.com/96036449/154788028-0d3c86da-4ea6-446b-8615-89ee67c703f5.jpg)
![Screenshot_20220219_083826](https://user-images.githubusercontent.com/96036449/154788039-d0a7d6a9-0482-4850-a878-45bfb2171047.jpg)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8101519/latestlog.txt)

### Steps To Reproduce

```markdown
1. Запуск Pojavlauncher
2. Создание или запуск мира
3. Ждать
4. Пишет Shutting down internal server
5. Вылетает ошибка с кодом -1
```

### Expected Behavior

Я ожидаю, что мир запустится

### Platform

```markdown
Модель устройства: Vivo2015 500mb
Архитектура процессора: aarch64
Версия андроида: 10
Версия Pojavlauncher: crocus-v3_openjdk (последняя)
```

**Comment by NotAHero04** [comment]
#2679

**Comment by ghost** [comment]
Вам нужна лицензия что бы не вылетало
