### ISSUE TITLE
Not letting me use premium acclunt

### ISSUE THREAD

**Issue by purpleYt** [PojavLauncherTeam/PojavLauncher#2758]
### Describe the bug

So im trying to login Pojavlauncher with a premium account, but i get this error, i tried reinstalling the game 4 times but it still didnt let me login. Please fix this
![Screenshot_2022-02-19-21-43-54](https://user-images.githubusercontent.com/83826327/154819089-dad0b37b-2eee-41b2-b547-92df6fe4e08d.jpg)

### The log file and images/videos

Idk

### Steps To Reproduce

```markdown
1. Start Pojav
2. Then login with a premium account and the error should popup.
```

### Expected Behavior

I expected the game to login when i reinstalled it the 2nd time.

### Platform

```markdown
- Device model: ZTE Blade v10 vita
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Latest Release
```

### Anything else?

idk

**Comment by khanhduytran0** [comment]
> **a** premium account

Sounds like it isn’t yours and Mojang account will be deprecated on March 10.

**Comment by ghost** [comment]
It says "Invalid credentials". Hmm wonder what the problem is...

Mojang accounts will not be supported shortly anyway.
