### ISSUE TITLE
[BUG] Can't change version to other than 1.7.10

### ISSUE THREAD

**Issue by adiantek** [PojavLauncherTeam/PojavLauncher#2759]
### Describe the bug

I can't change the version to another than 1.7.10

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8103033/latestlog.txt)
![image](https://user-images.githubusercontent.com/13407885/154819726-e1899b31-be1f-4a90-83ee-9bae7b209d1d.png)
![image](https://user-images.githubusercontent.com/13407885/154819733-68f844d4-1919-4908-9214-fb5f9a4b7b40.png)

### Steps To Reproduce

```markdown
1. Launch PojavLauncher
2. Change version to 1.8.9
3. Click Play
4. It will download 1.8.9 and start 1.7.10 (on the first runtime I had 1.7.10.json not found).
5. It will launch 1.7.10.
```

### Expected Behavior

I should be able to change version to another than 1.7.10.the 

### Platform

```markdown
- Device model: Surface Pro X
- CPU architecture: Microsoft SQ2
- Android version: Android 11 (Windows Subsystem for Android)
- PojavLauncher version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1846393453
```

**Comment by adiantek** [comment]
Same behavior on https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1795391636

**Comment by khanhduytran0** [comment]
Known issue. Please login with `keep me logged in` enabled.

**Comment by adiantek** [comment]
Ok, thanks

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.

**Comment by Pinecone6442** [comment]
this happened to me to

**Comment by mchnjt** [comment]
> this happened to me to

This build of PojavLauncher is no longer supported. If you did a fresh installation from Actions, tap the Version Selector, then Add New Profile. From there, select the version box, then the releases drop-down of your wanted version.
