### ISSUE TITLE
[BUG] <I accidentally deleted java 8>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2762]
### Describe the bug

I accidentally deleted java 8 how do I install it back

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8104069/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Login
3. Deletes java 8 by accident
```

### Expected Behavior

Just trying to enjoy playing on my world and accidentally deleted java 8.

### Platform

```markdown
- Device model: Samsung A31
- CPU architecture: aarch64
- Android version: Android 11
- PojavLauncher version: crocus-322-4e3fdf7f9-v3_openjdk
```

### Anything else?

Nope

**Comment by GaucovyAero** [comment]
Reinstall pojav with the java 8 runtime in it, maybe?

**Comment by Shromeyy** [comment]
Didn't work

**Comment by ghost** [comment]
Yea I for some reason have the same problem help!

**Comment by SprainedSpark89** [comment]
how about reinstalling the app and deleting it's folder
