### ISSUE TITLE
custom mouse cursor support

### ISSUE THREAD

**Issue by MistyStory1** [PojavLauncherTeam/PojavLauncher#2763]
### Is this request related to a bug?

no

### Describe the request.

My mouse cursor is a circle and it doesn't feels good,if I can change my mouse cursor to a better one,the gameplay would be better

**Comment by DovydasTEDS** [comment]
I'm pretty sure that is determined by your manufacture but you probably could change it by flashing a custom rom or if the app drew it's own mouse cursor.
