### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by mishpro-programm** [PojavLauncherTeam/PojavLauncher#2764]
### Describe the bug

Game error -1

### The log file and images/videos

When I run the game, it will crash with error code -1, but app don't close. 
![S20220-234332](https://user-images.githubusercontent.com/60785461/154853760-b204b55a-eb2e-44f2-8652-9d42118445eb.jpg)
I have tried changing ram count, changing visualizer, trying older minecraft versions.

### Steps To Reproduce

```markdown
1. Install latest (crocus-v3_openjdk) version of launcher from Google Play.
2. Login into offline account.
3. Started Minecraft.
```

### Expected Behavior

I except the game to launches.

### Platform

```markdown
- Device model: Meizu M3 Note
- CPU architecture: aarch64
- Android version: 5.1
- PojavLauncher version: [Latest Release || version crocus-v3_openjdk ]
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build. (probably)
