### ISSUE TITLE
[F-Req] 1.18?

### ISSUE THREAD

**Issue by BPG-ML64** [PojavLauncherTeam/PojavLauncher#2767]
### Is this request related to a bug?

It don't workie

### Describe the request.

"Do I look like I know 'hwhat' a ~jpeg~ Java Runtime is? I just want ~a picture of a goddang hot dog!~ to play on 1.18!"

Please and thank you

**Comment by GaucovyAero** [comment]
[**Install**](https://docs.google.com/document/d/18QJUfh-WANGbNI3cZyY3FK55MzqnH2KIAaZzxF1NrXE/edit) **it yourself, please.**

**Comment by BPG-ML64** [comment]
Thank you
