### ISSUE TITLE
[BUG] Pojav Launcher issue with PU Cores

### ISSUE THREAD

**Issue by Guilhacabala** [PojavLauncherTeam/PojavLauncher#2768]
### Describe the bug

Pojav Crashes while loading.

### The log file and images/videos

<p>I've been having some problems with Pojav on the phone of a friend of mine, so I decided to research the problem with the emulator BlueStacks and got some data that might help you show me what I should do to fix the problem.</p><p></p><p>I recorded a 
<a href="https://www.youtube.com/watch?v=tdeQ4eZVSFg" target="_blank">Video</a><a> showing what I did to get the data that I've left in the description</a></p>

### Steps To Reproduce

```markdown
1. Start Pojav Launcher with an "x86 32nm Arm" Processor with more than 2 PU Cores.
2. Define ram or leave it on auto.
3. Start the game.
4. Crash!
```

### Expected Behavior

I would expect the game to load no matter the cores defined on the device

### Platform

```markdown
- Device model: Emulated One Plus T3 (Contents on the linked Video)
- CPU architecture: x86 32nm ARM
- Android version: 7.1.1
- PojavLauncher version: 3.3.1.1
```

### Anything else?

<b><a href="https://www.youtube.com/watch?v=tdeQ4eZVSFg" target="_blank">Linked Video</a>
https://www.youtube.com/watch?v=tdeQ4eZVSFg

**Comment by khanhduytran0** [comment]
Please attach the log file.
Also, your test version is very outdated (over 1 year ago). Please get the latest in the [Actions tab](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

**Comment by Guilhacabala** [comment]
The error neither generates an error log nor a crash log.
I'll check the actions tab when I get home.
![Screenshot_20220221-141146.jpg](https://user-images.githubusercontent.com/64750771/155002099-3aa247c9-68c5-4d58-9076-993a4a920dee.jpg)

**Comment by GaucovyAero** [comment]
> The error neither generates an error log nor a crash log. I'll check the actions tab when I get home. ![Screenshot_20220221-141146.jpg](https://user-images.githubusercontent.com/64750771/155002099-3aa247c9-68c5-4d58-9076-993a4a920dee.jpg)

latestlog.txt in PojavLauncher or net.kdt.pojavlaunch/files, please.

**Comment by Guilhacabala** [comment]
Found It! Thank you for your time.

--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [lwjgl-jemalloc.jar, lwjgl.jar, lwjgl-glfw-classes.jar, lwjgl-opengl.jar, version, lwjgl-tinyfd.jar, jsr305.jar, lwjgl-openal.jar, lwjgl-stb.jar]
Architecture: x86
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.5.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1600
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-1/lib/x86
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=900
--------- beginning of main
I/LIBGL   ( 9830): Initialising gl4es
I/LIBGL   ( 9830): v1.1.4 built on Jul 19 2020 08:26:02
I/LIBGL   ( 9830): Using GLES 2.0 backend
I/LIBGL   ( 9830): loaded: libGLESv2.so
I/LIBGL   ( 9830): loaded: libEGL.so
I/LIBGL   ( 9830): Using GLES 2.0 backend
I/LIBGL   ( 9830): Hardware Full NPOT detected and used
I/LIBGL   ( 9830): FBO are in core, and so used
I/LIBGL   ( 9830): PointSprite are in core, and so used
I/LIBGL   ( 9830): CubeMap are in core, and so used
I/LIBGL   ( 9830): BlendColor is in core, and so used
I/LIBGL   ( 9830): Blend Substract is in core, and so used
I/LIBGL   ( 9830): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 9830): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 9830): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 9830): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 9830): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 9830): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 9830): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 9830): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 9830): Extension GL_OES_texture_float  detected and used
I/LIBGL   ( 9830): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   ( 9830): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 9830): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 9830): high precision float in fragment shader available and used
I/LIBGL   ( 9830): Max vertex attrib: 16
I/LIBGL   ( 9830): Max texture size: 32768
I/LIBGL   ( 9830): Max Varying Vector: 31
I/LIBGL   ( 9830): Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
I/LIBGL   ( 9830): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   ( 9830): Hardware vendor is Qualcomm
I/LIBGL   ( 9830): GLSL 300 es supported
I/LIBGL   ( 9830): GLSL 310 es supported and used
I/LIBGL   ( 9830): EGLImage to Texture2D supported
I/LIBGL   ( 9830): ignore MipMap
I/LIBGL   ( 9830): Targeting OpenGL 2.1
I/LIBGL   ( 9830): NPOT texture handled in hardware
I/LIBGL   ( 9830): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 9830): try to use VBO
I/LIBGL   ( 9830): glX Will try to recycle EGL Surface
I/LIBGL   ( 9830): Current folder is:/
I/jrelog  ( 9830): dlopen libgl4es_114.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/jli/libjli.so success
I/jrelog  ( 9830): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/server/libjvm.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libverify.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjava.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libnet.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libnio.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libawt.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libawt_headless.so success
I/jrelog  ( 9830): dlopen libfreetype.so failed: dlopen failed: library "libfreetype.so" not found
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libfontmanager.so failed: dlopen failed: library "libfreetype.so" not found
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/liblcms.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjsound.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libhprof.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libj2pcsc.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libfontmanager.so failed: dlopen failed: library "libfreetype.so" not found
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libmanagement.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libsctp.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libawt_headless.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/jli/libjli.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/server/libjvm.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libtinyiconv.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libj2pkcs11.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjava.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libnio.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjsig.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libawt_xawt.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libsunec.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libinstrument.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libnet.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libnpt.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjdwp.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjawt.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libmlib_image.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjava_crw_demo.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libunpack.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libverify.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjaas_unix.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libj2gss.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjsdt.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libjpeg.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libawt.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libzip.so success
I/jrelog  ( 9830): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/i386/libdt_socket.so success
I/jrelog  ( 9830): dlopen /data/app/net.kdt.pojavlaunch-1/lib/x86/libopenal.so success
I/jrelog  ( 9830): Done processing args
I/jrelog  ( 9830): Found JLI lib
I/jrelog  ( 9830): Calling JLI_Launch
Error occurred during initialization of VM
**Could not reserve enough space for 614400KB object heap**

**Comment by GaucovyAero** [comment]
It seems like you allocated too much memory. Try again with 256MB.

**Comment by Mathias-Boulay** [comment]
just not enough free RAM
