### ISSUE TITLE
[RAM Allocation] <Short description>

### ISSUE THREAD

**Issue by RobotZguy** [PojavLauncherTeam/PojavLauncher#2771]
ADDING MORE RAM ALLOCATION:

In the old builds of Pojav, you can allocate as much ram as you want. But in the new update, ram allocation is only the half of the total ram for e.g> I have a 4gb ram device but I can allocate only 2800mb (2.8gb). In the older versions, it allowed me to allocate 3gb of ram. Due to this, many people may experience performance issues.

### Describe the request.

Please allow the ram allocator to allow more ram to be allocated

**Comment by LegacyGamerHD** [comment]
Not gone happen or it isn't save for your phone

**Comment by NotAHero04** [comment]
I bet most of your games wouldn't take more than 2GB of RAM.

**Comment by rscDoesMoreTrolling** [comment]
nokia potato phones

**Comment by khanhduytran0** [comment]
> Due to this, many people may experience performance issues.

RAM doesn’t matter, unless you’re going to tell it to render too many chunks. Telling the game to eat 3/4 of the device RAM is not a good idea. What then? You may then experience background process force closes, especially with system apps like SystemUI.
