### ISSUE TITLE
Screen freezen

### ISSUE THREAD

**Issue by Roflad** [PojavLauncherTeam/PojavLauncher#2772]
### Describe the bug

Screen freezen/lagging when i use my mouse.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8112787/latestlog.txt)

https://user-images.githubusercontent.com/100006904/155045002-1aed46b5-2b89-4a1c-94bc-dce9a26a6cee.mp4

### Steps To Reproduce

```markdown
It happening always when i use my mouse for playing again if im not in a pvp.
```

### Expected Behavior

My screen is freezen hard when i do a high cps ( like 5-10cps ).

### Platform

```markdown
- Device model: Redmi note 8
- CPU architecture: perf
- Android version: 11
- PojavLauncher version: 1.8.9
```

### Anything else?

This bug is in all the version of PojavLauncher.

**Comment by Roflad** [comment]
>

**Comment by vasu1234321** [comment]
Same i lose the game with this bug

**Comment by GaucovyAero** [comment]
The more cps you click, the more lag, right?

Not sure if this is good advice, but you can try [OCMC 1.7.10](https://www.mediafire.com/file/s9gu4qj9uathv51/OCMC-Pojav.zip/file) and see if it helps.

**Comment by Roflad** [comment]
Yeah when i didn't do CPS it's lagging less and OCMC is not helping.

**Comment by khanhduytran0** [comment]
Could you try updating to the latest Actions build?

**Comment by Roflad** [comment]
How can i update it ?

**Comment by khanhduytran0** [comment]
[Here it is](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

**Comment by Roflad** [comment]
Thx but wich

**Comment by Roflad** [comment]
Thx but how i do it and wich one ?

**Comment by GaucovyAero** [comment]
Just log into github as you probably are, and download the app-debug.zip file from the latest action build. Then, extract the zip archive and install the app. After you install, the app directory should now be net.kdt.pojavlaunch.debug instead of net.kdt.pojavlaunch.

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
