### ISSUE TITLE
[BUG] Minecraft Textures and Blocks are Glitching

### ISSUE THREAD

**Issue by villagerrr1** [PojavLauncherTeam/PojavLauncher#2773]
### Describe the bug

Minecraft Blocks and Textures are Glitching and Not showing in Version 1.14.4 and using optifine. 

### The log file and images/videos

![Screenshot_20220222_104134_net kdt pojavlaunch](https://user-images.githubusercontent.com/90895958/155054391-e1a48187-bce4-48de-8fd6-ab7c720a2347.jpg)
![Screenshot_20220222_104110_net kdt pojavlaunch](https://user-images.githubusercontent.com/90895958/155054397-3426f853-06be-4f3f-9205-b041aa8cd9ac.jpg)

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

minecraft textures are glitching and buggy. 

### Platform

```markdown
- Device model: huawei honor 8x
- CPU architecture: aarch64 
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

this also happens in minecraft optifine 1.12.2.

**Comment by khanhduytran0** [comment]
Known issue. Try pressing F11.

**Comment by SprainedSpark89** [comment]
if it doesn't work reinstall the version

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
