### ISSUE TITLE
1.18.1 fabric

### ISSUE THREAD

**Issue by Pacific6938** [PojavLauncherTeam/PojavLauncher#2777]
### Describe the bug

When I run the fabric installer it just quits to the login screen or exits the app

### The log file and images/videos

Didn't run the game just an installer has nothing to do with Minecraft as far as I know

### Steps To Reproduce

```markdown
Download fabric installer and run it I guess
```

### Expected Behavior

Install fabric launcher

### Platform

```markdown
- Device model: Mi 11 Lite
- CPU architecture: 
- Android version: 11
- PojavLauncher version: newest Google play state February 22 2022
```

### Anything else?

Where would I put the mods if it works?

**Comment by khanhduytran0** [comment]
> Didn't run the game just an installer has nothing to do with Minecraft as far as I know

latestlog.txt has more than you think. It’s not latest.log

**Comment by LolexIsALazyPotato** [comment]
Use an older version of fabric.

I did it a while back on version 0.12.12 and it works with mods mostly without any problems.
Also, the Google Play version is heavily outdated, download the APK in the Actions section.

**Comment by tylerhacker999** [comment]
honestly having the same issue even with downloaded apk. . goes red and complete shutdown. i also have restarted it many times might have to delete files and re copy.
also username is just my actuall name not good enough at coding yet to offer real suggestions. but hopefully will soon.

**Comment by Pacific6938** [comment]
Thank you :) 

Edit: Wasn't using the newest build everything works fine the Google play version is outdated.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I feal dumb every time I ask but how do I download from actions?
