### ISSUE TITLE
its stuck on the loading dots

### ISSUE THREAD

**Issue by yungsgt** [PojavLauncherTeam/PojavLauncher#2778]
### Describe the bug

when i press play it starts to download every thing then it says loading resorces and it shows the oculus loadind dots then it will stay like that forever.

### The log file and images/videos

it just has the quest 1 loading dots that happen when somethings loading

### Steps To Reproduce

```markdown
1.start launcher and login
2.press play
3.stuck on loading dots
```

### Expected Behavior

i expect the game to start and load the menu in mine craft

### Platform

```markdown
- Device model:quest 
- CPU architecture:dont know 
- Android version:dont know 
- PojavLauncher version:dont know
```

**Comment by OKatiepowersO** [comment]
same issue on quest 2

**Comment by Flamgop** [comment]
This issue has nothing to do with PojavLauncher.
Please close this issue.

**Comment by yackityyack22** [comment]
I also have the same issue, 3 dots then black screen.100% has to do with PajavLauncher. its an alpha build, needs alot of work

**Comment by NotAHero04** [comment]
QuestCraft moment

**Comment by mchnjt** [comment]
questkarft

**Comment by artdeell** [comment]
> I also have the same issue, 3 dots then black screen.100% has to do with PajavLauncher. its an alpha build, needs alot of work

@yackityyack22 it has nothing to do with pojav since pojav has no VR code at all.

**Comment by ghost** [comment]
Why are you trying to use this with quest? There is no https://github.com/PojavLauncherTeam/PojavLauncher_Quest

Expect nothing at all to work. I doubt those things even have java...

**Comment by Ecorous** [comment]
> Why are you trying to use this with quest? There is no https://github.com/PojavLauncherTeam/PojavLauncher_Quest
> 
> Expect nothing at all to work. I doubt those things even have java...

They're using QuestCraft (which in the backend uses pojavlauncher android)

**Comment by Ecorous** [comment]
Please make this issue in the https://github.com/QuestCraftPlusPlus/QuestCraft repo instead

**Comment by crystall1nedev** [comment]
Closing, move to the QuestCraft repo for this issue.
