### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GeraldDoesStuff** [PojavLauncherTeam/PojavLauncher#2779]
### Describe the bug

when I downloaded quest craft it didnt have the fabric loader and i redownloaded it several times.

### The log file and images/videos

I dont have any log files

### Steps To Reproduce

```markdown
i dont know how to reproduce bug
```

### Expected Behavior

I expected everything to work just fine

### Platform

```markdown
- Device model: meta quest 2
```

**Comment by Flamgop** [comment]
This bug has nothing to do with PojavLauncher.
Please close this issue.
