### ISSUE TITLE
[BUG] No right click working

### ISSUE THREAD

**Issue by Peeyusharx** [PojavLauncherTeam/PojavLauncher#2781]
### Describe the bug

This is not a bug but when I connect my mouse mcpe right click is working but pojav launcher right click not working so itried to find back as right click button but there is not a button to activate it so plzzz ad it.

### The log file and images/videos

This thing don't need media to show 

### Steps To Reproduce

```markdown
Hn
```

### Expected Behavior

Right click will take me to home screen

### Platform

```markdown
- Device model: V2036
- CPU architecture: aarch 63
- Android version: 11
- PojavLauncher version: arm vtest 64 fixed flipped
```

### Anything else?

Nothing but plzz add this renderer to play store version

**Comment by Peeyusharx** [comment]
If you want any file related i will give you

**Comment by SprainedSpark89** [comment]
i think the external controls are broken on pojavlauncher

**Comment by Peeyusharx** [comment]
No but left click is working

**Comment by SprainedSpark89** [comment]
some controls work some messed up some don't

**Comment by LightestMC** [comment]
its the complete opposite for me, right click on mcpe not working but works on pojav

**Comment by KurbaybOst2** [comment]
> its the complete opposite for me, right click on mcpe not working but works on pojav

Same for me, i recommend use the playstore app

**Comment by LastCleanShirt** [comment]
> its the complete opposite for me, right click on mcpe not working but works on pojav

yeah same as mine

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
