### ISSUE TITLE
[BUG] <Short description>1.17 virgl renderer texure glitchy 

### ISSUE THREAD

**Issue by vasu1234321** [PojavLauncherTeam/PojavLauncher#2782]
### Describe the bug

Virgl. 1.17 texure glitchy
![Screenshot_20220223_135954](https://user-images.githubusercontent.com/97657011/155289295-f7773c5c-9037-41d2-9193-e4dd239fd1aa.jpg)

### The log file and images/videos

Pls fix 

### Steps To Reproduce

```markdown
Start pojav 
Select virgl renderer 
Launch 1.17 
Open a world
Texure is glitchy
```

### Expected Behavior

Fix pls

### Platform

```markdown
- Device model: vivo y91 
- CPU architecture: aarch 64
- Android version: 8.0.1
- PojavLauncher version: github
```

### Anything else?

No

**Comment by rscDoesMoreTrolling** [comment]
any screenshots pls? we don't know what the heck do you mean with "glitchy textures"

**Comment by mchnjt** [comment]
yes it is atm

**Comment by vasu1234321** [comment]
![Screenshot_2022_0224_080659](https://user-images.githubusercontent.com/97657011/155446811-3fc62c13-5b04-44fa-a03e-b80a974b86ad.png)

**Comment by vasu1234321** [comment]
This texture

**Comment by mchnjt** [comment]
god can you stop simping for virgl
just use a different renderer

**Comment by mchnjt** [comment]
stop spamming issues

**Comment by vasu1234321** [comment]
Can i fix this issue

**Comment by vasu1234321** [comment]
I want to fix tell me

**Comment by SprainedSpark89** [comment]
> just use a different renderer

**Comment by vasu1234321** [comment]
Bruh why i opened this issue

**Comment by SprainedSpark89** [comment]
because you didn't know

**Comment by Mathias-Boulay** [comment]
virgl bugs cannot be fixed
