### ISSUE TITLE
Добавьте Minecraft Dungeons!❤️

### ISSUE THREAD

**Issue by Maxpro886** [PojavLauncherTeam/PojavLauncher#2783]
### Is this request related to a bug?

Это не проблема‼️
 1) Добавьте майнкрафт DUNGEONS На телефоне в pojavlauncher ! 
 2) Добавьте кнопку в которой можно будет прям из лаунчера загрузить мод . А то в ручную не всегда получается 🥲
    Это должно выглядеть примерно так : 
![Picsart_22-02-22_18-54-02-329](https://user-images.githubusercontent.com/100140519/155346808-a9e3c6b6-7928-4173-b05b-b8eb43ecc696.jpg)
 Заранее спасибо :

### Describe the request.

 Добавления :
1) Добавьте майнкрафт Dungeons и DLS для него
2) Добавьте установку модов прямо из игры !❤️
 Изменения :
1) Измените интерфейс так как показано на фото, или примерно так : 
![Picsart_22-02-22_18-54-02-329](https://user-images.githubusercontent.com/100140519/155347541-77b9b6e4-3c90-4476-833c-ec4be056b4a4.jpg)

### Anything else?

Это не проблема . А ПРОСТО ПОЖЕЛАНИЯ ДЛЯ ВАШЕЙ ИГРЫ ‼️

**Comment by artdeell** [comment]
Что за ужас вы сделали с нашим интерфейсом
И да, про версии у пожава отдельной не будет.

**Comment by artdeell** [comment]
Данженс тоже. Как минимум потому что игра только под голимый Windows.

**Comment by mchnjt** [comment]
imagine Minecraft dungeons launcher

**Comment by mchnjt** [comment]
legit insta pircay pojav ban 101% speedrun

**Comment by vasu1234321** [comment]
What is pojavlauncher pro

**Comment by khanhduytran0** [comment]
This is not gonna be added as Minecraft Dungeons isn’t written in Java.

**Comment by Flashgami** [comment]
@khanhduytran0 I hope you add the pojavlauncher pro
