### ISSUE TITLE
Remove Black Bar/Notch

### ISSUE THREAD

**Issue by AweSam4XD** [PojavLauncherTeam/PojavLauncher#2784]
### Is this request related to a bug?

Idk

### Describe the request.

Just Remove Black Bar/Notch
![Screenshot_20220223-190457-picsay](https://user-images.githubusercontent.com/100339315/155473724-abb192de-59cb-4c52-96e1-44371851b74e.jpg)

### Anything else?

Idk

**Comment by mchnjt** [comment]
fack you d0mb@ss just toggle ignore notch in the settings

**Comment by AweSam4XD** [comment]
> fack you d0mb@ss just toggle ignore notch in the settings
> 
> 

I don't have that setting you f*k*ng sh*t, my phone setting are different with your phone f*k*ng b*st*rd rat

**Comment by crystall1nedev** [comment]
bruh

**Comment by AweSam4XD** [comment]
Sorry if i sent swear word too much dude.
