### ISSUE TITLE
<Short description>

### ISSUE THREAD

**Issue by vasu1234321** [PojavLauncherTeam/PojavLauncher#2785]
### Describe the bug

What is pojavlauncher pro 

### The log file and images/videos

Pls

### Steps To Reproduce

```markdown
Pls tell
```

### Expected Behavior

Pls tell

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
Pls
```

### Anything else?

Pls

**Comment by SprainedSpark89** [comment]
idk
