### ISSUE TITLE
a plan to support Ffmpeg

### ISSUE THREAD

**Issue by west-shell** [PojavLauncherTeam/PojavLauncher#2786]
### Is this request related to a bug?

we can make jar patch for replay mod. with it we don't need modify pojav or replay or system. we just patched the replay mod to use the ffmpeg integrated in the jar. who can help

**Comment by mchnjt** [comment]
you planned that now? duy and neko already planned that and was successful :trollface: 😂

**Comment by mchnjt** [comment]
if you're too lazy to follow the instructions on neko/duy's YouTube and the discord server, then get out

**Comment by west-shell** [comment]
> if you're too lazy to follow the instructions on neko/duy's YouTube and the discord server, then get out

use a jar to patch replay ? i saw a plan use apk editor

**Comment by NotAHero04** [comment]
> use a jar to patch replay ? i saw a plan use apk editor

Only rooting and APK editing works.

**Comment by west-shell** [comment]
> > use a jar to patch replay ? i saw a plan use apk editor
> 
> Only rooting and APK editing works.

I tried the apk editor version .but it doesn't work. could you share a modified launchor.

**Comment by mchnjt** [comment]
are you sure you did it properly

**Comment by west-shell** [comment]
> are you sure you did it properly

almost. I found that the bin dir of jre is on the path. I add ffmpeg to the jre and installed it.but still failed

**Comment by NotAHero04** [comment]
You should have added it to the APK. 🤦

**Comment by khanhduytran0** [comment]
> I add ffmpeg to the jre and installed it.but still failed

You didn’t check what I wrote in https://github.com/ReplayMod/ReplayMod/issues/684

> Google started blocking executables in the data directory [since Android 10](https://developer.android.com/about/versions/10/behavior-changes-10)
> Untrusted apps that target Android 10 cannot invoke exec() on files within the app's home directory. This execution of files from the writable app home directory is a [W^X violation](https://en.wikipedia.org/wiki/W%5EX). Apps should load only the binary code that's embedded within an app's APK file.

**Comment by west-shell** [comment]
it's me .that issue is mine. I think the dir of jre is  executable off cause. and to ensure the ffmpeg executable.I have checked it in termux. then i tar them together and installed. I thought that is a perfect way to enable ffmpeg.once pathed.leave behind. upgrade pojav and replay don't affect the patch

**Comment by west-shell** [comment]
I know that . the java is executed another way .we can execute ffmpeg the same way.

**Comment by Mathias-Boulay** [comment]
#2572
