### ISSUE TITLE
i cant play 1.18 

### ISSUE THREAD

**Issue by 1Aryan123** [PojavLauncherTeam/PojavLauncher#2789]
### Describe the bug

whenever i try to play a sanpshot version that is a higher level than 1.16.5, my game always says "Application Exited" can someone help me solve this and maybe giving me the link to the Java Runtime of 1.18. i use the app debug version of pojavlauncher

### The log file and images/videos

*no picture*

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

i expected for it to work normaly but it didnt

### Platform

```markdown
- Device model: Redmi Note 9 pro. 6/128
- CPU architecture: snapdragon 720G
- Android version: 10 (miui 12)
- PojavLauncher version: App debug
```

### Anything else?

.

**Comment by ghost** [comment]
https://pojavlauncherteam.github.io/updates/117.html

**Comment by SprainedSpark89** [comment]
you have to equip a pack and use java 17

**Comment by 1Aryan123** [comment]
How do i re-install the java runtime whenever i uninstall the java runtime i cant reistall it on the development build

**Comment by SprainedSpark89** [comment]
go to the link go to the part that says Platform-specific instruction download java 17 then pojavlauncher go to java runtime in settings then go to add java select the java

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
