### ISSUE TITLE
Pls add skin changer or how to get slim skin in offline account

### ISSUE THREAD

**Issue by Codex2008** [PojavLauncherTeam/PojavLauncher#2790]
### Is this request related to a bug?

Pls add skin changer or how to get slim skin in offline account****

### Describe the request.

Pls add skin changer or how to get slim skin in offline account

### Anything else?

Pls add skin changer or how to get slim skin in offline account

**Comment by GaucovyAero** [comment]
**Maybe try** [**this**](https://www.curseforge.com/minecraft/mc-mods/skinchanger) **out.**

**Comment by Codex2008** [comment]
Thang for help.

**Comment by khanhduytran0** [comment]
Buy the game to get the full experience.

**Comment by CritSpamHLG** [comment]
Just Get A Premium Account To Fix The Problem

**Comment by KatouMegumi-osu** [comment]
> Just Get A Premium Account To Fix The Problem

Did you really have to necro this?

**Comment by mchnjt** [comment]
~~install SkinsRestorer~~
