### ISSUE TITLE
[BUG] Minecraft crashing when I open multiplayer server.

### ISSUE THREAD

**Issue by TMM236** [PojavLauncherTeam/PojavLauncher#2793]
### Describe the bug

So I got Pojav Launcher and I tried to join an server in 1.18.1. When I joined, I could only walk around for 3-4 seconds and Pojav Launcher would close without a crash report (The server was a small server with only 1 online at the time). So then I tried playing a PvP server in 1.8.9 and the same thing happened. No crash reports or anything. Please help

### The log file and images/videos

I replaced the log file with another new log file

### Steps To Reproduce

```markdown
1) Start Pojav Launcher
2) Select Any Version
3) Play
4) Join a Server
5) Do anything in the server for 3-4 seconds
And the game crashes
```

### Expected Behavior

I expected the server to normally load and I can play without any problem

### Platform

```markdown
- Device model: Realme 7 Pro
- CPU architecture: x64
- Android version: Android 11
- PojavLauncher version: Play Store Latest Version
```

**Comment by ajit56** [comment]
This is not happened with me in 1.18.1

**Comment by TMM236** [comment]
> This is not happened with me in 1.18.1

It did with me

**Comment by khanhduytran0** [comment]
For 1.18.x, try disabling cloud rendering.
For 1.8.9, try enabling VBO.
