### ISSUE TITLE
Virgl entity block bug

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#2794]
### Describe the bug

This is virgl entity bug, it happend sometimes when I play pojavlauncher with virgl renderer, it will mostly happened when I play pojav.. with optifine or with mod or both mod and optifine.

### The log file and images/videos

![Screenshot_20220225-110144_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/100254075/155670311-84e9d318-cb85-4e73-a93b-b558c6f9b354.jpg)

### Steps To Reproduce

```markdown
Step 1. Play pojavlauncher with optifine/sodium with mods.
Step 2. Enter a server or play singleplayer world.
Step 3. Feel uncomfortable after see this bug.
```

### Expected Behavior

I expected that this bug will not occurs.

### Platform

```markdown
- Device model: Samsung galaxy a32 4g
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: *A version with virgl renderer*
```

### Anything else?

This bug is very annoying. I can't make me understand easily what block is that. And this bug only occurs to movable block (entities block) like shulker box, any type of chest and any other block that comes from my favorite mod(s)

**Comment by Thollp** [comment]
Question : Do you see the picture that I uploaded?

**Comment by khanhduytran0** [comment]
> Question : Do you see the picture that I uploaded?

As what you see, **Uploading**. You didn't let it to upload, but submit the issue right away. Also, it cannot be used to replace latestlog.txt

**Comment by Thollp** [comment]
> > Question : Do you see the picture that I uploaded?
> 
> As what you see, **Uploading**. You didn't let it to upload, but submit the issue right away. Also, it cannot be used to replace latestlog.txt

It fixed

**Comment by Thollp** [comment]
And also, I don't have any log files

**Comment by imjustpenguin** [comment]
Looks like a barrier block

**Comment by ajit56** [comment]
> Looks like a barrier block

Your right i think 🐮🐄

**Comment by GaucovyAero** [comment]
**Your keyconfig seems very MCInABox-y** (not very cool)

**Comment by Thollp** [comment]
> Looks like a barrier block

It's not barrier block, it's shulker box and its real texture of it is in front of it which is a glitch

**Comment by Thollp** [comment]
After a long time of waiting for this bug to ve fix, I just want to ask that does it fixed now?

**Comment by Mathias-Boulay** [comment]
virgl bugs cannot be fixed
