### ISSUE TITLE
What is pojavlauncher pro 

### ISSUE THREAD

**Issue by vasu1234321** [PojavLauncherTeam/PojavLauncher#2795]
### Describe the bug

Not a bug

### The log file and images/videos

No

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

idk

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: idk
- PojavLauncher version:
```

**Comment by Maxpro886** [comment]
Do not know ┐( ∵ )┌

**Comment by vasu1234321** [comment]
Pls tell

**Comment by artdeell** [comment]
PojavLauncher Pro doesn't exist and will never exist

**Comment by vasu1234321** [comment]
![Screenshot_2022_0225_122313](https://user-images.githubusercontent.com/97657011/155668745-5e9c55bb-d469-414c-80ec-29f81a6781f7.png)

**Comment by vasu1234321** [comment]
So what is this i seen this in a issue the person is sending this

**Comment by Maxpro886** [comment]
> ![Скриншот_2022_0225_122313](https://user-images.githubusercontent.com/97657011/155668745-5e9c55bb-d469-414c-80ec-29f81a6781f7.png)

**Comment by vasu1234321** [comment]
Ya what is this

**Comment by Maxpro886** [comment]
That's about as much as you could add. So to speak, the idea 😅 and it's mine. I'm sorry, I don't speak English well. Everything that is written here is just an idea ... Can we close the question already?

**Comment by mchnjt** [comment]
ideas for pojav pro

- .exe installer
- ~~enclosed version to server like oblivion thing~~
- remove the existence of pircay
- march 10
- artdev pron

**Comment by vasu1234321** [comment]
But what is pojavlauncher pro in this screen shot

**Comment by Maxpro886** [comment]
Это просто идея ...

**Comment by mchnjt** [comment]
> But what is pojavlauncher pro in this screen shot

it's a fucking concept, concept that will never happen

**Comment by crystall1nedev** [comment]
Not a useful issue as this is a third-party concept introduced in #2783.

**Comment by vasu1234321** [comment]
How to download that versions
