### ISSUE TITLE
Upside down screen

### ISSUE THREAD

**Issue by imjustpenguin** [PojavLauncherTeam/PojavLauncher#2796]
### Describe the bug

Nope

### The log file and images/videos

![Screenshot_20220225_153013](https://user-images.githubusercontent.com/96688215/155674935-77b958fa-6135-41fc-9529-3c69d6eefff5.jpg)

### Steps To Reproduce

```markdown
1. Start pojav launcher 
2. Use virgl 
3. Launch the game
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 9
- PojavLauncher version: crocus-327-6d2295d46
```

### Anything else?

Pls fix It

**Comment by Thollp** [comment]
I also experience this bug too.

**Comment by imjustpenguin** [comment]
How to fix it

**Comment by irice7** [comment]
what build lol
theres already a fix

**Comment by imjustpenguin** [comment]
Ok

**Comment by Landsquid950** [comment]
How does one fix this problem?
