### ISSUE TITLE
[BUG] how to fix 

### ISSUE THREAD

**Issue by vasu1234321** [PojavLauncherTeam/PojavLauncher#2797]
### Describe the bug

![Screenshot_2022_0224_080659](https://user-images.githubusercontent.com/97657011/155679168-2bb69518-6f87-4458-93fd-89296e29e2d0.png)
1.17 virgl bug 

### The log file and images/videos

![IMG_20220224_212311](z)

### Steps To Reproduce

```markdown
Launch 1.17 with virgl renderer 
This bug appear buggy texure
```

### Expected Behavior

idk

### Platform

```markdown
- Device model: vivo y91 or vivo 1820
- CPU architecture: 64
- Android version: 8.0.1
- PojavLauncher version: virgl
```

### Anything else?

idk

**Comment by vasu1234321** [comment]
Sry i added Mountain image sry

**Comment by NotAHero04** [comment]
Modify the message moment.

**Comment by NotAHero04** [comment]
If this is your intention, we may have to block you.

**Comment by vasu1234321** [comment]
As u wish :( !

**Comment by khanhduytran0** [comment]
Switch to gl4es
