### ISSUE TITLE
[Bug] Infinite loading screen

### ISSUE THREAD

**Issue by katmaster8007** [PojavLauncherTeam/PojavLauncher#2800]
### Describe the bug

I open questcraft ill sign in with my account go to video and rendering quality is at 80% I clicked the third option I go to the version I want which is fabric 0. 12. 12-1. 18. 1 and I click play I'm stuck on and endless loading screen but sometimes it will play music but it won't change anything.

### The log file and images/videos

no video

### Steps To Reproduce

```markdown
I explained it in the first half
```

### Expected Behavior

open menus

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
Please send **latestlog.txt** after you have succesfully crashed the game. You will find it in one of these directories:

- **a)** For Android 9 and older -> storage/emulated/0/games/PojavLauncher/latestlog.txt
- **b)** For Android 10 and newer -> storage/emulated/0/Android/data/net.kdt.pojavlaunch(or .debug)/files/latestlog.txt

**Comment by artdeell** [comment]
Please move this to the QuestCraft repository
