### ISSUE TITLE
Not able to type

### ISSUE THREAD

**Issue by ravensnest0205** [PojavLauncherTeam/PojavLauncher#2801]
### Is this request related to a bug?

There is no way to type for things such as a server address for questcraft.

**Comment by GaucovyAero** [comment]
Download [**this**](https://cdn.discordapp.com/attachments/779322558339088384/904585542438649866/pc.json) controlmap, it should help you.

**Comment by artdeell** [comment]
Please move this to the QuestCraft repository.
