### ISSUE TITLE
[F-Req] <Short description> Kapan Update Pojav Virgl 3.9 karna saya tidak ingin Minecraft saya lag

### ISSUE THREAD

**Issue by Rafil123** [PojavLauncherTeam/PojavLauncher#2802]
### Is this request related to a bug?

Kapan Update Pojav Virgl 3.9 karna saya tidak ingin Minecraft saya lag

**Comment by Rafil123** [comment]
Saya tidak suka Ngelag dan jg saat saya pake Sildurs vibrants Shader di Pojav Launcher GoodRays Nya hilang

**Comment by khanhduytran0** [comment]
> Saya tidak suka Ngelag 

Consider getting a better device. You can’t expect much from a PC game.

> jg saat saya pake Sildurs vibrants Shader di Pojav Launcher GoodRays Nya hilang

We don’t develop virgl after all. If your device suffers on running vanilla, things may go worse with shaders.
