### ISSUE TITLE
[BUG] <Short description>rafil044

### ISSUE THREAD

**Issue by Rafil123** [PojavLauncherTeam/PojavLauncher#2803]
### Describe the bug

When is Poja Virgl Update please let me know because when I use the Sildurs Shader, how come the GoodRays disappear, the difference with Zink If Zink has GoodRays and Lensflare but if Virgl Why isn't there please Update Pojav Launcher Virgl to Virgl 3.9 so I can use Shader Java without any lag If my Vgpu gets 300FPS IF VIRGL IS ONLY 60FPS EVEN WHEN THE SETTINGS ARE STILL 60FPS IF VGPU TOUCH 300fps please on. make the same and also please fix all the bugs so that all the Java shaders I use are the same as in the original Java 

### The log file and images/videos

Ya

### Steps To Reproduce

```markdown
When is Poja Virgl Update please let me know because when I use the Sildurs Shader, how come the GoodRays disappear, the difference with Zink If Zink has GoodRays and Lensflare but if Virgl Why isn't there please Update Pojav Launcher Virgl to Virgl 3.9 so I can use Shader Java without any lag If my Vgpu gets 300FPS IF VIRGL IS ONLY 60FPS EVEN WHEN THE SETTINGS ARE STILL 60FPS IF VGPU TOUCH 300fps please on. make the same and also please fix all the bugs so that all the Java shaders I use are the same as in the original Java
```

### Expected Behavior

When is Poja Virgl Update please let me know because when I use the Sildurs Shader, how come the GoodRays disappear, the difference with Zink If Zink has GoodRays and Lensflare but if Virgl Why isn't there please Update Pojav Launcher Virgl to Virgl 3.9 so I can use Shader Java without any lag If my Vgpu gets 300FPS IF VIRGL IS ONLY 60FPS EVEN WHEN THE SETTINGS ARE STILL 60FPS IF VGPU TOUCH 300fps please on. make the same and also please fix all the bugs so that all the Java shaders I use are the same as in the original Java 

### Platform

```markdown
- Device model: vivoy12i
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: virgl
```

### Anything else?

Tidak

**Comment by Rafil123** [comment]
Tolong di-update Pojavlauncher Virgl nya

**Comment by khanhduytran0** [comment]
Are you really requesting for ability to run SEUS PTGI E12 at maximum settings without a single rendering glitch at 120fps?

**Comment by khanhduytran0** [comment]
You know, mobile GPU has its limit. If you want, insert RTX 3090 into your phone.
