### ISSUE TITLE
Roughly enough items mod crash

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#2805]
### Describe the bug

My Pojavlauncher crash because I olay it with "Roughly enough items" mod, this bug was so annoying that it give me EMOTIONAL DAMAGE

### The log file and images/videos

No log or photos, because it crash without any reason

### Steps To Reproduce

```markdown
Step 1. Play pojav launcher version on playstore.
Step 2. Play fabric version of minecraft with mod "Roughly enough items" mod.
Step 3. EMOTIONAL DAMAGE (see it crash without tell any reason)
```

### Expected Behavior

I expected the game to launch as normal

### Platform

```markdown
- Device model: samsung galaxy a32 
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: *A playstore version of it*
```

### Anything else?

Nothing more

**Comment by NotAHero04** [comment]
Looks like this issue hasn't been filled up with enough information.
Did your "emotional damage" kill you?

**Comment by Thollp** [comment]
> Looks like this issue hasn't been filled up with enough information. Did your "emotional damage" kill you?

Yes, it kill me

And also, I does not give enough not on purpose. Because the game literally crashes for no reason and I can't show the log because it only show for a few millisecond while intializing game and it crash so it mean i can't copy it

**Comment by NotAHero04** [comment]
You should show us the log now. <:drunkcat:907853233857392652>

**Comment by Thollp** [comment]
> You should show us the log now. <:drunkcat:907853233857392652>

No

**Comment by khanhduytran0** [comment]
> No

How do we fix with such info? :eyes: even the mod version is not provided, and the launcher version is not explicitly stated. It also seems that you ignored this all the time
> The log file called `latestlog.txt` is located under `Android/data/net.kdt.pojavlaunch/files`, `games/PojavLauncher/` or `games/PojavLauncher/.minecraft`. You may need to activate an option in your file explorer to see hidden files and folders.

~~*I guess we will have to stop supporting for people who haven’t bought the game*~~ 🤔

**Comment by Thollp** [comment]
This bug report is closed, because I finally fix this crash right now
