### ISSUE TITLE
I want to change my cursor type and colour.

### ISSUE THREAD

**Issue by LUCIFErr6690cc** [PojavLauncherTeam/PojavLauncher#2806]
### Is this request related to a bug?

I want to change cursor for my pojavlauncher i have seen so much youtubers using black mouse cursor

### Describe the request.

Add a section for changing cursor colour

### Anything else?

**PLEASE ADD PLEASE TAKE MY REQUEST**

**Comment by LightestMC** [comment]
black mouse cursor means they are using external mouse

**Comment by LUCIFErr6690cc** [comment]
No i meant I want to change pojav launcher's inbuilt cursor(mouse pointer) so i requested to add a option to change mouse pointer colour
