### ISSUE TITLE
As soon as I create a world it crashes

### ISSUE THREAD

**Issue by hssbbdsbs** [PojavLauncherTeam/PojavLauncher#2807]
)
### Describe the bug

So, i install Minecraft forge 1.12.2 on my pojav, open it up, create a world and when i creat the world it tells me "shutting down internal server" and then it tells me "the application/game has been closed with the code -1" and here is an image of the crash report

### The log file and images/videos

![Screenshot_2022-02-26-09-58-55-497_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837109-3032b942-905e-4b8d-b1e7-5bd02e703f87.jpg)
![Screenshot_2022-02-26-10-00-42-194_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837176-9378f47f-928a-4c51-a1cc-2fdbb7b30ef8.jpg)
![Screenshot_2022-02-26-10-00-52-285_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837178-32f996d6-f657-4cf5-8bb3-59e87bedd019.jpg)
![Screenshot_2022-02-26-10-01-03-942_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837179-7bb60a85-53f4-4f96-9e3b-6c26afe1aa66.jpg)
![Screenshot_2022-02-26-10-01-09-927_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837180-3ddbc4d8-f938-4b8f-8627-2ac45af832eb.jpg)
![Screenshot_2022-02-26-10-01-16-932_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837182-7b24d0d4-7963-4dbb-b088-ad9f809e9101.jpg)
![Screenshot_2022-02-26-10-01-34-409_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837183-352d5d16-b86a-49cf-8174-dd9977e7a5dc.jpg)
![Screenshot_2022-02-26-10-01-29-429_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837185-3185ffc9-7cfc-4114-ada9-6a28514ddbcb.jpg)
![Screenshot_2022-02-26-10-01-21-238_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837186-3468cecc-b328-4a3a-b571-edbc97ea24a6.jpg)
![Screenshot_2022-02-26-10-01-38-434_net kdt pojavlaunch](https://user-images.githubusercontent.com/100465915/155837187-418a7465-2c2b-4ef6-84dc-b1b149aed955.jpg

### Steps To Reproduce

```markdown
1 open pojav launcher 1.12.2 forge
2 create a world 
And there you go
```

### Expected Behavior

I expected it to just open and that's all

### Platform

```markdown
- Device model: Xiaomi 11 lite 
- CPU architecture: - 4 cores at 1.9 GHz: Kryo 670 Silver (Cortex-A55)
- 3 cores at 2.2 GHz: Kryo 670 Gold (Cortex-A78)
- 1 core at 2.4 GHz: Kryo 670 Prime (Cortex-A78)
- Android version:10 
- PojavLauncher version: latest one
```

### Anything else?

The text is in italian ignore it lol-

**Comment by GaucovyAero** [comment]
Buy Minecraft: Java Edition.

**Comment by Py10lolz** [comment]
Yo duy, i get similar issue. Fix it pls.

**Comment by Py10lolz** [comment]
Jk

**Comment by khanhduytran0** [comment]
Duplicate of #2679

**Comment by hssbbdsbs** [comment]
I found a fix!!! Turn off wifi before playing

Il sab 26 feb 2022, 11:59 Py10lolz ***@***.***> ha scritto:
