### ISSUE TITLE
Crash using Forge 1.16.5

### ISSUE THREAD

**Issue by Bigbang56** [PojavLauncherTeam/PojavLauncher#2808]
### Describe the bug

I was using one mod (Crafting Dead) and it worked fine but after some update in the app or forge idk it doesn't load my world (crashes after 100% loaded)

### The log file and images/videos

[crash-2022-02-26_10.57.03-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8146436/crash-2022-02-26_10.57.03-client.txt)

### Steps To Reproduce

```markdown
1. Start pojav launcher with latest forge 1.16.5 installed
2. Load a world
3. Crash
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: Redmi 9 Power
- CPU architecture: Andreno64
- Android version: 11
- PojavLauncher version: Latest Release
```

**Comment by NotAHero04** [comment]
Duplicate of #2679. Buy the game to fix this error.

**Comment by Bigbang56** [comment]
> Duplicate of #2679. Buy the game to fix this error.

Yeah but I found an effective way without buying, turn off wifi/network lol
