### ISSUE TITLE
[BUG] Idk if this is a bug but please help

### ISSUE THREAD

**Issue by trig02838** [PojavLauncherTeam/PojavLauncher#2809]
### Describe the bug

![Screenshot 2022-02-27 1 38 13 AM](https://user-images.githubusercontent.com/98088072/155843645-ddfe3450-6993-4eae-a1a9-9d196294b218.png)
I cant play pojav on my chromebook please help

### The log file and images/videos

![Screenshot 2022-02-27 1 38 13 AM](https://user-images.githubusercontent.com/98088072/155843698-54720c01-212a-4fd0-b668-ac8c2367c499.png)
![Screenshot 2022-02-27 1 33 00 AM](https://user-images.githubusercontent.com/98088072/155843702-2f9c70af-bbff-436d-957b-0cd9270c1887.png)

### Steps To Reproduce

```markdown
idk what this is
```

### Expected Behavior

I tried to fix it but i couldnt find what was wrong

### Platform

```markdown
- Device model: Lenovo 300e Chromebook 2nd Gen
- CPU architecture: idk but heres a image https://psref.lenovo.com/syspool/Sys/PDF/Lenovo/Lenovo_300e_Chromebook_2nd_Gen_MTK/Lenovo_300e_Chromebook_2nd_Gen_MTK_Spec.PDF 
- Android version: 
- PojavLauncher version: crocus version3 openjdk
```

### Anything else?

i really dont know what to do, im new to github by the way :/

**Comment by Mathias-Boulay** [comment]
You need to download the x86_64 runtime, not the one for arm64 😄

**Comment by LUCIFErr6690cc** [comment]
#Mathias-Boulay **yup that's right**

**Comment by ajit56** [comment]
> #Mathias-Boulay **yup that's right**

He is always right.He is developer

**Comment by trig02838** [comment]
> You need to download the x86_64 runtime, not the one for arm64 😄

can you help me please discord:dogg1#1780

**Comment by Mathias-Boulay** [comment]
Probably fixed on the release candidate build.
