### ISSUE TITLE
[BUG] THREE DOTS

### ISSUE THREAD

**Issue by BoxOfUnity** [PojavLauncherTeam/PojavLauncher#2812]
### Describe the bug

I followed all the steps I believe- but when I press play it gives me the three dot loading screen and that's it-

No mods downloaded, no servers connected-  using the third option on the video render thing-  selected the last version on the list-  checked logs and found nothing-

UPDATE ON STATUS
I turned on ignore notch and tried again... the dots only lasted a second but the screen remained black

anyone?

### The log file and images/videos

these are the same loggs in the launcher right? nothing

### Steps To Reproduce

```markdown
all the steps in the tutorial video up to "press play"
```

### Expected Behavior

Launch \\\_(o.o)_/

### Platform

```markdown
- Device model: uhh Quest 2?
- CPU architecture:  uhhh Quest 2??
- Android version: what ever the Quest 2 runs???
- PojavLauncher version: latest I believe
I don't know this stuff-
```

**Comment by khanhduytran0** [comment]
Duplicate of #2778
