### ISSUE TITLE
Forge 1.12.2 crash when trying to create a world

### ISSUE THREAD

**Issue by MawMx** [PojavLauncherTeam/PojavLauncher#2813]
### Describe the bug

When I select the normal 1.12.2 and create a world it load normally but when i try to create a world with forge 1.12.2 Its just says loading world and then "Shutting Down Internal Server" and then pojavlaucher exit with code -1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8147576/latestlog.txt)

![Screenshot_20220226-174331_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/100492072/155860169-7b1e25db-2a66-4e56-ae9c-b8e911863d80.jpg)
![Screenshot_20220226-174350_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/100492072/155860171-b2a0c08b-30f7-4bd6-a01f-954aac501393.jpg)
![Screenshot_20220226-174409_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/100492072/155860174-2815f84e-94d2-450f-83c2-cda78c59b283.jpg)

### Steps To Reproduce

```markdown
1.Start pojavlauncher in Forge 1.12.2
2.Wait it to load
3.When it loads try o create a world.
```

### Expected Behavior

I expect the game says "Shutting Down Internal Server" and then close with code -1

### Platform

```markdown
- Device model: Samsung Galaxy J8 (SM-J810M)
- CPU architecture: 8x ARM Cortex-A53 @ 1,80 GHz
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by khanhduytran0** [comment]
Duplicate of #2679.
This is not a bug, buy the game to get the full experience.

**Comment by Tiger56c** [comment]
I get that sometimes how to fix it?

**Comment by Tiger56c** [comment]
Please fix it

**Comment by GaucovyAero** [comment]
> Please fix it

We don't help pirates. If you want it to work, buy the game, or find how to fix it yourself.
