### ISSUE TITLE
[BUG] Servidor interno sendo chutado Shutting down internal server

### ISSUE THREAD

**Issue by Rimuru330** [PojavLauncherTeam/PojavLauncher#2814]
### Describe the bug

O bug ocorre após eu instalar o app dnv depois de 2 semanas sem jogar, e praticamente o forge Crasha com qualquer mod e aparece Shutting down internal server Ou Chutando servidor inferno Por favor e as única forma de jogar com mods que eu tenho me ajudem esse bug e infernal e n consigo resolver

### The log file and images/videos

                      Shutting down internal server

### Steps To Reproduce

```markdown
1: Início o POJAVLAUNCHER com qualquer mod e com o forge 1.12.2 e outros
2:Crio ou abro um mundo
3: Aparece mensagem de erro escrita Shutting down internal server E o jogo fecha
```

### Expected Behavior

Que esse bug tivesse sido resolvido instalando e desistalando o app

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Nao

**Comment by Rimuru330** [comment]
🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷

**Comment by LUCIFErr6690cc** [comment]
This question is already answered check #2679

**Comment by LUCIFErr6690cc** [comment]
An if you wanna tell something you have to be in English not in your mother tongue
