### ISSUE TITLE
[F-Req] HOW TO PLAY POJAV WITH SDCARD?

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2815]
### Is this request related to a bug?

No

### Describe the request.

I really need a space to play

### Anything else?

How?

**Comment by GaucovyAero** [comment]
**Nope.**

**Comment by ghost** [comment]
This is not supported, but you can try. 

https://www.tomsguide.com/us/move-android-apps-to-sd-card,news-21279.html

**Comment by Mathias-Boulay** [comment]
adoptable storage is now supported on the code
