### ISSUE TITLE
[F-Req] <Short description> can you add java 1.6.0 or 1.5.0 because thats version is making me more ram/memory soo I will not get lag again

### ISSUE THREAD

**Issue by jethro527** [PojavLauncherTeam/PojavLauncher#2816]
### Is this request related to a bug?

I just want 1.6.0 or 1.5.0 to get no more lag

### Describe the request.

:>

### Anything else?

:>

**Comment by NotAHero04** [comment]
You know what's funny? They don't support Minecraft 1.6 <:HYPERROFEL:862691562814570518>

**Comment by GaucovyAero** [comment]
**I will assure you that no one will do an arm port of Java 5 and 6 anytime soon.**

_I would have a use-case for it, because I play mostly Minecraft 1.5.2 and lower, but it's probably never going to happen._

**Comment by khanhduytran0** [comment]
There’s [no JDK6 for arm64](https://github.com/openjdk/jdk6/tree/master/hotspot/src/os_cpu). The armv7 (32bit) version also only run on interpreter, not JIT. Therefore, JRE6 won’t give any performance improvements. ~~We may consider looking at HotSpot alternatives instead such as OpenJ9~~
