### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by sherlock298** [PojavLauncherTeam/PojavLauncher#2817]
### Describe the bug

not loadind on vr

### The log file and images/videos

no

### Steps To Reproduce

```markdown
no
```

### Expected Behavior

not loading

### Platform

```markdown
- Device model: oculus quest

- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

no

**Comment by artdeell** [comment]
move this to the questcraft repository
