### ISSUE TITLE
Question: Can't find .Minecraft folder

### ISSUE THREAD

**Issue by Pacific6938** [PojavLauncherTeam/PojavLauncher#2818]
### Describe the bug

I can't find the .Minecraft folder Wich is bad because I was trying to add mods to make the game run better. 

But the games folder doesn't exist I think that's a MIUI problem.

### The log file and images/videos

Not needed

### Steps To Reproduce

```markdown
Use MIUI I guess
```

### Expected Behavior

Find a Games filder

### Platform

```markdown
- Device model: Mi 11 Lite
- CPU architecture: arm?
- Android version: 11 MIUI
- PojavLauncher version: I think the newest successful build from actions
```

### Anything else?

Where could the .Minecraft folder be if there Is no gamee folder?

**Comment by GaucovyAero** [comment]
**This is not a PojavLauncher problem.**

**Solution:** Install zArchiver from the Google Play Store and enable Hidden files in zArchiver settings.

**Comment by mchnjt** [comment]
Imagine can't find .minecraft
Smh

**Comment by khanhduytran0** [comment]
Most built-in file managers don’t allow displaying hidden folders. Try using 3rd-party file managers instead.

**Comment by ghost** [comment]
If you use Android, which if you are here you do, the Google Files program is usually preinstalled on most devices and you can use that. Under settings enable viewing hidden files.
