### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Rafil123** [PojavLauncherTeam/PojavLauncher#2821]
### Describe the bug

Why is the Pojav Update this time lagging when I use Shader Please pls update Pojavlauncher Virgl The bar is delicious when I use Java Shader Pliss Update

### The log file and images/videos

Pojavlauncher Virgl Bug And Lag With Use Shader In Medium- High Specs Phone

### Steps To Reproduce

```markdown
1. My pojavlauncher lags different from Vgpu Vgpu doesn't lag and why does Virgl lag
```

### Expected Behavior

I really lag when I use a light shader

### Platform

```markdown
- Device model: Vivo Y12i
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Virgl
```

### Anything else?

Pls update Pojav Virgl

**Comment by GaucovyAero** [comment]
VirGL is generally slower than VGPU or GL4ES. It's main advantage is that it has more features than GL4ES and can actually work with shaders.
**If you want better performance with VirGL, please buy a better phone.**

![image](https://user-images.githubusercontent.com/85581164/156029124-3a65a7fc-9a1f-4238-94ec-511d0f15b053.png)
 /j

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
