### ISSUE TITLE
[F-Req] Update for microsoft login

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2822]
### Describe the request.

Please make it possible to log into a saved Minecraft account (migrated from Microsoft) without the Internet. It's so easy to work with accounts that are not migrated from Microsoft. Therefore, bring this mechanic for saved accounts migrated from Microsoft!

**Comment by ajit56** [comment]
It can be done by 'keep me logged in'

**Comment by andr0d1v** [comment]
It does not help!

**Comment by khanhduytran0** [comment]
I have no idea what do you mean. What after Microsoft account?
> migrated **from** Microsoft

**Comment by winnerscdik** [comment]
wowowow people now migrate from microsoft account to mojang account

**Comment by andr0d1v** [comment]
I mean, make the principle of logging in without the Internet into a microsoft account, the same as a mojang account

**Comment by Mathias-Boulay** [comment]
#2203
