### ISSUE TITLE
[BUG] Fabric 1.18.1 not loading

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2824]
### Describe the bug

I downloaded and installed my performance mods. I launch 1.18.1 (Microsoft license) The download reaches the end and then it starts again. I removed all mods (even fabric api) and the game started working smoothly (but then she lags terribly) How to fix this?

P.S: on the screenshot of the mods that I have
![Screenshot_2022-02-26-05-58-48-797_com mixplorer silver](https://user-images.githubusercontent.com/87223939/156079889-1dd0dac4-e20a-4c29-a447-51a7ec7b71f4.jpg)

### The log file and images/videos

https://user-images.githubusercontent.com/87223939/156079797-ea6af177-6ad3-452a-8649-3c9731d0b13b.mp4

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8157783/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Log in to the my microsoft license
3. Launch fabric 1.18.1
4. Wait for the mojang logo to appear
5. Wait a little
```

### Expected Behavior

I expect the game to run without problems

### Platform

```markdown
- Device model: Redmi 10 4/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest debug (from github actions)
```

**Comment by khanhduytran0** [comment]
A shader compilation error occurred
> Couldn't compile vertex program (Default, rendertype_solid) : 1:15: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'

Try switching to other renderer.

**Comment by andr0d1v** [comment]
Works (set virgl 4.3) only then in the game I have this
![Screenshot_2022-03-11-12-31-11-285_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87223939/158008357-2020c811-dc83-490f-b100-06e05139c001.jpg)

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
