### ISSUE TITLE
Minecraft clouds

### ISSUE THREAD

**Issue by MrCheese520** [PojavLauncherTeam/PojavLauncher#2826]
### Describe the bug

ok so i was playing questcraft and i was looking at the video settings and accidently clicked to turn on clouds and it crashed my game and now i load into Minecraft and cant see the menu and don't have hands and just see the land of Minecraft and see mobs but now i cant play and my computer is gone so i cant re install the game 

what should i do

### The log file and images/videos

y

### Steps To Reproduce

```markdown
Click clouds in Minecraft
```

### Expected Behavior

Accident 😃

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: Oculus quest 2
```

**Comment by SprainedSpark89** [comment]
you do realize we don't make it for oculus

**Comment by MrCheese520** [comment]
Oh I clicked report bug and it brought me there

**Comment by SprainedSpark89** [comment]
ohh

**Comment by kuzy21** [comment]
yeah told you the clouds break the game so how can WE fix this plus you didn't respond to the cloud bug anymore why?

**Comment by MrCheese520** [comment]
Exactly idk why it does that

**Comment by kuzy21** [comment]
he says that the cloud texture is too big

**Comment by kuzy21** [comment]
so i told him how to fix

**Comment by kuzy21** [comment]
he didnt respond ye

**Comment by kuzy21** [comment]
i have video of the cloud crashing i will send the youtube link

**Comment by MrCheese520** [comment]
When it happens is ther a way to turn off clouds or do you have to re
download it?

**Comment by jorgieee** [comment]
here:https: //www.youtube.com/channel/UCKFO4LX9g5yRk312NuAbFTg

**Comment by kuzy21** [comment]
here: https://www.youtube.com/channel/UCKFO4LX9g5yRk312NuAbFTg

**Comment by MrCheese520** [comment]
I have been using it on the oculus quest 2

**Comment by kuzy21** [comment]
its possible?

**Comment by SprainedSpark89** [comment]
what version

**Comment by MrCheese520** [comment]
I forgot the certain version but it is questcraft on side quest they have a
tutorial for it

**Comment by SprainedSpark89** [comment]
ok the minecraft version would help so i can try to help

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
