### ISSUE TITLE
[BUG] Options.txt File Keeps Resetting

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2829]
### Describe the bug

Every time I try to edit the `options.txt` file file for the 1.18 fix, the `resourcePacks:[]` line to `resourcePacks:["assets-v0_1.18+.zip", "assets-v0"]` the line keeps reverting back to `resourcePacks:[]`

Because of this, 1.18 is stuck loading indefinitely as seen on another of my issues, #2769

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8162289/latestlog.txt)
[options.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8162296/options.txt)

https://user-images.githubusercontent.com/65428515/156205925-dd55a499-2d7c-4ec5-be0e-ba59fb487cd7.mp4

### Steps To Reproduce

```markdown
1. Start ProjavLancher
2. Sign in to an account
3. Get Fabric Loader
4. Go back to ProjavLancher and get click options
5. Now click the "Launch a Mod Installer" button and select the Fabric Launcher
6. Wait, then in the menu, select 1.18 client and finish downloading
7. Download the fabric API and move it into the mods folder
8. Once done, follow the instructions on how to get Minecraft 1.18+ to work
9. Get stuck on the resource pack part
```

### Expected Behavior

I expect for me to be able to edit my `options.txt` file and maybe, JUST MAYBE get Minecraft to stop Minecraft getting stuck infinitely loading in the loading screen

### Platform

```markdown
- Device model: R96-14268.67.0
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I'm using the Fabric Launcher with the mods being from a Curseforge Modpack called [Fabulously Optimized 3.1.0](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized) (file download [here](https://github.com/PojavLauncherTeam/PojavLauncher/files/8105278/Fabulously.Optimized.3.-3.1.0.zip))

**Comment by GaucovyAero** [comment]
This may be an accidental issue. If assets-v0 has .zip after, make sure you change the value of resourcePacks to resourcePacks:["assets-v0_1.18+.zip", "assets-v0.zip"].

**Comment by Errorbot1122** [comment]
OMG, IT WORKED

I just forgot to add the .zip extension lol

TNX SO MUCH
