### ISSUE TITLE
RSApadding error

### ISSUE THREAD

**Issue by escaleirex** [PojavLauncherTeam/PojavLauncher#283]
I have been trying all day things to fix this issue, like turning on or off any vpn's or dns's and none of them worked, it's says "Unable to fix RSApadding". Does someone know how to fix this?
I tried in two phones, and both of them had this issue. 

My device's
Huawei P Smart 2019
Samsung A10

**Comment by khanhduytran0** [comment]
Use v2.5.2

**Comment by WesleyVanNeck** [comment]
@Escaleirex plz try this version https://drive.google.com/file/d/1UWv6d13-FzYxuhXkwp9FUR75T9zqI_aX/view?usp=sharing

**Comment by khanhduytran0** [comment]
@Escaleirex please reply for result
