### ISSUE TITLE
Laggy mouse

### ISSUE THREAD

**Issue by eopal** [PojavLauncherTeam/PojavLauncher#2830]
### Describe the bug

This is different from only moving the mouse, basically when i move my mouse and press at the same time my mouse lags, it makes it impossible to aim since i am a 1.8.9 pvper, i use 1.8.9
I can aim if i don't press my left click, but if i press it while aiming it lags, i have a decent fps raging from 60-120. Please fix it it's really annoying and makes it unplayable.

### The log file and images/videos

The bug is very obvious in my last fight, my mouse didn't even move ( i am a pc player and i am very experienced with the game this is not my terrible aim it's the launcher itself, i tried playing Minecraft pocket to see if it's my mouse and it worked just fine )
https://youtu.be/I3b2wo3kHZ4 video

### Steps To Reproduce

```markdown
1- start pojavlauncher
2- launch 1.8.9
3- go in a world or a server
4- move your mouse around while spam clicking the left button of the mouse
```

### Expected Behavior

I expect my mouse to move smoothly while clicking so i can actually aim

### Platform

```markdown
- Device model: Nokia 7.2
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest release (crocus-v3_openjdk)
```

### Anything else?

I used 3 different mouses and still the same issue.

**Comment by GaucovyAero** [comment]
Depends on phone to phone and I've had the same issue on my friends phone; We both have a Galaxy S7 Edge SM-G935F, also both on Android 8.0.0 and he does have the mouse lagging and I don't. I'm also a pvper (1.7.10 mind you) and actually what bugs me more is mouse acceleration on Android, which of course, you can't disable. Probably unfixable, but you could try flashing to LineageOS 19 (clean android) running Android 12 and it may solve the issue. Not a pojav problem as I'm aware, try reproducing it on your home screen.

**Comment by GaucovyAero** [comment]
*If you own the play store version of Pojav and you're having these issues, make sure to update to the latest Actions build on this GitHub page.

**Comment by Aerolome** [comment]
*If you own the play store version of Pojav and you're having these issues, make sure to update to the latest Actions build on this GitHub page.

**Comment by eopal** [comment]
> *If you own the play store version of Pojav and you're having these issues, make sure to update to the latest Actions build on this GitHub page.

I just did and it worked, thank you!!
