### ISSUE TITLE
Unexpected Crash whilst Loading Mods

### ISSUE THREAD

**Issue by hydroflame521** [PojavLauncherTeam/PojavLauncher#2831]
### Describe the bug

When I put certain mods into the mods folder of forge, it causes the "Game Exited" crash. This is running the latest version of Pojav and I do not know the origin of this issue. The mod works for windows / pc users, but causes a crash issue when loaded as a mod with forge on pojavlauncher.

### The log file and images/videos

[crash-2022-03-02_01.13.46-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8166030/crash-2022-03-02_01.13.46-client.txt)

### Steps To Reproduce

```markdown
1. Start the Launcher, Run Forge for 1.12.2
2. Open your choice file explorer and install the mod: https://github.com/TechAle/gsplusplus into the forge mods folder
3. Click play for forge 1.12.2
```

### Expected Behavior

Produces "Game Exited" Crash Issue.

### Platform

```markdown
- Device model: samsung phone
- PojavLauncher version: latest google play release
```

**Comment by NotAHero04** [comment]
Looks like it needs a native Discord RPC library. Maybe ask Google for `discord-rpc native library for Android`?

**Comment by hydroflame521** [comment]
how would i use the library in order to resolve the issue?

**Comment by Mathias-Boulay** [comment]
#1948
