### ISSUE TITLE
[BUG] fail connect minecraft server

### ISSUE THREAD

**Issue by LICKIL** [PojavLauncherTeam/PojavLauncher#2834]
### Describe the bug

Enter the server shows that the connection cannot be made
The first picture is hypixle and the second is 2b2t

### The log file and images/videos

This is true of each version
![Screenshot_2022-03-02-16-53-52-285_net kdt pojavlaunch](https://user-images.githubusercontent.com/46256433/156328486-7ff70945-5fd3-4344-9d0f-36c1223f4e37.jpg)

### Steps To Reproduce

```markdown
1.start app
2.launcher game
3.join server
```

### Expected Behavior

play in server

### Platform

```markdown
- Device model: redmi k40
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version:3.3.1.1_rel_20210206
```

**Comment by ajit56** [comment]
Not connected to internet?

**Comment by SprainedSpark89** [comment]
so are you using a hack client if so we can't help

**Comment by GaucovyAero** [comment]
You are using a VERY VERY old PojavLauncher build. Get a new one from Actions on this GitHub page.

**Comment by SprainedSpark89** [comment]
or from the playstore

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
