### ISSUE TITLE
Fabric won't work with 1.18+

### ISSUE THREAD

**Issue by AllyNex** [PojavLauncherTeam/PojavLauncher#2835]
### Describe the bug

I tried adding Fabric to 1.18+ but it crashes, the crash is the same one versions would get without the Asset Patcher, but the asset patcher wont work with fabric. Anything I can do?

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8169313/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Add the runtime manager your architecture needs
3. Click the renderer it needs
4. Use 1.18+ and use the asset patcher so it works
5. Install fabric and launch
```

### Expected Behavior

I expect Fabric to launch

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
> -jar /data/user/0/net.kdt.pojavlaunch/cache/client-intermediary.jar

This doesn’t look like a valid Fabric Installer, but rather client intermediary. Use [this up-to-date patcher](https://cdn.discordapp.com/attachments/724163890803638277/922043517860212736/Pojav117AssetsPatcher.jar).

**Comment by AllyNex** [comment]
Alright, will do

**Comment by AllyNex** [comment]
@khanhduytran0 Ok so I tried the patcher you gave me but it was the same as the one I was already using so it still didnt do anything, I downloaded the installer straight from the official site, the intermediary is a component of Fabric itself

**Comment by khanhduytran0** [comment]
> I downloaded the installer straight from the official site

The log showed that you didn’t run the installer, have you double-checked?

**Comment by AllyNex** [comment]
Yeah, I downloaded the installer and ran it as a Jar file as you normally would and then there was another version added that was Fabric but when I use the asset patcher it doesnt seem to pick up the new version. The menu shows 1.18.2 but not any of the Fabric versions

**Comment by AllyNex** [comment]
@khanhduytran0 here's an updated log if that helps
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8175654/latestlog.txt)

**Comment by Varunpal75** [comment]
I am having pretty much the same issue

**Comment by khanhduytran0** [comment]
Use assets-v0 moment.

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
