### ISSUE TITLE
[BUG] Cant select Java 17

### ISSUE THREAD

**Issue by vaporvee** [PojavLauncherTeam/PojavLauncher#2836]
### Describe the bug

Hey i want to play Minecraft 1.18 but i cant select any files in the android file explorer. I'm trying to add this jre17 [...] .tar.xz java runtime in the launcher settings

### The log file and images/videos

-

### Steps To Reproduce

```markdown
Start PojavLauncher, try to add a new java runtime in the settings
```

### Expected Behavior

Letting me select the tar.xz file

### Platform

```markdown
- Device model: Samsung Galaxy S10
- CPU architecture: Arm
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk (but i tried the newest build and doesn't work)
```

**Comment by vaporvee** [comment]
I got a working version from a random youtube tutorial lol

**Comment by SkyTheNerd** [comment]
> I got a working version from a random youtube tutorial lol

Can I have the link I can't open it either
