### ISSUE TITLE
Hey can u please make the launcher support oppo Reno 5

### ISSUE THREAD

**Issue by Shadow4202** [PojavLauncherTeam/PojavLauncher#2839]
### Is this request related to a bug?

I can't use it on oppo Reno 5 I just open it and 5 seconds then boom crash and when I use forge it just loads in Minecraft but crashes everytime pls make it support oppo Reno 5 or fix it if it's just a bug and thx u cool devs

**Comment by thegarykun** [comment]
how is this an enhancement? it seems like a bug ಠ_ಠ

**Comment by Mathias-Boulay** [comment]
Probably fixed on the release candidate build.
