### ISSUE TITLE
Optifine Installation causes the app to crash. 

### ISSUE THREAD

**Issue by escaleirex** [PojavLauncherTeam/PojavLauncher#284]
When I try to install optifine in 1.8, it restarts the app, and doesn't install it. I tried on 2 devices, the only one that worked was the Samsung A10, but the Huawei P Smart 2019, just restarted the app every time.

Device's
Huawei P Smart 2019 
Samsung A10

**Comment by khanhduytran0** [comment]
Just to do not try latest build. Use v2.5.2

**Comment by khanhduytran0** [comment]
@Escaleirex are you going to reply?

**Comment by Malaska678** [comment]
@khanhduytran0 Known issue right? Some Huwawei cant run minecraft or optifine

**Comment by Malaska678** [comment]
Same issue #280
