### ISSUE TITLE
[BUG] Left click doesnt work using external mouse on Android 9

### ISSUE THREAD

**Issue by LastCleanShirt** [PojavLauncherTeam/PojavLauncher#2841]
### Describe the bug

I open pojav, attached my mouse using OTG Cable, and play 1.8.9, but when i play on some server (luckynetwork.id) the left click didn't get registered/didnt work when i try it on my external mouse (also didnt left click didnt work on gui), only right click that works. **BUT** there is an exception, the left click get registered on the pause menu and the home menu

I also tried to install the latest build on actions, but still, the left click didnt work 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8182692/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Attach Mouse using OTG and connect my keyboard
３．Play 1.8.9
４．Join server
５．Tried to left clicking but didnt work
６．Tried to right clicking and it works
```

### Expected Behavior

I expect the left click to be working but it didn't work

### Platform

```markdown
- Device model: OPPO A12
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: 3.3.1.1 crocus-v3_openjdk (The latest on playstore)
-
```

### Anything else?

Keyboard = Bluetooth Keyboard, product name is OneSOS
Mouse = AulaS20

I already tried to re-install the PojavLauncher but it didnt work

**Comment by MARnelPH12** [comment]
Yee same as mine

**Comment by Mathias-Boulay** [comment]
try the latest action build then
_btw latest isn't a version_

**Comment by LastCleanShirt** [comment]
how can i install the latest build?, oh yeah btw sorry i will edit the "latest"

**Comment by LastCleanShirt** [comment]
And also for some reason, the left click only works **if** i press a key on my keyboard as fast as i click my mouse (on the latest build)

**Comment by Mathias-Boulay** [comment]
your version is incorrect, but both real version it could refer too are far from the latest

**Comment by LastCleanShirt** [comment]
> your version is incorrect, but both real version it could refer too are far from the latest **action** build

Yeah, i get the build from the **action** tab, please correct me if im wrong

**Comment by Mathias-Boulay** [comment]
Well, I kinda would like the precise version you tested then since no build on the action tab is bearing the version you stated in the first post

**Comment by LastCleanShirt** [comment]
![Screenshot_2022-03-07-21-23-43-84.jpg](https://user-images.githubusercontent.com/74228323/157052321-ffd6dbfa-3b8d-408d-bccf-4687bc619f36.jpg)

**Comment by Mathias-Boulay** [comment]
Perfect then, if that's not the case, I advise you to join the pojav discord and contact me from there, it should be easier to deal with custom debug builds 👍

**Comment by MARnelPH12** [comment]
Why its still not working i downloaded that build and yea nothing change also we have the same phone so :(

**Comment by LastCleanShirt** [comment]
> Perfect then, if that's not the case, I advise you to join the pojav discord and contact me from there, it should be easier to deal with custom debug builds 👍 

I actually joined the discord server tho, my username is Arya#0073

**Comment by LastCleanShirt** [comment]
Uhmm, soo is it already fixed or not?

**Comment by Mathias-Boulay** [comment]
> Uhmm, soo is it already fixed or not?, Its been a month, tried to install the latest build available, but the bug still not fixed

Instructions sent to you via discord.

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
