### ISSUE TITLE
[F-Req] MINECRAFT WINDOW RESIZING!!!!!

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2844]
### Is this request related to a bug?

Yes, as when you rise the Minecraft window on Chromebook, it crashes the game and it glitches out so hard that a can't even force close the windows

_(Video of this will be added later)_

### Describe the request.

I just want window resizing capabilities, so my game won't crash when I accidentally fullscreen

### Anything else?

I'm on Chromebook, so...

https://github.com/PojavLauncherTeam/PojavLauncher/issues/2743#issuecomment-1041048559

**Comment by WesleyVanNeck** [comment]
Dont use IT on a Chrome book

**Comment by Errorbot1122** [comment]
why not, it works...

**Comment by SprainedSpark89** [comment]
well if you want to use fullscreen you press the box on the keyboard and if you want to access the side panel you put your mouse about the right edge of your window or minecraft then hold left click then drag left.

**Comment by Mathias-Boulay** [comment]
DOOOOOONE

**Comment by Errorbot1122** [comment]
:)
