### ISSUE TITLE
[1.17.1] <SODIUM NOT WORKING>

### ISSUE THREAD

**Issue by LUCIFErr6690cc** [PojavLauncherTeam/PojavLauncher#2847]
### Describe the bug

I want to use sodium because i have a low end device . And i can ply older versions but i want to experience how 1.17/1.18 looks in game .

### The log file and images/videos

I dont have

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Install 1.17 fabric 
3. Install sodium
4. Launch 1.17 fabric 
5. Create new world
```

### Expected Behavior

WORLD WILL OPEN . 

### Platform

```markdown
- Device model: MOTOG5PLUS
- CPU architecture: ARMV7I
- Android version: 8.0.1
- PojavLauncher version: crocus_v3_openjdk
```

### Anything else?

IT SAYS THAT PROBLEM IS WITH SODIUM.

**Comment by NotAHero04** [comment]
Sodium is currently not supported.

**Comment by LUCIFErr6690cc** [comment]
**BUT WHY**

**Comment by mchnjt** [comment]
GL requirements.

**Comment by JohnPrincePoggi31** [comment]
My 1.17 sodium works? Just fix your settings
When i First intall sodium on 1.17 it crash too but i fix some settings and i got it working

**Comment by LUCIFErr6690cc** [comment]
But i want to use how

**Comment by LUCIFErr6690cc** [comment]
Tell me or send video

**Comment by LUCIFErr6690cc** [comment]
Please i beg you

**Comment by LUCIFErr6690cc** [comment]
Please

**Comment by NotAHero04** [comment]
Use Zink.

**Comment by LUCIFErr6690cc** [comment]
No it shows gray background and no text on buttons like singleplayer

**Comment by LUCIFErr6690cc** [comment]
@NotAHero04 **reply**

**Comment by NotAHero04** [comment]
> No it shows gray background and no text on buttons like singleplayer

Not related to Sodium.

**Comment by LUCIFErr6690cc** [comment]
I meant zink show gray background when enter game

**Comment by LUCIFErr6690cc** [comment]
So if you know please attach a video please

**Comment by WesleyVanNeck** [comment]
> So if you know please attach a video please

Dont use sodium use optifine

**Comment by LUCIFErr6690cc** [comment]
But it lags on latest after 1.17 versions

**Comment by LUCIFErr6690cc** [comment]
My device can run 1.16.4 optifine with around 30 fps on 644 mb ram and 40% resolution

**Comment by SprainedSpark89** [comment]
sodium is unsupported use optifine without a mod installer and lower the settings to the minimum and use a texture pack that has a lower resolution than vanilla the vanilla resolution it 16x use like a 8x or less.
