### ISSUE TITLE
1.18.2 bug

### ISSUE THREAD

**Issue by CharredMist** [PojavLauncherTeam/PojavLauncher#2848]
### Describe the bug

When I go into 1.18.2 with gl4es 1.1.4 and new assets-v0.zip, and gone into a world, it just crashes and makes me cancer because I cant progress on my skyblock world.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8190029/latestlog.txt)

### Steps To Reproduce

```markdown
1 Start PojavLauncher (debug with virglrenderer)
2 start 1.18.2
3 go into a world
4 wait 1 or 2 minutes
```

### Expected Behavior

Puts into login screen without ANY ERROR.

### Platform

```markdown
- Device model: Samsung Galaxy a71/128GB
- CPU architecture: aarch64
- Android version: Android 11
- PojavLauncher version: crocus-298-163206f34-v3_openjdk (Debug apk with virgl)
```

### Anything else?

Side note: I launched minecraft in 1.8.9 recently

**Comment by artdeell** [comment]
because you gotta use 1.1.5

**Comment by CharredMist** [comment]
> because you gotta use 1.1.5

Oh ok i'll try

**Comment by ERENPROO** [comment]
> because you gotta use 1.1.5

It didnt worked again

**Comment by CharredMist** [comment]
> because you gotta use 1.1.5

Didnt worked

**Comment by GaucovyAero** [comment]
**Name and ID cannot both be blank.** Buy Minecraft!

**Comment by CharredMist** [comment]
> **Name and ID cannot both be blank.** Buy Minecraft!

Dont have money bruh

**Comment by CharredMist** [comment]
> **Name and ID cannot both be blank.** Buy Minecraft!

And this didnt happened before

**Comment by GaucovyAero** [comment]
No support for pirates, sorry ;)

**Comment by khanhduytran0** [comment]
> > **Name and ID cannot both be blank.** Buy Minecraft!
> 
> Dont have money bruh

You have no more way for this.
