### ISSUE TITLE
1.18.2 crashed with gl4es1.1.5[BUG] <Short description>

### ISSUE THREAD

**Issue by CaveSpiderII** [PojavLauncherTeam/PojavLauncher#2850]
### Describe the bug

When I go into 1.18.2 game crashed with gl4es 1.1.5 and new assets_v0.zip,and gone into a world,it crashes without any notice.

### The log file and images/videos

[https://drive.google.com/file/d/1-2nT0pYAoduSE2885HGwDD9bAwJHunKv/view?usp=drivesdk](url)

### Steps To Reproduce

```markdown
1. Start PojavLauncher (debug with virglrenderer)
2. Start 1.18.2
3. go into a world
4. Wait for a few seconds
```

### Expected Behavior

Play for a lone time with gl4es1.1.5

### Platform

```markdown
- Device model: realme RM3366/256G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-332-4cfbf4c9a_v3_openjdk
```

### Anything else?

Nether optifine nor vanilla are crashed

**Comment by NotAHero04** [comment]
What do you mean by "the new assets-v0"? Also send the log file to the issue page directly.

**Comment by CaveSpiderII** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8190355/latestlog.txt)

**Comment by CaveSpiderII** [comment]
the patch pack for 21w37a or above(assets-v0.zip)

**Comment by ghost** [comment]
Using this assets-v0 that @NotAHero04 created for the 1.19 experimental snapshot, the game operated properly with gl4es 1.1.5. 
[assets-v0.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8192022/assets-v0.zip)

**Comment by RzdPai** [comment]
如果你安装了fabric，你的安装fabirc模组不支持，1.18的钠就不支持gl4es

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
