### ISSUE TITLE
essential x doesn't work not crash

### ISSUE THREAD

**Issue by blob83** [PojavLauncherTeam/PojavLauncher#2851]
### Describe the bug

never gonna give you up never gonna let you down

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8191673/latestlog.txt)

### Steps To Reproduce

```markdown
go to zachiver donate and to downloads copy essential x goto android data pojavlauncher. minecraft and mods
```

### Expected Behavior

eeeeee

### Platform

```markdown
- Device model: Samsung Galaxy A11 
- CPU architecture: 32 bits
- Android version: 11
- PojavLauncher version: idk
```

### Anything else?

essential x not showing

**Comment by winnerscdik** [comment]
EssentialsX is a **Server** plugin, not a mod. Are you dumb or what

**Comment by blob83** [comment]
oh ok
