### ISSUE TITLE
> When I try to open PojavLauncher, The app crashes. It happens on my Fire Tablet, so I use the phone and it does not crash on the phone, on Fire.. It did work now and not now. BUGS!!!
Android version: "Fire" Android 9
Android version: "

### ISSUE THREAD

**Issue by flexVDIDesktop** [PojavLauncherTeam/PojavLauncher#2852]
> When I try to open PojavLauncher, The app crashes. It happens on my Fire Tablet, so I use the phone and it does not crash on the phone, on Fire.. It did work now and not now. BUGS!!!
Android version: "Kindle Fire" Android 9
Android version: "Galaxy A21"
(Galaxy A21) (Service Carrier)
Boost Mobile

You'd better make a new issue and provide enough informations there.

_Originally posted by @NotAHero04 in https://github.com/PojavLauncherTeam/PojavLauncher/issues/2597#issuecomment-1059909250_

**Comment by NotAHero04** [comment]
Hmm, yes? You only did one half of my request.

**Comment by GaucovyAero** [comment]
Not enough. Any logs?

**Comment by flexVDIDesktop** [comment]
How!?

**Comment by GaucovyAero** [comment]
Please upload latestlog.txt here with the crash in it.

**Comment by SprainedSpark89** [comment]
go to games pojavlauncher latestlog.txt

**Comment by Mathias-Boulay** [comment]
invalid
