### ISSUE TITLE
mouse cursor disapears

### ISSUE THREAD

**Issue by SplitRacoon** [PojavLauncherTeam/PojavLauncher#2853]
### Describe the bug

Will be playing and then the mouse cursor seams to get stuck behind the game. if you position it to either the very top of the screen or the bottom of the screen it will show up again but not in the game area. if i close out of the game the mouse works perfect again. I have to restart the chromeboook and then it works again for a random amount of time and then it happens again. 

### The log file and images/videos

dont have this

### Steps To Reproduce

```markdown
start playing play until mouse is no longer working
```

### Expected Behavior

mouse to work all of he time. 

### Platform

```markdown
- Device model: chromebook flip 3
- CPU architecture: 
- Android version: 
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
Can not be reproduced with the release candidate build
