### ISSUE TITLE
Add Support IPv6 Address

### ISSUE THREAD

**Issue by plotaa** [PojavLauncherTeam/PojavLauncher#2854]
### Is this request related to a bug?

No

### Describe the request.

Some servers are running on IPv6 address but not on IPv4 address, so while connecting IPv6 server, it said 'Unsupported Address Type Exception'.

### Anything else?

no

**Comment by ghost** [comment]
You are unable to connect to a Minecraft server using IPv6. IPv6 relates to the unique device itself, much like IPv4. However, you can use an IPv4 address to connect to a Minecraft server so long as you're either on the same network as the host, or tunneled into the network.


This is not a Minecraft feature. Pojavlauncher does not have it either. 🤔
