### ISSUE TITLE
[BUG] Game Exited Better Minecraft Plus 

### ISSUE THREAD

**Issue by BloomyJaz** [PojavLauncherTeam/PojavLauncher#2855]
### Describe the bug

Game exited during forge mod sided setup.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8193567/latestlog.txt)

### Steps To Reproduce

```markdown
Download Better Minecraft [Plus] and launch the game.
```

### Expected Behavior

I expect to load to the game menu

### Platform

```markdown
- Device model: Model:
SM-G986U
- CPU architecture: Aarch64
- Android version: 12
- PojavLauncher version: Google Play version as of March 6th, 2022
```

**Comment by khanhduytran0** [comment]
OptiFine threw an incomplete framebuffer attachment. Try switching renderer.

Also #1948
