### ISSUE TITLE
[BUG] FAILED TO LOAD REASOURCE PACK!!

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2856]
### Describe the bug

when i try to select realistico lite pack and when its done loading it did not selcet like  <FAILED TO LOAD RESOURCES PACK!>

### The log file and images/videos

[](url)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8194127/latestlog.txt)

### Steps To Reproduce

```markdown
start pojav launcher
play 1.12.2 or 1.16.5 oftifine
select realistico pack
not selecting
```

### Expected Behavior

i thought it would work

### Platform

```markdown
- Device model: oppo a12 3/32
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: latest buld
```

### Anything else?

any suggestion?

**Comment by SprainedSpark89** [comment]
it could just be the texture pack

**Comment by RzdPai** [comment]
如果运存设置太少，一些高分辨率材质会无法使用，可以调高运存或使用低分辨率材质

**Comment by FermiumRain** [comment]
> it could just be the texture pack

I have the same with version 1.18.2 (optifine), after trying to install at least one of the 5 different packages I downloaded, none of them could not install. So I doubt it's about the resource/texture pack itself

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
