### ISSUE TITLE
[BUG] <shaders!>

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#2857]
### Describe the bug

When I use shader on 1.17+ with optifine the screen turn blue with white on the side and u can't see anything. Also it happens when I use the patcher.

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I expect to see the shader

### Platform

```markdown
- Device model: s20 fe
- CPU architecture: 64arm
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

I see people use shader on YouTube and don't have the same ruselt as me also forget the clouds

**Comment by GaucovyAero** [comment]
Please note that not every shader works.

**Comment by khanhduytran0** [comment]
> I see people use shader on YouTube and don't have the same result as me 

Do you have the same device as them? :eyes: every device come with a different GPU, so you can’t expect everything that work on their device to work on your device.
Note that Zink renderer is currently unavailable due to the current Mesa for virgl just takes empty frames.

**Comment by kuzy21** [comment]
i use the shqdrr that are only compatible with pojavlauncher
