### ISSUE TITLE
[BUG] I cant disable flat button style on my device

### ISSUE THREAD

**Issue by purpleYt** [PojavLauncherTeam/PojavLauncher#2862]
### Describe the bug

I want to disable the new button style since i dont like new one

### The log file and images/videos

what do i type

### Steps To Reproduce

```markdown
ok what its in the settings
```

### Expected Behavior

There will be flat button style option

### Platform

```markdown
- Device model: ZTE Blade V10 Vita
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: playstore version
```

### Anything else?

Contact me on discord: Colored#4959

**Comment by khanhduytran0** [comment]
The toggle is no longer available as there is already Custom Controls.
