### ISSUE TITLE
[BUG]  Mouse don't move the camera error  (Mouse External)

### ISSUE THREAD

**Issue by MrFrame20** [PojavLauncherTeam/PojavLauncher#2863]
### Describe the bug

And  bug works something like this:
I start the app and select 1.7.10 Forge with optifine, and start normally and load and everything else the menu, then when I start the map if I'm moving the mouse (or sometimes even not) the mouse goes "disappearing/not working".
The camera (of the character) does not respond to movements and does not appear anymore, even when pausing or entering the inventory, and if I want it to appear I have to "go to the cell phone", I say I lower the notification shade, then I can move the menus (pause and inventory) but if I try to go back to move the character's camera it disappears and stops again! (There is the keyboard at all times works normally)

### The log file and images/videos

https://user-images.githubusercontent.com/58985545/157145835-10303991-5e20-4e6c-b904-2001d9670f04.mp4

https://user-images.githubusercontent.com/58985545/157145818-e0437573-c6e8-4cf1-8eac-c94e057378f0.mp4

### Steps To Reproduce

```markdown
Start in any version of Minecraft and be using the external mouse
```

### Expected Behavior

The ideal was to work the movement of the camera with the external mouse

### Platform

```markdown
- Device model: S70Lite DOOGEE/ 4 ram 64GB 
- CPU architecture: AArch64 Processor rev 4 (aarch64) - 64bit
- Android version: 8.1.0
- PojavLauncher version: crocus-v3_openjdk (Last Version of Google Play Store)
```

### Anything else?

The problem can be avoided if you remove the mouse and start the app and only when you are on the map try to move the camera.

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
