### ISSUE TITLE
Mod bug report

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#2865]
### Is this request related to a bug?

No

### Describe the request.

This not a request, because I just try to report the mod bug because it crash, and it say to write down what operating system are you use, and thr problemis that I play on pojavlauncher and my operating system is not a pc operating system.

### Anything else?

Can you help me about this problem?

**Comment by NotAHero04** [comment]
~~If that field is not a bunch of options, you may be OK if writing something like `Android X ARM64`.~~

**Comment by Thollp** [comment]
> ~If that field is not a bunch of options, you may be OK if writing something like `Android X ARM64`.~

Lol

**Comment by Mathias-Boulay** [comment]
#1948
