### ISSUE TITLE
when i click play its all black and i only hear music [BUG] <Short description>

### ISSUE THREAD

**Issue by Yeasts** [PojavLauncherTeam/PojavLauncher#2866]
### Describe the bug

its all black

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

i expected it to just take me to the menu

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

in the darkness i just hear the menu music

**Comment by khanhduytran0** [comment]
`.` is not a valid information. Closing until further response.
