### ISSUE TITLE
[BUG] Upsidedown virglrenderer bug

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#2867]
### Describe the bug

This is a another virgl entity bug that I think everyone might experience like me too. If you want to see how the bug look like, go to "The log file and images/video".

### The log file and images/videos

![Screenshot_20220309-094309_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/100254075/157362992-f0ecaf84-7267-450d-a1d7-4d644be68ea0.jpg)

### Steps To Reproduce

```markdown
Step 1. Play minecraft 1.18.1 with virglrenderer after you download the app
Step 2. Create the new world or enter the world that you created
```

### Expected Behavior

I expected the game not to look that weird.

### Platform

```markdown
- Device model: Samsung galaxy a32
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-333-d18faffce-v3_openjdk (An automatic build version that have virglrenderer-renderer)
```

### Anything else?

This bug can be fix (temporarily) by force close minecraft and play it again.

**Comment by Iarkont** [comment]
Enabling "disable VBOs" in PojavLauncher settings sometimes helps

**Comment by jackjt8** [comment]
> Enabling "disable VBOs" in PojavLauncher settings sometimes helps

This option does not exist in the latest nightly. Any other options?

**Comment by GaucovyAero** [comment]
> > Enabling "disable VBOs" in PojavLauncher settings sometimes helps
> 
> This option does not exist in the latest nightly. Any other options?

VirGL isn't technically a fully working renderer. I recommend using gl4es instead. Disabling VBOs doesn't help with VirGL from my experience.

**Comment by Mathias-Boulay** [comment]
We cannot fix virgl bugs :eyes:
