### ISSUE TITLE
[BUG] Game crashes at start screen while using a SkyBlock Addon(Forge)

### ISSUE THREAD

**Issue by BIPROO** [PojavLauncherTeam/PojavLauncher#2868]
### Describe the bug

So, when I installed a SkyBlock Addon called "NEU(https://github.com/NotEnoughCoins/NotEnoughCoins) to forge and runned it, after the MOJANG screen, a imagine shows up as displayed in the screenshot provided. So after that, when I click the "Next" button, the game freezes and it crashes with "Game Exited" error.

Same case with other mods such as Scrollable Tooltips, ctjs(Chat Trigger), etc.

### The log file and images/videos

![Screenshot_2022-03-09-16-30-11-203_net kdt pojavlaunch](https://user-images.githubusercontent.com/101257734/157434516-3e193373-952d-4732-8a54-068e0c78df4e.jpg)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8214277/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install Forge 1.8.9
2. Install 'Not Enough Coins' mod to Forge
3. Run the game
```

### Expected Behavior

I expect the game to work without any crashes.

### Platform

```markdown
- Device model: Poco X3 Pro 6/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release
- Minecraft version: Forge 1.8.9
- Ram allocated: 1453MB
- Renderer: gl4es 1.1.4
```

**Comment by BIPROO** [comment]
I also appeal to get me unbanned from the PojaLauncher discord server :P... Username:- BIPRO#4053

**Comment by BIPROO** [comment]
Let me know if I need to provide any othe informations.

**Comment by artdeell** [comment]
This looks like a mod's bug, not Pojav's, since there's no context on the finalizer thread.

**Comment by mchnjt** [comment]
> I also appeal to get me unbanned from the PojaLauncher discord server :P... Username:- BIPRO#4053

We aren't accepting unban appeals here.

**Comment by mchnjt** [comment]
In fact, I remember why you got banned.
You we're being "too" annoying that time.

**Comment by BIPROO** [comment]
ye ik

**Comment by BIPROO** [comment]
> This looks like a mod's bug, not Pojav's, since there's no context on the finalizer thread.

Oh, ok.. Thanks for the reply anyways!

**Comment by BIPROO** [comment]
Is there a solution tho?

**Comment by BIPROO** [comment]
Hello?

**Comment by BIPROO** [comment]
is there a fix for it?

**Comment by DovydasTEDS** [comment]
I also had this problem but you have to launch the .jar file under mod installer. (options -> launch mod installer)

**Comment by BIPROO** [comment]
> I also had this problem but you have to launch the .jar file under mod installer. (options -> launch mod installer)

It says "Game Exited" when I run it on load mod

**Comment by Mathias-Boulay** [comment]
#1948
