### ISSUE TITLE
[BUG] Optifine + Opti-Fabric Crashing while Standalone Optifine Dose Not (But has glitch) 1.18.1

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2869]
### Describe the bug

Whenever I have the `fabric-api-0.46.6+1.18`, `optifabric-1.12.10`, and `OptiFine_1.18.1_HD_U_H5` in the same mods folder, my game crashes, but if I only use Optifine and install it using the Mod Installer, it works but has a weird glitch (More on that below V)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8215669/latestlog.txt)
[mods.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8215673/some.mods.zip)

### Steps To Reproduce

```markdown
1. Download the  Fabric Installer 
2. Install  Fabric 0.13.3, 1.18.1  using PojavaLancher
3. Download and move  Optifine 1.18 HD Ultra H5 ,  Opti-Fabric 1.18.1 1.12.10 , and the  Fabric API O.46.6  to the mod folder
4. Play Fabric Loader 0.13.3, 1.18
5. Crash
```

### Expected Behavior

I expect the game to boot up correctly

### Platform

```markdown
- Device model: R96-14268.67.0
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

Optifine works if you install instead but has this weird bug where none of the custom menus show up, only the Minecraft defaults

**Comment by ghost** [comment]
That's an older version of the app. Try the latest action build.

**Comment by Errorbot1122** [comment]
oof, I cant update :(

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
