### ISSUE TITLE
[BUG] Fabric 1.18.1 crashing

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2870]
### Describe the bug

When I launch fabric 1.18.1 and up, it crashes! I’m using Java 17 too!

### The log file and images/videos

[text.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8216753/text.txt)

### Steps To Reproduce

```markdown
Setup Fabric 1.18.1 (1.13.3/1.13.2)
Set the Java version to 17
Launch
```

### Expected Behavior

The game crashes

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ghost** [comment]
I’m using checkra1n 1.12.4 on an iPad 7, I’m on the stable build

**Comment by ghost** [comment]
IOS 14.6

**Comment by kuzy21** [comment]
it also crash on android

**Comment by khanhduytran0** [comment]
> I’m using checkra1n 1.12.4 on an iPad 7, I’m on the stable build

You didn’t realize that this repo is for Android. Anyways, updating to latest build should fix it.
