### ISSUE TITLE
Discord Rpc

### ISSUE THREAD

**Issue by MerciGG** [PojavLauncherTeam/PojavLauncher#2872]
### Is this request related to a bug?

When will you guys fix/add a discord rpc support, all mods that has discord rpc automatically turned on will just not work and it crashes i and prolly some people will like it if you guys do add a working Discord RPC

### Describe the request.

Add discord rpc

**Comment by mchnjt** [comment]
You can try [MRPC](https://github.com/khanhduytran0/MRPC)

But no, I think they will not add that

**Comment by NotAHero04** [comment]
I have a workaround but I haven't properly tested with any mod that features Discord RPC (only LabyMod 1.8 tested thoroughly).

**Comment by GaucovyAero** [comment]
this won't be worked on
