### ISSUE TITLE
[BUG]gui scale and unicode font thing

### ISSUE THREAD

**Issue by MistyStory1** [PojavLauncherTeam/PojavLauncher#2873]
### Describe the bug

My gui scale value is 3,after I turn on force unicode font, the buttons became very large and I have to press esc to exit the interface,then I set gui scale value to 4,the buttons still very large,then I set the value to 1,the gui became small,after i set the value to 2, the gui became a little bigger,but when i set the value to 3,thebuttons became very large as the gui scale value is 4.I can't make the gui size normal with force unicode font on.

### The log file and images/videos

https://www.mediafire.com/file/z4djv5extanavkb/SVID_20220310_182348_1.mp4/file

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.launch minecraft
3.open language settings
4.turn force unicode font on
5.the gui became very large or small but can't be at a normal size
```

### Expected Behavior

the gui size should be normal with force unicode font option is on

### Platform

```markdown
- Device model: huawei nova 6s 8 /128G
- CPU architecture: idk
- Android version: 10
- PojavLauncher version: crocus-327-dcac1c9a9-v3_openjdk
```

**Comment by SprainedSpark89** [comment]
you probably have to deal with no unicode fonts

**Comment by Mathias-Boulay** [comment]
Pretty sure that's not our issue, but a minecraft one
