### ISSUE TITLE
[BUG] I can't find the option for change jre in the settings pages.

### ISSUE THREAD

**Issue by heipiao233** [PojavLauncherTeam/PojavLauncher#2874]
### Describe the bug

Just like the title.

### The log file and images/videos

no log

### Steps To Reproduce

```markdown
1. Start the app.
2. Turn to page settings.
```

### Expected Behavior

I except the button for changing JRE, but it doesn't show.

### Platform

```markdown
- Device model: Redmi Note 8
- CPU architecture: idk
- Android version: 10
- PojavLauncher version: Lastet
```

**Comment by SprainedSpark89** [comment]
there is it should say java runtime or jvm or java vm but not java arguments

**Comment by heipiao233** [comment]
> 

But JRE means Java Runtime Environment.
So how to change it? I just want to play 1.18 with Java 17.

**Comment by GaucovyAero** [comment]
First, download **Java Runtime Environment 17** [**here.**](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559) 

Then, in settings go to **Java Tweaks -> Runtime Manager -> Add new -> Select the newly-downloaded runtime in your downloads.**

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
