### ISSUE TITLE
[BUG] keyboard enters incognito mode 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2875]
### Describe the bug

The keyboard goes into incognito mode and it is not turned off in any way. This greatly hinders. a problem not only with the SwiftKey keyboard but also with other keyboards supporting incognito mode 

### The log file and images/videos

![Screenshot_20220310_175018_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/157687923-256a0beb-cd55-4475-8cf2-4a204a6afa33.jpg)

### Steps To Reproduce

```markdown
It's business as usual
```

### Expected Behavior

I expected the keyboard to work properly

### Platform

```markdown
- Device model: honor 9c AKA-L29
- CPU architecture: 64
- Android version: 
- PojavLauncher version:Latest Release || version 3.3.1.1_rel_20210206
```

### Anything else?

please fix this problem.

**Comment by SprainedSpark89** [comment]
it's probably your keyboard

**Comment by Iarkont** [comment]
> it's probably your keyboard

Other owners of "honor" phones have the same problems

**Comment by SprainedSpark89** [comment]
maybe it is dark

**Comment by CriticalRange** [comment]
> - PojavLauncher version:Latest Release || version 3.3.1.1_rel_20210206

Update your launcher via Google Play Store or GitHub actions

**Comment by Iarkont** [comment]
> > * PojavLauncher version:Latest Release || version 3.3.1.1_rel_20210206
> 
> Update your launcher via Google Play Store or GitHub actions

This is the latest release

**Comment by mchnjt** [comment]
Latest builds in [here](https://github.com/PojavLauncherTeam/PojavLauncher/actions) :trollface:

**Comment by Iarkont** [comment]
> Latest builds in [here](https://github.com/PojavLauncherTeam/PojavLauncher/actions) :trollface:

![Screenshot_20220312_091323_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/158006448-b4bbeb3b-889e-4b6b-8648-165790a3140d.jpg)
This is on the last build, the problem has not disappeared.

**Comment by Mathias-Boulay** [comment]
Hmm, I didn't ask for incognito mode though

**Comment by Mathias-Boulay** [comment]
Hmm, I didn't ask for incognito mode though

**Comment by Mathias-Boulay** [comment]
However, I fail to see what problem this causes for you, aside from not having the theme you want maybe

**Comment by Iarkont** [comment]
> However, I fail to see what problem this causes for you, aside from not having the theme you want maybe

This problem is caused by the function of new on-screen keyboards such as gboard and Microsoft SwiftKey, namely in new versions there is a function "automatic inclusion of incognito mode" which can not be disabled in the settings and in the pojavlauncher itself something causes the activation of this function of the keyboard. Of course the solution there is it is just to download the old version of the keyboard in which there is no function "auto incognito" but these versions of the keyboard are very old

**Comment by SprainedSpark89** [comment]
would this bug also cause your keyboard to pop up when minecraft is started
