### ISSUE TITLE
[BUG] Android 11, LineageOS, permissions.

### ISSUE THREAD

**Issue by s4velyeva** [PojavLauncherTeam/PojavLauncher#2877]
### Describe the bug

To save crash logs and to install Fabric or Forge app requests storage access. But when im moving to Apps > Permissions > PojavLauncher it doesnt request any permissions, so im not able to install mods && send crash logs.

Also, installers (OptiFine, Forge, Fabric) doesnt work, it says "Wait", then opens sorta thing like window, and then it just returns me back to the launcher, like nothing even happened.

Is it Android issue? I guess not.

### The log file and images/videos

![App doesnt request any permissions on Android 11](https://user-images.githubusercontent.com/93286636/157811416-6160f267-7327-4c06-806c-737480e9701d.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Try to install Fabric/Forge/OptiFine
3. Enjoy the bug.
```

### Expected Behavior

Installator raises and i can install Fabric.

### Platform

```markdown
- Device model: Xiaomi Redmi 8
- CPU architecture: aarch64
- Android version: BiancaProject (LineageOS), 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I just want to help community to make good launcher. i play minecraft on pc.

**Comment by artdeell** [comment]
OptiFine/Forge/Fabric installation doesn't run off of internal storage, so it should work. Stack trace dialog just wasn't patched with the new storage in mind, so it still wants permissions.

**Comment by GaucovyAero** [comment]
Isn't this old pojav? Update to the latest version here in [actions.](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

**Comment by s4velyeva** [comment]
> Isn't this old pojav? Update to the latest version here in [actions.](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

ok, now it new, but it still doesn't request any permissions.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
