### ISSUE TITLE
1.18 renderer not working.

### ISSUE THREAD

**Issue by lol851** [PojavLauncherTeam/PojavLauncher#2878]
### Describe the bug

Vgpu, gl4es 1.1.5, and gl4es 1.1.4, none of those will work when I launch 1.18 it just exits the whole entire game. And
zink (Vulkan) isn't compatible with my device (Chromebook.) Any thoughts on how my renderer could work so I can launch 1.18 thanks! 

### The log file and images/videos

![Screenshot 2022-03-11 08 00 41](https://user-images.githubusercontent.com/81200808/157871479-65d5c369-1395-4293-b00a-e2ace1011053.png)

### Steps To Reproduce

```markdown
So I start pojav-launcher. Then I log in and click on version 1.18.2.
Then I go to settings and click put java 17 in and turn up my ram. Then mostly I choose a new renderer to see if that one would work. And finally, launch 1.18
```

### Expected Behavior

I then expect the game to load in but then it crashes and exits the whole game.

### Platform

```markdown
- Device model: chromebook
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by WesleyVanNeck** [comment]
outdated version

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
