### ISSUE TITLE
1.81.2 start-up error 

### ISSUE THREAD

**Issue by Lqxv** [PojavLauncherTeam/PojavLauncher#2879]
### Describe the bug

Whenever I press play for 1.18.2 an error message says "ERROR can't find and compatible Java run time" Then the development console says "Library 1.18.2.json is fine and usable"

### The log file and images/videos

 
![Screenshot_20220311-071130_PojavLauncher (Minecraft Java Edition for Android)~2](https://user-images.githubusercontent.com/101413632/157895363-da490618-4732-4adf-b2c0-f608c10300ce.jpg)
![Screenshot_20220311-071630_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/101413632/157895365-7b7e9928-8790-4a42-a5a6-ccc2f0904f5f.jpg)

### Steps To Reproduce

```markdown
1. start pojav launcher 
2. Press play in 1.18.2
```

### Expected Behavior

Error

### Platform

```markdown
- Device model: Samsung Galaxy S21
- CPU architecture: ?
- Android version: 12
- PojavLauncher version: ?
```

**Comment by tigerbrocode** [comment]
Didn't knew 1.81.2 was realeased i thought it would be released in 2072

**Comment by tigerbrocode** [comment]
Anyways download java 16 or 17

**Comment by sbgigapsec** [comment]
imagine 1.81.2 before getting 2.0
like Minecraft getting upto 1.100.0

**Comment by Lqxv** [comment]
Opps! ha!I meant to say 1.18.2

**Comment by kuzy21** [comment]
Use this runtime: https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
