### ISSUE TITLE
[F-Req] Controller remapping settings + controller overhaul

### ISSUE THREAD

**Issue by gqminq** [PojavLauncherTeam/PojavLauncher#2880]
### Describe the request.

At the moment Pojav does support controller, however it's quirky... Like crouch is d-pad up instead of B and you can't really open chat. Minecraft itself doesn't support remapping as trying to put Jump as B it simply says "No buttons" 

Pojav should include settings to remap controllers in launcher as a work around as I'm sure this would benefit a lot of players.

**Comment by mchnjt** [comment]
@Mathias-Boulay

**Comment by Mathias-Boulay** [comment]
On the roadmap for controls V3 😄 
Although I need time to code them, god know when I will have some

**Comment by GaucovyAero** [comment]
closing as this is a duplicate
