### ISSUE TITLE
[F-Req] FIX LEFT CLICK android 9 "external mouse"

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2881]
### Is this request related to a bug?

Yes cant left click on Android 9

### Describe the request.

I just want to play pvp but the left click does not work.

### Anything else?

Pls fix if you could.

**Comment by mchnjt** [comment]
PRI is the left click button, what do you mean

**Comment by MARnelPH12** [comment]
EXTERNAL MOUSE BROO U DONT KNOW THAT?

**Comment by mchnjt** [comment]
please put `[external mouse]` when you make issues about external mouse
thank you

**Comment by Mathias-Boulay** [comment]
Please, report precisely which version you used.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
