### ISSUE TITLE
[BUG] Crashing when rendering

### ISSUE THREAD

**Issue by jaYyYyY69** [PojavLauncherTeam/PojavLauncher#2882]
### Describe the bug

So I am using Pojav Launcher for the quest 2 and every time I try to load in the game. Its like black and when i look in the crash log it says rendering overlay and shaders failed to load or something like that. I don't have any mods on yet and I don't know if I need them. I'll try to add a screenshot of the crash log soon.

### The log file and images/videos

https://pastebin.com/7E7DuhwK

### Steps To Reproduce

```markdown
1. Download Sidequest and install Questcraft on your Quest 2.

2. When Questcraft is done, it should also install Pojav too. Just open it and select the most recent version of Minecraft

3. Press play and it should be black for like 30 seconds it will just restart Pojav Launcher.
```

### Expected Behavior

I expect the game to load me in the title screen of minecraft vr.

### Platform

```markdown
- Device model: Quest 2
- CPU architecture: idk what that means
- Android version: my oculus version is v37
- PojavLauncher version: 20210430
```

**Comment by artdeell** [comment]
Please open this in questcraft repository

**Comment by jaYyYyY69** [comment]
> Please open this in questcraft repository

?

**Comment by artdeell** [comment]
> > Please open this in questcraft repository
> 
> ?

We don't handle questcraft-related issues here since Pojav itself doesn't have VR-related code at all.

**Comment by jaYyYyY69** [comment]
so how do i fix it?
