### ISSUE TITLE
[BUG] Mouse doesn't work

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#2885]
### Describe the bug

Since I start playing pojav... (I don't want to call it pojavlauncher so I write pojav...), I have found a first bug which is very annoying is that the mouse doesn't work. This bug was so annoying that it make game unplayable

### The log file and images/videos

![Screenshot_20220312-173014_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/100254075/158014537-0d04b854-050c-48ad-8b76-def8c2b60e7b.jpg)

### Steps To Reproduce

```markdown
Step 1. Play any Minecraft version on Pojav...
Step 2. Turn the mouse on while wating the game to launch.
Step 3. Wait for the loading menu to finish loading.
Steo 4. Try hovering a mouse on to off any button.
```

### Expected Behavior

I expected the mouse to work

### Platform

```markdown
- Device model: *Any device model (mine is Samsung galaxy a32)*
- CPU architecture: *Any (Mine is aarch64/arm64)*
- Android version: *Any? (Mine is 11)*
- PojavLauncher version: *Any version*
```

### Anything else?

The reason why I said "any on 'plaform' " section because it already happened to other people.

**Comment by GaucovyAero** [comment]
Update to the latest action build [here.](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

**Comment by NotAHero04** [comment]
Whenever you play on 1.13+, don't touch the screen until the game starts.

**Comment by DovydasTEDS** [comment]
I have no issue and play 1.8.9 and 1.16.5 with keyboard and mouse, has no issues. I know this might be unrelated but why are you playing a modpack? Especially on 1.18! I'd also recommend hiding your gui if playing with a mouse.

**Comment by Thollp** [comment]
> I have no issue and play 1.8.9 and 1.16.5 with keyboard and mouse, has no issues. I know this might be unrelated but why are you playing a modpack? Especially on 1.18! I'd also recommend hiding your gui if playing with a mouse.

I just want to play with modpacks. And also, I have the same issue when I play with 1.16.5

**Comment by Thollp** [comment]
> I have no issue and play 1.8.9 and 1.16.5 with keyboard and mouse, has no issues. I know this might be unrelated but why are you playing a modpack? Especially on 1.18! I'd also recommend hiding your gui if playing with a mouse.

And also, how this is unrelated?

**Comment by DovydasTEDS** [comment]
> > I have no issue and play 1.8.9 and 1.16.5 with keyboard and mouse, has no issues. I know this might be unrelated but why are you playing a modpack? Especially on 1.18! I'd also recommend hiding your gui if playing with a mouse.
> 
> And also, how this is unrelated?

Probably because if it works, it works. I also mentioned that as many mods, including modpacks require a lot of ram / resources and may cause lots of lag.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.

**Comment by Cookie6612** [comment]
I'm experiencing a problem where I connect external mouse with my device 128 storage 6gb ram android 10  my mouse dosent fix / lock in il explain more on discord : itsmecookie6613
