### ISSUE TITLE
QUESTION: Where Pojav stores the game's files?

### ISSUE THREAD

**Issue by vico93** [PojavLauncherTeam/PojavLauncher#2887]
### Describe the bug

I can't find it using Samsung's File Explorer.

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

-

### Platform

```markdown
- Device model: Galaxy A8 2018
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release on Google Play.
```

**Comment by SamGoneMissing** [comment]
Even for
 me it shows nothing try some other explorers

**Comment by CriticalRange** [comment]
```/sdcard(Internal Storage)/games/PojavLauncher/.minecraft/``` for Android 9 and lower
```/sdcard(Internal Storage)/Android/data/net.kdt.pojavlaunch/files/.Minecraft/``` for Android 10+

Use Zarchiver if Android 10+

**Comment by vico93** [comment]
Thanks a lot for the info
