### ISSUE TITLE
[QUESTION] hi mate could i ask if 1.18 is getting worked  on? haha i would really wanna play 1.18 in my one year hardcore wold but there are just so many lags and rendering problems that doesnt match with hardcore minecraft sorry for interrupting thanks 

### ISSUE THREAD

**Issue by Dev1ss0** [PojavLauncherTeam/PojavLauncher#2889]
### Describe the bug

lag

### The log file and images/videos

.

### Steps To Reproduce

```markdown
start pojav on 1.18 and runs normal but lags alot
```

### Expected Behavior

alot of lag

### Platform

```markdown
- Device model: samsung galaxy s9+
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: 1,18
```

**Comment by WesleyVanNeck** [comment]
ask those qeastions on discord not on github

**Comment by KnuterrYT** [comment]
Everytime I go on pojav launcher then I go on a random update with no OptiFine then it crashes can you help me with that please
Device: Samsung Galaxy Tab a

**Comment by Dev1ss0** [comment]
u can use optifine but u have to patch it and turn off render regius (idk how to write that ) lmao

**Comment by WesleyVanNeck** [comment]
> Everytime I go on pojav launcher then I go on a random update with no OptiFine then it crashes can you help me with that please Device: Samsung Galaxy Tab a

Open your own issue

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
