### ISSUE TITLE
Premium servers error

### ISSUE THREAD

**Issue by TreinTR** [PojavLauncherTeam/PojavLauncher#289]
If i try to join premium server i get this error:

Internal Exception: java.lang.NullPointerException: Attempt to invoke virtual method bytell javax.crypto.Cipher.doFinal(bytell on a null object reference

What can i do?

**Comment by TreinTR** [comment]
I tried to join on 1.11.2 pojavlauncher ver. 2.5.2

**Comment by khanhduytran0** [comment]
Try to join with OptiFine installed version.

**Comment by TreinTR** [comment]
![Screenshot_20200829-091214](https://user-images.githubusercontent.com/62346884/91630155-c88ac700-e9d7-11ea-81ca-62b322f38014.png)
I can't

**Comment by TreinTR** [comment]
And i tried pojavlauncher beta 2.5.3 optifine works but servers still give that error

**Comment by WesleyVanNeck** [comment]
@TreinTR  van you try my patched apk as it fixes tour issue https://drive.google.com/file/d/1UWv6d13-FzYxuhXkwp9FUR75T9zqI_aX/view?usp=sharing

**Comment by TreinTR** [comment]
> @TreinTR van you try my patched apk as it fixes tour issue https://drive.google.com/file/d/1UWv6d13-FzYxuhXkwp9FUR75T9zqI_aX/view?usp=sharing

I can join hypixel but i think my phone isnt powerful enough to handle this, but maybe optifine will help. Thank you.

**Comment by WesleyVanNeck** [comment]
your welcome
