### ISSUE TITLE
[F-Req] pls make pojav support android 9

### ISSUE THREAD

**Issue by 23ergbcf** [PojavLauncherTeam/PojavLauncher#2890]
### Is this request related to a bug?

my samsung s8 is android 9, and i cant use pojavlauncher, but if i use other phone thats android 10+ it works fine

### Describe the request.

pls make pojav support android 9

### Anything else?

.

**Comment by WesleyVanNeck** [comment]
> ### Is this request related to a bug?
> my samsung s8 is android 9, and i cant use pojavlauncher, but if i use other phone thats android 10+ it works fine
> 
> ### Describe the request.
> pls make pojav support android 9
> 
> ### Anything else?
> .

pojav supports android 5.1 up to android 12.1

**Comment by WesleyVanNeck** [comment]
also without a log no help

**Comment by 23ergbcf** [comment]
huh thats really weird please check my another issue

**Comment by 23ergbcf** [comment]
> also without a log no help

can you check my last issue? i really need help im despreate

**Comment by mchnjt** [comment]
> also without a log no help

you forgot one more thing: no account = no support
