### ISSUE TITLE
[F-Req] Add Seperate .minecraft directories

### ISSUE THREAD

**Issue by DovydasTEDS** [PojavLauncherTeam/PojavLauncher#2892]
### Describe the request.

In the vanilla minecraft launcher, you can make profiles and choose the minecraft directory location. You could add an option to change it for different minecraft versions / add profiles or do something like **MultiMC**.

**Comment by artdeell** [comment]
Check builds from branch profiles-2-electric-boogaloo

**Comment by DovydasTEDS** [comment]
Hello, I downloaded the build but I am unable to set a .minecraft directory or mods folder for each installation of Minecraft. Due to this, I cannot seperately contain the mod files without moving them in and out using an external file browser, which is hard to come by one that you can actually edit the Android/data folder.

**Comment by DovydasTEDS** [comment]
Temporary fix (mods folder): have a folder inside mods for the mc version e.g.
mods/
           1.8.9/
                      1.8.9mod.jar
          1.12.2/
                      1.12.2mod.jar
