### ISSUE TITLE
why is the profile mode removed even though it's cool

### ISSUE THREAD

**Issue by BeJohnsonSentosa12** [PojavLauncherTeam/PojavLauncher#2893]
### Is this request related to a bug?

I just want profile mode back (if you can bring it back)

**Comment by 1493028** [comment]
maybe for security reasons it was removed

**Comment by Mathias-Boulay** [comment]
We'll let you handle the prison time and bills we could face.

**Comment by kuzy21** [comment]
Buy the game if you want to play read this: https://pojavlauncherteam.github.io/about-pojavlauncher/legal.html
