### ISSUE TITLE
[BUG] Can't Run Minecraft When Using Local Account (Offline Account)

### ISSUE THREAD

**Issue by 1493028** [PojavLauncherTeam/PojavLauncher#2894]
### Describe the bug

I want to start minecraft 1.12.2 OptiFine with an offline account but I can't write it, I recommend using an online account (mojang account) but I don't have money to buy me a Mojang though 

### The log file and images/videos

Nope

### Steps To Reproduce

```markdown
1. Open up Pojav launcher
2. Select offline account
3. Select version
4. Can't load the game
```

### Expected Behavior

It Does't running with offline account

### Platform

```markdown
- Device model: Vivo y50
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest Github Build
```

### Anything else?

It Does't running the game

**Comment by Jamespoxdxdxd** [comment]
same i dont have any money to buy a mojang account

**Comment by mchnjt** [comment]
PIRATES

**Comment by Jamespoxdxdxd** [comment]
> PIRATES

yep But i got no choice though im a broke man

**Comment by BeJohnsonSentosa12** [comment]
> same i dont have any money to buy a mojang account

Bruh

**Comment by kuzy21** [comment]
Get the game if you want bitches k or do you guys want no bitches 🤨

**Comment by XavierErrorLog** [comment]
Even though I have a jave account yall need to shut up first of all were going through a great depression. Second, getting a job is harder, and 3rd you don't get more women when you get Minecraft even though I have a gf most Minecrafters touch grass once a week. So you can take your 5000$ device somewhere else if I were you, James, I would try to look for a job for yourself and Minecraft ( not recommended ) I could give you 100,000,000$ buttt I can't do that cause that's going to pay for all the bills from my houses so0... Good Luck!

**Comment by Mathias-Boulay** [comment]
NOT Fixed on the release candidate build.

**Comment by hiimabignoobwihenolive** [comment]
yoooo there something called pirateing and its free source: trust me bro

**Comment by mchnjt** [comment]
> yoooo there something called pirateing and its free source: trust me bro

Not funny... Please don't introduce our users to pirating Minecraft, we're already glad that Microsoft didn't decide to pursue pulling PojavLauncher out of existence 

PojavLauncher was NOT made for the specific reason(s);
- To let our users play Minecraft: Java Edition on Android literally for FREE;
- To introduce our users to piracy;
- To replace the Android-native edition of Minecraft (Bedrock).

We weren't up to anything else until Microsoft found about this project, the main cause: this one-of-a-hell virus pandemic, youtube content, and popularity. You are allowed to downgrade PojavLauncher and play Minecraft within your heart's content; that is, if Mojang doesn't do account encryption to their resources download server. DO NOT BEG TO US TO BRING BACK OFFLINE MODE, THAT WILL **NOT** MAKE US BREAK A BONE OR TWO. Not even as a Christmas present to children like you.
