### ISSUE TITLE
[BUG] <Crash 1.16.5.>

### ISSUE THREAD

**Issue by lol851** [PojavLauncherTeam/PojavLauncher#2895]
### Describe the bug

When start-up a world on pojavlauncher right as it's about to go in it crashes. And exits the whole game.

### The log file and images/videos

![image](https://user-images.githubusercontent.com/81200808/158091043-8f3de3eb-75fc-4275-9f93-6840cc5b7f57.png)

### Steps To Reproduce

```markdown
1. start pojav launcher
2. Load in world
3. Games saves
4. The launcher crashes
```

### Expected Behavior

I expect to go onto my world.

### Platform

```markdown
- Device model: Chromebook
- CPU architecture: arm 64
- Android version: idk
- PojavLauncher version: 16.5
```

**Comment by khanhduytran0** [comment]
We saw that :eyes: as the stack trace said, you tried to modify the skin file, which means you didn’t buy the game.

**Comment by khanhduytran0** [comment]
Please buy the game and change your skin in https://minecraft.net/en-us/profile/skin

**Comment by lol851** [comment]
i bought the game though??
