### ISSUE TITLE
20220307_JDK17_AARCH64 zip file is corrupt

### ISSUE THREAD

**Issue by routhing** [PojavLauncherTeam/PojavLauncher#2897]
### Describe the bug

The latest release of the 20220307_JDK17_AARCH64_runtime file is corrupt.
(Use the unzipper software is com.rarlab.rar.6.10.build4.apk)

### The log file and images/videos

*

### Steps To Reproduce

```markdown
*
```

### Expected Behavior

*

### Platform

```markdown
- Device model: Redmi k30 5g
- CPU architecture: sdm765g/sm7250
- Android version: 10/MIUI12.0.7
- PojavLauncher version: latest release
```

### Anything else?

![Screenshot_2022-03-15-00-48-58-278_com opera browser](https://user-images.githubusercontent.com/71493668/158222762-83a5cea8-b9d2-4ed2-8464-b2aeab823fbd.jpg)
![Screenshot_2022-03-15-00-33-47-600_com rarlab rar](https://user-images.githubusercontent.com/71493668/158222770-619fe149-9b74-43b2-bbac-e3e9f06f8a59.jpg)

**Comment by routhing** [comment]
I have used these browsers is KiwiBrowser, Microsoft Edge and Opera, the zipper files both corrupted still

**Comment by WesleyVanNeck** [comment]
you dont use jdk use jre

**Comment by DovydasTEDS** [comment]
Also once you download the jre file, go to pojav launcher ->  options -> java (i can't remember) -> import and then select the file you downloaded.

**Comment by routhing** [comment]
> 

Have a small number of MODs are doesn't work if do not use JDK, For example: REI for MC1.17 on my 红米k30 5g

**Comment by routhing** [comment]
> 

Have a small number of MODs are doesn't work if do not use JDK, For example: REI for MC1.17 on my Redmi k30 5g Phone.

**Comment by artdeell** [comment]
Pojav was never able to run JDK, so...
Unless your mod actually requires it (REI does not), you don't need JDK.

**Comment by routhing** [comment]
> Pojav was never able to run JDK, so... Unless your mod actually requires it (REI does not), you don't need JDK.

I compared to the 20211126 Java17 version, jre17 is report it wrong(The log is probably about sun.java, I don't care about the following content), and few modules is doesn't work to Jre17. I mainly play on the Survival-Redstone server, and some special auxiliary modules are required.

**Comment by khanhduytran0** [comment]
JDK is JRE with additional **D**evelopment **K**it. How does a mod require the development kit? Does the mod allow you to code Java right in Minecraft? 🤔

**Comment by kuzy21** [comment]
Use this: https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz

**Comment by DovydasTEDS** [comment]
I don't believe the OP knows you can scroll in that page.

**Comment by ghost** [comment]
> Use this: https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz

this is **ARM64, NOT AARCH64**, try again

**Comment by artdeell** [comment]
literally the same thing

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.

**Comment by ugamerz982** [comment]
License file is currupted

**Comment by DovydasTEDS** [comment]
> License file is currupted

Why are you talking in a 2 YEAR OLD ISSUE.
