### ISSUE TITLE
[BUG] the screem turned upside down after press F2

### ISSUE THREAD

**Issue by west-shell** [PojavLauncherTeam/PojavLauncher#2902]
### Describe the bug

virgle has the bug

### The log file and images/videos

![Screenshot_20220315_112417_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/50977607/158300204-9f7494b9-46db-4fd7-ba00-73f34b654237.jpg)

### Steps To Reproduce

```markdown
use virgle render .enter a world in 1.18 .press F2
```

### Expected Behavior

work fine

### Platform

```markdown
- Device model: huawei M6
- CPU architecture: vendor Kirin980 (8) @ 1.805GH
- Android version: HarmonyOS 2.0
- PojavLauncher version: latest
```

### Anything else?

![Screenshot_20220315_113515_com android settings](https://user-images.githubusercontent.com/50977607/158301145-4e7d1108-f024-4e09-a509-9dbd702820c8.jpg)
this version works fine .the actions after this one all have the same bug

**Comment by SprainedSpark89** [comment]
looks like a iphone not a android

**Comment by west-shell** [comment]
Android CI #3626
 ddae3ec
v3_openjdk

**Comment by SprainedSpark89** [comment]
is it external keyboard?

**Comment by ghost** [comment]
That looks like IOS. If it is, make an issue here. https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues

**Comment by west-shell** [comment]
it is android10

**Comment by SprainedSpark89** [comment]
Are you sure it's that device

**Comment by west-shell** [comment]
![Screenshot_20220329_170208_com android settings](https://user-images.githubusercontent.com/50977607/160575599-a6e982fa-9685-4532-84c3-f64c854ce344.jpg)

**Comment by SprainedSpark89** [comment]
maybe android but also maybe ios

**Comment by SprainedSpark89** [comment]
@Smokeybear12 i think it's an android

**Comment by west-shell** [comment]
😂 Of course. It's a type of Android . That doesn't matter. Fix bug, please. It has been a long time.  It has been  Fixed  One time. But not really. Occasionally occurs. Especially when press f2.  Originally  I'm too lazy to report it. Hope someone will found it and fix it.  But nothing happened.

**Comment by Mathias-Boulay** [comment]
virgl stuff cannot be fixed

**Comment by west-shell** [comment]
why it have no bug before
