### ISSUE TITLE
[F-Req] A cool idea!!

### ISSUE THREAD

**Issue by VocalNutria9174** [PojavLauncherTeam/PojavLauncher#2905]
### A good idea:

You should add PojavLauncher to https://now.gg/ (it's basically an android app cloud streamer thing)
If you do this, we would basically have Minecraft java online!
=)

(_more info here: https://dev.now.gg/_)

**Comment by Jamespoxdxdxd** [comment]
umm what is this do?

**Comment by VocalNutria9174** [comment]
> umm what is this do?

It's a cloud gaming service that can run android apps. It has stuff like Among Us, Minecraft (Trial), etc...

**Comment by ghost** [comment]
I think they are talking about something like Gforce now.

**Comment by mchnjt** [comment]
> ### A good idea:
> You should add PojavLauncher to https://now.gg/ (it's basically an android app cloud streamer thing) If you do this, we would basically have Minecraft java online! =)
> 
> (_more info here: https://dev.now.gg/_)

you can make pojav online by connecting to wifi or enabling your data :frwoe:

**Comment by sbgigapsec** [comment]
I think it means you dont have to actually use your devices resources to run the game

**Comment by ajit56** [comment]
I think it is nice Idea if device is not supported then users can play on emulator like app

**Comment by ghost** [comment]
This is the PC version of what they are talking about. https://www.nvidia.com/en-us/geforce-now/

**Comment by VocalNutria9174** [comment]
Okokokok.
Bacilly now.gg is an android emulator, but in a web browser. It's really cool.

**Comment by VocalNutria9174** [comment]
But it is bacilly GeForce now, but a bit better

**Comment by CriticalRange** [comment]
So it's something like BlueStack X ? Afaik you can request apps to be added on it. But idk about now.gg

**Comment by VocalNutria9174** [comment]
> So it's something like BlueStack X ? Afaik you can request apps to be added on it. But idk about now.gg
Actually now.gg is owned by Bluestacks, soooo yeah.

**Comment by CriticalRange** [comment]
> > So it's something like BlueStack X ? Afaik you can request apps to be added on it. But idk about now.gg
> > Actually now.gg is owned by Bluestacks, soooo yeah.

Oh lol
I remember requestion pojav there
Maybe request again ?

**Comment by VocalNutria9174** [comment]
> you can make pojav online by connecting to wifi or enabling your data :frwoe:

@st0rmc4non what I was saying was that you can play pojavlauncher in a web browser using now.gg. now.gg is basically a android app emulator, but in a web browser (like geforce now for web, but bluestacks).
(a good example of it running would be in among us: https://now.gg/play/innersloth-llc/4047/among-us)

**Comment by Mathias-Boulay** [comment]
Won't be done

**Comment by mchnjt** [comment]
> > you can make pojav online by connecting to wifi or enabling your data :frwoe:
> 
> @st0rmc4non what I was saying was that you can play pojavlauncher in a web browser using now.gg. now.gg is basically a android app emulator, but in a web browser (like geforce now for web, but bluestacks). (a good example of it running would be in among us: https://now.gg/play/innersloth-llc/4047/among-us)

basically you're referring to something like S3AIR on the browser
Also, PojavLauncher is a **Launcher**, not the game itself.
