### ISSUE TITLE
please add keyboard suport to headsets

### ISSUE THREAD

**Issue by FarnoldFishyfliper69** [PojavLauncherTeam/PojavLauncher#2907]
### Is this request related to a bug?

whenever i tried to join a sever on questcraft i could not type in the adress can you add some type of virtural keyboard to help me

### Describe the request.

virtural keyboard for headset devices

**Comment by mchnjt** [comment]
gaming in a sound device? 😂
Anyways, I don't know what you're referring to "headset"

**Comment by artdeell** [comment]
Oprn this at the QuestCraft repository, we don't do headset support here
