### ISSUE TITLE
[BUG] Virgl 4.3 lagging

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2908]
### Describe the bug

The problem is that when playing with this visualizer, the game lags wildly. Even if you have a powerful phone. Why I'm writing this: because 1.18 only works with this renderer. Please fix this

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8258277/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select virgl renderer
3. Launch fabric 1.18.1
4. Join the world
5. watch the lags (The main menu of the game also lags)
```

### Expected Behavior

I expect that I will not lag. Because I have a powerful phone

### Platform

```markdown
- Device model: Redmi 10 4/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest debug from github actions
```

**Comment by sbgigapsec** [comment]
use gl4es virgl is really laggy

**Comment by Mathias-Boulay** [comment]
virgl cannot really be fixed
