### ISSUE TITLE
Could not find valid game provider!

### ISSUE THREAD

**Issue by routhing** [PojavLauncherTeam/PojavLauncher#2911]
### Describe the bug

PojavAPP-version: after v3.3.1.1 all version
Java17-runtime-version: jre20210630~jre20220307
game-version: 1.17.1-fabric (no mods)

### The log file and images/videos

  <log4j:Event logger="FabricLoader" timestamp="1647415858303" level="ERROR" thread="main">
    <log4j:Message><![CDATA[Could not find valid game provider!]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader" timestamp="1647415858317" level="ERROR" thread="main">
    <log4j:Message><![CDATA[- Minecraft]]></log4j:Message>
  </log4j:Event>
Exception in thread "main" 
java.lang.RuntimeException: Could not find valid game provider!
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:104)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Java Exit code: 1
I/jrelog  ( 1914): Going to free args

I/jrelog  ( 1914): Free done

### Steps To Reproduce

```markdown
*
```

### Expected Behavior

*

### Platform

```markdown
- Device model: sm-n920v(sm-note5-verizon)
- CPU architecture: exynos7420
- Android version: 7.0
- PojavLauncher version: latest
```

**Comment by NotAHero04** [comment]
You are using an unsupported launcher version. Update your launcher.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
