### ISSUE TITLE
[BUG] Sodium loading sodium-mixins.properties from .minecraft while a seperated folder is selected for game instance

### ISSUE THREAD

**Issue by sbgigapsec** [PojavLauncherTeam/PojavLauncher#2912]
### Describe the bug

I have set my minecraft folder to a different folder than .minecraft
Sodium mod should load sodium-mixins.properties from that folder rather than .minecraft

### The log file and images/videos

No response

### Steps To Reproduce

```markdown
1. Set Pojav launcher Game folder to one different than .minecraft
2. write a config/sodium-mixins.properties with contents "mixin.features.chunk_rendering=false" in said folder
3. Load minecraft and join a world
```

### Expected Behavior

Should join the world normally with chunk rendering mixins disabled

### Platform

```markdown
- Device model: Honor 6x
- CPU architecture: aarch64
- Android version: 7.0
- PojavLauncher version: https://github.com/PojavLauncherTeam/PojavLauncher/tree/de8a16e5c5bd3b2e898919e33ade44fcff4cca41
- Mc version: 1.18.2
- Fabric version: 0.13.3
- Sodium version: 0.4.1
```

### Anything else?

-- Workarounds:
put sodium-mixins.properties in .minecraft/config

**Comment by sbgigapsec** [comment]
btw it does load with sodium after using the workaround

**Comment by sbgigapsec** [comment]
![2022-03-16_04 55 02](https://user-images.githubusercontent.com/100747661/158560318-5d240634-2ee7-4b93-b9cd-2d3bdb8dcf86.png)

**Comment by sbgigapsec** [comment]
![Uploading Screenshot_20220316-100609.png…]()

**Comment by sbgigapsec** [comment]
![Screenshot_20220316-100609](https://user-images.githubusercontent.com/100747661/158561498-2b7845d8-3e66-4f03-a55e-953d60474096.png)

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/folder/n004fh6pxuxk8/Sodium+1.17+
here's the patch archive for Sodium, along with Sodium Extra + GL4ES

**Comment by Mathias-Boulay** [comment]
The worrying part for me is that fabric did not take into account the custom instance path
