### ISSUE TITLE
Minecraft 22w11a+ not working [BUG]

### ISSUE THREAD

**Issue by Illia24** [PojavLauncherTeam/PojavLauncher#2914]
### Anything else?

Mojang up format of resourcepacks to 9.

**Comment by Illia24** [comment]
Im hate mojang

**Comment by ghost** [comment]
Download the assets-v0 for 1.18 and go inside the pack.mcmeta and change the resource level to 9. That will hopefully fix the problem.

**Comment by Illia24** [comment]
Thanks REALLY WORKS!!

**Comment by ghost** [comment]
You are welcome.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
