### ISSUE TITLE
[F-Req] I Just Want Asked What The New Fitures In Latest Release Of Pojavlauncher 

### ISSUE THREAD

**Issue by BeJohnsonSentosa12** [PojavLauncherTeam/PojavLauncher#2918]
### Is this request related to a bug?

Just Asked

### Describe the request.

No 

### Anything else?

Nope

**Comment by artdeell** [comment]
You'll see when it would be released
For more information track the #development channel on our Discord server.

**Comment by BeJohnsonSentosa12** [comment]
> You'll see when it would be released For more information track the #development channel on our Discord server.

I can't i just got banned from the discord!
