### ISSUE TITLE
[F-Req] Xbox avatar profile

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2919]
### Is this request related to a bug?

I propose to make in the main menu of the launcher in the upper left corner (near the nickname) your avatar xbox account(like in the original minecraft launcher)

**Comment by andr0d1v** [comment]
only for licensed accounts

**Comment by artdeell** [comment]
Why? It uses your minecraft skin which is better in my opinion.

**Comment by andr0d1v** [comment]
i want it to look like in the original minecraft launcher

**Comment by Mathias-Boulay** [comment]
I agree with @artdeell here.

**Comment by andr0d1v** [comment]
Then why is my skin's head not showing up in the launcher? Even though I'm licensed!

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
