### ISSUE TITLE
Error during startup 1.15.2

### ISSUE THREAD

**Issue by moss0206** [PojavLauncherTeam/PojavLauncher#292]
Hi. I am a Korean Minecraft user.
My friends and I tried to play 1.15.2 using pojav launcher, but we all failed.
 Does this not support this 1.15.2 version?
 I keep getting error messages. Somebody help me.
 I'm sorry if I wasn't good at English.

**Comment by Malaska678** [comment]
@moss0206 1.11.2 and below is supported(only V2). And 1.12+ are planned in v3 toghether with forge and mods.

**Comment by xXFrostXx1** [comment]
Why not start from the latest Verison or Closest to him

**Comment by khanhduytran0** [comment]
Use v3, it now support 1.13+ including 1.16.3, do not try aarch64 one as it currently have problem, use this build with arm32 java https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/263292770
