### ISSUE TITLE
[F-Req] Ability to change game directory

### ISSUE THREAD

**Issue by DovydasTEDS** [PojavLauncherTeam/PojavLauncher#2920]
### Is this request related to a bug?

Nope

### Describe the request.

Have the ability to change the profile directory such as /{pojav directory}/profiles/{profile}

### Anything else?

Nope

**Comment by Evenz3839** [comment]
Good idea 
Download the latest apk of pojava (on github)
The newest apk redirects the path to Android/games/net
Kit.pojava (or somthing)

**Comment by DovydasTEDS** [comment]
I want each profile to have a seperate directory

**Comment by ghost** [comment]
That would be a good thing to do.

**Comment by DovydasTEDS** [comment]
Thank you so much Pojav devs!
