### ISSUE TITLE
Microsoft account login option doesn't work, Game Crash related to popup for login option

### ISSUE THREAD

**Issue by KayCelestia** [PojavLauncherTeam/PojavLauncher#2922]
### Describe the bug

Microsoft login Error:
It doesn't load, returns the following error: 
net::ERR_NAME_NOT_RESOLVED
This is consistant, and always happens for me. I'm using the latest play store version by the way. I'm using a Galaxy Tablet A7 Lite if that helps at all. 
![Screenshot_20220317-173222_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/101845050/158916078-74e3d44d-3679-4b54-a8f2-ebd07f61d0bf.jpg)

### The log file and images/videos

Log Generation/Storage Permissions issue:
The application cannot generate a log without storage permissions, yet those are not requested and there isn't an option to allow for storage either.

### Steps To Reproduce

```markdown
Microsoft Login Option Issue
1. Start Pojavlauncher
2. Click Microsoft Login
3. Allow popup/gui to load
4. Popup fails to load and returns the error specified earlier.

Storage issue
If exiting popup after failed load or during loading, the application will crash, causing an error to occur.
```

### Expected Behavior

I expected the Microsoft login page to load, yet it did not.

### Platform

```markdown
- Device model: Samsung Galaxy Tablet A7 Lite
- CPU architecture: ARM 64-bit
- Android version: Android 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

It's been a problem for my home network before, and if it isn't devices, I'd love some insight into why this is happening. Thank you for your time!

**Comment by KayCelestia** [comment]
Sorry if this isn't enough btw. I'd ask about this in the discord probably but I don't have a phone so...

**Comment by ghost** [comment]
Update your launcher to the latest action build.

If you can please upload the latestlog.txt which located at android/data/net.kdt.pojavlauncher/files.

**Comment by KayCelestia** [comment]
Alr, I'll look for the log, also, is there a newer version available? Is that available on github or play store?

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
