### ISSUE TITLE
[F-Req] Im just wondering if you guys can bring back this feature

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#2923]
### Is this request related to a bug?

no

### Describe the request.

I just want to get the password back at Pojav launcher on github just like this one 
![Screenshot_2022-03-18-12-46-22-32](https://user-images.githubusercontent.com/87040006/158939343-39f09d33-040d-482b-9b5c-b97dcf079a26.jpg)

### Anything else?

Yeah i just want to get it back on Pojavlauncher

**Comment by ajit56** [comment]
Idk what you want

**Comment by Jamespoxdxdxd** [comment]
i want the Password get back on github version of Pojavlaucnher cause look

**Comment by Jamespoxdxdxd** [comment]
![Screenshot_2022-03-18-16-57-11-48](https://user-images.githubusercontent.com/87040006/158971862-15ca279b-9dae-4815-9023-7132c6b7c4a0.jpg)

**Comment by kedrick021** [comment]
Yeah delete the Pojavlauncher site

**Comment by CriticalRange** [comment]
> ### Is this request related to a bug?
> no
> 
> ### Describe the request.
> I just want to get the password back at Pojav launcher on github just like this one ![Screenshot_2022-03-18-12-46-22-32](https://user-images.githubusercontent.com/87040006/158939343-39f09d33-040d-482b-9b5c-b97dcf079a26.jpg)
> 
> ### Anything else?
> Yeah i just want to get it back on Pojavlauncher

Piracy moment

**Comment by ghost** [comment]
They aren't talking about piracy. This feature was removed because on March 10, all Mojang accounts were required to switch to Microsoft accounts. Transfer your account to Microsoft, as even if you log in with Mojang it will not work.

**Comment by CriticalRange** [comment]
> They aren't talking about piracy. This feature was removed because on March 10, all Mojang accounts were required to switch to Microsoft accounts. Transfer your account to Microsoft, as even if you log in with Mojang it will not work.

I mean in a way, they want it

**Comment by ghost** [comment]
I don't understand what you are talking about.
