### ISSUE TITLE
The control map

### ISSUE THREAD

**Issue by Evenz3839** [PojavLauncherTeam/PojavLauncher#2925]
### Describe the bug

net.objecthunter.exp4j.tokenizer.UnknownFunctionOrVariableException: Unknown function or variable 'px' at pos 23 in expression '0.0040983604 * 2312 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 - (px(58.0) / 100.0 * ${preferred_scale}) - 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 - (px(58.0) / 100.0 * ${preferred_scale}) - 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4'
	at net.objecthunter.exp4j.tokenizer.Tokenizer.parseFunctionOrVariable(Tokenizer.java:177)
	at net.objecthunter.exp4j.tokenizer.Tokenizer.nextToken(Tokenizer.java:116)
	at net.objecthunter.exp4j.shuntingyard.ShuntingYard.convertToRPN(ShuntingYard.java:46)
	at net.objecthunter.exp4j.ExpressionBuilder.build(ExpressionBuilder.java:188)
	at net.kdt.pojavlaunch.customcontrols.ControlData.calculate(ControlData.java:187)
	at net.kdt.pojavlaunch.customcontrols.ControlData.insertDynamicPos(ControlData.java:166)
	at net.kdt.pojavlaunch.customcontrols.ControlData.update(ControlData.java:182)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:56)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:37)
	at net.kdt.pojavlaunch.CustomControlsActivity.loadControl(CustomControlsActivity.java:199)
	at net.kdt.pojavlaunch.CustomControlsActivity.access$900(CustomControlsActivity.java:21)
	at net.kdt.pojavlaunch.CustomControlsActivity$5.onFileSelected(CustomControlsActivity.java:189)
	at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:144)
	at com.kdt.pickafile.FileListView$1.onItemClick(FileListView.java:76)
	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1295)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3539)
	at android.widget.AbsListView$3.run(AbsListView.java:4642)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### The log file and images/videos

https://user-images.githubusercontent.com/101863253/158963650-e285a377-fe35-4238-973b-c4b7934e9538.mp4

Showcase 

### Steps To Reproduce

```markdown
1 start pojava 
2 tap on settings 
3 tap control map
4 load a control map under 3.3.1.1ver
5 crash
```

### Expected Behavior

Idk what to write 

Uploading Screen_Recording_20220318-172246_PojavLauncher (Minecraft Java Edition for Android).mp4…

### Platform

```markdown
- Device model: samsung a 51
- CPU architecture: arm
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel:20220125
```

### Anything else?

I hope u fix it

**Comment by artdeell** [comment]
You are using an outdated version of the launcher, which lacks features required to work with newer control maps.

**Comment by Mihai61** [comment]
> ### Describe the bug
> net.objecthunter.exp4j.tokenizer.UnknownFunctionOrVariableException: Unknown function or variable 'px' at pos 23 in expression '0.0040983604 * 2312 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 - (px(58.0) / 100.0 * ${preferred_scale}) - 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 - (px(58.0) / 100.0 * ${preferred_scale}) - 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4' at net.objecthunter.exp4j.tokenizer.Tokenizer.parseFunctionOrVariable(Tokenizer.java:177) at net.objecthunter.exp4j.tokenizer.Tokenizer.nextToken(Tokenizer.java:116) at net.objecthunter.exp4j.shuntingyard.ShuntingYard.convertToRPN(ShuntingYard.java:46) at net.objecthunter.exp4j.ExpressionBuilder.build(ExpressionBuilder.java:188) at net.kdt.pojavlaunch.customcontrols.ControlData.calculate(ControlData.java:187) at net.kdt.pojavlaunch.customcontrols.ControlData.insertDynamicPos(ControlData.java:166) at net.kdt.pojavlaunch.customcontrols.ControlData.update(ControlData.java:182) at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:56) at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:37) at net.kdt.pojavlaunch.CustomControlsActivity.loadControl(CustomControlsActivity.java:199) at net.kdt.pojavlaunch.CustomControlsActivity.access$900(CustomControlsActivity.java:21) at net.kdt.pojavlaunch.CustomControlsActivity$5.onFileSelected(CustomControlsActivity.java:189) at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:144) at com.kdt.pickafile.FileListView$1.onItemClick(FileListView.java:76) at android.widget.AdapterView.performItemClick(AdapterView.java:376) at android.widget.AbsListView.performItemClick(AbsListView.java:1295) at android.widget.AbsListView$PerformClick.run(AbsListView.java:3539) at android.widget.AbsListView$3.run(AbsListView.java:4642) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:246) at android.app.ActivityThread.main(ActivityThread.java:8653) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
> 
> ### The log file and images/videos
>  Screen_Recording_20220318-172246_PojavLauncher.Minecraft.Java.Edition.for.Android.mp4 
> Showcase
> 
> ### Steps To Reproduce
> 1 start pojava 
> 2 tap on settings 
> 3 tap control map
> 4 load a control map under 3.3.1.1ver
> 5 crash
> ### Expected Behavior
> Idk what to write
> 
> Uploading Screen_Recording_20220318-172246_PojavLauncher (Minecraft Java Edition for Android).mp4…
> 
> ### Platform
> - Device model: samsung a 51
> - CPU architecture: arm
> - Android version: 11
> - PojavLauncher version: 3.3.1.1_rel:20220125
> ### Anything else?
> I hope u fix it

**Comment by Mihai61** [comment]
> ### Describe the bug
> net.objecthunter.exp4j.tokenizer.UnknownFunctionOrVariableException: Unknown function or variable 'px' at pos 23 in expression '0.0040983604 * 2312 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 - (px(58.0) / 100.0 * ${preferred_scale}) - 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4 - (px(58.0) / 100.0 * ${preferred_scale}) - 4 + (px(58.0) / 100.0 * ${preferred_scale}) + 4' at net.objecthunter.exp4j.tokenizer.Tokenizer.parseFunctionOrVariable(Tokenizer.java:177) at net.objecthunter.exp4j.tokenizer.Tokenizer.nextToken(Tokenizer.java:116) at net.objecthunter.exp4j.shuntingyard.ShuntingYard.convertToRPN(ShuntingYard.java:46) at net.objecthunter.exp4j.ExpressionBuilder.build(ExpressionBuilder.java:188) at net.kdt.pojavlaunch.customcontrols.ControlData.calculate(ControlData.java:187) at net.kdt.pojavlaunch.customcontrols.ControlData.insertDynamicPos(ControlData.java:166) at net.kdt.pojavlaunch.customcontrols.ControlData.update(ControlData.java:182) at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:56) at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:37) at net.kdt.pojavlaunch.CustomControlsActivity.loadControl(CustomControlsActivity.java:199) at net.kdt.pojavlaunch.CustomControlsActivity.access$900(CustomControlsActivity.java:21) at net.kdt.pojavlaunch.CustomControlsActivity$5.onFileSelected(CustomControlsActivity.java:189) at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:144) at com.kdt.pickafile.FileListView$1.onItemClick(FileListView.java:76) at android.widget.AdapterView.performItemClick(AdapterView.java:376) at android.widget.AbsListView.performItemClick(AbsListView.java:1295) at android.widget.AbsListView$PerformClick.run(AbsListView.java:3539) at android.widget.AbsListView$3.run(AbsListView.java:4642) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:246) at android.app.ActivityThread.main(ActivityThread.java:8653) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
> 
> ### The log file and images/videos
>  Screen_Recording_20220318-172246_PojavLauncher.Minecraft.Java.Edition.for.Android.mp4 
> Showcase
> 
> ### Steps To Reproduce
> 1 start pojava 
> 2 tap on settings 
> 3 tap control map
> 4 load a control map under 3.3.1.1ver
> 5 crash
> ### Expected Behavior
> Idk what to write
> 
> Uploading Screen_Recording_20220318-172246_PojavLauncher (Minecraft Java Edition for Android).mp4…
> 
> ### Platform
> - Device model: samsung a 51
> - CPU architecture: arm
> - Android version: 11
> - PojavLauncher version: 3.3.1.1_rel:20220125
> ### Anything else?
> I hope u fix it
