### ISSUE TITLE
1.18 optifine install crash

### ISSUE THREAD

**Issue by Evenz3839** [PojavLauncherTeam/PojavLauncher#2926]
### Describe the bug

I downloaded 1.18 and 1.18.1 optifine install jar on the official page
I downloaded 1.18 and 1.18.1 (vanilla) on pojava and tried to install optifine but crashed

### The log file and images/videos

?

### Steps To Reproduce

```markdown
1 Install 1.18 and 1.18.1 on pojava (vanila)
2 install optifine 1.18 and 1.18.1 install jar
3 goto pojava and hit settings
3.1 hit mod installer (or somthing)
4 select 1.18 optifine jar
5 get the error
```

### Expected Behavior

After selecting the 1.18 optifine install jar
The game crashed with no error code

### Platform

```markdown
- Device model: samsung a51
- CPU architecture: arm
- Android version: 11
- PojavLauncher version: 3.3.1.1
```

### Anything else?

Oh and 1.17 and 1.17.1 
I can't seem to put on resource packs

**Comment by ghost** [comment]
1. Update your launcher to the latest action build.
2. Send the latestlog.txt to help us see what the crash is.

**Comment by OPGsGAMING** [comment]
crashing evertime

**Comment by jorgieee** [comment]
Use the patcher

**Comment by kuzy21** [comment]
Uninstall pojav the install it again

**Comment by BNaise** [comment]
Set the runtime to internal then install

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
