### ISSUE TITLE
Pojavlauncher

### ISSUE THREAD

**Issue by AiKk291** [PojavLauncherTeam/PojavLauncher#2927]
### Is this request related to a bug?

Pojavlauncher updates To play minecraft version, you must have a premium account, offline accounts will no longer exist = trash

**Comment by andr0d1v** [comment]
But what about people who do not have the Internet in other places other than at home?

**Comment by Jamespoxdxdxd** [comment]
yeah thats a pretty bad idea Tlauncher didnt even get sued for having an Offline account But sadly Its thier Decision We cant really nothing to do about it they just dont want to get sued  they made us possible to play Java on Mobile but yeah Removing Offline account and cant play Minecraft versions is a bad idea

**Comment by Jamespoxdxdxd** [comment]
> But what about people who do not have the Internet in other places other than at home?

yeah thats what im wondering and + the broke person too they cant buy Java Account Theres also some kids who cant buy Java account because of thier parents not letting them

**Comment by ghost** [comment]
Playing the game without paying for it is piracy, which is against the law. A feature could be implemented similar to the "Play offline" on the offical launcher. If you cannot afford the game or buy it, consider the fact that it is illegal to pirate the game.

**Comment by ghost** [comment]
"Play offline" would remove the first issue, allowing you to still have your main account whilst playing offline.

**Comment by AiKk291** [comment]
> Nhưng những người không có Internet ở những nơi khác ngoài nhà thì sao?

we should not update new version

**Comment by AiKk291** [comment]
> Nhưng những người không có Internet ở những nơi khác ngoài nhà thì sao?



> But what about people who do not have the Internet in other places other than at home?

We should not update to the new version

**Comment by ghost** [comment]
Offline accounts have not been removed yet, however they will be due to Mojang's EULA. However the new version may have an altered system that will have a play offline feature.

**Comment by khanhduytran0** [comment]
@AiKk291 you must understand the fact that Microsoft will DMCA takedown us anytime if we let people playing the full version for free. As a replacement, demo mode will be added later.

What we’ve experienced with the iOS version:
> @crystall1nedev: i emailed back and a microsoft lawyer basically said remove the offending debs or pay $30,000/go to jail

**Comment by khanhduytran0** [comment]
> Tlauncher didnt even get sued for having an Offline account 

If you check their site, since March 9th, they also stated that
> To run the game, you need a purchased license from the official site minecraft.net
