### ISSUE TITLE
[F-Req] i dont know buf its crashing 

### ISSUE THREAD

**Issue by Kaan1O1** [PojavLauncherTeam/PojavLauncher#2929]
### Is this request related to a bug?

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8306605/latestlog.txt)
im banned from discord server so yea i can type here for now

**Comment by ghost** [comment]
Please verify that you are logged in with an online account. An ongoing issue is forge crashing with offline accounts.

**Comment by ghost** [comment]
Please log in with an offical premium Minecraft account to prevent this issue.
