### ISSUE TITLE
My skin does not appear

### ISSUE THREAD

**Issue by xXFrostXx1** [PojavLauncherTeam/PojavLauncher#293]

**Comment by WesleyVanNeck** [comment]
know issue

**Comment by khanhduytran0** [comment]
Use v3

**Comment by mglovers123** [comment]
Use v3 and install Minecraft version on v3 And open zarchiver / ex file Explorer / or storage on your cellphone and open games / .minecraft / version /Your Minecraft version / delete the meta-inf folder. That's all I know but that's for v3 to v2 I don't know

**Comment by khanhduytran0** [comment]
@xXFrostXx1 reopen if problem re-occur (v3).
