### ISSUE TITLE
[BUG] External mouse Right click not really working too well

### ISSUE THREAD

**Issue by ImNotBrian** [PojavLauncherTeam/PojavLauncher#2930]
### Describe the bug

Im kind of having a hard time playing on the new pojav version because my external mouse right click is kind of buggy. Whenever i open my inventory or settings and press right click, its just closing them and i cant even press escape when i want to get out of the settings in game. When crafting, it does the same too. 

### The log file and images/videos

I have no recordings or screenshots of it.

### Steps To Reproduce

```markdown
There arent any steps to reproduce.
```

### Expected Behavior

I expected to be working fine.

### Platform

```markdown
- Device model: Realme c25
- CPU architecture: jdk64
- Android version: Android 11
- PojavLauncher version: Latest release
```

### Anything else?

I hope this gets fixed.

**Comment by ImNotBrian** [comment]
I also enjoy this pojavlauncher version, even though i turned on the highest settings possible, my fps is still at 80-90 fps (8 chunks) and this pojav version is actually very smooth to play with.

**Comment by khanhduytran0** [comment]
jdk64 is not a valid architecture, why do you use jdk? :eyes:
`Latest release` is not a valid version. There are multiple sources of it.

**Comment by ImNotBrian** [comment]
> 

well i kind of have no idea about tech stuff, but here ill just show you my phone specs. And also the version i use is from here, github, and its the Profile 2: Electric boogaloo one.
![Screenshot_2022-03-19-08-34-01-63_c42fd5307ad0c723935554bc80c21421](https://user-images.githubusercontent.com/88020152/159099805-1003fb0c-283e-44ea-9faf-804bef61c7e1.jpg)

**Comment by Mathias-Boulay** [comment]
probably Fixed on the release candidate build.
