### ISSUE TITLE
Minecraft shows black screen after launching the game

### ISSUE THREAD

**Issue by villagerrr1** [PojavLauncherTeam/PojavLauncher#2931]
### Describe the bug

Minecraft stays at black screen even its done launching itself while using VirGL Renderer. 

### The log file and images/videos

https://user-images.githubusercontent.com/90895958/159105075-887c4a94-6ce3-4177-9f1f-2a7096016be3.mp4

### Steps To Reproduce

```markdown
1.Open PojavLauncher
2.Choose or create a offline account
3.Go to Renderer and choose VirGL
4.Launch any version of Minecraft
```

### Expected Behavior

It will not show a black screen 

### Platform

```markdown
- Device model: Honor 8x 
- CPU architecture: aarch64 
- Android version: 10 
- PojavLauncher version:Crocus-299-f1bd70096-v3_openjdk
```

### Anything else?

I have also the Google play store version installed on my Phone.

**Comment by RevanMardagh** [comment]
Wait a few minutes, it will open after a few minutes

**Comment by Mathias-Boulay** [comment]
virgl cannot really be fixed
