### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Kaiboithe1** [PojavLauncherTeam/PojavLauncher#2932]
### Describe the bug

The version from 1.17-1.18.2 won't work for some reason it just says can't find any compatible java runtime and I don't know why but that's all and I hope you can fix this.

### The log file and images/videos

*

### Steps To Reproduce

```markdown
*
```

### Expected Behavior

*

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

that's all

**Comment by andr0d1v** [comment]
Your stupid? Install java 17

**Comment by Py10lolz** [comment]
> Your stupid? Install java 17

*You're

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
