### ISSUE TITLE
[BUG] Cannot play version 1.18.2

### ISSUE THREAD

**Issue by RevanMardagh** [PojavLauncherTeam/PojavLauncher#2933]
### Describe the bug

When you try to open Minecraft 1.18.2 , it says: 
`Cannot find java SE Runtime`

### The log file and images/videos

![IMG_20220319_105111](https://user-images.githubusercontent.com/58358191/159110959-61d3cae1-1b55-48e6-9120-978f6bf7dff4.jpg)

### Steps To Reproduce

```markdown
1 Start pojavlauncher
2. Launch version 1.18.2
```

### Expected Behavior
Launch minecraft 1.18.2

### Platform

```markdown
- Device model: Redmi 9t
- CPU architecture: 
- Android version: android 10
- PojavLauncher version:
```

### Anything else?

In my opinion, you should add an option to runtime manager for Java 16.

**Comment by ajit56** [comment]
Use aarch 64 architecture runtime

**Comment by RevanMardagh** [comment]
How do i do that?

**Comment by shadsaifi2233** [comment]
not work

**Comment by ghost** [comment]
Read the info on how to load 1.17+.

**Comment by kuzy21** [comment]
Download it here : https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz

**Comment by RevanMardagh** [comment]
It crashes when i open the game with that

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
