### ISSUE TITLE
[BUG] crashes when I load a world on 1.12.2 forge

### ISSUE THREAD

**Issue by DoubleShotgun** [PojavLauncherTeam/PojavLauncher#2934]
### Describe the bug

Crashes when I load up ourworld when I uses Forge with mods or no mods

### The log file and images/videos

[crash-2022-03-19_08.49.00-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8308865/crash-2022-03-19_08.49.00-client.txt)

### Steps To Reproduce

```markdown
1. Start up 1.12 forge
2. Load up a single player world
```

### Expected Behavior

Crash

### Platform

```markdown
- Device model: Oppo CPH 1920
- CPU architecture: aarch64
- Android version: 8.1.0
- PojavLauncher version: Latest Version
```

**Comment by GaucovyAero** [comment]
Pirate detected. Buy Minecraft: Java Edition first.

**Comment by DoubleShotgun** [comment]
> Pirate detected. Buy Minecraft: Java Edition first.

?
I don't think so because if I simply play on vanilla, it was completely fine

**Comment by kedrick021** [comment]
Turn off your data or wifi and try again

**Comment by khanhduytran0** [comment]
> ? I don't think so because if I simply play on vanilla, it was completely fine

If you don’t know, this error also applies to 1.18.2 (see #2848). Mojang changed their authentication system to prevent people from pirating. Buy the game, otherwise you won’t get any support.

**Comment by Tiger56c** [comment]
Hey if the owner of pojavlauncher see this can you add the forge and optifine version all of them because I have no more space of my phone I can't download 1 single optifine or forge please
