### ISSUE TITLE
[BUG] <Fabric-Loader-1.18.1 cannot work>

### ISSUE THREAD

**Issue by ProjectOmega666** [PojavLauncherTeam/PojavLauncher#2935]
### Describe the bug

Well,pojav worked when running 1.18.1 original game,but when I tried to run Fabric-Loader-1.18.1 version, it showed Application Exited with code 1.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8308936/latestlog.txt)

### Steps To Reproduce

```markdown
1.Enter Pojav and use INSTALL .JAR below
2.Find fabric-installer-0.10.2.jar(already checked not broken)and install fabric-loader
3.Return to Pojav and switch to fabric-loader-1.18.1 version and run
4.While using Java8,nothing is displayed except pojav buttons;
while using Java17,Application Exited with code 1.Changing the renderer does not work.
```

### Expected Behavior

fabric-loader-1.18.1 version could work so that mods can be used

### Platform

```markdown
- Device model: Mi 10 8/128G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: crocus-411-d1000c373-
```

### Anything else?

After pojav crashed, I found something in 
/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/fabric-loader-0.13.3-1.18.1/
![IMG_20220319_180718](https://user-images.githubusercontent.com/90470484/159116879-a7029244-014e-42f9-80b7-bdf34e720a76.jpg)
In this folder,fabric-loader-0.13.3-1.18.1.jar was broken,and no matter how I changed the network condition to install the fabric-loader(though I do not know whether loader needs to be downloaded or not),the jar was broken still.
So I was confused because I do not know where is wrong.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
