### ISSUE TITLE
[BUG] Can't Install Fabric On Latest Build Of PojavLauncher

### ISSUE THREAD

**Issue by 1493028** [PojavLauncherTeam/PojavLauncher#2936]
### Describe the bug

When i try to install fabric 1.16.4 it cannot show the install screen and it crash with code 1

### The log file and images/videos

Can't install Fabric 1.16.4

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Select installer mod and select the fabric installer
3. Crash
```

### Expected Behavior

Nope it crashes it self

### Platform

```markdown
- Device model: Vivo y50
- CPU architecture: Aarch64/Arm64
- Android version: 10
- PojavLauncher version: latest Github Build
```

### Anything else?

Nope

**Comment by ghost** [comment]
Please send us the latestlog.txt to help us debug the issue.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
