### ISSUE TITLE
[BUG] `Options.txt` is resetting (again)

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2938]
### Describe the bug

Every time I run 1.18.2 the game never loads and my options.txt file keeps removing my `assets-v0_1.18+.zip` fix. IDK WHY THIS IS HAPPENING AGAIN!!!

### The log file and images/videos

[my mods.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8309704/my.mods.zip)
[options.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8309705/options.txt)
[options_i_want.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8309707/options.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8309711/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start ProjavLancher
2. Sign in to an account
3. Get Fabric Loader
4. Go back to ProjavLancher and get click options
5. Now click the "Launch a Mod Installer" button and select the Fabric Launcher
6. Wait, then in the menu, select 1.18 client and finish downloading
7-1. Download the fabric API and move it into the mods folder
7-2. Afterwards, Get modmenu-3.1.0 and sodium-fabric-mc1.18.2-0.4.1+build.15 and add them to your mods directory
8. Once done, follow the instructions on how to get Minecraft 1.18+ to work
9. Get stuck on the resource pack part
```

### Expected Behavior

I expect my options.txt to stick and for my game to stop repeatedly loading

### Platform

```markdown
- Device model: R96-14268.67.0
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I can't update my app rn so you just have to deal with it 😎 

This is not the first time this has happened to me, #2829 (Yes, I have already tried the solution to that problem)

**Comment by Mathias-Boulay** [comment]
> I can't update my app rn so you just have to deal with it

How about we close the issue instead 😐

**Comment by Errorbot1122** [comment]
> How about we close the issue instead

:((((((((((((

**Comment by Errorbot1122** [comment]
Well can you at least try as `Chrome OS` made an update so that you can't just install random `.apk`s anymore so i cant update 😞

**Comment by Errorbot1122** [comment]
I found out the problem, it was Mod Menu. IDK what but for me, `modmenu-1.3.0` is broken
