### ISSUE TITLE
[F-Req] Minecraft on SD Card 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2939]
### Describe the request.

Hello
I  want to save minecraft data to micro SD card

:)

### Anything else?

I have a 8GB memory in my device and I can't install minecraft :(

**Comment by GaucovyAero** [comment]
You can try clearing cache and data from applications (mainly Chrome and YouTube). I can run PojavLauncher totally fine on a device with 4GB of storage (although that device is running Android 5.1).

**Comment by ghost** [comment]
ok
thanks
