### ISSUE TITLE
Error 403 

### ISSUE THREAD

**Issue by Danielpro55-pro** [PojavLauncherTeam/PojavLauncher#2940]
### Describe the bug

Me arto de ese problema porque quiero que mi cuenta este conectada por favor soluciolenlo

### The log file and images/videos

![Screenshot_20220319-213118](https://user-images.githubusercontent.com/101959433/159146844-545e2932-a1c8-482a-b248-4dfd0394311e.png)

### Steps To Reproduce

```markdown
Entra a pojav launcher crea una cuenta no eligas ninguna de las opciones decrear una cuenta sin conexión ni mantener la sesión iniciada selecciona iniciar sesión y te aparece
```

### Expected Behavior

Espere que me dejara iniciar sesión😔

### Platform

```markdown
- Device model:8 pro 8/128G 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version:1.12
.2
```

### Anything else?

Es en la versión 1.12.2 del Minecraft Java editon.

**Comment by Evenz3839** [comment]
Invalid id or password 
Read

**Comment by khanhduytran0** [comment]
Mojang account is no longer supported. Please migrate your account to Microsoft.
