### ISSUE TITLE
[BUG] shift bug on crafting/inv 

### ISSUE THREAD

**Issue by ZaphHG** [PojavLauncherTeam/PojavLauncher#2944]
### Describe the bug

the shift button is not working as it should, it does not work while I click the left mouse button, and sometimes it bugs and I can not use the inventory without having to use the shift, I hope you understood, this is a little confusing

### The log file and images/videos

https://user-images.githubusercontent.com/101457774/159166800-616726ef-1b0f-4c7c-9052-5ea4ee49614b.mp4

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. enter into a world
3. try using the shift button to compress your mouse movements while crafting or moving items etc
```

### Expected Behavior

the movements are really compressed so I don't have to click one by one

### Platform

```markdown
- Device model: Tab S6 Lite/64G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: actions latest version, Profiles 2: Electric Boogaloo
```

**Comment by GaucovyAero** [comment]
Weird. It's working fine on my phone.

**Comment by ZaphHG** [comment]
> Weird. It's working fine on my phone.

whats your pojavlauncher version?
