### ISSUE TITLE
[BUG] Recourse packs not showing up

### ISSUE THREAD

**Issue by Funtimey** [PojavLauncherTeam/PojavLauncher#2945]
### Describe the bug

I play on 1.8.9 and wanted a texture pack, I downloaded one and put it on the recoursepacks file, I used ZArchiver, and the pack didn't show up, Please fix
Thank you! 

### The log file and images/videos

![IMG_20220320_224750](https://user-images.githubusercontent.com/101968674/159168512-9e6c678f-6d25-4388-8bad-6f0deb6a1c42.jpg)
![Screenshot_2022-03-20-22-51-50-75](https://user-images.githubusercontent.com/101968674/159168517-ec24238d-16a8-4db9-b969-8bd42921671f.png)

### Steps To Reproduce

```markdown
1. Place pack file in recoursepack files from the PojavLauncher app folder
2. Start up Pojavlauncher and start playing
3. Recourse pack does not show up
```

### Expected Behavior

Expecting for the pack to appear

### Platform

```markdown
- Device model:.CPH1717
- CPU architecture: AArch64 Processor rev 2
- Android version: 7.1.1
- PojavLauncher version: 3.3.1.1
```

### Anything else?

**Nothing**

**Comment by GaucovyAero** [comment]
Very old PojavLauncher build. Update to the latest one in the Actions tab here on GitHub.

**Comment by Funtimey** [comment]
is it the "Crocus" gplay release?  It only shows the Source code, how do i update? And the latest release one shows 3.3.1.1

**Comment by GaucovyAero** [comment]
You have clicked on Releases, not on Actions
