### ISSUE TITLE
FIXED

### ISSUE THREAD

**Issue by PugBroKid** [PojavLauncherTeam/PojavLauncher#2946]
### Describe the bug

I hit a entity and it makes every object solid

### The log file and images/videos

https://user-images.githubusercontent.com/95888812/159180070-9a7febf4-078b-48b3-8b63-36ef5c233ecf.MP4

### Steps To Reproduce

```markdown
1. Start PojavLauncher And Login (Offline or online)
2. Start 1.8.8 (lowest i know) or any update before 1.15
3. Launch a multiplayer or singleplayer
4. Join server or world 
5. interact with mob, or player
6. Look at the worst glitch from old versions
```

### Expected Behavior

I expected the textures to stay like 1.15 and not broken

### Platform

```markdown
- Device model: Chromebook 3100
- CPU architecture: x86_64
- Android version: 9
- PojavLauncher version: Newest for android
```

### Anything else?

https://user-images.githubusercontent.com/95888812/159180070-9a7febf4-078b-48b3-8b63-36ef5c233ecf.MP4

**Comment by PugBroKid** [comment]
so sorry for lag i didnt know it was so laggy until i watched it after

**Comment by PugBroKid** [comment]
i am using gl4es 1.1.5 OpenGL ES 3 No 1.17 support

**Comment by GaucovyAero** [comment]
Switch to gl4es 1.1.4 if you don't want buggy textures.

**Comment by PugBroKid** [comment]
fixed

**Comment by PugBroKid** [comment]
Aerolome Thanks how do you close it?

**Comment by GaucovyAero** [comment]
I'm pretty sure I can't close it. Click on [close issue](https://stackoverflow.com/questions/34010565/how-do-i-close-a-github-issue-without-making-a-commit) down at the bottom in the new message window.
