### ISSUE TITLE
[BUG] not able to use versions after 1.16.5

### ISSUE THREAD

**Issue by Firestar9990** [PojavLauncherTeam/PojavLauncher#2947]
### Describe the bug

any version later than 1.16.5 doesn't work when I press play. this message shows up:

![image](https://user-images.githubusercontent.com/102011753/159208850-6a90fba5-f9ae-4af7-8210-ade62f4c9c0b.png)

I'm fairly certain this is a bug, but if it isn't, does anyone know how to fix it?

### The log file and images/videos

![image](https://user-images.githubusercontent.com/102011753/159208917-a3ed8103-c976-43ed-a000-9fa43a5990d5.png)

### Steps To Reproduce

```markdown
1. turn the version to anything past 1.16.5
2. press play
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: Acer Chromebook 315
- CPU architecture: the sticker's a bit worn, but it's blue and silvery 
- Android version: I'm not sure
- PojavLauncher version: the latest one i'm pretty sure
```

**Comment by Firestar9990** [comment]
wait, I just wanted to add this in case it helps: when I go to the development console, this message appears before the error shows up
![image](https://user-images.githubusercontent.com/102011753/159209213-10991320-19d2-42ff-8a0b-f41c3928cbe1.png)

**Comment by GaucovyAero** [comment]
Since you didn't join the PojavLauncher discord server, you didn't figure it out yet. Here's how: https://docs.google.com/document/d/18QJUfh-WANGbNI3cZyY3FK55MzqnH2KIAaZzxF1NrXE/edit?usp=sharing

**Comment by Firestar9990** [comment]
thanks

**Comment by Diacius** [comment]
install the newer jre. https://pojavlauncherteam.github.io/updates/117.html#platform-specific-instruction

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.

**Comment by Cadynse** [comment]
Listen here you toe-eyed cabbage, i wasn't born into this world so your large body could choke out low level insults at me. I hope you stub your toe in the dark and have to crawl around your bedroom at 3:47 am in horrific pain after going to the kitchen for a midnight snack of cheese and crackers you absolute gormless minger

**Comment by Firestar9990** [comment]
sorry

**Comment by Diacius** [comment]
what the hell happened here?!
