### ISSUE TITLE
Menu servers/worlds

### ISSUE THREAD

**Issue by xXFrostXx1** [PojavLauncherTeam/PojavLauncher#295]
I can not move the menu except via the keyboard

**Comment by khanhduytran0** [comment]
Which menu?

**Comment by artdeell** [comment]
> I can not move the menu except via the keyboard

On 1.8 you can move the menu using mouse while holding SEC

**Comment by xXFrostXx1** [comment]
> Which menu?

List* servers/worlds

**Comment by xXFrostXx1** [comment]
> > Which menu?
> 
> List* servers

**Comment by xXFrostXx1** [comment]
> > I can not move the menu except via the keyboard
> 
> On 1.8 you can move the menu using mouse while holding SEC

🌚I want use the touch

**Comment by xXFrostXx1** [comment]
> > I can not move the menu except via the keyboard
> 
> On 1.8 you can move the menu using mouse while holding SEC

1- I want use touch🌚
2- 1.8 is very Old update And some servers do not support 1.8 but 1.16.1/1.15.2

**Comment by khanhduytran0** [comment]
1. Then both mouse button is trigger on touch same time?
2. Don't you know this launcher can run to 1.11.2 or 1.12.2? Getting 1.16 to work is not an easy work.

**Comment by xXFrostXx1** [comment]
No
![Screenshot_20200903_163538_net kdt pojavlaunch](https://user-images.githubusercontent.com/48761453/92122017-9fb56800-ee03-11ea-88b4-f2a8fbea754e.jpg)

I touched these places and did not move👇🏻
![IMG-20200903-WA0002](https://user-images.githubusercontent.com/48761453/92123534-6f6ec900-ee05-11ea-8537-0210916e210d.jpg)

2- oh sorry I did not know
And thank you <3

**Comment by khanhduytran0** [comment]
So can this issue be closed?

**Comment by xXFrostXx1** [comment]
🌚I don't know I may collect the issues here🌚
