### ISSUE TITLE
When getting into the privite app folder no password section  and no option to log in as an offline account you can only log in with offline

### ISSUE THREAD

**Issue by Gffgyhgg** [PojavLauncherTeam/PojavLauncher#2951]
### Describe the bug

Hyfjyfhgghgghhvb

### The log file and images/videos

Ghggggggggggggg

### Steps To Reproduce

```markdown
Hgggggggggg
```

### Expected Behavior

Hhshdhdhhd

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Ygggggggggggggg

**Comment by NekoIceCream** [comment]
Offline mode is removed

Pirate is bad
Buy the game or u cant play the game

GO CRY ABOUT IT

**Comment by Gffgyhgg** [comment]
I said i cant log in with my online account bc there is no password section to type my password in
