### ISSUE TITLE
In the private app folder i cant log in with my online account bc there is no password section to type my password in and if i log in with an offline account icant get into the game

### ISSUE THREAD

**Issue by Gffgyhgg** [PojavLauncherTeam/PojavLauncher#2952]
### Describe the bug

Where to put my password there is no password section

### The log file and images/videos

Uuuuhhvvhhggty

### Steps To Reproduce

```markdown
Gygghhggghggh
```

### Expected Behavior

Fttjugghhghgggy

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Ghhuughyghuh

**Comment by khanhduytran0** [comment]
Duplicated.
