### ISSUE TITLE
Where is the password section in depugnoruntime private app folder

### ISSUE THREAD

**Issue by Gffgyhgg** [PojavLauncherTeam/PojavLauncher#2953]
### Describe the bug

No password section

### The log file and images/videos

![Screenshot_2022-03-21-14-32-32-820_net kdt pojavlaunch debug](https://user-
images.githubusercontent.com/101998515/159261962-a001a10d-c096-48e1-ae7f-f66a91bd0ed7.jpg)

### Steps To Reproduce

```markdown
Put a password section
```

### Expected Behavior

Gyhughugughhh

### Platform

```markdown
- Device model:poco x3 nfc
- CPU architecture: 64_arm
- Android version: 13
- PojavLauncher version: the private app folder
```

### Anything else?

Hh

**Comment by st0rmc4non** [comment]
> Password Section

What?

> private app folder

Are you on root? Or just confused where pojav stores versions?
> In Android 9, PojavLauncher stores Minecraft data in `/storage/emulated/0/games/PojavLauncher`
While in Android 10 and aboves, it stores in 
`storage/emulated/0/android/data/net.kdt.pojavlaunch(.debug if you're using action builds)/

**Comment by Gffgyhgg** [comment]
Where to type my password

**Comment by Gffgyhgg** [comment]
I bought but where to put my password where

**Comment by st0rmc4non** [comment]
PojavLauncher doesn't use any sort of password. Unless you want to log in, of course.

**Comment by st0rmc4non** [comment]
> I bought but where to put my password where

Tap the button "Microsoft Login"

**Comment by Gffgyhgg** [comment]
What about 23 dollars i used i have to buy another one

**Comment by st0rmc4non** [comment]
Migrate.

**Comment by Gffgyhgg** [comment]
Ok il try

**Comment by khanhduytran0** [comment]
How do you manage your duplicated issues @Gffgyhgg
