### ISSUE TITLE
[BUG] 1.13 mouse clicked event handler crash

### ISSUE THREAD

**Issue by An-undertale-fan** [PojavLauncherTeam/PojavLauncher#2954]
### Describe the bug

App closed

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8315552/latestlog.txt)

### Steps To Reproduce

```markdown
Start PojavLauncher in 1.13
Opened options
Opened videos options
Got a screen saying saving world then the app crashed
```

### Expected Behavior

To open video options 

### Platform

```markdown
- Device model:oppo 
- CPU architecture: i don't know 
- Android version: 6.1
- PojavLauncher version: latest version
```

**Comment by 1493028** [comment]
Same it happened to me too

**Comment by Aerolome** [comment]
Known issue. Happens on 1.14 snapshots too.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
