### ISSUE TITLE
[BUG] <Unable to enter the game due to a bug>

### ISSUE THREAD

**Issue by Chris090709** [PojavLauncherTeam/PojavLauncher#2955]
### Describe the bug

when I enter the game, I cannot create an online account, because there is a gmail field, but there is no password field, so I cannot create an account, please help or fix the error

### The log file and images/videos

![Screenshot_2022-03-20-22-16-52-92_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/100999455/159323709-c4f8b13c-0173-4c84-93b0-f11d63537465.jpg)
![Screenshot_2022-03-20-21-39-40-27_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/100999455/159323832-ab48d787-7137-499a-b4f6-bbe67bfe1be7.jpg)

### Steps To Reproduce

```markdown
1 launch pojav launcher  , you don't need to do anything else, I just can't create an online acc.
```

### Expected Behavior

I expected both fields, but I thought it was because of the update, I can’t fix the ban in any way, I tried everything.

### Platform

```markdown
- Device model: Oppo Reno 4 lite 8/128
- CPU architecture:arm64-v8a 
- Android version: 11
- PojavLauncher version: all beta versions
```

### Anything else?

nothing more to say

**Comment by ghost** [comment]
Accounts are now Microsoft only. Transfer your Mojang account to Microsoft to sign in with that.

**Comment by Chris090709** [comment]
> Учетные записи теперь только Microsoft. Перенесите свою учетную запись Mojang в Microsoft, чтобы войти с ней.

Oh thanks
