### ISSUE TITLE
Auto close pojavlauncher

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#2957]
### Describe the bug

Auto close when minimize the pojavlauncher or start the recording video like alt tab not support anymore

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.minecraft menu
3.minimize or click middle bottom
4.auto close the pojavlauncher
```

### Expected Behavior

i can't minimize anymore

### Platform

```markdown
- Device model: umidigi bison
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest version in khuntra update
```

### Anything else?

Fix it I can't recording if auto close when use another apps

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
