### ISSUE TITLE
[BUG] Skin head in the main screen

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2961]
### Describe the bug

When logging into an online account, it usually shows the head of your skin next to your nickname, but it doesn't show up for me! How to fix?

### The log file and images/videos

![Screenshot_2022-03-23-06-16-07-145_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87223939/159616965-c8b6d034-509e-48ee-86bc-5e6683ab23ba.jpg)

### Steps To Reproduce

```markdown
1. Launch PojavLauncher
2. Login to your minecraft account
3. Watch bug
```

### Expected Behavior

I expect my skin's head to be displayed next to my nickname

### Platform

```markdown
- Device model: Redmi 10 4/128
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest debug(from github actions)
```

**Comment by WesleyVanNeck** [comment]
Restart the app then it's fixed

**Comment by andr0d1v** [comment]
Did not help

**Comment by WesleyVanNeck** [comment]
> Did not help

Then your using a offline account

**Comment by andr0d1v** [comment]
Read carefully! It says that I use an online account.

**Comment by Mathias-Boulay** [comment]
did you try the "remember me" option ?

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
