### ISSUE TITLE
[BUG] <1.18.1 not working>

### ISSUE THREAD

**Issue by Andrey1008** [PojavLauncherTeam/PojavLauncher#2962]
### Describe the bug

Cant launch 1.18.1

### The log file and images/videos

[crash-2022-03-23_04.32.44-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8329725/crash-2022-03-23_04.32.44-client.txt)

### Steps To Reproduce

```markdown
1. Launch 1.18.1
```

### Expected Behavior

I expect the game to launches

### Platform

```markdown
- Device model: redmi 9c
- CPU architecture: arm
- Android version: 10
- PojavLauncher version: latest on google play
```

**Comment by Andrey1008** [comment]
CPU architecture: arm*

**Comment by kuzy21** [comment]
Did you follow the page for 1.17+ support, if you didn't then see it here: https://pojavlauncherteam.github.io/updates/117.html

**Comment by Andrey1008** [comment]
> 

Yes, 1.17.1 working

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
