### ISSUE TITLE
Forge 1.16.5 crash

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#2967]
### Describe the bug

Crashed with mods and without mods 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8339446/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher from play store
2.install forge
3.Crashed
```

### Expected Behavior

I expect Minecraft launch 

### Platform

```markdown
- Device model: samsung galaxy m31
- CPU architecture: aarch 64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by ghost** [comment]
Try running the forge installer again and install the latest action build.

**Comment by ajit56** [comment]
Ok
