### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by BeJohnsonSentosa12** [PojavLauncherTeam/PojavLauncher#2968]
### Describe the bug

I played Pojav launcher for 2-6 minutes then the app crashes I tried again and it just crashes my Pojav launcher version from github

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1. start the Pojav launcher 
2. Aplication crash
```

### Expected Behavior

Apk crash

### Platform

```markdown
- Device model: Vivo y50
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest github
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
Uhm, any logs, which version of minecraft?

**Comment by ghost** [comment]
Please provide the latestlog.txt so we can debug the issue.

**Comment by kuzy21** [comment]
What version of minecraft are you running?

**Comment by Mathias-Boulay** [comment]
probably Fixed on the release candidate build.
