### ISSUE TITLE
Minecraft 22w12a Not Working [BUG]

### ISSUE THREAD

**Issue by Illia24** [PojavLauncherTeam/PojavLauncher#2969]
### Is this request related to a bug?

Uh

### Describe the request.

Im launching 22w12a WITH RECOURSE PACK FORMAT 9, and crashing rendering overlay.

### Anything else?

Stop mojang adding someone else to graphic.

**Comment by WesleyVanNeck** [comment]
close this this aint a enhencemnt

**Comment by Illia24** [comment]
i can't write bug type only enchancement
