### ISSUE TITLE
Bug while loading 1.18.2

### ISSUE THREAD

**Issue by StaffMystic** [PojavLauncherTeam/PojavLauncher#2970]
### Describe the bug

I was loading V1.18.2 and it said something about the JavaRuntime.I don't know if it is my storage or Wifi but its a bug.I had the JavaRuntime 17 with render Zink. 

![Screenshot_20220324-163136](https://user-images.githubusercontent.com/102326963/160006613-a1f25e1a-ce8f-4387-88a2-33c56e84f655.png)

### The log file and images/videos

I watched everyone go into minecraft JE 1.18.2 and i was like,"Ok this is legit".then i tryed and got an unexpecting Error after i just watched proof that the Java Runtime was real.

### Steps To Reproduce

```markdown
Load up PojavLauncher,Choose my account,Add Javaruntime 17,choose Zink renderer,Load Version 1.18.2,Unexpected Error happend.
```

### Expected Behavior

Play 1.18.2 Minecraft Java edition.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

I need help.

**Comment by kuzy21** [comment]
It's because you are using 64 aarch and you Device doesn't support it use this java runtime instead https://www.mediafire.com/file/v0xcufgzwgga0jy/jre17-arm-20210914-termux.tar.xz/file

**Comment by StaffMystic** [comment]
Ok thank you

**Comment by StaffMystic** [comment]
> It's because you are using 64 aarch and you Device doesn't support it use this java runtime instead https://www.mediafire.com/file/v0xcufgzwgga0jy/jre17-arm-20210914-termux.tar.xz/file

Thank you

**Comment by kuzy21** [comment]
Ur welcome :)

**Comment by bigmann123** [comment]
I have this problem loading up 1.18.2 whenever it load it crash and say game existed.please help

**Comment by bigmann123** [comment]
I have this problem loading up 1.18.2 whenever it load it crash and say game existed.please help

**Comment by kuzy21** [comment]
What version of pojav r u running?

**Comment by ghost** [comment]
I Am aarch-64 But It Dosent Work I Tryed aarch-32 runtime still
