### ISSUE TITLE
[BUG] <22w12a not working>

### ISSUE THREAD

**Issue by Illia24** [PojavLauncherTeam/PojavLauncher#2971]
### Describe the bug

Exit with code -1.

### The log file and images/videos

The 22w12a not working

### Steps To Reproduce

```markdown
1. Open app
2. Open minecraft
3. Exit with code -1
```

### Expected Behavior

I think, not exit with code 1.

### Platform

```markdown
- Device model: vivo y31
- CPU architecture: aarch 64
- Android version: 12
- PojavLauncher version: openjdk-crocus
```

### Anything else?

The bug with code -1.

**Comment by ghost** [comment]
[assets-v0.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8346681/assets-v0.zip)

Try this patch. It should work fine.

**Comment by Illia24** [comment]
Hmmm ok

пт, 25 мар. 2022 г., 03:34 AndrewMC12 ***@***.***>:

**Comment by Illia24** [comment]
Omg thanks!
