### ISSUE TITLE
I cannot login an online account it shows error 403 [BUG] <Short description>

### ISSUE THREAD

**Issue by apilada123123** [PojavLauncherTeam/PojavLauncher#2974]
### Describe the bug

I cannot login an online account it shows code 403

### The log file and images/videos

![Screenshot_2022-03-25-19-40-06-00](https://user-images.githubusercontent.com/102361690/160114448-d4d1f2e5-7c81-4d4a-b272-a319e712fe67.png)

### Steps To Reproduce

```markdown
1.a cant login my account
```

### Expected Behavior

i cant play the game because of the bug

### Platform

```markdown
- Device model:oppo 
- CPU architecture: 107
- Android version:7 
- PojavLauncher version: new version
```

### Anything else?

plss fix this bug

**Comment by kuzy21** [comment]
What account how you using, if its bedrock it won't work also all monjang account have migrated to Microsoft account

**Comment by Mathias-Boulay** [comment]
mojang accounts have to be migrated, consult the minecraft website
