### ISSUE TITLE
[BUG] <frabric>

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#2976]
### Describe the bug

With any mod it crashes

### The log file and images/videos

Cant

### Steps To Reproduce

```markdown
Don't use it
```

### Expected Behavior

To run with the mod

### Platform

```markdown
- Device model: s20 fe
- CPU architecture: 64
- Android version: 12
- PojavLauncher version: beta
```

### Anything else?

Fix pls

**Comment by khanhduytran0** [comment]
It looks like you didn’t buy the game. Also, where’s latestlog.txt?

**Comment by kuzy21** [comment]
I bought the game and here is log:
--------- beggining with launcher debug
Info: Launcher version: crocus-326-b85dd1620-profiles-2-electric-boogaloo
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.1
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: POJAV_NATIVEDIR=/data/app/~~sU8U828hr9yudGY-Xs7XnA==/net.kdt.pojavlaunch.debug-KPW_UO1oq3WVrj_ZWB6JIw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: LIBGL_SHRINK=0
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~sU8U828hr9yudGY-Xs7XnA==/net.kdt.pojavlaunch.debug-KPW_UO1oq3WVrj_ZWB6JIw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2_5
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Dec 19 2021 02:56:01
Using GLES 2.0 backend
Shaderconv enabled
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Max Color Attachments: 1 / Draw buffers: 1
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main

I/jrelog  (16057): dlopen libgl4es_115.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success

I/jrelog  (16057): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (16057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (16057): dlopen /data/app/~~sU8U828hr9yudGY-Xs7XnA==/net.kdt.pojavlaunch.debug-KPW_UO1oq3WVrj_ZWB6JIw==/lib/arm64/libopenal.so success

I/jrelog  (16057): Done processing args

I/jrelog  (16057): Found JLI lib
I/jrelog  (16057): Calling JLI_Launch

[21:35:48] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
  <log4j:Event logger="FabricLoader/GameProvider" timestamp="1648330549540" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading Minecraft 1.18.1 with Fabric Loader 0.13.3]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/Resolution" timestamp="1648330549877" level="WARN" thread="main">
    <log4j:Message><![CDATA[Mod resolution failed]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/Resolution" timestamp="1648330549877" level="INFO" thread="main">
    <log4j:Message><![CDATA[Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED fabric 0.48.0+1.18.2 {depends minecraft @ [~1.18.2-alpha.22.5.a]}, ROOT_FORCELOAD_SINGLE fabric 0.48.0+1.18.2]]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/Resolution" timestamp="1648330549878" level="INFO" thread="main">
    <log4j:Message><![CDATA[Reason: [HARD_DEP fabric 0.48.0+1.18.2 {depends minecraft @ [~1.18.2-alpha.22.5.a]}]]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/Resolution" timestamp="1648330549879" level="INFO" thread="main">
    <log4j:Message><![CDATA[Fix: add [], remove [], replace [[minecraft 1.18.1] -> add:minecraft 1.18.2-alpha.22.5.a ([[1.18.2-alpha.22.5.a,1.19-)])]]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader" timestamp="1648330549896" level="ERROR" thread="main">
    <log4j:Message><![CDATA[Incompatible mod set!]]></log4j:Message>
    <log4j:Throwable><![CDATA[net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.18.1 with any version between 1.18.2-alpha.22.5.a (inclusive) and 1.19- (exclusive).
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) 0.48.0+1.18.2 requires any version between 1.18.2-alpha.22.5.a (inclusive) and 1.19- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
]]></log4j:Throwable>
  </log4j:Event>
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7704e33354)
process killed with signal 6 code 0xffffffff addr 0x2a1100003eb9
