### ISSUE TITLE
[F-Req] why I can't play with offline acc? Plss fix this

### ISSUE THREAD

**Issue by Gabbyph12** [PojavLauncherTeam/PojavLauncher#2977]
### Describe the request.

Why you removed the "Log in as offline account"

**Comment by khanhduytran0** [comment]
Offline account (aka. allow playing the full game for free) is removed to make sure that it won’t send us to any legal issues.

**Comment by Gabbyph12** [comment]
I thought Pojav Launcher is created for android players who don't have
money and plss don't remove the offline acc support version on play store

**Comment by offbeat-stuff** [comment]
they need legal security

**Comment by Gabbyph12** [comment]
What do you mean? Plss make it for us I have no money plsss
