### ISSUE TITLE
[F-Req] Add option to choose Minecraft Directory (REPOST)

### ISSUE THREAD

**Issue by DovydasTEDS** [PojavLauncherTeam/PojavLauncher#2978]
### Is this request related to a bug?

Nope, only that mods from different versions/loaders are launched accidentally.

### Describe the request.

When creating a profile, I would like the option to choose the location of my .minecraft directory for each profile. This is to be able to have different mods for different profiles / versions / loaders. The default Minecraft Launcher has this option already, with launchers like MultiMC making it an extremely greater experiance.

### Anything else?

I would be very happy if this feature was added, so would most PojavLauncher users.

**Comment by andr0d1v** [comment]
I completely agree. I need this

**Comment by DovydasTEDS** [comment]
We all need this feature. Hope they add it soon.

**Comment by offbeat-stuff** [comment]
You can edit the launcher profiles manually

**Comment by DovydasTEDS** [comment]
> You can edit the launcher profiles manually

Is it possible to change the game directory that way?

**Comment by DovydasTEDS** [comment]
Just edited launcher_profiles.json and gave gameDir a value. Then when I opened Pojav, it crashed after logging in.

**Comment by GaucovyAero** [comment]
> Just edited launcher_profiles.json and gave gameDir a value. Then when I opened Pojav, it crashed after logging in.

I need to verify if the issue also occurs on my phone. It's a bummer if it did.

**Comment by WesleyVanNeck** [comment]
Stop reposting issues

**Comment by WesleyVanNeck** [comment]
> We all need this feature. Hope they add it soon.

It's in it already with profiles

**Comment by DovydasTEDS** [comment]
> > We all need this feature. Hope they add it soon.
> 
> It's in it already with profiles

Can you change the directory for each profile? No.

**Comment by DovydasTEDS** [comment]
That is what we've been asking for, and I apologise for the reposts.

**Comment by andr0d1v** [comment]
![Screenshot_2022-04-13-05-12-48-416_com android chrome](https://user-images.githubusercontent.com/87223939/163086142-456495bc-c1d7-42a1-b499-625d7e34e312.jpg)
GUYS. THIS ADDED TO POJAV LAUNCHER

**Comment by DovydasTEDS** [comment]
Thank you so much Pojav devs!
