### ISSUE TITLE
[F-Req] being able to switch account for microsoft account

### ISSUE THREAD

**Issue by condone** [PojavLauncherTeam/PojavLauncher#2979]
### Is this request related to a bug?

_No_

### Describe the request.

Self-explantory enough, Basically a feature that let you switch account for microsoft account. Currently you can only do that to mojang accounts and not microsoft accounts. (only 1 microsoft account can be logged in)

### Anything else?

I have to clear app's data which is very irritating process in order to use my other accounts.

**Comment by khanhduytran0** [comment]
This is already fixed in dev build. Please update in [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

**Comment by condone** [comment]
Alright, I see. Thanks.
