### ISSUE TITLE
[F-Req] Return to the latest builds render vulkan (zink) 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2981]
### Is this request related to a bug?

VirGl renderer does not cope with its tasks: it does not work well with shaders, crashes when using some mods when renderer vulkan coped with all the tasks

### Describe the request.

Bring back plss renderer vulkan. It works much more stable than VirGl.
The problem of low fps is solved simply by optimizing the game itself with the help of mods

### Anything else?

No

**Comment by WesleyVanNeck** [comment]
Zink didnt run shaders to on snapdragon

**Comment by Iarkont** [comment]
> Zink didnt run shaders to on snapdragon

But VirGl works terribly on kirin

**Comment by kuzy21** [comment]
Just download the googleplay version it has zink renderer

**Comment by MasterGamingOp** [comment]
larkont bro vulkan renderer is expired plz i need a vulkan zink renderer pojavlauncher plzzz

**Comment by Bel69420** [comment]
Why? The performance still the same as old zink

**Comment by Bel69420** [comment]
Also, it has random crashes

**Comment by MasterGamingOp** [comment]
yr zink renderer i need but she is expired plz give me

**Comment by Iarkont** [comment]
I did not think that there were those who respond to such old requests. I wrote this back when I had a Kirin phone, but now I have a Snapdragon 680 phone and of course Zink doesn't work on it :)

**Comment by MasterGamingOp** [comment]
Plzzz i need zink

**Comment by Bel69420** [comment]
No
