### ISSUE TITLE
My lunar client and every version is crashing without anything showing

### ISSUE THREAD

**Issue by leftasaghost** [PojavLauncherTeam/PojavLauncher#2982]
### Describe the bug

any version are crashing but pixel client is working but after 4 minutes or 5 minutes its coming back to login page please fix this also please add every runtime I can't even run 1.16.5 on my device please fix that

### The log file and images/videos

I dont have a file

### Steps To Reproduce

```markdown
Please fix this bug
```

### Expected Behavior

game should not crash if it is 1.17 or 1.18.2 also it should not crash when we are playing

### Platform

```markdown
- Device model: Redmi 7a
- CPU architecture: arm64-v8a
- Android version: Android Pie 9.0
- PojavLauncher version: Latest version
```

**Comment by GaucovyAero** [comment]
:HYPERROFELwoe:

1. Pixel Client should work fine if VBOs is turned ON
2. "I don't have a file" is a lie. Please upload latestlog.txt.
3. 1.16 requires Java 8, not Java 17. Some people (like me) don't need the Java 17 runtime and therefore it shouldn't be preinstalled.
4. You haven't read the guide on how to install 1.17 and 1.18.
4. Also, what does "Latest version" mean? If you're running the GPlay Store version, you're VERY outdated. Download the "latest" one here on GitHub in the Actions tab.

**Comment by mchnjt** [comment]
some useful tip if you're updating to latest github build: buy minecraft

**Comment by kuzy21** [comment]
Also a usefull tip switch render to gl4es 1.14 and switch to java 8

**Comment by leftasaghost** [comment]
thanks
