### ISSUE TITLE
1.8 Error in "Multiplayer" Servers. 

### ISSUE THREAD

**Issue by TiRodrix** [PojavLauncherTeam/PojavLauncher#2983]
### Describe the bug

When I enter with 1.8 and I want to play Multiplayer they don't appear in Connection, could you give me a solution?, please:') 

![Screenshot_20220327-041759_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/102464568/160277200-5c820b3f-fac9-49aa-b163-e70795a25997.jpg)

### The log file and images/videos

![Screenshot_20220327-041759_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/102464568/160277328-333c2a7e-24fb-453f-9069-1fc6349269d9.jpg)

### Steps To Reproduce

```markdown
I enter 1.8 normally and when I want to play on Servers they don't appear in Literal Connection everything, I click Update and nothing.
```

### Expected Behavior

Que me aparecieran los Servidores activos.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

It would only be the problem of the 1.8 Server.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
