### ISSUE TITLE
[F-Req] <IPA Download>

### ISSUE THREAD

**Issue by TheBalkanDev** [PojavLauncherTeam/PojavLauncher#2984]
### Is this request related to a bug?

No

### Describe the request.

Hi,

Please Release an IPA Version.
It would be helpful, because right now you need an Jailbroken iDevice to use this.
IPA Files are like APK Files. You can Install them through an Program called AltStore.

### Anything else?

No

**Comment by khanhduytran0** [comment]
We all know that IPA exists for sideloading. But there’s a major problem: Apple doesn’t allow JIT (Just-In-Time) compiler, which is used to run the Java VM at near-native speed. Without it, you get interpreter, which gives you about 10% performance compared to JIT (6fps with interpreter, 60fps with JIT, tested version: 1.7.10).

**Comment by TheBalkanDev** [comment]
Is the JIC Compiler an alternative?

**Comment by khanhduytran0** [comment]
You may found there’s JIT enabling tool without jailbreak, however: With jailbreak, you get full access to JIT. Without it, you only get RW/RX JIT (what Xcode Debugger/AltJIT/Jitterbug) produces, which is something the Java VM doesn’t like for some reason.

**Comment by NotAHero04** [comment]
You may also forgot that this is the repository for the Android app. :)

**Comment by TheBalkanDev** [comment]
Is this an solution?

**Comment by TheBalkanDev** [comment]
https://github.com/osy/Jitterbug

**Comment by TheBalkanDev** [comment]
Note: iOS 14.2 Supports JIT nativly

**Comment by khanhduytran0** [comment]
> https://github.com/osy/Jitterbug

> With jailbreak, you get <ins>full access to JIT</ins>. Without it, you only get <ins>RW/RX JIT</ins> (what Xcode Debugger/AltJIT/Jitterbug produces), which is something that <ins>the Java VM doesn’t like</ins> for some reasons.

> Note: iOS 14.2 Supports JIT nativly

There’s no point to support jailed iOS 14.2, as it is jailbreakable.
