### ISSUE TITLE
Game crashing when i try to use forge mods

### ISSUE THREAD

**Issue by FitTurkoglu** [PojavLauncherTeam/PojavLauncher#2987]
It 's started 2-3 months ago game keeps crashing when i try to make world and says shutting down internal server but i play offline.
I don't even use mods that make game crash.
I used this mods before and everything was fine.
But for some reason the game no longer let's me play with mods.
It's happening both playstore and github versions.

Is there a solution for that?
because i searched so many things on youtube and still can't find a solution.

**Comment by khanhduytran0** [comment]
The reason is: you’re playing the full game for free. See #2679 for more info.

This is not a PojavLauncher issue.

The solution: buy the game.
