### ISSUE TITLE
[The Game Crash with -1 code] Crahs the Minecraft 1.18 to 1.18.2

### ISSUE THREAD

**Issue by OmarProGamer98** [PojavLauncherTeam/PojavLauncher#2989]
### Describe the bug

The game crash when. I launch the latest version of it in 1.18 the 1.18.1 and also 1.18.2 i don't know why the game crash with the -1 code the attachments are in Spanish but are photo about the error so if can you fix it or give me the solution i will appreciate very much so thanks for reading 
![Screenshot_20220327-202650_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88203855/160317206-4dce0489-eb27-4dd1-83e6-0b6407e30bc7.jpg)
![Screenshot_20220327-201923_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88203855/160317208-beed2a74-3fa0-4087-ac99-71c1d8c82e93.jpg)

### The log file and images/videos

![Screenshot_20220327-202650_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88203855/160317043-9d899544-5914-452e-836e-86772244dba5.jpg)
![Screenshot_20220327-201923_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88203855/160317047-c7351a8a-8a86-401a-91db-e08b67b951aa.jpg)

### Steps To Reproduce

```markdown
1. Start the launcher
2.the game crash when I launch the latest version 1.18 to up
```

### Expected Behavior

I expect that the latest version of Minecraft crash

### Platform

```markdown
- Device model: Samsung Galaxy a31s
- CPU architecture: arm x64
- Android version: 11
- PojavLauncher version: Latest version on play store
```

**Comment by kuzy21** [comment]
Use this patcher : https://cdn.discordapp.com/attachments/724163890803638277/922043517860212736/Pojav117AssetsPatcher.jar

**Comment by vFireRate** [comment]
for me, its showing the same messege: Application/game exited with code -1 
EVEN WITH VGPU?!!!

**Comment by WesleyVanNeck** [comment]
> for me, its showing the same messege: Application/game exited with code -1 EVEN WITH VGPU?!!!

use the new render branch

**Comment by Pojavlauncherisbest** [comment]
On thw mojanf screen my game crashes andin log it shows crash with -1 code

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
