### ISSUE TITLE
[SHADERS DID NOT LOAD IN CORRECTLY] <i press play on 1.18.2 and i have j17>

### ISSUE THREAD

**Issue by iiNexure** [PojavLauncherTeam/PojavLauncher#2990]
### Describe the bug

It doesnt load. Im trying to play 1.18.2 and it kicks me out of game and shows me this code in crash log

### The log file and images/videos

No log file. It is empty. However i have the crash code:

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 3/28/22, 3:51 AM
Description: Initializing game

java.lang.RuntimeException: could not preload blit shader
	at eql.a(SourceFile:406)
	at dyr.<init>(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:197)
Caused by: yw: Invalid shaders/core/blit_screen.json: Couldn't compile vertex program (minecraft:shaders/core/blit_screen.vsh, blit_screen) : ERROR: 0:5: 'in' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 1 compilation errors.  No code generated.
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.a(SourceFile:404)
	... 2 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/blit_screen.vsh, blit_screen) : ERROR: 0:5: 'in' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 1 compilation errors.  No code generated.
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 3 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.a(SourceFile:406)
	at dyr.<init>(SourceFile:619)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (aarch64) version Android-12
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2420920352 bytes (2308 MiB) / 4034920448 bytes (3848 MiB) up to 4034920448 bytes (3848 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 0 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd0d Stepping r0xdp14
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7747.59
	Virtual memory used (MB): 8579.25
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 2058.91
	JVM Flags: 2 total; -Xms3848M -Xmx3848M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 14 (aarch64)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Wait for game to load
3. Game crashes
```

### Expected Behavior

I expecf game to launch

### Platform

```markdown
- Device model: Galaxy Tab s7+
- CPU architecture: Kryo 585
- Android version: 12
- PojavLauncher version: 3.3.1.1
```

**Comment by ghost** [comment]
1. Update your pojavlauncher to the latest action build
2. Use this patcher and follow the instructions to start 1.18. 
[assets-v0.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8359696/assets-v0.zip)

**Comment by iiNexure** [comment]
What instructions?

**Comment by ghost** [comment]
https://pojavlauncherteam.github.io/updates/117.html

**Comment by artdeell** [comment]
Fixed on holy gl4es
