### ISSUE TITLE
[BUG] <Weird memory bug>

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#2991]
### Describe the bug

when i run out of memory on minecraft and turn up the memory it works but if i close pojavlauncher or turn on and off my device when i try to launch it crashes.

### The log file and images/videos

⠀

### Steps To Reproduce

```markdown
when i run out of memory on minecraft and turn up the memory it works but if i close pojavlauncher or turn on and off my device when i try to launch it crashes.
```

### Expected Behavior

i expect it to launch consistently.

### Platform

```markdown
- Device model: samsung galaxy tab e
- CPU architecture: idk
- Android version: 7.1.1
- PojavLauncher version: playstore
```

**Comment by kuzy21** [comment]
Don't turn off your device or use an older vision of the launcher

**Comment by SprainedSpark89** [comment]
i turn it off when i'm done using the tablet

**Comment by SprainedSpark89** [comment]
and it's from playstore

**Comment by mchnjt** [comment]
> ### Describe the bug
> when i run out of memory on minecraft and turn up the memory it works but if i close pojavlauncher or turn on and off my device when i try to launch it crashes.
> 
> ### The log file and images/videos
> ⠀
> 
> ### Steps To Reproduce
> ```gfm
> when i run out of memory on minecraft and turn up the memory it works but if i close pojavlauncher or turn on and off my device when i try to launch it crashes.
> ```
> 
> ### Expected Behavior
> i expect it to launch consistently.
> 
> ### Platform
> ```gfm
> - Device model: samsung galaxy tab e
> - CPU architecture: idk
> - Android version: 7.1.1
> - PojavLauncher version: playstore
> ```
> 
> ### Anything else?
> _No response_

What exactly do you mean about "turn on and off my device when i try to launch it crashes"

**Comment by PaRkErGey** [comment]
Can you try using the GitHub version?

**Comment by SprainedSpark89** [comment]
> > ### Describe the bug
> > when i run out of memory on minecraft and turn up the memory it works but if i close pojavlauncher or turn on and off my device when i try to launch it crashes.
> > ### The log file and images/videos
> > ⠀
> > ### Steps To Reproduce
> > ```
> > when i run out of memory on minecraft and turn up the memory it works but if i close pojavlauncher or turn on and off my device when i try to launch it crashes.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > i expect it to launch consistently.
> > ### Platform
> > ```
> > - Device model: samsung galaxy tab e
> > - CPU architecture: idk
> > - Android version: 7.1.1
> > - PojavLauncher version: playstore
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > _No response_
> 
> What exactly do you mean about "turn on and off my device when i try to launch it crashes"

Like if i go and turn off my device for the day then turning it back on with the same memory it will not launch

**Comment by SprainedSpark89** [comment]
And i haven't used the git hub ver i would have to reinstall java 17 (even though i can never seem to run 1.17+ and barly run 1.16.5)

**Comment by Mathias-Boulay** [comment]
better device needed
