### ISSUE TITLE
Pls add button shift for bedwars and skywars

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#30]
Plsss

**Comment by Azapru** [comment]
It is already in game.

**Comment by khanhduytran0** [comment]
![Screenshot_2020-04-01-05-47-12](https://user-images.githubusercontent.com/40482367/78082057-4c666600-73dc-11ea-8055-ac7fe11aa07d.png)

**Comment by khanhduytran0** [comment]
Available in all previews
