### ISSUE TITLE
[BUG] Can't log-in with email

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#3002]
### Describe the bug

For some reason, I try to login the latest action build where the offline account option was deleted with online account email, it say the username must be 3 to 16 letter etc. even tho it LITERALLY also said "login with email or username"

### The log file and images/videos

Don't really need it

### Steps To Reproduce

```markdown
Step 1. Open lastest action build version
Step 2. Try to log-in with online Minecraft account email
Step 3. Can't login
```

### Expected Behavior

I expectes that I can login with email

### Platform

```markdown
- Device model: Samsung galaxy a32
- CPU architecture: aarch64/arm64
- Android version: 11
- PojavLauncher version: lastest action build version
```

### Anything else?

I use account generator to get online account, becuz I don't want to pay for online account

**Comment by GaucovyAero** [comment]
Pirate detected. Please buy Minecraft: Java Edition first, thanks.

**Comment by DovydasTEDS** [comment]
"I don't want to pay for online account" Why?

**Comment by Thollp** [comment]
Lol

**Comment by Thollp** [comment]
> "I don't want to pay for online account" Why?

You think my mom will buy minecraft for me, right?

**Comment by GaucovyAero** [comment]
> > "I don't want to pay for online account" Why?
> 
> You think my mom will buy minecraft for me, right?

Well, you could maybe work at your friend's house and get some money that way, right?

**Comment by Thollp** [comment]
My parents considered Minecraft as a very violence game even tho my age is already above the minimum age for people to play mimecraft. And also my mom always said that they will never buy a paid game for me

**Comment by Thollp** [comment]
> > > "I don't want to pay for online account" Why?
> > 
> > 
> > You think my mom will buy minecraft for me, right?
> 
> Well, you could maybe work at your friend's house and get some money that way, right?

My friend house is very far from my house

**Comment by GaucovyAero** [comment]
> My parents considered Minecraft as a very violence game even tho my age is already above the minimum age for people to play mimecraft. And also my mom always said that they will never buy a paid game for me

I personally think they shouldn't pay for the games. Thing is, you can earn the money somehow and then buy a paysafecard and buy it that way.

**Comment by Thollp** [comment]
But I also just want to say that I will buy minecraft secretly when I got money from jobs

**Comment by GaucovyAero** [comment]
> But I also just want to say that I will buy minecraft secretly when I got money from jobs

yep, that's a good idea

**Comment by Thollp** [comment]
- [ ] etgg
