### ISSUE TITLE
[BUG] <fps bug>

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#3004]
### Describe the bug

Ok this is not what you think but when I am playing minecraft I get around 150 to 200 fps which is good for a phone I think, I have a 120 hz display, and when my phone started heating up it drops to 90 to 120

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Don't know
```

### Expected Behavior

To not drop

### Platform

```markdown
- Device model: s20 fe
- CPU architecture: 64
- Android version: 12
- PojavLauncher version: Latest
```

### Anything else?

I own minecraft

**Comment by Iarkont** [comment]
When the processor is heated, the fps will sag this happens with any smartphone or computer. And this does not apply to the PojavLauncher error, it is the problem of your smartphone

**Comment by Mathias-Boulay** [comment]
Lmao, latest, as if it was a version

**Comment by Mathias-Boulay** [comment]
My man just described thermal throttling.
Sorry to say, but you're phone doesn't have the adequate cooling, and thus reduced its performance, as to not kill itself

**Comment by Tiger56c** [comment]
Hey if the owner of pojavlauncher see this can you add the forge and optifine version all of them because I have no more space of my phone I can't download 1 single optifine or forge please

**Comment by khanhduytran0** [comment]
> Hey if the owner of pojavlauncher see this can you add the forge and optifine version all of them because I have no more space of my phone I can't download 1 single optifine or forge please

This is so confusing. You said you had no storage space but wanted every version of Forge/OptiFine packed into the ~~already-too-fat~~ apk.

**Comment by kuzy21** [comment]
Hey that's what everybody say with the version of pojav not my fault
