### ISSUE TITLE
[1.9-1.13] Attempt To Touch Any Keys Crashes The Game [Android x86] [ACER ASPIRE ONE]

### ISSUE THREAD

**Issue by Githubkiddo** [PojavLauncherTeam/PojavLauncher#3005]
### Describe the bug

*i attempt to play 1.9 to 1.13 but does not work and crashes a lot on my android x86 computer*

*also forge closed itself and optifine crashes while i also attempt to install them*
 

### The log file and images/videos

No Videos Right Now Or Photos Since my Android x86 Doesn't Allow Taking Screenshots
*

### Steps To Reproduce

```markdown
1. Plz Give Me Step On How To Fix It

2. Done
```

### Expected Behavior

*example: i click play and until i loaded a world. attempt to move crashes the game*
*

### Platform

```markdown
- Device model: *ACER Aspire One*
- CPU architecture: *Intel Celeron (r)*
- Android version: *9.0 r2*
- PojavLauncher version: croceus-v3_openjdk*
*
```

### Anything else?

*plz find me a way to play 1.9 to 1.12 without letting it crash*

**Comment by Githubkiddo** [comment]
this is the worst issues i ever created

**Comment by DovydasTEDS** [comment]
Install either: a. A linux distro or b. Windows and play Minecraft properly

**Comment by Githubkiddo** [comment]
thanks for that but my dad is lazy to create a windows 10 mbr and not gpi usb for my netbook
also. when i had windows. minecraft runs like potato. about a 10 fps to 36 fps
since my specs is not good for gaming

**Comment by Githubkiddo** [comment]
i also cant go to video setting since it will crash

**Comment by DovydasTEDS** [comment]
You could install a linux distro, especially a lightweight one. The install process is quite easy if you use a user friendly distro.

**Comment by Mathias-Boulay** [comment]
you could at least give a proper version of the issue
if you really have v3, you have a build old as fuck

**Comment by Githubkiddo** [comment]
> you could at least give a proper version of the issue if you really have v3, you have a build old as fuck



> you could at least give a proper version of the issue if you really have v3, you have a build old as fuck

ok mathias. i have a play store version one

**Comment by Mathias-Boulay** [comment]
Noted, can you try to reproduce the bug on current action builds ?
*The ones from the v3_openjdk branch*

**Comment by Mathias-Boulay** [comment]
hopefully should be fixed on the release candidate build.
