### ISSUE TITLE
Impossible to have multiples account

### ISSUE THREAD

**Issue by Adrir-v0id** [PojavLauncherTeam/PojavLauncher#3006]
### Describe the bug

This issue is really basic : i cannot have two microsoft accounts at the same time
oh and i jsut realize a small texture bug when you see profiles but idc about it

### The log file and images/videos

no need for log file because its an app issue

### Steps To Reproduce

```markdown
1.Start Pojav Launcher
2. Add a first microsoft minecraft account 
3. Add a second one
4. realize the problem
```

### Expected Behavior

Being able to choose between both accounts and to use them

### Platform

```markdown
- Device model: Redmi Note 10 S
- CPU architecture: 64 bits
- Android version:11
- PojavLauncher version: 3.3.1.1
```

**Comment by SprainedSpark89** [comment]
when you realize this is not only a problem with pojavlauncher

**Comment by Adrir-v0id** [comment]
It is,it works perfectly fine on java launcher

**Comment by SprainedSpark89** [comment]
i mean with other apps to

**Comment by artdeell** [comment]
Fixed in latest
