### ISSUE TITLE
[help] <Help find java 8 update 51 for pojavlauncher>

### ISSUE THREAD

**Issue by SprainedSpark89** [PojavLauncherTeam/PojavLauncher#3007]
### Is this request related to a bug?

well not with pojavlauncher maybe a bug with newer java versions

### Describe the request.

pls help me find java 8 update 51 for pojavlauncher.

### Anything else?

it would help run older versions and don't worry about log4j i will use a offline account for java 8
and for 32 bit arm The pojavlauncher java format is .xz

maybe gz if there is converter

**Comment by mchnjt** [comment]
PojavLauncher uses it's own, compiled Java 8. 
JRE from the official Java/Oracle website doesn't work.

**Comment by NotAHero04** [comment]
The current JVM is doing its work with even rd-132211. You just didn't try it.
The only problem I have faced so far was Forge 1.7.2, and it **has** a patch.

**Comment by SprainedSpark89** [comment]
how do you patch old versions to make them work with newer java?

**Comment by GaucovyAero** [comment]
> how do you patch old versions to make them work with newer java?

Check **NotAHero04/RandomPojavThings** repo here on GitHub. 
Click on Forge, then patchedJSONs, and you're in :D

**Comment by SprainedSpark89** [comment]
'-' i don't want forge and no issues with those versions i kind of start having problems with alpha 1.0.0 and older that's why i want to get java 8 update 51 and also all of the issues with older versions turns out to be the java all of the old versions start breaking after java 8 update 51

**Comment by SprainedSpark89** [comment]
> > how do you patch old versions to make them work with newer java?
> 
> Check **NotAHero04/RandomPojavThings** repo here on GitHub. Click on Forge, then patchedJSONs, and you're in :D


'-' i don't want forge and no issues with those versions i kind of start having problems with alpha 1.0.0 and older that's why i want to get java 8 update 51 and also all of the issues with older versions turns out to be the java all of the old versions start breaking after java 8 update 51
