### ISSUE TITLE
Plz fix this

### ISSUE THREAD

**Issue by Maxsteel2478** [PojavLauncherTeam/PojavLauncher#3008]
### Describe the bug

When i load the game the shaders dont load and it lagg

### The log file and images/videos

![Screenshot_20220402-084203](https://user-images.githubusercontent.com/102838391/161360084-db0046c9-7366-4532-9590-f0137ba95144.png)
![Screenshot_20220402-085146](https://user-images.githubusercontent.com/102838391/161360090-a1e0ea39-9a50-4a6a-92d9-91424b33739a.png)
![Screenshot_20220402-085157](https://user-images.githubusercontent.com/102838391/161360102-f61dcf94-178b-4000-9dcb-4b7d480150bc.png)
![Screenshot_20220402-084759](https://user-images.githubusercontent.com/102838391/161360113-b8ebb47d-6dc6-4b71-b7eb-5ec920c1edd7.png)

### Steps To Reproduce

```markdown
Plz help
```

### Expected Behavior

Plz fic

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Plz help meee

**Comment by khanhduytran0** [comment]
You might haven’t noticed that Open4ES isn’t made for virglrenderer. Also offline account moment :eyes:

**Comment by Tiger56c** [comment]
Hello why is my pojavlauncher if I play forge 1.12.2 when the world is generating and it will crash please fix this please

**Comment by ENDERMANYK** [comment]
Open4ES-BSL.updated.zip doesn't made by us, so no support, ask it creator for support

**Comment by WesleyVanNeck** [comment]
> Open4ES-BSL.updated.zip doesn't made by us, so no support, ask it creator for support

shaders are from this guy and they dont even have reflections as there made for gl4es
https://github.com/FilipinoAkoShaders/Output-Releases/releases/tag/UpdatedOpen4EsBsL

**Comment by Mathias-Boulay** [comment]
virgl stuff won't be fixed
