### ISSUE TITLE
How to allocate RAM? 

### ISSUE THREAD

**Issue by CloserPopcorn20** [PojavLauncherTeam/PojavLauncher#301]
So, I have 4 GB of RAM ( 2 GB used by the system). 
Without this function the Minecraft is being slowly. 
So, if you want, add the function, that on title.

**Comment by khanhduytran0** [comment]
That feature is a lot of users requested. If it's possible, I already added for a long time. But nope... Also allocating high ram may not good. Android lowmemkiller may do something unexpected.

**Comment by khanhduytran0** [comment]
This may be possible in v3, but also may be limited to 900mb (you may test if crash if set higher)

**Comment by KostyanSigaev** [comment]
If your system used 2 gb, try disable on settings this:
Google Play Market
YouTube
And all google apps, after this reboot your phone, and system use less than 1gb

**Comment by khanhduytran0** [comment]
Also @CloserPopcorn20 it's possible in v3 but
- 32-bit has limit of 768~950mb allocate.
- 64-bit has almost unlimited.
Currently using 64-bit Java Runtime (arm64 or x86_64) is having a problem about `glCheckFramebufferStatus() returned unknown status:0` so we disabled.

**Comment by khanhduytran0** [comment]
(as said before)
-----
V3 is already released so try it if you want.

**Comment by ednellbasilio** [comment]
But ram allocation for 1.16.5 fabric weird log because my ram allocation is 9B ram only
