### ISSUE TITLE
Forge 1.12.2 crash

### ISSUE THREAD

**Issue by Tiger56c** [PojavLauncherTeam/PojavLauncher#3011]
### Is this request related to a bug?

Hey pojav launcher please fix this if I play forge 1.12.2 with no mods when the world start generating and it will crash and i add mod like better fps and it crash please fix this

### Describe the request.

Please fix it

### Anything else?

Fix this please

**Comment by khanhduytran0** [comment]
You can fix it by buying the game.
See #2679 for more info.
(Since you didn’t provide any logs (also wrong form), we suppose that you haven’t bought the game)

**Comment by Tiger56c** [comment]
How do you buy it?

**Comment by Tiger56c** [comment]
And I can't log in my account
