### ISSUE TITLE
How to buy pojav launcher

### ISSUE THREAD

**Issue by Tiger56c** [PojavLauncherTeam/PojavLauncher#3012]
### Is this request related to a bug?

You said buy the game what is that mean

### Describe the request.

What is that mean

### Anything else?

????

**Comment by WesleyVanNeck** [comment]
buy a mojang account

**Comment by WesleyVanNeck** [comment]
not pojav

**Comment by Mathias-Boulay** [comment]
pojav cannot be bought, buy minecraft on their official website 😄

**Comment by Tiger56c** [comment]
I can't

**Comment by Tiger56c** [comment]
Whyyy

**Comment by Tiger56c** [comment]
Howww

**Comment by Tiger56c** [comment]
I'm trying to login

**Comment by Tiger56c** [comment]
I can't

**Comment by Tiger56c** [comment]
Why I can't log in

**Comment by Tiger56c** [comment]
And I can't play forge 1.12.2

**Comment by CriticalRange** [comment]
> Howww

https://www.minecraft.net/en-us

**Comment by Mathias-Boulay** [comment]
if you have an account, migrate it to microsoft
