### ISSUE TITLE
I can't log in to my online account

### ISSUE THREAD

**Issue by Tiger56c** [PojavLauncherTeam/PojavLauncher#3014]
### Is this request related to a bug?

I can't log in to my online account

### Describe the request.

How

### Anything else?

Howw

**Comment by kuzy21** [comment]
Did you migrated your account to Microsoft, all mojang accounts have migrated yo Microsoft

**Comment by Tiger56c** [comment]
Yes

**Comment by Tiger56c** [comment]
Why I can't log in?

**Comment by kuzy21** [comment]
What version of pojavlaucher are you running?

**Comment by Tiger56c** [comment]
My pojavlauncher version is crocus-v3_openjdk

**Comment by Tiger56c** [comment]
And if I play forge 1.12.2 it crash

**Comment by kuzy21** [comment]
So you can log in

**Comment by SprainedSpark89** [comment]
use java 8

**Comment by Tiger56c** [comment]
How

**Comment by SprainedSpark89** [comment]
go to setting then java then set java 8 as default
