### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Lox3209** [PojavLauncherTeam/PojavLauncher#3016]
### Describe the bug

1. Не получается установить текстуры-шейдеры для 1.16.5.
2. На 1.16.5 сломался интерфейс не работает (2. 4.)
3. Ещё какая-то проблема с инвинтарём нужно зажимать пкм чтобы перетаскивать предметы и не крафтится ничего с зажатым Shift. 

помогите решить проблемы 

### The log file and images/videos

7

### Steps To Reproduce

```markdown
Перетащил оптифайн фордж в папку с модами или ещё что-то
```

### Expected Behavior

Я не знаю что я ожидал

### Platform

```markdown
- Device model: mi 8 pro 8/128
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version:
3.3.1.1_rel_20210206]
```

**Comment by ajit56** [comment]
Very old version use new version

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
