### ISSUE TITLE
让在线账号下载的我的世界文件可以用其另外一个离线账号登录

### ISSUE THREAD

**Issue by villager1314** [PojavLauncherTeam/PojavLauncher#3017]
### Describe the request.

danke shone

### Anything else?

因为我有许多服务器需要登录，所以用不同的账号，例如离线账号和在线账号登录了对不同登陆有所需求的服务器，希望可以共同使用游戏文件。

**Comment by Thollp** [comment]
Please translate it

**Comment by SprainedSpark89** [comment]
i don't really understand request

https://translate.google.com

**Comment by GaucovyAero** [comment]
> i don't really understand request
> 
> https://translate.google.com

It seems like he wants 2 things that have already been done:
a) Downloading assets, resources n' stuff with the online account and then proceeding to log in and play singleplayer with an offline account.
b) He wants 2 Microsoft accounts, which is possible, so I don't really see a point made in this ticket.
c) He has to update to the latest Actions build to get these features.

**Comment by TWTommyee** [comment]
如果你知道如何使用離線帳號的話，這件事一直都做得到。
甚至，只要你有一個正版帳號，你下載的遊戲檔案給10個離線帳號使用都沒問題，因為離線帳號伺服器的玩家資料是用玩家名儲存的。
但是，你不能同時在啟動器登入兩個Microsoft帳號，使用離線帳號也會導致模組無法正常運作，請詳閱 https://github.com/PojavLauncherTeam/PojavLauncher/issues/2679#issue-1123875081

**Comment by villager1314** [comment]
> 请翻译一下

use Chrome translate

**Comment by TWTommyee** [comment]
It's already solved bro why are you still digging this issue

> > 请翻译一下
> 
> use Chrome translate
