### ISSUE TITLE
[F-Req] Minecraft account

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#3018]
### Is this request related to a bug?

 Nope

### Describe the request.

I just want to ask why anyone can't login with microsoft account on pojavlauncher

### Anything else?

Nothing

**Comment by Tiger56c** [comment]
Same

**Comment by Tiger56c** [comment]
If I try my Microsoft account I can't even log in pojav launcher need to fix this

**Comment by Mathias-Boulay** [comment]
you need to buy minecraft java on the account and link it
