### ISSUE TITLE
Forge 1.12.2 crash

### ISSUE THREAD

**Issue by Tiger56c** [PojavLauncherTeam/PojavLauncher#3022]
### Is this request related to a bug?

Hey pojav launcher can you fix the forge 1.12.2 crash when the world is generating and after the and it says shutting down internal after than and the pojav launcher game exited please fix this

**Comment by vFireRate** [comment]
it happened to me too! i just get back to launcher menu after 3sec in generating world, im using mc 1.12.2 forge,

**Comment by vFireRate** [comment]
also, it works very smoothly when im using OptiFine, i dont know why is this happened, before this is happened, my forge working normal, but now it feels like pojav wants me to use OptiFine 1.12.2 only.

**Comment by Tiger56c** [comment]
How to fix it? I wanna use my mod again please

**Comment by khanhduytran0** [comment]
@Tiger56c you always picked the wrong form
Please fill it in `Bug Report' instead. Additionally, if your Microsoft is unable to login, try the latest Actions builds.

**Comment by Tiger56c** [comment]
Ok and sorry I pick the wrong form

**Comment by vFireRate** [comment]
from now on idk how to fix this

Pada tanggal Sen, 4 Apr 2022 20.48, Tiger56c ***@***.***>
menulis:
