### ISSUE TITLE
[BUG] <Tlauncher not starting(tried all other fixes)>

### ISSUE THREAD

**Issue by DhruvRp** [PojavLauncherTeam/PojavLauncher#3023]
### Describe the bug

[hs_err_pid14244.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8409075/hs_err_pid14244.log)
I have tried all the possible solutions, like reinstalled java, updated java, reinstalled Minecraft, and updated video drivers.
I was also suggested to set this argument - XX:+IgnoreUnrecognizedVMOptions
Nothing is working Please help

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

,

### Platform

```markdown
- Device model: Dell
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
Hey, it looks like you have jumped to the wrong repository. This repo is PojavLauncher (Android), not TLauncher (PC)

**Comment by khanhduytran0** [comment]
> --accessToken null

Buy Minecraft when? :eyes:

**Comment by DhruvRp** [comment]
I am really sorry
