### ISSUE TITLE
Mouse right click not working 

### ISSUE THREAD

**Issue by Peeyusharx** [PojavLauncherTeam/PojavLauncher#3024]
### Describe the request.

In old versions of pojav launcher there was an option that treats back as right click for those mobiles that treat right click as back button plzz add it back

**Comment by GaucovyAero** [comment]
There are 2 fixes:
a) Updating Pojav via GitHub Actions
b) Updating your OS (to LineageOS 19 - Android 12 for example)

**Comment by Mathias-Boulay** [comment]
not an enhancement

**Comment by Peeyusharx** [comment]
My os is already updated to Android 12 and i have already updated the pojav launcher from actions

**Comment by Peeyusharx** [comment]
> not an enhancement

Why did you deleted that feature and now you are telling it's not enhancement ihave sent almost  bug three issues to your team but you didn't replied to me listen me you are a developer then you need to check all you app users problems you understood and it's an enhancement becoz this feature was deleted  by your freaky team

**Comment by Kirillka22** [comment]
I guess its time to close this request

**Comment by Peeyusharx** [comment]
I will not close the issue before it don't get be solved

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
