### ISSUE TITLE
[BUG] 1.18 crashes fix it pls

### ISSUE THREAD

**Issue by Pojavlauncherisbest** [PojavLauncherTeam/PojavLauncher#3025]
### Describe the bug

When the game loaded to mojang screen in log there is a error in last aw browser crash code-1
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8416790/latestlog.txt)

### The log file and images/videos

I already uploaded 

### Steps To Reproduce

```markdown
Start 1.18 optifine 
Game crashes
```

### Expected Behavior

Yes

### Platform

```markdown
- Device model: vivo 1820
- CPU architecture: 64
- Android version: 8.1.0
- PojavLauncher version: github
```

### Anything else?

No

**Comment by Pojavlauncherisbest** [comment]
idk why Its not showing in the file but it showed in log output

**Comment by Pojavlauncherisbest** [comment]
![Screenshot_2022_0405_195320](https://user-images.githubusercontent.com/102723873/161776075-c3e2e329-0878-406e-a184-96de6a6392f3.png)
Now its showing this error

**Comment by LegacyGamerHD** [comment]
stop making new issues

**Comment by Pojavlauncherisbest** [comment]
I am using gl4es

**Comment by WesleyVanNeck** [comment]
wait for #3019 to be merged

**Comment by kuzy21** [comment]
which one gl4es 14 or gl4es 15

**Comment by offbeat-stuff** [comment]
does not matter,after the merge there will only be gl4es holy
