### ISSUE TITLE
Keep alive service

### ISSUE THREAD

**Issue by NotScareBat** [PojavLauncherTeam/PojavLauncher#3028]
### Is this request related to a bug?

Crashes on lower end devices

### Describe the request.

A service made when minecraft is started so pojavlauncher won't crash but run in e background this would make it easier to switch between minecraft and other apps like discord when trying to call a friend to play. heres a screenshot of what i mean by service 
![Screenshot_20220405-193049-1](https://user-images.githubusercontent.com/90552670/161815647-7ea657d2-0c98-4233-a06d-91f79bfcfaec.jpg)

### it would be a rlly cool feature

**Comment by ghost** [comment]
I agree.

**Comment by VlipperGZ** [comment]
Up
