### ISSUE TITLE
Sustained performance

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#3029]
### Is this request related to a bug?

What us it?what does it do?

### Describe the request.

Does it effect the game?

### Anything else?

Should I enable it yes or no

**Comment by offbeat-stuff** [comment]
If you have a gaming phone turn it off
If you have a small tiny phone turn it on for less performace but less hot device

**Comment by kuzy21** [comment]
But what I'd I have a a phone that can do 200 fps with it on do I leave it on or naw

**Comment by kuzy21** [comment]
Because when I leave it on it heat my device but Martians the performance
