### ISSUE TITLE
requesting for returning  the offline account access 

### ISSUE THREAD

**Issue by Sazedzahan** [PojavLauncherTeam/PojavLauncher#3031]
### Is this request related to a bug?

why pojav launcher team you all make the launcher only can run minecraft java with online account why u all remove the offline account access why now I can't play mc and i can't buy mc java that's why I use pojavlauncher but u all make the can run mc java with only online account please reply me

**Comment by Sazedzahan** [comment]
please return the offline account access

**Comment by khanhduytran0** [comment]
Returning offline account (`playing the full game without a license`) will open the door for Mojang/Microsoft to shutdown this project anytime.
