### ISSUE TITLE
[BUG] None of the jre17 versions working on galaxy s9+ (exynos) 

### ISSUE THREAD

**Issue by raphaelko62** [PojavLauncherTeam/PojavLauncher#3032]
### Describe the bug

I've been trying to get 1.18.2 running on my S9+, but all the jre17 versions I'm using are giving me the same error, I would just like to get a proper version in order to play. 

### The log file and images/videos

java.lang.RuntimeException: Architecture arm64 is incompatible with Java Runtime arm.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Use any jre17 VM
3. Choose 1.18.2
4. Play
```

### Expected Behavior

I expected the game to launch, because I was somewhat sure everything was correct 

### Platform

```markdown
- Device model:Galaxy S9+ (Exynos) 
- CPU architecture: ARM mali-G72
- Android version: 10 
- PojavLauncher version: Crocus-v3_openjdk
```

### Anything else?

![Screenshot_20220406-120348_DevInfo](https://user-images.githubusercontent.com/103042318/161938712-2d9ee17b-f2b5-49d4-85d2-f741b15f997b.jpg)
![Screenshot_20220406-120355_DevInfo](https://user-images.githubusercontent.com/103042318/161938736-9d8a0685-d557-4ab9-8aa5-ca9bf109f7f9.jpg)

**Comment by khanhduytran0** [comment]
> CPU architecture: ARM mali-G72

A flagship running at 32-bit mode is illegal.

The jre17 you picked is made for ARM 32-bit, not 64-bit. What you need to do is obtain the exact one.

> Architecture __arm64__ is incompatible with Java Runtime arm.

- [jre17-arm-20210914-release.tar.xz](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm-20210914-release.tar.xz) 35.6 MB <- you picked this, which is not 64-bit
- [jre17-arm64-20210825-release.tar.xz](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz) 36.3 MB <- this matches the error message, but you haven’t tried it
- [jre17-x86-20220225-release.tar.xz](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-x86-20220225-release.tar.xz) 36.2 MB <- this is for Intel/AMD CPU (32-bit)
- [jre17-x86_64-20210825-release.tar.xz](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-x86_64-20210825-release.tar.xz) 37.4 MB  <- this is for Intel/AMD CPU (64-bit)

**Comment by raphaelko62** [comment]
> > CPU architecture: ARM mali-G72
> 
> A flagship running at 32-bit mode is illegal.
> 
> The jre17 you picked is made for ARM 32-bit, not 64-bit. What you need to do is obtain the exact one.
> 
> > Architecture **arm64** is incompatible with Java Runtime arm.
> 
> * [jre17-arm-20210914-release.tar.xz](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm-20210914-release.tar.xz) 35.6 MB <- you picked this, which is not 64-bit
> * [jre17-arm64-20210825-release.tar.xz](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm64-20210825-release.tar.xz) 36.3 MB <- this matches the error message, but you haven’t tried it
> * [jre17-x86-20220225-release.tar.xz](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-x86-20220225-release.tar.xz) 36.2 MB <- this is for Intel/AMD CPU (32-bit)
> * [jre17-x86_64-20210825-release.tar.xz](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-x86_64-20210825-release.tar.xz) 37.4 MB  <- this is for Intel/AMD CPU (64-bit)

tried all of them. same error message.
