### ISSUE TITLE
[BUG] assets-v0 zip 

### ISSUE THREAD

**Issue by Pojavlauncherisbest** [PojavLauncherTeam/PojavLauncher#3035]
### Describe the bug

![Screenshot_20220406_210839](https://user-images.githubusercontent.com/102723873/162014122-2e15688a-31c6-46e8-89c4-e51ce559f8aa.jpg)
 When i launch 1.18 it shows this error even i removed assets-v0.zip from option.txt file
And also put the assets-v0 pack in resource pack but nothing work

### The log file and images/videos

I uploaded 

### Steps To Reproduce

```markdown
Start pojavlauncher 
 launch 1.18 bug appears
```

### Expected Behavior

Yed

### Platform

```markdown
- Device model: Vivo 1820
- CPU architecture: 64
- Android version: 8.1.0
- PojavLauncher version: github
```

### Anything else?

No

**Comment by ghost** [comment]
What version are you running?

**Comment by Pojavlauncherisbest** [comment]
Bro whenever i open a ticket for a bug the bug gets fix this happen to me
every time

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
