### ISSUE TITLE
Low FPS on High-End Android device

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3037]
### Is this request related to a bug?

Hello everyone,
As you read in the title, my Samsung tab S7 ( Snapdragon 865+, Adreno 650, 6gb Ram) runs poorly. I installed Optifine and lowered the quality to 40%, turned off all animations, turned down render distance.. basically tried everything, but only get around 20fps
My tablet runs OneUi 4.0 Android 12.
I dont know if its because of my Android version not being optimized or my Device not being optimized or good enough(i dont think its not good enough because it ran 1.17.1 easily without optifine on 150fps).

### Describe the request.

A optimization for Android 12 or the specific device might fix it.

**Comment by kuzy21** [comment]
What minecraft vesion are u running?

**Comment by kuzy21** [comment]
I also got a snapdragon 865 and I get 200+ fps on 1.18.2

**Comment by offbeat-stuff** [comment]
Use fabric with sodium,lithium,starlight,ferritecore and lazydfu

**Comment by offbeat-stuff** [comment]
also turn off sodium chunk rendering because that is unsupported for now

**Comment by kuzy21** [comment]
US a patcher for 1.17 optifine and ubove and remember sodium crashes on 1.16.5 and above

**Comment by ghost** [comment]
> Use fabric with sodium,lithium,starlight,ferritecore and lazydfu

Can i use it on servers though?

**Comment by ghost** [comment]
> 

I tried using them, but they only give me around 3-10fps

**Comment by 1493028** [comment]
> > 
> 
> I tried using them, but they only give me around 3-10fps

getting worse and the fps

**Comment by simonjonnemeth** [comment]
> US a patcher for 1.17 optifine and ubove and remember sodium crashes on 1.16.5 and above

This is no longer necessary in the latest dev builds.

**Comment by GaucovyAero** [comment]
> > 
> 
> I tried using them, but they only give me around 3-10fps

I mean, the performance could even caused by the low render resolution. You should increase it up to 100%. Also, you shouldn't enable alternate surface rendering in PojavLauncher settings (Video and renderer).

I am running Android 12 too (be it LineageOS 19) on an old Galaxy S7 edge and have no issues whatsoever.

**Comment by offbeat-stuff** [comment]
make sure to use gl4es

**Comment by ghost** [comment]
> 

I changed the resolution to 100% and switched the Renderer and now my game is running an average of 80-130fps, thank you

**Comment by Ghuneyluyarnack123** [comment]
> > > 
> > 
> > 
> > I tried using them, but they only give me around 3-10fps
> 
> I mean, the performance could even caused by the low render resolution. You should increase it up to 100%. Also, you shouldn't enable alternate surface rendering in PojavLauncher settings (Video and renderer).
> 
> I am running Android 12 too (be it LineageOS 19) on an old Galaxy S7 edge and have no issues whatsoever.

Does it increase your fps by turning it on. ? But what does"use alternate surface rendering"  do? .
