### ISSUE TITLE
Where is download apk pl v3.2 ?

### ISSUE THREAD

**Issue by Mikar9** [PojavLauncherTeam/PojavLauncher#304]
Apk ?

**Comment by khanhduytran0** [comment]
I'm uploading. If want now go to https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/247571860

**Comment by khanhduytran0** [comment]
I think you will open another issue about java runtime, go here for instruction https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Testing-v3

**Comment by Mikar9** [comment]
> Tôi đang tải lên. Nếu muốn ngay bây giờ, hãy truy cập https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/247571860

Thanks 👍
