### ISSUE TITLE
Crash Apk

### ISSUE THREAD

**Issue by 1493028** [PojavLauncherTeam/PojavLauncher#3041]
### Describe the bug

The the app keeps crashing when enter version 1.16.5 optifine

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Nope
```

### Expected Behavior

Nope

### Platform

```markdown
- Device model: Vivo y50 8/128GB
- CPU architecture: Aarch64/Arm64
- Android version: 10
- PojavLauncher version: latest Github Build
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
You haven't sent any logs.

**Comment by 1493028** [comment]
> You haven't sent any logs.

Later i sent

**Comment by artdeell** [comment]
Invalid
