### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MerciGG** [PojavLauncherTeam/PojavLauncher#3042]
### Describe the bug

I was in a bw game and it was randomly crahsing for no reason it happened to me like 10 times now, i lost a fking winstreak cuz of this fix this or any suggestion to fix

### The log file and images/videos

No Crash logs, just freezes and crash, and brings me back to home screen like nothing ever happened

### Steps To Reproduce

```markdown
Start pojav, play and random crashes happens(forge 1.8.9)

My mods:
Lunar keystrokes
Foamfix
Betterfps
Optifine(ofc)
Vanilla enhancments
Powns Cheatbreaker hud
Memoryfix
Texfix
Oranges old animations mods
```

### Expected Behavior

I expect to not crash?

### Platform

```markdown
- Device model: Oppo A94 8/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Version 3.3.1
```

### Anything else?

None

**Comment by kuzy21** [comment]
Too much mods

**Comment by kuzy21** [comment]
And some are unsported

**Comment by GaucovyAero** [comment]
FoamFix, BetterFPS, MemoryFix and TexFix makes the game crash more (the game still crashes without the mods, but the crash takes more time to happen). Also, you're on a super-old build (more than 1 year old), so you should update to the latest one with a green checkmark on it in [Actions.](https://github.com/PojavLauncherTeam/PojavLauncher/actions)
