### ISSUE TITLE
[BUG] <holy edition is broken :(>

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#3043]
### Describe the bug

Everything thing looks weird from a distance

### The log file and images/videos

There is no log file

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

To look nice

### Platform

```markdown
- Device model: s20 fe
- CPU architecture: 64
- Android version: 12
- PojavLauncher version: holy edition
```

### Anything else?

I have the game bought

**Comment by kuzy21** [comment]
Uploading Screen_Recording_20220407-061816_PojavLauncher (Minecraft Java Edition for Android).mp4…

**Comment by GaucovyAero** [comment]
Uhm, maybe use virgl and crank up mipmap levels to 4?

**Comment by kuzy21** [comment]
Ok thanks

**Comment by kuzy21** [comment]
Virgl is crashing on 1.18.2 optifine for some reason

**Comment by kuzy21** [comment]
Watch this to see what i mean :https://youtu.be/Xyj5yf4yWis

**Comment by GaucovyAero** [comment]
Everything looks totally normal **except** your controlmap, and i also have no idea why virgl is crashing. Send logs.

**Comment by jorgieee** [comment]
what is a control map

**Comment by jorgieee** [comment]
and how do i fix the "control map"

**Comment by kuzy21** [comment]
Here is log: 
--------- beggining with launcher debug
Info: Launcher version: crocus-472-e46dab0ae-
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: POJAV_NATIVEDIR=/data/app/~~yZ7arRG-sLrZlByoVspLUg==/net.kdt.pojavlaunch.debug-Z1yAAzK81DQb2v7ioU3ylg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: LIBGL_SHRINK=0
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~yZ7arRG-sLrZlByoVspLUg==/net.kdt.pojavlaunch.debug-Z1yAAzK81DQb2v7ioU3ylg==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_virgl
Added custom env: LIBGL_ES=3_virgl
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=430
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.3
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/LIBGL   (23057): Initialising gl4es
I/LIBGL   (23057): v1.1.4 built on Apr  6 2022 13:41:20
I/LIBGL   (23057): Using GLES 1.1 backend
I/LIBGL   (23057): loaded: libGLESv1_CM.so
I/LIBGL   (23057): loaded: libEGL.so
I/LIBGL   (23057): Using GLES 1.1 backend

I/LIBGL   (23057): Hardware Full NPOT detected and used
I/LIBGL   (23057): Extension GL_OES_framebuffer_object  detected and used
I/LIBGL   (23057): Extension GL_OES_point_sprite  detected and used
I/LIBGL   (23057): Extension GL_OES_point_size_array  detected
I/LIBGL   (23057): Extension GL_OES_texture_cube_map  detected and used
I/LIBGL   (23057): Extension GL_OES_blend_subtract  detected and used
I/LIBGL   (23057): Extension GL_OES_blend_func_separate  detected and used
I/LIBGL   (23057): Extension GL_OES_blend_equation_separate  detected and used
I/LIBGL   (23057): Extension GL_OES_texture_mirrored_repeat  detected and used
I/LIBGL   (23057): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (23057): Extension GL_OES_depth24  detected and used
I/LIBGL   (23057): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (23057): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (23057): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (23057): Extension GL_OES
_draw_texture  detected and used
I/LIBGL   (23057): Extension GL_OES_texture_float  detected and used
I/LIBGL   (23057): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (23057): Max texture size: 16384

I/LIBGL   (23057): Texture Units: 2/2 (hardware: 2), Max lights: 8, Max planes: 1
I/LIBGL   (23057): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (23057): Max Anisotropic filtering: 16
I/LIBGL   (23057): Hardware vendor is Qualcomm
I/LIBGL   (23057): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   (23057): sRGB surface supported
I/LIBGL   (23057): EGLImage to Texture2D supported
I/LIBGL   (23057): EGLImage to RenderBuffer supported

I/LIBGL   (23057): ignore MipMap
I/LIBGL   (23057): Targeting OpenGL 1.5
I/LIBGL   (23057): No hack in shader converter to define overloaded function with int
I/LIBGL   (23057): NPOT texture handled in hardware
I/LIBGL   (23057): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (23057): glX Will try to recycle EGL Surface
I/LIBGL   (23057): Current folder is:/
I/jrelog  (23057): dlopen libgl4es_114.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  (23057): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (23057): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (23057): dlopen /data/app/~~yZ7arRG-sLrZlByoVspLUg==/net.kdt.pojavlaunch.debug-Z1yAAzK81DQb2v7ioU3ylg==/lib/arm64/libopenal.so success

I/jrelog  (23057): Done processing args

I/jrelog  (23057): Found JLI lib
I/jrelog  (23057): Calling JLI_Launch

Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
  <log4j:Event logger="LaunchWrapper" timestamp="1649356132286" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading tweak class name optifine.OptiFineTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1649356132294" level="INFO" thread="main">
    <log4j:Message><![CDATA[Using primary tweak class name optifine.OptiFineTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1649356132294" level="INFO" thread="main">
    <log4j:Message><![CDATA[Calling tweak class optifine.OptiFineTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="optifine.OptiFineTweaker" timestamp="1649356132295" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] OptiFineTweaker: acceptOptions]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="optifine.OptiFineTweaker" timestamp="1649356132295" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] OptiFineTweaker: injectIntoClassLoader]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="optifine.OptiFineClassTransformer" timestamp="1649356132297" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] OptiFine ClassTransformer]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="optifine.OptiFineClassTransformer" timestamp="1649356132298" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] OptiFine ZIP file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/optifine/OptiFine/1.18.2_HD_U_H7_pre3/OptiFine-1.18.2_HD_U_H7_pre3.jar]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="optifine.OptiFineTweaker" timestamp="1649356132317" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] OptiFineTweaker: getLaunchArguments]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="optifine.OptiFineTweaker" timestamp="1649356132317" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] OptiFineTweaker: getLaunchTarget]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1649356132326" level="INFO" thread="main">
    <log4j:Message><![CDATA[Launching wrapped minecraft {net.minecraft.client.main.Main}]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1649356133371" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1649356133372" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1649356133423" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.logging.CrashReportExtender]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1649356135648" level="INFO" thread="main">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Method not present: aid.create]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1649356143259" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="za" timestamp="1649356143524" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="za" timestamp="1649356143524" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="za" timestamp="1649356143525" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService" timestamp="1649356144124" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD']]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="dyr" timestamp="1649356147524" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Setting user: Teqoo0]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1649356147800" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.optifine.Log" timestamp="1649356148033" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Method not present: dyo.getKeyModifier]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="dyr" timestamp="1649356148227" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Backend library: LWJGL version 3.2.3 SNAPSHOT]]></log4j:Message>
  </log4j:Event>
VirGL: OSMesa buffer flush is DISABLED!
DlLoader: using external 
DlLoader: using default /data/app/~~yZ7arRG-sLrZlByoVspLUg==/net.kdt.pojavlaunch.debug-Z1yAAzK81DQb2v7ioU3ylg==/lib/arm64/libOSMesa_8.so
VirGL: libvirgl_test_server = 0x145d7197edf70563
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=27145
EGLBridge: EGLDisplay=0xb400007895a14c80, EGLSurface=0x76feb39d00
VirGL: created EGL context 0x76ff480180
EGLBridge: eglMakeCurrent() succeed!
VirGL: vtest_main = 0x76e7131278
VirGL: Calling VTest server's main function
OSMDroid: width=2400;height=1080, reserving 10368000 bytes for frame buffer
OSMDroid: created frame buffer
  <log4j:Event logger="net.optifine.Log" timestamp="1649356148455" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[OptiFine] (Reflector) Method not present: net.minecraftforge.fml.loading.progress.EarlyProgressVisualization.handOffWindow]]></log4j:Message>
  </log4j:Event>
OSMDroid: generating context
gl_version 32 - es profile enabled
WARNING: running without ARB/KHR robustness in place may crash
failed to create sync opengl context
vtest_client_dispatch_commands: client context created.
GLSL feature level 430
vrend_renderer_fill_caps: Entering with stale GL error: 1282
GLSL feature level 430
OSMESA_TARGET: screen=0x76dd130600
OSMESA: stmgr=0x76dcec51f0; stapi=0x76c1d13d20
OSMDroid: context=0x76fec296a0
OSMDroid: making current
unknown format is 19
OSMDroid: vendor: Mesa/X.org
OSMDroid: renderer: virgl

**Comment by kuzy21** [comment]
how come the enchants looks like that

**Comment by GaucovyAero** [comment]
there is no visible crash in the "log" you send though

**Comment by kuzy21** [comment]
but it kicked me out of the game

**Comment by kuzy21** [comment]
and how come the enchants and clouds look like that

**Comment by kuzy21** [comment]
Hello anyone there?

**Comment by kuzy21** [comment]
I am gonna leave this issue open till u guys fix it ok

**Comment by offbeat-stuff** [comment]
You should wait for at least a week gl4es extra is really experimental tech

**Comment by kuzy21** [comment]
ok thanks

**Comment by kuzy21** [comment]
Is it fixed now?

**Comment by kuzy21** [comment]
So does everything in the distance looks weird now
