### ISSUE TITLE
[BUG]  opening a world kicks me to login page

### ISSUE THREAD

**Issue by Pojavlauncherisbest** [PojavLauncherTeam/PojavLauncher#3044]
### Describe the bug

Opening a local  world kicks me to login page but when i open a multi player server then i can easily play and in log there is no error

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8443678/latestlog.txt)

### Steps To Reproduce

```markdown
Launch 1.18 open a world game kicks me to login page
```

### Expected Behavior

Yea

### Platform

```markdown
- Device model: vivo1820
- CPU architecture: 64
- Android version: 8.1.0
- PojavLauncher version: recent github version
```

### Anything else?

No

**Comment by ghost** [comment]
It looks like the assets-v0.zip file has the wrong pack format. Make sure for 1.18 that in the pack.mcmeta the pack format is 8.

**Comment by ghost** [comment]
It also looks like it hung on generating the world. Try adding more memory in the settings.

**Comment by Pojavlauncherisbest** [comment]
No i the pack is deactivated

**Comment by Pojavlauncherisbest** [comment]
I didnt activate the pack

**Comment by GaucovyAero** [comment]
Out of memory maybe? Thing is, there is no actual crash in the log. I would try to allocate less RAM.

**Comment by Pojavlauncherisbest** [comment]
Yes it shows u have 1200 ram available and u have given 1340

**Comment by artdeell** [comment]
Device not powerful enough
