### ISSUE TITLE
[BUG] Arm64 JRE17 not working on a 64 bit device 

### ISSUE THREAD

**Issue by raphaelko62** [PojavLauncherTeam/PojavLauncher#3045]
### Describe the bug

I think I'm going crazy. I'm using a galaxy S9+ (exynos) and I've tried playing 1.18.2 on EVERY SINGLE JRE17 VERSION. Even arm64 as yall recommended. Ive tried every version, with every renderer and it keeps saying architecture arm64 is incompatible with jave runtime arm. I've also heard about a resource pack thats needed to run this but i cant find it, so if you have the link, please comment. 

### The log file and images/videos

![Screenshot_20220407-174648_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103042318/162228315-23f881c9-d901-4744-80ac-369d6caa1058.jpg)
![Screenshot_20220407-174716_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103042318/162228325-42585ad0-c9d3-41c6-9673-32e5f7f9e6ba.jpg)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Use any java17 (i actually dont know about this one
3. Choose 1.18.2
4. Play
```

### Expected Behavior

i expected the game to launch because ive spent a whole day trying to fix this. 

### Platform

```markdown
- Device model: Galaxy S9+
- CPU architecture: i dont know at this point. everything says arm mali g72 but yall say 64 bit
- Android version: 10 
- PojavLauncher version: Crocus-v3_openjdk
```

### Anything else?

BIG UPDATE. I DELETED ALL MY OTHER JRE17 VERS AND WE GOT SOMEWHERE. BUT I GOT ANOTHER ERROR. HERE'S THE CRASH DATA.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/7/22, 3:19 PM
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:197)
Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7: S0054: Overloading built-in function 'max' not allowed
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.a(SourceFile:421)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7: S0054: Overloading built-in function 'max' not allowed
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1021735168 bytes (974 MiB) / 1610612736 bytes (1536 MiB) up to 1610612736 bytes (1536 MiB)
	CPUs: 8
	Processor Vendor: 0x53
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x002 Stepping r0x0p1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4858.42
	Virtual memory used (MB): 5397.83
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1386.09
	JVM Flags: 2 total; -Xms1536M -Xmx1536M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x #

even bigger update on this error: normal 1.18 is working fine. The game only crashes on 1.18.1/.2

**Comment by raphaelko62** [comment]
PS: its probably that my phone is aarch64

**Comment by WesleyVanNeck** [comment]
> PS: its probably that my phone is aarch64

arm64 and aarch64 are same thing

**Comment by WesleyVanNeck** [comment]
you instaled arm and x86 delete those and then is should work

**Comment by raphaelko62** [comment]
thanks for the info

**Comment by GaucovyAero** [comment]
Well, you should update to the latest GitHub [Actions build](https://github.com/PojavLauncherTeam/PojavLauncher/actions), because you're 1 year out of date.

**Comment by raphaelko62** [comment]
how do i do that?

**Comment by DovydasTEDS** [comment]
Download latest github version by clicking on actions, then click on the newest with a green tick.

**Comment by raphaelko62** [comment]
> Download latest github version by clicking on actions, then click on the newest with a green tick.

tried that, didn't find any download link

**Comment by DovydasTEDS** [comment]
Latest as of writing this comment: https://github.com/PojavLauncherTeam/PojavLauncher/suites/5962326637/artifacts/204841319

**Comment by DovydasTEDS** [comment]
I'd recommend getting the latest github actions build. To do this, click on actions, then the latest one with a green tick. Scroll down until you see app-debug. Click on app-debug. The apk will start to download. Once downloaded, run the file and do what the package installer says.
