### ISSUE TITLE
[BUG] Touch controls are misaligned from an offset at the bottom of the screen

### ISSUE THREAD

**Issue by simonjonnemeth** [PojavLauncherTeam/PojavLauncher#3046]
### Describe the bug

The touch controls seem to be accounting for my navigation bar as if it is still open and there is a dead gap at the bottom of my screen. This is also causing the touch controls to be misaligned and I have to touch above most buttons when navigating the menus.

### The log file and images/videos

Pending but you shouldn't require it.

### Steps To Reproduce

```markdown
Start the game and tap.
```

### Expected Behavior

To work.

### Platform

```markdown
- Device model: Samsung Galaxy Tab S7+
- CPU architecture: ARM64
- Android version: Android 12
- PojavLauncher version: Latest holy_gl4es_extra build (amazing btw).
```

### Anything else?

Nope.

**Comment by GaucovyAero** [comment]
Yeah. You will need to somehow disable the navigation bar in your Android settings. Not an issue to do with pojav tho.

**Comment by simonjonnemeth** [comment]
> Yeah. You will need to somehow disable the navigation bar in your Android settings. Not an issue to do with pojav tho.

Yes it is. It wasn't an issue in previous versions.

**Comment by simonjonnemeth** [comment]
> Yeah. You will need to somehow disable the navigation bar in your Android settings. Not an issue to do with pojav tho.

This has been fixed.

**Comment by simonjonnemeth** [comment]
> > Yeah. You will need to somehow disable the navigation bar in your Android settings. Not an issue to do with pojav tho.
> 
> This has been fixed in coming updates.
