### ISSUE TITLE
[BUG] Cant move mouse when installing forge or fabric

### ISSUE THREAD

**Issue by Goodmatthew2** [PojavLauncherTeam/PojavLauncher#3048]
### Describe the bug

I cant move the cursor when I try to install forge

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8451390/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Click options under version selector
3. Launch a mod installer
```

### Expected Behavior

I expected to be able to move the cursor

### Platform

```markdown
- Device model: Samsung Galaxy A32
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Version crocus-v3_openjdk
```

### Anything else?

Video of the bug: https://youtu.be/tfT_sUeXfs8

**Comment by DovydasTEDS** [comment]
Download latest github version by clicking on actions, then click on the newest with a green tick.

**Comment by Goodmatthew2** [comment]
It worked thanks
