### ISSUE TITLE
Statement about the support of Essential, and mods that depend on it.

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#3049]
Since the Essential mod does not support this launcher, as said by the moderation team, we will not serve any issues related to Essential. If you open an issue related to the Essential mod, or a mod that depends on it, the issue will be closed as soon as it was seen. If you want Essential to support Pojav, ask them [here](https://discord.gg/FrseKwSDDy).

**Comment by Vortexexpert115** [comment]
bruh
