### ISSUE TITLE
I have a gray screen when starting any version

### ISSUE THREAD

**Issue by joaquinleiva** [PojavLauncherTeam/PojavLauncher#305]
I have a gray screen when starting any version

**Comment by khanhduytran0** [comment]
You need wait up to 5 minutes.

**Comment by GlebTiK** [comment]
I have the same issue, version: 1.16. Waited for somewhat 10 minutes. Is something wrong?

**Comment by Pairman** [comment]
I waited too, and the game started correctly (1.15.2)

**Comment by xXFrostXx1** [comment]
Pairman
You can play?

**Comment by WesleyVanNeck** [comment]
known you mey need a more powerfull phone
