### ISSUE TITLE
[BUG] Minecraft crash when the phone is locked

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#3050]
### Describe the bug

hi, I have such a problem: I go into the game, play and don't touch anyone. So they tell me to move away for a while (I lock my phone and leave, and when I come back and unlock the phone, the game crashes) The most amazing thing is that I have a top-class android phone and such a problem on every version! And this happens after the last launcher update

PLZ FIX THIS(

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8456154/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Launch any version Minecraft
3. Lock phone
4. Unlock phone
5. Minecraft Crashed
```

### Expected Behavior

I expect that the game will not crash when I unlock the device

### Platform

```markdown
- Device model: Redmi 10 4/138G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest version from github actions
```

**Comment by NotScareBat** [comment]
Same here (༎ຶ￢༎ຶ)

**Comment by ajit56** [comment]
Same (༎ຶ￢༎ຶ)

**Comment by DovydasTEDS** [comment]
When your phone screen is locked, android attempts to use less battery, that is the main reason of locking it. You could just keep your phone unlocked. This is not a pojav bug, but an android feature

**Comment by andr0d1v** [comment]
Read the topic. IT IS WRITTEN THAT THIS HAPPENED AFTER THE FIRST UPDATE GL4ES HOLY EDITION

**Comment by CriticalRange** [comment]
> Read the topic. IT IS WRITTEN THAT THIS HAPPENED AFTER THE FIRST UPDATE GL4ES HOLY EDITION

Tried this build ? It also seems to fix the issue when you close your screen and unlock it https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2148773412

**Comment by andr0d1v** [comment]
@CriticalRange this did not solve the problem

**Comment by Mathias-Boulay** [comment]
We cannot fix android killing the app after some time
