### ISSUE TITLE
Pojav Launcher 1.18 to 1.18.2 crash

### ISSUE THREAD

**Issue by MarcyIgop** [PojavLauncherTeam/PojavLauncher#3051]
### Describe the bug

when i open 1.18.2 or 1.18.1 it crash or sometimes it sayed game exited i tried all renderers and still not working
the crashlog is here
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 4/9/22, 4:28 AM
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:197)
Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.a(SourceFile:421)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (arm) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 223139104 bytes (212 MiB) / 922746880 bytes (880 MiB) up to 922746880 bytes (880 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: ARMv8 Processor rev 4 (v8l)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4601.27
	Virtual memory used (MB): 5150.27
	Swap memory total (MB): 2684.07
	Swap memory used (MB): 2218.02
	JVM Flags: 2 total; -Xms880M -Xmx880M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x ARMv8 Processor rev 4 (v8l)

### The log file and images/videos

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 4/9/22, 4:28 AM
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:197)
Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.a(SourceFile:421)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (arm) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 223139104 bytes (212 MiB) / 922746880 bytes (880 MiB) up to 922746880 bytes (880 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: ARMv8 Processor rev 4 (v8l)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4601.27
	Virtual memory used (MB): 5150.27
	Swap memory total (MB): 2684.07
	Swap memory used (MB): 2218.02
	JVM Flags: 2 total; -Xms880M -Xmx880M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x ARMv8 Processor rev 4 (v8l)

### Steps To Reproduce

```markdown
1.open app
2.launch 1.18.2
3.crash
```

### Expected Behavior

Crashing

### Platform

```markdown
- Device model: Huawei y6p
- CPU architecture: aarch32
- Android version: Android 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

1.17.1 has no hud but it hand an arm shown :/

**Comment by DovydasTEDS** [comment]
Just download the latest github version (actions -> latest with green tick -> scroll down -> click on app-debug)

**Comment by MarcyIgop** [comment]
> Just download the latest github version (actions -> latest with green tick -> scroll down -> click on app-debug)

this will work?

**Comment by MarcyIgop** [comment]
> Just download the latest github version (actions -> latest with green tick -> scroll down -> click on app-debug)

cant find it

**Comment by DovydasTEDS** [comment]
I'd recommend getting the latest github actions build. To do this, click on actions, then the latest one with a green tick. Scroll down until you see app-debug. Click on app-debug. The apk will start to download. Once downloaded, run the file and do what the package installer says.

**Comment by MarcyIgop** [comment]
> I'd recommend getting the latest github actions build. To do this, click on actions, then the latest one with a green tick. Scroll down until you see app-debug. Click on app-debug. The apk will start to download. Once downloaded, run the file and do what the package installer says.

thx it work now
