### ISSUE TITLE
[BUG] github very latest bug 

### ISSUE THREAD

**Issue by Pojavlauncherisbest** [PojavLauncherTeam/PojavLauncher#3053]
### Describe the bug

Mouse  bug   i kept the mouse on other slot it points to other slot 

https://user-images.githubusercontent.com/102723873/162557725-302a00ba-df2a-486d-b330-2934d2dca905.mp4

### The log file and images/videos

Already 

### Steps To Reproduce

```markdown
Bug
```

### Expected Behavior

Yes

### Platform

```markdown
- Device model: vivo 1820
- CPU architecture: 64
- Android version: 8.1.0
- PojavLauncher version: very latest github
```

### Anything else?

No

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
