### ISSUE TITLE
[BUG] <Short description>special scroll

### ISSUE THREAD

**Issue by Astroynm** [PojavLauncherTeam/PojavLauncher#3055]
### Describe the bug

Special scroll up& down doesn't work.

### The log file and images/videos

https://user-images.githubusercontent.com/93282609/162562159-a1bdd30f-b398-4691-abf8-fc2757549559.mp4

### Steps To Reproduce

```markdown
there are no actions to do to reproduce the bug, special scroll up & down doesn't work
```

### Expected Behavior

I expect my client's clickgui to scroll down ?

### Platform

```markdown
- Device model: Samsung S10e
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: crocus-384-de8a16e5c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
Update to the latest Actions build first.

**Comment by Astroynm** [comment]
> 

no, Has this bug been fixed already?

**Comment by DovydasTEDS** [comment]
Nope

**Comment by DovydasTEDS** [comment]
Been here for a while

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.

**Comment by Astroynm** [comment]
> Fixed on the release candidate build.

where is the download?
