### ISSUE TITLE
22w14a + not working

### ISSUE THREAD

**Issue by Illia24** [PojavLauncherTeam/PojavLauncher#3056]
### Describe the bug

Rendering Overlay

### The log file and images/videos

Mojang stupids

### Steps To Reproduce

```markdown
1. Open Pojavlauncher
2. Select 22w14a
3. Tap to play
4. Exit with code -1
```

### Expected Behavior

I knew it.

### Platform

```markdown
- Device model: Vivo
- CPU architecture: 
- Android version: 12
- PojavLauncher version: crocus
```

### Anything else?

Mojang why?????

**Comment by offbeat-stuff** [comment]
more bro give more information

**Comment by offbeat-stuff** [comment]
I am also not able to run 22w14a

**Comment by offbeat-stuff** [comment]
[Uploading latestlog.txt…]()

**Comment by offbeat-stuff** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8456835/latestlog.txt)

**Comment by DovydasTEDS** [comment]
Just download the latest github version (actions -> latest with green tick -> scroll down -> click on app-debug)

**Comment by ghost** [comment]
That's a fabric issue.

**Comment by ghost** [comment]
Also make sure you have the assets-v0.zip that also has the rendertype_translucent in it or in simple terms, this one. [Patched Shader Program](https://github.com/PojavLauncherTeam/PojavLauncher/files/8098212/assets-v0.zip) (Unsure if it is needed, but for now use it with gl4es.)

**Comment by simonjonnemeth** [comment]
> Also make sure you have the assets-v0.zip that also has the rendertype_translucent in it or in simple terms, this one. [Patched Shader Program](https://github.com/PojavLauncherTeam/PojavLauncher/files/8098212/assets-v0.zip) (Unsure if it is needed, but for now use it with gl4es.)

The latest GL4ES build doesn't need to be patched.

**Comment by Illia24** [comment]
Oh sorry, its im dumb just im select wrong patch.

**Comment by simonjonnemeth** [comment]
> Oh sorry, its im dumb just im select wrong patch.

As above, the crocus build is very outdated. You should try the latest GL4ES HOLY EDITION build from the 'Actions' tab, always the first one from the top with a green tick. The shader patch will no longer be required if your device supports it but Optifine never hurts. It also fixes lots of other things as well.
