### ISSUE TITLE
[BUG] 1.18.2 Does Not Work

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3058]
### Describe the bug

Application/Game Exited With Code - 1
![Screenshot_20220409-163513_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/99503027/162574394-d672cccd-d597-4c07-9fec-df3a5ea6a498.jpg)

### The log file and images/videos

![Screenshot_20220409-162639_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/99503027/162574317-fbf9c85c-7b59-42bc-9cb4-2b1b9935ddd7.jpg)

### Steps To Reproduce

```markdown
1. START POJAVLAUNCHER 
2. OPEN 1.18.2
3. AUTOMATICALLY CRASHES
```

### Expected Behavior

I EXPECTED THE GAME TO LAUNCH 1.18.2

### Platform

```markdown
- Device model: Samsung Galaxy Tab S6 Lite 64GB One Ui:3.1Model Number SM-P610
- CPU architecture:aarch64 
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

Same With 1.17

**Comment by kuzy21** [comment]
Wtf is wrong with ur pojavlauncher

**Comment by kuzy21** [comment]
It say that u are trying to open 1.12.2

**Comment by offbeat-stuff** [comment]
use the latest build
this one
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2141723119
beware this is a beta and crashes can happen

**Comment by ghost** [comment]
> It say that u are trying to open 1.12.2

I crashed on 1.18 so i tried 1.12 if it crashes but it works for 1.1.0-1.16.5

**Comment by ghost** [comment]
> use the latest build this one https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2141723119 beware this is a beta and crashes can happen

Dosent Work With That too
