### ISSUE TITLE
[BUG] latest build always crashing!

### ISSUE THREAD

**Issue by MArnelPH** [PojavLauncherTeam/PojavLauncher#3059]
### Describe the bug

Just force close when press play.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8457100/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojav launcher
Slecet any version
Press play
Auto home screen:/
```

### Expected Behavior

I see something saying in the ingame LOG like (dynamic array not found)

### Platform

```markdown
- Device model: oppo a12 3/32
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: latest build
```

### Anything else?

Any suggestions?

**Comment by MArnelPH** [comment]
THIS IS THE LOG KEEP SAYING AND JUST FORCE CLOSE!  ![Screenshot_2022-04-09-22-28-20-44](https://user-images.githubusercontent.com/82855785/162578544-cb7bccac-145e-4a98-9060-8e26ea8261ff.jpg)

**Comment by Mathias-Boulay** [comment]
ah yes, latest build. totally a version number.

**Comment by WesleyVanNeck** [comment]
> THIS IS THE LOG KEEP SAYING AND JUST FORCE CLOSE! ![Screenshot_2022-04-09-22-28-20-44](https://user-images.githubusercontent.com/82855785/162578544-cb7bccac-145e-4a98-9060-8e26ea8

> THIS IS THE LOG KEEP SAYING AND JUST FORCE CLOSE! ![Screenshot_2022-04-09-22-28-20-44](https://user-images.githubusercontent.com/82855785/162578544-cb7bccac-145e-4a98-9060-8e26ea8261ff.jpg)

stop with capslock

**Comment by kuzy21** [comment]
Remember the newest build are still in beta so it will have some problems

**Comment by Mathias-Boulay** [comment]
he's using a non mainline build from what I can tell.
Closing
