### ISSUE TITLE
Na versao de 2022 quando tenta entra no forge 1.12.2 aparece o aplicativo fechou pelo codigo 1[BUG] <Short description>

### ISSUE THREAD

**Issue by Marcelo64y** [PojavLauncherTeam/PojavLauncher#3061]
### Describe the bug

Na versão 1.12.2 meu celular Samsung A02s

### The log file and images/videos

E8di8d

### Steps To Reproduce

```markdown
1.incia o qualquer forge
2.e parece o error
```

### Expected Behavior

O jogo fechou pelo o error do código 1

### Platform

```markdown
- Device model:Samsung A02s/32G 3giga ram
- CPU architectur  aarch32
- Android version: 11
- PojavLauncher version: de 2022
```

**Comment by offbeat-stuff** [comment]
E8di8d
That does not look like a word
Can you speak english

**Comment by Wilsiontavailable** [comment]
Ga bisa download 1.18.2

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
