### ISSUE TITLE
High use of cpu

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#3065]
### Is this request related to a bug?

You should use GPU for rendering . It will make less lag i think

### Describe the request.

Make GPU use because GPU is not in use

**Comment by artdeell** [comment]
GPU is used by PojavLauncher. But Minecraft is more intensive on the CPU, and not on the GPU, so that's why CPU is more loaded.

**Comment by ajit56** [comment]
Okay sir thank you
