### ISSUE TITLE
File opener

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#3067]
### Is this request related to a bug?

You should add file opener

### Describe the request.

It will help us to install datapacks , Shaders , Resource packs.

### Anything else?

Nope

**Comment by TwoKrazy** [comment]
There are plenty of third-party file explorers available on the Play Store for this purpose, though I can see why you'd want it on the app itself rather than having to install another app. If you do want a file explorer for you to install mods/resource packs/etc. then I recommend CX file explorer. It's free and you'll be able to access the folders you need. Just make sure to show the hidden files, since the .minecraft folder is marked as hidden due to the period in front of the folder name.

**Comment by simonjonnemeth** [comment]
> There are plenty of third-party file explorers available on the Play Store for this purpose, though I can see why you'd want it on the app itself rather than having to install another app. If you do want a file explorer for you to install mods/resource packs/etc. then I recommend CX file explorer. It's free and you'll be able to access the folders you need. Just make sure to show the hidden files, since the .minecraft folder is marked as hidden due to the period in front of the folder name.

	
Solid Explorer is excellent as well.

**Comment by ajit56** [comment]
But i want install datapacks without creating world

**Comment by simonjonnemeth** [comment]
> But i want install datapacks without creating world

I mean you create a world once your already in game so that's pretty much what we do already. You do understand how the .minecraft folder works?

**Comment by simonjonnemeth** [comment]
> There are plenty of third-party file explorers available on the Play Store for this purpose, though I can see why you'd want it on the app itself rather than having to install another app. If you do want a file explorer for you to install mods/resource packs/etc. then I recommend CX file explorer. It's free and you'll be able to access the folders you need. Just make sure to show the hidden files, since the .minecraft folder is marked as hidden due to the period in front of the folder name.

It would be nice to have options to select resource packs within the launcher and have it automatically install them for you rather than all the busywork you have to do now manually moving files around. I think that is what the OP is suggesting.

**Comment by ajit56** [comment]
> > There are plenty of third-party file explorers available on the Play Store for this purpose, though I can see why you'd want it on the app itself rather than having to install another app. If you do want a file explorer for you to install mods/resource packs/etc. then I recommend CX file explorer. It's free and you'll be able to access the folders you need. Just make sure to show the hidden files, since the .minecraft folder is marked as hidden due to the period in front of the folder name.
> 
> It would be nice to have options to select resource packs within the launcher and have it automatically install them for you rather than all the busywork you have to do now manually moving files around. I think that is what the OP suggesting.

Good idea

**Comment by ajit56** [comment]
@Mathias-Boulay

**Comment by Mathias-Boulay** [comment]
Meh
