### ISSUE TITLE
Update ui look like official minecraft launcher ui and backgraound. Pls. Update it for google play store pojav.

### ISSUE THREAD

**Issue by Ranpo2008** [PojavLauncherTeam/PojavLauncher#3068]
### Is this request related to a bug?

Update ui look like official minecraft launcher ui and backgraound. Pls. Update it for google play store pojav.

### Describe the request.

Update ui look like official minecraft launcher ui and backgraound. Pls. Update it for google play store pojav.

### Anything else?

Update ui look like official minecraft launcher ui and backgraound. Pls. Update it for google play store pojav.

**Comment by kuzy21** [comment]
If they update it to look like the official ui, they need to ask minecraft or they get sued.

**Comment by kuzy21** [comment]
Close this issue

**Comment by simonjonnemeth** [comment]
No, it needs its own identity. It already looks like a half baked copy of the official launcher. I would hope they would come up with their own UI eventually that's further from the Minecraft official launcher.

**Comment by Mathias-Boulay** [comment]
@Ranpo2008 
I follow the point of view of @simonjonnemeth here.
Also yes, pojav will get updated for play store when it is stable. We have patreon if you can help us dedicate time to develop it
