### ISSUE TITLE
Try including some opengl that will not glitch the textures in 1.18.1

### ISSUE THREAD

**Issue by miggythewriter** [PojavLauncherTeam/PojavLauncher#3069]
### Is this request related to a bug?

Yes, I loaded the latest developer build 04/10/22 and using opengl es 4, when loaded a server/world the textures would glitch out 

### Describe the request.

Make something to prevent textures from glitching out

**Comment by offbeat-stuff** [comment]
there is no opengl es 4,you should use gl4es holy edition
