### ISSUE TITLE
latest snapshot

### ISSUE THREAD

**Issue by blob83** [PojavLauncherTeam/PojavLauncher#3070]
### Describe the bug

its crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8461365/latestlog.txt)
pls help (deez nuts)

### Steps To Reproduce

```markdown
just start with preamium account
```

### Expected Behavior

game launch 

### Platform

```markdown
- Device model: SM-A115F 
- CPU architecture:32 bits 
- Android version: adroid 11
- PojavLauncher version:latest version
```

### Anything else?

e

**Comment by kuzy21** [comment]
No your a kid stuck in 2016, so not help for you (dezznutzz) don't say that

**Comment by kuzy21** [comment]
Nvm just joking anyways, what snapshot is it

**Comment by offbeat-stuff** [comment]
22w14a the same issue has already been submitted

**Comment by artdeell** [comment]
Should be fixed with holy gl4es
