### ISSUE TITLE
Can you Recreate Mcinabox new version

### ISSUE THREAD

**Issue by Gabbyph12** [PojavLauncherTeam/PojavLauncher#3071]
### Describe the request.

Plss recreate Mcinabox we missed it
I know you don't making any Mcinabox updates but plss recreate it

**Comment by TWTommyee** [comment]
https://github.com/Tungstend/HMCL-PE#hmcl-pe

**Comment by InfiniXDerg** [comment]
![image](https://user-images.githubusercontent.com/75786233/162704738-b92b9aa6-761a-46ad-8adc-f155bda42719.png)

**Comment by Ang425** [comment]
Pojavlauncher is way better

**Comment by Py10lolz** [comment]
LMFAO

**Comment by ghost** [comment]
LOL

**Comment by kuzy21** [comment]
U ARE STUPID FOR SAYING MCINABOX IN A POJAVLAUNCHER  ISSUE, UNWORTHY SOUL

**Comment by Gabbyph12** [comment]
I thought the designer of Mcinabox is Mathias boulay
