### ISSUE TITLE
[BUG] Minecraft crashes when the phone is unlocked (REPOST)

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#3073]
### Describe the bug

hi, I have such a problem: I go into the game, play and don't touch anyone. So they tell me to move away for a while (I lock my phone and leave, and when I come back and unlock the phone, the game crashes) The most amazing thing is that I have a top-class android phone and such a problem on every version! And this happens after first update gl4es holy edition and subsequent versions after it

PLZ FIX THIS(

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8464508/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Launch any version Minecraft
3. Lock phone
4. Unlock phone
5. Minecraft Crashed
```

### Expected Behavior

I expect that the game will not crash when I unlock the device

### Platform

```markdown
- Device model: Redmi 10 4/138G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest version from github actions
```

**Comment by ghost** [comment]
I think it's because the memory. Try putting the memory down to 500 or so and try again. It's not a permanent fix, but I've found that a low memory can fix the crashing.

**Comment by Ang425** [comment]
Dont lock your phone.A lock phone will try and close your background apps

**Comment by ghost** [comment]
It's a by-product of Android preserving battery.

**Comment by DovydasTEDS** [comment]
Just close this issue.

**Comment by WesleyVanNeck** [comment]
> ### Describe the bug
> hi, I have such a problem: I go into the game, play and don't touch anyone. So they tell me to move away for a while (I lock my phone and leave, and when I come back and unlock the phone, the game crashes) The most amazing thing is that I have a top-class android phone and such a problem on every version! And this happens after first update gl4es holy edition and subsequent versions after it
> 
> PLZ FIX THIS(
> 
> ### The log file and images/videos
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8464508/latestlog.txt)
> 
> ### Steps To Reproduce
> ```gfm
> 1. Start Pojav launcher
> 2. Launch any version Minecraft
> 3. Lock phone
> 4. Unlock phone
> 5. Minecraft Crashed
> ```
> 
> ### Expected Behavior
> I expect that the game will not crash when I unlock the device
> 
> ### Platform
> ```gfm
> - Device model: Redmi 10 4/138G
> - CPU architecture: aarch64
> - Android version: 12
> - PojavLauncher version: latest version from github actions
> ```
> 
> ### Anything else?
> _No response_

@artdeell  close the issue reposting a issue ain't allowed

**Comment by andr0d1v** [comment]
@Smokeybear12 and if I have version 1.18.2?

**Comment by ghost** [comment]
Huh? 1.18 should launch with less memory. It will just be more laggy. Also reposting issues isn't allowed @artdeell please close it.

**Comment by andr0d1v** [comment]
@Smokeybear12 And I don't want to lag

**Comment by andr0d1v** [comment]
@artdeell plz fix this(

**Comment by ghost** [comment]
Stop reposting issues

**Comment by andr0d1v** [comment]
@Smokeybear12 you don't understand. Because of this problem, I can't safely play Minecraft java.

**Comment by ghost** [comment]
What do you mean safe?? It's pretty much the same safety as running the launcher.

**Comment by andr0d1v** [comment]
@Smokeybear12 I have to constantly block my phone at school. And when I unlock it, it crashes the game!

**Comment by ghost** [comment]
If you're at school you probably shouldn't be playing anyway. The Android battery optimization system works to prevent background usage. If you don't want it to crash, start the game with low memory and it is less likely to stop, however it still will.

**Comment by kuzy21** [comment]
Just understand that every phone does that if u lock it, it's ur phone that's doing that also get a better phone, I get 200 fps on 1.18.2 just close this and stop being a bitch

**Comment by kuzy21** [comment]
Also smoky bear can you give me the permission of helping people with pojavlauncher, I will help and I will do good, no need to pay because you coders are amazing, so what do u think  :)

**Comment by andr0d1v** [comment]
![Screenshot_2022-04-20-03-54-05-152_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87223939/164125559-8b11b0ec-d9f2-4f2e-8f95-873d6d263834.jpg)
I have found a solution to my problem. It was because of this function that I was crashing. I disabled it and now the game does not crash.

**Comment by kuzy21** [comment]
Close this issue
