### ISSUE TITLE
Не показывает язык 1.16.X для смены

### ISSUE THREAD

**Issue by Yoorooh47** [PojavLauncherTeam/PojavLauncher#3074]
### Describe the bug

Помогите кто-нибудь не меняется язык на версии 1.16.X

### The log file and images/videos

![Screenshot_20220411-220410_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103455738/162815726-411eaf2c-b6da-4e21-a181-3e7bef297b2f.jpg)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

Я ожидаю нвыбор языков а там пусто

### Platform

```markdown
- Device model: Samsung a70 6/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version:[Последняя версия || версия 3.3.1.1_rel_20210206]
```

### Anything else?

.

**Comment by andr0d1v** [comment]
Вау, впервые вижу русский запрос в гитхабе. Вы скачали все файлы игры?
