### ISSUE TITLE
[BUG] First boot has an upside down text notice

### ISSUE THREAD

**Issue by Deliphin** [PojavLauncherTeam/PojavLauncher#3075]
### Describe the bug

It feels like this is an april fools joke, but it's now April 11th, not even Reddit is still doing april fools. So I'm guessing this is one but the dev forgot to turn it off.

I just installed PojavLauncher for the first time, not even logged in yet, (latestlog.txt not even generated yet), and I'm presented with a notice with all upside down text. It's clearly using an upside down "font", as the notice itself is right side up, shown by the OK button being at the proper bottom.

### The log file and images/videos

![Phone screenshot](https://user-images.githubusercontent.com/14265753/162827547-80a6c251-23f2-47ab-bc1a-66f0744dd4cd.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher for the first time
2. Get automatically presented this notice
```

### Expected Behavior

I expect the notice to be presented in a way I can read without flipping my phone.

### Platform

```markdown
- Device model: Samsung Galaxy S10e
- CPU architecture: ARM64, I think
- Android version: 12
- PojavLauncher version: Whatever is newest on the Google Play store
```

**Comment by DovydasTEDS** [comment]
Download the latest github actions version, as the google play version is very outdated.

**Comment by raphaelko62** [comment]
this is just storage changes, not a bug. they're saying that on android 10 or higher, the launcher folder is no longer on the main internal storage or sd card. instead, its now in android/data/net.kdt.pojavlaunch and if you want the .minecraft folder, install zarchiver and in the app settings, select "show hidden files"

**Comment by Deliphin** [comment]
> this is just storage changes, not a bug. they're saying that on android 10 or higher, the launcher folder is no longer on the main internal storage or sd card. instead, its now in android/data/net.kdt.pojavlaunch and if you want the .minecraft folder, install zarchiver and in the app settings, select "show hidden files"

You're not understanding. The issue I'm reporting isn't that the alert appears, the issue is that the text is upside down.

Look at the orientation of the game behind, and look at the orientation of the alert, and look at the orientation of the text within the alert.

**Comment by raphaelko62** [comment]
that's a way of not getting google to remove the app, because this is
technically breaking the rules.

**Comment by Deliphin** [comment]
Ah, alright, that makes sense.
