### ISSUE TITLE
[F-Req] Add option to choose Minecraft Directory (REPOST)

### ISSUE THREAD

**Issue by DovydasTEDS** [PojavLauncherTeam/PojavLauncher#3076]
### Describe the request.

Title, #2978

**Comment by kuzy21** [comment]
The app will need more storage for each person you make

**Comment by DovydasTEDS** [comment]
If you read the mentioned issue, #2978, you would have noticed it mainly request different profiles to have different mods

**Comment by DovydasTEDS** [comment]
Check #2978
