### ISSUE TITLE
Game Directory option not visible.

### ISSUE THREAD

**Issue by DovydasTEDS** [PojavLauncherTeam/PojavLauncher#3078]
### Describe the bug

I cannot see a prompt / option to change the game directory for a profile. Apparently its in the game.

### The log file and images/videos

![Screenshot_20220412-182355_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/61357186/163019312-0a6afefa-146b-495c-abf9-95c44f112069.png)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Login
3. Create profile
4. No input field
```

### Expected Behavior

I expect to have a field / prompt to choose the game directory.

### Platform

```markdown
- Device model: SM-A325
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: Latest GitHub (holy gl4es)
```

### Anything else?

Thank you all the PojavLauncher contributors for making this app a thing!

**Comment by kuzy21** [comment]
It's each time u change the profile

**Comment by DovydasTEDS** [comment]
Still uses the same directory, no matter what profile I use.

**Comment by DovydasTEDS** [comment]
Thank you so much Pojav devs!
