### ISSUE TITLE
[BUG] 1.12.2 forge crash when opening single player world!

### ISSUE THREAD

**Issue by MArnelPH** [PojavLauncherTeam/PojavLauncher#3079]
### Describe the bug

This happened so many times that i cant play forge :/

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8476717/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojav launcher
Play forge 1.12.2
Opening world
Kicks me out to home screen :/
```

### Expected Behavior

The game said *shuttingdown internal server*

### Platform

```markdown
- Device model: oppo a12 3/32
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: cocrus/latestbuild
```

### Anything else?

Nothin.

**Comment by khanhduytran0** [comment]
You need to have a look at #2679
