### ISSUE TITLE
Faire marcher tout les bouton des manettes xbox

### ISSUE THREAD

**Issue by felixlechatchat** [PojavLauncherTeam/PojavLauncher#3080]
### Is this request related to a bug?

Bonjour ,sur pojav launcher on peux utiliser une manette ceux-ci marche bien mais j'ai remarqué que les boutons suivant ne marchais pas  :
-Les boutons LT ,RT ,LB,RB
-Les bouton des joystick 
Et sa serai bien que les boutons  A,B,Y,X ont tous une touche différente!

### Describe the request.

J'aimerais pouvoir jouer a pojav launcher avec tous les bouton de la manettes sans problème .

Cordialement.

**Comment by Mathias-Boulay** [comment]
Well, that's for a bug report.
however, you forgot to specify the version of pojav on which the bug was encountered

**Comment by felixlechatchat** [comment]
The last on app store google

**Comment by Mathias-Boulay** [comment]
Yeah, quite outdated as expected.

**Comment by felixlechatchat** [comment]
If you prefer the August 31, 2021 version

**Comment by Mathias-Boulay** [comment]
so, crocus_v3 
Well, yeah this is fixed on dev builds, don't mind me closing the issue
