### ISSUE TITLE
Sodium crashed

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#3082]
### Describe the bug

Crashed after connecting to world

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8477870/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.load fabric with Sodium 1.16.5 and fabric api
3.join world
Crashed !!!
```

### Expected Behavior

I want to play with Sodium this will make game less laggy

### Platform

```markdown
- Device model: samsung galaxy m31
- CPU architecture: aarch 64
- Android version: 11
- PojavLauncher version: play store version
```

**Comment by Cube5x59999** [comment]
disable complex vertex format at settings

**Comment by ajit56** [comment]
Thanks sir
