### ISSUE TITLE
Block overlay not showing 1.18.2

### ISSUE THREAD

**Issue by BNaise** [PojavLauncherTeam/PojavLauncher#3085]
### Describe the bug

I don't know

### The log file and images/videos

Block outline not showing

### Steps To Reproduce

```markdown
1.i launch pojavlauncher
2.load the correct resource pack assets-v0.zip format 8
3.but block outlines still not showing
```

### Expected Behavior

I expect block outline was shown but not

### Platform

```markdown
- Device model: Redmi Note 7 Pro
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206]
```

**Comment by BNaise** [comment]
Please help🥺🥺🥺🥺🥺🥺🥺😭😭😭😭😭😭

**Comment by ghost** [comment]
Update your launcher to the latest action build.

**Comment by Cube5x59999** [comment]
try other renderer like zink or _virglrenderer_

**Comment by offbeat-stuff** [comment]
if you use assets-v0 block outline will not show use gl4es holy

**Comment by BNaise** [comment]
I fixed it my self thanks
