### ISSUE TITLE
Mouse Glitch When Enable 120hz

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#3086]
### Describe the bug

I Can't Play With Mouse and keyboard When This Happened To Me i Want To Play With 120hz Just Like Bedrock Edition

### The log file and images/videos

https://user-images.githubusercontent.com/79517194/163199438-24ab50b0-b037-41e6-bd11-a95dadae16c0.mp4

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Enter Any World
3.Mouse Doesn't Function Correctly
```

### Expected Behavior

1.Start PojavLauncher
2.Enter Any World
3.Play Normally

### Platform

```markdown
- Device model: Poco X3 Pro
- CPU architecture: aarch64 
- Android version: 12
- PojavLauncher version: Latest Google Play Build
```

**Comment by EnderBrine99FOX** [comment]
And The Same Happened To Me In The V3_openjdk Build (Github Build) But With Keyboard (it's Spam The Key i Use)

**Comment by EnderBrine99FOX** [comment]
i Discovered That This Issue occur when i turn my screen into 120hz So I'm Going To change The Bug Report

**Comment by Mathias-Boulay** [comment]
I really feel like I'm going to kill miui at one point.

**Comment by EnderBrine99FOX** [comment]
fr😤😡

**Comment by artdeell** [comment]
Fixed on latest builds or with a MIUI update, idk

**Comment by EnderBrine99FOX** [comment]
My MIUI is 13.0.3 Its Fixed in What Version?

**Comment by GaucovyAero** [comment]
> My MIUI is 13.0.3 Its Fixed in What Version?

No idea, but removing MIUI is going to result in this mouse issue fixing itself and your phone will also yield more performance.
