### ISSUE TITLE
[BUG] <Extreme lag forge>

### ISSUE THREAD

**Issue by JustGame1186** [PojavLauncherTeam/PojavLauncher#3087]
### Describe the bug

![IMG_20220414_064243](https://user-images.githubusercontent.com/83933901/163287698-51c7b7e5-4e94-47e8-9244-8f864562c8d4.JPG)

Idk what's the problem but forge is lagging on 1.16.5 and lower, even without mod for datapack

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8485298/latestlog.txt)
 
Here's the latestlog

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Select Forge 1.16.5
3. Minecraft is running, everything fine
4. Create new world, and 1-5 FPS/s
```

### Expected Behavior

I just want to try some mods (:

### Platform

```markdown
- Device model: Vivo y95
- CPU architecture: aarch64
- Android version: 8
- PojavLauncher version: Crocus-327-v3_OpenJDK
```

**Comment by kuzy21** [comment]
Well it's lag for u

**Comment by kuzy21** [comment]
And can't be fixed
