### ISSUE TITLE
 Forge Support 1.17+

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#3088]
### Is this request related to a bug?

 no but probably it is

### Describe the request.

Can you guys make Forge 1.17-1.18.2 support Pojav launcher ik its gonna take a long time to do but i hope on future updates of Pojav launcher Forge 1.17-1.18.2 will support it

**Comment by ghost** [comment]
bug

**Comment by artdeell** [comment]
Added in latest builds
