### ISSUE TITLE
Mod installer bug (not able to move virtual mouse)

### ISSUE THREAD

**Issue by Comy112** [PojavLauncherTeam/PojavLauncher#3089]
### Describe the bug

So, as you know that samsung users can't download OptiFine, Forge, Fabric, LabyMod and other mod installers. How about you make Pojav more optimized? I, and probably many other people are struggling to play as Samsung users. If that is possible in any way, it would be really good.

### The log file and images/videos

![Screenshot_20220414-183738_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/102830774/163434289-b84f8f1b-c6fa-4865-820a-af425c051b21.jpg)

### Steps To Reproduce

```markdown
1. Open Pojav
2. Click "Download Mod Installer"
3. Select mod installer
4. I can't move cursor
```

### Expected Behavior

i expected to be able to download optifine. But it certainly didn't happen.

### Platform

```markdown
- Device model: Samsung A12 6/128
- CPU architecture: 8x ARM Cortex-A55 @ 2002 MHz
- Android version: 11
- PojavLauncher version: downloaded latest from Play Store
```

**Comment by jorgieee** [comment]
Use the latest built on github, go on github and got to actions, press the latest build with a check and download apk, must be logged in to github in order ro get build
