### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by Stalin7002** [PojavLauncherTeam/PojavLauncher#3090]
### Describe the bug

Произошёл сбой приложения/игры с кодом -1

### The log file and images/videos

https://user-images.githubusercontent.com/103672635/163440353-01a7190e-bf4c-4876-a8d6-f5dcbc44e4bd.mp4

![Screenshot_2022-04-15-03-15-33-21_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/103672635/163440361-8309ffbe-aee9-4f52-9518-7f8545c9f6db.jpg)

### Steps To Reproduce

```markdown
Все видно на видео
```

### Expected Behavior

Я ожидал что игра запуститься 

### Platform

```markdown
- Device model: Realme 7 Pro
- CPU architecture: 128G
- Android version: aarch64
- PojavLauncher version: последняя версия
```

**Comment by GaucovyAero** [comment]
Your PojavLauncher is outdated. Update to the latest one here in GitHub Actions.

**Comment by Stalin7002** [comment]
Не чего не дало

**Comment by Stalin7002** [comment]
> Ваш PojavLauncher устарел. Обновите до последней версии здесь, в GitHub Actions.

Скачал новый лаунчер 3.3.1.1 и проблема не исправилась
