### ISSUE TITLE
Add other download sources

### ISSUE THREAD

**Issue by q20100321** [PojavLauncherTeam/PojavLauncher#3091]
### Is this request related to a bug?

no

### Describe the request.

You can add download sources similar to mcbbs and bmcl

### Anything else?

This can be some regions or countries fast download games

**Comment by DovydasTEDS** [comment]
Wouldn't work well as they have to abide by Minecraft's EULA

**Comment by YaoSiQian** [comment]
> Wouldn't work well as they have to abide by Minecraft's EULA

hmmm
These sources all said they didn't give copies
They have just done a mirror to help player to download resources from Mojang's server

**Comment by YaoSiQian** [comment]
I have found something about the eula from a developer of an unofficial Minecraft launcher
> 自行开发的启动器是否属于Mojang创建/提供的内容？

> 如果自行开发的启动器 不属于 Mojang所创建/提供的内容，则PCL也并不构成违反EULA中所指的“试图通过我们创建的任何内容赚钱”。

> 如果PCL 属于 Mojang创建/提供的内容，则以下列出的提供离线验证模式和分发提供Minecraft游戏的副本两项违反EULA的行为也不属于违反了EULA，因为在此定义下，PCL属于Mojang创建/提供的内容，而Mojang创建/提供的内容提供此行为不属于违反了Mojang的EULA。
