### ISSUE TITLE
I can't log in to my account [BUGGED ACCOUNT]

### ISSUE THREAD

**Issue by LightedBreeze** [PojavLauncherTeam/PojavLauncher#3094]
### Describe the bug

No example

### The log file and images/videos

That issue and PojavLauncher scammed me.

### Steps To Reproduce

```markdown
?
```

### Expected Behavior

?

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No.

**Comment by artdeell** [comment]
You literally filled out nothing. What the hell are we supposed to do with your problem if you didn't provide enough info?

**Comment by kuzy21** [comment]
Bruh what kinda crak r u on

**Comment by kuzy21** [comment]
Get the latest build

**Comment by JustJoshinDev** [comment]
Man, you can't expect anyone to help you if you don't tell us what's wrong.
