### ISSUE TITLE
[F-Req] <more people to know>

### ISSUE THREAD

**Issue by villager1314** [PojavLauncherTeam/PojavLauncher#3095]
### Describe the request.

I'd like to call it the most powerful of my world's boosters on mobile phones, and pojav brought me back from my personal computer to my mobile device. Not only did I experience happiness here, but the developer's hard work (and even more than 99% of the projects on git), if the MC doesn't die, I hope pojav (with Mio boat (if you can develop it together) never dies！

**Comment by villager1314** [comment]
thanks to pojav，thanks to developer！

**Comment by offbeat-stuff** [comment]
You should not use the issues tab for non issues even for thanking the devs

**Comment by Mathias-Boulay** [comment]
Hmmm, that's always nice to see someone expressing his happiness for the project.
It kinda warms my heart a bit 😄 
If you want to help us a bit, there is the https://www.patreon.com/pojavlauncher

That being said, this is the space for issues 👀
