### ISSUE TITLE
[BUG] Forge 1.12.2 crash with: "Game exited" 

### ISSUE THREAD

**Issue by EnderPluser** [PojavLauncherTeam/PojavLauncher#3096]
### Describe the bug

when i try to open Forge 1.12.2 version, it crash immediacy with code 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8501007/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher 
2.Chose Forge 1.12.2 version
3.Launch it
4.Crash with messages: Game exited
```

### Expected Behavior

i expected the game to launches 

### Platform

```markdown
- Device model: Samsung A30
- CPU architecture: Arm64 (aarch64)
- Android version: 10
- PojavLauncher version: Latest build from github action
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
You are launching 1.12.2 with Java 17, that's the issue. Only 1.17 upwards needs J17.

**Comment by EnderPluser** [comment]
> You are launching 1.12.2 with Java 17, that's the issue. Only 1.17 upwards needs J17.

**Comment by EnderPluser** [comment]
but why does the auto generated Forge profile use java17 though????

**Comment by artdeell** [comment]
Auto generated Forge profile doesn't use any Java version by default. But you probably set java 17 as the launcher default, so Pojav tried to start it with Java 17
