### ISSUE TITLE
Distant horizons mod crashed 

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#3097]
### Describe the bug

Application exited with code 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8501123/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install distant horizons in fabric 1.16.5
2.start Minecraft 
3. Join world 
4.crashed !
```

### Expected Behavior

I expect to run game with distant horizons mod

### Platform

```markdown
- Device model: samsung galaxy m31
- CPU architecture: aarch 64
- Android version: 12
- PojavLauncher version: crocus-449-6060e8bdc-v3_openjdk
```

**Comment by artdeell** [comment]
PojavLauncher's GL support only allows up to OpenGL 2.1, with extra OpenGL 3.3 shader support for Minecraft 1.17.x and newer. Distant Horizons requires OpenGL 3.2, so it's not supported.

**Comment by ajit56** [comment]
Okay
