### ISSUE TITLE
[BUG] KeyMapper Support

### ISSUE THREAD

**Issue by PadMadoff** [PojavLauncherTeam/PojavLauncher#3098]
### Describe the bug

For some reason, it is no longer possible to use the keymapper when playing through PoJav.
Keymapper is a program that allows you to change input methods for some buttons (Volume button → KEYCODE_F5)
In older versions, I used this program to play the game with the keyboard and mouse without problems. Of course, this can still be done now, but the problem is in the keyboard shortcuts that cannot be disabled. (ctrl+space = switch language = the player stops moving)

### The log file and images/videos

![Screenshot_2022-04-18-00-01-48-794_io github sds100 keymapper ci](https://user-images.githubusercontent.com/87415329/163731888-623e6ead-a06a-4b32-84e3-7c6377ad37ea.jpg)

### Steps To Reproduce

```markdown
1. Download KeyMapper in Google Play.
2. Change some buttons to some input methods (Volume+ → KEYCODE_Q)
3. Open Minecraft through PoJav and go to the some world.
4. Try press changed button.
5. Didn't work!
```

### Expected Behavior

I hope they add button reading without opening the on-screen keyboard.

### Platform

```markdown
- Device model: POCO X3 PRO (Rooted)
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-488-8b5efa9a6-v3_openjdk
```

**Comment by GaucovyAero** [comment]
Well, this can't be resolved as far as I'm aware...

**Comment by Mathias-Boulay** [comment]
Current dev builds should support keymappers
