### ISSUE TITLE
Ffmpeg

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#3099]
### Is this request related to a bug?

Add ffmpeg mod support

**Comment by vittogialli** [comment]
ffmpeg isn't even a mod

**Comment by GaucovyAero** [comment]
> ffmpeg isn't even a mod

he probably meant replay mod but his London broke

**Comment by kuzy21** [comment]
Ok.....

**Comment by ajit56** [comment]
So how to get MP4 video with it?

**Comment by vittogialli** [comment]
Replay mod works fine with me (Fabric 1.18.2) without downloading ffmpeg or anything else, so you probably messed something up while installing it

**Comment by ajit56** [comment]
How to get MP4 file

**Comment by ajit56** [comment]
@vittogialli

**Comment by Mathias-Boulay** [comment]
#2572
