### ISSUE TITLE
Optifine still doesn't works... but will it works? 

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#31]
I saw on YouTube that Optifine still does not work.
But will it even works? When I start OptiFine 1.7.10 and I see the mojang logo, after a while I have a crash ... so my question is:
Can I play the optifine version in Preview 8b1?
And if not then:
Will it be fixed / refined?

**Comment by khanhduytran0** [comment]
Some OptiFine will not playable, you can try with other versions 1.8 to 1.11

**Comment by khanhduytran0** [comment]
Try v3 for stable optifine
