### ISSUE TITLE
TLauncher

### ISSUE THREAD

**Issue by AmogusBebrikys** [PojavLauncherTeam/PojavLauncher#3100]
### Describe the request.

I beg you, add TLauncher support (sorry for the mistakes, I use Google Translate)

**Comment by ajit56** [comment]
What

**Comment by DovydasTEDS** [comment]
Stop pirating the game. Did you know if you tick offline mode you can play without paying? You should consider paying for the game.

**Comment by DovydasTEDS** [comment]
@AmogusBebrikys close this issue

**Comment by kuzy21** [comment]
He should what a pirate

**Comment by Iarkont** [comment]
> Stop pirating the game. Did you know if you tick offline mode you can play without paying? You should consider paying for the game.

And if, for example, there is not enough money for the game but you really want to play it? Or in some countries the sale of game licenses has ceased and therefore players from such countries pirating. Maybe piracy is prohibited in your country, but in many others countries are neutral about this and do not prohibit piracy for personal use.

**Comment by DovydasTEDS** [comment]
You could just tick the 'Offline Mode' box and select a username. I was just advising you pay for the game as you get many more features and proper support.

**Comment by GaucovyAero** [comment]
> > Stop pirating the game. Did you know if you tick offline mode you can play without paying? You should consider paying for the game.
> 
> And if, for example, there is not enough money for the game but you really want to play it? Or in some countries the sale of game licenses has ceased and therefore players from such countries pirating. Maybe piracy is prohibited in your country, but in many others countries are neutral about this and do not prohibit piracy for personal use.

Just buy a PC then. If you know how to tweak, a 2 core Pentium D, 2 gigs of ram and a 128mb gpu (5 euros for the whole pc) is totally fine, it will yield you about 120fps stable on 1.7.10 Lunar Client.

**Comment by Iarkont** [comment]
> > > Stop pirating the game. Did you know if you tick offline mode you can play without paying? You should consider paying for the game.
> > 
> > 
> > And if, for example, there is not enough money for the game but you really want to play it? Or in some countries the sale of game licenses has ceased and therefore players from such countries pirating. Maybe piracy is prohibited in your country, but in many others countries are neutral about this and do not prohibit piracy for personal use.
> 
> Just buy a PC then. If you know how to tweak, a 2 core Pentium D, 2 gigs of ram and a 128mb gpu (5 euros for the whole pc) is totally fine, it will yield you about 120fps stable on 1.7.10 Lunar Client.

Ok, and if you want to play on newer versions with average graphics settings? but there is no money on the PC. And the phone calmly gives out on version 1.16.5 stable 60fps at medium graphics settings. And yes the pc that you have costs 5 euros, we will have all 200 euros in our country.
