### ISSUE TITLE
[BUG] Does not open any versions

### ISSUE THREAD

**Issue by DepfyOfc** [PojavLauncherTeam/PojavLauncher#3101]
### Describe the bug

![Screenshot_20220418-161537_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103961559/163863497-2833d75d-704c-45b4-be16-6156315c7e19.jpg)
![Screenshot_20220418-161516_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103961559/163863503-4adfeb64-a795-429c-af4a-bffbce91709a.jpg)

My game just shows up and i can't log in,and since most attempts to reolver alone didn't work,i decided to report it.

### The log file and images/videos

![Screenshot_20220418-161537_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103961559/163865411-4d43edc2-4d02-4666-a5de-34f2728bb8ba.jpg)
![Screenshot_20220418-161516_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103961559/163865419-c76d4b26-1edd-4225-841a-71ecfa07ca36.jpg)

### Steps To Reproduce

```markdown
After i log in my account the game bugs
```

### Expected Behavior

Não consigo explicar

### Platform

```markdown
- Device model: Galaxy A32/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

Bug :(

**Comment by GaucovyAero** [comment]
But you're on v3_openjdk, which is now a year old :/ Update to the latest one in GitHub Actions.

**Comment by DepfyOfc** [comment]
> 

do you have a tutorial to solve it?

**Comment by tohaiphe** [comment]
hmm i can version not that
