### ISSUE TITLE
[F-Req] <distance>

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#3102]
### Is this request related to a bug?

Did you guys fix it, like how the signs and clouds and amor enchant and blocks from a distance have a weird look.

### Describe the request.

It only affects holy edition

### Anything else?

Pls tell me that they fix it and also I am no pirate

**Comment by kuzy21** [comment]
Also keep up the great work of having this updated unlike other java launchers

**Comment by Mathias-Boulay** [comment]
@jorgieee I am not able to reproduce the bug. Please fill out the bug form properly or contact me via the official pojav discord

**Comment by kuzy21** [comment]
Ok
