### ISSUE TITLE
[BUG] Logging in with a Microsoft Account treats me if I'm offline

### ISSUE THREAD

**Issue by Incineroar** [PojavLauncherTeam/PojavLauncher#3104]
### Describe the bug

Logging into a Microsoft account seems to not like the fact that it's a MS account. I've done an account migration so this is the only way I'm able to play the game now - logging into a Mojang account no longer works and returns an error in the launcher that I've already migrated.

After logging in from the launcher login page, I select a game profile and hit play, and it tells me, "Minecraft can't legally be installed when logged in with a local account. Please switch to an online account to continue." and after that it disables my big green Play button.

This is happening with the absolutely most recent build of the app (Android CI #3762: Start implementing the new color selector)

### The log file and images/videos

![Screenshot_20220418-185049_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/6592165/163899419-8971ae92-1526-4491-a8c2-5a9e56ef998d.png)

Crash log is empty.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select Microsoft Account to log in
3. Sign into MS account that has the game migrated to it
4. Select any profile
5. Press Play
```

### Expected Behavior

The game should let me play the account as I just signed in with an online account.

### Platform

```markdown
- Device model: Samsung Galaxy Tab S8+
- CPU architecture: AArch64 (ARMv9)
- Android version: 12
- PojavLauncher version: crocus-491-d1a7fd11e-color-selector
```

### Anything else?

I've attempted to reinstall the app and also clear all of the app data, as well as manually delete the folder in the Android directory to no avail.

**Comment by GaucovyAero** [comment]
But you haven't checked "Keep me logged in".

**Comment by artdeell** [comment]
Fixed in latest builds

**Comment by Mihai444444** [comment]
Hs6g

**Comment by pojavlover18** [comment]
is there any way to fix this on ios bc i have to play on demo then![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/134509043/d6e76fd8-d447-4bb3-8ffb-f589e38619cf)

**Comment by mchnjt** [comment]
> is there any way to fix this on ios bc i have to play on demo then![image](https://user-images.githubusercontent.com/134509043/241292558-d6e76fd8-d447-4bb3-8ffb-f589e38619cf.png)

I've already said. You need to buy Minecraft.

**Comment by Sekpc** [comment]
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/141757089/08573862-d0a5-4bbe-a327-516881f08692)
