### ISSUE TITLE
vgpu shaders bug

### ISSUE THREAD

**Issue by MarcyIgop** [PojavLauncherTeam/PojavLauncher#3105]
### Describe the bug

yo can you guys fix this i kinda want a shader to run on my pojav

### The log file and images/videos

![Screenshot_20220419_120601_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/103250052/163919015-2dccb69e-7e60-4181-b03a-eb8192678070.jpg)
![Screenshot_20220419_120538_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/103250052/163919019-4bfaa118-590a-4d86-9663-0637f55da2d3.jpg)
![Screenshot_20220419_120510_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/103250052/163919021-2868ab7e-efd9-4a48-b8f4-0275b29e461b.jpg)

### Steps To Reproduce

```markdown
1.open pojav
2.launch 1.12.2
3.launch world
4.choose shader
5.then it wikl bug
```

### Expected Behavior

it sun smooth but the shader looks bad

### Platform

```markdown
- Device model: Huawei y6p 
- CPU architecture: aarch32 
- Android version: Android 10 
- PojavLauncher version: latest github pojav
```

### Anything else?

no hud when choosing default shader in 1.17 up

**Comment by kuzy21** [comment]
Same happens to me

**Comment by GaucovyAero** [comment]
You guys need to have a Snapdragon device, other ones don't work.

**Comment by WesleyVanNeck** [comment]
Vgpu is removed

**Comment by MarcyIgop** [comment]
> Vgpu is removed

oh

**Comment by Ang425** [comment]
Close this issue now pls

**Comment by offbeat-stuff** [comment]
how big is your display?can you send a copy of those controls?

**Comment by Serezaa14** [comment]
Gg
