### ISSUE TITLE
[BUG] Trying to put in runtime when it's already there.

### ISSUE THREAD

**Issue by shiumano** [PojavLauncherTeam/PojavLauncher#3106]
### Describe the bug

When I install and start noruntime, it tries to install even if runtime is present, regardless of whether it is internal or external.

### The log file and images/videos

https://media.discordapp.net/attachments/965765746129010718/965862697352691722/screen-20220419-152805.mp4
(Sorry, my phone did not have enough RAM to upload the video)

### Steps To Reproduce

```markdown
1. Install APK with runtime or install runtime manually
2. Install noruntime build
3. Launch PojavLauncher
4. I am forced to install runtime quite often
```

### Expected Behavior

Fix bugs or eliminate first file selection.
(I feel like your thinking is similar to oneblockatatime)

### Platform

```markdown
- Device model: AQUOS sence3 basic SHV48 3/32G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-491-d1a7fd11e-color-selector
```

### Anything else?

I have an SD card for internal storage and PojavLauncher on it.
That may be what is causing the problem.

**Comment by artdeell** [comment]
A valid runtime is necessary for Pojav to work, so it' s necessary on startup.
