### ISSUE TITLE
Idea to save project from mojang and Microsoft

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#3107]
### Is this request related to a bug?

Can you build website like tlauncher. Tlauncher also give free Minecraft experience.

### Describe the request.

You need to make website . This way you can earn money with ads.

**Comment by khanhduytran0** [comment]
> Tlauncher also give free Minecraft experience.

This is literally what Mojang looks for to send a lawsuit.

**Comment by ajit56** [comment]
But sir you are making pojavlauncher paid to play because mojang and Microsoft

**Comment by ajit56** [comment]
Also tlauncher have no problem from Mojang and Microsoft

**Comment by khanhduytran0** [comment]
> But sir you are making pojavlauncher paid to play because mojang and Microsoft

PojavLauncher is still free, Minecraft itself is still not free. You pay for Minecraft, not us. This is how the official launcher works. We don't follow 3rd-party launcher roads.

**Comment by khanhduytran0** [comment]
And so, if you want something free, demo mode will fit this.

**Comment by ajit56** [comment]
So you need money?

**Comment by Felix14-v2** [comment]
Tdauncher... bruh

**Comment by offbeat-stuff** [comment]
They dont need saving they are working legally
