### ISSUE TITLE
Analog controller (Suggestion)

### ISSUE THREAD

**Issue by Hilma23** [PojavLauncherTeam/PojavLauncher#3110]
### Is this request related to a bug?

This is becouse opsional button called "swipeble" very hard to use and sometimes doesnt work perfectly

### Describe the request.

It will awesome if you adding analog feature in the controller (new button type)

**Comment by GaucovyAero** [comment]
I am pretty certain that this doesn't work even in 1.18.2 PC version, and therefore Pojav cannot implement it.

**Comment by khanhduytran0** [comment]
Minecraft: Java Edition only takes WASD input. Therefore, if a joystick is there, you might ask why can’t you control the movement speed (toggle sprint when the thumb is moved far away?) and direction.

**Comment by Jayden900** [comment]
It would be a great update if you made a way to change your skin in the launcher it self only if you have a Microsoft Account
