### ISSUE TITLE
虚拟光标错位

### ISSUE THREAD

**Issue by hyplant** [PojavLauncherTeam/PojavLauncher#3112]
### Describe the bug

虚拟光标的位置与输入进游戏的位置出现错位，实际位置在虚拟光标的右侧。

### The log file and images/videos

![Screenshot_20220421-091812_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/164352722-c4d0fc2c-7639-4867-a0e1-18afbbb9e160.jpg)
![Screenshot_20220421-091608_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/164352743-3780e481-c4af-4d77-8c73-f529fb7e8f54.jpg)
![Screenshot_20220421-091544_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/164352761-c0303963-d5ed-4671-bd57-ab3185e18112.jpg)

### Steps To Reproduce

```markdown
带有挖孔屏的手机上隐藏相机区域后启动应用就会导致这些问题。
```

### Expected Behavior

无

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 12
- PojavLauncher version: crocus-449-6060e8bdc-v3_openjdk
```

### Anything else?

无

**Comment by Mathias-Boulay** [comment]
Fixed in release candidate build.
