### ISSUE TITLE
[BUG] Quilt Installer does not work

### ISSUE THREAD

**Issue by offbeat-stuff** [PojavLauncherTeam/PojavLauncher#3113]
### Describe the bug

Quilt mc installer is not able to load version list and hence not able to install.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8526897/latestlog.txt)

### Steps To Reproduce

```markdown
1 Start Pojav
2 install jar
3 select quilt installer
4 wait for a minute
```

### Expected Behavior

Should list versions

### Platform

```markdown
- Device model: Honor 6x
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: latest development version as of 20 April
```

**Comment by kuzy21** [comment]
Press on default, and then press make new, then there should be a list with every version, also make sure to put the runtime and what render if not it will not work.

**Comment by offbeat-stuff** [comment]
solved it by installing through termux

**Comment by offbeat-stuff** [comment]
Does not seem to launch though

**Comment by kuzy21** [comment]
What minecraft version r u trying to run?

**Comment by offbeat-stuff** [comment]
1.18.2 with quilt loader

**Comment by offbeat-stuff** [comment]
It instantly exits the game as the jar in the versions folder is empty.btw fabric works totally fine for me.

**Comment by kuzy21** [comment]
Ok do u have runtime 17 and did u patch 1.18.2

**Comment by offbeat-stuff** [comment]
no patch and i do have java 17 installed

**Comment by offbeat-stuff** [comment]
can you try yourself to install quilt

**Comment by offbeat-stuff** [comment]
Here https://quiltmc.org/install/client

**Comment by GaucovyAero** [comment]
has a fix setting in the latest actions build

**Comment by TheKodeToad** [comment]
What is this setting?

Edit: from looking at the code it seems to be "Sandbox .jar installer" in the miscellaneous settings. I'm leaving this here for future reference ;)

**Comment by nopeless** [comment]
@TheKodeToad You are quite everywhere. Thanks for the comment, I was finding it

**Comment by GaucovyAero** [comment]
not related to the installation but if your mods crash, the game might crash too (before showing the error), because quilt tries to show a forked gui window, you fix it by putting `-Dloader.disable_forked_guis=true` into your jvm arguments
