### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by BeJohnsonSentosa12** [PojavLauncherTeam/PojavLauncher#3114]
### Describe the bug

Fabric 1.16.5 latest crashing

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1. Start Pojavlauncher from github build
2. Install fabric
3. Enter the game and crash
```

### Expected Behavior

The game not launch

### Platform

```markdown
- Device model: Vivo 1935
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: github build
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
You haven't sent any logs, therefore we can't help you of course.

**Comment by BeJohnsonSentosa12** [comment]
> You haven't sent any logs, therefore we can't help you of course.

My fault, my fault, I didn't log in using a premium account, so it crashed because the jar didn't exist, only json
