### ISSUE TITLE
Auto cut call and discord

### ISSUE THREAD

**Issue by kaicryptx** [PojavLauncherTeam/PojavLauncher#3116]
### Describe the bug

When I started to play pojavlauncher with my friend my discord automatically cut and also call 

### The log file and images/videos

999999999

### Steps To Reproduce

```markdown
1.when i start pojavlauncher with call 
2.discord or call automatically disconnect


### Expected Behavior

When I started to play pojavlauncher with my friend my discord automatically cut and also call 

### Platform

```markdown
- Device model: Realme C3
- CPU architecture: aarch64
- Android version: ANDROID 10
- PojavLauncher version: PLAY STORE
```

**Comment by kaicryptx** [comment]
Response?

**Comment by kaicryptx** [comment]
@khanhduytran0

**Comment by khanhduytran0** [comment]
> Response?

We are not always here to respond immediately. So please bring your patience here.

Since you haven’t stated the size of RAM that is given to the game. I assume that you put 100% for it, which is why background apps are killed quite often.

**Comment by mchnjt** [comment]
legit memory muncher
