### ISSUE TITLE
[F-Req] Themes for PojavLauncher

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#3117]
### Describe the request.

I propose such an idea as a design theme for the PojavLauncher. Which will create a community and upload to a special resource of themes for the launcher. The design styles will be by default: default, original Minecraft launcher, lunar client. 

PLZ ADD THIS FEATURE(

**Comment by GaucovyAero** [comment]
Although it is a good idea, pojav is still in the works. Devs do not have time even for interesting, but non-essential things. Maybe wait a couple of months (5+) and repost this :)

**Comment by andr0d1v** [comment]
@artdeell plz see this

**Comment by mchnjt** [comment]
> ### Is this request related to a bug?
> _No response_
> 
> ### Describe the request.
> I propose such an idea as a design theme for the PojavLauncher. Which will create a community and upload to a special resource of themes for the launcher. The design styles will be by default: default, original Minecraft launcher, lunar client.
> 
> PLZ ADD THIS FEATURE(
> 
> ### Anything else?
> _No response_

PojavLauncher's current UI almost looks like Minecraft Launcher for PC.

**Comment by andr0d1v** [comment]
@alsakuttle Not really, I would like to have this function!
