### ISSUE TITLE
[BUG] 1.18.2 TITLE SCREEN/ MAIN SCREEN LAGS 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3118]
### Describe the bug

When I Launch 1.18.2 The title /main screen lags also the game lags it lags more than any version 1.0.0-1.16.5 there will be little lag but 1.17-1.18.2 lags so much the title screen and also the game lags when i enter server pls fix this lag only mymqin/title screen lags my friend has the same device but hes title screen dosent lag help me :(

### The log file and images/videos

I Can't Attach Videos Because I Don't Have A Screen Recorder I Will Get One And Attach The Video Soon

### Steps To Reproduce

```markdown
1.Start PojavLauncher 
2.Launch Any 1.17 Or 1.18 Version
3.Title Screen / Main Screen Lags
4.Join Any Server
5.Lags More
```

### Expected Behavior

I excepted game to not lag so much

### Platform

```markdown
- Device model: Samsung Galaxy Tab S6 Lite 64GB One Ui:3.1Model Number SM-P610
- CPU architecture:aarch64 
- Android version: 11
- PojavLauncher version: Latest/crocus-v3_openjdk
- PojavLauncher Downloaded From Google Play Store Also The PojavLauncher Is Not Beta Or PreRelease
- Last updated On 31 Aug 2021
```

### Anything else?

Same With 1.17-1.18

**Comment by khanhduytran0** [comment]
> PojavLauncher version: Latest/crocus-v3_openjdk

Old version.

> my friend has the same device but hes title screen dosent lag

But the difference:
- Your friend might have used dev build instead of release build
- Your friend might have used gl4es, instead of Zink (yeah, with the Play Store version, the only way to get 1.17+ to work is to use Zink, which is 5x (?)slower than gl4es)

Also, what’s with #3058 now?

**Comment by kuzy21** [comment]
Use the patcher

**Comment by ghost** [comment]
> > PojavLauncher version: Latest/crocus-v3_openjdk
> 
> Old version.
> 
> > my friend has the same device but hes title screen dosent lag
> 
> But the difference:
> 
> * Your friend might have used dev build instead of release build
> * Your friend might have used gl4es, instead of Zink (yeah, with the Play Store version, the only way to get 1.17+ to work is to use Zink, which is 5x (?)slower than gl4es)
> 
> Also, what’s with #3058 now?

It works i just needed to change something like gl4es or zink but the lag kills me i crash bcz of the lag

**Comment by ghost** [comment]
Any link for the patcher

> Use the patcher

**Comment by ghost** [comment]
> * Your friend might have used dev build instead of release build
Any Link For The Dev Build

**Comment by khanhduytran0** [comment]
[Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk)
