### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by adaue1** [PojavLauncherTeam/PojavLauncher#3119]
### Describe the bug

Application exited with code 1

### The log file and images/videos

Can't give it is reseted pojavlauncher
 

### Steps To Reproduce

```markdown
Start pojav launcher
Login 
Play a game
Get out of it 
The game exited with code 1
```

### Expected Behavior

I expect the game to not exit

### Platform

```markdown
- Device model: SM-T280
- CPU architecture: can't find it
- Android version: 5.1.1
- PojavLauncher version: can't find it
```

### Anything else?

Nothing else

**Comment by adaue1** [comment]
Another big bug

Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=1280x800, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/data/net.kdt.pojavlaunch/cache/OptiFine_1.18.2_HD_U_H7.jar]
Added custom env: TMPDIR=/data/data/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1280
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/data/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/data/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli:/data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-1/lib/arm
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/data/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=800
--------- beginning of system
WARNING: linker: libawt_xawt.so: unused DT entry: type 
0x6ffffef5 arg 0xea4
WARNING: linker: libawt_xawt.so: unused DT entry: type 0x6ffffffe arg 0x1424
WARNING: linker: libawt_xawt.so: unused DT entry: type 0x6fffffff arg 0x2
--------- beginning of main
WARNING: linker: 
libopenal.so
: unused DT entry: type 
0x6ffffef5 arg 0x22398
WARNING: linker: libopenal.so: unused DT entry: type 0x6ffffffe arg 0x2c370
WARNING: linker: libopenal.so: unused DT entry: type 0x6fffffff arg 0x3
I/jrelog  (10913): dlopen libxhook.so success
referenceTable GDEF length=22 1
referenceTable GSUB length=1206 1
referenceTable GPOS length=12 1
OpenJDK Client VM warning: 
Can't detect primordial thread stack location - find_vma failed

referenceTable GDEF length=670 1
referenceTable GSUB length=7186 1
referenceTable GPOS length=24560 1
referenceTable head length=54 1
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  (10913): dlopen libjvm.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsound.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjpeg.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsdt.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pcsc.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmanagement.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libunpack.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjaas_unix.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libhprof.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_xawt.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsig.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2gss.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsunec.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnpt.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libtinyiconv.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pkcs11.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libdt_socket.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjdwp.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libzip.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsctp.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmlib_image.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/liblcms.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjawt.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  (10913): dlopen /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  (10913): dlopen /data/app/net.kdt.pojavlaunch-1/lib/arm/libopenal.so success
I/jrelog  (10913): Done processing args
I/jrelog  (10913): Found JLI lib
I/jrelog  (10913): Calling JLI_Launch
Policy policy.url.2=file:/storage/emulated/0/games/PojavLauncher/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/games/PojavLauncher/.java.policy (No such file or directory)

Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/*

OptiFine Version: OptiFine_1.18.2_HD_U_H7

Minecraft Version: 1.18.2

OptiFine Edition: HD_U_H7
URL: file:/data/data/net.kdt.pojavlaunch/cache/OptiFine_1.18.2_HD_U_H7.jar

Dir minecraft: /storage/emulated/0/games/PojavLauncher/.minecraft

Dir libraries: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries
Dir versions: /storage/emulated/0/games/PojavLauncher/.minecraft/versions
OptiFine Version: OptiFine_1.18.2_HD_U_H7

Minecraft Version: 1.18.2

OptiFine Edition: HD_U_H7
Minecraft_OptiFine Version: 1.18.2-OptiFine_HD_U_H7

**Comment by GaucovyAero** [comment]
Hi. 

Make sure to follow these steps to get 1.18.2 running on your phone:
1. Download the most updated PojavLauncher version [here.](https://github.com/PojavLauncherTeam/PojavLauncher/actions) - _press the topmost version with a green checkmark on it and download app-debug.zip_
2. Download Java 17 for your Galaxy Tab A 7.0 [here.](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm-20210914-release.tar.xz)
3. Then just install OptiFine and start it up :D

**Comment by offbeat-stuff** [comment]
probably this is better https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk
