### ISSUE TITLE
My minecraft keeps crashing

### ISSUE THREAD

**Issue by Fu-ad5** [PojavLauncherTeam/PojavLauncher#3122]
### Describe the bug

Minecraft launches and crashes before I'm able to even click on multiplayer or do anything

### The log file and images/videos

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-12
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1004065224 bytes (957 MB) / 1529348096 bytes (1458 MB) up to 1529348096 bytes (1458 MB)
	JVM Flags: 3 total; -Xms1528M -Xmx1528M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version      | Source                                |
	| ------ | --------------------- | ------------ | ------------------------------------- |
	| UCHIJA | mcp                   | 9.19         | minecraft.jar                         |
	| UCHIJA | FML                   | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9.jar    |
	| UCHIJA | Forge                 | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9.jar    |
	| UCHIJA | essential             | 1.0.0        | Essential (forge_1.8.9).jar           |
	| UCHIJA | hypixel_auto_complete | 1.1.0        | Hypixel Autocomplete-1.1 (1.8.9).jar  |
	| UCHIJA | notenoughupdates      | 2.0.0-REL    | NotEnoughUpdates-2.0-PRE26.jar        |
	| UCHIJA | skyblockaddons        | 1.6.0        | SkyblockAddons-1.6.0-for-MC-1.8.9.jar |
	| UCHIJA | skyblockcatia         | 1.2.0        | SkyBlockcatia-1.8.9-1.2.0.jar         |
	| UCHIJA | skytils               | 1.2.4        | Skytils-0.3.3.jar                     |

	Loaded coremods (and transformers): 
Skytils On Top (Skytils-0.3.3.jar)
  skytils.skytilsmod.asm.SkytilsTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: V2.3_ZachPlaysAN_HS_Texture_Pack_1.8.9.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x null
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.log in
3.go to forge 1.8.9
4.launch the game
5.crashes
I also replaced the lwjgl files to the most recent ones from the official website
And my ram is set to 1502mb
The renderer I'm using is gl4es 1.1.5 (OpenGl ES 2): exports OpenGL 2.1
```

### Expected Behavior

For the game to launch :(

### Platform

```markdown
- Device model: Samsung tab S7
- CPU architecture: Kryo585
- Android version: 12
- PojavLauncher version: crocus v3 openjl
```

**Comment by aovpgamer** [comment]
Trun using VBOs on

**Comment by Fu-ad5** [comment]
Thanks
