### ISSUE TITLE
[BUG] Cannot type @

### ISSUE THREAD

**Issue by Girraj999** [PojavLauncherTeam/PojavLauncher#3123]
### Describe the bug

I cannot type @ in chat. 
Tried on few keyboards
Hacker keyboard
Oppo default keyboard 
Gboard
Not working on any of these :(
Help me

Error shows twitch services not downloaded

### The log file and images/videos

Idk what is this

### Steps To Reproduce

```markdown
In minecraft i cannot type @ in chat
```

### Expected Behavior

Not working @ 

### Platform

```markdown
- Device model: Oppo a1k
- CPU architecture: 
- Android version: 9
- PojavLauncher version: 
[Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by Mathias-Boulay** [comment]
old launcher version from what you gave us
