### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#3124]
### Is this request related to a bug?

What is .pack unpacker

### Describe the request.

Which files are they

### Anything else?

I am bad in English

**Comment by offbeat-stuff** [comment]
read the latest pr closed

**Comment by offbeat-stuff** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/pull/3121

**Comment by ajit56** [comment]
🤐i was thinking it is in built file opener
