### ISSUE TITLE
1.17 and 1.18 Crashing [offline]

### ISSUE THREAD

**Issue by JustJoshinDev** [PojavLauncherTeam/PojavLauncher#3126]
### Describe the bug

Whenever I try and launch a version of 1.18 or 1.17 It loads up the game window and then crashes. It will go strait back to the launcher. No crash log, no error message, no nothing. Its just like it never launched. Same thing happens if I try and launch 1.18 or 1.17 Optifine. Anything bellow 1.17 works fine. At first I thought it was the same incompatible Java Runtime issue from before I updated, but it doesn't tell me that like it used to. It will say game exited and then have me press ok.

### The log file and images/videos

![Screenshot_20220423-203710](https://user-images.githubusercontent.com/104283405/164952054-9fb9c862-49a6-480b-b423-3db2067730f7.png)

### Steps To Reproduce

```markdown
Open PojavLauncher and Login
Launch MC
```

### Expected Behavior

Launch normaly

### Platform

```markdown
- Device model: Fire HD 10
- CPU architecture: arm64-v8a
- Android version: Fire OS 7.3.2.2
- PojavLauncher version: 3.3.1.1
```

**Comment by Tttryrf** [comment]
Yahi problem a rahi hai Maine use ful load bhi kar liya tha fir bhi yah
problem a rahi hai kuchh code de do taki main is problem ko solve kar sakun

**Comment by Tttryrf** [comment]
Main usko tumhari photo bhejta hun

**Comment by offbeat-stuff** [comment]
Is nt fire os tv

**Comment by offbeat-stuff** [comment]
also use the latest dev version rather than the latest release

**Comment by offbeat-stuff** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk+is%3Asuccess

**Comment by JustJoshinDev** [comment]
Thank you!
