### ISSUE TITLE
[F-Req] Ram Request

### ISSUE THREAD

**Issue by JustJoshinDev** [PojavLauncherTeam/PojavLauncher#3127]
### Describe the request.

Hello, I am very appreciative of your work on PojavLauncher. I feel bad because I've posted a couple of bug reports and now a request in an hour. If you guys even so much as read this I will be happy. 
Ok, I've been having a very minor problem with my game. The "Auto RAM" feature will occasionally set the amount of allocated RAM too low or too high. The minor fix to this is closing and relaunching the game. Usually it then sets it to an amount that somewhat fits my game. I would prefer however for it when the Auto RAM is off, for the old RAM slider to pop up, so I can manually adjust the allocated RAM to best suit my needs. 
This is by all means NOT a necessary feature and I do not expect it to be added. Just a request.

**Comment by artdeell** [comment]
You are using a very ancient version of the launcher. Auto RAM was removed long-long ago...

**Comment by JustJoshinDev** [comment]
Oh ok. Is there a link to the newest version?

**Comment by artdeell** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2216068576

**Comment by JustJoshinDev** [comment]
Thank you!
