### ISSUE TITLE
Re add

### ISSUE THREAD

**Issue by ajit56** [PojavLauncherTeam/PojavLauncher#3128]
### Is this request related to a bug?

You should add gl4es 1.1.5 again my sodium have bug .all blocks are invisible.

### Describe the request.

Gl4es 1.1.5

**Comment by offbeat-stuff** [comment]
i also use sodium in 1.18.2 with chunk rendering disabled and a lot of block are culled wrong is that related to your problem

**Comment by ajit56** [comment]
@artdeell

**Comment by ajit56** [comment]
@Mathias-Boulay

**Comment by ajit56** [comment]
@LegacyGamerHD

**Comment by ajit56** [comment]
@khanhduytran0

**Comment by Mathias-Boulay** [comment]
Nah.
If you're using the asset pack, remove it.

**Comment by ajit56** [comment]
No i m not using asset pack

**Comment by Mathias-Boulay** [comment]
*visible lack of proof*
Well then, chances are you enabled a sodium option that was not meant to be supported

**Comment by ajit56** [comment]
https://youtu.be/z2zGCySXw-U @Mathias-Boulay see this

**Comment by ajit56** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8590356/latestlog.txt)

**Comment by ajit56** [comment]
This is latest log

**Comment by mchnjt** [comment]
Spam. We're removing it for a reason. Spam ping devs and we'll block you out of this repo.

**Comment by ajit56** [comment]
> Spam. We're removing it for a reason. Spam ping devs and we'll block you out of this repo.

It's not spam

**Comment by WesleyVanNeck** [comment]
> > Spam. We're removing it for a reason. Spam ping devs and we'll block you out of this repo.
> 
> It's not spam

Its spam if keep opening and closing it

**Comment by WesleyVanNeck** [comment]
also the error isnt even related to gl4es
 
`1:08:05.846 [Sound engine] ERROR net.minecraft.class_4230 - Stop: Invalid name parameter.
`

**Comment by ajit56** [comment]
> > > Spam. We're removing it for a reason. Spam ping devs and we'll block you out of this repo.
> > 
> > 
> > It's not spam
> 
> Its spam if keep opening and closing it

Soory

**Comment by ajit56** [comment]
> also the error isnt even related to gl4es
> 
> `1:08:05.846 [Sound engine] ERROR net.minecraft.class_4230 - Stop: Invalid name parameter. `

Okay

**Comment by ajit56** [comment]
How to solve that issue
