### ISSUE TITLE
[F-Req] <Ability to launch the Curseforge launcher in pojavlauncher>>

### ISSUE THREAD

**Issue by Waxbyz** [PojavLauncherTeam/PojavLauncher#3130]
### Is this request related to a bug?

Ability to launch the Curseforge launcher in pojavlauncher

### Describe the request.

Ability to launch the Curseforge launcher in pojavlauncher

### Anything else?

Ability to launch the Curseforge launcher in pojavlauncher

**Comment by khanhduytran0** [comment]
CurseForge doesn’t have Linux support for now, so this is currently impossible.
