### ISSUE TITLE
[F-Req] <Ability to run programs related to minecraft>

### ISSUE THREAD

**Issue by Waxbyz** [PojavLauncherTeam/PojavLauncher#3131]
### Is this request related to a bug?

You should add the ability to run programs related to minecraft

### Describe the request.

A special button in the main menu of pojavlauncher. Ability to run files in exe, jar format. In this button you can also select the program you need. Example: mine-imator or blockbench

### Anything else?

Please add.

**Comment by artdeell** [comment]
You can run .jar files ehich do not re-launch or do not require JavaFX using the "Mod installer" feature. You cannot run .exe files on android without emulation, so this will not be implemented.

**Comment by Waxbyz** [comment]
How do I use the mods installer(with custom arguments) ?
