### ISSUE TITLE
[BUG] Play any version not working!

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#3132]
### Describe the bug

I just press play on any version but its not loading anything :/ its just black screen.

### The log file and images/videos

Here-.  [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8550698/latestlog.txt)
![Screenshot_2022-04-25-07-18-43-96](https://user-images.githubusercontent.com/96860972/165000880-08533ca5-40f2-4d61-8178-01dbca23ab35.jpg)

### Steps To Reproduce

```markdown
Start pojav launcher
Press play
Black screen :/
```

### Expected Behavior

It should load in menu screen.

### Platform

```markdown
- Device model: Oppo a12 3/32
- CPU architecture: aarch64
- Android version:9 
- PojavLauncher version: latest build
```

### Anything else?

Can you solve this?

**Comment by khanhduytran0** [comment]
How long have you waited for? If it’s 1 second then I think you have lost your patience. The game needs time to initialize stuff.

**Comment by MARnelPH12** [comment]
I've been waiting for an 20 to 30 mins but still nothing :/
And the version is 1.12.2 it should be load fast but nothin.

**Comment by PayToUse** [comment]
What renderer are you using and how much memory do you allocate

**Comment by Mathias-Boulay** [comment]
Fixed in release candidate build.
