### ISSUE TITLE
[BUG] <1.18.2 Optifine Virgl Shader and Texture Bug>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3133]
### Describe the bug

When i load optifine 1.18.2 virgl the menu is fine but when i load a world the textures become buggy. It all become jpeg files and the surroundings are darken.pls fix this

### The log file and images/videos

Cant record when im in game

### Steps To Reproduce

```markdown
1.Start Pojav Launcher
2.Launch 1.18.2 Optifine
3.Main Menu
4.Joining World
5.Texture Glitching
6.Shader not appearing
```

### Expected Behavior

It should be working like 1.16.5

### Platform

```markdown
- Device model: Infinix Hot 10 Play Mediatek Helio P35 4/64G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-326-685dd1620-profiles-2-electric-boogaloo
```

### Anything else?

Same as 1.18 and 1.18.1,1.17

**Comment by KentangGG121** [comment]
Don't ask again it won't be fixed so better don't ask again!

**Comment by artdeell** [comment]
VirGL is not fully supported
