### ISSUE TITLE
[BUG] Architecture arm64 is incompatible with Java Runtime arm.

### ISSUE THREAD

**Issue by GTAspy006** [PojavLauncherTeam/PojavLauncher#3134]
### Describe the bug

whenever i launch 1.17.1 it shows a message "Architecture arm64 is incompatible with Java Runtime arm."

and yes,i used the latest jre17 runtime

### The log file and images/videos

![Screenshot_20220425-192440_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/96731384/165078392-3f6ac434-955b-4170-b07c-e62eb1c123ce.jpg)

latestlog.txt : --------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Architecture arm64 is incompatible with Java Runtime arm
 

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Play 1.17.1
3.Architecture arm64 is incompatible with Java Runtime arm.
```

### Expected Behavior

i expect the game to launch or maybe atleast warn me about the renderer and other stuff

### Platform

```markdown
- Device model: Samsung Galaxy S8+ (SM-G955F)
- CPU architecture: 4x Samsung Exynos M2 @ 2.31 GHz
4x ARM Cortex-A53 @ 1.69 GHz
- Android version: 9
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by khanhduytran0** [comment]
*The error message has already explained itself*
Basically, your device is 64bit, but you tried to run 32bit Java.
