### ISSUE TITLE
[F-Req] <Add Bluetooth Controller Suppoort without Mod>

### ISSUE THREAD

**Issue by ProSteve12301** [PojavLauncherTeam/PojavLauncher#3138]
### Is this request related to a bug?

Nope

### Describe the request.

I want to play Java with Controller because mobile control is too difficult to use.

### Anything else?

I planning to buy an Controller for pvping.

**Comment by Mathias-Boulay** [comment]
you are really late my dude

**Comment by ProSteve12301** [comment]
What  do you mean?
