### ISSUE TITLE
[BUG] <Error in starting cristalix launcher in installer.jar>

### ISSUE THREAD

**Issue by Waxbyz** [PojavLauncherTeam/PojavLauncher#3139]
### Describe the bug

Pojavlauncher closed with error code:4103

### The log file and images/videos

![Screenshot_20220426_091104_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/104303336/165233790-e6fba087-93da-427c-846e-fc6c775c799a.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8560361/latestlog.txt)

### Steps To Reproduce

```markdown
1.By running pojavlauncher. 
2.In pojavlauncher run installer.jar
3.Select a cristalix file
4.Error 4103 opens
```

### Expected Behavior

I expect the installation to be successful and the "cristalix" version will appear in the pojavlauncher version. After I launch this version, a special installer environment Will installer.jar there I'll start the game

### Platform

```markdown
- Device model: Huawei P Smart Z 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest beta version of pojavlauncher
```

### Anything else?

Please add or fix this error

**Comment by artdeell** [comment]
Cristallix is a launcher, and running other launchers through the mod installer is not supported.

**Comment by Waxbyz** [comment]
Is it possible to implement this somehow?

**Comment by artdeell** [comment]
Nope. Not going to happen. If you want to play on it, ask for official approval from the cristallix team.

**Comment by Waxbyz** [comment]
But, is it possible to embed a simplified linux virtual machine in pojavlauncher?
