### ISSUE TITLE
[F-Req] <Add demo minecraft to pojavlauncher>

### ISSUE THREAD

**Issue by Waxbyz** [PojavLauncherTeam/PojavLauncher#3140]
### Is this request related to a bug?

You should add the ability to run a demo minecraft 

### Describe the request.

You should add Special version of minecraft demo

### Anything else?

Minecraft is my life! Maaaaaincraaaaaft!

**Comment by Mathias-Boulay** [comment]
how about you buy the game instead ?

**Comment by kuzy21** [comment]
Dam u just got exposed

**Comment by ghost** [comment]
At least he didn't ask for offline mode... let's look at the positives.

**Comment by kuzy21** [comment]
Yeah we don't like pirate's and this guy just asking for a 90 min game
