### ISSUE TITLE
[BUG] Random crashes during gameplay. 

### ISSUE THREAD

**Issue by CraftBossX** [PojavLauncherTeam/PojavLauncher#3141]
### Describe the bug

When playing version 1.8.9, crashes randomly happen during gameplay without any set condition. Current settings are:
- 2584 MB RAM
- Renderer: GL4ES 1.1.5
- Runtime Manager: Java 8
- Forge 1.8.9
The crashes seem to happen on any settings, as I've tried most possible combinations like with Java 17, vgpu, GL4ES 1.1.4, as well as lower RAM settings (900 MB).

The crashes occur on Forge 1.8.9, vanilla 1.8.9 and Optifine 1.8.9 (all tested) usually between 10 minutes to an hour into playing.

(Used forge mods: Essential, Patcher, Optifine) 

An important information may also be that the server I'm joining is Hypixel and gamemode Skyblock, which might have some part in these crashes since no crashes outside the specific gamemode have been encountered. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8561300/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Pick version 1.8.9 
3. Playing on hypixel.net and Skyblock gamemode
Then, the game crashes at random times.
```

### Expected Behavior

I expect being able to play longer amounts of time without crashes occuring. 

### Platform

```markdown
- Device model: Xiaomi Redmi Note 8 Pro 6/128
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by artdeell** [comment]
Please enable "Use VBO" in video settings of Minecraft, or update to the latest build from the Actions tab.

**Comment by CraftBossX** [comment]
> Please enable "Use VBO" in video settings of Minecraft, or update to the latest build from the Actions tab.

The crashes seem to completely disappear after enabling VBO, thank you so much! I'm surprised one setting fixes this much.
