### ISSUE TITLE
[F-Req] <PojavLauncher modding capability>

### ISSUE THREAD

**Issue by Waxbyz** [PojavLauncherTeam/PojavLauncher#3142]
### Is this request related to a bug?

You should add modding capability to pojavlauncher. So that pojavlauncher users can modulate it. For example they could remove a button they did not need or change the code to add the function they needed. 

### Describe the request.

I would like to add a modding pojavlauncher

**Comment by artdeell** [comment]
The code is here, so feel free to add anything you want to it

**Comment by Waxbyz** [comment]
What programming language is pojavlauncher written in?

**Comment by artdeell** [comment]
Java

**Comment by Waxbyz** [comment]
Ok
