### ISSUE TITLE
[BUG] no jre17 build for aarch64 (chromebook, play store version, no jailbreak)

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3143]
### Describe the bug

need jre17 build for aarch64 to play 1.18.

### The log file and images/videos

no video

### Steps To Reproduce

```markdown
select 1.18.2 and click play
(no option to select jre17, no jre17 build found on the net)
```

### Expected Behavior

being able to play 1.18

### Platform

```markdown
- Device model: Acer ChromeBook
- CPU architecture: aarch64
- Android version: Emulated by ChromeBook environement
- PojavLauncher version: Latest Play Store version
```

### Anything else?

My device isn't jailbreaked and i don't want to, so can't install apks manually (need to work on play store version)

**Comment by Mathias-Boulay** [comment]
Well, wait then since newer versions are needed.
You can also support us on patreon for faster google play updates 😄

**Comment by ghost** [comment]
paying money for updates ? no lmao

**Comment by Mathias-Boulay** [comment]
for **early** updates

**Comment by ghost** [comment]
if i had to pay 1 time to get the updates, i would be ok but i'll not if i have to pay a monthly plan.

**Comment by ghost** [comment]
imagine paying a bucks every month for every program you use

**Comment by artdeell** [comment]
> imagine paying a bucks every month for every program you use

you always can get the apk instead, if you want
paying only makes you receive early updates on google play

**Comment by ghost** [comment]
Ok
