### ISSUE TITLE
[BUG] Texture bug 1.12.2 minecraft

### ISSUE THREAD

**Issue by Dinomain38** [PojavLauncherTeam/PojavLauncher#3145]
### Describe the bug

When I enter minecraft 1.12.2 and hit any mob, the textures turn black.

### The log file and images/videos

![IMG-20220426-WA0019](https://user-images.githubusercontent.com/86514770/165351444-4523a1b1-342c-4627-8f72-b051a3391317.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Open 1.12.2 minecraft.
3. Join the world.
4. Hit mob.
5. see bug.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Asus ZenFone max pro M1
- CPU architecture: 64 bit armV8-A
- Android version: 9
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

With this bug i can't play minecraft with popular mods because i don't want see black textures.

**Comment by GaucovyAero** [comment]
Your pojav is outdated. Update to the latest one in [Actions.](https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk+is%3Asuccess)

**Comment by PayToUse** [comment]
use vgpu renderer to fix it

**Comment by vFireRate** [comment]
it causes the gl4es 1.1.5

**Comment by PayToUse** [comment]
Also it's only for 1.16 and up, using below 1.15 will bug the textures when hit a mob

**Comment by artdeell** [comment]
Fixed on holy gl4es
