### ISSUE TITLE
[BUG] 1.12.2 Menu Screen Freezes with Virgl renderer

### ISSUE THREAD

**Issue by PayToUse** [PojavLauncherTeam/PojavLauncher#3146]
### Describe the bug

After playing the world, the menu screen began to freeze
![Screenshot_20220427_073113_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/67496494/165409873-26cd1a07-a00d-4bc9-9016-ba588a40edf2.jpg)

### The log file and images/videos

Forgot to send the log, sorry

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Play 1.12.2
3. Play a world
4. When done, save and quit the world
5. Menu screen begins to freeze
```

### Expected Behavior

I was gonna quit the game and it began to freeze, but buttons and the cursor are functionable

### Platform

```markdown
- Device model: Huawei Nova 9 
- CPU architecture: aarch64
- Android version: 11 
- PojavLauncher version: Version crocus-509-6afc22e47-v3_openjdk
```

**Comment by ChooweKamska999** [comment]
Idk

**Comment by artdeell** [comment]
VirGL is not fully supported
