### ISSUE TITLE
[Error] 1.18.2 Fabric crash

### ISSUE THREAD

**Issue by BNaise** [PojavLauncherTeam/PojavLauncher#3148]
### Describe the bug

Game exited

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8578772/latestlog.txt)

### Steps To Reproduce

```markdown
1.Install fabric 1.18.2
2.play it and crash
```

### Expected Behavior

I expect it's not crash but it's crash 😭😭😭

### Platform

```markdown
- Device model: Redmi Note 7 Pro
- CPU architecture: aarch64
- Android version:10 
- PojavLauncher version:[Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by artdeell** [comment]
Fixed on latest builds
