### ISSUE TITLE
Crash[BUG] <Short description>

### ISSUE THREAD

**Issue by Printguyy** [PojavLauncherTeam/PojavLauncher#3151]
### Describe the bug

.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 759533616 bytes (724 MB) / 1035468800 bytes (987 MB) up to 1035468800 bytes (987 MB)
	JVM Flags: 3 total; -Xms991M -Xmx991M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	Launched Version: 1.14.1
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 9x null

### The log file and images/videos

None

### Steps To Reproduce

```markdown
When i start fabric it goes crash
```

### Expected Behavior

None

### Platform

```markdown
- Device model: redmi 10
- CPU architecture: mediatek
- Android version: 11
- PojavLauncher version: newest
```

### Anything else?

No

**Comment by mchnjt** [comment]
Invalid.

**Comment by offbeat-stuff** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk+is%3Asuccess
