### ISSUE TITLE
Scrolling Broken with physical mouse.

### ISSUE THREAD

**Issue by DovydasTEDS** [PojavLauncherTeam/PojavLauncher#3154]
### Describe the bug

I scroll, nothing happens

### The log file and images/videos

Dont need

### Steps To Reproduce

```markdown
1. Load into mc
2. Scroll
```

### Expected Behavior

It scrolls

### Platform

```markdown
- Device model: SM-A32 5g
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
This issue should be resolved in the latest action builds. Make sure to update your launcher first. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`
