### ISSUE TITLE
[BUG] <Departure of the world with mod plasmovoice >

### ISSUE THREAD

**Issue by Waxbyz** [PojavLauncherTeam/PojavLauncher#3155]
### Describe the bug

Departure of the world with the fashion plasmovoice. And at the same time the inscription "connection is lost" appears. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8583681/latestlog.txt)

### Steps To Reproduce

```markdown
1. Run pojavlauncher with mod plasmovoice 
2. Press the singl player button.
3. Choose our world. 
4. The message "connection lost" appears
```

### Expected Behavior

I expect the world to start. And I will play with the plasmovoice mod. 

### Platform

```markdown
- Device model: Huawei P Smart Z 
- CPU architecture: aarch64 
- Android version: 10
- PojavLauncher version: last beta
```

### Anything else?

Please fix

**Comment by Axon-waxby** [comment]
@artedeel

**Comment by Axon-waxby** [comment]
@artdeell

**Comment by Waxbyz** [comment]
@artdeell

**Comment by offbeat-stuff** [comment]
@Axon-waxby have you enabled the permission for microphone

**Comment by Waxbyz** [comment]
@offbeat-stuff How do I check this or how to give this permission?

**Comment by Waxbyz** [comment]
@offbeat-stuff Where are you

**Comment by offbeat-stuff** [comment]
this permission needs to be enable in android settings

**Comment by Waxbyz** [comment]
I turned on the microphone resolution for pojavlauncher in the settings but nothing works

**Comment by offbeat-stuff** [comment]
in android got to apps -> then pojav launcher -> then permissions and enable the microphone permission.
btw i personally use the simple voice chat mod so i am not sure whether that yours will work and try to not be in a call in any other app because that will interfere with pojav launcher's ability to record voice

**Comment by offbeat-stuff** [comment]
@Axon-waxby try it

**Comment by offbeat-stuff** [comment]
btw what are you playing on?? a server
make sure there are no network problems

**Comment by Waxbyz** [comment]
Okay I'll check if I have a network problem

**Comment by Waxbyz** [comment]
@offbeat-stuff in what sense is it "what are you playing on?"

**Comment by offbeat-stuff** [comment]
its only the plasmo voice chat that does not work right?
you can play normally on the server right?
can you also send some screenshots?

**Comment by offbeat-stuff** [comment]
on a server that you own yourself or on a server somebody else has

**Comment by offbeat-stuff** [comment]
Also if you are playing single player just try to not use the mod

**Comment by Waxbyz** [comment]
1.Only plasmovoice does not work
2. I can't play singl player at all, not multiplayer. 
3. 
![Screenshot_20220428_172743_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/104303336/166100036-67f94e8e-9bad-4771-97ce-e6bef3b9ecee.jpg)
4.The server is owned by someone else.

**Comment by offbeat-stuff** [comment]
try to install this mod https://modrinth.com/mod/notenoughcrashes
for better crash support
Also I would highly suggest removing the plasmo mod.
Its not worth the effort

**Comment by offbeat-stuff** [comment]
also i could not find a error message so it is probably that plasmo voice mod will not work for you

**Comment by offbeat-stuff** [comment]
you should just remove it from your mods. If you voice chat simple voice chat works

**Comment by offbeat-stuff** [comment]
If you still want to try can you send these files
Pojavlauncher/.minecraft/logs/latest.log
and
Pojavlauncher/.minecraft/.minecraft/crash-reports/[the newest file]

**Comment by Waxbyz** [comment]
OkThanks for your efforts to help me! So long.

**Comment by Waxbyz** [comment]
(https://github.com/PojavLauncherTeam/PojavLauncher/files/8596583/crash-2022-04-30_08.12.43-client.txt)

**Comment by Waxbyz** [comment]
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8596656/latest.log)

**Comment by artdeell** [comment]
Voice mods are not fully supported yet due to hardware opus encoding
