### ISSUE TITLE
[F-Req] Hideable buttons

### ISSUE THREAD

**Issue by noobimpostor2** [PojavLauncherTeam/PojavLauncher#3160]
![IMG_20220430_084341](https://user-images.githubusercontent.com/102277316/166088394-1ab4e75b-bcf3-45c9-81c2-ab8899b5f149.jpg)

See, you can see here 3 checkboxes

Add one more checkbox "Hideable" 
Default: checked 
When unchecked , on pressing GUI button , it won't hide the button unchecked

### Anything else?

_gasps_

**Comment by mchnjt** [comment]
@Mathias-Boulay

**Comment by Mathias-Boulay** [comment]
Meh, drawers exists.

**Comment by noobimpostor2** [comment]
> Meh, drawers exists.

Yaaaaouch @Mathias-Boulay i not mean drawer

Drawer exists I know

See, I am giving brief information:-
1) When GUI button clicked , all buttons get hidden including drawers

2) Add new Boolean checkbox for Hideable buttons

This Boolean apply to all buttons , all drawers
Default checkbox is checked

3) on checkbox checked: it will hide button on GUI button pressed, all buttons with checkbox will be get hidden after clicking GUI button

4) on checkbox unchecked: this buttons will be still visible even if GUI button clicked

**Comment by Mathias-Boulay** [comment]
My statement doesn't change actually.
Such behavior could be mimicked through clever usage of drawers

**Comment by noobimpostor2** [comment]
Idk and idc why you saying this. But Hideable buttons are independent
feature from drawers feature.
