### ISSUE TITLE
[BUG] Text and render issues 1.18.2

### ISSUE THREAD

**Issue by acocalypso** [PojavLauncherTeam/PojavLauncher#3161]
### Describe the bug

Main screen is not showing text and in-game rending issues occur

### The log file and images/videos

There is no log file available on my device

![Screenshot_20220430-090910](https://user-images.githubusercontent.com/2846629/166096020-7b913911-c607-45a2-b3e4-951f9be22075.jpg)
![Screenshot_20220430-091025](https://user-images.githubusercontent.com/2846629/166096024-f270d6aa-49cb-4334-9516-9e2ff1c193cf.jpg)

### Steps To Reproduce

```markdown
1. Start launcher
2. Select Profil with 1.18.2 (tried both renderer)
```

### Expected Behavior

Show UI elements and render textures

### Platform

```markdown
- Device model: OnePlus 8t
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: Version crocus-513-1d4df6d78-v3_openjdk
```

**Comment by ghost** [comment]
same for 1 17 1
virgl gives these bugs for some reason
and when using 2.1
cloud lags and artefacts

**Comment by offbeat-stuff** [comment]
dont use virgl use gl4es holy

**Comment by acocalypso** [comment]
I'm using gl4es. The screenshots are taken while using this renderer.

**Comment by acocalypso** [comment]
> same for 1 17 1 virgl gives these bugs for some reason and when using 2.1 cloud lags and artefacts

I tested 1.17.1 and also have the same issue with Virgo and gl4es.

1.16 is working fine.

**Comment by offbeat-stuff** [comment]
you should send the Pojavlauncher/.minecraft/logs/latest.log
@acocalypso
