### ISSUE TITLE
small question 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#3163]
### Is this request related to a bug?

Why I'm asking this: I have a smartphone with a kirin processor. And when playing minecraft with VirGl, a lot of OpenGL errors pop up, and with shaders (even the lightest as built into optifine) even more errors and the following errors occur when starting shaders: just a white screen, a crash, poor shader rendering. But there is no such thing with the renderer vulkan, but vulkan, although it works almost without problems, but has poor optimization. 

### Describe the request.

Are there renderers that work properly with kirin processors and export OpenGL 4.0+?

**Comment by GaucovyAero** [comment]
I really appreciate your effort, and it's a really good question. For now, there's not a renderer like that implemented in pojav. It's mostly about the fact that your GPU is different from Snapdragon devices and doesn't support the extensions that the Minecraft shaders require. It's basically like having a PC GPU from 2006 run new AAA games on PC. They don't support the GL extensions that the games' shaders/graphics require.
