### ISSUE TITLE
No Deja jugar las versiones 1.17 i hacia arriba

### ISSUE THREAD

**Issue by Minecra7557** [PojavLauncherTeam/PojavLauncher#3165]
### Describe the bug

No deja jugar de versiones 1.17 a 1.18.2. 
Me salta el error: no se pudo encontrar ningun java runtime.
Solucionenlo porfa

### The log file and images/videos

![Screenshot 2022-04-30 10 28 33 PM](https://user-images.githubusercontent.com/104592308/166121602-fe2cfbca-5175-4a6e-bc79-ca02a70f3428.png)

### Steps To Reproduce

```markdown
1.Inicie Pojav Laucher
2.Seleccione el boton para cambiar de version
3.Elija una berson desde la 1.17 hacia arriba
4.Seleccione Jugar/Play I se mostrara el error
```

### Expected Behavior

Espero que se pueda jugar esas bersiones del juego

### Platform

```markdown
- Device model: Chrome Os / Linux
- CPU architecture: 1.10 GHz
- Android version: 
- PojavLauncher version: Ultima version
```

**Comment by offbeat-stuff** [comment]
that is quite a good cpu architecture.
Also you should send the actual log

**Comment by artdeell** [comment]
Invalid
