### ISSUE TITLE
[BUG] <an error occurred while downloading the version>

### ISSUE THREAD

**Issue by GlitchAlpha000** [PojavLauncherTeam/PojavLauncher#3167]
### Describe the bug

when you want to download the version an error occurs and can't play on a local account.

### The log file and images/videos

![Uploading Screenshot_2022-05-01-13-21-41-98.png…]()

### Steps To Reproduce

```markdown
1.when i log in to pojav as usual i create an account with a local account 
 
2.when you want to download the version there is an error writing.

3.with writing ERROR
  
Minecraft can't be legally installed when logged in with a local account.
please switch to an online account to continue.
```

### Expected Behavior

hopefully in the future you can play with a local account without having to use a premium or online account.

### Platform

```markdown
- Device model: oppo a37f 2/16G
- CPU architecture: aarch64
- Android version: 5.1.1
- PojavLauncher version:rilis terbaru || versi crocus-513-1d4df6d78-v3_openjdk
```

### Anything else?

before, when there was no bug that I told you about, a bug occurred, namely when installing optifine and entering the downloaded version, the application/game writing often came out with code -1. and until now the bug is still there.

**Comment by GlitchAlpha000** [comment]
please fix the bug

**Comment by Comy112** [comment]
You can't play with local account, go buy java, its not expensive. 
Untill then, don't ever make a comment here.

**Comment by khanhduytran0** [comment]
> please fix the bug

This is not a bug, but rather an expected behavior.
You have to buy Minecraft to fix this.

**Comment by ghost** [comment]
> > لطفا اشکال را برطرف کنید
> 
> این یک اشکال نیست، بلکه یک رفتار مورد انتظار است. برای رفع این مشکل باید Minecraft بخرید.

T-Launcher is not like that

**Comment by ThePangel** [comment]
This is not T-Launcher lol

**Comment by ghost** [comment]
> This is not T-Launcher lol

Why doesn't Minecraft sue them?
LOL?

**Comment by mchnjt** [comment]
> > This is not T-Launcher lol
> 
> Why doesn't Minecraft sue them? LOL?

@SMAAMX If you didn't know, this project was on the verge of getting terminated after one Microsoft employee dmed @crystall1nedev via email. This is the reason why we removed offline mode

**Comment by ghost** [comment]
> > > این T-Launcher نیست lol
> > 
> > 
> > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> 
> @SMAAMXاگر نمی‌دانستید، این پروژه پس از dm یکی از کارمندان مایکروسافت در آستانه پایان یافتن بود@crystall1nedevاز طریق ایمیل. این دلیلی است که ما حالت آفلاین را حذف کردیم

Microsoft does not have the right to do this because it has never created Minecraft for Android (arm)

**Comment by ThePangel** [comment]
> > > > این T-Launcher نیست lol
> > > 
> > > 
> > > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> > 
> > @SMAAMXاگر نمی‌دانستید، این پروژه پس از dm یکی از کارمندان مایکروسافت در آستانه پایان یافتن بود@crystall1nedevاز طریق ایمیل. این دلیلی است که ما حالت آفلاین را حذف کردیم
> 
> Microsoft does not have the right to do this because it has never created Minecraft for Android (arm)

Do you know what Minecraft pocket edition is, even if they didn't make it Minecraft is THEIR trademark

**Comment by ghost** [comment]
> > > > > این T-Launcher نیست lol
> > > > 
> > > > 
> > > > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> > > 
> > > 
> > > @SMAAMXاگر نمی‌دانستید، این پروژه پس از dm یکی از کارمندان مایکروسافت در آستانه پایان یافتن بود@crystall1nedevاز طریق ایمیل. این دلیلی است که ما حالت آفلاین را حذف کردیم
> > 
> > 
> > Microsoft does not have the right to do this because it has never created Minecraft for Android (arm)
> 
> Do you know what Minecraft pocked edition is, even if they didn't make it Minecraft is THEIR trademark

Yes, but not Java

**Comment by mchnjt** [comment]
> > > > این T-Launcher نیست lol
> > > 
> > > 
> > > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> > 
> > 
> > @SMAAMXاگر نمی‌دانستید، این پروژه پس از dm یکی از کارمندان مایکروسافت در آستانه پایان یافتن بود@crystall1nedevاز طریق ایمیل. این دلیلی است که ما حالت آفلاین را حذف کردیم
> 
> Microsoft does not have the right to do this because it has never created Minecraft for Android (arm)

Microsoft has the legal rights because Notch, the original creator of the game, selled the game to Microsoft.

**Comment by ThePangel** [comment]
> > > > > > این T-Launcher نیست lol
> > > > > 
> > > > > 
> > > > > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> > > > 
> > > > 
> > > > @SMAAMXاگر نمی‌دانستید، این پروژه پس از dm یکی از کارمندان مایکروسافت در آستانه پایان یافتن بود@crystall1nedevاز طریق ایمیل. این دلیلی است که ما حالت آفلاین را حذف کردیم
> > > 
> > > 
> > > Microsoft does not have the right to do this because it has never created Minecraft for Android (arm)
> > 
> > Do you know what Minecraft pocked edition is, even if they didn't make it Minecraft is THEIR trademark
> 
> Yes, but not Java

Doesn't make a difference it's their game

**Comment by ghost** [comment]
> > > > > > > این T-Launcher نیست lol
> > > > > > 
> > > > > > 
> > > > > > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> > > > > 
> > > > > 
> > > > > @SMAAMXاگر نمی‌دانستید، این پروژه از dm یکی از افراد مایکروسافت در آستانه پایان یافتن بود.@crystall1nedevاز طریق ایمیل. این دلیل است که ما حالت آفلاین را حذف کنیم
> > > > 
> > > > 
> > > > مایکروسافت حق انجام این کار را ندارد زیرا هرگز Minecraft را برای اندروید (بازو) ایجاد نکرده است.
> > > 
> > > 
> > > آیا می دانید نسخه pocked Minecraft چیست، حتی اگر آنها آن را نساختند Minecraft علامت تجاری آنها است
> > 
> > 
> > بله، اما نه جاوا
> 
> فرقی نمی کند بازی آنهاست

Although T-Launcher has not been complained about this, sorry I asked this question

**Comment by ThePangel** [comment]
> > > > > > > > این T-Launcher نیست lol
> > > > > > > 
> > > > > > > 
> > > > > > > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> > > > > > 
> > > > > > 
> > > > > > @SMAAMXاگر نمی‌دانستید، این پروژه از dm یکی از افراد مایکروسافت در آستانه پایان یافتن بود.@crystall1nedevاز طریق ایمیل. این دلیل است که ما حالت آفلاین را حذف کنیم
> > > > > 
> > > > > 
> > > > > مایکروسافت حق انجام این کار را ندارد زیرا هرگز Minecraft را برای اندروید (بازو) ایجاد نکرده است.
> > > > 
> > > > 
> > > > آیا می دانید نسخه pocked Minecraft چیست، حتی اگر آنها آن را نساختند Minecraft علامت تجاری آنها است
> > > 
> > > 
> > > بله، اما نه جاوا
> > 
> > فرقی نمی کند بازی آنهاست
> 
> Although T-Launcher has not been complained about this, sorry I asked this question

Probably cause it's not worth Microsofts time since it's easy to pirate java edition
Just use a VPN bro

**Comment by ghost** [comment]
> > > > > > > > > این T-Launcher نیست lol
> > > > > > > > 
> > > > > > > > 
> > > > > > > > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> > > > > > > 
> > > > > > > 
> > > > > > > @SMAAMXاگر نمی‌دانستید، این پروژه از dm یکی از افراد مایکروسافت در آستانه پایان یافتن بود.@crystall1nedevاز طریق ایمیل. این دلیل است که ما حالت آفلاین را حذف کنیم
> > > > > > 
> > > > > > 
> > > > > > مایکروسافت حق انجام این کار را ندارد زیرا هرگز Minecraft را برای اندروید (بازو) ایجاد نکرده است.
> > > > > 
> > > > > 
> > > > > آیا می دانید نسخه pocked Minecraft چیست، حتی اگر آنها آن را نساختند Minecraft علامت تجاری آنها است
> > > > 
> > > > 
> > > > بله، اما نه جاوا
> > > 
> > > 
> > > فرقی نمی کند بازی آنهاست
> > 
> > 
> > Although T-Launcher has not been complained about this, sorry I asked this question
> 
> Probably cause it's not worth Microsofts time since it's easy to pirate java edition Just use a VPN bro

I will use it, but pirates in the Bedrock version are also easily possible

**Comment by ThePangel** [comment]
> > > > > > > > > > این T-Launcher نیست lol
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > چرا Minecraft از آنها شکایت نمی کند؟ LOL؟
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @SMAAMXاگر نمی‌دانستید، این پروژه از dm یکی از افراد مایکروسافت در آستانه پایان یافتن بود.@crystall1nedevاز طریق ایمیل. این دلیل است که ما حالت آفلاین را حذف کنیم
> > > > > > > 
> > > > > > > 
> > > > > > > مایکروسافت حق انجام این کار را ندارد زیرا هرگز Minecraft را برای اندروید (بازو) ایجاد نکرده است.
> > > > > > 
> > > > > > 
> > > > > > آیا می دانید نسخه pocked Minecraft چیست، حتی اگر آنها آن را نساختند Minecraft علامت تجاری آنها است
> > > > > 
> > > > > 
> > > > > بله، اما نه جاوا
> > > > 
> > > > 
> > > > فرقی نمی کند بازی آنهاست
> > > 
> > > 
> > > Although T-Launcher has not been complained about this, sorry I asked this question
> > 
> > Probably cause it's not worth Microsofts time since it's easy to pirate java edition Just use a VPN bro
> 
> I will use it, but pirates in the Bedrock version are also easily possible

Not as

**Comment by inari-codes** [comment]
Then i have to play the dreadful Bedrock Edition which s**** a lot? I don't want to run a virtual machine in my phone just to get tlauncher or a obscure chinese minecraft java launcher to make my phone explode

**Comment by ThePangel** [comment]
> Then i have to play the dreadful Bedrock Edition which s**** a lot? I don't want to run a virtual machine in my phone just to get tlauncher or a obscure chinese minecraft java launcher to make my phone explode

Then f**king buy java bro and don't cry

**Comment by vanistillhere** [comment]
> Then i have to play the dreadful Bedrock Edition which s**** a lot? I don't want to run a virtual machine in my phone just to get tlauncher or a obscure chinese minecraft java launcher to make my phone explode

whats so bad about it lololol

**Comment by Therealrex** [comment]
Same Thing Happened To Me :[

**Comment by ThePangel** [comment]
> Same Thing Happened To Me :[

Just buy java 🤷
