### ISSUE TITLE
[BUG] <Short description> 1.16.1 optfine crashes at black screen

### ISSUE THREAD

**Issue by vFireRate** [PojavLauncherTeam/PojavLauncher#3168]
### Describe the bug

i playing 1.16.1 optifine, after 3 second the game crashes with code 1, how to fix this?

### The log file and images/videos

Uploading 

- [ ] mobizen_20220501_143507.mp4…

### Steps To Reproduce

```markdown
1. Start PojavLauncher
...the game crashes
```

### Expected Behavior

I expect the game launches

### Platform

```markdown
- Device model: Mi 3 3/128gb
- CPU architecture: aarch64 
- Android version: 6.0/1 
- PojavLauncher version: Lastest version on google play
```

**Comment by vFireRate** [comment]
bruh

**Comment by WesleyVanNeck** [comment]
Use the action build

**Comment by WesleyVanNeck** [comment]
Not play store

**Comment by vFireRate** [comment]
> Not play store

oh thankyou
you mean the debug version?

**Comment by kuzy21** [comment]
Turn off clouds in settings before interning any world of server

**Comment by vFireRate** [comment]
> Turn off clouds in settings before interning any world of server

my games freezes at the black screen(before Mojang screen)

**Comment by artdeell** [comment]
Fixed
