### ISSUE TITLE
Mouse issue? [BUG]

### ISSUE THREAD

**Issue by Temperrr6969** [PojavLauncherTeam/PojavLauncher#3170]
### Describe the bug

Once the game has loaded and hover over an option for example options and you get close to quit game it highlight quit game when the cursor is not on it. I have attached an image and screen recording of my issue. (I think I done it correctly anyway)

### The log file and images/videos

![Screenshot_20220501-131647_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/47488976/166145625-7aa4dfc7-5ffd-41b3-b0b9-c5f23b0e498f.jpg)

https://user-images.githubusercontent.com/47488976/166145633-3e40ce00-8251-4e72-afd6-f67288391728.mp4

### Steps To Reproduce

```markdown
Start minecraft

Hover over a button with cursor close to another thats next to it
```

### Expected Behavior

Cursor works fine

### Platform

```markdown
- Device model: Samsung galaxy s10+/128GB
- CPU architecture: aarch64/arm64
- Android version: 12
- PojavLauncher version: latest build
```

**Comment by offbeat-stuff** [comment]
At least it it somewhat working for you.
For me mouse does not work

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
