### ISSUE TITLE
microphone permission

### ISSUE THREAD

**Issue by sky-sunnext** [PojavLauncherTeam/PojavLauncher#3174]
### Is this request related to a bug?

Some mods need recording. Can you add microphone permission

**Comment by kuzy21** [comment]
There already made a version of pojavlauncher with microphone permission

**Comment by offbeat-stuff** [comment]
you just have to enable the permission in settings v3_openjdk has the feature
@pcl-aacin

**Comment by sky-sunnext** [comment]
ok , thank you! (I am a Chinese, and my English is a little non-standard)

**Comment by sky-sunnext** [comment]
oh , sorry . I am a new person who has just come into contact with pojav, and I don't know how to operate it. Can you please make a tutorial and send it to my mailbox 3304457468@qq.com or kingstarjun@gmail.com? Thank you!

**Comment by artdeell** [comment]
Added

**Comment by Nitidez** [comment]
> There already made a version of pojavlauncher with microphone permission

Where is this version
