### ISSUE TITLE
[BUG] when i disconnect of a server game stop responding

### ISSUE THREAD

**Issue by SlowOnARocket** [PojavLauncherTeam/PojavLauncher#3175]
### Describe the bug

Just crashes and thats it seems to happen less on cheatbreaker2.0 1.7.10
device Samsung Galaxy tab a7
Renderer The renderer that isn't virgil

### The log file and images/videos

[https://www.mediafire.com/file/6vrasm8ytiw4evf/latestlog.txt/file](url) my latest log

### Steps To Reproduce

```markdown
1. Start Pojav
2. Launch any 1.8.9 client (in my case Lunar)
3. connect to any server 
4. disconect
5. if it dont bug try connecting to another server 
6. U should see the bug
```

### Expected Behavior

The game to dont freeze when i change the server or disconnect

### Platform

```markdown
- Device model: samsung galaxy tab a7
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

please help

**Comment by GaucovyAero** [comment]
For some reason, I can't click on the mediafire link you sent, because it redirects me to GitHub (i'm on a phone), but this freeze issue you have has happened to multiple phones and I'm pretty sure it hasn't been resolved yet. Try updating to the latest Actions build.

**Comment by PayToUse** [comment]
Maybe you use virgl renderer

**Comment by SlowOnARocket** [comment]
I use Gl4es

**Comment by SlowOnARocket** [comment]
https://www.mediafire.com/file/6vrasm8ytiw4evf/latestlog.txt/file here's the link

**Comment by SlowOnARocket** [comment]
849 mb

**Comment by KentangGG121** [comment]
Same with me on my case i use 1.12.2 for multiplayer after i disconect it not responding!

**Comment by Mathias-Boulay** [comment]
Fixed in the current candidate release
