### ISSUE TITLE
[BUG] BLACK SCREEN VIRGL.

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#3177]
### Describe the bug

When pressing play to any version even though im waiting for 10 minutes its nothing showing up but it has Sound to the Minecraft song any when im clicking anywhere I've been hearing an menu sound but its pure black screen.

### The log file and images/videos

Here! 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8607432/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojav launcher
Play any version
Black screen 
But theres a sound.
```

### Expected Behavior

I was expecting it to show on the Minecraft menu screen

### Platform

```markdown
- Device model: Oppo a12 3/32
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version:latest&old build
```

### Anything else?

What should I do to make it work again.
Pojav launcher virgl is working at my phone last time 
But not anymore:/

**Comment by ajit56** [comment]
I fixed this issue for myself by disabling developer option

**Comment by artdeell** [comment]
VirGL is  not fully supported
