### ISSUE TITLE
[BUG] Forge 40.1.0 - Minecraft 1.18.2,  mods.securejarhandler not found

### ISSUE THREAD

**Issue by BenjD90** [PojavLauncherTeam/PojavLauncher#3179]
### Describe the bug

Hello,

I'm trying to run Minecraft forge v 40.1.0 on Android : Samsung S20FE
I tried on the play store version, then on the latest build, I tried on this one : https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2237921247

I get this error : 
`Module cpw.mods.securejarhandler not found, required by cpw.mods.bootstraplauncher`

The forge installation ran fine, and was easy to run !
Thanks for this project, it rock's !

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-517-de0125392-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2312
Added custom env: POJAV_NATIVEDIR=/data/app/~~JakOdESlEhY_-2tQvBwvHw==/net.kdt.pojavlaunch.debug-ipTXuDi0a5PdsAwBZcbUww==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~JakOdESlEhY_-2tQvBwvHw==/net.kdt.pojavlaunch.debug-ipTXuDi0a5PdsAwBZcbUww==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/LIBGL   (21911): Initialising gl4es
I/LIBGL   (21911): v1.1.4 built on Apr 28 2022 08:00:50
I/LIBGL   (21911): Using GLES 2.0 backend
I/LIBGL   (21911): loaded: libGLESv2.so
I/LIBGL   (21911): loaded: libEGL.so
I/LIBGL   (21911): Using GLES 2.0 backend
I/LIBGL   (21911): Hardware Full NPOT detected and used
I/LIBGL   (21911): FBO are in core, and so used
I/LIBGL   (21911): PointSprite are in core, and so used
I/LIBGL   (21911): CubeMap are in core, and so used
I/LIBGL   (21911): BlendColor is in core, and so used
I/LIBGL   (21911): Blend Substract is in core, and so used
I/LIBGL   (21911): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (21911): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (21911): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (21911): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (21911): Extension GL_OES_depth24  detected and used
I/LIBGL   (21911): Extension GL_OES_rgb8_rgba8  detect
ed and used
I/LIBGL   (21911): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (21911): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (21911): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (21911): Extension GL_OES_texture_float  detected and used
I/LIBGL   (21911): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (21911): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (21911): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (21911): high precision float in fragment shader available and used
I/LIBGL   (21911): Max vertex attrib: 32
I/LIBGL   (21911): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (21911): Max texture size: 16384
I/LIBGL   (21911): Max Varying Vector: 31
I/LIBGL   (21911): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (21911): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (21911): Max Anisotropic filtering: 16

I/LIBGL   (21911): Hardware vendor is Qualcomm
I/LIBGL   (21911): GLSL 300 es supported
I/LIBGL   (21911): GLSL 310 es supported and used
I/LIBGL   (21911): GLSL 320 es supported
I/LIBGL   (21911): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (21911): sRGB surface supported
I/LIBGL   (21911): EGLImage to Texture2D supported
I/LIBGL   (21911): EGLImage to RenderBuffer supported
I/LIBGL   (21911): ignore MipMap
I/LIBGL   (21911): Targeting OpenGL 2.1
I/LIBGL   (21911): No hack in shader converter to define overloaded function with int
I/LIBGL   (21911): NPOT texture handled in hardware
I/LIBGL   (21911): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (21911): try to use VBO
I/LIBGL   (21911): glX Will try to recycle EGL Surface
I/LIBGL   (21911): Current folder is:/
I/jrelog  (21911): dlopen libgl4es_114.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  (21911): dlopen libjvm.so failed: dlop
en failed: library "libjvm.so" not found
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (21911): dlopen /data/user/0/
net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.
tar.xz/lib/libsyslookup.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  (21911): dlopen /data/user/0
/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pk
cs11.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.
debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (21911): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  (21911): dlopen /data/app/~~JakOdESlEhY_-2tQvBwvHw==/net.kdt.pojavlaunch.debug-ipTXuDi0a5PdsAwBZcbUww==/lib/arm64/lib
openal.so success
I/jrelog  (21911): Done processing args
I/jrelog  (21911): Found JLI lib
I/jrelog  (21911): Calling JLI_Launch

Exception in thread "main" 
java.lang.module.FindException: Module cpw.mods.securejarhandler not found, required by cpw.mods.bootstraplauncher
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:492)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:137)
Java Exit code: 1
I/jrelog  (21911): Going to free args

I/jrelog  (21911): Free done

### Steps To Reproduce

```markdown
1. Install latest build
2. Install forge 40
3. Configure to run it with JRE 1.17 as explained in the documentation and the good renderer
4. Run the script
```

### Expected Behavior

I expect to see the game launching

### Platform

```markdown
- Device model: S20 FE
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Version crocus-517-de0125392-v3_openjdk
```

**Comment by artdeell** [comment]
Fixed on latest

**Comment by SavageTheUnicorn** [comment]
This issue has come back again in the latest build!
