### ISSUE TITLE
[F-Req] <Short description>下载版本时一并下载forge/fabric

### ISSUE THREAD

**Issue by RzdPai** [PojavLauncherTeam/PojavLauncher#3180]
### Is this request related to a bug?

forge/fabric安装太麻烦，而且新版本mod安装器有问题

### Describe the request.

在添加版本时，一并选择forge/fabric

### Anything else?

https://github.com/Tungstend/forge-install-bootstrapper

**Comment by artdeell** [comment]
Won't be imeplemented due to the availability of the GUI installer
