### ISSUE TITLE
[F-Req] About microsoft account

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#3181]
### Is this request related to a bug?

Yes, I think

### Describe the request.

*This is not a feature request*
I just want to ask how do am I supposed to use microsoft account that is not migrated from mojang account? Because I don't have mojang account.

### Anything else?

#3040 motivated me to ask this question

**Comment by kuzy21** [comment]
Buy java edition = account for minecraft java edition.

-note if you have a monjang account you will need to migrated it to a Microsoft account.

**Comment by miggythewriter** [comment]
Imagine asking the dumbest questions ever

**Comment by Thollp** [comment]
> Imagine asking the dumbest questions ever

Shut up. I'm not that dumb to ask that question

**Comment by Thollp** [comment]
> Buy java edition = account for minecraft java edition.
> 
> -note if you have a monjang account you will need to migrated it to a Microsoft account.

Thx
