### ISSUE TITLE
[BUG] <the mouse doesn't have enough fps>

### ISSUE THREAD

**Issue by santoruplay** [PojavLauncherTeam/PojavLauncher#3182]
### Describe the bug

when connecting the mouse to the phone (poco x3 pro), everything works well. When I entered the world (it doesn't matter in solitary or not in solitary), the mouse, when viewed in the world, begins to twitch, teleport. As if the mouse just doesn't have enough fps. I tried to connect the mouse to my friends' phones, everything works fine for them. Please help fix the bug

### The log file and images/videos

the video that describes my problem:

https://drive.google.com/file/d/1QLEWoFLbQCkOp4Y2Sbou9nhdQdaiTx2D/view?usp=drivesdk

### Steps To Reproduce

```markdown
connecting the mouse to the phone, launching pojavlauncher, launching the version
```

### Expected Behavior

to make the mouse work smoothly and without lags

### Platform

```markdown
- Device model: Poco x3 pro 6/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest version
```

**Comment by kuzy21** [comment]
Use an older version holy edition because someone broke the code of one of the newer versions

**Comment by santoruplay** [comment]
> Use an older version holy edition because someone broke the code of one of the newer versions

I didn't really understand, my version was downloaded from the play store. How do I install the "older" version?

**Comment by offbeat-stuff** [comment]
use dev builds
From here https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk+is%3Asuccess
pick your poison

**Comment by santoruplay** [comment]
> используйте dev-сборки отсюда [https://github.com/PojavLauncherTeam/PojavLauncher/actions ?query=branch%3Av3_openjdk+is%3Asuccess](https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk+is%3Asuccess) выбери свой яд

thank you very much, everything worked out right for me, I am grateful to you
