### ISSUE TITLE
[MOUSE] <mouse is not responding. try to fix it again>

### ISSUE THREAD

**Issue by NictZzzOwO** [PojavLauncherTeam/PojavLauncher#3184]
PLS FIX 
/\_/\
( •~•)
/>❤

### The log file and images/videos

![Screenshot_20220504-001649_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/104856835/166505719-f3c9fed6-2f53-4da6-9ac4-51372a9142a8.jpg)
![Screenshot_20220504-001646_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/104856835/166505748-6b442a4c-42ca-4873-895e-8bf546349ff9.jpg)

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Select 1.16.5 fabric+optifine
3.Use the mouse
4.See the bug
```

### Expected Behavior

maybe it's because of my phone specs (btw my minecraft not getting lag) . and I've seen how to fix it on youtube. but it doesn't work

### Platform

```markdown
- Device model: SM J7 Core 2/16GB
- CPU architecture: 8x ARM Cortex-A53 @ 1,59 GHz
- Android version: 9
- PojavLauncher version:[Latest Release||version 3.3.1.1_rel_20210206]
```

**Comment by offbeat-stuff** [comment]
that is an amazing looking control setup

**Comment by offbeat-stuff** [comment]
It is kinda unclear what your bug is but ill assume it is the mouse click is not registered by game.
It is happening to me too and could not fix it in the latest build.
you probably should download a old build of pojavlauncher.
