### ISSUE TITLE
[BUG]Crash

### ISSUE THREAD

**Issue by Krrotp0** [PojavLauncherTeam/PojavLauncher#3188]
### Describe the bug

Hello, I'm a Korean who enjoys spore bruncher. I played the game today, and when suddenly the server comes in, it crashes a lot, and I go to the personal wild server and it crashes. 

### The log file and images/videos

Crash,lag fix plz...

### Steps To Reproduce

```markdown
1.crash fix
2.lag fix
```

### Expected Behavior

If this bug continues, the spore bruncher will not work. 

### Platform

```markdown
<font class="papago-parent"><font class="papago-source" style="display:none;">- Device model: 
</font>- 장치 모델:</font><font class="papago-parent"><font class="papago-source" style="display:none;">- CPU architecture: 
</font>- CPU 아키텍처:</font><font class="papago-parent"><font class="papago-source" style="display:none;">- Android version: 
</font>- Android 버전:</font><font class="papago-parent"><font class="papago-source" style="display:none;">- PojavLauncher version: 
</font>- PojavLauncher 버전:</font>
```

### Anything else?

It just crashes with lag

**Comment by offbeat-stuff** [comment]
latest.log ???

**Comment by Mathias-Boulay** [comment]
invalid, update to the latest build
