### ISSUE TITLE
[BUG] Endless "Wait" message when installing any .jar file

### ISSUE THREAD

**Issue by ShpyliukOleksii** [PojavLauncherTeam/PojavLauncher#3189]
### Describe the bug

Issue happens when i try to install any .jar file. My phone model is Poco X3 
I use Android CI#3801 build
I tried:
-optifine 1.16.5 G8/optifine 1.16.5 G7
-reinstalling the app
-clearing cache
-fabric 1.16.5

### The log file and images/videos

![Screenshot_2022-05-04-02-57-54-022_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/94637900/166605786-4f8fa0a1-b7f2-4ec7-a9ec-b2918b94a1c8.jpg)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Try to install any .jar file
```

### Expected Behavior

Was expected to install 1.16.5 optifine

### Platform

```markdown
- Device model: Poco X3 Pro
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: Android CI#3801
```

**Comment by khanhduytran0** [comment]
This is currently a known issue on Vertical UI builds. Please switch back to v3 builds (branch `v3_openjdk`)
