### ISSUE TITLE
[F-Req] Please fix pojav in playstore

### ISSUE THREAD

**Issue by GlitchAlpha000** [PojavLauncherTeam/PojavLauncher#3190]
### Describe the request.

i want pojav in playstore to fix the problem of force closing when entering version in pojav .

**Comment by GlitchAlpha000** [comment]
every time i enter verai in pojav in play store and enter world always force close

**Comment by GlitchAlpha000** [comment]
sorry i mean version

**Comment by kuzy21** [comment]
Use github version, it's more updated, also use an older build of pojav because the newer builds have a broken build

**Comment by WesleyVanNeck** [comment]
> Use github version, it's more updated, also use an older build of pojav because the newer builds have a broken build

for you its broken for most of us it aint

**Comment by kedrick022** [comment]
Turn off your data or wifi
