### ISSUE TITLE
[BUG] <ps3 controller doesn't work with pojav>

### ISSUE THREAD

**Issue by LostCat123** [PojavLauncherTeam/PojavLauncher#3191]
### Describe the bug

Only the joy stick, l3, r3 and a b y x are working. Please make it that we can disable the controller feature.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8617804/latestlog.txt)

### Steps To Reproduce

```markdown
Just plug your controller
```

### Expected Behavior

I expect the l2 and r2 and the other buttons to work

### Platform

```markdown
- Device model:r5x 
- CPU architecture:aarch64
- Android version:12
- PojavLauncher version:crocus-522-9fa912c41
```

### Anything else?

Nothing

**Comment by WesleyVanNeck** [comment]
Then you don't have a normal Xbox or playstation controller

**Comment by LostCat123** [comment]
> Then you don't have a normal Xbox or playstation controller

I was just asking if you can make it so that we can disable it, and all the gamepad tester shows that it's fine

**Comment by GaucovyAero** [comment]
We indeed have gamepad support, but only for the official Xbox controller. If you want to use a different controller and it doesn't work correctly, you will have to root your phone with Magisk and install a Magisk module that allows controller key remapping.
