### ISSUE TITLE
[F-Req] <gamepad>

### ISSUE THREAD

**Issue by LostCat123** [PojavLauncherTeam/PojavLauncher#3192]
### Is this request related to a bug?

You should add a switch to turn on off the keyboard mouse/ gamepad support https://github.com/PojavLauncherTeam/PojavLauncher/issues/3191#issue-1224898777

### Describe the request.

Add a switch to turn on off that feature

### Anything else?

Nothing

**Comment by GaucovyAero** [comment]
We indeed have gamepad support, but only for the official Xbox controller. If you want to use a different controller and it doesn't work correctly, you will have to root your phone with Magisk and install a Magisk module that allows controller key remapping.
