### ISSUE TITLE
[error] <tidak bisa login akun>

### ISSUE THREAD

**Issue by Xiontya** [PojavLauncherTeam/PojavLauncher#3193]
### Describe the bug

Ya

### The log file and images/videos

H

### Steps To Reproduce

```markdown
Y
```

### Expected Behavior

Y

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ruok9272** [comment]
LoL

**Comment by WesleyVanNeck** [comment]
@artdeell  close this invalid template and not English

**Comment by khanhduytran0** [comment]
@Xiontya buy Minecraft first (beli Minecraft dulu)
