### ISSUE TITLE
Bug installer.jar won't work in #3172

### ISSUE THREAD

**Issue by Shadowee12** [PojavLauncherTeam/PojavLauncher#3194]
### Describe the bug

Wait running for infinite time

### The log file and images/videos

Nothing

### Steps To Reproduce

```markdown
I click install jar and they wont work
```

### Expected Behavior

I wait for too long but it kept proceeding

### Platform

```markdown
- Device model: Redmi note7pro
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: #3172
```

### Anything else?

Please fix as soon

**Comment by GaucovyAero** [comment]
Yeah. Don't use the Vertical Fragment UI build. Rather use an older PojavLauncher build.

**Comment by petermg** [comment]
Can confirm this is broken in the vertical launcher.

**Comment by miggythewriter** [comment]
Install older builds

**Comment by offbeat-stuff** [comment]
@PrinceNormal Can you please direct me to the version that you use. Specifically send a link to action.
I have tried many versions of pojav launcher actions build after gl4es holy and they all either dont launch (shader error) or they just fail to respond to mouse or touch.
So please

**Comment by offbeat-stuff** [comment]
Okay nvm i found the version that worked
just after 6 days of searching

**Comment by miggythewriter** [comment]
If you need it here it ishttps://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2237921247

**Comment by miggythewriter** [comment]
Nvm you already found it

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
