### ISSUE TITLE
[BUG] <410 Error>

### ISSUE THREAD

**Issue by XavierErrorLog** [PojavLauncherTeam/PojavLauncher#3195]
### Describe the bug

Hello to whom is reading this I'm having a problem where when I try to sign in to my account it keeps saying 

Response Error
Code : 410
Message: {"error":"GoneException"
"errorMessage":"Migrated"}

### The log file and images/videos

Picture of error 
![Screenshot 2022-05-04 12 36 50 PM](https://user-images.githubusercontent.com/86020558/166733295-ded91154-214c-4938-992f-7f0a7490d9f2.png)

And a hotdog
![hotdog](https://user-images.githubusercontent.com/86020558/166733901-a7da5af3-47be-4187-9a2b-c9fab3d661cf.jpg)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Login into my account
3. Get th error code
```

### Expected Behavior

I expect to be able to login into my account

### Platform

```markdown
- Device model: Lenovo Chromebook Tablet Duet
- CPU architecture:aarch32 
- Android version:9
- PojavLauncher version:Playstore release
```

**Comment by offbeat-stuff** [comment]
that dog is quite hot
