### ISSUE TITLE
[BUG] <App/game exit with code 1>

### ISSUE THREAD

**Issue by ruok9272** [PojavLauncherTeam/PojavLauncher#3197]
### Describe the bug

App/game exit with code 1 when i use virgl renderer 4.3 in Samsung galaxy a01

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8629731/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open pojav launcher 
2. Select renderer to virgl renderer 4.3
3. Choose the game version and play
4. And there's a bug. in my phone
```

### Expected Behavior

I hope the bug is fixed

### Platform

```markdown
- Device model: Samsung Galaxy a01 2/16G
- CPU architecture: aarch32
- Android version: 11
- PojavLauncher version: version crocus-299-f1bd70996-v3_openjdk
```

**Comment by WesleyVanNeck** [comment]
There won't be updates on virgl

**Comment by ruok9272** [comment]
> There won't be updates on virgl


But why?
But will there be a vgpu update?

**Comment by WesleyVanNeck** [comment]
> > There won't be updates on virgl
> 
> But why? But will there be a vgpu update?

Vgpu got removed for holy gl4es

**Comment by ruok9272** [comment]
>

**Comment by ruok9272** [comment]
> > > There won't be updates on virgl
> > 
> > 
> > But why? But will there be a vgpu update?
> 
> Vgpu got removed for holy gl4es

So, there will be no vgpu update?
Right?
