### ISSUE TITLE
Preview 9 makes all versions unplayable

### ISSUE THREAD

**Issue by jrxohan** [PojavLauncherTeam/PojavLauncher#32]
In the new Preview 9 basically you cannot play any version from 1.7.10 onwards it cannot be played, when starting any version it launches a crash report

**Comment by emelin2004** [comment]
Same problem here,nothing works in preview9

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.9b1
