### ISSUE TITLE
[BUG] Some rendering glitch and bug

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3201]
### Describe the bug

(sorry for bad english)

transparent blocks like vines,grass,torch,etc. is rendered as opaque block

block entities like chest,ender chest,shulker box,bed,etc. become black when placed

some blocks and items become black in inventory

the player skin become black

enchantment glint gets bugged

but it doesn't crash

### The log file and images/videos

Launcher Log :
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8639210/latestlog.txt)

Game log :
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8639213/latest.log)

Images :
![Screenshot_20220506_170002](https://user-images.githubusercontent.com/104739729/167112161-f1d1b69a-6ccd-49a0-bc15-66ba896efa8c.jpg)
My survival world (copied from my laptop for testing)

![Screenshot_20220506_170019](https://user-images.githubusercontent.com/104739729/167112375-0386b068-b62f-4cf7-a736-ec7c86496f39.jpg)
Items inside my shulker box

![Screenshot_20220506_170047](https://user-images.githubusercontent.com/104739729/167112486-5def5412-37c3-4f23-85ba-73ce25fdd729.jpg)
Double chest and torch

![Screenshot_20220506_170123](https://user-images.githubusercontent.com/104739729/167114495-83ade6ab-1799-4f2d-9e42-217c90c39108.jpg)
Ender chest,shulker boxes and a bed

### Steps To Reproduce

```markdown
Just start pojavlauncher and start 1.18.2 normally

version : 1.18.2-OptiFine_HD_U_H7

renderer virglrenderer (OpenGL ES 3): exports OpenGL 4.3
ignore notch : off
resolution scaler : 75%
alternate surface rendering : off

java runtime : jdk17 i got from youtube
memory allocation : 800mb
JVM arguments : Xms800m -Xms800m Dorg.lwjgl.libname=libOsMesa.8.so

sustained performance mode : on
hide taskbar : off
check libraries : on
cosmetica capes : off

gl4es shrink hack : off

shaders is turned off
```

### Expected Behavior

just expected the game to process and render properly,like how it does in my laptop

### Platform

```markdown
- Device model: Vivo Y20 (V2027) 3/64
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest development version (from actions tab) crocus-519-321673e89- (9938647)
```

### Anything else?

I got the java 17 runtime [here](https://www.mediafire.com/file/rqsra3ub1l2agel/jdk17-aarch64.zip/file) 

Options file :
[options.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8639366/options.txt)
[optionsof.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8639367/optionsof.txt)

**Comment by artdeell** [comment]
You are using the wrong renderer. Please use gl4es 1.1.4 instead.

**Comment by Marshall2439** [comment]
Hey I am using Zink renderer but it's making random black rpolygons appear randomly anywhere can you guys tell me how do I fix it?  I cannot use create mod and stuff due to it

**Comment by GaucovyAero** [comment]
> Hey I am using Zink renderer but it's making random black rpolygons appear randomly anywhere can you guys tell me how do I fix it? I cannot use create mod and stuff due to it

you probably cant do anything about it

**Comment by Marshall2439** [comment]
Why

**Comment by Marshall2439** [comment]
Do you have any idea why is it happening it gives gl vertex attributer in chat

**Comment by Marshall2439** [comment]
Pls tell me

**Comment by GaucovyAero** [comment]
idk if mesa is the issue, create, or your phones driver

**Comment by Marshall2439** [comment]
So is there any way?

**Comment by GaucovyAero** [comment]
> So is there any way?

i dont have a phone thats capable of zink rn

**Comment by Marshall2439** [comment]
Which pojav version do you use? I think older versions had Zink support for idk every phone i guess

**Comment by Bel69420** [comment]
Old zink ran pretty slow than new zink, I'm not really recommend you for using old zink.

**Comment by Marshall2439** [comment]
Yeah ik that but that weird polygon thingy

**Comment by Bel69420** [comment]
Send a screenshot

**Comment by Marshall2439** [comment]
It would take time but okay

**Comment by Marshall2439** [comment]
![Uploading Screenshot_20231207_190515_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

**Comment by Marshall2439** [comment]
![Screenshot_20231207_190440_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets
![Screenshot_20231207_190420_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143608089/3baf6389-6c89-4e2b-86d7-1fef58bf9254)
/143608089/2e0fb466-cc87-4189-8c4b-5cbcc51abdbf)
![Screenshot_20231207_190424_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143608089/4c6f1855-a15e-4764-ae91-0a95ee59b631)

**Comment by Marshall2439** [comment]
Have a look
