### ISSUE TITLE
[1.18.2] Rendering & Runtime

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3202]
### Describe the bug

Hello,

I got a problem... I try to run mc on my chromebook with the pojav launcher.
1.17.1 works but 1.18.2 doesn't...
I use JAVA 17 x86_64 as runtime, gl4es 1.15.1 as renderer and  followed this steps...
https://pojavlauncherteam.github.io/updates/117.html#known-issues
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8643322/latestlog.txt)
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8643327/latestcrash.txt)

Crash:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/6/22, 7:47 PM
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:197)
Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00
0:10(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.a(SourceFile:421)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00
0:10(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version Android-9
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2029778720 bytes (1935 MiB) / 2304770048 bytes (2198 MiB) up to 2304770048 bytes (2198 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) N4120 CPU @ 1.10GHz
	Identifier: Intel64 Family 6 Model 122 Stepping 8
	Microarchitecture: Goldmont Plus
	Frequency (GHz): 1.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7477.35
	Virtual memory used (MB): 4322.02
	Swap memory total (MB): 5574.56
	Swap memory used (MB): 837.00
	JVM Flags: 2 total; -Xms2198M -Xmx2198M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Celeron(R) N4120 CPU @ 1.10GHz

### Steps To Reproduce

```markdown
1 Start Pojav-launcher.
2 Click on play.
3 Application/game is closed with code -1.
4 App closes.
```

### Expected Behavior

I expected just the menu to play on my cracked server.

### Platform

```markdown
- Chromebook: 
- x86_64: 
- Chromebook/Linux HP G8 EE: 
- crocus-v3_openjdk (downloaded in the playstore) Latest version i think:
```

### Anything else?

Just want to play minecraft...

**Comment by miggythewriter** [comment]
Try using GitHub builds

**Comment by offbeat-stuff** [comment]
latest builds are broken
This one worked for me
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2177504653

**Comment by miggythewriter** [comment]
Don't use the vertical uid build it's broken use this one it worked for me https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2237921247

**Comment by ghost** [comment]
Sorry i need to tell you this but what do i need to do with the build... and which file...

**Comment by GaucovyAero** [comment]
> Sorry i need to tell you this but what do i need to do with the build... and which file...

app-debug.zip

**Comment by ghost** [comment]
Thx, where i need to paste it?

**Comment by ghost** [comment]
I found out its an apk... but i can't run apks on this chromebook...

**Comment by GaucovyAero** [comment]
> I found out its an apk... but i can't run apks on this chromebook...

right, that's what multiple people said. well, you will have to do some hacking in order to get it working, ima tell you in a sec

**Comment by GaucovyAero** [comment]
So, what you have to do is just this.

1. Download assets-v0.zip (the shader fix) [here.](https://cdn.discordapp.com/attachments/971158675207102547/971158935220400158/assets-v0.zip)
2. Insert it into your resourcepacks folder
3. Go into options.txt and you will have to edit resourcePacks:[] to resourcePacks:["assets-v0.zip"] as **highlighted** in this screenshot:
![Screenshot from 2022-05-07 09-40-16](https://user-images.githubusercontent.com/85581164/167244264-1ac9f456-c376-4317-b9ec-bcedb8bc03a9.png)

**Comment by ghost** [comment]
wow okay

**Comment by ghost** [comment]
thank u i already knowed there where good people in the world...

**Comment by ghost** [comment]
i tried also termux but didnt work

**Comment by ghost** [comment]
I don't know how but its already in the folder and already changed in options.txt

**Comment by ghost** [comment]
[options.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8644683/options.txt)

**Comment by GaucovyAero** [comment]
> [options.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8644683/options.txt)

Alright, and is it still crashing to you?

**Comment by WesleyVanNeck** [comment]
> 

Latest holly gl4es doesn't need it

**Comment by WesleyVanNeck** [comment]
And it works fine on chrome os

**Comment by ghost** [comment]
> > [options.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8644683/options.txt)
> 
> Alright, and is it still crashing to you?

Yes :'(

**Comment by ghost** [comment]
> > 
> 
> Latest holly gl4es doesn't need it

Idk

**Comment by offbeat-stuff** [comment]
> Don't use the vertical uid build it's broken use this one it worked for me https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2237921247

@PrinceNormal 
That was not a vertical ui build

**Comment by ghost** [comment]
> > Don't use the vertical uid build it's broken use this one it worked for me https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2237921247
> 
> @PrinceNormal 
> That was not a vertical ui build

Can't install apk my chromebook is managed by my school

**Comment by ghost** [comment]
> > 
> 
> Latest holly gl4es doesn't need it

i Deleted now the file (assets-v0.zip) 
and now it gives this error:
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/7/22, 11:25 AM
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:197)
Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00
0:10(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.a(SourceFile:421)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00
0:10(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version Android-9
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1008054800 bytes (961 MiB) / 2275409920 bytes (2170 MiB) up to 2275409920 bytes (2170 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) N4120 CPU @ 1.10GHz
	Identifier: Intel64 Family 6 Model 122 Stepping 8
	Microarchitecture: Goldmont Plus
	Frequency (GHz): 1.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7477.32
	Virtual memory used (MB): 3968.02
	Swap memory total (MB): 5574.55
	Swap memory used (MB): 925.75
	JVM Flags: 2 total; -Xms2170M -Xmx2170M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Celeron(R) N4120 CPU @ 1.10GHz

**Comment by GaucovyAero** [comment]
> > > 
> > 
> > 
> > Latest holly gl4es doesn't need it
> 
> i Deleted now the file (assets-v0.zip) and now it gives this error: ---- Minecraft Crash Report ---- // I blame Dinnerbone.
> 
> Time: 5/7/22, 11:25 AM Description: Initializing game
> 
> java.lang.IllegalStateException: could not preload shader position at eql.a(SourceFile:425) at eql.a(SourceFile:409) at dyr.(SourceFile:619) at net.minecraft.client.main.Main.main(SourceFile:197) Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00 0:10(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00 at yw.a(SourceFile:48) at erd.(SourceFile:202) at eql.a(SourceFile:421) ... 3 more Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00 0:10(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00 at dtb.b(SourceFile:72) at dtb.a(SourceFile:54) at erd.a(SourceFile:244) at erd.(SourceFile:184) ... 4 more
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head -- Thread: Render thread Stacktrace: at eql.a(SourceFile:425) at eql.a(SourceFile:409) at dyr.(SourceFile:619)
> 
> -- Initialization -- Details: Modules: Stacktrace: at net.minecraft.client.main.Main.main(SourceFile:197)
> 
> -- System Details -- Details: Minecraft Version: 1.18.2 Minecraft Version ID: 1.18.2 Operating System: Linux (amd64) version Android-9 Java Version: 17-internal, N/A Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 1008054800 bytes (961 MiB) / 2275409920 bytes (2170 MiB) up to 2275409920 bytes (2170 MiB) CPUs: 4 Processor Vendor: GenuineIntel Processor Name: Intel(R) Celeron(R) N4120 CPU @ 1.10GHz Identifier: Intel64 Family 6 Model 122 Stepping 8 Microarchitecture: Goldmont Plus Frequency (GHz): 1.10 Number of physical packages: 1 Number of physical CPUs: 4 Number of logical CPUs: 4 Graphics card #0 name: unknown Graphics card #0 vendor: unknown Graphics card #0 VRAM (MB): 0.00 Graphics card #0 deviceId: unknown Graphics card #0 versionInfo: unknown Virtual memory max (MB): 7477.32 Virtual memory used (MB): 3968.02 Swap memory total (MB): 5574.55 Swap memory used (MB): 925.75 JVM Flags: 2 total; -Xms2170M -Xmx2170M Launched Version: 1.18.2 Backend library: LWJGL version 3.2.3 SNAPSHOT Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb Window size: GL Caps: Using framebuffer using OpenGL 3.2 GL debug messages: Using VBOs: Yes Is Modded: Probably not. Client jar signature and brand is untouched Type: Client (map_client.txt) CPU: 4x Intel(R) Celeron(R) N4120 CPU @ 1.10GHz

because you removed the file, you have to keep it in place for it to run, otherwise you are going to get the same **could not reload shaders** error.

**Comment by offbeat-stuff** [comment]
> Don't use the vertical uid build it's broken use this one it worked for me https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2237921247

this one has gl4es holy bugged it will not launch

**Comment by GaucovyAero** [comment]
> > Don't use the vertical uid build it's broken use this one it worked for me https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2237921247
> 
> this one has gl4es holy bugged it will not launch

no, he is on the play store version, aka crocus-v3_openjdk, so it is supposed to be fixable, but unfortunately his GPU is Intel UHD Graphics 600, and there might be a gpu-specific issue in place here. Devs are investingating, but I think it just comes to the PojavLauncher version being too outdated - the devs might not fix it.

**Comment by ghost** [comment]
> > > > 
> > > 
> > > 
> > > Latest holly gl4es doesn't need it
> > 
> > 
> > i Deleted now the file (assets-v0.zip) and now it gives this error: ---- Minecraft Crash Report ---- // I blame Dinnerbone.
> > Time: 5/7/22, 11:25 AM Description: Initializing game
> > java.lang.IllegalStateException: could not preload shader position at eql.a(SourceFile:425) at eql.a(SourceFile:409) at dyr.(SourceFile:619) at net.minecraft.client.main.Main.main(SourceFile:197) Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00 0:10(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00 at yw.a(SourceFile:48) at erd.(SourceFile:202) at eql.a(SourceFile:421) ... 3 more Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : 0:7(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00 0:10(7): error: A shader cannot redefine or overload built-in function `max' in GLSL ES 3.00 at dtb.b(SourceFile:72) at dtb.a(SourceFile:54) at erd.a(SourceFile:244) at erd.(SourceFile:184) ... 4 more
> > ## A detailed walkthrough of the error, its code path and all known details is as follows:
> > -- Head -- Thread: Render thread Stacktrace: at eql.a(SourceFile:425) at eql.a(SourceFile:409) at dyr.(SourceFile:619)
> > -- Initialization -- Details: Modules: Stacktrace: at net.minecraft.client.main.Main.main(SourceFile:197)
> > -- System Details -- Details: Minecraft Version: 1.18.2 Minecraft Version ID: 1.18.2 Operating System: Linux (amd64) version Android-9 Java Version: 17-internal, N/A Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 1008054800 bytes (961 MiB) / 2275409920 bytes (2170 MiB) up to 2275409920 bytes (2170 MiB) CPUs: 4 Processor Vendor: GenuineIntel Processor Name: Intel(R) Celeron(R) N4120 CPU @ 1.10GHz Identifier: Intel64 Family 6 Model 122 Stepping 8 Microarchitecture: Goldmont Plus Frequency (GHz): 1.10 Number of physical packages: 1 Number of physical CPUs: 4 Number of logical CPUs: 4 Graphics card #0 name: unknown Graphics card #0 vendor: unknown Graphics card #0 VRAM (MB): 0.00 Graphics card #0 deviceId: unknown Graphics card #0 versionInfo: unknown Virtual memory max (MB): 7477.32 Virtual memory used (MB): 3968.02 Swap memory total (MB): 5574.55 Swap memory used (MB): 925.75 JVM Flags: 2 total; -Xms2170M -Xmx2170M Launched Version: 1.18.2 Backend library: LWJGL version 3.2.3 SNAPSHOT Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb Window size: GL Caps: Using framebuffer using OpenGL 3.2 GL debug messages: Using VBOs: Yes Is Modded: Probably not. Client jar signature and brand is untouched Type: Client (map_client.txt) CPU: 4x Intel(R) Celeron(R) N4120 CPU @ 1.10GHz
> 
> because you removed the file, you have to keep it in place for it to run, otherwise you are going to get the same **could not reload shaders** error.

Okay
