### ISSUE TITLE
[BUG] Unexpected shift lock

### ISSUE THREAD

**Issue by swarties** [PojavLauncherTeam/PojavLauncher#3203]
### Describe the bug

While playing on bedwars with my mouse and keyboard, sometimes it locks the shifts with removes my items from my quick shop and basically does what a shift click does

### The log file and images/videos

There isn't really to add

### Steps To Reproduce

```markdown
Read the first thing
```

### Expected Behavior

Not shift clicking

### Platform

```markdown
- Device model: Samsung Galaxy tab a7
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest build from now
```

**Comment by offbeat-stuff** [comment]
make a video bro

**Comment by swarties** [comment]
Can't play block game anymore, exams :/

**Comment by Comy112** [comment]
> Can't play block game anymore, exams :/

Hi! Please don't send here troll messages like this one.

**Comment by swarties** [comment]
> 
This issue happened before i couldn't play block game, I'm not trolling

**Comment by Comy112** [comment]
I said for 
![Screenshot_20220507-185736_Chrome](https://user-images.githubusercontent.com/102830774/167264283-91a6bc4d-2cbe-4cf9-b4cb-92a984cda394.jpg)

**Comment by GaucovyAero** [comment]
Anyway, the fix would be updating to the latest [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) build.

**Comment by swarties** [comment]
> Anyway, the fix would be updating to the latest [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) build.

Wdym?
