### ISSUE TITLE
Cannot access PojavLauncher folder because android data folder is locked or something

### ISSUE THREAD

**Issue by blacklambCZ** [PojavLauncherTeam/PojavLauncher#3204]
### Describe the bug

Basically, i was using pojav launcher, could install mods, but when they made the change folder location to Android/data/net.kdz.pojavlaunch/
I cant install mods, or transfer data from older folder, i tried other device which doesnt have two storage data and it worked fine.
When i try accessing the folder, it shows that net.kdz.pojavlaunch has 0b (bytes) and i cant open it.

### The log file and images/videos

![IMG_20220507_112747](https://user-images.githubusercontent.com/76792760/167248286-8913c339-9186-496c-a5ba-00c8c0e58f71.jpg)
Otevření souboru selhalo -> failed to open file

### Steps To Reproduce

```markdown
Start pojav launcher, sign in and install forge any version. Then go to the android/data/ folder and find net.kdz.pojavlaunch
```

### Expected Behavior

I expected to open it just normal and put my mods into .minecraft/mods or copy old folder location

### Platform

```markdown
- Device model: Galaxy a20e
- CPU architecture:
- Android version: 11
- PojavLauncher version: v3 (latest)
```

### Anything else?

There might be possible fix to this issue: let people change default folder location. So if its inacessible, we can just change it and issue will be solved

EDIT: Fixed it. If you have same problems like me, use ZARchiver and allow permissions to access data folder

**Comment by GaucovyAero** [comment]
Jaj, jednoduchy fix. Stiahni si zArchiver a pouzivaj ten namiesto normalneho prehliadaca suborov. Este taka vecicka, v3_openjdk je takmer rok stara verzia (nie je ani zdaleka najnovsia), cize odporucam preinstalovat na najnovsiu v [GitHub Actions.](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

**Comment by blacklambCZ** [comment]
> Jaj, jednoduchy fix. Stiahni si zArchiver a pouzivaj ten namiesto normalneho prehliadaca suborov. Este taka vecicka, v3_openjdk je takmer rok stara verzia (nie je ani zdaleka najnovsia), cize odporucam preinstalovat na najnovsiu v [GitHub Actions.](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

Zkusil jsem a to funguje, divné protože to předtim to nefungovalo s Zarchiverem, protože mi nenaskočilo použít tuto složku, teď už jde.

**Comment by blacklambCZ** [comment]
Issue fixed
