### ISSUE TITLE
[BUG?] install forge or optifine crash the game to login screen but fabric not

### ISSUE THREAD

**Issue by rilimin** [PojavLauncherTeam/PojavLauncher#3207]
### Describe the bug

install forge crash the game to login screen

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8646218/latestlog.txt)

https://user-images.githubusercontent.com/97272600/167279017-937a29a3-35ec-47b1-bed2-218cd8016ac4.mp4

and the java runtime is internal java 8

### Steps To Reproduce

```markdown
1. Open pojav and login
2. press options
3. press launch a mod installer
4. select forge installer or optifine
5. it show the log output for 1 sec and then crash to the login screen
```

### Expected Behavior

I expect it will install normally because before I was install it no problem and now this happen

### Platform

```markdown
- Device model: Vsmart Joy 4
- CPU architecture: AArch64
- Android version: 11
- PojavLauncher version: google play version
```

**Comment by khanhduytran0** [comment]
The log that you sent was when you ran the Fabric installer.
Also, the launcher build that you installed is outdated. Try from [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions).
