### ISSUE TITLE
[BUG] login error

### ISSUE THREAD

**Issue by Ripme999** [PojavLauncherTeam/PojavLauncher#3209]
### Describe the bug

I have purchased minecraft java edition and I can play it on pc but if I go on my phone and try to login I get the same error other people do that don’t own the game,   Might it just be my device or what? I own both versions on the same account too so it should work right or am I wrong?

### The log file and images/videos

No image/video

### Steps To Reproduce

```markdown
Open application go to login through both options and get an error of not owning the game
```

### Expected Behavior

I expect to login and begin playing as others clearly show

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 3.3.1
```

### Anything else?

I don’t currently have the phone i use so I don’t know the specs but it’s a A70 idk if that helps

**Comment by GaucovyAero** [comment]
Well, basically, your issue is that you are on an archaic version of PojavLauncher. Just update to the latest one with a green checkmark on it in [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions). Just download app-debug.zip, then extract it and install app-debug.apk.

**Comment by Ripme999** [comment]
Okay,  I’ll try to do that when I have access to the phone again,  thank you for possibly solving my problem:)

**Comment by offbeat-stuff** [comment]
Use this build
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2177504653
The latest build does not launch due to gl4es been bugged

Please do NOT use old builds. Current builds already work well for most, if they don't work for you, report the problem in a separate issue.

**Comment by Ripme999** [comment]
I’m not 100% sure how to get that version of the build, could you possibly point me in the right direction

**Comment by Ripme999** [comment]
I fixed this issue but im facing another

**Comment by steven1steven** [comment]
![Uploading polandball-countryballs.gif…]()

**Comment by steven1steven** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/148647725/4c3ddebf-b808-4653-bc53-4224f7c527da

**Comment by steven1steven** [comment]
![images (1)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/148647725/bbf76f87-8843-429e-b765-b5a34da44294)

**Comment by steven1steven** [comment]
[Uploading Getting-Started-Guide-Scratch2.pdf…]()

**Comment by steven1steven** [comment]
[Readme.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15444701/Readme.txt)

**Comment by steven1steven** [comment]
#5488

**Comment by steven1steven** [comment]
Pojavlauncher + error 
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15444704/latestcrash.txt)

**Comment by steven1steven** [comment]
Uploading yahiamice orange(720P_HD).mp4…

**Comment by steven1steven** [comment]
Lol.mp4

**Comment by steven1steven** [comment]
LOL.mp4

**Comment by steven1steven** [comment]
YouTube yahicles 

Uploading yahiamice orange(720P_HD).mp4…

**Comment by steven1steven** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/148647725/df11e15b-54c2-4f5b-af0a-d570a0a71b09

**Comment by steven1steven** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/148647725/6e98fbff-a385-4ebd-871d-2fcedd7a9efa

**Comment by steven1steven** [comment]
@steven1steven

**Comment by steven1steven** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/148647725/7b5fd4fe-6657-4324-9501-6cdfe0400199

**Comment by steven1steven** [comment]
![countryballs-europe](https://github.com/PojavLauncherTeam/PojavLauncher/assets/148647725/5dc47f7d-4a6c-4714-a398-da94ee71a96e)

**Comment by steven1steven** [comment]
![polandball-countryballs](https://github.com/PojavLauncherTeam/PojavLauncher/assets/148647725/5981e6b8-1c14-41db-a7a0-d018b4b8529a)

**Comment by kiokori-git** [comment]
@steven1steven stop

**Comment by offbeat-stuff** [comment]
Wait KioKingz were you in this issue's chat (Is that what they say it to be). It's quite random that you joined? But anyways It was fun looking at some random person doing nonsense stuff in a github issue. Well Played Steven.

**Comment by kiokori-git** [comment]
> Wait KioKingz were you in this issue's chat (Is that what they say it to be). It's quite random that you joined? But anyways It was fun looking at some random person doing nonsense stuff in a github issue. Well Played Steven.

no, i just got here by seeing #github from the discord server.
