### ISSUE TITLE
[BUG] Input error

### ISSUE THREAD

**Issue by Hloredea** [PojavLauncherTeam/PojavLauncher#3211]
### Describe the bug

Can't enter @,#,*,",'

### Steps To Reproduce

```markdown
Enter in chat: @,#,*,",'
```

### Expected Behavior

I expected to type @,#,*,",'

### Platform

```markdown
- Device model: Redmi 7
- CPU architecture: ?
- Android version: 9-10
- PojavLauncher version: 3.3.1.1
```

**Comment by GaucovyAero** [comment]
Of course, because your Pojav version is more than 1 year old. Update to the latest one in the Actions tab on this GitHub page. Click on the uppermost one with a green checkmark on it and download app-debug.zip. Then install app-debug.apk

**Comment by Hloredea** [comment]
No, my version is the latest.

**Comment by WesleyVanNeck** [comment]
> No, my version is the latest.

ìt isnt

**Comment by Mathias-Boulay** [comment]
3.3.1.1 is not supported as it is too old
