### ISSUE TITLE
[BUG] Can't use Minecraft Forge Version 1.12.2 (game exited)

### ISSUE THREAD

**Issue by Trey336** [PojavLauncherTeam/PojavLauncher#3212]
### Describe the bug

Hello. I for some reason can't play forge 1.12.2 for one second without it exiting on me. I don't know if it's a bug or..........I'll just say it's a bug. The regular 1.12.2 works...but, anyway here are some screenshots (using action build by the way)
![Screenshot_20220509-122237_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/84420311/167454150-4e37926d-1e82-4e59-953b-da1cc102fca6.jpg)
Also local account

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8653533/latestlog.txt)

### Steps To Reproduce

```markdown
Pressing the play button again.
```

### Expected Behavior

I expect it to launch.

### Platform

```markdown
- Device model: Samsung S20
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: one of the action build
```

### Anything else?

No just trying to see if it is a bug

**Comment by Trey336** [comment]
Well......one screenshot 😑

**Comment by Ripme999** [comment]
what Build of forge are you using?

**Comment by Trey336** [comment]
Build 2858

**Comment by NotAHero04** [comment]
Local account + Forge is like water + oil. Buy the game.

**Comment by Trey336** [comment]
It's pointless if you don't buy the game. NotAHero is a Hero!!!
