### ISSUE TITLE
[BUG?] ClassNotFoundException

### ISSUE THREAD

**Issue by SytherPlayZ** [PojavLauncherTeam/PojavLauncher#3213]
### Describe the bug

hii, i am facing a problem when starting 1.17.1 or above, it says game exited.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8656535/latestlog.txt)
Here is the log of the error. It says Game Exited...

### Steps To Reproduce

```markdown
1. I tried different Java Runtimes.
2. I tried every renderer.
3. I removed all the texture packs.
4. I also removed assets-v0.zip.
```

### Expected Behavior

I expected that the game will work this time in every try but it didn't. Pls help

### Platform

```markdown
- Device model: Redmi Note 4 4/64G
- CPU architecture: aarch64
- Android version: Android 7
- PojavLauncher version: Playstore Version.
```

### Anything else?

No

**Comment by miggythewriter** [comment]
Use GitHub builds the builds are more updated

**Comment by SytherPlayZ** [comment]
Can you give me link?

**Comment by artdeell** [comment]
Use Actions.
