### ISSUE TITLE
[BUG] Touch failure

### ISSUE THREAD

**Issue by Tungstend** [PojavLauncherTeam/PojavLauncher#3218]
### Describe the bug

Touch not working after installing Fabric 0.14.0 or later , forge/optifine/vanilla/fabric0.13.3 or previous did not have this problem.

### The log file and images/videos

![KGP 9DO J0E8DP9M%6C8Q(1](https://user-images.githubusercontent.com/74163103/167989454-1f77aa03-ef88-427e-a5a9-ce037699652d.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8674901/latestlog.txt)

### Steps To Reproduce

```markdown
Start game with Fabric 0.14.0 installed
```

### Expected Behavior

I expected to click play button.

### Platform

```markdown
- Device model: OPPO Find X3 Pro 12+256
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: version built with the latest source code
```

### Anything else?

I add a argument printing function,other codes have not changed,it shouldn't have any impact.
![image](https://user-images.githubusercontent.com/74163103/167989734-6d8580a7-8241-4e2b-b9e1-796d2f2be29f.png)

**Comment by artdeell** [comment]
Have you tried it on the forge_1.17_wip branch?

**Comment by Tungstend** [comment]
Problem solved, why not make it the master branch?

**Comment by Tungstend** [comment]
![Screenshot_2022-05-12-14-17-08-58_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/74163103/168004610-81568074-f33e-4ed4-8ac7-e60e6bdd9632.jpg)
1.17+forge still crashes on this branch,I'm sure sucurejarhandler.jar is in the right place

**Comment by Tungstend** [comment]
Version below 1.13 crashes on this branch

**Comment by artdeell** [comment]
@Tungstend Have you tried to reinstall it? I just ran Forge 1.18.2 just fine like 5 minutes ago on it, so it should work.

**Comment by Tungstend** [comment]
It didn't work,well i will try it again,did you install it by forge installer or other installer?

**Comment by artdeell** [comment]
I installed forge using the official Forge installer and the jar installer in the launcher

**Comment by Tungstend** [comment]
![Screenshot_2022-05-12-22-16-27-84_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/74163103/168096236-e20e8397-7680-4166-8260-da4af49be547.jpg)
I use official forge installer this time and new error produced.

**Comment by artdeell** [comment]
Do you have any custom JVM args by chance?

**Comment by Tungstend** [comment]
no the 1.18.2 is vallina version and i use foege installer to install forge,maybe i should clear the .minecraft directory and reinstall it

**Comment by khanhduytran0** [comment]
Did you realize that Java 8 was picked instead of 17? :eyes:

**Comment by Tungstend** [comment]
i am sure i have use java17 instead of 8

**Comment by artdeell** [comment]
Logs say otherwise. "Internal" runtime (which is loaded by your log), is Java 8.

**Comment by Tungstend** [comment]
ohhhh,sry,i forgot to change it,

**Comment by Tungstend** [comment]
1.18.2 vallina is java17,forge installer create a new game profile so it hasn t been set to java17

**Comment by Tungstend** [comment]
![Uploading Screenshot_2022-05-12-22-43-37-32_9e8df3d0c7c1f50248b6ee043a653d26.jpg…]()
Well......

**Comment by artdeell** [comment]
your image hasn't uploaded yet

**Comment by Tungstend** [comment]
sry the internet went wrong

**Comment by Tungstend** [comment]
This time I am sure i have use java17
![Screenshot_2022-05-12-22-45-12-79_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/74163103/168102942-18286ffe-e03d-44c8-a990-cd073c70ba92.jpg)

**Comment by khanhduytran0** [comment]
> sry the internet went wrong

This is when copying plain text better than screenshot of plain text.

Try deleting the lwjgl3 folder.

**Comment by Tungstend** [comment]
I print all arguments this time,i will delete lwjgl and try again

**Comment by Tungstend** [comment]
[latestlog(1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8680179/latestlog.1.txt)

**Comment by Tungstend** [comment]
I tried to delete lw3 folder and regenerate lw3 files,still the same report

**Comment by Tungstend** [comment]
![Screenshot_2022-05-12-22-59-02-62_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/74163103/168105963-71d08a51-5377-46ca-a8be-1f63820ba2ee.jpg)
My lw3 folder

**Comment by Tungstend** [comment]
I delete .minecraft/lw3 again and reinstall forge,problem solved,thanks anyway,I waste your time
