### ISSUE TITLE
[BUG] classpath error

### ISSUE THREAD

**Issue by Tungstend** [PojavLauncherTeam/PojavLauncher#3219]
### Describe the bug

When i run forge and optifine together on Minecraft 1.12.2 or previous version ,game crashed.(optifine is not installed as a mod)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8681381/latestlog.txt)

### Steps To Reproduce

```markdown
Launch 1.12.2 or previous version with forge and optifine installed.
```

### Expected Behavior

Should be able to launch.

### Platform

```markdown
- Device model: OPPO Find X3 Pro
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest github action
```

### Anything else?

Maybe u should switch isClientFirst to true if minimumLauncherVersion is lower than 21,but when minimumLauncherVersion is 21 or higher, isClientFirst should be false, because optifine doesn't work when version.jar is placed at the start of the classpath.
![Screenshot_2022-05-13-01-23-30-56_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/74163103/168135680-dce69bc6-eba0-44a5-8b73-f90219cc946f.jpg)

**Comment by Tungstend** [comment]
This is my version.json,it crashed on pojavlauncher,but when i switch isClientFirst to true,it launched successfully.
[1.7.10.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8681436/1.7.10.zip)

**Comment by GaucovyAero** [comment]
Very weird issues i should say.

**Comment by Tungstend** [comment]
It's really strange, but I did encounter this problem. Generally speaking, if forge is installed, optifine exists in the form of mod, but the installation function that comes with some launchers allows optifine and forge to exist in the form of api at the same time  , so this problem occurred, and I was surprised at first, but it is the fact that the position of version.jar in the classpath has an impact

**Comment by artdeell** [comment]
You can probably also do it as a regular person and put the OF jar into the mods folder...

**Comment by Tungstend** [comment]
Maybe I should close this issue after all there shouldn't be anyone as boring as me,lol
