### ISSUE TITLE
[F-Req] <Open game links in browser>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3222]
### Is this request related to a bug?

Every time a link appears in the game, even copying the link does not go to the clipboard. 

### Describe the request.

Every time a link appears in the game, even copying the link does not go to the clipboard. It would be great if it went to the clipboard or opened in the mobile browser. 

### Anything else?

Nope.

**Comment by Mathias-Boulay** [comment]
#1021
