### ISSUE TITLE
[BUG] LabyMod 1.16.5

### ISSUE THREAD

**Issue by KentangGG121** [PojavLauncherTeam/PojavLauncher#3224]
### Describe the bug

LabyMod 1.16.5 crash

### The log file and images/videos

https://www.mediafire.com/download/zwkygsa9x8abr5b

### Steps To Reproduce

```markdown
1. Launch Pojav launcher from github action
2. Install LabyMod for 1.16.5
3. Download the required files (Online Account)
4. Launch and crash with code 0/1
```

### Expected Behavior

The game not able launch

### Platform

```markdown
- Device model: Vivo y50
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version: latest github build
```

### Anything else?

No, just like that

**Comment by GaucovyAero** [comment]
You are likely missing the LabyMod JAR file and/or LabyMod libraries because you are missing LabyModTweaker. Pretty sure something has gone wrong in the installation process.

**Comment by KentangGG121** [comment]
> You are likely missing the LabyMod JAR file and/or LabyMod libraries because you are missing LabyModTweaker. Pretty sure something has gone wrong in the installation process.

Wait let me check and install again
