### ISSUE TITLE
[F-Req] TechnicLauncher.jar

### ISSUE THREAD

**Issue by t0g3pii** [PojavLauncherTeam/PojavLauncher#3225]
### Describe the request.

Im currently trying to get TechnicLauncher.jar running in the latest PojavLauncher Version

The First Start works without issues, i can select a Installation Path if want and so on.
(If i use the Standard One it installs itself in /Android/data/net.kdt.pojavlaunch/files/.technic)
(Debug would be: /Android/data/net.kdt.pojavlaunch.debug/files/.technic

After the Installation the .jar Closes itself. After Reopening i get a black screen and get thrown back into the PojavLauncher after a few seconds (Probably because the .jar starts a loader, closes that and starts the real Window then normaly)

Is there some Argument to NOT get thrown back into PojavLaunch? Maybe it starts then? Do i need to do anything more maybe?
Would appreciate some help of you because i would love to play some older Modpacks like Tekkit Lite in PojavLauncher! 
(I cant get the Modpack running when setting it up on my own with the /versions and /mods folder yk?)

**Comment by artdeell** [comment]
Running other launchers within PojavLauncher is not supported, and will likely never be. There are no magic arguments to fix that.

**Comment by t0g3pii** [comment]
Im currently trying to debug it on my own as i want to play Tekkit Lite so badly on Pojav :P

Seems like Technic is trying to reach a folder outside of the given Permissions.. 

> [B#744] 2022/05/13 07:28:25 [INFO] Launching command: '/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/bin/java -Xmx256m -verbose -Djava.net.preferIPv4Stack=true -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -cp /data/data/net.kdt.pojavlaunch.debug/cache/TechnicLauncher.jar net.technicpack.launcher.LauncherMain '
> [B#744] 2022/05/13 07:28:25 [SEVERE] java.security.AccessControlException: access denied ("java.io.FilePermission" "/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/bin/java" "execute")
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at java.security.AccessController.checkPermission(AccessController.java:886)
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at java.lang.SecurityManager.checkExec(SecurityManager.java:796)
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1018)
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at net.technicpack.autoupdate.Relauncher.launch(Relauncher.java:167)
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at net.technicpack.autoupdate.Relauncher.relaunch(Relauncher.java:110)
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at net.technicpack.autoupdate.Relauncher.runAutoUpdater(Relauncher.java:92)
> [B#744] 2022/05/13 07:28:25 [SEVERE] 	at net.technicpack.launcher.LauncherMain.main(LauncherMain.java:211)

So this here isn't Pojav relevant anymore^^ Posting Updates here asap i get an result^^

**Comment by artdeell** [comment]
It's trying to launch the Java VM, which is possible in Pojav, but only without graphics and in a different folder. That's why i said launching other launchers inside Pojav is not supported. Closing.
