### ISSUE TITLE
[BUG] Origins Mod 1.16.5 Crashes Upon World Creation/Startup

### ISSUE THREAD

**Issue by PugBroKid** [PojavLauncherTeam/PojavLauncher#3226]
### Describe the bug

Launching into a world crashes with origins mod (Other mods have been tested without and it doesnt crash)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8686747/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8686751/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Install Fabric
3. Put Origins mod 1.16.5 In Mods folder
4. Launch Minecraft Fabric 1.16.5
5. Create or load a new world

Enjoy your crash =(
```

### Expected Behavior

I expected the game to launch into the world with the origins mod menu

### Platform

```markdown
- Device model: Chromebook
- CPU architecture: x86_64
- Android version: Latest for chromebook
- PojavLauncher version: Latest from play store
```

### Anything else?

https://user-images.githubusercontent.com/95888812/168276627-238cdd9e-de19-452f-9052-2abd05f6d76c.mp4

**Comment by artdeell** [comment]
Use a legitimate Minecraft account to fix this issue.
