### ISSUE TITLE
阴影黑线

### ISSUE THREAD

**Issue by RzdPai** [PojavLauncherTeam/PojavLauncher#3229]
### Describe the bug

gl4es打开光影后，阴影中会出现黑线和其他的一些渲染bug
这在以前的版本中从未有过

### The log file and images/videos

![Screenshot_20220515_183527](https://user-images.githubusercontent.com/79180302/168469337-015d36a0-8d64-406b-b865-61690d3ac953.jpg)

### Steps To Reproduce

```markdown
1启动pojavlauncher
2启动游戏(渲染器gl4es)
3进入存档
4打开光影
5光影出现黑色线条
```

### Expected Behavior

它应该正常工作

### Platform

```markdown
- Device model: vivo y93s
- CPU architecture: aarch64
- Android version: 8.1.0
- PojavLauncher version: 最新测试版
```

**Comment by TWTommyee** [comment]
Open4ES?

**Comment by artdeell** [comment]
Please get a better graphics chip
