### ISSUE TITLE
Error during startup 1.16.2

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#323]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/21/20, 10:57 AM
Description: Initializing game

java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:0
	at ded.b(SourceFile:180)
	at ded.b(SourceFile:149)
	at ded.d(SourceFile:65)
	at ded.a(SourceFile:54)
	at ded.<init>(SourceFile:45)
	at djw.<init>(SourceFile:466)
	at net.minecraft.client.main.Main.main(SourceFile:177)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ded.b(SourceFile:180)
	at ded.b(SourceFile:149)
	at ded.d(SourceFile:65)
	at ded.a(SourceFile:54)
	at ded.<init>(SourceFile:45)
	at djw.<init>(SourceFile:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Linux (aarch64) version 4.9.117+
	Java Version: 9-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 745813288 bytes (711 MB) / 973078528 bytes (928 MB) up to 973078528 bytes (928 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xms600m -Xmx900m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.2
	Backend library: LWJGL versio

**Comment by Malaska678** [comment]
Known issue

**Comment by khanhduytran0** [comment]
(aarch64 java runtime affected only)

**Comment by khanhduytran0** [comment]
Fixed already. Use v3.2 release.
