### ISSUE TITLE
[F-Req] <A Test : Un test>

### ISSUE THREAD

**Issue by BonjorBoi** [PojavLauncherTeam/PojavLauncher#3230]
### Is this request related to a bug?

English 🇺🇲 
Hello to who is reading this I would love to try this experiment out I'm will get straight to the point I want to have the most powerful Apk of Pojav launcher, JVM, and settings for 1.12.2 forge with over 80 mods I don't think it should be a challenge as I myself had used 5 apks to try this experiment one was new and older and the pattern repeats and I tried the google play app and I can tell that the google play one does not work the best it seems to crash more often then they work in progress apps now to the work in progress it has very more features then the Google play app and thou some of them made changes others did not which is 5 out of 6 of them did not make changes but they made the game some what play able 20 fps while the other apk made changes like 40+ fps this may all sound good right WRONG the fps drops to 0 alot so this is why i'm doing this experment to see what apk , JVM , and settings are enough to handle my mods and these mods are not that big for example i decide to make a map called Eporue europe spelled backwards post to repersent the 20th century of europe and i used mods like Decocraft , chisel , little tiles , Immersive railroading and more i tried this on my Snapdragon and it works perfectly but i decide to try it on my cousins tablet as he did stop using the app due to buying a new comupter apolisges if this sounds long but i just want to give a detail responds so are you up for the challange or request?

French🇫🇷 
Bonjour à tous ceux qui lisent ceci, j'aimerais bien essayer cette expérience, je vais aller droit au but, je veux avoir l'Apk le plus puissant de Pojav launcher, JVM, et les paramètres pour 1.12. 2 forge avec plus de 80 mods Je ne pense pas que ce devrait être un défi comme je l'avais moi-même utilisé 5 apks pour essayer cette expérience l'un était nouveau et plus anciens et le modèle se répète et j'ai essayé l'application google play et je peux dire que le google play un ne fonctionne pas le meilleur, il semble à planter plus souvent alors qu'ils travaillent dans les applications en cours maintenant à l'œuvre en cours, il a très plus de fonctionnalités que l'application Google play et thou certains d'entre eux ont fait des changements d'autres n'ont pas ce qui est 5 sur 6 d'entre eux n'ont pas fait des changements, mais ils ont fait le jeu quelque chose play able 20 fps tandis que l'autre apk a fait des changements comme 40 + fps ce mai tout bon droit FAUX le fps baisse à 0 alot donc c'est pourquoi je fais cette expérience pour voir ce que apk , JVM , et les paramètres sont suffisants pour gérer mes mods et ces mods ne sont pas si gros par exemple j'ai décidé de faire une carte appelée Eporue europe orthographiée à l'envers post pour représenter le 20ème siècle de l'Europe et j'ai utilisé des mods comme Decocraft , chisel , little tiles , J'ai essayé cela sur mon Snapdragon et cela fonctionne parfaitement mais j'ai décidé de l'essayer sur la tablette de mon cousin car il a arrêté d'utiliser l'application en raison de l'achat d'un nouvel ordinateur. Excusez-moi si cela vous semble long mais je veux juste donner une réponse détaillée.

### Describe the request.

Read above 

### Anything else?

 NO

**Comment by GaucovyAero** [comment]
Uhm, just use the latest PojavLauncher Actions build, that should do the trick. If you are using OptiFine, make sure to copy [these](https://youtu.be/FsdbI34uueQ) settings (even though they aren't 1.12.2). Make sure to also turn on Smart Animations in Performance settings.

**Comment by BonjorBoi** [comment]
Alright Thank you definitely try that have a great day and may God bless you

**Comment by GaucovyAero** [comment]
> Alright Thank you definitely try that have a great day and may God bless you

Also, kinda forgot to tell you. The latest build's Java 8 Runtime is temporarily broken, so you might wanna wait until tomorrow. The PojavLauncher team is currently doing its best to create a fully stable build after almost a year and also updating PojavLauncher on Google Play to that build.

**Comment by BonjorBoi** [comment]
Ohhh alright thanks for updating me i was just about to do it

**Comment by Mathias-Boulay** [comment]
Should be fixed on this build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2327940182
