### ISSUE TITLE
[BUG] Crash in version 1.8.9 when starting the game

### ISSUE THREAD

**Issue by VlipperGZ** [PojavLauncherTeam/PojavLauncher#3232]
### Describe the bug

I crash while using version 1.8.9

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8696291/latestlog.txt)

### Steps To Reproduce

```markdown
1. Login to pojavlauncher
2. Choose version to 1.8.9
3. Start (One second after starting it immediately crashes)
```

### Expected Behavior

I hope this is fixed soon because I want to play on that version

### Platform

```markdown
- Device model: VIVO Y12i 3/32G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-571-f966a153f-v3_openjdk
```

**Comment by ssaagamemer** [comment]
It Happened In Any Version Now man

**Comment by ghost** [comment]
Renderer: ?
Ram allocated: ?
Are you using any client ?

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build

**Comment by VlipperGZ** [comment]
> Renderer: ? Ram allocated: ? Are you using any client ?

all kinds of renderers
Alocated 1000
Using forge
