### ISSUE TITLE
[BUG] Crash the game immediately at launch

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#3233]
### Describe the bug

After the last update, I launch Minecraft, as a result: immediately after the launch, error -1. FIX IT

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-571-f966a153f-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.17.1
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: POJAV_NATIVEDIR=/data/app/~~fyQ6m8TG7QBqmOSqKkaeUg==/net.kdt.pojavlaunch.debug-v3eL2pvNbNdhqnm-NLChxw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220506-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220506-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220506-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~fyQ6m8TG7QBqmOSqKkaeUg==/net.kdt.pojavlaunch.debug-v3eL2pvNbNdhqnm-NLChxw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220506-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException: 
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x79a9a3280c)
process killed with signal 6 code 0xffffffff addr 0x2a0400001ea4
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x76ec5ea828)
process killed with signal 6 code 0xffffffff addr 0x2a0400001ea4
--------- beginning of main

I/LIBGL   ( 7844): Initialising gl4es
I/LIBGL   ( 7844): v1.1.4 built on May 15 2022 17:25:03
I/LIBGL   ( 7844): Using GLES 2.0 backend
I/LIBGL   ( 7844): loaded: libGLESv2.so
I/LIBGL   ( 7844): loaded: libEGL.so
I/LIBGL   ( 7844): Using GLES 2.0 backend
I/LIBGL   ( 7844): Hardware Full NPOT detected and used
I/LIBGL   ( 7844): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   ( 7844): FBO are in core, and so used
I/LIBGL   ( 7844): PointSprite are in core, and so used
I/LIBGL   ( 7844): CubeMap are in core, and so used
I/LIBGL   ( 7844): BlendColor is in core, and so used
I/LIBGL   ( 7844): Blend Substract is in core, and so used
I/LIBGL   ( 7844): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 7844): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 7844): Extension GL_OES_mapbuffer  detected
I/LIBGL   ( 7844): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 7844): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 7844): Ex
tension GL_OES_depth24  detected and used
I/LIBGL   ( 7844): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 7844): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 7844): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 7844): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   ( 7844): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   ( 7844): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 7844): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 7844): high precision float in fragment shader available and used
I/LIBGL   ( 7844): Max vertex attrib: 16
I/LIBGL   ( 7844): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 7844): Max texture size: 16383
I/LIBGL   ( 7844): Max Varying Vector: 31
I/LIBGL   ( 7844): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   ( 7844): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 7844): Max Anisotr
opic filtering: 16
I/LIBGL   ( 7844): Hardware vendor is ARM
I/LIBGL   ( 7844): GLSL 300 es supported
I/LIBGL   ( 7844): GLSL 310 es supported and used
I/LIBGL   ( 7844): GLSL 320 es supported
I/LIBGL   ( 7844): Max Color Attachments: 4 / Draw buffers: 4
I/LIBGL   ( 7844): sRGB surface supported
I/LIBGL   ( 7844): EGLImage to Texture2D supported
I/LIBGL   ( 7844): EGLImage to RenderBuffer supported
I/LIBGL   ( 7844): ignore MipMap
I/LIBGL   ( 7844): Targeting OpenGL 2.1
I/LIBGL   ( 7844): No hack in shader converter to define overloaded function with int
I/LIBGL   ( 7844): NPOT texture handled in hardware
I/LIBGL   ( 7844): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 7844): try to use VBO
I/LIBGL   ( 7844): glXMakeCurrent FBO workaround enabled
I/LIBGL   ( 7844): FBO workaround for using binded texture enabled
I/LIBGL   ( 7844): glX Will try to recycle EGL Surface
I/LIBGL   ( 7844): Current folder is:/
I/jrelog  ( 7844): dlopen libgl4es_114.so success
I/jrelog  ( 7844): dlopen /data/user/0/net
.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220506-release.tar.xz/lib/libjli.so success
I/jrelog  ( 7844): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 7844): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220506-release.tar.xz/lib/server/libjvm.so success

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login in your Microsoft account with bought minecraft
3. Launch game
```

### Expected Behavior

I expect the game to start

### Platform

```markdown
- Device model: Redmi 10 4/128
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest version from GitHub actions
```

**Comment by Mathias-Boulay** [comment]
Unproper java unpacking it seems

**Comment by andr0d1v** [comment]
@Mathias-Boulay did I do something wrong, or is it a version problem?

**Comment by GaucovyAero** [comment]
> Unproper java unpacking it seems

No idea, but it also happens on the latest Update JREUtils build. I have also tried manually installing the Java Runtime, also doesn't work :P

**Comment by andr0d1v** [comment]
Yeeee, fixed. Thanks

**Comment by Wolfixx7** [comment]
> Yeeee, fixed. Thanks

comment ta fais
