### ISSUE TITLE
[BUG] <Game Exited or Architecture x86 is not compatible with aarch 64 >

### ISSUE THREAD

**Issue by DevinC76** [PojavLauncherTeam/PojavLauncher#3237]
### Describe the bug

Doesnt work 

### The log file and images/videos

Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=1366x768, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/OptiFine_1.8.8_HD_U_I7.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1366
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-RsYXb1Snm5u9qwQFfULA6A==/lib/x86
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=768
--------- beginning of main
I/jrelog  ( 6517): dlopen /data/app/net.kdt.pojavlaunch-RsYXb1Snm5u9qwQFfULA6A==/lib/x86/libopenal.so success
I/jrelog  ( 6517): Done processing args
Java Exit code: -1
Install successful
I/jrelog  ( 6517): JLI lib = NULL: dlopen failed: library "libjli.so" not found
I/jrelog  ( 6517): Going to free args
I/jrelog  ( 6517): Free done
--------- beginning of system

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
Google Chrome	91.0.4472.167 (Official Build) (64-bit)
Revision	b2fe69bacb762e4fc9e6c25c7cfe6dc7ac00569a-refs/branch-heads/4472@{#1574}
Platform	13904.97.0 (Official Build) stable-channel auron_paine
Firmware Version	Google_Auron_paine.6301.58.98
ARC	7534053
JavaScript	V8 9.1.269.39
User Agent	Mozilla/5.0 (X11; CrOS x86_64 13904.97.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.167 Safari/537.36
Command Line	/opt/google/chrome/chrome --use-gl=egl --enable-native-gpu-memory-buffers --gpu-sandbox-failures-fatal=yes --video-capture-use-gpu-memory-buffer --enable-logging --log-level=1 --use-cras --enable-wayland-server --user-data-dir=/home/chronos --enable-features=SmartDim,UmaStorageDimensions,Crostini,CrostiniGpuSupport,CrostiniEnableDlc --login-profile=user --has-chromeos-keyboard --form-factor=CHROMEBOOK --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --child-wallpaper-large=/usr/share/chromeos-assets/wallpaper/child_large.jpg --child-wallpaper-small=/usr/share/chromeos-assets/wallpaper/child_small.jpg --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/oem_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/oem_small.jpg --default-wallpaper-is-oem --enable-consumer-kiosk --ozone-nnpalm-properties={} --disable-features=InstantTethering --arc-availability=officially-supported --enable-houdini --enterprise-enrollment-initial-modulus=15 --enterprise-enrollment-modulus-limit=19 --enable-crashpad --login-manager --first-exec-after-boot --vmodule=*arc/*=1,*night_light*=1,*/chromeos/power/auto_screen_brightness/*=1,*/ash/wm/tablet_mode/*=1,wizard_controller=1,*/webui/chromeos/login/*=1,*/browser/chromeos/login/screens/*=1,enrollment_screen_handler=1,*/browser/chromeos/login/enrollment/*=1,*/ui/ozone/*=1,*/ui/display/manager/chromeos/*=1 --enable-features=SmartDim,UmaStorageDimensions,Crostini,CrostiniGpuSupport,CrostiniEnableDlc --disable-features=InstantTethering --flag-switches-begin --flag-switches-end --ui-compositor-memory-limit-when-visible-mb=512
Executable Path	/opt/google/chrome/chrome
Profile Path	/home/chronos/u-8f9f042b1091f52b8eeb76a6e844416c25f8e685
Variations	1d758480-377be55a
5213eae1-69a6410b
77056158-377be55a
cbfd06b9-ca7d8d80
85bf39f3-377be55a
16b16054-377be55a
b0f75187-377be55a
1fa5b2f3-377be55a
59b6f412-377be55a
60d4b352-377be55a
b3249ec4-377be55a
a9ef513c-377be55a
6cb5e962-377be55a
f5a851ad-377be55a
d9e26b10-377be55a
3095aa95-3f4a17df
65d2bc3-377be55a
ace1c2dc-377be55a
edb58ea9-377be55a
d97d6ab5-377be55a
47bd2c48-377be55a
8e44abde-377be55a
47b5f350-377be55a
8f83697a-e70e85
f2cb61f-377be55a
dc2bb3ae-377be55a
b05c2566-377be55a
65570806-ebfb497f
a2e38c9c-ca7d8d80
dd8d67e-23c1fc5a
2cff698a-62d8b965
f6f5c542-12ede6a2
8ebcf27b-46931943
a582a1b8-ad75ce17
98be3390-377be55a
e4a357e9-ca7d8d80
6262de83-377be55a
83a11282-cd0c5295
e79de56c-4b407058
357a64de-ca7d8d80
3c42bcc5-377be55a
244970-91c810ef
9bfe3ed7-3f4a17df
56b8af1f-8f65fe02
d1591620-10c8698
72ab65ce-1fd511a3
a120b571-74a852ec
291d0672-7c933c8b
153e930d-33c3eba5
7a911e9f-80311101
7dec9614-377be55a
12366760-377be55a
f8947f2b-377be55a
55894b82-410b0ec4
d3566fbd-377be55a
cb9831f4-377be55a
7048821f-9d6bb081
f48aee36-377be55a
eda60cb-377be55a
dc69f43d-377be55a
64970026-377be55a
6a9d5557-377be55a
56165f3f-377be55a
931c5f72-5c0c1f00
494d8760-52325d43
3ac60855-486e2a9c
63dcb6a3-477de798
e706e746-58ca20a
f296190c-9ce370dd
4442aae2-e1cc0f14
f690cf64-75cb33fc
ed1d377-e1cc0f14
75f0f0a0-a5822863
710c3f90-d7f6b13c
e2b18481-7564fb06
e7e71889-e1cc0f14
b1ceb06f-d1372334
d39d5f23-377be55a
fb50494f-72cac062
547e761a-3f4a17df
89f843ca-2cbb00ec
5e31bb48-75513c66
abb39457-f237da07
c4c291c4-3f4a17df
a9deeaf7-602b1d49
a461b170-377be55a
fc330dc9-377be55a
def27776-ca7d8d80
5f2d3e7b-38429e84
```

### Anything else?

no

**Comment by artdeell** [comment]
x86 is not fully supported by the launcher, and also you used a wrong runtime

**Comment by DevinC76** [comment]
So it won't work right?

**Comment by GaucovyAero** [comment]
> So it won't work right?

Okay, so to recapitulate:

1. You have used the wrong runtime. Should have used JRE17 for x86 (you used aarch64).
2. Even if you were to install the correct runtime, it won't work because of some issues/bugs. 
3. A solution to this is sticking with 1.16.5 or a lower version. If you want to join a 1.17 server, you can easily bypass it by using Legacy Fabric for 1.8.9 and a mod, which I don't remeber the name of. The mod does 1.17 support on 1.8.9 basically.

**Comment by DevinC76** [comment]
--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-tinyfd.jar, lwjgl.jar, lwjgl-opengl.jar, version, lwjgl-glfw-classes.jar, lwjgl-stb.jar, lwjgl-openal.jar, lwjgl-jemalloc.jar]
Architecture: x86
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.8
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1366
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/bin:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-RsYXb1Snm5u9qwQFfULA6A==/lib/x86
Added custom env: POJAV_RENDERER=opengles3
Added custom env: LIBGL_ES=3
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=768
--------- beginning of main
I/jrelog  ( 3905): dlopen libgl4es_115.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjli.so success
I/jrelog  ( 3905): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libverify.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjava.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnet.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnio.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt_headless.so failed: dlopen failed: library "libawt.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfontmanager.so failed: dlopen failed: library "libawt.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement_ext.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libdt_socket.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libverify.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libprefs.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjawt.so failed: dlopen failed: library "libawt.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libzip.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfontmanager.so failed: dlopen failed: library "libawt.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libj2gss.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjdwp.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjavajpeg.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjaas.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/liblcms.so failed: dlopen failed: library "libawt.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt_headless.so failed: dlopen failed: library "libawt.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libextnet.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libsyslookup.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjsig.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/librmi.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmlib_image.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libsctp.so failed: dlopen failed: library "libnio.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjava.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjimage.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement_agent.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libattach.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libinstrument.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjli.so success
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnio.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  ( 3905): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnet.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3905): dlopen /data/app/net.kdt.pojavlaunch-RsYXb1Snm5u9qwQFfULA6A==/lib/x86/libopenal.so success
I/jrelog  ( 3905): Done processing args
I/jrelog  ( 3905): Found JLI lib
I/jrelog  ( 3905): Calling JLI_Launch
Error: dl failure on line 542

Error: failed /data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so, because dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)

Java Exit code: 6
I/jrelog  ( 3905): Going to free args
I/jrelog  ( 3905): Free done
--------- beginning of system

**Comment by artdeell** [comment]
x86 is not fully supported
