### ISSUE TITLE
[BUG] <Short description>You can't advance from the menu (it only happens to me when installing fabric)

### ISSUE THREAD

**Issue by Tonyasdasda** [PojavLauncherTeam/PojavLauncher#3238]
### Describe the bug

Install the latest fabric version when I try to create a world or go to options I can't interact with the menu

### The log file and images/videos

>

### Steps To Reproduce

```markdown
Install the latest fabric version when I try to create a world or go to options I can't interact with the menu
```

### Expected Behavior

It will work normally like the other versions

### Platform

```markdown
- Device model: One plus 8T 8ram 128
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version:last version
```

**Comment by offbeat-stuff** [comment]
may try fabric loader 13.3 when I tried to run fabric loader 14.4 my mouse stopped so maybe
also please send logs

**Comment by Puneetbrine** [comment]
I can't enter my premium account it is coming response error 404

**Comment by Gamerawesome865** [comment]
I cant inteact with anything to,but it only happens when i go on forge o fabic above 1.12.2
I've tied eveything i've could but no luck.If anyone could help me my discord is jerky#2522

**Comment by Gamerawesome865** [comment]
I fixed it, so wha you have to do is wait fo eveything to download you cant press skip when you ae loading into the game

**Comment by Gamerawesome865** [comment]
Nevermind i fixed it for 1 day, but then i cant click so if anyone help please.jerky#2522

**Comment by GaucovyAero** [comment]
> Nevermind i fixed it for 1 day, but then i cant click so if anyone help please.jerky#2522

Join our official PojavLauncher discord server i guess...
