### ISSUE TITLE
[BUG] <Requires an account>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3241]
### Describe the bug

Requires an account
I can not buy an account in my country and most of the servers I work on do not need an account, please delete it because it is very annoying

### The log file and images/videos

![Screenshot_2022-05-18-00-46-58-493_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/90418723/168902450-25e2cbb9-b084-4162-b77b-d2ed23126b6c.jpg)

### Steps To Reproduce

```markdown
1.Start Pojavlancher
2.run Minecraft
3.Requires an account
```

### Expected Behavior

Play Game Crack server's

### Platform

```markdown
- Device model: Poco X3 GT
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: crocus 573
```

**Comment by ThePangel** [comment]
You have to have an account because if pojav gave you Minecraft they could get sued, its not their problem you cannot buy Minecraft, just use a vpn

**Comment by ghost** [comment]
So what difference does it make if there is an offline mode?
Why we can with T-Launcher and some launchers, but not this launcher 
What version has this been added since?

**Comment by SMAAMX** [comment]
Can I revert to older versions?

> شما باید یک حساب کاربری داشته باشید زیرا اگر pojav به شما Minecraft بدهد ممکن است شکایت کنند، مشکل آنها نیست شما نمی توانید Minecraft بخرید، فقط از vpn استفاده کنید.

**Comment by ghost** [comment]
> شما باید یک حساب کاربری داشته باشید زیرا اگر pojav به شما Minecraft بدهد ممکن است شکایت کنند، مشکل آنها نیست شما نمی توانید Minecraft بخرید، فقط از vpn استفاده کنید.

There is no account in my sanctioned country and therefore I can not buy it
And I do not know how to convert money into dollars

**Comment by ghost** [comment]
I will only try the older version
