### ISSUE TITLE
[BUG] < problem 1.12.2 forge>

### ISSUE THREAD

**Issue by MHMD456** [PojavLauncherTeam/PojavLauncher#3242]
### Describe the bug

When i run the 1.12.2 forge ( 14.23.5.2860 version) , I try to run a mod pack that's name is ( SevTech_Ages_3.2.3 ) forge 1.12.2 give me a error 1 and a can't play in ( I know mod pack in really heavy for pojavluncher but i play it in server , and in past I play better Minecraft version 1.16.5 with my phone in server and in run and I have lag but that's working . But I can't run 1.12.2 forge with this mod and not show me loading screen and it crash with error code 1 ) 
My phone have 6 GB ram and android 11 and i give pojavluncher 2.7 GB ram 
Thanks.

### The log file and images/videos

Full description given 

### Steps To Reproduce

```markdown
1. I run pojavluncher forge 1.12.2 mod SevTech_Ages_3.2.3 and it crash and show me error code 1
```

### Expected Behavior

I expected the game to run because I had no problem with other heavier mod packs 

### Platform

```markdown
- Device model: Redmi not 8 pro / 128G
- CPU architecture: 
- Android version: 11
- PojavLauncher version: The latest version of the Play Store
```

**Comment by artdeell** [comment]
No log.

**Comment by GaucovyAero** [comment]
> ### Describe the bug
> When i run the 1.12.2 forge ( 14.23.5.2860 version) , I try to run a mod pack that's name is ( SevTech_Ages_3.2.3 ) forge 1.12.2 give me a error 1 and a can't play in ( I know mod pack in really heavy for pojavluncher but i play it in server , and in past I play better Minecraft version 1.16.5 with my phone in server and in run and I have lag but that's working . But I can't run 1.12.2 forge with this mod and not show me loading screen and it crash with error code 1 ) My phone have 6 GB ram and android 11 and i give pojavluncher 2.7 GB ram Thanks.
> 
> ### The log file and images/videos
> Full description given
> 
> ### Steps To Reproduce
> ```gfm
> 1. I run pojavluncher forge 1.12.2 mod SevTech_Ages_3.2.3 and it crash and show me error code 1
> ```
> 
> ### Expected Behavior
> I expected the game to run because I had no problem with other heavier mod packs
> 
> ### Platform
> ```gfm
> - Device model: Redmi not 8 pro / 128G
> - CPU architecture: 
> - Android version: 11
> - PojavLauncher version: The latest version of the Play Store
> ```
> 
> ### Anything else?
> _No response_

No log attached.
