### ISSUE TITLE
[BUG] < 1.12.2 forge have problem >

### ISSUE THREAD

**Issue by MHMD456** [PojavLauncherTeam/PojavLauncher#3243]
### Describe the bug

When i run the 1.12.2 forge ( 14.23.5.2860 version) , I try to run a mod pack that's name is ( SevTech_Ages_3.2.3 ) forge 1.12.2 give me a error 1 and a can't play in ( I know mod pack in really heavy for pojavluncher but i play it in server , and in past I play better Minecraft version 1.16.5 with my phone in server and in run and I have lag but that's working . But I can't run 1.12.2 forge with this mod and not show me loading screen and it crash with error code 1 )
My phone have 6 GB ram and android 11 and i give pojavluncher 2.7 GB ram
Thanks.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8717978/latestlog.txt) 
![Screenshot_۲۰۲۲-۰۵-۱۸-۲۰-۲۷-۰۹-۸۷۶_net kdt pojavlaunch](https://user-images.githubusercontent.com/105789863/169088198-9bed69df-aefb-45f0-a8f9-8c12c335d5e5.jpg)
![Screenshot_۲۰۲۲-۰۵-۱۸-۲۰-۲۷-۱۵-۳۶۵_net kdt pojavlaunch](https://user-images.githubusercontent.com/105789863/169088235-290391a7-b8e5-4dbf-a4be-f864660e627c.jpg)
![Screenshot_۲۰۲۲-۰۵-۱۸-۲۰-۲۷-۴۴-۰۳۵_net kdt pojavlaunch](https://user-images.githubusercontent.com/105789863/169088253-e8d7b3c7-dfbe-45e5-8037-176cc59802a3.jpg)
![Screenshot_۲۰۲۲-۰۵-۱۸-۲۰-۲۷-۵۲-۹۹۸_net kdt pojavlaunch](https://user-images.githubusercontent.com/105789863/169088276-afd6b6a8-145f-4c0b-b887-f65da87cc4e0.jpg)

### Steps To Reproduce

```markdown
1. I am running Forge 1.12.2, but when the loading page does not appear, Exit Game comes, but there is nothing in the crash report.
```

### Expected Behavior

I expect the game to run because I have already run heavier modpacks with version 1.16.5 and played on the server.

### Platform

```markdown
- Device model: Redmi note 8 pro /128GB
- CPU architecture: Eight-core maximum 2.05 GHz 
- Android version: 11
- PojavLauncher version:The latest version in the Play Store
```

**Comment by artdeell** [comment]
you made a whole another issue and STILL didn't bother to provide log. closing, duplicate of #3242

**Comment by artdeell** [comment]
Wait, you closed the old one. Still, waiting for log.

**Comment by MHMD456** [comment]
I'm sorry because this is the second time I'm done this. And I really do not know what exactly I mean by logging in and how to do it. I uploaded the log file from the game folder because I am with the phone. It's a bit of a problem for me Thank you

**Comment by GaucovyAero** [comment]
> Wait, you closed the old one. Still, waiting for log.

he send the log tho, the error is this:

![Screenshot from 2022-05-18 18-11-52](https://user-images.githubusercontent.com/85581164/169090831-58398671-02c8-488f-b63f-9a869cee45af.png)

I presume it's an issue with QuarkASM or randomepic42069ASM or anything similar.

**Comment by MHMD456** [comment]
I already had a log file that was for Pooja and I deleted it because somewhere on the same site I saw someone upload another log file and said that if you put this file instead of the previous file, the problem will be solved, but The problem was not solved and the original log file, which was for me, was deleted. I do not know what effect the log file has on the game.

**Comment by GaucovyAero** [comment]
> I already had a log file that was for Pooja and I deleted it because somewhere on the same site I saw someone upload another log file and said that if you put this file instead of the previous file, the problem will be solved, but The problem was not solved and the original log file, which was for me, was deleted. I do not know what effect the log file has on the game.

Your MC is crashing because of mod incompatibilities, not anything else probably.

**Comment by MHMD456** [comment]
Maybe this can help.
![Screenshot_۲۰۲۲-۰۵-۱۸-۲۰-۵۲-۱۴-۴۳۶_net kdt pojavlaunch](https://user-images.githubusercontent.com/105789863/169093125-1a2d605e-77bc-4f5d-b819-b5ed8ea13261.jpg)

**Comment by NotAHero04** [comment]
The mod that causes the issue is Random Patches, which is a known oddball.

**Comment by MHMD456** [comment]
> حالتی که باعث این مشکل می شود، Patch های تصادفی است که یک توپ عجیب و غریب شناخته شده است.

I think so too

**Comment by MHMD456** [comment]
When I run the game and the game crashes, these two folders appear automatically in my modes folder. 
[memory_repo.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8718368/memory_repo.zip)
[1.12.2.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8718369/1.12.2.zip)

**Comment by GaucovyAero** [comment]
> When I run the game and the game crashes, these two folders appear automatically in my modes folder. [memory_repo.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8718368/memory_repo.zip) [1.12.2.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/8718369/1.12.2.zip)

Absolutely no idea but you should definitely remove Random Patches.

**Comment by MHMD456** [comment]
Thanks to everyone who guided me and took the time to help me.
