### ISSUE TITLE
[F-Req] ZINK ANDROID 11?

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#3244]
### Is this request related to a bug?

No.

### Describe the request.

I saw some YouTubers that zink works on their PowerVR 
And i tried it to my moms phone that has the same PowerVr and when i press start it still says Not supported :( in My mom Android 11 phone.

### Anything else?

Do you know how zink works on Android 11?

I just hope so :)

**Comment by mchnjt** [comment]
what the fuck

**Comment by vannnemcee** [comment]
ok i can use zink rendering on android 11

**Comment by MARnelPH12** [comment]
How?

**Comment by mchnjt** [comment]
> How?

:sparkles: magic :sparkles:

**Comment by MARnelPH12** [comment]
Na men Just fr?

**Comment by tigerbrocode** [comment]
> Na men Just fr?

What version are you trying to launch

Did you download jre 17

Lastly what is your mom's phone specs

**Comment by artdeell** [comment]
Zink is not supported
