### ISSUE TITLE
[BUG] Logging in to an already logged in account, then switching accounts causing crash

### ISSUE THREAD

**Issue by 0n** [PojavLauncherTeam/PojavLauncher#3246]
### Describe the bug

Crashing when switching accounts to the same account being already used

### The log file and images/videos

https://streamja.com/bwze6

### Steps To Reproduce

```markdown
Be already logged in to a Microsoft account

Log in using the Microsoft Login button

Switch accounts to the same account

Crash
```

### Expected Behavior

Realize it's the same account and merge them in the UI

### Platform

```markdown
- Device model: ROG Phone II
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest release on the playstore
```

**Comment by GaucovyAero** [comment]
Not the latest PojavLauncher, not by a longshot. The version is almost 1 year old. Go into Actions here on GitHub and grab the latest build with a green checkmark on it. The newest build may not work at all, so make sure you test them one by one.

**Comment by 0n** [comment]
> Not the latest PojavLauncher, not by a longshot. The version is almost 1 year old. Go into Actions here on GitHub and grab the latest build with a green checkmark on it. The newest build may not work at all, so make sure you test them one by one.

It's the latest on the playstore, if it's not the latest elsewhere it should be updated on the playstore

**Comment by GaucovyAero** [comment]
> > Not the latest PojavLauncher, not by a longshot. The version is almost 1 year old. Go into Actions here on GitHub and grab the latest build with a green checkmark on it. The newest build may not work at all, so make sure you test them one by one.
> 
> It's the latest on the playstore, if it's not the latest elsewhere it should be updated on the playstore

Please read the whole message I have sent. The latest update currently (**crocus-573-9e26e4871-v3_openjdk**) is just 4 days old and you can find it here in Actions.

**Comment by 0n** [comment]
Yo @artdeell update the playstore version

**Comment by 0n** [comment]
> > > Not the latest PojavLauncher, not by a longshot. The version is almost 1 year old. Go into Actions here on GitHub and grab the latest build with a green checkmark on it. The newest build may not work at all, so make sure you test them one by one.
> > 
> > 
> > It's the latest on the playstore, if it's not the latest elsewhere it should be updated on the playstore
> 
> Please read the whole message I have sent. The latest update currently (**crocus-573-9e26e4871-v3_openjdk**) is just 4 days old and you can find it here in Actions.

Direct link pliz

**Comment by GaucovyAero** [comment]
> > > > Not the latest PojavLauncher, not by a longshot. The version is almost 1 year old. Go into Actions here on GitHub and grab the latest build with a green checkmark on it. The newest build may not work at all, so make sure you test them one by one.
> > > 
> > > 
> > > It's the latest on the playstore, if it's not the latest elsewhere it should be updated on the playstore
> > 
> > 
> > Please read the whole message I have sent. The latest update currently (**crocus-573-9e26e4871-v3_openjdk**) is just 4 days old and you can find it here in Actions.
> 
> Direct link pliz

No.

**Comment by KentangGG121** [comment]
Try to use from github one
