### ISSUE TITLE
Issue with game

### ISSUE THREAD

**Issue by jillv46** [PojavLauncherTeam/PojavLauncher#3247]
### Describe the bug

I'm trying to make it feel 100% like java and I can free move my mouse and keyboard when playing but it feels like Bedrock and I have to drag to move my cursor etc. I'm using BlueStacks Andoid Emulator on my gaming laptop and I want pc controls while playing not dragging to play. Is there anyway I can make it act like actual java?

### The log file and images/videos

I have nothing

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Try to move in game
```

### Expected Behavior

I expect to move like actual java but I don't

### Platform

```markdown
- Device model: Samsung S21 Ultra
- CPU architecture: Not sure
- Android version: Not sure since I'm using an emulator on my laptop
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I just want to make it to feel like java and not like Bedrock. And also does this launcher have an email support? I can't get support any other way since discord requires verification and I'm having issues with it and the staff don't want to help me

**Comment by artdeell** [comment]
if you have a gaming laptop, juat use the launcher from https://minecraft.net

mouse grab on emulators is not supported.

**Comment by jillv46** [comment]
I have the Java launcher but it requires migrating and since Microsoft ruined Bedrock with payment on everything like skins etc, I don't want my Java account with them either

**Comment by jillv46** [comment]
> if you have a gaming laptop, juat use the launcher from https://minecraft.net
> 
> mouse grab on emulators is not supported.

Idk if you say my other message or not
