### ISSUE TITLE
I am not able to load 1.18.2 on pojav launcher on Android

### ISSUE THREAD

**Issue by SkshmGaming** [PojavLauncherTeam/PojavLauncher#3248]
### Is this request related to a bug?

![Screenshot_20220521_135500](https://user-images.githubusercontent.com/105980181/169655342-7aa1791d-c904-423c-90a8-3311d9b17697.jpg)

**Comment by GaucovyAero** [comment]
Hi, you should update PojavLauncher. You can download an update from 16.5.2022 [here](https://github.com/PojavLauncherTeam/PojavLauncher/suites/6521502861/artifacts/242911679).

**Comment by offbeat-stuff** [comment]
It shows the problem you downloaded the wrong runtime
use the arm64 runtime

**Comment by SkshmGaming** [comment]
Sir please can you send the link for arm 64 runtime to play 1.18.2 on the
launcher

**Comment by artdeell** [comment]
Please use a valid runtime for your device
