### ISSUE TITLE
Won't start on pocoF1. Stuck on grey screen with controls. V3

### ISSUE THREAD

**Issue by golimonkey** [PojavLauncherTeam/PojavLauncher#325]
After launch (1.16.3 and 1.15.?) grey creen apears, controls are interactive but nothing hapens. I waited for about 10min. No mojang logo, no error messages no logs...

**Comment by artdeell** [comment]
V.3 or V.2?

**Comment by golimonkey** [comment]
V3 sorry

**Comment by khanhduytran0** [comment]
So now provide
- Launcher testing build
- Which Java Runtime architecture installed?
- Is LWJGL3 installed? Check `/sdcard/games/.minecraft/lwjgl3` folder. You need install manually.

**Comment by khanhduytran0** [comment]
- Did you read instuction carefully?

**Comment by golimonkey** [comment]
Tried again today. 

Screenchots: https://imgur.com/9PopTxB      https://imgur.com/eT34KHF

Minecraft 1.16.3
Launcher testing build: V3 testing 4
Java: jre9-arm32-20200919.tar.xz
LWJGL3: installed
PocoF1: MIUI 11.0.6.0 Android 10


Also tested java jre9-aarch64-20200920.tar.xz, with that version everything just closes after I download and game tries to start. No aparent logs.

**Comment by khanhduytran0** [comment]
testing4+ does not support aarch64 java runtime as it disabled

**Comment by khanhduytran0** [comment]
No latestlog.txt in first try??

**Comment by golimonkey** [comment]
latestlog says:

------- beginning of system
------- beginning of main

####Nothing else

**Comment by khanhduytran0** [comment]
Does that log on trying aarch32 java?

**Comment by golimonkey** [comment]
yes aarch32

**Comment by golimonkey** [comment]
I also looked at it with aarch 64. Output was ~50 lines. (but that should be irelevant now?)

**Comment by khanhduytran0** [comment]
Maybe send here

**Comment by khanhduytran0** [comment]
Send directly here as GitHub support include files

**Comment by golimonkey** [comment]
Aarch64 log

--------- beginning of system
--------- beginning of main
S/jrelog  (17459): Error occurred during initialization of VM
S/jrelog  (17459): Initial heap size set to a larger value than the maximum heap size
S/jrelog  (17459): 
S/jrelog  (17459): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so failed
S/jrelog  (17459): : dlopen failed: library "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so" not founddlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so failed: dlopen failed: library "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so" not founddlopen /data/app/net.kdt.pojavlaunch-adkkR2Tupp0rTn4HtGGBvQ==/lib/arm64/libopenal.so successdlopen /data/app/net.kdt.pojavlaunch-adkkR2Tupp0rTn4HtGGBvQ==/lib/arm64/libgl04es.so successDone processing argsFound JLI libCalling JLI_Launch
S/jrelog  (17459): [ERROR:mailbox_manager_sync.cc(57)] eglCreateSyncKHR failed

**Comment by khanhduytran0** [comment]
So you need understand Java Arguments

**Comment by khanhduytran0** [comment]
`-Xmx` must be equals or higher than `-Xms`
For example:
```
-Xms768m -Xmx512m
```
Will result in error above

**Comment by golimonkey** [comment]
I understand. Now it is grey screen with aarch64.

**Comment by khanhduytran0** [comment]
Now you need wait

**Comment by golimonkey** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/23/20, 11:24 PM
Description: Initializing game

java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:0
	at ded.b(SourceFile:180)
	at ded.b(SourceFile:149)
	at ded.d(SourceFile:65)
	at ded.a(SourceFile:54)
	at ded.<init>(SourceFile:45)
	at djw.<init>(SourceFile:466)
	at net.minecraft.client.main.Main.main(SourceFile:177)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ded.b(SourceFile:180)
	at ded.b(SourceFile:149)
	at ded.d(SourceFile:65)
	at ded.a(SourceFile:54)
	at ded.<init>(SourceFile:45)
	at djw.<init>(SourceFile:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (aarch64) version 4.9.186-perf-g636a063
	Java Version: 9-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 791251616 bytes (754 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xms1024m -Xmx1024m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.3
	Backend library: LWJGL version 3.2.3 build 13
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: 9x null

**Comment by khanhduytran0** [comment]
You should use testing4 with aarch32 java

**Comment by khanhduytran0** [comment]
While 64-bit can allocate more than 950mb, but 32-bit can't, so you need change after switch to testing4

**Comment by golimonkey** [comment]
Tried aarch32 but stuck on grey screen. This time changed xms and xmx to 900MB. Waited >10min Had to force close.

**Comment by khanhduytran0** [comment]
Check latestlog.txt?

**Comment by golimonkey** [comment]
> `` @
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5274610/latestlog.txt)

**Comment by khanhduytran0** [comment]
You need update to testing5

**Comment by khanhduytran0** [comment]
Also extract testing5 LWJGL3 replace old one

**Comment by golimonkey** [comment]
Upgraded to testing 5, set xmx and xms to 800MB, used aarch32. It started and I was able to navigate game menu. It lags periodicaly, shows that app is not responding but then works ok if you ignore warning for few seconds.

**Comment by albertstarfield** [comment]
kiln Ms ilpo k to keep oiolp ilpo 😆o ➿ ip lol
