### ISSUE TITLE
Resolved

### ISSUE THREAD

**Issue by UAG0** [PojavLauncherTeam/PojavLauncher#3254]
Resolved

**Comment by UAG0** [comment]
Galaxy s7 fe*

**Comment by Ichy29** [comment]
I too can't, this glitch is occurring with me so

**Comment by forkiesassds** [comment]
Can repro, happens when I install fabric loader.

**Comment by forkiesassds** [comment]
Seems to be solved by latest update

**Comment by BUGAMING85677** [comment]
Don't on your mouse during game is loading.

**Comment by UAG0** [comment]
****

**Comment by UAG0** [comment]
_**resolved**_
