### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by KOHTPAKT** [PojavLauncherTeam/PojavLauncher#3256]
### Describe the bug

when i creating the world, the application exited with code -1
and i using fabric 1.17.1 and sodium
but when i tried to create a world without any modifications, its working.

### The log file and images/videos

[crash-2022-05-23_14.38.48-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8755671/crash-2022-05-23_14.38.48-client.txt)
https://drive.google.com/file/d/13oa-NuHLx2IMv7t1KBoU8PypgNjULiDp/view?usp=sharing   (video)

### Steps To Reproduce

```markdown
I can try to download a Fabric API for 1.17.1, maybe i installed for 1.18.2... meh it is not working
```

### Expected Behavior

Game launches, all installed correctly, but the worlds aren't working

### Platform

```markdown
- Device model: Samsung A31
- CPU architecture: 6x ARM Cortex-A55 and 2x ARM Cortex-A75
- Android version: 12
- PojavLauncher version: crocus-579-f89eb4a51-v3_opendjdk
```

**Comment by Dgs555** [comment]
It wasn't complete

**Comment by Dgs555** [comment]
But ok

**Comment by mchnjt** [comment]
what the

**Comment by KOHTPAKT** [comment]
> what the

idk what really happened, but I think, this is problem with sodium. I tried to play without any mods, everything is working well.

**Comment by ToxicGamingGithub** [comment]
Same

**Comment by ghost** [comment]
Similar with me when i use fabric 1.16.5 in any world or server its just like every blocks are invisible

**Comment by KOHTPAKT** [comment]
> Similar with me when i use fabric 1.16.5 in any world or server its just like every blocks are invisible

yeah, I had this problem on 1.16.5. Know how to fix?

**Comment by ghost** [comment]
Idk im trying to fix it but it dosennt work
