### ISSUE TITLE
[BUG] Not letting me Make a New world in Forge 1.18.2

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#3257]
### Describe the bug

Hi Devs! im thankful to all devs in here that made playing Forge 1.18.2 possible but i have a little problem it wouldnt let me make a world for some reason maybe cause of my Device or because of Opengl 2.1 Renderer? idk honestly on other mods it let me create a world however when i Put this mods

Mods List:
![Screenshot_2022-05-24-22-40-42-30](https://user-images.githubusercontent.com/87040006/170063043-db3ef666-2f67-4cf1-83f4-7a0482fb9b05.jpg)

https://user-images.githubusercontent.com/87040006/170063240-8abd898b-256c-4635-aa03-f8d3ff6c0722.mp4

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8763767/latest.log)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Launch Forge 1.18.2 
3. Select Play
4.Select Singleplayer
5. Try to make a new world but i cant
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: Arm64
- Android version: 9
- PojavLauncher version: Latest Github Build the one that have name Made Enable
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
Maybe something with quark? Not sure, make sure you send latestlog.txt instead of latest.log.

**Comment by Jamespoxdxdxd** [comment]
> Maybe something with quark? Not sure, make sure you send latestlog.txt instead of latest.log.

so sorry for late reply im busy this is the latestlog
im doing some school stuffs
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8765167/latestlog.txt)

**Comment by artdeell** [comment]
Checked the log. Looks like a Forge or the mod bug. Closing for now
