### ISSUE TITLE
[F-Req] Where are the rest of the renders? 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#3258]
### Is this request related to a bug?

In the latest version of pojavlauncher there are only 2 renders: virgl and gl4es 1.1.4.
virgl render works terribly on my device 
gl4es 1.1.4 does not render the colors of sheep and banners

### Describe the request.

Why did you need to remove the renders: gl4es 1.1.5, vgpu, zink which worked almost perfectly on my device.

**Comment by Mizuuwa** [comment]
Skill Issue, maybe they merged all of the features of the renderers except Zink cause it's trash.

**Comment by artdeell** [comment]
The issue with sheep was fixed on our mod of gl4es 1.1.4

**Comment by Iarkont** [comment]
> The issue with sheep was fixed on our mod of gl4es 1.1.4

gl4es 1.1.4 does not draw many elements of mods unlike gl4es 1.1.5 here is an example of a mod xareos mini map launched in a new build pojavlauncher on render gl4es 1.1.4 
![Screenshot_20220525_102935_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/170236995-7027d3cd-4e75-4693-82f4-8a3ed4bd8484.jpg)

**Comment by artdeell** [comment]
you haven't uploaded the image

**Comment by Mathias-Boulay** [comment]
There are gone, and most likely not coming back.
We have size and device compatibility constraints to abide by.
