### ISSUE TITLE
[BUG] <stuck on Mojang>

### ISSUE THREAD

**Issue by Nikit2345** [PojavLauncherTeam/PojavLauncher#3259]
### Describe the bug

When starting version 1.5.2, while waiting for the launch, the only thing I saw was only the Mojang intro.

### The log file and images/videos

![Screenshot_2022-05-25-09-33-37-462_net kdt pojavlaunch](https://user-images.githubusercontent.com/101510441/170181442-497c6c58-3ca2-4ca3-a3c3-40a15abccae3.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start v.1.5.2
3. Waiting for start
4. Understanding that this is an endless loading
```

### Expected Behavior

I expect 1.5.4 to launch

### Platform

```markdown
- Device model: Redmi 9A
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
Looks like you haven't deleted the options.txt file and you're getting a null pointer on the base classes. Delete options.txt.

**Comment by Nikit2345** [comment]
> Looks like you haven't deleted the options.txt file and you're getting a null pointer on the base classes. Delete options.txt.
Thx, it's working

**Comment by Mathias-Boulay** [comment]
I'll try to provide something to auto swap options file for lower versions

**Comment by KentangGG121** [comment]
Delete the options.txt file and loading it back and the problem solved!
