### ISSUE TITLE
My device can't run version 1.13 and higher and stuck on black screen

### ISSUE THREAD

**Issue by Huskykunz** [PojavLauncherTeam/PojavLauncher#326]

**Comment by Huskykunz** [comment]
My device can run version 1.11.2 but can't run version 1.13 and higher,
Redmi 6a 2 gb ram

**Comment by khanhduytran0** [comment]
So which java are you on?

**Comment by khanhduytran0** [comment]
Are you on v2???

**Comment by khanhduytran0** [comment]
V2 does not support 1.13+

**Comment by Huskykunz** [comment]
Jre-x86

> Are you on v2???

No,i use version 3.2 testing 4

**Comment by Huskykunz** [comment]
> So which java are you on?

Jre-x86

**Comment by khanhduytran0** [comment]
JRE x86 is compatible with Intel and AMD CPU only.

**Comment by khanhduytran0** [comment]
So you need use aarch32 one

**Comment by Huskykunz** [comment]
So, aarch32 can run v 1.13 and higher in my device?

**Comment by khanhduytran0** [comment]
Yes

**Comment by Huskykunz** [comment]
Nothing happened,same as before.
Stuck on black screen
Sorry,i install wrong java,i instal aarch64

**Comment by khanhduytran0** [comment]
Please provide latestlog.txt

**Comment by Huskykunz** [comment]
--------- beginning of main
read: unexpected EOF!

**Comment by khanhduytran0** [comment]
I said that don't use aarch64

**Comment by Huskykunz** [comment]
I've downloaded aarch32

**Comment by Huskykunz** [comment]
Now,i need instal v 3.2 testing 4 or testing 3?

**Comment by khanhduytran0** [comment]
Use testing4

**Comment by khanhduytran0** [comment]
Testing5 will soon be released as include
- Fix mouse not working
- Implement char callback, now allow type text

**Comment by Huskykunz** [comment]
Oh,i have other bug too,My Keyboard bug

**Comment by khanhduytran0** [comment]
So what about that bug?

**Comment by Huskykunz** [comment]
I can't write in my keyboard

**Comment by artdeell** [comment]
Is fixed, wait for testing5

пт, 25 сент. 2020 г., 12:27 Huskykunz <notifications@github.com>:

**Comment by khanhduytran0** [comment]
> wait for testing5

I already released testing5 yesterday https://github.com/PojavLauncherTeam/PojavLauncher/releases/tag/v3.2.0-testing5

**Comment by Huskykunz** [comment]
Ok

**Comment by khanhduytran0** [comment]
So this will be closed. Reopen if you still get
