### ISSUE TITLE
1.18 crash (please  help)

### ISSUE THREAD

**Issue by fav-devs** [PojavLauncherTeam/PojavLauncher#3260]
### Describe the bug

After entering a world for 10 seconds the game crashes it then returns me to the  launcher homescreen I have tried this many times but there  is no solution.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8771466/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojav 
Tap play
Play anyway
Single player 
Enter world
```

### Expected Behavior

I expect game to launch 

### Platform

```markdown
- Device model: Samsung a71
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Version crocus-v3_openjdk
```

### Anything else?

I have placed the assets file in the resource packs folder and  have set the runtime manager to Jre 17 and my renderer is gl4es 1.15 opengl es3
Although I have tried all the renderers they all have the same problem.

**Comment by GaucovyAero** [comment]
Well, unfortunate. You probably didn't know this, but pirating is not an option right now, and is never going to be in the future for Pojav. You're crashing because you haven't bought Minecraft. There is a workaround for this, but we won't tell you. You have to buy Minecraft.

**Comment by Mathias-Boulay** [comment]
Buying minecraft is needed
