### ISSUE TITLE
[I can't install forge] <Every time I try to install forge it shows: Application/game closed with code 1.

### ISSUE THREAD

**Issue by Comic22** [PojavLauncherTeam/PojavLauncher#3261]
### Describe the bug

![Screenshot_20220525-142728_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/106269755/170326599-3a888ad5-81b1-4c3f-b3a2-246ae547fb13.jpg)
 

### The log file and images/videos

![Screenshot_20220525-142728_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/106269755/170327012-ca868c6f-7a86-4a98-a5bb-f614d843f3a9.jpg)

Translation: Application/game closed with code 1

### Steps To Reproduce

```markdown
Every time I go to install forge on poiavluncher
```

### Expected Behavior

don't give this problem!

### Platform

```markdown
- Device model: Samsung A30s
- CPU architecture: Mali
- Android version: 11
- PojavLauncher version: (Play Store) current version
```

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build, wait for an update soon 😄
