### ISSUE TITLE
How to play forge 1.18.2 tell me

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3263]
### Is this request related to a bug?

How to download forge 1.18.2 plss tell me

### Describe the request.

Tell me how too download forge 1.18.2

### Anything else?

Just forge 1.18.2

**Comment by Mizuuwa** [comment]
You and when they are is but yeah

**Comment by Mathias-Boulay** [comment]
You download forge installer jar
you install it via the install jar button
You launch it.
Pretty much the same as pc.
