### ISSUE TITLE
[BUG] <Game closes when trying to open Forge. error 1 >

### ISSUE THREAD

**Issue by Japperder** [PojavLauncherTeam/PojavLauncher#3264]
### Describe the bug

Application exited with error 1

### The log file and images/videos

![Screenshot 2022-05-26 14 38 49](https://user-images.githubusercontent.com/106318449/170489354-0a02a5eb-ef1e-4998-ae21-48b633e86034.png)

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. select forge
3. starts like usual ( black screen with the GUI)
4. the game crashes
```

### Expected Behavior

i expect it to work

### Platform

```markdown
- Device model: chromebook
- CPU architecture: idk
- Android version: above 10 bcs i can use pojavlauncher
- PojavLauncher version: probbably the newest
```

**Comment by Mathias-Boulay** [comment]
Send the log file or get terminated.

**Comment by Japperder** [comment]
i cant find a log file

**Comment by Mathias-Boulay** [comment]
under /Android/data/net.kdt.pojavlauncher(.debug if you're using the newest)/files

**Comment by Japperder** [comment]
this?

--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, jsr305.jar, lwjgl-jemalloc.jar, lwjgl-tinyfd.jar, lwjgl.jar, lwjgl-opengl.jar, version, lwjgl-openal.jar, lwjgl-stb.jar]
Architecture: x86_64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.2-forge-40.1.0 (1.18.2)
--------- beginning of main
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1366
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~6y0wRdrquZrqN38luUJxDw==/net.kdt.pojavlaunch-IWLH6c2bIOa_m7pWcbye-w==/lib/x86_64
Added custom env: POJAV_RENDERER=opengles3
Added custom env: LIBGL_ES=3
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=768
Initialising gl4es
v1.1.5 built on Aug 18 2021 16:49:37
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers is in core ES3, and so used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Extension GL_EXT_frag_depth  detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Max texture size: 16384
Max Varying Vector: 32
Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Max Color Attachments: 8 / Draw buffers: 8
Hardware vendor is Mesa/X.org
GLSL 300 es supported
GLSL 310 es supported and used
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
Targeting OpenGL 2.1
NPOT texture handled in hardware
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  ( 3658): dlopen libgl4es_115.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 3658): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libattach.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libmlib_image.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/librmi.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libsvml.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libinstrument.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjsig.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libzip.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libdt_socket.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libextnet.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/liblcms.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libjdwp.so success
I/jrelog  ( 3658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86_64-20210825-release.tar.xz/lib/libsctp.so success
I/jrelog  ( 3658): dlopen /data/app/~~6y0wRdrquZrqN38luUJxDw==/net.kdt.pojavlaunch-IWLH6c2bIOa_m7pWcbye-w==/lib/x86_64/libopenal.so success
I/jrelog  ( 3658): Done processing args
I/jrelog  ( 3658): Found JLI lib
I/jrelog  ( 3658): Calling JLI_Launch
Exception in thread "main" 
java.lang.module.FindException: Module cpw.mods.securejarhandler not found, required by cpw.mods.bootstraplauncher
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:492)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:137)
Java Exit code: 1
I/jrelog  ( 3658): Going to free args
I/jrelog  ( 3658): Free done
--------- beginning of system

**Comment by Mathias-Boulay** [comment]
Yep

**Comment by Mathias-Boulay** [comment]
This issue is fixed in the latest candidate release build. Will be pushed to gplay sooner or later

**Comment by Japperder** [comment]
okay
