### ISSUE TITLE
[HELP] link for 1.17/1.18/1.19 Patcher And 1.17/1.18/1.19 optifine patcher

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3265]
### Describe the bug

[HELP] link for 1.17/1.18/1.19 Patcher And 1.17/1.18/1.19 optifine patcher please give me the link 

### The log file and images/videos

[HELP] link for 1.17/1.18/1.19 Patcher And 1.17/1.18/1.19 optifine patcher please give me the link 

### Steps To Reproduce

```markdown
[HELP] link for 1.17/1.18/1.19 Patcher And 1.17/1.18/1.19 optifine patcher please give me the link
```

### Expected Behavior

[HELP] link for 1.17/1.18/1.19 Patcher And 1.17/1.18/1.19 optifine patcher please give me the link v

### Platform

```markdown
- Device model:s6 lite tab
- CPU architecture:aarch64
- Android version:11
- PojavLauncher version:latest google play version
```

### Anything else?

[HELP] link for 1.17/1.18/1.19 Patcher And 1.17/1.18/1.19 optifine patcher please give me the link

**Comment by ghost** [comment]
And the link for latest candidate release build please

**Comment by Mathias-Boulay** [comment]
not needed on the release candidate build.

**Comment by ghost** [comment]
> not needed on the release candidate build.

Can You Give The Candidate build
