### ISSUE TITLE
[F-Req] Make It So We Can Change The Color Of The Virtual Mouse

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3266]
### Is this request related to a bug?

No, Make It So We Can Change The Color Of The Virtual Mouse

### Describe the request.

Make It So We Can Change The Color Of The Virtual Mouse

### Anything else?

Make It So We Can Change The Color Of The Virtual Mouse

**Comment by ghost** [comment]
And also update the play store pojavlauncher

**Comment by Mathias-Boulay** [comment]
#2763
