### ISSUE TITLE
[BUG] <Short description>forge fabric and optifine installer error 

### ISSUE THREAD

**Issue by Matryx0207w** [PojavLauncherTeam/PojavLauncher#3269]
### Describe the bug

installing forge fabric or optifine on 1.16.5 closes pojavlauncher 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8787064/latestlog.txt)

### Steps To Reproduce

```markdown
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7b2da76cf8
```

### Expected Behavior

only that I could install forge optifine and fabric 

### Platform

```markdown
- Device model: redmi note 8 2021 4/128
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: última versión 3.3.1.1
```

### Anything else?

I hope you can help me with this problem

**Comment by artdeell** [comment]
3.3.1.1 is massively outdated

**Comment by Matryx0207w** [comment]
how out of date?

**Comment by Matryx0207w** [comment]
how outdated

**Comment by Matryx0207w** [comment]
I use the Google play version

**Comment by artdeell** [comment]
one year old

**Comment by artdeell** [comment]
google play version is not 3.3.1.1 but also isn't latest

**Comment by Matryx0207w** [comment]
So what can I Acer 🧐

**Comment by GaucovyAero** [comment]
> So what can I Acer monocle_face

? xD

**Comment by Matryx0207w** [comment]
Then I will look for the most current version

**Comment by GaucovyAero** [comment]
> Then I will look for the most current version

Its in the Actions tab here on GitHub.

**Comment by Matryx0207w** [comment]
Thanks for the help

**Comment by GaucovyAero** [comment]
np

**Comment by Matryx0207w** [comment]
update and see what happens
