### ISSUE TITLE
[F-Req] Add Minecraft Bedrock Support

### ISSUE THREAD

**Issue by MistGitHub24** [PojavLauncherTeam/PojavLauncher#3270]
### Is this request related to a bug?

No

### Describe the request.

I want support For Minecraft bedrock. If it's not possible than it's fine

### Anything else?

No

**Comment by kuzy21** [comment]
tf just download bedrock, this is only a java launcher

**Comment by artdeell** [comment]
minecraft bedrock is literally available on playstore and appstore
