### ISSUE TITLE
1.18.2 Crash

### ISSUE THREAD

**Issue by 8SamPSH9** [PojavLauncherTeam/PojavLauncher#3271]
### Describe the bug

Rendering overlay error and game exited with java 17 and open gl 4.6

### The log file and images/videos

![Screenshot_20220527-205927_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88630012/170740794-7510cae1-cf4b-4915-aa08-918f7dcc8033.jpg)

### Steps To Reproduce

```markdown
1.select 1.18.2
2.select java 17
3.select opengl 4.6 
4.and tap play
5.game exited
```

### Expected Behavior

i expect to 1.18.2 run and i can play on my Own population SMP😔

### Platform

```markdown
- Device model: Samsung galaxy A71
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest release on google play store
```

### Anything else?

Plssssss fix it

**Comment by GaucovyAero** [comment]
We have already fixed it, but you haven't updated yet. Update by clicking on the latest build in GitHub Actions, downloading app-debug and installing app-debug.apk.

**Comment by Mathias-Boulay** [comment]
fixed in the release candidate build
