### ISSUE TITLE
[BUG] Fabric 1.18.2 Crashes

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3272]
### Describe the bug

Crash

### The log file and images/videos

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 5/27/22, 5:34 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.lwjgl.glfw.GLFW.glfwGetWindowAttrib(GLFW.java:949)
	at dynamicfps.DynamicFPSMod.checkForRender(DynamicFPSMod.java:68)
	at net.minecraft.class_757.handler$zzi000$onRender(class_757.java:1519)
	at net.minecraft.class_757.method_3192(class_757.java)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.glfwGetWindowAttrib(GLFW.java:949)
	at dynamicfps.DynamicFPSMod.checkForRender(DynamicFPSMod.java:68)
	at net.minecraft.class_757.handler$zzi000$onRender(class_757.java:1519)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2383)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 954384296 bytes (910 MiB) / 1203765248 bytes (1148 MiB) up to 1203765248 bytes (1148 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd09 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4414.22
	Virtual memory used (MB): 5088.27
	Swap memory total (MB): 2560.00
	Swap memory used (MB): 1702.81
	JVM Flags: 2 total; -Xms1148M -Xmx1148M
	Fabric Mods: 
		alternate-current: Alternate Current 1.2.1
		betterbeds: Better Beds 1.2.0
		cullleaves: Cull Leaves 2.3.2
			midnightlib: MidnightLib 0.2.9
		dark-loading-screen: Dark Loading Screen 1.6.11
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entityculling: EntityCulling-Fabric 1.5.0
		fabric: Fabric API 0.53.4+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.5+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.16+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.12+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.4+d8d7804a60
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.1+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.1+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.0+2afceb2960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.14.6
		fastchest: FastChest 1.2+1.18
		ferritecore: FerriteCore 4.2.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		ksyxis: Ksyxis 1.1
		lazy-language-loader: lazy-language-loader 0.3.0
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.10
		minecraft: Minecraft 1.18.2
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		smoke_suppression: Smoke Suppression 1.0.9-1
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.4+mc1.18.2-build.39
			caffeineconfig: CaffeineConfig 1.1.0
		starlight: Starlight 1.0.2+fabric.89b8d9f
		vmp: Very Many Players 0.2.0+beta.3.17
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: zink (Mali-G72) GL version 4.6 (Compatibility Profile) Mesa 21.0.3 (git-0f92d7633e), Collabora Ltd
	Window size: 2000x1200
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x 

### Steps To Reproduce

```markdown
1.Start PojavLauncher 
2.Launch Fabric 1.18.2
3.Put Mods (Fabric API Included)
4.Launch Fabric 1.18.2
5.Crash
I Already Used The Runtime Using Zink (Vulcan):Exports Opengl 4.6
```

### Expected Behavior

I Expect the game to launch

### Platform

```markdown
- Device model: Samsung S6lite tab
- CPU architecture: aarch64 4gb ram 64gb memory
- Android version: Android 11
- PojavLauncher version: Latest Google Play Version
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
Thanks for actually clarifying that it's the latest Google Play version instead of "Latest version". Basically, the issue is that you're almost 1 year out of date. Update to the actually latest version here in GitHub actions by clicking on the latest build, downloading app-debug, extracting it and installing app-debug.apk.

**Comment by Mathias-Boulay** [comment]
Since we fixed it, closing

**Comment by ghost** [comment]
> Thanks for actually clarifying that it's the latest Google Play version instead of "Latest version". Basically, the issue is that you're almost 1 year out of date. Update to the actually latest version here in GitHub actions by clicking on the latest build, downloading app-debug, extracting it and installing app-debug.apk.

Do you any mc java ģen

**Comment by ghost** [comment]
> Since we fixed it, closing

Do you kno2 any mc acc gen
