### ISSUE TITLE
[BUG] crash on 1.19 pre1/2/3

### ISSUE THREAD

**Issue by PortableGames** [PojavLauncherTeam/PojavLauncher#3274]
### Describe the bug

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 28.05.22 4:11
Description: Initializing game

java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
	at egh.<init>(SourceFile:26)
	at egh.<clinit>(SourceFile:24)
	at egb.<init>(SourceFile:160)
	at eeu.<init>(SourceFile:585)
	at net.minecraft.client.main.Main.main(SourceFile:198)
Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at egh.<init>(SourceFile:26)
	at egh.<clinit>(SourceFile:24)
	at egb.<init>(SourceFile:160)
	at eeu.<init>(SourceFile:585)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:198)

-- System Details --
Details:
	Minecraft Version: 1.19 Pre-release 3
	Minecraft Version ID: 1.19-pre3
	Operating System: Linux (aarch64) version Android-12
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 730971648 bytes (697 MiB) / 1526726656 bytes (1456 MiB) up to 1526726656 bytes (1456 MiB)
	CPUs: 8
	Processor Vendor: 0x51
	Processor Name: AArch64 Processor rev 2 (aarch64)
	Identifier: 0x51 Family 8 Model 0x800 Stepping r0xap4
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3900,47
	Virtual memory used (MB): 4040,25
	Swap memory total (MB): 2048,00
	Swap memory used (MB): 947,13
	JVM Flags: 2 total; -Xms1455M -Xmx1455M
	Launched Version: 1.19-pre3
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: zink (Adreno (TM) 610) GL version 4.6 (Compatibility Profile) Mesa 21.0.3 (git-0f92d7633e), Collabora Ltd
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 2 (aarch64)

All other versions work to snapshot 22w19a .. only 1.19 pre1/2/3 crash

### The log file and images/videos

?

### Steps To Reproduce

```markdown
Launch version 1.19 pre1/2/3
```

### Expected Behavior

?

### Platform

```markdown
Details:
	Minecraft Version: 1.19 Pre-release 3
	Minecraft Version ID: 1.19-pre3
	Operating System: Linux (aarch64) version Android-12
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 730971648 bytes (697 MiB) / 1526726656 bytes (1456 MiB) up to 1526726656 bytes (1456 MiB)
	CPUs: 8
	Processor Vendor: 0x51
	Processor Name: AArch64 Processor rev 2 (aarch64)
	Identifier: 0x51 Family 8 Model 0x800 Stepping r0xap4
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3900,47
	Virtual memory used (MB): 4040,25
	Swap memory total (MB): 2048,00
	Swap memory used (MB): 947,13
	JVM Flags: 2 total; -Xms1455M -Xmx1455M
	Launched Version: 1.19-pre3
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: zink (Adreno (TM) 610) GL version 4.6 (Compatibility Profile) Mesa 21.0.3 (git-0f92d7633e), Collabora Ltd
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 2 (aarch64)
```

**Comment by artdeell** [comment]
This issue was fixed on latest builds.
