### ISSUE TITLE
[BUG] Crash when joining servers on 1.18.1 with fabric and mods

### ISSUE THREAD

**Issue by KentangGG121** [PojavLauncherTeam/PojavLauncher#3275]
### Describe the bug
I was playing on server and when joining world it crashing no log just crash with code 1 

Mods di i used:

OptiFabric=OptiFine

[latestlog.txt](https://www.mediafire.com/download/byjyt23sq3lm6q1) 

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Select 1.18.1 fabric and mods
3. Loading up the game
4. Join a server
5. Crash with code 1
```

### Expected Behavior

It crashing when i join a server

### Platform

```markdown
- Device model: Vivo y50
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version: github build
```

### Anything else?

Nothing

**Comment by ghost** [comment]
The fabric and forge is only supported officially till 1.16.5

**Comment by GaucovyAero** [comment]
> The fabric and forge is only supported officially till 1.16.5

dafuq? not true, 1.17 and 1.18 fabric and forge both work now

**Comment by GaucovyAero** [comment]
```
FATAL ERROR in native method: Thread[Render thread,10,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL30C.nglBindFragDataLocation(Native Method)
```

Make sure to disable Render Regions in OptiFine Performance settings, it may be causing your crashing issue. If this doesn't work, try creating a new world or joining multiplayer. And if that doesn't work, join our official PojavLauncher discord server and ask for help there. Support is a lot faster there.
