### ISSUE TITLE
[BUG] <Short description> I can't login

### ISSUE THREAD

**Issue by Apaa21** [PojavLauncherTeam/PojavLauncher#3276]
### Describe the bug

![Screenshot_20220528-203707](https://user-images.githubusercontent.com/106435611/170825998-0f69567b-395d-44eb-8599-4d81818f823b.png)

### The log file and images/videos

![Screenshot_20220528-203707](https://user-images.githubusercontent.com/106435611/170826050-7084c699-8325-4f47-8eb3-5ec50882f1f9.png)

### Steps To Reproduce

```markdown
I meed you help
```

### Expected Behavior

Can you fix this? I can't login online account.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Can you help me?

**Comment by Mathias-Boulay** [comment]
If you have a microsoft account, use the microsoft account button.
Else, migrate to microsoft
