### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Gostikus123** [PojavLauncherTeam/PojavLauncher#3277]
### Describe the bug

hello. When i playing in my world with those mods:
Thaumcraft 6, twilight Forest, custom npc,  deco craft, journey map, optifine, better fps, biblio craft, mo bends, hunger strike, improved back packs, nashorn, phosphor, quark, varied comoditions. I got crush without crash log but in lastlog write another error, not mine. So when i deleted optifine this error is gone, what i need do? Cuz i need optifine cuz optifine block shaders from thaumcraft effects 

### The log file and images/videos

![Screenshot_2022-05-28-22-20-49-220_com mi android globalFileexplorer](https://user-images.githubusercontent.com/106449627/170840267-38c83664-cf0b-4551-80bd-b99156d5ca13.jpg)
![Screenshot_2022-05-28-22-20-52-334_com mi android globalFileexplorer](https://user-images.githubusercontent.com/106449627/170840269-59162f15-4c69-4528-95d7-4046a696bf7b.jpg)
![Screenshot_2022-05-28-22-20-54-010_com mi android globalFileexplorer](https://user-images.githubusercontent.com/106449627/170840270-7e740d1d-0e48-4153-8bc7-8c4ff0fa4107.jpg)

### Steps To Reproduce

```markdown
1 just go into my world
2 gone some times
3 crush without crush log
```

### Expected Behavior

Im had waiting what my world will be stable

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Mathias-Boulay** [comment]
Sadly, mod compatibility is a hit or miss right now.
Even more so when we come to shader compatibility
See #1948
