### ISSUE TITLE
[BUG] 1.8.9 forge crashes with the new renderer.

### ISSUE THREAD

**Issue by OggyCodingStuff** [PojavLauncherTeam/PojavLauncher#3278]
### Describe the bug

1.8.9 and 1.18.2 forge crashes with the new *renderer*

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Login
3. Launch 1.8.9 or 1.18.2 forge
```

### Expected Behavior

it dose not shows any behavior thing

### Platform

```markdown
- Device model: Galaxy S21 Ultra/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Release
```

**Comment by KentangGG121** [comment]
My fabric 1.18.1 it crashing too

**Comment by Mathias-Boulay** [comment]
Send the log or get terminated

**Comment by OggyCodingStuff** [comment]
i cant copy the latestlog code thing ._.

**Comment by OggyCodingStuff** [comment]
Never mind i fixed it by deleting the data
