### ISSUE TITLE
[BUG] mirror settings

### ISSUE THREAD

**Issue by Aninz** [PojavLauncherTeam/PojavLauncher#3279]
### Describe the bug

Backwards Words within the Setting

### The log file and images/videos

![Screenshot_2022-05-29-12-56-48-800_net kdt pojavlaunch](https://user-images.githubusercontent.com/90094318/170853816-f3f1bd85-2849-4a19-9b49-f08b7d1f4186.jpg)
![Screenshot_2022-05-29-13-34-00-380_net kdt pojavlaunch](https://user-images.githubusercontent.com/90094318/170853882-9558ea98-a071-46c3-aa33-e5e6f51a05f0.jpg)

### Steps To Reproduce

```markdown
Open pojav
Log in 
Go to Setting section
Backward Setting
```

### Expected Behavior

Backwards Setting

### Platform

```markdown
- Device model: poco f3
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: dalhia v3 openjdk
```

**Comment by EnderBrine99FOX** [comment]
I Have the same issue

**Comment by Mathias-Boulay** [comment]
Fixed in the dev builds, and the latest release too
