### ISSUE TITLE
I Can't Remapped/Use The Keyboard Correctly + some keys keep Holding (dahlia-v3_openjdk build)

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#3280]
### Describe the bug

I Can't Bind Keys in My Keyboard + My Shift Button keep Holding Even If I Press it Once (Same For Other Keys) 

### The log file and images/videos

https://user-images.githubusercontent.com/79517194/170859403-c59030d2-ea8e-4105-a401-4defac6dc8bb.mp4

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Enter Any World
3.Play With Keyboard And Mouse
4.Buttons Doesn't Function
```

### Expected Behavior

Even Tho This Build Fixed My 120hz Issue it Comes With Even WORST Issue I Hope They Fix It Very Soon, Also This Bug is In The Debug Build Too

### Platform

```markdown
- Device model: Poco X3 Pro
- CPU architecture: aarch64 
- Android version: 12
- PojavLauncher version: dahlia-v3_openjdk
```

### Anything else?

Thanks For Your Support

**Comment by Mathias-Boulay** [comment]
*I hate miui more and more*

**Comment by NotAhackerforfun** [comment]
It's moving on its own for me if I walks it keep walking if I stop it tho

**Comment by EnderBrine99FOX** [comment]
1-The Remappe Issue Is Solved But You Need To Click the  Button Twice To Remappe it ( Still Broken in GP Build) 
2- The Latest Debug Build Kinda Fixed The Shift issue But Its Still Occur Anyways
3- There's Still Some Keyboard Function That Doesn't Work Correctly
4-Thank You For Reading This And I Appreciate Your Hard Work❤️

**Comment by GaucovyAero** [comment]
Yeah, you will have to flash a custom non-MIUI ROM onto your device to fix this. There is likely no other way. MIUI other than the fact that decreases performance by 50%, it also creates these issue that can't be fixed simultaneously on clean Android and on MIUI, which is well, unfortunate.

**Comment by Mathias-Boulay** [comment]
current dev builds should address the remaining issues
