### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by kobepullup** [PojavLauncherTeam/PojavLauncher#3281]
### Describe the bug

i am trying to get  forge on my pojavlauncher fore a while now i looked it up and the only thing i see is fixed in the release candidate build and i am asking how long this is going to take before it comes out because it is a problem fore a long time now

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: .
- CPU architecture: .
- Android version: .
- PojavLauncher version: .
```

**Comment by Mathias-Boulay** [comment]
The dahlia update is live on the play store.
Please, avoid creating issues for dumb stuff like this.
This only slows down development

**Comment by kobepullup** [comment]
sorry i was a bit dramitic i should of looked thx fore even replying
