### ISSUE TITLE
[BUG] <unable to play a modded server>

### ISSUE THREAD

**Issue by Japperder** [PojavLauncherTeam/PojavLauncher#3284]
### Describe the bug

i have forge installed and it works. i downloaded mods and put them in the mod folder using filemanager then i start up the game and i cant join the sever with the mods. my friend had a solution (and heres the problem) I just needed to go to "mods"(in game) then press on "open mods folder" and then i can add the mods. but. when i press it nothing happens, it doesn't open a folder

### The log file and images/videos

there is no log file or video for this

### Steps To Reproduce

```markdown
1. start pojav
2. press "mods"
3. press "open mods folder"
```

### Expected Behavior

i expect it to open a folder with the mods so i can add them

### Platform

```markdown
- Device model: chromebook
- CPU architecture: 
- Android version: 
- PojavLauncher version: newest version
```

**Comment by kobepullup** [comment]
they cant fix that in that way

**Comment by kobepullup** [comment]
o jij bent het

**Comment by Japperder** [comment]
Ja

**Comment by tigerbrocode** [comment]
So let me guide you through this 

First download an app called zarchiver from the playstore, now click on the three buttons on the top right then click settings then click file list then you will see "show hidden files" click it (if already on then ignore) then go to games/pojavlauncher/.minecraft/mods and insert the mod there  or go to android/data/net.kdt.pojavlaunch/files/.minecraft/mods and insert there

**Comment by Japperder** [comment]
Thank you, it works now
