### ISSUE TITLE
[BUG] <Short description> optifine error

### ISSUE THREAD

**Issue by Gostikus123** [PojavLauncherTeam/PojavLauncher#3285]
### Describe the bug

When i open minecraft1.12.2 with forge and optifine i got crush with code -1 just black screen loading and crush

### The log file and images/videos

![Screenshot_2022-05-29-21-27-39-034_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/106449627/170886072-76eaa624-168b-4f18-aaef-c9d791e15724.jpg)
![Screenshot_2022-05-29-21-27-44-264_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/106449627/170886079-87784238-9bf7-4803-af89-27d53d3b459b.jpg)

### Steps To Reproduce

```markdown
1open pojavlauncher
2open forge 1.12.2 (version of game)
3waiting and crush
```

### Expected Behavior

Im waiting what game is open

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Gostikus123** [comment]
Я узнал что это было из-за твайлайт Фореста но почему?

**Comment by Mathias-Boulay** [comment]
#1948
