### ISSUE TITLE
[BUG]Unreadable fonts in titles

### ISSUE THREAD

**Issue by Bunny6968** [PojavLauncherTeam/PojavLauncher#3287]
### Describe the bug

Whenever I try to open the settings (Of pojavalunch) Ofc to see new features , It shows unreadable words in titles (upside down etc ...) even changing renderers etc.... 

If anyone knows how to fix please reply onthis thread

### The log file and images/videos

![20220530_011701](https://user-images.githubusercontent.com/106491296/170888821-23acf899-22e5-425d-9394-1e973762e1e3.jpg)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Login to Mojang/Microsoft Account
3.Open settings tab (by sliding on press on settings in left down corner)
4.Unreadable upsidedown words
```

### Expected Behavior

Expected Fonts to Show correctly

### Platform

```markdown
- Device model: Samsung J7 3/32GB
- CPU architecture: aarch32
- Android version: 9
- PojavLauncher version: latest
```

**Comment by Mathias-Boulay** [comment]
We've noted this breaking issue, it will promptly be fixed in an update

**Comment by offbeat-stuff** [comment]
That says back to the last screen.
Its not unreadable

**Comment by JagritThukral** [comment]
Yeah it's inverted

**Comment by NotAhackerforfun** [comment]
Yes its inverted

**Comment by AstralVRZ** [comment]
![Screenshot_20220530-123001](https://user-images.githubusercontent.com/92945138/170974303-04e53a56-7864-45c8-b90c-03d8b16ec205.png)
Turns out it can also invert your entire game :)

**Comment by GaucovyAero** [comment]
> ![Screenshot_20220530-123001](https://user-images.githubusercontent.com/92945138/170974303-04e53a56-7864-45c8-b90c-03d8b16ec205.png) Turns out it can also invert your entire game :)

Because you are using VirGL instead of gl4es. VirGL also decreases performance even if it wouldn't invert your screen. Use gl4es and your issue is going to be fixed.

**Comment by JagritThukral** [comment]
@Aerolome nope why would renderer cause this issue . Also renderer wouldn't effect launcher

**Comment by miggythewriter** [comment]
@Aerolome the render wouldn't affect the launcher

**Comment by GaucovyAero** [comment]
> @Aerolome the render wouldn't affect the launcher

The renderer doesn't cause the issue with the launcher. Only the issue ingame. The fact that the issue looks the same both in game and in the launcher is just a coincidence, so beware. Changing the renderer is going to fix the ingame problems.

**Comment by miggythewriter** [comment]
@Aerolome did you look at the image it's using holy gl4es

**Comment by offbeat-stuff** [comment]
It happened to me a months back when using gl4es

**Comment by Mathias-Boulay** [comment]
Fixed on the release of today

**Comment by Bunny6968** [comment]
Thanks
