### ISSUE TITLE
[F-Req] please restore offline account in pojav launcher .

### ISSUE THREAD

**Issue by GlitchAlpha000** [PojavLauncherTeam/PojavLauncher#3288]

**Comment by InfiniXDerg** [comment]
No shut up and buy an account there: https://minecraft.net

**Comment by MerciGG** [comment]
Imagine not having an account L
![Screenshot_2022-05-30-17-26-39-53_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/100085202/170962021-eda97e38-b065-4750-8be3-81fe1c3d09b3.jpg)
Those are mostly alts to play 2b2t

**Comment by vanistillhere** [comment]
https://minecraft.net/
should fix your issue 🙂

**Comment by mchnjt** [comment]
> Imagine not having an account L ![Screenshot_2022-05-30-17-26-39-53_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/100085202/170962021-eda97e38-b065-4750-8be3-81fe1c3d09b3.jpg) Those are mostly alts to play 2b2t

Login with those on Hypixel to check their validity (and legality) :trollface:

**Comment by Jamespoxdxdxd** [comment]
> Imagine not having an account L ![Screenshot_2022-05-30-17-26-39-53_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/100085202/170962021-eda97e38-b065-4750-8be3-81fe1c3d09b3.jpg) Those are mos

> Imagine not having an account L ![Screenshot_2022-05-30-17-26-39-53_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/100085202/170962021-eda97e38-b065-4750-8be3-81fe1c3d09b3.jpg) Those are mostly alts to play 2b2t

theres no way your that rich thats alot of account LOL

**Comment by vanistillhere** [comment]
> > Imagine not having an account L ![Screenshot_2022-05-30-17-26-39-53_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/100085202/170962021-eda97e38-b065-4750-8be3-81fe1c3d09b3.jpg) Those are mos
> 
> > Imagine not having an account L ![Screenshot_2022-05-30-17-26-39-53_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/100085202/170962021-eda97e38-b065-4750-8be3-81fe1c3d09b3.jpg) Those are mostly alts to play 2b2t
> 
> theres no way your that rich thats alot of account LOL 

ikr, seems very suspicious... 
_where did you get your nfa-s_

**Comment by InfiniXDerg** [comment]
<@712923899142078464> close ETA when (imma try now with Ping-pong)
<@&835808706042134608>
