### ISSUE TITLE
[BUG] Mouse doesn't display where it actually is.

### ISSUE THREAD

**Issue by AstralVRZ** [PojavLauncherTeam/PojavLauncher#3289]
### Describe the bug

The visual mouse is not in the same place as the actual mouse that highlights the buttons. 

### The log file and images/videos

https://user-images.githubusercontent.com/92945138/170937406-3e86023c-24c7-4758-a099-9d45df2e8a42.mp4

https://user-images.githubusercontent.com/92945138/170937413-7f6b1cbc-8ef7-485e-954e-e223700f8f45.mp4

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Launch any version.
3. Hover over any button.
4. When the mouse is over a button it isn't always when it should be highlighted.
```

### Expected Behavior

I expect the mouse to highlight the correct things.

### Platform

```markdown
- Device model: moto g 5G plus
- CPU architecture: AArch64
- Android version: 11
- PojavLauncher version: dahlia-v3_openjdk
```

**Comment by Mousebu** [comment]
Yeah it also happens with me fix this please

**Comment by REYASKANNAN** [comment]
I can't click any of the single player or multiplayer even I can't click quit game the mouse is working but couldn't click even I click the home button on mobile and clear on the minimize and again went to pohavlanchur multipletimes but still I won't work

But that problem in fabric 1.16.5 but I can use normal vinnila 1.16.5 I can click on 1.16.5 also I really need the fabric
Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…

**Comment by REYASKANNAN** [comment]
![Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…]()

**Comment by GaucovyAero** [comment]
This is a known issue if you have a notch and you Android version is lower than 9 (which means Android 8.1 and lower has this issue). Google started implementing notch support in early developement builds of Android 9 and therefore you either have to flash a custom ROM onto your device, or you will be left with this issue.

**Comment by Mathias-Boulay** [comment]
Mistake, moto g 5G plus runs android 10/11.
Although tweaks have been made, so this issue is no more
