### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Tiger56c** [PojavLauncherTeam/PojavLauncher#3292]
### Is this request related to a bug?

WE NEED THE OFFLINE ACCOUNT BACK!!!

**Comment by NotAHero04** [comment]
So, will you pay the developers $30.000 for each time Microsoft sue them? If yes, go ahead.

**Comment by vanistillhere** [comment]
accept the fact that you don't own an account
it's seriously not that hard

**Comment by Tiger56c** [comment]
I just wanna play

**Comment by mchnjt** [comment]
> I just wanna play

excuse not accepted, go buy minecraft

**Comment by vanistillhere** [comment]
> I just wanna play

unfortunately, you can't do that anymore
a minecraft account is now needed because pojav almost got sued by mojang themselves iirc

and no, fuck your nfas

**Comment by Tiger56c** [comment]
I'm just gonna quit pojavlauncher

**Comment by mchnjt** [comment]
then quit lmao we don't give a shit

**Comment by ghost** [comment]
not possible simply.
nobody wants to get sued by a big company. and what's about purchasing a minecraft account? it's same as pc, even on pc somehow you gotta use a mc account legally

**Comment by vanistillhere** [comment]
> I'm just gonna quit pojavlauncher

that's fine, in the soon future you'll probably have a job which means you can buy an account

or buy a pc before that <:likebhai:972012294085152828>

**Comment by mchnjt** [comment]
> > I'm just gonna quit pojavlauncher
> 
> that's fine, in the soon future you'll probably have a job which means you can buy an account
> 
> or buy a pc before that <:likebhai:972012294085152828>

just a reminder, this isn't discord

**Comment by NotAHero04** [comment]
> I just wanna play

At least, who told you to update? 😆

**Comment by vanistillhere** [comment]
> > > I'm just gonna quit pojavlauncher
> > 
> > that's fine, in the soon future you'll probably have a job which means you can buy an account
> > 
> > or buy a pc before that <:likebhai:972012294085152828>
> 
> just a reminder, this isn't discord

it's gonna show up on the embed dw <:likebhai:972012294085152828><:likebhai:972012294085152828><:likebhai:972012294085152828>

**Comment by vanistillhere** [comment]
bhai let me test this <@!955066189850230827>

**Comment by vanistillhere** [comment]
you can ask for an account in <#729671788187091024> and get banned immediately too

**Comment by mchnjt** [comment]
bruh

**Comment by InfiniXDerg** [comment]
<#815977607413497866> moment
