### ISSUE TITLE
To All People who dont have Mojang Accounts/Microsoft Accounts

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#3293]
### Is this request related to a bug?

Guys I would recommend to all cracked players to downgrade Pojavlauncher or just stay in Minecraft Bedrock Edition cause they aint going to bring back Offline account just for you Lol so.. yeah kind of sad but yeah if you really want to play Pojavlauncher buy the game or just go to Minecraft Generators? 

### Describe the request.

.

### Anything else?

.

**Comment by inari-codes** [comment]
Bedrock Edition just simply sucks

**Comment by mchnjt** [comment]
> ### Is this request related to a bug?
> Guys I would recommend to all cracked players to downgrade Pojavlauncher or just stay in Minecraft Bedrock Edition cause they aint going to bring back Offline account just for you Lol so.. yeah kind of sad but yeah if you really want to play Pojavlauncher buy the game or just go to Minecraft Generators?
> 
> ### Describe the request.
> .
> 
> ### Anything else?
> .

no

**Comment by ABJ4403** [comment]
It would be great if someone makes a fork of this project that keeps the "Offline account" option...

**Comment by mchnjt** [comment]
> It would be great if someone makes a fork of this project that keeps the "Offline account" option...

If there is such active fork that
- has the latest commits
- keeping the offline mode button
the team will likely take it down. We'd be breaking Microsoft's agreement if we didn't remove Offline Mode.
Buy Minecraft. That's your only fix.
