### ISSUE TITLE
Offline mode!!

### ISSUE THREAD

**Issue by GerritJand** [PojavLauncherTeam/PojavLauncher#3295]
### Is this request related to a bug?

Why do you remove the offline mode?
All my frends played on it!!!
Turn it back on!

### Describe the request.

Why do you remove the offline mode?
All my frends played on it!!!
Turn it back on!

### Anything else?

Why do you remove the offline mode?
All my frends played on it!!!
Turn it back on!

**Comment by Mathias-Boulay** [comment]
Another dude who wants to go to prison it seems

**Comment by miggythewriter** [comment]
Pirate detected
