### ISSUE TITLE
Add joystick 🕹️ simulator for easy moving

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3297]

**Comment by miggythewriter** [comment]
This is not a issue 
It's a pull request

**Comment by khanhduytran0** [comment]
It wouldn’t work as you think. Minecraft supports only WASD input, so by mapping to joystick you only get 8 directions, not 360. This is also a known limitation when mapping from physical joystick on a controller.

Another problem is the movement speed, either you drag near or far, the speed will remain same (unless there are some detections which decide whenever to toggle sprint/crouch but then you get total 3 different movement speeds, not 100).

If you want swipe-able between buttons to look like a joystick, there’s an option in the custom controls.
