### ISSUE TITLE
The versions 1.8,1.9,1.10,1.11 is not working

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#33]
On 1.8 when you jump or fly game freeze and crash on 1.9,1.10,1.11 when you load a world and when you move game crash and I am using android 8 oreo

**Comment by khanhduytran0** [comment]
Please copy the crash report.

**Comment by khanhduytran0** [comment]
Please go back to previous preview and wait for fix.

**Comment by ghost** [comment]
This is the copy of the crash log on 1.9
     Description: Unexpected error

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.awt.Graphics.drawImage(java.awt.Image, int, int, int, int, int, int, int, int, java.awt.image.ImageObserver)' on a null object reference
	at bng.n(SourceFile:1105)
	at bng.a(SourceFile:1017)
	at bcf.av(SourceFile:985)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:748)
	at net.kdt.pojavlaunch.MainActivity.access$1000073(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000013$100000012.run(MainActivity.java:509)
	at java.lang.Thread.run(Thread.java:764)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at aht.a(SourceFile:2833)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bmt['xfd2009'/257, l='MpServer', x=-5.50, y=81.00, z=257.50]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-4,64,256), Chunk: (at 12,4,0 in -1,16; contains blocks -16,0,256 to -1,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 83 game time, 83 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [bmt['xfd2009'/257, l='MpServer', x=-5.50, y=81.00, z=257.50], vu['Bat'/455, l='MpServer', x=4.27, y=25.04, z=259.55], vu['Bat'/523, l='MpServer', x=10.16, y=16.00, z=247.49], vu['Bat'/396, l='MpServer', x=7.23, y=27.53, z=263.48], vu['Bat'/466, l='MpServer', x=-4.44, y=14.29, z=247.36]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at aht.a(SourceFile:2833)
	at bku.a(SourceFile:365)
	at bcf.b(SourceFile:2515)
	at bcf.a(SourceFile:406)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:748)
	at net.kdt.pojavlaunch.MainActivity.access$1000073(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000013$100000012.run(MainActivity.java:509)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (aarch64) version 3.18.91-14843133-QB28059365
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (null), The Android Project
	Memory: 0 bytes (0 MB) / 360553752 bytes (343 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.9
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.9b1
