### ISSUE TITLE
Can't do online login, an error shows while sign in using gmail account

### ISSUE THREAD

**Issue by halomanlodestar** [PojavLauncherTeam/PojavLauncher#330]
Whenever i tries to sign in to play servers it show an error, even if my username and password is correct (i use my gmail account). I tried it multiple times but same problem show. Please help maybe I'm wrong at some place.

**Comment by khanhduytran0** [comment]
Do you have premium account registered in that gmail?

**Comment by halomanlodestar** [comment]
Well thnx to help me actually my premium account was not registered on my
gmail but now I registered it and it's working absolutely amazing and I can
play with upto 70 FPS. Nice job, this is the finest launcher I have found
yet and it's the best for those people who don't wants to mess with
locating runtime and forge bcoz every option is present in the app Nicely
done 👍.
