### ISSUE TITLE
[BUG] <mouse glitching>

### ISSUE THREAD

**Issue by Japperder** [PojavLauncherTeam/PojavLauncher#3302]
### Describe the bug

when i try to start the game or join a server the game just chrases
very few times it happens while i am in the game

1 only made it into the server 3 times but then it chrashes after like 5sec.
i use optifine with al the fast setting on

### Steps To Reproduce

```markdown
1. start pojav (crash)
2. joining world (crash)

```

### Expected Behavior

i expect it to not keep crashing

### Platform

```markdown
- Device model: chromebook
- CPU architecture: .
- Android version: .
- PojavLauncher version: newest
```

### Anything else?

it isn't really an error  chrash it just closes the game and goes back to the login screen

**Comment by Japperder** [comment]
so the mouse glitching is because of the lag
so anyone know how to fix this lag is already use optifine with fast settings and have a lag reducer on the server
my RAM is 1200MB

**Comment by GaucovyAero** [comment]
You haven't mentioned literally anything about any of your device specs, cpu architechture nor android version. Nor have you sent any logs. Nor have you actually mentioned what "newest" means. Ima disregard this until we get more information from you. Thanks

**Comment by Japperder** [comment]
CPU: Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
i don't think there are crash logs bcs the game doesn't report a crash it just closes
with newest i mean the app is up-to-date
for now i cant find the android version but i will try to find it

**Comment by REYASKANNAN** [comment]
I can't click any of the single player or multiplayer even I can't click quit game the mouse is working but couldn't click even I click the home button on mobile and clear on the minimize and again went to pohavlanchur multipletimes but still I won't work

But that problem in fabric 1.16.5 but I can use normal vinnila 1.16.5 I can click on 1.16.5 also I really need the fabric
Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…

**Comment by REYASKANNAN** [comment]
![Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…]()

**Comment by GaucovyAero** [comment]
You didn't send anything.
