### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Apaa21** [PojavLauncherTeam/PojavLauncher#3303]
### Describe the bug

![Screenshot_20220531-204854](https://user-images.githubusercontent.com/106435611/171177387-d34076b5-a6d3-43aa-81b8-33cbb01f6421.png)

### The log file and images/videos

![Uploading Screenshot_20220531-204854.png…]()

### Steps To Reproduce

```markdown
Can you fix this
```

### Expected Behavior

I need help

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Please fix this

**Comment by BUGAMING85677** [comment]
This version of pojavlauncher is bad downgrade pojavlauncher.

**Comment by BUGAMING85677** [comment]
Here is link https://pojavlauncher-minecraft-java-edition-for-android.en.uptodown.com/android/download/3943278

**Comment by Mathias-Boulay** [comment]
Fixed on the release of today
