### ISSUE TITLE
For Microsoft account

### ISSUE THREAD

**Issue by arkeen19** [PojavLauncherTeam/PojavLauncher#3304]
### Describe the bug

Microsoft gives an error when trying to open an account, what is the reason for this. At the same time, if we do not create an online account, we cannot establish a new version. It's a bit of an upside. If you figure this out the best mobile app is definitely pojavlauncher. Thanks. :) 

### The log file and images/videos

![Screenshot_20220531-174608](https://user-images.githubusercontent.com/106608083/171202458-9f198fa6-905f-4193-9b44-82f7f773bf75.jpg)

### Steps To Reproduce

```markdown
I get error when trying to create an online accountI get an error when trying to create an online account even though I have tried many times
```

### Expected Behavior

I want to open my Microsoft account, but I'm getting an error

### Platform

```markdown
- Device model: huawei Y7 prime 
- CPU architecture: aarch64
- Android version: 8.2
- PojavLauncher version: [Latest version || version 3.3.2.1_rel_20210206]
```

**Comment by GaucovyAero** [comment]
Hmm, buy Minecraft: Java Edition.

**Comment by Baldi627** [comment]
What if he already OWNS Minecraft Java Edition?

**Comment by GaucovyAero** [comment]
@Baldi627 the log does not lie
