### ISSUE TITLE
[BUG] Account Not Working

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3305]
### Describe the bug

My microsoft account is not working dont say migrate to mojang account please

### The log file and images/videos

![Screenshot_20220531-185920_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/99503027/171205905-a8c9e7ad-79f9-4d09-b37e-78c9b7b6df77.jpg)

### Steps To Reproduce

```markdown
1. START POJAV
2. LOGIN USING MICROSOFT ACCOUNT
```

### Expected Behavior

I Expect It To Work

### Platform

```markdown
- Device model: Samsung S6 Lite Tab
- CPU architecture: 64bits aarch64 64gb 4gb ram
- Android version: Android 12 One Ui 4.1
- PojavLauncher version: Latest Google Play Version
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
You have to migrate to Microsoft. Mojang has already disabled the use of Mojang accounts to play the game. Also, make sure you bought Minecraft: Java Edition for 23.95$ before trying to log into Pojav.

**Comment by ghost** [comment]
> You have to migrate to Microsoft. Mojang has already disabled the use of Mojang accounts to play the game. Also, make sure you bought Minecraft: Java Edition for 23.95$ before trying to log into Pojav.

I already bought account and its already migrated to microsoft

**Comment by GaucovyAero** [comment]
> > You have to migrate to Microsoft. Mojang has already disabled the use of Mojang accounts to play the game. Also, make sure you bought Minecraft: Java Edition for 23.95$ before trying to log into Pojav.
> 
> I already bought account and its already migrated to microsoft

Yeah, but it literally says that the Microsoft account that you logged in with into Pojav does not own Minecraft: Java Edition. You can't just log in with any account. Make sure you log in with the one you bought Minecraft: Java Edition on.

**Comment by OMARALTARAWNEH5** [comment]
Please back pojavlauncher to the old one like you can make local account you can access Minecraft and you can enter any version without making new folder like the old one please......my Microsoft account is not working

**Comment by Mathias-Boulay** [comment]
@ToxicGamingGithub prove you have the account then, by logging into the official minecraft website

**Comment by saiswar5516T** [comment]
Install old version of pojav launcher simple
use https://apkpure.com for it

**Comment by SharmaStudios** [comment]
> > You have to migrate to Microsoft. Mojang has already disabled the use of Mojang accounts to play the game. Also, make sure you bought Minecraft: Java Edition for 23.95$ before trying to log into Pojav.
> 
> I already bought account and its already migrated to microsoft

Warn:- Don't use pojav launcher directly

Fill your username not email fill it in the blanks also the password then click Microsoft login if dosent work 

Idk it worked for me

**Comment by ghost** [comment]
> @ToxicGamingGithub prove you have the account then, by logging into the official minecraft website

I tried it on tlauncher (pc emulator) it worked @Mathias-Boulay

**Comment by mchnjt** [comment]
> Please back pojavlauncher to the old one like you can make local account you can access Minecraft and you can enter any version without making new folder like the old one please......my Microsoft account is not working

bruh

**Comment by mchnjt** [comment]
> > @ToxicGamingGithub prove you have the account then, by logging into the official minecraft website
> 
> I tried it on tlauncher (pc emulator) it worked @Mathias-Boulay

bruh

**Comment by USMP-lancer** [comment]
i dont think he knows what tlauncher is

**Comment by Mathias-Boulay** [comment]
Use the official launcher to prove it, not a third party one
