### ISSUE TITLE
[F-Req] Support creating documents in documentsprovider

### ISSUE THREAD

**Issue by Muvkina** [PojavLauncherTeam/PojavLauncher#3307]
### Is this request related to a bug?

This is not related to a bug particularly except that on some phones the documentprovider is the only way to move files into the pojavdirectoey (Android/data doesn't work on some phones mine included)

### Describe the request.

I would like to see the documentsprovider(gamefolderprovider) support some of the other overrides such as createdocument, copy document, etc. Here is some implementation info on the android docs: https://developer.android.com/guide/topics/providers/create-document-provider

**Comment by Mathias-Boulay** [comment]
@Vixeliz 
Indeed operations were severely limited.
I added better file support which should be available on this action build. https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2437056420

**Comment by Muvkina** [comment]
Looks like a good start! It would still be nice to support copying and moving files eventually. The android development docs has a good start. Just have to handle copying folders and such. If you can use apache licensed code at all look at my latest pr on love-android for some implementation ideas for copyDocument override.

**Comment by Mathias-Boulay** [comment]
oh it is supported too in theory 🤔

**Comment by Muvkina** [comment]
> oh it is supported too in theory 🤔 

Weird I tested and it does work. I thought copyDocument was needed to implement copying support. Perhaps copyDocument allows you to define other behavior? I'm not sure

**Comment by Mathias-Boulay** [comment]
maybe it has a fallback where it just spams create each file or something 🤷

**Comment by Muvkina** [comment]
> maybe it has a fallback where it just spams create each file or something 🤷 

That could be it or maybe it's file manager dependant. Regardless feel free if you want to implement it to be safe and can use apache code to look at my latest pr on love-android. Regardless thanks for adding createDocument!

**Comment by Mathias-Boulay** [comment]
tested with the stock file manager on my end
I may create a library for apps to easily open full access to their files. (aka just a preconfigured documentProvider 😄 )

**Comment by Muvkina** [comment]
> tested with the stock file manager on my end
> I may create a library for apps to easily open full access to their files. (aka just a preconfigured documentProvider 😄 )
> 

That would be cool especially with all of the apps that have lost access to their files from scoped storage. More apps need to implement them 😤

**Comment by Mathias-Boulay** [comment]
True, I'll put this on my checklist of things to do.

**Comment by Mathias-Boulay** [comment]
I added a few things for the provider, maybe I'll finish it in a few weeks

**Comment by Mathias-Boulay** [comment]
@Vixeliz Do you know any file manager that uses the other functions we mentioned earlier ?
Else, it is going to be hard to test them

**Comment by Muvkina** [comment]
> @Vixeliz Do you know any file manager that uses the other functions we mentioned earlier ?
> Else, it is going to be hard to test them

Hmmm I'm not sure off hand you can't even use pojav in other file managers right now till it supports the. IS_CHILD_DOCUMENT flag and has the isChildDocument override.

**Comment by Mathias-Boulay** [comment]
and once I do that ?

**Comment by Muvkina** [comment]
> and once I do that ? 

I can try to find one but I think isChildDocument is a good start and maybe could be called good enough for now. It appears that's all termux does

**Comment by Muvkina** [comment]
Ah yikes I'm being slow, forgot you used the termux one

**Comment by Muvkina** [comment]
Honestly if createDocument is good enough for termux it's probably fine. I do recall one situation where copyDocument was useful which is in the system file manager. It makes it so you can define custom copy behavior that makes it so copying a file onto an existing one won't overwrite it(this was the main issue I ran into) but only that is such a little detail it's probably fine where it's at right now.

**Comment by Mathias-Boulay** [comment]
> copy behavior that makes it so copying a file onto an existing one won't overwrite it

if it relies on the create document, yeah it won't overwrite it, as the termux one by default adds parenthesis + a number

**Comment by Muvkina** [comment]
> > copy behavior that makes it so copying a file onto an existing one won't overwrite it
> 
> if it relies on the create document, yeah it won't overwrite it, as the termux one by default adds parenthesis + a number

I'm not sure whst it's doing internally but testing termux file provider files don't get the parenthesis if you copy them over an existing one so I think for that functionality you do need copyDocument. But again a minor issue
