### ISSUE TITLE
[BUG] Game Freezes after disconnecting from server

### ISSUE THREAD

**Issue by NotScareBat** [PojavLauncherTeam/PojavLauncher#3308]
### Describe the bug

Game freezes after disconnecting from a server.

### The log file and images/videos

https://linksharing.samsungcloud.com/rvkcEuX0tGIS

### Steps To Reproduce

```markdown
1.Start pojavlauncher 
2.play any version
3.join a server e.g pvplegacy.net
4.disconnect
_Game Freezes_
```

### Expected Behavior

I expect the game to continue normally 

### Platform

```markdown
- Device model: Samsung a10 
- CPU architecture: architecture 32
- Android version: 11
- PojavLauncher version: crocus-496-a41826a16-v3_openjdk
```

### Anything else?

•It's really annoying to have to restart the game just to change servers

**Comment by Mathias-Boulay** [comment]
yeah it is fixed on the current dev builds
