### ISSUE TITLE
Pojav launcher closes when i tab out

### ISSUE THREAD

**Issue by MerciGG** [PojavLauncherTeam/PojavLauncher#3309]
### Describe the bug

So i was playing pojav, i tab out to open discord and when i go to recents to tab back it its not there it just closes, this is the latest update btw

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Start pojav new update
2. Play idk
3. Tab out(press home or somethn)
4. Go to recents and pojav isnt there
```

### Expected Behavior

To not close, it dosent happen in older versions so ik its not my phone thats doing it, i cant switch to old versions cuz its force updating pojav

### Platform

```markdown
- Device model: Oppo a94
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

Fix pls

**Comment by Mathias-Boulay** [comment]
#3028 
Also, it depends of whatever is running in background
