### ISSUE TITLE
The cursor or button is unable to click

### ISSUE THREAD

**Issue by Alreynn** [PojavLauncherTeam/PojavLauncher#331]
I don't know how this happened everytime. My OS now supported Android 10 and my device is Oppo F9. Please fix this soon, this bug sometimes happens in the main menu so i cannot play and i need to Restart the Game. And it happens too in the Settings so i need to press back in the "Navigation Button"

**Comment by artdeell** [comment]
That was an issue, but i think it's fixed on one of the releases

вс, 27 сент. 2020 г., 06:14 KeyzGames <notifications@github.com>:

**Comment by RusJJ** [comment]
Yeah, that's fixed, but after applying settings it seems that in settings menu i cannot open anything. All i need to do: close it and open again.

**Comment by khanhduytran0** [comment]
It was Minecraft reloading to apply settings.

**Comment by khanhduytran0** [comment]
Or seems like cursor bug.
