### ISSUE TITLE
[F-Req] Lunar client 1.16.5 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#3310]
### Describe the request.

Of course this is off-topic. But I can't find the jar version of lunar client 1.16.5 maximum I found version 1.8. I want to ask people who know: is it possible to find and install lunar client version 1.16.5 in any way by pojavlauncher? I installed lunar client 1.16.5 on the notebook but the jar version of the client on the disk did not find similarly the lunar launcher itself downloads the necessary resources for the client. If this issue turns out to be unacceptable, I will close it

**Comment by NotAhackerforfun** [comment]
There is no cracked version available for 1.16.5 lunar right now that's the reason

**Comment by Hussaingame** [comment]
Bnkbxjkn

**Comment by Hussaingame** [comment]
Cigijjchhoghc

**Comment by Hussaingame** [comment]
Knihvvjvhcn

**Comment by Hussaingame** [comment]
Jbchnbb

**Comment by Hussaingame** [comment]
Pojavlauncher6

**Comment by Vikashmali123456789** [comment]
Teri ma ki chut

**Comment by 99999996** [comment]
Same

**Comment by mchnjt** [comment]
Please, **STOP ASKING FOR LUNAR CLIENT .JAR**.

We do not develop Lunar Client.

**Comment by YTGAMINGKH** [comment]
Som link download lunar clinet 1.16.5

**Comment by YTGAMINGKH** [comment]
> ### Is this request related to a bug?
> _No response_
> 
> ### Describe the request.
> Of course this is off-topic. But I can't find the jar version of lunar client 1.16.5 maximum I found version 1.8. I want to ask people who know: is it possible to find and install lunar client version 1.16.5 in any way by pojavlauncher? I installed lunar client 1.16.5 on the notebook but the jar version of the client on the disk did not find similarly the lunar launcher itself downloads the necessary resources for the client. If this issue turns out to be unacceptable, I will close it
> 
> ### Anything else?
> _No response_
