### ISSUE TITLE
Forge & Optifine Incompatibility.

### ISSUE THREAD

**Issue by wishforstars** [PojavLauncherTeam/PojavLauncher#3311]
### Describe the bug

When installing optifine into the mods folder of a forge installation 1.16.5 in pojav launcher V3 , it acts like the mod is not there and doesn't install it , however it used to function correctly before the recent update.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8818434/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install the latest Forge version.
2. Add Optifine to the mods folder.
```

### Expected Behavior

Optifine & Forge should function together correctly.

### Platform

```markdown
- Device model: 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest release
```

**Comment by miggythewriter** [comment]
Did you used optifabric?
