### ISSUE TITLE
Versions and OptiFine installation <Short description>

### ISSUE THREAD

**Issue by KnuterrYT** [PojavLauncherTeam/PojavLauncher#3312]
### Describe the bug

So when I try to go onto another update instead of the main update 1.18.2 it will crash and when I was on the latest version it was lagging really bad so I tried to install OptiFine but it will keeps saying something about latest.log when I'm talking about the versions like 1.8 or 1.12 or any of them it will crash saying something about latest log as well so please fix that I would rather go on be downgraded version

### The log file and images/videos

It says latestlog.txt
Idk what rest said.

### Steps To Reproduce

```markdown
When I start the app then it was updated when I had my other tablet when I was updated it wasn't really well so I didn't want to update and it's still updated anyways that's when it started
```

### Expected Behavior

I just want the game to launch and it won't

### Platform

```markdown
- Device model:Samsung Tab a
- CPU architecture:idk 
- Android version:11 
- PojavLauncher version: latest version
```

### Anything else?

Fix offline account

**Comment by GaucovyAero** [comment]
Check your CPU architecture. Don't use your ARM32 device for Pojav for the time being. There is an issue with unpack200

**Comment by Mathias-Boulay** [comment]
unpacker bug fixed, check google play store for an update.
oh, and buy minecraft
