### ISSUE TITLE
[BUG] Shift is always active

### ISSUE THREAD

**Issue by GerritJand** [PojavLauncherTeam/PojavLauncher#3313]
### Describe the bug

When i walk and when i am in a chest. The shift button is always active.

### The log file and images/videos

-

### Steps To Reproduce

```markdown
1. Start the pojav launcher.
2. Open your game (1.12.2)
3. Join or map.
4. Go to a chest, or walk.
5. You see than, the shift button is always active.
```

### Expected Behavior

Please fix this bug!

### Platform

```markdown
- Device model: Chromebook
- CPU architecture: Intel
- Android version: ChromeOS
- PojavLauncher version: Lasted
```

**Comment by GaucovyAero** [comment]
Absolutely no idea, since you haven't told us any information. Exact model of chromebook, exact Pojav build (for example, crocus-590). Have you tried pressing the shift button, anything? Also no provided latestlog.txt.

**Comment by swarties** [comment]
It also happens to me on 1.8.9 on an android tablet on the latest version

**Comment by tigerbrocode** [comment]
Fellow nine year old did you try clicking  the shift button again

**Comment by NotAhackerforfun** [comment]
This is still happen ing to me

**Comment by keminawab** [comment]
Happens to me too
-1.8.9 and Latest version.

**Comment by GaucovyAero** [comment]
If you want to actually resolve this issue (because it's a rather difficult one to fix), you will have to contact us on our official PojavLauncher discord server. You will also recieve help faster.

**Comment by Mathias-Boulay** [comment]
This issue has been addressed a few commits ago on dev builds
