### ISSUE TITLE
[BUG] <Can't press menu button on Minecraft fabric>

### ISSUE THREAD

**Issue by SkulZOnTheYT** [PojavLauncherTeam/PojavLauncher#3314]
### Describe the bug

Why am I installing fabric, and how come I can't press the menu button? Even though in Minecraft forge everything is fine, and there are no bugs at all. 

### The log file and images/videos

I don't have pictures or videos, because when I tried to update, what happened I couldn't play Pojav Laucher, because I needed a premium account to play it :(

### Steps To Reproduce

```markdown
1. I open pojav launcher.
2. I'm bored with Minecraft forge and I'm trying to use fabric by downloading it.
3. I installed it and downloaded the required assets.
4. Having already downloaded the assets, I immediately started the Minecraft fabric.
5. that's when the loading of Minecraft forge has finished, the bug occurred.
6. I tried pressing the menu button but it didn't work, pressing the menu button using the default mouse didn't work, and I couldn't use a gaming mouse either.
```

### Expected Behavior

Hopefully this bug is answered and resolved, because this bug is really troublesome.

### Platform

```markdown
- Device model: Realme C12 3/32GB
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: [Before This Update | v3_openjdk]
```

### Anything else?

not only that from me

**Comment by miggythewriter** [comment]
I had the same problem in GitHub builds but I'm able to use forge in the new playstore version

**Comment by GaucovyAero** [comment]
Everything is working currently. You just have to buy Minecraft, of course. There is a workaround for this, but we won't tell you.

**Comment by MrVSnim** [comment]
I have the same problem what to do?

**Comment by MrVSnim** [comment]
I have the same problem what to do?
