### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by MhMukut** [PojavLauncherTeam/PojavLauncher#3315]
### Describe the bug

Game exited with code 1

### The log file and images/videos

![Screenshot_2022-06-02-19-39-14-085_net kdt pojavlaunch](https://user-images.githubusercontent.com/95852675/171651153-db20e467-9c8b-4e99-9777-6382222aecb8.jpg)

--------- beggining with launcher debug
Info: Launcher version: dahlia-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18
--------- beginning of system
--------- beginning of crash

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2240
Added custom env: POJAV_NATIVEDIR=/data/app/~~ArHdXBhQRTfylRRB14jbXg==/net.kdt.pojavlaunch-HsNnTpFkiPQww8r-DQvuyQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
--------- beginning of main

Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~ArHdXBhQRTfylRRB14jbXg==/net.kdt.pojavlaunch-HsNnTpFkiPQww8r-DQvuyQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
I/LIBGL   (27519): Initialising gl4es
I/LIBGL   (27519): v1.1.4 built on May 28 2022 20:23:20
I/LIBGL   (27519): Using GLES 2.0 backend

I/LIBGL   (27519): loaded: libGLESv2.so
I/LIBGL   (27519): loaded: libEGL.so
I/LIBGL   (27519): Using GLES 2.0 backend

I/LIBGL   (27519): Hardware Full NPOT detected and used
I/LIBGL   (27519): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (27519): FBO are in core, and so used
I/LIBGL   (27519): PointSprite are in core, and so used
I/LIBGL   (27519): CubeMap are in core, and so used
I/LIBGL   (27519): BlendColor is in core, and so used

I/LIBGL   (27519): Blend Substract is in core, and so used
I/LIBGL   (27519): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (27519): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (27519): Extension GL_OES_mapbuffer  detected
I/LIBGL   (27519): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (27519): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (27519): Extension GL_OES_depth24  detected and used
I/LIBGL   (27519): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (27519): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (27519): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (27519): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (27519): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (27519): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (27519): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (27519): high precision float in
 fragment shader available and used
I/LIBGL   (27519): Max vertex attrib: 16
I/LIBGL   (27519): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (27519): Max texture size: 8192
I/LIBGL   (27519): Max Varying Vector: 31
I/LIBGL   (27519): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (27519): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (27519): Max Anisotropic filtering: 16
I/LIBGL   (27519): Hardware vendor is ARM
I/LIBGL   (27519): GLSL 300 es supported
I/LIBGL   (27519): GLSL 310 es supported and used
I/LIBGL   (27519): GLSL 320 es supported

I/LIBGL   (27519): Max Color Attachments: 4 / Draw buffers: 4
I/LIBGL   (27519): sRGB surface supported
I/LIBGL   (27519): EGLImage to Texture2D supported
I/LIBGL   (27519): EGLImage to RenderBuffer supported

I/LIBGL   (27519): ignore MipMap
I/LIBGL   (27519): Targeting OpenGL 2.1
I/LIBGL   (27519): No hack in shader converter to define overloaded function with int
I/LIBGL   (27519): NPOT texture handled in hardware
I/LIBGL   (27519): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (27519): try to use VBO
I/LIBGL   (27519): glXMakeCurrent FBO workaround enabled

I/LIBGL   (27519): FBO workaround for using binded texture enabled
I/LIBGL   (27519): glX Will try to recycle EGL Surface
I/LIBGL   (27519): Current folder is:/
I/jrelog  (27519): dlopen libgl4es_114.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (27519): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success

I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (27519): dlopen /data
/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (27519): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success

I/jrelog  (27519): dlopen /data/app/~~ArHdXBhQRTfylRRB14jbXg==/net.kdt.pojavlaunch-HsNnTpFkiPQww8r-DQvuyQ==/lib/arm64/libopenal.so success

I/jrelog  (27519): Done processing args

I/jrelog  (27519): Found JLI lib
I/jrelog  (27519): Calling JLI_Launch

OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
ERROR StatusLogger Reconfiguration failed: No configuration found for '76ed5528' at 'null' in 'null'

[WARNING:spdy_session.cc(3541)] Received HEADERS for invalid stream 11
13:39:36.375 [main] ERROR LaunchWrapper - Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:187) ~[launchwrapper-of-2.3.jar:2.3]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0-internal]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:155) [launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.3.jar:2.3]
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0-internal]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178) ~[launchwrapper-of-2.3.jar:2.3]
	... 6 more
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7221faa56c)
process killed with signal 6 code 0xffffffff addr 0x28b700006b7f
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

--------- beginning of crash
--------- beginning of main

### Steps To Reproduce

```markdown
1. Start the game
2. Try to load 1.18 optifine
3. Game crashed showing a message 'Game exited with code 1
```

### Expected Behavior

I expected game to launch

### Platform

```markdown
- Device model: Redmi 10X 4G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Dahlia V3 openjdk
```

### Anything else?

Any solution for this new update or should I stay at previous version?

**Comment by GaucovyAero** [comment]
Why did you use Java 8 with 1.18?

**Comment by MhMukut** [comment]
> Why did you use Java 8 with 1.18?

Update said that this release has java 17 built-in 
So I thought it has java 17 enabled & I didn’t recheck it. ![Screenshot_2022-06-02-20-52-03-835_net.kdt.pojavlaunch.png](https://user-images.githubusercontent.com/95852675/171657669-c92ab076-19f1-40cc-be65-d688aa157bcf.png)

**Comment by MhMukut** [comment]
> Why did you use Java 8 with 1.18?

Should I retry with java 17?

**Comment by GaucovyAero** [comment]
> > Why did you use Java 8 with 1.18?
> 
> Should I retry with java 17?

yes

**Comment by MhMukut** [comment]
> > > Why did you use Java 8 with 1.18?
> > 
> > Should I retry with java 17?
> 
> yes

It did work. Thanks a lot bro.
