### ISSUE TITLE
[BUG] 1.12.2 crash with mods

### ISSUE THREAD

**Issue by Supertacoz** [PojavLauncherTeam/PojavLauncher#3317]
### Describe the bug

when attempting to launch with these three mods (controllable, phosphor, and pixelmon. there are likely more mods, but these are the only ones I have tested) (both together and/or separately) the game attempts to load, then an error message shows up saying game exited with error code 1.

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: dahlia-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.12.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2320
Added custom env: POJAV_NATIVEDIR=/data/app/~~P1fKxaaXRoJF3paAVWXz3g==/net.kdt.pojavlaunch-BNtzJ-bQ_-4CSad4Kyv7Ow==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~P1fKxaaXRoJF3paAVWXz3g==/net.kdt.pojavlaunch-BNtzJ-bQ_-4CSad4Kyv7Ow==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
--------- beginning of main

I/LIBGL   (16074): Initialising gl4es
I/LIBGL   (16074): v1.1.4 built on May 28 2022 20:23:20
I/LIBGL   (16074): Using GLES 2.0 backend
I/LIBGL   (16074): loaded: libGLESv2.so

I/LIBGL   (16074): loaded: libEGL.so
I/LIBGL   (16074): Using GLES 2.0 backend
I/LIBGL   (16074): FBO are in core, and so used
I/LIBGL   (16074): PointSprite are in core, and so used
I/LIBGL   (16074): CubeMap are in core, and so used
I/LIBGL   (16074): BlendColor is in core, and so used
I/LIBGL   (16074): Blend Substract is in core, and so used
I/LIBGL   (16074): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (16074): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (16074): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (16074): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (16074): Extension GL_OES_depth24  detected and used
I/LIBGL   (16074): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (16074): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (16074): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (16074): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (16074): Extension
 GL_OES_texture_float  detected and used
I/LIBGL   (16074): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (16074): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (16074): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (16074): high precision float in fragment shader available and used
I/LIBGL   (16074): Max vertex attrib: 32
I/LIBGL   (16074): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (16074): Max texture size: 16384
I/LIBGL   (16074): Max Varying Vector: 31
I/LIBGL   (16074): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (16074): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (16074): Max Anisotropic filtering: 16
I/LIBGL   (16074): Hardware vendor is Qualcomm
I/LIBGL   (16074): GLSL 300 es supported
I/LIBGL   (16074): GLSL 310 es supported and used
I/LIBGL   (16074): GLSL 320 es supported
I/LIBGL   (16074): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (16074): 
sRGB surface supported
I/LIBGL   (16074): EGLImage to Texture2D supported
I/LIBGL   (16074): EGLImage to RenderBuffer supported
I/LIBGL   (16074): ignore MipMap
I/LIBGL   (16074): Targeting OpenGL 2.1
I/LIBGL   (16074): No hack in shader converter to define overloaded function with int
I/LIBGL   (16074): NPOT texture handled in hardware

I/LIBGL   (16074): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (16074): try to use VBO
I/LIBGL   (16074): glX Will try to recycle EGL Surface
I/LIBGL   (16074): Current folder is:/
I/jrelog  (16074): dlopen libgl4es_114.so success

I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (16074): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success

I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success

I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (16074): dlopen /dat
a/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (16074): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (16074): dlopen /data/app/~~P1fKxaaXRoJF3paAVWXz3g==/net.kdt.pojavlaunch-BNtzJ-bQ_-4CSad4Kyv7Ow==/lib/arm64/libopenal.so success

I/jrelog  (16074): Done processing args

I/jrelog  (16074): Found JLI lib
I/jrelog  (16074): Calling JLI_Launch

  <log4j:Event logger="LaunchWrapper" timestamp="1654210988865" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1654210988996" level="INFO" thread="main">
    <log4j:Message><![CDATA[Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1654210988996" level="INFO" thread="main">
    <log4j:Message><![CDATA[Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FML" timestamp="1654210989029" level="INFO" thread="main">
    <log4j:Message><![CDATA[Forge Mod Loader version 14.23.5.2859 for Minecraft 1.12.2 loading]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FML" timestamp="1654210989030" level="INFO" thread="main">
    <log4j:Message><![CDATA[Java is OpenJDK 64-Bit Server VM, version 1.8.0-internal, running on Linux:aarch64:Android-12, installed at /data/user/0/net.kdt.pojavlaunch/runtimes/Internal]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FML" timestamp="1654210989085" level="ERROR" thread="main">
    <log4j:Message><![CDATA[Contained Dep is not in the jar: ForgeClientResetPacket-0.0.4.jar]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1654210989086" level="ERROR" thread="main">
    <log4j:Message><![CDATA[Unable to launch]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42)
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: Invalid contained dep, Missing from jar: ForgeClientResetPacket-0.0.4.jar
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:251)
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.extractPacked(LibraryManager.java:203)
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.cleanDirectory(LibraryManager.java:169)
	at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:97)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:106)
	... 5 more
]]></log4j:Throwable>
  </log4j:Event>
Exception in thread "main" 
  <log4j:Event logger="STDERR" timestamp="1654210989094" level="INFO" thread="main">
    <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="STDERR" timestamp="1654210989094" level="INFO" thread="main">
    <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="STDERR" timestamp="1654210989094" level="INFO" thread="main">
    <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="STDERR" timestamp="1654210989095" level="INFO" thread="main">
    <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="STDERR" timestamp="1654210989095" level="INFO" thread="main">
    <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="STDERR" timestamp="1654210989095" level="INFO" thread="main">
    <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="STDERR" timestamp="1654210989095" level="INFO" thread="main">
    <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)]]></log4j:Message>
  </log4j:Event>
Java Exit code: 1
I/jrelog  (16074): Going to free args
I/jrelog  (16074): Free done

### Steps To Reproduce

```markdown
1. start pojave launcher with forge 1.12.2 installed, and pixelmon, controllable, and phosphor (or only one of those) 
2. attempt to start the game.
```

### Expected Behavior

expected: game launches with pixelmon, controllable, and phosphor.

### Platform

```markdown
- Device model: Poco f3
- CPU architecture: ARM
- Android version: 12
- PojavLauncher version: latest google play store version as of june 2nd, 2022
```

### Anything else?

Note: I also have another problem in the menus of pojavelauncher (not in minecraft itself) where text that doesn't have an image attached to it is inverted.

**Comment by tigerbrocode** [comment]
Pixelmon works for 1.12.2
Phosphor does not have a 1.12 version (this might be the cause)
But idk about controllable it may also be the cause

Anyways try disabling phosphor and try if it works

**Comment by Dinnerbone6930** [comment]
How do you fix error t
419? 
![Uploading Screenshot_2022-06-03-15-17-34-93_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by Supertacoz** [comment]
phosphor does have a 1.12.2 forge version, and i have tried it without phosphor
