### ISSUE TITLE
[I Open using local and The letters are reversed]

### ISSUE THREAD

**Issue by PHDavidYT** [PojavLauncherTeam/PojavLauncher#3318]
### Describe the bug

I can't sign in to my microsoft account even though I have a microsoft account on my cellphone and when I log in to pojavlauncher I get an error

### The log file and images/videos

Plsss I need good game 

### Steps To Reproduce

```markdown
the letters are upside down and it's hard to read because the letters are upside down
```

### Expected Behavior

I hope the shader works on my cellphone 
 

Like this
![images](https://user-images.githubusercontent.com/106820281/171902692-6c7b9d58-08c8-47de-96d3-2f6cc91690ae.jpeg)

### Platform

```markdown
- Device model: Samsung j7 pro 
- CPU architecture:8x ARM Cortex-A53 @ 1.59 GHz
- Android version:9
- PojavLauncher version:[Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by Mathias-Boulay** [comment]
Fixed in the latest hotfix release, today.
Check for an update
