### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by KostyanSigaev** [PojavLauncherTeam/PojavLauncher#332]
When I click Play, a gray screen starts up, the controls appear, and nothing else happens ...
I installed all x86 files for my Intel Atom z2580 processor
![Screenshot_20200927-163804](https://user-images.githubusercontent.com/71372830/94366391-99ec3300-00e0-11eb-8165-b1cb432e3a94.png)

**Comment by khanhduytran0** [comment]
Minecraft will not start instantly. So you need wait ~5 minutes

**Comment by khanhduytran0** [comment]
If still nothing, send latestlog txt here

**Comment by KostyanSigaev** [comment]
OK

**Comment by KostyanSigaev** [comment]
Almost 30 minutes have passed since launch, but nothing has changed ...

**Comment by KostyanSigaev** [comment]
Log here 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5288453/latestlog.txt)

**Comment by khanhduytran0** [comment]
So you installed an incompatible java runtime, are you sure on x86?

**Comment by KostyanSigaev** [comment]
My Intel Atom z2580 processor on x86 architecture

**Comment by khanhduytran0** [comment]
Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/276392680

**Comment by khanhduytran0** [comment]
Try set max ram to 750mb

**Comment by KostyanSigaev** [comment]
It still didn't help, just endless loading ...

**Comment by bghyt** [comment]
With 1.16+ I can wait over 15 mins just for it to start.

**Comment by KostyanSigaev** [comment]
1.13, 1.14, 1.15, 1.16 and the rest of the versions do not start at all ... I tried to leave the phone at night with Minecraft running, but nothing loaded ...

**Comment by khanhduytran0** [comment]
Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/279450870
Then latestlog.txt will have some more logs about loading Java Runtime when launch.

**Comment by KostyanSigaev** [comment]
Judging by the log, the launcher thinks that my arm processor, not x86, does not want to work with the runtime ... Try removing the arm libraries from the launcher, it will be a separate version for x86, maybe this will help ... I gave this advice to the developer serious sam port on android, and it helped with the launch on many devices
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5304267/latestlog.txt)

**Comment by khanhduytran0** [comment]
Does your device have libhoudini installed?

**Comment by khanhduytran0** [comment]
You may try arm lib (yeah that's weird to) to see if it work...

**Comment by KostyanSigaev** [comment]
Yes, libhoudini.so installed
![Uploading Screenshot_20201001-125816.png…]()

**Comment by KostyanSigaev** [comment]
I installed the latest version of launcher but it sees my x86 cpu as ARM. I recorded a screencast of a new problem: https://drive.google.com/file/d/1fbUw6ij2BmHc1O92skycyeSYTMVkg28X/view?usp=drivesdk

**Comment by khanhduytran0** [comment]
Could you disable `native bridge` (libhoudini) and try again?

**Comment by KostyanSigaev** [comment]
How can I do this?

**Comment by artdeell** [comment]
I guess this setting is android-x86 only, so... Maybe try to remove ARM
binaries with apk editor?

вс, 11 окт. 2020 г., 18:09 KostyanSigaev <notifications@github.com>:

**Comment by KostyanSigaev** [comment]
Apk editors are many, how exactly do I need to do this? APK Editor for android or APK Editor Studio for pc?

**Comment by artdeell** [comment]
Use APK Editor for Android

вт, 13 окт. 2020 г., 13:55 KostyanSigaev <notifications@github.com>:

**Comment by KostyanSigaev** [comment]
I have tried many different versions of apk editors, but none of them have the ability to cut files. Can you provide the editor you want?
