### ISSUE TITLE
Application/game error code 1 exception 

### ISSUE THREAD

**Issue by Killer105** [PojavLauncherTeam/PojavLauncher#3320]
### Describe the bug

I Install mods and when I run it in forge it says error code 1 exception, plz help and tell how to fix.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8837029/latestlog.txt)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: vivo z1x 6/64gb
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest
```

**Comment by Mathias-Boulay** [comment]
Don't use virgl 🤔
