### ISSUE TITLE
[BUG] My Controller Is Not Working

### ISSUE THREAD

**Issue by JacobWEAST** [PojavLauncherTeam/PojavLauncher#3321]
### Describe the bug

Example: u can't jump u can't open inventory U can't Eat It Used To Work In The New Update I Doesn't Please Fix This

Thanks U For Ur Support

~user

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

Not Working My Controller

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Nothing Else

**Comment by Mathias-Boulay** [comment]
Sadly it means your device is not reporting the controller as such
