### ISSUE TITLE
[BUG] <crash on 1.7.10 with code 1>

### ISSUE THREAD

**Issue by Nikit2345** [PojavLauncherTeam/PojavLauncher#3323]
### Describe the bug

Application exited with code 1

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: dahlia-8-f527e8a14-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.7.10
--------- beginning of system

--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1546
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-AaVElDjWUzACCXWi2HB0CA==/lib/arm
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-AaVElDjWUzACCXWi2HB0CA==/lib/arm
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
I/LIBGL   (31940): Initialising gl4es
I/LIBGL   (31940): v1.1.4 built on May 28 2022 20:23:51
I/LIBGL   (31940): Using GLES 2.0 backend

I/LIBGL   (31940): loaded: libGLESv2.so
I/LIBGL   (31940): loaded: libEGL.so
I/LIBGL   (31940): Using GLES 2.0 backend

I/LIBGL   (31940): Hardware Full NPOT detected and used
I/LIBGL   (31940): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (31940): Extension GL_EXT_draw_buffers  detected and used
I/LIBGL   (31940): FBO are in core, and so used
I/LIBGL   (31940): PointSprite are in core, and so used
I/LIBGL   (31940): CubeMap are in core, and so used
I/LIBGL   (31940): BlendColor is in core, and so used
I/LIBGL   (31940): Blend Substract is in core, and so used
I/LIBGL   (31940): Blend Function and Equation Separation is in core, and so used

I/LIBGL   (31940): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (31940): Extension GL_OES_mapbuffer  detected
I/LIBGL   (31940): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (31940): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (31940): Extension GL_OES_depth24  detected and used
I/LIBGL   (31940): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (31940): Extension GL_EXT_multi_draw_arrays  detected
I/LIBGL   (31940): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (31940): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (31940): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (31940): Extension GL_EXT_texture_rg  detected and used

I/LIBGL   (31940): Extension GL_OES_texture_float  detected and used
I/LIBGL   (31940): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (31940): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (31940): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (31940): Extension GL_OES_fragment_precision_high  detected and used
I/LIBGL   (31940): Extension GL_EXT_shader_texture_lod detected and used

I/LIBGL   (31940): Max vertex attrib: 16
I/LIBGL   (31940): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (31940): Max texture size: 4096
I/LIBGL   (31940): Max Varying Vector: 15
I/LIBGL   (31940): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (31940): Hardware vendor is Imagination Technologies

I/LIBGL   (31940): GLSL 300 es supported
I/LIBGL   (31940): GLSL 310 es supported and used
I/LIBGL   (31940): GLSL 320 es supported
I/LIBGL   (31940): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (31940): sRGB surface supported
I/LIBGL   (31940): EGLImage to Texture2D supported
I/LIBGL   (31940): EGLImage to RenderBuffer supported

I/LIBGL   (31940): ignore MipMap
I/LIBGL   (31940): Targeting OpenGL 2.1
I/LIBGL   (31940): No hack in shader converter to define overloaded function with int
I/LIBGL   (31940): NPOT texture handled in hardware
I/LIBGL   (31940): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (31940): try to use VBO
I/LIBGL   (31940): FBO workaround for using binded texture enabled
I/LIBGL   (31940): glX Will try to recycle EGL Surface
I/LIBGL   (31940): Current folder is:/
I/jrelog  (31940): dlopen libgl4es_114.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success

I/jrelog  (31940): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmlib_image.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsunec.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libhprof.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pkcs11.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libzip.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjawt.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjaas_unix.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_xawt.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjdwp.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsig.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsctp.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/liblcms.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libdt_socket.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjpeg.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libunpack.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libtinyiconv.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsdt.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsound.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2gss.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmanagement.so success

I/jrelog  (31940): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pcsc.so success

I/jrelog  (31940): dlopen /data/app/net.kdt.pojavlaunch-AaVElDjWUzACCXWi2HB0CA==/lib/arm/libopenal.so success

I/jrelog  (31940): Done processing args

I/jrelog  (31940): Found JLI lib
I/jrelog  (31940): Calling JLI_Launch

Error: A JNI error has occurred, please check your installation and try again

Exception in thread "main" 
java.lang.NoClassDefFoundError: joptsimple/OptionSpec

	at java.lang.Class.getDeclaredMethods0(Native Method)

	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)

	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec

	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	... 7 more
Java Exit code: 1
I/jrelog  (31940): Going to free args
I/jrelog  (31940): Free done

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start 1.7.10
3. Get crash code 1
```

### Expected Behavior

I expect 1.7.10 to launch

### Platform

```markdown
- Device model: redmi 9a
- CPU architecture: aarch64 (32 bit mode)
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by Mathias-Boulay** [comment]
Vanilla or forge ?

**Comment by Nikit2345** [comment]
> Vanilla or forge ?

Vanilla

**Comment by Mathias-Boulay** [comment]
We didn't manage to recreate the issue, somehow

**Comment by AGENTISNUM1** [comment]
yea, looks like its the same for me, i made an issue on the same thing

**Comment by GaucovyAero** [comment]
`java.lang.NoClassDefFoundError: joptsimple/OptionSpec`

you are missing a libary, delete the `.minecraft/libraries` folder and try again.
