### ISSUE TITLE
[BUG] No obvious way to edit/delete existing profiles

### ISSUE THREAD

**Issue by delipunch** [PojavLauncherTeam/PojavLauncher#3324]
### Describe the bug

The seems to be no way to edit (or even delete) already existing profiles from within the launcher. Long pressing and/or double pressing profiles does not bring up any edit or deletion menu.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8838791/latestlog.txt)

### Steps To Reproduce

```markdown
N/A - Report is about missing rather than erroneous functionality.
```

### Expected Behavior

I expect a way to edit and delete profiles, in addition to creating them.

### Platform

```markdown
- Device model: Nubia Red Magic 5G, Samsung Galaxy Note 10+
- CPU architecture: aarch64, aarch64
- Android version: 11, 12
- PojavLauncher version: Google Play, Latest (June 3rd, 2022 update)
```

**Comment by artdeell** [comment]
Hold the profile selector

**Comment by delipunch** [comment]
That did the trick. I was long pressing on the profile in the pop-up list of profiles, not the selector.
