### ISSUE TITLE
ERRO código 1 não consigo entrar no jogo

### ISSUE THREAD

**Issue by NISSINNNNN** [PojavLauncherTeam/PojavLauncher#3325]
### Describe the bug

Depois dessa atualização quando entro para jogar aparace o erro código 1 e o app fecha antes conseguia entrar normalmente !

### The log file and images/videos

..

### Steps To Reproduce

```markdown
Entro no pojavlaucher e seleciono o lunar client quando clico em jogar ele inicia e logo apos aparece aplicativo jogo fechou com código 1
```

### Expected Behavior

Espero que consigam me diser o que e pois gosto muito de jogar minecraft

### Platform

```markdown
- Device model: SM-A315G (a31nndx)
- CPU architecture: ARM Cortex-A75
- Android version: 11
- PojavLauncher version: : [Última versão || versão 3.3.1.1_rel_20210206 ]
```

### Anything else?

Acho que pode ser por conta que nessa atualização mudou os renderizadores !

**Comment by Mathias-Boulay** [comment]
unofficial client, and you claim to use a really old release 🤔

**Comment by NISSINNNNN** [comment]
> cliente não oficial, e você afirma usar uma versão muito antiga🤔

Sim mais com outros cliente e versoes acontece a mesma coisa

**Comment by Mathias-Boulay** [comment]
We still need the latestlog.txt file
