### ISSUE TITLE
[BUG] Game Crashing on Startup

### ISSUE THREAD

**Issue by Bunny6968** [PojavLauncherTeam/PojavLauncher#3327]
### Describe the bug

Whenever I try to launch game with my device it crashes dosent even loads up the MOJANG screen even with Online Account / Offline Account....

### The log file and images/videos

![Screenshot_20220605-131547_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/106491296/172040946-6e5fb0a0-a9e6-474b-83e2-1646805f9297.jpg)
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8839519/latestcrash.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8839520/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Login Into your account 
3.Launch Any client or Version
4.Crahsed
```

### Expected Behavior

Expected Game to launch

### Platform

```markdown
- Device model : Samsung J7 NxT
- CPU architecture: aarch32 
- Android version: 9
- PojavLauncher version: latest
```

### Anything else?

#3287 is still not fixed

My Game details :-
Client Name : CmpackClient 1.8.8
Version : 1.8.9
Launcher : PojavLauncher

**Comment by Mathias-Boulay** [comment]
Can you reproduce the issue with a vanilla version ?

**Comment by Mathias-Boulay** [comment]
Also, #3287 is fixed, as language selection is properly handled now.
Still requires you to select the appropriate language

**Comment by Wadahxd** [comment]
I have the same bug with 1.18.2 forge how do i fix it ????

**Comment by GaucovyAero** [comment]
If you want to actually resolve this issue (because it's a rather difficult one to fix), you will have to contact us on our official PojavLauncher discord server. You will also recieve help faster.
