### ISSUE TITLE
[F-Req] PUHLEAZE let us make folder in the mods folder and have the mod loaders actually load them.

### ISSUE THREAD

**Issue by yum13241** [PojavLauncherTeam/PojavLauncher#3328]
### Is this request related to a bug?

We cannot have say, 1.16.5 fabric with mods, and say 1.18.2 fabric with mods, cuz they use the same folder, mods.

Sure you could just lump them into one folder, but that's not feasible.

### Describe the request.

inside the "mods" dir.

1.16.5
--example-1.16.5.jar

1.18.2
--example.1.18.2.jar

And it actually loading, and without the wrong version of the wrong mods.

### Anything else?

This helps with organization. Also, I don't want to change my .minecraft to smth else for every instance.

**Comment by yum13241** [comment]
Heck, even better, The Holy Profile Separation of MultiMC...

**Comment by Mathias-Boulay** [comment]
You can change the game directory per profile on the latest release. So you can separate both versions of fabric 👍

**Comment by yum13241** [comment]
The problem is you cant edit the fabric instance. The only other way is to change the directory in the fabric installer which is a pain.
