### ISSUE TITLE
[F-Req] Native controller support.

### ISSUE THREAD

**Issue by yum13241** [PojavLauncherTeam/PojavLauncher#3330]
### Is this request related to a bug?

The fact that controller mods don't usually work means that PojavLauncher should do something.

### Describe the request.

A way to make buttons on the controller do things in Minecraft, without the use of mods.

### Anything else?

This would be nice if you wanted to play say, an old version or if you are jarmodding.

**Comment by Mathias-Boulay** [comment]
If your device maps gamepad keys adequately, no mods should be necessary.

**Comment by yum13241** [comment]
The problem is that I for the life of me can't find an app that lets me map my controller buttons and sticks to keys.
