### ISSUE TITLE
[BUG] Right Click With External Mouse = ESC

### ISSUE THREAD

**Issue by VlipperGZ** [PojavLauncherTeam/PojavLauncher#3331]
### Describe the bug

I use an external mouse and keyboard to play Pojavlauncher but there is a bug that makes right click the ESC button sometimes it happens sometimes not but it's annoying

### The log file and images/videos

> 

### Steps To Reproduce

```markdown
1.Connecting USB
2.Play Pojavlauncher
3.When in the game you want to make something from the crafting table, the right click button instead becomes the ESC button
```

### Expected Behavior

Hopefully it's fixed

### Platform

```markdown
- Device model: VIVO Y12i
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release (Render Holy)
```

### Anything else?

Fix this

**Comment by Mathias-Boulay** [comment]
I will need to gather additional data about this, as your device is faulty in this case.
Contact me via the official pojav launcher discord

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
