### ISSUE TITLE
[BUG] <No Textures In Fabric 1.16.1>

### ISSUE THREAD

**Issue by RedbedMCPojav** [PojavLauncherTeam/PojavLauncher#3332]
### Describe the bug

No textures showing up in Fabric 1.16.1. I'm using a custom build of Sodium for Speedrunning. I'm also using play store version.

### The log file and images/videos

![Screenshot_2022-06-05-17-00-56-139_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/172043308-8ff6f241-4e61-48fc-8de0-da8827995a50.jpg)

### Steps To Reproduce

```markdown
1. Start Up PojavLauncher
2. Click play on Fabric 1.16.1
3. Open a world
4. No Textures

If you need the custom version of sodium and other mods here you go
Sodium
https://github.com/mrmangohands/sodium-fabric/releases/tag/mc1.16.1-0.2.0%2Bbuild.17
Phosphor
https://github.com/mrmangohands/phosphor-fabric/releases/tag/mc1.16.1-0.7.2
Lithium
https://github.com/mrmangohands/lithium-fabric/releases/tag/mc1.16.1-0.6.6
```

### Expected Behavior

I expected the textures to work but it didn't

### Platform

```markdown
- Device model: POCO X3 GT 8/256G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: PojavLauncher PlayStore version
```

**Comment by Mathias-Boulay** [comment]
Sadly sodium is not supported with the holy renderer for now

**Comment by RedbedMCPojav** [comment]
Oh ok thanks for clarifying

**Comment by Mathias-Boulay** [comment]
#1948
