### ISSUE TITLE
[BUG] Crash when Open Recent apps

### ISSUE THREAD

**Issue by NotScareBat** [PojavLauncherTeam/PojavLauncher#3333]
### Describe the bug

Pressing the home/recent apps button while playing/while the game is loading gives error:
-Application/game exited with code 1

### The log file and images/videos

No log produced

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Play any version
3. Press recent apps button 
4. Click pojavlauncher tab
-Starts loading then crashes 
-Immediate crash
```

### Expected Behavior

•I expect the game to continue normally

### Platform

```markdown
- Device model: Samsung a10s/a10
- CPU architecture: architecture 32
- Android version: 11
- PojavLauncher version: dahlia-17-f1652e8c7-
```

### Anything else?

•Only started happens in latest versions 
•Older versions run just fine

**Comment by Mathias-Boulay** [comment]
dahlia-17 doesn't exist on mainline. 
I don't know where the fuck you got this version

**Comment by Mathias-Boulay** [comment]
Actually, just checked. Don't use this build, use the ones from mainline
