### ISSUE TITLE
[BUG] <Screen Bug In World>

### ISSUE THREAD

**Issue by DanelOfficial** [PojavLauncherTeam/PojavLauncher#3335]
### Describe the bug

I just joined to world and i got the screen bug

### The log file and images/videos

![Screenshot_2022-06-05-18-09-41-606_net kdt pojavlaunch](https://user-images.githubusercontent.com/81319129/172057466-6bd57398-9871-4952-a944-2e8943501ad0.jpg)

### Steps To Reproduce

```markdown
I just joined to world
```

### Expected Behavior

All Besideschat was removed

### Platform

```markdown
- Device model: Redmi 9C 64G
- CPU architecture: armv8l
- Android version: 10
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

I don't know what to do

**Comment by GaucovyAero** [comment]
I don't see any "screen bugs" whatever that is, and since you are on the archaeologic release 3.3.1.1 build, ima disregard your statement. As to what to do, please download the latest update in [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) first. If you have any more issues / or the same old issue on the Actions build, make sure to message here so we can figure out what the issue is and fix it soon. Thanks!

Aero

**Comment by DanelOfficial** [comment]
> I don't see any "screen bugs" whatever that is, and since you are on the archaeologic release 3.3.1.1 build, ima disregard your statement. As to what to do, please download the latest update in [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) first. If you have any more issues / or the same old issue on the Actions build, make sure to message here so we can figure out what the issue is and fix it soon. Thanks!
> 
> Aero

Ok i will say what happened. I just joined in 1.18.1 world in minecraft 1.18.1 in pojav launcher and inventory, chat and scope gone

**Comment by GaucovyAero** [comment]
> > I don't see any "screen bugs" whatever that is, and since you are on the archaeologic release 3.3.1.1 build, ima disregard your statement. As to what to do, please download the latest update in [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) first. If you have any more issues / or the same old issue on the Actions build, make sure to message here so we can figure out what the issue is and fix it soon. Thanks!
> > Aero
> 
> Ok i will say what happened. I just joined in 1.18.1 world in minecraft 1.18.1 in pojav launcher and inventory, chat and scope gone

Riiiiiight, this got fixed about a month ago by a pretty random person. Install OptiFine on any version you want to play, disable Fast Render in OptiFine Performance settings, go to the Shaders tab and set Antialiasing to FXAA 2x. It should fix your issue.

![image](https://user-images.githubusercontent.com/85581164/188133783-70c8c628-a770-4903-bdf2-401e269126b2.png)
