### ISSUE TITLE
No optifine

### ISSUE THREAD

**Issue by WasierLion2102** [PojavLauncherTeam/PojavLauncher#3336]
### Describe the bug

On version 1.16.5, optifine does not work with forge

### The log file and images/videos

![Screenshot_2022-06-05-18-33-16-567_net kdt pojavlaunch](https://user-images.githubusercontent.com/105164782/172058260-3b50f817-26aa-4c66-b2e5-e607a8a6146e.jpg)
![IMG_20220605_183200](https://user-images.githubusercontent.com/105164782/172058267-82c88c48-ce66-4a99-a73e-0c666a4edfdb.jpg)

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Press play
3. 30 seconds later: error
```

### Expected Behavior

Game was crashed

### Platform

```markdown
- Device model: Poco X3 pro
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia
```

**Comment by Mathias-Boulay** [comment]
latestlog.txt needed

**Comment by Mathias-Boulay** [comment]
also, optifine alone works with forge 🤔

**Comment by GaucovyAero** [comment]
No log provided. The latest OptiFine builds (latest is H9 for 1.19.2) and all ones older than that are verified working on Pojav. Therefore, closing.
