### ISSUE TITLE
Mouse doesn't  highlight where it actually is 

### ISSUE THREAD

**Issue by Mousebu** [PojavLauncherTeam/PojavLauncher#3337]
### Describe the bug

The virtual mouse doesn't actually higlitght where it actually is

### The log file and images/videos

https://user-images.githubusercontent.com/106907343/172061681-a2a1d552-29d8-4909-b783-86049077871a.mp4

### Steps To Reproduce

```markdown
1. Start pojav launcher 
2. Launch any version 
3. The virtual mouse doesn't actually displays the button where it is
```

### Expected Behavior

Please fix this the virtual mouse should be there where it highlights 

### Platform

```markdown
- Device model: Vivo y91i 
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: latest on playstore
```

### Anything else?

Please fix this its so annoying

**Comment by Mathias-Boulay** [comment]
hmm
Notch detection is something available on android 9 onward.
Will be a bit tricky to handle your case

**Comment by Mousebu** [comment]
So you mean it will take time to fix this bug

**Comment by Mathias-Boulay** [comment]
@Mousebu Can you try this debug build ?
https://github.com/PojavLauncherTeam/PojavLauncher/runs/6759772253

**Comment by GaucovyAero** [comment]
> So you mean it will take time to fix this bug

No idea if serpent's build helped you, but you can do 2 things that will likely fix this problem.
a) Upgrade to Android 9 or higher (find a guide for your phone)
b) Enable the notch.

**Comment by Mousebu** [comment]
How to enable the notch?

**Comment by GaucovyAero** [comment]
> How to enable the notch?

Absolutely no idea. Every phone has it different. Basically, you have the screen that is currently disabled in the upper part of your phone where your camera is. That's why it doesn't work on pojav. You have to enable the upper part of your display in order to have an accurate virtual mouse on Android 8 and lower.

**Comment by Mathias-Boulay** [comment]
@Aerolome he can't, at least from pojav side. Since android supports display cutouts only since 9.

@Mousebu did you try the build ?

**Comment by Mousebu** [comment]
I dont have java 8 runtime

> @Aerolome he can't, at least from pojav side. Since android supports display cutouts only since 9.
> 
> @Mousebu did you try the build ?

What runtime should i choose? Java 17 would work?

**Comment by Mathias-Boulay** [comment]
I meant "since android 9"

**Comment by REYASKANNAN** [comment]
I can't click any of the single player or multiplayer even I can't click quit game the mouse is working but couldn't click even I click the home button on mobile and clear on the minimize and again went to pohavlanchur multipletimes but still I won't work

But that problem in fabric 1.16.5 but I can use normal vinnila 1.16.5 I can click on 1.16.5 also I really need the fabric
Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…

**Comment by REYASKANNAN** [comment]
![Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…]()

**Comment by il-av** [comment]
I'm running Android 13 beta and have a similar issue. Pojav doesn't render at all in the bar where the hole punch is. It renders the game properly but the controls extend off screen by an amount equal to the hole punch size.
This causes mouse clicks to be slightly offset.
I can fix it by going into developer options and hiding the cutout.
![Screenshot_20220731-161348](https://user-images.githubusercontent.com/88461714/182043901-aa49dcc5-dcbe-47d4-a243-20ae1eeb40eb.png)

**Comment by GaucovyAero** [comment]
> I'm running Android 13 beta and have a similar issue. Pojav doesn't render at all in the bar where the hole punch is. It renders the game properly but the controls extend off screen by an amount equal to the hole punch size. This causes mouse clicks to be slightly offset. I can fix it by going into developer options and hiding the cutout. ![Screenshot_20220731-161348](https://user-images.githubusercontent.com/88461714/182043901-aa49dcc5-dcbe-47d4-a243-20ae1eeb40eb.png)

Well, just enable the notch if you can.

**Comment by il-av** [comment]
The notch is enabled. Things display there throughout the OS. Pojav launcher doesn't use the space when running Minecraft. Other apps will use it and adapt to it.

**Comment by GaucovyAero** [comment]
> The notch is enabled. Things display there throughout the OS. Pojav launcher doesn't use the space when running Minecraft. Other apps will use it and adapt to it.

Well, then disable it and test again.

**Comment by il-av** [comment]
When the notch is disabled system wide, the issue is fixed.

**Comment by GaucovyAero** [comment]
> When the notch is disabled system wide, the issue is fixed.

indeed

**Comment by Mousebu** [comment]
New update fixed it   :-)
