### ISSUE TITLE
THE ISSUE 'DIDN'T FILE CLASS...' always appears in every time I try to play after downloading

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#334]
Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjglboardwalk/2.9.1/lwjglboardwalk-2.9.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar", zip file "/storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/versions/1.9/1.9.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by khanhduytran0** [comment]
V2 have issue on Android 6, so you can't launch on. Try use v3 instead.

**Comment by khanhduytran0** [comment]
(as that error was happend on most Android 6 devices)

**Comment by ghost** [comment]
I tried v3 but when I'm installing a version of Minecraft it Redirects me to the login page and my user is also automatically deleted. It happened on every pojav launcher v3

**Comment by ghost** [comment]
Please fix this issue.
Important please read ' I can launch upto Minecraft 
v 1.8.9 but , I can't play on the worlds I created and it prompted "Sorry I let you down".

**Comment by khanhduytran0** [comment]
> I tried v3 but when I'm installing a version of Minecraft it Redirects me to the login page
Try reduce max RAM to 768mb or try testing6 64bit

**Comment by khanhduytran0** [comment]
> I tried v3 but when I'm installing a version of Minecraft it Redirects me to the login page

Try reduce max RAM to 768mb or try testing6 64bit

**Comment by ghost** [comment]
Is this because of my device. It is has 1gb ram memory??????

**Comment by ghost** [comment]
And it is Android 5.1

**Comment by ghost** [comment]
Device name: OPPO NEO 5 ,
                         OPPO 1201

**Comment by ghost** [comment]
> > I tried v3 but when I'm installing a version of Minecraft it Redirects me to the login page
> 
> Try reduce max RAM to 768mb or try testing6 64bit

I am trying v2.5.2

**Comment by ChargedHat42838** [comment]
Now no version works.
I don't know what to do.😲😲😲😲😲😲

**Comment by ChargedHat42838** [comment]
I am not satisfied with your product sorry.
I have no hope. I'm quitting pojav launcher.

**Comment by ChargedHat42838** [comment]
If want to say something for the last time reply to me once. Then I shall close the issue.

**Comment by ghost** [comment]
I tried playing v3 on a more better device, that too only upto Minecraft v1.9 works. The device is Android 10, the first was Android 5.1

**Comment by ghost** [comment]
I was never trying v3 testing.
Because I didn't know what pojav launcher team uploaded in the assets releasing many Aarch stuffs.

And I didn't know what Aarch my device was but now that I know I will try the correct one
