### ISSUE TITLE
[F-Req] Please have Java 18 support for minecraft 1.19

### ISSUE THREAD

**Issue by CharlesCanlom** [PojavLauncherTeam/PojavLauncher#3340]
### Is this request related to a bug?

The latest version available for java working in here is java 17

### Describe the request.

I want to have easy downloads of java VMs of any version, not just Java 18.

**Comment by NotAHero04** [comment]
~~Why don't you build one for yourself? With some core Linux knowledge, you can do that with ease :)~~

**Comment by WesleyVanNeck** [comment]
> ### Is this request related to a bug?
> The latest version available for java working in here is java 17
> 
> ### Describe the request.
> I want to have easy downloads of java VMs of any version, not just Java 18.
> 
> ### Anything else?
> _No response_

mc 1.19 doesnt even use java 18 so no

**Comment by WesleyVanNeck** [comment]
![Screenshot_20220608-185142](https://user-images.githubusercontent.com/25864932/172673383-be58f8ae-93b0-4369-a145-67fb78f3b311.png)
![Screenshot_20220608-184657](https://user-images.githubusercontent.com/25864932/172673387-05f844d5-9760-409e-a818-d54082ade672.png)

**Comment by offbeat-stuff** [comment]
there can be performance benifits with using java 18
archlinux-arm has java 18 builf

**Comment by Safwaan210** [comment]
> ### Is this request related to a bug?
> The latest version available for java working in here is java 17
> 
> ### Describe the request.
> I want to have easy downloads of java VMs of any version, not just Java 18.
> 
> ### Anything else?
> _No response_

**Comment by Safwaan210** [comment]
Please download link share

**Comment by GaucovyAero** [comment]
no
