### ISSUE TITLE
[F-Req] <give me the link for v3_openjdk bcz its the most stable version and also it has offline account>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3341]

**Comment by ghost** [comment]
I meant v3_openjdk

**Comment by kuzy21** [comment]
@ToxicGamingGithub NO, I will not give you the link, you are pirating ( which is illegal ) just buy minecraft

**Comment by mchnjt** [comment]
> ### Is this request related to a bug?
> _No response_
> 
> ### Describe the request.
> _No response_
> 
> ### Anything else?
> _No response_

SUCK MY NUTSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

**Comment by miggythewriter** [comment]
No pirate

**Comment by ABJ4403** [comment]
wtf dude... Just download older version from APKMirror.com, or download manually if you have Aurora Store.
The last version that still have "Offline login" is "crocus-v3_openjdk (9938053)"

**Comment by ssaagamemer** [comment]
> @ToxicGamingGithub NO, I will not give you the link, you are pirating ( which is illegal ) just buy minecraft

Umm Someone Mom Not Gonna Buy It LOL

**Comment by crystall1nedev** [comment]
@ABJ4403 Do not assist piracy on our official repositories or you will be blocked from accessing them.

This issue is being closed because we removed offline mode for a reason, end of story. We will not condone piracy on our repository and do not support those who pirate the game.
