### ISSUE TITLE
[BUG] Fabric 1.18.2 black screen on startup

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3342]
### Describe the bug

No matter how long i wait, the game never actually displays anything. And i did have vanilla 1.18.2 before installing fabric.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8855401/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Download fabric installer
3.Install Fabric 1.18.2
4.Launch Fabric 1.18.2
```

### Expected Behavior

The game would display something

### Platform

```markdown
- Device model: Mi 9T Pro
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: latest github actions build
```

### Anything else?

h

**Comment by GaucovyAero** [comment]
Because you are not on Actions, and you are on an even older build. The archaeological build, because you downloaded it from Releases rather than Actions. Download the one in Actions.

**Comment by ghost** [comment]
Forgot to mention it, i DID test it with the github actions build, same error

> Because you are not on Actions, and you are on an even older build. The archaeological build, because you downloaded it from Releases rather than Actions. Download the one in Actions.

Forgot to mention it that i DID test it on the actions build, same error

**Comment by GaucovyAero** [comment]
> Forgot to mention it, i DID test it with the github actions build, same error
> 
> > Because you are not on Actions, and you are on an even older build. The archaeological build, because you downloaded it from Releases rather than Actions. Download the one in Actions.
> 
> Forgot to mention it that i DID test it on the actions build, same error

This crashes because you haven't installed Java 17 (it won't work even if you installed jre17 on this version of pojav, but at least it'll get past this error). Pretty sure the latest Actions build fully works, and if it doesn't, it sure does give a different error unless you force Java 8 onto 1.17 and higher (because these versions need Java 17).

**Comment by ghost** [comment]
I am pretty sure i installed jre17 and have set it to use jre17.  same error, maybe corrupt jre? unnecesary dont read: i use archlinux btw

**Comment by ghost** [comment]
installed github actions build, installed 1.18.2 fabric, installed jre17, forced it to use jre17, and now instead of just being a black screen, now just throws me an error, (code 1),and the log is the same, it seems it doesnt actually use jre17? well i guess its a step forward. Will try removing all the other java runtimes.

**Comment by ghost** [comment]
> installed github actions build, installed 1.18.2 fabric, installed jre17, forced it to use jre17, and now instead of just being a black screen, now just throws me an error, (code 1),and the log is the same, it seems it doesnt actually use jre17? well i guess its a step forward. Will try removing all the other java runtimes.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8859119/latestlog.txt)

**Comment by GaucovyAero** [comment]
> > installed github actions build, installed 1.18.2 fabric, installed jre17, forced it to use jre17, and now instead of just being a black screen, now just throws me an error, (code 1),and the log is the same, it seems it doesnt actually use jre17? well i guess its a step forward. Will try removing all the other java runtimes.
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8859119/latestlog.txt)

It still states release as version 3.3.1.1, which as I said, is brutally old and doesn't work with 1.18. Please update if you want to get it working.

**Comment by DitZ60fps** [comment]
what about 32bit? Can it?
