### ISSUE TITLE
[BUG] <Can't open minecraft 1.19-rc2>

### ISSUE THREAD

**Issue by FreakyMood** [PojavLauncherTeam/PojavLauncher#3343]
### Describe the bug

I am using JDK17, OpenGl 4.6 Vulkan
![Screenshot_2022-06-08-00-32-23-170_net kdt pojavlaunch](https://user-images.githubusercontent.com/84508366/172477239-eb24644d-50dd-4408-aced-63da150add62.jpg)
**I can not play minecraft 1.19-rc2**

ㅤ

**Crash log:**
---- _Minecraft Crash Report_ ----
// Quite honestly, I wouldn't worry myself about that.

Time: 07.06.22 20:32
Description: Initializing game

java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
	at egi.<init>(SourceFile:26)
	at egi.<clinit>(SourceFile:24)
	at egc.<init>(SourceFile:161)
	at eev.<init>(SourceFile:586)
	at net.minecraft.client.main.Main.main(SourceFile:198)
Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at egi.<init>(SourceFile:26)
	at egi.<clinit>(SourceFile:24)
	at egc.<init>(SourceFile:161)
	at eev.<init>(SourceFile:586)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:198)

-- System Details --
Details:
	Minecraft Version: 1.19 Release Candidate 2
	Minecraft Version ID: 1.19-rc2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1075546112 bytes (1025 MiB) / 1786773504 bytes (1704 MiB) up to 1786773504 bytes (1704 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 4 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4048,38
	Virtual memory used (MB): 3393,56
	Swap memory total (MB): 2252,00
	Swap memory used (MB): 347,45
	JVM Flags: 2 total; -Xms1703M -Xmx1703M
	Launched Version: 1.19-rc2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 4 (aarch64)

### The log file and images/videos

**Crash Logs:**
![Screenshot_2022-06-08-00-42-49-055_net kdt pojavlaunch](https://user-images.githubusercontent.com/84508366/172478815-efd08cd1-a1e4-4869-9dcd-027a6848e88e.png)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Going to settings page
3. Selecting runtime manager
4. Clicking "Add new"
5. Selecting JDK17.tar.xz file
6. Selecting JDK17 as default
7. Going back
8. Clicking renderer
9. Selecting OpenGl 3.0 or OpenGl 4.6
10. Selecting the "Snapshots☑️" in version types to list
11. Downloading minecraft "1.19-rc2"
12. Clicking to play
13. Waiting till opens
14. Pojavlauncher gives error: "Application/Game exited with code -1"
```

### Expected Behavior

I want to fix this problems in minecraft lastest versions (1.17+)

### Platform

```markdown
- Device model: Redmi 8/64G
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: crocus.v3.openjdk
```

**Comment by miggythewriter** [comment]
Won't get help pirate

**Comment by MarcyIgop** [comment]
same problem

**Comment by Fl414r** [comment]
> Won't get help pirate

Calm down, not everyone has the opportunity to buy the game.

**Comment by WesleyVanNeck** [comment]
> > Won't get help pirate
> 
> Calm down, not everyone has the opportunity to buy the game.

yes but we as pojav can get a lawsuite if we coninue offline mode

**Comment by Therealrex** [comment]
Same I Was Gonna Play 1.19 but it just crashed :[

**Comment by Therealrex** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 11/3/22, 12:01 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
	at egi.<init>(SourceFile:26)
	at egi.<clinit>(SourceFile:24)
	at egc.<init>(SourceFile:161)
	at eev.<init>(SourceFile:586)
	at net.minecraft.client.main.Main.main(SourceFile:198)
Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at egi.<init>(SourceFile:26)
	at egi.<clinit>(SourceFile:24)
	at egc.<init>(SourceFile:161)
	at eev.<init>(SourceFile:586)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:198)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (aarch64) version Android-7.0
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 643122688 bytes (613 MiB) / 964689920 bytes (920 MiB) up to 964689920 bytes (920 MiB)
	CPUs: 7
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 0 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd08 Stepping r0x0p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3450.67
	Virtual memory used (MB): 3484.09
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1230.01
	JVM Flags: 2 total; -Xms920M -Xmx920M
	Launched Version: 1.19
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 4 (aarch64)
