### ISSUE TITLE
[BUG] Latest version Running on pojavlauncher latest version comes out with code 1

### ISSUE THREAD

**Issue by Muktar47** [PojavLauncherTeam/PojavLauncher#3344]
### Describe the bug

I don't know why, after I installed minecraft 1.19 in the latest pojavlauncher it always crashes with code 1 even though I'm already using a premium account, please fix it

### The log file and images/videos

Latest log🔽
https://www.mediafire.com/file/4h24b6ytzuiqfme/latestlog.txt/file

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.select 1.19 version
3.wait
4.Crash
```

### Expected Behavior

Launch the pojavlauncher

### Platform

```markdown
- Device model: Vivo Y12 3/32
- CPU architecture: AARCH 64
- Android version: 9
- PojavLauncher version: dahlia-v3-openjdk
```

### Anything else?

No

**Comment by Vasuagent** [comment]
Sameew
