### ISSUE TITLE
Is it possible to change from the dahlia-9-e2e664715-v3_openjdk to another one

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#3345]
### Is this request related to a bug?

No

### Describe the request.

Is it possible, if so how can I do it, of not can the devs make it optional 

### Anything else?

Thanks for helping me

**Comment by mchnjt** [comment]
you uninstall dahlia and install v3_openjdk ¯\_(ツ)_/¯

**Comment by kuzy21** [comment]
@Jetstreem tried that, didn't work :(

**Comment by Mathias-Boulay** [comment]
full uninstallation is needed
