### ISSUE TITLE
[BUG] 1.19 crashing 

### ISSUE THREAD

**Issue by Vasuagent** [PojavLauncherTeam/PojavLauncher#3348]
### Describe the bug

1.19 crashes  application exited code 1

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Start pojavlauncher
Select Jr 17,holy renderer
Start 1.19
Game crashes with code 1
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: realme 8s 5g
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: play Store latest
```

### Anything else?

No

**Comment by 2019Z2** [comment]
Same here.
After checking the log file, it seems like a shared library is missing, or corrupted.

**Comment by WesleyVanNeck** [comment]
Update to the latest dev build

**Comment by WesleyVanNeck** [comment]
![Screenshot_20220609-121145_PojavLauncher (Minecraft_ Java Edition voor Android)](https://user-images.githubusercontent.com/25864932/172825355-4972a7d7-a6f7-47dd-b269-f594046afc95.png)
![Screenshot_20220609-122126_PojavLauncher (Minecraft_ Java Edition voor Android)](https://user-images.githubusercontent.com/25864932/172825364-df437a01-1a0e-4f04-9db6-70ba550b27c2.png)

**Comment by WesleyVanNeck** [comment]
Works for me fine on the dev build

**Comment by WesleyVanNeck** [comment]
Also no latestlog.txt no help

**Comment by Danazaxo** [comment]
rr

**Comment by Bel69420** [comment]
I guess he should use dahlia 15 cuz dahlia 15 auto patch the version

**Comment by GaucovyAero** [comment]
Make sure to update your launcher first. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`
