### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by RecorderPro** [PojavLauncherTeam/PojavLauncher#335]
Im trying to use Minecraft alpha 1.1.2_01 it opens the game but only shows the menu screen for a second at the bottom of the left side of my tablet it does this for all other versions as well

**Comment by khanhduytran0** [comment]
Go to send custom keycode then press f11, old versions will be go to normal state.

**Comment by RecorderPro** [comment]
Where do I go to send custom keycode?

**Comment by RecorderPro** [comment]
> Go to send custom keycode then press f11, old versions will be go to normal state.

Where would I go to do this?

**Comment by khanhduytran0** [comment]
Swipe from right side to left, you will see.

**Comment by mglovers123** [comment]
slide the screen right when click play and select send custom key

Pada tanggal Kam, 1 Okt 2020 05.17, RecorderPro <notifications@github.com>
menulis:

**Comment by RecorderPro** [comment]
I swiped right when I pressed play but all I see was the gui and mouse on and off button

**Comment by RecorderPro** [comment]
Of do you mean the dev log?
