### ISSUE TITLE
Bug Double account

### ISSUE THREAD

**Issue by Bel69420** [PojavLauncherTeam/PojavLauncher#3350]
### Describe the bug

When you Login To Your xbox account you can see there a double account

### The log file and images/videos

https://user-images.githubusercontent.com/89313901/172931327-f3965a4c-8484-485b-b367-c616e2cc80f5.mp4

### Steps To Reproduce

```markdown
1.Start Pojav Launcher
2.login Into your xbox account
3.after login and enter the launcher click the icon your account
4.you can see there double account
5.click the account 2

And there game crashes
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model:Samsung Galaxy Note 10 Lite
- CPU architecture:aarch64
- Android version:12
```

**Comment by GaucovyAero** [comment]
Thanks for figuring this out! We'll do more investigating as to what's the issue :)

**Comment by Mathias-Boulay** [comment]
Known since before the dahlia release

**Comment by Mathias-Boulay** [comment]
it doesn't happen on saved accounts iirc

**Comment by Bel69420** [comment]
I already try on old version of pojav and the result is same
