### ISSUE TITLE
[Login Problem] The problem occurs when i try to login with my online account 

### ISSUE THREAD

**Issue by Mrpro234** [PojavLauncherTeam/PojavLauncher#3352]
### Describe the bug

I will attach an image so can you please take a look at it and fix the problem of loging in with online account.

### The log file and images/videos

![Screenshot_20220609-165712_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/107222228/172952786-fb1322e7-daec-4c53-b032-7d4960b4850c.jpg)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Enter username and password.
3. Tap on login.
Then shows the message of error.
```

### Expected Behavior

I expect that I can play easily with my online account.

### Platform

```markdown
- Device model: Galaxy S21 5G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

### Anything else?

No but please fix these issue pleaseee!

**Comment by khanhduytran0** [comment]
You must use Microsoft login. Migration is required if you have a Mojang account.

**Comment by Mrpro234** [comment]
Can u explain how do I do this please
