### ISSUE TITLE
[BUG] LabyMod 1.8.9 pwease fix the crash effect when its 75% of the game loading its will crash 

### ISSUE THREAD

**Issue by jethro527** [PojavLauncherTeam/PojavLauncher#3353]
### Describe the bug

> `Start` Labymod 1.8.9 when load ing is 75% it will crash 

> `But` labymod 1.12.2 is not crashing but i dont like 1.12.2

### The log file and images/videos

> LabyMod 1.8.9 bug

> Please fix

> `not working`
![Screenshot_20220610-075956](https://user-images.githubusercontent.com/74866333/172964268-6b3b1949-a65d-49fd-b255-d3f7c0b8ffd0.png)

### Steps To Reproduce

```markdown
1. Start pojav launcher
Then install labymod 1.8.9
Then play labymod 1.8.9
Then it will crash at 75%
```

### Expected Behavior

I want this labymod 1.8.9 work now :

### Platform

```markdown
- Device model: Itel P36
- CPU architecture: arm/aarch32
- Android version: 9.0
- PojavLauncher version: latest
```

**Comment by NotAhackerforfun** [comment]
Pinag doesn't support lang mod 1.8.9 yet

**Comment by NotAhackerforfun** [comment]
Only 1.12+laby mod

**Comment by GaucovyAero** [comment]
There is a fix for this, check this out: https://github.com/NotAHero04/RandomPojavThings/blob/main/LabyMod/README.md
