### ISSUE TITLE
[F-Req] plese fix web display mod white screen

### ISSUE THREAD

**Issue by Fardhak** [PojavLauncherTeam/PojavLauncher#3354]
### Is this request related to a bug?

you needed mcef browser file for fix
![Screenshot_2022-06-10-13-37-05-26_f9ee0578fe1cc94de7482bd41accb329](https://user-images.githubusercontent.com/86583030/173005926-564387bd-4ac2-422d-837d-b82f8ca2d466.jpg)

### Describe the request.

no response

### Anything else?

no response

**Comment by mchnjt** [comment]
Please remember, #1948 exists. You can report it there, since this is a confirmed partially-working mod.

All mods **cannot** work with PojavLauncher itself, thus a workaround should be applied.

**Comment by Fardhak** [comment]
web display can't be fixed in pojav launcher?
too bad😔 if it can't be fixed. My youtuber friend want to try web display in pojav launcher to watch youtube.

**Comment by offbeat-stuff** [comment]
why though??

**Comment by NotAHero04** [comment]
It requires the entire Chromium platform (which is the base for browsers like Google Chrome) to be included, which skyrockets the app size.

**Comment by offbeat-stuff** [comment]
they probably dont want the app to include a whole project
they probably want a way to add or link .so dynamic libraries in minecraft

**Comment by offbeat-stuff** [comment]
actually the mod does not support linux
so you cannot run this mod because of the os not because its android

**Comment by ajit56** [comment]
https://youtu.be/T1pN4yyQFpU

**Comment by mchnjt** [comment]
> https://youtu.be/T1pN4yyQFpU

offtopic.
![Screenshot_2022-06-14-16-06-09-12](https://user-images.githubusercontent.com/83752061/173526649-291609e7-5cc4-40cb-ae76-19f2416cbb52.png)

**Comment by Mathias-Boulay** [comment]
#1948
