### ISSUE TITLE
Request for pojavlauncher crocus-v3 openjdk Version 

### ISSUE THREAD

**Issue by hemangiwani** [PojavLauncherTeam/PojavLauncher#3355]
### Describe the bug

I know this is not a bug but I had downloaded every 'pojavlauncher crocus-v3 openjdk' version but it shows that 'the file appears to be corrupt soo pls send me a valid download link for 'pojavlauncher crocus-v3 openjdk' pls pls pls

### The log file and images/videos

Nothing

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

I expect to get the valid downloadc
 link for 'pojavlauncher crocus-v3 openjdk' version pls send it

### Platform

```markdown
- Device model: redmi note 4 4/64G
- CPU architecture: aarch 64
- Android version: 11
- PojavLauncher version:
```

### Anything else?

Nothing

**Comment by mchnjt** [comment]
> ### Describe the bug
> I know this is not a bug but I had downloaded every 'pojavlauncher crocus-v3 openjdk' version but it shows that 'the file appears to be corrupt soo pls send me a valid download link for 'pojavlauncher crocus-v3 openjdk' pls pls pls

@hemangiwani don't be dumb, we know you're another pirate crawling in the pile.

This error triggers because of a corrupted JRE, stfu

We will **not** recompile crocus.
Go compile it yourself

**Comment by Perotanmay** [comment]
Bro but how to do it just tell me that

**Comment by HitmanzombieC148** [comment]
Well,you can search the crocus version from google
