### ISSUE TITLE
[BUG] App crashed, application code 1

### ISSUE THREAD

**Issue by 2019Z2** [PojavLauncherTeam/PojavLauncher#3356]
### Describe the bug

Application exited with code 1.

### The log file and images/videos

kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjli.so success
I/jrelog  (15767): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libverify.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjava.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libnet.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libnio.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libawt.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (15767): dlopen libfreetype.so failed: dlopen failed: library "libfreetype.so" not found

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libfontmanager.so failed: dlopen failed: library "libfreetype.so" not found: needed by /data/data/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libfontmanager.so in namespace classloader-namespace

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjimage.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/liblcms.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libdt_socket.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libverify.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libsctp.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjavajpeg.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libprefs.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libj2pkcs11.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libmlib_image.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libnio.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libinstrument.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjaas.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libextnet.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libmanagement_agent.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libnet.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libj2gss.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjava.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjsig.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libfontmanager.so failed: dlopen failed: library "libfreetype.so" not found: needed by /data/data/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libfontmanager.so in namespace classloader-namespace

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/server/libjsig.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/librmi.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjli.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libzip.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libmanagement_ext.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libmanagement.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libawt.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjdwp.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libjawt.so success

I/jrelog  (15767): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20220513-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (15767): dlopen /data/app/~~a4v1SDBXUrNWBZLHAt3lnw==/net.kdt.pojavlaunch.debug-QSk_AqSX7h6AFQple_kLig==/lib/arm64/libopenal.so success

I/jrelog  (15767): Done processing args
I/jrelog  (15767): Found JLI lib
I/jrelog  (15767): Calling JLI_Launch

2022-06-10 15:20:13,777 main ERROR appender Console has no parameter that matches element Policies
[15:20:26] [main/INFO]: Building optimized datafixer
[15:20:38] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[15:20:38] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[15:20:38] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics

### Steps To Reproduce

```markdown
Download Minecraft, use JRE17
```

### Expected Behavior

I expect the game to launch

### Platform

```markdown
- Device model: Redmi10
- CPU architecture: aarch64 (arm64)
- Android version: 12
- PojavLauncher version: Latest automatic build
```

### Anything else?

Btw, the text in this build is upside down.

**Comment by 2019Z2** [comment]
Perhaps I'm using a corrupted build of JRE?

**Comment by artdeell** [comment]
Send the full log, as a file

**Comment by 2019Z2** [comment]
How? Is it possible (it's stored in the application data, and not in a public folder)

**Comment by artdeell** [comment]
It's possible when using the right file explorer (e.g. ZArchiver)

**Comment by 2019Z2** [comment]
I don't know how to upload in GitHub, so I used a third party: https://file.io/8tPAMTPIRJB4

**Comment by 2019Z2** [comment]
Btw I used Dorg.lwjgl.util.Debug=true

**Comment by artdeell** [comment]
Try to delete the `libraries` from .minecraft (don't forget to turn on hidden folders)

>

**Comment by 2019Z2** [comment]
Any difference between deleting the folder and re-installing?

**Comment by artdeell** [comment]
Well, deleting the folder will force the launcher to redownload all libs
In your case, only jopt-simple seems to be broken, and deleting all libs is a pretty simple solution for that (since launcher will redownload them anyway (EXCEPT OPTIFINE AND FORGE, you will have to reinstall it))

**Comment by Askkqmq** [comment]
Man check the lasestlog.txt file
