### ISSUE TITLE
VirGL Renderer conflict with optifine

### ISSUE THREAD

**Issue by MerciGG** [PojavLauncherTeam/PojavLauncher#3357]
### Describe the bug

Fast render with VirGL renderer isnt support if u use fast render with virgl the menu panorama will just be grey and if u click on buttons such as singleplayer, multiplayer it it will freeze

### The log file and images/videos

No logs it dosent crash it just freezes

### Steps To Reproduce

```markdown
1. Use optifine
2. enable fast render
3. Use virgl
4. And yeah
```

### Expected Behavior

Be compatible with fast render

### Platform

```markdown
- Device model: Oppo A94
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

Plz Fix UwU

**Comment by offbeat-stuff** [comment]
dont use virgl use latest google play update or from github actions and use gl4es

**Comment by NotAHero04** [comment]
This is apparently a known issue. Use gl4es.
