### ISSUE TITLE
i need log in

### ISSUE THREAD

**Issue by Phonekhank** [PojavLauncherTeam/PojavLauncher#3359]
### Is this request related to a bug?

1.18.2

### Describe the request.

add

### Anything else?

no log in

**Comment by Phonekhank** [comment]
phonekhank@outlook.com

**Comment by Synz123** [comment]
What do you mean? you need an account? Use your microsoft or minecraft.net account.

**Comment by offbeat-stuff** [comment]
he is asking for a account with a password
Should close this issue

**Comment by USMP-lancer** [comment]
@Phonekhank issue lacks proper info, and should be closed
