### ISSUE TITLE
lots of bugs forge not working controls broken

### ISSUE THREAD

**Issue by dummy22328** [PojavLauncherTeam/PojavLauncher#3360]
### Describe the bug

cant play the game properly because i cant shift click items when in inventory and if am in inventory when i click esc it doesnt work i have to click it multiple times.forge doesnt work when i try to load it it says application exited with code 1 this only happened after the new update i cant change my F5 to v 

### The log file and images/videos

i cant record cus the copmuter gets too laggy to do antthing 

### Steps To Reproduce

```markdown
launch a world than try to shift click and also try to esc first try,try to change  F5 to v
```

### Expected Behavior

the gamewill crash if you use forge

### Platform

```markdown
- Device model:lenovo chromebook
- CPU architecture: 86_64
- Android version:dont know how to check 
- PojavLauncher version: the latest
```

### Anything else?

i was using optifine

**Comment by GaucovyAero** [comment]
Weird. Works just fine for me.

**Comment by Mathias-Boulay** [comment]
"the latest"

**Comment by GaucovyAero** [comment]
Make sure to update your launcher first. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`
