### ISSUE TITLE
[BUG] <1.19 crashed>

### ISSUE THREAD

**Issue by MHMD456** [PojavLauncherTeam/PojavLauncher#3361]
### Describe the bug

I have the latest official version of pojavluncher. I downloaded the 1.19 but when i run it 1.19 crashed with error code -1 I use the java 17 runtime and holy renderer . 

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8883937/latest.log)

### Steps To Reproduce

```markdown
1. I go to pojavluncher
2. I run 1.19 
3- pojavluncher crashed with error code -1
```

### Expected Behavior

I expected 1.19 in the new version pojavluncher Run but this did not happen

### Platform

```markdown
- Device model: Redmi note 8 pro/ 128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: The latest version of the Play Store
```

**Comment by GaucovyAero** [comment]
Uhm, what is this then?
[13:05:06] [Render thread/INFO]: Setting user: fyucyufugfyucjhf

**Comment by MHMD456** [comment]
This is my username in the game 😂

**Comment by MHMD456** [comment]
There was a problem for me in the game when I entered the server, if someone was my name, that person would identify me and say that you have registered and I had to enter the password, I created a completely random account and the server Allow the registry.

**Comment by MHMD456** [comment]
Is there anyone who can solve my problem?

**Comment by InfiniXDerg** [comment]
||no||

**Comment by MHMD456** [comment]
👌

**Comment by MHMD456** [comment]
I just saw this email, I do not know why you did not help me. It was
surprising to me. I had the old version until yesterday, when version 1.19
of Minecraft came, I downloaded it, then I found out that the launcher was
updated. I updated the launcher and added all the old launcher files to the
new launcher files, but unfortunately I realized that now I need a premium
account to play . However, I already had the old launcher files and could
play pre-downloaded versions on cracked servers. And since I had downloaded
1.19, I wanted to try it, but I got the error I told you about. That's all
the story, I hope you understand the truth. If there is a need and you
think I did not follow the rules, I can delete my account. Good luck.
Goodbye

در تاریخ شنبه ۱۱ ژوئن ۲۰۲۲،‏ ۲۰:۴۹ SpyroGam3r ***@***.***>
نوشت:

**Comment by mchnjt** [comment]
omfg can someone stop using github on their emails 
it's cringe

**Comment by MHMD456** [comment]
* English is not my native language . That's why we do not speak English as
well as our mother tongue.

در تاریخ یکشنبه ۱۲ ژوئن ۲۰۲۲،‏ ۲۰:۱۰ محمد امانی <
***@***.***> نوشت:

**Comment by MHMD456** [comment]
At least I can ask why you did not answer my questions
Of course, I thought that in order to unsubscribe, I had to log out of the
account, because of what you said, I logged out of the account . I created
a new account to ask my questions, yes it was very stupid. Because even I
do not know how to close my GitHub account. However, your work is worse
than with someone who does not even know English well , does not have
access to the original account , runs the game with its own old launcher
files and creates two accounts due to ignorance .
If you think that I have acted against the rules that I do not even know
what they are, tell me how to delete my GitHub account and I will do it
willingly with a little effort like before I can solve my problems myself.
Thanks .

در تاریخ یکشنبه ۱۲ ژوئن ۲۰۲۲،‏ ۱۳:۴۴ Jether Cloyd ***@***.***>
نوشت:
