### ISSUE TITLE
[BUG] I cannot play with fabric 0.14.0

### ISSUE THREAD

**Issue by BananaJoeIsCool** [PojavLauncherTeam/PojavLauncher#3362]
### Describe the bug

it kept black screen, i been waited for 5 minute and its still stuck!!

### The log file and images/videos

I dont know where to find it

### Steps To Reproduce

```markdown
1.Open Pojav
2.Login
3.use fabric 0.14.0
4.stuck in loading
```

### Expected Behavior

i expected the game would launch

### Platform

```markdown
- Device model: Oppo A71
- CPU architecture: aarch64 (i dont know how to check this)
- Android version: 7.1
- PojavLauncher version: lastest github release
```

### Anything else?

Pls help

**Comment by BananaJoeIsCool** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8884250/latestlog.txt)
I found the log!!

**Comment by GaucovyAero** [comment]
The Fabric JAR didn't get remapped, but i have two things to say:
1. Your launcher version is old, update to the latest one in Play Store,
2. Why are you using this specific version of Fabric (0.14.0) instead of the latest one (0.14.7)?

**Comment by BananaJoeIsCool** [comment]
> The Fabric JAR didn't get remapped, but i have two things to say:
> 
> 1. Your launcher version is old, update to the latest one in Play Store,
> 2. Why are you using this specific version of Fabric (0.14.0) instead of the latest one (0.14.7)?

1.there new one? Thanks
2.my friend recommended it

**Comment by BananaJoeIsCool** [comment]
And also after updating it still blacked screen

**Comment by GaucovyAero** [comment]
> And also after updating it still blacked screen

upgrade fabric to 0.14.7

**Comment by offbeat-stuff** [comment]
goto .minecraft/.fabric/remappedJars/<fabric 1.14.7>
rename .tmp file to client-intermediary.jar
and it should run

**Comment by BananaJoeIsCool** [comment]
> goto .minecraft/.fabric/remappedJars/<fabric 1.14.7> rename .tmp file to client-intermediary.jar and it should run

Ok il try

**Comment by BananaJoeIsCool** [comment]
Now its black screen, after i take a look to remapjar it didnt gave me tmp

**Comment by offbeat-stuff** [comment]
make sure there is a 20 mb file in .minecraft/.fabric/remappedJars/<fabric 14.7>
rename that to client-intermediary.jar

**Comment by offbeat-stuff** [comment]
@BananaJoeIsCool you have to wait a bit for the file to be renamed from client-intermediary.jar.tmp to something else
then just rename it and it should work

**Comment by offbeat-stuff** [comment]
can you also send after that if it does not work

**Comment by BananaJoeIsCool** [comment]
> can you also send after that if it does not work

![IMG_20220612_145721](https://user-images.githubusercontent.com/107315395/173223260-0e70927a-a8f7-4d70-859e-88cac9d3bbbc.jpg)
Its always empty after i waited so long in the loading

**Comment by BananaJoeIsCool** [comment]
Do you mind share some 0.14.7 files perhaps?

**Comment by offbeat-stuff** [comment]
send your latestlog.txt

**Comment by offbeat-stuff** [comment]
/storage/emulated/0/games/PojavLauncher/onenine/.fabric/remappedJars/minecraft-1.19-0.14.7/client-intermediary.jar
this is my file

**Comment by offbeat-stuff** [comment]
onenine is the .minecraft folder

**Comment by offbeat-stuff** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8884250/latestlog.txt) I found the log!!

/storage/emulated/0/games/PojavLauncher/.minecraft/.fabric/remappedJars/minecraft-1.16.5-0.14.0/zipfstmp5935078448534472486.tmp

**Comment by offbeat-stuff** [comment]
It should have a line like this saying the filename

**Comment by BananaJoeIsCool** [comment]
> send your latestlog.txt

[Uploading latestlog.txt…]()

**Comment by BananaJoeIsCool** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8885610/latestlog.txt)

**Comment by BananaJoeIsCool** [comment]
i did it, i played it thank you
