### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Zomin0123** [PojavLauncherTeam/PojavLauncher#3363]
### Describe the bug

以購買電腦正版minecraft 在手機無法用Microsoft登入

### The log file and images/videos

![Screenshot_20220612_073114](https://user-images.githubusercontent.com/107328155/173208192-dc66e8de-cbd2-4cd2-9c54-c452f262256b.jpg)

### Steps To Reproduce

```markdown
一樣無法登入Microsoft
```

### Expected Behavior

我希望手機也能玩以購買的正版minecraft

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

無

**Comment by TWTommyee** [comment]
你得到的是AddChildToFamily錯誤，代表您的帳號還沒滿18歲
你可以建一支滿18歲的帳號，然後把它當作家庭召集人加入你想使用的帳號
