### ISSUE TITLE
[BUG] <1.19 crashed with error code -1 >

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3366]
### Describe the bug

Hello . The first time I report a bug, I do not have much information because of it. In the latest official version of Minecraft Launcher, I downloaded 1.19 and it gives error -1 when I run it. 

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8885246/latest.log)

### Steps To Reproduce

```markdown
1.I start the launcher 
2.i start the Minecraft 1.19
3.game crashed and give me -1 error
```

### Expected Behavior

I expected Minecraft 1.19 to run in the new launcher 

### Platform

```markdown
- Device model: Redmi note 8 pro/ 128g
- CPU architecture: aarch64 
- Android version: 11
- PojavLauncher version: The latest official version of the Play Store
```

**Comment by SkulZOnTheYT** [comment]
Looks like you have to download these assets to play version 1.19: https://www.mediafire.com/file/tosb7pmcsnwvols/1.19+Official+Pojavlauncher+By+IlhamGaming.zip/file
This includes libraries, assets, version from 1.19 @ghost

**Comment by mchnjt** [comment]
stfu

**Comment by 2019Z2** [comment]
Try to reinstall the game assets (or to re-install the launcher)

**Comment by GaucovyAero** [comment]
```
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.5.41.jar:?]
```
Minecraft has detected a pirate account, therefore it crashed.
