### ISSUE TITLE
[BUG] Texture Packs dont work

### ISSUE THREAD

**Issue by dummy22328** [PojavLauncherTeam/PojavLauncher#3367]
### Describe the bug

I tried loading a texture pack with optifine 1.12.2 and i placed it into the correct file but when i went to the resource pack in th settings there was nothing 

### The log file and images/videos

there is no log 

### Steps To Reproduce

```markdown
load optifine 1.12.2(or other versions i haven't tested it )
put a texture pack in the texture pack folder
go to the settings 
and yu will see thats theres nothing there
```

### Expected Behavior

I expect the texture pack to be there

### Platform

```markdown
- Device model: Chromebook
- CPU architecture:86_64
- Android version: latest
- PojavLauncher version:latest
```

### Anything else?

This new update has looooots of bugs it could be my computer but these have just been happening after the update

**Comment by dummy22328** [comment]
also my esc key needs serveral trys to work or doesnt work at all,forge mods arent showing up and arent there,cants shift click items all of this has happenend jut when i updated pls fix these combined make the game unplayable

**Comment by yum13241** [comment]
PojavLauncher is not for PCs. There are MUCH better and more stable apps for that.

**Comment by BeastyCoke** [comment]
is there anyway for us chromebook players to download resource pack

**Comment by yum13241** [comment]
Download resource pack? Im pretty sure you mean install.

I would assume you just go into the .minecraft folder and dump the resource pack there.

**Comment by GaucovyAero** [comment]
Resource packs should work just fine though. But if you want to actually resolve this issue (because it's a rather difficult one to fix), you will have to contact us on our official PojavLauncher discord server. You will also recieve help faster.

**Comment by BeastyCoke** [comment]
but when i cant find the resource pack folder i redownloaded it alot of times (i cant use the pojavlauncher discord bc i dont have a account yet)
