### ISSUE TITLE
[BUG] <Keyboard doesn't work>

### ISSUE THREAD

**Issue by Ci15** [PojavLauncherTeam/PojavLauncher#3368]
### Describe the bug

I use galaxy tab 7+, and in latest version of pojav, i can't control the screen and keyboard(not screen keyboard) at the same time.
Player keep moving without pressing the keyboard when i touch the screen and keyboard at once.
Simply, after i touch the screen, the keyboard doesnt work for a while.
In addition, this bug doesnt appear in older version of pojav

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1. Start pojav
2. Touch the screen
3. Still touching the screen, press keyboard
4. Now stop pressing the keyboard
5. Player still move
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Galaxy Tab S7+ 8/256G
- CPU architecture: arch64
- Android version: 12
- PojavLauncher version: latest release
```

**Comment by Bel69420** [comment]
Wait did you use a external keyboard?

**Comment by GaucovyAero** [comment]
I mean, your keyboard should work just fine from my experience. If you want to actually resolve this issue though, you will have to contact us on our official PojavLauncher discord server. You will also recieve help faster.

**Comment by Mathias-Boulay** [comment]
This issue has been fixed a few commits ago, but has yet to be present in the gplay build, closing
