### ISSUE TITLE
[BUG] 1.18.2 Optifine Crash

### ISSUE THREAD

**Issue by EnderPluser** [PojavLauncherTeam/PojavLauncher#3369]
### Describe the bug

For some reason, in optifine 1.18.2 joining an world or an server will crash. But it's fine with vanilla 1.18.2

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8886906/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Login
3. Chose 1.18.2 optifine
4. Join an world/server
5. It crashed
```

### Expected Behavior

i expected optifine to launch like vanilla

### Platform

```markdown
- Device model: Samsung A30
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version: Latest playstore release
```

**Comment by khanhduytran0** [comment]
You were using Sodium, not OptiFine which is not supported for now. #1948
