### ISSUE TITLE
Grey screen for infinity

### ISSUE THREAD

**Issue by pranshuthegamer** [PojavLauncherTeam/PojavLauncher#337]
When I launch every version,
It always shows a grey screen and never goes past it
![Screenshot_20201001-085954](https://user-images.githubusercontent.com/61378895/94762134-8385f600-03c4-11eb-8aca-405615828a56.png)

**Comment by artdeell** [comment]
Send latestlog.txt from `/sdcard/.minecraft/latestlog.txt` here so we can know what happened

**Comment by golimonkey** [comment]
Mybe this will help. https://github.com/PojavLauncherTeam/PojavLauncher/issues/325

**Comment by golimonkey** [comment]
Upgrade to testing 5, set xmx and xms to 800MB, use aarch32 java.

**Comment by pranshuthegamer** [comment]
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--------- beginning of main

**Comment by pranshuthegamer** [comment]
Now will try 32 bit

**Comment by khanhduytran0** [comment]
Try testing6 64-bit as fixed framebuffer issue.

**Comment by pranshuthegamer** [comment]
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--------- beginning of main
S/jrelog  (15525): Error occurred during initialization of VM
S/jrelog  (15525): Could not reserve enough space for 950272KB object heap
S/jrelog  (15525): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so successdlopen /data/d
S/jrelog  (15525): ata/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so failed: dlopen failed: library "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so" not founddlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so failed: dlopen failed: library "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so" not founddlopen /data/app/net.kdt.pojavlaunch-1/lib/arm/libopenal.so successdlopen /data/app/net.kdt.pojavlaunch-1/lib/arm/libgl04es.so successDone processing argsFound JLI libCalling JLI_La
S/jrelog  (15525): unch


As soon as I opened Minecraft it returned back to launcher
32 bit

**Comment by WesleyVanNeck** [comment]
> int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied
> 
> Note: log switch off, only log_main and log_events will have logs!
> --------- beginning of main
> S/jrelog (15525): Error occurred during initialization of VM
> S/jrelog (15525): Could not reserve enough space for 950272KB object heap
> S/jrelog (15525): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so successdlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so successdlopen /data/d
> S/jrelog (15525): ata/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so failed: dlopen failed: library "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so" not founddlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so failed: dlopen failed: library "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so" not founddlopen /data/app/net.kdt.pojavlaunch-1/lib/arm/libopenal.so successdlopen /data/app/net.kdt.pojavlaunch-1/lib/arm/libgl04es.so successDone processing argsFound JLI libCalling JLI_La
> S/jrelog (15525): unch
> 
> As soon as I opened Minecraft it returned back to launcher
> 32 bit

Set your ram lower

**Comment by khanhduytran0** [comment]
Or use 64bit for higher RAM limit.
