### ISSUE TITLE
[F-Req] <Add Optifine, Forge, And Fabric for version 1.18+>

### ISSUE THREAD

**Issue by SkulZOnTheYT** [PojavLauncherTeam/PojavLauncher#3370]
### Is this request related to a bug?

Maybe yes, because this is a bit related to a bug, when I made the optifine 1.18+ version suddenly the pojav launcher crashes, and I hope that in the future I can install optifine,Forge, and fabric version 1.18+

### Describe the request.

Pojav Launcher developer please add optifine, forge and fabric for version 1.18+, I can only play vanilla 1.18 - 1.19 the rest don't, I thought it was like 1.17 back then, when 1.18 auto release 1.17 came with optifine but now it doesn't, why?
Also I'm surprised that until now I haven't been able to install Fabric 1.17, just vanilla is at the forefront, everything else is very lagging, that's why I'm hoping for a speedy update for optifine, forge, and fabric, We have started to object to having to use a premium account, so you developers should understand us too.

### Anything else?

Hopefully it's resolved quickly and I hope to be able to play it

**Comment by mchnjt** [comment]
no

**Comment by SkulZOnTheYT** [comment]
why not agree?

**Comment by khanhduytran0** [comment]
All of these are already supported. Just grab the installer of them and install. Send us logs if it doesn't work.

**Comment by SkulZOnTheYT** [comment]
but @khanhduytran0 I've tried the tutorial on installing optifine on youtube, they succeeded (T Launcher), while when I installed it it came out with the code 1 "[jre/log] 12:13 Free doing"
