### ISSUE TITLE
[ERROR] MSA 503 while logging in

### ISSUE THREAD

**Issue by Shubhooooo** [PojavLauncherTeam/PojavLauncher#3371]
### Describe the bug

java.lang.RuntimeException: 

MSA Error: 503: Service Unavailable, error stream:
{
  "path" : "/entitlements/mcstore"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcStore(Msa.java:225)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:201)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

I am getting this error i have already purchased Minecraft . I have played from pojav ast year there was no such error pls help.Thank you.

### The log file and images/videos

![Screenshot_2022-06-13-08-58-29-104_net kdt pojavlaunch](https://user-images.githubusercontent.com/106261921/173274336-d732860a-0a7e-4669-9643-7c89282352e2.jpg)

### Steps To Reproduce

```markdown
I just tried to login with Microsoft account and this happens sometimes after entering credentials and sometimes just after press Microsoft Login Button.
```

### Expected Behavior

It should have worked

### Platform

```markdown
- Device model: Redmi 9 Power
- CPU architecture: don't know
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

Pls fix or help

**Comment by iSnoxBox** [comment]
same here

**Comment by Vaporsdeath** [comment]
its a mojang side. they messed up something and now no 3rd party services works anymore

**Comment by Szymon64** [comment]
> ### Describe the bug
> 
> java.lang.RuntimeException: 
> 
> MSA Error: 503: Service Unavailable, error stream:
> {
>   "path" : "/entitlements/mcstore"
> }
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcStore(Msa.java:225)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:201)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
> 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:923)
> 
> 
> 
> 
> I am getting this error i have already purchased Minecraft . I have played from pojav ast year there was no such error pls help.Thank you.
> 
> ### The log file and images/videos
> 
> ![Screenshot_2022-06-13-08-58-29-104_net kdt pojavlaunch](https://user-images.githubusercontent.com/106261921/173274336-d732860a-0a7e-4669-9643-7c89282352e2.jpg)
> 
> 
> ### Steps To Reproduce
> 
> ```markdown
> I just tried to login with Microsoft account and this happens sometimes after entering credentials and sometimes just after press Microsoft Login Button.
> ```
> 
> 
> ### Expected Behavior
> 
> It should have worked
> 
> ### Platform
> 
> ```markdown
> - Device model: Redmi 9 Power
> - CPU architecture: don't know
> - Android version: 11
> - PojavLauncher version: Latest
> ```
> 
> 
> ### Anything else?
> 
> Pls fix or help

I have the same problem they have so destroyed and I wonder when they will fix it

**Comment by USMP-lancer** [comment]
i had a different error, 504 isntead of 503, seems after i logged in manually it turned it into a 503, odd, but it may help

**Comment by GaucovyAero** [comment]
Yeah, I have absolutely no idea what to do with this.

**Comment by GaucovyAero** [comment]
@USMP-lancer

Try updating your launcher. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it in your file explorer and then install `app-debug.apk`

Then try logging in again.

**Comment by Szymon64** [comment]
> @USMP-lancer
> 
> Try updating your launcher. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it in your file explorer and then install `app-debug.apk`
> 
> Then try logging in again.
> 

Now tell everyone they want to play and the game from the Play store, no one wants to play, even me, so let the creators embrace it and if not, the game is pure shit and the game will be useless
And no one will care about this game, it stopped for me when I found out that it is impossible to log in

**Comment by mchnjt** [comment]
> Now tell everyone they want to play and the game from the Play store, no one wants to play, even me, so let the creators embrace it and if not, the game is pure shit and the game will be useless And no one will care about this game, it stopped for me when I found out that it is impossible to log in

whoa, nice english
just a sad fact, **we did not ask for your opinion.**
We make the launcher, not the game

**Comment by GaucovyAero** [comment]
> > @USMP-lancer
> > Try updating your launcher. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it in your file explorer and then install `app-debug.apk`
> > Then try logging in again.
> 
> Now tell everyone they want to play and the game from the Play store, no one wants to play, even me, so let the creators embrace it and if not, the game is pure shit and the game will be useless And no one will care about this game, it stopped for me when I found out that it is impossible to log in

We got an email directly from Microsoft telling us that we would have to pay 150000$ if we supported piracy, so we stopped. So either pay 30$ for the game, or 150000$ for you and other people to play for free. Because Microsoft now owns GitHub, we also want to close tickets including piracy in them. Therefore, closing.
