### ISSUE TITLE
[BUG] list of bugs that NEED to be solved

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#3372]
### Describe the bug

exit code 1 shows when i switch renderer in new profile and version select is 1.19
(and other bugs too)
[BUGS] {
   1. the Upside Down text in settings;
}[feature Req]{
   1. why the log output resets when reopening it?;
}
### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8900727/latestlog.txt)

### Steps To Reproduce

```markdown
3. create new profile named 1.19 and version 1.19 and change renderer to holy gl4es
```

### Expected Behavior

you know

### Platform

```markdown
- Device model: galaxy tab a
- CPU architecture: armv8l
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

please fix me and by bro wanna play minecraft java soo much

**Comment by Cube5x59999** [comment]
[INFO] pojav crashes when selecting holy gl4es while creating a profile with 1.19 version NOT launching 1.19 _and i have jre 1.8 bc idk how to get jre 17 AGAIN_ (with prenium account)

**Comment by Cube5x59999** [comment]
[BUG] new feature/some text is upside down

**Comment by Cube5x59999** [comment]
[new bug?] when exiting game on any version, game sends us to login page

**Comment by Cube5x59999** [comment]
[feature] news tab is outdated.

**Comment by Cube5x59999** [comment]
[feature] WHY bad word at settings>experimental.

**Comment by Cube5x59999** [comment]
[solved bc i just set ram to 800 mb but my device has 480 mb ram left]
1.19 on first launch dosnt crash but stuck on preparing for world creation screen and on second launch it crashes on mojang logo(loading) screen

**Comment by offbeat-stuff** [comment]
then close the issue

**Comment by Cube5x59999** [comment]
why close. the main issue isnt solved

**Comment by Cube5x59999** [comment]
issue is that 1.19 stuck on preparing for world creation

**Comment by GaucovyAero** [comment]
> issue is that 1.19 stuck on preparing for world creation

send log

**Comment by Cube5x59999** [comment]
im on my laptop now

**Comment by Cube5x59999** [comment]
logs are above

**Comment by Cube5x59999** [comment]
ill send logs asap

**Comment by GaucovyAero** [comment]
> im on my laptop now

well, you have to get a new log, since the first 1.16.5 one is just caused by broken pojav, i recommend reinstalling it, and on the 1.19 thing, you havent sent a log.

**Comment by Cube5x59999** [comment]
btw preparing for world creation bug is resolved
_i was just impatient bc i see logs_

**Comment by Cube5x59999** [comment]
1 issue solved, 1 more need to be solved (upside down text in settings) and 1 feature req( see above)

**Comment by Cube5x59999** [comment]
(adtional info) im on 32 bit tablet playing pojavlauncher 1.19

**Comment by Cube5x59999** [comment]
helo

**Comment by GaucovyAero** [comment]
> helo

Yeah, sorry for not replying for so long, the upside down text is fixed in the latest action builds.

So, let's update your launcher. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`

**Comment by mchnjt** [comment]
i like how ppl are saying "EXIT CODE 1 MAJOR BUG PLS FIX"
