### ISSUE TITLE
[BUG] 游戏异常退出

### ISSUE THREAD

**Issue by sssssttttttjs** [PojavLauncherTeam/PojavLauncher#3373]
### Describe the bug

在此版本：dahlia-8-f527e8a14-v3_openjdk中
当我将游戏启动后挂在后台时，有很大几率游戏会被异常关闭，返回启动器只是登录界面，没有崩溃报告。
但在之前的版本中我没有遇到这样的问题
就在刚才，我启动游戏、登录服务器后将手机锁屏，解锁屏幕后问题复发

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8905723/latestlog.txt)

### Steps To Reproduce

```markdown
1，启动PojavLauncher
2，启动游戏
3，打开其他软件或将屏幕关闭
```

### Expected Behavior

我希望游戏不会像这样自动关闭

### Platform

```markdown
- Device model: Xiaomi Mi8 6/64
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

**Comment by TWTommyee** [comment]
Summarize English translation:
App got killed after locking the phone then unlock & app closed in background

**Comment by sssssttttttjs** [comment]
> Summarize English translation: App got killed after locking the phone then unlock & app closed in background

yes

**Comment by GaucovyAero** [comment]
Make sure to update your launcher first. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`
