### ISSUE TITLE
[BUG] Sodium doesnt work in 1.17,1.18,1.19

### ISSUE THREAD

**Issue by Nimiey** [PojavLauncherTeam/PojavLauncher#3374]
### Describe the bug

Application Exited with code 1

here is latest log of crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8906746/latestlog.txt)

### Steps To Reproduce

```markdown
Started Pojavlaucher
Runtime is default to 17
renderer holy gl4es
in mods fabric api and 1.19 sodium
started fabric 
game sucessful launched 
joined a server 
stuck at joining world
and then crashed with application game exited with code 1
```

### Expected Behavior

i used a premium account to launch the game and fabric loader 0.14.7 of 1.19

### Platform

```markdown
- Device model: Samsung Galaxy Tab A7
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest playstore version
- Renderer: holy gl4es
```

**Comment by offbeat-stuff** [comment]
it is a known issue
it does not work because pojav launcher actually fakes opengl 3 support

**Comment by offbeat-stuff** [comment]
you could just disable sodium renderer

**Comment by Mathias-Boulay** [comment]
We actually don't declare ogl 3 support lmao

**Comment by ghost** [comment]
> На самом деле мы не заявляем о поддержке ogl 3 lmao

is support planned

**Comment by Nimiey** [comment]
how to disable sodium renderer??

**Comment by Mathias-Boulay** [comment]
#1948
