### ISSUE TITLE
[F-Req] Add panfrost renderer (or driver) to support vulkan and desktop opengl 3.1 for mali gpus

### ISSUE THREAD

**Issue by offbeat-stuff** [PojavLauncherTeam/PojavLauncher#3376]
### Describe the request.

Add [Panfrost](https://docs.mesa3d.org/drivers/panfrost.html) driver to pojav launcher to
add almost native performance for opengl 3.1 in pojavlauncher for mali gpus
specifically add [panvk](https://gitlab.freedesktop.org/panfrost/mesa/-/tree/panvk) for vulkan support which some devices dont have even though their gpus and cpus are compatible
Like honor 6x which did not get a driver update for vulkan

### Anything else?

https://www.collabora.com/news-and-blog/blog/2021/01/13/desktop-opengl-3-1-on-mali-gpus-with-panfrost/

**Comment by offbeat-stuff** [comment]
~~This is panfrost running on a samsung m31 proot distro android
https://youtu.be/aJhV7K80OvQ~~
Sorry about that its just llvm pipe

**Comment by NotAHero04** [comment]
Guess what? Minecraft (at least since 1.17) requires a higher OpenGL version to run.

**Comment by offbeat-stuff** [comment]
well its not just opengl 3.2

**Comment by offbeat-stuff** [comment]
this thing is faster than gl4es and has vulkan support (which my phone manufacturer did not give a update for) (btw it is a mali t830)

**Comment by offbeat-stuff** [comment]
also gl4es supports upto opengl 2.1

**Comment by offbeat-stuff** [comment]
minecraft can run on opengl 3.1
Its only shaders that use opengl 3.2
and the only big feature they use was added in opengl 3.0 which is int
[forcegl20](https://modrinth.com/mod/forcegl20)

**Comment by khanhduytran0** [comment]
> well its not just opengl 3.2

So basically, it won’t run Minecraft 1.17+ without modification.

I think you’re really interested in running a shader ~~like SEUS PTGI E12~~ on it right?

For Vulkan:
- Going through Zink is a nightmare, it’s just too slow to be playable. Although newer Mesa version comes with updated Zink might be a lot faster, who knows if it requires extensions that mobile GPUs don’t support?
- For 1.17+, going through VulkanMod will give you various glitches and random crashes, as of now VulkanMod is known to be buggy on Mesa. Also, does it support Vulkan 1.1?

Another major problem on putting Mesa drivers to an APK: it links with system private libraries, which Android won’t give access anyways, unless there’s a hack around it.

**Comment by offbeat-stuff** [comment]
Not really shaders
I just want performance

**Comment by offbeat-stuff** [comment]
Also my device honor 6x did not get a vulkan driver despite having supported gpu
and with the vulkan mod and the support added for it in latest dev build
I was hoping for a much better performance

**Comment by offbeat-stuff** [comment]
well @khanhduytran0 I could just change the version number in all shaders like pojav had to before
and with this there is no need for changing any code beside version string

**Comment by offbeat-stuff** [comment]
I heard this can be installed in userspace and when i installed it in termux proot did not have any problems

**Comment by mchnjt** [comment]
what

**Comment by yum13241** [comment]
The idea behind this f-req is cool since I have a Mali-G72 and I wish I could use Sodium so the game is playable for once.

**Comment by yum13241** [comment]
A Mali-G7 to be more precise.

**Comment by NotScareBat** [comment]
Yeah I wish the gpu could atleast help with performance I have a Mali-G71

**Comment by yum13241** [comment]
The people, want, PERFORMANCE! Repeat with me lol (semi-joke)

**Comment by GaucovyAero** [comment]
> The people, want, PERFORMANCE! Repeat with me lol (semi-joke)

This is a good suggestion but since im not a programmer, i cant implement support for you guys.

**Comment by yum13241** [comment]
Yeah we know.

**Comment by offbeat-stuff** [comment]
Any updates??

**Comment by yum13241** [comment]
Nope, even through us Mail-G* users really want it lol

**Comment by offbeat-stuff** [comment]
anyone how to compile panfrost for android sdk 24 i could not get it to compile
does anyone have any specific compile instructions
maybe a gitpod workspace that can do that

**Comment by yum13241** [comment]
Nope, I don't know.


Also Android API level 24 is **_android 7.0_**

**Comment by rsc4nevee** [comment]
> Nope, I don't know.
> 
> Also Android API level 24 is **_android 7.0_**

Android versions ≠ Android API level just so you know😄

**Comment by NotScareBat** [comment]
Any updates?

**Comment by offbeat-stuff** [comment]
Does not seem like it
