### ISSUE TITLE
[Feature request] <希望安裝檔有自己獨立的標籤>

### ISSUE THREAD

**Issue by louie1116** [PojavLauncherTeam/PojavLauncher#3377]
### Is this request related to a bug?

希望安裝檔有自己獨立的標籤

I hope the installation file has its own independent label（Google Translate)

### Describe the request.

希望新增：
1.安裝檔編輯
2.安裝檔設定
3.安裝檔圖示
4.設定安裝檔時，能更方便選擇檔案位置

Hope to add:
 1. Installation file editing
 2. Setup file settings
 3. Installation file icon
 4. When setting the installation file, it is easier to choose the file location（Google Translate)

### Anything else?

希望新增：
1.安裝檔編輯
2.安裝檔設定
3.安裝檔圖示
4.設定安裝檔時，能更方便選擇檔案位置

Hope to add:
 1. Installation file editing
 2. Setup file settings
 3. Installation file icon
 4. When setting the installation file, it is easier to choose the file location（Google Translate)

**Comment by TWTommyee** [comment]
Guess what, it already exists

**Comment by louie1116** [comment]
Where
