### ISSUE TITLE
My mojang account stopped working

### ISSUE THREAD

**Issue by Dev0192** [PojavLauncherTeam/PojavLauncher#3378]
### Describe the bug

My mojang account is working before after 10 March it suddenly stopped working today is this can be fixed or I have to migrate

### The log file and images/videos

*

### Steps To Reproduce

```markdown
*
```

### Expected Behavior

*

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

*

**Comment by khanhduytran0** [comment]
Read the [official announcement](https://www.minecraft.net/en-us/article/last-call-voluntarily-migrate-java-accounts):
> Starting March 10, 2022, you won't be able to play Minecraft: Java Edition unless you move to a Microsoft account.

Since we aren't Microsoft, we can do nothing about this.
If you own the account, just go ahead to migrate. Else, you will lose access to it.
