### ISSUE TITLE
[BUG] 1.18 panorama in 1.19

### ISSUE THREAD

**Issue by RedbedMCPojav** [PojavLauncherTeam/PojavLauncher#3379]
### Describe the bug

idk if this is intended or not, but the 1.18 panorama is still in 1.19, if this is a bug then how can i fix?

### The log file and images/videos

![Screenshot_2022-06-16-03-53-19-622_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/173915615-12956360-72b7-4d40-84ff-e73aaab4ebcd.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Open 1.19 (online or local account)
3. The panorama is still the same
```

### Expected Behavior

I expected it to be changed but I guess not

### Platform

```markdown
- Device model: POCO X3 GT 8/256
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: PlayStore Version
```

**Comment by offbeat-stuff** [comment]
send logs

**Comment by GaucovyAero** [comment]
> ### Describe the bug
> idk if this is intended or not, but the 1.18 panorama is still in 1.19, if this is a bug then how can i fix?
> 
> ### The log file and images/videos
> ![Screenshot_2022-06-16-03-53-19-622_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/173915615-12956360-72b7-4d40-84ff-e73aaab4ebcd.jpg)
> 
> ### Steps To Reproduce
> ```gfm
> 1. Start PojavLauncher
> 2. Open 1.19 (online or local account)
> 3. The panorama is still the same
> ```
> 
> ### Expected Behavior
> I expected it to be changed but I guess not
> 
> ### Platform
> ```gfm
> - Device model: POCO X3 GT 8/256
> - CPU architecture: aarch64
> - Android version: 11
> - PojavLauncher version: PlayStore Version
> ```
> 
> ### Anything else?
> _No response_

Are you using a resource pack?

**Comment by NotAHero04** [comment]
Can a panorama affect your actual gameplay?

**Comment by ghost** [comment]
> Can a panorama affect your actual gameplay?


sunset scares him
and autumn grass
instead of green in the mountains

**Comment by RedbedMCPojav** [comment]
@offbeat-stuff 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8916296/latestlog.txt)

**Comment by RedbedMCPojav** [comment]
@Aerolome no I'm not

**Comment by RedbedMCPojav** [comment]
@NotAHero04 no I'm just confused as to why the panorama isn't changed

**Comment by RedbedMCPojav** [comment]
> send logs

hello, any update on what's wrong with my game?

**Comment by GaucovyAero** [comment]
> > send logs
> 
> hello, any update on what's wrong with my game?
```
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.5.41.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:140) ~[authlib-3.5.41.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:47) ~[authlib-3.5.41.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:158) ~[authlib-3.5.41.jar:?]
	at eev.a(SourceFile:677) [1.19.jar:?]
	at eev.<init>(SourceFile:415) [1.19.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:198) [1.19.jar:?]
```
are you on an offline account by any chance?

**Comment by EnderBrine99FOX** [comment]
> ### Describe the bug
> idk if this is intended or not, but the 1.18 panorama is still in 1.19, if this is a bug then how can i fix?
> 
> ### The log file and images/videos
> ![Screenshot_2022-06-16-03-53-19-622_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/173915615-12956360-72b7-4d40-84ff-e73aaab4ebcd.jpg)
> 
> ### Steps To Reproduce
> ```gfm
> 1. Start PojavLauncher
> 2. Open 1.19 (online or local account)
> 3. The panorama is still the same
> ```
> 
> ### Expected Behavior
> I expected it to be changed but I guess not
> 
> ### Platform
> ```gfm
> - Device model: POCO X3 GT 8/256
> - CPU architecture: aarch64
> - Android version: 11
> - PojavLauncher version: PlayStore Version
> ```
> 
> ### Anything else?
> _No response_

Delete The assets folder and re-download it

**Comment by RedbedMCPojav** [comment]
> > ### Describe the bug
> > idk if this is intended or not, but the 1.18 panorama is still in 1.19, if this is a bug then how can i fix?
> > ### The log file and images/videos
> > ![Screenshot_2022-06-16-03-53-19-622_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/173915615-12956360-72b7-4d40-84ff-e73aaab4ebcd.jpg)
> > ### Steps To Reproduce
> > ```
> > 1. Start PojavLauncher
> > 2. Open 1.19 (online or local account)
> > 3. The panorama is still the same
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > I expected it to be changed but I guess not
> > ### Platform
> > ```
> > - Device model: POCO X3 GT 8/256
> > - CPU architecture: aarch64
> > - Android version: 11
> > - PojavLauncher version: PlayStore Version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > _No response_
> 
> Delete The assets folder and re-download it

Ok I'll try it

**Comment by RedbedMCPojav** [comment]
> > > send logs
> > 
> > 
> > hello, any update on what's wrong with my game?
> 
> ```
> com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
> 	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.5.41.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:140) ~[authlib-3.5.41.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:47) ~[authlib-3.5.41.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:158) ~[authlib-3.5.41.jar:?]
> 	at eev.a(SourceFile:677) [1.19.jar:?]
> 	at eev.<init>(SourceFile:415) [1.19.jar:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:198) [1.19.jar:?]
> ```
> 
> are you on an offline account by any chance?

Yes i am but even in an online it still the same

**Comment by GaucovyAero** [comment]
> > > > send logs
> > > 
> > > 
> > > hello, any update on what's wrong with my game?
> > 
> > 
> > ```
> > com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
> > 	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.5.41.jar:?]
> > 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:140) ~[authlib-3.5.41.jar:?]
> > 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:47) ~[authlib-3.5.41.jar:?]
> > 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:158) ~[authlib-3.5.41.jar:?]
> > 	at eev.a(SourceFile:677) [1.19.jar:?]
> > 	at eev.<init>(SourceFile:415) [1.19.jar:?]
> > 	at net.minecraft.client.main.Main.main(SourceFile:198) [1.19.jar:?]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > are you on an offline account by any chance?
> 
> Yes i am but even in an online it still the same

looks like that's your issue

**Comment by RedbedMCPojav** [comment]
> > ### Describe the bug
> > idk if this is intended or not, but the 1.18 panorama is still in 1.19, if this is a bug then how can i fix?
> > ### The log file and images/videos
> > ![Screenshot_2022-06-16-03-53-19-622_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/173915615-12956360-72b7-4d40-84ff-e73aaab4ebcd.jpg)
> > ### Steps To Reproduce
> > ```
> > 1. Start PojavLauncher
> > 2. Open 1.19 (online or local account)
> > 3. The panorama is still the same
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Behavior
> > I expected it to be changed but I guess not
> > ### Platform
> > ```
> > - Device model: POCO X3 GT 8/256
> > - CPU architecture: aarch64
> > - Android version: 11
> > - PojavLauncher version: PlayStore Version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > _No response_
> 
> Delete The assets folder and re-download it

When i deleted the one in the 1.19 jar file it said this, and when i looked it still hasn't redownloaded
![Screenshot_2022-06-18-16-30-07-282_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/174429746-b3830e81-918c-4b21-841a-73664072675a.jpg)
![Screenshot_2022-06-18-16-30-41-027_ru zdevs zarchiver](https://user-images.githubusercontent.com/96370527/174429749-f8358f7a-4823-401b-9e89-0cc0e8893cd0.jpg)

**Comment by GaucovyAero** [comment]
> > > ### Describe the bug
> > > idk if this is intended or not, but the 1.18 panorama is still in 1.19, if this is a bug then how can i fix?
> > > ### The log file and images/videos
> > > ![Screenshot_2022-06-16-03-53-19-622_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/173915615-12956360-72b7-4d40-84ff-e73aaab4ebcd.jpg)
> > > ### Steps To Reproduce
> > > ```
> > > 1. Start PojavLauncher
> > > 2. Open 1.19 (online or local account)
> > > 3. The panorama is still the same
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Expected Behavior
> > > I expected it to be changed but I guess not
> > > ### Platform
> > > ```
> > > - Device model: POCO X3 GT 8/256
> > > - CPU architecture: aarch64
> > > - Android version: 11
> > > - PojavLauncher version: PlayStore Version
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Anything else?
> > > _No response_
> > 
> > 
> > Delete The assets folder and re-download it
> 
> When i deleted the one in the 1.19 jar file it said this, and when i looked it still hasn't redownloaded ![Screenshot_2022-06-18-16-30-07-282_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/174429746-b3830e81-918c-4b21-841a-73664072675a.jpg) ![Screenshot_2022-06-18-16-30-41-027_ru zdevs zarchiver](https://user-images.githubusercontent.com/96370527/174429749-f8358f7a-4823-401b-9e89-0cc0e8893cd0.jpg)

dunno, maybe delete the whole .minecraft folder and redownload again (with an online account of course)

**Comment by RedbedMCPojav** [comment]
> > > > ### Describe the bug
> > > > idk if this is intended or not, but the 1.18 panorama is still in 1.19, if this is a bug then how can i fix?
> > > > ### The log file and images/videos
> > > > ![Screenshot_2022-06-16-03-53-19-622_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/173915615-12956360-72b7-4d40-84ff-e73aaab4ebcd.jpg)
> > > > ### Steps To Reproduce
> > > > ```
> > > > 1. Start PojavLauncher
> > > > 2. Open 1.19 (online or local account)
> > > > 3. The panorama is still the same
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### Expected Behavior
> > > > I expected it to be changed but I guess not
> > > > ### Platform
> > > > ```
> > > > - Device model: POCO X3 GT 8/256
> > > > - CPU architecture: aarch64
> > > > - Android version: 11
> > > > - PojavLauncher version: PlayStore Version
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### Anything else?
> > > > _No response_
> > > 
> > > 
> > > Delete The assets folder and re-download it
> > 
> > 
> > When i deleted the one in the 1.19 jar file it said this, and when i looked it still hasn't redownloaded ![Screenshot_2022-06-18-16-30-07-282_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/174429746-b3830e81-918c-4b21-841a-73664072675a.jpg) ![Screenshot_2022-06-18-16-30-41-027_ru zdevs zarchiver](https://user-images.githubusercontent.com/96370527/174429749-f8358f7a-4823-401b-9e89-0cc0e8893cd0.jpg)
> 
> dunno, maybe delete the whole .minecraft folder and redownload again (with an online account of course)

Ok but if i copy paste my worlds will it still work?

**Comment by GaucovyAero** [comment]
pretty sure yes

**Comment by RedbedMCPojav** [comment]
> > > > ### Describe the bug
> > > > idk if this is intended or not, but the 1.18 panorama is still in 1.19, if this is a bug then how can i fix?
> > > > ### The log file and images/videos
> > > > ![Screenshot_2022-06-16-03-53-19-622_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/173915615-12956360-72b7-4d40-84ff-e73aaab4ebcd.jpg)
> > > > ### Steps To Reproduce
> > > > ```
> > > > 1. Start PojavLauncher
> > > > 2. Open 1.19 (online or local account)
> > > > 3. The panorama is still the same
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### Expected Behavior
> > > > I expected it to be changed but I guess not
> > > > ### Platform
> > > > ```
> > > > - Device model: POCO X3 GT 8/256
> > > > - CPU architecture: aarch64
> > > > - Android version: 11
> > > > - PojavLauncher version: PlayStore Version
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### Anything else?
> > > > _No response_
> > > 
> > > 
> > > Delete The assets folder and re-download it
> > 
> > 
> > When i deleted the one in the 1.19 jar file it said this, and when i looked it still hasn't redownloaded ![Screenshot_2022-06-18-16-30-07-282_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/174429746-b3830e81-918c-4b21-841a-73664072675a.jpg) ![Screenshot_2022-06-18-16-30-41-027_ru zdevs zarchiver](https://user-images.githubusercontent.com/96370527/174429749-f8358f7a-4823-401b-9e89-0cc0e8893cd0.jpg)
> 
> dunno, maybe delete the whole .minecraft folder and redownload again (with an online account of course)

Ok I redownloaded only the 1.19 folder and it worked again (still issue with the panorama tho) 
![Screenshot_2022-06-18-16-39-45-121_ru zdevs zarchiver](https://user-images.githubusercontent.com/96370527/174430065-ea0a000b-4f31-4e04-a407-8fe3d9d3a467.jpg)
![Screenshot_2022-06-18-16-42-22-971_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/174430066-39ba066b-c438-4c3a-b4fa-7d6d4363c421.jpg)

**Comment by GaucovyAero** [comment]
well, and have you downloaded the assets and stuff through pojav or from somewhere else?

**Comment by RedbedMCPojav** [comment]
> well, and have you downloaded the assets and stuff through pojav or from somewhere else?

Through pojav

**Comment by GaucovyAero** [comment]
> > well, and have you downloaded the assets and stuff through pojav or from somewhere else?
> 
> Through pojav

no idea whats the issue then, its working fine for me

**Comment by GaucovyAero** [comment]
what you can maybe do is put in a resource pack with the 1.19 panorama inside if you want to

**Comment by RedbedMCPojav** [comment]
> what you can maybe do is put in a resource pack with the 1.19 panorama inside if you want to

ok where can i get it?

**Comment by GaucovyAero** [comment]
> > what you can maybe do is put in a resource pack with the 1.19 panorama inside if you want to
> 
> ok where can i get it?

well, you have to know how to create resourcepacks, because you're gonna have to download the 1.19 client jar from mcversions.net and copy the resource pack stuff in the jar over to your resource pack, then create a pack.mcmeta and pack.png file, so it's not that easy.

**Comment by RedbedMCPojav** [comment]
> > > what you can maybe do is put in a resource pack with the 1.19 panorama inside if you want to
> > 
> > 
> > ok where can i get it?
> 
> well, you have to know how to create resourcepacks, because you're gonna have to download the 1.19 client jar from mcversions.net and copy the resource pack stuff in the jar over to your resource pack, then create a pack.mcmeta and pack.png file, so it's not that easy.

Hmmm what if i just use the jar from mcversions in pojav?

**Comment by GaucovyAero** [comment]
> > > > what you can maybe do is put in a resource pack with the 1.19 panorama inside if you want to
> > > 
> > > 
> > > ok where can i get it?
> > 
> > 
> > well, you have to know how to create resourcepacks, because you're gonna have to download the 1.19 client jar from mcversions.net and copy the resource pack stuff in the jar over to your resource pack, then create a pack.mcmeta and pack.png file, so it's not that easy.
> 
> Hmmm what if i just use the jar from mcversions in pojav?

i was thinking of that too, but it may as well just get automatically replaced by the original jar, but you can try that, yes

**Comment by RedbedMCPojav** [comment]
> > > > > what you can maybe do is put in a resource pack with the 1.19 panorama inside if you want to
> > > > 
> > > > 
> > > > ok where can i get it?
> > > 
> > > 
> > > well, you have to know how to create resourcepacks, because you're gonna have to download the 1.19 client jar from mcversions.net and copy the resource pack stuff in the jar over to your resource pack, then create a pack.mcmeta and pack.png file, so it's not that easy.
> > 
> > 
> > Hmmm what if i just use the jar from mcversions in pojav?
> 
> i was thinking of that too, but it may as well just get automatically replaced by the original jar, but you can try that, yes

yeah it just redownloaded the 1.19 jar file didn't work

**Comment by GaucovyAero** [comment]
> > > > > > what you can maybe do is put in a resource pack with the 1.19 panorama inside if you want to
> > > > > 
> > > > > 
> > > > > ok where can i get it?
> > > > 
> > > > 
> > > > well, you have to know how to create resourcepacks, because you're gonna have to download the 1.19 client jar from mcversions.net and copy the resource pack stuff in the jar over to your resource pack, then create a pack.mcmeta and pack.png file, so it's not that easy.
> > > 
> > > 
> > > Hmmm what if i just use the jar from mcversions in pojav?
> > 
> > 
> > i was thinking of that too, but it may as well just get automatically replaced by the original jar, but you can try that, yes
> 
> yeah it just redownloaded the 1.19 jar file didn't work

you'll have to do the resource pack thingy then

**Comment by zDominik111** [comment]
@RedbedMCPojav I had the same problem on a Windows OS, but I fixed. I had problems with the new sounds too, so I went to assets folder > indexes folder and deleted 1.19.json. Then I went to versions folder and deleted the 1.19 folder. Then I installed 1.19 again. This worked for me, hope this will work for you too!

**Comment by RedbedMCPojav** [comment]
> @RedbedMCPojav I had the same problem on a Windows OS, but I fixed. I had problems with the new sounds too, so I went to assets folder > indexes folder and deleted 1.19.json. Then I went to versions folder and deleted the 1.19 folder. Then I installed 1.19 again. This worked for me, hope this will work for you too!

Ok I'll try this

**Comment by RedbedMCPojav** [comment]
> @RedbedMCPojav I had the same problem on a Windows OS, but I fixed. I had problems with the new sounds too, so I went to assets folder > indexes folder and deleted 1.19.json. Then I went to versions folder and deleted the 1.19 folder. Then I installed 1.19 again. This worked for me, hope this will work for you too!

It worked, thanks a lot for helping I truly appreciate it <3
![Screenshot_2022-06-21-01-08-47-263_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/174650645-38baf6d4-0f56-4425-9494-548a98b0430a.jpg)
