### ISSUE TITLE
Poor Performance On Alpha 1.1.2_01

### ISSUE THREAD

**Issue by RecorderPro** [PojavLauncherTeam/PojavLauncher#338]
Is there a way to increase performance on this version? I have a low spec android and am trying to make the game some what playable.

**Comment by Malaska678** [comment]
Dont up lay too old version. It cause lag. Playable range 1.7 to 1.8.9.

**Comment by CosineMath** [comment]
So you need a better phone

**Comment by artdeell** [comment]
> Is there a way to increase performance on this version? I have a low spec android and am trying to make the game some what playable.

Tbh, older versions always worked slower due to engine inefficency. I tested - in v2 1.7.10 was running faster than Beta 1.8.
