### ISSUE TITLE
[F-Req] PLAY WITH OFFLINE ACCOUNT

### ISSUE THREAD

**Issue by SergueiKhadirov** [PojavLauncherTeam/PojavLauncher#3382]
### Describe the request.

I see in the latest PojavLAuncher update you added a feature not allowing people with offline accounts only to download and play Minecraft. I legally own Minecraft PE but I don't want to pay again for Minecraft Java, so is there a way I can play Minecraft Java on PojavLauncher without having to buy Minecraft Java ?

**Comment by thesh1xx** [comment]
You can download an older version of the PojavLauncher to continue playing for free.

**Comment by SlowOnARocket** [comment]
Every player that have mcpe have java now :) just jse your mcpe account

**Comment by Jamespoxdxdxd** [comment]
> Every player that have mcpe have java now :) just jse your mcpe account

that aint true lmaoo

**Comment by yum13241** [comment]
It's true for people that bought it on PC very recently.

**Comment by SlowOnARocket** [comment]
Go on mc website my friend who has mcpe have now java for free

**Comment by yum13241** [comment]
Bruh it's not called MCPE anymore.


It's called Bedrock edition (yes ik I'm being pendantic)



Also the offer is only for PC.


Otherwise me, having Bedrock on Switch would have given me Java, but it didn't.

**Comment by kuzy21** [comment]
JUST BUY JAVA YOU PIRATES

**Comment by Mathias-Boulay** [comment]
You better see with Microsoft with this issue 😆

**Comment by ghost** [comment]
> JUST BUY JAVA YOU PIRATES

Java owned by orache
They will sell it???

**Comment by ghost** [comment]
> You can download an older version of the PojavLauncher to continue playing for free.

No support for this

**Comment by InfiniXDerg** [comment]
![862691562814570518](https://user-images.githubusercontent.com/75786233/174490636-467ae6d4-dc5d-42c5-85ed-2bbb161be90c.png)

**Comment by ghost** [comment]
> ![862691562814570518](https://user-images.githubusercontent.com/75786233/174490636-467ae6d4-dc5d-42c5-85ed-2bbb161be90c.png)

@khanhduytran0 
![Screenshot_20220619-233801_Discord](https://user-images.githubusercontent.com/70785472/174491337-35248326-a01b-4106-a71e-800a86b9e422.png)

**Comment by ABJ4403** [comment]
> Mathias-Boulay commented:
> You better see with Microsoft with this issue :laughing:

Can you explain why offline login was removed? is it because you got Cease and Desist letter from Microsoft?

**Comment by mchnjt** [comment]
> > Mathias-Boulay commented:
> > You better see with Microsoft with this issue 😆
> 
> Can you explain why offline login was removed? is it because you got Cease and Desist letter from Microsoft?

We don't wanna talk about an issue that's been resolved months ago.
You can ask @crystall1nedev for it.
