### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Askkqmq** [PojavLauncherTeam/PojavLauncher#3383]
### Describe the bug

Forge 1.7.10 crashes

### The log file and images/videos

Crash

### Steps To Reproduce

```markdown
Start Pojavlauncher
Start Forge 1.7.10
Crash in black screen
```

### Expected Behavior

I expect that crash forge

### Platform

```markdown
- Device model:Honor 8S/32G
- CPU architecture:aarch64
- Android version:9
- PojavLauncher version:Latest Release crocus-93-14dcf9993-v3_openjdk
```

### Anything else?

Forge 1.7.10 start it crash

**Comment by GaucovyAero** [comment]
crocus-93, man that's old. We are already on dahlia-15, and crocus pojav ends at crocus-590-something iirc. I recommend you to update to dahlia-8, which is already present on Google Play Store and contains a bunch of bugfixes.

**Comment by Askkqmq** [comment]
You're a motherfucker with pojavlauncher debug

чт, 16 июн. 2022 г., 15:16 Aerolome ***@***.***>:
