### ISSUE TITLE
Textures being half transparent

### ISSUE THREAD

**Issue by Lewyfcb9pro** [PojavLauncherTeam/PojavLauncher#3385]
### Describe the bug

When I started the game nothing happened but when I joined a world caves were visible through blocks tile entities were completely broken

### The log file and images/videos

There is no log and the video is on YouTube because it's too big to upload onto github

### Steps To Reproduce

```markdown
Start pojavlauncher on latest google play version

Join a world

See the bug and close the game
```

### Expected Behavior

I expect the texture to render properly

### Platform

```markdown
- Device model:          Redmi note 10 pro
- CPU architecture:      no idea
- Android version:       12
- PojavLauncher version: latest google play
```

### Anything else?

https://youtu.be/TRrgpMA1_4Y

Here is a link to my YouTube video because the file is to big

**Comment by GaucovyAero** [comment]
> ### Describe the bug
> 
> When I started the game nothing happened but when I joined a world caves were visible through blocks tile entities were completely broken
> ### The log file and images/videos
> 
> There is no log and the video is on YouTube because it's too big to upload onto github
> ### Steps To Reproduce
> 
> ```gfm
> Start pojavlauncher on latest google play version
> 
> Join a world
> 
> See the bug and close the game
> ```
> 
> ### Expected Behavior
> 
> I expect the texture to render properly
> ### Platform
> 
> ```gfm
> - Device model:          Redmi note 10 pro
> - CPU architecture:      no idea
> - Android version:       12
> - PojavLauncher version: latest google play
> ```
> 
> ### Anything else?
> 
> https://youtu.be/TRrgpMA1_4Y
> 
> Here is a link to my YouTube video because the file is to big

Just press F11 a couple of times and see if that fixes it. Known issue.

**Comment by Lewyfcb9pro** [comment]
Will Test it at home

**Comment by SlowOnARocket** [comment]
If it's more than 1.8 try Virgil renderer

**Comment by NotScareBat** [comment]
Try turning fast render on with optifine but idk ab other performance mods like sodium

**Comment by GaucovyAero** [comment]
> If it's more than 1.8 try Virgil renderer

No, definitely don't try VirGL, it's definitely much slower than gl4es. Just press F11 and you have a fix.

**Comment by Lewyfcb9pro** [comment]
works after pressing f11 but if I accidentally press it a second time it goes to a small picture in the bottom left corner and breaks the textures the it goes to fullscreen with still broken texture and so on but after pressing once it works normally so thanks
