### ISSUE TITLE
[BUG] all render types are broken  holy and virgl 1.19

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3386]
### Describe the bug

No text and black texture in game
![Screenshot_20220616-221522_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/80956290/174119929-76a7db83-addc-418d-97fa-e157788ee2df.jpg)

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8920692/latest.log)

### Steps To Reproduce

```markdown
launch the game and select the holy - virgl render
to enter the world with holy
to increase the drawing range to 8 
and turn on the clouds

for virgl
, launch the game and go to the menu
, then go into the world and see the broken textures
```

### Expected Behavior

Normal grupchics 
And perfomance

### Platform

```markdown
- Device model: Galaxy tab s7
- CPU architecture: Snapdragon 865 plus
- Android version: 12
- PojavLauncher version latest build
```

### Anything else?

Holy broken
![Screenshot_20220616-222544_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/80956290/174119768-e365209b-d993-4847-a42b-9fd3962714f4.jpg)
![Screenshot_20220616-222435_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/80956290/174119804-de377631-36ef-42d3-bb88-e762c07850d3.jpg)
![Screenshot_20220616-222357_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/80956290/174121125-e80fd473-2d71-4b2f-9d2c-9ddeeec3545e.jpg)
![Screenshot_20220616-222411_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/80956290/174121143-39cc91e7-9106-463c-8c97-46d59c9b1287.jpg)

**Comment by offbeat-stuff** [comment]
please use the latest version
the one from google play will do

**Comment by offbeat-stuff** [comment]
please send latestlog.txt which contains the actual version you re playing

**Comment by ghost** [comment]
> please use the latest version the one from google play will do

and I wrote that from action
that from google play the effect is the same

**Comment by furai** [comment]
I get the same issue. It happens on java 17. On java 8 it works properly.

**Comment by WesleyVanNeck** [comment]
Give latestlog.txt or no help will be provided

**Comment by furai** [comment]
I understand. As developer you need it. Though I can't provide it right now as I have uninstalled it right away. I was just curious how it works. 

If I ever get back to it I'll send you the logs!
