### ISSUE TITLE
[F-Req] let us configure the gamepad bindings.

### ISSUE THREAD

**Issue by yum13241** [PojavLauncherTeam/PojavLauncher#3387]
### Is this request related to a bug?

On my Nintendo Switch Pro Controller, the binds are messed up. Push right stick down to mine, ZL and ZR do nothing, can't even look around, many problems like that.

### Describe the request.

A way to change the gamepad bindings.

### Anything else?

Also, you can't edit instances in the version picker which is sad.

**Comment by yum13241** [comment]
Oh and btw, the weird bindings are there even in vanilla mc.

**Comment by offbeat-stuff** [comment]
you can use https://modrinth.com/mod/lambdacontrols

**Comment by yum13241** [comment]
But I might want to play an old versions or use forge on older versions. So the problem isn't really solved, also mods take time to update lol.

Edit: there isn't even a 1.19 version lol

**Comment by GaucovyAero** [comment]
> But I might want to play an old versions or use forge on older versions. So the problem isn't really solved, also mods take time to update lol.
> 
> Edit: there isn't even a 1.19 version lol

there is :D

**Comment by offbeat-stuff** [comment]
well it is a workaround
not a full solution
you can also use some keymapper apk to bind gamepad keys to keyboard keys
or other hacky tricks

**Comment by yum13241** [comment]
Keymapper apps cause input lag, what I want is a native solution within PojavLauncher itself. 



Whoever thought these default bindings were good needs a spit in the face.




I don't want to play one direction Minecraft, I want to be able to look in all directions, this isn't classic doom, at least in classic Doom I could look around horizontally! And with source ports I can look up and down as well.




Wow. Just wow.

**Comment by yum13241** [comment]
> > But I might want to play an old versions or use forge on older versions. So the problem isn't really solved, also mods take time to update lol.
> > Edit: there isn't even a 1.19 version lol
> 
> there is :D

If you count MidnightControls, which is a fork of LambdaControls (man I don't understand the obsession of having to have at least one thing have the word lambda in it) then yes. And lo and behold! Does nothing to solve my woes. Also, did you know some people play vanilla? Or they play old versions?

**Comment by GaucovyAero** [comment]
If I remember correctly, there is a Magisk (root) module that lets you rebind the controller mappins, dunno how it's called tho, never used Magisk.

**Comment by GaucovyAero** [comment]
closing as this is a duplicate

**Comment by Maritako** [comment]
> well it is a workaround not a full solution you can also use some keymapper apk to bind gamepad keys to keyboard keys or other hacky tricks

I tried this, but pojav doesn't seem to recognize my input.

**Comment by GaucovyAero** [comment]
> > well it is a workaround not a full solution you can also use some keymapper apk to bind gamepad keys to keyboard keys or other hacky tricks
> 
> I tried this, but pojav doesn't seem to recognize my input.

rip

**Comment by Maritako** [comment]
> > > well it is a workaround not a full solution you can also use some keymapper apk to bind gamepad keys to keyboard keys or other hacky tricks
> > 
> > 
> > I tried this, but pojav doesn't seem to recognize my input.
> 
> rip

what is "rip"?

**Comment by yum13241** [comment]
Rest In Peace.

**Comment by kunaoyongyuanding** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我现在正在工作/学习中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
