### ISSUE TITLE
[F-Req] Add a Modpack Installer

### ISSUE THREAD

**Issue by Gabbyph12** [PojavLauncherTeam/PojavLauncher#3388]
### Is this request related to a bug?

No

### Describe the request.

I want to download boosted fps Modpack 1.18 but it requires curse forge Modpack Installer plss make a Modpack Installer 

And I'm sorry to Mathias Boulay for many request
Sorry For My Bad English

**Comment by yum13241** [comment]
Try the fabulously optimized modpack, but get rid of all sodium related mods, including sodium.

**Comment by offbeat-stuff** [comment]
he is not able to install modpacks

**Comment by offbeat-stuff** [comment]
@Gabbyph12 the modpack is a zip just extract it

**Comment by offbeat-stuff** [comment]
https://github.com/cdbbnnyCode/modpack-installer
you can use this

**Comment by offbeat-stuff** [comment]
or you can use modrinth modpacks
just unzip it
then run the command
```bash
cat modrinth.index.json | grep https | xargs wget
```
to download all the jars

**Comment by GaucovyAero** [comment]
added in the latest actions build
