### ISSUE TITLE
I can't see my texturrpack in Minecraft 

### ISSUE THREAD

**Issue by Oreomial** [PojavLauncherTeam/PojavLauncher#3389]
### Describe the bug

I instal and put my txt to PojavLauncher->.minecraft->rescorpacks, but when I open settings->rescourepack(in Minecraft) I can't see anywhere my texturepacks from PojavLauncher->.minecraft->rescoruepack.

I put my txt to PojavLauncher-> .Minecraft -> texturepacks but that  not work 

Please help and sorry for my english.

### The log file and images/videos

![Screenshot_2022-06-17-14-12-51-156_com mi android globalFileexplorer](https://user-images.githubusercontent.com/106767901/174300301-f9251328-6dce-48f0-984b-3c9e052cd9bd.jpg)
![Screenshot_2022-06-17-14-12-06-912_net kdt pojavlaunch](https://user-images.githubusercontent.com/106767901/174300307-13bf64f7-62c1-4231-8a58-0c8312bf7141.jpg)

### Steps To Reproduce

```markdown
1. Install aby put txt to games->PojavLauncher->.minecraft->rescourepacks

2. Open PojavLaucher and launch Minecraft(txt and Minecraft -> version 1.18.2)

3. Open in Minecraft settings and rescoure packs
```

### Expected Behavior

In settings->rescourepacks is my txt.

### Platform

```markdown
- Device model: Xami Redmi Note 8t/4GB
- CPU architecture: aarch64
- Android version: lastet release
- PojavLauncher version: lastet release
```

### Anything else?

I instal xray.

**Comment by EnderBrine99FOX** [comment]
Try To Extract it And Make Sure you See all the folder inside and Compess it again

**Comment by offbeat-stuff** [comment]
also make sure your profile directory is .minecraft

**Comment by Oreomial** [comment]
> Try To Extract it And Make Sure you See all the folder inside and Compess it again

Not work :(

**Comment by Oreomial** [comment]
> also make sure your profile directory is .minecraft

games->PojavLauncher->.minecraft ?

**Comment by GaucovyAero** [comment]
> > also make sure your profile directory is .minecraft
> 
> games->PojavLauncher->.minecraft ?

what android version are you on? also, could you send the resource packs here?

**Comment by Oreomial** [comment]
> > > also make sure your profile directory is .minecraft
> >> 
> > games->PojavLauncher->.minecraft ?
> 
> what android version are you on? also, could you send the resource packs here?
>
Android -> 11
Rescoure packs (from curseforage)-> https://www.curseforge.com/minecraft/texture-packs/xray-ultimate-1-11-compatible/download/3763778
