### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Alreynn** [PojavLauncherTeam/PojavLauncher#339]
This happened while you're playing on a server. It automatically crashes if the Chunks (maybe) didn't loaded in a server or the server had too much plugins used at once. Don't forget to reduce the fps to make it more like MCinaBox!

**Comment by artdeell** [comment]
Since the Minecraft JE on android is always kinda unstable, you should probably expect crashes if server's got many plugins.

**Comment by khanhduytran0** [comment]
V2 or v3?

Also
>  Don't forget to reduce the fps to make it more like MCinaBox!

Do you mean make performance worse to make similar to mcinabox?
