### ISSUE TITLE
[F-Req] Samsung Game Launcher Support

### ISSUE THREAD

**Issue by NotScareBat** [PojavLauncherTeam/PojavLauncher#3390]
### Is this request related to a bug?

You should make  pojavlauncher  be detected as a game to access game launcher features like priority mode or screen recording 

### Describe the request.

•Pojavlauncher being detected as a game by samsung game launcher

### Anything else?

Game launcher has acces to stuff like killing background apps when playing or clearing ram so I'd like to use it for pojavlauncher as it would be great use

**Comment by yum13241** [comment]
I support this. The amount of times I see the not enough RAM message is annoying ah.

**Comment by ghost** [comment]
++++++++++++++++

**Comment by offbeat-stuff** [comment]
I think it depends on the category of the app on playstore
so it probably will only work for latest dahlia update on gplay

**Comment by thegarykun** [comment]
ever of GOS (Game Optimizating Service)? it decreases the game's performance to keep your phone cool. 'IF' pojav heats your phone a little bit, it will reduce performance by 10% (or in the worst case scenario, it will decrease 25%)

GOS only works on games recognized by Game Launcher

**Comment by GaucovyAero** [comment]
but it would be pretty cool if there was a slider setting for performance in the launcher, because me and my friend have both the same phones (Galaxy S7 Edge), but im running Lineage 19.1 (Android 12) and hes running Touchwiz (Android 8.0.0):
My phone:
Sustained performance mode off: 85°C+
Sustained performance mode on: 70-75°C
His phone:
Gaming mode (i think it does the same as GOS) 35-40°C with almost the same performance as me.

**Comment by thegarykun** [comment]
> but it would be pretty cool if there was a slider setting for performance in the launcher, because me and my friend have both the same phones (Galaxy S7 Edge), but im running Lineage 19.1 (Android 12) and hes running Touchwiz (Android 8.0.0): My phone: Sustained performance mode off: 85°C+ Sustained performance mode on: 70-75°C His phone: Gaming mode (i think it does the same as GOS) 35-40°C with almost the same performance as me.

wait what samsung gaming mode is for TVs 💀 :wtfman:

**Comment by yum13241** [comment]
It's a different thing, now stop being a jerk with the skull emoji.

**Comment by NotScareBat** [comment]
Gaming mode has features like priority mode and opening discord/other apps while in game it also has discord status thingy which I like
![Screenshot_20220513-205622_Discord-Beta](https://user-images.githubusercontent.com/90552670/174473443-a6709bd0-728f-486f-b547-c031b8262f08.jpg)
You can also download addons that help with performance like app killers or ram cleaners or my favourite the game booster which has this 
![Screenshot_20220619-110231_Game Booster](https://user-images.githubusercontent.com/90552670/174473635-ecffec4f-5396-4f23-97da-9b2092539912.jpg)
You can turn on focus on performance for better framerates but only available for those classified as games by the game launcher

**Comment by thegarykun** [comment]
![unknown](https://user-images.githubusercontent.com/86944088/174502005-1df82c29-8136-4c89-b15d-9a4369e0bd91.png)

also GOS:

**Comment by GaucovyAero** [comment]
should be working now, pojav is marked as a game
