### ISSUE TITLE
[BUG] <Terrain Textures  (Virgl) 1.18.2>

### ISSUE THREAD

**Issue by JEXCRAFTER57177** [PojavLauncherTeam/PojavLauncher#3392]
### Describe the bug

some terrain textures turns on black or solid plain color textures kinda look like png format only affected is terrain textures, which is tall grass, sea grass, grass blocks dirt part of Grass block turn on black texture

sugarcane block bordered with white
![Screenshot_2022-06-17-12-46-51-04](https://user-images.githubusercontent.com/104181203/174440028-b6450fe6-fb3b-49e5-b264-2cb623ae8641.jpg)

and also all i mentioned I don't have many screenshots

### The log file and images/videos

![Screenshot_2022-06-17-12-48-24-59](https://user-images.githubusercontent.com/104181203/174439979-745c2d77-ebc4-4cb4-a2b8-ace91a0a9319.jpg)
![Screenshot_2022-06-17-12-47-21-99](https://user-images.githubusercontent.com/104181203/174439984-9e8549a8-942e-490e-a40b-35f87eed8436.jpg)
![Uploading Screenshot_2022-06-17-12-48-24-59.jpg…]()

### Steps To Reproduce

```markdown
i need support for my Android version , thanks
```

### Expected Behavior

read : unexpected eof warning on log :v

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: CPH2083/Octa-core processor
/Mediatek
- Android version: 9
- PojavLauncher version: playstore version
```

**Comment by GaucovyAero** [comment]
this may be caused by your Mediatek processor. Do you get any errors when you load up the shader?

**Comment by JEXCRAFTER57177** [comment]
> 

otherwise i dont get any error loading the shader, i know some features of shaders can crash anyway everything looks fine

**Comment by GaucovyAero** [comment]
alright, maybe you could try reverting to default settings in optifine?

**Comment by JEXCRAFTER57177** [comment]
> alright, maybe you could try reverting to default settings in optifine?

optifine? bugs still appears even use optifine or add custom resource packs i used it to replace terrain textures but it's still turns on same results still bugged

**Comment by JEXCRAFTER57177** [comment]
> maybe you could try reverting to default settings in optifine?   ( how?? can u teach me? interesting)

**Comment by GaucovyAero** [comment]
> > maybe you could try reverting to default settings in optifine?   ( how?? can u teach me? interesting)

in other settings, there is a reset button

**Comment by Iarkont** [comment]
Lol, here the shader works more or less normally you would see what is happening on kirin processors on them in general everything is bad: weak shaders of the makeup ultra-fast type are drawn poorly and with errors and shaders complamentary, seus and so on simply do not start. But with the zink renderer which the developers pojavlauncher consider garbage with kirin processors works fine and runs many shaders without errors.

**Comment by Cube5x59999** [comment]
> Lol, here the shader works more or less normally you would see what is happening on kirin processors on them in general everything is bad: weak shaders of the makeup ultra-fast type are drawn poorly and with errors and shaders complamentary, seus and so on simply do not start. But with the zink renderer which the developers pojavlauncher consider garbage with kirin processors works fine and runs many shaders without errors.

fkr Zink renderer, try older version of pojav

**Comment by Iarkont** [comment]
> 

I'm already on version 3.3.1.1 just because there's zink and gl4es 1.1.5 (gl4es 1.1.5 I need for full functionality mods such as xareos mini map on holy gl4es not displayed mini map) but i wanted to upgrade to the latest version of pojavlauncher but due to the lack of these two renders I am unlikely to switch

**Comment by Iarkont** [comment]
> > Lol, here the shader works more or less normally you would see what is happening on kirin processors on them in general everything is bad: weak shaders of the makeup ultra-fast type are drawn poorly and with errors and shaders complamentary, seus and so on simply do not start. But with the zink renderer which the developers pojavlauncher consider garbage with kirin processors works fine and runs many shaders without errors.
> 
> fkr Zink renderer, try older version of pojav

Yes, but version 3.3.1.1 is already a year old. And I do not understand the developers: why support only certain processors, why could not just leave the same zink and gl4es 1.1.5 because virgl works well only on snapdragon and holy gl4es, although it runs any versions, but has a drawback in drawing mod elements

**Comment by USMP-lancer** [comment]
bro i got snapdragon proc and still have issue with virgl
