### ISSUE TITLE
[BUG] crash open4es Shader 1.18

### ISSUE THREAD

**Issue by Pojavhelppls** [PojavLauncherTeam/PojavLauncher#3394]
### Describe the bug

It shows Application exited  if u try to load open4es Shader in 1.18

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8935760/latestlog.txt)

### Steps To Reproduce

```markdown
Start 1.18
Load open4es Shader
Game crashes
```

### Expected Behavior

Ya

### Platform

```markdown
- Device model: realme8s 5g
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: GitHub
```

### Anything else?

Noooooo

**Comment by Cube5x59999** [comment]
try holy gl4es or virglrenderer (im not a developer, just trying to help)

**Comment by Pojavhelppls** [comment]
I tried holy

**Comment by Pojavhelppls** [comment]
Is there any open4es shader for 1.18  holy gl

**Comment by GaucovyAero** [comment]
Yeah, I guess it broke. Try contating the Open4ES developer, ENDERMANYK on the official PojavLauncher discord server.
