### ISSUE TITLE
[BUG] crashed when i go to my world on fabric (with mod sodium, lithium and phosphor) and i have lincense

### ISSUE THREAD

**Issue by dontuo** [PojavLauncherTeam/PojavLauncher#3395]
### Describe the bug

exited with error code -1

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8936340/latest.log)

### Steps To Reproduce

```markdown
1. Start PojLaunc.
2. Log in
3. press button 'play'
4. go to world
5. game crashed
```

### Expected Behavior

if i delete the mods game is not crashed

### Platform

```markdown
- Device model: Poco x3 pro
- CPU architecture: Arm
- Android version: 11
- PojavLauncher version: latest from playmarket
```

### Anything else?

if i delete the mods game not crashed
i use gl4es but if choose virglrenderer then I have no text, but it starts with mods

**Comment by dontuo** [comment]
Expected Behavior: yes

**Comment by thegarykun** [comment]
> Steps To Reproduce
> 1. Start PojLaunc.
bro what

**Comment by dontuo** [comment]
> > Steps To Reproduce
> > 1. Start PojLaunc.
> bro what

Start pojav launcher

**Comment by vanistillhere** [comment]
PJ Kids <:HYPERROFEL:862691562814570518>

**Comment by dontuo** [comment]
> PJ Kids <:HYPERROFEL:862691562814570518>

??
