### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by BeastyCoke** [PojavLauncherTeam/PojavLauncher#3396]
### Describe the bug

 so i deleted everything in the game folder and i opened up a new one in the android folder without copying and the game wouldnt let me enter it just keep crashin up a new one in the android folder without copying and the game wouldnt let me enter it just keepg. 

### The log file and images/videos

![Screenshot 2022-06-20 13 22 02](https://user-images.githubusercontent.com/105903249/174530593-54890577-cdc8-4c87-9567-c35cc2ed6e5c.png)
![Screenshot 2022-06-20 13 06 48](https://user-images.githubusercontent.com/105903249/174530624-18a30174-8b47-4525-b8aa-ec391e009d46.png)

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

i expected the game to launch

### Platform

```markdown
- Device model: Chromebook
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Lastest
```

**Comment by GaucovyAero** [comment]
send /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

**Comment by BeastyCoke** [comment]
i realised it only crashed on 1.16.5 so... ye
