### ISSUE TITLE
[BUG] game crashed when i join world

### ISSUE THREAD

**Issue by Nisarg1102** [PojavLauncherTeam/PojavLauncher#3400]
### Describe the bug

![Screenshot_20220622-192135_Gallery](https://user-images.githubusercontent.com/108039095/175189851-99873c38-f4b5-4106-9168-dd0370f65725.jpg)
This is the last log which is shown .please help me when I join world it crash.

### The log file and images/videos

![Screenshot_20220622-192135_Gallery](https://user-images.githubusercontent.com/108039095/175190852-f6521ffe-0cba-4319-a20d-01d423d684b6.jpg)

### Steps To Reproduce

```markdown
Start PojavLauncher then I when I join world it crash
```

### Expected Behavior

It crash when I try to join

### Platform

```markdown
- Device model:samsunggalaxys21
- CPU architecture:aarch64
- Android version:12
-PojavLauncher version:3.3.1_rel_20210117
```

**Comment by offbeat-stuff** [comment]
please send the log file next and
just update the pojav launcher it will work

**Comment by Nisarg1102** [comment]
I have try in all version it crash

**Comment by Nisarg1102** [comment]
Every time last log is elf_dynamic_array_reader.h (64) tag not found

**Comment by GaucovyAero** [comment]
> Every time last log is elf_dynamic_array_reader.h (64) tag not found

Try a version lower than Beta 1.7.3 (b1.7.3). Or just update Pojav.

**Comment by Nisarg1102** [comment]
OK I will try if not work then message thanks

**Comment by GaucovyAero** [comment]
> OK I will try if not work then message thanks

The issue has been resolved.
Make sure to update your launcher. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`
