### ISSUE TITLE
[bedrock edition like the new update] <There is a new minecraft launcher update called version changer in it the minecraft launcher has both bedrock and java edition can you do the same>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3401]
### Is this request related to a bug?

No it's not related to a bug

### Describe the request.

Version switcher like the new minecraft launcher. You can play both java and bedrock edition

**Comment by offbeat-stuff** [comment]
nope just play bedrock on phone it is on play store

**Comment by offbeat-stuff** [comment]
why do you need it in game.
Well It is a super easy programming task to add a button for that but you could just go in app launcher and open the game there

**Comment by ghost** [comment]
> nope just play bedrock on phone it is on play store

Isn't the pocket edition is a paid game and now bedrock edition is free to play if you own minecraft java

**Comment by ssthunderyt** [comment]
> 

There isn't a option to play bedrock edition in pojav launcher rn

**Comment by ghost** [comment]
> why do you need it in game. Well It is a super easy programming task to add a button for that but you could just go in app launcher and open the game there

There isn't a option to play bedrock edition in pojav launcher right now

**Comment by offbeat-stuff** [comment]
yeah i dont think pojav launcher has the authority to provide that feature

**Comment by khanhduytran0** [comment]
> It is a super easy programming task to add a button

It’s easy if the added button has no function.
Then how can it be functional?

@ssthunderyt 
Looks like you’re requesting support for ability to launch Minecraft Bedrock (Windows 10/11), which has no point. If we could do it, Minecraft Dungeons would run aswell (both require DirectX 11, which is what Android doesn’t have)
