### ISSUE TITLE
[F-Req] Please Add Support IPv6 Address

### ISSUE THREAD

**Issue by dttzyjw0012** [PojavLauncherTeam/PojavLauncher#3402]
### Is this request related to a bug?

No

### Describe the request.

Some servers are running on IPv6 address only. And create a small self-use server by IPv6 was more convenient than by IPv4. But this software unsupported  IPv6 address. In the issue #2854 , Smokeybear12 says Minecraft does not have this feature. But I try it in Windows 10, it works. So Please Add Support IPv6 Address.

### Anything else?

I also found another way to using IPv6 in PojavLauncher. Just using socat in termux by command that "socat -d -d TCP4-LISTEN:25565,reuseaddr,fork TCP6:[2408:8210::8891]:25565".(Using your server ip and port to replace the [2408:8210::8891]:25565). Then enter 127.0.0.1 as server ip in your game. But in some android roms, termux will kill by system after some minites. So add support iPv6 natively is still important.

**Comment by unilock** [comment]
Surrounding the IPv6 address with brackets should work, no? A la:
```
[2001:0DB8:AC10:FE01:0000:0000:0000:0000]:25565
```
(in the "Server Address" field)

> But I try it in Windows 10, it works.

Java Edition or Bedrock Edition? (may be unrelated)

> termux will kill by system after some minites.

Have you tried using Termux's "Acquire wakelock" functionality?
(Off-topic, I know.)

**Comment by dttzyjw0012** [comment]
> Surrounding the IPv6 address with brackets should work, no? A la:
> 
> ```
> [2001:0DB8:AC10:FE01:0000:0000:0000:0000]:25565
> ```
> 
> (in the "Server Address" field)

By this way, it works in Windows 10 but doesn't work in PojavLauncher.

> > But I try it in Windows 10, it works.
> 
> Java Edition or Bedrock Edition? (may be unrelated)

My version is Java 1.16.5.

> > termux will kill by system after some minites.
> 
> Have you tried using Termux's "Acquire wakelock" functionality? (Off-topic, I know.)

I tried, but it didn't work on some Chinese devices.

**Comment by GaucovyAero** [comment]
nope
