### ISSUE TITLE
The game crashes when joining a world while sodium is installed on fabric 1.19

### ISSUE THREAD

**Issue by Nathan22211** [PojavLauncherTeam/PojavLauncher#3404]
### Describe the bug

I get error code -1. Probs due to sodium being incompatible with the renderer I'm using, holy 4gles.

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8980089/latest.log)

### Steps To Reproduce

```markdown
1. Start the game with fabric installed and sodium, or its forge port I guess as well. Make sure your using the holy gl4es renderer.
2.create a new world or load up a existing one.
The crash should occur
```

### Expected Behavior

The world should load (with better performance I might add)

### Platform

```markdown
- Device model: lenovo flex 5 (chromebook) and Samsung s22 ultra (phone, could be the version with Samsung's cpu as it's a US device)
- CPU architecture: x86_64 (chromebook) and aarch64 (phone)
- Android version: not sure about the chromebook (v102 of chromeOS) but the phone is Android 12
- PojavLauncher version: dahalia-8(some random text)-v3-openjdk. (I'm not going to try to type all of that random text on my phone... But i did install the app the day I submitted this)

Note that I tested 2 devices thinking it was a architecture issue.
```

### Anything else?

Haven't tried the forge port of sodium yet, nor canvas

**Comment by miggythewriter** [comment]
Sodium for 1.19 only works with virgl

**Comment by Jerald1009m** [comment]
Just delete a mod expect sodium to prevent crash

**Comment by miggythewriter** [comment]
> Just delete a mod expect sodium to prevent crash

Sodium is the one that is crashing it will only work with virgl

**Comment by Nathan22211** [comment]
Probs will put this in a separate issue later, but I recall Sodium with VIrgl not loading text in 1.19

**Comment by AlirezaParsi** [comment]
i have Same problem and when i use virgl for render texts not showing ...

**Comment by khanhduytran0** [comment]
@Nathan22211 I believe Sodium requires OpenGL 4, which gl4es doesn’t support.

**Comment by ElijahCoder** [comment]
i also tried vlrgl didnt work

**Comment by GaucovyAero** [comment]
> i also tried vlrgl didnt work

even though sodium should run on virgl, it definitely does not boost fps that much (because virgl with sodium is slower than gl4es on vanilla)
