### ISSUE TITLE
Gamepad keys not working properly

### ISSUE THREAD

**Issue by Manuel11243** [PojavLauncherTeam/PojavLauncher#3405]
### Describe the bug

When I connect a Gamepad to my device and enter some version of Minecraft, only some buttons work and many don't work

### The log file and images/videos

.

### Steps To Reproduce

```markdown
Connect a Gamepad and play minecraft
```

### Expected Behavior

The controller works perfectly

### Platform

```markdown
- Device model: Huawei nova 5T
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: GP
```

**Comment by GaucovyAero** [comment]
Please list the exact gamepad brand and model so we can maybe get it working in the future. The only supported gamepad is the official Xbox controller.

**Comment by DanerCampa** [comment]
Cualquier Gamepad Generico no funciona en las anteriores versiones si funcionaban estos mandos

**Comment by GaucovyAero** [comment]
> Cualquier Gamepad Generico no funciona en las anteriores versiones si funcionaban estos mandos

Well, because only the Xbox controller is supported by PojavLauncher, the only thing you can do to remap your controller buttons is to root your phone with Magisk and install a Magisk module that can remap your controller buttons.
