### ISSUE TITLE
[F-Req] <Streamcraft>

### ISSUE THREAD

**Issue by Waxbyz** [PojavLauncherTeam/PojavLauncher#3407]
### Is this request related to a bug?

I can't download Streamcraft in pojavlauncher 

### Describe the request.

I can't download Streamcraft in pojavlauncher

### Anything else?

Help me please

**Comment by GaucovyAero** [comment]
Okay, so... There was tutorial made on the PojavLauncher discord server on how to install CurseForge modpacks. Here it is:

--------------------------------------------------------------
**1. - Installation & setup** 
--------------------------------------------------------------

Download and install the Termux app from Google Play, GitHub or F-Droid.
In the Termux app, type in these commands one by one, line by line. Type Y and press enter at prompts. Install `pkg` after you have completed the `termux-setup-storage` command and turned on storage permissions for Termux.

```
termux-setup-storage
pkg install openjdk-17
pkg install wget
pkg install unzip 
pkg update && apt upgrade -y
wget https://github.com/North-West-Wind/CurseForge-CLI/releases/latest/download/curseforge.zip 
unzip curseforge.zip
```

Everything before this only has to be done to setup Termux, everything after this can be done whenever you use Termux again...

--------------------------------------------------------------
**2. - Modpack download and installation**
--------------------------------------------------------------
For this, you will first need the Project ID, it can be found on CurseForge on the right side of your screen. Every modpack has a different Project ID, it should look like this:

![image](https://user-images.githubusercontent.com/85581164/188115948-7e9fa971-7311-4068-b7b2-3ab71adefda8.png)

```
./curseforge modpack install (project-id) 
cd curseforge-cli/modpack
ls
```
The `ls` command should list your modpack downloaded. Now you have to zip your modpack, so do this: 
```
zip {modpack name u want}.zip -r {modpack name in blue in ls}
```
For example, `zip rlcraft.zip -r rlcraft-modpack_405838 `. Then type in `ls` again and it should have your zipped modpack listed in white color. Then do this, and you should have your modpack in the Downloads folder.
```
cp {name in white in ls}.zip ~/storage/emulated/0/Downloads
```

**Comment by GaucovyAero** [comment]
Alternatively, you can also use this YouTube tutorial: https://youtu.be/9ZdMPBcn71M
