### ISSUE TITLE
The 1.12.2 Not downloaded error

### ISSUE THREAD

**Issue by Alreynn** [PojavLauncherTeam/PojavLauncher#341]
![Screenshot_2020-10-04-10-14-11-67_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/71954929/95006231-52a7fa00-062c-11eb-9935-ba741cd40975.jpg)
I don't know how this happened, again. I got this error when i launching the version 1.12.2 in new 3.2.0 testing6 app version. It says in the picture. How do i not installed that one resource? I already done full downloading that 1.12.2 version in this PojavLauncher.

**Comment by artdeell** [comment]
Because LWJGL3 is the part that you should install manually.
Perhaps you didn't read the [wiki page](https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Testing-v3)?

**Comment by Alreynn** [comment]
Oh ok, thx. I just skipped all the parts and then downloaded them.
