### ISSUE TITLE
Virgl Renderer is broken

### ISSUE THREAD

**Issue by Guppy3874** [PojavLauncherTeam/PojavLauncher#3411]
### Describe the bug

You start the game and cannot see any text when the Virgl renderer is active. If you then try to enter a game, you will see many faulty textures.

### The log file and images/videos

![Screenshot_20220630-093840_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98043898/176637089-3cd65501-6da2-4f52-88d3-fd75098df397.jpg)
![Screenshot_20220630-093759_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98043898/176637096-5e86bee2-de46-4e69-aa0f-bac36df72890.jpg)
![Screenshot_20220630-093657_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98043898/176637098-16b8f352-647e-4eaa-9430-d61bf7ae97e8.jpg)
![Screenshot_20220630-093508_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98043898/176637101-ba7cea7b-769b-4b1f-a8f4-ce8367190a10.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Choose Virgl Renderer
3. Start Minecraft 1.18/1.19
4. Look at the Menu/Game
```

### Expected Behavior

Normal graphic, Visible text

### Platform

```markdown
- Device model: Samsung Galaxy A71 128GB
- CPU architecture: Snapdragon 730
- Android version: 11
- PojavLauncher version: Latest Realease || Playstore
```

**Comment by WesleyVanNeck** [comment]
dont use it on 1.17 and up

**Comment by SkulZOnTheYT** [comment]
right, even though I use handphone high-end Still can't render with virgl, it can but the texture will be damaged, I recommend using holy4es for 1.17+, if you want to keep using shaders use 1.16 and below, And also make sure you use shaders that support virgl (such as vibrant sildurs, ect) depending on your handphone.
