### ISSUE TITLE
[BUG] Can't click an item

### ISSUE THREAD

**Issue by Zakaii12** [PojavLauncherTeam/PojavLauncher#3412]
### Describe the bug

Can't click item you need to hold it and move it and showing 
Even my cursor not in the server list still showing that

### The log file and images/videos

![Screenshot_2022-07-02-12-03-54-46_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/108564217/176987273-4378c33b-a401-4ce9-80b6-3a13e73f036c.jpg)

### Steps To Reproduce

```markdown
It randomly showing and happend two times
```

### Expected Behavior

Fix this issues 

### Platform

```markdown
- Device model: CPH2251
- CPU architecture: cortex
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

Nothing else

**Comment by GaucovyAero** [comment]
Use the virtual mouse maybe?

**Comment by Zakaii12** [comment]
Same thing will happend
