### ISSUE TITLE
Cant load a world in 1.19

### ISSUE THREAD

**Issue by Mousebu** [PojavLauncherTeam/PojavLauncher#3413]
### Describe the bug

When i start version 1.19 or 1.19 optifine pre2 and then create/load a world it doesn't load it stop at 0% and then it never loads

### The log file and images/videos

Dont have a video 

### Steps To Reproduce

```markdown
1. Start pojav launcher 
2. Start version 1.19 or 1.19 optifine pre2
3. Load/create a new world then it will not load forever it will stop at 0% and then not increase
```

### Expected Behavior

I think that the world should load

### Platform

```markdown
- Device model: Vivo y91i
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: latest in playstore
```

### Anything else?

Nope

**Comment by miggythewriter** [comment]
Send latestlog.txt

**Comment by Mousebu** [comment]
content://ru.zdevs.zarchiver.external/storage/emulated/0/games/PojavLauncher/latestlog.txt

**Comment by Mousebu** [comment]
#
[Uploading latestlog.txt…]()
This is the latest log

**Comment by GaucovyAero** [comment]
> Uploading latestlog.txt… This is the latest log

you haven't finished sending it
