### ISSUE TITLE
Found a violation of the license

### ISSUE THREAD

**Issue by qwq233** [PojavLauncherTeam/PojavLauncher#3415]
Found [PojavLauncher's code](https://github.com/Tungstend/HMCL-PE/tree/main/PojavLauncher/src/main/java/net/kdt/pojavlaunch) during code review of [HMCL PE](https://github.com/Tungstend/HMCL-PE)

Although the software is under the GPL license, it provides a non-open source and [paid "closed beta version"](https://github.com/Tungstend/HMCL-PE/blob/main/HMCLPE/release/HMCLPE-release.apk) (also mentioned in their README file) and contains [missing critical components that fail to compile](https://github.com/Tungstend/HMCL-PE/pull/27#issuecomment-1166523147)

I have previously asked the Free Software Foundation via email that it is a violation of the GPL for non-original code providers to quote/use GPL-licensed code in such "missing critical components" projects.

I recommend submitting a [DMCA takedown request](https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice) to GitHub Staff, if Inconvenient, you authorize me to do so.

![image](https://user-images.githubusercontent.com/20317838/177008706-a0a0c39d-99c7-4cda-a24d-cef3a582941a.png)

**Comment by NotAHero04** [comment]
Looks like some other people have the same interest in that project. I'll talk about this with the developers.

**Comment by qwq233** [comment]
Repository owner deleted repository

**Comment by khanhduytran0** [comment]
I don't think they deleted it. They might have simply made it private.

**Comment by qwq233** [comment]
> 



> I don't think they deleted it. They might have simply made it private.

true

**Comment by qwq233** [comment]
> I don't think they deleted it. They might have simply made it private.

there's a forked repo from HMCL-PE repo
you can use it as a reference
https://github.com/577fkj/HMCL-PE

**Comment by TSaltedfishKing** [comment]
https://github.com/577fkj/FuckHMCLPE/issues/3

**Comment by TSaltedfishKing** [comment]
# #https://github.com/577fkj/FuckHMCLPE/issues/3

**Comment by TSaltedfishKing** [comment]
https://github.com/577fkj/FuckHMCLPE/issues/3

**Comment by zhangjing-GitHub-Code** [comment]
also a workflow-added [fork by me](https://github.com/zhangjing-GitHub-Code/HMCL-PE)
(workflow dont work due to device lock and another issue(after DeramOneX may remove the device auth zhangjing-GitHub-Code/HMCL-PE#7but i revert it)

**Comment by DreamOneX** [comment]
> > I don't think they deleted it. They might have simply made it private.
> 
> there's a forked repo from HMCL-PE repo you can use it as a reference https://github.com/577fkj/HMCL-PE

The owner of HMCL-PE restore the [repo](https://github.com/Tungstend/HMCL-PE)

**Comment by qwq233** [comment]
> > > I don't think they deleted it. They might have simply made it private.
> > 
> > 
> > there's a forked repo from HMCL-PE repo you can use it as a reference https://github.com/577fkj/HMCL-PE
> 
> The owner of HMCL-PE restore the [repo](https://github.com/Tungstend/HMCL-PE)


@khanhduytran0

**Comment by crystall1nedev** [comment]
@qwq233 I already filed a takedown request.

**Comment by Tungstend** [comment]
> @qwq233 I already filed a takedown request.

GPL does not stipulate that developers are not allowed to make profits, HMCL-PE is completely open source and does not violate GPL

**Comment by DreamOneX** [comment]
> Found [PojavLauncher's code](https://github.com/Tungstend/HMCL-PE/tree/main/PojavLauncher/src/main/java/net/kdt/pojavlaunch) during code review of [HMCL PE](https://github.com/Tungstend/HMCL-PE)
> 
> Although the software is under the GPL license, it provides a non-open source and [paid "closed beta version"](https://github.com/Tungstend/HMCL-PE/blob/main/HMCLPE/release/HMCLPE-release.apk) (also mentioned in their README file) and contains [missing critical components that fail to compile](https://github.com/Tungstend/HMCL-PE/pull/27#issuecomment-1166523147)
> 
> I have previously asked the Free Software Foundation via email that it is a violation of the GPL for non-original code providers to quote/use GPL-licensed code in such "missing critical components" projects.
> 
> I recommend submitting a [DMCA takedown request](https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice) to GitHub Staff, if Inconvenient, you authorize me to do so.
> 
> ![image](https://user-images.githubusercontent.com/20317838/177008706-a0a0c39d-99c7-4cda-a24d-cef3a582941a.png)

the missing components were published [here](https://github.com/Tungstend/HMCL-PE/blob/main/Boat/src/main/jni/security/security.cpp)

**Comment by zhangjing-GitHub-Code** [comment]
but the question is how to chsnge my fork back to the repo Tungstend/HMCL-PE (when it turns to private(or deleted), my fork changed to (some number)/HMCL-PE), now i want to change it back

**Comment by qwq233** [comment]
> > @qwq233 I already filed a takedown request.
> 
> GPL does not stipulate that developers are not allowed to make profits, HMCL-PE is completely open source and does not violate GPL

confirmed that it has updated their private code so close this issue

**Comment by Felix14-v2** [comment]
@khanhduytran0 , sorry for ping and sorry for this message as such, but in the issue you just closed, you wrote

> its source code is closed

You're wrong, because its original version has source code on GitHub, and is also available via a special link on their domain (not to be confused with its pirated fake).

**Comment by qwq233** [comment]
> 



> @khanhduytran0 , sorry for ping and sorry for this message as such, but in the issue you just closed, you wrote
> 
> > its source code is closed
> 
> You're wrong, because its original version has source code on GitHub, and is also available via a special link on their domain (not to be confused with its pirated fake).

it was closed-source software

**Comment by Felix14-v2** [comment]
> it was closed-source software

As I said above, you can download its source code via tlaun.ch/source. The repository on GitHub is no longer open from the moment when its name and source code were literally stolen by the owners of the "fake". You can access it through its developers in Discord. Also, don't confuse the launchers, I'm talking about the historically original TL, not its fake from ".org"

If you have any questions or misunderstandings, here is my Discord: Felix14#3357
(I think this is more appropriate than communicating here, in the issues section)

**Comment by qwq233** [comment]
> > it was closed-source software
> 
> As I said above, you can download its source code via tlaun.ch/source. The repository on GitHub is no longer open from the moment when its name and source code were literally stolen by the owners of the "fake". You can access it through its developers in Discord. Also, don't confuse the launchers, I'm talking about the historically original TL, not its fake from ".org"
> 
> If you have any questions or misunderstandings, here is my Discord: Felix14#3357 (I think this is more appropriate than communicating here, in the issues section)

are we talking about the same thing?

**Comment by DreamOneX** [comment]
I think they transfer original repository away. not deleted or turn private. so i think you should delete your fork.
