### ISSUE TITLE
[BUG] <Can't join on custom servers>

### ISSUE THREAD

**Issue by Popstleo** [PojavLauncherTeam/PojavLauncher#3416]
### Describe the bug

When tried to open a custom server cant join, every Ip possible was used. Its a custom server made by me. Yes the port is open. Yes another devices(PC's) can join.

I was thinking if a VPN programm (like Radmin that i use in pc) can make this connection

### The log file and images/videos

![2es67m3q14371](https://user-images.githubusercontent.com/108630109/177054319-09737f4d-6158-494c-8637-4e295104bc80.jpg)

### Steps To Reproduce

```markdown
1 Start luncher
2 multiplayer
3 Ip and join
4 unble to connect
```

### Expected Behavior

Join easily

### Platform

```markdown
- Device model: A52 
- CPU architecture: 
- Android version: 
- PojavLauncher version: last via play stiore
```

**Comment by Mathias-Boulay** [comment]
Damn, that's quite an old version you have there

**Comment by GaucovyAero** [comment]
> Damn, that's quite an old version you have there

probably 3.3.1.1 tbh

**Comment by GaucovyAero** [comment]
Are you using any VPN programs on PC (like Radmin or Hamachi) and have you changed your DNS on PC?

**Comment by Popstleo** [comment]
> Damn, that's quite an old version you have there

Oh thats is a print before i update, now is updated but the same error

**Comment by Popstleo** [comment]
> 

In the pc i am using radmin, you think is because that ? I tried to use without radmin but the persons cannot enter without it

**Comment by GaucovyAero** [comment]
> > 
> 
> In the pc i am using radmin, you think is because that ? I tried to use without radmin but the persons cannot enter without it

yep thats the issue, if you dont get somehow radmin working on your phone it wont work

**Comment by Popstleo** [comment]
> > > 
> > 
> > 
> > In the pc i am using radmin, you think is because that ? I tried to use without radmin but the persons cannot enter without it
> 
> yep thats the issue, if you dont get somehow radmin working on your phone it wont work

but i need unistall radmin or putting it down work ?

**Comment by GaucovyAero** [comment]
this is a no-go, because you have to IP-forward through your internet router and its settings

**Comment by Popstleo** [comment]
Hm i dont understand, mb mine english sometimes catch me. 
Cause the radmin i need to reconfig on my router mine ip ?
