### ISSUE TITLE
[F-Req] <add mouse scroll feature on inventory and settings>

### ISSUE THREAD

**Issue by SkulZOnTheYT** [PojavLauncherTeam/PojavLauncher#3417]
### Is this request related to a bug?

to add mouse scroll is a bug that must be addressed, because I have a little trouble when scrolling inventory when using mouse or using hand touch, there is no reaction to the inventory and settings.

### Describe the request.

my request , as described in the column "Is this request related to a bug?" I answered about the mouse scroll bug problem that must be resolved, even if this was successfully added it would be one of the best updates I've received, I haven't rated Pojav launcher yet, if there are still bugs, if my bugs and requests are fulfilled I will give full 5 stars.

### Anything else?

excited developer overcame my request :)

**Comment by GaucovyAero** [comment]
I mean, the mouse scroll bug needs to be fixed. But the world stuff certainly isn't about Pojav, more about your luck. We use official jars from Minecraft and it isn't just a ripoff or anything, so entering the same seeds on the same version on your pc and phone will result in the same world, obviously.

**Comment by SkulZOnTheYT** [comment]
Oh I see, that means the world's problems have been resolved, just the mouse scroll bug, right?

**Comment by GaucovyAero** [comment]
> Oh I see, that means the world's problems have been resolved, just the mouse scroll bug, right?

There were never any world issues. As I said, it's the absolute same file and works the same as your PC version.

**Comment by SkulZOnTheYT** [comment]
Okay okay I understand now, just waiting for the addition of the mouse scroll 🗿
How's @Mathias-Boulay @khanhduytran0  is it possible to add a mouse scroll?

**Comment by Dika23435** [comment]
are you still making virgl?@Mathias-Boulay
@khanhduytran0

**Comment by SkulZOnTheYT** [comment]
@Dika23435 it seems i'm not sure that pojav developer making virgl, because virgl only supports up to 1.16, That's even if you use a handphone mid - high,Low end handphone Just got to version 1.15 to use virgl, if you force it on 1.17+ then feel the impact, with broken renderer, broken textures and missing text etc.

**Comment by GaucovyAero** [comment]
@SkulZOnTheYT 

Can you please contact us on Discord via the official PojavLauncher discord server?

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
