### ISSUE TITLE
v3: colon deletes last character

### ISSUE THREAD

**Issue by nicknickeryt** [PojavLauncherTeam/PojavLauncher#342]
**PojavLauncher version:** v3
**Minecraft version:** tested in 1.13.2 and 1.16.3
**Description:**
Typing a colon results in deleting last character in text box.
**Example:**
![mobizen_2020100-1601832316751](https://user-images.githubusercontent.com/37023408/95022415-79d7e900-0677-11eb-90d6-0641c6568bb5.gif)

**Comment by WesleyVanNeck** [comment]
Fixed
