### ISSUE TITLE
[BUG] 1.17 optifine exits on world loading + Virgil renderer bug

### ISSUE THREAD

**Issue by JagritThukral** [PojavLauncherTeam/PojavLauncher#3420]
### Describe the bug

I launched the game with both renderer 
Holygles exists the game on world loading
Virgilrender flips the screen but in reality screen isn't flipped ( visually flipped )

### The log file and images/videos

Holygles:- 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9041473/latestlog.txt)
![Screenshot_2022-07-04-23-46-18-31_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/76104734/177203042-5541ad08-4d7f-4ae5-a66e-f560836e357e.jpg)

Virgilrender log and image: 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9041498/latestlog.txt)
)
![Screenshot_2022-07-04-22-15-08-88_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/76104734/177203834-cc561b51-0ed8-4a32-875d-86ce788bb47d.jpg)
**Flickering image**
![Screenshot_2022-07-04-23-53-51-35_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/76104734/177203767-dc6005af-7819-45c5-aba2-f125947eb29e.jpg)

### Steps To Reproduce

```markdown
1. Start 1.17 optifine  pojav ( use both renderer one by one)
2. Load world or join a server
```

### Expected Behavior

I expect game to launch

### Platform

```markdown
- Device model: oppo f17
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: playstore latest
```

**Comment by GaucovyAero** [comment]
This is normal. There is no fix for this and we know about this issue. RIP

**Comment by JagritThukral** [comment]
> This is normal. There is no fix for this and we know about this issue. RIP

What ? In the other issues i have read it's mentioned 1.17-1.18
9 optifine/forge/fabric is  supported in latest release

**Comment by miggythewriter** [comment]
Send latestlog.txt not .log files

**Comment by JagritThukral** [comment]
Ok

**Comment by JagritThukral** [comment]
> Send latestlog.txt not .log files

Done edited main message

**Comment by miggythewriter** [comment]
> > Send latestlog.txt not .log files
> 
> Done edited main message

Are you using optifine?

**Comment by JagritThukral** [comment]
> > > Send latestlog.txt not .log files
> > 
> > 
> > Done edited main message
> 
> Are you using optifine?

Yes

**Comment by miggythewriter** [comment]
> > > > Send latestlog.txt not .log files
> > > 
> > > 
> > > Done edited main message
> > 
> > 
> > Are you using optifine?
> 
> Yes

Are you using render regions?

**Comment by JagritThukral** [comment]
> > > > > Send latestlog.txt not .log files
> > > > 
> > > > 
> > > > Done edited main message
> > > 
> > > 
> > > Are you using optifine?
> > 
> > 
> > Yes
> 
> Are you using render regions?

Yeah

**Comment by miggythewriter** [comment]
> > > > > > Send latestlog.txt not .log files
> > > > > 
> > > > > 
> > > > > Done edited main message
> > > > 
> > > > 
> > > > Are you using optifine?
> > > 
> > > 
> > > Yes
> > 
> > 
> > Are you using render regions?
> 
> Yeah

Don't use it it will crash the game

**Comment by SkulZOnTheYT** [comment]
> > > > > > Send latestlog.txt not .log files
> > > > > 
> > > > > 
> > > > > Done edited main message
> > > > 
> > > > 
> > > > Are you using optifine?
> > > 
> > > 
> > > Yes
> > 
> > 
> > Are you using render regions?
> 
> Yeah

Indeed the rendering region makes the fps increase but the rendering region forces your gpu to work hard, it's better if the gpu is high (desktop gpu), the handphone only uses a mid - low gpu, We recommend using rendering regions on your pc or computer.

**Comment by JagritThukral** [comment]
Thanks it worked
