### ISSUE TITLE
[BUG] modpack crash

### ISSUE THREAD

**Issue by Hadbrinenotcool** [PojavLauncherTeam/PojavLauncher#3422]
### Describe the bug

Application exited with code 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9062179/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start Pojav
2.Crash
```

### Expected Behavior

The game launched

### Platform

```markdown
- Device model: oppo a71
- CPU architecture: arm64
- Android version: 7.1.1
- PojavLauncher version: Lastest
```

### Anything else?

i dunno, i just wanna play.

**Comment by ninem4re** [comment]
Could you provide the list of mods and the name of the modpack you are trying to play? From what I've read in the log, it seems like there's an incompatibility between some of your mods, but I'm not 100% certain.

**Comment by Hadbrinenotcool** [comment]
> Could you provide the list of mods and the name of the modpack you are trying to play? From what I've read in the log, it seems like there's an incompatibility between some of your mods, but I'm not 100% certain.

I got the modpacks from YT but here some the list
![Screenshot_2022-07-07-16-51-24-41](https://user-images.githubusercontent.com/83611884/177745845-ce15b70a-0471-4530-96ce-014720709ff4.png)
![Screenshot_2022-07-07-16-51-32-38](https://user-images.githubusercontent.com/83611884/177745876-2fcdf99f-9578-4949-93f7-f11fb2057bcf.png)
![Screenshot_2022-07-07-16-51-36-78](https://user-images.githubusercontent.com/83611884/177745904-aff585db-0602-4675-9a27-fc548712cb9a.png)
