### ISSUE TITLE
[BUG] Forge 1.5.2 black screen on launch

### ISSUE THREAD

**Issue by kkellogg378** [PojavLauncherTeam/PojavLauncher#3423]
### Describe the bug

Trying to run FTB Unleashed and vanilla 1.5.2 runs fantastically but simply installing forge gave a black screen. I tried the solutions in #2468 but the alternative JSON gave error code 1. 

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: dahlia-8-f527e8a14-v3_openjdk
Info: LWJGL3 directory: [version, lwjgl-glfw-classes.jar]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.5.2-Forge7.8.1.738
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2898
Added custom env: POJAV_NATIVEDIR=/data/app/~~JWIMc7j6-aeml8nzMgvabg==/net.kdt.pojavlaunch-gGDQkUOmKTKAqM6HdQajgw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~JWIMc7j6-aeml8nzMgvabg==/net.kdt.pojavlaunch-gGDQkUOmKTKAqM6HdQajgw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1440
--------- beginning of main

I/LIBGL   (25618): Initialising gl4es

I/LIBGL   (25618): v1.1.4 built on May 28 2022 20:23:20

I/LIBGL   (25618): Using GLES 2.0 backend

I/LIBGL   (25618): loaded: libGLESv2.so

I/LIBGL   (25618): loaded: libEGL.so

I/LIBGL   (25618): Using GLES 2.0 backend

I/LIBGL   (25618): Hardware Full NPOT detected and used

I/LIBGL   (25618): FBO are in core, and so used

I/LIBGL   (25618): PointSprite are in core, and so used

I/LIBGL   (25618): CubeMap are in core, and so used

I/LIBGL   (25618): BlendColor is in core, and so used

I/LIBGL   (25618): Blend Substract is in core, and so used

I/LIBGL   (25618): Blend Function and Equation Separation is in core, and so used

I/LIBGL   (25618): Texture Mirrored Repeat is in core, and so used

I/LIBGL   (25618): Extension GL_OES_element_index_uint  detected and used

I/LIBGL   (25618): Extension GL_OES_packed_depth_stencil  detected and used

I/LIBGL   (25618): Extension GL_OES_depth24  detected and used

I/LIBGL   (25618): Extension GL_OES_rgb8_rgba8  detected and used

I/LIBGL   (25618): Extension GL_EXT_texture_format_BGRA8888  detected and used

I/LIBGL   (25618): Extension GL_OES_depth_texture  detected and used

I/LIBGL   (25618): Extension GL_OES_texture_stencil8  detected and used

I/LIBGL   (25618): Extension GL_OES_texture_float  detected and used

I/LIBGL   (25618): Extension GL_OES_texture_half_float  detected and used

I/LIBGL   (25618): Extension GL_EXT_color_buffer_float  detected and used

I/LIBGL   (25618): Extension GL_EXT_color_buffer_half_float  detected and used

I/LIBGL   (25618): high precision float in fragment shader available and used

I/LIBGL   (25618): Max vertex attrib: 32

I/LIBGL   (25618): Extension GL_OES_standard_derivatives  detected and used

I/LIBGL   (25618): Max texture size: 16384

I/LIBGL   (25618): Max Varying Vector: 31

I/LIBGL   (25618): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6

I/LIBGL   (25618): Extension GL_EXT_texture_filter_anisotropic  detected and used

I/LIBGL   (25618): Max Anisotropic filtering: 16

I/LIBGL   (25618): Hardware vendor is Qualcomm

I/LIBGL   (25618): GLSL 300 es supported

I/LIBGL   (25618): GLSL 310 es supported and used

I/LIBGL   (25618): GLSL 320 es supported

I/LIBGL   (25618): Max Color Attachments: 8 / Draw buffers: 8

I/LIBGL   (25618): sRGB surface supported

I/LIBGL   (25618): EGLImage to Texture2D supported

I/LIBGL   (25618): EGLImage to RenderBuffer supported
I/LIBGL   (25618): ignore MipMap
I/LIBGL   (25618): Targeting OpenGL 2.1
I/LIBGL   (25618): No hack in shader converter to define overloaded function with int
I/LIBGL   (25618): NPOT texture handled in hardware
I/LIBGL   (25618): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (25618): try to use VBO

I/LIBGL   (25618): glX Will try to recycle EGL Surface
I/LIBGL   (25618): Current folder is:/
I/jrelog  (25618): dlopen libgl4es_114.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (25618): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so in namespace classloader-namespace
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes
/Internal/lib/aarch64/libjsig.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (25618): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (25618): dlopen /data/app/~~JWIMc7j6-aeml8nzMgvabg==/net.kdt.pojavlaunch-gGDQkUOmKTKAqM6HdQajgw==/lib/arm64/libopenal.so success

I/jrelog  (25618): Done processing args

I/jrelog  (25618): Found JLI lib

I/jrelog  (25618): Calling JLI_Launch

OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

Jul 07, 2022 4:06:00 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using tweak class name net.minecraftforge.legacy._1_5_2.LibraryFixerTweaker
Exception in thread "main" 
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor

	at java.lang.Class.getDeclaredConstructors0(Native Method)

	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)

	at java.lang.Class.getConstructor0(Unknown Source)

	at java.lang.Class.newInstance(Unknown Source)

	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:81)

	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:21)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:51)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor

	at java.net.URLClassLoader.findClass(Unknown Source)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	... 8 more

Java Exit code: 1
I/jrelog  (25618): Going to free args

I/jrelog  (25618): Free done

### Steps To Reproduce

```markdown
1. Start PoJavLauncher
2. Install Forge for 1.5.2
3. Run the game
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: Galaxy S10+
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest on gplay
```

### Anything else?

Tried the solution for replacing the JSON for forge found in #2468

**Comment by GaucovyAero** [comment]
Yeah, the JSON files from the repo in the video in `#frequently-asked-questions` are broken. Make sure to use ones in this link instead: https://www.mediafire.com/file/ojhk4i28sizplnl/PojavLauncher_Forge_1.3.2-1.7.2_Patchpack_v1.0.zip/file. The issue is that asm-all 5.2 didn't download correctly. If the issue keeps reoccurring with the new JSON, download asm-all 5.2 manually and insert it like this: `.minecraft/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar`
