### ISSUE TITLE
[BUG] <Fabric 1.17 crashes when logging into Minecraft>

### ISSUE THREAD

**Issue by SkulZOnTheYT** [PojavLauncherTeam/PojavLauncher#3424]
### Describe the bug

I'm trying Ares Client for Fabric, suddenly crashes when I'm entering minecraft, is there a problem with Ares Client or something else?
I initially used Fire Fabric, Sodium, and Ares Client. But it didn't work, I removed the sodium still still. Actually I haven't tried to play Fabric 1.17 without that client 😅
That's why I ask, is this because the client has a problem or a bug?
from latest.log attaching something is wrong with the font, whether it is correct or not.

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9068719/latest.log)

### Steps To Reproduce

```markdown
1. Open Pojav Launcher.
2. I chose Fabric version 1.17.1.
3. I press the play button and wait for it to finish loading.
4. As a result, the game crashes out with code 1.
```

### Expected Behavior

I hope there can be a solution or fix as soon as possible.

### Platform

```markdown
- Device model: Realme C12
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: [Latest Version || dahila-v8-f527e8a14-v3_openjdk]
```

### Anything else?

not only that.

**Comment by GaucovyAero** [comment]
```
java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[sodium-fabric-mc1.19-0.4.2+build.16.jar:?]
```

Don't use Sodium, it's not compatbile with Pojav. Use OptiFabric and OptiFine instead.
