### ISSUE TITLE
Sodium's Video settings fail to open

### ISSUE THREAD

**Issue by Noxyntious** [PojavLauncherTeam/PojavLauncher#3425]
### Describe the bug

Video settings does not open with Sodium installed

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9070609/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the game with Sodium
2. Open Options
3. Click Video settings
```

### Expected Behavior

I expect Video settings to open on press of the button.

### Platform

```markdown
- Device model: Samsung Galaxy A51 4G (SM-A515F, 4G/128G)
- CPU architecture: Exynos 9611, arm64-v8a
- Android version: 12.1
- PojavLauncher version: Latest GPlay release | Dahlia
```

### Anything else?

I'm using the modpack at http://github.com/Noxyntious/PojavOptimize-Actually-1.18. Tested on my PC and Video settings opens fine.
Fabric loader 0.14.8, used holy gl4es and virgl renderer, none of them fixed this issue.

**Comment by offbeat-stuff** [comment]
@Noxyntious please see this
https://github.com/FlashyReese/sodium-extra-fabric/issues/180

**Comment by Noxyntious** [comment]
thanks for the reply, however adding that line to sodium extra properties didn't help me.

**Comment by GaucovyAero** [comment]
> thanks for the reply, however adding that line to sodium extra properties didn't help me.

yeah, sodium isn't compatible with pojav, make sure to use optifabric and optifine instead.
