### ISSUE TITLE
Discord banned 6 months

### ISSUE THREAD

**Issue by Kaan1O1** [PojavLauncherTeam/PojavLauncher#3426]
Banned Discord

i banned on Pojav's Discord for nearly for 6 months
for not be 13 years old, i did became 13 but im not unbanned   Discord: kaansahin0001#5688 before Kaan_101#5688 somehow can i be unbanned

**Comment by USMP-lancer** [comment]
while yes you deserve an unban, here is not the best place

**Comment by mchnjt** [comment]
> Banned Discord
> 
> i banned on Pojav's Discord for nearly for 6 months for not be 13 years old, i did became 13 but im not unbanned Discord: kaansahin0001#5688 before Kaan_101#5688 somehow can i be unbanned

If you want an unban, consider sending one of the following
- birth certificate
- picture of you celebrating your 13th birthday
- exact screenshot, or unb case of when the ban happened
- your discord uid
🤣🤣🤣🤣
