### ISSUE TITLE
After i deleted and reinstalled the game i cant add nothing back

### ISSUE THREAD

**Issue by Technoblade90** [PojavLauncherTeam/PojavLauncher#3427]
### Describe the bug

Whenever i try to add a minecraft client or mod or resource pack it never shows up how could i fix this?

### The log file and images/videos

It shows none

### Steps To Reproduce

```markdown
1. install the client/pack
2. Add it to the file system u use
```

### Expected Behavior

I expect for it to not show

### Platform

```markdown
- Device model: Chromebook 14
- CPU architecture: Intel Pentium Silver N5030 CPU
- Android version: 103.0.0.0 
- PojavLauncher version: Latest Release 1.8.9
```

**Comment by GaucovyAero** [comment]
Well, this definitely is fixable. Because this is such a specific issue, make sure to join the official PojavLauncher discord server and get help there.

**Comment by GaucovyAero** [comment]
Didn't respond to my message, and resource packs are verified working on the latest v3_openjdk build. Closing.
