### ISSUE TITLE
[BUG] Text still upside down

### ISSUE THREAD

**Issue by ThatMG393** [PojavLauncherTeam/PojavLauncher#3429]
### Describe the bug

I thought it's fixed or maybe just an error in my end.

### The log file and images/videos

![Settings menu text upside down](https://user-images.githubusercontent.com/73651803/178147250-4be2b0ee-e9ec-4a1f-9582-f480b1208ad0.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Go to settings
```

### Expected Behavior

I expect it to be fine because I read the changelog and it said *"Fixed the language being upside down when selecting English"* 

### Platform

```markdown
- Device model: Samsung C5 Pro
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: Latest Release
```

### Anything else?

Nothing.

**Comment by ThatMG393** [comment]
Duplicate of issue #3397

**Comment by EnderBrine99FOX** [comment]
Change Your Language To English US And It Will Be Fixed

**Comment by mchnjt** [comment]
> Change Your Language To English US And It Will Be Fixed

oh em gee it's pirata pojava guy😱😱😱😱😱
