### ISSUE TITLE
Will Pojav work on my device.

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#343]
Specifications: Device-OPPO,
                            Aarchv7,
                            Ram-1gb,
                            Android-5.1
and it is 5 years old. But I have another little better device Redmi 8a,
                                 Ram-2gb,
                                 I don't know about the Aarch.

**Comment by ghost** [comment]
I'm eagerly waiting for your reply 😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋😋

**Comment by gamerboy737** [comment]
thats not enough atleast 4gb ram needed and android version 7.0 or higher.

**Comment by artdeell** [comment]
I think 1Gb is very small. You should expect lags, but it may work.

пн, 5 окт. 2020 г., 18:33 ChargedHat42838 <notifications@github.com>:

**Comment by khanhduytran0** [comment]
> thats not enough atleast 4gb ram needed and android version 7.0 or higher.

No, just Android 5 and higher could install and play. On my 2gb ram device, I just allocate 768mb and play 1.13.2 as nornal, but lag a lot.

**Comment by ghost** [comment]
Thanks very much.
I love POJAV LAUNCHER very muchhhhh
