### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by SoyAlexMC** [PojavLauncherTeam/PojavLauncher#3433]
### Describe the bug

forge makes minecraft not start in all versions and it gives me error 1 (Forge makes my screen go black and a few minutes later I get error 1)

### The log file and images/videos

Info: Launcher version: dahlia-8-f527e8a14-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.12.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2298
Added custom env: POJAV_NATIVEDIR=/data/app/~~FSk-mM7SXg7S1IN7h5-vzw==/net.kdt.pojavlaunch-nsu9UUohxZzh4-cUYAzMGg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~FSk-mM7SXg7S1IN7h5-vzw==/net.kdt.pojavlaunch-nsu9UUohxZzh4-cUYAzMGg==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main

I/LIBGL   (11746): Initialising gl4es
I/LIBGL   (11746): v1.1.4 built on May 28 2022 20:23:20
I/LIBGL   (11746): Using GLES 2.0 backend
I/LIBGL   (11746): loaded: libGLESv2.so
I/LIBGL   (11746): loaded: libEGL.so
I/LIBGL   (11746): Using GLES 2.0 backend
I/LIBGL   (11746): Hardware Full NPOT detected and used
I/LIBGL   (11746): FBO are in core, and so used
I/LIBGL   (11746): PointSprite are in core, and so used
I/LIBGL   (11746): CubeMap are in core, and so used
I/LIBGL   (11746): BlendColor is in core, and so used
I/LIBGL   (11746): Blend Substract is in core, and so used
I/LIBGL   (11746): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (11746): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (11746): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (11746): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (11746): Extension GL_OES_depth24  detected and used
I/LIBGL   (11746): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (11746
): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (11746): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (11746): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (11746): Extension GL_OES_texture_float  detected and used
I/LIBGL   (11746): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (11746): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (11746): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (11746): high precision float in fragment shader available and used
I/LIBGL   (11746): Max vertex attrib: 32
I/LIBGL   (11746): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (11746): Max texture size: 16384
I/LIBGL   (11746): Max Varying Vector: 31
I/LIBGL   (11746): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (11746): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (11746): Max Anisotropic filtering: 16
I/LIBGL   (11746): Hardware 
vendor is Qualcomm
I/LIBGL   (11746): GLSL 300 es supported
I/LIBGL   (11746): GLSL 310 es supported and used
I/LIBGL   (11746): GLSL 320 es supported
I/LIBGL   (11746): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (11746): sRGB surface supported
I/LIBGL   (11746): EGLImage to Texture2D supported
I/LIBGL   (11746): EGLImage to RenderBuffer supported
I/LIBGL   (11746): ignore MipMap
I/LIBGL   (11746): Targeting OpenGL 2.1
I/LIBGL   (11746): No hack in shader converter to define overloaded function with int
I/LIBGL   (11746): NPOT texture handled in hardware
I/LIBGL   (11746): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (11746): try to use VBO
I/LIBGL   (11746): glX Will try to recycle EGL Surface
I/LIBGL   (11746): Current folder is:/
I/jrelog  (11746): dlopen libgl4es_114.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (11746): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (11746)
: dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (11746): dlopen libfreetype.so failed: dlopen failed: library "libfreetype.so" not found
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so failed: dlopen failed: library "libfreetype.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtim
es/Internal-17/lib/libfontmanager.so in namespace classloader-namespace
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success
I
/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Int
ernal-17/lib/libjsig.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so failed: dlopen failed: library "libfreetype.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so in namespace classloader-namespace
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Intern
al-17/lib/libmanagement.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  (11746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  (11746): dlopen /data/app/~~FSk-mM7SXg7S1IN7h5-vzw==/net.kdt.pojavlaunch-nsu9UUohxZzh4-cUYAzMGg==/lib/arm64/libopenal.so success
I/jrelog  (11746): Done processing args
I/jrelog  (11746): Found JLI lib
I/jrelog  (11746): Calling JLI_Launch

Exception in thread "main" 
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java Exit code: 1
I/jrelog  (11746): Going to free args
I/jrelog  (11746): Free done

### Steps To Reproduce

```markdown
1 start Pojav Launcher
2 put the Forge.jar
3 press the button to enter in the game
4 the game no start 
5 the game takes me out
6 I get error 1
```

### Expected Behavior

I hope the screen doesn't go black and I get that error

### Platform

```markdown
- Device model: Redmi Note 9s
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: dahlia-8-f527e8a14-v3
_openjdk
```

### Anything else?

no

**Comment by khanhduytran0** [comment]
Forge 1.16.5 or older requires Java 8. With Java 17, it would break at many places due to incompatibility.
