### ISSUE TITLE
[BUG] <control+space bug and a small esc bug>

### ISSUE THREAD

**Issue by Aboodal7asan** [PojavLauncherTeam/PojavLauncher#3434]
### Describe the bug

I was using an external keyboard to play when i encountered this weird bug,
If i pressed left control then space bar while walking the player will stop suddenly
But if i pressed space bar then left control the player will start sprinting and jumping at the same time as it was meant to
Controls:
(
W = walk forward 
CTRL_LEFT= sprint
SPACE = jump
)
For the esc bug sometimes it doesn't work in other uis
Like settings or inventory or crafting table etc..

### The log file and images/videos

- logs : 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9106902/latestlog.txt)

Video link : 
https://youtu.be/eQX0gE0c4gs
[ i lowered the video volume because of my heavy breathing sound]
" Apologies for using a phone to record couldn't think of a better idea to show the bug "

* Minecraft version used: 1.8.8
-Reason: opens faster than 1.19
-Bug is also presented in all minecraft versions 

### Steps To Reproduce

```markdown
Using a physical/external keyboard
(
W = walk forward 
CTRL_LEFT= sprint
SPACE = jump
)
Steps to reproduce
1.Open any minecraft version
2.Open up any world
3.Press W to walk and keep pressing it
4.while holding the "w" press "left ctrl" and keep holding both buttons
5. Finally press "space bar" while other two buttons are being pressed
===========================
For the esc button just open any ui in minecraft and start messing with it (like crafting or smelting and settings) and it won't work
===========================
```

### Expected Behavior

Player stops suddenly

Esc doesn't work sometimes

### Platform

```markdown
- Device model: Poco F3 6/128G
- CPU architecture: aarch64
- Android version: 12.1
- PojavLauncher version: "dahlia-8-f527e8a14-v3_openjdk" gplay version "June 3"
```

### Anything else?

I want to thank you for the awesome work you are doing
What you're providing for the community is really useful thumbs-up for that and a deep thanks from the heart ♥

**Comment by GaucovyAero** [comment]
Well, sorry for the brutally late reply. This issue is infact caused by Android and Ctrl+Space or Shift+Space is the shortcut to changing keyboard layouts, therefore to fix this, use ToggleSneak or any other mod that has an option to toggle sprint.
