### ISSUE TITLE
Igortinixx [F-Req] <Short description>

### ISSUE THREAD

**Issue by Igortinixx** [PojavLauncherTeam/PojavLauncher#3435]
### Is this request related to a bug?

![unnamed](https://user-images.githubusercontent.com/109243040/178976986-64aa35f1-9a22-429e-9e74-dd6bc711051a.jpg)

### Describe the request.

Hello

### Anything else?

Hello

**Comment by miggythewriter** [comment]
Wtf

**Comment by mchnjt** [comment]
> ### Is this request related to a bug?
> ![unnamed](https://user-images.githubusercontent.com/109243040/178976986-64aa35f1-9a22-429e-9e74-dd6bc711051a.jpg)
> 
> ### Describe the request.
> Hello
> 
> ### Anything else?
> Hello

hi
![Screenshot_20220712-091259](https://user-images.githubusercontent.com/83752061/178980987-0001dc56-c12d-4750-9326-a47f8d288942.png)

**Comment by InfiniXDerg** [comment]
Frpeos

**Comment by Bel69420** [comment]
![Uploading 987546100632281118.png…]()

**Comment by mchnjt** [comment]
why

**Comment by Bel69420** [comment]
:HYPERROFEL:

**Comment by ghost** [comment]
imagine
