### ISSUE TITLE
[BUG] Shift Key Malfunction In Pojav

### ISSUE THREAD

**Issue by DirectiveTaurus** [PojavLauncherTeam/PojavLauncher#3437]
### Describe the bug

When i Open my inventory or Chests And use shift to Move things quickly and then released the shift key the Shift key  action stays Hold in Pojav Launcher. And sometimes the shift key don't work when we open the inventory .. it used to be okay in the previous version where we could use the Offline acc.

### The log file and images/videos

GitHub is not letting me upload a video soo here's the link to mediafire 

### Steps To Reproduce

```markdown
• Open inventory or chest
Hold shift key 
Move things with shift key
Release the shift key (you'll see the shift key action stays like that)
• Open Inventory or chest
Move things before Using shift key 
Then try to use shift key (you'll see the shift key wont work )
```

### Expected Behavior

I want the shift key to work properly 

### Platform

```markdown
- Device model: oppo Reno 5 pro 
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: [Latest Release || version dahlia-8-f527e8a14-v3_openjdk
```

**Comment by DirectiveTaurus** [comment]
https://www.mediafire.com/file/b49nyyekriewpa7/Record_2022-07-15-11-36-25_bab8561a5f94f0a53956d8cbbeaad774.mp4/file


The GitHub didn't let me Use the links too so the video is here

**Comment by swarties** [comment]
as a small fix, you can shift after closing a chest if this bug occurs

**Comment by HitmanzombieC148** [comment]
I have the same problem

**Comment by GaucovyAero** [comment]
Make sure to update your launcher first. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
