### ISSUE TITLE
[F-Req] Can Get Back To Offline Mode

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#3439]
### Is this request related to a bug?

No

### Describe the request.

Offline Account

### Anything else?

I Want A Offline Account Back For Anyone Who Didnt Have Money
Note To Dev: You App In Play Store Reached 3.7 Star Due To Local Account
Dont You Dare To Tell Me For Microsoft Sue It
Just See A Minecraft Tlauncher or Multimc It Didnt Get Sued 
If Not Just Leave You App In 3.7 or 1 star

**Comment by GaucovyAero** [comment]
We are the only actively developed mobile launcher currently, so we'll keep it as it is for the normal Minecraft Launcher. If you want to create a cracked fork of Pojav ane publish it on Play Store yourself, you're welcome, but we won't do it for you.

**Comment by miggythewriter** [comment]
Broke ass

**Comment by thegarykun** [comment]
> Dont You Dare To Tell Me For Microsoft Sue It, Just See A Minecraft Tlauncher or "Multimc" It Didnt Get Sued

multimc? they require an online account bruh

**Comment by CriticalRange** [comment]
> > Dont You Dare To Tell Me For Microsoft Sue It, Just See A Minecraft Tlauncher or "Multimc" It Didnt Get Sued
> 
> multimc? they require an online account bruh

There is a GitHub Repo for multimc cracked
They are probably referencing to that.

**Comment by ssaagamemer** [comment]
Umm Fine Ima discuss on everyone that thinking a local mode

**Comment by mchnjt** [comment]
> Note To Dev: You App In Play Store Reached 3.7 Star Due To Local Account
Dont You Dare To Tell Me For Microsoft Sue It

@ssaagamemer what else?

**Comment by ssaagamemer** [comment]
idk ima closed it
