### ISSUE TITLE
LWJGL3 not installed

### ISSUE THREAD

**Issue by zScyx** [PojavLauncherTeam/PojavLauncher#344]
I have a small tiny problem it is my second time installing an apk of minecraft java, I followed the steps on the page about the apk but every time I start the version I get an error of LWJGL3 is not installed when I already enter .minecraft and extracted the file LWJGL3 Only that is my only problem since I already installed the javaruntime 32 which was the first thing that appeared to me when I opened the apk.

https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Testing-v3

**Comment by zScyx** [comment]
![Screenshot_20201006-080641_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/72448051/95205381-e7d0fd00-07aa-11eb-99d2-65e08d0f8446.jpg)

**Comment by Malaska678** [comment]
Tutorial?

**Comment by zScyx** [comment]
![Uploading Screenshot_20201006-080635_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

**Comment by khanhduytran0** [comment]
You should make sure that `lwjgl3` folder is it. **No uppercase**, no child folders inside.

**Comment by zScyx** [comment]
![Screenshot_20201006-084254_My Files](https://user-images.githubusercontent.com/72448051/95209426-f4a41f80-07af-11eb-8221-4ae5f71b39e0.jpg)
![Screenshot_20201006-084257_My Files](https://user-images.githubusercontent.com/72448051/95209441-f8d03d00-07af-11eb-85b3-1cf13a4545f3.jpg)

**Comment by WesleyVanNeck** [comment]
folders is wrong

**Comment by zScyx** [comment]
As they are wrong even deleting the zip I get the same message. as I said I just followed the steps of the page

**Comment by zScyx** [comment]
Sorry if you understand the words I say in a bad way, I use a translator

**Comment by khanhduytran0** [comment]
> Download lwjgl3-lwjgl2bridge.zip, then extract to /sdcard/games/.minecraft/**lwjgl3** directory, create if not exists.

The folder name must be **lwjgl3** instead of **lwjgl3-lwjgl2bridge**.

**Comment by zScyx** [comment]
I just have to change the name right? I'll see if you let me if I do that, I'm coming

**Comment by khanhduytran0** [comment]
Yeah. You just need rename it to lwjgl3 and try again.

**Comment by ghost** [comment]
For me even the Minecraft folder doesn't comes up even if I installed every version of Minecraft

**Comment by khanhduytran0** [comment]
So you don't enabled hidden folder.

**Comment by ghost** [comment]
Here's a look of it.
![Screenshot_2020-10-06-19-32-13-75](https://user-images.githubusercontent.com/70811047/95212032-e6cfb800-080a-11eb-96e5-64e250034e42.png)
![Screenshot_2020-10-06-19-32-57-13](https://user-images.githubusercontent.com/70811047/95212061-efc08980-080a-11eb-98ae-0e0ab89f7a26.png)
![Uploading Screenshot_2020-10-06-19-33-05-36.png…]()

**Comment by ghost** [comment]
What is that. How do we do that ?

**Comment by zScyx** [comment]
Well it worked for me and everything but since the mouse or the same touch does not recognize it, the background animation sticks but when I move the mouse through the buttons it is selected but when I click it it does not accept it haha I am bad at this, but thanks for helping me

**Comment by ghost** [comment]
The pojav launcher I downloaded is v3 testing

**Comment by ghost** [comment]
How do we enable hidden folders ?

**Comment by zScyx** [comment]
How to open the hidden folders, I didn't know that to me, the file extractor came by default since I use a Samsung a10

**Comment by ghost** [comment]
> So you don't enabled hidden folder.

How do we do that?😅😅

**Comment by zScyx** [comment]
![Screenshot_20201006-085511_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/72448051/95213458-75651a80-07b4-11eb-893b-2f9d46f220de.jpg)

**Comment by ghost** [comment]
How do enable hidden folders.
Please help me

**Comment by zScyx** [comment]
> ¿Cómo habilitar carpetas ocultas?
> por favor, ayúdame

What appears to you in the 3 dots? could you click them?

**Comment by ghost** [comment]
I'm such a fool.
I already installed zarchiver and it already has show hidden files in the settings.😲😲😲

**Comment by zScyx** [comment]
Te mamaste jaja

**Comment by ghost** [comment]
> Te mamaste jaja

I can't understand what you are saying

**Comment by ghost** [comment]
Plis tell me 
How do you transfer the lwjgl3 to pojav launcher

**Comment by ghost** [comment]
Ok now that I did it after 30 mins of chatting. 
Thanks zScyx
