### ISSUE TITLE
[BUG] Game crashed when using internal shader on Optifine

### ISSUE THREAD

**Issue by takofaru** [PojavLauncherTeam/PojavLauncher#3440]
### Describe the bug

All good when opening Minecraft but when join a world, it crashed with code 1 when using internal shader on Optifine. Turning it off doesn't crash my game

### The log file and images/videos

[latestlog.txt](https://pastebin.com/Phm808HZ)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start Minecraft 1.18.2 - 1.19 with holy gl4es
3. Go to Options/Video Settings/Shaders/(Internal)
4. Go to any world
```

### Expected Behavior

I expected to play the game normally

### Platform

```markdown
- Device model: Redmi 6
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

### Anything else?

Also occurs to Redmi 9C with CPU architecture aarch64 on 32-bit mode

**Comment by NotAHero04** [comment]
Simply don't use it. What do you expect from the internal shaders?

**Comment by takofaru** [comment]
idk, perfomance I think. I always use it for decreasing render quality before the latest release

**Comment by NotAHero04** [comment]
There's an option to decrease the game resolution in the launcher settings.

**Comment by takofaru** [comment]
tried that, not fan of it. Ik, it's a stupid reason. I do use it

**Comment by maxim-lol** [comment]
У меня когда запускаю шейдеры в поджав лаунчере в мире чёрный экран и вылетают в чате ошибке это можно как-то исправить?
