### ISSUE TITLE
[BUG] <Short description> Ошибка приложения/игры с кодом -1

### ISSUE THREAD

**Issue by Ray0YT** [PojavLauncherTeam/PojavLauncher#3441]
### Describe the bug

При запуске версии Forge 1.19 с любым модом появляется ошибка "Ошибка приложения/игры с кодом -1" 

### The log file and images/videos

![Screenshot_20220716-212346_ES File Explorer]
![Screenshot_20220716-223231_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369762-7e2e2e43-5f30-4f86-a378-f51cfa1f2b8d.jpg)
![Screenshot_20220716-223249_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369765-4d1e53e6-880c-4f1c-9a73-642edfd61c40.jpg)
![Screenshot_20220716-223301_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369766-820216f2-6087-4927-be42-872061c6faf2.jpg)
![Screenshot_20220716-223314_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369767-13d076b1-c4bd-4d8c-8159-6967cd3989bd.jpg)
![Screenshot_20220716-223327_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369768-f887400e-3044-4c30-ba96-24150b1d5ee3.jpg)
![Screenshot_20220716-223339_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369769-8b2a665c-4912-4821-9598-5628ae83cff4.jpg)
![Screenshot_20220716-223352_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369770-96156803-8caa-43b1-99e1-127890392ae5.jpg)
![Screenshot_20220716-223408_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369771-d39e4a86-7b85-4164-8760-e64562bcee39.jpg)
![Screenshot_20220716-223425_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369773-0d80f3b8-b56f-4b98-8a0a-eb9c072e0265.jpg)
![Screenshot_20220716-223438_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369774-7d6763f6-8378-45c3-9b3f-af1759ed43b5.jpg)
![Screenshot_20220716-223456_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369775-174b1708-df44-43b2-8a47-1b99df76532e.jpg)
![Screenshot_20220716-223520_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369776-c499b5ff-3120-4da7-b094-43206d653a9a.jpg)
![Screenshot_20220716-223537_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369777-8e8cc715-1497-4f4b-8270-2f1524baa906.jpg)
![Screenshot_20220716-223550_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369778-88f19ce7-fa03-4338-88ec-df10c03c1e94.jpg)
![Screenshot_20220716-223612_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369780-850c6836-44b8-42e0-98b1-badadf7ad605.jpg)
![Screenshot_20220716-223624_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369782-90558ff4-4f6d-4272-b60b-96a71d772952.jpg)
![Screenshot_20220716-223641_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369783-926f2a2f-d37f-4e6e-b8bb-53318509ad8f.jpg)
![Screenshot_20220716-223656_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369784-869b0226-d7ca-436e-8e27-6affb21adf91.jpg)
![Screenshot_20220716-223708_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369785-c065eee9-d183-46a0-988b-facec9ded310.jpg)
![Screenshot_20220716-223721_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369786-c71de7cb-c30b-40ae-bfb6-e26b3e19551b.jpg)

![Screenshot_20220716-212404_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369761-5943330c-2077-461d-9329-90139a325029.jpg)
(https://user-images.githubusercontent.com/104714842/179369759-77cdf1c4-4a25-4d3b-a2fd-fd9933c3ccf8.jpg)
![Screenshot_20220716-212355_ES File Explorer](https://user-images.githubusercontent.com/104714842/179369760-fe9006fd-279d-4df7-9205-8df020d028b9.jpg)

### Steps To Reproduce

```markdown
1. Запустите Pojav launcher
2. Запустить Forge 1.19 с любым модом
3 Увидеть Ошибка приложения/игры с кодом -1
```

### Expected Behavior

Я ожидал увидеть запуск игры.

### Platform

```markdown
- Device model: Samsung A51
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Последняя версия
```

### Anything else?

При запуске версии Forge 1.19 с любым модом появляется ошибка "Ошибка приложения/игры с кодом -1"

**Comment by f1refa11** [comment]
Да блин нельзя ли было описать проблему на английском языке? Да и к тому же можно было отправить файл лога на pastebin и кинуть ссылку

**Comment by Mathias-Boulay** [comment]
#1948
