### ISSUE TITLE
[F-Req] add scroll wheel 

### ISSUE THREAD

**Issue by Mahipal2007** [PojavLauncherTeam/PojavLauncher#3442]
### Is this request related to a bug?

Kinda

### Describe the request.

Hi i play using pojav but i can't use mouse and my mobile is c type to kinda difficult to get mouse on this so can you add scroll up and down or its already there if it is pls tell where is it i can't find it

### Anything else?

It's definately needed for people like me who aren't able to connect a mouse

**Comment by Mahipal2007** [comment]
Reply?

**Comment by GaucovyAero** [comment]
> ### Is this request related to a bug?
> Kinda
> 
> ### Describe the request.
> Hi i play using pojav but i can't use mouse and my mobile is c type to kinda difficult to get mouse on this so can you add scroll up and down or its already there if it is pls tell where is it i can't find it
> 
> ### Anything else?
> It's definately needed for people like me who aren't able to connect a mouse

scroll up and down doesnt really work
