### ISSUE TITLE
[BUG] Crash 

### ISSUE THREAD

**Issue by Mahipal2007** [PojavLauncherTeam/PojavLauncher#3443]
### Describe the bug

Application exited with code 1
And the game crashes when ever I use a mod require essential like skytils or scrollable tooltips

### The log file and images/videos

>
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9132666/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install pojav launcher
2. Install forge 1.8.9
3. Download skytils or scrollable tooltips mod 
4. Put the skytils or tooltips in mods folder 
5. Launch pojavlauncher and select forge 
6. Click on play
7. Continue if doesn't crash go on multiplayer and join hypixel or any server
```

### Expected Behavior

Expected behaviour : To launch and play without crash

### Platform

```markdown
- Device model: Vivo v2130
- CPU architecture: arm64-v8a 8th generation/AArch64
- Android version: 12 
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

**Comment by Mahipal2007** [comment]
Reply?

**Comment by GaucovyAero** [comment]
`[14:21:18] [Client thread/ERROR]: Exception caught during firing event io.github.moulberry.notenoughupdates.events.RepositoryReloadEvent@4d9c5461`

as you may not know yet, long story short, skyblock modders strictly dislike pojav and they will never support it in the future.

**Comment by Mahipal2007** [comment]
There is no problem with neu it runs perfectly , the problem is those mods who use essential
