### ISSUE TITLE
Bookcover Keyboard Touchpad Not Working In PojavLauncher

### ISSUE THREAD

**Issue by SiegemusDaBoss** [PojavLauncherTeam/PojavLauncher#3446]
### Is this request related to a bug?

No, at least I don't think so.

### Describe the request.

I would like for the touchpad on the Samsung Bookcover Keyboard for the Samsung Galaxy Tab S7 to act like a cursor instead of a button press.

### Anything else?

When my keyboard is connected to my tablet physically, I try to use the touchpad in game. When the game boots up, instead of the cursor highlighting the different menu options, it doesn't highlight anything until i left-click with one finger. When I do, it just acts like a really quick button press. In-game, instead of moving my character around like a normal mouse would, it just goes across the screen. I also have to use two fingers just to left click and move my character. I also can't right click.

**Comment by Mathias-Boulay** [comment]
@SiegemusDaBoss Can you check the last action build ?
It should work now, but I need confirmation

**Comment by GaucovyAero** [comment]
Yeah, make sure to update your launcher. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`

**Comment by SiegemusDaBoss** [comment]
Hello! I'm trying to download and install the latest version (the one with a red x mark) in the actions build, but it's not working. I noticed that the latest green check mark build was posted about 3 days ago. Is that the on you want me to download, or am i doing something wrong?

**Comment by GaucovyAero** [comment]
> Hello! I'm trying to download and install the latest version (the one with a red x mark) in the actions build, but it's not working. I noticed that the latest green check mark build was posted about 3 days ago. Is that the on you want me to download, or am i doing something wrong?

download the one with the green checkmark on it

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
