### ISSUE TITLE
[BUG] Can't log into my microsoft account

### ISSUE THREAD

**Issue by Mack3133** [PojavLauncherTeam/PojavLauncher#3448]
### Describe the bug

When im trying to log into my microsoft account i got an error saying: "couldnt load page ...login.live.com.... because net::ERR_NAME_NOT_RESOLVED. I have faced this bug before. I think it might be web browser engine problem but im not sure. Any ideas / help?

https://user-images.githubusercontent.com/109618481/180160945-19767083-23d8-48fa-bc4c-055b6211d7a6.mp4

### The log file and images/videos

https://user-images.githubusercontent.com/109618481/180160945-19767083-23d8-48fa-bc4c-055b6211d7a6.mp4

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. click Microsoft login
```

### Expected Behavior

I expect the game to login into my Microsoft account

### Platform

```markdown
- Device model: Samsung Galaxy a12
- CPU architecture: ARM
- Android version: 11
- PojavLauncher version: Latest available on google store
```

**Comment by Mack3133** [comment]
day after i wrote this post, i was able to log into my microsoft account, but something wanted to ruin my happiness, today when i tried to login it refused to work again 😢

**Comment by khanhduytran0** [comment]
We have got a couple of cases recently with the same problem. Probably ISP/country blocked it? Anyways, VPN is your friend. You should give it a try.

**Comment by Mack3133** [comment]
the thing is that like 2,5 monts ago and a day before yesterday i was able to login normally :/. well ill try norton vpn

**Comment by Mack3133** [comment]
yo thanks! that trick with vpn works!
