### ISSUE TITLE
cant use Microsoft to login

### ISSUE THREAD

**Issue by ajjxf** [PojavLauncherTeam/PojavLauncher#3449]
### Describe the bug

![Screenshot_20220722_182456_net kdt pojavlaunch](https://user-images.githubusercontent.com/109795978/180422465-6ba6aa31-2220-4572-bed2-26ebcd401004.jpg)
![Screenshot_20220722_182042_net kdt pojavlaunch](https://user-images.githubusercontent.com/109795978/180422478-5298a299-5d41-4f69-8fd6-bd947caffa57.jpg)

### The log file and images/videos

![Screenshot_20220722_183413_com android settings](https://user-images.githubusercontent.com/109795978/180421795-09b4650e-77ab-4ebb-bd49-4573bf621887.jpg)

### Steps To Reproduce

```markdown
i'm in China and I use Microsoft to login.but…I just can't login…
```

### Expected Behavior

I finally found this minecraft(java) after weeks of searching,and I wanted to build some redstone machines. but when I opened this,I'm sad :( because I can't login… surely,anyone won't want this to happen…

### Platform

```markdown
- Device model: i'v put a screen shot on <The log file and images/videos>
- CPU architecture: ^
- Android version: ^
- PojavLauncher version: ^
```

### Anything else?

ps:I don't know why,but I can't put MPs here neither. 
uploading… and then,it's gone!

**Comment by miggythewriter** [comment]
You need to buy minecraft Java and then log in with Microsoft
