### ISSUE TITLE
[BUG] When clicking  and turning mouse sensitivity becomes laggy

### ISSUE THREAD

**Issue by swarties** [PojavLauncherTeam/PojavLauncher#3451]
### Describe the bug

Basically when you click on minecraft 1.8 and you turn your mouse to any direction, sensitivity becomes laggy but there's no fps drop. It's a bit like if clicking paused the sensitivity.

### The log file and images/videos

https://www.mediafire.com/file/qoinwzfebvd5qz6/Screen-record-1822b9a0f47.mp4/file

### Steps To Reproduce

```markdown
1. Start PojavLauncher on 1.8.9
2. Connect to a server
3. Click and turn your mouse
4. Enjoy Lag
```

### Expected Behavior

i expect the sensitivity to stay normal and don't lag

### Platform

```markdown
- Device model: Samsung Galaxy Tab A7
- CPU architecture: 
- Android version: 12
- PojavLauncher version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2721396214
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
Samsung issues right here I think. Because I've also had this issue on my Galaxy S7 Edge that was running Android 8.0.0. I thought it was an "old android" issue, so I flashed to LineageOS 19.1 running Android 12 and never had issues again. But it may just be the fact that it's the Samsung distribution of Android and therefore has these issues. Probably the only thing you can do to fix this is just change to a different rom (like LineageOS 19.1, Android 12 for example).

**Comment by swarties** [comment]
> Samsung issues right here I think. Because I've also had this issue on my Galaxy S7 Edge that was running Android 8.0.0. I thought it was an "old android" issue, so I flashed to LineageOS 19.1 running Android 12 and never had issues again. But it may just be the fact that it's the Samsung distribution of Android and therefore has these issues. Probably the only thing you can do to fix this is just change to a different rom (like LineageOS 19.1, Android 12 for example).

The bug only occurs on pojavlauncher not on the tablet + I don't want to flash a new rom

**Comment by Mathias-Boulay** [comment]
pojav treats mouse events as soon as they are passed to us

**Comment by Kishan7771** [comment]
I am also having same problem in galaxy A23 what is the fix

**Comment by GaucovyAero** [comment]
> I am also having same problem in galaxy A23 what is the fix

no fix for now

**Comment by rizky534** [comment]
I am also having the same problem on Infinix hot 12 play what is the way to fix it?, I am very uncomfortable

**Comment by magic99xd** [comment]
Ya I am asking for too long to get it fixed but still no response and I am in android 14 still I feel lag while moving my mouse
