### ISSUE TITLE
[BUG] virgls broken rendering on 1.18.2

### ISSUE THREAD

**Issue by USMP-lancer** [PojavLauncherTeam/PojavLauncher#3452]
### Describe the bug

this bug causes text rendering to stop and transparencies to fail

### The log file and images/videos

![Screenshot_20220723-001333](https://user-images.githubusercontent.com/42185819/180614890-83b238fb-2187-459e-96ea-446e7e1f9edd.png)
![Screenshot_20220723-110930](https://user-images.githubusercontent.com/42185819/180614898-34fb42b2-88b3-49d1-ae9a-53deb5e93a9e.png)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9174207/latestlog.txt)

### Steps To Reproduce

```markdown
set your renderer to virgl
get a 1.18 release
enjoy?
```

### Expected Behavior

i expect text to render and it not to do this wierd transparency thing( for comparism holy gl works fine, and virgl on older versions does as well)

### Platform

```markdown
- Device model:tcl 5g uw
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: action debug build, action run id:2721396214
```

### Anything else?

the mirrored rendering of the ingame image is caused upon world generation, and does not occur if a pregenerated world is loaded

**Comment by GaucovyAero** [comment]
this is kinda normal, because your CPU is a Snapdragon 765G. for reliable gameplay with VirGL, you either need Mali (if you don't want to run shaders) or Snapdragon 8xx (if you want to run shaders).

**Comment by USMP-lancer** [comment]
so im stuck with either this or not able to play create, h

**Comment by USMP-lancer** [comment]
so essentially, i gotta wait for devs to fix flywheel
