### ISSUE TITLE
[BUG] Forge crashes, same for Vanilla

### ISSUE THREAD

**Issue by 320kg** [PojavLauncherTeam/PojavLauncher#3453]
### Describe the bug

My friend tried to install Minecraft 1.16.5 with Forge, Optifine, AimAssistance, OfflineSkins, OpenLoader, U Team Core and Trajectory Preview, but it failed with error `java.lang.NoClassDefFoundError: com/google/common/base/Preconditions` at `org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.offer(MixinTransformationHandler.java:67)` , even thought this setup works on my PC. 
He also tried to use Vanilla 1.16.5, but the play button was gray.
We spent 3 hours trying to fix this issue.

### The log file and images/videos

![Capture_2022-07-23-22-10-30](https://cdn.discordapp.com/attachments/1000088090049773771/1000480107795845140/Capture_2022-07-23-22-10-30.jpg)
[latestlog.txt](https://cdn.discordapp.com/attachments/1000088090049773771/1000476472470949968/latestlog.txt)
[latestcrash.txt](https://cdn.discordapp.com/attachments/1000088090049773771/1000476472261222420/latestcrash.txt)

### Steps To Reproduce

```markdown
1 Install OpenJDK 17 for arm from [here](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559)
2 Install Forge 1.16.5 - 36.2.39 through "Install .JAR" button
3 Install Optifine 1.16.5 HD U G8, OpenLoader 1.16.5 9.0.2, OfflineSkins 1.16.5 v1a, U Team Core 1.16.5 3.2.1.195, TrajectoryPreview 3.0.2 1.16.4 and Aim Assistance 1.4.0 MC1.16.x (CurseForge versions) by copying into `/sdcard/games/PojavLauncher/.minecraft/mods/`.
4 Launch the game through automatically generated forge profile.
```

### Expected Behavior

The game launches with all of those mods working

### Platform

```markdown
- Device model: LG M320
- CPU architecture: ARM64 v8 (running 32-bit Android, PojavLauncher and OpenJDK (arm32))
- Android version: 7.0 
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

### Update:
The "Play" button is not grayed out for Vanilla now, but it fails to load the main class (see later comments).

**Comment by GaucovyAero** [comment]
Thank you for being intelligent in this thread, but I personally think all you need is switch to Java 8. Only MC versions higher than 1.17 need Java 17.

**Comment by 320kg** [comment]
> Thank you for being intelligent in this thread, but I personally think all you need is switch to Java 8. Only MC versions higher than 1.17 need Java 17.

Nothing happened, still the same error

**Comment by GaucovyAero** [comment]
> > Thank you for being intelligent in this thread, but I personally think all you need is switch to Java 8. Only MC versions higher than 1.17 need Java 17.
> 
> Nothing happened, still the same error

Show the log with Java 8 I guess...

**Comment by 320kg** [comment]
> > > Thank you for being intelligent in this thread, but I personally think all you need is switch to Java 8. Only MC versions higher than 1.17 need Java 17.
> > 
> > 
> > Nothing happened, still the same error
> 
> Show the log with Java 8 I guess...

It's exact same as with Java 17 [latest.log](https://cdn.discordapp.com/attachments/999366083179991070/1000493782384521296/latestlog.txt)

**Comment by GaucovyAero** [comment]
> > > > Thank you for being intelligent in this thread, but I personally think all you need is switch to Java 8. Only MC versions higher than 1.17 need Java 17.
> > > 
> > > 
> > > Nothing happened, still the same error
> > 
> > 
> > Show the log with Java 8 I guess...
> 
> It's exact same as with Java 17 [latest.log](https://cdn.discordapp.com/attachments/999366083179991070/1000493782384521296/latestlog.txt)

Yeah, I think it could only be one or more mods. Try removing them by half and see which half works, then half the not working half and so on.

**Comment by 320kg** [comment]
> > > > Thank you for being intelligent in this thread, but I personally think all you need is switch to Java 8. Only MC versions higher than 1.17 need Java 17.
> > > 
> > > 
> > > Nothing happened, still the same error
> > 
> > 
> > Show the log with Java 8 I guess...
> 
> It's exact same as with Java 17 [latest.log](https://cdn.discordapp.com/attachments/999366083179991070/1000493782384521296/latestlog.txt)

So, he deleted `.minecraft/libraries/org/spongepowered/mixin/` leftover by a mod we used before and now I get a completely different error [latestlog.txt](https://cdn.discordapp.com/attachments/999366083179991070/1000496764698251304/latestlog.txt).
Now for 1.16.5, the play button is not grayed out, but it's unable to load up the main class [latestlog.txt](https://cdn.discordapp.com/attachments/999366083179991070/1000498023362728017/latestlog.txt)

**Comment by GaucovyAero** [comment]
```
Error: Unable to initialize main class net.minecraft.client.main.Main
Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionSpec
```

yeah, some libs are definitely missing

**Comment by miggythewriter** [comment]
"Offlineskins" definitely pirate

**Comment by mchnjt** [comment]
> "Offlineskins" definitely pirate

~~This mod allows you to show off your skins even if the server is in offline mode, in case of your normal skin doesn't load. Stop looking at mods where ones install it you look them up as a pirate.~~ UUID is in 32 zeros. Guess i need to look into logs sometimes.
