### ISSUE TITLE
[F-Req] <Fix PojavLauncher uses Battery Usage so much.>

### ISSUE THREAD

**Issue by ProSteve12301** [PojavLauncherTeam/PojavLauncher#3457]
### Is this request related to a bug?

Fix it please because i want play Pojav with Keyboard and Mouse its Draining Battery so much.I playing pojav while charging so fix it please.

### Describe the request.

Tweak or add some stuff on PojavLauncher to fix the battery drain.

### Anything else?

PojavLauncher uses 50% of an 1% percent of battery so fix it please.

**Comment by WesleyVanNeck** [comment]
You have a lazy battery probably not our issue

**Comment by ProSteve12301** [comment]
> You have a lazy battery probably not our issue

Not the battery cuz 2 more pojav player(discord) proves that pojav is uses battery badly.Even i downgrade it use battery 2x that gplay update.So fix it please my phone was high end not lowend.

**Comment by crystall1nedev** [comment]
You're playing a game that was designed to run on desktop computers rather than mobile phones. The only real way to solve the battery issues would be to run Java in a slower mode, with lower graphics settings, or just not at all.

Closing this issue as we can't really fix this.
