### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by LevelOzone** [PojavLauncherTeam/PojavLauncher#3458]
### Describe the bug

application exited with code one 
When i load up 1.18 the game crashes 

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: dahlia-8-f527e8a14-v3_openjdk
Info: LWJGL3 directory: [version, lwjgl-glfw-classes.jar]
Architecture: x86_64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18
--------- beginning of system

--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1368
Added custom env: POJAV_NATIVEDIR=/data/app/~~JbZQHQafaLth9o3fI1Z5Xw==/net.kdt.pojavlaunch-U5USLQ2etB6L19i8419yYQ==/lib/x86_64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~JbZQHQafaLth9o3fI1Z5Xw==/net.kdt.pojavlaunch-U5USLQ2etB6L19i8419yYQ==/lib/x86_64
Added custom env: POJAV_RENDERER=opengles3
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=768
I/LIBGL   (30666): Initialising gl4es
I/LIBGL   (30666): v1.1.4 built on May 28 2022 20:24:57
I/LIBGL   (30666): Using GLES 2.0 backend

I/LIBGL   (30666): loaded: libGLESv2.so
I/LIBGL   (30666): loaded: libEGL.so

I/LIBGL   (30666): Using GLES 2.0 backend

I/LIBGL   (30666): Hardware Full NPOT detected and used
I/LIBGL   (30666): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (30666): Extension GL_EXT_draw_buffers  detected and used
I/LIBGL   (30666): FBO are in core, and so used
I/LIBGL   (30666): PointSprite are in core, and so used
I/LIBGL   (30666): CubeMap are in core, and so used
I/LIBGL   (30666): BlendColor is in core, and so used
I/LIBGL   (30666): Blend Substract is in core, and so used
I/LIBGL   (30666): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (30666): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (30666): Extension GL_OES_mapbuffer  detected
I/LIBGL   (30666): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (30666): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (30666): Extension GL_OES_depth24  detected and used
I/LIBGL   (30666): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (30666): Extension GL_EXT_multi_draw_arrays  detected
I/LIBGL   (3066
6): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (30666): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (30666): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (30666): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (30666): Extension GL_OES_texture_float  detected and used
I/LIBGL   (30666): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (30666): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (30666): Extension GL_EXT_color_buffer_half_float  detected and used

I/LIBGL   (30666): high precision float in fragment shader available and used
I/LIBGL   (30666): Extension GL_EXT_frag_depth  detected and used
I/LIBGL   (30666): Max vertex attrib: 16
I/LIBGL   (30666): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (30666): Max texture size: 16384
I/LIBGL   (30666): Max Varying Vector: 32
I/LIBGL   (30666): Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
I/LIBGL   (30666): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (30666): Max Anisotropic filtering: 16
I/LIBGL   (30666): Hardware vendor is Mesa/X.org
I/LIBGL   (30666): GLSL 300 es supported
I/LIBGL   (30666): GLSL 310 es supported and used
I/LIBGL   (30666): GLSL 320 es supported
I/LIBGL   (30666): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (30666): sRGB surface supported
I/LIBGL   (30666): EGLImage to Texture2D supported
I/LIBGL   (30666): EGLImage to RenderBuffer supported

I/LIBGL   (30666): ignore MipMap
I/LIBGL   (30666): Targeting OpenGL 2.1
I/LIBGL   (30666): No hack in shader converter to define overloaded function with int
I/LIBGL   (30666): NPOT texture handled in hardware
I/LIBGL   (30666): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (30666): try to use VBO
I/LIBGL   (30666): glX Will try to recycle EGL Surface
I/LIBGL   (30666): Current folder is:/
I/jrelog  (30666): dlopen libgl4es_114.so success
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjli.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjli.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/l
ib/server/libjvm.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libverify.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libverify.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjava.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjava.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnet.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnet.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnio.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnio.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt.so" is 32-bit instead of 6
4-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt_headless.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt_headless.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfreetype.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfreetype.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfontmanager.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfontmanager.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libattach.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libattach.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libzip.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libzip.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt_headless.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt_headless.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjavajpeg.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjavajpeg.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement_agent.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement_agent.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjaas.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjaas.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnet.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/l
ib/libnet.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libverify.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libverify.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/librmi.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/librmi.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libj2gss.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86
-20220225-release.tar.xz/lib/libj2gss.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libsyslookup.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libsyslookup.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libinstrument.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libinstrument.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libsctp.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libsctp.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjsig.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjsig.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfreetype.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfreetype.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjdwp.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjdwp.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjsig.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjsig.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/server/libjvm.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/liblcms.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/liblcms.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libdt_socket.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/l
ib/libdt_socket.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement_ext.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmanagement_ext.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjava.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjava.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libj2pkcs11.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libj2pkcs11.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libnio.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/l
ibnio.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libprefs.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libprefs.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjimage.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjimage.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjli.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjli.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libmlib_image.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225
-release.tar.xz/lib/libmlib_image.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjawt.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libjawt.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfontmanager.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libfontmanager.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libj2pcsc.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libj2pcsc.so" is 32-bit instead of 64-bit
I/jrelog  (30666): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libextnet.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/jre17-x86-20220225-release.tar.xz/lib/libextnet.so" is 32-bit instead of 64-bit

I/jrelog  (30666): dlopen /data/app/~~JbZQHQafaLth9o3fI1Z5Xw==/net.kdt.pojavlaunch-U5USLQ2etB6L19i8419yYQ==/lib/x86_64/libopenal.so success

I/jrelog  (30666): Done processing args

I/jrelog  (30666): JLI lib = NULL: dlopen failed: library "libjli.so" not found
I/jrelog  (30666): Going to free args
I/jrelog  (30666): Free done

Java Exit code: -1

### Steps To Reproduce

```markdown
start launcher
Log in
Select 1.18 
Start game 
Crashes with code 1 exit
```

### Expected Behavior

expect the game to load 

### Platform

```markdown
- Device model: Acer Chromebook R752TN-C1MT
- CPU architecture: Intel(R) Celeron(R) N4020 CPU @ 1.10GHz   (i dont really know what this is. 86x64?)
- Android version: 11
- PojavLauncher version: 1.18
```

**Comment by khanhduytran0** [comment]
You have installed 32bit Java on 64bit environment. You should have noticed the red line `Incompatible architecture`
Additionally, use the `app-debug` (not the `noruntime` build) to have Java 17 installed on-demand.
