### ISSUE TITLE
[BUG] Forge 1.19 Crashes

### ISSUE THREAD

**Issue by RedbedMCPojav** [PojavLauncherTeam/PojavLauncher#3459]
### Describe the bug

I tried running Forge 1.19 with Optifine and Worldedit and it kept saying "Application exited with code -1" Do y'all know a fix for this?

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9190937/latestlog.txt)
![Screenshot_2022-07-26-23-01-36-179_net kdt pojavlaunch](https://user-images.githubusercontent.com/96370527/181041651-af58fc1c-fcf3-48c5-b36f-693d2eebf3a9.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch Forge 1.19 (with optifine and worldedit)
3. In a couple seconds it says "Application exited with code -1"
```

### Expected Behavior

I expected it to lauch properly but ig not

### Platform

```markdown
- Device model: POCO X3 GT 
- CPU architecture: aarch64 
- Android version: 11
- PojavLauncher version: PlayStore version
```

**Comment by 0bla4k0** [comment]
I also have

**Comment by krokiecikpl** [comment]
Becuse optifine awlays crash in this version on forge

**Comment by RedbedMCPojav** [comment]
> Becuse optifine awlays crash in this version on forge

Ok I'll try older version of forge

**Comment by andrewmejico13** [comment]
andrewmeji12

**Comment by GaucovyAero** [comment]
```
java.lang.NoClassDefFoundError: net/minecraftforge/client/model/data/IModelData
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:491) ~[client-1.19-20220607.102129-srg.jar%23117!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
```

Forge made a lot of changes in this time, even PCs had this issue many times. Make sure to update Forge to the now recommended build and update your mods to the latest version.
