### ISSUE TITLE
How do I install Optifine in v3

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#346]
How do I install Optifine in the newest version?

**Comment by artdeell** [comment]
Currently it's only possible by copying already installed optifine from PC

ср, 7 окт. 2020 г., 20:25 leetmussc <notifications@github.com>:

**Comment by leetmussc** [comment]
How do I install the already copied files?

**Comment by khanhduytran0** [comment]
You may install use custom arguments.
Paste and replace parts
```
-cp [path to optifine.jar] optifine.SimpleInstaller --installClient
```

**Comment by leetmussc** [comment]
-cp /sdcard/Download/Optifine_1.12.2_HD_U_F5.jar/ optifine.SimpleInstaller --installClient

Is this correct?

**Comment by mglovers123** [comment]
https://github.com/zhuowei/Boardwalk/actions
![Uploading Screenshot_2020-10-10-23-56-29-98.jpg…]()

**Comment by leetmussc** [comment]
The image didn't upload

**Comment by leetmussc** [comment]
Where do I put the optifine files?

**Comment by khanhduytran0** [comment]
You could put anywhere that the launcher can access, then modify command to change to that path.

**Comment by leetmussc** [comment]
What would it be if I put them in the Download folder

**Comment by leetmussc** [comment]
-cp /sdcard/Download/(optifine path) /?

**Comment by leetmussc** [comment]
@mglovers123 the image didn't upload

**Comment by mglovers123** [comment]
https://nhentai.net/g/331317/

**Comment by mglovers123** [comment]
https://sokap.net/

**Comment by mglovers123** [comment]
Yhttps://nhl

**Comment by mglovers123** [comment]
Sokap niiiiccchhh

**Comment by mglovers123** [comment]
![Uploading steve.png…]()

**Comment by mglovers123** [comment]
2549640208

**Comment by khanhduytran0** [comment]
> -cp /sdcard/Download/(optifine path) /?

You mean /sdcard/Download/sdcard/Download/Optifine.path.jar?

**Comment by xXFrostXx1** [comment]
It should be like the old V2
It was installing like any normal update and then running

**Comment by xXFrostXx1** [comment]
@khanhduytran0 
It should be like the old V2
It was installing like any normal update and then running

**Comment by xXFrostXx1** [comment]
-cp /sdcard/Download/OptiFine_1.16.1_HD_U_G2.jar/

**Comment by RomanBZK-dev** [comment]
I write -cp /storage/emulated/0/Download/OptiFine_1.12.2_HD_U_F55.jar optifine.SimpleInstaller --installClient
 and get S/jrelog  (26392): Error: Could not find or load main class optifine.SimpleInstaller

**Comment by mglovers123** [comment]
> I write -cp /storage/emulated/0/Download/OptiFine_1.12.2_HD_U_F55.jar optifine.SimpleInstaller --installClient
> and get S/jrelog (26392): Error: Could not find or load main class optifine.SimpleInstaller

Install it on PC and transfer it to Mobile

**Comment by mglovers123** [comment]
Its work in pojav v3

**Comment by khanhduytran0** [comment]
Does Optifine exists on `/storage/emulated/0/Download/OptiFine_1.12.2_HD_U_F55.jar`?

**Comment by Adam0530** [comment]
> Does Optifine exists on `/storage/emulated/0/Download/OptiFine_1.12.2_HD_U_F55.jar`?

is it
