### ISSUE TITLE
Render Bug

### ISSUE THREAD

**Issue by EndMo0** [PojavLauncherTeam/PojavLauncher#3461]
### Describe the bug

**First. I have two devices with the chipsets SD665 and MTK G80**
_Both devices have the same .minecraft folder_

**The bug appears when install GalactiCraftPlanets But only**
**affects the renderer GL4 with the Chipset SD**
![Screenshot_20220726-161923_1](https://user-images.githubusercontent.com/110069891/181131371-750b24a7-f808-4b30-88c9-f0f65a931715.png)

MTK is not affected
![Screenshot_2022-07-26-16-27-32-559_net kdt pojavlaunch_1](https://user-images.githubusercontent.com/110069891/181131489-5e09d98f-e293-4207-829b-b935be57e7b5.jpg)

only disappears when change the renderer to Virgl
but is so laggy. 
![Screenshot_20220726-162242_1](https://user-images.githubusercontent.com/110069891/181131704-765dd718-944d-40db-9e7a-07a892959548.png)

vgpu was good, I don't understand why they removed it, 
it never gave me mistakes.

i used a translater maybe some things are not understood srry

### The log file and images/videos

they are not necessary but if they are I can put them

### Steps To Reproduce

```markdown
not on all devices. but install forge 1.12.2 with galacticraft and galacticraft planets
```

### Expected Behavior

bugged texture, if you have a correct device

### Platform

```markdown
- Device model:Xiaomi Mi A3 4/64
- CPU architecture: ARM 64
- Android version:11 
- PojavLauncher version: Dahlia-8-f527e8a14-v3-openjdk

- Device model:Xiaomi Redmi 9 4/64
- CPU architecture: ARM 64
- Android version:10
- PojavLauncher version: Dahlia-8-f527e8a14-v3-openjdk
```

### Anything else?

add other renderers

**Comment by GaucovyAero** [comment]
well, the issue is that you are out of video memory, you can't fix this on your sd665.

**Comment by Mathias-Boulay** [comment]
This issue is no more on current dev builds, closing.
