### ISSUE TITLE
[BUG] fabric 1.17.1+performance mods crashing

### ISSUE THREAD

**Issue by PojavLauncherOGGamers** [PojavLauncherTeam/PojavLauncher#3462]
### Describe the bug

It crashing after launch the game i've already downloaded full libraries!

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1. Start fabric 
2. Put any performance mods
3. Crash
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model: Vivo y50 
- CPU architecture: Aarch64 
- Android version: 10
- PojavLauncher version: github build
```

### Anything else?

No

**Comment by miggythewriter** [comment]
The first time you install fabric and play it, you shouldn't add any mods

**Comment by GaucovyAero** [comment]
please send latestlog.txt
