### ISSUE TITLE
[BUG] I Can't connect to cracked servers

### ISSUE THREAD

**Issue by Amirsunrise** [PojavLauncherTeam/PojavLauncher#3463]
### Describe the bug

Hello
Pojavlauncher has a problem for me and that is that I can't login to my free Aternos server its says pinging...
And when i want to enter it says failed to connect to server. (my cracked option in Aternos is on)
(It's not Aternos' problem because Pojavlauncher has this problem with Ploudos as well, and my friend who has the same internet as me can log in with PC)
I can only log in using vpn, but it's really hard to play with vpn
Please help if there is a solution and if there is nothing you can do, please fix it in the next update
Thankful

### The log file and images/videos

![IMG_20220727_071308](https://user-images.githubusercontent.com/110076470/181149303-36c0e775-e1ae-44bf-af9f-d9201033af06.jpg)
![Screenshot_2022-07-27-06-40-31-576_net kdt pojavlaunch](https://user-images.githubusercontent.com/110076470/181149322-70fdfe53-beff-48de-a488-7f15ca3e83ea.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9199156/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.run 1.19 (forge/OptiFine)
3.select multiplayer
4.try to login in my server(pinging...)
5.click on join server after a few seconds..
6.timeout failed to connect to the server
```

### Expected Behavior

Pls someone help or pls fix it in next update 🙏

### Platform

```markdown
- Device model: redmi note 8 pro 
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

**Comment by Amirsunrise** [comment]
Please someone help me because I have been dealing with this problem for about a month🙏🙏

**Comment by EnderPluser** [comment]
Do you use Mojang account? If yes, migrate it since mojang account is pretty much dead and that's the only way

**Comment by EnderPluser** [comment]
also close this

**Comment by Amirsunrise** [comment]
Im using offline account.

**Comment by mchnjt** [comment]
> Im using offline account. My friend use offline account too but he can join with pc

tlauncher? sus
anyways, no support for you

**Comment by Amirsunrise** [comment]
Nice🙃🗿
