### ISSUE TITLE
Gamepass accounts 

### ISSUE THREAD

**Issue by dummy22328** [PojavLauncherTeam/PojavLauncher#3464]
### Is this request related to a bug?

No

### Describe the request.

If you have Bedrock on the Xbox Gamepass you can get java for free but the account i use for gamepass when logging into pojavlauncher says i dont have an minecraft account

### Anything else?

If your account has Bedrock it should have Automatically have java

**Comment by Abhigaman** [comment]
I want account, I had already bedrock account

**Comment by mchnjt** [comment]
make unlimited java accounts at https://oracle.com <:likebhai:972012294085152828>

**Comment by Abhigaman** [comment]
How to make it

**Comment by miggythewriter** [comment]
> I want account, I had already bedrock account

It's a PC Bedrock account not a pe account

**Comment by Abhigaman** [comment]
What do you mean?

**Comment by PepsiDrxBw7** [comment]
I really wanted an original account original for me to have free skin and cosmetics and skin without having to use textures or mods
