### ISSUE TITLE
[BUG] Invalid Color Attachment error Minecraft 1.19

### ISSUE THREAD

**Issue by Furanzeru** [PojavLauncherTeam/PojavLauncher#3466]
### Describe the bug

I wanted to add a shader in Minecraft 1.19 but it gives me an error shown in the pic.
I tried adjusting some video options inside the game and it still doesn't fix the error.

-Using Virglrenderer OpenGL 4.3
-Using MakeUp Ultrafast 8.6a Shader
-Using Android 10

### The log file and images/videos

![Screenshot_2022-07-30-10-49-38-24_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/75703374/181870302-21b532d2-1daa-40e1-aac0-cf468b643049.jpg)
![Screenshot_2022-07-30-10-51-35-08_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/75703374/181870322-a2927846-f5ad-4ce3-9087-6a0072b538dd.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9224695/latestlog.txt)

### Steps To Reproduce

```markdown
1. Starting Pojavlauncher
2. Installing Optifine
3. Adding MakeUp Shader inside the game
4. Adjusting Holy gl4es to virgl
5. Launching Minecraft 1.19
6. Opening a world
7. Opengl error
```

### Expected Behavior

I expect the shader to be fixed

### Platform

```markdown
- Device model: Oppo F7 4/64G
- CPU architecture: ARM64 (I guess)
- Android version: 10
- PojavLauncher version: dahlia-35-23e8a6338-v3_openjdk
```

**Comment by miggythewriter** [comment]
You need a snapdragon cpu 8xx in order to play with shaders
