### ISSUE TITLE
[BUG] OFFLINE PLAY IS NOT POSSIBLE

### ISSUE THREAD

**Issue by AChitat** [PojavLauncherTeam/PojavLauncher#3467]
### Describe the bug

THE APPLICATION HAS BECOME ABSOLUTELY USELESS 

### The log file and images/videos

No

### Steps To Reproduce

```markdown
No
```

### Expected Behavior

No

### Platform

```markdown
- Device model: Honor 9X premium 6/128G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by khanhduytran0** [comment]
You’ll have to look at the local account first.
