### ISSUE TITLE
[BUG] Error when playing with forge

### ISSUE THREAD

**Issue by VictorNStar** [PojavLauncherTeam/PojavLauncher#3468]
### Describe the bug

Erro

java.lang.RuntimeException: Can't find the source version for 1.7.10-Forge10.13.4.1614-1.7.10 (req version=1.7.10)

### The log file and images/videos

![Screenshot_20220730-094415](https://user-images.githubusercontent.com/110292964/181916123-dc6c1ca3-4a02-4174-9cef-560379c7f621.png)

### Steps To Reproduce

```markdown
1.Started pojavlaucher 2.logged in with an account I created using javlaucher (not Microsoft account) 3.installed forge 4.started laucher with forge.
```

### Expected Behavior

Hope you fix this error

### Platform

```markdown
- Device model: Moto G60/128Gb
- CPU architecture: arm64-v8a
- Android version: 12
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

**Comment by khanhduytran0** [comment]
Without logged into online account, PojavLauncher will refuse to download anything (in this case, 1.7.10).
