### ISSUE TITLE
[BUG] <Short description>I can't use the mouse wheel.

### ISSUE THREAD

**Issue by YX-IT** [PojavLauncherTeam/PojavLauncher#3469]
### Describe the bug

The mouse wheel in the game can only switch items, but can't slide the screen up and down in the inventory.

### The log file and images/videos

Bug

### Steps To Reproduce

```markdown
I cannot use the mouse wheel.
```

### Expected Behavior

I hope your can fix it.

### Platform

```markdown
- Device model: HMA-AL00
- CPU architecture: aarch64
- Android version: HarmonyOS 2.0.0
- PojavLauncher version:
3.3.1.1_rel_20210206
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
just dont use the 1 year old version of pojav you are using currently and rather use the latest one here on pojavlauncher github in the actions tab

**Comment by YX-IT** [comment]
Thank you for your reply.However, I still have problems when I use the latest version.I  used version is :dahlia-35-23e8a6338-v3_openjdk(The last version released eight days ago.)-------- 原始邮件 --------发件人： Aerolome ***@***.***>日期： 2022年7月31日周日 16:30收件人： PojavLauncherTeam/PojavLauncher ***@***.***>抄送： YX_zimo ***@***.***>, Author ***@***.***>主    题： Re: [PojavLauncherTeam/PojavLauncher] [BUG] I can't use the mouse wheel. (Issue #3469)
just dont use the 1 year old version of pojav you are using currently and rather use the latest one here on pojavlauncher github in the actions tab

**Comment by GaucovyAero** [comment]
We are currently more active on our official PojavLauncher discord server. Join it to get faster support. The mouse scroll wheel issue may be an issue on HarmonyOS's side.

**Comment by GaucovyAero** [comment]
closing as this is a duplicate
