### ISSUE TITLE
[BUG] Exited with code 6

### ISSUE THREAD

**Issue by Ibattleu** [PojavLauncherTeam/PojavLauncher#3471]
### Describe the bug

Keeps exiting with code 6. After fixing another problem.

### The log file and images/videos

![Screenshot 2022-08-01 5 42 48 PM](https://user-images.githubusercontent.com/110431121/182257940-097d7de0-dc8e-46c2-9a12-b708cf3b850f.png)

Look in preview

### Steps To Reproduce

```markdown
https://met.game.blog/2021/09/17/jdk17-aarch64/ 32bit download set as default and hit play and wait
```

### Expected Behavior

I expected the game to launch.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Nothing else

**Comment by Ibattleu** [comment]
I used chromebook

**Comment by khanhduytran0** [comment]
You used a Java runtime downloaded from an unknown source, which may contain malicious code (more specifically, token or IP logger for example).
Since dahlia update, java 17 is installed on-demand.

**Comment by NotAHero04** [comment]
Wait, is that a common issue with x86-based machines?

**Comment by khanhduytran0** [comment]
> Wait, is that a common issue with x86-based machines?

If it is here, the dialog would have shown in the home screen instead of with buttons

**Comment by FreakyMood** [comment]
> You used a Java runtime downloaded from an unknown source, which may contain malicious code (more specifically, token or IP logger for example). Since dahlia update, java 17 is installed on-demand.

its not unknown source. Its the java runtime that you download and use it to open minecraft 1.17+ because you can not play minecraft 1.17, 1.18, 1.19 etc. without it
Im using it too. And its my site.

**Comment by JuiceQPS** [comment]
Same problem

**Comment by Ryzo1226** [comment]
Yo i fixed it im running minecraft pojav on chromebook firstly is go back to top by just install pojav first then install java 17 here is the link (https://download.oracle.com/java/17/archive/jdk-17.0.9_linux-x64_bin.deb) run this deb file (make sure you installed linux environment on chromebook) and run the pojav without installing new runtime manager it will auto install jvm 17 on pojav and that is it enjoy
