### ISSUE TITLE
Cant mod

### ISSUE THREAD

**Issue by 216321** [PojavLauncherTeam/PojavLauncher#3472]
### Describe the bug

I tried using forge but I used a computer to try to access Android/data/net.kdt.pojavlaunch/files 
But the .minecraft folder is missing

I'm on Android 10

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9238287/latestlog.txt)

### Steps To Reproduce

```markdown
Can't not reproduce
```

### Expected Behavior

I thought there would be a .minecraft 

### Platform

```markdown
- Device model: galaxy tab
- CPU architecture: ?
- Android version: 10.0
- PojavLauncher version: latest
```

**Comment by khanhduytran0** [comment]
> but I used a computer to try to access Android/data/net.kdt.pojavlaunch/files

Any third party file manager should be already able to access there.
Since the folder starts with a dot, `show hidden folder` must be enabled before you see the folder.
