### ISSUE TITLE
[BUG] Crashes randomly 

### ISSUE THREAD

**Issue by Mahipal2007** [PojavLauncherTeam/PojavLauncher#3473]
### Describe the bug

From somedays whenever i am playing pojav launcher crashes randomly in the middle of the game
And i am irritated with it as i play hypixel skyblock

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9241831/latest.log)

### Steps To Reproduce

```markdown
1. Install Pojavlauncher
2. Download forge jar of 1.8.9
3. And download neu and collection
4. Launch 
5. Play and it will randomly crash
```

### Expected Behavior

I expect the game runs properly without crashing

### Platform

```markdown
- Device model: Vivo v2130
- CPU architecture: arm64-v8a 8th generation/AArch64
- Android version: 12 
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

### Anything else?

Nah just help me to fix this

**Comment by Mahipal2007** [comment]
Hello? Reply pls

**Comment by Mahipal2007** [comment]
Hello? Anyone? Developers?

**Comment by miggythewriter** [comment]
> Hello? Anyone? Developers?

Latestlog.txt

**Comment by Mahipal2007** [comment]
@a

> > Hello? Anyone? Developers?
> 
> Latestlog.txt

I have given it

**Comment by Mahipal2007** [comment]
@Aerolome
