### ISSUE TITLE
I tried the internal java 17 

### ISSUE THREAD

**Issue by Ibattleu** [PojavLauncherTeam/PojavLauncher#3474]
### Describe the bug

I clicked play waited, and it opened the game then logged me out

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. set Java 17 as default
2. Then press create new
3. Then Click version 1.19.1
4. Lastly hit play
```

### Expected Behavior

I expected it to finally work after hours of trying to fix the problem 

### Platform

```markdown
- Device model: Chromebook 3
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Nothing else

**Comment by Mahipal2007** [comment]
Bro you have a laptop then why you want to play on pojav launcher in laptop 🤣

**Comment by GaucovyAero** [comment]
> Bro you have a laptop then why you want to play on pojav launcher in laptop 🤣

because its running android maybe?

**Comment by GaucovyAero** [comment]
> ### Describe the bug
> I clicked play waited, and it opened the game then logged me out
> 
> ### The log file and images/videos
> None
> 
> ### Steps To Reproduce
> ```gfm
> 1. set Java 17 as default
> 2. Then press create new
> 3. Then Click version 1.19.1
> 4. Lastly hit play
> ```
> 
> ### Expected Behavior
> I expected it to finally work after hours of trying to fix the problem
> 
> ### Platform
> ```gfm
> - Device model: Chromebook 3
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:
> ```
> 
> ### Anything else?
> Nothing else

send latestlog.txt

**Comment by Ibattleu** [comment]
Its because its running android.
