### ISSUE TITLE
[BUG] <impossible to join 1.6.4 multiplayer servers>

### ISSUE THREAD

**Issue by ZathegamE** [PojavLauncherTeam/PojavLauncher#3475]
### Describe the bug

Everytime i try to join the server, it says ;"failed to login : bad login".
I heard it was a common issue for 1.6.4 back then, and there were easy fix. However pojav launcher has no way that i know of to fix this bug. 
Sent 2 screens, hope it can help

### The log file and images/videos

![Screenshot_20220802-174656](https://user-images.githubusercontent.com/75631008/182417169-c8531f9f-76f8-4fe5-a97c-6a429f268773.jpg)
![Screenshot_20220802-174651](https://user-images.githubusercontent.com/75631008/182417177-d09a314c-1a62-4ca5-b280-a580a94b087c.jpg)

### Steps To Reproduce

```markdown
Start pojav launcher
Install 1.6.4
Launch it
Go to multiplayer
Add server
Join a random 1.6.4 server
```

### Expected Behavior

I expect that we are unable to join the server due to bad login

### Platform

```markdown
- Device model: one+ 7 pro
- CPU architecture: 
- Android version: 11
- PojavLauncher version: latest play store version
```

**Comment by GaucovyAero** [comment]
This has been fixed in a recent version of PojavLauncher. Go to the Actions tab here on PojavLauncher GitHub and click on the latest one that has a checkmark on it, then download app-debug (it's a zip file, so extract it) and install app-debug.apk
