### ISSUE TITLE
[F-Req] <Make Background Support>

### ISSUE THREAD

**Issue by ProSteve12301** [PojavLauncherTeam/PojavLauncher#3476]
### Is this request related to a bug?

Kinda.The Pojav Exits itself when you back it on a while and when you launch pojav again,its black screen and exits.

### Describe the request.

Add Background Support ;-)

### Anything else?

Add it please cuz i screensharing on discord and i need to response to a chat.

**Comment by GaucovyAero** [comment]
We have background support, but as expected, Pojav takes a lot of RAM, so when you dont use it, Android just kills that app to gain performance. We can't do anything about it.

**Comment by ProSteve12301** [comment]
> We have background support, but as expected, Pojav takes a lot of RAM, so when you dont use it, Android just kills that app to gain performance. We can't do anything about it.

K Thanks for Responce
