### ISSUE TITLE
[BUG] Crashes in middle of the game

### ISSUE THREAD

**Issue by Mahipal2007** [PojavLauncherTeam/PojavLauncher#3477]
### Describe the bug

Pojavlauncher is crashing in the middle of the game while i am playing and it don't even say game exited code 1 like nothing the game crashes 

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9261762/latest.log)
[All of my logs.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/9261773/All.of.my.logs.zip)
All of my logs just in case ;)

### Steps To Reproduce

```markdown
1. Download forge in the pojav launcher
2. Use Neu , collection and optifine
3. Play for while
```

### Expected Behavior

I expect for the game to run without crashing so i can enjoy ;)

### Platform

```markdown
- Device model: Vivo v2130
- CPU architecture: arm64-v8a 8th generation/AArch64
- Android version: 12 
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

### Anything else?

Nope

**Comment by Mahipal2007** [comment]
Why no one reply's to me

**Comment by GaucovyAero** [comment]
too much ram allocation, give less

**Comment by Mahipal2007** [comment]
O

**Comment by Mahipal2007** [comment]
How much ram? And very very very thanks finnally i can play skyblock crystal hollows and not lose the structure by crashing / me waiting for your reply k

**Comment by Mahipal2007** [comment]
Reply pls so i can know if it will crash i tried 1500 but it crashes still

**Comment by GaucovyAero** [comment]
> Reply pls so i can know if it will crash i tried 1500 but it crashes still

give 500

**Comment by Mahipal2007** [comment]
K

**Comment by Mahipal2007** [comment]
I use forge so tell me if you change your mind later until i will use 500 as you say
Thanks for the help

**Comment by Mahipal2007** [comment]
I just tried and it's to laggy ;-;

**Comment by GaucovyAero** [comment]
> I just tried and it's to laggy ;-;

i mean, you can try 1000, just make sure that it doesn't show the window that says "The current amount of free RAM is lower than allocated RAM, which may lead to crashes."

**Comment by Mahipal2007** [comment]
O k

**Comment by Mahipal2007** [comment]
Thx
