### ISSUE TITLE
[BUG] <Fullscreen button bug>

### ISSUE THREAD

**Issue by Evgenie3311** [PojavLauncherTeam/PojavLauncher#3478]
### Describe the bug

Resolution changed to 0x0 and it happened (check video) 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9263538/latestlog.txt)
https://imgur.com/a/B4PCUT2 (video with bug)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Clicking on the button Fullscreen mode.
3. Bug
```

### Expected Behavior

I'm nothing expected, I'm just watching settings

### Platform

```markdown
- Device model: POCO M3 4/64G 
- CPU architecture: aarch64 
- Android version: 11
- PojavLauncher version: latest version
```

**Comment by GaucovyAero** [comment]
```
java.lang.IllegalStateException: Must be 64 pixels wide
	at org.apache.commons.lang3.Validate.validState(Validate.java:829) ~[Validate.class:3.5]
```
change 0x0 to "Default", it should work afterwards.

**Comment by GaucovyAero** [comment]
Issue resolved.

![image](https://user-images.githubusercontent.com/85581164/188009223-10c6d0b9-e76d-4421-9473-aeec4675c5d2.png)
