### ISSUE TITLE
How to Launch Minecraft Client Jar on Command Line?:-)

### ISSUE THREAD

**Issue by ProSteve12301** [PojavLauncherTeam/PojavLauncher#3479]
### Is this request related to a bug?

No

### Describe the request.

Reply Bellow;-)

### Anything else?

I need it cuz my creating client doesnt launching on Pojav so i going to test it on CL but i dont know what command should i use ;-)

**Comment by Dannjay** [comment]
Use termux

**Comment by ProSteve12301** [comment]
$ java -jar 1.8.9.jar

Could not found main class net.minecraft.client.Main
