### ISSUE TITLE
[BUG] movement stuck even with high FPS

### ISSUE THREAD

**Issue by wkosh** [PojavLauncherTeam/PojavLauncher#3480]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9273976/latestlog.txt)
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9273977/latestcrash.txt)
### Describe the bug

my bug and the following no matter how many FPS I am moving the camera seems to have 20 FPS 

### The log file and images/videos

I don't have video or message 

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.enter the version 
3.enter the world
```

### Expected Behavior

I clearly want this resolved.

### Platform

```markdown
- Device model: Redmi Note 11
- CPU architecture: Snapdragon 680 4G
- Android version: 11
- PojavLauncher version: Last version
```

### Anything else?

Nothing more

**Comment by GaucovyAero** [comment]
You have to get a video first. No one has had this issue yet.

**Comment by wkosh** [comment]
I am going to try

**Comment by wkosh** [comment]
I already solved it was a setting that I activated on my phone
