### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Giorgi321201** [PojavLauncherTeam/PojavLauncher#3481]
### Describe the bug

632

### The log file and images/videos

Account error

### Steps To Reproduce

```markdown
Error
```

### Expected Behavior

Bug

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
1.19.1
```

### Anything else?

Acount sing in

**Comment by GaucovyAero** [comment]
send image

**Comment by Giorgi321201** [comment]
Error
