### ISSUE TITLE
make the quick menu(left side/pull area) can be turn off and on.

### ISSUE THREAD

**Issue by selut06** [PojavLauncherTeam/PojavLauncher#3482]
### Is this request related to a bug?

yes, this kinda related to bug, its make our game stop when accidenly slide the slider on right thing, like I said above.

### Describe the request.

so, I hope dev do a feature that can turn off and on the slider in pojavlauncher settings (some where else like on Miscellaneous Settings).

ITS VERY ANNOYING when play. because im using 8 fingers on phone I guess. example, a squad of zombies comes then u want to kill it, when u fighting , then u accidentally slide the slider , then u ded. 
( because u cant move while the slide u touching)

### Anything else?

just make sure what i mean, 
![Screenshot_20220807-090949](https://user-images.githubusercontent.com/82783126/183270936-1cafdb47-0c11-4094-8f24-e50fef0e3103.png)
u can see the right things.
I hope you guys can accept this :)

**Comment by Mahipal2007** [comment]
Dude you are Hella good bro like 8 fingersss.. 😱 me can't even use 2 fingers properly salute to you ✋

**Comment by mchnjt** [comment]
> ### Is this request related to a bug?
> yes, this kinda related to bug, its make our game stop when accidenly slide the slider on right thing, like I said above.
> 
> ### Describe the request.
> so, I hope dev do a feature that can turn off and on the slider in pojavlauncher settings (some where else like on Miscellaneous Settings).
> 
> ITS VERY ANNOYING when play. because im using 8 fingers on phone I guess. example, a squad of zombies comes then u want to kill it, when u fighting , then u accidentally slide the slider , then u ded. ( because u cant move while the slide u touching)
> 
> ### Anything else?
> just make sure what i mean, ![Screenshot_20220807-090949](https://user-images.githubusercontent.com/82783126/183270936-1cafdb47-0c11-4094-8f24-e50fef0e3103.png) u can see the right things. I hope you guys can accept this :)

bruh just don't get your fingers near the quick menu(left side/pull area)

**Comment by selut06** [comment]
the button im using is near to the quick menu, and  its so hard to avoid that from touching the quick menu.

**Comment by selut06** [comment]
thanks

**Comment by artdeell** [comment]
> the button im using is near to the quick menu, and its so hard to avoid that from touching the quick menu.

move the button then

**Comment by selut06** [comment]
> 

ahhh yess move the button, now i can see my barely hand, and nice view of gameplay.

**Comment by GaucovyAero** [comment]
> > 
> 
> ahhh yess move the button, now i can see my barely hand, and nice view of gameplay.

then move and hide the button

**Comment by selut06** [comment]
> then move and hide the button

bruh not the button, if i change the button somewhere else, i couldn't see my screen cause of my hand

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
