### ISSUE TITLE
[F-Req] Maybe you can still return the renderer Zink(Vulkan) 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#3483]
### Is this request related to a bug?

Yes, this issue is related to an error
Renderer Virgl which is added in the latest versions works very poorly with Kirin processors 

### Describe the request.

Just bring back the Zink renderer and make it work. It can be added to the "experimental stuff" section. 

### Anything else?

Another problem with holy gl4es: it doesn't work with some simple mods such as mini maps. I think that's because holy gl4es is made on gl4es version 1.1.4. 
On gl4es 1.1.5 there are no such problems. 
I would like to see in Pojavlauncher more necessary and interesting functions since the project is really good.

**Comment by WesleyVanNeck** [comment]
They are working on zink already

**Comment by Iarkont** [comment]
> 
that's fine, then, good luck. I'm closing the request
