### ISSUE TITLE
[F-Req] crash in j2 prime android 6.0.1 aarch32

### ISSUE THREAD

**Issue by valterineCraft** [PojavLauncherTeam/PojavLauncher#3486]
### Is this request related to a bug?

Not being able to report the bug by traditional means so I had to report it here, the bug happens as soon as I enter PojavLauncher on my android device J2 prime 1.5/16G android 6.0.1 aarch32

### Anything else?

Crash on my android device

**Comment by GaucovyAero** [comment]
please send /storage/emulated/0/games/PojavLauncher/latestlog.txt with the crash in it.

**Comment by GaucovyAero** [comment]
send log

**Comment by GaucovyAero** [comment]
Not enough information provided and stale issue. Closing.
