### ISSUE TITLE
[BUG] Texture glitch

### ISSUE THREAD

**Issue by Mahipal2007** [PojavLauncherTeam/PojavLauncher#3487]
### Describe the bug

Idk what to say but for some reason my minecraft decides to x ray from it self

### The log file and images/videos

![Screenshot_20220810_102103](https://user-images.githubusercontent.com/109529762/183819112-74daa6da-bcd8-451d-bb2c-ed6e9a9cc4aa.jpg)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9296843/latest.log)

### Steps To Reproduce

```markdown
1. Download pojav launcher
2. Use forge
3. Use these mods : neu,skytils,optifine,collection
4. Run
```

### Expected Behavior

I expect no texture issues 

### Platform

```markdown
- Device model: Vivo v23 5g
- CPU architecture: arm64-v8a 8th generation/AArch64
- Android version: 12
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

### Anything else?

Nope

**Comment by Mahipal2007** [comment]
There is a mod name patcher which fixes it but it has 1 bug that it adds like under words and it crashes
Pls help me to fix this Texture thing i don't wanna get banned from hypixel

**Comment by GaucovyAero** [comment]
> There is a mod name patcher which fixes it but it has 1 bug that it adds like under words and it crashes Pls help me to fix this Texture thing i don't wanna get banned from hypixel

skyblock developers and essential developers don't want their mods to run on pojav even though the fix is 2 lines, just don't use their mods..

**Comment by Mahipal2007** [comment]
But isn't there any fix cuz i have to use those mods as they are important

**Comment by Mahipal2007** [comment]
> > There is a mod name patcher which fixes it but it has 1 bug that it adds like under words and it crashes Pls help me to fix this Texture thing i don't wanna get banned from hypixel
> 
> skyblock developers and essential developers don't want their mods to run on pojav even though the fix is 2 lines, just don't use their mods..

By the way what do you mean by the fix is just 2 lines , is it a command to fix ? Then can you tell me i wanna use these mods they are important ;-;

**Comment by Mahipal2007** [comment]
And isn't there any way to extract a particular mod from a mod like if i wanna extract treasure chest solver from skytils how do I do it? Like in another folder or stuff 
Idk what i am saying or if it's even possible but I want the mods ;-;

**Comment by GaucovyAero** [comment]
> > > There is a mod name patcher which fixes it but it has 1 bug that it adds like under words and it crashes Pls help me to fix this Texture thing i don't wanna get banned from hypixel
> > 
> > 
> > skyblock developers and essential developers don't want their mods to run on pojav even though the fix is 2 lines, just don't use their mods..
> 
> By the way what do you mean by the fix is just 2 lines , is it a command to fix ? Then can you tell me i wanna use these mods they are important ;-;

no, the developers have to fix it on their MCP side, so no. they basically just don't want it to run on pojav

**Comment by GaucovyAero** [comment]
you can fix the x-ray with F11 tho.

**Comment by Mahipal2007** [comment]
O thxx

**Comment by Mahipal2007** [comment]
Thanks it worked 😊
And even for some sec its there it doesn't send any wierd packets to hypixel right cuz i don't wanna get banned

**Comment by Mahipal2007** [comment]
Ty tho ;)
