### ISSUE TITLE
Can't resolve host name on v3 latest version 

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#349]
I can't join any server, cracked or premium due to can't resolve host name.

**Comment by khanhduytran0** [comment]
Use v3.2 release with testing6's java Runtime.

**Comment by khanhduytran0** [comment]
Also try ping play.hypixel.net

**Comment by leetmussc** [comment]
I can't ping any server

**Comment by leetmussc** [comment]
![Screenshot_20201011-161736](https://user-images.githubusercontent.com/63871578/95682778-1dc51580-0bdf-11eb-8f12-207ffe310c54.jpg)
M

**Comment by leetmussc** [comment]
Invalid session I'd for connecting

**Comment by leetmussc** [comment]
Invalid session id

**Comment by leetmussc** [comment]
![Uploading Screenshot_20201011-162031.jpg…]()

**Comment by leetmussc** [comment]
![Screenshot_20201011-162031](https://user-images.githubusercontent.com/63871578/95682973-56192380-0be0-11eb-9219-eadb3783b468.jpg)
Invalid Session?

**Comment by khanhduytran0** [comment]
You need a premium account to join it.

**Comment by leetmussc** [comment]
Ok
