### ISSUE TITLE
[BUG] Cant open links to browser.

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3491]
### Describe the bug

Whenever I try to open a link (such as cosmetica customisation (not mod specific)) it just doesn't open the link.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9316181/latestlog.txt)

### Steps To Reproduce

```markdown
1. Find a link to open
2. Attempt to open link
```

### Expected Behavior

I expect the link to open.

### Platform

```markdown
- Device model: Galaxy A12
- CPU architecture: ARM
- Android version: 12
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk (play store)
```

### Anything else?

From a very basic understanding and a quick glance at thr log, I think it has something to do with: cannot run "xdg-open": Access Denied . I could very easily be wrong, and I also don't see any app permissions (from phone settings app) to allow it to open links.

**Comment by GaucovyAero** [comment]
opening links won't be supported because we would have to pack the whole chromium browser into the app, and thats just too much xD

**Comment by ghost** [comment]
Just to clear it up, I meant open the links in a separate app such as chrome. Opening the links inside if the app would obviously be too much lol. For example, if I was on the discord app (and had open links in app turned off), I could click a link and it would open Google in a separate window with the link. I don't know alot about chromium, and whether opening windows with links requires it or not, so I could  just be waffiling XD. Hope that clears it up.

**Comment by ghost** [comment]
Update: found a workaround. If you go into the latest log, scroll down to where you tried to open the link, you can copy paste the link into the browser! Gonna go ahead and close this for now, but would be nice if it was easier as mentioned above.

**Comment by GaucovyAero** [comment]
> Just to clear it up, I meant open the links in a separate app such as chrome. Opening the links inside if the app would obviously be too much lol. For example, if I was on the discord app (and had open links in app turned off), I could click a link and it would open Google in a separate window with the link. I don't know alot about chromium, and whether opening windows with links requires it or not, so I could just be waffiling XD. Hope that clears it up.

well, but that would crash the game, because putting pojav in the background, well, does that exact thing

**Comment by AverageFemale** [comment]
Put your browser into popup mode, copy the link, paste it into the browser that's in popup mode.
