### ISSUE TITLE
1.19.2 [Crash]

### ISSUE THREAD

**Issue by PhantomCrafter868** [PojavLauncherTeam/PojavLauncher#3492]
### Describe the bug

It loaded a bit then crashed

Application exited with code -1.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9319727/latestlog.txt)

### Steps To Reproduce

```markdown
I downloaded 1.19.2 from old pojav launcher then updated it,instaled runtime,etc.
```

### Expected Behavior

Always worked even on forge 1.18.2(even if laggy). But all 1.19 versions crash for me.

### Platform

```markdown
- Device model: Samsung Galaxy A32
- CPU architecture:Linux (aarch64)
- Android version: 12
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

**Comment by GaucovyAero** [comment]
```
java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
	at efn.<init>(SourceFile:19)
	at efu.<init>(SourceFile:637)
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)
Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```

The solution is to update PojavLauncher. Go to the [Actions](**https://github.com/PojavLauncherTeam/PojavLauncher/actions**) tab, then click on the latest build from the `v3_openjdk` branch, then download `app-debug`, extract it and install `app-debug.apk`. After that, 1.19 should load up just fine.

**Comment by PhantomCrafter868** [comment]
> ```
> java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
> 	at efn.<init>(SourceFile:19)
> 	at efu.<init>(SourceFile:637)
> 	at net.minecraft.client.main.Main.a(SourceFile:205)
> 	at net.minecraft.client.main.Main.main(SourceFile:51)
> Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	... 4 more
> ```
> 
> The solution is to update PojavLauncher. Go to the Actions tab, then click on the latest build from the `v3_openjdk` branch, then download `app-debug`, extract it and install `app-debug.apk`. After that, 1.19 should load up just fine.

Which one i should download? Can you give me the latest version download link? There are builds with  ✅️ and ❌️

**Comment by GaucovyAero** [comment]
> > ```
> > java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
> > 	at efn.<init>(SourceFile:19)
> > 	at efu.<init>(SourceFile:637)
> > 	at net.minecraft.client.main.Main.a(SourceFile:205)
> > 	at net.minecraft.client.main.Main.main(SourceFile:51)
> > Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
> > 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> > 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> > 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> > 	... 4 more
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The solution is to update PojavLauncher. Go to the Actions tab, then click on the latest build from the `v3_openjdk` branch, then download `app-debug`, extract it and install `app-debug.apk`. After that, 1.19 should load up just fine.
> 
> Which one i should download? Can you give me the latest version download link? There are builds with white_check_mark and x

Download `v3_openjdk` with ![image](https://user-images.githubusercontent.com/85581164/188015681-be251fd2-8c51-4849-b287-99f4a0082587.png) on it

**Comment by Shivamjiaao** [comment]
Link

**Comment by MENDOWSKY** [comment]
Jdjd

**Comment by MENDOWSKY** [comment]
How did i can download it?
