### ISSUE TITLE
[BUG] <Mouse scroll wheel doesnt work>

### ISSUE THREAD

**Issue by InfernoNova9999** [PojavLauncherTeam/PojavLauncher#3493]
### Describe the bug

Mouse scroll wheel doesnt work while using an external mouse. This is a really important issue hoping this gets fixed since cristalline now has an ipad

### The log file and images/videos

There is no log

### Steps To Reproduce

```markdown
1: Scroll
```

### Expected Behavior

i expect the mouse scroll wheel to work

### Platform

```markdown
- Device model: iPad air 4
- CPU architecture: A14
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
Have you tried the latest PojavLauncher_iOS Actions build? Also, if it's an iOS issue, make sure to go to PojavLauncher_iOS repo instead of this one. This is the repo for Android.
