### ISSUE TITLE
[F-Req] Add A Choice For Landscape or Portrait On Screens With Near-Square Aspect Ratios

### ISSUE THREAD

**Issue by roryyamm** [PojavLauncherTeam/PojavLauncher#3494]
### Is this request related to a bug?

Not really, I just want to play on a weird phone.

### Describe the request.

I use a Unihertz Titan Pocket. It has a physical keyboard and a screen resolution of 716x720. Since the resolution is only narrower than it is tall by about 4 pixels, I thought I would use it in portrait mode and use the physical keyboard to move around. Instead, PojavLauncher decides that it wants to launch in landscape mode, taking every last one of those 4 pixels for width instead of height. This means I can't effectively use the physical keyboard, especially when it comes time to enter in credentials. Using the phone's built-in Rotation Control also seems to fail.

Forcing landscape works well when the aspect ratio is 9:16, or even 3:4, but when it's 179:180, a choice would be highly appreciated. 

### Anything else?

The software keyboard still shows when using the Pocket, too, but I think I'll try to figure that one out myself before submitting a bug report.

**Comment by GaucovyAero** [comment]
yeah, sorry to tell you but i think this is going to be a super-low-priority enhancement, but yeah, maybe. thing is, no mobile phone and no tablet (probably only your device) has lower width than it has height when in the landscape mode, so yeah.

**Comment by Mathias-Boulay** [comment]
@roryyamm there are apps to force portrait mode anywhere on the phone.
Pojav should hold itself pretty well here, try and find out 👍

**Comment by roryyamm** [comment]
> @roryyamm there are apps to force portrait mode anywhere on the phone. Pojav should hold itself pretty well here, try and find out

Yep, it works. Turns out I wasn't FORCING portrait with the built-in rotation control. Still trying to figure out how to use the built-in hardware keyboard, but I can play it in the right orientation. Apologies for wasting your time.
