### ISSUE TITLE
Java Previews

### ISSUE THREAD

**Issue by IpanaDev** [PojavLauncherTeam/PojavLauncher#3495]
### Describe the bug

I want to launch the game with a custom built jar (jre17 preview which has class version of 61.5535 normal jre17 has class version of 61.0).
First I ran my game normally and it crashed with java.lang.UnsupportedClassVersionError: Preview features are not enabled for net/minecraft/client/Minecraft (class file version 61.65535). Try running with '--enable-preview'
So i tried to run with "--enable-preview" jvm argument. But it couldn't recognize it.

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: dahlia-8-f527e8a14-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: "--enable-preview"
Info: Selected Minecraft version: Ipana
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2160
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-y0c-WxZI7WjiDz2iaKP9wQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-y0c-WxZI7WjiDz2iaKP9wQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Unrecognized option: --enable
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Steps To Reproduce

```markdown
set your jvm arguments to --enable-preview
```

### Expected Behavior

I expect game to launches.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
and it doesn't say the java runtime is corrupted?

**Comment by IpanaDev** [comment]
> 

no it doesn't say anything like that

**Comment by khanhduytran0** [comment]
Currently, the parser treats dash prefix as a new argument, which expands `--enable-preview` to `--enable -preview`. This is a known issue.
For the meantime, specify it in `_JAVA_OPTIONS` environment variable instead. Create a file named `custom_env.txt` with the following content:
```
_JAVA_OPTIONS=--enable-preview
```

**Comment by IpanaDev** [comment]
> Currently, the parser treats dash prefix as a new argument, which expands `--enable-preview` to `--enable -preview`. This is a known issue. For the meantime, specify it in `_JAVA_OPTIONS` environment variable instead. Create a file named `custom_env.txt` with the following content:
> 
> ```
> _JAVA_OPTIONS=--enable-preview
> ```

thanks for the answer I'll do that 👍
