### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Crouzxoo** [PojavLauncherTeam/PojavLauncher#3498]
### Describe the bug

![Screenshot_2022-08-15-17-43-02-712_net kdt pojavlaunch](https://user-images.githubusercontent.com/92728662/184633305-fc36f085-e1de-4226-8136-f07d14200d60.jpg)

### The log file and images/videos

![Screenshot_2022-08-15-17-43-02-712_net kdt pojavlaunch](https://user-images.githubusercontent.com/92728662/184633359-4b0ce2b3-f615-4aa1-90b9-c5eeeb02d25f.jpg)

### Steps To Reproduce

```markdown
Pls help me
```

### Expected Behavior

Pls help

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Crouzxoo** [comment]
- Device model: M2101K7BI
- CPU architecture: MTK G95 Octa-core Max 2.05GHz
- Android version: 12
- PojavLauncher version:1.17.2

**Comment by miggythewriter** [comment]
It's a via version error

**Comment by GaucovyAero** [comment]
Even the error told you to contact ViaVersion GitHub Issues instead of our GitHub issues. Make sure to contact them.

**Comment by thecoder08** [comment]
We need more details. Post latestlog.txt

**Comment by GaucovyAero** [comment]
Stale issue and no log provided. Closing
