### ISSUE TITLE
[BUG] black screen after launching game with Zink sound of game come but screen remains black

### ISSUE THREAD

**Issue by abhishekgi** [PojavLauncherTeam/PojavLauncher#3499]
### Describe the bug

black screen after launching game with Zink sound of game come but screen remains black
My phone m31
Ram 6gb
Storage 64gb
GPU mali g72
CPU Exynos 9611

### The log file and images/videos

Black screen problem Zink rederer

### Steps To Reproduce

```markdown
Started pojav launcher lached Minecraft
```

### Expected Behavior

Black screen all time 
Only sound of game come 

### Platform

```markdown
- Device model:galaxy m31 6/128gb
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Version dahlia-19-f482c4c5f-v3_zink


### Anything else?

Please help me

**Comment by miggythewriter** [comment]
Why zink?

**Comment by abhishekgi** [comment]
> 



> Why zink?

Because I want to use shaders.

**Comment by GaucovyAero** [comment]
the screen will always be black, but you can screenshot everything with F2 and you will get what you want.

**Comment by abhishekgi** [comment]
> the screen will always be black, but you can screenshot everything with F2 and you will get what you want.

But i want to play Minecraft with shaders using Zink rederer

**Comment by miggythewriter** [comment]
> > the screen will always be black, but you can screenshot everything with F2 and you will get what you want.
> 
> But i want to play Minecraft with shaders using Zink rederer

Virgl exists btw

**Comment by mchnjt** [comment]
stop praising vgrill

**Comment by abhishekgi** [comment]
But Virgil support only few shaders many shaders are glitchy with Virgil while Zink support almost all shaders 

> > > the screen will always be black, but you can screenshot everything with F2 and you will get what you want.
> > 
> > 
> > But i want to play Minecraft with shaders using Zink rederer
> 
> Virgl exists btw

But Virgil support only few shaders many shaders are glitchy with Virgil while Zink support almost all shaders

**Comment by abhishekgi** [comment]
> stop praising vgrill

Yes Virgil is not to good renderer
