### ISSUE TITLE
[BUG] Keyboard quote key doesn't work.

### ISSUE THREAD

**Issue by AverageFemale** [PojavLauncherTeam/PojavLauncher#3500]
### Describe the bug

I can use the quote key on my physical keyboard on any application, but as soon as it comes to minecraft it doesn't work at all. I'm able to copy and paste the " in but that isn't really reliable when I have to copy and paste something else.

### The log file and images/videos

Don't think its gonna show up in any of these things..

### Steps To Reproduce

```markdown
1. Start Minecraft
2. Start a world
3. Try to type a " or ' with a physical keyboard in chat.

Might just be a me thing..
```

### Expected Behavior

I expect the game to actually put a " or a ' in when I press the quote key.

### Platform

```markdown
- Device model: Samsung Galaxy S20+
- CPU architecture: No clue
- Android version: 12
- PojavLauncher version: Latest
```

### Anything else?

My physical keyboard is a: Omoton Wireless Keyboard and Mouse combo

**Comment by GaucovyAero** [comment]
Well, it could just be a thing with your Android, but I think we should address this. If I don't forget, I will test this on my phone.

**Comment by GaucovyAero** [comment]
Thanks a lot for this suggestion! Turns out it actually doesn't work, I will try to address this with the devs.

**Also, sorry for the super-late reply.**

**Comment by GaucovyAero** [comment]
This issue has been reported to the devs and will be resolved soon. The dev team is currently working hard on a big UI update that will make the launcher more aesthetic and easier to use. The issue will be fixed once the UI update rolls out.

**Comment by AverageFemale** [comment]
Awesome, thanks for the reply and sorry I didn't reply sooner. Can't wait for this to be fixed as I like to do a lot of commands 😂

**Comment by GaucovyAero** [comment]
> Awesome, thanks for the reply and sorry I didn't reply sooner. Can't wait for this to be fixed as I like to do a lot of commands joy

Okay, cool :D

**Comment by AverageFemale** [comment]
Any updates on this?

**Comment by GaucovyAero** [comment]
> Any updates on this?

yeah, havent mentioned this, its fixed, but only in the new ui developement builds, which basically means that you gotta wait dunno how much till we release the new ui (because the new ui builds crash very often when you click on basically anything)

**Comment by AverageFemale** [comment]
Welp, if its possible to keep me updated that would be lovely. Can't join the discord beacuse of the phone verification thing.

**Comment by GaucovyAero** [comment]
> Welp, if its possible to keep me updated that would be lovely. Can't join the discord beacuse of the phone verification thing.

updating isnt viable because of the crashing

**Comment by AverageFemale** [comment]
I meant updated as in, keep me in the loop of whats happening or whatever, if thats possible. Sorry if that was missed in communication. <3

**Comment by Mathias-Boulay** [comment]
The quote key should work now @Kweeme if you can test it on your end real quick

**Comment by AverageFemale** [comment]
> The quote key should work now @Kweeme if you can test it on your end real quick

It works greatly, thank you! <3
