### ISSUE TITLE
 Help me: a new renderer VKGL

### ISSUE THREAD

**Issue by TuboFmc** [PojavLauncherTeam/PojavLauncher#3501]
### Is this request related to a bug?

I am writing and improving a GPU driver: VKGL.

https://github.com/TuboFmc/VKGL

I want it to work and be one of pojav's renderers.

Currently I use the Android NDK r22b to compile it. I compiled correctly on my local device, but it didn't compile properly when I used the NDK for Android CI.

### Describe the request.

I would like someone to help me look at the Android.yml file in my project and improve it.

**Comment by artdeell** [comment]
I mean it's not that important to build Pojav renderers on a CI. The important question is how it's intended to be integrated. Like, is there a header file for its context manager?

**Comment by artdeell** [comment]
I see, you already have EGL in it. Then you only need to modify the launcher a bit to load your EGL in order to test it. I can try to figure out what is up with the CI.

**Comment by artdeell** [comment]
Also, if you have Discord, it's recommended to join us at https://discord.gg/6RpEJda

**Comment by Mathias-Boulay** [comment]
Long time inactive, closing due to lack of interest
