### ISSUE TITLE
Can someone help me? Crash in Galaxy A71

### ISSUE THREAD

**Issue by Elmatecocido** [PojavLauncherTeam/PojavLauncher#3502]
### Is this request related to a bug?

The game crash in when i try to play in 1.19 and in the crash log show that:

### Describe the request.

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 17/8/22 0:20
Description: Initializing game

java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
 at egi.<init>(SourceFile:26)
 at egi.<clinit>(SourceFile:24)
 at egc.<init>(SourceFile:161)
 at eev.<init>(SourceFile:586)
 at net.minecraft.client.main.Main.main(SourceFile:198)
Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
 ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
 at egi.<init>(SourceFile:26)
 at egi.<clinit>(SourceFile:24)
 at egc.<init>(SourceFile:161)
 at eev.<init>(SourceFile:586)

-- Initialization --
Details:
 Modules: 
Stacktrace:
 at net.minecraft.client.main.Main.main(SourceFile:198)

-- System Details --
Details:
 Minecraft Version: 1.19
 Minecraft Version ID: 1.19
 Operating System: Linux (aarch64) version Android-12
 Java Version: 17-internal, N/A
 Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 1222113280 bytes (1165 MiB) / 1610612736 bytes (1536 MiB) up to 1610612736 bytes (1536 MiB)
 CPUs: 8
 Processor Vendor: 0x51
 Processor Name: AArch64 Processor rev 14 (aarch64)
 Identifier: 0x51 Family 8 Model 0x804 Stepping r0xdp14
 Microarchitecture: unknown
 Frequency (GHz): -0,00
 Number of physical packages: 1
 Number of physical CPUs: 1
 Number of logical CPUs: 8
 Graphics card #0 name: unknown
 Graphics card #0 vendor: unknown
 Graphics card #0 VRAM (MB): 0,00
 Graphics card #0 deviceId: unknown
 Graphics card #0 versionInfo: unknown
 Virtual memory max (MB): 6558,38
 Virtual memory used (MB): 6141,02
 Swap memory total (MB): 4096,00
 Swap memory used (MB): 1694,80
 JVM Flags: 2 total; -Xms1536M -Xmx1536M
 Launched Version: 1.19
 Backend library: LWJGL version 3.2.3 SNAPSHOT
 Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
 Window size: <not initialized>
 GL Caps: Using framebuffer using OpenGL 3.2
 GL debug messages: <disabled>
 Using VBOs: Yes
 Is Modded: Probably not. Client jar signature and brand is untouched
 Type: Client (map_client.txt)
 CPU: 8x AArch64 Processor rev 14 (aarch64)

**Comment by GaucovyAero** [comment]
you have to update pojav, check the official pojavlauncher discord server about that

**Comment by Elmatecocido** [comment]
> you have to update pojav, check the official pojavlauncher discord server about that

I do, but i can't update the version of minecraft in the last update of pojav

**Comment by GaucovyAero** [comment]
We can help you with that in the discord server, I mean, that's what it's for, make sure to join it, otherwise I may not reply, like I didn't here. I just forgot about this issue, like I usually do. Nonetheless, I am definitely more active and more reliable on the official PojavLauncher discord server.
