### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by sss9198** [PojavLauncherTeam/PojavLauncher#3503]
### Describe the bug

Access to /android/data is prohibited in Android 13.

### The log file and images/videos

![Screenshot_20220817-122131](https://user-images.githubusercontent.com/106522699/185027812-3e696c70-3beb-44e3-91d4-a258cf4c7eec.png)

### Steps To Reproduce

```markdown
1. Launch the Files app to install the mod.

2.Access is prohibited.
```

### Expected Behavior

Please add an option for mods.

### Platform

```markdown
- Device model: pixel 4a(5g)
- CPU architecture: 64-bit
- Android version: 13
- PojavLauncher version: Latest Release
```

**Comment by NotAHero04** [comment]
Could you try this?
https://forum.xda-developers.com/t/access-android-data-on-android-13-without-root.4480683/

**Comment by sss9198** [comment]
I couldn'.Same error.

**Comment by BlueGradientHorizon** [comment]
Try using ZArchiver from google play

**Comment by sss9198** [comment]
ZArchiver and X-plore tried but same error.

**Comment by mchnjt** [comment]
android 13:trollface:

**Comment by Fabian42** [comment]
There is a Magisk mod called "NoStorageRestrict" that claims to fix this, but be warned: When I tried it, it broke my files app, it doesn't show any files in my internal storage anymore, not even after uninstalling the mod again. So try at your own risk, if you want.

**Comment by GaucovyAero** [comment]
this is borked, fuk googelus

**Comment by sss9198** [comment]
Non-root is good because I use google pay.

**Comment by GaucovyAero** [comment]
use MiX
