### ISSUE TITLE
Text in settings tab is upside down

### ISSUE THREAD

**Issue by thesaguaro** [PojavLauncherTeam/PojavLauncher#3506]
### Describe the bug

The text in settings tab is upside down. 

### The log file and images/videos

![IMG_20220817_171602](https://user-images.githubusercontent.com/50411983/185177489-93c3bbea-bf5e-4b8e-ad3e-04425d941c8d.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Log in
3. Click settings tab
```

### Expected Behavior

Text being in right orientation. 

### Platform

```markdown
- Device model: Xiaomi Redmi Note 8 Pro
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

**Comment by ottohg** [comment]
I have this exact same issue on Samsung Galaxy S10 (Android 12) from Google Play Store.

**Comment by miggythewriter** [comment]
> I have this exact same issue on Samsung Galaxy S10 (Android 12) from Google Play Store.

Easy fix just change your language to English (United Kingdom)

**Comment by thecoder08** [comment]
same issue on google play store, but not apk version.
