### ISSUE TITLE
[BUG] bug with forge in 1.19

### ISSUE THREAD

**Issue by SkyperX12** [PojavLauncherTeam/PojavLauncher#3508]
### Describe the bug

The standard version 1.19 works correctly.. But when I install its corresponding forge, it doesn't start.

"The application/game has ended with code 1"

same error on samsung a71 and redmi 9

I used to play 1.17.1 with forge before and it worked fine, but now I can't update my worlds with mods because of this error... any response?

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9366582/latestlog.txt)

-------------------------contents----------------------------------

latestlog.txt

--------- beggining with launcher debug
Info: Launcher version: dahlia-8-f527e8a14-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: POJAV_NATIVEDIR=/data/app/~~FiJ8tkmvfJnuosxBZcA71A==/net.kdt.pojavlaunch-nxT-0qYAxNcKP6F2KweEzQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~FiJ8tkmvfJnuosxBZcA71A==/net.kdt.pojavlaunch-nxT-0qYAxNcKP6F2KweEzQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main

I/LIBGL   ( 8262): Initialising gl4es
I/LIBGL   ( 8262): v1.1.4 built on May 28 2022 20:23:20
I/LIBGL   ( 8262): Using GLES 2.0 backend
I/LIBGL   ( 8262): loaded: libGLESv2.so
I/LIBGL   ( 8262): loaded: libEGL.so
I/LIBGL   ( 8262): Using GLES 2.0 backend
I/LIBGL   ( 8262): Hardware Full NPOT detected and used
I/LIBGL   ( 8262): FBO are in core, and so used
I/LIBGL   ( 8262): PointSprite are in core, and so used
I/LIBGL   ( 8262): CubeMap are in core, and so used
I/LIBGL   ( 8262): BlendColor is in core, and so used
I/LIBGL   ( 8262): Blend Substract is in core, and so used
I/LIBGL   ( 8262): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 8262): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 8262): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 8262): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 8262): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 8262): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 8262
): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 8262): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 8262): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   ( 8262): Extension GL_OES_texture_float  detected and used
I/LIBGL   ( 8262): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   ( 8262): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 8262): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 8262): high precision float in fragment shader available and used
I/LIBGL   ( 8262): Max vertex attrib: 32
I/LIBGL   ( 8262): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 8262): Max texture size: 16384
I/LIBGL   ( 8262): Max Varying Vector: 31
I/LIBGL   ( 8262): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   ( 8262): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 8262): Max Anisotropic filtering: 16
I/LIBGL   ( 8262): Hardware 
vendor is Qualcomm
I/LIBGL   ( 8262): GLSL 300 es supported
I/LIBGL   ( 8262): GLSL 310 es supported and used
I/LIBGL   ( 8262): GLSL 320 es supported
I/LIBGL   ( 8262): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   ( 8262): sRGB surface supported
I/LIBGL   ( 8262): EGLImage to Texture2D supported
I/LIBGL   ( 8262): EGLImage to RenderBuffer supported
I/LIBGL   ( 8262): ignore MipMap
I/LIBGL   ( 8262): Targeting OpenGL 2.1
I/LIBGL   ( 8262): No hack in shader converter to define overloaded function with int
I/LIBGL   ( 8262): NPOT texture handled in hardware
I/LIBGL   ( 8262): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 8262): try to use VBO

I/LIBGL   ( 8262): glX Will try to recycle EGL Surface
I/LIBGL   ( 8262): Current folder is:/
I/jrelog  ( 8262): dlopen libgl4es_114.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 8262): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  ( 8262): dlope
n /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libattach.so success

I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib
/libjli.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjsig.so success

I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libdt_socket.
so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjdwp.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libzip.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libsctp.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success
I/jrelog  ( 8262): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libextnet.so success

[WARNING:spdy_session.cc(3541)] Received HEADERS for invalid stream 9
Exception in thread "main" 
java.lang.module.ResolutionException: Modules lwjgl.glfw.classes and org.lwjgl export package org.lwjgl.system.macosx to module brigadier
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:129)
Java Exit code: 1
I/jrelog  ( 8262): Going to free args
I/jrelog  ( 8262): Free done

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. I select version 1.19 with forge
3. I press the play button
4. wait for it to load
5. "The application/game has ended with code 1"
```

### Expected Behavior

Successful startup and loading of mods

### Platform

```markdown
- Device model: Samsung A71 6/128
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: [versión 3.3.1.1_rel_20210206]

- Device model: Redmi 9 4/64
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: [versión 3.3.1.1_rel_20210206]
```

**Comment by AverageFemale** [comment]
This could be, because one of your mods doesn't support 1.19 or one of your mods doesnt support your cpu/gpu.
I'd suggest going through all your mods and adding .bk for one of them and seeing which one makes your Minecraft able to boot up.

If you don't have mods then I have no clue what's going on.

**Comment by GaucovyAero** [comment]
Make sure to update your launcher first. Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`

**Comment by GaucovyAero** [comment]
Stale issue and is fixed in the latest Actions build. Closing.
