### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Mahipal2007** [PojavLauncherTeam/PojavLauncher#3509]
### Describe the bug

I fixed it somehow

**Comment by Giorgi321201** [comment]
tank you

ხუთ, 18 აგვ. 2022, 6:23 PM-ში Mahipal2007 ***@***.***> დაწერა:

**Comment by Giorgi321201** [comment]
Tank you


ხუთ, 18 აგვ. 2022, 6:31 PM-ში Mahipal2007 ***@***.***> დაწერა:
