### ISSUE TITLE
[BUG] VirGL fflickering

### ISSUE THREAD

**Issue by Pinecone6442** [PojavLauncherTeam/PojavLauncher#3510]
### Describe the bug

If you use virgl render then the screen flickers after a while and its annoying fix it

### The log file and images/videos

no.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Use VIRGL
3. join world
```

### Expected Behavior

I expect nothing

### Platform

```markdown
- Device model: Samsung a7 tablet
- CPU architecture: Mt3768Wt????
- Android version: 11
- PojavLauncher version: newest playstore
```

### Anything else?

no

**Comment by selut06** [comment]
> 

set your render distance up to 7+, fixed

**Comment by Pinecone6442** [comment]
did u forget lag, you fucking shit?

**Comment by GaucovyAero** [comment]
I personally never noticed any flickering on virglrenderer, but there may be issues with it on different GPUs, because it only works reasonably well on Mali GPUs. Also, is there any specific reason as to why are you using virgl? If no, use Holy GL4ES instead, because it performs a lot better.

**Comment by Pinecone6442** [comment]
i use gl4es, its just i want to try virgl but it does that

**Comment by GaucovyAero** [comment]
> 

yeah, that happens when you don't have a Mali GPU, it's fine, just don't use it i guess...
