### ISSUE TITLE
Minecraft Forge 1.5.1 can't load

### ISSUE THREAD

**Issue by Forever2397** [PojavLauncherTeam/PojavLauncher#3511]
### Describe the bug

I want to run Forge 1.5.1 but there are important files that need to be downloaded in it according to latestlog.txt, like this:.  deobfuscation_data_1.5.1.zipscala-library.jar asm-all-4.1.jar bcprov-jdk15on-148.jar guava-14.0-rc3.jar where can I download the file??

### The log file and images/videos

![Screenshot_2022-08-19-15-05-29-32_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185575239-377c2994-c20c-40d3-b18e-41f260a850e9.jpg)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9380360/latestlog.txt)

### Steps To Reproduce

```markdown
1.Game Exited
```

### Expected Behavior

I Hope Game Launch

### Platform

```markdown
- Device model:Oppo Reno 4F
- CPU architecture:aarch64
- Android version:10
- PojavLauncher version:dahlia-8f527e14-v3_openjdk
```

**Comment by GaucovyAero** [comment]
Okay, so, your problem at first are missing libraries, you can fix it by downloading [fmllibs151.zip](https://b2.mcarchive.net/file/mcarchive/33227b92d2c4dca78c3503b38680b099b73c46231e9f98af92ab4743d58e139f/fmllibs151.zip) from MCArchive. Put the ```lib``` folder inside **fmllibs151.zip** into ```.minecraft```. It will crash later because of a different issue, but I will send you the JSON fix pack in a while.

**Comment by GaucovyAero** [comment]
[**Here**](https://www.mediafire.com/file/ojhk4i28sizplnl/PojavLauncher_Forge_1.3.2-1.7.2_Patchpack_v1.0.zip/file) is the patchpack. Just extract it and replace your current Forge 1.5.1 JSON with this one. If you do both of these things, you should be all fixed. 

If you need libraries for different versions of Forge, make sure to check the **MCArchive** website and search for Minecraft Forge. Afterwards, find your Forge version and there should be a folder named, for example, fmllibs152.zip. Just download that and put the ```lib``` folder inside the zip file into ```.minecraft```

**Comment by Forever2397** [comment]
> [**Here**](https://www.mediafire.com/file/ojhk4i28sizplnl/PojavLauncher_Forge_1.3.2-1.7.2_Patchpack_v1.0.zip/file) is the patchpack. Just extract it and replace your current Forge 1.5.1 JSON with this one. If you do both of these things, you should be all fixed.

thanks i will try

**Comment by Forever2397** [comment]
![Screenshot_2022-08-21-21-10-46-09_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185795253-be452a64-acf8-45e1-bf86-472d32157541.jpg)

why is it like this??

**Comment by GaucovyAero** [comment]
> ![Screenshot_2022-08-21-21-10-46-09_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185795253-be452a64-acf8-45e1-bf86-472d32157541.jpg)
> 
> why is it like this??

have you replaced the JSON?

**Comment by Forever2397** [comment]
> > ![Screenshot_2022-08-21-21-10-46-09_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185795253-be452a64-acf8-45e1-bf86-472d32157541.jpg)
> > why is it like this??
> 
> have you replaced the JSON?

oh yeah i forgot where can i put the JSON file??

**Comment by GaucovyAero** [comment]
> > > ![Screenshot_2022-08-21-21-10-46-09_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185795253-be452a64-acf8-45e1-bf86-472d32157541.jpg)
> > > why is it like this??
> > 
> > 
> > have you replaced the JSON?
> 
> oh yeah i forgot where can i put the JSON file??

```.minecraft/versions/1.5.1-Forge7.7.2.682/1.5.1-Forge7.7.2.682.json```

**Comment by Forever2397** [comment]
> > > > ![Screenshot_2022-08-21-21-10-46-09_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185795253-be452a64-acf8-45e1-bf86-472d32157541.jpg)
> > > > why is it like this??
> > > 
> > > 
> > > have you replaced the JSON?
> > 
> > 
> > oh yeah i forgot where can i put the JSON file??
> 
> `.minecraft/versions/1.5.1-Forge7.7.2.682/1.5.1-Forge7.7.2.682.json`

Ok l will try

**Comment by Forever2397** [comment]
![Screenshot_2022-08-21-21-10-46-09_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185796348-3e7f13df-ea67-44b0-ae33-63021a342214.jpg)

I have changed the json file but why is it like this??

**Comment by GaucovyAero** [comment]
> ![Screenshot_2022-08-21-21-10-46-09_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185796348-3e7f13df-ea67-44b0-ae33-63021a342214.jpg)
> 
> I have changed the json file but why is it like this??

send the log

**Comment by Forever2397** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9389350/latestlog.txt)

**Comment by GaucovyAero** [comment]
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:81)
	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:21)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:51)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more

hmm, looks like it did not download, is something in the directory ```.minecraft/libraries/org/ow2/asm/asm-all/5.2/``` ?

**Comment by GaucovyAero** [comment]
aha, you launched 1.5.2, why don't you launch 1.5.1?

**Comment by Forever2397** [comment]
> aha, you launched 1.5.2, why don't you launch 1.5.1?

i tried to download version 1.5.1 but game exited

**Comment by Forever2397** [comment]
where can i download asm all 5.2??

**Comment by GaucovyAero** [comment]
> where can i download asm all 5.2??

i am not asking you to download, i am asking you if there's something in that folder

**Comment by Forever2397** [comment]
> > where can i download asm all 5.2??
> 
> i am not asking you to download, i am asking you if there's something in that folder

![Screenshot_2022-08-21-21-57-20-81_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185797276-e9e04b6f-718e-497a-9f41-920b479df703.jpg)

finally my problem is solved, thanks you so much

**Comment by GaucovyAero** [comment]
> > > where can i download asm all 5.2??
> > 
> > 
> > i am not asking you to download, i am asking you if there's something in that folder
> 
> ![Screenshot_2022-08-21-21-57-20-81_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185797276-e9e04b6f-718e-497a-9f41-920b479df703.jpg)
> 
> finally my problem is solved, thanks you so much

how did you fix it?

**Comment by Forever2397** [comment]
> > > > where can i download asm all 5.2??
> > > 
> > > 
> > > i am not asking you to download, i am asking you if there's something in that folder
> > 
> > 
> > ![Screenshot_2022-08-21-21-57-20-81_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185797276-e9e04b6f-718e-497a-9f41-920b479df703.jpg)
> > finally my problem is solved, thanks you so much
> 
> how did you fix it?

I replaced the asm-all-5.2.jar file And finally it worked

**Comment by GaucovyAero** [comment]
> > > > > where can i download asm all 5.2??
> > > > 
> > > > 
> > > > i am not asking you to download, i am asking you if there's something in that folder
> > > 
> > > 
> > > ![Screenshot_2022-08-21-21-57-20-81_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185797276-e9e04b6f-718e-497a-9f41-920b479df703.jpg)
> > > finally my problem is solved, thanks you so much
> > 
> > 
> > how did you fix it?
> 
> I replaced the asm-all-5.2.jar file And finally it worked

that's my fault then, i have to do some more debugging i guess.. hmm

**Comment by Forever2397** [comment]
> > > > > > where can i download asm all 5.2??
> > > > > 
> > > > > 
> > > > > i am not asking you to download, i am asking you if there's something in that folder
> > > > 
> > > > 
> > > > ![Screenshot_2022-08-21-21-57-20-81_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/185797276-e9e04b6f-718e-497a-9f41-920b479df703.jpg)
> > > > finally my problem is solved, thanks you so much
> > > 
> > > 
> > > how did you fix it?
> > 
> > 
> > I replaced the asm-all-5.2.jar file And finally it worked
> 
> that's my fault then, i have to do some more debugging i guess.. hmm
 
I hope my problem is solved And I will close this And thank you very much
