### ISSUE TITLE
[BUG] Minecraft 1.18.2 - Fabric 0.14.9 - "Exit code 1" - "FORTIFY: FD_SET: file descriptor 1246 >= FD_SETSIZE 1024"

### ISSUE THREAD

**Issue by unilock** [PojavLauncherTeam/PojavLauncher#3512]
### Describe the bug

I'm trying to play the modpack [All of Fabric 5](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5), version 1.5.1, using PojavLauncher.
However, after launching the game and waiting at a black screen for about a minute, it crashes with "exit code 1".
I believe the relevant error in the log is `FORTIFY: FD_SET: file descriptor 1246 >= FD_SETSIZE 1024`.

### The log file and images/videos

(I'm on mobile, so I can't attach the log directly)
https://gist.github.com/unilock/c24356e90e9ac43bd2d09e1f5cd6809d

### Steps To Reproduce

```markdown
1. Install Fabric 0.14.9 for Minecraft 1.18.2 in a new profile
2. Install All of Fabric 5 version 1.5.1 via the CurseForge launcher on a desktop computer (or equivalent)
3. Copy the contents of the `.minecraft` folder from the CurseForge launcher to to the newly created PojavLauncher profile
4. Attempt to launch the game
5. Crash with "exit code 1"
```

### Expected Behavior

I expected the game to launch to the loading screen, show the main menu, allow joining a world or server, etc.

### Platform

```markdown
- Device model: Google Pixel 6 Pro
- CPU architecture: aarch64
- Android version: Android 13 beta 4
- PojavLauncher version: dahlia-35-23e8a6338-v3_openjdk
```

**Comment by GaucovyAero** [comment]
looks like android killed your app. you are probably out of phone memory, try decreasing RAM allocation until it either starts working, or you get outofmemoryerror.

**Comment by unilock** [comment]
@Aerolome My phone has 12GB of RAM. Android tells me it's typically using about half of that. I've only allocated 3GB of RAM to Minecraft through PojavLauncher, so I don't think that's the issue.

**Comment by GaucovyAero** [comment]
> @Aerolome My phone has 12GB of RAM. Android tells me it's typically using about half of that. I've only allocated 3GB of RAM to Minecraft through PojavLauncher, so I don't think that's the issue.

you should not allocate more than 2GB, otherwise you are going to get terrible performance. try 1200MB first.

**Comment by unilock** [comment]
> you should not allocate more than 2GB, otherwise you are going to get terrible performance.

This is heavily modded 1.18.2, not vanilla 1.7.10. 2GB is practically the minimum for vanilla Minecraft these days. And I've had modded 1.19.2 work well with 3GB RAM allocated.

> try 1200MB first.

Same error. Except this time it stayed on the black screen I mentioned for about twice as long, probably due to the severe RAM limitation.

**Comment by unilock** [comment]
Maybe it has something to do with this?
https://github.com/PojavLauncherTeam/PojavLauncher/blob/81169bccaa000542ab11c949127800d5ddeef18b/app_pojavlauncher/src/main/jni/egl_bridge.c#L730

**Comment by unilock** [comment]
All the mods included in the modpack worked fine *separately* (during a binary search); however, starting the game with the entire set installed results in the same error, which makes me think the game is running out of memory.
I can't allocate more than 6GB though :P

Maybe it's running out of *VRAM*...?

**Comment by GaucovyAero** [comment]
![image](https://user-images.githubusercontent.com/85581164/187761869-7db82494-e720-4402-8ecf-872ef90f380c.png)

this is why i told you it could be a ram allocation issue, because it looks like android killed pojavlauncher

**Comment by unilock** [comment]
Ah, so the error means that Android killed PojavLauncher.

What can I do to fix this? Allocating a low amount of RAM didn't help, nor did allocating the maximum amount of RAM possible on my device.
Note that I'm able to run Minecraft 1.19.2 + Fabric 0.14.9 with fewer mods on 2GB just fine.

**Comment by GaucovyAero** [comment]
> Ah, so the error means that Android killed PojavLauncher.
> 
> What can I do to fix this? Allocating a low amount of RAM didn't help, nor did allocating the maximum amount of RAM possible on my device. Note that I'm able to run Minecraft 1.19.2 + Fabric 0.14.9 with fewer mods on 2GB just fine.

i mean, try sending the log again with a low amount of ram allocated, maybe you are actually getting a normal crash, not just an android-kill-app situation

**Comment by unilock** [comment]
Here's the log with 1200MB allocated.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9477571/latestlog.txt)

**Comment by GaucovyAero** [comment]
> Here's the log with 1200MB allocated. [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9477571/latestlog.txt)

Right, I have no idea what's the issue. Try using GL4ES instead and see if it crashes like this again. There is basically no information provided about the crash in the log, so no idea. If the crash keeps happening on the GL4ES renderer, make sure to reinstall Pojav, but don't use the Google Play Store version. Use this instead:

**How to update your launcher to the actually latest version:**
Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`

**Comment by unilock** [comment]
Log with 1200MB RAM allocated and the "holy gl4es" renderer selected. (I've been using VirGL, if I haven't mentioned that already.)
https://gist.github.com/unilock/44610d3c85244c0ded38b23d6f171e2e

The mod "Create" doesn't work with the GL4ES renderer, as is already known.

The build of PojavLauncher I've been using is from GitHub Actions (branch `v3_openjdk`). I didn't install it from the Play Store.

I can get a logcat later, if that could help?

**Comment by GaucovyAero** [comment]
> Log with 1200MB RAM allocated and the "holy gl4es" renderer selected. (I've been using VirGL, if I haven't mentioned that already.) https://gist.github.com/unilock/44610d3c85244c0ded38b23d6f171e2e
> 
> The mod "Create" doesn't work with the GL4ES renderer, as is already known.
> 
> The build of PojavLauncher I've been using is from GitHub Actions (branch `v3_openjdk`). I didn't install it from the Play Store.
> 
> I can get a logcat later, if that could help?

Yeah, I mean, Holy GL4ES log looks to be totally fine other than the fact that Create doesn't work :D

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
