### ISSUE TITLE
[BUG] <seeing air through blocks>

### ISSUE THREAD

**Issue by lukasinosus** [PojavLauncherTeam/PojavLauncher#3514]
### Describe the bug

Help me pls
![Screenshot_20220822-133813](https://user-images.githubusercontent.com/111748524/185913223-598c6c75-e278-4e8c-a9f1-3d472f4c6c8f.png)

### The log file and images/videos

Help

### Steps To Reproduce

```markdown
Help
```

### Expected Behavior

Help

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher
```

### Anything else?

Help me pls

**Comment by lukasinosus** [comment]
I need help

**Comment by GaucovyAero** [comment]
press F11 and it should fix itself

**Comment by ComicT897** [comment]
Sss UV del
