### ISSUE TITLE
[F-Req] Vulcan runtime

### ISSUE THREAD

**Issue by MOOOOs** [PojavLauncherTeam/PojavLauncher#3515]
### Describe the request.

Hey i was watching recent videos made around 1 month ago about using this launcher and everyone in videos had vulcan runtime. But i tried today and there is no option for Vulcan runtime i only got holy gl4es and virglrenderer which quite bad with fps on my Oneplus 7 Pro with Snapdragon 855. I don't know why vulcan is not present anymore im using play store version of this launcher. I would really like to use better runtime for better fps and Vulcan runtimes on all games that supported on android worked best all the time. Also using latest minecraft version.

**Comment by mchnjt** [comment]
this isn't mcinabox, we don't provide renderers in our runtimes

**Comment by MOOOOs** [comment]
im not even talking about mcinabox im talking about PojavLauncher. Is this possible that person somehow installed vulcan runtime from somewhere?

**Comment by mchnjt** [comment]
this isn't mcina- i mean, zink (or vul"c"an as what you said) is already removed due to issues

**Comment by MOOOOs** [comment]
Is there a way to somehow add Vulkan* back somehow? that person also had pixel 4 with same 855

**Comment by mchnjt** [comment]
i (sort of) added it back on my [fork](https://github.com/c4sc-extras/PojavLauncher/actions/runs/2472992264)
(no virgl, it's a joke)

However, the fork is on an outdated version. It should work nonetheless if your device supports Vulkan

**Comment by MOOOOs** [comment]
Yeah 855 supports Vulkan 1.1  about Virgl its really bad with optifine most stuff not loading textures and stays black like inventory items and character. also how hard is to make fork to newest version if this outdated version works?

**Comment by GaucovyAero** [comment]
> Is there a way to somehow add Vulkan* back somehow? that person also had pixel 4 with same 855

well, there is a lot of work being currently done on zink, it will come back eventually. just use the latest versions with virglrenderer for the time being.

**Comment by MOOOOs** [comment]
Virgl has issues with texture loading with optifine only render that works without texture issues is gl4es but it has fps problems
or maybe it was some setting with virgl idk

**Comment by MOOOOs** [comment]
also what about this https://github.com/PojavLauncherTeam/VulkanMod does it work same way as it would be by default launcher?

**Comment by GaucovyAero** [comment]
> also what about this https://github.com/PojavLauncherTeam/VulkanMod does it work same way as it would be by default launcher?

uhhhh no
