### ISSUE TITLE
[BUG] <error PojavLauncher crash on my device fix pls>

### ISSUE THREAD

**Issue by valterineCraft** [PojavLauncherTeam/PojavLauncher#3516]
### Is this request related to a bug?

PojavLauncher ended up crashing on my android device I can't mention the bug because there are very few times I use this site The error is in the version PojavLauncher version:Merge v3_openjdk into v3_vulkanmod
 Mine Device - model:J2 prime
CPU architecture:aarch32 or aarch I don't know for sure the exact aarch of my device
Android version:6.0.1
I couldn't show pojav launcher error from txt document Why doesn't even show up the pojav folder in my Android even seeing the hidden files in my file explorer
Sorry for the mistakes, I don't speak English very well

**Comment by mchnjt** [comment]
Can't help you man, you used the wrong issue form

**Comment by GaucovyAero** [comment]
Try using ZArchiver for copying the `latestlog.txt` file to your Downloads folder. Make sure to also enable hidden files in ZArchiver before you do that.

**Comment by GaucovyAero** [comment]
Stale issue, not enough info provided. Closing.
