### ISSUE TITLE
[BUG] Unknown host

### ISSUE THREAD

**Issue by 37dni** [PojavLauncherTeam/PojavLauncher#3518]
### Describe the bug

Hi, on PC I'm playing on server "Finerpg.pl" but on pojavlauncher when i try to connect to the server, i only see a message "Unknown host". Can this be a problem of server or pojavlauncher problem? Please help because other servers works.

### The log file and images/videos

![Screenshot_20220824-232153_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/112027533/186526258-6780a226-3a7f-48c5-8463-0b2a6f6dd2e0.jpg)
![20220824_232307](https://user-images.githubusercontent.com/112027533/186526297-cd9a65c2-6b6c-49de-9ed9-fe90b4f80d1d.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start game [1.8.9 vanilla]
3. Join server [Finerpg.pl]
4. You see " Unknown Host "
```

### Expected Behavior

I expect to join the server.

### Platform

```markdown
- Device model: Samsung Galaxy S9
- CPU architecture: Idk
- Android version: 9
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
Sorry that I didn't reply earlier, here is a screenshot from the `#frequently-asked-questions` channel on our official PojavLauncher discord server that you can use to fix your issue.

![image](https://user-images.githubusercontent.com/85581164/188000123-eb616b2a-bcdd-4908-9022-824f58c9b523.png)

**Comment by GaucovyAero** [comment]
Stale issue and likely can be resolved with this fix. Closing.
