### ISSUE TITLE
sire pojav launcher 1.19.2 how to play version apk

### ISSUE THREAD

**Issue by Sire96t** [PojavLauncherTeam/PojavLauncher#3519]
### Is this request related to a bug?

this not bug 1.19.2 how to play version and mods please provide APK me.

### Describe the request.

how to play pojav launcher 1.19.2 version Play please provide APK me.

### Anything else?

how to play 1.19.2 version please provide APK me.
![Screenshot_2022-08-26-09-15-53-215_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/112146803/186813186-a049af1a-1fb5-4e5b-b073-35d282d26676.jpg)

**Comment by rayedalyami** [comment]
How can I get it

**Comment by mchnjt** [comment]
This isn't Minecraft Bedrock. We don't provide game data.

**Comment by mchnjt** [comment]
In order to install the latest version of Minecraft: Java Edition, you must login with a valid, and existing Microsoft account; with Java Edition either migrated or bought on that specific account.

**Comment by Mathias-Boulay** [comment]
old pojav version.
