### ISSUE TITLE
I dont understand the step by step guide enough, im just stupid rlly

### ISSUE THREAD

**Issue by Jzhhdhshxhxh** [PojavLauncherTeam/PojavLauncher#352]
Soo i wanna try the v3 one thats currently really new, but my rlly small brain dont understand what "sdcard/games/.minecraft/lwjgl" or smth, i dont know what to do here, ive download everything thats need to be downloaded. And i also have known what my device architecture... I think thats what theyre called? Idk. Smth like that. Soo yeah... Help me, i guess?

**Comment by khanhduytran0** [comment]
So first look on it
- `/sdcard` could be `/storage/emulated/0` or Internal Storage.
- `.minecraft` start with a dot, so you need enable hidden folder to see it.

**Comment by Jzhhdhshxhxh** [comment]
Ok, soo ive found the ".minecraft" thingy using a file explorer. Now what?, It tolds me to extract the "lwjgl.something.something" or whtevr that is to the "lwjgl" folder on the ".minecraft" am i right or?

**Comment by khanhduytran0** [comment]
Yes
