### ISSUE TITLE
My game crash when i pick fabric - forge - optifine

### ISSUE THREAD

**Issue by TheBestXann** [PojavLauncherTeam/PojavLauncher#3522]
### Describe the bug

Nothing pop up

### The log file and images/videos

Uploading XRecorder_28082022_170348.mp4…

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

I know when i click it, it will not gonna do that

### Platform

```markdown
- Device model: Galaxy A12 Samsung
- CPU architecture: Aarch64
- Android version: 12
- PojavLauncher version:dahlia
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by mchnjt** [comment]
> My game crash when i pick fabric - forge - optifine

forgebrictifine loader? how

**Comment by GaucovyAero** [comment]
Please provide latestlog.txt with the crash in it.

**Comment by GaucovyAero** [comment]
No log provided and stale issue. Closing.
