### ISSUE TITLE
Add a profile icon changer

### ISSUE THREAD

**Issue by PanjiCraft28** [PojavLauncherTeam/PojavLauncher#3524]
### Describe the request.

if possible, every time you add a version the icon can be changed like in Minecraft launcher (pc)

**Comment by GaucovyAero** [comment]
it can be changed, you just gotta use a base64 converter like in this video: https://www.youtube.com/watch?v=V1RL6w65xYM

**Comment by PanjiCraft28** [comment]
![Screenshot_2022-08-30-20-01-07-00](https://user-images.githubusercontent.com/101273756/187444256-7e04bce9-780b-49c0-b56e-055b1bd44f04.png)

**Comment by PanjiCraft28** [comment]
like the photo above

**Comment by mchnjt** [comment]
> like the photo above

As for temporary support, @Aerolome has found a workaround to change profile icons. Please wait for a couple months for devs to implement this feature.

**Comment by GaucovyAero** [comment]
> > like the photo above
> 
> As for temporary support, @Aerolome has found a workaround to change profile icons. Please wait for a couple months for devs to implement this feature.

it isnt a workaround xDD

**Comment by GaucovyAero** [comment]
wont be added because it would be too graphically/ram intensive because we would have to implement an image editor inside the app. also its now practically a lot less useful when you get profile icons from installing modpacks with pojav
