### ISSUE TITLE
add old version 

### ISSUE THREAD

**Issue by PanjiCraft28** [PojavLauncherTeam/PojavLauncher#3525]
### Describe the request.

I want the old Minecraft version to be increased, where the classic version has 28 updates, The indev version has 23 updates, infdev version there are 27 updates, Alpha version There are 47 updates, The beta version has 44 updates. So let it be a lot like Minecraft launcher on computer

**Comment by NotAHero04** [comment]
There're toggles for that in settings. You'll not be able to play *every* version though, because Mojang doesn't provide some. (That means it does apply to the Minecraft Launcher.)

**Comment by Mathias-Boulay** [comment]
Older versions are indeed supported. 
For currently non available versions, maybe if a third party adds a repository from which we can download from

**Comment by SprainedSpark89** [comment]
you can get them here https://omniarchive.org/downloads/

**Comment by mchnjt** [comment]
the legend is back 
![838411174667354122](https://user-images.githubusercontent.com/83752061/188227050-02d915e1-7b24-4273-aae2-93e406c8dd59.png)
