### ISSUE TITLE
[BUG] <Game crashes when joining server with OptiFine 1.19.2>

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [PojavLauncherTeam/PojavLauncher#3526]
### Describe the bug

After installing OptiFine I went into the video settings and made the changes I wanted to I then went back to the title screen clicked on multiplayer, hovered The marse cursor over the server and clicked on the play button and then after like 3 seconds the game crashes

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9467154/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install OptiFine for 1.19.2
2. Change video settings
3. Go back to the title screen
4. Click on multiplaye
5. Hover mouse cursor over server and click on the play button
```

### Expected Behavior

I expect to be able to join the server. 

### Platform

```markdown
- Device model: Samsung Galaxy Note 10+
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version:  [Latest Release || dahlia-8-f527e8a14-v3_openjdk]
```

**Comment by GaucovyAero** [comment]
```
[05:33:56] [Render thread/ERROR]: [OptiFine] OpenGL error: 1280 (Invalid enum), at: Copy VBO: 196608
[05:33:56] [Render thread/ERROR]: [OptiFine] OpenGL error: 1280 (Invalid enum), at: Copy VBO: 1492992
```

Make sure to turn off Render Regions in OptiFine Performance settings, otherwise you are going to crash like this again.

**Comment by SkulZOnTheYT** [comment]
> ```
> [05:33:56] [Render thread/ERROR]: [OptiFine] OpenGL error: 1280 (Invalid enum), at: Copy VBO: 196608
> [05:33:56] [Render thread/ERROR]: [OptiFine] OpenGL error: 1280 (Invalid enum), at: Copy VBO: 1492992
> ```
> 
> Make sure to turn off Render Regions in OptiFine Performance settings, otherwise you are going to crash like this again.

Aerolome's is right, I've explained about render regions but the explanation was removed with github's pojav launcher, so I won't explain anymore -_-

**Comment by GaucovyAero** [comment]
Stale issue and already fixed. Closing.
