### ISSUE TITLE
[BUG] Random Texture 

### ISSUE THREAD

**Issue by Mahipal2007** [PojavLauncherTeam/PojavLauncher#3531]
### Describe the bug

So what basically happens whenever i play the game changes any texture to anything any time like some time mobs have inventory texture some time my skin changes to a mob skin or any other player skin

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9482101/latest.log)

### Steps To Reproduce

```markdown
1. Use mods like Skytils , neu , Skyblock addons , Skyclient updater(updates mod when new version is released) , Optifine 1.8.9
2. Run and play
3. Game wil change texture by itself to anything
```

### Expected Behavior

I expect to see the normal texture 

### Platform

```markdown
- Device model: Vivo v23 5g
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest release
```

### Anything else?

Nah

**Comment by Mahipal2007** [comment]
Bump

**Comment by mchnjt** [comment]
what texture actually

**Comment by Mahipal2007** [comment]
Any texture literally any like my skin changes to other players skin other mobs take texture of gui textures and item changes there texture to blank white or any other like a helmet changes to skyblock item texture in hypixel

**Comment by Mahipal2007** [comment]
It's changes for my side only

**Comment by mchnjt** [comment]
any screenshot?

**Comment by Mahipal2007** [comment]
Let me get it

**Comment by Mahipal2007** [comment]
![Screenshot_20220903_205023](https://user-images.githubusercontent.com/109529762/188277351-28aa7243-12f1-46a7-a2cd-23bd4ce2c4a3.jpg)
That's one of the example even my skin changes to someone else skin

**Comment by GaucovyAero** [comment]
I'm very tempted to say that this might not be an issue with Pojav... Try reloading your resource pack.

**Comment by Mahipal2007** [comment]
![Screenshot_20220903_211120](https://user-images.githubusercontent.com/109529762/188278073-ed7b8efb-daed-4caa-b9fc-07e6f1035434.jpg)
The skin i am wearing is an NPC skin the the skin NPC is wearing is an player skin and that NPC skin i dint do that it changed itself

**Comment by Mahipal2007** [comment]
And i tried without texture pack it's the same it changes the texture of items with any texture

**Comment by GaucovyAero** [comment]
> ![Screenshot_20220903_211120](https://user-images.githubusercontent.com/109529762/188278073-ed7b8efb-daed-4caa-b9fc-07e6f1035434.jpg) The skin i am wearing is an NPC skin the the skin NPC is wearing is an player skin and that NPC skin i dint do that it changed itself

Well, I don't think this is a Pojav issue, try testing the same exact mods on PC.

**Comment by mchnjt** [comment]
"i don't have a pc"
![838411174667354122](https://user-images.githubusercontent.com/83752061/188278239-b742d8c2-d6ba-4b02-b5f2-4dd6cdc37947.png)

**Comment by GaucovyAero** [comment]
well, he can still send the mods here and I can test them for him

**Comment by Mahipal2007** [comment]
The mods are listed in the issue

**Comment by Mathias-Boulay** [comment]
This shouldn't be an issue with latest dev builds

**Comment by GaucovyAero** [comment]
try this dev build (it's from 17.08.2022): https://github.com/PojavLauncherTeam/PojavLauncher/suites/7857967858/artifacts/332982258

**Comment by Mahipal2007** [comment]
What do I do with that?

**Comment by Mahipal2007** [comment]
Bump

**Comment by mchnjt** [comment]
discord be like

**Comment by Mahipal2007** [comment]
Lmao can ya tell me what to do with that app debug file?

**Comment by mchnjt** [comment]
why would you want to install a .zip file

**Comment by GaucovyAero** [comment]
> Lmao can ya tell me what to do with that app debug file?

This is the guide to install it. Just don't follow the download part (becase you've already done it), but follow just the install part:

Check [GitHub Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for the latest version of PojavLauncher. Make sure to always download `v3_openjdk` branch. When you click on the latest `v3_openjdk` build, download `app-debug`, extract it and then install `app-debug.apk`

**Comment by Mahipal2007** [comment]
I am still having a lot of issues like the screen shows some one skin in texture form and some item doesn't show texture

**Comment by Mahipal2007** [comment]
![Screenshot_20220915_165359](https://user-images.githubusercontent.com/109529762/190391824-993aaef6-56ae-4e81-ae00-9af381ee05d5.jpg)
![Screenshot_20220915_165353](https://user-images.githubusercontent.com/109529762/190391855-8b81b883-8c39-47d2-8265-0fa785f30b39.jpg)

**Comment by GaucovyAero** [comment]
could you please try maybe like sending your modpack to us or something?

**Comment by Mahipal2007** [comment]
Mods?

**Comment by Mahipal2007** [comment]
K i will share the mods and texture pack ig

**Comment by Mahipal2007** [comment]
I am unable to upload here

**Comment by Mahipal2007** [comment]
I will upload all needed in ice drive and share link ok?

**Comment by Mahipal2007** [comment]
https://icedrive.net/s/yvbQWzDWVA1R2FR9SCWbAW2GD5Gh
Here it is it has my config file to which has setting of the mods and my texture pack , mods , and my setting of minecraft

**Comment by Mahipal2007** [comment]
Bump

**Comment by Mahipal2007** [comment]
Hello reply pls and why my comment got deleted xD

**Comment by GaucovyAero** [comment]
okay i have them downloaded, now i just need to test, oh and also, does the issue occur on singleplayer?

**Comment by Mahipal2007** [comment]
I haven't tried the single player cus it take a lot of time to load but i will try

**Comment by Mahipal2007** [comment]
Why am I receiving this in email?

**Comment by Mahipal2007** [comment]
Why i got these things in my gmail?

**Comment by Mahipal2007** [comment]
And i replied there it came here 😐

**Comment by Mahipal2007** [comment]
Ye ig it happens there to 
![Screenshot_20220920_153400](https://user-images.githubusercontent.com/109529762/191229988-b8be87ce-171e-4544-804f-246ac659db79.jpg)

**Comment by Mahipal2007** [comment]
Crosshair gone hearts doesn't show hunger bar also doesn't show

**Comment by Mahipal2007** [comment]
I have noticed something that today this only happens when i am using essential but i need the essential for skytils and other mods

**Comment by mchnjt** [comment]
> Why am I receiving this in email?

sir this is 2022 not 90's
stop living under a rock

**Comment by Mahipal2007** [comment]
-.- i meant why do i have these messages e-mailed for no reason

**Comment by Mahipal2007** [comment]
Like u reply literally came in my gmail bro

**Comment by GaucovyAero** [comment]
> Ye ig it happens there to ![Screenshot_20220920_153400](https://user-images.githubusercontent.com/109529762/191229988-b8be87ce-171e-4544-804f-246ac659db79.jpg)

use optifine and in the shaders tab, turn on antialiasing to 2x fxaa

**Comment by Mahipal2007** [comment]
Have the optifine gonna try the 2x fxaa

**Comment by Mahipal2007** [comment]
What does it do tho i don't use shaders

**Comment by GaucovyAero** [comment]
> What does it do tho i don't use shaders

it fixes your hud

**Comment by Mahipal2007** [comment]
K other things dontnchange texture now all it does somw time inventory gui i changes i am fine with that tho and Thank you very much for help

**Comment by GaucovyAero** [comment]
> K other things dontnchange texture now all it does somw time inventory gui i changes i am fine with that tho and Thank you very much for help

well, i will keep the issue open for now, because your issue also happens to me on beta 1.7.3 forge, wonder whats up with that

**Comment by Mahipal2007** [comment]
Ok

**Comment by Mahipal2007** [comment]
Hi any solutions?

**Comment by Mahipal2007** [comment]
The texture comes again now sometimes

**Comment by GaucovyAero** [comment]
skyblock mods generally dont work well, or dont work at all
