### ISSUE TITLE
[BUG] não consigo jogar na 1.16.5 com fabric

### ISSUE THREAD

**Issue by drehMC** [PojavLauncherTeam/PojavLauncher#3533]
### Describe the bug

Sempre quando vou jogar fabric 1.16.5 com optifine/optifabric,inertia client,
sodium MC e fabric api

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9483068/latestlog.txt)

### Steps To Reproduce

```markdown
1 instale o fabric 1.16.5.jar
2 coloque sodium MC 1.16.5,optifabric/optifine,inertia client1.16.5,fabric ali 1.16.5 na pasta mods
3 inicie o fabricloader 1.16.5
```

### Expected Behavior

Que eu consiga jogar na 1.16.5 com fabric,sodium, optifine e inertia client

### Platform

```markdown
- Device model: Redmi 9i 4/128
- CPU architecture: arm
- Android version: 10
- PojavLauncher version: dahlia-8-f527e8 a14-v3_openjdk
```

### Anything else?

Espero que funcione

**Comment by GaucovyAero** [comment]
Please download your mods via a different browser (Brave, Kiwi, Opera). If you are using Chrome (just so you know), it tends to corrupt JARs and ZIPs. Please tell me if it works or not.

**Comment by miggythewriter** [comment]
Don't use optifine and sodium they won't work together

**Comment by drehMC** [comment]
I cant

**Comment by drehMC** [comment]
Im install this for opera

**Comment by drehMC** [comment]
@PrinceNormal i testing this now, dont work

**Comment by GaucovyAero** [comment]
> @PrinceNormal i testing this now, dont work

send log

**Comment by miggythewriter** [comment]
> @PrinceNormal i testing this now, dont work

Use optifine OR sodium don't use them together

**Comment by drehMC** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9483228/latestlog.txt)

**Comment by GaucovyAero** [comment]
```
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:201)
	... 6 more
```
i mean, you still crashed because some mod is corrupted, try using Brave browser to download your mod, please...

**Comment by drehMC** [comment]
Eu ja fiz isto

**Comment by GaucovyAero** [comment]
But your issue is the same, so you haven't really fixed it.

**Comment by GaucovyAero** [comment]
Try deleting Fabric 1.16.5 from .minecraft/versions and then reinstall Fabric. Download the Fabric installer JAR with Brave browser, and try again.

**Comment by drehMC** [comment]
Todas vezes que eu re-instalava os mods eu baixava outro fabric instaler

**Comment by drehMC** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9483290/latestlog.txt)

**Comment by GaucovyAero** [comment]
> 
```
java.io.IOException: error reading /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/fabric-loader-0.14.7-1.16.5/fabric-loader-0.14.7-1.16.5.jar
```
Again, same issue. Your Fabric 1.16.5 JAR is corrupted. I think you are doing something incorrectly. First time seeing this issue.

**Comment by DucKgst** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9483311/latestlog.txt)

**Comment by drehMC** [comment]
Agora fui sem mods

**Comment by drehMC** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9483319/latestlog.txt)

**Comment by drehMC** [comment]
Você tem alguma ideia de qual erro eu devo ter feito?

**Comment by GaucovyAero** [comment]
> Você tem alguma ideia de qual erro eu devo ter feito?

No, I have absolutely no idea. Make sure you use Brave browser for both the Fabric Installer, and the mods. Also, you have to wait longer when the assets and other stuff are downloading.

**Comment by drehMC** [comment]
Olha eu ainda não entendo disso mas será que é porque eu não baixei os assets por completo?

**Comment by drehMC** [comment]
E o mesmo erro está acontecendo com o 1.12.2 forge agora que eu vi isso

**Comment by GaucovyAero** [comment]
Yeah, this issue is weird. Join our official PojavLauncher discord server to get more support i guess.

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9483319/latestlog.txt)

Oh wait no, the issue here is that you used Java 17 to launch 1.16.5.
For 1.16.5 and older, use Java 8.

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
