### ISSUE TITLE
[BUG] JRE_Runtime Wrong Version when installing the APK

### ISSUE THREAD

**Issue by ShawnTrack** [PojavLauncherTeam/PojavLauncher#3535]
### Describe the bug

When installing via the apk, you will have a old JRE's version. If you start the Minecraft 1.19, you'll receive a Exit code 1.

This is the latestlog.txt
 

### The log file and images/videos

--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-opengl.jar, lwjgl-jemalloc.jar, lwjgl-stb.jar, lwjgl-openal.jar, lwjgl.jar, lwjgl-tinyfd.jar, version, lwjgl-glfw-classes.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms512m -Xmx800m"
Headless version detected! (20220805)
--------- beginning of main
I/jrelog  (22572): Starting logging STDIO as jrelog:V
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x361
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  (22572): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" unused DT entry: DT_RPATH
I/jrelog  (22572):  (type 0xf arg 0x450) (ignoring)
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x33c0
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x13b8
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x2196
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x6a46
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x4d9
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0xda0
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0xf13
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so success
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x1d2
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so success
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsunec.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x1c1
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x139
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so success
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so
I/jrelog  (22572): " unused DT entry: 
I/jrelog  (22572): DT_RPATH
I/jrelog  (22572):  (type 
I/jrelog  (22572): 0xf
I/jrelog  (22572):  arg 
I/jrelog  (22572): 0x5e6
I/jrelog  (22572): ) (ignoring)
I/jrelog  (22572): 
I/jrelog  (22572): WARNING: linker: 
I/jrelog  (22572): Warning: "
I/jrelog  (22572): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so
I/jrelog  (22572): " has unsupported flags DT_FLAGS_1=
I/jrelog  (22572): 0x81
I/jrelog  (22572):  (ignoring unsupported flags)
I/jrelog  (22572): 
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so success
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  (22572): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  (22572): OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/jrelog  (22572): Error: A JNI error has occurred, please check your installation and try again
I/jrelog  (22572): 
I/jrelog  (22572): Exception in thread "main" 
I/jrelog  (22572): java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.lang.ClassLoader.defineClass1(Native Method)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.security.AccessController.doPrivileged(Native Method)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
I/jrelog  (22572): 
I/jrelog  (22572): 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
I/jrelog  (22572): 
I/jrelog  (22572): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
I/jrelog  (22572): 
I/jrelog  (22572): 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
I/jrelog  (22572): 
Java Exit code: 1
I/jrelog  (22572): Going to free args
I/jrelog  (22572): Free done
--------- beginning of system

### Steps To Reproduce

```markdown
1. Clean instalation of the latest APK (Today is September, 04 of 2022)
2. Try playing Minecraft 1.19
```

### Expected Behavior

Menu screen appearing, instead getting an error.

### Platform

```markdown
- Device model: Oculus Quest 1
- Android version: 10
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
QuestCraft support is on QuestCraft's GitHub repo, your issue maybe that you haven't waited enough for the runtime to unpack when you first opened Pojav. Since the support for QuestCraft is not located here, I'm closing this.
