### ISSUE TITLE
[Minecraft Forge 1.7.10] <Problem with Gliby's Voice Chat>

### ISSUE THREAD

**Issue by ShippoteChan** [PojavLauncherTeam/PojavLauncher#3537]
### Describe the bug

The game starts "normally" with no audio, after a few minutes it just appears The application/game has closed with error -1

This error is replicated on multiple mobile devices, but I do not fully understand the problem that causes this situation 

### The log file and images/videos

[crash-2022-09-05_02.51.38-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9486600/crash-2022-09-05_02.51.38-client.txt)
[fml-client-latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9486601/fml-client-latest.log)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9486602/latest.log)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Load the game with version 1.7.10 forge 1614 And only Gliby's Voice Chat mod.
3. The game starts completely until the main menu is displayed but there is no Audio.
4. About a minute goes by and the game just crashes, even without entering a world.
```

### Expected Behavior

I expected the game to work properly 

### Platform

```markdown
- Device model: LG V40 ThinQ/64G
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: v3-3-1-1-1833-9680ba11b-v3-openjdk
```

**Comment by artdeell** [comment]
Hellishly outdated version, also all the wrong logs.

**Comment by ShippoteChan** [comment]
I just updated it, same result ![Screenshot_20220904-234308.png](https://user-images.githubusercontent.com/91218939/188362084-faafde10-d648-4b5d-85d6-290d2d5c21cd.png)

here the log

![latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9486737/latest.log)

**Comment by ShippoteChan** [comment]
I just updated it, same result ![Screenshot_20220904-234308.png](https://user-images.githubusercontent.com/91218939/188362084-faafde10-d648-4b5d-85d6-290d2d5c21cd.png)

here the log

![latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9486737/latest.log)

**Comment by GaucovyAero** [comment]
```
java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.playing(SoundManager.java:499)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:218)
```
The only voice chat mod that works on Pojav is a fork of SimpleVoiceChat on QuestCraft's repository. Only 1.19.2 tho. https://github.com/QuestCraftPlusPlus/simple-voice-chat/releases

**Comment by GaucovyAero** [comment]
Also, the **correct** log is `latestlog.txt`, it's located in (for various Android versions respectively):
- Android 9 and older: `/storage/emulated/0/games/PojavLauncher/latestlog.txt`
- Android 10 and newer: `/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt`

**Comment by ShippoteChan** [comment]
@Aerolome Thanks for the answer, I know it works, I used it before.

Too bad, I need 1.7.10 for a Mod that is only there (and still in development, Dragon Block C) I will have to sacrifice Gliby Voice Chat

i will close this

**Comment by ShippoteChan** [comment]
Hello, well, as you can see, I reopened the topic because recently I had the problem that it no longer only failed with this version 1.7.10.

Now, I'm back again to try to use PojavLauncher for Minecraft 1.7.10 and I would like VoiceChat to work in this version as well. 

I will try to provide what you need so we can resolve this as much as possible.

I am now using the most current version of PojavLauncher. I am on Minecraft version 1.7.10 Forge 1614

**Comment by GaucovyAero** [comment]
the only voice chat mod that works on pojav is SVC. we cannot do anything about other mods not working

**Comment by ShippoteChan** [comment]
i understand though, i also recently had problems with svc as i was using minecraft 1.19.2 and the app just crashed

**Comment by ShippoteChan** [comment]
i understand though, i also recently had problems with svc as i was using minecraft 1.19.2 and the app just crashed

**Comment by GaucovyAero** [comment]
we cant fix this
