### ISSUE TITLE
[BUG] Crash on launch

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3539]
### Describe the bug

crash on launch of 1.12.2 vanilla on  newly installed pojav launcher (downloaded from playstore)

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: dahlia-8-f527e8a14-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.12.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1482
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-22Uxo0mXjopJrZWEz-yZZw==/lib/arm
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch-22Uxo0mXjopJrZWEz-yZZw==/lib/arm
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
--------- beginning of crash

--------- beginning of main

I/LIBGL   (15818): Initialising gl4es
I/LIBGL   (15818): v1.1.4 built on May 28 2022 20:23:51
I/LIBGL   (15818): Using GLES 2.0 backend
I/LIBGL   (15818): loaded: libGLESv2.so
I/LIBGL   (15818): loaded: libEGL.so
I/LIBGL   (15818): Using GLES 2.0 backend
I/LIBGL   (15818): Hardware Full NPOT detected and used

I/LIBGL   (15818): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (15818): FBO are in core, and so used
I/LIBGL   (15818): PointSprite are in core, and so used
I/LIBGL   (15818): CubeMap are in core, and so used
I/LIBGL   (15818): BlendColor is in core, and so used
I/LIBGL   (15818): Blend Substract is in core, and so used
I/LIBGL   (15818): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (15818): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (15818): Extension GL_OES_mapbuffer  detected
I/LIBGL   (15818): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (15818): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (15818): Extension GL_OES_depth24  detected and used
I/LIBGL   (15818): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (15818): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (15818): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (15818): Extension GL_OES_texture_stencil8  d
etected and used
I/LIBGL   (15818): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (15818): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (15818): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (15818): high precision float in fragment shader available and used
I/LIBGL   (15818): Max vertex attrib: 16
I/LIBGL   (15818): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (15818): Max texture size: 8192
I/LIBGL   (15818): Max Varying Vector: 15
I/LIBGL   (15818): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (15818): Hardware vendor is ARM
I/LIBGL   (15818): GLSL 300 es supported
I/LIBGL   (15818): GLSL 310 es supported and used
I/LIBGL   (15818): GLSL 320 es supported
I/LIBGL   (15818): Max Color Attachments: 4 / Draw buffers: 4
I/LIBGL   (15818): sRGB surface supported
I/LIBGL   (15818): EGLImage to Texture2D supported
I/LIBGL   (15818): EGLImage to RenderBuffer supported
I/LIBGL   (15818): ignore MipMap
I/LIBGL 
  (15818): Targeting OpenGL 2.1
I/LIBGL   (15818): No hack in shader converter to define overloaded function with int
I/LIBGL   (15818): NPOT texture handled in hardware
I/LIBGL   (15818): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (15818): try to use VBO
I/LIBGL   (15818): glXMakeCurrent FBO workaround enabled
I/LIBGL   (15818): FBO workaround for using binded texture enabled
I/LIBGL   (15818): glX Will try to recycle EGL Surface
I/LIBGL   (15818): Current folder is:/
I/jrelog  (15818): dlopen libgl4es_114.so success
I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  (15818): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success
I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmlib_image.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsunec.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libhprof.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pkcs11.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libzip.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjawt.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjaas_unix.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_xawt.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjdwp.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsig.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsctp.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/liblcms.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libdt_socket.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjpeg.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libunpack.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libtinyiconv.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsdt.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsound.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2gss.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmanagement.so success

I/jrelog  (15818): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pcsc.so success

I/jrelog  (15818): dlopen /data/app/net.kdt.pojavlaunch-22Uxo0mXjopJrZWEz-yZZw==/lib/arm/libopenal.so success

I/jrelog  (15818): Done processing args

I/jrelog  (15818): Found JLI lib

I/jrelog  (15818): Calling JLI_Launch

Error occurred during initialization of VM
Could not reserve enough space for 958464KB object heap
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xe5ce82a0)
process killed with signal 6 code 0xffffffff addr 0x3dca

### Steps To Reproduce

```markdown
launch it, wait to download everything and it crashes after 2 seconds
```

### Expected Behavior

hmm not crashing

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
`Could not reserve enough space for 958464KB object heap`

Please allocate less RAM than the 32-bit limit is.

**Comment by ghost** [comment]
ok

**Comment by GaucovyAero** [comment]
Well I guess this issue is resolved. Closing.
