### ISSUE TITLE
1

### ISSUE THREAD

**Issue by yesayans** [PojavLauncherTeam/PojavLauncher#3540]
Fixed

**Comment by mchnjt** [comment]
Common fix;

1. Check if your email account and password is correct and valid

**Comment by MrGrigorPC** [comment]
> Common fix;
> 
> 1. Check if your email account and password is correct and valid

I am sure that my password and email are correct, I entered the official launcher with the same data.

**Comment by Pinecone6442** [comment]
nah thats your bedrock account
