### ISSUE TITLE
The inscriptions are not displayed in versions 1.17 and above.

### ISSUE THREAD

**Issue by Kolyanpetuh** [PojavLauncherTeam/PojavLauncher#3541]
### Describe the bug

When I run version 1.17 or higher, the screen does not show any inscriptions at all. On versions of Forge and OptiFine 1.17 and above, the same problem.

### The log file and images/videos

I can't do it.

### Steps To Reproduce

```markdown
Install any resourcepacks.
```

### Expected Behavior

I expect the inscriptions are displayed normally.

### Platform

```markdown
- Device model: Xiaomi Redmi Note 9 Pro
- CPU architecture: Snapdragon 618
- Android version: 12L
- PojavLauncher version: 3
```

### Anything else?

Please solve this problem!

**Comment by GaucovyAero** [comment]
please send latestlog.txt

**Comment by HypeMaxers** [comment]
![Screenshot_20220911-234904_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/41132838/189550355-0c146474-1db3-4742-b709-df3255da6b68.jpg)
Is this something similar to what you're experiencing? If so i can provide the latest logs.

**Comment by GaucovyAero** [comment]
> ![Screenshot_20220911-234904_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/41132838/189550355-0c146474-1db3-4742-b709-df3255da6b68.jpg) Is this something similar to what you're experiencing? If so i can provide the latest logs.

Oh, right, I understand. Your graphics chip is a PowerVR GE8320 64-bit limited to 32-bit mode. I know that, because ONLY this chip ONLY in this mode does this. 

The fix:
1. Install OptiFine
2. In Options -> Video Settings -> Performance, set Fast Render to OFF
3. In  Options -> Video Settings -> Shaders, set Antialiasing to 2x FXAA

**Comment by GaucovyAero** [comment]
@Kolyanpetuh
For you, the fix may be different. Just use Holy GL4ES as the renderer, not virglrenderer.

**Comment by Kolyanpetuh** [comment]
> @Kolyanpetuh
> For you, the fix may be different. Just use Holy GL4ES as the renderer, not virglrenderer.

Thank you so much! It worked for me!

**Comment by GaucovyAero** [comment]
Sounds great! Closing. :D
