### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by JJoshua04** [PojavLauncherTeam/PojavLauncher#3543]
### Describe the bug

Eye mod crashes it when I use fabric can u fix it and also fix sodium pls

### The log file and images/videos

Don't have one

### Steps To Reproduce

```markdown
Insert the mod into the mods folder and try to play it With Fabric and it crashes
```

### Expected Behavior

I expect it to launch it work 

### Platform

```markdown
- Device model: Samsung a20
- CPU architecture: arm64...
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

Nah

**Comment by ghost** [comment]
lol who cares

**Comment by GaucovyAero** [comment]
You have the log, crash the game and send `latestlog.txt`

Android 9 or older: `/storage/emulated/0/games/PojavLauncher/latestlog.txt`
Android 10 and newer: `/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt`

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
