### ISSUE TITLE
[BUG] Why does the game crash when I use Virgl renderer?

### ISSUE THREAD

**Issue by pedro4666** [PojavLauncherTeam/PojavLauncher#3544]
### Describe the bug

Game crashes when doing the initialization in with Virgl

### Platform

```markdown
- Device model: Motorola E20 2/32G
- CPU architecture: arm32
- Android version: 11
- PojavLauncher version: version: dahlia-56-3b771d602-v3_vulkanmod
```

**Comment by cyvinn** [comment]
ok and

**Comment by Aerolome** [comment]
Please do not use the `v3_vulkanmod` branch and use the official main `v3_openjdk` one. Branches different than `v3_openjdk` are just meant for testing and may not work as expected.
