### ISSUE TITLE
[BUG] Why does the game crash when I use Virgl renderer? 

### ISSUE THREAD

**Issue by pedro4666** [PojavLauncherTeam/PojavLauncher#3545]
### Describe the bug

Game crashes when logging in with Virgl
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9530729/latestlog.txt)

### Platform

```markdown
- Device model: Motorola E20 2/32G
- CPU architecture: arm32
- Android version: 11
- PojavLauncher version: dahlia-56-3b771d602-v3_vulkanmod
```

**Comment by Mathias-Boulay** [comment]
non mainline build. Please use builds from the v3_openjdk branch

**Comment by pedro4666** [comment]
> non mainline build. Please use builds from the v3_openjdk branch

But what does that have to do with the problem using a different unofficial version?
