### ISSUE TITLE
Error Code -1 While In Loading Screen

### ISSUE THREAD

**Issue by HeisenbergMCreal** [PojavLauncherTeam/PojavLauncher#3547]
### Describe the bug

Application/Game Exited With The Code -1 while it was in the Mojang loading screen

### The log file and images/videos

https://gist.github.com/HeisenbergMCreal/9c3c8b3a3705fff2e4d826dd8cb79ba1
(Latestlog.txt Direct link cuz mobile)

(Loading Screen Screenshot)
![Screenshot_2022-09-10-22-18-41-437_net kdt pojavlaunch](https://user-images.githubusercontent.com/113271162/189509979-51e02544-4298-4e82-a5fc-9125c9aca9aa.jpg)

### Steps To Reproduce

```markdown
1. Install Batmod Client in the Install .Jar button
2. Start Minecraft
```

### Expected Behavior

That it launches normally

### Platform

```markdown
- Device model: Redmi 6 Note Pro
- CPU architecture: aarch64
- Android version: idk 10 probably
- PojavLauncher version: Dahlia-8-f527e8a14v3_openjdk
```

### Anything else?

i was trying to install Batmod Client in pojavlauncher and this error appeared while loading, first time this error happened to me and i don't have any clue why help pls

**Comment by mchnjt** [comment]
> https://gist.github.com/HeisenbergMCreal/9c3c8b3a3705fff2e4d826dd8cb79ba1
(Latestlog.txt Direct link cuz mobile)


https://user-images.githubusercontent.com/83752061/189511094-78773e44-a9a4-4a86-abcc-0184456abdf0.mp4

**Comment by GaucovyAero** [comment]
```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
```
You are pirating Minecraft, therefore it will not work.

**Comment by GaucovyAero** [comment]
#2679
