### ISSUE TITLE
[BUG] <não é possível jogar com mods na 1.7.10

### ISSUE THREAD

**Issue by drehMC** [PojavLauncherTeam/PojavLauncher#3548]
### Describe the bug

Quando eu coloquei um modpack (https://www.mediafire.com/file/bcw39cq9urow0ju/mods.rar/file) de 40+ mods no forge 1.7.10 crasha

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9542439/latestlog.txt)

### Steps To Reproduce

```markdown
1coloque o modpack citado a cima na pasta .minecraft/mods
2 baixe o forge 1.7.10
3 entre no minecraft
```

### Expected Behavior

Quero jogar com mods na 1.7.10

### Platform

```markdown
- Device model: Samsung A21s 4/64
- CPU architecture: aarch64 
- Android version: 11
- PojavLauncher version: crocus-224-3ee46f49c-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
```
java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) ~[Not-Enough-Items-1.7.10-Latest.jar:?]
```
CodeChickenLib is missing or corrupted. The downloads are broken now. I put in a ZIP here, the JAR mod is inside it. Put the JAR inside into Minecraft like this: `.minecraft/mods/1.7.10/CodeChickenLib-1.7.10-1.1.3.138-universal.jar`

**[CodeChickenLib-1.7.10-1.1.3.138-universal.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/9542590/CodeChickenLib-1.7.10-1.1.3.138-universal.zip)**

**Comment by drehMC** [comment]
Ok muito obrigado mais uma vez amo o jeito que vocês tratam seus clientes

**Comment by drehMC** [comment]
Mas dessa vez eu consegui chegar ate a tela de carregamento da mojang mas crashou denovo

**Comment by drehMC** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9542812/latestlog.txt)

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9542812/latestlog.txt)

Remove EnderIO, EnderCore and everything related to it. These mods are not compatible with Pojav.

**Comment by drehMC** [comment]
Relacionado? Por exemplo oque?

**Comment by DucKgst** [comment]
![Uploading Screenshot_20220911-121638_ZArchiver.jpg…]()

**Comment by drehMC** [comment]
![Screenshot_20220911-121638_ZArchiver](https://user-images.githubusercontent.com/88793348/189535273-a945b9ac-7679-42dd-b610-a5bcb56936ce.jpg)

**Comment by drehMC** [comment]
Estes?

**Comment by GaucovyAero** [comment]
> Estes?

try that i guess

**Comment by GaucovyAero** [comment]
and then send the log

**Comment by drehMC** [comment]
Consegui entrar mas a textura bugou

**Comment by drehMC** [comment]
Mas ainda tenho que tentar entrar em um mundo

**Comment by drehMC** [comment]
![Screenshot_20220911-122416_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88793348/189535685-65414e17-6dfc-48d7-8b5e-f6439125012a.jpg)

**Comment by drehMC** [comment]
![Screenshot_20220911-122404_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88793348/189535698-7a28c4dc-0bad-4290-8fb1-60aa2ca7a4b0.jpg)

**Comment by GaucovyAero** [comment]
> Consegui entrar mas a textura bugou

press F11 as many times as you can till it fixes itself

**Comment by drehMC** [comment]
Amigo eu não vi sua mensagem depois da última screenshot mas eu consegui resolver desativando todas as opções do optfine em Quality e também consegui entrar em um mundo mas acabou q eu não gostei do modpack

**Comment by drehMC** [comment]
Mas pelo menos você resolveu todos meus ploblemas, muito obrigado.

**Comment by GaucovyAero** [comment]
Okay, cool! Closing.
