### ISSUE TITLE
RSA Padding

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#355]
Will RSA Padding be in v3?
So we can play premium servers?

**Comment by Malaska678** [comment]
I think skin would also work on v3

**Comment by khanhduytran0** [comment]
Yes, you can also ping and join some servers that v2 could not.

**Comment by WesleyVanNeck** [comment]
in both versions it suported as i fixed most multiplayers stuff at v2 @leetmussc also it hase rsa padding
