### ISSUE TITLE
[BUG] stuck/delayed movement 

### ISSUE THREAD

**Issue by wkosh** [PojavLauncherTeam/PojavLauncher#3551]
### Describe the bug

I start the normal version without bugs but when I go to move the character is delayed even though I have 120 FPS and it only happens 1.18+ 

### The log file and images/videos

I don't have files that prove this but I give my word 

### Steps To Reproduce

```markdown
1.start pojav 
2.I log into my account online
3.I start in versions 1.17+
4.I enter the world 
5.I move the character, but it gets delayed/stuck even with 120 fps
```

### Expected Behavior

The movement does not get stuck/delayed, so that the character's movement becomes normal 

### Platform

```markdown
- Device model: Redmi Note 11
- CPU architecture: Aarch64
- Android version: 11
- PojavLauncher version: dahlia-37-7f4e922a2-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
Please join the official PojavLaucnher discord server and ask for help there, so maybe we can respond faster and stuff. Also, maybe show a video of it happening? :D

**Comment by wkosh** [comment]
> Por favor, junte-se ao servidor oficial de discórdia PojavLaucnher e peça ajuda lá, então talvez possamos responder mais rápido e outras coisas. Além disso, talvez mostre um vídeo disso acontecendo? :D

ok I'll send a video right here but I also have the problem of not being able to record inside the game it just crashes

**Comment by GaucovyAero** [comment]
> > Por favor, junte-se ao servidor oficial de discórdia PojavLaucnher e peça ajuda lá, então talvez possamos responder mais rápido e outras coisas. Além disso, talvez mostre um vídeo disso acontecendo? :D
> 
> ok I'll send a video right here but I also have the problem of not being able to record inside the game it just crashes

about the video recording crashing, just allocate less RAM to pojav, and maybe if you need to, use an older minecraft version.

**Comment by wkosh** [comment]
I solved the problem, it was a configuration on my phone that was leaving any game stuck / with delay thanks for the support anyway
