### ISSUE TITLE
Pojav launcher crash on using fabric

### ISSUE THREAD

**Issue by anuragamer** [PojavLauncherTeam/PojavLauncher#3555]
### Describe the bug

Application exited with exit code 1 please check latestlog 

### The log file and images/videos

[latestlog.txt.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/9562871/latestlog.txt.zip)

### Steps To Reproduce

```markdown
Please check my log file given below
```

### Expected Behavior

I am using 1.19.2 fabric with sodium and iris shaders

### Platform

```markdown
- Device model: iqoo neo 6
- CPU architecture: 64
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

[latestlog.txt.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/9562863/latestlog.txt.zip) 
Here is log file please tell me solution

**Comment by GaucovyAero** [comment]
Remove Sodium and other mods related. They don't work on Pojav, because GL4ES doesn't support OpenGL 3.2 and VirGL is veeery buggy. So just don't use C2ME, Sodium, Lithium, Flywheel and Create. If you want to get more FPS, use OptiFabric and Starlight.

**Comment by anuragamer** [comment]
> Remove Sodium and other mods related. They don't work on Pojav, because GL4ES doesn't support OpenGL 3.2 and VirGL is veeery buggy. So just don't use C2ME, Sodium, Lithium, Flywheel and Create. If you want to get more FPS, use OptiFabric and Starlight.

I can use metro client?

**Comment by anuragamer** [comment]
I can use metro client

**Comment by GaucovyAero** [comment]
No idea. Depends if it has DiscordRPC integrated or not.

**Comment by GaucovyAero** [comment]
> I can use metro client

Have you tried it and it works?

**Comment by anuragamer** [comment]
> > I can use metro client
> 
> Have you tried it and it works?
Can u tell me all settings that I can u to run fabric with metor client

**Comment by GaucovyAero** [comment]
i have absolutely no idea, you will have to test that yourself unfortunately

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
