### ISSUE TITLE
[BUG] Unable to join MCC Island

### ISSUE THREAD

**Issue by AverageFemale** [PojavLauncherTeam/PojavLauncher#3558]
### Describe the bug

MCC Island is in closed beta and I got access to it, I went to join the game, but I am unable to because of their resource pack. I've asked their discord and its because of pojav. I checked the logs and theres an error after each load, Could not reload shaders, Attached is the log file.
I've tried with and without mods.

### The log file and images/videos

[Latest2.log](https://drive.google.com/file/d/1bvLRPMxT5yaPVaQoZPJZfiC-JdcKaykS/view?usp=drivesdk) (Google Drive because I had troubles uploading it for some reason)

### Steps To Reproduce

```markdown
1. Open Pojav
2. Join MCC Island (You have to be in their closed beta to join)

You can join the world but you'll be infinitly loading the resource pack.
```

### Expected Behavior

I expect the game to load into the server and I would be able to see their resource pack models/items.

### Platform

```markdown
- Device model: Samsung galaxy s20+
- CPU architecture: No clue, Think its aarch64
- Android version: 13
- PojavLauncher version: Latest playstore build.
```

**Comment by Mathias-Boulay** [comment]
I'll need an access to this beta to solve the issue.

**Comment by mchnjt** [comment]
pojav devs playing mcc island👀

**Comment by AverageFemale** [comment]
> I'll need an access to this beta to solve the issue.

Not meaning to advertise, but heres the link to sign-up for beta or buy instant pass. [Link](https://mccsignup.noxcrew.com/)
I got accepted into it a day after I registered but others took weeks/months so its RNG when they will accept you.

**Comment by Mathias-Boulay** [comment]
Not even going to care to wait for months for this, nor send my email to someone who will resell it.
Either you get a way for me to access it and debug, either I can't do anything.

**Comment by AverageFemale** [comment]
I could give you my login temporary. Add me on discord Kweeme | 🍮#5748

**Comment by Mathias-Boulay** [comment]
No, I don't need to be accused of hacking account.
My mc username is "SerpentSpirale", might be of some use if you can contact them

**Comment by iKrism** [comment]
Sometimes i think mathias is lazy to fix the issue and i also think he doesnt wanna fix it at all! Crazy...
They dont have to give you a way to get you in mathias,YOU are the dev And YOU are fixing the bug so dont be lazy and lay back waiting people to do stuff for you.

Its easy to sign up man

**Comment by artdeell** [comment]
> Sometimes i think mathias is lazy to fix the issue and i also think he doesnt wanna fix it at all! Crazy... They dont have to give you a way to get you in mathias,YOU are the dev And YOU are fixing the bug so dont be lazy and lay back waiting people to do stuff for you.
> 
> Its easy to sign up man

If you are so entitled to get a fix for this, go to our [gl4es repository](https://github.com/PojavLauncherTeam/gl4es-114-extra) and fix the issue yourself. Nobody from the dev team is willing to fix anything that isn't accessible to the public and therefore isn't easily testable without signing up and waiting for something.

**Comment by artdeell** [comment]
If you feel like my reply is unfair, reread yours. YOU play on the inaccessible server, not us.

Also nobody in the dev team is paid hourly, so all the work on the project is at-will.

**Comment by iKrism** [comment]
I feel like you are speaking for everyone here by saying "you play on the inaccessible server not us",but alright,there IS alot people who has pojav have a admission ticket and wants to play in the Mcc server.

But fine you do have a point the devs does not get paid hourly to fix or work on pojav andd also cant wait to get a ticket probably.

in resume i think this issue will remain unfixed forever until the MCC island is open to the public i think due that is not acessible for the pojav devs

**Comment by Mathias-Boulay** [comment]
> Sometimes i think mathias is lazy to fix the issue and i also think he doesnt wanna fix it at all! Crazy... They dont have to give you a way to get you in mathias,YOU are the dev And YOU are fixing the bug so dont be lazy and lay back waiting people to do stuff for you.
> 
> Its easy to sign up man

Yes I'm lazy. I do prefer spending time fixing issues that the majority of people are facing rather than waiting months.

**Comment by AverageFemale** [comment]
> Yes I'm lazy. I do prefer spending time fixing issues that the majority of people are facing rather than waiting months.

I'll sign you up for you.. once accepted I'll let you know here. Sorry for the 2 day response.

**Comment by AverageFemale** [comment]
> No, I don't need to be accused of hacking account. My mc username is "SerpentSpirale", might be of some use if you can contact them

Congrats, you now have access.
IP Is: play.mccisland.net

**Comment by Mathias-Boulay** [comment]
Nice to hear. Once I get my device back to a working state, I'll check out what I can do

**Comment by GaucovyAero** [comment]
> > No, I don't need to be accused of hacking account. My mc username is "SerpentSpirale", might be of some use if you can contact them
> 
> Congrats, you now have access. IP Is: play.mccisland.net

Hello. We have a new renderer in the testing. Please test with ANGLE (the new renderer) to see if it still crashes: https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8866885758/artifacts/404850022

**Comment by AverageFemale** [comment]
> > > No, I don't need to be accused of hacking account. My mc username is "SerpentSpirale", might be of some use if you can contact them
> > 
> > Congrats, you now have access. IP Is: play.mccisland.net
> 
> Hello. We have a new renderer in the testing. Please test with ANGLE (the new renderer) to see if it still crashes: https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8866885758/artifacts/404850022

The angle renderer works fine with MCC.
Though not with sodium.

**Comment by AverageFemale** [comment]
Closing because the original subject is fixed with the new angle renderer.

**Comment by jaydos2022** [comment]
hey anyway someone can help me get into mcci on pojav launcher i can get in the server but kicks me as it does not load the reasource packs

**Comment by AverageFemale** [comment]
Use the ANGLE engine.
