### ISSUE TITLE
1.17.1 Crash[F-Req] <Short description>

### ISSUE THREAD

**Issue by Sahilbone** [PojavLauncherTeam/PojavLauncher#3559]
### Is this request related to a bug?

I am open my pojav launcher and I use Java 17 arch64 but my game is crash so what is this problem you tell me plz

### Describe the request.

I am open my pojav launcher and I use Java 17 arch64 but my game is crash so what is this problem you tell me plz

### Anything else?

I am open my pojav launcher and I use Java 17 arch64 but my game is crash so what is this problem you tell me plz

**Comment by Sahilbone** [comment]
My moblie version is Android 11 and my pojav launcher version lastest

**Comment by GaucovyAero** [comment]
i mean. literally, everything is wrong in your message. please provide latestlog.txt with the crash in it.

**Comment by Sahilbone** [comment]
Ok sir 
I am soory but my English is so weak

**Comment by GaucovyAero** [comment]
> Ok sir I am soory but my English is so weak

send latestlog.txt and use a translator

**Comment by Sahilbone** [comment]
``

> #
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9574757/latestlog.txt)

**Comment by Sahilbone** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9574762/latestlog.txt)

**Comment by Sahilbone** [comment]
Suppose you have given it sir now look at him

**Comment by Sahilbone** [comment]
Suppose you have sent 2 because once it was changed

**Comment by Sahilbone** [comment]
Plz solve this issue sir

**Comment by NotAHero04** [comment]
Your launcher is too outdated.

**Comment by GaucovyAero** [comment]
well, yeah, you're on a SUPER outdated version of PojavLauncher (maybe even 2 years old). Here's the [**latest one**](https://github.com/PojavLauncherTeam/PojavLauncher/suites/7857967858/artifacts/332982258).

**How to install it:**
1. Uninstall **old PojavLauncher** that you have now
2. Download **new PojavLauncher** with the link i sent you, it should be named `app-debug.zip`
3. Install **ZArchiver** from Google Play Store
4. Open **ZArchiver**, go to `Downloads`
5. Click on `app-debug.zip` and press `Extract to ./<Archive name>/`
6. There should now be a folder called `app-debug`
7. Go to the `app-debug` folder
8. Click on `app-debug.apk`
9. Click `Install`
10. You are finished. That's all.

**Comment by Sahilbone** [comment]
where is the link sir

**Comment by GaucovyAero** [comment]
> where is the link sir

https://github.com/PojavLauncherTeam/PojavLauncher/suites/7857967858/artifacts/332982258

**Comment by Sahilbone** [comment]
sir i am doing the latest version of pujv launcher

**Comment by GaucovyAero** [comment]
> sir i am doing the latest version of pujv launcher

No, it's almost 2 years old, very old, I know what I'm saying.

**Comment by Sahilbone** [comment]
Sir i do that version which is on play store

**Comment by Sahilbone** [comment]
May I open again after crashing the game and send it back to you guys

**Comment by GaucovyAero** [comment]
> Sir i do that version which is on play store

that's old

**Comment by GaucovyAero** [comment]
download the new one from the link

**Comment by Sahilbone** [comment]
Sir but those people can also be wrong m sorry so talking but i m us play store version worship launcher that old hai kya

**Comment by GaucovyAero** [comment]
> Sir but those people can also be wrong m sorry so talking but i m us play store version worship launcher that old hai kya

I'm a collaborator, I know what I'm talking about. I support the launcher and various other people to get stuff working. You can't get it working on the old launcher, and I know that.

**Comment by Sahilbone** [comment]
Ok bro I will use new launcher you give me ok

**Comment by GaucovyAero** [comment]
> Ok bro I will use new launcher you give me ok

okay, it should work perfecly.

**Comment by Sahilbone** [comment]
Sir app me new java 17

**Comment by Sahilbone** [comment]
Give me

**Comment by GaucovyAero** [comment]
> Sir app me new java 17

You don't need to do anything. Java 17 will automatically install itself when you start up 1.17.1.

**Comment by Sahilbone** [comment]
But this too closed sir game on going and my game is closed

**Comment by Sahilbone** [comment]
[Uploading latestlog.txt…]()

**Comment by Sahilbone** [comment]
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9575012/latestcrash.txt)

**Comment by GaucovyAero** [comment]
> Uploading latestlog.txt…

your latestlog.txt didn't upload accidentally, upload it again i guess xD

**Comment by Sahilbone** [comment]
What

**Comment by GaucovyAero** [comment]
> What

it just said "Uploading latestlog.txt" but didn't upload it

please upload latestlog.txt again

**Comment by Sahilbone** [comment]
Brother my still not working game closes when open 1.17.1

**Comment by Sahilbone** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9575067/latestlog.txt)

**Comment by GaucovyAero** [comment]
```
[12:07:59] [Server Pinger #2/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 45:b6:9b:e6:ab:94:36:e6
[12:08:08] [Render thread/WARN]: handleDisconnection() called twice
```
hmm, do you have any controllers connected or something? also, how much memory do you have allocated in pojav?

**Comment by Sahilbone** [comment]
1090 Mb

**Comment by Sahilbone** [comment]
What is mean by controller

**Comment by Sahilbone** [comment]
कस्टम नियंत्रण

**Comment by Sahilbone** [comment]
Custom control yes i have

**Comment by GaucovyAero** [comment]
> 1090 Mb

I think you're very close to getting it working, because Minecraft almost started up just fine. Try putting in 800 MB.

**Comment by GaucovyAero** [comment]
> What is mean by controller

like a gamepad, mouse or keyboard

**Comment by Sahilbone** [comment]
No

**Comment by GaucovyAero** [comment]
okay, cool, can you try 800MB?

**Comment by Sahilbone** [comment]
Ok I will try

**Comment by Sahilbone** [comment]
Brother thanks game is open but it seems lag

**Comment by Sahilbone** [comment]
😭I have never been so happy

**Comment by GaucovyAero** [comment]
> Brother thanks game is open but it seems lag

Okay, cool. I will create a 1.17.1 modpack for you that you can install into Pojav and it will give you more fps okay? If I don't forget, I will give you the link.

**Comment by Sahilbone** [comment]
Ok

**Comment by Sahilbone** [comment]
But my fabric doesn't work

**Comment by Sahilbone** [comment]
I have many problems 😭🥺

**Comment by GaucovyAero** [comment]
> But my fabric doesn't work

i will send you fabric and everything, just wait a little please.

**Comment by Sahilbone** [comment]
Hlo brother you are very late

**Comment by Sahilbone** [comment]
Your little wait is so big

**Comment by GaucovyAero** [comment]
> Your little wait is so big

i know, i'll send it in maybe 30 minutes or more

**Comment by Sahilbone** [comment]
Hlo bro Till when give ?

**Comment by GaucovyAero** [comment]
Okay, so, here's the modpack will all the settings and all files needed: 

**https://www.mediafire.com/file/dqs4ljcb7qr48zs/Simply+Optimized+2.0+-+Pojav+(release+1.17.1).zip/file**

**How to install it:**
1. Download it.
2. Open **ZArchiver**, go to `Downloads`
3. Click on `Simply Optimized 2.0 - Pojav (release 1.17.1).zip`
4. Press `Extract to ./<Archive name>/`
5. Click on `Simply Optimized 2.0 - Pojav (release 1.17.1)`
6. Click on `Simply Optimized 2.0 - Pojav (release 1.17.1)`
7. There should be a hidden folder named `.minecraft` **(If there is a folder named `.minecraft`, continue with step 8)**.
7.1. **If you don't see the `.minecraft` folder, make sure to enable hidden files**
7.2. To enable hidden files, press on the `3 dots` on the top right corner of your screen. ![image](https://user-images.githubusercontent.com/85581164/190427494-7d0158b5-fa1d-4a45-b43e-34d413475eff.png)
7.3. Click on `Settings`
7.4. Click on `File list`
7.5. Turn ON `Show hidden files`
8. Long press your finger on `.minecraft`
9. Press `Copy`
10. Go to your PojavLauncher folder
10.1. **Android `5`, `6`, `7`, `8`, `9`**: `/storage/emulated/0/Android/games/PojavLauncher`
10.2. **Android `10`, `11`, `12`, `13`**: `/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/`
11. Click the green `Paste` button at the bottom right of your screen. ![image](https://user-images.githubusercontent.com/85581164/190426132-3081c76d-f6e6-4ea5-9ef3-9b3981242980.png)

![image](https://user-images.githubusercontent.com/85581164/190425924-a05e4c3e-093b-4014-92cd-265538723f8d.png)
12. Click `Apply to all files`
13. Click `Replace` 
14. Turn on PojavLauncher and click `Play`!
![image](https://user-images.githubusercontent.com/85581164/190426928-7782f563-c5c1-4cd8-9891-e9e492ba5319.png)

**Comment by Sahilbone** [comment]
Thanks

**Comment by Sahilbone** [comment]
Fabric give too

**Comment by GaucovyAero** [comment]
> Fabric give too

wait, does it work or no?

**Comment by Sahilbone** [comment]
Where to put them in the folder of the twist?

**Comment by Sahilbone** [comment]
Mod folder

**Comment by Sahilbone** [comment]
Tell me

**Comment by GaucovyAero** [comment]
> Where to put them in the folder of the twist?

just write everything you want in hindi, thats better

**Comment by Sahilbone** [comment]
No sir

**Comment by Sahilbone** [comment]
My mistake

**Comment by Sahilbone** [comment]
First I will try wait

**Comment by GaucovyAero** [comment]
okay, try first

**Comment by Sahilbone** [comment]
Thanks its work my game is smooth

**Comment by GaucovyAero** [comment]
> Thanks its work my game is smooth

Okay, cool! I'm closing this ticket now.
