### ISSUE TITLE
关于jre相关问题及一些建议

### ISSUE THREAD

**Issue by hyplant** [PojavLauncherTeam/PojavLauncher#3560]
### Describe the bug

![Screenshot_20220915-213859_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/190419620-0c8017ce-d875-4503-9a8b-e3f33f258c3f.jpg)
最新构建成功的测试版中jre出现损坏且无法启动任何游戏。
希望该问题可以尽快修复。
 
 
 一些小建议：
在模组安装器中可以使用类似于游戏控制器，可发送自定义键码。
可以在模组安装器中移动和缩放窗口。
添加一个Java终端，可以使用类似于cd,java,javac,jshell等命令，以便更好的以自定义参数启动模组安装器甚至服务端。
为每个游戏profile选择一个默认控制器

### The log file and images/videos

![Screenshot_20220915-213859_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/190419620-0c8017ce-d875-4503-9a8b-e3f33f258c3f.jpg)

### Steps To Reproduce

```markdown
正常安装
```

### Expected Behavior

无

### Platform

```markdown
- Device model: 三星one ui
- CPU architecture: *
- Android version: 12
- PojavLauncher version: dahlia-52-275bd18e0- (9938801)
```

**Comment by GaucovyAero** [comment]
我目前正在使用谷歌翻译。您使用的版本是一个 PR（拉取请求），由一个人完成，目的是破坏 PojavLauncher 中的一些代码。我们已经删除了该 PR 并删除了操作链接。如果您现在尝试下载最新版本，一切都应该没问题。

![972012294085152828](https://user-images.githubusercontent.com/85581164/190429138-d83ba0df-9173-490e-ae85-210a4fdbf4c3.png)

**Comment by GaucovyAero** [comment]
Okay, since this issue has been resolved, I'm closing this.
