### ISSUE TITLE
[BUG] <blank Textures and low fps in 1.18.2Short description>

### ISSUE THREAD

**Issue by Broken09** [PojavLauncherTeam/PojavLauncher#3561]
### Describe the bug

When I start 1.18.2 I hav to use assests which lowers my fps and has black particles cannot see throught doors trapdoors and glass item held in hand is also bugged I cannot see his back. I got very less Fps than usual I get 100 in 1.19 and below 20 in 1.18.2

### The log file and images/videos

![IMG_20220916_093055](https://user-images.githubusercontent.com/110962225/190553969-f213e080-a386-4653-ab14-a6e5a2804ce9.jpg)
![IMG_20220916_093025](https://user-images.githubusercontent.com/110962225/190553975-d24ceb27-1a01-4f6d-b323-6efeb2c83c86.jpg)
![IMG_20220916_093006](https://user-images.githubusercontent.com/110962225/190553985-a4500ab1-9f13-4e3a-ac00-7f9e0eab48c6.jpg)

### Steps To Reproduce

```markdown
Start 1.18.2 and install assests and then it would reproduce
```

### Expected Behavior

I wanted it to giv me atleast 30 fps and all textures to be fixed

### Platform

```markdown
- Device model: Redmi Note 10 Pro Max
- CPU architecture: aarch 64
- Android version: 11
- PojavLauncher version: Playstore (latest)
```

### Anything else?

Nothing else

**Comment by GaucovyAero** [comment]
what renderer are you using?

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
