### ISSUE TITLE
[BUG] pojave crashes when I install optifine

### ISSUE THREAD

**Issue by Text1220** [PojavLauncherTeam/PojavLauncher#3562]
### Describe the bug

Pojave just crashes when I try to install optifine or fabric does not exit with a error code

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9588466/latestlog.txt)

### Steps To Reproduce

```markdown
1. open pojave launcher
2. Click install .jar then click on optifine 1.19
```

### Expected Behavior

I expect it to open the optifine install screen

### Platform

```markdown
- Device model: moto g stylus 5G
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: version dahlia-8-f527e8a14-v3_openjdk
```

**Comment by GaucovyAero** [comment]
```
process killed with signal 6 code 0xffffffff addr 0x28d70000630f
process killed with signal 6 code 0xffffffff addr 0x28d70000630f
```
Android killed your process. Try again I guess. What runtime are you using?

**Comment by Text1220** [comment]
Java 7

**Comment by GaucovyAero** [comment]
> Java 7

you have to use Java 8, otherwise it will not work.

**Comment by Text1220** [comment]
Just tried to use java 17 but it still didn't work should I try another version of java? (Update: now it exited with code 1)

**Comment by Theendermat766** [comment]
Same for me to

**Comment by GaucovyAero** [comment]
> Just tried to use java 17 but it still didn't work should I try another version of java? (Update: now it exited with code 1)

just open the installer with java 8, and if it doesnt work, send latestlog.txt

**Comment by Text1220** [comment]
> > Just tried to use java 17 but it still didn't work should I try another version of java? (Update: now it exited with code 1)
> 
> just open the installer with java 8, and if it doesnt work, send latestlog.txt

Where can I find java 8?

**Comment by GaucovyAero** [comment]
> > > Just tried to use java 17 but it still didn't work should I try another version of java? (Update: now it exited with code 1)
> > 
> > 
> > just open the installer with java 8, and if it doesnt work, send latestlog.txt
> 
> Where can I find java 8?

it should be called "Internal (Java 8)"

**Comment by Text1220** [comment]
Yeah I just tried it but it doesn't open the optifine screen it just crashes

**Comment by GaucovyAero** [comment]
> Yeah I just tried it but it doesn't open the optifine screen it just crashes

just send latestlog.txt already

**Comment by Text1220** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9598131/latestlog.txt)

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9598131/latestlog.txt)

android is killing your process, not sure what to do about that. do you have developer options enabled? how much ram are you allocating to pojav?

**Comment by Text1220** [comment]
Yes I have dev options on and I allocated 1G of ram

**Comment by GaucovyAero** [comment]
> Yes I have dev options on and I allocated 1G of ram

disable dev option and set ram allocation to 800MB

**Comment by Text1220** [comment]
Well it does the same thing I sent the latest
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9615816/latestlog.txt)

**Comment by GaucovyAero** [comment]
> Well it does the same thing I sent the latest [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9615816/latestlog.txt)

try using ZArchiver to open the optifine installer in the jar installer

**Comment by Text1220** [comment]
Yeah It didn't work

**Comment by GaucovyAero** [comment]
> Yeah It didn't work

iii may have an explanation, if you are reading this, make sure to NOT use Chrome or any Chromium-based web browser, because those corrupt JAR files. Chromium-based web browsers are: Brave, Chrome, Vivaldi, Opera, Edge, Bromite, etc.
- **Therefore make sure to USE Firefox for downloading JAR files.**

**Comment by GaucovyAero** [comment]
OKAY OKAY, fixed! The solution is to have "auto-rotate" for your screen turned ON when using Pojav and when selecting the files, etc. Closing issue.

**Comment by bad1ending** [comment]
hi, can you help me ?

**Comment by GitAhmad304** [comment]
Gaucovy's fix worked for me, but disable render regions as that crashes the game
