### ISSUE TITLE
My One demand sir[F-Req] <Short description>

### ISSUE THREAD

**Issue by Sahilbone** [PojavLauncherTeam/PojavLauncher#3563]
### Is this request related to a bug?

Andiord version 11 
Pojav launcher version lastest

### Describe the request.

Sir Sir Mera Aap Mera Liya Fabric with mods by making and giving the game smoother chala version 1.16.5

**Comment by Sahilbone** [comment]
Beacuse my 1.16.5 fabric was not open

**Comment by Sahilbone** [comment]
You will give a file Inside that file both Fabric and Mods for 1.16.5 lug fix

**Comment by mchnjt** [comment]
> giving the game smoother chala version 1.16.5

"Minecraft: Java Edition is a very badly optimized game."
      -QuestCraft devs

Like really, if you're struggling to get a stable 20-35+ Frames per Second on your (potato) phone, then please play older versions instead.
