### ISSUE TITLE
Fabric was not open 1.16.5[F-Req] <Short description>

### ISSUE THREAD

**Issue by Sahilbone** [PojavLauncherTeam/PojavLauncher#3564]
### Is this request related to a bug?

All things download but  show only black screen

### Describe the request.

Andiord 11
Version 1.16.5 and pojav launcher version lastest

**Comment by Sahilbone** [comment]
My fabric was not work

**Comment by mchnjt** [comment]
(#3565) Duplicate.

**Comment by Sahilbone** [comment]
Hlo

**Comment by Sahilbone** [comment]
Believe everything is right Dali fabric also opens but the blocker sees the screen only

**Comment by mchnjt** [comment]
Looks like "tp for fuck" makes Fabric show a "black screen"

**Comment by Sahilbone** [comment]
Yes

**Comment by mchnjt** [comment]
lmao what
