### ISSUE TITLE
Fabric was not work[F-Req] <Short description>

### ISSUE THREAD

**Issue by Sahilbone** [PojavLauncherTeam/PojavLauncher#3565]
### Is this request related to a bug?

1.16.5  use and my fabric was not Android version is 11

### Describe the request.

1.16.5  use and my fabric was not Android version is 11

### Anything else?

1.16.5  use and my fabric was not Android version is 11

**Comment by mchnjt** [comment]
where log
- We can't solve your problem without the logfile.

Also, please use the `Issue` template rather than the `Feature Request` template.

**Comment by Sahilbone** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9590943/latestlog.txt)

**Comment by Sahilbone** [comment]
Me open fabric so show only black screen

**Comment by mchnjt** [comment]
I don't see any sort of issue. Are you sure this is the right one?
![Screenshot_2022-09-17-12-52-25-03](https://user-images.githubusercontent.com/83752061/190841041-3591e70b-20bd-45b2-9a66-ce1c4779e43e.png)

**Comment by Sahilbone** [comment]
Yes sir

**Comment by Sahilbone** [comment]
All thing all right work but doest not open my fabric only show black screen

**Comment by mchnjt** [comment]
~~tp for fuck~~ Please do a second run to verify your report as we can't just ssh to your phone and get it ourselves.

**Comment by GaucovyAero** [comment]
@Sahilbone can you like write down your issue in hindi so that we can actually know what you mean?

**Comment by Sahilkumar568** [comment]
Suno bhaiya maine sab sahi se download Kiya aur fabric bhi laga diya par jab fabric open karta hu to black screen aati hai fir vo chalta hi nhi hai.

**Comment by Sahilkumar568** [comment]
Only black screen show

**Comment by GaucovyAero** [comment]
so only black screen, nothing even after 5 minutes?

**Comment by GaucovyAero** [comment]
hm?

**Comment by Sahilkumar568** [comment]
Nothing

**Comment by Sahilkumar568** [comment]
Only black screen

**Comment by Sahilkumar568** [comment]
I am sahilbone

**Comment by GaucovyAero** [comment]
> I am sahilbone

send latestlog.txt

**Comment by Sahilkumar568** [comment]
given above

**Comment by GaucovyAero** [comment]
> given above

but thats a 1.17.1 log of you playing multiplayer

**Comment by GaucovyAero** [comment]
send latestlog.txt with the 1.16.5 crash in it

**Comment by Sahilkumar568** [comment]
Hai to 1.16.5 hua hi nhi open

**Comment by Sahilkumar568** [comment]
Tum bus yeh bataoo ki lag fix kasie karuuuu mai siirrrrrr

**Comment by GaucovyAero** [comment]
> Tum bus yeh bataoo ki lag fix kasie karuuuu mai siirrrrrr

send 1.16.5 latestlog

**Comment by Sahilkumar568** [comment]
Bro my game was not crash only show black screen no crash

**Comment by GaucovyAero** [comment]
> Bro my game was not crash only show black screen no crash

so your game did launch after that?

**Comment by Sahilkumar568** [comment]
no it is my problem

**Comment by GaucovyAero** [comment]
> no it is my problem

what does that mean

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
