### ISSUE TITLE
[BUG] Editing controls while on alpha 1.2.6 crashes my phone

### ISSUE THREAD

**Issue by Pinecone6442** [PojavLauncherTeam/PojavLauncher#3567]
### Describe the bug

I wanted to play alpha 1.2.6 when i was editing my controls, then it started lagging trying to find the escape key, it freezed, then restart, then my phone went extinct, now i cant use it.

### The log file and images/videos

I cant because it was just frozen

### Steps To Reproduce

```markdown
1. start pojav
2. play alpha 1.2.6
3. load world
4. edit controls
5. it starts to freeze
```

### Expected Behavior

I expect it to work normally

### Platform

```markdown
- Device model: Samsung A12 phone
- CPU architecture: I cant check cause its on the black screen on death
- Android version: 11
- PojavLauncher version: newest
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
If you're still getting the black screen on startup, send latestlog.txt. Also, how much RAM are you allocating to Minecraft?

**Comment by Pinecone6442** [comment]
> If you're still getting the black screen on startup, send latestlog.txt. Also, how much RAM are you allocating to Minecraft?

I cant cause my phone is ruined, but i allocated 1GB of ram out of 2GB, also the black screen is my phone trying to restart, i mainly play pojav on my tablet though

**Comment by GaucovyAero** [comment]
> > If you're still getting the black screen on startup, send latestlog.txt. Also, how much RAM are you allocating to Minecraft?
> 
> I cant cause my phone is ruined, but i allocated 1GB of ram out of 2GB, also the black screen is my phone trying to restart, i mainly play pojav on my tablet though

okay, so if I understand this correctly, pojav made your phone blackscreen totally and it's not usable now?

**Comment by GaucovyAero** [comment]
because thing is, changing controls and everything is working totally fine on a1.2.6 on my S7 Edge, so no idea what's up with your A12.

**Comment by Pinecone6442** [comment]
> > > If you're still getting the black screen on startup, send latestlog.txt. Also, how much RAM are you allocating to Minecraft?
> > 
> > 
> > I cant cause my phone is ruined, but i allocated 1GB of ram out of 2GB, also the black screen is my phone trying to restart, i mainly play pojav on my tablet though
> 
> okay, so if I understand this correctly, pojav made your phone blackscreen totally and it's not usable now?

Yes, my phone was kinda low on storage too, if i did lose all my storage, it should've just cleared, but now its gone. i didnt need it much anyways.,.

**Comment by GaucovyAero** [comment]
okay so is the A12 working, or is it not?

**Comment by Pinecone6442** [comment]
Nope, its not starting up

**Comment by GaucovyAero** [comment]
how is that even possible, i presume your battery died because of the heat

**Comment by GaucovyAero** [comment]
never seen a device dead because of pojav, but well, first time i guess

**Comment by mchnjt** [comment]
> I cant cause my phone is ruined

@PingPong Gang guys how do I logcat my broken phone-

**Comment by Pinecone6442** [comment]
it wasnt hot, its battery was at 22 and charging, so it cant drain fast, i wont risk the same for my tablet

**Comment by Pinecone6442** [comment]
my phone was only 9 months old, i should just get a better phone :|

**Comment by mchnjt** [comment]
okay, give us a brief description of what actually happened

**Comment by GaucovyAero** [comment]
> it wasnt hot, its battery was at 22 and charging, so it cant drain fast, i wont risk the same for my tablet

well i guess dont risk it, but still, never happened to anyone else, and, my phone is literally at 85°C CPU and 45°C battery while playing pojav and still hasn't died

**Comment by Pinecone6442** [comment]
my phone reloaded finally also my gpu is power vr

**Comment by GaucovyAero** [comment]
> my phone reloaded finally also my gpu is power vr

wait what, did the A12 literally start up rn

**Comment by mchnjt** [comment]
> my phone reloaded 

im confused, you said the phone is unusable
what actually happened

**Comment by GaucovyAero** [comment]
guys this is so sad insert `hyperrofel`

**Comment by mchnjt** [comment]
<:HYPERROFEL:862691562814570518>

**Comment by NotAHero04** [comment]
> Yes, my phone was kinda low on storage too, if i did lose all my storage, it should've just cleared, but now its gone. i didnt need it much anyways.,.

You shouldn't let your storage be low like that. It could cause real problems on any phone, from slowdowns to even boot failure.

**Comment by GaucovyAero** [comment]
![image](https://user-images.githubusercontent.com/85581164/190914418-0103e5b5-4e2e-4c30-9d9a-e3c6da1a47ad.png)

this is my epik storagus, i think am fine

**Comment by InfiniXDerg** [comment]
> my phone reloaded finally also my gpu is power vr

lol

**Comment by GaucovyAero** [comment]
Stale issue. Closing.
