### ISSUE TITLE
{BUG} Texture Pack

### ISSUE THREAD

**Issue by BeastyCoke** [PojavLauncherTeam/PojavLauncher#3568]
### Describe the bug

so i cant really find the texture pack folder in the zaarchiver app and idk what to do i also have no access to the discord server in pojavlauncher

### The log file and images/videos

![image](https://user-images.githubusercontent.com/105903249/191028087-7492a2ed-f2a7-4cdc-830d-33c41034fc8d.png)

### Steps To Reproduce

```markdown
1.start zaarchiver go to android>data>net.kdt.pojavlaunch>files
```

### Expected Behavior

I expect the resource pack folder to be there

### Platform

```markdown
- Device model: Acer chromebook
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Lastest
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
you didn't enable hidden files, files and folders starting with a dot are always hidden in Linux.

**Comment by BeastyCoke** [comment]
also how do i download optifine on chromebook i tried doing internal 8 but it keep crashing

**Comment by GaucovyAero** [comment]
send latestlog.txt with java 8

**Comment by BeastyCoke** [comment]
[](url)

**Comment by BeastyCoke** [comment]
[](url)
here

**Comment by BeastyCoke** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9642937/latestlog.txt)
here

**Comment by GaucovyAero** [comment]
```
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
```
You have a PojavLauncher build with broken Java 8. Reinstall Pojav and make sure to let it extract Java on first launch, otherwise it will crash like this.

**Comment by GaucovyAero** [comment]
stale issue. closing
