### ISSUE TITLE
[BUG] Render Bug

### ISSUE THREAD

**Issue by MMT007** [PojavLauncherTeam/PojavLauncher#3569]
### Describe the bug

for some reason when i go to play with the modpack i made it kinda looks that the blocks are inside out.. i sont know what mod ia causing it tho...

### The log file and images/videos

![Screenshot_20220920-144453](https://user-images.githubusercontent.com/67060689/191328562-88bdd70c-b189-4a93-bdcc-d9da5c2f3a64.png)

Mod List:

- BackPacked
- BetterAnimalPlus
- Blood Particles
- Carpenter's Blocks
- Corpse
- Doggy Talents
- Dynamic Surroundings
- Dynamic Trees
- Ex Nihilo Creatio
- Familiar Fauna
- FirstAid
- MrC Furniture mod
- MrC Gun mod
- MrC Vehicle Mod
- Iron Chest
- Jei
- LostCities 
- MobAmputation
- MobBlacklister
- Mo' Bends
- Mob Sunscreen
- More Furnaces
- Pam HaverstCraft
- Tektopia
- Xaeros Minimap

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Join A World
```

### Expected Behavior

Well.. what should haopen ia that the game goes as normal

### Platform

```markdown
- Device model: Moto E7 plus/64G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
press f11 till it fixes itself

**Comment by GaucovyAero** [comment]
stale issue. closing
