### ISSUE TITLE
1.17.1 FABRIC LAGG

### ISSUE THREAD

**Issue by Sahilkumar568** [PojavLauncherTeam/PojavLauncher#3574]
### Is this request related to a bug?

My GAME IS SO LAGGGY WITH 1.17.1 FABRIC MY MODS IS OFTIFABRIC AND STARLIGHT 

### Describe the request.

My GAME IS SO LAGGGY WITH 1.17.1 FABRIC MY MODS IS OFTIFABRIC AND STARLIGHT And CRASHED

### Anything else?

My GAME IS SO LAGGGY WITH 1.17.1 FABRIC MY MODS IS OFTIFABRIC AND STARLIGHT

**Comment by mchnjt** [comment]
We currently cannot do anything about that lag you're experiencing.
Try:

- Increasing the RAM allocation,
- or just play older versions.

If either does not help, you cannot do anything more but to either:
- "ROOT" and "flash" a custom ROM,
- or buy a device with a better chipset.

**Comment by GaucovyAero** [comment]
> We currently cannot do anything about that lag you're experiencing. Try:
> 
>     * Increasing the RAM allocation,
> 
>     * or just play older versions.
> 
> 
> If either does not help, you cannot do anything more but to either:
> 
>     * "ROOT" and "flash" a custom ROM,
> 
>     * or buy a device with a better chipset.

he dont understand

**Comment by GaucovyAero** [comment]
stale
