### ISSUE TITLE
[BUG] PojavLauncher suddenly crashing when joining worlds after removing shaders

### ISSUE THREAD

**Issue by Pinecone6442** [PojavLauncherTeam/PojavLauncher#3575]
### Describe the bug

pls fix it i dont want to use fucking shaders anymore

### The log file and images/videos

no

### Steps To Reproduce

```markdown
1. start pojav
2. load world with forge and some mods
3. crash
```

### Expected Behavior

i expect it to load

### Platform

```markdown
- Device model: Samsung A7 Lite
- CPU architecture: ?
- Android version: 12
- PojavLauncher version: newest
```

### Anything else?

no just fix it 😪

**Comment by Pinecone6442** [comment]
[2022-09-22-4.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/9621276/2022-09-22-4.log.gz)

**Comment by miggythewriter** [comment]
> [2022-09-22-4.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/9621276/2022-09-22-4.log.gz)

Don't use shaders if you don't have a snapdragon 8xx

**Comment by GaucovyAero** [comment]
I guess this is fixed. Closing.
