### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by KortySK** [PojavLauncherTeam/PojavLauncher#358]
When i start 1.16.1 i have gray screen and i do not know why. 
![Screenshot_20201016_173335_net kdt pojavlaunch](https://user-images.githubusercontent.com/57638778/96278409-c0add300-0fd5-11eb-9bb0-23edd23ba1a6.jpg)

**Comment by artdeell** [comment]
Checc `latestlog.txt`

пт, 16 окт. 2020 г., 18:34 KortySK <notifications@github.com>:

**Comment by KortySK** [comment]
Logs are empty.

**Comment by artdeell** [comment]
Weird. Absolutely empty?

пт, 16 окт. 2020 г., 20:06 KortySK <notifications@github.com>:

**Comment by KortySK** [comment]
Yes. Absolutely empty. And the games folder is now empty too
![Screenshot_20201016_200049_com huawei hidisk](https://user-images.githubusercontent.com/57638778/96292967-4cc9f580-0fea-11eb-8371-2718fce70439.jpg)

**Comment by WesleyVanNeck** [comment]
> Yes. Absolutely empty. And the games folder is now empty too
> ![Screenshot_20201016_200049_com huawei hidisk](https://user-images.githubusercontent.com/57638778/96292967-4cc9f580-0fea-11eb-8371-2718fce70439.jpg)

anable hiden folders

**Comment by KortySK** [comment]
I have. The folder was not empty but when i closed Pojav Launcher it deleted all from the games folder

**Comment by KortySK** [comment]
So I reinstalled launcher and i have my folder back with logs. So this is the log:
--------- beggining with launcher debug
Info: LWJGL3 directory: [ClassWrapper.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms768m -Xmx800m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
--------- beginning of system
--------- beginning of main
S/LaunchJVM(24478): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so success
S/LaunchJVM(24478): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so success
S/LaunchJVM(24478): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so success
S/LaunchJVM(24478): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so success
S/LaunchJVM(24478): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so success
S/LaunchJVM(24478): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so success
S/LaunchJVM(24478): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so success
S/LaunchJVM(24478): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so success
S/LaunchJVM(24478): dlopen /data/app/net.kdt.pojavlaunch-PVdzlKAPzHfelby4-JBVKQ==/lib/arm64/libopenal.so success
S/LaunchJVM(24478): dlopen /data/app/net.kdt.pojavlaunch-PVdzlKAPzHfelby4-JBVKQ==/lib/arm64/libgl04es.so success
S/LaunchJVM(24478): Done processing args
S/LaunchJVM(24478): Found JLI lib
S/LaunchJVM(24478): Calling JLI_Launch

**Comment by artdeell** [comment]
It seems that you didn't follow Testing v3 guide from GitHub wiki of Pojav

пт, 16 окт. 2020 г., 21:30 KortySK <notifications@github.com>:

**Comment by KortySK** [comment]
If you think this, i did. 
![Screenshot_20201017_085018_com android chrome](https://user-images.githubusercontent.com/57638778/96330504-fabeb980-1055-11eb-80b3-e398f08b6baa.jpg)
So what can i do?

**Comment by artdeell** [comment]
In your log it shows that you did not installed LWJGL3

сб, 17 окт. 2020 г., 09:52 KortySK <notifications@github.com>:

**Comment by KortySK** [comment]
Oh sorry when i reinstalled the Launcher i forgot to extract lwjgl3. But now i did it and nothing happend. Screen is still gray and if i want to wait after 3,4 minutes it crashes.
This is the latest log after extract
--------- beggining with launcher debug
Info: LWJGL3 directory: [ClassWrapper.jar, lwjgl3-lwjgl2bridge]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms768m -Xmx800m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
--------- beginning of crash
--------- beginning of system
--------- beginning of main
S/LaunchJVM(18530): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so success
S/LaunchJVM(18530): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so success
S/LaunchJVM(18530): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so success
S/LaunchJVM(18530): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so success
S/LaunchJVM(18530): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so success
S/LaunchJVM(18530): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so success
S/LaunchJVM(18530): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so success
S/LaunchJVM(18530): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so success
S/LaunchJVM(18530): dlopen /data/app/net.kdt.pojavlaunch-PVdzlKAPzHfelby4-JBVKQ==/lib/arm64/libopenal.so success
S/LaunchJVM(18530): dlopen /data/app/net.kdt.pojavlaunch-PVdzlKAPzHfelby4-JBVKQ==/lib/arm64/libgl04es.so success
S/LaunchJVM(18530): Done processing args
S/LaunchJVM(18530): Found JLI lib
S/LaunchJVM(18530): Calling JLI_Launch

And this is the crash report:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 10/17/20, 6:54 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dmb.<init>(SourceFile:143)
	at dlx.<init>(SourceFile:428)
	at net.minecraft.client.main.Main.main(SourceFile:177)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFW
	at dgn.<clinit>(SourceFile:46)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFW
	at dgn.<clinit>(SourceFile:41)
	... 3 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFW
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dmb.<init>(SourceFile:143)
	at dlx.<init>(SourceFile:428)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (aarch64) version 10
	Java Version: 9-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 589683008 bytes (562 MB) / 838860800 bytes (800 MB) up to 838860800 bytes (800 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xms768m -Xmx800m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.1
	Backend library: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	Backend API: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	GL Caps: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI

**Comment by khanhduytran0** [comment]
Do not put folder inside lwjgl3 folder.

**Comment by khanhduytran0** [comment]
Put .jar inside them to lwjgl3 folder, where ClassWrapper.jar on.

**Comment by KortySK** [comment]
I did not see this folder. Now it is not crashing and the gray screen disapear after 5 minutes. Thank you

**Comment by artdeell** [comment]
You didn't extracted it as wiki states. You should not create the new
folder inside the LWJGL3 folder

сб, 17 окт. 2020 г., 09:58 KortySK <notifications@github.com>:

**Comment by OfkoloBai** [comment]
``data
