### ISSUE TITLE
I don't see my realms world.

### ISSUE THREAD

**Issue by Ecossais09** [PojavLauncherTeam/PojavLauncher#3580]
### Describe the bug

When I enter realms on main screen I don't see any Realms world, app says that I have to buy one, but I already did that, and world is active. 
Any tips how to open realms on 1.19.2 version?

### The log file and images/videos

No photos needed

### Steps To Reproduce

```markdown
1. Login to migrated microsoft account.
2. Load minecraft 1.19.2 version and try to open realms.
```

### Expected Behavior

I expect to se my realms subscription. 

### Platform

```markdown
- Device model: Ipad Air 4
- CPU architecture: 
- Android version: IOS 15
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
Yeah, realms don't work. We have not implemented that yet.

**Comment by Mathias-Boulay** [comment]
it only works with the official minecraft launcher.
Cannot be fixed until Mojang does something.
