### ISSUE TITLE
[BUG] Click = crash

### ISSUE THREAD

**Issue by holmat1** [PojavLauncherTeam/PojavLauncher#3582]
### Describe the bug

So, I downloaded minecraft 1.12.2, but whenever I try to click on something (ingame buttons, controls), the game crashes. Tried it on 1.8.9 and got the same result.
Using Iphone 7, ios 15.6.1. Used the altstore ipa version of pojav

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9641548/latestlog.txt)

### Steps To Reproduce

```markdown
Turn on 1.12.2 and click anywhere
```

### Expected Behavior

Load up the menu

### Platform

```markdown
- Device model: Iphone 7 
- Ios version: 15.6.1 
- PojavLauncher version: Ipa
```

**Comment by Aerolome** [comment]
nothing in the latestlog, try crashing the game again and sending log

**Comment by holmat1** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9641563/latestlog.txt)

**Comment by Aerolome** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9641563/latestlog.txt)

hmm, interesting, it looks like there is no crash, can you try lowering the memory allocation? or maybe try lowering ram allocation to the lowest :D

**Comment by holmat1** [comment]
I will sound dumb rn, but how do I do that? Can’t find it in the preferences.

**Comment by Aerolome** [comment]
> I will sound dumb rn, but how do I do that? Can’t find it in the preferences.

i have no idea how is it called, maybe ram slider or something? also, this issue is on the android repository btw

**Comment by holmat1** [comment]
Alright, tried changing the ram usage via the jvm arguments (couldn’t find the ram slider anywhere, guess its not on ios), tried rescaling and some other optimizations, but nothing worked. It’s still the same: boots up, but when you try clicking singleplayer/multiplayer or anything, it crashes.

**Comment by artdeell** [comment]
Wait, why did you make an issue about the iOS Pojav on the Android repository?

**Comment by holmat1** [comment]
Sorry, idk where to post it :/

**Comment by holmat1** [comment]
Alright, I have ABSOLUTELY no idea what is going on; I tried to reinstall the ipa from altstore, but when I checked, IT’S NOT THERE. I have no idea how that could happen

**Comment by Aerolome** [comment]
> Alright, I have ABSOLUTELY no idea what is going on; I tried to reinstall the ipa from altstore, but when I checked, IT’S NOT THERE. I have no idea how that could happen

the ram slider is there both on android and ios tho

**Comment by khanhduytran0** [comment]
@holmat1 the build you installed (https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/3ce2ee901c291afe5737e966eb33d7831135860a) is very outdated, when JIT wasn’t even available, so if you even got it to run, you’d suffer from having the game at 1fps. Please follow [this instruction](https://github.com/PojavLauncherTeam/PojavLauncher_iOS#without-jailbreak-sideload-as-ipa)
