### ISSUE TITLE
[BUG] Sodium 1.19.2 crashing on joining world

### ISSUE THREAD

**Issue by Zeyrox1090** [PojavLauncherTeam/PojavLauncher#3583]
### Describe the bug

It said Application/Game exited with code -1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9645377/latestlog.txt)

### Steps To Reproduce

```markdown
1 start game with sodium
2 I disabled fog occlusion and I can't find compact vertex so I can't disable it
3 join a world/server
4 crash
```

### Expected Behavior

I expect it to not crash I guess

### Platform

```markdown
- Device model: POCO X4 Pro 5G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Action (dahlia-63-
8fdfa6425-seperate_bridges
```

**Comment by GaucovyAero** [comment]
1. - pretty sure Colormatic and Ok Zoomer only work on Quilt, so keep that in mind.
2. - only sodium 0.1.0 works, which is only for 1.16.3 up to 1.16.5. For newer versions of Minecraft, use OptiFabric and Starlight.

**Comment by Zeyrox1090** [comment]
> 1. * pretty sure Colormatic and Ok Zoomer only work on Quilt, so keep that in mind.
> 2. * only sodium 0.1.0 works, which is only for 1.16.3 up to 1.16.5. For newer versions of Minecraft, use OptiFabric and Starlight.

thanks
