### ISSUE TITLE
[F-Req] Remapping menu for controller

### ISSUE THREAD

**Issue by WilfredND** [PojavLauncherTeam/PojavLauncher#3584]
### Is this request related to a bug?

No this version isn't related to a bug, it's just a over sight

### Describe the request.

It feels odd not having a controller remap menu on the launcher screen so if you can add one, that will be nice, also if this request already exists, please send me it.

### Anything else?

Please be quick with it.

**Comment by mchnjt** [comment]
@Mathias-Boulay

**Comment by GaucovyAero** [comment]
We won't be quick, because it's pretty hard to implement. If you want to remap it though, just use the controller remapping Magisk module for now.

**Comment by Mathias-Boulay** [comment]
Pretty sure that a duplicate worth closing

**Comment by GaucovyAero** [comment]
Duplicate request. Closing.
