### ISSUE TITLE
How to install Mod pack pojav launcher

### ISSUE THREAD

**Issue by Secure96t** [PojavLauncherTeam/PojavLauncher#3586]
### Describe the bug

How to install pojav launcher Mod pack. 
![Picsart_22-09-27_16-49-12-872](https://user-images.githubusercontent.com/113331700/192512110-172d2625-aa23-4bdf-bf05-60798a2a69cb.jpg)

### The log file and images/videos

How to install mode pack

### Steps To Reproduce

```markdown
Pojav launcher modpack
```

### Expected Behavior

Modpack install

### Platform

```markdown
- Device model: redmi not10s
- CPU architecture: 
- Android version:13 
- PojavLauncher version: crocus-299-f1bd70996-v3_openjdk
```

### Anything else?

Please provide Mod pack option in pojav launcher

**Comment by Redd56** [comment]
this would be very nice to have, may i add onto it an add mods button so we can also just add single mods, as copying things on android 13 to the data folder is no longer supported (at least on my pixel 6)

**Comment by GaucovyAero** [comment]
> this would be very nice to have, may i add onto it an add mods button so we can also just add single mods, as copying things on android 13 to the data folder is no longer supported (at least on my pixel 6)

yeah exactly

**Comment by Redd56** [comment]
I found a qorkaround good video today

**Comment by AverageFemale** [comment]
> I found a qorkaround good video today

May I ask what this workaround is?

**Comment by Redd56** [comment]
Its no longer needed as i realized that direct folders exist (saf) 
![Screenshot_20221002-202339](https://user-images.githubusercontent.com/12189828/194640111-2e240549-798d-438a-9df6-3854258053d1.png)
Down at the bottom

**Comment by Redd56** [comment]
Very helpfull

**Comment by GaucovyAero** [comment]
closing this as it is a duplicate
