### ISSUE TITLE
[BUG] <Cant join servers with account>

### ISSUE THREAD

**Issue by VoidVanisher** [PojavLauncherTeam/PojavLauncher#3588]
I fixed it and migrated

**Comment by GaucovyAero** [comment]
Mojang accounts are no longer supported anywhere. This would not work even on the official Minecraft Launcher im pretty sure.

**Comment by VoidVanisher** [comment]
> Mojang accounts are no longer supported anywhere. This would not work even on the official Minecraft Launcher im pretty sure.

Uuuh then how do you get a working account

**Comment by GaucovyAero** [comment]
> > Mojang accounts are no longer supported anywhere. This would not work even on the official Minecraft Launcher im pretty sure.
> 
> Uuuh then how do you get a working account

buy directly from https://minecraft.net/ for 29.99$.

**Comment by VoidVanisher** [comment]
> > > Mojang accounts are no longer supported anywhere. This would not work even on the official Minecraft Launcher im pretty sure.
> > 
> > 
> > Uuuh then how do you get a working account
> 
> buy directly from https://minecraft.net/ for 29.99$.

Ain't no way they raised the price by 10 dollars and made old monang accounts not work that would be so scummy

**Comment by mchnjt** [comment]
What's "scummy" about Mojang or Microsoft making Mojang accounts not work?

**Comment by khanhduytran0** [comment]
> > Uuuh then how do you get a working account
> 
> buy directly from https://minecraft.net/ for 29.99$.

~~Account migration: am I a joke to you?~~
Anyways, you must be the ownership of the account to migrate.

**Comment by VoidVanisher** [comment]
> > > Uuuh then how do you get a working account
> > 
> > 
> > buy directly from https://minecraft.net/ for 29.99$.
> 
> ~Account migration: am I a joke to you?~ Anyways, you must be the ownership of the account to migrate.

Sorry I didn't realize that you meant migrate I thought you were saying they made everyone had to buy a new account after already buying a mojang one

**Comment by GaucovyAero** [comment]
I guess it's fixed. Closing.
