### ISSUE TITLE
Can't load 1.18 fabric 

### ISSUE THREAD

**Issue by Asjddkskddjsj** [PojavLauncherTeam/PojavLauncher#3589]
### Describe the bug

Application/Game exited with code 1

### The log file and images/videos

https://user-images.githubusercontent.com/114859391/193450962-7154180b-8bee-459f-9c42-b2c9f48c4829.mp4

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Install fabric 1.18 0.13.3
3. Click on play 
4. It will crash in a few seconds
```

### Expected Behavior

I expect the game not to crash

### Platform

```markdown
- Device model: Vivo y91i
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: latest on playstore
```

### Anything else?

Please tell me solution and if u want latest log the here it is
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9692320/latestlog.txt)

**Comment by GaucovyAero** [comment]
```
java.io.IOException: error reading fabric-loader-0.13.3-1.18.jar
Caused by: java.util.zip.ZipException: zip file is empty
```
make sure you don't use ANY custom runtimes in the play store version, once you start 1.18 with java 0 selected, java 17 will automatically unpack and install. Also, you may be running into an issue with the fabric installer (make sure you download the JAR file only thru Firefox, Via or Brave Browser. Other browsers tend to corrupt JAR files).

**Comment by Asjddkskddjsj** [comment]
Completed
