### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThomasBotizan** [PojavLauncherTeam/PojavLauncher#359]
Minecraft not starting. 

**Platform:**
 - Device Model Huawei P40Lite
 - CPU architecture idk
 - Android Version 10

**Additional context*
Unable to convert library org.lwjgl:lwjgl:3.2.1
processing archive /storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/INDEX.LIST...
writing META-INF/INDEX.LIST; size 554...
processing META-INF/MANIFEST.MF...
processing META-INF/versions/...
writing META-INF/versions/; size 0...
processing META-INF/versions/10/...
writing META-INF/versions/10/; size 0...
processing META-INF/versions/10/org/...
writing META-INF/versions/10/org/; size 0...
processing META-INF/versions/10/org/lwjgl/...
writing META-INF/versions/10/org/lwjgl/; size 0...
processing META-INF/versions/10/org/lwjgl/system/...
writing META-INF/versions/10/org/lwjgl/system/; size 0...
processing META-INF/versions/10/org/lwjgl/system/MathUtil.class...

PARSE ERROR:
unsupported class file version 54.0
...while parsing META-INF/versions/10/org/lwjgl/system/MathUtil.class
1 error; aborting
Exiting with code 1

**Comment by KortySK** [comment]
Check this
https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Testing-v3

**Comment by LuNeTiStU96** [comment]
![Uploading Screenshot_20201016_231939_net.kdt.pojavlaunch.jpg…]()

**Comment by ThomasBotizan** [comment]
java.lang.RuntimeException: Architecture arm64/aarch64 is incompatible with Java Runtime arm.
	at net.kdt.pojavlaunch.MainActivity.checkJavaArchitecture(MainActivity.java:968)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:951)
	at net.kdt.pojavlaunch.MainActivity.access$2700(MainActivity.java:28)
	at net.kdt.pojavlaunch.MainActivity$13$1.run(MainActivity.java:717)
	at java.lang.Thread.run(Thread.java:929)

**Comment by ThomasBotizan** [comment]
Sorry I downloaded wrong runtime

**Comment by ThomasBotizan** [comment]
Now I have Gray screen

**Comment by khanhduytran0** [comment]
Now you neee wait, or check latestlog.txt

**Comment by khanhduytran0** [comment]
Now you need wait, or check latestlog.txt

**Comment by ThomasBotizan** [comment]
Problem resolved but is crashing every time I enter a server section

**Comment by ThomasBotizan** [comment]
Enter with 1.11.2 and problem is solved
