### ISSUE TITLE
Can't install fabric

### ISSUE THREAD

**Issue by Asjddkskddjsj** [PojavLauncherTeam/PojavLauncher#3590]
### Describe the bug

Application/Game exited with code 1

### The log file and images/videos

https://user-images.githubusercontent.com/114859391/193501808-ebe6e30f-aaab-437b-9dec-42933edff03f.mp4

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Click install.jar
3. Choose fabric installer 0.11.1
4. It will crash with code 1
```

### Expected Behavior

I expect the game not to crash so that i can download fabric

### Platform

```markdown
- Device model: vivo y91i
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: latest on playstore
```

### Anything else?

Please tell me the solution and here's the latest log
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9694655/latestlog.txt)

**Comment by GaucovyAero** [comment]
Try using [this developement build](https://github.com/PojavLauncherTeam/PojavLauncher/suites/7857967858/artifacts/332982258) instead.

**Comment by Gigachadgs** [comment]
Plz don't give me mail

**Comment by GaucovyAero** [comment]
dude its not me, its github

**Comment by Redd56** [comment]
mans really over here anoyed by githubs auto email settings that only he can change

**Comment by Asjddkskddjsj** [comment]
LeL

**Comment by Redd56** [comment]
Lol
