### ISSUE TITLE
Can't load faric 1.19.2

### ISSUE THREAD

**Issue by Asjddkskddjsj** [PojavLauncherTeam/PojavLauncher#3591]
### Describe the bug

Exited with code 1

### The log file and images/videos

https://user-images.githubusercontent.com/114859391/193744902-5b9dc09a-a022-49ba-a66d-a1eeffc4ee4a.mp4

### Steps To Reproduce

```markdown
1. Start pojav launcher 
2. Choose fabric 1.19.2 
3. Click play 
4. Crash
```

### Expected Behavior

I expect the game to launch 

### Platform

```markdown
- Device model: Vivo y91i
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: latest in playstore
```

### Anything else?

Please tell me the solution, an if u want latestlog the here it is 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9703114/latestlog.txt)

**Comment by Asjddkskddjsj** [comment]
Mods i have
1. Fabric api 
2. Optifabric+optifine
3. Wurst

**Comment by GaucovyAero** [comment]
```
java.lang.RuntimeException: Could not find game constructor in net.minecraft.client.main.Main!
	at net.fabricmc.loader.impl.game.minecraft.patch.EntrypointPatch.process(EntrypointPatch.java:144) ~[fabric-loader-0.13.3.jar:?]
```
you fabric minecraft jar or installation is broken

**Comment by Asjddkskddjsj** [comment]
What?
Can i fix this?

**Comment by GaucovyAero** [comment]
try reinstalling it

**Comment by GaucovyAero** [comment]
also make sure to use fabric loader 0.14.9

**Comment by Asjddkskddjsj** [comment]
Thx 😁👍👍 it worked
