### ISSUE TITLE
[BUG] forge 1.8.9 installation keeps crashing

### ISSUE THREAD

**Issue by DoubleShotgun** [PojavLauncherTeam/PojavLauncher#3592]
### Describe the bug

Read the title

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9722310/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install forge 1.8.9
```

### Expected Behavior

Forge installer launch

### Platform

```markdown
- Device model: cph1920
- CPU architecture: arm64
- Android version: 8.1
- PojavLauncher version: latest Google Play version
```

### Anything else?

I have tried almost and every pojav version including the latest build

**Comment by GaucovyAero** [comment]
dont use forge universal, use forge installer
