### ISSUE TITLE
Change the location where you want to save the game folder 

### ISSUE THREAD

**Issue by lehoanduphong** [PojavLauncherTeam/PojavLauncher#3595]
### Is this request related to a bug?

irrelevant 

### Describe the request.

I want pojavlaucher to be able to customize the location to save the game folder according to the location, another folder at will 

### Anything else?

No

**Comment by GaucovyAero** [comment]
you can already do this in the actions builds, but it's buggy for now. it will be fixed in the latest gplay release tho.
