### ISSUE TITLE
App was deleted from Google Play Store 

### ISSUE THREAD

**Issue by Ruijin1722** [PojavLauncherTeam/PojavLauncher#3596]
### Describe the bug

App was deleted from Google Play Store pls Help 

Alternate Download Link for APK !?

### The log file and images/videos

App was deleted from Google Play Store pls Help 

Alternate Download Link for APK !?

### Steps To Reproduce

```markdown
App was deleted from Google Play Store pls Help 

Alternate Download Link for APK !?
```

### Expected Behavior

App was deleted from Google Play Store pls Help 

Alternate Download Link for APK !?

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
App was deleted from Google Play Store pls Help 

Alternate Download Link for APK !?
```

### Anything else?

App was deleted from Google Play Store pls Help 

Alternate Download Link for APK !?

**Comment by mchnjt** [comment]
Please get PL from [actions builds](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for now.

**Comment by Ruijin1722** [comment]
> Please get PL from [actions builds](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for now.

But the latest Versions without Download Link for APK 

Pls send a Link

**Comment by mchnjt** [comment]
do you think github is mediafire?
you're in the source code repo, all the actions builds are updated.

**Comment by RedTechGamer236** [comment]
I have noticed PojavLauncher was deleted from the Play Store as well, but I'm not finding information about why that happened. Has the team gotten anything mentioning why this happened if this wasn't the team?

**Comment by mchnjt** [comment]
> I have noticed PojavLauncher was deleted from the Play Store as well, but I'm not finding information about why that happened. Has the team gotten anything mentioning why this happened if this wasn't the team?

https://youtu.be/gYJL4J-mwXo

**Comment by DaCassiel** [comment]
Maybe they deleted it because they thought you stole Minecraft, but it's just a launcher

**Comment by DaCassiel** [comment]
Maybe they deleted it because they thought you stole Minecraft, but it's just a launcher

**Comment by Gidbro208** [comment]
this video can help you to download pojavlauncher 
Link-[https://www.youtube.com/watch?v=Nki7TybXiOM](url)
