### ISSUE TITLE
Material becomes rough and low definition

### ISSUE THREAD

**Issue by SetFireUw** [PojavLauncherTeam/PojavLauncher#3597]
### Describe the bug

![Screenshot_2022-10-10-12-16-49-54](https://user-images.githubusercontent.com/111931630/194799188-7cf30a7e-9bd9-47a0-a4b7-e3f53dc7d5ed.png)

### The log file and images/videos

![Screenshot_2022-10-10-12-16-49-54](https://user-images.githubusercontent.com/111931630/194799212-6b2006dc-bf37-4b44-9723-306814c032d6.png)

### Steps To Reproduce

```markdown
No steps to reproduce
```

### Expected Behavior

I hope the problem of material or rendering can be solved

### Platform

```markdown
- Device model: oppo r9/64G
- CPU architecture: aarch64
- Android version: 6
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

No thanks, I hope it can be resolved soon

**Comment by GaucovyAero** [comment]
3.3.1.1 is super old, make sure to update to this actions build: https://github.com/PojavLauncherTeam/PojavLauncher/suites/7857967858/artifacts/332982258
