### ISSUE TITLE
[BUG] Crash with sodium in Minecraft 1.19.2

### ISSUE THREAD

**Issue by felixlechatchat** [PojavLauncherTeam/PojavLauncher#3598]
### Describe the bug

Hello , my game crash with sodium 1.19.2 !

### The log file and images/videos

[crash-2022-10-10_15.39.06-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9747300/crash-2022-10-10_15.39.06-client.txt)

### Steps To Reproduce

```markdown
I am n't dev ,sorry.
```

### Expected Behavior

I want to go server or maps with sodium for more fps but i don't.

### Platform

```markdown
- Device model: V2109
- CPU architecture: PD2147GF_EX_A_36.18.2
- Android version: 12
- PojavLauncher version: version dahlia-8-f527e8a14-v3_openjdk
```

**Comment by GaucovyAero** [comment]
sodium crashes on every phone and the only exception would be sodium 0.1.0 (for 1.16.3 up to 1.16.5), which with pojav compatibility settings is actually slower than optifine, so just use optifine or optifabric.

**Comment by felixlechatchat** [comment]
Ok, thanks for informations

**Comment by GaucovyAero** [comment]
yeah no problem. closing issue

**Comment by Selenar888** [comment]
okay
