### ISSUE TITLE
On my Xiaomi Mi A2 version Android 10, MC versions 1.8+ do not work. Error code is below

### ISSUE THREAD

**Issue by Tom1390** [PojavLauncherTeam/PojavLauncher#36]
Unable to convert library net.java.dev.jna:platform:3.4.0
processing archive /storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/MANIFEST.MF...
processing com/...
writing com/; size 0...
processing com/sun/...
writing com/sun/; size 0...
processing com/sun/jna/...
writing com/sun/jna/; size 0...
processing com/sun/jna/platform/...
writing com/sun/jna/platform/; size 0...
processing com/sun/jna/platform/FileMonitor.class...
processing com/sun/jna/platform/FileMonitor$FileEvent.class...
processing com/sun/jna/platform/FileMonitor$FileListener.class...
processing com/sun/jna/platform/FileMonitor$Holder.class...
processing com/sun/jna/platform/FileUtils.class...
processing com/sun/jna/platform/FileUtils$1.class...
processing com/sun/jna/platform/FileUtils$DefaultFileUtils.class...
processing com/sun/jna/platform/FileUtils$Holder.class...
processing com/sun/jna/platform/KeyboardUtils.class...
processing com/sun/jna/platform/KeyboardUtils$1.class...
processing com/sun/jna/platform/KeyboardUtils$MacKeyboardUtils.class...
processing com/sun/jna/platform/KeyboardUtils$NativeKeyboardUtils.class...
processing com/sun/jna/platform/KeyboardUtils$W32KeyboardUtils.class...
processing com/sun/jna/platform/KeyboardUtils$X11KeyboardUtils.class...
processing com/sun/jna/platform/RasterRangesUtils.class...
processing com/sun/jna/platform/RasterRangesUtils$1.class...
processing com/sun/jna/platform/RasterRangesUtils$RangesOutput.class...
processing com/sun/jna/platform/WindowUtils.class...
processing com/sun/jna/platform/WindowUtils$1.class...
processing com/sun/jna/platform/WindowUtils$HeavyweightForcer.class...
processing com/sun/jna/platform/WindowUtils$Holder.class...
processing com/sun/jna/platform/WindowUtils$MacWindowUtils.class...
processing com/sun/jna/platform/WindowUtils$MacWindowUtils$1.class...
processing com/sun/jna/platform/WindowUtils$MacWindowUtils$OSXMaskingContentPane.class...
processing com/sun/jna/platform/WindowUtils$NativeWindowUtils.class...
processing com/sun/jna/platform/WindowUtils$NativeWindowUtils$1.class...
processing com/sun/jna/platform/WindowUtils$NativeWindowUtils$2.class...
processing com/sun/jna/platform/WindowUtils$NativeWindowUtils$3.class...
processing com/sun/jna/platform/WindowUtils$NativeWindowUtils$TransparentContentPane.class...
processing com/sun/jna/platform/WindowUtils$RepaintTrigger.class...
processing com/sun/jna/platform/WindowUtils$RepaintTrigger$Listener.class...
processing com/sun/jna/platform/WindowUtils$W32WindowUtils.class...
processing com/sun/jna/platform/WindowUtils$W32WindowUtils$1.class...
processing com/sun/jna/platform/WindowUtils$W32WindowUtils$2.class...
processing com/sun/jna/platform/WindowUtils$W32WindowUtils$3.class...
processing com/sun/jna/platform/WindowUtils$W32WindowUtils$4.class...
processing com/sun/jna/platform/WindowUtils$W32WindowUtils$W32TransparentContentPane.class...
processing com/sun/jna/platform/WindowUtils$X11WindowUtils.class...
processing com/sun/jna/platform/WindowUtils$X11WindowUtils$1.class...
processing com/sun/jna/platform/WindowUtils$X11WindowUtils$2.class...
processing com/sun/jna/platform/WindowUtils$X11WindowUtils$3.class...
processing com/sun/jna/platform/WindowUtils$X11WindowUtils$4.class...
processing com/sun/jna/platform/WindowUtils$X11WindowUtils$5.class...
processing com/sun/jna/platform/WindowUtils$X11WindowUtils$PixmapSource.class...
processing com/sun/jna/platform/WindowUtils$X11WindowUtils$X11TransparentContentPane.class...
processing com/sun/jna/platform/dnd/...
writing com/sun/jna/platform/dnd/; size 0...
processing com/sun/jna/platform/dnd/DragHandler.class...
processing com/sun/jna/platform/dnd/DropHandler.class...
processing com/sun/jna/platform/dnd/DropTargetPainter.class...
processing com/sun/jna/platform/dnd/GhostedDragImage.class...
processing com/sun/jna/platform/dnd/GhostedDragImage$1.class...
processing com/sun/jna/platform/dnd/GhostedDragImage$2.class...
processing com/sun/jna/platform/dnd/GhostedDragImage$3.class...
processing com/sun/jna/platform/dnd/package.html...
writing com/sun/jna/platform/dnd/package.html; size 253...
processing com/sun/jna/platform/mac/...
writing com/sun/jna/platform/mac/; size 0...
processing com/sun/jna/platform/mac/Carbon.class...
processing com/sun/jna/platform/mac/Carbon$EventHandlerProcPtr.class...
processing com/sun/jna/platform/mac/Carbon$EventHotKeyID.class...
processing com/sun/jna/platform/mac/Carbon$EventHotKeyID$ByValue.class...
processing com/sun/jna/platform/mac/Carbon$EventTypeSpec.class...
processing com/sun/jna/platform/mac/MacFileUtils.class...
processing com/sun/jna/platform/mac/MacFileUtils$FileManager.class...
processing com/sun/jna/platform/mac/package.html...
writing com/sun/jna/platform/mac/package.html; size 192...
processing com/sun/jna/platform/package.html...
writing com/sun/jna/platform/package.html; size 208...
processing com/sun/jna/platform/unix/...
writing com/sun/jna/platform/unix/; size 0...
processing com/sun/jna/platform/unix/X11.class...
processing com/sun/jna/platform/unix/X11$Atom.class...
processing com/sun/jna/platform/unix/X11$AtomByReference.class...
processing com/sun/jna/platform/unix/X11$Colormap.class...
processing com/sun/jna/platform/unix/X11$Cursor.class...
processing com/sun/jna/platform/unix/X11$Display.class...
processing com/sun/jna/platform/unix/X11$Drawable.class...
processing com/sun/jna/platform/unix/X11$Font.class...
processing com/sun/jna/platform/unix/X11$GC.class...
processing com/sun/jna/platform/unix/X11$KeySym.class...
processing com/sun/jna/platform/unix/X11$Pixmap.class...
processing com/sun/jna/platform/unix/X11$Screen.class...
processing com/sun/jna/platform/unix/X11$Visual.class...
processing com/sun/jna/platform/unix/X11$VisualID.class...
processing com/sun/jna/platform/unix/X11$Window.class...
processing com/sun/jna/platform/unix/X11$WindowByReference.class...
processing com/sun/jna/platform/unix/X11$XAnyEvent.class...
processing com/sun/jna/platform/unix/X11$XButtonEvent.class...
processing com/sun/jna/platform/unix/X11$XButtonPressedEvent.class...
processing com/sun/jna/platform/unix/X11$XButtonReleasedEvent.class...
processing com/sun/jna/platform/unix/X11$XCirculateEvent.class...
processing com/sun/jna/platform/unix/X11$XCirculateRequestEvent.class...
processing com/sun/jna/platform/unix/X11$XClientMessageEvent.class...
processing com/sun/jna/platform/unix/X11$XClientMessageEvent$Data.class...
processing com/sun/jna/platform/unix/X11$XColormapEvent.class...
processing com/sun/jna/platform/unix/X11$XConfigureEvent.class...
processing com/sun/jna/platform/unix/X11$XConfigureRequestEvent.class...
processing com/sun/jna/platform/unix/X11$XCreateWindowEvent.class...
processing com/sun/jna/platform/unix/X11$XCrossingEvent.class...
processing com/sun/jna/platform/unix/X11$XDestroyWindowEvent.class...
processing com/sun/jna/platform/unix/X11$XDeviceByReference.class...
processing com/sun/jna/platform/unix/X11$XEnterWindowEvent.class...
processing com/sun/jna/platform/unix/X11$XErrorEvent.class...
processing com/sun/jna/platform/unix/X11$XErrorHandler.class...
processing com/sun/jna/platform/unix/X11$XEvent.class...
processing com/sun/jna/platform/unix/X11$XExposeEvent.class...
processing com/sun/jna/platform/unix/X11$XFocusChangeEvent.class...
processing com/sun/jna/platform/unix/X11$XFocusInEvent.class...
processing com/sun/jna/platform/unix/X11$XFocusOutEvent.class...
processing com/sun/jna/platform/unix/X11$XGCValues.class...
processing com/sun/jna/platform/unix/X11$XGraphicsExposeEvent.class...
processing com/sun/jna/platform/unix/X11$XGravityEvent.class...
processing com/sun/jna/platform/unix/X11$XID.class...
processing com/sun/jna/platform/unix/X11$XImage.class...
processing com/sun/jna/platform/unix/X11$XInputClassInfoByReference.class...
processing com/sun/jna/platform/unix/X11$XKeyEvent.class...
processing com/sun/jna/platform/unix/X11$XKeyboardControlRef.class...
processing com/sun/jna/platform/unix/X11$XKeyboardStateRef.class...
processing com/sun/jna/platform/unix/X11$XKeymapEvent.class...
processing com/sun/jna/platform/unix/X11$XLeaveWindowEvent.class...
processing com/sun/jna/platform/unix/X11$XMapEvent.class...
processing com/sun/jna/platform/unix/X11$XMapRequestEvent.class...
processing com/sun/jna/platform/unix/X11$XMappingEvent.class...
processing com/sun/jna/platform/unix/X11$XModifierKeymapRef.class...
processing com/sun/jna/platform/unix/X11$XMotionEvent.class...
processing com/sun/jna/platform/unix/X11$XNoExposeEvent.class...
processing com/sun/jna/platform/unix/X11$XPoint.class...
processing com/sun/jna/platform/unix/X11$XPointerMovedEvent.class...
processing com/sun/jna/platform/unix/X11$XPropertyEvent.class...
processing com/sun/jna/platform/unix/X11$XRectangle.class...
processing com/sun/jna/platform/unix/X11$XReparentEvent.class...
processing com/sun/jna/platform/unix/X11$XResizeRequestEvent.class...
processing com/sun/jna/platform/unix/X11$XSelectionClearEvent.class...
processing com/sun/jna/platform/unix/X11$XSelectionEvent.class...
processing com/sun/jna/platform/unix/X11$XSelectionRequestEvent.class...
processing com/sun/jna/platform/unix/X11$XSetWindowAttributes.class...
processing com/sun/jna/platform/unix/X11$XSizeHints.class...
processing com/sun/jna/platform/unix/X11$XSizeHints$Aspect.class...
processing com/sun/jna/platform/unix/X11$XTest.class...
processing com/sun/jna/platform/unix/X11$XTextProperty.class...
processing com/sun/jna/platform/unix/X11$XUnmapEvent.class...
processing com/sun/jna/platform/unix/X11$XVisibilityEvent.class...
processing com/sun/jna/platform/unix/X11$XVisualInfo.class...
processing com/sun/jna/platform/unix/X11$XWMHints.class...
processing com/sun/jna/platform/unix/X11$XWindowAttributes.class...
processing com/sun/jna/platform/unix/X11$Xevie.class...
processing com/sun/jna/platform/unix/X11$Xext.class...
processing com/sun/jna/platform/unix/X11$Xrender.class...
processing com/sun/jna/platform/unix/X11$Xrender$PictFormat.class...
processing com/sun/jna/platform/unix/X11$Xrender$XRenderDirectFormat.class...
processing com/sun/jna/platform/unix/X11$Xrender$XRenderPictFormat.class...
processing com/sun/jna/platform/unix/package.html...
writing com/sun/jna/platform/unix/package.html; size 203...
processing com/sun/jna/platform/win32/...
writing com/sun/jna/platform/win32/; size 0...
processing com/sun/jna/platform/win32/Advapi32.class...
processing com/sun/jna/platform/win32/Advapi32Util.class...
processing com/sun/jna/platform/win32/Advapi32Util$Account.class...
processing com/sun/jna/platform/win32/Advapi32Util$EventLogIterator.class...
processing com/sun/jna/platform/win32/Advapi32Util$EventLogRecord.class...
processing com/sun/jna/platform/win32/Advapi32Util$EventLogType.class...
processing com/sun/jna/platform/win32/BaseTSD.class...
processing com/sun/jna/platform/win32/BaseTSD$DWORD_PTR.class...
processing com/sun/jna/platform/win32/BaseTSD$LONG_PTR.class...
processing com/sun/jna/platform/win32/BaseTSD$SIZE_T.class...
processing com/sun/jna/platform/win32/BaseTSD$SSIZE_T.class...
processing com/sun/jna/platform/win32/BaseTSD$ULONG_PTR.class...
processing com/sun/jna/platform/win32/BaseTSD$ULONG_PTRByReference.class...
processing com/sun/jna/platform/win32/Crypt32.class...
processing com/sun/jna/platform/win32/Crypt32Util.class...
processing com/sun/jna/platform/win32/DsGetDC.class...
processing com/sun/jna/platform/win32/DsGetDC$DOMAIN_CONTROLLER_INFO.class...
processing com/sun/jna/platform/win32/DsGetDC$DOMAIN_CONTROLLER_INFO$ByReference.class...
processing com/sun/jna/platform/win32/DsGetDC$DS_DOMAIN_TRUSTS.class...
processing com/sun/jna/platform/win32/DsGetDC$DS_DOMAIN_TRUSTS$ByReference.class...
processing com/sun/jna/platform/win32/DsGetDC$PDOMAIN_CONTROLLER_INFO.class...
processing com/sun/jna/platform/win32/DsGetDC$PDOMAIN_CONTROLLER_INFO$ByReference.class...
processing com/sun/jna/platform/win32/DsGetDC$PDS_DOMAIN_TRUSTS.class...
processing com/sun/jna/platform/win32/DsGetDC$PDS_DOMAIN_TRUSTS$ByReference.class...
processing com/sun/jna/platform/win32/GDI32.class...
processing com/sun/jna/platform/win32/Guid.class...
processing com/sun/jna/platform/win32/Guid$GUID.class...
processing com/sun/jna/platform/win32/Guid$GUID$ByReference.class...
processing com/sun/jna/platform/win32/Kernel32.class...
processing com/sun/jna/platform/win32/Kernel32Util.class...
processing com/sun/jna/platform/win32/LMAccess.class...
processing com/sun/jna/platform/win32/LMAccess$GROUP_INFO_0.class...
processing com/sun/jna/platform/win32/LMAccess$GROUP_INFO_1.class...
processing com/sun/jna/platform/win32/LMAccess$GROUP_INFO_2.class...
processing com/sun/jna/platform/win32/LMAccess$GROUP_INFO_3.class...
processing com/sun/jna/platform/win32/LMAccess$GROUP_USERS_INFO_0.class...
processing com/sun/jna/platform/win32/LMAccess$LOCALGROUP_INFO_0.class...
processing com/sun/jna/platform/win32/LMAccess$LOCALGROUP_INFO_1.class...
processing com/sun/jna/platform/win32/LMAccess$LOCALGROUP_USERS_INFO_0.class...
processing com/sun/jna/platform/win32/LMAccess$USER_INFO_0.class...
processing com/sun/jna/platform/win32/LMAccess$USER_INFO_1.class...
processing com/sun/jna/platform/win32/LMAccess$USER_INFO_23.class...
processing com/sun/jna/platform/win32/LMCons.class...
processing com/sun/jna/platform/win32/LMErr.class...
processing com/sun/jna/platform/win32/LMJoin.class...
processing com/sun/jna/platform/win32/LMJoin$NETSETUP_JOIN_STATUS.class...
processing com/sun/jna/platform/win32/Msi.class...
processing com/sun/jna/platform/win32/NTSecApi.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_FOREST_TRUST_BINARY_DATA.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_FOREST_TRUST_DOMAIN_INFO.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_FOREST_TRUST_INFORMATION.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_FOREST_TRUST_INFORMATION$ByReference.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_FOREST_TRUST_RECORD.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_FOREST_TRUST_RECORD$ByReference.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_FOREST_TRUST_RECORD$UNION.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_FOREST_TRUST_RECORD$UNION$ByReference.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_UNICODE_STRING.class...
processing com/sun/jna/platform/win32/NTSecApi$LSA_UNICODE_STRING$ByReference.class...
processing com/sun/jna/platform/win32/NTSecApi$PLSA_FOREST_TRUST_INFORMATION.class...
processing com/sun/jna/platform/win32/NTSecApi$PLSA_FOREST_TRUST_INFORMATION$ByReference.class...
processing com/sun/jna/platform/win32/NTSecApi$PLSA_FOREST_TRUST_RECORD.class...
processing com/sun/jna/platform/win32/NTSecApi$PLSA_FOREST_TRUST_RECORD$ByReference.class...
processing com/sun/jna/platform/win32/NTSecApi$PLSA_UNICODE_STRING.class...
processing com/sun/jna/platform/win32/NTSecApi$PLSA_UNICODE_STRING$ByReference.class...
processing com/sun/jna/platform/win32/NTStatus.class...
processing com/sun/jna/platform/win32/Netapi32.class...
processing com/sun/jna/platform/win32/Netapi32Util.class...
processing com/sun/jna/platform/win32/Netapi32Util$DomainController.class...
processing com/sun/jna/platform/win32/Netapi32Util$DomainTrust.class...
processing com/sun/jna/platform/win32/Netapi32Util$Group.class...
processing com/sun/jna/platform/win32/Netapi32Util$LocalGroup.class...
processing com/sun/jna/platform/win32/Netapi32Util$User.class...
processing com/sun/jna/platform/win32/Netapi32Util$UserInfo.class...
processing com/sun/jna/platform/win32/NtDll.class...
processing com/sun/jna/platform/win32/NtDllUtil.class...
processing com/sun/jna/platform/win32/ObjBase.class...
processing com/sun/jna/platform/win32/Ole32.class...
processing com/sun/jna/platform/win32/Ole32Util.class...
processing com/sun/jna/platform/win32/Oleaut32.class...
processing com/sun/jna/platform/win32/Secur32.class...
processing com/sun/jna/platform/win32/Secur32$EXTENDED_NAME_FORMAT.class...
processing com/sun/jna/platform/win32/Secur32Util.class...
processing com/sun/jna/platform/win32/Secur32Util$SecurityPackage.class...
processing com/sun/jna/platform/win32/SetupApi.class...
processing com/sun/jna/platform/win32/SetupApi$SP_DEVICE_INTERFACE_DATA.class...
processing com/sun/jna/platform/win32/SetupApi$SP_DEVICE_INTERFACE_DATA$ByReference.class...
processing com/sun/jna/platform/win32/SetupApi$SP_DEVINFO_DATA.class...
processing com/sun/jna/platform/win32/SetupApi$SP_DEVINFO_DATA$ByReference.class...
processing com/sun/jna/platform/win32/Shell32.class...
processing com/sun/jna/platform/win32/Shell32Util.class...
processing com/sun/jna/platform/win32/ShellAPI.class...
processing com/sun/jna/platform/win32/ShellAPI$SHFILEOPSTRUCT.class...
processing com/sun/jna/platform/win32/ShlObj.class...
processing com/sun/jna/platform/win32/Sspi.class...
processing com/sun/jna/platform/win32/Sspi$CredHandle.class...
processing com/sun/jna/platform/win32/Sspi$CtxtHandle.class...
processing com/sun/jna/platform/win32/Sspi$PSecHandle.class...
processing com/sun/jna/platform/win32/Sspi$PSecHandle$ByReference.class...
processing com/sun/jna/platform/win32/Sspi$PSecPkgInfo.class...
processing com/sun/jna/platform/win32/Sspi$PSecPkgInfo$ByReference.class...
processing com/sun/jna/platform/win32/Sspi$SECURITY_INTEGER.class...
processing com/sun/jna/platform/win32/Sspi$SecBuffer.class...
processing com/sun/jna/platform/win32/Sspi$SecBuffer$ByReference.class...
processing com/sun/jna/platform/win32/Sspi$SecBufferDesc.class...
processing com/sun/jna/platform/win32/Sspi$SecHandle.class...
processing com/sun/jna/platform/win32/Sspi$SecHandle$ByReference.class...
processing com/sun/jna/platform/win32/Sspi$SecPkgInfo.class...
processing com/sun/jna/platform/win32/Sspi$SecPkgInfo$ByReference.class...
processing com/sun/jna/platform/win32/Sspi$TimeStamp.class...
processing com/sun/jna/platform/win32/Tlhelp32.class...
processing com/sun/jna/platform/win32/Tlhelp32$PROCESSENTRY32.class...
processing com/sun/jna/platform/win32/Tlhelp32$PROCESSENTRY32$ByReference.class...
processing com/sun/jna/platform/win32/User32.class...
processing com/sun/jna/platform/win32/VerRsrc.class...
processing com/sun/jna/platform/win32/VerRsrc$VS_FIXEDFILEINFO.class...
processing com/sun/jna/platform/win32/VerRsrc$VS_FIXEDFILEINFO$ByReference.class...
processing com/sun/jna/platform/win32/Version.class...
processing com/sun/jna/platform/win32/W32Errors.class...
processing com/sun/jna/platform/win32/W32FileMonitor.class...
processing com/sun/jna/platform/win32/W32FileMonitor$1.class...
processing com/sun/jna/platform/win32/W32FileMonitor$FileInfo.class...
processing com/sun/jna/platform/win32/W32FileUtils.class...
processing com/sun/jna/platform/win32/W32Service.class...
processing com/sun/jna/platform/win32/W32ServiceManager.class...
processing com/sun/jna/platform/win32/WTypes.class...
processing com/sun/jna/platform/win32/Wdm.class...
processing com/sun/jna/platform/win32/Wdm$KEY_BASIC_INFORMATION.class...
processing com/sun/jna/platform/win32/Wdm$KEY_INFORMATION_CLASS.class...
processing com/sun/jna/platform/win32/Win32Exception.class...
processing com/sun/jna/platform/win32/WinBase.class...
processing com/sun/jna/platform/win32/WinBase$FILETIME.class...
processing com/sun/jna/platform/win32/WinBase$FILETIME$ByReference.class...
processing com/sun/jna/platform/win32/WinBase$MEMORYSTATUSEX.class...
processing com/sun/jna/platform/win32/WinBase$OVERLAPPED.class...
processing com/sun/jna/platform/win32/WinBase$PROCESS_INFORMATION.class...
processing com/sun/jna/platform/win32/WinBase$PROCESS_INFORMATION$ByReference.class...
processing com/sun/jna/platform/win32/WinBase$SECURITY_ATTRIBUTES.class...
processing com/sun/jna/platform/win32/WinBase$STARTUPINFO.class...
processing com/sun/jna/platform/win32/WinBase$SYSTEMTIME.class...
processing com/sun/jna/platform/win32/WinBase$SYSTEM_INFO.class...
processing com/sun/jna/platform/win32/WinBase$SYSTEM_INFO$PI.class...
processing com/sun/jna/platform/win32/WinBase$SYSTEM_INFO$PI$ByReference.class...
processing com/sun/jna/platform/win32/WinBase$SYSTEM_INFO$UNION.class...
processing com/sun/jna/platform/win32/WinBase$SYSTEM_INFO$UNION$ByReference.class...
processing com/sun/jna/platform/win32/WinCrypt.class...
processing com/sun/jna/platform/win32/WinCrypt$CRYPTPROTECT_PROMPTSTRUCT.class...
processing com/sun/jna/platform/win32/WinCrypt$DATA_BLOB.class...
processing com/sun/jna/platform/win32/WinDef.class...
processing com/sun/jna/platform/win32/WinDef$DWORD.class...
processing com/sun/jna/platform/win32/WinDef$DWORDLONG.class...
processing com/sun/jna/platform/win32/WinDef$HBITMAP.class...
processing com/sun/jna/platform/win32/WinDef$HCURSOR.class...
processing com/sun/jna/platform/win32/WinDef$HDC.class...
processing com/sun/jna/platform/win32/WinDef$HFONT.class...
processing com/sun/jna/platform/win32/WinDef$HICON.class...
processing com/sun/jna/platform/win32/WinDef$HINSTANCE.class...
processing com/sun/jna/platform/win32/WinDef$HMENU.class...
processing com/sun/jna/platform/win32/WinDef$HMODULE.class...
processing com/sun/jna/platform/win32/WinDef$HPALETTE.class...
processing com/sun/jna/platform/win32/WinDef$HPEN.class...
processing com/sun/jna/platform/win32/WinDef$HRGN.class...
processing com/sun/jna/platform/win32/WinDef$HRSRC.class...
processing com/sun/jna/platform/win32/WinDef$HWND.class...
processing com/sun/jna/platform/win32/WinDef$LONG.class...
processing com/sun/jna/platform/win32/WinDef$LPARAM.class...
processing com/sun/jna/platform/win32/WinDef$LRESULT.class...
processing com/sun/jna/platform/win32/WinDef$RECT.class...
processing com/sun/jna/platform/win32/WinDef$UINT_PTR.class...
processing com/sun/jna/platform/win32/WinDef$ULONGLONG.class...
processing com/sun/jna/platform/win32/WinDef$WORD.class...
processing com/sun/jna/platform/win32/WinDef$WPARAM.class...
processing com/sun/jna/platform/win32/WinError.class...
writing classes.dex; size 278264...
processing com/sun/jna/platform/win32/WinGDI.class...

trouble writing output: Too many field references to fit in one dex file: 4347; max is 4096.
You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large.
References by package:
  4347 com.sun.jna.platform.win32

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.pojavdx.dx.command.dexer.Main.processClass(Main.java:766)
	at com.pojavdx.dx.command.dexer.Main.processFileBytes(Main.java:729)
	at com.pojavdx.dx.command.dexer.Main.access$1000036(Unknown Source:0)
	at com.pojavdx.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1699)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:287)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.pojavdx.dx.command.dexer.Main.processOne(Main.java:682)
	at com.pojavdx.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.pojavdx.dx.command.dexer.Main.runMultiDex(Main.java:361)
	at com.pojavdx.dx.command.dexer.Main.runDx(Main.java:283)
	at com.pojavdx.dx.command.dexer.Main.main(Main.java:241)
	at com.pojavdx.dx.command.Main.main(Main.java:95)
	at net.kdt.pojavlaunch.Tools.runDx(Tools.java:329)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:572)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to get length of null array
	at com.pojavdx.dx.command.dexer.Main.rotateDexFile(Main.java:659)
	at com.pojavdx.dx.command.dexer.Main.access$1000033(Unknown Source:0)
	at com.pojavdx.dx.command.dexer.Main$DirectClassFileConsumer.call(Main.java:1834)
	at com.pojavdx.dx.command.dexer.Main$DirectClassFileConsumer.access$1000070(Unknown Source:0)
	at com.pojavdx.dx.command.dexer.Main.processClass(Main.java:760)
	... 21 more
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.pojavdx.dx.command.dexer.Main$OutputResources.putNoCheck(Main.java:2024)
	at com.pojavdx.dx.command.dexer.Main$OutputResources.putDex(Main.java:2011)
	at com.pojavdx.dx.command.dexer.Main$OutputResources.access$1000079(Unknown Source:0)
	at com.pojavdx.dx.command.dexer.Main.rotateDexFile(Main.java:657)
	... 25 more
1 error; aborting
Exiting with code 1

**Comment by khanhduytran0** [comment]
Increase max DX reference.
Options -> Settings -> Set max DX references, increase to 8k then try agsin.

**Comment by Tom1390** [comment]
Thx

**Comment by MxndzaLoL** [comment]
Still not working
