### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rozaliu** [PojavLauncherTeam/PojavLauncher#360]
Pls help with this bug Application/game exited with code 1 
![Screenshot_20201016-201019_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/18704289/96288015-6ddf1600-0feb-11eb-911c-f55dfac9fb43.jpg)

**Comment by artdeell** [comment]
First, show `latestlog.txt` from the game folder, then we may say how to fix

пт, 16 окт. 2020 г., 20:09 rozaliu <notifications@github.com>:

**Comment by rozaliu** [comment]
how to show that i dont know

**Comment by artdeell** [comment]
sdnd the file

пт, 16 окт. 2020 г., 20:35 rozaliu <notifications@github.com>:
