### ISSUE TITLE
[BUG] GAMEPAD CONTROLLER 

### ISSUE THREAD

**Issue by jeffrey1233** [PojavLauncherTeam/PojavLauncher#3600]
### Describe the bug

Hello I'm using Mocute 050 
It's working properly with PojavLauncher_vcrocus-v3_openjdk playing version 1.16.5

But when I tried to play 1.19 with the pojav launcher dahlia-8-f527e8a14-v3_openjdk (the latest one on APKPure.com)
It's not working properly anymore I can't jump using A button can't switch to previous or next button by clicking l1 or r1 and can't open chest or touch it 

Seems the gamepad mappings have changed 

### The log file and images/videos

Yes

### Steps To Reproduce

```markdown
Fix gamepad mappings
```

### Expected Behavior

Not working

### Platform

```markdown
- Device model:Xiaomi Redmi 9t
- CPU architecture:ARMv8-A
- Android version:11
- PojavLauncher version: PojavLauncher_vcrocus-v3_openjdk & dahlia-8-f527e8a14-v3_openjdk
```

**Comment by GaucovyAero** [comment]
xbox controllers had to be fixed, and we cannot have support for improperly designed controllers, so there is no fix other than installing a magisk module that can change the bindings of your controller

**Comment by GaucovyAero** [comment]
stale issue. closing
