### ISSUE TITLE
[BUG] Can't use holy gl4es with modded version

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#3601]
### Describe the bug

Hi. For many times ago, I try to use holy gl4es for modded version of minecraft (forge and fabric) but it didn't work. I try to configure the renderer related settings but it didn't work

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9782205/latestlog.txt)

### Steps To Reproduce

```markdown
Step 1. Install modded version (forge or fabric, depents on what u want)
Step 2. Change renderer to holy gl4es
Step 3. Crash.
```

### Expected Behavior

I expected the game to bring to the main menu

### Platform

```markdown
- Device model: samsung galaxy a32 4g
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-67-2ba204a74-separate_bridges
```

### Anything else?

It seems to work on forge when I install very very few mod (for a very few second). Btw is this cause from my phone its self? I wanna know.

**Comment by AverageFemale** [comment]
https://mclo.gs/ntmay8l#L56

I uploaded your log file to mclo.gs. Try its solution.

**Comment by Thollp** [comment]
Ok

**Comment by Thollp** [comment]
> https://mclo.gs/ntmay8l#L56
> 
> I uploaded your log file to mclo.gs. Try its solution.

U̶m̶m̶,̶ ̶I̶ ̶t̶h̶i̶n̶k̶ ̶I̶ ̶u̶s̶e̶ ̶t̶h̶e̶ ̶w̶r̶o̶n̶g̶ ̶l̶o̶g̶ ̶f̶i̶l̶e̶ ̶a̶f̶t̶e̶r ̶I̶ ̶v̶i̶e̶w̶ ̶t̶h̶e̶ ̶l̶o̶g̶.̶ ̶I̶'̶l̶l̶ ̶u̶p̶d̶a̶t̶e̶ ̶s̶o̶o̶n̶

File updated

**Comment by Thollp** [comment]
> https://mclo.gs/ntmay8l#L56
> 
> I uploaded your log file to mclo.gs. Try its solution.

Umm, bro. The file you uploaded to https://mclo.gs was actually the wrong log file that I put in issue's "The log file and images/videos". Can you check the updated log file please

**Comment by AverageFemale** [comment]
I have seen it, I just have no solution at this time.

**Comment by GaucovyAero** [comment]
```
java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83949_(RenderTarget.java:161) ~[client-1.18.2-20220404.173914-srg.jar%2356!/:?]
```
Create doesn't work on GL4ES, because it doesn't support OpenGL 3.2+ features. We luckily have a new renderer in the testing. Here's the build of Pojav with it: https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8866885758/artifacts/404850022
- The renderer's called ANGLE and supports OpenGL 3.0 with only partial OpenGL 3.2, therefore it doesn't really run sodium very well (it doesn't render the terrain at all), but maybe it won't crash with create, just test for yourself.
- Requires Vulkan to be supported by your phone.
