### ISSUE TITLE
[F-Req] Bring back zink renderer

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#3602]
### Is this request related to a bug?

Yes. A bug where the virglrenderer is mess up with textures or make screen flip

### Describe the request.

I want you to bring back the zink renderer if it possible, because I know virglrenderer is buggy (which is annoying) and zink is not buggy like virglrenderer.

### Anything else?

I also have a problem with holy gl4es renderer which I already explained here
#3601

**Comment by GaucovyAero** [comment]
check out v3_zink branch, but some things may not work as expected

**Comment by Thollp** [comment]
> check out v3_zink branch, but some things may not work as expected

Umm ok

**Comment by Thollp** [comment]
> check out v3_zink branch, but some things may not work as expected

Yes, you're right

**Comment by GaucovyAero** [comment]
Fixed. Closing.
