### ISSUE TITLE
[BUG] PojavLauncher was deleted from Google Play

### ISSUE THREAD

**Issue by line-0707** [PojavLauncherTeam/PojavLauncher#3604]
### Describe the bug

The page has been deleted from Google Play and cannot be downloaded.
"The requested URL was not found on this server."

### The log file and images/videos

https://user-images.githubusercontent.com/78641260/196016722-626aa14d-ae82-435b-b016-d4e20afddb0f.mp4

### Steps To Reproduce

```markdown
1.Access to main page(https://github.com/PojavLauncherTeam/PojavLauncher)
2.Scroll down to "Getting PojavLauncher"
3.Press the "GET IT ON Google Play"
4. Unable to download
```

### Expected Behavior

Remove the link to Google Play or replace it with an item that downloads the APK.

### Platform

```markdown
- Device model: Any device that can use Google Play itself
- CPU architecture: -
- Android version: -
- PojavLauncher version: latest
```

**Comment by mchnjt** [comment]
Please get PojavLauncher from [the "Actions" builds](https://github.com/PojavLauncherTeam/PojavLauncher/actions) for now.

As for an explanation about PojavLauncher's removal from Google Play, please watch [this video](https://youtu.be/gYJL4J-mwXo). Have a nice day!

**Comment by NopeProsOnly** [comment]
The Actions builds is not a apk. What am I supposed to do?

**Comment by GaucovyAero** [comment]
> The Actions builds is not a apk. What am I supposed to do?

extract the zip and install the apk

**Comment by NopeProsOnly** [comment]
> > The Actions builds is not a apk. What am I supposed to do?
> 
> extract the zip and install the apk

How would I install the apk.

**Comment by GaucovyAero** [comment]
> > > The Actions builds is not a apk. What am I supposed to do?
> > 
> > 
> > extract the zip and install the apk
> 
> How would I install the apk.

just click on the apk and press install

**Comment by NopeProsOnly** [comment]
> 

I can't find the apk. I dowloaded, extracted, and searched everywhere...

**Comment by NopeProsOnly** [comment]
![image](https://user-images.githubusercontent.com/78925970/197539967-b5faa183-f65f-44fe-b7f1-14d97e5f2d47.png)
No Apk

**Comment by GaucovyAero** [comment]
> ![image](https://user-images.githubusercontent.com/78925970/197539967-b5faa183-f65f-44fe-b7f1-14d97e5f2d47.png) No Apk

you quite literally downloaded the source code

**Comment by GaucovyAero** [comment]
https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8866885758/artifacts/404850022

here is the correct link - unofficial download tho, but it has some bugfixes in it

**Comment by NopeProsOnly** [comment]
> https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8866885758/artifacts/404850022
> 
> here is the correct link - unofficial download tho, but it has some bugfixes in it

![Screenshot_20221024-103131_Samsung Internet.jpg](https://user-images.githubusercontent.com/78925970/197551349-97e8005b-fd3f-4e62-8574-556d5fbe87ce.jpg)

**Comment by GaucovyAero** [comment]
you have to be logged into github in order for the download to work, also, i recommend using firefox for all pojav files instead of other browsers, you might get corrupted mods, etc. with chrome and other ones except firefox

**Comment by ATOM1138** [comment]
> you have to be logged into github in order for the download to work, also, i recommend using firefox for all pojav files instead of other browsers, you might get corrupted mods, etc. with chrome and other ones except firefox

after all these steps, still 404

**Comment by NopeProsOnly** [comment]
I already tried that. The link doesn't exist... perhaps a permission thing?

**Comment by CriticalRange** [comment]
> https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8866885758/artifacts/404850022
> 
> here is the correct link - unofficial download tho, but it has some bugfixes in it

Link gives 404 :hyperrofel:

**Comment by towermom9** [comment]
So how to download it now?

**Comment by miggythewriter** [comment]
> So how to download it now?

https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=is%3Asuccess+branch%3Av3_openjdk

**Comment by BR3XALITY** [comment]
> ![image](https://user-images.githubusercontent.com/78925970/197539967-b5faa183-f65f-44fe-b7f1-14d97e5f2d47.png) No Apk

Just rename the file you extracted that from and rename it to apk
