### ISSUE TITLE
[F-Req] Storage on SD card

### ISSUE THREAD

**Issue by initialcommit810** [PojavLauncherTeam/PojavLauncher#3605]
### Is this request related to a bug?

No

### Describe the request.

Is there SD card support for game files and if not, can you consider adding it? If there is, then how do I use it?

### Anything else?

I only have 8gb on my phone and most of it is taken by system and a few other apps. SD card support would be helpful.

**Comment by GaucovyAero** [comment]
yeah it should work, at least it worked for me when i was using it

**Comment by initialcommit810** [comment]
So, how do I use it?

**Comment by GaucovyAero** [comment]
> So, how do I use it?

every device has it different, cant help you with that

**Comment by initialcommit810** [comment]
if you are talking about moving it to the sd card using the Android settings menu, then it doesn't show the option to move it

**Comment by GaucovyAero** [comment]
this is an android thing, not pojav
