### ISSUE TITLE
No sound bug in pojavlauncher 

### ISSUE THREAD

**Issue by Hypergaming2021** [PojavLauncherTeam/PojavLauncher#3607]
### Describe the bug

Help when I play 1.19.2 and I join my world there's no sound and I can't even listen to music pls someone help!!!!

### The log file and images/videos

Help

### Steps To Reproduce

```markdown
Help
```

### Expected Behavior

I expect to have sound

### Platform

```markdown
- Device model: Redmi 9
- CPU architecture: aarch64
- Android version:android 12 
- PojavLauncher version: new version
```

### Anything else?

And it lags

**Comment by Thollp** [comment]
Bro, you also need to tell devs the version that cause bug. If just tell "new version", they will simply not know what version they need to fix

**Comment by Thollp** [comment]
> Bro, you also need to tell devs the version that cause bug. If just tell "new version", they will simply not know what version they need to fix

Example: Pojavlauncher version: dahlia-51-cc9efa8be-v3_zink

If you don't know what version you playing. Go to app info of pojav

**Comment by Hypergaming2021** [comment]
The version is dahlia-67-2ba204a74-separate_bridges

**Comment by GaucovyAero** [comment]
> The version is dahlia-67-2ba204a74-separate_bridges

no one has had this issue before and you didn't bring up any evidence that it's happening yet, therefore we cannot fix it

- please attach a video and latestlog.txt

**Comment by Hypergaming2021** [comment]
Wdym evidence?  And do I have to upload video?

**Comment by GaucovyAero** [comment]
> Wdym evidence? And do I have to upload video?

yeah that would be great, thing is, we cannot have any idea as to how to fix it, because no one is having this issue currently

**Comment by endervad** [comment]
While not in the same Minecraft version, there's no sound for me in both vanilla, and Forge 1.6.4. Interestingly enough, after that every latest major version does have sound (vanilla 1.7.10, 1.8.9, 1.9.4, etc. up to current 1.19.2).
```
- Device model: Lenovo Legion Y700
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-107-b6f15cb42-v3_openjdk
```
Couldn't test versions 1.5.x and lower since they hang on Mojang logo - I suppose that should be a different issue but I'm not sure if there's a demand for these versions lol.
Log is attached, I closed the game properly via "Quit Game" button.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9898186/latestlog.txt)

**Comment by GaucovyAero** [comment]
> While not in the same Minecraft version, there's no sound for me in both vanilla, and Forge 1.6.4. Interestingly enough, after that every latest major version does have sound (vanilla 1.7.10, 1.8.9, 1.9.4, etc. up to current 1.19.2).
> 
> ```
> - Device model: Lenovo Legion Y700
> - CPU architecture: aarch64
> - Android version: 12
> - PojavLauncher version: dahlia-107-b6f15cb42-v3_openjdk
> ```
> 
> Couldn't test versions 1.5.x and lower since they hang on Mojang logo - I suppose that should be a different issue but I'm not sure if there's a demand for these versions lol. Log is attached, I closed the game properly via "Quit Game" button. [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9898186/latestlog.txt)

isnt that because its resources were removed from mojang servers just like b1.7.3, etc.?

**Comment by GaucovyAero** [comment]
also, the hanging on mojang logo, you gotta delete options.txt, just like on PC, i think it is either a nullpointer or outofboundsexception but that doesnt really matter, just delete options.txt

**Comment by endervad** [comment]
> > While not in the same Minecraft version, there's no sound for me in both vanilla, and Forge 1.6.4. Interestingly enough, after that every latest major version does have sound (vanilla 1.7.10, 1.8.9, 1.9.4, etc. up to current 1.19.2).
> > ```
> > - Device model: Lenovo Legion Y700
> > - CPU architecture: aarch64
> > - Android version: 12
> > - PojavLauncher version: dahlia-107-b6f15cb42-v3_openjdk
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Couldn't test versions 1.5.x and lower since they hang on Mojang logo - I suppose that should be a different issue but I'm not sure if there's a demand for these versions lol. Log is attached, I closed the game properly via "Quit Game" button. [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9898186/latestlog.txt)
> 
> isnt that because its resources were removed from mojang servers just like b1.7.3, etc.?

Assuming Pojav downloads resources from the same place as other launchers, no. I use official launcher and MultiMC on desktop, and the sound works fine in 1.6.4 out of box even if I remove `assets` folder, forcing the launchers to download stuff again. If the resources weren't on the server, there wouldn't be any sound on desktop versions too.

> also, the hanging on mojang logo, you gotta delete options.txt, just like on PC, i think it is either a nullpointer or outofboundsexception but that doesnt really matter, just delete options.txt

I'll try that later out of interest, thanks.

**Comment by GaucovyAero** [comment]
you can also use betacraft proxy for 1.5.2 and older ig
