### ISSUE TITLE
[BUG] Zink renderer screen flickering

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#3608]
### Describe the bug

A days ago. I try v3_zink pojavlauncher but the zink renderer cause my game to starts flickering repeatedly

### The log file and images/videos

https://user-images.githubusercontent.com/100254075/196579134-8f1558f3-da43-4b46-a497-4d2f45e27199.mp4

### Steps To Reproduce

```markdown
Step 1. Start pojavlauncher after choose zink renderer
Step 2. Screen starts flickering
```

### Expected Behavior

I expected the screen is not flickering

### Platform

```markdown
- Device model: Samsung galaxy a32
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-51-cc9efa8be-v3_zink
```

### Anything else?
I don't know why. But I can't upload an original video of the bug footages, so I record the original video of the bug footages

And yes. The screen is flickering, but its still playable at good fps but my eye strain tho

**Comment by mchnjt** [comment]
Do you think photos can help us in solving your issue?

**Comment by Thollp** [comment]
> Do you think photos can help us in solving your issue?

 N̶o̶?̶
It fixed now

**Comment by GaucovyAero** [comment]
Fixed. Closing.

**Comment by Thollp** [comment]
> Fixed. Closing.

Nope. The fact that I said "It fixed now", I mean I changed the log file
