### ISSUE TITLE
Can't able to allocate more ram

### ISSUE THREAD

**Issue by Akku9446l** [PojavLauncherTeam/PojavLauncher#3609]
### Describe the bug

I am not able to allocate more ram . My device is 6gb ram and free of 4gb but it only show upto 1100mb

### The log file and images/videos

![Screenshot_2022-10-19-07-02-38-118_net kdt pojavlaunch](https://user-images.githubusercontent.com/116050237/196576351-f92a329b-02ee-4526-86cd-25138fd6b73f.jpg)

### Steps To Reproduce

```markdown
Help me
```

### Expected Behavior

I expect you will sopve this problem and then i can allocate more ram

### Platform

```markdown
- Device model: Redmi 9 activ
- CPU architecture:32 bit
- Android version: 10
- PojavLauncher version: Dahila latest version
```

### Anything else?

Help me

**Comment by Thollp** [comment]
I think the dev lowers the amount of the amount of ram allocation is because to prevent game crash (because when start game with allocated ram more than free ram, it say it can lead to game crash)

**Comment by Thollp** [comment]
BTW you should not tell the version type "dahlia new version" because dev will not know what version they need to fix

Tell the version like this
Ex. Pojavlauncher version: dahlia-51-cc9efa8be-v3_zink

Btw that's is the version I play so don't ask

**Comment by GaucovyAero** [comment]
> ### Describe the bug
> I am not able to allocate more ram . My device is 6gb ram and free of 4gb but it only show upto 1100mb
> 
> ### The log file and images/videos
> ![Screenshot_2022-10-19-07-02-38-118_net kdt pojavlaunch](https://user-images.githubusercontent.com/116050237/196576351-f92a329b-02ee-4526-86cd-25138fd6b73f.jpg)
> 
> ### Steps To Reproduce
> ```gfm
> Help me
> ```
> 
> ### Expected Behavior
> I expect you will sopve this problem and then i can allocate more ram
> 
> ### Platform
> ```gfm
> - Device model: Redmi 9 activ
> - CPU architecture:32 bit
> - Android version: 10
> - PojavLauncher version: Dahila latest version
> ```
> 
> ### Anything else?
> Help me

you just don't have 4GB left, im pretty sure the application you are using to show ram usage lies about it

**Comment by Akku9446l** [comment]
Not any application my system is showing the ram

**Comment by Akku9446l** [comment]
> BTW you should not tell the version type "dahlia new version" because dev will not know what version they need to fix
> 
> Tell the version like this
> Ex. Pojavlauncher version: dahlia-51-cc9efa8be-v3_zink
> 
> Btw that's is the version I play so don't ask

How to find it

**Comment by GaucovyAero** [comment]
in any case, you should not be using more than 1000MB for optimal performance (higher ram allocation = lower fps) if you are not playing a gigantic modpack

**Comment by Akku9446l** [comment]
> BTW you should not tell the version type "dahlia new version" because dev will not know what version they need to fix
> 
> Tell the version like this
> Ex. Pojavlauncher version: dahlia-51-cc9efa8be-v3_zink
> 
> Btw that's is the version I play so don't ask

dahlia-8-f527e8a14-v3_openjdk this is the version

**Comment by Akku9446l** [comment]
> in any case, you should not be using more than 1000MB for optimal performance (higher ram allocation = lower fps) if you are not playing a gigantic modpack

I would like to use shader that's why

**Comment by GaucovyAero** [comment]
> > in any case, you should not be using more than 1000MB for optimal performance (higher ram allocation = lower fps) if you are not playing a gigantic modpack
> 
> I would like to use shader that's why

Well, you won't be able to allocate more than that on a 32-bit device. You also can't do that on a PC if you are 32-bit. No game can allocate more than that on your phone.

**Comment by GaucovyAero** [comment]
Fixed. Closing.
