### ISSUE TITLE
none of the JRE works

### ISSUE THREAD

**Issue by Gaprix** [PojavLauncherTeam/PojavLauncher#361]
None of the suggested JREs work.
Processor: Samsung Exynos 9 Octa 9820
Android: 10

Screenshots of different JRE:

jre9-arm-20200929.tar.xz
![Screenshot_20201016-225713_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/45711510/96303375-f4ebb880-1002-11eb-8082-d45f1207700a.jpg)

jre9-arm64-20200929.tar.xz
![Screenshot_20201016-225830_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/45711510/96303548-4005cb80-1003-11eb-996f-5e4a0cffd0de.jpg)

jre9-x86_64-20200929.tar.xz
![Screenshot_20201016-230025_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/45711510/96303637-66c40200-1003-11eb-87aa-9d3c22845e84.jpg)

jre9-x86-20200929.tar.xz
![Screenshot_20201016-230124_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/45711510/96303723-8a874800-1003-11eb-8fc3-9244f164b872.jpg)

**Comment by artdeell** [comment]
1. Use arm64 runtime
2. Send `latestlog.txt` from the game, so that we would know what happened.

пт, 16 окт. 2020 г., 23:02 Gaprix <notifications@github.com>:

**Comment by Gaprix** [comment]
Problem solved. I copied the archive from the instructions to the wrong folder
