### ISSUE TITLE
[BUG] Minecraft 22w42a crashes on start

### ISSUE THREAD

**Issue by Baldi627** [PojavLauncherTeam/PojavLauncher#3610]
### Describe the bug

Application exited with code -1 before loading screen appeared

### The log file and images/videos

[crash-2022-10-19_13.49.19-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9821079/crash-2022-10-19_13.49.19-client.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Create a new profile for snapshot 22w42a
3. Play the snapshot
4. The game then crashes before the loading screen appears
```

### Expected Behavior

The game would loads

### Platform

```markdown
- Device model: Samsung Galaxy A53 5G
- CPU architecture: x64
- Android version: 12
- PojavLauncher version: 3.3.1
```

### Anything else?

If this is just an issue on my end I would like to know how to fix it.

**Comment by GaucovyAero** [comment]
you are using a super old launcher version, please update to this: https://github.com/PojavLauncherTeam/PojavLauncher/suites/7857967858/artifacts/332982258
if it still doesnt work after updating, make sure to send `latestlog.txt` and NOT the crash log nor latest.log

**Comment by Baldi627** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9821302/latestlog.txt)

That didn't work.

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9821302/latestlog.txt)
> 
> That didn't work.

yeah okay, great that you actually attached the right log this time (instead of the 1.19.2 working one :D), but yeah, this issue is real and will be investigated, great that you pointed this out

**Comment by Baldi627** [comment]
Should I close this issue now?

**Comment by GaucovyAero** [comment]
> Should I close this issue now?

nonono, just wait until its fixed probably

**Comment by GaucovyAero** [comment]
@Baldi627 try this pojav build: https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8856573088/artifacts/404121114

**Comment by Baldi627** [comment]
That build does not give snapshot 22w42a as an option

**Comment by InfernoNova9999** [comment]
i tried it it works fine for me on iOS.

**Comment by Baldi627** [comment]
I realized the reason the snapshot didn't show up was because snapshots were not enabled by default

**Comment by Baldi627** [comment]
It works! Thanks!

**Comment by ghost** [comment]
> @Baldi627 try this pojav build: https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8856573088/artifacts/404121114

The link don't work. Please give another

**Comment by GaucovyAero** [comment]
> > @Baldi627 try this pojav build: https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8856573088/artifacts/404121114
> 
> The link don't work. Please give another

its still working, no idea what's your issue, you were probably not logged into github

**Comment by VoidVanisher** [comment]
> @Baldi627 try this pojav build: https://github.com/NotAHero04/PojavLauncher-ANGLE/suites/8856573088/artifacts/404121114

This doesn't work, it loads the snapshot it says the version, however when you create a world, there's nothing new ever just normal stuff

**Comment by ghost** [comment]
Ok. I saw it. Sorry for it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
