### ISSUE TITLE
Unable to allocate more ram

### ISSUE THREAD

**Issue by Akku9446l** [PojavLauncherTeam/PojavLauncher#3611]
### Describe the bug

I am not able to allocate more ram than 1100mb my device is 6gb ram and avail of 4gb

### The log file and images/videos

![Screenshot_2022-10-19-07-02-38-118_net kdt pojavlaunch](https://user-images.githubusercontent.com/116050237/196836124-a72c4c44-352c-4308-a8ae-0b23ccc9c169.jpg)

### Steps To Reproduce

```markdown
Help me
```

### Expected Behavior

I expect you will solve this 

### Platform

```markdown
- Device model: Redmi 9 activ
- CPU architecture: 32bit
- Android version: 10
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

**Comment by AverageFemale** [comment]
Why double post?

**Comment by AverageFemale** [comment]
#3609

**Comment by Thollp** [comment]
> Why double post?

Because in old post, he describe "Pojavlauncher version: dahlia new version" and I think he's does not know how to edit post after I tell him you should not type just "dahlia new version"

**Comment by Thollp** [comment]
Btw I just want to say
![Screenshot_20221020-104207_Chrome](https://user-images.githubusercontent.com/100254075/196851514-79eee43a-547b-4e32-809f-eb58b1e455b9.jpg)
To him

**Comment by GaucovyAero** [comment]
Duplicate issue. Closing.
