### ISSUE TITLE
[F-Req] Game Crashed

### ISSUE THREAD

**Issue by Sahilkumar568** [PojavLauncherTeam/PojavLauncher#3612]
### Is this request related to a bug?

Plz help my game was crashed 

### Describe the request.

Plz help my game crash version 1.19

### Anything else?

Plz help

**Comment by Sahilkumar568** [comment]
> 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9829050/latestlog.txt)

**Comment by Sahilkumar568** [comment]
![Uploading Screenshot_20221020_161950.jpg…]()

**Comment by Sahilkumar568** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9829054/latestlog.txt)

**Comment by Sahilkumar568** [comment]
![Screenshot_20221020_161950](https://user-images.githubusercontent.com/98516723/196930319-f5871fc1-c5c3-4e4a-bc4f-da69990f475b.jpg)

**Comment by Thollp** [comment]
> > 
> 
> 	 - Replace mod 'Enhanced Block Entities' (enhancedblockentities) 0.7.1+1.19 with any version that is compatible with:
		 - optifabric 1.13.16
Unmet dependency listing:
	 - Mod 'Enhanced Block Entities' (enhancedblockentities) 0.7.1+1.19 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!


Bro, it's mod incompatable issue. The log file said that any version of "Enhanced Block Entities" mod is incompatable with Optifabric

**Comment by Akku9446l** [comment]
When i run sodium with fabric the blocks are invisible

**Comment by Sahilkumar568** [comment]
Bro I remove this mod but not worked

**Comment by Sahilkumar568** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9831308/latestlog.txt)

**Comment by Sahilkumar568** [comment]
Check this again bro

**Comment by Sahilkumar568** [comment]
This is new

**Comment by Sahilkumar568** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9831699/latestlog.txt)

**Comment by Sahilkumar568** [comment]
Check this

**Comment by Thollp** [comment]
> Check this

I think I really need the dev to solve this issue (BTW I'm not a dev). And also, this should labeled "bug" not "enhancement". Enhancement is for request(possible) new feature(s).

**Comment by Sahilkumar568** [comment]
Give me some mods to lag fix

**Comment by GaucovyAero** [comment]
Fixed. Closing.
