### ISSUE TITLE
[BUG] My Gamecrashed

### ISSUE THREAD

**Issue by Sahilkumar568** [PojavLauncherTeam/PojavLauncher#3613]
### Describe the bug

Application exited 1

### The log file and images/videos

Plz help my game crashed 

### Steps To Reproduce

```markdown
Start pojav launcher 
Version 1.19 fabric 
I using OFTIFABRIC mod
```

### Expected Behavior

My OFTIFABRIC mod was not worked plz help me

### Platform

```markdown
- Device model: 
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: 1.19
```

### Anything else?

Help bro OFTIFABRIC was not worked and crashed
![Screenshot_20221020_161950](https://user-images.githubusercontent.com/98516723/197170344-d4dc6b33-243b-49c6-8b97-13c121f1880c.jpg)

**Comment by Sahilkumar568** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9838000/latestlog.txt)

**Comment by Sahilkumar568** [comment]
This is log check bro and solve my problem bro

**Comment by Sahilkumar568** [comment]
Give me some mods to lag fux

**Comment by GaucovyAero** [comment]
> This is log check bro and solve my problem bro

you are using an outdated version of minecraft

**Comment by GaucovyAero** [comment]
> Give me some mods to lag fux

use holy gl4es as a renderer

**Comment by Sahilkumar568** [comment]
Yes bro I already that issue but I need mods for pojav launcher 1.19.2 fabric bro

**Comment by Sahilkumar568** [comment]
I use OFTIFABRIC with oftifine

**Comment by Sahilkumar568** [comment]
Plz some more mods

**Comment by Sahilkumar568** [comment]
Give

**Comment by GaucovyAero** [comment]
no

**Comment by Sahilkumar568** [comment]
Plz bro

**Comment by Sahilkumar568** [comment]
I will find many mods but it nots works

**Comment by Sahilkumar568** [comment]
You will give plz i ammm thankful to you plz

**Comment by Sahilkumar568** [comment]
You give names only

**Comment by GaucovyAero** [comment]
just get my fps boosting modpack in #general on the official PojavLauncher discord server

**Comment by Sahilkumar568** [comment]
Ok bro

**Comment by Sahilkumar568** [comment]
Where is general

**Comment by Sahilkumar568** [comment]
In dc

**Comment by GaucovyAero** [comment]
> In dc

#general on the PojavLauncher discord server

**Comment by Sahilkumar568** [comment]
No

**Comment by Sahilkumar568** [comment]
One time you will give me dc link

**Comment by GaucovyAero** [comment]
> One time you will give me dc link

https://discord.gg/vPjnkFAK

**Comment by Sahilkumar568** [comment]
![Screenshot_20221023_122452](https://user-images.githubusercontent.com/98516723/197378509-272e9650-9aec-4464-b4bc-d4f782f9fb89.jpg)

**Comment by Sahilkumar568** [comment]
See where is general

**Comment by Sahilkumar568** [comment]
I am soory i am wasting your time bri

**Comment by GaucovyAero** [comment]
> See where is general

you gotta have the english role to access #general

**Comment by Sahilkumar568** [comment]
Ok bro

**Comment by Sahilkumar568** [comment]
I message in general reply bro

**Comment by GaucovyAero** [comment]
Fixed. Closing.
