### ISSUE TITLE
Isn't letting me play with forge

### ISSUE THREAD

**Issue by Masterofloki69** [PojavLauncherTeam/PojavLauncher#3614]
### Describe the bug

I keep trying to play with forge and when l press play it go to code 1 or application/game exited with code 1 and l don't know what to do when that shows up. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9843535/latestlog.txt)

### Steps To Reproduce

```markdown
Get forge (1.12.2 l choose) go to pojavlaunchee using a offline account use.Jer 
Use the first of the three
Let it load, go to version and press play
```

### Expected Behavior

It fine just fix the code 1 problem

### Platform

```markdown
- Device model: google pixel 6
- CPU architecture:? 
- Android version: 11
- PojavLauncher version: Dahlia
```

**Comment by GaucovyAero** [comment]
```
java.lang.ClassNotFoundException: com.google.common.collect.Lists
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more
Java Exit code: 1
```
you are missing libraries. You have to be logged in with a Microsoft account that owns Minecraft: Java Edition in order to get access to downloading them. Closing.
