### ISSUE TITLE
1.19.2 Sodium Crash

### ISSUE THREAD

**Issue by YoussefzP** [PojavLauncherTeam/PojavLauncher#3615]
### Describe the bug

I Installed Fabric And Sodium For 1.19.2 It Was Fine But When I Generate The World The Game Crash

### The log file and images/videos

...

### Steps To Reproduce

```markdown
1-start Pojav Launcher
2-Open 1.19.2 With Sodium
3-Generator World
4-After Generate The Game Crash
```

### Expected Behavior

The World Will Open

### Platform

```markdown
- Device model: Redmi Note 10s
- CPU architecture: aarch 64
- Android version: 12
- PojavLauncher version: Lastest OpenJdk Version
```

**Comment by GaucovyAero** [comment]
Sodium won't work, because we don't support OpenGL 3.2. Closing. #1948

**Comment by Fl414r** [comment]
I too late, but Sodium works perfectly. Just dont use Sodium Extra.
Or maybe not enough RAM.
