### ISSUE TITLE
[F-Req] Add prebuilt APK to Github Release

### ISSUE THREAD

**Issue by BlockyTheDev** [PojavLauncherTeam/PojavLauncher#3616]
### Is this request related to a bug?

/

### Describe the request.

Add prebuilt APK to Github Release, because it is removed from Google Playstore and so I couldn't install it again.

### Anything else?

/

**Comment by mchnjt** [comment]
no.

**Comment by BlockyTheDev** [comment]
> no.

Why not? Was it removed by Google or by the team itself? I tried to build it myself but it says that a dependency couldn't be found.

**Comment by BlockyTheDev** [comment]
I close it because I saw the video in the other issue. Github didn't show me the other issue on Android, so I created a new one.
