### ISSUE TITLE
[BUG] Strange Texture.

### ISSUE THREAD

**Issue by GabeNewID** [PojavLauncherTeam/PojavLauncher#3617]
### Describe the bug

when I enter Minecraft ALL the textures are like 8-bit.

I tried to change the renderer, but I lose performance in all.
(using gl4es 1.1.4)

I'm using 41 MODs in 1.12.2. I don't believe that any of them is the cause of the problem because I've already tested them all individually.

### The log file and images/videos

![2022-10-27_20 51 13](https://user-images.githubusercontent.com/114858754/198399168-b0ed055f-644b-4fa8-9ef6-ac26e42974d6.png)

![2022-10-27_20 52 43](https://user-images.githubusercontent.com/114858754/198399174-f26f8721-973e-41fb-b1e5-03fe714a1e8a.png)

### Steps To Reproduce

```markdown
I don't know exactly how to reproduce, I just got into pojav with Forge from the latest 1.12.2 and some mods
```

### Expected Behavior

 I expect play normally without these texture issues.

### Platform

```markdown
- Device model: Samsung Galaxy M52
- CPU architecture: aarch64
- Android version: 12
```

### Anything else?

Sorry for bad English.

**Comment by GaucovyAero** [comment]
You are out of video memory. It's caused by the mods, although it should be fixed in this build right here: https://github.com/Aerolome/PojavLauncher-ANGLE/releases/download/1.0/app-debug.apk

**Comment by GabeNewID** [comment]
> You are out of video memory. It's caused by the mods, although it should be fixed in this build right here: https://github.com/Aerolome/PojavLauncher-ANGLE/releases/download/1.0/app-debug.apk

Okay, I'll install here and test

**Comment by GabeNewID** [comment]
That problem was solved, now there's another texture/rendering problem

![2022-10-27_23 48 20](https://user-images.githubusercontent.com/114858754/198418654-cfcd900f-7ff3-4f3c-b986-0f37cc6115d8.png)

![2022-10-27_23 48 40](https://user-images.githubusercontent.com/114858754/198418670-64d8621a-abde-447d-813d-b7eeb099819c.png)

**Comment by GaucovyAero** [comment]
> That problem was solved, now there's another texture/rendering problem
> 
> ![2022-10-27_23 48 20](https://user-images.githubusercontent.com/114858754/198418654-cfcd900f-7ff3-4f3c-b986-0f37cc6115d8.png)
> 
> ![2022-10-27_23 48 40](https://user-images.githubusercontent.com/114858754/198418670-64d8621a-abde-447d-813d-b7eeb099819c.png)

press F11 and you should be all fixed

**Comment by GabeNewID** [comment]
Ooooohh thank you very much, everything is resolved
