### ISSUE TITLE
[BUG] Mouse not showing where it really is.

### ISSUE THREAD

**Issue by GabeNewID** [PojavLauncherTeam/PojavLauncher#3619]
### Describe the bug

Hovering the mouse over any button does not correspond to the actual place the mouse is on the screen.

(I'm using version 1.12.2 with the latest Forge and 41 MODs)

### The log file and images/videos

![2022-10-28_11 44 59](https://user-images.githubusercontent.com/114858754/198582010-2be3e585-8b2a-4b10-9903-490a0c88f5dc.png)

![2022-10-28_11 44 32](https://user-images.githubusercontent.com/114858754/198582039-63c5369e-ce87-4593-bca9-5920f94a0d2e.png)

### Steps To Reproduce

```markdown
1. Start Pojav.
2. Put the mouse over anything.
```

### Expected Behavior

I expect a way to fix this.

### Platform

```markdown
- Device model: Samsung Galaxy M52
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: 20221025
```

### Anything else?

Sorry for bad English. (EDIT = I noticed that the mouse is not showing up in the screenshots, I'm sorry for the mistake)

**Comment by GaucovyAero** [comment]
If you have a setting called "Ignore notch" in Video and renderer setttings, enable that.
- if you don't have that setting, do the following:

In `/data/data/net.kdt.pojavlaunch.debug/shared_prefs/net.kdt.pojavlaunch.debug_preferences.xml`,
Change the `IgnoreNotch` value to `true`

**your mileage may vary, you may need root to do this**

**Comment by GabeNewID** [comment]
Thanks again, it's all resolved now S2

**Comment by lgsanai** [comment]
/data/data/net.kdt.pojavlaunch.debug/shared_prefs/net.kdt.pojavlaunch.debug_preferences.xml
Where to do this setting please tell me I have the same problem
