### ISSUE TITLE
Pojavlauncher crashes when installing .jar files

### ISSUE THREAD

**Issue by Text1220** [PojavLauncherTeam/PojavLauncher#3620]
### Describe the bug

When I try to install forge fabric or optifine the pojavlauncher app crashes 

### The log file and images/videos

https://user-images.githubusercontent.com/100729261/198833413-425a5c46-1e38-4980-a177-6c7ac8892d1b.mp4

[latestlog(1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9893752/latestlog.1.txt)

### Steps To Reproduce

```markdown
1. Open pojave launcher
2. Select account
3. Click install .jar
4. Choose fabric or forge installer
```

### Expected Behavior

I expect the game to start the fabric installer or forge installer

### Platform

```markdown
- Device model:Moto G Stylus 5G (XT2131-1)
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: latest from action builds
```

### Anything else?

And I did use Firefox and turned autorotate on

**Comment by stacode123** [comment]
Have the same error only it doesn't even ask for a file

**Comment by khanhduytran0** [comment]
@Text1220 please send `/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/hs_err_pid2979.log`

**Comment by khanhduytran0** [comment]
> Have the same error only it doesn't even ask for a file

It’s likely because no file manager exists on device

**Comment by Text1220** [comment]
> @Text1220 please send `/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/hs_err_pid2979.log`

I don't see the .Minecraft folder

**Comment by khanhduytran0** [comment]
You need to enable `show hidden folder ` in the file manager.

**Comment by Text1220** [comment]
[hs_err_pid2979.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9894209/hs_err_pid2979.log)

**Comment by GaucovyAero** [comment]
> [hs_err_pid2979.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9894209/hs_err_pid2979.log)

make sure to have auto-rotate turned on when using the jar installer

**Comment by Text1220** [comment]
> > [hs_err_pid2979.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9894209/hs_err_pid2979.log)
> 
> make sure to have auto-rotate turned on when using the jar installer

I did but it still crashes

**Comment by GaucovyAero** [comment]
> > > [hs_err_pid2979.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9894209/hs_err_pid2979.log)
> > 
> > 
> > make sure to have auto-rotate turned on when using the jar installer
> 
> I did but it still crashes

send latestlog.txt

**Comment by Text1220** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9900655/latestlog.txt)

**Comment by lulu0430** [comment]
add jre8

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9900655/latestlog.txt)

this happens exactly when you have auto rotate turned off, so like no idea, also, whats your launcher version?

**Comment by GaucovyAero** [comment]
also, what browser did you use to download the jar?

**Comment by Text1220** [comment]
> > [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9900655/latestlog.txt)
> 
> this happens exactly when you have auto rotate turned off, so like no idea, also, whats your launcher version?

version LOCAL-20221029 I got the app from GitHub actions

**Comment by Text1220** [comment]
> also, what browser did you use to download the jar?

And I used Firefox to download the .jar files

**Comment by Text1220** [comment]
And it also crashes when I don't use a modified version

**Comment by Pbg4444** [comment]
how can i turn autorotate on?

**Comment by Text1220** [comment]
Look in your notification shade or settings

**Comment by Pbg4444** [comment]
oh lamao that auto rotate. I think it is somthing for the game

**Comment by GaucovyAero** [comment]
rotate your screen into landscape mode

**Comment by Mathias-Boulay** [comment]
I'm confused about whether or not this is still an issue on the current dev version, or release for that matter

**Comment by GaucovyAero** [comment]
> I'm confused about whether or not this is still an issue on the current dev version, or release for that matter

i cant reproduce it but it sure is on play store

**Comment by Mathias-Boulay** [comment]
@Text1220 Can you reproduce it with the current dev build ?

**Comment by Text1220** [comment]
I think so

**Comment by GaucovyAero** [comment]
> I think so

try it, go to actions and find the uppermost build with a green checkmark on it, click on app-debug, extract app-debug.zip, install app-debug.apk

**Comment by Mathias-Boulay** [comment]
fixed by the latest MAINLINE dev build
