### ISSUE TITLE
[F-Req] Remapping controls for controller

### ISSUE THREAD

**Issue by DarkLimboV** [PojavLauncherTeam/PojavLauncher#3621]
### Is this request related to a bug?

Not that I am aware of.

### Describe the request.

I have saw duplicates on this subject, however the only one I have found was not solved. As the title suggests I want the ability to remap the controls on my controller. Whenever I press the X button on my controller it opens my inventory. I am used of the Y button for inventory from my experience from console/mobile. I have tried remapping the controls through the in-game settings, but its super funky and doesn't represent the key I pressed or for some buttons ignore them entirely. I also don't want a funky work around or a mod. I use different versions of Minecraft and not all of them support the mod/s that are available.

### Anything else?

If there is anyway to do this without mods or a workaround like a config file I need to change then please enlighten me.

**Comment by GaucovyAero** [comment]
closing this as it is a duplicate
