### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Saddamkhanjadaraghgdvvg** [PojavLauncherTeam/PojavLauncher#3624]
### Is this request related to a bug?

Please solve lag problem in 1.12.2 version 1gb ram please

**Comment by mchnjt** [comment]
You can try
- increasing the RAM allocation
  - for 32-bit devices, this feature is limited.
  - Try closing the apps running on the background
  - Enable "Sustained Performance" mode in the options
- install OptiFine then set the video settings to the lowest

You might just want to buy a better device to skip around all of the above.
