### ISSUE TITLE
[BUG] <cant get app>

### ISSUE THREAD

**Issue by toms1232123123** [PojavLauncherTeam/PojavLauncher#3628]
### Describe the bug

When I press the get now Google play link it says that something went wrong

### The log file and images/videos

![Screenshot_20221101-164004_Google Play Store](https://user-images.githubusercontent.com/116894701/199260314-1f3b32cf-8024-482a-9db6-8a83ccf950bc.jpg)

### Steps To Reproduce

```markdown
1. Open the git hub page
2. Press Get now on Google play
3. Doesn't work
```

### Expected Behavior

Can't get it

### Platform

```markdown
- Device model: samsung a51 128g
- CPU architecture:arm 64 
- Android version:12 
- PojavLauncher version:can't install
```

**Comment by Thollp** [comment]
https://youtu.be/gYJL4J-mwXo
Watch this whole video

**Comment by GaucovyAero** [comment]
works now
