### ISSUE TITLE
[BUG] fix incorrect mouse placement

### ISSUE THREAD

**Issue by L4wMOB** [PojavLauncherTeam/PojavLauncher#3629]
### Describe the bug

fix improper mouse placement

### The log file and images/videos

![IMG_20221101_222551](https://user-images.githubusercontent.com/116045808/199280129-78c5f9c3-1ff7-461f-a6be-19bc24e81807.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Turn on the mouse and the mouse placement doesn't match as in the picture I chose
```

### Expected Behavior

fix improper mouse placement

### Platform

```markdown
- Device model: Poco X3 Pro
- CPU architecture: Octa-core Max 2.96GHz
- Android version: 12
- PojavLauncher version: dahlia-114-f52814f0d-v3_openjdk
```

**Comment by GaucovyAero** [comment]
enable the ignore notch setting in the video and renderer tab in pojav settings

**Comment by L4wMOB** [comment]
> enable the ignore notch setting in the video and renderer tab in pojav settings

tysm <3

**Comment by Forever2397** [comment]
why pojavlauncher after the update, it's getting more and more unclear when when using the mouse it's so bad😣

**Comment by Forever2397** [comment]
> enable the ignore notch setting in the video and renderer tab in pojav settings

i wish there was a pro version of pojavlauncher i am willing to pay 10$ because this is the best MC launcher

**Comment by Mathias-Boulay** [comment]
The offset issue has been cleared a while ago now
