### ISSUE TITLE
[ERROR]Forge and Optifine System is broken

### ISSUE THREAD

**Issue by Vylesh** [PojavLauncherTeam/PojavLauncher#3630]
### Describe the bug

INFORMATION ABOUT PROBLEM :
Idk but i was downloaded game from lastest action and and game is gives this error : 
java.lang.RuntimeException: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:740)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:644)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:525)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:54)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:27)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:659)
	... 10 more

### The log file and images/videos

![Screenshot_20221102-112316_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/83465565/199439324-7c725777-93ba-4dda-9903-03655f8b3c53.jpg)

### Steps To Reproduce

```markdown
1-)Download lastest build from here
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3371778673
2-)Enter with account and enter as normal 1.19.2 game
3-)Exit game and download Optifine or forge
4-) click play button
```

### Expected Behavior

Enter the game

### Platform

```markdown
- Device model :Samsung Galaxy M31
- GPU architecture : Octa-core (4x2.3 GHz Cortex-A73 & 4x1.7 GHz Cortex-A53)
- Android Version : 12
- Pojavlauncher version: this version in this link (from action): https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3371778673:
```

### Anything else?

Idk really I hope it can be fixed asap

**Comment by Thollp** [comment]
I also got this issue. Just hope the devs will come across this issue

**Comment by wkosh** [comment]
bro in action #3997 is working normally, I'm even playing sodium with the new render, install it and it will work normally

**Comment by wkosh** [comment]
Here is the link


https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3370199705

**Comment by wkosh** [comment]
@Mathias-Boulay I'm having the same problem with the current versions, if you can solve the problem thank you
Obs:The only one that's working for me and the one above

**Comment by Vylesh** [comment]
> bro in action #3997 is working normally, I'm even playing sodium with the new render, install it and it will work normally 

Yeah ik 3998 3999 and 4000 is broken but 3997 is works well

**Comment by wkosh** [comment]
Until they release a new version that works this is the best option

**Comment by anshoo2745** [comment]
But i have this problem in #3997 so what u do next

**Comment by GaucovyAero** [comment]
> But i have this problem in #3997 so what u do next

doubt

**Comment by anshoo2745** [comment]
Really how can I fix this

**Comment by GaucovyAero** [comment]
> Really how can I fix this

use your mind and hands to uninstall pojav, delete all its data, restart your phone and download 3997

**Comment by anshoo2745** [comment]
But i have many versions installed and controls how can I save that if i can than i will do this

**Comment by GaucovyAero** [comment]
> But i have many versions installed and controls how can I save that if i can than i will do this

in that case i recommend you to back up the pojavlauncher folder

**Comment by anshoo2745** [comment]
That thing only i done ✅ before downloading this #3997 version of pojav

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
