### ISSUE TITLE
Zink crashing

### ISSUE THREAD

**Issue by Akku9446** [PojavLauncherTeam/PojavLauncher#3631]
### Describe the bug

Pls solve 

### The log file and images/videos

@
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9929872/latestlog.txt)

### Steps To Reproduce

```markdown
Start
Select Zink render
Crash
```

### Expected Behavior

I expect you solve this

### Platform

```markdown
- Device model: Redmi 9 activ
- CPU architecture:32bit
- Android version: 10
- PojavLauncher version: 
dahlia-51-cc9efa8be-v3_zink
```

### Anything else?

Pls solve this problem

**Comment by Heckervar** [comment]
You Bitch kid

**Comment by SavageTheUnicorn** [comment]
With that attitude I doubt you'll ever get proper help, kid. The version you are using is outdated as hell too.

**Comment by Akku9446l** [comment]
> With that attitude I doubt you'll ever get proper help, kid. The version you are using is outdated as hell too.

How to get the latest version

**Comment by NotAHero04** [comment]
Your GPU may not be supported in this version of Zink.

**Comment by Akku9446l** [comment]
> Your GPU may not be supported in this version of Zink.

My GPU support vulkan

**Comment by Mathias-Boulay** [comment]
Old version
