### ISSUE TITLE
Fix virgl render crashing

### ISSUE THREAD

**Issue by Akku9446** [PojavLauncherTeam/PojavLauncher#3632]
### Describe the bug

The virgl render is crashing . I tried in all versions but it's crashing

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9934588/latestlog.txt)

### Steps To Reproduce

```markdown
Start
Select virgl render
Open game
After few seconds
Crashed in to the login screen
```

### Expected Behavior

I expect you solve this

### Platform

```markdown
- Device model: Redmi 9 activ 
- CPU architecture: 32bit
- Android version: 10
- PojavLauncher version: in all versions
```

### Anything else?

Pls solve this

**Comment by Thollp** [comment]
Your phone might not supported the renderer if its not work all version, but you can still try Holy gl4es or ANGLE renderer to see if any of these will work. BTW if you wish to play Create mod, Holy gl4es is not supported this mod, only zink, virgl, ANGLE.

**Comment by Akku9446l** [comment]
> Your phone might be not support it if its not work all version, but you can still try Holy gl4es or ANGLE renderer to see if any of these will work. BTW if you wish to play Create mod, Holy gl4es is not support it.

Main problem is this VirGL: OSMesa buffer flush is DISABLED

**Comment by Thollp** [comment]
> > Your phone might be not support it if its not work all version, but you can still try Holy gl4es or ANGLE renderer to see if any of these will work. BTW if you wish to play Create mod, Holy gl4es is not support it.
> 
> Main problem is this VirGL: OSMesa buffer flush is DISABLED

May be you can ask dev about this problem

**Comment by Akku9446l** [comment]
> > > Your phone might be not support it if its not work all version, but you can still try Holy gl4es or ANGLE renderer to see if any of these will work. BTW if you wish to play Create mod, Holy gl4es is not support it.
> > 
> > Main problem is this VirGL: OSMesa buffer flush is DISABLED
> 
> May be you can ask dev about this problem

How to ask

**Comment by GaucovyAero** [comment]
virgl doesnt work on 32bit

**Comment by viratopppp** [comment]
Listen 1.16.5 optifine g8 crash in virgl render comes in log output  VirGL: OSMesa buffer flush is DISABLED the gme is being of crash

**Comment by viratopppp** [comment]
Solve now'
