### ISSUE TITLE
Angle render crashing

### ISSUE THREAD

**Issue by Akku9446** [PojavLauncherTeam/PojavLauncher#3635]
### Describe the bug

The angle render is crashing

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9938746/latestlog.txt)

### Steps To Reproduce

```markdown
Start
Select angle render
Open game
Crash
```

### Expected Behavior

I expect you solve this

### Platform

```markdown
- Device model: Redmi 9 activ
- CPU architecture: 32bit
- Android version: 10
- PojavLauncher version: 
dahlia-114-f52814f0d-v3_openjdk
```

### Anything else?

Pls solve this

**Comment by Thollp** [comment]
Ur phone might not be supported vulkan.

**Comment by GaucovyAero** [comment]
Looks like MIUI doesn't have Vulkan support. How strange. The GE8320 should support it no problem.

**Comment by wkosh** [comment]
Bro my cell phone has miui i'm playing normally, sodium and such.

**Comment by wkosh** [comment]
His cell phone is 32-bit of course it won't work, his cell phone shouldn't even support virgl

**Comment by Akku9446l** [comment]
So is there any way

**Comment by Akku9446l** [comment]
> Ur phone might not be supported vulkan.

No it support vulkan

**Comment by Akku9446l** [comment]
> Bro my cell phone has miui i'm playing normally, sodium and such.
 

Sodium and mods support for me also

**Comment by wkosh** [comment]
and why is it crashing when you just said you support sodium ;-;

**Comment by wkosh** [comment]
If it's working, just close it the problem.

**Comment by Akku9446l** [comment]
Sodium is supporting for me in holy gl4es but angle render is crashing because I want to try shaders

**Comment by Thollp** [comment]
> Sodium is supporting for me in holy gl4es but angle render is crashing because I want to try shaders

You may try virgl if zink crash. But it may cost you with bug.

**Comment by Akku9446l** [comment]
> > Sodium is supporting for me in holy gl4es but angle render is crashing because I want to try shaders
> 
> You may try virgl if zink crash. But it may cause you with bug.

I tried it but it says VirGL: OSMesa buffer flush is DISABLED!

**Comment by GaucovyAero** [comment]
> > > Sodium is supporting for me in holy gl4es but angle render is crashing because I want to try shaders
> > 
> > 
> > You may try virgl if zink crash. But it may cause you with bug.
> 
> I tried it but it says VirGL: OSMesa buffer flush is DISABLED!

virgl only works on 64bit devices

**Comment by GaucovyAero** [comment]
fixed, closing

**Comment by KaydenJR2310** [comment]
You cannot use angle renderer if your device is a 32-bit processor, Angle renderer requires a 64-bit processor for it to work properly. Plus, angke renderer only works for minecraft 1.17 up. Versions under 1.17 will crash. Hope this help :)

**Comment by KaydenJR2310** [comment]
Versions under 1.17 will crash while using angle renderer. I mean just see the name of the renderer, it says "release 1.17+, mid"
