### ISSUE TITLE
App crashes, latestlog.txt is empty

### ISSUE THREAD

**Issue by ThomasP731** [PojavLauncherTeam/PojavLauncher#3636]
### Describe the bug

After hitting play and after progress bar finishes, app returns to login screen, sometimes android tells me the app is not responding when this happens.

### The log file and images/videos

latestlog.txt has no text and is completely empty

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Log in/select account
3. Select version (i tested 1.7.10, 1.12.2, 1.17.1)
4. Play
```

### Expected Behavior

Game should launch

### Platform

```markdown
- Device model: chromebook acer c722 n20q9
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: latest one on google play, I believe it's Dhalia g play update
```

### Anything else?

I've tried allocating more/less ram, changing java within pojavlauncher, and have tried both available renderers. An older version from about a year ago worked as long as you select a different renderer than default, with the latest version both renderers do not work, and older renderers have been removed. Also I can't download older versions due to my chromebook being managed by an organization.

**Comment by ThomasP731** [comment]
Forgot to mention, renderers available on latest version are holy gl4es, virglrenderer

**Comment by MazeXP** [comment]
I'm sure it is also related to this: #3634

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
