### ISSUE TITLE
BUG pojav crash i lost my worlds forever

### ISSUE THREAD

**Issue by Pinecone6442** [PojavLauncherTeam/PojavLauncher#3638]
### Describe the bug

I click play and it crashed

### The log file and images/videos

I cant, i deleted the app with keep data and reinstall and nothing was there, so i deleted it again

### Steps To Reproduce

```markdown
1. start pojav
2. select account
3. click play
4. YOU CRASHED
```

### Expected Behavior

I expected it to run and my friend and me would play on a server

### Platform

```markdown
- Device model: Samsung A7 Lite tablet
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Newest Playstore Nov 4 2022
```

### Anything else?

im depressed now that i lost every mod, world, shader, resource pack, everything

**Comment by wkosh** [comment]
bro put the latest log, without it it is difficult

**Comment by Pinecone6442** [comment]
nvm i installed the version before and i got my mods back

**Comment by wkosh** [comment]
version #3997 is working normally

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
