### ISSUE TITLE
Minecraft doesn't start in new update.

### ISSUE THREAD

**Issue by Kolyanpetuh** [PojavLauncherTeam/PojavLauncher#3639]
### Describe the bug

After the last update on 10/28/2022, no version of the game starts, I tried almost everything, including Fabric, Forge and OptiFine. When I click "Play", it just takes me to the login page. Tried all versions of Jam and virtualization, there is a license of the game purchased from the official site.

### The log file and images/videos

There are no any errors, it just takes me to the login page.

### Steps To Reproduce

```markdown
Maybe it has something to do with a poorly installed runtime. Perhaps a separate virtualization partition should be added.
```

### Expected Behavior

I expect the game to run normally without crashes.

### Platform

```markdown
- Device model: Xiaomi Redmi Note 9 Pro
- CPU architecture: Qualcomm Snapdragon 720G
- Android version: 12L
- PojavLauncher version: dahlia-69-38218aef3-v3_openjdk
```

**Comment by origin1001** [comment]
I have same problem, same phone but dont have pro Version, i tried diff account, diff Versions too, i will go check if it work on diffrent phone

**Comment by origin1001** [comment]
Ok fixed, u need to install the Version from auctions in github not from the app store

**Comment by Kolyanpetuh** [comment]
> Ok fixed, u need to install the Version from auctions in github not from the app store 

Thank you. But it would still be better if it was fixed in App Store and Google Play.

**Comment by RoLtOn89** [comment]
Hello, I have the same problem but when I download from the auction I also does not work

**Comment by Samhere18** [comment]
> Hello, I have the same problem but when I download from the auction I also does not work

Yes

**Comment by mstudio45** [comment]
> Hello, I have the same problem but when I download from the auction I also does not work

Same

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
