### ISSUE TITLE
NEED CLIENT FOR 1.16 OR ABOVE

### ISSUE THREAD

**Issue by kaicryptx** [PojavLauncherTeam/PojavLauncher#3643]
### Is this request related to a bug?

I really get with playing with optifine and labymod can we get client for pojavlauncher plz plz plz

**Comment by kaicryptx** [comment]
Bored*

**Comment by miggythewriter** [comment]
> ### Is this request related to a bug?
> 
> I really get with playing with optifine and labymod can we get client for pojavlauncher plz plz plz
> ### Describe the request.
> 
> _No response_
> ### Anything else?
> 
> _No response_

Optifine and fabric

**Comment by kaicryptx** [comment]
I need client plz😟

**Comment by GaucovyAero** [comment]
no, there is nothing like that
