### ISSUE TITLE
[BUG] I need run 1.19.2 on PojavLauncher but it's throw "App exited with code 1."

### ISSUE THREAD

**Issue by lrsgzs** [PojavLauncherTeam/PojavLauncher#3646]
### Describe the bug

Can I run MineCraft 1.19.2 on PojavLauncher?
App exited with code 1.

### The log file and images/videos

I don't read "games" floder and logs on computer.
But I can read them on phone.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install MineCraft 1.19.2
3. Run MineCraft 1.19.2
4. Phone throw "App exited with code 1."
```

### Expected Behavior

I want run MineCraft 1.19.2 on my phone.

### Platform

```markdown
- Device model: HuaWei ATH-AL00
- CPU architecture: 8 Core 1.5 Ghz
- Android version: 5.1.1
- PojavLauncher version: 3.3.1.1
```

**Comment by GaucovyAero** [comment]
don't use 3.3.1.1 and install pojav from play store

**Comment by lrsgzs** [comment]
but I'm in china, I can't use play store on my phone.
