### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Bhaveshnoob** [PojavLauncherTeam/PojavLauncher#3647]
### Describe the bug

When games lauch means minecraft launches its crash and throw to the home screen 

### The log file and images/videos

It's crash plz solve it

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

The game lauch and it's crash 

### Platform

```markdown
- Device model: RealmeC25y 
- CPU architecture: 2x ARM Cortex-A75 @ 1.82 GHz 6x ARM Cortex-A55 @ 1.82 GHz
- Android version: 11
- PojavLauncher version: dahlia-69-38218aef3-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
use dahlia-114 (android ci no. 3997) from github actions instead

**Comment by Bhaveshnoob** [comment]
How to use dahila 114

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
