### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3648]
### Describe the bug

Device- Realme note 9 pro
Country- India

Hello,
This bug wasn't happening though I've been using this phone since I bought it. I have been using pojavlauncher and it has been working properly. But just before like 2-3 days ago, it stopped working! I mean the problems are: 1) When I click on my minecraft account The launcher instantly starts without loading from 1-6. 2) After that when I click on any version and tap play the black screen appears and the game gets exited without any reason or any code. 3) No news feed, lag feed appearing. Instead it shows No news to show and no lag detected.

Basically I can't login and play the game and I'm unable to do anything. On the other hand, I had one debug version which is working properly.

I deleted the app then again downloaded from playstore and during that the game files were also deleted and again I downloaded them.
Still nothing is working.

### The log file and images/videos

![Screenshot_2022-11-07-17-25-13-81_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/116268548/200306462-504d09ae-bd1e-4fda-875e-af4b2cc0c737.jpg)
This is the image where morning is appearing

### Steps To Reproduce

```markdown
1. Start Pojavlauncher.
2. Select your account. (It would not load from 1-6)
3. Click on any version and tap play. (The game will not start)

That's exactly the bug!
```

### Expected Behavior

I expected to load while login with my premium account and expected to launch the game without any issues.

### Platform

```markdown
- Device model: Resmi note 9 pro
- CPU architecture: Arm Cortex A78
- Android version: 12
- PojavLauncher version: latest
```

**Comment by kikler69** [comment]
same

**Comment by GaucovyAero** [comment]
you guys gotta upgrade to dahlia-114 (android ci 3997 in github actions tab)

**Comment by ghost** [comment]
> you guys gotta upgrade to dahlia-114 (android ci 3997 in github actions tab)

But what about the official version?

**Comment by GaucovyAero** [comment]
> > you guys gotta upgrade to dahlia-114 (android ci 3997 in github actions tab)
> 
> But what about the official version?

its broken for now xD

**Comment by wkosh** [comment]
> > vocês precisam atualizar para dahlia-114 (android ci 3997 na guia de ações do github)
> 
> Mas e a versão oficial?

if it's on github of course it is hahaha, #3997 is the only one that works for now.

**Comment by ghost** [comment]
> > > vocês precisam atualizar para dahlia-114 (android ci 3997 na guia de ações do github)
> > 
> > Mas e a versão oficial?
> 
> if it's on github of course it is hahaha, #3997 is the only one that works for now.

So the latest gplay update don't work?

**Comment by Piment200** [comment]
> vous devez passer à dahlia-114 (android ci 3997 dans l'onglet actions github)

And how did you do that ?

**Comment by WaylakeAnimations** [comment]
> you guys gotta upgrade to dahlia-114 (android ci 3997 in github actions tab)

yep i actually tried the version and things actually works just fine

**Comment by AGENTISNUM1** [comment]
I have the same issue. When will it be fixed?

**Comment by wkosh** [comment]
> Eu tenho o mesmo problema. Quando será corrigido?

brother please use Android CI #3997 for now because no one knows when it will be fixed just be patient

**Comment by AGENTISNUM1** [comment]
Im on chromebook so RIP

**Comment by ghost** [comment]
> > Eu tenho o mesmo problema. Quando será corrigido?
> 
> brother please use Android CI #3997 for now because no one knows when it will be fixed just be patient 

So nobody can use the gplay update?

**Comment by AGENTISNUM1** [comment]
not me

**Comment by AGENTISNUM1** [comment]
I hate to do this but do the devs have any idea over when the google play fixed version will release? Will it be a few days, weeks, or (hopefully not) months? again, sorry for asking.

**Comment by ghost** [comment]
> I hate to do this but do the devs have any idea over when the google play fixed version will release? Will it be a few days, weeks, or (hopefully not) months? again, sorry for asking.

Same question 😥

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
