### ISSUE TITLE
[BUG] Game not launching

### ISSUE THREAD

**Issue by Rjjeje** [PojavLauncherTeam/PojavLauncher#3649]
### Describe the bug

As I start launcher I login my acc it's fine when I click on Olay on 1.16.5 it is fine but when it's time for the game to start it crashes plsss tell me it's been like 1 year of me using it I can't live without it :( pleaseeee I really want to play games back it is started to happen with me from today only and while selecting acc it doesn't even show from 1 to 6

### The log file and images/videos

https://user-images.githubusercontent.com/117739600/200571689-8487b59a-073b-435b-80cb-d65ce2977d33.mp4

### Steps To Reproduce

```markdown
I start launcher and it crashes
```

### Expected Behavior

I expect game to start but it doesn't 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Wase fix it :( I beg

**Comment by GaucovyAero** [comment]
use android ci no. 3997 instead please
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3370199705

**Comment by Rjjeje** [comment]
Hlo pls tell how to download the new app or version Idk how to downalod or use it can u help me :)pls

**Comment by Rjjeje** [comment]
Hello uhhhh sooooo in the action s tab 3997 what to do I mean how to
install the new version or app what to click Idk how to install or how to
download the file pls tell me how to use the thing in actions tab 3997
thanks I hope u reply fast I'm impatient to use app :)

**Comment by GaucovyAero** [comment]
click on actions, find android ci 3997, click on it and then download app-debug

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
