### ISSUE TITLE
Can't login on Addicted2 server. 

### ISSUE THREAD

**Issue by ThomasBotizan** [PojavLauncherTeam/PojavLauncher#365]
When I try to login I type my credentials and nothing happens. What to do. They kick me out for inactivity.

**Comment by khanhduytran0** [comment]
Well, this launcher does not auto login for you. Click login to next.

**Comment by ThomasBotizan** [comment]
Well I type /login password
But nothing

**Comment by LuNeTiStU96** [comment]
But nothing

**Comment by khanhduytran0** [comment]
Use Gboard instead.

**Comment by ThomasBotizan** [comment]
I use softkey

**Comment by khanhduytran0** [comment]
Try type on Gboard https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin

**Comment by ThomasBotizan** [comment]
My phone doesn't have GMS. So I can't use Google play or other Google apps

Huawei P40 lite

**Comment by khanhduytran0** [comment]
Oh... You may try hacker keyboard at https://github.com/klausw/hackerskeyboard/releases/tag/1.40.7

**Comment by khanhduytran0** [comment]
(also try it)
