### ISSUE TITLE
[BUG] Not launching the game

### ISSUE THREAD

**Issue by Mahipal2007** [PojavLauncherTeam/PojavLauncher#3650]
### Describe the bug

Pojavlauncher isn't launching the game it just prepare for launching and when it time to launch it just go back to the login screen and i tried reinstalling and launched 1.8.9 clean but it still goes back to the login screen

### The log file and images/videos

[Screenrecording_20221108_221100.mp4.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/9963377/Screenrecording_20221108_221100.mp4.zip)
Extract this file it has the video

### Steps To Reproduce

```markdown
1. Launch Pojavlauncher
2. Play 1.8.9
3. Launch
4. It prepares for launching 
5. Goes back to log in screen
```

### Expected Behavior

I expect game to Launch 

### Platform

```markdown
- Device model: Vivo v23 5g
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest release
```

### Anything else?

Nope

**Comment by GaucovyAero** [comment]
go to github actions and download android ci no. 3997

**Comment by bilalRaad244** [comment]
same issue

**Comment by Mahipal2007** [comment]
Will that fix it and where do I have to put it

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
