### ISSUE TITLE
[BUG] GAME CRASHA AS SOON AS I START OPTIFINE, FABRIC

### ISSUE THREAD

**Issue by wkosh** [PojavLauncherTeam/PojavLauncher#3651]
### Describe the bug

the Bug is the following, I put my account, install the desired version, start OPTIFINE and crash 

### The log file and images/videos

![Screenshot_2022-11-09-23-52-08-185_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/94086290/200989247-d14e80ff-430a-470c-8313-8c4eaa7c5772.jpg)

### Steps To Reproduce

```markdown
1-Start Pojav
2_install OPTIFINE 
3_Start OPTIFINE 
4_game does not enter
```

### Expected Behavior

Nothing to say, just sort it out 

### Platform

```markdown
- Device model: Redmi Note 11 
- CPU architecture: Snapdragon 680
- Android version: 12
- PojavLauncher version: Experimental ui
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
use actions build 3997 instead

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
