### ISSUE TITLE
Custom control visual bugs in new update.

### ISSUE THREAD

**Issue by Kolyanpetuh** [PojavLauncherTeam/PojavLauncher#3652]
### Describe the bug

In the latest release 10.11.2022 I faced serious issue with custom game control.

### The log file and images/videos

https://user-images.githubusercontent.com/87006679/200998671-837d8c5d-1c6f-4d92-a6c5-66e68c21293f.mp4

### Steps To Reproduce

```markdown
I think it happens because of updating UI of the program.
```

### Expected Behavior

I expect UI to work normally without glitches.

### Platform

```markdown
- Device model: Xiaomi Redmi Note 9 Pro
- CPU architecture: Qualcomm Snapdragon 720G
- Android version: 10L
- PojavLauncher version: VUI fixes & improvements pt. 1 (https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3431258633)
```

**Comment by artdeell** [comment]
It literally says in the branch name that it's experimental. Don't want bugs? Don't use anything that literally says that it's experimental.
By the way, what happens when the Mojang logo appears?

**Comment by Kolyanpetuh** [comment]
> It literally says in the branch name that it's experimental. Don't want bugs? Don't use anything that literally says that it's experimental. By the way, what happens when the Mojang logo appears?

You misunderstood me. I'm not saying I don't want bugs. I'm just pointing out one of the bugs for feedback so you'll know about it and fix it.

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
