### ISSUE TITLE
Google Play Store version not working

### ISSUE THREAD

**Issue by Akos20189** [PojavLauncherTeam/PojavLauncher#3653]
### Describe the bug

When I tap play it start to kinda load and then it just switches to account selector

### The log file and images/videos

I cant send photo it doesn't let me

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Select account
3.Tap start 
4.It says prepairing resources
5.Grey screen
6.Back to account selector
```

### Expected Behavior

I expected the game to start normaly when I pressed play.

### Platform

```markdown
- Device model: Redmi 9
- CPU architecture: Octa-core Max2ghz
- Android version: 11
- PojavLauncher version: Latest on Google Play store
```

**Comment by GaucovyAero** [comment]
yes this is normal, use build 3997 here on github actions instead

**Comment by lilkorio** [comment]
> yes this is normal, use build 3997 here on github actions instead

Where would you find build 3997 and how do you use it I've been looking everywhere for it (sorry about this idk much about coding)

**Comment by Zakaii12** [comment]
> yes this is normal, use build 3997 here on github actions instead

Can you post the link?

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
