### ISSUE TITLE
[Bug] 无法以自定义参数启动jar安装器

### ISSUE THREAD

**Issue by hyplant** [PojavLauncherTeam/PojavLauncher#3658]
### Is this request related to a bug?

无法以自定义参数启动jar安装器

### Describe the request.

无法以自定义参数启动jar安装器，以前可长按启动，现在不行了

### Anything else?

dahlia-140-6dfb301d4-experimental_ui

**Comment by artdeell** [comment]
First of all, wrong template
Second of all, why did you even need this option? It was broken for a very long time due to no access to external storage, and (at least to my knowledge) nobody used it for much so idk.

**Comment by hyplant** [comment]
内部存储/android/data/net.kdt.pojavlaunch.debug还是可以访问的，即使没有管理所有文件权限。
另外，如果这个安装器不能使用，可以在选择文件后弹出一个输入框，允许输出额外的启动参数

**Comment by hyplant** [comment]
> First of all, wrong template
> Second of all, why did you even need this option? It was broken for a very long time due to no access to external storage, and (at least to my knowledge) nobody used it for much so idk.

已关闭提议并重新使用正确的模板提交
