### ISSUE TITLE
[BUG] When try to start the game it's sending back to login screen

### ISSUE THREAD

**Issue by Zakaii12** [PojavLauncherTeam/PojavLauncher#3659]
### Describe the bug

When i try start the game it's always send me back to log in screen 

### The log file and images/videos

Uploading Proyek Baru 111 [D41E180].mp4…

### Steps To Reproduce

```markdown
Step in the video
```

### Expected Behavior

The game running normally 

### Platform

```markdown
- Device model: CPH2251 (CPH2251T2)
- CPU architecture:  6× ARM cortex A-55 @2,00 GHz and 2× ARM cortex A-78 @2,40 GHz
- Android version: 12
- PojavLauncher version: lastest from i send the bug report now
```

### Anything else?

Hopefully this fixed as soon as possible :)

**Comment by FXgraphing** [comment]
I have the same issue, and i know like nothing about code but try a v3 build they don't crash, maybe a bit newer build but not sure

**Comment by GaucovyAero** [comment]
update to the latest play store build
