### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by AGENTISNUM1** [PojavLauncherTeam/PojavLauncher#3661]
### Describe the bug

When i try to launch the google play version, it freezes, and then goes back to login

### The log file and images/videos

there is no log

### Steps To Reproduce

```markdown
1. start pojav
2. run any version of the game
3. crash
```

### Expected Behavior

I expect the game to load and work.

### Platform

```markdown
- Device model: lenovo chromebook
- CPU architecture: 
- Android version: 
- PojavLauncher version: gplay
```

**Comment by AGENTISNUM1** [comment]
I am on chromebook so i cant use the latest github apk. pls fix

**Comment by slaygirlz** [comment]
> I am on chromebook so i cant use the latest github apk. pls fix

you have to turn on developer mode on make sure your school allows doing it so

**Comment by AGENTISNUM1** [comment]
this has been fixed

**Comment by AGENTISNUM1** [comment]
> > I am on chromebook so i cant use the latest github apk. pls fix
> 
> you have to turn on developer mode on make sure your school allows doing it so

im not wiping my chromebook.
