### ISSUE TITLE
[BUG] <Short description>Game not launching

### ISSUE THREAD

**Issue by Bluezmyth** [PojavLauncherTeam/PojavLauncher#3662]
### Describe the bug

i press green button to launch and it returns to sign in screen

### The log file and images/videos

https://user-images.githubusercontent.com/118066287/201482763-8e765b51-3654-46a0-8951-3c6e6d1c3124.mp4

### Steps To Reproduce

```markdown
start game
login
press launch
sent back to signin screen
```

### Expected Behavior

i expect the game to work

### Platform

```markdown
- Device model: Vivo v15 pro
- CPU architecture: good
- Android version: latest
- PojavLauncher version: playstore latest version
```

### Anything else?

fix this fast dude

**Comment by GaucovyAero** [comment]
update to the latest play store build
