### ISSUE TITLE
[BUG] Core mods are present error

### ISSUE THREAD

**Issue by anshoo2745** [PojavLauncherTeam/PojavLauncher#3663]
### Describe the bug

Honestly I don't know 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9995547/latestlog.txt)

### Steps To Reproduce

```markdown
You can't do with my mods i am using
```

### Expected Behavior

The game would open

### Platform

```markdown
- Device model: Realme Narzo 20
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: actions #3997
```

### Anything else?

Nope

**Comment by GaucovyAero** [comment]
remove skyblockaddons, because it uses discordrpc or ipc

**Comment by anshoo2745** [comment]
But in my other snapdragon phone it works well

**Comment by anshoo2745** [comment]
> remove skyblockaddons, because it uses discordrpc or ipc

Umm bro but the skyblock addon is the main thing what can I do for other thing

**Comment by GaucovyAero** [comment]
> > remove skyblockaddons, because it uses discordrpc or ipc
> 
> Umm bro but the skyblock addon is the main thing what can I do for other thing

i think you cannot do anything to fix it

**Comment by GaucovyAero** [comment]
or try messing with its config in .minecraft/config/skyblockaddons.cfg

**Comment by anshoo2745** [comment]
> or try messing with its config in .minecraft/config/skyblockaddons.cfg

But i don't have any type of name of this thing 
![Screenshot_2022-11-12-23-37-14-41_db51e592e420a9871f4a37915a68789b](https://user-images.githubusercontent.com/91818648/201488534-cd0b9ebd-5511-4f5b-ad79-5e64340d59a0.jpg)

**Comment by anshoo2745** [comment]
@GaucovyAero bro can you tell me what is that
![Screenshot_2022-11-13-13-19-03-98_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/91818648/201511700-ba877570-b963-403d-aea5-4dbe223673b1.jpg)

**Comment by GaucovyAero** [comment]
just do what it says you to

**Comment by anshoo2745** [comment]
What it said can u tell me in detail

> just do what it says you to

**Comment by GaucovyAero** [comment]
> What it said can u tell me in detail
> 
> > just do what it says you to

i mean its in the solution written just there, its not possible to simplify it

**Comment by anshoo2745** [comment]
If you could can you tell me what is written because i don't know what
written please

**Comment by GaucovyAero** [comment]
> 

i cant
