### ISSUE TITLE
[BUG] Angle Vulkan Does Not Start/Works 

### ISSUE THREAD

**Issue by wkosh** [PojavLauncherTeam/PojavLauncher#3664]
### Describe the bug

just doesn't start angle Vulkan, v

### The log file and images/videos

there is not

### Steps To Reproduce

```markdown
1.Start Pojavlauncher 
2.I enter the version
3.Start with Gles even with vulkan
```

### Expected Behavior

No

### Platform

```markdown
- Device model: Redmi Note 11 
- CPU architecture: Snapdragon 680
- Android version: 12
- PojavLauncher version: latest version released on github
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by LoranGold** [comment]
[Uploading latestlog.txt…]()

**Comment by wkosh** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9995816/latestlog.txt)

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9995816/latestlog.txt)

you sent a log with virgl that started up just fine

**Comment by GaucovyAero** [comment]
send a log with angle instead

**Comment by wkosh** [comment]
so i started with angle 
![Screenshot_2022-11-12-17-09-28-431_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/94086290/201492659-312c4158-460d-4db8-9fe5-e8a1eb752577.jpg)

**Comment by wkosh** [comment]
![Screenshot_2022-11-12-17-07-27-290_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/94086290/201492673-2512531e-b03e-4171-84fc-94ac49aa95b1.jpg)
It appears to me that it started with Gles 2.1.0

**Comment by wkosh** [comment]
I will send again
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9995844/latestlog.txt)

**Comment by GaucovyAero** [comment]
`Added custom env: POJAV_RENDERER=opengles3_desktopgl_angle_vulkan` it started with angle, i know it says gl4es but i think it still should be running angle

**Comment by wkosh** [comment]
vulkan does not work, gles 2.1 appears and does not start sodium, shaders, that is, vulkan is totally broken

**Comment by GaucovyAero** [comment]
> vulkan does not work, gles 2.1 appears and does not start sodium, shaders, that is, vulkan is totally broken

of course it doesnt start sodium when sodium only works on opengl 3.2 or higher

**Comment by artdeell** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3452614882

**Comment by wkosh** [comment]
Thanks

**Comment by wkosh** [comment]
nothing to talk

**Comment by wkosh** [comment]
> > vulkan does not work, gles 2.1 appears and does not start sodium, shaders, that is, vulkan is totally broken
> 
> of course it doesnt start sodium when sodium only works on opengl 3.2 or higher

a question, does vulkan work shaders?

**Comment by GaucovyAero** [comment]
> > > vulkan does not work, gles 2.1 appears and does not start sodium, shaders, that is, vulkan is totally broken
> > 
> > 
> > of course it doesnt start sodium when sodium only works on opengl 3.2 or higher
> 
> a question, does vulkan work shaders?

no
