### ISSUE TITLE
[BUG] Can't access files

### ISSUE THREAD

**Issue by jasondyoungberg** [PojavLauncherTeam/PojavLauncher#3666]
### Describe the bug

If I try to go to `/Android/data`, nothing is there.

### The log file and images/videos

![Screenshot_20221113-012212](https://user-images.githubusercontent.com/71162172/201512662-a51df9c8-173f-46f4-ba02-b10f0741b70a.png)

### Steps To Reproduce

```markdown
1. Open `/Android/data`
2. Nothing is there
```

### Expected Behavior

`/Android/data/net.kdt.pojavlaunch.launch/files/` should exist

### Platform

```markdown
- Device model: Google Pixel 6
- CPU architecture: idk
- Android version: 13
- PojavLauncher version: dahlia-114-f52814f0d-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use MiXplorer
