### ISSUE TITLE
[BUG] Fix Angle Renderer 

### ISSUE THREAD

**Issue by Jazlenkate** [PojavLauncherTeam/PojavLauncher#3667]
### Describe the bug

Game exited with code-1 when using Angle Renderer 

### The log file and images/videos

![Screenshot_2022-11-13-18-17-52-47_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/94172298/201516833-97fdb15d-03a5-4edc-8c72-1f8785b95f5b.jpg)

### Steps To Reproduce

```markdown
Fix Angle Renderer
```

### Expected Behavior

I expect to play with shaders

### Platform

```markdown
- Device model: Relame C11
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version:
```

### Anything else?

Please Fix the angle renderer

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by Jazlenkate** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9999624/latestlog.txt)
@GaucovyAero

**Comment by GaucovyAero** [comment]
idk, on some phones it works, on some it doesnt
