### ISSUE TITLE
[BUG] Game didn't launch with no log output

### ISSUE THREAD

**Issue by kl1024** [PojavLauncherTeam/PojavLauncher#3668]
### Describe the bug

I tried to start 1.19.2 but it stuck in blackscreen with no log output.
And there's nothing appeared in latastlog.txt.

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-147-d33e95346-experimental_ui
Info: LWJGL3 directory: [version, lwjgl-glfw-classes.jar]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19.2

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start 1.19.2
3. Nothing appeared but blackscreen
4. Nothing appeared in log output
```

### Expected Behavior

I expected the game run normally

### Platform

```markdown
- Device model: Redmi 10X
- CPU architecture: arm64-v8a
- Android version: 12
- PojavLauncher version: dahlia-147
```

**Comment by kl1024** [comment]
I can't upload latestlog.txt so I copied the contents inside.

Maybe java didn't launched?

**Comment by artdeell** [comment]
No, even if java didn't start up it should have put out a bunch of lines about loading libraries

**Comment by kl1024** [comment]
> No, even if java didn't start up it should have put out a bunch of lines about loading libraries

![image](https://user-images.githubusercontent.com/57281140/201520236-c34f3372-3d76-4e12-af15-bc5ce8aefcc6.png)

**Comment by artdeell** [comment]
Can you check logcat?

**Comment by kl1024** [comment]
![Screenshot_2022-11-13-19-53-58-272_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/57281140/201520336-0647c0f2-753f-41b4-a3fe-2a6f7401e7a1.jpg)

**Comment by artdeell** [comment]
That is normal since the launcher doesn't draw anything before the first frame of the game

**Comment by kl1024** [comment]
Like this? I'm feeling sorry to put them as text but I couldn't upload them as a .txt file.

--------- beginning of main
11-13 20:20:56.679  3770  3770 I libc    : SetHeapTaggingLevel: tag level set to 0
11-13 20:20:56.684  3770  3770 I .debug:launche: Late-enabling -Xcheck:jni
11-13 20:20:56.704  3770  3770 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
11-13 20:20:56.707  3770  3770 I MessageMonitor: Load libmiui_runtime
11-13 20:20:56.723  3770  3799 D AppScoutStateMachine: 3770-ScoutStateMachinecreated
11-13 20:20:56.733  3770  3770 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10016; state: ENABLED
11-13 20:20:56.845  3770  3770 V GraphicsEnvironment: ANGLE Developer option for 'net.kdt.pojavlaunch.debug' set to: 'default'
11-13 20:20:56.845  3770  3770 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
--------- beginning of system
11-13 20:20:56.847  3770  3770 I ForceDarkHelperStubImpl: initialize for net.kdt.pojavlaunch.debug , ForceDarkOrigin
11-13 20:20:56.848  3770  3770 D OpenGLRenderer: JNI_OnLoad success
11-13 20:20:56.848  3770  3770 I MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
11-13 20:20:56.850  3770  3770 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-13 20:20:56.850  3770  3770 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-13 20:20:56.872  3770  3770 I Environ : No environ found, creating...
11-13 20:20:56.872  3770  3770 I Environ : 0x7b1f5cc860
11-13 20:20:56.873  3770  3770 I jrelog  : dlopen libxhook.so success
11-13 20:20:56.884  3770  3805 I UnpackPrep: caciocavallo: Pack is up-to-date with the launcher, continuing...
11-13 20:20:56.884  3770  3805 I UnpackPrep: caciocavallo17: Pack is up-to-date with the launcher, continuing...
11-13 20:20:56.885  3770  3805 I UnpackPrep: lwjgl3: Pack is up-to-date with the launcher, continuing...
11-13 20:20:56.885  3770  3805 I UnpackPrep: security: Pack is up-to-date with the launcher, continuing...
11-13 20:20:56.888  3770  3811 D libMEOW : meow new tls: 0x7acb177700
11-13 20:20:56.889  3770  3811 D libMEOW : meow reload base cfg path: na
11-13 20:20:56.889  3770  3811 D libMEOW : meow reload overlay cfg path: na
11-13 20:20:56.889  3770  3811 D libMEOW : applied 0 plugin for [net.kdt.pojavlaunch.debug:launcher].
11-13 20:20:56.889  3770  3811 D libMEOW : meow delete tls: 0x7acb177700
11-13 20:20:56.928  3770  3770 D ViewScrollStubImpl: the value of mScrollFrictionRes is: 0.015
11-13 20:20:56.934  3770  3770 D MiuiMultiWindowUtils: freeform resolution args raw data:{  "zizhan":{    "freeform_args": {      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}}    },    "mini_freeform_args":{      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.165},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.165}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.293},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.293}}    }  },  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":0.125,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":-1,"left_margin":0.0714},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":0.125,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":-1,"left_margin":0.0714}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "vertical_landscape":{"aspect_ratio":-1, "original_ratio":0.144},        "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":0.144}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":1,"original_scale":0.7182,"top_margin":0.142,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.8, "original_ratio":1,"original_scale":0.7182,"top_margin":-1,"left_margin":0.05},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":0.142,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":-1,"left_margin":0.05}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "vertical_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3},        "horizontal_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio
11-13 20:20:56.937  3770  3770 W System.err: org.json.JSONException: No value for bomb
11-13 20:20:56.937  3770  3770 W System.err: 	at org.json.JSONObject.get(JSONObject.java:403)
11-13 20:20:56.937  3770  3770 W System.err: 	at org.json.JSONObject.getJSONObject(JSONObject.java:623)
11-13 20:20:56.937  3770  3770 W System.err: 	at android.util.MiuiMultiWindowUtils.initFreeFormResolutionArgsOfDevice(MiuiMultiWindowUtils.java:1436)
11-13 20:20:56.937  3770  3770 W System.err: 	at android.util.MiuiMultiWindowUtils.initFreeFormResolutionArgs(MiuiMultiWindowUtils.java:1430)
11-13 20:20:56.937  3770  3770 W System.err: 	at android.util.MiuiMultiWindowUtils.<clinit>(MiuiMultiWindowUtils.java:212)
11-13 20:20:56.937  3770  3770 W System.err: 	at android.util.MiuiMultiWindowUtils.isSupportMultiSwitchFeature(MiuiMultiWindowUtils.java:3300)
11-13 20:20:56.937  3770  3770 W System.err: 	at com.android.internal.policy.DecorViewMultiWinStubImpl.<init>(DecorViewMultiWinStubImpl.java:19)
11-13 20:20:56.937  3770  3770 W System.err: 	at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider.provideNewInstance(DecorViewMultiWinStubImpl$Provider.java:14)
11-13 20:20:56.937  3770  3770 W System.err: 	at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider.provideNewInstance(DecorViewMultiWinStubImpl$Provider.java:8)
11-13 20:20:56.937  3770  3770 W System.err: 	at com.miui.base.MiuiStubRegistry.get(MiuiStubRegistry.java:129)
11-13 20:20:56.938  3770  3770 W System.err: 	at com.miui.base.MiuiStubUtil.newInstance(MiuiStubUtil.java:77)
11-13 20:20:56.938  3770  3770 W System.err: 	at com.android.internal.policy.DecorViewMultiWinStub.newInstance(DecorViewMultiWinStub.java:11)
11-13 20:20:56.938  3770  3770 W System.err: 	at com.android.internal.policy.DecorView.<init>(DecorView.java:335)
11-13 20:20:56.938  3770  3770 W System.err: 	at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2380)
11-13 20:20:56.938  3770  3770 W System.err: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2760)
11-13 20:20:56.938  3770  3770 W System.err: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2140)
11-13 20:20:56.938  3770  3770 W System.err: 	at net.kdt.pojavlaunch.Tools.setFullscreen(Tools.java:502)
11-13 20:20:56.938  3770  3770 W System.err: 	at net.kdt.pojavlaunch.BaseActivity.onCreate(BaseActivity.java:15)
11-13 20:20:56.938  3770  3770 W System.err: 	at net.kdt.pojavlaunch.LauncherActivity.onCreate(LauncherActivity.java:154)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.Activity.performCreate(Activity.java:8176)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.Activity.performCreate(Activity.java:8143)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3753)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3947)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.os.Looper.loopOnce(Looper.java:210)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.os.Looper.loop(Looper.java:299)
11-13 20:20:56.938  3770  3770 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8274)
11-13 20:20:56.938  3770  3770 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-13 20:20:56.938  3770  3770 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
11-13 20:20:56.939  3770  3770 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
11-13 20:20:56.939  3770  3770 D IS_CTS_MODE: false
11-13 20:20:56.939  3770  3770 D MULTI_WINDOW_SWITCH_ENABLED: false
11-13 20:20:56.939  3770  3770 D IS_CTS_MODE: false
11-13 20:20:56.939  3770  3770 D MULTI_WINDOW_SWITCH_ENABLED: false
11-13 20:20:56.943  3770  3770 D DecorView[]: getWindowModeFromSystem  windowmode is 1
11-13 20:20:56.950  3770  3812 D ViewContentFactory: initViewContentFetcherClass
11-13 20:20:56.950  3770  3812 D ViewContentFactory: getInterceptorPackageInfo
11-13 20:20:56.951  3770  3812 D ViewContentFactory: getInitialApplication took 1ms
11-13 20:20:56.951  3770  3812 D ViewContentFactory: packageInfo.packageName: com.miui.catcherpatch
11-13 20:20:56.958  3770  3812 D ViewContentFactory: initViewContentFetcherClass took 8ms
11-13 20:20:56.958  3770  3812 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
11-13 20:20:56.958  3770  3812 D ViewContentFactory: createInterceptor took 8ms
11-13 20:20:56.959  3770  3770 W .debug:launche: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
11-13 20:20:56.960  3770  3770 W .debug:launche: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
11-13 20:20:57.110  3770  3770 I IconParser: Unsupported icon: null
11-13 20:20:57.140  3770  3770 I SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@96e1621
11-13 20:20:57.142  3770  3770 E MsyncFactory: [static] ClassNotFoundException
11-13 20:20:57.142  3770  3770 E MsyncFactory: java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at java.lang.Class.classForName(Native Method)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at java.lang.Class.forName(Class.java:454)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at java.lang.Class.forName(Class.java:379)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at com.mediatek.view.MsyncFactory.<clinit>(MsyncFactory.java:14)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at com.mediatek.view.MsyncFactory.getInstance(MsyncFactory.java:29)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:761)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:857)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:393)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5012)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.os.Looper.loopOnce(Looper.java:210)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.os.Looper.loop(Looper.java:299)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at android.app.ActivityThread.main(ActivityThread.java:8274)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at java.lang.reflect.Method.invoke(Native Method)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
11-13 20:20:57.142  3770  3770 E MsyncFactory: Caused by: java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at java.lang.Class.classForName(Native Method)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1358)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1418)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-13 20:20:57.142  3770  3770 E MsyncFactory: 	... 22 more
11-13 20:20:57.142  3770  3770 E MsyncFactory: Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-13 20:20:57.142  3770  3770 I MsyncFactory: [static] sMsyncFactory = com.mediatek.view.MsyncFactory@674f35d
11-13 20:20:57.149  3770  3770 D ViewRootImpl[LauncherActivity]: hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
11-13 20:20:57.151  3770  3770 D DecorView[]: getWindowModeFromSystem  windowmode is 1
11-13 20:20:57.151  3770  3770 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
11-13 20:20:57.156  3770  3770 D libMEOW : meow new tls: 0x7acb39e340
11-13 20:20:57.156  3770  3770 D libMEOW : applied 0 plugin for [net.kdt.pojavlaunch.debug:launcher].
11-13 20:20:57.158  3770  3770 W Looper  : PerfMonitor looperActivity : package=net.kdt.pojavlaunch.debug/net.kdt.pojavlaunch.LauncherActivity time=1ms latency=436ms running=0ms  procState=-1  historyMsgCount=4 (msgIndex=3 wall=152ms seq=3 running=139ms late=14ms h=android.app.ActivityThread$H w=110) (msgIndex=4 wall=272ms seq=4 running=247ms runnable=1ms late=164ms h=android.app.ActivityThread$H w=159)
11-13 20:20:57.224  3770  3770 I BufferQueueConsumer: [](id:eba00000000,api:0,p:-1,c:3770) connect: controlledByApp=false
11-13 20:20:57.225  3770  3770 I BLASTBufferQueue: [ViewRootImpl[LauncherActivity]#0] constructor()
11-13 20:20:57.228  3770  3807 D libMEOW : meow new tls: 0x7b2ead85c0
11-13 20:20:57.228  3770  3807 D libMEOW : applied 0 plugin for [net.kdt.pojavlaunch.debug:launcher].
11-13 20:20:57.232  3770  3807 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
11-13 20:20:57.244  3770  3807 I BufferQueueProducer: [ViewRootImpl[LauncherActivity]#0(BLAST Consumer)0](id:eba00000000,api:1,p:3770,c:3770) connect: api=1 producerControlledByApp=true
11-13 20:20:57.248  3770  3837 E ion     : ioctl c0044901 failed with code -1: Invalid argument
11-13 20:20:57.256  3770  3807 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
11-13 20:20:57.275  3770  3807 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
11-13 20:20:57.275  3770  3807 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
11-13 20:20:57.293  3770  3770 D DecorView[]: onWindowFocusChanged hasWindowFocus true
11-13 20:20:58.725  3770  3796 W System  : A resource failed to call close. 
11-13 20:20:58.725  3770  3796 W System  : A resource failed to call close. 
11-13 20:20:58.725  3770  3796 W System  : A resource failed to call close. 
11-13 20:20:58.725  3770  3796 W System  : A resource failed to call close. 
11-13 20:20:58.725  3770  3796 W System  : A resource failed to call close. 
11-13 20:20:58.726  3770  3796 W System  : A resource failed to call close. 
11-13 20:20:58.727  3770  3796 W System  : A resource failed to call close. 
11-13 20:20:58.727  3770  3796 W System  : A resource failed to call close. 
11-13 20:21:26.793  3770  3807 I BufferQueueProducer: [ViewRootImpl[LauncherActivity]#0(BLAST Consumer)0](id:eba00000000,api:1,p:3770,c:3770) disconnect: api 1
11-13 20:21:26.795  3770  3807 I BLASTBufferQueue: [ViewRootImpl[LauncherActivity]#0] destructor()
11-13 20:21:26.795  3770  3807 I BufferQueueConsumer: [ViewRootImpl[LauncherActivity]#0(BLAST Consumer)0](id:eba00000000,api:0,p:-1,c:3770) disconnect
11-13 20:21:26.962  3770  3770 D DecorView[]: onWindowFocusChanged hasWindowFocus false
11-13 20:21:27.620  3770  3799 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:16192026705923 framenumber:9 blastBufferQueue is dead
--------- beginning of main
11-13 12:22:40.123 +0000  3770  4658 D AppScoutStateMachine: 3770-ScoutStateMachinecreated
11-13 12:22:40.153 +0000  3770  3770 D DecorView[]: getWindowModeFromSystem  windowmode is 1
11-13 12:22:40.153 +0000  3770  3770 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
11-13 12:22:40.158 +0000  3770  3770 I BufferQueueConsumer: [](id:eba00000001,api:0,p:-1,c:3770) connect: controlledByApp=false
11-13 12:22:40.158 +0000  3770  3770 I BLASTBufferQueue: [ViewRootImpl[LauncherActivity]#1] constructor()
11-13 12:22:40.159 +0000  3770  3807 I BufferQueueProducer: [ViewRootImpl[LauncherActivity]#1(BLAST Consumer)1](id:eba00000001,api:1,p:3770,c:3770) connect: api=1 producerControlledByApp=true
11-13 12:22:40.224 +0000  3770  3770 D DecorView[]: onWindowFocusChanged hasWindowFocus true
11-13 12:23:10.085 +0000  3770  3807 I BufferQueueProducer: [ViewRootImpl[LauncherActivity]#1(BLAST Consumer)1](id:eba00000001,api:1,p:3770,c:3770) disconnect: api 1
11-13 12:23:10.088 +0000  3770  3807 I BLASTBufferQueue: [ViewRootImpl[LauncherActivity]#1] destructor()
11-13 12:23:10.088 +0000  3770  3807 I BufferQueueConsumer: [ViewRootImpl[LauncherActivity]#1(BLAST Consumer)1](id:eba00000001,api:0,p:-1,c:3770) disconnect
11-13 12:23:10.123 +0000  3770  3770 D DecorView[]: onWindowFocusChanged hasWindowFocus false
11-13 12:23:10.239 +0000  3770  3799 I BLASTBufferQueue: releaseBufferCallbackThunk bufferId:16192026705924 framenumber:12 blastBufferQueue is dead
11-13 12:23:29.748 +0000  3770  3799 D AppScoutStateMachine: 3770-ScoutStateMachinecreated
11-13 12:23:29.772 +0000  3770  3770 D DecorView[]: getWindowModeFromSystem  windowmode is 1
11-13 12:23:29.772 +0000  3770  3770 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
11-13 12:23:29.776 +0000  3770  3770 I BufferQueueConsumer: [](id:eba00000002,api:0,p:-1,c:3770) connect: controlledByApp=false
11-13 12:23:29.776 +0000  3770  3770 I BLASTBufferQueue: [ViewRootImpl[LauncherActivity]#2] constructor()
11-13 12:23:29.777 +0000  3770  3807 I BufferQueueProducer: [ViewRootImpl[LauncherActivity]#2(BLAST Consumer)2](id:eba00000002,api:1,p:3770,c:3770) connect: api=1 producerControlledByApp=true
11-13 12:23:29.840 +0000  3770  3770 D DecorView[]: onWindowFocusChanged hasWindowFocus true
11-13 12:23:33.680 +0000  3770  3796 W System  : A resource failed to call close. 
11-13 12:23:33.680 +0000  3770  3796 W System  : A resource failed to call close. 
11-13 12:23:33.793 +0000  3770  3770 I ProgressLayout: onProgressStarted
11-13 12:23:33.798 +0000  3770  3796 W System  : A resource failed to call close. 
11-13 12:23:33.799 +0000  3770  3770 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10016; state: ENABLED
11-13 12:23:33.802 +0000  3770  3770 D ProgressService: Started!
11-13 12:23:34.262 +0000  3770  5056 I AsyncMcDownloader: Assets begin time: 1668342214262
11-13 12:23:38.005 +0000  3770  5056 I AsyncMcDownloader: Queue size: 0
11-13 12:23:38.005 +0000  3770  5056 I AsyncMcDownloader: Fully shut down!
11-13 12:23:38.005 +0000  3770  5056 I AsyncMcDownloader: Assets end time: 1668342218005
11-13 12:23:38.055 +0000  3770  3770 I Process : Sending signal. PID: 3770 SIG: 9

**Comment by artdeell** [comment]
That seems like a usual run of the launcher process
Can you delete the 1.19.2 version jar?

**Comment by kl1024** [comment]
I reinstalled the game and it magically repaired.
Maybe I set it to a wrong folder.
