### ISSUE TITLE
Minecraft not starting on 1.19!! Below is the latestlog

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3669]
### Describe the bug

--------- beginning with launcher debug
Info: Launcher version: LOCAL-20221019
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2412
Added custom env: POJAV_NATIVEDIR=/data/app/~~LD0X9lWrzlY3aD5fpS2a6A==/net.kdt.pojavlaunch.debug-q5oi6BQ7DcakU5dicSsrDQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~LD0X9lWrzlY3aD5fpS2a6A==/net.kdt.pojavlaunch.debug-q5oi6BQ7DcakU5dicSsrDQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main

I/LIBGL   ( 4530): Initialising gl4es
I/LIBGL   ( 4530): v1.1.4 built on Oct 17 2022 00:55:05
I/LIBGL   ( 4530): Using GLES 2.0 backend
I/LIBGL   ( 4530): loaded: libGLESv2.so
I/LIBGL   ( 4530): loaded: libEGL.so
I/LIBGL   ( 4530): Using GLES 2.0 backend
I/LIBGL   ( 4530): Hardware Full NPOT detected and used
I/LIBGL   ( 4530): FBO are in core, and so used
I/LIBGL   ( 4530): PointSprite are in core, and so used
I/LIBGL   ( 4530): CubeMap are in core, and so used
I/LIBGL   ( 4530): BlendColor is in core, and so used
I/LIBGL   ( 4530): Blend Substract is in core, and so used
I/LIBGL   ( 4530): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 4530): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 4530): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 4530): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 4530): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 4530): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 4530
): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 4530): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 4530): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   ( 4530): Extension GL_OES_texture_float  detected and used
I/LIBGL   ( 4530): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   ( 4530): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 4530): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 4530): high precision float in fragment shader available and used
I/LIBGL   ( 4530): Max vertex attrib: 32
I/LIBGL   ( 4530): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 4530): Max texture size: 16384
I/LIBGL   ( 4530): Max Varying Vector: 31
I/LIBGL   ( 4530): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   ( 4530): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 4530): Max Anisotropic filtering: 16
I/LIBGL   ( 4530): Hardware 
vendor is Qualcomm
I/LIBGL   ( 4530): GLSL 300 es supported
I/LIBGL   ( 4530): GLSL 310 es supported and used
I/LIBGL   ( 4530): GLSL 320 es supported
I/LIBGL   ( 4530): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   ( 4530): sRGB surface supported
I/LIBGL   ( 4530): EGLImage to Texture2D supported
I/LIBGL   ( 4530): EGLImage to RenderBuffer supported
I/LIBGL   ( 4530): ignore MipMap
I/LIBGL   ( 4530): Targeting OpenGL 2.1
I/LIBGL   ( 4530): No hack in shader converter to define overloaded function with int
I/LIBGL   ( 4530): NPOT texture handled in hardware
I/LIBGL   ( 4530): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 4530): try to use VBO
I/LIBGL   ( 4530): glX Will try to recycle EGL Surface
I/LIBGL   ( 4530): Current folder is:/
I/jrelog  ( 4530): dlopen libgl4es_114.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 4530): dlopen libjvm.so failed: dlopen failed: library "libjvm.s
o" not found

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/
runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  ( 4530): dlopen /data/app/~~LD0X9lWrzlY3aD5fpS2a6A==/net.kdt.pojavlaunch.debug-q5oi6BQ7DcakU5dicSsrDQ==/lib/arm64/libopenal.so success

I/jrelog  ( 4530): Done processing args
I/jrelog  ( 4530): Found JLI lib
I/jrelog  ( 4530): Calling JLI_Launch

Error: Could not find or load main class net.minecraft.client.main.Main
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.main.Main

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: LOCAL-20221019
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2412
Added custom env: POJAV_NATIVEDIR=/data/app/~~LD0X9lWrzlY3aD5fpS2a6A==/net.kdt.pojavlaunch.debug-q5oi6BQ7DcakU5dicSsrDQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~LD0X9lWrzlY3aD5fpS2a6A==/net.kdt.pojavlaunch.debug-q5oi6BQ7DcakU5dicSsrDQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main

I/LIBGL   ( 4530): Initialising gl4es
I/LIBGL   ( 4530): v1.1.4 built on Oct 17 2022 00:55:05
I/LIBGL   ( 4530): Using GLES 2.0 backend
I/LIBGL   ( 4530): loaded: libGLESv2.so
I/LIBGL   ( 4530): loaded: libEGL.so
I/LIBGL   ( 4530): Using GLES 2.0 backend
I/LIBGL   ( 4530): Hardware Full NPOT detected and used
I/LIBGL   ( 4530): FBO are in core, and so used
I/LIBGL   ( 4530): PointSprite are in core, and so used
I/LIBGL   ( 4530): CubeMap are in core, and so used
I/LIBGL   ( 4530): BlendColor is in core, and so used
I/LIBGL   ( 4530): Blend Substract is in core, and so used
I/LIBGL   ( 4530): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 4530): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 4530): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 4530): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 4530): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 4530): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 4530
): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 4530): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 4530): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   ( 4530): Extension GL_OES_texture_float  detected and used
I/LIBGL   ( 4530): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   ( 4530): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 4530): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 4530): high precision float in fragment shader available and used
I/LIBGL   ( 4530): Max vertex attrib: 32
I/LIBGL   ( 4530): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 4530): Max texture size: 16384
I/LIBGL   ( 4530): Max Varying Vector: 31
I/LIBGL   ( 4530): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   ( 4530): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 4530): Max Anisotropic filtering: 16
I/LIBGL   ( 4530): Hardware 
vendor is Qualcomm
I/LIBGL   ( 4530): GLSL 300 es supported
I/LIBGL   ( 4530): GLSL 310 es supported and used
I/LIBGL   ( 4530): GLSL 320 es supported
I/LIBGL   ( 4530): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   ( 4530): sRGB surface supported
I/LIBGL   ( 4530): EGLImage to Texture2D supported
I/LIBGL   ( 4530): EGLImage to RenderBuffer supported
I/LIBGL   ( 4530): ignore MipMap
I/LIBGL   ( 4530): Targeting OpenGL 2.1
I/LIBGL   ( 4530): No hack in shader converter to define overloaded function with int
I/LIBGL   ( 4530): NPOT texture handled in hardware
I/LIBGL   ( 4530): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 4530): try to use VBO
I/LIBGL   ( 4530): glX Will try to recycle EGL Surface
I/LIBGL   ( 4530): Current folder is:/
I/jrelog  ( 4530): dlopen libgl4es_114.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 4530): dlopen libjvm.so failed: dlopen failed: library "libjvm.s
o" not found

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/
runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success

I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 4530): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  ( 4530): dlopen /data/app/~~LD0X9lWrzlY3aD5fpS2a6A==/net.kdt.pojavlaunch.debug-q5oi6BQ7DcakU5dicSsrDQ==/lib/arm64/libopenal.so success

I/jrelog  ( 4530): Done processing args
I/jrelog  ( 4530): Found JLI lib
I/jrelog  ( 4530): Calling JLI_Launch

Error: Could not find or load main class net.minecraft.client.main.Main
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.main.Main

### Steps To Reproduce

```markdown
1) Start your launcher
2) Start any version and click play
3) The black screen appears and shows 'Applicatiom ended with code 1'
```

### Expected Behavior

The game should have started normally like it does on lower versions

### Platform

```markdown
- Device model: Redmi note 9 pro
- CPU architecture: 64 bits
- Android version: 1
- PojavLauncher version: debug
```

### Anything else?

Nothing else

**Comment by GaucovyAero** [comment]
delete the 1.19.2 jar in your versions

**Comment by ghost** [comment]
> delete the 1.19.2 jar in your versions

Then? -_-... Cause I wanna play 1.19.2

**Comment by GaucovyAero** [comment]
you just click play

**Comment by ghost** [comment]
> you just click play

What you said actually doesn't make sense. 'Cause you said that to delete the version then hit play which in sense I already did 'cause I downloaded the version and then it don't work...

**Comment by GaucovyAero** [comment]
> > you just click play
> 
> What you said actually doesn't make sense. 'Cause you said that to delete the version then hit play which in sense I already did 'cause I downloaded the version and then it don't work...

it makes sense, because your 1.19.2 jar is corrupted and is missing the main class net.minecraft.client.main.Main, you gotta redownload

**Comment by ghost** [comment]
> > > you just click play
> > 
> > What you said actually doesn't make sense. 'Cause you said that to delete the version then hit play which in sense I already did 'cause I downloaded the version and then it don't work...
> 
> it makes sense, because your 1.19.2 jar is corrupted and is missing the main class net.minecraft.client.main.Main, you gotta redownload

Oh. Now I got it. Lemme try

**Comment by ghost** [comment]
> > > you just click play
> > 
> > What you said actually doesn't make sense. 'Cause you said that to delete the version then hit play which in sense I already did 'cause I downloaded the version and then it don't work...
> 
> it makes sense, because your 1.19.2 jar is corrupted and is missing the main class net.minecraft.client.main.Main, you gotta redownload

It worked
