### ISSUE TITLE
PLS HELP (again but it is different)

### ISSUE THREAD

**Issue by elyesgmzboi** [PojavLauncherTeam/PojavLauncher#367]
i have a problem(again) with pojavlauncher
after installing a new runtime  (thanks to @khanhduytran0 for the runtime) the screen is gray after 20 seconds it is light gray and it crashed

**To Reproduce**
1. Start PojavLauncher
installing the runtime
wait
if there is light gray just wait
5
4
3
2
1
crashed

**Expected behavior**
I expected it will work and i cought play with my friends but no :(

**Platform:**
 - Device Model [infinix hot 8]
 - CPU architecture [aarch64] 
 - Android Version [android 9]

**Comment by Malaska678** [comment]
Infinix is cheap but high spec. So infinix note 7 is my future phone (6gb ram but $140).. Btw give them crash log...

**Comment by khanhduytran0** [comment]
Where is log?

**Comment by elyesgmzboi** [comment]
u mean login?

if yes i allready logged in

**Comment by elyesgmzboi** [comment]
hers the crash log:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/19/20, 1:39 PM
Description: Initializing game

java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:0
	at dgf.b(SourceFile:180)
	at dgf.b(SourceFile:149)
	at dgf.d(SourceFile:65)
	at dgf.a(SourceFile:54)
	at dgf.<init>(SourceFile:45)
	at dlx.<init>(SourceFile:468)
	at net.minecraft.client.main.Main.main(SourceFile:177)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dgf.b(SourceFile:180)
	at dgf.b(SourceFile:149)
	at dgf.d(SourceFile:65)
	at dgf.a(SourceFile:54)
	at dgf.<init>(SourceFile:45)
	at dlx.<init>(SourceFile:468)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (aarch64) version 9
	Java Version: 9-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 575429536 bytes (548 MB) / 805306368 bytes (768 MB) up to 838860800 bytes (800 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xms512m -Xmx800m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.1
	Backend library: LWJGL version 3.2.3 build 13
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: 9x null

**Comment by khanhduytran0** [comment]
Have you updated to v3.2 release LWJGL?

**Comment by elyesgmzboi** [comment]
idk what is it soooo i can say no

**Comment by khanhduytran0** [comment]
You should re-install. Read instruction carefully. https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Testing-v3

**Comment by elyesgmzboi** [comment]
i did it but it still doesn't work there is a short error is
application/game exited with code 1

**Comment by artdeell** [comment]
Need log again

пн, 19 окт. 2020 г., 18:42 elyesishere <notifications@github.com>:

**Comment by elyesgmzboi** [comment]
this time there is no log

**Comment by elyesgmzboi** [comment]
hers new crash log
---- Minecraft Crash Report ----
// You're mean.

Time: 10/19/20, 4:21 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dmb.<init>(SourceFile:143)
	at dlx.<init>(SourceFile:428)
	at net.minecraft.client.main.Main.main(SourceFile:177)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFW
	at dgn.<clinit>(SourceFile:46)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFW
	at dgn.<clinit>(SourceFile:41)
	... 3 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFW
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dmb.<init>(SourceFile:143)
	at dlx.<init>(SourceFile:428)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (aarch64) version 9
	Java Version: 9-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 472620008 bytes (450 MB) / 738197504 bytes (704 MB) up to 838860800 bytes (800 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xms512m -Xmx800m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.1
	Backend library: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	Backend API: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	GL Caps: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI

**Comment by elyesgmzboi** [comment]
and hers the error i fond after doing everything the site said:
![Screenshot_20201019-173341](https://user-images.githubusercontent.com/72686414/96479884-6c069400-1231-11eb-9da0-dc9cf53c3219.png)

**Comment by artdeell** [comment]
You definitely did something wrong then, because well, it looks like LWJGL
is not installed. Show me your game directory.

пн, 19 окт. 2020 г., 19:35 elyesishere <notifications@github.com>:

**Comment by elyesgmzboi** [comment]
thanks it worked but the fps is 1-2 what os the problem?

**Comment by elyesgmzboi** [comment]
is*

**Comment by khanhduytran0** [comment]
The problem probably at Java 9. So I'm porting JRE8 for performance.

**Comment by elyesgmzboi** [comment]
can you explaix cuz i don't know what did you said (sorry)
