### ISSUE TITLE
[BUG] PojavLauncher keeps sending me to the login screen after the game loads.

### ISSUE THREAD

**Issue by anesth3siaaa** [PojavLauncherTeam/PojavLauncher#3671]
### Describe the bug

I get resended to the page when I try to play.

### The log file and images/videos

When I click the play button, after the game has started the extraction, I get resended to the login page. Here's a video explaining:

https://user-images.githubusercontent.com/118138658/201547829-8925c069-6b50-476d-a657-d15a0b6c057a.mp4

### Steps To Reproduce

```markdown
1. Login with my Microsoft Account
2. Select the version
3. Hit play
4. Get send to the login screen
```

### Expected Behavior

I expect the game to launch, not to send me to the login screen

### Platform

```markdown
- Device model: Realme 9 Pro+
- CPU architecture: Dimensity 920 Octa Core
- Android version: 12
- PojavLauncher version: Last uploaded to the Google Play Store
```

### Anything else?

Please help me with this issue

**Comment by GaucovyAero** [comment]
update pojav to the latest actions build

**Comment by GaucovyAero** [comment]
or play store, doesnt matter
