### ISSUE TITLE
[BUG] Can't Open Minecraft

### ISSUE THREAD

**Issue by MMT007** [PojavLauncherTeam/PojavLauncher#3672]
### Describe the bug

Game kinda Freezes for a sec and crashes

### The log file and images/videos

https://user-images.githubusercontent.com/67060689/201563475-e8288cd7-a252-4e39-8c69-a508f9d154c2.mp4

Nothing On Log

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Enter any version
3. crash
```

### Expected Behavior

Expected to word as normal

### Platform

```markdown
- Device model: Moto e7 plus/64GB
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: dahlia-69-38218aef3-v3_openjdk
```

**Comment by Rjjeje** [comment]
We know it's a glich the official app is bugged u can download the dahlia new version till the app fixes  in actions tab find .#3997 one click on title and down debug version it will work:) I'm not admin but yeah It will help u :)

**Comment by TOBIBLASTER0912** [comment]
How can i download the apk? I cant even click this debug thing
