### ISSUE TITLE
Angel render crash using shader Mali Mediatek Helio 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3673]
### Describe the bug

Pojavlauncher are
When using shader crashed
On Mali Mediatek Helio
Android 10

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10001543/latestlog.txt)

### Steps To Reproduce

```markdown
Select version
Start the game
Select shader
Crash
```

### Expected Behavior

Shader work on angles render Mali Mediatek Helio 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest action
```

### Anything else?

Plss help

**Comment by GaucovyAero** [comment]
```
[09:20:25] [Render thread/ERROR]: OpenGL API ERROR: 1280 (Enum 0x8501 is currently not supported.)
```
Shaders generally dont work on Pojav. Also, even if those shaders would run, you would get 1-5fps.
