### ISSUE TITLE
[BUG] Wont let me launch a game

### ISSUE THREAD

**Issue by Flixzr** [PojavLauncherTeam/PojavLauncher#3675]
### Describe the bug

When ever i launch a game (any version) it'll start doing its thing before it just sends me back to the login page

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10004957/latestlog.txt)

### Steps To Reproduce

```markdown
1. LAUNCH ANY VERSION
2. LET IT START LAUNCHING 
3. WAIT FOR THE "PREPARING TO DOWNLOAD REASOURCES" MESSAGE
4. IT'LL STOP LAUNCHING AND SEND YOU BACK TO THE LOGIN PAGE
```

### Expected Behavior

I Expect the game to launch normally

### Platform

```markdown
- Device model: Samsung Galaxy S10/128GB
- CPU architecture: ARM
- Android version: Android 12
- PojavLauncher version: Latest release From Play Store
```

**Comment by artdeell** [comment]
play store release is broken, use version from actions
