### ISSUE TITLE
1.12.2 Black screen on Angles Render

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3676]
### Describe the bug

Black screen on 1.12.2

### The log file and images/videos

None

### Steps To Reproduce

```markdown
Select version
Started the game
Black screen
But have a sounds
```

### Expected Behavior

Working 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest action
```

### Anything else?

Plss fix

**Comment by Akku9446l** [comment]
Angle render only for for 1.17 and above

**Comment by kedrick021** [comment]
> Angle render only for for 1.17 and above

Why

**Comment by Raidenxd2** [comment]
> > Angle render only for for 1.17 and above
> 
> Why

Because it only works on 1.17 and higher

**Comment by Mathias-Boulay** [comment]
1.17+ only
