### ISSUE TITLE
I need someone to check if this is a bug

### ISSUE THREAD

**Issue by lehoanduphong** [PojavLauncherTeam/PojavLauncher#3677]
### Is this request related to a bug?

Now pojav launcher is great for opening the link to chrome 

but it seems that the link to edit the cloak, pojav launcher can't be downloaded, I don't know if it's a bug
![Screenshot_20221115-122238_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103303530/201834305-4e2b57f7-7544-4281-abcc-332abc6dc121.png)
![Screenshot_20221115-122313_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103303530/201834329-baaa412e-1750-4f5e-a572-a1ac80d13762.png)
![Screenshot_20221115-122318_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103303530/201834339-ad1ea17c-5a7a-4ab6-b6de-460b42b0b516.png)
![Screenshot_20221115-122325_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103303530/201834346-5ed14b05-30d3-48b2-944d-7a91fa500c15.png)

**Comment by GaucovyAero** [comment]
```
java.lang.UnsupportedOperationException: Desktop API is not supported on the current platform
```
yep, this won't work, you need a PC for this
