### ISSUE TITLE
[BUG] Game crashes on start-up

### ISSUE THREAD

**Issue by jelleejamm** [PojavLauncherTeam/PojavLauncher#3678]
### Describe the bug

Upon launch, any version of Minecraft exits with code 1.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10010144/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Run any version of Minecraft
```

### Expected Behavior

I expected the game to launch.

### Platform

```markdown
- Device model: Samsung A13 128G
- CPU architecture: armeabi-v7a
- Android version: 12
- PojavLauncher version: Action Build #4043
```

### Anything else?

I checked the latestlog myself and it seems to be due to an .so file not initializing and an object heap failing or something?

I assume this is probably a problem with the Samsung version of Android 12, since I ran this fine on Android 11 before, but who knows.

**Comment by GaucovyAero** [comment]
just lower the ram allocation, automatic ram alloc on 32bit should be lower in the latest actions build
