### ISSUE TITLE
[BUG] It won't let me install

### ISSUE THREAD

**Issue by Arbifoxx** [PojavLauncherTeam/PojavLauncher#368]
When I try to install on the Razer phone 2 it keeps saying App not installed. (P.S. can I play on Minecraft java servers with this?)

**Comment by artdeell** [comment]
1. Maybe you installed some old ver. of the launcher before? Try to remove
first if you did.
2. yes

пн, 19 окт. 2020 г., 16:54 waterdragon78 <notifications@github.com>:
