### ISSUE TITLE
[BUG] <Small screen and incorrect button placement>

### ISSUE THREAD

**Issue by Eggir** [PojavLauncherTeam/PojavLauncher#3680]
### Describe the bug

It is impossible to enter the game, the buttons are located higher than they actually should be.

### The log file and images/videos

![Screenshot_2022-11-15-16-39-04-664_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/117267463/201900045-d50d1821-5248-4e1d-8b7d-6049ac823c46.jpg)
![Screenshot_2022-11-15-16-39-13-456_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/117267463/201900055-bee0531a-9c7b-47fd-9284-57039b2e72b8.jpg)
After F11, the problem remains the same.  Incorrect button placement.
![Screenshot_2022-11-15-16-39-33-834_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/117267463/201900122-3ec719ee-a479-4382-bd80-a81047bcde54.jpg)

### Steps To Reproduce

```markdown
1.Installed version 1.12.2
2.Installed forge
3.and started the game
Same for version 1.7.10
```

### Expected Behavior

I don't even know why this is happening.

### Platform

```markdown
- Device model:Poco X4 GT
- CPU architecture:64-bit
- Android version:12
- PojavLauncher version:#3997
```

**Comment by GaucovyAero** [comment]
dont use a custom directory

**Comment by GaucovyAero** [comment]
Update to this: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3464178381

**Comment by Eggir** [comment]
Thanks
