### ISSUE TITLE
[BUG] click bug (OTG mouse)

### ISSUE THREAD

**Issue by ZaphHG** [PojavLauncherTeam/PojavLauncher#3681]
### Describe the bug

I cant use my mouse buttons correctly, the game just lags as soon as I click, then i cant move my mouse correctly

its a problem bc im a pvp player and i cant 1v1 with this bug 

### The log file and images/videos

https://www.mediafire.com/file/cyqgq62jg1zy8o3/Screen_Recording_20221115_094224_PojavLauncher+(Minecraft+Java+Edition+for+Android).mp4/file

### Steps To Reproduce

```markdown
just start pojavlauncher with mouse/keyboard and try 6cps while moving the mouse
```

### Expected Behavior

I expected to be able to click the mouse without having lags 

### Platform

```markdown
- Device model: Tab S6 Lite / 64GB
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Update android.yml #4043 (https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3464178381)
```

**Comment by GaucovyAero** [comment]
this is caused by your android distribution, not pojav

**Comment by GaucovyAero** [comment]
luckily enough, your tablet can run lineageos 19 (official) and lineageos 20 (unofficial) custom roms which are known working and had fixed this exact issue on my s7 edge.

**Comment by Betagodd** [comment]
I have that same problem, I have a s10e and android 12

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/file/hidlbcf6iquorhz/crocus-299.apk/file
looks like this build works, but its really old, also doesnt work with 1.17+ without patches, and 1.19+ doesnt work at all.

**Comment by dashboy233** [comment]
Please send me your video, maybe I have the same problem as you, but I can't watch the video you sent me.
