### ISSUE TITLE
[F-Req] Mod loader should be added

### ISSUE THREAD

**Issue by anshoo2745** [PojavLauncherTeam/PojavLauncher#3682]
### Is this request related to a bug?

Nope

### Describe the request.

So i wanted that Pojav Launcher adds a mod loader because it is now became for premium ACC players so it should be added so that we can 1 click the modpacks in a second and easy to download and use mods . I request to please add this feature please please please...

### Anything else?

If don't know what i said just i said to 1 click download mods

**Comment by hiimabignoobwihenolive** [comment]
Ngl they gona close the issue because *they already responded to that🤓*

**Comment by anshoo2745** [comment]
> Ngl they gona close the issue because _they already responded to that🤓_

What they said

**Comment by GaucovyAero** [comment]
hmm, not yet i think, we are mostly focused on fixing bugs currently
