### ISSUE TITLE
[BUG] <When I try to open the game it sends me to the microsoft login page>

### ISSUE THREAD

**Issue by DarKaskarote** [PojavLauncherTeam/PojavLauncher#3683]
### Describe the bug

I have downloaded this on my chromebook ( a school computer ) and whenever I try to open any version of the game it gets stuck at "preparing to download resources" it then stops and shows me the microsoft login page. I have tried to re download the game many times but it still doesnt work.

### The log file and images/videos

[Screen recording 2022-11-15 18.54.08.webm](https://user-images.githubusercontent.com/97482406/201991348-f6753be3-6704-4f29-a5e9-abb3438b8de5.webm)

### Steps To Reproduce

```markdown
1. I just open any version of the game and the bug occurs.
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ghost** [comment]
Same problem. Just update the game

**Comment by GaucovyAero** [comment]
update pojav, fixed in the latest play store build
