### ISSUE TITLE
[BUG] <white screen>

### ISSUE THREAD

**Issue by sswarior26** [PojavLauncherTeam/PojavLauncher#3686]
### Describe the bug

Whenever i lauch pojavlauncher, white screen shows.

### The log file and images/videos

![Screenshot_2022-11-16-19-31-37-88_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/104709935/202200884-ae31eab5-ea70-4320-a67b-20a77532bcfe.png)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Laucn pojav launcher
```

### Expected Behavior

I expected to load it normally 

### Platform

```markdown
- Device model: realme c2
- CPU architecture: media tek
- Android version: 9
- PojavLauncher version: dahlia-159-b581c7ba8-v3_openjdk [latest on playstore]
```

**Comment by AGENTISNUM1** [comment]
same problem, its smth to do with the controls

**Comment by AGENTISNUM1** [comment]
the on screen ones i mean

**Comment by AGENTISNUM1** [comment]
its a render issue, happens on all versions

**Comment by AGENTISNUM1** [comment]
and here i was thinking i could use pojav after the new update

**Comment by sswarior26** [comment]
Same

**Comment by sswarior26** [comment]
> same problem, its smth to do with the controls

Ya, ig

**Comment by sswarior26** [comment]
Dev's pls slove the issue

**Comment by AGENTISNUM1** [comment]
Soon (hopefully) 
![image](https://user-images.githubusercontent.com/106842539/202747289-a8a193fb-bdc7-4a81-8a1b-0391beca6d6e.png)

**Comment by sswarior26** [comment]
Is it happening me only or everyone?

**Comment by Mathias-Boulay** [comment]
Reverted the optimization, as it collided with oem optimizations
