### ISSUE TITLE
[BUG] Game crashes on startup with code 1

### ISSUE THREAD

**Issue by Raidenxd2** [PojavLauncherTeam/PojavLauncher#3688]
### Describe the bug

Game crashes on startup with code 1
There is no mods being used
Every thing is default settings

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10025999/latestlog.txt)

### Steps To Reproduce

```markdown
1. Create a profile with 1.12.2 or lower
2. Launch it.
```

### Expected Behavior

I expect the game to launch

### Platform

```markdown
- Device model: Samsung Galaxy Tab A7/32G
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: dahlia-164-0a385781e-v3_openjdk (latest auto build)
```

**Comment by GaucovyAero** [comment]
reinstall pojav and wait till the runtime extracts, make sure you dont close the launcher if its frozen
