### ISSUE TITLE
[BUG] O CANT EDIT THE BUTTON

### ISSUE THREAD

**Issue by yarik303** [PojavLauncherTeam/PojavLauncher#3690]
### Describe the bug

Im trying to add an i button but button doest come up with setting
I hold the button
No settings

### The log file and images/videos

https://user-images.githubusercontent.com/75032600/202363634-3e8a9c9f-ffbb-40c2-8253-d2658c9144f9.mp4

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10028293/latestlog.txt)

### Steps To Reproduce

```markdown
1. Run pojavlauncher
2. Go to user settings
3. Create a button 
4. Good luck editing it
```

### Expected Behavior

I expected to actually edit the button

### Platform

```markdown
- Device model: Huawei p smart 2017
- CPU architecture: i cant find it
- Android version: 9
- PojavLauncher version:
```

**Comment by sswarior26** [comment]
It's happening with me also.

**Comment by Mathias-Boulay** [comment]
Should be fixed in the dev build
