### ISSUE TITLE
Forge 1.18 - 1.19+ latest using optifine crash on loading world

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3691]
### Describe the bug

Crash on loading world 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Select version
2. Start game
3. Loading world crash
```

### Expected Behavior

Optifine working

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest on GitHub
```

### Anything else?

None

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by kedrick021** [comment]
> send latestlog.txt

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10029618/latestlog.txt)

**Comment by GaucovyAero** [comment]
you sure you are not using any shaders, antialiasing or similar stuff?

**Comment by kedrick021** [comment]
> you sure you are not using any shaders, antialiasing or similar stuff?

No I don't use any shader and that the old problem and not fix until now

**Comment by maj113** [comment]
> > you sure you are not using any shaders, antialiasing or similar stuff?
> 
> No I don't use any shader and that the old problem and not fix until now

BTW does this happen only with forge or with vanilla MC + optifine, try disabling "Render regions" and "emissive textures" it fixed the issue for me but im not using forge

**Comment by GaucovyAero** [comment]
fixed ig?
