### ISSUE TITLE
[F-Req] Open Microsoft login in the default browser

### ISSUE THREAD

**Issue by Madis0** [PojavLauncherTeam/PojavLauncher#3693]
### Is this request related to a bug?

The Microsoft login is embedded in the app, which means the app (potentially) has full control over user's input.

### Describe the request.

The Microsoft login should open in the user's default browser, so that the user can verify it is the real site and that the app cannot get the password, only the token.

**Comment by Mathias-Boulay** [comment]
While the concern would be valid for a closed source app, you can check the webview code right in this repository.
