### ISSUE TITLE
Keep bringing me to PojavLuncher home menu

### ISSUE THREAD

**Issue by user1763013** [PojavLauncherTeam/PojavLauncher#3694]
### Describe the bug

I pressed play, it says wait. Then after that, it went back to PojavLauncher home menu

### The log file and images/videos

https://user-images.githubusercontent.com/118518714/202672424-1484dcfc-e334-42ba-80f7-35f15fa009a7.mp4

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Press play
```

### Expected Behavior

I expect for minecraft to launch

### Platform

```markdown
- Device model: Huawei Nova 2i
- CPU architecture: Hilisicon Kirin 659
- Android version: 8.0.0
- PojavLauncher version: 3.3.1.1
```

**Comment by user1763013** [comment]
Anyone pls help me

**Comment by GaucovyAero** [comment]
update your launcher
