### ISSUE TITLE
[BUG] White Screen on game launch

### ISSUE THREAD

**Issue by AGENTISNUM1** [PojavLauncherTeam/PojavLauncher#3696]
### Describe the bug

When i launch the game it loads fine, but then constantly refreshes and brightens until the screen is white.

### The log file and images/videos

![image](https://user-images.githubusercontent.com/106842539/202737945-5191894a-e90f-4546-8246-6878e28b028c.png)

### Steps To Reproduce

```markdown
1. start pojav
2. launch any version with any renderer
3. game launches fine but then whitescreens.
```

### Expected Behavior

I expect the game to render fine without whitescreening

### Platform

```markdown
- Device model: lenovo chromebook
- CPU architecture: ??
- Android version: ??
- PojavLauncher version: Latest Gplay Release
```

### Anything else?

For some reason, optifine seems to (kinda) fix it. all overlays and fog white screen tho.

Versions ive tested:

1.12.2
1.16.5
1.18.2
1.12.2 forge
1.12.2 optifine 
1.19.2
1.17.1 fabric
1.13.2

**Comment by AGENTISNUM1** [comment]
optifine screenshots:
![image](https://user-images.githubusercontent.com/106842539/202742391-56140a62-1a09-4f2b-92c7-850553dc2e70.png)
![image](https://user-images.githubusercontent.com/106842539/202742414-f182665d-cda6-4b48-a201-f35f98e3dd61.png)
![image](https://user-images.githubusercontent.com/106842539/202742427-94fac851-6a7b-4f3d-828f-1463ffb3716e.png)
![image](https://user-images.githubusercontent.com/106842539/202742445-b3e13664-71b1-473f-aa48-fabce49df70c.png)
![image](https://user-images.githubusercontent.com/106842539/202742459-af6c2c2a-635a-4efb-abfe-e9bc98067959.png)

**Comment by AGENTISNUM1** [comment]
Pls Fix

**Comment by AGENTISNUM1** [comment]
Also the texture pack has no effect.

**Comment by GaucovyAero** [comment]
we will be pushing an update with the fix soon to gplay

**Comment by AGENTISNUM1** [comment]
Ok thanks so much!

**Comment by khanhduytran0** [comment]
How about toggling `alternate surface rendering`?

**Comment by sswarior26** [comment]
> How about toggling `alternate surface rendering`?

Whats that?

**Comment by sswarior26** [comment]
> we will be pushing an update with the fix soon to gplay

Thanks!

**Comment by sswarior26** [comment]
> How about toggling `alternate surface rendering`?

DUDE THANK YOU SOOO MUCH!!!!

**Comment by Abhayprabhu1505** [comment]
Same with me pls fix it

**Comment by sswarior26** [comment]
> Same with me pls fix it

Bro go in settings then go in video and renderer then click on alternative surface renderar it will be fixed

**Comment by AGENTISNUM1** [comment]
k fixed
