### ISSUE TITLE
[BUG] Buggy UI

### ISSUE THREAD

**Issue by TheAirBlow** [PojavLauncherTeam/PojavLauncher#3698]
### Describe the bug

See screenshots

### The log file and images/videos

![Screenshot_2022-11-19-09-25-06-104_net kdt pojavlaunch~2](https://user-images.githubusercontent.com/68467762/202834547-66829239-694f-4b71-9f78-60969539e086.jpg)
![Screenshot_2022-11-19-09-25-12-208_net kdt pojavlaunch](https://user-images.githubusercontent.com/68467762/202834551-4075dc91-bd8b-41d9-b318-fcb79e026116.jpg)

### Steps To Reproduce

```markdown
1) Rotate phone
2) Start launching game
```

### Expected Behavior

Common sense

### Platform

```markdown
- Device model: POCO M4 Pro 5G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahila-159
```

**Comment by GaucovyAero** [comment]
this is a known issue, idk when it will be fixed

**Comment by TheAirBlow** [comment]
@GaucovyAero "not planned", bruh

**Comment by GaucovyAero** [comment]
> @GaucovyAero "not planned", bruh

this was pointed out many times, for now ill just be closing issues that dont really need to be there, i know about this
