### ISSUE TITLE
[ BUG ] Cannot install .jar file

### ISSUE THREAD

**Issue by user1763013** [PojavLauncherTeam/PojavLauncher#3699]
### Describe the bug

Crashed while pressing "Install .jar file".

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Press "Install .jar".
```

### Expected Behavior

I want to install OptiFine.

### Platform

```markdown
- Device model: Huawei Nova 2i
- CPU architecture: Hisilicon Kirin 659
- Android version: 8.0.0
- PojavLauncher version: dahlia-159-b581c7ba8-v3_openjdk
```

### Anything else?

None

**Comment by Kolyanpetuh** [comment]
> ### Describe the bug
> 
> Crashed while pressing "Install .jar file".
> 
> ### The log file and images/videos
> 
> None
> 
> ### Steps To Reproduce
> 
> ```markdown
> 1. Start PojavLauncher
> 2. Press "Install .jar".
> ```
> 
> 
> ### Expected Behavior
> 
> I want to install OptiFine.
> 
> ### Platform
> 
> ```markdown
> - Device model: Huawei Nova 2i
> - CPU architecture: Hisilicon Kirin 659
> - Android version: 8.0.0
> - PojavLauncher version: dahlia-159-b581c7ba8-v3_openjdk
> ```
> 
> 
> ### Anything else?
> 
> None

Maybe you should change runtime to Java 8 in launcher's options before installing .jar files if you didn't do that.

**Comment by Prostop194** [comment]
where can i download java 8? 
or give a link to download java 8

**Comment by Andmith07** [comment]
I want to install sodium patcher
