### ISSUE TITLE
What happen if i test minecraft java Tlauncher for mobiles? 

### ISSUE THREAD

**Issue by abdo-A028** [PojavLauncherTeam/PojavLauncher#37]
It is hard to explain what is this?
If the owner of Tlauncher for Minecraft java says add this on android and iOS, it can be better than PojavLauncher.

So There were Tlauncher for Minecraft pocket edition, but I don't know which version.

But Tlauncher for Minecraft java on mobile will be better, Because it have skins, download mods and etc.

**Comment by khanhduytran0** [comment]
Porting TLauncher to Android requires a Java VM, but without HUD touchscreen it will be unusable.
If porting to iOS it is harder, they must rewrite with UIKit API under RoboVM or other Java VM for iOS.
Android is not an desktop operating system, so don't think to install tons of mods.

**Comment by khanhduytran0** [comment]
Just about 5-10 mods might causing lag and freeze.

**Comment by abdo-A028** [comment]
Ok.
You can't put mods if causing lags or freeze

**Comment by khanhduytran0** [comment]
Modding will be later

**Comment by artdeell** [comment]
> It is hard to explain what is this?
> If the owner of Tlauncher for Minecraft java says add this on android and iOS, it can be better than PojavLauncher.
> 
> So There were Tlauncher for Minecraft pocket edition, but I don't know which version.
> 
> But Tlauncher for Minecraft java on mobile will be better, Because it have skins, download mods and etc.

I'm bet you're from Russia.
Why TLauncher for Java will be never ported to Android:

1. It uses JavaFX, so it will be too difficult to port complete JavaFX toolkit.
2. It's proprietary and not open-source. (No one there wants to be sued, right?)
3. It violates Minecraft EULA, by offering paid skin service.
4. It's written for x86, and needs to be fully rewritten to be compartible with Android.

It MAY be created, but it will be laggy and unfamous. Also,
> nothing is better than user-contributed

**Comment by artdeell** [comment]
Also, TLauncher Team will encounter HUGE issues with OptiFine & Forge compartiblity.

**Comment by khanhduytran0** [comment]
Also, I think most of mods at the moment use OpenGL high as OpenGL 3 or 4 which not supported by GL4ES.

**Comment by abdo-A028** [comment]
> > It is hard to explain what is this?
> > If the owner of Tlauncher for Minecraft java says add this on android and iOS, it can be better than PojavLauncher.
> > So There were Tlauncher for Minecraft pocket edition, but I don't know which version.
> > But Tlauncher for Minecraft java on mobile will be better, Because it have skins, download mods and etc.
> 
> I'm bet you're from Russia.
> Why TLauncher for Java will be never ported to Android:
> 
> 1. It uses JavaFX, so it will be too difficult to port complete JavaFX toolkit.
> 2. It's proprietary and not open-source. (No one there wants to be sued, right?)
> 3. It violates Minecraft EULA, by offering paid skin service.
> 4. It's written for x86, and needs to be fully rewritten to be compartible with Android.
> 
> It MAY be created, but it will be laggy and unfamous. Also,
> 
> > nothing is better than user-contributed

I an not from Russia, I am Arab
