### ISSUE TITLE
[BUG] Angle crashing

### ISSUE THREAD

**Issue by Kuru0rin** [PojavLauncherTeam/PojavLauncher#3700]
### Describe the bug

Pojav crashes when using angle

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10046353/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Change renderer to Angle
3.Start the game
```

### Expected Behavior

Game just crashed

### Platform

```markdown
- Device model: CPH1901 Oppo A7
- CPU architecture: arm64
- Android version: 8.1.0
- PojavLauncher version: dahlia-176-641eae051-v3_openjdk
```

**Comment by GaucovyAero** [comment]
your device likely does not have vulkan
