### ISSUE TITLE
Game launch white screen

### ISSUE THREAD

**Issue by Sahilkumar568** [PojavLauncherTeam/PojavLauncher#3701]
### Is this request related to a bug?

I launched my game and I see white screen in new update in Google Play store

### Describe the request.

I launched my game and I see white screen in new update in Google Play store

### Anything else?

I launched my game and I see white screen in new update in Google Play store

**Comment by artdeell** [comment]
will be fixed in a future update

**Comment by Sahilkumar568** [comment]
That time what can I do
