### ISSUE TITLE
[BUG] Black screen starting the game

### ISSUE THREAD

**Issue by AnotherNoName** [PojavLauncherTeam/PojavLauncher#3708]
### Describe the bug

When you start the game you get a black screen.

### The log file and images/videos

https://user-images.githubusercontent.com/65259492/202869683-650ac292-158b-4049-b565-2b2a69980c5e.mp4

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start the game
```

### Expected Behavior

I expect the game to launches / have any kind of logs

### Platform

```markdown
- Device model: Poco X3 Pro
- CPU architecture: ARMv8
- Android version: 12
- PojavLauncher version: dahlia-176-641eae051-v3_openjdk (from Actions)
```

### Anything else?

It has no logs, in fact, it does not generate any kind of folder.

**Comment by kedrick021** [comment]
Don't use angles render is only for 1.17

**Comment by AnotherNoName** [comment]
> Don't use angles render is only for 1.17

im using the default render (gl4es)

**Comment by dxcvvxd** [comment]
same issue, not a single version works and changing renderer/java version doesn't change anything either lol

**Comment by qpowei** [comment]
same issue

**Comment by asdzxc233** [comment]
same issue

**Comment by asdzxc233** [comment]
When I switched to another version of PojavLauncher, its fine.

**Comment by T-CATHOME** [comment]
close this,than try again
![IMG_20221126_191414](https://user-images.githubusercontent.com/73945464/204085895-987dbc77-7a24-4427-b7d1-ed7055117daf.jpg)

**Comment by deathnightdubs** [comment]
That is closed, same issue
