### ISSUE TITLE
[BUG] Blackscreen when starting game in dahlia 176

### ISSUE THREAD

**Issue by TOBIBLASTER0912** [PojavLauncherTeam/PojavLauncher#3711]
### Describe the bug

My game is still not working with the new update! I have only a blackscreen when i start my game. All my profiles wont work...
Latestlog is empty...

### The log file and images/videos

https://user-images.githubusercontent.com/118199012/202892224-0006e4f8-836e-45dc-a732-d3929b4de6eb.mp4

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Click any installed profile
3. Start
4. Only blackscreen
```

### Expected Behavior

I expect the game to start and play

### Platform

```markdown
Device model: Oppo Find X2 lite/128G
CPU architecture:  aarch64
Android version: 12
PojavLauncher version: dahlia 176
```

### Anything else?

Latestlog is empty lol

**Comment by qpowei** [comment]
same issue

**Comment by Nanu89007** [comment]
Same issue

**Comment by PauloTheDevGuy** [comment]
Same issue happened to me
It seems to maybe be related to changing the allocated RAM given to Minecraft
If you run it on the default amount pojavlauncher has it will not have this issue

**Comment by GaucovyAero** [comment]
reinstall pojav, you gotta delete all pojav data, then restart your phone and then reinstall, make sure you wait even if the launcher freezes for java to unpack
