### ISSUE TITLE
Angle Renderer Not Working

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3712]
### Describe the bug

The bug is that when I use shaders with Angle Renderer in version 1.17.1, the game crashes without reason. Some shaders just load and some directly crashes!! Can you tell me whether my device is compatible by reading the device details? 

### The log file and images/videos

![Screenshot_2022-11-20-14-24-56-34_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/116268548/202893759-81ca8223-f330-41ab-9641-1bae746664fe.jpg)

### Steps To Reproduce

```markdown
1. Open your launcher.
2. Play OptiFine 1.17.1
3. Enter a world.
4. Select shader.
 And then it continues it either crashes or black screen comes!
```

### Expected Behavior

It should have been played with the shader

### Platform

```markdown
- Device model: Redmi note 9 pro
- CPU architecture: 64x
- Android version: 12
- PojavLauncher version: latest play store released 18 Nov, 2022.
- GPU architechture: Adreno
```

### Anything else?

I also had another question. In the new update it seems that the sensitivity of touch is slightly increased. Is there any way to reduce the sensitivity?

**Comment by dxcvvxd** [comment]
i dont think it's supposed to be used with custom shaders

**Comment by ghost** [comment]
> i dont think it's supposed to be used with custom shaders

First of all I didn't know about that and the shaders I used are recommended by youtubers means they already used the shaders while testing hence it might be my phone issue

**Comment by GaucovyAero** [comment]
dont use angle and use open4es for gl4es https://www.mediafire.com/folder/cp87zpb3ichj7/Open4ES
