### ISSUE TITLE
Please make an open beta test of the application in App Store and Google Play.

### ISSUE THREAD

**Issue by Kolyanpetuh** [PojavLauncherTeam/PojavLauncher#3714]
### Is this request related to a bug?

No it's not a bug, I just want to be able to try the latest launcher features without having to download from GitHub.

### Describe the request.

Please make it possible to participate in the beta testing of this application in App Store and Google Play.

### Anything else?

I think it would be very cool if all users, without exception, had access to preview versions without GitHub.

**Comment by AGENTISNUM1** [comment]
agreed.

**Comment by Mathias-Boulay** [comment]
We have a patreon for that, check it out
