### ISSUE TITLE
[BUG] <Short description>i can't install.jar files

### ISSUE THREAD

**Issue by Andros42** [PojavLauncherTeam/PojavLauncher#3715]
### Describe the bug

Crash when I try to install any jar file 

### The log file and images/videos

Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch.debug/cache/fabric-installer-0.11.0.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: POJAV_NATIVEDIR=/data/app/~~YrAGNPNTaLr3uB_wzHx4_g==/net.kdt.pojavlaunch.debug-xwWmxDyyR06lBCjcnP7LMw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/bin:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~YrAGNPNTaLr3uB_wzHx4_g==/net.kdt.pojavlaunch.debug-xwWmxDyyR06lBCjcnP7LMw==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (10191): dlopen libjvm.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2gss.so success

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7d94afecf8)
--------- beginning of main

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (10191): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7d90630e18)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7d90630e18)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7d94afecf8)
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjaas_unix.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libsunec.so success

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aa
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/a
rch64/libhprof.so success

arch64/libawt_xawt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/In
ternal/lib/aarch64/server/libjvm.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnpt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.poja
vlaunch.debug/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (10191): dlopen /data/app/~~YrAGNPNTaLr3uB_wzHx4_g==/net.kdt.pojavlaunch.debug-xwWmxDyyR06lBCjcnP7LMw==/lib/arm64/libopenal.so success
I/jrelog  (10191): Done processing args
I/jrelog  (10191): Found JLI lib
I/jrelog  (10191): Calling JLI_Launch

I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnpt
.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (10191): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (10191): dlopen /data/app/~~YrAGNPNTaLr3uB_wzHx4_g==/net.kdt.pojav
launch.debug-xwWmxDyyR06lBCjcnP7LMw==/lib/arm64/libopenal.so success
I/jrelog  (10191): Done processing args
I/jrelog  (10191): Found JLI lib
I/jrelog  (10191): Calling JLI_Launch

### Steps To Reproduce

```markdown
Start pojavlauncher
Prass install.jar
```

### Expected Behavior

I want to install fabric and forge

### Platform

```markdown
- Device model:poco M4 pro 4g
- CPU architecture:64 bit
- Android version:12
- PojavLauncher version:dahila-177-86eb81c00-native-input
```

### Anything else?
None

**Comment by TOBIBLASTER0912** [comment]
Dont have the issue but ur screen record isnt uploaded... Try reupload it and wait till its fully uploaded.. Maybe i can help :)

**Comment by AGENTISNUM1** [comment]
Works fine for me... what file are you trying to install?

**Comment by Kolyanpetuh** [comment]
> ### Describe the bug
> 
> Crash when I try to install any jar file 
> 
> ### The log file and images/videos
> 
> 
> Uploading Screenrecorder-2022-11-20-21-10-39-421.mp4…
> 
> 
> 
> ### Steps To Reproduce
> 
> ```markdown
> Start pojavlauncher
> Prass install.jar
> ```
> 
> 
> ### Expected Behavior
> 
> I want to install fabric and forge
> 
> ### Platform
> 
> ```markdown
> - Device model:poco M4 pro 4g
> - CPU architecture:64 bit
> - Android version:12
> - PojavLauncher version:dahila-177-86eb81c00-native-input
> ```
> 
> 
> ### Anything else?
> None

Maybe you should change runtime to Java 8 in launcher's options before installing .jar files if you didn't do that.

**Comment by Andros42** [comment]
> 


> 

I have kept Java 8 but still I optifine not install

**Comment by Andros42** [comment]
> Works fine for me... what file are you trying to install?

Optifine fabric 1.19.2

**Comment by Andros42** [comment]
> Dont have the issue but ur screen record isnt uploaded... Try reupload it and wait till its fully uploaded.. Maybe i can help :)

how do i upload again

**Comment by GaucovyAero** [comment]
rotate your screen into landscape mode
