### ISSUE TITLE
[BUG] Fabric 1.16.5 not loading

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3716]
### Describe the bug

App closed with error code 1(obviously)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10050471/latestlog.txt)
Logs here. I installed vanilla minecraft using ready zip file.
Here it is if you want to investigate it:
https://drive.google.com/file/d/1MtiB18YB4sj6UhiuxfFi61Eeb4PbdnfS/view

### Steps To Reproduce

```markdown
1. Start pojav
2. Install fabric using fabric jar installer
3. Run fabric 1.16.5
4. Encountered an error
```

### Expected Behavior

Expected game to launch without mods

### Platform

```markdown
- Device model: Samsung A12 SM-A127F 3/32GB
- CPU architecture: AArch64
- Android version: 12(S?)
- PojavLauncher version: dahila-8-f527e8a14-v3_openjdk
```

### Anything else?

So like i found a modpack for performance.
As i remember it includes sodium, lazydfu, entityculling, lithium and fastload.

**Comment by artdeell** [comment]
Outdated launcher version
