### ISSUE TITLE
[BUG] <When i open pojavlauncher, it immediately crash>

### ISSUE THREAD

**Issue by rodrickhmmm** [PojavLauncherTeam/PojavLauncher#3717]
### Describe the bug

when i try to open pojavlauncher, it automatically crash and show this crash message:

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:288) at com.kdt.mcgui.mcAccountSpinner.onItemSelected(mcAccountSpinner.java:150) at android.widget.AdapterView.fireOnSelected(AdapterView.java:957) at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946) at android.widget.AdapterView.access$300(AdapterView.java:55) at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:210) at android.os.Looper.loop(Looper.java:299) at android.app.ActivityThread.main(ActivityThread.java:8261) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### Steps To Reproduce

```markdown
How do I fix this
```

### Expected Behavior

pls

### Platform

```markdown
- Device model: POCO X3 Pro
- CPU architecture: 
- Android version: 12 SKQ1.211006.001
- PojavLauncher version: dahila-176-641eae051-v3_openjdk
```

### Anything else?

pls help me with it

**Comment by Mathias-Boulay** [comment]
Should be fixed by latest dev build
