### ISSUE TITLE
[BUG] Pixelmon Crash/Bug

### ISSUE THREAD

**Issue by teodqr** [PojavLauncherTeam/PojavLauncher#3719]
### Describe the bug

Hi, im trying to play with my friend pixelmon and when i get in the main menu it pops up this error(i ll upload it) and i can t do anything about it,any fixes? 

Edit: Now when i allocated more memory like 2048 it crashed and i ll send the log

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10050587/latest.log)
[latest (1).log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10050588/latest.1.log)
![unknown](https://user-images.githubusercontent.com/60618655/202923639-f7a81a02-9a30-4f7c-aabe-fdf9deab5a3f.jpg)

### Steps To Reproduce

```markdown
1. Started the projav with the 1.16.5 forge version
2.Waited for it to load
3.And the error poped up
4.Idk
```

### Expected Behavior

idk

### Platform

```markdown
- Device model: Galaxy a71
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: lastest
```

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by bryanpojav** [comment]
@TeoHex open the file manager go to .minecraft/config/pixelmon open the config option find the part that says "use-discord-rich-presence: true" and write false instead of true

**Comment by vortx6** [comment]
hi so i downloaded pixelmon 9.1.3 for pojav and i opened it with 1.16.5 forge version 36.2.34 and its crashing with application/game exited with code-1 with this [][][][][][] coming on the screen can anyone tell me how to fix this
