### ISSUE TITLE
[F-Req] <Short description> Add a special button that hides the control that button will just hide the controls and not show in the screen

### ISSUE THREAD

**Issue by Andros42** [PojavLauncherTeam/PojavLauncher#3722]

**Comment by SLIXTREEN** [comment]
the gui button already exist

**Comment by Andros42** [comment]
> the gui button already exist

I am talking about a button that removes the controls by making the controls fully transparent

**Comment by Mathias-Boulay** [comment]
You can already create fully transparent controls, or a control scheme with no buttons

**Comment by Andros42** [comment]
> You can already create fully transparent controls, or a control scheme with no buttons

How
