### ISSUE TITLE
[F-Req] Add display over apps for virtual controller & mouse

### ISSUE THREAD

**Issue by Zugaraki** [PojavLauncherTeam/PojavLauncher#3723]
### Describe the request.

It would be cool if you added a feature to display over apps so I can play mcpe with pojav's controller and mouse cuz I hate the new & old controller in mcpe and I got used to it in pojav's controller with mouse

**Comment by Mathias-Boulay** [comment]
How is that related to the "display over other apps" permissions ?

**Comment by Zugaraki** [comment]
@Mathias-Boulay Hello sir, sry for the very late response this is how it will work in this video: https://youtu.be/RDgtkM3tmUs this is not a rickroll im srs finger crossed, but that app doesn't have the toggle, swipe, mousepass and key combinations features and it's very limited to customizations but pojavlauncher controller customizations is complete and the only thing I want is to be able to display this on any other apps games just like how it works in the video.


here's another example in mcpe gameplay: https://youtu.be/_9hb7mcmKIg skip to 2:15

**Comment by Zugaraki** [comment]
> How is that related to the "display over other apps" permissions ?

Hello sir, sry for the very late response this is how it will work in this video: https://youtu.be/RDgtkM3tmUs this is not a rickroll im srs finger crossed, but that app doesn't have the toggle, swipe, mousepass and key combinations features and it's very limited to customizations but pojavlauncher controller customizations is complete and the only thing I want is to be able to display this on any other apps games just like how it works in the video.


here's another example in mcpe gameplay: https://youtu.be/_9hb7mcmKIg skip to 2:15

**Comment by GaucovyAero** [comment]
> > How is that related to the "display over other apps" permissions ?
> 
> Hello sir, sry for the very late response this is how it will work in this video: https://youtu.be/RDgtkM3tmUs this is not a rickroll im srs finger crossed, but that app doesn't have the toggle, swipe, mousepass and key combinations features and it's very limited to customizations but pojavlauncher controller customizations is complete and the only thing I want is to be able to display this on any other apps games just like how it works in the video.
> 
> here's another example in mcpe gameplay: https://youtu.be/_9hb7mcmKIg skip to 2:15

i dont think we will be the ones doing it, but you can always fork our project and create an app with this feature
