### ISSUE TITLE
[BUG] Fabric 1.16.5 failed to launch it says Applicaton/Game Exited

### ISSUE THREAD

**Issue by Bancure99** [PojavLauncherTeam/PojavLauncher#3726]
### Describe the bug

It crashes when i try to launch fabric,i dont know why is this happening everytime.I can run forge but it crashes on fabric.

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-159-b581c7ba8-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.16.5
--------- beginning of system

--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1280
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-2/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-2/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
I/LIBGL   (16930): Initialising gl4es
I/LIBGL   (16930): v1.1.4 built on Oct 30 2022 20:18:46
I/LIBGL   (16930): Using GLES 2.0 backend

I/LIBGL   (16930): loaded: libGLESv2.so
I/LIBGL   (16930): loaded: libEGL.so
I/LIBGL   (16930): Using GLES 2.0 backend

I/LIBGL   (16930): Hardware Full NPOT detected and used
I/LIBGL   (16930): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (16930): FBO are in core, and so used

I/LIBGL   (16930): PointSprite are in core, and so used
I/LIBGL   (16930): CubeMap are in core, and so used

I/LIBGL   (16930): BlendColor is in core, and so used
I/LIBGL   (16930): Blend Substract is in core, and so used
I/LIBGL   (16930): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (16930): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (16930): Extension GL_OES_mapbuffer  detected
I/LIBGL   (16930): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (16930): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (16930): Extension GL_OES_depth24  detected and used
I/LIBGL   (16930): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (16930): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (16930): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (16930): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (16930): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (16930): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (16930): Extension GL_EXT_color_buffer_half_float  detect
ed and used
I/LIBGL   (16930): high precision float in fragment shader available and used
I/LIBGL   (16930): Max vertex attrib: 16
I/LIBGL   (16930): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (16930): Max texture size: 8192
I/LIBGL   (16930): Max Varying Vector: 15
I/LIBGL   (16930): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (16930): Hardware vendor is ARM

I/LIBGL   (16930): GLSL 300 es supported
I/LIBGL   (16930): GLSL 310 es supported and used
I/LIBGL   (16930): GLSL 320 es supported
I/LIBGL   (16930): Max Color Attachments: 4 / Draw buffers: 4

I/LIBGL   (16930): EGLImage to Texture2D supported
I/LIBGL   (16930): EGLImage to RenderBuffer supported
I/LIBGL   (16930): ignore MipMap
I/LIBGL   (16930): Targeting OpenGL 2.1
I/LIBGL   (16930): No hack in shader converter to define overloaded function with int
I/LIBGL   (16930): NPOT texture handled in hardware
I/LIBGL   (16930): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (16930): try to use VBO
I/LIBGL   (16930): glXMakeCurrent FBO workaround enabled
I/LIBGL   (16930): FBO workaround for using binded texture enabled
I/LIBGL   (16930): glX Will try to recycle EGL Surface
I/LIBGL   (16930): Current folder is:/
I/jrelog  (16930): dlopen libgl4es_114.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success

I/jrelog  (16930): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (16930): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (16930): dlopen /data/app/net.kdt.pojavlaunch-2/lib/arm64/libopenal.so success

I/jrelog  (16930): Done processing args

I/jrelog  (16930): Found JLI lib
I/jrelog  (16930): Calling JLI_Launch

2022-11-23 02:06:52,369 main ERROR appender Console has no parameter that matches element Policies
[02:06:53] [main/INFO]: Loading for game Minecraft 1.16.5
[02:06:54] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[02:06:54] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
Exception in thread "main" 
java.lang.RuntimeException: Failed to remap '/storage/emulated/0/games/PojavLauncher/.minecraft/versions/fabric-loader-0.11.0-1.16.5/fabric-loader-0.11.0-1.16.5.jar'!
	at net.fabricmc.loader.launch.common.FabricLauncherBase.deobfuscate(FabricLauncherBase.java:154)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:109)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.nio.file.FileSystemException: /storage/emulated/0/games/PojavLauncher/.minecraft/.fabric/remappedJars/minecraft-1.16.5/zipfstmp8519280630857058390.tmp: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:277)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:299)
	at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2167)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.sync(ZipFileSystem.java:1853)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.lambda$close$9(ZipFileSystem.java:479)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:478)
	at net.fabricmc.tinyremapper.OutputConsumerPath.close(OutputConsumerPath.java:315)
	at net.fabricmc.loader.launch.common.FabricLauncherBase.deobfuscate(FabricLauncherBase.java:153)
	... 2 more
I/jrelog  (16930): Going to free args
I/jrelog  (16930): Free done

Java Exit code: 1

### Steps To Reproduce

```markdown
1.Open PojavLauncher
2.Select Fabric version
3.Launch the game
```

### Expected Behavior

I expected it to run fabric perfectly but it crashed.

### Platform

```markdown
- Device model: Oppo A71
- CPU architecture: AArch64 Processor rev 2(aarch64)
- Android version: 7.1.1
- PojavLauncher version: dahlia-159-b581c7ba8-v3_openjdk
```

**Comment by yvu78** [comment]
Gjfk

**Comment by GaucovyAero** [comment]
this is caused by your android version being old, not sure what to do, i can communicate this with the devs tho.

**Comment by Bancure99** [comment]
Oh,that's why i cannot launch fabric.Thanks for your response.
