### ISSUE TITLE
[BUG] Process Crashed With Exit Code -1

### ISSUE THREAD

**Issue by Singulaxity** [PojavLauncherTeam/PojavLauncher#3728]
### Describe the bug

Process Crashed With Exit Code -1
EVERYTIME I Try To Use Forge 1.19.2
It installs it correctly but then it cashes on startup and gives me the error code above.
Even though I don't have mods installed, and same occurs with mods.
I can't find anything about error code  -1 on the internet.

### The log file and images/videos

latestlog.txt

### Steps To Reproduce

```markdown
1.Install Forge
2.Open Pojav Launcher
3.Tap Play With Forge 1.19.2 (No Mods)
4.Error Code -1
```

### Expected Behavior

I expect the game to launch.

### Platform

```markdown
- Device model: M2007J20CG
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Please help

**Comment by artdeell** [comment]
no log and no pojav version

**Comment by Singulaxity** [comment]
How do I add

**Comment by GaucovyAero** [comment]
> How do I add

send latestlog.txt

**Comment by GaucovyAero** [comment]
stale
