### ISSUE TITLE
Cannot connect to servers with Cloudflare DNS

### ISSUE THREAD

**Issue by Sirccet** [PojavLauncherTeam/PojavLauncher#3730]
### Describe the bug

Я захожу в майнкрафт, добавляю сервер в список серверов захожу на сервер и мне пишет "Unknown host"
 Вот ip который я вводил: mc.auraland.ru

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
What version of Pojav are you running?

**Comment by Sirccet** [comment]
Как понять какая версия?

**Comment by Sirccet** [comment]
У меня последняя версия. Скачана с Google play

**Comment by GaucovyAero** [comment]
> У меня последняя версия. Скачана с Google play

Have you tried switching between using mobile data and wifi?

**Comment by Sirccet** [comment]
Да

**Comment by Sirccet** [comment]
Всё равно не помогло

**Comment by dxcvvxd** [comment]
значит провайдер такой.
с ним решать и надо.

**Comment by GaucovyAero** [comment]
> Всё равно не помогло

Well, looks like for some servers you have to use a direct IP. Try getting that from the server owner.

**Comment by treierxyz** [comment]
I have the same problem, can't connect to my server using the domain name. "Unknown host". Running dahlia-176-641eae051-v3_openjdk from Play Store on Android 13.

**Comment by treierxyz** [comment]
I already think I figured it out. It seems like this is caused by Cloudflare proxying domains. When I use an unproxied subdomain I can get it working. This still doesn't fix the underlying issue, you don't need to do this for regular desktop clients.

**Comment by GaucovyAero** [comment]
closing in favor of #4479
