### ISSUE TITLE
[BUG] Mouse moving on a grid when turning camera

### ISSUE THREAD

**Issue by ArcyTeo000** [PojavLauncherTeam/PojavLauncher#3731]
### Describe the bug

When I join world, and move camera with mouse, it moves like on a grid. It moves only verticaly and horizontaly, not diagonaly. When I move mouse in menu or wherever else, it moves smoothly. I have a USB C hub/dock (however you call it), it has plugged in a keyboard and a mouse. when I unplug the keyboard, the effect is the same. It doesn't matter if I do that in Dex or in tablet mode, it behaves the same. It can be seen the best at the end of the video.

### The log file and images/videos

https://user-images.githubusercontent.com/76416909/203654090-927941dd-57bc-406d-914f-006b8163b8da.mp4

### Steps To Reproduce

```markdown
1. Start Pojav Launcher.
2. Join any world.
3. Turn your camera with mouse plugged in (cable mouse).
```

### Expected Behavior

I expect the mouse to not move on grid, because when I move camera with touch, it doesn't occur.

### Platform

```markdown
- Device model: Samsung Galaxy Tab S8 (11 inch model, without 5G)
- CPU architecture: ARM 64bit (???)
- Android version: 12L (the latest before Android 13, since I still don't have it)
- PojavLauncher version: Latest as for 23.11.2022, where it says: "Use the version ID from extra to run the game #4082"
```

**Comment by GaucovyAero** [comment]
samsung issue, we cannot fix this
