### ISSUE TITLE
chat not opening (not apk)

### ISSUE THREAD

**Issue by razomazo** [PojavLauncherTeam/PojavLauncher#3732]
### Describe the bug

when i press the chat button its not opening the chat i tried sending a custom keycode and changed the controls it still didnt open the chat, so if anyone knows the reason for this please respond

### The log file and images/videos

1

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. join a singleplayer game
3. press the chat button
```

### Expected Behavior

i expect the chat to open

### Platform

```markdown
- PojavLauncher version: dahlia-176-641eae051-v3_opendjk
```

**Comment by GaucovyAero** [comment]
update to the latest github actions build

**Comment by razomazo** [comment]
how do i do that?

**Comment by GaucovyAero** [comment]
> how do i do that?

click on actions here on this page, click on the latest build with a green checkmark on it and download `app-debug`

**Comment by TheRealPro3737626** [comment]
It's not working even on a single player game what should I do

**Comment by GaucovyAero** [comment]
> It's not working even on a single player game what should I do

create a new ticket and fill it out
