### ISSUE TITLE
[BUG] Game does not start

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#3734]
### Describe the bug

When I turn this feature on, the game will not run and the log will not have any content.

### The log file and images/videos

![IMG_20221126_191414](https://user-images.githubusercontent.com/73945464/204086167-96728090-529c-4ed9-bb79-9f7e1c7d1568.jpg)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: redmi
- CPU architecture: arch64
- Android version: 10
- PojavLauncher version: dahlia-185-ef36c96ed-v3_openjdk
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
cant reproduce, works fine for me, im on the same pojav build as you are

**Comment by GaucovyAero** [comment]
could you maybe record a video of your video and renderer settings and the game not launching?

**Comment by T-CATHOME** [comment]
@GaucovyAero 

> could you maybe record a video of your video and renderer settings and the game not launching?

![Screenshot_2022-11-27-01-08-01-045_com miui video](https://user-images.githubusercontent.com/73945464/204100562-a534e2aa-4cc2-40fe-8f46-e96f407c5fc6.jpg)
![Screenshot_2022-11-27-01-07-34-134_com miui video](https://user-images.githubusercontent.com/73945464/204100574-224822b8-6151-4252-be19-570dc61bc081.jpg)
![Screenshot_2022-11-27-01-07-19-197_com miui video](https://user-images.githubusercontent.com/73945464/204100580-04fda274-b4f2-4692-b366-710b4b73faac.jpg)
![Screenshot_2022-11-27-01-06-44-739_com miui video](https://user-images.githubusercontent.com/73945464/204100584-360e2857-33e9-4388-9d9b-c332718d34b4.jpg)

**Comment by GaucovyAero** [comment]
1. dont use custom java
2. use gl4es
3. make sure you use the correct java version for each minecraft version. only 1.17 and higher requires java 17, while others run on java 8

**Comment by SYZYGYGAMER** [comment]
I also face the same problem on Chromebook
