### ISSUE TITLE
[BUG] <pojav launcher crashing with code 1  in chrome book>

### ISSUE THREAD

**Issue by SYZYGYGAMER** [PojavLauncherTeam/PojavLauncher#3737]
### Describe the bug

When I launch Minecraft in pojav launcher it crashes 

### The log file and images/videos

![91D77380-A745-4F49-953F-4A8FC2F26077](https://user-images.githubusercontent.com/114241650/204123241-5fe7b439-a6aa-4b0e-b314-99de620edb32.jpeg)
![6B2A5DED-5277-4BD7-B837-2C69C0140859](https://user-images.githubusercontent.com/114241650/204123245-693d5579-0c72-43ab-a8d6-393c5c55b637.jpeg)
![DB26B80A-3063-412C-947D-5D41046FE4D6](https://user-images.githubusercontent.com/114241650/204123247-63ff57b6-c375-4b0a-b164-d01a1ba652ed.jpeg)
![2F401D1D-D078-4AD2-B235-60201209C990](https://user-images.githubusercontent.com/114241650/204123249-0ff52c1d-f09a-4455-acd5-b5832dd465f3.jpeg)
![1085D758-434A-42F8-80BB-C33DBBA912BC](https://user-images.githubusercontent.com/114241650/204123252-49d95b8e-c7be-4398-b1b5-9e24ea2cb460.jpeg)
![AD2DFDF7-35DC-4EE7-B81B-15D0FA113C88](https://user-images.githubusercontent.com/114241650/204123254-3f6b8a74-9371-4fd9-ad1d-eb492a92d3a1.jpeg)
![60C3314E-C699-4396-8E34-3345B5978ED5](https://user-images.githubusercontent.com/114241650/204123256-04b91ba3-5cc4-4100-9836-3e09ba718055.jpeg)
![9955D2FA-E9F1-43E4-B290-4E5A380888CA](https://user-images.githubusercontent.com/114241650/204123258-663a9df2-a734-44e5-8876-ce464f7cd2ad.jpeg)
![9709874C-7720-4D16-B7CF-A216A317CB80](https://user-images.githubusercontent.com/114241650/204123260-1ed0b1b8-717e-4d7b-b618-0cd210671d87.jpeg)
![95DB423C-D3E7-41DE-A0E0-E6D2D1F92766](https://user-images.githubusercontent.com/114241650/204123261-a59fcd93-0e2c-401d-997b-97729e3085d4.jpeg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10097714/latestlog.txt)

### Steps To Reproduce

```markdown
1 start pojav launcher 
2 launch 1.8.9 or any version you like
```

### Expected Behavior

Crashes with code 1 or doesn’t even load or work goes to a black screen with just controls and just does not launch the game basically 

### Platform

```markdown
- Device model: chrome 11 3180 P26T model dell 
- CPU architecture: broad ware architecture (intel Gen8) 
- Android version: chrome os 103.0.5060.132
- PojavLauncher version: latest in play store
```

### Anything else?

Idk if I’m supposed to use pojav in Chromebook if not sorry

**Comment by GaucovyAero** [comment]
reinstall pojav from play store and make sure to wait if it freezes
