### ISSUE TITLE
[BUG] VirGL problem with replay mod 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#3738]
### Describe the bug

When rendering a video in replay mod on VirGL, something incomprehensible happens. There is no such problem on zink. 

### The log file and images/videos

https://user-images.githubusercontent.com/75908293/204142863-5556d6eb-412d-40aa-8a67-60c0ab68c62a.mp4

### Steps To Reproduce

```markdown
1. Launch pojavlancher 
2. Chose a renderer VirGL 
3. Launched minecraft 1.16.5 fabric
4. Opened replay recording
5. Start video rendering
```

### Expected Behavior

. 

### Platform

```markdown
- Device model: huawei nova 9 se 8/128
- CPU architecture: aarch64
- Android version: emui 12
- PojavLauncher version: Latest release in action
```

**Comment by GaucovyAero** [comment]
we can't fix this, if you need zink, just grab an old build of Pojav.
