### ISSUE TITLE
PojavLauncher crashes when i try to load a server's terrain v1.19.2

### ISSUE THREAD

**Issue by bravebeatT** [PojavLauncherTeam/PojavLauncher#3739]
### Describe the bug

Probably my CPU is not powerful at all i want to enable Vertex Buffer Objects but couldnt find it in my settings can you help 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10098713/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start PojavLauncher 1.19.2
2.Click Multiplayer and join a random server
3.Wait for the game to load
4.Get a crash
```

### Expected Behavior

I expect the game to load the server.

### Platform

```markdown
- Device model: General Mobile Gm22 Pro 8/128G
- CPU architecture: Mediatek Helio G95 arm64
- Android version: 11
- PojavLauncher version: 3.3.1.1
```

### Anything else?

> My GPU is
MaliG76

**Comment by GaucovyAero** [comment]
not possible
