### ISSUE TITLE
[BUG] Screen delaying/lagging while hitting or placing blocks with pysical mouse

### ISSUE THREAD

**Issue by SurgiGG** [PojavLauncherTeam/PojavLauncher#3740]
### Describe the bug

When i hit or place block, the screen lags/delays and game becomes unplayable please fix this.
Didn't had this issue in earlier version.

### The log file and images/videos

The screen lags.

### Steps To Reproduce

```markdown
1. Start game
2. Hit in air or a player
3. Screen starts delaying or lagging.
```

### Expected Behavior

Screen be smooth.

### Platform

```markdown
- Device model: Samsung Galaxy a51
- CPU architecture: aa
- Android version: 12
- PojavLauncher version: Latest
```

### Anything else?

Please fix this issue as soon as possible.

**Comment by SurgiGG** [comment]
Please help, its been 6 days.
No reply.

**Comment by GaucovyAero** [comment]
> Please help, its been 6 days. No reply.

well it works fine on custom roms, so yeah

**Comment by GaucovyAero** [comment]
i mean ive always had issues with samsung's input system but i dont understand the fact that it apparently worked on older versions

**Comment by Stormysoap** [comment]
I have this exact same bug on my Samsung and it only started doing this since the update which changed the pojav ui
