### ISSUE TITLE
[BUG] crash when joining on WynnCraft server

### ISSUE THREAD

**Issue by VlipperGZ** [PojavLauncherTeam/PojavLauncher#3741]
### Describe the bug

The game crashes every time I interact with the npc there, it's like taking a quest

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10110812/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Login with Microsoft
3. Play with 1.15.2
4. Join WynnCraft server
```

### Expected Behavior

please fix it because I want to play on that server

### Platform

```markdown
- Device model: Vivo 2007 3/32G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: dahlia-185-ef36c96ed-v3_openjdk
```

### Anything else?

I've tried all versions and it still crashes

**Comment by GaucovyAero** [comment]
its their issue, they have some weird memory leak that makes the game die on pojav
