### ISSUE TITLE
Application exited with code 1 when installing .jar

### ISSUE THREAD

**Issue by gabfodastico** [PojavLauncherTeam/PojavLauncher#3742]
### Describe the bug

The error Application exited with code 1 happens when I try to execute the fabric installer version 0.11.1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10114856/latestlog.txt)

### Steps To Reproduce

```markdown
Click Install .jar
Select fabric-installer-0.11.1.jar
```

### Expected Behavior

fabric-installer-0.11.1.jar open without any errors

### Platform

```markdown
- Device model: Moto G60
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Release (Google Play)
```

**Comment by Andros42** [comment]
Same problem with me :..(

**Comment by GaucovyAero** [comment]
rotate your screen into landscape mode
