### ISSUE TITLE
[BUG] Buildcraft graphics glitch

### ISSUE THREAD

**Issue by L00K3** [PojavLauncherTeam/PojavLauncher#3745]
### Describe the bug

When Buildcraft is included in the mods the game fails to correctly render transparency making some vanilla opaque blocks transparent. This effect should be visible immediately when starting a game. The version is 7.99.24.8 running on Minecraft 12.2 and forge 14.23.5.2860

### The log file and images/videos

![Uploading Screenshot_20221202-190648_PojavLauncher_(Minecraft_Java_Edition_for_Android).png…]()

### Steps To Reproduce

```markdown
1) Install forge 14.23.5.2860
2) Add Buildcraft 7.99.24.8
3) Start Game
4) Create new survival with default world generation
```

### Expected Behavior

Some terrain will be transparent when it should be opaque, the terrain can still be interacted normally.

### Platform

```markdown
- Device model: Razer Phone 2
- CPU architecture: arm64
- Android version: 12 via Linage OS
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
press f11
