### ISSUE TITLE
[BUG] game not launching

### ISSUE THREAD

**Issue by 3v4ng310u5** [PojavLauncherTeam/PojavLauncher#3747]
### Describe the bug

when I click play and go to the game screen nothing happens, I can modify controls, but the game never starts 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10140956/latestlog.txt)
![Screenshot_20221202_131101_net kdt pojavlaunch](https://user-images.githubusercontent.com/107330167/205290148-e87331cb-489f-4310-b875-46bbabd35354.jpg)

### Steps To Reproduce

```markdown
I don't know how to reproduce this
```

### Expected Behavior

I expected to see the loading minecraft screen

### Platform

```markdown
- Device model: huawei p30 lite
- CPU architecture: 
- Android version: 10 or 11
- EMUI version: 12.0.0
- PojavLauncher version: latest
```

**Comment by Fl414r** [comment]
Same bug. I try versions Android CL #4082 and #4076. 
But "Install .jar" work, I can install Fabric.
(Honor 9C (AKA-L29), Android 10)
upd. Last Google Play Release work

**Comment by GaucovyAero** [comment]
if you are installing pojav, make sure to always uninstall pojav, remove all its data and restart your phone, only then you can install new pojav

**Comment by Julienraptor01** [comment]
> if you are installing pojav, make sure to always uninstall pojav, remove all its data and restart your phone, only then you can install new pojav

I did this and stil have the issue personnally.
The launcher seems to be far more unstable for me since the new UI version.

**Comment by Gadet-0** [comment]
Well are you trying to launch the game with `Start with virtual mouse option on`? if yes, please try to disable it and then launch the game

**Comment by Fl414r** [comment]
> Well are you trying to launch the game with `Start with virtual mouse option on`? if yes, please try to disable it and then launch the game

It works...

**Comment by GaucovyAero** [comment]
fixed
