### ISSUE TITLE
[F-Req] Give A Support The Angle Renderer For Shader

### ISSUE THREAD

**Issue by Jazlenkate** [PojavLauncherTeam/PojavLauncher#3748]
### Describe the request.

Can you add a Shader support for Angle Renderer that very optimized for all device's so they can try to test shader like bsl, complementary,sildurs vibrant and many more to support all GPU phones that will be the greatest update for pojav users because some of the pojavlauncher user are more likely shaders in the Mobile,thanks Pojavlauncher Team I hope you can add my req feature.

**Comment by Andros42** [comment]
Yes, it is true, but first pojavlauncher should fix the bugs, like jar installer not work angle renderer glitch in optifine 1.19.2

**Comment by GaucovyAero** [comment]
nope, not possible

**Comment by Natthakritp** [comment]
That's what makes it not work.
