### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by PortFeather7324** [PojavLauncherTeam/PojavLauncher#3749]
### Describe the bug

Cancel the right mouse button to return to invalid
When I click the right button, it is the default return of Android system.
Doesn't make the right button work as well as it used to

### The log file and images/videos

![Screenshot_2022-12-02-22-31-13-56_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/117568975/205319373-19cb4014-fa1e-4c96-9872-89a2698256ff.jpg)

### Steps To Reproduce

```markdown
The right button cannot be forced
```

### Expected Behavior

I wish I could force the right button to work like before.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
