### ISSUE TITLE
Plz fix it

### ISSUE THREAD

**Issue by Shubham-hahh** [PojavLauncherTeam/PojavLauncher#3753]
### Describe the bug

When clicking in gui and opening settings the task bar is cut in half.

### The log file and images/videos

![Screenshot_2022-12-04-10-51-35-152_net kdt pojavlaunch](https://user-images.githubusercontent.com/85120228/205475986-103e575c-8673-4e97-89eb-672f175512f6.jpg)

### Steps To Reproduce

```markdown
1. Start Pojavluacher
2. Click on play 
3. Click on gui on the deafult cobtrolmap 
4. The task bar is cut in half
```

### Expected Behavior

I saw the task bar is cut in half. Only force close to mouse speed is showing where are the other options.

### Platform

```markdown
- Device model: Poco C3
- CPU architecture: aarch32
- Android version: 10
- PojavLauncher version: dalhila-176-641eae051-v3_openjdk
```

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
