### ISSUE TITLE
Make the laucher fully customisable 

### ISSUE THREAD

**Issue by Shubham-hahh** [PojavLauncherTeam/PojavLauncher#3754]
### Is this request related to a bug?

Many minecraft lauchers especially many lauchers have the ability to customize it like your own taste. 

### Describe the request.

I would like to have the ability to change the background of the laucher, change the theme, also customisable launcher icon. Especially i would like to have two mods in one version installed. Eg -
version : 1.16.5
mods : Optifine + Forge

**Comment by sswarior26** [comment]
They should add compability to patcher mod also.

**Comment by GaucovyAero** [comment]
> They should add compability to patcher mod also.

https://www.mediafire.com/file/7a3gubce278k338/Patcher-1.6.1_1.8.9.jar/file moment

**Comment by sswarior26** [comment]
> > They should add compability to patcher mod also.
> 
> https://www.mediafire.com/file/7a3gubce278k338/Patcher-1.6.1_1.8.9.jar/file moment

Thanks, but whenever i start the game, text gets black

**Comment by TrollTransplantYT** [comment]
Optifine can run on forge if you put it in the mods folder

**Comment by GaucovyAero** [comment]
stale
