### ISSUE TITLE
libs finding error

### ISSUE THREAD

**Issue by jelebruh** [PojavLauncherTeam/PojavLauncher#3755]
### Describe the bug

I want to add my runtime, but always have "libawt_xawt" ENOENT.
But in archive I have libawt_xawt.so

### The log file and images/videos

![Screenshot_2022-12-05-12-29-25-19_61c78dc80ee02b53007c815fefe993e3](https://user-images.githubusercontent.com/90205154/205603105-acf53675-ad89-4308-b65b-4727116d7f69.jpg)
![Screenshot_2022-12-05-12-29-06-08_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/90205154/205603117-b3b6ceb7-3361-4061-92a1-1c22b194c11c.jpg)

### Steps To Reproduce

```markdown
1. Open runtimes list
2. Add runtime (I have openjdk)
3. Look!!
```

### Expected Behavior

Runtime added without error

### Platform

```markdown
- Device model: RMX3081 (realme 8 Pro)
- CPU architecture: 64
- Android version: 12
- PojavLauncher version: Dahila 135 (from GPlay)
```

**Comment by khanhduytran0** [comment]
I don’t know where you got the runtime (or compiled it?) but the extracted path is `/data/data/net.kdt.pojavlaunch/runtimes/jopen17.tar (1).xz/jdk-17.0.2/lib/libawt_xawt.so`. So, what you need to do is compress sub-folders, not the folder containing them.
If you just want to play 1.17+, simply tap Play and the builtin Java 17 will be installed before launching.

**Comment by jelebruh** [comment]
> So, what you need to do is compress sub-folders, not the folder containing them.

Why in task "log" I see other libs in this case? This stack only on libawt.



> If you just want to play 1.17+, simply tap Play and the builtin Java 17 will be installed before launching.

Thanks, captain, I need to test a com.sun.jna.nativelibrary error, but I check it with other way 

@khanhduytran0

**Comment by jelebruh** [comment]
![IMG_20221205_223355.jpg](https://user-images.githubusercontent.com/90205154/205726677-13e820cc-9330-4d14-822b-1d98f2b0faae.jpg)
![IMG_20221205_223500.jpg](https://user-images.githubusercontent.com/90205154/205726810-475e1c53-0679-4291-af5e-94e73c34cfed.jpg)

**Comment by GaucovyAero** [comment]
stale
