### ISSUE TITLE
[BUG] Depencies error

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3756]
### Describe the bug

After installation and playing on my modpack after a some time all is going to stop working when you going to black screen where is going loading of minecraft, problem is that in journal I see that minecraft stopped loading because of mods what needs a Depencies, problem is that in a past modpack is work well, but after a time that's doesn't work, I am deleted a folder mods with all mods but in journal I still have an error that bewitchment need's a cloth config and extra origins is needs a Origins 1.4.1 or above, but problem is that I don't have a folder mods, I am deleted them, so by idea Fabric can't see that been installed in the past but he do and that cause error what doesn't exist because all depencies is installed when that works and I am played in Minecraft so all mods are works but Fabric in one moment stopping to see a correct mods and see that mods are need depencies what is already installed, and if you just delete folder mods so fabric still said that mods need a depencies 

### The log file and images/videos

![IMG_20221205_114257](https://user-images.githubusercontent.com/71454894/205622701-8c09a81b-7405-4c9e-ad3e-306748457b19.jpg)
![Screenshot_2022-12-05-11-43-41-892_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/71454894/205622722-637b0bb4-4a7f-444c-b6be-04af4b2c1082.jpg)
![Screenshot_2022-12-05-11-43-45-406_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/71454894/205622746-e4082ed6-18d4-4bc2-9f40-695bae077d24.jpg)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Setup and start Fabric 1.18.2 with bewitchment and origins 1.4.1 (probably, exactly what mods makes broke Fabric is not determined)
3. Play in Minecraft some time
4. Exit from Minecraft
5. Wait some time
6. Get results
```

### Expected Behavior

Normal loading of modpack how before without broken Fabric

### Platform

```markdown
- Device model: POCO X3 Pro
- CPU architecture:arm64
- Android version: 12
- PojavLauncher version: 176-641 Dahilla, Latest Google Play Release
```

### Anything else?

Modpack: https://drive.google.com/file/d/11qJIWDgAFUkUDQ6gZeGBs_pyNZCEhDWH/view?usp=drivesdk

**Comment by ghost** [comment]
UPDATE: I am understand what happens, if be easier in two words that looks like that: Pojav Launcher release from Google Play in one moment starts to use debug folder of Pojav and this is not dependent on  is installed before a debug version with release version in the same time or not, if debug folder is don't exist, in that case launcher creates this is folder and continue use only this folder

**Comment by GaucovyAero** [comment]
yeah, i mean to fix your issue, install cloth config and origins

**Comment by ghost** [comment]
> yeah, i mean to fix your issue, install cloth config and origins

Now problem is why pojav launcher use two folders and change them in random time?

**Comment by GaucovyAero** [comment]
stale
