### ISSUE TITLE
[BUG] Force English 

### ISSUE THREAD

**Issue by Julienraptor01** [PojavLauncherTeam/PojavLauncher#3757]
### Describe the bug

Force English is disabled and stay like that until i exit to main menu if i put my phone in landscape 

### The log file and images/videos

Uploading Screen_Recording_20221206_082025_PojavLauncher (Minecraft Java Edition for Android).mp4…

### Steps To Reproduce

```markdown
Enable Force English
Restart the app
Go in the settings
Switch your phone to landscape
Observe your native language
Go back to main menu
See it being in English back
```

### Expected Behavior

Force English to Force English 

### Platform

```markdown
- Device model : Samsung Galaxy A52s 5G 
- CPU architecture : aarch64 
- Android version : 12 
- PojavLauncher version: Latest GPlay Release || Version dahlia-176-641eae051-v3_openjdk
```

**Comment by GaucovyAero** [comment]
upload the video

**Comment by Julienraptor01** [comment]
> upload the video

Seems like the upload has bugged, i'll see if i still have it and will send it

**Comment by Mathias-Boulay** [comment]
Hey there @Julienraptor01, the issue should be fixed with this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4018715354

**Comment by Julienraptor01** [comment]
> Hey there @Julienraptor01, the issue should be fixed with this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4018715354

Nice, can i install the CI version if the Play store version is already installed so i can test it ?

**Comment by GaucovyAero** [comment]
> > Hey there @Julienraptor01, the issue should be fixed with this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4018715354
> 
> Nice, can i install the CI version if the Play store version is already installed so i can test it ?

yep

**Comment by Julienraptor01** [comment]
Seems fixed, thanks you
