### ISSUE TITLE
[BUG] Poor performance on high-end device

### ISSUE THREAD

**Issue by spirek** [PojavLauncherTeam/PojavLauncher#3759]
![Screenshot_20221207-120557](https://user-images.githubusercontent.com/120018888/206163273-58457c3a-e75b-4cc0-b12d-d87143543f7e.png)
### Describe the bug

Hello, Im running pojav launcher on my Oukitel RT2 and I get poor performance , around 20fps on every version.I want to play beta 1.7.3  I've tried solution from another thread (gl4es and 100%res) and optifine but its not working . Also when running with optifine , chunks arent loading at all, only mobs are visible.

Android 12
CPU:MediaTek MT8788
6gb RAM
GPU: ARM Mali-G72 MP3 @800 MHz

### The log file and images/videos

nothing

### Steps To Reproduce

```markdown
Run pojav on RT2
```

### Expected Behavior

I expect more fps

### Platform

```markdown
Oukitel RT2
Android 12
CPU:MediaTek MT8788
8GB RAM
GPU: ARM Mali-G72 MP3 @800 MHz
```

**Comment by TrollTransplantYT** [comment]
Turn off the sustained performance

**Comment by GaucovyAero** [comment]
join our official discord server to get more info
