### ISSUE TITLE
[BUG] Can't run Forge 1.12.2

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#376]
I can't seem to run forge on any version
![Screenshot_20201026-123601](https://user-images.githubusercontent.com/63871578/97425429-08075e00-190a-11eb-8558-75f38a62eee4.jpg)
![Screenshot_20201026-123617](https://user-images.githubusercontent.com/63871578/97425470-105f9900-190a-11eb-8870-4398a490a65b.jpg)

**Comment by leetmussc** [comment]
It crashes after loading

**Comment by WesleyVanNeck** [comment]
known issue
