### ISSUE TITLE
Put pojavlauncher on Huawei app gallery 

### ISSUE THREAD

**Issue by RBGAMING1** [PojavLauncherTeam/PojavLauncher#3760]
### Describe the request.

Hey, I am huawei user recently i heard about this launcher i went to huawei app gallery for pojavlauncher but can't find it. It was risky to get apk so, developers please add pojavlauncher on Huawei app gallery too

**Comment by GaucovyAero** [comment]
what about using aurora store instead

**Comment by GaucovyAero** [comment]
stale
