### ISSUE TITLE
[BUG] Mouse isn't locking correctly.

### ISSUE THREAD

**Issue by AverageFemale** [PojavLauncherTeam/PojavLauncher#3761]
### Describe the bug

I whenever I use my notification bar or use an app using the pop up app feature on android while loading/joining into a server the cursor will sudden lose its mouse lock when going back into the game after I'm done loading/joining the server.
The temporary fix is to just alt tab or go to enough app and go back to the game.

### The log file and images/videos

https://user-images.githubusercontent.com/76181396/206325604-798fedaf-3caf-4932-b17b-aa6361fce762.mp4

Ignore the lag, I wasn't using forge. If you need one with less lag, lmk.

### Steps To Reproduce

```markdown
1. Start Minecraft
2. Put an app into pop up view
3. Start loading into a server or singleplayer world
4. While loading, click onto the pop up app.
5. Once done loading into the server/world, close the popup app and move your cursor.
6. Your cursor should now be free floating around instead of being locked and hidden in the center.
```

### Expected Behavior

I expected my cursor to be locked onto the center of the screen hidden once I click back into the game, like it used too.

### Platform

```markdown
- Device model: Samsung Galaxy S20+ 5G
- CPU architecture: ARM
- Android version: 12
- PojavLauncher version: Action #4085 https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3629182626
```

### Anything else?

This used to work before, some actions ago, I forget which one though.

**Comment by sarthjadhau** [comment]
My too

**Comment by AverageFemale** [comment]
Fixed.

**Comment by Cookie6612** [comment]
Can you tell me how to fix

**Comment by AverageFemale** [comment]
> Can you tell me how to fix 

This was a year ago so I don't know how to fix it for nowadays. I would suggest making a new issue.
