### ISSUE TITLE
how to edit control 

### ISSUE THREAD

**Issue by RBGAMING1** [PojavLauncherTeam/PojavLauncher#3762]
### Describe the bug

I have tried to edit control on pojavlauncher i firstly click on button but it doesn't show up editing option then i saw on upper side it say hold to edit resize so i try to hold but it doesn't open editing menu

### The log file and images/videos

https://user-images.githubusercontent.com/112553844/206347088-31448443-09d8-472a-a10c-70756430410b.mp4

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

. 

### Platform

```markdown
- Device model: huawei matepad t10 2/16
- CPU architecture: 4x ARM Cortex-A73 @ 2.00 GHz
                  : 4x ARM Cortex-A53 @ 1.70 GHZ
- Android version: 10
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
