### ISSUE TITLE
[BUG] ANGLE Render spamming in logs

### ISSUE THREAD

**Issue by Fl414r** [PojavLauncherTeam/PojavLauncher#3763]
### Describe the bug

All in description.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10182377/latestlog.txt)

### Steps To Reproduce

```markdown
1) Start Minecraft with ANGLE render.
2) Graphics Initialized
3) ANGLE start spam (But work)
```

### Expected Behavior

No Spam

### Platform

```markdown
- Device model: Honor 9C (AKA-L29)
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Release (May 28) and Android CL #4084
```

**Comment by GaucovyAero** [comment]
we cant fix this
