### ISSUE TITLE
Unable to start the game

### ISSUE THREAD

**Issue by Pplover123** [PojavLauncherTeam/PojavLauncher#3764]
### Describe the bug

Whenever I start the game it says game exited with exit code 1 on every version

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10185091/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav launcher
2.select any version
3.click start
```

### Expected Behavior

I expect the game to launch

### Platform

```markdown
- Device model: Samsung galaxy a32
- CPU architecture: 64-bit ARMv8-A
- Android version: 12
- PojavLauncher version: dahlia-176-641eae051-v3_openjdk
```

**Comment by MarcyIgop** [comment]
Version of minecraft?

**Comment by GaucovyAero** [comment]
make sure to enable "check game libraries after downloading"
