### ISSUE TITLE
[BUG] #2666 V2 (1.18.2)

### ISSUE THREAD

**Issue by jelebruh** [PojavLauncherTeam/PojavLauncher#3765]
### Describe the bug

Many mouths ago (in february) #2666 was opened with virglrenderer and fonts in game error.
Now... 7mo ago dev says, that it will be fixed in "next release candidate".... Nothing changed. All textures are black, font not loading.

### The log file and images/videos

Couldn't load Narrator library
java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna13288338118700109679.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna13288338118700109679.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"

![Screenshot_2022-12-08-21-51-26-75_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/90205154/206543835-98bc2f68-6725-4fb3-b92d-29e2af8d0177.jpg)

### Steps To Reproduce

```markdown
1. Start pojav
2. Select virglrenderer
3. Start game
4. After red screen see nothing
```

### Expected Behavior

text will be shown

### Platform

```markdown
- Device model: rmx3081 (realme 8 Pro)
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: 176 + 185 (in actions)
```

**Comment by artdeell** [comment]
virgl related bugs will not be fixed

чт, 8 дек. 2022 г., 21:59 DSA ***@***.***>:

**Comment by jelebruh** [comment]
> virgl related bugs will not be fixed


Then why it available? I think check for 87X snaps not hard thing

**Comment by artdeell** [comment]
> > virgl related bugs will not be fixed
> 
> Then why it available? I think check for 87X snaps not hard thing

because we are lazy and people would get mad if we remove it

**Comment by jelebruh** [comment]
> because we are lazy and people would get mad if we remove it
I think we can remove unstable feature or make banner about this

**Comment by GaucovyAero** [comment]
virgl may not fully work on all devices
