### ISSUE TITLE
[BUG] Reload Texture pack

### ISSUE THREAD

**Issue by anshoo2745** [PojavLauncherTeam/PojavLauncher#3766]
### Describe the bug

So basically what happened is that i want to play in mcc island and it needs a resource pack and when the texture pack downloads it always there on my screen like always and i am using optifine 1.19.2 and i offed the render regions how to fix it

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10193930/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start Pojav Launcher
2.Use Optifine 1.19.2
3.Join MCCisland
```

### Expected Behavior

I can't think sorry

### Platform

```markdown
- Device model: Realme Narzo 20
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: actions #3997
```

### Anything else?

Nope

**Comment by GaucovyAero** [comment]
use ANGLE or VirGL, gl4es crashes because of MCC Island's custom shaders

**Comment by GaucovyAero** [comment]
stale

**Comment by GaucovyAero** [comment]
stale
