### ISSUE TITLE
[BUG] Mouse isnt locking

### ISSUE THREAD

**Issue by sarthjadhau** [PojavLauncherTeam/PojavLauncher#3767]
### Describe the bug

while playing in server the mouse automaticaly start poping on screen help ....

### The log file and images/videos

na

### Steps To Reproduce

```markdown
anhjsbhabh
```

### Expected Behavior

na

### Platform

```markdown
- Device model: redmi note 5 pro
- CPU architecture: snapdragon 655
- Android version: 9.2
- PojavLauncher version: lattest
```

### Anything else?

na

**Comment by GaucovyAero** [comment]
virtual mouse or physical mouse?

**Comment by sarthjadhau** [comment]
Physical mouse

**Comment by AverageFemale** [comment]
Same #3761

**Comment by sarthjadhau** [comment]
> Same #3761

Use Hello Launcher

**Comment by WesleyVanNeck** [comment]
> > Same #3761
> 
> Use Hello Launcher

i wouldnt use it its full of bugsand isnt active anymore

**Comment by Mathias-Boulay** [comment]
Do we have a consistent way of reproducing the issue ?

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
