### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by CubyMC** [PojavLauncherTeam/PojavLauncher#3769]
### Describe the bug

The mouse is go to left about 1 mm

### The log file and images/videos

![2022-12-11_08 30 13](https://user-images.githubusercontent.com/97453924/206894087-9c610aaf-77e4-42ef-b679-4ebe91174963.png)

### Steps To Reproduce

```markdown
1. Move the mouse to the right a bit
```

### Expected Behavior

The mouse is not on center

### Platform

```markdown
- Device model: DIG-TL10
- CPU architecture: Qualcomm Snapdragon 435
- Android version: 6.0
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
enable ignore notch
