### ISSUE TITLE
After closing the MIUI13 small-window, the situation in the video will appear when you switch back from the background

### ISSUE THREAD

**Issue by routhing** [PojavLauncherTeam/PojavLauncher#3771]
### Describe the bug

As shown in this video:

### The log file and images/videos

https://user-images.githubusercontent.com/71493668/206913124-689decfe-9c80-44a3-8ffb-93908ff0626a.mp4

### Steps To Reproduce

```markdown
Open a MIUI13 small-window in the Pojav game program and then cross it out, and then switch back to the main program from the background, there will be a video in the above situation.
```

### Expected Behavior

It is hoped that the sliding mouse function, like the front end of the previous version, will be sensitive to switching between inside and outside the game. This abnormal situation of closing the small window and switching back from the background will not occur again.

### Platform

```markdown
- Device model: Redmi K50
- CPU architecture: aarch64(MT6895Z)(D8100)
- Android version: 12(MIUI13)
- PojavLauncher version: Latest Version
```

**Comment by GaucovyAero** [comment]
we are most probably not going to fix this, as it isn't an AOSP feature
