### ISSUE TITLE
Every time I try to install Forge 1.19.3, I get an error.

### ISSUE THREAD

**Issue by Kolyanpetuh** [PojavLauncherTeam/PojavLauncher#3772]
### Describe the bug

When I install Forge on version 1.19.3, I get an installation error. I've tried reinstalling the game files, but that doesn't help.

### The log file and images/videos

Here's the error I'm getting:
Processor failed, invalid outputs:

/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/clien

Expected: e0bd62d190cd8a4078069d0bb05bf9797dc32ea

Actual: 4c9bcf675ac4e1f23b577e86e2f54634813a741e

/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/clien

Expected e552266e2777e0045a578eb69dd6f689450502a

Actual: 8b485e0abf6564ac8cc6707ea2d43523af583e3d

### Steps To Reproduce

```markdown
Honestly, I don't know how to fix it. This is the first time I've come across this.
```

### Expected Behavior

I expect Forge on version 1.19.3 to install successfully.

### Platform

```markdown
- Device model: Xiaomi Redmi Note 9 Pro
- CPU architecture: Qualcomm Snapdragon 720G
- Android version: 13
- PojavLauncher version: dahlia-176-641eae051-v3_openjdk
```

### Anything else?

Here is a photo of this error:
![Uploading Screenshot_20221212-140336_PojavLauncher (Minecraft_ Java Edition для Android).png…]()

**Comment by GaucovyAero** [comment]
dont use chrome as your main browser

**Comment by Kolyanpetuh** [comment]
> не используйте Chrome в качестве основного браузера

But how can the browser affect the installation of Forge? It downloaded normally, it's PojavLauncher can not install it.

**Comment by Illia24** [comment]
TRY JAVA 8 IT WORKED!

**Comment by Clank50AE** [comment]
> TRY JAVA 8 IT WORKED!

I can confirm this works. Set the default Java environment to Java 8. I'm installing atm7 and had this issue. change to 17 to load atm 7

**Comment by GaucovyAero** [comment]
fixed
