### ISSUE TITLE
[BUG] <Unable to multi-touch in Android 13>

### ISSUE THREAD

**Issue by User9426** [PojavLauncherTeam/PojavLauncher#3773]
### Describe the bug

When touching the screen with two or more fingers, the "slidable" button is not slidable.

### The log file and images/videos

https://user-images.githubusercontent.com/98791793/207016543-5dda4c65-55e0-49db-847a-19ea3c35f7d6.mp4

### Steps To Reproduce

```markdown
1.Start PojavLauncher.
2.Start the game.
3.Slide the slideable button
4.The slideable button is working.
5.Touch the screen with another finger
6.Slide the slideable button again.
7.It doesn't work.
```

### Expected Behavior

The slide button works properly when multi-fingered.

### Platform

```markdown
- Device model: Mi 10S 8/256g
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: dahlia-187-16d8128b4-v 3_openjdk
```

### Anything else?

I think this is more of a MIUI 14 bug than the PojavLaunhcer itself.

**Comment by GaucovyAero** [comment]
duplicate issue
