### ISSUE TITLE
[F-Req] File manager or shortcut to one

### ISSUE THREAD

**Issue by Madis0** [PojavLauncherTeam/PojavLauncher#3774]
### Is this request related to a bug?

People want an easy way to access their .minecraft folder to manage worlds, resource packs, mods etc.

### Describe the request.

Pojav Launcher should bundle a file manager for its .minecraft folder or have a button that would open that in any of the installed file managers.

### Anything else?

It should also be compatible with in-game means, aka the datapacks folder button, resource packs folder button, mod folder button.

**Comment by Mathias-Boulay** [comment]
Hello there, you can already access all your pojav files though SAF, on the stock file manager :smile:

**Comment by Madis0** [comment]
I did realize that later, yes. But not everyone realizes this nor does everyone know how to open the stock file manager, so a simple shortcut could help.

**Comment by GaucovyAero** [comment]
use MiX
