### ISSUE TITLE
[Better Controls idea] <I have the controls solution>

### ISSUE THREAD

**Issue by TrollTransplantYT** [PojavLauncherTeam/PojavLauncher#3776]
### Describe the request.

Add in key mapping for the android volume buttons to break and attack. Also put the jump on the other side of the screen with shippable on by default.

### Anything else?

It makes the game feel more natural on mobile and more playable

**Comment by anshoo2745** [comment]
But bro if the volume is more what will do then actually if we want to volume up and down so please don't get this f request

**Comment by TrollTransplantYT** [comment]
Just a button mapper. You can set it to map only one volume key and click the other and use your slider to change the volume. I hope this helps your understanding.

**Comment by GaucovyAero** [comment]
i'm pretty sure this might not work for all devices.
