### ISSUE TITLE
Angle Render for 1.12.2 please 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3777]
### Is this request related to a bug?

 Vic modern warfare no lite when I fire the gun I try to use VirGl Render it's working
Not for holygl

### Describe the request.

 Vic modern warfare no lite when I fire the gun I try to use VirGl Render it's working
Not for holygl

### Anything else?

 Vic modern warfare no lite when I fire the gun I try to use VirGl Render it's working
Not for holygl

**Comment by GaucovyAero** [comment]
angle only works with 1.17+
