### ISSUE TITLE
[BUG] вертуальная мышь

### ISSUE THREAD

**Issue by SKILLPLAY220** [PojavLauncherTeam/PojavLauncher#3778]
### Describe the bug

У меня с право экрана находится полоса "барьер" в который я не могу плместить кнопку или передвинуть туда мышь например: я навожусь на кнопку настройки но хитбокс мышки наводится на кнопку провее

### The log file and images/videos

Не знаю как загрузить видео(

### Steps To Reproduce

```markdown
1. Заходим в игру
2. нводимся на любую кнопку (мышью)
```

### Expected Behavior

я ожидал что мышь бужет работать корректно

### Platform

```markdown
- Device model:Honor 7C 3/32 
- CPU architecture:Snapdragon 420
- Android version:8 
- PojavLauncher version:Самая новая версия
```

### Anything else?

Кнопки нельзя переташить до упора в право

**Comment by GaucovyAero** [comment]
stale, you have to press the GUI button
