### ISSUE TITLE
[BUG]  controller functions are broken 

### ISSUE THREAD

**Issue by Bendyg7** [PojavLauncherTeam/PojavLauncher#3779]
### Describe the bug

The buttons (A B X Y Start and Select) are not working and with wrong functions like the button B does back button function and Y does the space bar 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10237924/latestlog.txt)

### Steps To Reproduce

```markdown
1. Launch the game with the controller on
2. Activated gamepad controls
```

### Expected Behavior

The gamepad controls are broken 

### Platform

```markdown
- Device model: Realme 5 Pro 4/128G
- CPU architecture: aarch64 
- Android version: 11
- PojavLauncher version: [Latest Release || version dahlia-176-641eae051-v3_openjdk
```

**Comment by GaucovyAero** [comment]
not all controllers work, only the xbox one is supported
