### ISSUE TITLE
[BUG] Minecraft 1.0 an below not running correctly on v2

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#378]
**Expected behavior**
I expected ...

**Screenshots**
![Screenshot_20201030-081256](https://user-images.githubusercontent.com/63871578/97676148-1a0f0b00-1a88-11eb-97d6-0fd9cacb4bfc.jpg)
![Screenshot_20201030-080905](https://user-images.githubusercontent.com/63871578/97676163-1e3b2880-1a88-11eb-9be7-36d2da874d46.jpg)

**Platform:**
 - Device Model Huawei Y7
 - CPU architecture aarch64
 - Android Version 8.1.0

**Comment by leetmussc** [comment]
Help please, I need this fixed ASAP

**Comment by CosineMath** [comment]
Current focus is 1.13+. This version is too old and might be abandoned.

**Comment by khanhduytran0** [comment]
> Help please, I need this fixed ASAP 

Press F11, then it will render correctly.

**Comment by mfjfkfjf** [comment]
Well if they're going to be abandoning those versions then I'm really sad because I've always wanted to play Minecraft Classic on my phone and Alpha Beta and infdev

**Comment by khanhduytran0** [comment]
> Press F11, then it will render correctly.

What about this??
