### ISSUE TITLE
[BUG] wtf???

### ISSUE THREAD

**Issue by SrOnstiw** [PojavLauncherTeam/PojavLauncher#3782]
### Describe the bug

I installed 1.12.2 and I play and I got Application/Game exited with code -1, check latestlog.txt for more details. Why pojav launcher...

### The log file and images/videos

The Video
https://drive.google.com/file/d/1-RHG9BmZhEIUwClOsR1IN5HMvQ6feF-F/view?usp=drivesdk

### Steps To Reproduce

```markdown
1:I play 1.12.2
2:I got Application/Game exited with code -1, check latestlog.txt for more details.
3:wtf...
```

### Expected Behavior

I don't know

### Platform

```markdown
- Device model:Xiaomi Redmi Note 11
- CPU architecture:I don't know
- Android version:12
- PojavLauncher version:lastest debug build
```

### Anything else?

No one's Responses...

**Comment by mchnjt** [comment]
We don't know what problem you're facing. We're not wizards with the power to get your logs. Please send latestlog.txt.

Send it as a file, not text.

**Comment by GaucovyAero** [comment]
stale
