### ISSUE TITLE
[BUG] <Render Region (Optifine) crashes the game when world is loaded>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3783]
### Describe the bug

Whenever I try loading a world or joining a server, it will crash if Render Region is enabled in OptiFine.

### The log file and images/videos

[latestlog.old_2.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10249684/latestlog.old_2.txt)
![image](https://user-images.githubusercontent.com/94125093/208198558-17312dce-c5ec-46a6-8860-0e3ff339e5a6.png)

### Steps To Reproduce

```markdown
1. Install 1.19.2 OptiFine HD U H9
2. Run 1.19.2-OptiFine_HD_U_H9
3. Go to Options... > Video Settings... > Performance... > Turn Render Regions to ON
4. Go to any world or server.
```

### Expected Behavior

When the world is finished loading, it crashes with code 6, followed by the log screen.
The game may become unresponsive.

### Platform

```markdown
- Device model: iPad Pro 11-inch 4th Generation 8/256G (iPad14,3)
- CPU architecture: aarch64
- Android version: iOS 16.1.1
- PojavLauncher version: 2.1-release (main/ec106e2) (Unjailbroken)
```

**Comment by khanhduytran0** [comment]
> Android version: iOS 16.1.1

well.. did you even notice that you created issue in wrong repository? For new issue, please go to [PojavLauncher_iOS](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues)


Render regions, which makes use of multidraw functions, isn’t supported for now. Please keep it disabled, until we find out solution for proper multidraw.
