### ISSUE TITLE
[BUG] it's take so long to load only black screen

### ISSUE THREAD

**Issue by SrOnstiw** [PojavLauncherTeam/PojavLauncher#3784]
### Describe the bug

I open the app I installed 1.16.5 and play it and it's only black screen and takes so long to load

### The log file and images/videos

![Screenshot_2022-12-17-13-51-23-250_net kdt pojavlaunch](https://user-images.githubusercontent.com/120690191/208252642-1fd92986-88d8-44f0-b0c8-26a0cf91d4d2.jpg)

### Steps To Reproduce

```markdown
1 I open pojav
2 I installed 1.16.5
3 I play it and takes so long to load only black screen
```

### Expected Behavior

???

### Platform

```markdown
- Device model:Redmi Note 11
- CPU architecture:I don't know
- Android version:12
- PojavLauncher version:play store version
```

### Anything else?

???

**Comment by GaucovyAero** [comment]
reinstall pojav

**Comment by kurox313** [comment]
my man try 1.16.5 if it works means your device does not work with the latest build if nothing then clear some files and it might fix it

**Comment by GaucovyAero** [comment]
stale

**Comment by GaucovyAero** [comment]
stale
