### ISSUE TITLE
Internet Not Working in the launcher

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3785]
### Describe the bug

Whenever I play the game, a red border appear in the home menu. The internet not working in the game and I also am not able to play servers. This is very problematic. I have copied the issue please check. I also checked that the data access are denied or not but they are ok.

### The log file and images/videos

![Screenshot_2022-12-17-22-25-11-16_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/116268548/208252849-e1870010-8653-44a0-a549-7ab6b0ef56be.jpg)
![Screenshot_2022-12-17-22-25-21-88_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/116268548/208252851-45be0253-92b4-4949-84a3-ea0ef8b517e3.jpg)

### Steps To Reproduce

```markdown
1) Start the launcher
2) A red border appears and a great pop up box shows that Error Not Found and the internet don't work in the launcher
```

### Expected Behavior

The game should have consumed the internet normally.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Hopefully no

**Comment by ghost** [comment]
Here's the code below:
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.throwResponseError(MicrosoftBackgroundLogin.java:324)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:278)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:76)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by khanhduytran0** [comment]
Your Microsoft account ran into a problem.
If you got access by Xbox Gamepass subscription, it might’ve been expired, so your Minecraft profile was revoked.
Else, if you bought Minecraft, remove the account and login again.

**Comment by ghost** [comment]
> Your Microsoft account ran into a problem.
> If you got access by Xbox Gamepass subscription, it might’ve been expired, so your Minecraft profile was revoked.
> Else, if you bought Minecraft, remove the account and login again.

No way. I have full purchase to minecraft. And now I cleared data. And now I can't even sign in. I checked my minecraft profile and there is no problem

**Comment by GaucovyAero** [comment]
> > Your Microsoft account ran into a problem.
> > If you got access by Xbox Gamepass subscription, it might’ve been expired, so your Minecraft profile was revoked.
> > Else, if you bought Minecraft, remove the account and login again.
> 
> No way. I have full purchase to minecraft. And now I cleared data. And now I can't even sign in. I checked my minecraft profile and there is no problem

maybe your child account has to be linked to a parent account on microsoft's site

**Comment by GaucovyAero** [comment]
stale

**Comment by GaucovyAero** [comment]
stale
