### ISSUE TITLE
[BUG] <Short description> take long time to lode

### ISSUE THREAD

**Issue by Naiml007** [PojavLauncherTeam/PojavLauncher#3786]
### Describe the bug

New version take 30 minutes to lode main loding screen CPU SPD 435 maybe 

### The log file and images/videos

4

### Steps To Reproduce

```markdown
2
```

### Expected Behavior

2

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

3

**Comment by khanhduytran0** [comment]
There isn’t enough info.

**Comment by GaucovyAero** [comment]
stale issue
