### ISSUE TITLE
Gamepad with wrong keys ONLY in POJAV[BUG] <Short description>

### ISSUE THREAD

**Issue by Zdr0id** [PojavLauncherTeam/PojavLauncher#3788]
### Describe the bug

Hello, I would like to talk about an annoying error that is happening to me and many other people (many indeed) I am using a translator to write all this here, because I live in Brazil, well,The bug I come to talk about here is about the keys being completely wrong on gamepads (pojavlauncher reads the gamepad as a keyboard, but it admits that it is a gamepad) this bug is annoying me A lot, apart from this bug, as human days go by, pojavlauncher starts to crash, become very slow My phone is a POCO X3 PRO (128 GB/ 6 GB RAM) 

### The log file and images/videos

There is no image, it only has video, I tried to get in touch through discord and Instagram, I was totally ignored

### Steps To Reproduce

```markdown
Turn on the Bluetooth, connect the gamepad, enter the pojavlauncher, and then enter any version of Minecraft java, and tadammmn, the bug is there, that annoying one
```

### Expected Behavior

I expected pojavlauncher to work with gamepad like in the past

### Platform

```markdown
- Device model: POCO X3 PRO
- CPU architecture: ADRENO 64 BITS
- Android version: 12
- PojavLauncher version: most recent from Playstore (I wrote this on the 19th of December 2022)
```

### Anything else?

Very annoying bug, add a Configure Controls option

**Comment by GaucovyAero** [comment]
in pojav it indeed has to act like a keyboard, so yeah, you can try rebinding the keys in controls settings in minecraft

**Comment by GaucovyAero** [comment]
stale
