### ISSUE TITLE
[BUG] server resourcepack bug

### ISSUE THREAD

**Issue by ditt0132** [PojavLauncherTeam/PojavLauncher#3790]
### Describe the bug

when join a server that requires resourcepack it dosen't stop loading

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10273964/latestlog.txt)

[2022-12-21-6.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/10273973/2022-12-21-6.log.gz)

### Steps To Reproduce

```markdown
1. run game
2. join server that requires resourcepack
3. it dosen't stop loading
```

### Expected Behavior

resourcepack will be loaded

### Platform

```markdown
- Device model: Galaxy note20 5g
- CPU architecture: 
- Android version: 13
- PojavLauncher version: dahlia-17664eae051-v3_openjdk
```

**Comment by GaucovyAero** [comment]
not all resource packs works, mostly because some of them require opengl 3.2, which pojav does not have.
