### ISSUE TITLE
[BUG] <Short description> Application exited with code 1 when i try to install optifine 1.19.2

### ISSUE THREAD

**Issue by Andros42** [PojavLauncherTeam/PojavLauncher#3791]
### Describe the bug

Sir, I have been trying for a long time to install jar file clients like Optifine and Fabric in my Pojav Launcher but it crashes when I tab to my installer.jar. in pojavlauncher my everything is working fine but i install any file by using jar it crashed

### The log file and images/videos

Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch.debug/cache/OptiFine_1.19.2_HD_U_H9.Jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: POJAV_NATIVEDIR=/data/app/~~u8dpu-kBHMgwbus3jI2qFg==/net.kdt.pojavlaunch.debug-wPM9_lTz0agYPz8-9O87uQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/bin:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~u8dpu-kBHMgwbus3jI2qFg==/net.kdt.pojavlaunch.debug-wPM9_lTz0agYPz8-9O87uQ==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (23044): dlopen libjvm.so success

I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Inter
nal/lib/aarch64/libmlib_image.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjawt.so success

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsound.so success

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7a8d67ccf8)
--------- beginning of main

I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjpe
g.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnpt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/a
arch64/libunpack.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (23044): dlopen /data/app/~~u8dpu-kBHMgwbus3jI2qFg==/net.kdt.pojavlaunch.debug-wPM9_lTz0agYPz8-9O87uQ==/lib/arm64/libopenal.so success
I/jrelog  (23044): Done processing args
I/jrelog  (23044): Found JLI lib
I/jrelog  (23044): Calling JLI_Launch

I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Inter
nal/lib/aarch64/libmlib_image.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt
.pojavlaunch.debug/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (23044): dlopen /data/u
ser/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libnpt.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (23044):
 dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (23044): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (23044): dlopen /data/app/~~u8dpu-kBHMgwbus3jI2qFg==/net.kdt.pojavlaunch.debug-wPM9_lTz0agYPz8-9O87uQ==/lib/arm64/libopenal.so success
I/jrelog  (23044): Done processing args
I/jrelog  (23044): Found JLI lib
I/jrelog  (23044): Calling JLI_Launch

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7a93030e98)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7a93030e98)

### Steps To Reproduce

```markdown
1 open pojavlauncher
2 tab installer.jar
3 select optifine
```

### Expected Behavior

Install optifine forge and fabric without any error and crash

### Platform

```markdown
- Device model: poco m4 pro 4g
- CPU architecture: 64 architecture
- Processor: mediatek helio G96 
- Android version: 13
- PojavLauncher version:[Latest debug build] dahila-188-1058750a1-v3_openjdk
```

### Anything else?

https://user-images.githubusercontent.com/116652175/208808188-90bb68ed-6ed1-4fae-9f0c-002260e406a5.mp4

**Comment by ItsManasxD** [comment]
Select Java 17 
Because 1.19 need java 17 bro

**Comment by Andros42** [comment]
> Select Java 17 Because 1.19 need java 17 bro
I tried but still it is crashing while installing optifine this is a bug, it can be fixed by update only

**Comment by Darkness826** [comment]
Have you tried to turn it into a floating window and then install optifine?
It works for me

**Comment by GaucovyAero** [comment]
rotate your screen into landscape mode
