### ISSUE TITLE
Game Not Loading With Virgl Renderer 

### ISSUE THREAD

**Issue by ItsManasxD** [PojavLauncherTeam/PojavLauncher#3792]
### Describe the bug

I want to use shaders but when I am loading game with Virgl Renderer it's just closed no error nothing

I have taken a screenshot of the logs
Pls fix this in new update 

### The log file and images/videos

![Screenshot_2022-12-21-09-59-35-555_net kdt pojavlaunch](https://user-images.githubusercontent.com/104568043/208821609-0dfc3ab3-cedb-4a98-9eb1-185096ae12e6.jpg)

### Steps To Reproduce

```markdown
1 . Starts Pojav Launcher
2 . Selected Virgl Renderer
3 . Selected Version to play
4 . Launched the game
5 . Game closed with no errors
```

### Expected Behavior

Expected Behaviour - Game starts normally with Virgl Render 

### Platform

```markdown
- Device model: Xiaomi REDMI 9 4/64GB
- CPU architecture: aarch(32 bits)
- Android version: 10
- PojavLauncher version: latest from playstore
```

**Comment by Cube5x59999** [comment]
me too

**Comment by GaucovyAero** [comment]
virgl only runs on 64-bit devices
