### ISSUE TITLE
[BUG] VirGL on adreno does not work correctly with shaders. 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#3793]
### Describe the bug

Shaders on VirGL do not display correctly and it happens that minecraft crashes. About zink in general I am silent, there is nothing running at all.  

### The log file and images/videos

Here's an example of bsl shaders on low. 
![Screenshot_20221221_205622_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/208973805-d0a998c7-150e-4d55-9b9d-15201312926a.jpg)
![Screenshot_20221221_205631_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/208973866-bfbcca20-99e7-452c-9d74-0684b177e125.jpg)

### Steps To Reproduce

```markdown
1. Launched PojavLauncher 
2. Chose a renderer VirGL 
3. I chose minecraft version 1.16.5 optifine 
4. Launched minecraft 
5. Chose bsl shaders v8.0
6. Here's the picture
7. Tried to run shaders seus ptgi e12 but crashed minecraft
```

### Expected Behavior

I expected shaders to work fine at least with low fps

### Platform

```markdown
- Device model: huawei nova 9 se 
- CPU architecture: aarch64 snapdragon 680 (adreno 610)
- Android version: emui 12 
- PojavLauncher version: latest release from actions
```

**Comment by GaucovyAero** [comment]
this is to be expected, virgl only works fine on mali gpus, but on mali, you cant run shaders afaik, so theres that

**Comment by GaucovyAero** [comment]
not fixable
