### ISSUE TITLE
[BUG] resourcepack core-shaders

### ISSUE THREAD

**Issue by PortableGames** [PojavLauncherTeam/PojavLauncher#3795]
### Describe the bug

Core-shaders from this resourcepack cause the resourcepack to get stuck in a loop and load over and over again.

[emotes-resourcepack.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/10292336/emotes-resourcepack.zip)

### The log file and images/videos

[-5456494078216342473.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10292367/-5456494078216342473.txt)

### Steps To Reproduce

```markdown
Activate RP in version 1.19.3
```

### Expected Behavior

.

### Platform

```markdown
- Device model: moto g22
- CPU architecture: Octa-core (4x2.3 GHz Cortex-A53 & 4x1.8 GHz Cortex-A53)
- Android version: 12
- PojavLauncher version: Latest
```

**Comment by GaucovyAero** [comment]
this resource pack requires opengl 3.2 core profile, which gl4es does not have
