### ISSUE TITLE
[BUG] xray glitch in 1.13/14

### ISSUE THREAD

**Issue by v1rtual8525** [PojavLauncherTeam/PojavLauncher#3796]
### Describe the bug

i launch into the game and in 1.13 there is a weird xray glitch it seems to only happen in holy gl4es but any other renderer works fine just more glitchier, it worked before hand when i had to delete pojav for storage issues and now it doesent work

### The log file and images/videos

``

### Steps To Reproduce

```markdown
1. select 1.13 on pojav
2. select holy gl4es on 1.13
3. launch 1.13
4.load into world
5. expect the bug
```

### Expected Behavior

i expect 1.13 to launch normaly

### Platform

```markdown
- Device model: 
- CPU architecture: aarch64
- Android version: samsung a72
- PojavLauncher version: newest version
```

### Anything else?

it worked with holy gl4es before i deleted pojav and now it seems to not work

**Comment by khanhduytran0** [comment]
Toggling Fullscreen state (F11) should do the trick

**Comment by v1rtual8525** [comment]
k thx

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GaucovyAero** [comment]
issue fixed
