### ISSUE TITLE
Issues from Minecraft java1.16 

### ISSUE THREAD

**Issue by abdo-A028** [PojavLauncherTeam/PojavLauncher#38]
Unable to convert library org.lwjgl:lwjgl:3.2.1
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
processing archive /storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/INDEX.LIST...
writing META-INF/INDEX.LIST; size 554...
processing META-INF/MANIFEST.MF...
processing META-INF/versions/...
writing META-INF/versions/; size 0...
processing META-INF/versions/10/...
writing META-INF/versions/10/; size 0...
processing META-INF/versions/10/org/...
writing META-INF/versions/10/org/; size 0...
processing META-INF/versions/10/org/lwjgl/...
writing META-INF/versions/10/org/lwjgl/; size 0...
processing META-INF/versions/10/org/lwjgl/system/...
writing META-INF/versions/10/org/lwjgl/system/; size 0...
processing META-INF/versions/10/org/lwjgl/system/MathUtil.class...

PARSE ERROR:
unsupported class file version 54.0
...while parsing META-INF/versions/10/org/lwjgl/system/MathUtil.class
1 error; aborting
Exiting with code 1

**Comment by khanhduytran0** [comment]
You can't run Minecraft 1.12 or above.

**Comment by abdo-A028** [comment]
I know it can't work

**Comment by abdo-A028** [comment]
I m talking about some issues

**Comment by abdo-A028** [comment]
It says Minecraft java 1.12 May download it, but can't run

**Comment by abdo-A028** [comment]
But from 1.13 to latest update, you can't download

**Comment by khanhduytran0** [comment]
1.12 requires launcher with only Java8 which supported since Android 8. If I do it, any user will put ton of issues about can't install in Android 5 to 7.1

**Comment by khanhduytran0** [comment]
https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers
> Java SE 10 = 54 (0x36 hex)

**Comment by khanhduytran0** [comment]
A Java version which not supported by Android.
