### ISSUE TITLE
Please where is ARM64

### ISSUE THREAD

**Issue by DexyHatesYou** [PojavLauncherTeam/PojavLauncher#380]
Idk where is arm64

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model s9
 - CPU architecture 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Didn't you read instruction?

**Comment by mglovers123** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/releases/download/v3.2.0-testing6/jre9-arm64-20200929.tar.xz Link

**Comment by mglovers123** [comment]
> Idk where is arm64
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Start PojavLauncher
>    ...
> 
> **Expected behavior**
> I expected ...
> 
> **Screenshots**
> 
> **Platform:**
> 
> * Device Model s9
> * CPU architecture
> * Android Version [e.g. 10]
> 
> Additional context
