### ISSUE TITLE
I cannot login

### ISSUE THREAD

**Issue by sswarior26** [PojavLauncherTeam/PojavLauncher#3800]
### Describe the bug

I can't login. Whenever i do it says account not found

### The log file and images/videos

Idk

### Steps To Reproduce

```markdown
1. Start the launcher
2. Try to login
```

### Expected Behavior

I expect the game to launch

### Platform

```markdown
- Device model: realme c2
- CPU architecture: idk
- Android version: 9
- PojavLauncher version: latest
```

**Comment by sswarior26** [comment]
Bruh new login bug, Dev's please fix it

**Comment by sswarior26** [comment]
It's fixed now

**Comment by sswarior26** [comment]
Thanks!

**Comment by GaucovyAero** [comment]
resolved
