### ISSUE TITLE
[BUG] Replay Mod forge 1.16.5 fails to save video

### ISSUE THREAD

**Issue by Bancure99** [PojavLauncherTeam/PojavLauncher#3802]
### Describe the bug

When i try to save and quit,the video fails to save,i hope someone solve this issue.

### The log file and images/videos

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/26/22, 3:10 AM
Description: Saving replay file

java.nio.file.FileSystemException: /storage/emulated/0/games/PojavLauncher/.minecraft/./replay_recordings/recording/2022_12_26_03_08_41.mcpr: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?] {}
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?] {}
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?] {}
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:286) ~[?:?] {}
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:492) ~[?:?] {}
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267) ~[?:?] {}
	at java.nio.file.Files.move(Files.java:1432) ~[?:?] {}
	at com.replaymod.replaystudio.replay.ZipReplayFile.save(ZipReplayFile.java:323) ~[replaymod:?] {re:classloading}
	at com.replaymod.recording.packet.PacketListener.saveReplayFile(PacketListener.java:300) ~[replaymod:?] {re:classloading}
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$2(PacketListener.java:108) ~[replaymod:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version Android-7.1.1
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 717760784 bytes (684 MB) / 1415577600 bytes (1350 MB) up to 1415577600 bytes (1350 MB)
	CPUs: 7
	JVM Flags: 26 total; -XX:-UseGCOverheadLimit -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:+UseBiasedLocking -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:+UseCodeCacheFlushing -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:ReservedCodeCacheSize=2048m -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10 -Xmn128m -Xms1350M -Xmx1350M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-3.99m.jar                     |Performant                    |performant                    |3.73m               |DONE      |Manifest: NOSIGNATURE
		lithium-forge-mc1.16.5-0.6.6+rev.1.jar            |Lithium (Forge)               |lithium                       |0.6.6+rev.1         |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-mc1.16.5-1.5.2.jar            |EntityCulling                 |entityculling                 |1.5.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ALPHA.phosphor-forge-mc1.16.5-0.7.1-build_1.jar   |Phosphor (Forge)              |phosphor                      |0.7.1-build_1       |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.0-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.0               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		replaymod-1.16.4-forge-1.0.1.jar                  |Replay Mod                    |replaymod                     |2.5.1               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 16794a48-8fac-4ff6-9887-752c92c633e1
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

### Steps To Reproduce

```markdown
1.Enter the world to start recording.
2.Save and quit the world.
3.Then,the video failed to save,showing the log file above.
```

### Expected Behavior

I expected it to save my video with replay mod installed.

### Platform

```markdown
- Device model: Oppo A71
- CPU architecture: AArch64 Processor rev 2(aarch64)
- Android version: 7.1.1
- PojavLauncher version: dahlia-159-b581c7ba8-v3_openjdk
```

**Comment by mchnjt** [comment]
Oh we use a similar phone... I guess Replay Mod can only save videos if the android version is 8+ (i tried it too, as soon as i exit the world attempting to save the replay, it said "Operation not permitted"). It works fine on my Android 9 and 11.
Even if you have set it right, stuff wouldn't work properly. Try using a custom rom that is based  around AOSP 9 or up.

**Comment by Bancure99** [comment]
Thanks for your response.

**Comment by GaucovyAero** [comment]
fixed
