### ISSUE TITLE
[BUG] <Game Crashes after some time when running compact claustrophobia>

### ISSUE THREAD

**Issue by TheDaveCZ** [PojavLauncherTeam/PojavLauncher#3803]
### Describe the bug

Game Crashes after some time with the code 1. 
version is forge 1.12.2 
modpack is compact claustrophobia latest release

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10306389/latestlog.txt)
[crash-2022-12-27_06.20.35-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10306393/crash-2022-12-27_06.20.35-client.txt)

### Steps To Reproduce

```markdown
1. launch game
2. game loads and is running fine (for about 5 seconds)
3. game crashes with the report code 1
```

### Expected Behavior

1. game launches 
2. load a world 
3. play

### Platform

```markdown
- Device model: Realme X3 SuperZoom 256/12
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Google play: dahlia-176-641eae051-v3_openjdk
```

### Anything else?

i removed **foamfix** because:

  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2 (1).jar)

original crash report:

[crash-2022-12-27_06.51.17-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10306485/crash-2022-12-27_06.51.17-client.txt)

**Comment by GaucovyAero** [comment]
Poslal si doslova ze prazdne subory, ale odporucam znizit RAM allocation (ak nehras giganticky modpack ako je RLCraft) na 500-700MB. V pripade, ze by si mal dalsie problemy, normalne joini oficialny pojavlauncher discord a spytaj sa ma tam :D

![image](https://user-images.githubusercontent.com/85581164/209646537-a0150d09-f89f-47b3-a1d1-9e79e807e26b.png)

**Comment by GaucovyAero** [comment]
fixed
