### ISSUE TITLE
Error[BUG] <Short description>

### ISSUE THREAD

**Issue by joaojtm** [PojavLauncherTeam/PojavLauncher#3804]
### Describe the bug

the game no longer installs .jar files, like optifine, it does not run the installation and closes with "code 1" #

### The log file and images/videos

![Screenshot_20221227-181045](https://user-images.githubusercontent.com/121520741/209722719-5b2b44d9-de3d-4a1a-984d-bd1904e8d087.png)

### Steps To Reproduce

```markdown
1.Open the pojavlauncher 
2.Click on install .jar
3.Select the .jar file
4.The app crash
```

### Expected Behavior

i hope i can install optfine again 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by MegaFaresX** [comment]
Check for the default java version set it to java 1.8.0
![Screenshot_2022-12-29-14-51-48-81_67a64f1fc1b88908dad3392f76c1969b.jpg](https://user-images.githubusercontent.com/83421889/209953768-b421f7f7-42b6-4efc-8a7a-6e3531515316.jpg)

**Comment by joaojtm** [comment]
> Check for the default java version set it to java 1.8.0 ![Screenshot_2022-12-29-14-51-48-81_67a64f1fc1b88908dad3392f76c1969b.jpg](https://user-images.githubusercontent.com/83421889/209953768-b421f7f7-42b6-4efc-8a7a-6e3531515316.jpg)

it's already like this

**Comment by joaojtm** [comment]
> send latestlog.txt

Where can I find?

**Comment by MegaFaresX** [comment]
> > send latestlog.txt
> 
> Where can I find?
Using this button
![Screenshot_2022-12-29-16-49-26-56_67a64f1fc1b88908dad3392f76c1969b.jpg](https://user-images.githubusercontent.com/83421889/209969940-b17d7a60-391a-4e1e-bb5d-96441e7ce464.jpg)

**Comment by joaojtm** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10320126/latestlog.txt)

**Comment by joaojtm** [comment]
> send latestlog.txt

[Uploading latestlog.txt…]()

**Comment by GaucovyAero** [comment]
you didnt send the log

**Comment by joaojtm** [comment]
>
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10326760/latestlog.txt)

**Comment by joaojtm** [comment]
> > 
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10326760/latestlog.txt)

@GaucovyAero

**Comment by GaucovyAero** [comment]
stale
