### ISSUE TITLE
black screen when opening forge 1.5.2 in pojavlauncher

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#3805]
### Is this request related to a bug?

black screen when opening forge 1.5.2

### Describe the request.

black screen when opening forge 1.5.2

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/file/x46gqv0pf2rtw02/PojavLauncher_Forge_1.3.2-1.7.2_Patchpack_v1.1.zip/file
use the JSON from here and download fmllibs152.zip from MCArchive first.

**Comment by Prostop194** [comment]
i did everything you said but i still have a black screen

**Comment by GaucovyAero** [comment]
and have you installed the fmllibs into .minecraft/lib?

**Comment by GaucovyAero** [comment]
also, be sure to send latestlog.txt

**Comment by Prostop194** [comment]
sorry but i don't know how to send latestlog.txt

**Comment by Prostop194** [comment]
> также обязательно отправьте lastlog.txt

but i can send what was inside latestlog.txt

**Comment by Prostop194** [comment]
--------- beggining with launcher debug
Info: Launcher version: v3.3.1.1-1833-9680ba11b-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.5.2-Forge7.8.1.738
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2312
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~JB_QY1Z0Xm1ILkAK4rG1Og==/net.kdt.pojavlaunch-cMedN3SikxAgMNAY9TvhYQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
--------- beginning of main
I/LIBGL   ( 4622): GLSL 300 es supported
I/LIBGL   ( 4622): GLSL 310 es supported and used
I/LIBGL   ( 4622): sRGB surface supported
I/LIBGL   ( 4622): EGLImage to Texture2D supported
I/LIBGL   ( 4622): EGLImage to RenderBuffer supported
I/LIBGL   ( 4622): ignore MipMap
I/LIBGL   ( 4622): Targeting OpenGL 2.1
I/LIBGL   ( 4622): NPOT texture handled in hardware
I/LIBGL   ( 4622): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 4622): try to use VBO
I/LIBGL   ( 4622): glX Will try to recycle EGL Surface
I/LIBGL   ( 4622): Current folder is:/
I/jrelog  ( 4622): dlopen libgl4es_114.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  ( 4622): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  ( 4622): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  ( 4622): dlopen /data/app/~~JB_QY1Z0Xm1ILkAK4rG1Og==/net.kdt.pojavlaunch-cMedN3SikxAgMNAY9TvhYQ==/lib/arm64/libopenal.so success
I/jrelog  ( 4622): Done processing args
I/jrelog  ( 4622): Found JLI lib
I/jrelog  ( 4622): Calling JLI_Launch
РґРµРє 29, 2022 1:01:49 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using tweak class name net.minecraftforge.legacy._1_5_2.LibraryFixerTweaker
РґРµРє 29, 2022 1:01:49 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Launching wrapped minecraft
2022-12-29 13:01:50 [INFO] [ForgeModLoader] Forge Mod Loader version 5.2.23.738 for Minecraft 1.5.2 loading
2022-12-29 13:01:50 [INFO] [ForgeModLoader] Java is OpenJDK 64-Bit Server VM, version 1.8.0-internal, running on Linux:aarch64:Android-12, installed at /data/data/net.kdt.pojavlaunch/runtimes/Internal
2022-12-29 13:01:50 [INFO] [ForgeModLoader] Found a command line coremod : net.minecraftforge.legacy._1_5_2.LibraryFixerCoremod
2022-12-29 13:01:50 [INFO] [ForgeModLoader] [LegacyFixer] Removing CoreFMLLibraries: cpw.mods.fml.relauncher.CoreFMLLibraries@1060b431
2022-12-29 13:01:50 [INFO] [ForgeModLoader] Downloading file http://files.minecraftforge.net/fmllibs/deobfuscation_data_1.5.2.zip
2022-12-29 13:01:50 [SEVERE] [ForgeModLoader] There were errors during initial FML setup. Some files failed to download or were otherwise corrupted. You will need to manually obtain the following files from these download links and ensure your lib directory is clean. 
2022-12-29 13:01:50 [SEVERE] [ForgeModLoader] *** Download http://files.minecraftforge.net/fmllibs/deobfuscation_data_1.5.2.zip
2022-12-29 13:01:50 [SEVERE] [ForgeModLoader] <===========>
2022-12-29 13:01:50 [SEVERE] [ForgeModLoader] The following is the errors that caused the setup to fail. They may help you diagnose and resolve the issue
2022-12-29 13:01:50 [SEVERE] [ForgeModLoader] The downloaded file deobfuscation_data_1.5.2.zip has an invalid checksum e04c5335922c5e457f0a7cd62c93c4a7f699f829 (expecting 446e55cd986582c70fcf12cb27bc00114c5adfd9). The download did not succeed correctly and the file has been deleted. Please try launching again.
2022-12-29 13:01:50 [SEVERE] [ForgeModLoader] <<< ==== >>>
2022-12-29 13:01:50 [SEVERE] [ForgeModLoader] The following is diagnostic information for developers to review.
2022-12-29 13:01:50 [SEVERE] [ForgeModLoader] Error details
java.lang.RuntimeException: The downloaded file deobfuscation_data_1.5.2.zip has an invalid checksum e04c5335922c5e457f0a7cd62c93c4a7f699f829 (expecting 446e55cd986582c70fcf12cb27bc00114c5adfd9). The download did not succeed correctly and the file has been deleted. Please try launching again.
	at cpw.mods.fml.relauncher.RelaunchLibraryManager.performDownload(RelaunchLibraryManager.java:613)
	at cpw.mods.fml.relauncher.RelaunchLibraryManager.downloadFile(RelaunchLibraryManager.java:532)
	at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:165)
	at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:172)
	at cpw.mods.fml.relauncher.FMLRelauncher.relaunchClient(FMLRelauncher.java:104)
	at cpw.mods.fml.relauncher.FMLRelauncher.handleClientRelaunch(FMLRelauncher.java:38)
	at net.minecraft.client.Minecraft.main(Minecraft.java:2237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

**Comment by Prostop194** [comment]
> а вы установили fmllibs в .minecraft/lib?

yes, sure

**Comment by GaucovyAero** [comment]
log says you did not

**Comment by Prostop194** [comment]
![Screenshot_20221229-214113_ZArchiver Pro](https://user-images.githubusercontent.com/121510853/209976259-5ce3de30-092a-461a-8c9d-a7d9418c1909.jpg)
here is what i did

**Comment by Prostop194** [comment]
sorry please send the file fmllibs152.zip

**Comment by GaucovyAero** [comment]
> sorry please send the file fmllibs152.zip

download from mcarchive

**Comment by Prostop194** [comment]
> > извините пожалуйста пришлите файл fmllibs152.zip
> 
> скачать с макархива

I searched in MCarchive but I did not find it. You can edit the file fmllibs152.zip

**Comment by GaucovyAero** [comment]
ur stupid 
![Screenshot_20221229-171158_Bromite](https://user-images.githubusercontent.com/85581164/209979847-85ab97e0-1312-492c-8cdb-cecb531d1901.png)

**Comment by Prostop194** [comment]
> ты глупый ![Скриншот_20221229-171158_Бромит](https://user-images.githubusercontent.com/85581164/209979847-85ab97e0-1312-492c-8cdb-cecb531d1901.png)

please send this file fmllibs152.zip

**Comment by MegaFaresX** [comment]
Bro IT'S THE FIRST LINK
![Screenshot_2022-12-29-18-20-18-52_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/83421889/209980808-c38c8abf-4c91-445e-9499-f9ab03978861.jpg)

**Comment by Prostop194** [comment]
![Screenshot_20221229-222339_WhatsApp](https://user-images.githubusercontent.com/121510853/209981221-416b880d-f7e6-4cca-afce-6755cb64653a.jpg)
WHAT TO ENTER HERE. I entered fmllibs152.zip and there are no results

**Comment by MegaFaresX** [comment]
Search forge

**Comment by MegaFaresX** [comment]
Search forge

**Comment by MegaFaresX** [comment]
Search forge

**Comment by Prostop194** [comment]
i found fmllibs152.zip i unpacked it into lib folder and i still have endless black screen

**Comment by GaucovyAero** [comment]
> i found fmllibs152.zip i unpacked it into lib folder and i still have endless black screen

send latestlog.txt

**Comment by Prostop194** [comment]
> > я нашел fmllibs152.zip я распаковал его в папку lib и у меня все еще есть бесконечный черный экран
> 
> отправить последний журнал.txt

--------- beggining with launcher debug
Info: Launcher version: v3.3.1.1-1833-9680ba11b-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.5.2-Forge7.8.1.738
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2312
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~JB_QY1Z0Xm1ILkAK4rG1Og==/net.kdt.pojavlaunch-cMedN3SikxAgMNAY9TvhYQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/LIBGL   (31754): Initialising gl4es
I/LIBGL   (31754): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   (31754): Using GLES 2.0 backend
I/LIBGL   (31754): loaded: libGLESv2.so
I/LIBGL   (31754): loaded: libEGL.so
I/LIBGL   (31754): Using GLES 2.0 backend
I/LIBGL   (31754): Hardware Full NPOT detected and used
I/LIBGL   (31754): FBO are in core, and so used
I/LIBGL   (31754): PointSprite are in core, and so used
I/LIBGL   (31754): CubeMap are in core, and so used
I/LIBGL   (31754): BlendColor is in core, and so used
I/LIBGL   (31754): Blend Substract is in core, and so used
I/LIBGL   (31754): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (31754): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (31754): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (31754): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (31754): Extension GL_OES_depth24  detected and used
I/LIBGL   (31754): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (31754): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (31754): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (31754): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (31754): Extension GL_OES_texture_float  detected and used
I/LIBGL   (31754): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (31754): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (31754): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (31754): high precision float in fragment shader available and used
I/LIBGL   (31754): Max vertex attrib: 32
I/LIBGL   (31754): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (31754): Max texture size: 16384
I/LIBGL   (31754): Max Varying Vector: 31
I/LIBGL   (31754): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (31754): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (31754): Max Anisotropic filtering: 16
I/LIBGL   (31754): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   (31754): Hardware vendor is Qualcomm
I/LIBGL   (31754): GLSL 300 es supported
I/LIBGL   (31754): GLSL 310 es supported and used
I/LIBGL   (31754): sRGB surface supported
I/LIBGL   (31754): EGLImage to Texture2D supported
I/LIBGL   (31754): EGLImage to RenderBuffer supported
I/LIBGL   (31754): ignore MipMap
I/LIBGL   (31754): Targeting OpenGL 2.1
I/LIBGL   (31754): NPOT texture handled in hardware
I/LIBGL   (31754): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (31754): try to use VBO
I/LIBGL   (31754): glX Will try to recycle EGL Surface
I/LIBGL   (31754): Current folder is:/
I/jrelog  (31754): dlopen libgl4es_114.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (31754): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (31754): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (31754): dlopen /data/app/~~JB_QY1Z0Xm1ILkAK4rG1Og==/net.kdt.pojavlaunch-cMedN3SikxAgMNAY9TvhYQ==/lib/arm64/libopenal.so success
I/jrelog  (31754): Done processing args
I/jrelog  (31754): Found JLI lib
I/jrelog  (31754): Calling JLI_Launch
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

РґРµРє 29, 2022 4:40:59 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using tweak class name net.minecraftforge.legacy._1_5_2.LibraryFixerTweaker
РґРµРє 29, 2022 4:40:59 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Launching wrapped minecraft
2022-12-29 16:41:00 [INFO] [ForgeModLoader] Forge Mod Loader version 5.2.23.738 for Minecraft 1.5.2 loading
2022-12-29 16:41:00 [INFO] [ForgeModLoader] Java is OpenJDK 64-Bit Server VM, version 1.8.0-internal, running on Linux:aarch64:Android-12, installed at /data/data/net.kdt.pojavlaunch/runtimes/Internal
2022-12-29 16:41:01 [INFO] [ForgeModLoader] Found a command line coremod : net.minecraftforge.legacy._1_5_2.LibraryFixerCoremod
2022-12-29 16:41:01 [INFO] [ForgeModLoader] [LegacyFixer] Removing CoreFMLLibraries: cpw.mods.fml.relauncher.CoreFMLLibraries@612679d6
2022-12-29 16:41:02 [INFO] [ForgeModLoader] Found valid fingerprint for Minecraft Forge. Certificate fingerprint de4cf8a3f3bc15635810044c39240bf96804ea7d
Java Exit code: 0
I/jrelog  (31754): Going to free args
I/jrelog  (31754): Free done

**Comment by GaucovyAero** [comment]
looks like you didn't insert the patched JSON from the start

**Comment by Prostop194** [comment]
![Screenshot_20221230-003920_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/121510853/209995305-fbb405ea-0264-4be6-bcde-c64fbaf8bae7.jpg)
oh god thank you

**Comment by Prostop194** [comment]
thank you very much

**Comment by Prostop194** [comment]
now I can close this question :)

**Comment by GaucovyAero** [comment]
issue fixed
