### ISSUE TITLE
i cant go on servers

### ISSUE THREAD

**Issue by vevendu89** [PojavLauncherTeam/PojavLauncher#3806]
### Describe the bug

hello, when i try to connect to a server, i get the message: timed out. Also, when I register a server (I am in 1.8.9), impossible to see the ping and to connect to it. I do not understand why ,
Thank you for your help
Even

### The log file and images/videos

[
[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10314531/latestlog.old.txt)
](url)

### Steps To Reproduce

```markdown
1.Launch pojavlauncher
2.go on multiplayer
3.register a server
that's all
```

### Expected Behavior

I expect to be able to connect to a server as seen on the home page of the app

### Platform

```markdown
- Device model: Iphone 7
- CPU architecture: 
- IOS version: 15.0
- PojavLauncher version: The last on AltServer
```

**Comment by GaucovyAero** [comment]
this is the android repository, please issue this in the PojavLauncherTeam/PojavLauncher_iOS repo.
