### ISSUE TITLE
I am unable to open up any of the alpha beta or classic and indev era versions and whenever I open up RD no matter where I aim the Crosshair I cannot Place nor break as the white around a block where I would be placing another or be breaking that block does not appear and every time I try to do those things it won't work so please just fix those issues

### ISSUE THREAD

**Issue by mfjfkfjf** [PojavLauncherTeam/PojavLauncher#381]
**Describe the bug**
So basically I'm unable to play any of the old versions of Minecraft all the way up until release 1.5 and the pre-classic era I'm unable to break or place any blocks
**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ... I expected to be able to play these versions and for the pre-classic era versions the way they should be

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - android
![Screenshot_20201103-181632_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/73915765/98051485-035b1200-1e02-11eb-917e-b09b85e5c5d8.jpg)
![Screenshot_20201103-181604_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/73915765/98051503-09e98980-1e02-11eb-8c86-02f963a2aa04.jpg)

**Comment by khanhduytran0** [comment]
You haven't provided any more information.

**Comment by mfjfkfjf** [comment]
@khanhduytran0 this is my first time here I only create an account just so I could explain this I don't know how to add screenshots I don't have any money that so the least you could do it's just go off of the information you have until I figure out how to add a screenshot

**Comment by khanhduytran0** [comment]
You could by use github web version then add attachment

**Comment by mfjfkfjf** [comment]
Nevermind I added to comment go to the top of this and you should see more information then can you try and fix that will that be enough information for you

**Comment by khanhduytran0** [comment]
So are you on v2 or v3?

**Comment by mglovers123** [comment]
> So are you on v2 or v3?
