### ISSUE TITLE
[F-Req] <not able to add mods android 13 >

### ISSUE THREAD

**Issue by kurox313** [PojavLauncherTeam/PojavLauncher#3810]
### Is this request related to a bug?

so I'm going back to school and I wanted to make it worth the cost of buying java edition so I installed fabric and I was about to add mods but I don't see the .minecraft hidden file so I searched in the file manager+ and nothing showed up so if it's possible can you guys tell me where is the .minecraft located I don't have an SD card inserted so yeah

### Describe the request.

I don't know where is .minecraft located

### Anything else?

nope

**Comment by Andros42** [comment]
Use ZAchiver

**Comment by kurox313** [comment]
nope does not show up

**Comment by nawinlol3211** [comment]
![Uploading Screenshot_20230101_155014_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

**Comment by kurox313** [comment]
it gave me more details but no sighting of .minecraft and I tried moving .minecraft from my pc/laptop but nothing

**Comment by kurox313** [comment]
custom directory shows where it's located and it's at uhhh ./.minecraft/versions/ fabric-loader-0.14.12-1.18.2

**Comment by Andros42** [comment]
on which device are you looking for the minecraft folder
 
Pc or mobile?

**Comment by kurox313** [comment]
both

**Comment by RoomAlex68** [comment]
> 
Yeah same here I used FV File Explorer to access the android 13 files and it did and put the mods under mods in the ./.minecraft/mods in pojavlauncher folder in the android folder.But when I loaded up the game with Forge 1.19.2 installed. The mods weren't showing up

**Comment by RoomAlex68** [comment]
The. Minecraft folder is in the net.kdt.pojavlauncher.debug but hidden

**Comment by kurox313** [comment]
ok ill try that

**Comment by kurox313** [comment]
> > 
> 
> Yeah same here I used FV File Explorer to access the android 13 files and it did and put the mods under mods in the ./.minecraft/mods in pojavlauncher folder in the android folder.But when I loaded up the game with Forge 1.19.2 installed. The mods weren't showing up

i am not able to find the ./.minecraft/mods it does not exsist

**Comment by RoomAlex68** [comment]
Do you not have forge installed? It should exist in the .Minecraft folder

**Comment by RoomAlex68** [comment]
It's in net.kdt.pojavlauncher.debug/files/.minecraft/mods

**Comment by RoomAlex68** [comment]
![Screenshot_20230105_111042_FV File Explorer](https://user-images.githubusercontent.com/85209177/210861317-3e8c6a60-3d6b-4c9f-a388-dc987489f3f1.jpg)

**Comment by kurox313** [comment]
i have fabric installed to gain more fps

**Comment by kurox313** [comment]
I'll try to install forge

**Comment by Darklight-007** [comment]
same here when using the explorer i can access the net.kdt.pojavlauncher.debug folder but i cant seem to find the minecraft folder i can see the other four folders but cant see the minecraft folder and when forcefully accessing it, it says the file is corrupted please help

I have a Vivo V15 pro running Android 11

**Comment by kurox313** [comment]
uhh

**Comment by kurox313** [comment]
it didn't work

**Comment by RoomAlex68** [comment]
![Screenshot_20230110_110424_FV File Explorer](https://user-images.githubusercontent.com/85209177/211639168-1acabd4b-37fb-4e32-bbf6-4c9a1a7c4cb7.jpg)

Do you not have show hidden files enabled?

**Comment by RoomAlex68** [comment]
Ik the mods won't load because of android 13 even If forge is installed

**Comment by GaucovyAero** [comment]
> 

use MiXplorer to insert the mods and make sure you download the mods with Firefox and NOT Chrome. This is not a pojav issue.

**Comment by RoomAlex68** [comment]
Oh Ok

**Comment by RoomAlex68** [comment]
Ok I used Firefox to download the mods  and used MiXplorer to put them in them in the mods  folder and it didn't show up when I played minecraft 1.19.2 forge

**Comment by GaucovyAero** [comment]
> Ok I used Firefox to download the mods and used MiXplorer to put them in them in the mods folder and it didn't show up when I played minecraft 1.19.2 forge

did you change the minecraft directory?

**Comment by kurox313** [comment]
i tried everything and nothing worked its in a special folder in my device that i cant access

**Comment by RoomAlex68** [comment]
> > Ok I used Firefox to download the mods and used MiXplorer to put them in them in the mods folder and it didn't show up when I played minecraft 1.19.2 forge
> 
> did you change the minecraft directory?

No? And idk how to change the minecraft directory

**Comment by om3ga6400** [comment]
@nawinlol3211 just install forge go to settings click on "Resource Packs" Press "Go to Resources folder" go back to .minecraft and click mods, then just ad your mods there

**Comment by GaucovyAero** [comment]
use mixplorer, free download from mixplorer.com
