### ISSUE TITLE
[BUG] minecraft loading screen is messed up

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#3811]
### Describe the bug

the loading screen i messed up the mouse doesn't show in one half of the screen the bar is half shown and some letters appear on the screen 

### The log file and images/videos

![Screenshot_20230101_143119_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/101394924/210169474-bc830a63-5d76-40e6-9a8f-a96e423e8272.jpg)
![Screenshot_20230101_143626_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/101394924/210169478-2cea9a3f-5186-41d6-8ca1-3cbaa069e6a6.jpg)

### Steps To Reproduce

```markdown
1 start pojavlauncher
2 play on forge 1.16.5
3 the bug happens
```

### Expected Behavior

it looks normal 

### Platform

```markdown
- Device model: huawei y6s
- CPU architecture: MTK MT6765
- Android version: 9
- PojavLauncher version: version dhaila-107-b6f15cb42-v3_o...
```

### Anything else?

how can i fix it

**Comment by GaucovyAero** [comment]
disable alternate surface rendering

**Comment by hiimabignoobwihenolive** [comment]
Thanks it worked but i didn't turn on alternate surface rendering it just turned on when i installed forge it happens every time when i install a loader

**Comment by kaicryptx** [comment]
Click on gui button

**Comment by GaucovyAero** [comment]
Issue fixed in the latest pojav actions build.
