### ISSUE TITLE
Can't play any version below 1.16.5

### ISSUE THREAD

**Issue by Mousebu** [PojavLauncherTeam/PojavLauncher#3812]
### Describe the bug

application/game exited with code 1
I can't play versions below 1.16.5 and 1.16.5 it crashes instantly when i click play

### The log file and images/videos

https://user-images.githubusercontent.com/106907343/210174396-d05854c9-88bd-4c8e-951f-784cd561a1c0.mp4

### Steps To Reproduce

```markdown
1. Start Pojav launcher 
2. Choose any version below 1.16.5
3. Crash
```

### Expected Behavior

I expect the game not to crash and i can play any version 

### Platform

```markdown
- Device model: vivo 1820
- CPU architecture: 64aarch
- Android version: 8.1.0
- PojavLauncher version: latest available in playstore
```

### Anything else?

Please tell me solution,here's the latest log
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10328947/latestlog.txt)

**Comment by GaucovyAero** [comment]
try b1.7.3 and send latestlog.txt

**Comment by Mousebu** [comment]
Here, 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10330572/latestlog.txt)

**Comment by Mousebu** [comment]
> try b1.7.3 and send latestlog.txt

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10332393/latestlog.txt)

**Comment by Bel69420** [comment]
Its seem like that your java runtime is corrupted or broken, you have to delete Java 8 then launch the game again.

**Comment by GaucovyAero** [comment]
> Its seem like that your java runtime is corrupted or broken, you have to delete Java 8 then launch the game again.

yep

**Comment by Mousebu** [comment]
> Its seem like that your java runtime is corrupted or broken, you have to delete Java 8 then launch the game again.
It worked thnx

**Comment by Mousebu** [comment]
Thnx
