### ISSUE TITLE
[BUG] crashes when given more than 1000mb of ram

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#3813]
### Describe the bug

it will crash with code 1 if you  locate more 
than 1000mb

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10329025/latest.log)

### Steps To Reproduce

```markdown
1 start pojavlauncher
2 go to settings
3 give pojavlauncher more than 1000mb
4 crash
```

### Expected Behavior

I expected the game to launch 

### Platform

```markdown
- Device model: huawei y6s 
- CPU architecture: MTK MT6765 
- Android version: 9 
- PojavLauncher version: version dhaila-107-b6f15cb42-v3_o...
```

### Anything else?

I cant play mods without more ram

**Comment by TarikBR** [comment]
send the logs, but I think the problem is because you have less free RAM than you set, causing the crash

**Comment by khanhduytran0** [comment]
It appears that you have 32bit phone, with limited amount of RAM, so this can’t be fixed, unfortunately.

**Comment by Fl414r** [comment]
After little googling I can say MTK MT6765 aarch64 and Huawei Y6s have 3GB ram.
And in .log file game located in storage/games/Pojavlauncher.
Maybe try new version? If you not have Google Play you can get it here https://github.com/PojavLauncherTeam/PojavLauncher/actions
or
download aarch-64 (!!) Java https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/3452007313 and try set it in launcher

**Comment by GaucovyAero** [comment]
> After little googling I can say MTK MT6765 aarch64 and Huawei Y6s have 3GB ram. And in .log file game located in storage/games/Pojavlauncher. Maybe try new version? If you not have Google Play you can get it here https://github.com/PojavLauncherTeam/PojavLauncher/actions or download aarch-64 (!!) Java https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/3452007313 and try set it in launcher

well, you can't just think that you can allocate whatever you want out of those 3GB RAM you have. The system always takes about 1GB-2.5GB of RAM on average
