### ISSUE TITLE
I have a black screen and after second the game crashed 

### ISSUE THREAD

**Issue by PsanesX** [PojavLauncherTeam/PojavLauncher#3815]
### Describe the bug

I have a black screen and after second the game crached

### The log file and images/videos

O

### Steps To Reproduce

```markdown
O
```

### Expected Behavior

O

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by PsanesX** [comment]
What is latestlog.txt

**Comment by GaucovyAero** [comment]
> What is latestlog.txt

the main pojav log

**Comment by another-github-username** [comment]
I have encountered this issue, I get a black screen when selecting the latest release of Minecraft, if you specify a specific version it loads up

**Comment by PsanesX** [comment]
My version is 1.12.2 forge

**Comment by khanhduytran0** [comment]
@PsanesX please do not put random characters to the issue form, fill in it
