### ISSUE TITLE
My game stile like that and sometimes the game crash or he code 1

### ISSUE THREAD

**Issue by PsanesX** [PojavLauncherTeam/PojavLauncher#3816]
### Describe the bug

Application exited with code 1
![502587CE-1412-49BF-9944-9754793FDDA5](https://user-images.githubusercontent.com/120598400/210329683-38ff564b-b20e-477f-8f25-c0474013c66e.png)

### The log file and images/videos

Pl

### Steps To Reproduce

```markdown
P
```

### Expected Behavior

P

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

![DA0A9102-66CC-4D23-92B6-90BE98752D84](https://user-images.githubusercontent.com/120598400/210329817-55305f9b-3d82-4c62-98a8-9cfbe340d53d.png)

**Comment by khanhduytran0** [comment]
Given information is not complete. You’re not using Android.
The last screenshot, though, appears to stated that you were using Java 17 for Minecraft Forge.

**Comment by PsanesX** [comment]
Thanks
