### ISSUE TITLE
[F-Req] Black Background under Java activity for windowed mode

### ISSUE THREAD

**Issue by pimikiel** [PojavLauncherTeam/PojavLauncher#3818]
### Is this request related to a bug?

Is this request related to a bug? 
Kinda, but very specific one, nothing to fix in a java translation or something.

### Describe the request.

Hi
I'm playing under samsung dex UI many times, and everytime I make PojavLauncher in window, it's semi transparent. (see an attachment)
![Screenshot_20230103_144816_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/11504006/210369868-57ba8bcc-886f-48aa-9366-10f402d91e88.png)

and I found out that if it have black background, it looks like normal.

![Screenshot_20230103_144810_Samsung DeX home](https://user-images.githubusercontent.com/11504006/210369897-084f8092-98d8-48c5-97d0-919549be8de6.png)

Can I ask for black background under java activity to be added in newer release?

**Comment by GaucovyAero** [comment]
issue fixed in the latest actions build
