### ISSUE TITLE
[BUG] error 1

### ISSUE THREAD

**Issue by MrVSnim** [PojavLauncherTeam/PojavLauncher#3819]
### Describe the bug

This error 1 started after a new update 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10337721/latestlog.txt)

### Steps To Reproduce

```markdown
1.I run pojav laucher 2. I choose the version (any) 3. I start the game and error 1
```

### Expected Behavior

I expected the game to start and I would be able to play 

### Platform

```markdown
- Device model:OPPO A31 
- CPU architecture: aarch64
- Android version:9 
- PojavLauncher version:dahlia-176-641eae051-v3_openjdk
```

### Anything else?

It appeared after the update

**Comment by GaucovyAero** [comment]
This is not a pojav issue. Don't download JARs with Chrome. Use Firefox or Bromite.

**Comment by MrVSnim** [comment]
I didn't understand anything, okay......

**Comment by MrVSnim** [comment]
Are you talking about Forge

**Comment by MrVSnim** [comment]
Я скачиваюа через Яндекс это нормально?

**Comment by GaucovyAero** [comment]
> Are you talking about Forge

yep
