### ISSUE TITLE
[BUG] Forge Dark Screen

### ISSUE THREAD

**Issue by L0stFromSleep** [PojavLauncherTeam/PojavLauncher#3820]
### Describe the bug

When I have installed forge for version 1.12.2 and start up the game the screen is SUPER DARK seen below (you to look very closely to see the title screen)
![Screenshot_20230103-185805_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/121911187/210465426-8b2f2164-4c20-4e6a-9212-f6d5c5d4240b.jpg)

### The log file and images/videos

![Screenshot_20230103-185805_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/121911187/210465600-dbdc5956-f3ca-4bfc-aea9-7c7d9278d272.jpg)

### Steps To Reproduce

```markdown
1. Start pojave launcher
2. Install forge 1.12.2
3.start game
```

### Expected Behavior

The screen will be very dark

### Platform

```markdown
- Device model: Galaxy A11 5G
- CPU architecture: idk
- Android version: idk
- PojavLauncher version: latest release
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by Slingexe** [comment]
I am having this issue, was there any fix?

**Comment by Billybobertjoe** [comment]
Having same issue
