### ISSUE TITLE
[BUG] <code 6>

### ISSUE THREAD

**Issue by GameCapp** [PojavLauncherTeam/PojavLauncher#3825]
### Describe the bug

Error code 6

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10355542/latest.log)

### Steps To Reproduce

```markdown
Join server
```

### Expected Behavior

Join server

### Platform

```markdown
- Device model: iphone
- CPU architecture: ios
- ios version: 15.4.1
- PojavLauncher version: 1.19
```

### Anything else?

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10355540/latest.log)

**Comment by JuiceQPS** [comment]
Same problem

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by GaucovyAero** [comment]
Closing this as it's an issue we cannot fix.
