### ISSUE TITLE
[BUG] can't see realms you own to join them

### ISSUE THREAD

**Issue by RedstoneManiac3Xbox** [PojavLauncherTeam/PojavLauncher#3826]
### Describe the bug

I signed in with my Microsoft account that owns a java realm but it doesn't show up at all

### The log file and images/videos

![Screenshot_20230105-154624](https://user-images.githubusercontent.com/88521290/210876796-0cf9d39e-828a-4a55-b125-423f43d709fb.png)

### Steps To Reproduce

```markdown
Start pojav
Sign in with Microsoft account
Load mc
Tap realms
See empty realms
```

### Expected Behavior

See joinable realms

### Platform

```markdown
- Device model: LM-v600
- CPU architecture: aarch 64
- Android version: 12
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

Nothing I know of

**Comment by khanhduytran0** [comment]
> version 3.3.1.1_rel_20210206

It’s a 2-year-ago version, which is very outdated!
Edit: it appears thar you copied the version from the example.
Please go to https://github.com/PojavLauncherTeam/PojavLauncher/actions and get the latest build.

**Comment by GaucovyAero** [comment]
Stale issue and fixed. Closing.
