### ISSUE TITLE
[BUG] inaccurate mouse

### ISSUE THREAD

**Issue by Jambuaeru** [PojavLauncherTeam/PojavLauncher#3827]
### Describe the bug

This bug occurs when the Pojav Launcher application is updated And this bug is very annoying

### The log file and images/videos

![IMG-20230107-WA0007~2](https://user-images.githubusercontent.com/122162020/211158942-463c5c9d-8a42-448d-bd2a-d42122df6dbe.jpg)

### Steps To Reproduce

```markdown
1.start pojav launcher
2.Select the version you want to play
3.Start the game
4.No need for special tricks, just turn on the mouse and the bug occurs
```

### Expected Behavior

i wish mouse in pojav launcher back to normal as before

### Platform

```markdown
- Device model: Oppo a3s 2/16G
- CPU architecture: aarch64
- Android version: 8.1.0
- PojavLauncher version: dahlia-203-66c3aecd2-v3_openjdk
```

**Comment by Thollp** [comment]
Enable "Ignore notch" in pojavlauncher settings

**Comment by Jambuaeru** [comment]
> Enable "Ignore notch" in pojavlauncher settings

Nope

![Screenshot_2023-01-12-22-48-24-77.png](https://user-images.githubusercontent.com/122162020/212116735-2eae29cb-87bc-4cea-bd48-c41906b36605.png)

**Comment by GaucovyAero** [comment]
Ignore notch only works on Android 9 and higher.
