### ISSUE TITLE
[BUG] <Short description> Cant access .minecraft folder

### ISSUE THREAD

**Issue by Darklight-007** [PojavLauncherTeam/PojavLauncher#3828]
### Describe the bug

I installed the forge modloader to add mods but when i tried to find the folder i cant find it and when i force enter it , it either says that the folder is corrupted or cant access folder

### The log file and images/videos

https://user-images.githubusercontent.com/89621633/211158806-6a77e63d-8bde-4add-8903-b8ee1f1fd934.mp4

### Steps To Reproduce

```markdown
1. start Pojav
2. install forge
3. try to find the folder
```

### Expected Behavior

i expected to find the Games folder but i couldnt

### Platform

```markdown
- Device model: Vivo V15 Pro
- CPU architecture: 
- Android version: 11
- PojavLauncher version: Latest Release
```

**Comment by TarikBR** [comment]
You need enable a setting to see hidden folders, this does not a bug

**Comment by henryyuyhy** [comment]
You can install an app called x-plore, I succeeded by doing that

**Comment by GaucovyAero** [comment]
MiXplorer is recommended. Not a pojav issue.
