### ISSUE TITLE
[BUG] [RENDERER] Virglrenderer crashing

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#3829]
### Describe the bug

when i do virgl renderer it crashes, but theres no option for opengl 3.0 for shaders my tablet dosnt support opengl 3.0+ so can you bring back the opengl 3.0 renderer or fix the problem of virgl compatibility 

### The log file and images/videos

i cant upload it said 

`somthing whet really wrong`

### Steps To Reproduce

```markdown
1. start pojav
2. do virgl
3. lunch any version of minceraft
4. krash
```

### Expected Behavior

I GET TO PLAY SHADER

### Platform

```markdown
- Device model: galaxy tab a
- CPU architecture: arm8vl or something 
- Android version: 11 
- PojavLauncher version: goooooooooooogle play
```

### Anything else?

no.

**Comment by Cube5x59999** [comment]
### [latestlog of pojav](https://github.com/PojavLauncherTeam/PojavLauncher/files/10368188/latestlog.txt)
_now uploading works_

**Comment by GaucovyAero** [comment]
try reinstalling pojav, virgl works for me on latest playstore 
![Screenshot_2023-01-08-13-03-37-688_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/85581164/211195036-3ff7a52b-2aa4-4e5a-a656-3407123152b9.jpg)

**Comment by Cube5x59999** [comment]
> try reinstalling pojav, virgl works for me on latest playstore ![Screenshot_2023-01-08-13-03-37-688_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/85581164/211195036-3ff7a52b-2aa4-4e5a-a656-3407123152b9.jpg)

dosnt work, i think compatibility issue, opengl 4.x not supported on my device. ill try reinstall because virgl is virual open gl and i cant understand why still dosnt work it should work without opengl 4.x support as its "virtual" or it could be a straight up a **RAM** issue (have 600 free mb total 2 gb system uses a lot)

**Comment by GaucovyAero** [comment]
do you have alternate surface rendering enabled?

**Comment by Cube5x59999** [comment]
> do you have alternate surface rendering enabled?

yes
Edit: _should i turn it off?_
Edit2: _turning it off dosnt fix issue_

**Comment by ItsManasxD** [comment]
Same problem with me same logs 
When I am trying to open game with Virgl Renderer it's just closed no errors nothing and when I see the log it said OSmesa Buffer Flush is desabled or something like that

**Comment by TheNevinPie** [comment]
Exactly, VirGL: OSMesa buffer flush is DISABLED is the last line which is there in the log till it crashes. Hey @Cube5x59999 can you tell me your device specifications (especially, the GPU present) im rlly curious to know...

**Comment by GaucovyAero** [comment]
> Exactly, VirGL: OSMesa buffer flush is DISABLED is the last line which is there in the log till it crashes. Hey @Cube5x59999 can you tell me your device specifications (especially, the GPU present) im rlly curious to know...

this is a 32-bit only issue, runs fine on 64 bit devices

**Comment by GaucovyAero** [comment]
Ima close this, since it's unfixable.
