### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by r4e33333** [PojavLauncherTeam/PojavLauncher#3832]
### Describe the bug

2222

### The log file and images/videos

2222

### Steps To Reproduce

```markdown
33333
```

### Expected Behavior

222222

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Vylesh** [comment]
Your Problem is LİGMA DİEASE !!! 🤣
