### ISSUE TITLE
Physics mod not working 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3833]
### Describe the bug

Exit code 1 when start the game 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
Paste the mod on mods folders
Select version
Start the pojavlauncher
Crash not loading
```

### Expected Behavior

Working on pojavlauncher 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: 
Latest on pojavlauncher action
```

### Anything else?

Plss help

**Comment by Cube5x59999** [comment]
change renderer to virgl renderer

**Comment by kedrick021** [comment]
Not working when using VirGl Render is crash

**Comment by Cube5x59999** [comment]
try ANGLE or Holy gl4es

**Comment by kedrick021** [comment]
> try ANGLE or Holy gl4es

All Render

**Comment by kedrick021** [comment]
> try ANGLE or Holy gl4es

None are working

**Comment by GaucovyAero** [comment]
iirc this mod needs PhysX, which only works on PCs
