### ISSUE TITLE
[BUG] black overlay on game

### ISSUE THREAD

**Issue by fo-od** [PojavLauncherTeam/PojavLauncher#3834]
### Describe the bug

Black overlay that covers the game but not the controls.
It looks fine if you take a screenshot, but its still there.

### The log file and images/videos

image: (using a phone to take picture)
![image](https://user-images.githubusercontent.com/99752044/211257788-087acba9-6db3-4516-818e-d3fcfb1ded5f.png)
log:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10371087/latestlog.txt)

### Steps To Reproduce

```markdown
1. own a chromebook
2. open pojavlauncher
3. launch 1.8.9
4. black overlay on game (the controls are visible but minecraft isnt)
```

### Expected Behavior

i expected it to work with no problems

### Platform

```markdown
- Device model: Lenovo 500e 2nd gen
- CPU architecture: x86-64
- Android version: 11
- PojavLauncher version: Latest google play version
```

**Comment by fo-od** [comment]
im just gonna use ATlauncher since i found out that chromebooks can run linux stuff, but this problem should still be fixed for people that cant turn on the linux things

**Comment by GaucovyAero** [comment]
yeah, no idea what's the issue, try enabling alternate surface rendering and change the renderer to gl4es

**Comment by GaucovyAero** [comment]
@fo-od do you have alternate surface rendering enabled or not, is there anything else that could cause issues? can you reproduce it with the latest actions build?
