### ISSUE TITLE
[BUG] i f**ked up minecraft text rendering 

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#3835]
### Describe the bug

text rendering go brrrrrrrrrr

### The log file and images/videos

![Screenshot_20230109-205356_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98256780/211344174-6918b326-031b-4aaf-a1b3-9075f61aece6.jpg)
![Screenshot_20230109-205402_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98256780/211344186-e3045b5c-6cd7-490e-965d-e24538ae95a8.jpg)
![Screenshot_20230109-205409_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98256780/211344190-d379ec94-9632-4b95-b7e1-6d1a8109d46c.jpg)

### Steps To Reproduce

```markdown
1. Start Minecraft 1.12.2 (optifine)
2. Set shaders to (internal)
3. Restart Minecraft 1.12.2 optifine
4. Set shaders to Off
Congratulations! you f**ked up minecraft!
```

### Expected Behavior

You know.

### Platform

```markdown
- Device model: Galaxy tab a
- CPU architecture: 32 bit (armv8l) 
- Android version: 11
- PojavLauncher version: Play store latest (checked on 9 January)
```

### Anything else?

NO!

**Comment by GaucovyAero** [comment]
You are out of GPU memory, this is caused by your tablet, we can't fix this.
