### ISSUE TITLE
[F-Req] 我是否可以把pojav launcher加入整合包

### ISSUE THREAD

**Issue by hyplant** [PojavLauncherTeam/PojavLauncher#3836]
### Describe the request.

请问我是否可以把pojav launcher加入整合包，如果可以的话需要注意什么？

### Anything else?

由于中国大陆地区访问discord不方便，我只能在这里提问。

**Comment by ConfectionaryQwQ** [comment]
Please use English Bro
请使用英语，兄弟
Provide relevant links about Pojav when u add it to u modpack
请在整合包中表明pojav官网及出处
One the other hand,"Watt Toolkit"can help u 
另外「原名 Steam++」Watt Toolkit能帮助您访问Discord
:3
