### ISSUE TITLE
[F-Req] Add Vgpu for shaders on 32bit 

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#3837]
### Is this request related to a bug?

Add Vpgu because a lot of People want shaders but virgl dosnt support 32bit, os its a problem for 32 bit users

### Describe the request.

Add the renderer Vgpu back or try to make virgl renderer compatible with 32 bit

error when virglrenderer in 32 bit:
`VirGl: OSMesa flush is DISABLED`

### Anything else?

Please add it asap, many of the players will like this :)

**Comment by Cube5x59999** [comment]
@GaucovyAero @khanhduytran0 @Mathias-Boulay  what are the chances of getting this fixed?

**Comment by TheNevinPie** [comment]
Can you tell which version of pojav have the vgpu option? I want to try it out to see if that works...

**Comment by GaucovyAero** [comment]
> 

0%
