### ISSUE TITLE
Failed to Parse, total failure of install

### ISSUE THREAD

**Issue by Jay192x** [PojavLauncherTeam/PojavLauncher#384]
![Screenshot_20201106-003830_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/49378350/98330774-2126a380-1fc9-11eb-99c1-2d2b803325e6.jpg)

So yeah, it won't work on my phone. Watched a youtube video that said it was caused by runtime and compiler versions are out of sync (not the same version). Not sure how to fix that on my phone. Any ideas?

**Comment by mglovers123** [comment]
This is v2 not v3 In order to run Minecraft 1.13+, it must be v3
