### ISSUE TITLE
[BUG] Default Java memory allocation on 32bit devices is over the maximum a 32bit jvm can handle

### ISSUE THREAD

**Issue by SolDev69** [PojavLauncherTeam/PojavLauncher#3840]
### Describe the bug

When first installing Pojav on 32bit systems the default memory allocation is above the highest amount 32bit java can handle, leading to an exit code 1 on most systems.

### The log file and images/videos

None generated.

### Steps To Reproduce

```markdown
1. Install PojavLauncher on a 32bit device
2. Try running any version
3. Crash on launch.
```

### Expected Behavior

"I expect the game to launches" is pretty accurate here. One shouldn't have to go into the ram settings just to get MC to load.

### Platform

```markdown
- Device model: Any 32 bit device
- CPU architecture: arm 32bit / armhf
- Android version: N/A
- PojavLauncher version: Latest git (dahlia 209)
```

### Anything else?

Capping the max possible ram to 1100MB on 32bit devices will work, and I would recommend setting it to 1024MB by default as that's what the vanilla launcher does/did (idk if they dropped support for 32bit launchers yet) on 32 bit systems. The slider is already capped so it's weird that it goes above that.

**Comment by GaucovyAero** [comment]
yeah, this makes a lot of sense, will be fixed most probably

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
