### ISSUE TITLE
关于改善鼠标功能的建议

### ISSUE THREAD

**Issue by henryyuyhy** [PojavLauncherTeam/PojavLauncher#3842]
### Is this request related to a bug?

no

### Describe the request.

我觉得你们可以将电脑触控板的一些功能添加进去，比如双指滑动滚动页面之类的。望采纳，谢谢

### Anything else?

no

**Comment by hyplant** [comment]
现在本来就是支持双指滚动的

**Comment by tttghkg** [comment]
建议用英文提问，似乎其他语言的问题不会被回复

**Comment by ConfectionaryQwQ** [comment]
你不用英文老外不会看
Please use English
双指可以滑动，或者变滑边一直点着PRI

**Comment by ConfectionaryQwQ** [comment]
你不用英文老外不会看
Please use English
双指可以滑动，或者变滑边一直点着PRI
这种简单的建议你去Discord问，这里问题反馈速度太慢了

**Comment by GaucovyAero** [comment]
We won't add this anytime soon.
