### ISSUE TITLE
[BUG] Flipped screen in render VGPU 

### ISSUE THREAD

**Issue by Duatredam** [PojavLauncherTeam/PojavLauncher#3843]
### Describe the bug

when i use mods or shaders, the screen is flipped

### The log file and images/videos

Nope 

### Steps To Reproduce

```markdown
Start Pojavlauncher
Use VGPU render
Start game 1.16.5-36.2.39 forge
Flipped screen
```

### Expected Behavior

Pls fix it 

### Platform

```markdown
- Device model: Samsung A52 5g
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: latest release version on CHplay
```

### Anything else?

Nope

**Comment by Cube5x59999** [comment]
when did vgpu came again? did they add it again??

**Comment by Cube5x59999** [comment]
or do you mean virgl renderer

**Comment by Duatredam** [comment]
> or do you mean virgl renderer
![20230112_191050](https://user-images.githubusercontent.com/122512901/212063369-67738102-abaa-4577-a4d8-d358cfc55266.jpg)

**Comment by Cube5x59999** [comment]
unofficial version, cant help, option of vgpu not shown in my pojav

**Comment by GaucovyAero** [comment]
screen flipping cannot be fixed unfortunately, just use gl4es
