### ISSUE TITLE
[BUG] Visual Item and Settings problems

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3844]
### Describe the bug

Unable to scroll by clicking certain areas of the bar in settings and the inventory, clicking on an item in the inventory doesn't work properly, will not move with cursor. It acts like the cursor isn't there, as nothing shows up when hovering over items or buttons in the gui. This is all in the latest GPlay release.

### The log file and images/videos

No crash happens

### Steps To Reproduce

```markdown
Start Pojavlauncher, then load a world and play.
```

### Expected Behavior

You should be able to click on the bars and items and see movement. 

### Platform

```markdown
- Device model: HP Chromebook 11a na-0010nr
- CPU architecture: MediaTek MT8183
- Android version: 9
- PojavLauncher version: Latest GPlay
```

**Comment by GaucovyAero** [comment]
Make sure to disable touchscreen emulation in your chromebook settings, and the scroll wheel will come later as a fix i guess.

**Comment by GaucovyAero** [comment]
closing as this is a duplicate
