### ISSUE TITLE
Transparent texture while using mods

### ISSUE THREAD

**Issue by Ryan-fmf** [PojavLauncherTeam/PojavLauncher#3845]
### Describe the bug

i was trying to use a mod called BetterPortals mod, then when i joined the world the blocks and mobs were with a strange texture ( i will send photos ), so i decided to search in youtube and found nothing, here in github i saw people saying to just turn on and off fullscreen till it fix it self, but it didn't worked for me, maybe its my version, im playing in 1.12.2 but the problem is that this mod only exists in this version of the game, does anyone know how to fix this problem?

### The log file and images/videos

![Screenshot_2023-01-12-19-19-02-664_net kdt pojavlaunch](https://user-images.githubusercontent.com/67510051/212196562-8ce12156-cadb-4625-b95d-a5046a5fa234.jpg)
![Screenshot_2023-01-12-19-19-09-660_net kdt pojavlaunch](https://user-images.githubusercontent.com/67510051/212196566-f12e6697-7044-4768-8538-9623720ca4df.jpg)
![Screenshot_2023-01-12-19-19-24-604_net kdt pojavlaunch](https://user-images.githubusercontent.com/67510051/212196567-eabec7d2-9fdf-44f3-bf11-4487c665059e.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Download Forge 1.12.2 and install
3. Download and install BetterPortals mod and Forgelin(required to run the BetterPortals mod)
4. Join the game and create a new world
5. Join the new world
(Idk if its right)
```

### Expected Behavior

I expect normal textures

### Platform

```markdown
- Device model: Poco X4 GT 8/256G
- CPU architecture: idk but the cpu is a dimensity 8100(octa-core max 2,85GHz)
- Android version: 13
- PojavLauncher version: Latest release
```

### Anything else?

Nop

**Comment by GaucovyAero** [comment]
This is not caused by the mods. Just press F11.

**Comment by Ryan-fmf** [comment]
> This is not caused by the mods. Just press F11.

Ye i tryied but it didn't worked

**Comment by GaucovyAero** [comment]
> > This is not caused by the mods. Just press F11.
> 
> Ye i tryied but it didn't worked

well, that's the only solution unfortunately
