### ISSUE TITLE
[F-Req/Bug] Unable to access plauncher's data directory without external device or root

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [PojavLauncherTeam/PojavLauncher#3846]
### Describe the bug

On many newer models from Samsung, some directories are locked from being accessed due to security measures implemented by Samsung. One of these directories includes `~/android/data` which has the `net.kdt.pojavlaunch` directory to which instances can be accessed. Although you can access the data by connecting the device to a computer, it kinda defeats the point of java edition on mobile. Having a built in mods, resourcepack, world, etc. import options would be handy. A full blown file explorer even better.

### The log file and images/videos

There are no log files associated with this issue, but here is a screenshot of the `~/android/data` directory when navigating to it. As a note, hidden files is enabled:
![screenshot of the lack of contents of the android/data directory](https://user-images.githubusercontent.com/47730899/212205070-a0c9fac6-4150-48a7-a0c9-c03eb5999022.jpg)

### Steps To Reproduce

```markdown
Note: pre-requisite for reproduction requires a device that locks the `~/android/data` directory like many newer US based Samsung phones 

1. Install Pojavlauncher
2. Navigate to `~/android/data`
```

### Expected Behavior

My device is expected to lock the `~/android/data` directory, however preferably, I would be able to access `net.kdt.pojavlaunch`

### Platform

```markdown
- Device model: Samsung Galaxy A53 5G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Release as of 1/12/23
```

**Comment by hyplant** [comment]
试试mt管理器或es文件浏览器

**Comment by PaxiTheAlchemist** [comment]
> 试试mt管理器或es文件浏览器
*Translated: try mt manager or es file explorer*

The screenshot within the issue report was using the stock file explorer for Samsung ("My Files"). I've also attempted to use some open source managers derived from f-droid to which all errored and occasionally insisted root permission. Im unfamiliar with mt manager, [but didnt es file explorer get taken off of the playstore by google for committing click fraud?](https://wikiless.org/wiki/ES_File_Explorer?lang=en#Controversy_and_removal_from_Play_Store) Regardless, I highly doubt using a third party file explorer will magically unlock a secured directory. This on top of Samsung's iron grip on "security" with it's knox suite preventing me from rooting my device to begin with.

**Comment by PaxiTheAlchemist** [comment]
Also, if anyone has triage access, I would like to request that the `enhancement` label be added to my issue as I suggested a solution to the issue that I am having

**Comment by GaucovyAero** [comment]
> Also, if anyone has triage access, I would like to request that the `enhancement` label be added to my issue as I suggested a solution to the issue that I am having

I recommend using MiX, it runs on Android 2.2 and higher and can go into the Android 13 /storage/emulated/0/Android/data/ directory without issues.
