### ISSUE TITLE
Mouse Hovering bug in all versions.

### ISSUE THREAD

**Issue by IamaPineapple24** [PojavLauncherTeam/PojavLauncher#3847]
### Describe the bug

Hi! This issue started quite suddenly and I don't think i'd updated anything prior to this starting, but recently my mouse suddenly stopped being able to hover over buttons. It worked fine when trying a different mouse and in other android and web apps so i'm convinced it's a problem with the app. there is a video attached of what the bug is, I can't really explain it very well here.

### The log file and images/videos

latestlog.txt:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10410486/latestlog.txt)
The video:
https://www.dropbox.com/s/o4cw5izabdhxoaq/InShot_20230113_095224993.mp4?dl=0
Just a Dropbox link.

### Steps To Reproduce

```markdown
I just started the game and it happened seemingly for no reason
```

### Expected Behavior

I expect the buttons  in-game and items to glow blue/grey background when i hover over it with the mouse.

### Platform

```markdown
- Device model: HP Chromebook 11 G8 EE 16GB
- CPU architecture: x86 Architecture
- Computer OS: Google ChromeOS
- OS Version: Google ChromeOS Canary Version 109.0.5414.41 (Beta, Official Build) 64-bit.
- PojavLauncher version: Dahlia-209-0a485c9b0-v3_OpenJDK
```

### Anything else?

The problem started suddenly and I can't find a cause, I have already tried:
- Restarting the game.
- Restarting the launcher.
- Restarting my computer.
- Re-installing PojavLauncher and Minecraft.
- Using a different Minecraft version.

**Comment by GaucovyAero** [comment]
we likely cannot fix this though, make sure you have touch emulation disabled in your chromebook settings

**Comment by gtaiscool236** [comment]
How do you do that?

**Comment by IamaPineapple24** [comment]
> we likely cannot fix this though, make sure you have touch emulation disabled in your chromebook settings

How do you turn off touch emulation? i can't find it in my settings.

**Comment by GaucovyAero** [comment]
> > we likely cannot fix this though, make sure you have touch emulation disabled in your chromebook settings
> 
> How do you turn off touch emulation? i can't find it in my settings.

try the latest actions build, it should be fixed now https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4015149875, just download app-debug here

**Comment by IamaPineapple24** [comment]
> > > we likely cannot fix this though, make sure you have touch emulation disabled in your chromebook settings
> > 
> > 
> > How do you turn off touch emulation? i can't find it in my settings.
> 
> try the latest actions build, it should be fixed now https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4015149875, just download app-debug here

Yeah, thanks! got it working now. the settings was in android settings, rather than chromeos setings.

**Comment by Mathias-Boulay** [comment]
good then
