### ISSUE TITLE
How i can upload mods?

### ISSUE THREAD

**Issue by Enrico333** [PojavLauncherTeam/PojavLauncher#3848]
### Describe the bug

Helle i am on ios 16.2 and in the data manager from Apple and There is no way to show files that statrts with .     

### The log file and images/videos

No Video

### Steps To Reproduce

```markdown
No
```

### Expected Behavior

No

### Platform

```markdown
- Device model: iPhone 14 pro
- CPU architecture: a16
- Android version: 16.2
- PojavLauncher version:
```

### Anything else?

No

**Comment by khanhduytran0** [comment]
macOS doesn’t use `.minecraft` as place to store game data, so the same applies for iOS. Instead, go to launcher Settings > Minecraft game directory > long-press on the instance that you’d like to install mod to > Files. This will take you to place. Create a folder named `mods` if it isn’t there.

**Comment by GaucovyAero** [comment]
answered

**Comment by GaucovyAero** [comment]
answered
