### ISSUE TITLE
chromebook support

### ISSUE THREAD

**Issue by speedythehedghog** [PojavLauncherTeam/PojavLauncher#3849]
Chromebook support

can you add chromebook support in settings or somthing couse its hard to navagate on chrombook you cant use the scroll weel and on the newest update it broke completely you have to hold down lmb to do stuff in you invin tory and you cant use the slider box to navigate in any settings sutch as controll setting ect pls add a chromebook feature it would mean alot thats all thanks for reading this! :P

### Describe the request.

chromebook support

### Anything else?

nope  :P

**Comment by GaucovyAero** [comment]
this will be worked on later

**Comment by GaucovyAero** [comment]
closing, as this is a duplicate issue
