### ISSUE TITLE
Is labymod client installer can install in pojav

### ISSUE THREAD

**Issue by KUALALUM** [PojavLauncherTeam/PojavLauncher#385]
I already try it with the latest and its loong time to open and log ouput didnt show up

**Comment by leetmussc** [comment]
No

**Comment by leetmussc** [comment]
You cant

**Comment by leetmussc** [comment]
I've tried

**Comment by KUALALUM** [comment]
Ok :(

**Comment by khanhduytran0** [comment]
At the moment, the mod installer can only work with non-font programs, so most will not work. At least, if you have pc, install from it and copy .minecraft folder to phone.
