### ISSUE TITLE
The dead zone of the right rocker of the game controller is too large, and the angle of view can only rotate if it is moved far away. I hope to improve the dead zone of the right rocker of the game controller to make it more sensitive and try to be the same as the rocker of the bedrock version.[BUG] <Short description>[BUG] <Short description>

### ISSUE THREAD

**Issue by jiuhui0415** [PojavLauncherTeam/PojavLauncher#3851]
### Describe the bug

The dead zone of the right rocker of the game controller is too large, and the angle of view can only rotate if it is moved far away. I hope to improve the dead zone of the right rocker of the game controller to make it more sensitive and try to be the same as the rocker of the bedrock version.[BUG] <Short description>

### The log file and images/videos

The dead zone of the right rocker of the game controller is too large, and the angle of view can only rotate if it is moved far away. I hope to improve the dead zone of the right rocker of the game controller to make it more sensitive and try to be the same as the rocker of the bedrock version.[BUG] <Short description>

### Steps To Reproduce

```markdown
The dead zone of the right rocker of the game controller is too large, and the angle of view can only rotate if it is moved far away. I hope to improve the dead zone of the right rocker of the game controller to make it more sensitive and try to be the same as the rocker of the bedrock version.[BUG] <Short description>
```

### Expected Behavior

The dead zone of the right rocker of the game controller is too large, and the angle of view can only rotate if it is moved far away. I hope to improve the dead zone of the right rocker of the game controller to make it more sensitive and try to be the same as the rocker of the bedrock version.[BUG] <Short description>

### Platform

```markdown
- Device model: redmi k50 pro 8+256
- CPU architecture: Dimensity 9000
- Android version: 12
- PojavLauncher version: Google
```

**Comment by Mathias-Boulay** [comment]
What do you mean by  "the rocker" ?

**Comment by GaucovyAero** [comment]
> What do you mean by "the rocker" ?

the joystick responsible for looking around probably

**Comment by Mathias-Boulay** [comment]
It has been adjusted. And you can configure it inside settings in mainline dev builds
