### ISSUE TITLE
My pojav keeps crashing on a specific server[BUG] <Short description>

### ISSUE THREAD

**Issue by KindaWeird123** [PojavLauncherTeam/PojavLauncher#3852]
### Describe the bug

every time i log in my friends server the log always says the begining of crash

### The log file and images/videos

content://net.kdt.pojavlaunch.scoped.gamefolder/document/%2Fstorage%2Femulated%2F0%2Fgames%2FPojavLauncher%2Flatestlog.txt

### Steps To Reproduce

```markdown
1. Load a modded server or somethin
2. Watch as the log file is insanely confusing
```

### Expected Behavior

I expected it to work just fine and not show a black void

### Platform

```markdown
- Device model: CPH1853
- CPU architecture: 8x ARM Cortex-A53 @ 1.80
GHz
- Android version: 8.1.0
- PojavLauncher version: Version dahila-209-0a485c9b0-v3_openjdk
```

### Anything else?

If you can fix this i will be very gratefull!!

**Comment by KindaWeird123** [comment]
https://drive.google.com/file/d/1BR8WjtprxOJ0ES2rwgYTSoFakqk1RdgW/view?usp=drivesdk
yeah so im a dumbass

**Comment by GaucovyAero** [comment]
> https://drive.google.com/file/d/1BR8WjtprxOJ0ES2rwgYTSoFakqk1RdgW/view?usp=drivesdk yeah so im a dumbass

disable render regions in optifine performance settings

**Comment by KindaWeird123** [comment]
THANK YOU SO MUCH

**Comment by GaucovyAero** [comment]
fixed
