### ISSUE TITLE
[BUG] <Game Exited On Higher Phone Version>

### ISSUE THREAD

**Issue by BlueParrot789** [PojavLauncherTeam/PojavLauncher#3853]
### Describe the bug

Application exited with code 1 on android 8.1.0 (Oppo A5s) newest version (Google Play)
Run Normaly on Lenovo Tab 3 8, or Tab 3 7 ( i don't know)
Alot of devices have this problem

### The log file and images/videos

I didn't have

### Steps To Reproduce

```markdown
[Oppo A5s]
When Download Minecraft version (1.12.2)
Game exited with code 1
Install Optifine (1.12.2)
Game exited with code 1
Adjust setting ram , render, quality
Game exited with code 1
[Lenovo Tab 3 7]
Run Normaly
```

### Expected Behavior

Game launches normally

### Platform

```markdown
- Device model:Oppo A5S
- CPU architecture:Mediatek 
- Android version:8.0
- PojavLauncher version:Google play
```

**Comment by GaucovyAero** [comment]
This is just outright stupid, make sure you attach latestlog.txt
Thanks.

**Comment by GaucovyAero** [comment]
closing this as it is an issue on your side
