### ISSUE TITLE
[F-Req] Re-add the ability to swipe from the right to open the in-game menu

### ISSUE THREAD

**Issue by m-doescode** [PojavLauncherTeam/PojavLauncher#3855]
### Is this request related to a bug?

Not exactly, more of a quality of life improvement.

### Describe the request.

Previously, the in-game menu (the one with the options to customize controls and force close the game) could be opened by swiping from the right side of the screen.

However, in newer versions this functionality seems to have been replaced by a small settings button at the top of the screen. On my phone, it is too small to tap consistently and is kind of annoying to press.

It would be cool to have an option in the control settings to re-enable the ability to swipe from the right to open the menu. That way, people that like the new button could benefit from it but also those who prefer the old swiping method could use that as well.

### Anything else?

This affects version: (latest version on Play Store, will edit this later).

I would be happy to help by creating a pull request if this gets approved.

**Comment by GaucovyAero** [comment]
yeah, pretty sure this will somehow be enhanced in a later version of pojav - some people were complaining about the swipe thing during PvP with 8-finger controlmaps, etc., so we've made a solution. However, yeah, may be the most practical for casual players.

**Comment by GaucovyAero** [comment]
okay, kinda fixed i guess? you can now bind a controlmap button to it in the latest actions build
