### ISSUE TITLE
crashes on launching game code -1

### ISSUE THREAD

**Issue by jaycob12** [PojavLauncherTeam/PojavLauncher#3856]
### Describe the bug

when ever i try to launch the game 1.19.2 forge 43.2.3 it crashes with mods it also wont work without mods
logs and screenshot attached 

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10443532/latest.log
![Screenshot_20230118-174724~2](https://user-images.githubusercontent.com/24585354/213115641-707a7077-2f37-4021-8ad8-0e85cf5f99e5.jpg)
)

### Steps To Reproduce

```markdown
start the app 
click play
startes to load(black screen)
crashes app
```

### Expected Behavior

to rund modded minecraft

### Platform

```markdown
- Device model: ROG phone 6
- CPU architecture: ARM Cortex-X2
- Android version: android 13
- PojavLauncher version: dahlia-209-0a485c9b0-v3_openjdk
```

**Comment by GaucovyAero** [comment]
send latestlog.txt without mods and use gl4es as your renderer.

**Comment by GaucovyAero** [comment]
forge works, this is an issue on your side.
