### ISSUE TITLE
[BUG] 1.14-1.14.4

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#386]
![Screenshot_2020-11-08-10-55-18-621_net kdt pojavlaunch](https://user-images.githubusercontent.com/74020022/98460100-4e827580-21b2-11eb-8ff7-405bda580141.jpg)
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Change GUI scale to auto.

**Comment by WesleyVanNeck** [comment]
Fixed in the latest devbuild
