### ISSUE TITLE
Add better mouse and keyboard support.

### ISSUE THREAD

**Issue by AGENTISNUM1** [PojavLauncherTeam/PojavLauncher#3861]
### Is this request related to a bug?

To my knowledge, no.

### Describe the request.

In the newest update the game was made more touchscreen accessible. It was made so that, instead of hovering over items like usual, you had to double click on them to select them. I think this was a great feature for touchscreen users. But for people on chromebooks, this soon became annoying. I recommend that a setting is added to disable this, and make the game playable with a mouse once again. This setting could be added under miscellaneous and would default back to the original java gameplay. 

Thank you in advance,

-Wizard_11

**Comment by Mathias-Boulay** [comment]
Actually, nothing was changed
chances are you have touchscreen emulation enabled on your chromebook or something

**Comment by GaucovyAero** [comment]
yeah, make sure you have touchscreen emulation disabled

**Comment by GaucovyAero** [comment]
closing this as it is an issue on your side

**Comment by AGENTISNUM1** [comment]
Thank you so much, i have not been able to respond because my computer broke. Again, thanks for the fix.
