### ISSUE TITLE
[BUG] Test

### ISSUE THREAD

**Issue by Mathias-Boulay** [PojavLauncherTeam/PojavLauncher#3862]
### Describe the bug

Test

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10469491/latestlog.txt)

### Steps To Reproduce

```markdown
test
```

### Expected Behavior

test

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10469683/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10469726/latestlog.txt)

**Comment by VenomousSteam81** [comment]
***test***

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10471935/latestlog.txt)
