### ISSUE TITLE
[Bug] Screen Goes Black

### ISSUE THREAD

**Issue by RandomGitHubber302** [PojavLauncherTeam/PojavLauncher#3863]
### Describe the bug

Recently I had messed with the Pojav Files, and messed everything up, so I uninstalled and reinstalled the app. I had logged in, created a new profile in 1.16.5, 1.17.1, 1.18.2, 1.19.2. I created a world, and when I played, it would flicker black, and then stay black until I moved my cursor. Whenever my cursor was off the window or hidden, the screen would turn black. I tried it in a different version, the same thing. I installed optifine, forge, and fabric. None of them helped.

### The log file and images/videos

[Screen recording 2023-01-20 12.43.03.webm](https://user-images.githubusercontent.com/123204394/213792179-743acccd-37de-4f0d-88b7-349139c559d4.webm)

### Steps To Reproduce

```markdown
1. Launch Minecraft.
2. Hover your cursor off of the window, or hide it.
```

### Expected Behavior

I expected the game to be back to normal besides my worlds being deleted.

### Platform

```markdown
- Device model: I don't know.
- CPU architecture: I don't know. 
- Android version: Chrome OS, Version 109.0.5414.94 (Official Build) (64-bit)
- PojavLauncher version: Latest Update, I even tested again before writing, uninstalled and reinstalled.
```

### Anything else?

I think it has the same results with different renderers, but I can't remember if I had been testing for the black screen or something else. Even though it doesn't appear in the video for some reason, when the on screen buttons turn red, that is the loading screen, and when I bring up the shelf, it turns black. When I uninstalled the app it deleted all of my pojav files, so there wasn't anything from before that could've interfered. Thank you for your dedication to this.

**Comment by GaucovyAero** [comment]
i think you will have to get your device model for this, because it can be a device-specific issue
as a quick fix, can you try turning on alternate surface rendering and setting your renderer to gl4es?
- also make sure you don't have touchscreen emulation enabled in chromebook settings (maybe it's in developer settings idk)

**Comment by GaucovyAero** [comment]
Closing this as it's a duplicate.
