### ISSUE TITLE
[BUG] Test 2, love webhooks

### ISSUE THREAD

**Issue by Mathias-Boulay** [PojavLauncherTeam/PojavLauncher#3864]
**Pojav version:** dahlia-209-0a485c9b0-v3_openjdk

**Architecture:** ARM_64

**Renderer:** HOLY_GL4ES_114

**Minecraft version:** 1.19.2-optifine_hd_u_h9 - Type:OPTIFINE

**Java version:** INTERNAL JRE 17

**Errors detected:**

**Comment by Mathias-Boulay** [comment]
test 2222222

**Comment by ThatMG393** [comment]
test 3333333

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10472831/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10473166/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10473211/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10473221/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10473230/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10473248/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10473288/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
**Pojav version:** dahlia-209-0a485c9b0-v3_openjdk

**Architecture:** ARM_64

**Renderer:** HOLY_GL4ES_114

**Minecraft version:** 1.19.2-optifine_hd_u_h9 - Type:OPTIFINE

**Java version:** INTERNAL JRE 17

**Errors detected:**

**Comment by Mathias-Boulay** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10473288/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 209 - v3_openjdk |
| Minecraft version | 1.19.2-optifine_hd_u_h9 - OPTIFINE |
| Renderer | HOLY_GL4ES_114 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 17 |
| Java arguments |  |



|Errors Found: |
|--|
| opengl.generic.error |
| optifine.render_region.on |
