### ISSUE TITLE
Microsoft Passwordless Bug

### ISSUE THREAD

**Issue by NopeProsOnly** [PojavLauncherTeam/PojavLauncher#3865]
### Describe the bug

Turn your Microsoft account to a passwordless one.

### The log file and images/videos

Can't send screenshots for some reason

### Steps To Reproduce

```markdown
Turn your Microsoft account to a passwordless one. Then try to log in with pojav launcher. Boom error
```

### Expected Behavior

Successfully log into my account.

### Platform

```markdown
- Device model: Samsung something
- CPU architecture: ...
- Android version: 12
- PojavLauncher version: 
Latest
```

**Comment by Mathias-Boulay** [comment]
Hi there, can you do a few things for us
First, what is a passwordless account ?
Second, upload the error if possible
Third, a video to reproduce the crash would be nice

**Comment by NopeProsOnly** [comment]
[This](https://support.microsoft.com/en-us/account-billing/how-to-go-passwordless-with-your-microsoft-account-674ce301-3574-4387-a93d-916751764c43#:~:text=What%20does%20%22Going%20Passwordless%22%20mean,and%20convenient%20sign%2Din%20method.)

Gonna have to wait till tmr for the rest.

**Comment by Mathias-Boulay** [comment]
damn, didn't think it was possible
check you're on the current major update, just to be sure

**Comment by Mathias-Boulay** [comment]
*also, 50% chances the token has been revoked or something*

**Comment by NopeProsOnly** [comment]
I tried to login without the password, it didn't work. Then I reversed my action, and tried logging in again. It worked this time. So I don't think the problem is the token.

**Comment by NopeProsOnly** [comment]
Yep, I'm on the latest version

**Comment by Mathias-Boulay** [comment]
By the way, the crash log would be quite useful to us 😄

**Comment by GaucovyAero** [comment]
send latestcrash.txt or at least provide us with a screenshot

**Comment by NopeProsOnly** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10492361/latestlog.txt)
Hope this is the right one

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10492361/latestlog.txt) Hope this is the right one

this is just you playing hypixel

**Comment by GaucovyAero** [comment]
@NopeProsOnly change your account back to the passwordless one and send the error or something

**Comment by NopeProsOnly** [comment]
Hmm that's weird. It's not happening anymore... guess we can close this?

**Comment by GaucovyAero** [comment]
> Hmm that's weird. It's not happening anymore... guess we can close this?

okay cool
