### ISSUE TITLE
[BUG] crashes immediately

### ISSUE THREAD

**Issue by Fiz2zy** [PojavLauncherTeam/PojavLauncher#3868]
### Describe the bug

I press play on any version and a black screen appears for all of a millisecond before everything crashes. This only started happening after I updated the launcher on google play to the latest version.

### The log file and images/videos

There were no logs.

### Steps To Reproduce

```markdown
1. Open the latest version of pojavlauncer
2. Log in
3. Press play
4. Cry for a bit
```

### Expected Behavior

Game should actually start up

### Platform

```markdown
- Device model: Galaxy A12
- CPU architecture: 
- Android version: Android 11
- PojavLauncher version: latest
```

**Comment by artdeell** [comment]
No log

**Comment by GaucovyAero** [comment]
pojav is prone to update failures, make sure you:
1. uninstall pojav and remove all its data
2. restart your phone

before proceeding to install new pojav

**Comment by GaucovyAero** [comment]
answered, closing
