### ISSUE TITLE
[F-Req] Add new function: install integration package

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#3869]
### Is this request related to a bug?

It's not about mistakes

### Describe the request.

I suggest adding "install integration package" option.This will greatly improve the efficiency of installing the integration package, which is convenient and fast.

### Anything else?

not have

**Comment by Mathias-Boulay** [comment]
what is an "integration package" ?

**Comment by Baobuchi** [comment]
> 什么是“集成包

模组包

**Comment by GaucovyAero** [comment]
> what is an "integration package" ?

uhm i think hes trying to say that for example; custom controls would be an addon apk into pojav, just like MiX Archive and MiX PDF are to MiX

**Comment by GaucovyAero** [comment]
we'll not add this anytime soon tho
