### ISSUE TITLE
Fabric installer is it work

### ISSUE THREAD

**Issue by KUALALUM** [PojavLauncherTeam/PojavLauncher#387]
I try to download the fabric and i use the latest 1. After thats i open the log ouput to see is it work or not and i get this code
S/jrelog  (22433): 
S/jrelog  (22433): Latest Version: 1.16.4
S/jrelog  (22433): Latest Loader: 0.10.6+build.214
S/jrelog  (22433): referenceTable GDEF length=22 1
S/jrelog  (22433): referenceTable GSUB length=1206 1
S/jrelog  (22433): referenceTable GPOS length=12 1
S/LaunchJVM(22433): Freeing args
S/LaunchJVM(22433): Free done
  
I didnt understand thats and i wait about 20 minute and the screen still like this
![Screenshot_20201108_193029](https://user-images.githubusercontent.com/67228223/98463891-b4462000-21f9-11eb-8665-b66014289179.jpg)

My phone type is vivo y55l
2GB ram
16GB rom
Android ver. 6.0.1

**Comment by Malaska678** [comment]
Why use mod installer. Its still broken. Pls follow duy's instructions

**Comment by WesleyVanNeck** [comment]
mod installer is broken
