### ISSUE TITLE
Texture bug , drop fps , battery decrease

### ISSUE THREAD

**Issue by mahmoud-games12** [PojavLauncherTeam/PojavLauncher#3870]
### Describe the bug

I tried all performance and graphic settings but it still lagging and texture is not have alpha like (torch is block and grass background)
2-When I play (100% battery) 2 hours, then I see the battery it decrease 4x (30%)          **(my battery 6000mah)**

### The log file and images/videos

![msg1906825982-133](https://user-images.githubusercontent.com/75240258/214152267-e3ef1266-015d-48e1-af27-35ed7b1d2461.jpg)

### Steps To Reproduce

```markdown
1- start playing 1.19.2 with these settings
2-play any map
```

### Expected Behavior

I expect the game will be clean

### Platform

```markdown
- Device model: Realme C15 4/64GB
- CPU architecture: AArch 64 Processor rev 4 (aarch64)
- Android version: Android 10-Q (rollback version)
- PojavLauncher version: dahlia-218-6888cb7d8-v3_openjdk (latest version)
```

**Comment by mchnjt** [comment]
> ![msg1906825982-133](https://user-images.githubusercontent.com/75240258/214152267-e3ef1266-015d-48e1-af27-35ed7b1d2461.jpg)

This screenshot doesn't seem to help at all, hm
Maybe send us a log? (`latestlog.txt`)

Also, please use GL4ES or the newer variant (`Holy GL4ES`) that SerpentSpirale made.

For the battery issue, while launching PojavLauncher, launch AIDA64 alongside (either in a floating window or using the split screen feature) and take a look at the `Discharge Rate` if it's going crazy while playing PojavLauncher.

**Comment by mahmoud-games12** [comment]
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10484294/latest.log)

Discharge Rate: (normal 200-400ma)       (when launch 400-950ma) 
Is it going very crazy ?

**Comment by mahmoud-games12** [comment]
After change virglrenderer to holy gl4es
When I enter in server or map, it **crashed**

**Comment by Mathias-Boulay** [comment]
I recommend angle instead of virgl, at the very least

**Comment by GaucovyAero** [comment]
> [latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10484294/latest.log)
> 
> Discharge Rate: (normal 200-400ma) (when launch 400-950ma) Is it going very crazy ?

yeah that's normal, it's a PC game, what did you even expect?

**Comment by GaucovyAero** [comment]
> After change virglrenderer to holy gl4es When I enter in server or map, it **crashed**

send latestlog.txt, it's located in the pojavlauncher directory, not in .minecraft

**Comment by GaucovyAero** [comment]
well, we can't do anything about battery usage other than you lowering details and max fps. OptiFine + GL4ES is recommended, using the fps boost modpack in the official pojav discord server is also fine.
