### ISSUE TITLE
Handle（controller）

### ISSUE THREAD

**Issue by Maritako** [PojavLauncherTeam/PojavLauncher#3874]
### Is this request related to a bug?

I use a handle to play, but I can't find the function to modify the handle buttons. How to modify the handle buttons?

### Describe the request.

Modify handle buttons

**Comment by GaucovyAero** [comment]
whats a handle?

**Comment by ENDERMANYK** [comment]
he means controller, he maybe using the machine translation since "手柄"(controller) will translate to "handle".

**Comment by Maritako** [comment]
yes!

**Comment by GaucovyAero** [comment]
hm, closing as this is a duplicate

**Comment by Maritako** [comment]
> hm, closing as this is a duplicate

Link?
