### ISSUE TITLE
[BUG] <Short description>Angle error

### ISSUE THREAD

**Issue by YX-IT** [PojavLauncherTeam/PojavLauncher#3875]
### Describe the bug

It will be an error to click esc to exit the mobile viewing angle when opening the backpack, workbench, furnace and other containers in the game.

### The log file and images/videos

Angle error
![Screenshot_20230126_011719_com huawei himovie](https://user-images.githubusercontent.com/81810514/214634855-2d2390c6-9875-4e07-9a31-6b790c060666.jpg)
![Screenshot_20230126_011723_com huawei himovie](https://user-images.githubusercontent.com/81810514/214634882-5d08fb4d-36aa-4aa0-929f-b9bed6df3be9.jpg)

### Steps To Reproduce

```markdown
It will be an error to click esc to exit the mobile viewing angle when opening the backpack, workbench, furnace and other containers in the game.The angle of view will suddenly rotate.
```

### Expected Behavior

我希望可以修复这个bug

### Platform

```markdown
- Device model: HUAWEI mate 20 6/64
- CPU architecture: aarch64
- Android version: harmony 2.0
- PojavLauncher version: dahlia-218-6888cb7d8-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use gl4es, virgl is experimental

**Comment by YX-IT** [comment]
> 使用gl4es,virgl是实验性的

我用的就是holy gl4es
