### ISSUE TITLE
Custom controller button

### ISSUE THREAD

**Issue by Maritako** [PojavLauncherTeam/PojavLauncher#3878]
### Is this request related to a bug?

How to customize handle buttons? Just like the bedrock version of mine (pictured), I found that PojavLauncher does not seem to have this function, can it be added? My last question was also the same, but it was closed because of repetition, and I didn't see a similar article.
![Screenshot_2023-01-25-17-07-16-59_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/88639583/214800782-12a0bdc4-8668-4712-92f3-13cdb96aad73.jpg)

### Describe the request.

Custom controller buttons

**Comment by GaucovyAero** [comment]
this is a duplicate, closing, and no, you cannot
