### ISSUE TITLE
[BUG] Ingame Nickname is PlayerXX

### ISSUE THREAD

**Issue by Tayoikoo** [PojavLauncherTeam/PojavLauncher#388]
**Describe the bug**
In Launcher, My Nickname Is Tayoikoo but when ingame my nick is PlayerXX

**To Reproduce**
1. Start PojavLauncher
2.Login With Offline acconut
3.Start game
4.Joining Multiplayer
5.name is PlayerXX

**Screenshots**
![Screenshot_20201109_062925](https://user-images.githubusercontent.com/67594827/98487449-80004d00-2255-11eb-9aa1-5e4dbe8664ff.jpg)
![1604878425-picsay](https://user-images.githubusercontent.com/67594827/98487487-af16be80-2255-11eb-9fd4-71a67e52de3b.jpg)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Tayoikoo** [comment]
Actually, this is Cracked server.

**Comment by WesleyVanNeck** [comment]
cracked server problem

**Comment by Tayoikoo** [comment]
I found a way to fix it
Use AuthME (Fabric support)

**Comment by khanhduytran0** [comment]
Use latest Dev build for name and sound fix.

**Comment by khanhduytran0** [comment]
> cracked server problem

No, but Fabriced versions problem.

**Comment by khanhduytran0** [comment]
> Use latest Dev build for name and sound fix.

Will close once verified this fix.

**Comment by mglovers123** [comment]
nickname already working in latest build
