### ISSUE TITLE
[ERROR] <Short description>

### ISSUE THREAD

**Issue by theskybold** [PojavLauncherTeam/PojavLauncher#3880]
### Describe the bug

1 al conectar maose y teclado la plantilla brilla de color blanco , y al tocar ya pantalla del telefo vuelve a su color.

2 al conectar maose y teclado y luego avanzar con la flecha "W" la pantalla del minecraft se hacer pequeño y al volver a tocarla vuelve a su tamaño.

3 al conectar maose y teclado y al tocar correr y espacio al mismo tiempo el jugador se detiene , solo funciona bien si cambio el espacio (saltar) por otra tecla.

Todo probado en 2 dispositivos android 
1 tablet Lenovo
2 celular Huawei

### The log file and images/videos

No tengo ninguna prueba en imagen o en video

### Steps To Reproduce

```markdown
Conectar teclado y mause y iniciar el launcher
```

### Expected Behavior

1 que su color sea normal

2 Que al apretar la tecla "W" solo camine y cambie de tamaño la pantalla

3 que al apretar correr y saltar el jugador actúe normal como la versión de computadora 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Mathias-Boulay** [comment]
English wouldn't kill.
Please, provide videos of the issues, as well as your exact pojav version
