### ISSUE TITLE
[F-Req] 32-bit shader support

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#3881]
### Is this request related to a bug?

Virgl dosnt work on32 bit so we need some other renderer for 32 bit to run shaders

### Describe the request.

Add a new renderer or make it that holy gl4es exports opengl 3.0 instead of 2.1 for shaders on 32 bit, (strike out vgpu) virgl and angle render dosnt support 32 bit

### Anything else?

please provide a fix i like shaders and also you are most active than ever you closed a lot of reports
_or add vgpu back_

**Comment by mchnjt** [comment]
the only fix **YOU** can do at the moment is to plug in an RTX supported GPU on your phone. Also, you're probably one of the few unlucky souls that got a 32bit phone then proceeds to complain some stuff doesn't work. Remember, our phones don't work like computers.

**Comment by Cube5x59999** [comment]
> the only fix **YOU** can do at the moment is to plug in an RTX supported GPU on your phone. Also, you're probably one of the few unlucky souls that got a 32bit phone then proceeds to complain some stuff doesn't work. Remember, our phones don't work like computers.

i mean that you could add vgpu that works on olden days of pojav

**Comment by GaucovyAero** [comment]
> > the only fix **YOU** can do at the moment is to plug in an RTX supported GPU on your phone. Also, you're probably one of the few unlucky souls that got a 32bit phone then proceeds to complain some stuff doesn't work. Remember, our phones don't work like computers.
> 
> i mean that you could add vgpu that works on olden days of pojav

it actually didnt work on a lot of phones, and it also doesnt run 1.17+ so yeah
