### ISSUE TITLE
[BUG] how to install optifine (any) on forge 1.5.2? 

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#3882]
### Describe the bug

unable to install optifine on forge 1.5.2 

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I want to run forge 1.5.2 with optifine 

### Platform

```markdown
- Device model: Samsung Galaxy A52 
- CPU architecture: ?
- Android version:?
- PojavLauncher version: ?
```

**Comment by GaucovyAero** [comment]
you have to do it the same way as on pc but backwards

**Comment by Prostop194** [comment]
and more

**Comment by Prostop194** [comment]
but in reverse order

**Comment by Prostop194** [comment]
how should i do

**Comment by GaucovyAero** [comment]
yeah ima test it and ill tell you

**Comment by Prostop194** [comment]
Okey

**Comment by GaucovyAero** [comment]
![Screenshot_2023-01-27-19-06-03-734_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/85581164/215161756-3c243416-ecdb-4388-8003-a7bbf3e75733.jpg)
Okay, so the modpack i did about a year ago seems to work, but now i have to somehow get only optifine working

**Comment by Prostop194** [comment]
👍

**Comment by GaucovyAero** [comment]
okay so it worked for me first time for some reason, here's a tutorial:
1. You have to install Forge 1.5.2
1.1. You have to install the MiX file manager from mixplorer.com
3. Grab the Forge Patchpack v1.1 from an old issue here on github (you can find it on the last github issues page, its still open)
4. Install the JSON patch included in the patchpack - paste it into `.minecraft/versions/Forge1.5.2.../`
5. Download the Forge libraries - `fmllibs152.zip` from https://mcarchive.net/ (search for Forge). After you have successfully downloaded the libraries, extract `fmllibs152.zip` into a separate directory, then copy the .jar files in that directory into `.minecraft/lib/`
6. Start up Forge 1.5.2 and see if it's working
4.1. If it still doesn't work, make sure you download the Forge installer .jar with Firefox, definitely not Chrome
7. Duplicate Forge1.5.2... in `.minecraft/versions` and name the new folder for example `1.5.2-Forge_OF`
8. Change the **.jar** and **.json** name in the `.minecraft/versions/1.5.2-Forge_OF/` folder to `1.5.2-Forge_OF.jar` and `1.5.2-Forge_OF.json`
9. Open the JSON `.minecraft/versions/1.5.2-Forge_OF/1.5.2-Forge_OF.json` with MiX's text editor and change the `id` from Forge1.5.2... to `1.5.2-Forge_OF`
10. [Download](https://www.mediafire.com/folder/7z0wjbp7ga9ri/OptiFine_History) and **extract** OptiFine HD_U_D5.jar into a separate directory
11. Insert everything in the folder that you have extracted OptiFine HD_U_D5.jar to (the .class files and other stuff) directly into the .jar file `.minecraft/versions/1.5.2-Forge_OF/1.5.2-Forge_OF.jar`
12. Start the Minecraft version `1.5.2-Forge_OF`
- **make sure to read the guide thoroughly at least once before proceeding!**

**Comment by GaucovyAero** [comment]
your installation may fail due to an opengl check on the latest pojav version, im trying to talk this out with the devs

**Comment by GaucovyAero** [comment]
if you seriously have to get it running, grab this: https://www.mediafire.com/file/y2tbujxy3p5czi7/PojavLauncher_dahlia-41.apk/file

**Comment by Prostop194** [comment]
> хорошо, так что это сработало для меня в первый раз по какой-то причине, вот учебник:
> 
> 1. Установить Forge 1.5.2 
>    1.1. Установите MiX с сайта mixplorer.com
> 2. Возьмите Forge Patchpack из старого выпуска здесь, на github (вы можете найти его на последней странице, он все еще открыт)
> 3. Установите патч JSON
> 4. Запустите Forge 1.5.2 и посмотрите, работает ли он 
>    4.1. Если это все еще не работает, убедитесь, что вы загрузили файл .jar установщика Forge с помощью Firefox, а не Chrome.
> 5. Скопируйте и вставьте Forge 1.5.2 `.minecraft/versions`и назовите новую папку, например.`1.5.2-Forge_OF`
> 6. Измените имя **.jar** и **.json** в `1.5.2-Forge_OF`папке на `1.5.2-Forge_OF.jar`и`1.5.2-Forge_OF.json`
> 7. Откройте JSON с помощью текстового редактора MiX и измените `id`Forge-something на`1.5.2-Forge_OF`
> 8. Вставьте OptiFine HD_U_D5 непосредственно в`1.5.2-Forge_OF.jar`
> 9. Запустить версию МС`1.5.2-Forge_OF`
> 
> * **обязательно внимательно прочитайте руководство хотя бы один раз, прежде чем продолжить!**

very difficult and incomprehensible trying to understand

**Comment by GaucovyAero** [comment]
im trying to work with a translator to somehow make it easier to translate gimme a few minutes

**Comment by GaucovyAero** [comment]
uhm, i also forgot a lot of stuff that i have to add into the guide

**Comment by Prostop194** [comment]
надо содержимое оптифайна распоковать в 1.5.2-Forge_OF.jar

**Comment by Prostop194** [comment]
you need to unpack the contents of optifine in 1.5.2-Forge_OF.jar

**Comment by GaucovyAero** [comment]
> you need to unpack the contents of optifine in 1.5.2-Forge_OF.jar

okay, guide is done, use the [DeepL](https://www.deepl.com/translator) translator do translate the guide

**Comment by GaucovyAero** [comment]
> Do I need to extract the contents of Optifine in 1.5.2-Forge_OF?

yep

**Comment by Prostop194** [comment]
![Screenshot_20230128_014606_MiXplorer](https://user-images.githubusercontent.com/121510853/215183607-4ddf6da2-95e6-49a0-8bae-0a1ae0ced51a.jpg)
why

**Comment by GaucovyAero** [comment]
uhm, you don't need to add anything, no idea what are you doing

**Comment by GaucovyAero** [comment]
can you at least tell me which step did you get lost at?

**Comment by Prostop194** [comment]
> можешь хотя бы сказать мне, на каком этапе ты заблудился?

10

**Comment by GaucovyAero** [comment]
> > можешь хотя бы сказать мне, на каком этапе ты заблудился?
> 
> 10

just go into the pojav directory, then .minecraft/versions/1.5.2-Forge_OF/, then click on 1.5.2-Forge_OF.jar to open it and paste the .class files and other stuff

**Comment by Prostop194** [comment]
![Screenshot_20230128_020830_MiXplorer](https://user-images.githubusercontent.com/121510853/215187332-22509c13-a66f-49af-8f2d-c026bbc585e8.jpg)
bottom error

**Comment by Prostop194** [comment]
my files from optifine are not unpacked in 1.5.2-Forge_OF.jar

**Comment by GaucovyAero** [comment]
> my files from optifine are not unpacked in 1.5.2-Forge_OF.jar

thats fine, you just have to but the optifine files in the forge optifine jar

**Comment by Prostop194** [comment]
where is forge optifine.jar

**Comment by GaucovyAero** [comment]
> where is forge optifine.jar

forge optifine .jar is `.minecraft/versions/1.5.2-Forge_OF/1.5.2-Forge_OF.jar`

**Comment by Prostop194** [comment]
> ![Screenshot_20230128_020830_MiXplorer](https://user-images.githubusercontent.com/121510853/215187332-22509c13-a66f-49af-8f2d-c026bbc585e8.jpg) нижняя ошибка

I wanted to unpack Optifine again, but again it's a mistake to fix it

**Comment by GaucovyAero** [comment]
1. extract the `OptiFine_HD_U_G5.jar` in for example `/storage/emulated/0/Downloads/OptiFine_HD_U_G5/`
2. go into `/storage/emulated/0/Downloads/OptiFine_HD_U_G5/` and select EVERYTHING and click copy
3. go into `.minecraft/versions/1.5.2-Forge_OF/1.5.2-Forge_OF.jar` and click paste
4. start up Minecraft

**Comment by Prostop194** [comment]
I have this error again. I copy files from optifine for hoshu in 1.5.2-Forge_OF.jar, press paste and it doesn't install

**Comment by GaucovyAero** [comment]
ima try doing it myself gimme a few minutes

**Comment by Prostop194** [comment]
okay

**Comment by GaucovyAero** [comment]
https://user-images.githubusercontent.com/85581164/215267586-f96c5b9f-438b-407e-aafa-61c4726af50e.mp4
its crashing on my galaxy s7 edge, but this is how you do it, works on my poco f3 tho

**Comment by Prostop194** [comment]
![Screenshot_20230128_203206_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/121510853/215272242-2fc0a6ed-4227-4d2c-86e0-bdccdc03c942.jpg)
I did everything as in the video, I logged in and I have an endless download

**Comment by GaucovyAero** [comment]
> ![Screenshot_20230128_203206_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/121510853/215272242-2fc0a6ed-4227-4d2c-86e0-bdccdc03c942.jpg) I did everything as in the video, I logged in and I have an endless download

yeah, no idea how to fix this

**Comment by GaucovyAero** [comment]
works on some phones, on some it doesnt, dont use optifine with forge then, so either use just forge or just optifine

**Comment by Prostop194** [comment]
OK(

**Comment by GaucovyAero** [comment]
> OK(

can you also tell me whats your phone?

**Comment by Prostop194** [comment]
Samsung Galaxy A52

**Comment by GaucovyAero** [comment]
> Samsung Galaxy A52

hmm ok

**Comment by Prostop194** [comment]
> > Самсунг Галакси А52
> 
> Хмм хорошо

so I won't be able to play forge with optifine

**Comment by GaucovyAero** [comment]
> > > Самсунг Галакси А52
> > 
> > 
> > Хмм хорошо
> 
> so I won't be able to play forge with optifine

yep probably not

**Comment by Prostop194** [comment]
What do we do

**Comment by Prostop194** [comment]
> > > > Самсунг Галакси А52
> > > 
> > > 
> > > Хмм хорошо
> > 
> > 
> > поэтому я не смогу играть в кузницу с оптифайном
> 
> да наверное нет

what we are going to do

**Comment by GaucovyAero** [comment]
nothing yet

**Comment by Prostop194** [comment]
> пока ничего

let's wait for someone to help us

**Comment by Brunight** [comment]
You guys are extracting Optifine into the wrong jar, and there's no need to duplicate your Profile
Thar jar you should paste the Optifine files is `.minecraft/libraries/net/minecraftforge/minecraftforge/7.8.1.738/minecraftforge-7.8.1.738.jar`
Be sure to backup this file in case something goes wrong
That's all, this will work for any other mod that you would normally install by pasting files into minecraft.jar/modpack.jar
As this is not a bug on Pojav's side, this issue should be closed

**Comment by Prostop194** [comment]
more

**Comment by Prostop194** [comment]
wow thank you i was able to run optifine_HD_U_D5

**Comment by Prostop194** [comment]
on version forge 1.5.2

**Comment by Prostop194** [comment]
if you want you can close the question

**Comment by GaucovyAero** [comment]
> if you want you can close the question

yeah cool, how did you do it? did you put the optifine stuff into the minecraftforge jar just like the guy said?

**Comment by Prostop194** [comment]
> > если хотите можете закрыть вопрос
> 
> да круто, как ты это сделал? ты положил оптифайн в банку minecraftforge, как сказал парень?

yes i did as he said

**Comment by GaucovyAero** [comment]
> > > если хотите можете закрыть вопрос
> > 
> > 
> > да круто, как ты это сделал? ты положил оптифайн в банку minecraftforge, как сказал парень?
> 
> yes i did as he said

okay ima try that later
