### ISSUE TITLE
[F-Req] replace file manager app again 

### ISSUE THREAD

**Issue by lehoanduphong** [PojavLauncherTeam/PojavLauncher#3884]
### Is this request related to a bug?

in the new update (  #4138 ) was able Implement file/folder opening along with link opening #4138
but it has the problem that the device's native file manager doesn't transfer files to the app 

https://user-images.githubusercontent.com/103303530/215239951-42b292b3-4079-469b-bb12-ad097ff0d2c7.mp4
![Screenshot_20230128-103450_Files](https://user-images.githubusercontent.com/103303530/215240086-97afdb04-dfa7-4be6-aa36-3cb7c028ed09.png)

i think it would be better to use zachiver's file manager 
or some other file management application also 

### Anything else?

nothing left

**Comment by Julienraptor01** [comment]
It does allow you if you don't go through the app shortcut and instead take the full path from name of the phone -> Android -> data -> net.kdt.pojavlaunch -> files

**Comment by lehoanduphong** [comment]
> It does allow you if you don't go through the app shortcut and instead take the full path from name of the phone -> Android -> data -> net.kdt.pojavlaunch -> files

I just want to install the data pack directly while creating the map, like when I click on it, the phone's default file manager automatically unzips the zip file, so I can't install the data pack directly. next

**Comment by GaucovyAero** [comment]
> > It does allow you if you don't go through the app shortcut and instead take the full path from name of the phone -> Android -> data -> net.kdt.pojavlaunch -> files
> 
> I just want to install the data pack directly while creating the map, like when I click on it, the phone's default file manager automatically unzips the zip file, so I can't install the data pack directly. next

use MiX from mixplorer.com

**Comment by lehoanduphong** [comment]
> > > It does allow you if you don't go through the app shortcut and instead take the full path from name of the phone -> Android -> data -> net.kdt.pojavlaunch -> files
> > 
> > 
> > I just want to install the data pack directly while creating the map, like when I click on it, the phone's default file manager automatically unzips the zip file, so I can't install the data pack directly. next
> 
> use MiX from mixplorer.com

I need guidance

**Comment by GaucovyAero** [comment]
just install MiX, it's a file manager, you will be able to access the directory from it

**Comment by lehoanduphong** [comment]
> > > It does allow you if you don't go through the app shortcut and instead take the full path from name of the phone -> Android -> data -> net.kdt.pojavlaunch -> files
> > 
> > 
> > I just want to install the data pack directly while creating the map, like when I click on it, the phone's default file manager automatically unzips the zip file, so I can't install the data pack directly. next
> 
> use MiX from mixplorer.com

It can replace the original firmware of the device

**Comment by GaucovyAero** [comment]
it cannot

**Comment by GaucovyAero** [comment]
resolved
