### ISSUE TITLE
Keyboard not showing

### ISSUE THREAD

**Issue by KamuNanyaaa** [PojavLauncherTeam/PojavLauncher#3887]
### Describe the bug

https://user-images.githubusercontent.com/122107374/215316690-295b4368-d794-4bd9-a319-f640cb83cba1.mp4

the keyboard can't appear even though it's been clicked several times it still can't.

Even though my keyboard has been updated to the latest version 

Please help :)

### The log file and images/videos

None

### Steps To Reproduce

```markdown
None
```

### Expected Behavior

I hope that the keyboard can appear again

### Platform

```markdown
- Device model: Oppo A95 8/256G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: [ latest release || Dahlia-236-1f28b3a6a-v3_openjdk ]
```

**Comment by Mathias-Boulay** [comment]
Do you have any physical input connected to your device ?

**Comment by KamuNanyaaa** [comment]
No I did not connect any physical devices

**Comment by KamuNanyaaa** [comment]
For the keyboard I use the latest version of Gboard

**Comment by GaucovyAero** [comment]
we cant reproduce this, i think you have broke something, make sure your controlmap is set to default.json, and try using a different keyboard, for example simple keyboard, etc.

**Comment by KindaWeird123** [comment]
well the latest version is bugged. try older ones

**Comment by Heima945** [comment]
I met the same problem.You can use the previous version.

**Comment by yagnik1akbari** [comment]
Pls give update to fix keyboy

**Comment by Mathias-Boulay** [comment]
Fixed now

**Comment by KamuNanyaaa** [comment]
can you provide the fixed pojavlauncher link

**Comment by GaucovyAero** [comment]
> can you provide the fixed pojavlauncher link

https://github.com/PojavLauncherTeam/PojavLauncher/suites/10738702062/artifacts/538657417

**Comment by GaucovyAero** [comment]
the fix is also on play store tho
