### ISSUE TITLE
[F-Req] [Custom Controls] Conditions for button visiblity

### ISSUE THREAD

**Issue by Felix14-v2** [PojavLauncherTeam/PojavLauncher#3889]
### Introduction

Hello again! I'm trying to make the most versatile, and at the same time convenient controls. PojavLauncher gives good controls customization options, but now there is one very needed missed feature — the ability to display certain buttons only ingame when any types of UI (chat, settings menu or title screen) aren't opened. PojavLauncher already can detect this — the mouse cursor is displayed only when you can't control the camera. 
The problem is the "wasd", "space", "shift", and some other buttons are bothering you in the title screen, pause menu or opened chat (buttons usually largely overlaps the chat);
And vise versa, the text management buttons (arrows, backspace, ctrl+a/c/v/etc) aren't needed ingame, they can only be useful in chat and some UI (anvil, book, mod settings screens — wherever there are text input fields).

### Suggestion

So, I suggest adding new `Display conditions` switches under the `toggleable`,  `mouse pass` and `swipeable`options for each button/drawer:
- `Ingame` (displayed when your character can move, should be enabled by default)
- `Input fields` (will be shown only when you can enter text)
- `Title screen` (displayed in the main menu and in the list of worlds/servers)
- `Settings screens` (displayed in the pause menu, settings and other screens from the mods)

I guess technically it may not be possible to implement without modifying Minecraft. However, adding at least one `display in opened UI` setting (what the mouse cursor is currently using) already means a huge breakthrough in improving the user experience.

### Anything else?

Of course, I know about drawers, and I actively use them. But drawer has some flaws, such as the inability to adjust the size of each individual button, and it would be incredibly convenient for the buttons to switch their visibility depending on the condition(s).

**Comment by Heima945** [comment]
Great advice.

**Comment by artdeell** [comment]
only the first one is possible, but if you want to write a HID mod then we can expose necessary APIs to do this

**Comment by Felix14-v2** [comment]
Theoretically, it is also possible to check certain entries in the log — it is reflected there when player loads or leaves the world. This will allow you to implement buttons that work only inside the world.

**Comment by artdeell** [comment]
Log checking is not reliable and will not work across all MC versions

**Comment by Felix14-v2** [comment]
Reliable or not, in HMCL-PE, this was implemented somehow, and worked well. So I'm sure there is a way

**Comment by artdeell** [comment]
Worked well on a set if versions. Yeah, it will work on 1.12.2, but will it
work on Beta 1.7.3?
On Infdev?

сб, 4 мар. 2023 г., 11:07 Felix14-v2 ***@***.***>:

**Comment by Felix14-v2** [comment]
> will it work on Beta 1.7.3?

Just tried — yes, works fine. HMCL-PE has an extremely advanced controls system, I would even call it ideal. There is only one drawback — the lack of custom variables, but they are not enough in PojavLauncher too

**Comment by Mathias-Boulay** [comment]
Conditional visibility based on grab state has been done.
Given we won't modify the client, this is as far as we will go.
