### ISSUE TITLE
launcher crashes after starting up in tablet [BUG] 

### ISSUE THREAD

**Issue by brucekikkert** [PojavLauncherTeam/PojavLauncher#389]
**Describe the bug**
it crashes after start up i think it has to do with my android version
installed it correctly works well on my phone no crash log or event log given after crash

**To Reproduce**
1. Start PojavLauncher on a device with android version 7.1.1
2. set up the launcher
3. download a version doesnt matter which one.
4. start game
...

**Expected behavior**
I expected no problems but it only gives problems with any crash log or event log

**Screenshots**
dont have any right now
**Platform:**
 - Device Model samsung tab A
 - CPU architecture  aarch32
 - Android Version 7.1.1

maybe be a better crash log system would be nice 

with kind regards Bruce Kikkert

**Comment by WesleyVanNeck** [comment]
give latestlog.txt or we cant fix it

**Comment by brucekikkert** [comment]
man i didnt get one what about i didnt get a log you dont understand,
refactor your code because it works like sh*t i dont even got a log
and still you ask for one READ BEFORE THINKING OR ANSWERING

**Comment by khanhduytran0** [comment]
Enable **hidden folder** before say that.

**Comment by brucekikkert** [comment]
i did wanka i followed every instruction i did on my phone because it works on my phone

________________________________
Van: Tran Khanh Duy <notifications@github.com>
Verzonden: maandag 16 november 2020 23:05
Aan: PojavLauncherTeam/PojavLauncher <PojavLauncher@noreply.github.com>
CC: Student Bruce Kikkert <bkikkert7064@student.landstede.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [PojavLauncherTeam/PojavLauncher] launcher crashes after starting up in tablet [BUG] (#389)


Enable hidden folder before say that.
