### ISSUE TITLE
[BUG] Android 12 and 13

### ISSUE THREAD

**Issue by Yjs0987** [PojavLauncherTeam/PojavLauncher#3890]
### Describe the bug

When trying to run forge on Android 12 and 13, the system path to put the mod (games-pojavlauncher-.minecraft) does not exist

### The log file and images/videos

![20230131_084451](https://user-images.githubusercontent.com/124005679/215622248-6c619e88-fb8d-44ba-ba53-934d55c32ac5.jpg)

### Steps To Reproduce

```markdown
Run pojavlauncher with Android 12 and 13.
```

### Expected Behavior

The game works fine, but I can't install mods (e.g. jenny mod)

### Platform

```markdown
- Device model: samsung galaxy tab s6 lite(SM-P610)
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-1f28b3a6a-v3_openjdk
```

**Comment by mchnjt** [comment]
Game paths for A10^ has been changed. Try putting it on `.../Android/data/net.kdt.pojavlaunch*/files/.Minecraft/mods`

**Comment by GaucovyAero** [comment]
resolved, closing
