### ISSUE TITLE
Valkyrie skies physics not working 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3892]
### Describe the bug

![Screenshot_20230201-000610](https://user-images.githubusercontent.com/76839710/215820703-dbbea261-02b5-44a0-91b1-300cedb30053.png)
When I try to assembly physics not working 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10548692/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the game
2. Build balloon
3. Physics not change
```

### Expected Behavior

Working with physics 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Plss help

**Comment by GaucovyAero** [comment]
this feature does not work on android, likely requires physx, pojav cant fix this
