### ISSUE TITLE
[BUG] <long press does not work>

### ISSUE THREAD

**Issue by kzubec** [PojavLauncherTeam/PojavLauncher#3893]
### Describe the bug

When make long-press the scrollbar and move the cursor nothing happens

### The log file and images/videos

https://user-images.githubusercontent.com/77785957/215842248-4d7eed78-fc85-465b-902e-7ea0c13dd0b6.mp4

### Steps To Reproduce

```markdown
- Start PojavLauncher
- Run any version of Minecraft
- Open the inventory menu
- Make a long press on the scroll bar and swipe down
```

### Expected Behavior

I expected a long press to work

### Platform

```markdown
- Device model: Redmi 8A Olivelite (mi439)
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: dahlia-236-1f28b3a6a-v3_openjdk
```

**Comment by GaucovyAero** [comment]
![image](https://user-images.githubusercontent.com/85581164/215843437-fdd67e3d-b591-4475-80ea-141ba65c94e7.png)
look, your cursor is offset, this means you have "Ignore notch" disabled in the launcher settings

**Comment by kzubec** [comment]
> ![image](https://user-images.githubusercontent.com/85581164/215843437-fdd67e3d-b591-4475-80ea-141ba65c94e7.png) look, your cursor is offset, this means you have "Ignore notch" disabled in the launcher settings

there is no such thing here
![Screenshot_20230131-232354](https://user-images.githubusercontent.com/77785957/215874863-59045397-3e38-4e40-a61d-7a0c1e8f3ee5.png)
![Screenshot_20230131-232405](https://user-images.githubusercontent.com/77785957/215874878-5f64a81e-32ca-4b1e-bc9f-652d40ad5eca.png)
![Screenshot_20230131-232413](https://user-images.githubusercontent.com/77785957/215874883-e7d5fe7d-5aed-4a9d-93c6-6d735eba75e6.png)
![Screenshot_20230131-232418](https://user-images.githubusercontent.com/77785957/215874890-d11e53d5-8486-49a9-80da-31ebd3f3187c.png)
![Screenshot_20230131-232422](https://user-images.githubusercontent.com/77785957/215874895-f61b338e-2f97-42f7-873c-7f6132e0dfb9.png)

**Comment by GaucovyAero** [comment]
![image](https://user-images.githubusercontent.com/85581164/216110495-72557ec7-1167-42dd-9ad6-facc3a294685.png)
its this, just enable it

**Comment by kzubec** [comment]
> ![image](https://user-images.githubusercontent.com/85581164/216110495-72557ec7-1167-42dd-9ad6-facc3a294685.png) its this, just enable it

It didn't help.
It turns out only with the left mouse button pressed

**Comment by GaucovyAero** [comment]
use the PRI (SPECIAL_PRI) button in your controlmap instead
