### ISSUE TITLE
[F-Req] <Add the option to start gl4es1.1.5.>

### ISSUE THREAD

**Issue by Heima945** [PojavLauncherTeam/PojavLauncher#3894]
### Is this request related to a bug?

When I use 1.16.xfabric, the holy renderer chooses gl4es1.1.4, but sodium0.2.0 needs gl4es1.1.5 to work properly.（My device doesn't support angle renderer, and the effect of vgpu renderer is too poor.）

### Describe the request.

As before version, please add an option of gl4es1.1.5 to the renderer.
thanks.

**Comment by GaucovyAero** [comment]
optifine is still faster than sodium on pojav, if you need sodium, use 0.1.0

**Comment by Heima945** [comment]
I'm using 0.1.0, but it doesn't render fog properly.And optifine was banned in speedrun.So i need gl4es1.1.5

**Comment by mchnjt** [comment]
wh

**Comment by mchnjt** [comment]
why speedrunning

**Comment by Heima945** [comment]
@revoscode Do you mean I can't do that-_-？

**Comment by GaucovyAero** [comment]
> @revoscode Do you mean I can't do that-_-？

i recommend speedrunning on a different version then, just use anything below or anything newer

**Comment by Heima945** [comment]
okay
