### ISSUE TITLE
[BUG] The keyboard cannot be summoned

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#3895]
### Describe the bug

In one beta, the keyboard could not be summoned in-game, which was a big obstacle for me to type and log in

### The log file and images/videos

https://user-images.githubusercontent.com/100058929/215940193-ed888b1d-a6dd-418f-9c6f-db02061f2a01.mp4

### Steps To Reproduce

```markdown
no
```

### Expected Behavior

I hope this bug is fixed

### Platform

```markdown
- Device model: ART-AL00m 4/128G
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: Feature: OldVersionsUtils now handles dates without T correctly
```

### Anything else?

I believe that the official will definitely fix this bug

**Comment by NOfelll** [comment]
Me too

**Comment by yagnik1akbari** [comment]
Me too

**Comment by Heima945** [comment]
用之前几天的版本 等pojav更新就好了

**Comment by GaucovyAero** [comment]
duplicate issue, closing
