### ISSUE TITLE
Valkyrie skies mod not working 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3896]
### Describe the bug

When try use Valkyrie block saying need arch64
![Screenshot_20230201-000610](https://user-images.githubusercontent.com/76839710/215942099-7b0b7397-5e28-4266-9cc3-ce9d2760ffe0.png)

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Start the game
2. Create a world
3. Play showing not working
```

### Expected Behavior

Working 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: on latest GitHub
```

### Anything else?

Plss help

**Comment by kedrick021** [comment]
Working on iOS not android

**Comment by GaucovyAero** [comment]
> Working on iOS not android

i suggest you send latestlog.txt

**Comment by Mathias-Boulay** [comment]
#1948
