### ISSUE TITLE
[BUG] <The. jar tool cannot be used normally.>

### ISSUE THREAD

**Issue by Heima945** [PojavLauncherTeam/PojavLauncher#3897]
### Describe the bug

I tried to use installer.jar option to use ninjarbrainbot,but I can't use it normally.
Like in the video, I need to enter the game and use "f3 and C" to use this tool, but I can't do this in the installer.jar option.I tried to start the game, but the installer crashed.

### The log file and images/videos

https://user-images.githubusercontent.com/80663974/215998977-af80bc6a-2f82-493a-9348-396e6c97014a.mp4

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Click the install. jar option.
3.Select .jar tool
（ninjarbrainbot）
4.I tried to open the game, but the installer crashed
```

### Expected Behavior

I hope to start the. jar file to use the tool while the game is running.

### Platform

```markdown
- Device model: HUAWEI Honor
5C
- CPU architecture: aarch64
- Android version: 7
- PojavLauncher version: dahlia-213-0a329af8e-v3_openjdk
```

**Comment by Baobuchi** [comment]
兄弟,我觉得吧你应该去新特性那里写这些,pojavlauncher主攻Minecraft,也没在意这些,这就是我的理由

**Comment by Heima945** [comment]
@Baobuchi  随便发出来看看有没可能解决的 实质上也不抱多大希望

**Comment by Heima945** [comment]
@Baobuchi 实质上有关系
ninjarbrainbot是要塞坐标计算器 speedrun方面的

**Comment by Heima945** [comment]
@Baobuchi 实质上有关系
ninjarbrainbot是要塞坐标计算器 speedrun方面的

**Comment by Proplayer001** [comment]
Não consigo entrar na minha conta da Microsoft no pojavlauncher, eu já tinha essa conta a muito tempo inclusive tá ligada no site do Minecraft.net, fica dando erro Unauthorized

**Comment by GaucovyAero** [comment]
and thats a no.
