### ISSUE TITLE
[BUG] nao consigo entrar na conta Microsoft do pojavlauncher 

### ISSUE THREAD

**Issue by Proplayer001** [PojavLauncherTeam/PojavLauncher#3898]
### Describe the bug

Não consigo entrar na minha conta da Microsoft no pojavlauncher, eu já tinha essa conta a muito tempo inclusive tá ligada no site do Minecraft.net, fica dando erro Unauthorized preciso de ajuda.

### The log file and images/videos

![Screenshot_20230201_105133_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103421694/216067202-ea7fbf48-0875-492d-8da8-06064b0e4078.jpg)

### Steps To Reproduce

```markdown
1 Entrei no pojavlauncher 
2 fui para colocar uma conta da Microsoft 
3 coloquei a conta e deu erro Unauthorized
```

### Expected Behavior

Tomara que eles resolva esse bug

### Platform

```markdown
- Device model: galaxy m53 5g 
- CPU architecture: dimensity 900
- Android version: 13
- PojavLauncher version: mais recente
```

### Anything else?

Me ajuda por favor

**Comment by GaucovyAero** [comment]
duplicate issue, closing
