### ISSUE TITLE
[BUG] I can't login to Microsoft account from pojavlauncher

### ISSUE THREAD

**Issue by Proplayer001** [PojavLauncherTeam/PojavLauncher#3899]
### Describe the bug

I can't log into my Microsoft account on pojavlauncher, I already had this account for a long time, it's even connected to the Minecraft.net website, it keeps giving an Unauthorized error

### The log file and images/videos

![Screenshot_20230201_105133_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103421694/216068407-84737ee4-6658-432f-b704-a910c52c63e8.jpg)

### Steps To Reproduce

```markdown
I entered the pojavlauncher went to put a microsoft account I put the account and it gave Unauthorized error
```

### Expected Behavior

I hope they fix this bug

### Platform

```markdown
- Device model: galaxy m53 5g 
- CPU architecture: dimensity 900
- Android version: 13
- PojavLauncher version: last
```

### Anything else?

Help me please

**Comment by qaq1000w** [comment]
Landing  https://www.minecraft.net

**Comment by GaucovyAero** [comment]
yeah, try logging into minecraft.net first, this isnt our issue

**Comment by Proplayer001** [comment]
> sim, tente entrar no minecraft.net primeiro, este não é o nosso problema
R- eu já fiz isso mais continua com o mesmo erro :(

**Comment by GaucovyAero** [comment]
> > sim, tente entrar no minecraft.net primeiro, este não é o nosso problema
> > R- eu já fiz isso mais continua com o mesmo erro :(

try setting your birth of date earlier so that you are 25+ years old on the microsoft account

**Comment by Proplayer001** [comment]
> try setting your birth of date earlier so that you are 25+ years old on the microsoft account

I'm going to test it here and I'll talk :)

**Comment by EmeenPro123** [comment]
> 

If it's a Minecraft bedrock account it won't work it needs to be a java account not. Bedrock account

**Comment by DarkOutfi** [comment]
I complain about your game because I was making a microsorft account using your app and when I started it doesn't work my microsroft account and my friend's account work I wanted to know why it doesn't work on mine

**Comment by NotMoiz** [comment]
Cant login from Github and Microsoft on pojavlauncher pls fix this bug i have phone samsung galaxy a51

**Comment by brxay123** [comment]
i cant login am already sigin but icant

**Comment by AiyanShari** [comment]
I need this account to pojavlauncher.

**Comment by Montivillon** [comment]
wait, meaning that you need a java account by signing in on the computer in java edition then logging to the same account on pojav right @EmeenPro123 ?

**Comment by qaq1000w** [comment]
> 等等，这意味着您需要一个java帐户，方法是在java版本的计算机上登录，然后在pojav上登录到相同的帐户@EmeenPro123？

You need a Java Minecraft account, log in to https://www.minecraft.net on your mobile phone

需要java我的世界帐号，在手机上登录https://www.minecraft.net

**Comment by Montivillon** [comment]
It says it’s a demo account in Pojav

**Comment by Montivillon** [comment]
Cause I’m on iOS  which makes me play demo world and not servers or infinite world time.

**Comment by Aliak338** [comment]
I can't login but I have Microsoft Xbox normal account ![Screenshot_20240504-204728_PojavLauncher (Minecraft Java Edition for Android).png](https://github.com/PojavLauncherTeam/PojavLauncher/assets/162154719/353205c9-e3ca-477e-8a62-74698c11f7b3)

**Comment by GaucovyAero** [comment]
> I can't login but I have Microsoft Xbox normal account ![Screenshot_20240504-204728_PojavLauncher (Minecraft Java Edition for Android).png](https://private-user-images.githubusercontent.com/162154719/327964503-353205c9-e3ca-477e-8a62-74698c11f7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTY0OTAsIm5iZiI6MTcxNDg1NjE5MCwicGF0aCI6Ii8xNjIxNTQ3MTkvMzI3OTY0NTAzLTM1MzIwNWM5LWUzY2EtNDc3ZS04YTYyLTc0Njk4YzExZjdiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMDU2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZThkY2FkYjQ0MGUzYWJhNGU1ZDIwODIyNDM1OWMxZTQ3NDkwNTA0MWFkY2NkZjZlYjVkZDE4NzQ0ZmMwYWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QxwtjMkh_XKatpe6qs-iYWfl50cS59cwcykooZOv2sk)

try using a different internet connection and log into minecraft.net on your browser first

**Comment by Aliak338** [comment]
But Microsoft services is unvisited in my country (iran)

**Comment by kasrarouhi** [comment]
> But Microsoft services is unvisited in my country (iran)

Me too

**Comment by Odmar264** [comment]
![Image](https://github.com/user-attachments/assets/87d3986d-c122-40d7-9729-167eb71c4a41)a mi me aparece esto

**Comment by ayushkansai** [comment]
java.lang.RuntimeException: {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by ayushkansai** [comment]
#2349

**Comment by ayushkansai** [comment]
#2349

**Comment by ayushkansai** [comment]
#2349

**Comment by ayushkansai** [comment]
#2349java.lang.RuntimeException: {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by blryface** [comment]
what in the world
