### ISSUE TITLE
[BUG] alpha version don't work

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#390]
![Screenshot_2020-11-10-02-49-05-025_net kdt pojavlaunch](https://user-images.githubusercontent.com/74020022/98609904-76332400-22ff-11eb-9b7e-739162818f0e.jpg)
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
play release version of minecraft or use v2 also without logs we cant do anyting
