### ISSUE TITLE
[BUG] Trying to install forge or optifine .jar crashes.

### ISSUE THREAD

**Issue by Shadow00x7** [PojavLauncherTeam/PojavLauncher#3901]
### Describe the bug

When ever i try to install forge or optifine installer, the launcher or whatever crashes. I am on 1.19.3, and the vanilla game runs fine. 

### The log file and images/videos

[latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10559870/latestlog.1.txt)

### Steps To Reproduce

```markdown
1. Click on the .jar installer
2. Select the desired .jar you want to install
```

### Expected Behavior

Expect to start the installer and install it.

### Platform

```markdown
- Device model: Samsung Galaxy M21/128G (SM-M215F)
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: dahlia-256-1f28b3a6a-v3_openjdk
```

### Anything else?

I have vanila 1.19.3, which has no issues at all

**Comment by Heima945** [comment]
Try starting the installer using java8.

**Comment by GaucovyAero** [comment]
1. always use java 8 for the jar installer unless explicitly told to use java 17
2. rotate your phone into landscape mode

**Comment by GaucovyAero** [comment]
closed as this is a duplicate
