### ISSUE TITLE
THIS MODS ARE NOT WORKING 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3905]
### Describe the bug

![Screenshot_20230202-084838](https://user-images.githubusercontent.com/76839710/216239289-af0c1a00-175b-4ecf-98b5-cde110163942.png)

When I try use this mod they say arch64 need 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10565162/latestlog.txt)

Here logs I 

### Steps To Reproduce

```markdown
1. Valkyrie skies mod 
2. Start the game
2. Create world
3. Use mod not working
```

### Expected Behavior

Working  Valkyrie skies mod 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Plss help am using Valkyrie skies mod

**Comment by mchnjt** [comment]
You, uh, why do you need to scream

**Comment by kedrick021** [comment]
> You, uh, why do you need to scream

?

**Comment by Heima945** [comment]
#3896 ？

**Comment by Mathias-Boulay** [comment]
#1948 thanks.

**Comment by kedrick021** [comment]
> #1948 thanks.

Complete how to fix this?
