### ISSUE TITLE
[BUG] Fix Full-screen

### ISSUE THREAD

**Issue by Gadet-0** [PojavLauncherTeam/PojavLauncher#3906]
### Describe the bug

> So this error was also reported before by me, but it was closed, and no fix was implemented so, here i m again opening this issue, please fix it!

Please See the Video Recording To Understand Better, the full screen thing dosent allow me to type Capital "W" ("W")

**NOTE**: CHANGING FULL-SCREEN KEY DOSENT FIXES THE ISSUE

### The log file and images/videos

No Logs Required
Please just see the recording

https://user-images.githubusercontent.com/114248972/216240656-10e4d48f-754a-4eed-a8f6-27230683a804.mp4

### Steps To Reproduce

```markdown
1: Start Pojav (1.8.9)
2: Go into any world
3: Open Chat And Keyboard
4: Type "W"
```

### Expected Behavior

It was expected to type "W" and full screen should have been normal, but it dosent. Changing The FULL-SCREEN KEY DOSENT FIXES THE ISSUE IT REMAINS THE SAME

### Platform

```markdown
- Device model: Redmi note 7 pro
- CPU architecture: Aarch64 processor rev 14 (aarch64)
- Android version: 10 (QKQ1.190915.002)
- PojavLauncher version: Latest G-Play Release
```

### Anything else?

please fix it 😫

**Comment by mchnjt** [comment]
W is **NOT** the full-screen keybind. It's F11. W is walking forward.

**Comment by Heima945** [comment]
Try to use the latest beta version pojav.I have encountered this problem before.

**Comment by Mathias-Boulay** [comment]
F11 is the key you're looking for

**Comment by Gadet-0** [comment]
> W is **NOT** the full-screen keybind. It's F11. W is walking forward.

you dont understand, i have default keybinds, nothing changed, but still if i type "W" the above thing happens
