### ISSUE TITLE
[BUG] I can't login my Microsoft account in pojavlauncher

### ISSUE THREAD

**Issue by Proplayer001** [PojavLauncherTeam/PojavLauncher#3908]
### Describe the bug

I'm not able to log in to my account, it keeps giving an error saying that my account is not logged into the xbox, and I've been trying to log in for a long time and it always gives an error.

### The log file and images/videos

![Screenshot_20230201_211317_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103421694/216332095-abc07f93-9352-4351-b93b-9e7b3dc573f6.jpg)

![Screenshot_20230202_095849_Xbox](https://user-images.githubusercontent.com/103421694/216332112-2a67d3f9-fde5-4f3f-bfa6-694150001c42.jpg)

### Steps To Reproduce

```markdown
I entered the pojavlauncher I went to log into my Microsoft account and it gave my account error again.
```

### Expected Behavior

Espero que eles resolva esse bug.

### Platform

```markdown
- Device model:samsung m53 5g
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: lançamento mais recente
```

### Anything else?

Help me please

**Comment by GaucovyAero** [comment]
bruh just do what it says you to do, log into minecraft.net

**Comment by Proplayer001** [comment]
> bruh just do what it says you to do, log into minecraft.net

I already did that and it keeps giving me the same error.

**Comment by GaucovyAero** [comment]
have you bought minecraft java edition?

**Comment by Proplayer001** [comment]
> você comprou o minecraft java edition?

Sim

**Comment by GaucovyAero** [comment]
> > você comprou o minecraft java edition?
> 
> Sim

hm ok, no idea then
