### ISSUE TITLE
[F-Req] pre-launch commands

### ISSUE THREAD

**Issue by asdfghjkl403622** [PojavLauncherTeam/PojavLauncher#3909]
### Is this request related to a bug?

You should add pre-launch commands because it can be used to run utilities to keep modpacks up to date. Implementations like the one in prism launcher are incredibly useful for this purpose.

### Describe the request.

A text field that will allow you to enter a command to be used before startup. It should have parameters for relative pathing like for the java installation, instance directory, and maybe more?

### Anything else?

It could also be nice to add a during launch command, and a post launch command field as well.

**Comment by mchnjt** [comment]
Uh
![Screenshot_20230202_222410](https://user-images.githubusercontent.com/83752061/216350758-07908695-5b48-4038-92ec-79039101fefa.jpg)

**Comment by GaucovyAero** [comment]
pre-launch and post-launcher are a no for now

**Comment by asdfghjkl403622** [comment]
Those a jvm arguments

**Comment by asdfghjkl403622** [comment]
but yeah, that's alrighr
