### ISSUE TITLE
Нужно улучшения в элементах клавишах 

### ISSUE THREAD

**Issue by Tol561** [PojavLauncherTeam/PojavLauncher#391]
I need improvements in the controls. The thing is, I can't add the right key and use it. I can only do this through changes, but it's not convenient. You have to change all the time. Also, I can't swipe down the game and pick the world, server, items, etc. If I'm wrong. Then tell me how to do it. And so everything goes well

**Comment by WesleyVanNeck** [comment]
pri and sec are the mouse buttons

**Comment by WesleyVanNeck** [comment]
and scrolling isnt inplemented
