### ISSUE TITLE
[BUG] "Timed Out" 2 min after joining servers

### ISSUE THREAD

**Issue by xanning** [PojavLauncherTeam/PojavLauncher#3910]
### Describe the bug

[Note: my previous issue closed due to "completed" but they didnt even responded to me. Its so disrespectful you need to respond us and try to solve our problems.]

It kickes me out from servers like 3 minutes after i join with "Timed out" (I'm playing on cracked)
Idk why but i tired getting kicked out every 3 minute.
It not happening on my PC, just on pojavlauncher
Wifi is good, likely 100 ms etc.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10571795/latestlog.txt)

### Steps To Reproduce

```markdown
1) Starting pojav launcher
2) Entering minecraft 1.16.5 with 3GB ram
3) Going into any server
4) Getting kicked out with "timed out" after 3 minutes
```

### Expected Behavior

I except play normally

### Platform

```markdown
- Device model: Redmi Note 8 Pro 6 GB Ram
- CPU architecture: 8coremax 
- Android version: MIUI 11/ Android 9 PPR
- PojavLauncher version: Latest
```

### Anything else?

Stop. Its so disrespectful that closing issues without even replying them. My issue isnt solved and i still cannot play normally.

**Comment by GaucovyAero** [comment]
we cannot do anything about wifi, this is a miui issue i think

**Comment by xanning** [comment]
what is "miui issue"? This happens on my LG device also (I dont play on it but i downloaded for seeing am i getting same result or not)

**Comment by GaucovyAero** [comment]
that basically concludes its an issue with your wifi connection, as i said, pojav does not do ANYTHING about networking, therefore we cannot break it nor fix it
