### ISSUE TITLE
[BUG] wrong resolution

### ISSUE THREAD

**Issue by qaq1000w** [PojavLauncherTeam/PojavLauncher#3911]
### Describe the bug

wrong resolution
分辨率错误

### The log file and images/videos

![IMG_20230203_031014](https://user-images.githubusercontent.com/80654352/216429045-15e657b7-1baf-444f-9c78-f1847e337fad.jpg)
--
![IMG_20230203_031131](https://user-images.githubusercontent.com/80654352/216429129-becfbdfe-a936-4432-a45c-c5dee34bd5f1.jpg)
--
![IMG_20230203_031220](https://user-images.githubusercontent.com/80654352/216429192-8a304a19-76a3-47ab-a33a-cafa7ae7c551.jpg)

### Steps To Reproduce

```markdown
1:Open the multitasking interface
打开多任务界面
2:back to game
返回游戏
```

### Expected Behavior

![Uploading Screenshot_2023-02-03-03-05-48-568_net.kdt.pojavlaunch.debug.jpg…]()

### Platform

```markdown
Device model: redmi note 9
CPU architecture: aarch64
Android version: 11
PojavLauncher version: dahlia-250-27a3bb812-v3_openjdk
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
i dont think we can fix this but maybe yeah, its mostly just a miui issue

**Comment by Mathias-Boulay** [comment]
Weird...

**Comment by Mathias-Boulay** [comment]
Which miui version By the way ?

**Comment by qaq1000w** [comment]
MIUI  12.5.9

**Comment by qaq1000w** [comment]
> Which miui version By the way ?

Device model:  L70081
Zui13.5.380

**Comment by qaq1000w** [comment]
https://www.bilibili.com/video/av566447346

**Comment by qaq1000w** [comment]
dahlia-310-ed1870eec-v3_openjdk
9939075
