### ISSUE TITLE
Gyroscope invert left and right pls fix 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3912]
### Describe the bug

Invert left and right
Left is right
Right is left
Plss fix

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Create world
2. Use gyroscope
3. Invert left and right
```

### Expected Behavior

Working fine 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

PL

**Comment by mchnjt** [comment]
rotate. your. phone.

**Comment by kedrick021** [comment]
> rotate. your. phone.

I already do that and now up and down invert

**Comment by kedrick021** [comment]
Dev pls help

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
