### ISSUE TITLE
[BUG] so the 1.16 aprilfools version kinda wacky

### ISSUE THREAD

**Issue by blob83** [PojavLauncherTeam/PojavLauncher#3913]
### Describe the bug

Some rendering bugs

### The log file and images/videos

![Screenshot_20230203-181159_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98200395/216574237-51d9f315-dacb-4393-8d43-ed39a9e0e3cd.jpg)
So yeah

### Steps To Reproduce

```markdown
1.just start the 1.16 infinite version
2.load world.
3.rendering bugs
```

### Expected Behavior

I expect working fine because i played the infinite version in the old days and it was fine

### Platform

```markdown
- Device model: A11
- CPU architecture: 32 bit
- Android version: 11
- PojavLauncher version: idk
```

**Comment by Baobuchi** [comment]
Bro, I've also come across, it's strange where this rendering error comes from?

**Comment by GaucovyAero** [comment]
press f11
