### ISSUE TITLE
[BUG] gui bug white.

### ISSUE THREAD

**Issue by justinsanjp** [PojavLauncherTeam/PojavLauncher#3917]
### Describe the bug

No matter where I look except down on the floor, the GUI and blocks are bogged down like items. 
We use Minecraft Forge 1.7.10
With the following mods:
ImmersiveEngineering
ImmersiveRailroading
OpenComputers
TrackAPI
UniversalModCore
WorldEdit
And last but not least Optifine (it doesn't matter if optifine is in the mods folder or not, the bug remains).

Even without mods in all versions up to 1.16.1 I have this bug.

### The log file and images/videos

[Video on YouTube](https://youtu.be/oqRvrVP7GJ4) 
![Screenshot_2023-02-03-19-32-31-980_net kdt pojavlaunch](https://user-images.githubusercontent.com/64624657/216710882-36d197a1-1f2e-4bed-bc1e-c8233253551f.jpg)

### Steps To Reproduce

```markdown
1. Install forge 1.7.10 (my file name: forge-1.7.10-10.13.4.1614-1.7.10-installer.jar)
2. Install mods
3. install flowing immersive railroad content packs:
  1. https://www.curseforge.com/minecraft/texture-packs/chris-collection-of-german-stuff/
  2. https://www.curseforge.com/minecraft/texture-packs/voxel-trains-ir/screenshots
  3. https://www.curseforge.com/minecraft/texture-packs/tram-pack
4. Start forge 1.7.10
5. Play in Single player or connect to a Server like me
6. If you now looking around the bug is happened.
```

### Expected Behavior

I have no idea what is meant by this, if a short description is meant of the bug, then here: if you looking around that's a transparent & white bug.

### Platform

```markdown
- Device model: Xiaomi Mi 11T Lite (210911DG)
- CPU architecture: i don't know my CPU: Octacore Max 2,4 ghz
- Android version: 12
- PojavLauncher version: latest Playstore (dahlia-258-cb44314ab-v3_openjdk)
```

### Anything else?

If I press F1 to hide the gui, everything is normal the bug is gone but wehn I press it again in the gui is schown then it's Back.

**Comment by GaucovyAero** [comment]
Zombe 1.4.7 also has this issue, this defo has to be fixed

**Comment by justinsanjp** [comment]
@GaucovyAero Yes, I really agree with you. That is really annoying.

**Comment by Mathias-Boulay** [comment]
Isn't this a variant of #1948 ?

**Comment by justinsanjp** [comment]
@Mathias-Boulay nope I have the bug without mods too.

**Comment by Mathias-Boulay** [comment]
in which case, I am more interested.
Which setup should be used when mods aren't part of the equation ? @justinweichTV

**Comment by justinsanjp** [comment]
@Mathias-Boulay Unfortunately, I don't understand the question, my English isn't the best and Google translate gives me German words that don't mean anything for me as a native speaker.

**Comment by GaucovyAero** [comment]
> @Mathias-Boulay Unfortunately, I don't understand the question, my English isn't the best and Google translate gives me German words that don't mean anything for me as a native speaker.

how can we reproduce the issue on vanilla?

- also, please use the deepl.com translator

**Comment by justinsanjp** [comment]
Thanks! Normally I only use Deepl for translation, but only in Japanese, if I'm not sure if I'm right with my translation. Just start 1.7.10 without Forge

**Comment by justinsanjp** [comment]
Maby this can help this to fix the bug. i have describe ChatGPT the bug and the response is following:

This issue could be caused by several things, including outdated graphics drivers, incorrect video settings in Minecraft, or compatibility issues with your mods. To try and fix this issue, you can try the following steps:

Update your graphics drivers: Make sure you have the latest graphics drivers installed on your computer. Updating your drivers can fix compatibility issues and improve performance.

Reset video settings: Try resetting your video settings in Minecraft to their default values. Go to "Options" > "Video Settings" and click "Default".

Disable conflicting mods: If you are using mods, try disabling any that you think may be causing the issue. You can do this by removing the mod files from your Minecraft mods folder. (my Comment: I have chacked but everything is normal on pc...)

Verify game files: Try verifying the integrity of your Minecraft game files to ensure that they are not corrupted. You can do this through the game client or the game launcher.

Screenshots:
![Screenshot (17)](https://user-images.githubusercontent.com/64624657/216783445-b2e369d9-db78-4177-9931-61107f6ffd68.png)
![Screenshot (18)](https://user-images.githubusercontent.com/64624657/216783446-e7d9ffdb-a05f-406f-ad37-4282d8d114bd.png)

**Comment by GaucovyAero** [comment]
uhm, the issue is that the mod probably wants some OpenGL 3.2 features that gl4es does not have, all vanillas work fine for me

**Comment by justinsanjp** [comment]
Ok.
