### ISSUE TITLE
Add split screen 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#3918]
### Is this request related to a bug?

Best game you add split screen on gyroscope 

### Describe the request.

Plss read

### Anything else?

Thank you

**Comment by BitBlitObviMormon** [comment]
\*Cringes at the thought of sharing a screen to play Minecraft*

That's a lot of controls to share on a small phone or tablet screen without running the game twice at one time (game runs slow enough as it is). Ever considered playing on a console or PC instead? I can't imagine the thought of mobile split screen without full controller support first. It'd be a nightmare for the programmers to support and uncomfortable to use at best.

**Comment by TarikBR** [comment]
I think its the graphic on split, to use with cardboard, like the images

![Google-Cardboard.jpg](https://user-images.githubusercontent.com/64391349/216740885-bdcd8b2f-6e4f-4198-8e84-975c31ee9bf7.jpg)

![images.jpeg](https://user-images.githubusercontent.com/64391349/216740884-8983e0ab-5435-4e47-a344-cfa68e63ae77.jpeg)

**Comment by kedrick021** [comment]
> *Cringes at the thought of sharing a screen to play Minecraft*
> 
> That's a lot of controls to share on a small phone or tablet screen without running the game twice at one time (game runs slow enough as it is). Ever considered playing on a console or PC instead? I can't imagine the thought of mobile split screen without full controller support first. It'd be a nightmare for the programmers to support and uncomfortable to use at best.

Using Bluetooth controller dude

**Comment by kedrick021** [comment]
Split screen using hand 🤣

**Comment by BitBlitObviMormon** [comment]
> I think its the graphic on split, to use with cardboard, like the images

Vivecraft support could make things interesting, but it'd be more than difficult to implement properly. I've also never gotten Google Cardboard to do more than give me a migraine. 😅

**Comment by kedrick021** [comment]
> > I think its the graphic on split, to use with cardboard, like the images
> 
> Vivecraft support could make things interesting, but it'd be more than difficult to implement properly. I've also never gotten Google Cardboard to do more than give me a migraine. 😅

We don't have money to buy that thing we are poor

**Comment by Mathias-Boulay** [comment]
Let's say part of the codebase is not suited for making this work

**Comment by kedrick021** [comment]
> Let's say part of the codebase is not suited for making this work

Nooooooo 😭

**Comment by kedrick021** [comment]
Plss

**Comment by kedrick021** [comment]
> I think its the graphic on split, to use with cardboard, like the images
> 
> ![Google-Cardboard.jpg](https://user-images.githubusercontent.com/64391349/216740885-bdcd8b2f-6e4f-4198-8e84-975c31ee9bf7.jpg)
> 
> ![images.jpeg](https://user-images.githubusercontent.com/64391349/216740884-8983e0ab-5435-4e47-a344-cfa68e63ae77.jpeg)

Yes 👍

**Comment by mchnjt** [comment]
But why (your title is "Add split screen")
You wanted it to mean "add device vr support" am i correct?

**Comment by kedrick021** [comment]
> But why (your title is "Add split screen") You wanted it to mean "add device vr support" am i correct?

Is not that same?

**Comment by BitBlitObviMormon** [comment]
> Is not that same?

**No.**

Split screen means sharing one screen to play with multiple players.

**Comment by BitBlitObviMormon** [comment]
For example, Screencheat is a game that uses split screen:
![Split screen play](https://beebom.com/wp-content/uploads/2020/02/3.-Screencheat.jpg)

Vivecraft has VR support (and is designed to have one player per console):
![VR play](https://user-images.githubusercontent.com/19243263/217063336-6a6eddf4-086c-498b-9d7a-89fef1cfa238.jpeg)

**Comment by kedrick021** [comment]
> > Is not that same?
> 
> **No.**
> 
> Split screen means sharing one screen to play with multiple players. Hence my comment earlier on sharing controls on a small phone screen. Because that's what split screen would likely actually mean.

I think it's same but mirroring the another side of screen

**Comment by BitBlitObviMormon** [comment]
> I think it's same but mirroring the another side of screen

Except it's not a mirror? The camera is offset with each image to give depth perception to your eyes, similar to how 3D glasses work in a theater.

**Comment by kedrick021** [comment]
> > I think it's same but mirroring the another side of screen
> 
> Except it's not a mirror? The camera is offset with each image to give depth perception to your eyes, similar to how 3D glasses work in a theater.

......ok. But why same picture on boat side?

**Comment by BitBlitObviMormon** [comment]
> ......ok. But why same picture on boat side?

You're not meant to play it in your hands, you wear it as a headset and control your movement with a controller. Each image is for each eye. If they weren't a similar image you would probably have a seizure during proper use.

**Comment by BitBlitObviMormon** [comment]
The idea I'm getting at is that screencheat (and other split screen games) has multiple players, but Vivecraft (and other VR games) has only _one_ player despite having what you call a split screen.

**Comment by kedrick021** [comment]
> > ......ok. But why same picture on boat side?
> 
> You're not meant to play it in your hands, you wear it as a headset and control your movement with a controller. Each image is for each eye. If they weren't a similar image you would probably have a seizure during proper use.

Ok so what it call that thing in same image

**Comment by BitBlitObviMormon** [comment]
> Ok so what it call that thing in same image

Pardon? I don't understand what you mean when you say "what it call that thing in same image"
In any case, this has gone down into the weeds far enough. Were you wanting VR support or same-screen multiplayer support?

**Comment by kedrick021** [comment]
> 

Ok I understand
