### ISSUE TITLE
[BUG] not installed forge-1.4.7-6.6.2.534-src.zip

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#3919]
### Describe the bug

not installed forge-1.4.7-6.6.2.534-src.zip

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I'm waiting for the installation of forge 1.4.7.zip 

### Platform

```markdown
- Device model: Samsung Galaxy A52 
- CPU architecture: 
- Android version: 13
- PojavLauncher version:
```

### Anything else?

![Screenshot_20230204_134311_Files](https://user-images.githubusercontent.com/121510853/216755611-fdd7d90a-383f-4e72-b415-7ff9c02f1848.jpg)

**Comment by Prostop194** [comment]
there you can see forge 1.4.7 does not show up

**Comment by GaucovyAero** [comment]
src is the source code, you cannot play the game with that. You have to create a custom version just like you did before, extract the forge-universal jar, put it into the custom version jar, etc. and then launch it

**Comment by Prostop194** [comment]
I downloaded forge-1.4.7-6.6.2.534-universal.zip

**Comment by Prostop194** [comment]
but there is no internet forge-1.4.7-6.6.2.534-universal.jar

**Comment by GaucovyAero** [comment]
> but there is no internet forge-1.4.7-6.6.2.534-universal.jar

zip and jar are the same

**Comment by Prostop194** [comment]
and what to do I again did not understand sorry

**Comment by Prostop194** [comment]
thank you, I understood how it should be and I was able to launch forge 1.4.7
