### ISSUE TITLE
[BUG] Can't use scroll wheel on physical mouse.

### ISSUE THREAD

**Issue by IamaPineapple24** [PojavLauncherTeam/PojavLauncher#3920]
### Describe the bug

With a mouse plugged into my chromebook, or using the touchpad, the scroll whell doesn't work in menus

### The log file and images/videos

no images or videos

### Steps To Reproduce

```markdown
load minecraft and attempt to use the scroll wheel in a menu
```

### Expected Behavior

I expect the mouse scroll wheel to act like dragging the scrollbar

### Platform

```markdown
- Device model: HP Chromebook EE
- CPU architecture: x86_x64
- Android version: ChromeOS 110 Beta
- PojavLauncher version: dahlia 218
```

### Anything else?

i am on modded version 1.12.2

**Comment by GaucovyAero** [comment]
update your launcher, works on the latest one
