### ISSUE TITLE
[F-Req] <Gyro invert y/x axis>

### ISSUE THREAD

**Issue by william98r** [PojavLauncherTeam/PojavLauncher#3921]
### Is this request related to a bug?

No.

### Describe the request.

The ability to invert the gyro x/y axis depending on what you like. 

### Anything else?

The way the gyro is set up now is impossible for me to control. Left and right are normal but up and down are inverted. If there were an option to make it all inverted or all regular directions, that would be incredible!

**Comment by SellMONBHai** [comment]
click on Actions then click latest build and download it it's fixed in that build

**Comment by william98r** [comment]
Thank you! I am sorry for my ignorance.
