### ISSUE TITLE
[BUG] In the control customization, the Start Gyroscope button is not found

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#3922]
### Describe the bug

In the latest beta I didn't find the boot gyroscope option, which should be a bug, right?

### The log file and images/videos

![Screenshot_20230205_034939_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/100058929/216787080-4d051869-32e2-4916-a66b-fef8926d62b9.jpg)

### Steps To Reproduce

```markdown
1. Start Pojav
2.Settings - Custom control options
```

### Expected Behavior

I hope to fix a bug that isn't a bug

### Platform

```markdown
- Device model: Huawei
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: New beta
```

**Comment by TarikBR** [comment]
I'm almost sure your phone doesn't have the gyro sensor so it doesn't show the preference
