### ISSUE TITLE
[BUG] Crash when using fabric sodium on 1.16.5

### ISSUE THREAD

**Issue by inkyarev** [PojavLauncherTeam/PojavLauncher#3923]
### Describe the bug

When loading a world in fabric ml on 1.16.5 version with sodium and fabric api the launcher crashes. The crash report states that the renderer was not initialized.
The fog and vector settings are disabled.
Tried loading a world with
	Java 8(0.1 sodium from pojavoptimize and 0.2 sodium from curseforge):
		Holy GL4ES,
		virglrenderer(opengl es 3): exports opengl 4.3;
and the same but with Java 17;
Every time resulting in the same crash with same report(renderer not initialized).

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10609762/latestlog.txt)
[crash-2023-02-05_02.56.12-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10609763/crash-2023-02-05_02.56.12-client.txt)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Launch the fabric loader with fabric api and sodium in mods folder
3. Open a world
```

### Expected Behavior

I expected the game to initialize the renderer.

### Platform

```markdown
- Device model: Poco M4
- CPU architecture: 64 bit armv8-a
- Android version: 12
- PojavLauncher version: dahila-258-cb44314ab-v3_openjdk
```

### Anything else?

Optifine + Optifabric isn't a valid alternative for the infinite mojang screen load(and gigantic log) they cause.

**Comment by GaucovyAero** [comment]
use sodium 0.1.0 and turn off compact vertex format + fog occlusion

**Comment by inkyarev** [comment]
> use sodium 0.1.0 and turn off compact vertex format + fog occlusion

i said that already did that. (oops a missclick on closing the issue)

**Comment by GaucovyAero** [comment]
> > use sodium 0.1.0 and turn off compact vertex format + fog occlusion
> 
> i said that already did that. (oops a missclick on closing the issue)

give a log with jre8 + sodium 0.1.0

**Comment by inkyarev** [comment]
> > > use sodium 0.1.0 and turn off compact vertex format + fog occlusion
> > 
> > 
> > i said that already did that. (oops a missclick on closing the issue)
> 
> give a log with jre8 + sodium 0.1.0

used the 0.1 from the curseforge instead of the pojavoptimize and everything worked
haha
