### ISSUE TITLE
[BUG] <Rubidium crashes when ever I load a world>

### ISSUE THREAD

**Issue by EmeenPro123** [PojavLauncherTeam/PojavLauncher#3924]
### Describe the bug

Whenever I load this mod and start a world it keeps crashing 

### The log file and images/videos

This happens to many others who tried the Rubidium mod me and my sister and my brother

### Steps To Reproduce

```markdown
I think when I change to virgl render it will fix it but the biggest issue with virgl render it flips the screen upside down
```

### Expected Behavior

I expected the game would load

### Platform

```markdown
- Device model: huawei y9 prime
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: 
dahlia-258-cb44314ab-v3_openjdk
```

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/file/5p56yswkq3be24d/rubidium-mixins.properties/file
use the **gl4es** renderer and put this file into `/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/config/`

**Comment by EmeenPro123** [comment]
Thank you

**Comment by Forever2397** [comment]
does this patch apply to all versions??

**Comment by EmeenPro123** [comment]
I don't know

**Comment by Felix14-v2** [comment]
> does this patch apply to all versions?

if the names of the mixins have not changed, this will work with your version

**Comment by ParthYT2022** [comment]
Not working

**Comment by ParthYT2022** [comment]
Sub kar liya tab bhi nhi chal raha

**Comment by andynolife** [comment]
Not Work

**Comment by Proaman7603** [comment]
Me also not working pls help me 😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by Felix14-v2** [comment]
> Me also not working pls help me 😭😭😭😭😭😭😭😭😭😭😭😭😭

Why do you need Rubidium at all? It doesn't improve performance on Pojav.

**Comment by alexytomi** [comment]
> > Me also not working pls help me 😭😭😭😭😭😭😭😭😭😭😭😭😭
> 
> Why do you need Rubidium at all? It doesn't improve performance on Pojav.

no this is wrong, it _can_ improve performance. not always and usually hard to notice

**Comment by alexytomi** [comment]
> does this patch apply to all versions??

Only those based on sodium 0.4.10 and below. Otherwise it's useless.

**Comment by Proaman7603** [comment]
> > Me also not working pls help me 😭😭😭😭😭😭😭😭😭😭😭😭😭
> 
> Why do you need Rubidium at all? It doesn't improve performance on Pojav.

So how can i boost  fps ln forge  ? Pls tell me
I want to play an smp that's why I'm asking😭😭😭😭😭

**Comment by Proaman7603** [comment]
> > > Me also not working pls help me 😭😭😭😭😭😭😭😭😭😭😭😭😭
> > 
> > 
> > Why do you need Rubidium at all? It doesn't improve performance on Pojav.
> 
> So how can i boost fps ln forge ? Pls tell me I want to play an smp that's why I'm asking😭😭😭😭😭

**Comment by Felix14-v2** [comment]
> no this is wrong, it _can_ improve performance. not always and usually hard to notice

Don't talk to me about your placebo. The patch disables >90% of the Sodium optimizations, and the rest are not crucial.

> So how can i boost fps

The only viable way is to use VulkanMod – it runs natively on the Vulkan graphics without the slow compatibility layers like GL4ES or Angle. And it can literally triple your FPS compared to castrated Sodium. Here's [the folder](https://www.mediafire.com/folder/xsb4udjs7n8z9/VulkanMod_for_PojavLauncher) with different versions, but I recommend using the latest build with Minecraft 1.20.4.

> boost fps ln forge ? Pls tell me
I want to play an smp 

Why do you need Forge for that? Use the lightweight Fabric with newest VulkanMod instead.

**Comment by alexytomi** [comment]
> > > Me also not working pls help me 😭😭😭😭😭😭😭😭😭😭😭😭😭
> > 
> > 
> > Why do you need Rubidium at all? It doesn't improve performance on Pojav.
> 
> So how can i boost fps ln forge ? Pls tell me I want to play an smp that's why I'm asking😭😭😭😭😭

Get a better phone lmao.

The only effective mods we have that noticably boost FPS is Optifine and Vulkan mod. (and sometimes modernfix but that's not really the mods' job)

**Comment by alexytomi** [comment]
> > no this is wrong, it _can_ improve performance. not always and usually hard to notice
> 
> Don't talk to me about your placebo. The patch disables >90% of the Sodium optimizations, and the rest are not crucial.
> 
> > So how can i boost fps
> 
> The only viable way is to use VulkanMod – it runs natively on the Vulkan graphics without the slow compatibility layers like GL4ES or Angle. And it can literally triple your FPS compared to castrated Sodium. Here's [the folder](https://www.mediafire.com/folder/xsb4udjs7n8z9/VulkanMod_for_PojavLauncher) with different versions, but I recommend using the latest build with Minecraft 1.20.4.
> 
> > boost fps ln forge ? Pls tell me
> > I want to play an smp
> 
> Why do you need Forge for that? Use the lightweight Fabric with newest VulkanMod instead.

It's not placebo. It really does work for like a really small group of phones. For most it actually makes it worse lol.
