### ISSUE TITLE
[BUG] texture bug 

### ISSUE THREAD

**Issue by Eusbhs** [PojavLauncherTeam/PojavLauncher#3925]
### Describe the bug

So whenever I play on version 1.12.2 the items will have some kind of issue and kinda look un3d and whenever I add optifine it just becomes 2d and I don't know how to fix it. (this only happens in 1.12.2)

### The log file and images/videos

![XRecorder_05022023_083358](https://user-images.githubusercontent.com/89671110/216822255-22553bb1-4611-4ad1-92c8-36618641643d.jpg)
![XRecorder_05022023_083144](https://user-images.githubusercontent.com/89671110/216822256-9189656d-3f23-418c-95a8-0f562b546b20.jpg)

### Steps To Reproduce

```markdown
1. Start pojav 
2. Select version 1.12.2 
3. Start it and load in a world 
4. Item glitching 

1. Start pojav 
2. Download forge 1.12.2 
3. Add optifine 
4. Select forge 1.12.2 
5. Start it and load in a world 
6. Items become 2d
```

### Expected Behavior

I want it fixed

### Platform

```markdown
- Device model: Samsung Galaxy A50/128G
- CPU architecture: arm64-v8a
- Android version: 11
- PojavLauncher version: [Latest Release] dahlia-258-cb44314ab-v3_openjdk
```

### Anything else?

Every object becomes 2d beside blocks, they still have their 3d version texture.

**Comment by GaucovyAero** [comment]
your processor does not support high precision shaders, we cannot do anything about this
get a snapdragon device if you want it to behave normally

**Comment by Eusbhs** [comment]
Alright make sense

**Comment by Eusbhs** [comment]
Also it only happens in 1.12.2 and no other version with optifine, so what's up with that?

**Comment by GaucovyAero** [comment]
> Also it only happens in 1.12.2 and no other version with optifine, so what's up with that?

absolutely no idea, but it works just fine for me, i have a snapdragon 801
![Screenshot_20230211-220346](https://user-images.githubusercontent.com/85581164/218282052-06e9b5d0-ff94-4b45-8be9-bcc0f8236d8e.png)

**Comment by Eusbhs** [comment]
Idk man
