### ISSUE TITLE
[BUG] <server resource pack download loop>

### ISSUE THREAD

**Issue by william98r** [PojavLauncherTeam/PojavLauncher#3926]
### Describe the bug

When trying to download the server resource pack, it fails at 60-90% and restarts until the game crashes after 5min.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10611254/latestlog.txt)
[hs_err_pid26074.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10611255/hs_err_pid26074.log)

### Steps To Reproduce

```markdown
1. Start pojavlauncher.
2. Launch stock 1.19.3.
3. Join a server which requires a resource pack (play.wynncraft.com) and accept download.
```

### Expected Behavior

I expected the resource pack to download fully and the reappearing download screen would stop looping.

### Platform

```markdown
- Device model: S21 Ultra 256GB (exynos)
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: latest gyro build #4168
```

### Anything else?

This might just happen to only me because I have too much ram allocated or something. I tried reading the logs but I am not sure what the problem really is.

**Comment by GaucovyAero** [comment]
consider asking the server owners to support opengl 2.1 on their server resource pack, otherwise this is not going anywhere
