### ISSUE TITLE
[BUG] WASD while moving camera

### ISSUE THREAD

**Issue by william98r** [PojavLauncherTeam/PojavLauncher#3927]
### Describe the bug

Can not move camera and walk all directions at the same time. 

### The log file and images/videos

https://youtu.be/JoFG4pFSxdc

### Steps To Reproduce

```markdown
While moving camera, the first button you pressed (w) Will be the only one activated by swipe when cycling through WASD.
```

### Expected Behavior

I should be possible to walk all directions while looking around with the camera at the same time. They should not cancel each other out.

### Platform

```markdown
- Device model: S21 Ultra 256GB
- CPU architecture: AARCH64 
- Android version: 13
- PojavLauncher version: Latest
```

### Anything else?

I don't know if other people have this problem or it is a setting on my phone. Feels like it was possible to move like this once upon a time but it has not worked on the updated pojav versions at all for me. Don't know if it was ever possible.

**Comment by Mathias-Boulay** [comment]
Android 13 has some nasty bugs for now

**Comment by william98r** [comment]
Aw man

**Comment by GaucovyAero** [comment]
fixed in the latest actions builds
