### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheBestXann** [PojavLauncherTeam/PojavLauncher#3928]
### Describe the bug

.

### The log file and images/videos

Uploading 2023-02-06-12-52-14.mp4…

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Galazy A12
- CPU architecture: Aarch64 
- Android version: android 13
- PojavLauncher version: dahlia
```

### Anything else?

.

**Comment by crystall1nedev** [comment]
Fill out the issue template properly.
