### ISSUE TITLE
[Report] VirglRenderer Cannot Go More Than 30 FPS

### ISSUE THREAD

**Issue by AnikyMX** [PojavLauncherTeam/PojavLauncher#3929]
### Describe the bug

Can't Go More Than 30 FPS

### The log file and images/videos

-

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Set Render To VirglRenderer
3. Enter the World
```

### Expected Behavior

My Device Can Run VirglRenderer More Than 30 FPS, preferably up to 60 FPS+

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: New In Playstore
```

### Anything else?

Can You Fix This Problem?

**Comment by mchnjt** [comment]
We can't solve this. We don't do .so file trickery. Please switch back to GL4ES.
![2023-02-06_09 03 05](https://user-images.githubusercontent.com/83752061/216969918-5a83c1c9-0072-4ed0-80c7-914b5dd28145.png)

**Comment by AnikyMX** [comment]
But I also want to feel that using Shader doesn't lag in VirglRendered
