### ISSUE TITLE
[BUG] <Failed to login: Invalie session>

### ISSUE THREAD

**Issue by SpaghettoSensei** [PojavLauncherTeam/PojavLauncher#3930]
### Describe the bug

Failed to login: Invalie session.
I try to enter an Aternos server, this server is cracked for offline accounts.

### The log file and images/videos

![Screenshot_20230206-125218_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/66449669/217052921-27fd4758-c639-4b1f-bbd3-0d90adab922e.jpg)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Join server
```

### Expected Behavior

Join the server and play the server mods

### Platform

```markdown
- Device model: Samsung A50
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Lastest versión from play store
```

**Comment by saccharinesky** [comment]
consider buying the game

**Comment by GaucovyAero** [comment]
buy the game
