### ISSUE TITLE
[BUG] E key doesn't work in creative menu.

### ISSUE THREAD

**Issue by IamaPineapple24** [PojavLauncherTeam/PojavLauncher#3931]
### Describe the bug

When I open the search tab of the inventory (or Just enough items) typing The E key exits the inventory.

### The log file and images/videos

Presumably No log file needed

### Steps To Reproduce

```markdown
Launch any version of minecraft below 1.16.
load a world in creative mode.
open the inventory.
go to the search tab.
type the letter 'e.'
```

### Expected Behavior

I expect pressing 'e' in the inventory to type 'e' rather than closing the inventory.

### Platform

```markdown
- Device model: HP Chromebook G8 EE
- CPU architecture: x64_x86
- Android version: ChromeOS 110 Beta
- PojavLauncher version: latest as of 6/2/2023
```

### Anything else?

Im using minecraft 1.10.2

**Comment by artdeell** [comment]
Cannot reproduce on latest actions. Reply back if it still persists.
