### ISSUE TITLE
[BUG] Hotbar/Health/Hunger bars invisible but exist

### ISSUE THREAD

**Issue by SkarpoJade** [PojavLauncherTeam/PojavLauncher#3932]
### Describe the bug

As stated in title.I began survival world on pojav today and the hotbar was missing,so was the health and hunger bar. 
But,my hand/tool is still visible.
Also,I _can_ interact with my hotbar.I can select other tools/items.

Someone in reddit had the same problem.Also,I tried searching online but only found pressing F1 key solution and changing opacity,which can only be done in bedrock I think.I tried these but didnt work. 

### The log file and images/videos

![Screenshot_2023-02-07-16-11-07-456_net kdt 

> 

> 

>    `#@@pojavlaunch](https://user-images.githubusercontent.com/99120760/217225491-9deb2bb9-622a-4d31-ae75-b8c46266fc1c.jpg)`

![Screenshot_2023-02-07-16-15-11-590_net kdt pojavlaunch](https://user-images.githubusercontent.com/99120760/217225508-f478ebf5-6c3b-4063-b837-ae2fb08a5937.jpg)
@ #``

I cant attach log files,its grayed out in google files. 
--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms512m -Xmx800m"
Headless version detected! (20221207)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/[libjli.so](http://libjli.so/)" has unsupported flags DT_FLAGS_1=
0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libverify.so](http://libverify.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjava.so](http://libjava.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libnet.so](http://libnet.so/)" has unsupported flags DT_FLAGS_1=
0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libnio.so](http://libnio.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libawt.so](http://libawt.so/)" has unsupported flags DT_FLAGS_1=0x81
 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libawt_headless.so](http://libawt_headless.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)

WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libfontmanager.so](http://libfontmanager.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
--------- beginning of system
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libhprof.so](http://libhprof.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libj2pcsc.so](http://libj2pcsc.so/)" has unsupported flags DT_FLAGS_1=0x81
--------- beginning of main
 (ignoring unsupported flags)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libdt_socket.so](http://libdt_socket.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[liblcms.so](http://liblcms.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libmanagement.so](http://libmanagement.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjpeg.so](http://libjpeg.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libmlib_image.so](http://libmlib_image.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: 
Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjsdt.so](http://libjsdt.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libj2pkcs11.so](http://libj2pkcs11.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjsound.so](http://libjsound.so/)" has unsupported flags DT_FLAGS_1=
0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libj2gss.so](http://libj2gss.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libunpack.so](http://libunpack.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libnpt.so](http://libnpt.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libtinyiconv.so](http://libtinyiconv.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjava_crw_demo.so](http://libjava_crw_demo.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libzip.so](http://libzip.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjawt.so](http://libjawt.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjaas_unix.so](http://libjaas_unix.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/[libjli.so](http://libjli.so/) success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libsctp.so](http://libsctp.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/[libjvm.so](http://libjvm.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libverify.so](http://libverify.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjava.so](http://libjava.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libnet.so](http://libnet.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libnio.so](http://libnio.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libawt.so](http://libawt.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libawt_headless.so](http://libawt_headless.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libfreetype.so](http://libfreetype.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libfontmanager.so](http://libfontmanager.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libhprof.so](http://libhprof.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libfontmanager.so](http://libfontmanager.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libj2pcsc.so](http://libj2pcsc.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libdt_socket.so](http://libdt_socket.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[liblcms.so](http://liblcms.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libverify.so](http://libverify.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libmanagement.so](http://libmanagement.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjpeg.so](http://libjpeg.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libmlib_image.so](http://libmlib_image.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjsig.so](http://libjsig.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjsdt.so](http://libjsdt.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libawt_headless.so](http://libawt_headless.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libj2pkcs11.so](http://libj2pkcs11.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libnet.so](http://libnet.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjava.so](http://libjava.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjsound.so](http://libjsound.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libsunec.so](http://libsunec.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libawt.so](http://libawt.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libj2gss.so](http://libj2gss.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libunpack.so](http://libunpack.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdWARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjdwp.so](http://libjdwp.so/)" has unsupported flags DT_FLAGS_1=
t.pojavlaunch/jre_runtime/lib/aarch32/[libfreetype.so](http://libfreetype.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libnpt.so](http://libnpt.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjava_crw_demo.so](http://libjava_crw_demo.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libnio.so](http://libnio.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libawt_xawt.so](http://libawt_xawt.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/[libjvm.so](http://libjvm.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libtinyiconv.so](http://libtinyiconv.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libzip.so](http://libzip.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjawt.so](http://libjawt.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjaas_unix.so](http://libjaas_unix.so/) success
I/jrelog  (14609): 0x81 (ignoring unsupported flags)
dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libsctp.so](http://libsctp.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/[libjli.so](http://libjli.so/) success
WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libinstrument.so](http://libinstrument.so/)" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libjdwp.so](http://libjdwp.so/) success
I/jrelog  (14609): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/[libinstrument.so](http://libinstrument.so/) success
I/jrelog  (14609): dlopen /data/app/net.kdt.pojavlaunch-6Rxnajb4rol1PWf_HDWdKg==/lib/arm/[libopenal.so](http://libopenal.so/) success
I/LIBGL   (14609): Initialising gl4es
I/LIBGL   (14609): v1.1.4 built on Jul 19 2020 08:24:33
I/LIBGL   (14609): Using GLES 2.0 backend
I/LIBGL   (14609): loaded: [libGLESv2.so](http://libglesv2.so/)
I/LIBGL   (14609): loaded: [libEGL.so](http://libegl.so/)
I/LIBGL   (14609): Using GLES 2.0 backend
I/LIBGL   (14609): Hardware Full NPOT detected and used
I/LIBGL   (14609): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (14609): Extension GL_EXT_draw_buffers  detected and used
I/LIBGL   (14609): FBO are in core, and so used
I/LIBGL   (14609): PointSprite are in core, and so used
I/LIBGL   (14609): CubeMap are in core, and so used
I/LIBGL   (14609): BlendColor is in core, and so used
I/LIBGL   (14609): Blend Substract is in core, and so used
I/LIBGL   (14609): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (14609): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (14609): Extension GL_OES_mapbuffer  detected
I/LIBGL   (14609): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (14609): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (14609): Extension GL_OES_depth24  detected and used
I/LIBGL   (14609): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (14609): Extension GL_EXT_multi_draw_arrays  detected
I/LIBGL   (14609): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (14609): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (14609): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (14609): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (14609): Extension GL_OES_texture_float  detected and used
I/LIBGL   (14609): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (14609): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (14609): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (14609): Extension GL_OES_fragment_precision_high  detected and used
I/LIBGL   (14609): Extension GL_EXT_shader_texture_lod detected and used
I/LIBGL   (14609): Max vertex attrib: 16
I/LIBGL   (14609): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (14609): Max texture size: 4096
I/LIBGL   (14609): Max Varying Vector: 15
I/LIBGL   (14609): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (14609): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (14609): Hardware vendor is Imagination Technologies
I/LIBGL   (14609): GLSL 300 es supported
I/LIBGL   (14609): GLSL 310 es supported and used
I/LIBGL   (14609): sRGB surface supported
I/LIBGL   (14609): EGLImage to Texture2D supported
I/LIBGL   (14609): EGLImage to RenderBuffer supported
I/LIBGL   (14609): ignore MipMap
I/LIBGL   (14609): Targeting OpenGL 2.1
I/LIBGL   (14609): NPOT texture handled in hardware
I/LIBGL   (14609): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (14609): try to use VBO
I/LIBGL   (14609): FBO workaround for using binded texture enabled
I/LIBGL   (14609): glX Will try to recycle EGL Surface
I/LIBGL   (14609): Current folder is:/
I/jrelog  (14609): dlopen /data/app/net.kdt.pojavlaunch-6Rxnajb4rol1PWf_HDWdKg==/lib/arm/[libgl4es_114.so](http://libgl4es_114.so/) success
I/jrelog  (14609): Done processing args
I/jrelog  (14609): Found JLI lib
I/jrelog  (14609): Calling JLI_Launch
OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass([ClassLoader.java:756](http://classloader.java:756/))

	at [java.security](http://java.security/).SecureClassLoader.defineClass([SecureClassLoader.java:142](http://secureclassloader.java:142/))
	at [java.net](http://java.net/).URLClassLoader.defineClass([URLClassLoader.java:468](http://urlclassloader.java:468/))
	at [java.net](http://java.net/).URLClassLoader.access$100([URLClassLoader.java:74](http://urlclassloader.java:74/))
	at [java.net](http://java.net/).URLClassLoader$[1.run](http://1.run/)([URLClassLoader.java:369](http://urlclassloader.java:369/))
	at [java.net](http://java.net/).URLClassLoader$[1.run](http://1.run/)([URLClassLoader.java:363](http://urlclassloader.java:363/))

	at [java.security](http://java.security/).AccessController.doPrivileged(Native Method)
	at [java.net](http://java.net/).URLClassLoader.findClass([URLClassLoader.java:362](http://urlclassloader.java:362/))
	at java.lang.ClassLoader.loadClass([ClassLoader.java:418](http://classloader.java:418/))
	at sun.misc.Launcher$AppClassLoader.loadClass([Launcher.java:352](http://launcher.java:352/))

	at java.lang.ClassLoader.loadClass([ClassLoader.java:351](http://classloader.java:351/))
	at sun.launcher.LauncherHelper.checkAndLoadMain([LauncherHelper.java:601](http://launcherhelper.java:601/))
Java Exit code: 1
I/jrelog  (14609): Going to free args
I/jrelog  (14609): Free done

### Steps To Reproduce

```markdown
1.Start the game
2.Open survival world
```

### Expected Behavior

I wanted the hotbar,with hunger and health bars to appear by default in my survival world. 

### Platform

```markdown
- Device model:Redmi 9
- CPU architecture:ARM
- Android version:Miui 12
- PojavLauncher version: Latest playstore release
```

### Anything else?

I just installed the game today by following a guide on XDA developer website, with jr 1.17 installed and on version 1.19.2.

**Comment by GaucovyAero** [comment]
install optifine and in the shaders tab, set antialiasing to 2x fxaa

**Comment by SkarpoJade** [comment]
Hi! 
Its working now,thanks a lot. 

I installed Optifine and set the shaders to 2x FXAA, can see the hotbar/health/hunger bars now.
