### ISSUE TITLE
[F-Req] Port to HTML

### ISSUE THREAD

**Issue by FusionCow11** [PojavLauncherTeam/PojavLauncher#3933]
### Describe the request.

If the developers of Pojav Launcher could port this to html it would be greatly appreciated. Using this method, while Pojav wouldn't be natively available everywhere, it would still be playable everywhere.

If the developers of pojav would take my request seriously it would be greatly appreciated.

**Comment by artdeell** [comment]
HTML is not a programming language

But seriously, this would be a lot, and i mean a LOT of work, with very little return since it would be very, very slow (with the current state of webassembly performance anyway)
It would also be pretty limited due to the fact that it's a browser.
So we are doing native applications.

**Comment by FusionCow11** [comment]
This makes sense, but while it is true that HTML is not a programming language, HTML combined with html canvas, webassembly, and javascript can be combined to make a near perfect replica of minecraft. For example, Eaglercraft is a port of cracked minecraft 1.5.2 and 1.8.8 to HTML, and it runs quite well! The only issues with it are A. Its cracked and B. It seems to be a little suspicious. Something like this is possible, but if the required amount of work isn't worth your time I totally understand.

**Comment by GaucovyAero** [comment]
native better

**Comment by mchnjt** [comment]
> This makes sense, but while it is true that HTML is not a programming language, HTML combined with html canvas, webassembly, and javascript can be combined to make a near perfect replica of minecraft. For example, Eaglercraft is a port of cracked minecraft 1.5.2 and 1.8.8 to HTML, and it runs quite well! The only issues with it are A. Its cracked and B. It seems to be a little suspicious. Something like this is possible, but if the required amount of work isn't worth your time I totally understand.

Why

**Comment by mchnjt** [comment]
In what way this will benefit us
