### ISSUE TITLE
[F-Req] Mod Downloader like in PrismLauncher

### ISSUE THREAD

**Issue by Valdex** [PojavLauncherTeam/PojavLauncher#3935]
### Is this request related to a bug?

[Prism Launcher](https://github.com/PrismLauncher/PrismLauncher) is able to download & update individual mods from outside of modpacks using Modrinth and CurseForge. And modloaders (https://i.imgur.com/PKrIasE.png)
Like here: https://i.imgur.com/pV8jnES.png

**Comment by mchnjt** [comment]
No. Just use the curseforge CLI.

**Comment by mchnjt** [comment]
Also I don't think anyone's lazy enough to download a modloader installer from their designated websites and install them via the .jar installer in our launcher.

**Comment by mchnjt** [comment]
For downloading modpacks, please use [cursforge-cli](https://github.com/North-West-Wind/CurseForge-CLI).

**Comment by Valdex** [comment]
> Also I don't think anyone's lazy enough to download a modloader installer from their designated websites and install them via the .jar installer in our launcher.

I dont want to download 100 files from 50 sites to play with mods

**Comment by mchnjt** [comment]
> dont

You, uh, running Minecraft mods in the .jar installer doesn't work. I think you misunderstood what i said
