### ISSUE TITLE
[BUG] [Issue] [Crash] Recording and World Generation Crash

### ISSUE THREAD

**Issue by WDGaster17** [PojavLauncherTeam/PojavLauncher#3936]
### Describe the bug

Screen record crashing and world crashing during world generation
This is needed to fix for YouTubers

### The log file and images/videos

No log needed

### Steps To Reproduce

```markdown
1. Start recording
2. Start PojavLauncher
3. Play
4. Click any world saves
5. 0% world progress then recording crash
6. Joining world then World crash
```

### Expected Behavior

World generation with any screen recorder

### Platform

```markdown
- Device model: ...
- CPU architecture: armeabi-v7a
- Android version: 8.1.0
- PojavLauncher version: latest
```

### Anything else?

Please fix it every Pojavlauncher YouTubers need to Record for YouTube

**Comment by TarikBR** [comment]
it's probably your phone that's not supporting both at the same time. I tested with my phone, and there was no crash (Motorola One Vision).

**Comment by GaucovyAero** [comment]
allocate less RAM to pojav, and if that doesnt fix it, buy a 64-bit phone with more ram
