### ISSUE TITLE
[BUG] Black Screenshot

### ISSUE THREAD

**Issue by WDGaster17** [PojavLauncherTeam/PojavLauncher#3937]
### Describe the bug

Black screenshot on 1.17 - 1.19.3

### The log file and images/videos

![2023-02-05_16 02 32](https://user-images.githubusercontent.com/110589371/217739135-a017fed9-e63d-4106-935e-99f4d42f07d2.png)

### Steps To Reproduce

```markdown
Even in Menu, if you click F2 then the Result of Screenshots was Black only and its same kb/kilobyte
```

### Expected Behavior

Anytime

### Platform

```markdown
- Device model: Any of my device
- CPU architecture: armeabi-v7a and arm64-v8a
- Android version: 4.4 - 8.1.0
- PojavLauncher version: Latest
```

### Anything else?

Fix this

**Comment by GaucovyAero** [comment]
i dont understand whats the issue
