### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by jackyleo1234** [PojavLauncherTeam/PojavLauncher#3938]
### Describe the bug

it keeps crashing when i play all the mods 6 modpack is it because i have 4gb on my chromebook

### The log file and images/videos

`
[crash-2023-02-09_09.25.45-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10698713/crash-2023-02-09_09.25.45-client.txt)
`

### Steps To Reproduce

```markdown
unknown
```

### Expected Behavior

to load

### Platform

```markdown
- Device model: Version 109.0.5414.125 (Official Build) (32-bit)
- CPU architecture: unknown
- Android version: unknown
- PojavLauncher version: dahlia-258-cb44314ab-v3_openjdk
```

### Anything else?

can you tell me what mods to delete that would help i think...

**Comment by GaucovyAero** [comment]
you have not sent the log

**Comment by jackyleo1234** [comment]
how do i do it i forgot

**Comment by GaucovyAero** [comment]
> how do i do it i forgot

well it depends on the android version you have
