### ISSUE TITLE
[BUG] Weird rendering glitch (Faces showing the back instead of front?)

### ISSUE THREAD

**Issue by Raidenxd2** [PojavLauncherTeam/PojavLauncher#3940]
### EDIT
To anyone that is having this same problem, remove [Applied Energistics 2](https://appliedenergistics.github.io/) from your mods folder.

### Describe the bug

The rendering glitch seemed to happen around 1 hour of playing (I was just messing around)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10712585/latestlog.txt)
![Screenshot_20230210-230521_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/64755433/218238868-e1fa0ad2-78a8-4349-a96e-0261f3fa6e25.png)
![Screenshot_20230210-230600_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/64755433/218238877-aa6fa28a-5af6-4f8a-8e4f-d71fcde4b1b6.png)
![Screenshot_20230210-230452_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/64755433/218238879-0de9219d-9565-461e-b3b1-21c21ce14f3a.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start 1.7.10
3. Play for a bit
4. Rendering glitch
```

### Expected Behavior

I expect this not to happen.

### Platform

```markdown
- Device model: Samsung Galaxy Tab A7 3/32G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-258-cb44314ab-v3_openjdk
```

**Comment by Raidenxd2** [comment]
EDIT:
I have updated to dahlia-261-f3aeba0b2- (it ends with a dash in android settings).
I have disabled "Use alternate surface rendering".
I have disabled "Fast Render" in Optifine.
But the same thing still occurs (this time blanking out the screen).

**Comment by mchnjt** [comment]
do f5

**Comment by mchnjt** [comment]
what renderer are you also using btw

**Comment by Raidenxd2** [comment]
> what renderer are you also using btw

HolyGL4ES

**Comment by GaucovyAero** [comment]
> > what renderer are you also using btw
> 
> HolyGL4ES

try pressing F11 when the issue occurs, and if that doesn't fix it, you are out of VRAM

**Comment by Raidenxd2** [comment]
> try pressing F11 when the issue occurs, and if that doesn't fix it, you are out of VRAM

Did that when it happened but it did nothing.
If I am running out of VRAM, how can i reduce the VRAM usage?
I can attach a video of it happening if i need to.

**Comment by GaucovyAero** [comment]
> > try pressing F11 when the issue occurs, and if that doesn't fix it, you are out of VRAM
> 
> Did that when it happened but it did nothing. If I am running out of VRAM, how can i reduce the VRAM usage? I can attach a video of it happening if i need to.

thing is you probably cannot decrease vram usage, using olauncher as your main launcher may help a bit, but i suppose its gonna be extremely hard to navigate on such a big tablet

**Comment by Raidenxd2** [comment]
> thing is you probably cannot decrease vram usage, using olauncher as your main launcher may help a bit, but i suppose its gonna be extremely hard to navigate on such a big tablet

It seems like it was just [Applied Energistics 2](https://appliedenergistics.github.io/) causing it. I removed it and the rendering glitch stopped.

**Comment by GaucovyAero** [comment]
> > thing is you probably cannot decrease vram usage, using olauncher as your main launcher may help a bit, but i suppose its gonna be extremely hard to navigate on such a big tablet
> 
> It seems like it was just [Applied Energistics 2](https://appliedenergistics.github.io/) causing it. I removed it and the rendering glitch stopped.

cool
