### ISSUE TITLE
[BUG] <Discord link expired>

### ISSUE THREAD

**Issue by aotgamerz** [PojavLauncherTeam/PojavLauncher#3941]
### Describe the bug

Renew the discord link. also share the link i wanna join!

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
https://discord.gg/pojavlauncher-724163890803638273
alright, this should not expire, ive created a permanent link
