### ISSUE TITLE
Add a skin selector for offline or online accounts

### ISSUE THREAD

**Issue by JakeKimYT** [PojavLauncherTeam/PojavLauncher#3943]
### Is this request related to a bug?

You should add a skin selector because of the automatic skins (the normal skins like steve, alex, etc.) is random

### Describe the request.

Add a skin selector
The skin should be changeable anytime (but not while the game is running
Could add custom skin files and cape files

**Comment by mchnjt** [comment]
No

**Comment by GaucovyAero** [comment]
no
