### ISSUE TITLE
[BUG] Screen Shaking Bug

### ISSUE THREAD

**Issue by Entitygamer66** [PojavLauncherTeam/PojavLauncher#3945]
### Describe the bug

In the latest update,i encounter a new bug,the screen will slowly shake like an earthquake when i enter the world.

### The log file and images/videos

no available video yet.

### Steps To Reproduce

```markdown
1.Start the launcher.
2.Enter the world.
3.And then boom! the screen starts to shake.
```

### Expected Behavior

I expected no bugs at all.

### Platform

```markdown
- Device model: Vivo Y02s
- CPU architecture: Octa Core
- Android version: 12
- PojavLauncher version: latest release
```

**Comment by Entitygamer66** [comment]
So,this is not a bug guys,its a feature called gyroscope controls.

**Comment by GaucovyAero** [comment]
lol

**Comment by mchnjt** [comment]
> ### Describe the bug
> In the latest update,i encounter a new bug,the screen will slowly shake like an earthquake when i enter the world.

You should probably know what things you've been randomly turning on. Disable the Gyroscope Controls feature.
