### ISSUE TITLE
[BUG] Game crashes with error code -1

### ISSUE THREAD

**Issue by Khushiganda** [PojavLauncherTeam/PojavLauncher#3946]
### Describe the bug

It shows the error code -1. 

I've got a fairly big mod maybe that is causing some problem. 
Please help. 

### The log file and images/videos

[crash-2023-02-12_17.40.43-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10716059/crash-2023-02-12_17.40.43-client.txt)

### Steps To Reproduce

```markdown
1. Install forge on version 1.7.10.
2. Add the decimation mod to the mod folder. 
3. Start the game.
```

### Expected Behavior

I expected the game to start. 

### Platform

```markdown
- Device model: redmi note 10 pro
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest from play store
```

**Comment by Raidenxd2** [comment]
It seems the mod requires Discord RPC, as it says in the crash log:

`Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (linux-aarch64/libdiscord-rpc.so)`

I don't think PojavLauncher supports Discord RPC, as it is crashing trying to load it.
