### ISSUE TITLE
[BUG] Mouse scroll wheel too slow

### ISSUE THREAD

**Issue by IamaPineapple24** [PojavLauncherTeam/PojavLauncher#3949]
### Describe the bug

When i scroll the hotbar in versions 1.13+ it takes like 15 tries to scroll 1 slot.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10717015/latestlog.txt)

### Steps To Reproduce

```markdown
start minecraft 1.13+ and scroll through the hotbar with a physical mouse.
```

### Expected Behavior

I expect one notch on the mouse scroll wheel to attain to one hotbar slot.

### Platform

```markdown
- Device model: Chromebook HP EE G8
- CPU architecture: x64_x86
- Android version: chromeos 110
- PojavLauncher version: latest as of 12/2/2023
```

**Comment by MegaFaresX** [comment]
Ah scroll faster or try to get the real java edition runing via Linux or somethin

**Comment by MegaFaresX** [comment]
Then compare the results

**Comment by Raidenxd2** [comment]
How much FPS did you have?

**Comment by IamaPineapple24** [comment]
> How much FPS did you have?

something like 23, but it works fine in older versions, and on real java it runs perfectly no problems

**Comment by IamaPineapple24** [comment]
> > How much FPS did you have?
> 
> something like 23, but it works fine in older versions, and on real java it runs perfectly no problems

(it had to be on an old windows pc because my chromebook has like 16gb of storage on it

**Comment by GaucovyAero** [comment]
well, i can't reproduce the issue unfortunately - the scroll wheel works perfectly for me at 20fps, and none of the devs (or me) have a chromebook, i'll have to close this unfortunately, because it can be an OEM issue we may not be able to solve
