### ISSUE TITLE
[BUG] [Gyroscope controls] X axis is still inverted in the landscape orientation

### ISSUE THREAD

**Issue by Felix14-v2** [PojavLauncherTeam/PojavLauncher#3950]
### Description

The rotation of the camera in landscape orientation is inverted horizontally. At the same time, in portrait orientation, the camera rotation works correctly.

### Demo

https://youtu.be/F9EW5gotmvI

### To Reproduce

```may depend on the device```
- launch Minecraft with gyro controls
- join to any world
- move your device horizontally
- remember the direction
- split your screen to be able change the screen orientation or use 3rd-party screen orientators
- move your device horizontally
- the direction of camera rotation is different (in my case the direction is correct in contrast to the landscape orientation)

### Expected Behavior

PojavLauncher must correctly change the direction of the camera rotation depending on the device orientation.

### Platform

```markdown
- Device model: TECNO LE7n
- CPU architecture: x64
- Android version: 11
- PojavLauncher version: latest from Actions/GooglePlay
```

**Comment by GaucovyAero** [comment]
iirc we cannot do anything about this

**Comment by Felix14-v2** [comment]
> iirc we cannot do anything about this

At least it is possible to add a manual switch as a workaround

**Comment by Mathias-Boulay** [comment]
Done.
