### ISSUE TITLE
[BUG] holy gl4es is crashing

### ISSUE THREAD

**Issue by mahmoud-games12** [PojavLauncherTeam/PojavLauncher#3952]
### Describe the bug

I can't play.

log file: 
![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10716989/latestlog.txt)

### The log file and images/videos

![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10716989/latestlog.txt)

### Steps To Reproduce

```markdown
open pojavlauncher version 1.19.2 with optifine and renderer: holy gl4es and open a map
```

### Expected Behavior

I expect game will play

### Platform

```markdown
- Device model: Realme C15/64G RMX2180
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

### Anything else?

I tried virgl renderer. but all items and blocks texture is not work (looks bad and low fps)

angle renderer: same

please fix it.

**Comment by GaucovyAero** [comment]
disable render regions in optifine performance settings

**Comment by mahmoud-games12** [comment]
ok

**Comment by mahmoud-games12** [comment]
It Worked!! thanks.

Is there a way to increase(boost) fps ?

**Comment by GaucovyAero** [comment]
> It Worked!! thanks.
> 
> Is there a way to increase(boost) fps ?

yes, join https://discord.gg/pojavlauncher
