### ISSUE TITLE
[BUG] freezes and does not let me launch the game

### ISSUE THREAD

**Issue by ime-01** [PojavLauncherTeam/PojavLauncher#3953]
### Describe the bug

I have downloaded forge 1.16.5, and 8 mods. I launched it many times and it worked seamlessly at 120 fps. But after launching it again, it freezes on the startup screen before even showing the Mojang loading screen.

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10731628/latestlog.old.txt)
[forge.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/10731676/forge.zip)
[mods.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/10731679/mods.zip)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Press the "Install .jar" in the sidebar
3. In the files menu that pops up, open the forge installer .jar file.
4. Proceed with the installation.
5. Close the app.
6. Go to the mods folder and drop all 8 mods in (I have uploaded all the mod files (yes, optifine is considered a mod in this case) and also the forge downloader .jar file as well) -- For iPhone users, this should be: On My iPhone/Pojavlauncher/instances/default/mods
7. Open AltStore, and long press on PojavLauncher, select "enable JIT".
8. Wait for PojavLauncher to open.
9. Set a custom control UI.
10. Save it, name it "MAIN", and make it default.
11. Launch the game.
12. After playing for a while, exit the app completely.
13. Open AltStore, again, long-press on PojavLauncher, and press "enable JIT".
14. Wait for PojavLauncher to load, and press play.
15. Now it will freeze on the startup screen before showing the Mojang loading screen.

P.S. if the game launches properly, close out of it completely, and launch it again using the same way.
```

### Expected Behavior

I expect the game to launch properly every time.

### Platform

```markdown
- Device model: iPhone 14 Pro Max
- CPU architecture: Apple A16 Bionic
- Android version: uhh IOS 16.1.2
- PojavLauncher version: 2.1 (not sure)
```

**Comment by GaucovyAero** [comment]
weird

**Comment by ime-01** [comment]
[UPDATE]:
Sometimes it launches properly, and sometimes it doesn't. I just launched the game and played normally, closed the game, launched it, and now its frozen again :).

**Comment by GaucovyAero** [comment]
> [UPDATE]: Sometimes it launches properly, and sometimes it doesn't. I just launched the game and played normally, closed the game, launched it, and now its frozen again :).

try decreasing ram allocation till it starts to run consistently, maybe also try closing stuff in the background?

**Comment by ime-01** [comment]
let me try

**Comment by ime-01** [comment]
nope, still freezes

**Comment by GaucovyAero** [comment]
> nope, still freezes

i have no other explanation then

**Comment by ime-01** [comment]
I don't think it is about ram allocation, I can give it like 2g of ram. let me actually try that

**Comment by GaucovyAero** [comment]
> I don't think it is about ram allocation, I can give it like 2g of ram. let me actually try that

try 500MB

**Comment by ime-01** [comment]
I don't think 500 will work at all, but i'll try it

**Comment by ime-01** [comment]
nope, still froze at 500 mb

**Comment by ime-01** [comment]
i'll try 2g now

**Comment by ime-01** [comment]
oh yeah, btw its frozen in a way that I cannot even turn the game from landscape to portrait mode

**Comment by ime-01** [comment]
nope, still frozen even at 2g of ram

**Comment by ime-01** [comment]
I have an idea, I'll try it without turning on JIT.

**Comment by GaucovyAero** [comment]
> I have an idea, I'll try it without turning on JIT.

that wont run at all

**Comment by ime-01** [comment]
Yeah, I don't really know what I'm doing tbh

**Comment by ime-01** [comment]
this is what it looks like btw
![IMG_1003](https://user-images.githubusercontent.com/125314608/218726545-5606fb23-f1f9-4f5c-8904-c7e1210cd9fe.PNG)
![IMG_1004](https://user-images.githubusercontent.com/125314608/218726566-da39e9d6-0a83-4cf2-b346-8eaecc48669a.PNG)

**Comment by GaucovyAero** [comment]
rip

**Comment by ime-01** [comment]
lol

**Comment by ime-01** [comment]
This is the JVM arguments I have on my pc (same launcher, same mods, same everything): "-Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"

So can I like paste this in the pojav launcher JVM arguments section? but instead of the 8G, i'll do 1600M

**Comment by GaucovyAero** [comment]
> This is the JVM arguments I have on my pc (same launcher, same mods, same everything): "-Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
> 
> So can I like paste this in the pojav launcher JVM arguments section? but instead of the 8G, i'll do 1600M

jvm arguments do basically nothing on pojavlauncher

**Comment by ime-01** [comment]
oh

**Comment by ime-01** [comment]
i'll still try tho

**Comment by ime-01** [comment]
nope, doesnt work at all

**Comment by ime-01** [comment]
i'll just let my phone rest, and try again in like 5 minutes

**Comment by ime-01** [comment]
damn... I'm disappointed... it worked

**Comment by GaucovyAero** [comment]
kinda forgot to direct you to pojavlauncher_ios -> you posted this in the android repository, ill close this
