### ISSUE TITLE
The screen gets bigger when I want to play with mods[BUG] <Short description>

### ISSUE THREAD

**Issue by Anderson7654321** [PojavLauncherTeam/PojavLauncher#3954]
### Describe the bug

Every time I try to play with a mod the screen gets bigger and won't let me play with a mod

### The log file and images/videos

![Screenshot_20230215-172421](https://user-images.githubusercontent.com/115793233/219199034-cbbcb338-6364-45da-b132-8007342b6982.png)

![Screenshot_20230215-172218](https://user-images.githubusercontent.com/115793233/219199100-369dfd3f-2f85-4bee-bddd-4f5bb42fa19d.png)

### Steps To Reproduce

```markdown
1)Start PojavLauncher and put curse forge. 
2)I put a mod 
3) Suddenly the screen enlarges.
```

### Expected Behavior

I hope they answer my problem 

### Platform

```markdown
- Device model:DRA-L21/2.0
- CPU architecture:MT6739
- Android version:8.1.0
- PojavLauncher version:dahlia-260-ff1db3127-v3_openjdk
```

### Anything else?

Hope they fix it soon

**Comment by GaucovyAero** [comment]
just increase the resolution scale dafuq
