### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by luigi052005** [PojavLauncherTeam/PojavLauncher#3955]
### Describe the bug

Optifine shaders dont work

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10753327/latest.log)

### Steps To Reproduce

```markdown
1. Start Pojav 
2. Install Optifiabric 1.19.2
3. install optifine 1.19.2
4. Use Holy gl4es
5. Start the game and select a shader
6. Join a world
```

### Expected Behavior

I expected that some shaders work.

### Platform

```markdown
- Device model: ASUS Zenfone 8
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Release
```

### Anything else?

Sodium and iris also dont work

**Comment by GaucovyAero** [comment]
and they wont, gl4es is only running on opengl 2.1
