### ISSUE TITLE
[BUG] Shift+W toggling windowed mode?

### ISSUE THREAD

**Issue by enhancedrock** [PojavLauncherTeam/PojavLauncher#3956]
### Describe the bug

When I'm playing Minecraft, if I try to do any form of input using Shift+W (e.g. sneaking & moving forward), the actual Minecraft game itself as oppose to PojavLauncher as a whole shrinks and unshrinks as though it were entering a windowed mode.

### The log file and images/videos

Normal
![Screenshot 2023-02-17 10 21 35 AM](https://user-images.githubusercontent.com/98226500/219618028-c1333de3-d721-42eb-9ed4-e1861f7a4c4a.png)
After Shift+W
![Screenshot 2023-02-17 10 22 00 AM](https://user-images.githubusercontent.com/98226500/219618123-2a799702-2aa9-405e-8512-1f8db1bf017e.png)

### Steps To Reproduce

```markdown
1. Start PojavLauncher (seems to happen on 1.8.9)
2. Shift+W (you can do it anywhere in the game, except during loading)
```

### Expected Behavior

I expected to be able to shift and walk

### Platform

```markdown
- Device model: Acer C722 Series (Chromebook)
- CPU architecture: ARMv8-A (kernel architechture is aarch64)
- Android version: 9 in chromeOS sandbox
- PojavLauncher version: [Latest Google Play || version dahlia-260-ff1db3127-v3_openjdk]
```

**Comment by GaucovyAero** [comment]
bind fullscreen to f12 in minecraft controls settings, there is nothing we can do about this
