### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by Komnapas** [PojavLauncherTeam/PojavLauncher#3957]
### Describe the bug

Application exited with code -1

### The log file and images/videos

![Screenshot_2023-02-17-18-17-03-313_net kdt pojavlaunch](https://user-images.githubusercontent.com/125657397/219640887-af5ad659-b299-4b2e-9d82-b080ae9348c7.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10766224/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.this happen
```

### Expected Behavior

I expect the game to launch 

### Platform

```markdown
- Device model: Xiaomi poco x3 nfc 6/64g
- CPU architecture: kyro 470
- Android version: 11
- PojavLauncher version: dahlia-258-cb4431 4ab-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use mods on your own risk, a lot of them don't work
remove create and flywheel, they require opengl 3.2, pojav only has 2.1

**Comment by Komnapas** [comment]
![Screenshot_2023-02-24-18-51-50-376_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/125657397/221173038-07b8749c-3e8f-482e-a610-2843da198efe.jpg)

Bro how to fix this
