### ISSUE TITLE
[BUG] texture turns black with virglrender

### ISSUE THREAD

**Issue by NethermcYT666** [PojavLauncherTeam/PojavLauncher#3959]
### Describe the bug

I managed to get pojavlauncher settings working right but the virglrender texture with tools, torches, weapons and armour are broken
Please fix this

### The log file and images/videos

![Screenshot_2023-02-18-12-38-20-67_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95992727/219816987-5200ff32-0f5f-4937-a651-1784e15b3fd4.jpg)
![Screenshot_2023-02-18-12-37-56-21_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95992727/219817014-abd49503-920f-4626-9015-e6d39e506e0c.jpg)
![Screenshot_2023-02-18-12-37-41-21_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95992727/219817025-8bb5f909-ea54-421c-945c-870215d408f6.jpg)
![Screenshot_2023-02-18-12-37-31-51_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95992727/219817035-f7cd6eb7-672d-45fd-b831-ac89b393d143.jpg)
![Screenshot_2023-02-18-12-37-06-64_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95992727/219817061-1154be68-fe03-47ec-8828-d15c3bc615d1.jpg)
![Screenshot_2023-02-18-12-36-57-07_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/95992727/219817075-4a62950f-0bd9-4506-a551-465bbc91c13a.jpg)

### Steps To Reproduce

```markdown
N/A
```

### Expected Behavior

I expect that the game textures are fixed

### Platform

```markdown
- Device model: CPH1941
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210206
```

### Anything else?

N/A

**Comment by Baobuchi** [comment]
This kind, I seem to have seen it somewhere, but I have never encountered such a thing.

**Comment by aaaapai** [comment]
> This kind, I seem to have seen it somewhere, but I have never encountered such a thing.

The version of pojav he uses is too old

**Comment by NethermcYT666** [comment]
> 

Ok I did not know that but I'm using the lastest version

**Comment by mchnjt** [comment]
> ### Describe the bug
> I managed to get pojavlauncher settings working right but the virglrender texture with tools, torches, weapons and armour are broken Please fix this

Use HGL4ES. Like, literally no one uses virgl

**Comment by NethermcYT666** [comment]
> > ### Describe the bug
> > I managed to get pojavlauncher settings working right but the virglrender texture with tools, torches, weapons and armour are broken Please fix this
> 
> Use HGL4ES. Like, literally no one uses virgl

I will give it a try. Thanks so much

**Comment by mchnjt** [comment]
> > This kind, I seem to have seen it somewhere, but I have never encountered such a thing.
> 
> The version of pojav he uses is too old

I don't think 3.3.1.1 has this
![IMG_20230218_171356](https://user-images.githubusercontent.com/83752061/219852253-b05f69de-31f4-495a-9364-e7eb2b4e07ac.jpg)

**Comment by NethermcYT666** [comment]
> > > This kind, I seem to have seen it somewhere, but I have never encountered such a thing.
> > 
> > 
> > The version of pojav he uses is too old
> 
> I don't think 3.3.1.1 has this ![IMG_20230218_171356](https://user-images.githubusercontent.com/83752061/219852253-b05f69de-31f4-495a-9364-e7eb2b4e07ac.jpg)

I made a mistake. It's not the right version I posted the right version is dahlia-260-ff1db3127-V3_openjdk
