### ISSUE TITLE
[BUG] hi, i just installed the apk Pojavlauncher and it gave me this error, I wanted to play version 1.14.4 but when I wanted to play it threw me this error, does anyone know how to fix it?

### ISSUE THREAD

**Issue by MuzsNick** [PojavLauncherTeam/PojavLauncher#396]
Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/versions/1.14.4/1.14.4.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-6YWu5DF-CAvSYPL_VpZnDQ==/lib/arm, /system/lib, /vendor/lib]]

**Comment by khanhduytran0** [comment]
1.12+ is not supported on v2.

**Comment by 0385230806** [comment]
i want to download

**Comment by 0385230806** [comment]
Load

**Comment by 0385230806** [comment]
I want to download PojavLauncher

**Comment by 0385230806** [comment]
Tôi muốn tải PojavLauncher

**Comment by 0385230806** [comment]
Kkk

**Comment by 0385230806** [comment]
Tai

**Comment by 0385230806** [comment]
PojavLauncher

**Comment by 0385230806** [comment]
Get Load

**Comment by 0385230806** [comment]
Nó

**Comment by 0385230806** [comment]
No

**Comment by 0385230806** [comment]
Hh

**Comment by 0385230806** [comment]
Hh

**Comment by 0385230806** [comment]
Vg
