### ISSUE TITLE
Game exited with code -1

### ISSUE THREAD

**Issue by averageandroidconsumer** [PojavLauncherTeam/PojavLauncher#3960]
### Describe the bug

When i load up the version 1.19.2 the game crashes with a message saying "Game exited with code -1"

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2328
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~Zac5ucW2jSdWQGC1-aF0aQ==/net.kdt.pojavlaunch-iBjuu682gDVDGR2myurk7A==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/LIBGL   (19658): Initialising gl4es
I/LIBGL   (19658): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   (19658): Using GLES 2.0 backend
I/LIBGL   (19658): loaded: libGLESv2.so
I/LIBGL   (19658): loaded: libEGL.so
I/LIBGL   (19658): Using GLES 2.0 backend
I/LIBGL   (19658): Hardware Full NPOT detected and used
I/LIBGL   (19658): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (19658): FBO are in core, and so used
I/LIBGL   (19658): PointSprite are in core, and so used
I/LIBGL   (19658): CubeMap are in core, and so used
I/LIBGL   (19658): BlendColor is in core, and so used
I/LIBGL   (19658): Blend Substract is in core, and so used
I/LIBGL   (19658): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (19658): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (19658): Extension GL_OES_mapbuffer  detected
I/LIBGL   (19658): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (19658): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (19658): Extension GL_OES_depth24  detected and used
I/LIBGL   (19658): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (19658): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (19658): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (19658): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (19658): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (19658): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (19658): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (19658): high precision float in fragment shader available and used
I/LIBGL   (19658): Max vertex attrib: 32
I/LIBGL   (19658): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (19658): Max texture size: 16383
I/LIBGL   (19658): Max Varying Vector: 31
I/LIBGL   (19658): Texture Units: 16/16 (hardware: 64), Max lights: 8, Max planes: 6
I/LIBGL   (19658): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (19658): Max Anisotropic filtering: 16
I/LIBGL   (19658): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   (19658): Hardware vendor is ARM
I/LIBGL   (19658): GLSL 300 es supported
I/LIBGL   (19658): GLSL 310 es supported and used
I/LIBGL   (19658): sRGB surface supported
I/LIBGL   (19658): EGLImage to Texture2D supported
I/LIBGL   (19658): EGLImage to RenderBuffer supported
I/LIBGL   (19658): ignore MipMap
I/LIBGL   (19658): Targeting OpenGL 2.1
I/LIBGL   (19658): NPOT texture handled in hardware
I/LIBGL   (19658): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (19658): try to use VBO
I/LIBGL   (19658): glXMakeCurrent FBO workaround enabled
I/LIBGL   (19658): FBO workaround for using binded texture enabled
I/LIBGL   (19658): glX Will try to recycle EGL Surface
I/LIBGL   (19658): Current folder is:/
I/jrelog  (19658): dlopen libgl4es_114.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  (19658): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libattach.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjsig.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjdwp.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libzip.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libsctp.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libextnet.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libinstrument.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/librmi.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/liblcms.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (19658): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  (19658): dlopen /data/app/~~Zac5ucW2jSdWQGC1-aF0aQ==/net.kdt.pojavlaunch-iBjuu682gDVDGR2myurk7A==/lib/arm64/libopenal.so success
I/jrelog  (19658): Done processing args
I/jrelog  (19658): Found JLI lib
I/jrelog  (19658): Calling JLI_Launch
[23:40:59] [main/INFO]: Building optimized datafixer
[23:41:05] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[23:41:05] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[23:41:05] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[23:41:05] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:41:08] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:155) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.11.49.jar:?]
	at efu.a(SourceFile:711) [1.19.2.jar:?]
	at efu.<init>(SourceFile:431) [1.19.2.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:205) [1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) [1.19.2.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:87) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.11.49.jar:?]
	... 6 more
[23:41:08] [Render thread/INFO]: Setting user: spyfromgta
[23:41:08] [Render thread/ERROR]: Error parsing option value  for option Text Background Opacity: Not a boolean: ""
[23:41:08] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=20012
EGLBridge: EGLDisplay=0x7750956b90, EGLSurface=0x76f0af6e10
EGLBridge: Created CTX pointer = 0x76f0af7e60
[23:41:09] [Render thread/INFO]: [STDERR]: java.lang.Exception: Trace exception
[23:41:09] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:1004)
[23:41:09] [Render thread/INFO]: [STDERR]: 	at dzu.<init>(SourceFile:107)
[23:41:09] [Render thread/INFO]: [STDERR]: 	at fah.a(SourceFile:21)
[23:41:09] [Render thread/INFO]: [STDERR]: 	at efu.<init>(SourceFile:484)
[23:41:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.a(SourceFile:205)
[23:41:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:51)
EGLBridge: Comparing: thr=20012, this=0x76f0af7e60, curr=0x0
EGLBridge: Making current on window 0x76f0af7e60 on thread 20012
EGLBridge: eglMakeCurrent() succeed!
[23:41:09] [Render thread/INFO]: [STDOUT]: 76f0af7e60
EGLBridge: Comparing: thr=20012, this=0x76f0af7e60, curr=0x76f0af7e60
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2023-02-17 23:41:11
Description: Initializing game

java.lang.RuntimeException: could not preload blit shader
	at ezl.a(SourceFile:408)
	at efu.<init>(SourceFile:631)
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)
Caused by: abe: Invalid shaders/core/blit_screen.json: Couldn't compile vertex program (Default, blit_screen) : 0:5: L0001: Storage qualifier not allowed in GLSL ES version 100
	at abe.a(SourceFile:48)
	at fad.<init>(SourceFile:200)
	at ezl.a(SourceFile:406)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, blit_screen) : 0:5: L0001: Storage qualifier not allowed in GLSL ES version 100
	at eae.b(SourceFile:69)
	at eae.a(SourceFile:51)
	at fad.a(SourceFile:238)
	at fad.<init>(SourceFile:182)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ezl.a(SourceFile:408)
	at efu.<init>(SourceFile:631)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4040673688 bytes (3853 MiB) / 4420796416 bytes (4216 MiB) up to 4420796416 bytes (4216 MiB)
	CPUs: 8
	Processor Vendor: 0x53
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x004 Stepping r0x2p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 de
viceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 6514.67
	Virtual memory used (MB): 7626.43
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 1499.60
	JVM Flags: 2 total; -Xms4214M -Xmx4214M
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x 
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2023-02-17_23.41.11-client.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x79780358a8)
process killed with signal 6 code 0xffffffff addr 0x287900004cca
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x79780358a8)
process killed with signal 6 code 0xffffffff addr 0x287900004cca

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Select version 1.19.2
3.Press play
4.Game crashed with message saying "Game exited with code -1"
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: Samsung Galaxy S20+(Exynos variant)
- CPU architecture: aarch64
- Android version: Android 13
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by mchnjt** [comment]
Outdated build, Crocus isn't supported anymore.
Download the one from Actions, and PLEASE stop using Crocus.

**Comment by GaucovyAero** [comment]
guys this is so sad ples insert hyperrofel
