### ISSUE TITLE
[F-Req] Add VGPU Back

### ISSUE THREAD

**Issue by AnikyMX** [PojavLauncherTeam/PojavLauncher#3961]
### Is this request related to a bug?

-

### Describe the request.

Please return the VGPU rendering, because this rendering can be used on cellphones with low chipsets and it is stable on Mediatek chipsets. By returning this rendering, it may be possible for players with low specifications to play stably.

### Anything else?

Hopefully added

**Comment by Pinecone6442** [comment]
which is why i use the old version

**Comment by mchnjt** [comment]
- HGL4ES supports 1.17+ now. No more patches, just grab JRE17.
- Use OptiFine and lower the game resolution.

If Minecraft's performance on your phone is ass, it's not our fault.
