### ISSUE TITLE
[BUG] Mod: Not enough items is causing the game to crash.

### ISSUE THREAD

**Issue by Seilcommand** [PojavLauncherTeam/PojavLauncher#3962]
### Describe the bug

The game(after installing the not enough items mod) crashes with Code 1

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10774201/latest.log)

### Steps To Reproduce

```markdown
1.Install Forge(1.7.10)
2.Insert the Not Enough Items Mod(1.7.10) into the mods folder
3.Open the 1.7.10 (with Forge) version
```

### Expected Behavior

I expected the game to run normally.

### Platform

```markdown
- Device model: Samsung Galaxy A20e
- CPU architecture:aarch64 
- Android version:11
- PojavLauncher version: New one(from the Play store)
```

### Anything else?

I found a similar problem with the Morph Mod

**Comment by GaucovyAero** [comment]
CodeChickenLib's download links are broken. I have uploaded the working version of it. Just unzip it and place it in .minecraft/mods/1.7.10/
[CodeChickenLib-1.7.10-1.1.3.138-universal.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/10774763/CodeChickenLib-1.7.10-1.1.3.138-universal.zip)

**Comment by Seilcommand** [comment]
It still crashes.

GaucovyAero ***@***.***> schrieb am Sa., 18. Feb. 2023, 17:54:

**Comment by GaucovyAero** [comment]
you havent sent the log, its probably not related to notenoughitems anymore
