### ISSUE TITLE
[BUG] Botany Pots

### ISSUE THREAD

**Issue by aliszr263** [PojavLauncherTeam/PojavLauncher#3963]
### Describe the bug

It cannot enter any world it gives a datapack error on only IOS Pojavlauncher. It works on android for me

### The log file and images/videos

It is a world issue it isnt a crash so idk if log is available

### Steps To Reproduce

```markdown
Use botany pots mod on 1.18.2 forge
open minecraft and try to create a world
```

### Expected Behavior

expect to world to not load.

### Platform

```markdown
- Device model: IPad Air 5th gen
- CPU architecture: 
- Android version: IOS 16.3.1
- PojavLauncher version: 
```

**Comment by GaucovyAero** [comment]
ios posts don't belong here, in the android repository
