### ISSUE TITLE
[BUG] Mystery Vendors On Devices

### ISSUE THREAD

**Issue by AnikyMX** [PojavLauncherTeam/PojavLauncher#3964]
### Describe the bug

I Don't Have Vulkan Drivers, But Have libvulkan.so And Is The lib In The Screenshot Below Rendering PojavLauncher? Is it possible to export OpenGL 4.6 Or OpenGL 4.4?

### The log file and images/videos

![IMG_20230218_235212](https://user-images.githubusercontent.com/71912870/219875498-9e39ad5c-451e-4aa0-9541-a286ea6eb6fa.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Change the Render to Zink (If the Current Version is Called Angle)
3. Enter In Game
```

### Expected Behavior

I Hope Later Can Add Render With The libMEOW Vendor

### Platform

```markdown
- Device model: Oppo A12 / CPH2083
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Version From Play Store
```

**Comment by AnikyMX** [comment]
![IMG_20230219_000316](https://user-images.githubusercontent.com/71912870/219875887-2a0cf2ab-4c71-4e0e-b302-a7cc9590c3a3.jpg)

There is libvulkan.so but the device says it doesn't support vulkan

**Comment by GaucovyAero** [comment]
thats just oppo being extremely shit, pretty sure you cant do anything about that
basically, your processor supports vulkan, but oppo's android does not (or oppo's developers have not implemented it, because they are lazy)

**Comment by AnikyMX** [comment]
Hooh
