### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by khalimwu** [PojavLauncherTeam/PojavLauncher#3965]
### Describe the bug

Crash after loader

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10774685/latest.log)

### Steps To Reproduce

```markdown
Install forge for 1.19.3 (using pojavlauncher default settings)
Copy controllable mod to mods folder
Launch
```

### Expected Behavior

Load controllable mod

### Platform

```markdown
- Device model: Xiaomi note 11 lite 5g NE
- CPU architecture: Octa-core (1x2.4 GHz Cortex-A78 & 3x2.2 GHz Cortex-A78 & 4x1.9 GHz Cortex-A55)
- Android version: android 13
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
almost all mods modifying input are going to crash the game, don't use them (they don't support android's inputs, obviously)
