### ISSUE TITLE
[BUG] unpleasant rendering effects of holy gl4es

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#3966]
### Describe the bug

In the drawing of distant objects, you can see unpleasant stripes that are even better visible when approaching. 
This can be fixed by adding gl4es 1.1.5 for versions 1.12.2-1.16.5 since gl4es 1.1.5 does not have this. 

### The log file and images/videos

https://user-images.githubusercontent.com/75908293/219884321-469cdbe3-a9d4-4cef-a2f0-e830e99b1dee.mp4

### Steps To Reproduce

```markdown
Everything as usual just chose version 1.16.5 and holy gl4es
```

### Expected Behavior

In principle, I expected such an effect from holy gl4es since it is based on gl4es 1.1.4

### Platform

```markdown
- Device model: huawei nova 9 se 
- CPU architecture: aarch64 snapdragon 680 
- Android version: emui 12 
- PojavLauncher version: latest release
```

### Anything else?

No

**Comment by Mathias-Boulay** [comment]
damn, that's a weird device specific issue if I saw one

**Comment by Iarkont** [comment]
> damn, that's a weird device specific issue if I saw one


https://user-images.githubusercontent.com/75908293/227003050-aba357e0-b215-4704-a72f-a09a6ec841db.mp4

I added GL4ES 1.1.5 to the last pojav build (more precisely replaced holy GL4ES with GL4ES 1.1.5, since I haven't figured out how to add additional renderers yet) And as you can see from the video data there is no distortion. I also noticed 1 oddity on GL4ES 1.1.5 I have more and more stable fps than on holy GL4ES, although this should not be the case.

**Comment by Mathias-Boulay** [comment]
Good to know, although the fps thing is not unexpected

**Comment by Mathias-Boulay** [comment]
@Iarkont If you are available for some testing, can you contact me through the official [pojav discord](https://discord.gg/pojavlauncher-724163890803638273) ?
It would be more handy to try and test what's wrong on your device

**Comment by Iarkont** [comment]
> @Iarkont If you are available for some testing, can you contact me through the official [pojav discord](https://discord.gg/pojavlauncher-724163890803638273) ? It would be more handy to try and test what's wrong on your device

I can, but not through voice chat, as I do not know English well and communicate through an interpreter

**Comment by Mathias-Boulay** [comment]
@Iarkont maybe this can help ? https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4661196704

**Comment by Iarkont** [comment]
> @Iarkont maybe this can help ? https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4661196704

if there was replaced gl4ES 1.1.4 with GL4ES 1.1.5 then it helped, I just had to make a clone of the application, as some files due to the new Android are not copied and I do not want to delete them. But I installed the latest build, here's even a screenshot 
![Screenshot_20230411_085336_net kdt pojavlaunch debuh](https://user-images.githubusercontent.com/75908293/231071512-1096e1f0-7c5e-40a6-ab41-3bb54f822df0.jpg)

**Comment by Iarkont** [comment]
by the way, you don't know why VirGl behaves so strangely when rendering video in replay mod? it's just that there isn't even one on gl4ES. 
The result, of course, is a normal video, but the rendering process is kind of strange, of course I could do it on GL4ES but only virgl supports shaders. 

https://user-images.githubusercontent.com/75908293/231117865-2fcf9267-ff14-4aae-9b07-1d0fede4f013.mp4

**Comment by GaucovyAero** [comment]
this flipping is kinda normal on virgl, well at least its working correctly

**Comment by Iarkont** [comment]
> this flipping is kinda normal on virgl, well at least its working correctly

so it can't be fixed? I just remember virgl flipping the game screen on newer versions and that was fixed a long time ago. if this problem is not fixable, then okay I'll put up with it.

**Comment by Calinou** [comment]
This is a phenomenon known as z-fighting, which occurs because GL4ES limits depth buffer precision to improve performance. I'm surprised it looks this bad, but maybe Minecraft itself needs to be modded to better support 16-bit depth buffers (e.g. by increasing the near plane distance and decreasing the far plane distance).

**Comment by Mathias-Boulay** [comment]
The issue can be marked as fixed since current dev builds
