### ISSUE TITLE
forge crash

### ISSUE THREAD

**Issue by mahmoud-games12** [PojavLauncherTeam/PojavLauncher#3967]
### Describe the bug

![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10775244/latestlog.txt)

I tried to install boosted fps modpack and optifine. but it still crash

### The log file and images/videos

![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10775244/latestlog.txt)

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

I expect the game launches

### Platform

```markdown
- Device model: Realme C15
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest release
```

**Comment by GaucovyAero** [comment]
don't use Chrome to download your files, thanks, use Firefox or Brave
