### ISSUE TITLE
[BUG] Holy Gl4es and virgl is broken and clouds not rendering please anyone how to fix this

### ISSUE THREAD

**Issue by LithuanianBoi41** [PojavLauncherTeam/PojavLauncher#3969]
### Describe the bug

Holygl4es and virgl render need be fixed

### The log file and images/videos

![Screenshot_2023-02-19-14-52-27-621_net kdt pojavlaunch](https://user-images.githubusercontent.com/107354928/219952914-7e1a663b-61a0-4e54-b6e0-e859cf850298.jpg)

### Steps To Reproduce

```markdown
Start Pojav Launcher
Open Game
Render problem
```

### Expected Behavior

Virgl and holy gl4es is broken need be fixed

### Platform

```markdown
- Device model: M2007J20CG
- CPU architecture: arm64_v8
- Android version: 12
- PojavLauncher version: dahlia-260-ff1db3127-v3_openjdk
```

### Anything else?

Please Pojav Team Fix Render holy gl4es and virgl 
![Screenshot_2023-02-19-14-52-27-621_net kdt pojavlaunch](https://user-images.githubusercontent.com/107354928/219952869-7efea6d6-9097-4572-8c2a-d9cba907eb8c.jpg)

**Comment by Mathias-Boulay** [comment]
Welp. Can't fix this one. That's floating point imprecision.
