### ISSUE TITLE
[BUG] Selecting a custom path outside of /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files is not possible

### ISSUE THREAD

**Issue by bbaster** [PojavLauncherTeam/PojavLauncher#3970]
### Describe the bug

Navigating outside of /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files in the file picker is not possible, so there is no way of storing game data outside of this directory.

### The log file and images/videos

![Screenshot_20230219-163939_PojavLauncher (Minecraft_ Java Edition for Android)](https://user-images.githubusercontent.com/67292925/219958468-1dfbe344-faa2-41b2-8945-233c41b8cd27.png)

### Steps To Reproduce

```markdown
1. Open Pojav Launcher
2. Select the pencil icon to edit any instance
3. Click the "Select" button next to the "Custom path" field
```

### Expected Behavior

It should be possible to navigate outside of the above mentioned directory.

### Platform

```markdown
- Device model: Xiaomi Poco X3 Pro 8/256GB
- CPU architecture: aarch64
- Android version: ArrowOS 13
- PojavLauncher version: dahlia-265-a9993d387-v3_openjdk (latest automatic release at the time of writing this)
```

### Anything else?

It would be very useful to be able to store game data somewhere else as synchronization apps such as Syncthing aren't able to access the contents of Android/data/, making auto sync of game progress impossible. 

&nbsp;

I see two ways to solve this issue:
1. Replace the in-app file picker with [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider) (I think this would be the better solution)

2. Request the "Allow access to all files" permission when user moves to the parent directory in the file picker.

**Comment by artdeell** [comment]
Won't be implemented
Replacing picker with SAF would require fully emulating file I/O because a SAF folder isn't guaranteed to ge on a file system. This will be incredibly slow and annoying.
Requesting all file access would not allow us to put updates onto Google Play, since this permission can only be used by file managers.
