### ISSUE TITLE
mouse stops working after a piriod of time

### ISSUE THREAD

**Issue by speedythehedghog** [PojavLauncherTeam/PojavLauncher#3971]
### Describe the bug

after a piriod of time the mouse will stop working and after you bress cancel on a sign you cant use the mose and with a mod sutch as first aid when t try to right click an tiem your mouse stopps woking now i did not encounter this issue in september so whatever happend please fix it, also shift clicking doesint working ither

-speedy

### The log file and images/videos

none

### Steps To Reproduce

```markdown
play on chromebook
```

### Expected Behavior

the mose stopps orking when pressing cansel on a sign and on other items, try to shift click an tiem it wont work

### Platform

```markdown
- Device model: chromebook samsung
- CPU architecture: unown
- Android version: 10+
- PojavLauncher version: newist
```

### Anything else?

nope

**Comment by GaucovyAero** [comment]
this is an issue on your side unfortunately, we also don't have a chromebook to test on - chromebooks cannot be fully supported for now
