### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by ByeCry132** [PojavLauncherTeam/PojavLauncher#3972]
### Describe the bug

in pojavlauncher the scroll button doesnt work i am using a mouse on a ipad i tried using special controls but they dont work i can provide any image or recording if needed

### The log file and images/videos

![3D477FDD-B75F-4940-8500-16BC953077A3](https://user-images.githubusercontent.com/125900365/220148066-798c6290-6069-4973-a4b1-63cb9059d099.jpeg)

### Steps To Reproduce

```markdown
?
```

### Expected Behavior

scroll button was needed to needed to work

### Platform

```markdown
- Device model: iPad 9th generation/64G
- CPU architecture: A13
- iOS version: 16.3
- PojavLauncher version: 2.1
```

**Comment by ByeCry132** [comment]
.

**Comment by GaucovyAero** [comment]
this is not the ios repository
