### ISSUE TITLE
[BUG] 1.12.2 Title screen virgl renderer bug.

### ISSUE THREAD

**Issue by Entitygamer66** [PojavLauncherTeam/PojavLauncher#3974]
### Describe the bug

When i use virgl renderer the title screen bugged out and also when i pressed any buttons,i can't access any of it,the button just stucked.The version i currently playing is 1.12.2.

### The log file and images/videos

![Screenshot_2023_0221_162647](https://user-images.githubusercontent.com/124508167/220289886-d20a1f1a-ba29-41e5-a85d-74b1b4614f8a.jpg)

### Steps To Reproduce

```markdown
1.Open the launcher.
2.Select virgl renderer.
3.Select 1.12.2 version.
4.Launch the game,then wait for the title screen.
```

### Expected Behavior

I expected it to launch properly but because of this bug,i can't.

### Platform

```markdown
- Device model: Vivo Y02s
- CPU architecture: arm64-v8a
- Android version: 12
- PojavLauncher version: dahlia-260-ff1db3127-v3_openjdk
```

### Anything else?

Is anyone can fix this annoying bug?

**Comment by ghost** [comment]
Don't use virgl renderer it's bugged use holy renderer

**Comment by Entitygamer66** [comment]
> Don't use virgl renderer it's bugged use holy renderer

I was about to use shaders,but thanks for your reply.

**Comment by ghost** [comment]
> > Don't use virgl renderer it's bugged use holy renderer
> 
> I was about to use shaders,but thanks for your reply.

You can use shaders in holy, only if it is snapdragon (device)

**Comment by GaucovyAero** [comment]
disable fast render in optifine to get virgl working, but beware that shaders wont work on your device at all as its soc is not a snapdragon

**Comment by Entitygamer66** [comment]
> > > Don't use virgl renderer it's bugged use holy renderer
> > 
> > 
> > I was about to use shaders,but thanks for your reply.
> 
> You can use shaders in holy, only if it is snapdragon (device)

Well,my processor is Mediatek Helio P35.

**Comment by GaucovyAero** [comment]
then, no shaders for you
