### ISSUE TITLE
[BUG] Error "1" Forge and many non-functional mods

### ISSUE THREAD

**Issue by TimRou4** [PojavLauncherTeam/PojavLauncher#3975]
### Describe the bug

When starting Forge and many mods, it gives an error "1".  Error on all versions of the game.  Bring back the old Pojava!!!  👿

### The log file and images/videos

![Screenshot_2023-02-20-06-59-06-170_net kdt pojavlaunch](https://user-images.githubusercontent.com/125994989/220385286-e6b1aad9-8539-4146-9f87-38a42c52c80e.jpg)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

Wanted to play with a friend in a crib with mods but not Minecraft

### Platform

```markdown
- Device model: POCO X4 PRO
- CPU architecture: Snap dragon 695
- Android version: MYAU 13
- PojavLauncher version: Last
```

### Anything else?

I am clow

**Comment by mchnjt** [comment]
whar

**Comment by GaucovyAero** [comment]
latestlog.txt where
