### ISSUE TITLE
[BUG] Problem with physical keyboard connected via USB

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#3976]
### Describe the bug

It is impossible to play through a connected physical keyboard via otg usb: walking does not work at all, the jump key works but not always, also the backspace key does not always work, in terms of mods: the "C" key that is responsible for zooming does not work (optifine is set) 
Also, foreign layouts do not work, but they are provided on the keyboard
With usb otg mouse everything is fine, it works perfectly. 

### The log file and images/videos

https://user-images.githubusercontent.com/75908293/220448326-12ff07fd-a632-4958-b5f1-4d2ae30cdda5.mp4

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. I chose version 1.16.5 fabric 
3. Connected via OTG USB keyboard and mouse 
4. Entered the local world
5. Can't walk
```

### Expected Behavior

I expected that the usb keyboard would work fully

### Platform

```markdown
- Device model: huawei nova 9 se 
- CPU architecture: aarch64 snapdragon 680 
- Android version:emui 12 
- PojavLauncher version: latest release
```

### Anything else?

Like, no.

**Comment by GaucovyAero** [comment]
this is an issue with your layout most probably, use English (US)

**Comment by Iarkont** [comment]
> 

So the keyboard supports Russian and Ukrainian, and even in other applications these layouts work, but it is in PojavLauncher that only the English layout works

**Comment by GaucovyAero** [comment]
> > 
> 
> So the keyboard supports Russian and Ukrainian, and even in other applications these layouts work, but it is in PojavLauncher that only the English layout works

uhm, that's totally normal and we can't do anything about it. the russian layout also wouldn't work on PCs

**Comment by Iarkont** [comment]
> > > 
> > 
> > 
> > So the keyboard supports Russian and Ukrainian, and even in other applications these layouts work, but it is in PojavLauncher that only the English layout works
> 
> uhm, that's totally normal and we can't do anything about it. the russian layout also wouldn't work on PCs

Yes, this is not the point, through the keyboard connected via otg usb it is not possible to walk that is, the buttons w a s d do not work and even if you reassign the walking buttons to other keys, you still can not walk. Is this due to the fact that a new android is installed on the phone?

**Comment by GaucovyAero** [comment]
definitely not because of new android, but can you walk and do stuff if you hold down CTRL?

**Comment by Iarkont** [comment]
> definitely not because of new android, but can you walk and do stuff if you hold down CTRL?

I'll try, I'll tell you

**Comment by Iarkont** [comment]
> definitely not because of new android, but can you walk and do stuff if you hold down CTRL?

Yeah, it worked. And for some reason the backspace key doesn't work.

**Comment by GaucovyAero** [comment]
> > definitely not because of new android, but can you walk and do stuff if you hold down CTRL?
> 
> Yeah, it worked. And for some reason the backspace key doesn't work.

I've heard that this can happen on some android devices, and unfortunately, you can't do anything about it, nether can we I think

**Comment by Iarkont** [comment]
> > > definitely not because of new android, but can you walk and do stuff if you hold down CTRL?
> > 
> > 
> > Yeah, it worked. And for some reason the backspace key doesn't work.
> 
> I've heard that this can happen on some android devices, and unfortunately, you can't do anything about it, nether can we I think

I found the source of the problem and a fix. The problem is that on emui 12 the drivers for the physical keyboard are a bit broken. The solution to the problem: find an application that supports a physical keyboard and select it as the main input - only after that I started the Russian layout and walking now works without holding down ctrl.

**Comment by GaucovyAero** [comment]
what app are you using to fix it tho?

**Comment by Iarkont** [comment]
> what app are you using to fix it tho?

Russian keyboard v1.6.0r97
- in the settings of this program for the physical keyboard, you need to replace the language change combination with shift+space. And when entering minecraft, select it as the main one. And since emui 12 switches layouts via ctrl+space, shift+space can not be used, but only ctrl+space (language switching)

**Comment by GaucovyAero** [comment]
thanks
