### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by enhancedrock** [PojavLauncherTeam/PojavLauncher#3977]
### Is this request related to a bug?

No

### Describe the request.

The capability to access custom path folders outside of the PojavLauncher folder

E.g: being able to set Custom Path to a folder in the Documents folder or on an external device.

### Anything else?

Thought it could be possible because of the fact PojavLauncher asks for (and atleast in my case) is granted the Storage permission.

**Comment by GaucovyAero** [comment]
impossible

**Comment by artdeell** [comment]
Won't be implemented because it will only work on android 9 or lower, which are pretty rare. Closing.
