### ISSUE TITLE
[BUG] 1.12.2 optifine menu bugs out with VirGL

### ISSUE THREAD

**Issue by Fiz2zy** [PojavLauncherTeam/PojavLauncher#3978]
### Describe the bug

When I play Minecraft on 1.12.2 forge with Optifine_HD_U_G5 using VirGL it gets a buggy menu screen where the background flickers between the normal panorama and a grey/black vertical gradient with blurry gibberish white text in the corners.

Now I would be completely fine with this, but in this state every button I press on the menu completely freezes the game. It doesn't even crash, it just stops.

### The log file and images/videos

![Screenshot_20230222-081353_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/123341610/220460045-5118da61-a2bb-4b07-853d-c3ee5215c838.jpg)
![Screenshot_20230222-081343_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/123341610/220460101-ac219391-c2e8-4fb9-92b5-a5bd8190d4f2.jpg)

### Steps To Reproduce

```markdown
1. Press play on minecraft 1.12.2
2. Bug
```

### Expected Behavior

Menu screen consistently looks like a panorama of a minecraft world and buttons function without freezing the game

### Platform

```markdown
- Device model: Galaxy A12
- CPU architecture: 
- Android version: 11
- pojav version: dahlia-260-ff1db3127-v3_openjdk
```

### Anything else?

I'm also using the following mods:
- Immersive Railroading
- Universal mod core
- Track API
And the following texture packs:
- IR American Steam Addon
(Immersive railroading reads texture packs to add more locos/rolling stock to the mod)

All mods and texture packs work as intended with Optifine off, but the menu screen breaks with it on. I would just switch renderers but Immersive Railroading requires VirGL to work. I would just play the mod without Optifine but you could probably tell how well that would go for me by looking at my device model.

This issue was open in a bug report once before, but the person having the issue in question didn't care to elaborate on how they managed to fix the problem, so I thought I'd open a report of my own.

Hopefully someone can help me out, I just wanna play with minecraft trains :(

**Comment by GaucovyAero** [comment]
disable fast render

**Comment by Fiz2zy** [comment]
> disable fast render

Thank you so much! It all works fine now :)
It's always a bit funny when it's just one little incompatible setting messing everything up
