### ISSUE TITLE
[BUG] <buttons are not displayed in not enough items mod 1.4.7>

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#3979]
### Describe the bug
bottom photo 

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

i want to be able to watch crafting things 

### Platform

```markdown
- Device model: Samsung Galaxy A52 
- CPU architecture: 
- Android version: 13
- PojavLauncher version:
```

### Anything else?

.

**Comment by Prostop194** [comment]
![Screenshot_20230222_201212_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/121510853/220649129-987fc55c-f999-4429-884a-bf2fbb9a090c.jpg)
![Screenshot_20230222_201240_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/121510853/220649147-f8ce372f-993b-42ed-ae68-612ad653c9db.jpg)
i did everything right not enough items and codechickencore inside the coremods folder

**Comment by GaucovyAero** [comment]
try pressing O or P, these buttons are used to hide the old toomanyitems

**Comment by Prostop194** [comment]
Okay

**Comment by Prostop194** [comment]
I installed I wanted to view crafting items

**Comment by Prostop194** [comment]
how to see the crafting of any thing

**Comment by GaucovyAero** [comment]
> how to see the crafting of any thing

press R on the item

**Comment by Prostop194** [comment]
I press R on the element the button does not work

**Comment by Prostop194** [comment]
and why not enough items is not displayed on the button?

**Comment by Prostop194** [comment]
> а почему на кнопке не отображается недостаточно  in fashion "not enough items"

**Comment by Prostop194** [comment]
> 

> а почему на кнопке не отображается недостаточно элементов?

in "not enough items" fashion

**Comment by GaucovyAero** [comment]
i have no idea, figure it out yourself i guess

**Comment by Prostop194** [comment]
what we are going to do

**Comment by GaucovyAero** [comment]
> what we are going to do

R works just fine on my PC

**Comment by Prostop194** [comment]
> > что мы собираемся делать
> 
> R отлично работает на моем ПК

R button not working for me
