### ISSUE TITLE
[F-Req] new Quilt client fabric based compatible support (expectation seem not functioning properly beside: forge, fabric, optifine)

### ISSUE THREAD

**Issue by vrgtics** [PojavLauncherTeam/PojavLauncher#3980]
### Is this request related to a bug?

in .jar installer I tried that when Quilt installer opened after input bar label most likely keep saying "Loading..." forever, so I think it 'might not compatible' other than forge or fabric installer

I got some log output syntex in .jar installer, might coming handy:
https://imgur.com/a/zgg1rKQ

### Describe the request.

[unsure is this a bug or a request, so I end up wrote at form 'Is this request related to a bug?' above]

**Comment by GaucovyAero** [comment]
uhm, the imgur link has expired - also, uncheck the "sandbox .jar installer" in java tweaks when installing quilt

**Comment by vrgtics** [comment]
> uhm, the imgur link has expired - also, uncheck the "sandbox .jar installer" in java tweaks when installing quilt

imgur url never expired from me ever, I checked again is here, Please Confirm Again this time just copy the imgur url text to Open New Page searching bar, NOT click in the embed

**Comment by demiswish** [comment]
You know
You can just upload the image to GitHub directly, not using imgur

**Comment by vrgtics** [comment]
![Screenshot_20230223-052831_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/99676066/221417296-749afa54-c10f-4227-9f6d-754fc51de16a.jpg)

**Comment by GaucovyAero** [comment]
disable sandbox jar installer
