### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by Komnapas** [PojavLauncherTeam/PojavLauncher#3981]
### Describe the bug

Application exited with code -1 again
![Screenshot_2023-02-24-18-51-50-376_net kdt pojavlaunch](https://user-images.githubusercontent.com/125657397/221174558-2d84a478-848f-4b6c-aa46-1c51f9e7d88e.jpg)

### The log file and images/videos

[latestlog-1.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10823818/latestlog-1.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.Create new world
3.this happen
```

### Expected Behavior

I except the game to launch 

### Platform

```markdown
-Device model :Xiaomi poco x3 nfc 6/64g
- CPU architecture: kyro 470
- Android version: 11
- PojavLauncher version: dahlia-258-cb4431 4ab-v3_openjdk
```

**Comment by Raidenxd2** [comment]
Try removing OptiFine and see if that fixes it.

**Comment by Komnapas** [comment]
> Try removing OptiFine and see if that fixes it.

If I want to increase fps, which mods can I use?

**Comment by GaucovyAero** [comment]
> > Try removing OptiFine and see if that fixes it.
> 
> If I want to increase fps, which mods can I use?

use PojavOptimize, it's pinned in #general in the [pojav](https://discord.gg/pojavlauncher) discord server

**Comment by Komnapas** [comment]
> > > Try removing OptiFine and see if that fixes it.
> > 
> > If I want to increase fps, which mods can I use?
> 
> use PojavOptimize, it's pinned in #general in the [pojav](https://discord.gg/pojavlauncher) discord server

Ok thx bro
