### ISSUE TITLE
Crash on any version

### ISSUE THREAD

**Issue by Lewyfcb9pro** [PojavLauncherTeam/PojavLauncher#3982]
### Describe the bug

Well the app completely closes after tapping on play and waiting 1-2 second

### The log file and images/videos

https://pastebin.com/zJ55g4g0

### Steps To Reproduce

```markdown
1.start Pojavlauncher
2.choose any version
3.wait until close/crash
```

### Expected Behavior

I expect the game to launch

### Platform

```markdown
- Device model: Redmi note 10 pro
- CPU architecture: ARMv8-A
- Android version: 12
- PojavLauncher version: latest by standard on gplay
```

**Comment by Mathias-Boulay** [comment]
your jvm installation is corrupted

**Comment by Mathias-Boulay** [comment]
also, you're using a jre 17 for a version which doesn't need it

**Comment by GaucovyAero** [comment]
delete internal-17 and then start up 1.17+ manually (it's going to install itself)

**Comment by Lewyfcb9pro** [comment]
oh thanks also sorry for a late response I didn't get any notification or this site would show any comments
