### ISSUE TITLE
[F-Req] A renderer that gives better fps with shader in any processor is removed. 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3984]
### Is this request related to a bug? Partially yes

Zink renderer is best. I used it with shaders and i got 60-79 fps and without shaders 120-180 fps. But Zink renderer  was removed. Please bring it back. I have Mediatek processor. Today's renderer is not effective of that type. Holy gl4es renderer crash 1.19.3 fabric sodium.
Virgl gives 1-2 fps.
Angle gives stable 50 fps but no shaders are working if shaders are not working what is the difference between mcpe and pojav (In term of shaders). 

### Describe the request.

Bring Zink renderer back.

### Anything else?

Bring Zink renderer back.
I know this is hard but please 🥺.

Sorry i was late. i deleted pojav because of college. Today I reinstalled and.....

**Comment by khanhduytran0** [comment]
Just being curious, do you have any screenshots of Zink running full-blown shader at such fps?

**Comment by ghost** [comment]
> Just being curious, do you have any screenshots of Zink running full-blown shader at such fps?

I have screenshot but i don't have screenshot of fps.

![IMG-20220429-WA0010](https://user-images.githubusercontent.com/114477116/221356152-677ff0e3-1f35-4fd8-9d9d-a51face4ae7a.jpg)
![IMG-20220429-WA0009](https://user-images.githubusercontent.com/114477116/221356155-fa17b1ec-adff-4174-8e6d-65c6cf4f7664.jpg)
![IMG-20220429-WA0008](https://user-images.githubusercontent.com/114477116/221356158-a544b9a7-a776-4e31-8bbf-e6e5fec1e009.jpg)
![IMG-20220429-WA0007](https://user-images.githubusercontent.com/114477116/221356162-5e7dcf8b-de16-4109-bbfd-5a2881da2aaf.jpg)
![IMG-20220429-WA0005](https://user-images.githubusercontent.com/114477116/221356164-38fe2e2b-a52f-4029-80be-85356ce86ea5.jpg)

**Comment by mchnjt** [comment]
> Sorry i was late. i deleted pojav because of college. Today I reinstalled and.....

Try `-Dorg.lwjgl.opengl.libname=libOSMesa_8.so` on the JVM Arguments. The libfile iirc is not removed

**Comment by ghost** [comment]
> > Sorry i was late. i deleted pojav because of college. Today I reinstalled and.....
> 
> Try `-Dorg.lwjgl.opengl.libname=libOSMesa_8.so` on the JVM Arguments. The libfile iirc is not removed

Let me try

**Comment by mchnjt** [comment]
> > Just being curious, do you have any screenshots of Zink running full-blown shader at such fps?
> 
> I have screenshot but i don't have screenshot of fps.
> 
> ![IMG-20220429-WA0010](https://user-images.githubusercontent.com/114477116/221356152-677ff0e3-1f35-4fd8-9d9d-a51face4ae7a.jpg) ![IMG-20220429-WA0009](https://user-images.githubusercontent.com/114477116/221356155-fa17b1ec-adff-4174-8e6d-65c6cf4f7664.jpg) ![IMG-20220429-WA0008](https://user-images.githubusercontent.com/114477116/221356158-a544b9a7-a776-4e31-8bbf-e6e5fec1e009.jpg) ![IMG-20220429-WA0007](https://user-images.githubusercontent.com/114477116/221356162-5e7dcf8b-de16-4109-bbfd-5a2881da2aaf.jpg) ![IMG-20220429-WA0005](https://user-images.githubusercontent.com/114477116/221356164-38fe2e2b-a52f-4029-80be-85356ce86ea5.jpg)

Please toggle the `Show FPS` on Optifine's Other Settings section.

**Comment by ghost** [comment]
> > Sorry i was late. i deleted pojav because of college. Today I reinstalled and.....
> 
> Try `-Dorg.lwjgl.opengl.libname=libOSMesa_8.so` on the JVM Arguments. The libfile iirc is not removed

But i use angle renderer can I use shaders with it.

> > > Just being curious, do you have any screenshots of Zink running full-blown shader at such fps?
> > 
> > 
> > I have screenshot but i don't have screenshot of fps.
> > ![IMG-20220429-WA0010](https://user-images.githubusercontent.com/114477116/221356152-677ff0e3-1f35-4fd8-9d9d-a51face4ae7a.jpg) ![IMG-20220429-WA0009](https://user-images.githubusercontent.com/114477116/221356155-fa17b1ec-adff-4174-8e6d-65c6cf4f7664.jpg) ![IMG-20220429-WA0008](https://user-images.githubusercontent.com/114477116/221356158-a544b9a7-a776-4e31-8bbf-e6e5fec1e009.jpg) ![IMG-20220429-WA0007](https://user-images.githubusercontent.com/114477116/221356162-5e7dcf8b-de16-4109-bbfd-5a2881da2aaf.jpg) ![IMG-20220429-WA0005](https://user-images.githubusercontent.com/114477116/221356164-38fe2e2b-a52f-4029-80be-85356ce86ea5.jpg)
> 
> Please toggle the `Show FPS` on Optifine's Other Settings section.

That screenshot is old when pojav has zink renderer when 1.18 was released.

**Comment by mchnjt** [comment]
> > > Sorry i was late. i deleted pojav because of college. Today I reinstalled and.....
> > 
> > 
> > Try `-Dorg.lwjgl.opengl.libname=libOSMesa_8.so` on the JVM Arguments. The libfile iirc is not removed
> 
> But i use angle renderer can I use
> 
JVM Arguments overrides flags that causes ANGLE to load (i think)

**Comment by khanhduytran0** [comment]
> The libfile iirc is not removed

But the file content is different. You’re wrong. It does not contain Zink code anymore.

**Comment by mchnjt** [comment]
> > The libfile iirc is not removed
> 
> But the file content is different. You’re wrong. It does not contain Zink code anymore.

~~Oh~~

**Comment by mchnjt** [comment]
defo should've said to add back the original lib then via APK editing

**Comment by ghost** [comment]
Let's keep this open till that old Zink comes back.

**Comment by ghost** [comment]
> > Sorry i was late. i deleted pojav because of college. Today I reinstalled and.....
> 
> Try `-Dorg.lwjgl.opengl.libname=libOSMesa_8.so` on the JVM Arguments. The libfile iirc is not removed

I tried this and i got 1-7 fps when i joined world after sometime i got 37-41 fps in Virgl without shaders.
