### ISSUE TITLE
my game crash when i wanna play

### ISSUE THREAD

**Issue by Gustawo7** [PojavLauncherTeam/PojavLauncher#3985]
### Describe the bug

everytime i try to start minecraft it crashes the game. 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10831120/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10831127/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. click play button
3. crash the game
```

### Expected Behavior

i expect the game to launch

### Platform

```markdown
- Device model: poco x3pro 
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: newest from google play
```

**Comment by demiswish** [comment]
Is your JRE17 installation corrupted..?

**Comment by artdeell** [comment]
No. He installed jdk instead of jre.

**Comment by Gustawo7** [comment]
guys I installed jre a while ago and my game crashes again because of Code 1
![Screenshot_2023-02-25-13-47-13-531_net kdt pojavlaunch](https://user-images.githubusercontent.com/126330213/221357586-ebc22fe2-a999-447d-9606-c7cab73ca333.jpg)
[latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10831168/latestlog.1.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 260 - v3_openjdk |
| Minecraft version | 1.19.3 - VANILLA |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | EXTERNAL - JRE - 17 |
| Java arguments |  |



|Errors Found: |
|--|
| java.runtime.wrong.source |

**Comment by mchnjt** [comment]
> guys I installed jre a while ago and my game crashes again because of Code 1 ![Screenshot_2023-02-25-13-47-13-531_net kdt pojavlaunch](https://user-images.githubusercontent.com/126330213/221357586-ebc22fe2-a999-447d-9606-c7cab73ca333.jpg) [latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10831168/latestlog.1.txt)

Did the extraction said something like `File should end in .tar.xz`?

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 260 - v3_openjdk |
| Minecraft version | 1.19.3 - VANILLA |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | EXTERNAL - JRE - 17 |
| Java arguments |  |



|Errors Found: |
|--|
| java.runtime.wrong.source |

**Comment by mchnjt** [comment]
yeah i get your point serpent

**Comment by Gustawo7** [comment]
i fix that just install good runtime
