### ISSUE TITLE
Fabric Loader Crash

### ISSUE THREAD

**Issue by illiahryn11** [PojavLauncherTeam/PojavLauncher#3992]
### Describe the bug

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

ERROR: Unable to get more log.
Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment, -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader, --add-exports=java.desktop/java.awt=ALL-UNNAMED, --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED, --add-exports=java.desktop/sun.java2d=ALL-UNNAMED, --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED, --add-exports=java.desktop/sun.awt=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED, --add-exports=java.desktop/sun.font=ALL-UNNAMED, --add-exports=java.base/sun.security.action=ALL-UNNAMED, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.desktop/java.awt=ALL-UNNAMED, --add-opens=java.desktop/sun.font=ALL-UNNAMED, --add-opens=java.desktop/sun.java2d=ALL-UNNAMED, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.base/java.net=ALL-UNNAMED, -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/fabric-installer-0.11.1 (1).jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2341
Added custom env: POJAV_NATIVEDIR=/data/app/~~61i185qZk_FIGcMRQqnoSQ==/net.kdt.pojavlaunch-gHwa6ga4UoM8bhF3PhRoPQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~61i185qZk_FIGcMRQqnoSQ==/net.kdt.pojavlaunch-gHwa6ga4UoM8bhF3PhRoPQ==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

The log; im was trying open fabric loader and crashed woth code 1

### The log file and images/videos

Ugh

### Steps To Reproduce

```markdown
1. Open jar
2. Fabric loader 0.11.1
3. Crashed with code 1
```

### Expected Behavior

I didn't expect that.

### Platform

```markdown
- Device model: Vivo y31
- CPU architecture: x64
- Android version: 12
- PojavLauncher version: latest on google pkay
```

### Anything else?

I don't know what write here

**Comment by illiahryn11** [comment]
Oh, some words are not correct...

**Comment by GaucovyAero** [comment]
1. don't use java 17
2. rotate your screen into landscape mode before launching the jar installer

**Comment by illiahryn11** [comment]
Ok
