### ISSUE TITLE
Instant Crash when Launching Minecraft

### ISSUE THREAD

**Issue by Ella594YT** [PojavLauncherTeam/PojavLauncher#3993]
### Describe the bug

I recently bought this LG G Pro 2 so i can play pojavlauncher with my sister but bruh it crashes when i launch Minecraft itself in any version

Here's what i tried to fix it:

Changing every renderer as possible
Switching jre 8 to 17
Changing my RAM allocated to 300
Removing the Java Arguments

Nothing was fixed. Pls any solution?

Phone: LG G Pro 2 ( D838 ) Android 5

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10834376/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Select Any Version of Minecraft
3. Play the game and crash
```

### Expected Behavior

Expected the game to launch but nope

### Platform

```markdown
- Device model: LG G Pro 2
- CPU architecture: aarch32
- Android version: 5.0.1
- PojavLauncher version: dahlia-271-98a098a39v3_openjdk
```

**Comment by GaucovyAero** [comment]
for java 17, you need at least android 6

**Comment by Ella594YT** [comment]
> for java 17, you need at least android 6
Then why java 8 still crashes Minecraft then?

**Comment by GaucovyAero** [comment]
> for java 17, you need at least android 6
> Then why java 8 still crashes Minecraft then?

you haven't sent a log with it tho

**Comment by Ella594YT** [comment]
> > for java 17, you need at least android 6
> > Then why java 8 still crashes Minecraft then?
> 
> you haven't sent a log with it tho

Here a new log trying to launch Minecraft 1.9 with jre8

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10834511/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | dahlia - 271 - v3_openjdk |
| Minecraft version | 1.9 - VANILLA |
| Renderer | GL4ES_114 |
| Architecture | ARM_32 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by GaucovyAero** [comment]
> > > for java 17, you need at least android 6
> > > Then why java 8 still crashes Minecraft then?
> > 
> > 
> > you haven't sent a log with it tho
> 
> Here a new log trying to launch Minecraft 1.9 with jre8
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10834511/latestlog.txt)

you didn't select gl4es as your renderer

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | dahlia - 271 - v3_openjdk |
| Minecraft version | 1.9 - VANILLA |
| Renderer | GL4ES_114 |
| Architecture | ARM_32 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by GaucovyAero** [comment]
@Ella594YT just wanna clarify, virgl does not work on aarch32
