### ISSUE TITLE
[BUG] NullPointerException at versions 1.5.2 and below

### ISSUE THREAD

**Issue by oxota74** [PojavLauncherTeam/PojavLauncher#3994]
### Describe the bug

NullPointerException in end of log

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10834680/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch Minecraft 1.5.2 and below
```

### Expected Behavior

1. Working Minecraft

### Platform

```markdown
- Device model: Redmi K30 Ultra M2006J10C 6/128
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-271-98a098a39-v3_openjdk
```

### Anything else?

Previosly, version 1.5.2, even vanilla, even forge, worked every other time, sometimes a NullPointerException exception popped up, sometimes it was run (it turned out to be fixed by running another version above, then the 1.5.2 version). Now he doesn't want to start at all

**Comment by GaucovyAero** [comment]
delete options.txt

**Comment by oxota74** [comment]
ah, i got it, that's why it was launched every other time, thank you very much
