### ISSUE TITLE
[BUG] UI BUG

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#3995]
### Describe the bug

Edit Panel Stay

### The log file and images/videos

https://user-images.githubusercontent.com/89151134/221477166-4e462b9e-01de-402c-9ad7-3b7ce1f37932.mp4

### Steps To Reproduce

```markdown
1. Custom Control Button 
2. Click a button at random
3. Click on any area
4.bug
```

### Expected Behavior

Fix it.

### Platform

```markdown
- Device model: iqoo neo6
- CPU architecture: 8Gen1
- Android version: 13
- PojavLauncher version: dahlia-267-79af2ffd0-v3_openjdk
```

### Anything else?

I didn't find this bug, someone else did. This bug didn't happen on my phone, but it did happen on his phone, every time.

**Comment by Dawimpy** [comment]
Just tap the back button
