### ISSUE TITLE
[BUG] <Crashes With Impact 1.16.5>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#3996]
### Describe the bug

I don't know why it crashes but i can upload log file.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10840189/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start Launcher
2.Press Play Button
```

### Expected Behavior

I was waiting for the game to open.

### Platform

```markdown
- Device model: Samsung Galaxy M33 5G
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
looks like your jar is corrupted, download the jar with firefox and try again
