### ISSUE TITLE
Better idea for Pojav v3

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#4]
I thinked about it yesterday: the better idea for Pojav v3 is to create a separate branch with LWJGL 3-compartibble launcher.

SO:
PojavLaunchers with versions like 2.x.x will emulate LWJGL 2.
PojavLaunchers with versions like 3.x.x will emulate LWJGL 3.
Good idea?

Also, for an inspiration, you can check the Boardwalk's LWJGL 3 code.

**Comment by khanhduytran0** [comment]
Boardwalk 2.0 is not working, you can try as your own. Find zhuowei/Boardwalk find some issues you will get the APK.

**Comment by abdo-A028** [comment]
Try to see java script and fix it

**Comment by khanhduytran0** [comment]
My device didn't support Boardwalk2, also Android-x86 with libhoudini cause an error when trying to run.
EDIT: @abdo-A028 I received your comment in Youtube

**Comment by artdeell** [comment]
In my issue on Boardwalk you can see, the LWJGL 3 renderer of Boardwalk is partially working. Issue name: Use Gl4Es instead of GLShim.

**Comment by khanhduytran0** [comment]
I made Boardwalk2 use GL4ES. Not tested because any devices were not supported. https://drive.google.com/file/d/12Ro2CwGc-OODJKYah9aUzf8D4aw_zVNQ/view?usp=drivesdk
PojavLauncher 2.4.2preview3 shared to you.

**Comment by khanhduytran0** [comment]
@abdo-A028 you said in the comment that not working for you. Do you want access to preview or keeping `bad` char?
