### ISSUE TITLE
Error while loading on Xiaomi Mi A2 Android 10

### ISSUE THREAD

**Issue by Tom1390** [PojavLauncherTeam/PojavLauncher#40]
Even after increasing max DX it still doesn't work and brings up this error code:

java.lang.RuntimeException: Unable to convert library org.lwjgl:lwjgl:3.2.1
processing archive /storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/INDEX.LIST...
writing META-INF/INDEX.LIST; size 554...
processing META-INF/MANIFEST.MF...
processing META-INF/versions/...
writing META-INF/versions/; size 0...
processing META-INF/versions/10/...
writing META-INF/versions/10/; size 0...
processing META-INF/versions/10/org/...
writing META-INF/versions/10/org/; size 0...
processing META-INF/versions/10/org/lwjgl/...
writing META-INF/versions/10/org/lwjgl/; size 0...
processing META-INF/versions/10/org/lwjgl/system/...
writing META-INF/versions/10/org/lwjgl/system/; size 0...
processing META-INF/versions/10/org/lwjgl/system/MathUtil.class...

PARSE ERROR:
unsupported class file version 54.0
...while parsing META-INF/versions/10/org/lwjgl/system/MathUtil.class
1 error; aborting
Exiting with code 1

**Comment by artdeell** [comment]
org.lwjgl:lwjgl:3.2.1
Did you know, that all game versions that use lwjgl 3 is not working?
Also, it will not be supported, because Java 10 contains too new feature set for Android.
And multidoj16 doesn't support Java 10 classes.

**Comment by artdeell** [comment]
Guessing you're launched something like 1.13-1.15, yes?
If you want to play new versions, you're need to wait for Boardwalk 2 to be fixed.

**Comment by Tom1390** [comment]
Kool thank you
