### ISSUE TITLE
[BUG] world crashes with DistantHorizons mod

### ISSUE THREAD

**Issue by kingbuben2007** [PojavLauncherTeam/PojavLauncher#4000]
### Describe the bug

Can't open any worlds with distant horizons mod. Game crashes after «Loading terrain» screen and shows error code -1. Forge with no mods and vanilla work fine. Tried to use different java runtimes and graphic renderers, tried to download the mod from different sites. Even tried to set all mod's settings to the minimum to run as fast as possible.

1.19.3-forge-44.1.20 and DistantHorizons 1.6.10a.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10850505/latestlog.txt)

### Steps To Reproduce

```markdown
When DistantHorizons is active
1. Start Minecraft
2. Singleplayer
3. Choose or create a new world and start it
4. Loading screen
5. Joining world screen
6. Loading terrain screen
7. It crashes
```

### Expected Behavior

I expected the world to open

### Platform

```markdown
- Device model: Black Shark 5 8/128
- CPU architecture: arm64
- Android version: joyui13 (aka miui 13)
- PojavLauncher version: dahila-260-ff1db3127-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
#1948 moment
