### ISSUE TITLE
[BUG] <black screen when launching forge 1.3.2 >

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#4001]
### Describe the bug

I do everything  Right  I go to forge 1.3.2 endless black screen 

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

waiting for zaruska 

### Platform

```markdown
- Device model: Samsung Galaxy A52 
- CPU architecture: 
- Android version:13 
- PojavLauncher version:
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
use the jsons from here https://www.mediafire.com/file/x46gqv0pf2rtw02/PojavLauncher_Forge_1.3.2-1.7.2_Patchpack_v1.1.zip/file
