### ISSUE TITLE
[BUG] <UI not scaled properly>

### ISSUE THREAD

**Issue by IncludedBerry11** [PojavLauncherTeam/PojavLauncher#4002]
### Describe the bug

UI is not scaled properly (its offset) it is more noticable when using mouse

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1: Start Pojav Launcher on the playstore update Feb 12 2023
2: Start minecraft 1.12.2 (idk if this issue occurs on any other version)
3: Use Virtual mouse and go to the edges of the button (you may notice the ui is offset)
```

### Expected Behavior

.

### Platform

```markdown
- Device model: vivo 1811
- CPU architecture: 64
- Android version: 8.1.0
- PojavLauncher version: dahlia-260-ff1db3127-v3_openjdk
```

### Anything else?

.

**Comment by mchnjt** [comment]
wha
you didn't provide a screenshot, how can you prove that this bug exists

**Comment by GaucovyAero** [comment]
> wha you didn't provide a screenshot, how can you prove that this bug exists

its the frikkin notch on android 8.1 and lower, we cannot do anything about that unfortunately, only android 9 and higher has notch detection support
