### ISSUE TITLE
[BUG] when i play the survival test i get small screen

### ISSUE THREAD

**Issue by reynalz0** [PojavLauncherTeam/PojavLauncher#4003]
### Describe the bug

![Screenshot_20230302_231455_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/126856609/222655815-ac73d3cf-b592-49b6-939e-da278dd6af02.jpg)
See

### The log file and images/videos

Can you please help me and if any one has the same problem 

### Steps To Reproduce

```markdown

```

### Expected Behavior

Hope l can fix iy

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version
- PojavLauncher version: latest 
```

**Comment by GaucovyAero** [comment]
turn down your resolution scale to 45% if 1080p, or 70% if 720p, we can't do anything about this issue
