### ISSUE TITLE
Forge and RAM

### ISSUE THREAD

**Issue by N1993RBlackHole** [PojavLauncherTeam/PojavLauncher#4004]
### Describe the bug

when I log into forge with a large allocated amount of RAM (1000Mb) and with the "ic2" mod installed, the game immediately crashes with error code 1. when I insert a smaller RAM allocation (600~700Mb), it will be able to enter the game, but when I launch any world, then the game just crashes without any or mistakes, FPS 30. The mods used are: "ic2, optifine, jei" versions 1.12.2, the latest version of mods, the forge is old because on the new one it is not even included in the game. I tested it several times and the world loads in 20% of cases, the rest crashes, the world loads for 4 minutes. I noticed that it crashes because of ic2. device Redmi 9C 2/32, 32 bit. the latest version of the game pojavlauncher. Yandex translation

### The log file and images/videos

[crash-2023-03-03_09.34.15-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10879201/crash-2023-03-03_09.34.15-client.txt)

### Steps To Reproduce

```markdown
Start the game with Forge, waiting for 4 minutes, press play, any world starts at 20%.
```

### Expected Behavior

I expected the world to start but started at 20% 

### Platform

```markdown
- Device model: Redmi 9C 2/32
- CPU architecture: aarch32
- Android version: 10
- PojavLauncher version: latest
```

**Comment by artdeell** [comment]
Latestlog.txt when dtarting and not staring not attached. Please attach.

**Comment by artdeell** [comment]
Your actual issue isthat you use anglr on 1.12.2 - it never supported anything lower than 1.17, and it's a miracle that it somehow started.

**Comment by N1993RBlackHole** [comment]
I'm sorry about t I tested and sent another mistake. But I have great news I found how to fix the flight error when entering the world with mod
1. Enable MIUI screen recording
2.come into the world
3.wait and then the screen recording automatically will fly out but! the game did not fly and you entered the world! I experimented with it and learned that this method is irresponsible!!! there were no departure cases except departure departure app MIUI screen recording

**Comment by N1993RBlackHole** [comment]
Only that is unclear why the game flies, can you so specially done?

**Comment by GaucovyAero** [comment]
uhm, just, reduce your ram allocation to 500MB or something, maybe lower.

**Comment by N1993RBlackHole** [comment]
Why did you close this problem because this fich will be very useful for MIUI owners

**Comment by N1993RBlackHole** [comment]
If all words translated Yandex
