### ISSUE TITLE
Gabisa masuk server

### ISSUE THREAD

**Issue by tantraagustinus20com** [PojavLauncherTeam/PojavLauncher#4005]
### Describe the bug

Xhdhdhd

### The log file and images/videos

 Xv

### Steps To Reproduce

```markdown
Xvd
```

### Expected Behavior

 Xbs

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 19.

- PojavLauncher version: 
Svsvbs
```

**Comment by artdeell** [comment]
invalid info

**Comment by RadiatedExodus** [comment]
Seperti yang dibilang @artdeell, tolong tambah informasi lebih lanjut dan fill formnya sampai selesai, soalnya kalau tidak anda lakukan ya kita tidak bisa bantu
