### ISSUE TITLE
[BUG] Unable to open graphics settings with sodium extra & unable to find the "Compact vertex format" setting

### ISSUE THREAD

**Issue by oxota74** [PojavLauncherTeam/PojavLauncher#4007]
### Describe the bug

1. I can't go into the graphics settings, nothing happens, just a button is pressed and that's it (only with sodium extra). Sodium and Sodium common settings itself works without Extra.
1. I can't find "Compact vertex format", which is why I can't use holy gl4es (much more stable - 120 fps in void superflat)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10883450/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install Sodium, Sodium Extra and Reese's Sodium Options
2. Start PojavLauncher
3. Try to open Graphics settings
```

### Expected Behavior

Working graphics settings

### Platform

```markdown
- Device model: Redmi K30 Ultra M2006J10C
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-271-98a098a39-v3_openjdk
```

**Comment by artdeell** [comment]
You need to use the [sodium patcher](https://cdn.discordapp.com/attachments/824307242533781514/1048890510846214195/pojavpatcher-1.0.1-SNAPSHOT.jar) to use sodium versions newer than 0.1.0

**Comment by GaucovyAero** [comment]
> You need to use the [sodium patcher](https://cdn.discordapp.com/attachments/824307242533781514/1048890510846214195/pojavpatcher-1.0.1-SNAPSHOT.jar) to use sodium versions newer than 0.1.0

btw, 0.2.0 cant be patched by the patcher, since the config arguments are not same, maybe i should try fixing it rn

**Comment by oxota74** [comment]
> You need to use the [sodium patcher](https://cdn.discordapp.com/attachments/824307242533781514/1048890510846214195/pojavpatcher-1.0.1-SNAPSHOT.jar) to use sodium versions newer than 0.1.0

This only helps if it is manually extracted from the ".jar" file two ".properties" files in the "config" folder. Thanks!

![Screenshot_2023-03-03-18-50-59-817_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87602646/222766011-b5157954-25ff-46a6-bbb5-60a2f7bb5630.jpg)
