### ISSUE TITLE
Support keyboard and mouse !

### ISSUE THREAD

**Issue by Mikar9** [PojavLauncherTeam/PojavLauncher#401]
I have keyboard and mouse i want to play with its. Pls support keyboard and mouse, it's very good for me

**Comment by khanhduytran0** [comment]
It was already supported.

**Comment by Mikar9** [comment]
Pojavlauncher v3.2 can support 32 bit ?

Vào 16:25, T.5, 19 Th11, 2020 Tran Khanh Duy <notifications@github.com> đã
viết:

**Comment by khanhduytran0** [comment]
Yep
