### ISSUE TITLE
[BUG] Unknown error when entering the server

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#4012]
### Describe the bug

Crashes when entering the server using 1.19.2Fabric (including mods), and the crash report shows an unknown error

### The log file and images/videos

> 
[crash-2023-03-04_13.48.52-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10887573/crash-2023-03-04_13.48.52-client.txt)

### Steps To Reproduce

```markdown
1.Launch the latest Pojav beta
2.Start 1.19.2Fabric.
3.Join the server
```

### Expected Behavior

I hope to get a fix or get help

### Platform

```markdown
- Device model: Huawei 8/128G
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: Move every variable to Environ
```

**Comment by GaucovyAero** [comment]
patch your sodium please
