### ISSUE TITLE
Glitch texture bug

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4013]
### Describe the bug

Glitching texture on VirGl Render 1.18.2

### The log file and images/videos

![Screenshot_20230305-083245](https://user-images.githubusercontent.com/76839710/222935271-18215eae-16aa-4b74-b990-8a7d0a432405.png)

Glitch texture 

### Steps To Reproduce

```markdown
1. Start Modpacks
2. Start the game
3. Glitch texture
```

### Expected Behavior

No bug

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

VirGl Render have glitch texture

Angle render no texture bug

Am using Modpacks some mods need graphics like shader that why am using VirGl Render. in angle Render crash the game some mods not supported on this render can you fix VirGl texture like angle. only problem is texture glitch on VirGl Render

**Comment by VenomousSteam81** [comment]
Not sure if this could be fixed. Ofc im noy a dev so i dont actually know. Just replying my opinion tbh

**Comment by GaucovyAero** [comment]
This is your phone going out of GPU memory. There's nothing wrong with the renderer itself.

**Comment by kedrick021** [comment]
> This is your phone going out of GPU memory. There's nothing wrong with the renderer itself.

What on VirGl Render bug using create mod angle Render no texture bug
