### ISSUE TITLE
[BUG] Why can't my phone download JAVA17 automatically?

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#4014]
### Describe the bug

There is no description

### The log file and images/videos

![Screenshot_20230305_151730_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/100058929/222947235-77bedd63-14eb-4b99-93ac-110ec8613943.jpg)

### Steps To Reproduce

```markdown
no
```

### Expected Behavior

I want to get help

### Platform

```markdown
- Device model: Huawei 8/128G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest beta version
```

**Comment by artdeell** [comment]
It's unpacked only when you run a version that actually requires it
