### ISSUE TITLE
Game crashed when launching fabric 1.16.3

### ISSUE THREAD

**Issue by BLACKoDEMON** [PojavLauncherTeam/PojavLauncher#4015]
### Describe the bug

I use fabric 1.16.3 with fabric api and meteor client it says game crashed with code - 1 and crashes

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10891350/latestlog.txt)

### Steps To Reproduce

```markdown
N/A
```

### Expected Behavior

I expected the game to be launched 

### Platform

```markdown
- Device model: redmi 9i 4/128G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest version
```

### Anything else?

N/A

**Comment by GaucovyAero** [comment]
make sure all of your mods are compatible with 1.16.3

**Comment by UGArya** [comment]
Bro my game crashes when I install fabric

**Comment by GaucovyAero** [comment]
> Bro my game crashes when I install fabric

you have 1.16.5 mods installed

**Comment by Mathias-Boulay** [comment]
Stale issue, the dude probably downloaded the proper mods by now
