### ISSUE TITLE
Create mod 1.18.2 texture bug using VirGl Render 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4016]
### Describe the bug

Create mod have texture bug using VirGl Render 

### The log file and images/videos

![Screenshot_20230305-201927](https://user-images.githubusercontent.com/76839710/222960682-f48446d6-0e40-49b0-adf5-0b7bd633b791.png)
VirGl Render

![Screenshot_20230305-202641](https://user-images.githubusercontent.com/76839710/222960690-841df836-e9bc-40a8-b4f3-2a93fd529244.png)
Angle Render 

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10891821/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the game
2. Texture bug on create mod using VirGl Render
```

### Expected Behavior

No bug on VirGl Render 

### Platform

```markdown
- Device model: umidigi bison 6/125
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Plss help fix the create mod texture bug

**Comment by Mathias-Boulay** [comment]
Virgl is not officially supported by the team
(Also #1948)

**Comment by kedrick021** [comment]
> Virgl is not officially supported by the team (Also #1948)

Noo I only use VirGl Render because Modpacks work angle Render are not working can you help? I send logs. Using angle Render
