### ISSUE TITLE
just asking does anyone know what mods to remove in atm6 modpack to make it load?

### ISSUE THREAD

**Issue by jackyleo1234** [PojavLauncherTeam/PojavLauncher#4017]

**Comment by GaucovyAero** [comment]
send logs moment

**Comment by jackyleo1234** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10893010/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 260 - v3_openjdk |
| Minecraft version | 1.16.5-forge-36.2.39 - FORGE |
| Renderer | HOLY_GL4ES_114 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by jackyleo1234** [comment]
?

**Comment by jackyleo1234** [comment]
heres my crash report too

**Comment by jackyleo1234** [comment]
[crash-2023-03-05_14.39.22-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10893019/crash-2023-03-05_14.39.22-client.txt)

**Comment by jackyleo1234** [comment]
what do i do

**Comment by TarikBR** [comment]
> [crash-2023-03-05_14.39.22-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10893019/crash-2023-03-05_14.39.22-client.txt)

maybe kubjs mods, like:
- kubejs-immersive-engineering-1605.1.2-build.28.jar
- kubejs-blood-magic-1605.1.1-build.3.jar
- kubejs-mekanism-1605.1.2-build.2.jar
- kubejs-create-1605.1.4-build.12.jar
- kubejs-thermal-1605.1.4-build.4.jar
- kubejs-forge-1605.3.19-build.299.jar

but idk what happens with modpack without these mods
