### ISSUE TITLE
what mods to i remove for atm6 modpack to load?

### ISSUE THREAD

**Issue by jackyleo1234** [PojavLauncherTeam/PojavLauncher#4018]
### Describe the bug

its crashing when starting the game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10893005/latestlog.txt)

### Steps To Reproduce

```markdown
unknown
```

### Expected Behavior

i was hoping it would load so me and my friend could play together

### Platform

```markdown
- Device model: chrome os
- CPU architecture: unknown
- Android version: Version 112.0.5594.0
- PojavLauncher version: dahlia-260-ff1db3127-v3_openjdk
```

**Comment by GaucovyAero** [comment]
you need android 10 and higher to run it

**Comment by jackyleo1234** [comment]
is there a way for me to know if i have the right device version

**Comment by jackyleo1234** [comment]
can i run modpacks like vault hunters,rlcraft,insane craft, or better mc? because me and my friend been wanting to play minecraft with modpacks but it hasn't been working so he been feeling down so i really want to cheer him up

**Comment by GaucovyAero** [comment]
> can i run modpacks like vault hunters,rlcraft,insane craft, or better mc? because me and my friend been wanting to play minecraft with modpacks but it hasn't been working so he been feeling down so i really want to cheer him up

i mean i know what's the issue, it's just that the devs haven't fixed it yet

**Comment by jackyleo1234** [comment]
but do you think that one of the mod packs i metioned will work on my device or will they crash or is there mods i have to delete for them to work?

**Comment by jackyleo1234** [comment]
cause im still kinda new to this while your a pro at it

**Comment by GaucovyAero** [comment]
> but do you think that one of the mod packs i metioned will work on my device or will they crash or is there mods i have to delete for them to work?

it depends, im not a living encyclopedia to know which mod does and which mod doesnt work

**Comment by jackyleo1234** [comment]
actually i have this that also crashed

**Comment by jackyleo1234** [comment]
[crash-2023-03-06_12.43.58-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10902004/crash-2023-03-06_12.43.58-client.txt)

**Comment by GaucovyAero** [comment]
> [crash-2023-03-06_12.43.58-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10902004/crash-2023-03-06_12.43.58-client.txt)

wrong log, send latestlog.txt

**Comment by jackyleo1234** [comment]
oh sorry

**Comment by jackyleo1234** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10902010/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 260 - v3_openjdk |
| Minecraft version | 1.16.5-forge-36.2.33 - FORGE |
| Renderer | HOLY_GL4ES_114 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by jackyleo1234** [comment]
im just so confused i tried alot of things so it wouldn't crash but nothing worked

**Comment by jackyleo1234** [comment]
so is it a mod

**Comment by GaucovyAero** [comment]
> so is it a mod

update to the latest pojav actions build, should help in this case

**Comment by GaucovyAero** [comment]
just click on actions here on github, download app-debug, extract it, install app-debug.apk

**Comment by jackyleo1234** [comment]
ok

**Comment by jackyleo1234** [comment]
i pressed actions but where is app debug

**Comment by jackyleo1234** [comment]
i have lunix

**Comment by Mathias-Boulay** [comment]
#1948
