### ISSUE TITLE
worst community ever they think they everything but you guys aint [BUG]

### ISSUE THREAD

**Issue by brucekikkert** [PojavLauncherTeam/PojavLauncher#402]
you cant even help people like me why bothering to skip those pople
suck a cock and fuck your mom

**Comment by artdeell** [comment]
Yo, i vet he expected us to cry and say that we want him back probably

**Comment by khanhduytran0** [comment]
Also he says on last issue
> refactor your code because it works like sh*t i dont even got a log.

Stpd kid who can't get the log and says as always not respect to other.
