### ISSUE TITLE
Angle Render for 1.16

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4021]
### Is this request related to a bug?

Yes 1.16.5 create mod have texture glitch only angle Render no texture bug but only for 1.17

### Describe the request.

1.16 angle Render for create mod to work properly without bug

### Anything else?

Plss read

**Comment by kedrick021** [comment]
Complete? Angle render work on 1.16?

**Comment by NotAHero04** [comment]
Stop requesting nonsense and learn some code.
