### ISSUE TITLE
[BUG] why web display mod white screen.

### ISSUE THREAD

**Issue by Forever2397** [PojavLauncherTeam/PojavLauncher#4023]
### Describe the bug

![Screenshot_2023-03-08-20-43-11-18_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/85401948/223732359-f53405ab-ba07-4c71-9d59-17ac1296e423.jpg)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10921278/latestlog.txt)

Why is the web display mod missing a patch in pojavlauncher

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
```

### Expected Behavior

I Hope Game Launch

### Platform

```markdown
- Device model:Samsung A52
- CPU architecture:aarch64  
- Android version:12
- PojavLauncher version:latest Build
```

**Comment by GaucovyAero** [comment]
the mod just likely does not support android

**Comment by Forever2397** [comment]
but why??

**Comment by GaucovyAero** [comment]
> but why??

ask their devs, not us

**Comment by khanhduytran0** [comment]
@Forever2397 the backend web engine (Chromium) is just not compiled for Android. If you ask us to compile it, be aware that it takes up to days just to setup and compile, plus it is huge in size, so it’s not worth it.

**Comment by Forever2397** [comment]
yes i understand that but thank you so much for answering my comment

**Comment by Forever2397** [comment]
but what about mods like: Create mods
                                             : Physics mods
Is it supported on pojavlauncher?

**Comment by Gaanbiktimi** [comment]
compile and send it here please

**Comment by Gaanbiktimi** [comment]
compile and send it here please
(Скомпилируйте и отправьте сюда пожалуйста)

**Comment by GaucovyAero** [comment]
you will have to do it yourself unfortunately :/

**Comment by Forever2397** [comment]
do you have the patch?

**Comment by Forever2397** [comment]
> you will have to do it yourself unfortunately :/

do you have the patch?
