### ISSUE TITLE
Render thread

### ISSUE THREAD

**Issue by Apiz05** [PojavLauncherTeam/PojavLauncher#4026]
### Describe the bug

the app crashed after loading mods

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10926627/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojav launcher
2. run forge 1.19.2 
3. after loading the mojang crashed
```

### Expected Behavior

i expect that it will run and open the game

### Platform

```markdown
- Device model: Huawei tablet BAH3-W59
- CPU architecture: HUAWEI Kirin 820
- Android version: not android it = HarmonyOS 2.0.0
- PojavLauncher version: dahlia-260-ff1db3127-v3openjdk(9939012)
```

**Comment by GaucovyAero** [comment]
update to the latest GitHub actions build

**Comment by Mathias-Boulay** [comment]
#1948
