### ISSUE TITLE
[BUG] <Modpack Crash>

### ISSUE THREAD

**Issue by Hadbrinenotcool** [PojavLauncherTeam/PojavLauncher#4027]
### Describe the bug

Hello I was trying to play a modpack provided by a small creator, after a long loading it "saving world" and crash itself

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10929608/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Wait until loading finished
3. "Saving world"
4. Crash
```

### Expected Behavior

I expect the game launch

### Platform

```markdown
- Device model: Redmi 10
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Lastest Google Play version
```

### Anything else?

please help

**Comment by artdeell** [comment]
Try to use holy gl4es instead of angle

**Comment by Hadbrinenotcool** [comment]
> Try to use holy gl4es instead of angle

Will it work tho? I use 1.19

**Comment by GaucovyAero** [comment]
> > Try to use holy gl4es instead of angle
> 
> Will it work tho? I use 1.19

just try it and see

**Comment by Hadbrinenotcool** [comment]
> > > Try to use holy gl4es instead of angle
> > 
> > 
> > Will it work tho? I use 1.19
> 
> just try it and see

Alright il try now

**Comment by Hadbrinenotcool** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10930672/latestlog.txt)
Still crashed.

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 260 - v3_openjdk |
| Minecraft version | 1.19.2-forge-43.2.3 - FORGE |
| Renderer | HOLY_GL4ES_114 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 17 |
| Java arguments |  |

**Comment by Hadbrinenotcool** [comment]
Probably the Mekanism/Flux Network/Industrial Foregoing incompatibility

**Comment by Hadbrinenotcool** [comment]
> 

oh it's arm_64..

**Comment by Hadbrinenotcool** [comment]
Oh well it's fine Il try other modpacks instead, thanks for helping.

**Comment by artdeell** [comment]
@Hadbrinenotcool it should work on the latest latest google play version (dahlia-310)

**Comment by Hadbrinenotcool** [comment]
> @Hadbrinenotcool it should work on the latest latest google play version (dahlia-310)

It worked fine after I removed mekanism actually.
