### ISSUE TITLE
[BUG] <Short description>the game crash when I install fabric 

### ISSUE THREAD

**Issue by UGArya** [PojavLauncherTeam/PojavLauncher#4029]
### Describe the bug

Whenever I install fabric or forge the game crash 

### The log file and images/videos

#

### Steps To Reproduce

```markdown
Idk what to write
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: Realme 8 5g
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahila-310-ed1870eec-v3_openjdk
```

### Anything else?

Plz fix I want to play with shaders

**Comment by UGArya** [comment]
![IMG-20230310-WA0004](https://user-images.githubusercontent.com/127468527/224235319-c65cb9d4-3c42-4c3f-ae39-12b89e72275f.jpg)
![Uploading Screenshot_2023-03-10-11-25-53-99_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

**Comment by UGArya** [comment]
![Uploading Screenshot_2023-03-10-11-25-53-99_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

**Comment by GaucovyAero** [comment]
send latestlog.txt
