### ISSUE TITLE
[help wanted] when trying to add optifine to forge it doesn't work

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4030]
### Describe the bug

can't add optifine to forge. it doesn't even show up in the mods section nor it works

### The log file and images/videos

no pictures 

### Steps To Reproduce

```markdown
1. Add optifine to the mods folder
2. Join the game
3. optifine isn't there
```

### Expected Behavior

I expected optifine to be added to the mods

### Platform

```markdown
- Device model: huawei y6s 
- CPU architecture: MTK MT6765 
- Android version: 9 
- PojavLauncher version: dahlia-107-b6f15cb42-v3_openjdk
```

### Anything else?

i can play with optifine normally when i don't add it to forge

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by Mathias-Boulay** [comment]
Old version, also #1948 I guess
