### ISSUE TITLE
[BUG] <Unisoc Chipset Renderer Problems>

### ISSUE THREAD

**Issue by Jazlenkate** [PojavLauncherTeam/PojavLauncher#4032]
### Describe the bug

Why my zink renderer and Virgl renderer can't use in Unisoc chipsets it always crash.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I expect the game launch

### Platform

```markdown
- Device model: Realme C11 2021
- CPU architecture: 
- Android version: 11
- PojavLauncher version: Old Version and Playstore Version
```

### Anything else?

Ty for responding

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by Jazlenkate** [comment]
@GaucovyAero here the latest log

--------- beginning with launcher debug
Info: Launcher version: dahlia-260-ff1db3127-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.15.2-OptiFine_HD_U_G6
--------- beginning of main

I/jrelog  (13254): dlopen libxhook.so success

I/jrelog  (13502): dlopen libxhook.so success

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1120
Added custom env: POJAV_NATIVEDIR=/data/app/~~2argqPOLV8Gw1rpRPsoqVQ==/net.kdt.pojavlaunch-KWn232f9QVad4VqtSgspnw==/lib/arm
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/~~2argqPOLV8Gw1rpRPsoqVQ==/net.kdt.pojavlaunch-KWn232f9QVad4VqtSgspnw==/lib/arm
Added custom env: POJAV_RENDERER=opengles3_virgl
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=430
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.3
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=504
I/jrelog  (13502): dlopen libOSMesa_8.so failed: dlopen failed: cannot locate symbol "__aeabi_idiv0" referenced by "/data/app/~~2argqPOLV8Gw1rpRPsoqVQ==/net.kdt.pojavlaunch-KWn232f9QVad4VqtSgspnw==/lib/arm/libOSMesa_8.so"...

I/jrelog  (13502): dlopen /data/app/~~2argqPOLV8Gw1rpRPsoqVQ==/net.kdt.pojavlaunch-KWn232f9QVad4VqtSgspnw==/lib/arm/libOSMesa_8.so failed: dlopen failed: cannot locate symbol "__aeabi_idiv0" referenced by "/data/app/~~2argqPOLV8Gw1rpRPsoqVQ==/net.kdt.pojavlaunch-KWn232f9QVad4VqtSgspnw==/lib/arm/libOSMesa_8.so"...

I/LIBGL   (13502): Initialising gl4es
I/LIBGL   (13502): v1.1.4 built on Dec  6 2022 11:42:53
I/LIBGL   (13502): Using GLES 2.0 backend

I/LIBGL   (13502): loaded: libGLESv2.so

I/LIBGL   (13502): loaded: libEGL.so
I/LIBGL   (13502): Using GLES 2.0 backend

I/LIBGL   (13502): Hardware Full NPOT detected and used

I/LIBGL   (13502): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (13502): Extension GL_EXT_draw_buffers  detected and used
I/LIBGL   (13502): FBO are in core, and so used
I/LIBGL   (13502): PointSprite are in core, and so used
I/LIBGL   (13502): CubeMap are in core, and so used
I/LIBGL   (13502): BlendColor is in core, and so used
I/LIBGL   (13502): Blend Substract is in core, and so used
I/LIBGL   (13502): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (13502): Texture Mirrored Repeat is in core, and so used

I/LIBGL   (13502): Extension GL_OES_mapbuffer  detected

I/LIBGL   (13502): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (13502): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (13502): Extension GL_OES_depth24  detected and used
I/LIBGL   (13502): Extension GL_OES_rgb8_rgba8  detected and used

I/LIBGL   (13502): Extension GL_EXT_multi_draw_arrays  detected
I/LIBGL   (13502): Extension GL_EXT_texture_format_BGRA8888  detected and used

I/LIBGL   (13502): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (13502): Extension GL_OES_texture_stencil8  detected and used

I/LIBGL   (13502): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (13502): Extension GL_OES_texture_float  detected and used
I/LIBGL   (13502): Extension GL_OES_texture_half_float  detected and used

I/LIBGL   (13502): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (13502): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (13502): Extension GL_OES_fragment_precision_high  detected and used

I/LIBGL   (13502): Extension GL_EXT_shader_texture_lod detected and used

I/LIBGL   (13502): Max vertex attrib: 16
I/LIBGL   (13502): Extension GL_OES_standard_derivatives  detected and used

I/LIBGL   (13502): Max texture size: 8192
I/LIBGL   (13502): Max Varying Vector: 15
I/LIBGL   (13502): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6

I/LIBGL   (13502): Hardware vendor is Imagination Technologies

I/LIBGL   (13502): GLSL 300 es supported
I/LIBGL   (13502): GLSL 310 es supported and used

I/LIBGL   (13502): GLSL 320 es supported
I/LIBGL   (13502): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (13502): sRGB surface supported
I/LIBGL   (13502): EGLImage to Texture2D supported
I/LIBGL   (13502): EGLImage to RenderBuffer supported

I/LIBGL   (13502): ignore MipMap

I/LIBGL   (13502): Targeting OpenGL 2.1
I/LIBGL   (13502): No hack in shader converter to define overloaded function with int

I/LIBGL   (13502): NPOT texture handled in hardware
I/LIBGL   (13502): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (13502): try to use VBO
I/LIBGL   (13502): FBO workaround for using binded texture enabled
I/LIBGL   (13502): glX Will try to recycle EGL Surface
I/LIBGL   (13502): Current folder is:/
I/jrelog  (13502): dlopen /data/app/~~2argqPOLV8Gw1rpRPsoqVQ==/net.kdt.pojavlaunch-KWn232f9QVad4VqtSgspnw==/lib/arm/libgl4es_114.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success

I/jrelog  (13502): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libtinyiconv.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsdt.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pkcs11.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsctp.so success
I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libhprof.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libzip.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pcsc.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjawt.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsig.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmlib_image.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libunpack.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjdwp.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2gss.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_xawt.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjaas_unix.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmanagement.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsound.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjpeg.so success
I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsunec.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnpt.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/liblcms.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libdt_socket.so success

I/jrelog  (13502): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success

I/jrelog  (13502): dlopen /data/app/~~2argqPOLV8Gw1rpRPsoqVQ==/net.kdt.pojavlaunch-KWn232f9QVad4VqtSgspnw==/lib/arm/libopenal.so success

I/jrelog  (13502): Done processing args

I/jrelog  (13502): Found JLI lib
I/jrelog  (13502): Calling JLI_Launch

2023-03-12 18:33:39,385 main ERROR appender Console has no parameter that matches element Policies

[18:33:40] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[18:33:40] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[18:33:40] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions

OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/optifine/OptiFine/1.15.2_HD_U_G6/OptiFine-1.15.2_HD_U_G6.jar

OptiFineTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[18:33:41] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2023-03-12 18:33:41,713 main ERROR appender Console has no parameter that matches element Policies

[18:33:43] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.capabilities.ICapabilityProvider
[18:33:43] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[18:33:44] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[18:33:44] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[18:33:44] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[18:33:44] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[18:33:45] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[18:33:45] [main/INFO]: Setting user: jaz
Registered forkAndExec
[18:34:05] [main/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[18:34:05] [main/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[18:34:05] [main/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[18:34:05] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[18:34:06] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier
[18:34:06] [main/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
VirGL: OSMesa buffer flush is DISABLED!
--------- beginning of crash

**Comment by Jazlenkate** [comment]
@GaucovyAero is there anything solution here?

**Comment by GaucovyAero** [comment]
> @GaucovyAero is there anything solution here?

Uhm, the issue is that you are aarch32, that's why virgl won't work. Zink and ANGLE won't work, because your SoC does not support Vulkan.

**Comment by Jazlenkate** [comment]
@GaucovyAero Thanks for response.
