### ISSUE TITLE
Latest Integration Package Installation Method: Install using CMCL .JAR initiator

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#4034]
### Is this request related to a bug?

no

### Describe the request.

The steps are: 1. Download v1.8 cmcl .jar this URL: https://github.com/MrShieh-X/console-minecraft-launcher/releases
After downloading the cmcl .jar, move it to the folder you created and enter the folder name you want
2.Download Termux(https://github.com/termux/termux-app/releases/tag/v0.118.0) Download JAVA17:1.termux-setup-storage,2.termux-setup-storage,3.pkg search openjdk,4. You will find that an OpenJDK-17 was retrieved.
After that, execute the installation command: apt install openjdk-17 -y, 4. This step is to install jdk17 and agree to all options

Wait for the installation to complete and enter java -version, if the Java version is displayed, it is successful

3.Download the mod pack from curseforge, rename it to: modpack and move to the folder where cmcl .jar is located

4.Open termux, enter cd /sdcard/ (cmcl.jar folder name), locate it, and enter java -jar cmcl.jar -modpack -l modpack.zip

5.After installation, find the folder where the cmcl .jar is located, and directly move .minecraft to PojavLauncher's .minecraft (cannot be overwritten)

**Comment by Baobuchi** [comment]
java -jar cmcl.jar -modpack -l modpack.zip

**Comment by Baobuchi** [comment]
Please note: It is the CMCL launcher with version 1.8

**Comment by Baobuchi** [comment]
There is an error in the English writing, it is recommended to see the Chinese version translated into English.

**Comment by artdeell** [comment]
Except nobody in the dev team knows chinese

**Comment by GaucovyAero** [comment]
i guess ima close this cause like its just a tutorial
