### ISSUE TITLE
[BUG] Not logged into mc account problem

### ISSUE THREAD

**Issue by Saksham1727N** [PojavLauncherTeam/PojavLauncher#4037]
### Describe the bug

Basically I have a premium acc that I have been using like a year or 2 bur today when I tried to log on to hypixel and other servers they said <You are not logged on to your minecraft account . If ur logged on try restarting ur client or launcher> I've checked everything it seems fine also I don't use any mods neither did I touch settings or smth else 1 hour ago I was able to play it normally but now this bug      I also tried various version none are working (plz kindly investigate the case cuz I can't live without mc java)

### The log file and images/videos

![Screenshot_20230313_203812_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/127767829/224745297-a2cb1136-3176-4f9a-84a8-601d4ee55a90.jpg)

### Steps To Reproduce

```markdown
1.start pojav laucnehr with a account
2. Try to log on any premium server
```

### Expected Behavior

I expect that the server turns on like normal but it doesnt

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
this is not a pojav issue
