### ISSUE TITLE
[BUG] <Glitchy Black Screen>

### ISSUE THREAD

**Issue by RandomGitHubber302** [PojavLauncherTeam/PojavLauncher#4038]
### Describe the bug

When I start playing in a world, the screen glitches black whenever I'm using a lot of memory or something like that. I've tried switching renderers, stop using optifine, but nothing works. It happens in every version. Also, after I open a new world, whenever I don't have my mouse on the pojav tab it turns black until I hover my mouse back over. Even after I'm back on the menu screen. It is super annoying and it is borderline unplayable.

### The log file and images/videos

I can't use a recording software because it uses too much processing power, and it is flashing on even the Mojang loading screen. It just flashes black the whole time.

### Steps To Reproduce

```markdown
1. Use a lot of memory/CPU/GPU/something.
```

### Expected Behavior

I expected it to be normal.

### Platform

```markdown
- Device model: Chromebook
- CPU architecture: idk
- Android version: Chrome OS, Latest.
- PojavLauncher version: Latest
```

**Comment by GaucovyAero** [comment]
have you tried using fullscreen?

**Comment by RandomGitHubber302** [comment]
Yes, I have used nothing but fullscreen.

**Comment by GaucovyAero** [comment]
these are weird chromebook issues we cant really fix, almost every chromebook has a different random issue, and sometimes when we fix it, it causes bigger issues on phones and other devices that work perfectly, so yeah
