### ISSUE TITLE
[BUG] <Short description> Chat disabled due to missing profile public key. please try reconnecting in realm

### ISSUE THREAD

**Issue by mfsa0** [PojavLauncherTeam/PojavLauncher#4039]
### Describe the bug

Chat disabled due to missing profile public key. please try reconnecting in realm
Fix it please

### The log file and images/videos

Chat disabled due to missing profile public key. please try reconnecting

### Steps To Reproduce

```markdown
Chat disabled due to missing profile public key. please try reconnecting
```

### Expected Behavior

Chat disabled due to missing profile public key. please try reconnecting

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
no fix for now, play on a server that does not use microsoft's chat protection
