### ISSUE TITLE
[BUG] Unknown Crashes

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#4040]
### Describe the bug

Application Exited With Code -1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10978214/latestlog.txt)

### Steps To Reproduce

```markdown
open pojav
select any ver that use jar 17
click play
and cradh
```

### Expected Behavior

Normally boot

### Platform

```markdown
- Device model: Redmi Note 10 4+2/128G
- CPU architecture: universal (idk arch but compatible ever arch)
- Android version: 12
- PojavLauncher version: Version Action #4242
```

### Anything else?

please send me how to fix it (i dont wana remove app i will lose every mod and file i installed)

**Comment by GaucovyAero** [comment]
record your forge installation

**Comment by ssaagamemer** [comment]
there
[forge-1.19.2-43.2.6-installer.jar.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/10979290/forge-1.19.2-43.2.6-installer.jar.log)

**Comment by GaucovyAero** [comment]
![Screenshot_2023-03-15-13-04-02-695_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/85581164/225303881-68bfd1b1-43c7-4852-aa93-bae341ea07a8.jpg)

it works for me, so idk

**Comment by ssaagamemer** [comment]
what i need to fix reinstall app?

**Comment by GaucovyAero** [comment]
> what i need to fix reinstall app?

absolutely no idea

**Comment by ssaagamemer** [comment]
ima reinstall

**Comment by ssaagamemer** [comment]
> > what i need to fix reinstall app?
> 
> absolutely no idea

what pojav version?
