### ISSUE TITLE
Can't play 1.18 fabric with sodium 

### ISSUE THREAD

**Issue by Mousebu** [PojavLauncherTeam/PojavLauncher#4041]
### Describe the bug

Application exited with code 1

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1.Start Pojav launcher 
2.choose fabric loader 0.14.13 1.18
3.Click on play
3.It will crash after a few seconds
```

### Expected Behavior

I expect the game not to crash 

### Platform

```markdown
- Device model: Vivo y91i
- CPU architecture: 64 aarch
- Android version: 8.1
- PojavLauncher version: latest on Google Play Store
```

### Anything else?

I had theese mods
1.Fabric api
2.replay
3.Sodium
Latest log here-
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10978273/latestlog.txt)

**Comment by ssaagamemer** [comment]
its not supported replying as broken mod installed

**Comment by ssaagamemer** [comment]
#1948

**Comment by GaucovyAero** [comment]
your phone does not support vulkan
