### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by rkrownii518** [PojavLauncherTeam/PojavLauncher#4042]
### Describe the bug

Right stick is inconsistent on whether or not it works in game, sometimes I boot up the launcher and it works, other times it doesn't.

### The log file and images/videos

Nothing showed in log file

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Play with controller
3. Leave with controller connected
4. Reboot pojav launcher
```

### Expected Behavior

Should work fine, but sometimes it doesn't

### Platform

```markdown
- Device model: OnePlus 9 5g
- CPU architecture: ARM Cortex-X1 
- Android version: 12
- PojavLauncher version: Latest release
```

### Anything else?

It used to work perfectly but now it doesn't work at all

**Comment by VenomousSteam81** [comment]
Could be the controller itself

**Comment by Mathias-Boulay** [comment]
New controller handling has been done
