### ISSUE TITLE
[F-Req] Force Login/Force Account ReSync

### ISSUE THREAD

**Issue by Gadet-0** [PojavLauncherTeam/PojavLauncher#4044]
### Is this request related to a bug?

No

### Describe the request.

Add a button force login/account resync (The account login which happens ocassionally) to the account managment menu, sometimes due to invalid session, we need to restart the game, but if we just force relog it will ease it

### Anything else?

NOPE!

**Comment by VenomousSteam81** [comment]
That would be cool but it would still require you to restart the game, and different clients already have this feature, except its for making account lists without restarting the game

**Comment by Mathias-Boulay** [comment]
Yeah it would still require to relaunch the game
