### ISSUE TITLE
[BUG] <Short description>Can't join the server Ethereal Skies

### ISSUE THREAD

**Issue by CaveSpiderII** [PojavLauncherTeam/PojavLauncher#4046]
### Describe the bug

I can join the server play.etherealskies.com on my computer.But when I join on the pojavlauncher,it reported "unkown hostname".I changed java and dns on my mobile phone,but is doesn't work.

### The log file and images/videos

[19:21:23] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.12
[19:21:23] [main/INFO]: Loading 94 mods:
	- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
	- betterbeds 1.2.0
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- capes 1.3.1+1.18.2
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.3.81
	- com_github_llamalad7_mixinextras 0.0.9 via cull-less-leaves
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- continuity 2.0.1+1.18.2
	- cull-less-leaves 1.0.1
	- dynamicfps 2.1.0
	- enhancedblockentities 0.7.1+1.18.2
	- fabric-api 0.67.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric-api
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric-api
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.2+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.20+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.6.0+d8cf4e5a60 via fabric-api
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric-api
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric-api
	- fabric-models-v0 0.3.6+d7c144a860 via fabric-api
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric-api
	- fabric-registry-sync-v0 0.9.11+bb2e047760 via fabric-api
	- fabric-renderer-api-v1 0.4.15+ee3621fc60 via fabric-api
	- fabric-renderer-indigo 0.5.5+41a02c8a60 via fabric-api
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.8+ee3621fc60 via fabric-api
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric-api
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric-api
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric-api
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric-api
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.12
	- fastchest 1.2+1.18
	- indium 1.0.7+mc1.18.2
	- io_github_douira_glsl-transformer 2.0.0-pre9 via iris
	- iris 1.5.2
	- java 17
	- lambdynlights 2.1.0+1.17
	- lanserverproperties 1.8
	- lazydfu 0.1.2
	- lithium 0.10.2
	- minecraft 1.18.2
	- modmenu 3.0.0
	- omega-config 1.2.3-1.18.1 via capes
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- pride 1.1.0+1.17 via lambdynlights
	- reeses-sodium-options 1.4.9+mc1.18.2-build.66
	- skinlayers 1.4.6-mc1.18.2
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.17+mc1.18.2-build.94
	- spruceui 3.3.0+1.17 via lambdynlights
	- starlight 1.0.2+fabric.89b8d9f
	- wi_zoom 1.4-MC1.18.2
[19:21:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minec

### Steps To Reproduce

```markdown
1.start 1.18.2,fabric1.14.2
2.click multiplayer
3.join the world
```

### Expected Behavior

I expect I can join this server.

### Platform

```markdown
- Device model: RMX3366
- CPU architecture: 高通骁龙870八核
- Android version: 13
- PojavLauncher version: dahlia-310-ed1870eec-v3_openjdk
```

**Comment by Dawimpy** [comment]
What does it said?

**Comment by CaveSpiderII** [comment]
Unknown Host

**Comment by Vylesh** [comment]
Are you did a patch for sodium etc ?

**Comment by GaucovyAero** [comment]
make sure to use a direct ip and not a domain
