### ISSUE TITLE
[BUG] Forge does not work

### ISSUE THREAD

**Issue by JakeKimYT** [PojavLauncherTeam/PojavLauncher#4048]
### Describe the bug

when i launch forge 43.1.52 i crashes automatically
it says exit code 1

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-310-ed1870eec-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19.2-forge-43.1.52
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1520
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-F1wwYr9fKT7c4fuGTRAeVA==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-F1wwYr9fKT7c4fuGTRAeVA==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
OpenJDK 64-Bit Server VM warning: 
getcpu(2) system call not supported by kernel

Exception in thread "main" 
java.lang.module.ResolutionException: Modules lwjgl.glfw.classes and org.lwjgl.tinyfd export package org.lwjgl.util.tinyfd to module unsafe
	at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.finish(Unknown Source)
	at java.base/java.lang.module.Configuration.<init>(Unknown Source)
	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:129)
Java Exit code: 1

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Launch any forge 1.19.2 versions
3. wait a few seconds
```

### Expected Behavior

i expect the game to launch

### Platform

```markdown
- Device model: Oppo A3s
- CPU architecture: Aarch64 Processor rev 4 (aarch64)
- Android version: 8.1.0
- PojavLauncher version: latest version in google play
```

**Comment by Vylesh** [comment]
Are you using Angle or Virgl ?

**Comment by ssaagamemer** [comment]
i think he use angle

**Comment by JakeKimYT** [comment]
i was using gl4es

**Comment by JakeKimYT** [comment]
this is a screen record for more details

**Comment by JakeKimYT** [comment]
.

**Comment by JakeKimYT** [comment]
this is the screen record for more details
[Download screen record](https://www.mediafire.com/file/640br2uy9wx1iag/Record_2023-03-22-17-02-28.mp4/file)

**Comment by JakeKimYT** [comment]
also it also works with any version

**Comment by ssaagamemer** [comment]
problem i checked it from securejar in cpw folder idk how to fix it

**Comment by Vylesh** [comment]
@JakeKimYT Problem reason is using wrong type custom path... Use main .minecraft folder or create custom folder inside it.

**Comment by Vylesh** [comment]
> @JakeKimYT Problem reason is using wrong type custom path... Use main .minecraft folder or create custom folder inside it.

Making custom path outside of .minecraft folder result with crash

**Comment by ssaagamemer** [comment]
> > @JakeKimYT Problem reason is using wrong type custom path... Use main .minecraft folder or create custom folder inside it.
> 
> Making custom path outside of .minecraft folder result with crash

how to make custom folder without crash and not using an .minecraft

**Comment by Vylesh** [comment]
> > > @JakeKimYT Problem reason is using wrong type custom path... Use main .minecraft folder or create custom folder inside it.
> > 
> > Making custom path outside of .minecraft folder result with crash
> 
> how to make custom folder without crash and not using an .minecraft

![Screenshot_20230329-133403_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/83465565/228507515-993d4fe8-c428-4866-878b-9ef7996f5247.jpg)

![Screenshot_20230329-133417_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/83465565/228507574-7ab3b1d8-f83a-481f-958f-247bb21a87be.jpg)

İn 1st screenshot press select after in selecting screen go to .minecraft folder .after that in .minecraft folder press create folder and select it for custom path folder

**Comment by Vylesh** [comment]
> > > > @JakeKimYT Problem reason is using wrong type custom path... Use main .minecraft folder or create custom folder inside it.
> > > 
> > > Making custom path outside of .minecraft folder result with crash
> > 
> > how to make custom folder without crash and not using an .minecraft
> 
> ![Screenshot_20230329-133403_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/83465565/228507515-993d4fe8-c428-4866-878b-9ef7996f5247.jpg)
> 
> ![Screenshot_20230329-133417_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/83465565/228507574-7ab3b1d8-f83a-481f-958f-247bb21a87be.jpg)
> 
> İn 1st screenshot press select after in selecting screen go to .minecraft folder .after that in .minecraft folder press create folder and select it for custom path folder 
> 

İn short you need a create folder for custom path in .minecraft folder not outside otherwise game will crash for cant find assets etc.
(Edit: bcuz Custom path just works for custom configs etc. Otherwise custom path is not includes assets files or main files)

**Comment by RuneJakeKim** [comment]
Still does not work though

**Comment by Mathias-Boulay** [comment]
Said version now works on dev builds
