### ISSUE TITLE
[BUG] Keeps Crashing

### ISSUE THREAD

**Issue by Albertfatmus** [PojavLauncherTeam/PojavLauncher#4049]
### Describe the bug

I play on a Samsung Galaxy s23 phone 128gb of storage and 8gb of ram. Lately, when I log into my Thaumcraft world, the game keeps crashing becaue I have the effect "Unnatural Hunger II". The game lags for 7 seconds, then the game crashes.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11009538/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install Thaumcraft
2. Have "Unnatural Hunger II"
3. Game Crashes
```

### Expected Behavior

Game Crashes

### Platform

```markdown
- Device model: Galaxy s23
- CPU architecture: ARMV9
- Android version: 13
- PojavLauncher version: current
```

**Comment by GaucovyAero** [comment]
gl4es does not support your shader mods
