### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Pheterisdumb** [PojavLauncherTeam/PojavLauncher#4050]
### Describe the bug

Despite downloading optifine and turning off everything that can lag the game there's still a frequent lag spike,another thing i cant access the pojav file, through my files i turn on hidden files
I can only access it through the put resource pack button.

### The log file and images/videos

Pls fix it

### Steps To Reproduce

```markdown
1.start Pojavlauncher
2.go in a world 
3.lag.
```

### Expected Behavior

Less lag

### Platform

```markdown
- Device model: y1
- CPU architecture: idk?
- Android version: 6-7?
- PojavLauncher version:1.12
```

### Anything else?

I think its not my phone its the launcher

**Comment by NotAHero04** [comment]
Your provided information is unclear.
Still, increasing allocation may reduce GC lag spikes.

**Comment by GaucovyAero** [comment]
the solution is to either to buy a better phone, or join our discord server and install pojavoptimize

**Comment by Vylesh** [comment]
You need give us more information for solution
Which type render are you using ?
Are you using optifine etc.

**Comment by Pheterisdumb** [comment]
Optifine

**Comment by GaucovyAero** [comment]
figure it out yourself if you won't hear us out i guess
