### ISSUE TITLE
click bug otg mouse

### ISSUE THREAD

**Issue by Betagodd** [PojavLauncherTeam/PojavLauncher#4052]
### Describe the bug

every time i click the mouse the game lags

### The log file and images/videos

`

https://user-images.githubusercontent.com/128269031/226189933-1febf484-5aba-4528-a0b3-9a96729be6c1.mp4

`

### Steps To Reproduce

```markdown
start pojavlauncher and make several mouse clicks while rotating the mouse
```

### Expected Behavior

clicks should not be delayed

### Platform

```markdown
- Device model:s10e 6/128
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest version of play store
```

### Anything else?

Help

**Comment by GaucovyAero** [comment]
this is a samsung issue, not something we can fix
