### ISSUE TITLE
Skins for offline

### ISSUE THREAD

**Issue by Pheterisdumb** [PojavLauncherTeam/PojavLauncher#4054]
### Describe the request.

Yo is it just me or steve looks kinda boring,pls add like a option to add skins for offline accounts
Because i miss using skins plus its unfair that only the ones with accounts can have skins.

### Anything else?

None that's it thanks 🙏

**Comment by Vylesh** [comment]
Sorry but skin option for just premium users. Ofline is cant be.

**Comment by GaucovyAero** [comment]
no
