### ISSUE TITLE
Bring Zink renderer back 

### ISSUE THREAD

**Issue by abhishekgi** [PojavLauncherTeam/PojavLauncher#4057]
### Is this request related to a bug?

In my opinion viral should be improved and zink must be added back because zink run most shaders without issue 
In Mali gpu and viral run most shaders without issue in Andreno gpu so if both will be available we can choose the renderer according to our gpu and developer must mention after the name of renderer that which renderer is  best for which gpu and which renderer is used to run minecraft normally,   which renderer is used to run minecraft with shaders ,  which renderer is used to run minecraft with mods,  and which renderer provide best performance,  all these things should be metioned in the settings of launcher So that the new guys don't get confused selecting renderer. 

And zink renderer must be brought back it was the best .
Using zink I was able to run most shaders in my device of Mali g72 gpu with good performance 25 - 50 fps and also touched 70 fps in the latest zink build in branch:v3_zink , but viral barely run few shaders , viral is very glitchy and it's performance is not that good rarely cross 15 fps

So developers it is my request that please brought zink back

### Describe the request.

Zink was a renderer which was able to launch any minecraft version and almost all the shaders and mods send the performance shaders in zink was comparatively better than the performance of shaders in virgl and virgl is very glitchy and barely run few shaders 

So there is no reason that zink must not be brought back
If zink will come back so the people having Mali gpu devices will use zink and people with Andreno gpu devices Wil use virgl as virgl run better on Andreno 

So

Please

Bring 

Zink 

Back 

If my points make sense 

Please

I want to enjoy shaders on my Mali g72 gpu device

**Comment by GaucovyAero** [comment]
no
