### ISSUE TITLE
1.14 crash

### ISSUE THREAD

**Issue by Pheterisdumb** [PojavLauncherTeam/PojavLauncher#4059]
### Describe the bug

Ex.none

### The log file and images/videos

None is shown

### Steps To Reproduce

```markdown
1.start Pojavlauncher
2.play 1.14
3.create a world4.get kicked out of the launcher/game
```

### Expected Behavior

I expected the game would run smoothly 

### Platform

```markdown
- Device model: any
- CPU architecture: any
- Android version:any 
- PojavLauncher version: latest
```

### Anything else?

None

**Comment by NotAHero04** [comment]
You won't get proper support from us if we don't know what's happened with your game instance. Send a launcher log.

**Comment by Mathias-Boulay** [comment]
It works on dev builds: [
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/24864674/57b1dc99-1c26-4634-b7b0-838c3eb9fe1e)
](url)
