### ISSUE TITLE
Application/game exited with code 1

### ISSUE THREAD

**Issue by Minblud** [PojavLauncherTeam/PojavLauncher#406]
When ever I try to launch the game it just  brings this up and I downloaded the Java thing from a YouTube download

**Comment by mglovers123** [comment]
████████ jl

**Comment by WesleyVanNeck** [comment]
install lwjgl

**Comment by WesleyVanNeck** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Testing-v3

**Comment by khanhduytran0** [comment]
> install lwjgl

I don't think so. Missing LWJGL cause Minecraft to throw a crash report.

**Comment by mstiwithvihaan** [comment]
I open 1.17 I got this error - application/game exited with code 1

**Comment by NotAHero04** [comment]
> I open 1.17 I got this error - application/game exited with code 1

For 1.17 thing, go to #1035, it’s not supported for now.

**Comment by rscAvePlex** [comment]
> I open 1.17 I got this error - application/game exited with code 1

fck off

**Comment by Bruhwww** [comment]
i try to install forge and that same error comes up and i have no idea to fix

**Comment by jackyleo1234** [comment]
Can someone help me pls every time i try to open the app it always says app exited with code 1 and also what can i do for mods for 1.12.2 to not lag?

**Comment by Bruhwww** [comment]
Happened to me and i just had to find the right java runtime and the right
renderer then it worked. the mods idk. I don't even know who i'm writing to
but whatever


Den sön 25 dec. 2022 kl 23:12 skrev jackyleo1234 ***@***.***>:

**Comment by se7868** [comment]
Application/game exited with code 1 #406
