### ISSUE TITLE
[BUG] WASD berjalan sendiri

### ISSUE THREAD

**Issue by Fery1940** [PojavLauncherTeam/PojavLauncher#4062]
### Describe the bug

WASD berjalan sendiri, saat menggunakan keyboard otg, sebelum update bug ini tidak ada setelah saya update bug ini muncul,

### The log file and images/videos

Berjalan sendiri cacat keyboard

### Steps To Reproduce

```markdown
Bug wasd berjalan sendiri, saat menggunakan keyboard otg
```

### Expected Behavior

saya berharap bugnya di perbaiki

### Platform

```markdown
- Device model: Vivo v15
- CPU architecture: mediatek helio p70
- Android version: 11
- PojavLauncher version: versi dahlia-740-623f7dd33-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
fixed in current dev builds
