### ISSUE TITLE
i can't join any worlds or servers

### ISSUE THREAD

**Issue by forfade2007** [PojavLauncherTeam/PojavLauncher#4063]
### Describe the bug

when i'm trying to join server i have this error
![Screenshot_2023-03-22-10-19-10-711_net kdt pojavlaunch](https://user-images.githubusercontent.com/82573654/226830087-34067940-59ab-4860-8dd4-fbf25a26c6d5.jpg)
 if i'm trying to join my own world minecraft just crashes, here is log
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11037397/latestlog.txt)
I have only 1 mod installed, it's plasmo voice

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11037413/latestlog.txt)
![Screenshot_2023-03-22-10-19-10-711_net kdt pojavlaunch](https://user-images.githubusercontent.com/82573654/226830703-b7cea373-2d3b-4f8f-85d3-3159018155fe.jpg)

### Steps To Reproduce

```markdown
1. launch minecraft forge 1.19 with plasmo voice installed
2. Join any world or server
3. get minecraft crashed
```

### Expected Behavior

I expect that I will enter the world

### Platform

```markdown
- Device model: Xiaomi pad 5
- CPU architecture: AArch64 Processor rev 14 (aarch64)
- Android version: Android 13
- PojavLauncher version: latest version from Play Market
```

**Comment by GaucovyAero** [comment]
only simple voice chat works

**Comment by forfade2007** [comment]
> only simple voice chat works

so, i wont be able to play with plasmo voice?

**Comment by GaucovyAero** [comment]
> > only simple voice chat works
> 
> so, i wont be able to play with plasmo voice?

no

**Comment by forfade2007** [comment]
> > > only simple voice chat works
> > 
> > so, i wont be able to play with plasmo voice?
> 
> no

is there any ways to fix it? cause i cant play on server without that mod

**Comment by mchnjt** [comment]
ask the server owner to ~~hop to bloonstd~~ switch to svchat ig

**Comment by forfade2007** [comment]
> ask the server owner to ~~hop to bloonstd~~ switch to svchat ig

I do not think that they will change the mod that everyone has installed for the sake of me alone

**Comment by GaucovyAero** [comment]
> > ask the server owner to ~hop to bloonstd~ switch to svchat ig
> 
> I do not think that they will change the mod that everyone has installed for the sake of me alone

it isn't possible to fix it, deal with the owner or don't play on the server

**Comment by GaucovyAero** [comment]
latest plasmovoice apparently works, but i cant really guarantee
