### ISSUE TITLE
Unable to use gamepad

### ISSUE THREAD

**Issue by Kinshukhh** [PojavLauncherTeam/PojavLauncher#4064]
### Describe the bug

Gamepad still working before update but now its not #

### The log file and images/videos

I dont have screenshot but its not working 

### Steps To Reproduce

```markdown
When I start and connect my controller it doesnt provide to use it
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: Mi A3
- CPU architecture: idk
- Android version: 11
- PojavLauncher version: latest
```

**Comment by VenomousSteam81** [comment]
Not all gamepads/controllers are supported, and device compatbility can also hurt/help in different situations

**Comment by VenomousSteam81** [comment]
Not all gamepads/controllers are supported, and device compatbility can also hurt/help in different situations

**Comment by VenomousSteam81** [comment]
Not all gamepads/controllers are supported, and device compatbility can also hurt/help in different situations

**Comment by VenomousSteam81** [comment]
Oh crap github is being dumb, as it decided to say it couldnt comment at this time

**Comment by Kinshukhh** [comment]
> Not all gamepads/controllers are supported, and device compatbility can also hurt/help in different situations

Hey but I am having xbox 360 controller

**Comment by VenomousSteam81** [comment]
> > Not all gamepads/controllers are supported, and device compatbility can also hurt/help in different situations
> 
> Hey but I am having xbox 360 controller

How? The cable or the wireless adapter?

**Comment by Mathias-Boulay** [comment]
@Kinshukhh can you try the current dev builds ?
