### ISSUE TITLE
[Error] <Sodium Fabric>

### ISSUE THREAD

**Issue by Kr1nas** [PojavLauncherTeam/PojavLauncher#4065]
### Describe the bug

Help. I'm having trouble entering the world in Fabric Sodium. The game crashes after the player appears, and no error is displayed. Java runtime version 17 is installed, and I have also checked version 18. Fabric 0.11.1  1.16.5 What advice can you give me? 

### The log file and images/videos

![Screenshot_20230323_011056_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/128646565/227050857-a19dc21e-c860-4715-acfe-297c8f44607d.jpg)
![Screenshot_20230323_011103_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/128646565/227050860-5807dae3-877d-4f04-8c86-1539d009cedc.jpg)
![Screenshot_20230323_011108_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/128646565/227050862-35e4ce43-c18b-4156-a5b7-dde984147cf8.jpg)
![Screenshot_20230323_011043_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/128646565/227050865-258c9044-e221-4848-90cd-6158eb1708e5.jpg)
![Screenshot_20230323_072212_QuickEdit.jpg](https://user-images.githubusercontent.com/128646565/227102706-d7e1c424-e596-4865-947b-834cdb632ede.jpg)
![Screenshot_20230323_072157_QuickEdit.jpg](https://user-images.githubusercontent.com/128646565/227102705-cca601c0-5257-4ee9-9065-d0617eb56a2c.jpg)

### Steps To Reproduce

```markdown
1.I can launch PojavLauncher normally, but when I enter the world, it starts connecting to the world, then saving the world and ends with an error.
```

### Expected Behavior

No matter how much I watch videos or search forums, I can't find a solution to my situation.

### Platform

```markdown
- Device model:Samsung Tab A8 10.5 LTE.
- CPU architecture:Unisoc T618.
- Android version:13 
- PojavLauncher version:I recently downloaded from the Play Store.
```

### Anything else?

Help

**Comment by SolomoEudor143** [comment]
Run the sodium patcher tool given in the pojav discord in announcements and run it as a mod loader with java 17

**Comment by Kr1nas** [comment]
I couldn't find the patch tool in Discord.

**Comment by ssaagamemer** [comment]
i got banned from that server i cant get patcher or anything

**Comment by Kr1nas** [comment]
There is still no patcher.

**Comment by mchnjt** [comment]
Kindly recheck on the FAQ channel. We'll add it to our wiki later if needed (but i think its already there.)

**Comment by Kr1nas** [comment]
What should I do?

**Comment by GaucovyAero** [comment]
> What should I do?

check https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html
