### ISSUE TITLE
Just Discord unban request

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#4066]
### Is this request related to a bug?

No

### Describe the request.

-

### Anything else?

I Just Need Unban From Discord

**Comment by mchnjt** [comment]
No

**Comment by ThatMG393** [comment]
No

**Comment by ssaagamemer** [comment]
ok Ima Un Do All Of Crowdin Translated If Not I Do Crowdin Translate For It

ในวันที่ พฤ. 23 มี.ค. 2023 20:09 น. thatmidcoder393 <
***@***.***> เขียนว่า:

**Comment by ssaagamemer** [comment]
Ok I Mailed Lol I Forgot Im Using Thai Lang in app

**Comment by mchnjt** [comment]
> ok Ima Un Do All Of Crowdin Translated If Not I Do Crowdin Translate For It

Go ahead; no one's stopping you.
No developer can be threatened by your dumb threats. We don't directly push translations.

**Comment by ssaagamemer** [comment]
ya I know im not doing it

**Comment by ssaagamemer** [comment]
just want to get access to discord server again

**Comment by mchnjt** [comment]
Try struggling further; we will still NOT unban you.

**Comment by ssaagamemer** [comment]
fine Im Not Using IT ANYMORE I JUST WANT TO GET MY FORGE 1.19.2 WITH MOD FIXED

**Comment by ssaagamemer** [comment]
AND MY ACOCUNT I HAVE ONLY 0.86฿ 
Oh shoot i reveal my country

**Comment by crystall1nedev** [comment]
Unban requests should be handled by asking a moderator of the Discord server directly.

**Comment by ssaagamemer** [comment]
i cant access mod for unbanning

**Comment by ssaagamemer** [comment]
i cant dm him due to acocunt banned from server

**Comment by ssaagamemer** [comment]
if any mod want to talk to me then 
Discord:Secondyou2#3341
