### ISSUE TITLE
[BUG] Forge Crash (Request 2 To Get Fixed)

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#4068]
### Describe the bug

Exit with code 1 and error from cpw.securejar
and More

### The log file and images/videos

i removed an app but its same as problem

### Steps To Reproduce

```markdown
start pojavlauncher
run forge 1.19.2 with mod
then crashed
```

### Expected Behavior

Make forge launch with mods and playable

### Platform

```markdown
- Device model: Redmi note 10
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: dahlia-742
```

### Anything else?

No More

**Comment by GaucovyAero** [comment]
share your log file

**Comment by Mathias-Boulay** [comment]
probably a custom instance issue. Stale issue, closing.
