### ISSUE TITLE
There was a zboy application/ games with code 1.

### ISSUE THREAD

**Issue by ValentinEgynow** [PojavLauncherTeam/PojavLauncher#4069]
### Describe the bug

Hello developers and all the pojavlaunche community. Help solve the problem with the launch of the assembly on version 1.12.2. At first everything goes fine, but after ten seconds the game closes and the message "there was a zboy application / games with code 1. Check latestlog.txt to get more information." Please help me solve the problem.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11054667/latestlog.txt)

### Steps To Reproduce

```markdown
I run pojavlauncher on version 1.12.2-14.23.5.2860
```

### Expected Behavior

The game will start

### Platform

```markdown
- Device model: realme s25c 4/64G
- CPU architecture: Helio G85
- Android version: 12
- PojavLauncher version: crocus-93- 14dcf9993-v3_openjdk
```

**Comment by artdeell** [comment]
First of all, very outdated pojav version, please update to the google play latest.
Second of all, randompatches isn't yet supported
