### ISSUE TITLE
Jre8 Runtime

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#407]
Can you upload the jre9 runtime for anyone to download at anytime?, i really need the java 9 runtime to increase performance.

**Comment by WesleyVanNeck** [comment]
you mean 8? 9 is terable

**Comment by WesleyVanNeck** [comment]
join the discord we will help you there

**Comment by leetmussc** [comment]
yes i mean 8

**Comment by leetmussc** [comment]
Discord link?

**Comment by mglovers123** [comment]
@leetmussc https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/355646293
