### ISSUE TITLE
Could not create the Java Virtual Machine. [BUG] 

### ISSUE THREAD

**Issue by ItsCitronus** [PojavLauncherTeam/PojavLauncher#4071]
### Describe the bug

Error code 1 when trying to install any version of forge/Optifine

### The log file and images/videos

Info: Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/forge-1.12.2-14.23.5.2860-installer.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~jnrY9T7Lc9ov3LqYbC0jFg==/net.kdt.pojavlaunch-wR6fZUEJKueU8dUo7_cR8w==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~jnrY9T7Lc9ov3LqYbC0jFg==/net.kdt.pojavlaunch-wR6fZUEJKueU8dUo7_cR8w==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Policy policy.url.2=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy (No such file or directory)

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7f98039df8)
Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/*

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7f7b631038)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7f7b631038)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select any version of forge/optifine (jar) and install
3. Get error code 1 (Could not create the Java Virtual Machine)
```

### Expected Behavior

I was expecting a forge/Optifine installation to start

### Platform

```markdown
- Device model: Realme 10 8/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest version from playmarket
```

**Comment by Cube5x59999** [comment]
Try different versions of java, or reinstall the app

**Comment by GaucovyAero** [comment]
put your screen into landscape mode
