### ISSUE TITLE
[BUG] graphics issue

### ISSUE THREAD

**Issue by Huta0c6** [PojavLauncherTeam/PojavLauncher#4072]
### Describe the bug

minecraft 1.13.2 rendering the image has problems(skin,block and mob error).

### The log file and images/videos

![Screenshot_2023-03-26-07-36-47-67_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/126092312/227749444-1a6fad20-ee2f-422d-8f11-f65e0cbad0f5.jpg)
![Screenshot_2023-03-26-07-36-30-60_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/126092312/227749523-b60ae3d6-4d56-4bf3-a074-064a33cc2830.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11070514/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher 
2.install minecraft 1.13.2 release
3.create and enter any world
```

### Expected Behavior

I want to fix it

### Platform

```markdown
- Device model: realme c3/32G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest release from google play
```

**Comment by Cube5x59999** [comment]
Try virglrenderer

**Comment by Huta0c6** [comment]
I have tried and encountered different errors.

![Screenshot_2023-03-27-17-39-23-93_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/126092312/227920268-39216a65-ab2a-4431-99a6-a85fff324429.jpg)
![IMG_20230327_17472627](https://user-images.githubusercontent.com/126092312/227920609-8501d7bf-2fc7-4e2c-9b01-a4920635299b.jpg)
![IMG_20230327_17473430](https://user-images.githubusercontent.com/126092312/227920662-70ce20e2-2c78-4e28-998d-2cf842aebb09.jpg)

**Comment by GaucovyAero** [comment]
use gl4es and press f11

**Comment by Huta0c6** [comment]
It works lol
