### ISSUE TITLE
[BUG] <HOLY GL4ES crashes part 1>

### ISSUE THREAD

**Issue by NethermcYT666** [PojavLauncherTeam/PojavLauncher#4075]
### Describe the bug

When I join into my World which is very large (like 2.8GB) it just crashes

### The log file and images/videos

https://user-images.githubusercontent.com/95992727/227766863-dd9f4fba-35e5-4b50-9dde-cafbf8e2f9cc.mp4

### Steps To Reproduce

```markdown
Get HOLY GL4ES to work with large Worlds
```

### Expected Behavior

Not to expect lag fix but for it to render properly in large Worlds

### Platform

```markdown
- Device model: CPH2021
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

N/A

**Comment by mchnjt** [comment]
Your screen recording does not explain your issue very well.
