### ISSUE TITLE
[F-Req] Changeable button text size

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#4079]
### Is this request related to a bug?

Improve the default controlls because its too hard to use them, especially on tablets

### Describe the request.

New controls like
![Screenshot_20230326-191218_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98256780/227779875-3432c3d4-82a6-47cc-b2d4-6e8b58300f9b.jpg)

File for using it is (i cant upload .JSON files, sorry D: )

### Anything else?

Also, make a new slider in custom controls to change text size for individual buttons

**Comment by Cube5x59999** [comment]
+make a option to change text color

**Comment by Cube5x59999** [comment]
@GaucovyAero ?? Come here

**Comment by mchnjt** [comment]
> ### Is this request related to a bug?
> Improve the default controlls because its too hard to use them, especially on tablets
> 
> ### Describe the request.
> New controls like ![Screenshot_20230326-191218_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98256780/227779875-3432c3d4-82a6-47cc-b2d4-6e8b58300f9b.jpg)
> 
> File for using it is (i cant upload .JSON files, sorry D: )
> 
> ### Anything else?
> Also, make a new slider in custom controls to change text size for individual buttons

We're not changing our default controls.

**Comment by Cube5x59999** [comment]
Ok
