### ISSUE TITLE
Buttons is not working

### ISSUE THREAD

**Issue by Mynameispoop** [PojavLauncherTeam/PojavLauncher#408]
Please fix it i love pojavlauncher please fix it i hope u notice it :'(

**Comment by khanhduytran0** [comment]
Use latest dev build.

**Comment by Mynameispoop** [comment]
Can u send me a link to it please

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions

**Comment by Mynameispoop** [comment]
Still not working :'( i can click them but it dont work and when i put the mouse on the singleplayer and its not getting highlite :'( pls fix it

**Comment by khanhduytran0** [comment]
Do you mean mouse button or whatever?

**Comment by Mynameispoop** [comment]
Yes :(

**Comment by Mynameispoop** [comment]
Its not doing anything even when i click pri

**Comment by khanhduytran0** [comment]
Use latest build, another

**Comment by Mynameispoop** [comment]
> Use latest build, another

Thank u so so muchhh my friend im actually piketastic from discord
