### ISSUE TITLE
[BUG] Can't See inventory

### ISSUE THREAD

**Issue by DHK24** [PojavLauncherTeam/PojavLauncher#4080]
### Describe the bug

I can't see anything olny I can see it is Hand

### The log file and images/videos

![Screenshot_2023-03-26-19-27-28-455_net kdt pojavlaunch](https://user-images.githubusercontent.com/94371697/227781506-0ef552b9-496b-4796-830f-0eafb9eff2e3.jpg)

### Steps To Reproduce

```markdown
Start pojav go on any solo when go in other world it will show it but I am not sure
```

### Expected Behavior

IDK

### Platform

```markdown
- Device model: Redmi 9activa
- CPU architecture: Aarch64(32bit mode) 
- Android version: 10
- PojavLauncher version: Latest release
```

### Anything else?

IDK

**Comment by Cube5x59999** [comment]
Enable gui dude

**Comment by Cube5x59999** [comment]
Click on gui

**Comment by Cube5x59999** [comment]
Or see gui hide keybind

**Comment by DHK24** [comment]
> Or see gui hide keybind

Dude I am  talking about game not controls

**Comment by Cube5x59999** [comment]
Theres a hide gui keybind in the _game_, see its _keybind_

**Comment by mchnjt** [comment]
F1

**Comment by Cube5x59999** [comment]
activate the keybind, it will Fix it (or not if pojav issue)

**Comment by GaucovyAero** [comment]
install optifine, go to the shaders tab and put antialiasing to 2x fxaa
