### ISSUE TITLE
BugCraft: Bugged edition [Texture issue] [BUG]

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#4082]
### Describe the bug

Textures arent rendering correctly

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11076529/latestlog.txt)
![Screenshot_20230327-140755_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98256780/227888986-4463b46e-25f6-4a74-91ac-09c71712bbc7.jpg)
![Screenshot_20230327-140826_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98256780/227889005-c7fc955e-5435-4a7a-b42b-65935eca3651.jpg)

### Steps To Reproduce

```markdown
1. Start pojav
2. Select any shader and play a world
3. Chance the shader to none in world
4. Some textureS glitchy
5. Wait 1-2 mins, Text glitched
```

### Expected Behavior

Expected that i could change shaders with no problem

### Platform

```markdown
- Device model: Galaxy tab A
- CPU architecture: armv8l
- Android version: 11
- PojavLauncher version: gplay latest
- MC Version: 1.8.9 OF
- Shader: Open4Es mali smth
- Allocated RAM: 680mb
- Free ram before Game start: 700mb
- Java version: Jre8 (1.8.0 internal)
```

### Anything else?

Please fix the peoblem as soon as possible, as many players change shaders in comparisons, so it could ruin that thing

**Comment by GaucovyAero** [comment]
This is your running out of GPU memory, nothing we can fix.
