### ISSUE TITLE
How to fix securejar error in pojav

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#4083]
### Describe the bug

Not A Bug

### The log file and images/videos

If You Found out that has error like

cpw.securejar.handler or anything that includes securejar Its A Error Not Bug

### Steps To Reproduce

```markdown
How To Get Error Happended


1. bootup an Pojavlauncher
2. Play forge any ver that use custompath that not in .minecraft with mod or any version (i didn't check but its from forge)
3. and play
4. some secondyou error throw
```

### Expected Behavior

-

### Platform

```markdown
- Device model: -
- CPU architecture: -
- Android version: -
- PojavLauncher version: -
```

### Anything else?

This Is A guide to get you game fixed

Dont use custompath in forge use .minecraft to add mod

**Comment by GaucovyAero** [comment]
send log

**Comment by ssaagamemer** [comment]
okay

https://pastebin.com/raw/p93Sj8P9

**Comment by Mathias-Boulay** [comment]
Fixed in current dev builds
