### ISSUE TITLE
[BUG]Start forge 1.19.4-45.0.39 Flashback

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#4084]
### Describe the bug

Start forge 1.19.4-45.0.39 Flashback

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11113333/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.play
3.flashback
```

### Expected Behavior

Fix it

### Platform

```markdown
- Device model: honor 30 lite 6/64G
- CPU architecture: MediaTek 800
- Android version: 10
- PojavLauncher version: dahlia-742-90b97cd83-v3_openjdk
```

### Anything else?

The forge installer is downloaded from the forge website

**Comment by ThatMG393** [comment]
what mods are you using?

**Comment by aaaapai** [comment]
> what mods are you using?

no.

**Comment by aaaapai** [comment]
> what mods are you using? \n I found that setting the version isolation will flash back.
