### ISSUE TITLE
[BUG] when installing optifine the pojavlauncher closes 

### ISSUE THREAD

**Issue by bad1ending** [PojavLauncherTeam/PojavLauncher#4086]
### Describe the bug

I need help 

### The log file and images/videos

Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment, -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader, --add-exports=java.desktop/java.awt=ALL-UNNAMED, --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED, --add-exports=java.desktop/sun.java2d=ALL-UNNAMED, --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED, --add-exports=java.desktop/sun.awt=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED, --add-exports=java.desktop/sun.font=ALL-UNNAMED, --add-exports=java.base/sun.security.action=ALL-UNNAMED, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.desktop/java.awt=ALL-UNNAMED, --add-opens=java.desktop/sun.font=ALL-UNNAMED, --add-opens=java.desktop/sun.java2d=ALL-UNNAMED, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.base/java.net=ALL-UNNAMED, -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/OptiFine_1.19.4_HD_U_I3(1).jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=3200
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~rN-0kaH0PmgPKkGWzk6Imw==/net.kdt.pojavlaunch-aQRne02VnaMxozxBZp1iOA==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~rN-0kaH0PmgPKkGWzk6Imw==/net.kdt.pojavlaunch-aQRne02VnaMxozxBZp1iOA==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1440
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Steps To Reproduce

```markdown
I open pojavlauncher I install the JAR optifine and the app closes
```

### Expected Behavior

i want to play with optifine 

### Platform

```markdown
- Device model: samsung a51
- CPU architecture:-
- Android version: 13
- PojavLauncher version: dahlia-740-623f7dd33-v3_open
jdk
```

### Anything else?

when installing any version of optifine in pojavlauncher it doesn't matter which version the game closes

**Comment by bad1ending** [comment]
someone help me ?

**Comment by beastboymayu** [comment]
Did u solve this

**Comment by beastboymayu** [comment]
I need help in same error

**Comment by GaucovyAero** [comment]
> I need help in same error

send latestlog.txt
