### ISSUE TITLE
Operational issues with the MIUI14/Android13

### ISSUE THREAD

**Issue by routhing** [PojavLauncherTeam/PojavLauncher#4087]
### Describe the bug

Operational issues with the MIUI14/Android13

        Because opening the input method will reboot to recovery in MIUI 13.0.22, try an update to MIUI14 to fix it. There is a serious problem with touch screen operation now.

### The log file and images/videos

https://user-images.githubusercontent.com/71493668/229261479-1212dd94-d676-4d13-bab0-f98962bccf00.mp4

### Steps To Reproduce

```markdown
After entering the main world, it is impossible to slide to other directions while turning.
```

### Expected Behavior

Fix the problem

### Platform

```markdown
- Device model: Redmi K50
- CPU architecture: D8100
- Android version: 13
- PojavLauncher version: Latest version
```

**Comment by GaucovyAero** [comment]
this is a duplicate issue and unfortunately, we won't do anything about it yet.

**Comment by Mathias-Boulay** [comment]
android 13 + swipeable buttons are now fixed on dev builds
