### ISSUE TITLE
[F-Req] Discord Status/RPC support

### ISSUE THREAD

**Issue by Gadet-0** [PojavLauncherTeam/PojavLauncher#4088]
### Is this request related to a bug?

**NO**

### Describe the request.

Even after using clients, its not possible to show up that we are currently playing Minecraft, so can you add a discord rpc option, if enabled will show the status in the discord (maybe it will ask to link your account) but its ok, Please add this feature

### Anything else?

**NO**

**Comment by mchnjt** [comment]
No

**Comment by kaicryptx** [comment]
Use kizzy app to show playing rpc in discord

**Comment by VenomousSteam81** [comment]
> Use kizzy app to show playing rpc in discord

Not the best thing, but it works

**Comment by mchnjt** [comment]
Why do we even need RPC

**Comment by kaicryptx** [comment]
> Why do we even need RPC

Just for fun

**Comment by mchnjt** [comment]
Yeah but what's the actual purpose

**Comment by kaicryptx** [comment]
> Yeah but what's the actual purpose

Its shows in discord what are you playing

**Comment by GaucovyAero** [comment]
no
