### ISSUE TITLE
Game crashes when joining Mcc island

### ISSUE THREAD

**Issue by AugustSunshine** [PojavLauncherTeam/PojavLauncher#4089]
### Describe the bug

[Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11131132/latestlog.txt)

### Steps To Reproduce

```markdown
1. Use Angle Renderer and Java17
2. Start the launcher
3. Join mcc island server
4. It will show the red mojang loading screen then crashes
```

### Expected Behavior

I expect the game to join mccisland and work.

### Platform

```markdown
- Device model: samsung Galaxy s9
- CPU architecture: ARMv8-A
- Android version: Android 10
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

I am able to access Hypixel from the same version. I appreciate any help.

**Comment by AugustSunshine** [comment]
Can someone help me?

**Comment by VenomousSteam81** [comment]
I'm not totally sure, but I believe that there are fixes which are being done.

**Comment by GaucovyAero** [comment]
should be fixed in the latest play store update
