### ISSUE TITLE
can i play 6.0.1 android btw

### ISSUE THREAD

**Issue by zian04** [PojavLauncherTeam/PojavLauncher#409]
can i play 6.0.1 android btw

_Originally posted by @zian04 in https://github.com/PojavLauncherTeam/PojavLauncher/issues/210#issuecomment-732676338_

**Comment by WesleyVanNeck** [comment]
Yes v3 you can v2 not

**Comment by zian04** [comment]
Thank you so much for your reply

**Comment by zian04** [comment]
but how to you set v3 up?
