### ISSUE TITLE
[BUG] Pojav does not respect the launcher profile resolution

### ISSUE THREAD

**Issue by tienthanh2929** [PojavLauncherTeam/PojavLauncher#4090]
### Describe the bug

Unsure if it's a bug or intentional, but the Pojav Launcher doesn't affect by the launcher profile resolutions key:
https://minecraft.fandom.com/wiki/Launcher_profiles.json#Resolution_structure

The resolution will be overridden by the Pojav reference settings, no matter what.

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
1. Write `resolutions` key with specific width and height
2. PojavLauncher ignore the `resolution` key
```

### Expected Behavior

Prefer the resolution key if its define.

### Platform

```markdown
- Device model: Samsung
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release
```

### Anything else?

N/A

**Comment by artdeell** [comment]
Intended behavior. Pojav does not support setting resolutions by width and height and we do not intend on adding that.
