### ISSUE TITLE
[BUG] Failed to install latest Forge. 

### ISSUE THREAD

**Issue by CleMooling** [PojavLauncherTeam/PojavLauncher#4092]
### Describe the bug

Error occurred when building forge as the picture. 

### The log file and images/videos

![Screenshot_2023-04-04-00-09-53-94_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/93636342/229569688-da0aca5d-8608-485f-bfa0-654c0c464458.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Touch INSTALL .JAR
3. Select forge-1.19.4-45.0.40-installer.jar
4. Install it (by touching Install client)
5. Error occurred when building it as the picture.
```

### Expected Behavior

Forge should finally notice that it's installed successfully. 

### Platform

```markdown
- Device model: OPPO PFCM00
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Latest from Google Play Store
```

### Anything else?

After forcing to close the installation, the version of forge-installed appears, but can't be launched by exit with code 1. 
If need, logs will be provided later.

**Comment by CleMooling** [comment]
Forge-installed version was not appeared immediately, when you editing a profile and select versions, then you see it.

**Comment by GaucovyAero** [comment]
make sure you DON'T download the installer with chrome and make sure you ARE using java 8 to launch the installer
