### ISSUE TITLE
[BUG] <Cannot Open Cape Editor>

### ISSUE THREAD

**Issue by Wizard-NukeZ** [PojavLauncherTeam/PojavLauncher#4095]
### Describe the bug

While Watching random vids on yt, i saw a guy with santa hat so i wanna that so i went to pojavlauncher>settings>skin customization>Optifine Cape> Open Cape Editor and see that error

### The log file and images/videos

![Screenshot_2023-04-04-18-53-37-75_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/98901689/229800710-4c43ff6d-e320-4476-bc9b-f652d9f98be5.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Open settings
3. Open Skin Customization
4. Open Optifine Cape... (Use Optifine To get this option)
5. Click On Open Cape Editor
```

### Expected Behavior

I expected it to open cape editor...

### Platform

```markdown
- Device model: OPPO F9 4/64G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release || dahila-740-623f7dd33-v3-opendjk
```

**Comment by artdeell** [comment]
No idea. Nobody here has paid to sp614x to test this feature.
Please send the log though.

**Comment by Wizard-NukeZ** [comment]
> No idea. Nobody here has paid to sp614x to test this feature. Please send the log though.

Sir, i tried days in a row but when i open Click on Optifine cape the log gets disappeared

**Comment by GaucovyAero** [comment]
wont fix
