### ISSUE TITLE
[BUG] Unable to log in

### ISSUE THREAD

**Issue by leotheleopard** [PojavLauncherTeam/PojavLauncher#4096]
### Describe the bug

After hitting play, app requires user to log in again, even if they had logged in previously, game does not launch as it continues to request a log in, cresting a log in loop.

### The log file and images/videos

https://user-images.githubusercontent.com/59138587/229992964-5aa213d0-8ccd-4fe6-9ed4-409e2cebc6a1.mp4

### Steps To Reproduce

```markdown
1. Start Launcher
2. Hit play.
3. Login via proffered method
4. Wait for it to finish logging in.
5. Hit play again
```

### Expected Behavior

Game should launch, logged in to the correct account.

### Platform

```markdown
- Device model: Samsung Galaxy Fold 4
- CPU architecture: Kryo
- Android version: 13
- PojavLauncher version: dhalia-740-623f7dd33-v3_openjdk
```

**Comment by GaucovyAero** [comment]
this should not happen, try reinstalling the app
