### ISSUE TITLE
Landscape Bug

### ISSUE THREAD

**Issue by Pojavfanbhgfinder** [PojavLauncherTeam/PojavLauncher#4097]
### Describe the bug

The bug is that i cannot tap play On Landscape Mode Like Its So Annoying Accidentally Tapping Share 🫤

### The log file and images/videos

I cant ssend my screen record video it keep dissapering,might be a bug too

### Steps To Reproduce

```markdown
1.i started pojav launcher in vertical when the app becomes landscape it kinda bugs i cant tao play because a share file is buggin it like i keep tapping it
```

### Expected Behavior

Tapping playbutton And I Tapped Share Button Its Like A Play Button Dont Exist It Just Makes My Fingers nopclip through share button.

### Platform

```markdown
- Device model: realme 10
- CPU architecture: Mediatek MT8781 Helio
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

No more sir

**Comment by Mathias-Boulay** [comment]
Can you share a video please ?

**Comment by GaucovyAero** [comment]
> Can you share a video please ?

he probably means that the button is clipping through stuff because its too big

**Comment by GaucovyAero** [comment]
i guess wait till the new landscape ui comes out
