### ISSUE TITLE
My game crashes

### ISSUE THREAD

**Issue by ZhanBro** [PojavLauncherTeam/PojavLauncher#4099]
### Describe the bug

When I installed the eureka and Valkyrien skies and it crashed

### The log file and images/videos

![Screenshot_20230405-233141](https://user-images.githubusercontent.com/129985961/230158640-219443be-291e-4725-9661-6314269bea5a.png)
![Screenshot_20230405-233148](https://user-images.githubusercontent.com/129985961/230158652-213a4d3a-19e2-4e74-987f-281d620f909b.png)
![Screenshot_20230405-233151](https://user-images.githubusercontent.com/129985961/230158658-a41cbddc-5082-409b-ad62-37bc9d973b7a.png)
![Screenshot_20230405-233155](https://user-images.githubusercontent.com/129985961/230158661-4dcd3258-a21d-4f45-996e-d7a2b3783a53.png)
![Screenshot_20230405-233159](https://user-images.githubusercontent.com/129985961/230158663-ccb369f8-bb71-44a6-b8b5-2e58ef8dd2bf.png)
![Screenshot_20230405-233202](https://user-images.githubusercontent.com/129985961/230158665-51d34bee-5116-47cf-9ec3-d71aa97e8078.png)
![Screenshot_20230405-233205](https://user-images.githubusercontent.com/129985961/230158669-44fe709b-2d45-4e0b-9e09-2209ed045016.png)
![Screenshot_20230405-233207](https://user-images.githubusercontent.com/129985961/230158673-3866c1ab-8466-4d05-90b0-597dddc33120.png)

### Steps To Reproduce

```markdown
1. Installing eureka and Valkyrien skies
2. Lunching forge 1.18.2 
3. Crashes
```

### Expected Behavior

I didn't expect that

### Platform

```markdown
- Device model: techno spark 6
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest
```

**Comment by ssaagamemer** [comment]
Why You Battery Is 5%

**Comment by ZhanBro** [comment]
Idk

**Comment by VenomousSteam81** [comment]
Yo @ZhanBro, instead of uploading the log file to Google Drive or just sending multiple screenshots, try copying all of log contents to [GitHub Gist](https://gist.github.com/) and pasting it there, then sending the link here to the logs without having to worry about file access and such.

**Comment by Mathias-Boulay** [comment]
#1948
