### ISSUE TITLE
If I press the direction key first, I cannot move the angle of view

### ISSUE THREAD

**Issue by 311303** [PojavLauncherTeam/PojavLauncher#41]
However, it is normal to use the direction key when moving the viewing angle.
Hope you can fix it.
I used 1.11.2.
My fingers are really short A kind of.😂

**Comment by khanhduytran0** [comment]
Will be fix in preview9b5.

**Comment by 311303** [comment]
> Will be fix in preview9b5.

I recently tried to enter the 1.11.2 server, and I found that I couldn't get anything out of my backpack or box, or even click on them, which was very deadly. I would appreciate it if you could fix it....

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher#got-some-bugs

Latest preview could not be fixed direction key, won't work.

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.10.1

**Comment by khanhduytran0** [comment]
Fixed in above
