### ISSUE TITLE
[BUG] Mouse bug on 1.12.2 forge

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#410]
This virtual mouse position on forge isn't in line with the touchscreen mouse, how can I fix this?

**Comment by Statzar** [comment]
> This virtual mouse position on forge isn't in line with the touchscreen mouse, how can I fix this?

In the options.txt file, which is located in the .minecraft folder, change the lines
overrideWidth: 0
overrideHeight: 0
To the height and width of your display.
For example, my resolution is 1440x720, so I write
overrideWidth: 1440
overrideHeight: 720
Try

**Comment by khanhduytran0** [comment]
Fixed, try v3.3 or latest build.
