### ISSUE TITLE
[BUG] Valkyrien skies mod don't work

### ISSUE THREAD

**Issue by ZhanBro** [PojavLauncherTeam/PojavLauncher#4100]
### Describe the bug

Game crashes with code 1

### The log file and images/videos

https://drive.google.com/file/d/18abLifqaYtzkhCn5yed3BbDbTLBkZqwA/view?usp=drivesdk
This is latestlog.txt link

### Steps To Reproduce

```markdown
1.Starting pojavlauncher
2.Waiting
3.pojavlauncher crash error code 1
```

### Expected Behavior

I didn't expect that it crashes 

### Platform

```markdown
- Device model: techno spark 6
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

I just wanna play Valkyrien skies

**Comment by artdeell** [comment]
You didn't give public access to the file

**Comment by ZhanBro** [comment]
How I give public access?

**Comment by Joemammasus** [comment]
> How I give public access?

https://youtu.be/W6wq028A0Lo

**Comment by Joemammasus** [comment]
Same error btw

**Comment by GaucovyAero** [comment]
#1948

**Comment by Marshall2439** [comment]
There isnt any solution on #1948
