### ISSUE TITLE
[F-Req] Big Performance Issue

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#4103]
### Is this request related to a bug?

No Its A Big Problem Of Comparator Hmcl-pe

### Describe the request.

The Versions 1.12.2 mod 30-50 my choice mod

HMCL-PE has Made 100 fps or up
Pojavlauncher Has 10-45 fps or 60

We Loseing To Chinese App So Who Can Show and Download

Spark Mod

So We Can Help To Let Pojav dev to make Game Lag better

### Anything else?

No Anymore

**Comment by mchnjt** [comment]
We don't care. We didn't make PojavLauncher to do magic. It depends on how bulky or potato your phone is.

Also consider installing Optifine or update to the latest action build.

**Comment by NotAHero04** [comment]
Lack of provided information.

**Comment by mesflit** [comment]
> We don't care. We didn't make PojavLauncher to do magic. It depends on how bulky or potato your phone is.
> 
> Also consider installing Optifine or update to the latest action build.

HMCL-PE really gives more fps.

because they use this = https://github.com/AOF-Dev/Boat

**Comment by artdeell** [comment]
Depends on hardware and mc setup. On my phone vanilla is faster than on
hmcl-pe

сб, 8 апр. 2023 г., 05:15 mesflit ***@***.***>:

**Comment by mchnjt** [comment]
> > We don't care. We didn't make PojavLauncher to do magic. It depends on how bulky or potato your phone is.
> > Also consider installing Optifine or update to the latest action build.
> 
> HMCL-PE really gives more fps.
> 
> because they use this = https://github.com/AOF-Dev/Boat

elaborate further

**Comment by mesflit** [comment]
> > > We don't care. We didn't make PojavLauncher to do magic. It depends on how bulky or potato your phone is.
> > > Also consider installing Optifine or update to the latest action build.
> > 
> > 
> > HMCL-PE really gives more fps.
> > because they use this = https://github.com/AOF-Dev/Boat
> 
> elaborate further

You use your own environment to run Minecraft.
But this is better https://github.com/AOF-Dev/Boat

**Comment by mchnjt** [comment]
> > > > We don't care. We didn't make PojavLauncher to do magic. It depends on how bulky or potato your phone is.
> > > > Also consider installing Optifine or update to the latest action build.
> > > 
> > > 
> > > HMCL-PE really gives more fps.
> > > because they use this = https://github.com/AOF-Dev/Boat
> > 
> > 
> > elaborate further
> 
> You use your own environment to run Minecraft. But this is better https://github.com/AOF-Dev/Boat

ok and

**Comment by mesflit** [comment]
> > > > > We don't care. We didn't make PojavLauncher to do magic. It depends on how bulky or potato your phone is.
> > > > > Also consider installing Optifine or update to the latest action build.
> > > > 
> > > > 
> > > > HMCL-PE really gives more fps.
> > > > because they use this = https://github.com/AOF-Dev/Boat
> > > 
> > > 
> > > elaborate further
> > 
> > 
> > You use your own environment to run Minecraft. But this is better https://github.com/AOF-Dev/Boat
> 
> ok and

And?

**Comment by Mathias-Boulay** [comment]
I would bet quite a lot schedulers are making this comparison much harder, checking out frequencies and load would be more important

**Comment by mesflit** [comment]
> I would bet quite a lot schedulers are making this comparison much harder, checking out frequencies and load would be more important

But I had 2 devices, one of them was very old with a mediatek processor, I don't remember exactly. Boat was giving 70-80 fps while Pojavlauncher was between 40-50 fps. And the CPU temperature didn't get too high. As in HMCL PE, there should be a selection setting, the one that wants chooses the PojavLauncher, the one that chooses the BOAT. I think it will be of better quality this way.

**Comment by artdeell** [comment]
Not happening. Far too much would need to be done for this to happen, and
we'd like to improve our own instead of using somebody else's

пн, 10 апр. 2023 г., 19:22 mesflit ***@***.***>:

**Comment by ssaagamemer** [comment]
its can improve better just wait

**Comment by mesflit** [comment]
> its can improve better just wait

i will be waiting
