### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by weng251** [PojavLauncherTeam/PojavLauncher#4104]
### Describe the bug

Hello, I am a pojav user from China, I have been getting a problem with pojav to 1 code exit in my 1. Version 14 to 1. 19. Both versions have this problem. Please solve it. Thank you.

### The log file and images/videos

![Uploading Screenshot_20230408_123719.jpg…]()

### Steps To Reproduce

```markdown
Hello, I am a pojav user from China, I have been getting a problem with pojav to 1 code exit in my 1. Version 14 to 1. 19. Both versions have this problem. Please solve it. Thank you.
```

### Expected Behavior

Hello, I am a pojav user from China, I have been getting a problem with pojav to 1 code exit in my 1. Version 14 to 1. 19. Both versions have this problem. Please solve it. Thank you.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by MovTery** [comment]
请发日志
