### ISSUE TITLE
[F-Req] Install module package

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#4106]
### Is this request related to a bug?

I think it would be more convenient to add an option on the homepage to install the module package managed by Curseforge.

### Describe the request.

A new option for installing module packages.

### Anything else?

no more

**Comment by ssaagamemer** [comment]
That good idea like modpack or mod installation screen select version and directory

**Comment by GaucovyAero** [comment]
will be added soon
