### ISSUE TITLE
[BUG] It cant find my Minecraft account (prpbably because of game pass)

### ISSUE THREAD

**Issue by clawghost** [PojavLauncherTeam/PojavLauncher#4107]
### Describe the bug

Everytime it try to login with my microsoft account it says "seems like that microsoft account doesnt have a minecraft profil  if you have the xbox game pass pls login into minecraft.net and set it up.
![Screenshot_2023-04-09-20-16-33-861_net kdt pojavlaunch](https://user-images.githubusercontent.com/130310212/230789871-968b0fa0-5d52-4a2d-a13d-a0a1b1f7adcd.jpg)
(Unfortunatly the text is in german but i wrote what it says before.)
I do have the gamepass on this microsoft account but i had the minecraft account way before so i dont know how i can set the gamepass up in the official minecraft website or in what kind of way it relates to each other.

### The log file and images/videos

![Screenshot_2023-04-09-20-30-54-423_net kdt pojavlaunch](https://user-images.githubusercontent.com/130310212/230790309-dea91db6-b679-4bd0-9363-cc350a725238.jpg)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher 
2.click on add new account
3.click on microsoft login 
4.login with the correct data
```

### Expected Behavior

I expected it to recognize my minecraft account and letting me play with it.

### Platform

```markdown
- Device model: xiaomi Redmi Note 10
- CPU architecture: i dont know
- Android version: Android 12
- PojavLauncher version: newest from the playstore
```

**Comment by Mathias-Boulay** [comment]
Well, in theory you just need to login to the official mc website with your gamepass, it will allow you to setup a few things like defaukt skin and a username.

Then pojav will work

**Comment by clawghost** [comment]
Well at the end i fixes it by unsubscring my gamepass but thqnks for the response.

**Comment by marcissdn** [comment]
Anymore icant see video

**Comment by flipace** [comment]
I just encountered the same - turned out that I just had to add a Profile name on minecraft.net -> Profile, then it worked 👍

**Comment by GGG1T** [comment]
Что делать скажите пожалуйста, я что уже не делал, п.амять и.зменял, нас.тройках лазил, переустоновил поджав, телефон перезагружал, нече не помогает, вот ошибка↓ (ето при установке любой выерсии)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Произошёл собой приложения/игры с кодом -1. Проверьте latestlog.txt, чтобы получить больше информации.

**Comment by King677777** [comment]
And I, like you, get the same problem and before that I logged in to minecraft. Net
