### ISSUE TITLE
[BUG] I Can't press anything!

### ISSUE THREAD

**Issue by Hadbrinenotcool** [PojavLauncherTeam/PojavLauncher#4111]
### Describe the bug

I suddenly can't click anything even w/out mouse, The button inside the game is misplaced somewhere, and i believe it's a launcher bug because when I tried other version it acted the same way!

### The log file and images/videos

https://user-images.githubusercontent.com/83611884/231000773-db6ccebb-d8c8-44fd-ba28-9791a55d31a0.mp4

(In the end it's like I'm able to click Quit Game, So it gotta be misplaced button)

### Steps To Reproduce

```markdown
1.Star Pojav Launcher
2.Loading..
3.Cant click any "Play" or any other button!
```

### Expected Behavior

I just wanna play Pixelmon 😔

### Platform

```markdown
- Device model: Redmi 10 2022
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Version
```

### Anything else?

I do hope the launcher get an update to fix this bug, I'm not sure either if anyone else experience this or just me.

**Comment by Hadbrinenotcool** [comment]
Additional info: The GitHub version work perfectly (Dahlia 753), the one I recorded is from play store (Dahlia 740)

**Comment by Mathias-Boulay** [comment]
Good thing to know the dev versions works
