### ISSUE TITLE
[BUG] GL4ES

### ISSUE THREAD

**Issue by hexadec1mal** [PojavLauncherTeam/PojavLauncher#4112]
### Describe the bug

When I load with forge and lambda client game crash. When I change renderer to virgl game load, but I have 1 fps. Also lambda client load on old pojav launcher (crocus-V3). So this is 100% bug of a new GL4ES

### The log file and images/videos

[logs.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/11202826/logs.zip)

### Steps To Reproduce

```markdown
Load forge 1.12.2 and lambda client from https://GitHub.com/lambda-client/lambda
Game crash when renderer is GL4ES, but doesn't if virgl
```

### Expected Behavior

The game should launch with lambda, because it launch on old pojav/GL4ES

### Platform

```markdown
- Device model: Redmi note 8
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest build
```

**Comment by Ezleak** [comment]
hack[doge]

**Comment by GaucovyAero** [comment]
hacks generally dont work on pojav
