### ISSUE TITLE
F[BUG] <Fabric with mods doesnt load>

### ISSUE THREAD

**Issue by PepiKral** [PojavLauncherTeam/PojavLauncher#4113]
### Describe the bug

When i try running fabric with fabric api and ui utils im stuck on blackscreen

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11204653/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install fabric
2. Add ui utils and fabric api
3. Done
```

### Expected Behavior

I expected to see loaded game

### Platform

```markdown
- Device model: A225G 4/64GB
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
some mod compatibility issue
