### ISSUE TITLE
[BUG] Modpack Didnt Launch (FTB Stoneblock 2)

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#4117]
### Describe the bug

Black screen and log has error to make black screen and not anything running

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11230767/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher
Select version that installed ftb stoneblock 2 then click play
```

### Expected Behavior

Modpack Launch Normally

### Platform

```markdown
- Device model: Redmi Note 10 6/128G
- CPU architecture: aarch64
- Android version: 12/miui 14.0.2
- PojavLauncher version: Dahlia-752-3d0b341d1-v3_openjdk
```

### Anything else?

-

**Comment by GaucovyAero** [comment]
remove randompatches
