### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Yeung1234** [PojavLauncherTeam/PojavLauncher#4118]
### Describe the bug

Signpicture mod picture loading wrong.

### The log file and images/videos

Signpicture mod picture loading wrong.

### Steps To Reproduce

```markdown
......
```

### Expected Behavior

......

### Platform

```markdown
- Device model: Samsung A53
- CPU architecture: 8G
- Android version: 13
- PojavLauncher version: newest version
```

**Comment by NotAHero04** [comment]
Not reproducible.
![Screenshot_20230415-123113](https://user-images.githubusercontent.com/84689840/232185193-d32d010a-432e-4a10-8e30-ce7b71606a63.jpg)
[Image link here.](https://tinyurl.com/25ths7pr)
For long links, an URL shortener is required.

**Comment by Yeung1234** [comment]
When i playing 1.12.2 server
