### ISSUE TITLE
Bug with installer

### ISSUE THREAD

**Issue by Pepewy** [PojavLauncherTeam/PojavLauncher#4119]
### Describe the bug

Whenever I try to install a jar file I.e. optifine the log opens and then the game is crashed it says application exited with code 1 something like that

### The log file and images/videos

![Screenshot_2023-04-16-00-02-26-449_com miui gallery](https://user-images.githubusercontent.com/130863310/232247409-a46bf639-41e2-493f-866b-287af939e4d0.jpg)

### Steps To Reproduce

```markdown
I don't know
```

### Expected Behavior

 I expected to install optifine

### Platform

```markdown
- Device model: xiaomi not 10 pro/128g and 8gb ram
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest release
```

### Anything else?

No no

**Comment by Pepewy** [comment]
The log -Info: Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/OptiFine_1.19.4_HD_U_I4.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2326
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~un0JYPBU276u8XdzCliVfA==/net.kdt.pojavlaunch-Y0fvipT_953pZJClqSFK7w==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~un0JYPBU276u8XdzCliVfA==/net.kdt.pojavlaunch-Y0fvipT_953pZJClqSFK7w==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
I/jrelog  (31205): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (31205): dlopen libjvm.so success
I/jrelog  (31205): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (31205): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (31205): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (31205): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (31205): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7b8d1fdd08)

**Comment by Huta0c6** [comment]
https://user-images.githubusercontent.com/126092312/232384753-4129192b-5c18-4d2a-a6e1-d2d339f78a61.mp4
I installed it without any issues.

**Comment by Sohan301966** [comment]
I also have this problem Whenever I try to install a jar file optifine the log opens and then the game is crashed it says application exited with code 1

**Comment by Sohan301966** [comment]
Please give us a solution

**Comment by Kgdjj** [comment]
Hello, I also got that problem that when I wanted to install Optifine in the installer.jar, it took me out of the app and that the app closed with the code -1

**Comment by Kgdjj** [comment]
But I solved it, go to the (Actions) section, find what it says (Fox[Java Installer]: Vertical Mode Crashing the Installer) and download the app-debug, then they unzip it and install it, but they do have to Download the PojavLauncher version of the Play Store! Download the version you want as you usually do, then go to the app-debug you downloaded and installed enter the installer.jar and install. Favorite search for the section [android/data/net.kdt.pojavlaunch.debug] Enter [Files] Copy everything and pass it to [android/data/net.kdt.pojavlaunch] [files] and it they hit there. That would be everything, the first one will not enter but the second yes (this is the ones that the installer bug gives them.jar)

**Comment by GaucovyAero** [comment]
launch it in landscape
