### ISSUE TITLE
My phone: J5 Prime Samsung GB: 32 Android experience: 9.0 Android: 8.0.0    I want you to fix a crash that happens after using Minecraft 1.16.3 I use Jre9 arm 32 to answer my phone's memory  however when i create a world in 1.16.3 or any version i play for a few seconds and the game crashes and says that Poiavlauncher has stopped working should it be a problem on my phone or Java runtime?

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#412]
My phone: J5 Prime Samsung
GB: 32
Android experience: 9.0
Android: 8.0.0
  
I want you to fix a crash that happens after using Minecraft 1.16.3 I use Jre9 arm 32 to answer my phone's memory
 however when i create a world in 1.16.3 or any version i play for a few seconds and the game crashes and says that Poiavlauncher has stopped working should it be a problem on my phone or Java runtime?

**Comment by OwzygZawg** [comment]
1) select Minecraft 1.16.3

2) wait for Minecraft to load!

3) create a flat or standard world!

4) play for a few seconds and the game crashes and says that the poiavlauncher has stopped working or is not responding!


i use JRE9 which is compatible with my phone!

**Comment by OwzygZawg** [comment]
![Screenshot_20201125-165412_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/100275915-71957f00-2f3f-11eb-9b6f-791ff18dcc56.jpg)

**Comment by OwzygZawg** [comment]
On here! if you don't understand the language i'm brazilian! I'm playing Optifine 1.16.3 on Pojav, but when I play for a few seconds in the world this appears and the game crashes, I'm using Jre9 arm32

**Comment by khanhduytran0** [comment]
Do you mean a crash or ANR (App Not Responding)?

**Comment by OwzygZawg** [comment]
My phone has 32 bits! when I create the world at 1.16.3 or Optifine 1.16.3 I play for a few seconds and the game crashes and says the app is not responding! i use jre9 it is compatible with my cell phone i saw in the latest version 3.2v said that the java runtime can hang on some device and the performance is not good!

**Comment by khanhduytran0** [comment]
> says the app is not responding!

Well, the **actual crash** is when the app suddenly quit out, bring back to home device screen.

**Comment by khanhduytran0** [comment]
And show a dialog "PojavLauncher is **stopped**".

**Comment by OwzygZawg** [comment]
> Você quer dizer uma falha ou ANR (App Not Responding)?

I use Jre9 arm32 more when I finish creating the world in 1.16.3 I play for a few seconds and the game crashes and says it stopped responding! is this a problem in the Java runtime or on my phone or is the performance of Pojav v3.2 still not good? or the performance of the jre9 arm 32 java runtime is still not good? because I see video of several people using jre9 arm 32 plus Minecraft 1.16.3 does not crash and does not say that the app has stopped responding! only mine what happens

**Comment by khanhduytran0** [comment]
I already understand what you've said, repeating is not required.

You need understand difference between a Crash and a ANR.

**Comment by khanhduytran0** [comment]
On your case, press "Wait" to continue playing.

**Comment by OwzygZawg** [comment]
> E mostra uma caixa de diálogo "PojavLauncher está **parado** ".

Do you know how I can solve this problem? this problem irritates me! if you help me i appreciate

**Comment by khanhduytran0** [comment]
> On your case, press "Wait" to continue playing.

**Comment by OwzygZawg** [comment]
> No seu caso, pressione "Aguarde" para continuar jogando.

But when I click on wait the game is still stuck and after a few seconds the error appears again saying the app is not responding!

**Comment by khanhduytran0** [comment]
Maybe free some memory?

**Comment by OwzygZawg** [comment]
> Talvez liberar alguma memória?
Do you think that with jre9 I should allocate the memory to how many? to run well at 1.16.3?

**Comment by OwzygZawg** [comment]
> Talvez liberar alguma memória?

I still have 6 bits and 700 mb more the error continues

**Comment by khanhduytran0** [comment]
So how much your device free memory?
Note that max memory for 32-bit is 500~900mb

**Comment by OwzygZawg** [comment]
> Quanto o seu dispositivo libera memória?
> Observe que a memória máxima para 32 bits é de 500 ~ 900 MB

I allocated 512 also 900 but the error still continues I think I will give up Pojav I play a few seconds and the app crashes: /

**Comment by khanhduytran0** [comment]
So, play in other devices if you have.

**Comment by OwzygZawg** [comment]
> Portanto, jogue em outros dispositivos, se tiver.

If I click it waits and it doesn't work? what should I do? I can't stand being stuck anymore and the app still says it is not responding when entering the world! in 1.16.3! I'm going to win another new 32-bit phone, maybe this week you think I'll be able to play a lot? on my new device the other week i will win another

**Comment by OwzygZawg** [comment]
> Portanto, jogue em outros dispositivos, se tiver.

Or will the app work normally if I format my phone? and install Pojav again?

**Comment by OwzygZawg** [comment]
> Portanto, jogue em outros dispositivos, se tiver.

??

**Comment by OwzygZawg** [comment]
> Portanto, jogue em outros dispositivos, se tiver.

????

**Comment by OwzygZawg** [comment]
> Portanto, jogue em outros dispositivos, se tiver.

I know this problem is kind of hard to solve! I think I will give up Pojav is better! but there's Mcinabox

**Comment by khanhduytran0** [comment]
> > Portanto, jogue em outros dispositivos, se tiver.
> 
> I know this problem is kind of hard to solve! I think I will give up Pojav is better! but there's Mcinabox

Do you think if Mcinabox does not have ANR at all?

**Comment by OwzygZawg** [comment]
> > > Portanto, jogue em outros dispositivos, se tiver.
> > 
> > 
> > Eu sei que esse problema é meio difícil de resolver! Acho que vou desistir Pojav é melhor! mas tem o Mcinabox
> 
> Você acha que o Mcinabox não tem ANR?

More in Mcinabox I can play anytime I want in 1.16.3 in Pojav is playing for a few seconds and the app crashes

**Comment by OwzygZawg** [comment]
> > > Portanto, jogue em outros dispositivos, se tiver.
> > 
> > 
> > Eu sei que esse problema é meio difícil de resolver! Acho que vou desistir Pojav é melhor! mas tem o Mcinabox
> 
> Você acha que o Mcinabox não tem ANR?

What is ANR? in Mcinabox I play on 1.16.3,1.16.4 I always play whenever I want! but in Pojav I spend a few seconds playing and Pojav and crashes

**Comment by khanhduytran0** [comment]
I said above
> Do you mean a crash or **ANR (App Not Responding)**

**Comment by khanhduytran0** [comment]
I have a suggestion for you. Since this launcher supports Fabric, you can grab one with OptiFabric (1.14.4+) or Sodium (1.16.1+), see if it have anymore ANR? I respect your opinion.

**Comment by khanhduytran0** [comment]
Also Java9 is slowly than java8 (arm32 one not available yet).

**Comment by OwzygZawg** [comment]
> Além disso, o Java9 é mais lento do que o java8 (arm32 ainda não está disponível).

How do I use jre8 instead of jre9 will arm32 still improve?

**Comment by OwzygZawg** [comment]
> Eu tenho uma sugestão para você. Uma vez que este iniciador suporta Fabric, você pode pegar um com OptiFabric (1.14.4+) ou Sódio (1.16.1+), ver se ele tem mais ANR? Eu respeito a sua opinião.

Mcinabox can be even better than Pojav plus Mcinabox does not support Optifine 1.13., 1.14,1.15.2,1.16.3,1.16.4 pojav does

**Comment by khanhduytran0** [comment]
At this time, the only way is grab Boat's jre8 arm32 build.

**Comment by OwzygZawg** [comment]
> Neste momento, a única maneira é agarrar a compilação jre8 arm32 do Boat.

I'm kind of dumb! how can I do this? to use jre8 with a 32-bit phone?

**Comment by OwzygZawg** [comment]
> Neste momento, a única maneira é agarrar a compilação jre8 arm32 do Boat.

Even if jre8 is 64-bit, can you use jre8 in pojav on a 32-bit phone? please explain to me how I do it!

**Comment by OwzygZawg** [comment]
> > Neste momento, uma única maneira é agarrar a compilação jre8 arm32 do Boat.
> 
> Eu sou meio burro! como posso fazer isso? usar o jre8 com um telefone de 32 bits?

???

**Comment by OwzygZawg** [comment]
![Uploading 20201126_003046.jpg…]()

**Comment by artdeell** [comment]
> > > Neste momento, uma única maneira é agarrar a compilação jre8 arm32 do Boat.
> > 
> > 
> > Eu sou meio burro! como posso fazer isso? usar o jre8 com um telefone de 32 bits?
> 
> ???

https://drive.google.com/file/d/103EheBh7Vvss7pYKD2m9CG5yRuBOGtJB/view?usp=drivesd

32-bit Java 8 runtime, was taken from Boat and re-packed to run on Pojav. Give it a try @OwzygZawg

**Comment by OwzygZawg** [comment]
> > > > Neste momento, uma única maneira é agarrar a compilação jre8 arm32 do Boat.
> > > 
> > > 
> > > Eu sou meio burro! como posso fazer isso? usar o jre8 com um telefone de 32 bits?
> > 
> > 
> > ???
> 
> https://drive.google.com/file/d/103EheBh7Vvss7pYKD2m9CG5yRuBOGtJB/view?usp=drivesd
> 
> Java 8 runtime de 32 bits foi retirado do Boat e recompactado para rodar no Pojav. Experimente @OwzygZawg
Jre2 runs super well with the Pojav that needs jre9 with a 32-bit phone?

**Comment by OwzygZawg** [comment]
Jre2 runs super well with the Pojav that needs jre9 with a 32-bit phone?

**Comment by OwzygZawg** [comment]
> > > > Neste momento, uma única maneira é agarrar a compilação jre8 arm32 do Boat.
> > > 
> > > 
> > > Eu sou meio burro! como posso fazer isso? usar o jre8 com um telefone de 32 bits?
> > 
> > 
> > ???
> 
> https://drive.google.com/file/d/103EheBh7Vvss7pYKD2m9CG5yRuBOGtJB/view?usp=drivesd
> 
> 32-bit Java 8 runtime, was taken from Boat and re-packed to run on Pojav. Give it a try @OwzygZawg

Dude, you're amazing! with jre2 I can now play whenever I want on Optifine on 1.16.3 on Pojav! I forgot to congratulate you I will close the problem! you solved the problem! my phone only supports jre9 and jre2 o 2 ran super well! now I can always play when I want to thank you so much for your help! 😊👏👏
