### ISSUE TITLE
[BUG] Screen minimzes when Shift+W

### ISSUE THREAD

**Issue by kvfs2k07** [PojavLauncherTeam/PojavLauncher#4120]
### Describe the bug

Hello, I usually plug in my mouse and keyboard to my mobile. When I try to go forward while shifting, it toggles fullscreen, like F11. 

### The log file and images/videos

https://user-images.githubusercontent.com/64465478/232316266-6872b5ea-e18b-4bd9-a796-8c7bf44989e7.mp4

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Run ANY MC version (issue found in Vanilla 1.8.9)
3. Enter a world/MC server
4. Press Shift and then press once the W key. It will act like F11
```

### Expected Behavior

I expect not to be like F11 just go straight while shifting

### Platform

```markdown
- Device model: Xiaomi Mi 10T Lite
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Google Play Version (Dahlia 740) 
```

**Comment by GaucovyAero** [comment]
bind fullscreen to f12
