### ISSUE TITLE
Can't press WASD button (in MULTIPLAYER)

### ISSUE THREAD

**Issue by Dawimpy** [PojavLauncherTeam/PojavLauncher#4121]
### Describe the bug

I can't press WASD button unless I'm using it with jump button in multiplayer 

### The log file and images/videos

Video 

https://user-images.githubusercontent.com/87801676/232427844-ad74f7cd-8e8c-4526-9414-98b6b32561f9.mp4

Log file
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11247933/latestlog.txt)

### Steps To Reproduce

```markdown
1.start PojAV
2.join a multiplayer
3. Press WASD button
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Vivo Y20
- CPU architecture: Snapdragon 460
- Android version: 12
- PojavLauncher version: dahlia-754-57521c196-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
"latest", please state the true version.

**Comment by Dawimpy** [comment]
> "latest", please state the true version.

Info is edited. Please take node

**Comment by Dawimpy** [comment]
@Mathias-Boulay Edit: Now ALL WASD button don't work
