### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Jfjfrjdjjd** [PojavLauncherTeam/PojavLauncher#4122]
### Describe the bug

When I enter any version of Minecraft, its very lag (1-2 fps with holy gl4es rendering, 7 fps with virglrenderer, and 14 fps with angle).

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.0
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1390
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~IikY1_Z-3QEMqxJwkakdlQ==/net.kdt.pojavlaunch-aRUq9HXzmdJQyxua5JfQqA==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~IikY1_Z-3QEMqxJwkakdlQ==/net.kdt.pojavlaunch-aRUq9HXzmdJQyxua5JfQqA==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_virgl
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=430
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.3
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=648
--------- beginning of crash

--------- beginning of main

I/jrelog  (15746): dlopen libOSMesa_8.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (15746): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success

I/jrelog  (15746): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (15746): dlopen /data/app/~~IikY1_Z-3QEMqxJwkakdlQ==/net.kdt.pojavlaunch-aRUq9HXzmdJQyxua5JfQqA==/lib/arm64/libopenal.so success

I/jrelog  (15746): Done processing args
I/jrelog  (15746): Found JLI lib
I/jrelog  (15746): Calling JLI_Launch

OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
thg 4 17, 2023 3:30:52 CH net.minecraft.launchwrapper.LogWrapper log
INFO: Using tweak class name net.minecraft.launchwrapper.VanillaTweaker
thg 4 17, 2023 3:30:53 CH net.minecraft.launchwrapper.LogWrapper log
INFO: Launching wrapped minecraft
CacioComponentPeer::setZOrder: NOT YET IMPLEMENTED

27 achievements

174 recipes

Turning of ImageIO disk-caching
Loading current icons for window from: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets/icons/icon_16x16.png and /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets/icons/icon_32x32.png

javax.imageio.IIOException: Can't read input file!

	at javax.imageio.ImageIO.read(Unknown Source)
	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.loadIcon(VanillaTweakInjector.java:130)

	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.loadIconsOnFrames(VanillaTweakInjector.java:107)
	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.inject(VanillaTweakInjector.java:94)

	at net.minecraft.client.Minecraft.main(SourceFile:2115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
Setting gameDir to: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Registered forkAndExec
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.

[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
VirGL: OSMesa buffer flush is DISABLED!
VirGL: libvirgl_test_server = 0x107cd3f298fefeab
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=15823
EGLBridge: EGLDisplay=0x1, EGLSurface=0x7dea43ef00
VirGL: created EGL context 0x7dea446500
EGLBridge: eglMakeCurrent() succeed!
VirGL: vtest_main = 0x7dea6de278
VirGL: Calling VTest server's main function
--------- beginning of system

OSMDroid: width=1390;height=648, reserving 3602880 bytes for frame buffer
OSMDroid: created frame buffer
OSMDroid: generating context
gl_version 32 - es profile enabled
WARNING: running without ARB/KHR robustness in place may crash
failed to create sync opengl context
vtest_client_dispatch_commands: client context created.
GLSL feature level 430
vrend_renderer_fill_caps: Entering with stale GL error: 1282
GLSL feature level 430
OSMESA_TARGET: screen=0x7df2dbb200
OSMESA: stmgr=0x7df2dfee50; stapi=0x7e1baf5d20
OSMDroid: context=0x7df2d6f460
LWJGLX: ready-handle context created

OSMDroid: making current
unknown format is 19
OSMDroid: vendor: Mesa/X.org
OSMDroid: renderer: virgl
LWJGLX: GL caps init

Grab: false

Skipping bad option: key_key.pickItem:key.mouse.middle

Skipping bad option: key_key.playerlist:key.keyboard.tab

Skipping bad option: key_key.forward:key.keyboard.w

Skipping bad option: key_key.drop:key.keyboard.q
Skipping bad option: key_key.back:key.keyboard.s
Skipping bad option: key_key.attack:key.mouse.left

Skipping bad option: key_key.use:key.mouse.right

Skipping bad option: key_key.right:key.keyboard.d

Skipping bad option: key_key.jump:key.keyboard.space
Skipping bad option: key_key.sneak:key.keyboard.left.shift

Skipping bad option: key_key.left:key.keyboard.a

Skipping bad option: key_key.chat:key.keyboard.t

Skipping bad option: key_key.inventory:key.keyboard.e

Starting up SoundSystem...
Initializing LWJGL OpenAL

    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)

[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
OpenAL initialized.

I/NativeInput(15746): Input ready: 1

java.lang.NullPointerException

	at um.b(SourceFile:95)

	at ik.a(SourceFile:27)

	at um.b(SourceFile:95)

	at ik.a(SourceFile:27)

	at um.b(SourceFile:95)

	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)
	at vx.a(SourceFile:75)
	at vx.a(SourceFile:11)
	at w.a(SourceFile:52)
	at adg.b(SourceFile:34)
	at xz.l(SourceFile:64)
	at xz.a(SourceFile:54)
	at xe.a(SourceFile:95)
	at net.minecraft.client.Minecraft.a(SourceFile:466)

	at eh.a(SourceFile:113)
	at xe.a(SourceFile:72)
	at xe.h(SourceFile:120)
	at xe.g(SourceFile:108)
	at net.minecraft.client.Minecraft.k(SourceFile:1362)

	at net.minecraft.client.Minecraft.x(SourceFile:705)
	at net.minecraft.client.Minecraft.run(SourceFile:658)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException

	at um.b(SourceFile:95)
	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)
	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)
	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)

	at vx.a(SourceFile:75)
	at vx.a(SourceFile:11)

	at w.a(SourceFile:63)
	at adg.b(SourceFile:34)
	at xz.l(SourceFile:64)
	at xz.a(SourceFile:54)
	at xe.a(SourceFile:95)
	at net.minecraft.client.Minecraft.a(SourceFile:466)

	at eh.a(SourceFile:113)
	at xe.a(SourceFile:72)
	at xe.h(SourceFile:120)
	at xe.g(SourceFile:108)
	at net.minecraft.client.Minecraft.k(SourceFile:1362)
	at net.minecraft.client.Minecraft.x(SourceFile:705)
	at net.minecraft.client.Minecraft.run(SourceFile:658)

	at java.lang.Thread.run(Unknown Source)
Grab: true

Grab: false

java.lang.NullPointerException

	at um.b(SourceFile:95)
	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)
	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)

	at ik.a(SourceFile:27)

	at um.b(SourceFile:95)
	at vx.a(SourceFile:75)
	at vx.a(SourceFile:11)
	at w.a(SourceFile:52)
	at adg.b(SourceFile:34)
	at xz.l(SourceFile:64)
	at xz.a(SourceFile:54)

	at xe.a(SourceFile:95)
	at net.minecraft.client.Minecraft.a(SourceFile:466)

	at eh.a(SourceFile:113)
	at xe.a(SourceFile:72)
	at xe.h(SourceFile:120)
	at xe.g(SourceFile:108)
	at net.minecraft.client.Minecraft.k(SourceFile:1362)
	at net.minecraft.client.Minecraft.x(SourceFile:705)
	at net.minecraft.client.Minecraft.run(SourceFile:658)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
	at um.b(SourceFile:95)
	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)
	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)
	at ik.a(SourceFile:27)
	at um.b(SourceFile:95)
	at vx.a(SourceFile:75)
	at vx.a(SourceFile:11)
	at w.a(SourceFile:63)
	at adg.b(SourceFile:34)
	at xz.l(SourceFile:64)
	at xz.a(SourceFile:54)
	at xe.a(SourceFile:95)
	at net.minecraft.client.Minecraft.a(SourceFile:466)
	at eh.a(SourceFile:113)
	at xe.a(SourceFile:72)
	at xe.h(SourceFile:120)
	at xe.g(SourceFile:108)
	at net.minecraft.client.Minecraft.k(SourceFile:1362)
	at net.minecraft.client.Minecraft.x(SourceFile:705)
	at net.minecraft.client.Minecraft.run(SourceFile:658)
	at java.lang.Thread.run(Unknown Source)
java.lang.ClassCastException: vd cannot be cast to cg
	at ik.d(SourceFile:99)
	at nq.b(SourceFile:711)
	at vi.b(SourceFile:541)
	at di.b(SourceFile:256)
	at ia.e(SourceFile:879)
	at ry.a(SourceFile:232)
	at net.minecraft.client.Minecraft.a(SourceFile:1827)
	at net.minecraft.client.Minecraft.a(SourceFile:1767)
	at net.minecraft.client.Minecraft.a(SourceFile:1655)
	at xz.e(SourceFile:161)
	at pb.a(SourceFile:209)
	at jn.a(SourceFile:152)
	at xz.a(SourceFile:181)
	at adt.b(SourceFile:793)
	at net.minecraft.client.Minecraft.x(SourceFile:738)
	at net.minecraft.client.Minecraft.run(SourceFile:658)
	at java.lang.Thread.run(Unknown Source)
Grab: true

Grab: false

Grab: true

Grab: false

### Steps To Reproduce

```markdown
It only happens with my device, I tried it on another weaker device and it had more fps
```

### Expected Behavior

Performance improvement

### Platform

```markdown
- Device model: realme c15 qualcomm edition
- CPU architecture:aarch64
- Android version: 11
- PojavLauncher version: lastest from google play
```

**Comment by abhishekgi** [comment]
Delete pojavlauncher completely and reinstall it

**Comment by Jfjfrjdjjd** [comment]
> Delete pojavlauncher completely and reinstall it

I have tried uninstalling and reinstalling several times.

**Comment by abhishekgi** [comment]
> > Delete pojavlauncher completely and reinstall it
> 
> I have tried uninstalling and reinstalling several times.

Then hard reset your phone 📱 if possible by taking backup

**Comment by abhishekgi** [comment]
> > Delete pojavlauncher completely and reinstall it
> 
> I have tried uninstalling and reinstalling several times.

I think 🤔 it may be phone's performance issue play other games and see if they also lag too much
