### ISSUE TITLE
white screen when playing modpack rlcraft

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4126]
### Describe the bug

I have created a sever on aternos with modpack rlcraft 2.9 to play with my friend, I play normally until all of a sudden the screen goes white when I go back to the sever then it lags and the screen goes white

### The log file and images/videos

![Screenshot_2023-04-20-10-47-11-971_net kdt pojavlaunch](https://user-images.githubusercontent.com/84832540/233256191-4691e86b-75ad-47e8-aced-aabcb25462c7.jpg)

### Steps To Reproduce

```markdown
multiplayer and singleplayer
```

### Expected Behavior

how to fix

### Platform

```markdown
- Device model: Redmi note 7 pro
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: dahlia-258-cb44314ab-v3_openjdk
```

### Anything else?

how to fix error 😭😭😭😭😭

**Comment by GaucovyAero** [comment]
missing log file
