### ISSUE TITLE
[F-Req] <Short description> Cps setting

### ISSUE THREAD

**Issue by mesflit** [PojavLauncherTeam/PojavLauncher#4127]
### Is this request related to a bug?

Get cps adjustment feature especially for mouse buttons.
Because when we click, we barely get 7 8 cps. We need to be able to set this up.

**Comment by mchnjt** [comment]
Ratio
![](https://media.tenor.com/BVlCSzPsYQQAAAAM/low-tier-god.gif)

**Comment by artdeell** [comment]
skill issue

**Comment by mesflit** [comment]
> skill issue

💀💀💀💀💀
