### ISSUE TITLE
[BUG] screen lags when left or right clicking while looking around

### ISSUE THREAD

**Issue by Stormysoap** [PojavLauncherTeam/PojavLauncher#4130]
⁹### Describe the bug

Whenever I right or left click while looking around there's a sudden freeze when using a physical keyboard and mouse and it's been like this ever since the update which returned offline accounts,I've tried using hello minecraft launcher and the bug isn't there.

### The log file and images/videos

https://youtu.be/fpvqBJJU-gI

### Steps To Reproduce

```markdown
Right or left click while looking around using a physical mouse
```

### Expected Behavior

I expect it to be smooth when performing the action

### Platform

```markdown
- Device model: Samsung galaxy a52
- CPU architecture:
- Android version: 13
- PojavLauncher version: latest release
```

### Anything else?

Only happens with a physical mouse,when changing the attack button to my keyboard it does not happen

**Comment by GaucovyAero** [comment]
samsung issue
