### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Blazingshock** [PojavLauncherTeam/PojavLauncher#4131]
### Describe the bug

The application exited with code -1 because of optifine I don't know what I did to have that but I use forge I even tried optiforge still it said The application exited with code -1 help

### The log file and images/videos

http://adfoc.us/serve/sitelinks/?id=475250&url=http://optifine.net/adloadx?f=OptiFine_1.19.4_HD_U_I4.jar&x=dc08

(Note:Do Not Click On Any Ads Just Press Skip!!)

The log file is here⬇️
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11311877/latestlog.txt)

### Steps To Reproduce

```markdown
Step 1:go to ZArchiver
Step 2:go to Android
Step 3:go to data
Step 4:go to net.kdt.pojavlaunch
Step 5;go to .minecraft
Step 6:go to mods and put optifine 
Step 7:open poojav launcher
It's should say when you press play The application exited with code -1 
(Disclaimer: Enable the hidden files feature on ZArchiver)
```

### Expected Behavior

I expect the game to have forge but also have optifine in it

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by artdeell** [comment]
You did not send the log

**Comment by Blazingshock** [comment]
> You did not send the log

I uploaded it now please do help

**Comment by GaucovyAero** [comment]
> > You did not send the log
> 
> I uploaded it now please do help

you have to keep forge inside .minecraft, not a custom directory
