### ISSUE TITLE
Controller input passthrough to the game

### ISSUE THREAD

**Issue by DrSapling** [PojavLauncherTeam/PojavLauncher#4138]
### Is this request related to a bug?

Somewhat, nut not really.

### Describe the request.

A controller input is covered by the launcher, it is not passed through to the game. I saw that it is mentioned in Readme that controller mods are not working, but there is not explanations (what would be really nice).
This request is somewhat related to the ability to change mapping/flip axis on the built-in controller handler.

### Anything else?

A reason for the controller mods not working would be appreciated (or at least a guess as to why)

**Comment by GaucovyAero** [comment]
there is a controller remapper inside now, on the github actions builds, the controller mods just dont work because they are not made with android inputs in mind
