### ISSUE TITLE
Java Runtime Unsupported for android 10 one 

### ISSUE THREAD

**Issue by SlickAlex** [PojavLauncherTeam/PojavLauncher#414]
Hi , please help me with this : when It put me to install java runtime , it say to install : "Java Runtime arm64/aarch64 (.tar.xz)" but i have 3 java Runtime and not this so I tried with all 3 and it's not working ( when I press play it crash ) so please help me !
 #![Screenshot_20201126-101537](https://user-images.githubusercontent.com/75065761/100324788-62aadd00-2fd0-11eb-95d2-f1d2e7053e78.png)
 #![Screenshot_20201126-101849](https://user-images.githubusercontent.com/75065761/100325085-cfbe7280-2fd0-11eb-8385-417684b98a91.png)

 ◉‿◉

**Comment by WesleyVanNeck** [comment]
if it says use then Java Runtime arm64/aarch64
