### ISSUE TITLE
[F-Req] java 8 and java 17 file

### ISSUE THREAD

**Issue by Yeung1234** [PojavLauncherTeam/PojavLauncher#4140]
### Is this request related to a bug?

Where can give me the java 8 and java 17 file

### Describe the request.

Where can give me the java 8 and java 17 file

### Anything else?

No

**Comment by Jfjfrjdjjd** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/4711942621


https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559
