### ISSUE TITLE
[BUG] bugged textures in 1.14.4

### ISSUE THREAD

**Issue by maurix649** [PojavLauncherTeam/PojavLauncher#4141]
### Describe the bug

in version 1.14.4 the textures are not loaded correctly 

### The log file and images/videos

![Screenshot_20230426_205309_net kdt pojavlaunch](https://user-images.githubusercontent.com/122000593/234748547-1f6c297c-54a5-4e57-b382-e2f6e4f9e0b8.jpg)

### Steps To Reproduce

```markdown
help
```

### Expected Behavior

i expect a solution to play correctly the game in that version 

### Platform

```markdown
- Device model: Huawei Nova 5t
- CPU architecture: 4x ARM Cortex-A55 @ 1.81 GHz
- Android version: 10
- PojavLauncher version: lastest from pl
```

**Comment by Mathias-Boulay** [comment]
Press F11 twice I guess

**Comment by maurix649** [comment]
in muy device F11 Is for screenshots, when i connect a keyboard and mouse
