### ISSUE TITLE
[F-Req] Native OpenGLES 3.2 Support

### ISSUE THREAD

**Issue by Zue5s** [PojavLauncherTeam/PojavLauncher#4142]
### Describe the request.

I'm not a Programmer or anything, but maybe this is possible (there are reasons for this
1. For shaders. Mainly because virglrenderer has problems, and OpenGLES 2.0 doesn't support it, also for ANGLE, no because i am running <1.16.5
2. For better mod compatibility
3. For better stability (idk)

### Anything else?

I dont know how 2 program

**Comment by Mathias-Boulay** [comment]
OpenGL != OpenGL ES
Someone would be welcome to make a PR on the respective renderer repository though
