### ISSUE TITLE
[BUG] Input keys stuck

### ISSUE THREAD

**Issue by theredfire99** [PojavLauncherTeam/PojavLauncher#4143]
### Describe the bug

[Touchscreen] Some input keys stuck when there's a lag spikes or tapping it rapidly

### The log file and images/videos

These list of keys sometimes stuck when there's a lag spikes or when i press it rapidly:

-WASD keys
-Left click and right click key
-Shift key

but when i press ESC key to pause the game and press ESC again to resume, the key no longer stuck.

It makes me fall of the cliff because my character just move by itself.

I play on Fabric 1.19.4 by the way

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

...

### Platform

```markdown
- Device model: Redmi Note 9
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: dahlia-754-57521c196-v3_openjdk
```

**Comment by GaucovyAero** [comment]
known issue, duplicate

**Comment by biRec** [comment]
Дайте ссылку на пост с решением проблемы
