### ISSUE TITLE
[BUG] See through Blocks

### ISSUE THREAD

**Issue by Xenia6780** [PojavLauncherTeam/PojavLauncher#4144]
### Describe the bug

I opened pojav Forge 1.12.2 and used a modpack but when i loaded the world the blocks were see trough

### The log file and images/videos

![Screenshot_2023_0427_185335](https://user-images.githubusercontent.com/131973631/234862169-06ca4a47-ddb7-48f3-92a2-9445e72b5c58.jpg)

### Steps To Reproduce

```markdown
1 Open Pojav
2 load Forge 1.12.2
3 Load mods
4 load world
```

### Expected Behavior

I expect the game to be normal

### Platform

```markdown
- Device model:V2029
- CPU architecture:octa-core MediaTek Helio P35
- Android version:12
- PojavLauncher version:Newest
```

### Anything else?

Idk If its something with my settings or anything else

**Comment by Jfjfrjdjjd** [comment]
Try pressing f11

**Comment by kutschkem** [comment]
Some mods probably cause this, I had this happen in 1.7.10 with cofhcore.

**Comment by Dragonwoolf** [comment]
- Install Optifine
- open settings
- fast render: ON
- It helps me

**Comment by GaucovyAero** [comment]
press f11
