### ISSUE TITLE
[BUG] problem with the "PRI" button on minecraft servers 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#4145]
### Describe the bug

When attacking mobs or players on the server, many hits are simply missed. I don't know why this happens, but I checked the "PRI" button there was no such problem on the old version of PojavLauncher (namely crocus 3.3.1.1) and on the same server on the old version pojav. 

### The log file and images/videos

https://user-images.githubusercontent.com/75908293/234976268-09e9458e-2688-4314-ae31-ad2d0c6558df.mp4

### Steps To Reproduce

```markdown
1 started PojavLauncher 
2 chose Minecraft version 1.16.5 Fabric 
3 launched minecraft 
4 logged into the server 
5 The "Special_PRI" button does not work correctly.
```

### Expected Behavior

I expected the management to work fine on the server 

### Platform

```markdown
- Device model: Huawei nova 9 se 
- CPU architecture: aarch64 adreno 610 (Snapdragon 680) 
- Android version: emui 12 
- PojavLauncher version: latest Release actions
```

**Comment by Mathias-Boulay** [comment]
Not a problem on pojav end as far as I can see.
Pojav only sends the input, which has been received by mc (animation playing)

However, if you could help us reproducing the issue on your end, we might be able to look into it.
Simply give us repeatable steps, the more precise the better

**Comment by Iarkont** [comment]
> Not a problem on pojav end as far as I can see. Pojav only sends the input, which has been received by mc (animation playing)
> 
> However, if you could help us reproducing the issue on your end, we might be able to look into it. Simply give us repeatable steps, the more precise the better

I sent 2 videos for comparison:
This is on new versions of Pojav: 

https://user-images.githubusercontent.com/75908293/236614350-2620b50b-7a69-4315-8b1c-c8ae55c5c6e1.mp4

And now the same thing, but only on version 3.3.1.1 (here the beats are not displayed immediately due to the large ping) 

https://user-images.githubusercontent.com/75908293/236614502-fb87c4cc-ced5-4f73-8cdd-a5bd5a99eea2.mp4

As you can see, on the old version and on the same server, all hits are counted. All the game settings here and there are about the same. PC players, of course, do not have such problems on the server. I can throw off the IP of the server, but I think it is unlikely that you will go to CIS server.
