### ISSUE TITLE
1.16.5 bug

### ISSUE THREAD

**Issue by Vitor998** [PojavLauncherTeam/PojavLauncher#4146]
### Describe the bug

there is a bug when I enter version 1.16.5 it gives bug number 1 and I don't know what to do

### The log file and images/videos

whatnot

### Steps To Reproduce

```markdown
start pojavlaucher I choose forge 1.16.5 and click on play and when I start everything does this
```

### Expected Behavior

wanted to play 1.16.5 with the "optifine" "prime |piece" mods

### Platform

```markdown
- Device model: Galaxy 03
- CPU architecture: ?
- Android version: 12
- PojavLauncher version: new/playstore
```

### Anything else?

Please tell me why i do

**Comment by Jfjfrjdjjd** [comment]
You should at least send the log file, there is too little information to identify the error

**Comment by GaucovyAero** [comment]
missing log file
