### ISSUE TITLE
[BUG] Crash when launching [FORGE] 1.19.4

### ISSUE THREAD

**Issue by Zue5s** [PojavLauncherTeam/PojavLauncher#4147]
### Describe the bug

When i try to launch the game it gives me code 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11358343/latestlog.txt)

### Steps To Reproduce

```markdown
1. Press "Play"
```

### Expected Behavior

I expect FML 2 load

### Platform

```markdown
- Device model: Samsung Galaxy Tab S7
- CPU architecture: Aarch64 / Qualcomm Snapdragon 865
- Android version: 13
- PojavLauncher version: latest on Google Play Store
```

### Anything else?

Only on forge (not on vanilla)

**Comment by HierarchyMan** [comment]
![Screenshot_2023-05-04-09-31-54-95_bab8561a5f94f0a53956d8cbbeaad774.jpg](https://user-images.githubusercontent.com/97939376/236110168-f8c60422-e3d5-42e2-8cdc-4e2b1256f1db.jpg)

Works for me (No Mods) try using -noverify argument

![Screenshot_2023-05-04-09-32-11-48_bab8561a5f94f0a53956d8cbbeaad774.jpg](https://user-images.githubusercontent.com/97939376/236110201-304c5e5a-71cb-4f4c-bd57-8774c9405684.jpg)

And Rubidium and Sodium mods won't let you load into worlds

**Comment by fjdtb** [comment]
> ![Screenshot_2023-05-04-09-31-54-95_bab8561a5f94f0a53956d8cbbeaad774.jpg](https://user-images.githubusercontent.com/97939376/236110168-f8c60422-e3d5-42e2-8cdc-4e2b1256f1db.jpg)
> 
> У меня работает (без модов), попробуйте использовать аргумент -noverify
> 
> ![Screenshot_2023-05-04-09-32-11-48_bab8561a5f94f0a53956d8cbbeaad774.jpg](https://user-images.githubusercontent.com/97939376/236110201-304c5e5a-71cb-4f4c-bd57-8774c9405684.jpg)
> 
> А моды Rubidium и Sodium не позволят вам загружать миры.
