### ISSUE TITLE
Cant use Mouse and buttons at same time on 1.12.2 forge

### ISSUE THREAD

**Issue by TGMobile-leetmuscc** [PojavLauncherTeam/PojavLauncher#415]
please fix this issue

**Comment by WesleyVanNeck** [comment]
use latest dev build

**Comment by TGMobile-leetmuscc** [comment]
i have latest dev build.

**Comment by ghost** [comment]
Please send me a version which will work on my device.
Redmi 8a dual
2 gb ram

**Comment by artdeell** [comment]
use latest

сб, 28 нояб. 2020 г., 07:33 ChargedHat42838 <notifications@github.com>:
