### ISSUE TITLE
[BUG] space in arguments striped incorrectly

### ISSUE THREAD

**Issue by rhjdvsgsgks** [PojavLauncherTeam/PojavLauncher#4152]
### Describe the bug

set jvm args `--add-opens java.base/java.lang=ALL-UNNAMED`. launch. got `Unrecognized option: --add-opensjava.base/java.lang=ALL-UNNAMED` (space been striped)

### The log file and images/videos

```
Info: Custom Java arguments: "--add-opens java.base/java.lang=ALL-UNNAMED"
...
Unrecognized option: --add-opensjava.base/java.lang=ALL-UNNAMED
```

### Steps To Reproduce

```markdown
1. set jvm args `--add-opens java.base/java.lang=ALL-UNNAMED`
2. launch
3. got `Unrecognized option: --add-opensjava.base/java.lang=ALL-UNNAMED`
```

### Expected Behavior

args passed to jvm untouched

### Platform

```markdown
- Device model: not relevant
- CPU architecture:  aarch64
- Android version: 11
- PojavLauncher version: dahlia-763-401e60476-v3_openjdk
```

### Anything else?

maybe here https://github.com/PojavLauncherTeam/PojavLauncher/blob/e85177f56aa08f55bfef2483b4807ed1e44c4f67/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/utils/JREUtils.java#L452

**Comment by khanhduytran0** [comment]
Use the equal sign instead of the space
```
--add-opens=java.base/java.lang=ALL-UNNAMED
```

**Comment by rhjdvsgsgks** [comment]
yes, it works. is that means there is no plan about fix it when using space rather than equal?

**Comment by Mathias-Boulay** [comment]
Hi there, we can probably fix your specific case. The parser works on unspaced strings because a overwhelming majority was not competent enough to put spaces between args, or put spaces were they should be.

**Comment by Mathias-Boulay** [comment]
But first, a question. What lead you to needing this jvm argument ?

**Comment by ah-OOG-ah** [comment]
some mods hack into JVM internals to work
