### ISSUE TITLE
[BUG] Can't install Forge 1.8.9

### ISSUE THREAD

**Issue by RUSTYprince** [PojavLauncherTeam/PojavLauncher#4157]
### Describe the bug

When I try to install it, it crashes and report a "code 1 error" i tried different video solutions but none worked 

### The log file and images/videos

> 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11367547/latestlog.txt)

### Steps To Reproduce

```markdown
1.open jar installer
2.select forge version
```

### Expected Behavior

install without crash

### Platform

```markdown
- Device model: Poco m4 5g pro
- CPU architecture: ARM 64-bit (MediaTek Dimensity 810 (MT6833P))
- Android version: 12 
- PojavLauncher version: Playstore/ most recent complete app-debug (I tested both)
```

### Anything else?

.

**Comment by MegaFaresX** [comment]
Did you try changing the java version to the 8 one

**Comment by RUSTYprince** [comment]
> Did you try changing the java version to the 8 one

I try find it and I could not find

**Comment by RUSTYprince** [comment]
> Did you try changing the java version to the 8 one

I tried idk if i did everything right but it worked either way ( i downloaded on a jre8 and jdk8 archive and add in java manager )

**Comment by RUSTYprince** [comment]
I managed to fix it, I just need to use the installer version instead of the universal
