### ISSUE TITLE
[F-Req] Better instruction to compile and debug

### ISSUE THREAD

**Issue by MikeCoder96** [PojavLauncherTeam/PojavLauncher#4158]
### Is this request related to a bug?

I was trying to implement the joystick input that I already made for another project but this app is a mess with debugging.
I was able to run in Android Studio (even if in the README it is written to build from grandlew) but, when I press play after selected the version and installed JRE, it fail into [this](https://github.com/PojavLauncherTeam/PojavLauncher/blob/v3_openjdk/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/tasks/AsyncMinecraftDownloader.java#L91-L94).
I've compared the downloaded json from the release app and the debug app and they are the same so, I can't understand the problem.
NOTE: I've tried also the gradlew build too but fail with same error

### Describe the request.

Just, focus on instruction for everyone about how compile and debug because that is important to implement some changes

### Anything else?

https://developer.android.com/develop/ui/views/touch-and-input/game-controllers/controller-input
Controller input can be very helpful for someone

**Comment by artdeell** [comment]
And you didn't senf the stacktrace. By the way, controller input is already supported.

**Comment by MikeCoder96** [comment]
> And you didn't senf the stacktrace. By the way, controller input is already supported.

Can you please link me the part of the controller input?
UPDATE: Found, ty

**Comment by artdeell** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/blob/v3_openjdk/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/MinecraftGLSurface.java#L383
