### ISSUE TITLE
The game just restart

### ISSUE THREAD

**Issue by 299212** [PojavLauncherTeam/PojavLauncher#416]
Only shows a grey screen for 5 seconds and then it restarts.

I leave the latestlog.txt
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5605112/latestlog.txt)

**Comment by WesleyVanNeck** [comment]
you dont have anough ram left free

**Comment by khanhduytran0** [comment]
Reduce RAM to 512M, or 256M.
