### ISSUE TITLE
[BUG] Alpha 1.1.2_01 crashes

### ISSUE THREAD

**Issue by KedisPL** [PojavLauncherTeam/PojavLauncher#4160]
### Describe the bug

a1.1.2_01 crashesh at start. Mojang logo appear, but when the Minecraft logo tries to render stone blocks game crashes.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11376991/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select version a1.1.2_01 (Default Render Engine and Java)
3. Start the game
```

### Expected Behavior

Alpha worked without problems on debug version from 2~ months ago, but after updating to latest debug version it crashes.

### Platform

```markdown
- Device model: Asus Zenfone Max M2
- CPU architecture: I dont't know it, but probably x64
- Android version: 11
- PojavLauncher version: Latest Debug (https://github.com/PojavLauncherTeam/PojavLauncher/suites/12602332460/artifacts/674236160)
```

### Anything else?

From what I see every version with the old logo made from appearing blocks crashes.

**Comment by GaucovyAero** [comment]
enter LIBGL_ES=2 into /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt
should launch afterwards
