### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by FalkonelYT** [PojavLauncherTeam/PojavLauncher#4161]
### Describe the bug

I start the game in forge 1.16.5 and while I am playing the game crash

### The log file and images/videos

![Screenshot_20230503_085248_Settings](https://user-images.githubusercontent.com/132433545/235849326-0f090956-bb1e-4166-b4ae-b99d8172c704.jpg)

### Steps To Reproduce

```markdown
1. Start on forge 1.16.5
2. Start playing
3. Randomly crash
Alternative step of 2. Change something on settings
3 crash
```

### Expected Behavior

The game dont crash

### Platform

```markdown
- Device model: Samsung A23
- CPU architecture: idk i cant find it
- Android version: 13
- PojavLauncher version: photo
```

**Comment by HierarchyMan** [comment]
Send logs?

**Comment by GaucovyAero** [comment]
dont allocate too much ram
