### ISSUE TITLE
Add sodium support

### ISSUE THREAD

**Issue by HierarchyMan** [PojavLauncherTeam/PojavLauncher#4163]
### Is this request related to a bug?

Because how pojav launcher is built I don't think it supports sodium renderer natively
Everytime I load into a world with sodium (fabric) installed, the game crashes
I tried fabric 1.19.3 with literally any other mod and it didn't crash
So in short, Sodium mod was causing crashes

### Describe the request.

Therefore, I would like you to add sodium mod support
And if it's not possible to add seamlessly, then
Make a toggle-able switch in game profile editor to specify that sodium mod is gonna be loaded

### Anything else?

This launcher is great and has 98.99% compatibility to all of minecraft (which is great)

**Comment by artdeell** [comment]
Not possible, sodium requires some advanced OpenGL features which we cant implement, because nobody in the team has enough time and/or OpenGL knowledge

**Comment by HierarchyMan** [comment]
> Not possible, sodium requires some advanced OpenGL features which we cant implement, because nobody in the team has enough time and/or OpenGL knowledge

I hope one day pojav launcher will be big enough to add this feature
