### ISSUE TITLE
It is question 

### ISSUE THREAD

**Issue by Ajit6709** [PojavLauncherTeam/PojavLauncher#4164]
### Is this request related to a bug?

I can't find any app to rebuild launcher to run ffmpeg

### Describe the request.

Can you help me ? Also give me some instructions to do that

**Comment by mchnjt** [comment]
Try https://s1.rexdl.com/android/app/APK-Editor-Pro-1.10.0-20210718-Mod-Dark-Armeabi-v7a+Arm64-v8a-www.ReXdl.com.apk

As for the instructions, it should be on https://pojavlauncherteam.github.io/FFMPEG.html

**Comment by Ajit6709** [comment]
Can you give me direct link ?

**Comment by mchnjt** [comment]
What

**Comment by Ajit6709** [comment]
About app link

**Comment by Ajit6709** [comment]
How to add file ?

**Comment by Iarkont** [comment]
Why suffer and embed ffmpeg in the application. To do this, developers have recently made the FFmpeg plugin https://github.com/PojavLauncherTeam/FFmpegPlugin

Download the latest pojavlauncher build from Actions And just install the ffmpeg plugin. I say right away in versions 1.17+ Replay Mod does not see FFmpeg even if it is built into the application

**Comment by Ajit6709** [comment]
How I use it in 1.19.4 ?

**Comment by Iarkont** [comment]
> How I use it in 1.19.4 ?


Are you running ffmpeg in version 1.19.4? Or did I misunderstand you?

**Comment by Ajit6709** [comment]
Yes I am trying to run in 1.19.4
