### ISSUE TITLE
It crashes at mojang screen when i use create mod

### ISSUE THREAD

**Issue by Gullu154221** [PojavLauncherTeam/PojavLauncher#4165]
### Describe the bug

![Screenshot_20230504_125028](https://user-images.githubusercontent.com/132549688/236136687-fd12f324-fe8c-475a-8276-2fda13c7b5a8.jpg)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11394650/latestlog.txt)

### Steps To Reproduce

```markdown
It crashes when it is on mojang screen when i installed the create mod on 1.16.5
```

### Expected Behavior

I expected that it will finnaly take me to title screen

### Platform

```markdown
- Device model: V2059 (2059i
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by artdeell** [comment]
Switch to holy gl4es

чт, 4 мая 2023 г., 10:31 Gullu154221 ***@***.***>:

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.16.5-optifine_hd_u_g8 - OPTIFINE |
| Renderer | VIRGL |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| opengl.generic.error |
