### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by VIPProGamerPlag** [PojavLauncherTeam/PojavLauncher#4170]
### Describe the bug

When Installing optifine it's crash idk why it crash but yeah it happen

### The log file and images/videos

https://user-images.githubusercontent.com/95624703/236412887-d70ce82d-a6f5-45c8-97d1-ad57fa11cdf1.mp4

### Steps To Reproduce

```markdown
1.install .jar
2.crash cuz error 1
```

### Expected Behavior

I expected to install optifine but it's crash and said application/game existed with code 1, check latestlog.txt for more information.

### Platform

```markdown
- Device model: v2027
- CPU architecture: idk
- Android version: 12
- PojavLauncher version: 
dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

Yeah that all

**Comment by GaucovyAero** [comment]
use internal storage - download to select the file instead of downloads
