### ISSUE TITLE
[BUG] Version 1.12.2 rendering error

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#4171]
### Describe the bug

When I started version 1.12.2 with the "Holy GL4ES" renderer, all the edges of the items would be rendered incorrectly, and one edge of the box selection border would be coarse to fine.

### The log file and images/videos

![IMG_20230505_202240](https://user-images.githubusercontent.com/123115192/236456730-672b9be7-192c-4509-9b27-620e86d315c2.jpg)
![IMG_20230505_201736](https://user-images.githubusercontent.com/123115192/236456765-83d113b5-718e-4190-b74e-95ae150993fa.jpg)

### Steps To Reproduce

```markdown
1.Start version 1.12.2 with the "Holy GL4ES" renderer.
```

### Expected Behavior

I hope it can be repaired

### Platform

```markdown
- Device model: OPPO A9/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: LOCAL-2023050
```

**Comment by Mathias-Boulay** [comment]
Your version is curious not gonna lie
