### ISSUE TITLE
[BUG] <No sound in forge 1.2.5 >

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#4172]
### Describe the bug

.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Samsung Galaxy A52 
- CPU architecture: 
- Android version: 13
- PojavLauncher version: pojavlauncher-minecraft-java-edition-for-android-v3-3-1-1-1833-9680ba11b-v3-openjdk
```

**Comment by artdeell** [comment]
Not filled out propely and outdated version of the launcher.

**Comment by Prostop194** [comment]
What version of launcher do I need?

**Comment by Prostop194** [comment]
> Не корректно заполненная и устаревшая версия лаунчера.

what version of launcher do i need?

**Comment by artdeell** [comment]
dahlia-740 or newer

сб, 6 мая 2023 г., 13:07 Prostop194 ***@***.***>:
