### ISSUE TITLE
[F-Req] Silly question about console support

### ISSUE THREAD

**Issue by vico93** [PojavLauncherTeam/PojavLauncher#4173]
### Is this request related to a bug?

Is there any chance we could see this launcher adapted to run ou Playstation 4/5 consoles?

If not, is there any alternative to run MC Java on those consoles?

**Comment by artdeell** [comment]
I don't think so, mainly because we dont have playstations and its not easy to develop for them
And idk about alternatives.

**Comment by MikeCoder96** [comment]
I was wondering same idea recently. I think that on Xbox there be a change due to the possibility to develop via dev mode but for playstation it sound impossible unless you have jailbreak ps4/ps5 and possibility to run homebrew

**Comment by vico93** [comment]
> I was wondering same idea recently. I think that on Xbox there be a change due to the possibility to develop via dev mode but for playstation it sound impossible unless you have jailbreak ps4/ps5 and possibility to run homebrew

Yeah, of course unfortunately i think jailbreak would be a requisite for run such custom software, at least on playstaion line.

What i'm wondering is how it would performance. I know current gen hardware is very powerful, but would be enough to run Java edition?

**Comment by artdeell** [comment]
Let me remind you that modern consoLes are basically regular x86 computers with custom OSes, so yeah, it's more than capable.
