### ISSUE TITLE
[BUG] 1.17+ Replay Mod doesn't see ffmpeg 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#4174]
### Describe the bug

replay mod does not see ffmpeg in versions 1.17+, that is, even if FFmpegPlugin is installed, then replay mod will not see it. I also tried embedding the ffmpeg binary in pojavlauncher itself, but in versions 1.17+ also replay does not see ffmpeg (I copied the path to ffmpeg and pasted it into the replay mod command line) 
![Screenshot_20230504_141538_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/236562295-081f5d39-3ea5-4acb-a654-6c77b2fc4bf6.jpg)

### The log file and images/videos

above 

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. I chose version 1.17 fabric (I also tested it on 1.18.2)
3. Launched minecraft 
4. Opened Replay Record 
5. Tried to render
6. Replay Mod didn't see ffmpeg
```

### Expected Behavior

I expected Replay Mod to see FFmpeg in versions 1.17+

### Platform

```markdown
- Device model: Huawei nova 9 se 
- CPU architecture: aarch64 adreno 610 
- Android version: emui 12 
- PojavLauncher version:latest Release
```

### Anything else?

And one more thing: why can't I copy or move ".mcpr" files to another place, the system simply refuses to interact with these files in the /android/data/net.kdt.pojavlaunch.debug/files/.minecraft/replay_recordings folder. although I can interact with other files in the /net.kdt.pojavlaunch.debug folder

**Comment by aaaapai** [comment]
Плагин "флмпег" заряжен?（Машинный перевод）https://github.com/PojavLauncherTeam/FFmpegPlugin

**Comment by Iarkont** [comment]
> Плагин "флмпег" заряжен?（Машинный перевод）https://github.com/PojavLauncherTeam/FFmpegPlugin

Yes, it is installed, and works fine on version 1.16.5 .

**Comment by gdffgg43g** [comment]
the same problem lol, already wrote to them a long time ago, the plugin has not been updated yet, we are waiting for it to be updated

**Comment by Iarkont** [comment]
> the same problem lol, already wrote to them a long time ago, the plugin has not been updated yet, we are waiting for it to be updated

It's related to Java 17, it's because of it that Replay Mod doesn't want to see FFmpeg

**Comment by gdffgg43g** [comment]
> 

Maybe this will be fixed soon, which I really hope
