### ISSUE TITLE
[BUG] Missing text + game is darker

### ISSUE THREAD

**Issue by damian5466** [PojavLauncherTeam/PojavLauncher#4175]
### Describe the bug

When using Holy GL4ES as a renderer, some text in game is missing and overall image is darker, on ANGLE everything is fine.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11413682/latestlog.txt)

![MC_Menu](https://user-images.githubusercontent.com/52522685/236652568-e41c743d-fa2e-4be6-86be-ec6f0b7111af.png)
![MC_Game](https://user-images.githubusercontent.com/52522685/236652571-43e76c95-9f29-4e6f-90f6-1b75e6d8686b.png)
![MC_Settings](https://user-images.githubusercontent.com/52522685/236652570-6167f74b-9e1f-4ee7-a074-a1310b702a67.png)

### Steps To Reproduce

```markdown
1. Start launcher
2. Launch any game version with GL4ES renderer
```

### Expected Behavior

I expect the game to render correctly

### Platform

```markdown
- Device model: Samsung Galaxy S22 Ultra (Exynos) 12/256G
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Latest build from GitHub Actions
```

**Comment by Mathias-Boulay** [comment]
ooh, if you could get on the pojav discord, we could help you

**Comment by damian5466** [comment]
> ooh, if you could get on the pojav discord, we could help you

Created thread on discord:
https://discord.com/channels/724163890803638273/1105162210382192641
