### ISSUE TITLE
[BUG] Virgl: texture and text issues on fabric 1.19.4

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#4177]
### Describe the bug

here is purely on fabric 1.19.4 without mods
![Screenshot_20230507_165633_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/236682012-a6d6f41b-79a9-4dd0-878e-28d9ba4c7bc0.jpg)

Here the situation is a little better with OptiFabric 
![Screenshot_20230507_164910_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/236682055-b0d5dd0b-1803-4ec8-8770-2fbc88f962b6.jpg)
Even shaders are able to run :) 
![Screenshot_20230507_165327_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/236682090-668bb932-8d30-4b64-a8cc-2c5bd8ffa212.jpg)

### The log file and images/videos

above

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. chose VirGl 
3. Chose fabric 0.14.19-1.19.4
4. Launched Minecraft 
5. Entered the world
```

### Expected Behavior

I expected the textures to render correctly 

### Platform

```markdown
- Device model: Huawei nova 9 se 
- CPU architecture: aarch64 Snapdragon 680 
- Android version: emui 12 
- PojavLauncher version: latest Release actions
```

**Comment by Iarkont** [comment]
Also: it turns out that this is not only on 1.19.4 but also on 1.19.2, but at 1.19.2 it is even worse 
![Screenshot_20230507_232537_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/236701249-5217ac46-b9b7-4218-aae6-d2812af6cc3d.jpg)
![Screenshot_20230507_232609_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/236701296-794137b9-cb85-494e-9ad0-525fabd1b8ed.jpg)

**Comment by Iarkont** [comment]
@Mathias-Boulay Can this problem be solved?

**Comment by GaucovyAero** [comment]
virgl generally does not work well, will not fix
