### ISSUE TITLE
[BUG] <installing .jar issues>

### ISSUE THREAD

**Issue by VIPProGamerPlag** [PojavLauncherTeam/PojavLauncher#4178]
### Describe the bug

When 

https://user-images.githubusercontent.com/95624703/236714023-17e992ae-3674-44fd-ad5f-60bbc911bb1a.mp4

### The log file and images/videos

https://user-images.githubusercontent.com/95624703/236714059-6c54f0fc-a192-4d51-b762-6b47428d355f.mp4

### Steps To Reproduce

```markdown
When install optifine crash error 1.
```

### Expected Behavior

I expect to install optifine but crash

### Platform

```markdown
- Device model: v2027
- CPU architecture:idk 
- Android version: 12
- PojavLauncher version: dahila
```

### Anything else?

Nope

**Comment by MikeCoder96** [comment]
Do not use Google Play version but download from here in github actions. It fixed the problem for me

**Comment by VIPProGamerPlag** [comment]
> Do not use Google Play version but download from here in github actions. It fixed the problem for me

Ok

**Comment by VIPProGamerPlag** [comment]
> Do not use Google Play version but download from here in github actions. It fixed the problem for me

Give me your apk

**Comment by MikeCoder96** [comment]
No!
For your safe DO NOT ASK for apk to anyone. The apk is on Actions in artifacts, check the last commit with the green check and download from there

**Comment by realwawaman** [comment]
> No!
> For your safe DO NOT ASK for apk to anyone. The apk is on Actions in artifacts, check the last commit with the green check and download from there

I cannot find it. Can you help?

**Comment by GaucovyAero** [comment]
dont use the downloads tab, use internal storage - download instead to select your file (and please keep your downloads clean)
