### ISSUE TITLE
[BUG] Ram problem

### ISSUE THREAD

**Issue by Skyla2807A** [PojavLauncherTeam/PojavLauncher#4180]
### Describe the bug

The ram in my phone is not the same as in pojav launcher.

### The log file and images/videos

![IMG_20230508_181044](https://user-images.githubusercontent.com/86230594/236810595-73ec0510-68ab-4da4-b066-7c8384f192ac.jpg)

![IMG_20230508_182828](https://user-images.githubusercontent.com/86230594/236812568-ef44e22a-ab69-4dc6-8e87-e050f1f73df9.jpg)

### Steps To Reproduce

```markdown
‎　
```

### Expected Behavior

Please give a solution

### Platform

```markdown
- Device model:Realme 2 4/64G
- CPU architecture:aarch64
- Android version:9
- PojavLauncher version:v3
```

### Anything else?

I have problem with ram in pojav launcher.

**Comment by artdeell** [comment]
That's because not all of the RAM your phone has can be used by Pojav, since other apps use it too
