### ISSUE TITLE
[F-Req] A way to define resolution scale per profile

### ISSUE THREAD

**Issue by tienthanh2929** [PojavLauncherTeam/PojavLauncher#4181]
### Is this request related to a bug?

N/A

### Describe the request.

A way to describe resolution scale percentage per profile or at least a JVM args that Pojav can understand and scale down the resolution on demand.

Why?
Most average Pojav user don't even realize that they play the game on 100% resolution scale, which equals to over 2K resolution and it can cause extremely bad framerate.

Yes, I do know you can do it manually. But the point is it can also help the modpack creator that can define a recommended resolution scale.

Thanks!

### Anything else?

N/A

**Comment by Mathias-Boulay** [comment]
Hmm.
Your point raises another one I've been asking myself for quite a while.
Should the default resolution be 1080p if the device is capable of more ?

**Comment by tienthanh2929** [comment]
> Hmm. Your point raises another one I've been asking myself for quite a while. Should the default resolution be 1080p if the device is capable of more ?

Can be helpful, but is still not accurate.

From what I observe, I always tell players that use Pojav to use resolutions like 35% and 40%, which is around 480p.
I don't think 80% of players are really capable of playing the game at 1080p with Pojav, unless you have a >$300 phone.
