### ISSUE TITLE
added modpack installation feature 

### ISSUE THREAD

**Issue by lehoanduphong** [PojavLauncherTeam/PojavLauncher#4184]
### Is this request related to a bug?

No

### Describe the request.

I wish there was a modpack installation feature on pojavlauncher, but the old-fashioned manual modpack installation is too time consuming and difficult.

**Comment by MovTery** [comment]
You can try this:
https://github.com/PojavLauncherTeam/CurseForge-GUI

**Comment by lehoanduphong** [comment]
> Bạn có thể thử điều này: https://github.com/PojavLauncherTeam/CurseForge-GUI

I don't know how to use it =)

**Comment by GaucovyAero** [comment]
will be added soon
