### ISSUE TITLE
[BUG] PRI and SEC button doesn't work 

### ISSUE THREAD

**Issue by Ajit6709** [PojavLauncherTeam/PojavLauncher#4185]
### Describe the bug

I started Minecraft version 1.19.4 but important buttons SEC and PRI buttons doesn't work 

### The log file and images/videos

>
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11432320/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher and create control 
2.start version 1.19.4
3.you can click on single player but can't create world
```

### Expected Behavior

I expect I can use controls. I also done clean install yesterday but nothing worked

### Platform

```markdown
- Device model: Samsung galaxy m31
- CPU architecture: 64-bit
- Android version: 12
- PojavLauncher version: LOCAL-20230506
```

**Comment by Ajit6709** [comment]
@artdeell

**Comment by Ajit6709** [comment]
Why developers don't respond

**Comment by VenomousSteam81** [comment]
> Why developers don't respond

Bcuz gae
