### ISSUE TITLE
[F-Req] <Support MidnightControls mod "Touchscreen support". >

### ISSUE THREAD

**Issue by PengLx** [PojavLauncherTeam/PojavLauncher#4187]
### Is this request related to a bug?

In MidnightControls mod, support a touchscreen support in game and add button that style like minecraft bedrock edition.An it also can let player customize button in game. But when I try it, I found it not work in minecraft that running with pojavlauncher.I think maybe the controller that pojavlauncher mabye have bug with touchscreen interface.

### Describe the request.

Do a config for that let pojav not give controller for game.

**Comment by GaucovyAero** [comment]
i have seen some people get it working, so maybe it works now, but it shouldnt work anyway, so do it at your own risk
