### ISSUE TITLE
[BUG] <left click and right click on an actual mouse causesthe screen to lag>

### ISSUE THREAD

**Issue by Dhiiiiiiiii** [PojavLauncherTeam/PojavLauncher#4188]
### Describe the bug

[ACTUAL MOUSE] every time I  press left click or right click on my mouse the screen lags this only happens when i use the latest version of pojavlauncher meanwhile if I use the old version works fine version 

With this bug I can't pvp on the latest version of pojavlauncher 

### Steps To Reproduce

```markdown
I don't know it just happens every time I click right or left click
```

### Expected Behavior

I  expected that I will be able to use keyboard and mouse without any problems

### Platform

```markdown
- Device model: Samsung galaxy a52s
- CPU architecture: 64-bit
- Android version: android 13
- PojavLauncher version: dahlia-8-f527e8a14-v3_openjdk
```

### Anything else?

Please fix this

**Comment by Stormysoap** [comment]
I have the exact same bug on my a52

**Comment by Dhiiiiiiiii** [comment]
Interesting

**Comment by GaucovyAero** [comment]
only happens on samsung devices
