### ISSUE TITLE
Can't type or view mods Config in forge 1.12.2 along with custom key press not working?! 

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#419]
I can't type anything, view the mod Configs or use a custom key press.

**Comment by khanhduytran0** [comment]
Use latest build

**Comment by leetmussc** [comment]
Latest Build Link?

**Comment by khanhduytran0** [comment]
Fabulous! graphics?

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/suites/1576829137/artifacts/28490907

**Comment by khanhduytran0** [comment]
@Accountuser99 so you could not modify forge config?

**Comment by leetmussc** [comment]
I couldn't modify any Config in the forge application

**Comment by Accountuser99** [comment]
When I'm in 1.12.2 forge I can't modify any of the Configs in the Config
menu because the menus aren't working.

Any mod that uses a menu doesn't work.

**Comment by Mathias-Boulay** [comment]
mods config works on the latest google play release, closing issue.
