### ISSUE TITLE
[BUG] .jar installer does not work

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4190]
### Describe the bug

Attempting to use the .jar installer throws an error (1) as soon as a file is selected.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11445908/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Attempt to use the .jar installer
```

### Expected Behavior

The installer for the modloader works without issue.

### Platform

```markdown
- Device model: Samsung Galaxy S20+
- CPU architecture: Probably aarch64
- Android version: 13
- PojavLauncher version: LOCAL-20230506 (though it also happens on the Play Store one)
```

### Anything else?

It works fine on my Samsung Galaxy A21s, which is still on Android 12.

**Comment by GaucovyAero** [comment]
try using the latest play store version
