### ISSUE TITLE
Add FSR 1.0 For Mobile Or FSR 2 For Desktop

### ISSUE THREAD

**Issue by iqbal70** [PojavLauncherTeam/PojavLauncher#4191]
### Describe the request.

I Tried To Play Minecraft Java 1.12.2 OptiFine With 5 Chunk Render Distance And I Got Around 15-20 FPS And Then I Tried To Decrease The Rendering Resolution Into 50%, After That I Got An FPS Improvement To 30-45 FPS But With Blurry Visual, So If We Can Implement FSR Support We Could Get Higher FPS Without Sacrificing Visual Because FSR Is Just Render The Game On Half Of The Resolution And Then Upscale It Into Displays Actual Resolution

**Comment by Mathias-Boulay** [comment]
Sadly opengl is not even on the supported list for FSR
