### ISSUE TITLE
Resource Reload Failed

### ISSUE THREAD

**Issue by BottomotPH29** [PojavLauncherTeam/PojavLauncher#4193]
### Describe the bug

No response

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/82305152/d78928a9-2ba0-4450-b37e-1fd9d2246790

### Steps To Reproduce

```markdown
Start pojav go to settings go to resource pack
Put texture pack "resource reload failed"
```

### Expected Behavior

No response 

### Platform

```markdown
- Device model: Galaxy A12 
- CPU architecture: Aarch64 
- Android version: android 13
- PojavLauncher version: latest
```

### Anything else?

No response

**Comment by Mathias-Boulay** [comment]
how do we get the ressourcepack ?

**Comment by GaucovyAero** [comment]
packs that include custom shaders may not work
