### ISSUE TITLE
[BUG] -1 code cannot play 1,16,5

### ISSUE THREAD

**Issue by gamerogames** [PojavLauncherTeam/PojavLauncher#4195]
### Describe the bug

Cannot play the 1,16,5 version due to -1 error, it requests me to see the **latest log file** but i cannot do anything to the file, i tried with the 3 rendered things i have and none worked, plz help.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/133610176/c5debfab-2e84-42c2-a44f-90568bd32edd

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start the game
3. The error ocurrs
```

### Expected Behavior

**the game should open the game**

### Platform

```markdown
- Device model:vivo y22s
- Android version: 13
```

**Comment by Andrei2013961** [comment]
Что мне делать с световой игрй

**Comment by GaucovyAero** [comment]
no log provided
