### ISSUE TITLE
Stuck on "1 task in progress"

### ISSUE THREAD

**Issue by Qw3rt12212** [PojavLauncherTeam/PojavLauncher#4197]
### Describe the bug

The launcher wont start even after uninstalling it and its stuck on "1 task in progress" i cant even relogin after uninstalling and reinstalling

### The log file and images/videos

![Screenshot_2023-05-16-00-56-29-65_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/80119948/8b7a4152-75f3-4da5-8584-7f026afc1b6a)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.wont start because of the "1 task in progress"
```

### Expected Behavior

I expect the game to launch in about 2-5mins but it has been 10 mins

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
this is an issue with your internet
