### ISSUE TITLE
[BUG] essential causes crash

### ISSUE THREAD

**Issue by rohanatt** [PojavLauncherTeam/PojavLauncher#4199]
### Describe the bug

`
/`

### The log file and images/videos

When I have essential installed my game crashes

### Steps To Reproduce

```markdown
Install forge 
1.8.9 run 
Exit
Install any essential mod
Run again
Crash after 1-2 sec after loading
```

### Expected Behavior

Run completely fine

### Platform

```markdown
- Device model: vivo v10
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: letest version on 2023 may 16
```

**Comment by root-S7** [comment]
send  latest.log File, Please

**Comment by artdeell** [comment]
Then don't have essential installed, simple as that

**Comment by rohanatt** [comment]
> send latest.log File, Please

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11484644/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.8.9-forge1.8.9-11.15.1.2318-1.8.9 - FORGE |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| forge.install.corrupted |

**Comment by rohanatt** [comment]
> Field	Value
> Build type	PRODUCTION
> Pojav version	dahlia - 740 - v3_openjdk
> Minecraft version	1.8.9-forge1.8.9-11.15.1.2318-1.8.9 - FORGE
> Renderer	UNKNOWN
> Architecture	ARM_64
> Java runtime	INTERNAL - JRE - 8
> Java arguments	
> Errors Found:
> forge.install.corrupted

Reinstall forge?

**Comment by Mathias-Boulay** [comment]
#1948 moment
