### ISSUE TITLE
When i use logcat extreme?

### ISSUE THREAD

**Issue by abdo-A028** [PojavLauncherTeam/PojavLauncher#42]
It says about any apps have something wrong

**Comment by abdo-A028** [comment]
I m sure if I used it, it can show us about bugs in Pojavlauncher

**Comment by khanhduytran0** [comment]
It requires root.

**Comment by abdo-A028** [comment]
You used root

**Comment by abdo-A028** [comment]
If you need logcat extreme pro, it could be better

**Comment by khanhduytran0** [comment]
I used root for debugging.

**Comment by khanhduytran0** [comment]
PojavLauncher does not require root to launch.

**Comment by abdo-A028** [comment]
> PojavLauncher does not require root to launch.

Ok
