### ISSUE TITLE
Am I able to install forge 1.4.7?

### ISSUE THREAD

**Issue by kruszala** [PojavLauncherTeam/PojavLauncher#4200]
### Describe the request.

Hi. I'm trying to install forge for Minecraft 1.4.7, but it has no installer. After installing forge by dropping all files from forge universal to "1.4.7.jar", which is the correct folder for this version, it just redownloads old jar file.

**Comment by GaucovyAero** [comment]
read the custom mc guide on the pojav wiki, i think it's in the "going further" tab

**Comment by kruszala** [comment]
> 

You're right. Thank you for help.

**Comment by kruszala** [comment]
> read the custom mc guide on the pojav wiki, i think it's in the "going further" tab

I followed this tutorial and well, it doesn't work. It says in launcher "failed to download Minecraft" and has some more java errors. I tried to install forge 1.4.7 and  download the tekkit lite modpack. Do you have any more ideas as to what I can do?

**Comment by GaucovyAero** [comment]
> > read the custom mc guide on the pojav wiki, i think it's in the "going further" tab
> 
> I followed this tutorial and well, it doesn't work. It says in launcher "failed to download Minecraft" and has some more java errors. I tried to install forge 1.4.7 and download the tekkit lite modpack. Do you have any more ideas as to what I can do?

you modified the json incorrecrtly, the re-doing it and see if you did something wrong
