### ISSUE TITLE
[F-Req] New way of moving

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#4201]
### Is this request related to a bug?

No, I just wish it had a combination of joystick buttons in the custom controls to make it easier for the player to move around

### Describe the request.

Add a joystick like button that allows the player to move forward, backward, side to side, or even sideways
![Screenshot_2023-05-16-18-56-09-17_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/123115192/5259f99f-3eaf-4902-ba08-a99d9e9a9585)

### Anything else?

no

**Comment by mchnjt** [comment]
No WASD game uses a joystick. Don't you also dare bring in your MCinABox/HMCL-PE hypothesis.

**Comment by MovTery** [comment]
> 

Really? I've never used any of the launcher you're talking about. I just like the way they operate. I'm not forcing developers to do anything like this, it's just an opinion

**Comment by GaucovyAero** [comment]
added
