### ISSUE TITLE
[BUG] Black screen Divine Journey 2

### ISSUE THREAD

**Issue by n1ret** [PojavLauncherTeam/PojavLauncher#4202]
### Describe the bug

Black screen on startup.  Removed all optimization mods, nothing changed.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11488767/latestlog.txt)

### Steps To Reproduce

```markdown
1. Setup forge 1.12.2
2. Install Divine Journey 2
3. Start
```

### Expected Behavior

Delete all optimization mods.
Reinstall many times.

### Platform

```markdown
- Device model: POCO F3 8/256
- CPU architecture: ARM64
- Android version: 13
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
remove randompatches
