### ISSUE TITLE
[BUG] Toggling Full screen causes blocks to become transparent

### ISSUE THREAD

**Issue by kutschkem** [PojavLauncherTeam/PojavLauncher#4203]
### Describe the bug

Toggling full screen off with F11 causes blocks to become transparent.

### The log file and images/videos

I checked the log, nothing interesting in there.

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Use HolyGL4ES
3. Start Minecraft (Vanilla 1.7.10)
4. Load world
5. Press F11 to exit fullscreen
6. Optional: go back to fullscreen
```

### Expected Behavior

Going back to full screen returns everything to the state before

### Platform

```markdown
- Device model: Redmi Note 8 Pro
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

I experience this issue often in another context, namely returning after the screen was locked. I hope this issue is related and can help that problem, too. The full screen toggle seems easier to reproduce.

**Comment by Mathias-Boulay** [comment]
Perhaps a video would be helpful

**Comment by kutschkem** [comment]
![2023-05-31_15_45_31](https://github.com/PojavLauncherTeam/PojavLauncher/assets/1106888/0e05ff66-8560-404f-a838-356813aa7436)

@Mathias-Boulay

**Comment by GaucovyAero** [comment]
try updating to the latest play store version

**Comment by kutschkem** [comment]
@GaucovyAero I am on dahlia version.

**Comment by Mathias-Boulay** [comment]
Please, if possible state the FULL version, not the codename

**Comment by kutschkem** [comment]
@Mathias-Boulay  dahlia-740-623f7dd33-v3_openjdk

**Comment by Mathias-Boulay** [comment]
As far as I know, it is fixed on dev versions

**Comment by Mathias-Boulay** [comment]
Yeah it doesn't happen anymore on dev builds, I'll close the issue
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/24864674/952dd28a-1894-4e94-9e82-763c4ed55a13)
