### ISSUE TITLE
[F-Req] Nintendo Switch support

### ISSUE THREAD

**Issue by RiDDeR31** [PojavLauncherTeam/PojavLauncher#4204]
### Describe the request.

I know this is stupid and will take a long time adding suporte and making an NRO or any type of file to make it work, im just saying it would be cool, I'm just asking and I know this wont ever be but if yall want to try it, it would be cool and just so yall know pojav works good in lineage-os

**Comment by artdeell** [comment]
Buy us a switch and we'll consider

**Comment by Mathias-Boulay** [comment]
probably need a hack-able switch tbh

**Comment by ihavefoxdie** [comment]
So, if you were to have a modded switch, you would try to port it to HOS?

**Comment by artdeell** [comment]
> So, if you were to have a modded switch, you would try to port it to HOS?

Likely, sice, at least personally, i wont have much other reasons to own a switch

**Comment by ihavefoxdie** [comment]
> > So, if you were to have a modded switch, you would try to port it to HOS?
> 
> Likely, sice, at least personally, i wont have much other reasons to own a switch

that's just kind of fun to know, honestly.
