### ISSUE TITLE
[BUG] <Application not responding>

### ISSUE THREAD

**Issue by Dragonwoolf** [PojavLauncherTeam/PojavLauncher#4208]
### Describe the bug

Let's start with the fact that I play on the assembly SevTech 1.12.2, Pre-deleting the mod "RandomPatches" (He breaks the game).
The game itself, assembly, works well, FPS is excellent, but When creating a world, a window appears stating that the application is not responding, when you press the continue button, the window is removed, but not for long, literally after a couple of seconds it appears again. Preliminary attempts to solve the problem turned out that this window refers to ANR. Question - how to exclude the appearance of this window?

### The log file and images/videos

No needed

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Joining in world
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Poco F4 GT
- CPU architecture: SnapDragon
- Android version: 13
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by artdeell** [comment]
You just have to wait. Android likely recognizes MC not updating the display as "not responding" so it does that with the dialog.

**Comment by Mathias-Boulay** [comment]
how the fuck does it even detects that
does it freezes the whole app or something ?

**Comment by Dragonwoolf** [comment]
> You just have to wait. Android likely recognizes MC not updating the display as "not responding" so it does that with the dialog.

alas it doesn't work like that, after this window is useful when loading the world, it starts to appear regularly, every 5-6 seconds

**Comment by Dragonwoolf** [comment]
> how the fuck does it even detects that does it freezes the whole app or something ?

I think the system is tracking some indicators, by the type of screen or RAM update, and if there are no actions on them, then it will display this dialog box. The system is responsible for this ANR

**Comment by Dragonwoolf** [comment]
Question is open

**Comment by artdeell** [comment]
> Question is oppen

Android shows the App Not Responding dialog when the inputs into the app haven't veen processed in a long time, which happens when your device is in a very hard deadlock or the game stops receiving inputs (aka, when the screen does not update for a long time)

**Comment by Dragonwoolf** [comment]
> > Question is oppen
> 
> Android shows the App Not Responding dialog when the inputs into the app haven't veen processed in a long time, which happens when your device is in a very hard deadlock or the game stops receiving inputs (aka, when the screen does not update for a long time)

Unfortunately, this window pops up instantly after pressing the button to enter the world, and no matter what I do, no matter how long I wait, the window continues to appear even when the world has already loaded and I’m already playing, Most likely the problem is at the launcher level.

**Comment by Dragonwoolf** [comment]
> > Question is oppen
> 
> Android shows the App Not Responding dialog when the inputs into the app haven't veen processed in a long time, which happens when your device is in a very hard deadlock or the game stops receiving inputs (aka, when the screen does not update for a long time)

Just try to download GT New Horizon(Before starting you need to remove RandomPatcher and Better loading Screen) And try to enter the world. (P.S. You need at least 4GB of RAM)
