### ISSUE TITLE
[BUG] Fabric 0.14.19 for Minecraft 1.18.2 won't launch

### ISSUE THREAD

**Issue by funnsam** [PojavLauncherTeam/PojavLauncher#4209]
### Describe the bug

It'll keep at a black screen.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11508029/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install Fabric 0.14.19 for 1.18.2
2. Launch the Fabric profile
```

### Expected Behavior

The game launches

### Platform

```markdown
- Device model: Samsung Galaxy Note 5
- CPU architecture: aarch64 
- Android version: Android 7.0
- PojavLauncher version: [Latest version at GitHub action || LOCAL-20230517]
```

**Comment by GaucovyAero** [comment]
@VenomousSteam81 moment

**Comment by Miros77** [comment]
same thing

**Comment by GaucovyAero** [comment]
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/dfed794d-8421-4487-b9ec-ae4c8ab37f0a)
