### ISSUE TITLE
Insane lag in 20w22a snapshot

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#421]
Insane lag in 20w22a snapshot

**Comment by khanhduytran0** [comment]
There's no way to fix lag on a snapshot yet. At least change video settings.

**Comment by OwzygZawg** [comment]
This version is the only one that lag, less other versions of the 1.16 snapshots and releases and run with more fps less 20w22a

**Comment by khanhduytran0** [comment]
Maybe switch to Fabulous! graphics?

**Comment by OwzygZawg** [comment]
Did the Fabulous graph come out of Minecraft? because in the mcinabox when putting in the fabulous graph the game comes out I haven't tested this graph in Pojav yet, I believe that in 20w22a there is no fabulous graph

**Comment by OwzygZawg** [comment]
![Screenshot_20201128-234228_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/100530677-b0436780-31d3-11eb-9154-5e710558d3b5.jpg)

**Comment by khanhduytran0** [comment]
Fabulous graphics works on PojavLauncher.

**Comment by OwzygZawg** [comment]
> Gráficos fabulosos funcionam no PojavLauncher.

But in 20w22a it doesn't have the fabulous graph! I'm afraid to put it on this graph and 1.16.3 to crash since it is running super well with jre2 instead of jre9

**Comment by OwzygZawg** [comment]
Shaders work in Pojav in Optifine version 1.16.3?

**Comment by khanhduytran0** [comment]
Yes, but it requires Fabulous! graphics mode.

**Comment by OwzygZawg** [comment]
For shaders to work on Optifine from 1.16.3 in Pojav, does this have to be done with the fabulous graphics?

**Comment by OwzygZawg** [comment]
???

**Comment by khanhduytran0** [comment]
Maybe, I see any tests requires enable Fabulous graphics, otherwise shader will not be rendered.

**Comment by OwzygZawg** [comment]
Ooh

**Comment by OwzygZawg** [comment]
What will not be rendered?

**Comment by OwzygZawg** [comment]
???

**Comment by khanhduytran0** [comment]
> What will not be rendered?

The whole shader.

**Comment by khanhduytran0** [comment]
Also, you are on 32bit which is very slow. Do you have any other device with 64bit support?

**Comment by OwzygZawg** [comment]
No, I only have 32 bits! but jre2 is working fine now i can play at will at 1.16.3 in Pojav, if i use jre9 it crashes at 1.16.3

**Comment by khanhduytran0** [comment]
jre9 is slower than JRE8 (not jre2)

**Comment by OwzygZawg** [comment]
The whole shaders will not be rendering whole ok? but neither the water nor the sun? to say that the shaders works in 1.16.3 in Pojav only that it has 64 bits? I only have 32 bits

**Comment by khanhduytran0** [comment]
I'm unsure if shader work on 32bit or not, but vanilla already too slow, so I guessing shader will freeze or crash the game because of out of memory and other things.

**Comment by OwzygZawg** [comment]
You got me wrong! I said that jre2 is working perfectly on my 32-bit phone! more less the jre9 the jre compatible with my cell phone is the jre2 and the jre9 the jre9 has a bad performance and the jre2 has a great performance

**Comment by khanhduytran0** [comment]
Also, it's JRE8, not JRE2.

**Comment by OwzygZawg** [comment]
Several people use 32-bit shaders on Optifine 1.16.3 on Pojav, why doesn't it work on mine?

**Comment by khanhduytran0** [comment]
> You got me wrong! I said that jre2 is working perfectly on my 32-bit phone! more less the jre9 the jre compatible with my cell phone is the jre2 and the jre9 the jre9 has a bad performance and the jre2 has a great performance

So, how much fps on 1.16.x? I saw your screenshot on snapshot with jre8 only 2fps.

**Comment by OwzygZawg** [comment]
I've gotten used to calling it jre2

**Comment by khanhduytran0** [comment]
> Several people use 32-bit shaders on Optifine 1.16.3 on Pojav, why doesn't it work on mine?

I'm unsure, if you have high enough fps on vanilla 1.16.3 then you might able to run shader.

**Comment by OwzygZawg** [comment]
> > Você me entendeu errado! Eu disse que o jre2 está funcionando perfeitamente no meu telefone de 32 bits! mais menos o jre9 o jre compatível com meu celular é o jre2 e o jre9 o jre9 tem um desempenho ruim e o jre2 tem um ótimo desempenho
> 
> Então, quanto fps em 1.16.x? Eu vi sua captura de tela no instantâneo com jre8 apenas 2fps.

Only 20w22a running at 2 fps! the rest runs more fps

**Comment by khanhduytran0** [comment]
Maybe 20w22a have some changes in graphics render. Maybe switch mipmap and stuff?

**Comment by OwzygZawg** [comment]
I tried everything to make the 20w22a run super well as in 1.16.3 but it didn’t, work for you? want to see how much your wheel runs on 20w22a?

**Comment by khanhduytran0** [comment]
Check https://bugs.mojang.com/browse/MC-186296, it's the issue in snapshot itself.

**Comment by OwzygZawg** [comment]
I know that! but there is no way they can fix a bug in an existing snapshot! so I think it must be lag from the 20w22a version itself

**Comment by OwzygZawg** [comment]
Hmmm

**Comment by khanhduytran0** [comment]
There is a fix https://github.com/jellysquid3/mc186075-fix

**Comment by OwzygZawg** [comment]
Wow, you saved my life! I don't know why I liked the 20w22a version more, thanks now I will close the error

**Comment by OwzygZawg** [comment]
Thanks!!!!!

**Comment by OwzygZawg** [comment]
😄
