### ISSUE TITLE
Plss Update Gl4ES To Opengl 4.6 like angle render

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4211]
### Is this request related to a bug?

To fix bug like texture 

### Describe the request.

Update Gl4ES To Opengl 4.6 plss

**Comment by mchnjt** [comment]
No

**Comment by aaaapai** [comment]
更了也没啥用，最高opengl3.2，恐怕他们没有能力更新至opengl3.2，更别说opengl4.6了。因为gl4es是把opengl转换成opengl ES，opengl ES最高版本是3.2，但是lwjgl对opengl3.2兼容性不佳，恐怕还不如opengl2.1，所以更新至opengl4.6是不可能的。

**Comment by root-S7** [comment]
OpenGL ES ≠ OpenGL
There are rendering bugs even for "Angle"

**Comment by kedrick021** [comment]
Can you add Opengl 4.6 for 1.12.2 no shader support? Like angle render no shader support super fast

**Comment by mchnjt** [comment]
> Can you add Opengl 4.6 for 1.12.2 no shader support? Like angle render no shader support super fast

There. You said what you actually wanted.
Nope. Go plug in a fucking rtx or something to your phone.

**Comment by root-S7** [comment]
> Can you add Opengl 4.6 for 1.12.2 no shader support? Like angle render no shader support super fast

It's not easy to translate, use Chinese:
以下内容仅供参考，
一段废话：似乎做不到，即使是holy渲染器启动1.17+也是补全了少部分高版本OpenGL特性。1.17+使用到OpenGL3.2也只用到了部分特性，而Holy渲染器补全了这部分特性就能启动1.17+。
现阶段手机图形接口似乎做不到100%转换PC上OpenGL 3.0所有特性；也仅仅转换部分OpenGL2.0特性。除非Java版用OpenGL ES在做一份(似乎这不可能)。目前pojav社区几乎没人会OpenGL，OpenGL ES的人；大部分渲染器都是现有项目组合。
对了Angle不支持1.7-1.16.5我估计是angle中lwjglx问题，但也没人研究如何修复
