### ISSUE TITLE
Vic Modern Warfare mod freeze 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4212]
### Describe the bug

When I use gun the game freeze on latest pojavlauncher but I try the old one not freezing 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11513100/latestlog.txt)

### Steps To Reproduce

```markdown
Create world
Get a gun
Freeze screen on latest pojavlauncher
```

### Expected Behavior

Not freeze on mod

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Plss fix

**Comment by Mathias-Boulay** [comment]
#1948
