### ISSUE TITLE
[BUG] mause not working 

### ISSUE THREAD

**Issue by Carol3301** [PojavLauncherTeam/PojavLauncher#4216]
### Describe the bug

So, my mouse stopped working, I can't even enter the game, because I can't select any option on the home screen (like "single player"), clicking with my finger won't work either, I'm using the version 16.5, and I am using the mods: appleskin, mob battle, and demon slayer, and before the mouse works normally 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11523461/latestlog.txt)

### Steps To Reproduce

```markdown
1 I just started povjavlaucher
```

### Expected Behavior

I just expected to the mause to work😭😭

### Platform

```markdown
- Device model: S20 FE 5G
- CPU architecture: kryo 585
- Android version: 13
- PojavLauncher version: Lastest release (dahlia-740-623f7dd33-v3_openjdk)
```

**Comment by MovTery** [comment]
mause是个什么鬼东西哦

**Comment by GaucovyAero** [comment]
try reinstalling pojav
