### ISSUE TITLE
[BUG] Mods not loading on forge 1.12.2

### ISSUE THREAD

**Issue by scpfan69** [PojavLauncherTeam/PojavLauncher#4218]
### Describe the bug

Mods aren't loading

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11524094/latestlog.txt)

### Steps To Reproduce

```markdown
1. Star PL
2. Install forge 1.12.2
3. Install mods
4. Launch MC
```

### Expected Behavior

My game to load mods

### Platform

```markdown
- Device model: REVVL 6 Pro
- CPU architecture: ARM_64 I think or smth like that
- Android version: 12
- PojavLauncher version: dahlia I think? Idk I just got it off Google play
```

### Anything else?

Nope

**Comment by scpfan69** [comment]
UPDATE: I firmly believe this has something to do with PL, as MCinabox works fine
with mods

**Comment by GaucovyAero** [comment]
> UPDATE: I firmly believe this has something to do with PL, as MCinabox works fine with mods

no, this only has stuff to do with your phone, the log is saying "permission denied" on optifine, no other phone does this, which means we can't fix it
try asking for support on revvls website

**Comment by scpfan69** [comment]
> > UPDATE: I firmly believe this has something to do with PL, as MCinabox works fine with mods
> 
> no, this only has stuff to do with your phone, the log is saying "permission denied" on optifine, no other phone does this, which means we can't fix it try asking for support on revvls website

REVVL 6 is a phone made by T-Mobile, plus there still has to be a workaround if MCinabox works..

**Comment by GaucovyAero** [comment]
> > > UPDATE: I firmly believe this has something to do with PL, as MCinabox works fine with mods
> > 
> > 
> > no, this only has stuff to do with your phone, the log is saying "permission denied" on optifine, no other phone does this, which means we can't fix it try asking for support on revvls website
> 
> REVVL 6 is a phone made by T-Mobile, plus there still has to be a workaround if MCinabox works..

mcinabox works because it has the old file structure, but we can't use it because of security reasons, our app won't be able to go on play store if we do it

**Comment by scpfan69** [comment]
> > > > UPDATE: I firmly believe this has something to do with PL, as MCinabox works fine with mods
> > > 
> > > 
> > > no, this only has stuff to do with your phone, the log is saying "permission denied" on optifine, no other phone does this, which means we can't fix it try asking for support on revvls website
> > 
> > 
> > REVVL 6 is a phone made by T-Mobile, plus there still has to be a workaround if MCinabox works..
> 
> mcinabox works because it has the old file structure, but we can't use it because of security reasons, our app won't be able to go on play store if we do it

Well there's gotta be some workaround...

**Comment by scpfan69** [comment]
> > > > UPDATE: I firmly believe this has something to do with PL, as MCinabox works fine with mods
> > > 
> > > 
> > > no, this only has stuff to do with your phone, the log is saying "permission denied" on optifine, no other phone does this, which means we can't fix it try asking for support on revvls website
> > 
> > 
> > REVVL 6 is a phone made by T-Mobile, plus there still has to be a workaround if MCinabox works..
> 
> mcinabox works because it has the old file structure, but we can't use it because of security reasons, our app won't be able to go on play store if we do it

Oh yeah and better yet, T-Mobile says to CONTACT THE DEVELOPER

**Comment by GaucovyAero** [comment]
> > > > > UPDATE: I firmly believe this has something to do with PL, as MCinabox works fine with mods
> > > > 
> > > > 
> > > > no, this only has stuff to do with your phone, the log is saying "permission denied" on optifine, no other phone does this, which means we can't fix it try asking for support on revvls website
> > > 
> > > 
> > > REVVL 6 is a phone made by T-Mobile, plus there still has to be a workaround if MCinabox works..
> > 
> > 
> > mcinabox works because it has the old file structure, but we can't use it because of security reasons, our app won't be able to go on play store if we do it
> 
> Oh yeah and better yet, T-Mobile says to CONTACT THE DEVELOPER

and the developer has literally nothing to do with the issue, nice
never buy a phone from them again i guess

**Comment by khanhduytran0** [comment]
It is recommended to use a third party file manager to copy. Built-in one tends to cause permission issues.

**Comment by scpfan69** [comment]
> 

I used ZARCHIVER, that god?

**Comment by scpfan69** [comment]
> > > > UPDATE: I firmly believe this has something to do with PL, as MCinabox works fine with mods
> > > 
> > > 
> > > no, this only has stuff to do with your phone, the log is saying "permission denied" on optifine, no other phone does this, which means we can't fix it try asking for support on revvls website
> > 
> > 
> > REVVL 6 is a phone made by T-Mobile, plus there still has to be a workaround if MCinabox works..
> 
> mcinabox works because it has the old file structure, but we can't use it because of security reasons, our app won't be able to go on play store if we do it

Ain't there like a option in developer mode to do smth Abt files?
