### ISSUE TITLE
Plss add Opengl 4.6 without shader support 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4220]
### Describe the request.

Plss add Opengl 4.6 without shader support for 1.12.2 to 1.16.5 same on angle render only for 1.17 +

**Comment by scpfan69** [comment]
Bro quit reposting they're not adding that

**Comment by kedrick021** [comment]
They give up on 1.12.2 + 1.16.5 ? Fix glitch and texture bug?

**Comment by hitechbaaz** [comment]
Yas

**Comment by GaucovyAero** [comment]
added in the zink renderer, now in the zink branch on github actions
