### ISSUE TITLE
[F-Req] More Java version options

### ISSUE THREAD

**Issue by Lithum-12** [PojavLauncherTeam/PojavLauncher#4223]
### Is this request related to a bug?

no

### Describe the request.

Some modules require a very high Java version: for example:
Modern UI
Java 17~18(Mc1.18.x),Java16~17(Mc1.17.x),Java11~15(Mc1.16.x),Java8~15(Mc1.15.x).

I would like to add a few more versions of the Java runtime to run such modules, such as java9, which was removed

### Anything else?

The above paragraph, including this one, was completed by me with translation software, because I can't speak English.

**Comment by aaaapai** [comment]
Is Java9 stopped? It's not as good as Java8

**Comment by Lithum-12** [comment]
> Is Java9 stopped? It's not as good as Java8

![Screenshot_2023-05-24-02-58-05-84_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/130177907/3ec3d585-6635-432e-b7f2-e2cc28fa4d80)

**Comment by aaaapai** [comment]
> > Is Java9 stopped? It's not as good as Java8
> 
> ![Screenshot_2023-05-24-02-58-05-84_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/130177907/240392256-3ec3d585-6635-432e-b7f2-e2cc28fa4d80.jpg)

Where？

**Comment by Lithum-12** [comment]
> > > Is Java9 stopped? It's not as good as Java8
> > 
> > ![Screenshot_2023-05-24-02-58-05-84_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/130177907/240392256-3ec3d585-6635-432e-b7f2-e2cc28fa4d80.jpg)
> 
> Where？

![Screenshot_2023-05-27-19-10-03-33_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/130177907/3335c30a-a1a9-4ec6-b56e-29e6b662320e)

国人就用中文发吧 :D

**Comment by MovTery** [comment]
> > > > Is Java9 stopped? It's not as good as Java8
> > > 
> > > 
> > > ![Screenshot_2023-05-24-02-58-05-84_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/130177907/240392256-3ec3d585-6635-432e-b7f2-e2cc28fa4d80.jpg)
> > 
> > 
> > Where？
> 
> ![Screenshot_2023-05-27-19-10-03-33_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/130177907/241384616-3335c30a-a1a9-4ec6-b56e-29e6b662320e.jpg)
> 
> 国人就用中文发吧 :D

6，又不是所有外国人都看得懂中文，也不是所有外国人会使用翻译软件，这毕竟是外国团队所制作的软件，有些时候该用英文就用英文
