### ISSUE TITLE
[F-Req] Three-party server authentication login

### ISSUE THREAD

**Issue by Lithum-12** [PojavLauncherTeam/PojavLauncher#4224]
### Is this request related to a bug?

no

### Describe the request.

For example:
Little Skin
SkinMe
BlessingSkin

### Anything else?

The above including this paragraph is written by translation software, because I can't speak English.

**Comment by aaaapai** [comment]
不可能的，你去看一下官网，我发过类似的建议，结果拒绝了
以前还不让非正版帐户下载运行库
