### ISSUE TITLE
[BUG] error code -1

### ISSUE THREAD

**Issue by Femcil** [PojavLauncherTeam/PojavLauncher#4226]
### Describe the bug

I loaded up my minecraft and it shown the mojang logo perfectly but once the logo disappeared it crashed with error code -1

### The log file and images/videos

![Screenshot_20230522_215603_One UI Home](https://github.com/PojavLauncherTeam/PojavLauncher/assets/114507308/facf3217-2aa6-4aa2-9593-f01bc7693b6d)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11538501/latestlog.txt)

### Steps To Reproduce

```markdown
Use forge 1.19.4
Have like 12 mods
```

### Expected Behavior

The game to launch

### Platform

```markdown
- Device model: galaxy s20
- CPU architecture: idk
- Android version: Samsung galaxy s20
- PojavLauncher version: idk
```

**Comment by GaucovyAero** [comment]
weird, try reinstalling forge maybe
