### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by GermanEnim11** [PojavLauncherTeam/PojavLauncher#4233]
### Is this request related to a bug?

Мне нада войти аккаунт через Pojavlauncher Мне то очень нужна

**Comment by Iarkont** [comment]
а в чем собственно проблема? берешь и регаешься. если без лицензии minecraft не пускает, то тебе вряд ли кто-то поможет. но вроде в сборках из actions есть локальный аккаунт, там просто вводишь ник и всё. 

![Polish_20230526_181954923](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75908293/466f82a0-0f2c-4fe2-898c-663ffe943b57)

**Comment by GermanEnim11** [comment]
Ну я хочу войти аккаунт гугл мой ник ну мне не получается!

пт, 26 мая 2023 г., 21:36 Iarkont ***@***.***>:

**Comment by Iarkont** [comment]
а гугл аккаунт привязан к Microsoft и куплен ли на нём minecraft java edition? просто я тоже использую в качестве входа аккаунт с ".gmail.com" он привязан к Microsoft и естественно там куплен minecraft java edition, и у меня не возникает никаких проблем со входом
