### ISSUE TITLE
[BUG] Application/Game exited with code 1, check latestlog.txt for more details.

### ISSUE THREAD

**Issue by beastboymayu** [PojavLauncherTeam/PojavLauncher#4234]
### Describe the bug

Latestlog: 
Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment, -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader, --add-exports=java.desktop/java.awt=ALL-UNNAMED, --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED, --add-exports=java.desktop/sun.java2d=ALL-UNNAMED, --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED, --add-exports=java.desktop/sun.awt=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED, --add-exports=java.desktop/sun.font=ALL-UNNAMED, --add-exports=java.base/sun.security.action=ALL-UNNAMED, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.desktop/java.awt=ALL-UNNAMED, --add-opens=java.desktop/sun.font=ALL-UNNAMED, --add-opens=java.desktop/sun.java2d=ALL-UNNAMED, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.base/java.net=ALL-UNNAMED, -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/fabric-installer-0.11.2.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1554
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~OWpLZvU-6KDZAbCaDiVLSw==/net.kdt.pojavlaunch-3kHvQzRrVhK-4rW114Zjbg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~OWpLZvU-6KDZAbCaDiVLSw==/net.kdt.pojavlaunch-3kHvQzRrVhK-4rW114Zjbg==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x713397dce8)
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x714c0333d8)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x714c0333d8)

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
N/A
```

### Expected Behavior

N/A

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 13
- PojavLauncher version:
```

**Comment by Return0endline** [comment]
Invalid Renderer (VirGL), and/or missing JRE17 Package.
