### ISSUE TITLE
web version?

### ISSUE THREAD

**Issue by broman2323** [PojavLauncherTeam/PojavLauncher#4235]
### Is this request related to a bug?

no problems

### Describe the request.

basically i want to play minecraft java on web using pojav so can you make a version that is for browsers thanks

**Comment by dachisao** [comment]
Try porting the launcher to WASM. Might take a few years but, who knows ;)

**Comment by A-Random-Person-on-Github** [comment]
https://eaglercraft.ru/p/home/

**Comment by A-Random-Person-on-Github** [comment]
minecraft on web https://eaglercraft.ru/p/home/

**Comment by broman2323** [comment]
no this is cracked minecraft what about non cracked

**Comment by AfMovie** [comment]
i just wanted to piont this is a good idea for the newer versions pojav could port it using html or jave to port pojav to web browser so we could use 1.9 and more recent versions

**Comment by OZZZNY** [comment]
"I really hope that can happen as well (speaking personally)."
