### ISSUE TITLE
[BUG] Stuck at 0%

### ISSUE THREAD

**Issue by JuJuDinkyDoo** [PojavLauncherTeam/PojavLauncher#4236]
### Describe the bug

In the newest Minecraft versions for Optifine and Forge, loading into a world gets stuck at 0%

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/11589865/latest.log)

### Steps To Reproduce

```markdown
1. Use a newer Minecraft version like 1.19.4 for Optifine or Forge
2. Load into a world
3. World loading will be stuck at 0%
```

### Expected Behavior

World should load.

### Platform

```markdown
- Device model: Galaxy Tab A
- CPU architecture: idk what that is lol
- Android version: 11
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

**Comment by artdeell** [comment]
For how long have you tried waiting?

**Comment by JuJuDinkyDoo** [comment]
Like up to 10 minutes

**Comment by GaucovyAero** [comment]
you are probably out of memory
