### ISSUE TITLE
[BUG] Mouse speed adjustment display error

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#4237]
### Describe the bug

Mouse speed adjustment option displayed incorrectly on the in-game menu

### The log file and images/videos

When I open the game menu and click on "Mouse Speed"; After tweaking it, I found that whether I was using a touch screen or an external mouse, the value always showed 0%
Check out this video

https://github.com/PojavLauncherTeam/PojavLauncher/assets/123115192/b900c7bc-80f1-426d-8bea-29fd6407f0bb

### Steps To Reproduce

```markdown
1. Open the menu
2. Open the ”Mouse Speed“ TAB
3. Adjust the value
4. BUG appears
```

### Expected Behavior

Please fix it

### Platform

```markdown
- Device model: oppo A9/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 20230524
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
thanks for reporting, i suppose you are the first person to ever use that option lmao 👍

**Comment by MovTery** [comment]
> thanks for reporting, i suppose you are the first person to ever use that option lmao 👍

Yes, I discovered this bug when I tried to change the sensitivity of my external mouse through the "mouse speed" option😂

**Comment by Blockyguy15** [comment]
Mouse speed can be changed by pointer speed in Assesebility service on
Android

**Comment by GaucovyAero** [comment]
if you want to increase mouse speed in pojav, decrease your mouse polling rate to 125hz (if you can)

**Comment by GaucovyAero** [comment]
closing this as you opened another issue
