### ISSUE TITLE
Screen Freezed Crash While Playing

### ISSUE THREAD

**Issue by Kumababa** [PojavLauncherTeam/PojavLauncher#4238]
### Describe the bug

Application Exited With Code 

### The log file and images/videos

heres the log files

[](https://www.mediafire.com/file/wpbzwfkbbb7y6m8/latest.log/file) 

### Steps To Reproduce

```markdown
playing in my world
sometimes freezed a few seconds
crash code exited
```

### Expected Behavior

i expect to fixed the problem so i don't have to wait over 15mins to rejoin 

### Platform

```markdown
- Device model: VivoY19/128G
- CPU architecture:aarch64
- Android version:12  
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

no

**Comment by artdeell** [comment]
You did not send the log. Make a new issue with latestlog.txt attached.

latestlog.txt can be obtained using the "Share Log" button or manually in /Android/data/net.kdt.pojavlaunch.debug/files/latestlog.txt
