### ISSUE TITLE
[BUG] Pojav launcher install.jar crash

### ISSUE THREAD

**Issue by StuffXD** [PojavLauncherTeam/PojavLauncher#4239]
### Describe the bug

Whenever I try to install optifine, forge, fabric on clicking on install.jar pojav launcher crashes instantly.....      What should I do??  It crashes on older versions too

### The log file and images/videos

![Screenshot_2023-05-30-21-13-45-744_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135044797/98909073-e62b-44d8-86e3-6f4c0419f28d)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Click on install.jar
3. Selecting jar file
4. Crashes instantly
```

### Expected Behavior

I expected to install optifine, forge, fabric.

### Platform

```markdown
- Device model: Poco M4 Pro
- CPU architecture: 64-bit ARMv8-A
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

...

**Comment by artdeell** [comment]
"Latest" is not a version. Latest where?
You did not send the log. Make a new issue with latestlog.txt attached.

latestlog.txt can be obtained using the "Share Log" button or manually in <Internal storage>/Android/data/net.kdt.pojavlaunch.debug/files/latestlog.txt
