### ISSUE TITLE
Aarch 32 runtime jre8

### ISSUE THREAD

**Issue by leetmussc** [PojavLauncherTeam/PojavLauncher#424]

**Comment by WesleyVanNeck** [comment]
Know there is no rn

**Comment by mglovers123** [comment]
J2re-image.tar.xz

**Comment by SavagePy10** [comment]
> J2re-image.tar.xz

Pinned on discord server

**Comment by mglovers123** [comment]
https://drive.google.com/file/d/103EheBh7Vvss7pYKD2m9CG5yRuBOGtJB/view?usp=drivesd

**Comment by Mathias-Boulay** [comment]
Java 8 for aarch 32 is packed with the apk since latest github release, closing issue.
