### ISSUE TITLE
Zink crash on 1.12.2

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4243]
### Describe the bug

Start the pojavlauncher and crash 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11637594/latestlog.txt)

### Steps To Reproduce

```markdown
1. Use zink
2. Start the pojavlauncher
3. Crash the game
```

### Expected Behavior

Work on 1.12.2

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Plss help

**Comment by Iarkont** [comment]
Zink is under development, so we just have to wait for PojavLauncher to be released with stable Zink.

**Comment by GaucovyAero** [comment]
try latest zink from the zink branch on github actions
