### ISSUE TITLE
about zink renderer and virglrenderer

### ISSUE THREAD

**Issue by Ezleak** [PojavLauncherTeam/PojavLauncher#4244]
### Describe the request.

Can zink and virgl's mesa library be integrated and coexist, because the rendering quality of zink is higher but the efficiency is extremely low and the GPU cannot be used for rendering, while virgl is more efficient but the rendering quality is not good, so is it possible to combine virgl with zink Merge and switch freely.

**Comment by mchnjt** [comment]
Keeping two renderers would just increase the bloat codebase-side and we're currently trying to avoid that.

Plus, you cannot switch between renderers on runtime.

**Comment by Ezleak** [comment]
I understand, but the utility of zink is better than virgl.

**Comment by artdeell** [comment]
the thing is, zink does use the gpu, virgl does too
zink is inefficent due to how it is implemented right now, which will be changed later

**Comment by CatWork2403** [comment]
![Screenshot_2023-06-07-09-02-35-39_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135788378/dff843fb-b69c-4443-b3d4-10c0d8fdc42a)
Tôi không biết vì sao nó lại lật màn hình trong khi tôi đang thử nghiệm Shader
