### ISSUE TITLE
[BUG] cant install forge

### ISSUE THREAD

**Issue by ShiftJM** [PojavLauncherTeam/PojavLauncher#4245]
### Describe the bug

Application exited with code 1 when installing forge. I have tried different version of pojav but still cant install forge. Vanilla run normally tho.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11654887/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.install vanilla version
3.start pojav again
4.install forge
5.application exited with code 1
```

### Expected Behavior

I expect pojav to install forge

### Platform

```markdown
- Device model: redmi note 11t pro
- CPU architecture: 64
- Android version: 13
- PojavLauncher version: google store
```

**Comment by ShiftJM** [comment]
😭

**Comment by S4VAIBHAV** [comment]
> sob

Change your runtime and then try installing forge..

**Comment by ShiftJM** [comment]
> > sob
> 
> Change your runtime and then try installing forge..

I have tried newest Java 8 and newest java17 already

**Comment by mchnjt** [comment]
Leave your data turned on while Forge is installing. It downloads several required libraries from it's server. If it still doesn't work then reinstall it.

**Comment by mchnjt** [comment]
If anything else doesn't work, turn on disable sandbox.
