### ISSUE TITLE
[BUG] <Short description>Button stuck without touching

### ISSUE THREAD

**Issue by CaveSpiderII** [PojavLauncherTeam/PojavLauncher#4247]
### Describe the bug

When playing,there is a bad bug.Sometimes the buttons stuck after touching.It can't stop  inputing unless press the button again.It makes the game experence bad.The zip flie below is the control keyboard.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/96042134/31aa5122-6fd0-4a9c-9d87-4b150e21f37b

[keyboard.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/11659506/keyboard.zip)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11659513/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start fabric-1.19.4-1.14.21
2.Join a singleplay world
3.Playing
```

### Expected Behavior

Fix this bug and update on google play store.

### Platform

```markdown
- Device model: RMX3366
- CPU architecture: Qualcomm Snapdragon 870 Octa-core
- Android version: 13
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by ItsManasxD** [comment]
Yeah same issue

**Comment by GaucovyAero** [comment]
known issue, duplicate
