### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4248]
### Is this request related to a bug?

no

### Describe the request.

There should be a way to play online without having to buy x-box live

**Comment by GaucovyAero** [comment]
using online works normally, i have no issues with it (i have never bought xbox live in my life)

**Comment by Scratch-gu** [comment]
How do you do it?

**Comment by ghost** [comment]
> using online works normally, i have no issues with it (i have never bought xbox live in my life)

Do you do servers or what?

**Comment by ghost** [comment]
Bump (Bring up my post)

**Comment by GaucovyAero** [comment]
buy minecraft
