### ISSUE TITLE
[F-req] Pojavlauncher can't get player profilekey

### ISSUE THREAD

**Issue by ShulkerSakura** [PojavLauncherTeam/PojavLauncher#4249]
### Is this request related to a bug?

![Screenshot_2023-06-07-22-25-23-18_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/50770360/cb345812-61f6-4902-9cf3-90fbfbba00ed)

### Describe the request.

Even I refreshed my Microsoft account login , the game session keeps saying that my profile key is lost , chat is disabled and plz try reconnect,when I playing any online-mode=true server or realms server.
And when I checked /sdcard/Android/data/net.kdt.pojav~/files/.minecraft/
It do have no profilekey directory there.

**Comment by GaucovyAero** [comment]
wont fix
