### ISSUE TITLE
I can't install the fabric device: redmi note 7 android 10

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#425]
I can't install the fabric device: redmi note 7 android 10

**Comment by T-CATHOME** [comment]
@khanhduytran0

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by T-CATHOME** [comment]
@khanhduytran0 LD_LIBRARY_PATH = /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server:/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli:/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-bDzHqDVwX6x8vYoWfi3JGQ==/lib/arm64
--------- beginning of crash
--------- beginning of system
--------- beginning of main
S/LaunchJVM(20624): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "
S/jrelog  (20624): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (20624): " unused DT entry: 
S/jrelog  (20624): DT_RPATH
S/jrelog  (20624):  (type 0xf arg 0x450
S/jrelog  (20624): ) (ignoring)
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "
S/jrelog  (20624): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (20624): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20624): 0x81
S/jrelog  (20624):  (ignoring unsupported flags)
S/jrelog  (20624): 
S/LaunchJVM(20624): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
S/jrelog  (20624): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" unused DT entry: DT_RPATH (type 0xf arg 
S/jrelog  (20624): 0x33c0) (ignoring)
S/jrelog  (20624): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=
S/jrelog  (20624): 0x81 (ignoring unsupported flags)
S/LaunchJVM(20624): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "
S/jrelog  (20624): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (20624): " unused DT entry: 
S/jrelog  (20624): DT_RPATH
S/jrelog  (20624):  (type 
S/jrelog  (20624): 0xf
S/jrelog  (20624):  arg 
S/jrelog  (20624): 0x13b8
S/jrelog  (20624): ) (ignoring)
S/jrelog  (20624): 
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "
S/jrelog  (20624): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (20624): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20624): 0x81
S/jrelog  (20624):  (ignoring unsupported flags)
S/jrelog  (20624): 
S/LaunchJVM(20624): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  (20624): " unused DT entry: DT_RPATH (type 0xf arg 0x2196) (ignoring)
S/jrelog  (20624): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/jrelog  (20624): 
S/LaunchJVM(20624): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "
S/jrelog  (20624): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  (20624): " unused DT entry: 
S/jrelog  (20624): DT_RPATH (type 
S/jrelog  (20624): 0xf arg 
S/jrelog  (20624): 0x6a46) (ignoring)
S/jrelog  (20624): 
S/jrelog  (20624): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  (20624): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(20624): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "
S/jrelog  (20624): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  (20624): " unused DT entry: 
S/jrelog  (20624): DT_RPATH
S/jrelog  (20624):  (type 
S/jrelog  (20624): 0xf
S/jrelog  (20624):  arg 
S/jrelog  (20624): 0x4d9
S/jrelog  (20624): ) (ignoring)
S/jrelog  (20624): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  (20624): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(20624): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
S/LaunchJVM(20624): dlopen /data/app/net.kdt.pojavlaunch-bDzHqDVwX6x8vYoWfi3JGQ==/lib/arm64/libopenal.so success
S/LaunchJVM(20624): dlopen /data/app/net.kdt.pojavlaunch-bDzHqDVwX6x8vYoWfi3JGQ==/lib/arm64/libgl04es.so success
S/LaunchJVM(20624): Done processing args
S/LaunchJVM(20624): Found JLI lib
S/LaunchJVM(20624): Calling JLI_Launch
S/jrelog  (20624): OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "
S/jrelog  (20624): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (20624): " unused DT entry: 
S/jrelog  (20624): DT_RPATH
S/jrelog  (20624):  (type 
S/jrelog  (20624): 0xf
S/jrelog  (20624):  arg 
S/jrelog  (20624): 0x8ff
S/jrelog  (20624): ) (ignoring)
S/jrelog  (20624): 
S/jrelog  (20624): WARNING: linker: 
S/jrelog  (20624): Warning: "
S/jrelog  (20624): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (20624): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20624): 0x81
S/jrelog  (20624):  (ignoring unsupported flags)
S/jrelog  (20624): 
S/jrelog  (20624): Loading Fabric Installer: 0.6.1.51
S/jrelog  (20624): 
S/jrelog  (20624): Using latest loader version
S/jrelog  (20624): 
S/jrelog  (20624): Installing [1.14.4] with fabric 0.10.8
S/jrelog  (20624): 
S/jrelog  (20624): Done
S/jrelog  (20624): 
S/jrelog  (20624): Creating profile
S/jrelog  (20624): 
Java Exit code: 0
S/LaunchJVM(20624): Going to free args
S/LaunchJVM(20624): Free done

**Comment by khanhduytran0** [comment]
It's install done! Why don't you read??

**Comment by tttghkg** [comment]
java.lang.IllegalMonitorStateException: object not locked by thread before notifyAll()
	at java.lang.Object.notifyAll(Native Method)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity$4$1.onClick(JavaGUILauncherActivity.java:117)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
@khanhduytran0

**Comment by khanhduytran0** [comment]
Use latest launcher build.

**Pinging me is unnecessary.** @tttghkg

**Comment by tttghkg** [comment]
It crashes when I install fabric.

**Comment by tttghkg** [comment]
@khanhduytran0

**Comment by T-CATHOME** [comment]
@khanhduytran0 I crash when I install fabric.

**Comment by khanhduytran0** [comment]
Use this build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/388664860

**Comment by tttghkg** [comment]
@khanhduytran0 还是会崩溃

**Comment by tttghkg** [comment]
Or will it collapse

**Comment by T-CATHOME** [comment]
@khanhduytran0 Will still collapse.

**Comment by khanhduytran0** [comment]
Try https://github.com/PojavLauncherTeam/PojavLauncher/suites/1576829137/artifacts/28490907

**Comment by khanhduytran0** [comment]
Ignore the crash, and find for fabric version installed, run it

**Comment by pablodz** [comment]
Maybe with new releases can run without problems

**Comment by Mathias-Boulay** [comment]
Stale issue, and newer builds can make use of fabric (eg. PojavOptimize relies on fabric)
Closing the issue.
