### ISSUE TITLE
Part buttons held down abnormally

### ISSUE THREAD

**Issue by routhing** [PojavLauncherTeam/PojavLauncher#4250]
### Describe the bug

My ControlMap part buttons held down abnormally

### The log file and images/videos

VideoLink(CN): 
[BUG'Video](https://skify.lanzouw.com/i5SXT0ykusxg) 

### Steps To Reproduce

```markdown
↑ As described in the uploaded video.
```

### Expected Behavior

I hope to fix this error and bring convenience to the survival challenge held by the Molean'server

### Platform

```markdown
- Device model: Redmi K50
- CPU architecture: D8100
- Android version: 12(MIUI13.0.13)
- PojavLauncher version: LatestVersion(NewZinkRender)
```

**Comment by routhing** [comment]
My ControlMap (Used for emerging problems):

https://skify.lanzouw.com/i3NX70ykvvob

Hardware devices and system settings：Redmi k50，Android12，3200*1440，Android Developer options→smallest width：set400dp（Will change itself to 399dp）

Pojavlauncher settings：ControlMap size: 100%

**Comment by GaucovyAero** [comment]
known issue, duplicate
