### ISSUE TITLE
[BUG] Where's the latest version

### ISSUE THREAD

**Issue by mobei2333** [PojavLauncherTeam/PojavLauncher#4251]
### Describe the bug

I can't find version 1.20 of Minecraft in the latest PojavLauncher

### The log file and images/videos

![Screenshot_2023-06-08-00-14-20-08_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135552755/b68b982e-df26-4606-86dd-6f2b07f864bf)

### Steps To Reproduce

```markdown
I just can't find the latest version in the version list
```

### Expected Behavior

Fix it

### Platform

```markdown
- Device model: OPPO A9/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 20230605
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
restart your launcher dude

![Screenshot_2023-06-07-18-51-11-033_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/2154cf1f-2270-48bf-8cbf-61d252196cf2)
