### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Andrei2013961** [PojavLauncherTeam/PojavLauncher#4253]
### Describe the bug

У меня не работает сетевая игра

### The log file and images/videos

Сетевая игра просит проверить маикрософт но у меня в сё нормально с маикрософт

### Steps To Reproduce

```markdown
Что мне делать
```

### Expected Behavior

Я ожидал игра запустится и будет всё работать

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Я пытался перезагрузка телефон

**Comment by Andrei2013961** [comment]
Что мне делать

**Comment by GaucovyAero** [comment]
log into minecraft.net
