### ISSUE TITLE
[BUG] Multiplayer disabled. Local login

### ISSUE THREAD

**Issue by FilipinoAkoShaders** [PojavLauncherTeam/PojavLauncher#4254]
### Describe the bug

So yeah, i use Local Login, and tried to join our server, i got multiplayer disabled, so basically the bug is I think about the account, he use local login, and multiplayer is disabled

### The log file and images/videos

![received_794190619047020](https://github.com/PojavLauncherTeam/PojavLauncher/assets/92209213/f1f3a4a5-fe1b-42e5-8a2a-c7e05b9bfc21)

### Steps To Reproduce

```markdown
1. Pojav launcher started
2. Minecraft 1.16.5 started
3. Tried to click multiplayer
4. Multiplayer is disabled
```

### Expected Behavior

I don't really expect anything, I just want to know how to fix this

### Platform

```markdown
- Device model: Realme RMX3516
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: lastest from playstore
```

### Anything else?

Nothin

**Comment by NguyenSonhoa** [comment]
Me too, same bro

**Comment by NguyenSonhoa** [comment]
I tryed download hello mc launcher it had got it too

**Comment by ShulkerSakura** [comment]
For now ,only 1.16.4&1.16.5 have this issue , this may cause by the newest mojang policy or something else, I recommend you play other version.

**Comment by FilipinoAkoShaders** [comment]
Ill use 1.12.2 for now

**Comment by dachisao** [comment]
Buy Minecraft.

**Comment by praneel-g** [comment]
> Buy Minecraft.
> 

The issue only exists in 1.16, I just experienced this too
