### ISSUE TITLE
Zink bug

### ISSUE THREAD

**Issue by Abromaster** [PojavLauncherTeam/PojavLauncher#4256]
### Describe the bug

After enabling zink rendering, the game crashes. Version 1.12 starts the game, but freezes a lot and the menu turns into unknown symbols. Newer versions don't launch at all

![Screenshot_20230609-024231_PojavLauncher (Minecraft Java Edition fer Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/59277170/641a3316-dc2c-4bc0-abf8-82c755d9ce9f)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11693073/latestlog.txt)

### Steps To Reproduce

```markdown
start pojav launcher, choose zink renderer, start game.
```

### Expected Behavior

I'm expect for the game to launching

### Platform

```markdown
- Device model: samsung galaxy S20 FE (Snapdragon865)
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: v3_zink_new "Zink, but swapchain-based"
```

**Comment by Iarkont** [comment]
it's surprising that it started on adreno at all, since I can't run new zink on my Snapdragon 680(The game just crashes) . This error is due to the fact that the new zink is under development And we just have to wait for the stable Zink to be released

**Comment by Bel69420** [comment]
Fact : some adreno may work ig

**Comment by Bel69420** [comment]
Unexpected happen that it only works with Mali

**Comment by aaaapai** [comment]
> Unexpected happen that it only works with Mali

Arm Mali-G57 MC4
Failed to start the game

**Comment by Bel69420** [comment]
Using latest zink will crash 1.12.2 on both Mali and Adreno and it has very bad stuttering

**Comment by NotAHero04** [comment]
Zink is **only** ready when it's merged into the main branch. Expect crashes at this time.

**Comment by Abromaster** [comment]
I just watched the tests of people on YouTube. Everyone says Virgl is dead. Although on my device with rather demanding shaders it will show impressive performance. But it has a lot of bugs. Zink has been described as more advanced and stable. But as a result, new versions of Zink don't launch at all :( I hope this will be fixed someday!

**Comment by Abromaster** [comment]
> Удивительно, что он вообще запустился на адрено, так как я не могу использовать новый цинк на своем Snapdragon 680 (игра просто вылетает). Эта ошибка происходит с тем, что новый зинк находится в разработке и нам остается только дождаться выхода стабильного зинка

Don't be offended but your device is pretty slow... I don't see any reason to use Zink or another renderer other than HolyGL4ES.

**Comment by JmisDump** [comment]
device:Vulkan support:Yes 
Adreno (tm)
Qualcomm Snapdragon 680 
When I launched it crashes

**Comment by Bel69420** [comment]
Missing extensions moment

**Comment by Bel69420** [comment]
Adreno moment

**Comment by Iarkont** [comment]
adreno 610 moment

**Comment by JmisDump** [comment]
??

**Comment by Iarkont** [comment]
The current version of Turnip does not support Adreno 610

**Comment by Bel69420** [comment]
Thx for adreno

**Comment by Bel69420** [comment]
Their Vulkan driver is very shit

**Comment by Uacb58** [comment]
Zink

**Comment by resus12** [comment]
I have a poco x4 gt And zink vulkan doesn't work every time I use the graphics engine the application closes I won't even have the game being my mid-high range mobile phone and having support for vulkan
