### ISSUE TITLE
[BUG] Dynamic Surroundings Mod 1.12.2 rendering bug

### ISSUE THREAD

**Issue by Entitygamer66** [PojavLauncherTeam/PojavLauncher#4257]
### Describe the bug

I'm sure that many of you have experienced this issue when installing dynamic surroundings mod. When i move, the textures become white. When i fly, the textures became normal as soon as i hit the ground, the textures became white again. Probably this was the renderer issue. I hope the devs will fix this.

### The log file and images/videos

![2023-06-10_17 39 32](https://github.com/PojavLauncherTeam/PojavLauncher/assets/124508167/05cfd58f-9508-4d35-a638-9195a410b5fe)

![2023-06-10_18 01 54](https://github.com/PojavLauncherTeam/PojavLauncher/assets/124508167/3a7174f3-7d3c-48aa-adb2-cc1af5fd734a)

### Steps To Reproduce

```markdown
1. Install Dynamic Surroundings Mod
2. Launch the game.
3. Enter the world.
4. When entered the world, the bug occurs.
```

### Expected Behavior

I was already expected this to happen.

### Platform

```markdown
- Device model: Vivo Y02s
- CPU architecture: Octa Core
- Android version: 12
- PojavLauncher version: Latest version from Google Play
```

**Comment by GaucovyAero** [comment]
pojav does not support opengl 3.2+

**Comment by Bel69420** [comment]
Way to fix this : use Virgl to fix this

**Comment by Bel69420** [comment]
If you worried about the fps on Virgl, use zink on "Zink : the judge".

**Comment by Entitygamer66** [comment]
> If you worried about the fps on Virgl, use zink on "Zink : the judge".

Yeah, virgl fixes it but its very laggy.

**Comment by Bel69420** [comment]
Actually, zink performance doesn't bad but GL4ES still the fastest renderer.

**Comment by McTutorialID23** [comment]
calm down, I found a way around this.
https://youtu.be/rc5UcBW4ns0

If you don't understand the language, just watch how he does it

**Comment by Entitygamer66** [comment]
> calm down, I found a way around this. https://youtu.be/rc5UcBW4ns0
> 
> If you don't understand the language, just watch how he does it

Okay I'll try.

**Comment by Entitygamer66** [comment]
> calm down, I found a way around this. https://youtu.be/rc5UcBW4ns0
> 
> If you don't understand the language, just watch how he does it

Wow, i can't believe it works, that was an easy solution. Thank you so much.

**Comment by ghost** [comment]
> Wow, i can't believe it works, that was an easy solution. Thank you so much.


If it works now, you should close the issue.

**Comment by Gabriellokoh** [comment]
Turn off the "Footprints" in "effects". 
Footprints=false
