### ISSUE TITLE
[BUG] zink doesn't work well

### ISSUE THREAD

**Issue by laoqijun1** [PojavLauncherTeam/PojavLauncher#4258]
### Describe the bug

The launcher with the zink version that I picked up through actions will be displayed in portrait in minecraft with zink rendering enabled, but I actually want him to display it in landscape as well.
Tried to customize the resolution, the result indicates an error parameter, hope to solve.
Device: Mi Tablet 5 Pro

我通过actions获取的含有zink版本的启动器在启用zink渲染的minecraft里会用竖屏显示，但我实际上也希望他用横屏显示。
尝试了自定义分辨率，结果提示参数出错，希望能解决。
设备：，小米平板5 Pro

### The log file and images/videos

[5_6064176067386542593.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11712241/5_6064176067386542593.txt)
![Screenshot_2023-06-10-18-59-20-613_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128939868/66696280-4bec-4871-a58d-3a80bae473bb)

### Steps To Reproduce

```markdown
The normal startup process can repeat this phenomenon.
正常的启动流程即可复现此现象。
```

### Expected Behavior

It should start in landscape mode.

它应该以横屏的方式启动。

### Platform

```markdown
- Device model: Mi Tablet 5Pro 小米平板5Pro
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: LOCAL-20230605
```

**Comment by GaucovyAero** [comment]
try the latest zink branch
