### ISSUE TITLE
[BUG] upside-down/inverted screen while using VirglRenderer 

### ISSUE THREAD

**Issue by Halahcokcok** [PojavLauncherTeam/PojavLauncher#4261]
### Describe the bug

Upside-down/inverted screen while using VirglRenderer 

### The log file and images/videos

![Screenshot_20230611-111406](https://github.com/PojavLauncherTeam/PojavLauncher/assets/92002679/bb03069a-d62f-49a6-9dfe-3d5893923f40)

### Steps To Reproduce

```markdown
1. Start PojavLauncher (Minecraft 
   1.19 with optifine)
2.Use VirglRenderer
  Runtime Java :jre17-arm64-20210821-release-17
3. Launch the game 
4. the bug occurred while creating or enter the world
```

### Expected Behavior

I hope you can fix the bug quickly:3

### Platform

```markdown
- Device model: TECNO Pova 4 Pro 8/256
- CPU architecture:(Mediatek Helio G99) 2x 2,2 GHz-Cortex-A76
     6x 2 GHz – Cortex-A55 
- Android version: 12
- PojavLauncher version: [Latest Release || dahlia-740-623f7dd33-v3_openjdk]
```

**Comment by MovTery** [comment]
It seems that the problem of picture inversion occurs only when some mobile phones use this renderer

**Comment by GaucovyAero** [comment]
virgl generally does not work very well
