### ISSUE TITLE
Bug Angle Renderer

### ISSUE THREAD

**Issue by McTutorialID23** [PojavLauncherTeam/PojavLauncher#4262]
### Describe the bug

why every time I use Angle Renderer and play version 1.17+ it always crashes and black screen, Even though my cellphone device has pretty good specifications

I hope the Angle Renderer crash and black screen issues can be fixed

### The log file and images/videos

[crash-2023-06-10_21.37.11-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11719564/crash-2023-06-10_21.37.11-client.txt)

this is the crash report file
Btw, this file appears when playing Minecraft 1.17+ using an Angle Renderer on an old device

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Use Angle Renderer
3. Play any versions 1.17+
4. Crash!!
```

### Expected Behavior

Bruuhhh

### Platform

```markdown
- Device model: Xiaomi redmi 9t
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Release | Local20230501
```

### Anything else?

I also hope that this Angle Renderer supports the Snapdragon 439+ and Mediatek G88 chipsets

**Comment by root-S7** [comment]
this log is 1.16.5,Why use angle run 1.16.5？？？

**Comment by McTutorialID23** [comment]
it's just an experiment

**Comment by GaucovyAero** [comment]
angle only works on 1.17+
