### ISSUE TITLE
[F-Req] Better in-game log display

### ISSUE THREAD

**Issue by Lithum-12** [PojavLauncherTeam/PojavLauncher#4263]
### Is this request related to a bug?

no

### Describe the request.

Add an auto-scroll switch for in-game log output
This prevents the automatic scrolling from becoming invisible due to new logs when viewing the low

### Anything else?

The above description is filled by the translation software, because I can't speak English.

**Comment by Felix14-v2** [comment]
I personally just highlight a text in the log output, this prevents it from scrolling. Such a workaround
