### ISSUE TITLE
[F-Req] Change back to the old version name display

### ISSUE THREAD

**Issue by Lithum-12** [PojavLauncherTeam/PojavLauncher#4264]
### Is this request related to a bug?

no

### Describe the request.

I'd like to go back to the old naming scheme, which describes the Minecraft core names, but each core may have a very different name, such as an image, which looks very uncomfortable.
![Screenshot_2023-06-13-01-53-00-99_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/130177907/c38567a0-969e-4cf5-a14c-de31f8d117ee)

### Anything else?

The above description is filled by the translation software, because I can't speak English.

**Comment by aaaapai** [comment]
(Don't know where you're from, default English, machine translation)
I think the current one looks good, but you think the original one looks good.I think we should default to the current version display, you can switch the original version display by setting.
