### ISSUE TITLE
[BUG] Mesa-based renderers on armhf/arm32 don't work

### ISSUE THREAD

**Issue by SolDev69** [PojavLauncherTeam/PojavLauncher#4266]
### Describe the bug

Virgl on arm32 doesn't currently work, and zink doesn't support arm32 yet. ANGLE and GL4ES both do, so I don't know why zink is 64bit only.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11735226/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher on 32bit arm OS
2. try launching with virgl or zink
3. "VirGL: OSMesa buffer flush is DISABLED!"
4. Death
```

### Expected Behavior

I expect the game to not crash with "VirGL: OSMesa buffer flush is DISABLED!" with zink and to have zink binaries on arm32 or just no zink entirely.

### Platform

```markdown
- Device model: Galaxy J8
- CPU architecture: armhf/arm/arm32/armv8l/armv7l (Snapdragon 450 64bit on 32bit OS)
- Android version: 10
- PojavLauncher version: [this commit](https://github.com/PojavLauncherTeam/PojavLauncher/commit/2e17542fc78142d01b9e2913e7470318d6e5a945) (it's showing up as a local build in LATESTLOG and on android even tho it's not
```

### Anything else?

This has been an issue for idk how long. Updating `libOSMesa_8.so` partially works, I'll try seeing if that can fix virgl.

**Comment by GaucovyAero** [comment]
fixed in the latest zink builds
