### ISSUE TITLE
[BUG] holy gl4es got huge performance drop compare to history version

### ISSUE THREAD

**Issue by rhjdvsgsgks** [PojavLauncherTeam/PojavLauncher#4268]
### Describe the bug

when testing with #4246 . i tried to compare performance of different libgl . and found that holy gl4es got huge performance drop compare to gl4es in history commit (fa78ff0642af2adc2b0d2e8ced1741235732ce1b).

my test result:
(old means fa78ff0642af2adc2b0d2e8ced1741235732ce1b. new means 2e17542fc78142d01b9e2913e7470318d6e5a945)
1.16.5, fabric, distance 10, all fancy, super flat, sodium, 540p
new holy gl4es: 1-2 fps
new virgl: 90fps
old gl4es gles2: 200fps
old gl4es gles3: 250fps
old zink: 25fps

### The log file and images/videos

no significant error

### Steps To Reproduce

```markdown
build pojavlaucher by those commit. compare the performance of each libgl
```

### Expected Behavior

holy gl4es got similar performance to old version

### Platform

```markdown
- Device model: a qcom old device
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 2e17542fc78142d01b9e2913e7470318d6e5a945
```

### Anything else?

maybe related: #3759

**Comment by Mathias-Boulay** [comment]
Driver bug moment

**Comment by Mathias-Boulay** [comment]
The issue related is not related though

**Comment by rhjdvsgsgks** [comment]
is there anything i can do to help your debugging?

**Comment by GaucovyAero** [comment]
no
