### ISSUE TITLE
add mod manager

### ISSUE THREAD

**Issue by QuantumnKat** [PojavLauncherTeam/PojavLauncher#4270]
### Is this request related to a bug?

Nah

### Describe the request.

make a mod manager like tlauncher mod manager (cuz it good)

**Comment by Felix14-v2** [comment]
> like tlauncher mod manager

💀



> cuz it good


💀💀💀

**Comment by 5ghzx** [comment]
Well, a mod manager with some optimization mods would be nice.

**Comment by Quan2992** [comment]
No one care about this
