### ISSUE TITLE
[BUG] Redstone glitch

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4272]
### Describe the bug

When you place Redstone then break it and then start breaking the block under then stop abruptly in the middle The block under will look like it's being broken

### The log file and images/videos

I can't find my last log

### Steps To Reproduce

```markdown
1 Start the launch
2 Open any world
3 place Redstone 
4 break redstone and start on block underneath
5 stop abruptly on the block underneath
```

### Expected Behavior

The block underneath should stay looking like it's being broken until you try to break it again

### Platform

```markdown
This doesn't matter as I have done it on multiple devices
```

**Comment by Felix14-v2** [comment]
Wrong place to report Minecraft bugs, this is a launcher repo.
Anyway, see [MC-157404](https://bugs.mojang.com/browse/MC-157404)
If you're registered on the official bugtracker, you can vote and subscribe to this report updates.

**Comment by ghost** [comment]
> Wrong place to report Minecraft bugs, this is a launcher repo. Anyway, see [MC-157404](https://bugs.mojang.com/browse/MC-157404) If you're registered on the official bugtracker, you can vote and subscribe to this report updates.

Oh I thought this was a bug with the launcher not Minecraft itself sorry I will close
