### ISSUE TITLE
[BUG] game not wanting to load

### ISSUE THREAD

**Issue by lolmeme09** [PojavLauncherTeam/PojavLauncher#4273]
### Describe the bug

Hello i'm a player of pojav launcher, earlier i wanted to play the game in 1.16.5 but i couldn't it said that maybe i didn't have connection and all, i put my internet back and it worked, if it's a bug please fix it, if it's a feature, why ? Like i just want to play the game why do i have to put my internet to play ? I'm literally tryna play solo to build but no i need internet and i'm outside, please if it's a feature REMOVE it, the worst feature i've ever seen in this game.

Thank you.

### The log file and images/videos

![Screenshot_20230614_202402_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136636683/9eac209e-a367-4f36-bca9-11158164ac81)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. You have to disconnect from your internet
3. Try and play
```

### Expected Behavior

I expected the game to launch and play.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version:
- PojavLauncher version:
```

### Anything else?

Fix this problem if it's a bug.
Remove this feature if it's a feature.

**Comment by artdeell** [comment]
Press Dhow more and send what it says here

ср, 14 июн. 2023 г., 21:26 lolmeme09 ***@***.***>:

**Comment by lolmeme09** [comment]
Here

![Screenshot_20230615_082100_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136636683/2452c6df-2e9d-4e3c-a300-3d540693b909)
![Screenshot_20230615_082103_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136636683/4dba18f3-46f9-4bca-9051-55691fb024cd)

There's more though

**Comment by lolmeme09** [comment]
Here i took screenshot of the logs bc i can't copy them

![Screenshot_20230615_082103_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136636683/d5f8d746-a0cb-4ec0-b9fa-4a9d87a9f7ed)
![Screenshot_20230615_082100_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136636683/6db4d304-b40c-406b-ba56-f6f53edefad7)

There's more though, i rlly want this to be fixed i just want to play single player

**Comment by lolmeme09** [comment]
I really want this to be fixed or removed if it's a feature of needing connection to play the game while u wanna play solo, i lit just want to mess around in creative and build outside without internet

**Comment by lolmeme09** [comment]
Dude, it's literally a new feature they added, why did they add it ? Wanna know how i know it? I downloaded an old version of the game and downloaded a version without connection, play and guess what ? I can play without internet, why the hell would they add this feature ? It's literally annoying for ppl that just wants to play single player, like i just wanna play single player but i need internet, why did they do that? So annoying they are making their game worse, first in an old version of minecraft with mods if i break or place a block i crash, the game got more laggy, this game is literally getting worse and worse.

**Comment by GaucovyAero** [comment]
it works for me totally fine when offline, im on the latest dev build
you probably had some corrupted minecraft libraries or something like that, you should have tried connecting to the internet, downloading the stuff and disconnecting from the internet, then it should work forever

**Comment by progameir2309** [comment]
Maybe You Dont Have Enough Credits
