### ISSUE TITLE
[BUG] Fps stuck at 0 when using mod sodium/Rubidium 1.16+ on the latest version of Pojavlauncher 

### ISSUE THREAD

**Issue by McTutorialID23** [PojavLauncherTeam/PojavLauncher#4275]
### Describe the bug
EN :
Why since the dahlia version of the Pojavlauncher update, every time I play Minecraft I use the sodium/Rubidium mod on Minecraft 1.16+, The FPS is always at 0 even though when I try to open another application or scroll up the screen is normal / there are no problems  

So it's not the cellphone that's lagging but Minecraft because when I try to press the control, the control works and doesn't freeze

And also even though I've used the sodium/Rubidium patcher, the fps is still at 0, it pisses me off a bit because it wasn't like this before

JP : 
 Pojavlauncher アップデートのダリア バージョン以来、Minecraft をプレイするたびに、Minecraft 1.16 以降でナトリウム/ルビジウム MOD を使用しているのはなぜですか。別のアプリケーションを開こうとしたり、画面を上にスクロールしようとしたりしても、FPS は常に 0 になります。画面は正常/問題ありません。

つまり、遅れているのは携帯電話ではなく、Minecraft です。コントロールを押そうとすると、コントロールは機能し、フリーズしないからです。

また、ナトリウム/ルビジウム パッチを使用したにもかかわらず、fps は依然として 0 です。以前はこのようなことはなかったので、少し腹が立ちます。
 
### The log file and images/videos

-

### Steps To Reproduce

```markdown
1. Update Pojavlauncher (Dahlia version)
2. Play Minecraft 1.16+ with Rubidium/sodium
3. Create new world
3. Woalahh!! Fps is stuck at 0 and doesn't change at all
```

### Expected Behavior

-

### Platform

```markdown
- Device model: Xiaomi redmi 9t
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: New Release On Playstore (Dahlia version)
```

### Anything else?

-

**Comment by selut06** [comment]
u need a patch

**Comment by selut06** [comment]
sodium/rubidium doesn't work properly in gl4es renderer. so use this patch/config [here](https://cdn.discordapp.com/attachments/994411150261362688/1105129448849821857/sodium-mixins.properties) rename the "sodium" to "rubidium" and paste it in config folder in .minecraft
_u dont need to rename if u are using sodium_

**Comment by selut06** [comment]
also, the patcher disabled half of sodium/rubidium performance

**Comment by Lithum-12** [comment]
Please do not use sodium/Rubidium mod on pojavlauncher
Because their renderer, gl4es, is not officially supported by the pojavlauncher
[Uploading 7a82879dbf83fbaf1b67b07fcf3ea74658ef8ecd.png@656w_662h_progressive.webp…]()

**Comment by Lithum-12** [comment]
Please do not use sodium/Rubidium mod on pojavlauncher
Because their renderer, gl4es, is not officially supported by the pojavlauncher

**Comment by AjTheOpsuGamer** [comment]
Bro just say the one at google play store not dahila 2 times

**Comment by GaucovyAero** [comment]
sodium, rubidium and iris generally dont work
