### ISSUE TITLE
[BUG] <fps stuck on 1 in fabric>

### ISSUE THREAD

**Issue by lolmeme09** [PojavLauncherTeam/PojavLauncher#4276]
### Describe the bug

So, it's me, i already did another bug but this time it's different, i use sodium, lithium and all and i got like around 1-200 fps sometimes, now for some reason when i try to join a world, i'm literally stuck on 1 or 2 fps, no more, it's really strange bc before i didn't lag that much but now I'm just stuck in 1 or 2 fps, i don't know if i did anything wrong tho.

### The log file and images/videos

I didn't take a screen or a video.

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. You need fabric with sodium, lithium and some other mods
3. Join a world
```

### Expected Behavior

I expected to have more fps than getting stuck on 1 or 2.

### Platform

```markdown
- Device model: Huawei pot-lx1
- CPU architecture: 
- Android version: 
- PojavLauncher version: not that old version of the game but not the newer one.
```

### Anything else?

I did download an old version of the game bc of the new internet feature where u need internet to play literally single player.

**Comment by GaucovyAero** [comment]
you have to specify a lot more stuff (game version, renderer, exact pojav version) for us to know what issue it is
