### ISSUE TITLE
More RAM options

### ISSUE THREAD

**Issue by victorkayne2nd** [PojavLauncherTeam/PojavLauncher#4278]
### RAM reading bug

Should improve the RAM detection, including the ZRAM, because probably the latest version's RAM allocation is too limited, or specify RAM more manually.

### Suggestion

A good idea for the RAM use is typing number of RAM and/or use the slider

### So,

I would like to use mora RAM because I have 12GB ZRAM, and the PojavLauncher uses my 6GB physical memory.

**Comment by GaucovyAero** [comment]
zram is basically just using your cpu to compress the memory usage of other programs, it does not add any gigabytes, its just that more zram means more load for your cpu, therefore less fps
