### ISSUE TITLE
[BUG] pojavlauncher error after using virglrenderer on my device

### ISSUE THREAD

**Issue by valterineCraft** [PojavLauncherTeam/PojavLauncher#4279]
### Describe the bug

 Hola I'm having problems with the virglrenderer,the problem is simple but leaves the game impossible to play When I end up creating a world and after it fully loads I walk forward and it turns out that for no reason my Hud is upside down

### The log file and images/videos

Error
java.io.IOException: Permission denied: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/latestlog.txt
	at l.ۦ۫ۖ.۬ۜ(0AZ9:323)
	at l.۠ۢۗ.۟ۦ(718B:273)
	at l.۟۬ۗ.۬(UB35:124)
	at l.۟۬ۗ.۬(Native Method)
	at l.۬ۢۘ.call(SAU0:364)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
When I enter the world after taking a few steps in the game it turns out that my hud is upside down and I can not fix or rotate the screen to another position
Ps:This happens only when I use the virglrender
```

### Expected Behavior

I was hoping the game wouldn't bug that way since that was the only problem I encountered
Ps: the letters are also inverted

### Platform

```markdown
- Device model: A22
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: LOCAL-20230618
```

### Anything else?

In addition to the screen and the inverted Hud the letters are also inverted
Note: I do not speak fluent English and I am using Google translate And because of that, it may have some words, it may end up having some typos, both due to the translator and the way I speak, which may be offensive to some people, due to the culture of each country having differences of thickening, which for some may be yes, offensive... So if I offended someone by some offensive word it will be due to the culture of my country and probably also of GO

**Comment by GaucovyAero** [comment]
virgl generally does not work well
