### ISSUE TITLE
[Bug] Angle renderer does render blocks

### ISSUE THREAD

**Issue by kingsmen1234** [PojavLauncherTeam/PojavLauncher#4280]
### Describe the bug

When I run any version after 1.17 using angle it will load in the game and run fine but blocks are invisible yet moving contraptions for the create mod still render

### The log file and images/videos

No crashes and the log states the renderer is working

### Steps To Reproduce

```markdown
1 go to setting and activate angle renderer
2 load the game
```

### Expected Behavior

I expected a normal visible game

### Platform

```markdown
- Device model: fire HD 10[11th generation]
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: latest release
```

### Anything else?

I was just trying to use the create mod

**Comment by GaucovyAero** [comment]
create only works on gl4es and zink on snapdragon devices
