### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by zybzbk** [PojavLauncherTeam/PojavLauncher#4282]
### Describe the bug

Use java 8 to start Minecraft 1. 16. 5 flashed back after a while, java17 collapsed directly, and java21 also started and collapsed for a while, Logs using java21 detected an unsupported version of JNI, which may cause a crash. Please notify the LWJGL developer and it's over,When starting with the built-in java, the log to the back-end library: LWJGL version 3.3.1 snapshot is finished.

### The log file and images/videos

none

### Steps To Reproduce

```markdown
1. Open pojavlauncher
2. Start minecraft
```

### Expected Behavior

I hope this problem can be resolved

### Platform

```markdown
- Device model: V2057A
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Beta‖version LOCAL-20230619
```

### Anything else?

none

**Comment by GaucovyAero** [comment]
no log provided
