### ISSUE TITLE
[F-Req] does Create mod work now?

### ISSUE THREAD

**Issue by ZGStuff** [PojavLauncherTeam/PojavLauncher#4283]
### Is this request related to a bug?

Just wondering if the Create mod works now.

**Comment by ZGStuff** [comment]
Also someone update the wiki, its kinda out of date

**Comment by Bel69420** [comment]
Actually, Create works on pojav but there's a one problem. (Mali doesn't work with Create) Only Adreno can run Create mod

**Comment by Bel69420** [comment]
I hope you have a Snapdragon phone but if you doesn't have it then you're out of luck

**Comment by cyriotic3** [comment]
> Actually, Create works on pojav but there's a one problem. (Mali doesn't work with Create) Only Adreno can run Create mod

create does work on mali, you need to use ANGLE renderer, would probably be slower than holy but it works

**Comment by Bel69420** [comment]
Yeah, the performance become half but at least flywheel doesn't have any problem with Angle

**Comment by ZGStuff** [comment]
Thank God, I was hoping to screw around with trains on my way to school.

**Comment by ZGStuff** [comment]
Phew i have snapdragon

**Comment by Looksc** [comment]
i have a snapdragon phone
How do I run create mod?

Sorry, my English is bad

**Comment by Looksc** [comment]
> I hope you have a Snapdragon phone but if you doesn't have it then you're out of luck

i have a snapdragon phone
How do I run create mod?

Sorry, my English is bad, I'm using google translate

**Comment by Bel69420** [comment]
use GL4ES

**Comment by Bel69420** [comment]
And do /flywheel backend off before placing create stuff

**Comment by Looksc** [comment]
> And do /flywheel backend off before placing create stuff

Earlier I tried to create a mod in 1.19.2 and the result was a force close when I wanted to enter the world

i am using pojav launcher version: dahlia-740-623f7dd33-v3openjdk,

And my android is 7.1

Thank you for replying to my comment

Sorry again for this bad english

**Comment by Looksc** [comment]
> use GL4ES

Only for 1.16.5?

**Comment by ZGStuff** [comment]
> > And do /flywheel backend off before placing create stuff
> 
> Earlier I tried to create a mod in 1.19.2 and the result was a force close when I wanted to enter the world
> 
> i am using pojav launcher version: dahlia-740-623f7dd33-v3openjdk,
> 
> And my android is 7.1
> 
> Thank you for replying to my comment
> 
> Sorry again for this bad english

Download the latest build of Pojav from Google Play Store. If it's the latest version of GPlay Store, update Android if possible. what phone do you have?

**Comment by GaucovyAero** [comment]
it only works with snapdragon socs on gl4es
