### ISSUE TITLE
[BUG] Security issues

### ISSUE THREAD

**Issue by Lithum-12** [PojavLauncherTeam/PojavLauncher#4284]
### Describe the bug

On oppo's ColorOS 12.1-Android 12, Mobile Manager detects the latest version of pojavLauncher as a fraud virus

### The log file and images/videos

![Screenshot_2023-06-20-12-02-44-12_035d55d4552197c94b0185899d8a326c](https://github.com/PojavLauncherTeam/PojavLauncher/assets/130177907/bdbd94b5-3107-4e9f-80a0-15fce7e43116)
![Screenshot_2023-06-20-12-02-46-39_035d55d4552197c94b0185899d8a326c](https://github.com/PojavLauncherTeam/PojavLauncher/assets/130177907/ef6da7eb-2155-498f-9a8c-79dc78c211ba)
This app is suspected of fraud, please use it with caution

### Steps To Reproduce

```markdown
1.Automatic oppo scanning
2. Virus found
```

### Expected Behavior

It shouldn't be a virus.

### Platform

```markdown
- Device model: OPPO Reno4 Pro 5G
- CPU architecture: arm64-v8a_AArch64
- Android version: 12
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

The above content is completed by translation software.The above content is completed by translation software, because I can't speak English.

**Comment by NotAHero04** [comment]
You can temporary hide the warning by tapping on "Add to whitelist" or whatever is showing on your phone. Of course, we do not intend to code a virus pretending to be a Minecraft launcher.

**Comment by aaaapai** [comment]
This damn Tencent.

**Comment by Mathias-Boulay** [comment]
Technically, the app allows you to execute foreign code like minecraft, forge/fabric installer... Wouldn't be surprised if it triggered the package detection
