### ISSUE TITLE
[BUG] <Forge 1.7.10 no sound>

### ISSUE THREAD

**Issue by PhantomCrafter868** [PojavLauncherTeam/PojavLauncher#4286]
### Describe the bug

All the other forge versions up to 1.20 are working fine,but the 1.7.10 is without any sound(click buttons,breakblocks,mobs,etc)The normal 1.7.10 is with sounds but not the forge ver.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11805818/latestlog.txt)

### Steps To Reproduce

```markdown
I started it normaly,and it was without sound.
```

### Expected Behavior

All forges work normally idk whats wrong.

### Platform

```markdown
- Device model: Galaxy A32
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: LOCAL-20230619
```

### Anything else?

I tried reloading resource packs,F3+S,F3+T,none solutions i searched for worked

**Comment by aaaapai** [comment]
version 1.6.4 also has this problem.

**Comment by PhantomCrafter868** [comment]
I updated pojav to LOCAL-0230621(latest 
[feat/lwjgl-3.3.1]) and the sound was back. I still dont know what caused it.
