### ISSUE TITLE
<Crash or game exited code -1 or 1>

### ISSUE THREAD

**Issue by GALACTICGAMR** [PojavLauncherTeam/PojavLauncher#4287]
### Describe the bug

Whenever i try to install OF,fabric,forge or open minecraft (for launching minecraft this happens sometimes) it crashes a lot too

Please clear my issue:
Why it crashes?
Why it show me this code?

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: LOCAL-20230620
Info: Architecture: arm
Info: Device model: samsung SM-T515
Info: API version: 30
Info: Selected Minecraft version: 1.19.4-OptiFine_HD_U_I4
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=1152
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~Dmd4lcHj7p2zXzQrzQ8vFg==/net.kdt.pojavlaunch.debug-ir2JPqVvtpkOxbmTG5Y7yA==/lib/arm
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/~~Dmd4lcHj7p2zXzQrzQ8vFg==/net.kdt.pojavlaunch.debug-ir2JPqVvtpkOxbmTG5Y7yA==/lib/arm
Added custom env: POJAV_RENDERER=opengles3_desktopgl_angle_vulkan
Added custom env: LIBGL_ES=3
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: POJAVEXEC_EGL=libEGL_angle.so
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
--------- beginning of system

--------- beginning of main

I/jrelog  (18231): dlopen libtinywrapper.so success
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjli.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjli.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/server/libjvm.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/server/libjvm.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libverify.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libverify.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjava.so failed: dlopen failed: "/data/data/net.kdt.pojavlaun
ch.debug/runtimes/bin-arm64.tar.xz/lib/libjava.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libnet.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libnet.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libnio.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libnio.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt_headless.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt_headless.so" is 64-bit inste
ad of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libfreetype.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libfreetype.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libfontmanager.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libfontmanager.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjdwp.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjdwp.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libj2gss.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libj2gss.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjavajpeg.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjavajpeg.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libsctp.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libsctp.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjawt.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjawt.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjimage.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjimage.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libmanagement.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libmanagement.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjli.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjli.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libdt_socket.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libdt_socket.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libinstrument.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libinstrument.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libj2pkcs11.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libj2pkcs11.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libzip.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libzip.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/librmi.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/librmi.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libextnet.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libextnet.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libfontmanager.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libfontmanager.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libmanagement_ext.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libmanagement_ext.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libnet.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libnet.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/n
et.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjava.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjava.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libnio.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libnio.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt_xawt.so success
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt_headless.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libawt_headless.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/liblcms.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/liblcms.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libmlib_image.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libmlib_image.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/server/libjvm.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/server/libjvm.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/server/libjsig.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/server/libjsig.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libverify.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libverify.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libprefs.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libprefs.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libmanagement_agent.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libmanagement_agent.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjaas.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjaas.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjsig.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libjsig.so" is 64-bit instead of 32-bit
I/jrelog  (18231): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libfreetype.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/runtimes/bin-arm64.tar.xz/lib/libfreetype.so" is 64-bit instead of 32-bit

I/jrelog  (18231): dlopen /data/app/~~Dmd4lcHj7p2zXzQrzQ8vFg==/net.kdt.pojavlaunch.debug-ir2JPqVvtpkOxbmTG5Y7yA==/lib/arm/libopenal.so success

I/jrelog  (18231): Done processing args

Java Exit code: -1
I/jrelog  (18231): JLI lib = NULL: dlopen failed: library "libjli.so" not found
I/jrelog  (18231): Going to free args
I/jrelog  (18231): Free done

![Screenshot_2023-06-21_182906](https://github.com/PojavLauncherTeam/PojavLauncher/assets/110534809/70423c36-ad1b-472d-a634-cfde882094c3)

### Steps To Reproduce

```markdown
I started pojav launcher normally on 1.19.4 no optifine or anythihg but it crashes or shows game exited with code -1 or 1
```

### Expected Behavior

Every time i started pojav Launcher it worked normally (past) idk whats causing this

### Platform

```markdown
- Device model: Galaxy Tab A
- CPU architecture: armv8l
- Android version: 11
- PojavLauncher version: Version LOCAL-20230619
```

### Anything else?

It crashes a lot
My Device :
2gb Ram
600MB ram alloation (pojav)
Renderer : Angle (pojav)
Java runtime: jre8 (pojav)
Kernel architecture : armv8l

**Comment by GALACTICGAMR** [comment]
Plz help

**Comment by aaaapai** [comment]
Is your phone 32-bit or 64-bit?

**Comment by Flyrder** [comment]
Minecraft 1.16.5 and above requires Java 17，So do it

**Comment by ratsarecute2012** [comment]
Im using a Mac and the Mod will not respond

**Comment by GaucovyAero** [comment]
use the default java runtime
