### ISSUE TITLE
When Loading Texture Pack Game Crashes

### ISSUE THREAD

**Issue by SahiliBro** [PojavLauncherTeam/PojavLauncher#4288]
### Describe the bug

In the latest versions 1.19.4+ when loading texture pack the game crashes. So there is a server mcci it requires a custom texture pack to play when i tried to load that texture pack at first everything was normal but as the loading reaches the halfway my game crashed but when i tried to load it in 1.16 it didn't crash.

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11818788/latestcrash.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11818791/latestlog.txt)
[crash-2023-06-21_00.00.02-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11818800/crash-2023-06-21_00.00.02-client.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Go to MCCisland Server 
3. Download the texture pack
4. Load the texture pack
5. And then crash
```

### Expected Behavior

I expected that my texture pack will load and i will able to play

### Platform

```markdown
- Device model: Samsung Galaxy A10 
- CPU architecture: 
- Android version: 10
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
should be fixed in the latest play store version
