### ISSUE TITLE
Add an Option to Add Modpacks

### ISSUE THREAD

**Issue by SahiliBro** [PojavLauncherTeam/PojavLauncher#4290]
### Describe the request.

In Current Pojavlauncher we have to download the mods individually and place it in the folder manually. But if you add an option to directly install modpacks then it will save so much time.

**Comment by ghost** [comment]
The PojavLauncher dev team have already said that they will not add this.

**Comment by artdeell** [comment]
But, we will.

чт, 29 июн. 2023 г., 17:34 OtterDev ***@***.***>:

**Comment by ghost** [comment]
oh.

**Comment by GaucovyAero** [comment]
will be added
