### ISSUE TITLE
<Which jre should i use?>

### ISSUE THREAD

**Issue by GALACTICGAMR** [PojavLauncherTeam/PojavLauncher#4291]
### Is this request related to a bug?

Because my game lags & crashes a lot. So, I hwvento prevent that btw my ram is 2gb. Also , My game crashes a lot when i launch fabric with mods (that give FPS) is this is a bug for mod loaders?

### Describe the request.

Please give me some instructions so i prevent these crashes and lags . And, If this is a bug for mod loaders then please fix this.
I play on the lowest settings i can play

**Comment by lava191810** [comment]
If you are running low on memory, reduce the number of modpacks you load and optionally add mods that optimize memory usage.
If your game keeps crashing, upload the launcher log and the game log (along with crash reports).

**Comment by GALACTICGAMR** [comment]
Tell me your discord and I will share the logs to you

**Comment by lava191810** [comment]
I'm sorry, I don't have a discord account.
Can you upload logs on this issue?

**Comment by qaq1000w** [comment]
> ### 此请求是否与错误相关？
> 因为我的游戏经常滞后和崩溃。所以，顺便说一句，我必须防止我的内存是 2GB。另外，当我启动带有 mods（提供 FPS）的 Fabric 时，我的游戏经常崩溃，这是 mod 加载器的错误吗？
> 
> ### 描述请求。
> 请给我一些指示，以便我防止这些崩溃和滞后。并且，如果这是模组加载器的错误，请修复此问题。 我用可以玩的最低设置进行游戏
> 
> ### 还要别的吗？
> _没有反应_



> ### 此请求是否与错误相关？
> 因为我的游戏经常延迟和崩溃。所以，顺便说一句，我必须防止我的内存为 2GB。另外，当我启动带有 FPS（提供 FPS）的 Fabric 时，我的游戏崩溃，这是 mod 加载设备的错误吗？
> 
> ### 描述请求。
> 请给我一些指示，以便我防止这些崩溃和延迟。并且，如果是模组加载器的错误，请修复此问题。 我用可以玩的最低设置进行游戏
> 
> ### 还要另外吗？
> _没有反应_

sodium?

**Comment by lava191810** [comment]
Please provide log and crash-report (if available).

在 2023-07-15 12:00:31，qaq1000w ***@***.***> 写道：


此请求是否与错误相关？

因为我的游戏经常滞后和崩溃。所以，顺便说一句，我必须防止我的内存是 2GB。另外，当我启动带有 mods（提供 FPS）的 Fabric 时，我的游戏经常崩溃，这是 mod 加载器的错误吗？

描述请求。

请给我一些指示，以便我防止这些崩溃和滞后。并且，如果这是模组加载器的错误，请修复此问题。 我用可以玩的最低设置进行游戏

还要别的吗？

没有反应

此请求是否与错误相关？

因为我的游戏经常延迟和崩溃。所以，顺便说一句，我必须防止我的内存为 2GB。另外，当我启动带有 FPS（提供 FPS）的 Fabric 时，我的游戏崩溃，这是 mod 加载设备的错误吗？

描述请求。

请给我一些指示，以便我防止这些崩溃和延迟。并且，如果是模组加载器的错误，请修复此问题。 我用可以玩的最低设置进行游戏

还要另外吗？

没有反应

sodium?

**Comment by qaq1000w** [comment]
I need
/mods

**Comment by dachisao** [comment]
....which mods.

**Comment by GaucovyAero** [comment]
dont use many mods and dont put your ram allocation too high
