### ISSUE TITLE
Add auto allocated ram again 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4292]
### Is this request related to a bug?

Plss add auto allocated ram is easy to find how much ram I need to use

### Describe the request.

Plss add auto allocated ram is easy to find how much ram I need to use

**Comment by hiimabignoobwihenolive** [comment]
Won't happen L

**Comment by Miuhp100** [comment]
Miuhp100

**Comment by hiimabignoobwihenolive** [comment]
Correct

**Comment by GaucovyAero** [comment]
no
