### ISSUE TITLE
[BUG] <Render Error>

### ISSUE THREAD

**Issue by PhantomCrafter868** [PojavLauncherTeam/PojavLauncher#4293]
### Describe the bug

Upon loading 1.20 i entered a world and the textures were all dark. Also the entities/player were red colored as if were taking damage,some items were also black but others were also red. All the texts for options,quit game,etc were all with black letters.

### The log file and images/videos

![Screenshot_20230622_154346_PojavLauncher (Minecraft Java Edition fer Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/111135067/9d1f72ae-d07b-44ec-a828-1f9f8160c976)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11839340/latestlog.txt)

### Steps To Reproduce

```markdown
I started pojav,created the world and it happened,after i exited the world all the menu text still was dark,this dont happened when i first entered but only after retured to the menu.
```

### Expected Behavior

Maybe its a pojav build bug or something,i dont know but in the log say something about
[Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?Thread

### Platform

```markdown
- Device model: SM-A325M/DS
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: LOCAL-20230621
```

### Anything else?

I dont know if is related but this seems to happen in versions after 1.16.5(that uses jre 17 runtime).i dint test on 1.17 but it happned in 1.18.2,1.19.2,1.19.4.,1.20,1,20,1.

**Comment by GaucovyAero** [comment]
use the play store version
