### ISSUE TITLE
Best basic mods for forge 1.20.1

### ISSUE THREAD

**Issue by kareemnew2019** [PojavLauncherTeam/PojavLauncher#4294]
### Describe the bug

Note : this list for 1.20.1 forge newcomers to help you with mods
And not waste your time trying to solve it
First of all optifine doesn't with versions past 47.0.3 at all
Xaero's map mods doesn't work it crashes after some time
Here is the list of needed basic mods for items and performance:
1- ftb (map-ultimine)
2- journey map ( if you don't like ftb chunks )
3- rubidium
4- jei
5- mouse tweaks
WARNING MODS BELOW ARE CRASHING OR UNSTABLE AVOID THEM ANTIL THEY ARE FIXED ❤️
THIS IS ONLY FOR POJAVLAUNCHER MAYBE THE WORK IN OTHER PC LANCHERS
1- xaero's maps mod

Thanks for POJAVLAUNCHER TEAM for there amazing work
And sorry for any spelling errors .
Feel free to add any info I hope this doesn't bother the devs 👋

### The log file and images/videos

None

### Steps To Reproduce

```markdown
Try the mods
```

### Expected Behavior

It is just a list for 1.20.1 forge newcomers

### Platform

```markdown
- Device model: a52 8/128
- CPU architecture: 64×
- Android version:12 
- PojavLauncher version: lady mod is not a hack
```

**Comment by kareemnew2019** [comment]
A picture for all the mods that I have installed
![Screenshot_20230622_215211_ZArchiver](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78564582/77fc84aa-a6ac-4ecf-bd5b-36ac86fdc2de)
![Screenshot_20230622_215216_ZArchiver](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78564582/46eb3eb2-0b24-41a9-831a-c67b1b9f3ea3)

**Comment by kareemnew2019** [comment]
Tested with forge 47.0.16

**Comment by qaq1000w** [comment]
🚫1.20.1XaerosWorldMap
don't use it
不要使用它

Xaeros_Minimap
√

**Comment by kareemnew2019** [comment]
Thanks
