### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by lysander790** [PojavLauncherTeam/PojavLauncher#4295]
### Describe the bug

Hey why I cant create my account in this app I rlly want to play it I want to try and and I want to play with my friends an di want to play like java hope u will me!:(

### The log file and images/videos

Cant play peja

### Steps To Reproduce

```markdown
cant create acc
```

### Expected Behavior

It always errors

### Platform

```markdown
- Device model: Samsung
- CPU architecture: 
- Android version: Samsung A20
- PojavLauncher version: 1.19.83
```

**Comment by GaucovyAero** [comment]
buy minecraft
