### ISSUE TITLE
[BUG] The game crashes

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#4296]
### Describe the bug

During the Minecraft version loading after installation, a crash was suddenly encountered, as is possible with any version

### The log file and images/videos

Uploading SVID_20230624_011552_1.mp4…

### Steps To Reproduce

```markdown
1.Launch PojavLauncher
2.Install the high game version
3.Launch the game version
```

### Expected Behavior

I hope this loophole does not appear again in the future

### Platform

```markdown
- Device model: Huawei Enjoy 10 4/120
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: LOCAL-2023/6/20
```

**Comment by Baobuchi** [comment]
Uploading SVID_20230624_011552_1.mp4…

**Comment by GaucovyAero** [comment]
missing log file
