### ISSUE TITLE
[BUG] Some mod has problem

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#4297]
### Describe the bug

just black screen 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11857214/latestlog.txt)

### Steps To Reproduce

```markdown
start pojav
launch fabic 1.19.4 with my mods
crash happened
```

### Expected Behavior

game normaly launch and working

### Platform

```markdown
- Device model: Redmi note 10 6/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: [Currently Action || dahila_2023
```

**Comment by GaucovyAero** [comment]
remove optifabric and optifine
