### ISSUE TITLE
[BUG] Thaumcraft 4 Unnatural Hunger crashes the game

### ISSUE THREAD

**Issue by kutschkem** [PojavLauncherTeam/PojavLauncher#4298]
### Describe the bug

Giving the player Thaumcraft 4 Unnatural Hunger crashes the game, without a stack trace. The game slows down for a second or two, then crashes. This can be reproduced reliably, happens every time.
This happens regardless of whether shaders are enabled or disabled in the Thaumcraft config.

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/11860520/latest.log)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11869360/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start 1.7.10 instance with Forge and Thaumcraft 4.
2. Give yourself Unnatural hunger effect with commands.
```

### Expected Behavior

Player gets Unnatural hunger, other than that the game keeps running.

### Platform

```markdown
- Device model: Redmi Note 8 
- CPU architecture: arm
- Android version: 10
- PojavLauncher version: Play store version
```

**Comment by artdeell** [comment]
Please send latestlog.txt, not latest.log. It's in the launcher's data directory (Android/data/net.kdt.pojavlaunch/files/latestlog.txt)

**Comment by kutschkem** [comment]
@artdeell done, I attached it to the issue description.

**Comment by artdeell** [comment]
Hm, seems to be a shader issue. May look into it later.

**Comment by kutschkem** [comment]
@artdeell Were you able to reproduce the issue?

**Comment by kutschkem** [comment]
I checked Thaumcraft but am a little confused by the code. It seems like if I disable shaders they shouldn't run, but maybe that doesn't work as intended. In any case, the shader code itself is in clear text in the Thaumcraft jar, so maybe there is a way to easily just check the shader together with the renderer?

**Comment by GaucovyAero** [comment]
will keep this open for now

**Comment by kutschkem** [comment]
I tested again, here are some insights:

- The Thaumcraft config option regarding shaders does not help, same behaviour regardless of setting.

- I tried patching the shader to remove all the passes (so it's noop). That helped. So the problem is in fact the shader.

This is how it looks like (these are clear text in the Thaumcraft jar so I hope it's fine to post it):

hunger.json
```
{

    "targets": [
        "swap"
    ],
    "passes": [
        {
            "name": "color_convolve2",
            "intarget": "minecraft:main",
            "outtarget": "swap",
            "uniforms": [
                {
                    "name": "ColorScale",
                    "values": [ 1.0, 0.8, 0.8 ]
                },
				{
                    "name": "Saturation",
                    "values": [ 1.1 ]
                }
            ]
        },
        {
            "name": "blit",
            "intarget": "swap",
            "outtarget": "minecraft:main"
        }
    ]
}
```

color_convolve2.json
```
{

    "blend": {
        "func": "add",
        "srcrgb": "one",
        "dstrgb": "zero"
    },
    "vertex": "sobel",
    "fragment": "color_convolve2",
    "attributes": [ "Position" ],
    "samplers": [
        { "name": "DiffuseSampler" }
    ],
    "uniforms": [
        { "name": "ProjMat",     "type": "matrix4x4", "count": 16, "values": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },
        { "name": "OutSize",     "type": "float",     "count": 2,  "values": [ 1.0, 1.0 ] },
        { "name": "Gray",        "type": "float",     "count": 3,  "values": [ 0.3, 0.59, 0.11 ] },
        { "name": "RedMatrix",   "type": "float",     "count": 3,  "values": [ 1.0, 0.0, 0.0 ] },
        { "name": "GreenMatrix", "type": "float",     "count": 3,  "values": [ 0.0, 1.0, 0.0 ] },
        { "name": "BlueMatrix",  "type": "float",     "count": 3,  "values": [ 0.0, 0.0, 1.0 ] },
        { "name": "Offset",      "type": "float",     "count": 3,  "values": [ 0.0, 0.0, 0.0 ] },
        { "name": "ColorScale",  "type": "float",     "count": 3,  "values": [ 1.0, 1.0, 1.0 ] },
        { "name": "Saturation",  "type": "float",     "count": 1,  "values": [ 1.8 ] }
    ]
}
```

color_convolve2.fsh
```
#version 120

uniform sampler2D DiffuseSampler;

varying vec2 texCoord;
varying vec2 oneTexel;

uniform vec2 InSize;

uniform vec3 Gray = vec3(0.3, 0.59, 0.11);
uniform vec3 RedMatrix   = vec3(1.0, 0.0, 0.0);
uniform vec3 GreenMatrix = vec3(0.0, 1.0, 0.0);
uniform vec3 BlueMatrix  = vec3(0.0, 0.0, 1.0);
uniform vec3 Offset = vec3(0.0, 0.0, 0.0);
uniform vec3 ColorScale = vec3(1.0, 1.0, 1.0);
uniform float Saturation = 1.8;

void main() {
    vec4 InTexel = texture2D(DiffuseSampler, texCoord);
    
    // Color Matrix
    float RedValue = dot(InTexel.rgb, RedMatrix);
    float GreenValue = dot(InTexel.rgb, GreenMatrix);
    float BlueValue = dot(InTexel.rgb, BlueMatrix);
    vec3 OutColor = vec3(RedValue, GreenValue, BlueValue);
    
    // Offset & Scale
    OutColor = (OutColor * ColorScale) + Offset;
    
    // Saturation
    float Luma = dot(OutColor, Gray);
    vec3 Chroma = OutColor - Luma;
    OutColor = (Chroma * Saturation) + Luma;
    
    gl_FragColor = vec4(OutColor, InTexel.a);
}
```

Maybe you can spot something that is known to give the renderer trouble.

**Comment by GaucovyAero** [comment]
the default id for unnatural hunger is not 59, you would have to give me your whole modpack for me to test it

**Comment by kutschkem** [comment]
@GaucovyAero 
[ModTest.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12343855/ModTest.zip)
Here a minimal modpack with Thaumcraft and NEI (to dump potion ids). In this, unnatural hunger is potion id 34.

Thaumcraft assigns them automatically, so dumping is the only way to figure the ids out when mods change. If you use the attached one it should still be 34.

**Comment by GaucovyAero** [comment]
it works just fine for me, can you try the latest github actions version of pojav?

![Screenshot_20230815-143531_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/20929967-2b4f-4ff5-bae4-d9cb881f03b8)

**Comment by kutschkem** [comment]
@GaucovyAero Still breaks for me with dahlia-20230815-919a6a4-v3_openjdk, but with more information in the log:

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12347040/latestlog.txt)

**Comment by kutschkem** [comment]
#4049 seems to be a duplicate of this issue but doesn't contain much more info

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | dahlia - 20230815 - v3_openjdk |
| Minecraft version | 1.7.10-forge10.13.4.1614-1.7.10 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by GaucovyAero** [comment]
```
[19:57:24] [Client thread/WARN]: Error encountered when linking program containing VS sobel and FS color_convolve2. Log output:
[19:57:24] [Client thread/WARN]: L0001 Shader languages do not match.
```
i guess well wait for the devs to answer, but heres what it says

**Comment by GaucovyAero** [comment]
he said this should be fixed on the github actions builds, try them i guess

**Comment by kutschkem** [comment]
@GaucovyAero That last one was a github actions build from today, v3_openjdk branch. Which branch should I use if not that one?

**Comment by GaucovyAero** [comment]
> @GaucovyAero That last one was a github actions build from today, v3_openjdk branch. Which branch should I use if not that one?

hmm no idea then

**Comment by Mathias-Boulay** [comment]
Thank you for the accurate report and follow ups on it. Hopefully we resolve this in the future with an update of the rendering system. In the meantime, if your device is powerful enough, you can probably try the virgl renderer, although I don't think it likes 1.7.10 too much.

**Comment by GaucovyAero** [comment]
you can also wait for an update of the zink renderer (that makes your adreno 610 work with it), exports opengl 4.6, which means shaders are also possible

**Comment by kutschkem** [comment]
One more thing, I noticed the same behavior with the "Deadly gaze" potion effect. ID 36 in the test modpack. And this one is simply desaturating using the "color convolve" shader that [Minecraft ships with](https://minecraft.fandom.com/de/wiki/Shader).

Also, especially for people finding this issue who have the same problem: a first workaround that doesn't involve disabling warp effects completely. This simple resource pack disables the two offending shaders:

[pojavlauncher-4298-wa1.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12363093/pojavlauncher-4298-wa1.zip)

**Comment by GaucovyAero** [comment]
does this completely fix it for you?

**Comment by kutschkem** [comment]
@GaucovyAero it's a workaround, I wouldn't close the issue. If that was the question. It fixes it in the sense that there are no more crashes. At the cost of not having those shaders.

**Comment by GaucovyAero** [comment]
alr

**Comment by kutschkem** [comment]
A fix for me would be either:

- renderer supports whatever is the problem here
or
- resource packs that adapts the shader scripts to work with the renderer, replicating the original functionality

The second one can't be too hard but I have zero experience with opengl shader scripts, so I opted for the simple workaround first. Also, since you couldn't replicate the issue, I still don't know if there is some hardware dependent factor. I just want to believe there isn't.

**Comment by Mathias-Boulay** [comment]
Well, it is not uncommon for certain devices to not support some OGL extensions

**Comment by GaucovyAero** [comment]
for example for the create mod to work on gl4es, you need an adreno gpu, because it requires the GL_OES_framebuffer_object extension

**Comment by GaucovyAero** [comment]
zink will be added in the soon upcoming play store update (opengl 4.6 over vulkan), and a gl4es update will come later on

**Comment by kutschkem** [comment]
@GaucovyAero With edelweiss-20230928-9484d0c-v3_openjdk, this is still broken for Holy GL4ES renderer. Zinc simply crashes on startup for me.
