### ISSUE TITLE
Please send me a link of pojav launcher which will work on my android

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#430]
Redmi 8a dual
2 gb ram

**Comment by khanhduytran0** [comment]
Launcher builds are compatible with any devices running Android 5+.

**Comment by ghost** [comment]
I know but the best one plis
😁😁😁😁😁😁😁😁😁😁

**Comment by artdeell** [comment]
latest is always the best

вс, 29 нояб. 2020 г., 16:30 ChargedHat42838 <notifications@github.com>:

**Comment by ghost** [comment]
Thanks but I can't launch 1.10 and above on v3
It always says - game exited with code 0.
Even if I installed lwjgl3 bridge
