### ISSUE TITLE
Crashing when opening or creating a world

### ISSUE THREAD

**Issue by gabriel-fondato** [PojavLauncherTeam/PojavLauncher#4301]
### Describe the bug

There is no error code no crash report just the logs
 the app just closes. And i have some mods installed

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/11900847/latest.log)

### Steps To Reproduce

```markdown
Idk, use the same mods as mine i guess
```

### Expected Behavior

It should open the world

### Platform

```markdown
- Device model: Sansung galaxy A30s
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version:
```

### Anything else?

I think it have something to do with the narrator library

**Comment by ghost** [comment]
PojavLauncher is incompatible with Advanced Energistics 2.
