### ISSUE TITLE
[F-Req] <Short description>一个关于内存分配的建议

### ISSUE THREAD

**Issue by lava191810** [PojavLauncherTeam/PojavLauncher#4302]
### Is this request related to a bug?

能否将存储空间的一部分作为虚拟内存与物理内存一起给minecraft使用
或加入一个内存位置的选项用于选择使用存储空间作为内存使用或使用物理内存作为内存使用

**Comment by T-CATHOME** [comment]
按理来说，你应该用英文来反映，官方好像是不会处理其他语言的反馈

**Comment by lava191810** [comment]
好的

在 2023-06-30 15:10:41，T_Cat_White ***@***.***> 写道：


按理来说，你应该用英文来反映，官方好像是不会处理其他语言的反馈
