### ISSUE TITLE
[BUG] <render error>

### ISSUE THREAD

**Issue by Inverted-Fin** [PojavLauncherTeam/PojavLauncher#4303]
### Describe the bug

![Screenshot_2023-06-29-20-08-18-35_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/134783108/5ff20ae4-da31-48a3-a8f2-11fc8489980d)

render error,surface is black

### The log file and images/videos

no flie

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.choose renderer is gl4es
3.enter server-world
4.surface render as black
```

### Expected Behavior

improve render error

### Platform

```markdown
- Device model: oppo K10
- CPU model:Dimensity 8000-max
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: dahlia-20230627-e32a526-feat/lwjgl-3.3.1 (9939193)
```

**Comment by ghost** [comment]
Do you still get the same results when picking a different renderer?

**Comment by Inverted-Fin** [comment]
> 

Don' t know,I only choose gl4es this renderer,and return back to zink version

**Comment by ghost** [comment]
Try a different renderer.

**Comment by GaucovyAero** [comment]
use the play store version
