### ISSUE TITLE
Pojavlauncher crashes when loading textures from a server

### ISSUE THREAD

**Issue by ShippoteChan** [PojavLauncherTeam/PojavLauncher#4304]
### Describe the bug

Currently I work with a server with the Oraxen plugin, it is necessary to show the texture pack that the server has
When starting the game, everything is fine, I can enter local worlds, enter servers without mandatory resource packs and so on. However, when entering a server with resource packages, it simply closes

The problem has already been seen on various devices that I have, as well as users who want to test my server, unfortunately they can't even access the login as it closes before.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11912107/latestlog.txt)

### Steps To Reproduce

```markdown
1. Home Pojavlauncher
2. I select my preferred version
3. The game loads to the main screen 
4. I select the server to play
5. It loads the server but when it gets to load the resource pack it simply forces the closing
```

### Expected Behavior

I expected the game to load normally, I also tried having the textures Locally and the same thing happens

### Platform

```markdown
- Device model: LG V40 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Lastest Release || PlayStore
```

### Anything else?

I read inside the Lastest Log file something about the overlay crash, nothing to say.

**Comment by ShippoteChan** [comment]
https://youtu.be/i_ebgCuXnv0

Here's a video, I couldn't attach it directly 

The server to carry out the tests in case you need it.

195.201.246.233:25644

**Comment by SahiliBro** [comment]
Yeh same thing happens to me when i tried to load mccisland texturepack

**Comment by GaucovyAero** [comment]
it crashes, because gl4es fails to convert the shaders, the latest play store version has improved conversion support, check if it works now
