### ISSUE TITLE
[F-Req] is physics mod supported for pojavlauncher now?

### ISSUE THREAD

**Issue by Forever2397** [PojavLauncherTeam/PojavLauncher#4305]
### Describe the request.

Like the problem I'm having when I run minecraft with the physics mod logout it says something like this: java.lang.ExceptionInInitializer: null
I already know this problem because physx jni is not yet supported for android but i hope it will be complied thanks

**Comment by kaicryptx** [comment]
@Forever2397 Watch trankhanduy tutorial in yt

**Comment by Forever2397** [comment]
i know that but it's an old version, because the current physics mod uses a different engine so i hope that physx jni is compiled for android

**Comment by GaucovyAero** [comment]
no physx for now
