### ISSUE TITLE
Joining a random server

### ISSUE THREAD

**Issue by Vindex6785** [PojavLauncherTeam/PojavLauncher#4306]
### Describe the bug

I jest trying to join a popular server

### The log file and images/videos

![Screenshot_20230630-144300](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136948642/f558fd18-b72d-4687-b8e0-ce3319b8bc19)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Enters multiplayer
3. Adds a server or direct join
4. Joins the server
5. Says to me to restart the launcher/game
```

### Expected Behavior

I expect to normally join the server

### Platform

```markdown
- Device model: RMX3511
- CPU architecture: octa core
- Android version: 11
- PojavLauncher version: new version
(Im to lazy to put it)
```

### Anything else?

Nothing else

**Comment by selut06** [comment]
do u have Minecraft licence?

**Comment by ghost** [comment]
Make sure you have an account with Minecraft: Java Edition bought on it.

**Comment by Bel69420** [comment]
> ### Describe the bug
> I jest trying to join a popular server
> 
> ### The log file and images/videos
> ![Screenshot_20230630-144300](https://user-images.githubusercontent.com/136948642/250015254-f558fd18-b72d-4687-b8e0-ce3319b8bc19.png)
> 
> ### Steps To Reproduce
> ```
> 1. Start pojavlauncher
> 2. Enters multiplayer
> 3. Adds a server or direct join
> 4. Joins the server
> 5. Says to me to restart the launcher/game
> ```
> 
> ### Expected Behavior
> I expect to normally join the server
> 
> ### Platform
> ```
> - Device model: RMX3511
> - CPU architecture: octa core
> - Android version: 11
> - PojavLauncher version: new version
> (Im to lazy to put it)
> ```
> 
> ### Anything else?
> Nothing else

Can you give me the ip of that server? I want to check if that server work for me.

**Comment by Vindex6785** [comment]
> play.bendersmc.co there

**Comment by progameir2309** [comment]
Do you have a local account or minecraft account? Local is not for bendersmc

**Comment by Vindex6785** [comment]
> Do you have a local account or minecraft account? Local is not for bendersmc

I do not understand i jest remembered that i use my Minecraft username

**Comment by ghost** [comment]
no no no, you need to add an account, then sign in with your Microsoft account that you purchased Minecraft: Java Edition on.

**Comment by progameir2309** [comment]
> no no no, you need to add an account, then sign in with your Microsoft account that you purchased Minecraft: Java Edition on.

Yeah I Did It With Microsoft/Java Account

**Comment by ghost** [comment]
try connecting again. does it still show the same error?

**Comment by GaucovyAero** [comment]
buy minecraft
