### ISSUE TITLE
About Install JAR

### ISSUE THREAD

**Issue by ManyullynSword** [PojavLauncherTeam/PojavLauncher#4307]
### Is this request related to a bug?

No.

### Describe the request.

I really like the install JAR feature of PojavLauncher. But I found a better Minecraft Java Edition Launcher for Android, and I can't bear to lose this feature. Because I found that it can even run other files, even some small games. Therefore, I hope you can package the installation JAR feature into a JVM suitable for Android. I'm not demanding, but I really want a JVM like this.

**Comment by artdeell** [comment]
Nah, we won't, because we want you to use Pojav.
 But if you want to run games on the JAR installer, there are some forks of Pojav that do that, like [2009Scape-mobile](https://github.com/2009scape/2009Scape-mobile)

**Comment by ManyullynSword** [comment]
How to use 2009Scape-mobile to install other JAR?
