### ISSUE TITLE
[BUG] gl4es renderer with rlcraft

### ISSUE THREAD

**Issue by williamodavis** [PojavLauncherTeam/PojavLauncher#4309]
### Describe the bug

When loading Rlcraft with gl4es, most blocks do not render correctly, and only load one or two of the sides of the block. Virglrenderer loads everything properly, but is super laggy. Forge and optifine do not cause any issues, as I tested them separately. Turning on fast render from optifine fixes the block rendering, but messes with some other graphics in rlcraft, like water. 

### The log file and images/videos

![Screenshot_20230630_083158_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/98902842/2d7afeeb-1f59-4f98-af73-6a8977272223)
![Screenshot_20230630_083146_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/98902842/6cde6e40-8ad7-4197-952e-cec397f55930)

### Steps To Reproduce

```markdown
1. Install RLCraft manually
2. Launch
3. Enter world
```

### Expected Behavior

I expect for everything to render properly.

### Platform

```markdown
- Device model: S23+
- CPU architecture: ARM v9
- Android version: 13
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
press f11
