### ISSUE TITLE
Crash when installing forge fabric to automatically close the logging interface

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#431]
Crash when installing forge fabric to automatically close the logging interface

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by T-CATHOME** [comment]
@khanhduytran0 
Detected Fabric Installer!
Launching JVM
Info: Java arguments: [-Dcacio.managed.screensize=2261x1080, -jar, /storage/emulated/0/7733/fabric-installer.jar, client, -dir, ., -mcversion, 1.14.4]
--------- beginning of main
S/LaunchJVM( 8688): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  ( 8688): " unused DT entry: 
S/jrelog  ( 8688): DT_RPATH
S/jrelog  ( 8688):  (type 
S/jrelog  ( 8688): 0xf
S/jrelog  ( 8688):  arg 
S/jrelog  ( 8688): 0x450
S/jrelog  ( 8688): ) (ignoring)
S/jrelog  ( 8688): 
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  ( 8688): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 8688): 0x81
S/jrelog  ( 8688):  (ignoring unsupported flags)
S/jrelog  ( 8688): 
S/LaunchJVM( 8688): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  ( 8688): " unused DT entry: 
S/jrelog  ( 8688): DT_RPATH
S/jrelog  ( 8688):  (type 
S/jrelog  ( 8688): 0xf
S/jrelog  ( 8688):  arg 
S/jrelog  ( 8688): 0x33c0
S/jrelog  ( 8688): ) (ignoring)
S/jrelog  ( 8688): 
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  ( 8688): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 8688): 0x81
S/jrelog  ( 8688):  (ignoring unsupported flags)
S/jrelog  ( 8688): 
S/LaunchJVM( 8688): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  ( 8688): " unused DT entry: 
S/jrelog  ( 8688): DT_RPATH
S/jrelog  ( 8688):  (type 
S/jrelog  ( 8688): 0xf
S/jrelog  ( 8688):  arg 
S/jrelog  ( 8688): 0x13b8
S/jrelog  ( 8688): ) (ignoring)
S/jrelog  ( 8688): 
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  ( 8688): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 8688): 0x81
S/jrelog  ( 8688):  (ignoring unsupported flags)
S/jrelog  ( 8688): 
S/LaunchJVM( 8688): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  ( 8688): " unused DT entry: 
S/jrelog  ( 8688): DT_RPATH
S/jrelog  ( 8688):  (type 
S/jrelog  ( 8688): 0xf
S/jrelog  ( 8688):  arg 
S/jrelog  ( 8688): 0x2196
S/jrelog  ( 8688): ) (ignoring)
S/jrelog  ( 8688): 
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  ( 8688): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 8688): 0x81
S/jrelog  ( 8688):  (ignoring unsupported flags)
S/jrelog  ( 8688): 
S/LaunchJVM( 8688): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  ( 8688): " unused DT entry: 
S/jrelog  ( 8688): DT_RPATH
S/jrelog  ( 8688):  (type 
S/jrelog  ( 8688): 0xf
S/jrelog  ( 8688):  arg 
S/jrelog  ( 8688): 0x6a46
S/jrelog  ( 8688): ) (ignoring)
S/jrelog  ( 8688): 
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  ( 8688): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 8688): 0x81
S/jrelog  ( 8688):  (ignoring unsupported flags)
S/jrelog  ( 8688): 
S/LaunchJVM( 8688): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  ( 8688): " unused DT entry: 
S/jrelog  ( 8688): DT_RPATH
S/jrelog  ( 8688):  (type 
S/jrelog  ( 8688): 0xf
S/jrelog  ( 8688):  arg 
S/jrelog  ( 8688): 0x4d9
S/jrelog  ( 8688): ) (ignoring)
S/jrelog  ( 8688): 
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  ( 8688): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 8688): 0x81
S/jrelog  ( 8688):  (ignoring unsupported flags)
S/jrelog  ( 8688): 
S/LaunchJVM( 8688): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
S/LaunchJVM( 8688): dlopen /data/app/net.kdt.pojavlaunch-v_voTRRlTEAtroBdvf9m8w==/lib/arm64/libopenal.so success
S/LaunchJVM( 8688): dlopen /data/app/net.kdt.pojavlaunch-v_voTRRlTEAtroBdvf9m8w==/lib/arm64/libgl04es.so success
S/LaunchJVM( 8688): Done processing args
S/LaunchJVM( 8688): Found JLI lib
S/LaunchJVM( 8688): Calling JLI_Launch
S/jrelog  ( 8688): OpenJDK 64-Bit Server VM warning: 
S/jrelog  ( 8688): No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
S/jrelog  ( 8688): 
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  ( 8688): " unused DT entry: 
S/jrelog  ( 8688): DT_RPATH
S/jrelog  ( 8688):  (type 
S/jrelog  ( 8688): 0xf
S/jrelog  ( 8688):  arg 
S/jrelog  ( 8688): 0x8ff
S/jrelog  ( 8688): ) (ignoring)
S/jrelog  ( 8688): 
S/jrelog  ( 8688): WARNING: linker: 
S/jrelog  ( 8688): Warning: "
S/jrelog  ( 8688): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  ( 8688): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 8688): 0x81 (ignoring unsupported flags)
S/jrelog  ( 8688): Loading Fabric Installer: 0.6.1.51
S/jrelog  ( 8688): 
S/jrelog  ( 8688): Using latest loader version
S/jrelog  ( 8688): 
S/jrelog  ( 8688): Installing 1.14.4 with fabric 0.10.8
S/jrelog  ( 8688): 
S/jrelog  ( 8688): Done
S/jrelog  ( 8688): 
S/jrelog  ( 8688): Creating profile
S/jrelog  ( 8688): 
Java Exit code: 0
S/LaunchJVM( 8688): Going to free args
安装成功
S/LaunchJVM( 8688): Free done
--------- beginning of system
--------- beginning of crash

**Comment by khanhduytran0** [comment]
Duplicate #425
