### ISSUE TITLE
[F-Req] Modpack support

### ISSUE THREAD

**Issue by SniverDaBest** [PojavLauncherTeam/PojavLauncher#4311]
### Describe the request.

This launcher is close to being complete for me. But I feel like it needs support for built-in modpack installing. Something like just clicking the modpacks tab and being able to get modpacks from Modrinth, CurseForge, and FTB. Maybe even have a tab where you create your own modpacks so you don't have to put mods in the mods folder all the time. It would also give it more personality by doing this.

**Comment by hiimabignoobwihenolive** [comment]
theres already a way to do that you just need to use curseforge gui and enter the modpack id

**Comment by GaucovyAero** [comment]
there is already work being done on it

**Comment by GaucovyAero** [comment]
closing, as this is a duplicate
