### ISSUE TITLE
[F-Req] Themes

### ISSUE THREAD

**Issue by SniverDaBest** [PojavLauncherTeam/PojavLauncher#4312]
### Is this request related to a bug?

Nope.

### Describe the request.

Pojav is a little bland. So I think you should add themes to make it look a lot better! It doesn't have to be much, but it would make the launcher a little nicer. The little things count!

### Anything else?

Nope.

**Comment by GaucovyAero** [comment]
not yet, its really far away if its ever going to be implemented
