### ISSUE TITLE
[BUG] <The game does not have any sound>

### ISSUE THREAD

**Issue by Ink305Mua** [PojavLauncherTeam/PojavLauncher#4313]
### Describe the bug

The game does not have any sound, my game has been downloaded completely, but there is no sound, other launchers have sound, I do not know why, I enabled the version isolation

### The log file and images/videos

None

### Steps To Reproduce

```markdown
None
```

### Expected Behavior

None

### Platform

```markdown
- Device model: HONOR 20 PRO/256G
- CPU architecture: aarch64
- HarmonyOS version: 3.0.0
- PojavLauncher version: dahlia-20230630-6b0ec1f-feat/automatic_modloader_install
```

**Comment by lava191810** [comment]
Enable "Check libraries after downloading" in your Settings and check your network connection. Because some of Minecraft's resource files (including audio and language files) are not included in the core.jar file, the PojavLauncher launches directly after the.jar download, leaving the game without sound and multilingual support.

**Comment by aaaapai** [comment]
> Enable "Check libraries after downloading" in your Settings and check your network connection. Because some of Minecraft's resource files (including audio and language files) are not included in the core.jar file, the PojavLauncher launches directly after the.jar download, leaving the game without sound and multilingual support.

1.6.4 Is there no solution? I want to move files from the computer to the phone, right?

**Comment by Ink305Mua** [comment]
> 在“设置”中启用“下载后检查库”并检查网络连接。由于Minecraft的一些资源文件（包括音频和语言文件）不包含在core.jar文件中， PojavLauncher在.jar下载后直接启动，使得游戏没有声音和多语言支持。

It doesn't work, there is still no sound, also, when the version file name is Chinese, the game will not start, there is no log output, I hope you can support Chinese folder name
I replayed the game proper and found that the vanilla version had sound, but the Forge version did not

**Comment by caiji233r** [comment]
> 

I replayed the game proper and found that the vanilla version had sound, but the Forge version did not

**Comment by caiji233r** [comment]
>@lava191810 我重新播放了游戏，发现香草版有声音，但Forge版没有

**Comment by caiji233r** [comment]
> 

I replayed the game proper and found that the vanilla version had sound, but the Forge version did not

**Comment by Ink305Mua** [comment]
> 在“设置”中启用“下载后检查库”并检查网络连接。由于Minecraft的一些资源文件（包括音频和语言文件）不包含在core.jar文件中， PojavLauncher在.jar下载后直接启动，使得游戏没有声音和多语言支持。

才发现你不是官方（）

**Comment by GaucovyAero** [comment]
use the play store version for now
