### ISSUE TITLE
[F-Req] A suggestion about virtual memory versus physical memory

### ISSUE THREAD

**Issue by lava191810** [PojavLauncherTeam/PojavLauncher#4314]
### Is this request related to a bug?

This request isn't related to bug.

### Describe the request.

An optional option to use storage as memory.

### Anything else?

Can you use a portion of your storage space as virtual memory along with physical memory for minecraft
Or add the option of a memory location to choose between using storage space as memory use or using physical memory as memory use.

**Comment by artdeell** [comment]
You can't

Well, technically, you can, but that will need root and will be pretty useless anyway, since "virtual memory" on storage will be very, very slow. Thats why a lot of people recomend to not turn on RAM Plus or some other virtual memory setting on your device

**Comment by khanhduytran0** [comment]
You can within Java 11+ without root. Same warned as above. Add `-XX:AllocateHeapAt=.` into jvm arguments.

**Comment by artdeell** [comment]
> You can within Java 11+ without root. Same warned as above. Add `-XX:AllocateHeapAt=.` into jvm arguments.
I think its a bad idea to recommend this because flash wear will be very high with it

**Comment by lava191810** [comment]
How do I install jdk11+ for my PojavLauncher? I don't have another jdk available for PojavLauncher, and according to the authors, jdk distributions on the Web don't work with PojavLauncher. @artdeell

**Comment by GaucovyAero** [comment]
> How do I install jdk11+ for my PojavLauncher? I don't have another jdk available for PojavLauncher, and according to the authors, jdk distributions on the Web don't work with PojavLauncher. @artdeell

java 11+ only means java 17 and java 21 JREs on pojav
