### ISSUE TITLE
[BUG]  <Buildcraft mod 1.12.2 Error Fix Pls>

### ISSUE THREAD

**Issue by whisky1960** [PojavLauncherTeam/PojavLauncher#4316]
### Describe the bug

Buildcraft mode is broken for some reason, I tried everything but it didn't work 

### The log file and images/videos

![Screenshot_2023-07-01-17-34-45-28_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136997687/9a38276e-4117-4559-b394-136f65f733eb)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Oneplus 9
- CPU architecture:Adreno
- Android version: 12
- PojavLauncher version: last gp
```

### Anything else?

Pls help me

**Comment by NoWeRand** [comment]
this can be fixed by switching to another visualizer, but it is extremely slow

**Comment by GaucovyAero** [comment]
press f11
