### ISSUE TITLE
[BUG] <virglrenderer It does not work>

### ISSUE THREAD

**Issue by elbrayan817** [PojavLauncherTeam/PojavLauncher#4318]
### Describe the bug

I select virglrenderer to use shaders, but I only get a red screen and it doesn't start the game, this is in version 1.20

### The log file and images/videos

![Screenshot_20230701-162649](https://github.com/PojavLauncherTeam/PojavLauncher/assets/66798452/0f4fb326-2d21-4896-84b8-20135b24274c)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Start Minecraft 1.20 with OptiFine and virglrenderer
```

### Expected Behavior

Wait until the screen turns red, like the Minecraft logo, only it doesn't appear

### Platform

```markdown
- Device model: Moto G71 6/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Last version
```

**Comment by GaucovyAero** [comment]
virgl generally doesnt work well
