### ISSUE TITLE
[BUG] Pojav had problems installing the fabric

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#4319]
### Describe the bug

Such an error does not know where it came from

### The log file and images/videos

...

### Steps To Reproduce

```markdown
1.Open pojavlauncher
2.Install Fabric
```

### Expected Behavior

I hope the bug is fixed

### Platform

```markdown
- Device model: Huawei enjoy 10 4/128
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: 
dahlia-20230701-4aec0d5-feat/automatic_modloader_install
```

### Anything else?

no

**Comment by Baobuchi** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/100058929/43443bbb-655e-4620-9cf5-9aa480191bbf

**Comment by artdeell** [comment]
Press "Show more" and show the full stack trace
