### ISSUE TITLE
[BUG] memory allocation

### ISSUE THREAD

**Issue by U374** [PojavLauncherTeam/PojavLauncher#4320]
### Describe the bug

Hi pojav team,
I have noticed a bug in the pojav launcher that is I can't select memory more than 1000mb even I have 4gb+1gb memory extension but still I can't give more memory to my game.
Plz solve this bug,
Thankyou,
-Indian gamerz

### The log file and images/videos

![Screenshot_2023-07-02-07-37-55-977_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/83197237/27c362c6-60cc-4a30-b045-4f7c15548cf3)

### Steps To Reproduce

```markdown
1. Start the Pojav launcher 
2. Click on Settings
3. Click on Java tweaks 
4. At the memory allocation setting
```

### Expected Behavior

I expect that I will select 1500mb of ram and start the game but I can't increase ram more than 1000mb

### Platform

```markdown
- Device model: redmi 10a
- CPU architecture: 8x ARM Cortex-A53
- Android version: 11
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by ItsManasxD** [comment]
Yeah My Phone Also Have 
4GB RAM +1GB Virtual RAM

Device -- 
XIAOMI REDMI 10 [Indian Version] 
CPU - Qualcomm Snapdragon 680
GPU - Adreno 610
CPU Type- 64 bit

I also want to use Physics Memory+ Virtual memory for Pojav to make Game More Smoother

**Comment by dachisao** [comment]
Your device seems to be 32bit. Read
https://pojavlauncherteam.github.io/32BIT.html for more info.

Check your SOC if it's 32bit or not by using DevCheck or AIDA64.

**Comment by ItsManasxD** [comment]
> Your device seems to be 32bit. Read https://pojavlauncherteam.github.io/32BIT.html for more info. Check your SOC if it's 32bit or not by using DevCheck or AIDA64.

What about me xD

Actually I can allocate more but i don't have enough so I want to use virtual ram with Physical one

**Comment by GaucovyAero** [comment]
miui probably takes up 3GB by default, you cannot do anything about that
