### ISSUE TITLE
[BUG] <Forge 1.7.10 OpenGL error>

### ISSUE THREAD

**Issue by rpu5** [PojavLauncherTeam/PojavLauncher#4323]
### Describe the bug

When I play modpack GregTech New Horizons the error OpenGL 1280 spam in the chat window when I open the inventory or pause the game. 
The error also enlarges the log file. After 1 hour of gaming the latest.log was ~ 6 GB.

The problem appeared after the April's releases in GitHub. Play market's version and PojavLauncher (dahlia-297-017e8c175-) works fine.

### The log file and images/videos

/
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/11929806/latest.log)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11929807/latestlog.txt)
![Screenshot_2023-07-02-17-42-15-828](https://github.com/PojavLauncherTeam/PojavLauncher/assets/84013912/aeec6871-fa34-48a3-a533-3e0f742905f8)

### Steps To Reproduce

```markdown
1. Run GT NH modpack without better loading screens mod on Holy OpenGL render;
2. Enter in a world;
3. Pause the game or open inventory.
```

### Expected Behavior

No spam OpenGL error in the chat window and in the logs as in the older versions of PojavLauncher.

### Platform

```markdown
- Device model: Red Magic 8 Pro
- CPU architecture: Snapdragon 8Gen2
- Android version: 13
- PojavLauncher version: latest GitHub version and earlier (from April's versions)
```

### Anything else?

It seems that something is broken in the render in new releases

**Comment by GaucovyAero** [comment]
but the log is not really big because of the gl errors, mostly because of some "blockstexture not loaded" thing
probably just use an older pojav version if it works better for you

**Comment by rpu5** [comment]
It is not really big for now because I'll not download the log with the 681 mb of OpenGL error.

With the newest update the OpenGL error 1280 chained and it also has OpenGL error 1282.
![Screenshot_2023-08-15-20-59-15-099](https://github.com/PojavLauncherTeam/PojavLauncher/assets/84013912/3e22aebc-c61d-476f-b8df-9128eac7a7cc)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12347047/latest.log)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12347048/latestlog.txt)

Also for now I use old version but over time an update will be released in GP that breaks the game

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | dahlia - 20230815 - v3_openjdk |
| Minecraft version | 1.7.10-forge10.13.4.1614-1.7.10 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| load.shader.fail |
| opengl.generic.error |

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | dahlia - 20230815 - v3_openjdk |
| Minecraft version | 1.7.10-forge10.13.4.1614-1.7.10 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| load.shader.fail |
| opengl.generic.error |

**Comment by GaucovyAero** [comment]
cant really do much about this, gl4es only supports opengl 2.1, but in the next play store update, there should be the zink renderer, which supports opengl 4.6 over vulkan and therefore should work fine with your mods (with about 50-75%) performance compared to gl4es

**Comment by Mathias-Boulay** [comment]
oh yeah, we report errors now. We didn't in the past

**Comment by rpu5** [comment]
> cant really do much about this, gl4es only supports opengl 2.1, but in the next play store update, there should be the zink renderer, which supports opengl 4.6 over vulkan and therefore should work fine with your mods (with about 50-75%) performance compared to gl4es

Zink builds don't work for me, they crash the game at the beginning. This can be caused because of old Zink driver in the launcher that does not support a7xx

**Comment by GaucovyAero** [comment]
> Zink builds don't work for me, they crash the game at the beginning. This can be caused because of old Zink driver in the launcher that does not support a7xx

yeah, it will get updated eventually
