### ISSUE TITLE
Add New Renderer

### ISSUE THREAD

**Issue by McTutorialID23** [PojavLauncherTeam/PojavLauncher#4324]
### Is this request related to a bug?

ID :
Saya Berharap renderer VGpu dan VirGL ditambahkan lagi, soalnya saya kangen sama kedua renderer. Jadi biar renderernya ada 5 (Holy gl4es, VirGl, Angle, Vgpu , dan Zink)
Dan juga agar kita bisa bebas memilih renderer yang diinginkan 
 
Holy & VGpu : untuk meningkatkan performa/fps
VirGL & Zink : untuk menjalankan shader Pojavlauncher
Angle: untuk menjalankan shader Java

EN :
I hope the VGpu and VirGL renderers will be added again, because I miss both renderers. So let there be 5 renderers (Holy gl4es, VirGl, Angle, Vgpu , dan Zink)
And also so that we can freely choose the desired renderer 

Holy & VGpu : to improve performance/fps
VirGL & Zink : to run Pojavlauncher shaders
Angle: to run the Java shaders

### Describe the request.

Please restore the VGpu and VirGL renderers, so that there are 5 renderer options 🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by Bel69420** [comment]
Angle tidak bisa mejalankan shader karena semua shader tidak dapat mengenali extension opengl daripada Angle.

**Comment by Bel69420** [comment]
tidak mungkin Angle bisa mejalankan shader (kecuali ada orang yang bikin shader untuk Angle renderer)

**Comment by Bel69420** [comment]
Angle can be use for : fix mod from crash (unsupported device) and fix resources pack looping screen (unsupported renderer "gl4es")

**Comment by Ink305Mua** [comment]
I agree, because I also miss the vgpu renderer
