### ISSUE TITLE
[BUG] Why is this BUG still not fixed

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#4328]
### Describe the bug

I've been reporting this BUG for a long time, but it still hasn't been fixed
#4237

### The log file and images/videos

![Screenshot_2023-07-03-17-39-59-84_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/123115192/5deae283-3160-412f-9747-b1e072a55e57)

### Steps To Reproduce

```markdown
1.Open menu
```

### Expected Behavior

Please repair as soon as possible

### Platform

```markdown
- Device model: OPPO A9/128G
- CPU architecture:aarch64 
- Android version: 11
- PojavLauncher version: dahlia-20230702-a7444aa-v3_openjdk
```

### Anything else?

no

**Comment by hiimabignoobwihenolive** [comment]
the game is COMPLETELY UNPLAYABLE I WILL SUE THE SHIT OUT OF POJAVLAUNCHER TEAN IF NOT FIXED THIS IS NOT ACCEPTABLE 
![a19190a7dfcd00d59d65af8172386722f2e9ddc1](https://github.com/PojavLauncherTeam/PojavLauncher/assets/101394924/09bcb53a-ac5f-4491-9378-f06de7be4be4)
