### ISSUE TITLE
[BUG] Wrong way to open Fabric installation

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#4329]
### Describe the bug

When you press and hold the WIKI option, the Fabric installation screen opens directly

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/123115192/914a6816-9190-472f-ac43-a3fcb706b71f

### Steps To Reproduce

```markdown
1.Long press the WIKI option
```

### Expected Behavior

Fix it.

### Platform

```markdown
- Device model: OPPO A9/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: dahlia-20230702-a7444aa-v3_openjdk
```

### Anything else?

no

**Comment by VenomousSteam81** [comment]
But it is another way, so if I was a dev, I would leave it lmao
