### ISSUE TITLE
[BUG] Vanilla minecraft crashes with code 1 on start

### ISSUE THREAD

**Issue by DonnerTechQ2** [PojavLauncherTeam/PojavLauncher#4333]
### Describe the bug

Minecraft does not start, it immediately crashes with code 1. I think the problem in "dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found". I also tried to download java manually,  but it output the same error.

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-20230702-a7444aa-v3_openjdk
Info: Architecture: arm
Info: Device model: NVIDIA SHIELD Tablet
Info: API version: 27
Info: Selected Minecraft version: 1.12.2
Info: Custom Java arguments: ""
--------- beginning of crash

--------- beginning of main
I/jrelog  (29107): dlopen libxhook.so success

Added custom env: TMPDIR=/data/user/10/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=1920
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch.debug-82N8AZ4zX5fftz5rw_MJBQ==/lib/arm
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/10/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/10/games/PojavLauncher
Added custom env: PATH=/data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/jli:/data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/net.kdt.pojavlaunch.debug-82N8AZ4zX5fftz5rw_MJBQ==/lib/arm
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/10/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1200
Initialising gl4es
v1.1.5 built on Apr 10 2023 22:24:04
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Extension GL_EXT_shader_texture_lod detected and used
Extension GL_EXT_frag_depth  detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is NVIDIA Corporation
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
I/jrelog  (29107): dlopen libgl4es_114.so success

Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/jli/libjli.so success

I/jrelog  (29107): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/client/libjvm.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libverify.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjava.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libnet.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libnio.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libawt.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libawt_headless.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libmanagement.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libj2pcsc.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjawt.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libsctp.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libnet.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libtinyiconv.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libverify.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/liblcms.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjdwp.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjaas_unix.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libmlib_image.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjsig.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/jli/libjli.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libhprof.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libj2gss.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libawt_headless.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjsdt.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libinstrument.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libdt_socket.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libawt_xawt.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjsound.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/client/libjvm.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libjpeg.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libnpt.so success
I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libunpack.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libzip.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libj2pkcs11.so success

I/jrelog  (29107): dlopen /data/user/10/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/aarch32/libsunec.so success

I/jrelog  (29107): dlopen /data/app/net.kdt.pojavlaunch.debug-82N8AZ4zX5fftz5rw_MJBQ==/lib/arm/libopenal.so success

I/jrelog  (29107): Done processing args

I/jrelog  (29107): Found JLI lib
I/jrelog  (29107): Calling JLI_Launch

OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Error occurred during initialization of VM
Could not reserve enough space for 552960KB object heap
NvEglHandle: Unfreed handle upon egl deinit: type=1 refcnt=1
NvEglHandle: Unfreed handle upon egl deinit: type=2 refcnt=2
pure virtual method called
terminate called without an active exception

### Steps To Reproduce

```markdown
1. Just run vanilla or forge minecraft
```

### Expected Behavior

I expect the game to launch

### Platform

```markdown
- Device model: Nvidia Shield Tablet
- CPU architecture: arm32
- Android version: 8.1 oreo
- PojavLauncher version: dahlia-20230702-a7444aa
```

**Comment by artdeell** [comment]
You are trying to allocate more RAM than your platform allows you to

> Error occurred during initialization of VM
Could not reserve enough space for 552960KB object heap
