### ISSUE TITLE
[BUG] <jar. gives an error when choosing a forge (any)> >

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#4334]
### Describe the bug

![IMG-20230627-WA0002](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/865e01f1-b31a-43f6-b4d0-0594c46878fd)
![IMG-20230627-WA0001](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/f82525f0-90d4-498a-a71d-033aa0314095)
![IMG-20230627-WA0000](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/91c11447-9148-4968-90fb-77daabe09665)
![IMG-20230627-WA0004](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/36651cbf-24c4-41c7-951b-756cbcdd55bd)
![IMG-20230627-WA0003](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/701a2836-9b0c-402b-bd9b-58515a9f51e7)

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1)launch pojavlauncher
2)Install .jar
```

### Expected Behavior

..

### Platform

```markdown
- Device model: Samsung Galaxy A52 
- CPU architecture: 
- Android version: 13
- PojavLauncher version: any
```

**Comment by Prostop194** [comment]
where can i download java 8? 
or give a link to download java 8

**Comment by GaucovyAero** [comment]
you have to choose the file by clicking on internal storage - download, not just on downloads
