### ISSUE TITLE
[BUG] Cracks appear on the edge of the item

### ISSUE THREAD

**Issue by Ktyf37** [PojavLauncherTeam/PojavLauncher#4336]
### Describe the bug

As shown in the picture, the texture of the edge is not complete (transparency), there are cracks
![Screenshot_20230706_191835_com android gallery3d](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135925971/360edb87-85b9-412a-89de-1da1395fc144)
![Screenshot_20230706_191829_com android gallery3d](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135925971/0f622202-186b-4b55-9f3e-a033e715bbcd)

### The log file and images/videos

no crash log

### Steps To Reproduce

```markdown
None
```

### Expected Behavior

Game textures should display normally

### Platform

```markdown
- Device model: HUAWEI P20
- CPU architecture: ARMv8
- Android version: 10
- PojavLauncher version: Play latest version
```

### Anything else?

None

**Comment by ghost** [comment]
If I remember correctly, this is a bug with Minecraft itself, not PojavLauncher.

**Comment by GaucovyAero** [comment]
this is normal and we cannot do anything about that
