### ISSUE TITLE
application/game crash with code -1337

### ISSUE THREAD

**Issue by santoruplay** [PojavLauncherTeam/PojavLauncher#4337]
### Describe the bug

Hello, I'm asking for your help. I downloaded the LabyMod4 version 1.16.5 and when I log in, error -1337 appears. A skinshot will be attached below. help please.

### The log file and images/videos

https://disk.yandex.ru/i/4NCnxf7TTVjnzg

### Steps To Reproduce

```markdown
1)start pojav launcher
2)choose microsoft account
3)start LabyMod4 1.16.5
```

### Expected Behavior

I want the error to go away and the money to work

### Platform

```markdown
- Device model: POCO X3 PRO
- CPU architecture:aarch64 
- Android version:11 
- PojavLauncher version: Crocus-318-97dace30c-v3_openjdk
```

**Comment by artdeell** [comment]
You did not send the log.

**Comment by santoruplay** [comment]
the crash report folder is empty

**Comment by santoruplay** [comment]
where can there be a log file?

**Comment by GaucovyAero** [comment]
> where can there be a log file?

/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/latestlog.txt

**Comment by santoruplay** [comment]
thank you, here is the log file
https://disk.yandex.ru/d/dW3Tnmpvl35Phw

**Comment by Tet100** [comment]
Put java 17

**Comment by santoruplay** [comment]
with java 17, the same result, I'll throw off a new log file
https://disk.yandex.ru/d/dW3Tnmpvl35Phw

**Comment by NotAHero04** [comment]
Bytecode mods + VirGL (well I didn't choose the vanilla theme)
![Screenshot_20230709_211609_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/84689840/b0f3da31-1807-495b-b1d0-5e0c8469865c)

**Comment by ConfectionaryQwQ** [comment]
> Bytecode mods + VirGL (well I didn't choose the vanilla theme) ![Screenshot_20230709_211609_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/84689840/252152737-b0f3da31-1807-495b-b1d0-5e0c8469865c.jpg)

Tell me how to launch labymod4 pls,I tired Java17 but it still crashed

**Comment by codeplaya187** [comment]
guys, please help me fix Laby 4, i install Java 17, but nothing will happen

https://disk.yandex.ru/d/NJknk-Mvn57COg
