### ISSUE TITLE
Labymod 4 no working on Pojav

### ISSUE THREAD

**Issue by Tet100** [PojavLauncherTeam/PojavLauncher#4338]
### Describe the bug

Hello, Labymod 4 just recently came out, I and other people tried to log in, but either the error -1337) is repaired if you select Java 17), or it stops starting

### The log file and images/videos

![Screenshot_2023-07-07-14-15-07-418_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/137201887/880d2cd3-5c5d-4cf8-81a0-241188b2202e)

### Steps To Reproduce

```markdown
1. You need to use the installation instructions from the site
2. A new profile appears, set Java 17
3. We go into the magazine, and wait
```

### Expected Behavior

I thought everything would go well, but just stop the launch, and that's it 

### Platform

```markdown
- Device model: camellian_global M2103K19G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

They write that it is not supported by pressing the launcher. But you write that installation is possible

**Comment by ghost** [comment]
magazine?

**Comment by aaaapai** [comment]
> magazine?

He didn't provide a log, but I can provide a log. I booted labymod4 and crashed.

**Comment by aaaapai** [comment]
> magazine?

He didn't provide a log, but I can provide a log. I booted labymod4 and crashed.
[2023-07-08-4.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/11987205/2023-07-08-4.log.gz)

**Comment by Linh3870676** [comment]
I'm too

**Comment by Tet100** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12065100/latestlog.txt)
Вот мой

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | dahlia - 759 - v3_openjdk |
| Minecraft version | labymod-4-1.20.1-808c29e2 - VANILLA |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 17 |
| Java arguments |  |

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | dahlia - 759 - v3_openjdk |
| Minecraft version | labymod-4-1.20.1-808c29e2 - VANILLA |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 17 |
| Java arguments |  |

**Comment by Tet100** [comment]
[2023-07-17-4.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/12065103/2023-07-17-4.log.gz)
Here is the log

**Comment by GaucovyAero** [comment]
labymod does not work
