### ISSUE TITLE
application/game crash with code -1337

### ISSUE THREAD

**Issue by santoruplay** [PojavLauncherTeam/PojavLauncher#4339]
### Describe the bug

Hello, I'm asking for your help. I downloaded the LabyMod4 version 1.16.5 and when I log in the error -1337 appears

### The log file and images/videos

![Screenshot_2023-07-07-13-35-21-405_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104296059/6dad7b5a-1408-4cca-9dfb-336d1f430958)
https://disk.yandex.ru/d/dW3Tnmpvl35Phw

### Steps To Reproduce

```markdown
1) start pojav launcher
2)select and log in to my Microsoft account
3)start minecraft
```

### Expected Behavior

I want the error to go away and the money to work

### Platform

```markdown
- Device model: POCO X3 PRO 6/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Crocus-318-97dace30c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
labymod does not work
