### ISSUE TITLE
Right trigger doesn't register on Xbox One Controller

### ISSUE THREAD

**Issue by Surasia** [PojavLauncherTeam/PojavLauncher#4340]
### Describe the bug

My current controller has a broken right trigger, causing it to only press up to 99%. All other buttons work fine, however PojavLauncher doesn't recognize it as it's not "fully pressed".

### The log file and images/videos

![Screenshot_20230707_170659_PojavLauncher (Minecraft Java Edition fer Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/74399067/edc31a12-018b-4bfc-bda4-4359f04713d4)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Reset controller settings
3. Connect Xbox One controller
4. Get into Java runtime and set up your controller
```

### Expected Behavior

The trigger should register and the button selection should continue.

### Platform

```markdown
- Device model: Samsung S20 FE
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Latest from Github Actions as of 7/7/23
```

**Comment by CCShakeCat** [comment]
I can confirm that RT didn't work. I also tried on the DualSense controller, and same result

**Comment by Surasia** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/commit/bf2aa6c853603683bf1af3147819a79f9f132f72

@Mathias-Boulay related?

**Comment by Mathias-Boulay** [comment]
@Surasia Half related. It addressed a bug that would make mapping impossible on triggers when the screen was touched.

I'm not sure it fixes your case. @Surasia and @MimiCatGH can you contact me through the official PojavLauncher discord ?
It would be easier to perform some testing to narrow down the cause of the issue

**Comment by Mathias-Boulay** [comment]
Alternatively, try out this build I just made https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5649486158

**Comment by Surasia** [comment]
> Alternatively, try out this build I just made https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5649486158

Thank you, that worked! Issue can be closed now.

**Comment by Mathias-Boulay** [comment]
nice
