### ISSUE TITLE
[BUG] <Nethe Dimension Screen Flickering>

### ISSUE THREAD

**Issue by FarisFadh** [PojavLauncherTeam/PojavLauncher#4341]
### Describe the bug

Application Flickering in nether dimension in my optimized world 

### The log file and images/videos

Bug

### Steps To Reproduce

```markdown
Start pojav launcher in optimized world with optifine
```

### Expected Behavior

Flicker

### Platform

```markdown
- Device model:M201K7BNY
- CPU architecture:aarch64
- Android version: 12
- PojavLauncher version: current of playstore
```

### Anything else?

Bug

**Comment by GaucovyAero** [comment]
cant do anything about this, no video provided too
