### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Gregory269** [PojavLauncherTeam/PojavLauncher#4344]
### Describe the bug

Currently, when we want to play Pojavlauncher with the "Essential Mod" mod, the game crashes when confirming the privacy policy, etc.
I tried on any renderer and on Fabric and both Forge. Will you add support for this mod??

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/89700145/ec18e95b-7569-4d38-8b3e-252e27d147e7

Uploading lv_0_20230709110714.mp4…

### Steps To Reproduce

```markdown
1. Enable pojav
```

### Expected Behavior

Game crash with code -1

https://github.com/PojavLauncherTeam/PojavLauncher/assets/89700145/ba9f82bc-6937-49a5-af5b-4c4b88948d7d

### Platform

```markdown
- Device model: Huawei P30 Lite 4/128GB
- CPU architecture: aadch64
- Android version: 10
- PojavLauncher version: newest
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
they made it so that it wont work on pojav and they will not fix it
essential is not open source, it tracks all your device specifications and other spooky stuff, i dont recommend using it at all, even on pc
