### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Looksc** [PojavLauncherTeam/PojavLauncher#4345]
### Is this request related to a bug?

Id:
Rubidium dan rubidium extra vs optifine
Mana yang lebih bagus? untuk forge 1.18.2

Rubidium
https://www.curseforge.com/minecraft/mc-mods/rubidium
Rubidium extra
https://www.curseforge.com/minecraft/mc-mods/rubidium-extra

Jika rubidium lebih bagus daripada optifine boleh kah saya meminta settingan nya?

English:
Rubidium and rubidium extra vs optifine
Which one is better? For forge 1.18.2

Rubidium
https://www.curseforge.com/minecraft/mc-mods/rubidium
Rubidium extra
https://www.curseforge.com/minecraft/mc-mods/rubidium-extra

If rubidium is better than optifine, can you share the settings From rubidium

Sorry my english is bad

**Comment by GaucovyAero** [comment]
optifine is faster
