### ISSUE TITLE
[BUG] <Error -1.>

### ISSUE THREAD

**Issue by Bonnie3310** [PojavLauncherTeam/PojavLauncher#4347]
### Describe the bug

The application crashes after 10 seconds of being in the world.
Error code -1.
Help please.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12000594/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher.
2. Start Minecraft forge 1.12.2
3. Open my world
4. Minecraft crashes after 10 seconds of being in my world with error code -1.
```

### Expected Behavior

I can play miinecraft.

### Platform

```markdown
- Device model: SM-A137F
- CPU architecture: aarch32
- Android version: 13
- PojavLauncher version: latest release
```

### Anything else?

Everything was fine on the old version.

**Comment by GaucovyAero** [comment]
make sure your world is compatible with the game version you are playing on, issue not related to pojav

**Comment by Bonnie3310** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12335991/latestlog.txt)
I create new world and minecraft crash...

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.12.2-optifine_hd_u_g5 - OPTIFINE |
| Renderer | HOLY_GL4ES_114 |
| Architecture | ARM_32 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by Bonnie3310** [comment]
and I noticed that when I put Java 17 minecraft does not crash, but the forge does not work on java 17
