### ISSUE TITLE
The mouse is not working

### ISSUE THREAD

**Issue by HEBEI77** [PojavLauncherTeam/PojavLauncher#4351]
### Describe the bug

The mouse seems for some reason not to work in newer versions

### The log file and images/videos

I don't think you need screenshot for this

### Steps To Reproduce

```markdown
1. Start povaj launcher
2. Try to use the mouse
```

### Expected Behavior

The game launches with out no problem but the mouse is for some reason not working

### Platform

```markdown
- Device model:Redmi note 8
- CPU architecture:aarch64
- Android version:11
- PojavLauncher version:dahlia-740-623f7dd33-v3_openjdk
```

**Comment by Inverted-Fin** [comment]
同样的问题,在我退出服务器之后鼠标和按键也是失灵了(version:1.20.1fabric)

**Comment by GaucovyAero** [comment]
please record a video
