### ISSUE TITLE
[BUG] <A very serious control problem on 1.19.4 And above> 

### ISSUE THREAD

**Issue by Inverted-Fin** [PojavLauncherTeam/PojavLauncher#4353]
### Describe the bug

When I entered the server, the button control was still normal.When I entered the server and played for a period of time,during play time, There was a significant delay in the buttons.and then lightly clicked to exit, the button suddenly pressed onto another server,Followed by a very large touch delay,This has had a significant impact on my gaming experience

### The log file and images/videos

no files

### Steps To Reproduce

```markdown
1.launch game
2.enter server
3.play a time,exit server
4.When exiting, control the ventilation and press it to another server on your own
5.Afterwards, the button malfunctioned
```

### Expected Behavior

Improve control on high version experience

### Platform

```markdown
- Device model: oppo k10
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: dahlia-20230702-a7444aa-v3_openjdk
```

**Comment by Inverted-Fin** [comment]
version:1.20.1fabric

**Comment by GaucovyAero** [comment]
closing, as this is a duplicate issue
