### ISSUE TITLE
[BUG] The game crashes upon entering the world

### ISSUE THREAD

**Issue by kjnjubj** [PojavLauncherTeam/PojavLauncher#4354]
### Describe the bug

The game didn't give me any exit code, it just crashed.
Version: 1.16.5 Forge
Mods: Geckolib, Sodium, Public transit mod (not mtr mod).

### The log file and images/videos

There aren't any buttons in the video because I hid them.
video: https://www.mediafire.com/file/smxd2yklfvm0tsx/SVID_20230711_170330_1.mp4/file (it was too big)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12013069/latestlog.txt)

### Steps To Reproduce

```markdown
1 Starting pojavlauncher
2 Clicking my world 
3 The game crashes without exit code
```

### Expected Behavior

I expected the world would load

### Platform

```markdown
- Device model: Huawei (MRX-W29)
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: dahlia-176-641eae051-v3_openjdk
```

**Comment by GaucovyAero** [comment]
sodium generally does not work, dont use it
