### ISSUE TITLE
Using physical mouse only works of half the screen

### ISSUE THREAD

**Issue by termonaitor2004** [PojavLauncherTeam/PojavLauncher#4356]
### Describe the bug

Happens on all Minecraft versions. When I'm using a physical mouse I can't use it on the right half of the screen. just doesn't work

### The log file and images/videos

Log doesn't display anything even after turning it on an reinstalling app

### Steps To Reproduce

```markdown
Plug in mouse or use Bluetooth
Start pojav launcher 
Try to use mouse on right side of screen
```

### Expected Behavior

I expect to be able to use mouse ex1 to exit the game 

### Platform

```markdown
- Device model: pixel 6 pro
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: dahlia-740-623f7dd33-v3_opemjdk
```

### Anything else?

Controller cursor works perfectly. I can click the mouse dialog and drag the cursor with physical mouse and it works

**Comment by GaucovyAero** [comment]
please record the issue

**Comment by JSHSJSJSHHSJSJ** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/4356#issue-1799039865
