### ISSUE TITLE
Black textures when jkining game and leaving cause black text[BUG] <Short description>

### ISSUE THREAD

**Issue by Hal1WasHere** [PojavLauncherTeam/PojavLauncher#4357]
### Describe the bug

black texture when leave black text

### The log file and images/videos

![Screenshot_20230711_071828_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/111131258/22e75784-4096-44c4-87fe-8cd6a0aaa8e5)

### Steps To Reproduce

```markdown
balck text and texture
```

### Expected Behavior

game good to launch but the textures is all black. 

### Platform

```markdown
- Device model: huawei Med-Lx9
- CPU architecture:32 
- Android version: 10
- PojavLauncher version: 3.3.1.1_rel_20210206
```

**Comment by GaucovyAero** [comment]
3.3.1.1 is very old, update to the latest play store version
