### ISSUE TITLE
Delete the application

### ISSUE THREAD

**Issue by Konraiser** [PojavLauncherTeam/PojavLauncher#4358]
### Describe the bug

I want to install earlier version of launcher but I can't delete the latest version.  Other apps deletes correctly. 

### The log file and images/videos

Doesn't exist

### Steps To Reproduce

```markdown
1. Delete pojav launcher
```

### Expected Behavior

I expected the launcher would delete. 

### Platform

```markdown
- Device model: Samsung galaxy a12
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: dahila-20230709-fcafb3e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
uninstall it, do not delete
