### ISSUE TITLE
VirGL and Zink Renderer Bug 

### ISSUE THREAD

**Issue by worstmiky** [PojavLauncherTeam/PojavLauncher#4360]
### Describe the bug

![Screenshot_2023-07-13-11-15-55-799_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/6fc44898-f4e6-47f2-8fb1-b1993bcb3e18)
![Screenshot_2023-07-13-11-07-04-126_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/23ae8095-2bf5-4bfe-8587-b1f5f80bc888)
![Screenshot_2023-07-13-11-06-54-000_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/1c2867b3-7e32-491b-b5f8-d9cede7b8c6b)
![Screenshot_2023-07-13-11-06-35-280_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/0b2d7390-2898-47e7-87ab-617c1cf1a63d)
![Screenshot_2023-07-13-11-06-46-736_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/dd6c0750-4284-4032-a91a-43db1949afdd)
![Screenshot_2023-07-13-11-05-56-103_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/618988e5-3689-4335-8877-651618a37ad0)
![Screenshot_2023-07-13-11-05-36-597_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/9d2ebe0a-67b3-4d2b-b5f7-42c89f7e6334)
![Screenshot_2023-07-13-11-05-31-840_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/cd0cc84b-352d-4f1c-b3d8-47b1aff5dd1a)
![Screenshot_2023-07-13-11-04-26-733_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/9ea1a5f0-a6f8-44b6-ac54-b18c5986aec3)
![Screenshot_2023-07-13-11-04-16-440_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/ac3bfb2c-d2cc-4b66-a5ed-2d66b927ed57)

### The log file and images/videos

![Screenshot_2023-07-13-11-04-26-733_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/9f871794-e7ae-4553-990d-38012ad5e78a)
![Screenshot_2023-07-13-11-05-31-840_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/e2784618-9534-413b-897b-d3b25a089cc4)
![Screenshot_2023-07-13-11-04-16-440_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/92eb0cb7-1102-493e-b521-e7d0381440e7)

### Steps To Reproduce

```markdown
A happen bug
```

### Expected Behavior

I expect of the game i run my shader, but some of my phone can run the shader. 
![Screenshot_2023-07-13-11-07-04-126_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/13cb9c5a-7e8a-449c-852c-cde0493ea85b)

### Platform

```markdown
- Device model: POCO M3 4/64
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Latest
```

### Anything else?

Please fix VirGL and Zink i want to try Shader in andreno gpu snapdragon 610
![Screenshot_2023-07-13-11-24-20-479_com android settings](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139354718/79c93b33-3f03-404f-ac3c-bb392c6ade75)

**Comment by victorkayne2nd** [comment]
Turnip-Zink is a work-in-progress thing. Also, I have Adreno 610 and I can try to compile a "custom build version" to use in launcher and tries to run, but I don't know where the Zink goes at the launcher code.

**Comment by Bel69420** [comment]
Adreno Have a driver issue with VIRGL so chance of fixing it os 19.0%

**Comment by Bel69420** [comment]
is*

**Comment by Bel69420** [comment]
Virgl runs fine on Mali

**Comment by GaucovyAero** [comment]
you can now download zink from the zink branch on github actions, we wont be fixing virgl, it will be removed later on
