### ISSUE TITLE
[BUG] Incompatible with switchy

### ISSUE THREAD

**Issue by Sandr-aa** [PojavLauncherTeam/PojavLauncher#4361]
### Describe the bug

When launching Quilt with Switchy, the game crashes after loading mappings 
`java.lang.Error: java.io.IOException: Cannot run program "/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin/java": error=13, Permission denied`

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12037206/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install Quilt for 1.20.1
2. Add https://modrinth.com/mod/switchy
3. Start the Game
```

### Expected Behavior

The Game starts

### Platform

```markdown
- Device model: Samsung Galaxy S8 Wifi
- CPU architecture: aarch64
- Android version: Android 13 (OneUI 5.1)
- PojavLauncher version: Latest Release
```

**Comment by artdeell** [comment]
You need to disable forked guis in quilt, no idea how to do that though

**Comment by artdeell** [comment]
Although that won't fix the issue, because quilt seems to show an error message
