### ISSUE TITLE
[BUG] Game texture error

### ISSUE THREAD

**Issue by Ktyf37** [PojavLauncherTeam/PojavLauncher#4363]
### Describe the bug

When I move the screen quickly, the game texture flickers, I think this is a bug.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/135925971/5b52df4a-e617-4a5a-b4ff-5b21e7c3f98e

### Steps To Reproduce

```markdown
Start game
```

### Expected Behavior

Game textures should display normally, without flickering.

### Platform

```markdown
- Device model: HUAWEI P20
- CPU architecture: AArch64
- Android version: 10
- PojavLauncher version: Play latest version
```

### Anything else?

None

**Comment by Bel69420** [comment]
that's normal

**Comment by Bel69420** [comment]
~probably opengl texture clipping~

**Comment by GaucovyAero** [comment]
mali gpus do not have high precision
