### ISSUE TITLE
Where is my .minecraft folder

### ISSUE THREAD

**Issue by 06NinjaKid06** [PojavLauncherTeam/PojavLauncher#4364]
### Describe the bug

I have no sdcard, stop telling me to search scars, I go even into android search and search .minecraft (hidden files enabled) but can't find it

### The log file and images/videos

Can't go in my data folder "These files need to be viewed on a computer" pops up

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Mess around trying to find where the .minecraft folder is so you can put a forge mod
```

### Expected Behavior

To be able to search for .minecraft and it appear

### Platform

```markdown
- Device model: Samsung Galaxy A32/5G
- CPU architecture: idk
- Android version: 13
- PojavLauncher version: Latest release
```

### Anything else?

I don't have an sdcard

**Comment by 06NinjaKid06** [comment]
i used a pc to fix this but help for doing this without a PC would be helpful

**Comment by kedrick021** [comment]
Use hidden files enable on file manager

**Comment by 06NinjaKid06** [comment]
> Use hidden files enable on file manager

I did

**Comment by VenomousSteam81** [comment]
@06NinjaKid06 are you using a pc to put the mods on it? if so, thats why. samsung made it so hidden folders arent viewable on pc, so you will need to use a file manager like MiXplorer or ZArchiver

**Comment by 06NinjaKid06** [comment]
> @06NinjaKid06 are you using a pc to put the mods on it? if so, that's why. samsung made it so hidden folders aren't viewable on pc, so you will need to use a file manager like MiXplorer or ZArchiver

Other way around, they are viewable on pc but not android also Zarchuver cant go in my android/data folder

**Comment by GaucovyAero** [comment]
/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/
it is recommended to use mixplorer (free to download via mixplorer.com)

**Comment by raynblaze23copper** [comment]
guys, my "net.kdt.pojavlaunch" empty. How to fix it? I have saved lots of worlds in the game, i decided to try using resources pack but when i was going to put the resources pack i want in the resourcepacks file my "net.kdt.pojablaunch" is empty. I remembered that its not empty. get it? (sorry bad english)

**Comment by n1kohere** [comment]
> /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/ it is recommended to use mixplorer (free to download via mixplorer.com)

idk why, but it doesn't show me anything after /storage/emulated/0, it's just empty

**Comment by Akratet** [comment]
Same for me, but i don't have files at all for some reason

**Comment by CamoWolf1222** [comment]
> 
> idk why, but it doesn't show me anything after /storage/emulated/0, it's just empty

The Samsung android/data folder is funky like that. I used ZArchiver (other file managers may work) to get to /storage/emulated/0 (this is usually your home directory) and then from there go to android/ and in there you can find data/ (it said mine was empty on first glance, but opening the folder showed just the opposite). Go into the data/ folder and look for the pojavlauncher folder and from there you can find the .minecraft/ folder.

**Comment by ForMicrosoftAllTheWays** [comment]
where do i find the mods folder? and how do i upload them?

**Comment by ForMicrosoftAllTheWays** [comment]
![image](https://github.com/user-attachments/assets/fb24e9b2-f7df-4c90-9f9b-2a89ec9d2c2f)
im trying to upload via pc any way to find the mods folder?

**Comment by ForMicrosoftAllTheWays** [comment]
figured it out

**Comment by ForMicrosoftAllTheWays** [comment]
i just dont know why it wont let me type the server ip
is there any way i can transfer the servers via na  file?

**Comment by ForMicrosoftAllTheWays** [comment]
im attempting to move the servers.dat to the .minecraft and the version/1.20.1 forge but it wont let me know why???

**Comment by CamoWolf1222** [comment]
> im attempting to move the servers.dat to the .minecraft and the version/1.20.1 forge but it wont let me know why???

IDK, open a new issue maybe?

**Comment by ForMicrosoftAllTheWays** [comment]
now the game crashes on launch

**Comment by CamoWolf1222** [comment]
The title of this issue is "where is my .minecraft folder" not "my game crashed for unknown reasons after I moved the 'server.dat' file". Please do not use this issue to discuss a new issue. Make a new issue. Especially since these issues have nothing to do with each other.
