### ISSUE TITLE
VIC MODERN WARFARE plss fix the lag

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4365]
### Describe the bug

Lagging on latest version on GitHub and old version not lagging 

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/a689bb19-dee0-44d4-b6d8-f6279805f9b7

Latest GitHub

https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/f51c66c6-74a0-406f-a425-119a91e70508

Old version but crashed on 1h

### Steps To Reproduce

```markdown
1. Start the pojavlauncher
2. Create world
3. Use Vic Modern weapon
4. Lagging on weapon
```

### Expected Behavior

Not lagging 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Plss fix

**Comment by icyllite** [comment]
you dont give your device information so i assume you got a potato device
the solution: get a better device

**Comment by kedrick021** [comment]
> you dont give your device information so i assume you got a potato device the solution: get a better device

Did you watch the video how is potato there ?

**Comment by icyllite** [comment]
> > you dont give your device information so i assume you got a potato device the solution: get a better device
> 
> Did you watch the video how is potato there ?

¯\_(ツ)_/¯ you didnt write your device info how should i know 
perhaps use the old version in the meantime

**Comment by kedrick021** [comment]
I make two video the old and new pojavlauncher version and Only one version for modern warfare latest version and my phone
Umidigi bison
6gb/125gb
Android 10
64

**Comment by kedrick021** [comment]
> 

I make two video the old and new pojavlauncher version and Only one version for modern warfare latest version and my phone
Umidigi bison
6gb/125gb
Android 10
64

**Comment by icyllite** [comment]
> > 
> 
> I make two video the old and new pojavlauncher version and Only one version for modern warfare latest version and my phone Umidigi bison 6gb/125gb Android 10 64

seems decent, what renderer youre using, and how many memory you allocated, or maybe you could send me the log file

**Comment by kedrick021** [comment]
> > > 
> > 
> > 
> > I make two video the old and new pojavlauncher version and Only one version for modern warfare latest version and my phone Umidigi bison 6gb/125gb Android 10 64
> 
> seems decent, what renderer youre using, and how many memory you allocated, or maybe you could send me the log file

Gl4ES but I don't think that the phone problem because I try another phone Mali and adreno and it's same problem it's pojavlauncher when I use latest it's lagging but old version not

**Comment by icyllite** [comment]
> 

what minecraft and mod version you use, im gonna try it on my device

**Comment by kedrick021** [comment]
> > 
> 
> what minecraft and mod version you use, im gonna try it on my device

1.12.2 Vic Modern weapon 3.0 latest update and latest pojavlauncher GitHub

**Comment by GaucovyAero** [comment]
probably just use the old version of pojavlauncher if it works better for you
