### ISSUE TITLE
[BUG] Crash when starting up Forge 1.17+

### ISSUE THREAD

**Issue by Zue5s** [PojavLauncherTeam/PojavLauncher#4366]
### Describe the bug

This only happens when i use the forge version of minecraft 1.17+, older versions of minecraft forge work but this doesnt

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12046072/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Game with forge version 1.17 or over
```

### Expected Behavior

I expected it to work like versions under forge 1.17

### Platform

```markdown
- Device model: samsung galaxy tab s7
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: latest on google play
```

### Anything else?

When i try to launch version 1.17+ vanilla, it works, but i still wanted to use mods and ANGLE renderer to have better performance with shaders

**Comment by Zue5s** [comment]
It might be because the java or whatever is corrupted or missing since it says that "libjvm.so" is not found

**Comment by GaucovyAero** [comment]
your forge mods are incompatible
