### ISSUE TITLE
[BUG] bug create mod?

### ISSUE THREAD

**Issue by Looksc** [PojavLauncherTeam/PojavLauncher#4369]
### Describe the bug

How do configure it like this?

### The log file and images/videos

![2023-07-14_16 28 12](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136565680/c8f4ca79-8219-413c-a6b0-31e62bac99f6)
![2023-07-14_16 09 15](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136565680/b32203ae-e7ec-40cd-b4f5-312d3b3b6a1c)

### Steps To Reproduce

```markdown
1.start pojav launcher
2.open create configuration menu
```

### Expected Behavior

Hope it's fixed quickly

### Platform

```markdown
- Device model: mi max 2 4/64G
- CPU architecture: aarch64
- Android version: 7.1
- PojavLauncher version: latest on google play
```

### Anything else?

Help please ,and I use holy gl4es. I've tried using render
Virgl 

Sorry for my English

**Comment by Forever2397** [comment]
try using the angle renderer, so that the flywheel configuration works

**Comment by Looksc** [comment]
> try using the angle renderer, so that the flywheel configuration works

I cant using the angle renderer 😅

**Comment by Bel69420** [comment]
Yeah, because he has Android 7.1 and Angle only support android 10 (Q) and above

**Comment by Bel69420** [comment]
try pojavlauncher from github action

**Comment by Looksc** [comment]
> try pojavlauncher from github action

Thanks you

**Comment by Looksc** [comment]
> try pojavlauncher from github action

I try using https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5581879809

 Just the same

Sama aja

**Comment by Bel69420** [comment]
Kayaknya dari masalah gpu driver hape kamu, hp kamu terlalu tua dan drivernya sudah ketinggalan jaman.

**Comment by Bel69420** [comment]
~~why did i use Indonesian language~~

**Comment by Looksc** [comment]
> Kayaknya dari masalah gpu driver hape kamu, hp kamu terlalu tua dan drivernya sudah ketinggalan jaman.

Maybe

Mungkin

**Comment by Looksc** [comment]
> ~why did i use Indonesian language~

~Hahaha thanks you~
