### ISSUE TITLE
Cant log in Microsoft account

### ISSUE THREAD

**Issue by kdidbkdisgdhdjs** [PojavLauncherTeam/PojavLauncher#4371]
### Describe the bug

java.lang.RuntimeException: Not Found
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87)
at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

![Screenshot_20230714_210906_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139532805/9953161e-a09a-4fdc-87ef-70f3a42d358d)

### Steps To Reproduce

```markdown
1. Can't log in microsft account
```

### Expected Behavior

I was trying to log in my Microsoft Account and it said it "seems like this account does not have a minecraft profile. lf you have xbox game pass, please log in on" I keep log in it did not work

### Platform

```markdown
- Device model: samsung
- CPU architecture: I don't know
- Android version:ui 5.1
- PojavLauncher version: 1.19.4
```

### Anything else?

it seems like this account does not have a minecraft profile. lf you have xbox game pass, please log in on

**Comment by ghost** [comment]
Do you own Minecraft: Java Edition on the account you are logging in on?

**Comment by kdidbkdisgdhdjs** [comment]
I dont

**Comment by ghost** [comment]
well, you need Minecraft: Java Edition on that account for it to work :/

**Comment by kokokocraft** [comment]
I have an xbox gamepass account but I still can't log in

**Comment by ghost** [comment]
First, log in on minecraft.net.

**Comment by GaucovyAero** [comment]
log into minecraft.net first, you have to set up your profile

**Comment by dydhhsjsh** [comment]
> ### Opisz błąd
> java.lang.RuntimeException: Nie znaleziono w net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297) w net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin( Logowanie w tle Microsoft .java:87) pod adresem net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(nieznane źródło:8) pod adresem java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) pod adresem java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) i java.lang.Thread.run(Thread.java:1012)
> 
> ### Plik dziennika i obrazy/filmy
> ![Screenshot_20230714_210906_PojavLauncher (Minecraft Java Edition dla systemu Android)](https://user-images.githubusercontent.com/139532805/253579668-9953161e-a09a-4fdc-87ef-70f3a42d358d.jpg)
> 
> ### Kroki ku reprodukcji
> ```
> 1. Can't log in microsft account
> ```
> 
> ### Spodziewane zachowanie
> I was trying to log in my Microsoft Account and it said it "seems like this account does not have a minecraft profile. lf you have xbox game pass, please log in on" I keep log in it did not work
> 
> ### Platform
> ```
> - Device model: samsung
> - CPU architecture: I don't know
> - Android version:ui 5.1
> - PojavLauncher version: 1.19.4
> ```
> 
> ### Anything else?
> it seems like this account does not have a minecraft profile. lf you have xbox game pass, please log in on
