### ISSUE TITLE
[BUG] I can't see around!

### ISSUE THREAD

**Issue by seriousfreezing** [PojavLauncherTeam/PojavLauncher#4372]
### Describe the bug

I'm playing a modpack on version 1.12.2 with Forge, and I can't move the camera.

### The log file and images/videos

/

### Steps To Reproduce

```markdown
1. Install Forge with Mods;
2. Play an world;
3. Try move the camera.
```

### Expected Behavior

I can move the camera

### Platform

```markdown
- Device model: Motorola G7 Plus
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version: Latest release
```

**Comment by GaucovyAero** [comment]
no log provided
