### ISSUE TITLE
[BUG] button hidded problem

### ISSUE THREAD

**Issue by TGJASSIYT** [PojavLauncherTeam/PojavLauncher#4375]

**Comment by ghost** [comment]
f1 is a feature of Minecraft, not PojavLauncher.

**Comment by GaucovyAero** [comment]
> f1 is a feature of Minecraft, not PojavLauncher.

the issue is that his hand is rendering but everything else isnt, its a GE8320 GPU issue, not F1

@TGJASSIYT install optifine, go into video settings -> shaders and enable antialiasing to 2x fxaa
