### ISSUE TITLE
I cant find my password in local account in pojavlauncher 

### ISSUE THREAD

**Issue by kdidbkdisgdhdjs** [PojavLauncherTeam/PojavLauncher#4383]
### Describe the bug

How do I find my local account Password I Need A Password To Join Cracked Server And I don't know how How to find my password

### The log file and images/videos

:/

### Steps To Reproduce

```markdown
How do I find my password in local account
```

### Expected Behavior

None

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Nothing

**Comment by kdidbkdisgdhdjs** [comment]
Is it possible?

**Comment by ghost** [comment]
you do /login

**Comment by kdidbkdisgdhdjs** [comment]
And

**Comment by ghost** [comment]
oh wait. you must've picked a username that someone already has taken on a server. Change your username, and follow the instructions in chat.
