### ISSUE TITLE
[BUG] What is the keycode of SPECIAL_PRI?

### ISSUE THREAD

**Issue by mesflit** [PojavLauncherTeam/PojavLauncher#4385]
### Describe the bug

What is the keycode of SPECIAL_PRI?

### The log file and images/videos

What is the keycode of SPECIAL_PRI?

### Steps To Reproduce

```markdown
What is the keycode of SPECIAL_PRI?
```

### Expected Behavior

What is the keycode of SPECIAL_PRI?

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ghost** [comment]
That is the keycode. You can only use it via custom controls, you can't select "send custom keycode"

**Comment by victorkayne2nd** [comment]
SPECIAL_PRI is the key code for the left mouse button.

**Comment by hiimabignoobwihenolive** [comment]
this bug needs to be fixed lmao
