### ISSUE TITLE
[F-Req] Add ui for automatically downloading MixinBooter for forge 1.12.2 and lower.

### ISSUE THREAD

**Issue by offbeat-stuff** [PojavLauncherTeam/PojavLauncher#4386]
### Is this request related to a bug?

Not really.

### Describe the request.

MixinBooter is a mod library required to run mixin on forge 1.12.2.

Here is the maven link:

https://repo.cleanroommc.com/releases/zone/rong/mixinbooter/8.3/mixinbooter-8.3.jar

from here:
https://github.com/LoliKingdom/MixinBooter

This could be implemented through the settings menu for an instance.

### Anything else?

Modpack support would be nice though thats streching it a bit right?

**Comment by GaucovyAero** [comment]
the modpack installer will be added in the soon upcoming play store update, no mixinbooter though
