### ISSUE TITLE
[F-Req] [Controls] Custom variables for hotbar height and width

### ISSUE THREAD

**Issue by Felix14-v2** [PojavLauncherTeam/PojavLauncher#4388]
### Description

PojavLauncher already calculates the hotbar position to detect clicks on it. And adding [custom controls variables](https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Custom-controls-variables#custom-controls-variables) with its height and width would greatly simplify the binding of buttons to the visible part of hotbar:
![Screenshot_20230215-150254](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/0f011e11-51f2-4d4c-aa78-ee5e4450f134)
~Actually having only one of them is enough, but who cares :D~

This would allow custom controls creators to partially fix problems with buttons mispositioning:
![Screenshot_20230216-092744](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/dda0980e-a002-4623-9c79-c17d26e17258)

### Additional

It would be extremely cool to be able to assign variables in the height and width of the buttons. For example, for the inventory button from the screenshot above, so that it looks equally good on all screens.

**Comment by Mathias-Boulay** [comment]
While this is a plan of mine since a long while, I have yet to make a proper integration that sits well with the user... Actually I have an idea, I'll keep it in mind for controls v3.

**Comment by Felix14-v2** [comment]
Controls v3? 👀 
Is the current default controls a subject to change, or you mean just a bunch of new features for controls creators? Can I read somewhere more about them if so?
Also thanks for the answer!

**Comment by Mathias-Boulay** [comment]
The latter but perhaps the first as well.

**Comment by Felix14-v2** [comment]
I found that you can use this formula to perfectly align the button to the right side of hotbar: `dynamicX: "${screen_width}/2 + ${height}*3.95"`
So the only problem is to set the size of the buttons, but I believe this can be done manually by user. Especially considering that  in some cases Pojav determines the width of the hotbar incorrectly.
