### ISSUE TITLE
[BUG] <1.7.10 Various rendering errors>

### ISSUE THREAD

**Issue by Ink305Mua** [PojavLauncherTeam/PojavLauncher#4389]
### Describe the bug

I've been getting all kinds of rendering errors, sometimes at the beginning of the game, sometimes after playing for a while, and I've been playing for ten days straight in this situation, and it's been an extremely poor gaming experience! I hope you can fix this!

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12108537/latestlog.txt)

![Screenshot_20230720_203247_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/95970342/67c285c8-4c86-46b7-804f-d128851e952f)

![Screenshot_20230720_203736_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/95970342/da7b4ec8-8604-49f0-ab32-a9c027c4b4a4)

And that's not all!

### Steps To Reproduce

```markdown
1.Launch PojavLauncher
2.Go to game archive
3.Started having problems with various rendering errors
```

### Expected Behavior

I hope you guys can fix this.

### Platform

```markdown
- Device model: HONOR 20 PRO/256G
- CPU architecture: aarch64
- Android version: 10 / HarmonyOS version: 3.0.0
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by caiji233r** [comment]
![Uploading Screenshot_20230720_141917_net.kdt.pojavlaunch.jpg…]()

**Comment by Ink305Mua** [comment]
![Screenshot_20230720_140648_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/95970342/c23f8a08-6e14-417b-b73b-bd43657e2c6b)

**Comment by caiji233r** [comment]
![Uploading Screenshot_20230720_141917_net.kdt.pojavlaunch.jpg…]()

**Comment by Ink305Mua** [comment]
![Uploading Screenshot_20230720_141917_net.kdt.pojavlaunch.jpg…]()

**Comment by Bel69420** [comment]
Out of VRam ig

**Comment by Bel69420** [comment]
Changing renderer to zink should fix it
