### ISSUE TITLE
Game exited with code 0.

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#439]
It always say game exited with code 0

**Comment by Adity-png** [comment]
I also  same problems

**Comment by WesleyVanNeck** [comment]
Use the latest dev build or install lwjgl

**Comment by ghost** [comment]
> Use the latest dev build or install lwjgl

I installed lwjgl3 and latest build

**Comment by khanhduytran0** [comment]
Latest build auto install a compatible LWJGL3, so you installed again led to incompatible.
