### ISSUE TITLE
[BUG] PojavLauncher crash when removing all profiles

### ISSUE THREAD

**Issue by HyperLuna** [PojavLauncherTeam/PojavLauncher#4390]
### Describe the bug

PojavLauncher crash when all profiles were removed

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12123303/latestcrash.txt)

no latestlog.txt because app reinstalled

### Steps To Reproduce

```markdown
1. install apk
2. edit current profile
3. delete it
4. repeat 2,3 until all profiles were removed
5. app crash
```

### Expected Behavior

keep running when no profile exist
or
preserve or regenerate default profile

### Platform

```markdown
- Device model: raphael Redmi K20 Pro
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-20230718-8ef6607-v3_openjdk
```

**Comment by helmo2019** [comment]
The easiest fix for now is to just delete launcher_profiles.json, as this will restore the default profile.

**Comment by Mathias-Boulay** [comment]
This should be addressed by the latest mainline dev build
