### ISSUE TITLE
[BUG] Chat disabled

### ISSUE THREAD

**Issue by victorkayne2nd** [PojavLauncherTeam/PojavLauncher#4392]
### Describe the bug

By trying to send some message in the chat, the message doesn't send and displays "Cannot send chat message" (1.8.9) or the chat doesn't open and displays the same message (1.16.5)

### The log file and images/videos

The chat displays "cannot send chat messages"

### Steps To Reproduce

```markdown
1. Start PojavLauncher and add a local account.
2. Start the game (1.8.x or newer) and try to send a message on the chat or open the chat.
```

### Expected Behavior

I expect to be able to send messages in the chat instead of commands-only.

### Platform

```markdown
- Device model: Redmi 9 Power
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: latest 'dahlia' Google Play release
```

### Anything else?

The chat is set to send anything on the chat.
Multiplayer is disabled on my 1.16.5 test. The behavior is expected if I could use Microsoft Account and disable the multiplayer.

**Comment by GaucovyAero** [comment]
buy minecraft
