### ISSUE TITLE
[BUG] Forge 1.8.9 no sound

### ISSUE THREAD

**Issue by mesflit** [PojavLauncherTeam/PojavLauncher#4395]
### Describe the bug

no sound 1.8.9 forge

### The log file and images/videos

no sound

### Steps To Reproduce

```markdown
no sound
```

### Expected Behavior

no sound

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 11
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
downgrade to the latest play store version or don't use forge (which is not a viable solution)

**Comment by NOfelll** [comment]
e,no sound

**Comment by GaucovyAero** [comment]
should be fixed in the latest actions version
