### ISSUE TITLE
2d items in rl craft and glitchy mouse

### ISSUE THREAD

**Issue by ArkiBoyZ** [PojavLauncherTeam/PojavLauncher#4397]
### Describe the bug

The item i hold look like 2d version not like the real pc version and 
the mouse is little glitchy it move little left or right automatically after i move it 
both glitches are in the below video clip

### The log file and images/videos

![IMG_20230722_22055438](https://github.com/PojavLauncherTeam/PojavLauncher/assets/105589980/e1ca6c8d-dcd8-47bb-9c34-ac6827efb380)
![IMG_20230722_22053344](https://github.com/PojavLauncherTeam/PojavLauncher/assets/105589980/144d8d29-57b5-49fb-a9bb-92da13160574)

### Steps To Reproduce

```markdown
Just download and start playing rl craft it will all be visible to you
```

### Expected Behavior

The mouse should stop after i stop moving it and the item should look same as the pc rl craft version 

### Platform

```markdown
- Device model: RMX3241
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

I play completely regular rl craft in latest version downloaded from curse forge neither i added any mods nor i added any resource packs 
And the mouse glitch also happens in regular vanilla minecraft and it is not permanent it happens sometimes and fixes with a restart but restarting rl craft is pretty annoying as it takes lots of time to restart as it is heavly modded 
And for some reason i was unable to upload the video clip it was 72 mb

**Comment by Bel69420** [comment]
This is Mali GPU bug

**Comment by Bel69420** [comment]
where your item will become 2D

**Comment by Bel69420** [comment]
This only happen on 1.12.2

**Comment by Bel69420** [comment]
Adreno fine

**Comment by ArkiBoyZ** [comment]
Is there any way to fix ?

**Comment by Bel69420** [comment]
sadly no

**Comment by Bel69420** [comment]
You have no choice to play along with this bug

**Comment by ArkiBoyZ** [comment]
Can the developer fix this ?
And virglrenderer is fine it doesn't give 2d graphic but it gives very less fps like 20-35
But with holy renderer i get 40-55

**Comment by Bel69420** [comment]
I think they can't do anything about it

**Comment by Bel69420** [comment]
Mali fault

**Comment by Bel69420** [comment]
But I found a good renderer for 1.12.2 called Zink.

**Comment by Bel69420** [comment]
![2023-07-30_13 07 47](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89313901/325e60fe-76e8-4aa7-b868-14d5549c2450)

**Comment by ArkiBoyZ** [comment]
The game is starting but the game is in black and white colour everything is black and white even menu and the fps is too low only 23-35 on 2 chunks 
The holy give almost 80-90 fps but 2d graphic
Think i dont have any other choice :(

**Comment by Bel69420** [comment]
> The game is starting but the game is in black and white colour everything is black and white even menu and the fps is too low only 23-35 on 2 chunks The holy give almost 80-90 fps but 2d graphic Think i dont have any other choice :(

Don't give up, there's a new renderer that can fix the 2D bug

**Comment by Bel69420** [comment]
But Idk if your phone gpu is compatible with the renderer.

**Comment by Bel69420** [comment]
> But Idk if your phone gpu is compatible with the renderer or not.

**Comment by ArkiBoyZ** [comment]
Atleast i will try if it

**Comment by Bel69420** [comment]
Not mainline though

**Comment by ArkiBoyZ** [comment]
Maybe i wil try
