### ISSUE TITLE
I AM IN POJAV LAUNCHER DISCORD

### ISSUE THREAD

**Issue by Sahilkumar568** [PojavLauncherTeam/PojavLauncher#4398]
### Is this request related to a bug?

Can You Unban me On Pojav launcher Discord mai Discord Name PokeAsh

**Comment by WesleyVanNeck** [comment]
keep on dreaming i dont think they will

**Comment by Bel69420** [comment]
you did a big mistake last time

**Comment by Sahilkumar568** [comment]
Bro I need 1.20 optimzed mod and fabric so I need Discord server

**Comment by Sahilkumar568** [comment]
Can you give me

**Comment by Bel69420** [comment]
still no :/

**Comment by GaucovyAero** [comment]
no
