### ISSUE TITLE
Mouse not fixed

### ISSUE THREAD

**Issue by Dennisken2320** [PojavLauncherTeam/PojavLauncher#44]
The mouse or tap not fixed
Same tap or click But Here not fixed ex. 

You tapping hold a blocks item into the slot not work or all items you tap hold it into the slot not working cant place

i just tried keyboard pressing number ex.

You point the items and you press the keyboard number 1 ~ 10 worked placed

Please Owner Fix This Thing

Also change name apk is Minecraft Java 😅 and icon is grass block

**Comment by khanhduytran0** [comment]
Tap only, not hold
Hold means destroy block

**Comment by Dennisken2320** [comment]
Sorry? 😅😅

If you tap items into slot cant placed

Lol hold means destroy block?? Ok
Fix opengl ok

**Comment by khanhduytran0** [comment]
Yes yes.
Tap one mean RIGHT MOUSE, or place block
Hold mean LEFT MOUSE, or destroy block

**Comment by Dennisken2320** [comment]
Uhhh that not i mean just i mean if you choose pick a items into the slot
cant replace?

**Comment by khanhduytran0** [comment]
I can't understand what you said :/

**Comment by Dennisken2320** [comment]
This is will you can understand

Here if you pick the items what you want and you place on slot items and
the items didn't cant placed now is better ah?

**Comment by khanhduytran0** [comment]
Can you make an example video?

**Comment by khanhduytran0** [comment]
Pick an item from the ground, then that item can't be placed?

**Comment by Dennisken2320** [comment]
Ok???

**Comment by Dennisken2320** [comment]
I cant place video ;-;

**Comment by khanhduytran0** [comment]
Place on YouTube

**Comment by Dennisken2320** [comment]
Come on

**Comment by Dennisken2320** [comment]
https://youtu.be/CZuPpaj8zxc here i just unlisted but i gave you my link ok not picking in a ground the problem is the items you just hold into the inventory cant place

**Comment by khanhduytran0** [comment]
Disable touchscreen mode
Goto Minecraft settings -> Controls -> Touchscreen OFF!

**Comment by khanhduytran0** [comment]
If still not working try double/triple click then drag to hotbar

**Comment by khanhduytran0** [comment]
You describe a way that I can't understand, you may not pure-English?

**Comment by Dennisken2320** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh {93716204162x} lol
just kidding hmm ok thx
