### ISSUE TITLE
[F-Req] < add a button to disable and enable gyroscope while in game>

### ISSUE THREAD

**Issue by ShiftJM** [PojavLauncherTeam/PojavLauncher#4400]
### Is this request related to a bug?

as the title says.

**Comment by ShiftJM** [comment]
or is there any way to toggle the gyroscope while in the game?

**Comment by GaucovyAero** [comment]
nope, why would you want to do that?

**Comment by GaucovyAero** [comment]
if you want to reposition your phone, just use your finger to move the crosshair

**Comment by Bluberry-Kat** [comment]
Any chance I could get you to reconsider this decision? Ratcheting is a pretty important feature for Gyro control. For example, using the default control profile for Portal on the steam deck, gyro doesn't activate unless your finger is touching the right stick.  
While yes, you can just use your finger to move the crosshair, having to reverse any movements you recently made is not what I would call intuitive, compared to just halting input. Imagine trying to use a mouse you're not allowed to lift off your desk.

**Comment by goldfish911** [comment]
Was about to post another issue about this, thirding the request, physical and virtual UI bindings already have a 'toggleable' switch, all that's missing are like custom keycodes for SPECIAL_GYRO_ON and SPECIAL_GYRO_OFF for users to configure accordingly. 

 And absent a key binding, the gyro can remain always on, as is current gyro behavior.
