### ISSUE TITLE
[BUG] <World does not render after moving in early alphas>

### ISSUE THREAD

**Issue by LegendDD44** [PojavLauncherTeam/PojavLauncher#4401]
### Describe the bug

After the world load it will disappear if you move or look around.

### The log file and images/videos

None

### Steps To Reproduce

```markdown
Try to move in alpha rd 132328
```

### Expected Behavior

I want to see the ground and steves

### Platform

```markdown
- Device model: BE2025
- CPU architecture: kryo 570
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

None

**Comment by Mathias-Boulay** [comment]
perhaps showcasing a video might help, and precising the java version. Also a log file wouldn't kill

**Comment by GaucovyAero** [comment]
i don't consider this to be an issue, just move your crosshair a bit

https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/66c9e1a3-fa21-4456-b356-76e6b74701af
