### ISSUE TITLE
Error occurred during initialization of VM java/lang/NoClassDefFoundError: java/lang/Object

### ISSUE THREAD

**Issue by AmarKherala** [PojavLauncherTeam/PojavLauncher#4402]
### Describe the bug

this is the crash code

Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

### The log file and images/videos

Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

### Steps To Reproduce

```markdown
1-Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
```

### Expected Behavior

Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

### Platform

```markdown
- Device model: y7 prime 2019
- CPU architecture: idk
- Android version: 8
- PojavLauncher version: latest plau store
```

### Anything else?

Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

**Comment by GaucovyAero** [comment]
reinstall pojav

**Comment by AmarKherala** [comment]
> reinstall pojav

didnt work
