### ISSUE TITLE
NO MUSIC On latest pojavlauncher 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4407]
### Describe the bug

When I try the latest update pojavlauncher on GitHub don't music working 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Use pojavlauncher latest GitHub 
2. Start pojavlauncher
3. No music or clicking sound
```

### Expected Behavior

Have sound

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest pojavlauncher from github
```

### Anything else?

Plss fix only latest no sound

**Comment by GaucovyAero** [comment]
downgrade to the play store version (or don't use forge, which is not a viable solution)

**Comment by GaucovyAero** [comment]
duplicate

**Comment by Konraiser** [comment]
Just run Minecraft several times until assets download fully. I did that and I have music on latest version of launcher with forge.
