### ISSUE TITLE
[F-Req] Nothirium mod support

### ISSUE THREAD

**Issue by Danilo648648** [PojavLauncherTeam/PojavLauncher#4409]
### Describe the request.

It crashes when Nothirium mod and Renderlib installed
Nothirium is performance mod for 1.12.2 that changes rendering similar in way sodium did
https://www.curseforge.com/minecraft/mc-mods/nothirium

### Anything else?

I use feature request instead of issue because i think it suits it better.
When game lauched with Nothirium and Renderlib(dependency) it just closes instantly

**Comment by Bel69420** [comment]
Nothrium doesn't work with Pojav Launcher, use optifine instead.
