### ISSUE TITLE
[BUG] Keys "Stick"

### ISSUE THREAD

**Issue by RandomGitHubber302** [PojavLauncherTeam/PojavLauncher#4410]
### Describe the bug

You could be playing minecraft, and randomly a key/click would keep being "pressed" even when you let go off of the key. If you were moving forward by pressing w, and let go, you would keep going forward. If you pressed right click, it would sometimes keep placing the blocks. Sometimes it's the opposite. When you press a key, it won't register.

### The log file and images/videos

I can't submit a video, it only happens occasionally. It's kinda rare for how much you press the buttons, so I can't just make it happen.

### Steps To Reproduce

```markdown
1. Open a world or join a server
2. Press a key
3. There will be a chance that the button action will keep happening.

1. Join a Bedwars game
2. Start fighting somebody
3. Walk off the edge because you tapped D to strafe.
```

### Expected Behavior

It shouldn't happen.

### Platform

```markdown
- Device model: Chromebook ASUS
- CPU architecture: Idk
- Android version: Chrome OS 
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
duplicate
