### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by FUNGAMERZ125** [PojavLauncherTeam/PojavLauncher#4412]
### Describe the request.

![Screenshot_2023-07-27-09-19-23-385_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140680659/96f03ae6-f616-4ec7-89ee-d19603ae5a5a)

**Comment by GaucovyAero** [comment]
buy minecraft
