### ISSUE TITLE
Add compatability for patcher mod 

### ISSUE THREAD

**Issue by shexhan** [PojavLauncherTeam/PojavLauncher#4413]
### Is this request related to a bug?

Version:1.8.9
Android:12
Device:samsung tab A7

### Describe the request.

Patcher mod crasher when using 1.8.9 forge with optifine. Add compatibility to use patcher mod if this is possible.. it will be really helpfull

**Comment by xiezxc2709438619** [comment]
114514

**Comment by pptall** [comment]
You need to use an older version ask for it in the discord

**Comment by GaucovyAero** [comment]
skyblock mods generally do not work on pojav, i recommend either not using the mods or not playing skyblock for the optimal experience
