### ISSUE TITLE
[BUG] 1.19.2 crash for no apparent reason 

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4416]
### Describe the bug

application existed with code one

### The log file and images/videos

[crash-2023-07-28_14.47.34-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12194393/crash-2023-07-28_14.47.34-client.txt)

### Steps To Reproduce

```markdown
1 start the game
2 game crashed
```

### Expected Behavior

i expected it to work

### Platform

```markdown
- Device model: huawei y6s 
- CPU architecture: MTK MT6765 
- Android version: 9 
- PojavLauncher version: latest version from app store
```

### Anything else?

this happens with forge and optifine versions

**Comment by GaucovyAero** [comment]
no idea, try reinstalling forge and dont play any servers that require custom resource packs
