### ISSUE TITLE
[F-Req] <make Java17 or another can install .jar>

### ISSUE THREAD

**Issue by mine0605** [PojavLauncherTeam/PojavLauncher#4417]
### Is this request related to a bug?

No

### Describe the request.

Not only Java 8 can install the jar files

### Anything else?

Because Sometimes there is no Java 8 after accidentally deleting data，and Jre8 is hard to find

**Comment by ghost** [comment]
You can already do this. Just make sure you have java 8 in your runtimes and have java 17 as the default.

**Comment by mine0605** [comment]
Oh,thanks
