### ISSUE TITLE
[BUG] "Unable to initialize policy entry: Illegal character" at Minecraft start

### ISSUE THREAD

**Issue by marshallovski** [PojavLauncherTeam/PojavLauncher#4420]
### Describe the bug

When I trying to start Minecraft 1.12.2 (.jar file from PC), these error happens:
Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/*

Exit code: 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12207612/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select "client-1.12.2.jar" file
3. Press "Play" in PojavLauncher
```

### Expected Behavior

I expected the game to launch

### Platform

```markdown
- Device model: OnePlus 8 Pro 8/128 GiB
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Latest Release from Google Play `(dahlia-740-623f7dd33-v3_openjdk)`
```

### Anything else?

I'm trying to run minecraft .jar from the PC version of the game, but PojavLauncher says "Error: Could not find or load main class net.minecraft.client.Main". Why?

**Comment by GaucovyAero** [comment]
you always need to have a launcher to run minecraft, by clicking "install .jar", you are basically running it without the launcher, please select 1.12.2 in your profile version selection
