### ISSUE TITLE
[BUG] Music from Minecraft keep playing even if it closed

### ISSUE THREAD

**Issue by marshallovski** [PojavLauncherTeam/PojavLauncher#4421]
### Describe the bug

See the subject. When I minimizing the Minecraft and switching to another app, the music keeps to playing.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/68496774/02b3c8a1-1cde-41fc-a02f-eda062a2a41c

### Steps To Reproduce

```markdown
1. Start PojaveLauncher
2. Select 1.12.2 Minecraft version
3. Start Minecraft
4. Minimize the Minecraft window
5. Hear the Minecraft music
```

### Expected Behavior

Minecraft's music to stop

### Platform

```markdown
- Device model: OnePlus 8 Pro 8/128
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: dahlia-20230724-403c962-v3_openjdk
```

**Comment by artdeell** [comment]
That's because Minecraft controls the music, not us. If you minimize Minecraft on PC, it will be the same
