### ISSUE TITLE
[F-Req] Game chat box moves up

### ISSUE THREAD

**Issue by Ktyf37** [PojavLauncherTeam/PojavLauncher#4423]
### Is this request related to a bug?

Yes, when typing on the soft keyboard, it obscures the contents of the chat box

### Describe the request.

Make the game chat box move up, like Minecraft Bedrock Edition
![e5aYlzLlBEsOWFued5EBXA](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135925971/5eeaf158-c6ef-48fa-9377-317a7d7d2658)

### Anything else?

None

**Comment by GaucovyAero** [comment]
that is impossible to do, as java minecraft does not have any virtual keyboard handling

**Comment by Ktyf37** [comment]
> that is impossible to do, as java minecraft does not have any virtual keyboard handling

But https://github.com/FCL-Team/FoldCraftLauncher did
![Screenshot_20230823_102420_com bilibili app in](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135925971/de02cde9-ff15-4e34-9852-626e89477e4f)
