### ISSUE TITLE
[BUG] <Signpicture mod>

### ISSUE THREAD

**Issue by Yeung1234** [PojavLauncherTeam/PojavLauncher#4424]
### Describe the bug

All the pictures is wrong, but computer minecraft java launcher is no problem

### The log file and images/videos

No

### Steps To Reproduce

```markdown
No, please pojavlauncher faster to fix this bug
```

### Expected Behavior

No

### Platform

```markdown
- Device model: Samsung A53
- CPU architecture: 
- Android version: 13
- PojavLauncher version: newest version
```

**Comment by artdeell** [comment]
No log
No screenshot

**Comment by Bel69420** [comment]
> ### Describe the bug
> All the pictures is wrong, but computer minecraft java launcher is no problem
> 
> ### The log file and images/videos
> No
> 
> ### Steps To Reproduce
> ```
> No, please pojavlauncher faster to fix this bug
> ```
> 
> ### Expected Behavior
> No
> 
> ### Platform
> ```
> - Device model: Samsung A53
> - CPU architecture: 
> - Android version: 13
> - PojavLauncher version: newest version
> ```
> 
> ### Anything else?
> _No response_

Pls show us a screenshot and the latestlog
