### ISSUE TITLE
[BUG] erro ao tentar instalar um arquivo .jar

### ISSUE THREAD

**Issue by GuilhermeDunkly** [PojavLauncherTeam/PojavLauncher#4426]
### Describe the bug

Bem, eu sou novo aqui no github e não sei muito bem onde eu deveria buscar ajuda(ou relatar um bug), mas aqui estou eu, estou tendo um problema ao tentar instalar um arquivo .jar no povejavlauncher, pra ser mais específico eu estava tentando instalar o mod do pixelmon.
Quando tento instalar o arquivo .jar do pixelmon o app sai abruptamente, e depois aparece essa imagen:

![Screenshot_20230731-154200_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/118634858/56c843c6-9b1a-4e1f-81d1-b3ec80161bb0)

Eu normalmente fui verificar o arquivo latestlog.txt
E isso é oque tinha nele:

Info: Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/Pixelmon-1.12.2-8.4.3-universal.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2257
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~i9CuItB62syd28v-cXA0kQ==/net.kdt.pojavlaunch-g1LhogsBQKyI_SST-qimyg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~i9CuItB62syd28v-cXA0kQ==/net.kdt.pojavlaunch-g1LhogsBQKyI_SST-qimyg==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Exception on logging thread:
java.io.IOException: Cannot run program "logcat": error=14, Bad address
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
	at net.kdt.pojavlaunch.utils.JREUtils$1.run(JREUtils.java:131)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: error=14, Bad address
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 2 more

OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Policy policy.url.2=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy (No such file or directory)

Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/*
no main manifest attribute, in /data/user/0/net.kdt.pojavlaunch/cache/Pixelmon-1.12.2-8.4.3-universal.jar

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x6fa65f6cf8)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x6fbd031a88)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x6fbd031a88)
.
Bom, é isso, eu não consigo instalar um arquivo .jar, e realmente não sei oque fazer.
#3823 #
/

### The log file and images/videos

Info: Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/Pixelmon-1.12.2-8.4.3-universal.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2257
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~i9CuItB62syd28v-cXA0kQ==/net.kdt.pojavlaunch-g1LhogsBQKyI_SST-qimyg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~i9CuItB62syd28v-cXA0kQ==/net.kdt.pojavlaunch-g1LhogsBQKyI_SST-qimyg==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Exception on logging thread:
java.io.IOException: Cannot run program "logcat": error=14, Bad address
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
	at net.kdt.pojavlaunch.utils.JREUtils$1.run(JREUtils.java:131)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: error=14, Bad address
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 2 more

OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Policy policy.url.2=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy (No such file or directory)

Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/*
no main manifest attribute, in /data/user/0/net.kdt.pojavlaunch/cache/Pixelmon-1.12.2-8.4.3-universal.jar

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x6fa65f6cf8)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x6fbd031a88)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x6fbd031a88)

### Steps To Reproduce

```markdown
1.iniciei o povejavlauncher 
2.fui na opção instalar .jar
E obtive o erro
```

### Expected Behavior

Eu esperava que o mod do pixelmon(.jar) fosse instalado normalmente 

### Platform

```markdown
- Device model: samsung m31
- CPU architecture:aarch64
- Android version: 12
- PojavLauncher version: ultima versão
```

### Anything else?

Eu realmente não sei como deveria relatar esse bug, perdão se tiver algo errado no que eu escrevi

**Comment by yBrunoDev** [comment]
recomendo traduzir o texto. (text in portuguese he said: error on .jar installer)
mod do pixelmon você bota na pasta de mods e não instalando .jar baixe o forge

**Comment by GuilhermeDunkly** [comment]
Pasta de mods?
