### ISSUE TITLE
[BUG] forge freezing

### ISSUE THREAD

**Issue by ditt0132** [PojavLauncherTeam/PojavLauncher#4427]
### Describe the bug

after launching forge, it freezing

### The log file and images/videos

![Screenshot_20230801_182623_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104212145/86c1a952-32e6-481e-82c0-2546d19f4a64)
after launch.

I ran the game but there are no logs. logs/telemetry had YYYY-MM-DD-1, but the extension was just .json, not .json.gz.
I was looking for the latest log, but I couldn't find it anywhere.

i think the game freezed while launching game.

### Steps To Reproduce

```markdown
1. install forge-47.1.1
2. launch
3. game will be freeze
```

### Expected Behavior

i except to game launch

### Platform

```markdown
- Device model: 
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: dahlia-194-33ec18410-v3_openjdk
```

### Anything else?

i tested on other directory. but it wont create anything.(ex. log, mods folder, options.txt, config, assets)
and it wont load controll gui. just black screen

**Comment by ditt0132** [comment]
Update: I continued testing, but no logs were generated anymore. 
Update 2: The mod is irrelevant. I tried running it in an environment without mods and it doesn't work 
i think this is launcher problen, not forge

**Comment by ditt0132** [comment]
and all versions gone too.(maybe)

**Comment by GaucovyAero** [comment]
your pojav version is very outdated, update to the play store version
