### ISSUE TITLE
[GUESTION] Can't play on servers even though I've technically bought minecraft

### ISSUE THREAD

**Issue by Kassuapina** [PojavLauncherTeam/PojavLauncher#4428]
### Describe the request.

So, is there any way that i can play on servers, but i have the game on ps4 and on my phone so wouldn't that technically mean i have bought the game and thus should be able to have an account and not an offline one. What i mean is am i able to log into mc java (pojav launcher) with my microsoft because i have the same account connected to my pocket edition and on my ps4. This probably isn't possible but if it is, let me know!

**Comment by Mathias-Boulay** [comment]
Bedrock and java editions are separate versions. Head over to their official website if you want to buy minecraft java
