### ISSUE TITLE
Pojav screen

### ISSUE THREAD

**Issue by Mynameispoop** [PojavLauncherTeam/PojavLauncher#443]
Pls help idk how to make my screen not light like its more bright pls help 
![Screenshot_20201202-093609](https://user-images.githubusercontent.com/72054752/100817710-887a2b00-3483-11eb-9b6a-bf5773fd1302.jpg)

![Screenshot_20201201-110346](https://user-images.githubusercontent.com/72054752/100817698-83b57700-3483-11eb-9bde-d6b34842209f.jpg)

**Comment by Mynameispoop** [comment]
Oh the mojang studios screen its more light and the other picture is not when i played it 2 days ago its not brighter than the other one pls help i cant play properly :(

**Comment by yanluol** [comment]
What is your device and the runtime you use?

**Comment by DinoPL9** [comment]
How you make custom keyboard?

**Comment by Mynameispoop** [comment]
> What is your device and the runtime you use?

Huawei Y7 Pro 2019
Jre9 aarch64

**Comment by WesleyVanNeck** [comment]
use jre 8

**Comment by Mynameispoop** [comment]
> use jre 8

Will it be laggy

**Comment by khanhduytran0** [comment]
**JRE9 is slower than JRE8**

So, JRE8 should not be lag.

**Comment by Mynameispoop** [comment]
Ok but i cant replace it i uninstalled the runtime and restart it and launch it and it download the runtime automatically and its jre9 :(

**Comment by khanhduytran0** [comment]
The auto install one is jre8

**Comment by Mynameispoop** [comment]
Oh ok

**Comment by Mynameispoop** [comment]
Its didnt work

**Comment by Mynameispoop** [comment]
But it remove it self i downloaded the one with no runtime and installed jre8 there and i said cant copy and i forgot what it said and a few days i installed jre9 and it said the same thing and after that its still that and a few days it got rid of it

**Comment by ghost** [comment]
How to install jre8 instead of jre9

**Comment by khanhduytran0** [comment]
What's your device architecture?

**Comment by Mynameispoop** [comment]
Who,me?

**Comment by ghost** [comment]
> How you make custom keyboard?

Go to settings of the launcher and press the custom controls and slide from right to left of ur screen and custom options must appear.

**Comment by khanhduytran0** [comment]
> Who,me? 

You already replied before, I'm asking @ChargedHat42838

**Comment by khanhduytran0** [comment]
> But it remove it self i downloaded the one with no runtime and installed jre8 there and i said cant copy and i forgot what it said and a few days i installed jre9 and it said the same thing and after that its still that and a few days it got rid of it 

So?

**Comment by ghost** [comment]
> What's your device architecture?

ARMv8

**Comment by ghost** [comment]
I guess.

**Comment by khanhduytran0** [comment]
JRE8 is included since v3.3
Get https://github.com/PojavLauncherTeam/PojavLauncher/suites/1640032238/artifacts/30348476

**Comment by ghost** [comment]
> JRE8 is included since v3.3
> Get https://github.com/PojavLauncherTeam/PojavLauncher/suites/1640032238/artifacts/30348476

Thanks
🙃😁😁😁😁

**Comment by ghost** [comment]
> JRE8 is included since v3.3
> Get https://github.com/PojavLauncherTeam/PojavLauncher/suites/1640032238/artifacts/30348476

But you get automatically with the large app debug.apk or with the no runtime

**Comment by khanhduytran0** [comment]
If you already have JRE8, get noruntime instead.

**Comment by ghost** [comment]
How to get the jre8

**Comment by ghost** [comment]
> If you already have JRE8, get noruntime instead.

How

**Comment by khanhduytran0** [comment]
> How to get the jre8

How to get the 70mb app-debug contains JRE8.

**Comment by khanhduytran0** [comment]
@Mynameispoop maybe try latest build..

**Comment by Vijay96t1945** [comment]
Pojav launcher multiplayer lan world please

**Comment by khanhduytran0** [comment]
@Vijay96t1945 the client need to be logged in as premium account in order to join LAN.

**Comment by Mathias-Boulay** [comment]
The bright screen issue is fixed on the google play build, closing issue.
