### ISSUE TITLE
[BUG] an offline/local account can download minecraft for free, which contradicts your website pojavlauncherteam

### ISSUE THREAD

**Issue by brxxlstxrs** [PojavLauncherTeam/PojavLauncher#4431]
### Describe the bug

minecraft is downloaded just like that, for free it is not clear from where.
then can fully play it for free.
https://pojavlauncherteam.github.io/LOCAL-MODE.html - something completely different is described and expected here.

### The log file and images/videos

ㅤ

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Navigate to **Add account**
3. Choose the **LOCAL ACCOUNT**
3. Enter username (it can be some number of charactersnot, not email)
4. Click **LOGIN** button
5. Choose (create new) profile at the bottom
6. Click on the pencil (edit)
7. Choose version of Minecraft 
8. Click **SAVE**
9. Click **PLAY**
```

### Expected Behavior

expected that the download would be only if log in to microsoft account with the purchased Minecraft

### Platform

```markdown
- Android
- PojavLauncher version: dahlia-20230802-9f7a580-v3_openjdk
```

**Comment by crystall1nedev** [comment]
Yep. This wasn't intended, and I have said in private chats to the Android developers that this needs to be changed as we have already come across legal issues with Microsoft for this exact issue.

I don't know how to develop for the Android platform (as my area is mostly iOS), so I don't know how to reimplement local mode. But I'll keep bugging the others about it.

**Comment by D9074** [comment]
Park yeo

**Comment by alexanderpowerplays** [comment]
local accounts can only play singleplayer

**Comment by Cartrigger** [comment]
local accounts can play multiplayer if the server is set to offline mode, (online-mode false)

**Comment by crystall1nedev** [comment]
This issue has been resolved with the merging of #5560.

**Comment by Erik0958** [comment]
You cant ad for the pojavlauncher to change your skin?

**Comment by Erik0958** [comment]
How to change your skin?

**Comment by kiokori-git** [comment]
> You cant ad for the pojavlauncher to change your skin?

that would result in the need of pojavlauncher accessing your microsoft account entirely, you wouldn't want that do you?
