### ISSUE TITLE
The new launcher is not compatible with dynamicsurround mod.

### ISSUE THREAD

**Issue by gumen2258** [PojavLauncherTeam/PojavLauncher#4434]
### Describe the bug

Once the new starter is added with dynamic surround,There will be no sound.And many large integration packages will use this mod.

### The log file and images/videos

At least after updating the automatic installation module loader, this bug came out.

### Steps To Reproduce

```markdown
The image can't be expressed.
```

### Expected Behavior

Just fix this

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

no more

**Comment by GaucovyAero** [comment]
#1948
