### ISSUE TITLE
New modern warfare cubed mod crash 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4435]
### Describe the bug

When open inventory it's crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12246712/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Create world
3. Open inventory crash
```

### Expected Behavior

Work in pojavlauncher 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest github
```

### Anything else?

Hrlp

**Comment by GaucovyAero** [comment]
modern-warfare-cubed uses custom shaders that dont work on pojav
