### ISSUE TITLE
Error message 1

### ISSUE THREAD

**Issue by Slavik690** [PojavLauncherTeam/PojavLauncher#4437]
### Describe the bug

So i wanted to play the version 1.5.2
But it is crashing with the error code 1

The latestlog.txt

--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.5.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~C38eJtdsListtnUSJ7yXmA==/net.kdt.pojavlaunch-Rqu0mBRYstijn7PG42zu8Q==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~C38eJtdsListtnUSJ7yXmA==/net.kdt.pojavlaunch-Rqu0mBRYstijn7PG42zu8Q==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Exception in thread "main" 
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:24)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
Java Exit code: 1

### The log file and images/videos

![Screenshot_2023-08-03-19-39-29-63_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/137299026/ac5f3702-ea53-46a4-808f-83772882b72c)

### Steps To Reproduce

```markdown
1 start the app
2 select the version 1.5.2
3 run the game
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: CPH2219
- CPU architecture: Qualcomm® Snapdragon™ 662 Octa-core
- Android version: 13
- PojavLauncher version: the newest
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
use java 8

**Comment by GaucovyAero** [comment]
use java 17

**Comment by GaucovyAero** [comment]
oops, edited

**Comment by Slavik690** [comment]
> use java 17

Wdym

**Comment by Slavik690** [comment]
@GaucovyAero wdmy

**Comment by GaucovyAero** [comment]
> @GaucovyAero wdmy

use java 8, sorry xD, then it should work, if it gets stuck at the mojang screen, just delete options.txt in your .minecraft folder
