### ISSUE TITLE
Add (VgpuRender) 

### ISSUE THREAD

**Issue by LdragoLegendOP** [PojavLauncherTeam/PojavLauncher#4439]
### Describe the request.

Add vgpu render for fps boost and 32 bit support

### Anything else?

Add Vgpu Render

**Comment by hitechbaaz** [comment]
Yas

**Comment by Plasqyas** [comment]
I want vgpu as well but they probably will not add it back for a long time bro

**Comment by GaucovyAero** [comment]
use an older build of pojav if you need it, wont be added because 1.17+ doesnt work on it, it is slower than gl4es, and it makes the app size bigger
