### ISSUE TITLE
There is no sound when running dynamicsurround.[BUG] <Short description>

### ISSUE THREAD

**Issue by gumen2258** [PojavLauncherTeam/PojavLauncher#4442]
### Describe the bug

When loading the dynamic sound mod, there is no sound when running the game（There may be inaccuracies in artificial intelligence translation.）

### The log file and images/videos

Screenshots cannot be displayed.

### Steps To Reproduce

```markdown
1.Installation the dynamicsurround mod.
2.Start the game.
```

### Expected Behavior

I hope to fix the bug as soon as possible.

### Platform

```markdown
- Device model: Dynamicsurround
- CPU architecture: Kirin970
- Android version: HarmonyOS 2.0
- PojavLauncher version: v3_openjdk
```

### Anything else?

Nothing else.

**Comment by GaucovyAero** [comment]
#1948
