### ISSUE TITLE
[F-Req] Amazon App Store

### ISSUE THREAD

**Issue by mfulton26** [PojavLauncherTeam/PojavLauncher#4445]
### Is this request related to a bug?

No.

### Describe the request.

I want to be able to easily install this on my children's Kindle Fire tablets.

### Anything else?

Having it straight from the store will make it easy for Kindle Fire users too (which is Android but some differences, e.g., no Google Play Services).

**Comment by Mathias-Boulay** [comment]
huu, does amazon still make tablets that have enough compute power for this ?

**Comment by Mathias-Boulay** [comment]
Actually, what version of android is under those tablets ?

**Comment by artdeell** [comment]
> Actually, what version of android is under those tablets ?

We can still do it for all the WSA people

**Comment by artdeell** [comment]
@mfulton26 this will likely be done on the next tag release

**Comment by mfulton26** [comment]
> @mfulton26 this will likely be done on the next tag release

sweet, thank you!



> > Actually, what version of android is under those tablets ?
> 
> We can still do it for all the WSA people

what are "WSA people"? should I know that one? 😄

**Comment by mfulton26** [comment]
> huu, does amazon still make tablets that have enough compute power for this ?

I suspect a Fire HD 10 (Octa-core 2.0 GHz, 3 GB RAM) tablet would run this fine



> Actually, what version of android is under those tablets ?

forks of not the latest versions but ancient either ([Identifying Fire Tablet Devices | Fire Tablets](https://developer.amazon.com/docs/fire-tablets/ft-identifying-tablet-devices.html#fire-tablet-features) has some details)

**Comment by Mathias-Boulay** [comment]
So in theory we could support from Fire OS 5 then, at least API wise.
Power wise, it is a bit RAM limited, we'll see how it fares out I guess

**Comment by WesleyVanNeck** [comment]
> > @mfulton26 this will likely be done on the next tag release
> 
> sweet, thank you!
> 
> > > Actually, what version of android is under those tablets ?
> > 
> > 
> > We can still do it for all the WSA people
> 
> what are "WSA people"? should I know that one? 😄

am one of those wsa (windows subsystem android)  people

**Comment by GaucovyAero** [comment]
amazon denied this because it didnt work on their super old testing device

**Comment by Mathias-Boulay** [comment]
WSA is getting removed anyway, so there is not really use to distribute it there anyway.
