### ISSUE TITLE
Can you customize whether the length and width of each button set separately? Can custom buttons be modified in the game?

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#445]

**Comment by khanhduytran0** [comment]
> Can you customize whether the length and width of each button set separately?

Did you know the usage of the blue cursor when editing button??

> Can custom buttons be modified in the game?

It's not possible yet.

**Comment by T-CATHOME** [comment]
@khanhduytran0 The blue cursor has no effect

**Comment by khanhduytran0** [comment]
Could not drag?

**Comment by T-CATHOME** [comment]
@khanhduytran0 Unable to drag has no effect

**Comment by Mathias-Boulay** [comment]
Custom controls are now modifiable in game via the right tab, closing issue.
