### ISSUE TITLE
Holy render support for 32 bit 

### ISSUE THREAD

**Issue by LdragoLegendOP** [PojavLauncherTeam/PojavLauncher#4451]
### Is this request related to a bug?

Holy render error 1.17.1+ to 1.20.1 world black and inv hotbar not show Mobile name poco c3 Prosser mediaTek hello G35 32 but GPU PowerVR Android version 10 pls solve this problem

**Comment by Bel69420** [comment]
PowerVR moment

**Comment by Bel69420** [comment]
They're always buggy

**Comment by Bel69420** [comment]
Unlike Mali GPU

**Comment by GaucovyAero** [comment]
thats the powervr ge8320 driver issues, we cannot do anything about that

**Comment by LdragoLegendOP** [comment]
@GaucovyAero  holy render bug in PowerVR GPU and I think need pojavlauncher make angle render for all versions because angle work in 32 bit mobile performances are good and I think   pojavlauncher give better updates in angle in feature I think better than all render
