### ISSUE TITLE
[BUG] Curseforge Cli don't work

### ISSUE THREAD

**Issue by Adrian647PH** [PojavLauncherTeam/PojavLauncher#4453]
### Describe the bug

When you use The latest 1.5 Curseforge Cli(An Curseforge modpack Installer) and ise .jar installer.. it will just says "Installation Successful" and nothing else :(
Here's Curseforge Cli link github; https://github.com/PojavLauncherTeam/CurseForge-GUI

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/134882301/89d2e403-99d6-4df8-a7f5-0d296869496e

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Clicked .jar installer
3. Look for "Curseforge Cli 1.5.0"
4. Wait and nothing happens
```

### Expected Behavior

I expected that it will show an menu to intall modpacks

### Platform

```markdown
- Device model: Samsung A03s
- CPU architecture: I don't know what this is..
- Android version: 13
- PojavLauncher version: Latest.. it's long so i didn't put the version name
```

**Comment by GaucovyAero** [comment]
use getCFpack with termux instead, heres the tutorial (make sure to download termux from github, play store doesnt work)

download the getCF-main.zip here
turn on desktop mode and click code and then download the .zip
https://github.com/42LoCo42/getCFpack
get your cf api key here
https://console.curseforge.com/#/api-keys
```
termux-setup-storage
pkg update && pkg upgrade -y
pkg install golang
cp storage/downloads/getCFpack-main.zip ~/
pkg install unzip
unzip getCFpack-main.zip
cd getCFpack-main
pkg install nano
nano key
[paste your cf key]
ctrl+x
y and enter
go run . <modpackid>
ls
mv -r <modpack folder name> ~/storage/downloads
```

and then you will have your modpack in your downloads

**Comment by Adrian647PH** [comment]
> use getCFpack with termux instead, heres the tutorial (make sure to download termux from github, play store doesnt work)
> 
> download the getCF-main.zip here turn on desktop mode and click code and then download the .zip https://github.com/42LoCo42/getCFpack get your cf api key here https://console.curseforge.com/#/api-keys
> 
> ```
> termux-setup-storage
> pkg update && pkg upgrade -y
> pkg install golang
> cp storage/downloads/getCFpack-main.zip ~/
> pkg install unzip
> unzip getCFpack-main.zip
> cd getCFpack-main
> pkg install nano
> nano key
> [paste your cf key]
> ctrl+x
> y and enter
> go run . <modpackid>
> ls
> mv -r <modpack folder name> ~/storage/downloads
> ```
> 
> and then you will have your modpack in your downloads

Oh ok thanks
