### ISSUE TITLE
I want to add Microsoft account[BUG] <Short description>

### ISSUE THREAD

**Issue by Daquavis6969** [PojavLauncherTeam/PojavLauncher#4458]
### Describe the bug

I can add a Microsoft account 

### The log file and images/videos

Plss i want to add an account in pojavlauncher and im kid iwant some tutorials 

### Steps To Reproduce

```markdown
I start pojavlauncher i add local account
```

### Expected Behavior

I like the game is like pc

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
1.19.4
```

### Anything else?

I like pojavlauncher

**Comment by Daquavis6969** [comment]
I want a Microsoft account in pojavlauncher

**Comment by BlackberrieCake137** [comment]
its simple! theres a little option at the top to add an account, and you log in with your Microsoft account :) you'll have to remember your email and password though! so you might need do ask a parent to help guide you through it 
![Screenshot_20230809-025853](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121859020/c78dbaeb-a7f4-4a11-b537-0cc8779dae4c)

**Comment by Daquavis6969** [comment]
Bro
