### ISSUE TITLE
[BUG] Unable to delete files 

### ISSUE THREAD

**Issue by BlackberrieCake137** [PojavLauncherTeam/PojavLauncher#4459]
### Describe the bug

Im unable to delete any files in the app using Material Files (F-Droid), yet i can put files into it just fine. 

### The log file and images/videos

![Screenshot_20230809-025225](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121859020/13f7aba2-27a7-4582-ab0f-6dfcc6b6752d)

### Steps To Reproduce

```markdown
1. open Material Files 
2. click 'add storage'
3. select external
4. select pojav launcher from the menu
5. try and delete any file
```

### Expected Behavior

says the file doesnt exist

### Platform

```markdown
- Device model: Pixel 6
- CPU architecture: arm
- Android version: 13
- PojavLauncher version: dahlia
```

### Anything else?

N/A

**Comment by BlackberrieCake137** [comment]
forgot to add, the workaround i found so far was opening through androids native file manager in the resource pack settings. Deleting files worked perfectly fine there, though its a pretty inefficient method so far

**Comment by GaucovyAero** [comment]
use mixplorer, download for free from mixplorer.com via the google drive link (latest version as of today is v6.63.1)
