### ISSUE TITLE
[BUG] Can't play multiplayer since 9th August ("authentication servers under maintenance")

### ISSUE THREAD

**Issue by SnowyHears** [PojavLauncherTeam/PojavLauncher#4463]
### Describe the bug

EDIT: IT GOT FIXED YOU CAN CLOSE

The servers are pinged infinitely so I need to turn off wifi/4g then turn on again, it finally show the latency in ms and the network banner, but when I try to log in it says "logging in" for like 10 seconds and then says: 
"Failed to login: the authentication servers are currently down for maintenance."
![Screenshot_20230809_150820_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/141854047/b9c731dc-5437-423b-9360-f23dd3f2eb18)

### The log file and images/videos

![Uploading Screenshot_20230809_150820_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

### Steps To Reproduce

```markdown
1. Launch Pojav any version
2. Multiplayer: any normal server like hypixel
```

### Expected Behavior

I normally can login, just normal.

### Platform

```markdown
- Device model: Samsung galaxy a33 5g
- CPU architecture: aarch64 i suppose
- Android version: latest
- PojavLauncher version: latest
```

### Anything else?

I tried many reinstalls and other stuff and nothing worked, I hope you could fix this. Good luck have fun XD. EDIT: IT GOT FIXED

**Comment by offbeat-stuff** [comment]
works fine for me

**Comment by ghost** [comment]
this is because Mojang's auth servers were under maintenance.
