### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by 123rf** [PojavLauncherTeam/PojavLauncher#4464]
### Describe the bug

![Screenshot_2023-08-10-16-34-43-799_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/126236203/4f52f6ab-e363-43df-9667-9a0930f8b773)

### The log file and images/videos

![Screenshot_2023-08-10-16-34-43-799_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/126236203/6a865453-56a7-4dd3-ad2a-f8f9a73d65b0)

### Steps To Reproduce

```markdown
??
```

### Expected Behavior

![Screenshot_2023-08-10-16-34-43-799_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/126236203/d7e55b4f-5b19-4530-ac53-a8b94cce55c3)

### Platform

```markdown
- Device model: 小米12lite
- CPU architecture: 火龍778g
- Android version: 13
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

![Screenshot_2023-08-10-16-34-43-799_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/126236203/bb2f96bd-2b00-45d0-93b9-862344c9d191)

**Comment by 123rf** [comment]
能修復嗎画面颠倒了

**Comment by Bel69420** [comment]
Sorry for using English language but VirGL renderer is really buggy on Pojav

**Comment by Bel69420** [comment]
This is known issue

**Comment by 123rf** [comment]
Can it be fixed? The screen is upside down

**Comment by Bel69420** [comment]
I think it's permanent

**Comment by 123rf** [comment]
对呀

**Comment by Bel69420** [comment]
Because Pojav Dev doesn't made this renderer

**Comment by Bel69420** [comment]
If they made this renderer, they should know what's cause of this inverted screen bug

**Comment by 123rf** [comment]
建议整一个不会颠倒画面的渲染器

**Comment by Bel69420** [comment]
Your phone is Xiaomi12Lite?

**Comment by 123rf** [comment]
12Lite

**Comment by mchnjt** [comment]
![](https://media.tenor.com/wnlgIRj5QHIAAAAM/ximi-jumpscare.gif)

**Comment by 123rf** [comment]
对

**Comment by Bel69420** [comment]
Adreno642L moment

**Comment by Bel69420** [comment]
I'm not sure if this GPU support zink

**Comment by 123rf** [comment]
778G不支持

**Comment by Bel69420** [comment]
No, some of Adrenos doesn't support zink renderer that lead to crashing

**Comment by Bel69420** [comment]
Because of incompatibly of turnip driver

**Comment by 123rf** [comment]
![Uploading Screenshot_2023-08-10-16-57-23-438_com.android.settings.jpg…]()

**Comment by Bel69420** [comment]
Damn, there's no hope for your GPU to try the zink renderer

**Comment by Bel69420** [comment]
Thx to Adreno stock Vulkan Driver

**Comment by GaucovyAero** [comment]
dont use virgl, use gl4es
