### ISSUE TITLE
[BUG] Graphics rendering error

### ISSUE THREAD

**Issue by Ktyf37** [PojavLauncherTeam/PojavLauncher#4466]
### Describe the bug
After entering the game, the entire world, including buttons, are now displayed in black

![IMG_20230812_225011_edit_12082422094509](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135925971/f629bdd9-b8a8-4598-9ce0-cb5da2a6e495)
![IMG_20230812_224858](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135925971/a2bd176a-6a88-4e47-a632-2649fb728fd7)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12327593/latestlog.txt)

### Steps To Reproduce

```markdown
1、Enter the game
2、Generate a world
```

### Expected Behavior

The game screen should display normally

### Platform

```markdown
- Device model: HUAWEI P20
- CPU architecture: aarch64
- Android version:10 
- PojavLauncher version: dahlia-20230812-4a8c1e4-v3_openjdk (9939245)
```

### Anything else?

Perhaps a problem with LWJGL 3.3.1
https://github.com/PojavLauncherTeam/PojavLauncher/commit/4a8c1e4bc0f7b613db9eac416213a58822891684

**Comment by GaucovyAero** [comment]
no idea

**Comment by Bel69420** [comment]
Fucking New LWJGL bug moment

**Comment by Bel69420** [comment]
That the whole world turned into black

**Comment by GaucovyAero** [comment]
downgrade your pojav version for now, this will be fixed in a later update
