### ISSUE TITLE
Which buttons are the mouse wheel in the custom buttons

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#447]

**Comment by khanhduytran0** [comment]
Added in this build under name `SPECIAL_SCROLLUP` and `SPECIAL_SCROLLDOWN` https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/397662794

**Comment by T-CATHOME** [comment]
@khanhduytran0 Void

**Comment by khanhduytran0** [comment]
> @khanhduytran0 Void

Wdym ? @tttghkg

**Comment by T-CATHOME** [comment]
@khanhduytran0 Invalid mouse wheel

**Comment by khanhduytran0** [comment]
#543
