### ISSUE TITLE
Я запустил ядро сервера на projavlauncher! (Spigot 1.12.2)

### ISSUE THREAD

**Issue by vaniOK20** [PojavLauncherTeam/PojavLauncher#4471]
### Is this request related to a bug?

Projavlauncher может запускать не только установщики форджа или фабрик, но и любые jar программы. И я попытался запустить spigot 1.12.2 и он работает, но есть две проблемы 1: он сохраняет все файлы сервера в ".minecraft". 2: в консоль нельзя писать. (Вторую проблему можно решить подключением rcon.)

**Comment by artdeell** [comment]
Это вполне известный факт. Если очень хочется, то в пожаве можно и в дум
поиграть через установщик модов. Но зачем?

вс, 13 авг. 2023 г., 16:57 vaniOK20 ***@***.***>:
