### ISSUE TITLE
add screen resolution

### ISSUE THREAD

**Issue by McTutorialID23** [PojavLauncherTeam/PojavLauncher#4472]
### Is this request related to a bug?

I hope Pojavlauncher adds a screen resolution setting in the form of screen size, So there will be a choice of Minecraft screen resolution according to the cellphone screen resolution, such as size 1280x720, 1520x720, 480x360, 1920x1080, etc

So this feature will be similar to Minecraft Java, where Minecraft Java can customize the size of the screen resolution

(and if possible, for this feature, only customize the 16:9 resolution)

### Describe the request.

I hope Pojavlauncher adds a screen resolution setting in the form of screen size, So there will be a choice of Minecraft screen resolution according to the cellphone screen resolution, such as size 1280x720, 1520x720, 480x360, 1920x1080, etc

So this feature will be similar to Minecraft Java, where Minecraft Java can customize the size of the screen resolution

(and if possible, for this feature, only customize the 16:9 resolution)

### Anything else?

-

**Comment by GaucovyAero** [comment]
not going to be added, use the resolution scale setting
