### ISSUE TITLE
1.12.2 forge crash[BUG] <Short description>

### ISSUE THREAD

**Issue by MasterL5327L** [PojavLauncherTeam/PojavLauncher#4473]
### Describe the bug

Application exited with code 1

### The log file and images/videos

Info: Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/forge-1.12.2-14.23.5.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1520
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-9D22-wRwO0bbhyb_qxX7Fg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-9D22-wRwO0bbhyb_qxX7Fg==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
Exception on logging thread:
java.io.IOException: Cannot run program "logcat": error=14, Bad address
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
	at net.kdt.pojavlaunch.utils.JREUtils$1.run(JREUtils.java:129)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.IOException: error=14, Bad address
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 2 more

Error: Invalid or corrupt jarfile /data/user/0/net.kdt.pojavlaunch/cache/forge-1.12.2-14.23.5.jar
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7dababd1d0)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7dababd118)

### Steps To Reproduce

```markdown
I dtk=I don't know
```

### Expected Behavior

I was installing forge 1.12.2 and it the game exited with code 1

### Platform

```markdown
- Device model: redmi 8
- CPU architecture: Octa-core Max 2.01GHz
- Android version: 10 QKQ1.191014.001
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

Please
Fix
It!

**Comment by MasterL5327L** [comment]
Please
Fix
It!

**Comment by GaucovyAero** [comment]
your forge jar is corrupted
