### ISSUE TITLE
I want to download client

### ISSUE THREAD

**Issue by B00k546** [PojavLauncherTeam/PojavLauncher#4475]
### Is this request related to a bug?

_ I have an official minecraft account.
I have an official minecraft account . And i want to play in clients like lunat / badlion / etc .
Also patcher mod crash in pojav pls fix it 
I play in hypixel skyblock and its a good mode is mmo rpg 
But i cant download clients so improve my fps and i dont lose my experience 

### Describe the request.

We can download lunar client or badlion 
Fix patcher 1.8.9

### Anything else?

Ty .ur hard work give me some good times and i like the app and it will be better if u guys add what i say

**Comment by GaucovyAero** [comment]
skyblock mods generally dont work, use legacy fabric 1.8.9 + optifabric and axolotlclient

**Comment by B00k546** [comment]
What about Qol mods like neu and skytils . Skyhanni  i cant download them in fabric
