### ISSUE TITLE
Labymod crashe

### ISSUE THREAD

**Issue by B00k546** [PojavLauncherTeam/PojavLauncher#4476]
### Describe the bug

That the issue i install the debug app #4380. And it wont work and i get that log

### The log file and images/videos

[https://drive.google.com/file/d/18trRuQqswruaolIt1fBmumF-grk10ia_/view?usp=drivesdk](url)

### Steps To Reproduce

```markdown
Start pojav luncher
> install 1.8.9
Run it
> install labymod 4 
Run it
Get crashed before show anything
```

### Expected Behavior

Tbh idk

### Platform

```markdown
- Device model: redmi note 11 128gb
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: app debug #4380
```

### Anything else?

Pls i need solutions

**Comment by GaucovyAero** [comment]
labymod doesnt work

**Comment by B00k546** [comment]
> labymod doesnt work

But the title of app debug say fix labymod 4
