### ISSUE TITLE
Persistent Anti-Cheat Kicks for Players on Launcher - Integration with Floodgate Plugin Suggested

### ISSUE THREAD

**Issue by DimaSergeew** [PojavLauncherTeam/PojavLauncher#4477]
### Is this request related to a bug?

Hello,

I am encountering a recurring issue with players who are using my server through a specific launcher – they are consistently being kicked by the anti-cheat system. This issue is not present for players who are using the PC version of the game. I kindly request assistance in addressing this matter. One potential solution could be establishing integration with the Floodgate plugin. This integration could classify these launcher-based players as "Bedrock" users and exempt them from the anti-cheat verification. Alternatively, I am open to exploring other approaches that could mitigate the problem of false positive kicks triggered by the anti-cheat system on this launcher, affecting players using various anti-cheat clients.

Thank you for your attention to this issue. Your support in resolving this matter and enhancing the gameplay experience for all players would be greatly appreciated. If additional information is required or if there are further suggestions, please don't hesitate to reach out.

### Describe the request.

-

### Anything else?

-

**Comment by artdeell** [comment]
We need to know which anyicheat you use and which mods your players use to figure it out

**Comment by Mathias-Boulay** [comment]
Hello there, it would be great if we can pinpoint whats makes pojav different to resolve the issue.
If you can join our discord to discuss about it: https://discord.gg/aPD5kgqj

**Comment by DimaSergeew** [comment]
> We need to know which anyicheat you use and which mods your players use to figure it out

GrimAC

**Comment by Mathias-Boulay** [comment]
Given what it claims, it might as well detect a change in network latency and fuck over everyone using 4g

**Comment by Mathias-Boulay** [comment]
No need to close the issue now, we have yet to try anything about it :thinking:

**Comment by Mathias-Boulay** [comment]
@DimaSergeew What is your server ? 
Perhaps I could try to login and pin down what triggers the anti cheat with you :eyes:

**Comment by GaucovyAero** [comment]
fixed in this actions build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5917589480
