### ISSUE TITLE
Holy render textrue pack bug 

### ISSUE THREAD

**Issue by LdragoLegendOP** [PojavLauncherTeam/PojavLauncher#4480]
### Describe the bug

Holy render bug skin red and inv hotbar not working and fps and debug menu not working 
![Screenshot_2023-08-15-08-28-13-660_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/138747962/291e8f00-ec16-4709-800c-eba8e6c3b59d)
![Screenshot_2023-08-15-08-27-57-099_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/138747962/1cc53bd1-f81c-425b-a2dd-4cece9cb346e)

### The log file and images/videos

Fps drop

### Steps To Reproduce

```markdown
Pojav launcher full bug
```

### Expected Behavior

![Uploading Screenshot_2023-08-15-08-28-13-660_net.kdt.pojavlaunch.debug.jpg…]()
![Uploading Screenshot_2023-08-15-08-27-57-099_net.kdt.pojavlaunch.debug.jpg…]()

### Platform

```markdown
- Device model: poco C3 
- CPU architecture: 32 bit 
- Android version:10 
- PojavLauncher version:LOCAL-20230601
```

### Anything else?

Plszzzzzzzzz fix this problem and this problem with play store lasted version dehila version

**Comment by GaucovyAero** [comment]
updare to the latest github actions build, are you using any mods?

**Comment by GaucovyAero** [comment]
oh wait uh, you have the ge8320 gpu, which means you have confirmed driver issues, cant really do anything about this, you can try using optifine and enablng antialiasing to 2x fxaa in shaders settings (that will fix the hotbar not rendering) but other than that it wont really fix anything
