### ISSUE TITLE
[BUG] Game crashes when opening a new (mc) version

### ISSUE THREAD

**Issue by gdcolo7** [PojavLauncherTeam/PojavLauncher#4481]
### Describe the bug

"Application exited with code 1."

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12341816/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Use profile which is using 1.16.5 (this is **not** the only version that crashes, 1.18.2 and others that aren't installed yet I think)
3. Use the jvm args in the latestlog.txt
4. Press play.
5. Game Crashes
```

### Expected Behavior

Expected the game to launch and run

### Platform

```markdown
- Device model: RealMe C25s
- CPU architecture: 64 bit (if I understand this correctly)
- Android version: 11
- PojavLauncher version: Latest Google Play Release || dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

Runtime Manager: Internal 17

1020 Allocated RAM

There are 7 installed versions, 1.8.9, 1.16.5, 1.18.2, their Optifine versions, and 1.16.5 (current one)

**Comment by GaucovyAero** [comment]
dont use randon jvm args

**Comment by S4VAIBHAV** [comment]
1.16.5 needs Java 8, not internal 17
