### ISSUE TITLE
[BUG] <error 1 .jar file>

### ISSUE THREAD

**Issue by Gustavoalmir** [PojavLauncherTeam/PojavLauncher#4484]
### Describe the bug

every time I try to install a .jar file whether forge, fabric or others. gives error 1 and closes the app

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12354174/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojav
2. I click install .jar
3. I select the forge file (I tested it with others and it didn't work either)
4. it opens, loads and then gives the error "1" and closes the app
```

### Expected Behavior

install the .jar file

### Platform

```markdown
- Device model: Note 20 Ultra 5G
- CPU architecture: Octa-core (2x2.73 GHz Mongoose M5 & 2x2.50 GHz Cortex-A76 & 4x2.0 GHz Cortex-A55) - Global
Octa-core (1x3.0 GHz Kryo 585 & 3x2.42 GHz Cortex-A77 & 4x1.80 GHz Cortex-A55) - USA
- Android version: 13
- PojavLauncher version: dahilia-740-623f7dd33-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try reinstalling pojav (make sure to launch minecraft before running the installer)
you can also try rotating your phone into landscape mode and then running the installer
