### ISSUE TITLE
[F-Req] Native gamepad events

### ISSUE THREAD

**Issue by Criptobeta** [PojavLauncherTeam/PojavLauncher#4486]
### Is this request related to a bug?

Simulated Mouse and Keyboard inputs have priority over binded Gamepad inputs, Through one of the experimental builds which allows for controller binding I decided to test this out and It poses no use to me as even though Gamepad controls would be natively supported for the way I'm using them, They are just overwritten by mouse and keyboard.

### Describe the request.

A button somewhere in Pojav to disable Simulated Mouse and Keyboard input, Whether it in the menu or something that can be mapped into an onscreen button during gameplay.

**Comment by Mathias-Boulay** [comment]
There is no native gamepad input so far.

**Comment by GaucovyAero** [comment]
what app are you using to map the controller buttons to onscreen buttons? can you show a video of the inputs etting "overwritten" by pojav?

**Comment by Criptobeta** [comment]
A mistake on my part. I thought there was native gamepad input, And Since what i'm using in Pojav has Native Gamepad support I thought it was just prioritizing the Keyboard and Mouse inputs over the gamepad inputs.

**Comment by GaucovyAero** [comment]
what keyboard and mouse inputs though?

**Comment by Criptobeta** [comment]
Analog Sticks simulating WASD and Mouse. I'm not using any external apps other then Pojav and a Controller. So it's the default Pojav support.

**Comment by GaucovyAero** [comment]
oh okay, so would the switch to disable the keyboard + mouse emulation fix your issues?

**Comment by Criptobeta** [comment]
I would assume so. Since Pojav can take my inputs (with it simulating the mouse and keyboard by default) I think it'd be a safe guess to assume maybe It'd take the natural gamepad inputs(?).

**Comment by Mathias-Boulay** [comment]
We could still need to perform the mapping to transform them into "lwjgl native" gamepad events

**Comment by CloserPopcorn20** [comment]
So, how's the progress on this so far?

**Comment by ShulkerSakura** [comment]
I noticed that Controlify can recognized an unknown controller in the game,So is there any way to disable Pojav Controller Support to test if Controlify can use my controller?

**Comment by GaucovyAero** [comment]
this has been done, but inside the launcher instead
