### ISSUE TITLE
Zink not working 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4487]
### Describe the bug

When start the pojavlauncher crash

### The log file and images/videos

None

### Steps To Reproduce

```markdown
Start pojavlauncher crash
```

### Expected Behavior

Working 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest zink
```

### Anything else?

Plss update the working zink

**Comment by GaucovyAero** [comment]
it just doesnt work on some phones
