### ISSUE TITLE
[BUG] Cannot install forge 1.18.2 from jar file

### ISSUE THREAD

**Issue by TRB-Exe** [PojavLauncherTeam/PojavLauncher#4488]
### Describe the bug

At the end of installation I'm getting this error
![Screenshot_2023-08-17-11-41-03-162_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/72357112/4fdc1642-1d7f-4169-8fcf-49c991da1e45)
How I can resolve it?

### The log file and images/videos

![Screenshot_2023-08-17-11-41-03-162_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/72357112/4fdc1642-1d7f-4169-8fcf-49c991da1e45)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Select install .jar
3. Selecting forge install jar
4. Click install
5. Getting error
```

### Expected Behavior

Just getting error and installer is closing

### Platform

```markdown
- Device model: Xiaomi POCO X3 PRO
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use java 8
