### ISSUE TITLE
[BUG] Doesn't work on my 32-bit x86 Chromebook

### ISSUE THREAD

**Issue by SYZYGYGAMER** [PojavLauncherTeam/PojavLauncher#4489]
### Describe the bug

It keeps crashing after I use it on my chromebook
And I can't  find why

### The log file and images/videos

It crash 

### Steps To Reproduce

```markdown
Start pojav on chromebook (hp)
Crash
```

### Expected Behavior

It crash 

### Platform

```markdown
- Device model: hp chromebook 11 Ee 
- CPU architecture: hp
- Android version: newest
- PojavLauncher version: newest
```

**Comment by GaucovyAero** [comment]
send logs

**Comment by SYZYGYGAMER** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12370747/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.8.9 - VANILLA |
| Renderer | HOLY_GL4ES_114 |
| Architecture | X86_32 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by SYZYGYGAMER** [comment]
Sent log so pls reply

**Comment by GaucovyAero** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/5849582298
can you try this one? download `jre8-x86`, unzip it and install the .tar.xz file using pojavlauncher settings - java tweaks - runtime manager and set it as default, try then

**Comment by SYZYGYGAMER** [comment]
Ok

**Comment by SYZYGYGAMER** [comment]
i did it it failed and still crashed 
![Screenshot 2023-08-17 21 28 45](https://github.com/PojavLauncherTeam/PojavLauncher/assets/114241650/a5c49ab7-aa7e-406a-9cfa-5a516eb15183)
![Screenshot 2023-08-17 21 28 43](https://github.com/PojavLauncherTeam/PojavLauncher/assets/114241650/1aa80bf2-92f6-4e40-b45a-5a60f3278d72)

**Comment by SYZYGYGAMER** [comment]
Also log 
[Uploading latestlog (2).txt…]()

**Comment by SYZYGYGAMER** [comment]
Reply pls

**Comment by GaucovyAero** [comment]
> Also log Uploading latestlog (2).txt…

it didnt upload

**Comment by SYZYGYGAMER** [comment]
[latestlog (2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12374143/latestlog.2.txt)

**Comment by SYZYGYGAMER** [comment]
Sent

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.8.9 - VANILLA |
| Renderer | HOLY_GL4ES_114 |
| Architecture | X86_32 |
| Java runtime | EXTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| java.runtime.wrong.source |

**Comment by SYZYGYGAMER** [comment]
@GaucovyAero

**Comment by SYZYGYGAMER** [comment]
Pls fix

**Comment by GaucovyAero** [comment]
reported to the devs, but unfortunately, we dont have any i686 chromebooks at hand, so it wont be fixed anytime soon

**Comment by artdeell** [comment]
Issue from last year. Please check if it's still, applicable as there has been dome work done on x86 support.
