### ISSUE TITLE
Skin 

### ISSUE THREAD

**Issue by baqarigamer** [PojavLauncherTeam/PojavLauncher#449]
How to fix skin craching in pojavlaucher 1.16 1.15

**Comment by mglovers123** [comment]
maybe remove the meta-inf .Minecraft/version/yourminecraft.jar

**Comment by WesleyVanNeck** [comment]
use a mojang account

**Comment by baqarigamer** [comment]
How to get mojang account

**Comment by WesleyVanNeck** [comment]
by buying minecraft

**Comment by khanhduytran0** [comment]
For new account, Minecraft uses Microsoft account.
