### ISSUE TITLE
> And my Zink renderer crash with optifine but work with sodium why ?

### ISSUE THREAD

**Issue by Nitin1234556** [PojavLauncherTeam/PojavLauncher#4492]
> And my Zink renderer crash with optifine but work with sodium why ?

send log

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/4491#issuecomment-1684099158_

**Comment by Nitin1234556** [comment]
![Uploading Screenshot_2023-08-19-11-59-48-65.jpg…]()

**Comment by Nitin1234556** [comment]
See this it get crash at that log

**Comment by Bel69420** [comment]
Pls wait until the upload complete before you send it

**Comment by Bel69420** [comment]
It's kinda corrupted

**Comment by Nitin1234556** [comment]
> Pls wait until the upload complete before you send it

Wth

**Comment by Bel69420** [comment]
Try click the picture

**Comment by Nitin1234556** [comment]
![Uploading Screenshot_2023-08-19-11-59-48-65.jpg…]()

**Comment by Bel69420** [comment]
Still corrupted

**Comment by GaucovyAero** [comment]
you have to wait for it to upload

**Comment by Nitin1234556** [comment]
[Screenshot_2023-08-19-11-59-48-65.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12387242/Screenshot_2023-08-19-11-59-48-65.zip)

**Comment by GaucovyAero** [comment]
> [Screenshot_2023-08-19-11-59-48-65.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12387242/Screenshot_2023-08-19-11-59-48-65.zip)

it just doesnt work, dunno, you probably cant do anything about it
