### ISSUE TITLE
Mouse not clicking

### ISSUE THREAD

**Issue by lunatic-coded** [PojavLauncherTeam/PojavLauncher#4494]
### Describe the bug

Any buttons assigned to click a mouse button will not work. Clicking on the screen will also not work. 

### The log file and images/videos

[latestlog.old.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12387209/latestlog.old.txt)

### Steps To Reproduce

```markdown
Happens when clicking the single player or multiplayer button on 1.20.1.
```

### Expected Behavior

Expected the button to be clicked.

### Platform

```markdown
- Device model: iPhone 13
- CPU architecture: unsure (A15 bionic)
- IOS version: iOS 16.6
- PojavLauncher version: 2.2 deepslate
```

**Comment by ZnnieCODM** [comment]
Same problem and i use iphone 13 and i tried different version of pojavlauncher now it work on me 

Try it!
