### ISSUE TITLE
[F-Req] <Rendering problem>

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#4497]
### Is this request related to a bug?

use holy The bug that the renderer will become a black world when it enters version 1.17 or above has not been solved

### Describe the request.

You want to update or modify holy Renderer. There is a Minecraft launcher that has fixed this renderer The problem
https://github.com/fcl-team This is the address to get things, and I hope I can modify the renderer according to this launcher Some mobile phones of 1.17 plus version have been supported

**Comment by bsjssjjs** [comment]
https://github.com/fcl-team The launcher for this project has been fixed, and the renderer problem is not as irreparable as you say

**Comment by GaucovyAero** [comment]
please be more specific

**Comment by bsjssjjs** [comment]
Another initiator https://github.com/fcl-team/foldcarftlauncher/ The magnetic starter has solved the rendering problem But you answered that it could not be repaired I hope you can fix this rendering problem according to this launcher

**Comment by bsjssjjs** [comment]
You say it can't be fixed, but why https://github.com/FCL-Team/FoldCraftLauncher The launcher in this link fixes this rendering bug He uses holy The renderer does not become a black world in versions above 1.17
