### ISSUE TITLE
Test results for PojavLauncher on Android 9

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#45]
Test results for PojavLauncher on Android 9:

1.7.10 - Works very good!
1.8 - Works!
1.9 - Works but laggy
1.10 - Works but very laggy
1.11 - Works very good!
1.12 - Not works
1.12.2 - Not works
Infinite Snapshot - Not works
Optifine - not works

(sorry for bad english)

**Comment by khanhduytran0** [comment]
With me and someone 1.7.10 is crashing!

**Comment by khanhduytran0** [comment]
Thank for your test. Updating README.md
