### ISSUE TITLE
[BUG] Please fix.

### ISSUE THREAD

**Issue by BaNaN4Ik-STOP** [PojavLauncherTeam/PojavLauncher#4500]
### Describe the bug

Sticky keys almost every minute, almost every minute, it happens for a few minutes everything is fine and then it starts again. **Please fix** this is very annoying.

### The log file and images/videos

...

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Select version
3. Launch game
```

### Expected Behavior

...

### Platform

```markdown
- Device model: Samsung Galaxy S9
- CPU architecture: ???
- Android version: 9
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try the latest github actions build

**Comment by GaucovyAero** [comment]
also, closing as this is a duplicate issue
