### ISSUE TITLE
[BUG] Game exited with code -1

### ISSUE THREAD

**Issue by BlackSwordFIFTY5** [PojavLauncherTeam/PojavLauncher#4501]
### Describe the bug

dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so" is 64-bit instead of 32-bit
this is the log that shows the failed component, whats this problem and how do i solve it?

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12409655/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open Pojav Launcher
2. select Version 1.20.1
3. Launch
```

### Expected Behavior

normally the Game just gives a Low Memory warning and Launches but here it crashes immediatly.

### Platform

```markdown
- Device Model: LG V40 ThinQ
- CPU Architecture:AArch64(system Architecture) Kryo 385(CPU Architecture)
- Android Version: Android 10
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk (9939086)
```

**Comment by BlackSwordFIFTY5** [comment]
This Problem is Present with all versions not just with 1.20.1

**Comment by GaucovyAero** [comment]
wow, this is a very weird issue, try downloading jre17-aarch32 from the link below, extract it and install it with pojavlauncher settings - java tweaks - runtime manager and set it as default, try 1.20.1 then

https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/5885609317

this might be bad advice tho, so keep that in mind

**Comment by BlackSwordFIFTY5** [comment]
I downloaded Pojav Launcher from Play store instead of an APK Library and
now it's working fine, only downside is that I'm getting awful performance
which I've never encountered before, like getting 20 - 30 FPS with lowest
settings 2 Render chunks, but it could just be my ever slowing device. But
I really appreciate such an instant response from Pojav Launcher Team.

**Comment by Mathias-Boulay** [comment]
You can reach decent performance in theory with said chipset, I have a poco f1 but heavily modded.

**Comment by GaucovyAero** [comment]
okay, well at least you got it running, you can reach out to us via discord and i can help you get more fps
