### ISSUE TITLE
Modpack installer

### ISSUE THREAD

**Issue by McTutorialID23** [PojavLauncherTeam/PojavLauncher#4504]
### Is this request related to a bug?

I want pojavlauncher to add Minecraft version selection while installing modpack, So that we can download the modpack according to the Minecraft version he is playing

### Describe the request.

I want pojavlauncher to add Minecraft version selection while installing modpack, So that we can download the modpack according to the Minecraft version he is playing

**Comment by Mathias-Boulay** [comment]
already present in the PR, use the filters
