### ISSUE TITLE
PC Acessability

### ISSUE THREAD

**Issue by ShadowDuded** [PojavLauncherTeam/PojavLauncher#4505]
### Is this request related to a bug?

no

### Describe the request.

Add the ability to download Povjavlauncher for Windows

### Anything else?

idk i just want a way to play pojavlauncher on pc (don't ask me why I have the normal launcher i just prefer it) without having to go through scummy websites that inevitably don't work :V

**Comment by GaucovyAero** [comment]
i suggest you use multimc or prismlauncher, no pojav for pc for now okay
