### ISSUE TITLE
Add a custom mouse icon.加入自定义鼠标图标。

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#4506]

**Comment by GaucovyAero** [comment]
wont be added, do it manually instead

https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/8a284bfd-24dc-4542-9fd9-8d9d6727a5cc

**Comment by lzfddkd** [comment]
> wont be added, do it manually instead
> 
>  2022-12-02_1670008640274.mp4

What applition?
