### ISSUE TITLE
[BUG] <modpack Download problem>

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#4507]
### Describe the bug

Choose one modpack After clicking download, the module is downloaded normally.But after downloading the module, the progress bar is stuck, and it will not move or jump to a certain page.

### The log file and images/videos

![Uploading Screenshot_20230824_143531.jpg…]()

### Steps To Reproduce

```markdown
Turn on the starter.enter modpack Download a package.After downloading the module, the progress bar gets stuck.It doesn't jump to any page.
```

### Expected Behavior

INSTALL modpack It won't get stuck again.

### Platform

```markdown
- Device model: VIVO Y83
- CPU architecture: ARM64
- Android version: 8.1
- PojavLauncher version: dahlia-20230823-2f04525
```

**Comment by bsjssjjs** [comment]
![Screenshot_20230824_143531](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136832400/01289f57-fa6a-4c6e-92a7-747918aa9d36)
It's stuck right here.

**Comment by bsjssjjs** [comment]
Can it be solved?

**Comment by artdeell** [comment]
> Can it be solved?

You just need to wait, because some modpacks have a lot of overrides.
