### ISSUE TITLE
[Hotbar not sowing] <The hotbar is not shown in versions higher than 1.16.5>

### ISSUE THREAD

**Issue by Hitviralxdxd** [PojavLauncherTeam/PojavLauncher#4509]
### Describe the bug

good evening (depending on your country) I currently have a problem when I want to play versions higher than 1.16.5, because every time I try to play with gl4s the hotbar and the pointer do not appear, and I have seen videos that say that you just have to change to angle rendering but it doesn't appear and I've tried it on other devices and it lowers performance, I hope they fix that with gl4s rendering (it should be noted that I also tried different renderings but they gave me rendering problems)

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/143149036/ff585926-2efa-4c36-955b-719be93f9d98

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12435017/latestlog.txt)

### Steps To Reproduce

```markdown
1-start pojavlauncher on versions higher than 1.16.5 2
-the bug occurs
```

### Expected Behavior

I don't know

### Platform

```markdown
- Device model: Lenovo TB-X306X (LenovoTB-X306X
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest from google play dahlia
```

### Anything else?

Nop

**Comment by KhanhLamVirual** [comment]
work for me

**Comment by KhanhLamVirual** [comment]
> work for me

Try install optifine and open shader setting choose internal option!

**Comment by GaucovyAero** [comment]
this is caused by your ge8320 graphics chip, install optifine and either change the shaders to internal or set antialiasing to 2x fxaa

**Comment by Hitviralxdxd** [comment]
When I put the shader it gives me rendering problems like: the corners of my character's head and the others are highlighted, the sky turns black, and performance drops a bit, I'll try the antialiasing method although it would be good if they patched this in a next update.

**Comment by Bel69420** [comment]
Shader decrease your fps though

**Comment by Bel69420** [comment]
Also, GL4ES doesn't support shader that requires OpenGL 4.0+

**Comment by Hitviralxdxd** [comment]
I only wear the internal shaders, do you think they can solve that problem? or make my graphics chip compatible?

**Comment by GaucovyAero** [comment]
> I only wear the internal shaders, do you think they can solve that problem? or make my graphics chip compatible?

yep

**Comment by Hitviralxdxd** [comment]
I will look forward to it
