### ISSUE TITLE
May I know when to update the Google play store version and hope to release the apk on GitHub release

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#4511]

**Comment by GaucovyAero** [comment]
there should be a play store release when all the fixes and feature updates are done, github release will not contain the apk most probably as always

**Comment by cyriotic3** [comment]
hopefully they'll fix the bug with sodium 0.4 not working on ANGLE with LWJGL 3.3.1 before updating the play store version

**Comment by lzfddkd** [comment]
> hopefully they'll fix the bug with sodium 0.4 not working on ANGLE with LWJGL 3.3.1 before updating the play store version

The lwjgl3.3.1 renderer bug already fixed
