### ISSUE TITLE
[F-Req] <that the launcher has a skin editor for non-premium and premium ones>

### ISSUE THREAD

**Issue by Hitviralxdxd** [PojavLauncherTeam/PojavLauncher#4512]
### Is this request related to a bug?

I like to play survival, but something that bothers me is that I don't have a skin in my worlds and on servers that don't have the /skin command

### Describe the request.

It would be quite good if a skin editor was added for non-premium users like what tlauncher does, that is, the skins that we non-premiums wear with the pojav launcher can only not be seen among ourselves

**Comment by Hitviralxdxd** [comment]
by the way, when they update the play store version to the new functions

**Comment by GaucovyAero** [comment]
no, find mods that do that same thing
