### ISSUE TITLE
Zink render Problem Crash On Aderno 618

### ISSUE THREAD

**Issue by LithuanianBoi41** [PojavLauncherTeam/PojavLauncher#4513]
### Describe the bug

Draw Buffering 

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/107354928/afecd1bd-d489-4118-b05e-c0e3b130d2f2

I am trying running Minecraft 1.20.1 On Vulkan Zink render it Crashing 

### Steps To Reproduce

```markdown
Start Pojav Launcher
See Error
Zink Render Running
Crashing
```

### Expected Behavior

Please 🥺 Fix this problem for pojav launcher for aderno please 

### Platform

```markdown
- Device model: Poco X3 NFC 6/128
- CPU architecture: aarch64 
- Android version: 12
- PojavLauncher version: 20230601
```

### Anything else?

Problem is Keep Crashing And Exits We Want Fix This Problem With Zink Renderer On Aderno 618

**Comment by GaucovyAero** [comment]
zink doesnt really work on all devices yet, we will see if we can get it working later

**Comment by lzfddkd** [comment]
If you want zink work on Adreno GPU,you should install Turnip driver

**Comment by lzfddkd** [comment]
If your GPU already install Turnip driver,you should try newest zink version
