### ISSUE TITLE
Bookcover trackpad not working on samsung tab s9

### ISSUE THREAD

**Issue by N1njaDerp** [PojavLauncherTeam/PojavLauncher#4514]
### Is this request related to a bug?

Whenever I try to use the samsung s9 bookcover trackpad in game, it doesn't work as intended and just shakes around.

### Describe the request.

Hi! I saw a post from a user who seems to be having a similar issue with a samsung tab s7, and I would like to see if this could be resolved. It works find when using a wireless mouse. I'm on the latest build from github. I have tried to get it working in both dex mode and in default mode, and it doesn't work. I posted a video of what's happening just in case it helps.

https://github.com/PojavLauncherTeam/PojavLauncher/assets/33707877/28595644-c298-4d35-aa37-ed99158ef7e0

Thanks, and best wishes!

**Comment by GaucovyAero** [comment]
try updating to the latest v3_openjdk github actions build

**Comment by N1njaDerp** [comment]
I'm updated to the latest version, but it still doesn't work

**Comment by GaucovyAero** [comment]
> I'm updated to the latest version, but it still doesn't work

please state the exact version

**Comment by GaucovyAero** [comment]
stale
