### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by theDANiMC** [PojavLauncherTeam/PojavLauncher#4515]
### Describe the bug

Aplication exited with code 1

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.12.2-forge-14.23.5.2859
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2790
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~CmuW-VArfjwHUiMpjoWKtg==/net.kdt.pojavlaunch-e_zcDzy9dI0Vp0IqTLuXjg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~CmuW-VArfjwHUiMpjoWKtg==/net.kdt.pojavlaunch-e_zcDzy9dI0Vp0IqTLuXjg==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1440
--------- beginning of main

I/LIBGL   (20657): Initialising gl4es
I/LIBGL   (20657): v1.1.4 built on Mar 11 2023 20:15:08
I/LIBGL   (20657): Using GLES 2.0 backend

I/LIBGL   (20657): loaded: libGLESv2.so
I/LIBGL   (20657): loaded: libEGL.so

I/LIBGL   (20657): Using GLES 2.0 backend

I/LIBGL   (20657): Hardware Full NPOT detected and used
I/LIBGL   (20657): FBO are in core, and so used
I/LIBGL   (20657): PointSprite are in core, and so used
I/LIBGL   (20657): CubeMap are in core, and so used
I/LIBGL   (20657): BlendColor is in core, and so used
I/LIBGL   (20657): Blend Substract is in core, and so used
I/LIBGL   (20657): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (20657): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (20657): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (20657): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (20657): Extension GL_OES_depth24  detected and used
I/LIBGL   (20657): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (20657): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (20657): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (20657): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (20657): Extension GL_OES_texture_float  
detected and used
I/LIBGL   (20657): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (20657): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (20657): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (20657): high precision float in fragment shader available and used
I/LIBGL   (20657): Max vertex attrib: 32
I/LIBGL   (20657): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (20657): Max texture size: 16384
I/LIBGL   (20657): Max Varying Vector: 31
I/LIBGL   (20657): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (20657): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (20657): Max Anisotropic filtering: 16
I/LIBGL   (20657): Hardware vendor is Qualcomm

I/LIBGL   (20657): GLSL 300 es supported
I/LIBGL   (20657): GLSL 310 es supported and used
I/LIBGL   (20657): GLSL 320 es supported
I/LIBGL   (20657): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (20657): sRGB surface supported
I/LIBGL   (20657): EGLImage to Texture2D supported
I/LIBGL   (20657): EGLImage to RenderBuffer supported

I/LIBGL   (20657): ignore MipMap
I/LIBGL   (20657): Targeting OpenGL 2.1
I/LIBGL   (20657): No hack in shader converter to define overloaded function with int
I/LIBGL   (20657): NPOT texture handled in hardware
I/LIBGL   (20657): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (20657): try to use VBO
I/LIBGL   (20657): glX Will try to recycle EGL Surface
I/LIBGL   (20657): Current folder is:/
I/jrelog  (20657): dlopen libgl4es_114.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (20657): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (20657): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (20657): dlopen /data/app/~~CmuW-VArfjwHUiMpjoWKtg==/net.kdt.pojavlaunch-e_zcDzy9dI0Vp0IqTLuXjg==/lib/arm64/libopenal.so success

I/jrelog  (20657): Done processing args

I/jrelog  (20657): Found JLI lib
I/jrelog  (20657): Calling JLI_Launch

OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Unrecognized VM option 'DisableExplicitGC-'
Did you mean '(+/-)DisableExplicitGC'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7ab607ccf8)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. select the version 1.12.2 with forge
3. The app exited with code 1
```

### Expected Behavior

I expect the game to launches

### Platform

```markdown
- Device model: Google Pixel 3 XL
- CPU architecture: 4x Qualcomm Kryo 385 Silver @
- Android version: 12
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by theDANiMC** [comment]
I think my CPU architecture is wrong 🤔, isn't?

**Comment by Bel69420** [comment]
You forgot to put minus/+ behind your JVM argument

**Comment by theDANiMC** [comment]
> You forgot to put minus/+ behind your JVM argument

Like this? /+-Xmx1G -Xms1G -Xmn128m -XX:+DisableExplicitGC - 
Sorry if I'm too dumb
Im not very good for speaking english :(

**Comment by theDANiMC** [comment]
> You forgot to put minus/+ behind your JVM argument
Thanks, you gave me the idea of deleting the JVM arguments and now it worked, thank you very much!!!
