### ISSUE TITLE
[BUG] can't run jre 17

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#4517]
### Describe the bug

Exit with code 1

I can't play 1.17.x and above (including optifine , vanilla , forge ,.... All client i know) because i can't run jre 17 on my phone
When i switch to  jre 8 and set it default , i try to run the game again but it still automatically switch to jre 17 and crash
I also using custom jvm so sorry if that jvm make the game crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12445473/latestlog.txt)
https://drive.google.com/file/d/1SG92LwuTM9FlLJXgQE742HSLiA9t6f5y/view?usp=drivesdk  ((sorry the video was kinda heavy so i can't upload it here so i send the link instead))

### Steps To Reproduce

```markdown
1 start pojavlaucher
2 install 1.18.1 vanilla
3 install 1.18.1 optifine
4 run it with default settings and it crash
```

### Expected Behavior

I want to it run completely fine and doesn't crash when run jre 17

### Platform

```markdown
- Device model: google pixel 3 , 4/64gb
- CPU architecture: arm64-v8a (64-bit)
- Android version: 12 (up to date)
- PojavLauncher version: version dahlia-740-623f7dd33-v3_openjdk    (newest)
```

**Comment by GaucovyAero** [comment]
remove your custom jvm arguments, they dont work on pojav

**Comment by TylerHaoNhot** [comment]
> remove your custom jvm arguments, they dont work on pojav

Its doesn't work , it still crashing tho

**Comment by GaucovyAero** [comment]
> > remove your custom jvm arguments, they dont work on pojav
> 
> Its doesn't work , it still crashing tho

send log

**Comment by TylerHaoNhot** [comment]
> > > remove your custom jvm arguments, they dont work on pojav
> > 
> > 
> > Its doesn't work , it still crashing tho
> 
> send log

Wait sorry , my bad.
I deleted it on your first comment but after this second comment , i check the log and noticed its still having a jvm argument , i then check pojavlaucher and noticed the jvm is still there lol
I think i was click "cancel" instead of "ok" button so the jvm still there , sorry

And now its actually running fine though , thank you so much.
(Ima delete this bug report btw)
