### ISSUE TITLE
[F-Req] Support for loading custom Vulkan/OpenGL drivers

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4518]
### Is this request related to a bug?

Not directly related, but should solve some of the problems caused by lack of driver functionality

### Describe the request.

Just like the[ Skyline emulator](https://github.com/skyline-emu/skyline).

Mainly used for VulkanMod and Zink, nowadays VkMod/Zink requires Vulkan1.3 and most Android devices have proprietary drivers that only support Vulkan1.1. However, Mesa driver can support Vulkan 1.3 in full, but it lacks AHB support, so it's not a good idea to use it as a system Vulkan driver,  It should be used separately by PojavLauncher.

Integrating the driver into PojavLauncher is also not a good idea, it is not possible to update the driver independently of PojavLauncher, Zink and Turnip have new features and performance improvements almost every week.

Therefore, it is recommended to import the custom driver via a zip/tar package, similar to the way the JRE is currently imported.

**Comment by 0hStormy** [comment]
I really like this idea! I hope this gets added both to Android and iOS.

**Comment by lzfddkd** [comment]
I hope it can add in PojavLauncher.

**Comment by jelebruh** [comment]
bump

**Comment by gdffgg43g** [comment]
cool idea

**Comment by GaucovyAero** [comment]
turnip has been added into the latest actions builds and is automatically loaded when using zink
