### ISSUE TITLE
[SCREEN TEAR ZINK] S22 ultra xlipse 920 exynos 2200 

### ISSUE THREAD

**Issue by IceMan0505** [PojavLauncherTeam/PojavLauncher#4519]
### Describe the bug

Title

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143272182/655b89e7-f6f6-4e8f-b8f2-f508415b0649)

### Steps To Reproduce

```markdown
1 Start Pojav Launcher
2 Run game
```

### Expected Behavior

No screen tear

### Platform

```markdown
- Device model: S22 Ultra
- CPU architecture: 
- Android version: 13
- PojavLauncher version: Latest with Zink
```

**Comment by InfiniXDerg** [comment]
AMD moment

**Comment by Bel69420** [comment]
Smasnug moment using Xclipse instead of Mali

**Comment by Bel69420** [comment]
Smasnug knew that everyone started to hate Mali so they changed their GPU to Xclipse :HYPERROFEL:

**Comment by InfiniXDerg** [comment]
> Smasnug knew that everyone started to hate Mali so they changed their GPU to Xclipse :HYPERROFEL:

Wrong hyperrofel embed <:HYPERROFEL:862691562814570518>

**Comment by Bel69420** [comment]
They can just use Mali G710 but not Xclipse <:HYPERROFEL:862691562814570518>

**Comment by Bel69420** [comment]
> ### Describe the bug
> Title
> 
> ### The log file and images/videos
> ![image](https://user-images.githubusercontent.com/143272182/263495292-655b89e7-f6f6-4e8f-b8f2-f508415b0649.png)
> 
> ### Steps To Reproduce
> ```
> 1 Start Pojav Launcher
> 2 Run game
> ```
> 
> ### Expected Behavior
> No screen tear
> 
> ### Platform
> ```
> - Device model: S22 Ultra
> - CPU architecture: 
> - Android version: 13
> - PojavLauncher version: Latest with Zink
> ```
> 
> ### Anything else?
> _No response_

AMD become a nerd for 69 years straight

**Comment by Bel69420** [comment]
We can't do anything about this, blame AMD. <:HYPERROFEL:862691562814570518>

**Comment by IceMan0505** [comment]
> AMD moment

Never seen this problem in any game. AMD gpu lacks optimization and proper drivers but it will be one of the best GPUs imo if they fix this

**Comment by GaucovyAero** [comment]
i mean this is not a pojav issue, cant really do anything about that

**Comment by NotAHero04** [comment]
> Never seen this problem in any game. AMD gpu lacks optimization and proper drivers but it will be one of the best GPUs imo if they fix this
>
Samsung only licensed the architecture from AMD, nothing else. The driver is not from AMD, but actually ANGLE, a translation layer from OpenGL ES to whatever the GPU is using.

**Comment by GaucovyAero** [comment]
> Samsung only licensed the architecture from AMD, nothing else. The driver is not from AMD, but actually ANGLE, a translation layer from OpenGL ES to whatever the GPU is using.

though i have a feeling this might fix itself after android 14 rolls out, but we will see

**Comment by artdeell** [comment]
> Samsung only licensed the architecture from AMD, nothing else. The driver is not from AMD, but actually ANGLE, a translation layer from OpenGL ES to whatever the GPU is using.

well um aksually :nerd_face: :point_up: zink uses the vulkan driver, which is proprietary and written by amd
