### ISSUE TITLE
Java runtime

### ISSUE THREAD

**Issue by iocmet** [PojavLauncherTeam/PojavLauncher#452]
where to download runtime? I found only for arm64, but I have arm32 at all, nowhere do I have any information about runtime

**Comment by khanhduytran0** [comment]
Since v3.3, rumtimes are packed into app, except aarch32. You may get Boat's one as a runtime replacement https://drive.google.com/file/d/103EheBh7Vvss7pYKD2m9CG5yRuBOGtJB/view?usp=drivesd

**Comment by DENZAKIN** [comment]
![Uploading Screenshot_20201207-190632.jpg…]()
