### ISSUE TITLE
[modpack]Add more modpack install

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#4522]
### Describe the request.

I remember I could use it before curseforge-gui Download curseforge modpack And now Can only be downloaded modrint modpack I hope to add it curseforge modpack Installation of

**Comment by GaucovyAero** [comment]
# how to download curseforge modpack 

## Important!!
Install termux from github (not play store)
Get your curseforge api key here
<https://console.curseforge.com/#/api-keys>
keep it in your clipboard

### Setting up installer
```
termux-setup-storage
pkg update && upgrade
pkg install golang
pkg install unzip
apt install nano
wget <https://github.com/HeyImRuu/getCFpack/archive/refs/heads/main.zip>
unzip main.zip
cd getCFpack-main
nano key
```paste your cf key anywhere on the screen (don't press anything else)
Press CTRL + X
Press CTRL + Y
If it asks for a name type in ``key`` and press enter

### Actually downloading the pack (repeat from here if you finished everything above)
```
cd getCFpack-main 
go run . <modpack .zip or project ID>
ls
mv <modpack folder name> ~/storage/downloads/<anythingyouwant>
```
Modpack .zip can be download from the curseforge page, project ID is in the sidebar or under info tab. You can use either one.

Modpack .zip will work for curseforge profile exports

Modpack folder name is the blue text after the ``ls`` command

The modpack folder will be in download folder, you can move it into pojav with a file explorer 

``credits to xashed for finding the tool``
