### ISSUE TITLE
[F-Req] GUI at landscape.

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#4524]
### Is this request related to a bug?

No , i think.

### Describe the request.

Just make the main screen GUI better at landscape , or make it larger asleast. Its so annoying and hard to click when my phone screen was small (5.5 inch) and due with the small gui of the landscape mode
![Screenshot_20230828-090803](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143271606/eef7d5ba-806f-4f0a-9108-a1e6f4ab0bbf)

**Comment by TylerHaoNhot** [comment]
And btw , my phone dpi is about 780 , for who need it.

**Comment by bsjssjjs** [comment]
The main page of the software is vertical.It was deliberately designed,You shouldn't view the main page in landscape mode.

**Comment by GaucovyAero** [comment]
> And btw , my phone dpi is about 780 , for who need it.

decrease your dpi, there is no landscape mode currently
