### ISSUE TITLE
It is recommended to add support for Quilt[F-Req] <Short description>

### ISSUE THREAD

**Issue by Axyc15** [PojavLauncherTeam/PojavLauncher#4529]

**Comment by GaucovyAero** [comment]
will be added soon

**Comment by Axyc15** [comment]
By the way,automatically install Fabric API & QSL when users install Fabric or Quilt

**Comment by GaucovyAero** [comment]
> By the way,automatically install Fabric API & QSL when users install Fabric or Quilt

maybe later, closing this
