### ISSUE TITLE
Cant click or view config in forge 1.12.2

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#453]
Title Explains issue...!

**Comment by Accountuser99** [comment]
I have Latest Dev Build?

**Comment by WesleyVanNeck** [comment]
> Title Explains issue...!

some more info woeld be nice like latestlog etc

**Comment by WesleyVanNeck** [comment]
were not wizards

**Comment by Accountuser99** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5647516/latestlog.txt)

**Comment by Accountuser99** [comment]
Latest Log

**Comment by Accountuser99** [comment]
Clicking is fine, but I can't view Config

**Comment by khanhduytran0** [comment]
Which config?

**Comment by Accountuser99** [comment]
Any mod Config on the forge

**Comment by khanhduytran0** [comment]
Duplicate #419

**Comment by khanhduytran0** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5647516/latestlog.txt)
> 

```
S/jrelog (16687): Invalid maximum heap size: -Xmx1G-XX-XX
```
