### ISSUE TITLE
Whatch the video.[BUG] <Short description>

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#4530]
### Describe the bug

Uploading Screenrecorder-2023-08-28-20-02-26-459.mp4…

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/127660329/6902cb6f-0973-479c-8b36-5b6dfb5337cb

### Steps To Reproduce

```markdown
Start PojavLauncher
Create new profile
Choose Forge
Close error tips
Back Launcher's home
Create new profile
Choose anyone
Now that the bug appears, Whichever you choose, this error tips window will appear when you return to the PojavLauncher's home
```

### Expected Behavior

no

### Platform

```markdown
- Device model: Redmi K30 Pro
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: dahlia-20230828-ede5c73-
- CPU:Snapdragon 865
```

**Comment by Mathias-Boulay** [comment]
Can you click "show more" and paste the full error here ?
Also the version you stated doesn't seem to be mainline, please reproduce the bug with the mainline version

**Comment by MovTery** [comment]
> Can you click "show more" and paste the full error here ?
> Also the version you stated doesn't seem to be mainline, please reproduce the bug with the mainline version

java.net.MalformedURLException: no protocol: `https://maven.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml`
	at java.net.URL.<init>(URL.java:601)
	at java.net.URL.<init>(URL.java:498)
	at java.net.URL.<init>(URL.java:447)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:18)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadString(DownloadUtils.java:51)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadStringCached(DownloadUtils.java:138)
	at net.kdt.pojavlaunch.modloaders.ForgeUtils.downloadForgeVersions(ForgeUtils.java:43)
	at net.kdt.pojavlaunch.modloaders.ForgeUtils.downloadAllForgeVersions(ForgeUtils.java:94)
	at net.kdt.pojavlaunch.fragments.ForgeInstallFragment.loadVersionList(ForgeInstallFragment.java:52)
	at net.kdt.pojavlaunch.fragments.ForgeInstallFragment.loadVersionList(ForgeInstallFragment.java:22)
	at net.kdt.pojavlaunch.fragments.ModVersionListFragment.run(ModVersionListFragment.java:70)
	at java.lang.Thread.run(Thread.java:923)

**Comment by lzfddkd** [comment]
> Can you click "show more" and paste the full error here ? Also the version you stated doesn't seem to be mainline, please reproduce the bug with the mainline version

The error pop-up is because Forge has deleted metadata.xml and will pop up the error pop-up when retrieval fails

**Comment by lzfddkd** [comment]
> Can you click "show more" and paste the full error here ? Also the version you stated doesn't seem to be mainline, please reproduce the bug with the mainline version

But i don't think it should appear choose other and back to PojavLauncher's home

**Comment by lzfddkd** [comment]
> Can you click "show more" and paste the full error here ? Also the version you stated doesn't seem to be mainline, please reproduce the bug with the mainline version

But I am using the latest action version

**Comment by NotAHero04** [comment]
> java.net.MalformedURLException: no protocol: `https://maven.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml` at java.net.URL.(URL.java:601) at java.net.URL.(URL.java:498) at java.net.URL.(URL.java:447) at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:18) at net.kdt.pojavlaunch.utils.DownloadUtils.downloadString(DownloadUtils.java:51) at net.kdt.pojavlaunch.utils.DownloadUtils.downloadStringCached(DownloadUtils.java:138) at net.kdt.pojavlaunch.modloaders.ForgeUtils.downloadForgeVersions(ForgeUtils.java:43) at net.kdt.pojavlaunch.modloaders.ForgeUtils.downloadAllForgeVersions(ForgeUtils.java:94) at net.kdt.pojavlaunch.fragments.ForgeInstallFragment.loadVersionList(ForgeInstallFragment.java:52) at net.kdt.pojavlaunch.fragments.ForgeInstallFragment.loadVersionList(ForgeInstallFragment.java:22) at net.kdt.pojavlaunch.fragments.ModVersionListFragment.run(ModVersionListFragment.java:70) at java.lang.Thread.run(Thread.java:923)
>
Please downgrade to a previous build. The build you are using is from #4528, which is unfinished and is buggy. It was fixed, however I still do not recommend using it as the code is still very messy at the moment.

**Comment by Mathias-Boulay** [comment]
Closing as it is not a mainline build bug, nor a build from our repository.
