### ISSUE TITLE
[BUG] Control Editor BUG

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#4531]
### Describe the bug

1.If I copy a button, I find that the "Mouse pass-thru" and "Swipeable" Settings for the copied button are turned off by default, even though the original button has those Settings turned on

2.No matter how the transparency of my joystick is changed, it still shows 100% effect

Please watch this video ↓

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/123115192/d4efc095-e799-4a76-ae64-6e0962cebeca

### Steps To Reproduce

```markdown
Just the BUG of the control editor.
```

### Expected Behavior

Please fix it

### Platform

```markdown
- PojavLauncher version:dahlia-20230922-f06216d-v3_openjdk
```

### Anything else?

It's gone.

**Comment by pddno** [comment]
When will these bugs be fixed?

**Comment by ZEOHK** [comment]
I would like to use Pojav to play with PVP and publish videos to promote Pojav. For a better viewing experience and better promotion of Pojav, please repair it by the production team. Thank you

**Comment by Felix14-v2** [comment]
> I would like to use Pojav to play with PVP and publish videos to promote Pojav. For a better viewing experience and better promotion of Pojav, please repair it by the production team. Thank you

You can make custom joystick, something like that
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/66b6ab13-8221-480c-a3e0-f9e782e9e570)

You can also write me in Discord (felix14_v2), I can help with setting up custom controls, especially for PvP.

**Comment by Mathias-Boulay** [comment]
Both bugs should be fixed with the latest v3_openjdk dev build
