### ISSUE TITLE
[BUG] Version download problem

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#4532]
### Describe the bug

forge version, unable to download and install normally

### The log file and images/videos

![Screenshot_20230829_124014](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136832400/66123b70-e251-402d-9546-e8aa573481a7)
![Screenshot_20230829_124009](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136832400/20d9ad48-342f-4f6e-8160-8ed12cb0d52d)
![Screenshot_20230829_124006](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136832400/69f42e51-8ab2-4f00-8522-58f6cd43c92f)

### Steps To Reproduce

```markdown
The normal one goes into the launcher and downloads a version
```

### Expected Behavior

forge can be downloaded normally

### Platform

```markdown
- Device model: VIVOy83
- CPU architecture: arm64
- Android version: 8.1
- PojavLauncher version: dahlia-20230828-ede5c73-
```

**Comment by NotAHero04** [comment]
Please downgrade to a previous build. The build you are using is buggy. It was fixed, but I still recommend not using it as the code is very messy at the moment.

**Comment by lzfddkd** [comment]
> ### Describe the bug
> forge version, unable to download and install normally
> 
> ### The log file and images/videos
> ![Screenshot_20230829_124014](https://user-images.githubusercontent.com/136832400/263901515-66123b70-e251-402d-9546-e8aa573481a7.jpg) ![Screenshot_20230829_124009](https://user-images.githubusercontent.com/136832400/263901541-20d9ad48-342f-4f6e-8160-8ed12cb0d52d.jpg) ![Screenshot_20230829_124006](https://user-images.githubusercontent.com/136832400/263901561-69f42e51-8ab2-4f00-8522-58f6cd43c92f.jpg)
> 
> ### Steps To Reproduce
> ```
> The normal one goes into the launcher and downloads a version
> ```
> 
> ### Expected Behavior
> forge can be downloaded normally
> 
> ### Platform
> ```
> - Device model: VIVOy83
> - CPU architecture: arm64
> - Android version: 8.1
> - PojavLauncher version: dahlia-20230828-ede5c73-
> ```
> 
> ### Anything else?
> _No response_

It's not PojavLauncher's bug,because forge already deleted metadata.

**Comment by GaucovyAero** [comment]
duplicate
