### ISSUE TITLE
Combobox GUI disappears after opening

### ISSUE THREAD

**Issue by XiaoMingGame2023** [PojavLauncherTeam/PojavLauncher#4533]
### Describe the bug

Clicking the key after adding a GUI to the combo box causes all keys to disappear without a normal GUI

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/135619465/400f2921-4750-4930-9daa-81d5324ec224

### Steps To Reproduce

```markdown
Combo Box Add GUI Key Remove Key GUI and Save, Enter Game Use Combo Box Add GUI
```

### Expected Behavior

Normal display

### Platform

```markdown
redmi note12 turbo
arm64
android13
```

**Comment by GaucovyAero** [comment]
the gui button is designed to do exactly that
