### ISSUE TITLE
Sodium mod 1.20.1 crash when I create Minecraft world 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4538]
### Describe the bug

Crash when I create Minecraft world using sodium mod 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Create world
3. Crash the game
```

### Expected Behavior

Working with sodium mod 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Plss help

**Comment by Bel69420** [comment]
Lmao, do not use Sodium 0.5+ with GL4ES

**Comment by Bel69420** [comment]
It doesn't support since GL4ES only support GL 2.1
