### ISSUE TITLE
I started PojavLauncher and crash

### ISSUE THREAD

**Issue by JeromeJavier2007** [PojavLauncherTeam/PojavLauncher#454]
I selected minecraft 1.15 and crashed

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by khanhduytran0** [comment]
?

**Comment by ghost** [comment]
One month happened, when you gonna send the `/sdcard/games/.minecraft/latestlog.txt`

**Comment by Mathias-Boulay** [comment]
Stale issue from old build, closing issue.
*newer build available on google play*
