### ISSUE TITLE
Adreno GPU Does Not Support Zink Vulkan Renderer

### ISSUE THREAD

**Issue by shopcauxamsj** [PojavLauncherTeam/PojavLauncher#4543]
### Describe the bug

What Adreno GPU Does Not Support Zink Vulkan Renderer

How To Fix

### The log file and images/videos

Không Có

### Steps To Reproduce

```markdown
error
```

### Expected Behavior

How To Fix8

### Platform

```markdown
- Device model: Redmi K40
- CPU architecture: Snapdragon 870
- Android version: 13
- PojavLauncher version: 1.12.2
```

### Anything else?

ko

**Comment by GaucovyAero** [comment]
nobody knows, and it probably wont be fixed

**Comment by Bel69420** [comment]
Wait, doesn't Snapdragon 870 support turnip?

**Comment by GaucovyAero** [comment]
it does, maybe hes on an old build, he has the same phone as me and its working for me lol

**Comment by Bel69420** [comment]
Probably that guy using the wrong build that doesn't have turnip installed yet

**Comment by lzfddkd** [comment]
> ### Describe the bug
> What Adreno GPU Does Not Support Zink Vulkan Renderer
> 
> How To Fix
> 
> ### The log file and images/videos
> Không Có
> 
> ### Steps To Reproduce
> ```
> error
> ```
> 
> ### Expected Behavior
> How To Fix8
> 
> ### Platform
> ```
> - Device model: Redmi K40
> - CPU architecture: Snapdragon 870
> - Android version: 13
> - PojavLauncher version: 1.12.2
> ```
> 
> ### Anything else?
> ko

If you want zink renderer work on Anreno GPU,you need install Turnip driver
