### ISSUE TITLE
black world

### ISSUE THREAD

**Issue by KaityXD** [PojavLauncherTeam/PojavLauncher#4544]
### Describe the bug

it still not fixed black world

### The log file and images/videos

hhh

### Steps To Reproduce

```markdown
just join world and it start black
```

### Expected Behavior

start game
join world
black word

### Platform

```markdown
- Device model: realme c11
- CPU architecture: otacore
- Android version: 11
- PojavLauncher version: lastest
```

### Anything else?

plssss fix it

**Comment by HopiHopy** [comment]
这个问题不是早就修复了吗

**Comment by Bel69420** [comment]
You have a phone with GE8320 which mean we can't do anything about it

**Comment by GaucovyAero** [comment]
duplicate issue, use a different device
