### ISSUE TITLE
[BUG] <zink renderer crash from beginning>

### ISSUE THREAD

**Issue by Jazlenkate** [PojavLauncherTeam/PojavLauncher#4545]
### Describe the bug

Beta Zink renderer crash in beginning i can't open it always crash from beginning using the zink because I want to test some shader in 1.12.2-1.14.4

### The log file and images/videos

![Screenshot_2023-09-02-15-18-16-79_054ec268530ec348fc1d6bdef494c2ee](https://github.com/PojavLauncherTeam/PojavLauncher/assets/94172298/178b4254-076c-42cf-9fc8-67485037a3ff)

### Steps To Reproduce

```markdown
I just want try some shader
```

### Expected Behavior

I expect the game to Launch and join in the game

### Platform

```markdown
- Device model: Realme C12 3/32
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Feat: Zink Renderer - Remove VirGL #4316
```

### Anything else?

How to fix the crash using this zink beta

**Comment by Bel69420** [comment]
Dude, zink doesn't support powervr

**Comment by Bel69420** [comment]
We can't do anything about it.

**Comment by Bel69420** [comment]
Only Mali and Adreno are supported with this renderer

**Comment by S4VAIBHAV** [comment]
> Only Mali and Adreno are supported with this renderer

I have Adreno..but still it crashes..all versions..!!

**Comment by Bel69420** [comment]
What's your adreno btw

**Comment by Jazlenkate** [comment]
But in the old zink I can play with shader

**Comment by Bel69420** [comment]
Old pojav use zink from Collabora LTD

**Comment by Bel69420** [comment]
Not Mesa

**Comment by Bel69420** [comment]
That's why your game crashed, because the new zink is from Mesa and it requires some of your Vulkan Extensions device in your phone

**Comment by Bel69420** [comment]
But sadly, your Phone doesn't met the requirements

**Comment by S4VAIBHAV** [comment]
> What's your adreno btw
Adreno (TM) 610

**Comment by Bel69420** [comment]
Bro, not this adreno again
