### ISSUE TITLE
Language bug

### ISSUE THREAD

**Issue by LdragoLegendOP** [PojavLauncherTeam/PojavLauncher#4548]
### Describe the bug

I'm open game and language was bug 
![Screenshot_2023-09-02-21-46-14-131_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/138747962/36b95b2a-0361-4fec-ae14-aa2da761d2f5)

### The log file and images/videos

![Uploading Screenshot_2023-09-02-21-46-14-131_net.kdt.pojavlaunch.jpg…]()

### Steps To Reproduce

```markdown
I'm use fabric of 1.20.1 and optifabric and this bug render holy gl4es Java runtime internull 17
```

### Expected Behavior

![Uploading Screenshot_2023-09-02-21-46-14-131_net.kdt.pojavlaunch.jpg…]()

### Platform

```markdown
- Device model: poco c3 /4/64g
- CPU architecture:aarch32 
- Android version:10 
- PojavLauncher version:[latest Release version]
```

### Anything else?

 
![Uploading Screenshot_2023-09-02-21-46-14-131_net.kdt.pojavlaunch.jpg…]()

**Comment by GaucovyAero** [comment]
update optifabric to the latest github actions build or downgrade fabric api to 0.85.0
