### ISSUE TITLE
[BUG] Font error 

### ISSUE THREAD

**Issue by CommanderTho** [PojavLauncherTeam/PojavLauncher#4549]
### Describe the bug

After installing some mods and entering the game, I encountered this situation 

### The log file and images/videos

![Screenshot_2023-09-03-17-43-33-377_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/118540863/ce212aec-c536-4b0b-a0f4-bf352b323583)

### Steps To Reproduce

```markdown
1.Start The Launcher
2.Everything is normal except fonts
```

### Expected Behavior

Nothing.

### Platform

```markdown
- Device model: Xiaomi Mi Note 3
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by Bel69420** [comment]
Fabric Api moment, downgrade your fabric api

**Comment by GaucovyAero** [comment]
update optifabric to the latest github actions build or downgrade fabric api to 0.85.0

**Comment by CommanderTho** [comment]
> Fabric Api moment, downgrade your fabric api

Alr lastest

**Comment by CommanderTho** [comment]
> update optifabric to the latest github actions build or downgrade fabric api to 0.85.0

It was normal when I installed newer version of optifine. Thank u guys
