### ISSUE TITLE
[BUG]my accoount has minecraft, but it enables demo mode

### ISSUE THREAD

**Issue by Pemptous** [PojavLauncherTeam/PojavLauncher#4554]
### Describe the bug

I just bought the game from minecraft.net with the same account I'm logging in pojav. However, I'm getting the error that I haven't bought it, so it downloads the demo files. (Maybe important: I bought it some hours ago)

### The log file and images/videos

Nothing to type here

### Steps To Reproduce

```markdown
1. Start pojav
2. Login
3. Tap play
```

### Expected Behavior

An error pops up sayin that you must buy the game to play it, after that it just downloads the demo assets

### Platform

```markdown
- Device model: Samsung a72
- CPU architecture: snapdragon sth
- Android version: latest
- PojavLauncher version: -\\-
```

**Comment by GaucovyAero** [comment]
android pojav does not have demo mode yet, please make sure your pojav version is dahlia-740, the latest one on play store as of today

**Comment by Pemptous** [comment]
> android pojav does not have demo mode yet, please make sure your pojav version is dahlia-740, the latest one on play store as of today

I'm sorry for giving wrong info. I meant iPad 9 with processon a12.

Also, on android when I manage to load minecraft, I can't play online

**Comment by artdeell** [comment]
> I'm sorry for giving wrong info. I meant iPad 9 with processon a12.
> 
> Also, on android when I manage to load minecraft, I can't play online

Please repost your issue on the [PojavLauncher iOS repo](https://github.com/PojavLauncherTeam/PojavLauncher_iOS)
