### ISSUE TITLE
Add GlonD3D12 render.

### ISSUE THREAD

**Issue by PegNattha** [PojavLauncherTeam/PojavLauncher#4555]
### Is this request related to a bug?

GlonD3D12 render shader works without problems.

### Describe the request.

Want to add GlonD3D12 render for running graphics.

### Anything else?

I tested GLonD3D12 render on my windows 11 and it worked fine. So I would like to add this feature.

**Comment by artdeell** [comment]
The reason why this renderer has "D3D12" in it's name is because it uses the Direct3D (part of DirectX) API that is only available on Windows. So we won't be able to add it as PojavLauncher is only available on Android and iOS.
