### ISSUE TITLE
[F-Req] OpenGLES renderer

### ISSUE THREAD

**Issue by Gogo64pro** [PojavLauncherTeam/PojavLauncher#4556]
### Is this request related to a bug?

You should add the opengles renderer for compatibility. Angle is not that powerful. Holy GL4ES is prone to rendering issues

### Describe the request.

Add the opengles renderer as an option in the render select menu

**Comment by GaucovyAero** [comment]
minecraft cannot run on opengles, angle and gl4es serve as translation/compatibility layers between opengl and opengles
