### ISSUE TITLE
Sodium and optifabric

### ISSUE THREAD

**Issue by 5mok4y** [PojavLauncherTeam/PojavLauncher#4561]
### Describe the bug

Sodium doesn't work on Pojav Launcher.Show an message like sodium doesn't not work on Pojav Launcher and it may causes errors and crash the Launcher. 

Optifabric doesn't work on Pojav Launcher Like 
Whenever play multiplayer or single player it crashes the Launcher
@Mathias-Boulay @artdeell @Duy

### The log file and images/videos

**********************Fix this Error****************,,,

### Steps To Reproduce

```markdown
Launches Single player and crashes the Launcher
```

### Expected Behavior

Examples : Game would launch

### Platform

```markdown
- Device model: OnePlusNordCE2
- CPU architecture:octa-core 64 bit architecture 
- Android version:13 
- PojavLauncher version: latest version
```

### Anything else?

Nottingmore

**Comment by GaucovyAero** [comment]
share your log with the optifabric crash

**Comment by GaucovyAero** [comment]
stale issue, closing
