### ISSUE TITLE
[BUG] Local account email login

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#4568]
### Describe the bug

I wrote my email in local account and its not asking me for the password/logging me in

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/98971458/d2e8a384-c8e1-4f1c-9b81-75b357ae83e1

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Go to add account
3. Pick local account
4. Write your mojang email
5. Click Log in
6. It wont log you in or ask for your password
```

### Expected Behavior

I thought it would ask me for my password

### Platform

```markdown
- Device model: Techno Spark 8 Pro
- CPU architecture: 64 bit (arm64-v8a, armeabi-v7a, armeabi)
- Android version: Android 11
- PojavLauncher version: latest
```

### Anything else?

Here's another explanation: I wrote my email in the local account and clicked log in, nothing happened.

**Comment by GaucovyAero** [comment]
you should put a name there, not mail

**Comment by Marcosayfi** [comment]
> you should put a name there, not mail

then why does it say username OR email
and i have online mojang account, i wanna use THAT

**Comment by GaucovyAero** [comment]
pojav doesnt support mojang account login

**Comment by Marcosayfi** [comment]
> pojav doesnt support mojang account login

but in the old versions u could but why not anymore

**Comment by CowSheep72** [comment]
> > pojav doesnt support mojang account login
> 
> but in the old versions u could but why not anymore

It's because of account migration, meaning that Mojang accounts/Original Minecraft accounts would have to be migrated to Microsoft accounts, meaning if you didn't migrate, your account would not be accessible.
