### ISSUE TITLE
[BUG] Deleting the app

### ISSUE THREAD

**Issue by Konraiser** [PojavLauncherTeam/PojavLauncher#4569]
### Describe the bug

I want to download the older version of pojav launcher, but I can't delete the installed version. System app, which doing that just crashing with launcher. Other apps are deleting without problem

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1. Delete pojav launcher
```

### Expected Behavior

No

### Platform

```markdown
- Device model: Samsung Galaxy A12
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Any version
```

**Comment by Marcosayfi** [comment]
Can you send a video, please?

**Comment by GaucovyAero** [comment]
send a video yeah

**Comment by Konraiser** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/86909967/83f32767-a26a-4722-a24f-0d3efb6098fd

**Comment by GaucovyAero** [comment]
thats your phone's issue lol, never seen this happen, can you try uninstalling it through apps settings?

**Comment by GaucovyAero** [comment]
Because look, this is a Galaxy A12 too and it works just fine.

https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/0b6532c7-0f20-4ed4-b82f-7e155ff76c73
