### ISSUE TITLE
Forge 1.12.2 cursor is wrong on my phone.

### ISSUE THREAD

**Issue by PeterScorPioN** [PojavLauncherTeam/PojavLauncher#457]
I installed the Forge 1.12.2 on my phone, launched it, removed the splash as said in the wiki an it launched, except for one thing. The screen is very wrong. If i use the mouse for example, i will have to drag it  in the top right corner of my screen to select the settings button. This is what i mean. Something is wrong with the cursor in general. I don't know, maybe it's the phone, maybe i did something wrong... As i saw, no one had a problem like this. Please help me. Also, i use the Pojav Launcher 3.3 test 1.

My phone:Xiaomi Pocophone F1
RAM: 6GB
CPU:Snapdragon 845
GPU: Andreno 630
OS: Android 10

**Comment by Mynameispoop** [comment]
U need to on full screen

**Comment by PeterScorPioN** [comment]
Is it that? Because when the game starts and i see the main menu, it is on full screen, but it just acts like it's not. However, i will try. Thank you for answering.

**Comment by khanhduytran0** [comment]
Known issue.

**Comment by PeterScorPioN** [comment]
Nope, it's not this. I opened options.txt to change fullscreen, but it was already on true. It's not something that i have done, i guess... Also this happens only in Forge.

**Comment by PeterScorPioN** [comment]
Ok, i fixed it. The solution for this thing is to open the options.txt (sdcard/games/.minecraft/options.txt), find two settings called overrideWidth and overrideHeight and put your phone's resolution in pixels. Be careful with width and height though.

**Comment by Namdz1221** [comment]
Mình không biết chỉnh kiểu gì cho vừa

**Comment by khanhduytran0** [comment]
> Mình không biết chỉnh kiểu gì cho vừa

Bạn dùng một số app đo pixel màn hình ấy

**Comment by khanhduytran0** [comment]
@PeterScorPioN use this build auto set overrideWidth and overrideHeight https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/405706349

**Comment by PeterScorPioN** [comment]
> @PeterScorPioN use this build auto set overrideWidth and overrideHeight https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/405706349

I downloaded this build, but all of my versions stoped launching. They were working, but when i downloaded that build, i only had black screen.

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by PeterScorPioN** [comment]
I'm sorry, i reinstalled the 3.3.0 and i cannot find that log any more.

**Comment by khanhduytran0** [comment]
Also duplicate #410 

Use latest build will auto set overrideWidth/overrideHeight.

**Comment by brunkeyqpqpq** [comment]
Ive figured out how to move the mouse. how do you select with it. Ive clicked and tapped, not working.
