### ISSUE TITLE
With the Open4ES-Shader on Holy-GL4ES 115 Render, the blocks rendering perspective always faces north

### ISSUE THREAD

**Issue by routhing** [PojavLauncherTeam/PojavLauncher#4570]
### Describe the bug

With the Open4ES-Shader on Holy-GL4ES 115 Render, the blocks rendering perspective always faces north.

### The log file and images/videos

![Screenshot_2023-09-09-10-18-15-261_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/71493668/2e9c28fa-2370-4074-aa03-89a77c0e233f)
![Screenshot_2023-09-09-10-43-40-613_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/71493668/cf9bb20c-61d7-4255-b4a6-ec472be25aad)
![Screenshot_2023-09-09-10-44-04-030_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/71493668/9d44d0dc-b1c7-4bdc-afb3-628520744a1e)

### Steps To Reproduce

```markdown
Install 1.19.2 Xplus OptiReady fabric Pack, Add the Shader Pack as shown above in the game.
```

### Expected Behavior

The Open4ES-Shader renders normally

### Platform

```markdown
- Device model: Redmi K30 Pro & Redmi K50
- CPU architecture: S865 & D8100
- Android version: RedmiK30Pro: 10(MIUI11.0.19) & Redmi K50: 12(MIUI13.0.13)
- PojavLauncher version: latest
```

**Comment by Bel69420** [comment]
Lmao, this is shader issues since the shader doesn't support GL4ES 115

**Comment by Bel69420** [comment]
Use apk from playstore
