### ISSUE TITLE
[F-Req] Holy GL4ES upgraded to OpenGL3.3

### ISSUE THREAD

**Issue by Eostrehold** [PojavLauncherTeam/PojavLauncher#4571]
### Is this request related to a bug?

yes it is related to version 5.0 of sodium

### Describe the request.

I hope that Holy GL4ES can be upgraded to OpenGL3.3 to run more smoothly and play Minecraft with Sodium 5.0 version.

### Anything else?

Add a custom mouse.  Thanks

**Comment by GaucovyAero** [comment]
no
