### ISSUE TITLE
Added shader support on ANGLE render.

### ISSUE THREAD

**Issue by PegNattha** [PojavLauncherTeam/PojavLauncher#4573]
### Is this request related to a bug?

ANGLE render cannot run shaders.

### Describe the request.

Added Shader support for ANGLE render for playback on OpenGL 4.6.

**Comment by Bel69420** [comment]
That is not possible, Shaders doesn't recognise Angle renderer extensions

**Comment by Bel69420** [comment]
That's why it doesn't working

**Comment by GaucovyAero** [comment]
angle only has ogl 3.2, nothing below basically
