### ISSUE TITLE
Added Zink render to support more GPUs.

### ISSUE THREAD

**Issue by PegNattha** [PojavLauncherTeam/PojavLauncher#4577]
### Is this request related to a bug?

Unable to run the game with Zink render.

### Describe the request.

Added support for Zink on more GPUs.

**Comment by Bel69420** [comment]
@PegNattha what's your GPU

**Comment by PegNattha** [comment]
> @PegNatthaGPU ของคุณคืออะไร

Model:SM-A125F
GPU:PowerVR Rogue GE8320
Vulkan:1.1.131
Android:12

**Comment by Bel69420** [comment]
PowerVR moment

**Comment by Bel69420** [comment]
Yeah, probably Zink doesn't support PowerVR anymore

**Comment by Bel69420** [comment]
My suggestion is you have to buy a phone with Mali/Adreno GPU

**Comment by PegNattha** [comment]
> คำแนะนำของฉันคือคุณต้องซื้อโทรศัพท์ที่มี GPU Mali/Adren
Thank you for the advice.
