### ISSUE TITLE
After downloading jre17 app crash

### ISSUE THREAD

**Issue by kaicryptx** [PojavLauncherTeam/PojavLauncher#4578]
### Describe the bug

When i click on pojavlauncher app it crashes 

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12587908/latestcrash.txt)

### Steps To Reproduce

```markdown
1.Click On pojav app it crash
```

### Expected Behavior

Its happening after i downloaded jre17 runtime 

### Platform

```markdown
- Device model: realme c3
- CPU architecture:  aarch64
- Android version: 10
- PojavLauncher version: playstore latest version
```

**Comment by kaicryptx** [comment]
@khanhduytran0

**Comment by GaucovyAero** [comment]
thats not caused by jre17 lol, thats caused by you deleting all the profiles
delete .minecraft/launcher_profiles.json
issue resolved in the latest actions build
