### ISSUE TITLE
When aarch32 bit support fabric?

### ISSUE THREAD

**Issue by KUALALUM** [PojavLauncherTeam/PojavLauncher#458]
I just ask about it... And dont mad to me if it still working??

**Comment by khanhduytran0** [comment]
Aarch32 is supported, but no jre8 for it yet. But you could at least get boat runtime one

**Comment by KUALALUM** [comment]
> Aarch32 is supported, but no jre8 for it yet. But you could at least get boat runtime one

Can u send me link of the boat runtime becsuse i didnt find it

**Comment by khanhduytran0** [comment]
See #452

**Comment by Mathias-Boulay** [comment]
Java 8 for aarch 32 is packed with the apk since latest github release, closing issue.
