### ISSUE TITLE
Pixelmon Crash Fix

### ISSUE THREAD

**Issue by vortx6** [PojavLauncherTeam/PojavLauncher#4580]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12595603/latestlog.txt)
### Describe the bug

hi so i downloaded pixelmon 9.1.3 on pojav in 1.16.5 forge 36.2.34 so basically the problem is my game is crashing with code-1 i also used the exact same render that it needs 

### The log file and images/videos

![Screenshot_2023-09-12-13-24-04-60_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/144768054/6fa1e0ff-650d-4879-85a8-99e229f1dac8)

### Steps To Reproduce

```markdown
1: started the PojavLauncher with 1.16.5

2: the error popped after the loading screen

3: crashed with application/game exited with code-1
```

### Expected Behavior

i did the exact same thing to download it but its crashing

### Platform

```markdown
- Device model: oppoA15s
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: dahlia-74-623f7dd33-v3_openjdk
```

**Comment by GaucovyAero** [comment]
send log

**Comment by vortx6** [comment]
ok log done now check

**Comment by vortx6** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12595880/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.16.5-forge-36.2.34 - FORGE |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by vortx6** [comment]
ok?

**Comment by vortx6** [comment]
wht

**Comment by vortx6** [comment]
i used holy renderer

**Comment by vortx6** [comment]
can u tell me whats the exact problem bruh

**Comment by GaucovyAero** [comment]
it looks like optifine isnt compatible with pixelmon, its saying the textures atlas is too big

**Comment by vortx6** [comment]
ofc u need optifine it will lag asf in 4gb

**Comment by GaucovyAero** [comment]
> ofc u need optifine it will lag asf in 4gb

this is not a pojav issue, as i said, it looks like pixelmon doesnt work with optifine, i hope you understand now

**Comment by vortx6** [comment]
alr but its stucked on atlas stiching when i tried it rn

**Comment by vortx6** [comment]
i removed optifine still

**Comment by GaucovyAero** [comment]
> alr but its stucked on atlas stiching when i tried it rn

send log

**Comment by vortx6** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12598450/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.16.5-forge-36.2.34 - FORGE |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12598450/latestlog.txt)

it cant fit the texture, try asking on the pixelmon discord server i guess

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.16.5-forge-36.2.34 - FORGE |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by GaucovyAero** [comment]
try asking on the pixelmon discord server, i have no idea how to fix it
