### ISSUE TITLE
[BUG] Option to Install Forge missing

### ISSUE THREAD

**Issue by AshleighTheCutie** [PojavLauncherTeam/PojavLauncher#4582]
### Describe the bug

Option to Install Forge missing

### The log file and images/videos

![Screenshot_20230913-171553](https://github.com/PojavLauncherTeam/PojavLauncher/assets/35613156/24d0bc42-08a6-47de-85ea-13595502de80)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12602257/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Enter Options menu
3. Fail to find any options for installing Forge as outlined here: https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Install-Forge
```

### Expected Behavior

I expect the objects the Wiki mentions to be present in the final build.

### Platform

```markdown
- Device model: BLU G91 Pro
- CPU architecture: AARCH64
- Android version: 11 // Kernel 4.14.186 // Security Update Mar 5, 2022
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
- Game version: MC 1.4.7
```

### Anything else?

The log of when I manually meshed Forge into the main client.jar and tried to use it is also attached.

In case of the install button has been removed, why is it still in the Wiki?

**Comment by artdeell** [comment]
The button is not there because you are on the google play version. On the google play version, you have to use the install .jar feature or some other way to install Forge.
