### ISSUE TITLE
Zink not working on Mali Mediatek Helio 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4584]
### Describe the bug

Crash when start pojavlauncher 

### The log file and images/videos

Can't put latest log

### Steps To Reproduce

```markdown
1.zink Vulcan
2.start pojavlauncher
3.crash
```

### Expected Behavior

Work

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Plss help

**Comment by Bel69420** [comment]
I guess your driver is old

**Comment by kedrick021** [comment]
> I guess your driver is old

How to fix the problem?

**Comment by Bel69420** [comment]
Guess, there's no solution for your problem. I'm sorry

**Comment by Bel69420** [comment]
Since Mali isn't opensource so... You can't update the driver

**Comment by Bel69420** [comment]
Rip

**Comment by Bel69420** [comment]
@kedrick021 i forgot to ask you about the latestlog, can you send me your latestlog?

**Comment by kedrick021** [comment]
I can't put latest log here

**Comment by Bel69420** [comment]
Lemme check your Vulkan Driver

**Comment by Bel69420** [comment]
Download Aida64 from playstore, then go to device an scroll down until you see "Vulkan Device"

**Comment by Bel69420** [comment]
Scroll again until you see the vulkan extensions

**Comment by Bel69420** [comment]
Screenshot all extensions and send it to me

**Comment by kedrick021** [comment]
> @kedrick021 i forgot to ask you about the latestlog, can you send me your latestlog?

https://www.mediafire.com/file/75uvh5jjx5l1c5j/latestlog.txt/file

**Comment by kedrick021** [comment]
> Screenshot all extensions and send it to me

Why can't put any this site anymore?

https://www.mediafire.com/view/x06bedq0g7u3sgt/Screenshot_20230914-224159.png/file

**Comment by kedrick021** [comment]
> > Screenshot all extensions and send it to me
> 
> Why can't put any this site anymore?
> 
> https://www.mediafire.com/view/x06bedq0g7u3sgt/Screenshot_20230914-224159.png/file

https://www.mediafire.com/view/rcmkq9jcbpbrwf7/Screenshot_20230914-224207.png/file

**Comment by Bel69420** [comment]
Your device missing 3 (Maybe) extensions

**Comment by Bel69420** [comment]
That's why zink crashed on you

**Comment by kedrick021** [comment]
> That's why zink crashed on you

😭 no solution?

**Comment by Bel69420** [comment]
Yes

**Comment by Bel69420** [comment]
No solution.

**Comment by kedrick021** [comment]
> No solution.

Ok thanks for wasteting your time
