### ISSUE TITLE
Zink render getting crash

### ISSUE THREAD

**Issue by Nitin1234556** [PojavLauncherTeam/PojavLauncher#4585]
### Describe the bug

No error ocuur 

### The log file and images/videos

#
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12618372/latestlog.txt)

### Steps To Reproduce

```markdown
Game get crash will starting
```

### Expected Behavior

I don't know it get crash automatically on last load generating context 

### Platform

```markdown
- Device model: oppo a15s 4/64Gb
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub Zink render uptade
```

### Anything else?

Plz make Zink render support my device

**Comment by GaucovyAero** [comment]
your graphics chip lacks enough extensions to run zink
