### ISSUE TITLE
your graphics chip lacks enough extensions to run zink

### ISSUE THREAD

**Issue by Nitin1234556** [PojavLauncherTeam/PojavLauncher#4586]
your graphics chip lacks enough extensions to run zink

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/4585#issuecomment-1721051253_
            So it means i can't run Zink

**Comment by Bel69420** [comment]
Yes

**Comment by Bel69420** [comment]
Adreno also can't run zink but luckily turnip driver is exist that made zink will run on Adreno devices

**Comment by Bel69420** [comment]
PowerVR users are completely doomed because they can't run zink at all

**Comment by Bel69420** [comment]
Get a better phone with mali adreno gpu

**Comment by Bel69420** [comment]
or*
