### ISSUE TITLE
Fabric work, but not load any mod.

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#459]
I'm trying to use Sodium, but fabric do not load any mod :(

**Comment by khanhduytran0** [comment]
Known issue. It seems a Fabric issue. You may probably report to Fabric.

**Comment by T-CATHOME** [comment]
Check whether the correct fabric mod is used

**Comment by pstube** [comment]
1.16.4 Sodium 
It works. Check for conflicts with other mods.

**Comment by MateusL13** [comment]
> 1.16.4 Sodium
> It works. Check for conflicts with other mods.

The problem is that the Fabric even don't load any mod!

**Comment by MateusL13** [comment]
> 1.16.4 Sodium
> It works. Check for conflicts with other mods.

which fabric version do you use?

**Comment by pstube** [comment]
fabric 0.6.1.51    check  fabric API
im korean, my youtube tutorial >  https://youtu.be/NM2EElCDqRY

**Comment by ItisDrago** [comment]
That version of fabric  still doesn't work
Can you fix it if you can
