### ISSUE TITLE
Black screen and crush after launch on old device.

### ISSUE THREAD

**Issue by yar512** [PojavLauncherTeam/PojavLauncher#4590]
### Describe the bug

The application has terminated with code 1.

I tried to run on an old device with 32-bit ARMv7 architecture with support for OpenGL ES 2.0. I tried many versions of Java runtime and pojavLauncher, but I did not achieve results. Which version, video acceleration and Java runtime should I use?

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12641732/latestlog.txt)

### Steps To Reproduce

```markdown
1. Opened the application
2. installed the JVM
3. Installed 1.7.10 (same on other versions)
4. I press the play button
5. Black screen and crash with error log 1
```

### Expected Behavior

starting the game

### Platform

```markdown
- Device model: Samsung Galaxy Tab 2 3G
- CPU architecture: 2x ARM Cortex-A9/ 32-bit ARMv7
- Android version: 6.0.1 (Marshmallow)
- PojavLauncher version: 3.3.1 (same latest)
```

### Anything else?

I tried Java runtime 8, 9 and 17. Does not work. Also experimented with later versions of Pojav.

**Comment by artdeell** [comment]
The version of the launcher you have is outdated, and you need to use either a java 8 runtime or a java 17 runtime.

**Comment by yar512** [comment]
@artdeell 
Does not work. When using JDK8-arm, an error occurs in the application with without latelog. :/
[latestlog_Jre17.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12642302/latestlog_Jre17.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | dahlia - 20230624 - feat/lwjgl-3.3.1 |
| Minecraft version | 1.7.10 - VANILLA |
| Renderer | GL4ES_115 |
| Architecture | ARM_32 |
| Java runtime | EXTERNAL - JRE - 17 |
| Java arguments |  |



|Errors Found: |
|--|
| branch.not.mainline |
| java.runtime.wrong.source |

**Comment by yar512** [comment]
When using the latest version from github and JRE17-arm, a crash occurs without a log with error code 6. :/

**Comment by GaucovyAero** [comment]
just use the bundled-in internal runtime

**Comment by yar512** [comment]
@GaucovyAero 
Does not work. 
[latestlog_internal.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12642545/latestlog_internal.txt)

**Comment by Mathias-Boulay** [comment]
How about a log from the mainline build ?

**Comment by yar512** [comment]
@Mathias-Boulay 
Downloaded the official version 3.1.1 with Java Runtime preinstalled (app-debug). When starting the version, it crashes back to the menu without creating an error log.

 : /

**Comment by Mathias-Boulay** [comment]
and this is not a mainline build
v3_openjdk is the main one

**Comment by GaucovyAero** [comment]
> @Mathias-Boulay Downloaded the official version 3.1.1 with Java Runtime preinstalled (app-debug). When starting the version, it crashes back to the menu without creating an error log.
> 
> : /

i guess you are using 3.3.1.1? that one is like 2 years old man, use the latest actions build

**Comment by yar512** [comment]
@GaucovyAero 
@Mathias-Boulay 

Does not work. :/
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12662123/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | dahlia - 740 - v3_openjdk |
| Minecraft version | 1.7.10 - VANILLA |
| Renderer | GL4ES_114 |
| Architecture | ARM_32 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by GaucovyAero** [comment]
```
A newer kernel is required to run this binary. (__kernel_cmpxchg64 helper)
```
wow, ive never seen this happen, what exact android version and what linux kernel version are you running?

**Comment by yar512** [comment]
@GaucovyAero 

Android: 6.0.1 (Marshmallow)
API: 23
Kernel version: 3.0.101-g18f50de (andi@xeon) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Thu Nov 10 21:46:44 CET 2016

**Comment by GaucovyAero** [comment]
okay

**Comment by Mathias-Boulay** [comment]
wha, this is an old kernel indeed. Your device is surely running a custom rom, and I assume the kernel has not been updated to go along with it.

**Comment by GaucovyAero** [comment]
you probably wont be able to fix it even if you updated to an android 7.1 rom, because the kernel probably stays the same, the very old one

**Comment by Mathias-Boulay** [comment]
kernel 3.0 was released in 2011 from what I can tell

**Comment by GaucovyAero** [comment]
yeah, since you cant update the kernel version, this is not fixable

**Comment by GaucovyAero** [comment]
but maybe you can try this old experimental pojav build for android 4.4.4 (works on kernel 3.4.x)
