### ISSUE TITLE
[BUG] blocks and structures having transparency issues

### ISSUE THREAD

**Issue by BlackSwordFIFTY5** [PojavLauncherTeam/PojavLauncher#4595]
### Describe the bug

Blocks and Structures are having layering and transparency issues.

I'm using "Holy GL4ES" Renderer with "Use alternative surface rendering" Enabled.

### The log file and images/videos

![2023-09-18_03 03 43](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135648102/dde9d8c0-b7d4-4bec-9c0d-dba16b4bac4d)
![2023-09-18_03 03 59](https://github.com/PojavLauncherTeam/PojavLauncher/assets/135648102/65a2a405-0af4-420d-afc7-433e94caf250)

### Steps To Reproduce

```markdown
1. Launch Pojav Launcher
2. Start Minecraft
```

### Expected Behavior

I expect the game to show solid objects connected to other blocks to still be solid, while the game doesn't do that. when blocks are alone, they're solid and show as solid but when another block connected to the block, the block closer to the player is badly rendered

### Platform

```markdown
- Device model: LG V40 ThinQ 6/64 (LM-V405UA)
- CPU architecture: Kryo 385 (AArch64)
- Android version: Android 10
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

There is another issue that when I fullscreen the game window on my LG Screen+ Desktop my external mouse stops working.

**Comment by GaucovyAero** [comment]
press f11

**Comment by BlackSwordFIFTY5** [comment]
> press f11

Great! its working again, at Pressing F11 at first completely resized the window to the botton left corner but after I restarted the game its working completely fine, Thank you for your helpful assistence!
