### ISSUE TITLE
i want to solve this log what is this about log

### ISSUE THREAD

**Issue by masoomshado** [PojavLauncherTeam/PojavLauncher#4598]
### Describe the bug

[latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12651647/latestlog.1.txt)

pls solve this log and what is this problem 

### The log file and images/videos

i have sent the log file. i am trying to play game with sodium but i can't play bcz this error come me.

[latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12651647/latestlog.1.txt)

### Steps To Reproduce

```markdown
1. start pojav launcher
2. game crashes
```

### Expected Behavior

i expect to run the mods properly

### Platform

```markdown
- Device model: vivo y11
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use the patch for sodium thats on the pojav wiki
