### ISSUE TITLE
[Mod pack creator] <be able to create your own mod pack>

### ISSUE THREAD

**Issue by DevEriJMT** [PojavLauncherTeam/PojavLauncher#4599]
### Describe the request.

I would like to see a mod pack creator added, having the possibility of adding the mods you want to be able to choose whether it is forge, fabric or quilt. or even put the config folder you want (that is, mod configuration) or something similar to what curseforge does

**Comment by Mathias-Boulay** [comment]
Huu, just create the modpack with the online tools available to you.
