### ISSUE TITLE
Forge 1.12.2 crash

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#460]
1.12.2 forge is crashing after working before.. What have I done wrong and how do I fix?

I have included latest log. 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5648691/latestlog.txt)

**Comment by MateusL13** [comment]
Go to games/.minecraft/config and edit the file splash.properties, change "enabled=true" to "enabled=false". Tell me if it works 😊

**Comment by khanhduytran0** [comment]
Use latest build. It auto disables Forge splash screen.

**Comment by khanhduytran0** [comment]
S/jrelog (16687): Invalid maximum heap size: -Xmx1G-XX-XX

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/405706349

**Comment by notstackgb** [comment]
wdym latest build?
