### ISSUE TITLE
[BUG] Microsoft login SSL ERROR

### ISSUE THREAD

**Issue by eTNTdiscord** [PojavLauncherTeam/PojavLauncher#4607]
### Describe the bug

SSL ERROR An SSL error has occurred and a secure connection to the server
cannot be made.

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/84364590/a1a6f2bf-1113-4527-8079-af22a77ff8b3)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Enable JIT
3. Login to Microsoft
4. SSL ERROR
```

### Expected Behavior

I expect the game to sign in and launch.

### Platform

```markdown
- Device model: iPad 9th Generator
- CPU architecture: idk
- Android version: idk
- PojavLauncher version: 2.2 Depslate
```

**Comment by GaucovyAero** [comment]
this is not the ios repository
