### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by UjjwalWorriar** [PojavLauncherTeam/PojavLauncher#4608]
### Describe the request.

Plz add support of motion blur mod 
Plz make motion blur mod usefull in pojav not shader

**Comment by GaucovyAero** [comment]
there will soon be a new play store update that will add zink renderer support (opengl 4.6 over vulkan), which will make motion blur and shaders work, not all devices work with zink though

**Comment by UjjwalWorriar** [comment]
> there will soon be a new play store update that will add zink renderer support (opengl 4.6 over vulkan), which will make motion blur and shaders work, not all devices work with zink though

But Zink don't work in my device i think it doesn't support GPU ya my prosser
