### ISSUE TITLE
[BUG] T-Mobile Revvl 6 Permission denied

### ISSUE THREAD

**Issue by scpfan69** [PojavLauncherTeam/PojavLauncher#4609]
### Describe the bug

Title

### The log file and images/videos

https://media.discordapp.net/attachments/712749435419099269/1154361211710877696/Screenshot_20230921_061515.jpg

### Steps To Reproduce

```markdown
Try to install 1.12
```

### Expected Behavior

It to run

### Platform

```markdown
- Device model: T Mobile Revvl 6 Pro
- CPU architecture:ARM64
- Android version: 13
- PojavLauncher version:
```

**Comment by dDreaMmtTeaMm** [comment]
go to your version files and delete 1.12.2json file so thae launcher can redownload it + your pojav seems outdeted

**Comment by scpfan69** [comment]
> go to your version files and delete 1.12.2json file so thae launcher can redownload it + your pojav seems outdeted

Ok now when i run forge it doesnt load mods

**Comment by scpfan69** [comment]
Saying the same thing in logs "permission denied"

**Comment by dDreaMmtTeaMm** [comment]
> > go to your version files and delete 1.12.2json file so thae launcher can redownload it + your pojav seems outdeted
> 
> Ok now when i run forge it doesnt load mods 

i thought ur running vanilla 1.12.2
chek the app permissions thats all i know

**Comment by GaucovyAero** [comment]
> Saying the same thing in logs "permission denied"

android app permissions are very broken on t-mobile phones, i have no idea why, try installing pojav from play store and deleting all pojav data, thats probably all you can do

**Comment by scpfan69** [comment]
> > Saying the same thing in logs "permission denied"
> 
> android app permissions are very broken on t-mobile phones, i have no idea why, try installing pojav from play store and deleting all pojav data, thats probably all you can do

Yeah that font work aswell, is there a build where like it uses the old directory? Bc i have noticed that launchers that use a shared directory (such as FCL) load fine.

**Comment by scpfan69** [comment]
Hello?

**Comment by scpfan69** [comment]
.

**Comment by GaucovyAero** [comment]
that build would be very old, so dunno what to do about that

**Comment by scpfan69** [comment]
> that build would be very old, so dunno what to do about that

IA there a possibility someone could make a updated one with zink

**Comment by GaucovyAero** [comment]
please rename the issue to "T-Mobile Revvl 6 Permission denied", thanks
