### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#461]
Support for controller?

**Comment by khanhduytran0** [comment]
Controller aren't mapped yet, but try it.....

**Comment by Accountuser99** [comment]
I've tried controller and it doesn't work, is there a way to map the
controller myself?

**Comment by khanhduytran0** [comment]
Maybe go to Minecraft control settings?

**Comment by matt995** [comment]
Im not sure about this but you can use a app called keymapper by sds100

**Comment by matt995** [comment]
Tho joysticks might not work

**Comment by Mathias-Boulay** [comment]
duplicate from #80
Closing the issue.

**Comment by Tohidop78139** [comment]
Chbv
