### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by UjjwalWorriar** [PojavLauncherTeam/PojavLauncher#4611]
### Is this request related to a bug?

No

### Describe the request.

Make a custom mouse icon support like we can change how the mouse look in game 
And also add support of Zink to all processor and GPU
And the last uptade u had put on GitHub of name big uptade string XML wth uptade was in it

### Anything else?

No thx if u respond

**Comment by GaucovyAero** [comment]
a) duplicate
b) not possible
c) changes some button names in the launcher
