### ISSUE TITLE
[Add Zink render support pvr GPU] 

### ISSUE THREAD

**Issue by UjjwalWorriar** [PojavLauncherTeam/PojavLauncher#4612]
### Describe the request.

Please add support for pvr in Zink 
I want to use motion blur mod or can u give me any solution so I can use motion blur mod like patcher or any other think or any way to use Zink in pvr without changing mobile

**Comment by sa1672ndo** [comment]
Get a phone with a normal gpu, theres nothing we can do about ur shitty powervr gpu not supporting zink.

**Comment by GaucovyAero** [comment]
we cannot do anything more for zink support than we already did, this shader may work for you on gl4es:

https://www.mediafire.com/file/tgttiwqklrl8w4n/Pensa_73_Motion_Blur_V1.1.zip/file
