### ISSUE TITLE
we cannot do anything more for zink support than we already did, this shader may work for you on gl4es:

### ISSUE THREAD

**Issue by UjjwalWorriar** [PojavLauncherTeam/PojavLauncher#4613]
we cannot do anything more for zink support than we already did, this shader may work for you on gl4es:

https://www.mediafire.com/file/tgttiwqklrl8w4n/Pensa_73_Motion_Blur_V1.1.zip/file

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/4612#issuecomment-1729815309_
I don't want shaders i want motion blur mod usefull

**Comment by Bel69420** [comment]
Give up already, powervr is literally a shit GPU that imagination technology made

**Comment by GaucovyAero** [comment]
the motion blur mods also use shaders, its the same thing

**Comment by UjjwalWorriar** [comment]
Shaders are not good

**Comment by UjjwalWorriar** [comment]
It have much blur lines

**Comment by Bel69420** [comment]
Give up already man, motion blur mod needs a higher OpenGL version meanwhile GL4ES only have 2.1

**Comment by Bel69420** [comment]
Zink should work with Motion blue mod but your device doesn't support zink

**Comment by Bel69420** [comment]
Blur*

**Comment by UjjwalWorriar** [comment]
But bro but shader is not that much smooth

**Comment by GaucovyAero** [comment]
i have already said that motion blur mods use shaders to render the blur, its absolutely the same thing

**Comment by UjjwalWorriar** [comment]
> i have already said that motion blur mods use shaders to render the blur, its absolutely the same thing

Bro it is good if u atleast try u guys can do
