### ISSUE TITLE
the motion blur mods also use shaders, its the same thing

### ISSUE THREAD

**Issue by UjjwalWorriar** [PojavLauncherTeam/PojavLauncher#4614]
the motion blur mods also use shaders, its the same thing

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/4613#issuecomment-1729828131_
            Bro shaders have blury lines while moving camera you all are not adding support for Zink but atleast can add support for motion blur for holy by doing something

**Comment by GaucovyAero** [comment]
the shader is probably just broken on newer versions of gl4es, i guess you can only try older play store builds and see if the shader works there
