### ISSUE TITLE
Get a phone with a normal gpu, theres nothing we can do about ur shitty powervr gpu not supporting zink.

### ISSUE THREAD

**Issue by UjjwalWorriar** [PojavLauncherTeam/PojavLauncher#4616]
Get a phone with a normal gpu, theres nothing we can do about ur shitty powervr gpu not supporting zink.

_Originally posted by @sa1672ndo in https://github.com/PojavLauncherTeam/PojavLauncher/issues/4612#issuecomment-1729815152_
Bro Zink work in my device before these new uptades i use this pojav version of GitHub of 2 months ago
 (Merge v3_openjdk into zink #4385) 
of GitHub of Zink uptade and when i use Zink it work but the new uptades that u take it make it don't work plz do anything

**Comment by GaucovyAero** [comment]
show a video of it working with f3 on, chances are we actually can do something about it (now that you said its working on a previous version)

**Comment by UjjwalWorriar** [comment]
> show a video of it working with f3 on, chances are we actually can do something about it (now that you said its working on a previous version)

Oo thx I will make it and upload it

**Comment by UjjwalWorriar** [comment]
Can you give me the link of this build 
Zink Renderer - Remove VirGL #4316
It say it is expired

**Comment by UjjwalWorriar** [comment]
Because i check the build time when I used Zink it is 3 months ago build so it was this give me uptaded app build link of this

**Comment by UjjwalWorriar** [comment]
Bro can u just give me new download link of these build 
Feat: Zink Renderer - Remove VirGL
Start work on the new but swapchain-based Zink, based on the old patc…Zink, but swapchain-based #4318
Of these build 3 months ago the link was expired there

**Comment by UjjwalWorriar** [comment]
Beca

**Comment by UjjwalWorriar** [comment]
Bacause i check the date when i used Zink it was before 3 months

**Comment by GaucovyAero** [comment]
this is it i think

https://github.com/GaucovyAero/PojavLauncher/suites/16451159693/artifacts/940109888

this download link will probably be deleted in a few days tho, its just for testing

**Comment by UjjwalWorriar** [comment]
And these two bro
Feat: Zink Renderer - Remove VirGL #4316Start work on the new but swapchain-based Zink, based on the old patc… #4317
Because I am not sure that which of these three build I used on that time

**Comment by GaucovyAero** [comment]
try the thing i sent you

**Comment by UjjwalWorriar** [comment]
> try the thing i sent you

Kk

**Comment by UjjwalWorriar** [comment]
> try the thing i sent you

I try this but it is not that it didn't work and also the render name is different 
![Screenshot_2023-09-22-19-08-11-86_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/98732466/da8b932b-8d4f-4c84-9fa8-c88c6860b5fc)
It is only written Zink 
But the version that I used it's render name is Zink low device compact all versions fast

**Comment by UjjwalWorriar** [comment]
Give me these links that i say

**Comment by UjjwalWorriar** [comment]
> try the thing i sent you

Bro give the three link that app didn't work

**Comment by UjjwalWorriar** [comment]
It's render name is also different

**Comment by UjjwalWorriar** [comment]
this download link will probably be deleted in a few days tho, its just for testing
And is this new version of pojav ?

**Comment by GaucovyAero** [comment]
> this download link will probably be deleted in a few days tho, its just for testing And is this new version of pojav ?

no, its the old one that you requested lol

**Comment by UjjwalWorriar** [comment]
Nope

**Comment by UjjwalWorriar** [comment]
> > try the thing i sent you
> 
> I try this but it is not that it didn't work and also the render name is different ![Screenshot_2023-09-22-19-08-11-86_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/98732466/269953876-da8b932b-8d4f-4c84-9fa8-c88c6860b5fc.jpg) It is only written Zink But the version that I used it's render name is Zink low device compact all versions fast

See the date of msg in it

**Comment by UjjwalWorriar** [comment]
I want those 3 versions

> And these two bro Feat: Zink Renderer - Remove VirGL #4316Start work on the new but swapchain-based Zink, based on the old patc… #4317 Because I am not sure that which of these three build I used on that time

**Comment by UjjwalWorriar** [comment]
Bro see this

https://github.com/PojavLauncherTeam/PojavLauncher/assets/98732466/d02cb653-26fc-427b-8fd9-7e83d31d936b

This was the latest pojav build on GitHub that I use and that is how it get crashed bro plz make it change to support pvr also

**Comment by UjjwalWorriar** [comment]
It support before these uptades
So by doing some changes it will still support you all guys can do that and i only have proof of that is 
![Screenshot_2023-09-22-18-07-26-47_572064f74bd5f9fa804b05334aa4f912](https://github.com/PojavLauncherTeam/PojavLauncher/assets/98732466/9b97e059-15b2-41ec-8791-97d30d9ec838)
This I asked a youtuber name shadowee about my game crash with optifine not my game not crash with sodium while using Zink render and after that build when i change the build of the apk to the last Zink uptade it start crashing also with sodium plz do something about that

**Comment by UjjwalWorriar** [comment]
And see date also if you guys don't believe

**Comment by Nitin1234556** [comment]
@GaucovyAero bro plz 🙏 make Zink compatible to pvr plz

**Comment by GaucovyAero** [comment]
> I want those 3 versions
> 
> > And these two bro Feat: Zink Renderer - Remove VirGL #4316Start work on the new but swapchain-based Zink, based on the old patc… #4317 Because I am not sure that which of these three build I used on that time

dude, the thing i sent earlier should be exactly like one of those three, it just doesnt work for you, thats fine

**Comment by GaucovyAero** [comment]
closing this until you figure out a way to get it working and record it

**Comment by Nitin1234556** [comment]
> > I want those 3 versions
> > > And these two bro Feat: Zink Renderer - Remove VirGL #4316Start work on the new but swapchain-based Zink, based on the old patc… #4317 Because I am not sure that which of these three build I used on that time
> 
> dude, the thing i sent earlier should be exactly like one of those three, it just doesnt work for you, thats fine

No bro it is not fine also for me

**Comment by GTG921** [comment]
Use pojavlauncher beta version with zink mesa render it would support your device

**Comment by kiokori-git** [comment]
> Use pojavlauncher beta version with zink mesa render it would support your device

theres no pojavlauncher version is called "beta", only dev or debug

**Comment by SolDev69** [comment]
Use SCL for now it has virgl

**Comment by Ujjuyoyo173** [comment]
#4316
