### ISSUE TITLE
Power saving render/ one good idea

### ISSUE THREAD

**Issue by eie7y** [PojavLauncherTeam/PojavLauncher#4618]
### Is this request related to a bug?

If you add power saving render to make the phone less heat it's going be good idea
///
Auto ram + make valkin render a little bit faster it's going be good✓
+ if we run shader in regular render it well be crash or so much lag>shader doesn't work. Add an auto change render if you enabled shader ✓

**Comment by sa1672ndo** [comment]
"If you add power saving render to make the phone less heat it's going be good idea" lock your fps to 60 or lower/enable sustained performance mode.

"Auto ram" just allocate 1-2gb of ram.

"make valkin render a little bit faster it's going be good"(idk what is valkin renderer, but i guess its zink) Mesa Devs are responsible for optimizing zink, pojav devs can only update the zink to the latest version.

"if we run shader in regular render it well be crash or so much lag>shader doesn't work. Add an auto change render if you enabled shader" just don't use shaders with gl4es/angle + its probably not possible to change renderer while mc is running without breaking something.

**Comment by GaucovyAero** [comment]
auto ram is not there, because you may encounter a big fps difference between ram allocation even on the same phone (but with another person - different apps installed, different mods, mc version, etc.)

it is recommended for you to test yourself what you get the best fps with and choose that

**Comment by eie7y** [comment]
Good✓ 
But i have an issue
Modpack's it's not showing like I can't find the modpack i want please fix it

**Comment by GaucovyAero** [comment]
how am i supposed to know what modpack you want

works just fine for me

![Screenshot_20230922-140253_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/f60a5122-de23-4f4e-9727-858492ccb01e)
