### ISSUE TITLE
[BUG] Crash when loading a world with immersive portals

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#4619]
### Describe the bug

I loaded a world with the immersive portals mod then it crashes with out an error code

### The log file and images/videos

Here is my [log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12699859/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. install immersive portals and fabric api
3. launch a world
4. it crashes
```

### Expected Behavior

I thought that the world would launch

### Platform

```markdown
- Device model: Techno Spark 8 Pro
- CPU architecture: All 64 architectures
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

Pretty much nothing else.

**Comment by GaucovyAero** [comment]
your phone doesnt support this extension: `GL_EXT_clip_cull_distance`, so you cant run the mod on virgl
but you can try installing the latest github actions build and using zink (which uses vulkan instead of opengl es)
lmk if it works or not

**Comment by Marcosayfi** [comment]
THANK YOU IT WORKED
