### ISSUE TITLE
1.7.10forgeSTART COLLAPSE

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#462]
--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl-jemalloc.jar, lwjgl-opengl.jar, lwjgl.jar, lwjgl-glfw-classes.jar, lwjgl-tinyfd.jar, lwjgl-openal.jar, version, lwjgl-stb.jar, jsr305.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms512m -Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
--------- beginning of main
--------- beginning of system
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x361
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x450
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x33c0
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x13b8
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x2196
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x6a46
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x4d9
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0xda0
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/LaunchJVM( 7086): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
S/LaunchJVM( 7086): dlopen /data/app/net.kdt.pojavlaunch-Cdd5HlQwekmFUTsvcgPGZA==/lib/arm64/libopenal.so success
S/LaunchJVM( 7086): dlopen /data/app/net.kdt.pojavlaunch-Cdd5HlQwekmFUTsvcgPGZA==/lib/arm64/libgl04es.so success
S/LaunchJVM( 7086): Done processing args
S/LaunchJVM( 7086): Found JLI lib
S/LaunchJVM( 7086): Calling JLI_Launch
S/jrelog  ( 7086): OpenJDK 64-Bit Server VM warning: 
S/jrelog  ( 7086): No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x8ff
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
S/jrelog  ( 7086): " unused DT entry: 
S/jrelog  ( 7086): DT_RPATH
S/jrelog  ( 7086):  (type 
S/jrelog  ( 7086): 0xf
S/jrelog  ( 7086):  arg 
S/jrelog  ( 7086): 0x16fe
S/jrelog  ( 7086): ) (ignoring)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): WARNING: linker: 
S/jrelog  ( 7086): Warning: "
S/jrelog  ( 7086): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
S/jrelog  ( 7086): " has unsupported flags DT_FLAGS_1=
S/jrelog  ( 7086): 0x81
S/jrelog  ( 7086):  (ignoring unsupported flags)
S/jrelog  ( 7086): 
S/jrelog  ( 7086): [11:08:06] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
S/jrelog  ( 7086): [11:08:07] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
S/jrelog  ( 7086): [11:08:07] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
S/jrelog  ( 7086): [11:08:07] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
S/jrelog  ( 7086): [11:08:07] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0-internal, running on Linux:aarch64:Android-10, installed at /data/data/net.kdt.pojavlaunch/jre_runtime
S/jrelog  ( 7086): [11:08:07] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
S/jrelog  ( 7086): [11:08:07] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
S/jrelog  ( 7086): [11:08:07] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
S/jrelog  ( 7086): [11:08:07] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
S/jrelog  ( 7086): [11:08:07] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
S/jrelog  ( 7086): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" unused DT entry: DT_RPATH (type 0xf arg 0x364) (ignoring)
S/jrelog  ( 7086): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
S/jrelog  ( 7086): [11:08:10] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
S/jrelog  ( 7086): [11:08:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
S/jrelog  ( 7086): [11:08:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
S/jrelog  ( 7086): Exception in thread "main" 
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoSuchMethodError: com.google.common.io.CharSource.readLines(Lcom/google/common/io/LineProcessor;)Ljava/lang/Object;
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.asm.transformers.AccessTransformer.processATFile(AccessTransformer.java:125)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:120)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:97)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.newInstance(Class.java:442)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:32)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
S/jrelog  ( 7086): [11:08:10] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java Exit code: 1
S/LaunchJVM( 7086): Going to free args
S/LaunchJVM( 7086): Free done

**Comment by khanhduytran0** [comment]
**Known issue!**

**Comment by nedogimov** [comment]
you need to replace the file in .minecraft/libraries/com/google/guava/guava/15.0/15.0.jar to the renamed file 16.0.jar on 15.0
download 16.0: [https://repo1.maven.org/maven2/com/google/guava/guava/16.0/guava-16.0.jar](click)

**Comment by khanhduytran0** [comment]
Now you are on newer build. Try again @tttghkg
