### ISSUE TITLE
[F-Req] multiplayer with windows (via essential or lan, or anything else)

### ISSUE THREAD

**Issue by Pemptous** [PojavLauncherTeam/PojavLauncher#4620]
### Is this request related to a bug?

I’m sure enough this is not a bug, however I can’t connect to my friend’s essential’s world (I have installed forge, he has cursed forge). Is it essential’s fault, or the pojav-window thingy’s fault. Sorry for my bad English. We have also tried lan, but it didn’t work either.

### Describe the request.

Ok, so first of all I wanna know if it’s essential’s fault, or if another way exists. If not can you try to make one

### Anything else?

No response

**Comment by GaucovyAero** [comment]
essential doesnt support pojavlauncher (they dont guarantee that their mod will work on pojav) but it sometimes does work, but since the mod is closed source, we cant really know what the issue is, therefore we cannot really fix it
