### ISSUE TITLE
Zink getting crash 

### ISSUE THREAD

**Issue by GAMERGENIX1** [PojavLauncherTeam/PojavLauncher#4621]
### Describe the request.

Zink is getting crash on my mobile plealse help me 
Ya fix the crash problem

**Comment by Nitin1234556** [comment]
Plz solve it i am also getting same problem

**Comment by GaucovyAero** [comment]
what phone do you have? (exact model)

**Comment by Nitin1234556** [comment]
CPH2179
This was my mobile model

**Comment by ItsManasxD** [comment]
> CPH2179 This was my mobile model

Maybe Because Of This GPU **PowerVRGE8320**
You Have Oppo A15s Right?

**Comment by Nitin1234556** [comment]
Right

**Comment by ItsManasxD** [comment]
> Right

Zink doesn't Work On **PowerVR** GPUs Right Now Maybe

**Comment by Nitin1234556** [comment]
> > Right
> 
> Zink doesn't Work On **PowerVR** GPUs Right Now Maybe

So will it work till the play store uptade come ?

**Comment by Nitin1234556** [comment]
Or it still getting crash

**Comment by ItsManasxD** [comment]
> >  #Right
> 
> Zink doesn't Work On **PowerVR** GPUs Right Now Maybe

> Or it still getting crash

#4616  uhh Idk See This

**Comment by Nitin1234556** [comment]
> > > #Right
> > 
> > 
> > Zink doesn't Work On **PowerVR** GPUs Right Now Maybe
> 
> > Or it still getting crash
> 
> #4616 uhh Idk See This

Did developer re try on making Zink compatible with pvr ?

**Comment by Igmyt4080** [comment]
> > > > #Right
> > > 
> > > 
> > > Zink doesn't Work On **PowerVR** GPUs Right Now Maybe
> > 
> > 
> > > Or it still getting crash
> > 
> > 
> > #4616 uhh Idk See This
> 
> Did developer re try on making Zink compatible with pvr ?



> > > > #Right
> > > 
> > > 
> > > Zink doesn't Work On **PowerVR** GPUs Right Now Maybe
> > 
> > 
> > > Or it still getting crash
> > 
> > 
> > #4616 uhh Idk See This
> 
> Did developer re try on making Zink compatible with pvr ?

Idk I'm Not a Developer 😅

**Comment by ItsManasxD** [comment]
> > > > #Right
> > > 
> > > 
> > > Zink doesn't Work On **PowerVR** GPUs Right Now Maybe
> > 
> > 
> > > Or it still getting crash
> > 
> > 
> > #4616 uhh Idk See This
> 
> Did developer re try on making Zink compatible with pvr ?

IDK I'm not a Developer 😅

**Comment by Nitin1234556** [comment]
> > > > > #Right
> > > > 
> > > > 
> > > > Zink doesn't Work On **PowerVR** GPUs Right Now Maybe
> > > 
> > > 
> > > > Or it still getting crash
> > > 
> > > 
> > > #4616 uhh Idk See This
> > 
> > 
> > Did developer re try on making Zink compatible with pvr ?
> 
> IDK I'm not a Developer 😅

So did @GaucovyAero also don't know about that

**Comment by Nitin1234556** [comment]
Bro when the crash of Zink render get fix in pvr ?

**Comment by Bel69420** [comment]
Never, since pojav isn't original developer of Zink Renderer

**Comment by Bel69420** [comment]
You should ask Zink Developer itself, not pojav team :trollface:

**Comment by Nitin1234556** [comment]
> You should ask Zink Developer itself, not pojav team :trollface:

So did they don't make Zink renderr compatible with pvr ?

**Comment by Bel69420** [comment]
Yeah, so give up already

**Comment by Bel69420** [comment]
The old zink worked because it from another company

**Comment by Bel69420** [comment]
Idk the old zink is really slower than the new one

**Comment by GaucovyAero** [comment]
the guy didnt answer so im closing this
