### ISSUE TITLE
[F-Req] Gyro controlls on supported controllers

### ISSUE THREAD

**Issue by Sandr-aa** [PojavLauncherTeam/PojavLauncher#4622]
### Describe the request.

While gyro on-device might be great for phones, gyro for controllers would be more feasible for bigger tablets.
A few controllers that support motion controls:
- Sony Dualsense
- Nintendo switch pro controller
- 8bitdo Ultimate Bluetooth in Switch-Bluetooth mode (the 2,4G Model doesn't support gyro)

**Comment by 0hStormy** [comment]
That could be pretty cool, keep up the good suggestions!

**Comment by Mathias-Boulay** [comment]
The suggestion is actually pretty good, however I don't even know whether is it possible

**Comment by Mathias-Boulay** [comment]
After investigation, is it not yet possible to receive gyroscope information from controllers. So I will close the issue
