### ISSUE TITLE
Pls help I can't log in

### ISSUE THREAD

**Issue by TOPRAK717t** [PojavLauncherTeam/PojavLauncher#4623]
### Describe the bug

![Screenshot_2023-09-23-09-06-15-967_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/145592585/6fc37528-fe23-4a51-bf0e-ee754430abc3)

### The log file and images/videos

Pls helpppppp

### Steps To Reproduce

```markdown
1.microsoft log in 
2.continue
3.goes to step 6/6 and gives error 😭
```

### Expected Behavior

Log in and play on an server for first time

### Platform

```markdown
- Device model: idk
- CPU architecture: idk
- Android version: idk
- PojavLauncher version: idk
```

### Anything else?

Guys help meee eeeeeeeee😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭 I want play minemen.club               and hypixel        IP:eu.mienemen.club

**Comment by ItsManasxD** [comment]
Uhh Just Open Chrome Browser On Your Phone And Got To Minecraft.net and login with your account and Come back to Pojav And Relogin Your Account And It Will work 

Or If You use XBoxGamePass then see if that expired or something

**Comment by GaucovyAero** [comment]
it tells you exactly what to do, set up your nickname and skin at https://minecraft.net/
