### ISSUE TITLE
[BUG] ≤Blocks are invisible in Holy GL4ES> 

### ISSUE THREAD

**Issue by Maher3430** [PojavLauncherTeam/PojavLauncher#4625]
### Describe the bug

In Holy GL4ES render, I use it in fabric 1.20 (SODIUM) , and 1.16.1 fabric (SODIUM) and they work but in 1.16.5(SODIUM) the blocks are invisible(SPECIALLY IN HOLY GL4ES) (AND THAT ISSUE IN PLAYSTORE VERSION) 
note:, i try to use other render (VIRGLRENDER) and the problem is fixed, but the fps reduce from 200 to 50 with alot of drop frame. mean like it be unplayable. 

### The log file and images/videos

![Screenshot_20230923-173928](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78666776/20edf7ac-b404-45aa-a124-6a9e2b0b0bce)
video upload failed

### Steps To Reproduce

```markdown
We have no way to fix this problem in holy render and should to use virglrender, which it was for Shaders and has alot of problems

means you need to update the render i think..
```

### Expected Behavior

i dont have any world to write here. 

### Platform

```markdown
- Device model: Infinix
- CPU architecture: HELio G85
- Android version: 12
- PojavLauncher version: playstore version, dahlia-740-623f7dd33-v3_openjdk
```

**Comment by 0hStormy** [comment]
Sodium doesn't really work on Pojav, usually it either crashes or that happens.
If you need better performance, use OptiFine, because OptiFine works on all the renderers as far as I'm aware.

**Comment by 0hStormy** [comment]
You could maybe try Sodium 4.10, that worked for me on iOS, but your best bet is OptiFine.
