### ISSUE TITLE
[BUG] when i use modpack profile and try to create a world or join a world it crashes

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#4630]
### Describe the bug

application exited with code 1
 

I dont know why it happens everytime i try

### The log file and images/videos

Latest log is here
[Latest log.txt](https://cdn.discordapp.com/attachments/1155042331167313931/1155521423301951548/latestlog.txt) 

### Steps To Reproduce

```markdown
join a world or join a server
```

### Expected Behavior

When i try to join world or server

### Platform

```markdown
- Device model: iqoo z5
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: 1.20.1
```

**Comment by lzfddkd** [comment]
What modpack?

**Comment by lzfddkd** [comment]
Is not all modpacks can run on PojavLauncher

**Comment by aura123lol** [comment]
> What modpack?

Fabulously optimized

**Comment by lzfddkd** [comment]
Try to change renderer?

**Comment by GaucovyAero** [comment]
fabulously optimized doesn't work on gl4es, you have to use zink
if you want more fps, use optifine, maybe with a couple of other performance mods like modernfix and ferritecore
