### ISSUE TITLE
Croedin update

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#4631]

**Comment by Nitin1234556** [comment]
Did you know 
About the uptade is vgpu render coming back ?

**Comment by GaucovyAero** [comment]
> Did you know About the uptade is vgpu render coming back ?

its not coming back, that was a community pull request, it wont be pushed into mainline

**Comment by GaucovyAero** [comment]
crowdin updates come from the community (like you), right now there were big changes of the strings, so a bunch of strings are now left blank, if you are willing to update them, go ahead and do so at https://crowdin.com/project/pojavlauncher
