### ISSUE TITLE
[F-Req] Multiple .minecraft instances

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#4632]
### Is this request related to a bug?

No

### Describe the request.

I want pojav launcher to support multiple .minecraft so for example i can have 1 fabric/forge .minecraft to have sodium and another .minecraft to have different mods like immersive portals.

### Anything else?

Nothing else.

**Comment by GaucovyAero** [comment]
on the play store version, there is currently a bug where forge 1.17+ crashes if you put it in another directory (it will be fixed in the next play store update), but you can make as many fabric folders as you want (just change the directory in the profile settings)
