### ISSUE TITLE
[BUG] Crashes with 1.20.2

### ISSUE THREAD

**Issue by AbdullahTahirEkizler** [PojavLauncherTeam/PojavLauncher#4633]
### Describe the bug

The game doesn't launch and just exists with code -1 my phone is POCO F5 the 12 gb variant any way i could fix the issue? Or is it a bug?

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12709237/latestlog.txt)

### Steps To Reproduce

```markdown
1 Start pojavlauncher
2 Press play with 1.20.2 profile selected
```

### Expected Behavior

The game is supposed start up but the mojang logo doesnt even show up and crashes.

### Platform

```markdown
- Device model: POCO F5 12GB RAM
- CPU architecture: ARM64
- Android version: MIUI 14.0.7
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

### Anything else?

The game was also very unstable on 1.8.9 with optifine and kept crashing

**Comment by GaucovyAero** [comment]
a) to fix 1.20.1 crashing, please update to the latest pojav build on github actions
b) 1.8.9 crashing is all just your issue, make sure you are not allocating too much RAM

**Comment by masoomshado** [comment]
How to update pojav to run 1.20.2. give me tutorial pls i found this everywhere but I can't find anything 😞

**Comment by leahanderson1** [comment]
> How to update pojav to run 1.20.2. give me tutorial pls i found this everywhere but I can't find anything 😞

download latest apk from [here](https://github.com/PojavLauncherTeam/PojavLauncher/actions)
