### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by laitienphat123** [PojavLauncherTeam/PojavLauncher#4635]
### Describe the bug

Tôi vào sever sau đó nó để là đang lưu thế gới xong bị thoát với mã 1 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12715471/latestlog.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12715481/latestlog.txt)

### Steps To Reproduce

```markdown
Tôi khởi động pojavlauncher sau đó thì vào 1 sever sau một hồi thì nó để là đang lưu thế giới và thoát game với mã 1
```

### Expected Behavior

Mn giúp vs

### Platform

```markdown
- Device model: samsung galaxy a12
- CPU architecture: 
- Android version: 13
- PojavLauncher version: 1.18.2
```

### Anything else?

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12715494/latestlog.txt)

**Comment by GaucovyAero** [comment]
patch sodium with this patcher (use java 17 to run it in the jar installer)

https://www.mediafire.com/file/g09xmfa1yfrp1km/sodiumpatcher-1.0.1-SNAPSHOT.jar/file
