### ISSUE TITLE
[F-Req] <About the key position>

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#4636]
### Describe the request.

It is hoped that the key position of the launcher and the adsorption function can have a switch button. Sometimes the adsorption will cause the adjustment of the key position, which becomes very troublesome.
It is desirable to add a two-layer key layout,I want to add a key layout that can be divided and add the function of hiding keys.

**Comment by GaucovyAero** [comment]
a) misaligned is worse than a bit of troublesome setup
b) already can be done via drawers
