### ISSUE TITLE
[BUG] Stroke width and a text on buttons are not scaled properly

### ISSUE THREAD

**Issue by Felix14-v2** [PojavLauncherTeam/PojavLauncher#4638]
### Description

In custom controls, text on buttons and stroke width remains the same at all scale factors, leading to inaccuracy on different screens and even with different scaling defined in settings:

<details>
 <summary>Hotbar buttons</summary>

100%
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/68297c19-4253-4ea3-9675-a08456b8bf62)
250%
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/65eb2150-127e-4e24-922a-5d7b93ec4a6f)

</details>

<details>
 <summary>Joystick</summary>

100%
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/58ca3787-49dc-4779-a256-8a41ed8e8e39)

250%
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/ab2ca606-1a22-404d-a7a0-2f61a3e1d30a)

</details>

### To Reproduce

- Just upscale/downscale your controls and see the difference

### Expected Behavior

All button properties should be scaled correctly, this will improve appearance of your custom controls for other users on different screens. It might be worth adding a separate slider for the text scaling in the launcher settings.

### Anything else?
This is important in cases when the stroke width is a part of your design. For example, the shadow for custom hotbar buttons or "Close" button in my controls:
<details>
 <summary>...</summary>

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/6e2f0535-001f-4cae-8aa9-79bb68c080ff)
</details>

This bug imposes restrictions on the scalability of such elements.

### Implemented
- [x] Stroke scaling
- [ ] Text scaling

**Comment by Mathias-Boulay** [comment]
Text scaling won't be implemented this way as it does not follow accessibility guidelines.
