### ISSUE TITLE
The mouse arrow is not aligned

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#464]
![Screenshot_20201206-213221](https://user-images.githubusercontent.com/38146322/101299089-86abc100-380f-11eb-9e81-73e1055e704c.png)
Forge 1.12.2 work perfectly, but the mouse arrow is not aligned with the buttons 
(Pojav 3.3)

**Comment by ghost** [comment]
it same but touch doesn't work either

**Comment by khanhduytran0** [comment]
Use this build

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/405706349

**Comment by khanhduytran0** [comment]
Duplicate #457 also

**Comment by ghost** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/405706349

zip bagged dont opening

**Comment by khanhduytran0** [comment]
Try download app-debug-noruntime one.
