### ISSUE TITLE
Some strings are not localizable

### ISSUE THREAD

**Issue by GaucovyAero** [PojavLauncherTeam/PojavLauncher#4640]
### Describe the bug

Headings in menus can't be translated yet.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/4b486960-d00c-43d8-a96e-aea3b2fc9aae

### Steps To Reproduce

```markdown
1. Set a different language in your Android settings
2. Open Pojav and click on any tab in the settings
```

### Expected Behavior

All strings should be localizable.

### Platform

```markdown
- Device model: Xiaomi Poco F3 8/256G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230927-5d010fc-v3_openjdk
```

### Anything else?

nope

**Comment by MovTery** [comment]
Because they're written directly into the code, just like what's framed in this picture.
↓
![IMG_20230928_090231.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/123115192/8df26dd5-2a2c-4037-9229-f2e863d9a3b9)

**Comment by GaucovyAero** [comment]
> Because they're written directly into the code, just like what's framed in this picture.

obviously, but this is a known issue and should be fixed soon according to what ive heard

**Comment by Mathias-Boulay** [comment]
strings are made translatable from the latest v3_openjdk build
