### ISSUE TITLE
[BUG]  Modpack is not launching

### ISSUE THREAD

**Issue by SajoPlejer** [PojavLauncherTeam/PojavLauncher#4641]
### Describe the bug

Before update modpack launched.
I saw some problem with LWGJ in log.
Modpack: Nomifactory CEu downloaded in modpack manager inside application 

### The log file and images/videos

Log:
https://drive.google.com/file/d/1Fs2P8p_hmCullqYZLGCcGwZDGWl6Z2AC/view?usp=drivesdk

### Steps To Reproduce

```markdown
1 Start Modpack Nomifactory downloaded in app
2 Wait
3 Game crash
```

### Expected Behavior

I expect to load to main menu.

### Platform

```markdown
- Device model: Poco X3 Pro 
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: edelweiss-20230927-5d010fc-v3_openjdk
```

**Comment by GaucovyAero** [comment]
#1948 (list it as Avaritia mod)
