### ISSUE TITLE
Xray glitch

### ISSUE THREAD

**Issue by MustafaMokhtar** [PojavLauncherTeam/PojavLauncher#4642]
### Describe the bug

When i log in 1.16.5 it gives me some kind of xray vision glitch i can see thru trees and everything i used to enable Fullscreen in older versions to fix the bug but now whenever i try to enable Fullscreen it doesn't work 

### The log file and images/videos

..

### Steps To Reproduce

```markdown
1.launch pojav launcher
2.lanuch Minecraft 1.16.5
```

### Expected Behavior

I expected it to launch normally 

### Platform

```markdown
- Device model: realme 5 pro 8g ram
- CPU architecture: 2x 2.3 GHz – Kryo 360 Gold (Cortex-A75)
- Android version: 11
- PojavLauncher version: edelweiss
```

### Anything else?

Nothing else

**Comment by GaucovyAero** [comment]
known issue, press f11

**Comment by MustafaMokhtar** [comment]
> known issue, press f11

Tried doesn't work

**Comment by MustafaMokhtar** [comment]
Will some kind of visual information help you?
I can comment some pictures

**Comment by MustafaMokhtar** [comment]
Oh yes i need to also mention that this bug happens when i install the mod Immersive engineering or ender storage

**Comment by GaucovyAero** [comment]
> Oh yes i need to also mention that this bug happens when i install the mod Immersive engineering or ender storage

#1948

**Comment by KavalackalDistributors** [comment]
When I open any server I can't move and x ray glitch pls reply
