### ISSUE TITLE
no, pretty sure there are guides on the pojav discord on how to do it, you have to edit the apk to use a different cursor image

### ISSUE THREAD

**Issue by Nitin1234556** [PojavLauncherTeam/PojavLauncher#4646]
no, pretty sure there are guides on the pojav discord on how to do it, you have to edit the apk to use a different cursor image

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/4643#issuecomment-1739722935_
            I am ban from pojav because of offering one player minecraft account so can u tell me here

**Comment by Nitin1234556** [comment]
And u don't tell that how to use vulkan mod

**Comment by GaucovyAero** [comment]
heres the custom cursor guide
https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/40b309d3-67e9-47ba-aafc-868cd4d701de

heres vulkanmod
https://www.mediafire.com/folder/xsb4udjs7n8z9/VulkanMod_for_PojavLauncher
