### ISSUE TITLE
Please make the English language normally

### ISSUE THREAD

**Issue by D9074** [PojavLauncherTeam/PojavLauncher#4647]
### Describe the bug

Please make the English language normally. I uptaded Pojavlauncher and the English is not perfect. It's the pirate language and I don't want that. Please turn it back to normal English. Thanks

### The log file and images/videos

I tried to put screenshots but github won't let me

### Steps To Reproduce

```markdown
1. Just change the language to english
You will see the English is not normal. In the main menu the Play button isnt texted Play. It was texted SAIL. Like what the?????
```

### Expected Behavior

-

### Platform

```markdown
- Device model: samsung galaxy a13
- CPU architecture: Malo
- Android version: 12
- PojavLauncher version: latest Google play versikn
```

**Comment by GaucovyAero** [comment]
your phone prefers to use pirate speak instead of english, we already removed pirate speak from the languages on the latest github actions build, another play store update to fix that will be released soon
