### ISSUE TITLE
[F-Req] add back 1.7+ renderer

### ISSUE THREAD

**Issue by Adrian647PH** [PojavLauncherTeam/PojavLauncher#4648]
### Is this request related to a bug?

Add back 1.7+ renderer for old version modpacks to renderer. Because Renderer "Holy GL4ES" not renderer other old modpacks

### Describe the request.

Put/bring back 1.7+ renderer

**Comment by artdeell** [comment]
just use zink

**Comment by Adrian647PH** [comment]
.

> just use zink

It crashes when using zink

**Comment by Adrian647PH** [comment]
> just use zink

Because its zink renderer is not supported for the old modpacks

**Comment by GaucovyAero** [comment]
zink supports basically everything that comes to mind, other than devices with powervr gpus and old adreno

**Comment by GaucovyAero** [comment]
if you really need virglrenderer (keep in mind a loooot of people have had issues with it) just download and use an older pojav build
