### ISSUE TITLE
Angle still does not allow taking screenshots in the Edelweiss build

### ISSUE THREAD

**Issue by Renegade4339** [PojavLauncherTeam/PojavLauncher#4649]
### Describe the bug

In the Edelweiss build, its ANGLE renderer still doesn't make screenshots properly. Its output can be seen in the images/videos section.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12753027/latestlog.txt)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/90155229/2297825e-e076-4c48-bd6d-c3cd5a7308e4

The output in question:
![2023-09-29_02 51 59](https://github.com/PojavLauncherTeam/PojavLauncher/assets/90155229/80609fde-c4a5-4bde-8907-4fe1b340a94b)

### Steps To Reproduce

```markdown
1. Start Minecraft in any version with ANGLE renderer
2. Take a screenshot
3. Go to the screenshots folder
```

### Expected Behavior

Should make an output properly and not a purely black screen.

### Platform

```markdown
- Device model: Infinix HOT 30i
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Latest (stable) release (edelweiss-20230927-5d010fc-v3_openjdk)
```

**Comment by artdeell** [comment]
Fix not planned.

чт, 28 сент. 2023 г., 22:06 Renegade4339 ***@***.***>:

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230927 - v3_openjdk |
| Minecraft version | fabric-loader-0.14.22-1.20.1 - FABRIC |
| Renderer | ANGLE |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 17 |
| Java arguments |  |



|Errors Found: |
|--|
| libgles.wrong.value |
