### ISSUE TITLE
OneConfig still doesn't work (NanoVG)

### ISSUE THREAD

**Issue by GaucovyAero** [PojavLauncherTeam/PojavLauncher#4650]
### Describe the bug

```
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.nanovg.NanoVGGL2
	at cc.polyfrost.oneconfig.internal.renderer.NanoVGHelperImpl.setupAndDraw(NanoVGHelperImpl.java:107)
	at cc.polyfrost.oneconfig.internal.renderer.NanoVGHelperImpl.setupAndDraw(NanoVGHelperImpl.java:94)
        ...
```

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12753462/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install a mod that uses OneConfig (e. g. OverflowAnimationsV2)
2. Press RSHIFT (you will get a white screen), then ESC and the game will crash.
```

### Expected Behavior

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/1cf72b95-60f6-4800-b36b-e3f2f51c0ade)

### Platform

```markdown
- Device model: Xiaomi Poco F3 8/256G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: dahlia-20230815-919a6a4-v3_openjdk (in the log, outdated)
```

**Comment by alexytomi** [comment]
I can recreate it by using optifine's antialiasing option on PC but without the crash. Maybe its the 4x MSAA on android?

**Comment by GaucovyAero** [comment]
will be fixed on their side soon

**Comment by alexytomi** [comment]
> will be fixed on their side soon

It's been fixed for a while now..for zink only at least. HolyGL4ES is gonna take till the next major update is out ("codenamed" twoconfig as a joke) to not crash when GUI is rendered, still works as a library mod.
