### ISSUE TITLE
I hope to include an analysis of the cause of the crash

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#4653]
### Describe the request.

I hope to include an analysis of the cause of the crash,like FoldCarftLauncher. www.github.com/FCL-TEAM/FoldCraftLauncher

**Comment by lzfddkd** [comment]
www.github.com/FCL-Team/FoldCraftLauncher

**Comment by GaucovyAero** [comment]
no
