### ISSUE TITLE
[BUG] <Game crash when press start in the launcher>

### ISSUE THREAD

**Issue by GameboyVlol** [PojavLauncherTeam/PojavLauncher#4656]
### Describe the bug

Game exited with code -1

### The log file and images/videos

[latestlog 2.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12769277/latestlog.2.txt)

### Steps To Reproduce

```markdown
1. Open SideStore
2. Enable JIT
3. Start pojav
4. press start button in launcher
5. Crash
```

### Expected Behavior

I expect the game to launch

### Platform

```markdown
- Device model: IPad Air 4
- CPU architecture: A14 bionic
- IOS version: 16
- PojavLauncher version: 2.2
```

**Comment by GaucovyAero** [comment]
ios issues belong to PojavLauncherTeam/PojavLauncher_iOS repository
