### ISSUE TITLE
Lunar client crash....

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#4661]
### Describe the bug

I just run 1.8.9 and crash I tried 8 and 17 java and crash like Let's fix this 

### The log file and images/videos

UwU

### Steps To Reproduce

```markdown
I launch the Lunar client and after a second it crashes
```

### Expected Behavior

Doesn't crash

### Platform

```markdown
- teclast t40 pro: 
- idk: 
- 12 
- Latest beta from github
```

**Comment by MegaFaresX** [comment]
Lunar Client is Unsupoorted....

**Comment by sa1672ndo** [comment]
also "uwu" is not a log file.

**Comment by GaucovyAero** [comment]
Lunar Client is closed source and has its own PC launcher. Lunar Client JARs are unofficial and could be stealing your session, etc. If it doesn't work, it doesn't work.
