### ISSUE TITLE
[BUG] 1.20.1 Forge Crash by unsupported jave to mod

### ISSUE THREAD

**Issue by RimakiTaema** [PojavLauncherTeam/PojavLauncher#4662]
### Describe the bug

when you install mod call solar flux reborn
I check curseforge info it has problem if you use java 17 it will crash instantly but i need to play it did you have solutions or way to fix it

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12776048/latest.log)

### Steps To Reproduce

```markdown
Install forge
Install mod solar flux reborn
Use java 17
Then crash on launch
```

### Expected Behavior

Game launch normaly with mod installed

### Platform

```markdown
- Device model: Redmi Note 10/128G
- CPU architecture: Arm64-v8a armabi armabi-v7a
- Android version: 12
- PojavLauncher version: edelweiss || 20232908
- Rom: Mi 14.0.3
```

**Comment by GaucovyAero** [comment]
your installation of jei needs forge 48 or higher
