### ISSUE TITLE
[BUG] Forge 1.5.2/1.6.4 not launching/crashing before startup

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#4665]
### Describe the bug

Whenever i try to launch forge on version 1.6.4 or 1.5.2 it crashes.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12777594/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. add new version profile
3. add forge profile
4. add forge 1.5.2 (latest version)
5. launch forge 1.5.2
6. crash

(Same issue on 1.6.4 forge)
```

### Expected Behavior

Forge 1.5.2 launches and is playable

### Platform

```markdown
- Device model: Oppo A77 (CPH2339)
- CPU architecture: Dimensity 810 Octa Core
- Android version: 13
- PojavLauncher version: "Edelweiss" Release (Google Play version)
```

**Comment by GaucovyAero** [comment]
you have to use java 8

if you want forge 1.6.4...965 and lower, you will need the legacy java fixer mod, grab that from https://mcarchive.net/
you may also need to put `-Dfml.ignoreInvalidMinecraftCertificates=true` into your JVM arguments if the log tells you to do so
Lumy Skin Patch mod is recommended

if you want forge 1.5.2, grab fmllibs152.zip from https://mcarchive.net./ from the minecraft forge tab and put the jar files into .minecraft/lib
if you are on 1.5.2 and lower, be sure to put `-Dhttp.proxyHost=betacraft.uk -Djava.util.Arrays.useLegacyMergeSort=true` into your JVM arguments to get skins and sounds, but you may also need Lumy Skin Patch for the skins to work properly

**Comment by Accountuser99** [comment]
There is no lib folder and i've tried java 8 (same result)

**Comment by GaucovyAero** [comment]
> There is no lib folder and i've tried java 8 (same result)

you have to create the folder, send log with java 8

**Comment by Accountuser99** [comment]
I got it to work but there is now no audio

**Comment by Accountuser99** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/4666

**Comment by GaucovyAero** [comment]
> I got it to work but there is now no audio

make sure you have the betacraft proxy set, you can try pressing F3 + S in-game to see if that fixes the issue, but iirc some person on the pojav discord server fixed it by downloading the resources manually from here https://archive.org/details/CompleteMinecraftResourcesFolder2014
the resources go into .minecraft/resources

**Comment by GaucovyAero** [comment]
fixed by removing betacraft proxy
