### ISSUE TITLE
[BUG] Forge 1.5.2 No Audio

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#4666]
### Describe the bug

Even with the JVM there is still no in game audio

-Dhttp.proxyHost=betacraft.uk -Djava.util.Arrays.useLegacyMergeSort=true

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12777840/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Download Forge 1.5.2
3. Download fmllib and extract to .Minecraft folder
4. Add -Dhttp.proxyHost=betacraft.uk -Djava.util.Arrays.useLegacyMergeSort=true to JVM
5. Launch forge 1.5.2
6. No Audio
```

### Expected Behavior

Game has sound

### Platform

```markdown
- Device model: CPH2339
- CPU architecture: Dimensity 810 Octa Core
- Android version: 13
- PojavLauncher version: Latest Google Play Build
```

**Comment by GaucovyAero** [comment]
(copied over from #4665) make sure you have the betacraft proxy set, you can try pressing F3 + S in-game to see if that fixes the issue, but iirc some person on the pojav discord server fixed it by downloading the resources manually from here https://archive.org/details/CompleteMinecraftResourcesFolder2014
the resources go into .minecraft/resources

**Comment by Accountuser99** [comment]
> (copied over from #4665) make sure you have the betacraft proxy set, you can try pressing F3 + S in-game to see if that fixes the issue, but iirc some person on the pojav discord server fixed it by downloading the resources manually from here https://archive.org/details/CompleteMinecraftResourcesFolder2014 the resources go into .minecraft/resources

Removed the proxy JVM and now it works.

**Comment by GaucovyAero** [comment]
> > (copied over from #4665) make sure you have the betacraft proxy set, you can try pressing F3 + S in-game to see if that fixes the issue, but iirc some person on the pojav discord server fixed it by downloading the resources manually from here https://archive.org/details/CompleteMinecraftResourcesFolder2014 the resources go into .minecraft/resources
> 
> Removed the proxy JVM and now it works.

alr nice
