### ISSUE TITLE
[BUG] 1.6.4 forge no audio

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#4667]
### Describe the bug

Forge for 1.6.4 has no audio, tried multiple ways to fix wonder if there are any ways I haven't tried.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12778385/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2.Launch forge 1.6.4-9...1345
3.No audio
```

### Expected Behavior

Game audio

### Platform

```markdown
- Device model: Oppo A77 5G/64GB
- CPU architecture: Dimensity 810 Octa Core
- Android version: 13
- PojavLauncher version: Latest Google Play build
```

**Comment by Accountuser99** [comment]
Please help :(

**Comment by GaucovyAero** [comment]
how about F3 + S ?

**Comment by GaucovyAero** [comment]
oh, well i searched on the internet and it seems like the fix is to use the old minecraft launcher (on PC), i guess this has to be fixed so that pojav can actually download the old assets

**Comment by GaucovyAero** [comment]
in the meantime, heres a 1.6.4 modpack folder that has the whole assets folder in it, try copying assets over to your .minecraft folder https://www.mediafire.com/file/l180s9g3c5ywb55/.minecraft.zip/file

**Comment by Mathias-Boulay** [comment]
It should be fixed with the latest v3_openjdk dev build, that I just pushed

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
