### ISSUE TITLE
s23U Dex loads grey screen after pressing play

### ISSUE THREAD

**Issue by TomLewis** [PojavLauncherTeam/PojavLauncher#4668]
### Describe the bug

Hi!

First time using the launcher! I can get I name fine on my phone but as soon as I try to load in Dex for Samsung I just get a gray screen, any ideas how to fix this? This is the log

### The log file and images/videos

https://gist.github.com/TomLewis/a3a597be75ee03265b4c10c044da7aa8

### Steps To Reproduce

```markdown
1. Plug Samsung phone into hdmi Dex opens
2. Start launcher
3. Gray screen
```

### Expected Behavior

To not gray screen 

### Platform

```markdown
- Device model: s23U
- CPU architecture: 
- Android version: 
- PojavLauncher version: latest
```

**Comment by artdeell** [comment]
Some questions first:
- Are you loading it in full screen mode?
- Do the controls show up?

**Comment by TomLewis** [comment]
Oh my god, if I click the maximise button before I press play, it works? Ha! what an easy fix!
