### ISSUE TITLE
Rise Cracked not working

### ISSUE THREAD

**Issue by ilikehotpotateos** [PojavLauncherTeam/PojavLauncher#4669]
### Describe the bug

Crashes when I enter in a game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12784189/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start rise 6 cracked
2. Get in a single player world
```

### Expected Behavior

I expected rise to crash.

### Platform

```markdown
- Device model: pixel 6
- CPU architecture: arm64-v8a armeabi-v7a armeabi
- Android version: 13
- PojavLauncher version: latest
```

**Comment by ilikehotpotateos** [comment]
Oh and I'll send the video #

**Comment by ilikehotpotateos** [comment]
Oh and sorry to bring in hacking

**Comment by GaucovyAero** [comment]
discordrpc doesnt work on android/ios, only on pc, try communicating with the rise client devs so that they can make an option to turn it off or make it so that the game doesnt crash if the library doesnt get loaded

**Comment by ilikehotpotateos** [comment]
Thanks for the information.

**Comment by VenomousSteam81** [comment]
At least you said you were using cracked, unlike a lot of people. I will give you that.
