### ISSUE TITLE
Cant join aternos servers

### ISSUE THREAD

**Issue by manfromfms** [PojavLauncherTeam/PojavLauncher#467]
I cant join any aternos server. I used 1.15.2 and 20w49a, and no version worked. But i can join any other server.
Issuse: connection timed out

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by khanhduytran0** [comment]
Also, if you have access, please check server log when you attempt to join.

**Comment by pstube** [comment]
Try connecting using ip

**Comment by Harsh-bot-beep** [comment]
It's fixed now close it
