### ISSUE TITLE
Application/game exited with code 1

### ISSUE THREAD

**Issue by Immortal-Lotus** [PojavLauncherTeam/PojavLauncher#4670]
### Describe the bug

The game Crashes whenever I try to play Sevtech Ages modpack on 1.12.2.
I have no idea what's latestlog.txt is saying. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12788710/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Log In
3. Launch Sevtech Ages modpack
4. Wait
```

### Expected Behavior

It was expected the game to open as normaly, just as it was doing in older versions

### Platform

```markdown
- Device model: Poco X3 NFC / 64GB
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Version edelweiss-20231001-d8ed111-in_app_file_manager
```

**Comment by hiimabignoobwihenolive** [comment]
Modpacks generally don't work cuz theres some mods don't work in them

**Comment by Immortal-Lotus** [comment]
> Modpacks generally don't work cuz theres some mods don't work in them

What mod that's not work in my Sevtech Ages modpack? 
And, this is my crash report 
[crash-2023-10-03_07.48.25-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12792514/crash-2023-10-03_07.48.25-client.txt)

**Comment by GaucovyAero** [comment]
> > Modpacks generally don't work cuz theres some mods don't work in them
> 
> What mod that's not work in my Sevtech Ages modpack? And, this is my crash report [crash-2023-10-03_07.48.25-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12792514/crash-2023-10-03_07.48.25-client.txt)

you are out of memory
```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(Unknown Source)
	at java.util.HashMap.putVal(Unknown Source)
```

**Comment by Immortal-Lotus** [comment]
> > > Modpacks generally don't work cuz theres some mods don't work in them
> > 
> > 
> > What mod that's not work in my Sevtech Ages modpack? And, this is my crash report [crash-2023-10-03_07.48.25-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12792514/crash-2023-10-03_07.48.25-client.txt)
> 
> you are out of memory
> 
> ```
> Caused by: java.lang.OutOfMemoryError: Java heap space
> 	at java.util.HashMap.resize(Unknown Source)
> 	at java.util.HashMap.putVal(Unknown Source)
> ```

How can I play Sevtech Ages modpack? I really want to play it.

**Comment by Bel69420** [comment]
Increase your ram allocation, your ram allocation is too low to run this modpack

**Comment by Bel69420** [comment]
Like 3000MB

**Comment by Bel69420** [comment]
3500MB should be enough

**Comment by Immortal-Lotus** [comment]
> 3500MB should be enough

Still can't play it. Any recommendations modpack like Sevtech Ages?

**Comment by GaucovyAero** [comment]
nope, closing as resolved
