### ISSUE TITLE
Sigma 5.0

### ISSUE THREAD

**Issue by ilikehotpotateos** [PojavLauncherTeam/PojavLauncher#4671]
### Describe the bug

When I launch Sigma 5.0 the screen is all black and no it isn't discordrpc I checked

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/144628083/ca5216dc-bd3f-4a7b-9cff-20d799dcd104

### Steps To Reproduce

```markdown
1. Launch Sigma 5.0
```

### Expected Behavior

I expected to be all black

### Platform

```markdown
- Device model: pixel 6
- CPU architecture: arm64-v8a armeabi-v7a armeabi
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

Nah

**Comment by GaucovyAero** [comment]
send log

**Comment by ilikehotpotateos** [comment]
I lost the log it got deleted ._.

**Comment by GaucovyAero** [comment]
> I lost the log it got deleted ._.

crash it again then

**Comment by GaucovyAero** [comment]
closing as a stale issue
