### ISSUE TITLE
[BUG] Optifine crash

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4672]
### Describe the bug

as I play suvival on optifine it randomly crashes 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12790480/latestlog.txt)

### Steps To Reproduce

```markdown
1 open a survival world in optifine on a chromebook
```

### Expected Behavior

It crashes

### Platform

```markdown
I'm not sure about these
```

### Anything else?

N/A

**Comment by ilikehotpotateos** [comment]
model?

**Comment by ilikehotpotateos** [comment]
of Chromebook

**Comment by ghost** [comment]
Acer Spin 311

**Comment by hiimabignoobwihenolive** [comment]
Thats a another reason too not get a chrome book

**Comment by VenomousSteam81** [comment]
First, try removing all the custom java arguments, especially the `-Xmx2G` because pojav has a built-in ram allocation slider. Next, try [pojavoptimize](https://www.mediafire.com/folder/6p1xqhmmihf7x/PojavOptimize). It uses fabric and helps speed the game up a lot more.

**Comment by VenomousSteam81** [comment]
Also, why get a chromebook? These things are ass unless you pay a lot of money, where at that point you might as well get an actual laptop instead of a chromebook.

**Comment by GaucovyAero** [comment]
how much ram are you allocating?

**Comment by ghost** [comment]
> how much ram are you allocating?

1948 mb

**Comment by ghost** [comment]
> Also, why get a chromebook? These things are ass unless you pay a lot of money, where at that point you might as well get an actual laptop instead of a chromebook.

It's what my parents bought me

**Comment by GaucovyAero** [comment]
try 900MB

**Comment by ghost** [comment]
Thank you so much it worked!!
