### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Looksc** [PojavLauncherTeam/PojavLauncher#4673]
### Is this request related to a bug?

Embiddium work with pojav launcher 1.16.5?

**Comment by GaucovyAero** [comment]
i have no idea what that is, google yielded no search results

**Comment by Looksc** [comment]
> i have no idea what that is, google yielded no search results

https://www.curseforge.com/minecraft/mc-mods/embeddium 

This

**Comment by SolDev69** [comment]
Use Zink renderer.

**Comment by GaucovyAero** [comment]
yeah, either use zink or deal with it and dont use that mod, you are better off with gl4es renderer + optifine if it works with your mods
