### ISSUE TITLE
[BUG] <black screen 1.12.2 forge

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4675]
### Describe the bug

I installed a few mods and they worked but optifine would break the game it broke everything made the ui white and i removed it and it started to black screen after the loading screen finished

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12792823/latest.log)

### Steps To Reproduce

```markdown
Press play 
Loading screen appears
Black screen
```

### Expected Behavior

I expected to have a fun time

### Platform

```markdown
- Device model: honor x6
- CPU architecture: heilo g25 (yes)
- Android version: 12
- PojavLauncher version: zink but swap chain based
```

### Anything else?

i can hear the game music
And also theres an error in logs called invalid framebuffer

**Comment by GaucovyAero** [comment]
you have a mod thats causing a bunch of gl errors

**Comment by hiimabignoobwihenolive** [comment]
But i don't know why it worked with optifine tho 
This shit is scuffed

**Comment by hiimabignoobwihenolive** [comment]
Well it turns out that lib mods can cause fucking issues it makes more issues than they fucking fix it

**Comment by GaucovyAero** [comment]
ok lol
