### ISSUE TITLE
[BUG] Crash on immersive portals and optifabric

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#4677]
### Describe the bug

So my phone only supports zink to run immersive portals and its a bit laggy without any performance mods so i put optifabric (because sodium sucks on pojav) and optifine is better for me and in the first few seconds it crashee

### The log file and images/videos

Here is [my log file.](https://github.com/PojavLauncherTeam/PojavLauncher/files/12795025/latestlog-1.txt)

### Steps To Reproduce

```markdown
1- start pojav
2- install optifabric and immersive portals (i also installed optifine for optifabric to work)
3- launch fabric
4. crash
```

### Expected Behavior

I expected the game to open

### Platform

```markdown
- Device model: Techno Spark 8 pro
- CPU architecture: 64 bit
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

Nothing just i need prefirmance mods bc my phone sucks with vanilla minecraft no optifine.

**Comment by Bel69420** [comment]
Zink runs slower on Mediatek Helio (excluded Dimensity) and Snapdragon

**Comment by GaucovyAero** [comment]
```
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
```
you have jvm arguments that dont work on pojav

**Comment by VenomousSteam81** [comment]
I don't even know if immersive portals mod works on Pojav.

**Comment by Bel69420** [comment]
It is work, but there's a graphic issue with zink
