### ISSUE TITLE
[F-Req] Allow joystick on-screen control to look around as well as move

### ISSUE THREAD

**Issue by Nibroc-64** [PojavLauncherTeam/PojavLauncher#4679]
### Describe the request.

The current controls of "swipe to look around" work for the most part, but it would be good to be able to configure the on-screen joystick control to look around as well. It could also be useful if the joystick could be changed to other buttons as well.

### Anything else?

Apologies if this is a little short for a feature request, I'm not sure how detailed I need to go with these, and there's not much more to say about it anyway.

**Comment by VenomousSteam81** [comment]
I understand and this would be cool, however idk if it will be added or not.

**Comment by GaucovyAero** [comment]
will not be added as your gameplay will generally be worse/slower if you would play like that

you can just create a dummy button with mouse look for similar behavior i think

**Comment by Nibroc-64** [comment]
Can i ask how it would be slower/worse? As the intention was that it would be similar to using a controller, and it is completely possible to play well with one.
Aditionally, what do you mean by the second one? There doesn't appear to be anything to do with moving the mouse in the button mapping settings, so i'm either misunderstanding, or that's not a thing.
