### ISSUE TITLE
[F-Req] <About the key>

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#4682]
### Describe the request.

Using the original cross key, I sometimes inadvertently scratched my finger out of the key,Although when the mouse is floating,The key continues to activate,But it is very difficult to move at this time,
I hope the team can add a better cross key control

**Comment by artdeell** [comment]
Send a video of reproducing it

ср, 4 окт. 2023 г., 08:59 bsjssjjs ***@***.***>:

**Comment by GaucovyAero** [comment]
stale issue, closing
