### ISSUE TITLE
[BUG] <Forge 1.2.5>

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#4683]
### Describe the bug

When I launched Forge 1.2.5 I rebooted from Forge 1.2.5 to vanilla Minecraft 1.2.4 

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Samsung Galaxy A52 
- CPU architecture: 
- Android version: 13
- PojavLauncher version: Latest version of pojavlauncher
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by Prostop194** [comment]
--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.2.5
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2344
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~xz9zpJ3WPgrm4jkyD0P4bA==/net.kdt.pojavlaunch-4UPmjL2SNYKh5otdU_0oVA==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~xz9zpJ3WPgrm4jkyD0P4bA==/net.kdt.pojavlaunch-4UPmjL2SNYKh5otdU_0oVA==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/LIBGL   (11172): Initialising gl4es
I/LIBGL   (11172): v1.1.4 built on Mar 11 2023 20:15:08
I/LIBGL   (11172): Using GLES 2.0 backend
I/LIBGL   (11172): loaded: libGLESv2.so
I/LIBGL   (11172): loaded: libEGL.so
I/LIBGL   (11172): Using GLES 2.0 backend

I/LIBGL   (11172): Hardware Full NPOT detected and used
I/LIBGL   (11172): FBO are in core, and so used
I/LIBGL   (11172): PointSprite are in core, and so used
I/LIBGL   (11172): CubeMap are in core, and so used
I/LIBGL   (11172): BlendColor is in core, and so used
I/LIBGL   (11172): Blend Substract is in core, and so used
I/LIBGL   (11172): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (11172): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (11172): Extension GL_OES_element_index_uint  detected and used

I/LIBGL   (11172): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (11172): Extension GL_OES_depth24  detected and used
I/LIBGL   (11172): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (11172): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (11172): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (11172): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (11172): Extension GL_OES_texture_float  detected and used
I/LIBGL   (11172): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (11172): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (11172): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (11172): high precision float in fragment shader available and used

I/LIBGL   (11172): Max vertex attrib: 32
I/LIBGL   (11172): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (11172): Max texture size: 16384
I/LIBGL   (11172): Max Varying Vector: 31
I/LIBGL   (11172): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (11172): Extension GL_EXT_texture_filter_anisotropic  detected and used

I/LIBGL   (11172): Max Anisotropic filtering: 16
I/LIBGL   (11172): Hardware vendor is Qualcomm

I/LIBGL   (11172): GLSL 300 es supported
I/LIBGL   (11172): GLSL 310 es supported and used
I/LIBGL   (11172): GLSL 320 es supported
I/LIBGL   (11172): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   (11172): sRGB surface supported
I/LIBGL   (11172): EGLImage to Texture2D supported
I/LIBGL   (11172): EGLImage to RenderBuffer supported

I/LIBGL   (11172): ignore MipMap
I/LIBGL   (11172): Targeting OpenGL 2.1
I/LIBGL   (11172): No hack in shader converter to define overloaded function with int
I/LIBGL   (11172): NPOT texture handled in hardware
I/LIBGL   (11172): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (11172): try to use VBO
I/LIBGL   (11172): glX Will try to recycle EGL Surface
I/LIBGL   (11172): Current folder is:/
I/jrelog  (11172): dlopen libgl4es_114.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (11172): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success

I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (11172): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (11172): dlopen /data/app/~~xz9zpJ3WPgrm4jkyD0P4bA==/net.kdt.pojavlaunch-4UPmjL2SNYKh5otdU_0oVA==/lib/arm64/libopenal.so success

I/jrelog  (11172): Done processing args
I/jrelog  (11172): Found JLI lib
I/jrelog  (11172): Calling JLI_Launch

OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
окт 04, 2023 7:12:43 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using tweak class name net.minecraft.launchwrapper.VanillaTweaker
окт 04, 2023 7:12:43 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Launching wrapped minecraft
CacioComponentPeer::setZOrder: NOT YET IMPLEMENTED

27 achievements

182 recipes

Turning of ImageIO disk-caching

Loading current icons for window from: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets/icons/icon_16x16.png and /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets/icons/icon_32x32.png

javax.imageio.IIOException: Can't read input file!

	at javax.imageio.ImageIO.read(Unknown Source)

	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.loadIcon(VanillaTweakInjector.java:130)

	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.loadIconsOnFrames(VanillaTweakInjector.java:107)

	at net.minecraft.launchwrapper.injector.VanillaTweakInjector.inject(VanillaTweakInjector.java:94)

	at net.minecraft.client.Minecraft.main(SourceFile:2136)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

Setting gameDir to: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft

Registered forkAndExec
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.

[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.

[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.

LWJGLX: GL caps init

LWJGL Version: 3.2.3 SNAPSHOT

EGLBridge: Binding to OpenGL ES
LWJGLX: ready-handle context created

Grab: false

I/LIBGL   (11172): version string: (null)

I/LIBGL   (11172): version string: (null)

I/LIBGL   (11172): version string: (null)
I/LIBGL   (11172): version string: (null)


Starting up SoundSystem...

Initializing LWJGL OpenAL

    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)

[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
OpenAL initialized.


I/NativeInput(11172): Input ready: 1

I/LIBGL   (11172): version string: (null)
I/LIBGL   (11172): version string: (null)

Failed to add READ_ME_I_AM_VERY_IMPORTANT

Failed to add pack.mcmeta

java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at java.net.URL.openStream(Unknown Source)

	at ck.run(SourceFile:28)

Stopping!


SoundSystem shutting down...

Error in class 'SoundSystem'

    Problem during Library.cleanup()!
Ignoring errors... continuing clean-up.
    Author: Paul Lamb, www.paulscode.com

**Comment by GaucovyAero** [comment]
update to the latest play store build, also, whats even the issue?

**Comment by Prostop194** [comment]
I updated

**Comment by Prostop194** [comment]
my problem is when i launch forge 1.2.5 forge resets and vanilla minecraft is installed

**Comment by GaucovyAero** [comment]
> my problem is when i launch forge 1.2.5 forge resets and vanilla minecraft is installed

using the builtin installer wont work for jarmods yet

![Screenshot_20231004-224503_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/1e3c58e5-07c8-41a6-957f-9617e64b7cb7)

**Comment by GaucovyAero** [comment]
install forge 1.2.5 by following the custom mc guide on the pojav wiki, but be sure to use mixplorer 6.58.5 and not older or newer

**Comment by Prostop194** [comment]
> установите forge 1.2.5, следуя пользовательскому руководству mc на вики pojav, но обязательно используйте mixplorer 6.58.5, а не более старую или новее.

when switching from the wiki to the blue link, the error is 404, I read the notes but didn’t understand anything

**Comment by GaucovyAero** [comment]
> > установите forge 1.2.5, следуя пользовательскому руководству mc на вики pojav, но обязательно используйте mixplorer 6.58.5, а не более старую или новее.
> 
> when switching from the wiki to the blue link, the error is 404, I read the notes but didn’t understand anything

links are all ok, this is the wiki link https://pojavlauncherteam.github.io/CUSTOM-MC.html

**Comment by Prostop194** [comment]
![Screenshot_20231005_230648_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/6037185c-4cfe-4f2e-8054-cd825e594c60)
I was able to install Forge 1.2.5 but I have no sound in the game

**Comment by Prostop194** [comment]
![Screenshot_20231005_234005_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/7d858931-4535-472f-aba3-f8bf0ae1fa39)
Decided  I installed the cameracraft mod and then endless loading

**Comment by GaucovyAero** [comment]
> ![Screenshot_20231005_234005_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/121510853/272994801-7d858931-4535-472f-aba3-f8bf0ae1fa39.jpg) Regil I installed the cameracraft mod and then endless loading

send log (but please the file not the insides of it)

**Comment by Prostop194** [comment]
> > ![Screenshot_20231005_234005_PojavLauncher (Minecraft Java Edition для Android)](https://user-images.githubusercontent.com/121510853/272994801-7d858931-4535-472f-aba3-f8bf0ae1fa39.jpg)Регил я установил мод cameracraft и дальше бесконечная загрузка
> 
> отправьте журнал (но, пожалуйста, файл, а не его содержимое)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12821562/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.2.5forge - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| forge.install.corrupted |

**Comment by GaucovyAero** [comment]
you have a very old version of forge 1.2.5 installed, try installing the latest .171 for 1.2.5

**Comment by Prostop194** [comment]
> у вас установлена ​​очень старая версия forge 1.2.5, попробуйте установить последнюю версию .171 для 1.2.5

I installed a newer version of forge to 1.2.5

**Comment by Prostop194** [comment]
but there is no sound in the game

**Comment by Prostop194** [comment]
and when I installed the "cameracraft" mod and the same endless loading

**Comment by Prostop194** [comment]
Here 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12826584/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.2.5forge - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| forge.install.corrupted |

**Comment by Prostop194** [comment]
> Поле	Ценить
> Тип сборки	ПРОИЗВОДСТВО
> Появская версия	эдельвейс - 20230928 - v3_openjdk
> версия майнкрафта	1.2.5forge - КУЗИТЬ
> Рендерер	GL4ES_115
> Архитектура	ARM_64
> среда выполнения Java	ВНУТРЕННИЙ - JRE - 8
> Аргументы Java	
> Ошибки найдены:
> forge.install.corrupted

and what should I do now

**Comment by GaucovyAero** [comment]
idk whats exactly the issue but
a) your mod might be conflicting with the minecraft sound system (that means your mod is for a different version of mc)
b) you might be missing the sound system, which means that you maybe installed forge incorrectly, or the 1.2.5 jar you modified is broken

**Comment by Prostop194** [comment]
> Я не знаю, в чем именно проблема, но а) ваш мод может конфликтовать со звуковой системой Minecraft (это означает, что ваш мод предназначен для другой версии mc) б) у вас может отсутствовать звуковая система, а это означает, что вы, возможно, неправильно установили forge, или измененная вами банка 1.2.5 сломана

and what should I do now

**Comment by GaucovyAero** [comment]
send me the mod and ill see if it works, if not then ill send you a version of cameracraft 1.2.5 that works for me

**Comment by Prostop194** [comment]
> пришлите мне мод и я проверю, работает ли он, если нет, то я пришлю вам версию cameracraft 1.2.5, которая мне подходит

**Comment by Prostop194** [comment]
> пришлите мне мод и я проверю, работает ли он, если нет, то я пришлю вам версию cameracraft 1.2.5, которая мне подходит

https://disk.yandex.ru/d/nkTPnW76vEHA9A

**Comment by GaucovyAero** [comment]
you must have installed something incorrectly, it works fine for me

![Screenshot_20231007-202853_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/90e9c098-de27-4636-a778-7b9fa8c64845)

**Comment by Prostop194** [comment]
> видимо вы что-то неправильно установили, у меня все работает нормально
> 
> ![Screenshot_20231007-202853_PojavLauncher (Minecraft_ Java Edition для Android)](https://user-images.githubusercontent.com/85581164/273403072-90e9c098-de27-4636-a778-7b9fa8c64845.png)

and what should I do to make it work?

**Comment by Prostop194** [comment]
![Screenshot_20231008_124515_MiXplorer](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/0d06f3cf-2943-42c1-9532-b7a186d7137d)
How long should I delete it?

**Comment by GaucovyAero** [comment]
exactly like this but make sure there is only 1 comma and 1 space between `"complianceLevel":0` and `"id":"1.2.5Forge"` and edit `net.minecraft.launchwrapper.Launch` to `net.minecraft.client.Minecraft` and dont delete anything besides `META-INF/MANIFEST.MF` in the jar

**Comment by Prostop194** [comment]
> точно так же, но убедитесь, что между `"complianceLevel":0`и `"id":"1.2.5Forge"`и редактированием есть только 1 запятая и 1 `net.minecraft.launchwrapper.Launch`пробел `net.minecraft.client.Minecraft`, и не удаляйте ничего, кроме `META-INF/MANIFEST.MF`банки.

![Screenshot_20231008_163155_MiXplorer](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/dfb865e7-afb7-4046-8fe8-cbf2bcc436cd)
That is how it should be?

**Comment by GaucovyAero** [comment]
yeah

**Comment by Prostop194** [comment]
> ага

I decided to launch Forge with the cameracraft mod and again endless loading

**Comment by GaucovyAero** [comment]
> > ага
> 
> I decided to launch Forge with the cameracraft mod and again endless loading

always send log when you have an issue

**Comment by Prostop194** [comment]
> > > ага
> > 
> > 
> > Решил запустить Forge с модом cameracraft и снова бесконечная загрузка
> 
> всегда отправляйте журнал, если у вас есть проблема

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12840470/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.2.5forge - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| forge.install.corrupted |

**Comment by GaucovyAero** [comment]
it says you are missing the sound system, make sure you have not deleted the paulscode folder

**Comment by Prostop194** [comment]
![Screenshot_20231008_205957_MiXplorer](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/2022682f-aae1-42db-89f5-2ba601ab135d)

**Comment by GaucovyAero** [comment]
yeah i have no idea whats wrong, works just fine for me

**Comment by GaucovyAero** [comment]
you can try downloading all the jars and files with firefox and see if that makes any difference
maybe you could also try modifying the jar with the rar file manager (you will have to copy the jar over to downloads cause rar cant access files in /storage/emulated/0/Android/data/)

**Comment by GaucovyAero** [comment]
well, turns out you were right, if im using your files and doing it from my phone, it doesnt work, i get that error, hmm (when i sent the screenshot i just copied the jar over from my pc)

**Comment by GaucovyAero** [comment]
[cameracraft125.jar.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12847555/cameracraft125.jar.zip)

can you try this cameracraft jar? (you have to unzip it)

**Comment by GaucovyAero** [comment]
okay nice i got it working, you have to use RAR (from play store) to modify the jar, mixplorer corrupts it for some reason

![Screenshot_20231009-170456_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/bf6a9913-9650-4640-9d49-1509482bf747)

**Comment by Prostop194** [comment]
> окей, хорошо, у меня все работает, вам нужно использовать RAR (из магазина игр), чтобы изменить jar, mixplorer по какой-то причине повреждает его
> 
> ![Screenshot_20231009-170456_PojavLauncher (Minecraft_ Java Edition для Android)](https://user-images.githubusercontent.com/85581164/273625440-bf6a9913-9650-4640-9d49-1509482bf747.png)

thank you everything worked

**Comment by GaucovyAero** [comment]
nice
