### ISSUE TITLE
Unable to connect Minecraft Account 

### ISSUE THREAD

**Issue by conttdj** [PojavLauncherTeam/PojavLauncher#4684]
### Describe the bug

Basically it's stuck at 75% and not able to connect at all, I do not think it's a problem on my side, maybe you guys could take a look into this

### The log file and images/videos

![Screenshot_2023-10-04-21-52-26-24_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/112465867/bec207b1-cca4-4b3c-a2f0-4f14e420447c)

### Steps To Reproduce

```markdown
1.  Start Pojav Launcher
2.  Connect to Microsoft Account
```

### Expected Behavior

The Microsoft Account is connected

### Platform

```markdown
- Device model: One Plus CE2 Lite
- CPU architecture: 64 bit
- Android version: 12
- PojavLauncher version: Latest Play Store release
```

**Comment by GaucovyAero** [comment]
not a pojav issue, worked first time for me, make sure you arent using school internet

![Screenshot_20231004-223944_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/190d1b1e-7c6c-4a7a-848f-e91976a5bc77)
