### ISSUE TITLE
Crash with Rl craft

### ISSUE THREAD

**Issue by ArkiBoyZ** [PojavLauncherTeam/PojavLauncher#4686]
### Describe the bug

- I downloaded the rl craft 2.9.3 from create modpack profile option and it starts properly and opens till menu but after i create new world or open any world as it was about to to open it starts crashing and says shutting down internal server'' and games simple crashes
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12818963/latestlog.txt)

### The log file and images/videos
![Screenshot_2023-10-05-08-54-24-42_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/105589980/21fd6b4e-0b62-473f-b09c-52d864c8c040)
![Screenshot_2023-10-05-08-54-12-03_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/105589980/5648ac3c-20c6-48fd-a766-2ced3a1ca4aa)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12818963/latestlog.txt)

### Steps To Reproduce

```markdown
Start game 
Download Rl craft 2.9.3 
Click play 
And create new world
```

### Expected Behavior

The game should not crash after creating world

### Platform

```markdown
- Device model: RMX3241
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I tried with both holy gles and zink renderer it crash always and Before this update the games works fine

**Comment by GaucovyAero** [comment]
you have sent logs of 1.12.2 vanilla which clearly works

**Comment by ArkiBoyZ** [comment]
> you have sent logs of 1.12.2 vanilla which clearly works

I have update the latestlog please check it now

**Comment by GaucovyAero** [comment]
remove soundfilters mod and see what it does, you might have a few other mods (like dynamic surroundings) that dont work on gl4es, so get it working with zink first

**Comment by ArkiBoyZ** [comment]
I removed the soundfilters mod and the game started working properly in both zink and gl4es renderer but this wierd texture glitch started happening the items in jei is shown properly but not in inventory the items in my inventory are shown in the top left of jei mod respectively 
![Screenshot_2023-10-06-00-35-22-94_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/105589980/40a18c1d-309e-4487-876e-b9688b0d753c)

**Comment by GaucovyAero** [comment]
see if it works fine with zink and be sure to send log

**Comment by ArkiBoyZ** [comment]
Some of the textures are fine with zink renderer 
![Screenshot_2023-10-06-00-59-51-26_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/105589980/95f41a8c-f85e-4fb5-b728-730895b89dcd)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12822536/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.12.2-forge-14.23.5.2860 - FORGE |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| account.offline |

**Comment by ArkiBoyZ** [comment]
What i have do with this

**Comment by GaucovyAero** [comment]
no idea, try removing half of the mods and see which half is doing it, then progressively figure out which mod is the cause using the halves, maybe try removing jei first?

**Comment by GaucovyAero** [comment]
inactive issue, closing, react to this one with your log and ill reopen it

**Comment by ZnnieCODM** [comment]
Mine when i launch my world i can still go inside the game but after 5 seconds it will crash

**Comment by GaucovyAero** [comment]
> Mine when i launch my world i can still go inside the game but after 5 seconds it will crash

send log

**Comment by ZnnieCODM** [comment]
I dont know whts that log im new here in github
Are you talking about crash logs?

**Comment by GaucovyAero** [comment]
> I dont know whts that log im new here in github Are you talking about crash logs?

im talking about
android 9 and older: /storage/emulated/0/games/PojavLauncher/latestlog.txt
android 10 and newer: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

**Comment by ZnnieCODM** [comment]
> > I dont know whts that log im new here in github Are you talking about crash logs?
> 
> im talking about android 9 and older: /storage/emulated/0/games/PojavLauncher/latestlog.txt android 10 and newer: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

I fixed it now 
But thankyou

I deleted the following
- custommainmenumod
- fancyparticles
- dynamic surroundings
- soundfilters
And now i can play with open es shaders

**Comment by ZnnieCODM** [comment]
![Uploading Screenshot_20231013_030103.jpg…]()

**Comment by ZnnieCODM** [comment]
![Screenshot_20231013_025800](https://github.com/PojavLauncherTeam/PojavLauncher/assets/141920629/a643bca4-c3ac-4ec9-8dbd-fa7af6a67061)

**Comment by GaucovyAero** [comment]
nice

**Comment by ghost** [comment]
This wierd texture black and purple is for mod optifine i deleted optifine and texture are fixed
