### ISSUE TITLE
GL4ES 1.1.6 ? 

### ISSUE THREAD

**Issue by Username10926663** [PojavLauncherTeam/PojavLauncher#4698]
### Is this request related to a bug?

This is not related to any bug. 

### Describe the request.

When will there be gl4es 1.1.6 as we have 1.1.5 for over a year now.

**Comment by GaucovyAero** [comment]
version numbers dont really matter, there has been a big gl4es update with better server shader conversion in the last 2 weeks (check github actions)

**Comment by Username10926663** [comment]
Okay thank but will there more gl improvements such as:
in-game performances improvements 
Much more mods support
Shader support maybe ?
Sodium/VulkanMod support too without patching ?

**Comment by Bel69420** [comment]
Vulkanmod work but it just doesn't compatible with Arm 64

**Comment by Bel69420** [comment]
Shader required OpenGL 4.x+ so that's not possible if GL4ES could support all shaders

**Comment by Bel69420** [comment]
Except Open4es shader

**Comment by Bel69420** [comment]
Some mods depending on OpenGL extensions in your device
