### ISSUE TITLE
Testing the 9b5 release - optifine crashes with android 9 (crash log)

### ISSUE THREAD

**Issue by matteobranchi** [PojavLauncherTeam/PojavLauncher#47]
Ok I watched your last video on youtube, the latest Optifine 1.11.2 works well in android 10 but it crashes with android 9 ( for the tests I used the same folder with the same files with the latest pojav launcher release on two different phones ) it crashes during game loading ( while there is the "mojang" logo onscreen ).

also, ( I have those problems in both android 9 and 10 ) with the 9b5 release I still can't move my vision while going forward using touch controls, still no sound, Banners are invisibile in-game (open gl2 could fix that..?) and I can't use the virtual onscreen keyboard, ( it does appear but I can't press any button on it ).

I can't load any resourcepack, if I select one it will kick me out of resourcepack menu, (I think that happens because there is no Open gl2 or something) older versions used to give me the  "missing pack.mcmeta :(" error. 

also the game crashes when I click the "quit game" button in the main menu (android 10), the crash log is below (I had to write it on hand, the error won't let me select the text rip)
```
Unable to lacate crash! 
java.lang.NullPointerException: Attempt to get lenght of null array
 at net.kdt.pojavlaunch.Tools,lastFileModified(Tools.java:422) 
 at net.kdt.pojavlaunch-Tools.lastFileModified(Tools.java:422)
 at net.kdt.pojavlaunch.MainActivity$100000003$100000002.run(MainActivity.java:147)
 at android.os.Handler.handleCallback(Handler.java:883)
 at adnroid.os.Handler.dispatchMessage(Handler.java:100)
 at os.Looper.loop(Looper.java:244)
 at android.app.ActivityThread.main(ActivityThread.java:7520)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInt.java:539)
 at com.android.internal.os.ZygoreInit.main(Zygoteinit.java:950)
```

this is the crash log of android 9 with 1.11.2 optifine:
```
Description: Initializing game

java.lang.NullPointerException: Attempt to invoke virtual method 'cbh cbk.bakeModel(bri, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
 at cbk.a(ModelBakery.java:725)
 at cbl.a(SourceFile:23)
 at cae.a(SourceFile:100)
 at bes.an(SourceFile:519)
 at bes.a(SourceFile:383)
 at net.minecraft.client.main.Main.main(SourceFile:124)
 at java.lang.reflect.Method.invoke(Native Method)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
 at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
 at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
 at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
 at java.lang.Thread.run(Thread.java:764)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
 at cbk.a(ModelBakery.java:725)
 at cbl.a(SourceFile:23)
 at cae.a(SourceFile:100)

-- Initialization --
Details:
Stacktrace:
 at b.a(CrashReport.java:338)
 at bes.a(SourceFile:386)
 at net.minecraft.client.main.Main.main(SourceFile:124)
 at java.lang.reflect.Method.invoke(Native Method)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
 at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
 at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
 at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
 at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
 Minecraft Version: 1.11.2
 Operating System: Linux (aarch64) version 4.9.200-perf-g44bd5bc
 Java Version: 0, The Android Project
 Java VM Version: Dalvik (Xiaomi Mi MIX 2S), The Android Project
 Memory: 20987264 bytes (20 MB) / 203827320 bytes (194 MB) up to 536870912 bytes (512 MB)
 JVM Flags: 0 total; 
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 Launched Version: 1.11.2-OptiFine_HD_U_F5
 LWJGL: 2.9.1
 OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
 GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer, OpenGL 1.4
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

 Using VBOs: No
 Is Modded: Definitely; Client brand changed to 'PojavLauncher'
 Type: Client (map_client.txt)
 Resource Packs: 
 Current Language: English (US)
 Profiler Position: N/A (disabled)
 CPU: 9x null
 OptiFine Version: OptiFine_1.11.2_HD_U_F5
 OptiFine Build: 20191204-142531
 Render Distance Chunks: 8
 Mipmaps: 0
 Anisotropic Filtering: 1
 Antialiasing: 0
 Multitexture: false
 Shaders: null
 OpenGlVersion: 2.0 gl4es wrapper 1.1.2
 OpenGlRenderer: GL4ES wrapper
 OpenGlVendor: ptitSeb
 CpuCount: 8
```

**Comment by artdeell** [comment]
OpenGL 2 is already there (it's not fully supported)
Also, you may try older Optifines (like 1.8.8)

**Comment by artdeell** [comment]
Also, may be android 9 lacks some features from Java language.

**Comment by khanhduytran0** [comment]
That video use 1.11 not 1.11.2 so you can try with 1.11

**Comment by khanhduytran0** [comment]
`Unable to locate crash` error is often, you can ignore it.

**Comment by khanhduytran0** [comment]
> I can't use the virtual onscreen keyboard

Try other keyboard like GBoard, it will work.

> I can't load any resourcepack, if I select one it will kick me out of resourcepack menu, (I think that happens because there is no Open gl2 or something)

Check if you didn't skip download assets, also check if any crash report.

> older versions used to give me the "missing pack.mcmeta :(" error.

This is because you didn't download full assets, press skip.

**Comment by matteobranchi** [comment]
> > I can't use the virtual onscreen keyboard
> 
> Try other keyboard like GBoard, it will work.
> 
> > I can't load any resourcepack, if I select one it will kick me out of resourcepack menu, (I think that happens because there is no Open gl2 or something)
> 
> Check if you didn't skip download assets, also check if any crash report.
> 
> > older versions used to give me the "missing pack.mcmeta :(" error.
> 
> This is because you didn't download full assets, press skip.

Thanks! Gboard works! 
For the resouecepacks, I took my "assets" folder from my PC ( and also downloaded another resourcepack, that one had problems ) and it works!
What about the sounds? There is something I could try?

**Comment by khanhduytran0** [comment]
Sound only works on some devices, ex my Android-x86 (dualboot) worked

**Comment by artdeell** [comment]
Hm. What's wrong with al-soft?

**Comment by artdeell** [comment]
Also, you can try to use latest OpenAL-soft
https://github.com/kcat/openal-soft

**Comment by khanhduytran0** [comment]
Thank you, looking on it.

**Comment by khanhduytran0** [comment]
Optifine crashed is unfixable and I can't do anything more to fix it.

**Comment by khanhduytran0** [comment]
> Optifine crashes are unfixable and I can't do anything more to fix it.
