### ISSUE TITLE
sodium mod crashes

### ISSUE THREAD

**Issue by Hogira** [PojavLauncherTeam/PojavLauncher#4700]
### Describe the bug

the devs of sodium also know pojavlauncher exists and they also warn you at the start that the mod might crash or not work properly, after that when you turn off all the optimization, it crashes, and even with the optimizations turned on it crashes too.

theres something about the rendering or something idk but sodium just no longer works after the 1.20 update

### The log file and images/videos

lost the latest log file cause I started playing with optifine

### Steps To Reproduce

```markdown
open the game with fabric and sodium mod, change settings and no matter how many settings i tried, it just crashes
```

### Expected Behavior

The game does launch but the worlds aren’t playable

### Platform

```markdown
- Device model: samsung m20
- CPU architecture: unknown
- Android version: 10
- PojavLauncher version: Version edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I have no more to say but the only thing I know is, Sodium gives you warning that it will crash on pojavlauncher and it does crash no matter whatever setting I choose

**Comment by GaucovyAero** [comment]
sodium only fully supports computer graphics cards with opengl 4.6 (should still work down to 3.3), not stuff inside phones nor compatibility layers that translate mobile gles instructions to gl

gl4es doesnt have enough functions to work with sodium
