### ISSUE TITLE
[BUG] <Shaders Error: Invalid Program>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4701]
### Describe the bug

This is happening after I updated pojav to the latest version, before that the shaders loaded normally. Maybe the renderer has updated too so it could be broaking the shaders? Well, idk...

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12826776/latest.log)

![Screenshot_20231006_005813_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/142160595/cbb769d2-92d8-46ea-86f8-eafe3ea3a9b5)

### Steps To Reproduce

```markdown
1. Start pojav with the latest version of optifine and change the renderer to Holy-GL4ES (only change the renderer, don't change the other settings).
2. With the game open, in the optfine choose any shaders, example:(me:chocapic13 v6).
3. Start any world, invalid errors should appear (just me?).
```

### Expected Behavior

I expected the shaders to load normally as before, without these errors.

### Platform

```markdown
- Device model: Samsung A03/Mali-G57 & Unisoc T606
- CPU architecture: aarch64 - arm64-v8a
- Android version: 13
- PojavLauncher version: debug - edelweiss 20231015-64daa07
```

**Comment by guiilerm1** [comment]
I also want to make it clear that the game version is 1.19.4 and that the shaders I downloaded support it

**Comment by ghost** [comment]
I also want to make it clear that the game version is 1.19.4 and that the shaders I downloaded support it.

**Comment by GaucovyAero** [comment]
shaders dont work on gl4es, use zink if it works on your phone

**Comment by Reisaki127** [comment]
Has the problem been solved?
