### ISSUE TITLE
[BUG] <Key delay Republish the video>

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#4702]
### Describe the bug

When playing the game, I don't know why, suddenly the button delay very big, very obvious.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/136832400/1d67abb0-b7bc-4329-862a-6ab33268bb5e

### Steps To Reproduce

```markdown
1.Start the game.
2.Into the world.
3.Press the button.
```

### Expected Behavior

I hope it won't trigger this problem again, otherwise it will be very uncomfortable.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
are you using vulkanmod or sodium? also, your recording seems to be completely broken (at least on my phone rn) 

![Screenshot_20231006-145154_Fennec](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/59f2390d-b7be-4ed5-9342-114b397719c1)

**Comment by aaaapai** [comment]
> are you using vulkanmod or sodium? also, your recording seems to be completely broken (at least on my phone rn)
> 
> ![Screenshot_20231006-145154_Fennec](https://user-images.githubusercontent.com/85581164/273213638-59f2390d-b7be-4ed5-9342-114b397719c1.png)

The video won't load at all on my end

**Comment by bsjssjjs** [comment]
Uploading d2a3b5bcc3360185d2e1dcb3bd9f02c2.mp4…

**Comment by bsjssjjs** [comment]
Uploading d2a3b5bcc3360185d2e1dcb3bd9f02c2.mp4…

**Comment by bsjssjjs** [comment]
oh NO
