### ISSUE TITLE
[F-Req] Add all old Renders

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#4703]
### Is this request related to a bug?

For working on other devices

### Describe the request.

Add render
VirGL
VGPU GL 4.6
Zink (old)

**Comment by GaucovyAero** [comment]
a) virgl wont be added, because it is very slow and doesnt fully work on basically all devices
b) vgpu features have integrated into holy gl4es itself
c) new zink runs a lot faster than old zink
