### ISSUE TITLE
[BUG] Shaders do not work on HolyGl4es

### ISSUE THREAD

**Issue by Gregory269** [PojavLauncherTeam/PojavLauncher#4704]
### Describe the bug

From the new update in Pojavlauncher after enabling shaders on the rendering engine nothing turns on.

![Screenshot_20231006_200000_com huawei himovie overseas](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89700145/e1035862-8f76-460b-96bc-9a1c6eccdedc)
![Screenshot_20231006_200029_com huawei himovie overseas](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89700145/357876e7-9c6a-42d4-9cf2-1cf9187cb42b)

I have tried many shaders but to no avail.

### The log file and images/videos

After turning on the shader, there are only "final" errors

### Steps To Reproduce

```markdown
1. Run Minecraft 1.19.3 on OptiFine On the HolyGl4es engine 
2. Run the shader
```

### Expected Behavior

After enabling shaders, a blue background appears instead of my shader and "final" errors

### Platform

```markdown
- Device model: Huawei P30 Lite 4/128GB
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

no

**Comment by Bel69420** [comment]
Try Vulkan zink with non-mali version

**Comment by Bel69420** [comment]
I mean the shader

**Comment by Gregory269** [comment]
When I run Zink Vulkan it kicks me out of December

**Comment by Gregory269** [comment]
When I run Zink Vulkan it kicks me out of the game

**Comment by Bel69420** [comment]
Your phone has outdated vk version lmao

**Comment by Bel69420** [comment]
Too bad

**Comment by Bel69420** [comment]
Also, there's shadow issue with mali when you're using this shader

**Comment by Gregory269** [comment]
So what happened to shaders on HolyGl4es?

**Comment by Bel69420** [comment]
With GL4ES

**Comment by Bel69420** [comment]
It wasn't GL4ES fault, it just the shader is too outdated

**Comment by Gregory269** [comment]
I really want to use shaders on HolyGl4es but unfortunately I can't

**Comment by Bel69420** [comment]
Wait, lemme have a try

**Comment by Bel69420** [comment]
I mean, I also have Mali

**Comment by Bel69420** [comment]
Mali G77-MC9

**Comment by Gregory269** [comment]
Okay.

**Comment by Bel69420** [comment]
![Screenshot_2023-10-07-02-26-24-506_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89313901/8feff67f-c274-4045-8ed9-cd7459a3a270)
Lmao

**Comment by Bel69420** [comment]
:trollface:

**Comment by Gregory269** [comment]
Bruh

**Comment by Bel69420** [comment]
I declare that your GPU driver is trash

**Comment by Bel69420** [comment]
L Mali

**Comment by Bel69420** [comment]
I wish they have updatable drivers

**Comment by Bel69420** [comment]
Like Adreno

**Comment by Gregory269** [comment]
It's a pity that these shaders don't work

**Comment by Bel69420** [comment]
Old Mali GPU moment

**Comment by Gregory269** [comment]
When will this be fixed because I would really like to use shaders

**Comment by GaucovyAero** [comment]
> So what happened to shaders on HolyGl4es?

new holy gl4es has better server resource pack shader support, open4es probably just has to get updated

**Comment by Gregory269** [comment]
I hope everything will be fine soon
