### ISSUE TITLE
[BUG] Sodium(Fabric) and Rubidium(Forge) Kept crashing while joining a world or server

### ISSUE THREAD

**Issue by Adrian647PH** [PojavLauncherTeam/PojavLauncher#4709]
### Describe the bug

__Sodium and Rubidium mod/client kept crashing the game while joining a world__

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12837570/latestlog.txt)
I can't capture the screen because it kept crashing

### Steps To Reproduce

```markdown
1. Start pojavlauncher while having/using Sodium with Fabric OR Rubidium with Forge
2. Create a world or join a world
3. It crash because of Sodium/Rubidium Client ( Maybe because of the renderer?!?! )
```

### Expected Behavior

I expected to not crash the game and continue like normal

### Platform

```markdown
- Device model: Samsung A03s
- CPU architecture: I Don't know what this is
- Android version: 13
- PojavLauncher version: Latest Or the game version: 1.19.2 Forge latest (43.3.0 recommended)
```

### Anything else?

Nothing else

**Comment by Adrian647PH** [comment]
Oof Wrong log file..
Here's the correct one: 
[2023-10-03-2.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12837590/2023-10-03-2.log)

**Comment by Adrian647PH** [comment]
Oof wrong log file..
Here's the correct log file: 
[2023-10-07-1.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12837593/2023-10-07-1.log)

**Comment by Adrian647PH** [comment]
Also i use some other mods.. maybe it only works without any additional mods.. but please still fix it..

**Comment by GaucovyAero** [comment]
sodium/rubidium dont support opengl 2.1, hence why it doesnt work, you can use the patcher on the pojav wiki for some versions of sodium/rubidium, but it doesnt work on the latest one

**Comment by Adrian647PH** [comment]
> sodium/rubidium dont support opengl 2.1, hence why it doesnt work, you can use the patcher on the pojav wiki for some versions of sodium/rubidium, but it doesnt work on the latest one

What do you mean?

**Comment by Adrian647PH** [comment]
@GaucovyAero can you help fix it?

**Comment by RoomAlex68** [comment]
This is also happening with another mod called Embeddium which is based off of Rubidium but which is a fork of Sodium
