### ISSUE TITLE
[BUG] <invisible block>

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#4710]
### Describe the bug

Just look at the picture, i enter the world and it just go blank like that. 

### The log file and images/videos

![Screenshot_20231007-192045](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143271606/d3a8da04-d01d-4f01-810a-0eba7aedf1a2)

I used some mods btw , here's the list
![Screenshot_20231007-192838](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143271606/c4867215-5fd0-47a4-891b-d70c45ad7805)

### Steps To Reproduce

```markdown
1 / install mods
2 / enter the game
3 / setting quite a bit for performance
4 / create a world
5 / enter the world , but nothing is rendering
```

### Expected Behavior

I want my render back to normal

### Platform

```markdown
- Device model: pixel 3 (64/4) 
- CPU architecture: 4x Qualcomm Kryo 385 Silver @ 1766 MHz
4x Qualcomm Kryo 385 Gold @ 2803 MHz
- Android version: 12L
- PojavLauncher version: newest / 20230926
```

**Comment by GaucovyAero** [comment]
patch sodium with the patcher on the pojav wiki
