### ISSUE TITLE
[BUG] crashing on hypixel with mods

### ISSUE THREAD

**Issue by TiVO-OP** [PojavLauncherTeam/PojavLauncher#4712]
### Describe the bug

mods: NEU, Essential, Patcher, Optifine
Before adding essential and patcher the game was crashing too but it's now more frequent and says that there was an error with a error code -1 where earlier it was just crashing without any notification.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12838156/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav
2. Load up your minecraft forge 1.8.9 with: optifine, essential, neu and patcher
3. go play some skyblock
4. crash after a few minutes
5. get an error code -1
```

### Expected Behavior

Expected: not to crash during the few minutes of gameplay

### Platform

```markdown
- Device model: Mi 12 lite 6/128GB
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest release from google play
```

**Comment by GaucovyAero** [comment]
downgrade patcher to 1.6.1 located on the pojav wiki in the unsupported mods section (or just dont use patcher)
