### ISSUE TITLE
[BUG] Pojavlauncher is getting crashed after installing distant horizons mod 

### ISSUE THREAD

**Issue by AnasModassir** [PojavLauncherTeam/PojavLauncher#4714]
### Describe the bug

.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

.

**Comment by dDreaMmtTeaMm** [comment]
distant horizons doesn't work on pojav,
it needs opl3.2+ wich zink have but even if you tried to run it with zink it will probably not work.
https://github.com/PojavLauncherTeam/PojavLauncher/issues/1948

**Comment by alexytomi** [comment]
Well zink working depends on the device. A decent rule of thumb (there are still exceptions) is Anything that is PowerVR or Adreno 5XX will not work with zink.

Since they didn't really fill up anything then there's really no point to the report

**Comment by GaucovyAero** [comment]
distant horizons doesnt support old opengl 2.1, you need 4.6
to get 4.6, you need zink, and for that to work, you have to have a device that supports turnip (adreno 6xx and 7xx) or vulkan 1.3, powervr gpus wont work, because they only have vulkan 1.0 or 1.1
