### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by Hypergaming2020** [PojavLauncherTeam/PojavLauncher#4715]
### Describe the bug

Hello I have a problem where I open pojavlauncher a message pops up said bad request and I have a premium aqaunt and I can't play any servers whith in idk why is this happening pls someone help me!!!

### The log file and images/videos

Idk

### Steps To Reproduce

```markdown
Idk how to do it
```

### Expected Behavior

I expected to launc the premium account but it says bad request

### Platform

```markdown
- Device model: Samsung tab a7 and Redmi 9 
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: updated from playstore from September 28 2023 its latest version
```

### Anything else?

Pls help!!!!

**Comment by GaucovyAero** [comment]
log into minecraft.net first
