### ISSUE TITLE
[F-Req] Added login via EasyMC token

### ISSUE THREAD

**Issue by TechAdrianPro** [PojavLauncherTeam/PojavLauncher#4718]
### Is this request related to a bug?

No, the request is not related to an error 

### Describe the request.

It was nice to log in via EasyMC if someone doesn't have Minecraft Premium, e.g. Meteor Client has this function, but having it built into Pojavlauncher would also be nice 😉.

### Anything else?

You can also add a token from The Altening😉.

**Comment by GaucovyAero** [comment]
no
