### ISSUE TITLE
 dont work shift + right click

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#472]
doesnt work shift + right click

**Comment by PeterScorPioN** [comment]
Yes, i noticed that too. Actually, it's shift + left click, which is for transfering items quickly in your inventory, but it doesn't do anything. I even created a button for that, but nothing.

**Comment by ghost** [comment]
> Yes, i noticed that too. Actually, it's shift + left click, which is for transfering items quickly in your inventory, but it doesn't do anything. I even created a button for that, but nothing.

it same i create buttom right click and in setting add shift not work

**Comment by ImadeRamadany** [comment]
Goblog

Pada tanggal Jum, 29 Jan 2021 20:36, ytuy404 <notifications@github.com>
menulis:
