### ISSUE TITLE
Crash on Rlcraft 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4722]
### Describe the bug

Using latest pojavlauncher make Rlcraft crash I try old version of pojavlauncher it's working why after update the pojavlauncher so many things not working anymore 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Starting pojavlauncher
2. Create world
3. Crash on 5 sec play
```

### Expected Behavior

Using latest pojavlauncher crash
Old pojavlauncher working fine 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

After try some mod on update for months many mods are not working anymore plss fix

**Comment by GaucovyAero** [comment]
send log, also please mention what other things dont work and maybe send logs + screenshots + videos of them if you can

**Comment by kedrick021** [comment]
> send log

Wait I try latest pojavlauncher again if working now if not I send log

**Comment by kedrick021** [comment]
> > send log
> 
> Wait I try latest pojavlauncher again if working now if not I send log

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12849740/latestlog.txt)

Here it take me 5hour because I use Latest pojavlauncher he don't let me stall forge only error and use forge site file it's still error

Then I use second update on GitHub
It's Install now

I hope you fix what the problem

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | edelweiss - 20231005 - in_app_file_manager |
| Minecraft version | 1.12.2-forge-14.23.5.2860 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| branch.not.mainline |

**Comment by GaucovyAero** [comment]
remove dynamic surroundings (that mod never worked on pojav btw)

**Comment by kedrick021** [comment]
> remove dynamic surroundings (that mod never worked on pojav btw)

Nothing changes still crash

**Comment by kedrick021** [comment]
> > remove dynamic surroundings (that mod never worked on pojav btw)
> 
> Nothing changes still crash

Well I can still play using old version

**Comment by kedrick021** [comment]
> > > remove dynamic surroundings (that mod never worked on pojav btw)
> > 
> > 
> > Nothing changes still crash
> 
> Well I can still play using old version

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12850496/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | edelweiss - 20231005 - in_app_file_manager |
| Minecraft version | 1.12.2-forge-14.23.5.2860 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| branch.not.mainline |

**Comment by kedrick021** [comment]
> > > > remove dynamic surroundings (that mod never worked on pojav btw)
> > > 
> > > 
> > > Nothing changes still crash
> > 
> > 
> > Well I can still play using old version
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12850496/latestlog.txt)

This is the old version pojavlauncher am using to play Rlcraft
PojavLauncher (Minecraft  Java Edition for Android)_dahlia-159-b581c7ba8-v3_openjdk

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | edelweiss - 20231005 - in_app_file_manager |
| Minecraft version | 1.12.2-forge-14.23.5.2860 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| branch.not.mainline |

**Comment by GaucovyAero** [comment]
> > > > remove dynamic surroundings (that mod never worked on pojav btw)
> > > 
> > > 
> > > Nothing changes still crash
> > 
> > 
> > Well I can still play using old version
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12850496/latestlog.txt)

remove sound filters

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | edelweiss - 20231005 - in_app_file_manager |
| Minecraft version | 1.12.2-forge-14.23.5.2860 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| branch.not.mainline |

**Comment by GaucovyAero** [comment]
closing as resolved
