### ISSUE TITLE
[BUG] Need VulkanMod patcher

### ISSUE THREAD

**Issue by NothingMan29** [PojavLauncherTeam/PojavLauncher#4723]
### Describe the bug

In the new update, it was said that the "vulkan mode" mode was compatible, but I could not do it. i need patcher link and tutorial 

### The log file and images/videos

💀

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

Need it

### Platform

```markdown
Nty
```

### Anything else?

Not

**Comment by GaucovyAero** [comment]
its built into pojav, it does everything for you, if you want to find the patcher inside pojavs code, use github code search

**Comment by NothingMan29** [comment]
Whar a code name?

**Comment by NothingMan29** [comment]
> What
 a code name?

**Comment by NothingMan29** [comment]
I find the code

**Comment by NothingMan29** [comment]
What im do now?

**Comment by GaucovyAero** [comment]
whatever you want

**Comment by NothingMan29** [comment]
?
