### ISSUE TITLE
[BUG] Any modpack with Sodium in it crashes with GL4ES renderer

### ISSUE THREAD

**Issue by quber0** [PojavLauncherTeam/PojavLauncher#4724]
### Describe the bug

Every time when you try to join a world or a server on a profile with Sodium with GL4ES renderer, the game crashes while trying to join the world/server.

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12861930/latest.log)
[crash-2023-10-10_23.23.07-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12861931/crash-2023-10-10_23.23.07-client.txt)

### Steps To Reproduce

```markdown
1. Install a new modpack with Sodium in it or make a new profile with a Sodium mod.
2. Launch the game with just created profile and GL4ES renderer.
3. When the game has launched, join any world or server.
```

### Expected Behavior

The player should be moved to the world/server.

### Platform

```markdown
- Device model: Redmi Note 10 Pro 6/128 GB
- CPU architecture: unknown
- Android version: 12 SKQ1.210908.001
- PojavLauncher version: latest Google Play Store release (edelweiss-20230928-9484d0c-v3_openjdk)
```

**Comment by quber0** [comment]
And yes, I know that according to Discord FAQ GL4ES renderer doesn't work with newer versions of Sodium, but when testing, I realized it actually doesn't work with any Sodium version. Also, this makes like 95% of performance mods in modpack tab useless since they all require Sodium to work.

**Comment by quber0** [comment]
The fixes in FAQ channel don't work either

**Comment by GaucovyAero** [comment]
you can patch sodium 0.3 to 0.4.10 with the patcher on the wiki, then copy .minecraft/config/sodium-mixins.properties to your modpack config folder
