### ISSUE TITLE
[BUG] <Create chashed when I installed blocks from this mod>

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#4728]
### Describe the bug

I expected that the blocks from the create mod would be placed and did not crash. Minecraft version 1.18.2 forge version 40.2.10
Create mod version 0.5.1e

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12889225/latestlog.txt)
Last time you asked me to send latestlog.txt

### Steps To Reproduce

```markdown
My actions:
Launch pojav with create mod and render angle
Joining world
Placing the block from mod create
And crahed
```

### Expected Behavior

I expected that the blocks from the create mod would be placed and did not crash.

### Platform

```markdown
Device model: samsung s10
- CPU architecture: ex9820
- Android version: 12
- PojavLauncher version: edelweis-20230928-
```

### Anything else?

last time you asked me to send latestlog.txt here I am again

**Comment by GaucovyAero** [comment]
disable the flywheel backend
/flywheel backend off

**Comment by Faked4075** [comment]
> отключить серверную часть маховика /выключить серверную часть маховика

How? There is no separate mod for the flywheel in the crate, it is built in, and without the flywheel this mod will not work

**Comment by GaucovyAero** [comment]
> > отключить серверную часть маховика /выключить серверную часть маховика
> 
> How? There is no separate mod for the flywheel in the crate, it is built in, and without the flywheel this mod will not work

the command does not turn off flywheel, it just turns off its graphics backend and uses the slower minecraft one

**Comment by Faked4075** [comment]
> > > Отключить серверную часть маховика /выключить серверную часть маховика
> > 
> > 
> > Как? Отдельного мода на маховик в крейте нет, он встроен, и без маховика этот мод работать не будет.
> 
> команда не отключает маховик, она просто отключает графический интерфейс и использует более медленный вариант Minecraft.

then please tell me how to disable it

**Comment by Faked4075** [comment]
> /отключение маховика

Yeaah,  working, thank you veru muchh
