### ISSUE TITLE
[BUG] <When creating a world the game crashes Forge 1.12.2>

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#4729]
### Describe the bug

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12893818/latestlog.txt)
here is the list of mods 
Industrial craft 2
Jei
Map writer 
Treecapitator 
Bskprcore
Inventory tweaks
Ruins

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model:Samsung Galaxy A52 
- CPU architecture: 
- Android version: 13
- PojavLauncher version: Latest version
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
no crash in the log, make sure you dont have render regions turned on in video settings - performance (if you have optifine) otherwise try using zink if that fixes it
if not, then narrow it down to what mod is causing the issue and tell me what it is and ill investigate

**Comment by Prostop194** [comment]
I've already done everything thank you
