### ISSUE TITLE
[Mod Incompatibility] TF2 Stuff 1.12.2: can't aim

### ISSUE THREAD

**Issue by Dimon245** [PojavLauncherTeam/PojavLauncher#473]
So, first off: sorry if I'm not supposed to post this here. The reason I'm posting here actually is cause the dev of the mod abandoned it over a year ago and I  would like your help (if possible). Well, the issue is that when I hold a weapon (melee or shooting) I can't aim properly, i.e I'm moving the screen with my fingers and it's a lot less sensitive than when I hold a normal Minecraft item.

**Comment by khanhduytran0** [comment]
(maybe) known issue.

**Comment by Dimon245** [comment]
oh. Hope it gets fixed

**Comment by Dimon245** [comment]
Yay, it's fixed!
