### ISSUE TITLE
How can we access the world or saves folder of modpacks ? It doesn't show it in versions folder.

### ISSUE THREAD

**Issue by oddsairaj007** [PojavLauncherTeam/PojavLauncher#4739]
### Describe the request.

I want you to add the features of accessing the saves folder of modpacks

**Comment by artdeell** [comment]
Modpacks are stored in Android/data/net.kdt.pojavlaunch.debug/files/custom_instances if I recall correctly

**Comment by oddsairaj007** [comment]
> Modpacks are stored in Android/d

> Modpacks are stored in Android/data/net.kdt.pojavlaunch.debug/files/custom_instances if I recall correctly

Thx bro helped me
