### ISSUE TITLE
Minecraft 1.16 Scroll Bar not working

### ISSUE THREAD

**Issue by Furanzeru** [PojavLauncherTeam/PojavLauncher#474]
Hi i'm Franzel909, i created a new account because i have some verification issues on my previous account. Anyway, i have some small problems with the mouse cursor and the scroll bars, i keep Tap-Holding it, but it still doesn't respond.

**Comment by ghost** [comment]
works for me.

**Comment by Furanzeru** [comment]
> works for me.

I have Oppo a3s 2 gb RAM and android version 8.1

**Comment by ghost** [comment]
> > works for me.
> 
> I have Oppo a3s 2 gb RAM and android version 8.1

i have rn8pro 6ram android 10 custom os

**Comment by khanhduytran0** [comment]
Scroll bar does not work yet, instead use virtual scroll buttons or direct swipe.

**Comment by Furanzeru** [comment]
Virtual Mouse cursor doesn't work

**Comment by khanhduytran0** [comment]
? What do you mean? Mouse does not work at touch and click?

**Comment by Furanzeru** [comment]
> ? What do you mean? Mouse does not work at touch and click?

The click and touch works, but when i touch+hold it on scroll bars it doesn't work

**Comment by khanhduytran0** [comment]
As I said before 
> Scroll bar does not work yet

**Comment by Mathias-Boulay** [comment]
Closing since it is a duplicate from #648
