### ISSUE TITLE
[BUG] [MODS] Better questing mod's quest information texts are not showing.

### ISSUE THREAD

**Issue by ShoyebOP** [PojavLauncherTeam/PojavLauncher#4740]
### Describe the bug

Most of the modpacks between the versions 1.7-1.12 have the better questing mod for quests.

The mod loads without any errors or problems and the quest icons also loads up but the informations about how to complete the quests don't load up .

### The log file and images/videos

![Screenshot_20231016-101057](https://github.com/PojavLauncherTeam/PojavLauncher/assets/115879044/46d3cce9-8f49-451e-b671-02269705c604)
![Screenshot_20231016-101105](https://github.com/PojavLauncherTeam/PojavLauncher/assets/115879044/21d5a72c-b9ff-4229-8cc9-f9a5c2ab2546)

### Steps To Reproduce

```markdown
1.Start pojav launcher
2.install any modpack with better questing mod(ex: rlcraft)
3.load up the modpack
4.create a world
5.after the world loads up open quests tab
6.tap on any quest
```

### Expected Behavior

The information about the quest should load up normally not as black boxes

### Platform

```markdown
- Device model: OnePlus 5 (A5000)
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: [Latest Release || version edelweiss-20230928-9484d0c-v3_openjdk ]
```

**Comment by artdeell** [comment]
Seems like a GL4ES bug, you can try to switch to Zink and see if it works

**Comment by ShoyebOP** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12913375/latestlog.txt)
> Seems like a GL4ES bug, you can try to switch to Zink and see if it works

Using zink renderer crashes the game on launch. Here's the log. see if you could find the issue.

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.12.2-forge-14.23.5.2859 - FORGE |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| account.offline |

**Comment by kedrick021** [comment]
Use this mods
https://link-target.net/445467/undiscovered-modpacks

Have better questing no glitch

**Comment by GaucovyAero** [comment]
> > Seems like a GL4ES bug, you can try to switch to Zink and see if it works
> 
> Using zink renderer crashes the game on launch. Here's the log. see if you could find the issue.

seems like a pojav lwjgl bug, not sure if its actually a bug tho

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12913375/latestlog.txt)
> 
> > Seems like a GL4ES bug, you can try to switch to Zink and see if it works
> 
> Using zink renderer crashes the game on launch. Here's the log. see if you could find the issue.

not going to be fixed, the turnip driver which you need in order to run zink only supports adreno 6xx and 7xx series 
you have to have a zink compatible phone in order to run this mod for now

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.12.2-forge-14.23.5.2859 - FORGE |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| account.offline |

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.12.2-forge-14.23.5.2859 - FORGE |
| Renderer | UNKNOWN |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| account.offline |
