### ISSUE TITLE
Texture glitch on holygles Mali Mediatek Helio 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4741]
### Describe the bug

They have glitch texture bug on blocks in Mali Mediatek Helio 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12914481/latestlog.txt)

![Screenshot_20231016-171137](https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/40a31f47-6d61-4ffa-88f2-d43bc894e2ca)
![Screenshot_20231016-171156](https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/e9ab7bc9-4bb0-40cd-9f29-702f96fa8ec9)

### Steps To Reproduce

```markdown
0. Holygl4es render
1. start game
2. Place blocks
3. Texture bug
```

### Expected Behavior

Clean blocks

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Plss fix when I try the shader on holygles it rendering the texture glitch too

**Comment by kedrick021** [comment]
![Uploading Screenshot_20231016-171441.png…]()

**Comment by kedrick021** [comment]
![Screenshot_20231016-171441](https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/bcc3f4cf-b620-465f-8e6d-8a681f0e4baa)


Become brighter when use this

**Comment by kedrick021** [comment]
![Screenshot_20231016-171441](https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/225d2f4c-1b66-4780-ae7c-e250b2ed1670)

Using this shader texture glitch can see brighter

**Comment by Bel69420** [comment]
It seems like Mali skill issue

**Comment by GaucovyAero** [comment]
i dont see any issues there

**Comment by Bel69420** [comment]
@GaucovyAero i think he mean, the shadow looks goofy

**Comment by Bel69420** [comment]
Plus, zink doesn't work with Open4es in 1.12.2

**Comment by kedrick021** [comment]
> i dont see any issues there

Look at blocks planks

**Comment by GaucovyAero** [comment]
but thats only when using custom shaders, which isnt really supported on mali

**Comment by Bel69420** [comment]
Mali seems missing some extension that cause the shadow like this

**Comment by kedrick021** [comment]
> but thats only when using custom shaders, which isnt really supported on mali

Did you look the picture without shader you can see if you zoom in

**Comment by GaucovyAero** [comment]
> > i dont see any issues there
> 
> Look at blocks planks

there is no shadow there lol

**Comment by GaucovyAero** [comment]
if you mean the noise or whatever, thats caused by the fact that gl4es has disabled mipmaps to get more fps

**Comment by Bel69420** [comment]
That's why Mipmap 4 doesn't affect GL4ES

**Comment by kedrick021** [comment]
> That's why Mipmap 4 doesn't affect GL4ES

![Screenshot_20231016-171156](https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/628e3e5e-270a-4684-b206-d84c7a84513d)
Look on planks block you can see it the texture

**Comment by kedrick021** [comment]
> > That's why Mipmap 4 doesn't affect GL4ES
> 
> ![Screenshot_20231016-171156](https://user-images.githubusercontent.com/76839710/275493014-628e3e5e-270a-4684-b206-d84c7a84513d.png) Look on planks block you can see it the texture

Look like adidas

**Comment by Bel69420** [comment]
This is known problem, mipmap suppose to fix the plank but mipmap was disabled for performance

**Comment by GaucovyAero** [comment]
yes

**Comment by kedrick021** [comment]
> This is known problem, mipmap suppose to fix the plank but mipmap was disabled for performance

Ok
