### ISSUE TITLE
[BUG] Hypixel Skyblocks Mods doesn't work

### ISSUE THREAD

**Issue by Kartvya69** [PojavLauncherTeam/PojavLauncher#4743]
### Describe the bug

So i wanted to play hypixel skyblock and i have added some mods but it doesn't run the minecraft and it stucks on the launching session 

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12925633/latest.log)

### Steps To Reproduce

```markdown
1. Start the pojav 
2. Add the mods patcher, sba, skyhanni, skytils, optifine1.8.9, dulkirmod, soopy, cowlection, scrollable tooltips, neu, 
3. start forge 1.8.9 and the error will be reproduced
```

### Expected Behavior

I expect that game should Launch but it Didn't I saw some log outputs that it Stucks on Bar Steps and I don't have idea anything about

### Platform

```markdown
- Device model: Realme Narzo 20
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: [Latest Release On Google Play store
```

**Comment by GaucovyAero** [comment]
there is no crash in the log, try downgrading to patcher 1.7.0 from the pojav discord

**Comment by Kartvya69** [comment]
> there is no crash in the log, try downgrading to patcher 1.7.0 from the pojav discord

Actually dude I am banned from pojav discord from many months and I can't access it what u said cuz I can't join pojav dc sir if u could give me the link of patcher 1.7.0 so i could manage.
But Still I have that stuck issue I removed Patcher mod

**Comment by GaucovyAero** [comment]
[Patcher-1.7.0_1.8.9.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12985502/Patcher-1.7.0_1.8.9.zip)

send log without patcher

**Comment by Kartvya69** [comment]
> [Patcher-1.7.0_1.8.9.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12985502/Patcher-1.7.0_1.8.9.zip)
> 
> send log without patcher

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/13016093/latest.log)
Here is the log of without adding patcher mod and the patcher mod u given happens same thing idk why it is stuck on Bar step of SkyblockAddons

**Comment by GaucovyAero** [comment]
> > [Patcher-1.7.0_1.8.9.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12985502/Patcher-1.7.0_1.8.9.zip)
> > send log without patcher
> 
> [latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/13016093/latest.log) Here is the log of without adding patcher mod and the patcher mod u given happens same thing idk why it is stuck on Bar step of SkyblockAddons

no idea, remove some mods yourself and see which ones are causing it

**Comment by GaucovyAero** [comment]
stale issue
