### ISSUE TITLE
[BUG] "W" can't be typed in chat.

### ISSUE THREAD

**Issue by Maciekrybka009** [PojavLauncherTeam/PojavLauncher#4744]
### Describe the bug

Each time I try to attempt to write capital W in chat, the screen minimizes and message gets cleared.

### The log file and images/videos

![Screenshot_20231017-101001_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/39466238/6e8c01bf-99a8-4a56-964d-c643f27bf512)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Enter multiplayer server
3. Open chat and enter capital W
```

### Expected Behavior

It should type the letter in chat.

### Platform

```markdown
- Device model:
- CPU architecture: 
- Android version: 
- PojavLauncher version: Latest
```

**Comment by Maciekrybka009** [comment]
I tried using different keyboard. Issue persists.

**Comment by Maciekrybka009** [comment]
Upon further testing. Issue appears only on 1.8.9 Optifine

**Comment by GaucovyAero** [comment]
shift + w (or just w) is a hardcoded fullscreen shortcut in android, bind fullscreen to a different key in minecraft controls settings
