### ISSUE TITLE
[BUG] Nomifactory CEu crashes if launched without internet.

### ISSUE THREAD

**Issue by Doom3guy** [PojavLauncherTeam/PojavLauncher#4745]
### Describe the bug

Nomifactory CEu crashes with code 1 if the modpack is launched without internet.
If launched with internet it successfully loads to main menu.

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12929140/latest.log)

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Download Nomifactory CEu frough inbuilt modpack downloader.
3. Start the modpack without internet.
4. Crash.
```

### Expected Behavior

1. Start PojavLauncher.
2. Download Nomifactory CEu frough inbuilt modpack downloader.
3. Start the modpack without internet.
4. Successfully loads to the main menu.

### Platform

```markdown
- Device model: Redmi Note 12 Pro 8/256Gb
- CPU architecture: arm64-v8a
- Android version: 12
- PojavLauncher version: "Edelweiss" Release
```

### Anything else?

Reinstalling modpack and deleting and manually installing forge version doesn't change anything.
Im using newest google play store PojavLauncher as it was updated not that long ago.
Should i ask their discord for help?

**Comment by GaucovyAero** [comment]
not a pojav issue, ask nomifactory maintainers about it

```
Caused by: java.lang.RuntimeException: You are currently using SerializationIsBad without any patch modules configured. The mod on its own doesn't do anything so please install a config file patching the vulnerabilities
```
