### ISSUE TITLE
[BUG] Stuck on "Move the LEFT joystick to the RIGHT" with NS Pro Controller

### ISSUE THREAD

**Issue by Ch1216** [PojavLauncherTeam/PojavLauncher#4749]
### Describe the bug

When setting up controller controls with my Nintendo Switch Pro Controller with Bluetooth I get stuck on the "Move the LEFT joystick to the RIGHT", I do so with my controller but it does not continue with the next instructions, after further testing, the controller's joystick do not seem to work with Pojav properly, as it only even registers my left joystick when I rotate it for a bit (maybe some weird angle it registers?), and it only registers moving to the bottom with my right joystick

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13034868/latestlog.txt)
![Screenshot_20231018-191846_PojavLauncher_Minecraft_Java_Edition_for_Android](https://github.com/PojavLauncherTeam/PojavLauncher/assets/68875386/e8880ef9-80ce-49ca-8f42-ee5e6f253968)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Have a connected Nintendo Switch Pro Controller
3.Go through the setup for the face and menu buttons
4.Get stuck when it asks you to "Move the LEFT joystick to the RIGHT"
```

### Expected Behavior

I expected it to continue setting up the controller controls

### Platform

```markdown
- Device model: Galaxy S8
- CPU architecture: Octa-core (4x2.35 GHz Kryo & 4x1.9 GHz Kryo)
- Android version: 9
- PojavLauncher version: Version edelweiss-20230928-9484d0c-v3_openjk
```

**Comment by VenomousSteam81** [comment]
I have a similar issue on my Chromebook with my PS3 controller, but this knockoff XBox 360 controller was detected.

**Comment by GaucovyAero** [comment]
various controller issues have been caught, wait for a fix ig

**Comment by Mathias-Boulay** [comment]
@Ch1216 Please update to the latest dev version and retry. An update to support more controllers has been done

**Comment by Ch1216** [comment]
Im sorry but I cant get github to download files off actions in my phone, Please notify me if the update with the support gets into a google play release

**Comment by Mathias-Boulay** [comment]
you need to be logged int to download the github action build

**Comment by Mathias-Boulay** [comment]
Another update has been done to support switch style DPADs as well. Tested fully with official hardware, so I close the issue as it is resolved in dev builds
