### ISSUE TITLE
Pojav buttons and chat

### ISSUE THREAD

**Issue by Mynameispoop** [PojavLauncherTeam/PojavLauncher#475]
I cant click shift while in a chest or other buttons pls help. When on chats and type @ ' " : _ - = [ ] { } it removes

**Comment by khanhduytran0** [comment]
Known issue.

**Comment by Mynameispoop** [comment]
Oki

**Comment by khanhduytran0** [comment]
Try latest build

**Comment by Mathias-Boulay** [comment]
Stale issue and no answer after asking for a new build.
The happiest people are the one you don't see again.
Closing the issue :eyes:

**Comment by Ilovepojavlauncher** [comment]
Please old UI is best 🥺❤️🥺❤️🥺❤️ 🙏🙏🙏🙏🙏😭😭😭😭🥰🥰🥰😍🥺🥺🥺🥺🥹🥹 please convey this UI to old UI

**Comment by ghost** [comment]
> Please old UI is best 🥺❤️🥺❤️🥺❤️ 🙏🙏🙏🙏🙏😭😭😭😭🥰🥰🥰😍🥺🥺🥺🥺🥹🥹 please convey this UI to old UI

No, Developers wouldn’t bring this back old UI
New UI is good already, then why do they spam emojis too much

**Comment by Ilovepojavlauncher** [comment]
Please 😭

**Comment by ghost** [comment]
Nah, new ui was easy to use
Then stop
