### ISSUE TITLE
[BUG] balck world 1.17+

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4752]
### Describe the bug

This
![Screenshot_20231019_131643](https://github.com/PojavLauncherTeam/PojavLauncher/assets/101394924/7641502c-8a1d-4ebc-8b74-b2063ba143c5)

### The log file and images/videos

![2023-09-15_13 21 17_2](https://github.com/PojavLauncherTeam/PojavLauncher/assets/101394924/e236fbb9-656c-4f4e-89e3-95bda9e4573d)

### Steps To Reproduce

```markdown
1laod into world
2.dark af
```

### Expected Behavior

I expected it to be a normal world

### Platform

```markdown
- Device model: honor x6
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version:dahlia-20230913-4cd3ab0-zink-2
```

### Anything else?

I have a powervr Gpu (i know it makes the problem im asking for the fix)

**Comment by GaucovyAero** [comment]
update your pojav to the latest play store build, this has been fixed

**Comment by GaucovyAero** [comment]
in case you want to keep using the old version of pojav, here is a workaround, but keep in mind hit color wont work with this:
[powervr_ge8320_workaround.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13041354/powervr_ge8320_workaround.txt)

**Comment by hiimabignoobwihenolive** [comment]
Isn't hitcolor a malware or something? Btw thanks

**Comment by GaucovyAero** [comment]
> Isn't hitcolor a malware or something? Btw thanks

hitcolor means when you hit a mob he will turn red

**Comment by hiimabignoobwihenolive** [comment]
it crashed without any crash log

**Comment by GaucovyAero** [comment]
> it crashed without any crash log

send log /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt
use zarchiver to access the folder

**Comment by hiimabignoobwihenolive** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13041689/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.18.2-optifine_hd_u_h9 - OPTIFINE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 17 |
| Java arguments | -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Ddiscordfix=net.minecraft.client.main.Main |



|Errors Found: |
|--|
| account.offline |

**Comment by hiimabignoobwihenolive** [comment]
Ohhh damn you people Fixed it?

**Comment by GaucovyAero** [comment]
make sure you have render regions turned off in optifine performance video settings

**Comment by hiimabignoobwihenolive** [comment]
Ok

**Comment by hiimabignoobwihenolive** [comment]
It loaded thanks!!!

**Comment by hiimabignoobwihenolive** [comment]
But it crashed after some time i think it was because of limited amount of ram

**Comment by GaucovyAero** [comment]
> But it crashed after some time i think it was because of limited amount of ram

how much ram are you allocating?

**Comment by hiimabignoobwihenolive** [comment]
1gb
