### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by deyvid12349** [PojavLauncherTeam/PojavLauncher#4753]
### Describe the bug

Não dá para entrar

### The log file and images/videos

Não

### Steps To Reproduce

```markdown
Start pojavalaucher
```

### Expected Behavior

Não

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Nã

**Comment by deyvid12349** [comment]
Bom

**Comment by GaucovyAero** [comment]
provide more info please
