### ISSUE TITLE
[hud problem] <hud not showing>

### ISSUE THREAD

**Issue by DevEriJMT** [PojavLauncherTeam/PojavLauncher#4754]
### Describe the bug

hud is not displayed when playing versions older than 1.16.5, I mean things like the f3, the hotbar, the pointer. etc are not shown

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13048272/latestlog.txt)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/140129917/be30d57d-facd-48d2-8279-669f0564cdd3

Please ignore the audio, they are doing repairs in my house, I apologize

### Steps To Reproduce

```markdown
1-start a version higher than 1.16.5
```

### Expected Behavior

I hope you can help me with this problem or give it a solution.

### Platform

```markdown
- Device model: Lenovo-TB-X306X (LenovoTB-X306X)
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484dOc-v3_poenjdk (latest of playstore)
```

### Anything else?

I know that with optifine it can be solved, using antialiasing or the internal shader, but optifine is not something that I like to use and it does not optimize as much as sodium, is there a way to play vanilla without that error occurring? could you patch it?

**Comment by Bel69420** [comment]
PowerVR moment

**Comment by Bel69420** [comment]
It's a driver issue

**Comment by GaucovyAero** [comment]
most people with your gpu dont have this issue, you just appear to have a broken driver

**Comment by GaucovyAero** [comment]
i suggest you try exordium to see if that maybe fixes the issue, it renders the gui differently iirc

be sure to let me know if it works or not

**Comment by DevEriJMT** [comment]
> Te sugiero que pruebes Exordium para ver si eso soluciona el problema, ya que representa la interfaz gráfica de usuario de manera diferente.
> 
> Asegúrate de decirme si funciona o no.

Not work

**Comment by DevEriJMT** [comment]
> i suggest you try exordium to see if that maybe fixes the issue, it renders the gui differently iirc
> 
> be sure to let me know if it works or not

Other solution?

**Comment by DevEriJMT** [comment]
How I would love to be able to use sodium haha

**Comment by GaucovyAero** [comment]
> > i suggest you try exordium to see if that maybe fixes the issue, it renders the gui differently iirc
> > be sure to let me know if it works or not
> 
> Other solution?

you would probably have to create a mod that fixes this in some way that doesnt lower down fps and is compatible with sodium

**Comment by DevEriJMT** [comment]
> > > Te sugiero que pruebes Exordium para ver si eso soluciona el problema, representa la interfaz gráfica de usuario de manera diferente. 
> > > Asegúrate de informarme si funciona o no.
> > 
> > 
> > ¿Otra solución?
> 
> Probablemente tendrías que crear un mod que solucione este problema de alguna manera que no reduzca los fps y que sea compatible con el sodio.

I don't know how to program, but what exactly should that mod do?

**Comment by GaucovyAero** [comment]
change the rendering of the guis

**Comment by DevEriJMT** [comment]
Well, thank you very much for helping, I will ask a friend if he could help me with that.
