### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by Matiffi** [PojavLauncherTeam/PojavLauncher#4755]
### Describe the bug

Controls are not working correctly 

https://github.com/PojavLauncherTeam/PojavLauncher/assets/147846045/20a59efd-44ee-4513-a16e-8a1b9e657f7d

### The log file and images/videos

Controls are not working correctly 

### Steps To Reproduce

```markdown
1. Launch Minecraft
2. Logged into the server
3. Controls
```

### Expected Behavior

I expect normal controls

### Platform

```markdown
- Device model: Poco F3
- CPU architecture: 64-bit ARMv8-A
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
will not be fixed for now, sodium and vulkanmod both stay unsupported

**Comment by Bel69420** [comment]
No, @GaucovyAero Vulkanmod input delay has been fixed

**Comment by Bel69420** [comment]
Only Sodium left

**Comment by Bel69420** [comment]
So, Sodium is ass :trollface:
