### ISSUE TITLE
[BUG] Minecraft forge 1.18.2 ,game exited with code 1 

### ISSUE THREAD

**Issue by ABtreawoptis23** [PojavLauncherTeam/PojavLauncher#4759]
### Describe the bug

After I installed Minecraft 1.18.2 I proceeded to install forge version 1.18.2 as well but who knows what happened suddenly the application exited with code 1 😔

### The log file and images/videos

![Screenshot_2023-10-21-13-01-04-90_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/90324849/f14e4288-109d-409e-a5a8-fd7dda7b1055)
 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13059966/latestlog.txt)

### Steps To Reproduce

```markdown
1. starting the launcher 
2. Play Minecraft forge forge-1.18.2-40.2.10 
3. But after playing it appears that the application exits with code 1
```

### Expected Behavior

I hope this can be fixed soon so I can play in this version. 

### Platform

```markdown
- Device model:Oppo A5 2020
- CPU architecture:arm64
- Android version:10
- PojavLauncher version:edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Btw I haven't installed any mods on the forge yet...

**Comment by GaucovyAero** [comment]
no wonder, you are trying to run optifine 1.16.5 on 1.18.2
