### ISSUE TITLE
[BUG] <Short description> when i right click or left click it lagging so much that i can't even click like 10 cps with external keyboard and mouse plss fix this i can't pvp

### ISSUE THREAD

**Issue by Jdvdhtdmxh** [PojavLauncherTeam/PojavLauncher#4762]
### Describe the bug

https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/a29dd229-2fc3-4664-bb66-4b9ff7545e39

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/b6193fb2-b99b-437f-8c52-3b8d0c1e0540

### Steps To Reproduce

```markdown
Start pojavlauncher and try external keyboard and mouse
```

### Expected Behavior

Try external keyboard and mouse

### Platform

```markdown
- Device model:infinix zero 5g
- CPU architecture:dimensity 900
- Android version:12 
- PojavLauncher version:all version
```

### Anything else?

Plss fix this

**Comment by Jdvdhtdmxh** [comment]
Yooo i got 450 fps

**Comment by Mathias-Boulay** [comment]
Isn't this a duplicate?

**Comment by GaucovyAero** [comment]
> Isn't this a duplicate?

not really, i mean i closed all the issues related to samsung but this appears to be same thing but he says he has an infinix phone, ima label this as "needs fixing", you can verify the issue on any samsung device that isnt newer than the s21 (apparently those dont do it)

**Comment by GaucovyAero** [comment]
heres my video of the issue on an actual samsung device

https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/2fa24321-41ad-494d-a422-32c35235cf66

**Comment by Jdvdhtdmxh** [comment]
Same problem

**Comment by Jdvdhtdmxh** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/cd996c9f-5fb7-472b-8cbb-d82caacf35a7

Just a little bit

**Comment by Jdvdhtdmxh** [comment]
Now I can do 10 cps good work

**Comment by GaucovyAero** [comment]
what happened?

**Comment by Jdvdhtdmxh** [comment]
It fixed a little bit thank
