### ISSUE TITLE
[BUG] Vulkan Crash (libjvm not found???)

### ISSUE THREAD

**Issue by Pogzhsd2** [PojavLauncherTeam/PojavLauncher#4765]
### Describe the bug

It crashes when I start. Please help.

### The log file and images/videos

[Log.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13068197/Log.txt)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Use Zink
3. Launch (Anything)
(Has force vulkan on)
```

### Expected Behavior

It crashes.

### Platform

```markdown
- Device model: Poco F5 5G
- CPU architecture: aarch64 (Adreno 725, Snapdragon 7 Gen 2)
- Android version: 13
- PojavLauncher version: Play Store Lastest Version (As of Oct 23 2023)
```

**Comment by Bel69420** [comment]
Turnip doesn't support for Adreno 725

**Comment by Pogzhsd2** [comment]
Anything I can do or I can't use vulkan?

**Comment by Bel69420** [comment]
You can't use zink until developer of turnip releasing Turnip driver for your GPU

**Comment by Pogzhsd2** [comment]
rip, but is GL4ES also good for shaders?

**Comment by Bel69420** [comment]
Yes, you can try Open4ES

**Comment by Bel69420** [comment]
This shader is good for Adreno devices

**Comment by Pogzhsd2** [comment]
Can I use the Zink mod tho? Or just sodium

**Comment by GaucovyAero** [comment]
this is like the 4th duplicate already (please read previous issues)

Turnip doesn't yet support the Adreno 725, please wait for an update, it may take a few months.
