### ISSUE TITLE
[BUG] Mod and world textures are all wrong

### ISSUE THREAD

**Issue by SantannaCarlos** [PojavLauncherTeam/PojavLauncher#4766]
### Describe the bug

When I download my modpack to play with pojavlauncher, all the textures are wrong in my server, and I cannot create a singleplayer world.

### The log file and images/videos

Logs: https://mclo.gs/F3HhIFU
Modpack: https://www.dropbox.com/scl/fi/jn309g06ywcuulyxjvs1z/Novo-Macacomon.zip?rlkey=hdiunv7zwdl7m7psglly2z4zz&dl=0

And some screenshots
![Screenshot_20231023_074413_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/102835093/b83b5a55-a723-4abf-b9a1-8d108c894458)
![Screenshot_20231023_074403_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/102835093/81ebf68c-0e20-40a5-844e-6dd21a72a05d)

### Steps To Reproduce

```markdown
1. Download modpack and install it
2. Start PojavLauncher
3. Join my server (there's no way to create singleplayer world), ip: macacomon.jogar.io
```

### Expected Behavior

I expect it to have the right textures

### Platform

```markdown
- Device model: Samsung S22 Ultra
- CPU architecture: Kryo
- Android version: 13
- PojavLauncher version: Latest Release
```

**Comment by GaucovyAero** [comment]
press f11, known issue

**Comment by GaucovyAero** [comment]
your logs are the wrong ones btw, always send /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

**Comment by SantannaCarlos** [comment]
> your logs are the wrong ones btw, always send /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

Hello, F11 did not solve it
correct logs: https://mclo.gs/KOO2Hxv
