### ISSUE TITLE
[BUG] Models and Textures are all wrong

### ISSUE THREAD

**Issue by SantannaCarlos** [PojavLauncherTeam/PojavLauncher#4767]
### Describe the bug

*I ALREADY TRIED PRESSING F11*
When I download my modpack to play with pojavlauncher, all the textures are wrong in my server, and I cannot create a singleplayer world.

### The log file and images/videos

Logs: https://mclo.gs/KOO2Hxv
Modpack: https://www.dropbox.com/scl/fi/jn309g06ywcuulyxjvs1z/Novo-Macacomon.zip?rlkey=hdiunv7zwdl7m7psglly2z4zz&dl=0

And some screenshots
![Screenshot_20231023_074413_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/102835093/adcfb05a-3560-43bb-b144-bdf6433dcdaa)
![Screenshot_20231023_074403_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/102835093/83770ded-717c-4c11-a559-e94f9fe53362)

### Steps To Reproduce

```markdown
1. Download modpack and install it
2. Start PojavLauncher
3. Join my server (there's no way to create singleplayer world), ip: macacomon.jogar.io
```

### Expected Behavior

I expect a fix to this

### Platform

```markdown
- Device model: Samsung S22 Ultra
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Latest Release
```

### Anything else?

I already tried to press f11, nothing happens

**Comment by GaucovyAero** [comment]
duplicate, try removing optifine, messing with fast render, etc. wont fix, one or more of your mods may also be causing it

**Comment by SantannaCarlos** [comment]
there's no optfine bro
