### ISSUE TITLE
[BUG] <Cant do any modpacks due to lack of ram>

### ISSUE THREAD

**Issue by toogitt** [PojavLauncherTeam/PojavLauncher#4768]
### Describe the bug

All of the modpacks Im trying to run require at least 4 gigs of ram, which I have available, but I cant allocate any more than 2500mb. is there a way for me to allocate more?

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
N/A
```

### Expected Behavior

Expected: I want to allocate more ram to play modpacks

### Platform

```markdown
- Device model: Galaxy Z flip 5
- CPU architecture: idk
- Android version: 13
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
no lol, try `-XX:-UseG1GC` if you are running 1.16.5 and older, but its prolly not gonna help
you can also try momentarily using olauncher as your default system launcher (takes up less ram) and you can try disabling the mcafee security app in your phone via adb

**Comment by GaucovyAero** [comment]
the package name for the security app is ```com.samsung.android.sm.devicesecurity```

and alternatively you can try using TinyBit launcher which should take up even less ram

you can also use `com.kosajun.easymemorycleaner` as your memory cleaner

**Comment by GaucovyAero** [comment]
lmk if if helps
