### ISSUE TITLE
how can i load a world 

### ISSUE THREAD

**Issue by ahg-py** [PojavLauncherTeam/PojavLauncher#4769]
### Is this request related to a bug?

how can i load a world to my worlds 
i have the files

**Comment by GaucovyAero** [comment]
what android version are you on?

**Comment by ahg-py** [comment]
13

**Comment by GaucovyAero** [comment]
put the world into `/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/saves`

you can use zarchiver to do it
