### ISSUE TITLE
I can't use more than 6-8 mods on forge 1.12.2

### ISSUE THREAD

**Issue by OleraKyn** [PojavLauncherTeam/PojavLauncher#477]
If i put more than 9 mods in mods folder, minecraft will be crashed.
Please tell me how to use more than 9 mods? 
My phone called Xiaomi Mi 8:
I have 3 free gb of RAM, powerful enough processor that called snapdragon 845 (340000 points in AnTuTu).

**Comment by OleraKyn** [comment]
Much weak phone can use same number of mods

**Comment by pstube** [comment]
Try changing the memory value in Options.

**Comment by pstube** [comment]
Options > Settings > JVM Launch arguments > -Xms(  Here   ) -XmX(   Here   ) -XX:

**Comment by OleraKyn** [comment]
Oh man)
Thank you very much

**Comment by mglovers123** [comment]
Close
