### ISSUE TITLE
ps5 controller movement stuck

### ISSUE THREAD

**Issue by Domtastick** [PojavLauncherTeam/PojavLauncher#4770]
### Describe the bug

anytime you try to move with a ps5 controller it just keeps holding one direction infinitely without stopping.

i tried anything included several mods for controller support but nothing was working.

i attached the logs for each of the mods and for a try with no controller support mods.

### The log file and images/videos

[2023-10-24-7.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/13114450/2023-10-24-7.log.gz)
[2023-10-24-5.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/13114451/2023-10-24-5.log.gz)
[2023-10-24-6.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/13114452/2023-10-24-6.log.gz)
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/13114457/latest.log)

### Steps To Reproduce

```markdown
connect a ps5 controller and try to move in any direction.
```

### Expected Behavior

the player character stopping to move after you let go of the stick.

### Platform

```markdown
- Device model: 
- CPU architecture: samsung S21 fe 5G
- Android version: 12
- PojavLauncher version: Latest release || version edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

the ability to just disable pojav's built in controller support alltogether would be appreciated.

**Comment by GaucovyAero** [comment]
already fixed in the latest github actions build

**Comment by Domtastick** [comment]
> already fixed in the latest github actions build

oh nice, 
is that build already playable?

**Comment by GaucovyAero** [comment]
> > already fixed in the latest github actions build
> 
> oh nice, is that build already playable?

yeah, read the pojav wiki on how to install builds from github actions

**Comment by Domtastick** [comment]
> > > already fixed in the latest github actions build
> > 
> > 
> > oh nice, is that build already playable?
> 
> yeah, read the pojav wiki on how to install builds from github actions

i'm checking the wiki but i can't find it :(
sorry for being such a bother but i really have no clue of how github works
