### ISSUE TITLE
[F-Req] better keyboard and mouse support 

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4771]
### Is this request related to a bug?

 No

### Describe the request.

making it that the mouse is IN the game not on the screen so it can't press the control buttons and the exit button and also. the keyboard don't work with jei because when typing e it closes the inventory 

### Anything else?

Yes i know when you can fix jei problem by just changing the inventory button into something else but that is annoying and i don't like the inventory button being something else

**Comment by GaucovyAero** [comment]
a) not possible, since its the android mouse, its as on top as your touches are
if you want it not to touch the buttons, just remove all the buttons
b) duplicate issue, no fix found yet

**Comment by hiimabignoobwihenolive** [comment]
I seen a random indian guy showing some random ass launcher that i don't know the name playing with the way i just said

**Comment by hiimabignoobwihenolive** [comment]
> a) not possible, since its the android mouse, its as on top as your touches are if you want it not to touch the buttons, just remove all the buttons b) duplicate issue, no fix found yet

Well this was a fucking lie (anyways thanks for implementing the requst into the game it is really helpful)

**Comment by GaucovyAero** [comment]
yeah np
