### ISSUE TITLE
[BUG] [Custom Controls] SPECIAL_GUI button with `"isHideable": true` doesn't actually hideable

### ISSUE THREAD

**Issue by Felix14-v2** [PojavLauncherTeam/PojavLauncher#4773]
### Description
If you add a button that should hide the control overlay and be hidden in the menu, you will run into a problem: this button is always displayed regardless of whether "displayInMenu" is set to false or not. This can be a problem when you need to hide it outside the game.

### To Reproduce

1. Create a SPECIAL_GUI button
2. Set its visibility to in game only
3. Launch the game and see the bug

### Expected Behavior
I use F1 and SPECIAL_GUI on the same button to seamlessly hide the interface. This allows you to combine the game interface and the launcher controls for a more immersive gameplay experience. This button should only appear in the game and not in the menu, otherwise you may get a desynchronization:

https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/8ea3da45-f6a0-4834-8f2f-a9a3ade5bd73

### Actual behavior
However, because SPECIAL_GUI makes the button unhideable regardless of the `isHideable` value, the button is always displayed. This can cause problems like the one shown above.

### Additional
Controls from the demo video:
[Test controls](https://cdn.discordapp.com/attachments/902664003736707093/1166651100565348392/Default_vanilla_controls_by_Felix14_v2_0.7.2.json)

**Comment by GaucovyAero** [comment]
you are a monster

**Comment by Mathias-Boulay** [comment]
This is intended behavior

**Comment by Felix14-v2** [comment]
> This is intended behavior

Can we have any alternatives? Is it possible to add them?

**Comment by Mathias-Boulay** [comment]
No, as this is out of specification as of v3

**Comment by agent1243** [comment]
sorry for bothering you, but since you made these controls, it even looks like mcpe

**Comment by Mathias-Boulay** [comment]
The field has been moved into internal usage for future versions of the control map.

**Comment by agent1243** [comment]
why the hell was my comment deleted
