### ISSUE TITLE
Vic Modern Warfare mod have black screen when open the attachment on gun 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4775]
### Describe the bug

Vic Modern Warfare mod have black screen when open the attachment on gun 

### The log file and images/videos

![Screenshot_20231026-163251](https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/11352886-eaaf-444e-8149-b4f4aae3a452)

![Screenshot_20231026-163244](https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/423c14b8-0c0a-4424-b73f-a9f6e9fa3f20)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13174989/latestlog.txt)

### Steps To Reproduce

```markdown
1. Starting pojavlauncher
2. Create world
3. Open the attachment gun
4. Black screen
```

### Expected Behavior

No black screen on attachment gun

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: latest GitHub 
- PojavLauncher version: 10
```

### Anything else?

Plss help fix

**Comment by Bel69420** [comment]
GL4ES moment

**Comment by kedrick021** [comment]
> GL4ES moment

I try the version pojavlauncher
Is working fine without bug

But Latest version have black screen on attachment gun

**Comment by kedrick021** [comment]
> > GL4ES moment
> 
> I try the old version pojavlauncher Is working fine without bug
> 
> But Latest version have black screen on attachment gun

**Comment by GaucovyAero** [comment]
what is "" the "" version of pojavlauncher lol

**Comment by kedrick021** [comment]
> what is "" the "" version of pojavlauncher lol

Old version last year working fine without bug

Am using latest pojavlauncher GitHub
But black screen on attachment

**Comment by GaucovyAero** [comment]
> > what is "" the "" version of pojavlauncher lol
> 
> Old version last year working fine without bug
> 
> Am using latest pojavlauncher GitHub But black screen on attachment

what exact old version lol

**Comment by GaucovyAero** [comment]
and with what renderer?

**Comment by kedrick021** [comment]
> and with what renderer?

Wait I need to download and send you

**Comment by kedrick021** [comment]
Holy

**Comment by kedrick021** [comment]
> and with what renderer?

version dahlia-20230806-78737cf-v3_openjdk

**Comment by kedrick021** [comment]
> > and with what renderer?
> 
> version dahlia-20230806-78737cf-v3_openjdk

https://teraboxapp.com/s/1kOcMxkbJxJ5hnyKuGNOCMg

If you want to use

**Comment by GaucovyAero** [comment]
alr thx

**Comment by kedrick021** [comment]
> alr thx

I hope it fix 
And can you try
Modern Warfare cubed mod it crush why I open inventory on guns

**Comment by GaucovyAero** [comment]
> > alr thx
> 
> I hope it fix And can you try Modern Warfare cubed mod it crush why I open inventory on guns

send log

**Comment by GaucovyAero** [comment]
> > > and with what renderer?
> > 
> > 
> > version dahlia-20230806-78737cf-v3_openjdk
> 
> https://teraboxapp.com/s/1kOcMxkbJxJ5hnyKuGNOCMg
> 
> If you want to use

uh, i cant download it without signing into the thing, can you upload it onto temp.sh?

**Comment by kedrick021** [comment]
> > > > and with what renderer?
> > > 
> > > 
> > > version dahlia-20230806-78737cf-v3_openjdk
> > 
> > 
> > https://teraboxapp.com/s/1kOcMxkbJxJ5hnyKuGNOCMg
> > If you want to use
> 
> uh, i cant download it without signing into the thing, can you upload it onto temp.sh?

https://www.mediafire.com/file/ss6byj9ekqq2g86/app-debug.apk/file
Here

**Comment by kedrick021** [comment]
> > > alr thx
> > 
> > 
> > I hope it fix And can you try Modern Warfare cubed mod it crush why I open inventory on guns
> 
> send log

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13183208/latestlog.txt)

Modern Warfare cubed mod

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | edelweiss - 20231022 -  |
| Minecraft version | 1.12.2-forge-14.23.5.2860 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |



|Errors Found: |
|--|
| branch.not.mainline |

**Comment by VenomousSteam81** [comment]
@Mathias-Boulay Cool, is that automatic or did you do that yourself?

**Comment by GaucovyAero** [comment]
> @Mathias-Boulay Cool, is that automatic or did you do that yourself?

automatic

**Comment by GaucovyAero** [comment]
> > > > > and with what renderer?
> > > > 
> > > > 
> > > > version dahlia-20230806-78737cf-v3_openjdk
> > > 
> > > 
> > > https://teraboxapp.com/s/1kOcMxkbJxJ5hnyKuGNOCMg
> > > If you want to use
> > 
> > 
> > uh, i cant download it without signing into the thing, can you upload it onto temp.sh?
> 
> https://www.mediafire.com/file/ss6byj9ekqq2g86/app-debug.apk/file Here

thx

**Comment by kedrick021** [comment]
> > > > > > and with what renderer?
> > > > > 
> > > > > 
> > > > > version dahlia-20230806-78737cf-v3_openjdk
> > > > 
> > > > 
> > > > https://teraboxapp.com/s/1kOcMxkbJxJ5hnyKuGNOCMg
> > > > If you want to use
> > > 
> > > 
> > > uh, i cant download it without signing into the thing, can you upload it onto temp.sh?
> > 
> > 
> > https://www.mediafire.com/file/ss6byj9ekqq2g86/app-debug.apk/file Here
> 
> thx

👍

**Comment by Mathias-Boulay** [comment]
I have a feeling that it will be somehow shader related

**Comment by GaucovyAero** [comment]
> I have a feeling that it will be somehow shader related

shader version mismatch, same as the weird thaumcraft 4 potion effect shader thing

**Comment by Mathias-Boulay** [comment]
This won't be an issue with the F release, at least I hope

**Comment by GaucovyAero** [comment]
might fix itself in a future release of gl4es, closing

**Comment by rathanak265** [comment]
I hope someone will tell me how to fix 😭
