### ISSUE TITLE
[BUG] <player rendering problem>

### ISSUE THREAD

**Issue by PSgamer20x** [PojavLauncherTeam/PojavLauncher#4776]
### Describe the bug

I have problem in pojav launcher
In a game I am enable to see players in a distance 
With 3-4 blocks I can see properly
but after 5-6 blocks I can only see players skin not armour 
And after some more blocks back I am enable to see a proper player (I only can see player's head)
Head is only visisble :((

I have also tried to increase entity distance but it is same as elier
Even I have also changed version & mods I am enbale to fix it

As you can see on this images

![Screenshot_2023-10-02-11-28-39-979_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/aea8c7b2-df40-4bb2-bc88-7843a52abd0e)
![Screenshot_2023-10-02-11-28-36-248_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/75519592-8481-4c4e-a344-3ac85613ccb6)
![Screenshot_2023-10-02-11-28-31-023_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/7967f9bf-364b-4ece-8751-f402f8863bb7)

### The log file and images/videos

If you can fix it do it plsss

### Steps To Reproduce

```markdown
Just this much thanks
```

### Expected Behavior

**Nah** other every thing is fine :)

![Screenshot_2023-09-01-16-31-54-408_com africasunrise skinseed~2](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/b8d6a51a-bab5-46d8-8799-7a55cbfaa9ea)

### Platform

```markdown
- Device model: poco m4 pro 5g
- CPU architecture: ahm ?
- Android version: 13
- PojavLauncher version: 1.19.2
```

### Anything else?

Nah thanks

**Comment by GaucovyAero** [comment]
most probably an issue with your mods lol

**Comment by PSgamer20x** [comment]
> most probably an issue with your mods lol

Yes you are right ,I have checked rn :()

But how do I know which mod is that 
I have 60+ mods ._.

**Comment by PSgamer20x** [comment]
Lmao I found 
Now I can see players out of my render distance XD
MOD NAME : TOO MUCH PLAYERS 

![Screenshot_2023-10-26-21-25-57-868_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/16447c7d-ded7-49be-b091-2864fd0f17ac)

**Comment by GaucovyAero** [comment]
alr nice
