### ISSUE TITLE
How to use Vulkan Renderer mod

### ISSUE THREAD

**Issue by NothingMan29** [PojavLauncherTeam/PojavLauncher#4778]
### Describe the bug

I want use VulkanRenderer

### The log file and images/videos

Not

### Steps To Reproduce

```markdown
Not
```

### Expected Behavior

I want use

### Platform

```markdown
Not
```

### Anything else?

Wan it

**Comment by dDreaMmtTeaMm** [comment]
just download vulkan mod from the official pojav discord server.

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/folder/xsb4udjs7n8z9/VulkanMod_for_PojavLauncher

**Comment by NothingMan29** [comment]
Amazing🔥
