### ISSUE TITLE
Will minecraft 1.16 work on 6gb ram ARMv8.               

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#478]
Will minecraft 1.16 work lagless and cool on 6 gb Ram ARMv8
64gb storage. 2300 Mhz CPU frequency android 
Android 10.

**Comment by khanhduytran0** [comment]
It will work smoothly I think.

**Comment by ghost** [comment]
my phone 6gb ram 2000 mhz work fine

**Comment by ghost** [comment]
> It will work smoothly I think.

Thanks

**Comment by ghost** [comment]
> my phone 6gb ram 2000 mhz work fine

Then I'll use DREAM'S strong plugins

**Comment by ghost** [comment]
I am using poco M2
