### ISSUE TITLE
[BUG] mouse is broken again!

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4780]
### Describe the bug

the mouse is off center like when there was a bug in the old versions!

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/101394924/7c7d92d2-7ccc-406a-a420-b24a63baf54b

### Steps To Reproduce

```markdown
Start pojav
load into the game
mouse off centre!!
```

### Expected Behavior

I expected it to be normal 

### Platform

```markdown
- Device model: honor x6 
- CPU architecture: aarch69
- Android version: 12
- PojavLauncher version: latest google version
```

### Anything else?

I tried agnior notch thingy 
Also I cropped the video because it was too long

**Comment by GaucovyAero** [comment]
dayum

**Comment by Mathias-Boulay** [comment]
hold on can you rotate the phone the other way ?

**Comment by hiimabignoobwihenolive** [comment]
I found the problem it was because i was using a old Minecraft version from the old launcher i just deleted the version and reinstalled so sorry for the unimportant issue
