### ISSUE TITLE
add skin and cape feature and addon installer

### ISSUE THREAD

**Issue by stevespid3rr** [PojavLauncherTeam/PojavLauncher#4781]
### Is this request related to a bug?

No it's not a bug it's a feature 

### Describe the request.

It would be very helpful if built in skin and cape customizer added 
And also we need a built in addon installer to install mods/addons/datapack/worlds/resource packs
Me and all pojav players will be glad if these featurs are added

### Anything else?

Thank you so much for giving us an opportunity to play Minecraft java in mobile phones
You guys are a hero for me

**Comment by GaucovyAero** [comment]
not going to be added, it would be too intensive for low-end devices
