### ISSUE TITLE
[BUG] <No Crash Log>

### ISSUE THREAD

**Issue by KocTRH2287586** [PojavLauncherTeam/PojavLauncher#4782]
### Describe the bug

When i loaded 1.19.4 and started messing around, the game crashed. I started troubleshooting in latestlog text and found no crash log. All it was saying is: Are you running essential or <1.13?. Even the file with crash reports didnt had the crash report of todays date. I had this problem while using a texture pack.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13196295/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Start 1.19.4 Fabric.
3. Start any world.
4. Wait until your game crashes.
5. Check the latestlog.txt
```

### Expected Behavior

I expected the game launches normally instead of it crashing after a few minutes.

### Platform

```markdown
- Device model: OPPO A5
- CPU architecture: arm64
- Android version: 10 
- PojavLauncher version: Latest release
```

### Anything else?

Im not pretty sure but it also happens when you start the other versions of minecraft like 1.20.1.

**Comment by KocTRH2287586** [comment]
Whoops. The latest log just redirects you back to this. I will leave it here and test it again.

**Comment by KocTRH2287586** [comment]
bro i literally didnt knew that the description of this is deafult LOL

**Comment by KocTRH2287586** [comment]
Also, Hello from Russia!

**Comment by GaucovyAero** [comment]
you havent sent the log

**Comment by KocTRH2287586** [comment]
> you havent sent the log

Im really sorry tho, Now I saw my mistake and put it there now lol

**Comment by GaucovyAero** [comment]
> > you havent sent the log
> 
> Its in the link I put in there

thats a local link thats broken (or maybe only works on your phone) lol, send the actual file, not a link or whatever

**Comment by KocTRH2287586** [comment]
> > > you havent sent the log
> > 
> > 
> > Its in the link I put in there
> 
> thats a local link thats broken (or maybe only works on your phone) lol, send the actual file, not a link or whatever

Aight i've done that it turns out I've tried attaching that file and didnt waited long enough until i saw my mistake lol

**Comment by GaucovyAero** [comment]
try patching sodium with the patcher on the pojav wiki in the unsupported mods section, if that doesnt work then remove sodium and sodium extra

**Comment by KocTRH2287586** [comment]
> try patching sodium with the patcher on the pojav wiki in the unsupported mods section, if that doesnt work then remove sodium and sodium extra

When I patched the sodium and sodium extra it still was sending Are you running essential<1.13?. But when I removed it, it stopped sending the message. But still there was no crash log.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13196451/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | fabric-loader-0.14.22-1.19.4 - FABRIC |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | EXTERNAL - JRE - 17 |
| Java arguments | -Xms600m -Xmx3G |



|Errors Found: |
|--|
| java.runtime.wrong.source |

**Comment by KocTRH2287586** [comment]
> Field	Value
> Build type	PRODUCTION
> Pojav version	edelweiss - 20230928 - v3_openjdk
> Minecraft version	fabric-loader-0.14.22-1.19.4 - FABRIC
> Renderer	GL4ES_115
> Architecture	ARM_64
> Java runtime	EXTERNAL - JRE - 17
> Java arguments	-Xms600m -Xmx3G
> Errors Found:
> java.runtime.wrong.source

I dont really know why this happened but i have the arm 64 runtime and it still doesn't work
![Screenshot_2023-10-28-23-21-11-08_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149249431/1ac01929-2ff2-4ed0-8643-d058a9740ce4)

**Comment by GaucovyAero** [comment]
is your game crashing or no?

**Comment by KocTRH2287586** [comment]
> is your game crashing or no?

I've checked today and it didnt crash but the game was unplayable. Frames was low since I removed sodium and sodium extra. It still was unplayable when I added performance mods like Starlight and Moar FPS.

**Comment by GaucovyAero** [comment]
> > is your game crashing or no?
> 
> I've checked today and it didnt crash but the game was unplayable. Frames was low since I removed sodium and sodium extra. It still was unplayable when I added performance mods like Starlight and Moar FPS.

try using the pojavoptimize modpack, its pinned in #general pins on the pojavlauncher discord

**Comment by KocTRH2287586** [comment]
> > > is your game crashing or no?
> > 
> > 
> > I've checked today and it didnt crash but the game was unplayable. Frames was low since I removed sodium and sodium extra. It still was unplayable when I added performance mods like Starlight and Moar FPS.
> 
> try using the pojavoptimize modpack, its pinned in #general pins on the pojavlauncher discord

Can you please, send the file of it, because i dont have discord lol. Thanks.

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/folder/6p1xqhmmihf7x/PojavOptimize

**Comment by GaucovyAero** [comment]
make sure to not try to download the whole folder, that will result in a prompt to buy a subscription
download stuff file by file ok

**Comment by KocTRH2287586** [comment]
> make sure to not try to download the whole folder, that will result in a prompt to buy a subscription download stuff file by file ok

So if there is 2 types of a file with a sodium edition (which is 1.0 and 1.1) do I have to download both of them?

**Comment by GaucovyAero** [comment]
> > make sure to not try to download the whole folder, that will result in a prompt to buy a subscription download stuff file by file ok
> 
> So if there is 2 types of a file with a sodium edition (which is 1.0 and 1.1) do I have to download both of them?

use the optifine edition, its faster

**Comment by KocTRH2287586** [comment]
> use the optifine edition, its faster

The game crashes after I enable the 3D crystals pack, and there still no crash log I think
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13197738/latestlog.txt)
But with the 2D crystals it doesn't crash my game. The modpack really helped tho. You're the best man alive and I wish you the best!

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | fabric-loader-0.14.22-1.19.4 - FABRIC |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | EXTERNAL - JRE - 17 |
| Java arguments | -Xms600m -Xmx3G |



|Errors Found: |
|--|
| java.runtime.wrong.source |

**Comment by GaucovyAero** [comment]
> > use the optifine edition, its faster
> 
> The game crashes after I enable the 3D crystals pack, and there still no crash log I think [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13197738/latestlog.txt) But with the 2D crystals it doesn't crash my game. The modpack really helped tho. You're the best man alive and I wish you the best!

the shaders in the resource pack are probably for newer opengl versions than what gl4es supports unfortunately, cant do anything about that

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | fabric-loader-0.14.22-1.19.4 - FABRIC |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | EXTERNAL - JRE - 17 |
| Java arguments | -Xms600m -Xmx3G |



|Errors Found: |
|--|
| java.runtime.wrong.source |
