### ISSUE TITLE
(forge 1.20+) game closes when minimized

### ISSUE THREAD

**Issue by cyolix** [PojavLauncherTeam/PojavLauncher#4783]
### Describe the bug

Forge 1.20.1 closes when minimized (the back button)  it only happens in forge 1.20+

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/148950843/583be0c3-d2f1-42a4-8ac9-d6582c17c8db

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13197335/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start Minecraft Forge 1.20+
3. Press the back button on your device
```

### Expected Behavior

I expect the game to just be minimized

### Platform

```markdown
- Device model: Vivo Y33S
- CPU architecture: i dont know
- Android version: 11
- PojavLauncher version: Latest Release (on the google play store)
```

**Comment by GaucovyAero** [comment]
you havent sent the logs (send latestlog.txt)

**Comment by cyolix** [comment]
> you havent sent the logs (send latestlog.txt)

done

**Comment by GaucovyAero** [comment]
well thats a funny issue, is that just forge with just optifine?

**Comment by cyolix** [comment]
> well thats a funny issue, is that just forge with just optifine?

mhm

**Comment by GaucovyAero** [comment]
yeah it seems like forge is calling some sort of special snowflake opengl function that gl4es doesnt have when alt tabbing

**Comment by cyolix** [comment]
> yeah it seems like forge is calling some sort of special snowflake opengl function that gl4es doesnt have when alt tabbing

got it, so do i just use a different renderer?

**Comment by GaucovyAero** [comment]
> > yeah it seems like forge is calling some sort of special snowflake opengl function that gl4es doesnt have when alt tabbing
> 
> got it, so do i just use a different renderer?

pretty sure the other ones straight up dont support going out of the window but you can try

**Comment by GaucovyAero** [comment]
[latestlog-1.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13259706/latestlog-1.txt)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/65d3398d-642a-4ebc-b3b7-5b5aab533d6c

[tombstone_34.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13259707/tombstone_34.txt)

successfully reproduced, here are my logs and video

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | edelweiss - 20231104 - feat/activity_destruction_handling |
| Minecraft version | 1.20.1-forge-47.2.0 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 17 |
| Java arguments |  |



|Errors Found: |
|--|
| branch.not.mainline |

**Comment by GaucovyAero** [comment]
nevermind, sorry, you can workaround this,

just change `earlyWindowControl` to `false` in `.minecraft/config/fml.toml`

**Comment by Mathias-Boulay** [comment]
I'll take a look to see if I can fix this without needing a workaround

**Comment by cyolix** [comment]
> nevermind, sorry, you can workaround this,
> 
> just change `earlyWindowControl` to `false` in `.minecraft/config/fml.toml`

how do i edit the toml file?

**Comment by kedrick021** [comment]
How to fix this crash on minimize?

**Comment by GaucovyAero** [comment]
> > nevermind, sorry, you can workaround this,
> > just change `earlyWindowControl` to `false` in `.minecraft/config/fml.toml`
> 
> how do i edit the toml file?

dunno if Acode editor works but i use mixplorer's text editor and it works fine (free download from mixplorer.com)

**Comment by GaucovyAero** [comment]
> nevermind, sorry, you can workaround this,
> 
> just change `earlyWindowControl` to `false` in `.minecraft/config/fml.toml`

@kedrick021

**Comment by kedrick021** [comment]
> > nevermind, sorry, you can workaround this,
> > just change `earlyWindowControl` to `false` in `.minecraft/config/fml.toml`
> 
> @kedrick021

It's working thank you

By the way do you know how to make costume control?

**Comment by GaucovyAero** [comment]
> > > nevermind, sorry, you can workaround this,
> > > just change `earlyWindowControl` to `false` in `.minecraft/config/fml.toml`
> > 
> > 
> > @kedrick021
> 
> It's working thank you
> 
> By the way do you know how to make costume control?

yes

**Comment by kedrick021** [comment]
> > > > nevermind, sorry, you can workaround this,
> > > > just change `earlyWindowControl` to `false` in `.minecraft/config/fml.toml`
> > > 
> > > 
> > > @kedrick021
> > 
> > 
> > It's working thank you
> > By the way do you know how to make costume control?
> 
> yes

Like mcpe icon?

**Comment by GaucovyAero** [comment]
> > > > > nevermind, sorry, you can workaround this,
> > > > > just change `earlyWindowControl` to `false` in `.minecraft/config/fml.toml`
> > > > 
> > > > 
> > > > @kedrick021
> > > 
> > > 
> > > It's working thank you
> > > By the way do you know how to make costume control?
> > 
> > 
> > yes
> 
> Like mcpe icon?

no

**Comment by GaucovyAero** [comment]
fixed in the latest v3_openjdk actions build
