### ISSUE TITLE
[F-Req] <Bedrock Edition Versions>

### ISSUE THREAD

**Issue by KocTRH2287586** [PojavLauncherTeam/PojavLauncher#4784]
### Is this request related to a bug?

Absolutely not.

### Describe the request.

This will affect players to ACTUALLY have two versions of Minecraft in one launcher, only if they bought Java & Bedrock Edition in their Microsoft Account. (Don't do piracy, kids.)

### Anything else?

That's all.

**Comment by artdeell** [comment]
but you can just run mc on your phone

**Comment by KocTRH2287586** [comment]
> but you can just run mc on your phone

Nah I mean, It could be in PojavLauncher since the links that offer you "free minecraft" is probably a virus

**Comment by GaucovyAero** [comment]
pretty sure thats not possible

**Comment by Fl414r** [comment]
> > but you can just run mc on your phone
> 
> Nah I mean, It could be in PojavLauncher since the links that offer you "free minecraft" is probably a virus

Umm how to explain... I'm bad in explaining, but I try.
On phones you can officialy download only bedrock and only if you buy it in Google Play. It's **official** version (yes, Bedrock on PC and Consoles just a official port of mobile version) of Bedrock on phones.
But Pojav ISN'T official launcher, it just fanmade port of Java that allows to launch Minecraft Java. Just a **Fanmade port of engine.** Not even minecraft itself.
