### ISSUE TITLE
[F-Req] Text pasting from Android.

### ISSUE THREAD

**Issue by pachuco** [PojavLauncherTeam/PojavLauncher#4785]
### Describe the request.

Requesting ability to paste text from Android side. In my case, I am trying to paste a world seed in the creation menu.

**Comment by GaucovyAero** [comment]
should be already possible with some keyboards

**Comment by artdeell** [comment]
The user just needs to add CTRL-C and CTRL-V in their controls

вс, 29 окт. 2023 г., 18:41 GaucovyAero ***@***.***>:

**Comment by pachuco** [comment]
I added Ctrl+V button after copying seed on Android side. It did not paste!

**Comment by Fl414r** [comment]
> I added Ctrl+V button after copying seed on Android side. It did not paste!

Idk, try Hackers Keyboard (its Android 4 keyboard with extra buttons like Ctrl or Alt)
I never have problems like your while using this

**Comment by 0913696920** [comment]
Fucktame kick me

Vào Th 2, 30 thg 10, 2023 lúc 17:24 Fl414r ***@***.***> đã
viết:

**Comment by pachuco** [comment]
> > I added Ctrl+V button after copying seed on Android side. It did not paste!
> 
> Idk, try Hackers Keyboard (its Android 4 keyboard with extra buttons like Ctrl or Alt) I never have problems like your while using this

Now that you mention it, I've been long time Unexpected Keyboard user.
