### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by s1QE** [PojavLauncherTeam/PojavLauncher#4788]
### Is this request related to a bug?

Changing language using a physical keyboard does not work in the launcher

**Comment by GaucovyAero** [comment]
not caused by the launcher, we do not modify anything like that

**Comment by s1QE** [comment]
in all games except pressing the launcher the language change works lol

**Comment by Mathias-Boulay** [comment]
huu, this may right as we are only mapped to the physical keys ?

**Comment by Mathias-Boulay** [comment]
No like I want to address it, this would create another layer of translation. Costly.

**Comment by s1QE** [comment]
ммдаа
