### ISSUE TITLE
[BUG] Sodium + GL4ES STILL spamming in logs, I can't play any modpack with at least 50 mods

### ISSUE THREAD

**Issue by Fl414r** [PojavLauncherTeam/PojavLauncher#4789]
### Describe the bug

I don't know why you still can't fix it, but it a really huge problem to me (everyone I think), who NOT have Vulkan 1.1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13203061/latestlog.txt) (2.62mb after one minute. Just wth guys)

### Steps To Reproduce

```markdown
1) Choose GL4ES
2) install Fabric and any version of Sodium
3) Launch it and watch
```

### Expected Behavior

Finally fix it or at least add something to disable all logs.

### Platform

```markdown
- Device model: Honor-9C (Vulkan 1.0)
- CPU architecture: arm-64
- Android version: 9
- PojavLauncher version: [edelweiss-20231020-88149ae-V3_openjdk](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/6685484265)
```

**Comment by sa1672ndo** [comment]
Don't use sodium.

**Comment by Bel69420** [comment]
Even Zink work for your device, doesn't mean it will improve your performance while using Sodium

**Comment by GaucovyAero** [comment]
yeah unfortunately not something thats gonna be fixed right now

**Comment by Fl414r** [comment]
> Even Zink work for your device, doesn't mean it will improve your performance while using Sodium

I literally send you logs in discord that Vulkan mod and Zink just not working on Vulkan 1.0 device
They both have Vulkan 1.1 in requirements

**Comment by Fl414r** [comment]
> Don't use sodium.

Ok, give me anything on Fabric that not worse than sodium, not requires remove half of my mods and not need Vulkan

**Comment by khanhduytran0** [comment]
Sodium requires OpenGL 4, whereas gl4es can only do maximum of limited 3.2. There’s nothing to “fix”, there’s something needs to be replaced: mobile GPU. It doesn’t natively support OpenGL 4.6 with full blown SEUS shader support to begin with.

**Comment by Fl414r** [comment]
> Sodium requires OpenGL 4, whereas gl4es can only do maximum of limited 3.2. There’s nothing to “fix”, there’s something needs to be replaced: mobile GPU. It doesn’t natively support OpenGL 4.6 with full blown SEUS shader support to begin with.

Oh Really?
The Sodium SPAMMING IN LOGS but still WORKS PERFECTLY.
It's only one problem, that Sodium destroys log file!
Sodium ver 4.x also have this bug after devs updated GL4ES, but before this update I used Sodium (even v5) on this "old GPU" without ANY problem

**Comment by Bel69420** [comment]
Because, the sodium patcher remove some features in sodium. That's why it works perfectly

**Comment by Bel69420** [comment]
I mean, Sodium has a feature that GL4ES doesn't support.

**Comment by Bel69420** [comment]
Since GL4ES version is 2.1

**Comment by Bel69420** [comment]
Also, we don't know what's wrong with the log spam

**Comment by Fl414r** [comment]
> Because, the sodium patcher remove some features in sodium. That's why it works perfectly
> 

They fixed it a long time ago lol and before another update that again broken sodium I used it without patcher
