### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by ENDERDERAGON** [PojavLauncherTeam/PojavLauncher#4790]
### Describe the bug

Was

### The log file and images/videos

![Screenshot_2023_1030_214442](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149395149/2efd76ac-bf53-4cb2-a8f7-c82852950e0c)

### Steps To Reproduce

```markdown
Kenapa tidak bisa masuk pojav
```

### Expected Behavior

Kenapa error

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

![Uploading Screenshot_2023_1030_214442.jpg…]()

**Comment by GaucovyAero** [comment]
not an issue with pojav
