### ISSUE TITLE
Render Region

### ISSUE THREAD

**Issue by L1v3p** [PojavLauncherTeam/PojavLauncher#4791]
### Describe the bug

This is the Render Region bug Does anyone know if the creator will fix it?

### The log file and images/videos

![Screenshot_20231008_160635_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/142171751/ba927394-5a66-44f7-96b6-600b8ae281ff)

### Steps To Reproduce

```markdown
1.I go to Configuration and click on rendering and go to render region when I activate crash
```

### Expected Behavior

Let them fix

### Platform

```markdown
- Device model:Samsung A14
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: 3.3.1.1_rel_20210206
```

### Anything else?

Render Region Bug

**Comment by GaucovyAero** [comment]
not supported by gl4es

**Comment by L1v3p** [comment]
Others don't work

**Comment by L1v3p** [comment]
![Screenshot_20231030_183540_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/142171751/bd7a5417-e0d6-4113-8376-8c7efa0a870d)

**Comment by GaucovyAero** [comment]
thats an issue with your phone unfortunately (maybe it doesnt support some other stuff too)

**Comment by L1v3p** [comment]
Will the creator of PojavLauncher fix this?

**Comment by L1v3p** [comment]
It was running before the new version on PojavLauncher

**Comment by GaucovyAero** [comment]
what renderer is that with the red screen? you didnt give any info

**Comment by L1v3p** [comment]
I had the gl4s, the one with the red screen and the zink

**Comment by L1v3p** [comment]
Zink (Vunkan)

**Comment by GaucovyAero** [comment]
zink wasnt even in the release before this

**Comment by GaucovyAero** [comment]
there is no change between angle on the last version and now

**Comment by L1v3p** [comment]
I'm sorry for taking so long to respond, I'm trying to find a way to fix the bug but no news.

**Comment by GaucovyAero** [comment]
its just not supported by your phone, deal with it ig

**Comment by L1v3p** [comment]
Could it be because of the update?

**Comment by GaucovyAero** [comment]
> Could it be because of the update?

~~yes, its also not even a bug, pojav is just missing rendering features which create needs and they are very hard to implement on phones~~

oops, commenting on the wrong issue

**Comment by L1v3p** [comment]
Hi, I'm back if I turn off VBOs in 1.12.2 and turn on Render Region doesn't it bug because?

**Comment by L1v3p** [comment]
Funciona Normal
