### ISSUE TITLE
They should make a Java Emulator within Pojavlauncher

### ISSUE THREAD

**Issue by ErickN13** [PojavLauncherTeam/PojavLauncher#4792]
### Is this request related to a bug?

One thing that the Android System needs is an application that runs any type of Java Program or Java Game, but Pojavlauncher only runs Minecraft (As far as I know),So, they should add a function to Pojavlauncher to be able to run any Java game or program, not just Minecraft

**Comment by Coloryr** [comment]
Use JNI
https://developer.android.google.cn/training/articles/perf-jni?hl=zh-cn
And Pojavteam's `JRE`
https://github.com/PojavLauncherTeam/openjdk-multiarch-jdk8u

**Comment by GaucovyAero** [comment]
pojav can already run another game (Spiral Knights), if you want another game to run pls let us know

**Comment by ErickN13** [comment]
> pojav can already run another game (Spiral Knights), if you want another game to run pls let us know

It would be cool for PojavLauncher to also run (Minicraft LudumDare22), or for PojavLauncher to run any Java8 Game or Program

**Comment by ErickN13** [comment]
**NOTCH's MINICRAFT LD22**

**Comment by ErickN13** [comment]
Or else it would be better when I click:![IMG_20231031_130605.png](https://github.com/PojavLauncherTeam/PojavLauncher/assets/144749573/14c01a88-fcd3-4bf3-9216-e2130309a48d)
, instead of the buttons being these:![Screenshot_20231031-153030.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/144749573/9599fccb-e542-45a8-8b6c-1e20a9029a39)
, it was supposed to be these:![Screenshot_20231031-153103.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/144749573/407d016c-1d3b-4648-a38e-f3eb8929ae2a)
, that's it, I hope they add this in the next version of PojavLauncher

**Comment by GaucovyAero** [comment]
gonna close this, maybe someone can do a PR or make another app for this

**Comment by ErickN13** [comment]
> gonna close this, maybe someone can do a PR or make another app for this

Ok ✔️

**Comment by Coolboy42-89** [comment]
> pojav can already run another game (Spiral Knights), if you want another game to run pls let us know

Why not every game it crashes
