### ISSUE TITLE
How sodium 1.20.2 ?

### ISSUE THREAD

**Issue by NothingMan29** [PojavLauncherTeam/PojavLauncher#4796]
### Describe the bug

Sodium 1.20.2

### The log file and images/videos

Not

### Steps To Reproduce

```markdown
Not
```

### Expected Behavior

Sodium 1.20.2

### Platform

```markdown
Not
```

### Anything else?

Not

**Comment by GaucovyAero** [comment]
[sodium-fabric-mc1.20.2-0.5.3git.81b3e6e-dirty.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/13234722/sodium-fabric-mc1.20.2-0.5.3git.81b3e6e-dirty.zip)

but you are going to get log spam
