### ISSUE TITLE
[BUG] libshaderc.so fails to load on SD845

### ISSUE THREAD

**Issue by Waterdish** [PojavLauncherTeam/PojavLauncher#4800]
### Describe the bug

When using Vulkanmod on the newest PojavLauncher, it crashes after pressing play. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13245701/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install fabric for 1.20.2 or 1.20.1 and install the patched Vulkanmod.
2. Press play
```

### Expected Behavior

The game should launch

### Platform

```markdown
- Device model: Samsung Galaxy S9/Snapdragon 845
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Wasn't sure if this goes in "Mod X doesn't work" or not, but the app fails to load the libshaderc.so library. This issue has been seen with PowerVR devices apparently, but I'm using snapdragon 845 with Adreno 630. Is it perhaps the android version?

**Comment by GaucovyAero** [comment]
rename the issue so that it has SD845 at the end ples

**Comment by GaucovyAero** [comment]
thanks

**Comment by GaucovyAero** [comment]
issue fixed on the latest github actions build
