### ISSUE TITLE
(x86_64) A bunch of dlopen errors for the x86_64/amd64 Java 8 runtime.

### ISSUE THREAD

**Issue by mchnjt** [PojavLauncherTeam/PojavLauncher#4801]
### Describe the bug

I think this bug should've been posted on https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch, but whether it's an existing issue, I'll open one here to see if other people also experienced this issue.

I'm running PojavLauncher on WayDroid, an Android container (@ x86_64 platform) for documentation on the wiki. Here i was trying to use the `INSTALL .JAR` function of the launcher, but every time I do so it just crashes, then closes.

Looking at the logs, i pinpointed the probable cause of why this was happening. It says that there's a library missing for other libraries to work.
![4471b74c-0edd-4a47-b049-eb2a72a186a3](https://github.com/PojavLauncherTeam/PojavLauncher/assets/83752061/2cd48936-01f7-46fc-b504-373b53c14aa9)

Whether this is an existing issue, i would like to report this so that it'll seek attention to other people who had this issue or haven't faced issue on this architecture.

I haven't tried pure Android (Android x86) yet, since it would be a risk to lose all of my files on my laptop. Plus, other operating system and linux distributions failed to have the audio working out of the box.

### The log file and images/videos

Already posted an image of the log above, but i may send it later if ever needed.

### Steps To Reproduce

```markdown
Mentioned.
```

### Expected Behavior

...

### Platform

```markdown
- Device model: CHUWI HeroBook Air
- CPU architecture: x86_64
- Android version: Waydroid, LineageOS 11
- PojavLauncher version: Can't say latest, huh?
```

### Anything else?

Again, i think this is not an issue on the application itself, but rather the runtime environment.

**Comment by Mathias-Boulay** [comment]
As far as I know, it seems to be waydroid specific.
I couldn't reproduce the issue on official x86_64 android images

**Comment by Mathias-Boulay** [comment]
@xenophiee Can we get the full latestlog here ?

**Comment by mchnjt** [comment]
> @xenophiee Can we get the full latestlog here ?

Alright, I'll try to get a chance to install Linux and Waydroid on my laptop again.
