### ISSUE TITLE
Crashing while opening the game 

### ISSUE THREAD

**Issue by IxXLEGXxI** [PojavLauncherTeam/PojavLauncher#4802]
### Describe the bug

Every time I lunch the (Chemical Exchange) modpack it's crashing 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13251261/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Chose (Chemical Exchange-1.12.2-forge-14.23.5.2860)
3. Run the game
4. Crashing
```

### Expected Behavior

I expected to run the modpack without any crashes like it used to be 

### Platform

```markdown
- Device model: OPPO CPH2015
- CPU architecture: 64x
- Android version: 9
- PojavLauncher version:
```

### Anything else?

Any modpack run normally and I didn't add or edit or removed any fill of the modack fills

**Comment by GaucovyAero** [comment]
remove randompatches

**Comment by IxXLEGXxI** [comment]
> remove randompatches

Excuse me please wait fills I should remove again and were it located because I install it directly from the luncher not from curse forge

**Comment by GaucovyAero** [comment]
your modpack should be located in `<pojav directory>/custom_instances/ChemicalExchange (or something like that)`, remove the randompatches mod from your mods and if it crashes, send log again

**Comment by IxXLEGXxI** [comment]
It worked
