### ISSUE TITLE
[BUG] mouse icon issue

### ISSUE THREAD

**Issue by KAZU-YAA** [PojavLauncherTeam/PojavLauncher#4804]
### Describe the bug

the mouse icon dissapears like it cant render halfway down the screen

### The log file and images/videos

cutted icon
![Screenshot_2023-11-04-13-40-08-37](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149859518/d2a02ba4-fd22-4863-8a0f-78df0c652be4)
![Screenshot_2023-11-04-13-40-41-43](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149859518/dff14c5e-0a54-4e0d-8529-b31fa91280ac)
![Screenshot_2023-11-04-13-41-02-70](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149859518/e22118f1-7063-4c47-9df0-0dd8f93cf93)

normal icon
![Screenshot_2023-11-04-13-41-11-37](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149859518/9c02918c-d716-4a42-b2d9-4863e63dc1ab)

### Steps To Reproduce

```markdown
1. modify certain game controls (like mouse icon size)
2. try it out
```

### Expected Behavior

i expect the mouse icon to be normal

### Platform

```markdown
- Device model: Oppo A3s
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: latest gplay ver
```

**Comment by Lesa001** [comment]
Hi

**Comment by GaucovyAero** [comment]
either disable alternate surface rendering or make your controlmap so that you have a button on each corner of the screen, not possible to fix unfortunately
