### ISSUE TITLE
Turnip Updated

### ISSUE THREAD

**Issue by LecitronArts** [PojavLauncherTeam/PojavLauncher#4805]
### Describe the request.

https://github.com/K11MCH1/AdrenoToolsDrivers/releases/tag/v23.3.0_R8
a730 variant support. (Fixes the crashes 8+ gen1 and 7+ gen2 were having from Turnip Revision 5 and up.)

**Comment by GaucovyAero** [comment]
will only be added once its an official release, you will have to wait a pretty long time, but in the meantime you can fork pojav and update it yourself

**Comment by GaucovyAero** [comment]
ill close this issue because it doesnt really serve a purpose if its gonna be actually updated, just not today, later
