### ISSUE TITLE
Crashing when join world

### ISSUE THREAD

**Issue by Komnapas** [PojavLauncherTeam/PojavLauncher#4806]
### Describe the bug

When i join server it crashing with code -1

### The log file and images/videos

[latestlog-2.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13257273/latestlog-2.txt)

### Steps To Reproduce

```markdown
1. Start pojav
2. Join server
3. Crashing Code -1
```

### Expected Behavior

I expect the game to launch 

### Platform

```markdown
- Device model: poco x3 nfc 6/64
- CPU architecture: kyro470
- Android version: 12
- PojavLauncher version: latest in playstore
```

**Comment by GaucovyAero** [comment]
your optifine and forge are incompatible (you would get a crash on pc too), try using different versions of them to see if you can get it working, optifine always has on their site which version of forge its compatible with
