### ISSUE TITLE
Add "external login" function

### ISSUE THREAD

**Issue by gumen2258** [PojavLauncherTeam/PojavLauncher#4807]
### Is this request related to a bug?

![Uploading Screenshot_20231105_122722_com.tungsten.hmclpe.jpg…]()

### Describe the request.

Use external login. Log in with the authentication server.

**Comment by GaucovyAero** [comment]
attach the screenshot pls, it didnt upload

**Comment by gumen2258** [comment]
> attach the screenshot pls, it didnt upload

![Screenshot_20231105_122722_com.tungsten.hmclpe.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136236969/7762b959-5aa0-4d20-aedb-97955ac1fce2)

**Comment by gumen2258** [comment]
就是这个功能。
> attach the screenshot pls, it didnt upload

![无标题95_20231105194313.png](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136236969/6294191d-f28f-4f3a-af83-87071b1ec9b2)

**Comment by GaucovyAero** [comment]
not going to be done
