### ISSUE TITLE
Clients

### ISSUE THREAD

**Issue by benaw386** [PojavLauncherTeam/PojavLauncher#4808]
### Describe the bug

I install clients like Pluto, Ares, Cloud on a chromebook, it lets me put the jar in the .minecraft folder but not versions. anyone got a fix?
![Screenshot 2023-11-05 07 56 30](https://github.com/PojavLauncherTeam/PojavLauncher/assets/141126510/4a8848c7-1423-4395-aaeb-9fa71809ef54)

### The log file and images/videos

client.jar - .minecraft - succesfully done - client.jar - versions - could not move, the file or directory can not be used.

### Steps To Reproduce

```markdown
lalalalala
```

### Expected Behavior

lallalalalalal### lalalallalalalala

### Platform

```markdown
- Device model: Chromebook Flex 5
- CPU architecture: 64bit
- Android version: Chrome Os (latest and not android)
- PojavLauncher version: latest
```

### Anything else?

nothin

**Comment by GaucovyAero** [comment]
use zarchiver or mixplorer as your file manager (free download from https://mixplorer.com/

**Comment by GaucovyAero** [comment]
keep in mind you may still get a crash using those clients if they have integrated discordrpc and dont continue if it doesnt load, or if gl4es doesnt support the shaders that their hacks use
