### ISSUE TITLE
[F-Req] <Update Mesa Zink to the latest>

### ISSUE THREAD

**Issue by PegNattha** [PojavLauncherTeam/PojavLauncher#4809]
### Describe the request.

is Mesa 23.2 or 23.3

**Comment by Bel69420** [comment]
Iirc, Mesa 23.2 used Vulkan 1.3, if we update it to this version, maybe it will crash on Mali Devices since it used Vulkan 1.1.

**Comment by sa1672ndo** [comment]
Feel free to fork pojav, update mesa to 23.3 and then make a pull request with a working build.

**Comment by GaucovyAero** [comment]
yeah exactly 👍
