### ISSUE TITLE
[BUG] Simple Voice Chat on 1.12.2 does not work.

### ISSUE THREAD

**Issue by Seilcommand** [PojavLauncherTeam/PojavLauncher#4810]
### Describe the bug

So when I try to add a microphone or speaker it says that there is no speaker/microphone 
Is it possible to use a voice chat mod on Pojav Laucher and if so how does it work.
Mod I used:Simple Voice Chat 1.12.2/2.4.27

### The log file and images/videos

Do I still need a log file for this?

### Steps To Reproduce

```markdown
1.Install Simple Voice Chat(Forge) Mod for 1.12.2/2.4.27
2.Launch Pojav Launcher/start the game
3.Go into Mods(in game)
4.Config Simple Voice Chat 
5.Select microphone/speaker
```

### Expected Behavior

I expected it to use the phone speaker/microphone or a Bluetooth one.

### Platform

```markdown
- Device model: Samsung Galaxy A20e 
- CPU architecture: ARMv8-A
- Android version: 11
- PojavLauncher version:version20230928
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by GaucovyAero** [comment]
make sure you have microphone permission enabled for pojav in android settings
