### ISSUE TITLE
[ZINK] Improve performances if possible.

### ISSUE THREAD

**Issue by Username10926663** [PojavLauncherTeam/PojavLauncher#4811]
### Is this request related to a bug?

I love zink but it does give me low fps it is possible to improve it so it give atleast 60fps? im using optifine but nothing. still low fps.
![Screenshot_20231105-141059_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139702541/34c8a065-ce1e-4776-9d60-0685753d23ab)

### Describe the request.

already said. 

### Anything else?

nothing else.

**Comment by Username10926663** [comment]
oops sorry i put the issue in it is related to a bug i didnt saw.

**Comment by GaucovyAero** [comment]
you are lucky that it even works on your phone lol, not possible
if you want more fps, buy a faster phone

**Comment by Username10926663** [comment]
i dont think its possible to get high fps on zink (more than 30) almost everyone has this issue too unless we use patched vulkanmod
