### ISSUE TITLE
[BUG] Destroyed mutex

### ISSUE THREAD

**Issue by RandomGuy6767** [PojavLauncherTeam/PojavLauncher#4814]
### Describe the bug

Application closed with code -1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13260358/latestlog.txt)

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I expected for it to launch

### Platform

```markdown
- Device model: Chrome OS (Linux Debian)(Lenvo)
- CPU architecture: idk
- Android version:118.0.5993.124 (Official Build) (64-bit) 
- PojavLauncher version:Latest
```

**Comment by RandomGuy6767** [comment]
Code:0x7a8430975538

**Comment by artdeell** [comment]
allocate more ram

**Comment by GaucovyAero** [comment]
out of memory, allocate more ram,

if you cant, maybe try using something like tinybit launcher as your system launcher to reduce ram usage and use com.kosajun.easymemorycleaner as your ram cleaner

if this doesnt help you, you gotta install a less intensive modpack
