### ISSUE TITLE
[BUG] physical keyboard being weird 

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4820]
### Describe the bug

Every time i do click something it shows the typing thingy unless i click esc key

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/101394924/9da3683c-51e1-477c-b50f-829d0a542aef

> 

### Steps To Reproduce

```markdown
Start pojav
Load into world
Try to walk or do something
Problem happens
```

### Expected Behavior

I expected to not see the phone keyboard 

### Platform

```markdown
- Device model: honor x6 
- CPU architecture: idk 
- Android version: 12
- PojavLauncher version: latest store version
```

### Anything else?

This happens after 3-4 minutes playing every time also show virtual keyboard is turned off

**Comment by GaucovyAero** [comment]
hmm honestly no idea, another huawei issue it seems like

**Comment by GaucovyAero** [comment]
maybe try using a different physical keyboard? in one part of your video it seems like your left arrow is stuck down, which should not be happening

**Comment by hiimabignoobwihenolive** [comment]
Sorry i can't sell another kidney

**Comment by hiimabignoobwihenolive** [comment]
But I'll try to fix the left arrow key

**Comment by GaucovyAero** [comment]
> Sorry i can't sell another kidney

just borrow one for 5 minutes from a friend or family member

**Comment by hiimabignoobwihenolive** [comment]
i CAN NOT catch a break now a days!

**Comment by hiimabignoobwihenolive** [comment]
I changed the virtual keyboard into another keyboard (Microsoft swift key) and it happened but this time different

**Comment by hiimabignoobwihenolive** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/101394924/12ff2070-036a-4f9e-9835-e0240f65b3cb

I cannot move expected my mouse and i can't use esc to get out of this

**Comment by GaucovyAero** [comment]
im probably not correct about this but i think you are somehow pressing a key combination that opens the virtual keyboard

**Comment by hiimabignoobwihenolive** [comment]
I mean it says that pressing alt+shift+space would open it but i don't click alt but that could be the problem

**Comment by hiimabignoobwihenolive** [comment]
I think its because when open the gui it happens because the keyboard button is super colse to the gui button

**Comment by hiimabignoobwihenolive** [comment]
I will change its place

**Comment by hiimabignoobwihenolive** [comment]
I think pojav is force opening the keyboard so it does this I think i fixed by removing the keyboard button so its working fine now
