### ISSUE TITLE
[F-Req] is there a way to increase the hud size?

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4822]
### Is this request related to a bug?

Maybe

### Describe the request.

The hud size is wayy too small at lower game resolutions which is quite annoying is There a mod make them bigger or a built in feature that makes them larger?

### Anything else?

I know its not requesting a feature but i cannot ask for help anywhere else (it can be a feature if you can add it in the pojav settings)

**Comment by GaucovyAero** [comment]
i want to make such a mod, but i dont know how to do it right now. for now you can decrease the resolution further and buttons will become bigger

**Comment by hiimabignoobwihenolive** [comment]
> i want to make such a mod, but i dont know how to do it right now. for now you can decrease the resolution further and buttons will become bigger

Now i can count the number of pixels on my screen thanks!!
