### ISSUE TITLE
[F-Req] showing the mod loader in modpack downloads?

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4823]
### Is this request related to a bug?

being able to see what type of modloader the modpack using like fabric or forge and possibly show the Minecraft version 

### Describe the request.

![Screenshot_20231108_184122](https://github.com/PojavLauncherTeam/PojavLauncher/assets/101394924/d1b7c36a-53f7-4031-a2e7-102cdbf9852b)

### Anything else?

Its annoying that i need to go to the website and look at the modpack

**Comment by GaucovyAero** [comment]
im pretty sure that cannot be implemented, and thats because it isnt reported on the modpack page

![Screenshot_20231108-195303_Fennec](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/c78c6ecf-2238-4bae-81c3-88ebc25940df)

**Comment by artdeell** [comment]
> im pretty sure that cannot be implemented, and thats because it isnt reported on the modpack page
> 
> ![Screenshot_20231108-195303_Fennec](https://user-images.githubusercontent.com/85581164/281512154-c78c6ecf-2238-4bae-81c3-88ebc25940df.png)

It is reported but not always
Which woudl generate even more complaints than rn
