### ISSUE TITLE
Mouse click 

### ISSUE THREAD

**Issue by NegixD** [PojavLauncherTeam/PojavLauncher#4825]
### Describe the bug

 when I click with the mouse, on pojavlucher the place where the mouse is located does not click and the one next to it clicks. And I attached mouse in pojavlucher the same problem with mouse 

### The log file and images/videos

 when I click with the mouse, the place where the mouse is located does not click and the one next to it clicks.

https://github.com/PojavLauncherTeam/PojavLauncher/assets/150320665/8d31ff7b-d069-4900-ac70-56b3da7a094d

https://github.com/PojavLauncherTeam/PojavLauncher/assets/150320665/b87f82fc-f3eb-4480-8b72-a2b05f91f1a5

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Idk

**Comment by GaucovyAero** [comment]
enable the ignore notch setting in the launcher, this is caused by your phone improperly reporting the notch size. if you are on android 8.1 and lower, the setting wont show up and you wont be able to fix this (because the first android notch implementation was in android 9)

**Comment by NegixD** [comment]
How?

**Comment by GaucovyAero** [comment]
pojav settings - video and renderer - ignore notch

**Comment by NegixD** [comment]
> pojav settings - video and renderer - ignore notch

Bro it's not their 

![Screenshot_20231110_185537](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150320665/622e209c-c76a-40ee-83e1-051989f53941)
