### ISSUE TITLE
[F-Req] <Add VirGL (Vulkan)>

### ISSUE THREAD

**Issue by PegNattha** [PojavLauncherTeam/PojavLauncher#4826]
### Describe the request.

Using Vulkan on VirGL

**Comment by sa1672ndo** [comment]
"mom can we have zink"
"we already have zink at home"
zink at home: 
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/87911255/4d3057fd-f001-4e7c-91ac-99db24524829)

**Comment by GaucovyAero** [comment]
virgl runs on opengl es lol, and virgl wont be added again, as its very buggy and slow
