### ISSUE TITLE
Create mod Crash

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4828]
### Describe the bug

When I try to build something on create mod it's crash my game like steam engine 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13322999/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Create World
3. Build something on create mod
4. Crash
```

### Expected Behavior

No crash 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

Please help

**Comment by kedrick021** [comment]
Using angle render

**Comment by kedrick021** [comment]
Again this mod is working fine on older version

**Comment by GaucovyAero** [comment]
no workaround known yet, i mean we wont really add stuff into angle, thats a renderer that google itself maintains, not us

**Comment by kedrick021** [comment]
> no workaround known yet, i mean we wont really add stuff into angle, thats a renderer that google itself maintains, not us

Create mod using holygl4es
Keep crashing do you know how to fix?

**Comment by GaucovyAero** [comment]
> > no workaround known yet, i mean we wont really add stuff into angle, thats a renderer that google itself maintains, not us
> 
> Create mod using holygl4es Keep crashing do you know how to fix?

no

**Comment by kedrick021** [comment]
> > > no workaround known yet, i mean we wont really add stuff into angle, thats a renderer that google itself maintains, not us
> > 
> > 
> > Create mod using holygl4es Keep crashing do you know how to fix?
> 
> no

There a future work this mod on your project?

**Comment by GaucovyAero** [comment]
> > > > no workaround known yet, i mean we wont really add stuff into angle, thats a renderer that google itself maintains, not us
> > > 
> > > 
> > > Create mod using holygl4es Keep crashing do you know how to fix?
> > 
> > 
> > no
> 
> There a future work this mod on your project?

probably not

**Comment by JaydevGaming4** [comment]
Create mod crash problem
Fix this problem
New angel render (vulkan) crash
Old pojav Angel no crash

**Comment by JaydevGaming4** [comment]
Pojavlauncher create mod crash problem fix this

**Comment by Not905** [comment]
I have same problem but still not solve pls help

**Comment by casherka** [comment]
Try a ltw visualiser. 90% works!
