### ISSUE TITLE
Can't write DOT on "server address"

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#483]
Android: 10
Minecraft ver: 1.12.2
PojavLauncher: newest

pla fix :(

**Comment by khanhduytran0** [comment]
Latest Action build?

**Comment by pstube** [comment]
Try using direct connection as a temporary measure

**Comment by khanhduytran0** [comment]
@ZetingX please reply

**Comment by khanhduytran0** [comment]
Use latest build
