### ISSUE TITLE
can't run raven b4

### ISSUE THREAD

**Issue by BetterHitred** [PojavLauncherTeam/PojavLauncher#4831]
### Describe the bug

Once I enter the Mojang image, I get exit code 1

### The log file and images/videos

https://www.mediafire.com/file/r0dksxvvshhbj1u/latestlog.txt/file

### Steps To Reproduce

```markdown
1. I put Raven b4 into the mod file 2. I use gl4s rendering to get it when I enter a lag with code 1
```

### Expected Behavior

I hope to have Raven b4 live on pojavlaucher soon

### Platform

```markdown
- Device model: oppo reno4 
- CPU architecture: Adreno (TM) 618 @ 750 MHz
- Android version: 12.1
- PojavLauncher version: forge 1.8.9
```

### Anything else?

The raven file contains a very long file name and this is the raven b4 link https://www.mediafire.com/file/iw6r9keqgbelrwo/raven-b4-crack.jar/file

**Comment by GaucovyAero** [comment]
likely an issue with your installation, not in pojav
if it is in pojav, it would be pretty hard to figure out lol, first time seeing this issue
