### ISSUE TITLE
Raven b4 not working

### ISSUE THREAD

**Issue by BetterHitred** [PojavLauncherTeam/PojavLauncher#4832]
### Describe the bug

Raven b4 is not working and it has exit code 1

### The log file and images/videos

https://www.mediafire.com/file/r0dksxvvshhbj1u/latestlog.txt/file video:https://www.mediafire.com/file/bncrg84yo1365k0/az_recorder_20231111_194551.7z/file 

### Steps To Reproduce

```markdown
When entering at a time, exit code 1
```

### Expected Behavior

I hope to have Raven b4 live on pojavlaucher soon

### Platform

```markdown
- Device model: oppo reno4 
- CPU architecture: Adreno (TM) 618 @ 750 MHz
- Android version: V12.1
- PojavLauncher version: forge1.8.9
```

### Anything else?

I hope to have Raven b4 live on pojavlaucher soon

**Comment by tibetpro** [comment]
Same
