### ISSUE TITLE
[BUG] correr para frente controle

### ISSUE THREAD

**Issue by Gatosmias** [PojavLauncherTeam/PojavLauncher#4834]
### Describe the bug

When I go to run forward in any version of Minecraft in Pojav within a world when I click on the run button and hold it goes backwards instead of forward in any version it's not the control because the control is working normal.          

### The log file and images/videos

`

https://github.com/PojavLauncherTeam/PojavLauncher/assets/150546039/be86596b-1f4d-40ae-9c9f-3e93b02e275b

### Steps To Reproduce

```markdown
1 enter minecraft java inside pojavlancher 2 you can enter the world if you want 3 hold the run button and start forward
```

### Expected Behavior

Don't pull when running forward 

### Platform

```markdown
- Device model: sm-m127f/ds
- CPU architecture: Exynos 850
- Android version: 13
- PojavLauncher version: recent
```

**Comment by GaucovyAero** [comment]
please keep speaking in portuguese (not english) so that the conversation can be more accurate, you will have to translate my replies tho

try using the latest github actions build, which has better controller support, guide is on the pojav wiki https://pojavlauncherteam.github.io/
