### ISSUE TITLE
[BUG] Game exited with Error 6

### ISSUE THREAD

**Issue by qriii** [PojavLauncherTeam/PojavLauncher#4835]
### Describe the bug

If I try to go in any kind of version this error shows up… 
![IMG_0533](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150556458/ba07d299-3f00-4ea5-8271-d904dade4281)

### The log file and images/videos

[Pre-Init] PojavLauncher INIT!
[Pre-Init] Version: 2.2-development
[Pre-Init] Commit: d9877bc (main)
[Pre-Init] Device: iPhone 14
[Pre-Init] iOS 17.0.3 (Unjailbroken)
[Pre-init] Entitlements availability:
* com.apple.developer.kernel.extended-virtual-addressing: NO
* com.apple.developer.kernel.increased-memory-limit: NO
* com.apple.private.security.no-sandbox: NO
* dynamic-codesigning: NO
[Debugging] Debug log enabled: YES
[Pre-init] Restored game directory preference (default)
[MCDL] Downloading 1.8.9
[MCDL] SHA1 passed for 1.8.9.json
[MCDL] Downloading 1.8
[MCDL] SHA1 passed for 1.8.json
[MCDL] SHA1 passed for netty-1.8.8.jar
[MCDL] SHA1 passed for oshi-core-1.1.jar
[MCDL] Begin: download libraries
[MCDL] SHA1 passed for jna-5.13.0.jar
[MCDL] SHA1 passed for platform-3.4.0.jar
[MCDL] SHA1 passed for icu4j-core-mojang-51.2.jar
[MCDL] SHA1 passed for jopt-simple-4.6.jar
[MCDL] SHA1 passed for codecjorbis-20101023.jar
[MCDL] SHA1 passed for codecwav-20101023.jar
[MCDL] SHA1 passed for libraryjavasound-20101123.jar
[MCDL] SHA1 passed for librarylwjglopenal-20100824.jar
[MCDL] SHA1 passed for soundsystem-20120107.jar
[MCDL] SHA1 passed for netty-all-4.0.23.Final.jar
[MCDL] SHA1 passed for guava-17.0.jar
[MCDL] SHA1 passed for commons-lang3-3.3.2.jar
[MCDL] SHA1 passed for commons-io-2.4.jar
[MCDL] SHA1 passed for commons-codec-1.9.jar
[MCDL] SHA1 passed for jinput-2.0.5.jar
[MCDL] SHA1 passed for jutils-1.0.0.jar
[MCDL] SHA1 passed for gson-2.2.4.jar
[MCDL] SHA1 passed for authlib-1.5.21.jar
[MCDL] SHA1 passed for realms-1.7.59.jar
[MCDL] SHA1 passed for commons-compress-1.8.1.jar
[MCDL] SHA1 passed for httpclient-4.3.3.jar
[MCDL] SHA1 passed for commons-logging-1.1.3.jar
[MCDL] SHA1 passed for httpcore-4.3.2.jar
[MCDL] SHA1 passed for log4j-api-2.0-beta9.jar
[MCDL] SHA1 passed for log4j-core-2.0-beta9.jar
[MCDL] Skipped library org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209
[MCDL] Unknown artifact object for org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822, attempting to generate one
[MCDL] Unknown artifact object for net.java.jinput:jinput-platform:2.0.5, attempting to generate one
[MCDL] Skipped library org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209
[MCDL] Skipped library org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209
[MCDL] Skipped library org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[MCDL] Skipped library org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[MCDL] SHA1 passed for twitch-6.5.jar
[MCDL] Unknown artifact object for tv.twitch:twitch-platform:6.5, attempting to generate one
[MCDL] Unknown artifact object for tv.twitch:twitch-external-platform:4.5, attempting to generate one
[MCDL] Skipped library org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[MCDL] Skipped library net.java.jinput:jinput-platform:2.0.5
[MCDL] Skipped library tv.twitch:twitch-platform:6.5
[MCDL] Skipped library tv.twitch:twitch-external-platform:4.5
[MCDL] SHA1 passed for 1.8.9.jar
[MCDL] Finished: download libraries
[MCDL] Begin: download assets
[MCDL] Finished: download assets
[MCDL] SHA1 passed for 732/734 asset files
Note: some files of 1.19+ are skipped to workaround an issue
Debug option skipped waiting for JIT. Java might not work.
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/378062C6-0F8D-4181-998B-5EBC87E6FEC9/Documents/Library/Application Support/minecraft/versions/1.8.9/1.8.9.json, have to assume it's good.
[MCDL] SHA1 passed for 1.8.json
[JavaLauncher] Beginning JVM launch
[JavaLauncher] Restored preference: JAVA_HOME is set to /var/containers/Bundle/Application/9172A6F8-EEE3-476B-B9CB-CE39320C6746/PojavLauncher.app/java_runtimes/java-17-openjdk
[JavaLauncher] Restored preference: RENDERER is set to libOSMesaOverride.dylib
[JavaLauncher] Max RAM allocation is set to 4833 MB
[Init] Found JLI lib
[Init] Calling JLI_Launch
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x000000013f2a00bc, pid=5256, tid=60167
#
# JRE version:  (17.0.8) (build )
# Java VM: OpenJDK 64-Bit Server VM (17.0.8-internal+0-adhoc.eilionoir.openjdk, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# Problematic frame:
# v  ~StubRoutines::call_stub
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /private/var/mobile/Containers/Data/Application/378062C6-0F8D-4181-998B-5EBC87E6FEC9/Documents/instances/default/hs_err_pid5256.log
#
#
abort() called

### Steps To Reproduce

```markdown
1. Start any kind of Version on Pojav
```

### Expected Behavior

Start normally

### Platform

```markdown
- Device model: IPhone 14
- CPU architecture: x86 ???
- IOS version: 17.2.0
- PojavLauncher version: 2.2
```

**Comment by GaucovyAero** [comment]
this is not the ios repository, go to PojavLauncherTeam/PojavLauncher_iOS 
ios 17 is not supported yet
