### ISSUE TITLE
[BUG] Can't install maps with datapecks

### ISSUE THREAD

**Issue by Carol3301** [PojavLauncherTeam/PojavLauncher#4836]
### Describe the bug

So, I don't know if I should post this here, but I don't know where to post it, when I try to install a map with datapecks, when moving the file to the "saves" folder, Zachiver gives the error saying that access was denied.

### The log file and images/videos

![Screenshot_20231111_214012_ZArchiver](https://github.com/PojavLauncherTeam/PojavLauncher/assets/134178773/f9b46117-9f4a-474a-9cc4-a4f343f3bba8)

### Steps To Reproduce

```markdown
Try install a map with datapecks😭

(The map I tried to install was the pickaxe quest)
```

### Expected Behavior

The map file should normally be copied to the "saves" folder

### Platform

```markdown
- Device model: S20 FE 5G
- CPU architecture: kryo 585
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try extracting the zip first, then copy over the files
