### ISSUE TITLE
[F-Req] <Short description>Mouse scroll

### ISSUE THREAD

**Issue by ZingMCPC** [PojavLauncherTeam/PojavLauncher#4837]
### Is this request related to a bug?

No

### Describe the request.

You should add a mouse wheel to make it more convenient to use the scrolls cilent

### Anything else?

I want pojavlauncher to have mouse scrolling soon

**Comment by GaucovyAero** [comment]
add the buttons SPECIAL_SCROLLUP and SPECIAL_SCROLLDOWN into your controlmap
