### ISSUE TITLE
[BUG] Region Render not working in PojavLauncher but work in FCL

### ISSUE THREAD

**Issue by Username10926663** [PojavLauncherTeam/PojavLauncher#4838]
### Describe the bug

What's happening ?
Well the Region Render in PojavLauncher like everyone know has a issue it show a black screen but in fold craft launcher it works properly using gl4es.
![Picsart_23-11-12_13-44-01-141](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139702541/0138313c-cb80-45b0-b4b9-a730b894a8bd)

### The log file and images/videos

none for me as it doesn't crash.

### Steps To Reproduce

```markdown
start PojavLauncher
use region render
crash or black screen with lags.
```

### Expected Behavior

expected Region render to work on PojavLauncher 

### Platform

```markdown
- Device model: Samsung 
- CPU architecture: ???
- Android version: 12 
- PojavLauncher version: Beta (from Vera Firefly)
```

**Comment by genericgithubaccount185** [comment]
traitor, hang him by the balls

**Comment by Mathias-Boulay** [comment]
fun fact it actually doesn't work on fcl either, the actual reason is due to a known mistake in declaring what's supported

**Comment by Jdvdhtdmxh** [comment]
Fold craft is better fuck pojavlauncher 💀

**Comment by L1v3p** [comment]
Mine is glitching all over the screen, buggy chunk.

**Comment by Inverted-Fin** [comment]
maybe fcl better than pojav?

**Comment by Proaman7603** [comment]
Is FCL is better than pojav?

**Comment by sa1672ndo** [comment]
> Is FCL is better than pojav?

Fcl is basically pojav but old and with a lot of useless renderers.

**Comment by sa1672ndo** [comment]
They literally copy shit from pojav and add nothing new.

**Comment by Username10926663** [comment]
> They literally copy shit from pojav and add nothing new.

Totally , but its weird thats render region works on Fcl and not pojav using gl4es though maybe they use a old gl4es version that dkes support render reg

**Comment by Mathias-Boulay** [comment]
it doesn't work on fcl either, they just disable the feature internally :sweat_smile:

**Comment by KaydenJR2310** [comment]
No, the render region did work, but it's only on 1.12.2 until 1.16.5. The render region may not work on minecraft version 1.17 up. Also, in 1.16.5, if you use render region, it did not crash your game, but just makes the texture glitched up.
