### ISSUE TITLE
[BUG] texture Not in full proportion

### ISSUE THREAD

**Issue by tibetpro** [PojavLauncherTeam/PojavLauncher#4839]
### Describe the bug

When I installed the texture pack, it turned out that the sword and other things I was holding were out of proportion and when I opened them ui client Make tech see it through and make tech see it through and bug.

### The log file and images/videos

![Screenshot_2023-11-07-18-10-02-326_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150565667/34d0be8a-e3aa-4954-a909-b8d744ab6c2a)

### Steps To Reproduce

```markdown
I enter the map and I open ui client it And then when I turn off the texture, it crashes.
```

### Expected Behavior

Please fix It's been buggy for a long time.

### Platform

```markdown
- Device model: Poco m5s 
- CPU architecture: MediaTex Helio G90 2.05 Ghz
- Android version: 13
- PojavLauncher version: 1.8.9-1.12.2
```

### Anything else?

![Screenshot_2023-11-12-22-26-06-623_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150565667/3fef08b5-80d5-4734-b3c7-6b1ad5931cb0)
![Screenshot_2023-11-12-22-25-54-397_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150565667/ac239064-1c45-4334-bccb-3e3ab132ae00)
![Screenshot_2023-11-12-22-25-35-300_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150565667/6ef43006-3a25-41a7-955b-2f294cffa724)

m It bugged when I applied the texture pack.

**Comment by Username10926663** [comment]
Its probably due to opengl version being too old or missing GL extensions in your device

**Comment by GaucovyAero** [comment]
you can ""fix"" the see-through bug by pressing f11
and the issues with swords will be addressed later, we already know how to fix those

**Comment by tibetpro** [comment]
I've already tried it ui Again it was, I just tried pressing f11 Again, it appears that it was the same.

**Comment by GaucovyAero** [comment]
> I've already tried it ui Again it was, I just tried pressing f11 Again, it appears that it was the same.

then you can try disabling and enabling fast render, though it might not work, it may also be caused by some mod

**Comment by tibetpro** [comment]
SigmaNg client
