### ISSUE TITLE
Can I play java 1.16.4 extremely without major lags.

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#484]
Can I play java 1.15.2 and above extreme with forge or optifine or fabric without major lags on POCO M2 
6 gb ram 64 gb storage ARMv8.

**Comment by khanhduytran0** [comment]
How much fps?

**Comment by khanhduytran0** [comment]
Also make sure you on JRE8 instead of JRE9. At least screenshot debug screen.

**Comment by ghost** [comment]
> Also make sure you on JRE8 instead of JRE9. At least screenshot debug screen.



> How much fps?

This device isn't currently available because.
It is to be arriving from FLIPKART on 31st December.

**Comment by ghost** [comment]
But how to check whether jre8 or jre9.

**Comment by ghost** [comment]
Can you develop an app which adds custom controls on any games?
I wanna play with the custom controls.
I would love if you help.

**Comment by ghost** [comment]
> But how to check whether jre8 or jre9.

If possible plis send a gif video

**Comment by Kirillka22** [comment]
Try changing amount of ram minecraft using. Settings : JVM. And change numbers afrer xms and xmx to bigger ones

**Comment by WesleyVanNeck** [comment]
> > But how to check whether jre8 or jre9.
> 
> If possible plis send a gif video


use the debug button

**Comment by WesleyVanNeck** [comment]
in game ofc

**Comment by ghost** [comment]
I can't play the game on this 1 gb ram device @LegacyGamerHD .
I'll get a new device on 31st December

**Comment by ghost** [comment]
Isn't there another way to check.
Rather in game

**Comment by khanhduytran0** [comment]
> Isn't there another way to check.
> Rather in game

Other way: requires root.

Better use old version as 1.7.10 then join world and screenshot debug screen.

**Comment by ytuy404** [comment]
у меня в 60 фпс идёт с 8 чанками

**Comment by ghost** [comment]
I would play both mcinabox and pojav launcher now.
