### ISSUE TITLE
[BUG] <Short description>extermal mouse problem

### ISSUE THREAD

**Issue by Jdvdhtdmxh** [PojavLauncherTeam/PojavLauncher#4841]
### Describe the bug

https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/b229d413-6d9f-4854-8850-e795e7246a3f

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/991a0146-daa5-499a-8387-3470b300b9b8

### Steps To Reproduce

```markdown
Start pojavlauncher and try external mouse
```

### Expected Behavior

I don't know 💀

### Platform

```markdown
- Device model:infinix
- CPU architecture:dimensity
- Android version:12
- PojavLauncher version:all
```

### Anything else?

Fuck pojavlauncher fold craft is better

**Comment by GaucovyAero** [comment]
duplicate
