### ISSUE TITLE
How do i install other java versions ?[F-Req]

### ISSUE THREAD

**Issue by LeonardoCT** [PojavLauncherTeam/PojavLauncher#4842]
### Is this request related to a bug?

More a question than a feature request, but where do i find other and older java runtimes (like java 8)? i can't find a download for it.

It would be great if the application had a built in downloader for other and older java runtimes

**Comment by GaucovyAero** [comment]
a downloader wont be built in, but heres the link https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions
