### ISSUE TITLE
My forge keeps crashing in versions below 1.16

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#4845]
![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13338321/latestlog.txt)

**Comment by GaucovyAero** [comment]
1.15.2 should be launched with java 8

**Comment by aura123lol** [comment]
> 1.15.2 should be launched with java 8

It's still crashing

**Comment by aura123lol** [comment]
> 1.15.2 should be launched with java 8

It's still crashing

**Comment by aura123lol** [comment]
> 1.15.2 should be launched with java 8

It's still crashing

**Comment by aura123lol** [comment]
> 1.15.2 should be launched with java 8

It's still crashing

**Comment by aura123lol** [comment]
> 1.15.2 should be launched with java 8

Brother it's still crashing 
![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13339686/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | PRODUCTION |
| Pojav version | edelweiss - 20230928 - v3_openjdk |
| Minecraft version | 1.7.10-forge10.13.4.1614-1.7.10 - FORGE |
| Renderer | GL4ES_115 |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 8 |
| Java arguments |  |

**Comment by GaucovyAero** [comment]
> > 1.15.2 should be launched with java 8
> 
> Brother it's still crashing

this is a totally different issue lol, your forge libraries are missing, make sure you have the libraries check enabled and reinstall forge

**Comment by aura123lol** [comment]
> > > 1.15.2 should be launched with java 8
> > 
> > Brother it's still crashing
> 
> this is a totally different issue lol, your forge libraries are missing, make sure you have the libraries check enabled and reinstall forge

Real
