### ISSUE TITLE
Sodium does not work, even after launching the Sodium patcher

### ISSUE THREAD

**Issue by Haygao** [PojavLauncherTeam/PojavLauncher#4846]
### Describe the bug

Before using the Sodium patcher, If there is Sodium or another not working mod in the mods folder, there was an endless black screen that, before loading, with text "Mojang". And after the Sodium patcher, the loading screen itself with the text “Mojang” became endless. The loading bar almost reaches the end, but stops forever. Minecraft version 1.20.1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13339438/latestlog.txt)

### Steps To Reproduce

```markdown
Run pojavlauncher Run the Sodium patcher using the secure runtime .jar. Move Sodium to the mods folder. Launch Minecraft and wait
```

### Expected Behavior

I would like the game to launch so I can play with a higher fps

### Platform

```markdown
- Device model:Tecno pova 4 8/128
- CPU architecture: 
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484doc-v3_openjdk
```

**Comment by GaucovyAero** [comment]
remove the `Stylized Overlays.zip` resource pack, its most probably breaking your game launch

**Comment by Haygao** [comment]
> remove the `Stylized Overlays.zip` resource pack, its most probably breaking your game launch
It worked, but a warning came out that I was lucky to be able to launch the game with Sodium and that I should play at my own risk, and when I started the world the game crashed, and the reason was Sodium

**Comment by Haygao** [comment]
> remove the `Stylized Overlays.zip` resource pack, its most probably breaking your game launch

This actually helped, but a warning came out that Sodium is not supported, and the game crashed when entering the world![Screenshot_20231113-214845.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/127290082/daa84f61-3e1e-47b8-9a43-e9c85d58b0d0)

![crash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13339873/crash.txt)

**Comment by GaucovyAero** [comment]
the warning was not made by us but by the sodium team, since they are using features that are not supported by gl4es, it doesnt work (they only support PC GPUs that have OpenGL 4.6)

**Comment by AlekinPlayer** [comment]
Eu tentei usar o sodium patcher mas quando fui executar não apareceu nada como resolvo isso e eu renomeei tirando o.zip e deixando.Jar
