### ISSUE TITLE
[BUG] <Fly Wheel Mod Bug>

### ISSUE THREAD

**Issue by L1v3p** [PojavLauncherTeam/PojavLauncher#4848]
### Describe the bug

This bug happened when I entered Minecraft and the screen said Saving World and it crashed right after.

### The log file and images/videos

Me

### Steps To Reproduce

```markdown
1.starts and after the mojang screen crashes
```

### Expected Behavior

That would go into minecraft

### Platform

```markdown
- Device model:Samsung A14
- CPU architecture:arm64
- Android version:13
- PojavLauncher version:current
```

### Anything else?

sad and wanted to play but there was no way

**Comment by L1v3p** [comment]
Sad

**Comment by GaucovyAero** [comment]
turn off the backend in the config or try using angle, if that doesnt work then rip

**Comment by L1v3p** [comment]
where is the backend?

**Comment by L1v3p** [comment]
it was working fine. and the bug came with it

**Comment by GaucovyAero** [comment]
yes, its also not even a bug, pojav is just missing rendering features which create needs and they are very hard to implement on phones
