### ISSUE TITLE
Tidak bisa menggunakan akun Microsoft di pojav [BUG] <Short description>

### ISSUE THREAD

**Issue by DazzzzPride** [PojavLauncherTeam/PojavLauncher#4849]
### Describe the bug

Saya sudah mencoba login tapi tidak bisa

### The log file and images/videos

Tidak ada

### Steps To Reproduce

```markdown
1. Masuk ke pajak launcher
2. Pencet Add account
3. Masukin akun lalu login
4. Gagal
```

### Expected Behavior

Not

### Platform

```markdown
- Device model: samsul 
- CPU architecture: I don't know
- Android version: I don't know
- PojavLauncher version: 1.7.10
```

### Anything else?

Not

**Comment by GaucovyAero** [comment]
not a pojav issue, log into minecraft.net first
