### ISSUE TITLE
How to install forge 1.7.10

### ISSUE THREAD

**Issue by Holyshit1221** [PojavLauncherTeam/PojavLauncher#485]
How to install forge 1.17.10 (v3.3 testing 1)
help me thank you very much

**Comment by khanhduytran0** [comment]
- Download the Forge installer
- Go to launcher -> Options -> Launch mod installe
- Select Forge 1.7.10
- Let it download required files, but do not start yet!
- Go to `/storage/emulated/0/games/.minecraft/libraries/com/google/guava/guava/17.0` copy `guava-17.0.jar` replaces `/storage/emulated/0/games/.minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar`
- Start launch

**Comment by Holyshit1221** [comment]
Replace guava-17.0.jar file for guava-15.0.jar but do you need to rename file guava-17.0.jar

**Comment by khanhduytran0** [comment]
Latest launcher build fixed libraries handling, no need to replace libraries manually.

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/418308661

**Comment by Holyshit1221** [comment]
Thank you and wish you success

**Comment by Holyshit1221** [comment]
Auto-configuration overrides wrong width and length

**Comment by ghost** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/418308661

archive broken

**Comment by khanhduytran0** [comment]
> Auto-configuration overrides wrong width and length

Known issue on forge 1.7.10

**Comment by khanhduytran0** [comment]
> > https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/418308661
> 
> archive broken

Make sure you have a good connection

**Comment by khanhduytran0** [comment]
> Thank you and wish you success

You're welcome. as main problem solved, closing

**Comment by Juice913** [comment]
How can i Make It work Need to Rename Anything? Pls give full instructions plsss

**Comment by mchnjt** [comment]
> How can i Make It work Need to Rename Anything? Pls give full instructions plsss

???

**Comment by Juice913** [comment]
> > How can i Make It work Need to Rename Anything? Pls give full instructions plsss
> 
> ???

What do you mean im just saying what do i have to do i get an error when i start
