### ISSUE TITLE
Zink

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#4850]
### Describe the bug

I try to use zink launch forge47.1.0,but it always cash

### The log file and images/videos

Here is the log
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13372295/latestlog.txt)

### Steps To Reproduce

```markdown
Start PojavLauncher
Use zink renderer launch forge47.1.0
Get cash
```

### Expected Behavior

No

### Platform

```markdown
- Device model: Redmi K30 Pro
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: edelweiss-20231110-c773b92-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
it says you are out of gpu memory, weird
