### ISSUE TITLE
[BUG] <Xbox Live API Error>

### ISSUE THREAD

**Issue by KocTRH2287586** [PojavLauncherTeam/PojavLauncher#4852]
### Describe the bug

When I try to login to a Microsoft Account after that, I got an API error (which is below) and I dont really know what the code is but the only thing I saw is that code wanted me to redirect me to the enforcement page.

### The log file and images/videos

![IMG_20231116_153437](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149249431/a8f4a4e8-9797-4839-bcb3-7662fbae0233)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login to any Microsoft Account
3. Error triggered
```

### Expected Behavior

Clearly I expected it to be normal, but today is not my day.... I guess.

### Platform

```markdown
- Device model: OPPO A5 2020
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: latest version
```

### Anything else?

Nope, nothing else

**Comment by GaucovyAero** [comment]
you may have some issues with your xbox live account, log into xbox live, make sure all your account info is ok, then log into minecraft.net and also check, then try again
not a pojav issue

**Comment by KocTRH2287586** [comment]
> you may have some issues with your xbox live account, log into xbox live, make sure all your account info is ok, then log into minecraft.net and also check, then try again not a pojav issue 

I just checked and the account is suspended! Thanks a lot!
