### ISSUE TITLE
[Crash]  Physics Mod still not working for now

### ISSUE THREAD

**Issue by Forever2397** [PojavLauncherTeam/PojavLauncher#4853]
### Describe the bug

I have seen in your discord that physics mod is already supported for Android but why is it like this?

I have entered this physx jni android version but it is still like can you help me?

![Screenshot_2023-11-16-18-29-33-82_4161f6d30e86d11b7f385d6fce8c6438](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85401948/153b2058-88cd-49eb-a367-0002e9f8f52b)

### The log file and images/videos

[Uploading latestlog.txt…]()

### Steps To Reproduce

```markdown
ㅤㅤㅤ ㅤ
```

### Expected Behavior

I hope this is working

### Platform

```markdown
- Device model:Oppo Reno 4f
- CPU architecture:aarch64
- Android version: 11
- PojavLauncher version: playstore version
```

**Comment by sa1672ndo** [comment]
This method doesn't work, there's currently no known way to fix physics mod on android.

**Comment by Forever2397** [comment]
Hey, one of the discord members sent this photo

**Comment by sa1672ndo** [comment]
Well, they don't want to disclose how they fixed it, so they are the only person who can do it.

**Comment by sa1672ndo** [comment]
Not even Artdev knows how to fix it.

**Comment by Forever2397** [comment]
Yes, I know that even Duytrankhan, the owner of PojavLauncher, doesn't care about it

**Comment by Forever2397** [comment]
even though it is very important to increase the number of Pojavlauncher players

**Comment by sa1672ndo** [comment]
I'm 99% sure that it already works on iOS without needing to patch anything.

**Comment by Forever2397** [comment]
> I'm 99% sure that it already works on iOS without needing to patch anything.

Yes, because Physics Mod already supports MacOS without having to patch it, but it's different for Android

**Comment by sa1672ndo** [comment]
> Yes, because Physics Mod already supports MacOS without having to patch it, but it's different for Android

That's why Duy doesn't care, because it already works on iOS.

**Comment by sa1672ndo** [comment]
> even though it is very important to increase the number of Pojavlauncher players

Doubt it, not everyone will be able to run this. U need zink for it to work without any issues and not everyone will be able to run it with zink without their phones exploding.

**Comment by Forever2397** [comment]
does it need zink support to work?

**Comment by GaucovyAero** [comment]
we would need the physx library to exist on android, which isnt a thing yet

**Comment by GaucovyAero** [comment]
use this https://www.youtube.com/watch?v=ktL1Ql_YQGo

**Comment by GaucovyAero** [comment]
and use pojav from here https://github.com/NotAHero04/PojavLauncher

**Comment by Forever2397** [comment]
> and use pojav from here https://github.com/NotAHero04/PojavLauncher

![Uploading Screenshot_2023-11-18-18-38-09-05_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

**Comment by Bel69420** [comment]
The patcher only works for 1.17+
