### ISSUE TITLE
[BUG] Chat disabled due to missing profile bublic key. Please try recconecting.

### ISSUE THREAD

**Issue by lulu0430** [PojavLauncherTeam/PojavLauncher#4855]
### Describe the bug

If you chat in Realm, you will be denied the chat saying "Chat disabled due to missing profile public key. Please try reconnecting."

I'm using a translator, so the words can be awkward

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Join a Realm
2. Enter chat
```

### Expected Behavior

Use a seamless chat

### Platform

```markdown
- Device model: Samsung Galaxy Note Ultra 5G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20231110-c773b92-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
Fixed on the latest dev build
