### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by fish1145** [PojavLauncherTeam/PojavLauncher#4856]
### Describe the bug

When you click on the item bar, it will left-click 1-3 times，

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
cannot reproduce, show a video
