### ISSUE TITLE
[+] Add zink to the PowerVR gpu

### ISSUE THREAD

**Issue by Forever2397** [PojavLauncherTeam/PojavLauncher#4857]
### Is this request related to a bug?

Can you please add zink renderer on powervr gpu because at launch it crashes on my phone even though my Phone supports Vulkan

**Comment by Bel69420** [comment]
Nope, PowerVR missing a lot of extensions for zink.

**Comment by sa1672ndo** [comment]
Feel free to ask Mesa3d to make zink work with powerv ge8320 gpus.

**Comment by GaucovyAero** [comment]
afaik this is a physical limitation, same as if you would want to run shaders on minecraft 1.7.10 on a pc from 1999, it just doesnt support the gl extensions and doesnt have the option to
