### ISSUE TITLE
> Ask all pojav comunity members all will say yes So plz full fill our demand

### ISSUE THREAD

**Issue by Nitin1234556** [PojavLauncherTeam/PojavLauncher#4859]
> Ask all pojav comunity members all will say yes So plz full fill our demand

Running .exe files requires Windows. How do you think we can put Windows into Pojav?

_Originally posted by @artdeell in https://github.com/PojavLauncherTeam/PojavLauncher/issues/4858#issuecomment-1817822711_

**Comment by Nitin1234556** [comment]
I am just saying that u can add support for clints in pojav

**Comment by GaucovyAero** [comment]
We are running on Android, not Windows.
