### ISSUE TITLE
Не работает русская раскладка клавиатуры 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#486]

**Comment by nedogimov** [comment]
Известная причина.

**Comment by ghost** [comment]
я это уже писал, пометьте как повторение

**Comment by Artemii388** [comment]
А у меня вообще сквозь клавиатуру нажимает

**Comment by Mathias-Boulay** [comment]
![image](https://user-images.githubusercontent.com/24864674/120835274-65305580-c564-11eb-8fef-76f6ca34fd67.png)
It works now.
Closing the issue.
