### ISSUE TITLE
Zink renderer crash 

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#4862]
### Describe the bug

When I tried to run zink it crashes
In log file it says beginning of crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13403753/latestlog.txt)

### Steps To Reproduce

```markdown
I started pojav launcher in zink renderer
My game started running but after few minutes later it crashes
```

### Expected Behavior

I was expecting to run shaders on it but it's crashes

### Platform

```markdown
- Device model: Poco C3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Please reply fast

**Comment by Bel69420** [comment]
Sorry, your GPU doesn't compatible with Zink

**Comment by Bel69420** [comment]
And we can't fix this.

**Comment by Bel69420** [comment]
You can ask mesa3d to make zink support for PowerVR GE8320

**Comment by Proaman7603** [comment]
So how other people's work with zink? 
Many people's have this gpu but they have not any issue
