### ISSUE TITLE
[BUG] control

### ISSUE THREAD

**Issue by Gatosmias** [PojavLauncherTeam/PojavLauncher#4863]
### Describe the bug

When I go to run forward in any version of Minecraft in Pojav within a world when I click on the run button and hold it goes backwards instead of forward in any version it's not the control because the control is working normal

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/150546039/28073aef-a566-47d9-a510-c3ad4835b699

### Steps To Reproduce

```markdown
1 enter minecraft java inside pojavlancher 2 you can enter the world if you want 3 hold the run button and start forward
```

### Expected Behavior

Don't pull when running forward

### Platform

```markdown
- Device model: sm-m127f/ds
- CPU architecture: Exynos 850
- Android version: 13
- PojavLauncher version: recent
```

**Comment by Mathias-Boulay** [comment]
If you have some drift, simply increase the deazone
