### ISSUE TITLE
[BUG] <Zink Renderer and Rubidium>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4864]
### Describe the bug

as sodium is not available for forge I opted for rubidium (fork from sodium) but blocks become invisible. After changed the renderer to see if it would solve it but with zink Im having problems with crashes

### The log file and images/videos

![Screenshot_20231119_164641_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/142160595/20ac6e77-88e7-4a4c-8c4b-e1e91cda52f7)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13404463/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav and go to video/renderer settings.
2. Set the renderer to Zink (Vulkan).
2. Play, then wait for the crash (latestlog.txt).
```

### Expected Behavior

zink renderer crashes shouldnt happen

### Platform

```markdown
- Device model: Galaxy A03 
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: 20231199-3f302dc-v3_openjdk
```

**Comment by GaucovyAero** [comment]
your phone doesnt have enough extensions to run zink
there is a patch available for rubidium 1.18.2 which basically disables almost all of its features, so if you want more fps, just use optifine

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/folder/9slju5pyuoc03/SodiumRubidium heres the patch

**Comment by Bel69420** [comment]
@GaucovyAero , zink support with his GPU

**Comment by Bel69420** [comment]
Somehow, Zink OpenGL version is 3.1

**Comment by Bel69420** [comment]
Make a custom_env.txt and put `MESA_GL_VERSION_OVERRIDE=4.6
