### ISSUE TITLE
[BUG] <mouse axis inverted>

### ISSUE THREAD

**Issue by owlman123** [PojavLauncherTeam/PojavLauncher#4865]
### Describe the bug

It works normally on the Minecraft main screen, but when you enter the game, there is a bug where the mouse axis changes from X+ to Y+ and Y+ to X-.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1.start a pojavlauncher 
2.enter the game
```

### Expected Behavior
Expect that mouse x and y axes move normally in the game without being reversed.

### Platform

```markdown
- Device model: XiaoXin Pad Pro 12.7(128G)
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

It seems that certain Lenovo tabs do not have Android patches applied. Below you'll find examples of people experiencing this and the code they say solved it. I would appreciate it if you could refer to it.

https://github.com/moonlight-stream/moonlight-android/issues/1240

https://cs.android.com/android/_/android/platform/frameworks/native/+/258e2b909a91e893bf8cdd5b46ac7a9446de2549

**Comment by NEELGAMER0903** [comment]
G

**Comment by NEELGAMER0903** [comment]
Ddd

**Comment by justinnys** [comment]
Having the same problem with Lenovo P11 Gen 2 Tablet.  How do we get this resolved?

**Comment by GaucovyAero** [comment]
closing in favor of #5463
