### ISSUE TITLE
I also same problem how to fix please tell me

### ISSUE THREAD

**Issue by VKGAMER31** [PojavLauncherTeam/PojavLauncher#4866]
I also same problem how to fix please tell me 

1.Error
Chain validation failed

Error
Failed to download Minecraft!
This could be due to bad network
connection, incorrectly placed files,
etc.

How to fix

_Originally posted by @VKGAMER31 in https://github.com/PojavLauncherTeam/PojavLauncher/issues/2478#issuecomment-1818795901_

**Comment by GaucovyAero** [comment]
send the error

**Comment by VKGAMER31** [comment]
Can I reboot my mobile

**Comment by VKGAMER31** [comment]
Can I reboot my mobile and can fix tell me sir

**Comment by VKGAMER31** [comment]
javax.net.ssl.SSLHandshakeException: Chain validation failed
 at
com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
 at
com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
 at
com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
 at
com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
 at
com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
 at
com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
 at
com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
 at
com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown
Source:0)
 at
com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
 at
com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
 at
com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
 at
com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
 at
com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
 at
com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
 at
com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
 at
com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:302)
 at
com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
 at
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
 at
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
 at
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
 at
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
 at
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
 at
net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:103)
 at
net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadLibrary(AsyncMinecraftDownloader.java:339)
 at
net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:150)
 at
net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:54)
 at
net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown
Source:10)
 at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
Caused by: java.security.cert.CertificateException: Chain validation failed
 at
com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:717)
 at
com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:547)
 at
com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:568)
 at
com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:613)
 at
com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:503)
 at
com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:423)
 at
com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:351)
 at
android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
 at
android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
 at
com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
 at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:256)
 at
com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
 at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native
Method)
 at
com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
 at
com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
 at
com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
 ... 28 more
Caused by: java.security.cert.CertPathValidatorException: Response is
unreliable: its validity interval is out-of-date
 at
sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
 at
sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
 at
sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
 at
sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
 at
java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
 at
com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:713)
 ... 43 more
Caused by: java.security.cert.CertPathValidatorException: Response is
unreliable: its validity interval is out-of-date
 at
sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
 at
sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
 at
sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
 at
sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
 at
sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
 ... 48 more
 Suppressed: java.security.cert.CertPathValidatorException: Unable to
determine revocation status due to network error
  at
sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:562)
  at
sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
  at
sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
  ... 50 more
 Caused by: sun.security.provider.certpath.PKIX$CertStoreTypeException:
java.io.IOException: Cleartext HTTP traffic to crl.globalsign.com not
permitted
  at
sun.security.provider.certpath.URICertStore.engineGetCRLs(URICertStore.java:430)
  at java.security.cert.CertStore.getCRLs(CertStore.java:190)
  at
sun.security.provider.certpath.DistributionPointFetcher.getCRL(DistributionPointFetcher.java:245)
  at
sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:189)
  at
sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:121)
  at
sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:552)
  ... 52 more
 Caused by: java.io.IOException: Cleartext HTTP traffic to
crl.globalsign.com not permitted
  at
com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:127)
  at
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
  at
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
  at
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
  at
sun.security.provider.certpath.URICertStore.engineGetCRLs(URICertStore.java:396)
  ... 57 more

**Comment by GaucovyAero** [comment]
no idea, yes, you can reboot

**Comment by VKGAMER31** [comment]
It's working!


Sir but mods work or not
