### ISSUE TITLE
[F-Req] Virtual mouse mode and gyroscope enabled/disabled switch in In-game side menu

### ISSUE THREAD

**Issue by AbrasiveBoar902** [PojavLauncherTeam/PojavLauncher#4867]
### Is this request related to a bug?

We can use some in-game touchscreen supporting mods.

### Describe the request.

Swirch virtual mouse mode manually between dragging(the mode in game) and touching(in menu).
A toggle in side menu to enable/disable gyroscope.
This could be helpful :)

**Comment by GaucovyAero** [comment]
too much hassle for little effect, wont be done
