### ISSUE TITLE
[BUG]He'll crash when I start the game 

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#487]
--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl-jemalloc.jar, lwjgl-opengl.jar, lwjgl.jar, lwjgl-glfw-classes.jar.z, lwjgl-glfw-classes.jar, lwjgl-tinyfd.jar, lwjgl-openal.jar, version, lwjgl-stb.jar, jsr305.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms512m -Xmx800m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
--------- beginning of system
--------- beginning of main
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x361
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x450
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x33c0
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x13b8
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x2196
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x6a46
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x4d9
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0xda0
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/LaunchJVM(25364): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
S/LaunchJVM(25364): dlopen /data/app/net.kdt.pojavlaunch-tkKebHz0R-QAF1z5O7bGUg==/lib/arm64/libopenal.so success
S/LaunchJVM(25364): dlopen /data/app/net.kdt.pojavlaunch-tkKebHz0R-QAF1z5O7bGUg==/lib/arm64/libgl04es.so success
S/LaunchJVM(25364): Done processing args
S/LaunchJVM(25364): Found JLI lib
S/LaunchJVM(25364): Calling JLI_Launch
S/jrelog  (25364): OpenJDK 64-Bit Server VM warning: 
S/jrelog  (25364): No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x8ff
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
S/jrelog  (25364): " unused DT entry: 
S/jrelog  (25364): DT_RPATH
S/jrelog  (25364):  (type 
S/jrelog  (25364): 0xf
S/jrelog  (25364):  arg 
S/jrelog  (25364): 0x16fe
S/jrelog  (25364): ) (ignoring)
S/jrelog  (25364): 
S/jrelog  (25364): WARNING: linker: 
S/jrelog  (25364): Warning: "
S/jrelog  (25364): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
S/jrelog  (25364): " has unsupported flags DT_FLAGS_1=
S/jrelog  (25364): 0x81
S/jrelog  (25364):  (ignoring unsupported flags)
S/jrelog  (25364): 
S/jrelog  (25364): Exception in thread "main" 
S/jrelog  (25364): java.lang.NoClassDefFoundError: com/google/common/collect/ForwardingMultimap
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.lang.ClassLoader.defineClass1(Native Method)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.security.AccessController.doPrivileged(Native Method)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
S/jrelog  (25364): 
S/jrelog  (25364): 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
S/jrelog  (25364): 
S/jrelog  (25364): 	at net.minecraft.client.main.Main.main(SourceFile:112)
S/jrelog  (25364): 
S/jrelog  (25364): Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ForwardingMultimap
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
S/jrelog  (25364): 
S/jrelog  (25364): 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
S/jrelog  (25364): 
S/jrelog  (25364): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
S/jrelog  (25364): 
S/jrelog  (25364): 	... 13 more
S/jrelog  (25364): 
Java Exit code: 1
S/LaunchJVM(25364): Going to free args
S/LaunchJVM(25364): Free done

**Comment by khanhduytran0** [comment]
Which version?

**Comment by T-CATHOME** [comment]
@khanhduytran0 Latest version

**Comment by T-CATHOME** [comment]
@khanhduytran0 Latest version

**Comment by khanhduytran0** [comment]
@tttghkg no need to repeat message.
