### ISSUE TITLE
[BUG] <Panfrost Crash>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4870]
### Describe the bug

my gpu is mali-g57 but after updating to test the new renderer, panfrost contains crashes. Check my changelog.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13419554/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Go to Settings/Video and Renderer/Renderer
3. Select Panfrost (Mali) - all versions, mid
4. Now Play
```

### Expected Behavior

pojav shouldnt crash with panfrost since my gpu is mali bruh

### Platform

```markdown
- Device model: Galaxy A03
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: 20231120-375feb5-panfrost
```

**Comment by GaucovyAero** [comment]
not supported at all yet lol
