### ISSUE TITLE
[BUG] Visual glitches when using Betacraft proxy

### ISSUE THREAD

**Issue by SzyZET777** [PojavLauncherTeam/PojavLauncher#4871]
### Describe the bug

When using Betacraft proxy to get old sounds on early Minecraft versions visual glitches appear. They only exist in some versions in range from Infdev to Beta 1.8.  

When using Holy GL4ES the shading of player model and mobs doesn't work. The textures are the same light level.

In Zink the player model and mobs flicker black.

None of those issues seem to occur with Betacraft proxy turned off.

### The log file and images/videos

Setup for bug:

![Screenshot_2023-11-20-22-48-12-794_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/151512452/cba81bd8-0860-49dd-972b-631864235df8)

No shading in Holy GL4ES:

![Screenshot_2023-11-20-23-00-21-030_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/151512452/8fc9ba01-7a01-49ec-bf5d-192767d9d084)

Player's hand visual glitch in Zink:

![Screenshot_2023-11-20-22-51-07-920_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/151512452/d590967f-e5e6-4185-b38b-77bbec99ab10)

### Steps To Reproduce

```markdown
1 Start Pojavlauncher
2 Select version beta 1.7.3
3 Use renderer Holy GL4ES or Zink
4 Use any betacraft proxy through JVM arguments like: 
-Dhttp.proxyHost=betacraft.uk 
-Dhttp.proxyPort=11705
```

### Expected Behavior

I expect player and mobs models to be shaded properly and without flickering while also having old sound effects support.

### Platform

```markdown
- Device model: Poco F3
- Android version: Android 13
- PojavLauncher version: latest version
```

**Comment by Mathias-Boulay** [comment]
LIBGL_ES moment

**Comment by Faked4075** [comment]
1Try switching the option in the Optifine settings: fast render, in the performance tab.
And By the way, what does the betacraft proxy do?
if you don’t have Optifine, download it

**Comment by GaucovyAero** [comment]
the issue is not related to the betacraft proxy, if you install optifine and put LIBGL_ES=2 in /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt, the issue will be gone
