### ISSUE TITLE
Sodium hotbar and debug screen blinking

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#4872]
### Describe the bug

When I tried to run sodium with mods my hotbar start blinking my version is 1.20.1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13423395/latestlog.txt)

### Steps To Reproduce

```markdown
I tried sodium with my mods but my hotbar and debug screen is blinking
```

### Expected Behavior

I expect my sodium will run properly

### Platform

```markdown
- Device model: Poco C3  4/64 GB
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Pls solve my solution

**Comment by Bel69420** [comment]
Known issue, it's probably PowerVR GE8320 driver issue

**Comment by Bel69420** [comment]
And we can't fix this afaik

**Comment by Proaman7603** [comment]
Any other solution

**Comment by Proaman7603** [comment]
Pls reply

**Comment by GaucovyAero** [comment]
your gpu is most known for having super weird issues, wont fix

**Comment by Proaman7603** [comment]
Can i change my gpu  ?

**Comment by sa1672ndo** [comment]
No. You must buy a new phone.

**Comment by Bel69420** [comment]
Buy another phone

**Comment by genericgithubaccount185** [comment]
> Can i change my gpu ?

~~Yeah, just plop that bad boy out of the SoC~~ (you can't)
