### ISSUE TITLE
Add Modpack Supports

### ISSUE THREAD

**Issue by UltimateLegend09** [PojavLauncherTeam/PojavLauncher#4874]
### Is this request related to a bug?

Please add modpack Compatible and fix shutting down internal server

### Describe the request.

Please make many mods or modpack compatible like make  dawncraft, Sevtech ages and also fix shutting down internal server with rl craft and other mods or modpacks plz plz plzzzz

**Comment by UltimateLegend09** [comment]
Plzzz fix it and add it

**Comment by GaucovyAero** [comment]
invalid issue, no log provided
