### ISSUE TITLE
[Question] <Mali or Adreno, which one is better?>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#4877]
### Is this request related to a bug?

I'm having problems with my PowerVR and will be buying a new phone.(Requires a GPU that supports the features of Vulkan,OpenGL ES,OpenCL are the best.)

**Comment by NotAHero04** [comment]
Both are supported and will work, there's no "better" GPU here.
Buy a phone that fits your needs and your budget. (This is not a phone Q&A.)

**Comment by GaucovyAero** [comment]
afaik, phones with adreno 6xx work the best, but not the adreno 610
