### ISSUE TITLE
[BUG] Can't run Forge on Aarch32 1.12.2

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#488]
Is there a runtime to fix this or can forge not run at all on Aarch32 devices?

**Comment by WesleyVanNeck** [comment]
get a better device if even wanna think about force

**Comment by Mathias-Boulay** [comment]
The issue isn't related to the architecture neither the runtime, but only due to the device limitations.
Closing the issue, as it isn't Pojav's fault.
