### ISSUE TITLE
[BUG] black screen

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#4880]
### Describe the bug

When I launch the Immersive enginering 1.18.2 mod, the game starts, I hear menu sounds and button presses, but the screen is black.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I expected that either the game would crash or there would be no black screen.

### Platform

```markdown
- Device model: samsung s10
- CPU architecture: Exynos 9820
- Android version: 12
- PojavLauncher version: on play market
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
requires opengl 4.x

**Comment by Faked4075** [comment]
> требуется opengl 4.x

Please tell me how to install opengl 4.x except for ANGLE rendering

**Comment by GaucovyAero** [comment]
update pojav to the latest play store version and use zink if your phone supports it, otherwise it will crash or not show up
