### ISSUE TITLE
[BUG] Can't access Pojavlauncher folder that is in Android data folder on Android 13

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#4881]
### Describe the bug

Trying to access .minecraft on android but I can't get into the Pojavlauncher folder that is located in the android/data folder

### The log file and images/videos

No Log

### Steps To Reproduce

```markdown
1. Open any Android file explorer
2. Got on Android/data
3. Got to (net.kdt.pojavluancher)-idk what it's name is...
4. Can't give access to the folder
```

### Expected Behavior

You can open the Pojavlauncher data foler

### Platform

```markdown
- Device model: OPPO A77
- CPU architecture: 
- Android version: 13
- PojavLauncher version: Latest Play Store Release.
```

**Comment by GaucovyAero** [comment]
not a pojav issue lol, use zarchiver or mixplorer as your file manager

mixplorer 6.6x.x free download from mixplorer.com, the play store version is for donations

**Comment by DearFox** [comment]
> not a pojav issue lol, use zarchiver or mixplorer as your file manager
> 
> mixplorer 6.6x.x free download from mixplorer.com, the play store version is for donations

zarchiver still cannot access this folder.  He asks me to give him something, but in the application in which I need to give him access, I cannot do this.

![изображение](https://github.com/PojavLauncherTeam/PojavLauncher/assets/59219907/50a96a8f-7e3e-4cad-88d0-90907e843d5b)
