### ISSUE TITLE
[F-Req] <Vulkan PowerVR>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#4883]
### Describe the request.

This might work
https://docs.mesa3d.org/drivers/powervr.html

**Comment by GaucovyAero** [comment]
your ge8320 is not listed there, also you need at least vulkan 1.3 (for zink)

**Comment by Bel69420** [comment]
Or Mali with Vulkan 1.1

**Comment by sa1672ndo** [comment]
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/87911255/ee15bfb6-49e3-47be-8c32-53d5fd8fc624)
1st: ur gpu is not listed here.
2nd: this driver only gives vulkan 1.0 which is not enough to run zink.
Stop creating these stupid post if u have no idea what the fuck ur typing about.
