### ISSUE TITLE
[BUG] Forge install is unable to access manually installed mods

### ISSUE THREAD

**Issue by Elextro-B** [PojavLauncherTeam/PojavLauncher#4884]
### Describe the bug

As the app does not have access to the all files permission, any manually installed mods in the Android/data/net.kdt.pojavlaunch/files/.minecraft/mods folder are not recognised by forge and gives the following Main menu error/warning 
File (insertmodname).jar is not a jar file
(E.g) File lazydfu-0.1.3.jar is not a jar file
This error is quite frankly, funny but was also confusing at the start. After looking at the log file within the .minecraft folder and searching for the main root error, I found this (It relates to the earlier example)
[11:04:19] [main/ERROR]: Zip Error when loading jar file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/lazydfu-0.1.3.jar
java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/lazydfu-0.1.3.jar (Permission denied)
Essentially what this means is that either forge or the app was denied permission to this folder (very unusual because it is within the app's scoped storage) and so forge skipped it and it is considered invalid in another section of the log file
[11:04:20] [main/WARN]: File /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/lazydfu-0.1.3.jar has been ignored - it is invalid
While this is a small issue, if this issue is solved we will be able to manually install mods in a forge file thereby reducing the need for a fully fledged mod installer/modpack installer for pojav (a mod installer is still necessary as this is a very non beginner friendly method of mod installation)

### The log file and images/videos

This is the Minecraft/Forge log file
[latest.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13459979/latest.txt)
This is the pojav launcher log file (essentially the same thing)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13459987/latestlog.txt)
This is the error/warning screen
![Screenshot_20231120_112801](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143090016/502d017e-1bcf-475f-8fd5-026702e99844)

### Steps To Reproduce

```markdown
1.Open up Android/data/net.kdt.pojavlaunch/files/.minecraft/mods (this will require a proper file manager or access to the settings file manager https://play.google.com/store/apps/details?id=com.marc.files)
2.Move a mod into this folder (this may be very difficult depending on the file manager but if your methods do not work then use this method https://www.reddit.com/r/Android/s/wHtz5Bvure this utilises the above mentioned settings file manager)
3.Start pojav
4.Create a forge profile and set it to the version of the mod you placed in the above mentioned folder
5.Start the game
6.Go through the startup process
7.Non critical warning screen
```

### Expected Behavior

The expected result would be the game just recognising the mods and loading them like they would on a pojav modpack profile or on a regular Java Minecraft Forge profile running on a pc. 

### Platform

```markdown
- Device model: Honor X9 5G
- CPU architecture:ARM
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d 0c-v3_openjdk
```

### Anything else?

I find one of the methods to fix this (based on the limited information I gathered online) is to make the app request the READ_EXTERNAL_STORAGE or MANAGE_EXTERNAL_STORAGE permission. Now this is a very janky solution and the developer may have to submit a report on why they require this permission to google play. It is also a major privacy hazard. But the other method is to make the app request specifically permission to read the folder containing the mods. This topic is however something that I'm not familiar nor well versed enough in Android app development to fully understand but I would very much like for this to be fixed in order to  have a method of installing your own mods. Atleast untill a proper mod installation method is brought to the app

**Comment by GaucovyAero** [comment]
fyi, this issue is only present on some honor phones and the t-mobile revvl 6 series, not on other phones, but yeah, devs might aswell respond to this

**Comment by Elextro-B** [comment]
> fyi, this issue is only present on some honor phones and the t-mobile revvl 6 series, not on other phones, but yeah, devs might aswell respond to this

I suspected this might be a cause. I hate the way Honor treats some of its products. They're not a major player in the smartphone industry and yet they do all the bad things other major players do in the industry like restricting access to things like this

**Comment by sauceysaucer** [comment]
I'm on a Samsung S24 Ultra and also get the (permission denied) thing. Unfortunate x.x

**Comment by Xeltro** [comment]
Tru mine too

**Comment by CaptainAbby** [comment]
I don't able to understand plz help
![Uploading Screenshot_2024-08-08-08-32-16-57_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()
![Uploading Screenshot_2024-08-08-08-32-09-42_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

**Comment by GaucovyAero** [comment]
not a pojav nor phone issue, its just android, copy the mods instead of cutting them
