### ISSUE TITLE
[F-Req] Add External login

### ISSUE THREAD

**Issue by hsragi** [PojavLauncherTeam/PojavLauncher#4885]
### Is this request related to a bug?

Nothing to do with the bug, just want to use yggdrasil api as well as authlib for external login.

### Describe the request.

When adding an account, add an "external sign-in" feature in addition to your Microsoft account and offline sign-in. Used to use things like "littleskin.cn", "skin.prinzeugen.net", and "skin.lovepx.team". Ability to change skins for players who don't have a genuine account, as well as display skins in multiplayer.

### Anything else?

The url of "authlib-injector”：https://authlib-injector.yushi.moe/
It seems that all you need to do is add "-javaagent:</path/to/authlib-injector-*.*.*.jar>=<URL to yggdrasil api>" to the jvm parameter, and the same goes for the server. In China, there are some launchers like PojavLauncher that have this feature.

**Comment by GaucovyAero** [comment]
use the javaagent argument, this wont be added
