### ISSUE TITLE
[BUG] Unable to enter the world Rlcraft and error 

### ISSUE THREAD

**Issue by HenryTvChanel** [PojavLauncherTeam/PojavLauncher#4886]
### Describe the bug

When entering the world, it will be shut down and Error -1 RLCRAFT 2.9.3

### The log file and images/videos

![Screenshot_2023-11-25-15-00-14-29_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/151994177/a79e1b2a-0c99-4b88-b8b8-a776d11fe1fe)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13463347/latestlog.txt)

### Steps To Reproduce

```markdown
multiplayer and singleplayer
```

### Expected Behavior

How to fix it

### Platform

```markdown
- Device model: Realme Gt 2 Pro
- CPU architecture: snapdragon  8gen1 arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by ghost** [comment]
Delete these mods and rl craft work

custommainmenumod
fancyparticles
dynamic surroundings
soundfilters

**Comment by ghost** [comment]
fancyparticles=fancyblockparticles

**Comment by ghost** [comment]
Don,t add optifine . texture will bugy and lagy . Add perfomance mod like vanillafix and better fps for big modpack 1.12.2

**Comment by UltimateLegend09** [comment]
Use dahilla version of pojavluncher and turn off data and wifi it not crash no mods want to delete if ur game get texture white go to config menu of dynamic surrount then effect option all of except frost breathing
