### ISSUE TITLE
[ask] <Mali with Adreno (Zink)>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#4887]
### Describe the request.

Mali or Adreno, which works best on Zink?

**Comment by Nekotaco** [comment]
> ### Is this request related to a bug?
> _No response_
> 
> ### Describe the request.
> Mali or Adreno, which works best on Zink?
> 
> ### Anything else?
> _No response_

Your mom

**Comment by D3llwyn** [comment]
It'll depend on your phone's Vulkan drivers. Adreno devices have the advantage of having open drivers, that is Turnip, so you can update your Vulkan drivers.

**Comment by Natthakritp** [comment]
> It'll depend on your phone's Vulkan drivers. Adreno devices have the advantage of having open drivers, that is Turnip, so you can update your Vulkan drivers.

Is there a way to update?

**Comment by GaucovyAero** [comment]
turnip (the vulkan driver you need for zink to work on adreno) only works on adreno 6xx and 7xx, but both mali and adreno work pretty well

**Comment by ghost** [comment]
Why my phone have adreno 725 but i use renderer zink and angle . Will crashing

**Comment by Bel69420** [comment]
Your GPU does not support Turnip, that's why zink crashing

**Comment by ghost** [comment]
And angle render

**Comment by Bel69420** [comment]
It could be a driver bug.

**Comment by ghost** [comment]
VGPU render is good idea for many phones

**Comment by kasrarouhi** [comment]
ADREEL VERY THANKS FOR 3 MOUNTS FINALY I CAN OPEN ZINK RENDER VERY NICELY thank you very much my turnip driver not have any problem
