### ISSUE TITLE
[BUG]forge1.14.4+ Initiating crash 

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#489]
--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl-jemalloc.jar, lwjgl-opengl.jar, lwjgl.jar, lwjgl-glfw-classes.jar.z, lwjgl-glfw-classes.jar, lwjgl-tinyfd.jar, lwjgl-openal.jar, version, lwjgl-stb.jar, jsr305.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms512m -Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
--------- beginning of crash
--------- beginning of main
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  (10163): " unused DT entry: 
S/jrelog  (10163): DT_RPATH
S/jrelog  (10163):  (type 
S/jrelog  (10163): 0xf
S/jrelog  (10163):  arg 
S/jrelog  (10163): 0x361
S/jrelog  (10163): ) (ignoring)
S/jrelog  (10163): 
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  (10163): " has unsupported flags DT_FLAGS_1=
S/jrelog  (10163): 0x81
S/jrelog  (10163):  (ignoring unsupported flags)
S/jrelog  (10163): 
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (10163): " unused DT entry: 
S/jrelog  (10163): DT_RPATH
S/jrelog  (10163):  (type 
S/jrelog  (10163): 0xf
S/jrelog  (10163):  arg 
S/jrelog  (10163): 0x450
S/jrelog  (10163): ) (ignoring)
S/jrelog  (10163): 
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (10163): " has unsupported flags DT_FLAGS_1=
S/jrelog  (10163): 0x81
S/jrelog  (10163):  (ignoring unsupported flags)
S/jrelog  (10163): 
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  (10163): " unused DT entry: 
S/jrelog  (10163): DT_RPATH
S/jrelog  (10163):  (type 
S/jrelog  (10163): 0xf
S/jrelog  (10163):  arg 
S/jrelog  (10163): 0x33c0
S/jrelog  (10163): ) (ignoring)
S/jrelog  (10163): 
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  (10163): " has unsupported flags DT_FLAGS_1=
S/jrelog  (10163): 0x81
S/jrelog  (10163):  (ignoring unsupported flags)
S/jrelog  (10163): 
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (10163): " unused DT entry: 
S/jrelog  (10163): DT_RPATH
S/jrelog  (10163):  (type 
S/jrelog  (10163): 0xf
S/jrelog  (10163):  arg 
S/jrelog  (10163): 0x13b8
S/jrelog  (10163): ) (ignoring)
S/jrelog  (10163): 
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (10163): " has unsupported flags DT_FLAGS_1=
S/jrelog  (10163): 0x81
S/jrelog  (10163):  (ignoring unsupported flags)
S/jrelog  (10163): 
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  (10163): " unused DT entry: 
S/jrelog  (10163): DT_RPATH
S/jrelog  (10163):  (type 
S/jrelog  (10163): 0xf
S/jrelog  (10163):  arg 
S/jrelog  (10163): 0x2196
S/jrelog  (10163): ) (ignoring)
S/jrelog  (10163): 
S/jrelog  (10163): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" has unsupported flags DT_FLAGS_1=
S/jrelog  (10163): 0x81 (ignoring unsupported flags)
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
S/jrelog  (10163): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" unused DT entry: 
S/jrelog  (10163): DT_RPATH (type 0xf arg 0x6a46) (ignoring)
S/jrelog  (10163): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" has unsupported flags DT_FLAGS_1=0x81
S/jrelog  (10163):  (ignoring unsupported flags)
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
S/jrelog  (10163): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: 
S/jrelog  (10163): DT_RPATH (type 0xf arg 0x4d9) (ignoring)
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81
S/jrelog  (10163):  (ignoring unsupported flags)
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
S/jrelog  (10163): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" unused DT entry: 
S/jrelog  (10163): DT_RPATH (type 0xf arg 0xda0) (ignoring)
S/jrelog  (10163): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=
S/jrelog  (10163): 0x81 (ignoring unsupported flags)
S/LaunchJVM(10163): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
S/LaunchJVM(10163): dlopen /data/app/net.kdt.pojavlaunch-PPQgwFj2W6A9PmLas8CuWg==/lib/arm64/libopenal.so success
S/LaunchJVM(10163): dlopen /data/app/net.kdt.pojavlaunch-PPQgwFj2W6A9PmLas8CuWg==/lib/arm64/libgl04es.so success
S/LaunchJVM(10163): Done processing args
S/LaunchJVM(10163): Found JLI lib
S/LaunchJVM(10163): Calling JLI_Launch
S/jrelog  (10163): OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (10163): " unused DT entry: 
S/jrelog  (10163): DT_RPATH
S/jrelog  (10163):  (type 
S/jrelog  (10163): 0xf
S/jrelog  (10163):  arg 
S/jrelog  (10163): 0x8ff
S/jrelog  (10163): ) (ignoring)
S/jrelog  (10163): 
S/jrelog  (10163): WARNING: linker: 
S/jrelog  (10163): Warning: "
S/jrelog  (10163): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (10163): " has unsupported flags DT_FLAGS_1=
S/jrelog  (10163): 0x81
S/jrelog  (10163):  (ignoring unsupported flags)
S/jrelog  (10163): 
S/jrelog  (10163): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
S/jrelog  (10163): " unused DT entry: DT_RPATH (type 0xf arg 0x16fe) (ignoring)
S/jrelog  (10163): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81
S/jrelog  (10163):  (ignoring unsupported flags)
S/jrelog  (10163): 2020-12-13 12:38:31,930 main WARN Advanced terminal features are not available in this environment
S/jrelog  (10163): 
S/jrelog  (10163): [32m[12:38:32] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, ttt, --version, 1.15.2, --gameDir, /storage/emulated/0/games/.minecraft, --assetsDir, /storage/emulated/0/games/.minecraft/assets, --assetIndex, 1.15, --uuid, 00000000-0000-0000-0000-000000000000, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.47, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpV
S/jrelog  (10163): ersion, 20200515.085601, --fullscreen]
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:32] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 1.8.0-internal by Oracle Corporation
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: /storage/emulated/0/games/.minecraft/mods/[mccome.com]OptiFine_1.15.2_HD_U_G1_pre30_fbecfe14.jar
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/storage/emulated/0/games/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
S/jrelog  (10163): [m
S/jrelog  (10163): [1;31m[12:38:33] [main/FATAL] [ne.mi.fm.lo.FMLCommonLaunchHandler/CORE]: Failed to find Minecraft resource version 1.15.2-20200515.085601 at /storage/emulated/0/games/.minecraft/libraries/net/minecraftforge/forge/1.15.2-31.2.47/forge-1.15.2-31.2.47-client.jar
S/jrelog  (10163): [m
S/jrelog  (10163): Exception in thread "main" 
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:199)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:33] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:981)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
S/jrelog  (10163): [m
S/jrelog  (10163): [32m[12:38:34] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
S/jrelog  (10163): [m
Java Exit code: 1
S/LaunchJVM(10163): Going to free args
S/LaunchJVM(10163): Free done

**Comment by khanhduytran0** [comment]
Did you download Minecraft 1.15.2 before launch Forge?

**Comment by tttghkg** [comment]
@khanhduytran0 Downloaded.

**Comment by T-CATHOME** [comment]
@khanhduytran0 I downloaded it.

**Comment by khanhduytran0** [comment]
Minecraft version seems wrong (`1.15.2-20200515.085601`)
Try forge 1.16.x

**Comment by T-CATHOME** [comment]
@khanhduytran0 I'll try.

**Comment by T-CATHOME** [comment]
@khanhduytran0 Can you send me the 1.15.2 forge that can be started?

**Comment by khanhduytran0** [comment]
https://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.2-31.2.0/forge-1.15.2-31.2.0-installer.jar

**Comment by T-CATHOME** [comment]
@khanhduytran0 I got it started.
