### ISSUE TITLE
[BUG] Game Crashes While Creating Turning Track in " Create: Steam' n Rails "

### ISSUE THREAD

**Issue by 112211ss** [PojavLauncherTeam/PojavLauncher#4890]
### Describe the bug

Game Crashes While Creating Turning Track in " Create: Steam' n Rails ".But there is no such issue in " create".

### The log file and images/videos

![Screenshot_2023-11-26-09-03-10-691_bin mt plus](https://github.com/PojavLauncherTeam/PojavLauncher/assets/151979081/70c3737d-91af-4a6a-9919-ad6351d15e7d)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2.Create turning tracks in " Create: Steam' n Rails "
3.Game meltdown
```

### Expected Behavior

Create turning tracks normally in " Create: Steam' n Rails "

### Platform

```markdown
- Device model: Redmi Pad
- CPU architecture: arm
- Android version: 13
- PojavLauncher version: edelweiss-20231121-7794d58-
```

**Comment by kedrick021** [comment]
Don't use latest pojavlauncher use old pojavlauncher

**Comment by 112211ss** [comment]
Thank you.
