### ISSUE TITLE
[how to fix crash on rubidium mod 1.20.1

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4891]
### Describe the bug

When I create world and finish loading to 100% crash my game 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.creaye world
3. Crash
```

### Expected Behavior

Wow 

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

🥵

**Comment by GaucovyAero** [comment]
use zink, there is a very difficult patch you can do to run sodium/rubidium on 1.20.1+ but optifine is still faster and with sodium you will get your log spammed with errors, so it doesnt really make sense to use rubidium

**Comment by Faked4075** [comment]
> используйте zink, есть очень сложный патч, который вы можете сделать для запуска натрия/рубидия на 1.20.1+, но optifine все равно быстрее, а с натрием вы получите спам в журнале с ошибками, поэтому на самом деле нет смысла использовать рубидий

where is your very complex patch?
