### ISSUE TITLE
Vulkan renderer crash[BUG] <vulkan renderer crash in powerVR >

### ISSUE THREAD

**Issue by system32crowdstrikewin11** [PojavLauncherTeam/PojavLauncher#4892]
### Describe the bug

In this s bug  when I try to play with zinc renderer it crashes I tried all version but it still crashes 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13466328/latestlog.txt)

### The log file and images/videos

When I try to run the vulkan render in my device it crashes in every version
My device have mediatek helio p22 and powerVR rogue GE8320

### Steps To Reproduce

```markdown
[14:43:41] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker

[14:43:41] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker

[14:43:41] [main/INFO]: Calling tweak class optifine.OptiFineTweaker

OptiFineTweaker: acceptoptions

OptiFineTweaker: injectIntoClassLoader

OptiFine ClassTransformer

OptiFine ZIP file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/

libraries/optifine/OptiFine/1.12.2_HD_U_G6_pre1/OptiFine-1.12.2_HD_U_G6_pre1.jar

OptiFineTweaker: getLaunchArguments OptiFineTweaker getLaunchTarget

SEC [14:43:42] [main/INFO]: Launching wrapped minecraft (net.minecraft.client.main.Main)

Policies

Registered forkAndExec

2023-11-26 14:43:43,444 main ERROR appender Console has no parameter that matches element
```

### Expected Behavior

[14:43:57] [main/INFO]: [STDERR): at java.base/

jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[14:43:57] [main/INFO]: [STDERR) at java.base/java.lang.reflect.Method.invoke(Unknown

Source) [14:43:57] [main/INFO]: [STDERR] at

net.minecraft.launchwrapper.Launch.launch(Launch.java:159)

[14:43:57] [main/INFO]: [STDERR): at net.minecraft.launchwrapper.Launch.main(Launch.java: 30)

[14:43:57] [main/INFO]: [OptiFine] (Reflector) Class not present:

net.minecraftforge.fml.common.eventhandler. Event$Result [14:43:57] [main/INFO]: LWJGL Version: 3.3.1 SNAPSHOT

OSMDroid: loading vulkan regularly... OSMDroid: loaded vulkan, ptr=0x8d89542b9bc08fe5

OSMDroid: generating context

beginning of crash 

### Platform

```markdown
- Device model: tecno camon 15
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version:edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Please fix it

**Comment by Bel69420** [comment]
In this case, we can't do anything about it. 
PowerVR GE8320 missing a lot of extensions that caused zink renderer ending up crashing

**Comment by Bel69420** [comment]
Feel free to ask mesa3d about zink support for PowerVR GE8320

**Comment by GaucovyAero** [comment]
legit like 10+ issues already with the same thing, i recommend checking beforehand to see if something hasnt already been mentioned before

**Comment by system32crowdstrikewin11** [comment]
Thanks for replying now I know why it was crashing
