### ISSUE TITLE
[BUG] joystick issue

### ISSUE THREAD

**Issue by stevespid3rr** [PojavLauncherTeam/PojavLauncher#4893]
### Describe the bug

when i change the joystick opacity it doesn't work and looks ugly

### The log file and images/videos

I don't have any pics

### Steps To Reproduce

```markdown
Create a new control and click add a joystick and change the opacity to any percentage(I recommend 10%) then save and apply the control and join a world or server you will see the opacity didn't change:(
```

### Expected Behavior

I expected it would change the opacity and the button will look transparent 

### Platform

```markdown
- Device model: oppo a12 
- CPU architecture:mtk helio p35
- Android version: 9
- PojavLauncher version: 
Playstore version
```

### Anything else?

Devs fix it please 🥺

**Comment by GaucovyAero** [comment]
cant reproduce, works fine for me
