### ISSUE TITLE
[F-Req] vgpu render 

### ISSUE THREAD

**Issue by B00k546** [PojavLauncherTeam/PojavLauncher#4897]
### Describe the request.

vgpu work perfectly good in fcl and I though why pojav Dev don't add it and make it better . I know u guys work harder but every render is sucks with opengl es 3 . vgpu is the solution for that when I tested it in forge 1.8.9 . it was avrg 25 fps in holy render to avrg 66 in vgpu render

### Anything else?

Pls make my dream true :3

**Comment by SolDev69** [comment]
PowerVR moment

**Comment by Natthakritp** [comment]
VGPU works well

**Comment by Vera-Firefly** [comment]
It has been eliminated

**Comment by GaucovyAero** [comment]
vgpu is mostly integrated into holy gl4es, and from the testing we did, gl4es was always faster
