### ISSUE TITLE
Error when opening launcher.

### ISSUE THREAD

**Issue by MxndzaLoL** [PojavLauncherTeam/PojavLauncher#49]
Unable to copy pojavdx.dex to /data/data/net.kdt.pojavlaunch/app_working_dir/pojavdx.dex

**Comment by khanhduytran0** [comment]
Are you using latest preview?

**Comment by MxndzaLoL** [comment]
Sure, 9b5

**Comment by khanhduytran0** [comment]
Can you copy the stack trace?

**Comment by khanhduytran0** [comment]
Ok, just ignore it, pojavdx.dex is included in classesN.dex

**Comment by MxndzaLoL** [comment]
And i cant play. You told me the solution yesterday, setting it to 8000, but it still fails. the Launcher crashes, but no error code or anything like that.

**Comment by khanhduytran0** [comment]
Where will crash?

**Comment by MxndzaLoL** [comment]
After converting all the files, at the moment of opening the game.

**Comment by khanhduytran0** [comment]
Do it have any crash report?

**Comment by khanhduytran0** [comment]
And you Android version?
Same as me, but screen go black for a while then crash.

**Comment by MxndzaLoL** [comment]
I do not know if there is a Crash report because when I enter that section of Crash reports it also crashes.

**Comment by MxndzaLoL** [comment]
And I have android 9, Miui 11 and a Xiaomi mi mix 2

**Comment by khanhduytran0** [comment]
/storage/emulated/0/games/minecraft/crash-reports
Check recent crash.

**Comment by khanhduytran0** [comment]
But if it is Minecraft crash, a dialog will show with message Game Crashed.

**Comment by MxndzaLoL** [comment]
What closes is the launcher. On the other hand, I don't have that folder so I assume you have not saved any information about the shutdown.

**Comment by MxndzaLoL** [comment]
Sorry for bad communication, im using Google translator

**Comment by khanhduytran0** [comment]
If you have root or anything you can give me the  error stack trace from /data/system/dropbox

**Comment by MxndzaLoL** [comment]
I dont have root, sorry

**Comment by khanhduytran0** [comment]
If you don't have root, use PC
Run `adb logcat > log.txt` then run the launcher until crash and send me that log.

**Comment by khanhduytran0** [comment]
Also install `adb` before

**Comment by MxndzaLoL** [comment]
Yes i have adb, but i cant acces my pc for now.
I will do in a few hours.

**Comment by khanhduytran0** [comment]
An easier way, use ADB over Network.
Use other devices and download app https://play.google.com/store/apps/details?id=com.cgutman.androidremotedebugger

**Comment by khanhduytran0** [comment]
> If you don't have root, use PC
> Run `adb logcat > log.txt` then run the launcher until crash and send me that log.

Check.if problem occurred again.
