### ISSUE TITLE
[BUG] <Crash while entering world>

### ISSUE THREAD

**Issue by HaziqDy201200** [PojavLauncherTeam/PojavLauncher#4900]
### Describe the bug

The world get crash while entering.

### The log file and images/videos

[latestlog.txt.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/13487573/latestlog.txt.zip)

### Steps To Reproduce

```markdown
Setting crash while paling Minecraft fabric modloaders
```

### Expected Behavior

The world Genting crash while use fabric and other mods

### Platform

```markdown
- Device model: Resmi 9C
- CPU architecture: armv81
- Android version: 10
- PojavLauncher version: edelweiss-20230938-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
sodium 0.5.3 needs a very difficult patch in order to run (and you will still get the log spam), you can look at the offbeat-stuff/pojavium to see how such patch looks
optifine is faster on pojav
