### ISSUE TITLE
[BUG] The game crashes when creating a turning track in " Create: "

### ISSUE THREAD

**Issue by 112211ss** [PojavLauncherTeam/PojavLauncher#4901]
### Describe the bug

The game crashes when I Create a turning track in " Create "

### The log file and images/videos

[Uploading latestlog.txt…]()

### Steps To Reproduce

```markdown
1.Start PojavLauncher.
2.Create a turning track in " Create ".
3.Game meltdown.
```

### Expected Behavior

Create turning tracks normally in " Create ".

### Platform

```markdown
- Device model: RedmiPad
- CPU architecture: arm
- Android version: 13
- PojavLauncher version:edelweiss-20231121-7794d58-
```

**Comment by 112211ss** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13488897/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
|Field| Value |
|--|--|
| Build type | DEBUG |
| Pojav version | edelweiss - 20231121 -  |
| Minecraft version | 1.19.2-forge-43.2.14 - FORGE |
| Renderer | ANGLE |
| Architecture | ARM_64 |
| Java runtime | INTERNAL - JRE - 17 |
| Java arguments |  |



|Errors Found: |
|--|
| libgles.wrong.value |
| branch.not.mainline |

**Comment by GaucovyAero** [comment]
sorry to say this after your long wait for the response but create obviously wont work when it uses gl functions that pojav doesnt support
