### ISSUE TITLE
Video settings causes perpetual loading

### ISSUE THREAD

**Issue by p-spine** [PojavLauncherTeam/PojavLauncher#4903]
### Describe the bug

Unsure about other versions, but on b1.7.3, when you select "video settings", the game enters a loading screen that seemingly never stops unless you force quit. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13493304/latestlog.txt)

### Steps To Reproduce

```markdown
Repro steps:
Install b1.7.3
In game or at menu, select video settings. 
If in game, "saving chunks" appears
Starts loading indefinitely
```

### Expected Behavior

Expect to enter video settings menu 

### Platform

```markdown
- Device model: Google Pixel 6 pro
- CPU architecture: Octa-core (2x2.80 GHz Cortex-X1 & 2x2.25 GHz Cortex-A76 & 4x1.80 GHz Cortex-A55)
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Don't know if this is already an issue somewhere. If so, please point me to the solution. Thanks!

**Comment by GaucovyAero** [comment]
your options.txt file might be too new (for a newer minecraft version), try deleting it

**Comment by p-spine** [comment]
> your options.txt file might be too new (for a newer minecraft version), try deleting it

Yep that did it. Thanks so much!

**Comment by GaucovyAero** [comment]
np
