### ISSUE TITLE
[BUG] <keep crashing with this one mod>

### ISSUE THREAD

**Issue by Kisamerr** [PojavLauncherTeam/PojavLauncher#4905]
### Describe the bug

So recently I'm opening an SMP with my java friend.. and when I tried to install synitra connector with all the dependency.. it keep crashing my Minecraft with code -1.. I've ask the mod developer and they just simply said they won't be supporting pojav launcher because pojav launcher work different then other launcher..

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/13495618/latest.log)

### Steps To Reproduce

```markdown
1.start pojav launcher and install forge 1.20.1-47.1.3
2.install synitra connector, forgified fabric api,Connector extra, and any fabric mod such as replay mod 
3.pojav with start crashing.

(Keep in mind this method work on java edition)
```

### Expected Behavior

I'm expecting you could tell me how to fix this problem or help me fix it.. 

### Platform

```markdown
- Device model:red magic 7 
- CPU architecture:Octa-core (1x3.00 GHz Cortex-X2 & 3x2.50 GHz Cortex-A710 & 4x1.80 GHz Cortex-A510)
- Android version: 12
- PojavLauncher version:edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Please help me I really need this mod to work

**Comment by GaucovyAero** [comment]
looks like a mod conflict tbh, not a pojav issue

**Comment by Kisamerr** [comment]
But could you actually help me with it ?

**Comment by GaucovyAero** [comment]
> But could you actually help me with it ?

i have no idea which mod is the issue, try pinpointing it

**Comment by Kisamerr** [comment]
The mod name is synitra connector

**Comment by GaucovyAero** [comment]
> The mod name is synitra connector

send the modpack pls

**Comment by Kisamerr** [comment]
> > The mod name is synitra connector
> 
> send the modpack pls

[mod.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/13522913/mod.zip)

**Comment by GaucovyAero** [comment]
the modpack you sent works fine on PC (sorry for the late response), can you try upgrading forge to the latest version?

**Comment by GaucovyAero** [comment]
works on my phone

![Screenshot_20231209-121420_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/2bc13522-5858-4a68-9ee5-9c7a81257827)

![Screenshot_20231209-121441_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/dd6c8ef8-2bd7-4b46-a9ca-e5c8231cbf61)

**Comment by Bel69420** [comment]
32bit lmao
