### ISSUE TITLE
Enable to set coustom key of mouse

### ISSUE THREAD

**Issue by PSgamer20x** [PojavLauncherTeam/PojavLauncher#4906]
### Is this request related to a bug?

I have buyed one new mouse it's gaming mouse there are 4 buttons (2 extra shortcut keys) in side of mouse  , I want to use it for changing inventory shortcut because I am keybord mouse player 

Acully, when I go in keyblinds setting I am enable to select the key of mouse , when I click for selecting that button 'nothing heppens' I thik it's problem of pojav launcher cause I tried same on pc tlaucnher I can select and use that button for shortcut

![Screenshot_2023-11-29-15-16-44-763_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/a546a74b-2d92-4c86-b773-226e0cc8c1dd)

### Describe the request.

Pls fix it or give me suggestion for it 

I am enable to select extra buttons of mouse for shortcut keys

**Comment by PSgamer20x** [comment]
Mouse name : Red gear A20
Device name : poco m4 pro 5g

**Comment by Mathias-Boulay** [comment]
We're open for a PR handling it

**Comment by PSgamer20x** [comment]
> We're open for a PR handling it

What's PR btw

**Comment by Nightsky000** [comment]
pull request

**Comment by GaucovyAero** [comment]
make a pr if you want that feature to be there

**Comment by PSgamer20x** [comment]
> make a pr if you want that feature to be there

Bro I don't know how to make pr 
But I want that feature pls add it as soon as possible
In next update
