### ISSUE TITLE
Can i allocate more than allowed

### ISSUE THREAD

**Issue by BlueWinGMod** [PojavLauncherTeam/PojavLauncher#4907]
the max i Can allocate on my phone is 1800mb ram Can i allocate more than 1800mb my phone IS 3gb ram and i want allocate 2gb but when i want allocate in the settings its just 1800mb max Can i do a thing for allocate more than the maximum?

**Comment by BlueWinGMod** [comment]
sorry im New to github so i dont know how it works

**Comment by GaucovyAero** [comment]
do you get a warning when launching the game if you allocate 1800MB?

**Comment by BlueWinGMod** [comment]
> do you get a warning when launching the game if you allocate 1800MB?








yeah but i dont care my phone IS a 3gb ram lddr3 i think and 64 bit sorry is i am rude sorry

**Comment by GaucovyAero** [comment]
> > do you get a warning when launching the game if you allocate 1800MB?
> 
> yeah but i dont care my phone IS a 3gb ram lddr3 i think and 64 bit sorry is i am rude sorry

if you get a warning, that means you cant allocate such amount, because its already taken up by other apps lol
