### ISSUE TITLE
[BUG] zink OSmesa lag

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4908]
### Describe the bug

I download the new version of pojav launcher write feat[zink] update OSMesa and i updated but  in 3 minutes of start pojav launcher is work very fine with zink render but after 3 minutes game will start big lag and fps down . My fps 3 minutes in start is 40 but after 3 minutes in enter a world is 1 or 3 . In turnip update pojav launcher work very fine with zink render .

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1:download pojav will writes feat[zink] update Os Mesa
2:start pojav launcher
3:start a new world
4:and after 3 minutes getting lag spikes
```

### Expected Behavior

.

### Platform

```markdown
- Device model: poco f5 12/256gb
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: .
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
seems like other people with the poco f5 also have this issue but we cant really do anything about zink, because it is maintained by mesa developers, just wait for an update with a fix i guess

**Comment by ghost** [comment]
But in turnip update crash zink is fixed and it,s work very well and i satisfied
