### ISSUE TITLE
[ latest game exited with text 1 ] IN bluestacks 5 pojav launcher

### ISSUE THREAD

**Issue by DragzolaDrag** [PojavLauncherTeam/PojavLauncher#4910]
### Describe the bug

I play in pojav launcher pc in Bluestacks 5 5.13.215
And this error suddenly occured

### The log file and images/videos

It is saying interrupted and corrupted file

### Steps To Reproduce

```markdown
IDK ;-;
```

### Expected Behavior

WORK

### Platform

```markdown
- Device model:PC
- CPU architecture:AHEM IDK
- Android version: 
- PojavLauncher version:latest
```

### Anything else?

PLS HELP ME FIX IT 
PLS I AM CRYING MY EXAM JUST ENDED AND NOW THIS HAPPENED
pls help me ik i am being rude

**Comment by GaucovyAero** [comment]
send log

**Comment by DragzolaDrag** [comment]
For some reason when i am trying to check the logs its saying interrupted and corrupted file
and i can also enter 1.7.1 version
also my renderer is holy gl4es and no other renderer is available

**Comment by GaucovyAero** [comment]
i dont know whats wrong without the log lol, the log's location is mentioned in the create issue template

**Comment by DragzolaDrag** [comment]
> i dont know whats wrong without the log lol, the log's location is mentioned in the create issue template

Thats where its showing interrupted and currupted file

**Comment by GaucovyAero** [comment]
cant really help you with that then
