### ISSUE TITLE
[F-Req] ability to change maximum ram

### ISSUE THREAD

**Issue by laithalshabi** [PojavLauncherTeam/PojavLauncher#4918]
### Is this request related to a bug?

No

### Describe the request.

I have a phone with 3gb of ram but the app limit my ram to 1Gb i want to be able to give it more than 1Gb and yeah i can use more cause i have a custom rom in my phone that is debloated  so i hope to see that feature<3

**Comment by GaucovyAero** [comment]
duplicate of #4907, if you get a warning, you dont have enough free ram

**Comment by laithalshabi** [comment]
But i don't have any warning

> duplicate of #4907, if you get a warning, you dont have enough free ram
