### ISSUE TITLE
[BUG] Unable to use neoforge

### ISSUE THREAD

**Issue by 112211ss** [PojavLauncherTeam/PojavLauncher#4919]
### Describe the bug

When I tried to use Neo Forge, the game crashed.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13538791/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Initiating neoforge 47.1.81
3. Game meltdown
```

### Expected Behavior

Use neoforge Normally.

### Platform

```markdown
- Device model: Redmi Pad
- CPU architecture: arm
- Android version: 13
- PojavLauncher version: edelweiss-20231129-3635f53-feat/secure_modpacks_downloads
```

**Comment by GaucovyAero** [comment]
you are trying to play 1.19.2 mods on 1.20.1, that wont work

**Comment by 112211ss** [comment]
It works.Thank you.
