### ISSUE TITLE
Error mod NEI with forge 1.7.10

### ISSUE THREAD

**Issue by Holyshit1221** [PojavLauncherTeam/PojavLauncher#492]
If I installed mod NEI, I would be exited game with code 1

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by Holyshit1221** [comment]
--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-glfw-classes.jar.z, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms1600m -Xmx1800m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
Java Exit code: 1

**Comment by Holyshit1221** [comment]
I also can't play the world I created

**Comment by khanhduytran0** [comment]
> I also can't play the world I created

Known issue on 1.7.10 and probably some other versions.

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
