### ISSUE TITLE
[BUG] Server-related problems occur when running Sodium using Zink

### ISSUE THREAD

**Issue by lulu0430** [PojavLauncherTeam/PojavLauncher#4921]
### Describe the bug

When I apply Sodium using zink and try to connect to the server, I cannot connect to the server well. Even if I am connected to the server, a key-related bug occurs, so the key is recognized as a toggle or even if I press one key and press another key. An unrecognized bug occurred

### The log file and images/videos

Nope

### Steps To Reproduce

```markdown
1. start Pojavlauncher
2. set up zink renderer
3. Apply Sodium
4. Start Minecraft
```

### Expected Behavior

Normal Game

### Platform

```markdown
- Device model: Samsung Galaxy Note 20+ Ultra 5G
- CPU architecture: Arm64
- Android version: 13
- PojavLauncher version: edelweiss-20231127-f88fb3c-v3_openjdk
```

### Anything else?

The words may be strange because you use a translator.

**Comment by GaucovyAero** [comment]
wont fix this unfortunately, use optifine if you can
