### ISSUE TITLE
[BUG] <Modern Industrialization mod visual bugs>

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#4922]
### Describe the bug

in the MI 1.19.2 Fabric mod there are visual bugs like this, but the most interesting thing is that without sodium there is no such bug, I also tried indium, but to no avail.

### The log file and images/videos

![Screenshot_20231205_140304_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/141859258/5fde77c1-f376-441b-8404-af4144e0aac6)

### Steps To Reproduce

```markdown
1. Launch mods
2. See visual bugs
```

### Expected Behavior

I expected the textures to be normal

### Platform

```markdown
- Device model: samsung s10
- CPU architecture: ex9820
- Android version: 12
- PojavLauncher version: latest release from play market
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
sodium uses gl functions that pojav does not support, dont use it
