### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by AlexLionking3** [PojavLauncherTeam/PojavLauncher#4925]
### Describe the bug

When I try and open frabric I'm just left on a black screen, I've having troubles with this all the time, mod packs won't load at times. Forge kinda works. 

### The log file and images/videos

[latestlog-1.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13588663/latestlog-1.txt)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/153016333/d692f251-b77b-4e6b-b31d-dc08d203c1f7

### Steps To Reproduce

```markdown
1. Start the launcher
2. Clicked on the fabric 
3. Black screen with my controls is only shown and never loads
```

### Expected Behavior

Be able to open fabric and use mods like it's supposed to

### Platform

```markdown
- Device model: Galaxy S10e
- CPU architecture: idk
- Android version: 12
- PojavLauncher version: Version
edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Nope

**Comment by GaucovyAero** [comment]
send log

**Comment by AlexLionking3** [comment]
[Uploading latestlog-1.txt…]()

**Comment by AlexLionking3** [comment]
Sorry about that

**Comment by GaucovyAero** [comment]
> Uploading latestlog-1.txt…

you havent uploaded it, you gotta wait till it uploads

**Comment by AlexLionking3** [comment]
Oh my apologies

**Comment by AlexLionking3** [comment]
Sorry about this, this is my first time using this

**Comment by GaucovyAero** [comment]
> Sorry about this, this is my first time using this

np just send it

**Comment by AlexLionking3** [comment]
I added it to the thing about the video

**Comment by GaucovyAero** [comment]
oops, misclick, the log shows you playing vanilla optifine with shaders, not fabric

**Comment by AlexLionking3** [comment]
Oh crap my apologizes

**Comment by AlexLionking3** [comment]
Think that should be right

**Comment by GaucovyAero** [comment]
the log tells you what to do at the bottom, you gotta upgrade fabric and remove sodium

**Comment by AlexLionking3** [comment]
Okay lemme try

**Comment by AlexLionking3** [comment]
I'm confused I updated the log what does it say is wrong?

**Comment by GaucovyAero** [comment]
replaymod is not supported above 1.16.5 without the pojav ffmpeg plugin

**Comment by AlexLionking3** [comment]
Okay lemme try a lower version

**Comment by AlexLionking3** [comment]
So what Versions of the fabric, And replay mod would I do

**Comment by AlexLionking3** [comment]
I'm so confused and lost

**Comment by GaucovyAero** [comment]
> So what Versions of the fabric, And replay mod would I do

you cant use replay mod on new versions of minecraft on pojav, thats it, and its also very complicated to get it running even on older versions of mc on pojav

**Comment by AlexLionking3** [comment]
Ah okay yeah, thank you for your help!

**Comment by GaucovyAero** [comment]
np
