### ISSUE TITLE
[BUG] <Rubidium 1.20.1 transparent world>

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#4929]
### Describe the bug

I run FORGE 1.20.1 with the Rubidium mod, on the ANGLE renderer, but after entering the world I see the following bugs:

### The log file and images/videos

![Screenshot_20231207_005006_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/141859258/60c22dde-6983-439f-9a40-054f842ec10b)
Please help me.

### Steps To Reproduce

```markdown
1. Launch FORGE 1.20.1 with Rubidium
2. Join world
3. See bugs
```

### Expected Behavior

I expected that there would be no transparent world.

### Platform

```markdown
- Device model: Samsung s10
- CPU architecture: ex9820
- Android version: 12
- PojavLauncher version: elderweis release
```

### Anything else?

No, thanks

**Comment by Faked4075** [comment]
By the way, I even tried removing other mods and changing Rubidium settings, nothing helped (

**Comment by GaucovyAero** [comment]
sodium/rubidium use gl functions that pojav doesnt support, there are about 20+ more tickets about this, duplicate issue
