### ISSUE TITLE
[BUG] Weird behaviors with keyboard

### ISSUE THREAD

**Issue by xszqxszq** [PojavLauncherTeam/PojavLauncher#493]
**Describe the bug**
Pressing some buttons on virtual keyboard or on bluetooth keyboard (not using the "send key" option in menu) will cause weird behaviors.

**To Reproduce**
1. Start PojavLauncher
2. Launch 1.16+ version
3. Several things seem to be weird:
Press `Space` will cause the "GUI" button or the "keyboard" button created by launcher being triggered, so only by pressing space could I jump in game;
Press `E` twice won't make Inventory GUI close; 
Press `Esc` in game won't work, and in Inventory or Chest GUI it will directly pause the game;
Press `T` will make a 't' letter appear in the cheat, and `/` will make double '/' letter appear.

**Expected behavior**
1.`Space` shouldn't conflict with any key on screen;
2. Press `E` twice can close Inventory normally;
3. `Esc` should work just as it on computer;
4. `T` or `/` shouldn't be repeated twice after pressed that key.

**Screenshots**
Providing screenshots for this issue isn't necessary.

**Platform:**
 - Phone: Huawei nova youth
 - CPU architecture: aarch64
 - Android Version: 8

**Additional context:**
Maybe allowing users to disable GUI stuffs when bluetooth keyboard or USB keyboard is connected will be a good solution.

**Comment by khanhduytran0** [comment]
Current workaround: press Keyboard button before use external keyboard.

**Comment by khanhduytran0** [comment]
> Maybe allowing users to disable GUI stuffs when bluetooth keyboard or USB keyboard is connected will be a good solution.

You can just create a control Json with no buttons.

**Comment by xszqxszq** [comment]
Thanks for providing current workaround, and hope this bug can be fixed soon

**Comment by Mathias-Boulay** [comment]
All of those bugs aren't reproducible on the google play build (with minecraft 1.16.5), closing issue.
