### ISSUE TITLE
[BUG] <crash when I close the program>

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#4930]
### Describe the bug

on the new version of forge 1.20.1 when I build pojav the game just crashes, leaving neither Crashreport nor information in the logs

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1. Launch forge 1.20.1
2. collapse pojav
3. See crash without logs and crashreport
```

### Expected Behavior

maybe you know what this is from?

### Platform

```markdown
- Device model: samsung s10
- CPU architecture: ex9820
- Android version: 12
- PojavLauncher version: elderweis
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
disable forge window control in .minecraft/config/forge.cfg

**Comment by Faked4075** [comment]
> disable forge window control in .minecraft/config/forge.cfg

but I only have forge-client there, and there is no such function as window management.

**Comment by GaucovyAero** [comment]
maybe its in another config

**Comment by Faked4075** [comment]
yes, I already found out, it ends up in fml.toml
