### ISSUE TITLE
[BUG] <Optifine crash 1.20.1 forge>

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#4931]
### Describe the bug

After installing optifine 1.20.1 forge without other mods, when entering the world my game crashed, latest log and crash report below. Optifine version: OptiFine_1.20.1_HD_U_I5.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13600484/latestlog.txt)
[crash-2023-12-07_19.08.21-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13600486/crash-2023-12-07_19.08.21-client.txt)

### Steps To Reproduce

```markdown
1. Launch forge 1.20.1 with optifine
2. Joining world
3. See a crash
```

### Expected Behavior

I expected that there would be no crash

### Platform

```markdown
- Device model: samsung s10
- CPU architecture: ex9820
- Android version: 12
- PojavLauncher version: elderveis
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
optifine is not compatible with latest forge, even on pc

**Comment by Faked4075** [comment]
> optifine не совместим с последней версией Forge даже на ПК.

Optifine rolled down
