### ISSUE TITLE
[VirGL] <Add VirGL again>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#4933]
### Describe the request.

Added VirGL and updated Mesa to the latest version.Added support for OpenGL 4.6

### Anything else?

VirGL may be faster

**Comment by sa1672ndo** [comment]
Virgl won't be faster. In fact, it's 1 of the slowest renderers other than llvmpipe.
Feel free to add it urself to ur own fork of pojav and use it.

**Comment by Forever2397** [comment]
> Virgl won't be faster. In fact, it's 1 of the slowest renderers other than llvmpipe. Feel free to add it urself to ur own fork of pojav and use it.

How to add it?

**Comment by Marshall2439** [comment]
Bruh Virgil was most glitched renderer but older Zink has opengl 4.6

**Comment by GaucovyAero** [comment]
virgl was buggy and slow, no

**Comment by Faked4075** [comment]
You can download doewnload this build:
https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink/actions/runs/7084105869
there is your favorite virgl, thanks to Vera-firefly for this build.
