### ISSUE TITLE
[F-Req] <rubidium 1.20.1>

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#4934]
### Is this request related to a bug?

No

### Describe the request.

I recently saw that you made a patched version of sodium 0.5.2-1.20.1, on offbeat-stuff/pojavium, I would like to ask you to do the same thing, but with rubidium. If you already have it, please give it to me.

### Anything else?

No

**Comment by GaucovyAero** [comment]
i dont really have time to do it, recreate the patch yourself
