### ISSUE TITLE
[BUG] Weird black polygons

### ISSUE THREAD

**Issue by Marshall2439** [PojavLauncherTeam/PojavLauncher#4935]
### Describe the bug

I have no clue why are these occuring but there are these weirdly shaped polygons appearing out of nowhere and making game unplayable. 
![Screenshot_20231207_190503_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143608089/99569244-4e41-4c7e-b6ff-841049d27914)
![Screenshot_20231207_190424_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143608089/add3290c-5deb-4c94-9d9b-97e9ce9127e6)
![Screenshot_20231207_190440_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143608089/57868906-214e-421f-8238-51a55ff37540)
![Screenshot_20231207_190515_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143608089/b70095cc-879f-47bf-9fce-c8f4884d7fc0)

The game is modded, forge version 36.2.39

### The log file and images/videos

[2023-12-07-6.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/13612219/2023-12-07-6.log.gz)

### Steps To Reproduce

```markdown
Select Zink renderer and run modded minecraft (forge)
```

### Expected Behavior

To run minecraft normally

### Platform

```markdown
- Device model: Samsung A53 5G
- CPU architecture: 64
- Android version: 13
```

### Anything else?

Fix this asap please

**Comment by Bel69420** [comment]
I think your Vulkan driver has a bug

**Comment by Bel69420** [comment]
Had*

**Comment by Marshall2439** [comment]
What

**Comment by Marshall2439** [comment]
If it "Had" bug then it should not give this error

**Comment by Bel69420** [comment]
Tell me your mods

**Comment by Marshall2439** [comment]
There are many but mods that need Zink are:
Create
Immersive railroading
Immersive engineering

**Comment by Marshall2439** [comment]
I can give zip file of modpack

**Comment by Bel69420** [comment]
Do /flywheel backend off

**Comment by Marshall2439** [comment]
What does that mean? Disable flywheel?

**Comment by Bel69420** [comment]
Yes

**Comment by Marshall2439** [comment]
Yeah I tried it and it still doesn't work

**Comment by GaucovyAero** [comment]
you sent the wrong log, send latestlog.txt (guide on how to send it is in the issue template)

i presume the error comes up because you dont have enough extensions on your gpu to use some other extensions on zink

**Comment by Marshall2439** [comment]
I can't send log it's not working

**Comment by GaucovyAero** [comment]
then im closing this as invalid

**Comment by Marshall2439** [comment]
How is this invalid

**Comment by Marshall2439** [comment]
> you sent the wrong log, send latestlog.txt (guide on how to send it is in the issue template)
> 
> i presume the error comes up because you dont have enough extensions on your gpu to use some other extensions on zink

Dude my phone supports vulkan

**Comment by Bel69420** [comment]
But your Vulkan driver is broken

**Comment by Bel69420** [comment]
:trollface:
