### ISSUE TITLE
Forge 1.12.2 doesn't work and crashes

### ISSUE THREAD

**Issue by EggsPeggs** [PojavLauncherTeam/PojavLauncher#4936]
### Describe the bug

I tried to use forge 1.12.2 to play minecraft with some forge mods. But the loader creashes.
I am using 
Samsung galaxy M31
Processor: Exynos 9611
GPU: Mali-G72

I am using 2320 mb memory allocation (i ususally play 1.20.1 and use 3000+ mb. Sometimes it says using too much might crash the game so i used a lower memory since it was crashing. But no, it didnt work. 1.20.1 forge,fabric,optifine works just fine but Forge 1.12.2 and the previous versions just crash)
It says "Application/game exited with code 1"

I tried both using pojavs internal mod/mod loader installer.
I also tried to install the mod from the internal mod installer.

But all of them crashed.

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13613288/latestcrash.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13613289/latestlog.txt)

### Steps To Reproduce

```markdown
1) start pojav launcher
2)click create new profile 
3) choose forge profile
4) choose 1.12.2 (None of the forge versions work)
```

### Expected Behavior

I expected the game to load normally. 

### Platform

```markdown
- Device model: Samsung Galaxy M31
- CPU architecture: Exynos-9611
- Android version: Android 12
- PojavLauncher version: Version edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
mc 1.12.2 requires java 8, not 17
