### ISSUE TITLE
Rlcraft/ Medieval minecraft  mods don't work

### ISSUE THREAD

**Issue by EggsPeggs** [PojavLauncherTeam/PojavLauncher#4938]
### Describe the bug

I was trying to play with some mods but none of them work.
I tried rlcraft(1.12.2) medieval minecraft (Both forge and fabric versions 1.19.2)
None of them work.
When i tried to play rlcraft, created a new world, it took a really long time to load. the screen popped up with the hunger,thirst bar and everything but hen it said shutting down internal server for no reason and crashed.
For medieval minecraft, it took a long time to create a world and just crashed.

I tried to play on two aternos servers with each of these mods. But they crashed as well.
I used pojavs internal mod installer.
My friend joined the server and could play normally (He used tlauncher)

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13623325/latestcrash.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13623327/latestlog.txt)
[latestlog(medieval i renamed it to make it clear).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13623330/latestlog.medieval.i.renamed.it.to.make.it.clear.txt)

### Steps To Reproduce

```markdown
1) start pojav
2) create new profile-modpack-rlcraft(1.12.2)/medieval(1.19.2)
```

### Expected Behavior

I expected the mods to work

### Platform

```markdown
- Device model: Samsung galaxy m31
- CPU architecture: Exynos 9611
- Android version: 12
- PojavLauncher version: Version edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I dont think the problem is with the mods. It worked for my friend normally in tlauncher

**Comment by GaucovyAero** [comment]
in order for rlcraft to not crash, remove these mods:

- custommainmenumod
- fancyblockparticles
- dynamic surroundings
- soundfilters

you might have to remove different ones on that other modpack based on whats in the log

**Comment by EggsPeggs** [comment]
> in order for rlcraft to not crash, remove these mods:
> 
> * custommainmenumod
> * fancyblockparticles
> * dynamic surroundings
> * soundfilters
> 
> you might have to remove different ones on that other modpack based on whats in the log

Ahh thank you rlcraft works now. But do you have any idea about the medieval minecraft mod?
