### ISSUE TITLE
Can you try to fix sildurs shader

### ISSUE THREAD

**Issue by crazymobile** [PojavLauncherTeam/PojavLauncher#494]
I try sildurs shader but my screen show black sky, green blocks and white grass and sand 
And I try to search on YouTube I see one same problems but it's for seus shader can you try to fix

**Comment by khanhduytran0** [comment]
Currently, only simple shaders will work.

**Comment by Zeyrox1090** [comment]
like wut?

**Comment by artdeell** [comment]
> like wut?

sildurs basic

**Comment by Zeyrox1090** [comment]
does it work?

**Comment by Zeyrox1090** [comment]
testing @thatone (artdeell)#0595

**Comment by Aqmal86** [comment]
can you make pojavlauncher support shader?

**Comment by Aqmal86** [comment]
> Saya mencoba sildurs shader tetapi layar saya menunjukkan langit hitam, balok hijau dan rumput putih dan pasir
> Dan saya mencoba mencari di YouTube Saya melihat satu masalah yang sama tetapi untuk seus shader dapatkah Anda mencoba memperbaikinya

same

**Comment by khanhduytran0** [comment]
We are not graphics developer, so we can't do that. Wait for GL4ES update.

**Comment by Aqmal86** [comment]
![Uploading Screenshot_2020-12-28-14-55-03-16.jpg…]()

**Comment by Aqmal86** [comment]
Invalid Program:gbuffer_skybasic,cloud,terrain,damageblock,entities,hand,weather,water
Invalid Program:Shadow

**Comment by jeremy985** [comment]
You need zink build bro to work your want shader

**Comment by Raden1** [comment]
how to solve bsl shader not working there is only a black image if using a sheder

**Comment by Raden1** [comment]
Can't use shaders if using shader the screen turns black

**Comment by jeremy985** [comment]
What kind of PojavLauncher did you download?

**Comment by 1493028** [comment]
Zink very laggy
