### ISSUE TITLE
Help needed/Bug Web displays and MCEF mods dont work and show a white screen.

### ISSUE THREAD

**Issue by hejejee** [PojavLauncherTeam/PojavLauncher#4941]
### Describe the bug

I tried to use WebDisplays and MCEF mods together in forge 1.12.2 (The mods version was 1.11 for MCEF and 1.1 for Webdisplays)

It loaded properly, opened a world, and i got the webdisplay, mouse, keyboard from my inventory. But when i turned the screen on, it was white.

### The log file and images/videos

![166836583-5a8677a6-f943-4e86-ab38-6031e5ddfe21~2](https://github.com/PojavLauncherTeam/PojavLauncher/assets/153409965/1f3f38c5-2994-4d8f-a708-d2f81202b58b)

(No logs i just used an image because i wont be able to submit it otherwise)

### Steps To Reproduce

```markdown
1) Start pojav
2) download mcef and webdisplay from montyolo and curseforge
3) put them in the mods folder 
4) start with forge 1.12.2
5) load a world, create a screen and turn it on
```

### Expected Behavior

I expected it to show something in the screen but it was white

### Platform

```markdown
- Device model: Samsung galaxy m31
- CPU architecture: exynos 9611
- Android version: 12
- PojavLauncher version: Version edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I dont think the problems with the mod

**Comment by hejejee** [comment]
SORRY I SENT IT TWIXE

**Comment by hejejee** [comment]
Sorry i acci

**Comment by hejejee** [comment]
Sorry accidentally closed the issue

**Comment by hejejee** [comment]
Sorry accidentally closed the issue

**Comment by Mathias-Boulay** [comment]
#1948
