### ISSUE TITLE
[BUG] Delay Input Caused by Spammed Log

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4942]
### Describe the bug

The Control input is delay which is unplayable (like walking automatically, incorrect action in button, unusable/delay left/right mouse). Caused by these message spamming the log: 

No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?

### The log file and images/videos
Test in Forge 1.8.9 without mod (Normal Input)
Comment Below.

Test in Fabric 1.20.2 with PojavOptimize Modpack (Delayed Input)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13627153/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install PojavOptimize Modpack
3. Play
4. Join Singleplayer/Multiplayer
5. Delay Input
```

### Expected Behavior

Expected to have an normal input and avoidance of trash 50MB latestlog.txt file....

### Platform

```markdown
- Device model: OPPO A5 2020
- CPU architecture: ARM64
- Android version: 10 (Q)
- PojavLauncher version: PlayStore (Version edelweiss-20230928-9484d0c-v3_openjdk)
```

### Anything else?

Suggestion is to add an option in app to throw the Minecraft Console/Log in /dev/null or just fix it completely :)

**Comment by ghost** [comment]
Broken Link:
Test in Forge 1.8.9 without mod (Normal Input)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13627171/latestlog.txt)

**Comment by ghost** [comment]
Please have an solution in console log (like having an option in modifying the output of log4j, or send the standard output in /dev/null), it is a long issue to me in 1.8.9 lunar client but it is not noticable, until now. I can't really remove some mod in the modpack because i can now reach the 100FPS that i can't achieve in some versions. BTW disabling the log in Log Output don't do anything.

**Comment by artdeell** [comment]
It is not caused by the log, it is a separate unrelated issue in the input system.

**Comment by ghost** [comment]
> It is not caused by the log, it is a separate unrelated issue in the input system.

Um i think it relates, i try optifine one(1.20.2) which is no reason to have an spam log, it works fine(but laggy), while in the fabric 1.20.2(spams alot that froze the Log Output section) delays.

**Comment by Fl414r** [comment]
#4789 
They not want fix it and just repeating "dont use sodium" and "use Vulkan"

**Comment by ghost** [comment]
> #4789 They not want fix it and just repeating "dont use sodium" and "use Vulkan"

Um gonna try using zink, but the sodium in gl4es works really well without spam in 1.20.1 in outdated playstore dahlia version. I think gonna use the patcher i found in google, where my sodium works normally in 1.20.1. 

Sorry for bad english, not practiced.

**Comment by GaucovyAero** [comment]
fixed in the latest actions build
