### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by joeiscool3112** [PojavLauncherTeam/PojavLauncher#4946]
### Describe the bug

I connect keyboard and when i press shift + W the screen glitched

### The log file and images/videos

https://www.veed.io/view/28e14c7b-704f-411a-b666-c202bdb1a21c?sharingWidget=true&panel=share

### Steps To Reproduce

```markdown
1START POJAVLAUNCHER
2RUN 1.8.9 OPTIFINE
3. CONNECT NEYBOARD AND MOUSE
4. PRESSED SHIFt AND W
```

### Expected Behavior

I EXPECTED THE SCREEN WILL NOT GLITCHED

### Platform

```markdown
- Device model: IPHONE 11 PRO MAX
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

AND WHY I GOT BANNED FROM THE DISCORD FOR NO REASON, I Verified with my minecraft account

**Comment by joeiscool3112** [comment]
i checked my discord on my alt and they said i used mcfa, but the fact that i can prove its my account and he just banned be bc he though i bought minecraft from the link in my bio( i bought netfliz there wth)

**Comment by GaucovyAero** [comment]
this is a hardcoded android shortcut, bind fullscreen to a different key than f11
