### ISSUE TITLE
[BUG] Force Close When entering The world with forge

### ISSUE THREAD

**Issue by Iyanryzcut** [PojavLauncherTeam/PojavLauncher#4947]
### Describe the bug

Bug When the player using forge 1.20.1 , and using other mod ,Then it becomes a force close
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13649294/latestlog.txt)

### The log file and images/videos

Help me

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Using forge 1.20.1(Newest)
3.forge + optifine
4.create new world
5.start the world
6.Force close
```

### Expected Behavior

If this had been fixed I would have given it 5 stars

### Platform

```markdown
- Device model: CPH2043
- CPU architecture: aarch64
- Android version: android 12
- PojavLauncher version: (Newest) on playstore
```

### Anything else?

Help me

**Comment by Iyanryzcut** [comment]
Bro help me

**Comment by ghost** [comment]
What is name is your mods you install in forge

**Comment by GaucovyAero** [comment]
optifine is not compatible with latest forge rn, dont use it, be sure to also not use sodium/rubidium or similar because those crash on pojav

**Comment by Proaman7603** [comment]
So which performance mod are compatible with forge in pojav pls reply fast
