### ISSUE TITLE
Typing problem in servers

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#4949]
### Describe the bug

When I type an message my whole sentence got disappeared and only the last word was showing to all friends  of  my server

### The log file and images/videos

I don't have 

### Steps To Reproduce

```markdown
Start pojavlauncher
Join server
Type any message
Message got disappeared 
Only last word  left
```

### Expected Behavior

I want to talk with my friends

### Platform

```markdown
- Device model: Poco C3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

Please hlep

**Comment by GaucovyAero** [comment]
cannot reproduce, please record a video from your phone and send your friends' videos

**Comment by GaucovyAero** [comment]
closing as stale
