### ISSUE TITLE
[BUG]crashes when starting forge 1.18.2

### ISSUE THREAD

**Issue by Gaanbiktimi** [PojavLauncherTeam/PojavLauncher#4950]
### Describe the bug

crashes at startup (forge 1.18.2 40.2.14)
Mods:create (1.18.2 0.5.1f)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13656832/latestlog.txt)
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13656833/latestcrash.txt)

### Steps To Reproduce

```markdown
1.launch forge 1.18.2 (zink visualizer)
2.installing the create mod
3. launch
done
```

### Expected Behavior

correction

### Platform

```markdown
- Device model: infinix hot 12 pro
- CPU architecture: arm64-8a
- Android version: 12
- PojavLauncher version:new
```

**Comment by GaucovyAero** [comment]
seems like you got out of actual memory (if you get a warning, be sure to allocate at least 10% less than the maximum memory allocation)
