### ISSUE TITLE
[BUG] Minecraft doesn't work on new versions 

### ISSUE THREAD

**Issue by TimRou4** [PojavLauncherTeam/PojavLauncher#4951]
### Describe the bug

When entering versions such as 1.16.5 or 1.19.2, after starting Minecraft where the main menu appears, the game stops responding to any actions.  The multiplayer button is disabled.  Other buttons don't work.  Using the mouse the buttons also do not work.  I asked my friends to check the same thing, so this is not just my mistake

### The log file and images/videos

![Screenshot_20231213_191538](https://github.com/PojavLauncherTeam/PojavLauncher/assets/125994989/2f4ee343-1476-4efe-8056-72a7dd56ef59)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Honor x9
- CPU architecture: -
- Android version: 13
- PojavLauncher version: Last
```

**Comment by GaucovyAero** [comment]
reinstall pojav and delete all of its data when uninstalling
