### ISSUE TITLE
[Black Screen] When using Mclib Mod or Blockbuster mod 

### ISSUE THREAD

**Issue by Iyanryzcut** [PojavLauncherTeam/PojavLauncher#4953]
### Describe the bug

Black screen when we using Mclib Mod or Blockbuster mod, with render : Holy4ges 
Black screen total 100% black screen on android 12

### The log file and images/videos

........Fix it

### Steps To Reproduce

```markdown
1.Install Mclib Mod
2.Enter pojav
3.Loading mojang screen
4.Black Screen!
```

### Expected Behavior

I hope it Will be fixed:)

### Platform

```markdown
- Device model: android
- CPU architecture: aaarch64
- Android version: 12
- PojavLauncher version: (Newest)
```

### Anything else?

Pls fix this bug because I want to make another video using Blockbuster mod and mclib

**Comment by Iyanryzcut** [comment]
Fix it 💀

**Comment by Bel69420** [comment]
We can't fix it until you send the latestlog

**Comment by Bel69420** [comment]
latestlog.txt*

**Comment by GaucovyAero** [comment]
send log

**Comment by lost72738** [comment]
You need turn on fast render on in optionsof.txt to not being black screen
if U don't see optionsof.txt put Optifine in forge mods like mods folder
