### ISSUE TITLE
[BUG] add Microsoft account bug or not

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4955]
### Describe the bug

![Screenshot_20231214-235608](https://github.com/PojavLauncherTeam/PojavLauncher/assets/67903447/24e03b39-8474-4b70-a027-694303ad4bef)
I'm install pojav launcher on my new phone.
this error appeared. I recently purchased a license from me and I played with it before in pojavlauncher

### The log file and images/videos

this error appeared. I recently purchased a license from me and I played with it before in pojavlauncher

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Logging account type Microsoft
3. This message
```

### Expected Behavior

O

### Platform

```markdown
- Device model: realme c30
- CPU architecture: arm7vi
- Android version: 11
- PojavLauncher version: lastes
```

**Comment by GaucovyAero** [comment]
log into minecraft.net first and set up your account if it needs something to be configured, not a pojav issue
