### ISSUE TITLE
[F-Req] <Holy GL4ES>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#4956]
### Describe the request.

Can Holy Gl4es be updated to support OpenGL 4.6?

**Comment by sa1672ndo** [comment]
it prob can be done if you donate ptitSeb couple hundred dollars to make him continue to work on gl4es.
You can find his paypal here> https://github.com/ptitSeb/gl4es

**Comment by genericgithubaccount185** [comment]
# We did **not** make gl4es.
ptitseb did, you can ask him to continue working on gl4es and donate to him, [here's his repo](https://github.com/ptitSeb/gl4es)
