### ISSUE TITLE
[BUG] Pojav can't load Curseforge packs

### ISSUE THREAD

**Issue by Fl414r** [PojavLauncherTeam/PojavLauncher#4957]
### Describe the bug

Modrinth packs works as well, but Curseforge packs can't be loaded.

### The log file and images/videos

![Screenshot_20231216_104125_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/74704475/d487dbc2-514d-41d9-b9c7-edb3a4671850)

### Steps To Reproduce

```markdown
1) Start Pojav
2) Open "create new instance" menu
3) Search modpacks and try to load any
```

### Expected Behavior

I can load not only Modrinth packs

### Platform

```markdown
- Device model: Honor 9C (AKA-L29)
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: edelweiss-20231211-c6a6c54-rew/_java_gui_changes (#4564)
```

**Comment by GaucovyAero** [comment]
fixed in the recent github actions builds

**Comment by ZenZenXDz** [comment]
> fixed in the recent github actions builds

Doesn't seem to be fixed.
