### ISSUE TITLE
[BUG] Pantalla negra, forge 1.12.2

### ISSUE THREAD

**Issue by nothingonhere** [PojavLauncherTeam/PojavLauncher#4958]
### Describe the bug

Después de que forge inicie todo correctamente y este en el menú la pantalla aparece completamente negra, y cuando logro entrar a un mundo, sigue igual, solo las pantallas de carga si se muestran con normalidad.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13692364/latestlog.txt)
![Screenshot_20231216-044901](https://github.com/PojavLauncherTeam/PojavLauncher/assets/153989175/bef983bc-754b-4e59-82d4-3be974bea3d0)

### Steps To Reproduce

```markdown
El problema viene con el mod de emoticons, al instalarlo y poner su respectiva librería (mclib 2.1) y al cargar completamente Minecraft muestra la pantalla completamente negra tengo otros 3 mods que no hacen conflicto los cuales son optifine, 3dskinlayers y offlineskins los cuales funcionan correctamente, al lograr entrar a un mundo sigue igual con la pantalla negra, solo que las pantallas de carga son las que si se muestran, la versión de mc es la 1.12.2 y la de forge la última que salió la 60.
```

### Expected Behavior

Creo que lo que ocurre será alguna incompatibilidad con el render o algo por el estilo normalmente pongo el máximo de ram que se puede en mi PojavLauncher (1000mb)

### Platform

```markdown
- Device model: Redmi A2 2/32
- CPU architecture: arm64
- Android version: 13 Go Edition
- PojavLauncher version: edelweiss-20230928-9484d0c-V3-openjdk
```

### Anything else?

El mod lo necesito para probar algunas animaciones que estoy haciendo, y necesito esa versión en específico ya que es en dónde se implemento esa opción.

**Comment by GaucovyAero** [comment]
wont fix, dont use mods that dont work like this, they likely require newer opengl functions which gl4es doesnt have
