### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Codershell911** [PojavLauncherTeam/PojavLauncher#4959]
### Describe the bug

When i click play DIRECT BLACK SCREEN IT DIDNT EVEN LOAD ANYTHING ONLY THE CONTROLS EVEN NO SOUND

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13693672/latestlog.txt)

### Steps To Reproduce

```markdown
1. I start the app
2. I click play
3. Black screen appears
4. Controlls appears too
5. Notification appears on the screen it is talking about ram
Latest. I HAVE A FAST SAMSUNG GALAXY A14
```

### Expected Behavior

To play properly

### Platform

```markdown
- Device model: Samsung galaxy A14
- CPU architecture: ×64 supportive
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Downloaded from playstore not an apk

**Comment by artdeell** [comment]
press "OK" on the ram notification

**Comment by Codershell911** [comment]
> press "OK" on the ram notification

I did

**Comment by Codershell911** [comment]
> press "OK" on the ram notification

Still black screen

**Comment by Codershell911** [comment]
> press "OK" on the ram notification

And i waited hours too

**Comment by GaucovyAero** [comment]
decrease the ram allocation to 650MB, and if that doesnt work, reinstall pojav

**Comment by Codershell911** [comment]
How
