### ISSUE TITLE
Не меняется язык и не открывается мир в 1.7.10

### ISSUE THREAD

**Issue by Eurannic** [PojavLauncherTeam/PojavLauncher#496]
При нажатии (пальцем или курсором) на мир он не выбирается, тем самым его нельзя открыть. Тоже самое с выбором языка.

**Платформа:**
 - Модель девайса [Samsung Galaxy A10]
 - Архитектура процессора [aarch32] 
 - Версия Android [10]

<details> <summary><b>Дополнение</b></summary>
<br>
<pre>
Я пробовал в версиях 1.7.10+ (1.16.4) и там это уже работало.
</pre>
</details>

**Comment by artdeell** [comment]
Известное. Мир не выбрать ещё с 1.8.

**Comment by KostyanSigaev** [comment]
Везёт... У меня лаунчер вообще не стартует
