### ISSUE TITLE
[BUG]  1.20.4+ SODIUM CRASH 

### ISSUE THREAD

**Issue by cheesakeyk** [PojavLauncherTeam/PojavLauncher#4960]
### Describe the bug

Is there any way to fix sodium 1.20.4+ to run? Whenever I try to join a world It will crash. 
Plus help 

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

1 open pojavlauncher version latest from the playstation
2 run 1.20.4 fabric with sodium mod 
3 join a world
4 crashed

### Platform

```markdown
- Device model: CPH2179
- CPU architecture: octacore (not sure)
- Android version: 10
- PojavLauncher version: dahlia-20230813-5e8842b-v3_openjdk
```

**Comment by GaucovyAero** [comment]
sodium uses gl functions that pojav doesnt support, so its obviously not going to work
