### ISSUE TITLE
Rl craft bug

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#4961]
![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13696107/latestlog.txt)

I tried using rl craft it crashes when i try to join a world i join it for a sec and then it says "shutting down internal server"

**Comment by GaucovyAero** [comment]
remove these mods:

- custommainmenumod
- fancyblockparticles
- dynamic surroundings
- soundfilters

**Comment by Areez96** [comment]
How do I remove a specific mod from a modpack
