### ISSUE TITLE
[BUG] Microsoft login ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by artiom99338** [PojavLauncherTeam/PojavLauncher#4964]
### Describe the bug

when i click in the add account page on "Microsoft account" i get a blackscreen. Do you know, what I should do about that?
I cant even get the log data

### The log file and images/videos

![Screenshot_20231218_123229_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/153064557/0105f336-9f31-438f-872e-06df5cc97d36)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Click on add account
3. Click on Microsoft account
```

### Expected Behavior

I expected to get to the Microsoft login page

### Platform

```markdown
- Device model: Samsung Galaxy S20
- CPU architecture: i dont know
- Android version: 13
- PojavLauncher version: latest from Google play
```

**Comment by Minecon724** [comment]
I am getting net::ERR_UNKNOWN_URL_SCHEME

**Comment by arqalite** [comment]
Same error here - net::ERR_UNKNOWN_URL_SCHEME.

They seem to require Xbox Live authentication now, which is annoying. The protocol is ms-xal-00000000402b5328://auth/?code=<redacted>

**Comment by arqalite** [comment]
I solved mine by using ProtonVPN to connect to an United States server, that seems to bypass the Xbox Live Auth requirement. So if you run into ERR_UNKNOWN_URL_SCHEME, try that.

**Comment by artiom99338** [comment]
I soulved mine by restarting the device

**Comment by Minecon724** [comment]
neither suggestions work

**Comment by petermg** [comment]
I'm having this exact same issue, I'm getting ERR_UNKNOWN_URL_SCHEME

**Comment by GaucovyAero** [comment]
nobody has an idea why this is happening but ima keep this open, i suggest you rename this issue to "Microsoft login ERR_UNKNOWN_URL_SCHEME"

**Comment by GaucovyAero** [comment]
seems like this fixed itself, closing
