### ISSUE TITLE
[BUG] ANGLE Renderer causes red screen on 1.20.1

### ISSUE THREAD

**Issue by tom300z** [PojavLauncherTeam/PojavLauncher#4966]
### Describe the bug

I'm trying to run the Create Mod on Forge modded Minecraft 1.20.1 (Create requires OpenGL 3.2 / ANGLE).
However the game only shows a red screen.
Otherwise the game seems to work fine (i hear Music/Menu sounds).
The bug also occurs on a Vanilla 1.20.1 instance

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13712220/latestlog.txt)

### Steps To Reproduce

```markdown
1. Set up a 1.20.1 instance
2. Select the ANGLE Renderer in the settings
3. Launch and wait for music
```

### Expected Behavior

The Main Menu is displayed.

### Platform

```markdown
- Device model: Samsung Galaxy A54 5G
- CPU architecture: ARM
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I suspect this might be a Device/GPU specific problem.

**Comment by GaucovyAero** [comment]
turn off earlywindowcontrol in .minecraft/config/fml.toml

**Comment by tom300z** [comment]
Thanks for the suggestion, unfortunately this doesn't help.

I don't think this Problem is Forge related, as it also happens on a vanilla instance.
