### ISSUE TITLE
[BUG] crash 

### ISSUE THREAD

**Issue by Minecon724** [PojavLauncherTeam/PojavLauncher#4967]
### Describe the bug

it's launching as usual but stops after black screen

### The log file and images/videos

https://paste.sh/Kd1MqNmx#5Ailp_Af6IpUOlQ8u0PD9YqY

PojavLauncher crash report
 - Time: Dec 19, 2023 10:37:14
 - Device: lineage_begonia Redmi Note 8 Pro
 - Android version: 14
 - Crash stack trace:
 - Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.content.ComponentName.<init>(ComponentName.java:132)
	at android.content.Intent.<init>(Intent.java:7650)
	at net.kdt.pojavlaunch.ExitActivity.showExitMessage(ExitActivity.java:37)

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. start Minecraft
3. the game (black) screen appears normally but it crashes shortly after
```

### Expected Behavior

starting?

### Platform

```markdown
see log section
```

### Anything else?

fresh install

**Comment by Minecon724** [comment]
while the log says labymod it's also happening on vanilla 1.12.2 and any other version

**Comment by GaucovyAero** [comment]
reinstall pojav, your java runtime is corrupted

**Comment by Minecon724** [comment]
i did, first boot was fine then the error

**Comment by GaucovyAero** [comment]
not reproducable, the issue is on your end
but it could also be an android 14 thing

**Comment by GaucovyAero** [comment]
#5136 ?

**Comment by GaucovyAero** [comment]
cannot reproduce, please open a new issue and reference this
