### ISSUE TITLE
[BUG] Create crashed the game when a block that uses/transfers su is placed

### ISSUE THREAD

**Issue by kingsmen1234** [PojavLauncherTeam/PojavLauncher#4968]
### Describe the bug

When the fabric/forge version of create is loaded into a server/world any block that can rotate/transfer su will crash the game, but the decorational blocks dont

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13739584/latestlog.txt)

### Steps To Reproduce

```markdown
Start PojavLauncher on a forge/fabric version for 1.20.1 with create 0.5.1.f in the mods folder
Have angle/zink set as the renderer
Start a world (server/single player) with no create blocks
Place a shaft/cogwheel/waterweel/backtank and the game will crash,
```

### Expected Behavior

I expect the game to run smoothly like it has done before in previous instances 

### Platform

```markdown
- Device model: fire HD 10(11th generation) 
- CPU architecture: arm64 
- Android version: 10
- PojavLauncher version: edelweiss-20231217-031ad28-rew/_java_gui_changes
```

### Anything else?

I have player using create before, and it has never crashed

**Comment by kingsmen1234** [comment]
I now have some to add, even after going to the latest version it crashes still
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13739771/latestcrash.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13739772/latestlog.txt)

**Comment by GaucovyAero** [comment]
looks like a native crash, have you turned off the flywheel backend?

**Comment by kingsmen1234** [comment]
Omg thank you, it works and doesn't instantly crash
