### ISSUE TITLE
[BUG]v3.3 not working too

### ISSUE THREAD

**Issue by KostyanSigaev** [PojavLauncherTeam/PojavLauncher#497]
This time I will not write, but I will show everything on video:
https://youtu.be/XzlaGgF_PAM

**Comment by nedogimov** [comment]
You need usage v3.3 testing 1 or send log from /sdcard/games/.minecraft/latestlog.txt

**Comment by KostyanSigaev** [comment]
@nedogimov 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5701322/latestlog.txt)

**Comment by KostyanSigaev** [comment]
@nedogimov ты на x86 хоть раз запускал?

**Comment by nedogimov** [comment]
> @nedogimov ты на x86 хоть раз запускал?

Да, сегодня еще раз проверю дома

**Comment by nedogimov** [comment]
> @nedogimov ты на x86 хоть раз запускал?

По логам у тебя с памятью проблемы, скорее всего тебе надо в JVM аргументах прописать -Xms200M -Xmx500M
Значит у тебя всего 1 гб озу

**Comment by KostyanSigaev** [comment]
У меня 2 гб

**Comment by KostyanSigaev** [comment]
@nedogimov что у тебя за девайс?

**Comment by KostyanSigaev** [comment]
У меня ASUS ZenFone 5 T00F

**Comment by nedogimov** [comment]
> @nedogimov что у тебя за девайс?

У меня Samsung Galaxy Tab 2 (1 гб)

**Comment by nedogimov** [comment]
> У меня 2 гб

Скорее всего это связанно с тем что ты ставишь x86 рантайм, у меня тоже x86 такая же ошибка была. Пофиксил изменением нв меньшие настройки

**Comment by KostyanSigaev** [comment]
Вот тут у мегя проблема. В логе написано, что лаунчер не может в java определить arm архитектуру, т.к. мой процессор x86, но при этом сам лаунчер определяет его как arm, и при установке jre для x86 просто не запускает майн и пишет о неслвместимой архитектуре. Вот круг и замкнулся

**Comment by KostyanSigaev** [comment]
@nedogimov так на твоём же самсунге процессор архитектуры arm, а не x86... Скорее у него разрядность x86

**Comment by nedogimov** [comment]
> > У меня 2 гб
> 
> Скорее всего это связанно с тем что ты ставишь x86 рантайм, у меня тоже x86 такая же ошибка была. Пофиксил изменением нв меньшие настройки

Нет, там именно x86 + поддержка через патч arm

**Comment by KostyanSigaev** [comment]
А что если удалить arm библиотеки из лаунчера?

**Comment by ghost** [comment]
I cannot run Minecraft Forge 1.7.10 (other forges too). No errors - just a crash with the game code 1. I didn't even put any mods!

Я не могу запустить фордж 1.7.10 (другие форджи тоже). Никаких ошибок - только сбой игры с кодом 1. Хотя я даже моды не ставил!

**Comment by khanhduytran0** [comment]
So you run the installer or version?

**Comment by KostyanSigaev** [comment]
@KomyDaTb а без форджа у тебя работает?

**Comment by ghost** [comment]
> @KomyDaTb а без форджа у тебя работает?

Да, работает

**Comment by khanhduytran0** [comment]
Try: disable ARM emulation, then re-install the launcher.

**Comment by KostyanSigaev** [comment]
> Try: disable ARM emulation, then re-install the launcher.

Perhaps telepathists are sitting here ... Or perhaps not ... In any case, apart from the idea, you need to say how to do it ...

**Comment by WesleyVanNeck** [comment]
most of us are sleeping

**Comment by KostyanSigaev** [comment]
I installed android 7 on my phone and now the launcher correctly detects the architecture ... But now in the log there is such an incomprehensible error:
--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: x86/i*86
Info: Custom Java arguments: "-Xms384m -Xmx768m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
--------- beginning of main
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libfreetype.so success
S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libfontmanager.so failed: dlopen failed: cannot locate symbol "AWTFreeFont" referenced by "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libfontmanager.so"...
S/LaunchJVM( 7737): dlopen /data/app/net.kdt.pojavlaunch-1/lib/x86/libopenal.so success
S/LaunchJVM( 7737): dlopen /data/app/net.kdt.pojavlaunch-1/lib/x86/libgl04es.so success
S/LaunchJVM( 7737): Done processing args
S/LaunchJVM( 7737): Found JLI lib
S/LaunchJVM( 7737): Calling JLI_Launch
S/jrelog  ( 7737): Error occurred during initialization of VM
S/jrelog  ( 7737): Could not reserve enough space for 786432KB object heap

**Comment by WesleyVanNeck** [comment]
> I installed android 7 on my phone and now the launcher correctly detects the architecture ... But now in the log there is such an incomprehensible error:
> --------- beggining with launcher debug
> Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
> Architecture: x86/i*86
> Info: Custom Java arguments: "-Xms384m -Xmx768m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
> --------- beginning of main
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libfreetype.so success
> S/LaunchJVM( 7737): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libfontmanager.so failed: dlopen failed: cannot locate symbol "AWTFreeFont" referenced by "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libfontmanager.so"...
> S/LaunchJVM( 7737): dlopen /data/app/net.kdt.pojavlaunch-1/lib/x86/libopenal.so success
> S/LaunchJVM( 7737): dlopen /data/app/net.kdt.pojavlaunch-1/lib/x86/libgl04es.so success
> S/LaunchJVM( 7737): Done processing args
> S/LaunchJVM( 7737): Found JLI lib
> S/LaunchJVM( 7737): Calling JLI_Launch
> S/jrelog ( 7737): Error occurred during initialization of VM
> S/jrelog ( 7737): Could not reserve enough space for 786432KB object heap

You dont have anough ram it cant alocated it

**Comment by artdeell** [comment]
Known i*86 bug: you cannot allocate more than 128M of RAM. The game isn't playable on i\*86 platforms.

**Comment by KostyanSigaev** [comment]
@artdeell I specified 128 MB of RAM in the parameters and now the game closes with error 1

**Comment by KostyanSigaev** [comment]
I have new error
![Screenshot_20210106-101807](https://user-images.githubusercontent.com/71372830/103745696-9d108c80-5008-11eb-8d69-2a6efa40e3b6.png)

**Comment by khanhduytran0** [comment]
It's warning on android side. Ignore it

**Comment by KostyanSigaev** [comment]
@khanhduytran0 can you disable flags DT_FLAGS_1=0x81 in jre i386?
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5774966/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
Stale issue from a version many months old.
Closing
