### ISSUE TITLE
Crashwith Zink(Vulkan) [BUG] 

### ISSUE THREAD

**Issue by Davidparker2826** [PojavLauncherTeam/PojavLauncher#4970]
### Describe the bug

When I try to start the game with zink as renderer I just crashes . In the previous versions would be shown a gray screen for a split second and then everything would go black but now it just crashes instantly when I launch the game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13751467/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Select Zink(Vulkan) as renderer
3. Start the game
4. Game crashes after few seconds
```

### Expected Behavior

Expected To show the main menu of minecraft

### Platform

```markdown
- Device model: Samsung f14
- CPU architecture: IDK
- Android version: Android 14
- PojavLauncher version: edelweiss-20231221-5f39dd7-rep/bytehook
- GPU : Mali G68
```

### Anything else?

Was Thinking to use some shaders

**Comment by GaucovyAero** [comment]
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G68) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance
```

your gpu doesnt meet the requirements of zink, get a better phone
