### ISSUE TITLE
Vulkan Mod Buggy Textures

### ISSUE THREAD

**Issue by LionSh1ki** [PojavLauncherTeam/PojavLauncher#4972]
### Describe the bug

current vulkan mod patch makes some blocks not rendered or broken

### The log file and images/videos

![Picsart_23-12-23_12-17-32-009](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104547613/d872bf1f-99b1-443f-9178-63eaef417530)
![Picsart_23-12-23_12-25-05-323](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104547613/7e8c3c0f-1613-47dd-9591-581ebc0586de)
![Picsart_23-12-23_12-23-54-715](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104547613/71fc9215-d22f-4982-89d9-58c444e3d139)
![Picsart_23-12-23_12-23-08-787](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104547613/4f582f5a-72c8-49e0-94f2-92d63d46e9e5)
![Picsart_23-12-23_12-22-19-960](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104547613/e2ba2210-63b9-4550-8f33-0d07bbb82fa1)
![Picsart_23-12-23_12-19-55-354](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104547613/35440839-2235-4c80-bd9c-eaef0304c01b)
![Picsart_23-12-23_12-18-58-868](https://github.com/PojavLauncherTeam/PojavLauncher/assets/104547613/5b6e99f9-e09e-45ac-be33-b652b432c0a6)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.load fabric 1.20.1
3.enter world
```

### Expected Behavior

textures to be fixed 

### Platform

```markdown
- Device model: Infinix Note 30 5G 8/256G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20231210-5336b80-v3_openjdk
```

**Comment by AmarKherala** [comment]
i belive there's V14 for 1.20.2 that fixes this

**Comment by sa1672ndo** [comment]
Send latestlog.txt

**Comment by qinahqk** [comment]
Shshw

**Comment by LionSh1ki** [comment]
> Send latestlog.txt
> 

why would you need the log file the Textures are the only problem the rest works

**Comment by sa1672ndo** [comment]
> > Send latestlog.txt
> 
> why would you need the log file the Textures are the only problem the rest works

Because this issue was fixed some time ago, and I want to make sure that you are not using an old version of vulkanmod
