### ISSUE TITLE
[F-Req] Bring back Vgpu renderer

### ISSUE THREAD

**Issue by Marshall2439** [PojavLauncherTeam/PojavLauncher#4973]
### Describe the request.

Please add Vgpu back it was great renderer please

**Comment by GaucovyAero** [comment]
holy gl4es is faster and already has almost all of vgpu features integrated into it

**Comment by Marshall2439** [comment]
But it doesn't run shaders

**Comment by Marshall2439** [comment]
Idk if Vgpu can run shaders or not
