### ISSUE TITLE
I have the problem for play modpack in PojavLauncher

### ISSUE THREAD

**Issue by Polll252** [PojavLauncherTeam/PojavLauncher#4974]
I entered the world. After entering the world. within a few seconds.
Application/Game exited with code -1, check latestlog.txt for more details.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13760430/latestlog.txt)
I use the RLCraft modpack

**Comment by GaucovyAero** [comment]
remove these mods:

- custommainmenumod
- fancyblockparticles
- dynamic surroundings
- soundfilters

**Comment by Polll252** [comment]
thank for help
