### ISSUE TITLE
Sodium 1.20.2 v0.5.5 Crash Join World

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#4976]
### Describe the bug

* PojavLauncher Is not Supported when using Sodium.
* You Are Very likely to run into extreme performance issues,
* You Will be on your own if you decide to continue -- We Will not help you with any bugs or crashes!

Sodium Bug In Game Menu Fabric

### The log file and images/videos

There isn't any

### Steps To Reproduce

```markdown
Sodium 1.20.2 And Install Fabric
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo v23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Edelweiss-20230828-9484d0c-v3_openjdk
```

### Anything else?

Let me know immediately how to fix the sodium Bug

**Comment by GaucovyAero** [comment]
thats a warning created by the sodium devs to tell you that sodium will not work, because it uses opengl features unsupported by pojav
