### ISSUE TITLE
[BUG] LabyMod 4 Crash

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#4977]
### Describe the bug

LabyMod 4 Crash Code -1 Play In Game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13761616/latestlog.txt)

### Steps To Reproduce

```markdown
Install Labymod
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Edelweiss-20230828-9484d0c-v3_openjdk
```

### Anything else?

Fix Crash LabyMod 4

**Comment by GaucovyAero** [comment]
duplicate issue, not supported
