### ISSUE TITLE
Low fps on servers

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#4978]
### Describe the bug

I am using 55 mods to boost fps in pojavlauncher 1.20.1 but in server my fps is very low like 20-25 . But in singleplayer i am getting about 60 fps

### The log file and images/videos

My log file is about 56 mb so can't  upload it

### Steps To Reproduce

```markdown
Start pojav launcher
Join server
Very low fps
```

### Expected Behavior

I expected that I can play on 60 fps

### Platform

```markdown
- Device model: Poco C3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest on playstore
```

### Anything else?

Pls give a solution fast

**Comment by Proaman7603** [comment]
Pls reply fast
I am using aternos server btw

**Comment by Bel69420** [comment]
Buy a new phone

**Comment by Proaman7603** [comment]
Why I think it's not my phone problem

**Comment by Bel69420** [comment]
Ofc it your phone problem

**Comment by Bel69420** [comment]
Look at the CPU and GPU

**Comment by Bel69420** [comment]
That your phone use

**Comment by Bel69420** [comment]
They're trash :trollface:

**Comment by GaucovyAero** [comment]
buy a faster phone or use lower settings, keep in mind that sodium is slower than optifine and optifine is slower than vulkanmod
vulkanmod doesnt work on all phones tho
