### ISSUE TITLE
[BUG] Can't Login Premium Account it stuck on half line 

### ISSUE THREAD

**Issue by Sahil88822** [PojavLauncherTeam/PojavLauncher#4979]
### Describe the bug

It's not logging my premium account 

### The log file and images/videos

![Screenshot_20231224-232123](https://github.com/PojavLauncherTeam/PojavLauncher/assets/151452139/2e8dc054-1e61-4824-89e0-f4e37877f547)

### Steps To Reproduce

```markdown
Just download latest version and try to login your account
```

### Expected Behavior

It should login

### Platform

```markdown
- Device model: Itel S23
- CPU architecture: idk 
- Android version: 12
- PojavLauncher version: Latest Play Store
```

**Comment by Sahil88822** [comment]
Can't login local also button not working

**Comment by GaucovyAero** [comment]
try using another network or logging into minecraft.net in your browser and setting up your profile

**Comment by Sahil88822** [comment]
Thank You Worked ☺️
