### ISSUE TITLE
[BUG] Minecraft don't start

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#498]
**Platform:**
 - CPU architecture: aarch32
 - Android Version: 7
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5698075/latestlog.txt)

**Comment by khanhduytran0** [comment]
You ran out of memory.

**Comment by Mateus13000** [comment]
> Você ficou sem memória.

What can I do?

**Comment by MateusL13** [comment]
> Você ficou sem memória.

Thank you!
