### ISSUE TITLE
[BUG] Controller Issues 

### ISSUE THREAD

**Issue by ItsJustJoshDev** [PojavLauncherTeam/PojavLauncher#4980]
### Describe the bug

When i move once the stick moves on its own I've tried multiple controllers that work fine on other games and devices

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13763182/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Play with controller
3. Leave with controller connected
4. Reboot pojav launcher
```

### Expected Behavior

The left stick should work fine

### Platform

```markdown
- Device model: Samsung Galaxy S10E (US Model)
- CPU architecture: idk
- Android version: 12.1
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
the play store build is outdated, use the latest one from github actions, guide is on the wiki
