### ISSUE TITLE
[BUG] Forge

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#4981]
### Describe the bug

1.17.1-forge-37.0.15 Crash Code -1 Play The Game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13763643/latestlog.txt)

### Steps To Reproduce

```markdown
Install Forge
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Edelweiss-20230828-9484d0c-v3_openjdk
```

### Anything else?

Fix Bug Forge 1.17.1

**Comment by GaucovyAero** [comment]
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```

hmm try using java 17 from android-openjdk-build-multiarch repository to see if it makes any difference

**Comment by Dilen0001** [comment]
Nothing Even Appears
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13765998/latestlog.txt)

**Comment by Dilen0001** [comment]
But Version 1.17.1-forge-37.1.1 Whereas 1.17.1-forge-37.0.15 Exit Code -1

**Comment by GaucovyAero** [comment]
37.1.1 is newer, so just use that, the older one probably just had a bug
