### ISSUE TITLE
[F-Req] Change Skins

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#4982]
### Is this request related to a bug?

![IMG_20231226_093807](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/5756f5c8-42e2-4c16-bf26-e3a336d8bc00)

### Describe the request.

I Want To Add Change Skin Feature In PojavLauncher

### Anything else?

Please Add This Feature

**Comment by GaucovyAero** [comment]
duplicate issue, no, use another app
