### ISSUE TITLE
Create mod no work new ANGEL RENDER (VULKAN)[F-Req] <Short description>

### ISSUE THREAD

**Issue by JaydevGaming4** [PojavLauncherTeam/PojavLauncher#4983]
### Is this request related to a bug?

can you guys add old ANGEL RENDER 
it doesn't have crash Can add old ANGEL RENDER

**Comment by GaucovyAero** [comment]
no

**Comment by Bel69420** [comment]
Bro, the file still uploading and you sent it already.

**Comment by Bel69420** [comment]
Bro, the file still uploading and you sent it already.

**Comment by JaydevGaming4** [comment]
I am having problem with all these, I am playing in old pojavlauncher 
in which angel render runs
