### ISSUE TITLE
[BUG] Physics Mod

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#4985]
### Describe the bug

Physics 1.19.3 Crash In Game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13774986/latestlog.txt)

### Steps To Reproduce

```markdown
Install Physics Mods And Fabric 1.19.3
```

### Expected Behavior

Please Tell Me How to Solve It

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64 
- Android version: 13
- PojavLauncher version: Edelweiss-20230828-9484d0c-v3_openjdk
```

### Anything else?

There isn't any

**Comment by Forever2397** [comment]
Currently the physics mod only works on version 1.20.1+

**Comment by Dilen0001** [comment]
Give me the link

**Comment by Mario191209** [comment]
Join pojav launcher discord server

**Comment by Mario191209** [comment]
:trolley:
