### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#4986]
### Describe the bug

Entering the new function and customizing the icon interface will let us select an image file. At this time, if we exit without selecting any file, the application will crash directly.

### The log file and images/videos

![Uploading Screenshot_20231227_195210.jpg…]()

### Steps To Reproduce

```markdown
Open the app.
Change the custom icon.
Crash occurs without selecting any file to exit.
```

### Expected Behavior

After choosing the file interface to exit, nothing happens to return to the main page instead of crashing.

### Platform

```markdown
-设备型号:VIVOy83
n- CPU架构:n-64
 Android版本:8.2
n-pojavluncher版本:December 24th layout cropped version.
```

### Anything else?

No.

**Comment by GaucovyAero** [comment]
your image did not upload, wait for it to upload and then post the issue/comment

**Comment by GaucovyAero** [comment]
moreover, the feature you are trying to use is unfinished for now and not in v3_openjdk, therefore closing
