### ISSUE TITLE
[BUG] <Game crashes on startup >

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#4987]
I wanted to play on the Survival Minecraft server, but to do this I need to log in through the launcher with a username and password.

**Comment by Prostop194** [comment]
![Screenshot_20231228_000509_Cx File Explorer](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/e7c4c359-2b27-4954-991f-ab953956438f)
![Screenshot_20231228_000503_Cx File Explorer](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/8b84d30a-c528-4c5a-9459-bd9559cfa9e6)
![Screenshot_20231228_000454_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/83e4d4b5-6fe1-4ac5-a7d9-015f2b619a89)

**Comment by Prostop194** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13780411/latestlog.txt)

**Comment by GaucovyAero** [comment]
unsupported
