### ISSUE TITLE
[BUG] <Short description> external mouse problem 

### ISSUE THREAD

**Issue by Jdvdhtdmxh** [PojavLauncherTeam/PojavLauncher#4988]
### Describe the bug

https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/51df579e-571f-4d63-aa13-e280db2996a0

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/350e72da-0422-4b09-92a1-36b3532d7e79

### Steps To Reproduce

```markdown
Start pojavlauncher and try extermal mouse and click and move fast
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: infinix zero 5g
- CPU architecture: dimensity
- Android version: 12
- PojavLauncher version: all
```

### Anything else?

I got 500 fps thanks

**Comment by Jdvdhtdmxh** [comment]
Please fix this bro please

**Comment by Jdvdhtdmxh** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/04df0bd0-eb23-4ed5-8aa8-41566b9be2d8

Ever time i wanted to play this happens bro i can't play with this problem

**Comment by GaucovyAero** [comment]
duplicate issue, samsung and infinix phones do this, get a phone with a custom rom if you want to play normally with an external mouse

**Comment by Jdvdhtdmxh** [comment]
Bruh it won't happen in fold craft

**Comment by Jdvdhtdmxh** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/de63b3f5-14fa-4515-92ca-f13a719204eb

**Comment by Jdvdhtdmxh** [comment]
My brothers realme phone also dose this in poiav launcher same problem
