### ISSUE TITLE
[BUG]v3.3 testing 1 doesn't seem to want to launch Fabric

### ISSUE THREAD

**Issue by dbl7id** [PojavLauncherTeam/PojavLauncher#499]
Fabric tries to initialize JARs but doesn't even get past that stage, the game just exits.

1. Start PojavLauncher
2. Install Fabric for 1.16.4 using the install modloader option
3. Launch Fabric
4. After a few seconds, launcher will give a "Game exited" message.

 - Device Model: Samsung Galaxy S6+
 - CPU architecture: AArch64
 - Android Version: 7

Log
[00:42:41] [main/INFO]: Loading for game Minecraft 1.16.4 
[00:42:41] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...

**Comment by khanhduytran0** [comment]
Didn't you download vanilla first?

**Comment by dbl7id** [comment]
> 
> 
> Didn't you download vanilla first?

I did

**Comment by WesleyVanNeck** [comment]
try the latest dev build (from github actions)

**Comment by Mathias-Boulay** [comment]
Stale issue with an old version, closing the issue.
