### ISSUE TITLE
[BUG] <BETTER MC FORGE 1.16.5 CRASH>

### ISSUE THREAD

**Issue by RealTTraction** [PojavLauncherTeam/PojavLauncher#4990]
### Describe the bug

I have a problem in the better mc forge 1.16.5 
Everything loads fine i clicked the video segttings its working with rubidium mod
But when i press create new world its kick me from the lancher without any text
But you can check the lastestlog
And i was using this file for making rubidium works: https://www.mediafire.com/file/5p56yswkq3be24d/rubidium-mixins.properties/file?dkey=dgvxnvl4pzs&r=1271

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13786469/latestlog.txt)

### Steps To Reproduce

```markdown
Idk
```

### 

### Platform

```markdown
- Device model:samsung SM-M127F
- CPU architecture:arm64 
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Idk

**Comment by GaucovyAero** [comment]
sodium and related mods use opengl functions that gl4es does not support
