### ISSUE TITLE
[F-Req] Add a "Add Mod" button for modded profiles.

### ISSUE THREAD

**Issue by bettywolfy** [PojavLauncherTeam/PojavLauncher#4991]
### Is this request related to a bug?

I can't access the "Android" folder, so a button to add mods would be useful.

### Describe the request.

Add an option to add mods to modified profiles?

### Anything else?

Unfortunately, due to Google's new policy, it is no longer possible to access the "Android" folder, making modded profiles useless.
I've already tried using apps like ZArchiver.

**Comment by GaucovyAero** [comment]
more like a built-in file manager but yes, should be done in my opinion
what phone? can you try using mixplorer to access the directory? free download 6.6x.x from mixplorer.com

**Comment by bettywolfy** [comment]
> more like a built-in file manager but yes, should be done in my opinion
> what phone? can you try using mixplorer to access the directory? free download 6.6x.x from mixplorer.com

It's not the best option for me at the moment.

**Comment by GaucovyAero** [comment]
> > more like a built-in file manager but yes, should be done in my opinion
> > what phone? can you try using mixplorer to access the directory? free download 6.6x.x from mixplorer.com
> 
> It's not the best option for me at the moment.

at least try and see if it works, this feature is not going to be implemented anytime soon

**Comment by bettywolfy** [comment]
> > > more like a built-in file manager but yes, should be done in my opinion
> > > what phone? can you try using mixplorer to access the directory? free download 6.6x.x from mixplorer.com
> > 
> > It's not the best option for me at the moment.
> 
> at least try and see if it works, this feature is not going to be implemented anytime soon

I can't download anything outside the play store, thanks for your help, but unfortunately I'll have to wait until a final answer.

**Comment by bettywolfy** [comment]
Yeah... it's going to take a while...

**Comment by radiantgurl** [comment]
Same issue here

**Comment by radiantgurl** [comment]
> more like a built-in file manager but yes, should be done in my opinion
> what phone? can you try using mixplorer to access the directory? free download 6.6x.x from mixplorer.com

![Screenshot_20240314_201441_Files.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/69520693/7a6a883c-0182-4fa0-a507-e2601e33a610)

**Comment by radiantgurl** [comment]
Another app says this will work if you add the mods in from pc on the phone

**Comment by radiantgurl** [comment]
For a fully android method, use shizuku and termux to move over the mod files to `/storage/emulated/0/Android/net.kdt.pojavlaunch` (this is not the actual mod folder but a path directing you to where your install is.

**Comment by Algiuxs** [comment]
Use the hidden files app, works on android14

**Comment by Sebz102030** [comment]
Hiden file app everyone who has developer options can go by searching for system tracking and then open folder with log files with trace and then housing ppjavlancher

**Comment by Marcemcc** [comment]
You can unlock the android folder by wiping the data and uninstalling updates for all the file managers you have, doing this You will be able to enter the Android folder

**Comment by GaucovyAero** [comment]
use com.marc.files
