### ISSUE TITLE
[F-Req] Add custom path selection when create modpack profile

### ISSUE THREAD

**Issue by ConfectionaryQwQ** [PojavLauncherTeam/PojavLauncher#4994]
### Is this request related to a bug?

I download a modpack that have different minecraft versions.
e.g.
I download  Fabulously Optimized(FO)
for Minecraft 1.16.5 and 1.20.4 and I found that modpack files are in same filepath:
/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/custom_instances/fabulously optimized/
To prove this
If you open "mods" you'll found both 1.16 5 and 1.20.4 mods are in same file folder
And I can't select custom path before I download a new modpack.
![Image_1703914683704](https://github.com/PojavLauncherTeam/PojavLauncher/assets/91813030/ab713481-732b-472d-9f4b-4ac996d60151)
![Screenshot_20231230_133227_bin mt plus_edit_25597761530468](https://github.com/PojavLauncherTeam/PojavLauncher/assets/91813030/adc5af8e-667c-46a4-a25d-1cbd0b62c2a8)

### Describe the request.

Add custom path selection when create modpack profile.

### Anything else?

None

**Comment by root-S7** [comment]
"If you open "mods" you'll found both 1.16 5 and 1.20.4 mods are in same file folder"
版本隔离，但这个词我不知道应该怎么翻译它，应该是要求添加这个功能
