### ISSUE TITLE
[F-Req] Adding support for Third-party Apps.

### ISSUE THREAD

**Issue by SCOS100** [PojavLauncherTeam/PojavLauncher#4995]
### Is this request related to a bug?

No

### Describe the request.

Currently, the only way to access the PojavLauncher function requires root, so adding Third-party support would be great.
For example: An external application could make possible for automatic installation of versions, mods, or even an external launcher that could comunicate to PojavLauncher to launch or modifying versions.

### Anything else?

No

**Comment by GaucovyAero** [comment]
android does not allow this afaik
