### ISSUE TITLE
How to launch Sodium mod on minecraft 1.20.4

### ISSUE THREAD

**Issue by sqx02a** [PojavLauncherTeam/PojavLauncher#4999]
### Is this request related to a bug?

Please, make it possible to launch and play with Sodium mod

### Describe the request.

When i try to launch the world with Sodium mod, minecraft just crashes

**Comment by Hanuko33** [comment]
Sodium doesn't support pojav, I tried using it, and while starting the game, I saw text saying that (at least on my device)

Use optifine, it works.

**Comment by Dilen0001** [comment]
Render Zink Work Sodium 1.20.4

**Comment by GaucovyAero** [comment]
it is possible but not right now
