### ISSUE TITLE
[BUG] Physical mouse doesn't work on right side of the screen on Android 14

### ISSUE THREAD

**Issue by imLucki** [PojavLauncherTeam/PojavLauncher#5000]
### Describe the bug

When you are using a physical mouse to play, you can't right or left click on the right side of the screen 

### The log file and images/videos

Isn't needed.

### Steps To Reproduce

```markdown
1. Start PojavLauncher on an Android device running Android 14.
2. Use a physical keyboard and mouse .
3. Try to Left or Right click on the right side of the screen.
```

### Expected Behavior

I expect the mouse to work normally.

### Platform

```markdown
- Device model: IQOO Neo 7
- CPU architecture: arm64-v8a
- Android version: 14
- PojavLauncher version: version edelweiss-20231230-78405e3-feat/profile_icon_customization
```

**Comment by imLucki** [comment]
hey guys, anyone know any temporary fix to this?

**Comment by RimakiTaema** [comment]
try to turn on inverted mouse for now

**Comment by OnlyonGamingOG** [comment]
I having the same problem in Realme gt neo 3t
On latest update Android 14 so please fix it 

PLEASE SOME ONE FIX THIS TEMPRARY

**Comment by OnlyonGamingOG** [comment]
> try to turn on inverted mouse for now

Don't work

**Comment by RimakiTaema** [comment]
uhhhh so I don't have temp fix now i think wait unitl devs response and temp fix

**Comment by fearry** [comment]
me too     i lost half of my screen   please fix it

**Comment by RimakiTaema** [comment]
i will ask dev on discord server then i think will helps

**Comment by Frozensidxd** [comment]
I have optical mouse still not working pls help

**Comment by Frozensidxd** [comment]
Take action it's been months and months still it didn't fix how can we play

**Comment by Frozensidxd** [comment]
Gaucovyaero fix this

**Comment by GaucovyAero** [comment]
> Gaucovyaero fix this

im not even a developer lol, also this kind of device-specific stuff is a lot less likely to get fixed since we would need a device with such an issue, which we dont currently have

**Comment by GaucovyAero** [comment]
realme 12 plus 5g (android 14) also has this issue apparently

**Comment by GaucovyAero** [comment]
should be fixed in the latest play store update

**Comment by NoodleMeister** [comment]
@GaucovyAero Why do you keep closing these threads?
