### ISSUE TITLE
[BUG] Minecraft crashes when using optifine with forge

### ISSUE THREAD

**Issue by Zabolin148290** [PojavLauncherTeam/PojavLauncher#5002]
### Describe the bug

The game crashes when using optifine with forge when joining a world or server .The Forge and FML creators have officially announced that optifine will not work with forge and there is no other alternative performance mods (that works on pojav launcher). It is now impossible to play with mods without Optifine , please give a solution to this

### The log file and images/videos

Here is the log and crash files.
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/13802518/latest.log)
[crash-2024-01-01_07.12.00-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13802519/crash-2024-01-01_07.12.00-client.txt)

### Steps To Reproduce

```markdown
Put optifine in the mods folder and launch minecraft and join any world.
```

### Expected Behavior

I expected the world to open up correctly but the server crashed

### Platform

```markdown
- Device model: M2006C3LII
- CPU architecture: Octa-core Max 2.00GHz
- Android version: 10
- PojavLauncher version: Edelweiss
```

**Comment by GaucovyAero** [comment]
how are we supposed to give a solution when the issue is literally unrelated to pojav lmfao
