### ISSUE TITLE
Issues with Android 13 and above

### ISSUE THREAD

**Issue by ShadowYT4909** [PojavLauncherTeam/PojavLauncher#5003]
### Describe the bug

I have an s23 ultra and it's running on Android 14 rn but i cant seem to add mods to the pojav data folder because of the new thing that samsung did to their Android folder. I can still access the pojav data file but i can't really do anything else either than add and remove files 🫤

### The log file and images/videos

![Screenshot_20240101_135532_ZArchiver](https://github.com/PojavLauncherTeam/PojavLauncher/assets/112268815/0085e002-6e14-4e41-9d0c-3600fe19b388)

![Screenshot_20240101_135540_Files](https://github.com/PojavLauncherTeam/PojavLauncher/assets/112268815/2ca0c15a-438a-466e-b43d-dea4479d21c9)

### Steps To Reproduce

```markdown
1. Have an android device 13 and above

2. Use any file app

3. Try and copy your mods and go into the data folder which will mostly likely not be there even tho when you don't try and copy files into the folder you can see it
```

### Expected Behavior

I expected the pojav folder to be in the games folder since i knew that you could've done that before and I've been experiencing the stupid Android 13 isse for awhile now🫤🫤

### Platform

```markdown
- Device model: Samsung S23 Ultra
- CPU architecture: arm64-v8a armeabi-v7a armeabi
- Android version: 14
- PojavLauncher version: Edelweiss
```

### Anything else?

Maybe add like an option to add mods from your phone directly into the mods folder

**Comment by GaucovyAero** [comment]
there is a already a suggestion for like installing mods into pojav directly through the app, but its probably not going to be done anytime soon

for now, try different file managers like zarchiver and mixplorer (mixplorer free download 6.6x.x from mixplorer.com, its not paid, only the donation version is on play store), or you can try attaching the phone to a PC and going to the folder from your PC
