### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by 1248257** [PojavLauncherTeam/PojavLauncher#5004]
### Describe the bug

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13805740/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13805776/latestlog.txt)

### Steps To Reproduce

```markdown
Eu Baixei o instalador forge 1.7.10, instalou o forge e quando eu entrei deu o erro de código 1
```

### Expected Behavior

Eu espero que consertem isso...

### Platform

```markdown
- Device model:Samsung Galaxy J4+ (SM-J4 15G)
- CPU architecture:4× ARM Cortex-A53 @1,40 ghz
- Android version:9
- PojavLauncher version:edelweiss-20230928-9484dOc-v3_openjdk
```

**Comment by GaucovyAero** [comment]
you are missing codechickenlib

```
Exception in thread "main" [17:00:18] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
```

[CodeChickenLib-1.7.10-1.1.3.138-universal.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/13809616/CodeChickenLib-1.7.10-1.1.3.138-universal.zip)

extract this and put it into your mods like this

.minecraft/mods/1.7.10/CodeChickenLib-1.7.10-1.1.3.138-universal.jar
