### ISSUE TITLE
[BUG] <Blank Texture>

### ISSUE THREAD

**Issue by Yanji17** [PojavLauncherTeam/PojavLauncher#5006]
### Describe the bug

All the blocks are invisible the only thing I can see is the sky and the void. Mobs are visible including other players and entities like armor stand. Items in my inventory are also visible.

### The log file and images/videos

![Screenshot_20240103_114439_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/155512606/c299fbd3-9a91-485f-a5d4-aa6741630055)

### Steps To Reproduce

```markdown
1. Enter a world/server
```

### Expected Behavior

I expect that there would be texture or images of the blocks

### Platform

```markdown
- Device model: Samsung A12
- CPU architecture: 
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I downloaded mods to join my friends' mc server. My mc is not cracked. Minecraft version is "forge - 1.19.2-forge-43.3.5"

My friends with the same mods and version doesn't experience any bugs.

**Comment by Yanji17** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13815939/latestlog.txt)

**Comment by GaucovyAero** [comment]
patch sodium with the patcher located on the wiki

**Comment by Yanji17** [comment]
Hello how can I use the patcher? https://www.mediafire.com/folder/n004fh6pxuxk8/Sodium_1.17%2B
The link above is what the "patch" links to beside the sodium,, do I just download the .jar or also the 2 other files above it? After that what should I do? Sorry I'm really clueless about this thing.. thank you for the help!

**Comment by Yanji17** [comment]
> patch sodium with the patcher located on the wiki

Hello how can I use the patcher? https://www.mediafire.com/folder/n004fh6pxuxk8/Sodium_1.17%2B
The link above is what the "patch" links to beside the sodium,, do I just download the .jar or also the 2 other files above it? After that what should I do? Sorry I'm really clueless about this thing.. thank you for the help!

By the way, I looked at the mod list and we don't use sodium but rather, rubidium. In that case, how to use the patcher for rubidium found in https://www.mediafire.com/folder/jcyrf8l0osn4m/Rubidium_1.17%2B

Thanks again!
