### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by Hiho2950** [PojavLauncherTeam/PojavLauncher#5008]
### Describe the bug

When i run labymod 4 for 1.20.4 i got a crash

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/13818433/latest.log)

### Steps To Reproduce

```markdown
Install it and enter it
```

### Expected Behavior

I dont know why it doesn't work

### Platform

```markdown
- Device model: Samsung galaxy A12 nacho
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: last action build of v3_openjdk
```

### Anything else?

.

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
loading custom lwjgls is not supported on pojav
