### ISSUE TITLE
[BUG] <Crash When Creating World (Im Use 17 Mods)>

### ISSUE THREAD

**Issue by AkaBar74** [PojavLauncherTeam/PojavLauncher#5009]
### Describe the bug

Previously I made a world in Forge 1.18.2 (40.2.14) using 17 mods and it ran normally, (these are the mods I used
1.architecture
2. better combat
3. caelus
4.cloth config
5. curios
6.dungeon crawl
7. geckolib
8. immersive armor
9. ironspells books
10. jei
11.mowzies mobs
12. optifine
13.parcool
14.player animator
15.presence footsteps
16.shoulder surf
17.simply sword)
but recently when I created a world a warning appeared (experimental world settings) after I agreed to the warning, showing the loading process, the loading only reached 0 and after that the code -1 appeared

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13818953/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Play The Forge 1.18.2 (40.2.14)
3.Wait Loading
4.Create World
5.Appear Experimental World Warning
6.Agreed The Warning
7.Shows Loading Process
8.Loading Only Reached 0%
9.Code -1
```

### Expected Behavior

I expect the mods loaded,the world created,and run normally

### Platform

```markdown
- Device model: Samsung A12 Nacho
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
its not apparent whats the issue (likely not a pojav one), try removing some mods and see which one is causing the issue, its most likely a conflict between two mods
