### ISSUE TITLE
Vulkan mod crashes

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5010]
### Describe the bug

I tried to run vulkan mod on 1.20.1 but it crashes

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13820447/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher
Run fabric
Crashes
```

### Expected Behavior

Expected that my game will run smoothly

### Platform

```markdown
- Device model: Poco C3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

Reply fast

**Comment by lzfddkd** [comment]
Use VulkanMod patcher(VulkanMod_For_PojavLauncher)

**Comment by lzfddkd** [comment]
VulkanMod_For_PojavLauncher is here:https://www.mediafire.com/folder/xsb4udjs7n8z9/VulkanMod_for_PojavLauncher

**Comment by lzfddkd** [comment]
The issue you mentioned is similar to this issue #4778

**Comment by GaucovyAero** [comment]
```
java.lang.RuntimeException: Vulkan 1.2 not supported!: Only Has: 1.1.0
	at net.vulkanmod.vulkan.DeviceInfo.getVkVer(DeviceInfo.java:128)
```
your device does not support the mod, at least not the version you are running right now
