### ISSUE TITLE
when will OUYA be supported

### ISSUE THREAD

**Issue by jbmanlol** [PojavLauncherTeam/PojavLauncher#5011]
this should be on the failed game console the OUYA because after all they said minecraft was gonna be on here so it would make sense to put java on here due to it just being android 4 right?

**Comment by GaucovyAero** [comment]
your sentence does not really make sense but it should run if you are on android 4.4+ - minecraft versions 1.6 - 1.16.5 (ideally android 5.0+ - minecraft versions all up to 1.16.5)

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/folder/89o43qfvzbd6q/Android+4.4.4

here are unofficial builds of pojav for android 4.4
