### ISSUE TITLE
[BUG] World

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5012]
### Describe the bug

World Minecraft Error Render In Holy GL4ES

### The log file and images/videos

![Screenshot_20240104_122130](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/056bf14b-13d4-438c-b2d7-97dafd1465c2)
![Screenshot_20240104_123412](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/ad0b07f0-0bf9-4a13-98f2-71809bae27d3)

### Steps To Reproduce

```markdown
Install Maps And Version Minecraft
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Edelweiss-20230828-9484d0c-v3_openjdk
```

### Anything else?

Fix Bug World In Render Holy GL4ES

**Comment by GaucovyAero** [comment]
press f11, fullscreen off and on, fast render (if you are on optifine) off and on

if those dont work, its one of your mods causing the issue

**Comment by Dilen0001** [comment]
Render Zink Vulkan Work No Error

**Comment by duyanga** [comment]
receive







                       
原始邮件
                       
                     

发件人："Dilen0001"< ***@***.*** &gt;;

发件时间：2024/1/4 19:52

收件人："PojavLauncherTeam/PojavLauncher"< ***@***.*** &gt;;

抄送人："Subscribed"< ***@***.*** &gt;;

主题：Re: [PojavLauncherTeam/PojavLauncher] [BUG] World (Issue #5012)




 
Render Zink Vulkan Work No Error
