### ISSUE TITLE
[BUG] I can't use sodium patchers 

### ISSUE THREAD

**Issue by U374** [PojavLauncherTeam/PojavLauncher#5013]
### Describe the bug

I have installed sodium in it and then I installed sodium patcher but when I used it in execute .jar option in crashed

### The log file and images/videos

Info: Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/sodiumpatcher-1.0.1-SNAPSHOT.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1600
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~rWcHy_TPuPZfwes5Ige1Aw==/net.kdt.pojavlaunch-MFN1UgQJtyj4EkRbUP6a_g==/lib/arm
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32:/system/lib:/vendor/lib:/vendor/lib/hw:/data/app/~~rWcHy_TPuPZfwes5Ige1Aw==/net.kdt.pojavlaunch-MFN1UgQJtyj4EkRbUP6a_g==/lib/arm
Added custom env: LIBGL_NOERROR=1
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
--------- beginning of main

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success
I/jrelog  (19093): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlau
nch/runtimes/Internal/lib/aarch32/libfreetype.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libinstrument.so in namespace classloader-namespace
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnet.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libtinyiconv.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsound.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/liblcms.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libverify.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnio.so success
I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libnpt.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsig.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfontmanager.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjsdt.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libunpack.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjpeg.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2gss.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_headless.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsctp.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libzip.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libfreetype.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pcsc.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt_xawt.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava_crw_demo.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmlib_image.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjaas_unix.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libhprof.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjava.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libdt_socket.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjawt.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libmanagement.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libjdwp.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/client/libjvm.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/jli/libjli.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libawt.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libj2pkcs11.so success

I/jrelog  (19093): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch32/libsunec.so success

I/jrelog  (19093): dlopen /data/app/~~rWcHy_TPuPZfwes5Ige1Aw==/net.kdt.pojavlaunch-MFN1UgQJtyj4EkRbUP6a_g==/lib/arm/libopenal.so success

I/jrelog  (19093): Done processing args

I/jrelog  (19093): Found JLI lib

I/jrelog  (19093): Calling JLI_Launch

--------- beginning of system

Policy policy.url.2=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy (No such file or directory)
Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/*
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/notahero/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Java Exit code: 1
I/jrelog  (19093): Going to free args

I/jrelog  (19093): Free done

Install successful

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Click on execute .jar option
3. Click on sodium patcher file (first download it)
```

### Expected Behavior

I expect that it will patch sodium.

### Platform

```markdown
- Device model: redmi 10a
- CPU architecture: 8x ARM Cortex-A53 @ 2.00 GHz
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Plz solve it

**Comment by GaucovyAero** [comment]
you gotta use java 17 to launch the sodium patcher

**Comment by lost72738** [comment]
Try 1.17 or above
