### ISSUE TITLE
you gotta use java 17 to launch the sodium patcher

### ISSUE THREAD

**Issue by U374** [PojavLauncherTeam/PojavLauncher#5014]
you gotta use java 17 to launch the sodium patcher

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/5013#issuecomment-1877313421_

Plz give me that java 17 file which supports my device plz.

**Comment by GaucovyAero** [comment]
its integrated inside pojav, just launch 1.17+ for it to automatically install
