### ISSUE TITLE
[BUG]  external mouse problem

### ISSUE THREAD

**Issue by Jdvdhtdmxh** [PojavLauncherTeam/PojavLauncher#5017]
### Describe the bug

https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/8ab632bd-fcea-4018-94d8-7d9940ea89d1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13843656/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher and try realme Or infinixs phone if it's heppens you need to fix it ☹️
```

### Expected Behavior

Because of my phone

### Platform

```markdown
- Device model: realme
- CPU architecture:hellio g95
- Android version: 12
- PojavLauncher version: leatest
```

**Comment by GaucovyAero** [comment]
deemed as an issue with your phone for now

**Comment by Jdvdhtdmxh** [comment]
Okie ☹️

**Comment by Jdvdhtdmxh** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/141278166/83e63c11-3a21-4cb7-995f-bf8638d89ea1

**Comment by Jdvdhtdmxh** [comment]
Ok
