### ISSUE TITLE
Allow the app to access all files on Android

### ISSUE THREAD

**Issue by Enderteck** [PojavLauncherTeam/PojavLauncher#5018]
### Is this request related to a bug?

Not a bug but external apps such as synching can't access the Pooja launcher Files

### Describe the request.

I'd like to sync my worlds between PC And mobile but I can't put an instance in the documents folder for example.

I don't want to root my tablet but I think if I could allow the app to access all files there might be a possibility.

This would also make sharing modpacks easier and the usage of future mobile mod managers possible.

I'm not certain this idea is possible but I'd love if it was. Thx in advance for your feedback.

### Anything else?

Happy new year !

**Comment by GaucovyAero** [comment]
unsupported unless you somehow find a way to do it yourself, or come up with a code solution that will work, because pojav having access to other folders than the one in `/storage/emulated/0/Android/data/` would mean huge security risks
afaik, we could basically only move the pojav folder to `/data/`, which means you would need root even to install mods, edit files and such (which is obviously not a solution)

**Comment by Enderteck** [comment]
I'm not familiar with android's latest file security systems so, how do other apps get acces to the video or DCIM folder on our devices ?

**Comment by artdeell** [comment]
> I'm not familiar with android's latest file security systems so, how do other apps get acces to the video or DCIM folder on our devices ?

You can request permission to create files in shared storage, the problem with it is that when you reinstall the app you lose the permissions for the files you created.

I experimented putting the Pojav folder like this into Documents, but once the app got reinstalled, all existing files in it became inaccessible, which breaks the launcher *hard*.

**Comment by Fl414r** [comment]
> > I'm not familiar with android's latest file security systems so, how do other apps get acces to the video or DCIM folder on our devices ?
> 
> You can request permission to create files in shared storage, the problem with it is that when you reinstall the app you lose the permissions for the files you created.
> 
> I experimented putting the Pojav folder like this into Documents, but once the app got reinstalled, all existing files in it became inaccessible, which breaks the launcher *hard*.

With is strange, cuz to me it all works perfectly. I still use some apps that uses custom folders outside android/data (minecraft v0.5.0, Malody, PPSSPP, Telegram) and can access files by build-in explorer (Malody, PPSSPP, Mindustry) and there 0 problems with it.
I reinstalled some of them a lot, also 2 apps uses Telegram folder at same time and I never seen any problems. 
Only OSU!laser has problems with this, but it develops to 4 platforms (Windows, Linux, Mac and Android) at same time and Android version has lowest priority
