### ISSUE TITLE
Mouse capture not working (v3.3 / 1.12)

### ISSUE THREAD

**Issue by AZzyydeezz** [PojavLauncherTeam/PojavLauncher#502]
Mouse capture is not working for me and the mouse button doesn't work in game but in the minecraft menu they work. 

Right click is doing back button, left click is just pressing the "keyboard" button.

Configuration
Huawei P30 lite
Pojavlauncher V3.3
Usb Otg Hub
Mouse and Keyboard

I hope you guys can do somthing for this

**Comment by AZzyydeezz** [comment]
Oh and my android version is: 10.0.0.339

**Comment by khanhduytran0** [comment]
Known issue.

**Comment by AZzyydeezz** [comment]
> Known issue.

When do you think you can fix this?

**Comment by AZzyydeezz** [comment]
Btw you guys are awesome
