### ISSUE TITLE
[F-Req] <VirGL for other gpu>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#5020]
### Describe the request.

Because some GPUs do not support Zink.
And Zink creates beautiful shader.
At least bring back VirGL for nice shaders.

### Anything else?

VirGL also doesn't do bad FPS.
Try updating Mesa to VirGL, it may support version 1.17+.

**Comment by Natthakritp** [comment]
I tested VirGL and got 36-60 FPS.

**Comment by Natthakritp** [comment]
The Pojavlauncher I tested VirGL with is https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink

**Comment by Natthakritp** [comment]
Let's bring back VirGL to test the debug version.

**Comment by GaucovyAero** [comment]
you can use whatever pojav you want, but virgl is not going back into official pojav

**Comment by Marshall2439** [comment]
Vgpu is better cuz it had opengl 4.6
