### ISSUE TITLE
[BUG] Error when trying to enter on a multiplayer server

### ISSUE THREAD

**Issue by Koala555Koala** [PojavLauncherTeam/PojavLauncher#5021]
### Describe the bug

I want to pay for a multiplayer server, but first I made an Aternos server for test to see if all is good with connection, but I get an error every time I try to connect as you van see in the photo. Please help me with a solution.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13853004/latestlog.txt)

![Screenshot_20240107_012951_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/155856828/07eaa741-1b78-48e2-82c4-31d9285df57d)

### Steps To Reproduce

```markdown
1. Start pojavlauncher(offline account)
2. Enter multiplayer
3. Enter a server
4. Get the error every time
```

### Expected Behavior

I expect to join the server

### Platform

```markdown
- Device model: Samsung A52s
- CPU architecture: Don't know, you can find on google
- Android version: Latest
- PojavLauncher version: Latest from Google Play
```

### Anything else?

Please help me fast!!!

**Comment by GaucovyAero** [comment]
try using a different network (e. g. mobile data), if that doesnt work, send the log

**Comment by Koala555Koala** [comment]
I tried using different network and doesn't worked, now I will edit and put the log

**Comment by Koala555Koala** [comment]
I put the log in the comment with the problem, so you can remove the "no_log" tag too

**Comment by GaucovyAero** [comment]
nothing out of the ordinary really, this issue is probably not related to pojav, try searching on the internet to see what to do

**Comment by Koala555Koala** [comment]
I searched and all things are like "dezactivate the firewall" or only windows related stuff. How can I do that on phone?....Pls help me

**Comment by GaucovyAero** [comment]
> I searched and all things are like "dezactivate the firewall" or only windows related stuff. How can I do that on phone?....Pls help me

i have absolutely no idea and ive never had to do anything like that

**Comment by Koala555Koala** [comment]
Me neither, that's why I asked here, I thought at least one person would know what to do

**Comment by GaucovyAero** [comment]
> Me neither, that's why I asked here, I thought at least one person would know what to do

maybe but definitely not me
