### ISSUE TITLE
[BUG] crash trying to launch a modpack profile

### ISSUE THREAD

**Issue by Jmbrand395** [PojavLauncherTeam/PojavLauncher#5022]
### Describe the bug

The game crashes when I tried to load a modpack profile named "Forever Stranded"
My device information:
Device Manufacturer Xiaomi
Device Name         violet
Device Model        Redmi_Note_7_Pro
Device Brand        Xiaomi
Android Version     13
CPU Arch            aarch64
Storage Total       50.49GB
Storage Free        17.58GB
RAM Total           5.48GB
Is Device Rooted    false

Latestlog.txt:
--------- beginning with launcher debug
Info: Launcher version: edelweiss-20240105-9a83875-feat/profile_icon_customization
Info: Architecture: arm64
Info: Device model: Xiaomi Redmi Note 7 Pro
Info: API version: 33
Info: Selected Minecraft version: 1.10.2-forge1.10.2-12.18.3.2511
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=1808
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_BIG_CORE_AFFINITY=1
Added custom env: POJAV_NATIVEDIR=/data/app/~~E-piA1uYPwWzPotYG35whA==/net.kdt.pojavlaunch.debug-WNC_XckebSvJL1tQTZ_IpA==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LIBGL_VGPU_DUMP=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~E-piA1uYPwWzPotYG35whA==/net.kdt.pojavlaunch.debug-WNC_XckebSvJL1tQTZ_IpA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=864
--------- beginning of main
I/jrelog  (13397): dlopen libOSMesa.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (13397): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libinstrument.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libzip.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjimage.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjavajpeg.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/librmi.so success
I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (13397): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (13397): dlopen /data/app/~~E-piA1uYPwWzPotYG35whA==/net.kdt.pojavlaunch.debug-WNC_XckebSvJL1tQTZ_IpA==/lib/arm64/libopenal.so success

I/jrelog  (13397): Done processing args
I/jrelog  (13397): Found JLI lib
I/jrelog  (13397): Calling JLI_Launch

Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java Exit code: 1
I/jrelog  (13397): Going to free args
I/jrelog  (13397): Free done

### The log file and images/videos

![Screenshot_20240107-123211_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/81294872/97aebcaf-644c-483d-9e11-8d0e2ccdc205)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Create a modpack profile of Forever Stranded modpack
3. Select renderer as Zink Vulkan
4. Click Play button
```

### Expected Behavior

I expected for the game to launch and play properly without any errors or crashes. 

### Platform

```markdown
- Device model: Redmi Note 7 Pro
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: Feat[cropper]: improve UI #4588
```

**Comment by GaucovyAero** [comment]
use java 8

**Comment by Jmbrand395** [comment]
> use java 8

Ok I will try and let you know if it's still crashing
