### ISSUE TITLE
LOGO BUG

### ISSUE THREAD

**Issue by padamchauhan** [PojavLauncherTeam/PojavLauncher#5025]
### Describe the bug

Version logo become large
![IMG_20240108_093534](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75151049/6aa2406a-738f-46f8-af07-16cc80af994f)

### The log file and images/videos

Nothing here

### Steps To Reproduce

```markdown
After clicking profile this occur
```

### Expected Behavior

Nothing serious 

### Platform

```markdown
- Device model: redmi note 7 pro
- CPU architecture: 
- Android version: 10
- PojavLauncher version: Improve ui one
```

### Anything else?

Nope
Hasta la vista , baby

**Comment by GaucovyAero** [comment]
known issue, keep in mind you are not using v3_openjdk, therefore not supported
