### ISSUE TITLE
[BUG] Game crashes when loading any modpack profile

### ISSUE THREAD

**Issue by Jmbrand395** [PojavLauncherTeam/PojavLauncher#5028]
### Describe the bug

My game crashes when I try to load a modpack profile

### The log file and images/videos

![Screenshot_20240108-133803_Pixel Launcher](https://github.com/PojavLauncherTeam/PojavLauncher/assets/81294872/48bdfaa9-f6e2-4225-879f-e24041a54375)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Click create new profile
3. Select modpack profile of any version of any modpack
4. Download everything
5. Click Play
```

### Expected Behavior

I expected the game to load and run smoothly

### Platform

```markdown
- Device model: Redmi Note 7 pro
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20240105-9a83875-feat profile_icon_customization
```

**Comment by GaucovyAero** [comment]
no log

**Comment by GaucovyAero** [comment]
it says authentication token invalid, most probably an issue unrelated to pojav

**Comment by Jmbrand395** [comment]
> no log

Oh sorry I forgot the log
