### ISSUE TITLE
There is no skins ui in PojavLauncher

### ISSUE THREAD

**Issue by JeromeJavier2007** [PojavLauncherTeam/PojavLauncher#503]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
~~It's on our TODO at the moment. It's currently impossible to change skin for offline account without mod/client/resourcepack modification. For paid accounts go to https://minecraft.net to.~~ idk

**Comment by Mathias-Boulay** [comment]
The dev team decided that it won't be on their roadmap, since the official website exists for that.
Closing the issue.

**Comment by Lolplays112** [comment]
SKINNNNNNNNNNNNNNNNNN

**Comment by OBITOGGFF22** [comment]
![SKIN_20240821_181349_514](https://github.com/user-attachments/assets/9a98e408-e1e7-496d-a806-04ee0d9c321a)
