### ISSUE TITLE
[BUG] <problem with textures >

### ISSUE THREAD

**Issue by n111k111ta** [PojavLauncherTeam/PojavLauncher#5031]
### Describe the bug

sometimes when running some mods, a bug occurs with textures (like xray). Is it possible to somehow fix this? (photo for example, how the bug is visible) 

### The log file and images/videos

![Screenshot_20240108_231907_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/155998412/bafa0dd5-2367-4418-8e92-920516dd1ff0)

### Steps To Reproduce

```markdown
use some mods?
```

### Expected Behavior

repairing textures 

### Platform

```markdown
- Device model: Samsung galaxy s22 ultra
- CPU architecture: 
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
it can either be fixed by pressing F11, turning fullscreen off and on, turning fast render off and on (if you have optifine) or removing some mods, this is not a bug that can be easily fixed
