### ISSUE TITLE
hi my game is crashing while using the mod "axiom"

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#5032]
![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13864300/latestlog.txt)

**Comment by lost72738** [comment]
what?

**Comment by GaucovyAero** [comment]
it needs a library that pojav does not ship by default, fork pojav and add the feature yourself, please also consider making a plugin for pojav like the FFmpeg plugin that does a similar thing

**Comment by Faked4075** [comment]
> ему нужна библиотека, которая pojav не поставляется по умолчанию, разветвите pojav и добавьте эту функцию самостоятельно, пожалуйста, также рассмотрите возможность создания плагина для pojav, такого как плагин FFmpeg, который делает то же самое.

tell me what library this is

**Comment by RimakiTaema** [comment]
Imgui-Java (arm64)

**Comment by Cobble-MC** [comment]
How can we install please?

**Comment by RimakiTaema** [comment]
it's currently no way to compile in arm64

**Comment by Cobble-MC** [comment]
Zalith launcher da yapamaz mıyız imgui yi nasıl ekliyecez

**Comment by Cobble-MC** [comment]
Can't we do it in Zalith launcher? How can we add imgui?

**Comment by RimakiTaema** [comment]
> Can't we do it in Zalith launcher? How can we add imgui?

idk you can try find it
