### ISSUE TITLE
[BUG] Vulkan Renderer Mod for 1.20.4

### ISSUE THREAD

**Issue by Yusuf-Kerem** [PojavLauncherTeam/PojavLauncher#5034]
### Describe the bug

I want Vulkan Renderer Mod for 1.20.4

### The log file and images/videos

Not

### Steps To Reproduce

```markdown
Not
```

### Expected Behavior

Not

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Not

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
more info on the pojav discord
