### ISSUE TITLE
Bring back virgl render

### ISSUE THREAD

**Issue by Hacker979** [PojavLauncherTeam/PojavLauncher#5036]
### Is this request related to a bug?

The new zink render shows worse fps and picture, leave both renders. So that you can have a choice
![Screenshot_20240109-014147_PojavLauncher (Minecraft_ Java Edition для Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75617199/287428fd-68d7-4def-a0d1-2f2313f2c7f2)
![Screenshot_20240109-014338_PojavLauncher (Minecraft_ Java Edition для Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75617199/e8fa8cf1-64fd-4536-b72c-ba08d9e4dda7)
Zink shaders have black bars and picture quality has deteriorated along with FPS 

### Describe the request.

Bring back the virgl

**Comment by abhishekgi** [comment]
Yes , developers should leave both renderers . And I wanna know that why Zink is performing this bad and crashing too. Earlier Zink used to give peak 70 fps . The maximum I recorded is 77 fps there is YouTuber who has a good phone he used to get 100+ sometimes. But now Zink crashes too much and runs really slow , maximum 20 fps for me

**Comment by ghost** [comment]
Yes zink is not always very useful my fps normaly is 20 or 30 with bsl shader but after osmesa update my fps down in 3 or 2 please fix the osmesa

**Comment by GaucovyAero** [comment]
guys, if the answer is no on multiple issues, the answer is no, its very buggy on most versions
if you guys want virgl, maintain a fork of pojav yourself that has it

this fork currently has it but who knows for how long its going to stay maintained
https://github.com/SolDev69/PojavLauncher/actions
