### ISSUE TITLE
[BUG] Vulkan Mod Crashes

### ISSUE THREAD

**Issue by RimakiTaema** [PojavLauncherTeam/PojavLauncher#5037]
### Describe the bug

When i Launch An Game With Vulkan Mod Its Ded Or I Mean Crash

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/13881472/latest.log)

### Steps To Reproduce

```markdown
1. Open An Game With Vulkan Mods
2. Then Crash
```

### Expected Behavior

Expected To Make Mod Running Correctly Without Crashes

### Platform

```markdown
- Device model: Redmi Note 10
- CPU architecture: aarch64/arm64-v8a
- Android version: 12
- PojavLauncher version: edelweiss-20231219-594e4cb-rep/bytehook
```

### Anything else?

I Got Banned On Discord If Y'all Want To Join Discord To Download It I Can't Okay

(I Have Minecraft Java Account Now Tho)

**Comment by RimakiTaema** [comment]
Forgot Crash Logs :(

[crash-2024-01-10_06.28.14-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13881497/crash-2024-01-10_06.28.14-client.txt)

**Comment by GaucovyAero** [comment]
im pretty sure your redmi note 10 doesnt run android 7.1.2
for more support with vulkanmod, go to the pojavlauncher discord server, keep in mind your android 7 phone probably does not even support vulkan at all

**Comment by GaucovyAero** [comment]
btw wrong logs, send latestlog.txt next time (share log file button or /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt)

**Comment by RimakiTaema** [comment]
> im pretty sure your redmi note 10 doesnt run android 7.1.2 for more support with vulkanmod, go to the pojavlauncher discord server, keep in mind your android 7 phone probably does not even support vulkan at all

I'm using vmos to render replay so that why

**Comment by RimakiTaema** [comment]
i mean vmos apps

**Comment by RimakiTaema** [comment]
and lastest logs i just played an not current one and its overwritten btw
