### ISSUE TITLE
[F-REQ]Add the ability to force the choice of architecture in the settings

### ISSUE THREAD

**Issue by KostyanSigaev** [PojavLauncherTeam/PojavLauncher#504]
Many people may have a problem like mine. The essence of this problem is that the launcher does not see the real architecture, and therefore it does not work. Adding this item in the settings may help solve this problem.

**Comment by khanhduytran0** [comment]
There was already auto runtime installer, why stills this required?

**Comment by KostyanSigaev** [comment]
The problem is that even installed runtime requires installing runtime (mine is like that)

**Comment by khanhduytran0** [comment]
I believe it's a bug on Asus x86 firmware when it find ARM native libraries before find x86 one. Please try turn off ARM emulation (if can) then re-install app https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/430553955

**Comment by Mathias-Boulay** [comment]
newer versions properly detect the architecture of the device from asus zenfones.
However, since Gplay deals with who get which libs, we cannot guarantee google detects the correct architecture.
Closing since we can't do more.
