### ISSUE TITLE
[BUG] libjvm.so

### ISSUE THREAD

**Issue by TopPro104** [PojavLauncherTeam/PojavLauncher#5040]
### Describe the bug

Hello, in general, my problem is with the libjvm.so file, I downloaded the assembly from my PC to several mods, it started, not on the first try, but it still started, when I tried to log into the server the application crashed, I read the logs and realized that there was a problem with the libraries , I tried to delete the folder and thereby install them again, but now it doesn’t even open the game (if this is my mistake and I’m wrong about something, then forgive me) Phone: Poco f4 gt Android: 13 Dedicated RAM: 3500

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13892123/latestlog.txt)

### Steps To Reproduce

```markdown
Run this mod pack : https://drive.google.com/file/d/1UqQOOeO0cpAvEjVJloFGlmi9wvGFEvls/view?usp=sharing
```

### Expected Behavior

Running mods without bugs

### Platform

```markdown
- Device model: Poco f4 gt 8/128gb
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
```
I/jrelog  (19555): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (19555): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
```
this is an android 5 workaround, as you can see it said success
the issue is that you are missing forge libraries (it says invalid paths argument for the forge jar), try reinstalling forge, not a pojav issue
