### ISSUE TITLE
Loigtech G cloud 

### ISSUE THREAD

**Issue by FamBoy32** [PojavLauncherTeam/PojavLauncher#5041]
### Is this request related to a bug?

You should add a version of Logitech G Cloud 

### Describe the request.

The Logitech G cloud when I first open it up will detected my right joystick but it won't register inside of the game. I was wondering if you could add something to it so that the logitech g cloud gets all the features to play on Pojavlauncher.

**Comment by GaucovyAero** [comment]
update to the latest actions build (guide is on the wiki and create a new bug issue if the issue still occurs)
