### ISSUE TITLE
[BUG]  Vulkan Mod Broke After Reloaded

### ISSUE THREAD

**Issue by RimakiTaema** [PojavLauncherTeam/PojavLauncher#5044]
### Describe the bug

I Played An Vulkan mod (patched one) and i found something weird when i join an server with server resourcepack its broke an texture and all of blocks texture

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13902471/latestlog.txt)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/146542478/849c8028-cfb2-43ed-970d-ee236d0745c1

### Steps To Reproduce

```markdown
Start An Game With Vulkan Mod And Other Optimization Mods (No Sodium or Unsupported Mod There)

Join An Server With Server Resourcepack Requests

Then Its Broke
```

### Expected Behavior

I Expect To Game Run Correctly With Normally Texture

### Platform

```markdown
- Device model: Redmi Note 10
- CPU architecture: aarch64/arm64-v8a
- Android version: 12
- PojavLauncher version: edelweiss-20231219-594e4cb-rep/bytehook
```

**Comment by GaucovyAero** [comment]
the server resource pack is most probably not compatible with vulkanmod, because it most likely contains opengl shaders for some stuff on the server
