### ISSUE TITLE
Vulkan mod crashed

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5046]
### Describe the bug

Vulkan  mod crashed in my phone I'm using patched version of it

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13910932/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojav launcher
Run fabric loader with vulkan mod
Crashes
```

### Expected Behavior

I  expected to get more fps than sodium

### Platform

```markdown
- Device model: Poco C3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest on playstore
```

### Anything else?

Pls reply fast

**Comment by Dilen0001** [comment]
.

**Comment by Proaman7603** [comment]
> .

👌 ok

**Comment by GaucovyAero** [comment]
unfortunately this is an issue with your gpu being a powervr ge8320
