### ISSUE TITLE
[BUG] I was trying to play 1.8 forge

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5047]
### Describe the bug

When I clicked on play it crashed
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13919494/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13919500/latestlog.txt)

### Steps To Reproduce

```markdown
Start game
1.8
```

### Expected Behavior

It should start 

### Platform

```markdown
- Device model: Vivo y36
- CPU architecture: what's this
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
you have mods installed for different versions of mc
