### ISSUE TITLE
Crashes when opening  forge with a mod  in pojav. [BUG] <Short description>

### ISSUE THREAD

**Issue by Minecrafterian** [PojavLauncherTeam/PojavLauncher#5050]
### Describe the bug

distant horizons 1.20.2 mod in forge 1.20.2-forge-48.1.0.  any idea as to why the screen is glitching out when I tried to open forge?and why it crashes when I try to create a world or join one?

Renderer:Zink (vulkan) - (all versions,mid).

I tried holy GL4ES and ANGLE (vulkan) but both crashes when trying to just open forge.

This crash only happens if I add distant horizons forge 1.20.2 in the :internal storage=Android=pojav launcher=. Minecraft=mods. If i remove the distant horizons mod forge runs smoothly in  holy GL4ES .any idea as to why this is happening?

Device: Samsung A33  5G 6gb ram , Android 13.

Pojav launcher version is the latest one in Play Store right now.

GPU renderer mali g68
GPU vendor ARM
Samsung Exynos 1280 processor 

### The log file and images/videos

[crash-2024-01-13_01.38.49-server.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13924029/crash-2024-01-13_01.38.49-server.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher

Install forge in pojav launcher version 1.20.2-forge-48.1.0

Install distant horizons mod from curse forgot version 1.20.2 forge.

Add the distant horizons mod in 
Android
Data
Pojavlauncher
. Minecraft
Mods

And after that open pojavlauncher and play  forge ,if it is in renderer holy gl4es and angle vulkan it will simply crash when loading in forge mojang loading screen that has the red  colour background. But if you open it with renderer Zink vulkan the first time the mojang logo loading screen shows the screen will glitch from the red background colour to grey repeatedly flashing for a while then disappear,and after the loading screen finishes the game opens but when you try to create a new world or join one as same as 1.20.2 it crashes with the world creation in 0%.


If the distant horizons mod is removed from
Android
Data
Pojavlauncher
. Minecraft
Mods 
 
Or if it isn't even there ,forge runs Minecraft normally in pojavlauncher in holy gl4es. What is the problem here?
```

### Expected Behavior

Forge to work normally and the mod also to be work normally,when you try to create or join a world it doesn't crash pojavlauncher or when the app crashes before even the loading screen finishes 

### Platform

```markdown
- Device model: Android Samsung galaxy A33 5G 6gb ram 128rom
- CPU architecture: The performance of the Galaxy A33 5G is driven by Samsung's in-house Exynos 1280 chipset. Its octa-core CPU architecture consists of two Cortex-A78 (2.4GHz) and six Cortex-A55 (2.0GHz) cores
- Android version: Android 13
- PojavLauncher version: endelweiss something.. I will attach a pic of the pojav launcher version..
```

### Anything else?

Pojavlauncher version pic
![Screenshot_20240113_024601_Google Play Store](https://github.com/PojavLauncherTeam/PojavLauncher/assets/156471742/05f0aac5-f3f8-4dd1-a764-84b00abcebf2)

**Comment by GaucovyAero** [comment]
wrong log sent, you gotta send latestlog.txt (you can do that by clicking the share log file button) or /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

**Comment by Minecrafterian** [comment]
> wrong log sent, you gotta send latestlog.txt (you can do that by clicking the share log file button) or /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

[]![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13927453/latestlog.txt)

I think this is the one , please check

**Comment by GaucovyAero** [comment]
```
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~FBlNTXt83GIygtWxSqvbFA==/net.kdt.pojavlaunch-2efuZ9pIoYa4hpB_tkLHHw==/lib/arm64:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
```
we dont ship sql, hence why it will not work
