### ISSUE TITLE
[F-Req] Restore VGPU Renderer

### ISSUE THREAD

**Issue by JetId** [PojavLauncherTeam/PojavLauncher#5051]
### Describe the request.

Add Back the VGPU Renderer Because This Renderer I Think Is Stable On PowerVR GPUs And MediaTek Chipsets Than Holy GL4ES. Although There Are Some Bugs In The VGPU Renderer But This Is Very Helpful For Someone Using PowerVR GPU And MediaTek Chipset (Low Device). I've tried the VGPU renderer with "Vsync" and the results were 57-60FPS. I played 1-2 hours on version 1.12.2 - 1.16.5 and the results were extraordinary. But when I use Holy GL4ES, I get a slight decrease in FPS, which is around 48-52FPS.

**Comment by GaucovyAero** [comment]
no, make a fork of pojav that has it if you want
a currently maintained fork that has vgpu is https://github.com/SolDev69/PojavLauncher/actions
