### ISSUE TITLE
[F-Req] Adding Mods - Add a selection dialog in the launcher

### ISSUE THREAD

**Issue by jagprog5** [PojavLauncherTeam/PojavLauncher#5052]
How do I add mods to forge? I don't know how to get around android (11+)'s walled garden.

My understanding is that the launcher's data folder is restricted only for the launcher's use. So **I** can't move something into it. However, the **launcher** could move into this folder and expose this to a user via a file explorer dialog.

**Comment by GaucovyAero** [comment]
just install mixplorer/zarchiver file manager to get access
free download mixplorer 6.6x.x from mixplorer.com, the app on play store is the donation version
if you still have issues, find your stock files app in your settings (the default android one, not xiaomi or whatever) and click uninstall updates, then try going to the folder again with mix/zarchiver

**Comment by jagprog5** [comment]
> just install mixplorer/zarchiver file manager to get access free download mixplorer 6.6x.x from mixplorer.com, the app on play store is the donation version if you still have issues, find your stock files app in your settings (the default android one, not xiaomi or whatever) and click uninstall updates, then try going to the folder again with mix/zarchiver

Please reopen. Not even the default system app allows this due to new android permissions.

**Comment by artdeell** [comment]
It is the opposite of being simple to implement. Imprementing it would lead to s huge chain of feature requests which will end in us implementing a mod manager (hard) or an integrated file explorer (also hard)

**Comment by artdeell** [comment]
Also, PojavLauncher provides a Storage Access Framework storage provider for the game directory, so you should be able to use the system file explorer to navigate the minecraft directory.
![Screenshot_20240126-230915_Файлы](https://github.com/PojavLauncherTeam/PojavLauncher/assets/45949002/4b4f6268-2b46-42f5-b3e3-cb6ddfc9cf02)

**Comment by jagprog5** [comment]
The Storage Access Framework is exactly what I was looking for. Thanks for the explanation. 👍
