### ISSUE TITLE
wrong log sent, you gotta send latestlog.txt (you can do that by clicking the share log file button) or /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

### ISSUE THREAD

**Issue by Minecrafterian** [PojavLauncherTeam/PojavLauncher#5054]
wrong log sent, you gotta send latestlog.txt (you can do that by clicking the share log file button) or /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/5050#issuecomment-1890361364_

**Comment by GaucovyAero** [comment]
duplicate, answered in #5050
