### ISSUE TITLE
[F-Req] Update LWJGL To Version 3.3.3

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5055]
### Is this request related to a bug?

There isn't any

### Describe the request.

Please Update LWJGL To 3.3.3 In PojavLauncher

### Anything else?

Please Update LWJGL

**Comment by GaucovyAero** [comment]
minecraft isnt even using it yet lol

**Comment by Dilen0001** [comment]
Update LWJGL 3.3.2

**Comment by GaucovyAero** [comment]
> Update LWJGL 3.3.2

there is already an issue about it

**Comment by Dilen0001** [comment]
Please LWJGL to 3.3.2
