### ISSUE TITLE
[Question] How does pojavlauncher get desktop opengl 4.6 through ANGLE

### ISSUE THREAD

**Issue by kde-yyds** [PojavLauncherTeam/PojavLauncher#5056]
As far as i know, angle can only translate opengles to other api. does pojavlaubcher use another fork of angle which has opengl support?(if so, we will have another way to get desktop opengl in a gnu/linux chroot container since we already have turnip with dri3 support

**Comment by GaucovyAero** [comment]
angle only has opengl 3.2 core profile and nothing else, not even 2.1, etc.
the reason why you see 4.6.0 is because its spoofed so that some mods can work

**Comment by kde-yyds** [comment]
but why does support ANGLE has desktop opengl support? i can only run gles apps with  ANGLE's libEGL(i built one by myself, only vulkan backend enabled). what should i do to make it support opengl?
