### ISSUE TITLE
[BUG] Version Alpha c0.30_01c

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5057]
### Describe the bug

Minecraft Alpha Version Error Even If Pressing F11 Key

### The log file and images/videos

![Screenshot_20240114_112705](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/b8a21e86-5e40-4223-8683-5e5fb601cd11)
![Screenshot_20240114_112650](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/a939f42a-dd53-4a5d-b2c2-decc9a5cf098)

### Steps To Reproduce

```markdown
Install Versi Alpha c0.30_01c
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Edelweiss-20230828-9484d0c-v3_openjdk
```

### Anything else?

Please Fix the Bug

**Comment by GaucovyAero** [comment]
these versions dont have fullscreen mode, use zink and reduce your resolution scale
