### ISSUE TITLE
A Request

### ISSUE THREAD

**Issue by mchnjt** [PojavLauncherTeam/PojavLauncher#5059]
### Is this request related to a bug?

No. To be fact; here's the tldr: 
### Describe the request.

I've been thinking about continuing my work on the wiki; but concerning my accessibility to this matter, i simply think as if it's impossible. I do have GaucovyAero on my dms; getting him to look at PRs and discuss about improvements; but calling out the community alone to help in this matter looked like a treacherous task to me.

### Anything else?

If you'd still look up to my request; please unban my Discord account. Obviously no one would use out-of-date technology just for working together; and i was also surprised that even i've left the community for a long time; each of my new accounts would get auto-banned.
## I'm not trying to clear my name or my history on the community. 
**Again, i only did this request to reconvene my own rights as a contributor and maintainer of the wiki: having people to talk about ideas and collaborate on further improving it.**

**Comment by GaucovyAero** [comment]
absolutely no idea man

**Comment by GaucovyAero** [comment]
i got informed you gotta communicate with me individually ripooz
