### ISSUE TITLE
Cant join server in forge

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5060]
### Describe the bug

I can't join server in forge in 1.20.1 I'm using only create mod

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13932170/latestlog.txt)
![Screenshot_2024-01-14-21-19-02-698_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/151455750/06d7644e-3baa-4ca3-b22c-115bfdf236b3)

### Steps To Reproduce

```markdown
Start pojavlauncher
Launch forge with create mod 1.20.1
Cant join server
```

### Expected Behavior

I expected I can join servers

### Platform

```markdown
- Device model: Poco C3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest on playstore
```

### Anything else?

Pls reply fast

**Comment by myavkat** [comment]
Create mod is under the list of "may not work mods"

**Comment by GaucovyAero** [comment]
doesnt seem like a pojav issue
