### ISSUE TITLE
[BUG] <Cant Join Hopite>

### ISSUE THREAD

**Issue by JJoshua04** [PojavLauncherTeam/PojavLauncher#5061]
### Describe the bug

I Can't join Hoplite.gg on Android on a Samsung galaxy s21 ultra I have tried to download the server resource pack and tried to reinstall pojav on my phone (I am using the Google Play Store Build Currently Published).

https://github.com/PojavLauncherTeam/PojavLauncher/assets/43502535/d71cded3-6f79-4396-97d9-6a0ecfd12c9d

### The log file and images/videos

.

### Steps To Reproduce

```markdown
Run pojavlauncher 1.20.1 open multiplayer load hoplite.gg and it doesn't work on a s21 ultra it kicks me from server.
```

### Expected Behavior

I would've expected to run hoplite.

### Platform

```markdown
- Device model: s21 Ultra by samsung
- CPU architecture: 
- Android version: One ui 6.0 android 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Nope.

**Comment by JJoshua04** [comment]
Resource reload always fails I don't know why I downloaded the pack so.

**Comment by GaucovyAero** [comment]
gl4es is failing to convert the shaders the server is using to render some items
use a different renderer (you will get lower fps) or dont play on the server, or just dont use the server resource pack if you can do that
