### ISSUE TITLE
Rubidium crashed

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5063]
### Describe the bug

My rubidium mod crashed in holy rendrer 1.20.1 with create mod. I have installed the patch file in config but it crashes. And in angle rendrer the game launched but when joining world it crashes says " Saving world" And crashed

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13938181/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojav
Launch forge 1.20.1
Crashes
```

### Expected Behavior

Why

### Platform

```markdown
- Device model: Poco c3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest on playstore
```

### Anything else?

No

**Comment by lost72738** [comment]
Try Angle renderer. Cause it will playable but black world icon. Just like im using souls like armor reworked mod with rubidium

**Comment by lost72738** [comment]
I have no idea

**Comment by Proaman7603** [comment]
> I have no idea

So what to do now?

**Comment by GaucovyAero** [comment]
your version of rubidium is most probably higher than what the patcher supports unfortunately

**Comment by lost72738** [comment]
> your version of rubidium is most probably higher than what the patcher supports unfortunately

Like rubidium 6.5 only
