### ISSUE TITLE
[BUG] error code 1 in 1.20.1

### ISSUE THREAD

**Issue by Ivan26085** [PojavLauncherTeam/PojavLauncher#5064]
### Describe the bug

When I play forge Minecraft in the loading screen the error code 1 pops out. And I ignore it. But few minutes later it's still in the loading screen.
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13947013/latestlog.txt)
![Screenshot_20240115-230834](https://github.com/PojavLauncherTeam/PojavLauncher/assets/156776522/7212399a-cb40-40a3-a8ae-6942fc103bba)

### The log file and images/videos

![Screenshot_20240115-230834](https://github.com/PojavLauncherTeam/PojavLauncher/assets/156776522/2fe46522-330f-4050-9245-0017c91ebf6a)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. It's on forge 1.20.1
3. Java runtime is defult
4. Pres play
```

### Expected Behavior

Error code 1 exited pops out in the loading screen

### Platform

```markdown
- Device model: i don't know 
- CPU architecture: i don't know 
- Android version: realme c33 android 12
- PojavLauncher version: latest
```

### Anything else?

There's no any other context about the problem.

**Comment by GaucovyAero** [comment]
```
[15:36:13] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'citadel', Requested by: 'alexsmobs', Expected range: '[2.4.4,)', Actual version: '[MISSING]'
	Mod ID: 'puzzleslib', Requested by: 'mutantmonsters', Expected range: '[8.0.4,)', Actual version: '[MISSING]'
```
you have to install some mods

btw, its recommended to turn off earlyWindowControl in .minecraft/config/fml.toml for the game to not crash when you go out of the pojav window
