### ISSUE TITLE
[BUG] Forge 1.20.4 crashing at boot

### ISSUE THREAD

**Issue by pixelthrived** [PojavLauncherTeam/PojavLauncher#5066]
### Describe the bug

I tried installing Forge on Pojav Launcher. After booting up Minecraft, it crashes with code 1. I tried doing a Shared and Standalone installation, but it still crashes with the same errors.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13958945/latestlog.txt)
![Screenshot_20240117-072309](https://github.com/PojavLauncherTeam/PojavLauncher/assets/91941157/7f63dc03-ddd5-4a39-9c29-4fe9d1b33db3)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher.
2. Install Forge for 1.20.4.
3. Start it.
```

### Expected Behavior

Forge should've started without issue, and be perfectly fine.

### Platform

```markdown
- Device model: Moto G32 8GB RAM/256GB Storage
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by Vini182837** [comment]
The same thing happens to me
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14003292/latestlog.txt)

**Comment by Algiuxs** [comment]
Forge 1.20.4-49.0.3 works, but be sure to set the default java to jre 8, because the installer only works on jre 8, for the game you need jre 17.

**Comment by Algiuxs** [comment]
There is a release in pojavs actions, that release fixes the forge error, but you will need to reinstall forge.
