### ISSUE TITLE
[F-Req] Add this two options in PojavLauncher 

### ISSUE THREAD

**Issue by MDEmonY** [PojavLauncherTeam/PojavLauncher#5067]
### Is this request related to a bug?

No

### Describe the request.

i want to add two options 
![Screenshot_20240117-121021](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154258490/68dd47ea-da2d-47fb-b74d-7a59cdb7c44c)
![Screenshot_20240117-121021~2](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154258490/06128705-c9a9-4243-bd6f-f473b2193df4)

**Comment by alexytomi** [comment]
Isn't this already a thing by default? We just call them profiles and custom .minecraft directory instead

**Comment by MDEmonY** [comment]
> Isn't this already a thing by default? We just call them profiles and custom .minecraft directory instead

yeah it's available but not automatic.

**Comment by alexytomi** [comment]
> > Isn't this already a thing by default? We just call them profiles and custom .minecraft directory instead
> 
> yeah it's available but not automatic.

No? 
When installing modpacks we also set a custom .minecraft directory automatically.
It's not automatic when you manually make the profile, that's on purpose.
