### ISSUE TITLE
Optifine crashing on 1.12.2.

### ISSUE THREAD

**Issue by GhetoKeto** [PojavLauncherTeam/PojavLauncher#5068]
### Describe the bug

Putting in Optifine immediately crashes the game on start-up.
Keep getting the crash report saying it's about window opening, otherwise i don't know what it's referring to.
(removing optifine makes the game run.)

### The log file and images/videos

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.8.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.2.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 1/13/24 2:31 PM
Description: Initializing game

java.lang.IllegalArgumentException: No window pointer found: 530274887168
	at org.lwjgl.glfw.GLFW.internalGetWindow(GLFW.java:649)
	at org.lwjgl.glfw.GLFW.glfwSetWindowSize(GLFW.java:1039)
	at org.lwjgl.opengl.Display.setDisplayMode(Display.java:858)
	at Config.checkDisplaySettings(Config.java:2512)
	at Config.initDisplay(Config.java:225)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:128)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:459)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.internalGetWindow(GLFW.java:649)
	at org.lwjgl.glfw.GLFW.glfwSetWindowSize(GLFW.java:1039)
	at org.lwjgl.opengl.Display.setDisplayMode(Display.java:858)
	at Config.checkDisplaySettings(Config.java:2512)
	at Config.initDisplay(Config.java:225)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:128)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:459)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0_392-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2215552632 bytes (2112 MB) / 2361917440 bytes (2252 MB) up to 2361917440 bytes (2252 MB)
	JVM Flags: 3 total; -Xms2350M -Xmx2350M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.8.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
	Launched Version: 1.12.2
	LWJGL: 3.3.1 SNAPSHOT
	OpenGL: Mali-G72 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: fabric
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 2
	Multitexture: true
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: Mali-G72
	OpenGlVendor: PojavLauncherTeam & ptitSeb
	CpuCount: 8

### Steps To Reproduce

```markdown
1. Start Pojav Launcher.
2. Start up the game.
3. The game loads, but still a blackscreen. (it's just loading in.)
4. The game exits with the code 1.
```

### Expected Behavior

Atleast enter the main menu.

### Platform

```markdown
- Device model: Samsung Note 9.
- CPU architecture: Arm64
- Android version: 10
- PojavLauncher version: using the version with in-built modpack installer thingy. Don't remember.
```

**Comment by lost72738** [comment]
My phone looks fine than yours.

**Comment by MDEmonY** [comment]
> ### Describe the bug
> Putting in Optifine immediately crashes the game on start-up. Keep getting the crash report saying it's about window opening, otherwise i don't know what it's referring to. (removing optifine makes the game run.)
> 
> ### The log file and images/videos
> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present: llibrary (llibrary-core-1.0.11-1.12.2.jar) AstralCore (astralsorcery-1.12.2-1.10.27.jar) SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.8.jar) MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.2.jar) SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar) IvToolkit (IvToolkit-1.3.3-1.12.jar) Contact their authors BEFORE contacting forge
> 
> // You should try our sister game, Minceraft!
> 
> Time: 1/13/24 2:31 PM Description: Initializing game
> 
> java.lang.IllegalArgumentException: No window pointer found: 530274887168 at org.lwjgl.glfw.GLFW.internalGetWindow(GLFW.java:649) at org.lwjgl.glfw.GLFW.glfwSetWindowSize(GLFW.java:1039) at org.lwjgl.opengl.Display.setDisplayMode(Display.java:858) at Config.checkDisplaySettings(Config.java:2512) at Config.initDisplay(Config.java:225) at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:128) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:459) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- Head -- Thread: Client thread Stacktrace: at org.lwjgl.glfw.GLFW.internalGetWindow(GLFW.java:649) at org.lwjgl.glfw.GLFW.glfwSetWindowSize(GLFW.java:1039) at org.lwjgl.opengl.Display.setDisplayMode(Display.java:858) at Config.checkDisplaySettings(Config.java:2512) at Config.initDisplay(Config.java:225) at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:128) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:459)
> 
> -- Initialization -- Details: Stacktrace: at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details -- Details: Minecraft Version: 1.12.2 Operating System: Linux (aarch64) version Android-10 Java Version: 1.8.0_392-internal, Oracle Corporation Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 2215552632 bytes (2112 MB) / 2361917440 bytes (2252 MB) up to 2361917440 bytes (2252 MB) JVM Flags: 3 total; -Xms2350M -Xmx2350M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar) net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher AstralCore (astralsorcery-1.12.2-1.10.27.jar)
> 
> SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.8.jar)
> 
> MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.2.jar) micdoodle8.mods.miccore.MicdoodleTransformer SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
> 
> IvToolkit (IvToolkit-1.3.3-1.12.jar)
> 
> ```
> Launched Version: 1.12.2
> LWJGL: 3.3.1 SNAPSHOT
> OpenGL: Mali-G72 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
> GL Caps: 
> Using VBOs: Yes
> Is Modded: Definitely; Client brand changed to 'fml,forge'
> Type: Client (map_client.txt)
> Resource Packs: fabric
> Current Language: ~~ERROR~~ NullPointerException: null
> Profiler Position: N/A (disabled)
> CPU: <unknown>
> OptiFine Version: OptiFine_1.12.2_HD_U_G5
> OptiFine Build: 20210124-142939
> Render Distance Chunks: 5
> Mipmaps: 0
> Anisotropic Filtering: 1
> Antialiasing: 2
> Multitexture: true
> Shaders: null
> OpenGlVersion: 2.1 gl4es wrapper 1.1.5
> OpenGlRenderer: Mali-G72
> OpenGlVendor: PojavLauncherTeam & ptitSeb
> CpuCount: 8
> ```
> 
> ### Steps To Reproduce
> ```
> 1. Start Pojav Launcher.
> 2. Start up the game.
> 3. The game loads, but still a blackscreen. (it's just loading in.)
> 4. The game exits with the code 1.
> ```
> 
> ### Expected Behavior
> Atleast enter the main menu.
> 
> ### Platform
> ```
> - Device model: Samsung Note 9.
> - CPU architecture: Arm64
> - Android version: 10
> - PojavLauncher version: using the version with in-built modpack installer thingy. Don't remember.
> ```
> 
> ### Anything else?
> _No response_

delete everything from .minecraft folder without assets, libraries, versions and launcher profile. i also had this problem then i did it and it was fixed.

**Comment by MDEmonY** [comment]
but if you have mods, config or instance related folder or files then backup them and delete

**Comment by TomXD1234** [comment]
Go to Java tweaks and set jre 8 and try to install again

**Comment by GaucovyAero** [comment]
cannot reproduce, might be fixable by turning off the forge loading screen in .config/splash.properties
