### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Montivillon** [PojavLauncherTeam/PojavLauncher#5070]
### Is this request related to a bug?

No

### Describe the request.

Pojavlauncher on iOS does not have a joystick but only the android has. I want to add that since I am on iOS and I want to use the joystick.

### Anything else?

Just add it already

**Comment by lost72738** [comment]
I have android 13. What you get

**Comment by Montivillon** [comment]
I’m on iOS 17.2 and I’m not an android. But the thing is, my Pojav version is 2.2 deep slate and I tried to customize my controls but it doesn’t have the add a joystick button.

**Comment by Montivillon** [comment]
Pls tell me you can communicate with the Pojav team?

**Comment by alexytomi** [comment]
> ### Is this request related to a bug?
> 
> No
> ### Describe the request.
> 
> Pojavlauncher on iOS does not have a joystick but only the android has. I want to add that since I am on iOS and I want to use the joystick.
> ### Anything else?
> 
> Just add it already

iOS issues go on https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues

**Comment by alexytomi** [comment]
> I’m on iOS 17.2 and I’m not an android. But the thing is, my Pojav version is 2.2 deep slate and I tried to customize my controls but it doesn’t have the add a joystick button.

Use 3.0

**Comment by Montivillon** [comment]
Wait, does the 3.0 have the joystick? If it does, pls send me the link for the PojavLauncher ipa 3.0

**Comment by GaucovyAero** [comment]
> Wait, does the 3.0 have the joystick? If it does, pls send me the link for the PojavLauncher ipa 3.0

its in the actions tab, also, closing this as this is the android repository, go to PojavLauncherTeam/PojavLauncher_iOS

**Comment by Montivillon** [comment]
Bro, is it the net.kdt.pojavlauncher.ipa.zip? Or in the releases net.kdt.pojavlauncher-2.2.ipa?

**Comment by Montivillon** [comment]
Just send the link first long tap the link and copy it

**Comment by Montivillon** [comment]
WAIT I INSTALLED IT AND FINALLY I GOT JOYSTICK FOR DAYS HAHAHHAHAH

**Comment by Montivillon** [comment]
THANK U SO MUCH

**Comment by Ramlof** [comment]
Wait how u download the joystick I need help pls
