### ISSUE TITLE
[BUG] PojavLauncher crash

### ISSUE THREAD

**Issue by MDEmonY** [PojavLauncherTeam/PojavLauncher#5071]
### Describe the bug

i have launcher fabulously optimized 1.16.5 Minecraft version, it was launched without any problem but when i start a world then it crash. So can you help me to fix this problem?

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/13972587/latest.log)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Redmi A1+
- CPU architecture: 32 bit
- Android version: 12
- PojavLauncher version: lastest google play version.
```

### Anything else?

i need help please help me to fix it.

**Comment by lost72738** [comment]
Use 1.19.2 version. Oh also iris doesn't work because they won't change shader.

**Comment by MDEmonY** [comment]
> Use 1.19.2 version. Oh also iris doesn't work because they won't change shader.

but i want to play 1.16.5

**Comment by GaucovyAero** [comment]
use sodium 0.1.0 and disable fog occlusion and compact vertex format
