### ISSUE TITLE
[F-Req] Make on screen controls transparency solid at 100% and add size slider!

### ISSUE THREAD

**Issue by bxmpublishingonline** [PojavLauncherTeam/PojavLauncher#5073]
### Describe the request.

When using the on screen controls at 100% opacity, they are still very see through when really they should be solid. This makes it awkward to use when in dark areas and during the night. It would be useful to allow the user to select different colours which is something that will help those who struggle with seeing colour and be easier to see when in dark places. It might also be a good idea to add a slider for adjusting the size of the controls as it wasn't obvious that a tab shows when the button is selected. If it can be missed being seen it should either blink to show what is the current selection and in the sidebar a slider highlights to adjust the size.

Also add the joystick an option to be a floating joystick. Other than that I am impressed with what has been achieved here. Great work. Keep it up and who knows, you may be hired by Mojang as the Minecraft Java for Android/iOS Edition.

**Comment by GaucovyAero** [comment]
> When using the on screen controls at 100% opacity, they are still very see through when really they should be solid.

thats probably because the color you set on the controls is transparent

> It would be useful to allow the user to select different colours which is something that will help those who struggle with seeing colour and be easier to see when in dark places. 

this is already there

> It might also be a good idea to add a slider for adjusting the size of the controls 

if you can make a code solution that would still keep the launcher lightweight please submit a PR

> Also add the joystick an option to be a floating joystick. 

i guess you can rename the issue name to "Floating joystick", the other things wont be done

**Comment by GaucovyAero** [comment]
#5100
