### ISSUE TITLE
[BUG] <crash when launching>

### ISSUE THREAD

**Issue by Nekotaco** [PojavLauncherTeam/PojavLauncher#5074]
### Describe the bug

Crash pls help sir

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13989596/latestlog.txt)

### Steps To Reproduce

```markdown
Press launch and it crashed sar
```

### Expected Behavior

Crash sir

### Platform

```markdown
- Device model:oppo a3s
- CPU architecture: snapdragon
- Android version: 9
- PojavLauncher version: idk
```

### Anything else?

Sir pls halp

**Comment by GaucovyAero** [comment]
balls
