### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by froz-hue** [PojavLauncherTeam/PojavLauncher#5076]
### Describe the bug

I can't play minecraft 1.20.2 in sodium idk why it's not working when I try login in any server it crashes my game 

### The log file and images/videos

[sodiumpatcher-1.0.1-SNAPSHOT.jar.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/13996802/sodiumpatcher-1.0.1-SNAPSHOT.jar.zip)
Zolve

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

Idkk 

### Platform

```markdown
- Device model: TECNO SPARK 8C
- CPU architecture: 1.6Ghz octa core
- Android version: 11
- PojavLauncher version: 1.20.2
```

### Anything else?

![Screenshot_20240119-204917](https://github.com/PojavLauncherTeam/PojavLauncher/assets/157195171/74b4bd6a-b43b-4433-bd7a-cbe592ea3f94)
As u can see the problem pls solve this

**Comment by Dilen0001** [comment]
You Have To Use Zink Work Render

**Comment by lost72738** [comment]
> You Have To Use Zink Render For It To Work

Angle or zink

**Comment by froz-hue** [comment]
> > You Have To Use Zink Render For It To Work
> 
> Angle or zink

Bro look I play in Android in which Zink and angel both sux idk it lags too much idk what to do nothing is working

**Comment by GaucovyAero** [comment]
the patcher does not work on sodium 0.5.0+ and there is currently no patcher for the newer versions of sodium
