### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by froz-hue** [PojavLauncherTeam/PojavLauncher#5077]
### Describe the bug

no game sound bro }:

### The log file and images/videos

no game sound

### Steps To Reproduce

```markdown
no game sound
```

### Expected Behavior

idk wj=hta to do but the problem is no game sound

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

}:

**Comment by GaucovyAero** [comment]
not enough info, cannot reproduce
