### ISSUE TITLE
Forge crashing[BUG] <Short description>

### ISSUE THREAD

**Issue by Vini182837** [PojavLauncherTeam/PojavLauncher#5078]
### Describe the bug

When I was install forge, every time I ran Minecraft it gave me 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14002019/latestlog.txt)
an error code 1, I already tried with 1.12.2 but the problem persisted

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14002025/latestlog.txt)

### Steps To Reproduce

```markdown
1. Launch PojavLauncher 
2. Select Forge profile
3. Click play and a message will appear on the screen saying that the game/application has been closed
```

### Expected Behavior

I didn't expect this to happen 

### Platform

```markdown
- Device model: Xiaomi Redimi Note 9S Glacier White 128GB 6GB+2 RAM
- CPU architecture: 64 bits
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use java 8
