### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by matt995** [PojavLauncherTeam/PojavLauncher#508]
Make a ram allocation manual setting pojav. It thinks it is only able  allocate 800mb ,but i can allocate 2408mb of ram to pojav. Forge will like to crash with low ram allocation.

**Comment by WesleyVanNeck** [comment]
edit flag: xmx

**Comment by WesleyVanNeck** [comment]
basic java understanding woeuld go well

**Comment by matt995** [comment]
Ahh the arguments
