### ISSUE TITLE
Litematica gui  not opening

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5080]
### Describe the bug

I installed optifabric 1.20.1 and some mods with litematica but pressing m button the gui is not opening. I have tested with sodium also it is not working

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14003951/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher
Join world
Press m button
Gui not opening
```

### Expected Behavior

I have already told

### Platform

```markdown
- Device model: Poco C3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest on playstore
```

### Anything else?

Pls reply fast

**Comment by GaucovyAero** [comment]
you gotta use zink which your phone probably doesnt support
