### ISSUE TITLE
Please make a mod 

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5081]
### Is this request related to a bug?

Please make a mod for forge because optifine crash with forge 1.20.1 and rubidium also crashes with forge (I installed patch). I'm getting low fps  in forge so please make a performance mod

### Describe the request.

I want more fps

### Anything else?

No

**Comment by sa1672ndo** [comment]
If u want more fps, get a better phone or even better, a pc. 
U cant just create a mod that improves fps, u need an idea on HOW to make it increase fps and the skill to implement it. Most of the time u will need to pile up multiple methods just to make fps a little bit better, and at some point they will start to conflict with each other and cause a lot of problems which will take ages to fix.

**Comment by agent1243** [comment]
rubidium and embeddium are an example of mods that try to improve performance but don't achieve much, I recommend using optfine
