### ISSUE TITLE
Add new kd&m support

### ISSUE THREAD

**Issue by Jdvdhtdmxh** [PojavLauncherTeam/PojavLauncher#5088]
### Is this request related to a bug?

yes

### Describe the request.

New kd&m support

### Anything else?

Nope

**Comment by artdeell** [comment]
Would be good to know what "kd&m" is. Did you mean "keyboard and mouse"?

**Comment by Jdvdhtdmxh** [comment]
Yes

**Comment by Jdvdhtdmxh** [comment]
Yes because when i move my mouse and clicks it at the same time screen lags

**Comment by Jdvdhtdmxh** [comment]
I am playing fold craft for now

**Comment by GaucovyAero** [comment]
i opened #5099
