### ISSUE TITLE
Join in external Login Option

### ISSUE THREAD

**Issue by bswxz** [PojavLauncherTeam/PojavLauncher#5089]
### Describe the request.

An external login option can be added to the options for offline users and Microsoft accounts.

**Comment by VenomousSteam81** [comment]
this will not be added as far as im aware because if that gets added then we might get sued by microsoft

**Comment by bswxz** [comment]
Two suggestions1.The mouse style can be customized, and the mouse style of win11 is provided2.Preassembly Java17 This saves players from having to install it themselves.This message I will be in github Send it again.I can't speak English. I use translation software to reply. There may be some errors. Forgive me.
