### ISSUE TITLE
[BUG] <i can't login>

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#5090]
### Describe the bug

so, i'm trying to login an account and it gave me an error.

### The log file and images/videos

![Screenshot_20240124-203659](https://github.com/PojavLauncherTeam/PojavLauncher/assets/98971458/b7a01d22-d849-4699-827f-e635d7a6e06d)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Login an account (maybe only an issue for me)
```

### Expected Behavior

i expected for it to **let me in the account.**

### Platform

```markdown
- Device model: techno spark 8 pro
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: latest or smth idk, i'm lazy.
```

### Anything else?

no.

**Comment by artdeell** [comment]
![Screenshot_20240124-224130_Firefox](https://github.com/PojavLauncherTeam/PojavLauncher/assets/45949002/89232992-048c-404c-a4c4-8659bed44e2a)

**Comment by Marcosayfi** [comment]
> ![Screenshot_20240124-224130_Firefox](https://private-user-images.githubusercontent.com/45949002/299437884-89232992-048c-404c-a4c4-8659bed44e2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTc2MTQsIm5iZiI6MTcwNjE1NzMxNCwicGF0aCI6Ii80NTk0OTAwMi8yOTk0Mzc4ODQtODkyMzI5OTItMDQ4Yy00MDRjLWE0YzQtODY1OWJlZDQ0ZTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA0MzUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMzM3NjFkYTk2MTY0ODNkYThhNjc3ODI3MjA5ZTc4ZmU4M2ZiMmQzMjU2N2YxNjdhYjMyNzZlNDhmNWRiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0DGVilmaceq4GbQphDuUWio_QejRQcox8vx88suasM)

i got a different errorr.

**Comment by GaucovyAero** [comment]
> > ![Screenshot_20240124-224130_Firefox](https://private-user-images.githubusercontent.com/45949002/299437884-89232992-048c-404c-a4c4-8659bed44e2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTc2MTQsIm5iZiI6MTcwNjE1NzMxNCwicGF0aCI6Ii80NTk0OTAwMi8yOTk0Mzc4ODQtODkyMzI5OTItMDQ4Yy00MDRjLWE0YzQtODY1OWJlZDQ0ZTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA0MzUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMzM3NjFkYTk2MTY0ODNkYThhNjc3ODI3MjA5ZTc4ZmU4M2ZiMmQzMjU2N2YxNjdhYjMyNzZlNDhmNWRiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0DGVilmaceq4GbQphDuUWio_QejRQcox8vx88suasM)
> 
> i got a different errorr.

this image is not openable

**Comment by GaucovyAero** [comment]
try reinstalling
