### ISSUE TITLE
Increased the memory provided to Minecraft to 5000 + etc[F-Req] <Short description>

### ISSUE THREAD

**Issue by yffugfh** [PojavLauncherTeam/PojavLauncher#5091]
### Is this request related to a bug?

Increased the memory provided to Minecraft to 5000 + etc

### Describe the request.

Increased the memory provided to Minecraft to 5000 + etc

**Comment by Nekotaco** [comment]
Why?, whats the point?

**Comment by GaucovyAero** [comment]
phones that have that much memory can allocate that amount, im pretty sure you can allocate around 14GB if you have a 18GB phone
