### ISSUE TITLE
[question] <Short description>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5092]
### Is this request related to a bug?

Actaully yes

### Describe the request.

My phone vulkan version is 1.1
![Screenshot_۲۰۲۴-۰۱-۲۵-۱۰-۵۹-۲۸-۱۹۷_ru andr7e deviceinfohw-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/30ee7bc3-8b14-452a-9695-8a44fba30c5e)
But minecraft writes is 1.3

It is normal? My mesa version is 23.2.0 
I test shaders like bsl in optifine is getting lagy but in iris is finely working . is problem is for optifine or my mesa version (after osmesa update optifine is getting the problem)
I think is my mesa version problem not in vulkan version but i can,t update mesa to 24.0.0
To fix optifine lag
### Anything else?

No

**Comment by ghost** [comment]
![IMG_۲۰۲۴۰۱۲۵_۱۲۰۶۳۸](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/d1ab75f5-19b5-4b59-8dbc-cee1ee9bbce5)

**Comment by Bel69420** [comment]
Well, if you're using zink renderer with Adreno, it will use Turnip (Vulkan 1.3 driver) instead of Adreno Driver as Adreno driver is broken

**Comment by Bel69420** [comment]
Don't even try to use Zink with adreno driver otherwise it will crash

**Comment by Bel69420** [comment]
Plus, Turnip driver is slower than native driver so that's normal, updating mesa to 24.0.0 might fucked up the performance so i'm not recommend you to update mesa but anyway you can do it if you really want to update it.

**Comment by ghost** [comment]
You right

**Comment by kasrarouhi** [comment]
![Screenshot_۲۰۲۴-۰۱-۲۶-۱۸-۰۵-۲۳-۷۴۸_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/df210552-aed5-40b1-a4b8-9f56ede95738)
In newer version of osmesa
![Screenshot_۲۰۲۴-۰۱-۲۶-۱۸-۱۰-۴۹-۲۲۳_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/f981a890-e3f9-4e78-85b4-90c76d4d1382)
In older version of osmesa(in turnip update

**Comment by ghost** [comment]
![IMG_۲۰۲۴۰۱۲۶_۱۸۱۷۵۹](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/44f88995-d133-462c-9048-e5d78b8bf7da)
In newer cersion of pojav launcher
![Screenshot_۲۰۲۴-۰۱-۲۶-۱۸-۰۵-۲۳-۷۴۸_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/58b099b1-a8be-4e23-8eb3-465ed5985e27)
In older version of pojav launcher turnip update
With same setting

**Comment by ghost** [comment]
Please bring back old mesa version for better perfomance

**Comment by GaucovyAero** [comment]
> Please bring back old mesa version for better perfomance

on other gpus its the other way around, i think we gotta wait for mesa 24 stable

**Comment by ghost** [comment]
Mesa 24.0.0 is relased . And i don,t think updating mesa help to perfomance

**Comment by Bel69420** [comment]
Mesa 24 isn't stable

**Comment by ghost** [comment]
Correct . Is very near to relasing is in pre relase version like 24.0.0-rc3 . Why i thinking is relased
