### ISSUE TITLE
Black screen problem ( in v.1.20.1 sodium)

### ISSUE THREAD

**Issue by PSgamer20x** [PojavLauncherTeam/PojavLauncher#5093]
### Describe the bug

I am using sodium from 3-4 months I have didn't face this type of problem :

When I open game using sodium (mods)
I face black screen problem [logs]

As you can see in last (fabric-loader 1.15.6 ?)
I don't know what it means tell me how to fix it ?

![Screenshot_2024-01-25-13-59-44-372_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/6c0734ad-db73-419a-bcc8-c801fcc28426)

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14049017/latest.log)

### Steps To Reproduce

```markdown
Start pojavluncher and Waite some time for load and stuck in black screen loop
```

### Expected Behavior

.

### Platform

```markdown
- Device model: poco M4 pro 5g
- CPU architecture: 
- Android version: 13
- PojavLauncher version: 1.20.1
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
try fabric loader 0.14.x

**Comment by PSgamer20x** [comment]
> try fabric loader 0.14.x

I am confused that day that's why I reistalled the game and now it's running good but when I uploaded mods as usual ,I saw this warning , if there is any way to fix it ? Then tellme
And also I am unable to open any world or server when ever I try to join any server / world my game crashes (while using mods) I usually uses sodium , exodium , sodium extra & etc...

Warning :-
![Screenshot_2024-01-27-20-17-32-532_net.kdt.pojavlaunch.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/66a6d92b-dfbc-42ea-8c53-8297ffe0e463)

Game Crash :-
![Screenshot_2024-01-28-12-57-32-364_net.kdt.pojavlaunch.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/149081943/1240b9e1-5f0e-4cb1-9d05-a7c4275bddec)
