### ISSUE TITLE
[F-Req] set coustom mouse key

### ISSUE THREAD

**Issue by PSgamer20x** [PojavLauncherTeam/PojavLauncher#5094]
### Is this request related to a bug?

I have one gaming mouse but I can't add custom key for better experience while playing with keyboard mouse 

I have tried in-game settings not working unable to set

### Describe the request.

I have allready created bug req you can also see that to know nicely

https://github.com/PojavLauncherTeam/PojavLauncher/issues/4906#issue-2016212693

**Comment by GaucovyAero** [comment]
i dont remember the reason but i know this isnt possible, might be because different manufacturers' android flavors treat the other keys differently or something like that, but there is a high chance that im wrong

**Comment by PSgamer20x** [comment]
> i dont remember the reason but i know this isnt possible, might be because different manufacturers' android flavors treat the other keys differently or something like that, but there is a high chance that im wrong

Yeah that's a feature in Minecraft real Java edition able to add coustom key which is common but in pojav launcher I am unable to set it So I want that feature in pojav launcher in next update 🥹 please add it

**Comment by PSgamer20x** [comment]
@GaucovyAero ...
