### ISSUE TITLE
[BUG] when i play forge 1.12.2 and "Game exited with code 1"

### ISSUE THREAD

**Issue by SeeDX176** [PojavLauncherTeam/PojavLauncher#5095]
### Describe the bug

![1EEF0C95-9CDC-4F22-9E97-5B17DAC0243B](https://github.com/PojavLauncherTeam/PojavLauncher/assets/127076873/02ab28a4-2903-46fd-9028-b531d1af1d07)

### The log file and images/videos

With trollstore i get pojavlauncher
When i download forge 1.12.2 .jar and start it ,what I get back is as above.I play the official versions and it's still normal. i need help

### Steps To Reproduce

```markdown
When i play pojavlauncher All other game versions work normally including optifine but when i download forge 1.12.2 and even older and newer versions the same error as above occurs.
```

### Expected Behavior

I need help.because I'm really looking forward to playing modpacks on forge

### Platform

```markdown
- Device model: iphone xsmax
- CPU architecture: apple a12
- iphone version: 16.2
- PojavLauncher version: 2.1
```

### Anything else?

I don't have.

**Comment by GaucovyAero** [comment]
this is the android repository, go to PojavLauncherTeam/PojavLauncher_iOS
