### ISSUE TITLE
Hud flickering fabric

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5098]
### Describe the bug

My inventory and hud is flickering in 1.19.2 fabric  with sodium

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14071830/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher
Load world
Inventory flickering
```

### Expected Behavior

Why

### Platform

```markdown
- Device model: poco c3
- CPU architecture: 32 bit
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

I know my gpu has broken driver but is there a solution. Pls solve it

**Comment by GaucovyAero** [comment]
there will likely be no solution, since this only happens on your gpu and it isnt a priority to fix at all
