### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by RuMir694** [PojavLauncherTeam/PojavLauncher#51]
Things are not taken from inventory(android 10)-(1.7.10)

**Comment by khanhduytran0** [comment]
Disable touchscreen mode

**Comment by khanhduytran0** [comment]
Minecraft Settings -> Controls -> Touchscreen Mode, toggle to OFF

**Comment by RuMir694** [comment]
Thanks men!!!if I can then throw donat!!,

**Comment by RuMir694** [comment]
Thanks
