### ISSUE TITLE
Mouse scroll not works

### ISSUE THREAD

**Issue by JeromeJavier2007** [PojavLauncherTeam/PojavLauncher#510]
The mouse scrolling is not working

**Comment by khanhduytran0** [comment]
Direct scroll by swipe! Other methods may not work.

**Comment by tttghkg** [comment]
@khanhduytran0 How to slide in the game. I'm just not in gui

**Comment by T-CATHOME** [comment]
@khanhduytran0 How to slide in the game? I mean, not in gui

**Comment by khanhduytran0** [comment]
Why? A mod requires it?

**Comment by T-CATHOME** [comment]
@khanhduytran0 Yes, the Create mod is almost unusable without a mouse wheel

**Comment by khanhduytran0** [comment]
> Direct scroll by swipe! Other methods may not work.
