### ISSUE TITLE
[BUG] <Can't allocate ram more than 1024 mb even though I have more free ram.>

### ISSUE THREAD

**Issue by ShoyebOP** [PojavLauncherTeam/PojavLauncher#5101]
### Describe the bug

I have a Samsung j8 device which has 4 gb ram and it has more than 2.2 gb ram free all the time but the game doesn't allow me to increase the ram allocation more than 1024 mb even it allows me to increase it to 1024 mb it crashes immediately (*crash report is included*) after starting the game to play i had to decrease it to 800 mb.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14072270/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher.
2. Go to Java tweaks settings.
3. Allocate 1024 mb ram.
4. Select any game profile and hit play.
5. The game will crash.

*I don't think it can be reproduced without specific devices but I still included it*
```

### Expected Behavior

I have another device named OnePlus 5 where I can allocate ram up to 6840 mb (as it has 8 gb ram) even if I don't have that much ram free and if I attempt to play with that it gives me warning but still lets me play. But in Samsung j8 it crashes directly.

Now,
First of all it doesn't even allows me to allocate the full 2.2 gb free ram .

Secondly it even crashes if I give the max amount of allocated ram(1024 mb)

Thirdly it only allows me to play with 800 mb allocated ram which easily gets overloaded.

### Platform

```markdown
- Device model: 1samsung SM-J810G
- CPU architecture: arm
- Android version: 8
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

It was not like that before pojavlauncher was released on play store.

**Comment by artdeell** [comment]
This is due to the fact that there is a 4 GB address space limit on 32-bit versions of Android, which is likely what your Samsung Galaxy J8 has. Most of the address space is already taken up by the Android Runtime that runs the input, output and UI rendering tasks for PojavLauncher. The rest can be given to the Java Runtime that runs the actual game.

I want to fix this issue, but it occurs on very few devices. Can you get in contact with me on discord? My profile is [artdev](https://discord.com/users/438714312157298699). If it is more convenient, you can also contact me with telegram: [@artdeell](https://t.me/artdeell)

**Comment by ShoyebOP** [comment]
> This is due to the fact that there is a 4 GB address space limit on 32-bit versions of Android, which is likely what your Samsung Galaxy J8 has. Most of the address space is already taken up by the Android Runtime that runs the input, output and UI rendering tasks for PojavLauncher. The rest can be given to the Java Runtime that runs the actual game.
> 
> I want to fix this issue, but it occurs on very few devices. Can you get in contact with me on discord? My profile is [artdev](https://discord.com/users/438714312157298699). If it is more convenient, you can also contact me with telegram: [@artdeell](https://t.me/artdeell)

I'm glad to hear that you want to fix this issue and I will try my best to help as much as I can. I have sent you a friend request on discord from this(shoyebop) account.
