### ISSUE TITLE
[BUG] Error Forge 1.20.4

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5102]
### Describe the bug

Forge Error In Play Game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14072421/latestlog.txt)

### Steps To Reproduce

```markdown
Install Forge 1.20.4
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Please Fix The Bug

**Comment by GaucovyAero** [comment]
closing because title is not good enough
#5116 opened
