### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by hasangamse** [PojavLauncherTeam/PojavLauncher#5105]
### Describe the bug

OPTIFABRIC ISSUE 
![Screenshot_2024-01-28-14-18-41-47](https://github.com/PojavLauncherTeam/PojavLauncher/assets/157950732/f50957cc-8c3f-42cf-9f2a-20c3be4da106)

### The log file and images/videos

I

### Steps To Reproduce

```markdown
I
```

### Expected Behavior

<>

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
unrelated to pojav
