### ISSUE TITLE
Mouse and JAVA17

### ISSUE THREAD

**Issue by bswxz** [PojavLauncherTeam/PojavLauncher#5106]
### Is this request related to a bug?

Custom Mouse Style
Preassembly JAVA17

### Describe the request.

Two suggestions
1.The mouse style can be customized, and the mouse style of win11 is provided
2.Preassembly Java17 This saves players from having to install it themselves.
-------------------------------------
I can't speak English. I use translation software to reply. There may be some errors. Forgive me.
-------------------------------------
![IMG_20240128_201102](https://github.com/PojavLauncherTeam/PojavLauncher/assets/129058318/71968420-93b0-49af-b5f6-9903f2535547)
![Screenshot_20240128_201024](https://github.com/PojavLauncherTeam/PojavLauncher/assets/129058318/6f3564bf-76d4-4ac8-91d1-157e73d7e0e0)

**Comment by artdeell** [comment]
Java 17 is preinstalled in the launcher,mit's unpacked automatically if you dpn't already have a compatible java version already installed (in this case, you already have java 21)

**Comment by GaucovyAero** [comment]
closing, the custom mouse cursor probably wont be done
