### ISSUE TITLE
[F-Req] Movable settings button

### ISSUE THREAD

**Issue by n00b69** [PojavLauncherTeam/PojavLauncher#5108]
### Is this request related to a bug?

On MIUI it is impossible to use the settings button, due to it instantly opening the QS panel instead, making it impossible to save controls

### Describe the request.

Move the settings button someplace else (not on the top of the screen) and make it movable.

Or, make the back button behave like the settings button.

**Comment by GaucovyAero** [comment]
create a SPECIAL_MENU button in your controlmap, you can reposition it where you want and the cogwheel button is going to automatically disappear
