### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Weqrus** [PojavLauncherTeam/PojavLauncher#5109]
### Describe the bug

First, when I'm trying to load and make a new world, it sticks to 0% and crashes the game, but when I'm working on servers, it works. The second is when I'm joining a server, and when I stay longer, the game crashes for like 10–15 minutes with no lag. (Correct me if this is not a bug.) i'm using optifine ans version 1.20.4

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14078783/latestlog.txt)
![S40129-095115](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158004747/d3d0c3d2-1fe7-45c9-aaf4-2044e81f531b)

### Steps To Reproduce

```markdown
I don't have idea
```

### Expected Behavior

I expect fix the loading screen and no crashes when joining in my world/server

### Platform

```markdown
- Device model: MEIZU M6
- CPU architecture: 8 cores; AArch64 Processor rev 2 (aarch64) mt6750; Max: 1001,0 MHz; Min: 156,0 MHz
- Android version: 7
- PojavLauncher version: edelwesis-20230928-9484d0cv3_openjdk
```

### Anything else?

Nothing else

**Comment by GaucovyAero** [comment]
honestly i have absolutely no idea how can you expect your phone to run vanilla 1.20.4 fine without any big optimizations on a phone that has an soc comparable to a 17 year old core 2 duo e4300 and you also only have 2/3gb ram.

get pojavoptimize from the pojav discord

also, i suggest you remove your jvm arguments, as they might be causing the issue
