### ISSUE TITLE
[BUG]3D clouds rendering improperly

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#511]
**Describe the bug**
3d clouds not displayed correctly

**Screenshots**
![Screenshot_2020-12-18-12-57-55-141_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/75588714/102607384-e1f38280-4130-11eb-96f0-ba1b7b889a46.jpg)
**Platform:**
 - Device Model [redmi note 8 pro 6/64]
 - CPU architecture [aarch64] 
 - Android Version [10]

**Comment by khanhduytran0** [comment]
Known issue on GL4ES 1.1.4.

**Comment by khanhduytran0** [comment]
Switch to GL4ES 1.1.5 fixes problem, but rendering will be buggy on 1.14.4 and below.
Add `-Dorg.lwjgl.opengl.libname=libgl4es_115.so` to JVM arguments to use GL4ES 1.1.5

**Comment by ghost** [comment]
> Switch to GL4ES 1.1.5 fixes problem, but rendering will be buggy on 1.14.4 and below.
> Add `-Dorg.lwjgl.opengl.libname=libgl4es_115.so` to JVM arguments to use GL4ES 1.1.5

![Screenshot_2020-12-18-22-48-42-363_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/75588714/102660136-36275280-4183-11eb-94bd-5ca83d5a8253.jpg) sheep color and - grass in hand fixed render stable on 1.16.4 cloud not fixed, many graphical errors were fixed, FPS and render dont changed, i use 2d clouds before fix

**Comment by ghost** [comment]
i think need use 1.1.5 is fixes many graphical bugs

**Comment by ghost** [comment]
I researched the world a lot, there are no new bugs and many are fixed

**Comment by jumperli** [comment]
Guys, whats the difference between 
-Dorg.lwjgl.opengl.libname=libgl4es_115.so 
And
-Dorg.lwjgl.opengl.libname=libOSMesa_8.so

And which one of them should i use, i have 6gb ram phone :)

**Comment by WesleyVanNeck** [comment]
> Guys, whats the difference between
> -Dorg.lwjgl.opengl.libname=libgl4es_115.so
> And
> -Dorg.lwjgl.opengl.libname=libOSMesa_8.so
> 
> And which one of them should i use, i have 6gb ram phone :)

liosmesa is fors zink

**Comment by Mathias-Boulay** [comment]
Since the latest gplay update, a renderer option exists.
Closing.
