### ISSUE TITLE
[F-Req] Can you add a custom skin?

### ISSUE THREAD

**Issue by TopedGames** [PojavLauncherTeam/PojavLauncher#5110]
### Is this request related to a bug?

Russian: В Pojavlauncher много игроков и много видео роликов на просторах youtube, и большинство бы хотело иметь свой скин, возможно ли нам предоставить такую возможность?
English: There are a lot of players in Pojavlauncher and a lot of videos on youtube, and most would like to have their own skin, is it possible for us to provide such an opportunity?

### Describe the request.

Russian: Я бы хотел чтобы каждый мог иметь свой пользовательский скин как в Fold Craft Launcher или как в Hello Launcher.
English: I would like everyone to be able to have their own custom skin like in Fold Craft Launcher or like in Hello Launcher.
![Screenshot_2024-01-29-10-35-30-63_c8a66bc90793a73eafa5773962b202df](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150599356/131f18cb-d71c-4552-a9b6-4ec4ebaee5e5)
![Screenshot_2024-01-29-10-35-40-36_c8a66bc90793a73eafa5773962b202df](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150599356/6bb3c747-a18e-433c-b054-dac19b5a7610)
![Screenshot_2024-01-29-10-40-41-91_d17cc25ab2657fbd260b0454040eb4aa](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150599356/2b21ecdb-0b41-487b-ace5-98d44b783a9a)
![Screenshot_2024-01-29-10-40-30-37_d17cc25ab2657fbd260b0454040eb4aa](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150599356/d913a746-677f-470e-b970-c93576ba4cb9)

**Comment by lost72738** [comment]
Use offline skins mod. Needed modded Minecraft like forge and fabric
