### ISSUE TITLE
Forge 49.0.x (Minecraft 1.20.4) crashes on launch with no mods installed

### ISSUE THREAD

**Issue by GaucovyAero** [PojavLauncherTeam/PojavLauncher#5116]
### Describe the bug

self-explanatory

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14103288/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install the latest version of Forge for 1.20.4 and launch.
```

### Expected Behavior

I expect the game to not crash.

### Platform

```markdown
- Device model: Xiaomi Poco F3 8/256GB
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20240122-693f90b-v3_openjdk (debug)
```

### Anything else?

nope

**Comment by Dilen0001** [comment]
Plis Fix Bug Forge 1.20.4
