### ISSUE TITLE
[BUG] Item dropping bug

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5117]
### Describe the bug

There is this bug that sometimes appears when i tap on my inventory slot to switch item sometime it would drop the item non stop until i click on it to stop it, which is bad what if i wanted to switch between my diamond sword to pickaxe and then i will drop the pickaxe

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158475307/67a58297-bf89-427d-a3ba-ac77af1ecf6f)

### The log file and images/videos

Dont got it

### Steps To Reproduce

```markdown
1. Switch item
2. Drops item (i did not hold it for a long time)
3. Taps on the slot to stop it
```

### Expected Behavior

I expected it NOT to drop the item when i switched to it

### Platform

```markdown
- Device model: Galaxy A31
- CPU architecture: MediaTek Helio P65
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
duplicate issue (see stuck keys issue)
