### ISSUE TITLE
[BUG] Can't change control map midgame

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5118]
### Describe the bug

Everytime i try to change it it wont work

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Launch pojavlauncher
2. Custom controls
3. Select default controlmap
4. Leave editor
```

### Expected Behavior

I expected it to change the controlmap when i leave the editor but it didnt

### Platform

```markdown
- Device model: galaxy a31
- CPU architecture: MediaTek Helio P65
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Proaman7603** [comment]
Bro
Select default controlmap
Choose the controls
Click save
Then save and quit



Don't click leave the editor

**Comment by TotallyNotSaeed** [comment]
When i quit it just goes back to the previous one

I have to force close than change it from the pojavlauncher menu and then launch back up

**Comment by GaucovyAero** [comment]
you didnt select as default

**Comment by TotallyNotSaeed** [comment]
I did
