### ISSUE TITLE
Gun mods problem in 1.12.2

### ISSUE THREAD

**Issue by crazymobile** [PojavLauncherTeam/PojavLauncher#512]
I try to play gun mods but not firing only breaking block and try all gun mods pojavluncher all same problems in firing

**Comment by khanhduytran0** [comment]
You may try change mod keycode.

**Comment by crazymobile** [comment]
How?

**Comment by khanhduytran0** [comment]
Gp to Minecraft control settings. Find for shoot key.

**Comment by crazymobile** [comment]
There no firing setting there in modern warfare mod

**Comment by darkzero021** [comment]
Plss help how to fix not firing in any guns mod in Pojavluncher there is no firing setting in minecraft

**Comment by Mathias-Boulay** [comment]
This has been fixed on the google play version, closing issue.
