### ISSUE TITLE
[BUG] missing pixels in items

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5120]
### Describe the bug

The only solution is using zink but it causes lag is there any other way that i can get rid of this? This bug appears in 1.8 and disappears in 1.14 it looks worse using forge version some items have it some don't

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158475307/ae07bd66-75b6-4f3d-8a70-18444180ac2a)

### Steps To Reproduce

```markdown
1. Launch pojavlauncher
```

### Expected Behavior

No more missing pixels

### Platform

```markdown
- Device model: galaxy a31
- CPU architecture: MediaTek Helio P65
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
will be fixed when a new release of holy gl4es rolls out, wont be soon
