### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by nickname2712** [PojavLauncherTeam/PojavLauncher#5123]
### Describe the bug

Parece que você não tem uma conta Xbox Live. Por favor, faça login Em https://minecraft.net/ e tente novamente. (Mas eu já tenho conta nesse lugar)

### The log file and images/videos

.

### Steps To Reproduce

```markdown
Apenas colocar o email ou gmail, e falhar miseravelmente.
```

### Expected Behavior

Apenas logar.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Não

**Comment by nickname2712** [comment]
Help me, please

**Comment by GaucovyAero** [comment]
do what it tells you to do
