### ISSUE TITLE
[BUG] No IPv6 Support

### ISSUE THREAD

**Issue by Xinhe9** [PojavLauncherTeam/PojavLauncher#5126]
### Describe the bug

I can't use IPv6 address to connect my server normally. It works ow Windows 11 but can't work in Pojavlauncher. Please support it 
Thanks

### The log file and images/videos

![Screenshot_20240203_174327 (1)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/86970814/e641ddd8-ca6e-4a59-8603-333a572a9d7f)
![Screenshot_20240203_174419_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/86970814/4bba9d0c-0f6c-4e8b-a36c-6a89f88534ea)
![Screenshot_20240203_174438_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/86970814/00a091ca-93d4-4e06-b806-281f03816ab4)
![Screenshot_20240203_174440_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/86970814/d1372062-e5aa-4f4b-a247-f53aa5b24dec)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Start games
3. Multiplayer
4. Add server and the address is [address]:25565
5. Can't connect to server
```

### Expected Behavior

No

### Platform

```markdown
- Device model: 
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20240127-bb16bff-feat/profile_icon_customization
```

### Anything else?

Hope the Pojavlauncher can better and better!!

**Comment by Xinhe9** [comment]
Sorry, I submit 2 times

**Comment by JohnNyC13jonas** [comment]
How to make an Pojavlauncher account without teh X-Box game pass ???????????

**Comment by VenomousSteam81** [comment]
> How to make an Pojavlauncher account without teh X-Box game pass ???????????

no
