### ISSUE TITLE
[BUG] Can't find Java8.

### ISSUE THREAD

**Issue by ClosedSum664984** [PojavLauncherTeam/PojavLauncher#5127]
### Describe the bug

When installing the third-party client and it shows that it is"not found Java8".

### The log file and images/videos

![Screenshot_2024-02-03-19-06-13-96_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/147115470/ed18923d-d4e2-47ff-b423-bf4d4e00ea88)

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Click "Execute.jar"
```

### Expected Behavior

I want to be able to use other Java versions to make this work

### Platform

```markdown
- Device model: OPPO A2 Pro 12/256G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20240201-d060cbd-feat/profile icon customization
```

**Comment by GaucovyAero** [comment]
dont use noruntime builds
