### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#5128]
### Describe the bug

Crash on 1.7.10 not 1.12.2 +

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. Create world
3. loading shader
4. Crash
```

### Expected Behavior

Work on pojavlauncher 1.7.10

### Platform

```markdown
- Device model: redmi 9
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: Google play
```

### Anything else?

Working on 1.12.2+  but not on 1.7.10

**Comment by kedrick021** [comment]
Zink Vulcan Shader on 1.7.10 crash

**Comment by GaucovyAero** [comment]
invalid
