### ISSUE TITLE
[BUG]Mouse doesn't work

### ISSUE THREAD

**Issue by Dimon245** [PojavLauncherTeam/PojavLauncher#513]
**Describe the bug**
Mouse only works in GUI's, but not when you're actually playing, like you can't look around, nor can you use left or right click (for some reason right click is bound to "go back" a step as if I pressed the button on my screen. Also mouse3 is kind of the same, so these 2 buttons are unusable)

**To Reproduce**
1. Start PojavLauncher
2. Plug in a mouse
3. Join a world and try doing the above-mentioned

**Expected behavior**
I expected it to work kind of like on bedrock, where a mouse works, but looking around requires you to hold left click

**Screenshots**
No screenshots needed
**Platform:**
 - Samsung S20+ (SM-G985F/DS)
 - aarch64
 - Android 10

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
The mouse used is Microsoft BT Mouse 3600. I tried editing options.txt's height and width (like mentioned on some other issues), but they get automatically reset on launch every time.
</pre>
</details>

**Comment by matt995** [comment]
Yea that happens to me too.

**Comment by khanhduytran0** [comment]
> I expected it to work kind of like on bedrock, where a mouse works, but looking around requires you to hold left click

Make sure mouse pointer is hidden otherwise it would not work.

**Comment by Dimon245** [comment]
It is, I mean, I removed all the buttons (including mouse ON/OFF) so that it doesn't conflict with the keyboard pressing "space" and mouse left clicking. I think it's mostly because I can't change the resolution, it's set to 1461x720 (and I tried changing it, but no luck), when my phone's res is 1440x3200 according to Google

**Comment by khanhduytran0** [comment]
Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/433331905

**Comment by Dimon245** [comment]
Oh, thanks a lot. Now it works. I can look around now and use left click. But there are 2 bugs:
1. The mouse is inverted (temporary fix is to enable "invert mouse" in controls)
2. When you press left click, it gets stuck (kind of) and starts breaking blocks when you look at them (temporary fix is to keep pressing "home" button or mouse3 whenever that happens, but that's really annoying)

**Comment by Dimon245** [comment]
Also, about GUI related issues: shift-clicking (shift + left click) doesn't work. And left clicking in inventory/crafting grid doesn't split items by 2

**Comment by khanhduytran0** [comment]
> The mouse is inverted (temporary fix is to enable "invert mouse" in controls)

Does mouse inverted both X and Y?

**Comment by Dimon245** [comment]
I guess so, because if you use "Invert mouse" it fixes it completely.

**Comment by Dimon245** [comment]
update: In the latest build you can't use left click again :/ 
Had to revert back to this

> Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/433331905

**Comment by GoldenFurredFox** [comment]
Was able to reproduce the issue with BM30X Bluetooth Mouse and Logitech MK320 Wireless USB from 2014.

**Comment by ramazanhdmn** [comment]
I can't solve the problem please help

**Comment by AdamGnu** [comment]
I can't press the mouse and other buttons on the GUI when I use the fabric mod, but other mods like forge and optifine work fine.
