### ISSUE TITLE
Game crash wan i Start using project Ozone lite modpack 

### ISSUE THREAD

**Issue by Kishan000777** [PojavLauncherTeam/PojavLauncher#5130]
### Describe the bug

Game crash after some time my 
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14155840/latest.log)

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14155842/latest.log)

### Steps To Reproduce

```markdown
Automatic back to home screen
```

### Expected Behavior

Aa

### Platform

```markdown
- Device model: oppo f9 pro 6gb / 64 storage 
- CPU architecture: 64bit
- Android version: 10
- PojavLauncher version: latest on Google play store :- dahlia-20230813-5e8842b-v3_openjdk
```

### Anything else?

Game crash wan i start project Ozone lite modpack

**Comment by Kishan000777** [comment]
And you meed more info about game crashes

**Comment by GaucovyAero** [comment]
remove avaritia
