### ISSUE TITLE
[F-Req] 16:9 aspect ratio

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5131]
### Is this request related to a bug?

Nope

### Describe the request.

Add a switch that allows you to change the current aspect ratio of the phone to 16:9

**Comment by artdeell** [comment]
Why would you even need this

**Comment by TotallyNotSaeed** [comment]
I just prefer 16:9 and i want my yt vids to also be 16:9

**Comment by GaucovyAero** [comment]
duplicate issue
