### ISSUE TITLE
[question] Why Tools.APP_NAME is null?

### ISSUE THREAD

**Issue by zkitefly** [PojavLauncherTeam/PojavLauncher#5136]
https://github.com/PojavLauncherTeam/PojavLauncher/blob/88e003badb29bf0ac9dc6636bb26ed0f4fe47298/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/Tools.java#L97

I looked at the code here, why is APP_NAME null?

One more thing, what is the network request User-Agent for PojavLauncher?

Thanks for the reply.

**Comment by Mathias-Boulay** [comment]
The APP_NAME is set at runtime, although looking at the code, it seems pointless to do so.
