### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by Bobuxic** [PojavLauncherTeam/PojavLauncher#5139]
### Describe the bug

when i launch the minecraft everything is good but when i enter the world, if i open the inventroy or the menu it turns black screen and if i exit the inventory its all good again, it only happens when the mouse appears i think so, im using a chromebook maybe its the problem?

### The log file and images/videos

![Screenshot 2024-02-07 20 39 05](https://github.com/PojavLauncherTeam/PojavLauncher/assets/90838562/85567ab7-1ee6-4911-83db-cfa12604703c)

### Steps To Reproduce

```markdown
launch the world enter the inventory or menu
```

### Expected Behavior

idk delete my mouse icon

### Platform

```markdown
- Device model: chromebook
- CPU architecture: 
- Android version: 
- PojavLauncher version: Fix[cropper]: refactor image loading + fix huawei dialog chin + docs #4612
```

### Anything else?

this bug is only on new versions other versions like 1.12.2 dont have this problem

**Comment by GaucovyAero** [comment]
this cant be fixed, because the fix will most likely break all other devices
