### ISSUE TITLE
GUI mouse won't work

### ISSUE THREAD

**Issue by matt995** [PojavLauncherTeam/PojavLauncher#514]
Bug makes it so that you can't craft using a table can't pick blocks in inventory

1. Start PojavLauncher
2. Open forge 1.16.1 w optifine
3. Open world use inventory
4. You can't pick blocks

This might onlyvbe me though

**Platform:**
 - Device Model huawei p30 lite
 - CPU architecture aarch64
 - Android 10

**Comment by khanhduytran0** [comment]
**Use the touch or mouse!**
> you can't craft using a table

Split it by right mouse.

> can't pick blocks in inventory

Isn't it simply just a left mouse click?????

**Comment by khanhduytran0** [comment]
So if mouse won't work why can you stills able to select world?

**Comment by matt995** [comment]
I don't know it only works in gui

**Comment by matt995** [comment]
But not invin

**Comment by matt995** [comment]
I tried what you asked still nothing.
