### ISSUE TITLE
[pull requests] add VBOs 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5142]
### Is this request related to a bug?

No

### Describe the request.

Add VBOs (Vertex buffer object) for opengl for better perfomance for many phones in launcher setting. In 1.12.2 minecraft version VBOs can get 5% or 10% frame per second

### Anything else?

Ammm no actually . Thanks for bring back old osmesa version

**Comment by GaucovyAero** [comment]
invalid
