### ISSUE TITLE
How can I install mods?

### ISSUE THREAD

**Issue by SafeBotCaptcha** [PojavLauncherTeam/PojavLauncher#5144]
### Describe the bug

I tried finding the Mods path
Everytime it opens the pojav louncher where I can't select Anything.

### The log file and images/videos

https://photos.app.goo.gl/FjhbMaNHMWF6ru3N6

### Steps To Reproduce

```markdown
I just cannot copy mods into the louncher
```

### Expected Behavior

That I can click on share on the mod and it installs it on the program. (Pojavlouncher)

### Platform

```markdown
- Device model: Nothing Phone (1)
```

**Comment by SenyxLois** [comment]
You need a file browser to install mod.

**Comment by heygite** [comment]
Due to restrictions in Android 11-14, it has become almost impossible to interact with files in the data folder

**Comment by GaucovyAero** [comment]
use zarchiver
/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft

**Comment by Marshall2439** [comment]
You can't access it unless rooted your phone

**Comment by Marshall2439** [comment]
Launch mc, then Click Open mods folder option, select blue files app and open it then you click three bars at top left corner to open side menu where downloads AND pojavlauncher folders are so now you can copy mods form downloads to mods folder

**Comment by Marshall2439** [comment]
I think it might not work on all devices

**Comment by Blackv098** [comment]
> I think it might not work on all devices

So there aren no another way to do that like change the app storge out the data or something else

**Comment by GaucovyAero** [comment]
> > I think it might not work on all devices
> 
> So there aren no another way to do that like change the app storge out the data or something else

nowadays what works is using com.marc.files and clicking the 3 lines in the top left and pressing pojavlauncher

**Comment by Blackv098** [comment]
> > > I think it might not work on all devices
> > 
> > So there aren no another way to do that like change the app storge out the data or something else
> 
> nowadays what works is using com.marc.files and clicking the 3 lines in the top left and pressing pojavlauncher

What is com.marc.files?

**Comment by GaucovyAero** [comment]
> > > > I think it might not work on all devices
> > > 
> > > 
> > > So there aren no another way to do that like change the app storge out the data or something else
> > 
> > 
> > nowadays what works is using com.marc.files and clicking the 3 lines in the top left and pressing pojavlauncher
> 
> What is com.marc.files?

thats an app you can download in the play store, its basically just a shortcut to your default hidden android files app, com.marc.files is less than 50KB

**Comment by Blackv098** [comment]
> > > > > I think it might not work on all devices
> > > > 
> > > > 
> > > > So there aren no another way to do that like change the app storge out the data or something else
> > > 
> > > 
> > > nowadays what works is using com.marc.files and clicking the 3 lines in the top left and pressing pojavlauncher
> > 
> > What is com.marc.files?
> 
> thats an app you can download in the play store, its basically just a shortcut to your default hidden android files app, com.marc.files is less than 50KB

Thanks does it need root system device?

**Comment by Marshall2439** [comment]
> > > > > > I think it might not work on all devices
> > > > > 
> > > > > 
> > > > > So there aren no another way to do that like change the app storge out the data or something else
> > > > 
> > > > 
> > > > nowadays what works is using com.marc.files and clicking the 3 lines in the top left and pressing pojavlauncher
> > > 
> > > 
> > > What is com.marc.files?
> > 
> > 
> > thats an app you can download in the play store, its basically just a shortcut to your default hidden android files app, com.marc.files is less than 50KB
> 
> Thanks does it need root system device?

Absolutely NOT


(You can use adb aswell but it's complex)

**Comment by spoof-idk** [comment]
> You can't access it unless rooted your phone

Fist, make sure you have dev mode, usb debugging, and wireless debugging ON.

Next, download shuzuku,and click "pair with pairing code"

Then go back to the settings, and click on "wireless debugging" and pair.

Last, pair it with zarchiver in the settings, and then you should have access to Android>data>"appname"
