### ISSUE TITLE
increaseView Groups

### ISSUE THREAD

**Issue by REYXTE** [PojavLauncherTeam/PojavLauncher#5147]
### Is this request related to a bug?

No

### Describe the request.

Add one View Groups This will make it easier to make keys.
Just like FoldCraftLauncher.

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
use drawers in your controlmap and per-profile settings to set a specific controlmap for a specific modpack/profile
this is an unneeded feature
