### ISSUE TITLE
[BUG] Downloading modpacks keeps getting stuck

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5149]
### Describe the bug

Whenever i download a modpack it keeps getting stuck at the very end when it's almost finished or gets stuck at random moment during downloading, some modpacks i never be able to install because it always gets stuck

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158475307/3c71620d-aec7-4bd6-ade5-b4455b408c55)

### Steps To Reproduce

```markdown
1. Launch pojav
2. Install a modpack
3. Download stuck
```

### Expected Behavior

Install successfully

### Platform

```markdown
- Device model: Galaxy A31
- CPU architecture: MediaTek Helio P65
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
most probably an issue on your side, works fine for me
