### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by matt995** [PojavLauncherTeam/PojavLauncher#515]
Bug makes it so that you can't craft using a table can't pick blocks in inventory

1. Start PojavLauncher
2. Open forge 1.16.1 w optifine
3. Open world use inventory
4. You can't pick blocks

This might onlyvbe me though

**Platform:**
 - Device Model huawei p30 lite
 - CPU architecture aarch64
 - Android 10

**Comment by khanhduytran0** [comment]
**Use the touch or mouse!**
> you can't craft using a table

Split it by right mouse.

> can't pick blocks in inventory

Isn't it simply just a left mouse click?????

**Comment by khanhduytran0** [comment]
Well duplicate your own issue #514
