### ISSUE TITLE
Provides installation of jdk format files in the Java runtime or build source code and others[F-Req] <Short description>

### ISSUE THREAD

**Issue by yffugfh** [PojavLauncherTeam/PojavLauncher#5150]
### Describe the request.

It is known that the launcher can install jar files, if it is based on the software function in termux, then theoretically can install the Java runtime, free, so I hope that the launcher will have technical innovation to promote the development of the launcher

**Comment by yffugfh** [comment]
One-sided in installing the Java runtime

**Comment by yffugfh** [comment]
Or other build functions

**Comment by yffugfh** [comment]
Or maybe it's a different operating system

**Comment by VenomousSteam81** [comment]
what the hell is this supposed to mean lmfao
