### ISSUE TITLE
[F-Req] Neoforge performance mods patched 1.20.4, please 

### ISSUE THREAD

**Issue by Hir0DF** [PojavLauncherTeam/PojavLauncher#5151]
### Is this request related to a bug?

I'm a pojav player who has a cell phone with low Android, which takes away the possibility of using fabric and forge 1.20.4 is currently not working I imagine it's a Java error, but even if it worked the performance mods wouldn't work, so I went to neoforge, as I need to play with some mods, so the OptiFine version wasn't that useful for me, and of all the current mods for neoforge 1.20.4, only 4 didn't work, these being the embeddium and its two addons(which, if possible, I would love for a patch to be made, fixing or explanation of how to make it work, it is a fork of sodium, so I imagine it is not that difficult since you patched sodium) and the 3d skin, but I don't mind this one as much since it's more visual. Sorry for my bad English, I'm Brazilian.

**Comment by GaucovyAero** [comment]
i have no idea how to explain to this but basically all of the patches are made by the community on the pojav discord and not the actual pojav devs, which means this might not happen 
i suggest you learn how the mods work and patch them yourself so that they work on pojav and share with others
