### ISSUE TITLE
[BUG] launcher closes with no provided error message when launching game

### ISSUE THREAD

**Issue by SummitSodaroo** [PojavLauncherTeam/PojavLauncher#5152]
### Describe the bug

Whenever i try to launch the game, the launcher closes and doesn't provide an error message.

### The log file and images/videos

nothing is provided to me

### Steps To Reproduce

```markdown
1. start PojavLauncher
2. set any version, any settings
3. launch
4. launcher closes
```

### Expected Behavior

I expected the game to open smoothly or provide some kind of error message as to why it's not launching.

### Platform

```markdown
- Device model: Lenovo IdeaPad Flex 5 Chromebook
- CPU architecture: TGL
- Android version: unknown
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by GaucovyAero** [comment]
stale
