### ISSUE TITLE
add java 21 in pojavlauncher  

### ISSUE THREAD

**Issue by agent1243** [PojavLauncherTeam/PojavLauncher#5153]
### Is this request related to a bug?

it's not a problem 

### Describe the request.

in pojavlauncher we have java 8 and java 17, there could be java 21 as well as the foldcraft launcher.  

### Anything else?

Java 21 is often faster than Java 17

**Comment by Dilen0001** [comment]
.

**Comment by agent1243** [comment]
????

**Comment by TotallyNotSaeed** [comment]
Fr?

**Comment by GaucovyAero** [comment]
fork the android-openjdk-build-multiarch repo and do a jre21 actions build if there isnt one already, then download and install the artifact

**Comment by Hissymaster** [comment]
Duplicate of #5308
