### ISSUE TITLE
[BUG] <Crash sodium>

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#5155]
### Describe the bug

Crash sodium When entering the world I tried pathcer Does not work:(
I checked both in the world and on the server

### The log file and images/videos

this
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14319276/latestlog.txt)

### Steps To Reproduce

```markdown
1 start pojavlauncher
2 launch fabric with sodium
3 I go to the server or to the world
4 I wait and crash
```

### Expected Behavior

I expected that the sodium patcher would help

### Platform

```markdown
- Device model: Teclast t40 pro 8/120gG
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version:edelweiss-20240208-b9b2dae-
```

**Comment by lost72738** [comment]
Use 1.20 or below

**Comment by savvacorgi** [comment]
> Use 1.20 or below

I used 1.20.2 and 1.20.4 crash

**Comment by savvacorgi** [comment]
> Use 1.20 or below

a oh my translete bad...

**Comment by TotallyNotSaeed** [comment]
Use this modpack, it has rubidium, sodium, vulkan and optifine version some of them may not work properly
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158475307/60959121-5f42-41f3-b6ba-74b7aa893b2f)

**Comment by savvacorgi** [comment]
> Use 1.20 or below

That helped

**Comment by savvacorgi** [comment]
> Use this modpack, it has rubidium, sodium, vulkan and optifine version some of them may not work properly ![image](https://private-user-images.githubusercontent.com/158475307/305716970-60959121-5f42-41f3-b6ba-74b7aa893b2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjI2ODgsIm5iZiI6MTcwODI2MjM4OCwicGF0aCI6Ii8xNTg0NzUzMDcvMzA1NzE2OTcwLTYwOTU5MTIxLTVmNDItNDFmMy1iNmJhLTc0YjdhYTg5M2IyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMzE5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2Q1ODY5NTNiOGQ5NWY1M2E2NWE1YzYzMWMyOGI3ZWIzN2FjNzVjNTRjNWNkMzVmMTQzYTRjNThmYTUyNmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xFRpSNcKvjkfZFBdrcXfWtBz-aLVvhawhWqIxp5oiPA)

That is, it will help with the crash of sodium? On 1.20.1+

**Comment by TotallyNotSaeed** [comment]
Yes it helped for me
