### ISSUE TITLE
[BUG] Game crash

### ISSUE THREAD

**Issue by MDEmonY** [PojavLauncherTeam/PojavLauncher#5157]
### Describe the bug

i have installed Additive modpack for 1.16.5 and when i start the game it were normal but when i enter a world then it crash.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14323258/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. install additive (1.16.5) version 1.23.0
3. enter a world
```

### Platform

```markdown
- Device model: Redmi A1+
- CPU architecture: 32 bit
- Android version: 12
- PojavLauncher version: latest Google play store version.
```

**Comment by zkitefly** [comment]
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/64117916/609fc43f-947a-4472-b7db-276ed4577986)

https://github.com/PojavLauncherTeam/PojavLauncher/issues/5013#issuecomment-1877313421

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/64117916/db6d2329-a585-4e03-bce7-5142a992fdb8)

**Comment by Bel69420** [comment]
You need zink renderer for Sodium 0.5, the patcher doesn't work after Sodium 0.5 Update.

**Comment by MDEmonY** [comment]
> You need zink renderer for Sodium 0.5, the patcher doesn't work after Sodium 0.5 Update.

but my device doesn't support zink

**Comment by Bel69420** [comment]
Wait mb, i though it was 1.17+

**Comment by Bel69420** [comment]
Thought*

**Comment by GaucovyAero** [comment]
disable fog occlusion and compact vertex format
if that doesnt work, downgrade to sodium 0.1.0 and do the same thing
