### ISSUE TITLE
[BUG] <pojavlauncher crashes while using shaders packs on Zink renderer>

### ISSUE THREAD

**Issue by mahi09-spev** [PojavLauncherTeam/PojavLauncher#5160]
### Describe the bug

On loading shader packs on Zink renderer in pojavlauncher with optifine, the game crashes after 10 - 15 seconds 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14328957/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher
Select Zink renderer
Load up Minecraft with optifine
Play a world
Enable shaders and then crash
```

### Expected Behavior

The shaders should work without any problem 

### Platform

```markdown
- Device model: Redmi note 10S
- CPU architecture: 64-bit architecture
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk (playstore version)
```

**Comment by GaucovyAero** [comment]
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G76) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance have_EXT_custom_border_color 
```
native system crash, its most likely your gpu not meeting zink requirements

**Comment by Bel69420** [comment]
@GaucovyAero, that's not the problem

**Comment by Bel69420** [comment]
Zink mesa 23.0.4 is buggy

**Comment by mahi09-spev** [comment]
Then what should I do it just crashes after a set period like 10 seconds after enabling. But the game works perfectly fine in those 10 seconds

**Comment by mahi09-spev** [comment]
@GaucovyAero wasn't the Zink supposed to be stable and should work on most devices?
