### ISSUE TITLE
[BUG] <Short description>Shutting down internal server 

### ISSUE THREAD

**Issue by Muazraza** [PojavLauncherTeam/PojavLauncher#5161]
### Describe the bug

While playing stoneblock 2 i get this error when i opened the ender chest

### The log file and images/videos

[crash-2024-02-19_17.55.48-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14331114/crash-2024-02-19_17.55.48-client.txt)

### Steps To Reproduce

```markdown
Remove the random patches mod from stoneblock 2 and add optifine
```

### Expected Behavior

I expect that mod pack should work properly 

### Platform

```markdown
- Device model: samsung SM-N770F
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by RimakiTaema** [comment]
Disable Shaders (Mods : DE[Called As Draconic Evolution] and others mods that can be disable the shaders

**Comment by Muazraza** [comment]
Shaders are already disabled

**Comment by GaucovyAero** [comment]
you gotta somehow disable loading of custom shaders in codechickenlib, maybe its in a config file somewhere?

**Comment by Muazraza** [comment]
Thanks its in the config of draconic evolution i turned it of and it worked
