### ISSUE TITLE
[BUG] <game crashes on Zink renderer while using optifine with shaders>

### ISSUE THREAD

**Issue by mahi09-spev** [PojavLauncherTeam/PojavLauncher#5166]
### Describe the bug

When I play the game with optifine and Zink renderer, after enabling shaders packs the game crashes after 10 -12 seconds. But it doesn't crash in sodium-iris

### The log file and images/videos

[latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14347723/latestlog.1.txt)

### Steps To Reproduce

```markdown
Start pojavlauncher launcher 
Launch an optifine profile with Zink as renderer 
Load into a world
Enable shaders
Crash
```

### Expected Behavior

The shaders should run completely fine lik they do on sodium - iris

### Platform

```markdown
- Device model: Redmi note 10S
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: playstore latest
```

### Anything else?

The game works completely fine with shaders in sodium while using iris but crashes on optifine after 10 seconds so i don't think that it is compatibility problem with the GPU of my device or buggy mesa

**Comment by Bel69420** [comment]
What kind of shader?

**Comment by Bel69420** [comment]
Lemme try with my phone

**Comment by mahi09-spev** [comment]
@Mario191209 every type of shader crashes

**Comment by Bel69420** [comment]
![Screenshot_2024-02-21-01-27-51-220_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89313901/eb409b8f-5cd4-4d25-ab42-1adc34895e6e)
It works for me

**Comment by mahi09-spev** [comment]
@Mario191209 Did you use custom jvm arguments?

**Comment by Bel69420** [comment]
Nope

**Comment by Bel69420** [comment]
I'm sure there's a problem with your GPU

**Comment by mahi09-spev** [comment]
Then why doesn't it crash on sodium which is ironically buggy according to pojavlauncher

**Comment by Bel69420** [comment]
Cuz the OpenGL version was spoofed

**Comment by Bel69420** [comment]
If not, sodium will crash including Minecraft 1.17+ when you're using Mali GPU

**Comment by Bel69420** [comment]
In Mesa 23.0.4, mali only supports OpenGL 3.1 with zink. Which mean, Minecraft does not support 3.1 anymore

**Comment by mahi09-spev** [comment]
Why didn't sodium crash then, I used it on 1.20

**Comment by mahi09-spev** [comment]
With Zink and shaders and got 30+ fps

**Comment by mahi09-spev** [comment]
With mods ofc

**Comment by Bel69420** [comment]
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G76) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance have_EXT_custom_border_color 


Bro, your GPU missing one extension 💀

**Comment by mahi09-spev** [comment]
What should I do ? Is it unsolvable?

**Comment by Bel69420** [comment]
I think yeah, it is unsolvable

**Comment by Bel69420** [comment]
Your Vulkan driver is too old for zink

**Comment by mahi09-spev** [comment]
One thing I am not able to understand how does this work on sodium! I mean it should crash on it also then . Right?

**Comment by Bel69420** [comment]
Well you know that Zink met the requirements

**Comment by Bel69420** [comment]
That's why it doesn't crash

**Comment by mahi09-spev** [comment]
Besides here's the screenshot shot in sodium 
![Screenshot_2024-02-20-23-15-37-448_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/81853976/59ffaefd-e702-4c25-9ac9-1fed6778c3e1)

**Comment by Bel69420** [comment]
What's the resolution scale and chunk distance you use?

**Comment by mahi09-spev** [comment]
Resolution is 60 and render distance is 6 and the graphics are set to fancy

**Comment by mahi09-spev** [comment]
I set render distance low because of the shaders but without it goes up to 59 average

**Comment by GaucovyAero** [comment]
> One thing I am not able to understand how does this work on sodium! I mean it should crash on it also then . Right?

iris shaders most probably dont require the features your gpu is missing

**Comment by mahi09-spev** [comment]
Any way to counter it?
