### ISSUE TITLE
[F-Req] <Add VGPU and remove GL4ES>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#5168]
### Is this request related to a bug?

Shader failed

### Describe the request.

Updated VGPU to support GLSL 460 and OpenGL 4.6.

### Anything else?

Because Holy GL4ES has stopped development and has become obsolete OpenGL.

**Comment by Marshall2439** [comment]
I don't think they will.....

**Comment by GaucovyAero** [comment]
vgpu is gl4es and had never supported anything over incomplete opengl 3.0 lol
