### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by axylex** [PojavLauncherTeam/PojavLauncher#517]
I was trying to install optifine and sildurs basic and tried watching some tutorials. But I can’t find ‘.minecraft’ folder in games folder which is required for installing optifine and shaders. Am I doing something wrong??

**Comment by WesleyVanNeck** [comment]
shaders aren't supported rn

**Comment by artdeell** [comment]
enable hidden folders

сб, 19 дек. 2020 г., 20:00 axylex <notifications@github.com>:
