### ISSUE TITLE
[BUG] Crash after downloading the server texture pack on 1.20.1

### ISSUE THREAD

**Issue by Jinerast928** [PojavLauncherTeam/PojavLauncher#5170]
### Describe the bug

I playing on vanilla server and one of them it was necessary to download a texture pack

### The log file and images/videos

[crash-2024-02-23_10.13.26-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14382754/crash-2024-02-23_10.13.26-client.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14382755/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Join to private server HiMaks
3. Download texture pack
4. Game crashed
```

### Expected Behavior

Crash after downloading server texture pack

### Platform

```markdown
- Device model: Redmi 13C
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
unsupported, your server resource pack is using custom shaders
