### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Mustafa12442** [PojavLauncherTeam/PojavLauncher#5171]
### Describe the bug

When i try to launch quilt loader 0.23.1-1.19.2 it crashes and it says "application/game exited with code 1, check latestlog.txt for more details." Please help

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 220333QAG
Info: API version: 33
Info: Selected Minecraft version: quilt-loader-0.23.1-1.19.2
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1600
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~NOVNY4uKcMasebto7WR8yw==/net.kdt.pojavlaunch-rH08a3O_WpsNV9gpfm97Aw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~NOVNY4uKcMasebto7WR8yw==/net.kdt.pojavlaunch-rH08a3O_WpsNV9gpfm97Aw==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
--------- beginning of main
I/jrelog  (27254): dlopen libOSMesa.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (27254): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (27254): dlope
n /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so su
ccess
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/In
ternal-17/lib/libawt_headless.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  (27254): d
lopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success
I/jrelog  (27254): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  (27254): dlopen /data/app/~~NOVNY4uKcMasebto7WR8yw==/net.kdt.pojavlaunch-rH08a3O_WpsNV9gpfm97Aw==/lib/arm64/libopenal.so success
I/jrelog  (27254): Done processing args
I/jrelog  (27254): Found JLI lib
I/jrelog  (27254): Calling JLI_Launch

٢٠٢٤-٠٢-٢٣ ١٣:٥٤:٣٦,٣٩٠ main ERROR appender Console has no parameter that matches element Policies
[13:54:36] [main/INFO]: Loading Minecraft 1.19.2 with Quilt Loader 0.23.1
[13:54:36] [main/INFO]: Loading mappings: jar:file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar!/mappings/mappings.tiny
[13:54:37] [main/WARN]: Unknown file in mods folder: <mods>/OptiFine_1.19.2_HD_U_H9.jar
[13:54:38] [main/ERROR]: Crashed! The full crash report has been saved to /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2024-02-23_13.54.38.4938-quilt_loader.txt
---- Quilt Loader: Failed to load ----
Date/Time: 2024/02/23 13:54:38.5138
Quilt Loader Version: 0.23.1

-- Error 1 --

Cardinal Components API (base) requires version [0.1.2, ∞) of fabric-api-base, which is missing!

- <mods>/requiem-2.0.0-beta.16.jar!/META-INF/jars/cardinal-components-base-5.0.1.jar

-- Error 2 --

2 mods requires any version of fabric-api-base, which is missing!

- <mods>/requiem-2.0.0-beta.16.jar!/META-INF/jars/satin-1.9.0.jar
- <mods>/requiem-2.0.0-beta.16.jar!/META-INF/jars/fabric-permissions-api-0.1-SNAPSHOT.jar

-- Error 3 --

Cardinal Components API (worlds) requires any version of fabric-networking-api-v1, which is missing!

- <mods>/requiem-2.0.0-beta.16.jar!/META-INF/jars/cardinal-components-world-5.0.1.jar

-- Error 4 --

3 mods requires any version of fabric, which is missing!

- <mods>/requiem-2.0.0-beta.16.jar!/META-INF/jars/impersonate-2.8.0.jar
- <mods>/requiem-2.0.0-beta.16.jar!/META-INF/jars/automatone-0.9.0.jar
- <mods>/requiem-2.0.0-beta.16.jar!/META-INF/jars/PlayerAbilityLib-1.6.0.jar

-- Error 5 --

Reach Entity Attributes requires version [0.9.16, ∞) of fabric-registry-sync-v0, which is missing!

- <mods>/requiem-2.0.0-beta.16.jar!/META-INF/jars/reach-entity-attributes-2.3.0.jar

-- Plugin State --

Cycle number = 1
Cycle Step = SOLVE

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)

---- end of report ----
[13:54:38] [main/ERROR]: For more details see the full crash report file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2024-02-23_13.54.38.4938-quilt_loader.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7f4ef7fd30)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7f3f832038)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7ea8223298)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7f3f832038)

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model: Redmi 10C
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: latest version
```

### Anything else?

Nothing

**Comment by GaucovyAero** [comment]
you need qfapi

**Comment by Mustafa12442** [comment]
> you need qfapi

And how do i get it?

**Comment by zkitefly** [comment]
> > you need qfapi
> 
> And how do i get it?

https://modrinth.com/mod/qsl
