### ISSUE TITLE
[BUG] Problem with ForgeMultipart 1.16.5

### ISSUE THREAD

**Issue by SeMISos** [PojavLauncherTeam/PojavLauncher#5172]
### Describe the bug

Minecraft shows error when loading mods, and in crash log i can see its problem with ForgeMultipart

### The log file and images/videos

[log.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14392369/log.log)
[crashlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14392371/crashlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install SkyTech II from CurseForge
3. Start Game
```

### Expected Behavior

Minecraft will show screen that it cant load some mods.

### Platform

```markdown
- Device model: Samsung Galaxy A54 5G
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by artdeell** [comment]
You seem to be using Java 17 for this modpack. Have you tried using Java 8 instead?

**Comment by GaucovyAero** [comment]
the modpack starts up fine for me with java 8, there is a graphic z-layer issue, that might be fixable by just using zink or removing the mod thats causing it
