### ISSUE TITLE
[Suggestion] Open with PojavLauncher

### ISSUE THREAD

**Issue by senina4** [PojavLauncherTeam/PojavLauncher#5173]
### Describe the request.

Use "open with" to open the jar installation file. 

![picture 1](https://github.com/PojavLauncherTeam/PojavLauncher/assets/84493324/ed8186ef-a15c-492f-a644-818324065e63)
 

## My English is bad, I use translation for some words.

**Comment by zkitefly** [comment]
Is this feature necessary? It feels like the gain is too small

这个功能有必要吗？感觉收益太小了

**Comment by senina4** [comment]
More convenient

**Comment by 0hStormy** [comment]
I could see this being useful when installing stuff like OptiFine, I like this.

**Comment by EDUARDO9L** [comment]
Recentemente estive tentando instalar mods e vendo essa função tudo ficaria mais fácil!

**Comment by senina4** [comment]
Any process?
