### ISSUE TITLE
[BUG] Please remove mcbbs download source

### ISSUE THREAD

**Issue by zkitefly** [PojavLauncherTeam/PojavLauncher#5174]
### Describe the bug

Currently mcbbs is closed, you can't use mcbbs download source, please remove it.

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

No more mcbbs download sources (not bmclapi download sources, he's normal)

### Platform

```markdown
-
```

### Anything else?

There will be a new high speed download source, I'll come here to notify when it's available.

**Comment by ghost** [comment]
I can't wait to be removed
