### ISSUE TITLE
Ability to change skins directly in the launcher + delivery of the assembly with modrith File .mrpack

### ISSUE THREAD

**Issue by Offensive69** [PojavLauncherTeam/PojavLauncher#5175]
### Is this request related to a bug?

Maybe

### Describe the request.

Hello, I suggest adding to the launcher the ability to change the skin without going to the Microsoft website, I have a license and every time I go to the site in pairs + there is a mod for one skinswapper but it doesn’t work For some reason it works even with a license, although others work, but this mod is the best in my opinion and I would be glad, like others, to possibly add support for this mod or fix it, thanks for your respect!
![IMG_20240224_193439_929](https://github.com/PojavLauncherTeam/PojavLauncher/assets/88339290/1e3d3566-1bdb-4fa9-a15d-358d67357637)

### Anything else?

In the podjavlauncher it is used Assemblies from modrit and courseforge, but when you download the required assembly from modrit, there is a .mrpack file and it can’t be put in a subzavl or I don’t know this, but I need those mods from the assemblies for my assembly Because in the assembly that is downloaded by the launcher, it does not use my resource packs and shaders :( thanks for that!

**Comment by GaucovyAero** [comment]
wont be added, put your resource packs and shaders into the custom_instances/Modpack folder in your pojav directory
