### ISSUE TITLE
[AWT] About running Java AWT application on Android

### ISSUE THREAD

**Issue by StArraySharp** [PojavLauncherTeam/PojavLauncher#5177]
### Is this request related to a bug?

no
### Describe the request.

Hello, PojavLauncher team, I am a bad personal developer, and I want to ask a question, how do you run JavaAWT applications on Android? I know that JRE and cacio are used in this method, and I have tried this method by imitating your code, and I will always encounter the following problems:
```
02-26 15:12:35.017  6947  6947 E jrelog  : dlopen /data/data/com.example.application/files/lib/aarch64/libawt_headless.so failed: dlopen failed: cannot locate symbol "jvm" referenced by "/data/data/com.example.application/files/lib/aarch64/libawt_headless.so"...
02-26 15:12:35.020  6947  6947 E jrelog  : dlopen /data/data/com.example.application/files/lib/aarch64/libfontmanager.so failed: dlopen failed: cannot locate symbol "AWTFreeChar" referenced by "/data/data/com.example.application/files/lib/aarch64/libfontmanager.so"...
```
If so, will you create a demo repository?

**Comment by khanhduytran0** [comment]
We have no official AWT-dedicated project for now, maybe you can check this fork out: https://github.com/2009scape/2009Scape-mobile

**Comment by GaucovyAero** [comment]
~~good issue but i have no idea whether anybody will respond to this, i guess you are on your own~~ disregard what i just said, didnt see comment above
