### ISSUE TITLE
[question] is there a way to access pojavlauncher's directory?

### ISSUE THREAD

**Issue by hoanhan1105** [PojavLauncherTeam/PojavLauncher#5178]
### Describe the request.

I'm using a Samsung phone with Android 14, but since the new privacy update of Android, I no longer can get access to any folder that is inside the Android's data directory. I want to add mods for my game, but it seems like even Zarchiver or X-Plorer could not help. I would like to know if there's any way to get access or just add mods.

### Anything else?

Device: Samsung Galaxy A52s
Android version: 14
Pojavlauncher version: latest
Here is a screenshot i took when i tried to log in to pojavlauncher's data folder:
![Screenshot_20240227_130036_ZArchiver](https://github.com/PojavLauncherTeam/PojavLauncher/assets/115875916/748ad8c6-4cdc-477c-a2d4-4b0fd2e68bc4)

**Comment by GaucovyAero** [comment]
you gotta use the default files app built into android to access it, you might have to create a shortcut to that filesactivity if you are on oneui

**Comment by GaucovyAero** [comment]
![Screenshot_20240227-094756_Files](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/ec5aaf95-71a9-46ec-997f-e1d18cccc666)

**Comment by RandomMinecraftGuy** [comment]
> you gotta use the default files app built into android to access it, you might have to create a shortcut to that filesactivity if you are on oneui

could you explain a little more? im trying to help my friend use shaders but he cant find the directory
