### ISSUE TITLE
CRASH PROBLEM 

### ISSUE THREAD

**Issue by RISHABH7120109** [PojavLauncherTeam/PojavLauncher#5179]
### Describe the bug

I WAS OPEN MY POJAVLAUNCHER SUDDENLY LAUCHER IS HAS BEEN CRASHED 

### The log file and images/videos

![1000097628](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161552627/5ce3c3ee-9564-47db-8604-0a1f135b58f5)
[crash-2024-02-28_09.31.06-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14428867/crash-2024-02-28_09.31.06-client.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher suddenly pojavlauncher has been crashed
```

### Expected Behavior

PLZ HELP

### Platform

```markdown
- Device model: CPH2201
- CPU architecture: no
- Android version: 13
- PojavLauncher version: 1.20.1
```

### Anything else?

Plz help

**Comment by Algiuxs** [comment]
Log, plz?

**Comment by Algiuxs** [comment]
Remove the boosted brightness mod
