### ISSUE TITLE
[Suggestion] Please allow to select other folders 

### ISSUE THREAD

**Issue by tygoee** [PojavLauncherTeam/PojavLauncher#5181]
### Is this request related to a bug?

(Transferred from PojavLauncherTeam/pojavlauncherteam.github.io/issues/139, the wrong repository)

As of a newer Android version (13?), Android restricted users from folder access to Android/data folders. It's now only meant to be accessible on desktop with USB and currently there are workarounds, but they're getting patched every update. This means that if we want to put in mods or recourcepacks into our .minecraft/ folder, it's not possible.

### Describe the request.

When trying to select another folder, there's no option besides the ones in the data folder:

<img src="https://github.com/PojavLauncherTeam/PojavLauncher/assets/87303800/d97d865d-a4dd-4f02-9876-ac5a10b20acb" width="300"/>

It would be nice to have a seperated button (at the top maybe) saying 'Internal storage' that leads to /data/emulated/0/

### Anything else?

I don't know the codebase, but this should be a pretty small change. For accessing the storage you do need to prompt the user for MANAGE_EXTERNAL_STORAGE by the way

As this is quite a big permission, maybe another implementation is better; a tab (f.e. Manage Instances) where you can upload files or zipped folders anywhere, you won't need any additional permissions as you already can read files (for selecting jar files).

**Comment by Creeper-banner** [comment]
For now, you can try to use a third-party file manager that allows you to get access to /Android/data/xxx folder.

**Comment by tygoee** [comment]
Currently it's only possible to bypass the restriction by reverting Android's built-in file manager's updates via the app menu, but on some phones this is greyed out.

Third party file managers won't work, Android [restricted users](https://developer.android.com/about/versions/11/privacy/storage) granting permissions to the /storage/emulated/0/Android/data folder.

The only workaround that works for all users is connecting your android to a desktop device and accessing your files via usb.

**Comment by GaucovyAero** [comment]
> Currently it's only possible to bypass the restriction by reverting Android's built-in file manager's updates via the app menu, but on some phones this is greyed out.
> 
> Third party file managers won't work, Android [restricted users](https://developer.android.com/about/versions/11/privacy/storage) granting permissions to the /storage/emulated/0/Android/data folder.
> 
> The only workaround that works for all users is connecting your android to a desktop device and accessing your files via usb.

the other thing that works is to use com.marc.files or an activity launcher to launch the stock files app which can access the pojav directory via the hamburger menu

**Comment by tygoee** [comment]
Yes that's what I mean using the built-in file manager (my Samsung has a shortcut to the stock one by default). I'm just saying that may be resolved in later Android versions, so other folders should be able to get selected.

If I had the time and knew some java, I would make a pull request

**Comment by Frostybtfindingscript** [comment]
That's what im saying I can't even put mods into the game because of AOSP files app it is implemented in every android devices (newer device that are made in latest dates of android 11-14 are already inaccessible but some can, i have a android 12 and have full access to Zarchiver's Android/data folder) if i could get back the old SAF (Storage Access Framework) it would be great and regain all access from Android>Data and Android>OBB, Their is a way to Actually access the Android>data, Android>OBB files is to reset all updates from AOSP files app, but it's just a Read write files meanin you can't copy, move, nor paste.

**Comment by Mathias-Boulay** [comment]
We are constrained within the data folders, as per android restrictions.

**Comment by tygoee** [comment]
> We are constrained within the data folders, as per android restrictions.

I mentioned in my post that if getting the permission `MANAGE_EXTERNAL_STORAGE` wouldn't be possible, a feasible solution would be to make it possible to be able to select files (which is not restricted with Android), and move it to the current built-in file manager. 

This has to have some more features though, like to copy, paste, duplicate, edit, delete, make new files/folders, export a file, extract a zip, etc.

Without this, modding would be basically impossible without an older Android or a PC.

**Comment by GaucovyAero** [comment]
you can install com.marc.files (about 100KB) to get a shortcut to the default file manager on android that has access to pojav's files via the hamburger menu

**Comment by tygoee** [comment]
My phone comes with that shortcut by default, and it was the way I could make some mods work. But as others said, on some phones it's not possible to copy, move or paste so for them that feature is pretty much useless.

**Comment by artdeell** [comment]
Having an integrated file manager, sadly, is a huge burden on us since if we implement it, people will start asking for more and more features in it.
We are considering a "Show in file explorer" button that will open your files using a system file explorer and Pojav's SAF provider (available regardless of OEM restrictions on Android/data)

**Comment by tygoee** [comment]
If that will work, it would be great but I don't know how long it would last as Android is continuously trying to remove access to Android/data and eventually they might fully restrict the internal file manager from the folder (I already can't navigate to it the usual way)
