### ISSUE TITLE
Stuck with spam about Opengl error/no context was called

### ISSUE THREAD

**Issue by RealTraxData** [PojavLauncherTeam/PojavLauncher#5182]
### Describe the bug

The modpack is stucking at the end of initialization with a spam about
[Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
And
Thread[Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14440576/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Start modpack Prominence II Rpg
3. After initializarion the game stuck with the 2 errors that is described
```

### Expected Behavior

To enter at least in the menu

### Platform

```markdown
- Device model: Samsung Galaxy Note 10+
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Video renderer is set on Angle. On zink and holy is crashing

**Comment by GaucovyAero** [comment]
downgrade sodium to 0.4.10 and use the patcher on the pojav wiki or go to the pojav discord and download a patched version of 0.5.x
