### ISSUE TITLE
Can you get it into the App Store 

### ISSUE THREAD

**Issue by SilkRoadMod** [PojavLauncherTeam/PojavLauncher#5184]
### Describe the request.

Right now I have absolutely no way to put this onto my iPad Pro without an Apple dev account as there are no jailbreaks for iOS 17 that work on iPad pros

### Anything else?

Pangu8 is the only one I could find but it thinks I’m on macOS because of iPad Pro stuff

**Comment by khanhduytran0** [comment]
![](https://pspdfkit.com/assets/images/blog/2019/wwdc-tips-2019-edition/apple-no-f2204e66.gif)

PojavLauncher is against App Store rule for dynamically generating untrusted code (JIT). In EU, only verified web browser engines are allowed to use JIT.
If you stayed in iOS 16, you’d have had either TrollStore or SideStore with on-device JIT enabling capability.

You’re opening this issue in wrong repo.

**Comment by SilkRoadMod** [comment]
Bro I just bought this thing and it already had iOS 17 on it

**Comment by Algiuxs** [comment]
Then downgrade
