### ISSUE TITLE
[BUG] <mod crash and entity display problem in server >

### ISSUE THREAD

**Issue by witherHong** [PojavLauncherTeam/PojavLauncher#5186]
### Describe the bug

I'm using PojavLauncher to play Minecraft, but after installing the Valkyrien Skies mod, the game crashes as soon as I open the world. Does anyone know what's going on?
![Screenshot_20240229_205150](https://github.com/PojavLauncherTeam/PojavLauncher/assets/159994069/dc3630de-9faa-44a5-9012-d15e88659fec)
This screenshot shows where the crash report indicates a problem with the mod. I unpacked it to check. By the way, when I join a server, everything works fine. It only crashes when I open my own world
btw i also got some problem in server.i cant see entity such as the cover of chest and alot of mod entity
but worked normally.

Here is the crash report
[crash-2024-02-29_20.33.32-server.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14449959/crash-2024-02-29_20.33.32-server.txt)

### The log file and images/videos

![Screenshot_20240216_160634](https://github.com/PojavLauncherTeam/PojavLauncher/assets/159994069/64b5aac7-5abe-48df-bd3c-22961e794ad4)
Entity problem in server 

### Steps To Reproduce

```markdown
1.put valkyrien skies mod in mods folder
2.open game
3.create world
4.crash
```

### Expected Behavior

I need to open the world without crash

### Platform

```markdown
- Device model: honor 90
- CPU architecture: arm64-v8a(64bit)
- Android version: Android 13(T)
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
custom shaders/physics generally dont work on pojav
