### ISSUE TITLE
[BUG] problemas con un mod

### ISSUE THREAD

**Issue by Elabrax** [PojavLauncherTeam/PojavLauncher#5187]
### Describe the bug

[BUG] no funciona con el mod webdisplay quisiera saber si tiene algún arreglo☺️

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14454925/latest.log)

### Steps To Reproduce

```markdown
Start PojavLauncher
```

### Expected Behavior

Mi teclado trabaja excelente mentew

### Platform

```markdown
- Device model: poco x3 
- CPU architecture: octa-core max 2.30
- Android version: 12
- PojavLauncher version:edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
we would have to bundle chromium inside pojav for it to work and that would make pojav 500+ MB big

**Comment by Elabrax** [comment]
pero se podria hacer es que quisiera que algunos usuarios pudieran entrar en mi servidor por el telefono sin tener que poner el addon de bedrock
