### ISSUE TITLE
[BUG] <Icon bug>

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#5189]
### Describe the bug

When I was using the launcher, because the game download failed inexplicably, the icon under the game suddenly had a problem
![Screenshot_20240302_121302](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136832400/7ce5eb9d-28fe-4373-87c5-b099f04e5c49)

### The log file and images/videos

![Screenshot_20240302_121302](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136832400/cdf3179e-aa70-4226-9f07-7d6a4ba64759)

### Steps To Reproduce

```markdown
1.Turn on the starter
2.Download a version of the game
3.Version download failed with icon bug
```

### Expected Behavior

The icon will be the same as before

### Platform

```markdown
- Device model: 64
- CPU architecture: 
- Android version: 8.1.0
- PojavLauncher version: edelweiss-20240219-195568c-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
Oh yeah I got this one somehow. I have yet to reproduce it consistently
