### ISSUE TITLE
sodium mod doesn't work

### ISSUE THREAD

**Issue by manolis07** [PojavLauncherTeam/PojavLauncher#519]
So basically I can install fabric perfectly fine and all other mods but as soon I try to open a world when sodium is active it just crashes. Idk if this is a problem with the launcher or with the mod but if you think you can solve this issue please comment

**Comment by khanhduytran0** [comment]
You need disable these options
- Compact vertex format
- Fog occlusion

**Comment by Zeyrox1090** [comment]
yes and make 
![Screenshot_2020-12-20-09-17-31-20](https://user-images.githubusercontent.com/73925046/102703027-9d88f380-42a4-11eb-88c0-4ab14256ae83.jpg) 3.0

**Comment by Zeyrox1090** [comment]
cuz sometimes the default is 2 for me lol

**Comment by manolis07** [comment]
> You need disable these options
> 
> * Compact vertex format
> * Fog occlusion

Omg thanks a lot it actually worked . You are actually the best
