### ISSUE TITLE
[BUG] LabyMod  Crash

### ISSUE THREAD

**Issue by whaltermc** [PojavLauncherTeam/PojavLauncher#5193]
### Describe the bug

its crashing i  any renderer its require FML support

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14472326/latest.log)

### Steps To Reproduce

```markdown
1.i install labymod 1.20.1
2. run labymod
```

### Expected Behavior

crashed whe launche after frw mins

### Platform

```markdown
- Device model: Oppo A92 CPH2059
- CPU architecture: 64 bit
- Android version: 11
- PojavLauncher version: edwells release 
- Cpu: SnapDragon 665 andreno 610™ 
-Ram: 8GB
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
its trying to load its own lwjgl, which wont work on pojav, because pojav is already using its custom one for the game to even work on android, hence why it cannot be replaced (the game would not work anyway with their lwjgl)
