### ISSUE TITLE
A humble request

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5196]
### Is this request related to a bug?

Can u give me a build of old zink from collabora Ltd company . Pls pls pls 🥺🥺🥺🥺🥺🥺 pls

**Comment by GaucovyAero** [comment]
no but this fork has it https://github.com/SolDev69/SolCraftLauncher/actions

**Comment by Proaman7603** [comment]
Bro there are many builds which one I  should download?

**Comment by Proaman7603** [comment]
https://github.com/SolDev69/SolCraftLauncher/actions/runs/7833759571 is this will work pls reply

**Comment by SolDev69** [comment]
> https://github.com/SolDev69/SolCraftLauncher/actions/runs/7833759571 is this will work pls reply

https://github.com/SolDev69/SolCraftLauncher/actions/runs/8115754514 latest stable build
