### ISSUE TITLE
[BUG] When im in the folder it does show the files( i have hidden files on as well and it still does not work).

### ISSUE THREAD

**Issue by Idle34coder** [PojavLauncherTeam/PojavLauncher#5197]
### Describe the bug

Basicallywhen I go to the folder to add contorls or anything it does not show the contorlls folder and the .minecraft folder.  I have show hidden files on as well

### The log file and images/videos

![Screenshot_20240304_093702_ZArchiver](https://github.com/PojavLauncherTeam/PojavLauncher/assets/122610162/689e47b3-8f53-499a-868a-8572e3eb56ed)

### Steps To Reproduce

```markdown
To show files
```

### Expected Behavior

To show the foldets

### Platform

```markdown
- Device model: SM-G781U
- CPU architecture: idk
- Android version: 13
- PojavLauncher version: google play store
```

**Comment by GaucovyAero** [comment]
android has recently brutally restricted access to these folders, use activity launcher from play store to access it via the default files activity

**Comment by Idle34coder** [comment]
Where can I find that folder
