### ISSUE TITLE
question: how do I install 1.5.2 optifine

### ISSUE THREAD

**Issue by vyevillcie** [PojavLauncherTeam/PojavLauncher#5199]
### Describe the bug

I was trying to get 1.5.2 optifine to work but I need help with the modifying the .json to stop the launcher from redownloading the .jar file

### The log file and images/videos

i don't think you need this 

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. then it will redownload the file
```

### Expected Behavior

I expect the launcher to not redownload the .jar file

### Platform

```markdown
- Device model: SM-T295
- CPU architecture: arm64
- Android version: Android 11
- PojavLauncher version: latest playstore
```

**Comment by GaucovyAero** [comment]
https://pojavlauncherteam.github.io/CUSTOM-MC.html

be sure to use rar or something else for modifying your jar as mix might corrupt it

**Comment by GaucovyAero** [comment]
oh and mix is free, just click on the links, the play store thing is just the donation version
