### ISSUE TITLE
Error al usar optifine

### ISSUE THREAD

**Issue by pablo3240** [PojavLauncherTeam/PojavLauncher#52]
Cuando se instala optifine y entras al juego te da un error es el mismo cuando juegas otras versiones que la app no dejan espero que se solucione y que promete sea posible que se puedan mods

**Comment by khanhduytran0** [comment]
(Can you speak and understand English?)
(I used Google Translate to translate your report)
Can you copy error log or crash report ?

**Comment by abdo-A028** [comment]
> (Can you speak and understand English?)
> (I used Google Translate to translate your report)
> Can you copy error log or crash report ?

When optifine is installed and you enter the game it gives you an error is the same when you play other versions that the app does not leave I hope it is solved and that it promises that it is possible that mods can be

**Comment by abdo-A028** [comment]
@pablo3240 said this with French language

**Comment by khanhduytran0** [comment]
In the previous comment:
> Can you copy error log or crash report ?

**Comment by pablo3240** [comment]
> @ pablo3240 dijo esto con el idioma francés

Español

**Comment by khanhduytran0** [comment]
Is your device Huawei or other?

**Comment by pablo3240** [comment]
> ¿Su dispositivo es Huawei u otro?

if it is huawei android 7.0

**Comment by khanhduytran0** [comment]
So other Huawei devices in other reports getting error too. I thought some Huawei devices don't support OptiFine.

**Comment by pablo3240** [comment]
> Entonces, otros dispositivos Huawei en otros informes también reciben errores. Pensé que algunos dispositivos Huawei no son compatibles con OptiFine.

and it could be compatible later

**Comment by CloserPopcorn20** [comment]
But what about xiaomi? Is it not supports optifine too?

**Comment by khanhduytran0** [comment]
It were weird bugs. Some devices can be run.

**Comment by pablo3240** [comment]
> Eran bichos raros. Algunos dispositivos pueden ejecutarse.

and could it be fixed in the future?

**Comment by khanhduytran0** [comment]
I'm not sure for this.

**Comment by khanhduytran0** [comment]
Try v3
