### ISSUE TITLE
Application/game exited with code -1

### ISSUE THREAD

**Issue by Fuenzo4889** [PojavLauncherTeam/PojavLauncher#5200]
### Describe the bug

Whenever I try to play on fabric 1.20.4 with some optimization mods this error pops up when I launch the world or join any servers
Modlist:
![Screenshot_20240305_153712_FV File Explorer](https://github.com/PojavLauncherTeam/PojavLauncher/assets/155115863/aceb7836-afca-4b9c-9c00-ec79aa163bd1)

### The log file and images/videos

[latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14494467/latestlog.1.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Launch Fabric 1.20.4 with mods
3. Join the any world/server
4. Wait
```

### Expected Behavior

I expect that i join the world or server without any problems

### Platform

```markdown
- Device model: Samsung A73 5G
- CPU architecture: arm
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use patched sodium from pojav discord
