### ISSUE TITLE
[BUG] ANGLE does not work on waydroid x86_64

### ISSUE THREAD

**Issue by SolDev69** [PojavLauncherTeam/PojavLauncher#5202]
### Describe the bug

ANGLE fails to launch on waydroid

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14502484/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install waydroid on a linux PC with Intel UHD Graphics 630
2. Install PojavLauncher
3. Try running ANGLE on 1.20.4
4. Crash
```

### Expected Behavior

ANGLE should work on all 64bit architectures not just arm

### Platform

```markdown
- Device model: Waydroid x86_64 Device (Acer Nitro 5 running Arch Linux with latest waydroid and binder dkms)
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: edelweiss-20240219-195568c-v3_openjdk
```

### Anything else?

I won't fix this :)

**Comment by GaucovyAero** [comment]
send tombstone

**Comment by Enderteck** [comment]
Why in the world would you play Minecraft on Waydroid if you can install it outside ?

**Comment by GaucovyAero** [comment]
finding a bug isnt necessarily bad lol

**Comment by Enderteck** [comment]
I didn't say that though. Reporting bugs is always nice.

But the usecase it inexistant. 

Waydroid is a linux app that allows you to have an android subsytem. 

Why install pojav launcher in an Android subsystem instead of the Main OS ?

**Comment by SolDev69** [comment]
> send tombstone

I forgor I made this report, will send tomorrow

**Comment by GaucovyAero** [comment]
closing as not planned, angle will be removed later on
