### ISSUE TITLE
[BUG+WARN] User-Agent not have set `PojavLauncher/<version>` in User-Agent's Head

### ISSUE THREAD

**Issue by 8MiYile** [PojavLauncherTeam/PojavLauncher#5204]
### Is this request related to a bug?

Because our statistics found that PojavLauncher uses the BMCLAPI service and does not request according to the specifications, resulting in a large number of User-Agent requests starting with Dalvik in our statistical list.
I hope you can change your User-Agent, which will facilitate our statistics.

### Describe the request.

This is a `WARNING` !
https://github.com/MCLF-CN/docs/issues/2#issuecomment-1982754824

**Comment by zkitefly** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/5136

**Comment by 8MiYile** [comment]
@zkitefly Thx

**Comment by Mathias-Boulay** [comment]
Thanks for the report, we'll handle this soon enough. Is there a precise specification beyond a user agent that you would prefer ?

**Comment by 8MiYile** [comment]
user-agent's head must be launcher name and version
for example
```
PojavLauncher/1.145 (github.com/PojavLaunchet)
```
or just
```
PojavLauncher/1.145
```
Because we're just looking at the beginning of this argument

**Comment by Mathias-Boulay** [comment]
Hi there, for now the user agent will be named after pojavLauncher, without the version.

**Comment by 8MiYile** [comment]
@Mathias-Boulay I hope it's better to include the version number

**Comment by Mathias-Boulay** [comment]
if we include dynamic version number, your stats will be heavily spread out due to each commit being it s own version. We will do so at some point

**Comment by 8MiYile** [comment]
We have optimizations such as viewing only the client name or viewing the client name and version.

**Comment by GaucovyAero** [comment]
fixed in https://github.com/PojavLauncherTeam/PojavLauncher/commit/0163c6fedc69994b34ade3b9a611b765294251d7
