### ISSUE TITLE
[BUG] I can't import any .jar file

### ISSUE THREAD

**Issue by Cronnn** [PojavLauncherTeam/PojavLauncher#5205]
### Describe the bug

I'm trying to import .jar in my pojavlauncher when I tap the execute .jar file and select the file it shows " application/games exited with code 1 check latestlog.txt for more information " in every .jar file I'm going to put in-game it pops in thing and also I can't manually import file in zarchiver in android 13 you can't access android/data file without root.

### The log file and images/videos

![Screenshot_20240308-022147](https://github.com/PojavLauncherTeam/PojavLauncher/assets/162622654/d4d7d8a5-554f-41b6-8e45-7290a901581d)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14528485/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open pojavlauncher
2. Tap execute.jar file
3. Error pop up
```

### Expected Behavior

Fix this buggy I think 

### Platform

```markdown
- Device model: Infinix x6525
- CPU architecture: UMS9230 (T606)
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Nothing.

**Comment by GaucovyAero** [comment]
you cant execute mods lol, there is no import feature in pojav
to get access to the folder, use the marc files app from play store (it is basically just a shortcut to the vanilla android files app)
