### ISSUE TITLE
[QUESTION] data folder

### ISSUE THREAD

**Issue by RandomMinecraftGuy** [PojavLauncherTeam/PojavLauncher#5206]
### Describe the bug

not exactly a bug, but a question for my friend, im trying to install an shader for him

### The log file and images/videos

![1709822601698](https://github.com/PojavLauncherTeam/PojavLauncher/assets/157529512/90db9c92-2f61-4f8f-b9ec-196986247218)
![1709822523634](https://github.com/PojavLauncherTeam/PojavLauncher/assets/157529512/80c2c48d-cdb4-4cb0-907f-d388a74b05ed)

### Steps To Reproduce

```markdown
1. he goes into an file explorer
2. finds the android folder
3. click on data
4. finds the pojavlauncher folder
5. clicks on it and gets redirected into samsung default file manager
```

### Expected Behavior

open the actaul folder instead of getting redirected

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
you gotta click use this folder and it will bring you back to zarchiver
if that doesnt work, install the marc files app from play store to get access to the stock files app to get access to the pojav folder
