### ISSUE TITLE
[BUG] My Microsoft account shows up instead of my Minecraft account and my Microsoft account appears as a demo account

### ISSUE THREAD

**Issue by Rage65** [PojavLauncherTeam/PojavLauncher#5207]
### Describe the bug

I logged in to my email on pojav launcher and it showed my xbox live username (rage3976) instead of my Minecraft name. Note it did used to work. (Rage65) it also used to show my skin but now it only shows my Microsoft pic. Normally I would be fine with this but my Microsoft account shows up as a demo account so I can’t play the game.
![IMG_2395](https://github.com/PojavLauncherTeam/PojavLauncher/assets/142182455/c2cd2e27-f3ac-4a2e-b1d6-a55104b5f2bc)

### The log file and images/videos

I don’t have logs unfortunately 

### Steps To Reproduce

```markdown
Start pojav launcher with jit and log in with Microsoft
```

### Expected Behavior

It will show your Minecraft account name and skin and let you play the full game

### Platform

```markdown
- Device model: IPhone XR
- CPU architecture: arm 
- Android version: I’m on iOS 16.6.1 
- PojavLauncher version: latest (deep slate)
```

**Comment by Rage65** [comment]
After I wrote this I tryed singing in to Microsoft with GitHub and it asked if I was trying to sign in to Minecraft launcher and I said yes and the page closed and pojav launcher sad error 400 bad request.

**Comment by zkitefly** [comment]
Do you have Minecraft Java under your Microsoft account?

**Comment by GaucovyAero** [comment]
try logging into minecraft.net first and make sure your username is set up and stuff

**Comment by Rage65** [comment]
> Do you have Minecraft Java under your Microsoft account?

Yes it is the account I purchased it on

**Comment by GaucovyAero** [comment]
> > Do you have Minecraft Java under your Microsoft account?
> 
> Yes it is the account I purchased it on

make sure you did the login on the mc website and went to the username page, then try relogging into pojav

**Comment by Rage65** [comment]
I just got a new phone and it works fine so imma close this

**Comment by K0IDzZz** [comment]
for me i just logged in twice like even after the acc was added i logged in the second time and it just showed my skin and worked
