### ISSUE TITLE
[BUG] Creating world with datapack

### ISSUE THREAD

**Issue by BaNaN4Ik-STOP** [PojavLauncherTeam/PojavLauncher#5208]
### Describe the bug

I can't create world with datapack. I know about the datapack folder in saves directory, but if I insert datapack with structures in generated world, you give a crash! If I open the datapacks folder during creating a world, has been opened a "mcworld-(random numbers)" and give an error.

### The log file and images/videos

-

### Steps To Reproduce

```markdown
1. Start Pojavlauncher.
2. Create a world.
3. Open the datapack folder.
```

### Expected Behavior

I play on the vanilla 1.20.1 and above.

### Platform

```markdown
- Device model: Samsung Galaxy S9
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
send log

**Comment by GaucovyAero** [comment]
stale
