### ISSUE TITLE
[BUG] Modpack Galacticraft Pack Error

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5209]
### Describe the bug

Galacticraft Pack Crashes While Playing

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14545685/latestlog.txt)

### Steps To Reproduce

```markdown
Install Modpack Galacticraft Pack Version 1.12.2
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Edelweiss-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
remove galacticraft rpc mod
