### ISSUE TITLE
Where to throw mods? 

### ISSUE THREAD

**Issue by BigBotoDaddy** [PojavLauncherTeam/PojavLauncher#521]
Help please

**Comment by khanhduytran0** [comment]
`/sdcard/games/.minecraft/mods` (v3.3 release or older) or `/sdcard/games/PojavLauncher/.minecraft/mods` (v3.3.1)

**Comment by aqali1** [comment]
I can launch a world fine with Forge 1.12.2 installed but on 3.3.1
`/games/PojavLauncher/` is only the directories, nothing inside
can't find anywhere else where the data is
so I can add mods

**Comment by Google61** [comment]
Enable hidden folders in your file manager

**Comment by aqali1** [comment]
Thanks it worked.
