### ISSUE TITLE
[F-Req] Zink support for A750 gpu 

### ISSUE THREAD

**Issue by Dergrive** [PojavLauncherTeam/PojavLauncher#5210]
### Describe the request.

Add Zink render support for Adreno 750 gpu

**Comment by Vera-Firefly** [comment]
Remarkably, the PojavLauncher Team no response the request https://github.com/PojavLauncherTeam/PojavLauncher/pull/5148

**Comment by GAMERGENIX2** [comment]
Also for pvr

**Comment by Vera-Firefly** [comment]
> Also for pvr

What I want to know is, what are you waiting for?

**Comment by Vera-Firefly** [comment]
What I want to know is what are you waiting for?

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۴-۰۳-۰۰-۴۲-۵۵-۳۵۰_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/c0a39726-ab60-4bd1-b6d8-0f48f86829fd)
Vera firefly Published a version about support zink for adreno 750  and added new options like solDev69 published version about renderer
