### ISSUE TITLE
[BUG] can't join world in sodium 

### ISSUE THREAD

**Issue by U374** [PojavLauncherTeam/PojavLauncher#5211]
### Describe the bug

Hey team,
I am a pojav user and I can't join any world in Minecraft I am using sodium,mod menu, fabric API in mods and patched the sodium with this (file provided with discription) I can open Minecraft but I cant join any Minecraft world it says saving world and then my game crashed..........
**Plz fix it as soon as possible**
Thankyou 
Sodium patcher file:- 
[sodiumpatcher-1.0.1-SNAPSHOT.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/14548298/sodiumpatcher-1.0.1-SNAPSHOT.zip)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14548279/latestlog.txt)

### Steps To Reproduce

```markdown
1 start pojav
2 install fabric fabric API sodium sodium patcher mod menu (all for any Minecraft version 1.20.1,1.20.2,1.20.3,1.20.4)
3 patch sodium
4 click on play
5 join any world
6 **game crashed**
```

### Expected Behavior

I thought I will be in the Minecraft world but.........

### Platform

```markdown
- Device model: redmi 10A 220233L21
- CPU architecture: 8x ARM Cortex-A53 @ 2.00 GHz
- Android version: 11 RP1A.200720.011
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Silvigarabis** [comment]
See this <https://github.com/PojavLauncherTeam/PojavLauncher/issues/1948#issuecomment-1808858195>, Sodium is not supported.
If you sure you want to use sodium, try this modpack: [Haste](https://www.modrinth.com/modpack/plo). It has another patched version of Sodium, which can work with PojavLauncher.

**Comment by GaucovyAero** [comment]
keep in mind patched sodium is very slow, if you want more fps, use pojavoptimize from the pojav discord

**Comment by CrexAccount2** [comment]
My problem is I don't see any blocks on the world and it's doesn't give me a crash

**Comment by kivals728** [comment]
> keep in mind patched sodium is very slow, if you want more fps, use pojavoptimize from the pojav discord

Where can i get a link for the server?

**Comment by ghost** [comment]
> > keep in mind patched sodium is very slow, if you want more fps, use pojavoptimize from the pojav discord
> 
> Where can i get a link for the server?

No need to that. Try LTW renderer with sodium (really work)

**Comment by WalmartOwl** [comment]
> > > keep in mind patched sodium is very slow, if you want more fps, use pojavoptimize from the pojav discord
> > 
> > 
> > Where can i get a link for the server?
> 
> No need to that. Try LTW renderer with sodium (really work)

What is that renderer and how can i get it

**Comment by CrexAccount2** [comment]
> > > keep in mind patched sodium is very slow, if you want more fps, use pojavoptimize from the pojav discord
> > 
> > 
> > Where can i get a link for the server?
> 
> No need to that. Try LTW renderer with sodium (really work)

Are you sure it's will see all the blocks?
