### ISSUE TITLE
[F-Req] Add NeoForge Profiles Update

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5212]
### Is this request related to a bug?

![Screenshot_20240310_110748](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/fc058be4-5906-4b51-84e6-3de44969a142)

### Describe the request.

Please Add NeoForge Profiles In Pojav Launcher

### Anything else?

Please Fix Bug Forge 1.20.4

**Comment by ind33deda** [comment]
#5203 likely

**Comment by GaucovyAero** [comment]
duplicate of #4523
