### ISSUE TITLE
[F-Req] <Mesa LLVMpipe render>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#5213]
### Is this request related to a bug?

-

### Describe the request.

Added rendering of Mesa LLVMpipe.Mesa LLVMpipe supports OpenGL 4.5 and has Shader support.

### Anything else?

https://docs.mesa3d.org/drivers/llvmpipe.html

**Comment by khanhduytran0** [comment]
llvmpipe executes in CPU, not GPU. As a result, you’ll get nowhere near 5fps with shaders.
