### ISSUE TITLE
[BUG] <shaders>

### ISSUE THREAD

**Issue by Cronnn** [PojavLauncherTeam/PojavLauncher#5214]
### Describe the bug

Shaders don't work when I'm joining in world or server when I'm joining it stuck in loading screen

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14548929/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open pojavlauncher
2. Go to setting select and enable shader
3. Go to world and play
```

### Expected Behavior

Don't know

### Platform

```markdown
- Device model: Infinix x6525
- CPU architecture: UMS9230 (T606)
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Nothing

**Comment by GaucovyAero** [comment]
you gotta use zink

**Comment by Cronnn** [comment]
Do you have the link? Of zinkyou?

**Comment by GaucovyAero** [comment]
> Do you have the link? Of zinkyou?

what? its in the launcher already

**Comment by Cronnn** [comment]
I switch my renderer to zink and now this happened ( stuck in red help )
![Screenshot_20240311-132341](https://github.com/PojavLauncherTeam/PojavLauncher/assets/162622654/b0c6f4a1-26d1-4d6a-9180-8e985b07c555)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14553913/latestlog.txt)

**Comment by Bel69420** [comment]
It seems like you have borked VK driver on your GPU

**Comment by Bel69420** [comment]
Sorry but this is unfixable

**Comment by Bel69420** [comment]
What's your GPU though.

**Comment by Cronnn** [comment]
GPU: Mali-G57 MP1 @650 MHz

By resetting the app does this work and also once I reset the app do I need to use the zink or not? I mean I'll reset the app and back to normal?

**Comment by Cronnn** [comment]
I'll just switch my randerer if it's not gonna work and also what kind of shaders does my phone support?

**Comment by Bel69420** [comment]
Yeah, your phone manufacturer uses a broken vk driver.

**Comment by Bel69420** [comment]
That's why you can't run zink

**Comment by Cronnn** [comment]
Do you know any kind of shaders that support my phone?

**Comment by GaucovyAero** [comment]
> I'll just switch my randerer if it's not gonna work and also what kind of shaders does my phone support?

most probably only some shaders on virgl on sol's fork (solcraftlauncher) at maybe 5-15fps
