### ISSUE TITLE
Orinthe Project Support [AKA Adding Orinthe To LauncherProfiles (best you read the desc)]

### ISSUE THREAD

**Issue by VloxyGG** [PojavLauncherTeam/PojavLauncher#5215]
### Is this request related to a bug?

It maybe loosely tied to the former quilt issue but it is not what seems it be the case here.

### Describe the request.

Orinthe Project is a project that forks both fabric and quilt to older versions (pre-1.15.2 [including early beta to indev]).
However when installing it using vanilla launcher format, it would create a blank jar file which can't be launched....
It would be best adding it to the launcher as we already know how tedious quilt already was to install....

### Anything else?

It is better than the solution "just use a pc"

**Comment by GaucovyAero** [comment]
this certainly wont be integrated into the launcher but i suggest creating a support ticket on the pojav discord and there are people that have got fabric running on older versions of mc that can help you
