### ISSUE TITLE
[BUG] Multiplayer Connection throws an Error

### ISSUE THREAD

**Issue by Sacki666** [PojavLauncherTeam/PojavLauncher#5217]
### Describe the bug

If I try to connect to a server with a long address, the client runs to an error like
Connection Lost

Internal Exception: io.netty.handler.codec.DecoderExceprion: java.lang.IndexOutOfBoundsException: Index 26 out of bounds for length 10

Back to Server List

The address I entered is simmilar to "thisisaverylongserveradress.aternos.me"

### The log file and images/videos

![WhatsApp Bild 2024-03-11 um 14 06 56_4d10ebc7](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78081859/0c1da348-33dd-400d-b628-0941b2547aa1)

### Steps To Reproduce

```markdown
1. Start PoJavLouncher
2. Choose 1.20.4 Profile
3. click on Multiplayer
4. Choose the Server
5. Click "Join Server"
6. Error
```

### Expected Behavior

Connecting to the choosen server

### Platform

```markdown
- Device model: Oukitel OT5
- CPU architecture: 
- Android version: 13
- PojavLauncher version: current from PlayStore (28.09.2023)
```

**Comment by Mathias-Boulay** [comment]
@Sacki666 Thanks for reaching out !
To investigate, a log would be nice. Furthermore, providing us a server with an address that has this issue would be even better.

You can contact us on the pojav discord if you want to whitelist the server for only the devs

**Comment by Sacki666** [comment]
Hi Mathias,

 

where can I find the requested log?

Unfortubnaly, the server is not my server, so I cannot whitelist you on the server settings. But it is possible to register you own free server at aternos.org and create it with a long name, so the address will be as long as the one I tried to play on.

 

Best regards

Matthias

 

Von: Mathias Boulay ***@***.***> 
Gesendet: Montag, 25. März 2024 19:10
An: PojavLauncherTeam/PojavLauncher ***@***.***>
Cc: Sacki666 ***@***.***>; Mention ***@***.***>
Betreff: Re: [PojavLauncherTeam/PojavLauncher] [BUG] Multiplayer Connection throws an Error (Issue #5217)

 

@Sacki666 <https://github.com/Sacki666>  Thanks for reaching out !
To investigate, a log would be nice. Furthermore, providing us a server with an address that has this issue would be even better.

You can contact us on the pojav discord if you want to whitelist the server for only the devs

**Comment by GaucovyAero** [comment]
/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt 
or click the share log file button

**Comment by Sacki666** [comment]
While I was trying to reproduce the problem to create the requested log, this time everything worked fine. Maybe it was a problem on my local networtk (but everything else worked fine) or a problem caused by the provider aternos.

 

Sorry for wasting your time.

 

Greetings

Matthias

 

Von: GaucovyAero ***@***.***> 
Gesendet: Samstag, 30. März 2024 14:13
An: PojavLauncherTeam/PojavLauncher ***@***.***>
Cc: Sacki666 ***@***.***>; Mention ***@***.***>
Betreff: Re: [PojavLauncherTeam/PojavLauncher] [BUG] Multiplayer Connection throws an Error (Issue #5217)

 

/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt
or click the share log file button
