### ISSUE TITLE
[BUG] Modpack Create Live 4 Error

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5219]
### Describe the bug

Modpack Create Live 4 Crash Code 1 When Entering the World

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14566040/latestlog.txt)

### Steps To Reproduce

```markdown
Install Modpack Create Live 4 Version 1.19.2
```

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

There isn't any

**Comment by GaucovyAero** [comment]
remove xaeros minimap and replace it with journeymap or something else
