### ISSUE TITLE
Hello, two question? How do we got jre8 in pojavlauncher? Second, how do we check if we are using arm64 or something like that?

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#522]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
> How do we got jre8 in pojavlauncher?

Just install 70mb APK.

> Second, how do we check if we are using arm64 or something like that? 

You don't need take care of architecture, 70mb APK will do the rest to install compatible java.
