### ISSUE TITLE
[BUG] Black screen in forge 1.12.2

### ISSUE THREAD

**Issue by TechD1** [PojavLauncherTeam/PojavLauncher#5222]
### Describe the bug

I need some mods to make machinima which are only available in 1.12.2, there is no problem after installing the forge version, but after applying the mods I need, after starting, the screen goes black.  These are the mods: Blockbuster, aperture, chameleon, metamorph and mclib.

### The log file and images/videos

![2024_03_12_21 02 35](https://github.com/PojavLauncherTeam/PojavLauncher/assets/163214610/9d3b60e9-8ef2-4aaf-981d-9c419427fd59)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14580187/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Press play
3. Run
```

### Expected Behavior

I expect a functional sistem.

### Platform

```markdown
- Device model: Samsung A03 core
- CPU architecture: 8x arm ou armv8l (I don't know which of the two)
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Please, help me.

**Comment by GaucovyAero** [comment]
no errors, you gotta figure this out yourself
