### ISSUE TITLE
[BUG] <mouse inverted

### ISSUE THREAD

**Issue by wirrrrrrr** [PojavLauncherTeam/PojavLauncher#5223]
### Describe the bug

How to fix inverted mouse pls i already turn off mouse inverted in settings but its doesnt work

### The log file and images/videos

Idonthavr

### Steps To Reproduce

```markdown
E
```

### Expected Behavior

E

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
invalid issue, fill the template and send a video

**Comment by GaucovyAero** [comment]
stale
