### ISSUE TITLE
[BUG] Skin not showing

### ISSUE THREAD

**Issue by BaconHairisRed** [PojavLauncherTeam/PojavLauncher#5225]
### Describe the bug

Is this a bug because I changed my skin in Minecraft.net Website but it didn't show up the Account skin when I logged in the PojavLauncher even if I joined a World or Server it still didn't show up but I think its visible or showing up to everyone

### The log file and images/videos

![Screenshot_20240313-204238](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161017880/d5b60d9e-82b3-4b5e-babb-62e5a3129958)
![Screenshot_20240313-204431](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161017880/ff2a83d6-dbfe-42f1-b86a-16b3bbfd59e3)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Log in to Microsoft/Minecraft Account
```

### Expected Behavior

My skin will show up in the launcher and inside the game

### Platform

```markdown
- Device model: Infinix Hot 30i 
- CPU architecture: 
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try waiting 24 hours
