### ISSUE TITLE
[BUG] <código 17 forge>

### ISSUE THREAD

**Issue by Legna1104** [PojavLauncherTeam/PojavLauncher#5228]
### Describe the bug

pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-mappings.txt
Sanitize:   false
Format:     TSRG
Skip:       false
Initialization timed out!
No se instala el forge me saca

### The log file and images/videos

![Screenshot_2024-03-13-21-44-48-994_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/163371234/ac9ceba0-b324-49ed-8bba-ab264e13964e)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/163371234/4a537bd0-f3c7-41dd-98f1-3f75fe4a6239

### Steps To Reproduce

```markdown
Entro al pojavlauncher presionó para crear un perfil de forge en la versión 1.20.1 de ahí carga hasta ahí y se cierra
```

### Expected Behavior

Solo espero poder instalar el forge correctamente 

### Platform

```markdown
- Device model:redminote8
- CPU architecture: arm64-v8a
- Android version: 11
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Nada mas, espero su pronta respuesta

**Comment by GaucovyAero** [comment]
use java 8

**Comment by Legna1104** [comment]
Porque no estar previsto?

**Comment by Cristianxd13** [comment]
Me pasa lo mismo

**Comment by tekoraik** [comment]
Hola, a mí me ha funcionado descargando el instalador de forge y ejecutando en pojav la opción de Execute jar file.

**Comment by matiasde098** [comment]
la solucion es facil, dale mas memoria de seguro lo tienes al minimo xd
