### ISSUE TITLE
[BUG] Crashing when trying to launch minecraft in general

### ISSUE THREAD

**Issue by Blobanium** [PojavLauncherTeam/PojavLauncher#523]
**Describe the bug**
So i launch minecraft and it crashes with a JavaIOE Exception.

**To Reproduce**
1. Start PojavLauncher
2. launch 1.16.4
3. crash

**Expected behavior**
I expected minecraft to start normally

**Screenshots**
![Screenshot_20201220-150505.png](https://user-images.githubusercontent.com/45613796/102726613-0ab47d00-42d5-11eb-85a0-74a4a8646eeb.png)

**Platform:**
 - Device Model: ASUS Zenfone V
 - CPU architecture: aarch64 (for some reason its running aarch32(i used boats runtime)
 - Android Version: Android 8 (oreo)

for some reason Android doesnt want me to attach a file so i really cant upload a crash log, i think i can try to upload it using it via my laptop

**Comment by dashboarder** [comment]
Use https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/434513287

**Comment by khanhduytran0** [comment]
Use https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/434513287

**Comment by Blobanium** [comment]
ok that seemed to fix the issue
