### ISSUE TITLE
[BUG] language crash

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5233]
### Describe the bug

In version edelweiss-20240315 writes (DO NOT USE. Feat[launcher]: start implementing custom JVM launcher) of pojav. In english language not have any problem but i turn off (force language to English) game crash in old version it not have any problem but now it crash

https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/8db6dbfb-ed80-4dc3-9de2-e4edbdea25c8

And latest log
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14615587/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14615588/latestlog.txt)

### Steps To Reproduce

```markdown
1:start launcher
2:turn off (force language to english)
3:exit launcher
4:start again launcher
5:crash
```

### Expected Behavior

.

### Platform

```markdown
- Device model: xiaomi poco f5 256gb/12gb ram
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20240315
```

### Anything else?

Add vbo option in launcher setting

**Comment by GaucovyAero** [comment]
do not use

**Comment by ghost** [comment]
The version of pojav
