### ISSUE TITLE
[BUG] 1.20.4 forge crashes even without mods

### ISSUE THREAD

**Issue by GeoTreeTT** [PojavLauncherTeam/PojavLauncher#5234]
### Describe the bug

Pojav crashed upon launch despite having zero mods installed showing me code 1 error. I've reinstalled it fresh and it still haven't fix the issue. Somehow there are no crashing problem on other lower versions below MC 1.19. And works fine when launching it on optifine instead of Forge. 

I've tried setting it Java runtime to jre17 and java 1.8, and tried setting video render to every options and none of it fixes the issue. I've tried installing lower versions of forge and still nothing.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14616265/latestlog.txt)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/163540599/9f08334a-f2bb-427c-9abe-29a5d5616983

### Steps To Reproduce

```markdown
1. Start launcher
2. Install forge 
3. Press play
```

### Expected Behavior

I expect forge to start processing and start Minecraft 

### Platform

```markdown
- Device model: Samsung Tab S8
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

N/A

**Comment by Dilen0001** [comment]
.

**Comment by sa1672ndo** [comment]
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/87911255/c14498b9-d981-437c-a825-53038ccc41cb)

**Comment by GeoTreeTT** [comment]
> ![image](https://private-user-images.githubusercontent.com/87911255/313244452-c14498b9-d981-437c-a825-53038ccc41cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTkzMjQsIm5iZiI6MTcxMDUxOTAyNCwicGF0aCI6Ii84NzkxMTI1NS8zMTMyNDQ0NTItYzE0NDk4YjktZDk4MS00MzdjLWE4MjUtNTMwMzhjY2M0MWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE2MTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYmFmNzNiZjA1NDI2OWM3YzU5MzBhMWRiNTJmMmUzNzdlZjQwMmE5OWY3ZjI4MTdjZTIwMzk1OGYxMzg2NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-wsmhaJ_JuApzTfS4Ta25wkWmEGwpnR3DU2TzE_4Lpc)

That's not the reason it crashed. Tried to lower the ram allocation just to make sure but the crash still presist.
Also currently I'm using Fabric loader with sodium and even with the same ram configuration it doesn't crash so its not the issue.

**Comment by GaucovyAero** [comment]
your device doesnt seem to work with zink

**Comment by GeoTreeTT** [comment]
> your device doesnt seem to work with zink

I've already said I tried all renderer and it still crashes. And I've used zink before with lower versions of Minecraft with forge and there was no problem.

**Comment by GaucovyAero** [comment]
> > your device doesnt seem to work with zink
> 
> I've already said I tried all renderer and it still crashes. And I've used zink before with lower versions of Minecraft with forge and there was no problem.

send log with no pojav setting changes (gl4es)

**Comment by Bel69420** [comment]
Well @GaucovyAero , it managed to uses Turnip Driver but the renderer dies

**Comment by Bel69420** [comment]
I'm not sure why it dies

**Comment by GeoTreeTT** [comment]
> > > your device doesnt seem to work with zink
> > 
> > 
> > I've already said I tried all renderer and it still crashes. And I've used zink before with lower versions of Minecraft with forge and there was no problem.
> 
> send log with no pojav setting changes (gl4es)
 

Here
[latestlog(2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14627076/latestlog.2.txt)
