### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Seilcommand** [PojavLauncherTeam/PojavLauncher#5236]
### Describe the bug

When starting Minecraft 1.7.10 Forge,the game crashes.

### The log file and images/videos

-------- beginning with launcher debug Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk Info: Architecture: arm64 Info: Device model: samsung SM-A202F Info: API version: 30 Info: Selected Minecraft version: 1.7.10-Forge10.13.4.1614-1.7.10 Info: Custom Java arguments: "" Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache Added custom env: AWTSTUB_WIDTH=1502 Added custom env: FORCE_VSYNC=false Added custom env: POJAV_NATIVEDIR=/data/app/~~Hj0_TJMromHmsUVSKimdsA==/net.kdt.pojavlaunch-Cl-qUuHIYq-5yJWrYH-wcg==/lib/arm64 Added custom env: REGAL_GL_VERSION=4.5 Added custom env: REGAL_GL_VENDOR=Android Added custom env: LIBGL_MIPMAP=3 Added custom env: allow_higher_compat_version=true Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin Added custom env: LIBGL_NOINTOVLHACK=1 Added custom env: force_glsl_extensions_warn=true Added custom env: LIBGL_NORMALIZE=1 Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~Hj0_TJMromHmsUVSKimdsA==/net.kdt.pojavlaunch-Cl-qUuHIYq-5yJWrYH-wcg==/lib/arm64 Added custom env: LIBGL_NOERROR=1 Added custom env: POJAV_RENDERER=opengles2 Added custom env: LIBGL_ES=2 Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink Added custom env: MESA_GLSL_VERSION_OVERRIDE=460 Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal Added custom env: MESA_GL_VERSION_OVERRIDE=4.6 --------- beginning of system Added custom env: allow_glsl_extension_directive_midshader=true Added custom env: REGAL_GL_RENDERER=Regal Added custom env: AWTSTUB_HEIGHT=720 Initialising gl4es v1.1.5 built on Sep 27 2023 17:42:09 Using GLES 2.0 backend loaded: libGLESv2.so loaded: libEGL.so Using GLES 2.0 backend Hardware Full NPOT detected and used Extension GL_EXT_blend_minmax detected and used FBO are in core, and so used PointSprite are in core, and so used CubeMap are in core, and so used BlendColor is in core, and so used Blend Subtract is in core, and so used Blend Function and Equation Separation is in core, and so used Texture Mirrored Repeat is in core, and so used Extension GL_OES_mapbuffer detected Extension GL_OES_element_index_uint detected and used Extension GL_OES_packed_depth_stencil detected and used Extension GL_OES_depth24 detected and used Extension GL_OES_rgb8_rgba8 detected and used Extension GL_EXT_texture_format_BGRA8888 detected and used Extension GL_OES_depth_texture detected and used Extension GL_OES_texture_stencil8 detected and used Extension GL_EXT_texture_rg detected and used Extension GL_EXT_color_buffer_float detected and used Extension GL_EXT_color_buffer_half_float detected and used high precision float in fragment shader available and used Max vertex attrib: 16 Extension GL_OES_standard_derivatives detected and used Extension GL_ARM_shader_framebuffer_fetch detected and used Extension GL_OES_get_program_binary detected and used Number of supported Program Binary Format: 1 Max texture size: 8192 Max Varying Vector: 31 Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6 Hardware vendor is ARM GLSL 300 es supported GLSL 310 es supported and used GLSL 320 es supported Max Color Attachments: 4 / Draw buffers: 4 sRGB surface supported EGLImage to Texture2D supported EGLImage to RenderBuffer supported ignore MipMap glGetError() always return GL_NOERROR Targeting OpenGL 2.1 No hack in shader converter to define overloaded function with int Not trying to batch small subsequent glDrawXXXX try to use VBO glXMakeCurrent FBO workaround enabled FBO workaround for using binded texture enabled Force texture for Attachment color0 on FBO Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done Force normals to be normalized on FPE shaders glX Will try to recycle EGL Surface Current folder is:/ --------- beginning of main I/jrelog ( 1606): dlopen libgl4es_114.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success I/jrelog ( 1606): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success I/jrelog ( 1606): dlopen /d ata/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavla unch/runtimes/Internal/lib/aarch64/libfontmanager.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success I/jrelog ( 1606): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success I/jrelog ( 1606): dlopen /data/app/~~Hj0_TJMromHmsUVSKimdsA==/net.kdt.pojavlaunch-Cl-qUuHIYq-5yJWrYH-wcg==/lib/arm64/libopenal.so success I/jrelog ( 1606): Done processing args I/jrelog ( 1606): Found JLI lib I/jrelog ( 1606): Calling JLI_Launch OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes I/jrelog ( 1852): dlopen libxhook.so success 2024-03-15 20:14:24,921 ERROR appender Console has no parameter that matches element Policies [20:14:25] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker [20:14:25] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker [20:14:25] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker [20:14:25] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading [20:14:25] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_392-internal, running on Linux:aarch64:Android-11, installed at /data/user/0/net.kdt.pojavlaunch/runtimes/Internal [20:14:26] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 15 more [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 17 more [20:14:26] [main/ERROR]: An error occurred trying to configure the minecraft home at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/./1.7.10 for Forge Mod Loader java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) ~[NotEnoughItems-1.7.10-1.0.5.120-universal.jar:?] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_392-internal] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal] 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_392-internal] 	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_392-internal] 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?] 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?] 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?] 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal] 	... 15 more Caused by: java.lang.NullPointerException 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_392-internal] 	... 15 more Exception in thread "main" [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 15 more [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) [20:14:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 17 more Java Exit code: 1 I/jrelog ( 1606): Going to free args I/jrelog ( 1606): Free done 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14619915/latestlog.txt)

### Steps To Reproduce

```markdown
1.Install Minecraft 1.7.10 Forge
2.Start it
3.Wait
```

### Expected Behavior

Well I expected it to boot

### Platform

```markdown
- Device model: Samsung Galaxy A20e 
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
duplicate issue, unrelated to pojav, install codechickenlib into .minecraft/mods/1.7.10
