### ISSUE TITLE
[BUG] Forge 1.20.4

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5237]
### Describe the bug

Plis Fix Bug 1.20.4

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14626533/latestlog.txt)

![Screenshot_20240317_143108](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/3706bcfa-6b8f-4286-87f5-6ac643553e29)

### Steps To Reproduce

```markdown
1. Install Minecraft Vanilla 1.20.4
2. Install Forge 1.20.4
```

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

There isn't any

**Comment by GaucovyAero** [comment]
duplicate issue

**Comment by Dilen0001** [comment]
When I Play Forge 1.20.4 In Fold Craft Launcher It Doesn't Come Out Code 1

**Comment by ind33deda** [comment]
> When I Play Forge 1.20.4 In Fold Craft Launcher It Doesn't Come Out Code 1

not an PojavLauncher related
