### ISSUE TITLE
[BUG] Game crashes using the better mc integration pack

### ISSUE THREAD

**Issue by 112211ss** [PojavLauncherTeam/PojavLauncher#5238]
### Describe the bug

Game crashes using the better mc integration pack

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14626596/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download the better mc package 
2. Start the game 
3. Crash the game
```

### Expected Behavior

The game is running normally

### Platform

```markdown
Device model: redmi pad
CPU architecture: arm64
Android version: 14
PojavLauncher version: edelweiss-20240219-195568c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try reading the log, it says bclib might be the issue
make sure you pinpoint a specific mod (not modpack) when creating an issue
