### ISSUE TITLE
[BUG] 3d Shareware won't work is this a prank? because I want to play 3d Shareware minecraft.

### ISSUE THREAD

**Issue by Ezekiel2011** [PojavLauncherTeam/PojavLauncher#524]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
3D Shareware won't work, as it uses some unsupported shader.

**Comment by manolis07** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Start PojavLauncher
>    ...
> 
> **Expected behavior**
> I expected ...
> 
> **Screenshots**
> 
> **Platform:**
> 
> * Device Model [e.g. Mi 8 Pro 8/128]
> * CPU architecture [e.g. aarch64]
> * Android Version [e.g. 10]
> 
> Additional context

I can't help you with the problem but I just want to say we have the same phone and also Search how to install shaders on Minecraft java in Android and a video should pop up that show how to install Minecraft java and also I download to a shader that works . I hope I did something

**Comment by khanhduytran0** [comment]
You need some modifications to shader to get it work.
Modified shader resource pack: https://cdn.discordapp.com/attachments/782924421177278464/809926216723202052/3DShareware4Pojav_resourcepack.zip
Extract and put to `/sdcard/games/PojavLauncher/.minecraft/resourcepacks` folder.
On options.txt modify
```
resourcePacks: ["vanilla", "3DShareware4Pojav"]
```
Also, if you are getting a dirt only screen when play **3D Shareware v1.34**, switch to GL4ES 1.1.5. Add `-Dorg.lwjgl.opengl.libname=libgl4es_115.so` to JVM arguments to fix it.

**Comment by lunastarlun73** [comment]
> You need some modifications to shader to get it work.
> Modified shader resource pack: https://cdn.discordapp.com/attachments/782924421177278464/809926216723202052/3DShareware4Pojav_resourcepack.zip
> Extract and put to `/sdcard/games/PojavLauncher/.minecraft/resourcepacks` folder.
> On options.txt modify
> ```
> resourcePacks: ["vanilla", "3DShareware4Pojav"]
> ```
> Also, if you are getting a dirt only screen when play **3D Shareware v1.34**, switch to GL4ES 1.1.5. Add `-Dorg.lwjgl.opengl.libname=libgl4es_115.so` to JVM arguments to fix it.

the link doesn't work anymore
