### ISSUE TITLE
[BUG] Java Exit Code: 1

### ISSUE THREAD

**Issue by The1NPC** [PojavLauncherTeam/PojavLauncher#5240]
### Describe the bug

When Minecraft first loads (the first time the red display appears), it immediately forces close.

Java Runtime: Default
Renderer: ANGLE (Vulkan)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14628210/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Start Minecraft
```

### Expected Behavior

Running Fine

### Platform

```markdown
- Device model: Redmi Note 10
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
duplicate issue, forge 49.0.x doesnt work
