### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Chris1235057** [PojavLauncherTeam/PojavLauncher#5241]
### Describe the bug

I tryna install a jar file but it never works

### The log file and images/videos

When I'm tryna install a jar it kicks me out

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

It should be installed without any problems

### Platform

```markdown
- Device model: Chromebook
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
send log

**Comment by Chris1235057** [comment]
wyd

**Comment by Chris1235057** [comment]
do you need a Java license

**Comment by GaucovyAero** [comment]
stale, closing, you havent sent the log, the file path is in the issue template
