### ISSUE TITLE
Application game exited with code -1 

### ISSUE THREAD

**Issue by RonitNarkhede** [PojavLauncherTeam/PojavLauncher#5242]
### Describe the bug

My game is getting the error when I play ninshu origins mod of 1.19.2

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14649202/latestlog.txt)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I want to play that mod

### Platform

```markdown
- Device model: Samsung galaxy A03 y
- CPU architecture: armv81 
- Android version:13 
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
```
net.minecraft.client.renderer.texture.StitcherException: Unable to fit: operation_otsutsuki:painting/i_want_you - size: 457x600 - Maybe try a lower resolution resourcepack?
```

**Comment by RonitNarkhede** [comment]
> ```
> net.minecraft.client.renderer.texture.StitcherException: Unable to fit: operation_otsutsuki:painting/i_want_you - size: 457x600 - Maybe try a lower resolution resourcepack?
> ```

So what are solutions for the problem can you please fix it

**Comment by GaucovyAero** [comment]
> > ```
> > net.minecraft.client.renderer.texture.StitcherException: Unable to fit: operation_otsutsuki:painting/i_want_you - size: 457x600 - Maybe try a lower resolution resourcepack?
> > ```
> 
> So what are solutions for the problem can you please fix it

the textures atlas is too big for minecraft to handle i think

**Comment by RonitNarkhede** [comment]
> > > ```
> > > net.minecraft.client.renderer.texture.StitcherException: Unable to fit: operation_otsutsuki:painting/i_want_you - size: 457x600 - Maybe try a lower resolution resourcepack?
> > > ```
> > 
> > 
> > So what are solutions for the problem can you please fix it
> 
> the textures atlas is too big for minecraft to handle i think

Is that mean I can't play the mod ninshu origins in pojavlauncher

**Comment by RonitNarkhede** [comment]
> > > > ```
> > > > net.minecraft.client.renderer.texture.StitcherException: Unable to fit: operation_otsutsuki:painting/i_want_you - size: 457x600 - Maybe try a lower resolution resourcepack?
> > > > ```
> > > 
> > > 
> > > So what are solutions for the problem can you please fix it
> > 
> > 
> > the textures atlas is too big for minecraft to handle i think
> 
> Is that mean I can't play the mod ninshu origins in pojavlauncher

Please bro fix it I had installed pojavlauncher to play that mod

**Comment by GaucovyAero** [comment]
its prolly not fixable
