### ISSUE TITLE
[BUG] Can't connect to Minecraft Server "play.mixelpixel.net"

### ISSUE THREAD

**Issue by mfilser** [PojavLauncherTeam/PojavLauncher#5243]
### Describe the bug

Hello,
I can't connect to the Minecraft Server "play.mixelpixel.net".
Other servers like hypixel.net are working perfectly.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14649821/latestlog.txt)

### Steps To Reproduce

```markdown
1. add Minecraft Server "hypixel.net".
2. join the Server "hypixel.net" -> success
3. add Minecraft Server "play.mixelpixel.net" to the Multiplayer Menu
4. try to join the Server "play.mixelpixel.net" -> failure (no connection possible)
```

### Expected Behavior

I want to join the MixelPixel Server "play.mixelpixel.net" with PojavLauncher

### Platform

```markdown
- Device model: Samsung S20
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I think MixelPixel Servers are using a SRV DNS records. Trying to add the IP and Port itself also doesn't work to connect to the Server, currently this addresses:

45.135.203.184:10000
45.135.203.184:10001
45.135.203.185:10002
45.135.203.185:10003

**Comment by GaucovyAero** [comment]
yeah the "anything else" part is whats the issue

**Comment by mfilser** [comment]
@GaucovyAero
Thank you for your comments.

What do you mean exactly with "anything else" part is the issue?

I added the Mixelpixel server with "ip:port" like '45.135.203.185:10002" (direct connection without using SRV DNS record), but I still can't connect. So I am not sure if this issue is related to a SRV problem.

**Comment by ghost** [comment]
probably srv problem

**Comment by mfilser** [comment]
@ind33deda 
If adding the Minecraft Server with it's Ip:Port, how could this be a srv problem?

I tried to connect to the server directly with "45.135.203.185:10002"

**Comment by ghost** [comment]
it wasn’t a server problem, probably the server is using dns srv which don’t work likely

**Comment by mfilser** [comment]
@ind33deda
As in my last post, I use ip connection (resolved the dns records manually) and no dns name, but can't still connect. The same ip address on Windows Minecraft works without any issues.
So SRV problems arent't an issue here.

**Comment by GaucovyAero** [comment]
closing as a duplicate of #4479
