### ISSUE TITLE
Blury display 

### ISSUE THREAD

**Issue by AwesomeDuo** [PojavLauncherTeam/PojavLauncher#5246]
### Describe the bug

Blury display in pojavlauncher even at 100% resolution 

### The log file and images/videos

Good

### Steps To Reproduce

```markdown
Good
```

### Expected Behavior

My device is good give 60+ fps

### Platform

```markdown
- Device model: M2006C3MI
- CPU architecture: 32BIT
- Android version: 10
- PojavLauncher version: LATEST
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
send a photo of it and try turning on/off alternate surface rendering

**Comment by GaucovyAero** [comment]
stale
