### ISSUE TITLE
[BUG] I own minecraft java but it still says my account is demo

### ISSUE THREAD

**Issue by Landor151** [PojavLauncherTeam/PojavLauncher#5247]
### Describe the bug

i think the title actually explained itI

### The log file and images/videos

I am on IOS so I don't know where to find it, but it does not give me errors so..

### Steps To Reproduce

```markdown
just by adding an account
```

### Expected Behavior

Being able to play mc with my legit account

### Platform

```markdown
- Device model: Iphone 12
- CPU architecture: A-15 i think
- Android version: ios 17
- PojavLauncher version: latest from this date
```

**Comment by ghost** [comment]
login into minecraft.net and went to username page, then try relogging it
