### ISSUE TITLE
[question] about java dcl

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5248]
### Describe the request.

Java dcl is on in default or off in pojav. It's necessary to know
![Screenshot_۲۰۲۴-۰۳-۲۱-۱۸-۲۶-۱۰-۷۶۵_com android settings-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/ba7a6229-4a0f-4e24-96ea-022b16977493)
(Enforce read only java dcl) is for enable java dcl and only read the java dcl without any code change and changes or in default java dcl is enable but this option just for disable code changing and changes in java dcl

### Anything else?

I found this option in app compatibility changes and i researched about java dcl it's can improve perfomance speed

**Comment by Mathias-Boulay** [comment]
Java DCL is for the main app, it wouldn't affect performance in game.
(https://kalpeshchandora12.medium.com/dynamic-code-loading-in-android-dea83ba3bc85)

**Comment by kasrarouhi** [comment]
Isn't dcl short for double checking looking?

**Comment by ghost** [comment]
Thank's a lot
