### ISSUE TITLE
App crushing when exporting a.jar.

### ISSUE THREAD

**Issue by pawfix** [PojavLauncherTeam/PojavLauncher#5250]
### Describe the bug

When I try to export literally any mod except optifine the app just crushes. When installing optifine the app won't crush. It would just say that optifine was installed successfully , but in log output there was no action except the window with installation confirmation.
I use newest forge for 1.20.1

### The log file and images/videos

Screenshot:
![Screenshot_20240323_110913_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/119623013/1aadb22b-07a8-4b93-a11e-fd8b423afe66)
Lastestlog for "x" mod:
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14731233/latest.log)

### Steps To Reproduce

```markdown
1. Start pojąć Launcher
2. Export.jar
3. Select "x" Mod
4. Watch log output
5. App crushes
```

### Expected Behavior

.jar being exported and showing in the modmenu

### Platform

```markdown
- Device model: samsung m12
- CPU architecture: 8x 2,00 GHz
- Android version: 11
- PojavLauncher version: newest in play store
```

**Comment by GaucovyAero** [comment]
mods are not executable, just as you do on pc, you have to put them into the mods folder
