### ISSUE TITLE
[BUG] a bug maybe??

### ISSUE THREAD

**Issue by Frostybtfindingscript** [PojavLauncherTeam/PojavLauncher#5251]
### Describe the bug

The log file and images/videos

I get this on my screen whenever i play on my downloaded modpacks, it always pops up "Waiting [A,B,X,O etc] button" i just want to play and have fun. 
![Screenshot_20240324-142058](https://github.com/PojavLauncherTeam/PojavLauncher/assets/100270583/0f4d2ca1-541a-438a-8f63-2dbbc2754590)

### 
  I didn't get one it just says "Waiting for A button"

### Steps To Reproduce

```markdown
Idk what i did but i just did these steps
1. Redownload pojavlauncher
2. Open pojavlauncher
3. Create a local account
4. Create new profile
5. Press "Modpacks"
6. Pick a 'modpack'
7. After downloading, i just tried to open it and waited and then i got the "Waiting for A(or any button that it says) Button".
```

### Expected Behavior

I expected it to open normally but it didn't and i was stuck here for a good amount of time and then restart the app and still the same.. i did also infact reset my phone.

### Platform

```markdown
- Device model: Infinix Hot40i 8-16/256G
- CPU architecture: octa-core Cortex-A75
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
pojav thinks you have a gamepad attached

**Comment by Frostybtfindingscript** [comment]
> pojav thinks you have a gamepad attached

Thanks.

**Comment by GaucovyAero** [comment]
no idea really, check your apps maybe?

**Comment by GaucovyAero** [comment]
stale issue
