### ISSUE TITLE
[BUG] bug crash error -1 

### ISSUE THREAD

**Issue by BrianRako** [PojavLauncherTeam/PojavLauncher#5253]
### Describe the bug

When joining a world have a crash error code -1

### The log file and images/videos

[latestlog (2).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14734984/latestlog.2.txt)

### Steps To Reproduce

```markdown
I just put mods on the folder, juste before joining à world 8n singleplayer it crash
```

### Expected Behavior

Joining à world

### Platform

```markdown
- Device model: samsung z fold 4
- CPU architecture: Qualcomm SM8475 Snapdragon 8+ Gen 1 (4 nm)
- Android version: 14
- PojavLauncher Version : latest one on play store
```

**Comment by GaucovyAero** [comment]
remove rubidium
