### ISSUE TITLE
[BUG] forge versions do not launch and will say exit code 1

### ISSUE THREAD

**Issue by SilentIncognito** [PojavLauncherTeam/PojavLauncher#5254]
### Describe the bug

the forge installers or forge clients dont work but the default 1.20.4 works alright when i try to launch any forge versions there will just be a message saying EXIT CODE 1 and when i followed the instructions based on my research on how to get rid of it , it still says the same thing. did i do something wrong? or something

### The log file and images/videos

[latestlog.txt](h
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14735554/latestlog.txt)

thats my log

and here is what i see when i launch every version of forge

![Screenshot_2024-03-24-21-15-10-83_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/164752758/9b59972d-a76f-4cb0-a662-eac7b22fd110)

### Steps To Reproduce

```markdown
1. launched forge client on pojav and saw the exit code 1
2. looked for tutorials on how to solve and followed it
3. it helped reset pojav but it still shows exit code 1.
```

### Expected Behavior

I thought by doing so would help me relaunch forge but every version i install just says exit code 1. maybe it was because i installed optifine but it was working fine for an entire day before it suddenly said exit code 1. and then i uninstalled it but it still said so until i reached a point where i was following tutorials on how to fix it and so on and so forth but every version of forge still says exit code 1. please help

### Platform

```markdown
- Device model: Realme Pad X
- CPU architecture: 
- Android version: 12
- PojavLauncher version: edelweis-20230928-9484d0c-v3_openjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
use forge 49.0.3

**Comment by GaucovyAero** [comment]
duplicate issue
