### ISSUE TITLE
[BUG] minecraft Crashes not launch

### ISSUE THREAD

**Issue by Rakib12345yb** [PojavLauncherTeam/PojavLauncher#5262]
### Describe the bug

i launch but log show minecraft Crashes

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14752231/latest.log)

### Steps To Reproduce

```markdown
check my log
```

### Expected Behavior

i expect is fix pojavlauncher developers

### Platform

```markdown
- Device model:SAMSUNG GALAXY A13 4G
- CPU architecture:Armeabi-v7a
- Android version:Android 14
- PojavLauncher version:Last google play store
- game version: fabric-loader-0.15.7.jar 1.20.4
```

**Comment by GaucovyAero** [comment]
remove sillyrendering

**Comment by Rakib12345yb** [comment]
> remove sillyrendering

what is??
is mod
