### ISSUE TITLE
[BUG] Forge crash with optifine.

### ISSUE THREAD

**Issue by BNaise** [PojavLauncherTeam/PojavLauncher#5265]
### Describe the bug

In the logs it shows Requested GL version 4.6 got version 0.0 I don't know what to do.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14766259/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Select 1.20.4 forge-49.0.31 (with optifine)
3.Play
4.Crash
```

### Expected Behavior

Its obvious.

### Platform

```markdown
- Device model: RMX3501
- CPU architecture: can't find
- Android version: 12
- PojavLauncher version: vedelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try putting 
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
into custom_env.txt, create the file in the same directory as latestlog.txt

**Comment by Bel69420** [comment]
@GaucovyAero what the, he's using gl4es. How's that will work if that's only for mesa renderer.

**Comment by GaucovyAero** [comment]
> @GaucovyAero what the, he's using gl4es. How's that will work if that's only for mesa renderer.

maybe that mod is checking for that specific variable and cant find it
