### ISSUE TITLE
[BUG] Can't start fabric with mod version on Pojav Launcher

### ISSUE THREAD

**Issue by Rakib12345yb** [PojavLauncherTeam/PojavLauncher#5266]
### Describe the bug

Can't start fabric-loader-0.15.7 with mods on Pojav Launcher

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14771700/latest.log)

### Steps To Reproduce

```markdown
check log
```

### Expected Behavior

I am Expected fix my problem 

### Platform

```markdown
- Device model: Samsung Galaxy A13 4G
- CPU architecture: Armeabi-v7a (32bit)
- Android version: Android 14
- PojavLauncher version: Last google play store version
```

**Comment by Rakib12345yb** [comment]
> ### Describe the bug
> Can't start fabric-loader-0.15.7 with mods on Pojav Launcher
> 
> ### The log file and images/videos
> [latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14771700/latest.log)
> 
> ### Steps To Reproduce
> ```
> check log
> ```
> 
> ### Expected Behavior
> I am Expected fix my problem
> 
> ### Platform
> ```
> - Device model: Samsung Galaxy A13 4G
> - CPU architecture: Armeabi-v7a (32bit)
> - Android version: Android 14
> - PojavLauncher version: Last google play store version
> ```
> 
> ### Anything else?
> _No response_

what is sillyrendering

**Comment by Rakib12345yb** [comment]
what is sillyrendering

**Comment by Rakib12345yb** [comment]
what is sillyrendering

**Comment by GaucovyAero** [comment]
its a mod
