### ISSUE TITLE
[BUG] Can't start fabric with mod version on Pojav Launcher

### ISSUE THREAD

**Issue by Rakib12345yb** [PojavLauncherTeam/PojavLauncher#5267]
### Describe the bug

Can't start fabric-loader-0.15.7 with mods on Pojav Launcher

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14773734/latest.log)

### Steps To Reproduce

```markdown
check log
```

### Expected Behavior

I am Expected fix my problem

### Platform

```markdown
- Device model: Samsung Galaxy A13 4G
- CPU architecture: Armeabi-v7a (32bit)
- Android version: Android 14
- PojavLauncher version: Last google play store version
```

**Comment by Rakib12345yb** [comment]
@GaucovyAero

**Comment by Rakib12345yb** [comment]
@GaucovyAero

**Comment by ghost** [comment]
Sodium isn't supported on PojavLauncher and you're using 32-bit ROM on an 64-bit SOC Android device

**Comment by GaucovyAero** [comment]
try removing notenoughcrashes

**Comment by Rakib12345yb** [comment]
again crashe
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14783692/latest.log)

**Comment by ghost** [comment]
Try removing sodium jar file in the mods folder

**Comment by Rakib12345yb** [comment]
> Try removing sodium jar file in the mods folder

again crashe
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14783877/latestlog.txt)

**Comment by ghost** [comment]
Probably you're using 32-bit android rom on an 64-bit SOC 🤦‍♂️

**Comment by Rakib12345yb** [comment]
> Probably you're using 32-bit android rom on an 64-bit SOC 🤦‍♂️

What is SOC??

**Comment by ghost** [comment]
> Probably you're using 32-bit android rom on an 64-bit SOC 🤦‍♂️
>
> What is SOC??
>

System-on-chip

>

**Comment by GaucovyAero** [comment]
> > Try removing sodium jar file in the mods folder
> 
> again crashe [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14783877/latestlog.txt)

remove carpet
