### ISSUE TITLE
[BUG] Exit code -1

### ISSUE THREAD

**Issue by bomboclot** [PojavLauncherTeam/PojavLauncher#5269]
### Describe the bug

When i start playing it suddenly kicks me off saying exit code -1

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14787989/latest.log)
[crash-2024-03-28_18.44.11-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14787993/crash-2024-03-28_18.44.11-client.txt)
![Screenshot_20240328_190144_com gbox android](https://github.com/PojavLauncherTeam/PojavLauncher/assets/157385004/4300bf61-f7ce-489e-b5e8-e5f805a8443b)

### Steps To Reproduce

```markdown
1. Download 1.20.4
2. Play
3. U get the exit code -1
```

### Expected Behavior

I excpect it to work normally

### Platform

```markdown
- Device model: HUAWEI nova 7 JEF-NX9
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk (from playstore)
```

### Anything else?

Also for more details i am in huawei and also downloaded it from gbox google playstore which is a thing to download apps in the playstore because huawei doesn't have one

**Comment by GaucovyAero** [comment]
it doesnt work because gbox doesnt seem to allow loading pojavexec
you dont have to use the play store at all, follow the github actions guide on the pojav wiki

**Comment by bomboclot** [comment]
> it doesnt work because gbox doesnt seem to allow loading pojavexec you dont have to use the play store at all, follow the github actions guide on the pojav wiki

omg it work i love u so much

![Screenshot_20240328_200821_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/157385004/ba697a36-e13a-4ef2-b192-438889caed59)
