### ISSUE TITLE
[BUG] Latest snapshot not playable without java 21

### ISSUE THREAD

**Issue by treefrog1109** [PojavLauncherTeam/PojavLauncher#5272]
### Describe the bug

Latest snapshot showing as invalid session in Realms tab. Patch 24w13a
edit: now it needs java 21 for patch 24w14a but Pojav doesnt have that available yet.

### The log file and images/videos

No Crash 

### Steps To Reproduce

```markdown
Start pojav with 24w13a snapshot and open realms.
```

### Expected Behavior

A connection to realms servers

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
send log

**Comment by ghost** [comment]
With premium account ore not?

**Comment by ghost** [comment]
probably you're using local accounts

**Comment by zkitefly** [comment]
now the 24w13a is not latest snapshot, what about 24w14a?

**Comment by ghost** [comment]
I used local account and premium account but i lost my premium account but if you don't use premium account minecraft realms showing invalid session but if you use premium account realms not showing invalid session.

**Comment by ghost** [comment]
🤦‍♂️ I think he lost my premium account

Vào Th 4, 3 thg 4, 2024 lúc 23:26 Kasraio ***@***.***> đã
viết:

**Comment by ghost** [comment]
Use easymc mod and tokens for enter or mcalts all is website . Easymc need mod for enter token to get premium account and mcalts give you Microsoft account for premium account for minecraft java and all it's work

**Comment by ghost** [comment]
But it’s illegal

Vào Th 4, 3 thg 4, 2024 lúc 23:29 Kasraio ***@***.***> đã
viết:

**Comment by kasrarouhi** [comment]
It's not my premium account in minecraft

**Comment by ghost** [comment]
Probably but not have any problem if you can't buy a premium account

**Comment by treefrog1109** [comment]
Im using a Microsoft account and now I can't run the latest 24w14a because it says I need java 21? How do I get that

**Comment by treefrog1109** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14858274/latestlog.txt)

**Comment by ghost** [comment]
Wait for the devs to add java 21 into pojavlauncher

Vào Th 5, 4 thg 4, 2024 lúc 03:34 treefrog1109 ***@***.***>
đã viết:

**Comment by ghost** [comment]
newer minecraft would requires java 21 and 64-bit system

**Comment by ghost** [comment]
Until Java 21 got added into PojavLauncher in the future

**Comment by Algiuxs** [comment]
Java 21 https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions?query=branch%3Abuildjre21
