### ISSUE TITLE
[BUG] <Crouch on exiting UI>

### ISSUE THREAD

**Issue by dualposition** [PojavLauncherTeam/PojavLauncher#5273]
### Describe the bug

i dont really have a precise description, it just crouches when i close an ui, this makes the "EmoteCraft" mod not work. and its kind of annoying when every time you close a UI, you have to press the crouch button

### The log file and images/videos

i dont rlly have images
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/159695210/91e1e7ff-619a-415a-b0a4-72aa781a8550)

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. get into a server or singleplayer world
3. open inventory
2. close inventory
```

### Expected Behavior

i expect it not to crouch whenever i close an ui

### Platform

```markdown
- Device model: oneplus nord 2 5G i think
- CPU architecture: i dont know 💀
- Android version: i dont know 💀
- PojavLauncher version: i dont know 💀
```

**Comment by dualposition** [comment]
i doubt this is going to get fixed, i dont have much info

**Comment by GaucovyAero** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/0d475b38-6881-49c9-9092-865cee7e24aa

this just simply doesnt happen lol, try changing your controlmap to see if it makes any difference

**Comment by dualposition** [comment]
whats a controlmap? and how do i change it?
it says on the crouch button SHIFT LEFT + UNKNOWN + UNKNOWN + UNKNOWN
and on the emotecraft button it says B + UNKNOWN + UNKNOWN + UNKNOWN

**Comment by dualposition** [comment]
wth, on my aternos server it crouches on exiting emotecraft ui, but on craftmc (p2w polish minecraft server) it doesnt, but it still crouches on exit inventory

**Comment by dualposition** [comment]
try 1.20.1, i only play on that version

**Comment by GaucovyAero** [comment]
> try 1.20.1, i only play on that version

can you record a video? im 100% sure its fine because otherwise there would be a ton of issues related to this

**Comment by dualposition** [comment]
i think that it only crouches in multiplayer ima go make a screen recording

**Comment by dualposition** [comment]
setting crouch to "Hold" fixed it
turns out toggle buttons when activated on, are holding. so theres no point of setting "Sneak" to "Toggle"
"Sneak" is set to toggle automatically (nvm it isnt) on pojavlauncher, which creates the bug. ima go to my phone to send the screen recording
so this bug is actually a minecraft bug, but usually happens on pojav, since its set to toggle by default.

> > try 1.20.1, i only play on that version
> 
> can you record a video? im 100% sure its fine because otherwise there would be a ton of issues related to this

**Comment by dualposition** [comment]
![Screenshot_2024-03-30-20-39-59-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/PojavLauncherTeam/PojavLauncher/assets/159695210/4d59dc0a-a6ea-4d97-af1e-bdbdc044a0e1)

**Comment by dualposition** [comment]
this video is too Try again
