### ISSUE TITLE
[BUG] (use system vulkan driver) option crash

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5275]
### Describe the bug

I will enable this (use system vulkan driver) option in zink render it's crash.but i disable this option game work finely maybe
It's support only for adreno 6xx and 5xx no for 7xx my adrene version is adreno 725

### The log file and images/videos

Video
https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/a246a3e8-afee-431e-9d3e-5745f6ae46df

Latest log (jvm arguments are not have any problem)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14798236/latestlog.txt)

### Steps To Reproduce

```markdown
1:open pojav launcher
2:enable (use system vulkan driver)
3:start game
4:crash
```

### Expected Behavior

I will disable this option game work finely maybe

### Platform

```markdown
- Device model: xiaomi poco f5 12/256G
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20240325
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
well obviously since your system driver aint open source and iirc is only vulkan 1.1, meanwhile zink needs 1.3
