### ISSUE TITLE
[BUG] Incognito mode when using Microsoft SwiftKey

### ISSUE THREAD

**Issue by Luiz0l** [PojavLauncherTeam/PojavLauncher#5276]
### Describe the bug

When using the Microsoft Swiftkey keyboard I have two problems:
1 - in versions 1.8 (1.8 - 1.8.9) when I press the "W" key, the screen becomes "miniature".
2 - For some reason, the keyboard's incognito mode is always active and there is no way to disable it.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/159967827/61dbe33f-82af-4b8a-af3b-c7136ae59791

### Steps To Reproduce

```markdown
1. Open version 1.8 (1.8 - 1.8.9) using the Microsoft SwiftKey keyboard
2. Type "W" or try turning off incognito mode.
```

### Expected Behavior

I expected that I would be able to use the keyboard normally (type W without any problems and freely turn incognito mode on and off).

### Platform

```markdown
- Device model: Xiaomi POCO X3 NFC
- CPU architecture: arm64
- Android version: Android 12; MIUI 14.0.5
- PojavLauncher version: Latest version from Github (Until the date 03/29/2024; 12:46am)
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/8426666022
```

**Comment by GaucovyAero** [comment]
the w thing can be fixed by binding fullscreen to another key in the minecraft settings, but no idea whats up with the incognito mode, im also using swiftkey

**Comment by GaucovyAero** [comment]
i guess rename the issue to "Incognito mode when using Microsoft SwiftKey"

**Comment by GaucovyAero** [comment]
this is happening because learning words is disabled in pojav because you enter commands and stuff, wont enable that
