### ISSUE TITLE
Sodium latest version get crashed in pojav 

### ISSUE THREAD

**Issue by GAMERGENIX2** [PojavLauncherTeam/PojavLauncher#5277]
### Describe the bug

We are not able to use new sodium so plz give me sodium patcher for latest sodium 

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Upload sodium latest version in mods folder of 1.20.1 or 120.1+
```

### Expected Behavior

No

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No plz give sodium patcher

**Comment by GaucovyAero** [comment]
optifine is faster on pojav anyway, if you want, grab patched sodium jars from pojav discord but yeah, very slow
