### ISSUE TITLE
Code -1

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5279]
### Describe the bug

I play mod and crash 1.16.5

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14800753/latest.log)

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: 
- Android version: 12
- PojavLauncher version: edelweiss 2024325-d32347d-
```

**Comment by GaucovyAero** [comment]
remove sophisticated backpacks and physicsmod

**Comment by wayxyz89** [comment]
![Screenshot_2024-03-29-20-15-33-628_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165360557/84ec441c-3e26-4ac5-b3ca-4fbd9621e3e6)
Thank you it works❤️❤️❤️

**Comment by GaucovyAero** [comment]
pog
