### ISSUE TITLE
[BUG] не работает русская раскладка клавиатуры 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#528]
...
При написании текста в чате мне требуется русская раскладка клавиатуры которая не работает 
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
-model Huawei HONOR 9C 
<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Известно.

**Comment by ghost** [comment]
ты это уже писал, разработчики знают

**Comment by BekYal** [comment]
А разрабы виксят баги? Просто хз, они как у мсинаьокса, или нет

**Comment by artdeell** [comment]
русская клавиатура не в приоритете. потому что никто не знает как её чинить.

сб, 26 дек. 2020 г., 15:03 DEABRO-BEK <notifications@github.com>:

**Comment by Mathias-Boulay** [comment]
![image](https://user-images.githubusercontent.com/24864674/120835618-d8d26280-c564-11eb-8058-5f43f733a749.png)
It works now, closing the issue.
