### ISSUE TITLE
[BUG] Forge 37.0

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5281]
### Describe the bug

Forge 1.17.1 Error In Play

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14804897/latestlog.txt)

### Steps To Reproduce

```markdown
Install Forge 1.17.1 And Minecraft Vanilla 1.17.1
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64 
- Android version: 12
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

There isn't any

**Comment by GaucovyAero** [comment]
fixed in the latest github actions build

**Comment by Dilen0001** [comment]
When fixed forge 1.17.1 in the latest github actions build

**Comment by Dilen0001** [comment]
Whens fix forge 1.17.1 in the latest github action build

**Comment by Dilen0001** [comment]
Why Forge 1.17.1 Still Exit Code 1

**Comment by GaucovyAero** [comment]
> Why Forge 1.17.1 Still Exit Code 1 [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14893944/latestlog.txt)

you are using a very old version of java 17, use internal-17

**Comment by Dilen0001** [comment]
Still Exit Code 1
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14894949/latestlog.txt)

**Comment by GaucovyAero** [comment]
![Screenshot_20240406-225554_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/80b04085-8923-4695-a332-dbd782828c66)

update to latest forge

**Comment by Dilen0001** [comment]
Is the Old Forge Not Working?

**Comment by GaucovyAero** [comment]
> Is the Old Forge Not Working?

no, why do you need old forge?

**Comment by Dilen0001** [comment]
I Want to Install Mods

**Comment by GaucovyAero** [comment]
> I Want To Install A Mod On Old Forge

use latest forge for 1.17.1, it is going to work

**Comment by Dilen0001** [comment]
Will the Old Forge 1.17.1 Not Be Fixed
