### ISSUE TITLE
optifine is faster on pojav anyway, if you want, grab patched sodium jars from pojav discord but yeah, very slow

### ISSUE THREAD

**Issue by GAMERGENIX2** [PojavLauncherTeam/PojavLauncher#5282]
optifine is faster on pojav anyway, if you want, grab patched sodium jars from pojav discord but yeah, very slow

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/5277#issuecomment-2026843342_

**Comment by GAMERGENIX2** [comment]
I am banned from pojav discord for my stupid mistake 
So can u give here I want to use sodium latest version

**Comment by GaucovyAero** [comment]
[Sodium 0.5.8 1.20.1](<https://github.com/TarikBR/sodium-fabric/actions/runs/7817821565>)
[Sodium 0.5.5 1.20.2](<https://github.com/TarikBR/sodium-fabric/actions/runs/7817825738>)
[Sodium 0.5.8 1.20.4](<https://github.com/TarikBR/sodium-fabric/actions/runs/7814951815>)

be sure to back up these files, they might go down in a few months
