### ISSUE TITLE
latestlog (1).txt

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#5283]
![latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14805281/latestlog.1.txt)

i was trying to load a modpack called "sevtech ages" and its crashed

**Comment by GaucovyAero** [comment]
remove randompatches

**Comment by aura123lol** [comment]
> remove randompatches

After removing random patches it is still crashinf
