### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#5284]
![latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14806180/latestlog.txt)

It is still crashing after removing "randompatches"

**Comment by GaucovyAero** [comment]
out of memory

**Comment by aura123lol** [comment]
> out of memory

Can you tell me how to fix

**Comment by GaucovyAero** [comment]
allocate more ram, and if you cant, you have to remove memory intensive mods
