### ISSUE TITLE
Document from Aryan.

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#5285]
![Uploading latestlog(69).txt …]()
 
I fixed everything but everytime i try to load a world it crashes pls help me one more time

**Comment by GaucovyAero** [comment]
you didnt upload it

**Comment by aura123lol** [comment]
> you didnt upload it
> 

![latestlog(69).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14808835/latestlog.69.txt)

Now is this uploaded?

**Comment by GaucovyAero** [comment]
yep, remove thebetweenlands or somehow disable or modify the shaders that its using or use another renderer cause gl4es doesnt work with them

**Comment by aura123lol** [comment]
> yep, remove thebetweenlands or somehow disable or modify the shaders that its using or use another renderer cause gl4es doesnt work with them

I'll try that tmmrw but thank you for helping me 🙏🏿🙏🏿🙏🏿
