### ISSUE TITLE
“Your account is a demo account!”

### ISSUE THREAD

**Issue by matrSid** [PojavLauncherTeam/PojavLauncher#5286]
### Describe the bug

So Im trying to login pojav launcher through my microsoft account and it says that its a demo account even though i bought minecraft.

### The log file and images/videos

None

### Steps To Reproduce

```markdown
Logging in
```

### Expected Behavior

I expect it to not say that my account is a demo.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ghost** [comment]
Make sure to login minecraft.net and try relogging in to PojavLauncher
