### ISSUE TITLE
Add a custom screen recorder in pojav 

### ISSUE THREAD

**Issue by GAMERGENIX2** [PojavLauncherTeam/PojavLauncher#5287]
### Is this request related to a bug?

No

### Describe the request.

Add custom screen recorder in pojav so that we don't need external recorder for recording and perform also don't get drop

### Anything else?

No

**Comment by GAMERGENIX2** [comment]
And wth about to add some other features that increases pojav performance like the system that feather use to improve performance so we can't use feather in pojav but atleast u guys can use the same ya alternative system or features that can improve performance

**Comment by GAMERGENIX2** [comment]
In short I am trying to say that to convert pojav into a new launcher that give good fps and many other features like one click any mods instal mods not modpack or a custom gui in game it doesn't matter that much but the player will like it alot when pojav have all features that feather or other clients have

**Comment by ghost** [comment]
🫠

**Comment by GAMERGENIX2** [comment]
> 🫠

?

**Comment by ghost** [comment]
I don't think they could add built-in screen recorder into PojavLauncher

**Comment by GaucovyAero** [comment]
a screen recorder inside pojav would require us to capture one frame and show another one on screen, not gonna do that
to increase performance, install pojavoptimize from the pojav discord

**Comment by ghost** [comment]
Screen recorder can sometimes drop fps
