### ISSUE TITLE
How to fix it code 1 😥😥

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5288]
### Describe the bug

Crash 1.19.2 code 1😥😥

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14811005/latest.log)

### Steps To Reproduce

```markdown
1.start pojav
2.run Minecraft
3.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: ??
- Android version: 12
- PojavLauncher version: latest
```

**Comment by wayxyz89** [comment]
![Screenshot_2024-03-30-14-43-55-716_net.kdt.pojavlaunch.debug.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165360557/0ea0bad4-45f0-4af4-bde4-227fc1ad63ed)

**Comment by GaucovyAero** [comment]
you sent the wrong log, send latestlog.txt

**Comment by Uhak9373728** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14811677/latestlog.txt)

**Comment by Uhak9373728** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14811688/latestlog.txt)

**Comment by wayxyz89** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14811695/latestlog.txt)
This??

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14811695/latestlog.txt) This??

you are missing some mods

```
18:27:35] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'atlaslib', Requested by: 'hordes', Expected range: '[1.1.5,)', Actual version: '[MISSING]'
	Mod ID: 'architectury', Requested by: 'bakery', Expected range: '[6.5.77,)', Actual version: '[MISSING]'
	Mod ID: 'framework', Requested by: 'additionalguns', Expected range: '[0.4.2,)', Actual version: '[MISSING]'
	Mod ID: 'framework', Requested by: 'cgm', Expected range: '[0.6.16,)', Actual version: '[MISSING]'
	Mod ID: 'framework', Requested by: 'projectarsenal', Expected range: '[0.4.2,)', Actual version: '[MISSING]'
	Mod ID: 'architectury', Requested by: 'betteranimalsplus', Expected range: '[5.9.30,7.0.0)', Actual version: '[MISSING]'
	Mod ID: 'framework', Requested by: 'moguns', Expected range: '[0.4.0,)', Actual version: '[MISSING]'
	Mod ID: 'doapi', Requested by: 'bakery', Expected range: '[1.1.0,)', Actual version: '[MISSING]'
```
