### ISSUE TITLE
Crash code 1 

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5289]
### Describe the bug

Version 1.19.2

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14811708/latestlog.txt)
![Screenshot_2024-03-30-14-43-55-716_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165360557/10ee8b1d-ea56-4c1e-b5af-7ba818a77f05)

### Steps To Reproduce

```markdown
1.start pojav
2.run version
3crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: 
- Android version: 12
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
you are missing some mods
```
[18:27:35] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'atlaslib', Requested by: 'hordes', Expected range: '[1.1.5,)', Actual version: '[MISSING]'
	Mod ID: 'architectury', Requested by: 'bakery', Expected range: '[6.5.77,)', Actual version: '[MISSING]'
	Mod ID: 'framework', Requested by: 'additionalguns', Expected range: '[0.4.2,)', Actual version: '[MISSING]'
	Mod ID: 'framework', Requested by: 'cgm', Expected range: '[0.6.16,)', Actual version: '[MISSING]'
	Mod ID: 'framework', Requested by: 'projectarsenal', Expected range: '[0.4.2,)', Actual version: '[MISSING]'
	Mod ID: 'architectury', Requested by: 'betteranimalsplus', Expected range: '[5.9.30,7.0.0)', Actual version: '[MISSING]'
	Mod ID: 'framework', Requested by: 'moguns', Expected range: '[0.4.0,)', Actual version: '[MISSING]'
	Mod ID: 'doapi', Requested by: 'bakery', Expected range: '[1.1.0,)', Actual version: '[MISSING]
```

**Comment by wayxyz89** [comment]
> you are missing some mods
> 
> ```
> [18:27:35] [main/ERROR]: Missing or unsupported mandatory dependencies:
> 	Mod ID: 'atlaslib', Requested by: 'hordes', Expected range: '[1.1.5,)', Actual version: '[MISSING]'
> 	Mod ID: 'architectury', Requested by: 'bakery', Expected range: '[6.5.77,)', Actual version: '[MISSING]'
> 	Mod ID: 'framework', Requested by: 'additionalguns', Expected range: '[0.4.2,)', Actual version: '[MISSING]'
> 	Mod ID: 'framework', Requested by: 'cgm', Expected range: '[0.6.16,)', Actual version: '[MISSING]'
> 	Mod ID: 'framework', Requested by: 'projectarsenal', Expected range: '[0.4.2,)', Actual version: '[MISSING]'
> 	Mod ID: 'architectury', Requested by: 'betteranimalsplus', Expected range: '[5.9.30,7.0.0)', Actual version: '[MISSING]'
> 	Mod ID: 'framework', Requested by: 'moguns', Expected range: '[0.4.0,)', Actual version: '[MISSING]'
> 	Mod ID: 'doapi', Requested by: 'bakery', Expected range: '[1.1.0,)', Actual version: '[MISSING]
> ```

thanks for telling
