### ISSUE TITLE
Not a bug I can't play with my friends

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5290]
### Describe the bug

Anyone who can fix it, please

### The log file and images/videos

![Uploading IMG_20240330_200116.jpg…]()

### Steps To Reproduce

```markdown
1. run game
2.play multiplayer
3join 
4.error invasi argument
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: ?
- Android version: 12
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
you didnt upload the image

**Comment by wayxyz89** [comment]
![IMG_20240330_200116](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165360557/e4193699-f1dc-4fef-8e65-1c93eb68342f)
Sorry ,invalid argument

**Comment by alexsovi** [comment]
Send logs

**Comment by wayxyz89** [comment]
> Send logs

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14812261/latestlog.txt)

This??

**Comment by Uhak9373728** [comment]
> Send logs

![Uploading Screenshot_2024-03-30-21-12-49-148_net.kdt.pojavlaunch.debug.jpg…]()

**Comment by wayxyz89** [comment]
> you didnt upload the image

![Screenshot_2024-03-30-21-12-49-148_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165360557/1f093165-f47b-4f0c-8a43-6fc0485bb6e4)

**Comment by GaucovyAero** [comment]
```
[21:12:36] [main/INFO]: Connecting to 33069, 25565
Mar 30, 2024 9:12:43 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 77:8c:1d:4c:11:73:24:0f
[21:12:43] [Server Connector #1/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedSocketException: Invalid argument: 0.0.129.45/0.0.129.45:25565
```

33069:25565 isnt a valid ip address lol

**Comment by wayxyz89** [comment]
> ```
> [21:12:36] [main/INFO]: Connecting to 33069, 25565
> Mar 30, 2024 9:12:43 PM io.netty.util.internal.MacAddressUtil defaultMachineId
> WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 77:8c:1d:4c:11:73:24:0f
> [21:12:43] [Server Connector #1/ERROR]: Couldn't connect to server
> io.netty.channel.AbstractChannel$AnnotatedSocketException: Invalid argument: 0.0.129.45/0.0.129.45:25565
> ```
> 
> 33069:25565 isnt a valid ip address I entered it correctly, so I don't know, I entered the port my friend said

**Comment by GaucovyAero** [comment]
your friend gotta know what hes doing first of all

**Comment by wayxyz89** [comment]
> your friend gotta know what hes doing first of all

So what should my friend do,I play with different places

**Comment by GaucovyAero** [comment]
> > your friend gotta know what hes doing first of all
> 
> So what should my friend do,I play with different places

he should host a public server himself or pay for it
