### ISSUE TITLE
a screen recorder inside pojav would require us to capture one frame and show another one on screen, not gonna do that

### ISSUE THREAD

**Issue by GAMERGENIX2** [PojavLauncherTeam/PojavLauncher#5291]
a screen recorder inside pojav would require us to capture one frame and show another one on screen, not gonna do that
to increase performance, install pojavoptimize from the pojav discord

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/5287#issuecomment-2027995048_

**Comment by GAMERGENIX2** [comment]
So do u know any recorder that do not drop much fps with pojav and can record goodly
And I am not saying about mods bro I am saying that why don't convert pojav into a high client with in-game features and quil skin change for premium accounts and seperate mod installer not modpack installer

**Comment by GaucovyAero** [comment]
> So do u know any recorder that do not drop much fps with pojav and can record goodly

your built-in android recorder

> I am saying that why don't convert pojav into a high client with in-game features and quil skin change for premium accounts and seperate mod installer not modpack installer

do it yourself lol
