### ISSUE TITLE
[BUG] The main menu is blacked out

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#5292]
### Describe the bug

If we press the back button on the main menu or perform a back operation in other ways, the MainMenuFragment will disappear directly, and returning again will quit the app. I suspect that the problem lies in Fragment management.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/123115192/f02f60f3-f292-4a50-acb3-f2cc5bd21ff1

### Steps To Reproduce

```markdown
When returning from the main menu.
```

### Expected Behavior

When returning from the main menu, the app should be exited directly instead of clearing the Fragment.

### Platform

```markdown
Irrelevant, such a problem can occur on any device.
- PojavLauncher Version : 9939478
```

**Comment by Mathias-Boulay** [comment]
Bahaha yes that's on my fault, I tweaked the back stack management to avoid invisible stacking fragments but it changes the "root".

**Comment by GaucovyAero** [comment]
fixed in https://github.com/PojavLauncherTeam/PojavLauncher/commit/dda7a4e45ca04a95b74b1c38b50ff6d82ac743b2
