### ISSUE TITLE
[BUG] vulkan mod crash

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5293]
### Describe the bug

I will use vulkan mod it's crash with code 1 and why. vulkan mod support 1.1 and up api vulkan version my vulkan api version is 1.1.128 
![Screenshot_۲۰۲۴-۰۳-۳۱-۰۳-۳۷-۴۷-۱۲۳_de saschawillems vulkancapsviewer-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/3023b274-4d8d-4080-ab33-70c8896d7b8d)
My full profile f vulkan

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14813672/latestlog.txt)
Jvm arguments are not have any problem

### Steps To Reproduce

```markdown
1:install vulkan mod and fabric api in mods folder for 1.20.4
2:start pojav launcher
3:launch game
4:crash with code 1
```

### Expected Behavior

I deleted vulkan mod in mods folder and not crashed again

### Platform

```markdown
- Device model: poco f5 12/256G
- CPU architecture: arm64_v8a
- Android version: 14
- PojavLauncher version: in latest log has writes
```

### Anything else?

Can i update gpu driver on android

**Comment by khanhduytran0** [comment]
VulkanMod requires Vulkan 1.2 at least. ~~You gotta use Turnip driver~~
Update: according to log, turnip seems loaded

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۳-۳۱-۰۵-۱۹-۵۴-۸۶۳_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/57e4e4f9-f409-4409-9321-2e7bb524ae7f)

**Comment by ghost** [comment]
This conversation about vulkan api support for vulkan mod and says minimum support is 1.1
The (use system vulkan driver) option is off then turnip is off and this option requires vulkan api 1.3

**Comment by ghost** [comment]
Probably your device doesn't support vulkan api 1.2 or 1.3 something

**Comment by VenomousSteam81** [comment]
wut da hail?
why are we providing support for this!!! we dont in the discord

**Comment by ghost** [comment]
Also VulkanMod Is Unsupported on PojavLauncher android

**Comment by kasrarouhi** [comment]
![Uploading Screenshot_۲۰۲۴-۰۳-۳۱-۱۷-۲۴-۵۷-۶۱۵_com.android.chrome-edit.jpg…]()

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۳-۳۱-۱۷-۲۴-۵۷-۶۱۵_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/6ba25cd4-dbc5-48d9-ab1a-1d1ad17252b0)

**Comment by Algiuxs** [comment]
> ![Screenshot_۲۰۲۴-۰۳-۳۱-۱۷-۲۴-۵۷-۶۱۵_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/6ba25cd4-dbc5-48d9-ab1a-1d1ad17252b0)
> 
the vulkan mod needs patching

**Comment by mchnjt** [comment]
> > ![Screenshot_۲۰۲۴-۰۳-۳۱-۱۷-۲۴-۵۷-۶۱۵_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/6ba25cd4-dbc5-48d9-ab1a-1d1ad17252b0)
> > 
> 
> Can't you read the brackets?

can you less be hostile

**Comment by Algiuxs** [comment]
> > > ![Screenshot_۲۰۲۴-۰۳-۳۱-۱۷-۲۴-۵۷-۶۱۵_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/6ba25cd4-dbc5-48d9-ab1a-1d1ad17252b0)
> > > 
> > 
> > Can't you read the brackets?
> 
> can you less be hostile

Sorry, I had an argument with my sister.

**Comment by Raghav155221** [comment]
vro disable auto update and install Edelweiss with vulkan mod
