### ISSUE TITLE
Can't join multi player servers

### ISSUE THREAD

**Issue by IAMJAXXwasTaken** [PojavLauncherTeam/PojavLauncher#5296]
### Describe the bug

Every time I try to join a multiplayer server and I add the IP it Says to restart the launcher.What do I do

### The log file and images/videos

It says ( Try to restart the game or launcher)

### Steps To Reproduce

```markdown
It wants me to put stuff here and I don't know. What to put here
```

### Expected Behavior

Once you fix it, it should work.

### Platform

```markdown
- Device model:idk 
- CPU architecture:idk 
- Android version:idk 
- PojavLauncher version:idk
```

### Anything else?

The version I'm on is 1.19 on Minecraft.

**Comment by Marshall2439** [comment]
Nuh uh you need to buy official minecraft account for that

**Comment by Marshall2439** [comment]
You don't even know what to put there 🤦🏾‍♂️

**Comment by IAMJAXXwasTaken** [comment]
I already have an Official Minecraft account, it's hooked up to my. Pojav Launcher @Marshall2439

**Comment by IAMJAXXwasTaken** [comment]
How do i get My account in java But I'm inside the game. @Marshall2439

**Comment by Flowerr4sr0** [comment]
Shit that's fucked

**Comment by Marshall2439** [comment]
> How do i get My account in java But I'm inside the game. [@Marshall2439](https://github.com/Marshall2439)

Login with microsoft account then you should be able to join servers
