### ISSUE TITLE
[BUG] Snapshot 24w14potao is crashing help needed.

### ISSUE THREAD

**Issue by BNaise** [PojavLauncherTeam/PojavLauncher#5297]
### Describe the bug

It's crashing.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14822639/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Select 24w14potato
3. Play
4. Crash
```

### Expected Behavior

- Not to crash.

### Platform

```markdown
- Device model: RMX3501
- CPU architecture: 
- Android version: 12
- PojavLauncher version: vedelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by BNaise** [comment]
> .

What

**Comment by EmuplayM** [comment]
nah it works on this release of pojav https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/8494081349

**Comment by GaucovyAero** [comment]
remove your mods

**Comment by Moidar** [comment]
Oh, i have crush too, but my latestlog is different your latestlog
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14827403/latestlog.txt)

**Comment by GaucovyAero** [comment]
yeah i also had this no idea what to do about it

**Comment by Moidar** [comment]
Maybe is it a problem of PojavLauncher? And this can't be solved

**Comment by GaucovyAero** [comment]
seems like a pojav issue, reopening
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14827548/latestlog.txt)

**Comment by Moidar** [comment]
In other renderer other latestlog
Zink: 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14827776/latestlog.txt)
Angle:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14827786/latestlog.txt)

**Comment by GaucovyAero** [comment]
![Screenshot_2024-04-02-10-28-22-956_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/579923d8-e93d-454d-9560-77ab792df9ce)

guys wait for it to appear in your versions list, then its gonna work

**Comment by Moidar** [comment]
Which versions list is it not on? If this is not the list where installed, releases, snapshots, and etc. And it’s also in the versions folder, but it doesn’t start. Just wait?

**Comment by Moidar** [comment]
Okay, in my 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14835128/latestlog.txt)
There is a new "version string 150"

**Comment by Moidar** [comment]
Oh, its worked thanks
![Screenshot_2024-04-02-13-31-45-871_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165697848/54d95cb4-a902-4141-8efd-4129457e7bf7)

**Comment by BNaise** [comment]
Ok now it's working.
