### ISSUE TITLE
Can't join servers.

### ISSUE THREAD

**Issue by IAMJAXXwasTaken** [PojavLauncherTeam/PojavLauncher#5298]
### Describe the bug

I can't join servers that are multi player when I try to join them.
 Access to restart the game or launcher.

### The log file and images/videos

Im in 1.19

### Steps To Reproduce

```markdown
1. Start pojavLauncher
2. Open 1.19
3. Click on multi player
4. Join server
5. Error
```

### Expected Behavior

I expect that when I join a multiplayer server. It will let me join.

### Platform

```markdown
- Device model: Galaxy A51 
- CPU architecture:im not Sure 
- Android version:13 
- PojavLauncher version:I'm not sure
```

### Anything else?

![Screenshot_20240331_191750_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150642248/ddfc2193-d799-4bf6-a325-b289dc036b95)

**Comment by GaucovyAero** [comment]
buy minecraft
