### ISSUE TITLE
Phantom Inputs with Joycons

### ISSUE THREAD

**Issue by SUNGOD374** [PojavLauncherTeam/PojavLauncher#5299]
### Describe the bug

When using joycons with PojavLauncher, the drift from the joycons causes phantom inputs.  PovjavLauncher clearly seems to detect every minute input that comes as a result, despite how minimal.
Joycons work perfectly normal on other things like Android OS.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/73479290/67f117ec-4bec-4909-b4b4-32cc9abbcc1b

@

https://github.com/PojavLauncherTeam/PojavLauncher/assets/73479290/c336dfdc-3a86-4b8e-a484-dde0dd643579

### Steps To Reproduce

```markdown
Pair used joycons to your device and launch PojavLauncher.
```

### Expected Behavior

The ability to use joycons on Minecraft despite minimal drift

### Platform

```markdown
- Device model: Nintendo Switch V1
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
"latest" is not a version

**Comment by SUNGOD374** [comment]
> "latest" is not a version

edelweiss-20230928-9484d0c-v3_openjdk (according to google play store). ill reflect this in the original post.

**Comment by 1vogada** [comment]
Same issue using a ps5(dual sense) controller

**Comment by SUNGOD374** [comment]
Update: I no longer believe that this is the result of joycon drift, for I just installed hall-effect joysticks (and calibrated them) and it still drifts in the same manner.

**Comment by GaucovyAero** [comment]
open a new issue if still present on the latest play store build
