### ISSUE TITLE
[BUG] pixelmon reforged and pixelmon gens crashes

### ISSUE THREAD

**Issue by bonniechica** [PojavLauncherTeam/PojavLauncher#530]
**Describe the bug**
Ok so let's start I either put reforged or generations in mods folder 1.12.2 forge I asked the devs of reforged they said u the devs need to look the issue they say is the way they handle cursor input on there end crashes here's what gens does it goes to menu load into world or server crash hope it can be fixed the error is nosuchmethoderror

**To Reproduce**
1. Have pixelmon generations or reforged in mods
2. Start pojav launcher
3. Launch forge 1.12.2
4. Wait for mojang logo/reforged load into world or server/generations
5. Automatic crash after black screen with no controls

...

**Expected behavior**
I expected that the menu would load and no crash from the mod since biomes o plenty optifine don't cause any probs 

**Screenshots**
I don't have any but willing to post more if u need it

**Platform:**
 - Device Model moto g power
 - CPU architecture aarch 64
 - Android Version 10

**Comment by artdeell** [comment]
Log?

**Comment by bonniechica** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5733180/latestlog.txt)

**Comment by bonniechica** [comment]
they said cuz the one i spoke to was lower in the ranks in the discord server they have said it may be the lwjgl idk why tho or how that is fixable

**Comment by bonniechica** [comment]
that causes my error so im reporting to u guys so u can work on a fix for these things

**Comment by artdeell** [comment]
What's your launcher version?

**Comment by bonniechica** [comment]
version 3.3.0

**Comment by bonniechica** [comment]
i got that working somewhat i  just cant do pixelmon when its the only mod i play

**Comment by artdeell** [comment]
Pixelmon crash is kniwn; try to disable VBO or use latest action run.

**Comment by bonniechica** [comment]
ok

**Comment by bonniechica** [comment]
the latest dev build didnt work and vbos didnt work from options idk if its enabled in game ill boot into it without the mod

**Comment by bonniechica** [comment]
it shows in game vbos are off so idk

**Comment by khanhduytran0** [comment]
Your installed LWJGL has problem(?). Remove /sdcard/games/.minecraft/lwjgl3 then launch again.

**Comment by khanhduytran0** [comment]
Also send log after mod crash.

**Comment by bonniechica** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5733515/latestlog.txt)

**Comment by bonniechica** [comment]
if u mean that one

**Comment by pstube** [comment]
Pixelmon Generations
https://youtu.be/vUVUVCud-9g

**Comment by bonniechica** [comment]
i was trying that then i thought maby im doing ram wrong and boom i uninstalled leaving ram at default works then i move ram to 1gb of ram crashes??

**Comment by pstube** [comment]
Xmx 2000

**Comment by bonniechica** [comment]
Tried that it crashes still if I don't change it I can load into world

**Comment by pstube** [comment]
Which device do you use?

**Comment by bonniechica** [comment]
Moto g power 64 bit 4gb ram

**Comment by bonniechica** [comment]
So did anyone find a fix yet? Or

**Comment by khanhduytran0** [comment]
Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/443579505

**Comment by bonniechica** [comment]
Tried that + the one u just built and it crashed when login now

**Comment by ASGAMING009** [comment]
> Tried that + the one u just built and it crashed when login now

Sorry pojav but i have to say it for now you can play pixelmon generations not reforged because uhh idk in MCINBOX!?!?!?!

**Comment by artdeell** [comment]
> > Tried that + the one u just built and it crashed when login now
> 
> Sorry pojav but i have to say it for now you can play pixelmon generations not reforged because uhh idk in MCINBOX!?!?!?!

It is very efficent to write an issue with a last response one month ago. Also... you know what.

**Comment by Mathias-Boulay** [comment]
Stale issue, not reproducible in the latest action builds, closing issue.
