### ISSUE TITLE
[BUG] please don't close the issue and fix this thing

### ISSUE THREAD

**Issue by BUCIOJEK** [PojavLauncherTeam/PojavLauncher#5300]
### Describe the bug

Plsss fix this buuuug plsss i need it for my YouTube to make Minecraft video plssss fix it🙏😭 im android 14 btw

https://github.com/PojavLauncherTeam/PojavLauncher/assets/89052261/15cb9d4d-46d4-497a-8aac-385c760579e7

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: realme c55
- CPU architecture: h g88
- Android version: 14
- PojavLauncher version: newest
```

### Anything else?

Nope

**Comment by BUCIOJEK** [comment]
Plss fix it 🙏🙏🙏😭😭😭

**Comment by GaucovyAero** [comment]
duplicate issue

**Comment by GaucovyAero** [comment]
#5000
