### ISSUE TITLE
Karar

### ISSUE THREAD

**Issue by karar123123** [PojavLauncherTeam/PojavLauncher#5304]
### Describe the bug

Karara

### The log file and images/videos

B

### Steps To Reproduce

```markdown
Hbfhhgh
```

### Expected Behavior

Hdhdhdh

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
dahlia-20230813-5e8842b-v3_openjdk)
```

### Anything else?

Hfhf

**Comment by karar123123** [comment]
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
dahlia-20230813-5e8842b-v3_openjdk)

**Comment by karar123123** [comment]
Karar

**Comment by karar123123** [comment]
Hbfhhgh

**Comment by karar123123** [comment]
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
dahlia-20230813-5e8842b-v3_openjdk)

**Comment by karar123123** [comment]
Hbfhhgh

**Comment by karar123123** [comment]
Okay 😊

**Comment by karar123123** [comment]
dahlia-20230813-5e8842b-v3_openjdk)

**Comment by karar123123** [comment]
2148916233

**Comment by karar123123** [comment]
java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:222)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:80)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by karar123123** [comment]
KKajajgsuddj

**Comment by karar123123** [comment]
****

**Comment by karar123123** [comment]
__bdjxhx

**Comment by karar123123** [comment]
>

**Comment by karar123123** [comment]
Jg

> Vncjcj

> Tjjrfj

> Hcbx

**Comment by karar123123** [comment]
Okay

**Comment by karar123123** [comment]
Okay 😊☺️ you love lraq you ok no prob we are follow up and I'll talk to you later I love it I love you no cry in front seat ok I'll talk with him tomorrow

**Comment by karar123123** [comment]
Okay with you soon and I will of people in front seat y are you doing for Thanksgiving and I will

**Comment by karar123123** [comment]
Xnxnxnzn

**Comment by karar123123** [comment]
Vjcjcjxhxh

**Comment by karar123123** [comment]
Karar #5304

**Comment by karar123123** [comment]
Karar #4650

**Comment by karar123123** [comment]
Hbfhhgh

**Comment by VenomousSteam81** [comment]
nobodys gonna help you if you keep spamming

**Comment by karar123123** [comment]
<sup> </sup>	None	This is a <sup>superscript</sup> text

**Comment by karar123123** [comment]
<sup> </
This is a <sup>superscript</sup> text

**Comment by ghost** [comment]
Close that issue now

**Comment by ghost** [comment]
Yeah

**Comment by ghost** [comment]
Spamming is not allowed here, just don't spam here

**Comment by ghost** [comment]
Alright done
