### ISSUE TITLE
Bug Crashing With Fabric+Sodium

### ISSUE THREAD

**Issue by RelaxingNostalgia** [PojavLauncherTeam/PojavLauncher#5305]
### Describe the bug

The Game/Launcher crashes whenever i load/create a new world,and it dosent render any chunks.

edit 
sodium also dosent work with vulkanmod,version tested 1.20.2 issue being it opens the game but stays with black screen infinitely.

Hardware:Snapdragon 680 4GB Ram 

video showing the issue
https://youtu.be/ptE-pGxMoKE

### The log file and images/videos

no file

### Steps To Reproduce

```markdown
start pojav have fabric and sodium installed,create world
```

### Expected Behavior

crash

### Platform

```markdown
- Device model: Motog32
- CPU architecture: Arm
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

.

**Comment by ThatMG393** [comment]
Sodium is not supported on PojavLauncher nor VulkanMod is supported with Sodium and/or PojavLauncher

**Comment by RelaxingNostalgia** [comment]
> Sodium is not supported on PojavLauncher nor VulkanMod is supported with Sodium and/or PojavLauncher

actually i was able to run vulkanmod in pojavlauncher,just wasnt able to run sodium.
also i dont know how your response is in any way meant to solve the issue,or help.

**Comment by GaucovyAero** [comment]
get patched sodium from the pojav discord, its slower than optifine tho

**Comment by ThatMG393** [comment]
> > Sodium is not supported on PojavLauncher nor VulkanMod is supported with Sodium and/or PojavLauncher
> 
> actually i was able to run vulkanmod in pojavlauncher,just wasnt able to run sodium. also i dont know how your response is in any way meant to solve the issue,or help.

Like I said VulkanMod is unsupported, it doesn't mean that if it works it is supported.
