### ISSUE TITLE
PojavLauncher not compatible with other apps

### ISSUE THREAD

**Issue by RelaxingNostalgia** [PojavLauncherTeam/PojavLauncher#5306]
### Describe the bug

apps that run on background,and arent system native,dont work

screen recorders not working
also volume boosters not working

changing how much ram the app consumes dosent fix this,no matter how low i set

### The log file and images/videos

.

### Steps To Reproduce

```markdown
apps ive used
volume booster
https://play.google.com/store/apps/details?id=boostvolume.soundbooster.soundamplifier.loudspeaker.increasevolume.soundenhancer.volumebooster

screen recorder
https://play.google.com/store/apps/details?id=us.rec.screen

only the system native recorder works(but it sucks as all native app records audio in mono but the rest is all high quality bruh)
```

### Expected Behavior

the sound booster wont boost anything

and the recorder will give an error/failure

### Platform

```markdown
- Device model: motog32
- CPU architecture: arm
- Android version: 13
- PojavLauncher version: lastest
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
what does not working mean?

**Comment by artdeell** [comment]
Expected. PC Minecraft is not a resource-efficent game, which causes Android to start freeing resources by shutting down background applications. The solutions to your problem are:
- Do not play with lots of mods
- Enable power saving of your device
If none of these help you, your only option is getting a better device with higher specifications, such as a better processor and more RAM.
