### ISSUE TITLE
[F-Req] add java 21

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5308]
### Describe the request.

In newer version on minecraft snapshot 24w14a only work with java 21 not 17 please add java 21 in launcher

### Anything else?

Java 21 is faster or 17 i researched again and I take back what I said. java 21 have better performance. And jdk in heavy than jre please add with jre file

**Comment by kasrarouhi** [comment]
![Uploading Screenshot_۲۰۲۴-۰۴-۰۴-۰۶-۳۱-۰۴-۶۶۱_com.google.android.googlequicksearchbox-edit.jpg…]()

**Comment by kasrarouhi** [comment]
![Screenshot_۲۰۲۴-۰۴-۰۴-۰۶-۳۱-۰۴-۶۶۱_com google android googlequicksearchbox-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/aa4282a8-4fbc-41ce-aa89-86224c760588)

**Comment by ghost** [comment]
It would be a great idea, since the new snapshot requires java 21 starting at 24w14a

**Comment by Dilen0001** [comment]
.

**Comment by treefrog1109** [comment]
This would allow me to play the lastest snapshots again

**Comment by kasrarouhi** [comment]
Yes

**Comment by ghost** [comment]
Yes and with better performance

**Comment by ghost** [comment]
would be added into next pojavlauncher update

**Comment by U374** [comment]
Yes pojav should add this it might be a good update

**Comment by treefrog1109** [comment]
Is there a way to add it ourselves before the update?

**Comment by Algiuxs** [comment]
There is java 21 already in android multi arch java pojavs repository, you need to go in actions and find it, the tag is 21, but the description says it's 17 that's 21 java release.
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions?query=branch%3Abuildjre21

**Comment by treefrog1109** [comment]
Which file specifically will Pojav recognize or are you saying I need to build java 21 into my phone before hand?

**Comment by ghost** [comment]
Frist، download java21 and choice to which the java file for support your device for example my device is aarch64 you just go to download java21_aarch64. Now in zarchiver click on java21_aarch64 and click on extract here. A new file open

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۴-۱۵-۲۱-۵۲-۱۷-۹۹۲_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/9a8ea521-24db-43e7-84a1-7e1fa5a96438)

Go to the this setting and enter in download folder and click on extracted java file and java21 is installed in pojav launcher

**Comment by ghost** [comment]
Very thanks to Algiuxs for this java21 and i tested it's faster than java17

**Comment by ghost** [comment]
But i want to pojav launcher automatically install java21. not players

**Comment by Algiuxs** [comment]
Welp, for now there is no other option, but install manually.

**Comment by ghost** [comment]
Yep

**Comment by SkyBlee** [comment]
How do I download Java 21?

**Comment by SkyBlee** [comment]
How do I download Java 21?

**Comment by ghost** [comment]
. . . 

Just look up

**Comment by Mark7888** [comment]
What am I doing wrong? I downlad the aarch64 ones, but when i extract them, i get a tar.xz file instead of a jar

**Comment by Mark7888** [comment]
I tried to add it like @kasrarouhi shows on the picture, but got no result. Instead I clicked Settings -> Java Tweaks -> Runtime Manager -> ADD NEW, than added the `jdk21.tar.xz` file, and it worked like a charm.

**Comment by kasrarouhi** [comment]
You right I whistled to guiding. Sorry

**Comment by ghost** [comment]
You right @Mark7888 i just mistaked in explaining

**Comment by iCraftIP** [comment]
> . . .
> 
> Just look up

Sorry everyone for being stupid/inexperienced, but I don't know where to find any download for JREs on the page Algiuxs linked, there's only some workflow evolution scheme or something..?
I'm not too experienced with github and with the Actions page UI... Where _are_ the JRE 21 files themselves? (I know the rest of the passages, the only missing one is where to find the very files to choose between)

**Comment by ghost** [comment]
If you want to know download (device info HW) in play store
![Screenshot_۲۰۲۴-۰۴-۲۳-۲۱-۱۴-۲۹-۰۹۰_ru andr7e deviceinfohw-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/16baa8c3-d5e6-4c58-ad76-50fd12ab74cd)

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۴-۲۳-۲۱-۱۷-۰۰-۱۴۳_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/44ce901d-c7ab-470e-a628-e792b031064b)

**Comment by iCraftIP** [comment]
> ![Screenshot_۲۰۲۴-۰۴-۲۳-۲۱-۱۷-۰۰-۱۴۳_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/324940746-44ce901d-c7ab-470e-a628-e792b031064b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTQ4MDYsIm5iZiI6MTcxMzg5NDUwNiwicGF0aCI6Ii8xNDA0NjUyNjYvMzI0OTQwNzQ2LTQ0Y2U5MDFkLWM3YWItNDcwZS1hNjI4LWU3OTJiMDMxMDY0Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxNzQ4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjIxNWUxNjFlODVkNDU0ZDFiYzA4M2Q0MmNiZmNkMDIyNTllZTRiMTNiZDE4ZDhiZTBkZmI0YjhhZjljYjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cx28Hc-O3g4Khb1HlK09zjSi2-AhljXpoWWzU8ZsFgw)

Oh my GOD I'm blind I never saw the download button on the right... Thank you so much and sorry 😅

**Comment by rcoundon** [comment]
After downloading and extracting the 

> I tried to add it like @kasrarouhi shows on the picture, but got no result. Instead I clicked Settings -> Java Tweaks -> Runtime Manager -> ADD NEW, than added the `jdk21.tar.xz` file, and it worked like a charm.

This is the approach that worked for me

**Comment by justandree** [comment]
Guys I searched for a tutorial for almost 2 days now, because there's no such option as "Runtime Manager", and so I can't update the java version so now I'm stuck playing 1.20.2. Anyone who knows?

EDIT: forgot to mention I'm playing on iPad Pro (11' 2 gen)

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۵-۱۴-۱۷-۵۲-۵۹-۵۱۰_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/a5909c59-8fb9-4438-a83f-482414ec0d92)
![Screenshot_۲۰۲۴-۰۵-۱۴-۱۷-۵۳-۰۸-۲۶۵_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/2d5f143d-f8e1-4158-8228-27bcb5d39789)

If you don't have this option i think your pojav version is old or it's for ios version

**Comment by justandree** [comment]
I'm using Pojav2.2, downloaded from the github repo. Is there a new version I'm not aware about?

**Comment by ItAnthon** [comment]
you’re actually on the completely wrong repo, this is for Android’s version of PojavLauncher.

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۵-۱۴-۱۹-۰۱-۰۶-۷۰۲_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/1939b0d6-84e4-41d3-a989-dd53224385f5)
It is latest version on GitHub

**Comment by ItAnthon** [comment]
yeah problem is that guys on an iPad and you can’t just run an ANDROID COMPILED APP on an iPad

**Comment by ItAnthon** [comment]
@justandree please go to https://github.com/PojavLauncherTeam/PojavLauncher_iOS

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۵-۱۴-۱۹-۰۴-۲۷-۷۶۳_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/4d515e34-fd7c-4ed5-85d1-4d33dc8d167f)
The latest version on ios i don't know about pojav ios version but runtime manager is necessary

**Comment by justandree** [comment]
I genuinely hate how in the releases of the iOS repo the last version is 2.2, but searching deeper and deeper until my neurons almost collapsed I found out that the last version is 3.0. I downloaded the .opa and found out that Java 21 is preconfigured. I hate pojavteam.

**Comment by ItAnthon** [comment]
nono… 2.2 is the official release, 3.0 doesn’t exist. it’s just a developer thing to do to put a really high version that’s never expected to be hit. 2.3 will release soon, but we need to fix bugs and add features first, but 3.0 dev build has jre 21 built in. if you’ve already installed 2.2, you have to delete 2.2 completely and install 3.0 dev build.

**Comment by justandree** [comment]
already did it

**Comment by ItAnthon** [comment]
@justandree if you care for worlds or PojavLauncher keybinds, please back up the PojavLauncher folder prior to deleting.

**Comment by ItAnthon** [comment]
sounds great, but let us know on https://github.com/PojavLauncherTeam/PojavLauncher_iOS

since this repo is for Android.

**Comment by kasrarouhi** [comment]
Okay!! Pojav developers need to work to ios version of pojav

**Comment by kiokori-git** [comment]
> Okay!! Pojav developers need optimize ios version of pojav

optimize it? what do you mean, it already runs perfectly

**Comment by kiokori-git** [comment]
> ![Screenshot_۲۰۲۴-۰۵-۱۴-۱۹-۰۴-۲۷-۷۶۳_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/330501489-4d515e34-fd7c-4ed5-85d1-4d33dc8d167f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDgzNjQsIm5iZiI6MTcxNTc0ODA2NCwicGF0aCI6Ii8xNDA0NjUyNjYvMzMwNTAxNDg5LTRkNTE1ZTM0LWZkN2MtNGVkNS04NWQxLTRkMzNkYzhkMTY3Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwNDQxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTA4ZWUwYzViZTZlMDhhMjZmMjgwODQwYTFlYzM2OWM4YmU3OTQ5NTNhZjdkYTAxOWNmYzI0YzBlY2M3MDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oW1gBv7wNm6dOTV3pg39-gszvPvT4A2A_Hlkqk8n8zE) The latest version on ios i don't know about pojav ios version but runtime manager is necessary

runtime manager already exists on the pojavlauncher ios version, you just need to get the correct JRE's.

**Comment by rcoundon** [comment]
> I genuinely hate how in the releases of the iOS repo the last version is 2.2, but searching deeper and deeper until my neurons almost collapsed I found out that the last version is 3.0. I downloaded the .opa and found out that Java 21 is preconfigured. I hate pojavteam.

This is free, open source software, maintained by people in their spare time. Entitlement, criticism and demands like yours are toxic to the open source community.
If you hate it, don't use it, write your own, contribute to make it better, but criticising or hating on the team is out of order, it just smacks of entitlement and lack of empathy.

**Comment by ghost** [comment]
@justandree says he can't find any option writes runtime manager. I mean about optimize is add this option. And i confirm @rcoundon words

**Comment by Arthurxl155** [comment]
Mine is giving code -1 when I open Forge

**Comment by ghost** [comment]
Well it's added in latest pojav action in GitHub. Thank to consider it.

**Comment by ghost** [comment]
> Mine is giving code -1 when I open Forge

You need to download latest action on pojav. Minecraft 1.21 need lwjgl 3.3.3
In latest actions of pojav update lwjgl 3.3.1 to 3.3.3

**Comment by FullOfSpaghetti** [comment]
> > Mine is giving code -1 when I open Forge
> 
> You need to download latest action on pojav. Minecraft 1.21 need lwjgl 3.3.3 In latest actions of pojav update lwjgl 3.3.1 to 3.3.3

Can I ask how to download/install the action that allows Java 21 on iOS?

**Comment by ghost** [comment]
I don't know about ios version of pojav you need to report it in pojav ios GitHub website

**Comment by kroesufos** [comment]
> ![Screenshot_۲۰۲۴-۰۴-۲۳-۲۱-۱۷-۰۰-۱۴۳_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/324940746-44ce901d-c7ab-470e-a628-e792b031064b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjcyMDEsIm5iZiI6MTcxOTc2NjkwMSwicGF0aCI6Ii8xNDA0NjUyNjYvMzI0OTQwNzQ2LTQ0Y2U5MDFkLWM3YWItNDcwZS1hNjI4LWU3OTJiMDMxMDY0Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxNzAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjEyMTM0NDJiM2U4OTI3YWE0NjlmNmQ3MDBmZjFmZGI5YjM3YzVlNDg0OWY0ZTBhMzJhYjhmYzc1MDY5NjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b9T0P3Ljh81aMzPhVTI1QgZVLsNkRqPN0sGkN0BoksI)

Yeah that zip isn't really an "aarch64" file, is just a dumbass arm repacked jdk

**Comment by ghost** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions?query=branch%3Abuildjre21

I think thats help to find for you device support

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۶-۳۰-۲۱-۲۷-۲۶-۱۸۷_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/eb3c0bc1-c117-4ba6-b855-59053872639d)
Also have jre and jdk. But jdk have unnecessary features pojav don't need them and not compatible with some mods

**Comment by DuyAnh662** [comment]
iOS?

**Comment by ghost** [comment]
This website is for android and ios


![Screenshot_۲۰۲۴-۰۷-۰۴-۱۴-۴۶-۴۷-۹۴۵_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/276f60c6-efea-4787-9379-652de6ba91d4)

**Comment by kiokori-git** [comment]
> > > Mine is giving code -1 when I open Forge
> > 
> > 
> > You need to download latest action on pojav. Minecraft 1.21 need lwjgl 3.3.3 In latest actions of pojav update lwjgl 3.3.1 to 3.3.3
> 
> Can I ask how to download/install the action that allows Java 21 on iOS?

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9720445756

**Comment by LukasMendez** [comment]
> > > > Mine is giving code -1 when I open Forge
> > > 
> > > 
> > > You need to download latest action on pojav. Minecraft 1.21 need lwjgl 3.3.3 In latest actions of pojav update lwjgl 3.3.1 to 3.3.3
> > 
> > 
> > Can I ask how to download/install the action that allows Java 21 on iOS?
> 
> https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9720445756

How is that accomplished when you use AltStore?

**Comment by FullOfSpaghetti** [comment]
> > > > > Mine is giving code -1 when I open Forge
> > > > 
> > > > 
> > > > You need to download latest action on pojav. Minecraft 1.21 need lwjgl 3.3.3 In latest actions of pojav update lwjgl 3.3.1 to 3.3.3
> > > 
> > > 
> > > Can I ask how to download/install the action that allows Java 21 on iOS?
> > 
> > 
> > https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/9720445756
> 
> How is that accomplished when you use AltStore?

Hey! I set this up with Altstore successfully after some troubleshooting, although my iPad was not powerful enough to run the mods I like.

-Sidejitserver on my laptop
-Download the action and add to altstore with the plus on the top left
-DONT update pojav launcher in altstore as that will re-install the default version
1.21 forge started up fine for me after that!

Optifine aswell as sodium/ebeddium did not work with my ipad, i beleive due to openGL but dont quote me on that

**Comment by Oluwatise431** [comment]
Bruh you sure this will work?
