### ISSUE TITLE
[BUG] forge 1.20.4 game exited with code -1

### ISSUE THREAD

**Issue by oddsairaj007** [PojavLauncherTeam/PojavLauncher#5309]
### Describe the bug

I have done everything thing I change render and java tweaks but nothing seems to work I also cleared data and downloaded the latest version of pojav from PlayStore 

### The log file and images/videos

..

### Steps To Reproduce

```markdown
..
```

### Expected Behavior

To run atleast without mods

### Platform

```markdown
- Device:realme 11 pro
- Android version:14
- PojavLauncher version:latest from playstore
```

**Comment by GaucovyAero** [comment]
update to the latest github actions build, guide is on the wiki
