### ISSUE TITLE
[BUG]shows this! when I install forge 1.16.4

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#531]
shows this! when I install forge 1.16.4
![Screenshot_20201223-005801_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/102957925-773ca100-44ba-11eb-9d20-6c5752a4db20.jpg)

**Comment by artdeell** [comment]
Log?

**Comment by OwzygZawg** [comment]
what should i edit?

**Comment by mglovers123** [comment]
> what should i edit?


https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/420347106

**Comment by mglovers123** [comment]
Maybe

**Comment by OwzygZawg** [comment]
???

**Comment by OwzygZawg** [comment]
What??!

**Comment by khanhduytran0** [comment]
> Log?
@OwzygZawg
