### ISSUE TITLE
Game crash after joining skybattle 

### ISSUE THREAD

**Issue by GAMERGENIX2** [PojavLauncherTeam/PojavLauncher#5310]
### Describe the bug

I joined servere name sirius mc which have skybattle releam then I proceed it resource pack and my game get crash after pack load

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14861873/latestlog.txt)

### Steps To Reproduce

```markdown
Strt pojav 1.20.1 
Join siriusmc.in
Then in server join skybattle releam
Then proceed it's recourse pack 
After loading game crash
```

### Expected Behavior

May be because recourse pack not compatible or anything else 

### Platform

```markdown
- Device model: CPH2179
- CPU architecture: aarch64 proccesr rev 4
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

No plz fix my problem

**Comment by GAMERGENIX2** [comment]
Help me plz

**Comment by GaucovyAero** [comment]
duplicate issue
