### ISSUE TITLE
[BUG] cursed fabric launcher(as well as intended mods) no longer work

### ISSUE THREAD

**Issue by kingsmen1234** [PojavLauncherTeam/PojavLauncher#5311]
### Describe the bug

In recent PojavLauncher updates, certain versions and mods have been causing more lag than usual, more specifically in older versions, then upon updating to the most recent version of PojavLauncher was unable to play better than wolves, crashing after 3 seconds of black screen with error  -1. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14861918/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download cursed fabric launcher for btw
2. Download most recent version or PojavLauncher(at the time of writing)
3. Launch the jar folder for cursed fabric and set the better than wolves mod up
4. Attemp playing on standard settings including ram amount, render, jvm arguments, and jvm launch arguments
```

### Expected Behavior

I expected the mod to load as usual, even with a bit of lag, and work perfectly fine afterwards. 

### Platform

```markdown
- Device model: Amazon KFTRWI
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: edelweiss-20231217-031ad28-rew
```

**Comment by GaucovyAero** [comment]
check the pojav discord for fixes, cursed fabric and better than wolves need a patched and recompiled AppletMain.class file (as they are running an older version of fabric loader)

**Comment by GaucovyAero** [comment]
[INSTALL_BTW_updated_v1.1.pdf](https://github.com/user-attachments/files/16457001/INSTALL_BTW_updated_v1.1.pdf)

guide here, this should work
