### ISSUE TITLE
[BUG] server resource pack doesn't finish downloading

### ISSUE THREAD

**Issue by Chromekun** [PojavLauncherTeam/PojavLauncher#5313]
### Describe the bug

When joining a server with a server resource pack the download goes smoothly 98% of the way an then suddenly stops and never finishes, evan after hours of loading.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14886793/latestlog.txt)

Log output: No closing tokens 2 , somehow

### Steps To Reproduce

```markdown
1. Start Pojav
2. Open the newest release version of vanilla(1.20.4)
3. Join the cytooxien.de server
```

### Expected Behavior

I expect the dowload to finish

### Platform

```markdown
- Device model: Samsung Galaxy Tab S8 Ultra
- CPU architecture: Kryo
- Android version: 14
- PojavLauncher version: edelweiss 20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
turn on shader dump and send log again

**Comment by Chromekun** [comment]
> turn on shader dump and send log again

I turned on shader dump and updated the log

**Comment by GaucovyAero** [comment]
okay thanks

**Comment by GaucovyAero** [comment]
please test again on the latest github actions build, you might also try a build with the LTW renderer by going to our discord server
