### ISSUE TITLE
[BUG] Holy GL4ES - (All versions, fast) Renderer glitches In v1.16.5 And Also Cant install .jar files

### ISSUE THREAD

**Issue by Flysakib** [PojavLauncherTeam/PojavLauncher#5314]
### Describe the bug

In Version 1.16.5 Most of the world Chunks are gone and it glitches
![2024-04-05_00 35 34](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165303806/078cdf1e-f1f2-4468-865a-9e342e8bb20b)
![2024-04-05_00 35 48](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165303806/b057497d-4e9b-4eb7-8fbf-d00ba5ee4129)
![2024-04-05_00 36 45](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165303806/0fad1dee-37b1-48aa-aaaa-b265278d0545)
And Also Another bug i Cant install any type of .jar file
When i try to install a .jar file the game crashes and the error message says "Application/Game Exited With Code 1 check latestlog.txt for more details"
![Screenshot_20240405-003704_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165303806/6a16e3e5-c234-4293-a078-13a9b4fefec5)

### The log file and images/videos

Here Is The Latestlog.txt File
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14876020/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Options
3. Video and Renderer
4. Renderer
5. Select Holy GL4ES - (All versions, Fast)
6. Select v1.16.5 and play
7. Create New World
8. Walk Around
9. Quit the game
10. Install .jar file 
11. Optfabric 1.16.5.jar (then my game crashes)
12. Try to walk forward in v1.20.4 or play the game for a while
```

### Expected Behavior

In version 1.20.4 the controls are kind glitchy when i press forward it works 2 seconds laters in the game . it happens with all the other keys 

### Platform

```markdown
- Device model: Samsung Galaxy M21
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Just Please Fix those Issues as soon as possible.

**Comment by artdeell** [comment]
Turn off Render Regions. Also, send latestlog.txt after running a .jar file.

**Comment by Flysakib** [comment]
I got it The render regions and fast math = game crash and glitches
Here is the latestlog.txt after installing a .jar file 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14881167/latestlog.txt)
And also why the holy fast renderer glitches in v1.16.5? Does this have any solution?

**Comment by GaucovyAero** [comment]
> I got it The render regions and fast math = game crash and glitches Here is the latestlog.txt after installing a .jar file [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14881167/latestlog.txt) And also why the holy fast renderer glitches in v1.16.5? Does this have any solution?

probably no solution to the renderer glitching but with the execute jar, you are trying to launch a mod, mods are not launchable even on pc lol, just put it into the mods folder

```
no main manifest attribute, in /data/user/0/net.kdt.pojavlaunch/cache/optifabric_1.16_1.17_1.11.18.jar
```
