### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by GAMERGENIX2** [PojavLauncherTeam/PojavLauncher#5317]
### Describe the bug

I joined servere name sirius mc which have skybattle releam then I proceed it resource pack and my game get crash after pack load

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14879477/latestlog.txt)

### Steps To Reproduce

```markdown
Strt pojav 1.20.1 
Join siriusmc.in
Then in server join skybattle releam
Then proceed it's recourse pack 
After loading game crash
```

### Expected Behavior

I don't know 

### Platform

```markdown
- Device model: CPH2179
- CPU architecture: aarch64 proccesr rev 4
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
turn on shader dump, send the log again and change the issue title

**Comment by GAMERGENIX2** [comment]
> turn on shader dump, send the log again and change the issue title

Shaders don't work

**Comment by GAMERGENIX2** [comment]
And see up I had sended log file

**Comment by GaucovyAero** [comment]
> And see up I had sended log file

you did not turn on the shader dump in the pojav settings
the shaders that the server is using are causing the crash, thats why the shader dump exists, it logs the code of the shaders and the conversion into the log

**Comment by GaucovyAero** [comment]
stale
