### ISSUE TITLE
[BUG] <Scrolling bug on forge and vanilla>

### ISSUE THREAD

**Issue by VeensCal** [PojavLauncherTeam/PojavLauncher#5318]
### Describe the bug

I can't scroll in forge and vanilla like cloud client

### The log file and images/videos

No logs 

### Steps To Reproduce

```markdown
1.open pojav launcher
2.install forge
3.install random client example cloud client
4.open click GUI Rshift
5.scroll won't work
```

### Expected Behavior

If I press scroll on cloud client (forge mod btw) it won't work

### Platform

```markdown
- Device model: Realme c25
- CPU architecture: maliG57 I think
- Android version: 13
- PojavLauncher version: 
Edelweisss version playstore
```

### Anything else?

That's all

**Comment by VeensCal** [comment]
Fabric scroll is work not forge

**Comment by VeensCal** [comment]
My phone is arm64

**Comment by GaucovyAero** [comment]
cant reproduce the issue on forge, im quite sure this is just cloud's issue, you can workaround the issue by just using search, closing
