### ISSUE TITLE
[F-Req] Fix the app thinking that you have an xbox controler

### ISSUE THREAD

**Issue by Frostybtfindingscript** [PojavLauncherTeam/PojavLauncher#5319]
### Is this request related to a bug?
 Update i have figured it out my finger print sensor was causing it.
-I have made a bug report about this one but its been weeks I'ved deleted every keyboard apps and controler apps relate nothing really worked, i waited for an hour to load up one of my version's just to be quickly get destroyed by the "Waiting For [A,X,B,O] Button" I can't take it anymore.
![Screenshot_20240405-161014](https://github.com/PojavLauncherTeam/PojavLauncher/assets/100270583/d7e44c13-049b-426d-b5c2-9fb5495e7a83)-

**Comment by GaucovyAero** [comment]
attach a log please

**Comment by Frostybtfindingscript** [comment]
> attach a log please

I have figured it out, it was just my fingerprint and i have to literally suffer with an xbox cross in the middle
