### ISSUE TITLE
[F-Req] This mod should support Holy GL4ES

### ISSUE THREAD

**Issue by Arthurwilson990** [PojavLauncherTeam/PojavLauncher#5320]
###### Is this request **related** to a bug?

The mod called 'realtrainmod' also known as rtm mod crashes sometimes in holy GL4ES in version 1.12.2. This mod crashes if placed too much tracks together in flat world.

### Describe the request.

Pls provide support to the mod on holy GL4ES and fix the crash. (And interesting thing is that using zink {vulkun} can handle the crash but i only get 20 fps on 2 render chunks).

### Anything else?

When I played in that flat world without using tracks i averagely get around and the mod i use cause sudden drop in fps which is about 20-35 fps around.                               
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14892135/latestlog.txt)

**Comment by GaucovyAero** [comment]
turn on the shader dump and send log with gl4es

**Comment by Arthurwilson990** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14888143/latestlog.txt)
Well. If you are able to fix it pls inform me. ;)###

**Comment by Arthurwilson990** [comment]
Btw what is shader dump?

**Comment by GaucovyAero** [comment]
it is a setting that enables us to see whats the issue with converting your mod's shaders

**Comment by GaucovyAero** [comment]
stale issue
