### ISSUE TITLE
[BUG] Minecraft Error633 Version Creepypasta

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5323]
### Describe the bug

Minecraft Error633 Stack In Loading Mojang

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14892347/latestlog.txt)

### Steps To Reproduce

```markdown
Install Version Minecraft Error633 Creepypasta
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try removing options.txt and using the betacraft proxy
```
-Dhttp.proxyHost=betacraft.uk -Djava.util.Arrays.useLegacyMergeSort=true
```

**Comment by Dilen0001** [comment]
Fixed getting stuck while loading mojang
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14892877/latestlog.txt)

**Comment by GaucovyAero** [comment]
> Fixed getting stuck while loading mojang [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14892877/latestlog.txt)

is it working or not?

**Comment by Dilen0001** [comment]
Still Not Working

**Comment by GaucovyAero** [comment]
> Still Not Working

remove options.txt

**Comment by Dilen0001** [comment]
Even though I have deleted option.txt, there is still a problem loading Mojang

**Comment by GaucovyAero** [comment]
> Even though I have deleted option.txt, there is still a problem loading Mojang

send log again

**Comment by Dilen0001** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14893728/latestlog.txt)

**Comment by GaucovyAero** [comment]
no idea, try it in a fresh .minecraft folder

**Comment by GaucovyAero** [comment]
stale issue
