### ISSUE TITLE
[BUG] Pojavlauncher Failed to download Minecraft 

### ISSUE THREAD

**Issue by GtzFighter** [PojavLauncherTeam/PojavLauncher#5325]
### Describe the bug

None of my servers were loading at all then i pressed the refresh button super fast but nothing worked so i reinstalled pojavlauncher then the pojavlauncher said " Failed to download Minecraft! This could be due to bad network connection, incorrectly placed files, ect.. And no versions would load and nothing works

### The log file and images/videos

![Screenshot_2024-04-06-14-11-51-21_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166210778/38c14a30-bb63-41f4-add7-eab51b0a81a1) 

### Steps To Reproduce

```markdown
There is no way to reproduce it judging by my experience.
```

### Expected Behavior

I expected for it to run normally after the reinstallation 

### Platform

```markdown
- Device model: Realme Narzo 30a 4/64G
- CPU architecture: arm64 
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I was using an auto clicker i may have forgot to close it . So i think that my auto clicker just destroyed the app . But at first i just loaded in on my friends server but out of nowhere disconnected, nothing worked, but then the server loaded again and boom disconnected again, then it never loaded up again and now i am stuck here .

**Comment by GaucovyAero** [comment]
click show more and send the output here

**Comment by GtzFighter** [comment]
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:795)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:73)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:54)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:823)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:708)
	... 6 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8092)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 10 more

**Comment by GtzFighter** [comment]
This is what it said

**Comment by GaucovyAero** [comment]
select 1.7.10 from the release list, not from installed versions

**Comment by GtzFighter** [comment]
As i mentioned in the " Describe the bug " there are no versions

**Comment by GtzFighter** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/166210778/d16bcd82-6641-46b8-a9b6-de49c18ab55c

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۴-۰۶-۱۹-۰۳-۳۵-۹۶۰_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/0bcb3194-c44c-42f6-b8c6-1ddbf21a0107)
Set it to default in researching i do BMCLAPI is no so much good but i seted to default and it's fixed

**Comment by GtzFighter** [comment]
I don't have that option though

**Comment by ghost** [comment]
You need to download pojav launcher version in GitHub not google play in google play updates scarcely

**Comment by GtzFighter** [comment]
Oh well i find the GitHub version super hard to download soo a little help would be really appreciated

**Comment by ghost** [comment]
It's not really hard. in pojav launcher GitHub website go in actions and download the latest version and click in app debug. And go to google play download a another app name is zarchiver a file manager and click it and go to download folder and you find app_debug.zip click it and have many options open you just choice extract here and you extracted two another files you go to click the app_debug.apk and download it. And works very well. its safe to use

**Comment by GtzFighter** [comment]
Well yes i know that part but there's like a thousand files so i get a little confused there

**Comment by ghost** [comment]
You have many files in download folder. You can search it in
![Screenshot_۲۰۲۴-۰۴-۰۸-۲۲-۳۴-۴۵-۷۱۰_ru zdevs zarchiver-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/546695e1-8a8a-40e2-b93d-91694d4b3dcc)

**Comment by GtzFighter** [comment]
No i do know how to use ZA Archiver but there are a few thousand files in GitHub so i get confused on which one to download

**Comment by ghost** [comment]
Download latest update 
![Screenshot_۲۰۲۴-۰۴-۰۹-۱۴-۳۰-۳۷-۹۰۹_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/b6636eeb-015a-4473-9f66-3e56abe01a07)

**Comment by GtzFighter** [comment]
No like i meant in the GitHub , there are a few thousand files so i get super confused on which one to download

**Comment by Algiuxs** [comment]
Just download the app-debug.apk

**Comment by moserkoter** [comment]
> Just download the app-debug.apk

I downloaded app-debug from github, but I still can't download minecraft.

**Comment by Algiuxs** [comment]
As said choose the version from release, not from installed list

**Comment by GtzFighter** [comment]
Yes i know , oh and my internet was the problem... The router was bugging out so i set it up again now it works. Sorry for giving you guys a headache...

**Comment by kasrarouhi** [comment]
![Screenshot_2024-04-27-16-06-39-360_com android settings-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/f702b195-d8ed-40c0-a21d-b2b9a4b93fc5)
Try this in developer option on your phone

**Comment by ghost** [comment]
![Screenshot_2024-04-27-16-06-39-360_com android settings-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/1ac4c33f-056e-487e-8b65-3d04d3040cce)
Okay but in anytime your internet have problem try this

**Comment by IndianBoy420** [comment]
I tried it but didn't worked

**Comment by ghost** [comment]
Download new pojav GitHub version and try again if doesn't work again delete pojav and download it again

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۷-۰۶-۲۰-۳۳-۱۱-۳۶۶_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/9520d65d-136b-474c-8da3-d43b9b1dc865)

be sure you enable this setting in default is enabled and if you disable it in long time show network error and only way to fix its delete pojav and download again

**Comment by IndianBoy420** [comment]
I enabled that option, did everything you said . But same problem showing

**Comment by ghost** [comment]
Well i can't fix your problem so you need to report it in pojav website to developer handle it

**Comment by IndianBoy420** [comment]
How to report on pojav website

**Comment by ghost** [comment]
You reported
