### ISSUE TITLE
[BUG] Updated my bug with latestlog.txt 

### ISSUE THREAD

**Issue by Arthurwilson990** [PojavLauncherTeam/PojavLauncher#5326]
### Describe the bug

It's the rtm mod i have Been talking about since yesterday. SO here's the latest log file.        

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14893107/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher 1.12.2 with using the rtm mod.(Enable GL4ES)
2. Enter a flat world and starting creating tracks.
3. Render distance 5.
4. Place 5-6 long tracks.
5. And it crashes.
```

### Expected Behavior

I expected better performance while  playing the mod . With single track 1 get 150-190 fps and after too much of placing it the fps drops by 100 fps and I barely get 30 fps.

### Platform

```markdown
- Device model: MT6833G
- CPU architecture: 2x arm cortex A76 @2.20GHz,6x arm cortex @2.00 GHz
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
remove phosphor and try again

**Comment by Arthurwilson990** [comment]
Ok

**Comment by ghost** [comment]
Rl craft have phosphor mod and it doesn't have any problem in my phone just change light in minecraft in 1.12.2

**Comment by GaucovyAero** [comment]
stale
