### ISSUE TITLE
java

### ISSUE THREAD

**Issue by ilovepandas1** [PojavLauncherTeam/PojavLauncher#5327]
### Describe the bug

how do you get java 21 cuz I cant play the newest snapshot without it

### The log file and images/videos

file:///home/chronos/u-82d2d8006cdf54a3389a1688669f4a5ac75c55a0/MyFiles/Downloads/Screenshot%202024-04-06%205.49.21%20PM.png

just paste the into the web

### Steps To Reproduce

```markdown
just go on the newest snapshot without java 21
```

### Expected Behavior

idk

### Platform

```markdown
- Device model: idk
- CPU architecture: idk
- Android version: idk
- PojavLauncher version: 1.20.4
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
check the android-openjdk-build-multiarch repository

**Comment by ilovepandas1** [comment]
????

**Comment by ilovepandas1** [comment]
what that
