### ISSUE TITLE
[BUG] <Multi-touch not working>

### ISSUE THREAD

**Issue by JankleDev** [PojavLauncherTeam/PojavLauncher#5328]
### Describe the bug

i updated my android (rmx3761) to android 14 last night and when tried to use pojav launcher it only detects 2 touches at a time. so i can't play with 3 fingers becayse when i put my third finger on screen it stops detecting until i remove all of them.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14895750/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Try doing multiple touches at a time.
```

### Expected Behavior

I expect it to work normally like before.

### Platform

```markdown
- Device model: Realme Narzo N53 4/64G
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: Latest OpenJDK_v3 build
```

### Anything else?

https://github.com/PojavLauncherTeam/PojavLauncher/assets/91403810/7415971c-cc5d-45dc-9da8-a34cf57c7d78

**Comment by JankleDev** [comment]
update: other apps are also unable to track my touch movements but system can.
update: some apps like bgmi or Google board/SwiftKey keyboard work

**Comment by GaucovyAero** [comment]
apparently on realme phones the solution is to disable gesture shortcuts like 3-finger screenshot, etc.
