### ISSUE TITLE
Disable gesture option not working 

### ISSUE THREAD

**Issue by GAMERGENIX2** [PojavLauncherTeam/PojavLauncher#5330]
### Describe the bug

I on disable gesture option but in game when I put my finger on my phone then it automatically started breaking blocks and hitting someone 

### The log file and images/videos

No log file it just happen normally 

### Steps To Reproduce

```markdown
Strt pojav go to world or multiplayer and long press on screen it automatically start breaking
```

### Expected Behavior

I am not holding any key and also disable geasure option but it stil happening 

### Platform

```markdown
- Device model: CPH2179
- CPU architecture: aarch64 proccesr rev 4
- Android version: 10
- PojavLauncher version: Fix[input]: also check for double taps on ACTION_DOWN/ACTION_POINTER_…
```

### Anything else?

Nope plz fix the disable geasure option

**Comment by GaucovyAero** [comment]
non-mainline build
