### ISSUE TITLE
UI customization for Pojav? 🤔

### ISSUE THREAD

**Issue by grosioso** [PojavLauncherTeam/PojavLauncher#5331]
### Is this request related to a bug?

This might be a dumb question, but I have ALWAYS imagined custom themes being enabled in Pojav, instead of like dull, boring gray/black color. it's not because this ui sucks, but I want to see customizable UI being officially released for Pojav.

### Describe the request.

Here's how it works through my concept(its sometimes bad but i seriously tried my best making these):

Button for UI customization:

![Untitled2_20240407101018](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/669626fc-9d68-4eb6-82bf-11427bcbf26e)

This button can basically let you change the UI style (light/dark/system default theme, custom backgrounds that can be stretched or filled and background tiles) to make it customizable.

Light theme:

![Untitled1_20240407101050](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/c617a7c4-fbf2-4a6b-a23d-26acbbc9f68a)

Custom backgrounds and tiles:

![Untitled3_20240407101855](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/cc2a6dc6-e538-4aca-9459-803cfd9ccc95)

Since I don't have much time to make this concept (because my battery is low), it is OK I guess. also, speaking of tiles, here are the tiles you need to put:

1. Dirt
2. Grass (top layer)
3. Stone
4. Cobblestone
5. Bedrock
6. Planks
7. Blackstone
8. Netherracks

i almost forgot to say, the build name should be called "enderplanks" or any name. You can make pre-releases in GitHub to release the packages and right after the new feature being completed, you can release it in Play Store.

that's all I need, thank you.

### Anything else?

This change is inspired by HMCL-PE ui customization.

**Comment by GaucovyAero** [comment]
not coming soon

**Comment by grosioso** [comment]
> not coming soon

yeah why

**Comment by grosioso** [comment]
yknow what forget it

**Comment by grosioso** [comment]
I should’ve became braindead just for this

**Comment by agent1243** [comment]
your idea is very good, foldcraft already has this
