### ISSUE TITLE
[BUG] Modpack Valhelsia: Plasma

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5334]
### Describe the bug

Modpack Valhelsia: Plasma In The World Minecraft

### The log file and images/videos

![Screenshot_20240408_120823](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/56bfd3cc-4d72-44b9-a3c4-53d8b3ce81a1)

### Steps To Reproduce

```markdown
Install Modpack Valhelsia: Plasma Version 1.20
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use zink if your device supports it, this will likely be fixed in the next play store updated but i dont think its coming any soon
