### ISSUE TITLE
Community issue

### ISSUE THREAD

**Issue by RelaxingNostalgia** [PojavLauncherTeam/PojavLauncher#5335]
### Describe the bug

i tried getting into the discord community to get help over a question/issue and i was treated like less than a human being simply for not owning an official copy of the game,and instantly banned(wasnt exactly banned but was limited only to the off-topic chat which dosent make any difference between that and being banned,because why in the hell would i want to stay in a server only to talk about topics not related to the server,the only reason the moderators probably dont insta ban is to not get much backlash or be still perceived as morally good).

this seems to be a common issue even inside the pojavteam you guys have somenthing personal against people pirating the game,you have to understand that not everyone is white privileged and lives in a first world country,there's human beings outside of U.S and Europe who made other countries their colonies,we are human beings just as you are and have bills to pay just like you have i was treated like a thief and actually it is a fact that winthin the U.S law piracy of software is not actually stealing but its a copyright infringment.

anti piracy measures never ever in the history of gaming have reached the desired effect,it always reached the opposite,Gabe Newell explained this

https://youtu.be/pLC_zZ5fqFk

the way i was treated in discord community only convinced me,to never actually buy an official copy of minecraft
i know that this will probably get ignored as i doubt anyone in the team has any idea of what is the world outside of their point of view and i will be treated as thief regardless(even though it is explicit in the U.S law that is not)
but i had to try.

i live in a country that was both colony of europe,and a victim of U.S imperialism.
we helped you guys in ww2 and this is how we are treated,worse than garbage.

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
.
```

### Anything else?

.

**Comment by RelaxingNostalgia** [comment]
im 100% sure even YOU guys already pirated somenthing at some point in your lifes,specially because according to the law even making a copy backup of a game you legally own is already piracy,thats in the law youre only allowed to make a backup of a computer program,and videogames(many werent even developed in machines defined as computers) dont fall in such definition,even the offficial Nintendo website states this.

https://www.law.cornell.edu/uscode/text/17/117

**Comment by catofworld123** [comment]
Seems like a skill issue

**Comment by catofworld123** [comment]
Get a job idk

**Comment by RelaxingNostalgia** [comment]
> Seems like a skill issue

actually i have more skill than you will ever have,and i m disabled by the way

https://youtu.be/LDHbs3Hut9Y

**Comment by catofworld123** [comment]
Reset your roblox character to get more luck

**Comment by catofworld123** [comment]
And considering the way you speak, you are a 12 year old from Russia who's mom doesn't give you the credit card

**Comment by catofworld123** [comment]
Or a Brazilian mf

**Comment by catofworld123** [comment]
Idk

**Comment by catofworld123** [comment]
Get 20$ and buy the game lol thats not like buying a house

**Comment by RelaxingNostalgia** [comment]
> Get a job idk

**Comment by RelaxingNostalgia** [comment]
the discord moderator maturity lmao

**Comment by Nekotaco** [comment]
Insulting disabled person is crazy

**Comment by kiokori-git** [comment]
either way i don't know how did you even get treated like shit, even though you already sound like a cool guy, but apparently we can't help to the people that doesn't own minecraft/pirated it due to microsoft would litteraly take this project down, this already happened in the past as we did help the unverifieds and microsoft did sue us, not helping the pirates is what still makes this project still up, if you're from russia you can join the pojavlauncher russian server, but i do not know whats the invite link, but whatever.

not buying a copy of minecraft is your choice, just that we wouldn't be able to help you for crashes or issues, etc, we never had anything personal against piratinng, its really just because of microsoft.

bringing up about your country helped in WW2 is not a valid excuse.
i do feel bad about you being disabled, but again it shouldn't be an excuse.

also @catofworld123 you shouldn't be saying stuff such like that, like be human

**Comment by kiokori-git** [comment]
after reviewing the chats it seems that you're just exaggerating, no-one treated you like in-humanly

**Comment by khanhduytran0** [comment]
@RelaxingNostalgia
First of all, you weren’t banned, you were just limited to certain channels, including general where you're still allowed to talk about Pojav.
Second, we used to enforce game ownership requirement when one US member was threatened with lawsuit. It was then lifted for Android only.
You see, Nintendo sued Yuzu team and shut it down, in all of sudden. Now basically you’re forcing us to play with fire.
While we keep it for Android, you’re responsible for your actions and what happens, including crash bugs etc.

**Comment by alexytomi** [comment]
> not buying a copy of minecraft is your choice

This is just wrong. It's literally impossible or economically unviable to buy games in many many places. It's not always a choice.

**Comment by alexytomi** [comment]
> im 100% sure even YOU guys already pirated somenthing at some point in your lifes,specially because according to the law even making a copy backup of a game you legally own is already piracy,thats in the law youre only allowed to make a backup of a computer program,and videogames(many werent even developed in machines defined as computers) dont fall in such definition,even the offficial Nintendo website states this.
> 
> https://www.law.cornell.edu/uscode/text/17/117

This is a heavily debated topic and each government deals with it in their own way. Do not make such broad statements about the world unless the entire world is united in everything (it isn't)

**Comment by alexytomi** [comment]
You already get this shit for free, you have no right to demand mere unpaid volunteers to support your usecase, especially when doing so puts us at risk.

**Comment by ITLSupress** [comment]
> > not buying a copy of minecraft is your choice
> 
> This is just wrong. It's literally impossible or economically unviable to buy games in many many places. It's not always a choice.

This discussion would be better reserved for Mojang and Microsft no? 
They are the one that put the price on the game not us. They are the ones that set the rules stating what we can and can't do. And they are the ones that will sue everyone here for millions for distributing or attempting to assist with pirating copyright material.

Essentially Microsoft/Mojang has said that any attempt to distribute a pirated copy, assist or support pirated play, or even so much as discuss piracy surrounding the game they will follow up with action.

Not to mention any discussion of piracy violates discord TOS and can get the discord shut down. So you'd want to talk to them to.

Let me remind you that even so much as hosting a server cracked players can join violates the EULA that you agree to by playing the game in a multiplayer setting or running the server.

**Comment by GaucovyAero** [comment]
It's not just that pirating MC is illegal, it's also that a lot of people that do pirate aren't nearly as intelligent as you which makes support a lot harder if that kind of support is allowed (i remember late 2021)

**Comment by GaucovyAero** [comment]
just a heads up you can still make github issues and ask for help here

**Comment by catofworld123** [comment]
@Kiokingz yeah, i shouldn't talk like that, i apologise. I live in russia myself, where you cant buy (oficially) minecraft. But you still can get a license by using VPN's and other methods. @RelaxingNostalgia im sorry for what i've said, but dont think that the unverified conditions on the server are so bad.

**Comment by catofworld123** [comment]
i mesn im not trying to insult you, i say skill issue when there is a way to easily deal with a problem, but a person doesn't really want to do somethink ( i totally wasnt in a silly mood while typing all of that i said a couple of hours ago). And im not laughing at you because you are disabled, i was laughing at the fact thatits literally an easy fix to that problem.

**Comment by VenomousSteam81** [comment]
@GaucovyAero 
> just a heads up you can still make github issues and ask for help here

yeah but would we still help people?

**Comment by GaucovyAero** [comment]
> @GaucovyAero
> 
> > just a heads up you can still make github issues and ask for help here
> 
> yeah but would we still help people?

most probably yes
