### ISSUE TITLE
[BUG] Better Than Wolves servers doesnt work on pojav

### ISSUE THREAD

**Issue by catofworld123** [PojavLauncherTeam/PojavLauncher#5336]
### Describe the bug

I can join any server on non-btw version. I purchased minecraft. 
![Screenshot_2024-04-08-08-59-05-09_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/80473111/ac40a02e-1b44-4a00-97af-c6937dba4f9b)

I get a Bad login error.
Tried using github's betas but i cant even launvh BTW in the newest betas

### The log file and images/videos

![Screenshot_2024-04-08-08-59-05-09_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/80473111/525afb24-3342-475d-a52f-f6924849709a)

### Steps To Reproduce

```markdown
1) Start PoJavLauncher
2) Install BTW by instructions in discord
3) Try joining a server
```

### Expected Behavior

You get kicked with "Bad login" error

### Platform

```markdown
java 8
BTW CE 2.1.4 
Latest google play release
Android 10
OPPO A9 2020
```

### Anything else?

im stoopid

**Comment by catofworld123** [comment]
Yeah i got banned in a discord for a stoopid joke, definetly a skill issue lol

**Comment by catofworld123** [comment]
Reopened it because thats not a mod's error but rater a config error of PojavLauncher, because i get no errors in logs (both server and client)

**Comment by ITLSupress** [comment]
Newest BTW Beta (3.x) Requires Legacy Fabric and if that's the case it probably needs a different patch from the 2.x patch, though I can confirm from the BTW Discord that this is either an issue on Pojav's or Microsoft/Mojang Authentication side.

**Comment by catofworld123** [comment]
Definetly not Microsoft's side because it works on pc
BTW found a workaround: use AnyDesk to connect to my pc and play java

**Comment by GaucovyAero** [comment]
> Newest BTW Beta (3.x) Requires Legacy Fabric and if that's the case it probably needs a different patch from the 2.x patch, though I can confirm from the BTW Discord that this is either an issue on Pojav's or Microsoft/Mojang Authentication side.

if its using the latest fabric-loader version, it should not need any patchy patchy because the issue was fixed in official mainline fabric-loader some time ago

**Comment by GaucovyAero** [comment]
oh and if you cant launch btw, be sure to reach out via the pojav discord, create a thread and ping me

**Comment by ITLSupress** [comment]
I think the version Cat is still playing is still using that custom modified 1.5.2 fork of fabric loader. Installation and single-player works fine just seems to be multiplayer related.

**Comment by catofworld123** [comment]
Yes, i just followed the guide in pojav's discord

**Comment by catofworld123** [comment]
Also, @GaucovyAero i got banned in pojav's discord cor a stupid joke in the main chat, so i can only ask there. But i was verified, you can see my verification in the branches.

**Comment by RadiatedExodus** [comment]
@catofworld123 https://docs.google.com/forms/d/e/1FAIpQLSfbAH-LG52hXUExVcP4UENW0I0gGLCf8QfGR1YdgG5O0rmfQA/viewform?usp=sf_link

Do not post about Discord moderation issues here, it's not relevant.

**Comment by catofworld123** [comment]
yeah ok no problems

**Comment by VenomousSteam81** [comment]
@catofworld123 
> Definetly not Microsoft's side because it works on pc BTW found a workaround: use AnyDesk to connect to my pc and play java

that is NOT a workaround. you're literally just remotely controlling your computer and not running minecraft on your phone.

**Comment by catofworld123** [comment]
@VenomousSteam81 i know, thats a workaround just to play, but not a pojav's err workaround lol
+ the controls are impossible with AnyDesk

**Comment by catofworld123** [comment]
@GaucovyAero BTW doesnt work on the newest pojav's snapshots

**Comment by GaucovyAero** [comment]
> @GaucovyAero BTW doesnt work on the newest pojav's snapshots

send logs pls otherwise i have no idea whats going on

**Comment by catofworld123** [comment]
ok sure

**Comment by catofworld123** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14936961/latestlog.txt)

**Comment by catofworld123** [comment]
@GaucovyAero here it is.

**Comment by GaucovyAero** [comment]
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14936961/latestlog.txt)

i mean this is exactly what you get without the patch so i doubt anything changed really, just put the patched appletmain.class thats in discord into the cursed fabric libraries jar

**Comment by GaucovyAero** [comment]
[AppletMain.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/14937082/AppletMain.zip)

here it is zipped just in case

**Comment by catofworld123** [comment]
@GaucovyAero the problem is that i put in the patch

**Comment by catofworld123** [comment]
And it still crashes

**Comment by GaucovyAero** [comment]
yeah it seems to crash for me too but it exhibits the exact same symptoms, you can get further by like doing -Dfabric.gameVersion="1.7.3" (cause it does 1.0.0-beta.7.3 by default which pojav isnt able to parse for whatever reason in this instance) and then you get a tinyremapper issue, so you get a remapped jar and then i havent tested but i think its gonna be a black screen with a window showing up that cannot be shown on pojav because two windows at the same time aint possible

**Comment by GaucovyAero** [comment]
but it might just be that i have to recompile the appletmain class for the latest version of the loader but i doubt thats the case, who knows

**Comment by catofworld123** [comment]
But how do i fix the server err?

**Comment by catofworld123** [comment]
So, i just wait till fix right?

**Comment by GaucovyAero** [comment]
> But how do i fix the server err?

you cant

**Comment by catofworld123** [comment]
So i just wait, right?

**Comment by GaucovyAero** [comment]
yeah but the fix might not come

**Comment by catofworld123** [comment]
Yay

**Comment by GaucovyAero** [comment]
attaching the updated install guide for foxglove here, prolly does not fix the server issue tho

[INSTALL_BTW.pdf](https://github.com/user-attachments/files/16446630/INSTALL_BTW.pdf)

**Comment by GaucovyAero** [comment]
[INSTALL_BTW_updated_v1.1.pdf](https://github.com/user-attachments/files/16457029/INSTALL_BTW_updated_v1.1.pdf)

this one should in theory actually fix the server issue, usernames and skins now work instead of you being just "Player"
