### ISSUE TITLE
Exit with code 1 when playing Minecraft version above 1.16.5

### ISSUE THREAD

**Issue by ImNotTheChiku35** [PojavLauncherTeam/PojavLauncher#5338]
### Describe the bug

When I play any (Minecraft) version above 1.16.5, it exit with code 1.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14913437/latestlog.txt)

[Video](https://github.com/PojavLauncherTeam/PojavLauncher/assets/162564754/efa2d603-1d22-4185-a2c1-6f227bae0e72)

### Steps To Reproduce

```markdown
1. Open PojavLauncher.
2. Play any Minecraft version from 1.17 to 1.20.4.
```

### Expected Behavior

I can play the Version without the error.

### Platform

```markdown
- Device model: RMX1971 (Realme 5 Pro)
- CPU architecture: Aarch64 (ARM64)
- Android version: 11
- PojavLauncher version: edelweiss-20240409-a85af24-feat/touch_event_refactor_2
```

**Comment by GaucovyAero** [comment]
it says mc isnt downloaded, make sure you have check libraries checked

**Comment by ImNotTheChiku35** [comment]
![Screenshot_2024-04-09-12-05-48-28_67a64f1fc1b88908dad3392f76c1969b.jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/162564754/ba88b5ef-7616-49a6-b3c3-db246db13ad3)
