### ISSUE TITLE
Access to the restricted Android/data folder for mods needing to download stuff.

### ISSUE THREAD

**Issue by Nucceteere** [PojavLauncherTeam/PojavLauncher#5339]
### Is this request related to a bug?

No. It is not.

### Describe the request.

Some mods need to download files to the game directory, but can't because of the restrictions of the File app on newer Android versions. ZArchiver solved this by requesting the user to downgrade the File app (not Google Files) and then redirecting to the file apps info page where you click the uninstall updated and then downgrade it. Then they ask you to specify the folder of the obb folder by sending you to inside of the File App inside the folder that needs permissions to be granted. You click the use this folder and it prompts you to confirm. When you do that, now the app has access to that specific restricted file. Add an option in the settings to enable this incase they may be using mods that require to download files.

### Anything else?

This problem was discovered when testing the Loqui mod. A centralised hub for translations for Minecraft mods. See [IMB11/Loqui](https://github.com/IMB11/Loqui) and [mineblock11/loqui-translations](https://github.com/mineblock11/loqui-translations) for info.

**Comment by artdeell** [comment]
You can transfer files into the Pojav's game directory using the Storage Access Framework file provider, accessible from the AOSP Files app. Mods running within Pojav should already have the required permission to download to this folder/access internet/etc.

**Comment by GaucovyAero** [comment]
use com.marc.files from the play store if the default aosp files app is not accessible by default on your device
