### ISSUE TITLE
[BUG]  Zink renderer is keep crashing.

### ISSUE THREAD

**Issue by Nighvisit** [PojavLauncherTeam/PojavLauncher#5340]
### Describe the bug

I use beta version of pojavlauncher. I update my launcher after almost 2 months. Everything was perfect until I try to load mod in Zink renderer and it crashed. Later I try to change version of the launcher but it didn't work. I try to use vanilla minecraft it also crashed. Also the play store version is perfectly fine.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14926698/latestlog.txt)

### Steps To Reproduce

```markdown
It crashes immediately when the main load start.
```

### Expected Behavior

Please make the Zink renderer usable.

### Platform

```markdown
- Device model: Samsung galaxy M-31
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Any latest beta release
```

**Comment by Dilen0001** [comment]
.

**Comment by Marshall2439** [comment]
What mod do you use?

**Comment by GaucovyAero** [comment]
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G72) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
```
your gpu does not meet base zink requirements
you can try using solcraftlauncher, it should have builds with legacy versions of zink

**Comment by TERMKIEL** [comment]
Yeah same to me

**Comment by kasrarouhi** [comment]
> ```
> WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G72) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
> ```
> 
> your gpu does not meet base zink requirements you can try using solcraftlauncher, it should have builds with legacy versions of zink

Or virgl
