### ISSUE TITLE
app/game closed with the code -1, check latestlog.txt for more details

### ISSUE THREAD

**Issue by palitodefosforo** [PojavLauncherTeam/PojavLauncher#5343]
### Describe the bug

minecraft loads and before it finishes, said bug happens and it crashes

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14932043/latestlog.txt)

### Steps To Reproduce

```markdown
1. run the game on forge 1.18.2 40.2.18 with the mods on the file installed
2. wait
```

### Expected Behavior

i expected the game not to crash 

### Platform

```markdown
- Device model: Samsung galaxy m54
- CPU architecture: exynos 1380
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3-openjdk
```

**Comment by GaucovyAero** [comment]
mali gpus cannot run create on gl4es (try using zink, if it doesnt work then you prolly gotta use an older version of pojav with virgl or solcraftlauncher)
also, create is probably not even compatible with optifine

**Comment by grosioso** [comment]
what Java version u use?

**Comment by agent1243** [comment]
Do you know why mod create doesn't work in gl4es?

**Comment by GaucovyAero** [comment]
> Do you know why mod create doesn't work in gl4es?

because you dont have a snapdragon

**Comment by agent1243** [comment]
I understand, my cell phone is a Meditek Mali G52, that must be why
