### ISSUE TITLE
[BUG] Forge 1.7.10 giving a permanent black screen

### ISSUE THREAD

**Issue by Nulleer** [PojavLauncherTeam/PojavLauncher#5344]
### Describe the bug

Launching the game gives me a black screen, no matter how long I waited, it's still a black screen. 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14935457/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav
2. Create new profile
3. Choose the latest 1.7.10 forge version
4. Play
```

### Expected Behavior

I expected it to start normally, like how vanilla did. 

### Platform

```markdown
- Device model: oppo f1s
- CPU architecture: arm64-v8a, armeabi-v7a, armeabi
- Android version: 6.0
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?
Tried finding solutions to this issue, but was only able to find ones for older versions.

**Comment by GaucovyAero** [comment]
![Screenshot_20240411-161633_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/998b63a2-756a-4a76-a80d-8b15c695a09f)

cannot reproduce, try using the latest github actions build (installation guide is on the wiki)
