### ISSUE TITLE
embbedium on pojav

### ISSUE THREAD

**Issue by Proaman7603** [PojavLauncherTeam/PojavLauncher#5345]
### Is this request related to a bug?

Is it possible to run embeddium Or rubidium mod in pojav. 
Pls tell  me pls 😭😭

### Describe the request.

I want to use embbedium mod in forge

### Anything else?

No

**Comment by Marshall2439** [comment]
This isnt place for asking stuff bro this is for actual issues not talking platform

**Comment by Marshall2439** [comment]
You can use rubidium with its patch given on website of pojavlauncher paste it in .jar file of rubidium mod then you could use it but it wont work on most devices it may need zink renderer
