### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by gameflee** [PojavLauncherTeam/PojavLauncher#5347]
### Describe the bug

0

### The log file and images/videos

skin bast

### Steps To Reproduce

```markdown
Pojavlauncher
```

### Expected Behavior

free

### Platform

```markdown
- Device model: 10
- CPU architecture: 500
- Android version: 14
- PojavLauncher version: 1.20.4
```

### Anything else?

free pls

**Comment by VenomousSteam81** [comment]
get minecraft yourself when
