### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by S1nka2** [PojavLauncherTeam/PojavLauncher#5349]
### Describe the request.

I would like to ask how to make maximum performance in podjavlauncher, I downloaded a lot of mods, I did everything but there was no progress, maybe someone knows?

### Anything else?

- Device model:Redmi note 11 pro 5g 6/128g(google experience firmware)
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484dOc-v3_openjdk
-

**Comment by GaucovyAero** [comment]
pojavoptimize, check the pojav discord
