### ISSUE TITLE
[BUG] can't play on 1.16.4

### ISSUE THREAD

**Issue by t5xc** [PojavLauncherTeam/PojavLauncher#535]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Nothing more? Without log?

**Comment by ghost** [comment]
Android 10 don't work
Using vmos

**Comment by khanhduytran0** [comment]
> I download 3.3.1 and 1.16.4 works
