### ISSUE TITLE
1.17.1 exited with code 1

### ISSUE THREAD

**Issue by milosnail** [PojavLauncherTeam/PojavLauncher#5350]
### Describe the bug

when i launch the game in 1.17.1 it kept crashing

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14952278/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. launch the game in 1.17.1
```

### Expected Behavior

I expect it to work

### Platform

```markdown
- Device model: SM-T295
- CPU architecture: arm64
- Android version: Android 11
- PojavLauncher version: latest github actions
```

**Comment by GaucovyAero** [comment]
minecraft is missing in your instance, cannot reproduce
![Screenshot_20240412-132645_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/7db565dc-e727-4822-bce8-eb91b68fdac7)

**Comment by milosnail** [comment]
> minecraft is missing in your instance, cannot reproduce
> ![Screenshot_20240412-132645_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/7db565dc-e727-4822-bce8-eb91b68fdac7)
> 

welp i guess i gotta stick to gplay release

**Comment by milosnail** [comment]
> minecraft is missing in your instance, cannot reproduce
> ![Screenshot_20240412-132645_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/7db565dc-e727-4822-bce8-eb91b68fdac7)
> 

i tried redownloading everything and installed 1.20.1 and it's the same problem
