### ISSUE TITLE
The folder this app uses is inaccessible in the latest versions of android

### ISSUE THREAD

**Issue by Hoontarius** [PojavLauncherTeam/PojavLauncher#5351]
### Is this request related to a bug?

I physically cannot open the folder to add mods of any kind in any way shape or form, the folder does not appear in /Android/Data

### Describe the request.

I physically cannot open the folder to add mods of any kind in any way shape or form, the folder does not appear in /Android/Data
Please add a way to add mods to a version from within the app itself as currently I cant unless its a modpack already approved on curseforge

### Anything else?

This is something that is really only the case for REALLY new android cuz you cant actually alter things in the Android Data and Obb folders

**Comment by ghost** [comment]
Use files by marc

**Comment by Frostybtfindingscript** [comment]
You can still do the move/copy on the .marc files app by doing split screen and new window
I have manage to put mods on android 13 using it. Hope this helps!
(The picture below is what it would look like)

![Screenshot_20240412-112350](https://github.com/PojavLauncherTeam/PojavLauncher/assets/100270583/83dc8f6c-039b-482c-b526-382318daa501)

**Comment by Hoontarius** [comment]
That file manager tells me its unsupported for my phone

**Comment by Hoontarius** [comment]
![Screenshot_20240411_233928](https://github.com/PojavLauncherTeam/PojavLauncher/assets/155866992/c6e4f10d-40e0-4202-b418-8657a30f0fbe)
![Screenshot_20240411_233924](https://github.com/PojavLauncherTeam/PojavLauncher/assets/155866992/be67bf9a-b29a-4927-b19c-d4ddd9a2d6b2)

**Comment by Hoontarius** [comment]
So now what?

**Comment by Frostybtfindingscript** [comment]
> ![Screenshot_20240411_233928](https://private-user-images.githubusercontent.com/155866992/321847970-c6e4f10d-40e0-4202-b418-8657a30f0fbe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTM3ODUsIm5iZiI6MTcxMjg5MzQ4NSwicGF0aCI6Ii8xNTU4NjY5OTIvMzIxODQ3OTcwLWM2ZTRmMTBkLTQwZTAtNDIwMi1iNDE4LTg2NTdhMzBmMGZiZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMzQ0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2ZkOTUxNDc1OTQwYjI2NzM4ODVhMjdhMGYwZmMyY2Y3OWVlMWIzMTlkNDBiZjk2YmRmM2M0Y2U0NTBhNWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FVwrsytS6cY6uiUsMUqDUeuVcBd8edybpjWFjqeDbLM) ![Screenshot_20240411_233924](https://private-user-images.githubusercontent.com/155866992/321847983-be67bf9a-b29a-4927-b19c-d4ddd9a2d6b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTM3ODUsIm5iZiI6MTcxMjg5MzQ4NSwicGF0aCI6Ii8xNTU4NjY5OTIvMzIxODQ3OTgzLWJlNjdiZjlhLWIyOWEtNDkyNy1iMTljLWQ0ZGRkOWEyZDZiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMzQ0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWM1OGYzM2Y4ZTg2OWZiNjgxZmZmOThhNTRhYTgzOGM4NWNlNGYyZmYyNTE0ZTUyZTIxNGRmZWYxYjRlYjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h6DRefAP2AVrtap-_NUp3N-v0p8ZuUaLAHLFoeReTlQ)
 
What phone brand do you use?

**Comment by Hoontarius** [comment]
Redmagic 9 Pro

**Comment by GaucovyAero** [comment]
what happens if you try to attach files, can you screenshot? also, you should be able to access the folder via PC

**Comment by ditt0132** [comment]
You can use FV file manager with Shizuku!
or Use Marc's file manager to make shortcut for System files app

BUT Pojav add support for Folder select thing it will really good cuz Two file manager are tooooo slow

**Comment by GaucovyAero** [comment]
yeah i guess you can use a file manager that supports shizuku
