### ISSUE TITLE
[BUG] Typing with CTRL key pressed makes message disappear

### ISSUE THREAD

**Issue by ditt0132** [PojavLauncherTeam/PojavLauncher#5352]
### Describe the bug
Type some text with CTRL key pressed just deletes all message before that charactor

### The log file and images/videos
None

### Steps To Reproduce

```markdown
1. Launch game
2. Make togglable CTRL key
3. When type, all character except last typed one disappear
```

### Expected Behavior

I except pressing ctrl not delete

### Platform

```markdown
- Device model: SM-N981N
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20240325-e90e78e-fix/gamepad_analog_trigger
- Software keyboard: Samsung Keyboard
```

**Comment by ditt0132** [comment]
Oops it looks it only happen when ctrl key is pressed!
ill change title and all to "text deletes when CTRL is pressed"
sorry for bad testing

**Comment by GaucovyAero** [comment]
can you reproduce this with gboard?

**Comment by GaucovyAero** [comment]
works as expected, this is also how it works on PC, it only deletes one word at a time tho, and only when you press the backspace key, closing
