### ISSUE TITLE
1.4.2 Not starting[BUG] <Short description>

### ISSUE THREAD

**Issue by nikitadan4pi** [PojavLauncherTeam/PojavLauncher#5353]
### Describe the bug

I can't start game. Mojang logo - all I can see

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14958771/latest.log)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Download Minecraft 1.4.6 withit mod
3. start
```

### Expected Behavior

All new version work correct. 1.12.2 with  internal java 1.8.0 working good

### Platform

```markdown
- Device model: Blackview Oscal C80
- CPU architecture: Arm64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by milosnail** [comment]
have you tried deleting the options.txt file?

**Comment by GaucovyAero** [comment]
you sent a log of 1.8.9 optifine running fine

**Comment by GaucovyAero** [comment]
stale
