### ISSUE TITLE
[BUG] Unable to add account

### ISSUE THREAD

**Issue by rcoundon** [PojavLauncherTeam/PojavLauncher#5354]
### Describe the bug

Using a Lenovo Chromebook IP Slim 3 14M868 I'm unable to add an account.

The stack trace suggests the account isn't found, however I have used the same login on another machine (though not at the same time).

### The log file and images/videos

Log file contains only the same as the stack trace below.

This is what shown after the error occurs in the error dialog:

```terminal
java.lang.RuntimeException: Not Found
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
```

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Add Account -> Microsoft Account
3. Sign In using Microsoft credentials
4. "Error: it seems like this account does not have a Minecraft profile. If you have Xbox Game Pass, please log in on https://minecraft.net/ and set it up"
5. Show More displays stack trace included above
```

### Expected Behavior

I expected to be able to add the account as it is confirmed to be correct and owns a Minecraft licence.

### Platform

```markdown
- Device model: Lenovo Chromebook IP Slim 3 14M868
- CPU architecture: Arm
- Chromebook version: 123.0.6312.112 (64-bit)
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try logging into minecraft.net first

**Comment by rcoundon** [comment]
I hadn't tried that as I'd assumed, wrongly it would seem, that the headless browser inside the PojavLauncher wouldn't have access to any session information from the main Chrome browser on the device.
However, it must as your suggestion worked, thanks!

**Comment by artdeell** [comment]
> I hadn't tried that as I'd assumed, wrongly it would seem, that the headless browser inside the PojavLauncher wouldn't have access to any session information from the main Chrome browser on the device. However, it must as your suggestion worked, thanks!

The browser in Pojav does not in fact interact with the system browser, it seems to be a funky caching implementation on MS's side according to #5370
