### ISSUE TITLE
[BUG] <Crash while trying to load sodium>

### ISSUE THREAD

**Issue by Jmbrand395** [PojavLauncherTeam/PojavLauncher#5357]
### Describe the bug

When I try to load my world in 1.16.5 with sodium it crashes with error code 1

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/81294872/ab14871e-bad4-4163-9c6b-159efd3003c6

### Steps To Reproduce

```markdown
1. Install the mods shown in the video
2. Start pojavlauncher
3. Click play
4. Load world
```

### Expected Behavior

I expected my world to load like normal

### Platform

```markdown
- Device model: RMX3771
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
send log

**Comment by longrironghang** [comment]
Why I cannot use sodium in 1.20.1

**Comment by longrironghang** [comment]
When I use sodium then it say sodium is to high fps  why we cannot use high fps 😡

**Comment by longrironghang** [comment]
Reply me please 😭

**Comment by alexytomi** [comment]
> When I use sodium then it say sodium is to high fps why we cannot use high fps 😡

use gl4es and optifine

sodium never said it would give high fps on phones

> Reply me please 😭

send logs??

**Comment by longrironghang** [comment]
Sorry but one question we can't use shader in render fast please reply me

**Comment by longrironghang** [comment]
One thing I noticed that I can't use physics mod in fabric please give me
this solution ❤️❤️

**Comment by longrironghang** [comment]
When will update pojav launcher please reply

**Comment by GaucovyAero** [comment]
stale, no log

**Comment by longrironghang** [comment]
Ok, no problem.
