### ISSUE TITLE
[F-Req] Add pre-launch command

### ISSUE THREAD

**Issue by dimaguy** [PojavLauncherTeam/PojavLauncher#5358]
### Is this request related to a bug?

Some modpacks require running a modpack updater, usually in the form of a separate jar file, which can't be done in this launcher (PrismLauncher allows it for example)

### Describe the request.

I'd like to see a user-definable pre-launch command field added to the profile configuration

### Anything else?

Maybe a post-launch command would be nice too for flexibility, but not needed

**Comment by GaucovyAero** [comment]
probably everything at the same time but i would like to hear some other use cases (e. g. for wrapper command)

**Comment by dimaguy** [comment]
It's not a very widely used ability, not to mention that it's further limited by already being in a limited environment that's android.
It's just an added facility to get things working as-is (especially because the custom .jar runner doesn't do arguments as far as I know)

The modpack I'm trying to get working is SwitchCraft, that was proven to mostly work in pojavlauncher already, but it can't update itself due to the lack of the prelaunch thing

**Comment by artdeell** [comment]
> It's not a very widely used ability, not to mention that it's further limited by already being in a limited environment that's android. It's just an added facility to get things working as-is (especially because the custom .jar runner doesn't do arguments as far as I know)
> 
> The modpack I'm trying to get working is SwitchCraft, that was proven to mostly work in pojavlauncher already, but it can't update itself due to the lack of the prelaunch thing

You can run the jar installer with custom command line args by holding the jar installer button.
A pre-launch command won't be added, sadly, due to the fact that multiple instances of a JVM can't be made in one process, and thus running anything other than the game would require the launcher to relaunch.

**Comment by dimaguy** [comment]
> You can run the jar installer with custom command line args by holding the jar installer button.
> A pre-launch command won't be added, sadly, due to the fact that multiple instances of a JVM can't be made in one process, and thus running anything other than the game would require the launcher to relaunch.

Out of curiosity, does android not allow an app to launch more than one process at a time?

**Comment by GaucovyAero** [comment]
> > You can run the jar installer with custom command line args by holding the jar installer button.
> > A pre-launch command won't be added, sadly, due to the fact that multiple instances of a JVM can't be made in one process, and thus running anything other than the game would require the launcher to relaunch.
> 
> Out of curiosity, does android not allow an app to launch more than one process at a time?

basically it would have to be 2 pojav apps, you cant do that on 1
