### ISSUE TITLE
FORGE 1.12.2 CRASH

### ISSUE THREAD

**Issue by mesx2** [PojavLauncherTeam/PojavLauncher#5359]
### Describe the bug

hi the game crash as soon as the mojang logo appear it doesnt even make it to minecraft

### The log file and images/videos

[latestlog[1].txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15012889/latestlog.1.txt)

### Steps To Reproduce

```markdown
start the game
takes like 5 min black screen
mmojang logo appear
crash
```

### Expected Behavior

the game to open 

### Platform

```markdown
- Device model: HUAWI P20 PRO
- CPU architecture: Hisilicon Kirin 970
- Android version: 12
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
valkyrien skies wont work with gl4es

**Comment by mesx2** [comment]
> valkyrien skies wont work with gl4es

Hi i deleted valyrien skies and it crashed the same what should i do
