### ISSUE TITLE
[BUG] Can't click Config on forge (PojavLauncher Issue NOT FORGE) 

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#536]

**Comment by Accountuser99** [comment]
The Config select is broken, I have a video of it and if you can, please fix it really soon. I was thinking of switching to MCinaBox again because of this.

**Comment by Accountuser99** [comment]
The forge mod menu does not work, neither does any of the mods that use this type of menu.

**Comment by Accountuser99** [comment]
I will upload the video and send the link to it here

**Comment by artdeell** [comment]
> I will upload the video and send the link to it here

do it

**Comment by Accountuser99** [comment]
It's uploading rn

**Comment by Accountuser99** [comment]
Once it's uploaded I will send the link

**Comment by Accountuser99** [comment]
https://youtu.be/5xsMnPSERFc

**Comment by Accountuser99** [comment]
The link is uploaded

**Comment by artdeell** [comment]
It is a known bug that some mouse events aren't handled right in some menus.

**Comment by Accountuser99** [comment]
Is there a way to fix this?

**Comment by artdeell** [comment]
Maybe, but it seems that no one before you used the mod config menu extensively, so yeah, it was just left like that.

Also, it's your choice about what launcher to use. Like, idk, i'm myself biased against Box, but if you prefer, just use it.

**Comment by Accountuser99** [comment]
I don't want to resort to MCinaBox because it's worse on the Performance side of the game and its annoying to set up.

**Comment by Accountuser99** [comment]
MCinaBox also doesn't support the mods that pojav supports

**Comment by artdeell** [comment]
I'll tell and recheck then.

**Comment by Accountuser99** [comment]
OK, Thanks

**Comment by Accountuser99** [comment]
@khanhduytran0 Can this issue be put on a list for the next update?

**Comment by khanhduytran0** [comment]
Maybe. So the input pipe (for 1.12.2 and below) need to be rewritten.

**Comment by Accountuser99** [comment]
Yeah

**Comment by khanhduytran0** [comment]
Use latest build.

**Comment by Accountuser99** [comment]
Link to latest build?

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/498877588

**Comment by khanhduytran0** [comment]
Fixed
