### ISSUE TITLE
[BUG] Error Modpack Better MC

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5361]
### Describe the bug

Modpack Better MC Crashes When Entering the World

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15013422/latestlog.txt)

### Steps To Reproduce

```markdown
Install Modpack Better MC Version 1.20.1
```

### Expected Behavior

There isn't any

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Edelweiss-20230928-v3_openjdk
```

**Comment by GaucovyAero** [comment]
no errors, try removing half of the mods and see which one is causing the issue
