### ISSUE TITLE
[BUG] <Short descriptio> games folder bug

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [PojavLauncherTeam/PojavLauncher#5364]
### Describe the bug

I am finding the game folder the launcher files the launcher folders but when I go in Android / data and pojavlauncher there are not file or a file folder so I can apply modes on it so solve my problem 🥺🥺🥺🥺

### The log file and images/videos

I don't have any photos

### Steps To Reproduce

```markdown
I don't have any coding
```

### Expected Behavior

I don't have coding related this so please so please my situation 😭😭😭😭

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version:14
- PojavLauncher version: latest version
```

### Anything else?

So in Android version 14 the games folder is not available the files are not available so please fix it and please give update we are waiting

**Comment by GaucovyAero** [comment]
not a pojav issue, its just how android works (pojav wouldnt be able to exist on play store if the files werent in /storage/emulated/Android/data/...

use com.marc.files from play store (100kb shortcut to the default files app) and use the hamburger menu to get into the pojav folder

**Comment by kjjjjjjjjjjjj** [comment]
Thank you so much my dear

**Comment by kjjjjjjjjjjjj** [comment]
This is working thank you
