### ISSUE TITLE
Change gamefolder

### ISSUE THREAD

**Issue by Tem41kk** [PojavLauncherTeam/PojavLauncher#5365]
### Is this request related to a bug?

I'm use pojavlauncher for long time and i remember changing game folder to /games/pojavlauncher/files/.minecraft,but now i cant change game location.Now its impisible to add some mods in android 11 and bellow.

### Describe the request.

Can you add it back?

### Anything else?

no

**Comment by GaucovyAero** [comment]
use com.marc.files from play store and access the pojav directory with the hamburger menu

if we had our directory in /storage/emulated/0/games/ on Android 10 and above, we would not be able to exist on Play Store
