### ISSUE TITLE
[BUG] Black screen on Fabric 1.20.4

### ISSUE THREAD

**Issue by MeowcaTheoRange** [PojavLauncherTeam/PojavLauncher#5366]
### Describe the bug

After loading certain things, such as a texture pack refresh or the game itself, PojavLauncher renders a dark screen. I can only see the gameplay through the scrim (black part) of the settings menu.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15042462/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Join a single player world
3. The screen should stay normal, except when the world loads, when it turns completely black
4. Open the Settings menu (it's there, it's just hidden) to see that the world has fully loaded, it just isn't visible
```

### Expected Behavior

No black screen. I should be able to see my world.

### Platform

```markdown
- Device model: iQM995 SBID-6075S-V3
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: Package installer; edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

PojavLauncher is running on a SMART board.
Yes, those tablets that you may find at schools.
Don't ask how I have access to one.

**Comment by GaucovyAero** [comment]
dont use the angle renderer if you have issues with it, use gl4es instead

**Comment by MeowcaTheoRange** [comment]
> dont use the angle renderer if you have issues with it, use gl4es instead

Forgot to mention, this also happened with GL4ES. 
Though, in the time I submitted this, I've fixed the black screen issue, using these settings:

`Video and renderer > Use alternate surface rendering [ON]`
`Video and renderer > Force enable vsync [ON]`
