### ISSUE TITLE
[Realm invalid session] 

### ISSUE THREAD

**Issue by LFRNG07** [PojavLauncherTeam/PojavLauncher#5367]
### Describe the bug

Version 1.20.5rc1 it showing invalid session 
![Screenshot_20240420_104125_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/167270331/7dcec8d3-d4c5-4c65-a120-491e2572bad7)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15047185/latestlog.txt)

![Screenshot_20240420_104125_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/167270331/b3b69e28-c22a-4a57-8cef-03b77f3f1709)

### Steps To Reproduce

```markdown
Realm invalid session
```

### Expected Behavior

Realm invalid session

### Platform

```markdown
- Device model: I2011
- CPU architecture: arm64
- Android version: 13
- PojavLauncher: version edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Plz fix it

**Comment by ghost** [comment]
You need premium account

**Comment by LFRNG07** [comment]
> You need premium account

I have premium account

**Comment by ghost** [comment]
If you are using snapshots or mods that's normal

**Comment by kasrarouhi** [comment]
You are using snapshop because gui in background is not dirt

**Comment by ghost** [comment]
1.20.5rc1 is snapshot version so do not use. use release versions like 1.20.4

**Comment by LFRNG07** [comment]
Can't do anything bro my friends realm is in snapshot version

**Comment by Hagagzag** [comment]
Just don't play

**Comment by Algiuxs** [comment]
> Can't do anything bro my friends realm is in snapshot version 

Just use Aternos, it's free, it also has support for plugins, mods, but it requires a registered account, but the account is free.

**Comment by treefrog1109** [comment]
Also having this issue

**Comment by Algiuxs** [comment]
The full 1.20.5 version is now available.

**Comment by ghost** [comment]
Yes is released version so you can play realms in this version

**Comment by Algiuxs** [comment]
Well that solved the issue.

**Comment by treefrog1109** [comment]
Still having this issue with snapshot 24w20a

**Comment by ghost** [comment]
Just play with release version of minecraft like 1.20.6

**Comment by treefrog1109** [comment]
My server I play on with friends is on the snapshot :(

**Comment by StungDev** [comment]
I'm playing on release 1.20.6 and I still get this issue

**Comment by pl-k4** [comment]
Still happening.

**Comment by Nerbles1** [comment]
Still happening.

**Comment by Algiuxs** [comment]
The realms only work on the latest stable Minecraft version
