### ISSUE TITLE
How to fix crash

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5368]
### Describe the bug

-

### The log file and images/videos

![Screenshot_2024-04-20-16-25-47-223_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165360557/6e4f2200-e245-4bf2-a9c2-231402203d52)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15047611/latestlog.txt)

### Steps To Reproduce

```markdown
1.run MC
2.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: ?
- Android version:12 
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
## In order for RLCraft to not crash, remove these mods:

- custommainmenumod
- fancyblockparticles
- dynamic surroundings
- soundfilters
### credits to @kasrarouhi on github
