### ISSUE TITLE
[F-Req] 优化微软账户登录

### ISSUE THREAD

**Issue by zkitefly** [PojavLauncherTeam/PojavLauncher#5370]
https://github.com/HMCL-dev/HMCL/pull/2986

该提交修复了一个有时需要前往 minecraft.net 登录账户才能在 PojavLauncher 上登录的问题

### Describe the request.

在获取到 Minecraft Access Token 后先访问 `https://api.minecraftservices.com/entitlements/mcstore`，再执行接下来的账户信息获取

https://wiki.vg/Microsoft_Authentication_Scheme#Checking_Game_Ownership

要这么做应该是 Mojang API 有 Bug 导致的？

### Anything else?

应该可以修复 https://github.com/PojavLauncherTeam/PojavLauncher/issues/5354 https://github.com/PojavLauncherTeam/PojavLauncher/issues/5286 https://github.com/PojavLauncherTeam/PojavLauncher/issues/5232 等...

**Comment by artdeell** [comment]
Thank you for this info, it wil be fixed later
