### ISSUE TITLE
[BUG] <I can only play demo>

### ISSUE THREAD

**Issue by InconsistentMinecraftServer** [PojavLauncherTeam/PojavLauncher#5373]
### Describe the bug

I have no idea if it’s intended or not but I own Minecraft Java and it’s saying I can only play the demo.

### The log file and images/videos

I don’t have an image

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Sign in to your Microsoft account
3. The message pops up
```

### Expected Behavior

I don’t know what the expected behavior should be

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by artdeell** [comment]
Are you on Android or iOS?

**Comment by InconsistentMinecraftServer** [comment]
> Are you on Android or iOS?

I’m on IOS

**Comment by kiokori-git** [comment]
> > Are you on Android or iOS?
> 
> I’m on IOS

then you are in the wrong repository, proceed to https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues please
