### ISSUE TITLE
[BUG] mouse icon not show

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5375]
### Describe the bug

In newer version of pojav launcher in GitHub mouse is on and work but mouse texture is disappearing

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/db8fcddb-c2e7-435a-8d8e-5c48d6096b70

### Steps To Reproduce

```markdown
1:enter pojav launcher
2:turn mouse on
```

### Expected Behavior

I use GitHub pojav launcher version writes Fix[build]: put exp4j into the repository instead of relying on jitpack #4671 version of pojav launcher mouse icon is show without any problem

### Platform

```markdown
- Device model: xiaomi pocof5 12/256gb
- CPU architecture: aarch64
- Android version: 14
- PojavLauncher version: edelweiss-20240421-08bd0f2-v3_openjdk
```

### Anything else?

I turned alternate surface rendering off and doesn't work

**Comment by ghost** [comment]
> 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15067007/latestlog.txt)
And latest log

**Comment by ItsGlucose** [comment]
I confirm this. I have the same issue. Mouse icon is completely hidden as soon as I click "play" when surface rendering is on and when It's off, It hides when game launches. I'm using latest action build(#4676).

**Comment by artdeell** [comment]
Please check if it's fixed in this build: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/8805528887

**Comment by ItsGlucose** [comment]
It's fixed, thanks.

**Comment by ghost** [comment]
It's fixed thank's
