### ISSUE TITLE
Sodium and other renderer support.[F-Req] <Short description>

### ISSUE THREAD

**Issue by 13Ralef** [PojavLauncherTeam/PojavLauncher#5376]
### Describe the request.

I just want a single thing, that is actually so useful, and it is adding official support for other renderers, like: Sodium Renderer, VulkanMod, Canvas Renderer, Rubidium Renderer, Embeddium Renderer, etc.
I know there's a lot of differences between renderer especially because of GL4ES Wich I think is a port of OpenGL. I hope they add this feature, thanks!

**Comment by kiokori-git** [comment]
they aren't renderers, they're mods, optimization mods. (not sure about what the hell is canvas renderer) and how are you gonna think that adding official support would work if the mod developers don't even make their mods support pojavlauncher? Zink is also already exporting OpenGL 4.x which is nice but has an ass performance, this type of suggestion would have been done already if its possible

**Comment by 13Ralef** [comment]
They're Renderers haha, mods that rewrites the rendering engine.

**Comment by kiokori-git** [comment]
haha, you're definitely right it seems, no, vulkanmod only does that, not others.

**Comment by kiokori-git** [comment]
also when are you going to answer the question

**Comment by 13Ralef** [comment]
> also when are you going to answer the question

I thought they were renderers because in F3 it says "Sodium Render x Built"

**Comment by mchnjt** [comment]
> They're Renderers haha, mods that rewrites the rendering engine.

what the scallop are you yapping

**Comment by GaucovyAero** [comment]
you would likely have to get a talented dev or pay a lot of money for someone to do it
