### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by Hagagzag** [PojavLauncherTeam/PojavLauncher#5377]
### Describe the bug

Whenever I install any mod and play for example chemical exchange and clicks on okay button it starts and after some time it says application game exited with code 1 check latestlog.txt for more info

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15073311/latestlog.txt)

### Steps To Reproduce

```markdown
1 download meta deta and mods of any modpack and install it 
2 go to pojavlauncher select version and click play
3 wait
4 the bug
```

### Expected Behavior

I only clicks on play button and wait

### Platform

```markdown
- Device model:  Huawei p39 pro 8/512G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484dOc-v3_openjdk
```

**Comment by GaucovyAero** [comment]
send crash-2024-04-23_11.39.27-client.txt

**Comment by GaucovyAero** [comment]
stale
