### ISSUE TITLE
[BUG] crash when opening forge with no mod

### ISSUE THREAD

**Issue by rousseauaaa** [PojavLauncherTeam/PojavLauncher#5380]
### Describe the bug

Im just starting minecraft forge 1.20.4 with 2gb of ram and when there is the red screen it crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15094990/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Launch forge 1.20.4
Crash
```

### Expected Behavior

Playing minecraft with mods

### Platform

```markdown
- Device model: s9
- CPU architecture: ?
- Android version: android 8
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
install the latest github actions build, guide is on the wiki
