### ISSUE TITLE
[F-Req]  A way to change Minecraft installation folder on Android 13

### ISSUE THREAD

**Issue by breadlol64** [PojavLauncherTeam/PojavLauncher#5381]
### Is this request related to a bug?

Not really

### Describe the request.

I have a Android 13 phone, so I can't access "Android" folder and can't install mods. I really want to be able to change the Minecraft installation folder.

**Comment by GaucovyAero** [comment]
duplicate issue, use com.marc.files from play store (which is a 100KB shortcut to the default file manager) and access the pojav directory via the hamburger menu
