### ISSUE TITLE
[BUG] fabric no load

### ISSUE THREAD

**Issue by RalseiGithub** [PojavLauncherTeam/PojavLauncher#5384]
### Describe the bug

Fabric doesn’t load when mods are installed

### The log file and images/videos

There is none it doesn’t load

### Steps To Reproduce

```markdown
Put mods in mod folder and start fabric
```

### Expected Behavior

I expect fabric to load with mods.

### Platform

```markdown
- Device model: idk I use now.gg
- CPU architecture:  x64 if correct
- Android version: 13
- PojavLauncher version: don’t remember
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by GaucovyAero** [comment]
stale
