### ISSUE TITLE
[BUG] cant click half screen with otg mause

### ISSUE THREAD

**Issue by BUCIOJEK** [PojavLauncherTeam/PojavLauncher#5385]
### Describe the bug

![Screenshot_2024-04-25-16-41-03-44_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89052261/7dbe5769-2f6e-4537-b854-c65912d527c4)

### The log file and images/videos

No 

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Enter Eny Minecraft version with otg mause and keyboard
3. Enter Minecraft lobby
4. Bug
```

### Expected Behavior

No respons

### Platform

```markdown
- Device model: REALME C55
- CPU architecture: Helio g88
- Android version: 14
- PojavLauncher version: Latest
```

### Anything else?

I think need landscape (horizontal screen) version on this pojavlauncher because when play landscape Minecraft launcher the bug ITS gone only when i play pojav and roblox (vertical screen when in the launcher lobby) This bug exists but im traying to use auto rotation aplication the bug dosnt gone plss help me😭😭

**Comment by GaucovyAero** [comment]
duplicate issue
