### ISSUE TITLE
Stoneblock 2 Modpacks 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#5386]
### Describe the bug

The Modpacks is not loading or crash am stock on this
![Screenshot_2024-04-26-09-09-36-428_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/76839710/6378a26a-8c26-4003-8286-1f14d90c29c0)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15123955/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Open log output 
3. Not reading or loading
```

### Expected Behavior

Working fine 

### Platform

```markdown
- Device model: Poco c65
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: on Google play
```

### Anything else?

Plss help

**Comment by GaucovyAero** [comment]
remove randompatches
