### ISSUE TITLE
[BUG] I can't change language

### ISSUE THREAD

**Issue by DrSTOpka** [PojavLauncherTeam/PojavLauncher#5387]
### Describe the bug

I can't change the language :(
Language list is empty
![Screenshot_2024-04-26-13-54-23-685_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/168172566/09d98b1a-2fd7-450c-adfa-5bdc4c4cbf46)

### The log file and images/videos

![Screenshot_2024-04-26-13-54-23-685_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/168172566/efa32824-eb75-424b-a990-8cd11ed3b7ed)

### Steps To Reproduce

```markdown
1. Run Pojavlauncher
2. Enter the "Languages" tab
3. See that there is no list of languages
```

### Expected Behavior

I expect that I can change the language 

### Platform

```markdown
- Device model: Redmi Note 10 Pro
- CPU architecture: arm64-v8a
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
what mc version

**Comment by DrSTOpka** [comment]
> какая версия mc

I have this on all versions

**Comment by GaucovyAero** [comment]
![Screenshot_20240502-224058_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/185cc3f4-1a1d-4d4a-bce5-83b448a7d305)

cannot reproduce, try reinstalling pojav
