### ISSUE TITLE
[F-Req] optimize graphics in pojav launcher

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5388]
### Describe the request.

![IMG_۲۰۲۴۰۴۲۶_۱۵۵۳۵۰](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/dc755d30-fe8b-4df2-a9d5-ad7bacd930f0)
I think is helpful. reduce picture size in every frames to better experience

### Anything else?

Is can add in pojav launcher. Game turbo in xiaomi have optimize graphics option can help gpu and save power but pojav is not fully support for game turbo .nevermind. Pojav launcher can have optimize graphics option in launcher?

**Comment by GaucovyAero** [comment]
no
