### ISSUE TITLE
[BUG] Better MC 1.20.1 v26 not working (idk what mod to remove or what to do)

### ISSUE THREAD

**Issue by Blunerz** [PojavLauncherTeam/PojavLauncher#5389]
### Describe the bug

i just start the game and it crashes after a min or 2

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15130778/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. download better mc 1.20.1 v26
3. run the game
```

### Expected Behavior

i expect tha game to run

### Platform

```markdown
- Device model: samsung galaxy m34 5g
- CPU architecture: arm (i think)
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
remove bclib

**Comment by Blunerz** [comment]
will the aether work if i remove it?

**Comment by Blunerz** [comment]
still not working

**Comment by Blunerz** [comment]
[latestlog (1).txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15131515/latestlog.1.txt)

**Comment by GaucovyAero** [comment]
remove xaeros minimap
