### ISSUE TITLE
BTW CE

### ISSUE THREAD

**Issue by NDG312** [PojavLauncherTeam/PojavLauncher#5392]
Is there any way to install BTW CE on pojavlauncher?

**Comment by GaucovyAero** [comment]
there is (on the pojav discord) but apparently it doesnt work with the latest btw version for some reason

**Comment by NDG312** [comment]
I followed the steps but when it comes to downloading appletmain, there is no file to download.

**Comment by GaucovyAero** [comment]
> I followed the steps but when it comes to downloading appletmain, there is no file to download.

https://www.mediafire.com/file/afgraead4kwjnlw/AppletMain.class/file
