### ISSUE TITLE
[BUG] <Sodium Crash 1.20.5>

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#5394]
### Describe the bug

Sodium crash on 1.20.5

### The log file and images/videos

///

### Steps To Reproduce

```markdown
1.Open Fabric 1.20.5
2.Go to world or server
3.Minecraft crash
```

### Expected Behavior

Minecraft not crash(sodium)

### Platform

```markdown
- Teclast t40 pro eea: 
- ARM64: 
- 12: 
- Last version pojavlaucher in https://github.com/PojavLauncherTeam/PojavLauncher/actions:
```

### Anything else?

I used haste to fix this but I don’t want to wait, please advise how to fix this

**Comment by GaucovyAero** [comment]
dont use the builtin fabric installer for now, its not compatible with the latest version of fabric/mc
