### ISSUE TITLE
When I start a forge modpack I get crash code -1

### ISSUE THREAD

**Issue by RaduIanis** [PojavLauncherTeam/PojavLauncher#5395]
### Describe the bug

I can't play a modpack on 1.16.5 forge, because when it enters the main menu it freezes then crashes ( My phone is good enough to handle it) 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15137687/latestlog.txt)

### Steps To Reproduce

```markdown
1 start pojav
2 start Minecraft
3 wait for it to load
4 it is loaded
5 it freezes for a few seconds
6 then it crashes
```

### Expected Behavior

I expected Minecraft to not crash

### Platform

```markdown
- Device model: moto g54
- CPU architecture: mediately 7020
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15137686/latestlog.txt)

**Comment by GaucovyAero** [comment]
try removing optifine

**Comment by RaduIanis** [comment]
I removed optifine, but it still crashes

**Comment by RaduIanis** [comment]
> try removing optifine

Actually your installer is broken, with my own jar it works perfectly!
