### ISSUE TITLE
[REIPlugin] and [REIServerPlugin] Every time I launch my game I get these errors.

### ISSUE THREAD

**Issue by DrDuckyyy** [PojavLauncherTeam/PojavLauncher#5397]
### Describe the bug

Hello! I want to start by saying that I'm new to using Fabric. I just finished making a custom modpack but I get the error messages "Could not create REI Plugin [REIPlugin] due to errors, provided by roughlyenoughitems" and "Could not create REI Plugin [REIServerPlugin] due to errors, provided by roughlyenoughitems". while looking for ways to fix these errors, I kept seeing that a nown cause is the Let's do: Vinery mod, but I don't have that installed in the modpack. Any help would be greatly appreciated, thank you :)

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/15139551/latest.log)

### Steps To Reproduce

```markdown
1. Click "Play" on curseforge launcher.
2. Start the game with minecraft launcher. 
3. After loading, right before the title screen, th errors will appear with the only pressable button being "Exit" at the bottom.
```

### Expected Behavior

Expected the modpack to work properly.

### Platform

```markdown
I'm not sure what this field is asking for, I'm pretty sure it's system information. Sorry if I'm wrong. 
Device name	DuckyyysCompter
Processor	AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz
Installed RAM	64.0 GB (63.4 GB usable)
Device ID	EFF12A32-CD44-4207-94CB-918E63B71E2D
Product ID	00342-20814-57537-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

**Comment by GaucovyAero** [comment]
why is this in pojav issues lol, unrelated to pojav
