### ISSUE TITLE
[Not A Bug] ram allocating is sorta werid. 

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5398]
### Describe the bug

I donno how to explain it, but here's the test and the results.

> First test: High Ram.
Ram allocate: 1700mb
Ram free (system report): 2,5GB
Fps: Max:27 / Min:2 / Avg:20.
Minecraft ram usage: rise from 200mb till 1500mb and then drop. (Not very accurate)

> Second test: Low ram
Ram allocate: 830mb
Ram free (system report): 2,3 GB
Fps: Max:112 / Min: 17 / Avg:53
Minecraft ram usage: rise from 200mb till 700mb and drop. (Not verry accurate)

> Other results: Ram allocate before I do this test.
Ram allocate: 1170mb
Ram free: around 1,5GB up.
Fps: Avg:40-70 fps (this is not a test so no specific number.)

As you can see, with 830mb ram allocated, my phone performance the best, idk why so i just report here to ask. 

For more information about hardware, check the **Platform** section.

### The log file and images/videos

Forgot to take it, but you can test yourself. The results might not same as mine, maybe your phone perform better with higher fps.

### Steps To Reproduce

```markdown
N/A
```

### Expected Behavior

This might be not a bug, so i don't really expect anything , this might be my device fault.

### Platform

```markdown
- Device model: Yuho Tab 10
- CPU architecture: idk, but the chip set is Unisoc T310. Could you please check it...?
- Total ram: 4GB
- Minecraft version: 1.20.1 Sodium modpack. 
- (file) Minecraft version: [pack.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/15142243/pack.zip)
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

No.

**Comment by TylerHaoNhot** [comment]
**Some questions you might ask:**

**Q:** Why you use 2 specific number for ram allocating, 830mb and 1700mb? Why don't you use higher or lower value?
**A:** There was a time I used another device, with same amount of 4GB of ram and better CPU, snap845. But my phone only perform best on 1170mb of ram, give me maximum 400fps. 830mb ram also good, 100fps max, i usually lower my ram down to there to multitasking. And the worst come when i set my ram higher 1600mb. Not over 40fps.

**Q:** where did you get this mod pack from?
**A:** I searched this with the keyword "Haste" in pojavlauncher's mod downloader.

**Q:** What's yours Minecraft setting when testing?
**A:** Almost lowest.

**Comment by TylerHaoNhot** [comment]
Also, if this is my device fault, how many RAM i should allocate then to gain best performance?

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۴-۲۸-۲۲-۳۸-۳۵-۰۹۵_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/3a422a32-4185-41f4-8d5b-d1b65546a8fe)
It's not very true. doesn't more ram increase FPS, more ram means the game can keep those same framerate, at better stability and heating up system a little

**Comment by ghost** [comment]
But i allocated 4gb ram. i think it's good. i have 12gb ram

**Comment by Marshall2439** [comment]
Dude how tf yall getting so fps I was getting like 40 fps at Max on lowest settings and mid settings

**Comment by kasrarouhi** [comment]
And for this allocating ram doesn't change fps

**Comment by Marshall2439** [comment]
> And for this allocating more or less ram doesn't change fps very much but not allocate to much ram .to much ram = lower fps In one time i allocated 11gb ram and minecraft get lag spikes more and more and heated up system and game doesn't exit and . . . So DON'T ALLOCATE VERY MUCH RAM

So what's the range for allocating ram on CREATE MOD modpack

**Comment by Marshall2439** [comment]
Please tell cuz im getting unbearable lag

**Comment by kasrarouhi** [comment]
I don't know about create mod but let me to search

**Comment by ghost** [comment]
4gb or 6gb ram create mod needed and enough for it like better minecraft.

**Comment by ghost** [comment]
But allocating ram doesn't change fps very much you can use performance mods like optifine and best settings or turn on alternate surface rendering and if you in minecraft servers use current jvm argument and best developer option for performance and  . . .

**Comment by Marshall2439** [comment]
And?...

**Comment by Marshall2439** [comment]
> But allocating ram doesn't change fps very much you can use performance mods like optifine and best settings or turn on alternate surface rendering and if you in minecraft servers use current jvm argument and best developer option for performance and . . .

As far as I know optifine doesn't work on forge 1.20.1 versions and embeddium gives me like 30 fps at Max. I do allocate 4 gigs of ram tho but it still gives 30 fps at Max PLEASE HELP

**Comment by Marshall2439** [comment]
@GaucovyAero help me

**Comment by ghost** [comment]
Mods like embeddium not fully supported for pojav. Try mods like lazydfu _ clumps _ cutting leaves _ smoothboot _ ferricore _ let me despawn _ . . .
https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance118.md#forge-118x
This link very help you. (Not all mods support for pojav you need to test each mod)
Mods for 1.18.2 version of minecraft of create mod is 1.18.2
https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance120.md
Fot 1.20.x

**Comment by Marshall2439** [comment]
> Mods like embeddium not fully supported for pojav. Try mods like lazydfu _ clumps _ cutting leaves _ smoothboot _ ferricore _ let me despawn _ . . . https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance118.md#forge-118x This link very help you. (Not all mods support for pojav you need to test each mod) Mods for 1.18.2 version of minecraft of create mod is 1.18.2 https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance120.md Fot 1.20.x

Yeah embeddium isn't supported but without embeddium, game lags so bad like 2 fps average not only that I already have those optimization mods idk why it lags so bad I have seen other people on yt getting high fps tho

**Comment by ghost** [comment]
They have powerful device

**Comment by Marshall2439** [comment]
> They have powerful device

What powerful device are we talking here? Majority of them either have 6gb or 8gb RAM phone I have 8gb ram phone

**Comment by TylerHaoNhot** [comment]
> > They have powerful device
> 
> What powerful device are we talking here? Majority of them either have 6gb or 8gb RAM phone I have 8gb ram phone

Maybe you just having a bad cpu on your device. or not, maybe you just donno how to optimize your game.

**Comment by Marshall2439** [comment]
> > > They have powerful device
> > 
> > 
> > What powerful device are we talking here? Majority of them either have 6gb or 8gb RAM phone I have 8gb ram phone
> 
> Maybe you just having a bad cpu on your device. or not, maybe you just donno how to optimize your game.

Exynos 1280 cpu

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۶-۰۱-۱۸-۴۵-۵۰-۷۸۷_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/e8bcddfb-8380-4f8c-ac38-58df6b456e0e)
In benchmark not have powerful cpu to run big modpacks

**Comment by Marshall2439** [comment]
Now what? Most of my mods are performance improvement mods. I have few create addons with create and few furniture mods like mr crayfish mod and handcrafted

**Comment by TylerHaoNhot** [comment]
> Now what? Most of my mods are performance improvement mods. I have a few create addons with create and a few furniture mods like Mr. Crayfish mod and handcrafted

Bro, maybe that a few of your mods cause the lag. Your device is very powerful though (at least more powerful than my tablet that reaches 100fps). If you want to keep playing those mods you added, you can upload them to a server (only server-side mods, client-side mods like performance mods don't work there) and then join the server. It will reduce the pressure on your phone because it doesn't need to run any map(a.k.a a server itself).

If the lag keeps going, try to change some settings, client settings, and pojavlauncher's settings like RAM, JVM, etc...
Finally, if it doesn't work, just delete all your mods and keep performance mods only.💀👌

**Comment by Marshall2439** [comment]
> > Now what? Most of my mods are performance improvement mods. I have a few create addons with create and a few furniture mods like Mr. Crayfish mod and handcrafted
> 
> Bro, maybe that a few of your mods cause the lag. Your device is very powerful though (at least more powerful than my tablet that reaches 100fps). If you want to keep playing those mods you added, you can upload them to a server (only server-side mods, client-side mods like performance mods don't work there) and then join the server. It will reduce the pressure on your phone because it doesn't need to run any map(a.k.a a server itself).
> 
> If the lag keeps going, try to change some settings, client settings, and pojavlauncher's settings like RAM, JVM, etc... Finally, if it doesn't work, just delete all your mods and keep performance mods only.💀👌

I did thought about that. Anyways what's the best ram for create mod? JVM is changed to reduce Garbage collection lag. I dont want to play without mods because for me minecraft is less content

**Comment by TylerHaoNhot** [comment]
> > > Now what? Most of my mods are performance improvement mods. I have a few create addons with create and a few furniture mods like Mr. Crayfish mod and handcrafted
> > 
> > 
> > Bro, maybe that a few of your mods cause the lag. Your device is very powerful though (at least more powerful than my tablet that reaches 100fps). If you want to keep playing those mods you added, you can upload them to a server (only server-side mods, client-side mods like performance mods don't work there) and then join the server. It will reduce the pressure on your phone because it doesn't need to run any map(a.k.a a server itself).
> > If the lag keeps going, try to change some settings, client settings, and pojavlauncher's settings like RAM, JVM, etc... Finally, if it doesn't work, just delete all your mods and keep performance mods only.💀👌
> 
> I did thought about that. Anyways what's the best ram for create mod? JVM is changed to reduce Garbage collection lag. I dont want to play without mods because for me minecraft is less content

I never used any 8gb ram devices before, try to change the ram until you find yourself a max fps performance. (It's quite take  a lot of time though)
I would recommend you set it more than 2gb, I think so.

**Comment by Marshall2439** [comment]
> > > > Now what? Most of my mods are performance improvement mods. I have a few create addons with create and a few furniture mods like Mr. Crayfish mod and handcrafted
> > > 
> > > 
> > > Bro, maybe that a few of your mods cause the lag. Your device is very powerful though (at least more powerful than my tablet that reaches 100fps). If you want to keep playing those mods you added, you can upload them to a server (only server-side mods, client-side mods like performance mods don't work there) and then join the server. It will reduce the pressure on your phone because it doesn't need to run any map(a.k.a a server itself).
> > > If the lag keeps going, try to change some settings, client settings, and pojavlauncher's settings like RAM, JVM, etc... Finally, if it doesn't work, just delete all your mods and keep performance mods only.💀👌
> > 
> > 
> > I did thought about that. Anyways what's the best ram for create mod? JVM is changed to reduce Garbage collection lag. I dont want to play without mods because for me minecraft is less content
> 
> I never used any 8gb ram devices before, try to change the ram until you find yourself a max fps performance. (It's quite take a lot of time though) I would recommend you set it more than 2gb, I think so.

I have allocated 4gigs already it doesn't seem to give more than 30fps MAX same with 3.5gigs less than that world doesn't load

**Comment by TylerHaoNhot** [comment]
> > > > > Now what? Most of my mods are performance improvement mods. I have a few create addons with create and a few furniture mods like Mr. Crayfish mod and handcrafted
> > > > 
> > > > 
> > > > Bro, maybe that a few of your mods cause the lag. Your device is very powerful though (at least more powerful than my tablet that reaches 100fps). If you want to keep playing those mods you added, you can upload them to a server (only server-side mods, client-side mods like performance mods don't work there) and then join the server. It will reduce the pressure on your phone because it doesn't need to run any map(a.k.a a server itself).
> > > > If the lag keeps going, try to change some settings, client settings, and pojavlauncher's settings like RAM, JVM, etc... Finally, if it doesn't work, just delete all your mods and keep performance mods only.💀👌
> > > 
> > > 
> > > I did thought about that. Anyways what's the best ram for create mod? JVM is changed to reduce Garbage collection lag. I dont want to play without mods because for me minecraft is less content
> > 
> > 
> > I never used any 8gb ram devices before, try to change the ram until you find yourself a max fps performance. (It's quite take a lot of time though) I would recommend you set it more than 2gb, I think so.
> 
> I have allocated 4gigs already it doesn't seem to give more than 30fps MAX same with 3.5gigs less than that world doesn't load

Kinda weird, lol. My pixel 3 only has 4gb of ram , I played create mod with furniture mods and terrain mod. I allocate only 1150mb of ram and getting more than 45fps when standing still, getting 20-30fps when moving.

**Comment by Marshall2439** [comment]
Yeah now what should I do? I can't just play at 7fps average until I get a pc. Gimme some solution.

**Comment by TylerHaoNhot** [comment]
> Yeah now what should I do? I can't just play at 7fps average until I get a pc. Gimme some solution.

I donno💀
If you said so, you can start building your pc from now. Its not that expensive btw, just buy yourself an I5-2400 and gtx 750 for around more than 80$ is way enough to get more than 200fps on minecraft

**Comment by Marshall2439** [comment]
> > Yeah now what should I do? I can't just play at 7fps average until I get a pc. Gimme some solution.
> 
> I donno💀 If you said so, you can start building your pc from now. Its not that expensive btw, just buy yourself an I5-2400 and gtx 750 for around more than 80$ is way enough to get more than 200fps on minecraft

I ain't getting a pc until like few months bro

**Comment by Marshall2439** [comment]
Gimme solution

**Comment by TylerHaoNhot** [comment]
> Gimme solution

Can you gimme your game files? I'll test it on my device
