### ISSUE TITLE
For zink developer 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#5399]
### Describe the bug

When I change my render distance to 4 or higher is crashing my game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15142270/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the game 
2. Change render distance to 4 or higher 
3. Crashing my game
```

### Expected Behavior

I thought is mod that why delete it but still crash my game on 4 or higher 

### Platform

```markdown
- Device model: Poco c65
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: on latest Google play
```

### Anything else?

Create mod crashed when I tried to combine the train

**Comment by GaucovyAero** [comment]
most likely out of memory, try decreasing your memory allocation if you are running above the limit

**Comment by kedrick021** [comment]
> most likely out of memory, try decreasing your memory allocation if you are running above the limit

I have 8gb ram am using only 3500 but still crash
