### ISSUE TITLE
Sound fix

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#54]
I figured out how to fix sound:
 1. Open app with APK Editor
 2. Delete the lib/arm64 -v8a folder
 3. Delete existing PojavLauncher
 4. Install modified APK
 5. Enjoy the sound!

This method works for most 64-bit ARM phones.

**Comment by khanhduytran0** [comment]
### But:
- This will decrease performance of 64-bit devices.
- This will be a big problem if Android stopping support execute 32-bit native libraries.

**Comment by artdeell** [comment]
Yes. Can you force the app to use 32-bit openal binary? Most of the current phones support 32-bit ABIs and users will be happy(lwjgl will remain 64-bit)

**Comment by matteobranchi** [comment]
> I figured out how to fix sound:
> 
> 1. Open app with APK Editor
> 2. Delete the lib/arm64 -v8a folder
> 3. Delete existing PojavLauncher
> 4. Install modified APK
> 5. Enjoy the sound!
> 
> This method works for most 64-bit ARM phones.

This works but, yes it decreases performance by quite a bit.

**Comment by khanhduytran0** [comment]
I will try your shared OpenAL before thinking to remove arm64 native libraries.

**Comment by abdo-A028** [comment]
> I figured out how to fix sound:
> 
> 1. Open app with APK Editor
> 2. Delete the lib/arm64 -v8a folder
> 3. Delete existing PojavLauncher
> 4. Install modified APK
> 5. Enjoy the sound!
> 
> This method works for most 64-bit ARM phones.

You can only delete lib/arm64-v8a folder

**Comment by abdo-A028** [comment]
It may fix sounds

**Comment by artdeell** [comment]
The main reason why i added "Delete existing PojavLauncher" is because some devices verify the app's signature, and APK Editor doesn't keep the app's sign.

**Comment by khanhduytran0** [comment]
Any modification to APK require re sign or app will unable to install.

**Comment by khanhduytran0** [comment]
I did it in latest preview.
