### ISSUE TITLE
Keyboard is not working in in invariti to search

### ISSUE THREAD

**Issue by Threecheetah119** [PojavLauncherTeam/PojavLauncher#540]
I am open invariety to search torch and I Tab on the keyboard button to open keyboard and keyboard will opened but I search touch but nothing is type fix it please

**Comment by artdeell** [comment]
please write better, i can't understand.

**Comment by dashboarder** [comment]
Use gbpard

**Comment by khanhduytran0** [comment]
Use Gboard.
