### ISSUE TITLE
(Not a bug) pls add opengl 4.6 or later? Sodium mod is the mod i think that can boost my game alot.

### ISSUE THREAD

**Issue by Rocraft27** [PojavLauncherTeam/PojavLauncher#5400]
### Describe the bug

Ive been using optifabric for 2years now, i have enough of these lags, lag spikes, etc.
I hope sodium can help more.

### The log file and images/videos

![Screenshot_20240429-142852_Chrome](https://github.com/PojavLauncherTeam/PojavLauncher/assets/168403787/a11d6c12-0908-469a-baa1-8f91e1b26028)

### Steps To Reproduce

```markdown
My MODS that i use can reproduce it..
```

### Expected Behavior

I expected to have me seeng invisible chunks in Sodium Mod

### Platform

```markdown
- Device model: samsung SM-A600G
- CPU architecture: 32Bit
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by zkitefly** [comment]
Sodium 不适合于 PojavLauncher，他会让游戏崩溃

**Comment by ghost** [comment]
I know @zkitefly virgl render or opengl 4.6 is buggy like texture items turn to black or display will be converse for and more bugs many phones for this developers are removed and added zink. But i think it's not bad idea to add virgl render or opengl 4.6 but in many report about add virgl renderer developer not planed thier reports. solDev69 are work with virgl render but crash in 1.20 or up

**Comment by fishiatee** [comment]
Sodium needs more than just GL4.6 support. Also, Android graphic drivers often sucks except for Adreno GPUs.

That being said, your phone despite having a literal 64-bit SoC still runs in 32-bit only mode, has only 3 GB of RAM, and worst of all it has Mali GPU. That thing is not going to play nice with Sodium or even Minecraft if at all.

**Comment by ghost** [comment]
Yeah. sodium is not fully supported for android

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۴-۳۰-۱۳-۲۷-۰۴-۷۱۰_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/f6ce1bce-b5e6-4f09-b7ae-bd0a11735532)
I have adreno 725 and 12gb ram but sodium report me in all 3 renderers so . . .
