### ISSUE TITLE
[Probably a bug] Mod that try to directing to the browser

### ISSUE THREAD

**Issue by BestFurTH** [PojavLauncherTeam/PojavLauncher#5402]
### Describe the bug

it's not direct (failed to launch)

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/104305704/8dce64df-6e0f-4b1d-8c09-1655d0355c70

### Steps To Reproduce

```markdown
whatever if it speaking about direct... it should be always show as like select browser app
```

### Expected Behavior

just about better direct app system

### Platform

```markdown
(just about mod about direct to browser)
```

**Comment by GaucovyAero** [comment]
seems like its trying to open something on top of the mc window inside pojav which is not possible
