### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Zetsuooo** [PojavLauncherTeam/PojavLauncher#5406]
### Describe the bug

When im using mod/sodium my screen turning black and i waited for so long and nothing happens, but when i remove it its back to normal again

https://github.com/PojavLauncherTeam/PojavLauncher/assets/168599511/00baa4ef-2cb9-4bfd-ad5f-eb2eaa69725c

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/168599511/0d0e1956-9ea5-4b1e-a6d1-986bd3fd5048

### Steps To Reproduce

```markdown
Start pojav
Black screen
```

### Expected Behavior

I expect that if i waited for so long it will work

### Platform

```markdown
- Device model: Infinix Smart 8
- CPU architecture: Unisoc (T606)
- Android version: 13
- PojavLauncher version: i just download it on playstore i dont know the version
```

### Anything else?

Please fix thid

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by GaucovyAero** [comment]
stale
