### ISSUE TITLE
[F-Req] <Short description> Can this mod run on pojav launcher 

### ISSUE THREAD

**Issue by Doorpol** [PojavLauncherTeam/PojavLauncher#5407]
### Is this request related to a bug?

No

### Describe the request.
Can this mod run on pojav launcher?

https://www.curseforge.com/minecraft/mc-mods/embeddium

https://www.curseforge.com/minecraft/mc-mods/rubidium-extra

https://www.curseforge.com/minecraft/mc-mods/bobby-forge

https://www.curseforge.com/minecraft/mc-mods/distant-horizons

https://www.curseforge.com/minecraft/mc-mods/create

https://www.curseforge.com/minecraft/mc-mods/vulkanmod

Thanks you

### Anything else?

No

**Comment by GaucovyAero** [comment]
zink
old one works
no idea whats that
works with a patch
works on zink, angle with backend off or gl4es on adreno
not possible to get anymore

**Comment by cpagentboot** [comment]
> zink old one works no idea whats that works with a patch works on zink, angle with backend off or gl4es on adreno not possible to get anymore

Where can I find this patch? I see nothing of it. Can you help me please?
