### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by Manhdayne** [PojavLauncherTeam/PojavLauncher#541]
Can you fix the world not replay error 1.7.10 please

**Comment by artdeell** [comment]
Known issue. But no one knows for sure why it happens.

**Comment by Manhdayne** [comment]
Can you fix it

**Comment by artdeell** [comment]
How do you think someone can fix something when no one knows why the bug happens?

**Comment by Manhdayne** [comment]
:)

**Comment by artdeell** [comment]
Seems like Replay Mod tries to set a DOS/Windows attribute in Android enviroinment...
