### ISSUE TITLE
[F-Req] <Add "record game" function (添加"录制游戏"功能)>

### ISSUE THREAD

**Issue by OutHimic** [PojavLauncherTeam/PojavLauncher#5410]
### Is this request related to a bug?

Recording the buttons on the screen directly with the mobile phone will greatly affect the recording effect. So I hope PoJav can launch this kind of function, thank you.
用手机直接录屏会录制到屏幕上的按钮,非常影响录制效果.所以希望PoJav能够推出这类功能,谢谢.

### Describe the request.

Add a function to record the game, so that the function can record the game content without recording the operation button and recording the mouse pointer normally.
添加一个录制游戏的功能,使该功能可以在不录制到操作按钮且正常录制鼠标指针的情况下录制游戏内容.

### Anything else?

If possible, I also hope to customize the storage location, resolution, refresh rate, bit rate, etc. Thank you.
如果可以,还希望能够自定义存储位置,分辨率,刷新率,比特率等,谢谢.

**Comment by GaucovyAero** [comment]
no, read previous enhancement issues on this topic, duplicate
