### ISSUE TITLE
[F-Req] Add the third-party login function, just like PCL2 can log in with LittleSkin.

### ISSUE THREAD

**Issue by OutHimic** [PojavLauncherTeam/PojavLauncher#5411]
### Is this request related to a bug?

Without a third-party login, many people can't use the skin they want, and they can't log on to some servers, which is one of the reasons why PoJav Launcher is rarely used in China.

### Describe the request.

There are more login options to choose from when logging in . It's useful !

### Anything else?

Little skin comes with "drag the button to the launcher" to realize the login function.

**Comment by zkitefly** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/5112

**Comment by OutHimic** [comment]
Oh...I haven't notised ... sorry...

________________________________
发件人: zkitefly ***@***.***>
发送时间: 2024年5月1日 18:03
收件人: PojavLauncherTeam/PojavLauncher ***@***.***>
抄送: OutHimic ***@***.***>; Author ***@***.***>
主题: Re: [PojavLauncherTeam/PojavLauncher] [F-Req] Add the third-party login function, just like PCL2 can log in with LittleSkin. (Issue #5411)


#5112<https://github.com/PojavLauncherTeam/PojavLauncher/issues/5112>

―

**Comment by OutHimic** [comment]
Okay.
________________________________
发件人: GaucovyAero ***@***.***>
发送时间: 2024年5月1日 19:45
收件人: PojavLauncherTeam/PojavLauncher ***@***.***>
抄送: OutHimic ***@***.***>; Author ***@***.***>
主题: Re: [PojavLauncherTeam/PojavLauncher] [F-Req] Add the third-party login function, just like PCL2 can log in with LittleSkin. (Issue #5411)


Closed #5411<https://github.com/PojavLauncherTeam/PojavLauncher/issues/5411> as not planned.

―
