### ISSUE TITLE
Cannot download latest releases

### ISSUE THREAD

**Issue by Sam10909** [PojavLauncherTeam/PojavLauncher#5412]
### Describe the bug

When I try to download latest releases such as 1.20.6 or 1.20.5.It gives me a error message 

### The log file and images/videos

![Screenshot_2024-05-01-15-23-34-57_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/162701878/29d4cfe7-bbee-4b2b-819b-69f2afe74601)
![Screenshot_2024-05-01-15-09-19-01_67a64f1fc1b88908dad3392f76c1969b](https://github.com/PojavLauncherTeam/PojavLauncher/assets/162701878/35c8ec06-8e1f-4dcb-9950-21907481ad20)

### Steps To Reproduce

```markdown
1.Start pojav
2.Login using offline account
3.Try to download latest releases
```

### Expected Behavior

I expect to download the latest releases 

### Platform

```markdown
- Device model: One plus Nord CE 3 lite 5g
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version:the latest released 2 hours ago
```

### Anything else?

Pls help me

**Comment by zkitefly** [comment]
you must download and input java 21

https://github.com/PojavLauncherTeam/PojavLauncher/issues/5308

**Comment by Sam10909** [comment]
How to do it?

**Comment by zkitefly** [comment]
> How to do it?
> 

 There are hints in the comments of this issue, you can read them. 

https://github.com/PojavLauncherTeam/PojavLauncher/issues/5308

**Comment by Sam10909** [comment]
No i am asking how to download java 21

**Comment by zkitefly** [comment]
> No i am asking how to download java 21

https://github.com/PojavLauncherTeam/PojavLauncher/issues/5308#issuecomment-2057031680

**Comment by grosioso** [comment]
https://youtu.be/RZlgbDCa-YA?si=4sWlvL2BayLexYjX

this tutorial might help ;)
