### ISSUE TITLE
[BUG] <Problems with mouse penetration>

### ISSUE THREAD

**Issue by Ink305Mua** [PojavLauncherTeam/PojavLauncher#5413]
### Describe the bug

I think this is a bug, players want to be able to move the viewpoint while holding down a button, not hold down a button that triggers the left and right mouse buttons, which affects the player's actions! This has been an issue for quite a while now, and as far as I remember, older versions of the Pojav launcher didn't have this problem, so I'd like to see you guys fix this, please! This feature is a great help for 2-finger players! For multi-fingered players it still is too

### The log file and images/videos

None, if you need a video I'll record it.

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.Start minecraft. Enter the world.
3.Pressing a button with mouse pass-through enabled will trigger the left and right mouse buttons (there is a chance that this will happen, if it doesn't, you can try to press the button and then try to trigger the left and right mouse buttons several times, just like playing the game normally).
```

### Expected Behavior

Pressing a button moves the viewpoint instead of triggering the left and right mouse buttons.

### Platform

```markdown
- Device model: HONOR 20 PRO 8/256
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20240423-11e0be0-v3_openjdk
```

**Comment by GaucovyAero** [comment]
please elaborate

**Comment by Xiaomo305Mua** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/168640573/66d16b6c-5b9b-4978-84f1-fb6096df17c0



> please elaborate

Because of the size of the upload, I cut some useless content from the video and only kept the content when the problem occurs, in the video I didn't press the left mouse button I only pressed the jump button, but it triggered the left mouse button

Uploading lv_0_20240501205742.mp4…

**Comment by Xiaomo305Mua** [comment]
> 请详细说明

？

**Comment by Xiaomo305Mua** [comment]
> please elaborate

？

**Comment by artdeell** [comment]
Turn off gestures if you don't want them

**Comment by Xiaomo305Mua** [comment]
> Turn off gestures if you don't want them

I need to be able to move the view while holding down the button

**Comment by GaucovyAero** [comment]
that is going to work just fine with the gestures off

**Comment by Xiaomo305Mua** [comment]
> that is going to work just fine with the gestures off

But you can't use the same finger to move the view while holding down a button, the FCL launcher can do it, if this is not a bug, can the Pojav launcher be updated with this feature?

**Comment by Xiaomo305Mua** [comment]
> that is going to work just fine with the gestures off

But you can't use the same finger to move the view while holding down a button, the FCL launcher can do it, if this is not a bug, can the Pojav launcher be updated with this feature?

**Comment by GaucovyAero** [comment]
you can do that on pojav lol

**Comment by Xiaomo305Mua** [comment]
> you can do that on pojav lol

But mouse-through triggers the left and right mouse buttons, I don't want that, I just want to be able to use the same finger to move the viewpoint while holding down the button, can this be split from the mouse-through function? I can do this with all four fingers, but it increases finger fatigue

**Comment by GaucovyAero** [comment]
> > you can do that on pojav lol
> 
> But mouse-through triggers the left and right mouse buttons, I don't want that, I just want to be able to use the same finger to move the viewpoint while holding down the button, can this be split from the mouse-through function? I can do this with all four fingers, but it increases finger fatigue

its triggering because you have the gestures on in the pojav settings

**Comment by Xiaomo305Mua** [comment]
> > > you can do that on pojav lol
> > 
> > 
> > But mouse-through triggers the left and right mouse buttons, I don't want that, I just want to be able to use the same finger to move the viewpoint while holding down the button, can this be split from the mouse-through function? I can do this with all four fingers, but it increases finger fatigue
> 
> its triggering because you have the gestures on in the pojav settings

However, if you turn off mouse-through, you can't use the same finger to move the view while holding down a button

**Comment by paim134** [comment]
So if you want to use the mouse penetration, and you also want to use the gesture, the above situation will occur (you press the jump button, but it also triggers the left mouse button)

> lv_0_20240501205742.mp4 
> > please elaborate
> 
> Because of the size of the upload, I cut some useless content from the video and only kept the content when the problem occurs, in the video I didn't press the left mouse button I only pressed the jump button, but it triggered the left mouse button
> 
> Uploading lv_0_20240501205742.mp4…

**Comment by paim134** [comment]
However, the player wants to be able to control the camera while holding down the button, rather than triggering the left and right mouse buttons at the same time.

**Comment by paim134** [comment]
The purpose of mouse penetration is to be able to control the viewing angle while pressing a button, and it does not trigger the left and right mouse buttons

**Comment by paim134** [comment]
> lv_0_20240501205742.mp4 
> > please elaborate
> 
> Because of the size of the upload, I cut some useless content from the video and only kept the content when the problem occurs, in the video I didn't press the left mouse button I only pressed the jump button, but it triggered the left mouse button
> 
> Uploading lv_0_20240501205742.mp4…
