### ISSUE TITLE
Minecraft java update 21

### ISSUE THREAD

**Issue by abdullah11071** [PojavLauncherTeam/PojavLauncher#5414]
### Is this request related to a bug?

I am playing minecraft in pojav launcher  at night I am starting pojav launcher it show that "update java21 or newer" please do some thing this thing happens after minecraft update 1.20.5 please update java 21 

### Describe the request.

Please update java 21 other wise the game does not start

### Anything else?

Please update java 21 thank you

**Comment by GaucovyAero** [comment]
Java 21 for arm64 phones: 
https://nightly.link/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/8216398145/jre21-aarch64.zip
Java 21 for arm32 phones: 
https://nightly.link/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/8216398145/jre21-aarch32.zip
after you download it, unzip the file. Open pojav, go to "settings>java tweaks>runtime manager>add new" and then select the java 21 tar.xz file
