### ISSUE TITLE
[Feature] <can select more java,not import them by users>

### ISSUE THREAD

**Issue by ufufvinoy** [PojavLauncherTeam/PojavLauncher#5418]
### Describe the request.

Making pojavlauncher like fcl,please.Github have java yet,but it's to complex and it's not the newest.This leeds to newer versions can't open.
![Screenshot_20240502_195321_com tungsten fcl](https://github.com/PojavLauncherTeam/PojavLauncher/assets/141605215/6190bb83-fb5c-427f-b678-4889da29f838)

**Comment by GaucovyAero** [comment]
wait for the next play store update
