### ISSUE TITLE
[BUG] Can't run 1.20.6

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5419]
### Describe the bug

I get this message when i try to run it, is there a java 21 that i can download? Or any way i can fix this?

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158475307/5148182e-1778-4b95-a3fc-121946a158be)

### Steps To Reproduce

```markdown
1. Launch 1.20.6
2. Scary message saying i need java 21
```

### Expected Behavior

I expected it to run just like the other versions 😀

### Platform

```markdown
- Device model: Galaxy A31
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Erm no

**Comment by GaucovyAero** [comment]
Java 21 for arm64 phones: 
https://nightly.link/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/8216398145/jre21-aarch64.zip
Java 21 for arm32 phones: 
https://nightly.link/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/8216398145/jre21-aarch32.zip
after you download it, unzip the file. Open pojav, go to "settings>java tweaks>runtime manager>add new" and then select the java 21 tar.xz file
