### ISSUE TITLE
[virtual mouse problems] <acceleration and pixel jumping>

### ISSUE THREAD

**Issue by ZackyTV2** [PojavLauncherTeam/PojavLauncher#5420]
### Describe the bug

the virtual mouse still has pixel skipping issues when you use it, for example;  clicking on the inventory to recraft, out of nowhere the mouse jumps to another position or simply accelerates. A discord user said he lowered the mouse's polling rate and resolved it.  I believe that calibrating the polling rate of the Pojav virtual mouse would solve this problem.  but it could be something else.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15196284/latestlog.txt)

### Steps To Reproduce

```markdown
whenever I make several clicks (butterfly for example) the cursor jumps pixels.
```

### Expected Behavior

It's remarkable to see how fluid the system cursor is and then you see what the pojav cursor looks like.  It would be great if there was some way to change the polling rate on the pojav cursor because it appears to be running at 60 Hz. It would be nice to have some way to make the system cursor work the same way as the game mouse (always return to the previous path). open inventory, etc.) or that the pojav cursor would work at a higher search rate.

### Platform

```markdown
- Device model: xiaomi poco f1
- CPU architecture: snapdragon 845
- Android version: 13
- PojavLauncher version: latest github version
```

**Comment by artdeell** [comment]
No videos?

**Comment by ZackyTV2** [comment]
> No videos?

I will provide

**Comment by ZackyTV2** [comment]
> No videos?

There's no way to send more than 10mb here, so I uploaded it to Mediafire

https://www.mediafire.com/file/m8xqtbi8td7g1ke/lv_0_20240503134137.mp4/file

**Comment by Luizpojavin** [comment]
bem quando aperta o botão tanto direito quanto esquerdo a tela e o mouse travam, no pojavlauncher da play store era so usar keymapper mas agora não funciona mais

**Comment by ZackyTV2** [comment]
> bem quando aperta o botão tanto direito quanto esquerdo a tela e o mouse travam, no pojavlauncher da play store era so usar keymapper mas agora não funciona mais

Sim mano! Mas antigamente eu não sofria com isso.
Nessa atualização de usar o mouse do pojav ajudpy muito na jogabilidade mais semelhante ao pc, mas infelizmente Também veio esses bugs

**Comment by GaucovyAero** [comment]
duplicate #5099
