### ISSUE TITLE
[F-Req] add news option

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5422]
### Is this request related to a bug?

No

### Describe the request.

In older version of pojav launcher. Have news option to check new features and links of pojav but now this option is gone.
![Screenshot_۲۰۲۴-۰۵-۰۳-۱۱-۰۱-۱۲-۷۷۱_com google android googlequicksearchbox-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/a5bc6b1b-af05-4f83-b8f5-d93576a44dda)

### Anything else?

No

**Comment by Mathias-Boulay** [comment]
We didn't maintain any news regarding pojav, hence its removal.

**Comment by ghost** [comment]
But your can start to maintain news regarding pojav. Pojav play store version update every year and every year add documents about new features added in pojav

**Comment by GaucovyAero** [comment]
we removed news also to reduce ram usage in pojav for slower devices
