### ISSUE TITLE
[BUG] otg mouse left click does not work in attacking/destroying blocks ingame

### ISSUE THREAD

**Issue by Xarl10** [PojavLauncherTeam/PojavLauncher#5424]
### Describe the bug

I'm experiencing an issue where my left-click functionality is not working correctly in Minecraft. Strangely, it works fine in GUIs and menus, but in-game actions like breaking blocks or attacking mobs are not registering. I've checked my mouse settings, verified that the left-click button works outside of Minecraft, and even tried resetting controls and updating pojav to the latest version. 

### The log file and images/videos

![IMG_20240503_202235](https://github.com/PojavLauncherTeam/PojavLauncher/assets/168829926/a1b67775-7cfb-4a0b-a12d-91f283a346cf)

### Steps To Reproduce

```markdown
1.otg turned on, connect my external kbd and mouse 
2.open pojav and load in a world
3.left click works in guis only and not ingame, right click works
```

### Expected Behavior

Expected everything to work just fine

### Platform

```markdown
- Device model: realme 5
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: Version edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I can't add the latestlog file, mine is 86mb lol

**Comment by GaucovyAero** [comment]
thats an issue with your specific phone os, ima keep this open but its very likely not going to get a fix any soon

**Comment by Xarl10** [comment]
Right, works on my old phone with android 12 but with a crappy chipset but I'm still looking forward to get any fix for thiss

**Comment by ScreyZee** [comment]
Bro my left click and right working on attacking and destroying block but not working in gui

**Comment by GaucovyAero** [comment]
should be fixed in the latest play store update
