### ISSUE TITLE
[BUG] <Short description> 

### ISSUE THREAD

**Issue by Neiry1yazar730** [PojavLauncherTeam/PojavLauncher#5425]
### Describe the bug

Não consigo fazer minha conta e também não consigo colocar mod e skin

### The log file and images/videos

O

### Steps To Reproduce

```markdown
1. que eu consiga colocar minha conta
```

### Expected Behavior

Espero que faça que eu consiga colocar minha conta e os mod

### Platform

```markdown
- Device model: moto e7 pawer
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: 1.20.4
```

### Anything else?

Não consigo colocar minha conta e também não consigo colocar mod e skin

**Comment by GaucovyAero** [comment]
buy minecraft and log into minecraft.net, a skin changer wont be available for pojav
