### ISSUE TITLE
[BUG] The new Java 17 does not work.

### ISSUE THREAD

**Issue by milosnail** [PojavLauncherTeam/PojavLauncher#5426]
### Describe the bug

When I launched the any version of the game with Java 17 it will always be exited with code 1. But when I tried running the game with Java 21 it does work but the problem is that Java 21 will give less fps.

### The log file and images/videos

![Screenshot_20240504-075817_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166671287/c0f096ed-fc23-4db7-8b1c-b5c481056fea)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15205844/latestlog.txt)

### Steps To Reproduce

```markdown
1. Set default java runtime to Java 17
2. Launch any versions
```

### Expected Behavior

I expected the app to launch the game properly without crashes.

### Platform

```markdown
- Device model: SM-T295
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: latest github actions
```

**Comment by GaucovyAero** [comment]
your minecraft version hasnt properly downloaded

**Comment by milosnail** [comment]
> your minecraft version hasnt properly downloaded

are you sure? , i tried running it with java 21 and it works perfectly fine.

**Comment by GaucovyAero** [comment]
yeah its weird, try removing the version from .minecraft/versions and redownload it

**Comment by milosnail** [comment]
> yeah its weird, try removing the version from .minecraft/versions and redownload it

it still doesn't work
