### ISSUE TITLE
Can't run Angelica

### ISSUE THREAD

**Issue by EvenWen1215** [PojavLauncherTeam/PojavLauncher#5428]
### Describe the bug

when i use Angelica +unimixins gtnhlib it will crash
But there are no problems when running gtnhlib + unimixins

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/15209245/latest.log)

### Steps To Reproduce

```markdown
run pojavlauncher and it Flashback
but when i use zink It will run but it is inefficient
```

### Expected Behavior

i hope it can run

### Platform

```markdown
- Device model: Redmi k60 pro
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
duplicate of #5416
