### ISSUE TITLE
The mouse wheel can not be used in the higher version. Please repair it as soon as possible.

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#543]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Maybe you should fill in the template?
Also, you should probably give some more info about game version, launcher version, hardware or emulated input...

**Comment by T-CATHOME** [comment]
@artdeell 
Device Model [redmi note 7 4/64]
CPU architecture [aarch64]
Android Version [10]
The mouse wheel is not available in version 1.13 or later.

**Comment by artdeell** [comment]
Launcher version?

**Comment by T-CATHOME** [comment]
@artdeell 
I use this version.
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/445514492

**Comment by artdeell** [comment]
Update to latest-est

**Comment by artdeell** [comment]
Also, is it on the physical mouse or on the touchscreen wheel emulation?

**Comment by T-CATHOME** [comment]
@artdeell Simulate on a touch screen

**Comment by artdeell** [comment]
Wheel buttons or the scroll emulation?

**Comment by T-CATHOME** [comment]
@artdeell Wheel buttons or the scroll emulation?
 What do you mean?

**Comment by artdeell** [comment]
One of the devbuilds added an ability to add buttons that would be whell scroll up or wheel scroll down
And scroll emulation is when you drag a list with your finger.

**Comment by T-CATHOME** [comment]
@artdeell  Wheel buttons.

**Comment by T-CATHOME** [comment]
@artdeell The latest version is still unavailable.

**Comment by khanhduytran0** [comment]
On app They are not called wheel button BUT on issue mentioned above.

**Comment by T-CATHOME** [comment]
@khanhduytran0 Can this bug be fixed?

**Comment by khanhduytran0** [comment]
A bug? Did you use virtual mouse while using onscreen wheel buttons?

**Comment by T-CATHOME** [comment]
@khanhduytran0 I used it.

**Comment by T-CATHOME** [comment]
@khanhduytran0 Can it be repaired?

**Comment by khanhduytran0** [comment]
Idk but if latest build fixed this?
