### ISSUE TITLE
[BUG] Farbic doesn't run on my friend's device. 

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5430]
### Describe the bug

Simply when he load the game with fabric, including non-mods and modded it's still crash with -1 message.
The game run fine with optifine and vanilla 1.18.2 and 1.20.1, but crash on the same version on farbic.

### The log file and images/videos

Logs: 
content://com.facebook.orca.securefileprovider/temp/orca_share_media1714737244280_7192129282635083422.txt
(Sorry my friend send me his logs though Facebook so i couldn't save it into file.)

### Steps To Reproduce

```markdown
First, I downloaded the game and after downloading it, I tried to go in and install the mod but I couldn't play the fabric. Then I got so frustrated that I deleted it, then today I downloaded it again and tried it, but it still didn't work, so I tried to install optifine, but I didn't expect it to work.
(Direct words from my friend)
```

### Expected Behavior

Just want to run farbic.

### Platform

```markdown
- Device model:gree g0215d  (Chinese cheap smartphone)
- CPU architecture: Snap 820.64-bit Kryo
- Android version: LineageOS Android 6.0.1 (Im do not sure cuz im not the owner of that device)
- PojavLauncher version: he said he download the latest version on Play Store.
```

### Anything else?

Contact my friends via Facebook if you want more infomation. https://www.facebook.com/profile.php?id=61550021536832&mibextid=ZbWKwL

**Comment by GaucovyAero** [comment]
tell your friend to upload the log onto another site (google drive, mediafire, mega, etc.) and send the link here

**Comment by TylerHaoNhot** [comment]
> tell your friend to upload the log onto another site (google drive, mediafire, mega, etc.) and send the link here

Here's the log.
https://drive.google.com/file/d/1oN2pj2nsKTZ9VSo9LHZ3LC4Q_Mnif7DG/view?usp=drivesdk
Actually, he didn't get the error -1 and crash. Just unable to get more logs.

**Comment by GaucovyAero** [comment]
fabric wont work on android 9 and lower because of android permissions (it does not let fabric create or access the intermediary file), if you have a fix for this on the code side we are open for PRs

**Comment by TylerHaoNhot** [comment]
> fabric wont work on android 9 and lower because of android permissions (it does not let fabric create or access the intermediary file), if you have a fix for this on the code side we are open for PRs

Hey, I wonder if there are any way to "force" it to have permission? Like rooting or something.
