### ISSUE TITLE
[BUG] <Short description>tidak ada profil

### ISSUE THREAD

**Issue by EMANRAHMAESA** [PojavLauncherTeam/PojavLauncher#5433]
### Describe the bug

https://github.com/settings/sessions/authentications/3160051547

### The log file and images/videos

https://github.com/settings/security

### Steps To Reproduce

```markdown
https://docs.github.com/articles/keeping-your-account-and-data-secure/
```

### Expected Behavior

https://github.com/settings/security-log

### Platform

```markdown
- Device model: oppoa18
- CPU architecture: 1800hz
- Android version: 14
- PojavLauncher version: 1.20.6
```

**Comment by artdeell** [comment]
Invalid data
