### ISSUE TITLE
[BUG]No Inventory when using Holy GL4es

### ISSUE THREAD

**Issue by zcxllt** [PojavLauncherTeam/PojavLauncher#5434]
### Describe the bug

No Inventory when using Holy GL4es
![Screenshot_2024-05-05-19-10-57-482](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165377218/9270c08b-3e51-44c3-834c-d3fdd959a6ba)

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/15212689/latest.log)
![Inventory](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165377218/079d264f-0c29-4adc-be41-c96b1582efaa)

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2. Open the World
3.No Inventory
```

### Expected Behavior

I hope to have Inventory when using Holy GL4es

### Platform

```markdown
- Device model: Lenovo TB-X606F
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20240503-84aca2e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use optifine and enable antialiasing to 2x fxaa in shaders settings

**Comment by zcxllt** [comment]
thank you
