### ISSUE TITLE
[F-Req] Unofficial F-Droid Repo

### ISSUE THREAD

**Issue by codenyte** [PojavLauncherTeam/PojavLauncher#5435]
### Is this request related to a bug?

Many people use Android without Google Play services and don't have access to the Play Store. An alternative platform, independent from Google, would be awesome.

### Describe the request.

Publish the app on the [F-Droid](https://f-droid.org/) app store.

**Comment by GaucovyAero** [comment]
f-droid's requirements are too strict for pojav, just install the apk from github actions or use apkmirror if you want an older version
im degoogled myself and have no issues with using that

**Comment by codenyte** [comment]
Could you at least publish APKs on GitHub releases so people can use apps like [Obtainium](https://github.com/ImranR98/Obtainium) to automatically download and install new updates? Or maybe host a custom F-Droid repo on GitHub? What about [IzzyOnDroid](https://apt.izzysoft.de/fdroid/), it doesn't have as strict requirements?

**Comment by GaucovyAero** [comment]
rename the issue and ima keep it open i guess

**Comment by ghost** [comment]
Pojav GitHub versions are very better than play store or any downloaders. If you download in GitHub you can debug pojav or enter to compatibility changes in developer option and any little updates come in GitHub not playstore or any downloaders. in playstore pojav update 1 time on every year but in GitHub updates are fast

**Comment by Mathias-Boulay** [comment]
Github release versions are the one being shipped to google play. There is no point in splitting release distribution for this use case.

**Comment by Mathias-Boulay** [comment]
actions builds are not considered stable, hence not published as releases
