### ISSUE TITLE
[F-Req] can you set termux to pojav?! 🥲

### ISSUE THREAD

**Issue by Reeao** [PojavLauncherTeam/PojavLauncher#5437]
### Is this request related to a bug?

![Screenshot_2024-05-07-20-03-34-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/PojavLauncherTeam/PojavLauncher/assets/163851911/2242c01a-809e-440b-a25e-8d2107b9ccba)

this is described and I need use termux in pojav

### Describe the request.

1. set terminal of termux to pojav
2. set box64 to arm64 version of pojav
3. set box86 to armv7 version of pojav
4. set wine64 to amd64 version of pojav
5. set wine to i386 + i686 version of pojav
6. set automatic latest ubuntu to pojav
7. set kde to pojav
8. set automatic java lts, automatic java non-lts and java 8 to pojav
9. remove java 17 to pojav
10. remove java 17 required minecraft java version to pojav
11. set gl4 to pojav renderer
12. create "PojavShader" as shader enabler and set PojavShader to pojav

**Comment by GaucovyAero** [comment]
no

**Comment by seroxyl** [comment]
unintelligible yapping
