### ISSUE TITLE
[re-post the question] the solution is most probably like fork pojav and move its minecraft directory into root

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5439]
the solution is most probably like fork pojav and move its minecraft directory into root

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues/687#issuecomment-2100448880_
            

Eek! Sorry for posting in the wrong place, but can you please guide me the solution...? I don't quite understand.

**Comment by GaucovyAero** [comment]
there is no solution, you gotta know how to code
