### ISSUE TITLE
[BUG] 1.20.4 blocks not rendering

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5440]
### Describe the bug

How do i fix

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158475307/fce0abf9-b8db-4159-92dc-a0cdf121aea1)

### Steps To Reproduce

```markdown
1. Launches pojavlauncher
2. Plays 1.20.4
3. Loads world
4. Blocks not rendering fully
```

### Expected Behavior

All blocks shouldve rendered correctly

### Platform

```markdown
- Device model: galaxy a31
- CPU architecture: MediaTek Helio P65 (Arm64)
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

no

**Comment by ghost** [comment]
Turn off alternate surface rendering in launcher setting or if you turned on render region in optifine turn off then and try again

**Comment by ghost** [comment]
I think it's render region because i have this bug after using render region in angle and holy gl4es renderers. Not alternate surface rendering but if you turn off render region and doesn't work try alternate surface rendering to off
