### ISSUE TITLE
OPTIFABRIC+REPLAY MOD NOT WORKING [BUG] <Short description>

### ISSUE THREAD

**Issue by DHRUV740** [PojavLauncherTeam/PojavLauncher#5441]
### Describe the bug

When i install fabric and then I also install fabric api 
Optifine optifabric and replay mod and I start fabric loader 1.19.4 but it's crash 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15250795/latestlog.txt)
So please give me solution 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15250840/latestlog.txt)

### Steps To Reproduce

```markdown
1. When I start or launch game then game will be crash because optifabric or reply mod not working
```

### Expected Behavior

Please give me solution to fix this type of error

### Platform

```markdown
- Device model: iq neo 7 
- CPU architecture: 64arc Mali 
- Android version: 14
- PojavLauncher version: letest
```

**Comment by ghost** [comment]
He says true i tested and crash replay mod without optifabric work normaly and optifabric without replay mod work normaly but replay with optifabric mod crash

**Comment by GaucovyAero** [comment]
yeah thats normal, the mods just dont work with each other, this would also happen to you on PC
