### ISSUE TITLE
[ Updates ] ptitSeb/GL4ES was updated to 1.1.6

### ISSUE THREAD

**Issue by Ezleak** [PojavLauncherTeam/PojavLauncher#5442]

**Comment by ghost** [comment]
I don't know gl4es 1.1.5 is faster or 1.1.6 but it's not much very different but good idea

**Comment by Ezleak** [comment]
> I don't know gl4es 1.1.5 is faster or 1.1.6 but it's not much very different but good idea

a little change 1.1.6 is faster but not much

**Comment by ghost** [comment]
Oh ok it's good. developer needs update it

**Comment by Mathias-Boulay** [comment]
pojav uses its own custom version, we already follow closely the developer changes
