### ISSUE TITLE
Проблема блютуз кдавиатуры

### ISSUE THREAD

**Issue by RaZrad** [PojavLauncherTeam/PojavLauncher#5444]
### баг с блютуз клавиатурой

В чате (по нажатию кнопки Т) не работает зажатие кнопки "backspace", но в других приложениях все отлично работает. 

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/164731463/36ee1efc-83af-4156-b46f-5e74aaeee332

### Steps To Reproduce

```markdown
1. Запустить игру
2. Нажать на клавиатуре букву "T"
3. Напечатать любой текст
4. Задать кнопку "backspace"
5. Готово сотрётся только один символ а остальные стераться не будут
```

### Expected Behavior

Я ожидаю, что при нажатии кнопки "T" открывалась и клавиатура(экранная) и чат.

### Platform

```markdown
- Device model: 2306EPN60G, Xiaomi 13T
- CPU architecture: Dimensity 8200-ultra, 8 ядер, максимально 3.1 ГГц
- Android version: Android 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
this is intended behavior, allowing to spam keys would decrease the performance of pojav
