### ISSUE TITLE
When can Zink be used on some old equipment, such as Huawei nova5z?

### ISSUE THREAD

**Issue by kwssdme** [PojavLauncherTeam/PojavLauncher#5445]
I'm just curious, that's all.
Huawei nova5z uses Kirin 810 mailGPU, but the version is very old.
But mailg52 seems to support vulkan1.1.0?
The performance seems to be good

**Comment by GaucovyAero** [comment]
you need vulkan 1.3 for zink

**Comment by Bel69420** [comment]
> you need vulkan 1.3 for zink

or vulkan 1.1 with good driver instead of broken driver
