### ISSUE TITLE
Mod true prime pice won't work[BUG] <Short description>

### ISSUE THREAD

**Issue by Jorgepopz** [PojavLauncherTeam/PojavLauncher#5449]
### Describe the bug

I'm using GitHub version of pojavluncher[version edelweiss-20240509-85a9f21-v3_openjdk]  and I download some mods to only 4 mods= true prime pice,Optifine, player animator,gekolib.
And my I don't change any settings other than increasing ram to 4000. Then I start loading 1.16.5 forge it's actually fully loaded but in the opening screen it crash😞 and I tried somuch time but end up crashing.
 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15285459/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavluncher 
2. Load forge 1.16.5
3. Loading screen appears 
4. Fully loaded and open Minecraft 
5. Crashes...😞
```

### Expected Behavior

I expect my 1.16.5 forge fully loaded and I can play Minecraft.

### Platform

```markdown
- Device model: Realme 8i 128 GB
- CPU architecture:  arm64-v8a,armeabi-v7a,armeabi
- Android version: 13
- PojavLauncher version: version edelweiss-20240509-85a9f21-v3_openjdk
```

**Comment by Jorgepopz** [comment]
Please help...🥲

**Comment by GaucovyAero** [comment]
your textures atlas is too big, remove mods that have a lot of textures
