### ISSUE TITLE
Zink crash on 6 render distance 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#5450]
### Describe the bug

Zink can only do 6 render distance 
Angle render get 32 render distance 

### The log file and images/videos

Plss fix

### Steps To Reproduce

```markdown
1. Create world on zink
2. Changed render distance to 8 crash

1. Create world on angel render
2. Change render distance to 8 nit crash I can do to 64 still not crashing
```

### Expected Behavior

Plss fix bug on zink

### Platform

```markdown
- Device model: Poco c65 8/250gb
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: Google play
```

### Anything else?

Plss fix this bug plss

**Comment by Bel69420** [comment]
1. Where's the latestlog?
2. We're not creator of zink renderer.
3. Stop yapping and just play with 6 chunks

**Comment by Bel69420** [comment]
There is no guarantee we will be able to fix the Zink renderer since we're not making this renderer.

**Comment by Bel69420** [comment]
Feel free to code the Zink renderer and fix it yourself :likebhai:
