### ISSUE TITLE
Zink Vulkan not working 

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#5451]
### Describe the bug

When I used zink Vulkan render my crash using latest Pojavlauncher GitHub but Google play zink works well plss fix

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15290473/latestlog.txt)

### Steps To Reproduce

```markdown
1. Change to zink Vulkan render 
2. Start the Pojavlauncher 
3. Crash
```

### Expected Behavior

Working on my phone Poco c65 I hope 

### Platform

```markdown
- Device model: Poco c65 8/250
- CPU architecture: 64
- Android version: 14
- PojavLauncher version:  GitHub latest update
```

### Anything else?

Plss fix

**Comment by ghost** [comment]
It's for OSMESA update solDev69 sayed after OSMESA update zink is not fully supported for mali gpu and he says true .my phone have adreno gpu but after this update game is very laggy. My fps before update 30 with shader bsl after osmesa update my fps is 4 with BSL
Don't worry we are closely to developer update
Play store not have this update

**Comment by ghost** [comment]
I talk about this
![Screenshot_۲۰۲۴-۰۵-۱۳-۱۶-۰۹-۲۱-۷۶۶_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/9ac0e4ca-0951-43ec-8eae-0688c9d2c256)

**Comment by kedrick021** [comment]
> I talk about this ![Screenshot_۲۰۲۴-۰۵-۱۳-۱۶-۰۹-۲۱-۷۶۶_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/330058955-9ac0e4ca-0951-43ec-8eae-0688c9d2c256.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDk5MDYsIm5iZiI6MTcxNTYwOTYwNiwicGF0aCI6Ii8xNDA0NjUyNjYvMzMwMDU4OTU1LTlhYzBlNGNhLTA5NTEtNDNlYy04ZWFlLTA2ODhjOWQyYzI1Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxNDEzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGJlMjViYjFiODQxY2ExNmJhMzMyNDNlYjJkMTQwMzQ1ZjRlYzMzMTU0OTZjOWUxNzg4ZmI1MTgxYWMwYThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lNGSF4v38SyPcwd8EiiE8OLFAhKl9V84HtX560CTu9k)

That update is only for 1.12 - 1.16 te the highest version is cradh
