### ISSUE TITLE
[F-Req] Using Holy GL4ES renderer via Termux

### ISSUE THREAD

**Issue by Sandendaty** [PojavLauncherTeam/PojavLauncher#5453]
### Describe the request.

Sorry I am not a developer and don't know much about this. But I am really curious about whether I can use Holy GL4ES renderer via Termux and play Minecraft in Linux Containers. I found that sometimes PojavLauncher might not be completely compatible with some external devices like bluetooth mice but Termux does better about the compatibility. However, PojavLauncher offers a very excellent renderer Holy GL4ES, but it seems that I can only use the renderer in PojavLauncher itself. So I am curious about whether there is a possibility to play Minecraft in Linux Containers and using Holy GL4ES.

**Comment by GaucovyAero** [comment]
i suggest using the pojav discord for stuff like this, not sure whether anybody has done this before

**Comment by alexytomi** [comment]
If you already have lxc's working then there's no point in using holygl4es, it depends on gles, but the lxc doesn't have the drivers. You also can't just pass it through.

on adrenos you can just use freedreno/turnip

on mali there is only panfrost, panvk, and reverse engineered drivers.

Translation layers won't work under an lxc. 

For questions like these do ask in the termux discord #gaming channel or the matrix bridge.
