### ISSUE TITLE
[BUG] 1.20.4 Forge 49.0.50 exited with code 1

### ISSUE THREAD

**Issue by milosnail** [PojavLauncherTeam/PojavLauncher#5454]
### Describe the bug

when i launched 1.20.4 forge 49.0.50 after a while it will exited with code 1 and the game doesn't close also

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15320001/latestlog.txt)

### Steps To Reproduce

```markdown
1. Launch the game in 1.20.4-forge-49.0.50
2. Wait
```

### Expected Behavior

I expect the game to launch properly without crash

### Platform

```markdown
- Device model: SM-T295
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: latest GPlay version
```

### Anything else?

I tried reinstalling forge to make sure that nothing is corrupted but nothing worked.

**Comment by GaucovyAero** [comment]
update to the latest github actions build
