### ISSUE TITLE
[BUG] forge and optifine not automatically install

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5455]
### Describe the bug

I will use modded versions fabric optifine and forge it's not install but i use jar file it's install perfectly in older version of pojav modded version automatically install without any problem

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/3775c203-ce49-4e9d-9f15-b0b646c9615d

### Steps To Reproduce

```markdown
1:open pojav
2:click on modded version
3:click on fabric or optifine and forge
4:not work just a black screen
```

### Expected Behavior

I expect use older version of pojav modded versions can automatical install but now i don't have any choice to download with jar file

### Platform

```markdown
- Device model: poco f5 12/256gb
- CPU architecture: aarch64 
- Android version: 14
- PojavLauncher version: latest version on GitHub
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
you can still run the jar manually

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
Probably fixed i don't know which update and when but i don't have this problem in newer version of pojav

**Comment by ghost** [comment]
Thanks
