### ISSUE TITLE
Ui buttons not clicking in mouse

### ISSUE THREAD

**Issue by ScreyZee** [PojavLauncherTeam/PojavLauncher#5457]
### Describe the bug

I connected mouse and keyboard in my mobile. And my mouse is working but when I open pojav and click on Minecraft ui buttons it's not working but u can destroy and place block but can't click ui buttons 

### The log file and images/videos

![Screenshot_2024-05-15-17-57-06-53_99c04817c0de5652397fc8b56c3b3817](https://github.com/PojavLauncherTeam/PojavLauncher/assets/169906339/889987b2-badc-43b1-a974-606007433f87)

### Steps To Reproduce

```markdown
;-;
```

### Expected Behavior

My keyboard and mouse working but not clicking ui buttons in pojav

### Platform

```markdown
- Device model:Realme 11x5g 
- CPU architecture: 
- Android version: 14
- PojavLauncher version: latest
```

### Anything else?

Nah

**Comment by GaucovyAero** [comment]
most probably device-related

**Comment by GaucovyAero** [comment]
will consider this as a wontfix for now

**Comment by ScreyZee** [comment]
Did anyone know how should I fix this?

**Comment by GaucovyAero** [comment]
> Did anyone know how should I fix this?

try turning off screen gestures whatever that means (triple finger screenshot, etc. 
this might not help tho

**Comment by ScreyZee** [comment]
> > Did anyone know how should I fix this?
> 
> try turning off screen gestures whatever that means (triple finger screenshot, etc. this might not help tho

;-; I tired it's not working I can place block and destroy but can't click on ui buttons

**Comment by Frostybtfindingscript** [comment]
> > > Did anyone know how should I fix this?
> > 
> > 
> > try turning off screen gestures whatever that means (triple finger screenshot, etc. this might not help tho
> 
> ;-; I tired it's not working I can place block and destroy but can't click on ui buttons

Try unplugging and plug it back in?

**Comment by ScreyZee** [comment]
> > > > Did anyone know how should I fix this?
> > > 
> > > 
> > > try turning off screen gestures whatever that means (triple finger screenshot, etc. this might not help tho
> > 
> > 
> > ;-; I tired it's not working I can place block and destroy but can't click on ui buttons
> 
> Try unplugging and plug it back


> > > > Did anyone know how should I fix this?
> > > 
> > > 
> > > try turning off screen gestures whatever that means (triple finger screenshot, etc. this might not help tho
> > 
> > 
> > ;-; I tired it's not working I can place block and destroy but can't click on ui buttons
> 
> Try unplugging and plug it back in?

I tried on pocket edition and it's working but not working on pojav

**Comment by Zeltron14y** [comment]
Bro I'm also having same issue it's not device related I tried in 3 phone one plus realme and Vivo

**Comment by ScreyZee** [comment]
> Bro I'm also having same issue it's not device related I tried in 3 phone one plus realme and Vivo

Bro how can I fix this ;-;

**Comment by Zeltron14y** [comment]
Idk bro fr

**Comment by ScreyZee** [comment]
> Idk bro fr

Bro my keyboard and mouse is zebronics Zeb companion 500 and what is ur?

**Comment by Zeltron14y** [comment]
Portronics key 5 combo wireless

**Comment by ScreyZee** [comment]
> Portronics key 5 combo wireless

That means it's not keyboard related bro u said that u tried on other phones and it's not working  I think it's a pojav launcher bug :-: I hope it will fix soon

**Comment by Zeltron14y** [comment]
Why pojav team isn't replying to this problem

**Comment by kiokori-git** [comment]
> Why pojav team isn't replying to this problem

we are unpaid team, we do this as a hobby, be patient

**Comment by Zeltron14y** [comment]
Let's hope for the best ig

**Comment by ScreyZee** [comment]
> > Why pojav team isn't replying to this problem
> 
> we are unpaid team, we do this as a hobby, be patient

Bro please solve this ;-;

**Comment by GaucovyAero** [comment]
> Why pojav team isn't replying to this problem

devs currently dont have any phone that has these issues

**Comment by ScreyZee** [comment]
I deleted android 14 and updated to android 13 and it fixed

**Comment by ScreyZee** [comment]
Haha

**Comment by Zeltron14y** [comment]
Lemme try aswell

**Comment by Zeltron14y** [comment]
Can u tell how u download android 13

**Comment by Zeltron14y** [comment]
And delete 14

**Comment by ScreyZee** [comment]
U can search on YouTube how to uninstall A14 update in ( device name)

**Comment by ScreyZee** [comment]
But bro when u uninstall A14 ur mobile will be reset
