### ISSUE TITLE
Shaders dont load up.

### ISSUE THREAD

**Issue by matrSid** [PojavLauncherTeam/PojavLauncher#5458]
### Describe the bug

I’m trying to use a shader on my pojavlauncher (Optifine) but when I use it, its just a black screen. Im using open4es shaders which im pretty sure is conpatible.

### The log file and images/videos

none

### Steps To Reproduce

```markdown
1. Launch minecraft
2. Go to settings > shaders
3. Select shader
4. Click done
```

### Expected Behavior

I expect the shader to load up properly

### Platform

```markdown
- Device model: Ipad Pro 4th Gen
- CPU architecture: -
- Android version: iOS 17.4 
- PojavLauncher version: 2.2
```

**Comment by ItAnthon** [comment]
a few things: 1: prior to downloading [this](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions) be sure that there’s nothing you care about in your current pojavlauncher 2.2 installation. and i mean anything. 

2: delete PojavLauncher 2.2 and download PojavLauncher from github actions for the latest features and bug fixes. 2.2 is outdated.

**Comment by ItAnthon** [comment]
also for your sake stop updating your ipad

**Comment by GaucovyAero** [comment]
wrong repository
