### ISSUE TITLE
[BUG] Failed to load light and shadow

### ISSUE THREAD

**Issue by mgxhhg** [PojavLauncherTeam/PojavLauncher#5459]
### Describe the bug

When I loaded the light and shadow, it crashed when entering the world

### The log file and images/videos

1.  ![IMG_20240517_031805](https://github.com/PojavLauncherTeam/PojavLauncher/assets/97750654/939d81fb-c030-4b1a-88c6-a05bd4a59aaf)_
![Screenshot_2024-05-17-03-58-28-146_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/97750654/457ee0a5-e115-4861-81be-ada5ee4042be)
![Screenshot_2024-05-17-03-34-28-666_com android settings](https://github.com/PojavLauncherTeam/PojavLauncher/assets/97750654/18151717-ca30-4c65-8f19-663906a412a1)

2. Log:

--------- beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 23116PN5BC
Info: API version: 34
Info: Selected Minecraft version: 1.20.1-forge-47.2.32
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=3116
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~z1ZlDRX4W3LfC6WJyOP97Q==/net.kdt.pojavlaunch-f7rWXTb4pv1pBXwlp5BkcA==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~z1ZlDRX4W3LfC6WJyOP97Q==/net.kdt.pojavlaunch-f7rWXTb4pv1pBXwlp5BkcA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1440
2024-05-17 03:52:24,464 main ERROR appender Console has no parameter that matches element Policies
[03:52:24] [main/INFO]: ModLauncher running: args [--username, ggv, --version, 1.20.1, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 5, --uuid, 00000000000000000000000000000000, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.32, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[03:52:24] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17-internal by N/A; OS Linux arch aarch64 version Android-14
[03:52:24] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
Registered forkAndExec
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[03:52:25] [main/INFO]: Trying GL version 4.6
AdrenoSupp: Loaded Turnip, loader address: 0xecf189189246472d
OSMDroid: generating context

### Steps To Reproduce

```markdown
Install shaders to mods, start the app, select the world, the interface prompts: world loading, world saving, the app crashes, try changing the driver but it still crashes
```

### Expected Behavior

No

### Platform

```markdown
- Device model: XIAOMI 14 PRO
- CPU architecture: 8gen3 arm64-v8a
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484dOc-v3_openjdk
```

### Anything else?

No

**Comment by mgxhhg** [comment]
Since the log selection is wrong, please select this

https://drive.google.com/file/d/10fDd72M4Y_3p0se4XHMPWV7yZvmMt8sg/view?usp=drivesdk

**Comment by GaucovyAero** [comment]
> Since the log selection is wrong, please select this
> 
> https://drive.google.com/file/d/10fDd72M4Y_3p0se4XHMPWV7yZvmMt8sg/view?usp=drivesdk

this log does not have public access

**Comment by mgxhhg** [comment]
> > 由于日志选择错误，请选择此项
> > https://drive.google.com/file/d/10fDd72M4Y_3p0se4XHMPWV7yZvmMt8sg/view?usp=drivesdk
> 
> 该日志没有公共访问权限

Updated, now it works

**Comment by mgxhhg** [comment]
@GaucovyAero Updated, now it works

**Comment by GaucovyAero** [comment]
remove embeddium and all the mods that depend on it

**Comment by mgxhhg** [comment]
@GaucovyAero  have also tried optifine, and the app crashed as well, so is there any recommended light and shadow loader?

**Comment by GaucovyAero** [comment]
> @GaucovyAero have also tried optifine, and the app crashed as well, so is there any recommended light and shadow loader?

no
