### ISSUE TITLE
HELP ME 

### ISSUE THREAD

**Issue by christopher2305** [PojavLauncherTeam/PojavLauncher#546]
**Describe the bug**
When I want to start forge 1.7.10 I get a message that has been closed with code 1 

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [Huawei P10]
 - CPU architecture [aarch64] 
 - Android Version [9]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by christopher2305** [comment]
![Screenshot_20201227_214314_net kdt pojavlaunch](https://user-images.githubusercontent.com/55072771/103188107-bf7a0b80-488c-11eb-995f-3d6144ff97d6.jpg)

**Comment by Manhdayne** [comment]
If you install some mods please try to remove it

**Comment by WesleyVanNeck** [comment]
@christopher2305  with no log no help

**Comment by christopher2305** [comment]
Sorry

content://com.whatsapp.provider.media/item/d18a26e6-e2b8-43ae-87ff-80f15b25936a

**Comment by khanhduytran0** [comment]
That address is only accessible local
