### ISSUE TITLE
[F-Req] Fix x and y axis inverted OTG mouse on some android 13

### ISSUE THREAD

**Issue by Frostybtfindingscript** [PojavLauncherTeam/PojavLauncher#5460]
### Is this request related to a bug?

Yes this is related to a bug, when landscape mode on my phone my mouse inverts the y and x axis example: 
I move my mouse up it either goes right or left and when i move my mouse down it either moves left or right same thing if i moved it to left or right.

### Describe the request.

Plez fix thiz <3 so that the mouse wont be inverted,

### Anything else?

device: 
- Device model: Infinix Hot40i 8-16/256G
- CPU architecture: octa-core Cortex-A75
- Android version: 13
- PojavLauncher version: edelweiss-20240509-85a9f21-v3_openjdk

**Comment by Frostybtfindingscript** [comment]
I had to litterly inver my mouse into 90 degrees

**Comment by GaucovyAero** [comment]
device not specified

**Comment by Frostybtfindingscript** [comment]
> device not specified

Added

**Comment by GaucovyAero** [comment]
duplicate issue
