### ISSUE TITLE
[BUG] OTG mouse Y and X Axis inverted on some android 13 phones

### ISSUE THREAD

**Issue by Frostybtfindingscript** [PojavLauncherTeam/PojavLauncher#5463]
### Describe the bug

I don't have any solution on this but when u specifically play minecraft pojavlauncher and mcpe it always inverts the Y and X axis i think the mouse works perfectly in android 12 devices idk though,

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1. Get an android 13 device
2. Download the new pojavlauncher debug update
3. Create local account
4. Download any version
5. Connect OTG mouse and keyboard to the device
6. Load up the version you downloaded.
7. And if it works for you that it dont invert then lucky you i guess.
```

### Expected Behavior

The mouse will not invert and work as expected.

### Platform

```markdown
- Device model: INFINIX HOT40I 8GB/256GB
- CPU architecture: octa-core Cortex-A75 
- Android version: 13
- PojavLauncher version: edelweiss-20240509-85a9f21-v3_openjdk
```

### Anything else?

> **really need a fix to this and i also made one bug report before this.**

**Comment by GaucovyAero** [comment]
Lenovo XiaoXin Pad Pro 12.7 (Android 13) and Motorola G14 (Android 13) are also affected

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/12ca60cb-6dd2-481d-880a-1158005518d5)

**Comment by Josh915x** [comment]
Im having the same problem, bought my usb hub and got it today, but when I tried to move my camera around in Minecraft, the y axis of the mouse becomes the x axis on the game, vice versa. Please, could someone help?
(Im on android 13)

**Comment by awgybop1** [comment]
Same bug with a Samsung Tab S7 on Android 13 with the keyboard/trackpad attachment. The control axis rotates 90 degrees to the left. (ex. swipe up=look right, swipe left=look up)

**Comment by GaucovyAero** [comment]
> Same bug with a Samsung Tab S7 on Android 13 with the keyboard/trackpad attachment. The control axis rotates 90 degrees to the left. (ex. swipe up=look right, swipe left=look up)

open a new issue, yours is different

**Comment by GaucovyAero** [comment]
closing this issue as a wontfix since this also affects other apps and is 100% an OS-related issue on all motorola/lenovo devices
