### ISSUE TITLE
[BUG] artifact downloads only work for signed in users

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5465]
### Describe the bug

I am unable to download jdk21 on my phone because I'm not signed in there and it would be inconvenient to do so especially for users without any need for accounts

### The log file and images/videos

404 not found

### Steps To Reproduce

```markdown
make sure you're not signed into github then go to https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/8805754633 and try to download from artifacts
```

### Expected Behavior

regardless of whether a user is signed in or not, the downloads should work

### Platform

```markdown
- Device model: 
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version:
```

### Anything else?

further discussion: https://github.com/actions/upload-artifact/issues/51
possible solution: https://github.com/actions/upload-artifact/issues/51#issuecomment-1424698542

**Comment by ghost** [comment]
Frist don't download jdk download jre file. Jre have necessary feature to run a java app but jdk have unnecessary features you don't need jdk and you need to register to download pojav launcher GitHub versions and java versions need to login or register to download. GitHub is trusted website

**Comment by kasrarouhi** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions?query=branch%3Abuildjre21

**Comment by ghost** [comment]
ah right, security and convenience
