### ISSUE TITLE
Vic modern warfare cubed mod crash

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#5466]
### Describe the bug

When I tried to open the inventory in Vic modern guns item is crashing my game 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15367428/latestlog.txt)

### Steps To Reproduce

```markdown
1. Pojavlauncher zink 
2. Pojavlauncher holigl4es
3. Start Pojavlauncher 
4. Create world 
5. Open inventory gun item crashed
```

### Expected Behavior

Plss fix 

### Platform

```markdown
- Device model: Poco c65 
- CPU architecture: 64 8/250
- Android version: 14
- PojavLauncher version: Google play
```

### Anything else?

Plss fix

**Comment by Mathias-Boulay** [comment]
#1948
