### ISSUE TITLE
[BUG] <Stuck on world loading screen on Chromebook>

### ISSUE THREAD

**Issue by AndreCodin24** [PojavLauncherTeam/PojavLauncher#5467]
### Describe the bug

Hello, guys, So I tried to load up my world, and got stuck on the world loading screen. Can anyone fix this? I'm on my Chromebook.

### The log file and images/videos

Quick update for my comment, I put a log on my comment
### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Load up your world
3. You stuck in world loading screen, and taking forever
```

### Expected Behavior

The world loading screen was taking so long, and it wouldn't join the world.

### Platform

```markdown
- Device model: Google dedede
- CPU architecture: 
- Android version: 
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

When you load up your world, you literally stuck waiting for the world loading screen.

**Comment by ghost** [comment]
You using pojav launcher in laptop? Do not use pojav on laptop is not compatible. Use Tlauncher for pc or any android and ios device for pojav. not pc

**Comment by kiokori-git** [comment]
do not do what @kasrarouhi just said, TLauncher is a spyware.

**Comment by kiokori-git** [comment]
@AndreCodin24 please attach a log

**Comment by ghost** [comment]
It's just a recommendation. i watched videos about tlauncher have virus so i think it's not very trusted but it's famous launcher for minecraft. MultiMC is another launcher i think it's okay to use but minecraft launcher is trusted

**Comment by GaucovyAero** [comment]
send log

**Comment by AndreCodin24** [comment]
Ah yeah, here's a log. 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15371187/latestlog.txt)

**Comment by AndreCodin24** [comment]
> do not do what @kasrarouhi just said, TLauncher is a spyware.

I know, I know. TLauncher is a virus. Thanks

**Comment by AndreCodin24** [comment]
Ah yeah, here's a log. 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15371187/latestlog.txt)

**Comment by GaucovyAero** [comment]
yeah thats pretty weird, be sure to turn off render regions in video settings - performance

**Comment by ghost** [comment]
If you using holy gl4es renderer

**Comment by AndreCodin24** [comment]
> If you using holy gl4es renderer

yes its fast I think..

**Comment by AndreCodin24** [comment]
> yeah thats pretty weird, be sure to turn off render regions in video settings - performance

yep
