### ISSUE TITLE
I miss the old interface of this pojavlaucher so much 🥹

### ISSUE THREAD

**Issue by lehoanduphong** [PojavLauncherTeam/PojavLauncher#5468]
### Is this request related to a bug?

No

### Describe the request.

I wish it would come back 🥹
![Screenshot_2024-05-19-12-56-27-028_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/103303530/4ce1b14b-c922-4eab-8e0f-8e035237e548)
![Uploading Screenshot_2024-05-19-12-58-31-301_net.kdt.pojavlaunch.jpg…]()

**Comment by ghost** [comment]
NOSTALGIA. I like that
