### ISSUE TITLE
Add support for OpenGl 3.0

### ISSUE THREAD

**Issue by QuasyStellar** [PojavLauncherTeam/PojavLauncher#547]
When I'm trying to install shaders or make the graphics awesome. I see a warning that OpengGl is 2.1 and it is not supported. But I know that my video card supports OpenGl 3.2. Maybe if you add support for OpenGl 3 and higher, it may be possible to install shaders.

**Comment by artdeell** [comment]
Ask for it in this repo https://github.com/ptitSeb/gl4es - that's the command converter that we use (y'know that phone and PC OpenGL are different?)

**Comment by Google61** [comment]
gl4es supports only OpenGL (desktop) 2.x -> OpenGL ES 2.x (android) conversion

**Comment by r44r44** [comment]
How to download?

**Comment by Druxelite** [comment]
There isn't any stable open gl 3.0, if you try to use an unstable build it would lag horribly and be filled with a butt load of bugs

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
