### ISSUE TITLE
[BUG] weird double click when operating too quickly

### ISSUE THREAD

**Issue by Silvigarabis** [PojavLauncherTeam/PojavLauncher#5470]
### Describe the bug

After I install the latest build of `v3_openjdk`, when I use the virtual mouse to operate quickly, some operations may be input as double-clicks, but I don't want to trigger a double-click.

For example: Now I am sorting items in my inventory. I hold a bunch of items in my hand, press and hold the touchpad, and move the cursor to the position I want. I quickly release my finger, and then click the screen to drop items.  Then quickly release it, and then press and hold the screen again to move the cursor to the next item.  But Pojav seemed to see me touching the screen twice in a short period of time and interpreted my operation as a double-click input to the game. As a result, my item was put down and then picked up again.

Now I have to wait a while after each time I drop the item to avoid it being considered a double click.  And this delay is very uncomfortable.

### The log file and images/videos

before update, with build <https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9022894637>:

https://github.com/PojavLauncherTeam/PojavLauncher/assets/73000464/1fc6f8de-5560-4c4e-8f01-92e7be853722

after update, with build <https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9142570207>:

https://github.com/PojavLauncherTeam/PojavLauncher/assets/73000464/98b15999-e48d-41b0-a352-baa569960607

### Steps To Reproduce

```markdown
Here are the steps that demonstrate the impact of this behavior, but not the only one

1. launch the game and join in the world, and take some item to your inventory 
2. open inventory
3. with virtual mouse, to pickup an item (just left-click the item)
4. move cursor to any empty slots
5. (do it quickly!) click on touchpad, or hold your finger to the touchpad, then release it.
6. (do it quickly!) hold your finger on the touchpad (because you want to move the cursor to the other items), and drag your finger on the touchpad
7. weird double-click happened, the items placed before back to your cursor now
```

### Expected Behavior

I want to place the item to the slot normally, instead of triggering a double click. In other words, I want to trigger the double-click when there is a real double-click, rather than triggering the double-click when the screen is touched again without releasing after the first click.

### Platform

```markdown
- Device model: Huawei DUB-AL00
- CPU architecture: aarch64
- Android version: 8.1
- PojavLauncher version: edelweiss-20240518-3443b04-v3_openjdk
```

### Anything else?

I'm also testing it with build <https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9148192919>, because its name contains "control", but the buggy behaviour still appears.
At the same time, when I wrote this issue, the `v3_openjdk` branch seemed to have a new commit, but it seemed that it was only the "control" branch that was merged, so I believe this problem still exists in the latest build.

Finally, if we ignore the problem above, the double-click operation works just fine!  Can directly gather scattered similar items.

**Comment by Frostybtfindingscript** [comment]
Maybe just add a Q button?

**Comment by Frostybtfindingscript** [comment]
> Maybe just add a Q button?

My bad didn't read it full.

**Comment by Mathias-Boulay** [comment]
Hi there @Silvigarabis, first of all thank you for the detailed report, it made reproducing the issue very quick. I'm looking into it

**Comment by Mathias-Boulay** [comment]
@Silvigarabis Can you try this build : https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9158891889 ?
Hopefully it works as intended

**Comment by Silvigarabis** [comment]
> @Silvigarabis Can you try this build : https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9158891889 ? Hopefully it works as intended

(*The specified build didn't succeed, I checked and found that it was just because there was out of memory, so I forked the repository, then manually triggered a build, and tested it using the built apk: <https://github.com/Silvigarabis/PojavLauncher/actions/runs/9159337062>*)

There seems to be no problem. The accidental double-click has not occurred again, and there is no problem with the normal double-click operation.

https://github.com/PojavLauncherTeam/PojavLauncher/assets/73000464/6d12d737-3610-4c97-bc3d-4f43270bfc62

I think this should be successfully fixed
