### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Daviliraushs** [PojavLauncherTeam/PojavLauncher#5476]
### Describe the bug

please fix the control bug in the new version of pojavlauncher, the control I'm trying to place is not supported
![Screenshot_20240520-225056_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/5fda4d3b-e9cd-40fe-a2ee-c0e3bc7a6cba)

### The log file and images/videos

please fix the control bug in the new version of pojavlauncher, the control I'm trying to place is not supported
![Screenshot_20240520-225056_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/5fda4d3b-e9cd-40fe-a2ee-c0e3bc7a6cba)

### Steps To Reproduce

```markdown
please fix the control bug in the new version of pojavlauncher, the control I'm trying to place is not supported
![Screenshot_20240520-225056_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/5fda4d3b-e9cd-40fe-a2ee-c0e3bc7a6cba)
```

### Expected Behavior

please fix the control bug in the new version of pojavlauncher, the control I'm trying to place is not supported
![Screenshot_20240520-225056_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/5fda4d3b-e9cd-40fe-a2ee-c0e3bc7a6cba)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

please fix the control bug in the new version of pojavlauncher, the control I'm trying to place is not supported
![Screenshot_20240520-225056_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/5fda4d3b-e9cd-40fe-a2ee-c0e3bc7a6cba)

**Comment by GaucovyAero** [comment]
thats not a bug, thats likely your controlmap being too old

**Comment by GaucovyAero** [comment]
nevermind, keeping closed as its a duplicate issue
