### ISSUE TITLE
[BUG] Unsupported layout error

### ISSUE THREAD

**Issue by JLeBKa** [PojavLauncherTeam/PojavLauncher#5479]
### Describe the bug

When I press Start button or when I'm trying to edit layout, I get this message named "Unsupported control layout version"

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15389321/latestlog.txt)
![Screenshot_2024-05-21-17-42-09-732_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/170422270/4abaa2b2-7568-480a-a076-682853677f34)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Press "User layout"
3. Change default layout and save it
4. Join the game or press "User layout" again
```

### Expected Behavior

I expect I will normally join the game

### Platform

```markdown
- Device model: Redmi Note 12 Pro+ 5G 8/256G
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20240520-f872f11-v3_openjdk
```

**Comment by sqx02a** [comment]
Same, device: Samsung galaxy a54

**Comment by JLeBKa** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9174466296
This version got "Unsupported control layout version" error fix

**Comment by MovTery** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9174466296 This version got "Unsupported control layout version" error fix

@JLeBKa This is just a Pull Request submission and has not been officially merged into this code repository yet.
