### ISSUE TITLE
[BUG] Weird controls behavior 

### ISSUE THREAD

**Issue by Ruslanllll** [PojavLauncherTeam/PojavLauncher#5481]
### Describe the bug

the buttons work every once in a while

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/86971528/4ff8e4b7-820e-454c-b3de-700ac00d0d1a

### Steps To Reproduce

```markdown
1. Join to the server
2. Try to click any buttons or write text with keyboard
```

### Expected Behavior

Normal buttons behavior

### Platform

```markdown
- Device model: Samsung galaxy A52
- CPU architecture: aarch64
- Android version: 12 
- PojavLauncher version: f0daae373e0cf2afb9cdfce86bfad13101a911fd (from gh actions)
```

**Comment by GaucovyAero** [comment]
dont use sodium

**Comment by Ruslanllll** [comment]
> dont use sodium

This issue occurs on Zink even without mods

**Comment by GaucovyAero** [comment]
> > dont use sodium
> 
> This issue occurs on Zink even without mods

reproduce it and show video

**Comment by Ruslanllll** [comment]
> > > dont use sodium
> > 
> > 
> > This issue occurs on Zink even without mods
> 
> reproduce it and show video

The problem seems to have gone away, sorry.
