### ISSUE TITLE
RlCraft shutting down internal server

### ISSUE THREAD

**Issue by VzLatte** [PojavLauncherTeam/PojavLauncher#5485]
### Describe the bug

Whenever I open a new world or try to play one in RLCraft it says shutting down internal server

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15412751/latestlog.txt)

### Steps To Reproduce

```markdown
Download RlCraft and open any world or server
```

### Expected Behavior

I should be able to play but it crashes instead

### Platform

```markdown
- Device model: oppo a77s
- CPU architecture: idk
- Android version: 14
- PojavLauncher version: latest in play store as of May 2024
```

**Comment by ghost** [comment]
In order for RLCraft to not crash, remove these mods:
1:custommainmenumod
2:fancyblockparticles
3:dynamic surroundings
4:soundfilters

If you wanna install optifine for Rlcraft . After enter a world in invertory or in item list 50% of items have wierd black and pink texture for fix the issue you need to turn off (emissive textures) but after turn off game frezes and you can't turn off it for turn off this option go to pojav launcher files and enter (options.txt) and find emissive texture and write off and texture fix

**Comment by ghost** [comment]
And use performance mods like better fps or optifine because Rlcraft is a heavy modpack for phone my phone have snapdragon 7 gen 2 plus and rlcraft fps is 50 or 70 with render distance 12. And use jvm arguments for performance

**Comment by kasrarouhi** [comment]
Use this jvm argument
-Xmx4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+DisableExplicitGC -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+PerfDisableSharedMem -XX:-UsePerfData -XX:+ParallelRefProcEnabled -XX:+UseThreadPriorities -XX:+OmitStackTraceInFastThrow -XX:+UseFastUnorderedTimeStamps -XX:+UseLargePages -XX:+UseLargePagesInMetaspace -XX:+UseTransparentHugePages -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:CompileThreshold=300 -XX:MaxGCPauseMillis=100 -XX:G1HeapRegionSize=4M -XX:InitiatingHeapOccupancyPercent=15 -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20

**Comment by FranklinAzriel** [comment]
skill issue

**Comment by kiokori-git** [comment]
> I think Use this jvm argument is helpful if not crash for you phone
> -Xmx4G -Dsun.rmi.dgc.server.gcInterval=[2147483646](tel:2147483646) -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+DisableExplicitGC -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+PerfDisableSharedMem -XX:-UsePerfData -XX:+ParallelRefProcEnabled -XX:+UseThreadPriorities -XX:+OmitStackTraceInFastThrow -XX:+UseFastUnorderedTimeStamps -XX:+UseLargePages -XX:+UseLargePagesInMetaspace -XX:+UseTransparentHugePages -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:CompileThreshold=300 -XX:MaxGCPauseMillis=100 -XX:G1HeapRegionSize=4M -XX:InitiatingHeapOccupancyPercent=15 -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20

JVM Arguments don't help with performance, stop. you are NOT helping. you are misleading users.

**Comment by ghost** [comment]
I researched about it in 
https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks
And
https://cassiofernando.netlify.app/blog/minecraft-java-arguments
It's actually helped me around 5 fps

**Comment by ghost** [comment]
![IMG_۲۰۲۴۰۵۲۳_۱۵۴۱۵۸](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/33d769c6-8a59-44bb-b887-5e1604590c30)

**Comment by FranklinAzriel** [comment]
yep it can affect performance
but not worth for using it

wasting time!

**Comment by FranklinAzriel** [comment]
Also kinda useless to tell this into github issues page

**Comment by ghost** [comment]
Yeah. you right

**Comment by kiokori-git** [comment]
> ![IMG_۲۰۲۴۰۵۲۳_۱۵۴۱۵۸](https://private-user-images.githubusercontent.com/140465266/333176677-33d769c6-8a59-44bb-b887-5e1604590c30.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjcxMDcsIm5iZiI6MTcxNjQ2NjgwNywicGF0aCI6Ii8xNDA0NjUyNjYvMzMzMTc2Njc3LTMzZDc2OWM2LThhNTktNDRiYi1iODg3LTVlMTYwNDU5MGMzMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMjIwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzhkYjBlYjlhYjA0NDRhYjIwNTdjNjAyYjNlNWM0ZGUzNTdiYmU4NWYxM2M5YjQxNzBhNWQ4YzVjOTFkNDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eBPrZdEDz_r0rzJPS2hyH-xP9sojub4hMAKjqaZeHDQ)

not everything on google is true.

**Comment by kiokori-git** [comment]
> I researched about it in
> https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks
> And
> https://cassiofernando.netlify.app/blog/minecraft-java-arguments
> It's actually helped me around 5 fps

yeah, it might improve for you, but not for others.
i have a list if JVM arguments thats tested by a few users, some benefit from it, some gets worse instead, so theres no point in using it, and i also found out that it has huge instability.

**Comment by kiokori-git** [comment]
those JVM args are also made for PCs, not mobile phones!

**Comment by graperpie** [comment]
> those JVM args are also made for PCs, not mobile phones!

i just saw this reply in real time, this is graperpie

**Comment by ghost** [comment]
I have Nothing to say

**Comment by FranklinAzriel** [comment]
What do you expect lower boost clock in phone? 69420 fps?
the game itself need a higher clock speed around 3,5ghz

even aikar flags seems not useful for client
it only useful for backend side(server side)

if u want high fps
just buy pc
stop misleading ppl!

**Comment by EpicLays** [comment]
> I researched about it in https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks And https://cassiofernando.netlify.app/blog/minecraft-java-arguments It's actually helped me around 5 fps

I'm pretty sure 80% of JVM flags are disabled/blacklisted so it wouldn't work if you input it
one of the devs on discord says it

**Comment by ghost** [comment]
Really??
