### ISSUE TITLE
[BUG] <Jre was outdated, or an error? (REUPLOADED BY ME)>

### ISSUE THREAD

**Issue by AndreCodin24** [PojavLauncherTeam/PojavLauncher#5486]
### Describe the bug

Hi, second issue... I have downloaded a Jre file, and put it on PojavLauncher. After setting the default, the red text says "Incompatible architecture: aarch64". And "Application/Game exited with code -1, check latestlog.txt for more details." Is this an error code I just put in?

### The log file and images/videos

![ezgif-7-dc1a125460](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/54dbe35d-0b8f-4daa-ba9d-a2049c059ef2)
![Screenshot 2024-05-23 6 15 16 PM](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/e8b3fa06-ebc1-46bb-8d8b-3ea0ec0c03fb)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15412618/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Go to settings
3. Java Tweaks
4. Runtime Manager
5. Add new
6. Wait until it's done
7. Then put a new thing and run java
6. And get this error message
```

### Expected Behavior

I tried and use a 64 bit, but won't work.

### Platform

```markdown
- Device model: Google dedede
- CPU architecture: 
- Android version: 
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Can you please fix this issue?

**Comment by artdeell** [comment]
The Java runtime you specified is for aarch64. But your device is x86_64. You need java for x86_64.

**Comment by ghost** [comment]
If you don't know about your device machine download (device info hw) after download enter to it and go to SOC and 
![Screenshot_۲۰۲۴-۰۵-۲۳-۱۳-۵۱-۰۰-۱۶۸_ru andr7e deviceinfohw-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/0f48fa3d-b3ae-496d-87ca-3f75b8e80a9a)
In machine writes you which machine have and after you know download java version for support your machine for example: my machine is aarch64 and i need to download and install java version for aarch64

**Comment by AndreCodin24** [comment]
> If you don't know about your device machine download (device info hw) after download enter to it and go to SOC and ![Screenshot_۲۰۲۴-۰۵-۲۳-۱۳-۵۱-۰۰-۱۶۸_ru andr7e deviceinfohw-edit](https://private-user-images.githubusercontent.com/140465266/333145209-0f48fa3d-b3ae-496d-87ca-3f75b8e80a9a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMjU4NjMsIm5iZiI6MTcxNzAyNTU2MywicGF0aCI6Ii8xNDA0NjUyNjYvMzMzMTQ1MjA5LTBmNDhmYTNkLWIzYWUtNDk2ZC04N2NhLTNmNzViOGU4MGE5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQyMzMyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmU4NDdjNGM4ZGViZDFjYzU1MmQwNDBkYzUzZTQzZTA4ZjcwZjEwYThkOGMyZWRhYzQ4NmJmNDljZjI0MDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Q4Jk9qdgawcGOUNqEXC9NfU3cCvgcKrFhmCwt-djRg) In machine writes you which machine have and after you know download java version for support your machine for example: my machine is aarch64 and i need to download and install java version for aarch64

Thank you
