### ISSUE TITLE
[F-Req] <add a new render similar to zink but the shader does more work>

### ISSUE THREAD

**Issue by Nekongawi** [PojavLauncherTeam/PojavLauncher#5487]
### Is this request related to a bug?

no I just want there to be a render to use shaders that do more work

### Describe the request.

My request is to add a new render, similar to Zinc Tender, only with wider use of Java shaders, the problem is that many Java shaders have errors that don't work in Pojav, such as terrain errors.(Black world, white screen, transparent screen, only the sky can be seen I hope there is a better rendering from zinc because I also develop shaders in Pojav and my other friends also want the same thing Namely New Render. Better than zinc if you can give the new render smoothly later :D

### Anything else?

Added resolution change feature directly in the game without having to exit + and new render

**Comment by kiokori-git** [comment]
i wish making stuff like this was easy

**Comment by kiokori-git** [comment]
also, were open for PRs :D 👍
