### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by GAMERGENIX1** [PojavLauncherTeam/PojavLauncher#5489]
### Describe the bug

Replay mod is not working it get stuck when click on load in 1.20.4

### The log file and images/videos

[2024-05-24-2.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/15437055/2024-05-24-2.log.gz)

### Steps To Reproduce

```markdown
Start pojav 1.20.4 
Then record replay then click on load
```

### Expected Behavior

It get stuck after click on load joining world screen come and then it get stuck there

### Platform

```markdown
- Device model: CPH2179
- CPU architecture: octa core
- Android version: 10
- PojavLauncher version: latest GitHub
```

### Anything else?

How to fix it

**Comment by GAMERGENIX1** [comment]
Wrong log file 😔
[2024-05-24-1.log.gz](https://github.com/PojavLauncherTeam/PojavLauncher/files/15437099/2024-05-24-1.log.gz)
This one is correct

**Comment by GAMERGENIX1** [comment]
Help

**Comment by GaucovyAero** [comment]
unsupported
