### ISSUE TITLE
[BUG] <Unable to download the resource pack needed to install the server>

### ISSUE THREAD

**Issue by bdjjsss180219** [PojavLauncherTeam/PojavLauncher#5495]
### Describe the bug

I am here hypixel Server,A crash occurred while downloading the installation server resource package,Repeated attempts or crashes.

https://github.com/PojavLauncherTeam/PojavLauncher/assets/140313909/bd9e4d9e-60a9-42f0-bcae-bcd409947018

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/140313909/509a35ae-8d6f-4dd5-bbf9-0960e67b597d

### Steps To Reproduce

```markdown
1.Turn on the starter
2.Enter the 1.8.9version
3.Play multiplayer games
4.Enter the server
5.Supermarket downloads and installs resource packs
6.Exit with error code minus one
```

### Expected Behavior

You can download and install the recommended resource packages in the server normally

### Platform

```markdown
- Device model: VIVO y83
- CPU architecture: 64arm
- Android version: 8.1
- PojavLauncher version: edelweiss-20240330-dda7a4e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
gl4es couldnt convert the shaders used by that resource pack, you gotta use a different renderer, and if your phone doesnt support it, then you are out of luck, you gotta get a different phone
