### ISSUE TITLE
[BUG] ERROR CODE 1

### ISSUE THREAD

**Issue by TimRou4** [PojavLauncherTeam/PojavLauncher#5496]
### Describe the bug

Error 1 occurs when I try to log into Minecraft via forge (1.19.2) with a mod (this happens with every mod)

### The log file and images/videos

[latestlog-1.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15447160/latestlog-1.txt)
![IMG-20240526-WA0004](https://github.com/PojavLauncherTeam/PojavLauncher/assets/125994989/fcb5105e-dda8-4de5-a52b-5923f010a110)

### Steps To Reproduce

```markdown
1. Launch Pojava
 2. Download forge (1.19.2)
 3. Enter the game
 4. Catch a mistake
```

### Expected Behavior

Поиграть в Майнкрафт с модами

### Platform

```markdown
- Device model: POCO X5 PRO
- CPU architecture: Qualcomm SM7325 Snapdragon 778G 5G (6 nm)
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

This is a problem with the game files, not an account problem.  I tried logging in through a local account and through an official one.

**Comment by GaucovyAero** [comment]
the mod does not have correct permissions inside your files, try using a different file manager to move the mod there (e. g. the default android one - com.marc.files is a shortcut to it on play store)

**Comment by TimRou4** [comment]
The file manager that you wrote to me was used for dragging and dropping files, are there any other working programs for this?
