### ISSUE TITLE
How to fix "Can't find any compatible Java runtime. This version requires java 21 or newer"

### ISSUE THREAD

**Issue by neomiemo** [PojavLauncherTeam/PojavLauncher#5497]
### Describe the bug

When I try to play Minecraft java version 1.20.6 I get this error

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Try to play Minecraft 1.20.6
3. Error
```

### Expected Behavior

.

### Platform

```markdown
- Device model: poco x3 pro 8/256Gb
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d 0c-v3_openjdk
```

**Comment by ghost** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions?query=branch%3Abuildjre21

**Comment by ghost** [comment]
Very careful about this to download
![Screenshot_۲۰۲۴-۰۵-۲۶-۱۸-۲۵-۴۸-۶۲۳_ru andr7e deviceinfohw-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/109b1051-8bf1-42af-a88b-74bf4e907995)
