### ISSUE TITLE
Logout spam bug

### ISSUE THREAD

**Issue by TomXD1234** [PojavLauncherTeam/PojavLauncher#5498]
### Describe the bug

So when I open log and I saw spam files that effect to performance their any solution?

### The log file and images/videos

How to fix logout spam glitch

### Steps To Reproduce

```markdown
!
```

### Expected Behavior

!

### Platform

```markdown
- Device model: vivo y100a
- CPU architecture: 64Bit
- Android version: 14
- PojavLauncher version: latest
```

### Anything else?

How to fix logout spam bug

**Comment by GaucovyAero** [comment]
send log

**Comment by TomXD1234** [comment]
[Uploading latestlog.txt…]()

**Comment by TomXD1234** [comment]
> send log 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15454098/latestlog.txt)

**Comment by GaucovyAero** [comment]
remove sodium, sodium extra and all mods that need it
