### ISSUE TITLE
[BUG] You can't type letters in Chat / Naming a world / Naming a server / Adding a server / Others 

### ISSUE THREAD

**Issue by AlandTheGamer** [PojavLauncherTeam/PojavLauncher#550]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Use gboard.

**Comment by AlandTheGamer** [comment]
> Use gboard.

What is Gboard ?

**Comment by khanhduytran0** [comment]
Gboard is this https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin

**Comment by AlandTheGamer** [comment]
> Gboard is this https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin

Thank you but now I can't type .

**Comment by artdeell** [comment]
> > Gboard is this https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin
> 
> Thank you but now I can't type .

Type ":" key before every . that you type. Then remove the ":"s.

**Comment by AlandTheGamer** [comment]
> > > Gboard is this https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin
> > 
> > 
> > Thank you but now I can't type .
> 
> Type ":" key before every . that you type. Then remove the ":"s.
OMG THANK YOU SO MUCH I CAN FIANLLY PLAY ON YOUTUBERS SERVERS !

**Comment by artdeell** [comment]
Closing.
