### ISSUE TITLE
Completely no sound on version 1.5.2 [BUG]

### ISSUE THREAD

**Issue by sqx02a** [PojavLauncherTeam/PojavLauncher#5500]
### Describe the bug

When i play minecraft version 1.5.2, there is completely no sound

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15450697/latestlog.txt)

### Steps To Reproduce

```markdown
1.Download version 1.5.2
2.Launch it
3.No sound
```

### Expected Behavior

I expected presence of the sound, but there isn't any

### Platform

```markdown
- Device model: Samsung Galaxy a54
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20240521-3аеа338-
```

**Comment by GaucovyAero** [comment]
https://archive.org/details/CompleteMinecraftResourcesFolder2014

put this `resources` folder into your .minecraft and press F3+S to reload the sounds if needed
your .minecraft folder is in /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/
if you dont know how to get access to it, use com.marc.files from play store and use the 3 lines button (hamburger menu) to get into it

**Comment by sqx01** [comment]
I cannot download your file
