### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Rafi13575876** [PojavLauncherTeam/PojavLauncher#5501]
### Describe the bug

1. Please fix the Microsoft account bug. This bug is really not good for premium servers, please fix it :(
2. And add a skin to the Pojav launcher, please

### The log file and images/videos

![Screenshot_2024-05-27-21-06-00-10_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/170678217/a87bb16b-d863-4208-9d0f-98ee095bd01f)

### Steps To Reproduce

```markdown
1 Do not know
```

### Expected Behavior

1 Do not know

### Platform

```markdown
- Device model: realme 5i
- CPU architecture: Andro (TM) 610
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
log into minecraft.net first
