### ISSUE TITLE
[F-Req] add a portrait mode of playing

### ISSUE THREAD

**Issue by Zaffox** [PojavLauncherTeam/PojavLauncher#5503]
### Is this request related to a bug?

No, not related to a bug.

### Describe the request.

Add a portrait version of playing. Like a gameboy style. Controls on bottom with a resizable screen on the top.

**Comment by Vylesh** [comment]
Minecraft is can be playable only Landspace even on PC version... This tupe feature is Probably really empty feature for gameplay + Configuring keymap for portrait mode is really time killing proccess...

**Comment by ghost** [comment]
why would need to add portrait mode into pojavlauncher android

**Comment by Zaffox** [comment]
So you can have a screen without having the controls be in the way. And when your phone is charging the cord is not in the way. 

I used a orientation forcer and I am trying to edit Activity_basemain to use it like a Gameboy but I can't get it to work.

**Comment by OwenThePurpleCat** [comment]
![Screenshot_2024-05-28-13-01-00](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161511358/1c42ec95-c4e8-4167-bb62-912b5b35543a)
![Screenshot_2024-05-28-13-00-39](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161511358/cb328fd5-4bc8-453b-96b8-e7e851e498ce)
![Screenshot_2024-05-28-12-59-56](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161511358/ab1bb00e-1718-4c6d-9fe5-158dd42de446)
![Screenshot_2024-05-28-11-08-29](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161511358/6a8dc665-83be-48fc-8ba4-9e7d301bd017)

**Comment by Zaffox** [comment]
![Screenshot_2024-05-28-13-01-00](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161511358/ca174e37-b4db-4980-ad3f-7aea776e185d)
![Screenshot_2024-05-28-13-00-39](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161511358/e22cec55-e045-4bff-b7b8-52565bab4518)
![Screenshot_2024-05-28-12-59-56](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161511358/7537cef1-eb47-4a5a-b08a-eb3f94c7f7cf)

**Comment by ghost** [comment]
Playing minecraft with portrait mode would be a nightmare

**Comment by Zaffox** [comment]
Yah I don't know what I was thinking
