### ISSUE TITLE
[BUG] Microsoft account is not working

### ISSUE THREAD

**Issue by Princepro96** [PojavLauncherTeam/PojavLauncher#5504]
### Describe the bug

It's not working

### The log file and images/videos

Jwwj

### Steps To Reproduce

```markdown
Jwjsjjwjw
```

### Expected Behavior

Bwbhjw

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
Sjjwjwjw
```

### Anything else?

Sjjsj

**Comment by zkitefly** [comment]
Send logs and screenshots

**Comment by Vylesh** [comment]
Please Send A Video about Bug...

**Comment by GaucovyAero** [comment]
log into minecraft.net
