### ISSUE TITLE
The ability to turn off the controller mapping.

### ISSUE THREAD

**Issue by AdroitJackson** [PojavLauncherTeam/PojavLauncher#5505]
### Describe the request.

When connecting a controller it automatically brings up a button mapping screen pre mapping the controller but fabric mods like example controllable have the chance of picking up the controller allowing you to use it So I personally believe that the ability to turn on and off the controller mapping and using at will.

**Comment by GaucovyAero** [comment]
duplicate of #4486

**Comment by AdroitJackson** [comment]
> duplicate of #4486

Is there A way to disable it already then? I just read over that

**Comment by GaucovyAero** [comment]
nope, hence why that issue is not closed yet
