### ISSUE TITLE
Shift+W =F11 on keyboard?

### ISSUE THREAD

**Issue by tahiinpekmez** [PojavLauncherTeam/PojavLauncher#5506]
### Describe the bug

hi im user of pojavlauncher on Android. im playing minecraft with keyboard and mause. my favorite game bedwars on hypixel. but there is a problem. when im bridging or whatever anytime i press shift+w converts the game from full screen to windowed. and i always die because it distracts me. if there is something that can be fixed, how do i fix it? or if it is something that cannot be done manually in Android, please fix it in the next update. thanks dear pojavlauncher team

https://github.com/PojavLauncherTeam/PojavLauncher/assets/170959352/b8f1f201-15c6-46fa-8b4b-bb045e859e06

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/170959352/5fa79597-24d0-4316-b534-e802a4e6e9b9

### Steps To Reproduce

```markdown
1. Start the game
2. Join singleplayer or multiplayer
3. When you stop press Shift+W
```

### Expected Behavior

I want this situation not to happen. Shift+W

https://github.com/PojavLauncherTeam/PojavLauncher/assets/170959352/32223784-c9f3-4f88-8932-63bd19e74bf1

### Platform

```markdown
- Device model: Xiaomi Redmi Note 10S
- CPU architecture: 
- Android version: 13
- PojavLauncher version: Lastest
```

**Comment by ZackyTV2** [comment]
This has been a problem for years... To solve it, just change the F11 button in the game's control settings

**Comment by GaucovyAero** [comment]
Shift + W or just W is a hardcoded Android fullscreen shortcut and cannot be changed, thus you just have to rebind the fullscreen key to something else in controls
