### ISSUE TITLE
[BUG] <PojavLauncher MumbleLink Mod Crash 1.7.10>

### ISSUE THREAD

**Issue by justice6a** [PojavLauncherTeam/PojavLauncher#5507]
### Describe the bug

Simply when starting Forge 1.7.10, it crashes in the middle of loading mods.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/171114312/fad957e9-29c1-46c0-84b8-13f23b8980ed

Logfile: 
[latestlog1.7.10.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15478884/latestlog1.7.10.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Loading assests and mods
3. Boom, crash PojavLauncher
```

### Expected Behavior

It opened normally and worked.

### Platform

```markdown
- Device model: Positivo T810
- CPU architecture: 64-bit ARMv8-A (32-bit Mode)
- Android version: 11 (Red Velvet Cake)
- PojavLauncher version: Edelweiss
```

### Anything else?

pls help

**Comment by GaucovyAero** [comment]
```
java.lang.NullPointerException: Initializing game
	at zsawyer.mods.mumblelink.addons.pa.es.ExtendedPASupport.activate(ExtendedPASupport.java:139)
	at zsawyer.mods.mumblelink.addons.pa.es.ExtendedPASupport.load(ExtendedPASupport.java:128)
```
im assuming mumblelink tries to communicate with PulseAudio, we dont use that and will not, as implementing it is not that useful and it would very much complicate the pojav code
