### ISSUE TITLE
there is a crash whenever i open multiplayer

### ISSUE THREAD

**Issue by teddgarry2** [PojavLauncherTeam/PojavLauncher#5508]
### Describe the bug

just always crash note there is mods but it works perfectly on a another device

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15479726/latestlog.txt)
[hardman-09.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/15479772/hardman-09.zip)

### Steps To Reproduce

```markdown
use these mod pack  i listed
```

### Expected Behavior

it working

### Platform

```markdown
- Device model: redmi 9c tab
- CPU architecture: mediatek helio G99 octa-core max 2.2GHz,arm-64-v8a
- Android version: 12
- PojavLauncher version: "Edelweiss" Release
```

**Comment by GaucovyAero** [comment]
```
Caused by: java.lang.RuntimeException: Error creating fragment shader: mwc:shaders/select
	at com.paneedah.weaponlib.shader.jim.ShaderLoader.loadShader(ShaderLoader.java:70) ~[ShaderLoader.class:?]
	at com.paneedah.weaponlib.render.Shaders.<clinit>(Shaders.java:13) ~[Shaders.class:?]
	... 18 more
```
gl4es failed to convert the shaders in weaponlib, try using zink
if it doesnt work on your device, you gotta use a different device that has higher specs and does support zink
