### ISSUE TITLE
Crash when joining world

### ISSUE THREAD

**Issue by Lunar2091** [PojavLauncherTeam/PojavLauncher#5510]
### Describe the bug

So I am using a Microsoft acc for minecraft and when I join a world on the mod pack pojav launcher closes 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15488394/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.launch spxdd's horror pack
3. Go to play
4. Make a world
After making the world it crashes tried it 2 times
```

### Expected Behavior

To play the game

### Platform

```markdown
- Device model: galaxy s10
- CPU architecture: arm64
- Android version: android 9 
- PojavLauncher newest
```

**Comment by GaucovyAero** [comment]
patch rubidium
