### ISSUE TITLE
[BUG] <My game crashes, because of Chromebook update (Only Chromebook)>

### ISSUE THREAD

**Issue by AndreCodin24** [PojavLauncherTeam/PojavLauncher#5511]
### Describe the bug

So there's a new Chromebook update that adds some new features, and stuff. But PojavaLauncher, when I tried to play the game, it crashed. I already just cleared my data, but it kept on crashes.

### The log file and images/videos

[Screen recording 2024-05-30 12.01.51 PM.webm](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/3d15c2e5-fe24-41ee-9a06-1c81e24a42ed)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15491912/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open PojavaLauncher
2. Check a Launcher profile
3. Press Play button
4. An weird white screen crashes
```

### Expected Behavior

Weird white screen game crash.

### Platform

```markdown
- Device model: Google dedede
- CPU architecture: ???
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I once tried again, and the game kept crashing.

**Comment by AndreCodin24** [comment]
Can anyone fix this?

**Comment by AndreCodin24** [comment]
Oh yeah, that's why I can't play PojavLauncher? I'm not doing this...

**Comment by GaucovyAero** [comment]
try reinstalling, cant really help with this, LWJGL is not starting at all on your device

**Comment by AndreCodin24** [comment]
> try reinstalling, cant really help with this, LWJGL is not starting at all on your device

okay

**Comment by noohislegend** [comment]
play without optifine i also have chromebook and crash when i use optifine use sodium

**Comment by GaucovyAero** [comment]
open a new issue if this persists on the latest play store build

**Comment by BFDIFourBFB** [comment]
> play without optifine i also have chromebook and crash when i use optifine use sodium

this pretty much happened with me without optifine
