### ISSUE TITLE
Sodium for 1.20.5/1.20.6

### ISSUE THREAD

**Issue by GAMERGENIX1** [PojavLauncherTeam/PojavLauncher#5513]
### Is this request related to a bug?

No

### Describe the request.

Can you give me sodium patched version for 1.20.5 or for 1.20.6

### Anything else?

No plz give me

**Comment by ghost** [comment]
For veraion 1.20.6
https://modrinth.com/mod/sodium/version/mc1.20.6-0.5.8

**Comment by kasrarouhi** [comment]
![Screenshot_۲۰۲۴-۰۵-۳۰-۱۲-۵۵-۱۵-۱۹۹_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/24b669ef-0c9d-4a9e-8ffb-5f73bda46ad5)

**Comment by ghost** [comment]
Click in download
![Screenshot_۲۰۲۴-۰۵-۳۰-۱۲-۵۵-۱۵-۱۹۹_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/5ccfe593-fbd2-4cad-b03d-0fe17a197354)

**Comment by GAMERGENIX1** [comment]
> For veraion 1.20.6 https://modrinth.com/mod/sodium/version/mc1.20.6-0.5.8

I want patched for holy render

**Comment by ghost** [comment]
Sorry but sodium need opengl 4.6 or highter but holygl4es have opengl 2.1

**Comment by GAMERGENIX1** [comment]
> Sorry but sodium need opengl 4.6 or highter but holygl4es have opengl 2.1

Ya that's why I said patched version

**Comment by ghost** [comment]
Alright

**Comment by GaucovyAero** [comment]
https://github.com/TarikBR/sodium-fabric/tree/1.20.4/pojavFixing try patching the source code yourself with changes from here and recompile

also, patched sodium runs worse than if you set up optifine well
