### ISSUE TITLE
Avoir java 21 sur pojav launcher

### ISSUE THREAD

**Issue by Timmychat** [PojavLauncherTeam/PojavLauncher#5515]

**Comment by GaucovyAero** [comment]
Java 21 for android arm64 phones: 
https://nightly.link/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/8216398145/jre21-aarch64.zip
Java 21 for iOS phones:
https://nightly.link/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/8216398145/jre21-ios-aarch64.zip
after you download it, unzip the file. Open pojav, go to "settings >java tweaks >runtime manager >add new" and then select the java 21 tar.xz file
