### ISSUE TITLE
[BUG] Crash in 1.21-pre1+

### ISSUE THREAD

**Issue by KedisPL** [PojavLauncherTeam/PojavLauncher#5516]
### Describe the bug

When I want to run 1.21-pre1 the game crashes after a few seconds.

### The log file and images/videos

[crash-2024-05-30_19.35.59-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15503713/crash-2024-05-30_19.35.59-client.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch Minecraft 1.21-pre1
```

### Expected Behavior

The game should start, but crashes.

### Platform

```markdown
- Device model: Infinix Note 12 Pro 5G (X671B)
- CPU architecture: arm64 (I think)
- Android version: 13
- PojavLauncher version: Latest from actions
```

**Comment by KedisPL** [comment]
As far as I can see it's because, 1.21 uses lwjgl 3.3.3, and the launcher has 3.3.1.

**Comment by ghost** [comment]
Yes i have the same issue so need lwjgl 3.3.3 I don't know about this (needs fixing)

**Comment by ghost** [comment]
It's fixed. Thank you
