### ISSUE TITLE
I founded how to fix crash in better minecraft modpack

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5519]
### Is this request related to a bug?

No

### Describe the request.

By deleting 8 mods of 235 crash and freeze game fixed for me in better minecraft modpack

1:connectedness
2:entity texture feature
3:immediatelyfastreforged
4:modernfix
5:quark
6:reforgium
7:xearos world map
8:Simple Discord Rich Presence

Warning: optifine not supported for this modpack for example Twilight forest not compatible with optifine(real)
Is there mods unnecessary to use now

1:Rubidium
2: Rubidium extra
3:texture Rubidium options

### Anything else?

. . .

**Comment by Marshall2439** [comment]
Dude this is an issue tracker this is not for conversations i think

**Comment by Marshall2439** [comment]
All of mods worked for me tho I dont have better minecraft modpack but I have few mods from them

**Comment by ghost** [comment]
Yeah i know. but after deleting these mods my crash fixed let me test again

**Comment by ghost** [comment]
Chef's delight and bundle delight are supported. after using optifine these 2 mods crash  i edited my document. Thank you but other mods i tested or crash or show error message

**Comment by Marshall2439** [comment]
What version you are on?

**Comment by ghost** [comment]
1.18.2

**Comment by ghost** [comment]
show error like quark mod
![Screenshot_۲۰۲۴-۰۶-۰۱-۱۳-۱۳-۰۲-۰۵۰_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/f70c24cf-a35e-4212-b5ad-e080527a5dbd)

**Comment by Marshall2439** [comment]
I can run quark mod very well

**Comment by ghost** [comment]
Well i think quark mod not compatible with other mods in better mc

**Comment by lgsanai** [comment]
> Well i think quark mod not compatible with other mods in better mc

Bro I deleted all the mods you deleted but says game exist 0 bullshit is here do you know the solution

**Comment by ghost** [comment]
I think you installed optifine because optifine is not compatible with some mods. Try delete
1:bundledelight
2: chef's delight
3:oh the biomes you'll go
4: twilight forest
And try again if still exist with code 1 let me work on it again

**Comment by ghost** [comment]
> > Well i think quark mod not compatible with other mods in better mc
> 
> Bro I deleted all the mods you deleted but says game exist 0 bullshit is here do you know the solution

I see your new issue 
#5998

My information is for version 1.18.2 not 1.20.1
