### ISSUE TITLE
[BUG] <My Game Crashes>

### ISSUE THREAD

**Issue by AndreCodin24** [PojavLauncherTeam/PojavLauncher#5522]
### Describe the bug

I played Pojavlaucnher for the first time. But, when I tried to use a latest release, it crashes. Can you, or anyone fix this? 

### The log file and images/videos

[335836018-3fae943e-1932-41bc-bc61-f97fd871f07c.webm](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/3636f844-41f4-46b0-bba7-6cbbb29d92b6)
[latestlog.txt](https://github.com/user-attachments/files/15523941/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Pick an latest release, or snapshots
3. Wait until it's loaded
4. Crashes
```

### Expected Behavior

When I load up the PojavLauncher, it crashes, and some white screen appears.

### Platform

```markdown
- Device model: Google dedede
- CPU architecture: x86_64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I once try again but it kept crashes.

**Comment by Marshall2439** [comment]
🤦

**Comment by Marshall2439** [comment]
Newest version requires lwjgl 3.3.3 which is not available YET but there is workaround until it is released. Workaround is that download latest version from actions tab up there

**Comment by Marshall2439** [comment]
Or play older version

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۶-۰۲-۰۹-۲۹-۳۹-۱۹۳_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/c4eb5092-7063-41f9-bf54-812dc9b89a89)
We talking about this in GitHub actions in pojav

**Comment by AndreCodin24** [comment]
> ![Screenshot_۲۰۲۴-۰۶-۰۲-۰۹-۲۹-۳۹-۱۹۳_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/335843106-c4eb5092-7063-41f9-bf54-812dc9b89a89.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDExMjIsIm5iZiI6MTcxNzM0MDgyMiwicGF0aCI6Ii8xNDA0NjUyNjYvMzM1ODQzMTA2LWM0ZWI1MDkyLTcwNjMtNDFmOS1iZjU0LTgxMmRjOWI4OWE4OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNTA3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzBkM2NiYTljOGY2YTkzZWExZWM0MmM0ZmZjZjUyMzJkMTVlZjVlMWI0Y2EwZTQzMTc4Y2UyYTg2ZjRkY2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CV9nh0z1-68Ol66eAms5cVriPQIGHsc1rtctP3B44z0) We talking about this in GitHub actions in pojav



> ![Screenshot_۲۰۲۴-۰۶-۰۲-۰۹-۲۹-۳۹-۱۹۳_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/335843106-c4eb5092-7063-41f9-bf54-812dc9b89a89.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDExMjIsIm5iZiI6MTcxNzM0MDgyMiwicGF0aCI6Ii8xNDA0NjUyNjYvMzM1ODQzMTA2LWM0ZWI1MDkyLTcwNjMtNDFmOS1iZjU0LTgxMmRjOWI4OWE4OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxNTA3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzBkM2NiYTljOGY2YTkzZWExZWM0MmM0ZmZjZjUyMzJkMTVlZjVlMWI0Y2EwZTQzMTc4Y2UyYTg2ZjRkY2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CV9nh0z1-68Ol66eAms5cVriPQIGHsc1rtctP3B44z0) We talking about this in GitHub actions in pojav

Ok, I try it out..

**Comment by ghost** [comment]
You right you need java 21 to install wait a minute

**Comment by ghost** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions/runs/8805754633
It's java 21 link download jre file and compatible for your device

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۶-۰۲-۱۸-۵۵-۱۷-۱۱۵_ru andr7e deviceinfohw-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/89e19dd7-9138-4a7c-b781-ad3655d9207b)
Device info HW writes what is your machine and you can fing what java 21 do you want download
![Screenshot_۲۰۲۴-۰۶-۰۲-۱۸-۵۶-۲۳-۹۶۴_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/6bd02960-86d9-496a-a221-45b6468eac6a)
After download java 21.  extract here file in zarchiver app and go to pojav launcher → settings → java tweaks → manage run time → add java → choice extracted java and done

**Comment by AndreCodin24** [comment]
Sorry, I don't use mobile phone.. But, should I use jre21-x86_64? I've used Device Info HW, to see what is that thing is running.. 
![4](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/d289805c-27ce-474f-8d1e-82b2990991c0)
![3](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/649171da-c3a2-4017-9c5f-9a8f691b3736)
![2](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/f4292812-1c1a-4eb7-b2a3-6802d6ca16c2)
![1](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/040c68d1-a586-4941-9f3c-7a9b2ab91381)

**Comment by ghost** [comment]
Yes i tell you download device info to understand which version of java you need use. You need use jre21-x86_64. Don't use jdk file. Jdk have unnecessary features minecraft don't need them and slow down game

**Comment by AndreCodin24** [comment]
> Yes i tell you download device info to understand which version of java you need use. You need use jre21-x86_64. Don't use jdk file. Jdk have unnecessary features minecraft don't need them and slow down game

Ok, hopefully this works...

**Comment by AndreCodin24** [comment]
Hey! It works! So, should I loaded it now?
![Screenshot 2024-06-03 11 54 52 AM](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/259124fa-f96c-43dd-9075-2482bd325555)

**Comment by ghost** [comment]
Don't worry it's work for you
