### ISSUE TITLE
Hdudhdh[BUG] <Short description>

### ISSUE THREAD

**Issue by Khang2868** [PojavLauncherTeam/PojavLauncher#5524]
### Describe the bug

Jrid

### The log file and images/videos

Idkdkkd

### Steps To Reproduce

```markdown
Udu
```

### Expected Behavior

6ududu

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Jdjdj

**Comment by Cube5x59999** [comment]
@GaucovyAero I think this is a troll account
