### ISSUE TITLE
[BUG] Crashing on Android 14 device

### ISSUE THREAD

**Issue by Axyc15** [PojavLauncherTeam/PojavLauncher#5525]
### Describe the bug

Crashing when entering the world with an Android 14 device.( Minecraft Version:1.20.1, Fabric Loader 0.15.11)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15525015/latestlog.txt)
[crash-2024-06-02_18.41.13-client.txt](https://github.com/user-attachments/files/15525016/crash-2024-06-02_18.41.13-client.txt)
[latest.log](https://github.com/user-attachments/files/15525017/latest.log)

### Steps To Reproduce

```markdown
Enter the world with any renderer using an Android 14 device.
```

### Expected Behavior

Fix this bug.

### Platform

```markdown
- Device model: Xiaomi K60(POCO F5 Pro) 16/256G
- CPU architecture: Arm64
- Android version: 14
- PojavLauncher version: edelweiss-20240531-bdc7f33-v3_openjdk
net.kdt.pojavlaunch.debug
```

### Anything else?

When my device was Android 13 everything was fine.

**Comment by GaucovyAero** [comment]
use java 17 for 1.20.4 and lower

**Comment by Axyc15** [comment]
I've tried many times with different versions of Java17, but Minecraft won't start at all!
[latest.log](https://github.com/user-attachments/files/15688320/latest.log)
