### ISSUE TITLE
Denis

### ISSUE THREAD

**Issue by Denisboss09** [PojavLauncherTeam/PojavLauncher#5526]
### Describe the bug

Jenbsbs s nsisjsnsnnsjsbs jsmsn

### The log file and images/videos

Hsisjbsywjwvsusn

### Steps To Reproduce

```markdown
Jsjbsgzj whskwbgsjw W sjnwbehwj wjwjbwgejeksjue jkwjhsjsns wiksnsn
```

### Expected Behavior

Jsjjidi7euwisjvsbw d nshebsbusjsvs s jsnefaktsbevrjsn

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
Hdhhsujebuiwvysjbhskvyaiwb7s
```

### Anything else?

Hdjidududhxvjcgchxgkxgkzyks udiff

**Comment by Denisboss09** [comment]
Gxohxhfcjhfjgdyhfigsidd9y

**Comment by Denisboss09** [comment]
Yddyycuf7rf77 7f7ff

**Comment by Marshall2439** [comment]
WHAT the actual fuck is going on here

**Comment by Cube5x59999** [comment]
@GaucovyAero  we got some trolling here
