### ISSUE TITLE
[BUG] Zink not compatible with vulkan 1.3.219

### ISSUE THREAD

**Issue by NykolasSilva** [PojavLauncherTeam/PojavLauncher#5527]
### Describe the bug

When i start the game with Zink, the game Just stay in a red screen, and the game Is running in background because of the music, the angle render doesn't Works too.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15526430/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install optfine I6 1.20.1
2. Select Zink render
3. Start the launcher
4. The game Will show the red screen
```

### Expected Behavior

I expect my game was running Just normal way without any problems

### Platform

```markdown
- Device model: Galaxy A15 5G
- CPU architecture: Dimensity 6100 2x ARM Cortex-A76 @ 2,20 GHz 6x ARM Cortex-A55 @ 2,00 GHz
- Android version: 14 One ui 6.0
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Bel69420** [comment]
1. Your GPU driver is fried(bad) and you cannot run zink
2. zink depends on GPU driver to run normally on some GPUs.

**Comment by Bel69420** [comment]
Basically, you're screwed. We cannot fix this because we are not developer of zink renderer.

**Comment by NykolasSilva** [comment]
But I saw other videos on YouTube where a helio g99 was already running with shaders and zink no problems. 
so my service is a "trash" to run the pojavlauncher?

**Comment by NykolasSilva** [comment]
Device*

**Comment by Bel69420** [comment]
Well, because that YouTuber has Vulkan 1.1 with old driver that can run zink

**Comment by Bel69420** [comment]
Your oem just putting a broken GPU Driver which mean it's really buggy

**Comment by NykolasSilva** [comment]
Is there any way to go back to the old driver?

**Comment by Bel69420** [comment]
At the moment, i don't think installing custom os with old android version will make your driver to 32.1.0

**Comment by Bel69420** [comment]
You can try but risking your phone for getting bricked

**Comment by GaucovyAero** [comment]
zink sometimes works and sometimes doesnt on the same gpus depending on the driver version or maybe also manufacturer
