### ISSUE TITLE
[BUG] Crash because of Create mod

### ISSUE THREAD

**Issue by RealitySplitter95** [PojavLauncherTeam/PojavLauncher#5528]
### Describe the bug

I downloaded it and start the game. After that, there's a loading screen for the mod to process but, after a while it crashed. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15530268/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download Create
2. Open pojavlauncher
3. Start
```

### Expected Behavior

I expect to run successfully

### Platform

```markdown
- Device model: Huawei nova 3i
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
```
java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83949_(RenderTarget.java:228) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?] {re:computing_frames,xf:OptiFine:default,re:classloading,xf:OptiFine:default}
```
since you don't have a snapdragon, your GPU does not support running create on gl4es, use zink if your device supports it

**Comment by GaucovyAero** [comment]
maybe you could also use virgl on a fork of pojav called SolCraftLauncher

**Comment by Marshall2439** [comment]
You can also use ANGLE renderer
