### ISSUE TITLE
[BUG] <Short description>uh it doesn't read jars idk why

### ISSUE THREAD

**Issue by Xeltro** [PojavLauncherTeam/PojavLauncher#5529]
### Describe the bug

Idk why I'm just trying to play Pixelmon 

### The log file and images/videos

Uploading screen-20240604-025846.mp4…

### Steps To Reproduce

```markdown
Normal loading but it doesn't read it has jars
```

### Expected Behavior

...

### Platform

```markdown
- Device model: realme c21y
- CPU architecture: 
- Android version: lastest I think 
- PojavLauncher version:
```

### Anything else?

...

**Comment by Xeltro** [comment]
![Uploading Screenshot_20240604-031204.png…]()

**Comment by GaucovyAero** [comment]
send log

**Comment by Xeltro** [comment]
Thank you but it's fix when I reinstalled ty
