### ISSUE TITLE
https://github.com/TarikBR/sodium-fabric/tree/1.20.4/pojavFixing try patching the source code yourself with changes from here and recompile

### ISSUE THREAD

**Issue by GAMERGENIX1** [PojavLauncherTeam/PojavLauncher#5532]
https://github.com/TarikBR/sodium-fabric/tree/1.20.4/pojavFixing try patching the source code yourself with changes from here and recompile

also, patched sodium runs worse than if you set up optifine well

_Originally posted by @GaucovyAero in https://github.com/PojavLauncherTeam/PojavLauncher/issues/5513#issuecomment-2145764840_

**Comment by GAMERGENIX1** [comment]
Is there any way to run replay mod with optifene in latest version

**Comment by ghost** [comment]
No. Replay mod not compatible with optifabric

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۶-۰۵-۰۱-۲۴-۱۵-۱۷۸_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/9b4efa58-d119-46f0-908c-5ab9221393a4)
