### ISSUE TITLE
[MOUSE NOT WORKING] Mouse wont lock into game.

### ISSUE THREAD

**Issue by birdboi123** [PojavLauncherTeam/PojavLauncher#5533]
### Describe the bug

I have to hold the trackpad to move the camera around. I am using amazons physical keyboard for the amazon fire max 11

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/70000883/33fcd6ae-820a-41bd-9307-1f74dc2d9beb

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Join a world or server
3. Try to move the camera with the keyboards trackpad
```

### Expected Behavior

i expected to be able to move the camera around normally

### Platform

```markdown
- Device model: Amazon Fire Max 11 (2023)
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
should be fixed in the latest play store update
