### ISSUE TITLE
Game exits with code: 1

### ISSUE THREAD

**Issue by Seif-Fares** [PojavLauncherTeam/PojavLauncher#5534]
### Describe the bug

Every time I play Minecraft forge 1.7.10 it shows code 1

### The log file and images/videos

Here's the log file
[latestlog.txt](https://github.com/user-attachments/files/15585086/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Launch Minecraft
3. Instantly get error code 1
```

### Expected Behavior

Expected behavior: Minecraft starts

### Platform

```markdown
- Device model: Realme 10 pro+ 5G
- CPU architecture: arm64-v8a
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I have these mods installed:
1-Optifine
2-Fisks superhero mod
With java runtime 17.0.9
With renderer Holy GL4ES

**Comment by TarikBR** [comment]
use java 8
