### ISSUE TITLE
Add virglrender again with vulkan and fix virglrender's bug

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5537]
### Is this request related to a bug?

Can you fix the bug which make the screen in virgl render and the error texture  in this render and at it with zink in the next update plss cuz my don't support vulkan zink so I use virgl

**Comment by GaucovyAero** [comment]
pojav devs dont develop virgl, and since it was buggy it was removed

use the solcraftlauncher fork if you want virgl
https://github.com/SolDev69/SolCraftLauncher

**Comment by Hoanpojavlauncher** [comment]
> pojav devs dont develop virgl, and since it was buggy it was removed
> 
> use the solcraftlauncher fork if you want virgl https://github.com/SolDev69/SolCraftLauncher

But I require microsoft account 😞
