### ISSUE TITLE
[BUG] Cannot control with bluetooth keyboard

### ISSUE THREAD

**Issue by xszqxszq** [PojavLauncherTeam/PojavLauncher#554]
Cannot control or type any text with bluetooth keyboard in game, though it works fine in previous versions. Currently using the latest build in Actions.
PS: My bluetooth keyboard is fine, since I'm filling this issue form with it.

**Comment by artdeell** [comment]
do you have acess to logcat?

**Comment by artdeell** [comment]
> Cannot control or type any text with bluetooth keyboard in game, though it works fine in previous versions. Currently using the latest build in Actions.
> PS: My bluetooth keyboard is fine, since I'm filling this issue form with it.

Can you type into input boxes from it?

**Comment by artdeell** [comment]
I disabled enhanced software input for hardware keyboards, try it now

**Comment by xszqxszq** [comment]
> > Cannot control or type any text with bluetooth keyboard in game, though it works fine in previous versions. Currently using the latest build in Actions.
> > PS: My bluetooth keyboard is fine, since I'm filling this issue form with it.
> 
> Can you type into input boxes from it?

No. Only the virtual keyboard works.

By the way Unicode characters input from virtual keyboard works, but only one character appeared when I typed multiple characters. This is especially incovenient for Chinese input. Besides, it crashed when I pressed backspace button on screen. Here is the latestcrash.txt:
```
PojavLauncher crash report
 - Time: 2020年12月31日 下午7:52:30
 - Device: TAS-AL00 TAS-AL00
 - Android version: 10
 - Crash stack trace:
java.lang.IndexOutOfBoundsException: replace (0 ... -1) has end before start
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1326)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:513)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:37)
	at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:250)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:450)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by xszqxszq** [comment]
> I disabled enhanced software input for hardware keyboards, try it now

Still not working

**Comment by artdeell** [comment]
So, do you have access to the logcat?

**Comment by xszqxszq** [comment]
> So, do you have access to the logcat?

I have a termux and maybe I can use the logcat command

**Comment by xszqxszq** [comment]
> So, do you have access to the logcat?

Uh it seems that I do not have root access on my phone and I currently cannot use a computer

**Comment by artdeell** [comment]
is your board a QWERTY board?
Also, you should have English layout enabled to play the game in enhanced mode

**Comment by xszqxszq** [comment]
> is your board a QWERTY board?
> Also, you should have English layout enabled to play the game in enhanced mode

Of course a QWERTY keyboard. I'm not quite understand that where is the enhanced mode to setup that layout? In my phone's settings or in the launcher or in game?

**Comment by artdeell** [comment]
Enhanced mode is a new input system that made Unicode work in launcher, but I think it's causing issues for for hardware keyboars (can't test because i have no Bluetooth boards nor OTG cables)

**Comment by xszqxszq** [comment]
> Enhanced mode is a new input system that made Unicode work in launcher, but I think it's causing issues for for hardware keyboars (can't test because i have no Bluetooth boards nor OTG cables)

After I set my keyboard layout to English in my phone's settings, it still didn't work, so probably that is not the problem

**Comment by xszqxszq** [comment]
> Enhanced mode is a new input system that made Unicode work in launcher, but I think it's causing issues for for hardware keyboars (can't test because i have no Bluetooth boards nor OTG cables)

Maybe consider test on emulators?

**Comment by artdeell** [comment]
> > Enhanced mode is a new input system that made Unicode work in launcher, but I think it's causing issues for for hardware keyboars (can't test because i have no Bluetooth boards nor OTG cables)
> 
> Maybe consider test on emulators?

Try the new latest build, i reimplemented the pipe as Android suggests.

**Comment by xszqxszq** [comment]
> > > Enhanced mode is a new input system that made Unicode work in launcher, but I think it's causing issues for for hardware keyboars (can't test because i have no Bluetooth boards nor OTG cables)
> > 
> > 
> > Maybe consider test on emulators?
> 
> Try the new latest build, i reimplemented the pipe as Android suggests.

Still cannot type or send control key from bluetooth keyboard, and in this build Unicode characters input seem to be disabled

**Comment by artdeell** [comment]
I'll try to do something after I get a real keyboard, because AVD is very slow for me. Please use the previous builds before this would be fixed.

**Comment by artdeell** [comment]
Found our family Bluetooth board, traced the issue. The bug is now (perhaps) fixed. Please update to the latest build and close the issue if it works.

**Comment by xszqxszq** [comment]
> Found our family Bluetooth board, traced the issue. The bug is now (perhaps) fixed. Please update to the latest build and close the issue if it works.

[This build](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/454761066) works, but the [latest build](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/459454346) fails

**Comment by xszqxszq** [comment]
One weird thing is that my keyboard can only type latin characters and still cannot control game(escape, slash, WASD and other keys do not work) in [this build](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/454761066)

**Comment by artdeell** [comment]
Try the latest

**Comment by xszqxszq** [comment]
> Try the latest

Solved
