### ISSUE TITLE
Minecraft GRAFİK KULLANICI ARAYÜZÜ ELEMANLARI KAYBOLMUŞ DURUMDA

### ISSUE THREAD

**Issue by Halitacar47** [PojavLauncherTeam/PojavLauncher#5541]
### Describe the bug

Ekranda ne envanter ne can ne yemek barı hiçbişey gözükmüyor ortada imleç yok chat a basıyorum açılmıyor debug a basıyorum açılmıyor Tab a basıyorum hiçbişekilde açılmıyor uygulama ismi:pojav launcher

### The log file and images/videos

![IMG-20240604-WA0002(1)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172036008/a85d8410-79c0-4751-a4a0-e725e071eba3)

### Steps To Reproduce

```markdown
1.pojav launcheri başlattım
2.tek oyunculu dünya oluşturdum
3.ortada ne imleç ne envanter ne yemek barı hiçbişey gözükmüyordu ama kolum gözüküyordu 
4.F1 denedim olmadı
```

### Expected Behavior

Envanter gözükmüyor tüm dosyalarımı sildigim halde çalışmadı

### Platform

```markdown
- Device model: Lenovo tab M10 fhd plus
- CPU architecture: bilinmiyor
- Android version: 10
- PojavLauncher version: bilinmiyor son sürüm
```

**Comment by GaucovyAero** [comment]
the issue is that your tablet has the PowerVR GE8320 graphics chip, in order to workaround this, install optifine, go into the shaders tab and turn on antialiasing to 2x fxaa
