### ISSUE TITLE
[BUG] <HOW CAN I FIX THIS CRASH?!?!?!?>

### ISSUE THREAD

**Issue by AndreCodin24** [PojavLauncherTeam/PojavLauncher#5543]
### Describe the bug

I just already got Java 21, cleared my data, uninstalled it, INSTALLED IT, and lowered my MB to 250. When I load it in, it still crashes. I also wanna play Pojavlauncher so badly, because it keeps on crashing. Please, fix this.

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/165141019/cc9f2332-1d05-4919-ac91-5815bf255200)
[latestlog.txt](https://github.com/user-attachments/files/15747156/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Create new profile
3. Use the latest Optifine
4. Use render Holy GL4ES
5. Use Java runtime jre21
6. Click Play
7. Boom. Crashes.
```

### Expected Behavior

I tried using x84_64 bits, and using Java runtime Jre21. But now it crashed. I don't use my Phone, cuz I'm using Chromebook.

### Platform

```markdown
- Device model: Google Intel Jasper Lake Chromebook
- CPU architecture: x86_64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

IDK, it still crashes on my Chromebook.

**Comment by AndreCodin24** [comment]
Sorry about yelling. I still don't know how to fix the crash. I watch some How To Fix Crash On PojavLauncher videos, but it's not working.

**Comment by GaucovyAero** [comment]
dude you literally have an open issue right now, closing this as a duplicate, try reinstalling pojav

**Comment by AndreCodin24** [comment]
> dude you literally have an open issue right now, closing this as a duplicate, try reinstalling pojav

should I have to restart?
