### ISSUE TITLE
[ BUG ] Screen frozen when clicking 

### ISSUE THREAD

**Issue by Kyuurlo** [PojavLauncherTeam/PojavLauncher#5545]
### Describe the bug

Basically, when I move my screen by clicking it freezes almost completely. This occurs only in newer versions of PojavLauncher.
I have already tried the version available in PlayStore and even with other launchers for Mobile (FoldCraft, BattlyLauncher, etc.. ) And everything works perfect.

This ONLY HAPPENS in newer versions released on GitHub.

It should be noted that I play with an OTG adapter connected to my device, however the same thing also happens when I play with touch controls, so I rule out the possibility that the The problem is due to the OTG adapter.

Leave two videos recorded, one internally from the same device and the other from outside so they can see what I'm talking about, he also highlighted that it is not a lag or FPS problem. At no time did my FPS drop, I was always above 200+ stable, even while the screen was lag I could see how the FPS number varied.

I am a player who normally enjoys PvP and this makes it impossible for me to play what I like, I hope you can help me.

### The log file and images/videos

Internal video
https://github.com/PojavLauncherTeam/PojavLauncher/assets/168349822/91527b8b-5b93-45c7-bd18-b50210c7637c

External video
https://github.com/PojavLauncherTeam/PojavLauncher/assets/168349822/87bcfa9a-07c4-43fb-9a95-0c18c1815dce

( There are no " lastetlog.txt " files basically because there are no crash errors or anything like that, the problem is purely visual within the game. )

Anyway, in case you're really interested, here it is: 
[latestlog.txt](https://github.com/user-attachments/files/15749606/latestlog.txt)

### Steps To Reproduce

```markdown
Simply open the pojav and start playing.

Any version, any world, any server, it always passes.
If I move the camera and click it just freezes, always
```

### Expected Behavior

Being able to move my camera while clicking without it freezing

### Platform

```markdown
- Device model: POCO X6 PRO 5G 12/512G
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20240531-bdc7 f33-v3_openjdk
```

### Anything else?

I didn't have this problem before, at first I felt that it starts after updating the Hyper OS version of my device, and maybe it could be a reason.

However in other versions of the app and even other Minecraft Java launchers on Android I don't have that problem, so it's definitely something in recent GitHub versions.

**Comment by GaucovyAero** [comment]
this is a known issue and yours is a duplicate but i want you to tell me exact versions of pojav where the issue happens and where it doesnt happen for you

**Comment by Kyuurlo** [comment]
> this is a known issue and yours is a duplicate but i want you to tell me exact versions of pojav where the issue happens and where it doesnt happen for you






It happens to me in the last three most recent versions published on GitHub, I don't know if the same thing still happens in previous versions.

https://github.com/PojavLauncherTeam/PojavLauncher/actions/workflows/android.yml

**Comment by Kyuurlo** [comment]
> this is a known issue and yours is a duplicate but i want you to tell me exact versions of pojav where the issue happens and where it doesnt happen for you

It doesn't happen to me in the version available from PlayStore for example, and in older versions (months ago) 
I don't know the exact version where the problem appears

**Comment by Kyuurlo** [comment]
> this is a known issue and yours is a duplicate but i want you to tell me exact versions of pojav where the issue happens and where it doesnt happen for you

Do you have any idea how to solve the problem?

**Comment by GaucovyAero** [comment]
> > this is a known issue and yours is a duplicate but i want you to tell me exact versions of pojav where the issue happens and where it doesnt happen for you
> 
> It doesn't happen to me in the version available from PlayStore for example, and in older versions (months ago) I don't know the exact version where the problem appears

thats so weird lol, please repost this comment along with your device model, maybe videos into issue #5099 
closing this as a duplicate
