### ISSUE TITLE
[F-Req] The cog icon is covered by Xiaomi's stupid multitasking icon and thus cannot be clicked 

### ISSUE THREAD

**Issue by Panjaksli** [PojavLauncherTeam/PojavLauncher#5547]
### Is this request related to a bug?

Move it from the center please ?  When I click anywhere near the 3 dots it opens multitasking dialogue so I can't click under the 3 dots at all. And I can't change control layout because of it.
![IMG_20240609_000418](https://github.com/PojavLauncherTeam/PojavLauncher/assets/82727531/d945f362-84a2-446f-b871-4d080c33d836)

**Comment by TarikBR** [comment]
You can create a button with SPECIAL_MENU, before entering on game

![Screenshot_2024-06-08-19-57-55-972_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/64391349/75e4985d-1f75-4f41-9cb8-6b9f68548dc0)
