### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5548]
### Describe the bug

When I start the game it's normal until the screen in the main menu is black and the music shows up but it's still black. I think it's a bug. Then I click randomly and I get in my world but its still black and I add mods in to pojav

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15749907/latestlog.txt)

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I expect it was normal but noooooo

### Platform

```markdown
- Device model:Oppo Reno 3 8/128g 
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: lastest version on google play
```

**Comment by TarikBR** [comment]
What mods are you using, and have you tried another renderer?

**Comment by GaucovyAero** [comment]
is this happening only on this modpack? did it work before? are you using alternate surface rendering?

**Comment by Hoanpojavlauncher** [comment]
> is this happening only on this modpack? did it work before? are you using alternate surface rendering? 

First no its a mod for pojavlaucher on yt like parasite for pojav 
Second no 
Third I use holy render  and also pojav nó zink cuz when I use it crash Immediately

**Comment by GaucovyAero** [comment]
ok and does this happen on vanilla?

**Comment by Hoanpojavlauncher** [comment]
> ok and does this happen on vanilla?

No 
sir

**Comment by GaucovyAero** [comment]
then i suppose its an issue with your mod setup, try removing half of the mods, then see which half has the issue and then remove half of those which dont work and see which mod is broken

**Comment by Hoanpojavlauncher** [comment]
> thì tôi cho rằng đó là vấn đề với thiết lập mod của bạn, hãy thử xóa một nửa số mod, sau đó xem nửa nào có vấn đề và sau đó loại bỏ một nửa số mod không hoạt động và xem mod nào bị hỏng

Ok I'll try

**Comment by Hoanpojavlauncher** [comment]
> then i suppose its an issue with your mod setup, try removing half of the mods, then see which half has the issue and then remove half of those which dont work and see which mod is broken

I forgot to mention that the file I put into the game includes a config section, do I need to delete it? I just delete the mod's config, not the game's.

**Comment by GaucovyAero** [comment]
> > then i suppose its an issue with your mod setup, try removing half of the mods, then see which half has the issue and then remove half of those which dont work and see which mod is broken
> 
> I forgot to mention that the file I put into the game includes a config section, do I need to delete it? I just delete the mod's config, not the game's.

you dont have to remove any configs

**Comment by ghost** [comment]
I don't know very much about black screen bug but try change java version if you using java 17.0.11 change to 21.0.1

**Comment by GaucovyAero** [comment]
uh hes on java 8 cause its forge 1.12.2, that certainly wont even launch

**Comment by GaucovyAero** [comment]
also im thinkin maybe the youtuber is using a different renderer than you? try using zink, but beware that your device might not support it

**Comment by Hoanpojavlauncher** [comment]
> also im thinkin maybe the youtuber is using a different renderer than you? try using zink, but beware that your device might not support it

When I use zink it crash but nvm I Found it the error(just my phpne)It is back tools and its add-on mod ichunutil

**Comment by Hoanpojavlauncher** [comment]
> > also im thinkin maybe the youtuber is using a different renderer than you? try using zink, but beware that your device might not support it
> 
> When I use zink it crash but nvm I Found it the error(just my phpne)It is back tools and its add-on mod ichunutil 

Or just the ichunutil mod

**Comment by GaucovyAero** [comment]
so you fixed it?

**Comment by Hoanpojavlauncher** [comment]
> so you fixed it?

Yesv Just delete ichunutil

**Comment by GaucovyAero** [comment]
ok nice

**Comment by ghost** [comment]
Strange

**Comment by Oshnik5** [comment]
I also have same issue which is not in my four year old phone but in my two year phone(I didn't installed ichuntil mod)
Modpacks tested
Chemical exchange 
Fees the Factory
No options.txt file change
Opengl renderer (zink crashed my game )
