### ISSUE TITLE
Sodium crash

### ISSUE THREAD

**Issue by Hanu9098** [PojavLauncherTeam/PojavLauncher#5550]
### Describe the bug

Whenever i install sodium , and load a world , it saves the world.

### The log file and images/videos

Latest log. - 
[latestlog.txt](https://github.com/user-attachments/files/15751477/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Install sodium
3. Play
4. Start a world
5. game will crash.
```

### Expected Behavior

I expect the world to load.

### Platform

```markdown
- Device model: realme pad 4/64 gb
- CPU architecture: arm 64
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by frdude** [comment]
Sodium is not supported in pojav. There is a patch you can do to make it work, but it is much slower than optifine/optifabric (from my testing) if you use the correct settings.

**Comment by GaucovyAero** [comment]
there is currently no patch for sodium 1.20.5, if you want to do it yourself, you have to change the source code
here is the repository with the 1.20.4 sodium 0.5.x patch https://github.com/TarikBR/sodium-fabric/tree/1.20.4/pojavFixing
optifine is faster than patched sodium
