### ISSUE TITLE
How to put datapacks before the world is generated?

### ISSUE THREAD

**Issue by Muggle2077** [PojavLauncherTeam/PojavLauncher#5551]
### Is this request related to a bug?

No.

### Describe the request.

Launch the game and click on those buttons:
"Singleplayer" -> "Create New World" -> "More" -> "Data Packs" -> "Open Pack Folder"
And you will see a temporary folder is created.
if on Windows, the path of the folder will be like:
`C:\Users\<UserName>\AppData\Local\Temp\mcworld-8983710657627869423`
but on Android, the path looks like:
`/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files//data/user/0/net.kdt.pojavlaunch.debug/cache/mcworld-8983710657627869423`
You will see 2 forward slashes between "files" and "data".
So where is the folder? How can I move my data pack into it?

### Anything else?

No.

**Comment by 5ghzx** [comment]
Isn't the windows datapack folder in .minecraft?

**Comment by 5ghzx** [comment]
lemme test that

**Comment by 5ghzx** [comment]
Oh it is

**Comment by 5ghzx** [comment]
What happens if you try going to that folder ignoring the double slash?

**Comment by Muggle2077** [comment]
> What happens if you try going to that folder ignoring the double slash?

It told me the path can't be found.

After I clicked on "Open Pack Folder", the "Files" application of Android opened the folder so I can see the path, but after I left the folder without a name (there should be a folder name between 2 slashes), I can't find it anymore.

**Comment by GaucovyAero** [comment]
the two slashes are not what you think they are, the actual directory is `/data/user/0/net.kdt.pojavlaunch.debug/cache/` which is located in **root** (meaning its not located anywhere in `/storage/emulated/0/`) and is not a directory users can access on android by default
the fact that the directory is accessible on windows and not on android is just part of the "secure" design of android

**Comment by Muggle2077** [comment]
> the directory is accessible on windows and not on android is just part of the "secure" design of android

So, how to put datapacks before the world is generated? Or, there is no way?

**Comment by 5ghzx** [comment]
root your device

**Comment by 5ghzx** [comment]
try magisk

**Comment by GaucovyAero** [comment]
> try magisk

1. you have to make sure your device is supported (that you can unlock the bootloader, e.g. on new Asus phones, Huawei, Honor, Samsung USA models, Vivo, etc. you cannot)
2. beware that you might brick your device completely so that its unusable
3. even if you succeed all your data gets wiped when you install magisk

**Comment by 5ghzx** [comment]
Might be overkill for such a tiny task ya i agree. Still, it is the only way

**Comment by alexytomi** [comment]
> > the directory is accessible on windows and not on android is just part of the "secure" design of android
> 
> So, how to put datapacks before the world is generated? Or, there is no way?

Here's a way.


https://github.com/PojavLauncherTeam/PojavLauncher/assets/60690056/35091206-355b-4aa2-a4ca-7bdac67492ff
