### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Dhiaaldeen0780** [PojavLauncherTeam/PojavLauncher#5553]
### Describe the bug

لماذا لايمكنني تسجيل دخول حساب xbox في pojavluncher

### The log file and images/videos

لماذا لايمكنني تسجيل دخول حساب xbox في pojavluncher

### Steps To Reproduce

```markdown
لماذا لايمكنني تسجيل دخول حساب xbox في pojavluncher
```

### Expected Behavior

لماذا لايمكنني تسجيل دخول حساب xbox في pojavluncher

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

لماذا لايمكنني تسجيل دخول حساب xbox في pojavluncher

**Comment by AndreCodin24** [comment]
Try connecting to Minecraft.net. If it still works...

**Comment by GaucovyAero** [comment]
yeah microsoft has server outages right now, just try again
