### ISSUE TITLE
Find mod

### ISSUE THREAD

**Issue by NDG312** [PojavLauncherTeam/PojavLauncher#5554]
Are there any minimap mods compatible with vulkan pojavlauncher 1.20.1?

**Comment by kiokori-git** [comment]
vulkanmod isn't supported on pojavlauncher.

**Comment by NDG312** [comment]
I have a vulkan 1.20.1 that supports pojavlauncher.

**Comment by kiokori-git** [comment]
no support will be provided, vulkanmod is not supported on pojavlauncher and never will be.

**Comment by NDG312** [comment]
bro you can search on youtube to see the results.

**Comment by kiokori-git** [comment]
> bro you can search on youtube to see the results.

youtube is a place that has very poor source, alot of them are clickbaits.
even if they're real, no support will be provided and any damages caused on your device, we are not responsible for it.

**Comment by Marshall2439** [comment]
There is vulkanmod patch that is supported i think

**Comment by alexytomi** [comment]
> There is vulkanmod patch that is supported i think

There are no supported vulkanmod patches or ports for Android or iOS

What you found is entirely unofficial and is not supported by either us nor the official vulkanmod devs. Use them at your own risk.

**Comment by Marshall2439** [comment]
Just as i said that's what I THINK I'm not sure about it existing
