### ISSUE TITLE
Shader without zink??

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5556]
### Is this request related to a bug?

I am a fan of shader but my device don't support zink so I want to add a feature that run zink on low device

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/folder/cp87zpb3ichj7/Open4ES

open4es works on snapdragon devices on mc 1.8 up to 1.16.5, you can get updated 1.17+ versions that might work on other devices too on the open4es github page

though if it doesnt work, it wont work on your device and you likely need a snapdragon
