### ISSUE TITLE
[BUG] forge error codigo 17

### ISSUE THREAD

**Issue by ITsKhote** [PojavLauncherTeam/PojavLauncher#5558]
### Describe the bug

MC version 1.19.4 
Sanitize: false
Format: TSRG
Skip:false
![Screenshot_20240610-093742](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172284988/f598efa0-1ae4-491b-8044-9ecb4b68c052)

cuando estoy instalando forge el juego me expulsa 

### The log file and images/videos

![codigo17](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172284988/f68d13eb-83a6-4c11-864d-32e3460b0fd4)

### Steps To Reproduce

```markdown
no tengo un grabador de video perdon
```

### Expected Behavior

quiero instalar forge porfa llevo horas intentandolo y no puedo

### Platform

```markdown
- Device model: Moto Z3 Play
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: edelweiss20230928-9484d0c-v3_openjdk
```

### Anything else?

Solo eso ayudenme porfavor

**Comment by GaucovyAero** [comment]
try using java 17 to use the installer

**Comment by ITsKhote** [comment]
> try using java 17 to use the installer

Ty :D

**Comment by GaucovyAero** [comment]
it worked?

**Comment by ITsKhote** [comment]
> it worked?

yes
