### ISSUE TITLE
White screen and enhanced features

### ISSUE THREAD

**Issue by WangWenBin2017** [PojavLauncherTeam/PojavLauncher#556]
Device model and software version number:
Device: vivo V1824A (Android 9,SM8150,aarch64)

Problems encountered:

The latest pre-release version (https://github.com/PojavLauncherTeam/PojavLauncher/releases/tag/untagged-a59287e89e1347dc2890) does not start normally on any Minecraft version on my device.  But I reverted to the previous pre-release version (v3.3 testing 1 pre-release), and it works. Therefore, the following problems I encountered were all encountered in v3.3 testing 1.

After entering the game, the screen turns white and it is normal on the launcher page.  I have attached a screenshot below.

Hope to enhance the function:
It is hoped that there is no need to manually enter the X/Y coordinates of each button in the custom key position, but can be directly dragged by long pressing the touch screen, which will be very friendly to the player.

PojavLauncher runs very efficiently on my device. The 1.12.2 default setting I tested by myself can reach 140+ FPS with vertical synchronization turned off, which is better than any of the same type of applications on my device (such as boats), optimized  With these bugs, it can do better.  Thank you.

Screenshot:
![Screenshot_20201231_191837](https://user-images.githubusercontent.com/30495356/103409773-4d166d80-4ba3-11eb-8291-b0fe8ca8010b.jpg)
![Screenshot_20201231_191901](https://user-images.githubusercontent.com/30495356/103409776-4f78c780-4ba3-11eb-84f0-059b9bcd6000.jpg)
![Screenshot_20201231_191932](https://user-images.githubusercontent.com/30495356/103409778-50a9f480-4ba3-11eb-8a3b-84157b5eb532.jpg)

**Comment by artdeell** [comment]
The latest pre-release version is v.2 of he launcher. Pre-releases are now located only in the GitHub Actions.

**Comment by WangWenBin2017** [comment]
I tried this version, but the problem persists, and it does not support multiple languages.

**Comment by pstube** [comment]
Turn on fast rendering in video settings after installing Optifine

**Comment by khanhduytran0** [comment]
Can you screenshot when on a dark place to see how much white was?

**Comment by Adam0530** [comment]
> Can you screenshot when on a dark place to see how much white was?

I will... Wait a second

**Comment by WangWenBin2017** [comment]
> Can you screenshot when on a dark place to see how much white was?

For comparison, I use the same type of application boat and pojavlauncher for comparison.  The test seed is 1145141919810, the version number is 1.12.2, and the time is /time set night.  It can be seen that the color of pojavlauncher is white.
![Screenshot_20210105_171155](https://user-images.githubusercontent.com/30495356/103628749-67bd5d80-4f7a-11eb-8403-8a567a4eafac.jpg)
![Screenshot_20210105_171652](https://user-images.githubusercontent.com/30495356/103628758-6a1fb780-4f7a-11eb-80fe-0953fd9f24ab.jpg)

**Comment by Adam0530** [comment]
> Can you screenshot when on a dark place to see how much white was?

![Screenshot_20210105_171946](https://user-images.githubusercontent.com/76242887/103628784-71df5c00-4f7a-11eb-9fac-f72b2259591e.jpg)
![Screenshot_20210105_171956](https://user-images.githubusercontent.com/76242887/103628788-73a91f80-4f7a-11eb-8c89-2a9221fffa76.jpg)

**Comment by WesleyVanNeck** [comment]
> > Can you screenshot when on a dark place to see how much white was?
> 
> For comparison, I use the same type of application boat and pojavlauncher for comparison. The test seed is 1145141919810, the version number is 1.12.2, and the time is /time set night. It can be seen that the color of pojavlauncher is white.
> ![Screenshot_20210105_171155](https://user-images.githubusercontent.com/30495356/103628749-67bd5d80-4f7a-11eb-8403-8a567a4eafac.jpg)
> ![Screenshot_20210105_171652](https://user-images.githubusercontent.com/30495356/103628758-6a1fb780-4f7a-11eb-80fe-0953fd9f24ab.jpg)

Don't compare boat with pojav also not every one have that issue like me

**Comment by WangWenBin2017** [comment]
> > > Can you screenshot when on a dark place to see how much white was?
> > 
> > 
> > For comparison, I use the same type of application boat and pojavlauncher for comparison. The test seed is 1145141919810, the version number is 1.12.2, and the time is /time set night. It can be seen that the color of pojavlauncher is white.
> > ![Screenshot_20210105_171155](https://user-images.githubusercontent.com/30495356/103628749-67bd5d80-4f7a-11eb-8403-8a567a4eafac.jpg)
> > ![Screenshot_20210105_171652](https://user-images.githubusercontent.com/30495356/103628758-6a1fb780-4f7a-11eb-80fe-0953fd9f24ab.jpg)
> 
> Don't compare boat with pojav also not every one have that issue like me

I just want to make the whitening problem more obvious.  The rendering efficiency of pojav is better, I think fixing this bug will do better, nothing more.

**Comment by zhanhou0731** [comment]
I have this problem too , how to fix it ?
I already tried to turn on fast rendering in optifine , but it's still occurs  
Version 1.16.4 
Device :Vivo y15

**Comment by pstube** [comment]
options > video settings > shaders > internal

**Comment by khanhduytran0** [comment]
Update to latest build. It should be already fixed.

**Comment by zhanhou0731** [comment]
> options > video settings > shaders > internal

Thanks! But how about fabric sodium?

**Comment by zhanhou0731** [comment]
> Update to latest build. It should be already fixed.

I'm already in v3.3.1.1,is that latest build?

**Comment by AutumnVN** [comment]
> > Update to latest build. It should be already fixed.
> 
> I'm already in v3.3.1.1,is that latest build?

https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk 
download the latest

**Comment by zhanhou0731** [comment]
Thanks y'all !!
Y'all really helpful and friendly!!
