### ISSUE TITLE
[BUG] Error code 1

### ISSUE THREAD

**Issue by keyboard304** [PojavLauncherTeam/PojavLauncher#5561]
### Describe the bug

When I launch the application in version 1.20 it crashes.

While downloading assets/libraries the game launches mid download which is weird
![Screenshot_20240610-224711](https://github.com/PojavLauncherTeam/PojavLauncher/assets/123272222/c0892500-dd3d-466c-9f25-d015761f688c)

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/15778226/latest.log)

### Steps To Reproduce

```markdown
1- Download any version above 1.20 forge
2- start downloading 
3- the game starts mid download and gives error code 1 
4- close game
5- open and start again 
6- game downloads and opens 
7- error code appears
```

### Expected Behavior

The game to open normally like any other forge version.

### Platform

```markdown
- Device model: Infinix hot 10 (128gb)
- CPU architecture: Helio G70
- Android version: android 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

I downloaded Java 6 for the new version 
As well as trying all 3 renders 

I also deleted assets and libraries and tried redownloading 

Also I play forge 1.14 and 1.12 regularly and they are fine. I used to play 1.19 a year ago also fine I didn't test 1.19 lately

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt

**Comment by keyboard304** [comment]
> wrong log, send latestlog.txt

[latestlog.txt](https://github.com/user-attachments/files/15804313/latestlog.txt)

**Comment by GaucovyAero** [comment]
update pojav to the latest github actions build, guide is on the wiki

**Comment by keyboard304** [comment]
> update pojav to the latest github actions build, guide is on the wiki

Sorry, but I am not very familiar with GitHub and I am not sure how to find "actions build" the wiki is Abit confusing. If I can get a link I would be thankful.

Thank in advance!
