### ISSUE TITLE
Directory cusltom[F-Req] <Short description>

### ISSUE THREAD

**Issue by Mirik9724** [PojavLauncherTeam/PojavLauncher#5562]
### Is this request related to a bug?

No

### Anything else?

You need to add a custom directory for Minecraft to the launcher (this is useful for Android 11 and higher)

**Comment by TarikBR** [comment]
Its impossible on android 11 and higher

> Starting in Android 11, apps cannot create their own app-specific directory on external storage. To access the directory that the system provides for your app, call getExternalFilesDirs().

https://developer.android.com/about/versions/11/privacy/storage

**Comment by Mirik9724** [comment]
or add a mod installer and world export, etc. in the launcher directory

**Comment by GaucovyAero** [comment]
please rename this issue to "Mod installer, world export, etc."

**Comment by GaucovyAero** [comment]
maybe also datapacks?

**Comment by Mirik9724** [comment]
No, this is an alternative option to fix the problem, if the custom directory is not really implemented

**Comment by GaucovyAero** [comment]
that wont be done, rename it please

**Comment by Mirik9724** [comment]
Ок

**Comment by GaucovyAero** [comment]
gonna close this, even the alternative prolly wont be done anyway

**Comment by Mirik9724** [comment]
это глупо
