### ISSUE TITLE
[BUG]When using angle, the world icon is black

### ISSUE THREAD

**Issue by zhangxixi2012** [PojavLauncherTeam/PojavLauncher#5563]
### Describe the bug

When using angle, the world icon is black

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/15781984/latest.log)
![Screenshot_2024-06-05-13-37-31-834](https://github.com/PojavLauncherTeam/PojavLauncher/assets/169125019/d3b8d0f8-5ff5-4ce2-aff0-22c6fc1f2120)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2.The world icon is black
```

### Expected Behavior

I hope the world icon is normal when using angle.

### Platform

```markdown
- Device model: Lenovo tb X606F
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20240531-bdc7f33-v3_openjdk
```

### Anything else?

Please tell me the solution or fix this problem. Thank you

**Comment by Marshall2439** [comment]
Are you sure it's because of angle renderer?

**Comment by Bel69420** [comment]
This is intended as angle cannot capture a picture for world icon because of framebuffer issue

**Comment by Bel69420** [comment]
Idk if this is fixable.

**Comment by GaucovyAero** [comment]
probably will not be fixed, make a controlmap so that its invisible when you press gui
