### ISSUE TITLE
[BUG] Jar files not opening a window

### ISSUE THREAD

**Issue by MobMasterMind** [PojavLauncherTeam/PojavLauncher#5567]
### Describe the bug

No window opens when i try to execute jars. I want to patch sodium and also install labymod both of which require opening a jar file. But when i try to open them i run into this issue where its just a black screen and no window is opening. And there is some kind of error described in the log.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15800217/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open Pojavlauncher
2. Click "Execute a .jar
3. Open any jar file (i used sodiumpatcher, optifine, forge and fabric installers)
```

### Expected Behavior

I expected it to open a window but no window is opened

### Platform

```markdown
- Device model: Realme RMX1825
- CPU architecture: x86_64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
sodiumpatcher has to be run with java 17, not 21
pretty sure labymod installer is java 8
