### ISSUE TITLE
[BUG] Exit Code -1

### ISSUE THREAD

**Issue by SovietOverlord** [PojavLauncherTeam/PojavLauncher#5569]
### Describe the bug

When I try to launch minecraft on my iPhone SE it crashes after a few seconds after hitting play. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15808244/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Enable JIT on AltServer
3. Start Minecraft
```

### Expected Behavior

Starting minecraft without getting this error. 

### Platform

```markdown
- Device model: iPhone SE (3rd Generation) A2595
- CPU architecture: A15 Bionic Chip (arm64)
- Android version: -
- PojavLauncher version
```

**Comment by GaucovyAero** [comment]
wrong repository, please go to PojavLauncherTeam/PojavLauncher_iOS
quick reply tho, your issue is that your launcher is too much out of date, please switch to 3.0-development builds from PojavLauncher_iOS github actions
