### ISSUE TITLE
[F-Req] <Performance issues and not many options to Fix them>

### ISSUE THREAD

**Issue by JellyPacMan9283** [PojavLauncherTeam/PojavLauncher#5570]
### Is this request related to a bug?

This Request isn't really related to a bug but it is more like an issue, See Pojav Has Some Serious performance issues, Even on PC"s Comparing pojav to Other launchers, Pojav is really unoptimized But on mobile its even worse, u barely hit 60 fps, It is understandable that java Minecraft isnt built for mobiles but instead built for PC's but as said before, the performance is worse on PC's too if compared  to other launchers so that means the performance is bad on both mobiles and pcs

### Describe the request.

My request is That You Add some More Options and settings to Control the performance And add some performance tweaks too Also increase the CPU or GPU utilization or if possible add a system where u could configure the CPU and GPU utilization 

### Anything else?

The Zink And angle Renderer Are unoptimized, Optimize them And Also there are heating issues, I Request that u fix them too

**Comment by 5ghzx** [comment]
people run pojav on pc? also java args

**Comment by 5ghzx** [comment]
and mods

**Comment by HassaanBG** [comment]
Aggred, pojav is kinda laggy

**Comment by ghost** [comment]
Yes also with powerful gpu zink run worse many heavy games run with vulkan on android but not run heavy like pojav. I think adding options to optimize performance pojav needed like alternate surface rendering and is for all renderers and pojav already have it but i think it's can better because i think pojav have many unused potential can be use

**Comment by ThatMG393** [comment]
1. You can't control nor increase GPU and CPU utilization because those things would probably require root. _(except for limiting MC's FPS but that wouldn't probably touch the CPU or maybe use your system's game booster?)_

2. Try lowering your graphics settings, it's not the phones fault that it's overheating _(unless it's those specific chipset that had been reported to overheat easily)_, Minecraft is a heavy game and it's very unoptimized. _(or maybe buy a better phone?)_

3. Zink and Angle is already optimized _(if you can, why not go to their repository [zink & angle] and tell them to optimize it_). PLUS, the pojav devs didn't made those so if they were to improve it, it's probably gonna be hard and will take some time. _(or maybe never?)_

**Comment by GaucovyAero** [comment]
thanks for the reply lol

**Comment by Bel69420** [comment]
> 1. You can't control nor increase GPU and CPU utilization because those things would probably require root. _(except for limiting MC's FPS but that wouldn't probably touch the CPU or maybe use your system's game booster?)_
> 2. Try lowering your graphics settings, it's not the phones fault that it's overheating _(unless it's those specific chipset that had been reported to overheat easily)_, Minecraft is a heavy game and it's very unoptimized. _(or maybe buy a better phone?)_
> 3. Zink and Angle is already optimized _(if you can, why not go to their repository [zink & angle] and tell them to optimize it_). PLUS, the pojav devs didn't made those so if they were to improve it, it's probably gonna be hard and will take some time. _(or maybe never?)_

Well, ximi gamebooster just ruined the performance so using gamebooster is not recommended if you're Miui users.

**Comment by Bel69420** [comment]
Depends on some xiaomi/poco/redmi phone

**Comment by WesleyVanNeck** [comment]
if i run pojav in waydroid it is much slower compared to prismlauncher runing native and waydroid runs android apps at native speeds most of the time pojav has alot of overhead on zink

**Comment by Mathias-Boulay** [comment]
Pojav isn't made with PC in mind. 
If you have useful code to help address the performance issues, make a pr.

**Comment by WesleyVanNeck** [comment]
> Pojav isn't made with PC in mind. If you have useful code to help address the performance issues, make a pr.

yeah but its same on mobile do the overhead in zink

**Comment by JellyPacMan9283** [comment]
> 1. You can't control nor increase GPU and CPU utilization because those things would probably require root. _(except for limiting MC's FPS but that wouldn't probably touch the CPU or maybe use your system's game booster?)_
> 2. Try lowering your graphics settings, it's not the phones fault that it's overheating _(unless it's those specific chipset that had been reported to overheat easily)_, Minecraft is a heavy game and it's very unoptimized. _(or maybe buy a better phone?)_
> 3. Zink and Angle is already optimized _(if you can, why not go to their repository [zink & angle] and tell them to optimize it_). PLUS, the pojav devs didn't made those so if they were to improve it, it's probably gonna be hard and will take some time. _(or maybe never?)_



> 1. You can't control nor increase GPU and CPU utilization because those things would probably require root. _(except for limiting MC's FPS but that wouldn't probably touch the CPU or maybe use your system's game booster?)_
> 2. Try lowering your graphics settings, it's not the phones fault that it's overheating _(unless it's those specific chipset that had been reported to overheat easily)_, Minecraft is a heavy game and it's very unoptimized. _(or maybe buy a better phone?)_
> 3. Zink and Angle is already optimized _(if you can, why not go to their repository [zink & angle] and tell them to optimize it_). PLUS, the pojav devs didn't made those so if they were to improve it, it's probably gonna be hard and will take some time. _(or maybe never?)_

OK But I also said pojav's performance wasn't the best when compared to other launchers out there.

**Comment by ThatMG393** [comment]
> OK But I also said pojav's performance wasn't the best when compared to other launchers out there.

Again, It's not Pojav's problem, there's really not much "good" renderers to use unlike PC's, PC's use OpenGL and mobiles use OpenGLES and they're completely different GAPI's that why there are renderers on Pojav, they translate OpenGL calls to OpenGLES calls or Vulkan (if Zink). All the Pojav devs did was use some hacks, workarounds, and patches to launch Minecraft on Android. AND! Don't compare launchers, they're launchers and launchers are launchers not a game, they should only be compared by useability, looks and performance (launcher responsiveness, etc.)
