### ISSUE TITLE
1.21 crash

### ISSUE THREAD

**Issue by BUGAMING85677** [PojavLauncherTeam/PojavLauncher#5573]
### Describe the bug

1.21 is crashing

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15825305/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher.
2. Select 1.21
3. Play.
4. Crash.
```

### Expected Behavior

To not crash.

### Platform

```markdown
- Device model: RMX3501
- CPU architecture: ?
- Android version: 13
- PojavLauncher version: vedelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Raidware** [comment]
same with me

**Comment by kasrarouhi** [comment]
Are you download latest version of pojav in GitHub. And installed java 21

**Comment by ghost** [comment]
Are you downloaded latest version of pojav in GitHub
![Screenshot_۲۰۲۴-۰۶-۱۳-۲۱-۰۴-۱۷-۹۷۹_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/d3c532df-0d82-445f-939d-71861275953b)
I talk about this PLUS needs java 21

**Comment by Lucasgamer571109** [comment]
![Screenshot_20240613_153523_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172643614/6ea8453b-2451-4aff-bb60-3f6632f85fa8)
Java 1.21 doesnt work and I have Java 21

**Comment by moidar5366** [comment]
okay, if you discuss the 1.21 crush, i send a 
[latestlog.txt](https://github.com/user-attachments/files/15827954/latestlog.txt)
my latestlog isn't similar like him latestlog,

**Comment by moidar5366** [comment]
no, similar

**Comment by ghost** [comment]
> Are you downloaded latest version of pojav in GitHub ![Screenshot_۲۰۲۴-۰۶-۱۳-۲۱-۰۴-۱۷-۹۷۹_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/339489550-d3c532df-0d82-445f-939d-71861275953b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMDkwOTgsIm5iZiI6MTcxODMwODc5OCwicGF0aCI6Ii8xNDA0NjUyNjYvMzM5NDg5NTUwLWQzYzUzMmRmLTBkODItNDQ1Zi05MzlkLTcxODYxMjc1OTUzYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxOTU5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGMyZmVkZjIzNGQxNTA1Y2FjZjMzNDIyZjBhNWNjZjZiNzc3ZGI0MDNhNjQ2MTNlODg0MjQ1OTE4ZjVkMGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cASqcGwbnHeFDBYFBHM-nj_mMlpxpkDAo3goeZzUUtk) I talk about this PLUS needs java 21

In minecraft 1.21 need lwjgl 3.3.3 and this version update lwjgl 3.3.1 to 3.3.3

**Comment by GaucovyAero** [comment]
update to the latest github actions build, guide is on the wiki
