### ISSUE TITLE
[BUG] 1.21 not available for download

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5575]
### Describe the bug

Can't download 1.21

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158475307/26e581d4-bdd4-43eb-a54a-53244a88e135)

### Steps To Reproduce

```markdown
1. Launch pojav
2. Try to download 1.21
3. Dosen't exist
```

### Expected Behavior

I expected 1.21 to be there

### Platform

```markdown
- Device model: Galaxy A31
- CPU architecture: 64arm
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by ghost** [comment]
Be Patient

**Comment by GaucovyAero** [comment]
there is no reload button in the launcher, wait till it somehow appears or reinstall the launcher
