### ISSUE TITLE
[F-Req] when is the next pojav release coming out?

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5577]
### Is this request related to a bug?

No

**Comment by 5ghzx** [comment]
One came out 3 days ago, another 2 weeks ago. Or do you mean MC version? 1.21 comes out on June 13th.

**Comment by 5ghzx** [comment]
Which is today.

**Comment by GaucovyAero** [comment]
dont ask for etas

**Comment by TotallyNotSaeed** [comment]
> Which is today.

No, last time it was updated was on sep 28th "edelweiss release"

When is the next one?
