### ISSUE TITLE
[BUG]  new version 1.21 does not start 

### ISSUE THREAD

**Issue by Samikhaya** [PojavLauncherTeam/PojavLauncher#5578]
### Describe the bug

I can't load the new version of minecraft 1.21 .when I try to launch it, I get an error and it kicks me out of the game even though I have Java installed  21
![Screenshot_20240614_033043_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172678224/598c1860-d57c-493f-901e-2995bd169515)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15829637/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start PojavLaunche
2.Use 1.21 Version
3.Start Game
```

### Expected Behavior

I expect so that everything works well 

### Platform

```markdown
- Device model: Samsung A14
- CPU architecture:  arm64
- Android version: 13
- PojavLauncher version: dahlia-20230813-5e8842b-v3_openjdk
```

### Anything else?

No

**Comment by ghost** [comment]
You need download latest version of pojav in GitHub. In latest version of minecraft need lwjgl 3.3.3 in pojav GitHub updated lwjgl 3.3.1 to 3.3.3

**Comment by Samikhaya** [comment]
> You need download latest version of pojav in GitHub. In latest version of minecraft need lwjgl 3.3.3 in pojav GitHub updated lwjgl 3.3.1 to 3.3.3

I cant find him could you send me the link?

**Comment by 5ghzx** [comment]
go to the github actions tab, click on the top one, scroll to artifacts and download the apk

**Comment by Samikhaya** [comment]
> go to the github actions tab, click on the top one, scroll to artifacts and download the apk

app.debug.apk?

**Comment by Genvix** [comment]
Post a link, I have the same problem.

**Comment by 5ghzx** [comment]
yes
app debug

**Comment by 5ghzx** [comment]
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/77870202/fbc5b832-6075-4c66-b992-13aa10a4565a)

**Comment by ThatMG393** [comment]
Click this link: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9313978704

Scroll down and download `app-debug` _(or `app-debug-noruntime` if you already downloaded a debug build and want to update)_.

Open the downloaded zip file and extract the apk file and install it.

**Comment by Genvix** [comment]
How do I find it?

**Comment by ThatMG393** [comment]
> How do I find it?

Follow what I said.

**Comment by Genvix** [comment]
Thanks man

**Comment by 5ghzx** [comment]
> Post a link, I have the same problem.

pebkac

**Comment by ghost** [comment]
THIS HELPED ME IT WORKS THANK YOU..

**Comment by LIPO69** [comment]
How to download ???? I have the code open

**Comment by LIPO69** [comment]
How to download ???? I have the code open

**Comment by LIPO69** [comment]
How to download????

**Comment by ThatMG393** [comment]
> How to download ???? I have the code open

https://github.com/PojavLauncherTeam/PojavLauncher/issues/5578#issuecomment-2167077233

**Comment by Igg8g** [comment]
Thanks! Worked for me! Vielen Danke

**Comment by Cuchari** [comment]
How can i open a apk file in pc???

**Comment by 5ghzx** [comment]
bluestacks emulator

**Comment by Emwhatasigma** [comment]
For these who cant install: you need to be logged in

**Comment by Cale445** [comment]
> You need download latest version of pojav in GitHub. In latest version of minecraft need lwjgl 3.3.3 in pojav GitHub updated lwjgl 3.3.1 to 3.3.3

Hi bro do you have any tips or things to do to fix the same problem but when mods are installed? Because when I put mods in the mods folder from pojav launcher and start the game the same problem shows up but I have downloaded the latest version of pojav

**Comment by Cale445** [comment]
> Click this link: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9313978704
> 
> Scroll down and download `app-debug` _(or `app-debug-noruntime` if you already downloaded a debug build and want to update)_.
> 
> Open the downloaded zip file and extract the apk file and install it.

HI bro do you know how to fix mine? Its shows up the same problem but with mods installed even when I have already installed the latest version of my pojav launcher
