### ISSUE TITLE
Excess textures when using mod pack the fog

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5579]
### Describe the bug

I downloaded the fog from pojav modpack library and I entered the game, when I created the world and played it I saw it. Brains are strange things
![Screenshot_2024-06-14-07-53-15-10_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139622169/ad51ec98-a7bf-4c64-9963-2f208159143c)

### The log file and images/videos

Idk

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I expect the mod work good

### Platform

```markdown
- Device model: Oppo Reno 3
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: lastest version on gg play
```

**Comment by Nekotaco** [comment]
Use fancy leaves or remove better leaves texture pack
