### ISSUE TITLE
Installing forge does not work  Devices Xiaomi 8, Android 10

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#558]
--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl-tinyfd.jar, ClassWrapper.jar, lwjgl-stb.jar, lwjgl.jar, lwjgl-opengl.jar, lwjgl-jemalloc.jar, jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-openal.jar, version, lwjgl-glfw-converted.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms4096m -Xmx4096m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
--------- beginning of system
--------- beginning of main
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x361
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x450
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x33c0
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x13b8
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x2196
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x6a46
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x4d9
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0xda0
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/LaunchJVM(20540): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
S/LaunchJVM(20540): dlopen /data/app/net.kdt.pojavlaunch-e2HYTA7MtXTpA703p3_u9g==/lib/arm64/libopenal.so success
S/LaunchJVM(20540): dlopen /data/app/net.kdt.pojavlaunch-e2HYTA7MtXTpA703p3_u9g==/lib/arm64/libgl04es.so success
S/LaunchJVM(20540): Done processing args
S/LaunchJVM(20540): Found JLI lib
S/LaunchJVM(20540): Calling JLI_Launch
S/jrelog  (20540): OpenJDK 64-Bit Server VM warning: 
S/jrelog  (20540): No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x8ff
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
S/jrelog  (20540): " unused DT entry: 
S/jrelog  (20540): DT_RPATH
S/jrelog  (20540):  (type 
S/jrelog  (20540): 0xf
S/jrelog  (20540):  arg 
S/jrelog  (20540): 0x16fe
S/jrelog  (20540): ) (ignoring)
S/jrelog  (20540): 
S/jrelog  (20540): WARNING: linker: 
S/jrelog  (20540): Warning: "
S/jrelog  (20540): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
S/jrelog  (20540): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20540): 0x81
S/jrelog  (20540):  (ignoring unsupported flags)
S/jrelog  (20540): 
S/jrelog  (20540): 2021-01-01 04:52:19,190 main ERROR Error creating converter for tEx java.lang.reflect.InvocationTargetException
S/jrelog  (20540): 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
S/jrelog  (20540): 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
S/jrelog  (20540): 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
S/jrelog  (20540): 	at java.lang.reflect.Method.invoke(Method.java:498)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:582)
S/jrelog  (20540): 	at org.apache
S/jrelog  (20540): .logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:638)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:414)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:177)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:163)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.pattern.HighlightConverter.newInstance(HighlightConverter.java:196)
S/jrelog  (20540): 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
S/jrelog  (20540): 	at
S/jrelog  (20540):  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
S/jrelog  (20540): 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
S/jrelog  (20540): 	at java.lang.reflect.Method.invoke(Method.java:498)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:582)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:638)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:414)
S/jrelog  (20540): 	at org.a
S/jrelog  (20540): pache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:177)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.layout.PatternLayout$SerializerBuilder.build(PatternLayout.java:376)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:128)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:58)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:652)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.buil
S/jrelog  (20540): d(PatternLayout.java:516)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.config.Ab
S/jrelog  (20540): stractConfiguration.createConfiguration(AbstractConfiguration.java:884)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.Lo
S/jrelog  (20540): ggerContext.reconfigure(LoggerContext.java:617)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
S/jrelog  (20540): 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
S/jrelog  (20540): 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
S/jrelog  (20540): 	at org.apache.logging.log4j.L
S/jrelog  (20540): ogManager.getLogger(LogManager.java:551)
S/jrelog  (20540): 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
S/jrelog  (20540): 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
S/jrelog  (20540): Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.core.pattern.ThrowablePatternConverter.<init>(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Lorg/apache/logging/log4j/core/config/Configuration;)V
S/jrelog  (20540): 	at cpw.mods.modlauncher.log.TransformingThrowablePatternConverter.<init>(TransformingThrowablePatternConverter.java:45)
S/jrelog  (20540): 	at cpw.mods.modlauncher.log.TransformingThrowablePatternConverter.newInstance(TransformingThrowablePatternConverter.java:79)
S/jrelog  (20540): 	... 41 more
S/jrelog  (20540): 
S/jrelog  (20540): 2021-01-01 04:52:19,198 main ERROR Unrecognized conversion specifier [tEx] starting at position 68 in conversion pattern.
S/jrelog  (20540): 
S/jrelog  (20540): [32m[04:52:19.506] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, 2845064122@qq.com, --version, 1.16.4, --gameDir, /storage/emulated/0/games/.minecraft, --assetsDir, /storage/emulated/0/games/.minecraft/assets, --assetIndex, 1.16, --uuid, 00000000-0000-0000-0000-000000000000, --accessToken, 鉂勨潉鉂勨潉鉂勨潉鉂勨潉, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.28, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, -
S/jrelog  (20540): -fml.mcpVersion, 20201102.104115, --fullscreen] %tEx
S/jrelog  (20540): [m
S/jrelog  (20540): [32m[04:52:19.512] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0-internal by Oracle Corporation %tEx
S/jrelog  (20540): [m
S/jrelog  (20540): [32m[04:52:19.971] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/storage/emulated/0/games/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT %tEx
S/jrelog  (20540): [m
S/jrelog  (20540): [1;31m[04:52:20.004] [main/ERROR] [LaunchServiceHandler/MODLAUNCHER]: Cannot find launch target fmlclient, unable to launch %tEx
S/jrelog  (20540): [m
S/jrelog  (20540): Exception in thread "main" 
S/jrelog  (20540): java.lang.RuntimeException: Cannot find launch target
S/jrelog  (20540): 
S/jrelog  (20540): 	at cpw.mods.modlauncher.LaunchServiceHandler.validateLaunchTarget(LaunchServiceHandler.java:87)
S/jrelog  (20540): 
S/jrelog  (20540): 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:78)
S/jrelog  (20540): 
S/jrelog  (20540): 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
S/jrelog  (20540): 
Java Exit code: 1
S/LaunchJVM(20540): Going to free args
S/LaunchJVM(20540): Free done

**Comment by khanhduytran0** [comment]
Didn't you install target vanilla version?

**Comment by yanluol** [comment]
what do you mean?

**Comment by khanhduytran0** [comment]
I mean did you install 1.16.4 already?

**Comment by yanluol** [comment]
yes

**Comment by yanluol** [comment]
Yes, I am

**Comment by artdeell** [comment]
You are on a launcher version that doesn't support 1.13+ Forge. Use Fabric, or update your launcher version.

**Comment by yanluol** [comment]
How to get a new version

**Comment by T-CATHOME** [comment]
@yanluol https://github.com/PojavLauncherTeam/PojavLauncher/actions

**Comment by yanluol** [comment]
Cannot get

**Comment by yejunjie10311031** [comment]
我的华为nova3 android9可以正常安装forge
![Screenshot_20210101_093142_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/103450641-352d0f80-4cb1-11eb-9f6f-2952ce6f9c0a.jpg)
![Screenshot_20210101_093826_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/103450643-38280000-4cb1-11eb-8e82-c2c16361b117.jpg)
![Screenshot_20210101_093422_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/103450644-39592d00-4cb1-11eb-86b8-d7c230f2a248.jpg)
![Screenshot_20210101_224519_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/103450645-39f1c380-4cb1-11eb-8735-75e85ca0bc7b.jpg)

**Comment by WesleyVanNeck** [comment]
> 我的华为nova3 android9可以正常安装forge
> ![Screenshot_20210101_093142_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/103450641-352d0f80-4cb1-11eb-9f6f-2952ce6f9c0a.jpg)
> ![Screenshot_20210101_093826_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/103450643-38280000-4cb1-11eb-8e82-c2c16361b117.jpg)
> ![Screenshot_20210101_093422_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/103450644-39592d00-4cb1-11eb-86b8-d7c230f2a248.jpg)
> ![Screenshot_20210101_224519_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/103450645-39f1c380-4cb1-11eb-8735-75e85ca0bc7b.jpg)

Pls use english

**Comment by artdeell** [comment]
Why not use chinese?
it's not Discord after all

**Comment by khanhduytran0** [comment]
- Update to latest build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/479585593
- If error persists, remove `.minecraft` folder and install again.

**Comment by khanhduytran0** [comment]
@yanluol please reply

**Comment by yanluol** [comment]
I will try thanks

**Comment by yanluol** [comment]
Still failed
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/Attempt to get length of null array/Attempt to get length of null array.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:577)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:335)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:44)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/Attempt to get length of null array/Attempt to get length of null array.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:645)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:496)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 13 more

**Comment by artdeell** [comment]
Old build. This exception was patched in newer builds.

**Comment by yanluol** [comment]
I'm using a new version, but it doesn't appear after I install forge

**Comment by khanhduytran0** [comment]
Don't pick and play when versions list became error
```
- Error:
- Attempt to get length of null array
```

**Comment by Mathias-Boulay** [comment]
Stale issue from an old build, forge now benefits from the graphical installer on the google play release.
