### ISSUE TITLE
1.21 is not opening 

### ISSUE THREAD

**Issue by Krish-cyber-3311** [PojavLauncherTeam/PojavLauncher#5581]
### Describe the bug

1.21 the latest version is not opening please do something 😕 

### The log file and images/videos

Please fix this problem 

### Steps To Reproduce

```markdown
Please do something
```

### Expected Behavior

1.21 not opening should be fixed

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No

**Comment by ThatMG393** [comment]
How are they gonna fix it if you do not provide the game logs, please follow the template so the devs can identify the issue and fix it.

**Comment by YHMKWDSJ** [comment]
[latestlog.txt](https://github.com/user-attachments/files/15836390/latestlog.txt)
game log…？

**Comment by ThatMG393** [comment]
> [latestlog.txt](https://github.com/user-attachments/files/15836390/latestlog.txt) game log…？

according to your log file, the issue you're having has already been fixed. follow this tutorial: https://github.com/PojavLauncherTeam/PojavLauncher/issues/5578#issuecomment-2167077233

**Comment by EdoardLimondi** [comment]
i have a issues that can't see at latest version 1.21 but see only latest snapshot 1.21-rc1 and latest release 1.20.6
