### ISSUE TITLE
1.21 keep crashing (java 21 used)

### ISSUE THREAD

**Issue by bobbyiscool123** [PojavLauncherTeam/PojavLauncher#5584]
### Describe the bug

The game kept crashing when i tried to load the minecraft 1.21 update it works fine for 1.20 but not for 1.21 
[latestlog.txt](https://github.com/user-attachments/files/15838063/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15838120/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.download 1.21 update
3.select the java 21 as default java runtime 
4.select the zink vulkan renderer
5.launch the game
6.crashes
```

### Expected Behavior

work as usual as the snapshots thst used java 21 which worked before

### Platform

```markdown
- Device model: samsung galaxy f23 
- CPU architecture: arch64
- Android version: 14
- PojavLauncher version: edelweiss
```

**Comment by ThatMG393** [comment]
this will fix it: https://github.com/PojavLauncherTeam/PojavLauncher/issues/5578#issuecomment-2167077233

**Comment by YukiFuyuko** [comment]
Expect JNA 7.0.0?

**Comment by ThatMG393** [comment]
> Expect JNA 7.0.0?

It's harmless.

**Comment by spectre4570** [comment]
Where is the APK file?

**Comment by GaucovyAero** [comment]
fixed in latest playstore
