### ISSUE TITLE
How to use Shaders in the New Edelweiss Update

### ISSUE THREAD

**Issue by RealTTraction** [PojavLauncherTeam/PojavLauncher#5585]
### Is this request related to a bug?

Kinda but I really want to use shaders but I need to go to the older versions of pojav to do that

### Describe the request.

If you have a way please say it to me

### Anything else?

<3

**Comment by GaucovyAero** [comment]
you gotta mention what exact shaders you were using, what version of mc, renderer and what phone you have

**Comment by D3llwyn** [comment]
Currently in the newest update, you can only run shaders using Zink renderer

The only shaders that Holy GL4ES renderer supports is Open4ES shaders
