### ISSUE TITLE
[BUG] Error Modpack Fear Nightfall

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5586]
### Describe the bug

Modpack Fear Nightfall Crash Code -1 When Running

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15840504/latestlog.txt)

### Steps To Reproduce

```markdown
Install Modpack Fear Nightfall 1.19.2
```

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64 
- Android version: 13
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

There isn't any

**Comment by GaucovyAero** [comment]
seems like your sodium is not compatible with your other mods
