### ISSUE TITLE
Zink 1.21 crash

### ISSUE THREAD

**Issue by NinjaLegendmc** [PojavLauncherTeam/PojavLauncher#5589]
### Describe the bug

When use Zink render in Pojavlauncher GitHub latest auction build it happening and it says zink need lwjgl 3.3.1 to run please fix this and give update in playstore.

### The log file and images/videos

Update!

### Steps To Reproduce

```markdown
1.start Pojavlauncher 1.21
2.use Zink render
3.It crash :(
```

### Expected Behavior

Update

### Platform

```markdown
- Device model:vivo y100a
- CPU architecture:arm64
- Android version:14
- PojavLauncher version:lastest GitHub auction build
```

### Anything else?

Please give playstore update

**Comment by GaucovyAero** [comment]
zink likely does not support your gpu

**Comment by NinjaLegendmc** [comment]
> zink likely does not support your gpu

Google play Pojavlauncher Zink works fine without any problem

**Comment by SolDev69** [comment]
Use the Google Play version then, or use (shameless plug) [SolCraftLauncher](https://github.com/SolDev69/SolCraftLauncher/actions/runs/9368526064)'s zink (not UMP zink)

**Comment by NinjaLegendmc** [comment]
> Use the Google Play version then, or use (shameless plug) [SolCraftLauncher](https://github.com/SolDev69/SolCraftLauncher/actions/runs/9368526064)'s zink (not UMP zink)

I can't use your launcher because it need premium account to login 😔

**Comment by 5ghzx** [comment]
minecraft is on sale rn, go buy it
