### ISSUE TITLE
[BUG] Не работает клавиатура (вообще)

### ISSUE THREAD

**Issue by Eurannic** [PojavLauncherTeam/PojavLauncher#559]
Когда я хочу где либо ввести текст (будь то в чате, или когда хочу переименовать мир) он не вводится, причем не только на русской, но и на любой другой раскладке. И работает только стирание текста, больше ничего. Это можно как то пофиксить или это недоработка разработчиков?

**Comment by artdeell** [comment]
Версия лаунчера какая?

**Comment by Eurannic** [comment]
Я хз, скачал самую последнюю из вкладки "Actions"

**Comment by artdeell** [comment]
А какую вы используете клавиатуру?

**Comment by Eurannic** [comment]
Ну не внешняя, а та что включается нажатием кнопки

**Comment by artdeell** [comment]
Я имею ввиду - какое приложение клавиатуры?

**Comment by Eurannic** [comment]
Клавиатура Samsung. Вы это имеете ввиду?

**Comment by artdeell** [comment]
Именно это. Пожалуйста, попробуйте использовать другие клавиатуры, такие как Gboard или Hacker's Keyboard. Мы не гарантипуем работу с другими клавиатурами.

**Comment by Eurannic** [comment]
Большое спасибо, помогло
