### ISSUE TITLE
[update pojav in pm] <update pojav>

### ISSUE THREAD

**Issue by moidar5366** [PojavLauncherTeam/PojavLauncher#5590]
### Is this request related to a bug?

1.21 is out, but more people can’t play this version, and they don’t want to download a clone of PojavLauncher to play this version, copy all worlds and version, it's to long

### Describe the request.

Update PojavLauncher in Play Market)

### Anything else?

no

**Comment by TotallyNotSaeed** [comment]
Fr they should release one update every time mojang releases one
And 7+ reports about 1.21 crashing in just a day, and that number will increase if they don't release an update

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/158475307/22f2df5f-dc13-4cd7-bdea-f1dd46bc3bcd)

**Comment by TarikBR** [comment]
> Fr they should release one update every time mojang releases one
> And 7+ reports about 1.21 crashing in just a day, and that number will increase if they don't release an update

but they're already working on it, it's not their fault that these problems only appeared when mojang released 1.21, and not before
it should be noted that there are only 2 official pojav developers here

**Comment by GaucovyAero** [comment]
current dev builds are not in a very stable state
