### ISSUE TITLE
Minecraft 1.21 Not working

### ISSUE THREAD

**Issue by brawllaunchchannel** [PojavLauncherTeam/PojavLauncher#5591]
### Describe the bug

Minecraft 1.21 crashes ( doesnt Open ) also i think some Versions below. I have pinned the Log ( and found the Error ) but idk how to Actually fix it without roots Access...

[latestlog.txt](https://github.com/user-attachments/files/15841618/latestlog.txt)
![Screenshot_20240614-175140](https://github.com/PojavLauncherTeam/PojavLauncher/assets/123104434/3c5e21bd-8e9e-4bee-9297-3e02a1d4552c)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15841686/latestlog.txt)

### Steps To Reproduce

```markdown
Start 1.21
```

### Expected Behavior

It crashes 

### Platform

```markdown
- Device model: Nokia x30
- CPU architecture: idk ( arm64 ??)
- Android version: 14
- PojavLauncher version: newest ( 14.6.24 )
```

**Comment by GaucovyAero** [comment]
update to the latest github actions build, guide is on the wiki
