### ISSUE TITLE
1.21 no working fix it 

### ISSUE THREAD

**Issue by Demon8628** [PojavLauncherTeam/PojavLauncher#5592]
### Describe the bug

![Screenshot_20240614-225439](https://github.com/PojavLauncherTeam/PojavLauncher/assets/159460652/3bb2bd88-70ce-4673-b543-640c2be2edfd)

### The log file and images/videos

Pl

### Steps To Reproduce

```markdown
Pl
```

### Expected Behavior

Pl

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
update to the latest github actions build, guide is on the wiki
