### ISSUE TITLE
selecting a game directory other than data/pojav-folder/files

### ISSUE THREAD

**Issue by Mirik9724** [PojavLauncherTeam/PojavLauncher#5593]
### Is this request related to a bug?

mayby

### Describe the request.

selecting a game directory other than data/pojav-folder/files

**Comment by GaucovyAero** [comment]
not possible due to android restrictions

**Comment by GaucovyAero** [comment]
(it would not be possible to exist on play store if the directory was outside of there, it would also be a security issue)
