### ISSUE TITLE
Add "Search profiles..."?

### ISSUE THREAD

**Issue by ImNotTheChiku35** [PojavLauncherTeam/PojavLauncher#5594]
### Is this request related to a bug?

no, it's not a bug. I just want to easily find profile, because I have many of them

### Describe the request.

Add a search thing to easily find profiles. like from profile name, version, etc

### Anything else?

I don't know what will change the current UI

**Comment by GaucovyAero** [comment]
wont be done, thats too complicated for the current UI, but a UI change will come someday
