### ISSUE TITLE
Jre problem 

### ISSUE THREAD

**Issue by NinjaLegendmc** [PojavLauncherTeam/PojavLauncher#5596]
### Describe the bug

![Screenshot_2024_0615_133428](https://github.com/PojavLauncherTeam/PojavLauncher/assets/170965489/71600b6e-1e23-4c3c-8113-bbc70484853e)
When try to use distance horizon jre 21 in Pojavlauncher and this jre form Pojavlauncher discord server jre 21 for distance horizon 

### The log file and images/videos

...

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

...

### Platform

```markdown
- Device model:vivoy100a
- CPU architecture:64BIT
- Android version:14
- PojavLauncher version: playstore version
```

### Anything else?

...

**Comment by ThatMG393** [comment]
Change the file extension of the jre to `.tar.xz`.

Result -> `jre21-arm64-SQLite.tar.xz`

**Comment by NinjaLegendmc** [comment]
> Change the file extension of the jre to `.tar.xz`.
> 
> Result -> `jre21-arm64-SQLite.tar.xz`

Mean
