### ISSUE TITLE
1.21 not running jre21 runtime

### ISSUE THREAD

**Issue by Tappyplays** [PojavLauncherTeam/PojavLauncher#5597]
### Describe the bug

If I have the java 21 runtime, it doesn't run or it's  just black screen/crashes.

### The log file and images/videos

[2024-06-15-1.log.gz](https://github.com/user-attachments/files/15846158/2024-06-15-1.log.gz)

### Steps To Reproduce

```markdown
1. Make 1.21 run
2. new update for lwjgl 3.3.3
3. add java 21 without downloading it from links
```

### Expected Behavior

I expected that 1.21 will run in java 21 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ThatMG393** [comment]
Can you upload the `latestlog.txt` instead?

**Comment by Fernandosin** [comment]
@ThatMG393 
https://github.com/user-attachments/files/15846471/latestlog.txt

**Comment by GaucovyAero** [comment]
update to the latest github actions build, guide is on the wiki
