### ISSUE TITLE
[BUG] <Short description> lastestlog.txt error 1.21

### ISSUE THREAD

**Issue by Ratata01** [PojavLauncherTeam/PojavLauncher#5598]
### Describe the bug

sempre que tento entrar na versão 1.21 default dá o erro "aplicação/jogo saiu com código -1, verifique lastestlog.txt para mais detalhes"

### The log file and images/videos

lastestlog.txt

### Steps To Reproduce

```markdown
1.iniciar pojavlauncher
2.instalar versão 1.21 default
3.clicar play
4.esperar
5.error
```

### Expected Behavior

Esperava que eu pudesse jogar

### Platform

```markdown
- Device model: xiaomi redmi 12c
- CPU architecture: aarch64
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by ThatMG393** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/5578#issuecomment-2167077233
