### ISSUE TITLE
External mouse is not working [BUG] <Short description>

### ISSUE THREAD

**Issue by Oppvirtual** [PojavLauncherTeam/PojavLauncher#5602]
### Describe the bug

When I connect external mouse with launcher it is not working it got freez in centre 
Device redmi note 8 pro 
Ram 6gb rom 128 64 bit
Please solve my issue

### The log file and images/videos

![Screenshot_2024-06-16-14-43-13-774_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/163013607/553b9910-d161-4eed-a6a3-78bacbb768b4)

### Steps To Reproduce

```markdown
Start Pojavlauncher
Then play 1.21
After it launches external mouse freeze in centre
```

### Expected Behavior

When I connect mouse with my device after opening game it freeze in centre 

### Platform

```markdown
- Device model:redmi note 8 pro
- CPU architecture:arm 64
- Android version:11
- Pojalaucherversion:edelweiss-20240531-b

dc7f33-v3_openjdk
```

### Anything else?

Please solve my problem

**Comment by Mathias-Boulay** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9521311277
