### ISSUE TITLE
[BUG] OptiFine is not loading and the GUI button is missing 

### ISSUE THREAD

**Issue by AndrosPlays** [PojavLauncherTeam/PojavLauncher#5603]
### Describe the bug

When I create an Optifine account, it doesn't show in the profiles and it's not loading as well.
![Screenshot_20240616-175231](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172959444/9e74693e-52b3-4b84-81d7-01871a3eb268)
![Screenshot_20240616-175756](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172959444/4c2d63f0-bebd-41e8-a855-900a0f149e01)

### The log file and images/videos

NA

### Steps To Reproduce

```markdown
1. Start Pojav
2. Select Create new profile
3. Select Create Optifine Profile
4. Select OptiFine HD U 17
```

### Expected Behavior

I expected it to load and after 30 mins still not loading and the GUI button is also missing as I use external mouse.

### Platform

```markdown
- Device model: Techno Spark 10C
- Android version: 12
- PojavLauncher version: NA
```

**Comment by GaucovyAero** [comment]
you have to scroll up a bit in your profiles

**Comment by AndrosPlays** [comment]
> you have to scroll up a bit in your profiles


Uploading screen-20240616-181116.mp4…

Still not showing and GUI button missing

**Comment by GaucovyAero** [comment]
the video did not upload, you have to wait a bit

**Comment by GaucovyAero** [comment]
stale issue

**Comment by AndrosPlays** [comment]
I'm quit
