### ISSUE TITLE
How to add java 21 version in pojavlauncher

### ISSUE THREAD

**Issue by showoiz** [PojavLauncherTeam/PojavLauncher#5604]
### Is this request related to a bug?

my friend wanna play with me but his app daid he haven't java 21 to run 
where i can go to download in  android

### Describe the request.

1.21 good but i can't play it

**Comment by ThatMG393** [comment]
Join the PojavLauncher discord and go to frequently-asked-question channel.

**Comment by GaucovyAero** [comment]
its on the android-openjdk-build-multiarch github repo in the actions tab, just download, extract the zip and install the runtime
