### ISSUE TITLE
[BUG] Memory Tagging in GrapheneOS crashes Pojav

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5605]
### Describe the bug

Hello
I have a Pixel 8 pro flashed with GrapheneOS and I've noticed with MTE or memory tagging extensions enabled it crashes Pojav when launching Minecraft regardless of version.  Pojav runs fine with MTE disabled.

### The log file and images/videos

[PojavLauncher (Minecraft_ Java Edition for Android) log f8368905be5f.txt](https://github.com/user-attachments/files/15861487/PojavLauncher.Minecraft_.Java.Edition.for.Android.log.f8368905be5f.txt)

### Steps To Reproduce

```markdown
Open Pojav Launcher on Pixel 8 Pro running GrapheneOS with memory tagging enabled
Click Play
App Crashes
```

### Expected Behavior

Launch Minecraft with MTE enabled

### Platform

```markdown
- Device model: Pixel 8 Pro / Husky (codename)
- CPU architecture: ARM v8
- Android version: Android 14 QPR3
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

While this is currently a GrapheneOS specific issue, the stock Android OS on Pixel 8 and up might enable MTE in the future.

**Comment by ghost** [comment]
Here is the log file from Pojav too since my initial log was from the system logs on GrapheneOS although it doesn't look to be revealing much
[latestlog.txt](https://github.com/user-attachments/files/15862696/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
yeah no pojav won't run with memory tagging.
