### ISSUE TITLE
Fabric 1.20.1 crashes everytime

### ISSUE THREAD

**Issue by grosioso** [PojavLauncherTeam/PojavLauncher#5606]
### Describe the bug

I was trying to run fabric 1.20.1 it crashes after a bit of loading. I don't know why but this is so annoying even though I did nothing. 1.21 & 1.20.6 works fine

1. I use the latest github action build of pojavlauncher
2. all of the yt tutorials would never work
3. It shows the application/game exited with code -1

### The log file and images/videos

The screenshot:
![Screenshot_20240617-141721_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/2f39c4c1-0ac0-4137-b7b0-530e6a40eb02)
The log:
[latestlog.txt](https://github.com/user-attachments/files/15866432/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Install and open 1.20.1 fabric
3. Get this error message
```

### Expected Behavior

I expected to be working normally

### Platform

```markdown
- Device model: Samsung Galaxy A12 (A125F)
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest github actions build
```

**Comment by ThatMG393** [comment]
Switch to Java 17.

**Comment by grosioso** [comment]
> Switch to Java 17.

I still get the same error

**Comment by grosioso** [comment]
> Switch to Java 17.

I will send you proof rn, just wait

**Comment by grosioso** [comment]
> Switch to Java 17.

https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/fd46ad7a-6837-486b-af40-50eac3c74797

this is the proof

**Comment by grosioso** [comment]
![Screenshot_20240617-172413_PojavLauncher (Minecraft Java Edition for Android).jpg](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/7189e493-98cd-4311-9a36-fdc3875ebdd0)

I have the jre 17 set by default

edit: I accidentally removed jre 21 but it's ok

**Comment by grosioso** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/ce3c4ad5-3a01-4766-83d3-8737fd6eb16d

**Comment by RajveerBeast5665** [comment]
It is because of the dynamic fps mod
Remove it and then launch

**Comment by grosioso** [comment]
> It is because of the dynamic fps mod
> Remove it and then launch
> 
> 
> 

it works...
