### ISSUE TITLE
[BUG] <Zink UI rendering has an error on the cellphone Infinix Smart 8>

### ISSUE THREAD

**Issue by Nekoj09** [PojavLauncherTeam/PojavLauncher#5607]
### Describe the bug

![Screenshot_20240617-181514](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172976991/1156a390-0103-4f21-b46a-62adc49cf1ce)
JSo that's how it is. There is a bug when I use Zink rendering on the latest version and the old version, the UI still has errors.

### The log file and images/videos

![Screenshot_20240617-181511](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172976991/e3e81d8a-5b9a-4c47-bbcb-3610fbad6240)

### Steps To Reproduce

```markdown
I request that Render Zink can support all specifications
```

### Expected Behavior

I hope that the pojav developers can fix the Zink rendering bug on the infinix Smart 8 Because I don't like the Zink rendering which has bugs like if I only use a low end shader the screen is immediately transparent?

### Platform

```markdown
- Device model: Infinix Smart 8
- CPU architecture: ARMv8
- Android version: Android 13 XOS
- PojavLauncher version:*I only use the Pojav version which has Zink rendering, but everything is the same*
```

### Anything else?

That's all I hope the Infinix Smart 8 can support Zink rendering without errors on the Minecraft UI screen.

**Comment by Nekoj09** [comment]
Why?? Can you fix this for lastest update?

**Comment by grosioso** [comment]
> Why?? Can you fix this for lastest update?

I don't think they can fix it

**Comment by grosioso** [comment]
> Why?? Can you fix this for lastest update?

I think some devices cannot handle the zink renderer

**Comment by grosioso** [comment]
I just don't know

**Comment by Bel69420** [comment]
1. Your GPU driver is broken
2. You're using fork version of pojav launcher
3. Get a new phone with better driver 
4. Zink required at least Vulkan 1.1 with imageless framebuffer extension
5. Zink depends on your vulkan driver

**Comment by Bel69420** [comment]
And yes, pojav dev cannot fix this issue

**Comment by SenyxLois** [comment]
the simplest fix here is easy. Get a better phone

**Comment by grosioso** [comment]
> the simplest fix here is easy. Get a better phone
> 

true

**Comment by Nekoj09** [comment]
Very simple answer. So where's the money? 😂Oh yes, where can I see what version of Vulkan is on a cellphone?

**Comment by Bel69420** [comment]
Easy, just download vulkancapsviewer app on playstore

**Comment by GaucovyAero** [comment]
not all devices work perfectly with all renderers, renderers are very complicated, zink is not developed by us
