### ISSUE TITLE
[F-REQ]Can I add gamepad support? It's just really necessary. 

### ISSUE THREAD

**Issue by FoxEdKr07** [PojavLauncherTeam/PojavLauncher#561]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WesleyVanNeck** [comment]
@FoxEdKr07 there is already progress for it but yeah sure add it

**Comment by Oleksii222** [comment]
Please 🥺🙏 add it I will be thank full

**Comment by khanhduytran0** [comment]
Anyways you could try use another app to map controller to keyboard.

**Comment by Oleksii222** [comment]
For example

**Comment by Oleksii222** [comment]
?

**Comment by OksmaWarez** [comment]
You can use [Octopus](https://play.google.com/store/apps/details?id=com.chaozhuo.gameassistant&hl=lt&gl=US) to map the gamepad controls.

**Comment by Oleksii222** [comment]
I didn't find such an app

**Comment by Oleksii222** [comment]
Thanks for answering though

**Comment by Oleksii222** [comment]
Just like I said thankfull

**Comment by Oleksii222** [comment]
Buttons in launcher not swipe able

**Comment by Oleksii222** [comment]
I tried allredy octopus 🐙

**Comment by Oleksii222** [comment]
Simply put

**Comment by Oleksii222** [comment]
Can not map joystick

**Comment by Oleksii222** [comment]
And it is bugy

**Comment by Oleksii222** [comment]
I also tried odo gamepad mapper a few buttons work and that's it

**Comment by Oleksii222** [comment]
It didn't come out simply put

**Comment by Oleksii222** [comment]
Again thanks very much

**Comment by Mathias-Boulay** [comment]
Closing the issue, as it is a duplicate from many people begging instead of helping.

**Comment by megapro17** [comment]
> Closing the issue, as it is a duplicate from many people begging instead of helping.

and how we can help? where's to do list? what's the problem?
