### ISSUE TITLE
[BUG] <Short description> crash

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5610]
### Describe the bug

Crash

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15877547/latestlog.txt)

### Steps To Reproduce

```markdown
1.run game
2.create new world
3.loading
4.crash
```

### Expected Behavior

+

### Platform

```markdown
- Device model: redmi note 9 pro
- CPU architecture: -
- Android version: 12
- PojavLauncher version: -
```

**Comment by TarikBR** [comment]
Im not sure, but i thin you need to add more memory to the game

`java.lang.OutOfMemoryError: Java heap space`

**Comment by wayxyz89** [comment]
> Im not sure, but i thin you need to add more memory to the game
> 
> `java.lang.OutOfMemoryError: Java heap space`

Thank ITS work
