### ISSUE TITLE
My [BUG] <Short description> 1.21 Fabric Installer Is crash game is no open 

### ISSUE THREAD

**Issue by A-S-Playz** [PojavLauncherTeam/PojavLauncher#5611]
### Describe the bug

MY fabric installer is crashing in Pojav Launcher 1.21 fix that problem all loader crashing fix

### The log file and images/videos

MY fabric installer is crashing in Pojav Launcher 1.21 fix that problem all loader crashing fix

### Steps To Reproduce

```markdown
All loader are crashing
```

### Expected Behavior

MY fabric installer is crashing in Pojav Launcher 1.21 fix that problem all loader crashing fix

### Platform

```markdown
- Device model: Realme 7 6/64G
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: 3.3.3
```

### Anything else?

MY fabric installer is crashing in Pojav Launcher 1.21 fix that problem all loader crashing fix

**Comment by 5ghzx** [comment]
Fill out the template properly.

**Comment by GaucovyAero** [comment]
send log

**Comment by GaucovyAero** [comment]
stale, your pojav is years out of date
