### ISSUE TITLE
[BUG] LAN World

### ISSUE THREAD

**Issue by NDG312** [PojavLauncherTeam/PojavLauncher#5612]
### Describe the bug

Can't see my friend's LAN world even though we're connected to the same wifi (fabric 1.20.1-0.15.11).

- Device model: Redmi Note 12
- CPU architecture: -
- Android version: 14 
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk

**Comment by GaucovyAero** [comment]
duplicate of #5493
