### ISSUE TITLE
Hahaha shsksjha[F-Req] <Short description>

### ISSUE THREAD

**Issue by Ahmedsenseiv1** [PojavLauncherTeam/PojavLauncher#5613]
### Is this request related to a bug?

Hajjhwusbsb

### Describe the request.

Jyataggwmjsnahydbgdb

### Anything else?

Aglapakshsjnnx
Aygwh

**Comment by Ahmedsenseiv1** [comment]
Urt

**Comment by Ahmedsenseiv1** [comment]
Ytr

**Comment by Ahmedsenseiv1** [comment]
Ahmedsenseiv1

**Comment by ThatMG393** [comment]
@GaucovyAero uhm..

**Comment by whal-whales** [comment]
![no way chat](https://github.com/PojavLauncherTeam/PojavLauncher/assets/148692775/120f61b6-a0de-4f2f-aaa4-b4e9ecbfb5a6)

**Comment by Dung1609** [comment]
Broooooooooo

**Comment by moidar5366** [comment]
...

**Comment by zkitefly** [comment]
？

**Comment by ghost** [comment]
Spam detected

**Comment by JuusK** [comment]
same

**Comment by JuusK** [comment]
uihdskahkfdsa

**Comment by JuusK** [comment]
oiuy

**Comment by JuusK** [comment]
kjgh

**Comment by grosioso** [comment]
bro what?

**Comment by ghost** [comment]
Another spam

**Comment by TotallyNotSaeed** [comment]
> ### Is this request related to a bug?
> Hajjhwusbsb
> 
> ### Describe the request.
> Jyataggwmjsnahydbgdb
> 
> ### Anything else?
> Aglapakshsjnnx Aygwh

SPIT IT POOKIE 😝😝😝😝

**Comment by Marshall2439** [comment]
What in the flying fk
