### ISSUE TITLE
Dawn craft crash on the loading screen 

### ISSUE THREAD

**Issue by Dung1609** [PojavLauncherTeam/PojavLauncher#5614]
### Describe the bug

Dawn craft crash on the loading screen 

### The log file and images/videos

[](url)
[latestlog.txt](https://github.com/user-attachments/files/15882875/latestlog.txt)
#Steps To Reproduce
1. Create modpack
2. Search DawnCraft
3. Select DawnCraft 
4. Install DawnCraft 
5. Play DawnCraft 

### Platform

```markdown
- Device model:Redmi note 12t pro
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by ThatMG393** [comment]
Try switching renderers.

**Comment by GaucovyAero** [comment]
your phone does not support create on gl4es, because you dont have a snapdragon
