### ISSUE TITLE
[BUG] black screen on startup 

### ISSUE THREAD

**Issue by JuusK** [PojavLauncherTeam/PojavLauncher#5616]
### Describe the bug

Using fabric and any mods, my game wont open because it doesnt have permission to access the files

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15885164/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install fabric
3. Install any mod
4. Open the game
```

### Expected Behavior

it should open the game with the mods

### Platform

```markdown
- Device model: Redmi Note 12 Pro 5G
- CPU architecture: idk
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try using a different file manager to move the files maybe, this is not a pojav issue

**Comment by JuusK** [comment]
i tried different file managers and it still doesnt work
