### ISSUE TITLE
JRE17-supported versions crashes

### ISSUE THREAD

**Issue by grosioso** [PojavLauncherTeam/PojavLauncher#5617]
### Describe the bug

I got pojavlauncher from the github actions buld and when I use JRE17 as my runtime and play JRE17-supported versions, it won't work. For example, when I play 1.17.1 it gives me an "application/game exited with code -1" error. I don't know why.

### The log file and images/videos

![Screenshot_20240618-141641_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/4729d2b0-e51d-45c1-a331-9f69d30a7de7)

![Screenshot_20240618-141607_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/87e61fd0-1434-41c9-9eb7-a0451c38dee4)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher normally
```

### Expected Behavior

I expect to run normally

### Platform

```markdown
- Device model: Samsung Galaxy A12 (A125F)
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest github actions build
```

**Comment by ThatMG393** [comment]
Please upload the `latestlog.txt` file

**Comment by grosioso** [comment]
>  Please upload the `latestlog.txt` file

sorry
![latestlog.txt](https://github.com/user-attachments/files/15886064/latestlog.txt)

**Comment by grosioso** [comment]
it's been a day...
