### ISSUE TITLE
Need help about black screen

### ISSUE THREAD

**Issue by Oshnik5** [PojavLauncherTeam/PojavLauncher#5619]
### Describe the bug

I also have black screen issue which is not in my four year old phone but in my two year old phone.
Modpacks tested
Chemical exchange 
Feed the Factory
No options.txt file change
Opengl renderer (zink crashed my game )
Something I know is optifine and any library mod with my gou is causing this thing but how should I identify it
Detailed:
I launched minecraft modpack, my friend launched same modpack. We both used optifine. The I created a world and started lan but then the game of my friend loaded(identified by music) but It was black screen. We tried clicking randomly there but it seemed like the button is pressed (identified by sound).
Modlist:
xaerominimap_core, xaeroworldmap_core, foamfixcore, bspkrscore, treecapitator, akashictome, autoreglib, base, bdlib, betterboilers, betterbuilderswands, bookshelf, buildcraftcore, buildcraftlib, buildcraftfactory, capsule, carryon, chameleon, chisel, clochecall, codechickenlib, cofhcore, cofhworld, commoncapabilities, contenttweaker, controlling, craftingstation, ctgui, crafttweaker, crafttweakerjei, ctm, cttinycoal, custommainmenu, cyclopscore, deepmoblearning, defaultworldgenerator-port, diethopper, ding, elevatorid, endercore, enderio, enderiobase, enderioconduits, enderiopowertools, enderioendergy, facadepainter, f0-resources, fastfurnace, fastleafdecay, foamfix, ftbbackups, ftblib, ftbquests, ftbutilities, gamestages, guideapi, igwmod, immersivepetroleum, immersiveposts, incontrol, integratedcrafting, integrateddynamics, integrateddynamicscompat, integratedterminals, integratedterminalscompat, integratedtunnels, integratedtunnelscompat, inventorytweaks, ironchest, itemfilters, itemstages, jei, jecalculation, justenoughpetroleum, logisticalautomation, logisticspipes, lostcities, modtweaker, modularmachinery, moreoverlays, morphtool, mousetweaks, mtlib, multiblockstages, nonetherportals, nuclearcraft, patchouli, placebo, pressure, rad, recipestages, redstoneflux, resourceloader, signals, storagenetwork, solarflux, storagedrawers, superfactorymanager, supersoundmuffler, theoneprobe, thermalexpansion, thermalfoundation, toastcontrol, travellersboots, unidict, wanionlib, xaerominimap, xaeroworldmap, industrialwires, immersiveengineering

### The log file and images/videos

Ok

### Steps To Reproduce

```markdown
Can be done only in the devices with particular GPU(s)
```

### Expected Behavior

My screen not to be covered by black screen

### Platform

```markdown
- Device model: Vivo
- CPU architecture: idk (arm64 has higher chances)
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

Not anything else

**Comment by TarikBR** [comment]
Send latestlog.txt

**Comment by GaucovyAero** [comment]
thats kinda normal, not all devices support all renderers
