### ISSUE TITLE
Full Modpack  import/export feature 

### ISSUE THREAD

**Issue by Vanilama-modded** [PojavLauncherTeam/PojavLauncher#5620]
### Is this request related to a bug?

Every time i want to import a modpack that i made myself on my pc i need to extract it and copy it to different locations and create folders and so on.

### Describe the request.

I wish there was a feature where you can directly import the modpack file (.zip/.mrpack/ etc.) In the launcher itself so that i dont need to make a profile first wirh correct modloader version and than need to copy all the files one by one to specific locations just to play them. If this feature somehow already exists and I'm just to stupid to find it than i apologize for the request post but i don't think it exists.  •෴•

### Anything else?

I'm to stupid to do all the stuff properly and always run into problems with getting the modpack to work without missing half of the file's.

**Comment by TarikBR** [comment]
Duplicate #5555

**Comment by Vanilama-modded** [comment]
> Duplicate #5555

Oh ok

**Comment by GaucovyAero** [comment]
exporting is very much out of scope as of now, because that would mean implementing stuff like the PrismLauncher directory structure
