### ISSUE TITLE
Please artdell can you add an option to put skins in please add an option to put skins in pojavlauncher in pojavlauncher?

### ISSUE THREAD

**Issue by Daviliraushs** [PojavLauncherTeam/PojavLauncher#5622]
### Is this request related to a bug?

please add an option to put skins in pojavlauncher please add an option to put skins in pojavlauncher 

### Describe the request.

please add an option to put skins in pojavlauncher please add an option to put skins in pojavlauncher 

### Anything else?

please add an option to put skins in pojavlauncher please add an option to put skins in pojavlauncher

**Comment by ImNotTheChiku35** [comment]
use CustomSkinLoader ;)

**Comment by Daviliraushs** [comment]
Very thanks bro you it's very cool

Em ter., 18 de jun. de 2024 11:49 PM, ImNotTheChiku35 <
***@***.***> escreveu:

**Comment by Daviliraushs** [comment]
You it's very cool bro very thanks by updates of pojavlauncher

Em qui., 20 de jun. de 2024 8:12 AM, GaucovyAero ***@***.***>
escreveu:
