### ISSUE TITLE
[BUG] 1.21 fabric won't launch with favorite mods 

### ISSUE THREAD

**Issue by Samikhaya** [PojavLauncherTeam/PojavLauncher#5623]
### Describe the bug

Any mods prevent the 1.21 fabric
 from starting and crash the game 

### The log file and images/videos

![Screenshot_20240614_033043_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172678224/c653c036-0d7e-4aa5-86b4-9edf3e6705bc)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Start Mincraft 1.21 Fabric
3.Crash the game
```

### Expected Behavior

I want everything to work 

### Platform

```markdown
- Device model: Samsung
- CPU architecture:  arm64
- Android version:  11
- PojavLauncher version: dahlia-20230813-5e8842b-v3_openjdk
```

### Anything else?

No

**Comment by ThatMG393** [comment]
What are "favorite mods", can you maybe list them? Can you also send `latestlog.txt`?

**Comment by GaucovyAero** [comment]
stale issue
