### ISSUE TITLE
[BUG] Error Modpack DawnCraft

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5624]
### Describe the bug

Modpack DawnCraft Exit Code 1 When Launching

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15897470/latestlog.txt)

### Steps To Reproduce

```markdown
Install Modpack DawnCraft 1.18
```

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?
There isn't any

**Comment by artdeell** [comment]
You have a mod conflict

**Comment by Dilen0001** [comment]
How to handle it

**Comment by GaucovyAero** [comment]
remove patchouli
