### ISSUE TITLE
[BUG] Forge 1.20.4 crashes with code -1 when using mods

### ISSUE THREAD

**Issue by Vini158916** [PojavLauncherTeam/PojavLauncher#5626]
### Describe the bug

I play Minecraft with mods, and when I open Forge 1.20.4, the game literally crashes with code -1.  Forge works normally (Only in 49.0.3) but when I add mods the game crashes, it only crashes in Pojavlauncher, on PC it works normally

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15902486/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Launch Forge 1.20.4 - Forge version: 49.0.3
3. Wait for the game load
```

### Expected Behavior

Expected the game loads normally

### Platform

```markdown
- Device model: Samsung Galaxy S20 FE 5G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

The game works normally with no mods, it only crashes with -1 code when using mods

**Comment by TarikBR** [comment]
The mods you are trying to use, needs a more recent forge version

**Comment by Vini158916** [comment]
But I cant use another forge versions, only works Forge 49.0.3, above this version the game crashes with code 1

**Comment by ghost** [comment]
You can use old version of mods you use

**Comment by TarikBR** [comment]
> But I cant use another forge versions, only works Forge 49.0.3, above this version the game crashes with code 1

Send latestlog.txt when you use higher version of forge

**Comment by Vini158916** [comment]
Here' s it
[latestlog.txt](https://github.com/user-attachments/files/15904308/latestlog.txt)
I used latest version of Forge 1.20.4 - Forge 49.1.0

**Comment by TarikBR** [comment]
> Here' s it [latestlog.txt](https://github.com/user-attachments/files/15904308/latestlog.txt) I used latest version of Forge 1.20.4 - Forge 49.1.0

Try pojav from github actions, prefer for v3_openjdk builds one, like this https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9570322481

**Comment by Vini158916** [comment]
It worked, thank you! I think it was the version because I downloaded pojav from Play Store
