### ISSUE TITLE
Add the option to put sounds into the app's UI buttons

### ISSUE THREAD

**Issue by grosioso** [PojavLauncherTeam/PojavLauncher#5628]
### Is this request related to a bug?

no, but putting sound into buttons would be a great idea

### Describe the request.

(Sorry for the bad english)

![Screenshot_20240619-191701_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/6bfefcb6-ada8-47b1-af33-73568a3bf839)

add an option that any button you click in the app it plays the minecraft button click sound

**Comment by ghost** [comment]
WHY ARE YOU NOT PLAN the F_requesd
