### ISSUE TITLE
[BUG] 1.20.6 Fabulously Optimized crash

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5629]
### Describe the bug

When i launch Fabulously Optimized for 1.20.6 it crashes when i create/load world with a "saving world" before it

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/15903776/latest.log)

### Steps To Reproduce

```markdown
1. Launch Fabulously Optimized 1.20.6
2. Create/load world
```

### Expected Behavior

To load/create the world successfully and playable

### Platform

```markdown
- Device model: galaxy A315
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

No

**Comment by artdeell** [comment]
Sodium is not supported
