### ISSUE TITLE
No Escape button on keyboard

### ISSUE THREAD

**Issue by Preloading** [PojavLauncherTeam/PojavLauncher#563]
Uhm.... this seems like a dumb question but on my phone (Samsung Galaxy S6 running android 7.0 +rooted) it doesn't have an escape button or an enter button.... Sorry if my question is dumb!

**Comment by khanhduytran0** [comment]
Are you too lazy to add them for yourself?

**Comment by khanhduytran0** [comment]
(Go to custom controls)

**Comment by Preloading** [comment]
oh srry
