### ISSUE TITLE
Controls changed

### ISSUE THREAD

**Issue by subbugarilokesh** [PojavLauncherTeam/PojavLauncher#5630]
### Describe the bug

My pojav launcher right and left controls not working properly as it used to be in 1.20 ,I recently downloaded a new verson of pojav launcher from GitHub because my Java 1.21 was crashing ,I installed Java 21 my phone ,aarm64x.the problem is like ,the virtual mouse ingame does not click in the crafting table to craft,I have to long press it to just craft one e.g bread,again I have to keep in my inventory and again craft one,it takes so much long time to craft etc.my mobile ,realme 6 64gb 6gb ram

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Lol
```

### Expected Behavior

Dum

### Platform

```markdown
- Device model: realme 6
- CPU architecture: aarm64
- Android version: 11
- PojavLauncher version: 20240531-bdc7f33-v3_openjdk
```

### Anything else?

No

**Comment by TarikBR** [comment]
Download from v3_openjdk branch, like this one https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9570322481

**Comment by GaucovyAero** [comment]
he did, the mouse input is broken as usual

**Comment by subbugarilokesh** [comment]
So when are you going to fix it ,because if I downgrade the verson ,I can't
play 1.21,please tell when are you going to fix it

**Comment by GaucovyAero** [comment]
your testing can perhaps help if you join the pojav discord and ping me in #community-development

**Comment by GaucovyAero** [comment]
should be fixed in the latest play store build
