### ISSUE TITLE
[F-Req] <Just a Request>

### ISSUE THREAD

**Issue by JellyPacMan9283** [PojavLauncherTeam/PojavLauncher#5631]
### Is this request related to a bug?

Not really, Just a request asking for a little bit of performance tweaks in ur next release

### Describe the request.

Just wanting some optimizations. On PC Pojav doesn't really perform well when compared to other launchers so that's why I made this Req

**Comment by artdeell** [comment]
Pojav is not intended to be ran on PC, as it uses quite a bit of translation layers intended for compatibility with Android

**Comment by Marshall2439** [comment]
Why would anyone intentionally use java minecraft lancher for mobile on pc? Why not just play official version?

**Comment by kiokori-git** [comment]
why would you run pojav on a PC

**Comment by GaucovyAero** [comment]
if you run it on pc, its gonna run thru a bunch of translation layers, hence why the performance is worse (we cant do anything about this)
