### ISSUE TITLE
[BUG] visual glitches in zink renderer on exynos 2200

### ISSUE THREAD

**Issue by MochaSteve256** [PojavLauncherTeam/PojavLauncher#5632]
### Describe the bug

Visual glitches when starting game with zink rendering backend as seen in pictures. Zink is great tho bc i can load standard BSL shaders with that rendering backend

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15916993/latestlog.txt)
![Screenshot_20240620_175411_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78016786/06bee214-c876-4f90-b9fe-a64319ef7795)
![Screenshot_20240620_175052_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78016786/f63e6dde-7b3f-4e04-a39c-fc4c096fc9c8)
![Screenshot_20240620_175034_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78016786/fce7b14b-34ea-4c55-b84a-e614210cb1a7)
![Screenshot_20240620_174951_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78016786/776b82b9-bd4f-4051-95e4-70720d5a646c)
![Screenshot_20240620_174945_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/78016786/4f09a6f9-ade4-464d-aaf3-8ef8c6bb8904)

### Steps To Reproduce

```markdown
Get samsung s22 ultra
Get pojav
Get optifine 1.20.4
Set zink renderer
Experience weird glitched game
```

### Expected Behavior

Just normal looking game.

### Platform

```markdown
- Device model: samsung s22 ultra, exynos variant
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: latent from google play
```

**Comment by GaucovyAero** [comment]
zink does not support all gpus equally, this is not a pojav issue and zink is not maintained by pojav developers
this is very likely some sort of incompatibility with your device driver that might not ever be fixed in zink

**Comment by MochaSteve256** [comment]
Duplicate of #5180.
