### ISSUE TITLE
Code 1

### ISSUE THREAD

**Issue by SahilArafat** [PojavLauncherTeam/PojavLauncher#5636]
### Describe the bug

When I click to play, it crashed and shows -

Application/Game exited with code 1... 

Then when I open latestlog.txt it shows - 

error:could not create the Java Virtual Machine.
error:A fatal exception is occurred.Program will exit. 

### The log file and images/videos

![IMG_20240621_071450](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173423011/d026232c-b87f-46ae-b756-d87f4d2ffcb1)
![IMG_20240621_071304](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173423011/f2257be5-1577-456d-b36c-4fcc49b31338)

### Steps To Reproduce

```markdown
When click to Play.
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model: V2310
- CPU architecture: don’t know 
- Android version: 14
- PojavLauncher version:edelweiss-20230928-9484dOc-v3_openjdk
```

### Anything else?

Nothing

**Comment by TarikBR** [comment]
Remove custom jvm args
