### ISSUE TITLE
[BUG] <Short description>djjdndnd

### ISSUE THREAD

**Issue by Heepvp** [PojavLauncherTeam/PojavLauncher#5637]
### Describe the bug

Bdhdhdjdj
Bsnsns

### The log file and images/videos

Sgbssb

### Steps To Reproduce

```markdown
Bsbsns
```

### Expected Behavior

Sbsbsbsn

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by 5ghzx** [comment]
What a productive and useful issue. This is an issue that should be fixed this very second

**Comment by Heepvp** [comment]
N consigo logar

**Comment by Heepvp** [comment]
Quero jogar

**Comment by TarikBR** [comment]
> N consigo logar

Você precisa ter uma conta de minecraft original de PC, a que vem a versão java, o minecraft da playstore não conta para ser considerado uma conta original.
