### ISSUE TITLE
[BUG] <не запускается чистая  1.21>

### ISSUE THREAD

**Issue by Neytral77** [PojavLauncherTeam/PojavLauncher#5638]
### Describe the bug

Обновил через Google play  лаунчер, выбрал версию 1.21. При запуске происходит сбой с кодом 1
Версия чистая, без модов, надстроек и прочего.
По умолчанию  java 21,  holy.
Пробовал разные варианты с памятью, визуализатором, удалял папки библиотек и версии и устанавливал заново, все бесполезно. Версия 1.20.6 прекрасно запускается и играет., а всё,  что касается 1.21 разные снаршоты, релиз - сбой запуска. Прошу помощи!!!

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15923629/latestlog.txt)

### Steps To Reproduce

```markdown
1. Запускаем pojavlauncher 
2. Выбираем версию 1.21
3. Запускаем
4. Видим окно сбоя с кодом 1
```

### Expected Behavior

Ожидаемо играть в долгожданную версию 1.21

### Platform

```markdown
- Device model: samsung SM-G998B
- CPU architecture: arm64
- Android version: 14
Version UI: One UI 6.0
- PojavLauncher version: 
Последняя с Google play 
edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by TarikBR** [comment]
Outdated PojavLauncher, update from play store or github actions

**Comment by Neytral77** [comment]
Так я из гугл плай и обновлял... 
Подскажите, какой мне тогда установить, ссылку на скачивание, подскажите

**Comment by Neytral77** [comment]
Обновил из гугл плай, исчезла учётная запись и теперь я вообще не могу запустить майнкрафт

**Comment by savvacorgi** [comment]
> Обновил из гугл плай, исчезла учётная запись и теперь я вообще не могу запустить майнкрафт

Try it https://github.com/PojavLauncherTeam/PojavLauncher/actions/workflows/android.yml There are new builds

**Comment by Neytral77** [comment]
Спасибо) 
Я скачал исходный код в зип архиве новой версии - Фоксглав. Но и что с ним делать и сто со сборка и делать я не знаю. К сожалению... был бы файл апк, это я знаю, установка...  а что с другими делать не знаю.. помогите, пожалуйста,  без майнкрафта и жизнь не жизнь)

**Comment by Neytral77** [comment]
В сборке есть отладка, файл в 150 мб.. я его запускал. Ничего не изменилось.. лаунчер говорит, что сохранённых учетных записей нет. А новую не создает.  При попытки входа через учётную запись майкрософт пишет, что нет лицензии на майнкрафт и вылетает

**Comment by Neytral77** [comment]
Закрыто, всем спасибо
