### ISSUE TITLE
[BUG] Renderer Zink Error

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5639]
### Describe the bug

Render Zink Crash Code -1 When Launching

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15926032/latestlog.txt)

### Steps To Reproduce

```markdown
Install Minecraft Version 1.21
```

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?
There isn't any

**Comment by Mario191209** [comment]
Mali moment

**Comment by Dilen0001** [comment]
How to handle it

**Comment by Marshall2439** [comment]
Why do you want to use zink anyways?

**Comment by Dilen0001** [comment]
Because you want to use shaders and mods

**Comment by Marshall2439** [comment]
Option 1 get better phone and deal with issues
Option 2 get a pc with almost zero issues

**Comment by GaucovyAero** [comment]
your gpu is not supported
