### ISSUE TITLE
[BUG] Left and right mouse clicks don't work

### ISSUE THREAD

**Issue by Dimon245** [PojavLauncherTeam/PojavLauncher#564]
So I've had this issue before and I downloaded the very last build (which even has "mouse support" in it) in hopes it'd get fixed, but sadly it hasn't. Compared to before, you could left click (still no right click), but it would get stuck and you would have to use the "back" button on your phone/mouse to fix it. Now you can't left click at all and right click doesn't serve the function of the "back" button anymore, so it's basically useless. But the left + right click kinda works in the crafting menu now.
Note: when you try to map right click in the settings it counts as a "left mouse" button for some reason.
Mouse used is Microsoft BT Mouse 3600.
[Prev issue](https://github.com/PojavLauncherTeam/PojavLauncher/issues/513)

**Comment by Dimon245** [comment]
Forgot to say that menu's (and GUI's) only update when you use left click, i.e mouse pointer stopped working in the recent builds, apparently.

**Comment by artdeell** [comment]
It is very sad that I don't have a real mouse to debug on. I'll try to do something though

**Comment by Dimon245** [comment]
Thank you very much for your hard work, it's really appreciated

**Comment by artdeell** [comment]
I see, I checked my commit and i definitely flipped the buttons

**Comment by artdeell** [comment]
Please try the latest

**Comment by Dimon245** [comment]
I tried it just now and it doesn't make a difference, but now you can't actually craft with right click while holding left click. Yeah, left and right click still don't work

**Comment by artdeell** [comment]
But do they do something ingame?

**Comment by artdeell** [comment]
(not in GUIs)

**Comment by Dimon245** [comment]
No, sadly they don't

**Comment by artdeell** [comment]
All mouse buttons (including tertiary (middle) button) should work im both GUIs and game. Try the latest.

**Comment by Dimon245** [comment]
Oh, wow it actually works everywhere now! Magnificent job, artdeel, tysvm!!

**Comment by artdeell** [comment]
It was a huge pain doe, i had to hard reset my  PC every 5 or so minutes to hop between Android and Debian, but now, the nightmare is over

**Comment by Dimon245** [comment]
Oh, sorry, dude. I did imagine it very troublesome, so I'm extra appreciative of your work. I guess the new bugs I reported are going to have to wait then. 
Take a rest from these mouse/keyboard related issues, you deserved it :3
Edit: you're a real MVP

> It was a huge pain doe, i had to hard reset my PC every 5 or so minutes to hop between Android and Debian, but now, the nightmare is over
