### ISSUE TITLE
auto-updater feature on pojavlauncher (for github actions builds)

### ISSUE THREAD

**Issue by grosioso** [PojavLauncherTeam/PojavLauncher#5640]
### Is this request related to a bug?

no

### Describe the request.

add an auto-updater to pojavlauncher

here's how it works:

 ● the auto-updater is used to check for latest updates on pojavlauncher (the app version, not the game)
 ● it will automaticly check for updates through the github actions releases.
 ● this might or might not be useful for people who doesn't want to update pojav using its apk files

### Anything else?

if you want, you can release the feature on the play store version in the future.

**Comment by ghost** [comment]
Developers Need to consider it

**Comment by grosioso** [comment]
> Developers Need to consider it

exactly

**Comment by 5ghzx** [comment]
I believe this would be low priority over actual issues.

**Comment by ghost** [comment]
> I believe this would be low priority over actual issues.

I don't think so

**Comment by grosioso** [comment]
> I believe this would be low priority over actual issues.

you might be right, should I close it?

**Comment by grosioso** [comment]
> I believe this would be low priority over actual issues.

or actually no.

**Comment by kasrarouhi** [comment]
No. Be patient to developer leave comment. Sorry for bad english

**Comment by ghost** [comment]
> > I believe this would be low priority over actual issues.
> 
> you might be right, should I close it?

No. Be patient to developer leave comment. Sorry for bad english

**Comment by deivpaukst** [comment]
Also attaching the release apk to the releases on Github could be considered. Then people who use apps like Obtainium could use this to get and update the app directly from the Github releases page.

**Comment by noone-git** [comment]
Former Pojav moderator here

How about you guys subscribe to [Pojav's Patreon]( https://www.patreon.com/pojavlauncher) instead? You'll get exclusive access to Play Store internal testing and GitHub Actions builds will get pushed there, so you don't have to download it from Actions. These developers spend their free time improving the launcher, so supporting their hard work is much better than asking for a pointless feature, don’t you think?

**Comment by grosioso** [comment]
> Former Pojav moderator here
> 
> How about you guys subscribe to [Pojav's Patreon]( https://www.patreon.com/pojavlauncher) instead? You'll get exclusive access to Play Store internal testing and GitHub Actions builds will get pushed there, so you don't have to download it from Actions. These developers spend their free time improving the launcher, so supporting their hard work is much better than asking for a pointless feature, don’t you think?

I don't use patreon but good advice

**Comment by deivpaukst** [comment]
> These developers spend their free time improving the launcher, so supporting their hard work is much better than asking for a pointless feature, don’t you think?

You may find it pointless, however I don't think it is if people are requesting it. 
Also even if I was subscribed to the Patreon, which I encourage anyone who likes the project to do so if they can, I and other people who prefer using Google services as little as possible would still not have an alternative to get updates in a convenient manner.

**Comment by noone-git** [comment]
> I and other people who prefer using Google services as little as possible would still not have an alternative to get updates in a convenient manner.

...which is probably only around 2% of the entire launcher user base (excluding countries where Play Services aren't available, like China). Most users are kids with mid-range phones who stumbled upon the launcher through random YouTube videos. Let's be real, hardly anyone is clamoring for this feature, I've only seen two or three people mention it. The developers have limited time and resources, so they prioritize what really matters instead of something so minor. This feature likely isn't on their radar and won't be added anytime soon. Especially if they already offer a similar capability through Patreon. If you're keen on it, you can always fork the project and develop your own auto updater.

**Comment by deivpaukst** [comment]
Sure, but how about attaching the apk to the releases. That does not need a new feature to be developed and would provide a stable build version for everyone, even people without Github accounts.
In fact it seems this used to be a feature, even the readme still mentions it, however it was randomly abandoned at some point.
And as a final note, would you prefer people not ask for features or report bugs? This is an issue tracker and it is up to the maintainers to decide what they want to do with each issue. As a user, I report things that I think are broken or could need improving, whether anything actually needs changing is up to them.

**Comment by artdeell** [comment]
We prefer to not get overwhelmed with stuff that is not of immediate concern, like, for example, an updater. If you want automatic updates, we offer gplay internal testing subscription to patrons which receives latest action builds as updates

**Comment by GaucovyAero** [comment]
also a lot of the time you would not want to update cause action builds tend to break stuff, its better this way imo

**Comment by deivpaukst** [comment]
What do you two think about attaching the apk that goes out to GPlay to the releases of this Github repo?
If you prefer keeping things as is, that's perfectly fine.
I found the app by helping someone set up Altstore on their IPhone and thought it was strange that there was no F-droid version or release builds on github, so I thought I might ask about the builds on Github, as I saw that an F-droid release wasn't feasible.

**Comment by GaucovyAero** [comment]
why not just use apkmirror?

**Comment by grosioso** [comment]
> why not just use apkmirror?

yeah, good idea. I will think about it

**Comment by deivpaukst** [comment]
I use [Obtainium](https://github.com/ImranR98/Obtainium) to get updates for most of my apps from all sorts of different sources and as per request of the owners of Apkmirror, the app can only track version changes, but not directly download from there.

If this is a lot of work, that's fine, it would just be a nice to have.
