### ISSUE TITLE
[BUG] <FPS Problem and Crashing>

### ISSUE THREAD

**Issue by XavierErrorLog** [PojavLauncherTeam/PojavLauncher#5642]
### Describe the bug

Hello to whoever is reading this, I have a problem with forge 1.12.2 Vanilla & 1.12.2-14.23.5.2860. I just downloaded Pojavlauncher on my Lenovo Duet and it was working perfectly fine a few months ago now it's pretty laggy and the FPS is really that good. I'm use to getting 70-80Fps normally to now getting 30-56Fps without the random lag spikes that happen when night falls. Other than vanilla Forge is kinda unplayable it crashes alot and i Installed a ton of FPS boosting mods and it still is giving me a hard time at first I just assume it was Mcheli but nah when just removing the one mod and just having Optifine on it still was not giving good FPS i dunno whats happening but might need an update for chrome users..

### The log file and images/videos

[optionsof.txt](https://github.com/user-attachments/files/15930634/optionsof.txt)
[options.txt](https://github.com/user-attachments/files/15930636/options.txt)
[crash-2024-06-21_11.07.28-server.txt](https://github.com/user-attachments/files/15930637/crash-2024-06-21_11.07.28-server.txt)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Wait
3. Load Game
4. Decent FPS
5. Lag Spike
6. Few Minutes later Crash x_x
```

### Expected Behavior

- [ Start Game }
- [ Wait ]
- [ Loads world ]
- [Plays game for 89 hours without lag spikes for no reason ]

### Platform

```markdown
- Device model: Lenovo Chromebook Duet {kukui}
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version:Foxglove (Playstore June 21st Update )
```

**Comment by ghost** [comment]
Attention to @GaucovyAero says pojav not for pc. And you can optimize settings like turn on alternate surface rendering in your android phone really effective

**Comment by 5ghzx** [comment]
No, this is Chromebook, not PC. Would general FPS boosting tips apply?

**Comment by ghost** [comment]
But chrome book uses pc gpus like geforge and . . .not adreno or . . .

**Comment by 5ghzx** [comment]
No geforce here, although intel gpus may be the difference. It worked before though.

**Comment by ghost** [comment]
Maybe but chromebook not use android gpu and for this pojav not very compatible with chromebook

**Comment by 5ghzx** [comment]
do android devices use a special GPU? Doesn't it vary?

**Comment by XavierErrorLog** [comment]
Hmm I think it's compatible to be honest it was working great not to long ago
