### ISSUE TITLE
[F-Req] <Logs>

### ISSUE THREAD

**Issue by JellyPacMan9283** [PojavLauncherTeam/PojavLauncher#5644]
### Is this request related to a bug?

Not a problem but I don't normally look through logs nor do most people do.

### Describe the request.

My request is that u add an option to turn off the logs and not generate logs.

**Comment by 5ghzx** [comment]
Is this because mobile devices have limited space? If your logs are taking that much space there is likely an error you should fix.

**Comment by frdude** [comment]
Why though? If you encounter an issue with either modded or vanilla minecraft without logs, you won't be able to identify the issue, nor can you get help from others.

**Comment by ghost** [comment]
He says add a option to turn on or off this option not delete logs

**Comment by ghost** [comment]
But i researched and turn off log generate can improve performance

**Comment by JellyPacMan9283** [comment]
> Why though? If you encounter an issue with either modded or vanilla minecraft without logs, you won't be able to identify the issue, nor can you get help from others.

Just turn on logs back when u experience an issue

**Comment by 5ghzx** [comment]
Correct me if i'm wrong, but wouldn't this take a long time to implement for almost entirely useless gains?

**Comment by JellyPacMan9283** [comment]
> Correct me if i'm wrong, but wouldn't this take a long time to implement for almost entirely useless gains?

No useless gains, U get more performance and then half of ur storage would be free.

**Comment by GaucovyAero** [comment]
no
