### ISSUE TITLE
[BUG] When launching the latest version of Forge, Application/Game exits with error code 1.

### ISSUE THREAD

**Issue by user96s-stuff** [PojavLauncherTeam/PojavLauncher#5645]
### Describe the bug

Version 1.20.1-forge-47.3.1 of Minecraft forge will crash with error code 1.

### The log file and images/videos

Failed to create /data/.cache for shader cache (Permission denied)---disabling.
--------- beginning with launcher debug
Info: Launcher version: foxglove-20240621-332de88-v3_openjdk
Info: Architecture: x86_64
Info: Device model: Google coral
Info: API version: 28
Info: Selected Minecraft version: 1.20.1-forge-47.3.1
Info: Custom Java arguments: "-Xmx3G -Xms3G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10"
--------- beginning of system

--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1366
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-FUOVX_qMH37wp4X_Ge8JPQ==/lib/x86_64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-FUOVX_qMH37wp4X_Ge8JPQ==/lib/x86_64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=768
Initialising gl4es
v1.1.5 built on May  4 2024 09:58:07
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClientActiveTexture is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glVertexPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormalPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColorPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glEnableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDisableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glShadeModel is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFunc is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLogicOp is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMatrixMode is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadIdentity is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSize is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFuncx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearColorx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearDepthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4ub is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDepthRangex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetFixedv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLineWidthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawArrays is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawElements is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthof is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthox is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizePointerOES is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPolygonOffsetx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPopMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPushMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glSampleCoveragex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvi is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatex is NULL
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
high precision float in fragment shader available and used
Extension GL_EXT_frag_depth  detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 32
Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Intel Open Source Technology Center
GLSL 300 es supported
GLSL 310 es supported and used
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClientActiveTexture is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glVertexPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormalPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColorPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glEnableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDisableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glShadeModel is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFunc is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLogicOp is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMatrixMode is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadIdentity is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSize is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFuncx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearColorx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearDepthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4ub is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDepthRangex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetFixedv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLineWidthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawArrays is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawElements is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthof is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthox is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizePointerOES is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPolygonOffsetx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPopMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPushMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glSampleCoveragex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvi is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatex is NULL
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  ( 2865): dlopen libgl4es_114.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  ( 2865): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success
I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  ( 2865): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  ( 2865): dlopen /data/app/net.kdt.pojavlaunch-FUOVX_qMH37wp4X_Ge8JPQ==/lib/x86_64/libopenal.so success

I/jrelog  ( 2865): Done processing args
I/jrelog  ( 2865): Found JLI lib
I/jrelog  ( 2865): Calling JLI_Launch

Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Install & Run Forge 1.20.1-forge-47.3.1 (latest, I believe).
3. Get error code 1.
```

### Expected Behavior

Run 1.20.1-forge-47.3.1 properly.

### Platform

```markdown
- Device model: Acer Spin 11 Chromebook (or "Google Coral" as mentioned in latestlog.txt")
- CPU architecture: x86_64
- Android version: 9.0
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

It would download game files before attempting to run Minecraft.

![Screenshot 2024-06-21 1 50 29 PM](https://github.com/PojavLauncherTeam/PojavLauncher/assets/163361877/70ac1d52-8ffc-4af1-8bb9-b4f40309a3dd)

**Comment by TarikBR** [comment]
Remove custom jvm args

**Comment by user96s-stuff** [comment]
I uninstalled the game, thinking it would work (there were jvm args) after I reinstalled it, but on reinstall there are no jvm args, and it still crashes.

**Comment by U53R-96** [comment]
Thanks though!

**Comment by TarikBR** [comment]
> I uninstalled the game, thinking it would work (there were jvm args) after I reinstalled it, but on reinstall there are no jvm args, and it still crashes.

send another latestlog.txt

**Comment by user96s-stuff** [comment]
I'll do it later, busy with something right now. Just wanted to check in and see if a response was made. I will edit this reply with latestlog.txt.

*Edit: now it works, just had to downgrade forge. Thanks for your help!
