### ISSUE TITLE
(gl4es extra) PowerVR GM9446 blackout

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5646]
### Describe the bug

This morning I update my pojavlaucher to the lastest version every thing is ok when I start the game and join my server As the title says everything is black I also created a world and tried but it's still black

### The log file and images/videos

![Screenshot_2024-06-22-06-41-25-45_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139622169/d35ff367-f5ba-4c60-b937-72e6e8f7feb4)
![Screenshot_2024-06-22-06-41-19-36_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139622169/a6170fad-622b-4096-af38-ce1f430dd00c)

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I expect the game work the same as last version but add some new features 

### Platform

```markdown
- Device model: Oppo Reno 3
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: 
Latest version on gg play
```

**Comment by 5ghzx** [comment]
try latest github actions build

**Comment by Hoanpojavlauncher** [comment]
> try latest github actions build
> 

Yes

**Comment by Legna1104** [comment]
A mi usando el único renderizado con el que me va bien se me reinicia el celular

**Comment by ALEX826762** [comment]
i have the sam thing in lobby and the game

**Comment by GaucovyAero** [comment]
new powervr issue i guess? PowerVR GM9446
try getting the methane mod or some sort of fullbright to see if it helps you

**Comment by GaucovyAero** [comment]
also happens on PVR GE8320

**Comment by GaucovyAero** [comment]
@Hoanpojavlauncher 

heres the old workaround, it might help you if it works
**you dont have to do the hit color thing if you dont have red mobs**
also maybe if you can find another hit color mod for fabric that isnt so sussy use that instead

[powervr_ge8320_workaround.txt](https://github.com/user-attachments/files/15993022/powervr_ge8320_workaround.txt)

**Comment by hiimabignoobwihenolive** [comment]
Didn't last pojav update fix blackout for powervr? Did we just go back full circle? Maybe you deleted the fix for blackout but it's quite unlikely (this is what im talking about #4752)

**Comment by hiimabignoobwihenolive** [comment]
Will there be a hot fix? Or we will have to downgrade until its fixed?

**Comment by GaucovyAero** [comment]
there might be a hotfix but no etas, the devs seem to be busy

**Comment by hiimabignoobwihenolive** [comment]
> there might be a hotfix but no etas, the devs seem to be busy

I have a question. what is the latest github release that doesn't have this problem?

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
