### ISSUE TITLE
I cant use mouse in pojav after latest update

### ISSUE THREAD

**Issue by GreatArman** [PojavLauncherTeam/PojavLauncher#5648]
### Describe the bug

I cant move mouse on pojav if i move my mouse connected with usb hub in mobile if i move mouse the virtual mouse of pojav turns on if i turn off virtual mouse in pojav and move my real one than also the virtual mouse turns on and again and again please help me solve this i was freely playing with my external real mouse yesterday but after my game was auto updated my real mouse is not working 

### The log file and images/videos

U

### Steps To Reproduce

```markdown
Huh
```

### Expected Behavior

I expect my mouse to work in pojav or pojav have to bring keyboard and mouse option in pojav menu

### Platform

```markdown
- Device model:Realme pad  
- CPU architecture: idk 
- Android version: 11
- PojavLauncher version: idk it's new updated one today
```

### Anything else?

*Plznhelp me solve

**Comment by GreatArman** [comment]
Help me solve it

**Comment by Bepper00** [comment]
I also experience the same exact thing after I updated my pojavlauncher, please resolve this issue as soon as possible

**Comment by jhosep3** [comment]
tambien me pasa lo mismo, ayuda

**Comment by 5ghzx** [comment]
I believe no log, no help.

**Comment by Bepper00** [comment]
What

**Comment by bxssdxrk** [comment]
I had the same problem. My game updated automatically via PlayStore and now I have this problem. It's terrible to use the physical mouse as a virtual mouse, it feels heavy and lacks precision.

Edit: I noticed that the shortcuts "CTRL + A", "CTRL + X", "CTRL + C" and "CTRL + V" also stopped working.

**Comment by jhosep3** [comment]
a mi tampoco me funcionan las teclas virtuales y me pasa lo mismo que a ti paulo

**Comment by GreatArman** [comment]
> I also experience the same exact thing after I updated my pojavlauncher, please resolve this issue as soon as possible

Same here I installed old pojav version from Google and I downloaded 1.20 in pojav minimum 21 to 25 times tomorrow and finally I am playing freely now solution is uu have to download old version from sites

**Comment by Bepper00** [comment]
> > I also experience the same exact thing after I updated my pojavlauncher, please resolve this issue as soon as possible
> 
> Same here I installed old pojav version from Google and I downloaded 1.20 in pojav minimum 21 to 25 times tomorrow and finally I am playing freely now solution is uu have to download old version from

> > I also experience the same exact thing after I updated my pojavlauncher, please resolve this issue as soon as possible
> 
> Same here I installed old pojav version from Google and I downloaded 1.20 in pojav minimum 21 to 25 times tomorrow and finally I am playing freely now solution is uu have to download old version from sites

Can i still retrieve my account after downgrading my pojav?

**Comment by GreatArman** [comment]
> tambien me pasa lo mismo, ayuda

Until the pojav developers do not fix this we have to download older version of pojav from third party sites either it I'll not solve I m playing freely after I downloaded old version if u want that version too dm me in discord my id is @always_great_arman

**Comment by GreatArman** [comment]
> > > I also experience the same exact thing after I updated my pojavlauncher, please resolve this issue as soon as possible
> > 
> > 
> > Same here I installed old pojav version from Google and I downloaded 1.20 in pojav minimum 21 to 25 times tomorrow and finally I am playing freely now solution is uu have to download old version from
> 
> > > I also experience the same exact thing after I updated my pojavlauncher, please resolve this issue as soon as possible
> > 
> > 
> > Same here I installed old pojav version from Google and I downloaded 1.20 in pojav minimum 21 to 25 times tomorrow and finally I am playing freely now solution is uu have to download old version from sites
> 
> Can i still retrieve my account after downgrading my pojav?

Yes you can downgrading pojav doesn't affect your account

**Comment by Hanu9098** [comment]
BRO There's gotta be something to fix this issue 
I also tried downloading older version of pojav from like 10 sites but my device showed app not installed . I tried everything but I was still unable to install it.
can anybody pls drop the file here?

**Comment by GaucovyAero** [comment]
^ issue also on the Google Pixel 7

**Comment by GaucovyAero** [comment]
^ issue also on some random oppo device with android 9

**Comment by GaucovyAero** [comment]
^ also on some oppo device with android 13

**Comment by GaucovyAero** [comment]
^ same on redmi k20 pro

**Comment by GaucovyAero** [comment]
^ same on Vivo V15 Pro

**Comment by GaucovyAero** [comment]
same on Galaxy Tab S8 Ultra

**Comment by GreatArman** [comment]
> BRO There's gotta be something to fix this issue I also tried downloading older version of pojav from like 10 sites but my device showed app not installed . I tried everything but I was still unable to install it. can anybody pls drop the file here?

I downloaded older and playing freely

**Comment by Hanu9098** [comment]
Same on realme pad

**Comment by Hanu9098** [comment]
> > BRO There's gotta be something to fix this issue I also tried downloading older version of pojav from like 10 sites but my device showed app not installed . I tried everything but I was still unable to install it. can anybody pls drop the file here?
> 
> I downloaded older and playing freely

Bruh
Can u provide the apk

**Comment by bovfz** [comment]
i also had the same issue I play on Chromebook and its very anoyng when in playing in combat because getting the items is slow and you can die and its  just bad please fix this asap and thank you *btw it only appears when I log in It popped up for me 2 days ago please fix this pojav

**Comment by GaucovyAero** [comment]
^ also on Honor Play 5T

**Comment by GaucovyAero** [comment]
^ also on Infinix Hot 9

**Comment by GreatArman** [comment]
> Same on realme pad

Yes I have also realme pad but I downloaded old version and now I m playing freely

**Comment by Hanu9098** [comment]
> > Same on realme pad
> 
> Yes I have also realme pad but I downloaded old version and now I m playing freely

Ya bro i also did the same but we definitely need to tell them

**Comment by Hanu9098** [comment]
any idea when will this be fixed 
As I can't load 1.21 on older version

**Comment by artdeell** [comment]
Please re-test on this version:
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9813527583

**Comment by ViktorHajse** [comment]
Can you make an option in the settings so that you can disable the virtual mouse completely, without being able to enable it in the game?

**Comment by Hanu9098** [comment]
> Please re-test on this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9813527583

Yep
Solved
