### ISSUE TITLE
[F-Req] <Pojavlauncher May be less popular if not.....>

### ISSUE THREAD

**Issue by Natthakritp** [PojavLauncherTeam/PojavLauncher#5649]
### Is this request related to a bug?

VirGL should be much more stable. And I've heard that it supports OpenGL 4.6.

### Describe the request.

I feel like there are too few renderers to choose from.And I'm not okay with Zink because it only works on some devices.And I recommend you add VirGL back again with Mesa 24.1x.Feel free to bring it back even though VirGL has bugs. It's nice to have GPU acceleration and is supported on most devices.Don't bring GL4ES into this, I'm talking about VirGL because GL4ES supports very minimal shaders.

### Anything else?

Thank you.

**Comment by Natthakritp** [comment]
Please reply to me with reasons. And if I can't add VirGL, then I'm not interested in your project anymore.

**Comment by Marshall2439** [comment]
Vgpu meanwhile: 💀💀

**Comment by Marshall2439** [comment]
I mean there is solcraft launcher which is modified pojavlauncher but idk

**Comment by Natthakritp** [comment]
> Vgpu meanwhile: 💀💀

That VGPU is stable but integrated with GL4ES.

**Comment by ghost** [comment]
> Please reply to me with reasons. And if I can't add VirGL, then I'm not interested in your project anymore.

I don't think developers reply good reason. In hunkai star rail  display mode have normal mode(use vulkan)  and compatible mode(uses opengl) both of them are same and support all graphicsl setting. Compatible mode is for phones not support or fully support vulkan
And use opengl with no different with normal mods and work fine i think pojav need bring back virgl

**Comment by GaucovyAero** [comment]
get solcraftlauncher if you want more renderers

**Comment by Marshall2439** [comment]
> get solcraftlauncher if you want more renderers

Solcraft launcher has more renderers but literally zero of them work with my phone whether it's virgl or Zink or vgpu only angle and holygles works there but it's pointless to use them since you installed solcraft launcher for more renderers

**Comment by GaucovyAero** [comment]
> > get solcraftlauncher if you want more renderers
> 
> Solcraft launcher has more renderers but literally zero of them work with my phone whether it's virgl or Zink or vgpu only angle and holygles works there but it's pointless to use them since you installed solcraft launcher for more renderers

then its most probably just your phone then

**Comment by Marshall2439** [comment]
> > > get solcraftlauncher if you want more renderers
> > 
> > 
> > Solcraft launcher has more renderers but literally zero of them work with my phone whether it's virgl or Zink or vgpu only angle and holygles works there but it's pointless to use them since you installed solcraft launcher for more renderers
> 
> then its most probably just your phone then

Idk but previous gplay release of pojav worked with Zink but it doesn't work anymore did Devs do something?
