### ISSUE TITLE
[BUG] (gl4es extra) Black line when using Nuke mod

### ISSUE THREAD

**Issue by XavierErrorLog** [PojavLauncherTeam/PojavLauncher#5651]
### Describe the bug

Hello to whoever is reading this, I have a problem with forge 1.12.2.14.23.5.2860 theres a little funny black line on my screen when using the HBM nuclear weapons mod everything works fine with FPS and all that just this comically large black line...

### The log file and images/videos

![lol](https://github.com/PojavLauncherTeam/PojavLauncher/assets/86020558/a88a26f3-f12b-4537-884f-ddcce47865dd)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Wait
3. Load Game
4. Good FPS
5. Big ahh black line
```

### Expected Behavior

[ Start Game }
[ Wait ]
[ Loads world ]
[ Commit war crimes with weapons of mass destruction ]

### Platform

```markdown
- Device model: Lenovo Chromebook Duet {kukui}
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version:Foxglove (Playstore June 21st Update )
```

### Anything else?

Its a very large line even tho the time set is night its very noticeable

**Comment by Mathias-Boulay** [comment]
Hopefully fixed with the shader fixes
