### ISSUE TITLE
[BUG] Cursor otg mouse can't move

### ISSUE THREAD

**Issue by Ferdyansy** [PojavLauncherTeam/PojavLauncher#5656]
### Describe the bug

I have a mouse and keyboard, when I play the latest version of Pojavlauncher and I use Minecraft version 1.21 my cursor can't move, I think it's because Pojavlauncher doesn't support it, but the keyboard can still be used

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15942220/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the Pojav Pojav launcher
2. Play with 1.21 version
3. In game, i play in multiplayer and singleplayer
4. When i move the mouse, kursor can't moving
```

### Expected Behavior

I expect, the mouse work in my android 9

### Platform

```markdown
- Device model: oppo
- CPU architecture: 4x ARM Cortex-A53 @ 2,30 GHz
- Android version: 9
- PojavLauncher version: foxglove 20240621-332de88-v3_openjdk
```

**Comment by Ratul376** [comment]
Bro same problem with me too

**Comment by Sahariasamadsoyad** [comment]
Same

**Comment by GaucovyAero** [comment]
duplicate of #5648
