### ISSUE TITLE
[F-Req] Allow Pojavlauncher To Manage External Storage On Newer Android Versions

### ISSUE THREAD

**Issue by ItzMeNeon** [PojavLauncherTeam/PojavLauncher#5662]
### Is this request related to a bug?

Nothing Affect to the game or the app itself

### Describe the request.

'Allow The App To Store Game Files To Another Directory than the isolated one Using SAF Or Any Approach'
'Allow The Users To Use A Desired Folder By Asking Them To Put On Which Folder Except "~/Storage/Emulated/0/" or AKA The root Folder of a normal Android Phones Would Store the user files'
'Ask The Users If The Files From The Default Directory Will Be Moved To The Directory They Choose Or Not After Selecting a new default directory'

### Anything else?

Why I'm Posting This? Because I Want This Feature Could Be Available Because I don't Need To Use Shizuku Or Rooting A Phone First To Access Android/data/net.kdt.pojavlauncher on any file manager (including ZArchiver), Especially For Common people who Use their Devices and doesn't know how to Use Shizuku And Rooting Their Devices Or even worse didn't have a laptop/pc for rooting or using adb for shizuku or wifi nearby (for wireless adb usage), it will be a total nightmare to access those folder without them... And since Android 10 or newer made a new nightmare, some people would Struggle to access that folder if they want to put a new mods from Modrinth / curseforge because we can't access the Android Folder Anymore...

Note : If this feature is nearly or literally Impossible, that's ok I don't mind that

**Comment by GaucovyAero** [comment]
use com.marc.files
