### ISSUE TITLE
Zink renderer is broken

### ISSUE THREAD

**Issue by Marshall2439** [PojavLauncherTeam/PojavLauncher#5663]
### Describe the bug

It got broken again. It crashes the game right before screen starts showing anything 

### The log file and images/videos

[Uploading latestlog.txt…]()

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Select Zink
3. Launch game
4. Enjoy crashes
```

### Expected Behavior

To run game as intended? 

### Platform

```markdown
- Device model: Samsung A53 5g
- CPU architecture: arm 64
- Android version: 14
- PojavLauncher version: foxglove or something like that
```

### Anything else?

Idk how to fix it. Weirdly enough it worked in previous version but loading screen was glitching for about few mins until mojang logo appeared but not it just crashes. This seems like device specific but it worked before

**Comment by grosioso** [comment]
zink is not supported on all devices. it is not maintained or made by pojav. just get a better phone with better zink support and problem fixed 😂

**Comment by 5ghzx** [comment]
worked before though

**Comment by ghost** [comment]
Virgl remder is more compatible than zink i don't know why developers remove it. I know virgl have many bugs but i testd solcraft launcher and it's fine work without bug

**Comment by Marshall2439** [comment]
> Virgl remder is more compatible than zink i don't know why developers remove it. I know virgl have many bugs but i testd solcraft launcher and it's fine work without bug


It didn't even work both virgl and zink

**Comment by Marshall2439** [comment]
> zink is not supported on all devices. it is not maintained or made by pojav. just get a better phone with better zink support and problem fixed 😂

Then how it worked before?

**Comment by GaucovyAero** [comment]
duplicate of #5653
