### ISSUE TITLE
Mouse Problem In This New 23 june 2024 Pojavlauncher update

### ISSUE THREAD

**Issue by Sahariasamadsoyad** [PojavLauncherTeam/PojavLauncher#5664]
### Describe the bug

I Purchased A Mouse And Keyboard Like 1 Months Then Now 23 June 2024 i Want To Play Pojavlauncher Keyboard And Mouse Then I Opened Pojavlauncher With Keyboard And Mouse Then I Saw The Pojavlauncher New Update Then I Updated Then I Click Play Then When I Click Play Then My Corsour Suddenly Gone Then I Am Moving My Mouse Then I Saw The Pojavlauncher Default Mouse Appeared But I Dosnt Clicked The Mouse Button Then I Am Also Moving The Mouse But No Response (but This Is Working Mouse And I Tryed Other Applications Its Working)  plz fix this!!!!

### The log file and images/videos

I Purchased A Mouse And Keyboard Like 1 Months Then Now 23 June 2024 i Want To Play Pojavlauncher Keyboard And Mouse Then I Opened Pojavlauncher With Keyboard And Mouse Then I Saw The Pojavlauncher New Update Then I Updated Then I Click Play Then When I Click Play Then My Corsour Suddenly Gone Then I Am Moving My Mouse Then I Saw The Pojavlauncher Default Mouse Appeared But I Dosnt Clicked The Mouse Button Then I Am Also Moving The Mouse But No Response (but This Is Working Mouse And I Tryed Other Applications Its Working)  plz fix this!!!!

### Steps To Reproduce

```markdown
I Purchased A Mouse And Keyboard Like 1 Months Then Now 23 June 2024 i Want To Play Pojavlauncher Keyboard And Mouse Then I Opened Pojavlauncher With Keyboard And Mouse Then I Saw The Pojavlauncher New Update Then I Updated Then I Click Play Then When I Click Play Then My Corsour Suddenly Gone Then I Am Moving My Mouse Then I Saw The Pojavlauncher Default Mouse Appeared But I Dosnt Clicked The Mouse Button Then I Am Also Moving The Mouse But No Response (but This Is Working Mouse And I Tryed Other Applications Its Working)  plz fix this!!!!I Purchased A Mouse And Keyboard Like 1 Months Then Now 23 June 2024 i Want To Play Pojavlauncher Keyboard And Mouse Then I Opened Pojavlauncher With Keyboard And Mouse Then I Saw The Pojavlauncher New Update Then I Updated Then I Click Play Then When I Click Play Then My Corsour Suddenly Gone Then I Am Moving My Mouse Then I Saw The Pojavlauncher Default Mouse Appeared But I Dosnt Clicked The Mouse Button Then I Am Also Moving The Mouse But No Response (but This Is Working Mouse And I Tryed Other Applications Its Working)  plz fix this!!!!
```

### Expected Behavior

I Purchased A Mouse And Keyboard Like 1 Months Then Now 23 June 2024 i Want To Play Pojavlauncher Keyboard And Mouse Then I Opened Pojavlauncher With Keyboard And Mouse Then I Saw The Pojavlauncher New Update Then I Updated Then I Click Play Then When I Click Play Then My Corsour Suddenly Gone Then I Am Moving My Mouse Then I Saw The Pojavlauncher Default Mouse Appeared But I Dosnt Clicked The Mouse Button Then I Am Also Moving The Mouse But No Response (but This Is Working Mouse And I Tryed Other Applications Its Working)  plz fix this!!!!

### Platform

```markdown
- Device model: vivoy91
- CPU architecture: i dont know
- Android version: 8
- PojavLauncher version: 2.2.0
```

**Comment by Dana-pn** [comment]
У меня тоже самое

**Comment by Dana-pn** [comment]
А также вопрос у меня пишет ошибка 923 и я не могу выбрать версию в релизах

**Comment by Sahariasamadsoyad** [comment]
> У меня тоже самое

Do You know How To Fix??
