### ISSUE TITLE
Error code 1 when attempting to execute jar

### ISSUE THREAD

**Issue by Manoffwar** [PojavLauncherTeam/PojavLauncher#5665]
### Describe the bug

I attempted to add JEI. Responded with error code 1. Tried Tinkers Construct. Error code 1. All other mods also return error code 1

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15948159/latestlog.txt)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/173640673/bd0c6f91-3f81-4bc1-8c39-94f33cc78d37

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Execute Jar of any mod
3. 1-2 seconds black screen
4. Crash
```

### Expected Behavior

The thing for jar execution to appear

### Platform

```markdown
- Device model:  Galaxy Note 20 Ultra
- CPU architecture:  64
- Android version: 13
- PojavLauncher version: The Google play version
```

**Comment by 5ghzx** [comment]
you aren't supposed to run mod .jars, you're supposed to put them in the mods folder.

**Comment by 5ghzx** [comment]
this is expected behaviour.
