### ISSUE TITLE
[F-Req]*remove this flickering glitch*

### ISSUE THREAD

**Issue by SHIVAMxMC** [PojavLauncherTeam/PojavLauncher#5668]
### Is this request related to a bug?

*so recently I switched to pojav and I saw chat,hotbar,f3 screen are flickering you can see in this video.*
![lv_0_20240624131543](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173661163/dd3a6d0d-b85f-4ef3-af35-2cef35143264)

### Describe the request.

*So try to remove bcz I see on YouTube many ppl have this problem*

**Comment by GaucovyAero** [comment]
hm ok, cant repro, also dunno what device he has, pls figure that out

**Comment by SHIVAMxMC** [comment]
I have Redmi 9 but if you search on YouTube you will find this problem.

**Comment by GaucovyAero** [comment]
> I have Redmi 9 but if you search on YouTube you will find this problem.

can you give me a link pls

**Comment by SHIVAMxMC** [comment]
https://youtu.be/wqoX5FDH7o0?si=Stpq3xPhiyzVVovV
Here u go

**Comment by GaucovyAero** [comment]
thanks

**Comment by GaucovyAero** [comment]
that video doesnt show your issue tho, his device most likely has a powervr gpu which causes this, he can fix it by turning on antialiasing to 2x fxaa in optifine shaders settings (maybe give him a comment) you should also try that i think

**Comment by SHIVAMxMC** [comment]
I try all of solution but doesn't work flickering and invisible hotbar are same trust me

**Comment by GaucovyAero** [comment]
have you tried switching renderers to angle for example?

**Comment by SHIVAMxMC** [comment]
Yes I tried to change render to angle and zink but these render has another glitch bcz the renderer angle and zink is for vulkan and I use sodium so I have many problem I have problem with holy I have problem with zink and angle it shows black screen after entering the game I loaded the world but I can see my hand and some slime and the world I full of darkness like void (sorry for my bad grammar) but please fix this issue if u are the moderator of pojavlauncher

**Comment by SHIVAMxMC** [comment]
@GaucovyAero @itsnebulalol help

**Comment by GaucovyAero** [comment]
i prolly gotta get a redmi 9 then

**Comment by GaucovyAero** [comment]
cannot reproduce on the ge8320 chip, still
