### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#567]
1. NO SKIN UI
2. NO PROFILE
3. LAG
4. I CAN'T INSTALL FORGE
5. THE CUSTOM CONTROLS
6. PLAY YOUR LAUNCHER IN YOUR PHONE AND YOU WILL SEE OUR ISSUES.
7. FIX

**Comment by khanhduytran0** [comment]
0. **DISABLE your caps lock**
1. See #503
2. invalid
3. Buy a new device.
4. We can't fix without log.
5. Already added.
6. invalid
7. **FIX it yourself** because you hold the log file.

**Comment by khanhduytran0** [comment]
So... what about logs?

**Comment by artdeell** [comment]
> PLAY YOUR LAUNCHER IN YOUR PHONE AND YOU WILL SEE OUR ISSUES.

i play it on my phone almost every day, what are you talking about

**Comment by netkv** [comment]
i think they use v2 version of launcher...

**Comment by netkv** [comment]
for skins use this https://www.minecraft.net/en-us/profile/skin in your browser, it should work atleast on chrome

**Comment by WesleyVanNeck** [comment]
INVALID SO CLOSING
