### ISSUE TITLE
[BUG] Bad drivers, blackout screen

### ISSUE THREAD

**Issue by doggosamp** [PojavLauncherTeam/PojavLauncher#5674]
### Describe the bug

Cuando descargo las versiones que van de la 1.15 hasta la 1.21 me sale un bug donde no se ve las letras y en el juego se corrompen las texturas, ya verifique y elimine por todos lados, reinstale y todo y aún sigue este bug, llego a pensar que es el launcher 

### The log file and images/videos

No tengo imagenes por ahora, primera vez que me registro y veo todo en inglés

### Steps To Reproduce

```markdown
Entro a pojavlauncher
Intento iniciar la 1.20.4
Veo que no aparece ninguna letra
Intento entrar a un servidor 
Entro al servidor y veo las texturas de color negro
```

### Expected Behavior

No puedo jugar tranquilamente

### Platform

```markdown
- Device model: Asus Chromebook
- CPU architecture: Intel(R) Celeron(R) CPU N3350 @ 1.10GHz (2 subprocesos, 2.40 GHz)
- Android version: 9
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

The render on pojav is : Santo GL4ES

**Comment by doggosamp** [comment]
Se me olvido poner qué tampoco me deja ejecutar los .jar

**Comment by GaucovyAero** [comment]
"La más reciente" is not a version, please provide the actual version, also mention what renderer you are using and if the issue just started happening after the last update

**Comment by doggosamp** [comment]
> "La más reciente" is not a version, please provide the actual version, also mention what renderer you are using and if the issue just started happening after the last update
hi this is?: foxglove-20240621-332de88-v3_openjdk

**Comment by GaucovyAero** [comment]
thats the version, but did the issue only start happening on the last update and what renderer are you using? be sure to also provide the log (latestog.txt)

**Comment by doggosamp** [comment]
> thats the version, but did the issue only start happening on the last update and what renderer are you using? be sure to also provide the log (latestog.txt)

Hello, I'm using the Santo GL4ES renderer, and before I used one called Divina or something like that, I don't remember anymore, I'm frustrated, Oh, this was also in the last version, the one I commented a few hours ago. I think I don't have the lastetlog, since I'm playing 1.8.0 because it won't let me play 1.20

**Comment by doggosamp** [comment]
> thats the version, but did the issue only start happening on the last update and what renderer are you using? be sure to also provide the log (latestog.txt)

Estoy llegando a creer que es el renderizador, no entiendo por qué ha sido cambiado si anteriormente funcionaba de maravilla :'c

**Comment by GaucovyAero** [comment]
dunno if this will even work, but you might aswell try
create a file in the pojav directory (/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/) called custom_env.txt
type this into the file: `LIBGL_VGPU_OPT=2`
you can use acode editor or something like that to edit the file
if this doesnt work, delete the file (custom_env.txt)

**Comment by doggosamp** [comment]
> dunno if this will even work, but you might aswell try create a file in the pojav directory (/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/) called custom_env.txt type this into the file: `LIBGL_VGPU_OPT=2` you can use acode editor or something like that to edit the file if this doesnt work, delete the file (custom_env.txt)

![Uploading Screenshot 2024-06-25 4.48.47 PM.png…]()
[Uploading latestlog.txt…]()

If you have discord, add me as friends my name is doggosamp there you explain to me in more detail

**Comment by doggosamp** [comment]
> dunno if this will even work, but you might aswell try create a file in the pojav directory (/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/) called custom_env.txt type this into the file: `LIBGL_VGPU_OPT=2` you can use acode editor or something like that to edit the file if this doesnt work, delete the file (custom_env.txt)

Ok, what you just told me, didn't any other solution work for me? I think it's the render.

**Comment by GaucovyAero** [comment]
it is the renderer

**Comment by doggosamp** [comment]
> it is the renderer

yes yes, do you know how I change it without installing any external app???, I'm dying, I had a very op hardcore world and now I can't play

**Comment by GaucovyAero** [comment]
> > it is the renderer
> 
> yes yes, do you know how I change it without installing any external app???, I'm dying, I had a very op hardcore world and now I can't play

yeah you gotta wait for a fix

**Comment by GaucovyAero** [comment]
^ also happens on i3-1215U with Intel UHD Graphics for 12th Gen

**Comment by GaucovyAero** [comment]
keep in mind this might not get fixed in a long time, because it does not happen on the devices we have and the android gpu inspector does not support such GPU

**Comment by GaucovyAero** [comment]
anyway heres something that might help you (you dont have a powervr gpu but the blackout applies)
**you dont have to do the hit color thing if you dont have red mobs**
also maybe if you can find another hit color mod for fabric that isnt so sussy use that instead

[powervr_ge8320_workaround.txt](https://github.com/user-attachments/files/15993022/powervr_ge8320_workaround.txt)

**Comment by doggosamp** [comment]
> anyway heres something that might help you (you dont have a powervr gpu but the blackout applies) **you dont have to do the hit color thing if you dont have red mobs** also maybe if you can find another hit color mod for fabric that isnt so sussy use that instead
> 
> [powervr_ge8320_workaround.txt](https://github.com/user-attachments/files/15993022/powervr_ge8320_workaround.txt)
 
Come on man, that's what I said at the beginning, I can't install any apk that doesn't come from the playstore

**Comment by GaucovyAero** [comment]
you dont have to do that, just follow everything else

**Comment by doggosamp** [comment]
I'll try it brother, it's a bit complicated for me since it's all in English and translating it is complicated for me
I would have to guess the buttons since I don't see them :v

**Comment by doggosamp** [comment]
It doesn't work brother, the game crashes

**Comment by Camara23ts** [comment]
El problema solo es en chromebook o al menos a mi me paso en el chromebook, el error esta en que Pojav actualizo su app así qu la unica forma para arreglarlo es esperando a que de actualize.

**Comment by doggosamp** [comment]
> El problema solo es en chromebook o al menos a mi me paso en el chromebook, el error esta en que Pojav actualizo su app así qu la unica forma para arreglarlo es esperando a que de actualize.

bueno maestro de la inteligencia, en el reporte está aclarado que es el nuevo renderizador de Pojav el ''Santo GL4ES'' y anteriormente jugaba con el ''Divinas'' cuál era el que a mi me funcionaba

**Comment by doggosamp** [comment]
> El problema solo es en chromebook o al menos a mi me paso en el chromebook, el error esta en que Pojav actualizo su app así qu la unica forma para arreglarlo es esperando a que de actualize.

Hola sí así es el problema es solo en chromebook, como lo dice el reporte, este bug es causado gracias al renderizador nuevo, el Santo GL4ES

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
