### ISSUE TITLE
[BUG] mod error (code 1)

### ISSUE THREAD

**Issue by Ion00000** [PojavLauncherTeam/PojavLauncher#5675]
### Describe the bug

PojavLauncher 1.21 Is there anyone who uses mode?

 I want to use it, but I can't do it because it's an error (code: 1). 

It occurs when even one file exists in the mode file

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15965227/latestlog.txt)

### Steps To Reproduce

```markdown
1. Put the downloaded mode in the mode file. 
2. Run version 1.21 with fabric loader. 
3. Forced termination with error code 1
```

### Expected Behavior

I don't know. 

### Platform

```markdown
- Device model: Samsung s22u
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version:Google play Store version
```

**Comment by GaucovyAero** [comment]
try moving the mod files with another file manager, cant really help with this and its not a pojav issue (minecraft didnt get android permission to open the mod files)
