### ISSUE TITLE
Physical mouse not working[BUG] <Short description>

### ISSUE THREAD

**Issue by Oppvirtual** [PojavLauncherTeam/PojavLauncher#5678]
### Describe the bug

When I connect physical mouse and launche the game it is not working freezes in the centre

### The log file and images/videos

Freezes physical mouse 

### Steps To Reproduce

```markdown
Start launcher
And tap on play button 
Physical mouse freezes in centre
```

### Expected Behavior

Solve

### Platform

```markdown
- Device model: redmi note 8 pro
- CPU architecture: arm64 
- Android version: 11
- Launcher version: play store version
```

### Anything else?

Solve the problem

**Comment by GaucovyAero** [comment]
duplicate of #5648

**Comment by ZombieSPie** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9584072517
