### ISSUE TITLE
[BUG] Chunks blacked out or dimmed in brightness

### ISSUE THREAD

**Issue by TOOTS1610** [PojavLauncherTeam/PojavLauncher#5679]
### Describe the bug

I have been using the launcher for a few weeks and it is starting to bug out by dimming the brightness of chunks or blacking them out completely and i have not changed any settings to cause this. I am very confused.Can someone please give me some advice. I cannot take a screenshot as i am on chromebook.

### The log file and images/videos

Random blacked out chunks no patern in a multi or single player world.

### Steps To Reproduce

```markdown
1. Start PovJavLauncher
2. Open a single or multiplayer world
3. Find a random blacked out chunk.
```

### Expected Behavior

I expect my world to be normal without these random chunks 

### Platform

```markdown
- Device model: Chromebook IP 5 Chrome 16IAU7
- CPU architecture: 
- Android version: not on android 
- PojavLauncher version: 1718957503643
```

**Comment by GaucovyAero** [comment]
no log provided, invalid pojav version, no screenshot provided

**Comment by GaucovyAero** [comment]
duplicate of #5674

**Comment by TOOTS1610** [comment]
Version 1.20.4 or above not sure about anything before 1.20
