### ISSUE TITLE
Can't touch screen

### ISSUE THREAD

**Issue by Minblud** [PojavLauncherTeam/PojavLauncher#568]
Ok so I open mc 1.16.4 and I can't even touch anything on the screen not even with the mouse feature that comes with the launcher

![Screenshot_20210105-121428_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/47721915/103630064-36309c00-4f52-11eb-8bdc-93b010b448b9.png)

![Screenshot_20210103-154127_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/47721915/103630074-3892f600-4f52-11eb-8a1d-995195394f79.png)

![Screenshot_20210103-174045_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/47721915/103630234-71cb6600-4f52-11eb-8a1b-85dcd60b99f2.png)

My device: s20ultra 12ram 128gb 

My Java runtime: jre8-arm64-20201104-release.tar.xz 

My launcher version:
![Screenshot_20210103-165140_Settings](https://user-images.githubusercontent.com/47721915/103630144-54969780-4f52-11eb-82d6-59bc4b6b93ea.png)

My discord: Minblud#3186

**Comment by artdeell** [comment]
Clear app data and game folder and try again

**Comment by Minblud** [comment]
> Clear app data and game folder and try again

ok

**Comment by khanhduytran0** [comment]
@MinbludGamer please reply

**Comment by khanhduytran0** [comment]
Timeout
