### ISSUE TITLE
[F-Req] change the location where the game stores files

### ISSUE THREAD

**Issue by 500LRB** [PojavLauncherTeam/PojavLauncher#5680]
### Is this request related to a bug?

Yes this is related to a bug, on newer android versions you aren't able to access the game files without a file manager or a shortcut to the built in file app

### Describe the request.

Change the file location to "android/media" as that is a folder normally Accessible without needing a seperate shortcuts app or files app
Media folder (google files)
![Screenshot_20240625-152334](https://github.com/PojavLauncherTeam/PojavLauncher/assets/145224574/68c7b7dc-b34f-4b12-910c-776cf13fd532)
Data folder (google files)
![Screenshot_20240625-152330](https://github.com/PojavLauncherTeam/PojavLauncher/assets/145224574/5f2e224c-6e87-4307-b808-76457660a017)

### Anything else?

I use a google pixel so it comes with the google files app and I'm required to use a shortcut app to access the files

**Comment by GaucovyAero** [comment]
use com.marc.files from play store, pojav would not be able to exist on play store if it had data stored elsewhere
