### ISSUE TITLE
[BUG] Black world and text

### ISSUE THREAD

**Issue by PoisonAspectIII** [PojavLauncherTeam/PojavLauncher#5681]
### Describe the bug

When I tried to launch 1.20.6 with optifine the world becomes all black upon loading and the text does to. This effects all versions and when I deleted the .minecraft folder 3 times it still did the same thing when I tried to get optifone to work again and my minimapping is off and brightness is on default please help

### The log file and images/videos

...
![image0](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161101810/8e3276a1-ebcd-4a80-9926-bb022e5c3e88)

### Steps To Reproduce

```markdown
I need someone to help me figure this bug out
```

### Expected Behavior

I expect ,minecraft to work back normal

### Platform

```markdown
- Device model: Galaxy tablet a7
- CPU architecture: idk
- Android version: 11 (I think)
- PojavLauncher version: Newly Updated
```

### Anything else?

Nope

**Comment by doggosamp** [comment]
Hello brother, I would like to be able to help you solve your problem but the same thing is happening to me and what I have come to is that it is the new update of PojavLauncher which has removed the Divinas render and has placed one that is nicknamed Santo, that is why he sees you like this

**Comment by PoisonAspectIII** [comment]
Ah so it's just part of the game now..? I can't play minecraft sith optifine anymore and idl if sodium will work bc you have to install more mods on fabric

**Comment by doggosamp** [comment]
> Ah so it's just part of the game now..? I can't play minecraft sith optifine anymore and idl if sodium will work bc you have to install more mods on fabric

I have not tried with fabric, but if I install vanilla the same thing happens to me, the textures are seen in their color but what is not seen are the letters, so you will not be able to play brother

**Comment by PoisonAspectIII** [comment]
Gotdamn it and I though about installing the apk version

**Comment by PoisonAspectIII** [comment]
Dang...I though it was fixable

**Comment by ThatMG393** [comment]
Please upload `latestlog.txt`

**Comment by GaucovyAero** [comment]
please confirm the SoC model you have (use AIDA64 to figure out)

**Comment by Bel69420** [comment]
> please confirm the SoC model you have (use AIDA64 to figure out)

He has PowerVR GE8320, Mediatek Helio P22T

**Comment by Bel69420** [comment]
Idk he mean A7 2020 or A7 Lite

**Comment by GaucovyAero** [comment]
> > please confirm the SoC model you have (use AIDA64 to figure out)
> 
> He has PowerVR GE8320, Mediatek Helio P22T

ok thanks for the info, this was expected

**Comment by GaucovyAero** [comment]
duplicate of #5646

**Comment by PoisonAspectIII** [comment]
> > > please confirm the SoC model you have (use AIDA64 to figure out)
> > 
> > 
> > He has PowerVR GE8320, Mediatek Helio P22T
> 
> ok thanks for the info, this was expected

A7 lite

**Comment by PoisonAspectIII** [comment]
And when I try to use with optifine it makes the world and text black upon loading
![Screenshot_20240626_130359_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161101810/e0c9e086-7c58-4ce7-81cc-f9ec1657335f)
![Screenshot_20240626_130126_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161101810/c3dd6c53-7eac-468c-9ec7-730783ae03fc)
![Screenshot_20240626_130110_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/161101810/b96e6dd9-218f-463d-888c-14f77769dd14)

**Comment by PoisonAspectIII** [comment]
> Idk he mean A7 2020 or A7 Lite

A7 lite

**Comment by TopedGames** [comment]
![345064212-9b437061-d6dc-4f57-b18c-aedd1713d3ca](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150599356/d5cdd518-4462-4ab2-8a06-978b05479608)
Люди, у меня всё тоже самое: https://github.com/PojavLauncherTeam/PojavLauncher/issues/5727. И у других упомянутых: https://github.com/PojavLauncherTeam/PojavLauncher/issues/5698, https://github.com/PojavLauncherTeam/PojavLauncher/issues/5715, https://github.com/PojavLauncherTeam/PojavLauncher/issues/4752, https://github.com/PojavLauncherTeam/PojavLauncher/issues/5646, https://github.com/PojavLauncherTeam/PojavLauncher/issues/5681. Предлагаю стереть данные pojavlauncher, а после, если ошибка не исчезнет, то будем спамить компании Pojavlauncher Team.
