### ISSUE TITLE
BROKEN Zink Renderer [BUG] <Short description>

### ISSUE THREAD

**Issue by Unknown795** [PojavLauncherTeam/PojavLauncher#5683]
### Describe the bug

Launcher immediately crashes/does not open Minecraft everytime I I try to use zink renderer.

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/15981181/latest.log)

### Steps To Reproduce

```markdown
Step 1: Open Pojav launcher.
Step 2: Open Pojav launcher (Settings/Video and Renderer).
Step 3: On the renderer, select Zink (Vulkan).
Step 4: Go back and open your selected Minecraft version (The version I tried to open are (1.7.101.10.2/1.12.2/1.16.5/1.19.4/1.20.4/1.21).

After all of these steps, the game won't open and will immediately crash.
```

### Expected Behavior

I expect the game to open and launch properly with the Zink renderer.

### Platform

```markdown
- Device model: Xiaomi Redmi Note 10s
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by GaucovyAero** [comment]
you sent the wrong file, send latestlog.txt

**Comment by GaucovyAero** [comment]
stale
