### ISSUE TITLE
[F-Req] run external jars while playing

### ISSUE THREAD

**Issue by blob83** [PojavLauncherTeam/PojavLauncher#5684]
### Is this request related to a bug?

Its not a bug but its like multiuse of jars

### Describe the request.

When you play minecraft normally and your playing a client and the client request a external jar in the .minecraft folder but it cant since the client is using the main java and cant use any other .jar so this feature can make clients access other jar or launch another jar and the other jar can be accessible by making another gui in the pojavlauncher maybe the devs can add some way to add multiuse of version support and maybe even jars

### Anything else?

Idk but this seems a good idea

**Comment by Felix14-v2** [comment]
Just don't use your broken hacks, and you won't need to solve this issue.
