### ISSUE TITLE
Black screen when playing in zink render on the operating system iOS

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5686]
### Describe the bug

I use optifine and zink vulkan to play Minecraft with shaders when in the game interface, although it plays background music in Minecraft but the interface is still black.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/139622169/b19636d8-561a-4565-98d4-ef0975c65648

### Steps To Reproduce

```markdown
Make
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: iPhone se 2020
- CPU architecture:  arm64
- Android version: iOS version:16
- PojavLauncher version: iOS lastest version
```

**Comment by kiokori-git** [comment]
- your pojavlauncher is outdated, grab a dev build from github actions
- don't set your resolutiom scale to 150, it isn't recommended or your performance will be insanely bad, set it to 50 - 65% or something
- set your ram to auto

**Comment by GaucovyAero** [comment]
wrong repository, go to PojavLauncherTeam/PojavLauncher_iOS
