### ISSUE TITLE
Pojav launcher keeps crashing with Fabric 1.20.4

### ISSUE THREAD

**Issue by ranajisujal5117** [PojavLauncherTeam/PojavLauncher#5687]
### Describe the bug

It crashes with Fabric 1.20.4 and says 'Application exited with exit code 1 please check latest log'

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

It should not crash. I should be able to play fabric.

### Platform

```markdown
- Device model: Redmi 11 prime 5g
- CPU architecture: 
- Android version: 14
- PojavLauncher version: Latest
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
send the log

**Comment by GaucovyAero** [comment]
stale
