### ISSUE TITLE
Nothing is showing in chromebook

### ISSUE THREAD

**Issue by noohislegend** [PojavLauncherTeam/PojavLauncher#5688]
### Describe the bug

after 1.21 whenever i click on play it started downloading and then i will say unable to create directory and then i press on ok and again click on play it will start but in game nothing is written like singleplayer,mutliplayer and in world none of items 
ar ther nothing is wriiten

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15993016/latestlog.txt)
![Screenshot 2024-06-26 23 07 00](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173461709/b207f45f-42a5-4d2d-b739-107ef0218c7c)
![Screenshot 2024-06-26 23 06 26](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173461709/61a77ccd-f127-4835-9bcc-9c3e43ea7f80)
![Screenshot 2024-06-26 23 05 11](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173461709/fac2a33a-186d-427d-9c51-5dbc6942e94d)

### Steps To Reproduce

```markdown
1. Click On Play 
2.Then an error (unable to create target directory)
3.Then i will click on ok and again click on play the i will be downloaded 
4.But in Game This error
```

### Expected Behavior

I expect i will get the solution

### Platform

```markdown
- Device model: Dell Chromebook 11 (3180) 2/16G
- CPU architecture: x86
- Android version: 11 or 10
- PojavLauncher version: 1.21*
```

**Comment by noohislegend** [comment]
![Screenshot 2024-06-26 23 15 54](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173461709/86b4948c-68e2-4321-8695-1dab3814d780)
![Screenshot 2024-06-26 23 16 28](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173461709/3899b177-a729-47c3-9cc1-0562dcc0ad38)
![Screenshot 2024-06-26 23 16 49](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173461709/b20fd7ab-28f7-4dfa-8426-1065d7173d5a)

**Comment by doggosamp** [comment]
I am also presenting the same error, I hope the developers find out about this and solve it, this error is due to the new Santo GL4ES renderer since this does not happen with the Divinas renderer

**Comment by noohislegend** [comment]
> after 1.21 whenever i click on play it started downloading and then it will say unable to create directory and then i press on ok and again click on play it will start but in game nothing is written like singleplayer,mutliplayer and in world none of items will show

please fix 

> I am also presenting the same error, I hope the developers find out about this and solve it, this error is due to the new Santo GL4ES renderer since this does not happen with the Divinas renderer

yeah

**Comment by doggosamp** [comment]
I think there is a solution by downloading an external file, but my chromebook cannot install apks, I hope they solve this soon and return to the old 'Divinas' renderer

**Comment by noohislegend** [comment]
yeah bro same also  with me my chromebook also cannot install apks it say turn on devloper mode

**Comment by noohislegend** [comment]
i know the reason why this is happening
![Screenshot 2024-06-28 18 17 00](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173461709/0c6d65f9-3cdd-408a-88ee-331764e685e4)

**Comment by grosioso** [comment]
this feels like an anomaly to me

**Comment by noohislegend** [comment]
see on the its says unable to create target directory

**Comment by noohislegend** [comment]
see on the top it says unable to create target directory

**Comment by ALEX826762** [comment]
i have the same problem and i think we need to wait for 1.21.1 actualization and this will be fixed

**Comment by Fede2782** [comment]
Can't you use Minecraft Java in Crostini (aka Linux) instead of running on Android container? Install as you would normally do on a Linux Debian system. The performance are better than Android and there is full graphics support.

**Comment by Anyhtt1-0** [comment]
If y'all see on files and pick pojavlauncher there is control map, lwgl3, caciocavallo, caciocavallo 13 there is suppose be .Minecraft and etc there 4 files instead of 12 were not cooking so we need this update fast asf

**Comment by Eggzheads** [comment]
Does this always happen when you launch?
Try reinstalling the version or pojav

**Comment by nooo00000** [comment]
same issue

**Comment by Fede2782** [comment]
> same issue

Sorry to insist but could you try running Minecraft Java in the Linux environment. This would avoid all the issues related to Android graphics. On my previous chromebook i used to play java ed there without issues and performance were good (60fps, fabulous, with Intel i7 8th gen integrated graphics)

**Comment by nooo00000** [comment]
i wonder when they will fix it
my lunix doesnt work

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
