### ISSUE TITLE
[F-Req] add a built in mod manager 

### ISSUE THREAD

**Issue by 500LRB** [PojavLauncherTeam/PojavLauncher#5689]
### Is this request related to a bug?

It becomes really annoying to remove and add mods and debug mods as I have to do it from the files app all the time, and go back and forth between the files app and pojav and google chrome.

### Describe the request.

As we have a built in mod pack manager and downloader, it would make sense to have a built in mod manager to make it easier to download and remove mods.

**Comment by GaucovyAero** [comment]
out of scope for this launcher
