### ISSUE TITLE
[BUG] Game crash on startup with Zink renderer

### ISSUE THREAD

**Issue by LynxEko** [PojavLauncherTeam/PojavLauncher#5694]
### Describe the bug

Game crashes when launched with the Zink renderer

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16017302/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start Minecraft with the Zink renderer
3. Wait...
4. Game crashes
```

### Expected Behavior

I expect the game to launch successfully without crashing

### Platform

```markdown
- Device model: Xiaomi 13T
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240624-53b29fa-patch-3
```

### Anything else?

This seems to be an issue with Zink on Mali GPUs

**Comment by GaucovyAero** [comment]
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G610 MC6) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
```
your device does not meet base zink requirements
