### ISSUE TITLE
[BUG] <Keeps Crashing>

### ISSUE THREAD

**Issue by MustafaMokhtar** [PojavLauncherTeam/PojavLauncher#5695]
### Describe the bug

After i updated pojav to the latest build it just keeps crashing whenever i try to launch minecraft 1.19.2 or above

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16019396/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.launch Minecraft 1.19.2 or above
```

### Expected Behavior

I expected my game to launch normally

### Platform

```markdown
- Device model: RMX1971
- CPU architecture: ARM
- Android version: 11
- PojavLauncher version: foxglove
```

**Comment by GaucovyAero** [comment]
duplicate of #5657, update to the latest java 17 build from the android-openjdk-build-multiarch repo
