### ISSUE TITLE
[BUG] Fabric 1.20.1 would load but it crashes before showing main menu.

### ISSUE THREAD

**Issue by user96s-stuff** [PojavLauncherTeam/PojavLauncher#5696]
### Describe the bug

Fabric 1.20.1 would load but it crashes before showing main menu.

My mods are:

- Create Mod
- Immersive Portals
- Fabric API
-And a car datapack https://www.planetminecraft.com/data-pack/realistic-car-datapack-1-17

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16020001/latestlog.txt)
Github would not allow me to post all of it here.

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Run 1.20.1 Fabric.
3. Wait for game to load, and let it crash.
```

### Expected Behavior

To run Fabric without crashing.

### Platform

```markdown
- Device model: Acer Spin 311
- CPU architecture: x86_64
- Android version: 9.0
- PojavLauncher version: foxglove-20240626-df0b762-v3_openjdk (9939594)
```

### Anything else?

No.

**Comment by GaucovyAero** [comment]
remove create, it tries to access system cpu options for whatever reason, which android doesnt allow
