### ISSUE TITLE
All my textures are black and the world is super dark.

### ISSUE THREAD

**Issue by Eagl3r** [PojavLauncherTeam/PojavLauncher#5698]
### Describe the bug

Every time I open Optifine version 1.20, or just the normal version of Minecraft, all of my textures are black and the world is very dark. I uninstalled then reinstalled, but the problem wasn't fixed.

### The log file and images/videos

Unfortunately, I couldn't get any pictures.

### Steps To Reproduce

```markdown
1. Start Pojavlauncher.
2. Make a Optifine version 1.20 I5 pre5
3. Install the Optifine.
4. Load Minecraft.
5. Make a super flat world (or any type of world) then load it.
6. Your textures will be all black (well for me in this case)
Note that this is on the playstore version and not the APK file version.
```

### Expected Behavior

I expect it to work normally but it randomly started yesterday. (June 26)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: (Im on a Chromebook)
- PojavLauncher version: Java 21
```

**Comment by Eagl3r** [comment]
Please make a new update or something! By the way, this all started happening after I started using block displays.

**Comment by ThatMG393** [comment]
This may or may not be related to this issue: https://github.com/PojavLauncherTeam/PojavLauncher/issues/5646

**Comment by GaucovyAero** [comment]
yeah it is, please mention your model and cpu/gpu in that issue
