### ISSUE TITLE
[BUG] <latestlog.TxT>

### ISSUE THREAD

**Issue by bruh72** [PojavLauncherTeam/PojavLauncher#5699]
### Describe the bug

when im installing a forge or fabric to add mods,it crashes.please fix this

### The log file and images/videos

![Screenshot_20240628_172212](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174101450/38b3c262-341f-4fb4-ba27-2da5971b0095)  

### Steps To Reproduce

```markdown
what i did is cleared the cache of pojavlauncher but still,did not work,theres still "application/game exited with code 1,check latestlog.TxT for more details"Please fix this issue.
```

### Expected Behavior

i expected that if i cleared the cache it will work,but still ive watch yt tutorials on how to fix it but its not really working.

### Platform

```markdown
- Device model: Vivo 1808
- CPU architecture: arm64
- Android version: 8.1.0
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

this is only my problem about latestlog.TxT

**Comment by ThatMG393** [comment]
Please upload the `latestlog.txt` file.

**Comment by bruh72** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16027386/latestlog.txt)

**Comment by TarikBR** [comment]
> [latestlog.txt](https://github.com/user-attachments/files/16027386/latestlog.txt)

You are using the wrong java version, go to java preferences and select java 8 runtime (1.8)

**Comment by bruh72** [comment]
> > [latestlog.txt](https://github.com/user-attachments/files/16027386/latestlog.txt)
> 
> You are using the wrong java version, go to java preferences and select java 8 runtime (1.8)

**Comment by bruh72** [comment]
its still not working even if i do it,is there more ways to fix this？

**Comment by TarikBR** [comment]
> its still not working even if i do it,is there more ways to fix this？

Send the new `latestlog.txt`

**Comment by bruh72** [comment]
「
[latest.log](https://github.com/user-attachments/files/16027822/latest.log)
is this it？

**Comment by TarikBR** [comment]
> 「 [latest.log](https://github.com/user-attachments/files/16027822/latest.log) is this it？

No, i want `latestlog.txt`

**Comment by bruh72** [comment]
oh yeah i have a question,i think what happened is i extracted the mods in mods file

**Comment by TarikBR** [comment]
> oh yeah i have a question,i think what happened is i extracted the mods in mods file

Probably, you dont need to extract them

**Comment by bruh72** [comment]
YO MAN WHAT I JUST DID IS CLEARED THE CACHE,THEN DELETE THE EXTRACTED MODS,AND I SELECT JAVA RUNTIME TO 1.8

THANK YOU SO MUCH I CAN NOW PLAY MY MODS

（heres the screenshot)
![Screenshot_20240628_183235](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174101450/16c7582e-5012-4ed9-bc2d-3d50350c7cb0)
