### ISSUE TITLE
Bugs in Minecraft java

### ISSUE THREAD

**Issue by abdo-A028** [PojavLauncherTeam/PojavLauncher#57]
Banners are only the problem: no texture

**Comment by Azapru** [comment]
Really! 
![Screenshot_20200404_150521_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/78451398-adfd2d80-7685-11ea-85a7-dac3732dd183.jpg)

**Comment by khanhduytran0** [comment]
Latest preview?

**Comment by abdo-A028** [comment]
> Really!
> ![Screenshot_20200404_150521_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/78451398-adfd2d80-7685-11ea-85a7-dac3732dd183.jpg)

I am right, that was bad

**Comment by khanhduytran0** [comment]
You said anything were bad, but can you fix it?

**Comment by pedrosouzabrasil** [comment]
Hi from brazil!i would like to help you to find some bugs..there are some problems related to the horse models and the banners. I am very happy testing the latest version of this launcher on my samsung note 10!!i would like to say congratulations for khanduytran for this amazing project!

**Comment by pedrosouzabrasil** [comment]
I am using optifine on 1.11.2 by the way

**Comment by pedrosouzabrasil** [comment]
@khanhduytran0

**Comment by abdo-A028** [comment]
> You said anything were bad, but can you fix it?

Can you do it like boardwalk that did it 
Zhuowei Zhang

**Comment by khanhduytran0** [comment]
https://youtu.be/LjcD8rK5ic0 it's a bit different.

**Comment by khanhduytran0** [comment]
Use OpenJDK too.

**Comment by khanhduytran0** [comment]
So can you do anything like me or @ zhuowei?

**Comment by abdo-A028** [comment]
Why can't Banners are fixed on java

**Comment by khanhduytran0** [comment]
> Why can't Banners are fixed on java

I can't find where Minecraft loading banner texture, or by OpenGL.

**Comment by khanhduytran0** [comment]
Not sure if it is fixed in v3 since v3 have almost nothing worked.

**Comment by abdo-A028** [comment]
So we are dead on Minecraft
