### ISSUE TITLE
[BUG] Pojav Launcher keeps crashing for all versions and renderes

### ISSUE THREAD

**Issue by jadedgal** [PojavLauncherTeam/PojavLauncher#5703]
### Describe the bug

The launcher crashes irrespective to the amount of ram I am using

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16037188/latestlog.txt)
[latestlog.txt](https://github.com/user-attachments/files/16037192/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Click play on any version
3. Crash
```

### Expected Behavior

Crashes apon loading. Gui loads and then it crashes. 

### Platform

```markdown
- Device model: Google Pixel 3
- CPU architecture: Arm64
- Android version: 12
- PojavLauncher version: foxglove-202406210332de88-v3_openjdk
```

**Comment by GaucovyAero** [comment]
duplicate of #5657, update your java runtime to the latest from android-openjdk-build-multiarch repo

**Comment by Vino118** [comment]
Pls fix bug block invisible
