### ISSUE TITLE
[BUG]  External mouse does not work properly in "Foxglove" release version.

### ISSUE THREAD

**Issue by Kal19801** [PojavLauncherTeam/PojavLauncher#5704]
### Describe the bug

Mouse pointer not displaying properly, and problems during interactions

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/158162434/0f8e2411-c558-470b-9117-095f9f3d4760

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Connecting a Keyboard and Mouse
3. Access to the world
```

### Expected Behavior

I need it to work like the last pojav version.

### Platform

```markdown
- Device model: honor play5t
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by Kal19801** [comment]
The keyboard is normal, but the mouse is clearly not.

**Comment by GaucovyAero** [comment]
duplicate of #5648
