### ISSUE TITLE
Games keeps crashing with mods

### ISSUE THREAD

**Issue by KatazGuy** [PojavLauncherTeam/PojavLauncher#5705]
### Describe the bug

So now on the newest google play version my game is always crashing whenever i enter a new world play some time on it and try to open a new one or re enter the same world, this is extremely annoying when i try to use the Replay mod since the game keeps crashing when i load the world replay. This has happened without the Replay mod and while using other mods and has never happened before on older Pojav versions.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16037646/latestlog.txt)

### Steps To Reproduce

```markdown
1- Launch Minecraft with some mods on it (6 mods in my case)
2- open or create a world
3- exit that world and create a new world or re enter the same world
4- the game goes a black screen and closes itself on the loading screen
```

### Expected Behavior

The world opens correctly and doesn't crash

### Platform

```markdown
- Device model: Samsung Galaxy A31 5G/128GB
- CPU architecture: aarm64
- Android version: 12
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by TarikBR** [comment]
install this https://github.com/PojavLauncherTeam/FFmpegPlugin/releases/tag/v1.0
