### ISSUE TITLE
[BUG] Crash for no reason

### ISSUE THREAD

**Issue by DoriteLover** [PojavLauncherTeam/PojavLauncher#5706]
### Describe the bug

just launched and crashed

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16038581/latestlog.txt)

### Steps To Reproduce

```markdown
1. editing instance since new update clear everything
2. launched
3. crashed
```

### Expected Behavior

expectly to work perfectly

### Platform

```markdown
- Device model: samsung galaxy tab s6 lite wifi 4/64g
- CPU architecture: arm64,86
- Android version: 14,oneui6.0
- PojavLauncher version: lastest from playstore
```

### Anything else?

hi

**Comment by DoriteLover** [comment]
extra: it was 1.8.9

**Comment by GaucovyAero** [comment]
you cant play 1.8.9 with java 21, use java 8
