### ISSUE TITLE
[BUG] error -1

### ISSUE THREAD

**Issue by Luis1982Yt** [PojavLauncherTeam/PojavLauncher#5714]
### Describe the bug

I downloaded some mods and when i try to run it, it loads until the mojang white screen shows up (forge 1.7.10) and then close, idk why and even what the error means
I also tried to get the lastest.log but it doensnt shows up when i click to share to any options so idk
When the pojav closes to show up the error it says "error -1... Try latest.log.."

### The log file and images/videos

[latestlog(Copy).txt](https://github.com/user-attachments/files/16042744/latestlog.Copy.txt)

### Steps To Reproduce

```markdown
Start pov and click play
```

### Expected Behavior

The forge loading mods to show up

### Platform

```markdown
- Device model: Poco x3 Pro 128 gb
- CPU architecture: idk how to find thid
- Android version: 12
- PojavLauncher version: foxglove20240621-332de88-v3_openjdk
```

### Anything else?

No

**Comment by SolDev69** [comment]
Remove the discord RPC mod, doesn't work with Pojav
