### ISSUE TITLE
Solution For PowerVR GPUs

### ISSUE THREAD

**Issue by AnikyMX** [PojavLauncherTeam/PojavLauncher#5717]
### Is this request related to a bug?

Many are experiencing problems with the world and item textures turning black.

### Describe the request.

Provide alternative renders such as "vGPU" or "VirGL", these two renders are quite stable on devices that have a PowerVR GPU and this could be a solution for the world and item textures turning black.

**Comment by GaucovyAero** [comment]
you can move to solcraftlauncher if you want vgpu iirc
