### ISSUE TITLE
Black Minecraft interface when playing modpack last day of humanity 

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5718]
### Describe the bug

Download LDOH in the pojav's modpacks Library start the game and in the ui(my English is so bad:(.)

### The log file and images/videos

Idk

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I expect the modpack work correctly 

### Platform

```markdown
- Device model: Oppo Reno 3 
- CPU architecture: arm64
- Android version: corloros 12
- PojavLauncher version:  edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by ghost** [comment]
Send latestlog.txt to know how to fix it

**Comment by Hoanpojavlauncher** [comment]
> Send latestlog.txt to know how to fix it

Here is the lo ![latestlog.txt](https://github.com/user-attachments/files/16081020/latestlog.txt)

**Comment by GaucovyAero** [comment]
most likely a native crash, figure out which mod is causing it in the first place, and then create a new issue referencing that mod along with the adb bugreport file
