### ISSUE TITLE
When I try to enter a world the game crashes

### ISSUE THREAD

**Issue by J-Lazos** [PojavLauncherTeam/PojavLauncher#5719]
### Describe the bug

I'm using the modpack RLCraft and every time that I enter a world the game crashes. 

### The log file and images/videos

[crash-2024-07-01_10.48.06-client.txt](https://github.com/user-attachments/files/16056996/crash-2024-07-01_10.48.06-client.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Enter a world
3. When I enter a world the inventory UI is shown for a seconds and after that the game crashes.
```

### Expected Behavior

Entering the world normally. 

### Platform

```markdown
- Device model: Poco F5
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by ghost** [comment]
In order for RLCraft to not crash, remove these mods:
1:custommainmenumod
2:fancyblockparticles
3:dynamic surroundings
4:soundfilters

If you wanna install optifine for Rlcraft . After enter a world in invertory or in item list 50% of items have wierd black and pink texture for fix the issue you need to turn off (emissive textures) but after turn off game frezes and you can't turn off it for turn off this option go to pojav launcher files and enter (options.txt) and find emissive texture and write off and texture fix
