### ISSUE TITLE
Add Gamepad Support !!!

### ISSUE THREAD

**Issue by 5vixin** [PojavLauncherTeam/PojavLauncher#572]
Fucking taping while moving gives you a complete 180 its very fucking hard to move / fight / run away i keep dying to this please add like gamepad support holy shit

**Comment by artdeell** [comment]
Dev builds already fixed the accidental 180s during mouse use, and gamepad support will be added later

**Comment by WesleyVanNeck** [comment]
> Fucking taping while moving gives you a complete 180 its very fucking hard to move / fight / run away i keep dying to this please add like gamepad support holy shit

Do not curse or will be fucking baned

**Comment by WesleyVanNeck** [comment]
> > Fucking taping while moving gives you a complete 180 its very fucking hard to move / fight / run away i keep dying to this please add like gamepad support holy shit
> 
Do not curse or you will be fucking baned

**Comment by NOM425378** [comment]
> Dev builds already fixed the accidental 180s during mouse use, and gamepad support will be added later

>i cant wait to play it with X3 gamepad

**Comment by NOM425378** [comment]
i hope it will support more than xbox
