### ISSUE TITLE
[BUG] Better Than Wolves

### ISSUE THREAD

**Issue by NDG312** [PojavLauncherTeam/PojavLauncher#5720]
### Describe the bug

I followed the steps on discord to install better than wolves but my game always crashes.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16061090/latestlog.txt)

### Platform

```markdown
- Device model: Redmi Note 12
- CPU architecture: Adreno 610
- Android version: 14
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by ghost** [comment]
Why you close the issue

**Comment by NDG312** [comment]
i ínstalled the old pojavlauncher debug apk and installed this mod so i thought i should close this issue

**Comment by ghost** [comment]
Okay

**Comment by GaucovyAero** [comment]
updated guide here, its working now using foxglove

[INSTALL_BTW.pdf](https://github.com/user-attachments/files/16446593/INSTALL_BTW.pdf)

**Comment by GaucovyAero** [comment]
updated guide here, skins and usernames now work, prolly even multiplayer? idk i dont have whitelist
[INSTALL_BTW_updated_v1.1.pdf](https://github.com/user-attachments/files/16456993/INSTALL_BTW_updated_v1.1.pdf)

**Comment by NDG312** [comment]
I tried in my offline server BTW and my username works
