### ISSUE TITLE
[BUG] <Short description> crash blackscreen

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5721]
### Describe the bug

I don't know of any crashes that occur when I use optifabric

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16063721/latestlog.txt)
-

### Steps To Reproduce

```markdown
1.start pojav
2.blackscreen
```

### Expected Behavior

-

### Platform

```markdown
- Device model: rn 11
- CPU architecture: 
- Android version: 12
- PojavLauncher version:latest
```

**Comment by GaucovyAero** [comment]
update optifabric or remove it

**Comment by wayxyz89** [comment]
> update optifabric or remove it

Thanks
