### ISSUE TITLE
Minimap mods break textures

### ISSUE THREAD

**Issue by KatazGuy** [PojavLauncherTeam/PojavLauncher#5722]
### Describe the bug

Whenever i use any minimap mod (I've tried Xaero's Minimap and JourneyMap) the textures of entities and huds start slowly breaking by becoming in a plain white texture.

### The log file and images/videos

![Screenshot_20240702-034126_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/83526218/2c9d58c6-b3cc-4f4e-96e3-9d4004cbd7c7)
![Screenshot_20240702-034110_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/83526218/84be44a8-fc42-4b53-8fcc-335b6cc2c665)
![Screenshot_20240702-034410_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/83526218/ad6e9674-5bc5-4f10-a0c8-7b604ea6f56e)

### Steps To Reproduce

```markdown
1- play with any mods and a minimap mod (i use Journey map)
2- walk around for some time
3- you will start seeing that the textures of animals,enemies and some weapons start breaking in different ways
```

### Expected Behavior

The game works normally and the textures don't break

### Platform

```markdown
- Device model: Samsung Galaxy a31 5G/128GB
- CPU architecture: aarm64
- Android version: 12
- PojavLauncher version: Foxglove-20240621-332de88-v3_openjdk
```

**Comment by GaucovyAero** [comment]
means you are out of GPU memory
