### ISSUE TITLE
[BUG] <Crash Sinytra Connector>

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#5723]
### Describe the bug

i just run Sinytra Connector and he crashing

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16064967/latestlog.txt)

### Steps To Reproduce

```markdown
1 run forge with Sinytra Connector
2 wait
3 crash
```

### Expected Behavior

dont crashing Sinytra Connector

### Platform

```markdown
- Device model: teclast t40 pro
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: last ('https://github.com/PojavLauncherTeam/PojavLauncher/actions')
```

**Comment by GaucovyAero** [comment]
seems like it requries an X11 or Wayland desktop to run, which is not possible
