### ISSUE TITLE
Code -1 when using minecarft version 1.21

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5724]
### Describe the bug

I download java 21 from yt and install it.in pojav I add jre 21 and install minecarft 1.21 .I enter game and I have code-1

### The log file and images/videos

Herr is the lastestlog file:
[latestlog.txt](https://github.com/user-attachments/files/16065184/latestlog.txt)

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I think I can hit oneshot ender dragon with mace

### Platform

```markdown
- Device model: Oppo Reno 3 
- CPU architecture: arm64
- Android version: corloros 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by TarikBR** [comment]
Wrong log, this one you are playing in Minecraft forge 1.16.5

**Comment by Hoanpojavlauncher** [comment]
> Wrong log, this one you are playing in Minecraft forge 1.16.5

![latestlog.txt](https://github.com/user-attachments/files/16074494/latestlog.txt)

Is this?

**Comment by TarikBR** [comment]
> > Wrong log, this one you are playing in Minecraft forge 1.16.5
> 
> ![latestlog.txt](https://github.com/user-attachments/files/16074494/latestlog.txt)
> 
> Is this?

You are using a outdated launcher version, wich not support 1.21

**Comment by Hoanpojavlauncher** [comment]
> > > Wrong log, this one you are playing in Minecraft forge 1.16.5
> > 
> > ![latestlog.txt](https://github.com/user-attachments/files/16074494/latestlog.txt)
> > 
> > Is this?
> 
> You are using a outdated launcher version, wich not support 1.21

Yes cuz neww version has a light bug😭😭
