### ISSUE TITLE
[BUG] Чёрный мир

### ISSUE THREAD

**Issue by TopedGames** [PojavLauncherTeam/PojavLauncher#5727]
### Describe the bug

Когда я захожу на любую карту или сервер, весь мир и предметы чёрные.

### The log file and images/videos

![Screenshot_2024-07-02-21-00-26-83_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/150599356/9b437061-d6dc-4f57-b18c-aedd1713d3ca)

### Steps To Reproduce

```markdown
1. Запуск Pojavlauncher
2. Вход в мир
3. Баг
```

### Expected Behavior

Я предполагал что это всё с java связано, но я менял java, заходил на другие версии, нечего не менялось, всё чёрное.

### Platform

```markdown
- Device model: Realme Ц2
- CPU architecture: aarch64/arm64-v8a
- Android version: 9
- PojavLauncher version: foxglove-20240621
```

**Comment by GaucovyAero** [comment]
duplicate of #5646
