### ISSUE TITLE
Erro codigo -1 [BUG] <Short description>

### ISSUE THREAD

**Issue by Nauj749** [PojavLauncherTeam/PojavLauncher#5730]
### Describe the bug

I have error -1 When I try to enter my Forge I end up logging out immediately and the error message appears 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16075216/latestlog.txt)

### Steps To Reproduce

```markdown
1. start the pojav launcher 2. enter the desired version 3. exit the application due to the bug.
```

### Expected Behavior

I expected to go straight without any errors 

### Platform

```markdown
- Device model: samsung m23
- CPU architecture: 64 bits
- Android version: 14
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

When I change the runtime to internal 17, it closes but with code 1

**Comment by GaucovyAero** [comment]
install carbonconfig
