### ISSUE TITLE
[BUG] error code -1 forge 1.12.2 

### ISSUE THREAD

**Issue by Nayu481** [PojavLauncherTeam/PojavLauncher#5731]
### Describe the bug

When entering Minecraft Forge 1.12.2 the black loading screen appears after a while it does not load and it also closes with the error code -1, honestly don't know why it happens, since 1-2 days ago the error didn't appear. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16076035/latestlog.txt)
![Screenshot_20240702_215325_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/157756924/91d73637-7e1f-474a-83c7-41cfcd2f2127)

### Steps To Reproduce

```markdown
select forge 1.12.2 and press "start", see the black loading screen and wait but then the error occurs
```

### Expected Behavior

I hope the game loads correctly and that error does not appear [](url)

### Platform

```markdown
- Device model: samsung a22
- CPU architecture: Aarch64(64Bits)
- Android version: 13
- PojavLauncher version: play store
```

**Comment by GaucovyAero** [comment]
remove naruto mod addon, it has custom shaders that pojav is unable to convert
