### ISSUE TITLE
Error[BUG] <Short description>

### ISSUE THREAD

**Issue by Jacse64** [PojavLauncherTeam/PojavLauncher#5732]
### Describe the bug

Siempre ceintento iniciar sesión sale error

### The log file and images/videos

Y4

### Steps To Reproduce

```markdown
Ce medejen en trar
Ytu
```

### Expected Behavior

H4ur

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
U4
```

### Anything else?

Jr

**Comment by Jacse64** [comment]
Error

**Comment by Jacse64** [comment]
Error

**Comment by Jacse64** [comment]
Error

**Comment by GaucovyAero** [comment]
microsoft server issue, should be fine by now
