### ISSUE TITLE
The mouse cursor moves abnormally

### ISSUE THREAD

**Issue by CloudBack0601** [PojavLauncherTeam/PojavLauncher#5733]
### Describe the bug

My mouse is connected to my phone via the VGA docking station, and when I move the mouse, the in-game cursor can't be moved. I can only swipe the screen to turn the perspective instead of sliding the mouse

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16083236/latestlog.txt)

### Steps To Reproduce

```markdown
1.start projav launcher
2.Go to any save 
3.Use the VGA docking station to connect the mouse to the phone
4.Open the in-game cursor and slide the mouse, the in-game cursor will not move
```

### Expected Behavior

i would like there is an option inside the launcher to toggle the in-game cursor and use the system cursor like the older version of projavlauncher in 2023

### Platform

```markdown
- Device model: HUAWEI P30
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by artdeell** [comment]
Please try on this version of the launcher:
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9584072517
It's a little old, but if it works on this one then we know what the issue is

**Comment by CloudBack0601** [comment]
> Please try on this version of the launcher:
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9584072517
> It's a little old, but if it works on this one then we know what the issue is

No it still doesnt work ，may it  works on the modified versions like [this](https://github.com/Vera-Firefly/Pojav-Glow-Worm/releases/tag/20240414)

**Comment by CloudBack0601** [comment]
> > Please try on this version of the launcher:
> > https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9584072517
> > It's a little old, but if it works on this one then we know what the issue is
> 
> No it still doesnt work ，may it  works on the modified versions like [this](https://github.com/Vera-Firefly/Pojav-Glow-Worm/releases/tag/20240414)

And I discover that it works on v3.3.1

**Comment by BLSK666** [comment]
Probe esa versión de la aplicación, ahora me funciona el teclado pero no el raton.

Me refiero al primer enlace que pasaron, el segundo funciona perfectamente.

**Comment by artdeell** [comment]
@CloudBack0601 Hello, can you try it on this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9783677689

**Comment by BLSK666** [comment]
Acabo de probar la versión, la aplicación reconoce el teclado y el click
derecho e izquierda del rato pero no deja mover el rato y tampoco la camara.

**Comment by CloudBack0601** [comment]
> @CloudBack0601 Hello, can you try it on this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9783677689

It doesn't work on as well,

**Comment by BLSK666** [comment]
Sigue exactamente igual que en la prueba anterior, el teclado funciona
normalmente, click derecho e izquierda funcionan pero el raton se bloquea
por completo y no se puede mover ni girar la cámara, solo con la pantalla
tactil, quizas puede ser un caso de incompatibilidad con los controladores
para el uso de mandos. :v

**Comment by BLSK666** [comment]
Cuando lo probe desde la app en la play store, al entrar al juego este me reconocía la tecla espacio como la letra A de aceptar en un mando y el raton como una de las palancas del mando.

**Comment by CloudBack0601** [comment]
> > @CloudBack0601 Hello, can you try it on this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9783677689
> 
> It doesn't work on as well,

 This is a video described my issue [here](https://www.mediafire.com/file/osvum3omt2pngzl/mmexport1720065739994.mp4/file)

**Comment by Ferdyansy** [comment]
> @CloudBack0601 Hello, can you try it on this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9783677689

this still doesn't work :(

**Comment by CloudBack0601** [comment]
> > > @CloudBack0601 Hello, can you try it on this version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9783677689
> > 
> > It doesn't work on as well,
> 
>  This is a video described my issue [here](https://www.mediafire.com/file/osvum3omt2pngzl/mmexport1720065739994.mp4/file)

I found that if we remove“always grab the mouse and use the touchpad as the cursor”or make    it   a  functional botton to toggle it.The issue will be solved perfectly

**Comment by artdeell** [comment]
That is not a solution, as it does not address the root of this problem

**Comment by CloudBack0601** [comment]
> That is not a solution, as it does not address the root of this problem

But i see the author of another version of projav adding this opinion into a modified version.From that version the issue appears

**Comment by artdeell** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9793515570
Try this version

**Comment by BLSK666** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9793515570 Pruebe esta versión

Funciona ya perfectamente

**Comment by CloudBack0601** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9793515570
> Try this version

There was a slight difference, but at least it worked on well

**Comment by Ferdyansy** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9793515570 Coba versi ini

This works but on Android 9 and below left click can't work

**Comment by artdeell** [comment]
> > https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9793515570 Coba versi ini
> 
> This works but on Android 9 and below left click can't work

Hello. I have tested this version on a device with Android 8.1 and I am unable to reproduce your issue.
Can you please re-test on this version specifically:
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9798562521

and tel me the model of your device?

**Comment by Ferdyansy** [comment]
> > > https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9793515570 Coba versi ini
> > 
> > 
> > Ini berfungsi tetapi pada Android 9 dan di bawahnya klik kiri tidak dapat berfungsi
> 
> Halo. Saya telah menguji versi ini pada perangkat dengan Android 8.1 dan saya tidak dapat menemukan masalah Anda. Bisakah Anda menguji ulang pada versi ini secara khusus: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9798562521
> 
> dan beri tahu saya model perangkat Anda?

Device Oppo a12
Cpu architecture arm64
android 9

**Comment by Ferdyansy** [comment]
> > > https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9793515570 Coba versi ini
> > 
> > 
> > This works but on Android 9 and below left click can't work
> 
> Hello. I have tested this version on a device with Android 8.1 and I am unable to reproduce your issue. Can you please re-test on this version specifically: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9798562521
> 
> and tel me the model of your device?

I have used pojav launcher and the cursor can move, but I have a problem when I left click the menu button it doesn't work, and also when in the game I can't destroy blocks, when I press left click my screen is stuck and doesn't work

**Comment by artdeell** [comment]
Please re-test on the latest build:
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9813527583

Note: left click may still not work properly

**Comment by CloudBack0601** [comment]
> Please re-test on the latest build:
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9813527583
> 
> Note: left click may still not work properly

It works well,but why LWJGL is still 3.3.1,Minecraft 1.21 with  modified sodium can't run

**Comment by Ferdyansy** [comment]
> Please re-test on the latest build: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9813527583
> 
> Note: left click may still not work properly

left click still doesn't work, but the others have worked, like placing block and moving the screen, maybe I have to download an old version of Pojavlauncher so that it can bring up an external cursor (because Pojav's default cursor doesn't work) but it doesn't support 1.21

**Comment by CloudBack0601** [comment]
> > Please re-test on the latest build: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9813527583
> > 
> > Note: left click may still not work properly
> 
> left click still doesn't work, but the others have worked, like placing block and moving the screen, maybe I have to download an old version of Pojavlauncher so that it can bring up an external cursor (because Pojav's default cursor doesn't work) but it doesn't support 1.21

I think u r right. projav's default cursor looks so bad and it is uncomfortable to control,the external cursor like android's is good.

**Comment by Ferdyansy** [comment]
> > > Please re-test on the latest build: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9813527583
> > > Note: left click may still not work properly
> > 
> > 
> > left click still doesn't work, but the others have worked, like placing block and moving the screen, maybe I have to download an old version of Pojavlauncher so that it can bring up an external cursor (because Pojav's default cursor doesn't work) but it doesn't support 1.21
> 
> I think u r right. projav's default cursor looks so bad and it is uncomfortable to control,the external cursor like android's is good.

yes, the old pojav external cursor is better
