### ISSUE TITLE
A specific screen problem for Samsung S23fe devices

### ISSUE THREAD

**Issue by beratbaa** [PojavLauncherTeam/PojavLauncher#5735]
### Describe the bug

![Screenshot_20240629_120039_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174627377/a7a72b9f-0752-4fcc-931f-b2b2bd71721e)

I don't know how to describe it.I've tested on two diffrent S23fes and got the same result.Using Zink(Vulkan).Minecraft version is 1.19.4 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16086766/latestlog.txt)

### Steps To Reproduce

```markdown
It is enough to starting game
```

### Expected Behavior

Working normally

### Platform

```markdown
- Device model:Samsung S23fe 
- CPU architecture:Exynos2200
- Android version:14
- PojavLauncher version:foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
we dont develop zink, if the gpu is not supported, its just not
