### ISSUE TITLE
Fps limited did not working

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#574]
I try using vsync and as we know vsync will get our game same refresh rate like our phone refresh rate... Example: 60Hz phone..... the game will run 60fps and not more then that.. But why when I am turning on vsync.. The game have more then 60fps(My phone refresh rate 60hz) Pls fix this...

**Comment by WesleyVanNeck** [comment]
You don't need it as your phone has vsync

**Comment by khanhduytran0** [comment]
VSync is just for fixing screen tearing, what you need is Maximum FPS, did you limit?

**Comment by Adam0530** [comment]
> VSync is just for fixing screen tearing, what you need is Maximum FPS, did you limit?

I dont need more then my fps limit phone(60Hz) Because I read that more then our refresh rate monitor(fps) will not be showen or effect anything.... My game feel lagging even the fps show 90fps(It feel like I am having 30fps) and the only way that I will got 60fps experience is by having 120fps or more... Thats why I need the fps need to be limited and vsync too (vsynce make my game smoother, I have tried it on minecraft 1.16.4 using sodium... it has really much different when I am turning on vsync(feel even more smoother))....
