### ISSUE TITLE
Duble chech GeForce deleting

### ISSUE THREAD

**Issue by Sebz102030** [PojavLauncherTeam/PojavLauncher#5746]
### Is this request related to a bug?

IT is note related to bug

### Describe the request.

I would like to request duble chęci if you wants to delete instalation because I mamy times deleted instalation that I woned to play

**Comment by Sebz102030** [comment]
I ment before note GeForce my autocorect simetimes changes

**Comment by GaucovyAero** [comment]
duplicate of #5625
