### ISSUE TITLE
[BUG] Models with wrong textures

### ISSUE THREAD

**Issue by lulesus** [PojavLauncherTeam/PojavLauncher#5747]
### Describe the bug

i really dont know but, using only the tech guns mod cause this issue

### The log file and images/videos

![Screenshot_20240704-191938](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174751584/c6c5ce82-06ac-47bb-8818-aa1bea854f4a)
![Screenshot_20240703-181604](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174751584/9986534f-1f8b-4aa5-8332-ae8827c03961)
![Screenshot_20240703-180831](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174751584/bce1d7b8-9a80-4108-8e4d-2710b817c2cb)

### Steps To Reproduce

```markdown
start pojavlauncher
install the techguns mod
enter a world/server
```

### Expected Behavior

only to crash or something

### Platform

```markdown
- Device model: motorola one macro
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
you are out of gpu memory
