### ISSUE TITLE
[BUG] Minecraft will black screen after switching screens

### ISSUE THREAD

**Issue by senina4** [PojavLauncherTeam/PojavLauncher#5748]
### Describe the bug

Minecraft will black screen after switching screens

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16109514/latestlog.txt)
Video: https://github.com/PojavLauncherTeam/PojavLauncher/assets/84493324/3fceba68-1550-465c-8d26-9fa2759fee92

### Steps To Reproduce

```markdown
```

### Expected Behavior

The screen should not be black. 

### Platform

```markdown
- Device model: Realme 10pro
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by TylerHaoNhot** [comment]
I think the game just reload it self. Check the log to see if the game is starting over again. My friend have this issues on his Vivo Y15a too.

**Comment by senina4** [comment]
> I think the game just reload it self. Check the log to see if the game is starting over again. My friend have this issues on his Vivo Y15a too.

No. It didn't auto restart, Because I can clearly hear Minecraft sound.

**Comment by lzfddkd** [comment]
You can try to off the option"Use alternate surface rendering"

**Comment by senina4** [comment]
> You can try to off the option"Use alternate surface rendering"

Oh it worked!
