### ISSUE TITLE
When I install forge 1.16.3 it's just that ridiculous screen!

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#575]
When I install forge 1.16.3 it's just that ridiculous screen!
![Screenshot_20210107-203625_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/103957067-a6911600-5128-11eb-9c82-f66011ca088d.jpg)

**Comment by khanhduytran0** [comment]
Update to latest build.

**Comment by OwzygZawg** [comment]
????

**Comment by OwzygZawg** [comment]
NOT understand

**Comment by khanhduytran0** [comment]
V3.3.0 **does not support** forge 1.14+

**Comment by khanhduytran0** [comment]
V3.3.1 does https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/468350828

**Comment by OwzygZawg** [comment]
In fact I am in version 3.3.1 the latest! the link you sent does nothing

**Comment by OwzygZawg** [comment]
Bruh

**Comment by khanhduytran0** [comment]
But it should not display that screen.

**Comment by OwzygZawg** [comment]
This also happens with Fabric 1.16 when I install the modmenu does not appear

**Comment by OwzygZawg** [comment]
💯

**Comment by OwzygZawg** [comment]
:/

**Comment by Malaska678** [comment]
@OwzygZawg Forge 1.14+ worked! Special thanks to @ReclusionsHD for his method:
Add -Dfml.earlyprogresswindow=false to JVM Arguments and run!
EDIT: the JVM arguments above is added by default since this build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/418593909

A simpler Forge 1.13.2+ installer will be added soon.

**Comment by khanhduytran0** [comment]
Well does **Mod menu** available on mods folder? Fabric does not include with a mod manager! If Fabric mods won't load, known issue.

**Comment by Malaska678** [comment]
I think he need to cleardata

**Comment by OwzygZawg** [comment]
Mod menu in file mods?

**Comment by OwzygZawg** [comment]
> @OwzygZawg Forge 1.14+ funcionou! Agradecimentos especiais a @ReclusionsHD por seu método:
> Adicione -Dfml.earlyprogresswindow = false aos Argumentos JVM e execute!
> EDITAR: os argumentos JVM acima são adicionados por padrão desde esta compilação https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/418593909
> 
> Um instalador mais simples do Forge 1.13.2+ será adicionado em breve.

Where should i put? Record a tutorial to let me know

**Comment by OwzygZawg** [comment]
> Bem, o **menu Mod está** disponível na pasta mods? Tecido não inclui com um gerenciador de mod! Se os mods do Fabric não carregam, é um problema conhecido.

Modmenu not in files mods

**Comment by khanhduytran0** [comment]
> Fabric does not include with a mod manager!

**Comment by OwzygZawg** [comment]
Okay

**Comment by khanhduytran0** [comment]
> Where should i put? Record a tutorial to let me know

JVM arguments.
