### ISSUE TITLE
Iris with holy render.

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5754]
### Is this request related to a bug?

Maybe. I can't use shader with iris mod.

### Describe the request.

This is not a request. This is a question about how or can I use shaders on iris shader. If can, how to use it.

### Anything else?

When install a shader, the shader doesn't render and show some errors in chat.

Information:
Gpu: adreno 640 - snap 855
Render: Holy

**Comment by GaucovyAero** [comment]
not possible, as gl4es does not have enough opengl extensions to support shaders that are regularly used on PC

**Comment by ghost** [comment]
Yes you need use zink renderer
