### ISSUE TITLE
Sound physics mod 1.12.2 And Sound filter Mod 1.12.2

### ISSUE THREAD

**Issue by Renerosal01234** [PojavLauncherTeam/PojavLauncher#5756]
### Describe the bug

Whrn I use Sound physics mod 1.12.2 it remove the game sound and I use Sound filter it crash my game

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16115493/latestlog.txt)

### Steps To Reproduce

```markdown
1. Use Sound physics 
2. Start the Pojavlauncher 
3. In Minecraft menu no sound 
Create world no sound either 
4. Use Sound filter 
5. After finish create the world loading crash the game
```

### Expected Behavior

Working with sound and no cradh

### Platform

```markdown
- Device model: Poco c65
- CPU architecture: 64
- Android version: 14 8/250gb
- PojavLauncher version: latest update GitHub or Pojavlauncher Google play
```

### Anything else?

Plss fix

**Comment by Dilen0001** [comment]
.

**Comment by Renerosal01234** [comment]
The midnight mod it's same problem no sound too

**Comment by GaucovyAero** [comment]
id say its just because these mods werent designed to run on android and in this case it matters
