### ISSUE TITLE
[BUG] game crash

### ISSUE THREAD

**Issue by Razapixelwt** [PojavLauncherTeam/PojavLauncher#5757]
### Describe the bug

When I try playing 1.20.1 game crash with code 1 error

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16116169/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Play version 1.20.1
3. game crash with error code 1
```

### Expected Behavior

I have try yt tutorial too non of them worked

### Platform

```markdown
- Device model: OnePlus 6 
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest for play store
```

### Anything else?

I try fabric, forge, optfine, even vanilla crash
With no mod too

**Comment by GaucovyAero** [comment]
use java 17 from the android-openjdk-build-multiarch repo instead
