### ISSUE TITLE
My Game Crash (I don't know how to fix it)

### ISSUE THREAD

**Issue by DarienM-2013** [PojavLauncherTeam/PojavLauncher#5758]
### Describe the bug

I honestly don't know what happened. I was trying to copy A WORLD FOLDER from Alpha 1.20. Then My Computer Restarted. I opened the app and every time I loaded any version it crashes. I have no idea how to fix it

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16117056/latestlog.txt) (The File is in Preview)

### Steps To Reproduce

```markdown
1 Start a world in the only version of infdev
2 Update the world through THESE VERSIONS: A1.04 A1.017 A1.10 A1.12 And A1.20.
3 Copy the world While in Minecraft 1.0 (Then My Computer Crashed)
```

### Expected Behavior

The Game is supposed to load instead of crash

### Platform

```markdown
- Device model: Its a chromebook Idk what model
- CPU architecture: arm 64
- Android version: Version 13
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

Heres a video of what happens
[Screen recording 2024-07-06 2.46.21 PM.webm](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174901394/e2a6adfb-5def-4bcd-8eb0-a9c53e2087f9)

**Comment by AndreCodin24** [comment]
Have you tried use Zink (Vulkan) to make it work?

**Comment by DarienM-2013** [comment]
I did but it still crashes. Could We Try getting the data files from net.kdt.pojavlaunch (They're: caciocavallo, caciocavallo17,controlmap, and lwjgl3 and .minecraft) from someone else. I have realized that if you delete the files in the net.kdt.povjavlaunch the folders won't come back even if you uninstall and reinstall the app

**Comment by GaucovyAero** [comment]
duplicate

**Comment by DarienM-2013** [comment]
Could you make an update if the files are corrupted or missing then replace the files with new files in the Android data folder
