### ISSUE TITLE
Double clicking toggles fullscreen

### ISSUE THREAD

**Issue by usjrjfj** [PojavLauncherTeam/PojavLauncher#5759]
### Describe the bug

When i try to play, almost every time I click it toggles the fullscreen, making it completely unplayable.

### The log file and images/videos

It constantly toggles fullscreen on every click.

### Steps To Reproduce

```markdown
start pojavlauncher,
double click while moving the mouse
```

### Expected Behavior

double clicking while moving the mouse eg pvping wouldnt toggle fullscreen

### Platform

```markdown
- Device model: samsung galaxy tablet s9+
- CPU architecture: 
- Android version: latest
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
this is a hardcoded android shortcut (shift + w or w = F11) means you have to rebind the fullscreen key in minecraft settings
