### ISSUE TITLE
*small* issues with keyboard and mouse

### ISSUE THREAD

**Issue by Dimon245** [PojavLauncherTeam/PojavLauncher#576]
So, thanks to artdell most of the bugs regarding keyboard and mouse use are fixed, but there are 3 I noticed that are small, so you could take your time fixing them, cause they bring discomfort, but the game is playable, I guess.
1. C̶a̶n̶'̶t̶ s̶h̶i̶f̶t̶ c̶l̶i̶c̶k̶ (̶s̶h̶i̶f̶t̶ +̶ l̶e̶f̶t̶ ̶c̶l̶i̶c̶k̶ i̶n̶ G̶U̶I̶'̶s̶ t̶o̶ m̶o̶v̶e̶ y̶o̶u̶r̶ i̶t̶e̶m̶s̶ f̶a̶s̶t̶e̶r̶)̶.̶ I̶t̶'̶s̶ j̶u̶s̶t̶ n̶o̶n̶ f̶u̶n̶c̶t̶i̶o̶n̶a̶l̶,̶ b̶u̶t̶ d̶o̶e̶s̶n̶'̶t̶ b̶l̶o̶c̶k̶ j̶u̶s̶t̶ l̶e̶f̶t̶ c̶l̶i̶c̶k̶i̶n̶g̶
2. Can't ctrl-click (ctrl + left click in creative inventory to duplicate an item completely with its nbt tags and stuff left intact)
3. C̶a̶n̶'̶t̶ ̶r̶i̶g̶h̶t̶ ̶c̶l̶i̶c̶k̶ ̶i̶n̶ ̶G̶U̶I̶'̶s̶ ̶(̶y̶e̶a̶h̶,̶ ̶a̶r̶t̶d̶e̶l̶l̶ ̶y̶o̶u̶ ̶t̶o̶l̶d̶ ̶m̶e̶ ̶y̶o̶u̶ ̶f̶i̶x̶e̶d̶ ̶i̶t̶ ̶s̶o̶ ̶i̶t̶ ̶m̶i̶g̶h̶t̶ ̶o̶n̶l̶y̶ ̶b̶e̶ ̶a̶ ̶b̶u̶g̶ ̶o̶n̶ ̶m̶y̶ ̶m̶o̶u̶s̶e̶)̶.̶ ̶I̶t̶ ̶d̶o̶e̶s̶n̶'̶t̶ ̶e̶v̶e̶n̶ ̶w̶o̶r̶k̶ ̶o̶n̶ ̶T̶o̶o̶l̶b̶o̶x̶ ̶f̶o̶r̶ ̶M̶i̶n̶e̶c̶r̶a̶f̶t̶ ̶B̶e̶d̶r̶o̶c̶k̶,̶ ̶s̶o̶ ̶i̶t̶ ̶m̶i̶g̶h̶t̶ ̶j̶u̶s̶t̶ ̶b̶e̶ ̶m̶y̶ ̶m̶o̶u̶s̶e̶.̶.̶
4. T̶h̶i̶s̶ ̶d̶o̶e̶s̶n̶'̶t̶ ̶a̶f̶f̶e̶c̶t̶ ̶t̶h̶e̶ ̶l̶a̶t̶e̶s̶t̶ ̶v̶e̶r̶s̶i̶o̶n̶ ̶o̶f̶ ̶M̶C̶,̶ ̶s̶o̶ ̶I̶'̶m̶ ̶n̶o̶t̶ ̶s̶u̶r̶e̶ ̶i̶f̶ ̶y̶o̶u̶'̶d̶ ̶f̶i̶x̶ ̶i̶t̶,̶ ̶b̶u̶t̶ ̶h̶e̶r̶e̶ ̶y̶o̶u̶ ̶g̶o̶:̶ ̶i̶n̶ ̶1̶.̶1̶2̶.̶2̶ ̶(̶a̶ ̶v̶e̶r̶s̶i̶o̶n̶ ̶t̶o̶ ̶w̶h̶i̶c̶h̶ ̶m̶o̶s̶t̶ ̶h̶u̶g̶e̶ ̶m̶o̶d̶s̶ ̶a̶r̶e̶ ̶u̶p̶d̶a̶t̶e̶d̶)̶ ̶s̶p̶a̶c̶e̶ ̶t̶o̶ ̶j̶u̶m̶p̶ ̶d̶o̶e̶s̶n̶'̶t̶ ̶w̶o̶r̶k̶ ̶(̶b̶u̶t̶ ̶r̶e̶b̶i̶n̶d̶i̶n̶g̶ ̶i̶t̶ ̶t̶o̶ ̶a̶n̶o̶t̶h̶e̶r̶ ̶k̶e̶y̶ ̶w̶o̶r̶k̶s̶ ̶f̶i̶n̶e̶)̶ ̶e̶v̶e̶n̶ ̶t̶h̶o̶u̶g̶h̶ ̶y̶o̶u̶ ̶c̶a̶n̶ ̶s̶e̶t̶ ̶i̶t̶ ̶t̶o̶ ̶"̶s̶p̶a̶c̶e̶"̶ ̶i̶n̶ ̶t̶h̶e̶ ̶s̶e̶t̶t̶i̶n̶g̶s̶.̶ ̶

4.5. Also, when you go into a GUI or menu your aim tilts upwards when you get out of it.
Edit: it actually does happen on the latest version (4.5), but not every time. I'm not sure how it works, but I hope it gets fixed. Especially in 1.12.2
5. I just noticed when playing that when you press tab your mouse toggles between being usable and non-usable. Not sure if this is a bug, seems like it could be the same on PC

Thanks for reading and most importantly, listening

**Comment by Dimon245** [comment]
Thanks for fixing shift-clicking

**Comment by artdeell** [comment]
)

пт, 15 янв. 2021 г., 22:14 Dimon245 <notifications@github.com>:

**Comment by Dimon245** [comment]
Omg, I thought you didn't notice this thread, cause you didn't reply, but now that you did I have some peace of mind. 
I hope you fix the 1.12.2 related issues too, especially space bar not working.

**Comment by khanhduytran0** [comment]
@Dimon245 are all fixed?

**Comment by Dimon245** [comment]
Not sure about #5, but the first 2 which I didn't strikethrough are totally not fixed.
There's actually one other thing that'd been bothering me: even when you type in creative inventory, it still closes itself when you type "e". This is not PC behaviour

**Comment by artdeell** [comment]
> Not sure about #5, but the first 2 which I didn't strikethrough are totally not fixed.
> There's actually one other thing that'd been bothering me: even when you type in creative inventory, it still closes itself when you type "e". This is not PC behaviour

I can disable hwkeys for the software keyboard, but I'm not sure if it would work good...

**Comment by Dimon245** [comment]
yeah, not sure how you'd fix it either, since you still need to be able to use "e" to close inventory once you stop searching items

**Comment by ImaDoor2785** [comment]
That's not an issue with pojav that's an actual minecraft feature
You have to press esc when searching

**Comment by Dimon245** [comment]
@ImaDoor2785, loool. Then, what do I do if I have a Bluetooth Samsung Tab keyboard that doesn't have an Esc key? I can't really rebind it, can I?

**Comment by ImaDoor2785** [comment]
Go out of the search tab and then press e

**Comment by Dimon245** [comment]
doesn't work, I've tried. I mean, the initial issue was not being able to type "e" into the search bar

**Comment by ImaDoor2785** [comment]
Guess you'll have to press the back button instead

**Comment by Dimon245** [comment]
read the edit

**Comment by ImaDoor2785** [comment]
Ok never mind then I don't have that issue though

**Comment by ImaDoor2785** [comment]
What version are you on

**Comment by Dimon245** [comment]
1.12.2
Latest pojav build

**Comment by ImaDoor2785** [comment]
I mean launcher version because on the latest dev build I don't get that issue
I'll check with a keyboard right now just to be sure though

**Comment by ImaDoor2785** [comment]
Ok on 1.12.2 using a real keyboard e exits the inventory even when searching like you said 
But on 1.16.5 e works like normal

And middle click still acts as the back button for me

**Comment by Dimon245** [comment]
Ok, thanks for checking

Nah, middle click works for me, oddly

**Comment by REYASKANNAN** [comment]
I can't click any of the single player or multiplayer even I can't click quit game the mouse is working but couldn't click even I click the home button on mobile and clear on the minimize and again went to pohavlanchur multipletimes but still I won't work

But that problem in fabric 1.16.5 but I can use normal vinnila 1.16.5 I can click on 1.16.5 also I really need the fabric
Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…

**Comment by REYASKANNAN** [comment]
![Uploading Screenshot_2022-06-12-07-43-58-255_net.kdt.pojavlaunch.debug.jpg…]()

**Comment by Mathias-Boulay** [comment]
Hey there @Dimon245 How many issues can you still reproduce with the current build of pojav ?

**Comment by artdeell** [comment]
All of them were fixed very long ago, if you have any more please open a new issue
