### ISSUE TITLE
The pojavlauncher in the foxglove update has a different text when saving the world and also the color of the items in the inventory is a little off, please fix this along with mods [BUG] <Short description>

### ISSUE THREAD

**Issue by Daviliraushs** [PojavLauncherTeam/PojavLauncher#5760]
### Describe the bug

![Screenshot_20240706-203419_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/92885b23-843b-43b2-ba4e-f77e289aa018)
The pojavlauncher in the foxglove update has a different text when saving the world and also the color of the items in the inventory is a little off, please fix this along with mods [BUG] <Short description>

### The log file and images/videos

![Screenshot_20240706-204310_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/99515963-ad98-40c5-a3fd-99d086ed57c1)

### Steps To Reproduce

```markdown
pojavlauncher has a constant bug in the game text when we enter the world and then click on the inventory the items become a bit dark
```

### Expected Behavior

![Screenshot_20240706-204153_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/a42b27a0-5cd5-49a7-9694-c06f373ba881)
the lava blackout bug

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version:
- PojavLauncher version:
```

### Anything else?

![Screenshot_20240706-204310_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/1d6aa438-e7de-4518-b091-0aca48882504)
menu with different text please fix this

**Comment by GaucovyAero** [comment]
what device

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
