### ISSUE TITLE
Font is gone

### ISSUE THREAD

**Issue by piercr** [PojavLauncherTeam/PojavLauncher#5762]
### Describe the bug

There is no text font

### The log file and images/videos

![Uploading Screenshot_20240707_152112_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

### Steps To Reproduce

```markdown
Idk what this is
```

### Expected Behavior

Pls fix i need to read stuff to know what stuff is

### Platform

```markdown
- Device model: Samsung A55 5G
- CPU architecture: 4 x 2.05GHz
                    4 x 2.75GHz
- Android version: 14
- PojavLauncher version:
foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

Every single letter is gone

**Comment by piercr** [comment]
Pls fix ASAP

**Comment by piercr** [comment]
I used forge 1.20.1 latest

**Comment by GaucovyAero** [comment]
duplicate

**Comment by piercr** [comment]
Fixed it
