### ISSUE TITLE
[F-Req] Add Neoforge Profile

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5765]
### Is this request related to a bug?

![Screenshot_20240708_194834](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/c7e26cc3-1fd1-4bd2-9261-be0bfa64db12)

### Describe the request.

Add Create NeoForge Profile To Pojav Launcher

### Anything else?

Please Add This Feature

**Comment by kasrarouhi** [comment]
Your request is in build

**Comment by kasrarouhi** [comment]
![Screenshot_۲۰۲۴-۰۷-۰۸-۱۷-۴۳-۲۵-۵۷۴_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/e963b3b9-e0c8-40b4-aa80-50744fa8fc55)

**Comment by Dilen0001** [comment]
When Will It Be Released With App-Debug

**Comment by GaucovyAero** [comment]
duplicate
