### ISSUE TITLE
[BUG] Forge can't run with mods

### ISSUE THREAD

**Issue by K1r1kRuina** [PojavLauncherTeam/PojavLauncher#5767]
### Describe the bug

I can't launch Minecraft with mods, it says that permission for mod.jar file is denied

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16138287/latest.log)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Use forge - 1.18.2-forge-40.2.21
3. Wait 5-10 seconds
4. Get an error "1"
```

### Expected Behavior

1. Start PojavLauncher
2. Use forge - 1.18.2-forge-40.2.21
3. Wait some time
4. See red "Mojang" loading screen
5. Play

### Platform

```markdown
- Device model: Tecno POVA 5
- CPU architecture: arm
- Android version: 13
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try using a different file manager to move the file

**Comment by K1r1kRuina** [comment]
> try using a different file manager to move the file

Thank you my guy, never thought my file manager could be the reason
Anyway, huge thanks, you're a life-saver. ♥
