### ISSUE TITLE
[BUG] 1.7.10 forge game exit 0

### ISSUE THREAD

**Issue by lgsanai** [PojavLauncherTeam/PojavLauncher#5768]
### Describe the bug

So yeah I wanted to play fisk superhero mod for that I need 1.7.10 forge but when I install it and open it it crash's immediately and I found same here to and the answer was use java 8 I did still didn't work please help me wanna play that mod

### The log file and images/videos

Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on May  4 2024 09:53:01
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClientActiveTexture is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glVertexPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormalPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColorPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glEnableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDisableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glShadeModel is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFunc is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLogicOp is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMatrixMode is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadIdentity is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSize is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFuncx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearColorx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearDepthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4ub is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDepthRangex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetFixedv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLineWidthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawArrays is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawElements is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthof is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthox is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizePointerOES is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPolygonOffsetx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPopMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPushMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glSampleCoveragex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvi is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatex is NULL
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClientActiveTexture is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glVertexPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormalPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColorPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glEnableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDisableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glShadeModel is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFunc is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLogicOp is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMatrixMode is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadIdentity is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSize is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFuncx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearColorx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearDepthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4ub is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDepthRangex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetFixedv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLineWidthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawArrays is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawElements is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthof is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthox is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizePointerOES is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPolygonOffsetx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPopMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPushMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glSampleCoveragex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvi is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatex is NULL
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  (29066): dlopen libgl4es_114.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (29066): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success
I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  (29066): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (29066): dlopen /data/app/~~dmHqTzg5ViDYH6v5uA8zPw==/net.kdt.pojavlaunch-EcCoqrbMIkKctszuXnvknw==/lib/arm64/libopenal.so success

I/jrelog  (29066): Done processing args
I/jrelog  (29066): Found JLI lib
I/jrelog  (29066): Calling JLI_Launch

Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java Exit code: 1
I/jrelog  (29066): Going to free args
I/jrelog  (29066): Free done

### Steps To Reproduce

```markdown
Open 1.7.10 forge
 it closes immediately
```

### Expected Behavior

It should open and I should play it

### Platform

```markdown
- Device model: Infinix note 30
- CPU architecture: 64 bit
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

I installed the optifine 1.7.10 and it opened and ran beautifully but I think the problem is with forge

**Comment by GaucovyAero** [comment]
use java 8

**Comment by lgsanai** [comment]
> use java 8

I don't have java 8 how do I install it

**Comment by ghost** [comment]
It's impossible you don't have hava 8 because if you delete it download automatically
![Screenshot_۲۰۲۴-۰۷-۱۰-۱۵-۰۸-۴۹-۸۵۶_net kdt pojavlaunch debug-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/1668ac14-443e-4b94-b87b-f270b538cd70)

**Comment by lgsanai** [comment]
It is set by default already still doesn't work

**Comment by lgsanai** [comment]
![Uploading Screenshot_20240710-182541.jpg…]()
