### ISSUE TITLE
How to report bug?

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#577]
I dont find any option to report bug or enhanment 
![Screenshot_20210108_162854](https://user-images.githubusercontent.com/76242887/103992189-b2cfae80-51ce-11eb-9cf1-57d084b635e1.jpg)

**Comment by IG3R** [comment]
English: every time I download a client or a forge appears "Application / Game closed with code 1" helps me please
Português: todo vez que vou baixar um cliente ou um forge aparece "Aplicativo/Jogo fechou com códico 1" me ajuda pofavor

**Comment by kasrarouhi** [comment]
[BUG] Cloud are chunk chunk and trees are black
![Screenshot_۲۰۲۳-۰۷-۲۸-۰۴-۵۹-۵۳-۳۹۴_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/ade4d991-aa51-4116-b963-77f0182db7af)
![Screenshot_۲۰۲۳-۰۷-۲۸-۰۴-۵۶-۳۳-۹۶۱_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/7bb04ece-0c15-4724-8171-5a379e127ad7)

**Comment by ghost** [comment]
[BUG] my game crash in zink render in snapdragon 7+ gen 2 and adreno 725 graphic card you saying zink render support adreno graphic card but my game crashes my phone is xiaomi poco f5

**Comment by Bel69420** [comment]
Probably, your phone doesn't compatible with Turnip Driver either your phone isn't rooted.

**Comment by Bel69420** [comment]
Turnip Driver doesn't support Adreno 7xx at the moment.

**Comment by Bel69420** [comment]
Some of them works with turnip

**Comment by Bel69420** [comment]
With adren 7xx series
