### ISSUE TITLE
[BUG] Offlinemode/local mode

### ISSUE THREAD

**Issue by ly-nxs** [PojavLauncherTeam/PojavLauncher#5771]
### Is this request related to a bug?

You claim to not support piracy, yet I can make an offline/local account and play without paying...

### Describe the request.

Remove local account option or make it just the java trial version

### Anything else?

I got muted from the Minecraft discord for talking about pojav lol fuck Microsoft

**Comment by ly-nxs** [comment]
I read the page on offlinemode is going places and I tried and I could still download and play Minecraft (after clearing app cache and storage)

**Comment by GaucovyAero** [comment]
yeah this has been mentioned already (its an open issue), closing this as a duplicate

**Comment by ghost** [comment]
No i think add local account is best idea developers do and you think minecraft is full of security to use Microsoft account. Minecraft's pocket edition doesn't actually need microsoft account.

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۰۷-۱۰-۰۱-۲۰-۳۰-۹۳۲_com android chrome-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/ce479b4d-a198-4fd4-a992-0a9a814e67d3)
