### ISSUE TITLE
[BUG] <Short description> yeah crash

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5772]
### Describe the bug

I add some mods and crash

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16154703/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: 
- Android version: 12
- PojavLauncher version: playstore latest
```

### Anything else?

-

**Comment by GaucovyAero** [comment]
the veinminer mod only works if you use java 21

**Comment by wayxyz89** [comment]
> the veinminer mod only works if you use java 21

But in Playstore there is already an update adding Java 21
