### ISSUE TITLE
Crash when using Cursed Fabric (Better Than Wolves)

### ISSUE THREAD

**Issue by XanderZR** [PojavLauncherTeam/PojavLauncher#5773]
### Describe the bug

Well I want to play Better Than Wolves and download it, I do all thing that have in the instruction on Discord, but since I tried to play, it crash with code -1.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16155254/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Get into the Cursed Fabric
3. Game crash with code -1
```

### Expected Behavior

I hope you can help me fix this

### Platform

```markdown
- Device model: Oppo Reno 2F
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
ok this is some other error, but yeah, it seems like the patch has stopped working for whatever reason, ill take a look at it when ill have time and dont forget

**Comment by GaucovyAero** [comment]
oops, didnt mean to close

**Comment by NDG312** [comment]
try installing cursed fabric with old pojavlauncher debug apk, i tried and it works

**Comment by GaucovyAero** [comment]
updated guide here, its working now

[INSTALL_BTW.pdf](https://github.com/user-attachments/files/16446573/INSTALL_BTW.pdf)

**Comment by GaucovyAero** [comment]
skins/usernames should also work now with this updated version of the guide, maybe also multiplayer?
[INSTALL_BTW_updated_v1.1.pdf](https://github.com/user-attachments/files/16456724/INSTALL_BTW_updated_v1.1.pdf)
