### ISSUE TITLE
[BUG] 1.21 Fabric Crash (incompatible JNI library)

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5774]
### Describe the bug

Latest 1.21 Fabric Version crashed (i've using Haste Modpack).

### The log file and images/videos

Log:
[latestlog.txt](https://github.com/user-attachments/files/16155545/latestlog.txt)
JNI Library Error Photo:
![Screenshot_2024-07-10-13-23-14-60](https://github.com/PojavLauncherTeam/PojavLauncher/assets/123849671/f69f0233-98dc-44b6-8884-d7e6c4ab02b7)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Install Java 21 Manually (using java 21 branch in Pojavlauncher openjdk repo)
3. Install Haste Modpack Profile
4. Launch the Game
```

### Expected Behavior

I expect that the game will gonna start without any error from LWJGL nor JNI.

### Platform

```markdown
- Device model: Oppo A5 2020
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

BTW Haste Modpack is an patched Sodium Optimization Modpack for Pojavlauncher.

**Comment by GaucovyAero** [comment]
thats not the cause of the crash, the actual cause is a missing method (your lwjgl is out of date, you gotta update pojav)
```
java.lang.NoSuchMethodError: 'void org.lwjgl.glfw.GLFW.glfwSetWindowSizeLimits(long, int, int, int, int)'
```
