### ISSUE TITLE
[BUG] <when i am starting my pojav launcher version 1.20.1 vanilla or either fabric its crashing  immediat!>

### ISSUE THREAD

**Issue by FindingBlood** [PojavLauncherTeam/PojavLauncher#5776]
### Describe the bug

Just when I open the game it's crashe
[latestlog.txt](https://github.com/user-attachments/files/16167058/latestlog.txt)
s!

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1: Start pojav launcher
2: downloaded 1.20.1
3: do some basic settings
4: Start the game
```

### Expected Behavior

I except that it will run without any error!

### Platform

```markdown
- Device model: idk
- CPU architecture: idk
- Android version: idk
- PojavLauncher version: idk
```

### Anything else?

No

**Comment by Millymilo000** [comment]
Most likely situation is not enough ram is allocated or present. You can probably find the amount of ram your device has in developer options. Also, please figure out what platform stuff you have, just putting it as "idk" isn't helpful.

**Comment by GaucovyAero** [comment]
install another java 17 runtime from android-openjdk-build-multiarch repo and use that one
