### ISSUE TITLE
[BUG] Sodium Mod doesn't work on 1.21

### ISSUE THREAD

**Issue by apricoffee** [PojavLauncherTeam/PojavLauncher#5777]
### Describe the bug

I installed the fabric mod named "Sodium" and put it into the mods directory.

### The log file and images/videos

[latest[1].log](https://github.com/user-attachments/files/16167672/latest.1.log)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Download Sodium and put it into the mods directory.
3. Run the game.
```

### Expected Behavior

Minecraft runs and works fine.

### Platform

```markdown
- Device model: Xiaomi Redmi 13
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: Latest version of the Google Play Store app.
```

**Comment by ghost** [comment]
Sodium need opengl 4.6. not supported with android devices
