### ISSUE TITLE
[BUG] <The game simply crashes and closes with code 1>

### ISSUE THREAD

**Issue by Shotmas99ter** [PojavLauncherTeam/PojavLauncher#5778]
### Describe the bug

I'm having to start the game with a modpack I made, but the game stays 10 seconds on black screen and crashes with code 1

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16178025/latestlog.txt)

### Steps To Reproduce

```markdown
Start the game normally and wait for the inevitable
```

### Expected Behavior

Launch the game and load normally 

### Platform

```markdown
- Device model: moto e7 plus
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version:foxglove-20240709-045018f-v3_openj dk
```

**Comment by Shotmas99ter** [comment]
A few months ago this never happened

**Comment by GaucovyAero** [comment]
remove patchouli

**Comment by Shotmas99ter** [comment]
But the version is having some problem or the mod just doesn't workBut the version is having some problem or the mod just doesn't work?

**Comment by Shotmas99ter** [comment]
It keeps crashing :(
