### ISSUE TITLE
[BUG] <Short description>OptiFabric 1.20.4 Crashing

### ISSUE THREAD

**Issue by RajveerBeast56** [PojavLauncherTeam/PojavLauncher#5779]
### Describe the bug

Optifabric on 1.20.4 Crashing 
I cannot find that whether my mod setup is incompatible or something else is not working. 
Please help me. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16178663/latestlog.txt)

### Steps To Reproduce

```markdown
1. Setup my mods uploaded in 'Anything Else' section
2. Start Pojavlauncher
3. Launch the game with Fabric 1.20.4 ( Loaded Version: 0.15.10) 
4. Get crashed
```

### Expected Behavior

The game to open normally and run fine. 

### Platform

```markdown
- Device model: Xiaomi Redmi 9 Power
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Google Play Version
```

### Anything else?

My mods : 
[mods.zip](https://github.com/user-attachments/files/16178670/mods.zip)

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
this might be caused by a fabric api update, if not, try figuring out half by half to see which mod is conflicting with optifine
