### ISSUE TITLE
[BUG] <Game closing with code 1>

### ISSUE THREAD

**Issue by Shotmas99ter** [PojavLauncherTeam/PojavLauncher#5780]
### Describe the bug

I'm having to start the game with a modpack I made, but the game stays 10 seconds on black screen and crashes with code 1

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16181282/latestlog.txt)

### Steps To Reproduce

```markdown
Just start and wait a moment right after the game will close with code 1
```

### Expected Behavior

Launch the game and load normally

### Platform

```markdown
- Device model: moto e7 plus
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version:foxglove-20240709-045018f-v3_openj dk
```

### Anything else?

I've tried to remove some mods but I didn't succeed at all

**Comment by whiteralt** [comment]
It's problem with mods, I had the same. Try this:
Launch this modpack without mods, if it doesn’t start, try to change renderer.
Disable all mods, then add them one by one and run them.

**Comment by whiteralt** [comment]
Am forgot to add, do you have library checking enabled?

**Comment by Shotmas99ter** [comment]
Uhhh how can I see that?

**Comment by Shotmas99ter** [comment]
oh Man, am I really going to need to add 140 mods one by one? Ok :(

**Comment by Shotmas99ter** [comment]
> Esqueci de acrescentar: a verificação da biblioteca está habilitada?

Yes

**Comment by whiteralt** [comment]
Sorry for delay, i have really bad network

This option look like that:
![PSX_20240711_223419](https://github.com/PojavLauncherTeam/PojavLauncher/assets/134695450/41aa5dcc-f6b7-4593-820e-e37d968b38d8)

WAIT! I have it same, a lot of mods accumulated, try instead of queuing, adding in groups; if some group is not launched, try removing it from it, and then adding one by one.
Sorry for bad English, am using Google Translator & not so good knowing of English. And I also have a "that one people" living and lying in my house who is trying to make my brain rotten.

**Comment by Shotmas99ter** [comment]
> Desculpe pela demora, minha rede é muito ruim
> 
> Esta opção se parece com isso: ![PSX_20240711_223419](https://private-user-images.githubusercontent.com/134695450/347930579-41aa5dcc-f6b7-4593-820e-e37d968b38d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjgyMjMsIm5iZiI6MTcyMDcyNzkyMywicGF0aCI6Ii8xMzQ2OTU0NTAvMzQ3OTMwNTc5LTQxYWE1ZGNjLWY2YjctNDU5My04MjBlLWUzN2Q5NjhiMzhkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxOTU4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODk0N2U4YzZhYzNjMGQ1YWRiNWQ2M2RjMjZjNDc4NWQwMWNlZGRiNmNkMzMyMmE5N2ZlMWNkNDBhOGUxMTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v-iwfq3MwkPwWF5l9g7WbsGQvfSfjI94tt7sG-VLCxo)
> 
> ESPERE! Eu tenho o mesmo, muitos mods acumulados, tente em vez de enfileirar, adicionar em grupos; se algum grupo não for iniciado, tente removê-lo dele e, em seguida, adicionar um por um. Desculpe pelo inglês ruim, estou usando o Google Translator e não tenho um conhecimento tão bom de inglês. E eu também tenho um "aquele povo" morando e deitado na minha casa que está tentando apodrecer meu cérebro.

I'm also using Google translate LOL, ok I appreciate the tip

**Comment by GaucovyAero** [comment]
remove patchouli if you have it, maybe optifine is causing your issue, just remove it

**Comment by Shotmas99ter** [comment]
Finally I found the mod that was screwing everything up 
The name of the mod is:immersive portals 
Apparently pojavlauncher is not yet compatible with it :(

**Comment by whiteralt** [comment]
> Finally I found the mod that was screwing everything up The name of the mod is:immersive portals Apparently pojavlauncher is not yet compatible with it :(

This work for me and it's my favorite super liminal mod (last time played on supported version with it was for a really long time ago, may PJL stopped to supporting it with fine).
