### ISSUE TITLE
[BUG] Crashed using internal-17

### ISSUE THREAD

**Issue by JuStCallMeRenzXD** [PojavLauncherTeam/PojavLauncher#5781]
### Describe the bug

Version 1.20.1 internal-17 I'm using the jre17 and it's crashing 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16182971/latestlog.txt)

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

Launch normally 

### Platform

```markdown
- Device model:  vivo 0906
- CPU architecture: armm64
- Android version: 11
- PojavLauncher version: the lastest one July 9 update
```

**Comment by GaucovyAero** [comment]
known issue, use jre17 from android-openjdk-build-multiarch github actions
