### ISSUE TITLE
{Crash} Crashing with Zink

### ISSUE THREAD

**Issue by AllenPlayzMC** [PojavLauncherTeam/PojavLauncher#5782]
### Describe the bug

whenever i hit play button it loads for a while but then it crashes, it always happens to me this is the log. Can someone pls help me, i dont know if this is just about my device or its in the app
[latest.log](https://github.com/user-attachments/files/16194046/latest.log)

@GaucovyAero 
### The log file, i hope this one is right log

[crash-2024-07-13_12.18.47-client.txt](https://github.com/user-attachments/files/16200888/crash-2024-07-13_12.18.47-client.txt)

this is in the crash log

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2024-07-13 12:18:47
Description: Initializing game

java.lang.RuntimeException: could not preload blit shader
	at net.minecraft.class_757.method_34521(class_757.java:443)
	at net.minecraft.class_310.<init>(class_310.java:676)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_2973: Invalid shaders/core/blit_screen.json: The call method_34416 is not cancellable.
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:176)
	at net.minecraft.class_757.method_34521(class_757.java:441)
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_34416 is not cancellable.
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101)
	at net.minecraft.class_281.handler$cdj000$iris$causeException(class_281.java:535)
	at net.minecraft.class_281.method_34416(class_281.java:68)
	at net.minecraft.class_281.method_1283(class_281.java:51)
	at net.minecraft.class_5944.method_34579(class_5944.java:214)
	at net.minecraft.class_5944.<init>(class_5944.java:161)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_34521(class_757.java:443)
	at net.minecraft.class_310.<init>(class_310.java:676)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Linux (aarch64) version Android-14
	Java Version: 21.0.1-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1034066272 bytes (986 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	JVM Flags: 3 total; -Xms2048M -Xmx2048M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Fabric Mods: 
		animatica: Animatica 0.6.1+1.20.6
		appleskin: AppleSkin 3.0.2+mc1.20.5
		badoptimizations: BadOptimizations 2.1.4
		bettermounthud: Better Mount HUD 1.2.3
		bobby: Bobby 5.2.0+mc1.20.6
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51ff
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51ff
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.96+1.20.6
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.96+1.20.6
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.96+1.20.6
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.96+1.20.6
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.96+1.20.6
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.96+1.20.6
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.96+1.20.6
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.96+1.20.6
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.96+1.20.6
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.96+1.20.6
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.96+1.20.6
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.96+1.20.6
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.96+1.20.6
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.96+1.20.6
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.96+1.20.6
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.96+1.20.6
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.96+1.20.6
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.96+1.20.6
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.96+1.20.6
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.96+1.20.6
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.96+1.20.6
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chunky: Chunky 1.4.10
		clean-debug: Clean F3 0.4.5
		cloth-config: Cloth Config v14 14.0.126
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.20.5
		cubes-without-borders: Cubes Without Borders 1.1.0+1.20
		debugify: Debugify 1.20.6+1.0
		eatinganimationid: Eating Animation 1.20.6+1.9.7
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.20.6
		entity_model_features: Entity Model Features 2.0.2
		entity_texture_features: Entity Texture Features 6.1.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		fabric-api: Fabric API 0.100.0+1.20.6
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.6+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.2+bd772e83b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.2.2+a5d5299db0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.3+6e5bbc4ab0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+e0fdb017b0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.11+a7dc0e41b0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+3cb1a7b8b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.4+c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.17+ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.13+8d125e3bb0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.0+a5d5299db0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0+c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.74+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.20.5
		fastquit: FastQuit 3.0.0+1.20.6
		ferritecore: FerriteCore 6.1.1
		forgeconfigapiport: Forge Config API Port 20.6.1
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		immediatelyfast: ImmediatelyFast 1.2.18+1.20.6
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.31+mc1.20.4
		iris: Iris 1.7.0+mc1.20.6
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 14.2.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.7
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		languagereload: Language Reload 1.6.1+1.20.6
		lithium: Lithium 0.12.3
		midnightcontrols: MidnightControls 1.9.5+1.20
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
			spruceui: SpruceUI 5.0.3+1.20.4
		midnightlib: MidnightLib 1.5.5
		minecraft: Minecraft 1.20.6
		minimalcoordshud: Minimal Coords HUD 1.1.2
		modernfix: ModernFix 5.18.0+mc1.20.6
		modmenu: Mod Menu 10.0.0-beta.1
		moreculling: More Culling 0.25.0
			com_github_fallen-breath_conditional-mixin: conditional-mixin v0.6.2
			mixinsquared: MixinSquared 0.1.1
		noisium: Noisium 2.1.0+mc1.20.5-1.20.6
		noxesium: Noxesium 2.0.5+6bc9e3d
			com_noxcrew_noxesium_api_: api 2.0.5+6bc9e3d
		nvidium: Nvidium 0.2.7-beta
		optigui: OptiGUI 2.3.0-beta.2+1.20.5
			org_apache_commons_commons-text: commons-text 1.12.0
			org_ini4j_ini4j: ini4j 0.5.4
		packetfixer: Packet Fixer 1.4.1
		puzzle: Puzzle 1.6.2+1.20.6
			puzzle-base: Puzzle Base 1.6.2+1.20.6
			puzzle-gui: Puzzle GUI 1.6.2+1.20.6
			puzzle-models: Puzzle Models 1.6.2+1.20.6
			puzzle-splashscreen: Puzzle Splash Screen 1.6.2+1.20.6
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.5-build.103
		rrls: Remove Reloading Screen 4.1.0+mc1.20.6-fabric
		shulkerboxtooltip: Shulker Box Tooltip 4.1.0-alpha.4+1.20.6
		sodium: Sodium 0.5.8+mc1.20.6
		sodium-extra: Sodium Extra 0.5.5+mc1.20.6-build.118
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		status-effect-bars: Status Effect Bars 1.0.5
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.6-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.13.5+1.20.6
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: (off) (fallback)
	Launched Version: 1.20.6
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: zink Vulkan 1.1(Mali-G52 MC2 (ARM_PROPRIETARY)) GL version 3.1 Mesa 23.2.0-devel (git-957009978e), Mesa
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en
	CPU: <unknown>

### Expected Behavior

i expect to normally load the game, but it crashes

### Platform

```markdown
- Device model: Redmi 13C 8/256GB
- CPU architecture: Arm Cortex A75 / Arm Cortex A55 
- Android version: 14
- PojavLauncher version: foxglove-20240709-045018-f-v3_openjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt (use the share log file button or find the file in file picker -> 3 lines -> PojavLauncher)

**Comment by AllenPlayzMC** [comment]
> wrong log, send latestlog.txt (use the share log file button or find the file in file picker -> 3 lines -> PojavLauncher)

i have edited it can you please check it?

**Comment by GaucovyAero** [comment]
> > wrong log, send latestlog.txt (use the share log file button or find the file in file picker -> 3 lines -> PojavLauncher)
> 
> i have edited it can you please check it?

wrong logs, send latestlog.txt

**Comment by AllenPlayzMC** [comment]
@GaucovyAero 
[2024-07-15-1.log.gz](https://github.com/user-attachments/files/16228123/2024-07-15-1.log.gz)
[latest.log](https://github.com/user-attachments/files/16228124/latest.log)
is it fthis one?, this is the latest log

**Comment by ghost** [comment]
No latest.log he gaucovyaero say latestlog.txt

**Comment by AllenPlayzMC** [comment]
> No latest.log he gaucovyaero say latestlog.txt

thats the latest log😭😭

**Comment by ThatMG393** [comment]
> > No latest.log he gaucovyaero say latestlog.txt
> 
> thats the latest log😭😭

It's not in the `.minecraft` directory, it resides within where `.minecraft` is located, there's a latestlog.txt there

**Comment by AllenPlayzMC** [comment]
wait.... i dont think there is a crash log 💀💀💀. It just loads, shows
black screen, then crash.

I'll just ask you a question, does mali gpu support zink?

**Comment by ghost** [comment]
> wait.... i dont think there is a crash log 💀💀💀. It just loads, shows black screen, then crash. I'll just ask you a question, does mali gpu support zink?


Need latestlog.txt to know this crash is for your mali gpu issue or is fir another problem

**Comment by AllenPlayzMC** [comment]
> > wait.... i dont think there is a crash log 💀💀💀. It just loads, shows black screen, then crash. I'll just ask you a question, does mali gpu support zink?
> 
> Need latestlog.txt to know this crash is for your mali gpu issue or is fir another problem

i cant find the crash log bro, i checked all the logs

**Comment by AllenPlayzMC** [comment]
wait i think this is the log

**Comment by AllenPlayzMC** [comment]
wait i think this is the log

[latestlog.txt](https://github.com/user-attachments/files/16260558/latestlog.txt)

@GaucovyAero @kasrarouhi

**Comment by GaucovyAero** [comment]
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
```
yeah your gpu does not support zink, you gotta get a much better phone (one with a snapdragon soc too)

**Comment by AllenPlayzMC** [comment]
> ```
> WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
> ```
> 
> yeah your gpu does not support zink, you gotta get a much better phone (one with a snapdragon soc too)

is there any way to fix that?, when i use holygl4es its just trash

**Comment by ghost** [comment]
> > ```
> > WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > yeah your gpu does not support zink, you gotta get a much better phone (one with a snapdragon soc too)
> 
> is there any way to fix that?, when i use holygl4es its just trash

Don't say that holygl4es is one of the best Best renderer pojav have. And is no other option to fix this issue because of mali gpu problems. I recommend to use adreno gpu for zink if the adreno gpu support vulkan 1.3 is much better like adreno 740 and 750. Not 735 or 730. 730 and 735 uses vulkan 1.1 and have less optimizations. Warning: don't use phone with adreno 750 for now pojav not update for support adreno 750 but don't be worry fixing this is in merge request

**Comment by ghost** [comment]
Try solcraftlauncher if you have Microsoft account.solcraft launcher have virgl renderer I think it's work it's just like zink but not use vulkan uses opengl and have more compatible than zink and support shaders. I don't know why developers remove virgl but you can try in solcraftlauncher

**Comment by ghost** [comment]
This option need adreno gpu with vulkan version 1.3


![Screenshot_۲۰۲۴-۰۷-۲۲-۲۱-۴۷-۳۸-۹۵۲_net kdt pojavlaunch debug-edit](https://github.com/user-attachments/assets/26afb783-d623-4b7d-923c-cd02c17e914d)

**Comment by AllenPlayzMC** [comment]
> Try solcraftlauncher if you have Microsoft account.solcraft launcher have virgl renderer I think it's work it's just like zink but not use vulkan uses opengl and have more compatible than zink and support shaders. I don't know why developers remove virgl but you can try in solcraftlauncher

where to download that solcraft launcher, is it working only for a microsoft account? no offline account?

**Comment by ghost** [comment]
Just Microsoft account and if you search in chrome sol craft launcher click on GitHub website and download the latest action

**Comment by AllenPlayzMC** [comment]
> Just Microsoft account and if you search in chrome sol craft launcher click on GitHub website and download the latest action

Can u upload the file?

**Comment by ghost** [comment]
https://github.com/SolDev69/SolCraftLauncher/actions/runs/10029650998
Click on app debug and extract here in zarchiver app and install it. If you already have a Microsoft account

**Comment by AllenPlayzMC** [comment]
> https://github.com/SolDev69/SolCraftLauncher/actions/runs/10029650998 Click on app debug and extract here in zarchiver app and install it. If you already have a Microsoft account

I'll try this, thank u for the link
