### ISSUE TITLE
[BUG] <Doesn't start fabric 1.20.1>

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#5784]
### Describe the bug

I'm just running factories And there is an error and it restarts 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16195947/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav
2. Use java 17
3. Doesn't run fabric
```

### Expected Behavior

Run fabric 1.20.1 last version

### Platform

```markdown
- Device model: teclast t40 pro
- CPU architecture: arm64 
- Android version: 12
- PojavLauncher version: last
```

**Comment by GaucovyAero** [comment]
most likely caused by you using a really outdated jre17 runtime, please update to the latest one from android-openjdk-build-multiarch github actions
