### ISSUE TITLE
[BUG] 1.9+ Crash issue

### ISSUE THREAD

**Issue by Eggzheads** [PojavLauncherTeam/PojavLauncher#5785]
### Describe the bug

I've been using Pojavlauncher for quite some time and never have I had an issue like this. Every time I launch Minecraft from 1.9+ It crashes (I haven't tested  _all_ versions). This issue never came to be until I started using the new "Game Dashboard" (which replicates mobile clicks with Chromebook keyboard) which before I used it, pojav used my chromebook curser but now it uses the Pojav's one. Pojavlauncher also runs on my phone perfectly fine on my phone and I've also tested this on my friend's touchscreen chromebook and 1.8.9 won't even load. I have linked the lastestlog.txt down below

### The log file and images/videos

Latest log file here - [latestlog.txt](https://github.com/user-attachments/files/16199668/latestlog.txt)
![Screenshot 2024-07-13 10 10 42](https://github.com/user-attachments/assets/6494c714-215c-45be-8969-f6ea1b223a23)

### Steps To Reproduce

```markdown
1. Launch Pojavlauncher 1.20.4
2. If it doesn't crash try using the "Game Dashboard" for a little bit then try again
```

### Expected Behavior

![Screenshot 2024-07-13 10 10 42](https://github.com/user-attachments/assets/2e0deef7-c6c5-455d-b0ed-d8a74542aabe)
[latestlog.txt](https://github.com/user-attachments/files/16199641/latestlog.txt)

### Platform

```markdown
- Device model: Lenovo 100e Chromebook 2nd Gen AST
- CPU architecture: x86
- Android version: 11
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by JuStCallMeRenzXD** [comment]
Probably the issues on jre17 latest update bug

**Comment by Eggzheads** [comment]
> Probably the issues on jre17 latest update bug

Wdym?

**Comment by GaucovyAero** [comment]
use java 17 from android-openjdk-repo multiarch github actions instead
