### ISSUE TITLE
[BUG] World Folder Issue

### ISSUE THREAD

**Issue by APerson976** [PojavLauncherTeam/PojavLauncher#5786]
### Describe the bug

So, whenever I try to open up any world folders, it instead of opening the folder, it opens my contacts for whatever reason. My device is a Samsung Galaxy Tab A8 model XM-200.

### The log file and images/videos

It won't let me screen record in the app :(

### Steps To Reproduce

```markdown
1. Start Minecraft
2. Select Single Player
3. Click On World
4. Click "Open World Folder."
```

### Expected Behavior

I expect the game to open the world folder.

### Platform

```markdown
- Device model: XM-200
- CPU architecture: x64
- Android version: 14
- PojavLauncher version: latest
```

### Anything else?

I encountered this bug when trying to install a datapack.

**Comment by GaucovyAero** [comment]
cannot reproduce, not a pojav issue, cause pojav is handling the activity normally (it normally opens the default android files app)
