### ISSUE TITLE
[BUG] Zink (Vulkan) doesn't work correctly

### ISSUE THREAD

**Issue by TheCreeperyXYZ** [PojavLauncherTeam/PojavLauncher#5788]
### Describe the bug

I heard you have to use Zink renderer to be able to have shaders, so I did just that, but when I opened the game, half of the screen was glitched out, completely unreadable.

### The log file and images/videos

![Screenshot_20240713_121239_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/a25a0b7a-f6e3-4628-9cc8-4db29b185fe0)

### Steps To Reproduce

```markdown
1. Enter PojavLauncher
2. Go to options
3. Select Zink (Vulkan) as renderer
4. Start the game in OptiFine 1.20.6
```

### Expected Behavior

I expected the renderer to work, since it did for everyone else, and I haven't heard of this bug.

### Platform

```markdown
- Device model: Samsung Galaxy S23 FE
- CPU architecture: ARMv8
- Android version: 14
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by GaucovyAero** [comment]
zink does not support xclipse, also zink is not developed by us
