### ISSUE TITLE
[F-Req] Mod sodium dont work

### ISSUE THREAD

**Issue by Regotek05** [PojavLauncherTeam/PojavLauncher#5789]
### Is this request related to a bug?

Sodium dont work if pojav launcher have lwjgl version is 3.3.1

### Describe the request.

I would like the developers to update LWJGL Up to version 3.3.3, Because many mods do not launch due to the wrong version lwjgl

**Comment by Dilen0001** [comment]
.

**Comment by JuStCallMeRenzXD** [comment]
It's working bro just download the modpack haste but i recommend delete the iris mod cuz it's bugging the renders.

**Comment by JuStCallMeRenzXD** [comment]
Btw there's already version of POJAV that have LWJGL 3.3.3 on action

**Comment by kiokori-git** [comment]
by installing haste, we are not responsible for any damages done to your device. we will not give any help about it, as that modpack uses unofficial files (sodium)
