### ISSUE TITLE
Please don't remove latest versions in version 2

### ISSUE THREAD

**Issue by GreenNinja00** [PojavLauncherTeam/PojavLauncher#579]
Hey I am a mcinabox player I was also trying pojav launcher and it was good but I heard you are removing all new mc versions in version 2 just dont do that

**Comment by netkv** [comment]
what...? new (1.13+) mc versions never worked in v2 in first place and showing them in version list is afaik from mojang versioning info or something like that

**Comment by khanhduytran0** [comment]
> removing all new mc versions in version 2 

It fetch versions from mojang server so don't worry about removal.
