### ISSUE TITLE
Advanced controller remapper

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5790]
### Is this request related to a bug?

No

### Describe the request.

I see that you are supporting certain Nintendo controllers on some models, so I would be happy if you support all controllers on all phones.

### Anything else?

I suggest that you make a section to map controller keys, the same way you map touch screen keys. There will be sections for you to choose what action this button performs. Example: A_BUTTON : SPACE

**Comment by GaucovyAero** [comment]
> all controllers on all phones

imagine a single person buying all controllers in the world and all android devices

please rename the issue to "Advanced controller remapper"

**Comment by GaucovyAero** [comment]
added in the latest play store build
