### ISSUE TITLE
bug do mouse no mobilador e em tv box eu e meu amigo tamo sofrendo com isso por favor  arrumem logo

### ISSUE THREAD

**Issue by Zack140-wq** [PojavLauncherTeam/PojavLauncher#5791]
### Describe the bug

Assunto: Bug - Movimento do Mouse Não Funciona no PojavLauncher em Dispositivos Móveis

Descrição:

Estou enfrentando um problema ao usar um mouse com o PojavLauncher em meu dispositivo móvel (TV Box com 1 GB de RAM). Quando conecto o mouse via mobilador, o cursor não se move ou responde corretamente dentro do jogo.

Detalhes:

Dispositivo: TV Box com 1 GB de RAM
Conexão do Mouse: Mobilador (adaptador)
Problema: O cursor do mouse não se move ou responde dentro do Minecraft
Mods: O problema persiste com ou sem mods instalados
Impacto:

Esse problema está afetando significativamente a jogabilidade, tornando quase impossível jogar Minecraft com precisão.

Soluções Tentadas:

Reinstalei o PojavLauncher e o Minecraft
Ajustei várias configurações de vídeo e desempenho
Testei diferentes mouses e adaptadores
Solicitação:

Por favor, investiguem e corrijam esse bug. Qualquer ajuda seria muito apreciada.

Obrigado,
[Seu Nome/Usuário]

Espero que essa descrição clara e concisa ajude a equipe do PojavLauncher a entender e resolver o problema.

### The log file and images/videos

Estou enfrentando um problema ao usar um mouse com o PojavLauncher em meu dispositivo móvel (TV Box com 1 GB de RAM). Quando conecto o mouse via mobilador, o cursor não se move ou responde corretamente dentro do jogo. Isso acontece independentemente das configurações ou versões que tento so na atualizacao ta esse bug, e persiste mesmo sem mods instalados.

Este problema está afetando significativamente minha experiência de jogo, tornando quase impossível jogar Minecraft com precisão.

Já tentei várias soluções, incluindo reinstalar o PojavLauncher e o Minecraft, ajustar configurações de vídeo e desempenho, e usar diferentes mouses e adaptadores, mas nada resolveu o problema.

Por favor, poderiam investigar e corrigir esse bug? Qualquer ajuda seria muito apreciada.

Obrigado

### Steps To Reproduce

```markdown
EU Quando ja entro o meu mouse nao si adapta eu entro com meu mouse noprmal entro num mapa pra testar e eu clico o botao de bater e o mouse do aplicativo fucionamais o mouse fica parado
```

### Expected Behavior

Espero que meu mouse fucione logo para mim aproveita o aplicativo

### Platform

```markdown
- Device model: Tv box 1 GB de RAM
- CPU architecture: ARM
- Android version: 10.2
- PojavLauncher version: A anterio da atualizacao FoxGlove
```

### Anything else?

Estou enfrentando um problema ao usar um mouse com o PojavLauncher em meu dispositivo móvel (TV Box com 1 GB de RAM). Quando conecto o mouse via mobilador, o cursor não se move ou responde corretamente dentro do jogo. Isso acontece independentemente das configurações ou versões que tento, e persiste mesmo sem mods instalados.

Este problema está afetando significativamente minha experiência de jogo, tornando quase impossível jogar Minecraft com precisão.

Já tentei várias soluções, incluindo reinstalar o PojavLauncher e o Minecraft, ajustar configurações de vídeo e desempenho, e usar diferentes mouses e adaptadores, mas nada resolveu o problema.

Por favor, poderiam investigar e corrigir esse bug? Qualquer ajuda seria muito apreciada.

Obrigado

**Comment by GaucovyAero** [comment]
is this issue on both foxglove and pre-foxglove? also please mention the specific model of your device as we have basically no way of buying it for example for testing if we dont know the exact model

**Comment by Zack140-wq** [comment]
The model of my TV box is TV Box NXQ Pro 5G 4K. I downloaded the PojavLauncher from Google, in the updated Foxglove version.

**Comment by GaucovyAero** [comment]
can you reproduce on the older edelweiss version if you have access to installing apks, try maybe apkmirror?

**Comment by GaucovyAero** [comment]
closing the issue because of inactivity

**Comment by Zack140-wq** [comment]
ja arrumei o bug
