### ISSUE TITLE
[BUG] no me deja jugar a la 1.19.2

### ISSUE THREAD

**Issue by MAXLAN2089** [PojavLauncherTeam/PojavLauncher#5792]

**Comment by MAXLAN2089** [comment]
Me equivoque de log es este
[2024-07-14-6.log.gz](https://github.com/user-attachments/files/16227769/2024-07-14-6.log.gz)

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt, you can find it like this: android file picker - 3 lines - pojavlauncher

**Comment by MAXLAN2089** [comment]
Me volvi a equivocar perdon
[latestlog.txt](https://github.com/user-attachments/files/16227792/latestlog.txt)
