### ISSUE TITLE
[BUG] -1 error in 1.19.2 

### ISSUE THREAD

**Issue by MAXLAN2089** [PojavLauncherTeam/PojavLauncher#5793]
### Describe the bug

No me deja cargar mods de la 1.19.2 intente con varias cosas pero nada

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16227848/latestlog.txt)

### Steps To Reproduce

```markdown
Descarga mods de tipo create version 0.5.1
```

### Expected Behavior

Que me deje entrar a la versión 1.19.2 con create y otros mods

### Platform

```markdown
- Device model:poco x5 pro
- CPU architecture:arm64
- Android version:14
- PojavLauncher version:foxglove
```

### Anything else?

Requiero ayuda porfavor

**Comment by GaucovyAero** [comment]
```
Caused by: java.nio.file.AccessDeniedException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/goblintraders-1.8.0-1.19.2.jar
```

dont cut your mods, copy them instead (you can try fixing this one by zipping the mod and unzipping it again

**Comment by MAXLAN2089** [comment]
Ok

**Comment by MAXLAN2089** [comment]
And for this ?
![Screenshot_2024-07-14-17-57-11-621_net kdt pojavlaunch](https://github.com/user-attachments/assets/818907cb-31fa-4d51-a299-1a68b902b62f)

[latestlog.txt](https://github.com/user-attachments/files/16228902/latestlog.txt)
