### ISSUE TITLE
[BUG] <Jit doesn’t work, minecraft 1.21 with java 21 >

### ISSUE THREAD

**Issue by Krrr0** [PojavLauncherTeam/PojavLauncher#5794]
### Describe the bug

He tells me that I'm checking jit and not completing the verification. I've been waiting for about half an hour.
IPad ios 17.5.1

another thing 
I can’t play he said get java 21 

### The log file and images/videos

![IMG_0782](https://github.com/user-attachments/assets/6cf3ed0b-fec0-4d21-8a2e-65e15be1ce65)

### Steps To Reproduce

```markdown
Start pojav
Play
Waiting for jit
Nothing Else
```

### Expected Behavior

.

### Platform

```markdown
- Device model: ipad 7
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Nothing

**Comment by ghost** [comment]
You need to download latest action build in pojav GitHub website

**Comment by GaucovyAero** [comment]
wrong repository, go to PojavLauncherTeam/PojavLauncher_iOS
