### ISSUE TITLE
[BUG] lighting glitch in random chunks 1.20.4 and above.

### ISSUE THREAD

**Issue by TOOTS1610** [PojavLauncherTeam/PojavLauncher#5795]
### Describe the bug

When in a multiplayer or single player world, chunks are completely blacked out or dimmed in lighting. There is no pattern to which chunks are generated like this. To my knowledge it is only in versions above 1.20 but have not tested earlier versions.

### The log file and images/videos

![image](https://github.com/user-attachments/assets/c380aa74-54a2-4021-a813-027efbaf4c8d)
![image](https://github.com/user-attachments/assets/07ca38e3-d7d6-4f44-bbdf-504178be3cad)
![image](https://github.com/user-attachments/assets/981b58a9-e29e-4e8c-88af-5d618c594a8e)
Photos provided show the bug in a single player world.

### Steps To Reproduce

```markdown
1. Start povjavlauncher in 1.20 or above.
2. Open a single/multiplayer world.
3. The bug will appear in random chunks across the world.
```

### Expected Behavior

I expect to have a normal world with normal lighting and no weird chunks.

### Platform

```markdown
- Device model: Lenovo Chromebook
- CPU architecture: not sure
- Android version: not on android 
- PojavLauncher version: 1.20.4
```

**Comment by GaucovyAero** [comment]
try testing earlier versions

**Comment by Mathias-Boulay** [comment]
Hopefully fixed with changes in shader handling
