### ISSUE TITLE
Un error a iniciar sesión 

### ISSUE THREAD

**Issue by victxrino14** [PojavLauncherTeam/PojavLauncher#5796]
### Describe the bug

Descarge la app y inicie sesión con github y pongo la app y dise java.lang.RuntimeException: Not Found 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:301) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:86) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 	at java.lang.Thread.run(Thread.java:1012) y no puedo jugar porque me sale eso me ayudan con el problema porfavor 

### The log file and images/videos

..

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

..

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Eso namas

**Comment by GaucovyAero** [comment]
buy minecraft java edition, if you have bought it, try logging into minecraft.net first and then into pojav
