### ISSUE TITLE
App store?

### ISSUE THREAD

**Issue by Legend727** [PojavLauncherTeam/PojavLauncher#5797]
### Is this request related to a bug?

No. This is not related to a bug

### Describe the request.

Since how Delta and UTM SE got on the App store (both requiring JIT). Is it possible for Pojavlauncher to also get on the AppStore? I don't know a lot and may sound dumb, but also the fact of Altstore PAL and the EU changing the restrictions. It may be possible and it sounds like a good idea for me. It will make it more accessible too. I don't have a computer and I can't jailbreak or get trollstore so I'm hoping this happens. Please respond

### Anything else?

I also heard on reddit that JIT is possible on the app store without anything crazy with a computer or jailbreak. Could explain Delta and UTM getting on there

**Comment by ThatMG393** [comment]
Wrong repository, please move this issue to https://github.com/PojavLauncherTeam/PojavLauncher_IOS
