### ISSUE TITLE
Crash when using Forge 1.12.2

### ISSUE THREAD

**Issue by XanderZR** [PojavLauncherTeam/PojavLauncher#5798]
### Describe the bug

When I enter the world, it crash. This bug is repeat many time, I have to reset and reset...
I still do same thing when the bug is appear. Pls fix this :(

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16230011/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Play Forge 1.12.2
3. Create a world
4. Do something and leave the game
5. Enter the world
6. Game crash
```

### Expected Behavior

I hope you can fix this

### Platform

```markdown
- Device model: Oppo Reno 2F 
- CPU architecture: arm64
- Android version: Android 11
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

### Anything else?

If you read the log, don't care about the name of the world. And I can't send message in your server cuz the phone number verification doesn't work

**Comment by Dilen0001** [comment]
.

**Comment by ThatMG393** [comment]
Can you try running forge without mods? It's probably a mod incompability. Plus, there's no crash in the logs.

**Comment by XanderZR** [comment]
> Can you try running forge without mods? It's probably a mod incompability. Plus, there's no crash in the logs.

I will try

**Comment by GaucovyAero** [comment]
this seems to be a native crash, you gotta figure out which mod causes it by removing them
