### ISSUE TITLE
Automatically sprint when lock forward in joystick

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5799]
### Describe the bug

This is not a bug, just a feature that i got really annoyed. 
I'm using both the keyboard and the touch screen at the same time. To make it more familiar, I swapped the positions of the sprint button and the drop button.When I use the joystick, when I lock forward it seems like it pressed the ctrl button, causing me to drop items.

### The log file and images/videos

https://github.com/user-attachments/assets/bbf85f91-76bf-44eb-b9d6-c9f590b7dba7

### Steps To Reproduce

```markdown
1 Replace the keys:
  Drop: Ctrl
  Sprint: Q
2 use lock forward mode on joystick. It cause me to drop items.
```

### Expected Behavior

I hope that you remove this automatic sprint feature, or add an option to choose which button to sprint.

### Platform

```markdown
- Device model: redmi k20 pro
- CPU architecture: 64 bit
- Android version: 11
- PojavLauncher version: newest
```

**Comment by TarikBR** [comment]
You can disable this
![Screenshot_2024-07-15-08-16-21-487_net kdt pojavlaunch-edit](https://github.com/user-attachments/assets/4cae3c95-c6a7-462e-bf5a-9839dfcfbe84)

**Comment by TylerHaoNhot** [comment]
> You can disable this ![Screenshot_2024-07-15-08-16-21-487_net kdt pojavlaunch-edit](https://private-user-images.githubusercontent.com/64391349/348685502-4cae3c95-c6a7-462e-bf5a-9839dfcfbe84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDg3NjgsIm5iZiI6MTcyMTA0ODQ2OCwicGF0aCI6Ii82NDM5MTM0OS8zNDg2ODU1MDItNGNhZTNjOTUtYzZhNy00NjJlLWJmNWEtOTgzOWRmY2ZiZTg0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEzMDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZWEzNjE2ZTNmNzhiOGNjZjM5NzQ1ZjBiYjMwMDhhZDA4ZjJjMmIyOTQ4YjhkN2FjYjNlM2RiMzdiN2M5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jkmnH8jy5CHg5nk4tLR7gJHTDQeSB3zswhptdem0OJ8)

Yes, but I also want to use forward lock...:(

**Comment by Mathias-Boulay** [comment]
Bahaha. This specific use case is not planned for now.
