### ISSUE TITLE
Y axis is inverted

### ISSUE THREAD

**Issue by TheOriginalGolem** [PojavLauncherTeam/PojavLauncher#58]
When i try to use a usb mouse and keyboard, the y axis is inverted and the mouse buttons do not work correctly, otherwise everything else is flawless, any idea how to fix the issue?

**Comment by matteobranchi** [comment]
> When i try to use a usb mouse and keyboard, the y axis is inverted and the mouse buttons do not work correctly, otherwise everything else is flawless, any idea how to fix the issue?

There is an "invert mouse" button in the controls settings of minecraft.

**Comment by TheOriginalGolem** [comment]
The mouse buttons still are not mapped correctly, the left one does nothing  but the right one does the android back button

**Comment by matteobranchi** [comment]
> The mouse buttons still are not mapped correctly, the left one does nothing but the right one does the android back button

True, this can't be fixed from the game config sadly (there is no actual fix yet).
But you can break blocks by pressing the left button for like 1-2 seconds and you can place blocks.

**Comment by khanhduytran0** [comment]
You can help me debug.
Record a video. Ingame -> MORE -> Pointer capture Debug.

**Comment by khanhduytran0** [comment]
https://stackoverflow.com/a/12743948

**Comment by khanhduytran0** [comment]
Fixing

**Comment by khanhduytran0** [comment]
Try it https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.10.2

**Comment by matteobranchi** [comment]
> Try it https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.10.2

I have still Issues with preview 10.2 , I can still go back with the left click and now I can move my view on the X axis but not on the Y axis, it is stuck on the ground, I can't rise my view. (Also mouse toggle won't fix this and the "invert mouse" in minecraft config won't help). 
Also, I can no longer break blocks by keeping pressed the right button for 1 / 2 seconds.

**Comment by khanhduytran0** [comment]
Please temporary use touchscreen while the problem is solving.

**Comment by TheOriginalGolem** [comment]
Now i cant use y axis at all

**Comment by khanhduytran0** [comment]
Can you record a debug?

**Comment by khanhduytran0** [comment]
@TheOriginalGolem please reply about status of Y axis (is it fixed, because I don't have compatible device and mouse so can't test).

**Comment by khanhduytran0** [comment]
Reopen if problem occur again.
