### ISSUE TITLE
[BUG] so basically every time i turn on i crash

### ISSUE THREAD

**Issue by JestemKebab** [PojavLauncherTeam/PojavLauncher#580]
**Describe the bug**
I keep crashing, i installed pojav, installed optifine, used the install optifine function and turned on the game, after that i get an error message 

**To Reproduce**
1. Start PojavLauncher
2. Turn on optifine (install) on 1.16.4
3. Press 1.16.4
4. Just skip the loading when u can

**Expected behavior**
I expected it to turn on?

**Screenshots**

**Platform:**
 - Device Model Redmi 7
 - CPU architecture aarch64
 - Android Version newest for now, i really have no idea

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by JestemKebab** [comment]
![Screenshot_2021-01-08-18-32-41-722_net kdt pojavlaunch](https://user-images.githubusercontent.com/77166968/104046381-49f13200-51e0-11eb-8b82-6bcb976052a4.jpg)

**Comment by JestemKebab** [comment]
![Uploading Screenshot_2021-01-08-18-32-32-298_net.kdt.pojavlaunch.jpg…]()

**Comment by WesleyVanNeck** [comment]
give version and latestlog.txt were not wizards

**Comment by WesleyVanNeck** [comment]
@JestemKebab

**Comment by artdeell** [comment]
> ![Screenshot_2021-01-08-18-32-41-722_net kdt pojavlaunch](https://user-images.githubusercontent.com/77166968/104046381-49f13200-51e0-11eb-8b82-6bcb976052a4.jpg)

this can be ignored
