### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Brayan8632** [PojavLauncherTeam/PojavLauncher#5801]
### Describe the bug

Ta  aparecendo que não tenho uma conta w eu tenho lá no pixemon que tá bugado 

### The log file and images/videos

Ta bugado 

### Steps To Reproduce

```markdown
Ta bugado o pixemon Brasil
```

### Expected Behavior

Ta bugado o pixemon Brasil 

### Platform

```markdown
- Device model: pixemon Brasil 
- CPU architecture: pixemon Brasil 
- Android version: pixemon Brasil 
- PojavLauncher version: pixemon Brasil
```

### Anything else?

Ta bugado o pixemon Brasil

**Comment by TarikBR** [comment]
Explica direito, conta no launcher ou no servidor?

O servidor, seus dados são salvos em seu nick, só usar o mesmo e logar com sua senha. No launcher, o login por microsoft serve apenas quando se tem o jogo original de computador, enquanto o login local, você coloca o seu nick de forma local.

**Comment by GaucovyAero** [comment]
stale
