### ISSUE TITLE
[BUG] Texture Glitch?

### ISSUE THREAD

**Issue by Niko101-png** [PojavLauncherTeam/PojavLauncher#5802]
### Describe the bug

This bug happens in every single version with or without mods. My device has more than enough specs for pojav launcher. I can temporarily fix it by changing my chunks or graphics.

### The log file and images/videos

![Screenshot_2024-07-15-01-06-03-92_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/user-attachments/assets/f9f005fc-3795-47a0-8e6d-3781aee7e435)

### Steps To Reproduce

```markdown
1. I start up any version of pojavlauncher.
2. I join a world or server.
3. The glitch starts.
```

### Expected Behavior

Expected behaviour is for the textures to not glitch

### Platform

```markdown
- Device model: OnePlus 8
- CPU architecture: ARM64
- Android version: 13
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by GaucovyAero** [comment]
please send screenshot with f3 in vanilla world, also be sure to mention whether you are using a custom rom or something else that might be important

**Comment by GaucovyAero** [comment]
cant reproduce, stale, closing
