### ISSUE TITLE
[BUG] <anything below 1.20.6 crashes immediately with error code 1>

### ISSUE THREAD

**Issue by CrazyKieran19** [PojavLauncherTeam/PojavLauncher#5803]
### Describe the bug

I have been trying to launch 1.20.4 and it won't work.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16235977/latestlog.txt)

### Steps To Reproduce

```markdown
1. start pojavlauncher
play 1.20.4
```

### Expected Behavior

I expect to launch 1.20.4

### Platform

```markdown
- Device model: Lenovo Chromebook s330
- CPU architecture: 8
- Android version: 8
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
use latest java 17 from android-openjdk-build-multiarch repo

**Comment by CrazyKieran19** [comment]
how

**Comment by CrazyKieran19** [comment]
I cant find it
