### ISSUE TITLE
[BUG] Holy gl4es does not render text in 1.21 and some textures are black

### ISSUE THREAD

**Issue by carloanselmini** [PojavLauncherTeam/PojavLauncher#5804]
### Describe the bug

Whenever i use the holy gl4es renderer the game does not show any text at all, in game items in the hotbar and dropped are totally black

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16236661/latestlog.txt)
![Screenshot_20240715_172046_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/cec5aec4-4767-4385-8668-5456de663a34)
![Screenshot_20240715_171919_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/0ab2c212-ec16-4b48-8b28-0c3ebdb03571)

### Steps To Reproduce

```markdown
Install Minecraft 1.21, select Holy Gl4es as renderer and whatever jre and launch the game
```

### Expected Behavior

Showing text and textures, the same problem does not exist with holy in foldcraft for example

### Platform

```markdown
- Device model: Galaxy S22
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by carloanselmini** [comment]
I also tried the last v3_openjdk and lwjgl 3.3.3 and same problem

**Comment by GaucovyAero** [comment]
duplicate of #5646
