### ISSUE TITLE
Game crashes while using mods

### ISSUE THREAD

**Issue by Ineedmentalhelp** [PojavLauncherTeam/PojavLauncher#5806]
Mod 8s making my game crash

After i download a mod, put it int9 the mod folder and boot up Minecraft it just crashes and says something like "app closed. Error code 1"
And sometimes code -1

### The log file and images/videos
_Cant add images_
--------- beginning with launcher debug
Info: Launcher version: foxglove-20240709-045018f-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-A546B
Info: API version: 34
Info: Selected Minecraft version: fabric-loader-0.15.11-1.20.1
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1694
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~oMOV-33aMgx6xKvuzXdY8Q==/net.kdt.pojavlaunch-CZGYu2fo4jjxjy7tKQeWZQ==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~oMOV-33aMgx6xKvuzXdY8Q==/net.kdt.pojavlaunch-CZGYu2fo4jjxjy7tKQeWZQ==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=810
Initialising gl4es
v1.1.5 built on May  4 2024 09:53:01
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClientActiveTexture is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glVertexPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormalPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColorPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glEnableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDisableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glShadeModel is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFunc is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLogicOp is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMatrixMode is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadIdentity is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSize is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFuncx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearColorx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearDepthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4ub is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDepthRangex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetFixedv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLineWidthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawArrays is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawElements is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthof is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthox is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizePointerOES is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPolygonOffsetx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPopMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPushMatrix is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glRotatex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glSampleCoveragex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glScalex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvi is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTranslatex is NULL
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 64), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClientActiveTexture is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glVertexPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormalPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColorPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glEnableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDisableClientState is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4f is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glShadeModel is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFunc is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLogicOp is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMatrixMode is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadIdentity is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanef is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSize is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnviv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glAlphaFuncx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearColorx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClearDepthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4ub is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glColor4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glDepthRangex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordPointer is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogCoordfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFogxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glFrustumx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetClipPlanex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetFixedv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvfv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexEnvxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glGetTexParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightModelxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLightxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLineWidthx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glLoadMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMaterialxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultMatrixx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawArrays is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiDrawElements is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glMultiTexCoord4x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glNormal3x is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthof is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glOrthox is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterf is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterx is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointParameterxv is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizePointerOES is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPointSizex is NULL
warning, ./src/gl/host.c line 33 function init_gl_functions: host_functions.glPolygonOffsetx is NULL
warning, ./src/gl/host.c

### Steps To Reproduce

```markdown
1 go to files
2 put mods and fabric api into the mods folder from pojavlauncher
3 install fabric instqller with the .jar function
4 boot up java with the right version 5 crash.
```

### Expected Behavior

I expect my minecraft to be able to run mods without problems

### Platform

```markdown
- Device model: samsung galaxy A54 5G
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by GaucovyAero** [comment]
send the log file, not the text thats in it

**Comment by ietkd** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16323166/latestlog.txt)

**Comment by GaucovyAero** [comment]
```
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/实例/v1.21/mods/fabric-api-0.100.6+1.21.jar (Permission denied)
```
dunno why theres some weird symbols after .minecraft but okay (thats prolly some emojis or whatever), but you gotta remove the fabric api mod cause it has bad permissions then copy (NOT cut) a new version in

**Comment by GaucovyAero** [comment]
if that happens to other mods just do the same thing

**Comment by Ineedmentalhelp** [comment]
Thanks man this made my day it works

**Comment by NotManjiroSano** [comment]
My game crashes in 1.21 when I put mods but when I remove them it still works but I need the mods as they make my Minecraft smooth

**Comment by ghost** [comment]
Try sodium mod with LTW renderer in new pojav actions named add renderer and compatible checks
