### ISSUE TITLE
[BUG] crash al usar mods en la 1.20.1

### ISSUE THREAD

**Issue by MAXLAN2089** [PojavLauncherTeam/PojavLauncher#5808]
### Describe the bug

Cuando intento jugar con mods en la 1.20.1 me saca

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16253928/latestlog.txt)
![Screenshot_2024-07-16-12-43-02-240_net kdt pojavlaunch](https://github.com/user-attachments/assets/40b9feec-22c4-4037-8f83-94bc17854efe)

### Steps To Reproduce

```markdown
Instale mods de optimización de Embeddium
```

### Expected Behavior

Que me deje entrar al menu de Minecraft 

### Platform

```markdown
- Device model:poco x5 pro
- CPU architecture:arm64
- Android version:14
- PojavLauncher version:foxglove
```

### Anything else?

I need help

**Comment by GaucovyAero** [comment]
seems like one of your mods is trying to access sysfs, which is not possible on android
