### ISSUE TITLE
When tinywapper render coming?

### ISSUE THREAD

**Issue by NinjaLegendmc** [PojavLauncherTeam/PojavLauncher#5809]
### Is this request related to a bug?

When the tinywapper render coming?

### Describe the request.

When the tinywapper render coming?

### Anything else?

...

**Comment by CowSheep72** [comment]
bro be patient

**Comment by CowSheep72** [comment]
plus tinywrapper's probably not gonna release because fold craft launcher(🤢) could steal it

**Comment by NinjaLegendmc** [comment]
> plus tinywrapper's probably not gonna release because fold craft launcher(🤢) could steal it

Mother fucker foldcraftLauncher a.k.a viruscraftLauncher
