### ISSUE TITLE
Pojavluncher 1.20.6 crashes

### ISSUE THREAD

**Issue by error657756** [PojavLauncherTeam/PojavLauncher#5810]
### Describe the bug

pojavluncher 1.20.6 crashes i have java runtime 21 and it still crashes idk why even with fabric

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16262696/latest.log)

### Steps To Reproduce

```markdown
1. start pojavluncher
2. add java 21 runtime
3. download minecraft 1.20.6
4. open minecraft 1.20.6
```

### Expected Behavior

i expect minecraft runes correctly 

### Platform

```markdown
- Device model: Poco x6 (not pro)
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk(9939608) (latest version)
```

**Comment by ghost** [comment]
Wrong log. Send latestlog.txt

**Comment by error657756** [comment]
> Wrong log. Send latestlog.txt

sorry
[latestlog.txt](https://github.com/user-attachments/files/16264360/latestlog.txt)

**Comment by GaucovyAero** [comment]
your libraries are broken, try deleting the libraries folder

**Comment by error657756** [comment]
> your libraries are broken, try deleting the libraries folder

didnt worked
[latestlog (2).txt](https://github.com/user-attachments/files/16270600/latestlog.2.txt)

**Comment by GaucovyAero** [comment]
> > your libraries are broken, try deleting the libraries folder
> 
> didnt worked [latestlog (2).txt](https://github.com/user-attachments/files/16270600/latestlog.2.txt)

different issue now, so it worked, delete the 1.20.6 fabric jar in your versions (dont delete the json)

**Comment by error657756** [comment]
> > > your libraries are broken, try deleting the libraries folder
> > 
> > 
> > didnt worked [latestlog (2).txt](https://github.com/user-attachments/files/16270600/latestlog.2.txt)
> 
> different issue now, so it worked, delete the 1.20.6 fabric jar in your versions (dont delete the json)

im not gonna zay anything

> > > your libraries are broken, try deleting the libraries folder
> > 
> > 
> > didnt worked [latestlog (2).txt](https://github.com/user-attachments/files/16270600/latestlog.2.txt)
> 
> different issue now, so it worked, delete the 1.20.6 fabric jar in your versions (dont delete the json)

im not gonna say anything just guss
[latestlog (3).txt](https://github.com/user-attachments/files/16283356/latestlog.3.txt)

**Comment by GaucovyAero** [comment]
you are trying to run 1.19.2 mods on 1.20.6, thats not going to work
