### ISSUE TITLE
[BUG] ReplyMod not working?

### ISSUE THREAD

**Issue by CruxSky** [PojavLauncherTeam/PojavLauncher#5811]
### Describe the bug

Hello, 

I tried using the reply mod on PojavLauncher on Android. There are dependencies the mod needed called FFmpeg. The instructions said to put the extracted file of FFmpeg into .Minecraft. I followed the instructions, but when I returned to the game and tried rendering the record, it said, "To render a video, you need to have installed FFmpeg," but it's already in .Minecraft. Is it a bug, or something the game can't handle? Please help me; I really don't know how to fix it, and I want to record my game. Thank you very much.

### The log file and images/videos

![Screenshot_20240718-125722](https://github.com/user-attachments/assets/1a6ddec5-e2b4-41c6-93cf-f63f5ad13130)

### Steps To Reproduce

```markdown
1. Install replymod and ffmpeg
2. Open pojav and play
3. Record the game, save and quit
4. Tap reply records and tap the video
5. Add timestamp and position 
6. Tap "rander video"
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: Infinix Smart 8 
- CPU architecture: - 6 cores at 1.6 GHz: Cortex-A55 - 2 cores at 1.6 GHz: Cortex-A75
- Android version: Android 13
- PojavLauncher version: app debug version apk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
ffmpeg would have to be compiled for android and put inside root
get the ffmpeg plugin for pojav from github (try googling), its only going toa work up to mc 1.16.5
