### ISSUE TITLE
lwgjl version issue on 1.20.1

### ISSUE THREAD

**Issue by PiTa-23** [PojavLauncherTeam/PojavLauncher#5812]
### Describe the bug

i open 1.20.1 fabric instalatilon i created and this pops up (only coppied main error from the log)
[09:24:32] [main/ERROR]: The game failed to start because the currently active LWJGL version is not compatible.

### The log file and images/videos

![93907E6D-388C-41E5-A7B4-188838863A76](https://github.com/user-attachments/assets/b7bc2515-1302-4dad-8333-f3727544f2ec)
![08E9A9F5-89E0-4A04-B248-7249EA5280D3](https://github.com/user-attachments/assets/bc06a522-8fb9-4de9-9a6e-2067b6352653)
![86CABC6C-4689-4A2C-85BC-C23433ADC02E](https://github.com/user-attachments/assets/91a7f72b-b581-4936-b33e-b4d45ffae977)

### Steps To Reproduce

```markdown
start launcher
launch fabric 1.20.1 instalation
```

### Expected Behavior

dont crash 

### Platform

```markdown
- Device model: ipad 4th generation
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by CowSheep72** [comment]
this is an ipados issue, report ios issues here: https://github.com/PojavLauncherTeam/PojavLauncher_iOS
