### ISSUE TITLE
I just want to ask about the future pojav development and adding some performance updates.

### ISSUE THREAD

**Issue by DRONZER850** [PojavLauncherTeam/PojavLauncher#5816]
### Is this request related to a bug?

No

### Describe the request.

I just wanna ask what's your future goals for pojav launcher and do you plan on adding some performance updates in pojav. Also do you planning to make a performance mod pack like sodium but specifically for pojav launcher. I don't know much about this but I think there is a translation bcz of which we can play pojav so do you plan on making it more efficient. Do plan on making shaders support with really good performance. Also the do you plan on making the current renders more good or adding some new for more performance. Last question Is it possible to  make pojav as close to Java so that when new things come like distant horizon  natively support the pojav. 

Please answer these questions I have been thinking of writing these questions a long time ago but didn't get time. Hopefully you will answer. 👍

### Anything else?

No

**Comment by kiokori-git** [comment]
> as close to Java

it runs Java :/

**Comment by DRONZER850** [comment]
I know it runs Java but does it support sodium and other various mods. What I meant to say is that can they make pojav launcher such that there is no mods restriction and other things.

**Comment by kiokori-git** [comment]
no, mobile phones aren't PCs.
if you want mod compatibilty, tell the android manufacturers to add OpenGL drivers

**Comment by DRONZER850** [comment]
I don't know much about this and I am not telling them to add this but I am just asking. Btw you are from the development team ?

**Comment by kiokori-git** [comment]
> i am just asking

and you have your answer already.
i'm not from the development team nor a dev, but a helper in the PojavLauncher discord server.
my answer would likely be the same for the devs, as to have a 1:1 mod compatibilty to PC would definitely be impossible to do, as rendering problems is already an issue, which is really hard to fix

**Comment by DRONZER850** [comment]
Yes you are right

**Comment by Mathias-Boulay** [comment]
The devs are not paid. Therefore they work on whatever they feel like really. 
Hard to create a roadmap, but usually compatibility is usually a focus for us.

**Comment by alexytomi** [comment]
> would definitely be impossible 

Am pretty sure it could be possible but it will be dogshit slow since it would need A LOT of emulation

Like less than 1fps levels of slow

**Comment by DRONZER850** [comment]
What's about performance updates bcz right now its really hard to play newer versions.

**Comment by kiokori-git** [comment]
> What's about performance updates bcz right now its really hard to play newer versions.

no

**Comment by DRONZER850** [comment]
> > What's about performance updates bcz right now its really hard to play newer versions.
> 
> no

Why ????

**Comment by kiokori-git** [comment]
> > > What's about performance updates bcz right now its really hard to play newer versions.
> > 
> > 
> > no
> 
> Why ????

why are you asking "why", its literally really your answer
theres no things like an "update" nor "improve performance" button, it doesn't work like that. each renderers already perform at its max, if you want a better performance, just get a better phone at this point, actually

just get a fucking PC

**Comment by InfiniXDerg** [comment]
Here's the performance update https://amzn.eu/d/0gGtdkHl

**Comment by DRONZER850** [comment]
Its so cheap man. You can't even think of any big like 4070 or 4090

**Comment by InfiniXDerg** [comment]
> Its so cheap man. You can't even think of any big like 4070 or 4090

Now shut up and get a computer, even a Intel Atom intel stick runs Minecraft at 60FPS on the new versions with a resolution of 1080p

**Comment by InfiniXDerg** [comment]
It's not our fault that Java runs like trash on those latest versions

**Comment by DRONZER850** [comment]
Why you acting like a 9 year old boy. Just stop messaging me.

**Comment by InfiniXDerg** [comment]
I'm 9, but multiplied by 2 which equals to 18

**Comment by graperpie** [comment]
> Why you acting like a 9 year old boy. Just stop messaging me.

i'm 9, but actually is nine, but the difference in maturity between the two of us individuals is honestly pretty dumb. you should quit your bullshit and learn to read.

if you need a tutorial, hit me up

**Comment by kasrarouhi** [comment]
This conversation is going to off_topic
