### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5817]
### Describe the bug

Run pojav and force close 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16310044/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.loading Minecraft 
3 force close/crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: -
- Android version: 12
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
no errors, cant really help, maybe try removing half of your mods and see which half does that, then figure out which mod it is

**Comment by wayxyz89** [comment]
> no errors, cant really help, maybe try removing half of your mods and see which half does that, then figure out which mod it is

Owh thanks
