### ISSUE TITLE
[BUG] <E4mc not working on pojav>

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#5819]
### Describe the bug

I wanted to play with a friend through e4mc but it doesnt work

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16312175/latestlog.txt)

### Steps To Reproduce

```markdown
1. run minecraft 1.20.1 fabric with e4mc
2. Open world
3. errror
```

### Expected Behavior

e4mc open world

### Platform

```markdown
- Device model: teclast t40 pro
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: last
```

### Anything else?

Can you please help me I asked on github e4mc said that I will not help you because you are on pojavlaucher

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
its trying to load some linux library, that wont work because of android permissions, also not compatible with android i think, there would have to exist a recompiled version of that lib for android as a pojav plugin apk
