### ISSUE TITLE
[BUG] 1.21 Forge crashes on startup.

### ISSUE THREAD

**Issue by SHI117A1** [PojavLauncherTeam/PojavLauncher#5821]
### Describe the bug

1.21 froge unable to start

### The log file and images/videos

[log.txt](https://github.com/user-attachments/files/16318567/log.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.start forge
```

### Expected Behavior

1.21 forge can start

### Platform

```markdown
- Device model: redmi tuber 3
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: 9939611
```

**Comment by GaucovyAero** [comment]
seems like it requires lwjgl 3.3.3

**Comment by GaucovyAero** [comment]
make sure you are on that branch
