### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Dokitt** [PojavLauncherTeam/PojavLauncher#5822]
### Describe the bug

Plss i can't login

### The log file and images/videos

Ggggf

### Steps To Reproduce

```markdown
Plss
```

### Expected Behavior

Plsss

### Platform

```markdown
- Device model:idk
- CPU architecture:no
- Android version:11
- PojavLauncher version:1.20
```

### Anything else?

Plss

**Comment by CowSheep72** [comment]
send logs

**Comment by GaucovyAero** [comment]
log into minecraft.net first
