### ISSUE TITLE
[BUG] <Install ffmpeg on pojavlauncher>

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#5823]
### Describe the bug

I wanted to make a video but I was told to install ffmpeg I wanted to install it but it's only on pc I don't know how to install it on pojavlaucnher and I installed plugin for ffmpeg pojav but it didn't help.

### The log file and images/videos

![Screenshot_20240720-131655](https://github.com/user-attachments/assets/71862477-828f-4575-b576-c35fca5aa203)
p.s sorry russian laung

### Steps To Reproduce

```markdown
1. click to rendring replay
```

### Expected Behavior

rendring video

### Platform

```markdown
- Device model: teclast t40 pro
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: last (https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/10004602281)
```

### Anything else?

is there a rootless solution

**Comment by TarikBR** [comment]
https://github.com/PojavLauncherTeam/FFmpegPlugin/releases/tag/v1.0

**Comment by GaucovyAero** [comment]
only works up to 1.16.5
