### ISSUE TITLE
Shaders not appearing

### ISSUE THREAD

**Issue by Fantasy924** [PojavLauncherTeam/PojavLauncher#5824]
### Describe the bug

I use optifine but when I load a shader it gets loaded but nothing is showing up it's just default minecraft no shaders

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16321741/latest.log)

### Steps To Reproduce

```markdown
1.Open Pojalauncher
2.launch optifine 1.20.1
3.load any shaders(I've tried bsl and complementary)
4.join a server or load in a world
```

### Expected Behavior

I expect the shaders to work 

### Platform

```markdown
- Device model: Poco x6 pro
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: idk how to check but I downloaded the latest one in action
```

### Anything else?

I also tried using zink but pojav just closes it self for sm reason

**Comment by GaucovyAero** [comment]
wrong log, also since your gpu is mali it prolly does not support that kind of stuff
