### ISSUE TITLE
Buttons with files in .png format

### ISSUE THREAD

**Issue by CplShephard** [PojavLauncherTeam/PojavLauncher#5827]
### Is this request related to a bug?

Its not a bug

### Describe the request.

I think we need this, I want pocket edition buttons because I'm a little too obsessed, and it's much better than putting emojis in the button name.

### Anything else?

And if this possible pojav team make better touch mod from 1.7.10 to 1.21 (bedrock style inventory for non-mouse gameplay,better sliding and rgb mode for buttons)

**Comment by TarikBR** [comment]
Image on control buttons will perform poorly for potato devices

**Comment by GaucovyAero** [comment]
this would significantly decrease performance yeah, but there is someone on discord that has a controlmap like that created with a script

**Comment by CplShephard** [comment]
> Kontrol düğmeleri üzerindeki görüntü patates aygıtlarında zayıf performans gösterecek

For this reason, anyone who wants can use emoji and text as before, and whoever wants can use png, so there will be no problems in potato systems.

**Comment by Felix14-v2** [comment]
Do you mean something like this?
![image](https://github.com/user-attachments/assets/80b27e50-44fd-4ecc-b11a-e9fdb2daa855)
DM me in Discord if you want to try my controls ([felix14_v2](https://discordapp.com/users/694497672182104124)).

**Comment by CplShephard** [comment]
> Do you mean something like this?
> ![image](https://github.com/user-attachments/assets/80b27e50-44fd-4ecc-b11a-e9fdb2daa855)
> DM me in Discord if you want to try my controls ([felix14_v2](https://discordapp.com/users/694497672182104124)).

Hey yeah I want controls like bedrock I sender friend request :D closing issue
