### ISSUE TITLE
[BUG]Could not install Forge

### ISSUE THREAD

**Issue by New-Wheat** [PojavLauncherTeam/PojavLauncher#583]
**Describe the bug**
Game exits with code 1 when installing Forge-1.15.2-31.2.47

**To Reproduce**
1. Start PojavLauncher
2. Install mod launcher

**Expected behavior**
I expected to install Forge successfully.

**Screenshots**

**Platform:**
 - Device Model 
 - CPU architecture  aarch64
 - Android Version 10

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Here is the log:
Detected Forge Installer 1.13 or above!
Launching JVM
Info: Java arguments: [-Dcacio.managed.screensize=2050x1080, -cp, /storage/emulated/0/games/PojavLauncher/.minecraft/config/forge-installer-headless.jar:/storage/emulated/0/Download/Browser/forge-1.15.2-31.2.47-installer_20210103_115010.jar, me.xfl03.HeadlessInstaller, --installClient, .]
--------- beginning of crash
--------- beginning of main
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  (29913): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" unused DT entry: DT_RPATH (type 0xf arg 0x450) (ignoring)
I/jrelog  (29913): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  (29913): WARNING: linker: 
I/jrelog  (29913): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" unused DT entry: DT_RPATH (type 0xf arg 0x33c0) (ignoring)
I/jrelog  (29913): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
I/jrelog  (29913): WARNING: linker: 
I/jrelog  (29913): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" unused DT entry: DT_RPATH (type 0xf arg 0x13b8) (ignoring)
I/jrelog  (29913): 
I/jrelog  (29913): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
I/jrelog  (29913): WARNING: linker: 
I/jrelog  (29913): Warning: "
I/jrelog  (29913): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
I/jrelog  (29913): " unused DT entry: 
I/jrelog  (29913): DT_RPATH
I/jrelog  (29913):  (type 
I/jrelog  (29913): 0xf
I/jrelog  (29913):  arg 
I/jrelog  (29913): 0x2196
I/jrelog  (29913): ) (ignoring)
I/jrelog  (29913): 
I/jrelog  (29913): WARNING: linker: 
I/jrelog  (29913): Warning: "
I/jrelog  (29913): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
I/jrelog  (29913): " has unsupported flags DT_FLAGS_1=
I/jrelog  (29913): 0x81
I/jrelog  (29913):  (ignoring unsupported flags)
I/jrelog  (29913): 
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  (29913): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" unused DT entry: DT_RPATH (type 0xf arg 0x6a46) (ignoring)
I/jrelog  (29913): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
I/jrelog  (29913): WARNING: linker: 
I/jrelog  (29913): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: DT_RPATH (type 0xf arg 0x4d9) (ignoring)
I/jrelog  (29913): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
I/jrelog  (29913): WARNING: linker: 
I/jrelog  (29913): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" unused DT entry: DT_RPATH (type 0xf arg 0xda0) (ignoring)
I/jrelog  (29913): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(29913): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
S/LaunchJVM(29913): dlopen /data/app/net.kdt.pojavlaunch-H4YQXbwKggor2GqhBaZMLw==/lib/arm64/libopenal.so success
S/LaunchJVM(29913): dlopen /data/app/net.kdt.pojavlaunch-H4YQXbwKggor2GqhBaZMLw==/lib/arm64/libgl04es.so success
S/LaunchJVM(29913): Done processing args
S/LaunchJVM(29913): Found JLI lib
S/LaunchJVM(29913): Calling JLI_Launch
I/jrelog  (29913): OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/jrelog  (29913): 
I/jrelog  (29913): WARNING: linker: 
I/jrelog  (29913): Warning: "
I/jrelog  (29913): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
I/jrelog  (29913): " unused DT entry: 
I/jrelog  (29913): DT_RPATH
I/jrelog  (29913):  (type 
I/jrelog  (29913): 0xf
I/jrelog  (29913):  arg 
I/jrelog  (29913): 0x8ff
I/jrelog  (29913): ) (ignoring)
I/jrelog  (29913): 
I/jrelog  (29913): WARNING: linker: 
I/jrelog  (29913): Warning: "
I/jrelog  (29913): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
I/jrelog  (29913): " has unsupported flags DT_FLAGS_1=
I/jrelog  (29913): 0x81
I/jrelog  (29913):  (ignoring unsupported flags)
I/jrelog  (29913): 
I/jrelog  (29913): Exception in thread "main" 
I/jrelog  (29913): joptsimple.UnrecognizedOptionException: X is not a recognized option
I/jrelog  (29913): 
I/jrelog  (29913): 	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
I/jrelog  (29913): 
I/jrelog  (29913): 	at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633)
I/jrelog  (29913): 
I/jrelog  (29913): 	at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528)
I/jrelog  (29913): 
I/jrelog  (29913): 	at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523)
I/jrelog  (29913): 
I/jrelog  (29913): 	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59)
I/jrelog  (29913): 
I/jrelog  (29913): 	at joptsimple.OptionParser.parse(OptionParser.java:396)
I/jrelog  (29913): 
I/jrelog  (29913): 	at me.xfl03.HeadlessInstaller.main(HeadlessInstaller.java:50)
I/jrelog  (29913): 
Java Exit code: 1
S/LaunchJVM(29913): Going to free args
S/LaunchJVM(29913): Free done
Install successful
--------- beginning of system
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
we need more info i will close this for now

**Comment by artdeell** [comment]
We don't know the fix yet, reopening

**Comment by WesleyVanNeck** [comment]
> We don't know the fix yet, reopening

yes but there is no log and no device info

**Comment by artdeell** [comment]
> > We don't know the fix yet, reopening
> 
> yes but there is no log and no device info

Open the "Additional context" thingie

**Comment by khanhduytran0** [comment]
@New-Wheat you broke JVM arguments.

**Comment by khanhduytran0** [comment]
(?)

**Comment by khanhduytran0** [comment]
Which method you used to install? Custom arguments or 1st option?

**Comment by New-Wheat** [comment]
> Which method you used to install? Custom arguments or 1st option?

1st option

**Comment by Zeyrox1090** [comment]
it doesnt work on 1.16.4 too sad

**Comment by Zeyrox1090** [comment]
i will just install stable version of pojav then install forge then install the new pojav version back
