### ISSUE TITLE
Lighting issues

### ISSUE THREAD

**Issue by GStudiosX2** [PojavLauncherTeam/PojavLauncher#5830]
### Describe the bug

Is there anyway to fix lighting in 1.16.5 it works fine but 1.17+ it doesn't 

### The log file and images/videos

1.16.5 
![Screenshot_20240721-064406](https://github.com/user-attachments/assets/b3494756-f139-4072-ba54-9bfa93f93ac7)
1.21 
![Screenshot_20240721-064556](https://github.com/user-attachments/assets/562f06de-0776-4b8b-a935-33ac1ff6312f)
(I have tested 1.17.1 though and same issue)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Launch up anything as long as it's Minecraft 1.17.1+
3. The lighting isn't fully functional
```

### Expected Behavior

I expect it to be similar to 1.16.5

### Platform

```markdown
- Device model: Moto G54 5G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by GStudiosX2** [comment]
Seems like the angle renderer fixes this but it feels a little more slower

**Comment by GaucovyAero** [comment]
are you using vanilla on both?

**Comment by GStudiosX2** [comment]
> are you using vanilla on both?

Yes both are vanilla

**Comment by GStudiosX2** [comment]
Oh wait I just realised I put the wrong android version it's android 13 not 14

**Comment by Mathias-Boulay** [comment]
Normally fixed a while ago, an issue with shader input on 1.17+ that left the liberty on implementations to be full bright or full dark...
