### ISSUE TITLE
Holo soy fan de Minecraft[BUG] <Short description>

### ISSUE THREAD

**Issue by pedro1398400** [PojavLauncherTeam/PojavLauncher#5831]
### Describe the bug

La mejor aplicación para jugar Minecra[](url)

### The log file and images/videos

Tienen que aprobar la te va a divertir mucho

### Steps To Reproduce

```markdown
Y muy fácil de usar para jugar
```

### Expected Behavior

Se la recomiendo

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Mucho

**Comment by GaucovyAero** [comment]
👍
