### ISSUE TITLE
[BUG] crash with mods on Minecraft 1.20.1 fabric

### ISSUE THREAD

**Issue by MAXLAN2089** [PojavLauncherTeam/PojavLauncher#5836]
### Describe the bug

Me saca cuando intento cargar el mundo aparte el menu no carga la imagen solo los botones

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16325795/latestlog.txt)

### Steps To Reproduce

```markdown
Ve a YouTube y busca rust just that mods 1.20.1 y descarga los mods y instala fabric 1.20.1
```

### Expected Behavior

Que carge el mundo y la imagen del menu

### Platform

```markdown
- Device model:poco x5 pro
- CPU architecture:arm64
- Android version:14
- PojavLauncher version:foxglove
```

### Anything else?

Antes si me dejaba entar pero no se que paso que ya no deja

**Comment by GaucovyAero** [comment]
```
java.nio.file.AccessDeniedException: /sys/devices/system/cpu/memlat/c4_memlat/cpu4-cpu-l3-lat
```
some mod is trying to do something with your cpu files in sysfs but android doesnt allow it to
