### ISSUE TITLE
[BUG] ATM9 Doesn't work

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5838]
### Describe the bug

When i open the game, it shows the red screen, supposedly loading, but doesn't show the Mojang Logo, or the loading bar, i suppose this is normal, but it crashes after maybe 1 minute, and goes to the home screen

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16328080/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Create New Profile
3. Create Modpack Profile
4. Install ATM9 (All The Mods 9-0.2.60 - 1.20.1 version)
5. Click "Play"
```

### Expected Behavior

To work, and not just crash the app...?

### Platform

```markdown
- Device model: Xiaomi 2311DRK48G - Poco X6 Pro 8gb 256gb
- CPU architecture: Arm64 (...? thats what it says on the specs)
- Android version: 14 UP1A.230905.011
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by GaucovyAero** [comment]
corgilib requires an Intel/AMD/Zhaoxin PC in order to run
