### ISSUE TITLE
[F-REQ] How to use install mod with custom argument?

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#584]

**Comment by khanhduytran0** [comment]
So which mod are you trying to install?

**Comment by Adam0530** [comment]
> So which mod are you trying to install?

Optifine, ofcourse

**Comment by khanhduytran0** [comment]
Use built in installer

**Comment by Adam0530** [comment]
> Use built in installer

what is it?

**Comment by khanhduytran0** [comment]
The first option `Launch a mod install`

**Comment by Adam0530** [comment]
> The first option `Launch a mod install`

Thank it work!

**Comment by Mathias-Boulay** [comment]
The user's issue was solved a long time ago, closing it.
