### ISSUE TITLE
(Question about experimental stuff) What is these two options are actually do

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5841]
### Is this request related to a bug?

No

### Describe the request.

![Screenshot_۲۰۲۴-۰۷-۲۳-۰۳-۳۶-۵۵-۴۸۹_net kdt pojavlaunch debug-edit](https://github.com/user-attachments/assets/fae04bce-bce0-4a24-b5ea-eac5c56e0778)
I wanna ask to these two options are actually work or just is in build and after turn on shader dumping where is folder to find logs.
And renderer run on the big core improve performance or decrease it

### Anything else?

No

**Comment by TarikBR** [comment]
Shader dumping -> send shaders used by game/mods to log
Renderer on big core -> set the renderer to use the core with the highest frequency, which may or may not help performance

**Comment by ghost** [comment]
Ok ok
