### ISSUE TITLE
Create an official subreddit forum 

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5842]
### Is this request related to a bug?

no

### Describe the request.

the titles says it all. A subreddit will be useful to report bugs with who don't use GitHub and fun to share their moments, flex their fps, modpack, etc....

**Comment by 5ghzx** [comment]
r/PojavLauncher already exists

**Comment by TylerHaoNhot** [comment]
> r/PojavLauncher already exists

But it's closed and made private

**Comment by 5ghzx** [comment]
try the discord then

**Comment by GaucovyAero** [comment]
github is infinitely better to manage for these kinds of things IMO, you can also use the discord tho, managing another platform by a group of people this small would be pretty difficult also useless
