### ISSUE TITLE
[BUG] Weird graphical bug

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5843]
### Describe the bug

Occasionally when entering the game, this error will occur, affected by blocks. In the video I'm on the water so I can see what's happening. This bug will likely to go away when closing the application and re-entering the game, I don't understand why.

I don't remember this bug clearly but it seems to also happen with Minecraft Vanilla, here I use iris and sodium. When I turn on the iris shader, this error goes away. I guess this bug is related to the game's rendering. 

### The log file and images/videos

https://github.com/user-attachments/assets/156d703b-c0eb-47e1-813d-c6168cee6973

### Steps To Reproduce

```markdown
Play like normal, no step reproduce.
```

### Expected Behavior

Render like normal

### Platform

```markdown
- Device model: redmi k20 pro
- CPU architecture: snap 855- 64 bit
- Android version: 11 china rom
- PojavLauncher version: newest on play store
```

### Anything else?

This bug has also happened to me before, it is not serious enough to spread to all blocks like this but only from other players, NPCs and entities. Re-entering the game doesn't fix this well, but I have no clue when suddenly one day it's fixed. And now this bug back with worse.

**Comment by ghost** [comment]
Another zink renderer bug. I no really use sodium or iris but if in iris shaders setting have antialasing option like optifine try use internal shader and turn antialasing to 2x or 4x if you not wanna without shader in zink

**Comment by CloudBack0601** [comment]
用zink渲染器和iris试试？

**Comment by GaucovyAero** [comment]
yeah we dont develop zink, zink might get an update somewhere in the future tho
