### ISSUE TITLE
[BUG] Cursor disappears on Title Screen

### ISSUE THREAD

**Issue by GreenNinja2525** [PojavLauncherTeam/PojavLauncher#5844]
### Describe the bug

When using a controller, trying to use the on screen Cursor is impossible as it disappears after moving over a certain area. I tried changing video settings but it still persists. It won't even launch Minecraft on Vulkan
EVEN THOUGH ITS FABRIC, NO MODS ARE INSTALLED, ISSUE STILL PERSISTS ON VANILLA TOO

### The log file and images/videos

https://github.com/user-attachments/assets/9f83bc2b-8a55-4f50-9f0a-155b215e0d68

I heavily compressed the video but the bug is still visible

### Steps To Reproduce

```markdown
1. Launch an instance of modern Minecraft
2. Use a controller and try to use the left joystick to use the onscreen Cursor
3. Watch it disappear after moving away from the top left corner
```

### Expected Behavior

Working Cursor that remains visible and doesn't vanish

### Platform

```markdown
- Device model: Retroid Pocket 4 Pro
- CPU architecture: Mediatek Dimensity 1100
- GPU: Mali G77 MC9 
- Android version: 13
- PojavLauncher version: Latest GitHub Actions build (any recent build)
```

**Comment by GaucovyAero** [comment]
the issue is caused by how your buttons are distributed across the screen, either turn off alternate surface rendering or put some buttons in all the corners (they can also be invisible thats fine)
