### ISSUE TITLE
MENECRAFT [BUG] <Short description>

### ISSUE THREAD

**Issue by figueravanessa** [PojavLauncherTeam/PojavLauncher#5845]
### Describe the bug

Ejekek

### The log file and images/videos

Vsjejdbdkbdkf

### Steps To Reproduce

```markdown
Djjendndn
```

### Expected Behavior

Dujkenenene

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 1.21.1
```

### Anything else?

Si

**Comment by 5ghzx** [comment]
whats the point, the inconvenience is mild because it is just one post, why do it?
