### ISSUE TITLE
[BUG] <Short description>MENECRAFT java

### ISSUE THREAD

**Issue by figueravanessa** [PojavLauncherTeam/PojavLauncher#5846]
### Describe the bug

Ejekek

### The log file and images/videos

Vsjejdbdkbdkf

### Steps To Reproduce

```markdown
Djjendndn
```

### Expected Behavior

Dujkenenene

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 1.21.1
```

### Anything else?

Si

**Comment by 5ghzx** [comment]
oh wait there are 3?
