### ISSUE TITLE
I downloaded my pojav launcher do my previous settings and when i launched my game it crashes after 3 to 4 seconds

### ISSUE THREAD

**Issue by FindingBlood** [PojavLauncherTeam/PojavLauncher#5849]
### Describe the bug

The pojav launcher crashes after 3 to 4 seconds when I launched my game!  And also I can't connect my physical mouse with that

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16357763/latestlog.txt)

### Steps To Reproduce

```markdown
1: Start Pojav launcher
2: Create a local acc
3: Do some bsic settings like: RAM, Controls etc..
4: Install fabric of 1.20.1 and after downloading I launched it

After launching the game crashes after 4 seconds
```

### Expected Behavior

I except my physical mouse to work like before! When I connect my physical mouse and move that the pojav launcher mouse comes but it doesn't move with my mouse I have to control.it with hand

### Platform

```markdown
- Device model: Samsung galaxy A30s
- CPU architecture: ARM
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

My physical mouse not working

**Comment by GaucovyAero** [comment]
you are crashing because of cosmetica not working (issue #5379) and the mouse issue should be fixed in the latest github actions build, (issue #5648)
