### ISSUE TITLE
[ERROR] Error in pojavlauncher

### ISSUE THREAD

**Issue by Jaozin3** [PojavLauncherTeam/PojavLauncher#5851]
### Describe the bug

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:301)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:86)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

![Screenshot_20240724-135525](https://github.com/user-attachments/assets/87369f8d-0cfa-48d1-9d77-a424821a68aa)

### Steps To Reproduce

```markdown
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here
```

### Expected Behavior

I hope they fix this so I can log in with my gmail account on pojavlauncher

### Platform

```markdown
- Device model: ? 
- CPU architecture: ?
- Android version: Motorola e13
- PojavLauncher version: v3?
```

### Anything else?

Please fix this

**Comment by Yashkum0831p** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here
- Device model: vivo y95
- CPU architecture: snapdragon 439
- Android version: 9
- PojavLauncher version: v3
- please fix this

**Comment by GaucovyAero** [comment]
try logging into minecraft.net and then into pojav (make sure your username is set up)

**Comment by Zezopiroc** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here

**Comment by Rhuanzimmm** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:301)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:86)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Vadey1** [comment]
Tutorial

**Comment by Hello-bdhdvd** [comment]
- Device model: ios18
- CPU architecture: gaming 
- Android version: Motorola e13
- PojavLauncher version: v3?

**Comment by RAZASAKIB786** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here

**Comment by noname123456678-boop** [comment]
- Device model: vivo y100 5g
- CPU architecture: snapdraon 4gen2
- Android version: funtouch os 14 android 14
- PojavLauncher version: v3

**Comment by NoerX-Afk** [comment]
Plis i just want to login to pojavlaucher

- Device model: SM-A205U
- CPU architecture: Octa-core (2x1.6 GHz Cortex-A73 & 6x1.35 GHz Cortex-A53)
 - Android version: v11
- PojavLauncher version: v3

**Comment by noname123456678-boop** [comment]
Plis i just want to login to pojavlaucher

Device model: SM-A205U
CPU architecture: Octa-core (2x1.6 GHz Cortex-A73 & 6x1.35 GHz Cortex-A53)
Android version: v11
PojavLauncher version: v3

**Comment by ThiagoGG1** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here

**Comment by ThiagoGG1** [comment]
- Device model: ? 
- CPU architecture: ?
- Android version: Motorola e13
- PojavLauncher version: v3?

**Comment by ItsMUKE5H** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here
Android version Vivo t1x

**Comment by GaucovyAero** [comment]
> try logging into minecraft.net and then into pojav (make sure your username is set up)

this still applies

**Comment by jesuspatata** [comment]
I tried to put my account but It doesnt want

**Comment by sheidex00** [comment]
1. I started my pojavlaucher
2. I tried calling with my Gmail account
3. The message appeared that I couldn't call and told me to come here

**Comment by Dilkasth** [comment]
Norm

**Comment by ConfirmMe-1222** [comment]
> ### Platform
> ```
> - Device model: Vivo Y17
> - CPU architecture: SnapDragon 360
> - Android version: FunTouchOS (Android 9.0)
> - PojavLauncher version: v3
> ```

**Comment by Pritamparida99764675332** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here

**Comment by VeldoraCL** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here

Device model: vivo y27
CPU architecture: MediaTek Helio G85
Android version: FunTouchOS (Android 13) 
PojavLauncher version: v3

**Comment by Luiz661** [comment]
Modelo realme c55 
Cpu
Versão Android 14
Pojav v3

**Comment by azazel726** [comment]
- Device model: samsung a05s
- CPU architecture: Snapdragon® 680 
- Android version: android 14
- PojavLauncher version: v3

**Comment by cdw11-LE** [comment]
계정을 추가하라고 해서 추가했는데 이 계정은 마인크래프트를 소유하지 않다고뜨네요

**Comment by Fx-Mateus** [comment]
Oi boa noite tudo bem

**Comment by Fx-Mateus** [comment]
Eu queria jogar por Java

**Comment by Fx-Mateus** [comment]
É só isso

**Comment by Fx-Mateus** [comment]
Boa noite

**Comment by Fx-Mateus** [comment]
Jjkbjnj

**Comment by khalifiardan** [comment]
- Device model: Redmi 13c 
- CPU architecture: helio g85
- Android version: hyper os (v.1.0.5.0)
- PojavLauncher version: v3

**Comment by Tranchihao** [comment]
Xin hãy sửa lỗi

**Comment by AnDyx444** [comment]
David

**Comment by rewtt122** [comment]
Знайте ето кал а не программа я каждый заказ какда захожу то ошибка на 2 тилифонах

**Comment by rafagame204** [comment]
saya tidak bisa login padahal saya sudah masukan akun yang benar terimakasih semoga di baca...

**Comment by yusufo1j1** [comment]
Device model: Samsung m31
- CPU architecture: 4x2,3 GHz Cortex-A73 ve 4x1,7 GHz Cortex-A53
- Android version:Android 10
- PojavLauncher version: v3

**Comment by KaiForGoad55** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/5851#issuecomment-2253766780

**Comment by KaiForGoad55** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here- 
Device model: realme c12
- CPU architecture: gaming
- Android version: android 12
- PojavLauncher version: v3?

**Comment by Jonassbb** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:301)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:86)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Manpqa** [comment]
Please fix

**Comment by Muhdfateh** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here


- Device model: honor 200 pro
- CPU architecture: snapdragon 8s gen 3
- Android version: android 15
- PojavLauncher version: v3?

**Comment by Leonardo76151** [comment]
- Device model: ? 
- CPU architecture: ?
- Android version: Motorola e13
- PojavLauncher version: v3?

**Comment by Muhdfateh** [comment]
Device model: honor 200 pro 5g
CPU architecture: snapdragon 8s gen 3
Android version: 15
PojavLauncher version: v3

Pada Kha, 13 Feb 2025, 4:31 PG Leonardo76151 ***@***.***>
menulis:

**Comment by zavoaldigoad** [comment]
- Device model:itels666LN
- CPU architecture:helio G99 ultimate 
- Android version:13
- PojavLauncher version: v3

**Comment by Muhdfateh** [comment]
What?

Pada Kha, 13 Feb 2025, 11:16 PTG zavoaldigoad ***@***.***>
menulis:

**Comment by SoloBush** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here

- Device model: Tecno Camon 20 Pro 5G (Mobile) 
- CPU architecture: Dimensity 8050
- Android version: Android 14
- PojavLauncher version: v3

**Comment by hexa-sketch** [comment]
1. I started my pojavlauncher
2. I tried calling with my gmail account
3. The massage appeared that i couldn't call and told me to come here
 

• Device model: Redmi note 13
• CPU Architecture: Quad Cortex-A73 + Quad Cortex-A53
• Android version: Android 13
•pojavlauncher version: V3

**Comment by VIPMAN028** [comment]
me mando aca para mi cuenta de Microsoft que ago??

**Comment by ninja473** [comment]
- Device model: SM-A515
- CPU architecture: Samsung Exynos 9611 2.31GHz
- Android version: 13
- PojavLauncher version: v3
- pls help i fix

**Comment by Kenshin2124** [comment]
1.I started my pojavlaucher
2.I tried calling with my gmail account
3.The message appeared that I couldn't call and told me to come here

Device model: Redmi note 13 pro

CPU Architecture: Helio G-99-Ultra Octa-core Max 2.2GHz

Pojavlauncher version: v3?

**Comment by Cristian19251** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:301)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:86)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by LILMEOWMEOW573** [comment]
- Device model: Vivo y19s
- CPU architecture: MediaTek Dimensity T612 processor
- Android version: Motorola e13
- PojavLauncher version: v3?

**Comment by Bel69420** [comment]
Buy Minecraft java license, this isn't bedrock edition yk

**Comment by pepsi62** [comment]
They tell me that if I have an Xbox game pass created in one and I have Xbox game pass but how to do it?
