### ISSUE TITLE
[BUG] error al cargar en la 1.20.1

### ISSUE THREAD

**Issue by MAXLAN2089** [PojavLauncherTeam/PojavLauncher#5853]
### Describe the bug

Al cargar la versión 1.20.1 con mods se crashea

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16369121/latestlog.txt)

### Steps To Reproduce

```markdown
Instale el mod pack BM: exosphere
```

### Expected Behavior

Que deje cargar la versión con los mods

### Platform

```markdown
- Device model:poco x5 pro
- CPU architecture:arm64
- Android version:14
- PojavLauncher version:foxglove
```

### Anything else?

No se cual es el error

**Comment by GaucovyAero** [comment]
corgilib requires an Intel/AMD PC
