### ISSUE TITLE
[BUG] 1.20.1 Fabric failed to start

### ISSUE THREAD

**Issue by LanRhyme** [PojavLauncherTeam/PojavLauncher#5858]
### Describe the bug

I'm using 1.20.1 Fabric and no matter what mod I add, it always results in a crash. The log says it's started with Java 21, but it's the same with Java 17.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16381419/latestlog.txt)

### Steps To Reproduce

```markdown
start 1.20.1fabric
```

### Expected Behavior

I hope to be able to solve this problem.

### Platform

```markdown
- Device model: Redmi k60
- CPU architecture:Snapdragon 8+
- Android version: Android 14
- PojavLauncher version: foxglove-20240719-3f63042-v3_openjdk
```

**Comment by GaucovyAero** [comment]
android says permission denied to fabric for some of your mods, check in the log which mods have the issue and make sure that when you install mods, always copy and do NOT cut (because that is going to create this issue)
