### ISSUE TITLE
[F-REQ]Which one should I install? the latest action or the latest release?

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#586]

**Comment by Doxelix** [comment]
Latest release is the stable-est version.
Latest action build is devbuils version, and sometimes, there are bugs.

**Comment by Dimon245** [comment]
Latest build also has more functionality like mouse and keyboard support

**Comment by Adam0530** [comment]
> Latest build also has more functionality like mouse and keyboard support

So? Latest release?

**Comment by zeyrox1090** [comment]
actions

**Comment by Zeyrox1090** [comment]
actions:more functions more bug
releases:less functions less bug

**Comment by Adam0530** [comment]
> actions:more functions more bug
> releases:less functions less bug

k thanks! 👍
