### ISSUE TITLE
[BUG] hola

### ISSUE THREAD

**Issue by mateito12** [PojavLauncherTeam/PojavLauncher#5860]
### Describe the bug

Hola
Hola

### The log file and images/videos

A

### Steps To Reproduce

```markdown
A
```

### Expected Behavior

A

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: a
```

### Anything else?

A

**Comment by CowSheep72** [comment]
hola A moment
