### ISSUE TITLE
Crash when joining anyworld

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5861]
### Describe the bug

When I everything is okay until it reach 100% and loading terrain it ceash

### The log file and images/videos

Latestlog file:
[latestlog.txt](https://github.com/user-attachments/files/16390295/latestlog.txt)
Lastest crash file
[latestcrash.txt](https://github.com/user-attachments/files/16390300/latestcrash.txt)

### Steps To Reproduce

```markdown
1.Start pojav
2.join a world
2.enjoy crash
```

### Expected Behavior

.

### Platform

```markdown
- Device model: vivo y51 
- CPU architecture: 64-bit ARM LTE 
- Android version: Android 13
- PojavLauncher version: lastest ver on gg play
```

**Comment by DonutEpicuS** [comment]
same bug bro

**Comment by Hoanpojavlauncher** [comment]
> ### Describe the bug
> 
> When I everything is okay until it reach 100% and loading terrain it ceash
> 
> ### The log file and images/videos
> 
> Latestlog file:
> [latestlog.txt](https://github.com/user-attachments/files/16390295/latestlog.txt)
> Lastest crash file
> [latestcrash.txt](https://github.com/user-attachments/files/16390300/latestcrash.txt)
> 
> 
> ### Steps To Reproduce
> 
> ```markdown
> 1.Start pojav
> 2.join a world
> 2.enjoy crash
> ```
> 
> 
> ### Expected Behavior
> 
> .
> 
> ### Platform
> 
> ```markdown
> - Device model: vivo y51 
> - CPU architecture: 64-bit ARM LTE 
> - Android version: Android 13
> - PojavLauncher version: lastest ver on gg play
> ```
> 
> 
> ### Anything else?
> 
> _No response_

**Comment by GaucovyAero** [comment]
make sure you have render regions and shaders turned off (and are not using internal)

**Comment by ghost** [comment]
And antialasing
