### ISSUE TITLE
[BUG] :c

### ISSUE THREAD

**Issue by kk8745** [PojavLauncherTeam/PojavLauncher#5863]
### Describe the bug

text is nameless and textures are black

### The log file and images/videos

![Screenshot 2024-07-26 12 52 54 PM](https://github.com/user-attachments/assets/6a4b2759-2d79-4ce3-a9b6-15a2a663a435)

### Steps To Reproduce

```markdown
i just start my world
```

### Expected Behavior

i expect this to get fixed pls

### Platform

```markdown
- Device model: chromebook 11
- CPU architecture: idk
- Android version:13 
- PojavLauncher version: foxglove google play ver
```

### Anything else?

pls help i just want answers :c when will this ever get fixed

**Comment by GaucovyAero** [comment]
duplicate of #5674
