### ISSUE TITLE
[BUG] game not loading - stuck on loading terrain (pojav-1.21)

### ISSUE THREAD

**Issue by DonutEpicuS** [PojavLauncherTeam/PojavLauncher#5864]
### Describe the bug

I've been trying to play pojav 1.21 for several weeks by now but the game just won't load
i use java21 on 32bit ★★★
when i load up the game the "mojang" loading screen is now my panarama and when i click on other buttons the tabs selected become the panarama
but this is not the main issue, after a couple minutes the normal tricky trials panarama appears, now back to the point when i want to join a world of a server it always ALWAYS gets stuck on the "loading terrain" screen, and after a couple minutes it just decides to crash

### The log file and images/videos

the panarama glitch:
![Screenshot_2024-07-27-03-15-22-287_net kdt pojavlaunch](https://github.com/user-attachments/assets/dd410a5e-6a39-472b-8fd7-ea97ecf76c28)
![Screenshot_2024-07-27-03-15-31-504_net kdt pojavlaunch](https://github.com/user-attachments/assets/a46855ff-369a-4648-8b6e-2beb638e7306)
the "loading terrain" not loading and crashing glitch 
![Screenshot_2024-07-27-03-16-25-256_net kdt pojavlaunch](https://github.com/user-attachments/assets/067fd062-c460-443a-b268-711ea42d952a)
i unfortunately don't have a pic from when it crashes, it takes too long to crash, approximately 10 minutes 

### Steps To Reproduce

```markdown
1.open pojavlauncher -java21 32bit
2.wait for game to load
3. join/create a world/server
4.get stuck on loading terrain screen
5. get a crash after 10 minutes
```

### Expected Behavior

i EXPECTED that the game would LOAD properly and that i WOULD be able to join my favorite servers or my hardcore worlds!

### Platform

```markdown
- Device model: Xiaomi - Redmi 9C
- CPU architecture: it says arm64 (32 bit mode)
- Android version: 10
- PojavLauncher version: foxglove v3 openJDK
```

### Anything else?

im using :
holy Gl4es- java21 (32bit) -on 64 it crashes
900 mb ram allocated (it crashes if i go higher)

**Comment by Acel16x** [comment]
We have same problem here
I have Xiaomi - Redmi 9C
Android 10
foxglove V3 2024


I can join server but blocks are not rendered (GL4ES)
then game becomes bugged when I max out Allocated Memory
Now I cant Join Server

I hope developers or programmers solved this thing

**Comment by GaucovyAero** [comment]
guys this is just mojang completely removing support from minecraft for 32bit devices, not a pojav issue
