### ISSUE TITLE
Where does pojavlauncher load turnip driver from?

### ISSUE THREAD

**Issue by beta-mango** [PojavLauncherTeam/PojavLauncher#5865]
### Is this request related to a bug?

No

### Describe the request.

Pojavlauncher uses turnip 23.2.0, and it's pretty old. I want to try and use turnip 24.2
I know that pojavlauncher loads turnip from some kind of a library. Where can I find that library? I will replace it with the new one with turnip 24.2

**Comment by ghost** [comment]
I want to know because i have a problem with mesa 23.2.0 but after playing with mesa 24.0 in sol craft launcher old versions ump zink (can't play newer because microsoft account) my bug is fixed

**Comment by EvilAlee** [comment]
> I want to know because i have a problem with mesa 23.2.0 but after playing with mesa 24.0 in sol craft launcher old versions ump zink (can't play newer because microsoft account) my bug is fixed

Interesting 🤔.

**Comment by ghost** [comment]
I use chipset snapdragon 7+ gen 2 with adreno 725 gpu and have this problem

**Comment by beta-mango** [comment]
The driver is loaded from libOSMesa.so in /data/app. The issue can be closed
