### ISSUE TITLE
[BUG] hi only need 1 check in this erros

### ISSUE THREAD

**Issue by MAXLAN2089** [PojavLauncherTeam/PojavLauncher#5868]
### Describe the bug

Al usar mods de optimización de mi pc se crashea al entrar a un mundo

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16401701/latestlog.txt)

![Screenshot_2024-07-27-19-17-01-772_ru zdevs zarchiver](https://github.com/user-attachments/assets/948e12fc-ff0f-4f22-8dac-b49efd3355c4)
![Screenshot_2024-07-27-19-17-32-724_ru zdevs zarchiver](https://github.com/user-attachments/assets/69b3cd15-908a-4eaf-8885-8a283f99bae5)
![Screenshot_2024-07-27-19-17-50-760_ru zdevs zarchiver](https://github.com/user-attachments/assets/af389677-7631-481c-bb5c-354747eac2e4)
![Screenshot_2024-07-27-19-17-55-089_ru zdevs zarchiver](https://github.com/user-attachments/assets/1c3d1277-5326-4ace-9a31-b46733ae745d)

### Steps To Reproduce

```markdown
Inicie pojav con los siguientes mods de arriba ⬆️
```

### Expected Behavior

Que deje entrar a mis mundos o almenos crear uno

### Platform

```markdown
- Device model:poco x5 pro
- CPU architecture:arm 64
- Android version:14
- PojavLauncher version:fox glove v3 2024
```

### Anything else?

Solo quiero saber cual es el mod que saca error

**Comment by GaucovyAero** [comment]
follow the instructions in the attached image to get distant horizons to work

heres the [link](https://cdn.discordapp.com/attachments/824307242533781514/1249069976778707034/jre21-arm64-SQLite.tar.xz?ex=66a9dbd1&is=66a88a51&hm=430258c236cde9f829b6909277c44d0ae80b26d48653848399682c44225fa2c4&) to the special jre21

![image](https://github.com/user-attachments/assets/02a1bb29-d61d-4f22-9a3e-831d1012e8b9)
