### ISSUE TITLE
[BUG] My microsoft acc cant be connected to pojavlauncher

### ISSUE THREAD

**Issue by aidenisherelmao** [PojavLauncherTeam/PojavLauncher#5869]
### Describe the bug

so, i clicked add account in pojav launcher and then i put my gmail. and then password, when i signed up it said this, altough im signed in the minecraft.net

### The log file and images/videos

![Screenshot_20240728-132117](https://github.com/user-attachments/assets/befe9ce6-4052-41b3-84d6-c2eba2f869c0)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
```

### Expected Behavior

i expect for my microsoft account to work in pojav launcher

### Platform

```markdown
- Device model: Infinix hot 30 play
- CPU architecture: Arm-Cortex 53
- Android version: 13
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by ThatMG393** [comment]
As you can see your account is a child account, maybe try changing your account birthdate to be 13+ or 18+
