### ISSUE TITLE
Java 21 zip file is expired

### ISSUE THREAD

**Issue by mahdoosh1** [PojavLauncherTeam/PojavLauncher#5870]
### Describe the bug

title

### The log file and images/videos

...

### Steps To Reproduce

```markdown
Go to discord faq and click the link  for java 21
```

### Expected Behavior

should download but instead says it is expired >90 days

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
the person who is responsible for that message is currently inactive, hence why the link is outdated
for now, download manually from https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions

**Comment by mahdoosh1** [comment]
> the person who is responsible for that message is currently inactive, hence why the link is outdated
> for now, download manually from https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions

Thanks.
