### ISSUE TITLE
Forge not instaling

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5872]
### Describe the bug

I installed forge but it errored

### The log file and images/videos

![Screenshot_2024-07-28-20-51-54-385_net kdt pojavlaunch zh](https://github.com/user-attachments/assets/ef09fe6f-9379-43e2-a938-0533ed5196f2)

### Steps To Reproduce

```markdown
1.installing
2.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: 
- Android version: 12
- PojavLauncher version: zenith
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
use java 8 to install
