### ISSUE TITLE
[BUG] Pojavlauncer crash exit code 0

### ISSUE THREAD

**Issue by znibsss** [PojavLauncherTeam/PojavLauncher#5873]
### Describe the bug

When manually installing mods for forge 1.20.1 my game crashes with the exit code 0 but when I install the same mods using a new modpack profile and pojavlauncher downloads and install the mods itself it doesn't crash. Seems like when the mods arent installed by the app itself it cant run it but when I installed mods manually on forge 1.7.10 it didnt crash

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16403967/latest.log)

### Steps To Reproduce

```markdown
1. Install forge 1.20.1 on a samsung galaxy A35 5G

2. Manually install any mods

3. Launch forge 1.20.1 and see it crash
```

### Expected Behavior

The game should launch properly without any issue with the mods enabled and running.

### Platform

```markdown
- Device model: samsung galaxy a35 5g
- CPU architecture: exynos 1380 64 bit 8 cores
- Android version: 14
- PojavLauncher version: foxglove-20240719-3f63042v3_openjdk
```

### Anything else?

If the app (pojav launcher) itself installs the mods it doesnt crash. For exemple if you install a modpack profile it wont crash.

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt located in /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files

**Comment by znibsss** [comment]
[latestcrash.txt](https://github.com/user-attachments/files/16428187/latestcrash.txt)
[latestlog.txt](https://github.com/user-attachments/files/16428190/latestlog.txt)

**Comment by GaucovyAero** [comment]
```
java.nio.file.AccessDeniedException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/custom_instances/a_horrific_experience/mods/personal_intermediate_groink-alpha-2-forge-1.20.1 (1).jar
```
when installing mods, be sure to copy and not cut, otherwise you will get permission denied like right here and thats why you are crashing
