### ISSUE TITLE
Idk what to do

### ISSUE THREAD

**Issue by Vasko9** [PojavLauncherTeam/PojavLauncher#5876]
![Uploading latestlog.txt …]()
Everytime i play with any mod the game either crashes when starting or when joining a world

**Comment by ghost** [comment]
Witch version of minecraft

**Comment by Vasko9** [comment]
> Witch version of minecraft

1.20.6

**Comment by GaucovyAero** [comment]
create a bug report and upload the log, as you did not upload it (you gotta not touch anything until it uploads)

**Comment by Vasko9** [comment]
> create a bug report and upload the log, as you did not upload it (you gotta not touch anything until it uploads)

How do i do that i just started using github
