### ISSUE TITLE
can't read .jar file

### ISSUE THREAD

**Issue by Phucdepzainazi** [PojavLauncherTeam/PojavLauncher#5880]
### Describe the bug

I don't understand why when installing the FABRIC file there is a message that the .jar file cannot be read

### The log file and images/videos

![Screenshot_20240730-171617_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/c8df3ba7-78cb-478b-9c67-2ef70745a8d1)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: samsung a13
- CPU architecture: 
- Android version: 12
- PojavLauncher version: google play store :)
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
send log

**Comment by Phucdepzainazi** [comment]
> send log

[latestlog.txt](https://github.com/user-attachments/files/16428161/latestlog.txt)

**Comment by Phucdepzainazi** [comment]
> send log
I execute the fabric file and the latestlog had 0KB

**Comment by GaucovyAero** [comment]
dunno, but you cant execute mods, you cant only execute installers (this is how it also works on PC), you gotta put mods into your .minecraft/mods directory
