### ISSUE TITLE
The fabric mod is not working

### ISSUE THREAD

**Issue by Raghav155221** [PojavLauncherTeam/PojavLauncher#5883]
### Describe the bug

When i try to launch fabric on pojav launcher it just crashes after a few minutes.

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16427222/latest.log)

### Steps To Reproduce

```markdown
(1) start pojav launcher
(2) Select fabric loader
(3) Click play
(4) Wait a few minutes
(5) There you go pojav launcher just crashed
```

### Expected Behavior

I expected it to not crash and finnaly finish my pumpkin farm

### Platform

```markdown
- Device model: vivo Y100A
- CPU architecture: 2x ARM Cortex-A78 @ 2.21 GHz 6x ARM Cortex-A55 @ 1.80 GHz
- Android version: 13
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

Pls fix this

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt

**Comment by Raghav155221** [comment]
Okay

**Comment by Raghav155221** [comment]
Just download it then open it

**Comment by Raghav155221** [comment]
I cant add when i go to the website it just sends me back at the app

**Comment by Raghav155221** [comment]
[latest.log](https://github.com/user-attachments/files/16430897/latest.log)
Here but i cant directly send the log you need to download it

**Comment by GaucovyAero** [comment]
> [latest.log](https://github.com/user-attachments/files/16430897/latest.log) Here but i cant directly send the log you need to download it

wrong log, send latestlog.txt

**Comment by Raghav155221** [comment]
Bruh how tho

**Comment by Raghav155221** [comment]
Oh nvm here 
[latestlog.txt](https://github.com/user-attachments/files/16439111/latestlog.txt)

**Comment by GaucovyAero** [comment]
looks like pojavs lwjgl doesnt have this method anymore
```
java.lang.NoSuchMethodError: 'org.lwjgl.system.Struct org.lwjgl.vulkan.VkApplicationInfo.wrap(java.lang.Class, long)'
	at org.lwjgl.vulkan.VkApplicationInfo.calloc(VkApplicationInfo.java:330)
```

**Comment by GaucovyAero** [comment]
unsupported

**Comment by artdeell** [comment]
> looks like pojavs lwjgl doesnt have this method anymore
> 
> ```
> java.lang.NoSuchMethodError: 'org.lwjgl.system.Struct org.lwjgl.vulkan.VkApplicationInfo.wrap(java.lang.Class, long)'
> 	at org.lwjgl.vulkan.VkApplicationInfo.calloc(VkApplicationInfo.java:330)
> ```

hes using vkmod which has lwjgl 3.3.1 bundled in, so it conflicts with pojav

**Comment by Raghav155221** [comment]
So vulkan does not support pojav all of a sudden now?
