### ISSUE TITLE
[BUG] Can't find client jar file

### ISSUE THREAD

**Issue by Imbored702** [PojavLauncherTeam/PojavLauncher#5888]
### Describe the bug

Attempting to install forge results in it failing and instead giving an error message. IT is also taking much longer than its suppost to for the installation prompt to appear on screen as the FPS doesn't drop immediately upon executing the jar. Restarting my device, restarting the app, and even a factory reset did not solve the issue.

### The log file and images/videos

![Screenshot 2024-07-30 2 42 58 PM](https://github.com/user-attachments/assets/5d3f9992-0432-4c61-8afe-d6071cdcf6cb)

### Steps To Reproduce

```markdown
1: Start Pojavlauncher
2: Execute Forge 1.19.2 
3: Wait for 2-3 minutes for the installation prompt to appear
4: Select "Install Client"
5: The error message saying that the manifest failed to download
```

### Expected Behavior

Expected for Forge to download faster instead of seeing a massive imcrease in FPS upon executing the jar and for the installation process to be succesful.

### Platform

```markdown
- Device model: Chromebook (Grunt)
- CPU architecture: arm64 x86_64
- Android version: 11
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

This happens only when attempting to install Forge manually, installing a modpack does not trigger the issue. This also happened a day after i had installed the latest patch.

**Comment by artdeell** [comment]
you have issues with your network

**Comment by Imbored702** [comment]
is that a question or is that a possible cause?

**Comment by artdeell** [comment]
that is the cause, if you read the exception message you can clearly see shat one of the main steps of downloading fails

**Comment by Imbored702** [comment]
Very well, what steps can I take to troubleshoot or possibly fix it? I am not one who is very familiar with the code so it will be more difficult for me to understand.

**Comment by GaucovyAero** [comment]
maybe try installing it on a pc and copy the files over, or get llaunch running in a linux container with a graphical interface if you dont have a pc and copy the files like that, or run a virtual machine or something, theres like a million options, or maybe try using a different network, vpn, etc.

**Comment by GaucovyAero** [comment]
but in any case this is not a pojav issue, if you want more offtopic help pls go to the pojav discord and ping me
