### ISSUE TITLE
[BUG] How to use Vulkan Mod 1.21 

### ISSUE THREAD

**Issue by SpeedCuberMC** [PojavLauncherTeam/PojavLauncher#5889]
### Describe the bug

How to use Vulkan Mod 1.21

### The log file and images/videos

Vulkan mode 1.21

### Steps To Reproduce

```markdown
Dowload Vulkan mod 
Join Pojavlauncer
Got crash
```

### Expected Behavior

I want use Vulkan Mod 1.21

### Platform

```markdown
- Device model:Samsung 
- CPU architecture: idk
- Android version: 13
- PojavLauncher version: idk
```

### Anything else?

Vulkan mod 1.21

**Comment by GaucovyAero** [comment]
prolly wont work, android is not supported anymore

**Comment by CowSheep72** [comment]
help
