### ISSUE TITLE
The game wont let me play with mods

### ISSUE THREAD

**Issue by Vasko9** [PojavLauncherTeam/PojavLauncher#5892]
### Describe the bug

The game crashes everytime i join with mods either when i join the game or before the loading screen

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16445406/latest.log)

### Steps To Reproduce

```markdown
1.start pojav
2.select modpacks
3.join the game
4.join a world/server
5.the game crashes
```

### Expected Behavior

I expect my game to be playable when i have mods

### Platform

```markdown
- Device model: SM-A556B (a55xnaxx)
- CPU architecture: 4x ARM Cortex-A78 @ 2.75 GHz 4x ARM Cortex-A55 @ 2.05 GHz
- Android version: 14
- PojavLauncher version: edelweiss-20230927-5d010fc-v3_openjdk
```

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt

**Comment by Vasko9** [comment]
![latestlog.txt](https://github.com/user-attachments/files/16447485/latestlog.txt

**Comment by GaucovyAero** [comment]
sodium wont work

**Comment by Vasko9** [comment]
> sodium wont work

https://github.com/user-attachments/files/16448283/latestlog.txt what about now
