### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by DorianChow** [PojavLauncherTeam/PojavLauncher#5893]
### Is this request related to a bug?

Niewiem

### Describe the request.

Niewiem

### Anything else?

Nie można zalogować się na konto a jak już tak to jest błąd

**Comment by DorianChow** [comment]
Proszę to naprawisz proszę bardzo

**Comment by GaucovyAero** [comment]
try logging into minecraft.net first and set up your username, then try logging into pojav again
