### ISSUE TITLE
[BUG] Game crashes when loading decocraft mod in Forge 1.16.5

### ISSUE THREAD

**Issue by Vini158916** [PojavLauncherTeam/PojavLauncher#5894]
### Describe the bug

When I put the Decocraft mod in Forge 1.16.5, during loading, the game crashes. This also happens in Forge 1.14.4, in Forge versions 1.12.2 and 1.7.10 it does not happen. Decocraft is not the only mod that has this error, other mods like it crash (except Crayfish Furniture). Even increasing the memory does not solve it.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16447000/latestlog.txt)
Log file when loading mod in Forge 1.16.5

### Steps To Reproduce

```markdown
1. Start Pojavlauncher and launch 
minecraft.
2. Wait for mod loading
Result: Game crash
```

### Expected Behavior

The game loads normally and play minecraft

### Platform

```markdown
- Device model: Samsung Galaxy S20 FE 5G (Samsung SM-G781B)
- CPU architecture: arm64
- Android version: Android 13
- PojavLauncher version: edelweiss-20240618-856bace-v3_openjdk
```

### Anything else?

Note: I'm using a 32 modpack for this version, so if the problem is one of the mods, there is the mods names (I cant upload the entite modpack because of the files size)
[modpack.txt](https://github.com/user-attachments/files/16447132/modpack.txt)
Note 2: I'm using a github actions build

**Comment by GaucovyAero** [comment]
the latestlog link is broken

**Comment by Vini158916** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16457192/latestlog.txt)
Try this link now

**Comment by GaucovyAero** [comment]
try using zink

**Comment by Vini158916** [comment]
The game crashes instantly when using zink

**Comment by GaucovyAero** [comment]
> The game crashes instantly when using zink

send log

**Comment by Vini158916** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16457284/latestlog.txt)

**Comment by GaucovyAero** [comment]
you are on an outdated version of pojav

**Comment by Vini158916** [comment]
Soo, I need to download from the play store or latest github release. Because I'm using an actions build of pojav

**Comment by GaucovyAero** [comment]
just update your actions build to the latest one

**Comment by Vini158916** [comment]
No, I will just download the latest version of pojav, because the actions build I'm using fixes a crash in forge 1.20.4 and I don't play anymore in this version (and it's so laggy for my phone)

**Comment by Vini158916** [comment]
I downloaded the lastest github action build (I changed my mind) and It's still crashes

**Comment by GaucovyAero** [comment]
rip, thats means zink doesnt support your phone, at least not on the stock OS
