### ISSUE TITLE
[hit particles] hit particles not showing

### ISSUE THREAD

**Issue by pojavaddicted** [PojavLauncherTeam/PojavLauncher#5899]
### Describe the bug

The hitparticles are not showing up when im not using a sharpness sword. Crits work normal tho

### The log file and images/videos

https://github.com/user-attachments/assets/e57bb53c-4461-4d52-a74a-f203e0f9682a

### Steps To Reproduce

```markdown
Join a pvp server like mineberry on 1.8.9 then join like a bedwars game, bridge over to someone and start fighting 

The hit particals only will show up if u buy sharpness
```

### Expected Behavior

Im expecting my hit particles to show up without needing sharpness

### Platform

```markdown
- Device model: samsung galaxy A54 5G
- CPU architecture: arm64 i think 
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by artdeell** [comment]
go to minecraft video settings and change particles to "all"

**Comment by pojavaddicted** [comment]
I already tried that

**Comment by GaucovyAero** [comment]
the "hit particles" only show up if you have sharpness on your sword
