### ISSUE TITLE
[BUG] Forge 1.18.2 40.2.21 Optifine Crash

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5901]
### Describe the bug

Just Crashing own made modpack with forge

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16487511/latestlog.txt)

### Steps To Reproduce

```markdown
1. Started PojavLauncher
2. Installed Forge
3. Installed mods
4. Installed Optifine
5. Launched the Game
```

### Expected Behavior

Just Crash

### Platform

```markdown
- Device model: Samsung S20FE 5G (SM-G780G)
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
remove darkmodeeverywhere
