### ISSUE TITLE
[BUG] 1.20.1 Modded Crash

### ISSUE THREAD

**Issue by Average6fps** [PojavLauncherTeam/PojavLauncher#5904]
### Describe the bug

An LWJGL error which causes the game to crash

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16489143/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install 1.20.1 Forge
2. Drop mods into the mods folder
3. Launch the game
```

### Expected Behavior

Game booting up correctly and the mods working

### Platform

```markdown
- Device model: Samsung A14 4/128G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240803-e4120f3-revert-5560-no-piracy
```

**Comment by ctl-axixmz** [comment]
Ur device dont support zink

**Comment by GaucovyAero** [comment]
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
```

**Comment by Average6fps** [comment]
So I should off the zink renderer? Ain't no way that was so easy

**Comment by GaucovyAero** [comment]
try this

*/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt*

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```

**Comment by Average6fps** [comment]
Oh thanks but I already fixed the problem

**Comment by ghost** [comment]
If you fixed so WHY you reported
