### ISSUE TITLE
Fabric loadng problem[BUG] <Short description>

### ISSUE THREAD

**Issue by Abanob-amgad** [PojavLauncherTeam/PojavLauncher#5907]
### Describe the bug

I have trouble loading fabric loader 0.15.11-1.20.1 wile using fabric api and a mod called immersive portals when I load minecraft it says error loading resources and when I try to join any game my game crashes so please help
[latestlog.txt](https://github.com/user-attachments/files/16495590/latestlog.txt) this is the latest log

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16495693/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavluncher
2.enters minecraft
3.an error pops up and says error loading resources
4.join a world
5.the game crashes
```

### Expected Behavior

A year ago I tried to use the immersive portals and it worked perfectly

### Platform

```markdown
- Device model:BAH3-LO9
- CPU architecture: Mali-G52 MP6 (I am not sure what did u want by cpu architecture)
- Android version: HarmonyOS 2.0.0
- PojavLauncher version:latest
```

### Anything else?

I want to play this mod so please help me

**Comment by GaucovyAero** [comment]
```
Recovery reason: java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
```

the shaders used by the mod are not supported by gl4es, try using a different renderer, if that doesnt work, you gotta get a device with a snapdragon
