### ISSUE TITLE
请加入版本隔离功能

### ISSUE THREAD

**Issue by FFDVDGD** [PojavLauncherTeam/PojavLauncher#5908]
### Is this request related to a bug?

无关吧

### Describe the request.

请问可以加入版本隔离功能吗？或者如果支持的话请问该如何开启。

**Comment by GaucovyAero** [comment]
what does version isolation mean?

**Comment by FFDVDGD** [comment]
差不多就是这样。https://hmcl.huangyuhui.net/help/launcher/isolation.html

**Comment by GaucovyAero** [comment]
this wont be done, but you can change the game directory in profile options
