### ISSUE TITLE
Crash -1

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#5909]
### Describe the bug

Crash When loading game 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16506405/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.loading
2.crash
```

### Expected Behavior

No

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: ?
- Android version: 12
- PojavLauncher version: playstore latest
```

**Comment by GaucovyAero** [comment]
remove enhanced block entities
