### ISSUE TITLE
[BUG] Can't join cracked servers

### ISSUE THREAD

**Issue by TheRhu4n** [PojavLauncherTeam/PojavLauncher#591]
So, the title says it all. I can't join any cracked servers. I usually get this error: io.netty.channel.abstractchannel$annotatedconnectexception
Servers like mineplex, hypixel works fine

**Comment by xszqxszq** [comment]
Not related to cracked. Its probably because these servers use SRV record, which is not supported by pojav.

**Comment by TheRhu4n** [comment]
Got it. Actually I've find a way to bypass that just by enabling the wifi hotspot on the phone, when it's enabled I can join those servers

**Comment by Mathias-Boulay** [comment]
The issue has been fixed thanks to artdell.
Closing the issue.
