### ISSUE TITLE
<bug> pojavlauncher inner bug very annoying

### ISSUE THREAD

**Issue by Rvecececdwdwfx** [PojavLauncherTeam/PojavLauncher#5910]
### Describe the bug

This bug is very annoying I am using 43 mods when I join a server or singleplayer world and I will click on forward button but when I click it will continually moving and when click on another button it will also. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16509390/latestlog.txt)

### Steps To Reproduce

```markdown
I don't have idea
```

### Expected Behavior

Don't know

### Platform

```markdown
- Device model: LRNS10GIL0
- CPU architecture: 
- Android version: 10
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
remove sodium and all related mods
