### ISSUE TITLE
exit code1

### ISSUE THREAD

**Issue by sadfl** [PojavLauncherTeam/PojavLauncher#5911]
### Describe the bug

When I entered 1.20.6forge, it didn't run anything, and then it crashed.

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16512041/latest.log)

### Steps To Reproduce

```markdown
1. Start pojavlaunch
2.Login Account
3.Click to execute jar
4. Select the 1.20.6force file
5.install
6.Open 1.20.6force version mc
7.Enter
8.Collapse
```

### Expected Behavior

It enters normally

### Platform

```markdown
- Device model: HTC Desire 22 pro
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
send the crash report pls
