### ISSUE TITLE
[BUG] Access denied error with any mod

### ISSUE THREAD

**Issue by clmc99** [PojavLauncherTeam/PojavLauncher#5912]
### Describe the bug

My Minecraft 1.20.1/Forge 47.3.5 installation crashes with an access denied error if I have mods in the mods folder (the example shown here is with Canary but it appears to happen with any mod). I'm using the internal Java 17 and default OpenGL renderer.

### The log file and images/videos

[Log file](https://github.com/user-attachments/files/16516012/latestlog.1.txt)

![Screenshot_20240806_170519_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/8d5b65e1-c0b9-4e71-aa8c-729965d9032e)
![Screenshot_20240806_170527_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/f2793eeb-c132-4946-8a90-c925d11b47f5)

### Steps To Reproduce

```markdown
1. Install and start the latest version of PojavLauncher from the Play Store (foxglove-20240727-ae48e8e-v3_openjdk)
	1a) Modify settings as shown above*
2. Create installation with latest version of Forge 1.20.1
	2a) Set Java version of installation to internal Java 17*
3. Put any mod in the mods folder (/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods; tested with Canary, FerriteCore, and ModernFix)
4. Press Play

*not known if necessary to reproduce
```

### Expected Behavior

Minecraft successfully loads into the menu screen. This is what happens when I have no jars in the mods folder

### Platform

```markdown
- Device model: Samsung Galaxy Tab S9 FE
- CPU architecture: ARMv8-A
- Instruction sets: arm64-v8a
- Kernel architecture: aarch64
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

please help Parsec is broken

**Comment by GaucovyAero** [comment]
dont cut the mods, copy the mods, pretty sure you can fix existing mod permission issues in your folder by zipping and unzipping the mods

**Comment by clmc99** [comment]
This seems to work. Thank you for help!

**Comment by Godzilla6049** [comment]
clmc99 we have the same device i just have less ram and storage
