### ISSUE TITLE
[BUG] <CobbleMon 1.20.1>

### ISSUE THREAD

**Issue by Cruhp** [PojavLauncherTeam/PojavLauncher#5913]
### Describe the bug

I was trying to play Pokemon mod ( CobbleMon 1.20.1 ) when opened the game it just stopped I can't tap anything and and it takes a time to load the creating world everything was slow how to fix this issue?

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16516626/latestlog.txt)

### Steps To Reproduce

```markdown
1. open pojavlauncher 
2. Open "Create Modpack Profile"
3. Install "CobbleMon"
4. Open the launcher 
5. It show's the menu but can't tap and everything is slow/lagging
```

### Expected Behavior

I expected that I can play normally without any error

### Platform

```markdown
- Device model: Infinix Smart 8 
- CPU architecture: 2×1.6 GHz Cortex-A75 and 6×1.6 GHz Cortex-A55 cores
- Android version: 13
- PojavLauncher version: edelweiss-20240531-bdc7f33-v3_openjdk
```

### Anything else?

Nothing else

**Comment by GaucovyAero** [comment]
for the touch issue, try to see if you have it on any other mc versions, maybe try removing a few mods from the modpack or try changing your controlmap to see if that helps, maybe try reinstalling pojav
as for the world loading slow, thats just your phone

**Comment by Cruhp** [comment]
I don't have mods I just reinstalled Pojav and first time using the CobbleMon but the game is laggy and it takes more time to load everything
