### ISSUE TITLE
Custom GLSL

### ISSUE THREAD

**Issue by RzdPai** [PojavLauncherTeam/PojavLauncher#5914]
### Is this request related to a bug?

Custom GLSL

### Describe the request.

Force the GLSL version to 460 and the GL version to 4.6 can solve the issue of zink crashing on some devices.

**Comment by CowSheep72** [comment]
yeah, much easier to use than replacing that one file that contains the overrides i think?

**Comment by ghost** [comment]
Vera firefly already add it

**Comment by ghost** [comment]
![Screenshot_2024-08-14-02-10-07-093_net kdt pojavlaunch firefly-edit](https://github.com/user-attachments/assets/95bcbee9-4c68-42fd-be7c-d2acd0df71ab)

**Comment by GaucovyAero** [comment]
do it manually via custom env

*/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt*

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```
