### ISSUE TITLE
Simply optimized mod not working

### ISSUE THREAD

**Issue by JARDIDS** [PojavLauncherTeam/PojavLauncher#5915]
### Describe the bug

For some reason the mod 'simply optimized' crashes whenever i try to load in a world and  normally when i start the launcher i get a pop up message saying that pojavlauncher is not supported with sodium
Update: its the modpack that has sodium. Im a bit slow

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16519528/latestlog.txt)

### Steps To Reproduce

```markdown
1. Started up pojavlauncher
2. Installed simply optimized (the latest version) from the add modpack profile option
3. Started up the launcher
3. Get popup message
4. Try to load in a world but game crashes
```

### Expected Behavior

I thought that the mod wouldve worked as normal when loading up a world

### Platform

```markdown
- Device model: samsung s23+
- CPU architecture: ARMv8
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
yeah sodium wont work as it requires new gl features that are not supported by gl4es
