### ISSUE TITLE
[BUG] Minecraft crashes when I switch to other apps (Samsung)

### ISSUE THREAD

**Issue by clmc99** [PojavLauncherTeam/PojavLauncher#5916]
### Describe the bug

When I switch to another app, the game closes itself. The log doesn't seem to have any sign of Minecraft crashing. The Pojav app itself stays open. I've tried lowering the allocated RAM to 2 GB with no effect, so I don't think it's an issue of allocating too much RAM

### The log file and images/videos

Example a log file: 
[latestlog.txt](https://github.com/user-attachments/files/16550003/latestlog.txt)

Settings modified:
![Screenshot_20240806_170519_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/19ee2166-983e-4e92-b7a4-cd7dd18898a3)
![Screenshot_20240806_170527_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/e05dcbf0-457e-48c3-a78b-0cec64ff3aa1)

### Steps To Reproduce

```markdown
1. Install and start the latest version of PojavLauncher from the Play Store (foxglove-20240727-ae48e8e-v3_openjdk)
	1a) Modify settings as shown above*
2. Create installation with latest version of Forge 1.20.1
	2a) Set Java version of installation to internal Java 17*
3. Start the game, wait for the menu screen to appear
4. Switch to another app using the built-in Android app switcher
5. Switch back to Pojav. The Pojav home screen, instead of Minecraft, will be showing

*Not known if necessary to reproduce. Appears to recur regardless of RAM setting
```

### Expected Behavior

I expect to be able to switch to another app and come back to Pojav without Minecraft closing.

### Platform

```markdown
- Device model: Samsung Galaxy Tab S9 FE
- CPU architecture: ARMv8-A
- Instruction sets: arm64-v8a
- Kernel architecture: aarch64
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

Parsec is still broken please help

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt

**Comment by clmc99** [comment]
Edited

**Comment by NinjaLegendmc** [comment]
Crash cause because of alternate surface rendring try disable alternate surface rendring

**Comment by GaucovyAero** [comment]
try disabling earlyWindowControl in .minecraft/config/fml.toml and see if that helps

**Comment by kasrarouhi** [comment]
I don't know but if you turn no background process in developer option turn to standard limit

**Comment by mozyu28282828** [comment]
Same here.
In my case, it's only when the forge is installed. Vanilla and fabric are no problem.
Still no luck.

**Comment by mozyu28282828** [comment]
> try disabling earlyWindowControl in .minecraft/config/fml.toml and see if that helps

This is worked! Thank you!
