### ISSUE TITLE
[BUG] Add JNA 7.0.0

### ISSUE THREAD

**Issue by Idkwoeer** [PojavLauncherTeam/PojavLauncher#5920]
### Describe the bug

Basically some mods crash and leave this
Expected: 7.0.0
Found:    6.1.6

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1.Start pojav
2. Fabric with mods 
3. Crash
4. Expected: 7.0.0
Found:    6.1.6
```

### Expected Behavior

I expect it to work 

### Platform

```markdown
- Device model: idk
- CPU architecture: android 14
- Android version: 17
- PojavLauncher version: last
```

### Anything else?

No please fix

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
duplicate of #5634
