### ISSUE TITLE
[Crashing] The Betweenlands mod crashes when entering the dimension

### ISSUE THREAD

**Issue by Marcemcc** [PojavLauncherTeam/PojavLauncher#5921]
### Describe the bug

I'm playing quietly, I enter the mod portal and the game suddenly closes 

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16556719/latest.log)

### Steps To Reproduce

```markdown
-Install forge 1.12 14.23.5.2860
-place the Betweenlands mod and qof mods
-enter a world
```

### Expected Behavior

The game works perfectly until I enter the mod portal

### Platform

```markdown
- Device model: Tecno Pova 5 8/256
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

help 🔥

**Comment by GaucovyAero** [comment]
try sending me the mod's config file, it has custom shaders that dont work on pojav

**Comment by Marcemcc** [comment]
[thebetweenlands.zip](https://github.com/user-attachments/files/16561589/thebetweenlands.zip)
I put the folder because the file cannot be sent

**Comment by GaucovyAero** [comment]
[config.zip](https://github.com/user-attachments/files/16564842/config.zip)

try with this

**Comment by Marcemcc** [comment]
Your configuration did not work, but speaking about shaders from the mod I just had to disable them in the game - settings![Screenshot_20240809-175840.jpg](https://github.com/user-attachments/assets/02ef5417-0ee2-4561-b2ce-5e26628a71fc)

**Comment by Marcemcc** [comment]
Now it works
