### ISSUE TITLE
Game crashing with zink  renderer and sodium mod

### ISSUE THREAD

**Issue by rishabha102010** [PojavLauncherTeam/PojavLauncher#5922]
### Describe the bug

When I start the game it crashes for zink renderer and sodium crashes for gl4es iam using sunsungM32 5G ARM mali G57 MC3 please fix this issue

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16561068/latestlog.txt)

### Steps To Reproduce

```markdown
Startpojavlauncher game opens with zink and crashes
```

### Expected Behavior

I though that latest version must fix everything but not.

### Platform

```markdown
- Device model: sunsungM32 5G
- CPU architecture: A76,6x2.0GHz Armcortex A55
- Android version: 13
- PojavLauncher version: foxglove.latest playstore version
```

### Anything else?

Add a playstore update for zink crash fix for mali and sodium crash fix for all renderer

**Comment by rishabha102010** [comment]
Please help wanted

**Comment by kiokori-git** [comment]
sodium isn't supported, no support will be provided

**Comment by rishabha102010** [comment]
What about zink

**Comment by ghost** [comment]
> sodium isn't supported, no support will be provided

Sodium is supported for pojav. Depends on your gpu

**Comment by rishabha102010** [comment]
Back to old update my sodium was supported on zink but now the only renderer provides zink in my device is now crashing

**Comment by kiokori-git** [comment]
> > sodium isn't supported, no support will be provided
> 
> Sodium is supported for pojav. Depends on your gpu

are you blind? do you not see the big red notification on top-left of your screen? i'm not repeating this again.

**Comment by rishabha102010** [comment]
Ok

**Comment by rishabha102010** [comment]
Then I can't run sodium mod so next update make the game optimised well for gl4es I asked sodium for only optimising purpose only sorry

**Comment by kiokori-git** [comment]
> Then I can't run sodium mod so next update make the game optimised well for gl4es I asked sodium for only optimising purpose only sorry

gl4es already runs great, its your phone

just use optifine

**Comment by rishabha102010** [comment]
Bro you serious but game runs with low framarates but no problem  youtubers will provide supported sodium mod by their own so I'll wait and use it thank you

**Comment by kiokori-git** [comment]
> Bro you serious but game runs with low framarates but no problem youtubers will provide supported sodium mod by their own so I'll wait and use it thank you

yeah the game runs like trash is because of your phone, stop crying and expect to get 500 FPS on your nokia 8810

**Comment by rishabha102010** [comment]
What I actually love in this update is I can turn off v-sync with zink shaders run smoothly depends on our device

**Comment by kasrarouhi** [comment]
> > > sodium isn't supported, no support will be provided
> > 
> > 
> > Sodium is supported for pojav. Depends on your gpu
> 
> are you blind? do you not see the big red notification on top-left of your screen? i'm not repeating this again.

![Screenshot_2024-08-09-22-02-46-785_com android chrome-edit](https://github.com/user-attachments/assets/48f871ff-5313-425c-8877-d65668a67bb9)

Sodium work on adreno 730

**Comment by ghost** [comment]
> > > sodium isn't supported, no support will be provided
> > 
> > 
> > Sodium is supported for pojav. Depends on your gpu
> 
> are you blind? do you not see the big red notification on top-left of your screen? i'm not repeating this again.

It's not my say

![Screenshot_2024-08-09-22-02-46-785_com android chrome-edit](https://github.com/user-attachments/assets/edf0619d-f10b-49dc-9e04-a4814a76c0fc)

For beta-mango sodium work

**Comment by CowSheep72** [comment]
> > sodium isn't supported, no support will be provided
> 
> Sodium is supported for pojav. Depends on your gpu

no. it isnt. sodium currently requires tweaks to even run on pojav, and that includes breaking optimizations. your answer? sodium is useless.

**Comment by CowSheep72** [comment]
> > sodium isn't supported, no support will be provided
> 
> Sodium is supported for pojav. Depends on your gpu

sodium on zink even requires tweaks for some versions, as evidenced by the input delay bug.

**Comment by CowSheep72** [comment]
> Then I can't run sodium mod so next update make the game optimised well for gl4es I asked sodium for only optimising purpose only sorry

gl4es and angle currently lacks a lot of extensions required for sodium, given the performance of zink today... yeah it's useless

**Comment by CowSheep72** [comment]
> > Then I can't run sodium mod so next update make the game optimised well for gl4es I asked sodium for only optimising purpose only sorry
> 
> gl4es and angle currently lacks a lot of extensions required for sodium, given the performance of zink today... yeah it's useless

not saying that some sodium versions can't launch and enter worlds on angle, some sodium versions launch on angle(0.3.x or 0.4.x?) and can even launch worlds, however it's still useless i believe

**Comment by ghost** [comment]
Need to wait for see any good optimization mod create for pojav because optifine is not release for 1.21 after months and sodium is very strict for Android gpu.

**Comment by CowSheep72** [comment]
kio does have a list of performance mods that are more compatible than optifine, but lacks shaders and i'm not even sure if some of those even exist for 1.21

**Comment by not-incogn170** [comment]
optikai is released for 1.21, you can try that

**Comment by rishabha102010** [comment]
Ok let me

**Comment by GaucovyAero** [comment]
for the zink issue, try this

_/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt_

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```

**Comment by kasrarouhi** [comment]
I think mean try vera firefly forks because have this

**Comment by rishabha102010** [comment]
Where to paste this

**Comment by GaucovyAero** [comment]
> Where to paste this

the file path is in the quote in my message

**Comment by rishabha102010** [comment]
Thank you zink error is fixed thank you and ❤️!!!!!!!!

**Comment by rishabha102010** [comment]
Well now the game fps caped under 40 what to do

**Comment by rishabha102010** [comment]
Even after turning of vsync with zink
