### ISSUE TITLE
Zink renderer limits the game fps under 40

### ISSUE THREAD

**Issue by rishabha102010** [PojavLauncherTeam/PojavLauncher#5924]
### Describe the bug

Whenever I use zink renderer the game lags a lot shaders are extremely laggy

### The log file and images/videos

Game got vsync with zink

### Steps To Reproduce

```markdown
Game lags when using zink vsynced
```

### Expected Behavior

I though the game runs like gl4es without vsync

### Platform

```markdown
- Device model: sumsungM32 5G
- CPU architecture: 2.0 ghxarm cortexa76,6x2.0ghxarmcortexA55
- Android version: 13
- PojavLauncher version: foxglove
```

### Anything else?

Please explain how to fix this

**Comment by rishabha102010** [comment]
Any one please tell me how to fix this

**Comment by Bel69420** [comment]
Zink was not developed by us, go ask mesa3d.

**Comment by rishabha102010** [comment]
Ok

**Comment by rishabha102010** [comment]
Where do I go for him

**Comment by GaucovyAero** [comment]
thats your phone, maybe you can try this but i doubt its gonna work or anything
*/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt*

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
vblank_mode=0
```

**Comment by rishabha102010** [comment]
No it doesn't work for me 🥲

**Comment by GaucovyAero** [comment]
rip, cant really help, thats most likely just your phone not being good enough to get more fps

**Comment by rishabha102010** [comment]
But in gl4es I got 100 plus more

**Comment by GaucovyAero** [comment]
thats because gl4es is faster, its not that your fps are capped
