### ISSUE TITLE
[BUG] <Unable to create target directory>

### ISSUE THREAD

**Issue by riaddair** [PojavLauncherTeam/PojavLauncher#5928]
### Describe the bug

wanted to download fabric 1.16.5 and it say unable to create target directory
java.io.IOException: Unable to create target directory
at net.kdt.pojavlaunch.utils.FileUtils.ensureDirectory(FileUtils.java:59)
at net.kdt.pojavlaunch.modloaders.FabriclikeDownloadTask.runCatching(FabriclikeDownloadTask.java:57)
at net.kdt.pojavlaunch.modloaders.FabriclikeDownloadTask.run(FabriclikeDownloadTask.java:37)
at java.lang.Thread.run(Thread.java:923)

### The log file and images/videos

0 byte bin file i cant check it

### Steps To Reproduce

```markdown
1.starting pojav launcher 
2.click download fabric 1.16.5
3.getting "Unable to create target directory" error
```

### Expected Behavior

Need to download

### Platform

```markdown
- Device model: realme c25y 
- CPU architecture: arm64-v8a
- Android version: 11
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

Pls help i didnt see this error solution

**Comment by GaucovyAero** [comment]
yeah i have absolutely no idea, does not happen on my device

**Comment by riaddair** [comment]
> yeah i have absolutely no idea, does not happen on my device

Bruh that is impossible to get this error first time in the world

**Comment by GaucovyAero** [comment]
cannot reproduce
