### ISSUE TITLE
[BUG]Come alive mod did not work

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#593]
I have follow all the inctruction carefully to get this mod working but when I load into the world the crystall ball in come alive mod did not appear.... The mod did not work

**Platform:**
 - Device Model [Vivo y17 4/64GB]
 - CPU architecture [aarch64] 
 - Android Version [9]

**Comment by WesleyVanNeck** [comment]
not our issue but the mod probely
