### ISSUE TITLE
[BUG] OpenGL errors on S24 Ultra and no shaders support/instant crash

### ISSUE THREAD

**Issue by DosDokTor** [PojavLauncherTeam/PojavLauncher#5934]
### Describe the bug

S24 Ultra: Adreno 750 on driver 744, ZINK does not work at all and ANGLE does not run shaders. It throws the errors: 1280 (invalid enum) under no shaders, 1286 (invalid buffer operation) while under the internal shader, showing a black screen. Would be weird for an overpowered phone to not run a single shader.
![Screenshot_20240812_113729_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/a380bb6f-41f9-4620-811e-c24d6dd38cd3)
![Screenshot_20240812_113751_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/f9841f81-b6ef-4c3d-b4df-5460eed8e9b4)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16580448/latestlog.txt)

### Steps To Reproduce

```markdown
Install PojavLauncher on a S24Ultra, try to run any shaders.
```

### Expected Behavior

I would expect a Snapdragon 8 Gen 3 to run Minecraft at least as well as a Snapdrsgon 865, but it crashes instantly, instead.

### Platform

```markdown
- Device model: S24 Ultra
- CPU architecture: AARCH64 SDM8G3
- Android version: 14
- PojavLauncher version: foxglove-20240803-ce958b6-v3_openjdk
```

**Comment by ghost** [comment]
Try vera firefly patches. Supported adreno 750

**Comment by DosDokTor** [comment]
Hey, that worked, thanks so much.

**Comment by FragDev** [comment]
Where are the vera firefly patches? Can't seem to find them.

**Comment by ghost** [comment]
> Where are the vera firefly patches? Can't seem to find them.

https://github.com/Vera-Firefly/Pojav-Glow-Worm

**Comment by DataShar** [comment]
How do i use the vera firefly patches for s24 ultra so i can use shaders?

**Comment by DosDokTor** [comment]
You download the latest PojavGlowWorm build and add the shaderpacks to the
normal folders.

**Comment by azurawrtata** [comment]
Some shader require older turnip (mostly SEUS based shader) but this doesn't matter anyway since there's plenty good shader out there.
