### ISSUE TITLE
[BUG] Controller double trigger input

### ISSUE THREAD

**Issue by ZERO1234-hub** [PojavLauncherTeam/PojavLauncher#5935]
### Describe the bug

![Picsart_24-08-12_13-10-38-667](https://github.com/user-attachments/assets/58c36a7c-79fe-42ce-852e-650d0518a143)
Some controllers have 2 inputs for each trigger buttons; one being for pressing the trigger slightly and the other for pressing it all the way.
But it seems that in game both of these inputs are assigned to the same action, meaning that if a person pressed for an example the left trigger once the game will do the action twice instantly, this makes using things like buckets infuriating because most of the time it'll pick up and place in the blink of an eye.

### The log file and images/videos

![Picsart_24-08-12_13-10-38-667](https://github.com/user-attachments/assets/dccbd694-b310-46ca-b907-3c956212e671)

### Steps To Reproduce

```markdown
**An easy fix would be to disable the short press input, or the other way around.
I don't know how to program but I'm trying my best to explain the problem**
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Honor X7b 8/256GB
- Controller: PS4
- Android version: Android 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by danhminhquan123** [comment]
- Device model: Honor X7b 8/256GB
- Controller: PS4
- Android version: Android 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk

**Comment by GaucovyAero** [comment]
thx

**Comment by ZERO1234-hub** [comment]
Alright guys so i found a temporary solution:
In the pojav mapping screen, assign the select button to "LT", and then assign the "LT" button to "L3".
Apparently there's a third input for some reason? but basically when you assign one of the triggers to a random button, it'll use a third input for that specific button instead of replacing the existing ones; so what i basically did is moving all the inputs aside to buttons that serve no function in game (Select & L3) to leave only the long press functioning on the trigger.
[Sorry if my english is a bit broken]

**Comment by ZERO1234-hub** [comment]
Oops
