### ISSUE TITLE
[BUG] Fabric/Forge Crashing every 4 mins or so

### ISSUE THREAD

**Issue by Zack694** [PojavLauncherTeam/PojavLauncher#5936]
### Describe the bug

It crashes the game randomly like 6 mins in the game

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16600389/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the game
2. Go to a world or a server
3. Crashes every 6-8 mins for no reason
```

### Expected Behavior

Crashes

### Platform

```markdown
- Device model: vivo 1906
- CPU architecture: 1.95 GHz Snapdragon 439 Octa-core
- Android version: Android 11
- PojavLauncher version: Foxglove or latest
```

**Comment by GaucovyAero** [comment]
out of memory

**Comment by Zack694** [comment]
> out of memory

Which memory? Ram or storage?

**Comment by ghost** [comment]
Ram
