### ISSUE TITLE
.minecraft folder not generating

### ISSUE THREAD

**Issue by randomusert** [PojavLauncherTeam/PojavLauncher#5937]
### Describe the bug

The .minecraft folder doesn't generate on vanilla instalation

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1. Launch Pojavlauncher 
2. Make a new profile
3. Check The files folder where it should Be located in with ZArchive For example
4. Seen that The folder didn't generate
```

### Expected Behavior

.minecraft folder should Be there

### Platform

```markdown
- Device model: OnePlus nord ce 3 lite 5g 8/128G
- CPU architecture: arm64
- Android version: 14 
- PojavLauncher version: foxglove-20240727-ae48e8e-v_openjdk
```

**Comment by GaucovyAero** [comment]
send proof

**Comment by ghost** [comment]
You meaning this 


![Screenshot_2024-08-14-00-24-06-629_ru zdevs zarchiver](https://github.com/user-attachments/assets/4e81b510-a1db-4144-81f7-08b0e5614074)

**Comment by ghost** [comment]
Go to
![Screenshot_2024-08-14-00-24-40-169_ru zdevs zarchiver-edit](https://github.com/user-attachments/assets/11526fbe-941d-4839-a082-546251f8a948)


And
![Screenshot_2024-08-14-00-24-49-022_ru zdevs zarchiver-edit](https://github.com/user-attachments/assets/dcc0df8c-813d-4640-b936-ca3b80067890)


And
![Screenshot_2024-08-14-00-24-57-792_ru zdevs zarchiver-edit](https://github.com/user-attachments/assets/5d607963-61d6-4309-a375-39e05bb3b4f7)


And
![Screenshot_2024-08-14-00-25-04-209_ru zdevs zarchiver-edit](https://github.com/user-attachments/assets/58792128-a053-4dd8-b1cc-9a544b282284)


And
![Screenshot_2024-08-14-00-25-12-127_ru zdevs zarchiver-edit](https://github.com/user-attachments/assets/be7fafa5-141b-4d7d-b2d4-ea423d505224)


And done

**Comment by ghost** [comment]
Be sure run Minecraft 1 time and wait Mojang studio screen load fully

**Comment by randomusert** [comment]
Didn't know it was a hidden folder
