### ISSUE TITLE
[BUG] <когда я запускаю minecraft 1.17 - 1.20, у меня вылатает с ошибкой кодом -1>

### ISSUE THREAD

**Issue by Rufar** [PojavLauncherTeam/PojavLauncher#5938]
### Describe the bug

Раньше такого не было, случилось это после установки последнего обновления Pojavlauncher. 

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/16608016/latest.log)

### Steps To Reproduce

```markdown
1. Запустить Pojavlauncher
2. Выбрать версию minecraft 1.20.2
3. Нажать "редактирование профиля"
4. Выбрать рендер "Angle"
5. поставить Java 17
6. Сохранить
7. Нажать "играть"
8. ожидание
9. Вылет
```

### Expected Behavior

Я ожидал что модпак "Popsicle Pack" запуститься без проблем, ведь раньше он запускался без проблем, как и с другими модпаками для Pojavlauncher

### Platform

```markdown
- Device model: Infinix hot 11s NFC
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Foxglove-20240727
```

### Anything else?

![Screenshot_20240814-095600](https://github.com/user-attachments/assets/95dcb110-6cb3-47af-b984-be1a69c0ae95)

**Comment by Rufar** [comment]
Он вылетает именно тогда когда я выбираю рендер "Angle" или рендер "Zink" для версий 1.17+ и выше. Откат на прошлую версию pojavlauncher я не пробовал.

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt

/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

**Comment by Rufar** [comment]
> неправильный лог, отправьте latestlog.txt
> 
> /хранилище/эмулированный/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt

[latestlog.txt](https://github.com/user-attachments/files/16608658/latestlog.txt)
Вот

**Comment by GaucovyAero** [comment]
you are missing lwjgl libraries for vulkanmod, support is complicated 
try getting the android vulkanmod libs from curseforge
