### ISSUE TITLE
[BUG] Cannot use Chinese IME to input

### ISSUE THREAD

**Issue by xszqxszq** [PojavLauncherTeam/PojavLauncher#594]
**Describe the bug**
Cannot type Chinese characters through IME in chat/cheat/anvil/sign or other places for input. **In some older builds (like [this](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/454419068)), Chinese input was supported, but it seemed to be removed soon.**
Strangely, other unicode characters(like Russian) can be input if keyboard layout is set to that language in system settings. However, there is no keyboard layout for Chinese on Android.

**To Reproduce**
1. Start PojavLauncher
2. Launch the game
3. Use Chinese IME(like sogou) to type anything

**Expected behavior**
I expected Chinese characters to be inputed.

**Screenshots**
Not available.

**Platform:**
 - Device Model [Huawei Nova youth]
 - CPU architecture [aarch64] 
 - Android Version [8]

**Comment by khanhduytran0** [comment]
Press keyboard before type non-English key, even when keyboard is showing.

**Comment by xszqxszq** [comment]
> Press keyboard before type non-English key, even when keyboard is showing.

Still the same after pressed keyboard

**Comment by xszqxszq** [comment]
> Press keyboard before type non-English key, even when keyboard is showing.

Tested on another Android 10 device and works. However, everytime I typed multi Chinese characters, only the first one appears.
![Screenshot_20210111_211523_net kdt pojavlaunch](https://user-images.githubusercontent.com/18241776/104187175-68f6fa80-5452-11eb-916c-35d71799929b.jpg)
![Screenshot_20210111_211532_net kdt pojavlaunch_edit_56641188310106](https://user-images.githubusercontent.com/18241776/104187263-84620580-5452-11eb-8c3f-e734022ff34a.jpg)

**Comment by artdeell** [comment]
What can I say
Multichar input can be supported...

**Comment by xszqxszq** [comment]
> What can I say
> Multichar input can be supported...

OK I will wait

**Comment by artdeell** [comment]
So, multichar was added in latest, and `replace(0 ... -1)` crash was fixed

**Comment by xszqxszq** [comment]
> So, multichar was added in latest, and `replace(0 ... -1)` crash was fixed

Confirmed, thanks
