### ISSUE TITLE
[BUG] <我在使用外接键盘时，因为使用shift，导致弹出输入法，卡成了小窗>

### ISSUE THREAD

**Issue by shuaishenshift** [PojavLauncherTeam/PojavLauncher#5940]
### Describe the bug

我连接了实体键盘后，因为按下了shift，导致弹出了输入法，并卡成了在全屏时再次按下f11时的样子，希望可以修复
![Screenshot_2024-08-15-16-01-47-06_67a64f1fc1b88908dad3392f76c1969b](https://github.com/user-attachments/assets/0f8d2d31-83e1-4aa8-889c-f2b0a5f0fec8)

### The log file and images/videos

![Screenshot_2024-08-15-16-01-47-06_67a64f1fc1b88908dad3392f76c1969b](https://github.com/user-attachments/assets/70129005-5dfd-498b-927e-7fbe5983bd51)

### Steps To Reproduce

```markdown
我重启了pojavlauncher后，再次启动游戏后,发现只要没有开启大写锁定的情况下，按什么键都没有bug，但只要打开了大写锁定，就会卡成这样的小窗
```

### Expected Behavior

我希望我的键盘再按下大写锁定或是shift时都可以不变成这样

### Platform

```markdown
- Device model:  Oppo A55 5G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240812-9e95930
```

**Comment by GaucovyAero** [comment]
bind fullscreen to f12 or something you dont use

**Comment by shuaishenshift** [comment]
Thank you！


________________________________
发件人: GaucovyAero ***@***.***>
发送时间: 2024年8月15日 21:14
收件人: PojavLauncherTeam/PojavLauncher ***@***.***>
抄送: shuaishenshift ***@***.***>; State change ***@***.***>
主题: Re: [PojavLauncherTeam/PojavLauncher] [BUG] <我在使用外接键盘时，因为使用shift，导致弹出输入法，卡成了小窗> (Issue #5940)


bind fullscreen to f12 or something you dont use

―
