### ISSUE TITLE
[BUG] <Short description>вылетает из игры как только полностью загружается полоска mojang

### ISSUE THREAD

**Issue by D1MpLe24** [PojavLauncherTeam/PojavLauncher#5943]
### Describe the bug

Установлено несколько модов и думаю что 1 из них в этом и виновен

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16634376/latestlog.txt)

### Steps To Reproduce

```markdown
Нажимаю играть жду загрузку вылет
```

### Expected Behavior

Я ожидаю что смогу по играть с этими модами

### Platform

```markdown
- Device model: red magic 9 pro
- CPU architecture: arm64-v8a
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
disable the flywheel backend in the create or flywheel config somewhere in .minecraft/config
