### ISSUE TITLE
[BUG] application/game exited with code -1

### ISSUE THREAD

**Issue by KingTSloth** [PojavLauncherTeam/PojavLauncher#5947]
### Describe the bug

When I try and start forge 1.8.9(no mods yet) I just waited a few seconds then it sends that msg
[latestlog.txt](https://github.com/user-attachments/files/16639883/latestlog.txt)

### The log file and images/videos

![Screenshot_20240816_123511_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/29876897-2b48-40c5-9218-02f66e5cc41e)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Download forge 1.8.9(any version)
3. Select that version of minecraft
4. Start minecraft
5. Wait 10 seconds-2 minutes
```

### Expected Behavior

I expect that I can run forge 1.8.9 without it crashing then run it with skyblock mods without it crashing.

### Platform

```markdown
- Device model: Samsung Note20 Ultra 5G/128G
- CPU architecture: idk how to find that out
- Android version: 13
- PojavLauncher version: Version foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
update forge

**Comment by KingTSloth** [comment]
> update forge

how?

**Comment by CowSheep72** [comment]
download a new version of forge on the installer, that simple

**Comment by CowSheep72** [comment]
@KingTSloth
