### ISSUE TITLE
[BUG] <Short description>el mas insano

### ISSUE THREAD

**Issue by PEKE273** [PojavLauncherTeam/PojavLauncher#5949]
### Describe the bug

Pekiii

### The log file and images/videos

ONICHAAAN

### Steps To Reproduce

```markdown
Nose
```

### Expected Behavior

Tiliiiin

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

MABPPE

**Comment by CowSheep72** [comment]
wtf

**Comment by 5ghzx** [comment]
What's the point of this garbage?

**Comment by ghost** [comment]
> What's the point of this garbage?

Don't know

**Comment by SaanMye** [comment]
You guys should fix mbappe bug lmao
