### ISSUE TITLE
[BUG] Vulkan mod with meteor client

### ISSUE THREAD

**Issue by ItzAbhishek794** [PojavLauncherTeam/PojavLauncher#5951]
### Describe the bug

When I tried to play meteor client with vulkan my pojavlauncher was crashing in any version how can I fix it.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16646440/latestlog.txt)

### Steps To Reproduce

```markdown
1. I PASTE FABRIC API AND METORE CLIENT AND VULKAN MOD IN MOD FOLDER
2. I OPEN THE GAME 
3. AND ITS CRASH
```

### Expected Behavior

Give me a solution to fix it

### Platform

```markdown
- Device model: Samsung galaxy a33 5g 
- CPU architecture: 64bit
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt

**Comment by ItzAbhishek794** [comment]
@GaucovyAero 
[latestlog.txt](https://github.com/user-attachments/files/16646437/latestlog.txt)

**Comment by ThatMG393** [comment]
Meteor Client is incompatible with VulkanMod. Please close the issue
