### ISSUE TITLE
Can't log in? 

### ISSUE THREAD

**Issue by Pord19mana** [PojavLauncherTeam/PojavLauncher#5952]
### Is this request related to a bug?

1-Logged in to Microsoft accont 
2- I put the Gmail and the password
3- After you are done, he goes out to this phrase[wrong] 
![Screenshot_٢٠٢٤٠٨١٨_٠٠٥٥٥٧](https://github.com/user-attachments/assets/db751611-c778-4054-9db6-1cb9575e6d96)
I hope to fix this problem or tell me about my benefit from it because if it is from Microsoft then please tell us! 

### Describe the request.

Please reply as soon as possible

### Anything else?

if it There is no problem in the server so please do not reply because I want to enjoy

**Comment by GaucovyAero** [comment]
log into minecraft.net first, make sure you bought minecraft java edition
