### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Itielo** [PojavLauncherTeam/PojavLauncher#5953]
### Is this request related to a bug?

itieioliverasantos475@gmail.com 

### Describe the request.

itieioliverasantos475@gmail.com

### Anything else?

itieioliverasantos475@gmail.com

**Comment by Itielo** [comment]
itieioliverasantos475@gmail.com

**Comment by Itielo** [comment]
itieioliverasantos475@gmail.com

**Comment by Itielo** [comment]
Itel

**Comment by Itielo** [comment]
Itel

**Comment by Itielo** [comment]
Itiel

**Comment by CowSheep72** [comment]
any mods, can you please remove the email addresses?

**Comment by VenomousSteam81** [comment]
why post your email
