### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by JesterX0** [PojavLauncherTeam/PojavLauncher#5954]
### Is this request related to a bug?

Gabanz 

### Describe the request.

vBbHaj

### Anything else?

nBb

**Comment by JesterX0** [comment]
Vvj

**Comment by JesterX0** [comment]
Bbgvk

**Comment by JesterX0** [comment]
Kdjxhkxnxzz

**Comment by JesterX0** [comment]
JesterX0

**Comment by JesterX0** [comment]
Hsbzbznznnznznznzhxggd

**Comment by JesterX0** [comment]
Helo

**Comment by JesterX0** [comment]
### https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#headings

**Comment by JesterX0** [comment]
> [_**__**_](url)

**Comment by JesterX0** [comment]
1. ``

**Comment by CowSheep72** [comment]
spam

**Comment by CowSheep72** [comment]
im sad that this isn't the good spam(the food), this is the bad spam
