### ISSUE TITLE
[BUG] <Immersive Portals Crash>

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#5958]
### Describe the bug

i try to go to immersive portals, wait a little and then it crashes. i only have fabric api 1.14.4 and immersive portals for 1.14.4.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16656415/latestlog.txt)

### Steps To Reproduce

```markdown
1. Get fabric api and immersive portals 1.14.4 and put in mods folder.
2. Open fabric 1.14.4.
3. Wait a little then it'll crash.
```

### Expected Behavior

the game to load up.

### Platform

```markdown
- Device model: TECHNO KG8
- CPU architecture: 64 bit
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

I downloaded Fabric API and Immersive Portals from curseforge, and fabric loader from pojavlauncher.

**Comment by GaucovyAero** [comment]
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance have_EXT_custom_border_color 
```

your gpu does not support zink, you can try this to get it running tho, it will likely not work tho

*/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt*

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```

**Comment by Marcosayfi** [comment]
> ```
> WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance have_EXT_custom_border_color 
> ```
> 
> your gpu does not support zink, you can try this to get it running tho, it will likely not work tho
> 
> _/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt_
> 
> ```
> MESA_GL_VERSION_OVERRIDE=4.6
> MESA_GLSL_VERSION_OVERRIDE=460
> ```

what renderer do i use?

**Comment by GaucovyAero** [comment]
you can only use zink to run the mod, if it doesnt work on your device, you cannot run the mod
