### ISSUE TITLE
[F-Req] make an app version for altstore pal 2.1

### ISSUE THREAD

**Issue by ItsRenCup** [PojavLauncherTeam/PojavLauncher#5961]
### Is this request related to a bug?

you know that now in the us you can get altstore without jailbreaking? the problem is that the pojav source does not work in the pal version of altstore

### Describe the request.

add another source for altstore pal 2.1

### Anything else?

no

**Comment by artdeell** [comment]
can you turn on jit in altstore pal? also i think distribution there still requires apple "notarization"
