### ISSUE TITLE
[BUG] looping loading screen

### ISSUE THREAD

**Issue by Darklord204** [PojavLauncherTeam/PojavLauncher#5962]
### Describe the bug

I installed Fabric 1.19.2 and installed a few mods, everything was going well, but the red loading screen started to loop, it happened 10-20 times and then it closed by itself. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16676154/latestlog.txt)

### Steps To Reproduce

```markdown
1. I logged into Pojavlaunchera and entered the game

2. I waited for about half an hour and still got the red screen 

3. And crashed
```

### Expected Behavior

I want it resolved without removing any of my mods (at least the important ones)

### Platform

```markdown
- Device model: redmi note 7 4/64gb
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: latest version
```

### Anything else?

Mods:

Geckolib
Jcraft:eyes of ender
Player animator
Modmenu
Sodium
Sodium extra
Reeses sodium options
Cloth config
Lazydfu

**Comment by GaucovyAero** [comment]
try updating fabric loader, if that doesnt work, you likely gotta remove geckolib and all the mods that need it
