### ISSUE TITLE
[BUG] Risugami's ML issue

### ISSUE THREAD

**Issue by sharusu** [PojavLauncherTeam/PojavLauncher#5963]
### Describe the bug

when installing ModLoader with Aether mod the game crashes 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16688060/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Installed Risugami's ML with Aether
3. Crash
```

### Expected Behavior

The game should have started 

### Platform

```markdown
- Device model: Samsung Galaxy S20FE 5G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove
```

**Comment by GaucovyAero** [comment]
dont use modloadertweaker, change the mainClass to net.minecraft.client.Minecraft instead

**Comment by sharusu** [comment]
> dont use modloadertweaker, change the mainClass to net.minecraft.client.Minecraft instead

But how?

**Comment by GaucovyAero** [comment]
didnt you edit the json? its in the json, just do a search in your text editor

**Comment by wackycreeper** [comment]
@sharusu See this tutorial:
https://youtu.be/8WQyx7OvLUo

**Comment by sharusu** [comment]
i already fix problem

**Comment by sharusu** [comment]
[b1.7.3ML.zip](https://github.com/user-attachments/files/16736299/b1.7.3ML.zip)
Who need here this b1.7.3ML with optifine
