### ISSUE TITLE
[BUG] screen

### ISSUE THREAD

**Issue by ZaniWomp** [PojavLauncherTeam/PojavLauncher#5965]
### Describe the bug

i used vulkan mod version 1.21-0.4.5.1 but the screen in the game changes to portrait 
![IMG-20240821-WA0222](https://github.com/user-attachments/assets/6a81773c-5b31-44f7-a7e3-614e0b984025)

### The log file and images/videos

![IMG-20240821-WA0222](https://github.com/user-attachments/assets/003d3ce8-c1a2-4fda-9fc2-e84ed48d9ae0)

### Steps To Reproduce

```markdown
1. start pojav launcher with mod vulkan
2. already in game
3. bug on screen
```

### Expected Behavior

nope

### Platform

```markdown
- Device model: oppo a96 8/256G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Zenith horizon 1.2.8
```

### Anything else?

There isn't any

**Comment by miggythewriter** [comment]
1. zenith is not official and you won't get help

**Comment by GaucovyAero** [comment]
turn off alternate surface rendering
