### ISSUE TITLE
[BUG] whatever this is

### ISSUE THREAD

**Issue by Marshall2439** [PojavLauncherTeam/PojavLauncher#5966]
### Describe the bug

Basically new snapshot doesn't work 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16708681/latestlog.txt)

### Steps To Reproduce

```markdown
Start game 
Wait to load
Deal which black screen and absolutely nothing
```

### Expected Behavior

Expected to run normally

### Platform

```markdown
- Device model: scamsung a53
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: foxglove
```

### Anything else?

Game is actually running but it's just a black screen. Music and clicking sound still works

**Comment by GaucovyAero** [comment]
rename the issue pls

**Comment by kasrarouhi** [comment]
He/she right. new Minecraft version 24w34a is buggy with holygl4es renderers
See

https://github.com/user-attachments/assets/e46be124-9676-495b-b424-92e4b4a70048

But after switch to zink renderers it's fixed

https://github.com/user-attachments/assets/3b4db13a-0463-4dc1-81e7-ab64202f0256

I turned off alternate surface rendering but still doesn't work on holygl4es

**Comment by ghost** [comment]
He/she right in newer Minecraft version 24W34A with holygl4es renderer. Screen is going to red and black but music plays. But after switch to zink renderer it's fixed see

With holygl4es

https://github.com/user-attachments/assets/dce77fbe-ff7b-4241-bb4a-f28a4983ec56

With zink

https://github.com/user-attachments/assets/b349010e-77b7-4b13-8143-8d0b7204994a

I turned off alternate surface rendering for holygl4es but still doesn't fixed


Device model:poco f5 12/256gb
CPU architecture: aarch64 
Android version:14.  Android 15 is coming soon for my device
PojavLauncher version:latest version on GitHub writes update to sdk 34

**Comment by ghost** [comment]
And this is not invalid. remove this mark for this issue

**Comment by ghost** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16710427/latestlog.txt)

**Comment by GaucovyAero** [comment]
the issue is invalid because of the name, closing in favor of #5968

**Comment by Marshall2439** [comment]
Bruh this issue is first one why close this

**Comment by GaucovyAero** [comment]
> Bruh this issue is first one why close this

you cant just name an issue "whatever this is"

**Comment by Marshall2439** [comment]
> > Bruh this issue is first one why close this
> 
> you cant just name an issue "whatever this is"

There are literally spam/brainrot issues here
