### ISSUE TITLE
Upgrade JNA library to 7.0.x

### ISSUE THREAD

**Issue by CloudBack0601** [PojavLauncherTeam/PojavLauncher#5967]
### Is this request related to a bug?

If JNA is out of date. Lots of mods cant run on 1.21

### Describe the request.

this thing can only be done by projavTeam bec users need ROOT to upgrade JNA

**Comment by CloudBack0601** [comment]
And JNA out of date also leads crash the game

**Comment by CloudBack0601** [comment]
I have solve my issues just now

**Comment by Idkwoeer** [comment]
> I have solve my issues just now

How did you fix it

**Comment by CloudBack0601** [comment]
> > I have solve my issues just now
> 
> How did you fix it

Get latest projav apk file
Go to java native access [Github Page](https://git.homegu.com/java-native-access/jna) and then looked for android-aarch64.jar (it was in lib/native folder)
Access the projavAPK/lib and you will see 4 folders（x86-64 x86 armeabi-v7a arm64-v&a）
Access 4 folders and cover the libjnidispatch.so files in turn
At this point your file manager should let you sign the APK just sign it 
Install the APK you changed

**Comment by CloudBack0601** [comment]
> > > I have solve my issues just now
> > 
> > How did you fix it
> 
> Get latest projav apk file
> Go to java native access [Github Page](https://git.homegu.com/java-native-access/jna) and then looked for android-aarch64.jar (it was in lib/native folder)
> Access the projavAPK/lib and you will see 4 folders（x86-64 x86 armeabi-v7a arm64-v&a）
> Access 4 folders and cover the libjnidispatch.so files in turn
> At this point your file manager should let you sign the APK just sign it 
> Install the APK you changed 
> 

My eng is bad: (
If you have problem understanding ask me

**Comment by Idkwoeer** [comment]
> > > > I have solve my issues just now
> > > 
> > > 
> > > How did you fix it
> > 
> > 
> > Get latest projav apk file
> > Go to java native access [Github Page](https://git.homegu.com/java-native-access/jna) and then looked for android-aarch64.jar (it was in lib/native folder)
> > Access the projavAPK/lib and you will see 4 folders（x86-64 x86 armeabi-v7a arm64-v&a）
> > Access 4 folders and cover the libjnidispatch.so files in turn
> > At this point your file manager should let you sign the APK just sign it
> > Install the APK you changed
> 
> My eng is bad: ( If you have problem understanding ask me

Can you patch the APK then share it with me?

**Comment by Idkwoeer** [comment]
> > > > I have solve my issues just now
> > > 
> > > 
> > > How did you fix it
> > 
> > 
> > Get latest projav apk file
> > Go to java native access [Github Page](https://git.homegu.com/java-native-access/jna) and then looked for android-aarch64.jar (it was in lib/native folder)
> > Access the projavAPK/lib and you will see 4 folders（x86-64 x86 armeabi-v7a arm64-v&a）
> > Access 4 folders and cover the libjnidispatch.so files in turn
> > At this point your file manager should let you sign the APK just sign it
> > Install the APK you changed
> 
> My eng is bad: ( If you have problem understanding ask me

Please?
