### ISSUE TITLE
[BUG] Cursed Legacy Fabric Do not started

### ISSUE THREAD

**Issue by sharusu** [PojavLauncherTeam/PojavLauncher#5969]
### Describe the bug

when launching Cursed Legacy Fabric the game crashes with code 1 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16733890/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Installed Cursed Legacy Fabric
3. Start game
Crash
```

### Expected Behavior

As you can see, the game should crash. 

### Platform

```markdown
- Device model: Samsung Galaxy S20FE 5G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove
```

### Anything else?

Problem After Problems... (thanks GaucovyAero for helping me in #5964 )

**Comment by GaucovyAero** [comment]
sorry for being a bit late, heres a tutorial

edit: wrong video, hold up

**Comment by GaucovyAero** [comment]
here

https://github.com/user-attachments/assets/a52066d6-c544-40cc-8c70-e2fbeb8d02ca

**Comment by sharusu** [comment]
Man youre a hero!:D
