### ISSUE TITLE
[BUG] <Short description>My Game Crashes In the new update At The Starting fo the Launcher 

### ISSUE THREAD

**Issue by iamking398** [PojavLauncherTeam/PojavLauncher#5970]
### Describe the bug

When I start my game it crashes with no reason I have tried with out mods and with mods also and it crashes

### The log file and images/videos

[latestcrash.txt](https://github.com/user-attachments/files/16735464/latestcrash.txt)
[latestlog.txt](https://github.com/user-attachments/files/16735466/latestlog.txt)

### Steps To Reproduce

```markdown
1) Starting of the Game
2) Game Crashes in 1sec
```

### Expected Behavior

I expected that It won't crash but it happens every single time

### Platform

```markdown
- Device model: Oppo K3 
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: newest update one foxglove
```

### Anything else?

Yea, My virtual Mouse does not work in new update

**Comment by GaucovyAero** [comment]
the log is not even the game

**Comment by iamking398** [comment]
Now also crashing it was fixed before

**Comment by GaucovyAero** [comment]
i cant help you with that if you dont send any of the right logs
