### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by SannyDey** [PojavLauncherTeam/PojavLauncher#5975]
### Is this request related to a bug?

Hello I'm trying to create Microsoft account

![IMG_20240819_162624](https://github.com/user-attachments/assets/5dc2d7b7-bd67-43ed-a16a-d92f122896cd)

### Describe the request.

Hello hello hello hello hello hello hello hello 

### Anything else?

Hello hello hello hello hello hello hello hello hello hello

**Comment by SannyDey** [comment]
I'm creating Microsoft account but dose not working please fix problems

**Comment by ghost** [comment]
Ammmm any log or video to proof it and what the hell
