### ISSUE TITLE
[BUG] OrnitheMC Installer issue

### ISSUE THREAD

**Issue by sharusu** [PojavLauncherTeam/PojavLauncher#5985]
### Describe the bug

when running the installer with Java 17... IT ASKED FOR 17 JAVA T_T

### The log file and images/videos

![Screenshot_20240827_224550_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/6b26a65d-797f-4402-8593-a47d09fb34bc)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start Installer
3. Issue
```

### Expected Behavior

OrnitheMC requires 17 java 

### Platform

```markdown
- Device model: S20FE
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove
```

**Comment by GaucovyAero** [comment]
the issue is that pojav detects the jar is runnable with java 8 hence why runs it like that, ima create a suggestion
