### ISSUE TITLE
[F-Req]  Add a option for external Minecraft account like ely.by

### ISSUE THREAD

**Issue by MDEmonY** [PojavLauncherTeam/PojavLauncher#5988]
### Is this request related to a bug?

no

### Describe the request.

You should add a feature for external Minecraft account, it will allow players to use skins, and also it'll give players too much advantage.

Thanks.

**Comment by GaucovyAero** [comment]
nope

**Comment by MDEmonY** [comment]
> nope

why?

**Comment by GaucovyAero** [comment]
out of scope for now, gotta wait another feature to come first
