### ISSUE TITLE
[crash] JAR native library unsupported

### ISSUE THREAD

**Issue by Jasvixx** [PojavLauncherTeam/PojavLauncher#5990]
### Describe the bug

When I try to enter a server it crashes with code -1, I'm playing on fabric 1.21.1. What do I have to do? I don't understand what the log tells me to do, what file do I have to "change"? or if you know another way to fix it please tell me ty

### The log file and images/videos

![Screenshot_2024-08-28-14-21-51-007_com mi globalbrowser](https://github.com/user-attachments/assets/c33fce3a-b9e1-4c43-ac1e-6419e6c7beba)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Open Minecraft and enter a world
3. Shows "Joining world" and "Loading terrain"
4. Crashes
```

### Expected Behavior

The game should load my world normally...

### Platform

```markdown
- Device model: Redmi Note 11s
- CPU architecture: arm
- Android version: 13
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
dont use mods that require jna on 1.21+ , you basically need to upgrade JNA to 7.0.0 but this breaks all mods that use jna on 1.20.4 and older to do it

follow the steps in #5634 to get the .so file, then fork pojav and change the lib in jniLibs folder, then enable actions to get the build, download, extract and install app-debug
