### ISSUE TITLE
Gl4es shader is buggy

### ISSUE THREAD

**Issue by rishabha102010** [PojavLauncherTeam/PojavLauncher#5991]
### Describe the bug

Shaders for holy gl4es is just looks so not giner and straight lines passing through shadows

### The log file and images/videos

Please tell something to fix

### Steps To Reproduce

```markdown
I don't know
```

### Expected Behavior

I thought the gl4es shader runs perfect in gl4es

### Platform

```markdown
- Device model: sumsung m32 5g
- CPU architecture: I don't know
- Android version: 11
- PojavLauncher version: foxglow
```

### Anything else?

Please tell what to do ill add the pictures and vidieos

**Comment by rishabha102010** [comment]
The shaders aren't working showing black screen

**Comment by rishabha102010** [comment]
If I activate the shader😭

**Comment by ghost** [comment]
> The shaders aren't working showing black screen

I don't know very much about holygl4es shaders but holygl4es renderer is not good at supporting shader you need run with zink renderer. Pojav glow worm is includes many renderers even vgpu for up to 1.16.5 support low level shaders with good performance but with zink renderer you can take amazing pictures like this

**Comment by ghost** [comment]
![Screenshot_۲۰۲۳-۱۲-۰۸-۱۹-۳۳-۳۰-۳۵۶_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/3329adaf-99d5-4eeb-98a4-666ddb956cbe)

**Comment by rishabha102010** [comment]
Oh thankyou

**Comment by GaucovyAero** [comment]
> If I activate the shader😭

thats the fault of your gpu not supporting precise rendering, get snapdragon if you want that
