### ISSUE TITLE
[BUG] MCHELI OVERDRIVE CRASH

### ISSUE THREAD

**Issue by Average6fps** [PojavLauncherTeam/PojavLauncher#5992]
### Describe the bug

A crash when starting up 1.7.10 Forge with Mcheli Overdrive installed

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16786878/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install 1.7.10 Forge 
2. Download and Install Mcheli Overdrive
3. Start the game
```

### Expected Behavior

For the game to start up correctly and the mod working correctly

### Platform

```markdown
- Device model: Galaxy A14 4/128G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
select java 8
