### ISSUE TITLE
[BUG] Rlcraft not starting 

### ISSUE THREAD

**Issue by Amenslord** [PojavLauncherTeam/PojavLauncher#5994]
### Describe the bug

Whenever I try to start a new world using the rlcraft modpack it loads in for 1second then goes black and says "shutting down internal server"

### The log file and images/videos

[latestlog-1.txt](https://github.com/user-attachments/files/16790836/latestlog-1.txt)

### Steps To Reproduce

```markdown
1. Start pojavlancher 
2. Load up rlcraft modpack 
3. Create new world 
4. "Shutting down internal server"
```

### Expected Behavior

I expect the modpack to work without shutting down 

### Platform

```markdown
- Device model: Samsung SM-S911B
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

Idk if it's a performance problem but it's a S23 so idk maybe its the settings

**Comment by GaucovyAero** [comment]
## In order for RLCraft to not crash, remove these mods:

- custommainmenumod
- fancyblockparticles
- dynamic surroundings
- soundfilters
### credits to @kasrarouhi on github
