### ISSUE TITLE
Sound is not working.

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#6]
I tested PojavLauncher on my phone multiple times, and sound didn't work.
Phone model: Xiaomi Mi5S Plus.
Firmware: LineageOS 16.0 Android 9
Kernel: 3.18.120
Architecture: Arm64 (AArch64)

**Comment by khanhduytran0** [comment]
Make sure you didn't SKIP download asset.

**Comment by artdeell** [comment]
I didn't. I'll check libopenal, maybe this helps.

**Comment by khanhduytran0** [comment]
OK found the problem: not implemented but not sure if it will work after implement. Fix `System.arraycopy()` and implement `sun.applet.AppletAudioClip`? will be in preview4.

**Comment by khanhduytran0** [comment]
Not at `sun.applet.AppletAudioClip` might be at OpenSLES can't be initialized.
![Screenshot_2020-03-22-15-22-55](https://user-images.githubusercontent.com/40482367/77245500-8bb0ec00-6c51-11ea-98b7-7e0b03c98517.png)

**Comment by khanhduytran0** [comment]
Another: adding `javax.sound.midi` backport may fix the problem.

**Comment by abdo-A028** [comment]
You are right ( javax.sound.midi ) 
What about downloading updates

**Comment by Azapru** [comment]
This is bug. It's not yet fixed...

**Comment by abdo-A028** [comment]
> Not at `sun.applet.AppletAudioClip` might be at OpenSLES can't be initialized.
> ![Screenshot_2020-03-22-15-22-55](https://user-images.githubusercontent.com/40482367/77245500-8bb0ec00-6c51-11ea-98b7-7e0b03c98517.png)

How did you get this app?

**Comment by artdeell** [comment]
SLES problem still exists in 9b4
![Screenshot_20200402-130115_PojavLauncher_(Minecraft_Java_Edition_for_Android)](https://user-images.githubusercontent.com/45949002/78236157-4ce92480-74e2-11ea-9302-f8af511f2b37.png)

**Comment by khanhduytran0** [comment]
As you know, fixed by use @.kcat's OpenAL
