### ISSUE TITLE
POWER VR VULKAN ZINK COMPABILITY 

### ISSUE THREAD

**Issue by GTG921** [PojavLauncherTeam/PojavLauncher#6001]
### Is this request related to a bug?

YOU SHOULD MAKE VULKAN ZINK SUPPORT POWER VR GPU OR BRING OLD MESA ZINK BACK

### Describe the request.

I like to play minecraft with shaders but vulkan zink is crashing in my phone.I came to known that it was due to gpu.So,I request you make vulkan zink support power vr devices.Otherwise,try to bring old mesa zink back.It not my request alone.like me most of people's request too

**Comment by CowSheep72** [comment]
never >:)

**Comment by Felix14-v2** [comment]
Use [Simply Upscaled](https://modrinth.com/mod/simply-upscaled) (or [Open4Es](https://github.com/Open4Es/Open4Es-Shader-Android)) and GL4ES for both shaders and good performance

**Comment by GTG921** [comment]
Why can't you bring old mesa zink back

**Comment by Felix14-v2** [comment]
Idk, i'm not a dev. But Zink is extremely slow anyways, you can improve your framerate multiple times just by changing the renderer. For example:
|Renderer|Screenshot|Settings|Average|Version|
|---|---|---|---|---|
|Zink|![Screenshot_20221214-010216](https://github.com/user-attachments/assets/a7807652-cf63-4d26-8e6e-a98316d2693c)|2 chunks, lowest settings|3 FPS|1.16.5|
|GL4ES|![Screenshot_20240730-144457](https://github.com/user-attachments/assets/23dfc97d-4082-46d9-adaf-d0a20be66138)|4 chunks, mid settings|25 FPS|1.20.1|

That's on my MediaTek Helio G85 (Mali G52 MC-2 GPU)

**Comment by GTG921** [comment]
But good shaders like bsl,chocapic are only for opengl 4.6
By perfomance wise it is good,but quality wise is not that much

**Comment by GTG921** [comment]
If you known how to improve fps in 1.20.1 please tell me.
Even when I use performance mods also I was receiving only 3 fps

**Comment by Felix14-v2** [comment]
Join PojavLauncher discord to get help with that, this is the issue tracker, not a help center

**Comment by GTG921** [comment]
Where I get link of the discord channel

**Comment by Felix14-v2** [comment]
https://pojavlauncherteam.github.io/DISCORD.html

**Comment by miggythewriter** [comment]
Crazy
