### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by JaxxonSlimp** [PojavLauncherTeam/PojavLauncher#6002]
### Describe the bug

it wont let me use projavLunchiter

### The log file and images/videos

it wont let me use projavLunchiter

### Steps To Reproduce

```markdown
it wont let me use projavLunchiter
```

### Expected Behavior

it wont let me use projavLunchiter

### Platform

```markdown
- PojavLauncher version:
```

### Anything else?

it wont let me use projavLunchiter

**Comment by CowSheep72** [comment]
ah yes, i love "ProjavLunchiter"

**Comment by CowSheep72** [comment]
do you mean "Pro Java Luncheater"?
