### ISSUE TITLE
Fabric 1.21.1 crashes with angle rendered java 21

### ISSUE THREAD

**Issue by Algiuxs** [PojavLauncherTeam/PojavLauncher#6003]
### Describe the bug

When I launch fabric, I can get to the title screen, but when I try to load a world in single player it crashes when it loads to 100%

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16814584/latestlog.txt)

### Steps To Reproduce

```markdown
1 Download fabric 1.21.1 with mods and java 21
2 Launch
3 Crashes
```

### Expected Behavior

I expect the world to render

### Platform

```markdown
- Device model: Xiaomi Redmi note 12 pro 5g
- CPU architecture: aarch64(arm64)
- Android version: 14
- PojavLauncher version: foxglove-20240825-8dd34
c8-v3_openjdk
```

**Comment by CowSheep72** [comment]
remove sodium

**Comment by Algiuxs** [comment]
Is there a way to make sodium work, just curious.

**Comment by Algiuxs** [comment]
Removing sodium fixed the issue.
