### ISSUE TITLE
[BUG] <Short description> не заходила на сервер

### ISSUE THREAD

**Issue by Costea518** [PojavLauncherTeam/PojavLauncher#6004]
### Describe the bug

При входе на любой мультиплеер не работает не кокой сервер

### The log file and images/videos

![Screenshot_2024-08-30-12-29-44-867_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/bce3bbb9-1c8f-48fd-bd37-62b16da8b846)

### Steps To Reproduce

```markdown
1 запустите пожав
2 загрузите версию 1.7.10
Зайдите на любой сервер
```

### Expected Behavior

Што заидётся

### Platform

```markdown
- Device model: xiaomi note 10 pro
- CPU architecture: 8
- Android version: 13
- PojavLauncher version: new beta
```

### Anything else?

Почему так

**Comment by kasrarouhi** [comment]
Are you sure you enter the correct hostname because writes (can't resolve hostname)

**Comment by GaucovyAero** [comment]
most likely duplicate of #4479
