### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Ripmyself** [PojavLauncherTeam/PojavLauncher#6005]
### Describe the bug

When I log in into my account on pojavlauncher it keeps saying error can u fix this pls.

### The log file and images/videos

![Screenshot_20240830_180523_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/9273ec55-b33c-4722-8592-3814158dc583)

### Steps To Reproduce

```markdown
When I log in into my account it says error
```

### Expected Behavior

I expect pojavlauncher to work perfectly fine.

### Platform

```markdown
- Device model:Samsung 
- CPU architecture:idk
- Android version: yes
- PojavLauncher version:1.7.10
```

### Anything else?

Please fix this bug

**Comment by GaucovyAero** [comment]
follow the instructions
