### ISSUE TITLE
[BUG] 1.20.1 FABRIC TACZ ATTACHMENT CRASH

### ISSUE THREAD

**Issue by Average6fps** [PojavLauncherTeam/PojavLauncher#6010]
### Describe the bug

A bug/glitch that causes the game to crash when you hold a scope attachment in your hand

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16824471/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install 1.20.1 Fabric
2. Download and Install Timeless and Classics: Zero
3. Create/Join a world in creative mode
4. Pick a scope attachment from the inventory
5. Hold the scope attachment
```

### Expected Behavior

The scope attachment rendering and working correctly without crashing my game

### Platform

```markdown
- Device model: Galaxy A14 4/128G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240828-254a528-
```

**Comment by Vylesh** [comment]
@average

**Comment by Vylesh** [comment]
Can you send log @Average6fps and This can be caused by gun mod due they using never version of Shader technique in general

**Comment by Vylesh** [comment]
@Average6fps

**Comment by Vylesh** [comment]
@GaucovyAero İ'm Correct right ?

**Comment by sa1672ndo** [comment]
@Average6fps tacz uses opengl extensions that GL4ES doesn't support. You can either:
Select angle and pray it supports the extension.
Select zink and pray ur phones GPU supports zink.
Remove tacz and sodium (remove sodium because gl4es can't run that as well).
Start with the first option, and if that doesn't work, do the next one until 1 of the options work.

**Comment by Average6fps** [comment]
@sa1672ndo Oh,sorry for the late reply. I'll try angle and zink,if these two don't work then I'll play with the 1.19.2 version of the mod. Since the attachments on that version work but they're..I don't know how to explain it but they're "aim" textures render outside of the attachment itself. But I can bear with it.

**Comment by Average6fps** [comment]
@sa1672ndo oh and btw I'm using the "patched" version of sodium so it works

**Comment by Vylesh** [comment]
Remove Sodium... Pojavlauncher doesn't support sodium @Average6fps it can cause as well

**Comment by ghost** [comment]
Sodium is supposed for pojav depend on your gpu. but there is no gpu exist for Android support sodium. Plus sodium patcher I don't think work I try haste mod(sodium for pojav) but nothing changed like sodium not improve performance. Optifine is much better

**Comment by CowSheep72** [comment]
> Sodium is supposed for pojav depend on your gpu. but there is no gpu exist for Android support sodium. Plus sodium patcher I don't think work I try haste mod(sodium for pojav) but nothing changed like sodium not improve performance. Optifine is much better

haste is sketchy

**Comment by sa1672ndo** [comment]
> @sa1672ndo oh and btw I'm using the "patched" version of sodium so it works

You do know that patched sodium is worse than optifine in terms of performance?

**Comment by Average6fps** [comment]
> > @sa1672ndo oh and btw I'm using the "patched" version of sodium so it works
> 
> You do know that patched sodium is worse than optifine in terms of performance?

I get the same amount of performance on sodium as optifine idk why lol

**Comment by sa1672ndo** [comment]
> I get the same amount of performance on sodium as optifine idk why lol

Are you sure about it?

**Comment by CowSheep72** [comment]
> > I get the same amount of performance on sodium as optifine idk why lol
> 
> Are you sure about it?

well, sodium 0.4 and optifine have same fps with shaders on 1.18.2, but its shaders

**Comment by whal-whales** [comment]
> Sodium is supposed for pojav depend on your gpu.

no

**Comment by CowSheep72** [comment]
i think according to my usage

**Comment by CowSheep72** [comment]
with zink on edelweiss

**Comment by whal-whales** [comment]
> with zink on edelweiss

try gl4es and see how much worse it is

**Comment by Bel69420** [comment]
> Sodium is supposed for pojav depend on your gpu.

Can you stop being dumbass and stop spreading misinformation in pojav github?

**Comment by ghost** [comment]
> > Sodium is supposed for pojav depend on your gpu.
> 
> Can you stop being dumbass and stop spreading misinformation in pojav github?

Not my say
See
![IMG_20240901_152427](https://github.com/user-attachments/assets/04e6033c-227f-455f-892f-b27ef018e1fb)

**Comment by sa1672ndo** [comment]
> Not my say See ![IMG_20240901_152427](https://private-user-images.githubusercontent.com/140465266/363489313-04e6033c-227f-455f-892f-b27ef018e1fb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxOTIwNjAsIm5iZiI6MTcyNTE5MTc2MCwicGF0aCI6Ii8xNDA0NjUyNjYvMzYzNDg5MzEzLTA0ZTYwMzNjLTIyN2YtNDU1Zi04OTJmLWIyN2VmMDE4ZTFmYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxMTU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzYxYjZjNjdjNmJlZTc0MDM4YzU2YWQ2YTU0ZDczY2Y3MzZhOTgxZDlmY2UxODU1MzE0NWI4ZWRjNDA5YTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U_FvRENtaqpsDUVLk00SV2LcESLZzAZq1g93xQbo23M)

"Whether or not it is playable" nowhere is mentioned that sodium is supported. 
![Screenshot_20240901-145943_Firefox](https://github.com/user-attachments/assets/77952aff-3a6c-44e4-905f-69dcf9269e82)

**Comment by kasrarouhi** [comment]
In this document playable meaning supported

**Comment by Average6fps** [comment]
Did I just start a war about sodium or something

**Comment by sa1672ndo** [comment]
> I don't know for sure need to talk to khanhduytran0 I think playable mean support in some terms I'm not very good at english

"Playable" means that it can run at a decent perf. "supported" means that if theres any bugs when running sodium on pojav, sodium devs will fix it. Sodium DOES NOT SUPPORT pojav, even though u can still run it.

**Comment by ghost** [comment]
I agree. Sorry for bothering you i thinked playable mean support
