### ISSUE TITLE
Pojavlouncher please read this

### ISSUE THREAD

**Issue by Coryxkenshin-pixel** [PojavLauncherTeam/PojavLauncher#6012]
### Describe the bug

So I installed forge and I installed some mods but when I installed another mod when I pressed de start button it showed me this picture
![Screenshot_20240831_194619_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/416068f0-46a1-444b-b80c-d77cef0f1e4f)
I dont know if the picture works but it says something about code 1 search on youtube pojavlouncher code 1

### The log file and images/videos

![Screenshot_20240831_194619_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/3d8c15e5-f27e-4eb6-97dd-b0321d93ff1e)

### Steps To Reproduce

```markdown
So instal forge and then instal some mods I dont know how many mods because this already happen to me and sometimes it was different and the open forge and then it shows de code 1
```

### Expected Behavior

![Uploading Screenshot_20240831_194619_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Coryxkenshin-pixel** [comment]
Please fix this I love pojavlouncher

**Comment by ThatMG393** [comment]
Upload the log file.

We can't diagnose the issue without the log file.

**Comment by Coryxkenshin-pixel** [comment]
Ok I will it could take a little bit long because I uninstalled pojavlouncher but I do all what I did to get de log file

**Comment by Coryxkenshin-pixel** [comment]
Ok I will it could take a little bit long because I uninstalled pojavlouncher but I do all what I did to get de log file

**Comment by GaucovyAero** [comment]
you gotta click the share log file button

**Comment by asumy1** [comment]
@GaucovyAero check my problem pls

**Comment by asumy1** [comment]
@GaucovyAero the link is https://github.com/PojavLauncherTeam/PojavLauncher/issues/6025

**Comment by asumy1** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/6025

**Comment by GaucovyAero** [comment]
closing
