### ISSUE TITLE
[BUG] black screen

### ISSUE THREAD

**Issue by Fregsie** [PojavLauncherTeam/PojavLauncher#6013]
### Describe the bug

Whenever I start my pojav it loads but it's black screen

### The log file and images/videos

![Screenshot_2024-09-01-09-43-05-788_net kdt pojavlaunch zh](https://github.com/user-attachments/assets/1771123f-6df1-47b8-94b9-23a3135a7b1b)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.play
```

### Expected Behavior

I want to play Minecraft

### Platform

```markdown
- Device model: Redmi note 13 pro 
- CPU architecture: 
- Android version: 14
- PojavLauncher version: pojav zenith 1.2.7.1
```

**Comment by Fregsie** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16826970/latestlog.txt)
This is the log

**Comment by ThatMG393** [comment]
Try using other renderers or remove Xaero Minimap. 

Also seeing your log file, you're using Pojav Zenith Horizon. You need to report it to them because PojavLauncher is NOT Pojav Zenith Horizon.

**Comment by CowSheep72** [comment]
> Try using other renderers or remove Xaero Minimap.
> 
> Also seeing your log file, you're using Pojav Zenith Horizon. You need to report it to them because PojavLauncher is NOT Pojav Zenith Horizon.

how did you not realize earlier, it literally says on "platform"

**Comment by ThatMG393** [comment]
> > Try using other renderers or remove Xaero Minimap.
> > Also seeing your log file, you're using Pojav Zenith Horizon. You need to report it to them because PojavLauncher is NOT Pojav Zenith Horizon.
> 
> how did you not realize earlier, it literally says on "platform"

mb cuh, im not good of a reader tbh
