### ISSUE TITLE
[BUG] Game keeps saying not responding

### ISSUE THREAD

**Issue by idkwhattomakemynameonthissite** [PojavLauncherTeam/PojavLauncher#6016]
### Describe the bug

I downloaded Pojav for my Chromebook. Every time I play it, after around 5 minutes, it says Pojav isn’t responding. But, most of the time, that’s a total lie. And it keeps doing it every 5 seconds. I need help

### The log file and images/videos

https://github.com/user-attachments/assets/293d90bf-a760-4591-83f4-4e82ae184502

### Steps To Reproduce

```markdown
1. Start Pojav Launcher on Chromebook
2. Open Minecraft
3. Play, or wait, for 5 ish minutes, maybe longer or shorter.
4. The issue of “Pojav Launcher isn’t responding” every 5 seconds
```

### Expected Behavior

I expect to be able to play Minecraft without getting the pop up every time

### Platform

```markdown
- Device model: Lenovo Chromebook, bought in November 2023
- CPU architecture: idk
- Android version: ChromeOS
- PojavLauncher version: Latest Version
```

**Comment by GaucovyAero** [comment]
you are most likely just overloading your device resulting in parts of the pojav process hanging up, try decreasing settings and memory allocation in the launcher and i also suggest capping your fps
