### ISSUE TITLE
[BUG] Log stuck on beginning of system and game won't load.

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#6017]
### Describe the bug

i'm trying to play the fabulously optimized modpack and it gets stuck on "-----beginning of system" and it won't load.

### The log file and images/videos

[log.](https://github.com/user-attachments/files/16833411/latestlog.txt)

### Steps To Reproduce

```markdown
use fabulously optimized modpack and use "0.13.3 - 1.16.5"
```

### Expected Behavior

the game to load and my fps to go to like 6999999.

### Platform

```markdown
- Device model: TECHNO KG8
- CPU architecture: 64 bit.
- Android version: 11.
- PojavLauncher version: latest.
```

### Anything else?

nothing else i need the modpack because my fps goes to like 21 without it.

**Comment by GaucovyAero** [comment]
your fabric loader is too old, not a pojav issue

**Comment by Marcosayfi** [comment]
but it's what the modpack does!

**Comment by GaucovyAero** [comment]
change it manually then
