### ISSUE TITLE
[BUG] game crashes when using fabric mods

### ISSUE THREAD

**Issue by Deepak239487** [PojavLauncherTeam/PojavLauncher#6018]
### Describe the bug

whenever i try to use mods in fabric us crashes and shows me this:
![Screenshot_20240902_164911_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/efd40dc2-2a40-4699-bd1c-fcd01a67952e)
[latestlog.txt](https://github.com/user-attachments/files/16836751/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16836751/latestlog.txt)

### Steps To Reproduce

```markdown
what
```

### Expected Behavior

[Screenshot_20240902_164911_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/efd40dc2-2a40-4699-bd1c-fcd01a67952e)

### Platform

```markdown
- Device model: samsung m14/6gb/128 rom
- CPU architecture: exynos 1330, 64arm
- Android version: 14
- PojavLauncher version: latest
```

**Comment by rishabha102010** [comment]
Use the suited versions of mod or it will crashes and don't put the same mod twice in mod menu it will also crash and add fabric api which can stop crashing

**Comment by GaucovyAero** [comment]
dont cut your mods, copy your mods

**Comment by Deepak239487** [comment]
I tryed it by using suited mod,and didnt put it in twice
