### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by johnyt101154** [PojavLauncherTeam/PojavLauncher#602]
I can not type! Meaning i won't be able to chat or play on servers.
My device can handle 1.16.4 and its a samsung phone.

**Comment by khanhduytran0** [comment]
Use gboard

**Comment by khanhduytran0** [comment]
@johnyt101154

**Comment by Mathias-Boulay** [comment]
some keyboards just don't focus 👀 
Closing the issue since is a duplicate from others
