### ISSUE TITLE
[BUG] Game exited with code 1 when I use fabric

### ISSUE THREAD

**Issue by SahilDhiman1-pixel** [PojavLauncherTeam/PojavLauncher#6020]
### Describe the bug

![Screenshot_20240902_202345](https://github.com/user-attachments/assets/0434164e-f3ff-4df3-b330-0f26033f0839)
[latestlog.txt](https://github.com/user-attachments/files/16839057/latestlog.txt)

### The log file and images/videos

What

### Steps To Reproduce

```markdown
Yo
```

### Expected Behavior

Plz When I use fabric this happend

### Platform

```markdown
- Device model:
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
you are missing fabric libraries, not a pojav issue

**Comment by SahilDhiman1-pixel** [comment]
So what I have to do for solve this issue
