### ISSUE TITLE
Pojavlauncher launcher keeps crashing when I open inventory in stoneblock

### ISSUE THREAD

**Issue by MehulLahre** [PojavLauncherTeam/PojavLauncher#6021]
### Describe the bug

When I click inv button the game crashes and says application exited with code 1

### The log file and images/videos

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 9/2/24 9:15 PM
Description: 
CCL Has caught an exception whilst rendering an item.
  Item Class:     class com.brandon3055.draconicevolution.items.EnderEnergyManipulator
  Registry Name:  draconicevolution:ender_energy_manipulator
  Metadata:       0
  NBT:            null
  Model Class:    class net.minecraftforge.client.model.PerspectiveMapWrapper
  Model Location: draconicevolution:ender_energy_manipulator#inventory
You can turn off player messages in the CCL config file.
If you want CCL to attempt to recover the game next time, enable it in the CCL config.

java.lang.IllegalStateException: Unable to compile FRAGMENT shader object:
ERROR: 0:73: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:73: '-' :  wrong operand types  no operation '-' exists that takes a left-hand operand of type 'const int' and a right operand of type 'float' (or there is no acceptable conversion)
ERROR: 0:73: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:73: 'max' : no matching overloaded function found 
ERROR: 0:73: 'max' : no matching overloaded function found 
ERROR: 0:74: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:74: '+' :  wrong operand types  no operation '+' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:74: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:74: 'min' : no matching overloaded function found 
ERROR: 0:76: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'uniform float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:77: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'uniform float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:78: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:81: '=' :  cannot convert from 'const int' to 'float'
ERROR: 0:84: 'pow' : no matching overloaded function found 
ERROR: 0:85: 'max' : no matching overloaded function found 
ERROR: 0:89: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:91: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:93: '-' :  wrong operand types  no operation '-' exists that takes a left-hand operand of type 'const int' and a right operand of type 'float' (or there is no acceptable conversion)
ERROR: 0:93: 'max' : no matching overloaded function found 
ERROR: 19 compilation errors.  No code generated.

	at codechicken.lib.render.shader.ShaderObject.compileShader(ShaderObject.java:73)
	at java.lang.Iterable.forEach(Unknown Source)
	at codechicken.lib.render.shader.ShaderProgram.useShader(ShaderProgram.java:120)
	at com.brandon3055.draconicevolution.client.render.item.RenderItemEnderEnergyManipulator.renderItem(RenderItemEnderEnergyManipulator.java:62)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)
	at codechicken.lib.render.item.CCRenderItem.func_191962_a(CCRenderItem.java:270)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:337)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:30)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:23)
	at mezz.jei.render.IngredientRenderer.renderSlow(IngredientRenderer.java:69)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:189)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2895_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.lib.render.shader.ShaderObject.compileShader(ShaderObject.java:73)
	at java.lang.Iterable.forEach(Unknown Source)
	at codechicken.lib.render.shader.ShaderProgram.useShader(ShaderProgram.java:120)
	at com.brandon3055.draconicevolution.client.render.item.RenderItemEnderEnergyManipulator.renderItem(RenderItemEnderEnergyManipulator.java:62)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)

-- Item being rendered --
Details:
	Item Type: com.brandon3055.draconicevolution.items.EnderEnergyManipulator@37d9c8a2
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:188)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:343)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:30)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:23)
	at mezz.jei.render.IngredientRenderer.renderSlow(IngredientRenderer.java:69)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:189)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2895_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Ingredient being rendered --
Details:
	Mod Name: Draconic Evolution
	Registry Name: draconicevolution:ender_energy_manipulator
	Display Name: Ender Energy Manipulator
	String Name: 1xitem.draconicevolution:ender_energy_manipulator@0

-- JEI render details --
Details:
	Unique Id (for Blacklist): draconicevolution:ender_energy_manipulator
	Ingredient Type: class net.minecraft.item.ItemStack
	Error Info: 1xitem.draconicevolution:ender_energy_manipulator@0 draconicevolution:ender_energy_manipulator
	Filter Text: fro
	Edit Mode Enabled: false
	Debug Mode Enabled: false

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (64, 42). Absolute: (129, 514)
	Screen size: Scaled: (360, 300). Absolute: (720, 600). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['qwertyyhnrfv'/132, l='MpServer', x=-1009.54, y=90.00, z=-993.68]]
	Chunk stats: MultiplayerChunkCache: 40, 40
	Level seed: 0
	Level generator: ID 11 - voidworld, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,90,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 574821 game time, 574821 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntityPlayerSP['qwertyyhnrfv'/132, l='MpServer', x=-1009.54, y=90.00, z=-993.68], EntityLatchedRenderer['unknown'/134, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/135, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/136, l='MpServer', x=-999.59, y=90.00, z=-994.15], EntityHat['unknown'/137, l='MpServer', x=-1009.54, y=90.00, z=-993.68], EntityPigZombie['Zombie Pigman'/139, l='MpServer', x=-998.50, y=90.00, z=-1007.50]]
	Retry entities: 3 total; [EntityLatchedRenderer['unknown'/134, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/135, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/136, l='MpServer', x=-999.59, y=90.00, z=-994.15]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-14
	Java Version: 1.8.0_422-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1088955440 bytes (1038 MB) / 3299344384 bytes (3146 MB) up to 3299344384 bytes (3146 MB)
	JVM Flags: 3 total; -Xms3376M -Xmx3376M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 247 mods loaded, 247 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                   | Source                                              | Signature                                |
	|:------ |:--------------------------------- |:------------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                    | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                               | 9.42                      | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                               | 8.0.99.99                 | forge-1.12.2-14.23.5.2854.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2854              | forge-1.12.2-14.23.5.2854.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | openmodscore                      | 0.12.2                    | minecraft.jar                                       | None                                     |
	| LCHIJA | foamfixcore                       | 7.7.4                     | minecraft.jar                                       | None                                     |
	| LCHIJA | concheckrmd                       | 1.9.5                     | Modpack Configuration Checker-1.12.2-v1.9.5.jar     | None                                     |
	| LCHIJA | actuallyadditions                 | 1.12.2-r151               | ActuallyAdditions-1.12.2-r151-2.jar                 | None                                     |
	| LCHIJA | baubles                           | 1.5.2                     | Baubles-1.12-1.5.2.jar                              | None                                     |
	| LCHIJA | actuallybaubles                   | 1.1                       | ActuallyBaubles-1.12-1.1.jar                        | None                                     |
	| LCHIJA | ctm                               | MC1.12.2-1.0.2.31         | CTM-MC1.12.2-1.0.2.31.jar                           | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-7              | appliedenergistics2-rv6-stable-7.jar                | None                                     |
	| LCHIJA | bdlib                             | 1.14.3.12                 | bdlib-1.14.3.12-mc1.12.2.jar                        | None                                     |
	| LCHIJA | ae2stuff                          | 0.7.0.4                   | ae2stuff-0.7.0.4-mc1.12.2.jar                       | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76             | EnderCore-1.12.2-0.5.76.jar                         | None                                     |
	| LCHIJA | crafttweaker                      | 4.1.20                    | CraftTweaker2-1.12-4.1.20.574.jar                   | None                                     |
	| LCHIJA | mtlib                             | 3.0.6                     | MTLib-3.0.6.jar                                     | None                                     |
	| LCHIJA | modtweaker                        | 4.0.18                    | modtweaker-4.0.18.jar                               | None                                     |
	| LCHIJA | jei                               | 4.15.0.297                | jei_1.12.2-4.15.0.297.jar                           | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.3.358                 | CodeChickenLib-1.12.2-3.2.3.358-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.1                     | RedstoneFlux-1.12-2.1.1.1-universal.jar             | None                                     |
	| LCHIJA | cofhcore                          | 4.6.6                     | CoFHCore-1.12.2-4.6.6.1-universal.jar               | None                                     |
	| LCHIJA | brandonscore                      | 2.4.18                    | BrandonsCore-1.12.2-2.4.18.210-universal.jar        | None                                     |
	| LCHIJA | cofhworld                         | 1.4.0                     | CoFHWorld-1.12.2-1.4.0.1-universal.jar              | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.7                     | ThermalFoundation-1.12.2-2.6.7.1-universal.jar      | None                                     |
	| LCHIJA | draconicevolution                 | 2.3.25                    | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar  | None                                     |
	| LCHIJA | thermalexpansion                  | 5.5.7                     | ThermalExpansion-1.12.2-5.5.7.1-universal.jar       | None                                     |
	| LCHIJA | enderio                           | 5.1.55                    | EnderIO-1.12.2-5.1.55.jar                           | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                            | None                                     |
	| LCHIJA | projecte                          | 1.12.2-PE1.4.1            | ProjectE-1.12.2-PE1.4.1.jar                         | None                                     |
	| LCHIJA | chisel                            | MC1.12.2-1.0.2.45         | Chisel-MC1.12.2-1.0.2.45.jar                        | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.1.55                    | EnderIO-1.12.2-5.1.55.jar                           | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183         | TConstruct-1.12.2-2.13.0.183.jar                    | None                                     |
	| LCHIJA | tesla                             | 1.0.63                    | Tesla-1.12.2-1.0.63.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | p455w0rdslib                      | 2.3.161                   | p455w0rdslib-1.12.2-2.3.161.jar                     | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | ae2wtlib                          | 1.0.34                    | AE2WTLib-1.12.2-1.0.34.jar                          | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | extrautils2                       | 1.0                       | extrautils2-1.12-1.9.9.jar                          | None                                     |
	| LCHIJA | flyringbaublemod                  | 0.3.1_1.12-d4e654e        | angel

### Steps To Reproduce

```markdown
Click inv button
```

### Expected Behavior

To open inventory 

### Platform

```markdown
- Device model: Xiaomi pad 6 8gb ram
- CPU architecture: snapdragon 870
- Android version: 14
- pojavlauncher version - foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
custom shaders dont work a lot of the time, the ones in codechickenlib dont seem to work on gl4es

**Comment by MehulLahre** [comment]
But I cant remove this as it is required for other mods
