### ISSUE TITLE
[BUG] Immersive portals crashing when loading

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#6022]
### Describe the bug

i'm tryna use immersive portals, fabric api, sodium and modmenu but it just crashes. (1.16.5)

### The log file and images/videos

[log :D](https://github.com/user-attachments/files/16843362/latestlog.txt)

### Steps To Reproduce

```markdown
install sodium, fabric api, immersive portals and mod menu on fabric 1.16.5.
```

### Expected Behavior

the game to load snd i can enjoy my dream mod.

### Platform

```markdown
- Device model: TECHNO KG8.
- CPU architecture: 64-bit.
- Android version: 11.
- PojavLauncher version: latest.
```

### Anything else?

i read the log myself and at the end it said smth about the java version not me the latest. i'm not sure tho. this is all i know.

**Comment by Marcosayfi** [comment]
why do i always get spelling mistakes :/

**Comment by GaucovyAero** [comment]
it has some issue with your sodium installation, althougi immersive portals might not work on pojav due to the old opengl spec that gl4es has

**Comment by Marcosayfi** [comment]
then what renderer do i use?
