### ISSUE TITLE
[BUG] my game crash when something falls

### ISSUE THREAD

**Issue by LVEOUYO** [PojavLauncherTeam/PojavLauncher#6023]
### Describe the bug

I was playing in my world but when I was gonna turn my render in options in menu it crashes. Also when. A falling block falls it crashes my game. Sometimes also when I mine it crashes my pojav idk why.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16844132/latestlog.txt)

### Steps To Reproduce

```markdown
1. Join a world play a bit break a gravel it crash after another fall

2. When I open options in menu it crashes my game

3. When I mine sometimes it crashes my game
```

### Expected Behavior

I expect that it was normal and now it been happening every I cannot play properly (⁠╥⁠﹏⁠╥⁠)

### Platform

```markdown
- Device model: TECNO KI5k (KI5k-GL)
- CPU architecture: 2x ARM Cortex-A75 @ 1.61 GHz 6x ARM Cortex-A55 @ 1.61 GHz
- Android version: 12
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

That's it and I do not know how to put the log in new in GitHub I just watched a tut on how to creater a issue or a bug in YouTube ༎ຶ⁠‿⁠༎ຶ

**Comment by CowSheep72** [comment]
"[13:22:03] [Render thread/WARN]: Received passengers for unknown entity"
this may be related to your issue? idk

**Comment by hiimabignoobwihenolive** [comment]
Memory leak?

**Comment by LVEOUYO** [comment]
I don't even know haha that's why I reported it;-;

**Comment by GaucovyAero** [comment]
continuity most likely doesnt work on pojav
