### ISSUE TITLE
[BUG] <App constantly crashes>

### ISSUE THREAD

**Issue by StarKida** [PojavLauncherTeam/PojavLauncher#6026]
### Describe the bug

My Pojavlauncher 1.12 keeps crashing! I'm on version 1.12.2 forge (No optifine. ) 
Mods and recourse packs  :
Bibliocraft
Blockbuster
ChiselandBits
ConquestreforgedRP
Conquestreforgedmod
Decocraft
MCLib
Metamorph
PTRLib

I'm trying to join the game, but the app keeps crashing. 

### The log file and images/videos

https://drive.google.com/file/d/13M2C5guX2nEHK3ctaAysd9ZInFf47Jlq/view?usp=drivesdk

https://drive.google.com/file/d/13GFI2aJ-_nidpd2nBaijJBz-LcQLNFLb/view?usp=drivesdk

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

I expected it to let me join the game, without to many bugs or crashes.

### Platform

```markdown
- Device model: samsung tablet SM-X510
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Unknown Source)
	at java.lang.String.<init>(Unknown Source)
```

you are out of allocated memory
