### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Mukulalam06** [PojavLauncherTeam/PojavLauncher#6027]
### Is this request related to a bug?

how to play any modpack in pojav launcher

Please fix modpack crash 
Please fix MediaTek processor crash Zink
Please support add shaders MediaTek processor

### Describe the request.

how to play any modpack in pojav launcher

Please fix modpack crash 
Please fix MediaTek processor crash Zink
Please support add shaders MediaTek processor

### Anything else?

how to play any modpack in pojav launcher

Please fix modpack crash 
Please fix MediaTek processor crash Zink
Please support add shaders MediaTek processor

**Comment by GaucovyAero** [comment]
thats your phone being low-end and not supporting gpu features that zink requires
