### ISSUE TITLE
[BUG] Where are any of my mods?

### ISSUE THREAD

**Issue by StarKida** [PojavLauncherTeam/PojavLauncher#6028]
### Describe the bug

They don't appear. Yes I'm using mods that work for pojavlauncher,  yes I'm using forge, yes I'm using the right version. 

I put them into the mods folder, yet in game they don't appear.  I've tried leaving the app and going inqgqin, didn't work. I think this is an app issue because I have done everything right in the tutorials.  

The only things that appear are the recourse packs. 

### The log file and images/videos

![Screenshot_20240904_083609_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/87c5d808-eb0d-4898-9022-6abe663707f1)
![Screenshot_20240904_083547_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/b4e64c93-5c77-48d9-9dc6-9ccd334707dc)
![Screenshot_20240904_083146_ZArchiver](https://github.com/user-attachments/assets/f83de276-c04e-408b-92c0-52304cdce3c8)
![Screenshot_20240904_083131_ZArchiver](https://github.com/user-attachments/assets/6b5f1907-3fb4-4ef9-9499-3fbb6115dcb5)

### Steps To Reproduce

```markdown
Tried everything to be real.
```

### Expected Behavior

I expected my mods to be loaded in correctly and working.

### Platform

```markdown
- Device model: Device model: samsung tablet SM-X510
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by gabriel-mauricioo** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by StarKida** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

Thanks, do I put it in the mods / recourse packs folder?

**Comment by GaucovyAero** [comment]
send log

**Comment by StarKida** [comment]
> send log

It doesn't give me a log. The mods just don't show up

**Comment by GaucovyAero** [comment]
> > send log
> 
> It doesn't give me a log. The mods just don't show up

just click the share log file button

![image](https://github.com/user-attachments/assets/64625219-329c-4e9a-b97d-dff8bcac4101)
