### ISSUE TITLE
[BUG] <mods says is not a jar file>

### ISSUE THREAD

**Issue by Fullvampz** [PojavLauncherTeam/PojavLauncher#6036]
### Describe the bug

I dowlanding mods form curseforge, modrinth, 9minecraft and some mods sayng is not a jar file idk why and i see 1.16.5 and 1.12.2 itested and is same on fabric idk i used only 1.20.1, 1.20.4, 1.20.6, 1.21

### The log file and images/videos

![Screenshot_20240907_134141_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/d4930538-70c3-48d2-8cb5-4f415a92f9dd)

[latestlog.txt](https://github.com/user-attachments/files/16917691/latestlog.txt)

### Steps To Reproduce

```markdown
Put the mods in mods folder
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: SM- samsung galaxy a03
- CPU architecture: Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55)
- Android version: 13
- PojavLauncher version: foxglove-20240905-8c90b54-v3_openjdk
```

### Anything else?

Only thath

**Comment by GaucovyAero** [comment]
permission denied, you have to copy the mods, not cut

**Comment by XDJAMES678** [comment]
> permission denied, you have to copy the mods, not cut

is this real??

**Comment by XDJAMES678** [comment]
> permission denied, you have to copy the mods, not cut

THANK YOU BRO!!!!!!
