### ISSUE TITLE
[Question] Runtime directory

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#6037]
### Is this request related to a bug?

no.

### Describe the request.

i wanna no where the runtime is so i can install app-debug no runtime and then copy and paste the runtime without having to download 50 mb that i already have downloaded.

### Anything else?

nah.

**Comment by GaucovyAero** [comment]
use the runtime manager inside pojav
in case you wanna know where it is, its inside root 
/data/data/net.kdt.pojavlaunch.debug/runtimes
