### ISSUE TITLE
minecraft forge 1.12.2, exited with code 1

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6038]
### Describe the bug

I wanted to play with some mods in version 1.12.2
so I created a forge profile in 1.12.2 but when launched with or without mods it doesn't work and appears the message "game exited with code 1"

I used java 1.8 and rederer: Holy gl4es(also tried zink(vulkan) also didn't work)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16918566/latestlog.txt)

### Steps To Reproduce

```markdown
1- create a forge profile 1.12.2
2- lauch the game
```

### Expected Behavior

for it to launch without this bug ;>;

### Platform

```markdown
- Device model: Samsung Galaxy M53 5G
- CPU architecture: 6x ARM Cortex-A55 @ 2000 MHz
2x ARM Cortex-A78 @ 2400 MHz
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment]
you cant play 1.7.10 mods on 1.12.2

**Comment by ghost** [comment]
oh thanks for the help!!
I thought since I could launch other versions with no problem, that it would ignore the 1.7 mods and just read the 1.12 ones
my badd!!

**Comment by GaucovyAero** [comment]
most of the time you can figure out the issue just by reading the log, if you need more versions use custom directories, note that stuff might error out on older mc versions when using custom directories
