### ISSUE TITLE
[F-REQ] Skin UI

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#604]
Add skin UI

**Comment by artdeell** [comment]
why do you need a skin ui in the launcher?
just use [minecraft.com profile editor](https://www.minecraft.net/en-us/profile) to change skin
if you are offline, well... you should buy the game.

**Comment by LANCECRAFT1104** [comment]
I cant add my skin in the game

**Comment by artdeell** [comment]
java is not bedrock - if you didn't buy the game, you have to mod the game to add skins

**Comment by LANCECRAFT1104** [comment]
> java is not bedrock - if you didn't buy the game, you have to mod the game to add skins

What mod can you give me link

**Comment by khanhduytran0** [comment]
Isn't Google a place to search everything? Go to and find.

**Comment by LANCECRAFT1104** [comment]
> Isn't Google a place to search everything? Go to and find.

I can't find!
I search Skin UI Mod for Java Edition and the results is https://www.google.com/search?q=Skin+UI+Mod+for+Java+Edition&oq=Skin+UI+Mod+for+Java+Edition&aqs=chrome..69i57.7186j0j7&client=ms-android-oppo&sourceid=chrome-mobile&ie=UTF-8

**Comment by khanhduytran0** [comment]
Duplicate #503
