### ISSUE TITLE
[BUG] World crash

### ISSUE THREAD

**Issue by Fregsie** [PojavLauncherTeam/PojavLauncher#6041]
### Describe the bug

If I open up a world with sodium my world crashes when it generates 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16920682/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.open pojavlauncher
3.start a world
```

### Expected Behavior

I expect that my Minecraft will run fine

### Platform

```markdown
- Device model: Redmi note 13 pro 5g
- CPU architecture: 
- Android version: 14
- PojavLauncher version: foxglove-20240905-8c90 b54-v3_openjdk
```

### Anything else?

I play without sodium is fine but I want more fps

**Comment by Fregsie** [comment]
Opening the game is fine but when I load the world that's where it crashes

**Comment by GaucovyAero** [comment]
delete sodium and all related mods, it doesnt work on 1.21.1 on pojav with gl4es
