### ISSUE TITLE
[BUG] <Can't run 1.5.2>

### ISSUE THREAD

**Issue by Faked4040** [PojavLauncherTeam/PojavLauncher#6042]
### Describe the bug

vanilla version 1.5.2 does not work, set jre8, renderer Gl4ES. But still does not start.
the launch stops when the Mojang logo appears, after that absolutely nothing happens, waited more than 5 minutes

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16921126/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start 1.5.2 vanilla
2. Nothing
```

### Expected Behavior

No

### Platform

```markdown
- Device model: samsung s10
- CPU architecture: Ex9820
- Android version: 12
- PojavLauncher version: latest foxglove
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
disable the shader dump (it does nothing) and delete options.txt

**Comment by Faked4040** [comment]
> отключите дамп шейдера (он ничего не делает) и удалите options.txt

Thank you! It is working
