### ISSUE TITLE
[BUG] <CANT RUN OPTIFABRIC IN 1.21>

### ISSUE THREAD

**Issue by MrDiamondPlayz** [PojavLauncherTeam/PojavLauncher#6043]
### Describe the bug

I can't run optifabric in 1.21 I don't like fake sodium so that's why I use optifabric but it's not working on 1.21 and when j start it crashed give any solution 

### The log file and images/videos

[latest.log](content://com.whatsapp.provider.media/item/6ddc590c-d1fa-430d-91a3-7a662b0bb794)

### Steps To Reproduce

```markdown
1. Download optifabric and optifine for 1.21
2. Add it to pojav
3. Start pojavlauncher 
4. Launch game
5. Game crashed after some seconds
```

### Expected Behavior

Optifabric not working

### Platform

```markdown
- Device model: samsung m33 5g 8/128
- CPU architecture: octa-core processor
- Android version: 14
- PojavLauncher version: foxglove-20240905-
8c90b54-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
not a pojav issue, last ver of optifabric is for 1.20.4

**Comment by MrDiamondPlayz** [comment]
> not a pojav issue, last ver of optifabric is for 1.20.4

But it's available on modrinth
