### ISSUE TITLE
[BUG] <Short description>game exited with code-1 

### ISSUE THREAD

**Issue by CHOPDAHEADYT** [PojavLauncherTeam/PojavLauncher#6044]
Describe game exited with code- 1
[crash-2024-09-08_16.12.25-client.txt](https://github.com/user-attachments/files/16922829/crash-2024-09-08_16.12.25-client.txt)
![Screenshot_20240908_213735_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/b6736aef-b3ff-40b7-8232-96380b54b035)
Latest  @GaucovyAero 
[latestlog.txt](https://github.com/user-attachments/files/16945772/latestlog.txt)

### Steps To Reproduce

```markdown
1 put mods in folder
2 open pojav forge
3 get error game exited with code -1
```

### Expected Behavior

I need a solution pls

### Platform

```markdown
- Device model: Galaxy Tablet s6 lite
- CPU architecture: 64
- Android version: 13
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
latest is not a version, send latestlog.txt

**Comment by CHOPDAHEADYT** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16945766/latestlog.txt)

**Comment by GaucovyAero** [comment]
# How to make OneConfig work on PojavLauncher with minimal lag 
### Thanks to JellyLab and littleone24_ for bringing this option to our attention and Wyvest for even attempting to support us in the first place

Requirements: 
    At least on PojavLauncher Edelweisse/Playstore Release
    (Optional) Device is capable of using Zink (Note: this hasn't been tested on iOS yet, someone please test it)

* Launch OneConfig or mod using OneConfig. __***It will crash on first time launch, that's okay.***__
* Set `updatechannel` to 1 in `.minecraft/OneConfig/OneConfig.json` and `.minecraft/OneConfig/Preferences.json`
* Set `enableBlur` to 0 in `.minecraft/OneConfig/Preferences.json` (Optionally, disable all animations as well)
* Use Zink renderer (or HolyGL4ES)
* Set Optifine Antialiasing to Off in Video Settings (Only if using Optifine)

**Known Bugs**
* Scroll bar is misaligned slightly to the right of the actual GUI

__***Important***__
Mods that use OneConfig will work on HolyGL4ES. But you cannot open the OneConfig menu or else it will crash. If you have a startup crash, just go to another app while Minecraft loads in.
__***Important***__

**Comment by CHOPDAHEADYT** [comment]
What is onecinfig where to update  channel
