### ISSUE TITLE
[BUG] 1.12 Wurst OF crashing

### ISSUE THREAD

**Issue by Zack694** [PojavLauncherTeam/PojavLauncher#6045]
### Describe the bug

Exit - 1 code

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16930435/latestlog.txt)

### Steps To Reproduce

```markdown
1.Open PojavLauncher
2.Play 1.12 Wurst OF
3. Wait 1 second then crash
```

### Expected Behavior

In my other phone it works (doesn't has the latest pojav version)
In this phone it doesn't work ( has the latest pojav version)

### Platform

```markdown
- Device model: vivo 1906
- CPU architecture: Snapdragon
- Android version: 11
- PojavLauncher version: Latest
```

**Comment by GaucovyAero** [comment]
no errors there, cant really help with this
