### ISSUE TITLE
[F-Req] <Custom Panel Keyboard>

### ISSUE THREAD

**Issue by LutraVibes** [PojavLauncherTeam/PojavLauncher#6049]
### Is this request related to a bug?

The OS keyboard covers the chat box on servers.

### Describe the request.

Create a custom application keyboard that can be moved across the screen as a panel (for chat, world naming, etc.) since OS keyboard covers chat.

### Anything else?

With a moveable panel keyboard, users can move it to a desired location that best fits for them, and perhaps can pin it and resize it for better interaction.

**Comment by khanhduytran0** [comment]
Many keyboards have already offered floating keyboard feature. It should be what you need.

**Comment by GaucovyAero** [comment]
Gboard, SwiftKey and Samsung Keyboard already have the feature, though there does not seem to be any open source one that supports it unfortunately
closing as this is not a pojav issue

**Comment by ghost** [comment]
Gboard is really good in anyway

**Comment by LutraVibes** [comment]
> Gboard, SwiftKey and Samsung Keyboard already have the feature, though there does not seem to be any open source one that supports it unfortunately closing as this is not a pojav issue

This is why I suggested it. The keyboard doc still covers up chat in GBoard.
![Screenshot_20240910-093839_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/user-attachments/assets/b511a4dd-59a4-47e1-9af7-d635559e3301)

**Comment by LutraVibes** [comment]
> Gboard is really good in anyway

It simply isn't. It covers up chat in floating mode as well.
