### ISSUE TITLE
[F-REQ] Add disable funtion for place block/destroy block everytime tap on the screen

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#605]
If you guys can.. Then pls add that funtion. Because I am always got like accidently destroy some block or put some block and also in minecraft 1.12... everytime I use open inventory, crafting table, furnace, chat or anything that mouse appear... My screen will always from looking at downside to upside really fast and also it will auto tap... so the block will ne place automatically and I need to remove the block back... It was really annoying.. So pls.. add that disable function for that.. Thanks

**Comment by khanhduytran0** [comment]
Known issue

**Comment by Mathias-Boulay** [comment]
This enhancement has now been added to mainline.
Closing the issue.
