### ISSUE TITLE
Feat: SPECIAL_MENU should appear when the back button is pressed in-game

### ISSUE THREAD

**Issue by GaucovyAero** [PojavLauncherTeam/PojavLauncher#6050]
### Is this request related to a bug?

no

### Describe the request.

SPECIAL_MENU should appear when the back button is pressed in-game, Winlator has it like this and it seems pretty convenient

### Anything else?

No.

**Comment by TylerHaoNhot** [comment]
There will be people who use the back button on their phone as the esc button in games, so adding this feature is no different than a bug for them.
or in some users physical keyboard connected to their Android device, when pressing esc key it is recognized as back key, inferring that it will open that menu
and also, there's already a key that you could set in your gui which also do the same job as this feature.

**Comment by GaucovyAero** [comment]
okay, closing then
