### ISSUE TITLE
Pojavloumcher code 1 bug

### ISSUE THREAD

**Issue by Cory939** [PojavLauncherTeam/PojavLauncher#6052]
### Describe the bug

So a I installed forge and installed some mods sometimes its less or more mods so when I enter to the forge it appears a code 1 thing 
![Screenshot_20240909_181227_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/c9f86505-f96f-4e21-9daa-4e724064ba1e)
Heres a picture

### The log file and images/videos

![Screenshot_20240909_181227_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/bb08f569-f5df-43a0-8b9d-da78689be2be)
[latestlog.txt](https://github.com/user-attachments/files/16937499/latestlog.txt)
Heres de log file I think, someone else told me that you needed this log file

### Steps To Reproduce

```markdown
So install forge it can be on every version then install some mods untill it appears a code 1 thing.
```

### Expected Behavior

I would like for you to fix it please.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No thats it.

**Comment by GaucovyAero** [comment]
crash the game and send the log again (the log you uploaded is from the jar installer, not from crashing the game)

**Comment by Cory939** [comment]
Im so sorry but I dont know how to send de log of de crashing game sorry

**Comment by GaucovyAero** [comment]
> Im so sorry but I dont know how to send de log of de crashing game sorry

upload files - 3 lines top left - PojavLauncher - latestlog.txt

**Comment by Cory939** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16971214/latestlog.txt)

**Comment by Cory939** [comment]
Tell me if its that one

**Comment by GaucovyAero** [comment]
your mods say access denied, you have to copy them and not cut them

**Comment by Cory939** [comment]
Thank you very much 🙃
