### ISSUE TITLE
[BUG] Keyboard Covers up Chat

### ISSUE THREAD

**Issue by LutraVibes** [PojavLauncherTeam/PojavLauncher#6053]
### Describe the bug

My OSs keyboard (GBoard) covers up chat, in both normal docked mode and floating mode.

My suggested solution to this problem is to instead of overlaying the keyboard over the app, just simply move up the app (a little bit for floating mode, a lot for normal docked mode) to make room for the keyboard, so chat isn't covered up.

### The log file and images/videos

![Screenshot_20240910-093839_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/user-attachments/assets/7964fcfa-102e-4dfc-9189-18d7dba37ea9)

### Steps To Reproduce

```markdown
1. Open PojavLauncher and run Minecraft
2. Open a world or server
3. Open chat and open keyboard
```

### Expected Behavior

I expect my keyboard to not cover up chat.

### Platform

```markdown
- Device model: Motorola Razr 2023
- CPU architecture: ARM
- Android version: 14
- PojavLauncher version: Latest (foxglove-20240905-8c90b54-v3_openjdk)
```

**Comment by GaucovyAero** [comment]
i created #6054 for this
