### ISSUE TITLE
Shift the game window when opening the system keyboard to see chat

### ISSUE THREAD

**Issue by GaucovyAero** [PojavLauncherTeam/PojavLauncher#6054]
### Is this request related to a bug?

Nope.

### Describe the request.

Shift the game window when opening the system keyboard to see what I'm typing in chat. Not everybody has a keyboard that supports Floating mode and also it might not work as expected sometimes, covering the chat anyway.

### Anything else?

Nope.

**Comment by Mathias-Boulay** [comment]
Now, you can't see when you type a server ip...

**Comment by Felix14-v2** [comment]
Isn't this a duplicate of https://github.com/PojavLauncherTeam/PojavLauncher/issues/4627?

**Comment by GaucovyAero** [comment]
it is, closing
