### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Ronaldo-desing-g** [PojavLauncherTeam/PojavLauncher#6055]
### Describe the bug

Fala que eu não loguei no Xbox live sendo que eu nem tenho e eu já tenho umas 4 contas da Microsoft e fala sempre que dá incorreta 

### The log file and images/videos

Não tá dando pra logar o pojavlauncher

### Steps To Reproduce

```markdown
Start pojavlauncher
```

### Expected Behavior

Eu irei ficar feliz se o problema for resolvido

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
you have to buy minecraft java edition just like on PC
