### ISSUE TITLE
[F-Req] update the lwjgl version to 3.3.3

### ISSUE THREAD

**Issue by Keanpojavlauncher** [PojavLauncherTeam/PojavLauncher#6056]
### Is this request related to a bug?

Sodium (patched) 5.11 is not compatible with lwjgl version 3.3.1

### Describe the request.

Just update the lwjgl version and who knows it might provide a fps boost

### Anything else?

Nothing

**Comment by Mathias-Boulay** [comment]
If my memory serves me right, we do ship 3.3.3 on the current mainline version

**Comment by GaucovyAero** [comment]
its the other way around and we are not going to downgrade
