### ISSUE TITLE
1.8.9 Optifine keyboard makes exit full screen.

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#6057]
### Describe the bug

when i play 1.8.9 i press shift + w (and some other random combination) it will exit full screen mode.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16962152/latestlog.txt)

video:

https://github.com/user-attachments/assets/7540216c-9203-4183-91cb-36ce8f1200e3

### Steps To Reproduce

```markdown
1 join 1.8.9 optifine.
2 bug happen when i press shift + w on my keyboard.
```

### Expected Behavior

fix the proplem, no longer exiting fullscreen when pressing buttons.

### Platform

```markdown
- Device model: this bug happened on all devices i had (google pixel 3; yuho tab 10; redmi k20 pro)
- CPU architecture: all arm64
- Android version: 11 asop, 11 miui rom and 12 asop
- PojavLauncher version: foxglove 20240905
```

**Comment by GaucovyAero** [comment]
bind fullscreen to f12 or some other key that cannot be pressed with this or similar shortcut

**Comment by GaucovyAero** [comment]
this is a hardcoded android shortcut and cannot be fixed
