### ISSUE TITLE
[BUG] Voxel map 1.7.10 crash

### ISSUE THREAD

**Issue by Xiaomo305Mua** [PojavLauncherTeam/PojavLauncher#6060]
### Describe the bug

VoxelMap Mod is suddenly unusable at the start of a certain version of Pojav Launcher, this is an excellent map mod, I hope you guys will fix this bug, Xaero's Minimap and JourneyMap have some weird rendering bugs in version 1.7.10-1.12.2, I don't understand why, but VoxelMap doesn't seem to have this problem, I provide latestlog

### The log file and images/videos

[Uploading latestlog.txt…]

### Steps To Reproduce

```markdown
After installing the mod, the game crashes
```

### Expected Behavior

Able to get this mod to work

### Platform

```markdown
- Device model: HONOR 20 PRO
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: foxglove-20240909-366f181-v3_openjdk
```

**Comment by Xiaomo305Mua** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16970079/latestlog.txt)
Sorry the latestlog was posted before it was uploaded, the latestlog is here.

**Comment by GaucovyAero** [comment]
if the app just crashes when joining the world, you have to do an `adb bugreport`, if you did not understand how to do it from the internet after trying it multiple times, try asking here

if you have the bugreport zip file, just send it here (basically crash the game, then do `adb bugreport`)

**Comment by Xiaomo305Mua** [comment]
> if the app just crashes when joining the world, you have to do an `adb bugreport`, if you did not understand how to do it from the internet after trying it multiple times, try asking here
> 
> if you have the bugreport zip file, just send it here (basically crash the game, then do `adb bugreport`)

The game won't start and will crash when loaded into the "Mojang" interface, which worked fine with previous versions of Pojav Launcher

**Comment by Xiaomo305Mua** [comment]
> if the app just crashes when joining the world, you have to do an `adb bugreport`, if you did not understand how to do it from the internet after trying it multiple times, try asking here
> 
> if you have the bugreport zip file, just send it here (basically crash the game, then do `adb bugreport`)

Only latest.log and latestlog.txt

**Comment by Xiaomo305Mua** [comment]
> if the app just crashes when joining the world, you have to do an `adb bugreport`, if you did not understand how to do it from the internet after trying it multiple times, try asking here
> 
> if you have the bugreport zip file, just send it here (basically crash the game, then do `adb bugreport`)

I don't have a computer to adb,But it seems that it is the problem of lwjgl3 that makes VoxelMap Mod unusable, and Pojav Glow Worm can use VoxelMap Mod.

**Comment by Xiaomo305Mua** [comment]
> if the app just crashes when joining the world, you have to do an `adb bugreport`, if you did not understand how to do it from the internet after trying it multiple times, try asking here
> 
> if you have the bugreport zip file, just send it here (basically crash the game, then do `adb bugreport`)

Anyway, I can't execute adb,If I had a computer, I wouldn't use my phone to run the Minecraft Java Edition,The problem of this Mod is also very simple to trigger, as long as this Mod is installed to start the game, it will crash, even the main menu of the game can not be entered, in the previous version of Pojav Launcher can use this Mod, so I think this BUG is necessary to fix, Pojav Launcher is constantly improving. However, the progress has also led to the sudden unavailability or rendering errors of some Mods, such as Phosphor and Dynamic Surroundings.

**Comment by CowSheep72** [comment]
> > if the app just crashes when joining the world, you have to do an `adb bugreport`, if you did not understand how to do it from the internet after trying it multiple times, try asking here
> > if you have the bugreport zip file, just send it here (basically crash the game, then do `adb bugreport`)
> 
> Anyway, I can't execute adb,If I had a computer, I wouldn't use my phone to run the Minecraft Java Edition,The problem of this Mod is also very simple to trigger, as long as this Mod is installed to start the game, it will crash, even the main menu of the game can not be entered, in the previous version of Pojav Launcher can use this Mod, so I think this BUG is necessary to fix, Pojav Launcher is constantly improving. However, the progress has also led to the sudden unavailability or rendering errors of some Mods, such as Phosphor and Dynamic Surroundings.

termux

**Comment by CowSheep72** [comment]
you can use termux to do adb with wireless debugging

**Comment by aaaapai** [comment]
> you can use termux to do adb with wireless debugging

I found that it does have something to do with lwjgl
[logcat-lwjgl3.3.1.txt](https://github.com/user-attachments/files/16977184/logcat-lwjgl3.3.1.txt)
[logcat-lwjgl3.3.3.txt](https://github.com/user-attachments/files/16977185/logcat-lwjgl3.3.3.txt)
lwjgl3.3.1 can go in, but lwjgl3.3.3 can't
`00000000001cf1c8  /data/app/net.kdt.pojavlaunch.firefly-ZIrD_z1cnn7xsib-LYtpKw==/lib/arm64/libgl4es_114.so (glGenFramebuffers+268) (BuildId: 7355ce8a7d0664b98e87814add15ec7a7ea7fd03)`

**Comment by GaucovyAero** [comment]
> I don't have a computer to adb,But it seems that it is the problem of lwjgl3 that makes VoxelMap Mod unusable, and Pojav Glow Worm can use VoxelMap Mod.

i suggest doing it with shizuku + ashell you, or maybe termux but i guess thats a tad more difficult

**Comment by Xiaomo305Mua** [comment]
> > I don't have a computer to adb,But it seems that it is the problem of lwjgl3 that makes VoxelMap Mod unusable, and Pojav Glow Worm can use VoxelMap Mod.
> 
> i suggest doing it with shizuku + ashell you, or maybe termux but i guess thats a tad more difficult

Uh, this is a little difficult for me, so is the information provided by the person upstairs helpful?

**Comment by Xiaomo305Mua** [comment]
> > I don't have a computer to adb,But it seems that it is the problem of lwjgl3 that makes VoxelMap Mod unusable, and Pojav Glow Worm can use VoxelMap Mod.
> 
> i suggest doing it with shizuku + ashell you, or maybe termux but i guess thats a tad more difficult

Does aaaapai seem to provide what you need?

**Comment by GaucovyAero** [comment]
> Does aaaapai seem to provide what you need?

no, i basically need the tombstone file, which is only located in the bugreport

**Comment by Xiaomo305Mua** [comment]
> > Does aaaapai seem to provide what you need?
> 
> no, i basically need the tombstone file, which is only located in the bugreport

Can you tell me how to get this file? Other Launchers seem to have termux built-in, but I have a 0 base for this thing, and I don't know how to operate it.

**Comment by GaucovyAero** [comment]
use shizuku + ashell you, crash the game and put in adb bugreport inside ashell you

**Comment by Xiaomo305Mua** [comment]
> use shizuku + ashell you, crash the game and put in adb bugreport inside ashell you

Uh, I'm sorry, I don't understand..

**Comment by Xiaomo305Mua** [comment]
> use shizuku + ashell you, crash the game and put in adb bugreport inside ashell you

**Comment by Xiaomo305Mua** [comment]
> use shizuku + ashell you, crash the game and put in adb bugreport inside ashell you

My device can't get ROOT permission, and there is no other way to activate shizuku except using a computer.

**Comment by Xiaomo305Mua** [comment]
> use shizuku + ashell you, crash the game and put in adb bugreport inside ashell you

Let me ask you a question. Do you have time to get this thing by yourself? In this way, the problem can be solved quickly. It's better than spending time with me here. I don't understand the way you said to get it. Sorry.

**Comment by Xiaomo305Mua** [comment]
> use shizuku + ashell you, crash the game and put in adb bugreport inside ashell you

Is this what you want? I asked my friend for help.
[bugreport-mondrian-UKQ1.230804.001-2024-09-16-20-49-36.zip](https://github.com/user-attachments/files/17013490/bugreport-mondrian-UKQ1.230804.001-2024-09-16-20-49-36.zip)

**Comment by Xiaomo305Mua** [comment]
> use shizuku + ashell you, crash the game and put in adb bugreport inside ashell you

One Launcher author said there was a problem with the OpenGL section.

**Comment by GaucovyAero** [comment]
[tombstone_17.txt](https://github.com/user-attachments/files/17034376/tombstone_17.txt)
[latestlog-zink-works.txt](https://github.com/user-attachments/files/17034377/latestlog-zink-works.txt)
[latestlog-gl4es-doesnt.txt](https://github.com/user-attachments/files/17034379/latestlog-gl4es-doesnt.txt)

**Comment by Xiaomo305Mua** [comment]
> [tombstone_17.txt](https://github.com/user-attachments/files/17034376/tombstone_17.txt) [latestlog-zink-works.txt](https://github.com/user-attachments/files/17034377/latestlog-zink-works.txt) [latestlog-gl4es-doesnt.txt](https://github.com/user-attachments/files/17034379/latestlog-gl4es-doesnt.txt)

Thank you for your hard work.

**Comment by GaucovyAero** [comment]
closing, because the cause cant be easily determined, it most likely is that gl4es is missing some new opengl feature and we can't really do much about it, might be fixed in the future if new gl features are gonna be added
