### ISSUE TITLE
[BUG] <black screen>

### ISSUE THREAD

**Issue by GALOB17** [PojavLauncherTeam/PojavLauncher#6062]
### Describe the bug

Everytime when my game is on whenever I open some apps like discord yt etc so after using them when I return to my game it gets Black screen I tried to remove it but I can't because of this I have to use old pojav which I don't want so please fix this issue as soon as possible thank you!!

### The log file and images/videos

I cant

### Steps To Reproduce

```markdown
1 open your game 
2 click on the middle button of your phone and use any app for some time
3 open your game again and there you will have black screen
```

### Expected Behavior

I expect that whenever I open my game it doesn't have black screens

### Platform

```markdown
- Device model: oppo a15
- CPU architecture: octa core 
- Android version: 10
- PojavLauncher version:latest
```

**Comment by ThatMG393** [comment]
wdym "I can't" 😭❓️

try turning off "Alternate Surface Rendering" in Settings > Video and Renderer

upload the log file or we will not help.

**Comment by GaucovyAero** [comment]
and be sure to not use angle
