### ISSUE TITLE
Embedium mod crash the game

### ISSUE THREAD

**Issue by Renerosal01234** [PojavLauncherTeam/PojavLauncher#6063]
### Describe the bug

Embedium mod crash game when create world like sodium mod 1.21.1

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16990601/latestlog.txt)

### Steps To Reproduce

```markdown
1. Pojavlauncher start
2. Create world 
3. Crash game
```

### Expected Behavior

Embedium mod work 

### Platform

```markdown
- Device model: Poco c65 
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: latest update on GitHub
```

### Anything else?

Plss help I want to play Modpacks but it's lagging without embedium mod for neoforge

**Comment by GaucovyAero** [comment]
this seems to be a mod conflict, tho keep in mind than embeddium only works on zink

**Comment by Renerosal01234** [comment]
> this seems to be a mod conflict, tho keep in mind than embeddium only works on zink

Where do I get java 21 runtime latest?

**Comment by ghost** [comment]
It's already exist in latest pojav play store version

**Comment by Renerosal01234** [comment]
> It's already exist in latest pojav play store version

Yeah I thinking to try on old zink because zink on Google play store are not working on mali

**Comment by GaucovyAero** [comment]
> Yeah I thinking to try on old zink because zink on Google play store are not working on mali

try this

*/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt*

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```

**Comment by Renerosal01234** [comment]
> > Yeah I thinking to try on old zink because zink on Google play store are not working on mali
> 
> try this
> 
> _/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt_
> 
> ```
> MESA_GL_VERSION_OVERRIDE=4.6
> MESA_GLSL_VERSION_OVERRIDE=460
> ```

On Pojavlauncher from Google play store?

**Comment by Renerosal01234** [comment]
> > > Yeah I thinking to try on old zink because zink on Google play store are not working on mali
> > 
> > 
> > try this
> > _/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt_
> > ```
> > MESA_GL_VERSION_OVERRIDE=4.6
> > MESA_GLSL_VERSION_OVERRIDE=460
> > ```
> 
> On Pojavlauncher from Google play store?

![Screenshot_2024-09-13-20-44-08-610_com google android documentsui](https://github.com/user-attachments/assets/03dc5a7e-e5c8-409e-83a3-42faa6f40f5f)

No costum envtxt here

**Comment by GaucovyAero** [comment]
you gotta create it

**Comment by Renerosal01234** [comment]
> you gotta create it

Not working 😞

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by Renerosal01234** [comment]
Video 
https://github.com/user-attachments/assets/de31b52f-072b-4632-b2e6-92ccdac9f258

[latestlog.txt](https://github.com/user-attachments/files/17001361/latestlog.txt)

**Comment by Renerosal01234** [comment]
> send latestlog.txt

Video 

https://github.com/user-attachments/assets/7bbc9fc7-48e5-4ed9-9365-456195ded1b4

[latestlog.txt](https://github.com/user-attachments/files/17001363/latestlog.txt)

**Comment by GaucovyAero** [comment]
yeah seems like your helio g85 really doesnt support zink
