### ISSUE TITLE
[BUG] Xbox elite controller 2 isn't working 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6064]
### Describe the bug

So when I remap the controller cause it wasn't working all buttons work, a,b,x,y etc. all buttons work and this is a just bought controller and pojavlauncher was working with my scuf controller but if you're in single player (use touch controller) the buttons are all over the place when I press Y it jumps and sometimes just doesn't even work

### The log file and images/videos

[latestlog (3).txt](https://github.com/user-attachments/files/16994432/latestlog.3.txt)

### Steps To Reproduce

```markdown
1. Use elite series 2 controller
2. Map all buttons
3. Start game
4. Try to click multiplayer or anything 
5. Nothing happens
```

### Expected Behavior

I expect all buttons to work 

### Platform

```markdown
- Device model: s23 ultra 
- CPU architecture: uninown
- Android version: 14
- PojavLauncher version: foxglove-20240909-366f181-v3_openjdk
```

### Anything else?

N/a

**Comment by ghost** [comment]
B presses escape 
Y jumps 
A nothing
B nothing 
Up dpad sneak
Right dpad nothing
Left dpad nothing
Down dpad nothing
Left bumper nothing
Right bumper nothing
Pressed in left joystick nothing 
Pressed in right joystick nothing 
Left trigger right click
Right trigger left click
Only ones that actually work is left trigger and right trigger those are normal here are my control schemes they are all the default.
![Uploading Screenshot_20240913_092452_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

**Comment by ghost** [comment]
Be advised that my controller works on PC and my phone on any other game such as call of duty or guilty gear strive or cod mobile. It just doesn't work on pojavlauncher

**Comment by GaucovyAero** [comment]
go to pojav settings - controls and press reset gamepad mappings, then join the game and map the controller and see if it works

**Comment by ghost** [comment]
Tried, still not working do you suggest another version?

**Comment by GaucovyAero** [comment]
> Tried, still not working do you suggest another version?

you can only use like older builds from apkmirror or something

pls send a video of doing what i said in the previous comment

**Comment by ghost** [comment]
Tried this pojavlauncher version via apkmirror.com still not working. https://www.apkmirror.com/apk/artdeell/pojavlauncher-minecraft-java-edition-for-android/pojavlauncher-minecraft-java-edition-for-android-edelweiss-20230928-9484d0c-v3_openjdk-release/pojavlauncher-minecraft-java-edition-for-android-edelweiss-20230928-9484d0c-v3_openjdk-2-android-apk-download/download/?key=1faa38446c3c75aad4ce8dacb52fa429e8


https://github.com/user-attachments/assets/1be5a83e-46c2-47f5-ad5a-6f790a19dd95

**Comment by ghost** [comment]
So I tried with my scuf instinct controller (the one that was working before) And it was working seems like this is a issue with elite controller 2 from xbox

**Comment by GaucovyAero** [comment]
okay

**Comment by GaucovyAero** [comment]
try reproducing the issue in this app

https://play.google.com/store/apps/details?id=ru.elron.gamepadtester

**Comment by ghost** [comment]
https://github.com/user-attachments/assets/37dab850-9e61-4138-a87a-f5618e8ee12e

**Comment by ghost** [comment]
All buttons work on gamepad tester.

**Comment by GaucovyAero** [comment]
okay

**Comment by ghost** [comment]
Do you have any other ideas how to fix this or will this require a new fork?

**Comment by ghost** [comment]
do we have any idea when this will be fixed?

**Comment by GaucovyAero** [comment]
devs have basically 0 time always and this is a low priority issue, it does indeed cost money and time to buy a controller and test it, might not be done anytime soon

**Comment by ghost** [comment]
Hey all good! I'll return this controller and try a different controller to see if it's just a issue with this controller.

**Comment by ghost** [comment]
So I have replaced the controller and it doesnt seem to be working anyway with a new elite series 2.
