### ISSUE TITLE
[BUG] Inability to navigate Fabric Menus

### ISSUE THREAD

**Issue by FiveNights21611** [PojavLauncherTeam/PojavLauncher#6065]
### Describe the bug

I downloaded Fabric for 1.18.2, but whenever the main menu loads, I can't click any of the buttons or even highlight them when I hover over them like they should.

Only mod I have installed is the Fabric API because I wanted Sodium and Iris

### The log file and images/videos

![Screenshot_20240913_142157_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/f57a3c5e-b2ff-4ce5-9196-8e5198b613cb)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Download and run Fabric 1.18.2
3. Wait for the Main Menu to load
```

### Expected Behavior

To be able to properly navigate the menus

### Platform

```markdown
- Device model: Samsung Galaxy A15 Pro
- CPU architecture: arm64 (I think)
- Android version: Android-14
- PojavLauncher version: Latest
```

**Comment by FiveNights21611** [comment]
I have also tested if it was Fabric API, it is not.

**Comment by FiveNights21611** [comment]
Okay, so it's not an issue of not being able to interact, but it is an issue of graphical mouse misplacement-
![Screenshot_20240913_143608_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/3397ad57-eb0c-4c44-ae5f-cf266ae9bf7c)
![Screenshot_20240913_143652_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/451ed633-eba2-4d37-b097-56e5e424f3b9)

**Comment by GaucovyAero** [comment]
this sometimes happens and nobody has an idea why, try removing your options.txt file and make sure fullscreen is on

**Comment by GaucovyAero** [comment]
closing until someone finds a way to consistently reproduce this on all devices
