### ISSUE TITLE
[BUG] Can't connect to server

### ISSUE THREAD

**Issue by Teekqu** [PojavLauncherTeam/PojavLauncher#6066]
### Describe the bug

I tried to connect to my server, but this doesn't work via the domain. If I try to connect directly via the IP, everything works. I can use the domain normally via the Java Edition on the PC. I suspect there are problems connecting to Cloudflare as these are only smaller servers that use Cloudflare for the domain.

I used the following servers for testing:
- swacrew.net
- dev.timo.ac

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17003839/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Add "Swacrew.net" as server
3. Connect to Server
4. "Unknown host"
```

### Expected Behavior

I expected to come to the server.

### Platform

```markdown
- Device model: Samsung Galaxy A50
- CPU architecture: Octa-core (4x2.3 GHz Cortex-A73 & 4x1.7 GHz Cortex-A53)
- Android version: 11
- PojavLauncher version: foxglove-20240909-366f181-v3_openjdk
```

**Comment by GaucovyAero** [comment]
yeah this is a triple duplicate issue #5243 and #4479 but thanks for actually putting some IPs here for testing

**Comment by GaucovyAero** [comment]
closing as a duplicate, i put the testing ips in the original issue
