### ISSUE TITLE
Code 1 bug again

### ISSUE THREAD

**Issue by Cory939** [PojavLauncherTeam/PojavLauncher#6067]
### Describe the bug

So its de same thing as de code 1 that I reported like 3 or 4 days I think so someone told me that to fix de code 1 bug I had to cut de mods but so I install pojavlouncher and I installed forge and I just installed 2 mods and then cut them and put them in the mods folder then I then I put the start button of forge and it appear again the code 1 thing heres de latestlog 
[latestlog.txt](https://github.com/user-attachments/files/17004113/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17004116/latestlog.txt)

### Steps To Reproduce

```markdown
So this is what I did so install forge and then install 2 mods and cut them and put them in the mods folder and the start forge.
```

### Expected Behavior

I would like it to not say de code 1 thing

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Thats it

**Comment by ThatMG393** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/6052#issuecomment-2346136794

**Comment by Cory939** [comment]
Its the same thing well not the same because this time I cut the mods

**Comment by GaucovyAero** [comment]
# Installing any mod results in a crash
Please check the log file. In case you find yourself getting "Permission denied" on all of your files, please do not cut the mods, copy them instead.
