### ISSUE TITLE
[BUG] FKIN READ THIS BROOOOOOO

### ISSUE THREAD

**Issue by asumy1** [PojavLauncherTeam/PojavLauncher#6069]
### Describe the bug

start loading crash

### The log file and images/videos

psl

### Steps To Reproduce

```markdown
1. start pojav
2. crash while loading mods
```

### Expected Behavior

FIX ITTT

### Platform

```markdown
- Device model: Samsung a9+
- PojavLauncher version:lastest
```

### Anything else?

plsllslslallakakakappslslsplspsls

**Comment by asumy1** [comment]
log file :
[latest.log](https://github.com/user-attachments/files/17006555/latest.log)
and this one is pojav's log file:
[latestlog.txt](https://github.com/user-attachments/files/17006560/latestlog.txt)
pojav crash file :
[latestcrash.txt](https://github.com/user-attachments/files/17006562/latestcrash.txt)
crash from .minecraft:
[crash-2024-09-15_22.10.05-client.txt](https://github.com/user-attachments/files/17006569/crash-2024-09-15_22.10.05-client.txt)

plsssss

**Comment by ghost** [comment]
Iris doesn't work with pojav remove it.

**Comment by ghost** [comment]
Also according to your log is "Warnings were found!
 - Mod 'More Culling' (moreculling) 1.18.2-0.8.2 recommends any version of memoryleakfix, which is missing!"

**Comment by ghost** [comment]
Iris can only work if put iris and sodium mod together because if you not put sodium mod it's crash but sodium it's pretty useless for pojav. optifine better

**Comment by ghost** [comment]
Agreed optimize 10x better but if it was open sourced it'd be 100x better
