### ISSUE TITLE
[BUG]spectator mode..f5 skin not showing

### ISSUE THREAD

**Issue by pedrosouzabrasil** [PojavLauncherTeam/PojavLauncher#607]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...any device

**Screenshots**

**Platform:**
 - Device Model [e.g. núbia 5s 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Skin not showing in spectator mode? Or skin not showing while in F5?

**Comment by pedrosouzabrasil** [comment]
Maybe both...but maybe related tô gl4es

**Comment by pedrosouzabrasil** [comment]
Need investigation

**Comment by Mathias-Boulay** [comment]
The head is properly showing on the crocus update.
Closing
