### ISSUE TITLE
Game exited with code -1

### ISSUE THREAD

**Issue by CHOPDAHEADYT** [PojavLauncherTeam/PojavLauncher#6072]
### Describe the bug

I had pu up some mods and opened 1.8.9 forge it crashed with saying game exited with code  -1

### The log file and images/videos

[crash-2024-09-16_17.32.25-client.txt](https://github.com/user-attachments/files/17012783/crash-2024-09-16_17.32.25-client.txt)
[latestlog (1).txt](https://github.com/user-attachments/files/17012786/latestlog.1.txt)

### Steps To Reproduce

```markdown
I put some mods in mods folder 
I opened Forge 1.8.9 
It took some time then it crashed 
Saying game exited with code  -1
```

### Expected Behavior

I need a solution

### Platform

```markdown
- Device model: Galaxy Tablet s6 lite 
- CPU architecture: arm64
- Android version: latest 
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
you are crashing because of oneconfig, try this

**Comment by GaucovyAero** [comment]
# How to make OneConfig work on PojavLauncher with minimal lag 
### Thanks to JellyLab and littleone24_ for bringing this option to our attention and Wyvest for even attempting to support us in the first place

Requirements: 
    At least on PojavLauncher Edelweisse/Playstore Release
    (Optional) Device is capable of using Zink (Note: this hasn't been tested on iOS yet, someone please test it)

* Launch OneConfig or mod using OneConfig. __***It will crash on first time launch, that's okay.***__
* Set `updatechannel` to 1 in `.minecraft/OneConfig/OneConfig.json` and `.minecraft/OneConfig/Preferences.json`
* Set `enableBlur` to 0 in `.minecraft/OneConfig/Preferences.json` (Optionally, disable all animations as well)
* Use Zink renderer (or HolyGL4ES)
* Set Optifine Antialiasing to Off in Video Settings (Only if using Optifine)

**Known Bugs**
* Scroll bar is misaligned slightly to the right of the actual GUI

__***Important***__
Mods that use OneConfig will work on HolyGL4ES. But you cannot open the OneConfig menu or else it will crash. If you have a startup crash, just go to another app while Minecraft loads in.
__***Important***__

**Comment by CHOPDAHEADYT** [comment]
Pls sm1 respond

**Comment by CHOPDAHEADYT** [comment]
Pls send a vid of u doing it
