### ISSUE TITLE
[BUG] <Short description> what is this ??? Plz tell a solution 

### ISSUE THREAD

**Issue by pzykidoo** [PojavLauncherTeam/PojavLauncher#6073]
### Describe the bug

![Screenshot_20240917_014148](https://github.com/user-attachments/assets/63c2b416-6295-47d3-8543-fcb4ecd45ea0)

### The log file and images/videos

Plz tell a solution 

### Steps To Reproduce

```markdown
Login with Microsoft account
```

### Expected Behavior

Loggin successfull

### Platform

```markdown
- Device model:iqoo z6 5g
- CPU architecture:
- Android version:14
- PojavLauncher version:1.20.6
```

### Anything else?

Plz fix

**Comment by GaucovyAero** [comment]
do what it tells you to do

**Comment by Marshall2439** [comment]
Buy Minecraft
