### ISSUE TITLE
[BUG] Minecraft Newer version Crashing

### ISSUE THREAD

**Issue by FindingBlood** [PojavLauncherTeam/PojavLauncher#6074]
### Describe the bug

I downloaded pojav launcher from play store and do some basic settings. Then when I play very old version so it work correctly but when playing 1.20.1 and 1.20.4 it crashes immediately.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17022933/latestlog.txt)

### Steps To Reproduce

```markdown
1: Start Pojav Launcher
2: Do some Basic Settings
3: Downloaded 1.20.1 and 1.20.4
4: It crashed Immediately.
```

### Expected Behavior

I except it will run like older versions but it crashed

### Platform

```markdown
- Device model: Galaxy Samsung A30s
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: latest foxglove
```

### Anything else?

Yes! My physical mouse doesn't show when I connect my physical mouse it just shows in built mouse but it moves according to my physical mouse it will be great if my physical mouse works correctly.

**Comment by artdeell** [comment]
is library verification turned on in your settings?

**Comment by Zack694** [comment]
U need jvm 21 above 1.17+ to run 1.18-1.19-1.20

**Comment by GaucovyAero** [comment]
oh, this is the aarch32 samsung issue, try installing the latest runtime from the android-openjdk-build-multiarch repository
