### ISSUE TITLE
[CRASH] 1.20.1 Fabric Sodium

### ISSUE THREAD

**Issue by Zack694** [PojavLauncherTeam/PojavLauncher#6075]
### Describe the bug

It crashes for no reason and randomly, it even crashes in the main menu even if ur doing nothing

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17052322/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start 1.20.1 fabric 1.15.11
2. Play in any server
3. Wait for 1 min and crash
```

### Expected Behavior

To not crash

### Platform

```markdown
- Device model: vivo 1906
- CPU architecture: 1.95 GHz Snapdragon 439 Octa-Core
- Android version: Android 11
- PojavLauncher version: Latest
```

**Comment by TylerHaoNhot** [comment]
try sodium from "Haste" modpack

**Comment by TylerHaoNhot** [comment]
btw im impressed that you're playing pojav on snapdragon 400 series ☠️

**Comment by Zack694** [comment]
> try sodium from "Haste" modpack

Can I add mods to haste modpack? Like wurst and other stuff?

**Comment by TylerHaoNhot** [comment]
> > try sodium from "Haste" modpack
> 
> Can I add mods to haste modpack? Like wurst and other stuff? 

yes, but some are incompatible so make sure to test it out first.

**Comment by GaucovyAero** [comment]
patch it with pojavpatcher, 0.4.10 should work then

**Comment by Zack694** [comment]
> patch it with pojavpatcher, 0.4.10 should work then

I can't execute jars for no reason, it crashes every 3 seconds
