### ISSUE TITLE
[BUG] Can't execute any jars

### ISSUE THREAD

**Issue by Zack694** [PojavLauncherTeam/PojavLauncher#6078]
### Describe the bug

I can't execute any jars, I execute 1 and it crashes for no reason at all, I checked at mclo.gs but it said there's no errors

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17061515/latestlog.txt)

### Steps To Reproduce

```markdown
1.Click "Execute .jars"
2. Wait for 3.49 seconds and close/crash
```

### Expected Behavior

To execute the jar file

### Platform

```markdown
- Device model: vivo 1906
- CPU architecture: Snapdragon
- Android version: Android 11
- PojavLauncher version: Latest
```

### Anything else?

N/A

**Comment by GaucovyAero** [comment]
make sure your java tweaks settings look like this

![27814](https://github.com/user-attachments/assets/282eb67a-d20a-42ef-b921-3b9250edf620)

**Comment by Zack694** [comment]
> make sure your java tweaks settings look like this
> 
> ![27814](https://private-user-images.githubusercontent.com/85581164/369058357-282eb67a-d20a-42ef-b921-3b9250edf620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTUxNDcsIm5iZiI6MTcyNjc5NDg0NywicGF0aCI6Ii84NTU4MTE2NC8zNjkwNTgzNTctMjgyZWI2N2EtZDIwYS00MmVmLWI5MjEtM2I5MjUwZWRmNjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxMTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MjBkNDZmNTZjY2VlOGEwZjU3ZjZhNjQ0ODgyZmM5YTAwMDIyZTcyYmE4Yzk0MmYyMGIwZGE5NThjZmM5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rl9beAj1SmN8Z9yC2hb8qPmSqaT1saM0ko9ZTj-Cpyo)


https://github.com/user-attachments/assets/6a49e839-a5ec-4498-8e70-f9ea95134394

It's still crashing

**Comment by GaucovyAero** [comment]
send log

**Comment by Zack694** [comment]
> send log

[latestlog.txt](https://github.com/user-attachments/files/17071907/latestlog.txt)
I'm trying to execute pojavpatcher or sodium patcher but it crashes

**Comment by GaucovyAero** [comment]
try using latest jre17-pojav from the android-openjdk-build-multiarch repository on github

**Comment by Zack694** [comment]
> try using latest jre17-pojav from the android-openjdk-build-multiarch repository on github

Still crashing😭
[latestlog.txt](https://github.com/user-attachments/files/17072347/latestlog.txt)

**Comment by GaucovyAero** [comment]
you are still using internal-17 and not the custom runtime

**Comment by Zack694** [comment]
Oh wait let me delete internal 17

**Comment by Zack694** [comment]
It worked thanks

**Comment by GaucovyAero** [comment]
nice
