### ISSUE TITLE
[BUG]BLUE Button appears sometimes holding shift (squat skin) 

### ISSUE THREAD

**Issue by pedrosouzabrasil** [PojavLauncherTeam/PojavLauncher#608]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. núbia 5s 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
It's default behavior of toggleable buttons. Disable toggleable and try again.

**Comment by pedrosouzabrasil** [comment]
Thanks ;!
