### ISSUE TITLE
can't use the witchery: resurrected mod

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6080]
### Describe the bug

so I wanted to play the witchery: resurrected mod and a couple of others, the thing is taht witchery resurrected requires the original witchery(1.7.10) to be installed and in the resourcepacks folder in order to work, but this causes an error, game exited with code -1.

this issue is more a question as to if pojavlauncher support jar files in the resourcepacks folder as the error comes from that

### The log file and images/videos

>
[latestlog.txt](https://github.com/user-attachments/files/17067289/latestlog.txt)

### Steps To Reproduce

```markdown
1. download witchery and witchery: resurrected (links used bellow)
2. create a forge 1.12.2 profile
3. place the witchery jar in the resourcepacks folder
4. place the witchery: ressurected jar in the mods folder
5. launch the game
```

### Expected Behavior

I expected the mod to load as I _think_ I did everything that was necessary to make that happen

### Platform

```markdown
- Device model: samsung SM-M536B
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240905-8c90b54-v3_openjdk
```

### Anything else?

witchery version used- [download page here](https://www.curseforge.com/minecraft/mc-mods/witchery/files/2234410)
witchery: ressurected (version used was 0.5.2 Hotfix 4)- [download page here](https://witchery.msrandom.net/home/downloads)

**Comment by ghost** [comment]
I'm sorry, I tried to change the label for question but Idk why it doesn't let me do it

**Comment by GaucovyAero** [comment]
gl4es failed to convert the shaders in that mod, cant really help with that

**Comment by GaucovyAero** [comment]
you can try using zink, if it doesnt work, you have to create this file

This might work on some devices, however not on ones which don't fulfill the base Zink requirements.
    **/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt**

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```
