### ISSUE TITLE
Forge 1.18.2 40.2.14 (stoneblock 3 modpack) Code -1

### ISSUE THREAD

**Issue by leelando** [PojavLauncherTeam/PojavLauncher#6081]
### Describe the bug

I wanted to start the mod version and it crashes after loading the Mojang logo with the error code -1 
)

### The log file and images/videos

![Screenshot_2024-09-20-09-01-07-194_com google android apps nbu files](https://github.com/user-attachments/assets/67fb7801-43ce-4957-a780-de9aa1ffa7e4)
[latestlog.txt](https://github.com/user-attachments/files/17071273/latestlog.txt)

### Steps To Reproduce

```markdown
Start the launcher 
Modpack installed
Mod version launched 
It loads the Mojang logo
It crashes -1
```

### Expected Behavior

I hoped it would work flawlessly 

### Platform

```markdown
- Device model: Xiaomi 13T Pro 
- CPU architecture: MediaTek Dimensity 9200+
- Android version: 14 UP1A.230905.011
- PojavLauncher version: foxglove-20240905-8c90b5
4-v3_openjdk
```

**Comment by GaucovyAero** [comment]
for create to run, you have to get a phone with a snapdragon soc or use zink, if it doesnt work, create this file

This might work on some devices, however not on ones which don't fulfill the base Zink requirements.
    **/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt**

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```

**Comment by leelando** [comment]
Thank you, but unfortunately it doesn't seem to work. Is there another option?

**Comment by GaucovyAero** [comment]
no
