### ISSUE TITLE
ZEROS APPEARING IN MINECRAFT MENU

### ISSUE THREAD

**Issue by GTG921** [PojavLauncherTeam/PojavLauncher#6082]
### Describe the bug

When I load HazardousDaniel's Unlimited modpack . Zeros appeared in minecraft menu

### The log file and images/videos

![Screenshot_20240920_170252_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/31e126db-0873-4a65-b0f5-7894c6a380db)
[latestlog.txt](https://github.com/user-attachments/files/17074579/latestlog.txt)

### Steps To Reproduce

```markdown
I tried to fix this issue but I cant
```

### Expected Behavior

Please fix this

### Platform

```markdown
- Device model: Samsung F04
- CPU architecture: 4x 2.3 GHz ARM Cortex-A53, 4x 1.8 GHz ARM Cortex-A53
- Android version: 14
- PojavLauncher version: foxglove-20240905-8c90b54-v3_openjdk
```

**Comment by GaucovyAero** [comment]
![27865](https://github.com/user-attachments/assets/c2feb7eb-873e-4ab7-ba78-6689abacad05)

works just fine for me on gl4es (try not using angle), keep in mind i have a snapdragon soc

**Comment by GTG921** [comment]
If I gl4es render also it is coming like this.
It is coming only in this modpack

**Comment by GaucovyAero** [comment]
as i already said, it works for me, try removing the mods by half and figure out which one is causing you the issue
1. Remove half of the mods (including mods that depend on other mods from the first half)
2. If you don't crash, put in half of the mods you just removed, then continue adding up. If you do crash, remove half of the mods you have now.
3. Figure out which mod is causing the issue.

**Comment by GTG921** [comment]
Can I known which version of modpack do you know
