### ISSUE TITLE
[BUG] (issue is fixed).  redmi 9a hud/hotbar not rendering in 1.18.2 

### ISSUE THREAD

**Issue by Minecraftdestroyer12** [PojavLauncherTeam/PojavLauncher#6086]
### Describe the bug

My hotbar is not rendering but hand is rendering I think it has something to do with 1.18.2 it's happening in that version 1.16.5 is working fine 
 I have check log file everything seems fine but there is a some kind of error no context or a function available something like that. after using exoduim mod is hud will start to flicker i think the exoduim mod is trying render my hud but theres no hud soo it's flickering 
And the no context error is spamming in the log

THE HOTBAR GLITCH 

https://github.com/user-attachments/assets/89781625-14ec-4b47-a88d-e9bfe93cc544

![Screenshot_2024-09-21-12-35-44-197_net kdt pojavlaunch](https://github.com/user-attachments/assets/fd1d31eb-b619-4b6a-aa95-2df36e7590b6)

After using exoduim 
![Screenshot_2024-09-20-21-59-57-303_net kdt pojavlaunch](https://github.com/user-attachments/assets/aa058456-1fb2-4cec-89a5-126c4ffe1068)

### The log file and images/videos

Btw this log is without any mods only fabric
https://github.com/user-attachments/files/17084536/latestlog.txt

### Steps To Reproduce

```markdown
Step 1 start pojavlauncher and start pojavlauncher 1.18.2 version
```

### Expected Behavior

Hud not rendering in 1.18.2

### Platform

```markdown
- Device model: Redmi 9A
- CPU architecture: 32
- Android version: 10
- PojavLauncher version: lastest in playstore
```

### Anything else?

Nuh uh

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt

**Comment by GaucovyAero** [comment]
please say exact device model

**Comment by Minecraftdestroyer12** [comment]
Ok!

**Comment by Minecraftdestroyer12** [comment]
[latestlog.txt](https://github.com/user-attachments/files/17084495/latestlog.txt)

**Comment by Minecraftdestroyer12** [comment]
[Uploading latestlog.txt…]()

**Comment by Minecraftdestroyer12** [comment]
[latestlog.txt](https://github.com/user-attachments/files/17084536/latestlog.txt)

**Comment by Minecraftdestroyer12** [comment]
Everything done

**Comment by Minecraftdestroyer12** [comment]
Thanks for help aero-sama

**Comment by GaucovyAero** [comment]
yeah seems like this is confirmed but i gotta somehow get a redmi 9a (keep in mind this issue only happens on your phone)

**Comment by GaucovyAero** [comment]
try installing optifine and in the shaders tab, set antialiasing to 2x fxaa and see if it helps

**Comment by Minecraftdestroyer12** [comment]
Hmm ok!

**Comment by Minecraftdestroyer12** [comment]
Are my textures tempered?

**Comment by GaucovyAero** [comment]
i dont know what you mean by that, resend the picture here and explain what you mean

**Comment by Minecraftdestroyer12** [comment]
Well I put the log file in a ai code reader it said my textures are tempered something like that

**Comment by GaucovyAero** [comment]
yeah it says that in the log too but i dont think it means anything (still means it only happens on your phone)

**Comment by Minecraftdestroyer12** [comment]
Well Ik

**Comment by Minecraftdestroyer12** [comment]
But that glitch only happens in holy render thats strange

**Comment by GaucovyAero** [comment]
try renaming the issue to "Redmi 9A hotbar not rendering", thanks

**Comment by GaucovyAero** [comment]
> But that glitch only happens in holy render thats strange

no thats known, in the past it was also happening on other phones that have the same gpu as you but now it only happens on your phone

**Comment by Minecraftdestroyer12** [comment]
But that glitch only happens on 1.18.2 not on any others. Not even in 1.18.1 or 1.18

**Comment by GaucovyAero** [comment]
ok thx, you mistyped 9a with a9 but isnt a big issue

**Comment by GaucovyAero** [comment]
> But that glitch only happens on 1.18.2 not on any others. Not even in 1.18.1 or 1.18

oh thats funny, if ill have time ima check on my galaxy a12 that has the same gpu as you do

**Comment by Minecraftdestroyer12** [comment]
Btw when did devs update the holy renderer?

**Comment by Minecraftdestroyer12** [comment]
Thanks for help aero-sama

**Comment by GaucovyAero** [comment]
> Btw when did devs update the holy renderer?

first and second foxglove update were huge updates

**Comment by GaucovyAero** [comment]
was this working before?

**Comment by Minecraftdestroyer12** [comment]
Yep

**Comment by Minecraftdestroyer12** [comment]
Like 2 years ago lol

**Comment by Minecraftdestroyer12** [comment]
my engish isn't that good yet I'm still learning. I'm sorry

**Comment by GaucovyAero** [comment]
> Like 2 years ago lol

lol

**Comment by GaucovyAero** [comment]
> my engish isn't that good yet I'm still learning. I'm sorry

ur good at english lol

**Comment by Minecraftdestroyer12** [comment]
Nope i started learning english two months ago soo i don't think my english that good .thanks for compliment aero-sama

**Comment by Minecraftdestroyer12** [comment]
![Screenshot_2024-09-22-21-39-03-453_com android chrome](https://github.com/user-attachments/assets/3ae5ec44-cbd6-4193-8dd2-84613a2c624b)

**Comment by Minecraftdestroyer12** [comment]
Hello aero-sama can i fix this bug in sodium? 
Btw optifine donest work on my phone

**Comment by GaucovyAero** [comment]
> Hello aero-sama can i fix this bug in sodium? Btw optifine donest work on my phone

probably not fixable

**Comment by Minecraftdestroyer12** [comment]
Well. is there a way to use haste sodium in 1.16.5?

**Comment by Minecraftdestroyer12** [comment]
Btw areo-sama can you check is there's something wrong or missing in my game file. And here that files link
https://www.mediafire.com/file/yebpykc2a8srpdz/files.zip/file

**Comment by GaucovyAero** [comment]
> Btw areo-sama can you check is there's something wrong or missing in my game file. And here that files link https://www.mediafire.com/file/yebpykc2a8srpdz/files.zip/file

i have no idea, if something is missing is has to be in latestlog.txt, whats even the issue?

**Comment by GaucovyAero** [comment]
> Well. is there a way to use haste sodium in 1.16.5?

normal sodium should work in 1.16.5 if you disable fog occlusion and compact vertex format

**Comment by Minecraftdestroyer12** [comment]
Ohh thx

**Comment by Minecraftdestroyer12** [comment]
Btw if you're free. can you check the libraries files for me?

**Comment by ghost** [comment]
Try LTW renderer

**Comment by Minecraftdestroyer12** [comment]
Areo-sama i fix the hud glitch in 1.18.2 you will be surprise by how did i fix it lol
 Bye bye this our last time chatting together btw if want to know how did fix it you can massage me for it

**Comment by Minecraftdestroyer12** [comment]
And 3pm thought are usefull

**Comment by Minecraftdestroyer12** [comment]
Hehehehe

**Comment by RoyalRyze** [comment]
> Areo-sama i fix the hud glitch in 1.18.2 you will be surprise by how did i fix it lol Bye bye this our last time chatting together btw if want to know how did fix it you can massage me for it

could you tell me about it I have the same device as you

**Comment by playiquick** [comment]
Ltw rendering is not fix this issue

**Comment by playiquick** [comment]
In sodium
