### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Sidikjjj** [PojavLauncherTeam/PojavLauncher#6087]
### Describe the bug

Saya ingin mempunyai akun Microsoft 

### The log file and images/videos

Akun Microsoft ini sangat berguna

### Steps To Reproduce

```markdown
Saya hanya ingin akun Microsoft 
Ini ga ada yang lain lagi
```

### Expected Behavior

Ya saya akan memainkan kanya di akun baru saya

### Platform

```markdown
- Device model: java
- CPU architecture: resmi mamin kanya
- Android version: Oppo a12
- PojavLauncher version: 1.20
```

### Anything else?

Reset aku ta berjalan

**Comment by Dilen0001** [comment]
.
