### ISSUE TITLE
[BUG] PUTTING MODS ON POJAV CRASHES

### ISSUE THREAD

**Issue by ZeNon0q** [PojavLauncherTeam/PojavLauncher#6088]
### Describe the bug

I can't put any fabric mods on my pojav launcher even a zoomify doesn't work it crashes my pojav 

### The log file and images/videos

My version is 1.21
My fabric loader is 0.16.5
![Screenshot_20240921-211823](https://github.com/user-attachments/assets/5eea9175-04de-4e92-b722-4399aeb9955e)
And this the only mods that i can only put if i add like appleskin there it'll crash. Is there anyway to fix this?? 

### Steps To Reproduce

```markdown
When i add a mod let's say zoomify and then when i go to the launcher amd try to play using the version 1.21 it crushes it doesn't even go to the mojang loading screen when i remove the mod that i added its back to normal and it will load normally
```

### Expected Behavior

Can i fix this? 

### Platform

```markdown
- Device model:infinix x6833B/infinix NOTE 30
- CPU architecture:helio g99 
- Android version: 14
- PojavLauncher version: i don't know the version of this pojav i just downloaded it, it said it was app debug so idk
```

### Anything else?

Nope

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by ZeNon0q** [comment]
I'm sorry i don't know where to find that latestlog.txt cuz before my game crashes there's no pop up text like check latestlog.txt for more details

https://github.com/user-attachments/assets/007ff9c3-45b5-4696-b30c-1db2d479ae9e
It's just this.. "In this recording i added zoomify mod"

**Comment by ZeNon0q** [comment]
I think this is the latestlog.txt


--------- beginning with launcher debug
Info: Launcher version: edelweiss-20240616-849d6e6-feat/multi_integrated_runtime
Info: Architecture: arm64
Info: Device model: INFINIX Infinix X6833B
Info: API version: 34
Info: Selected Minecraft version: fabric-loader-0.16.5-1.21
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2460
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~sxKXNPh10qTp_3D5mUSDnw==/net.kdt.pojavlaunch.debug-TDSSGHYw5zhHdF1bdH1C8g==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~sxKXNPh10qTp_3D5mUSDnw==/net.kdt.pojavlaunch.debug-TDSSGHYw5zhHdF1bdH1C8g==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  ( 7829): dlopen libgl4es_114.so success

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/libjli.so success

I/jrelog  ( 7829): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/server/libjvm.so success

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/libverify.so success

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/libjava.so success

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Inte

**Comment by ZeNon0q** [comment]
> send latestlog.txt

I think this is latestlog.txt??

 
--------- beginning with launcher debug
Info: Launcher version: edelweiss-20240616-849d6e6-feat/multi_integrated_runtime
Info: Architecture: arm64
Info: Device model: INFINIX Infinix X6833B
Info: API version: 34
Info: Selected Minecraft version: fabric-loader-0.16.5-1.21
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2460
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~sxKXNPh10qTp_3D5mUSDnw==/net.kdt.pojavlaunch.debug-TDSSGHYw5zhHdF1bdH1C8g==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~sxKXNPh10qTp_3D5mUSDnw==/net.kdt.pojavlaunch.debug-TDSSGHYw5zhHdF1bdH1C8g==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  ( 7829): dlopen libgl4es_114.so success

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/libjli.so success

I/jrelog  ( 7829): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/server/libjvm.so success

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/libverify.so success

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-21/lib/libjava.so success

I/jrelog  ( 7829): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/Inte

**Comment by GaucovyAero** [comment]
it is but you have to send it as a file, not as text

**Comment by ZeNon0q** [comment]
> it is but you have to send it as a file, not as text

Oh i don't know how to do that😅

**Comment by ZeNon0q** [comment]
> it is but you have to send it as a file, not as text

[latestlog.txt](https://github.com/user-attachments/files/17084722/latestlog.txt)
Like this??

**Comment by GaucovyAero** [comment]
yep thanks, it tells you to do this

```
	 - Install yet_another_config_lib_v3, version 3.5.0 or later.
```

**Comment by ZeNon0q** [comment]
> yep thanks, it tells you to do this
> 
> ```
> 	 - Install yet_another_config_lib_v3, version 3.5.0 or later.
> ```

Uhhh im not an expert at this um what does it mean?

**Comment by GaucovyAero** [comment]
it tells you to install a mod

**Comment by ZeNon0q** [comment]
> it tells you to install a mod

Ohhh okay I'll try

**Comment by ZeNon0q** [comment]
> it tells you to install a mod

It works buutt only for the zoomify when i add other mods it still crash

**Comment by GaucovyAero** [comment]
send log again

**Comment by ZeNon0q** [comment]
> send log again

  
[latestlog (1).txt](https://github.com/user-attachments/files/17084987/latestlog.1.txt)
Here's the new log 🫡

**Comment by GaucovyAero** [comment]
install sodium and libipn

**Comment by ZeNon0q** [comment]
> install sodium and libipn

I just downloaded it and it's still doesn't work i guess i can't fix this but thank you for your time

**Comment by GaucovyAero** [comment]
> > install sodium and libipn
> 
> I just downloaded it and it's still doesn't work i guess i can't fix this but thank you for your time

just send another log and ill tell you what it says

**Comment by ZeNon0q** [comment]
> > > install sodium and libipn
> > 
> > 
> > I just downloaded it and it's still doesn't work i guess i can't fix this but thank you for your time
> 
> just send another log and ill tell you what it says

Yes sir 🫡
[latestlog (3).txt](https://github.com/user-attachments/files/17085783/latestlog.3.txt)

**Comment by ZeNon0q** [comment]
> > > install sodium and libipn
> > 
> > 
> > I just downloaded it and it's still doesn't work i guess i can't fix this but thank you for your time
> 
> just send another log and ill tell you what it says

Uhhh

**Comment by GaucovyAero** [comment]
remove moreculling

**Comment by ZeNon0q** [comment]
> remove moreculling

Still doesn't work sir
