### ISSUE TITLE
[F-Req] Bring back the old shifting

### ISSUE THREAD

**Issue by ZERO1234-hub** [PojavLauncherTeam/PojavLauncher#6089]
### Is this request related to a bug?

I don't think so, from the way it behaves now it feels like it was intentional

### Describe the request.

For some reason after the new update (foxglove-20240905-8c90b54-v3_op
enjdk) in order to sneak using R2 I must double click it, every other button works just fine, requiring one press to sneak.
Other thing i noticed is that shifting now uses the in game preset; unlike before where sneaking was toggleable no matter the setting in game. this is bad because past versions don't have a toggle option and holding R2 is hard and easy to slip.
I'd love for the old shifting to come back, maybe replacing the modern one or being an option, or atleast remove the requirement to double click, i still don't get it.

### Anything else?

I appreciate the new controller keybinding system ALOT, the extra customizablity is phenomenon and made my experience in the game way better; as now I have access to the D-pad Up and L2 and can merge sprinting with jumping.
Thank you so much for your amazing work and I hope you continue forward with Pojavlauncher, I wish I was able to donate.

**Comment by ZERO1234-hub** [comment]
WOW THAT WAS FAST, I thought it'd take a week to fix this, but man I was wrong.
Thank you for the update!

**Comment by artdeell** [comment]
i like to fast track updates if the solution is simple enough
