### ISSUE TITLE
[BUG]CRASH ISSUE

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#609]
Everytime I load some world(any world) for a minute like 5 to 10 minutes.. The game crash

1. Start PojavLauncher
2. Play
3. Load some world
4. Play for a couple minutes
5. Crash

**Platform:**
 - Device Model [Vivo y17 4/64]
 - CPU architecture [aarch64] 
 - Android Version [9]

--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl-jemalloc.jar, jsr305.jar, lwjgl-opengl.jar, lwjgl-glfw-classes.jar, version, lwjgl.jar, lwjgl-openal.jar, lwjgl-tinyfd.jar, lwjgl-stb.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms750m -Xmx1G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
--------- beginning of main
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
I/jrelog  (18526): " unused DT entry: 
I/jrelog  (18526): DT_RPATH
I/jrelog  (18526):  (type 
I/jrelog  (18526): 0xf
I/jrelog  (18526):  arg 
I/jrelog  (18526): 0x361
I/jrelog  (18526): ) (ignoring)
I/jrelog  (18526): 
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
I/jrelog  (18526): " has unsupported flags DT_FLAGS_1=
I/jrelog  (18526): 0x81
I/jrelog  (18526):  (ignoring unsupported flags)
I/jrelog  (18526): 
S/LaunchJVM(18526): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
S/LaunchJVM(18526): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
I/jrelog  (18526): " unused DT entry: 
I/jrelog  (18526): DT_RPATH
I/jrelog  (18526):  (type 
I/jrelog  (18526): 0xf
I/jrelog  (18526):  arg 
I/jrelog  (18526): 0x450
I/jrelog  (18526): ) (ignoring)
I/jrelog  (18526): 
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
I/jrelog  (18526): " has unsupported flags DT_FLAGS_1=
I/jrelog  (18526): 0x81
I/jrelog  (18526):  (ignoring unsupported flags)
I/jrelog  (18526): 
S/LaunchJVM(18526): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
I/jrelog  (18526): " unused DT entry: 
I/jrelog  (18526): DT_RPATH
I/jrelog  (18526):  (type 
I/jrelog  (18526): 0xf
I/jrelog  (18526):  arg 
I/jrelog  (18526): 0x33c0
I/jrelog  (18526): ) (ignoring)
I/jrelog  (18526): 
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
read: unexpected EOF!
--------- beginning of main
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so
I/jrelog  (18526): " unused DT entry: 
I/jrelog  (18526): DT_RPATH
I/jrelog  (18526):  (type 
I/jrelog  (18526): 0xf
I/jrelog  (18526):  arg 
I/jrelog  (18526): 0x119
I/jrelog  (18526): ) (ignoring)
I/jrelog  (18526): 
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so
I/jrelog  (18526): " has unsupported flags DT_FLAGS_1=
I/jrelog  (18526): 0x81
I/jrelog  (18526):  (ignoring unsupported flags)
I/jrelog  (18526): 
S/LaunchJVM(18526): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so success
S/LaunchJVM(18526): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found
S/LaunchJVM(18526): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found
S/LaunchJVM(18526): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
S/LaunchJVM(18526): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsig.so success
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so
I/jrelog  (18526): " unused DT entry: 
I/jrelog  (18526): DT_RPATH
I/jrelog  (18526):  (type 
I/jrelog  (18526): 0xf
I/jrelog  (18526):  arg 
I/jrelog  (18526): 0x6c1
I/jrelog  (18526): ) (ignoring)
I/jrelog  (18526): 
I/jrelog  (18526): WARNING: linker: 
I/jrelog  (18526): Warning: "
I/jrelog  (18526): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so
I/jrelog  (18526): " has unsupported flags DT_FLAGS_1=
I/jrelog  (18526): 0x81
read: unexpected EOF!
--------- beginning of main
S/LaunchJVM(18526): dlopen /data/app/net.kdt.pojavlaunch-sLBYd4aN2dL9saSMlFCNrg==/lib/arm64/libgl04es.so success
S/LaunchJVM(18526): Done processing args
S/LaunchJVM(18526): Found JLI lib
S/LaunchJVM(18526): Calling JLI_Launch
I/jrelog  (18526): OpenJDK 64-Bit Server VM warning: 
I/jrelog  (18526): No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/jrelog  (18526): 
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
read: unexpected EOF!
ERROR: Unable to get more log.

**Comment by WesleyVanNeck** [comment]
ram mey not be anough to run minecraft

**Comment by Adam0530** [comment]
> ram mey not be anough to run minecraft

So I need to increase the ram by increasing the amount of number in jvm argument xms and xmx? Can you suggest me the best jvm argument for 4GB ram? Also, now I just noticed that I will only crash when I am using forge that has mod

**Comment by Bosi23** [comment]
minecraft forge with mods will always crash on 4gb ram devices if you whant to play forge the only version of minecraft that works are 1.16.4 and below (1.16.5 maybe ) on 1.16.4 and below you can use as many mods as you like and i won't crash.
