### ISSUE TITLE
[BUG] "Mods? [Permission denied]"

### ISSUE THREAD

**Issue by Zahar2loshara** [PojavLauncherTeam/PojavLauncher#6091]
### Describe the bug

When adding more mods after entering a game when already has mods, screen of nothing, remove that second time mod,

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17091001/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download fabric (in my case 0.16.5 fabric on 1.20.1) but don't get in
2. Add any amount of mods
3. Enter the game and exit
4. Add any mod
5. Game stops logging anything else
```

### Expected Behavior

Enter a game or at least some readeble log

### Platform

```markdown
- Device model: Poco x6 pro 5g
- CPU architecture: arm64-v8a
- Android version: hyperos 1.0.12.0.unlmixm
- PojavLauncher version: latest from app store, foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

Im think problem in updated os, when was 1.0.8.0 it was running as usually, but at night of a friday (19.09) it downloads update, and camera doesn't work, so i reload the phone, with new version, and then it does not work.
Im not sure.

**Comment by GaucovyAero** [comment]
copy your mods, do not cut

**Comment by GaucovyAero** [comment]
this is an android thing, not pojav

**Comment by Zahar2loshara** [comment]
And you (as a team) cant do something?

**Comment by Zahar2loshara** [comment]
> copy your mods, do not cut

wdym

**Comment by Zahar2loshara** [comment]
As i watched it problem is in /.minecraft/.fabric/**proceededMods**/
Might be unable to create a that kind of mod
