### ISSUE TITLE
[F-Req] <Short description>TAMIM GAMERZ 

### ISSUE THREAD

**Issue by TAMIMGAMEERZ** [PojavLauncherTeam/PojavLauncher#6094]
### Is this request related to a bug?

1.21.1

### Describe the request.

Please 

### Anything else?

999

**Comment by TAMIMGAMEERZ** [comment]
Please help me I don't sign Minecraft java

**Comment by GaucovyAero** [comment]
https://pojavlauncherteam.github.io/CANTLOGIN.html
