### ISSUE TITLE
[F-Req] i think the pojavlaucher needs a better renderer 

### ISSUE THREAD

**Issue by Minecraftdestroyer12** [PojavLauncherTeam/PojavLauncher#6095]
### Is this request related to a bug?

I'm politely asking you guys too add a new renderer or holy renderer 2.0 thingy. and also everyone would like a new mini update but its upto you guys. Not like I'm forcing you guys or anything. Being a pojav dev seems quite hard and boring. i'm right aero-sama?

### Describe the request.

Nuh uh

### Anything else?

Nuh uh

**Comment by TylerHaoNhot** [comment]
well, if they can create it, probably they'll or they already did it.

**Comment by GaucovyAero** [comment]
you cant just spit out a renderer, it doesnt work like that, we are not opengl devs
