### ISSUE TITLE
Wizards RPG conflicting with Pojavlauncher 

### ISSUE THREAD

**Issue by Azzmikaelson** [PojavLauncherTeam/PojavLauncher#6096]
### Describe the bug

When the mod is installed on fabric, the launcher keeps crashing regardless if its dependencies are installed or not. Minecraft is barely given the chance to load. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17097747/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install Wizards RPG
2. Load Minecraft
```

### Expected Behavior

I expected that this mod wouldn't have conflicted with Pojavlauncher as I don't have Optifabric installed anymore which sometimes conflicts with other mods. 

### Platform

```markdown
- Device model:V2022
- CPU architecture: Kryo 16
- Android version: 12
- PojavLauncher version:
```

### Anything else?

Nothing else.

**Comment by GaucovyAero** [comment]
A potential solution has been determined, this may resolve your problem:
	 - Install playeranimator, version 1.9.0 or later.
	 - Replace mod 'Fabric API' (fabric-api) 0.100.3+1.21 with mod 'Fabric API' (fabric-api), version 0.102.0+1.21.1 or later.
	 - Replace mod 'Fabric Loader' (fabricloader) 0.15.11 with version 0.16.3 or later.

**Comment by Azzmikaelson** [comment]
> A potential solution has been determined, this may resolve your problem: - Install playeranimator, version 1.9.0 or later. - Replace mod 'Fabric API' (fabric-api) 0.100.3+1.21 with mod 'Fabric API' (fabric-api), version 0.102.0+1.21.1 or later. - Replace mod 'Fabric Loader' (fabricloader) 0.15.11 with version 0.16.3 or later

The results are still the same, it crashed.
