### ISSUE TITLE
[F-Req] "joystickable" buttons

### ISSUE THREAD

**Issue by Just-Gogalo** [PojavLauncherTeam/PojavLauncher#6097]
### Is this request related to a bug?

No

### Describe the request.

The best way I have to describe this is: Bedrock.
When playing Bedrock mobile you can hold to mine and then move your camera around.
When playing in Pojav, you'd have to move -> hit button -> move -> hit button. 
It would be great to either be able to configure a joystick so when you use it it does a "hold action" on the button selected, or for buttons to be able to be "dragged" even if just by action and not visually dragging them

### Anything else?

Using the "hold" feature could be a workaround, but is not as seamless
This may also give joysticks another use instead of just noving the player around

**Comment by GaucovyAero** [comment]
enable mouse pass-thru on your button
