### ISSUE TITLE
[BUG] <Jar file is not jar file>

### ISSUE THREAD

**Issue by SnegPadaet** [PojavLauncherTeam/PojavLauncher#6098]
### Describe the bug

when I launch mods on forge Minecraft says "Jar file is not jar file" And I don't see them in mods

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/17107965/latest.log)
![Screenshot_20240924-073330](https://github.com/user-attachments/assets/bf28d7b9-f4b8-45f7-8fbf-8f55838df0be)

### Steps To Reproduce

```markdown
1. Open game
2. Get error
```

### Expected Behavior

I expect the mods to work

### Platform

```markdown
- Device model:Tecno Pova Neo 6
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove- 20240922-a6a6a29-v3_openjdk
```

**Comment by ghost** [comment]
Send latestlog.txt not latest.log 
I think you cut the mods. Do not cut the mods. copy them

**Comment by SnegPadaet** [comment]
[latestlog.txt](https://github.com/user-attachments/files/17122958/latestlog.txt)

**Comment by GaucovyAero** [comment]
do not cut the mods

**Comment by kasrarouhi** [comment]
> do not cut the mods

I already say that

**Comment by kasrarouhi** [comment]
Right!!
