### ISSUE TITLE
Compiling JAVA arm7

### ISSUE THREAD

**Issue by DwifteJB** [PojavLauncherTeam/PojavLauncher#610]
The compling instructions are confusing and i have no idea how to compile Java arm7 for PojavLauncher.

**Comment by WesleyVanNeck** [comment]
arm7 32 bit is not suported rn there is a uffcial run time do

**Comment by DwifteJB** [comment]
Ah okay but on [the build script](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch) it shows armv7

**Comment by WesleyVanNeck** [comment]
> Ah okay but on [the build script](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch) it shows armv7

yes it doesnt compile for armv7

**Comment by DwifteJB** [comment]
then why mention armv7? i think it would of been better to add the unsupported archs on the readme.

**Comment by artdeell** [comment]
Armv7 is supported by the launcher itself, and will be built by default.

**Comment by artdeell** [comment]
(The launcher itself works on armv7, but there's no official armv7 JRE yet.)

**Comment by DwifteJB** [comment]
Yeah okay that makes sense, i thought he meant it was impossible to compile arm7 JRE. Also is there a way to compile JRE for arm7.

**Comment by khanhduytran0** [comment]
There was separate repo for armv7 recently.
