### ISSUE TITLE
[BUG] <Shader failed to load>

### ISSUE THREAD

**Issue by ZeNon0q** [PojavLauncherTeam/PojavLauncher#6100]
### Describe the bug

Everytime i put a shader the chat says "shader failed to load"

### The log file and images/videos

And it wanted me to copy something and it's this  
sky_basic.vsh: sky_basic.vsh: 0:110: S0023: Function 'ftransform' redefined

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

Ahh

### Platform

```markdown
- Device model:infinex note 30  
- CPU architecture: Helio G99
- Android version: 14
- PojavLauncher version:
```

### Anything else?

I hope there's a solution for this

**Comment by ghost** [comment]
Use zink renderer if it failed to load again because of bad gpu. if gpu is mali or adreno it's more compatible with zink renderer than helio gpu

**Comment by ghost** [comment]
But send latestlog.txt

**Comment by ZeNon0q** [comment]
> But send latestlog.txt

Here's my latest latestlog
[latestlog.txt](https://github.com/user-attachments/files/17116315/latestlog.txt)

**Comment by ZeNon0q** [comment]
> Use zink renderer if it failed to load again because of bad gpu. if gpu is mali or adreno it's more compatible with zink renderer than helio gpu

If i use zink it just forces my pojav to close when i hit play so i use holy gl4es

**Comment by GaucovyAero** [comment]
shaders don't work on gl4es

**Comment by GaucovyAero** [comment]
# Zink doesn't work
This might work on some devices, however not on ones which don't fulfill the base Zink requirements.
    **/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt**

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```
