### ISSUE TITLE
[BUG] use zink (vulkan) causes the game to immediately close

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6102]
### Describe the bug

whenever i select zink vulkan as the renderer, the game automatically closes uppon launching it without the usual dialogue that says to share the textlog file, first I thought it was due to me using forge, but it also doesn't work using vanilla minecraft

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17120928/latestlog.txt)

### Steps To Reproduce

```markdown
1. install a forge/vanilla profile 1.7.10
2. choose zink(vulkan) as the renderer
3. launch the game
```

### Expected Behavior

I expected the renderer to work because a mod that I wanted to play is only supported by Zink apparently

### Platform

```markdown
- Device model: samsung SM-M536B
- CPU architecture: arm64
- Android version: 34
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
# Zink doesn't work
This might work on some devices, however not on ones which don't fulfill the base Zink requirements.
    **/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt**

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```
