### ISSUE TITLE
Djava.library.path is set to a folder containing shared libraries of an older LWJGL version

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6103]
### Describe the bug

this keeps appearing in the textlog file whenever I try Zink renderer, along with a message saying game exited with code -1, but I have no idea what library it's talking about, much less how to update it.
I've already tried to uninstall and reinstall/update pojavlauncher but the library problem persists

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17135831/latestlog.txt)

### Steps To Reproduce

```markdown
1. install any version
2. choose zink(vulkan) as your renderer
3. launch the game
```

### Expected Behavior

I expected the zink vulkan to work without any errors (I already used zink vulkan in other emulators and it worked so at least I know my device can support it)

### Platform

```markdown
- Device model: samsung SM-M536B
- CPU architecture: arm64
- Android version: 34
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
```
java.lang.RuntimeException: could not preload blit shader
	at gdj.a(SourceFile:443)
	at ffh.<init>(SourceFile:676)
```

this is the actual error

**Comment by GaucovyAero** [comment]
# Zink doesn't work
This might work on some devices, however not on ones which don't fulfill the base Zink requirements.
    **/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt**

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```
