### ISSUE TITLE
[BUG] <world currupt??>

### ISSUE THREAD

**Issue by ZeNon0q** [PojavLauncherTeam/PojavLauncher#6104]
### Describe the bug

I don't what this is

### The log file and images/videos

![Screenshot_20240926-095721](https://github.com/user-attachments/assets/fc6d4fc9-ca53-4b7b-bab7-f9a3603c314b)
It looks like this

### Steps To Reproduce

```markdown
It happens when i join a world or a server
```

### Expected Behavior

I hope there's a way to fix this

### Platform

```markdown
- Device model: infinix note 30
- CPU architecture: helio g99
- Android version: 14
- PojavLauncher version:
```

### Anything else?

Nope

**Comment by GaucovyAero** [comment]
no log attached, if the server uses a custom resource pack and you are using gl4es, turn on the shader dump and send log

**Comment by GaucovyAero** [comment]
and fill out the pojav version correctly

**Comment by itsakc-me** [comment]
Goto "Options > Video Settings" and then turn off "Use VBOs"

**Comment by ghost** [comment]
> Goto "Options > Video Settings" and then turn off "Use VBOs"

Or turn off render region
