### ISSUE TITLE
[Bug] Zink(vulkan) crashes when launched on forge 1.7.10

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6105]
### Describe the bug

so I made a issue about Zink not working on any version and the solution given to me was creating a file called custom_env.txt  on the files folder with the following:

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```
I tested Zink on a newer version (1.20.6) with this new file, and it worked perfectly, but the problem still persists on forge 1.7.10

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17150508/latestlog.txt)

### Steps To Reproduce

```markdown
1. install forge 1.7.10 
2. choose zink as your renderer
3. launch the game
```

### Expected Behavior

I expected it to work  like it worked for 1.20.6

### Platform

```markdown
- Device model: samsung SM-M536B
- CPU architecture: arm64
- Android version: 34
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
if it doesnt work, it probably just wont, we dont make renderers and cant really fix these issues, this is very much device-specific and updating zink might result in other devices not working
