### ISSUE TITLE
[BUG] Minecraft 1.20.1 crashes only when I use optifine

### ISSUE THREAD

**Issue by Dummy-destroyer** [PojavLauncherTeam/PojavLauncher#6106]
### Describe the bug

When I use any mod, nothing happens but when I use optifine, it crashes and says application excited with code 1 or something like that

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17155691/latestlog.txt)

### Steps To Reproduce

```markdown
1 start povjavlauncher
2 start Minecraft 1.20.1 forge
3 application excited with game code 1
```

### Expected Behavior

I expect for my optifine to work correctly 

### Platform

```markdown
- Device model: HONOR X7b
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: version foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
permission denied, do not cut the mod, copy the mod (this is an android thing)

**Comment by Dummy-destroyer** [comment]
So I have to copy the mod instead of cutting it to the game directory?

**Comment by Dummy-destroyer** [comment]
Thx you so much, it worked (:
