### ISSUE TITLE
[BUG] Physical Keyboard SPACE* ENTER* is not working

### ISSUE THREAD

**Issue by itsakc-me** [PojavLauncherTeam/PojavLauncher#6107]
### Describe the bug

so here it is.

i want to play pojav launcher but after the new update i just cannot use the spacebar to jump but if i try using another key in term of his like v then the player jumps perfectly this only happens when im in the game screen not in others like if i chat and then try to click spacebar it is working perfectly same when going to customizing the key from v to space again (by pressing not resetting).

also when i try to run any command or try to write and send any msg through chat the enter key is not working. i am really obsessed with this bug. please fix it as soon as possible (hope).

Physical Keyboard : Dell KB216 (fully working when i code or do anything else but not in pojav launcher game screen).

the game version i used is v1.8.9 and cmpack v1.8.8

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17159114/latestlog.txt)

### Steps To Reproduce

```markdown
1. Connect any physical keyboard.
2. Start pojavlauncher.
3. Open the specified game version.
4. Create new world or join old ones or join any server.

Spacebar Bug
5. Try clicking spacebar while you are in the game screen (not in chat).

Enter Bug
5. Try writing any thing in the chat and then press enter.
```

### Expected Behavior

i expect the player should jump when pressing spacebar and send any msg when pressing enter.

### Platform

```markdown
- Device model: Xiaomi POCO M5
- CPU architecture: arm64
- Android version: Android 14, HyperOS
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try setting the physical keyboard language to US and try changing your software keyboard (just to see if it does something) maybe from Gboard to SwiftKey or the other way around, see if that helps

**Comment by itsakc-me** [comment]
> try setting the physical keyboard language to US

But this not seems to work as at the old version of pojav launcher (dahlia) works fine with my current keyboard language but still i will try.

> try changing your software keyboard (just to see if it does something) maybe from Gboard to SwiftKey or the other way around, see if that helps

I am already using another open source keyboard FlorisKeyboard (Beta latest version), so iam going to try to change it to gboard then maybe it works.

Btw thanks for atleast replying me.

**Comment by itsakc-me** [comment]
@GaucovyAero thanks brother, man or whoever you are but the problem is fixed as soon as I choose the gboard keyboard instead of the FlorisKeyboard.

Again thanks dude and also i am closing this issue but still I want to remind this issue as a real issue like choosing another software keyboard can offend the physical keyboard than maybe, you (devs) can fix it because I only got this error while in game screen not in chat or any other place.

So, please check it out if you (devs) can do something to not let the software keyboard to create problem for physical keyboard players because I don't like gboard, so again please check it fr.

**Comment by GaucovyAero** [comment]
pretty sure this is not a pojav issue but rather an issue with florisboard, pls let them know about this
