### ISSUE TITLE
Game crashes when opening world in rl craft

### ISSUE THREAD

**Issue by MehulLahre** [PojavLauncherTeam/PojavLauncher#6108]
### Describe the bug

The game crashes when opening world and shows shutting down internal servers

### The log file and images/videos

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (BedBreakBegone-1.0.2.jar)
  SimpleDifficulty ASM (SimpleDifficulty-1.12.2-0.3.9.jar)
  RLTweaker ASM (RLTweaker-1.12.2-0.5.12.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
  ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.4.1.jar)
  LoadingPlugin (ChunkAnimator-1.12.2-1.2.1.jar)
  BlockOverlayFixPlugin (BlockOverlayFix-1.12.2-1.0.0.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  MixinLoader (Locks-1.12.2-3.0.0.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6%2bbuild50-universal.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  RLMixinsPlugin (RLMixins-1.2.15.jar)
  EntityCullingPlugin (EntityCulling-1.12.2-6.3.1.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.8.jar)
  SoManyEnchantments ASM (SoManyEnchantments-0.5.5.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64%2bdev.151.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
  MaterialTweakerPlugin (MaterialTweaker-1.1.1.jar)
  RenderLibPlugin (RenderLib-1.12.2-1.2.8.jar)
  Snow! Real Magic! (SnowRealMagic-1.12.2-0.7.1.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.4.1.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar)
  Born in a Barn (Born%20In%20A%20Barn%20V1.8-1.12-1.1.jar)
  WolfArmorCore (WolfArmorAndStorage-3.8.1%2b1.12.2.alpha.1-SNAPSHOT-signed.jar)
  Better Biome Blend (betterbiomeblend-1.12.2-1.1.7-forge.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
  MixinLoader (framevoidpatch-1.0.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 9/27/24 4:12 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at org.lwjgl.system.Checks.check(Checks.java:188)
	at org.lwjgl.openal.EXTEfx.alFilterf(EXTEfx.java:1119)
	at org.lwjgl.openal.EFX10.alFilterf(EFX10.java:81)
	at com.tmtravlr.soundfilters.filters.FilterLowPass.loadParameters(FilterLowPass.java:53)
	at com.tmtravlr.soundfilters.ModifiedLWJGLOpenALSource.updateFilters(ModifiedLWJGLOpenALSource.java:161)
	at com.tmtravlr.soundfilters.ModifiedLWJGLOpenALSource.stopped(ModifiedLWJGLOpenALSource.java:114)
	at paulscode.sound.Source.playing(Source.java:1210)
	at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.playing(SoundManager.java:604)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:258)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SoundHandler.java:293)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1858)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.system.Checks.check(Checks.java:188)
	at org.lwjgl.openal.EXTEfx.alFilterf(EXTEfx.java:1119)
	at org.lwjgl.openal.EFX10.alFilterf(EFX10.java:81)
	at com.tmtravlr.soundfilters.filters.FilterLowPass.loadParameters(FilterLowPass.java:53)
	at com.tmtravlr.soundfilters.ModifiedLWJGLOpenALSource.updateFilters(ModifiedLWJGLOpenALSource.java:161)
	at com.tmtravlr.soundfilters.ModifiedLWJGLOpenALSource.stopped(ModifiedLWJGLOpenALSource.java:114)
	at paulscode.sound.Source.playing(Source.java:1210)
	at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.playing(SoundManager.java:604)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:258)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SoundHandler.java:293)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['dhisnp12bg'/1291, l='MpServer', x=-6740.50, y=50.20, z=7776.98]]
	Chunk stats: MultiplayerChunkCache: 25, 25
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (228,64,224), Chunk: (at 4,4,0 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 137 game time, 137 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 4 total; [EntityPlayerSP['dhisnp12bg'/1291, l='MpServer', x=-6740.50, y=50.20, z=7776.98], EntityZombie['Zombie'/1314, l='MpServer', x=-6733.50, y=21.00, z=7779.50], EntityLatchedRenderer['unknown'/1351, l='MpServer', x=8.50, y=65.00, z=8.50], EntityCreeper['Creeper'/1307, l='MpServer', x=-6743.50, y=13.00, z=7774.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/1351, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-14
	Java Version: 1.8.0_432-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1454605728 bytes (1387 MB) / 3219652608 bytes (3070 MB) up to 3219652608 bytes (3070 MB)
	JVM Flags: 3 total; -Xms3264M -Xmx3264M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 183 mods loaded, 183 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version              | Source                                                         | Signature                                |
	|:------ |:--------------------------- |:-------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2               | minecraft.jar                                                  | None                                     |
	| LCHIJA | mcp                         | 9.42                 | minecraft.jar                                                  | None                                     |
	| LCHIJA | FML                         | 8.0.99.99            | forge-1.12.2-14.23.5.2860.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2860         | forge-1.12.2-14.23.5.2860.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy           | 1.0.0                | minecraft.jar                                                  | None                                     |
	| LCHIJA | itemphysic                  | 1.4.0                | minecraft.jar                                                  | None                                     |
	| LCHIJA | ivtoolkit                   | 1.3.3-1.12           | minecraft.jar                                                  | None                                     |
	| LCHIJA | foamfixcore                 | 7.7.4                | minecraft.jar                                                  | None                                     |
	| LCHIJA | tnt_utilities_core          | 1.2.3                | minecraft.jar                                                  | None                                     |
	| LCHIJA | forgeendertech              | 1.12.2-4.5.6.1       | ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar                   | None                                     |
	| LCHIJA | adhooks                     | 1.12.2-3.3.1.0       | AdHooks-1.12.2-3.3.1.0-build.0626.jar                          | None                                     |
	| LCHIJA | advanced-fishing            | 1.3.3                | Advanced-Fishing-1.12.2-1.3.3.jar                              | None                                     |
	| LCHIJA | aireducer                   | 0.3.0                | AIReducer-1.12.2-0.3.0.jar                                     | None                                     |
	| LCHIJA | alcatrazcore                | 1.0.4                | alcatrazcore-1.0.4.jar                                         | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | antiqueatlas                | 4.6.3                | antiqueatlas-1.12.2-4.6.3.jar                                  | None                                     |
	| LCHIJA | antiqueatlasoverlay         | 1.2                  | antiqueatlas-1.12.2-4.6.3.jar                                  | None                                     |
	| LCHIJA | lostcities                  | 2.0.22               | lostcities-1.12-2.0.22.jar                                     | None                                     |
	| LCHIJA | antiquecities               | 1.0                  | antiquecities-1.2.1.jar                                        | None                                     |
	| LCHIJA | anvilpatch                  | 1.1.1                | anvilpatch-1.1.1.jar                                           | None                                     |
	| LCHIJA | aquaculture                 | 1.6.8                | Aquaculture-1.12.2-1.6.8.jar                                   | None                                     |
	| LCHIJA | carrots                     | 1.0.0b1              | carrotslib-mc1.12.2-1.0.0b1.jar                                | None                                     |
	| LCHIJA | armorunder                  | 1.0.0                | armorunder-mc1.12.2-1.0.0.jar                                  | None                                     |
	| LCHIJA | astikorcarts                | 1.12.2-0.1.2.8       | astikorcarts-1.12.2-0.1.2.8.jar                                | None                                     |
	| LCHIJA | attributefix                | 1.0.12               | AttributeFix-Forge-1.12.2-1.0.12.jar                           | None                                     |
	| LCHIJA | crafttweaker                | 4.1.20               | CraftTweaker2-1.12-4.1.20.687.jar                              | None                                     |
	| LCHIJA | mtlib                       | 3.0.7                | MTLib-3.0.7.jar                                                | None                                     |
	| LCHIJA | modtweaker                  | 4.0.19               | modtweaker-4.0.20.11.jar                                       | None                                     |
	| LCHIJA | jei                         | 4.16.1.302           | jei_1.12.2-4.16.1.302.jar                                      | None                                     |
	| LCHIJA | quark                       | r1.6-179             | Quark-r1.6-179.jar                                             | None                                     |
	| LCHIJA | autoreglib                  | 1.3-32               | AutoRegLib-1.3-32.jar                                          | None                                     |
	| LCHIJA | base                        | 3.14.0               | base-1.12.2-3.14.0.jar                                         | None                                     |
	| LCHIJA | battletowers                | 1.6.5                | BattleTowers-1.12.2.jar                                        | None                                     |
	| LCHIJA | baubles                     | 1.5.2                | Baubles-1.12-1.5.2.jar                                         | None                                     |
	| LCHIJA | bedbreakbegone              | 1.0.2                | BedBreakBegone-1.0.2.jar                                       | None                                     |
	| LCHIJA | llibrary                    | 1.7.20               | llibrary-1.7.20-1.12.2.jar                                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                  | 1.7.1                | iceandfire-1.7.1-1.12.2.jar                                    | None                                     |
	| LCHIJA | mantle                      | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                                       | None                                     |
	| LCHIJA | inspirations                | 1.12.2-0.2.9         | Inspirations-1.12.2-0.2.9.jar                                  | None                                     |
	| LCHIJA | reachfix                    | 1.0.8                | ReachFix-1.12.2-1.0.8.jar                                      | None                                     |
	| LCHIJA | potioncore                  | 1.9_for_1.12.2       | PotionCore-1.9_for_1.12.2.jar                                  | None                                     |
	| LCHIJA | qualitytools                | 1.0.7_for_1.12.2     | QualityTools-1.0.7_for_1.12.2.jar                              | None                                     |
	| LCHIJA | bettercombatmod             | 2.0.8                | RLCombat-1.12.2-2.0.8.jar                                      | None                                     |
	| LCHIJA | somanyenchantments          | 0.5.5                | SoManyEnchantments-0.5.5.jar                                   | None                                     |
	| LCHIJA | mujmajnkraftsbettersurvival | 1.5.3                | better_survival-1.5.3.jar                                      | None                                     |
	| LCHIJA | betterbiomeblend            | 1.12.2-1.1.7-forge   | betterbiomeblend-1.12.2-1.1.7-forge.jar                        | None                                     |
	| LCHIJA | bettercaves                 | 1.12.2               | bettercaves-1.12.2-2.0.4.jar                                   | None                                     |
	| LCHIJA | forgelin                    | 1.8.4                | Forgelin-1.8.4.jar                                             | None                                     |
	| LCHIJA | betterfoliage               | 2.3.2                | BetterFoliage-MC1.12-2.3.3.jar                                 | None                                     |
	| LCHIJA | bettermineshafts            | 1.12.2-2.2.1         | BetterMineshaftsForge-1.12.2-2.2.1.jar                         | None                                     |
	| LCHIJA | betternether                | 0.1.8.6              | betternether-0.1.8.6.jar                                       | None                                     |
	| LCHIJA | betterquesting              | 3.5.329              | BetterQuesting-3.5.329.jar                                     | None                                     |
	| LCHIJA | librarianlib                | 4.22                 | librarianlib-1.12.2-4.22.jar                                   | None                                     |
	| LCHIJA | classyhats                  | %VERSION%            | classyhats-1.6.0.jar                                           | None                                     |
	| LCHIJA | levelup2                    | ${version}           | Level%20Up!%202-1.1.23-1.12.jar                                | None                                     |
	| LCHIJA | lycanitesmobs               | 2.0.8.9 - MC 1.12.2  | lycanitesmobs-1.12.2-2.0.8.9.jar                               | None                                     |
	| LCHIJA | bettertabs                  | 1.0.4                | BetterTabs-1.0.4.jar                                           | None                                     |
	| LCHIJA | blockoverlayfix             | 1.0.0                | BlockOverlayFix-1.12.2-1.0.0.jar                               | None                                     |
	| LCHIJA | bloodmoon                   | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bnbgaminglib                | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                                 | None                                     |
	| LCHIJA | bountifulbaubles            | 0.0.1                | Bountiful%20Baubles-1.12.2-0.1.8.jar                           | None                                     |
	| LCHIJA | bountiful                   | 2.2.3                | Bountiful-1.12.2-2.2.3.jar                                     | None                                     |
	| LCHIJA | reccomplex                  | 1.4.8.4              | RecurrentComplex-1.4.8.4.jar                                   | None                                     |
	| LCHIJA | bq_msi                      | 1.0.9                | BQ_Multiblock_Structure_Integration-1.0.9.jar                  | None                                     |
	| LCHIJA | bqtweaker                   | 1.3.5                | BQTweaker-1.3.5.jar                                            | None                                     |
	| LCHIJA | callablehorses              | 1.1.1                | callablehorses-1.12.2-1.1.1.jar                                | None                                     |
	| LCHIJA | carryon                     | 1.12.3               | carryon-1.12.2-1.12.7.23.jar                                   | None                                     |
	| LCHIJA | champions                   | 1.12.2-1.0.11.10     | champions-1.12.2-1.0.11.10.jar                                 | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | charm                       | 1.4                  | Charm-1.12.2-1.4.1.jar                                         | None                                     |
	| LCHIJA | chunkanimator               | 1.12.2-1.2           | 

### Steps To Reproduce

```markdown
Open world in rl craft
```

### Expected Behavior

To open world

### Platform

```markdown
- Device model: Xiaomi pad 6
- CPU architecture: snapdragon 870
- Android version: 14
- PojavLauncher version: latest version on play store
```

**Comment by GaucovyAero** [comment]
In order to run RLCraft you have to remove these mods:

    Custom Main Menu

    Fancy Block Particles

    Dynamic Surroundings

    Sound Filters

credits to [kasrarouhi](https://github.com/kasrarouhi)
