### ISSUE TITLE
[BUG] modpack crashes while loading

### ISSUE THREAD

**Issue by epicspacecat** [PojavLauncherTeam/PojavLauncher#6109]
### Describe the bug

The modpack is all the mods 9, 20.1 minecraft modpack. When im starting the game its seems normal, all the mods modpack loading its files like it should, but in some way in it crashes for some reason, it stops at loading twilight forest files then crashes with code -1 error. I changed some settings in PojavLauncher because before that it wasnt even starting, it was just stuck at red screen, i changed the visualizer from Holy GL4ES to ANGLE and Java runtime from internal to internal 17. Here is some screenshots and latestlog.

### The log file and images/videos

![Screenshot_20240927_151612_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/fcb547f3-f1a3-4a4c-932e-58b75d017fe3)
![Screenshot_20240927_154819](https://github.com/user-attachments/assets/93289389-74c3-47bb-9187-bfcc42174f31)
[latestlog.txt](https://github.com/user-attachments/files/17164377/latestlog.txt)
![Screenshot_20240927_161612_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/8308e60d-c31f-4a7c-8937-ff179929a86e)
![Screenshot_20240927_161558_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/5b52063c-63ea-4b8b-9e50-13d6104c2979)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Go to settings 
3. Change memory usage from default to 3048
4. Go to Graphics Settings 
5. Change visualizer from Holy GL4ES to ANGLE 
6. Go to Java settings 
7. Change Java runtime from internal to internal 17
8. Go back
9. Click New profile
10. Click modpacks
11. Find all the mods 9 modpack
12. Choose latest version (9-0.3.2 - 1.20.1)
13. Click install
14. Wait for install process
15. Click play
16. Wait some time at loading screen
17. Get crashed
```

### Expected Behavior

Launching minecraft

### Platform

```markdown
- Device model: Huawei p40 lite
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

I would love if you will help me! Thank you!

**Comment by epicspacecat** [comment]
Account is local btw

**Comment by GaucovyAero** [comment]
no log attached, use the share log file button

edit: just didnt see it lol

**Comment by GaucovyAero** [comment]
you gotta remove axiom, because it requires a library which is inside the mod but their build of the lib only works on PCs

java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch.debug/cache/imgui-java-natives_1727439390714/libimgui-java64.so: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/cache/imgui-java-natives_1727439390714/libimgui-java64.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183) (Possible cause: can't load AMD 64 .so on a AARCH64 platform)

**Comment by epicspacecat** [comment]
> you gotta remove axiom, because it requires a library which is inside the mod but their build of the lib only works on PCs
What is axiom

**Comment by GaucovyAero** [comment]
a mod obviously

**Comment by epicspacecat** [comment]
> a mod obviously

Where to remove it? I cant find it in mods folder

**Comment by epicspacecat** [comment]
Theres no axiom mod

**Comment by GaucovyAero** [comment]
then something else requires imgui, you gotta figure out which one it is

**Comment by GaucovyAero** [comment]
Try removing the mods by half:
1. Remove half of the mods (including mods that depend on other mods from the first half)
2. If you don't crash, put in half of the mods you just removed, then continue adding up. If you do crash, remove half of the mods you have now.
3. Figure out which mod is causing the issue.
