### ISSUE TITLE
[BUG] Why do I get crashes every time I try the zink renderer?

### ISSUE THREAD

**Issue by ABtreawoptis23** [PojavLauncherTeam/PojavLauncher#6110]
### Describe the bug

When I try zink renderer it always crashes , Btw the gpu is Mali-G615 MC6

### The log file and images/videos

https://github.com/user-attachments/assets/b72fbd87-ca3b-4c14-88dc-a47215407a66

[latestlog.txt](https://github.com/user-attachments/files/17172858/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojavlauncher 
2.use renderer zink 
3.klik play 
4.and crash
```

### Expected Behavior

I hope this issue can be resolved quickly :)

### Platform

```markdown
- Device model: Poco x6 Pro 12/512G
- CPU architecture:arm64
- Android version:14
- PojavLauncher version:foxglove-20240922-a6аба29-v3_openjdk
```

### Anything else?

Please fix it asap because I want to try java shaders

**Comment by GaucovyAero** [comment]
# Zink doesn't work
If Zink worked for you before the `foxglove` update, this might get it running on your device. It doesn't help on devices which don't fulfill the base Zink requirements.

**/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt** 
(if this file does not exist, create it)

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```

**Comment by ABtreawoptis23** [comment]
So, will it be fixed or not?
