### ISSUE TITLE
[BUG] WHY TF I CANT PLAY WITH OPTIFABRIC IN 1.18.2

### ISSUE THREAD

**Issue by asumy1** [PojavLauncherTeam/PojavLauncher#6112]
### Describe the bug

crash or pop up a screen about something after starting

### The log file and images/videos

blah

### Steps To Reproduce

```markdown
1. start pojav
2. problem with optifabric
```

### Expected Behavior

blah blah

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: mss
```

### Anything else?

pls fix itttt

**Comment by asumy1** [comment]
@everyone @pojavsupport

**Comment by GaucovyAero** [comment]
closing as spam
