### ISSUE TITLE
[BUG] MineCraft crashes when trying to create a new world with mods

### ISSUE THREAD

**Issue by MazTankaz** [PojavLauncherTeam/PojavLauncher#6114]
### Describe the bug

I decided to build for more than 200 mods in fabric 1.20.1 to play with my friends. And then it turns out that one of the friends uses PojavLauncher on Android. And we tried to run this build on his phone, but as a result, the creation of the world failed. 

Looking through the logs, I still didn't understand what the problem might be, so I couldn't think of anything better than to address this issue here. I apologize in advance for this. I also apologize for my English. 

Please help me with this problem!

### The log file and images/videos

[latestlog (4).txt](https://github.com/user-attachments/files/17176672/latestlog.4.txt)

There is no video available...

### Steps To Reproduce

```markdown
1. Installing modifications
2. Launch PojavLauncher
3. Launching MineCraft 1.20.1 fabric
4. Creating a new world
5. The application displays an error and shuts down
```

### Expected Behavior

The world will be created calmly and I will start playing in it.

### Platform

```markdown
- Device model: Xiaomi Pad 5
- CPU architecture: ARM v8.2-A (64-bit)
- Android version: 13
- PojavLauncher version: Foxglove - 20240922...
```

### Anything else?

help Т_Т

**Comment by GaucovyAero** [comment]
optifine is most likely conflicting with a bunch of mods, if you get any more conflicts, try removing the mods by half

**Comment by GaucovyAero** [comment]
Removing the mods by half:
1. Remove half of the mods (including mods that depend on other mods from the first half)
2. If you don't crash, put in half of the mods you just removed, then continue adding up. If you do crash, remove half of the mods you have now.
3. Figure out which mod is causing the issue.

**Comment by MazTankaz** [comment]
> optifine, скорее всего, конфликтует с кучей модов, если у вас возникнут еще какие-либо конфликты, попробуйте удалить моды наполовину

The optifine is not installed in my build...

As for removing mods by half, I just didn't want to resort to this method, but I will have to. Thanks for the help!

**Comment by GaucovyAero** [comment]
> The optifine is not installed in my build...

it is, look
![image](https://github.com/user-attachments/assets/1088620e-7587-4c15-afc6-2d42370286db)
