### ISSUE TITLE
[BUG] rlcraft constantly crashing while playing

### ISSUE THREAD

**Issue by epicspacecat** [PojavLauncherTeam/PojavLauncher#6115]
### Describe the bug

It crashes every 2-8 minutes when im playing and prevents me from normal gameplay (btw i removed the mods not compatable with pojav) is there a way to remove these crashes or make them a little less common atleast? 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17179262/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select rlcraft
3. Click play
4. Wait for loading
5. Click play
6. Play for 2-8 minutes
7. Get crashed
```

### Expected Behavior

Playing with almost no crashes

### Platform

```markdown
- Device model: Huawei p40 lite 
- CPU architecture: arm64 
- Android version: 10 
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

Love if you will help me

**Comment by GaucovyAero** [comment]
remove enhancedvisuals and try messing with the ram allocation (give less memory to the game) i think you are having a memory leak

**Comment by epicspacecat** [comment]
> remove enhancedvisuals and try messing with the ram allocation (give less memory to the game) i think you are having a memory leak

Thank you! That helped a lot, i removed the mod and put ram usage on 2 gb and it helped!
