### ISSUE TITLE
[Zink (vulkan) Renderer crash]

### ISSUE THREAD

**Issue by system32crowdstrikewin11** [PojavLauncherTeam/PojavLauncher#6118]
### Describe the bug

So in this issue the vulkan and renderer simply crashes but if we look at previous 3 month it used to run smoothly but now vulkan renderer crashes 
Idk how this is happening
When my device was new it used to work properly I don't know what's the root cause of this issue maybe a software update or pojavlauncher bug
I would be glad if this issue is fixed or if not fixable then answered because this is my second time reporting the same bug but with different device

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17187415/latestlog.txt)

https://github.com/user-attachments/assets/95c1377e-e080-4030-922c-14c1fc78cf0c

### Steps To Reproduce

```markdown
1. Open pojavlauncher 
2. Select Zink(Vulkan) as renderer
3. Start the game
4. Game crashes after few seconds
```

### Expected Behavior

Simply launch the game and being able to play with shaders

### Platform

```markdown
- Device model: Poco X6 pro
- CPU architecture: x64 arm
- Android version: 14
- PojavLauncher version: foxglove-20240905-8c90b5 4-v3_openjdk
- GPU - Mali-G615 MC6
```

**Comment by system32crowdstrikewin11** [comment]
Here is the proof that shaders really used to work in my device
https://github.com/user-attachments/assets/e0d56ea4-406a-4025-8ad3-7c43223bb61c

**Comment by GaucovyAero** [comment]
# Zink doesn't work
If Zink worked for you before the `foxglove` update, this might get it running on your device. It doesn't help on devices which don't fulfill the base Zink requirements.

**/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt** 
(if this file does not exist, create it)

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```

**Comment by GaucovyAero** [comment]
cant really help if its caused by the zink update, because zink updates like any other thing

**Comment by WOOD6563** [comment]
Same issue with my mali g52 mc2

**Comment by Gannu5704Q** [comment]
_Gaucovy_ _Aero_ it work in pojav glow worm by enable render experiment you can install this version - **edelweiss-20230928-9484d0c- v3_openjdk** of pojav launcher in this Zink (Vulkan) work properly with a glitch of opening it open with grey screen then open

**Comment by KaydenJR2310** [comment]
Me also crash on my mali g72 idk why

**Comment by WOOD6563** [comment]
Then use old mesa or custome evn
