### ISSUE TITLE
[BUG] Help me please! Idk what i supposed to do

### ISSUE THREAD

**Issue by 1337Vlad228** [PojavLauncherTeam/PojavLauncher#612]
Video:
https://www.mediafire.com/file/t2g6d5jue42oerc/mobizen_20210114_201833.mp4/file
Model: Lenovo TB-X304L
CPU architecture: arm64
Android version: 7.1.1
I can't play in Minecraft.
Help me please!

**Comment by khanhduytran0** [comment]
Invalid java runtime.

**Comment by khanhduytran0** [comment]
What about using the 70mb apk instead of separate java runtime?

**Comment by 1337Vlad228** [comment]
> What about using the 70mb apk instead of separate java runtime?

This is 70mb apk in video. Idk what i supposed to do

**Comment by khanhduytran0** [comment]
70mb apk does not requires install java runtime manually. Clear app data and try again.

**Comment by khanhduytran0** [comment]
Also, maybe post logs instead of video.

**Comment by 1337Vlad228** [comment]
> 70mb apk does not requires install java runtime manually. Clear app data and try again.

Which data?

**Comment by 1337Vlad228** [comment]
> Also, maybe post logs instead of video.

That's it?
https://www.mediafire.com/file/3im3c1lhef7kfv8/ClientCorrelation2535461490087986.dat/file
It's from logs

**Comment by 1337Vlad228** [comment]
> > Also, maybe post logs instead of video.
> 
> That's it?
> https://www.mediafire.com/file/3im3c1lhef7kfv8/ClientCorrelation2535461490087986.dat/file

It's from logs

**Comment by khanhduytran0** [comment]
> https://www.mediafire.com

Doesn't GitHub has option to send files?

Also it does not looks like log.

**Comment by WesleyVanNeck** [comment]
> > https://www.mediafire.com
> 
> Doesn't GitHub has option to send files?
> 
> Also it does not looks like log.

yes it does have a option to upload logs

**Comment by khanhduytran0** [comment]
@1337Vlad228 If you don't see file attachment, just pick image attachment instead (but you can attach non-image)

**Comment by 1337Vlad228** [comment]
> @1337Vlad228 If you don't see file attachment, just pick image attachment instead (but you can attach non-image)

I don't understand

**Comment by khanhduytran0** [comment]
Are you on GitHub web or app?

**Comment by 1337Vlad228** [comment]
> Are you on GitHub web or app?

On web

**Comment by khanhduytran0** [comment]
Here is where you can upload any type of files.
![60418A46-D908-425D-AF85-D4E5FCB7A245](https://user-images.githubusercontent.com/40482367/104599511-77d7ea00-56aa-11eb-8288-e4a772152058.jpeg)

**Comment by 1337Vlad228** [comment]
> Here is where you can upload any type of files.
> ![60418A46-D908-425D-AF85-D4E5FCB7A245](https://user-images.githubusercontent.com/40482367/104599511-77d7ea00-56aa-11eb-8288-e4a772152058.jpeg)

What i supposed to do next? I know this button

**Comment by 1337Vlad228** [comment]
> Here is where you can upload any type of files.
> ![60418A46-D908-425D-AF85-D4E5FCB7A245](https://user-images.githubusercontent.com/40482367/104599511-77d7ea00-56aa-11eb-8288-e4a772152058.jpeg)

Let's meet here later. I'm going to bed because it's midnight

**Comment by khanhduytran0** [comment]
Then, pick the log file.

**Comment by 1337Vlad228** [comment]
> Then, pick the log file.

Hi, where i can find log file?

**Comment by khanhduytran0** [comment]
On `/sdcard/games/.minecraft/latestlog.txt`

Also, what about clearing app data?

**Comment by 1337Vlad228** [comment]
> On `/sdcard/games/.minecraft/latestlog.txt`
> 
> Also, what about clearing app data?

A have latestcrash.txt in .minecraft.
Where app data?

**Comment by khanhduytran0** [comment]
Go to **device** Settings -> App -> PojavLauncher -> Clear app data

**Comment by khanhduytran0** [comment]
(It's very likely that you are new to Android platform right?)

**Comment by 1337Vlad228** [comment]
> (It's very likely that you are new to Android platform right?)

No, I'm not new. Just i'm not professional programmer

**Comment by 1337Vlad228** [comment]
> Go to **device** Settings -> App -> PojavLauncher -> Clear app data

I'm cleared app data. What to do next?

**Comment by khanhduytran0** [comment]
Then launch again

**Comment by 1337Vlad228** [comment]
> Then launch again

It's not helped

**Comment by 1337Vlad228** [comment]
> Then launch again

Can we go to Discord?

**Comment by Mathias-Boulay** [comment]
Stale issue, such behaviors are no more with the google play version anyway.
Closing.
