### ISSUE TITLE
Connect texture issues with Continuity Mod

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#6120]
### Describe the bug

This bug has been out here for a long while. Happened in the "Haste" Modpack.
most of the resources pack required connect texture is quite buggy with grass and stone.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17192219/latestlog.txt)

![Screenshot_20240930-194215](https://github.com/user-attachments/assets/212bda4d-91a5-4970-90ed-f82e9332f158)
![Screenshot_2024-09-30-22-04-56-964_com discord](https://github.com/user-attachments/assets/bb8e47d4-1f20-4774-a713-c946522eda6b)

### Steps To Reproduce

```markdown
1. Install Haste modpack. Including Continuity mod
2. Download some resources pack required connect texture 
3. enter Minecraft world 
4. connect texture issues.
```

### Expected Behavior

rendering connect texture normally 

### Platform

```markdown
many device.
```

**Comment by TylerHaoNhot** [comment]
probably known issues

**Comment by artdeell** [comment]
Haste is not supported

пн, 30 сент. 2024 г., 18:15 TylerHaoNhot ***@***.***>:

**Comment by GaucovyAero** [comment]
wont fix
