### ISSUE TITLE
[BUG] <Short description>Zink crashing in Asus Rog Phone 6D (Dimensity)

### ISSUE THREAD

**Issue by gitmoono** [PojavLauncherTeam/PojavLauncher#6121]
### Describe the bug

When i join any version of the game with zink it have a instant crash, Asus rog phone 6D uses a Mediatek/Dimensity 9000+

### The log file and images/videos

.........

### Steps To Reproduce

```markdown
I open pojav
i enter in the configs 
i put zink
i put the memory to the nescesarry for shaders
i open Minecraft editor 
i put also zink
i open the game
it crash instantly
I can make a video doing it
```

### Expected Behavior

Please fix it i rlly love to play pojav

### Platform

```markdown
- Device model: Asus rog Phone 6D
- CPU architecture: Dimensity
- Android version: 14
- PojavLauncher version: Play store
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
# Zink doesn't work
If Zink worked for you before the `foxglove` update, this might get it running on your device. It doesn't help on devices which don't fulfill the base Zink requirements.

**/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt** 
(if this file does not exist, create it)

```
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
```
