### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by JagdishGAmra** [PojavLauncherTeam/PojavLauncher#6123]
### Is this request related to a bug?

Jagdish100k 

### Describe the request.

![Screenshot_20241001_075530](https://github.com/user-attachments/assets/3b540f74-d2aa-49c5-aeb1-56d067c1f3a0)

### Anything else?

![Screenshot_20241001_075521](https://github.com/user-attachments/assets/ea774ad3-eae8-436c-aee5-07692148d866)

**Comment by GaucovyAero** [comment]
do what it tells you to
