### ISSUE TITLE
[F-Req] ControlMap feature enchancements

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#6124]
### Is this request related to a bug?

no

### Describe the request.

So, i was making controls in Pojav (Im a ui designer), and my goal is to make it look like the new Roblox CoreGui. But, i wanted images in it and theres no way as of now for images. So i made this feature request. _Plus frames cuz using unnamed button as a workaround has the click highlight_. maybe highlight selected buttons also for good ui design and user experience?

Reference images :
![20241001_091123](https://github.com/user-attachments/assets/3aa32594-5208-4285-95c3-7eaec132a803)

![20241001_093444](https://github.com/user-attachments/assets/debb8c9a-c5f8-432a-adc9-a8a01cdcbd2c)

## 1. Image buttons
Currently, pojav saves the controlmap as a .json file, But to implement images, we would need to use a renamed .zip file. This would be easy or something as pojav already has extraction as it extracts the jre .tar.xz files. structure of the zip file:
```
Controlmap.<extension>
    | - images
    |     | - Image1.png/jpg/whatever
    | - layout.json
```
layout.json (imagebutton only for reference): 
```
{
    "image": "Image1.png/jpg/whatever";
    // Other properties inherited from button, except name
},
```
new property: image, directs to the imagename in the image directory.

also, there will be a new folder called controlmapImages in the same dir as Controlmap

## Importation steps (done by launcher's backend)
1. Extract the archive
2. If contains layout and image then continue else throw Unsupported file format
3. put all images from images and put it in controlmapImages with new name `${ArchiveNameNoExtension}_${imagename}`
4. put the layout file into the controlmap folder
5. rename layout file to the archive name with no extension

that concludes importation

### Anything else?

if this gets cancled its alright, but it will help with designing ui with good user experience

**Comment by Cube5x59999** [comment]
i forgot to mention abt frames

frames are just buttons which are not clickable, no name property and no keybinds.

**Comment by artdeell** [comment]
> i forgot to mention abt frames

just add a button with no set binds and an empty name?

**Comment by Cube5x59999** [comment]
> > i forgot to mention abt frames
> 
> just add a button with no set binds and an empty name?

it could be possible, but we get the annoying click highlight, maybe you could add a highlight toggle?

**Comment by GaucovyAero** [comment]
adding images is not going to be added because its a big performance hit
