### ISSUE TITLE
[BUG] which mods to remove for all the mods 9 (atm9) modpack to work? 

### ISSUE THREAD

**Issue by epicspacecat** [PojavLauncherTeam/PojavLauncher#6125]
### Describe the bug

When im starting the game it crashes somewhere in the loading the game, i tried launching the game without applied energistics 2 and some mods and it launched but i wasnt able to play because some mods were dependent on applied energistics 2 mod, but when i removed all mods that were dependent on applied energistics 2 it crashed again. I dont know which mods to remove for it to work, can anyone help me? That screenshot down here is last i see before crash. 

### The log file and images/videos

![Screenshot_20241001_153630_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/69580fb0-c97c-4fd7-b3f1-e65fed545f7c)
[latestlog.txt](https://github.com/user-attachments/files/17209497/latestlog.txt)

### Steps To Reproduce

```markdown
1. Remove applied energistics and its dependencies from mod folder
2. start PojavLauncher
3. Go to atm9
4. Click play
5. Wait a bit
6. Get crashed
```

### Expected Behavior

Launching minecraft correctly

### Platform

```markdown
- Device model: Huawei p40 lite 
- CPU architecture: arm64 
- Android version: 10 
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

I will love if you will help me!

**Comment by GaucovyAero** [comment]
corgilib requires an x86_64 PC
