### ISSUE TITLE
[F-Req] Please update ANGLE to a newer version for bug fixes and improvements, and also potentially performance improvements

### ISSUE THREAD

**Issue by mrjasonn** [PojavLauncherTeam/PojavLauncher#6128]
### Is this request related to a bug?

There may be many bugs with an older version, whilst a newer version may be more stable and potentially more performant.

### Describe the request.

Please update ANGLE to a newer version for bug fixes and improvements, and a potential performance increase. Potentially the Sodium mod might work properly if it is updated. I have created a pull request in the PojavLauncher custom ANGLE repository.

**Comment by artdeell** [comment]
ANGLE will be replaced

**Comment by mrjasonn** [comment]
> ANGLE will be replaced

Any ETA though? (for both iOS and Android) @artdeell

**Comment by kiokori-git** [comment]
> > ANGLE will be replaced
> 
> Any ETA though? (for both iOS and Android) @artdeell

no, no ETA, we're an unpaid team so yeah
and on iOS? we're still focusing on compatibility (like libraries and stuff), renderers are low priority atm.

**Comment by GaucovyAero** [comment]
no ETAs but its pretty close, not sure when its gonna be uploaded to play store tho, you can test the new renderer using the github actions builds
