### ISSUE TITLE
[BUG]FIX BACKGROUND NOISE

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#613]
So, here it is... 1 week ago I have to play minecraft with pojavlauncher using my earphone just to get the full experience.. and then when the game just start  I started here noise(not really loud but still).. So I though my earphone was broke and I decide to buy a new one(that cost much expensive.. And then when I tried again launching pojavlauncher and tap play wait for the loading... and I still here the noise(everytime any sound come the noise will straight come in non stop until I quit the game)) The only that I can make the noise lower down is by increasing my volume(I dont really like to open my volume so high)...So, for me it was really annoying... I hope you guys can fix this... Thanks

**Platform:**
 - Device Model [Vivo 4/64]
 - CPU architecture [aarch64] 
 - Android Version [9]

**Comment by khanhduytran0** [comment]
We have no idea to fix this... we used 3rd party audio implementation, maybe try to take a look at Minecraft audio settings?

**Comment by Adam0530** [comment]
> We have no idea to fix this... we used 3rd party audio implementation, maybe try to take a look at Minecraft audio settings?

What do you mean?

**Comment by khanhduytran0** [comment]
I mean 
![image](https://user-images.githubusercontent.com/40482367/104724223-f8f2b800-5762-11eb-9d03-e7867cc8cafd.png)

**Comment by Adam0530** [comment]
> I mean 
> ![image](https://user-images.githubusercontent.com/40482367/104724223-f8f2b800-5762-11eb-9d03-e7867cc8cafd.png)
> 

Oh, so what am I supposed to do? I am always to that setting just to lower down the sound or increasing the sound

**Comment by khanhduytran0** [comment]
Maybe maximum them, but device audio keep low.

**Comment by Mathias-Boulay** [comment]
@Adam0530 does the bug still happens with the google play version ?

**Comment by Mathias-Boulay** [comment]
Stale issue from an old version with no response from the creator of the issue.
Closing
