### ISSUE TITLE
[BUG] Pojav Crashing launching fabric on 1.21.1 even if I uninstall sodium

### ISSUE THREAD

**Issue by Justjaxkeryz** [PojavLauncherTeam/PojavLauncher#6132]
### Describe the bug

Help, I want to play fabric with my mods on 1.21.1 with fabric with the same version and even if I uninstall sodium It still is crashing, HELP!

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17254181/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the PojavLauncher WITH Fabric as the game to launch
2.Launch
3.Wait and have a log with Pojav Crashing
```

### Expected Behavior

To Play fabric.

### Platform

```markdown
- Device model: Samsung A25 5G
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by ghost** [comment]
If you installed iris mod delete it

**Comment by Justjaxkeryz** [comment]
No.

**Comment by Justjaxkeryz** [comment]
https://github.com/user-attachments/assets/c7150683-dbad-4130-83bc-1dc9ccc05aa5

Game crashes before it even loads

**Comment by GaucovyAero** [comment]
your fabric api is for 1.21.0 and you are using minecraft 1.21.1, fix that
