### ISSUE TITLE
[BUG] Optifabric 1.18.2 

### ISSUE THREAD

**Issue by asumy1** [PojavLauncherTeam/PojavLauncher#6135]
### Describe the bug

crash 

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/17256148/latest.log)
[crash-2024-10-04_14.52.20-client.txt](https://github.com/user-attachments/files/17256152/crash-2024-10-04_14.52.20-client.txt)
![Screenshot_20241004_145509_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/9db6ecb5-e0c1-48b2-a15b-08c3a0e1061f)
![Screenshot_20241004_145353_Chrome](https://github.com/user-attachments/assets/299d37c6-42b7-48f4-b318-2e70e5dc56cd)

### Steps To Reproduce

```markdown
1. Start pojav
2. crash
```

### Expected Behavior

please fix it

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: lastest
```

### Anything else?

a guy came and told use optifabric 1.14.3 and use fabric Loader 1.14.x I used 1.14.25 so I tried it crash

**Comment by asumy1** [comment]
@everyone @pojavsupport

**Comment by GaucovyAero** [comment]
fabric loader too old i think, try 0.15.x or 0.16.x, closing, also wrong logs, always send latestlog.txt, not latest.log, nor crash-xxx unless requested

**Comment by asumy1** [comment]
didn't work

**Comment by ghost** [comment]
You can try sodium with LTW renderer it's better than optifabric with holygl4es

**Comment by GaucovyAero** [comment]
> didn't work

## We don't know what doesn't work means

"Doesn't work" does not actually mean anything, explain more thoroughly. For example:

**Wrong:** My game crashes please help!11!1
**Correct:** After I installed OptiFine, my game crashes, here's the latestlog.txt. Please tell me which mod it's conflicting with.

**Wrong:** My resource pack doesn't show up!11!1
**Correct:** I installed a resource pack from (link) and I have no idea how to properly install it, it doesn't show up in-game. Do I leave it as a zip, extract it or what do I do? Here's a video of how it looks.

If you don't really know what you are doing, the best you can do is just send the log file (latestlog.txt), you don't have to say anything about it.
