### ISSUE TITLE
Unable to launch modpack

### ISSUE THREAD

**Issue by bassism** [PojavLauncherTeam/PojavLauncher#6136]
### Describe the bug

I am not able to launch the modpack Prominence 2 after installing it, it crashed after some time.
![Screenshot_2024-10-04-18-03-21-432_net kdt pojavlaunch-edit](https://github.com/user-attachments/assets/b23d6705-ed07-4db6-9904-41d54086f802)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17256627/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select Profile (Prominence 2 RPG Modpack)
3. Play.
```

### Expected Behavior

I expect my modpack prominence 2 to launch regardless of the performance

### Platform

```markdown
- Device model: Xiaomi 23043RP34G
- CPU architecture: arm64
- Android version: 14 UKQ1.230917.001
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by artdeell** [comment]
remove sodium

**Comment by bassism** [comment]
> remove sodium

would you roughly guide me on how to do that?

**Comment by GaucovyAero** [comment]
/storage/emulated/0/Android/data/net.kdt.pojavlaunch/custom_instances/your_modpack/mods/sodium-...
