### ISSUE TITLE
gl4es&snapshot version

### ISSUE THREAD

**Issue by RzdPai** [PojavLauncherTeam/PojavLauncher#6138]
### Is this request related to a bug?

no

### Describe the request.

gl4es is so old that it no longer runs the latest snapshot version.

### Anything else?

update gl4es

**Comment by CowSheep72** [comment]
use LTW for the time being

**Comment by RzdPai** [comment]
> use LTW for the time being

On my device, LargeThinWrapper still has a lot of problems and gl4es has been updated to 1.1.6 (and 1.1.7 snapshots) with OpenGL 3.3 support, while Pojav is still using gl4es 1.1.4 with OpenGL 2.1.

**Comment by Mathias-Boulay** [comment]
> > use LTW for the time being
> 
> On my device, LargeThinWrapper still has a lot of problems and gl4es has been updated to 1.1.6 (and 1.1.7 snapshots) with OpenGL 3.3 support, while Pojav is still using gl4es 1.1.4 with OpenGL 2.1.

False. We ship pretty much the latest gl4es version with our own set of modifications. Sadly, it seems like the new versions also introduced performance regressions.

**Comment by RzdPai** [comment]
> > > use LTW for the time being
> > 
> > On my device, LargeThinWrapper still has a lot of problems and gl4es has been updated to 1.1.6 (and 1.1.7 snapshots) with OpenGL 3.3 support, while Pojav is still using gl4es 1.1.4 with OpenGL 2.1.
> 
> False. We ship pretty much the latest gl4es version with our own set of modifications. Sadly, it seems like the new versions also introduced performance regressions.

It's also possible to add both versions of gl4es at the same time, as was done initially
