### ISSUE TITLE
About:renderer LTW

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#6140]
### Describe the bug

I don't know if this is a bug, I just want to know if this is a device problem or a renderer problem.

Describe：
When using the LTW renderer with any version of Minecraft (1.17+), the FPS is always 1. No matter which version(1.17+) I try, even with the Sodium Mod, the FPS remains 1.

### The log file and images/videos

Screen shot 1 :
![Screenshot_2024-10-05-13-07-04-951_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/80b9a377-9a90-4e43-a81b-0ccea9ab7246)

Log file 1 :
[latestlog.txt](https://github.com/user-attachments/files/17265291/latestlog.txt)
Screen shot 2 :
![Screenshot_2024-10-05-14-05-17-962_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/b48fc34e-1cd4-43fc-a723-35c84df78d37)
![Screenshot_2024-10-05-00-53-30-108_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/46133fae-f0b6-4536-9414-b47b55c9d84a)
Log file 2 :
[latestlog.txt](https://github.com/user-attachments/files/17265308/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start PojavLauncher on Redmi K30 Pro
2.Use LTW running any version
3.The FPS is always 1
```

### Expected Behavior

No

### Platform

```markdown
- Device model:Redmi K30 Pro 
- CPU architecture: aarch64
- Android version: Android 12
- PojavLauncher version: foxglove-20241004-14a0907-feat/tinywrapper
```

### Anything else?

No

**Comment by artdeell** [comment]
did you turn off mipmaps

**Comment by lzfddkd** [comment]
> did you turn off mipmaps

oh,it worked
