### ISSUE TITLE
2d Texture 1.12.2 optifine and forge

### ISSUE THREAD

**Issue by Enuma05** [PojavLauncherTeam/PojavLauncher#6141]
### Describe the bug

2d Texture in the all weapons and tools in Optifine and forge 1.12.2
![images (36)](https://github.com/user-attachments/assets/77a78ee0-fef1-4425-9a32-ff8b251f57ec)

### The log file and images/videos

![images (36)](https://github.com/user-attachments/assets/e7d35e1b-75c7-4c22-8542-6e10d8901039)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher 
2. Open 1.12.2 Forge 
3. Open A world and check the tools and weapon textures
```

### Expected Behavior

i expect that my weapon and tools will not be 2d Texture 

### Platform

```markdown
- Device model: infinix hot 11s nfc
- CPU architecture: helio g88
- Android version: 11
- PojavLauncher version: Crocus v3 openjdk
```

**Comment by artdeell** [comment]
Ceocus is super outdated. Update.

**Comment by GaucovyAero** [comment]
fixed in the latest update
