### ISSUE TITLE
x ray like texture

### ISSUE THREAD

**Issue by Enuma05** [PojavLauncherTeam/PojavLauncher#6142]
### Describe the bug

its like xray

### The log file and images/videos

![Screenshot_20241005-161024](https://github.com/user-attachments/assets/c7279819-0ab0-4c62-bef2-29b8e5fac8de)
![Screenshot_20241005-161018](https://github.com/user-attachments/assets/46499167-605d-42db-b21f-c80cec9f8029)
![Screenshot_20241005-161005](https://github.com/user-attachments/assets/832cc687-23b4-4867-88d4-c1a9df2ac1b5)
![Uploading Screenshot_20241005-161857.jpg…]()
![Uploading Screenshot_20241005-161844.jpg…]()

### Steps To Reproduce

```markdown
1.open PojavLauncher 
2. play 1.12.2 forge
3. open a world and see that bug
```

### Expected Behavior

i dont even know what to expect 

### Platform

```markdown
- Device model: infinx hot11s
- CPU architecture: helio g88
- Android version: 11
- PojavLauncher version: foxglove-20240922-ababa29-v3_openjdk
```

**Comment by CowSheep72** [comment]
send log

**Comment by Enuma05** [comment]
[Uploading latestlog.txt…]()

**Comment by Enuma05** [comment]
[latestlog.txt](https://github.com/user-attachments/files/17265630/latestlog.txt)

**Comment by GaucovyAero** [comment]
one or more mods is using shaders that gl4es cant handle, if you know which mod it is, you can try checking its config file to disable shaders or something else that might be causing your issue, if there isnt an option like that, you have to remove the mod thats causing you the issue
