### ISSUE TITLE
Black screen when staring game in newest snapshot 

### ISSUE THREAD

**Issue by LeadoffDoge** [PojavLauncherTeam/PojavLauncher#6143]
### Describe the bug

I'm getting a bug where the display isn't working in the newest snapshot in both the GitHub version and the Google play store version. I am using a note 10+

![Screenshot_20241003-073607_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/4feb1422-7770-417f-aeb1-ef4c2cfe6df8)

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240922-a6a6a29-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-N975U
Info: API version: 31
Info: Selected Minecraft version: 24w40a
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2280
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~qZKVUNutxv2Uy9gJArRRvg==/net.kdt.pojavlaunch-_YUQeThFgF0JMwHkVTeNHQ==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~qZKVUNutxv2Uy9gJArRRvg==/net.kdt.pojavlaunch-_YUQeThFgF0JMwHkVTeNHQ==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  (20192): dlopen libgl4es_114.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  (20192): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success
I/jrelog  (20192): dl
open /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjawt.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/librmi.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjavajpeg.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsctp.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libdt_socket.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjsig.so suc
cess
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2gss.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_ext.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_agent.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmlib_image.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjimage.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libinstrument.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.poj
avlaunch/runtimes/Internal-21/lib/libprefs.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjdwp.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjsig.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/liblcms.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2pkcs11.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libzip.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  (20192)
: dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsyslookup.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjaas.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libextnet.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success
I/jrelog  (20192): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_xawt.so success
I/jrelog  (20192): dlopen /data/app/~~qZKVUNutxv2Uy9gJArRRvg==/net.kdt.pojavlaunch-_YUQeThFgF0JMwHkVTeNHQ==/lib/arm64/libopenal.so success
I/jrelog  (20192): Done processing args
I/jrelog  (20192): Found JLI lib
I/jrelog  (20192): Calling JLI_Launch

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
  <log4j:Event logger="ac" timestamp="1728125482868" level="WARN" thread="main">
    <log4j:Message><![CDATA[Failed retrieving info for group processor]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~qZKVUNutxv2Uy9gJArRRvg==/net.kdt.pojavlaunch-_YUQeThFgF0JMwHkVTeNHQ==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230)
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at ac.c(SourceFile:79)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:79)
	at ac.e(SourceFile:56)
	at ac.a(SourceFile:87)
	at ac.<init>(SourceFile:56)
	at o.<init>(SourceFile:35)
	at o.g(SourceFile:234)
	at net.minecraft.client.main.Main.main(SourceFile:133)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="ac" timestamp="1728125482916" level="WARN" thread="main">
    <log4j:Message><![CDATA[Failed retrieving info for group memory]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60)
	at ac.a(SourceFile:81)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:81)
	at ac.e(SourceFile:56)
	at ac.a(SourceFile:87)
	at ac.<init>(SourceFile:56)
	at o.<init>(SourceFile:35)
	at o.g(SourceFile:234)
	at net.minecraft.client.main.Main.main(SourceFile:133)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~qZKVUNutxv2Uy9gJArRRvg==/net.kdt.pojavlaunch-_YUQeThFgF0JMwHkVTeNHQ==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230)
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at ac.c(SourceFile:79)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:79)
	... 6 more
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="com.mojang.datafixers.DataFixerBuilder" timestamp="1728125483293" level="INFO" thread="Datafixer Bootstrap">
    <log4j:Message><![CDATA[236 Datafixer optimizations took 547 milliseconds]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="amg" timestamp="1728125488579" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
  <log4j:Event logger="com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService" timestamp="1728125488941" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="flz" timestamp="1728125488970" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Setting user: LeadoffDoge]]></log4j:Message>
  </log4j:Event>
Registered forkAndExec
  <log4j:Event logger="fmd" timestamp="1728125489185" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Error parsing option value off for option Fullscreen: Not a boolean: "off"]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="flz" timestamp="1728125489208" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Backend library: LWJGL version 3.3.3-snapshot]]></log4j:Message>
  </log4j:Event>
EGLBridge: Binding to OpenGL ES
  <log4j:Event logger="amg" timestamp="1728125489278" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="amg" timestamp="1728125489689" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="avd" timestamp="1728125489849" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[Missing metadata in pack file/szejderujonc-lite.zip]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="amg" timestamp="1728125489987" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="com.mojang.text2speech.Narrator" timestamp="1728125490484" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Error while loading the narrator]]></log4j:Message>
    <log4j:Throwable><![CDATA[com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69)
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18)
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41)
	at flq.<init>(SourceFile:19)
	at flz.<init>(SourceFile:701)
	at net.minecraft.client.main.Main.main(SourceFile:248)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.N

### Steps To Reproduce

```markdown
1: Start game in new snapshot (24w40a)

2: Black screen will happen.
```

### Expected Behavior

Expected for display to work normally.

### Platform

```markdown
- Device model: Samsung Galaxy Note 10+ 
- Android version: 11 
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
duplicate of #5968

**Comment by LeadoffDoge** [comment]
Changing the render to ANGLE seems to work

**Comment by ghost** [comment]
> Changing the render to ANGLE seems to work

Or LTW renderer
