### ISSUE TITLE
[BUG] black screen with red strips while loading all the mods 9 (atm9) modpack

### ISSUE THREAD

**Issue by epicspacecat** [PojavLauncherTeam/PojavLauncher#6144]
### Describe the bug

When im loading all the mods 9 modpack its loading a bit then goes black screen at loading twilight forest files, i deleted the corgilib mod that is for pcs but it still wont load, maybe someone can recomend me more mods to remove or something. When i loaded the game first time after removing the corgilib mod (btw after installing it without opening the game i deleted it) it was loading like it should, then it black screened, then it showed me a screen with some rectangles then, after pressing somewhere it crashed. Then on second try i waited like 30 minutes on black screen, and nothing happened, and i closed the game, then on third time i waited 30 minutes then it crashed. Here are some screenshots and latestlog, i hope you will help me! 

### The log file and images/videos

![Screenshot_20241005_152731_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/ac22d1b9-a1d2-4126-b1a1-303a90136f8c)
![Screenshot_20241005_140747_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/4eae7ed3-7c76-4e54-89f8-8cf874bf396c)
[latestlog.txt](https://github.com/user-attachments/files/17266579/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Go to settings
3. Go to Java settings
4. Go to memory usage
5. Set to 2008
6. Go to Graphics Settings 
7. Change from Holy GL4ES to ANGLE
8. Go back
9. Click New profile
10. Modpacks
11. Find and click all the mods modpack
12. Click install
13. Wait for the download untill its done
14. Go to mods folder in the files manager
15. Remove corgilib mod
16. Go back to PojavLauncher
17. Go to all the mods 9
18. Click play
19. Wait for the loading
20. Get black screen with red strips
21. Get crashed
```

### Expected Behavior

Launching and playing minecraft

### Platform

```markdown
- Device model: Huawei p40 lite 
- CPU architecture: arm64 
- Android version: 10 
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

Nice if you will help me!

**Comment by GaucovyAero** [comment]
java.lang.OutOfMemoryError: Java heap space

cant really help with that

**Comment by epicspacecat** [comment]
> java.lang.OutOfMemoryError: Java heap space
> 
> cant really help with that

What that means? Not enough memory?

**Comment by epicspacecat** [comment]
> java.lang.OutOfMemoryError: Java heap space
> 
> cant really help with that

Will 2500 mb be enough?

**Comment by epicspacecat** [comment]
> java.lang.OutOfMemoryError: Java heap space
> 
> cant really help with that

What about now? I gave a little more memory and it gives me -1 error here is latestlog
[latestlog.txt](https://github.com/user-attachments/files/17266821/latestlog.txt)

**Comment by epicspacecat** [comment]
> java.lang.OutOfMemoryError: Java heap space
> 
> cant really help with that

There also one with Holy GL4ES it now worked but crashed check it please
[latestlog.txt](https://github.com/user-attachments/files/17266910/latestlog.txt)
