### ISSUE TITLE
[BUG] shaders on the S24 ultra dont work not even internal

### ISSUE THREAD

**Issue by DataShar** [PojavLauncherTeam/PojavLauncher#6145]
### Describe the bug

I have the s24 ultra but when i load shaders it either crashes or black screens and its strange that a phone this strong cant handle shaders

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/17267522/latest.log)

### Steps To Reproduce

```markdown
Load up minecraft apply shaders with the s24 ultra phone
```

### Expected Behavior

I expect at least chopaich 13 shaders to work

### Platform

```markdown
- Device model: s24 ultra
- CPU architecture: AARCH64 SDM8G3
- Android version: android 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3-openjdk
```

### Anything else?

No response

**Comment by GaucovyAero** [comment]
unofficial pojav version and + running shaders on gl4es is not possible

**Comment by DataShar** [comment]
What do you mean i have official pojav and i used all the renderer

**Comment by DataShar** [comment]
Can you atleast give me official pojav if not i dont have it and one shader that works on the S24 Ultra?
