### ISSUE TITLE
[BUG] crash after mojang screen

### ISSUE THREAD

**Issue by epicspacecat** [PojavLauncherTeam/PojavLauncher#6149]
### Describe the bug

Hello again! Im trying to play all the mods modpack (atm9) and its crashing after mojang screen with -1 error, i tried changing the memory to 2320, changing visualizer from ANGLE to Holy GL4ES and removing the corgilib mod and i think now its diffirent issue. Could you help me? 

### The log file and images/videos

![Screenshot_20241006_153712_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/6ae64ac0-9f99-423a-9884-9f228344ce1b)
[latestlog.txt](https://github.com/user-attachments/files/17269564/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Go to settings
3. Change memory usage from default to 2320
4. Go back
5. Go to profile
6. New profile
7. Modpacks
9 find all the mods 9 
modpack
10. Click download
11. Wait for the installation process 
12. Go to mods folder in the files manager
13. Remove corgilib mod
14. Go back to PojavLauncher
15. Click play
16. Wait a bit in the red screen
17. Wait a bit in the loading
18. Get crashed
```

### Expected Behavior

Launching minecraft

### Platform

```markdown
- Device model: Huawei p40 lite 
- CPU architecture: arm64 
- Android version: 10 
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

It would be awesome if you will help me!

**Comment by GaucovyAero** [comment]
```
Suppressed: java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
```
some mod idk which one requires a new opengl function that gl4es/angle doesnt support, cant help with that really

**Comment by casherka** [comment]
Use a ltw visualizer. 90% works!
