### ISSUE TITLE
[BUG] Can't find tinywrapper

### ISSUE THREAD

**Issue by zhangxixi2012** [PojavLauncherTeam/PojavLauncher#6150]
### Describe the bug

I have opened the latest pojavlauncher, but I cannot see the new renderer tinywraper.

### The log file and images/videos

![Screenshot_2024-10-07-12-52-55-463](https://github.com/user-attachments/assets/fb612aa2-bf29-4971-b8e9-3a65228dd697)

### Steps To Reproduce

```markdown
1.Open PojavLauncher
2.Can't find tinywrapper
```

### Expected Behavior

I hope to find and use tinywrapper

### Platform

```markdown
- Device model: Lenovo tb X606F
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: foxglove-20241006-68254e0-v3_openjdk
```

### Anything else?

Please solve this problem or contact me for a solution

**Comment by ghost** [comment]
Download this
![IMG_20241007_151213](https://github.com/user-attachments/assets/cd7d28e8-9780-4a21-8a94-3f4349c443ba)

**Comment by GaucovyAero** [comment]
its most likely the angle thing is just a bad translation, try launching the game and check the renderer in f3
if you want to fix the translation, go to https://crwd.in/pojavlauncher
