### ISSUE TITLE
[BUG] force close when use any mod

### ISSUE THREAD

**Issue by RatMeatball12** [PojavLauncherTeam/PojavLauncher#6151]
### Describe the bug

When I install the mod it will force close idk I have tried all the tutorials on YouTube and I have changed the forget version many times but it still doesn't work

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17278555/latestlog.txt)

### Steps To Reproduce

```markdown
When I play pojav without mod it doesn't fc but when I use mod it force close
```

### Expected Behavior

Keeps force closing no matter what I try

### Platform

```markdown
- Device model: 
- CPU architecture: Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55)
- Android version: 13
- PojavLauncher version: the lattest
```

**Comment by GaucovyAero** [comment]
# Installing any mod results in a crash
Please check the log file. In case you find yourself getting "Permission denied" on all of your files, please do not cut the mods, copy them instead.

**Comment by RatMeatball12** [comment]
I Will tray it
