### ISSUE TITLE
[F-Req] about LTW and sodium mod

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6152]
### Describe the request.

The new renderer actually is really good and satisfying but I have a question. you said sodium needs opengl es 3.1
![373847832-891a8012-6498-4ec0-bd50-c5c029fb9873](https://github.com/user-attachments/assets/a952e386-0bb5-42e6-b5cc-0965c13542fc)
 but tiny wrapper uses opengl es 3.0
![Screenshot_2024-10-07-16-54-50-982_net kdt pojavlaunch debug-edit](https://github.com/user-attachments/assets/9c86067f-c9b3-48a3-bf69-d8a169a921ed)
Why

**Comment by GaucovyAero** [comment]
OpenGL ES is what your phone runs on, LTW is translating your OpenGL ES to OpenGL 3.0. If your phone does not support GLES 3.1, Sodium will not run.

**Comment by tranthainguyen9620** [comment]
Да

**Comment by Samiul-XD** [comment]
Bro how
[latest.log](https://github.com/user-attachments/files/17991714/latest.log)

artDev, A piece of advice, If you can replace the zink renderer it will be just fine. Get back zink from (edelweiss-20230927-5d010fc-v3_openjdk)

¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by Marshall2439** [comment]
Zink now is just better. It doesn't work on some devices; doesn't mean it's bad. Also ltw renderer exists
