### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Itshanz659** [PojavLauncherTeam/PojavLauncher#6155]
### Describe the bug

Why cant use

### The log file and images/videos

😒😒

### Steps To Reproduce

```markdown
😒😒
```

### Expected Behavior

😒😒

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No

**Comment by ghost** [comment]
Scam
