### ISSUE TITLE
(issue fixed).    [BUG] [LWJGL] [ERROR] Incompatible Java and native library verison detected and hud is missing

### ISSUE THREAD

**Issue by Nymnya** [PojavLauncherTeam/PojavLauncher#6156]
### Describe the bug

I have been facing this glitch for quite a while now and for some stupid reason hud is missing. f1 is not working its bit strange. any help will be appreciated and. here my latest log
[latest.log](https://github.com/user-attachments/files/17292945/latest.log)

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

> 

### Platform

```markdown
- Device model: redmi a9
- CPU architecture: 8x arm cortex-A53
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

No.

**Comment by artdeell** [comment]
Wrong log. Use the "Share log file" button on the main screen of the launcher.

**Comment by Nymnya** [comment]
Hmm

**Comment by Nymnya** [comment]
[latestlog.txt](https://github.com/user-attachments/files/17293218/latestlog.txt)
Here's that log file

**Comment by Nymnya** [comment]
Btw i have tried this jvm text but it didn't work
-Dloader.disable_forked_guis=true

**Comment by GaucovyAero** [comment]
duplicate of #6086

**Comment by Nymnya** [comment]
Hmm what?
