### ISSUE TITLE
[BUG] <failed to install forge>

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#6157]
### Describe the bug

I can't install forge, through the built-in installer, the game crashes with code 17)). I launched it on jre8

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17297048/latestlog.txt)

### Steps To Reproduce

```markdown
1. Install forge 1.20.1 47.3.7
2. Get crash with code 17
```

### Expected Behavior

No

### Platform

```markdown
- Device model: samsung s10
- CPU architecture: ex9820
- Android version: 12
- PojavLauncher version: foxglove latest
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
use java 17, not a pojav issue

**Comment by Faked4075** [comment]
> use java 17, not a pojav issue

it still didn't help, but the loading took longer.
[latestlog.txt](https://github.com/user-attachments/files/17300713/latestlog.txt)
