### ISSUE TITLE
[BUG] game crash 

### ISSUE THREAD

**Issue by dododuck1** [PojavLauncherTeam/PojavLauncher#6160]
### Describe the bug

Clash 
[latestlog.txt](https://github.com/user-attachments/files/17325372/latestlog.txt)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17325376/latestlog.txt)

### Steps To Reproduce

```markdown
I don't know
```

### Expected Behavior

I don't know 

### Platform

```markdown
- Device model: Redmi12C
- CPU architecture: Mediatek Helio G85 
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
# My mods don't show up in-game
1. Please check the log file. In case you find yourself getting "Permission denied" on all of your files, please do not cut the mods, copy them instead.
2. If a custom path is set in Profile options (pencil button), make sure your mods are in your custom path.
