### ISSUE TITLE
Pre-test LTW render compatibility issue with the same device but different rom.

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#6161]
### Describe the bug

Me and my friend are using Redmi k20 Pro. He's using evolution X android 13. mine is original android 11 miui rom.
I tested out the new pre-test build and using the new LTW render. it's work. but my friend had some incompatibility issues and got -1 error after joining a world (it doesn't crash immediately, after 1-2 second instead.)

### The log file and images/videos

had this error as well:
![Messenger_creation_9953B7EA-F5B6-437C-82BC-14C3AE5C9CD9](https://github.com/user-attachments/assets/1fac94d5-7bbe-4f49-b932-e43645b2371a)

he's busy now so he can't send me the log now. but when he's available, I'll sent it asap as a comment below.

### Steps To Reproduce

```markdown
1 start pojav
2 use the new render 
3 join 1.21 sodium version.
4 got incompatible gpu message.
5 got into the game, click multiplayer/single player
6 join a server/world
7 it got in for a few seconds, but soonly crash with the -1 error
```

### Expected Behavior

fix this error

### Platform

```markdown
- Device model: Redmi k20 pro
- CPU architecture: arm64
- Android version: 11 miui & 13 asop
- PojavLauncher version: pre-test ltw
```

**Comment by Bel69420** [comment]
Well this is normal because your GPU (Adreno GPUs) is not capable of rendering 7 chunks distance without Sodium.

**Comment by Bel69420** [comment]
This was caused by the GPU driver

**Comment by TylerHaoNhot** [comment]
> This was caused by the GPU driver

but it's weird. my friends are using the same phone as mine, but he's facing this problem, while I don't

**Comment by AverageMinecraftuser** [comment]
> > This was caused by the GPU driver
> 
> but it's weird. my friends are using the same phone as mine, but he's facing this problem, while I don't

Just make it lower than 7 chunks or use sodium

**Comment by TylerHaoNhot** [comment]
> > > This was caused by the GPU driver
> > 
> > but it's weird. my friends are using the same phone as mine, but he's facing this problem, while I don't
> 
> Just make it lower than 7 chunks or use sodium 

in the bug report, I already reproduce that he's using 1.21 sodium.

**Comment by TylerHaoNhot** [comment]
update: 
log here: https://drive.google.com/file/d/17LUNW-CGaZRaPKIn2uzL7EFGf0m5yztP/view?usp=drivesdk

**Comment by GaucovyAero** [comment]
its crashing because of xaeros
