### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by NihallHush** [PojavLauncherTeam/PojavLauncher#6162]
### Describe the bug

it says permission denied whenever i add a new mod in fabric pojab
[latest.log](https://github.com/user-attachments/files/17332089/latest.log)

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Vivo V30
- CPU architecture: 
- Android version: 14
- PojavLauncher version: last
```

### Anything else?

i said all

**Comment by GaucovyAero** [comment]
# My mods don't show up in-game
1. Please check the log file. In case you find yourself getting "Permission denied" on all of your files, please do not cut the mods, copy them instead.
2. If a custom path is set in Profile options (pencil button), make sure your mods are in your custom path.
