### ISSUE TITLE
[BUG] LTW does not have Inventory and Crosshair

### ISSUE THREAD

**Issue by zhangxixi2012** [PojavLauncherTeam/PojavLauncher#6165]
### Describe the bug

LTW does not have Inventory and Crosshair

### The log file and images/videos

![Screenshot_2024-10-09-13-05-32-220](https://github.com/user-attachments/assets/0b52d973-aaa0-40cc-9c84-1955f3f2c0a5)

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.click***start game***
3.click***Single play***
4.click***new world***
5.LTW does not have Inventory and Crosshair
```

### Expected Behavior

I hope to have Crosshair and Inventory when using LTW

### Platform

```markdown
- Device model: Lenovo tb X606F
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: foxglove-20241004-14a0907-feat/tinywrapper
```

### Anything else?

Please solve this problem or tell me the solution (please do not recommend Optifine). I have always had high expectations for LTW and kindly request that you solve this problem，thanks

**Comment by zhangxixi2012** [comment]
[latest.log](https://github.com/user-attachments/files/17348823/latest.log)
This is a log

**Comment by zhangxixi2012** [comment]
This is a log
[latest.log](https://github.com/user-attachments/files/17348826/latest.log)

**Comment by Bel69420** [comment]
Ah yes, this is clearly PowerVR GPU driver bug. Since LTW uses OpenGLES like GL4ES but instead of 2.x it uses OpenGLES 3.x which mean you need an optifine to fix this.

**Comment by zhangxixi2012** [comment]
我的是OpenGL ES 3.2

**Comment by zhangxixi2012** [comment]
Sincerely request that you solve this problem

**Comment by VenomousSteam81** [comment]
> Sincerely request that you solve this problem

try using optifine like @Mario191209 suggested

**Comment by zhangxixi2012** [comment]
Can I not use Optifine?

**Comment by zhangxixi2012** [comment]
Can we not use Optifine? Because I want to use sodium

**Comment by zhangxixi2012** [comment]
I used optifine and enabled 2 * antialiasing, But this will make the game too laggy

**Comment by zhangxixi2012** [comment]
Can make LTW backward compatible with my device?

**Comment by GaucovyAero** [comment]
> I used optifine and enabled 2 * antialiasing, But this will make the game too laggy

at least we know that this works, good

**Comment by DITYE123** [comment]
fuck!

**Comment by GaucovyAero** [comment]
closing for now, has to be tested again when LTW goes back into testing
