### ISSUE TITLE
Auto crash when minimize the screen

### ISSUE THREAD

**Issue by Renerosal01234** [PojavLauncherTeam/PojavLauncher#6166]
### Describe the bug

When minimize the screen the Pojavlauncher close using LTW Render 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17348944/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the Pojavlauncher 
2. Minimize the screen 
3. Pojavlauncher auto close
```

### Expected Behavior

Help

### Platform

```markdown
- Device model: Poco c65 
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: latest GitHub
```

**Comment by zjkhuan9** [comment]
P

**Comment by emma727272** [comment]
- Device model: Poco c65 
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: latest GitHub

**Comment by emma727272** [comment]
1. Start the Pojavlauncher 
2. Minimize the screen 
3. Pojavlauncher auto close

**Comment by GaucovyAero** [comment]
disable earlyWindowControl in the forge config file, for normal forge, its in .minecraft/config/fml.toml, dunno whats the location for neoforge

**Comment by Renerosal01234** [comment]
> disable earlyWindowControl in the forge config file, for normal forge, its in .minecraft/config/fml.toml, dunno whats the location for neoforge

But I using neoforge

**Comment by GaucovyAero** [comment]
> > disable earlyWindowControl in the forge config file, for normal forge, its in .minecraft/config/fml.toml, dunno whats the location for neoforge
> 
> But I using neoforge

figure out the location for yourself
