### ISSUE TITLE
[BUG] Optifabric Red Screen

### ISSUE THREAD

**Issue by Pityciuu** [PojavLauncherTeam/PojavLauncher#6167]
### Describe the bug

I just installed Optifabric ( 1.21.1 ) then when I opened the Optifabric the screen just went red

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17349764/latestlog.txt)
![Screenshot_20241012-184614](https://github.com/user-attachments/assets/d911b540-9f37-4d26-b00c-0a6966128c20)

### Steps To Reproduce

```markdown
1. Download Optifabric ( 1.21.1 )
2. Open the Optifabric 
3. Wait a second then the game went red
```

### Expected Behavior

I expected that the red screen would be fix

### Platform

```markdown
- Device model: Infinix Smart 8 
- CPU architecture: Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55)
- Android version: Android 13
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

Nope.

**Comment by Dani7412** [comment]
Mera problem

**Comment by Pityciuu** [comment]
@Dani7412 could you explain what's mera? and how to fix it?

**Comment by Minecraftdestroyer12** [comment]
I think Mera means (my) in hindi

**Comment by Minecraftdestroyer12** [comment]
Hmm, you're red screen problem is related to More Culling mod, try disabling it,

**Comment by Pityciuu** [comment]
@Minecraftdestroyer12 I don't have more culling mod doesn't know that mod too

**Comment by Minecraftdestroyer12** [comment]
Hmm interesting

**Comment by Minecraftdestroyer12** [comment]
You have to find what mod is causing this glitch

**Comment by Minecraftdestroyer12** [comment]
Try deleting mods 1 by 1 to see which mod is causing problems

**Comment by Pityciuu** [comment]
I don't use any mod yet i try putting fabric api yet still the same with/without the red screen still appear have you tried Optifabric?

**Comment by Minecraftdestroyer12** [comment]
Yeah I have tried optifabic but  it sucks

**Comment by Minecraftdestroyer12** [comment]
I get like 30to20 fps in optifabic in sodium I get like 90to80 fps

**Comment by Pityciuu** [comment]
do you have the link of sodium also if there's dependencies could you please pass it to me I'll try to use it

**Comment by Minecraftdestroyer12** [comment]
Here's the link https://modrinth.com/modpack/plo
https://modrinth.com/mod/sodium/versions

**Comment by ghost** [comment]
Try with LTW renderer

**Comment by Pityciuu** [comment]
@kasrarouhi I'm not familiar with LTW randerw do you have link?

**Comment by Marshall2439** [comment]
> @kasrarouhi I'm not familiar with LTW randerw do you have link?

Download from actions tab

**Comment by ghost** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/11180313158
Download link

**Comment by Marshall2439** [comment]
> Mera problem

world isn't just india bro speak english here fr

**Comment by Pityciuu** [comment]
@kasrarouhi still the same even though i switch launcher

**Comment by Marshall2439** [comment]
Optifiabric is broken

**Comment by ghost** [comment]
I recommend use LTW renderer with sodium not optifabric

**Comment by GaucovyAero** [comment]
nothing obvious in the log, cant help
