### ISSUE TITLE
[F-Req] pojavlauncher really need a inbuilt screen recorder 

### ISSUE THREAD

**Issue by Nymnya** [PojavLauncherTeam/PojavLauncher#6168]
### Is this request related to a bug?

Can you guys add a screen recorder to pojavlauncher? I mean everyone will be happy

### Describe the request.

no need

### Anything else?

nope

**Comment by Minecraftdestroyer12** [comment]
Did your hud not rendering glitch fixed?

**Comment by Minecraftdestroyer12** [comment]
Did my trick worked?

**Comment by Nymnya** [comment]
Yep it got fixed. thx to your trick
Btw the mathod you show me was really crazy hahaha lol

**Comment by Minecraftdestroyer12** [comment]
Bye bye seeya

**Comment by Nymnya** [comment]
Bye bye! I won't forget your help and you

**Comment by TylerHaoNhot** [comment]
> Yep it got fixed. thx to your trick Btw the mathod you show me was really crazy hahaha lol

yo what's the trick? I wanna know it. since pojav is taking my ram too much that I can't run screen recorder

**Comment by Nymnya** [comment]
Thats trick about hud not rendering glitch fix

**Comment by Nymnya** [comment]
Ohh you also facing the same problem about screen recorder?

**Comment by TylerHaoNhot** [comment]
> Ohh you also facing the same problem about screen recorder?

ahh i guess i don't faced that problem then. but anyway, I'd like to have in-built screen recorder 😀

**Comment by Minecraftdestroyer12** [comment]
Well having screen recorder inbuilt in pojavlauncher will help the community to grow,
Because Xiaomi got the worst ram management system ever,
Bro you can't even run more then 1 app in the background
