### ISSUE TITLE
[BUG] Shift button not working in inventory

### ISSUE THREAD

**Issue by Qmgamerzyt** [PojavLauncherTeam/PojavLauncher#6171]
### Describe the bug

I was trying to add items in inventory instantly but _shift button not working._

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
1. Open any chest
2. Hold shift and type pri/left button to move items instantly
(Shift button not work) Items never move.
```

### Expected Behavior

..... 

### Platform

```markdown
- Device model: infinix s4
- CPU architecture: 8x ARM Cortex-A53 @ 2.00 GHz
- Android version: 9
- PojavLauncher version: foxglove-20241013-6474015-v3_openjdk
```

### Anything else?

Fix this or provide me any old version in which this work properly.

**Comment by GaucovyAero** [comment]
cant reproduce, works fine for me, its likely caused by your mods
