### ISSUE TITLE
[bug] <Short description>

### ISSUE THREAD

**Issue by BAUTISTA2011-droid** [PojavLauncherTeam/PojavLauncher#6175]
### Describe the bug

No me deja hacer me una cuenta 

### The log file and images/videos

No como jugar 

### Steps To Reproduce

```markdown
Ayudaaa
```

### Expected Behavior

Quiero jugar pero me salta una problema 

### Platform

```markdown
- Device model: moto e22 
- CPU architecture: 4
- Android version: 12
- PojavLauncher version: 1.20
```

### Anything else?

No me deja hacer me una cuenta

**Comment by whatswronglol4** [comment]
so when i log in on Microsoft acc, it says i need to log in on minecraft.net but I already did it, I tried it multiple times it didn't work, why?

**Comment by whatswronglol4** [comment]
- Device model: HONOR 90
- CPU architecture: what's that?
- Android version: 14
- PojavLauncher version: 1.21.1

**Comment by GaucovyAero** [comment]
invalid, fill the template

**Comment by whatswronglol4** [comment]
> invalid, fill the template

which one?

**Comment by whatswronglol4** [comment]
> invalid, fill the template

What template? Because I can't find it
