### ISSUE TITLE
[BUG] Oneconfig doesn't work

### ISSUE THREAD

**Issue by Slixxthedev** [PojavLauncherTeam/PojavLauncher#6177]
### Describe the bug

It just won't load, and if it loads (assuming only oneconfig is the mod running) it will crash upon joining world, furthermore disabling VBO in settings will allow you to load into the world but when you go on opening the GUI of the mod, it will just straight up crash without any crash log (kicks you out of the app).

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17431893/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Load the version Skyclient or forge with oneconfig
3. Crash as stated above
```

### Expected Behavior

Expected the game to run normally.

### Platform

```markdown
- Device model: Redmi Note 12 5G (sunstone)
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

Seems like having the minimal of the mods allows you to get into the game but it still crashes upon opening the GUI of Oneconfig, might be a render issue but would like to have this fixed if possible in the newer updates

**Comment by Slixxthedev** [comment]
Here is the crash report from the game:
[crash-2024-10-18_14.43.08-client.txt](https://github.com/user-attachments/files/17432031/crash-2024-10-18_14.43.08-client.txt)

**Comment by GaucovyAero** [comment]
# How to make OneConfig work on PojavLauncher with minimal lag 
### Thanks to JellyLab and littleone24_ for bringing this option to our attention and Wyvest for even attempting to support us in the first place

Requirements: 
    At least on PojavLauncher Edelweisse/Playstore Release
    (Optional) Device is capable of using Zink (Note: this hasn't been tested on iOS yet, someone please test it)

* Launch OneConfig or mod using OneConfig. __***It will crash on first time launch, that's okay.***__
* Set `updatechannel` to 1 in `.minecraft/OneConfig/OneConfig.json` and `.minecraft/OneConfig/Preferences.json`
* Set `enableBlur` to 0 in `.minecraft/OneConfig/Preferences.json` (Optionally, disable all animations as well)
* Use Zink renderer (or HolyGL4ES)
* Set Optifine Antialiasing to Off in Video Settings (Only if using Optifine)

**Known Bugs**
* Scroll bar is misaligned slightly to the right of the actual GUI

__***Important***__
Mods that use OneConfig will work on HolyGL4ES. But you cannot open the OneConfig menu or else it will crash. If you have a startup crash, just go to another app while Minecraft loads in.
__***Important***__
