### ISSUE TITLE
I am getting application/game ended with code 1

### ISSUE THREAD

**Issue by CrazyKieran19** [PojavLauncherTeam/PojavLauncher#6178]
### Describe the bug

I am trying to load create but I wont let me in version 1.20.1

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17435914/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. launch 1.20.1 fabric
3.crash
```

### Expected Behavior

I expect to play create mod

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

I have the mod jar in the mods folder

**Comment by CrazyKieran19** [comment]
HELP

**Comment by CrazyKieran19** [comment]
I am trying to use create

**Comment by GaucovyAero** [comment]
read the log, the solution is listed in there
