### ISSUE TITLE
[BUG]In previous versions, 1.7.10nei was available, but not in the latest version And there is a problem with the installer that cannot be installed 

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#618]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Possibly outdated latest

**Comment by T-CATHOME** [comment]
@ @artdeell No, it's not. It's the latest

**Comment by khanhduytran0** [comment]
So, give us full version name installed.

**Comment by T-CATHOME** [comment]
@khanhduytran0 I'm using the latest version of actions.

**Comment by khanhduytran0** [comment]
> full version name
There's no version named "the latest version of actions"

> [latest](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/490976561)
