### ISSUE TITLE
*Bug: Error code 1 Pojav

### ISSUE THREAD

**Issue by jeferson412** [PojavLauncherTeam/PojavLauncher#6180]
### Describe the bug

*App crahs because a error code 1 apear*
[latestlog.txt](https://github.com/user-attachments/files/17447497/latestlog.txt)

### The log file and images/videos

no

### Steps To Reproduce

```markdown
*I open it, put the mods already with Forge and it gives error 1*
```

### Expected Behavior

*open and play*

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

*no*

**Comment by GaucovyAero** [comment]
use java 8
