### ISSUE TITLE
don't play 1.20.1 forge

### ISSUE THREAD

**Issue by ssbtt** [PojavLauncherTeam/PojavLauncher#6181]
### Describe the bug

Error reported when playing 1,20.1forge

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: 1.3.5.1 (9941117)
Info: Architecture: arm64
Info: Device model: OPPO PDBM00
Info: API version: 28
Info: Selected Minecraft version: 1.20.1-forge-47.3.11
Info: Custom Java arguments: "-Dsodium.checks.issue2561=true"
Info: Java Runtime: Internal-17
--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.zh/cache
Added custom env: AWTSTUB_WIDTH=1544
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch.zh-FcwxHcWW6RRZrtWVBffI4Q==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.zh/cache
Added custom env: HOME=/storage/emulated/0/games/PojavZenithHorizon
Added custom env: PATH=/data/app/net.kdt.pojavlaunch.ffmpeg-7pBMz61okk6YfGVv-Qaaxw==/lib/arm64:/data/app/net.kdt.pojavlaunch.ffmpeg-7pBMz61okk6YfGVv-Qaaxw==/lib/arm64:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/app/net.kdt.pojavlaunch.ffmpeg-7pBMz61okk6YfGVv-Qaaxw==/lib/arm64:/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch.zh-FcwxHcWW6RRZrtWVBffI4Q==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=720
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_OES_fragment_precision_high  detected and used
Extension GL_EXT_shader_texture_lod detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 4096
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 2
Hardware vendor is Imagination Technologies
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  (16632): dlopen libgl4es_114.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (16632): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjaas.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjimage.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement_agent.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/librmi.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libzip.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libsctp.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (16632): dlopen /data/app/net.kdt.pojavlaunch.zh-FcwxHcWW6RRZrtWVBffI4Q==/lib/arm64/libopenal.so success

I/jrelog  (16632): Done processing args

I/jrelog  (16632): Found JLI lib
I/jrelog  (16632): Calling JLI_Launch

Exception in thread "main" java.lang.module.ResolutionException: Module lwjgl.glfw.classes contains package org.lwjgl.util.tinyfd, module org.lwjgl.tinyfd exports package org.lwjgl.util.tinyfd to lwjgl.glfw.classes
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:807)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:755)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:129)
Java Exit code: 1
I/jrelog  (16632): Going to free args
I/jrelog  (16632): Free done

--------- beginning of system

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

--------- beginning of main

read: unexpected EOF!

ERROR: Unable to get more Logging.

### Steps To Reproduce

```markdown
1setting java for 17
2 setting holy
3 start
```

### Expected Behavior

can use 1.20.1forge

### Platform

```markdown
- Device model: oppo A8
- CPU architecture: mtk p35
- Android version: 9
- PojavLauncher version: dahlia-20230813-5e8842b-v3_openjdk)
```

### Anything else?

logs:
--------- beginning with launcher debug
Info: Launcher version: 1.3.5.1 (9941117)
Info: Architecture: arm64
Info: Device model: OPPO PDBM00
Info: API version: 28
Info: Selected Minecraft version: 1.20.1-forge-47.3.11
Info: Custom Java arguments: "-Dsodium.checks.issue2561=true"
Info: Java Runtime: Internal-17
--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.zh/cache
Added custom env: AWTSTUB_WIDTH=1544
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch.zh-FcwxHcWW6RRZrtWVBffI4Q==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.zh/cache
Added custom env: HOME=/storage/emulated/0/games/PojavZenithHorizon
Added custom env: PATH=/data/app/net.kdt.pojavlaunch.ffmpeg-7pBMz61okk6YfGVv-Qaaxw==/lib/arm64:/data/app/net.kdt.pojavlaunch.ffmpeg-7pBMz61okk6YfGVv-Qaaxw==/lib/arm64:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/app/net.kdt.pojavlaunch.ffmpeg-7pBMz61okk6YfGVv-Qaaxw==/lib/arm64:/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch.zh-FcwxHcWW6RRZrtWVBffI4Q==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=720
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_OES_fragment_precision_high  detected and used
Extension GL_EXT_shader_texture_lod detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 4096
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 2
Hardware vendor is Imagination Technologies
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  (16632): dlopen libgl4es_114.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (16632): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (16632): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (16632): dlopen /d

**Comment by GaucovyAero** [comment]
custom builds of pojav are not supported
