### ISSUE TITLE
[BUG] <Short description>minecraft 1.21 blocks are not visible and i can't move

### ISSUE THREAD

**Issue by Yasin365026** [PojavLauncherTeam/PojavLauncher#6183]
### Describe the bug

When I want to enter the servers in minecraft on pojavlauncher, it enters the server but no blocks are visible and I cannot move. I can only see water, lava, signs, lantern lights, chests and players.

### The log file and images/videos

![Screenshot_2024-10-19-17-40-44-153_net kdt pojavlaunch](https://github.com/user-attachments/assets/a0886542-7dc3-46a8-a4bc-3cc6aa54c962)
![Screenshot_2024-10-18-21-47-10-953_net kdt pojavlaunch](https://github.com/user-attachments/assets/e3403472-cffb-40f7-9f16-9c7eb21866fc)

### Steps To Reproduce

```markdown
I enter pojavlauncher, select optifine version 1.21.1, enter the game, then when I enter any of the servers, this happens
```

### Expected Behavior

I want to be able to play comfortably on any server I want on pojavlauncher

### Platform

```markdown
- Device model: redmi 6
- CPU architecture: ARMv8-A
- Android version: 9
- PojavLauncher version: 1.21.1
```

**Comment by GaucovyAero** [comment]
most likely caused by custom shaders on the server's side
