### ISSUE TITLE
Cant start DJ 2

### ISSUE THREAD

**Issue by Dragonwoolf** [PojavLauncherTeam/PojavLauncher#6186]
### Describe the bug

When running the build, the launcher crashes without an error. I am attaching the log file. What could be the problem? 
https://pastebin.com/8QNcEFZw

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1.Instal DJ 2
2. Remove Random Patches
3. Start
```

### Expected Behavior

.

### Platform

```markdown
- Device model: poco f4 gt
- CPU architecture: 8 gen 1
- Android version: latest
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
try removing the mods half by half and figure out which mod is causing this, then report the not-working mod in another issue
