### ISSUE TITLE
LTW Render texture glitch 

### ISSUE THREAD

**Issue by Renerosal01234** [PojavLauncherTeam/PojavLauncher#6187]
### Describe the bug

LTW Render texture glitch on create mod

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Create world 
3. Place create item 
4. Glitch texture
```

### Expected Behavior

Plss fix

### Platform

```markdown
- Device model: Poco c65 
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: latest update on GitHub
```

### Anything else?

Plss update

**Comment by Faked4075** [comment]
Disable flywheel backend. Config/flywheel.json - and edit flysheel backend = OFF

**Comment by Marshall2439** [comment]
or just do /flywheel backend off in chat
