### ISSUE TITLE
[BUG] Crashing because of mods

### ISSUE THREAD

**Issue by Watche4-1** [PojavLauncherTeam/PojavLauncher#6188]
### Describe the bug

Whenever I put any mod in my mod folder when I try to play pojav with any mod loader it crashes and goes to the homescreen I tried with every version of the mod loader

### The log file and images/videos

The Files app prevents me to give any txt or logs

### Steps To Reproduce

```markdown
1. Put any mod in the mod folder
2. Use any mod loader, I used fabric
3. Start the game
4. Crash and get sent back to homescreen
```

### Expected Behavior

The mods work and smooth gameplay

### Platform

```markdown
- Device model: 23106RN0DA
- CPU architecture: MediaTek Helio G85 Octa-core Max 2.00Ghz
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

That's all

**Comment by artdeell** [comment]
we cant diagnose without a log, use the "share log file" button

**Comment by Watche4-1** [comment]
> we cant diagnose without a log, use the "share log file" button

![latestlog.txt](https://github.com/user-attachments/files/17474357/latestlog.txt)

**Comment by Watche4-1** [comment]
> we cant diagnose without a log, use the "share log file" button

@artdeell can you fix the problem I sent the latest log here

**Comment by Watche4-1** [comment]
@GaucovyAero Pls Help

**Comment by miggythewriter** [comment]
> @GaucovyAero Pls Help

This is so easy to fix 😑

**Comment by artdeell** [comment]
> > we cant diagnose without a log, use the "share log file" button
> 
> @artdeell can you fix the problem I sent the latest log here

![image](https://github.com/user-attachments/assets/53fe0483-bc92-4e8f-8e21-a8571dc357fd)
it literally tells you what the problem is
you are running minecraft 1.21.2 which is not supported by your mods, and also you forgot to install fabric api, and distant horizons is not (yet) supported by pojav so remove it

**Comment by Watche4-1** [comment]
My bad, I saw distant horizons run on pojav which I saw in youtube

**Comment by ghost** [comment]
> My bad, I saw distant horizons run on pojav which I saw in youtube

It's kinda true
![374187883-a952e386-0bb5-42e6-b5cc-0965c13542fc](https://github.com/user-attachments/assets/a1031cba-41e5-4cc5-a429-4fdfe9d70a35)
But with LTW renderer
