### ISSUE TITLE
[BUG] Game render as a transparent Window

### ISSUE THREAD

**Issue by Aom92** [PojavLauncherTeam/PojavLauncher#6189]
### Describe the bug

When launching the game through desktop mode. The game window becomes transparent. I attach video clip as reference

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17470269/latestlog.txt)

https://github.com/user-attachments/assets/76807196-05bf-4122-b657-02227c1c9e44

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch any version
3. After menu loads, click any button to render a new scene.
```

### Expected Behavior

The game renders with the correct transparency

### Platform

```markdown
- Device model: Huawei P50 Pro - International
- CPU architecture: ARM64 
- Android version: Android 12 
- PojavLauncher version: Latest, playstore
```

**Comment by GaucovyAero** [comment]
that's an issue with your device, try messing with the alternate surface rendering setting, else there's probably not much to be done, fixing this on your device might break something on all other devices
