### ISSUE TITLE
[F-Req] <Short description>جعفر الطيار 

### ISSUE THREAD

**Issue by JaafarAlTayyar** [PojavLauncherTeam/PojavLauncher#6190]
### Is this request related to a bug?

لا اقدر ان افعل حساب اصلي في بوجاف لان شار 

### Describe the request.

اريد احساب اصلي بوجاف لان شار 

### Anything else?

احساب اصلي بوجاف لان شار

**Comment by GaucovyAero** [comment]
if you have bought minecraft java edition, try logging into minecraft.net first, then log into pojav
