### ISSUE TITLE
[BUG] ModernUI mod crashes due to missing lwjgl function(?)

### ISSUE THREAD

**Issue by SanekGamer007** [PojavLauncherTeam/PojavLauncher#6191]
### Describe the bug

Launching the game with modernui 3.11.0.1 mod crashes it.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17477100/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Start an 1.20.1 forge-47.2.18 instance with modernui 3.11.0.1 installed.
3. Crash.
```

### Expected Behavior

The game launches like normal.

### Platform

```markdown
- Device model: Mi Pad 6
- CPU architecture: armv8a
- Android version: 14, crdroid 10.5
- PojavLauncher version: foxglove-20241004-14a0907-feat/tinywrapper
```

### Anything else?

Was tested with ltw renderer.

edit: also tested with fabric on 1.20.6 and the issue is the same.

**Comment by Dilen0001** [comment]
.

**Comment by BloCamLimb** [comment]
I have suppressed the NoSuchMethodError, then I suppose ModernUI 3.11.1 will work with LTW.

**Comment by GaucovyAero** [comment]
please test again

**Comment by SanekGamer007** [comment]
> please test again

will have to wait for 3.11.1 release.

**Comment by GaucovyAero** [comment]
okay

**Comment by BloCamLimb** [comment]
Does LTW really support the following functions?
* glClearBufferiv
* glClearBufferfv
* glClearBufferfi
* glBindBufferRange
* glDrawArraysInstanced
* glDrawElementsInstanced
* glGetUniformBlockIndex
* glUniformBlockBinding
* glFenceSync
* glDeleteSync
* glClientWaitSync
* glVertexAttribDivisor
* ARB_explicit_attrib_location
* ARB_instanced_arrays

These are defined in OpenGL 3.3 and OpenGL ES 3.0, but I feel like they didn't work as expected. ModernUI requires these to render, but the fact is that it renders nothing, the game runs as usual without crashing, and there are no GL errors. However, when using Zink, everything works out the way it's supposed to.

**Comment by artdeell** [comment]
> Does LTW really support the following functions?
> 
>     * glClearBufferiv
> 
>     * glClearBufferfv
> 
>     * glClearBufferfi
> 
>     * glBindBufferRange
> 
>     * glDrawArraysInstanced
> 
>     * glDrawElementsInstanced
> 
>     * glGetUniformBlockIndex
> 
>     * glUniformBlockBinding
> 
>     * glFenceSync
> 
>     * glDeleteSync
> 
>     * glClientWaitSync
> 
>     * glVertexAttribDivisor
> 
>     * ARB_explicit_attrib_location
> 
>     * ARB_instanced_arrays
> 
> 
> These are defined in OpenGL 3.3 and OpenGL ES 3.0, but I feel like they didn't work as expected. ModernUI requires these to render, but the fact is that it renders nothing, the game runs as usual without crashing, and there are no GL errors. However, when using Zink, everything works out the way it's supposed to.

The version of LTW released to the public has broken uniform blocks, so this may be the reason

**Comment by SanekGamer007** [comment]
> will have to wait for 3.11.1 release.

Just tested 3.11.1.3 on 1.20.6 Fabric and the issue is the same.
crashlog: [latestlog.txt](https://github.com/user-attachments/files/18266560/latestlog.txt)

**Comment by BloCamLimb** [comment]
> > will have to wait for 3.11.1 release.
> 
> Just tested 3.11.1.3 on 1.20.6 Fabric and the issue is the same. crashlog: [latestlog.txt](https://github.com/user-attachments/files/18266560/latestlog.txt)

The log says 3.11.0.3

**Comment by SanekGamer007** [comment]
> > > will have to wait for 3.11.1 release.
> > 
> > 
> > Just tested 3.11.1.3 on 1.20.6 Fabric and the issue is the same. crashlog: [latestlog.txt](https://github.com/user-attachments/files/18266560/latestlog.txt)
> 
> The log says 3.11.0.3

I'm a bit dumb and put the mod into the wrong folder, after fixing that it no longer crashes
i guess i will close the issue now?

**Comment by SanekGamer007** [comment]
> > > will have to wait for 3.11.1 release.
> > 
> > 
> > Just tested 3.11.1.3 on 1.20.6 Fabric and the issue is the same. crashlog: [latestlog.txt](https://github.com/user-attachments/files/18266560/latestlog.txt)
> 
> The log says 3.11.0.3

I'm a bit dumb and put the mod into the wrong folder, after fixing that it no longer crashes
i guess i will close the issue now?
