### ISSUE TITLE
[BUG] <Short description>OTG mouse Y and X Axis inverted on some android 13 phones

### ISSUE THREAD

**Issue by Nekikono** [PojavLauncherTeam/PojavLauncher#6193]
### Describe the bug

I have the same prob as others, my x and y axis in the mouse is inverted when I play minecraft and pojav launcher. When i go the mouse in the right, the pov goes up.

### The log file and images/videos

(*)

### Steps To Reproduce

```markdown
1. Open Minecraft
2. Play using bluetooth mouse or OTG Mouse
```

### Expected Behavior

I expect my mouse work correctly 

### Platform

```markdown
- Device model: Infinix Hot 40I
- Android version: 13
```

### Anything else?

Pwease help me fix this

**Comment by GaucovyAero** [comment]
this is an issue with your phone
