### ISSUE TITLE
[BUG] <1.20.1 fabric Not Starting Pojavlauncher

### ISSUE THREAD

**Issue by ZombieSPie** [PojavLauncherTeam/PojavLauncher#6194]
### Describe the bug

https://github.com/user-attachments/assets/11209245-ebac-4c90-8f7b-a38a94cf2f89

### The log file and images/videos

No Mods 

### Steps To Reproduce

```markdown
start PojavLauncher
```

### Expected Behavior

https://github.com/user-attachments/assets/72c720c1-fa8b-493d-bae5-3462c7a42220

### Platform

```markdown
- Device model: Infinix Hot 8
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: Newest
```

### Anything else?

https://github.com/user-attachments/assets/c43dc956-4532-4c02-b6b2-bfa3e27cb228

**Comment by GaucovyAero** [comment]
no log, closing
