### ISSUE TITLE
Fabric pojavlouncher 

### ISSUE THREAD

**Issue by Itamidomo** [PojavLauncherTeam/PojavLauncher#6195]
### Describe the bug

The Control input is delay which is unplayable (like walking automatically, incorrect action in button, unusable/delay left/right mouse). 
however this only happens when using fabric, forge moves normally, another bug is forge and optifine using shaders that cause the sky to flicker

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Pojavlouncher
```

### Expected Behavior

Tôi muốn di chuyển bình thường trong fabric 

### Platform

```markdown
- Device model: 23122PCD1I
- CPU architecture: CPU: Dimensity 8300-Ultra.
- Android version: Android 13
- PojavLauncher version:edelweiss-20230927-5d010fc-v3_openjdk
```

### Anything else?

No

**Comment by artdeell** [comment]
You are using an extremely out-of-date version of the launcher. Please update.
