### ISSUE TITLE
Laby mod 4 bug

### ISSUE THREAD

**Issue by Coryxkenshin-pixel** [PojavLauncherTeam/PojavLauncher#6197]
### Describe the bug

Every time I get to laby mod it shows this
![Screenshot_20241023_170709_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/c27bf507-c22f-4c81-8d82-26ea042c8208)

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240922-a6a6a29-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-A146U
Info: API version: 33
Info: Selected Minecraft version: LabyMod-4-1.21.2-e492519a
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2342
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 128), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  ( 3986): dlopen libgl4es_114.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  ( 3986): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjawt.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/librmi.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjavajpeg.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsctp.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libdt_socket.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjsig.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2gss.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_ext.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal
-21/lib/libmanagement_agent.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmlib_image.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjimage.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libinstrument.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libprefs.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjdwp.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjsig.so success
I/jrelog  ( 3986): dlope
n /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/liblcms.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2pkcs11.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libzip.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsyslookup.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjaas.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libextnet.so success

I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success
I/jrelog  ( 3986): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_xawt.so success
I/jrelog  ( 3986): dlopen /data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64/libopenal.so success

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
  <log4j:Event logger="LaunchWrapper" timestamp="1729721214998" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading tweak class name net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1729721215023" level="INFO" thread="main">
    <log4j:Message><![CDATA[Using primary tweak class name net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="LaunchWrapper" timestamp="1729721215025" level="INFO" thread="main">
    <log4j:Message><![CDATA[Calling tweak class net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker]]></log4j:Message>
  </log4j:Event>
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.labymod.api.loader.platform.PlatformEnvironment.<clinit>(PlatformEnvironment.java:16)
	at net.labymod.core.loader.vanilla.launchwrapper.LaunchWrapperTransformerRegistry.setPlatformClassloader(LaunchWrapperTransformerRegistry.java:88)
	at net.labymod.core.loader.vanilla.launchwrapper.Java17LabyModLaunchWrapperTweaker.acceptOptions(Java17LabyModLaunchWrapperTweaker.java:80)
	at net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker.acceptOptions(LabyModLaunchWrapperTweaker.java:105)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:188)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70)
Caused by: java.lang.NullPointerException: Cannot invoke "net.labymod.api.loader.MinecraftVersion.getReleaseTime()" because "current" is null
	at net.labymod.api.loader.MinecraftVersion.initialize(MinecraftVersion.java:32)
	at net.labymod.api.loader.MinecraftVersions.<clinit>(MinecraftVersions.java:1056)
	... 6 more
Java Exit code: 1
I/jrelog  ( 3986): Going to free args
I/jrelog  ( 3986): Free done

### Steps To Reproduce

```markdown
First download laby mod then pick the version 1.21.3 I dont know if it happens on the other versions of laby mod but I instaled the 1.21.3 then enter to the version of laby mod and the it appears de code -1 thing
```

### Expected Behavior

I expect that it doesnt show that

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Thats it

**Comment by Coryxkenshin-pixel** [comment]
Please help me

**Comment by Joanfigueroa** [comment]
> por favor, ayúdame

Labbymod is incompatible with pojavlauncher

**Comment by Coryxkenshin-pixel** [comment]
Ok

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
> > por favor, ayúdame
> 
> Labbymod is incompatible with pojavlauncher

yep
