### ISSUE TITLE
[BUG] 1.21.3 farbic - stuck at loading screen without logo.

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#6198]
### Describe the bug

Stuck at Minecraft loading screen, no mojang logo showed. It's just stuck there.
Farbic 0.16.7 (1.21.3) holy render. Without mod.
This doesn't happen with the new LTW render.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17516396/latestlog.txt)
(Tell me if this log is wrong, i stored a lot of logs file in my device lol)

### Steps To Reproduce

```markdown
1 Start pojav
2 install farbic version, the default installer build-in game doesn't work, so i had to install the installer file directly from fabric's site.
3 click install a jar file and import that installer file.
4 install farbic loader 1.21.3
5 done, quit the jar program and enter the farbic version without changing anything.
```

### Expected Behavior

Fix this

### Platform

```markdown
- Device model: tested on 3 different devices. Redmi k20 pro, redmi note 8, yuho tab 10.
- CPU architecture: all arm64.
- Android version: 13, 11, 11 (sort by devices model)
- PojavLauncher version: newest from playstore. 20240922 (ig)
```

### Anything else?

Sorry if my grammar are bad, i just couldn't fix it:(

**Comment by ghost** [comment]
Holygl4es is to old for run newer Minecraft versions. The red screen even not fixed

**Comment by elpepe1024** [comment]
Same but with vanilla

**Comment by elpepe1024** [comment]
> Same but with vanilla

But I can click things and hear sound even though its all red

**Comment by elpepe1024** [comment]
Got a solution- I used ANGLE renderer and now it works, try that.

**Comment by GaucovyAero** [comment]
duplicate of #5968
