### ISSUE TITLE
Multiple issues on galaxy s10e android 10

### ISSUE THREAD

**Issue by Letfordlay** [PojavLauncherTeam/PojavLauncher#62]
This is all on the preview 10b1
Ive tested multiple versions and 1.1 and below have a issue where the entire screen is in the bottom left and i cant get any further
![Screenshot_20200404-233905_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/21146162/78467054-749ce000-76ce-11ea-8464-7e721715ad6a.jpg)

Certain versions have errors such as
![Screenshot_20200404-233747_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/21146162/78467015-f9d3c500-76cd-11ea-8cdd-03a133933824.jpg)

Every version from 1.2.1 to 1.5.2 crash with the error 
![Screenshot_20200404-234000_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/21146162/78467022-0c4dfe80-76ce-11ea-958c-1d4a55f42c12.jpg)

Everything from  to 1.11.2 work fine in singleplayer, multiplayer works on some servers, many others dont.

 Everything 1.12 and up crashes with the error 
![Screenshot_20200404-234057_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/21146162/78467038-3a334300-76ce-11ea-82a0-d0b0fd1e212e.jpg)

**Comment by khanhduytran0** [comment]
> Ive tested multiple versions and 1.1 and below have a issue where the entire screen is in the bottom left and i cant get any further

Download Hacker's Keyboard, and press F11 using it's keyboard or OTG/Bluetooth keyboard. This will full screen and may fix the error.




> Certain versions have errors such as
> ![Screenshot_20200404-233747_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/21146162/78467015-f9d3c500-76cd-11ea-8cdd-03a133933824.jpg)

Try to force close the app and try again.


> Every version from 1.2.1 to 1.5.2 crash with the error
> ![Screenshot_20200404-234000_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/21146162/78467022-0c4dfe80-76ce-11ea-958c-1d4a55f42c12.jpg)

Please copy the error log to here.

> Everything from to 1.11.2 work fine in singleplayer, multiplayer works on some servers, many others dont.

Ok

> Everything 1.12 and up crashes with the error
> ![Screenshot_20200404-234057_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/21146162/78467038-3a334300-76ce-11ea-82a0-d0b0fd1e212e.jpg)

You can't run 1.12 or above at the moment.

**Comment by Letfordlay** [comment]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	... 5 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.client.Minecraft.a(SourceFile:2066)
	at net.minecraft.client.Minecraft.a(SourceFile:2058)
	at net.minecraft.client.Minecraft.main(SourceFile:2139)
	... 7 more
Caused by: java.lang.IllegalStateException: Unsupported platform
	at org.lwjgl.opengl.AWTGLCanvas.createImplementation(Unknown Source:14)
	at org.lwjgl.opengl.AWTGLCanvas.<clinit>(Unknown Source:3)
	... 10 more

**Comment by khanhduytran0** [comment]
Ok seems like the error come from the full AWT. Will be fixed in the next preview.

**Comment by Letfordlay** [comment]
Would it be possible to implement a fullscreen button or make it automatically go into fullscreen for certain versions? When using the hackers keyboard those versions work fine other than a few graphical bugs here and there. Also another issue that seems to be there from the original code from boardwalks gui. It cant sense multi-touch and i cant walk and look around at the same time

**Comment by khanhduytran0** [comment]
> Would it be possible to implement a fullscreen button or make it automatically go into fullscreen for certain versions?

I added `--fullscreen` argument to `preview10b2` but seems like it is not working properly.

> Also another issue that seems to be there from the original code from boardwalks gui. It cant sense multi-touch and i cant walk and look around at the same time

Maybe fix in the next preview.

**Comment by khanhduytran0** [comment]
I will add list of buttons (including F11) instead of fullscreen button.

**Comment by khanhduytran0** [comment]
> Also another issue that seems to be there from the original code from boardwalks gui. It cant sense multi-touch and i cant walk and look around at the same time

Tried to fix, but it causing more bugs, so not fix now.

**Comment by khanhduytran0** [comment]
> Also another issue that seems to be there from the original code from boardwalks gui. It cant sense multi-touch and i cant walk and look around at the same time

Fixed in latest preview @Letfordlay

**Comment by khanhduytran0** [comment]
Re-open if you have bug again.
