### ISSUE TITLE
[F-Req] Other Controller handlers

### ISSUE THREAD

**Issue by Lazikbro12** [PojavLauncherTeam/PojavLauncher#6203]
### Is this request related to a bug?

There should be a way to use controller mods like legacy4j adds the support or controllable.

### Describe the request.

It would be nice to just use triggers to switch menus in legacy4j. The 4j handlers are better personaly. If you dont want to you dont need to but it would be awesome if you would add it.

### Anything else?

You can delete this post later.
I just Hope for a response.

**Comment by GaucovyAero** [comment]
no
