### ISSUE TITLE
[BUG] <is happen when i try to run shader exited code 6>

### ISSUE THREAD

**Issue by Beelzebub13208** [PojavLauncherTeam/PojavLauncher#6205]
### Describe the bug

[latestlog.txt](https://github.com/user-attachments/files/17534195/latestlog.txt)

### The log file and images/videos

![Uploading IMG_0009.png…]()

### Steps To Reproduce

```markdown
only can run normal minecraft with no shader
```

### Expected Behavior

ios 17.7 so it can run zink vulkan GL

### Platform

```markdown
- Device model: iphone 13 pro max
- CPU architecture: A15 bionic 
- Android version: ios 17.7
- PojavLauncher version: 2.2
```

### Anything else?

try download old version of minecraft and povalauncher or new have try to use another GL ANGLE GL4ES

**Comment by ghost** [comment]
I think you need to report in pojav launcher iOS website not for android

**Comment by GaucovyAero** [comment]
wrong repo, go to PojavLauncherTeam/PojavLauncher_iOS
