### ISSUE TITLE
1.21.3 and 1.21.2 bug

### ISSUE THREAD

**Issue by Coryxkenshin-pixel** [PojavLauncherTeam/PojavLauncher#6206]
### Describe the bug

Every time I enter to the version 1.21.3 or 1.21.2 it appears this
![Screenshot_20241027_102304_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/2b852d5b-5f5e-4571-a0d7-5e99904c6161)

### The log file and images/videos

Heres the log file --------- beginning with launcher debug
Info: Launcher version: foxglove-20240922-a6a6a29-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-A146U
Info: API version: 33
Info: Selected Minecraft version: 24w40a
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2342
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 128), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  (22653): dlopen libgl4es_114.so success

I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  (22653): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so 
success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjawt.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/librmi.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjavajpeg.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsctp.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libdt_socket.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjsig.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Inter
nal-21/lib/libjava.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2gss.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_ext.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_agent.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmlib_image.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjimage.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libinstrument.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libprefs.so success
I/jrelog  (22653): dlope
n /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjdwp.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjsig.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/liblcms.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2pkcs11.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libzip.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so s
uccess
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsyslookup.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjaas.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libextnet.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success
I/jrelog  (22653): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_xawt.so success
I/jrelog  (22653): dlopen /data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64/libopenal.so success

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
  <log4j:Event logger="ac" timestamp="1730042891101" level="WARN" thread="main">
    <log4j:Message><![CDATA[Failed retrieving info for group processor]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230)
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at ac.c(SourceFile:79)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:79)
	at ac.e(SourceFile:56)
	at ac.a(SourceFile:87)
	at ac.<init>(SourceFile:56)
	at o.<init>(SourceFile:35)
	at o.g(SourceFile:234)
	at net.minecraft.client.main.Main.main(SourceFile:133)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="ac" timestamp="1730042891186" level="WARN" thread="main">
    <log4j:Message><![CDATA[Failed retrieving info for group memory]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60)
	at ac.a(SourceFile:81)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:81)
	at ac.e(SourceFile:56)
	at ac.a(SourceFile:87)
	at ac.<init>(SourceFile:56)
	at o.<init>(SourceFile:35)
	at o.g(SourceFile:234)
	at net.minecraft.client.main.Main.main(SourceFile:133)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230)
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at ac.c(SourceFile:79)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:79)
	... 6 more
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="com.mojang.datafixers.DataFixerBuilder" timestamp="1730042891883" level="INFO" thread="Datafixer Bootstrap">
    <log4j:Message><![CDATA[236 Datafixer optimizations took 910 milliseconds]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="amg" timestamp="1730042899467" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
  <log4j:Event logger="com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService" timestamp="1730042899901" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="flz" timestamp="1730042899930" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Setting user: nxkdkd]]></log4j:Message>
  </log4j:Event>
Registered forkAndExec
  <log4j:Event logger="fmd" timestamp="1730042900204" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Error parsing option value off for option Fullscreen: Not a boolean: "off"]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="fmd" timestamp="1730042900227" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Error parsing option value 0.5d for option Text Background Opacity: Failed to parse either. First: Not a number: "0.5d"; Second: Not a boolean: "0.5d"]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="flz" timestamp="1730042900243" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Backend library: LWJGL version 3.3.3-snapshot]]></log4j:Message>
  </log4j:Event>
EGLBridge: Binding to OpenGL ES
  <log4j:Event logger="amg" timestamp="1730042900294" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="amg" timestamp="1730042900727" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="amg" timestamp="1730042901035" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="flz" timestamp="1730042901283" level="ERROR" thread="Download-2">
    <log4j:Message><![CDATA[Failed to fetch user properties]]></log4j:Message>
    <log4j:Throwable><![CDATA[com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150)
	at flz.bM(SourceFile:464)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: MinecraftClientHttpException[type=HTTP_ERROR, status=401, response=ErrorResponse[path=/player/attributes, error=null, errorMessage=null, details=null]]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100)
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121)
	... 5 more
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="com.mojang.text2speech.Narrator" timestamp="1730042901694" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Error while loading the narrator]]></log4j:Message>
    <log4j:Throwable><![CDATA[com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69)
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18)
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41)
	at flq.<init>(SourceFile:19)
	at flz.<init>(SourceFile:701)
	at net.minecraft.client.main.Main.main(SourceFile:248)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:90)
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67)
	... 5 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~-EChrR1LQq1L_NYiPf4k-Q==/net.kdt.pojavlaunch-aEmam8_IePe1Rk3UNxV3hA==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230)
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at ac.c(SourceFile:79)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:79)
	at ac.e(SourceFile:56)
	at ac.a(SourceFile:87)
	at ac.<init>(SourceFile:56)
	at o.<init>(SourceFile:35)
	at o.g(SourceFile:234)
	at net.minecraft.client.main.Main.main(SourceFile:133)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="avs" timestamp="1730042901733" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Reloading ResourceManager: vanilla]]></log4j:Message>
  </log4j:Event>
I/NativeInput(22653): Input ready: 1

  <log4j:Event logger="frg" timestamp="1730042901962" level="INFO" thread="Worker-Main-3">
    <log4j:Message><![CDATA[Found unifont_all_no_pua-15.1.05.hex, loading]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="frg" timestamp="1730042902866" level="INFO" thread="Worker-Main-6">
    <log4j:Message><![CDATA[Found unifont_jp_patch-15.1.05.hex, loading]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hgd" timestamp="1730042906782" level="WARN" thread="Render thread">
    <log4j:Message><![CDATA[Missing sound for event: minecraft:block.spawner.fall]]></log4j:Message>
  </log4j:Event>
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
  <log4j:Event logger="fdy" timestamp="1730042906895" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[OpenAL initialized on device OpenSL]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hgd" timestamp="1730042906898" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Sound engine started]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907149" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 1024x512x0 minecraft:textures/atlas/blocks.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907168" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 256x256x0 minecraft:textures/atlas/signs.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907172" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 512x512x0 minecraft:textures/atlas/banner_patterns.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907174" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 512x512x0 minecraft:textures/atlas/shield_patterns.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907177" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 1024x1024x0 minecraft:textures/atlas/armor_trims.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907188" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907192" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 128x64x0 minecraft:textures/atlas/decorated_pot.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907194" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907196" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907386" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907656" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907661" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907663" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="hbd" timestamp="1730042907665" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="fhb" timestamp="1730042908271" level="INFO" thread="IO-Worker-1">
    <log4j:Message><![CDATA[Could not authorize you against Realms server: Invalid session id]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="fgv" timestamp="1730042908275" level="ERROR" thread="IO-Worker-1">
    <log4j:Message><![CDATA[Couldn't connect to realms]]></log4j:Message>
    <log4j:Throwable><![CDATA[fix: Realms authentication error with message 'Invalid session id'
	at fhb.a(SourceFile:445)
	at fhb.g(SourceFile:232)
	at fgv.c(SourceFile:51)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></log4j:Throwable>
  </log4j:Event>

### Steps To Reproduce

```markdown
First download 1.21.3 and 1.21.2 and then enter first of them and then the second one and then your going to see the screen
```

### Expected Behavior

I expect it to work

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

And it this bug also happens on the snapshot 24w40a up to the snapshot 1.21.2-pre2

**Comment by Villanity** [comment]
Same issue, I tried with 1.21.3

**Comment by WesleyVanNeck** [comment]
Use ltw

**Comment by ghost** [comment]
![Screenshot_2024-10-30-05-34-52-840_com android chrome-edit](https://github.com/user-attachments/assets/2fd5b728-b43a-467b-87ac-15938c791315)

**Comment by CreepyWe** [comment]
How to fix it

**Comment by Matei2010** [comment]
Only angle works at the moment with MANY graphic glitches

**Comment by Fractal420** [comment]
Still same issue with 1.21.3, please fix this, as i can't use baritone because of that.
