### ISSUE TITLE
[BUG] 1.12.3 Red Screen Glitch

### ISSUE THREAD

**Issue by Vradzy** [PojavLauncherTeam/PojavLauncher#6207]
### Describe the bug

I am using 1.12.3 version tried both fabric and vanilla when clicking on launch, there is a weird red screen with no logo and we can hear the music and button sounds but after sometime the screen turns black.

### The log file and images/videos

Here are the images:
![Screenshot_2024-10-27-22-34-38-41_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/user-attachments/assets/73715f4e-2e4f-4d59-b582-8c0e027f5951)
![Screenshot_2024-10-27-22-34-53-96_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/user-attachments/assets/dc2d2459-7abf-44cc-a8c5-e91469cd7031)

### Steps To Reproduce

```markdown
Start PojavLauncher then install 1.21.3 either vanilla or any mod loader. You will be met with an weird red screen with no lolo.
```

### Expected Behavior

I expect the game to start.

### Platform

```markdown
- Device model: Oppo A79 5G
- CPU architecture: 7nm
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk [Latest]
```

**Comment by SolDev69** [comment]
gl4es needs to be updated with a fix, for now use zink, Angle, or the experimental LTW branch

**Comment by WesleyVanNeck** [comment]
> gl4es needs to be updated with a fix, for now use zink, Angle, or the experimental LTW branch

Artdev said he doesn't want to figure out why gl4es isn't working

**Comment by SolDev69** [comment]
> > gl4es needs to be updated with a fix, for now use zink, Angle, or the experimental LTW branch
> 
> Artdev said he doesn't want to figure out why gl4es isn't working 

Ah so is LTW gonna be the recommended for 1.21.2+?

**Comment by ghost** [comment]
Probably yes. LTW have much options holygl4es doesn't have. some shaders work. Better compatibility for mods. Updated gl4es 2.1 to 3.0. and faster because of sodium. So it's probably better than holygl4es.

**Comment by GaucovyAero** [comment]
> > > gl4es needs to be updated with a fix, for now use zink, Angle, or the experimental LTW branch
> > 
> > 
> > Artdev said he doesn't want to figure out why gl4es isn't working
> 
> Ah so is LTW gonna be the recommended for 1.21.2+?

yeah most probably, later

**Comment by Gannu5704Q** [comment]
Use this version of pojav launcher 
Link - (https://www.apkmirror.com/apk/artdeell/pojavlauncher-minecraft-java-edition-for-android/pojavlauncher-minecraft-java-edition-for-android-edelweiss-20230928-9484d0c-v3_openjdk-release/pojavlauncher-minecraft-java-edition-for-android-edelweiss-20230928-9484d0c-v3_openjdk-2-android-apk-download/download/?key=58f64fbb1be4cf72ef7ee13b084b4ee70e7b08d4&forcebaseapk=true)
Search this link on Google 
"This version support holy render and Zink Render and Angel Render properly but Java21 not install automatically by supporting version so install Java 21 externally or using GitHub or other" ( Do everything manually )  
Thanks
