### ISSUE TITLE
Nie moge zrobic konta na pojavluncher bo wystepuje blad xbox live

### ISSUE THREAD

**Issue by skibiditojletik** [PojavLauncherTeam/PojavLauncher#6209]
### Is this request related to a bug?

NIE MOGE ZROBIC NOWEGO KONTA NA POJAVLUNCHER  BO WYSKAKUJR CALY CZAS BLAD EROR  XBOX LIVE

### Describe the request.

nie

### Anything else?

Nie

**Comment by GaucovyAero** [comment]
just do what it tells you to
