### ISSUE TITLE
[F-Req] <Short description

### ISSUE THREAD

**Issue by Nitin1234556** [PojavLauncherTeam/PojavLauncher#6212]
### Is this request related to a bug?

No

### Describe the request.

Can you plz give me vulkan mod for 1.21 for holy render plz

### Anything else?

No

**Comment by Bel69420** [comment]
Vulkanmod is not supported, if you asking again, your request will be ignored

**Comment by Nitin1234556** [comment]
> Vulkanmod is not supported, if you asking again, your request will be ignored

But there are vedios in which they use vulkan mod

**Comment by ghost** [comment]
> > Vulkanmod is not supported, if you asking again, your request will be ignored
> 
> But there are vedios in which they use vulkan mod

Yes vulkan mod android library is can make vulkanmod playable for pojav but needs vulkan 1.2 and up and it doesn't seem vulkanmod support shader. Try sodium mod with LTW renderer

**Comment by WOOD6563** [comment]
But how are some people using vulkan mod in minecraft 1.21.1 with vulkan 1.1
