### ISSUE TITLE
zink crashing in tecno pova 5 pro

### ISSUE THREAD

**Issue by gamingman7** [PojavLauncherTeam/PojavLauncher#6214]
### Describe the bug

Zink was working when I bought the device and it was working for two months, but after that it stopped working and I don’t know why... I tried to solve the problem but to no avail.. This is the error file... 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17572820/latestlog.txt)

### Steps To Reproduce

```markdown
1-START POJAVLAUNCHER
2-choose zink render
3-Choose any version I want 
4-start the game
5-the game crashing
```

### Expected Behavior

Zink work. 

### Platform

```markdown
- Device model: TECNO LH8n
- CPU architecture: GPU, Mali-G57 
- Android version: android 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_op enjdk
```

### Anything else?

PLEASE.. Please give me a solution to this problem!!

**Comment by GaucovyAero** [comment]
your gpu is likely not capable enough to run zink, you can try putting MESA_GL_VERSION_OVERRIDE=4.6 into /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt and see what it does, it might not help tho
