### ISSUE TITLE
The Black Screen When Minimize

### ISSUE THREAD

**Issue by Aditya014JB** [PojavLauncherTeam/PojavLauncher#6215]
### Describe the bug

So Whenever I Play Pojavlauncher,,while using keyboard and writing,I Mistakenly Clicks The Main Home Button Or Minimize Button Of Mobile And When I Enter Again The Game Is Showing Black Screen Meanwhile The Noises,commands,game is still on 

### The log file and images/videos

Uploading VID_20241030195639.mp4…

### Steps To Reproduce

```markdown
1.start pojav
2.when game shows interface of game like, single player, multiplayer 
3.click home button or minimize button and re-enter in game
4.and game shows the black screen but the buttons of games or music will still work
```

### Expected Behavior

I don't want to click minimize or home button of mobile 

### Platform

```markdown
- Device model: Realme C55 6/64GB
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

I* Have A Small Request That You Can Show A Small Interface Of "Update Pojavlauncher" When The Player Opens Pojavlauncher  when bugs,or new features gets added and one more thing that if possible that you can add fabric/forge mods can be installed and kept in mods file like feather client

Thanks

**Comment by GaucovyAero** [comment]
if you are using Forge, disable earlyWindowControl in .minecraft/config/fml.toml by putting it to false

**Comment by Aditya014JB** [comment]
> if you are using Forge, disable earlyWindowControl in .minecraft/config/fml.toml by putting it to false

In Whole Pojav Not Only In Forge :[
