### ISSUE TITLE
[BUG] Input issues concerning controller and physical keybard

### ISSUE THREAD

**Issue by GreenNBlacko** [PojavLauncherTeam/PojavLauncher#6216]
### Describe the bug

For the keyboard, the keys stick(you press down w and even after you release the key, the player remains going forward), have reproduced with multiple keyboards and different layouts(ANSI, ISO, en-us, norwegian)
For the controller, everything works as intended except for when I open the on-screen keyboard, then the sticks stop tracking, which I can sometimes get working again just by wiggling the sticks a bit, however usually it requires reconnecting the controller completely(Reproduced with wired/wireless dualsense, ds4, xbox series x controller)

### The log file and images/videos

Keyboard issue
[latestlog.txt](https://github.com/user-attachments/files/17574648/latestlog.txt)

Controller
[latestlog.txt](https://github.com/user-attachments/files/17574718/latestlog.txt)

### Steps To Reproduce

```markdown
Keyboard
1. Start minecraft
2. Go into a world
3. Press any key
4. Release key
5. Key continues to be pressed down

Controller
1-2. Same as for keyboard
3. Open on-screen keyboard
4. Attempt to look/walk around with the controller sticks
5. The sticks don't register an input
```

### Expected Behavior

For keyboard keys to register as released when they are released and so controller sticks wouldn't lose tracking over opening the on-screen keyboard

### Platform

```markdown
- Device model: Sony Xperia 1 VI
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
update to the latest github actions build, its fixed in there, installation guide for github actions builds is on the wiki
