### ISSUE TITLE
Ltw doesn't support older sodium versions 

### ISSUE THREAD

**Issue by NinjaLegendmc** [PojavLauncherTeam/PojavLauncher#6219]
### Describe the bug

Ltw only support 0.5 or above versions of sodium not the older one it just crash 

### The log file and images/videos

Nothing 

### Steps To Reproduce

```markdown
1. Start pojav with ltw and old sodium
2. Join world or server's
3. Crash!
```

### Expected Behavior

Crash

### Platform

```markdown
- Device model: vivo y100a
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: ltw pojav
```

### Anything else?

Nothing

**Comment by GaucovyAero** [comment]
if the renderer doesnt support some gl features it just doesnt lol, also 0.4.10 and lower work on gl4es so you can use that instead

**Comment by NinjaLegendmc** [comment]
> if the renderer doesnt support some gl features it just doesnt lol, also 0.4.10 and lower work on gl4es so you can use that instead

It will give me invisible blocks in world if I use it with holy Gl4es 
And what does you mean by some gl support?
