### ISSUE TITLE
[BUG] Regarding Red screen on startup v1. 21.2 - 1.21.3

### ISSUE THREAD

**Issue by Pityciuu** [PojavLauncherTeam/PojavLauncher#6221]
### Describe the bug

Whenever I installed versions 1.21.2 to 1.21.3, the launcher screen turned red. I could still hear the Minecraft soundtrack and click on things, but the screen remained red and black. When the main menu loaded, I tried using the "Feat[launcher]: add renderer, add compatibility checks" as mentioned in bug report #6206 

Additionally, the game file size was only 400MB+, compared to 800MB+ for version 1.21.1. I think the game file download was incomplete or some files were missing.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17593433/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open the Pojavlauncher and ensure it's set to the "Latest Release" option.
2. Click "Play" to start the game.
3. Observe the screen - it should turn red and black, but you'll still hear the Minecraft soundtrack and be able to click on things.
```

### Expected Behavior

idk

### Platform

```markdown
- Device model: Infinix Smart 8 
- CPU architecture: Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55)
- Android version: 13
- PojavLauncher version: foxglove-20241004-14a0907-feat/tinywrapper
```

### Anything else?

i hope this one got fix

**Comment by Yoidiotiamback** [comment]
It works fine with zink renderer but low fps

**Comment by Yoidiotiamback** [comment]
Use zink renderer works fine if you face lag use sodium zink supports sodium

**Comment by GaucovyAero** [comment]
use the ltw renderer

**Comment by bolrom** [comment]
Same problem __

**Comment by eric5828** [comment]
Alguém sabe resolver isso prfv me avise blz tô tentandó e não está funcionando Alguém pode ajudar nessa questão dessas versões que não está funcionando 1.21.3 e 1.21.2

**Comment by Piadineitor09** [comment]
i have the same problem

**Comment by ghost** [comment]
He says use LTW renderer it fix the problem so USE IT if you want to play 1.21.2 and up

**Comment by Betabeta** [comment]
> He says use LTW renderer it fix the problem so USE IT if you want to play 1.21.2 and up

How do you install it?

**Comment by Piadineitor09** [comment]
> i have the same problem

forget it it's fixed

**Comment by ghost** [comment]
Yes but LTW is better than holygl4es renderer

**Comment by WesleyVanNeck** [comment]
> > Yes but LTW is better than holygl4es renderer
> 
> @kasrarouhi But there isn't a LTW renderer.
> 
> I only see **holygl4es, Zink, Angle** renderers.

Its in a experimental branch

**Comment by WesleyVanNeck** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/11180313158/job/31081774197
