### ISSUE TITLE
[BUG] <Zink(vulcan)and angle(vulcan) renderer keeps crashing>

### ISSUE THREAD

**Issue by KURTAINFDSH** [PojavLauncherTeam/PojavLauncher#6224]
### Describe the bug

I try to use Zink(vulkan) and angle (vulcan) but it just show me blackscreen and 
Crash in a few seconds my phone is a Tecno spark go 2024
idk if to use a shader I need to use zink renderer
Or shader work to on holy gl4es 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17605317/latestlog.txt)

### Steps To Reproduce

```markdown
Pls fix if posible
```

### Expected Behavior

It will continue to loading screen

### Platform

```markdown
- Device model: TECNO BG6
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_op enjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
the log says that your gpu does not meet minimum requirements to run zink

**Comment by KURTAINFDSH** [comment]
Ah ok

**Comment by KURTAINFDSH** [comment]
But I have question does shader work on holy gl4es renderer?

**Comment by GaucovyAero** [comment]
only on older versions of gl4es if you had a snapdragon soc

**Comment by GaucovyAero** [comment]
open4es for 1.17+ mali might still work for you tho

**Comment by KURTAINFDSH** [comment]
Is that a renderer?

**Comment by KURTAINFDSH** [comment]
Or a shader?

**Comment by KURTAINFDSH** [comment]
![Uploading Screenshot_20241102-183101.png…]()

I found this shader

**Comment by Bel69420** [comment]
That's a shader, tho it might bugged up on mali gpus

**Comment by KURTAINFDSH** [comment]
I'm experiencing some shadow issue idk if its fixable on the setting or its bc of my phone
I'm seeing an line of shadow 
![Uploading Screenshot_20241102-190508.png…]()

**Comment by Bel69420** [comment]
That's what im talking about

**Comment by Bel69420** [comment]
This is caused by GPU driver fault

**Comment by Bel69420** [comment]
We can't really do anything about it

**Comment by KURTAINFDSH** [comment]
Ty for the help

**Comment by KURTAINFDSH** [comment]
Um another question does modpacks works?
I haven't tried it tho

**Comment by GaucovyAero** [comment]
depends on the mods they are using
