### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Bigmike085** [PojavLauncherTeam/PojavLauncher#6227]
### Describe the bug

Simplesmente não entra na minha conta coloco o email e senha certinho nas não entra 

### The log file and images/videos

![Screenshot_20241103-000151](https://github.com/user-attachments/assets/d984c5be-d5df-414d-ba36-c3504ecf2e23)

### Steps To Reproduce

```markdown
O pujavlauncher n entra na minha conta
```

### Expected Behavior

Eu esperava que entrasse na minha conta 

### Platform

```markdown
- Modelo do dispositivo: moto g30 
- Arquitetura da CPU: Qualcomm
- Versão Android: 12
- Versão PojavLauncher: v3
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
you are ignoring what pojav says lol
