### ISSUE TITLE
[BUG] The mouse wrong direction

### ISSUE THREAD

**Issue by RatMeatball12** [PojavLauncherTeam/PojavLauncher#6228]
### Describe the bug

I play pojav and the mouse direction is wrong

### The log file and images/videos

I don't have

### Steps To Reproduce

```markdown
Just start pojav
```

### Expected Behavior

My mouse The direction is wrong

### Platform

```markdown
- Device model: infinix smart 8
- CPU architecture: tsoc 606
- Android version: 13
- PojavLauncher version: lattest
```

### Anything else?

Mouse doest work

**Comment by Dilen0001** [comment]
.

**Comment by RatMeatball12** [comment]
> .

Pls tell me how to fix it

**Comment by GaucovyAero** [comment]
this is an issue with your device, wont fix
