### ISSUE TITLE
[BUG] bug with 1.21.2 and 1.21.3 or thier snapshot 

### ISSUE THREAD

**Issue by King201321** [PojavLauncherTeam/PojavLauncher#6229]
### Describe the bug

Whenever I open 1.21.2 or 1.21.3 or their snapshots a red screen appears and the Minecraft music starts playing

### The log file and images/videos

![Screenshot_20241103_142555_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/d67cfea3-0523-438b-9b80-d7935258d507)

### Steps To Reproduce

```markdown
Start pojavlauncher
Open Minecraft black screen for a while then the red screen appears
```

### Expected Behavior

I expect Minecraft to open 

### Platform

```markdown
- Device model: Samsung Galaxy Tab A8 and Samsung Galaxy A14
- CPU architecture: don't know
- Android version: 14 of both
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

I have tested on two devices and both of them have the same issue

**Comment by Dilen0001** [comment]
.

**Comment by Yoidiotiamback** [comment]
Use ltw renderer from githubs action scroll down and you will see add renderer and complability click it download select ltw and ur to go

**Comment by King201321** [comment]
Thank you very much helped me a lot thanks
