### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BNaise** [PojavLauncherTeam/PojavLauncher#6231]
### Describe the bug

This is not related to pojavlauncher but if somebody could help please help.
So I found this guy on reddit who needs help when his friend join his server he sees falling in void.

### The log file and images/videos

Latestlog of his friend.
https://mclo.gs/yc5pCjA#L1
This is what his friend sees
![RDT_20241103_2010403232654702073950764](https://github.com/user-attachments/assets/616bb0ab-4ec1-4ea9-8ec3-f438f834e20a)
This is his post
https://www.reddit.com/r/MinecraftHelp/s/NYLM5AtuoI
For people who's asking why you are posting this on pojavlauncher.
Ans :- because I don't know Minecraft's forms I would get a reply but whenever I bug report in pojavlauncher I always get a reply.

### Steps To Reproduce

```markdown
Like i said in description not related to pojavlauncher.
```

### Expected Behavior

His friend to join correctly.

### Platform

```markdown
- Device model: don't know
- CPU architecture: don't know 
- Android version: not android
- PojavLauncher version: not related to pojavlauncher
```

**Comment by ghost** [comment]
I think it's mod issue. Remove the mods one by one to see which mod makes Minecraft in the void

**Comment by GaucovyAero** [comment]
![image](https://github.com/user-attachments/assets/198a5f5c-fc9e-44d5-8437-299b6997cade)

he gotta check the firewall or **speak with his isp**
