### ISSUE TITLE
forge 1.6.4 game crashes with code 1

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6232]
### Describe the bug

for some reason I can't launch forge 1.6.4, I also tried deleting it, installing the vanilla 1.6.4 version first and then reinstalling forge but to no avail (the vanilla version works wonderfully though, and forge 1.7.10 works)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17612297/latestlog.txt)

### Steps To Reproduce

```markdown
1. install forge 1.6.4
2. launch the game
3. watch it crash
```

### Expected Behavior

I expected it to launch 

### Platform

```markdown
- Device model: samsung SM-M536B
- CPU architecture: arm64
- Android version: 34
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
read the log file, it tells you what to do
