### ISSUE TITLE
[BUG] Virtual mouse still on after turning it off

### ISSUE THREAD

**Issue by aplaster394** [PojavLauncherTeam/PojavLauncher#6233]
### Describe the bug

I go into the control customization page of the settings and flip the "start with virtual mouse on" switch to off, yet the virtual mouse is still present. I am launching 1.21.1 Optifine, with the jre21-arm64-20240309-release - 21.0.1 java runtime, and Holy GL4ES renderer if that matters.

### The log file and images/videos

![Screenshot 2024-11-03 4 36 08 PM](https://github.com/user-attachments/assets/d18b8d67-c98d-4fcd-9776-26e8178d8da9)
![Screenshot 2024-11-03 4 36 17 PM](https://github.com/user-attachments/assets/52208fc7-d196-49a9-bbdc-ba654f09d65d)

### Steps To Reproduce

```markdown
Open Pojav
Go to settings
Go to Control Customization
Scroll down until you see "Start with virtual mouse on"
Turn it off
Launch any version of Minecraft(for sure happens on 1.21.1 Optifine and 1.16.5 Vanilla with above mentioned runtime and renderer)
```

### Expected Behavior

No virtual cursor should appear

### Platform

```markdown
- Device model: HP 11a-na0035nr Chromebook
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk(installed from play store)
```

**Comment by GaucovyAero** [comment]
you wanna play touchscreen on your chromebook? i think if you have a touchpad it just uses that instead lol

**Comment by aplaster394** [comment]
My Chromebook doesn't have a touch screen, it my actual mouse that doesn't work properly, and it is only in game

**Comment by aplaster394** [comment]
> you wanna play touchscreen on your chromebook? i think if you have a touchpad it just uses that instead lol

My Chromebook doesn't have a touch screen, it my actual mouse that doesn't work properly, and it is only in game

**Comment by GaucovyAero** [comment]
most probably not going to be fixed since this only happens on your device and maybe a couple other ones and the issue isnt on most devices, meaning devs cant really debug it (cause we dont have that much money to buy every device in the world)
also fixing the issue on your device might break it on other devices, so yeah

**Comment by aplaster394** [comment]
> most probably not going to be fixed since this only happens on your device and maybe a couple other ones and the issue isnt on most devices, meaning devs cant really debug it (cause we dont have that much money to buy every device in the world) also fixing the issue on your device might break it on other devices, so yeah

I understand

**Comment by artdeell** [comment]
> > you wanna play touchscreen on your chromebook? i think if you have a touchpad it just uses that instead lol
> 
> My Chromebook doesn't have a touch screen, it my actual mouse that doesn't work properly, and it is only in game

How does it "not work properly"? Can you describe it?

**Comment by aplaster394** [comment]
> > > you wanna play touchscreen on your chromebook? i think if you have a touchpad it just uses that instead lol
> > 
> > 
> > My Chromebook doesn't have a touch screen, it my actual mouse that doesn't work properly, and it is only in game
> 
> How does it "not work properly"? Can you describe it?

The virtual mouse would be really slow even at max speed on both game and device settings, on all surfaces. It would also teleport when moved at high speeds. If I actually used my touch pad it would just fine.

**Comment by GaucovyAero** [comment]
your polling rate is set too high, you have to set it to 125Hz for optimal experience, if your mouse cant set such settings into its memory (via a Windows app for example), you gotta get a mouse that can do that

**Comment by aplaster394** [comment]
> your polling rate is set too high, you have to set it to 125Hz for optimal experience, if your mouse cant set such settings into its memory (via a Windows app for example), you gotta get a mouse that can do that

My mouse has the option to lower the polling rate, and I set it to 125 Hz, and it didn't fix it. (The mouse is the Logitech G305, my old mouse was the Logitech M510, I had no problems with my old mouse)

Edit: my onboard memory wasn't working properly, I fixed it and now everything works, thanks for the help
