### ISSUE TITLE
[BUG] Red Screen Problem

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6234]
### Red Screen Problem

I opened the game. And I got black scren for some time and then I got stuck with red screen without the mojang logo and loading screen. I tried some profiles like Fabric, normal, sodium plus 1.21.3 I tried some jar files but couldn't load anything. Some got failed to read jar file and some got execution not compatible with jar 21. I also tried othe java version.

### The log file and images/videos

Sorry I cant upload the log file because my mobile file manager is broken. Latest log was 0 byte. And one before had one error which was caused due to my bad java argument.

### Steps To Reproduce

```markdown
I dont think this can be reproduced. But here are the steps I did
1. I started Pojav launcher and clicked play.
2. After a bit of waiting I got the red screen without mojang logo and loading screen.
```

### Expected Behavior

I expect the red screen to load the mojang logo and loading screen and the game to work.

### Platform

```markdown
- Device model: Redmi 10A
- CPU architecture: armeabi, armeabi-v7a
- Android version: 11
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by Yoidiotiamback** [comment]
We would recommend to switch to zink renderer or ltw renderer

**Comment by Putul182** [comment]
Plz give me direct download link

**Comment by Yoidiotiamback** [comment]
Hmm I don't know how to give you direct link I would say that go to github actions scroll down until you see add renderer and compability check click it download go to the game renderer select ltw and ur to go your problem solved or I if you have a good phone then go to renderer select zink if you Hava strong phone or highly recommended ltw
