### ISSUE TITLE
[BUG] Mods not loading because the permission of the PojavLauncher directory is denied

### ISSUE THREAD

**Issue by Not-That-Important-Name** [PojavLauncherTeam/PojavLauncher#6235]
### Describe the bug

Whenever I use any mod loader with mods, it crashes and according to the log, its because the permission of the PojavLauncher directory is denied. This does not happen with Vanilla versions of Minecraft.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17630528/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher using a mod loader with mods
2. Wait for a few seconds
3. It crashes
```

### Expected Behavior

I expect it to launch and load the mods properly.

### Platform

```markdown
- Device model: INFINIX Infinix X669D
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

On my other Samsung Phone that is also Android 12, it launches and does not crash. On fabric on my INFINIX phone, it crashes but in NeoForge, it does not crash though it is stuck on the loading screen and still shows the issue in the log file.

**Comment by miggythewriter** [comment]
If you join the discord server I could help you

**Comment by Felix14-v2** [comment]
You have to use the file manager from AOSP, it doesn't have the permission issues:
https://play.google.com/store/apps/details?id=com.marc.files
Don't forget to clear your mods folder before using it.
