### ISSUE TITLE
[BUG] Fisk's superhero mod in 1.7.10 broken textures only

### ISSUE THREAD

**Issue by SingkamasBANG** [PojavLauncherTeam/PojavLauncher#6236]
### Describe the bug

Some broken textures and missing textures that made it ugly to look at  otherwise other mods is working

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

Maybe there's a way to fix it by trying it for yourselves...

### Platform

```markdown
.
```

**Comment by GaucovyAero** [comment]
cant really help there, you are most likely out of gpu memory, not a pojav issue or just not something that can be resolved
