### ISSUE TITLE
[BUG] <Short description> crash code 1

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6242]
### Describe the bug

Crash when run pojav

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17674801/latestlog.txt)

### Steps To Reproduce

```markdown
1.run pojav and crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model:redmi note 11 
- CPU architecture: -
- Android version: 12
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
reignofnether is most likely conflicting with optifine

**Comment by wayxyz89** [comment]
> reignofnether is most likely conflicting with optifine

Does this mean it doesn't support optifine?
