### ISSUE TITLE
[BUG] <Short description>crash code 1

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6243]
### Describe the bug

Crash when use modpack rad

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17688605/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: -
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

-

**Comment by GaucovyAero** [comment]
randompatches is conflicting with optifine or randompatches just doesnt work
