### ISSUE TITLE
[BUG] only new output is visible

### ISSUE THREAD

**Issue by Chaodeus** [PojavLauncherTeam/PojavLauncher#6244]
### Describe the bug

I am unable to see any output that was produced before I opened the live output viewer

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17689437/latestlog.txt)
![Screenshot_20241109-142616](https://github.com/user-attachments/assets/743de07c-2f2a-4e49-bf39-fb3f89a094eb)

### Steps To Reproduce

```markdown
luanch any version of minecraft
tap the gear icon on the top middle of the screen
tap log output
close the output
reopen the output
```

### Expected Behavior

any output that happened before opening the viewer should be visible

### Platform

```markdown
- Device model: AIGO a16
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try reinstalling pojav
