### ISSUE TITLE
[BUG] failed to read .jar 

### ISSUE THREAD

**Issue by BIoxland** [PojavLauncherTeam/PojavLauncher#6245]
### Describe the bug

When I execute a .jar it appears to not be able to read it nor understand it. I tried with many and yet no way to fix.

### The log file and images/videos

No clue how to take a screenshot

### Steps To Reproduce

```markdown
1 open the app
2 click on execute .jar file
3. Add a .jar file
```

### Expected Behavior

Cannot read .jar 

### Platform

```markdown
- Device model: android
- CPU architecture: \(-_-)/
- Android version: \(-_-)/
- PojavLauncher version: foxglove 20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
if its a mod you have to put it into .minecraft/mods
double clicking that jar on pc will also not work
