### ISSUE TITLE
[BUG] <Short description>crash -1

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6246]
### Describe the bug

I play mod and crash

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17689832/latestlog.txt)

### Steps To Reproduce

```markdown
1.sart pojav and crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: -
- Android version: 12
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
most likely optifine conflicting with valhelsia
