### ISSUE TITLE
[BUG] <Short description>exit code -1

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6248]
### Describe the bug

create map and crash

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17690232/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.create map
3.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: -
- Android version:12 
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
its most likely conflicting with optifine
