### ISSUE TITLE
Can pojavlauncher load "bin" folder?

### ISSUE THREAD

**Issue by NDG312** [PojavLauncherTeam/PojavLauncher#6251]
I want to play some beta 1.7.3 mods, so it must use bin folder. If not, is there any way i can install mods for this version?

**Comment by GaucovyAero** [comment]
the installation is different, you gotta create a custom version with a custom json
your custom jar goes into .minecraft/versions/your-custom-version/your-custom-version.jar

heres a guide
https://pojavlauncherteam.github.io/CUSTOM-MC.html

if you need more help tell me

**Comment by NDG312** [comment]
do you know how to fix the error like this https://github.com/PojavLauncherTeam/PojavLauncher/issues/2525#issue-1097035355
but i can't use optifine because it breaks texture of mods

**Comment by ghost** [comment]
Do you meaning this
![Screenshot_2024-11-16-19-50-28-248_com android chrome~2](https://github.com/user-attachments/assets/2d241250-c29e-4ee5-a91b-b9b879a5d765)
Turn off emissive textures

**Comment by NDG312** [comment]
I think they are not the same error

**Comment by NDG312** [comment]
and i'm using this version https://m.youtube.com/watch?v=KGPwPC7u03w&pp=ygURZmFybGFuZCBubyBqaXR0ZXI%3D

**Comment by GaucovyAero** [comment]
> do you know how to fix the error like this [#2525 (comment)](https://github.com/PojavLauncherTeam/PojavLauncher/issues/2525#issue-1097035355) but i can't use optifine because it breaks texture of mods

put this into /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt

LIBGL_ES=1

and use gl4es, all the entities (including you) are going to be lit up and you are going to get lower FPS, but at least you won't have the issue, kind of
