### ISSUE TITLE
[BUG] <Short description> for some reason when I used my pojav launcher with zink it's shows red screen with angel and crashed when vulkan

### ISSUE THREAD

**Issue by Yooboee69** [PojavLauncherTeam/PojavLauncher#6252]
### Describe the bug

![Screenshot_2024-11-10-18-27-33-124_net kdt pojavlaunch](https://github.com/user-attachments/assets/b1c51c22-5524-40ce-889b-1cc07f9fa5cd)

This happenes with angel vulkan

And 

It crashes with angel ( zink )

### The log file and images/videos

![Screenshot_2024-11-10-18-27-33-124_net kdt pojavlaunch](https://github.com/user-attachments/assets/3f87fac7-3a4d-47bb-aa41-0a5e63fabb51)

### Steps To Reproduce

```markdown
When I chose the vulkan and angel renderer and start the game 

It crashes if I had chosen vulkan

It shows red screen if I have as angel
```

### Expected Behavior

I want to play pojavlauncher with zink and vulkan , for shaders 

### Platform

```markdown
- Device model: 1.0.3.0 redmi 13 
- CPU architecture: octacore max 2.2 GHz | dinesnity 6100+
- Android version: 14
- PojavLauncher version: v3
```

### Anything else?

Please help me

**Comment by Yoidiotiamback** [comment]
Use this in pojavlauncher data MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460 crate a file named custom_env.txt and paste that. I think your crash should fixed if not go to githubs action tou will see update zink and turnip download it and run with zink renderer if you have good fps with zink use or use the ltw renderer same go to actions scroll down and you will see add renderer and compability checks click it download go to game renderer select ltw and ur to go

**Comment by Yooboee69** [comment]
> Use this in pojavlauncher data MESA_GL_VERSION_OVERRIDE=4.6 MESA_GLSL_VERSION_OVERRIDE=460 crate a file named custom_env.txt and paste that. I think your crash should fixed if not go to githubs action tou will see update zink and turnip download it and run with zink renderer if you have good fps with zink use or use the ltw renderer same go to actions scroll down and you will see add renderer and compability checks click it download go to game renderer select ltw and ur to go

Wait let me try

**Comment by Yooboee69** [comment]
> > Use this in pojavlauncher data MESA_GL_VERSION_OVERRIDE=4.6 MESA_GLSL_VERSION_OVERRIDE=460 crate a file named custom_env.txt and paste that. I think your crash should fixed if not go to githubs action tou will see update zink and turnip download it and run with zink renderer if you have good fps with zink use or use the ltw renderer same go to actions scroll down and you will see add renderer and compability checks click it download go to game renderer select ltw and ur to go
> 
> Wait let me try

Where am I supposed to put it in

**Comment by Yooboee69** [comment]
![Screenshot_2024-11-10-19-44-48-081_ru zdevs zarchiver](https://github.com/user-attachments/assets/320d2560-f3bb-4ddd-aa44-980148d8d7a3)

Where should I put it

**Comment by Yooboee69** [comment]
Bro where I am I suppose to put this file in
In which folder,

And what do you mean please tell me in detail I couldn't understand

**Comment by Dilen0001** [comment]
.

**Comment by Yooboee69** [comment]
> .

Can I get help

**Comment by GaucovyAero** [comment]
open custom_env.txt
and type this into it:
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GL_VERSION_OVERRIDE=460
