### ISSUE TITLE
[BUG] game crashes in 1.20.4 forge when using Simple Voice Radio

### ISSUE THREAD

**Issue by DarkOFC73** [PojavLauncherTeam/PojavLauncher#6255]
### Describe the bug

when i load the game it just shows me the red forge loading screen and then just crashes.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17692108/latestlog.txt)

### Steps To Reproduce

```markdown
1. start up forge 1.20.4 with Simple Voice Radio
2. the game crashes
```

### Expected Behavior

the game should load normally.

### Platform

```markdown
- Device model: Xiaomi Redmi Note 12 5G
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove_20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
most likely incompatible with your version of minecraft, it still might not work tho even if you manage to launch the game if it tries to use your hardware encoder instead of the software one
keep in mind you also have to grant pojav microphone permission

**Comment by DarkOFC73** [comment]
turns out that for some reason you need to install any mod that uses MixinExtras,i tried using Embeddium but just crashed when i try to load a world.
