### ISSUE TITLE
[BUG] Crash when using had enough items' searchbar

### ISSUE THREAD

**Issue by Neutron-a11y** [PojavLauncherTeam/PojavLauncher#6256]
### Describe the bug

I am playing Nomifactory Ceu version 1.7.3
Sometimes, when I use the had enough items searchbar, the game crashes.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17698432/latestlog.txt)
![Screenshot_2024-11-11-12-22-15-880_net kdt pojavlaunch](https://github.com/user-attachments/assets/a21b2a3a-2303-4e5f-a1eb-3a71bf5f4d3b)
![Screenshot_2024-11-11-12-22-21-820_net kdt pojavlaunch](https://github.com/user-attachments/assets/3766c0f7-0680-423b-86e2-f3a992132e9e)

### Steps To Reproduce

```markdown
1. Install nomifactory ceu as modpack profile 
2. Enter a server
3. Open inventory and use the searchbar in the bottom right corner of the screen
4. Sometimes it will crash
```

### Expected Behavior

The searchbar works normally and searches through the items

### Platform

```markdown
- Device model: POCO M6 5G 
- CPU architecture: 2x ARM cortex-A76 @2.20 ghz, 6x ARM cortex-A55 @2.00 ghz
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

The modpack works fine of pc, so it's a bug on pojavlauncher's side

**Comment by GaucovyAero** [comment]
the search bar requires opengl features which are not implemented in gl4es
