### ISSUE TITLE
[BUG] <Short description> não consigo criar minha conta

### ISSUE THREAD

**Issue by Unflybbff** [PojavLauncherTeam/PojavLauncher#6258]
### Describe the bug

Não consigo criar minha conta

### The log file and images/videos

J

### Steps To Reproduce

```markdown
Não consigo criar minha conta
```

### Expected Behavior

S

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 1
```

### Anything else?

S

**Comment by GaucovyAero** [comment]
log into minecraft.net and buy minecraft java edition first, then log into pojav with that account
