### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6262]
### Describe the bug

Idk what happen,when i enter the world it crash and say fatal error

### The log file and images/videos

[Uploading latestlog.txt…]()

### Steps To Reproduce

```markdown
1.run pojav
2.start Minecraft 
3.make new world 
4.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi note 11
- CPU architecture: -
- Android version: 12
- PojavLauncher version: glow worm latest
```

**Comment by wayxyz89** [comment]
[latestlog.txt](https://github.com/user-attachments/files/17716170/latestlog.txt)

**Comment by artdeell** [comment]
glow worm is not supported
