### ISSUE TITLE
Crash code 1

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6263]
### Describe the bug

Crash

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17716503/latestlog.txt)

### Steps To Reproduce

```markdown
1.run pojav
2.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: -
- Android version:12 
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
put -Dsodium.checks.issue2561=false into your jvm arguments

**Comment by wayxyz89** [comment]
> put -Dsodium.checks.issue2561=false into your jvm arguments

Thanks it workedddd
