### ISSUE TITLE
[F-Req] <Short description> 1

### ISSUE THREAD

**Issue by Cleokocham134** [PojavLauncherTeam/PojavLauncher#6267]
### Is this request related to a bug?

Pokazuje za nie mam konta a mam konto

### Describe the request.

Chcę zagrać w Minecraft 

### Anything else?

Nie chce mi się załadować

**Comment by Cleokocham134** [comment]
Nie mogę grać

**Comment by GaucovyAero** [comment]
log into minecraft.net first
