### ISSUE TITLE
Crash when make world

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6268]
### Describe the bug

Idk what happen When i make a world it crashes saving world

### The log file and images/videos

[crash-2024-11-13_21.24.01-client.txt](https://github.com/user-attachments/files/17734042/crash-2024-11-13_21.24.01-client.txt)

### Steps To Reproduce

```markdown
1.crssh
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: -
- Android version: 12
- PojavLauncher version: latest
```

**Comment by RainbowyGuy** [comment]
The same thing happened to me on computer, but it was on a server, and the thing was that the server wasn't turned on. But it's probably not the answer you need in this case.

**Comment by wayxyz89** [comment]
> The same thing happened to me on computer, but it was on a server, and the thing was that the server wasn't turned on. But it's probably not the answer you need in this case.

Do you know how to fix it?

**Comment by RainbowyGuy** [comment]
> > The same thing happened to me on computer, but it was on a server, and the thing was that the server wasn't turned on. But it's probably not the answer you need in this case.
> 
> Do you know how to fix it?

Sorry, no. But could I maybe know if you have any mods? Or other rendering than the default gl4les? And also version, since those are very important things when making a bug report.

**Comment by GaucovyAero** [comment]
most likely an issue with your modpack, i cant really tell what caused it, remove some mods yourself and see which one is causing it
