### ISSUE TITLE
[BUG] <Zink Problem>

### ISSUE THREAD

**Issue by AzzrailX** [PojavLauncherTeam/PojavLauncher#6271]
### Describe the bug

I have the screen error when i open it which Zink.

### The log file and images/videos

[2024-11-13-1.log.gz](https://github.com/user-attachments/files/17743542/2024-11-13-1.log.gz)
![Screenshot_20241114_102941_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/a526ca44-09b7-4958-a742-d209c91db34b)
![Screenshot_20241114_094134_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/9ba3aae8-fc90-4457-bec3-13b0700d6846)

### Steps To Reproduce

```markdown
1. Start pojav
2. See the screen error
```

### Expected Behavior

I think i get fix of that.

### Platform

```markdown
- Device model: Samsung Galaxy S24+
- CPU architecture: arm64x
- Android version: 14
- PojavLauncher version: foxglove-20240922-абаба29-v3_openjdk
```

**Comment by Bel69420** [comment]
Known issue, can't be fixed as zink wasn't developed by PojavlauncherTeam

**Comment by Bel69420** [comment]
This is clearly your GPU driver problem which mean you're completely screwed (you can't update gpu driver on phone)

**Comment by AzzrailX** [comment]
> This is clearly your GPU driver problem which mean you're completely screwed (you can't update gpu driver on phone)

😭

**Comment by GaucovyAero** [comment]
xclipse gpus are not supported, turn on power saving mode or something, maybe thats going to force your phone to use your other gpu, it should work then
