### ISSUE TITLE
[GPU] <allow the minecraft to use your phone GPU>

### ISSUE THREAD

**Issue by windtheminer** [PojavLauncherTeam/PojavLauncher#6273]
### Is this request related to a bug?

NA

### Describe the request.

insted of emulating gpu for minecraft,use the phone gpu for better performance

### Anything else?

NA

**Comment by artdeell** [comment]
We already do that. We use translation layers to get OpenGL for Minecraft, because Android only supports OpenGL ES (which is different and not directly compatible) and Vulkan.

**Comment by ONINUM** [comment]
Good

**Comment by SSKILLERS123** [comment]
Wdym?
