### ISSUE TITLE
[BUG] constant freezes while playing rlcraft

### ISSUE THREAD

**Issue by epicspacecat** [PojavLauncherTeam/PojavLauncher#6274]
### Describe the bug

I reinstalled the rlcraft modpack and it constatly freezes after that, also im trying to get callable horses mod to work and it isnt working maybe you can figure out how to fix it

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17748190/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install rlcraft modpack
3. Open a World with rlcraft
4. Get freezes
```

### Expected Behavior

Playing game normally

### Platform

```markdown
- Device model: Huawei p40 lite 
- CPU architecture: arm64 
- Android version: 10 
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment]
your device is not capable enough, try putting more memory allocation, if you cant, you just cant, thats it
