### ISSUE TITLE
[BUG] crash while loading all the mods 9 modpack (atm9), which mods to remove? 

### ISSUE THREAD

**Issue by epicspacecat** [PojavLauncherTeam/PojavLauncher#6275]
### Describe the bug

I crash after red screen and get -1 error, can you help me? I removed corgilib mod as recomended, which mods to remove? 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17748972/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install all the mods 9 modpack
3. Go to all the mods 9 mod folder and delete corgilib mod
4. Start modpack
5. Wait a bit on red screen
6. Get crashed
```

### Expected Behavior

Launching and playing all the mods 9 modpack 

### Platform

```markdown
- Device model: Huawei p40 
- CPU architecture: arm64 
- Android version: 10 
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

I hope you will help me

**Comment by GaucovyAero** [comment]
you have to have a snapdragon chip for create to work on gl4es, use zink instead
