### ISSUE TITLE
[BUG] mods no can load 

### ISSUE THREAD

**Issue by MAXLAN2089** [PojavLauncherTeam/PojavLauncher#6277]
### Describe the bug

My mod pack no can load 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17758246/latestlog.txt)

### Steps To Reproduce

```markdown
Open pojav with the mods
```

### Expected Behavior

Enter on the menu

### Platform

```markdown
- Device model:poco x5 pro
- CPU architecture:arm64
- Android version:14
- PojavLauncher version:foxglove 2024
```

### Anything else?

I need help

**Comment by GaucovyAero** [comment]
remove optifine
