### ISSUE TITLE
[BUG] Chat Click Actions/Hover Are misaligned

### ISSUE THREAD

**Issue by Slixxthedev** [PojavLauncherTeam/PojavLauncher#6279]
### Describe the bug

The Chat Click/Hover is misaligned 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17770642/latestlog.txt)
![Screenshot_2024-11-15-11-51-37-077_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/8683227b-5a32-4278-b2e5-2a6886332dda)
![Screenshot_2024-11-15-11-51-28-264_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/8f53a3bd-e573-4386-adb2-d93a2a8f0192)
![Screenshot_2024-11-15-11-51-22-496_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/c87a72be-7618-409a-9b8f-3f9733a1fed8)
![Screenshot_2024-11-15-11-51-03-174_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/5713bd4d-9d6f-4230-9165-a1ae0f007c31)

### Steps To Reproduce

```markdown
1. Start any latest version with LTW Renderer.
2. Load into a world
3. Send some commands, (most probably /locate)
4. See the misaligned hover/click action in the chat
```

### Expected Behavior

Expected the game to run normally.

### Platform

```markdown
- Device model: Redmi Note 12 5G 
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20241004-14a0907-feat/tinywrapper
```

### Anything else?

This apparently seems to affect latest versions on LTW Renderer

**Comment by GaucovyAero** [comment]
has to be tested again when LTW goes back into testing, in the meantime try messing with the ignore notch setting or try different versions of the game to see if it gets any better
