### ISSUE TITLE
[BUG] Shadow bug with entity models

### ISSUE THREAD

**Issue by zozogame1** [PojavLauncherTeam/PojavLauncher#6281]
### Describe the bug

Entity models seems to be glitched with some sort of shadow bug. This includes the player himself, items (dropped or not) and mobs like animals or hostile one.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17770806/latestlog.txt)
![Screenshot_20241115_073149_net_kdt_pojavlaunch_MainActivity](https://github.com/user-attachments/assets/0c0a230f-516c-48a5-9efc-9d6b3668ff4d)
![Screenshot_20241115_073158_net_kdt_pojavlaunch_MainActivity](https://github.com/user-attachments/assets/1b641caf-c1bb-4086-8908-9bd6f550424a)
![Screenshot_20241115_073208_net_kdt_pojavlaunch_MainActivity](https://github.com/user-attachments/assets/25658582-bf6e-402c-bfde-eb711eb401ad)
![Screenshot_20241115_073424_net_kdt_pojavlaunch_MainActivity](https://github.com/user-attachments/assets/f4c7ec6b-b85d-43dd-8175-4ce24e89e7b0)
![Screenshot_20241115_073647_net_kdt_pojavlaunch_MainActivity](https://github.com/user-attachments/assets/f9f5cc94-ba54-42e9-8d11-f2b84af776cf)

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Create/load a world (IN ALPHA VERSIONS)
3. See by yourself
```

### Expected Behavior

I thought the entity models would be fine.

### Platform

```markdown
- Device model: Honor 70 Lite
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by BNaise** [comment]
What renderer you are using?

**Comment by zozogame1** [comment]
> What renderer you are using?

The one by default

**Comment by zozogame1** [comment]
I tried the other one (ZINK) and pretty much the same problem but it's flashing

https://github.com/user-attachments/assets/25aeb57e-0a13-406a-9a9f-5292b5e10850

**Comment by GaucovyAero** [comment]
in /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt (if it doesnt exist, create that file)

if you put
`LIBGL_ES=2` into custom_env.txt, on gl4es, you are going to get this issue

if you put
`LIBGL_ES=1` into custom_env.txt, on gl4es, all entities are going to be lit up but the halved lighting isnt going to be there

if you really wanna fix it, you have to install optimine/optifine (means using minecraft b1.1_02 or higher)
the reindev minecraft mod also has this halved lighting pojav issue fixed
https://www.mediafire.com/file/y0qkkyibyuz7tp1/OptiFine_History_b1.1_02_-_b1.9p5_v2.zip/file
