### ISSUE TITLE
[BUG] <I'm trying to test my zombie zombie apocalyptic world>

### ISSUE THREAD

**Issue by KURTAINFDSH** [PojavLauncherTeam/PojavLauncher#6285]
### Describe the bug

Its not a bug but I need help whats the problem it keep crashing when its done loading

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17783422/latestlog.txt)

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

Its will continue to home screen

### Platform

```markdown
- Device model: tecno bg6
- CPU architecture: 
- Android version: 13
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
update pojav to the latest version
