### ISSUE TITLE
[BUG] <just black screen>

### ISSUE THREAD

**Issue by KURTAINFDSH** [PojavLauncherTeam/PojavLauncher#6286]
### Describe the bug

I'm using fabric and Minecraft 1.20.1
I trying to use a mod but it just showing a 
Black screen

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/17783875/latest.log)

### Steps To Reproduce

```markdown
Jj
```

### Expected Behavior

I expect it to continue to loading screen 

### Platform

```markdown
- Device model: tecno bg6
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

Like I said I'm trying to use mod but when I luanch the game it just showing 
Me blackscreen but without a mod there is no problem no blackscreen

**Comment by Zahar2loshara** [comment]
Same thing, it was some android shit
But you can for example download modpack (remove all sodium related stuff) and it works! So there is some way, but i dunno how its avoid being bugged

When firstly download loader and **dont enter yet** and add mods and then enter it works

**Comment by GitAlasGo** [comment]
> Same thing, it was some android shit But you can for example download modpack (remove all sodium related stuff) and it works! So there is some way, but i dunno how its avoid being bugged

@Zahar2loshara Can you please explain more clearly?

Also can you help me with jenny mod having black screen? https://github.com/PojavLauncherTeam/PojavLauncher/issues/1948#issuecomment-2488265251

Thanks.

**Comment by Zahar2loshara** [comment]
My details and issue is #6091

And s_x mods was blocked by Pojavlauncher, check unsupported mods [here](https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html)

**Comment by Zahar2loshara** [comment]
@GitAlasGo hmmm, i checked now and yea, it doesn't have it, but it was there, let me check archive...
Edit: [here](https://web.archive.org/web/20240123183256/https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html#other-mods) it was, i dunno why it was removed, maybe too hard or like that

**Comment by GaucovyAero** [comment]
use files by marc to move the files
