### ISSUE TITLE
[BUG] <Short description>when i try to sign in it keeps on saying put ur problem in this website can u pls fix it

### ISSUE THREAD

**Issue by 1234max73** [PojavLauncherTeam/PojavLauncher#6287]
### Describe the bug

it keeps on showing up and i am geting mad like i cant make a acc i didnt buy a acc i was trying to make one and it is bot workin i put the password in and the email and it keeps on saying not working

### The log file and images/videos

i dont know

### Steps To Reproduce

```markdown
i dont know
```

### Expected Behavior

i dont know

### Platform

```markdown
- Device model: infnix
- CPU architecture: i dont know
- Android version: infnix
- PojavLauncher version: 1.21
```

### Anything else?

nope

**Comment by GaucovyAero** [comment]
not a pojav issue, you have to fix your microsoft account and buy minecraft java edition
