### ISSUE TITLE
v3.3.1 mouse right click not working [BUG]

### ISSUE THREAD

**Issue by golimonkey** [PojavLauncherTeam/PojavLauncher#629]
In PojavLauncher 3.3.1 with integrated java running mc 1.16.5, right mouse button does nothing(canot place blocks). Keyboard works great and rest of mouse functions work great. 

Btw game works at locked 60FPS, with render @ 5 chunks and fancy graphics on Pocophone F1 android 10.

Awsome yob guys, ty very much.

**Comment by matt995** [comment]
Is it the otg one as in recent action builds its fixed by going into settings and using back as right click

**Comment by EnderBrine99FOX** [comment]
@matt995 Me 2 When I Play With My Mouse And Keyborad Right Click Not Working So I Hope They Will Fix It Soon

**Comment by khanhduytran0** [comment]
@EnderBrine99FOX enable "Treat right click as right mouse" as him.

**Comment by EnderBrine99FOX** [comment]
> @EnderBrine99FOX enable "Treat right click as right mouse" as him.

Where I Can Find It?

**Comment by khanhduytran0** [comment]
It's at launcher settings.

**Comment by EnderBrine99FOX** [comment]
> It's at launcher settings.

i couldn't Find It Can You Plz Show Me Where? 

Sorry For Annoying You❤️

**Comment by AutumnVN** [comment]
> > It's at launcher settings.
> 
> i couldn't Find It Can You Plz Show Me Where?
> 
> Sorry For Annoying You❤️

![Screenshot_2021-02-24-15-10-04-23](https://user-images.githubusercontent.com/77253698/108967782-81457080-76b2-11eb-9816-a957aff6f596.png)
if u cant find it, update your launcher

**Comment by EnderBrine99FOX** [comment]
> > > It's at launcher settings.
> > 
> > 
> > i couldn't Find It Can You Plz Show Me Where?
> > Sorry For Annoying You❤️
> 
> ![Screenshot_2021-02-24-15-10-04-23](https://user-images.githubusercontent.com/77253698/108967782-81457080-76b2-11eb-9816-a957aff6f596.png)
> if u cant find it, update your launcher

ohh My Luncher Version is 3.3.1.1
Can Tou Give Your Luncher Link? 

Thank You!

**Comment by AutumnVN** [comment]
> > > > It's at launcher settings.
> > > 
> > > 
> > > i couldn't Find It Can You Plz Show Me Where?
> > > Sorry For Annoying You❤️
> > 
> > 
> > ![Screenshot_2021-02-24-15-10-04-23](https://user-images.githubusercontent.com/77253698/108967782-81457080-76b2-11eb-9816-a957aff6f596.png)
> > if u cant find it, update your launcher
> 
> ohh My Luncher Version is 3.3.1.1
> Can Tou Give Your Luncher Link?
> 
> Thank You!

go to actions, download latest "v3_openjdk"
or
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/594914945

**Comment by EnderBrine99FOX** [comment]
> > > > > It's at launcher settings.
> > > > 
> > > > 
> > > > i couldn't Find It Can You Plz Show Me Where?
> > > > Sorry For Annoying You❤️
> > > 
> > > 
> > > ![Screenshot_2021-02-24-15-10-04-23](https://user-images.githubusercontent.com/77253698/108967782-81457080-76b2-11eb-9816-a957aff6f596.png)
> > > if u cant find it, update your launcher
> > 
> > 
> > ohh My Luncher Version is 3.3.1.1
> > Can Tou Give Your Luncher Link?
> > Thank You!
> 
> go to actions, download latest "v3_openjdk"
> or
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/594914945

Thank You Its Worked!!❤️

**Comment by Mathias-Boulay** [comment]
Since this feature has been merged into mainline and is now available via google play, closing the issue.
