### ISSUE TITLE
[BUG] Broken water rendering in Holy GL4ES with Fabulous graphics

### ISSUE THREAD

**Issue by kran27** [PojavLauncherTeam/PojavLauncher#6290]
### Describe the bug

On latest version (both vanilla and OptiFine) water has various rendering issues such as going through blocks its in front of and showing faces of distant blocks through closer ones. 

### The log file and images/videos

![Screenshot_20241117-115532](https://github.com/user-attachments/assets/7b6c8ddd-9e69-46f1-97b1-b2167cb625a8)

### Steps To Reproduce

```markdown
Launch with Holy GL4ES and Fabulous graphics (Zink crashes and ANGLE renders fine but is slow, fancy and fast graphics are unaffected)
```

### Expected Behavior

Water should look correct and not show faces of blocks far in distance through it

### Platform

```markdown
- Device model: Pixel 9
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20241115-edib879-v3_openjdk
```

**Comment by GaucovyAero** [comment]
we cant support this, probably an issue with shader precision

**Comment by GaucovyAero** [comment]
gl4es has already been pushed extremely far in terms of compatibility in its current state
