### ISSUE TITLE
[BUG] Pojavlauncher can't detect mod files inside the mods folder

### ISSUE THREAD

**Issue by Entitygamer66** [PojavLauncherTeam/PojavLauncher#6292]
### Describe the bug

I can run the game well, however i have a new issue. When i try to put mods into the mods folder, forge can't detect any mods even though i put them in the mods folder. I think i found out what causes this bug is pojavlauncher doesn't have a permission to access the files according to the log below, and i can't seem to grant permission to my storage. Because of this, i can't play any mods. Can you fix this? I play forge 1.7.10.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17799493/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open Pojavlauncher 
2. Select forge version(1.7.10, i haven't tried other versions yet)
3. Run Minecraft
```

### Expected Behavior

I expected it to play with mods.

### Platform

```markdown
- Device model: Vivo y02s
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: latest version
```

**Comment by GaucovyAero** [comment]
use files by marc to move the files
