### ISSUE TITLE
Visual bug which makes text look glowy and weird UI behaviour

### ISSUE THREAD

**Issue by IraqLobster37** [PojavLauncherTeam/PojavLauncher#6293]
### Describe the bug

When I launch a game, no matter which version or runtime, the UI acts weird, also I'm unable to join any world, singleplayer or multiplayer. Some text is glowly and I can't really describe it, so there will be a few screenshots below:

### The log file and images/videos

![Screenshot_20241118_191225_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/473fb43c-4aab-4466-8826-152bf8e530ae)
![Screenshot_20241118_191218_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/92178173-67f4-461c-8ce2-a3f678ab7e2e)
![Screenshot_20241008_193423_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/9d98e3f5-ae3a-4444-a041-f12f70c4b92c)
[latestlog.zip](https://github.com/user-attachments/files/17804776/latestlog.zip)

### Steps To Reproduce

```markdown
I open the game and it just happens , nothing more to that.
```

### Expected Behavior

Normal Minecraft, no glowy text or UI bugs and being able to join worlds.

### Platform

```markdown
- Device model: SM-A137F/DSN
- CPU architecture: arm
- Android version: 14
- PojavLauncher version: foxglove-20241115-ed1b879-v3_openjdk
```

### Anything else?

I've tried running different runtimes such as jave 18, 17 and 21. I've also tried running it in all the rendering engines but nothing worked. The game also used to work normally before that.

**Comment by GaucovyAero** [comment]
send log and screenshots with gl4es

**Comment by IraqLobster37** [comment]
I have already provided screenshots and log above but here you go:
[latestlog.txt](https://github.com/user-attachments/files/17913097/latestlog.txt)
![Screenshot_20241126_062649_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/ad35aa72-3b75-4358-9f37-3e777aa14dec)
![Screenshot_20241126_062640_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/22498089-34b5-4862-aa66-dfcc0748360c)
![Screenshot_20241126_062626_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/907e4008-77ea-4d3a-bdf1-01c96f4e12e5)
![Screenshot_20241126_062611_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/88abb9d7-a1c2-4724-9651-109f5e953f07)
I have also noticed this In the log: 
ERROR StatusConsoleListener appender Console has no parameter that matches element Policies [06:25:23] [main/WARN]: Failed retrieving info for group processor java.lang.Error: There is an incompatible JNA native library installed on this system Expected: 7.0.0 Found: 6.1.6

**Comment by IraqLobster37** [comment]
I just updated the game and the bug appears to be fixed!
