### ISSUE TITLE
Optifine bug

### ISSUE THREAD

**Issue by Coryxkenshin-pixel** [PojavLauncherTeam/PojavLauncher#6295]
### Describe the bug

When I get in my world and put my shaders on it shows this 
![Screenshot_20241118_184304_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/50e51af3-2682-4c86-a969-65c39ad83429) this also hapen on every version of optifine I think.

### The log file and images/videos

Heres the log file 
[Uploading latestlog.txt…]()

### Steps To Reproduce

```markdown
First download optifine it can be any version then download shaders and then enter on your world and put the shaders and thats it.
```

### Expected Behavior

I expect that this dosent happen

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No thats it

**Comment by Bel69420** [comment]
Don't use shader. Don't expecting a phone to run an OpenGL shaders, phone only supports GLES.

**Comment by Bel69420** [comment]
GL4ES cannot run shaders because it only supports gl 2.0 while zink required proper Vulkan driver (some phone might have broken or good driver) but still slow

**Comment by Coryxkenshin-pixel** [comment]
Know it shows this 
![Uploading Screenshot_20241119_154722_PojavLauncher (Minecraft Java Edition for Android).jpg…]()

**Comment by Coryxkenshin-pixel** [comment]
Know it shows this
![Screenshot_20241119_154722_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/14376741-66ac-4b9c-9806-54b099c76175)

**Comment by GaucovyAero** [comment]
shaders wont work on gl4es
