### ISSUE TITLE
Fabric 1.21.3 crash

### ISSUE THREAD

**Issue by BNaise** [PojavLauncherTeam/PojavLauncher#6296]
### Describe the bug

Fabric 1.21.3 crashing because of fabric-api-0.109.0+1.21.3

### The log file and images/videos

Here the latest log :-
[latestlog.txt](https://github.com/user-attachments/files/17813337/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Select fabric loader 0.16.9 - 1.21.3
3. Play
4. Crash
```

### Expected Behavior

Not crash

### Platform

```markdown
- Device model: CPH2667
- CPU architecture: 
- Android version: 14
- PojavLauncher version: vfoxglove-20241115-ed1b879-v3_openjdk
```

**Comment by GaucovyAero** [comment]
use files by marc to move the mod files
