### ISSUE TITLE
[BUG] <Error in app>

### ISSUE THREAD

**Issue by MrDimos1234** [PojavLauncherTeam/PojavLauncher#6300]
### Describe the bug

I press play to start my game but it shows this. I have an Poco F6, HyperOS, 12gb Ram (8gb is Memory Extension Setting)
![Screenshot_2024-11-15-19-14-23-474_net kdt pojavl2aunch](https://github.com/user-attachments/assets/ee532032-0566-4371-99f8-375875a0d54a)

### The log file and images/videos

![Screenshot_2024-11-15-19-14-23-474_net kdt pojavl2aunch](https://github.com/user-attachments/assets/4120360d-a829-4216-9e53-e4938c1fe8d0)

### Steps To Reproduce

```markdown
Start Pojav Laumcher, i press start and when this
```

### Expected Behavior

To open the game

### Platform

```markdown
- Device model: Poco F6
- CPU architecture: Idk
- Android version: 14
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
not a pojav issue, fix your microsoft account accoring to the instructions
