### ISSUE TITLE
Datapacks is not working

### ISSUE THREAD

**Issue by Ismail1237** [PojavLauncherTeam/PojavLauncher#6302]
### Steps To Reproduce

1. Start the game and type the
2. /datapack list enabled command
3. The datapacks should be listed as enabled.
 However, the datapacks are not working in the game
### How to Fix
1 download the mod https://datapack.org/ https://modrinth.com/
Type to chat /datapack fix <your datapack name.(your extension like.zip(if this is a Archive if A  do it folder write folders name Only )>

**Comment by GaucovyAero** [comment]
follow this video

https://www.youtube.com/watch?v=m4JI3cSudFc

terralith works for me, look

![Screenshot_20241228-151242_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/user-attachments/assets/8f3f17ca-e4ad-4414-a96d-52118904417d)

**Comment by Ismail1237** [comment]
Bro i sloved My datapack problem thanks for
help but this wouldn't work on me

28 Ara 2024 Cmt 18:15 tarihinde GaucovyAero ***@***.***> şunu
yazdı:
