### ISSUE TITLE
Mouse scaling set to 25%

### ISSUE THREAD

**Issue by ImNotTheC35** [PojavLauncherTeam/PojavLauncher#6304]
### Describe the bug

The "Mouse scaling" setting is broken, it set to 25%

### The log file and images/videos

[Video](https://github.com/user-attachments/assets/72ac7067-9c8b-4465-af93-59151f2a75bb)
**No log file**

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Click the Settings
3. Go to "Control customization"
4. Change the "Mouse scaling"
5. Back
6. Check the Mouse scaling again
```

### Expected Behavior

I expected it to not set to 25% and I can set it to 75%

### Platform

```markdown
- Device model: Realme 5 Pro(RMX1971)
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: foxglove-20241122-19dc51f-feat/quick_settings
```

**Comment by Mathias-Boulay** [comment]
Hi @ImNotTheC35 thank you for the report ! I managed to reproduce the issue. A fix for it should be shortly available, given the small scope of the issue.

**Comment by Mathias-Boulay** [comment]
Fix done.

**Comment by ImNotTheChiku35** [comment]
It is fixed, thanks!
