### ISSUE TITLE
Can you add please 

### ISSUE THREAD

**Issue by Renerosal01234** [PojavLauncherTeam/PojavLauncher#6306]
### Is this request related to a bug?

Can you add auto clicker

### Describe the request.

I mean adjusting how many clicks per second like 50 click per second on control please 🥺

### Anything else?

I hope you consider

**Comment by VenomousSteam81** [comment]
Nah, it won't get added. We don't need any kind of cheat to be a feature in the launcher.

**Comment by SticksS123** [comment]
Dumb kids 🤣
