### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Arthurxl15** [PojavLauncherTeam/PojavLauncher#6307]
### Is this request related to a bug?

Como resolver de não conseguir baixar os forge 

### Describe the request.

![Screenshot_20241124-112020](https://github.com/user-attachments/assets/ffa1d8a1-3296-48f3-bd88-5590e0684536)
![Screenshot_20241124-111717](https://github.com/user-attachments/assets/a4c20a96-01c2-4201-aa10-0d1a88df369e)

**Comment by TarikBR** [comment]
O maven do forge está instável, só aguardar eles resolverem, tenta baixar mais tarde

![image](https://github.com/user-attachments/assets/eac949df-f474-46db-aa4c-22e3321a98b0)
