### ISSUE TITLE
[BUG] <Short description> Fabric Black Screen No Log Output

### ISSUE THREAD

**Issue by xdboomer69** [PojavLauncherTeam/PojavLauncher#6308]
### Describe the bug

So I can open fabric without any mods and it works fine but the second I add even the API it sits on a black screen and the log output is empty like it doesn't even try to load I even uninstalled and it still won't work.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17895755/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open Pojav
2. Sit on black screen until I close it.
```

### Expected Behavior

Open normally like everyone else.

### Platform

```markdown
- Device model: Google Pixel 6
- CPU architecture: Octa-core (2x2.8 GHz Cortex-X1 & 2x2.25 GHz Cortex-A76 & 4x1.8 GHz Cortex-A55)
- Android version: Android 15
- PojavLauncher version: foxglove-20241119-a5d02c1-v3_openjdk
```

**Comment by GaucovyAero** [comment]
permission denied, use the default file manager to move the files
if its hidden on your device (in your case it is hidden), you have to install files by marc from play store to access it

**Comment by xdboomer69** [comment]
It didn't work dude I can't move to my android app data because of Android privacy features even with show hidden files on why did u close it it didn't fix it only app that works for moving is archiver and file manager +.
