### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by nxsto** [PojavLauncherTeam/PojavLauncher#6309]
### Describe the bug

Я запуская поджав с модами на версию 1.21 моды все должны подходить но у меня крашится маинкрафт.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17901531/latestlog.txt)

### Steps To Reproduce

```markdown
1.запускаю поджавлаунчер нажимаю играть жду и крашит
```

### Expected Behavior

Я ожидаю что я смогу поиграть в майнкрафт 

### Platform

```markdown
- Device model: Samsung A52 256gb
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
in the log, fabric is giving you a potential solution to the problem, you can read the log with Acode editor from Play Store.
