### ISSUE TITLE
Bugged textures

### ISSUE THREAD

**Issue by J-Lazos** [PojavLauncherTeam/PojavLauncher#6311]
### Describe the bug

Some textures seem to be replaced by others. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17905843/latestlog.txt)
![Screenshot_2024-11-25-09-01-06-695_net kdt pojavlaunch](https://github.com/user-attachments/assets/02e0d4e4-55e1-414c-a5b6-40e8a379e647)
![Screenshot_2024-11-25-09-08-04-436_net kdt pojavlaunch](https://github.com/user-attachments/assets/1a853c70-9880-4278-adac-4e73849455e7)
![Screenshot_2024-11-25-10-05-37-730_net kdt pojavlaunch](https://github.com/user-attachments/assets/496551b6-b0d2-4852-aa18-648a699441e4)
![Screenshot_2024-11-25-10-08-44-120_net kdt pojavlaunch](https://github.com/user-attachments/assets/3fc4e3ff-36df-4d57-b066-051c5b453517)
![Screenshot_2024-11-25-10-09-25-657_net kdt pojavlaunch](https://github.com/user-attachments/assets/8000f34f-7944-4285-b344-460f0af98b14)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Enter a world
```

### Expected Behavior

I expect to have normal textures. 

### Platform

```markdown
- Device model: Xiaomi Poco X4 GT
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20241119-a5d02c1-v3_openjdk
```

### Anything else?

I've had this bug since I started using pojav Launcher and it occurs in every modded version of the game.

**Comment by GaucovyAero** [comment]
out of gpu memory, happens when the textures atlas is too big (i. e. you have too many mods)
