### ISSUE TITLE
[BUG] <render glitches in modpack>

### ISSUE THREAD

**Issue by Greatpug** [PojavLauncherTeam/PojavLauncher#6314]
### Describe the bug

So I recently installed the better mc modpack and have come across some unforeseen issues. The blocks surrounding me do not load . Monsters and mobs load perfectly pls fix 
![Screenshot_2024-11-26-14-43-58-22_b9530d923fff59dfb5cdc6a8e8e3c8af](https://github.com/user-attachments/assets/84351a95-b909-460a-b1f1-8a414130b249)

### The log file and images/videos

![Screenshot_2024-11-26-14-43-58-22_b9530d923fff59dfb5cdc6a8e8e3c8af](https://github.com/user-attachments/assets/d45e6279-aca3-4484-b22d-8eeea56734ac)

### Steps To Reproduce

```markdown
1. Install better mc modpack
2. Load into world
3. See no textures
```

### Expected Behavior

Blocks to load

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
probably caused by one of your mods, figure out which one it is first
