### ISSUE TITLE
Jna issue

### ISSUE THREAD

**Issue by littleboulderbro** [PojavLauncherTeam/PojavLauncher#6316]
### Describe the bug

I can't launch 1.21+ because the dna is incorrect and also I can't fox it cause my file thing (arm64) isn't even in the files

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17927514/latestlog.txt)

### Steps To Reproduce

```markdown
Im just starting the game on the latest version of the launcher+version
```

### Expected Behavior

I wanna play th game

### Platform

```markdown
- Device model: fire HD 11
- CPU architecture: arm64
- Android version: lastest?
- PojavLauncher version: latest from playstore
```

### Anything else?

😫

**Comment by hiimabignoobwihenolive** [comment]
Same problem happening

**Comment by littleboulderbro** [comment]
> Same problem happening

Any ideas why?

**Comment by hiimabignoobwihenolive** [comment]
nope no ideas

**Comment by GaucovyAero** [comment]
probably just out of memory

**Comment by littleboulderbro** [comment]
> probably just out of memory

No It discribes the jna being wrong in the log
