### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6317]
### Describe the bug

Idk when i play atm9 modpack it happens 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17928191/latestlog.txt)

### Steps To Reproduce

```markdown
1.run
2.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: -
- Android version:12 
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
unsupported lwjgl method
