### ISSUE TITLE
[BUG] <Short description> tolong ya ada kesalahan aku gak bisa microsof

### ISSUE THREAD

**Issue by Gamin4910** [PojavLauncherTeam/PojavLauncher#6318]
### Describe the bug

Tolong ada kesalahan bug aku gak bisa microsof 

### The log file and images/videos

Tolong ada bug di pojav launcher 

### Steps To Reproduce

```markdown
Pojav launcher ada kesalahan Bug gak bisa microsof
```

### Expected Behavior

Tolong ya bang 

### Platform

```markdown
- Device model: roopek 
- CPU architecture: aku 
- Android version: Infinix 
- PojavLauncher version: 1.20.1
```

**Comment by wayxyz89** [comment]
Beli akun java dulu dek🤣

**Comment by Gamin4910** [comment]
Cara kak


Pada Rab, 27 Nov 2024 11.07, Uhak9373728 ***@***.***> menulis:

**Comment by GaucovyAero** [comment]
log into minecraft.net
