### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by MRKing6377** [PojavLauncherTeam/PojavLauncher#6319]
### Is this request related to a bug?

Can't login to Microsoft account 

### Describe the request.

Please fix it quickly

### Anything else?

![Screenshot_20241127-223250](https://github.com/user-attachments/assets/ce443d77-af4a-4aef-9e67-f15c025b8af9)
![Screenshot_20241127-223253](https://github.com/user-attachments/assets/8cb0479c-20d4-4fcb-b123-9c7964f44ef0)

**Comment by GaucovyAero** [comment]
log into minecraft.net
