### ISSUE TITLE
Microsoft login error

### ISSUE THREAD

**Issue by bubbelbadHD** [PojavLauncherTeam/PojavLauncher#632]
I just updated my pojav launcher and now when I try microsoft login it gives an error
java.lang.RuntimeException: MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:276)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:208)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Please help me

**Comment by artdeell** [comment]
You need to actually buy the game on this Microsoft account.

**Comment by bubbelbadHD** [comment]
How can I do that. Cuz in don't have a pc so I use pojav launcher

**Comment by artdeell** [comment]
Go to https://minecraft.net and buy the game (Java Edition for PCs)

**Comment by bubbelbadHD** [comment]
I cant buy because my mom will not permit me for it 😭😭

**Comment by bubbelbadHD** [comment]
Pls help me

**Comment by netkv** [comment]
bruh
you need to buy game, there is no other help
~~unless you install kali and hack entire mojangosoft thingy~~

**Comment by Google61** [comment]
Tick the `Login as a offline account` option to play without Minecraft license

**Comment by bubbelbadHD** [comment]
Thx guys so much

**Comment by bubbelbadHD** [comment]
It is not working

**Comment by Google61** [comment]
First, make sure you are updated to 3.3.1, second, make sure you provide some additional info while typing 
> It is not working

**Comment by bubbelbadHD** [comment]
When I open launcher, there is Microsoft login thingy. When I click it it redirects me to Microsoft page. When I login it shows loading files and gives the error

**Comment by khanhduytran0** [comment]
So, you want login with a demo account anyways????

**Comment by Google61** [comment]
Input nickname, tick `Login as a offline account`, press `Login`. That's it.

**Comment by bubbelbadHD** [comment]
I wanna play hypixel and other premium server. I got one alt which was banned on all premium servers. Please fix this issue

**Comment by bubbelbadHD** [comment]
I wanna login to all premium servers and alts are temporary. So I wanna login to Microsoft but the error doesn't let me login so please please fix the issue as soon as possibel

**Comment by khanhduytran0** [comment]
What you need is to buy Minecraft to continue. Microsoft login does not provide free premium account.

**Comment by bubbelbadHD** [comment]
Oh no :(

**Comment by bubbelbadHD** [comment]
I have to see if an app can run windows on android

**Comment by khanhduytran0** [comment]
> I have to see if an app can run windows on android

Exagear Windows Emulator does it. It can run many Windows game, but graphics are not on GPU, so very slow. With normal UI-only apps it's fast.

**Comment by bubbelbadHD** [comment]
I tried using that but it does not respond after updating i applied windows 10 on that

**Comment by khanhduytran0** [comment]
Minecraft win10 is completely different with Minecraft java.

**Comment by bubbelbadHD** [comment]
So what can i do?

**Comment by khanhduytran0** [comment]
Go to https://minecraft.net and buy Minecraft java

**Comment by bubbelbadHD** [comment]
Where can i download it?

**Comment by khanhduytran0** [comment]
But what are you talking about???

**Comment by bubbelbadHD** [comment]
Where can i download the apk file of minecraft?

**Comment by bubbelbadHD** [comment]
In exagear?

**Comment by khanhduytran0** [comment]
In exagear you run exe instead of apk

**Comment by artdeell** [comment]
Java is not like Bedrock, no cracked APK files will help, you need to PAY to play on premium servers

**Comment by bubbelbadHD** [comment]
Ok

**Comment by bubbelbadHD** [comment]
I tried to run exe file of minecraft it showed upadting and then it stopped responding and it was not opening

**Comment by bubbelbadHD** [comment]
> Java is not like Bedrock, no cracked APK files will help, you need to PAY to play on premium servers

I gone to alternative downloads and downloaded exe file but it showed updating and then the file was not opening and the app wasnt installed either

**Comment by RadiatedExodus** [comment]
@bubbelbadHD 
Please, understand the fact that you have to buy the game first if you want to login using Microsoft Account and play in premium servers, and no you cannot play premium servers using offline accounts. You cannot use Minecraft Bedrock Edition to play Minecraft Java Edition servers. If you want to play premium servers then buy Minecraft.

**Comment by bubbelbadHD** [comment]
> @bubbelbadHD
> Please, understand the fact that you have to buy the game first if you want to login using Microsoft Account and play in premium servers, and no you cannot play premium servers using offline accounts. You cannot use Minecraft Bedrock Edition to play Minecraft Java Edition servers. If you want to play premium servers then buy Minecraft.

Ok thanks but i don't have a pc so I have to use alts unbanned on hypixel :(

**Comment by bubbelbadHD** [comment]
Ok guys thankyou I didn't use Microsoft account but I bought a mojang account but it crashes on hypixel

**Comment by Google61** [comment]
*mojang account*
Anyway, what's your device? May it be too... ~~cheap~~ low-end?

**Comment by bubbelbadHD** [comment]
I have redmagic 5g

**Comment by Google61** [comment]
Then, send latestlog.txt

**Comment by bubbelbadHD** [comment]
What is that?

**Comment by ImCatBinxi** [comment]
bubbelbadHD You need A PC to get minecraft Java apk from a website it's call Tlancher

**Comment by WesleyVanNeck** [comment]
> bubbelbadHD You need A PC to get minecraft Java apk from a website it's call Tlancher

First it isn't a APK second if you don't know different of exacutables then silents

**Comment by WesleyVanNeck** [comment]
> bubbelbadHD You need A PC to get minecraft Java apk from a website it's call Tlancher

Also it's tlauncher

**Comment by ImCatBinxi** [comment]
> Minecraft win10 is completely different with Minecraft java.

Windows 10 is after version of java but you can apply as macos,linux,windows 7orwindows 9

**Comment by Nothing-456** [comment]
> > Minecraft win10 is completely different with Minecraft java.
> 
> Windows 10 is after version of java but you can apply as macos,linux,windows 7orwindows 9


There is no Windows 9. Do you mean Windows 8 and Windows 8.1?

**Comment by JamesRG2603** [comment]
You must reinstall pojav so you can use you're account

**Comment by Dorabot2222** [comment]
> You must reinstall pojav so you can use you're account

Wtf it won't work reinstalling will delete all yr data instead to get a smooth experience you can clear the cache junk (just telling)

**Comment by RadiatedExodus** [comment]
Buy Minecraft.

**Comment by Frostionguy** [comment]
@BubblebadHD u can get free account using the master alts account genrator

**Comment by khanhduytran0** [comment]
@Frostionguy playing that way is illegal.

**Comment by JackSaint1385** [comment]
Im having this same issue but I 100% checked and I have mc and it worked fine like an hour ago, now bam 1 update later now it gives me this same error even tho the account I input does own minecraft

**Comment by JackSaint1385** [comment]
I dont know where to ask anymore, anyone got advice?

**Comment by ghost** [comment]
You could try making a backup of all your important files (saves, options, resource packs, etc.) and reinstalling to have a fresh instance of the launcher.

**Comment by JackSaint1385** [comment]
Have tried reinstalling, tried different versions and cleared app data, just keeps telling me that the account doesnt own mc but I checked and I do still own it XD, but also I cant find my /games ffolder so that might be it idk

**Comment by JackSaint1385** [comment]
I know they changed file location recently but like I cant even find my files in the new location they specified, and btw, hidden files are on

**Comment by Githubuser0118** [comment]
Is there a primeum minecraft account generator?

**Comment by mchnjt** [comment]
> Is there a primeum minecraft account generator?

buy the fucking game

**Comment by Sherolion** [comment]
@artdeell if i have a genuine account that is made by me legally.is this account is gonna tell me "token does not exist"

**Comment by RDXTHEPRO** [comment]
But how to make a online account in pojav launcher and how to fix error 403

**Comment by JTM360** [comment]
I have switched my mojang account to microsoft and it still shows the error

**Comment by JTM360** [comment]
like I own the game, I have an Microsoft account, and I followed all the steps for everything and I still get the error.

**Comment by khanhduytran0** [comment]
@JTM360 if you’re under 18, link your account to parent first.

**Comment by JTM360** [comment]
where and how do i do that

**Comment by JTM360** [comment]
and plus i can still play minecraft on my pc when using my microsoft account

**Comment by khanhduytran0** [comment]
[Here is how](https://support.microsoft.com/en-us/account-billing/add-people-to-your-family-group-4a07b974-8103-16ad-6ea2-46549ca19e03)

> and plus i can still play minecraft on my pc when using my microsoft account

Well yeah, there’s no age restriction on the official Minecraft Launcher. But on 3rd-party launchers, your account's age has to be set to 18+ or be linked to an adult account.

**Comment by JTM360** [comment]
ok, i make it so im 18 but it still has the error

**Comment by JTM360** [comment]
and I am admin on my quest, what do i do

**Comment by JTM360** [comment]
do you want to talk on discord so it wont take much time to talk

**Comment by JTM360** [comment]
are you there

**Comment by JTM360** [comment]
> [Here is how](https://support.microsoft.com/en-us/account-billing/add-people-to-your-family-group-4a07b974-8103-16ad-6ea2-46549ca19e03)
> 
> > and plus i can still play minecraft on my pc when using my microsoft account
> 
> Well yeah, there’s no age restriction on the official Minecraft Launcher. But on 3rd-party launchers, your account's age has to be set to 18+ or be linked to an adult account.

yo could we get in a discord call

**Comment by AmmargamingYT** [comment]
Hlo i play micro account in pojavlauncher

**Comment by bubbelbadHD** [comment]
But I have already bought the game on micro account

**Comment by bubbelbadHD** [comment]
And it wokrs on PC and the birthdate is 2000

**Comment by RedDream3405** [comment]
https://www.reddit.com/r/Minecraft/comments/ftr0ms/how_to_play_minecraft_on_a_windows_computer/

**Comment by USSR5678** [comment]
java.lang.RuntimeException: 

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "error" : "NOT_FOUND",
  "errorMessage" : "Not Found"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Unknown Source:119)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Unknown Source:177)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Unknown Source:194)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Unknown Source:228)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Unknown Source:201)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Unknown Source:230)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Unknown Source:5)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(Unknown Source:12)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by USSR5678** [comment]
I can't log in to Microsoft in pojavlauncher

**Comment by USSR5678** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/632#issuecomment-1367339227

**Comment by MegaFaresX** [comment]
Go to your Microsoft account settings and change the date to anything more than 18 years ago

**Comment by some-du6e** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher/issues/632#issuecomment-1367339227

i can't with these (s)kids on github 💀

**Comment by zkitefly** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/5370 ？

**Comment by fatafatih281** [comment]
Gak bisa
