### ISSUE TITLE
Cant use mods

### ISSUE THREAD

**Issue by Mysterious9212** [PojavLauncherTeam/PojavLauncher#6320]
### Describe the bug

Everytime i want to use a mod (fabric) (its the exact version as the mod) it gives error code 1. Any way to fix?

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17937521/latestlog.txt)

### Steps To Reproduce

```markdown
Put the mod in the mods folder
Open pojav
Launch the game
Crashes and gives error code 1
```

### Expected Behavior

It should work cuz its the same version as the mod

### Platform

```markdown
- Device model: galaxy tab A8
- CPU architecture: idk
- Android version: 14
- PojavLauncher version: foxglove
```

### Anything else?

No

**Comment by HACKradio** [comment]
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
	
Do you have Fabric api also in the mod folder?

**Comment by Mysterious9212** [comment]
> A potential solution has been determined, this may resolve your problem: - Install fabric, any version.
> 
> Do you have Fabric api also in the mod folder?

Yes i have

**Comment by HACKradio** [comment]
> > A potential solution has been determined, this may resolve your problem: - Install fabric, any version.
> > Do you have Fabric api also in the mod folder?
> 
> Yes i have

Just tested the mod that shows up in your log and it works just fine on the LTW build (https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/11180313158) . I don't have the play store release installed to test it. Sorry I can't be of much help.

**Comment by GaucovyAero** [comment]
install fabric api
