### ISSUE TITLE
[BUG] game crashes with etto code "1"

### ISSUE THREAD

**Issue by POMAH4IK** [PojavLauncherTeam/PojavLauncher#6321]
### Describe the bug

My freind is trying to lauch an oprifibe version of 1.21.3 and got this error. Its like 90% that it isns because of the version of Minecraft because he also has problems with other versions and with app all in all. Heres the latest log file of the error. Thanks!

### The log file and images/videos

I attached the laretslog.txt to that post
[latestlog.txt](https://github.com/user-attachments/files/17948454/latestlog.txt)

### Steps To Reproduce

```markdown
1. start the app
2. Ibatall the optifine version of 1.21.6
3. Wait for the installation 
4. Launch the game
5. Black screen like 30 - 40 second 
6. See that error
```

### Expected Behavior

I expect that you can help me to solve that bug, thak you in advance!

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: the latest at the moment
I can clarify the rest of the information later if necessary
```

**Comment by GaucovyAero** [comment]
dont use gbox

**Comment by POMAH4IK** [comment]
What is it? Is it an app or something else?
