### ISSUE TITLE
zink renderer crashing

### ISSUE THREAD

**Issue by ffllyy404** [PojavLauncherTeam/PojavLauncher#6322]
### Describe the bug

Launcher crashes 3 seconds after I launch the game with zink renderer regardless of game version or mods. 

### The log file and images/videos

![Screenshot_20241128_231924_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/96864737-7dba-4762-93b5-53d11f15c1d7)
[latestlog.txt](https://github.com/user-attachments/files/17949960/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Use zink
3.Crash
```

### Expected Behavior

Expect the game to load.

### Platform

```markdown
- Device model: Samsung S24 plus (8 gen 3 chipset)
- CPU architecture: ARM64
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

I have an old phone with Snapdragon 888, Android 14 and same launcher version that works perfectly fine with zink.

**Comment by Necspt** [comment]
I think it has something to do with android 14 i also got that error when i load pojav with zink. I cant even load into the game without crashing

**Comment by ImNotTheChiku35** [comment]
I think because you're using VulkanMod, try remove it?

**Comment by ffllyy404** [comment]
> I think because you're using VulkanMod, try remove it?

Tried running vanilla, the exactly same thing happens

**Comment by VenomousSteam81** [comment]
just don't use zink as your phone's gpu probably doesn't support it.

**Comment by azurawrtata** [comment]
> just don't use zink as your phone's gpu probably doesn't support it.

Nahhhh Snapdragon 8 Elite and Gen 2 can run Zink while Gen 3 cant? That's wild

**Comment by ghost** [comment]
Related to #5934
Try pojav glow worm support adreno 750

**Comment by DroidlyMobile** [comment]
It has nothing to do with Android 14 and everything to do with the vulkan driver of the device. I own a RedMagic Nova and S24 Ultra they both have the same Adreno GPU and drivers with the Snapdragon 8 Gen 3.  Zink with Vulkan turned on the screen goes red and no menu appears because of the driver.  I haven't tried to force past the menu but it does load into the menu.  With the Vulkan driver turned off (found in Misc settings btw) the launcher just crashes.  The weird thing is that my 8 Elite chip which has a newer GPU does use Zink but shaders like the Complimentary shader don't render as good either becuase the driver is too new not even Mesa Turnip drivers have been developed yet for that chip.  From my testing Snapdragon 845-8 Gen 2 devices are the best for shaders.  Mali GPU that is a completely different story as I tested multiple Mali GPU devices and they only allow OpenGL.

**Comment by azurawrtata** [comment]
> It has nothing to do with Android 14 and everything to do with the vulkan driver of the device. I own a RedMagic Nova and S24 Ultra they both have the same Adreno GPU and drivers with the Snapdragon 8 Gen 3. Zink with Vulkan turned on the screen goes red and no menu appears because of the driver. I haven't tried to force past the menu but it does load into the menu. With the Vulkan driver turned off (found in Misc settings btw) the launcher just crashes. The weird thing is that my 8 Elite chip which has a newer GPU does use Zink but shaders like the Complimentary shader don't render as good either becuase the driver is too new not even Mesa Turnip drivers have been developed yet for that chip. From my testing Snapdragon 845-8 Gen 2 devices are the best for shaders. Mali GPU that is a completely different story as I tested multiple Mali GPU devices and they only allow OpenGL.

You can actually run on Gen 3. Just need to find proper turnip drivers. 
https://github.com/K11MCH1/AdrenoToolsDrivers/releases/

**Comment by DroidlyMobile** [comment]
> > It has nothing to do with Android 14 and everything to do with the vulkan driver of the device. I own a RedMagic Nova and S24 Ultra they both have the same Adreno GPU and drivers with the Snapdragon 8 Gen 3. Zink with Vulkan turned on the screen goes red and no menu appears because of the driver. I haven't tried to force past the menu but it does load into the menu. With the Vulkan driver turned off (found in Misc settings btw) the launcher just crashes. The weird thing is that my 8 Elite chip which has a newer GPU does use Zink but shaders like the Complimentary shader don't render as good either becuase the driver is too new not even Mesa Turnip drivers have been developed yet for that chip. From my testing Snapdragon 845-8 Gen 2 devices are the best for shaders. Mali GPU that is a completely different story as I tested multiple Mali GPU devices and they only allow OpenGL.
> 
> You can actually run on Gen 3. Just need to find proper turnip drivers. https://github.com/K11MCH1/AdrenoToolsDrivers/releases/

Yup and how do you install them with Pojav Launcher without rooting?

**Comment by KaydenJR2310** [comment]
Don't use zink in pojav in the foxglove update because zink is so so broken in this update, try edelwiss update it works

**Comment by DroidlyMobile** [comment]
> Don't use zink in pojav in the foxglove update because zink is so so broken in this update, try edelwiss update it works

Why are you still using foxglove?  Did you download some random garbage from some dumb content creator that put the download behind a paywall?  I use Zink perfectly fine however I prefer to use the Mesa library for my Adreno GPU devices.  I never have a single issue with crashing.
