### ISSUE TITLE
[BUG] Crash when entering any world

### ISSUE THREAD

**Issue by FannaFx3** [PojavLauncherTeam/PojavLauncher#6323]
### Describe the bug

I log into Minecraft, click single mode or multiplayer mode, go to any world, server, create any world, crashes when I log in, I use the build for optimization, the file below, I removed the conflicting mods from it crashlog.txt I also use the cheat wurst client
my mods
![Screenshot_20241129_015859_ru zdevs zarchiver](https://github.com/user-attachments/assets/929eb053-6f94-4c28-97da-79ea14bce8a4)
the build:
[OptiSodiumLite.zip](https://github.com/user-attachments/files/17951271/OptiSodiumLite.zip)

### The log file and images/videos

[latest.log](https://github.com/user-attachments/files/17951275/latest.log)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. entry into any world
3.crash -1
```

### Expected Behavior

I expect that the world can be entered without problems

### Platform

```markdown
- Device model: HUAWEI STF-L09(HONOR 9)
- CPU architecture: arm64
- Android version: 9 pie
- PojavLauncher version: foxglove-20241124.......
```

### Anything else?

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (aarch64) version Android-9
	Java Version: 17.0.14-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1280326144 bytes (1221 MiB) / 2004877312 bytes (1912 MiB) up to 2004877312 bytes (1912 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 4 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd09 Stepping r0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 2
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4097.67
	Virtual memory used (MB): 3960.89
	Swap memory total (MB): 2240.00
	Swap memory used (MB): 437.82
	JVM Flags: 3 total; -Xms1912M -Xmx1912M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar 

**_I am writing through a translator, there may be inaccuracies_**

**Comment by kasrarouhi** [comment]
I didn't test all mods but I'm sure you need to delete mod moreculling. Use LTW renderer for better mod support

**Comment by FannaFx3** [comment]
**_I removed the modifications from the build, installed a different one, switched to a different version, and that was it. The issue was with sodium._**
