### ISSUE TITLE
mods not working

### ISSUE THREAD

**Issue by Godzilla6049** [PojavLauncherTeam/PojavLauncher#6324]
### Describe the bug

whenver i try to launch fabric with mods (expect performence mods) it has a black screen the entire time. (i had a missing lib for a mod and i downloaded but it only did the audio with a red screen the entire time)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17962430/latestlog.txt)

https://github.com/user-attachments/assets/ffae2254-bd68-48f9-8083-368d762548c2

### Steps To Reproduce

```markdown
1 launch vanilla 1.20.1 minecraft.
2 when you are in the game, quit the game.
3 install fabric 1.20.1
4 start fabric 1.20.1 and exit
5 download mods and copy them into the mods folder
6 start fabric 1.20.1
```

### Expected Behavior

i expect for it to show my mods and not have a black screen/red screen

### Platform

```markdown
- Device model: samsung S9 Tab FE
- CPU architecture: ARM64
- Android version: 14
- PojavLauncher version: foxglove
```

**Comment by Marshall2439** [comment]
Dude you have sent wrong log. Send latestlog.txt file

**Comment by Godzilla6049** [comment]
> Dude you have sent wrong log. Send latestlog.txt file

i cant find that

**Comment by Godzilla6049** [comment]
> Dude you have sent wrong log. Send latestlog.txt file

i think i sent the right log

**Comment by Zahar2loshara** [comment]
Where it was?

**Comment by Godzilla6049** [comment]
> Where it was?

the log was in the log folder

**Comment by Zahar2loshara** [comment]
I think he asks you about log which is in
`~/Android/data/net.kdt.pojavlauncher/files/latestlog.txt`

**Comment by Godzilla6049** [comment]
> I think he asks you about log which is in `~/Android/data/net.kdt.pojavlauncher/files/latestlog.txt`

i gave the log in the 2024-11-29 zip file in the log folder

**Comment by Zahar2loshara** [comment]
The one that you give is a bit different, minecraft's log (i think), needs log of pojav

**Comment by Godzilla6049** [comment]
> The one that you give is a bit different, minecraft's log (i think), needs log of pojav

where do i get logs of pojav

**Comment by Zahar2loshara** [comment]
> `~/Android/data/net.kdt.pojavlauncher/files/latestlog.txt`

**Comment by Godzilla6049** [comment]
> > `~/Android/data/net.kdt.pojavlauncher/files/latestlog.txt`
oh ok

**Comment by Godzilla6049** [comment]
i sent the right log now

**Comment by Zahar2loshara** [comment]
I dont see anything useful for me, maybe the @Marshall2439 see smth

**Comment by Godzilla6049** [comment]
shoukd i change renderer

**Comment by Zahar2loshara** [comment]
It has some sign about, tryitands.ee

**Comment by Godzilla6049** [comment]
i changed renderer and now its working fine
