### ISSUE TITLE
[BUG] <Short description>fatal error

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6327]
### Describe the bug

I play a modpack  join the world and crash

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17964735/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.joon world
3.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: -
- Android version: 12
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
some mod is probably using custom shaders
