### ISSUE TITLE
[BUG] <Short description>I can't run modpack

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6328]
### Describe the bug

I launch a modpack and error

### The log file and images/videos

![Screenshot_2024-11-30-20-03-15-893_net kdt pojavlaunch](https://github.com/user-attachments/assets/71b5f2e2-69b9-420d-b35c-0f8e83eb5e8d)

### Steps To Reproduce

```markdown
1.launch error
```

### Expected Behavior

-

### Platform

```markdown
- Device model: redmi
- CPU architecture: -
- Android version: 12
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
not a pojav issue, this likely needs a manual fix with the json
