### ISSUE TITLE
[BUG] Login Error

### ISSUE THREAD

**Issue by Gerold55** [PojavLauncherTeam/PojavLauncher#6329]
### Describe the bug

I'm unable to log into my microsoft account now and when installing modpacks & forge the app crashes every single time!

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17965607/latestlog.txt)

### Steps To Reproduce

```markdown
Start Pojavlauncher and try to log into Microsoft or download anything at all.
```

### Expected Behavior

To download and also log into my account.

### Platform

```markdown
- Device model: Samsung Galaxy S23 Ultra
- CPU architecture: snapdragon 
- Android version: android 14
- PojavLauncher version: latest Google play
```

**Comment by GaucovyAero** [comment]
this is just a log with the forge 1.12.2 installer and nothing else, open a new issue pls
