### ISSUE TITLE
Application/Game aborted by fatal signal 6

### ISSUE THREAD

**Issue by CodeByAnvith** [PojavLauncherTeam/PojavLauncher#6330]
### Describe the bug

![Screenshot_20241130-213156_PojavLauncher_(Minecraft_Java_Edition_for_Android) 1](https://github.com/user-attachments/assets/44913c5f-4b1d-4ca8-92f2-a3a8a6d4a3ba)

### The log file and images/videos

[latestlog[1].txt](https://github.com/user-attachments/files/17966002/latestlog.1.txt)

### Steps To Reproduce

```markdown
1)open pojav launcher
2) play optifine 1.21.1_hd_u_j1
2)open world
3)loading terrain message displayed 
4)game crashes
```

### Expected Behavior

i expect my world to load and able to play

### Platform

```markdown
- Device model: samsung galaxy a50 4/64g
- CPU architecture: ARMv8-A, specifically an Exynos 9610 Octa-core processor
- Android version: 11
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

please fix it please i beg u

**Comment by Axeyz** [comment]
Your problem is the same as mine🙂

**Comment by ghost** [comment]
This is happen if you use LTW renderer with 8 render distance and above without sodium mod. Install sodium mod and try again

**Comment by Mrpanda98** [comment]
> This is happen if you use LTW renderer with 8 render distance and above without sodium mod. Install sodium mod and try again

It's says saving world and crashes

**Comment by Mrpanda98** [comment]
> This is happen if you use LTW renderer with 8 render distance and above without sodium mod. Install sodium mod and try again

این باز هم کرش می‌کنه چیکار کنم لطفا کمکم کن میگه saving world و کرش میکنه

**Comment by Fullnoname** [comment]
У меня тоже самое но на фабрик, что делать? У меня стоит содиум но нечего не роботает
![Screenshot_20241217-014209](https://github.com/user-attachments/assets/a4214ac6-b400-495e-89f4-ce746414d62d)

**Comment by fjdgh** [comment]
> Це трапляється, якщо ви використовуєте рендерер LTW із відстанню візуалізації 8 і більше без модифікації натрію. Встановіть sodium mod і повторіть спробу

В мене це відбулось навпаки від того що я встановив rubidium (forge sobium) з дистанцією промальовування 2 чанки, можете що порадити?

**Comment by fjdgh** [comment]
> У меня тоже самое но на фабрик, что делать? У меня стоит содиум но нечего не роботает ![Screenshot_20241217-014209](https://private-user-images.githubusercontent.com/191926263/396301926-a4214ac6-b400-495e-89f4-ce746414d62d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTIzNjIsIm5iZiI6MTczNDc5MjA2MiwicGF0aCI6Ii8xOTE5MjYyNjMvMzk2MzAxOTI2LWE0MjE0YWM2LWI0MDAtNDk1ZS04OWY0LWNlNzQ2NDE0ZDYyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxNDQxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDZhNjMzMzAyZjlmYTU1NzcwZWQ5ZDFmMjM1MzZmZjZkYzcwMzU5NjZlNzI5ODY3NzM3ZWVmZjc4NTdiNTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DWQYVGji3AlE5KUtrZ_oFv2qEthU4ddIZNtN7pbHOu4)

У мене так само відбулось, але без содіума було все нормально

**Comment by CamoWolf1222** [comment]
Duplicate of #6325, there seems to be a fix in #6377

**Comment by Its-porodx** [comment]
If anyone knows how to fix this, please tell me (I'm playing with sodium)

**Comment by Its-porodx** [comment]
If anyone knows how to fix this, please write (I'm playing with sodium)

**Comment by Mrpanda98** [comment]
> If anyone knows how to fix this, please write (I'm playing with sodium)

Are you playing with xareos waypoint?

**Comment by Its-porodx** [comment]
> > If anyone knows how to fix this, please write (I'm playing with sodium)
> 
> Are you playing with xareos waypoint?

No, I don't play with xareos waypoint, I play with optimizing mods, some of which add items/new systems

**Comment by Its-porodx** [comment]
> > If anyone knows how to fix this, please write (I'm playing with sodium)
> 
> Are you playing with xareos waypoint?

And I'm still playing on version 1.21.1 of NeoForge

**Comment by Its-porodx** [comment]
> > If anyone knows how to fix this, please write (I'm playing with sodium)
> 
> Are you playing with xareos waypoint?

And I'm still playing on version 1.21.1  NeoForge

**Comment by Mrpanda98** [comment]
> > > If anyone knows how to fix this, please write (I'm playing with sodium)
> > 
> > 
> > Are you playing with xareos waypoint?
> 
> And I'm still playing on version 1.21.1 NeoForge

If you are playing better mc delete the xareos waypoint (I'm playing with journey map)

**Comment by CamoWolf1222** [comment]
> If anyone knows how to fix this, please write (I'm playing with sodium)

Did you check the fix in #6377

**Comment by GaucovyAero** [comment]
try resetting your video settings

**Comment by Its-porodx** [comment]
> > If anyone knows how to fix this, please write (I'm playing with sodium)
> 
> Did you check the fix in #6377 

What?

**Comment by CamoWolf1222** [comment]
> > > If anyone knows how to fix this, please write (I'm playing with sodium)
> > 
> > 
> > Did you check the fix in #6377
> 
> What?

https://github.com/PojavLauncherTeam/PojavLauncher/issues/6330#issuecomment-2563953601 (Click the link)

**Comment by Its-porodx** [comment]
> > > > If anyone knows how to fix this, please write (I'm playing with sodium)
> > > 
> > > 
> > > Did you check the fix in #6377
> > 
> > What?
> 
> https://github.com/PojavLauncherTeam/PojavLauncher/issues/6330#issuecomment-2563953601 (Click the link)

And I still haven't figured out how to fix the bug.

**Comment by Its-porodx** [comment]
> > > > If anyone knows how to fix this, please write (I'm playing with sodium)
> > > 
> > > 
> > > Did you check the fix in #6377
> > 
> > What?
> 
> https://github.com/PojavLauncherTeam/PojavLauncher/issues/6330#issuecomment-2563953601 (Click the link)

And I still haven't figured out how to fix the bug.

**Comment by CamoWolf1222** [comment]
That is all I can help with.

**Comment by Mrpanda98** [comment]
> > > > > If anyone knows how to fix this, please write (I'm playing with sodium)
> > > > 
> > > > 
> > > > Did you check the fix in #6377
> > > 
> > > 
> > > What?
> > 
> > 
> > [#6330 (comment)](https://github.com/PojavLauncherTeam/PojavLauncher/issues/6330#issuecomment-2563953601) (Click the link)
> 
> And I still haven't figured out how to fix the bug.

I said if you using xareos waypoint delete it

**Comment by CamoWolf1222** [comment]
> I said if you using xareos waypoint delete it

He isn't.

**Comment by Its-porodx** [comment]
> > > > > > If anyone knows how to fix this, please write (I'm playing with sodium)
> > > > > 
> > > > > 
> > > > > Did you check the fix in #6377
> > > > 
> > > > 
> > > > What?
> > > 
> > > 
> > > [#6330 (comment)](https://github.com/PojavLauncherTeam/PojavLauncher/issues/6330#issuecomment-2563953601) (Click the link)
> > 
> > And I still haven't figured out how to fix the bug.
> 
> I said if you using xareos waypoint delete it 

I play without mods on the Mani map

**Comment by Its-porodx** [comment]
> > > > > > If anyone knows how to fix this, please write (I'm playing with sodium)
> > > > > 
> > > > > 
> > > > > Did you check the fix in #6377
> > > > 
> > > > 
> > > > What?
> > > 
> > > 
> > > [#6330 (comment)](https://github.com/PojavLauncherTeam/PojavLauncher/issues/6330#issuecomment-2563953601) (Click the link)
> > 
> > And I still haven't figured out how to fix the bug.
> 
> I said if you using xareos waypoint delete it 

I play without mods on the Mani map

**Comment by Its-porodx** [comment]
> > I said if you using xareos waypoint delete it
> 
> He isn't.
> 
> 

Bro, sometimes you don't know what to do if Forge doesn't see the mods?

**Comment by UnknownDude995** [comment]
I have the same problem I use Fabric 1.21.4 with fabulously optimized

**Comment by Kaik9** [comment]
I tried using Sodium patcher but it still gives me Faltal signal 6 error, I am using sodium 5.11

**Comment by Hypergaming2020** [comment]
Hello im having the same problem but i play bedwars with a texture pack without texture pack it works fine

**Comment by Hypergaming2020** [comment]
I use 1.8.8 version
