### ISSUE TITLE
Mods not loaded

### ISSUE THREAD

**Issue by TotallySaeed** [PojavLauncherTeam/PojavLauncher#6331]
### Describe the bug

I have added multiple mods but not all of them are loaded in

### The log file and images/videos

![Screenshot_20241130-225808](https://github.com/user-attachments/assets/2ea042ba-66ce-4ef5-bb14-3a2485fe305d)
![1732985921494](https://github.com/user-attachments/assets/3b850f86-ce81-42c9-8d1b-d526eaa9d6f6)
[latest.log](https://github.com/user-attachments/files/17966185/latest.log)

### Steps To Reproduce

```markdown
1. add mods to mods folder
2. Launch pojav
3. Only couple of the mods work
```

### Expected Behavior

I expected all of them to work

### Platform

```markdown
- Device model: Infinix hot 50i
- CPU architecture: 64arm
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3-openjdk
```

### Anything else?

Am I doing something wrong?

**Comment by GaucovyAero** [comment]
use files by marc to move the files
