### ISSUE TITLE
[BUG] error when using shader on LTW renderer

### ISSUE THREAD

**Issue by Furina-imw** [PojavLauncherTeam/PojavLauncher#6334]
### Describe the bug

I am using a sodium pack mod that I compiled myself. When I install the shader, the game interface turns black. Same with all items. When I turn off the shader, everything is worse when the ground, water, grass, flowers and leaves around are all black. This phenomenon only disappears completely when I turn off the shader and re-enter the game. I apologize if this google translate is not perfect, because I don't know much English so I have to use it.

### The log file and images/videos

Here is the game log file:
[latestlog.txt](https://github.com/user-attachments/files/17967714/latestlog.txt)
and here is a detailed video of the error (sorry the video is too heavy so I had to upload it to google drive):https://drive.google.com/file/d/1Q5wDypUCnE_IheeZmuec3toLa2slD8KW/view?usp=sharing

### Steps To Reproduce

```markdown
I wrote above:v
```

### Expected Behavior

I hope this bug will be fixed soon and this renderer can use shaders with "shadows"

### Platform

```markdown
- Device model: Sharp AQUOS Zero6
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20241129-07c5502-feat/ltw
```

**Comment by Dilen0001** [comment]
.

**Comment by Yoidiotiamback** [comment]
We all expected ltw supports shadows in latest github actions I thought developers experimented and fixed those errors but it seem?

**Comment by ghost** [comment]
LTW renderer actually support shaders but not the powerful shaders. Try mellow shader. Works on LTW and have good options

**Comment by Yoidiotiamback** [comment]
You can even use makeup ultra fast shaders just turn off shadows

**Comment by Furina-imw** [comment]
@Yoidiotiamback yeah i know that, but with shading off the shaders don't look as good anymore... i really wish this renderer could support shading XD

**Comment by kiokori-git** [comment]
> @Yoidiotiamback yeah i know that, but with shading off the shaders don't look as good anymore... i really wish this renderer could support shading XD

soon™

**Comment by zeend89** [comment]
LTW renderer only supports a few shaders, and hopefully the next update will be better than this.
