### ISSUE TITLE
[BUG] <Short description> Game crashing when going underwater 

### ISSUE THREAD

**Issue by SingdonYT2** [PojavLauncherTeam/PojavLauncher#6335]
### Describe the bug

Whenever I go underwater in rlcraft 2.9.3 my games lags and after a few seconds it crashes

Device: poco f6
Processor: Snapdragon 8s gen 3
Ram: 12gb
Gpu: andreno 735

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17968346/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Play rlcraft 
3. Go underwater 
4. Games crashes after few seconds
```

### Expected Behavior

Game crash

### Platform

```markdown
- Device model: Poco F6
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

**Comment by GaucovyAero** [comment]
remove enhanced visuals, it has custom shaders
