### ISSUE TITLE
[BUG] Crash Landing crashes the game

### ISSUE THREAD

**Issue by Gerold55** [PojavLauncherTeam/PojavLauncher#6336]
### Describe the bug

The modpack crash landing doesn't load and crashes the app

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17968990/latestlog.txt)

### Steps To Reproduce

```markdown
When trying to download and install the modpack the game crashes.
```

### Expected Behavior

To effectively download it and install it.

### Platform

```markdown
- Device model: Samsung Galaxy S23 Ultra 
- CPU architecture: Snapdragon
- Android version: 14
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
theres multiple ways to do this, one way i think is to get forge 1.6.4 -.1345 running and copy the mods into that profile somehow
