### ISSUE TITLE
It doesn't let you play Forge or NeoForge 

### ISSUE THREAD

**Issue by Knuckesrosa** [PojavLauncherTeam/PojavLauncher#6337]
### Describe the bug

Well, coincidentally, after they updated the pojavlauncher, I went to a minecraft with mods, it was neoforge 1.21.1 and it loaded slowly and I decided to try again with forge 1.20.1 and install the same mods for both things, but code 1 appeared. I tried more methods and it still continued and I tried again in minecraft forge 1.19.2 and it still happened, only the normal and oftifine versions work, nothing else. 

### The log file and images/videos

I don't even know what to do anymore 

### Steps To Reproduce

```markdown
I don't know
```

### Expected Behavior

1. 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Marshall2439** [comment]
Send log smh

**Comment by Knuckesrosa** [comment]
> Send log smh

let me send a capture because it won't let me send a text report or let me try

**Comment by Knuckesrosa** [comment]
> Send log smh

![latestlog.txt](https://github.com/user-attachments/files/18049338/latestlog.txt)

**Comment by Marshall2439** [comment]
You have aether mod for 1.12.2 installed in 1.20.1 smh

**Comment by Knuckesrosa** [comment]
> You have aether mod for 1.12.2 installed in 1.20.1 smh
I had those mods yet because I haven't removed them yet to give you the latestlog.txt

**Comment by Knuckesrosa** [comment]
> You have aether mod for 1.12.2 installed in 1.20.1 smh

Look, I'll give you another latestlog.txt

**Comment by Knuckesrosa** [comment]
> You have aether mod for 1.12.2 installed in 1.20.1 smh

The error has just been fixed, it's not a joke, it shows that the others do work
