### ISSUE TITLE
[BUG] About Custom Controls

### ISSUE THREAD

**Issue by ImNotTheC35** [PojavLauncherTeam/PojavLauncher#6342]
### Describe the bug

When I want to edit the controls, ingame or from menu, it randomly crashed the PojavLauncher. and the button can randomly have SPECIAL_MENU on four of the mapping

### The log file and images/videos

Crash: [crash.log](https://github.com/user-attachments/files/17977406/crash.log)

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Click the Custom Controls
3. Try Copy, Click, Edit the control button
```

### Expected Behavior

1. It doesn't crash the Launcher
2. the mapping doesn't change to SPECIAL_MENU randomly

### Platform

```markdown
- Device model: 
- CPU architecture: Aarch64 
- Android version: 11
- PojavLauncher version: foxglove-20241202-fd6bea9-v3_openjdk
```

### Anything else?

Pls fix if can

**Comment by Mathias-Boulay** [comment]
Hi there @ImNotTheC35 !
I didn't manage to reproduce the issue, but I added a safety check that I hope would help with the issue: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/12147219724

Try it out once it builds, and let me know if it helps !

**Comment by ImNotTheChiku35** [comment]
I think it don't crashed (yet), thanks!
(Sorry, different GitHub account)

**Comment by Mathias-Boulay** [comment]
closing it then :smile:
