### ISSUE TITLE
[BUG] Angle renderer dont work without optifine. 

### ISSUE THREAD

**Issue by Nighvisit** [PojavLauncherTeam/PojavLauncher#6343]
### Describe the bug

Well I wanted to play create mod. So, I tried to use angle renderer. First I tried to use it with optifine. It worked perfectly. Then when I tried to use it with sodium or vanilla it only showed red screen. With some try I joined a World in vanilla. I joined perfectly but my screen was black my log output showed i joined but my screen was black. Pls help me

### The log file and images/videos

[2024-12-02-1.log](https://github.com/user-attachments/files/17978692/2024-12-02-1.log)

### Steps To Reproduce

```markdown
Start minecraft with angle renderer without using optifine.
```

### Expected Behavior

Load with any mod and vanilla. 

### Platform

```markdown
- Device model: Samsung Exynos 850
- CPU architecture: armv8l (32-bit)
- Android version: Android 14
- PojavLauncher version: latest pojavlauncher
```

### Anything else?

Pls Help I need this.

**Comment by Nighvisit** [comment]
I forget to tell It was play store version of pojavlauncher

**Comment by Nighvisit** [comment]
This only happen in 1.20.1

**Comment by Kuki0771** [comment]
Go to the pojav launcher discord duh
