### ISSUE TITLE
[BUG] pojav launcher doesnt detect mods

### ISSUE THREAD

**Issue by Jjermah5298** [PojavLauncherTeam/PojavLauncher#6344]
### Describe the bug

For some reason pojav launcher doesnt detect mods and i can't even grant file access to it pls help

### The log file and images/videos

It also crashes for 1.18.2 mods and on that version at the end of the log says:free args
[latestlog.txt](https://github.com/user-attachments/files/17980432/latestlog.txt)

### Steps To Reproduce

```markdown
I start pojav. 2:go to android/data/pojavlauncher/.mineccraft/mods then i put better fps and decocraft mod 1.12.2. start game. Then no mods detected
```

### Expected Behavior

I wanted for the mod to work

### Platform

```markdown
- Device model: redmi 13c
- CPU architecture: x64
- Android version: hyperos
- PojavLauncher version: latest
```

**Comment by TotallySaeed** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/6331#issue-2707668373 I also reported the same issue but no responses for 7 days

**Comment by GaucovyAero** [comment]
use files by marc to move the files
