### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Arrumzx** [PojavLauncherTeam/PojavLauncher#6345]
### Is this request related to a bug?

P

### Describe the request.

P

### Anything else?

Pppppp

**Comment by Vylesh** [comment]
Bruh

**Comment by Nighvisit** [comment]
..........

**Comment by Vylesh** [comment]
@GaucovyAero Bro Troll ticket moment

**Comment by Marshall2439** [comment]
ok vylesh

**Comment by Vylesh** [comment]
> ok vylesh

I Smell some sussy Canidae_fan

**Comment by Marshall2439** [comment]
Be professional and call me marshall smh. Canidae fan is my nick-nickname

**Comment by Vylesh** [comment]
> Be professional and call me marshall smh. Canidae fan is my nick-nickname

Nuh Uh, I'd like to discord
