### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Daviptolomeu** [PojavLauncherTeam/PojavLauncher#6347]
### Describe the bug

Eu crio uma conta no final fala que ouve um erro

### The log file and images/videos

E isso

### Steps To Reproduce

```markdown
Não sei mais o que fazer
```

### Expected Behavior

Clt

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Vocês e rascista

**Comment by VenomousSteam81** [comment]
You most likely won't get help with an issue if you're calling people fascists.

**Comment by 5ghzx** [comment]
translating as racist on my end

**Comment by VenomousSteam81** [comment]
Either way, they most likely won't get help

**Comment by Fx-Mateus** [comment]
1.

**Comment by Fx-Mateus** [comment]
__

**Comment by Fx-Mateus** [comment]
[`[](url)`](url)
