### ISSUE TITLE
1.21.4 just shows Red screen 

### ISSUE THREAD

**Issue by TheBrockReal** [PojavLauncherTeam/PojavLauncher#6349]
### Describe the bug

When I try to load Version 1.21.4, it just shows a red screen and nothing else 

### The log file and images/videos

https://github.com/user-attachments/assets/73c638b7-852d-402f-8d03-d80c07dd2f0d

### Steps To Reproduce

```markdown
Launch the app on version 1.21.4
```

### Expected Behavior

For it to work 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Marshall2439** [comment]
Update your pojav to latest version if you already didn't yet

**Comment by Trtryrey** [comment]
@Marshall2439 it doesnt work either.its the modded version off 1.21.4

**Comment by INFIYOP** [comment]
> Update your pojav to latest version if you already didn't yet

I am having the same problem @Marshall2439

**Comment by neptunecentury** [comment]
Same, here. Just red screen.

**Comment by ghost** [comment]
Try LTW renderer with sodium mod
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/12079825845
Download link for LTW renderer. I think it fix the problem

**Comment by Trtryrey** [comment]
> Try LTW renderer with sodium mod https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/12079825845 Download link for LTW renderer. I think it fix the problem

Nope.i use 1.21.4 so if i use ltw renderer its just shown black screen

**Comment by Marshall2439** [comment]
> @Marshall2439 it doesnt work either.its the modded version off 1.21.4

use angle/Zink renderer if updating pojav doesn't resolve your issue

**Comment by Marshall2439** [comment]
> > Try LTW renderer with sodium mod https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/12079825845 Download link for LTW renderer. I think it fix the problem
> 
> Nope.i use 1.21.4 so if i use ltw renderer its just shown black screen

Have you tried using ltw? 
If it causes issues send log

**Comment by neptunecentury** [comment]
> > @Marshall2439 it doesnt work either.its the modded version off 1.21.4
> 
> use angle/Zink renderer if updating pojav doesn't resolve your issue

I tried zink on a vanilla instance and that worked as a workaround for now. Thanks!

**Comment by GaucovyAero** [comment]
update pojav
