### ISSUE TITLE
This doesn't work.

### ISSUE THREAD

**Issue by ths9307** [PojavLauncherTeam/PojavLauncher#635]
![Screenshot_20210118-014421_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/77576703/104849775-e6c57500-592e-11eb-837d-9b9e8b25522c.jpg)

I'm sorry. I've been writing wrong lately.

**Comment by pstube** [comment]
음? 한국인? 정품아이디로 로그인했나요??

**Comment by ths9307** [comment]
> 음? 한국인? 정품아이디로 로그인했나요??

네 했는데 다시 접속해보라고 뜨더군요
마이크로소프트 아이디로 접속했구요

**Comment by pstube** [comment]
싱글플레이로 들어가면 스킨은 잘 나오나요?? 아니면 스마트폰 인터넷을 다른와이파이나 핫스팟에 연결해서 접속해보세요

**Comment by ths9307** [comment]
> 싱글플레이로 들어가면 스킨은 잘 나오나요?? 아니면 스마트폰 인터넷을 다른와이파이나 핫스팟에 연결해서 접속해보세요

싱글에서 적용한스킨도 잘나오고 기존와이파아끄고 ㄷ기본인터냇으로도 안되고 다른 와이파이애서도
유효하지 않은 세션  마크를 껏다켜라라고 나오네요

**Comment by pstube** [comment]
다른 기기에서 중복 로그인할 일도 없죠??  하이픽셀서버는 잘 들어가지나요?

**Comment by ths9307** [comment]
> 다른 기기에서 중복 로그인할 일도 없죠?? 하이픽셀서버는 잘 들어가지나요?

네 평소에는 컴터로 하고 다른 휴대폰에는 실험도 안해봤어요

**Comment by Adam0530** [comment]
OMG! What the frick are they talking about?

**Comment by WesleyVanNeck** [comment]
realms is not our issue
