### ISSUE TITLE
[F-Req] <Short description> Want to replace a button.

### ISSUE THREAD

**Issue by ShauryaJha383** [PojavLauncherTeam/PojavLauncher#6352]
### Is this request related to a bug?
No.

You should replace 'PRI' / Left click with something such that whenever we click anywhere on the screen, the left click happens like it happens normally in MCPE.
 **(In your application 'PojavLauncher')**

### Describe the request.

A left clickable 'PRI' button.

**Comment by Marshall2439** [comment]
Absolutely not bro

**Comment by Marshall2439** [comment]
How else are you gonna right click then?

**Comment by ShauryaJha383** [comment]
> How else are you gonna right click then?

You can do it by sec or holding the screen.

**Comment by Marshall2439** [comment]
That does not make sense. You're more likely to use right click than left click. And limiting it to just few buttons doesn't seem like a good idea to me. Placing blocks by holding the screen is absolutely not worth it. Even mcpe doesnt do it.

**Comment by ShauryaJha383** [comment]
Bro Left click helps us to fight,kill animals,Ender dragons, Wither etc.

**Comment by Marshall2439** [comment]
Bro its a block game not "killing mobs" type game. You're most likely gonna use right click to use and place blocks rather than hitting animals. You're gonna place blocks faster than hitting mobs. You can just use scrollable left click buttons on one side of screen instead. Its much more easier to click anywhere to place blocks rather than focusing it onto one single button.

**Comment by ShauryaJha383** [comment]
Bro but PojavLauncher is made to feel mobile players like java and
ovbesioly 90% things are common in both java and bedrock/pocket edition
except servers and you know in most servers we have to fight and do PVP
with players /mobs

**Comment by Marshall2439** [comment]
its not made for "feeling mobile players like java" what are you talking about.
Minecrap is primarily a block game not PvP based game

Secondly you can literally make gigantic left click buttons and spam a bunch of them

**Comment by GaucovyAero** [comment]
you can easily create your custom controlmap thats gonna fit your needs

**Comment by ShauryaJha383** [comment]
Bro what are you talking about? Minecrap? But I am talking about Pojav
Launcher!

**Comment by ShauryaJha383** [comment]
Guys please tell what's the issue is there any problem if yes then what's
it?

**Comment by Marshall2439** [comment]
Dude we literally told you what's the problem and solution is to make a custom control map that fits your needs as aero said

**Comment by ShauryaJha383** [comment]
Bro you should understand 🥺

**Comment by Marshall2439** [comment]
No

**Comment by khanhduytran0** [comment]
@ShauryaJha383 PojavLauncher does not know what item player is holding and what is the target ingame to decide what key to send. Unless there is a mod installed to read such info, ~~or a machine learning model that takes screenshot of every frame and read from it (not to mention the diversity of resource packs will make the job heavier)~~, implementing this is not possible.
