### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by ImNotTheC35** [PojavLauncherTeam/PojavLauncher#6354]
### Describe the bug

1. I can't click to place/interact with block. is this intended?

2. when leave the application and re-enter, I can't do anything, even try to leave the app

### The log file and images/videos

1. [Video](https://github.com/user-attachments/assets/67394f94-eb61-4511-9116-908ebccb4f4d
)
2. [Video](https://github.com/user-attachments/assets/2101295a-09c0-4624-afaf-d6d228763d95)

I think there's nothing on the log, but:
[latestlog.txt](https://github.com/user-attachments/files/18046273/latestlog.txt)

### Steps To Reproduce

```markdown
The first one:
1. Open PojavLauncher
2. Play any profile you have
3. Play any world
4. Try place block by tapping the screen

The second one:
1. While the game is running, leave the app
2. Re-enter the app
```

### Expected Behavior

1. I be able to place/interact a block

2. It doesn't freeze

### Platform

```markdown
- Device model: Realme 5 Pro (RMX1971)
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: foxglove-20241205-a80b85d-fix/QoL_stuff
```

**Comment by GaucovyAero** [comment]
i cant reproduce the issues, also you are not running v3_openjdk, which is not supported

**Comment by ImNotTheChiku35** [comment]
uh, how I run the v3_openjdk?
