### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Doorpol** [PojavLauncherTeam/PojavLauncher#6355]
### Is this request related to a bug?

Are there any better alternatives toOptifine for Forge? 1.20.1 pojavlauncher 

### Describe the request.

.

### Anything else?

.

**Comment by kasrarouhi** [comment]
Rubidium with LTW renderer is perform better than optifine

**Comment by Doorpol** [comment]
> Rubidium with LTW renderer is perform better than optifine

Black screen how to fix that?

**Comment by Doorpol** [comment]
> Rubidium with LTW renderer is perform better than optifine

Crash 
[latest.log](https://github.com/user-attachments/files/18089785/latest.log)
