### ISSUE TITLE
Game doesn't see any mods like .jar file format 

### ISSUE THREAD

**Issue by RygmiUser** [PojavLauncherTeam/PojavLauncher#6360]
### Describe the bug

I'll just give more details
When I tried to download ANY mod on Forge or Fabric, the mods simply don't show up, and when loading into the game, it just throws a warning that such and such a mod is not a .jar file, be it optiforge, jei, Any other mod, addon, resource pack, texture pack (and this didn't happen with shaders) 
Below I attach screenshots of what the mod is jei in the folder .minecraft/mods, where it should be; And also a screenshot of the warning that the mod is not a .jar format and a screenshot from the "mods" tab in the main menu  

### The log file and images/videos

![Screenshot_2024-12-07-21-04-18-256_ru zdevs zarchiver-edit](https://github.com/user-attachments/assets/657d4ca6-45a8-41cf-a8b1-0c7fea640ea6)
![Screenshot_2024-12-07-21-08-03-430_net kdt pojavlaunch](https://github.com/user-attachments/assets/c9208a13-a5c6-480b-9c7a-9fa4e34d3193)
![Screenshot_2024-12-07-21-08-18-539_net kdt pojavlaunch](https://github.com/user-attachments/assets/6af5ab44-6776-40fe-a7e9-26f0e3003e76)

### Steps To Reproduce

```markdown
1.download mod from any sources(I use curseforge)
2.go to pojav and download forge/fabric version which is needed by the mod and start it(just to get resources and "mods" folder)
3. Go to zarchiver, then find the mod you need, copy it to the "mods" folder
4. Go to pojav and just start version that you downloaded
```

### Expected Behavior

I'm sure I'm doing everything right, all mods are compatible and I downloaded the right versions, I'm sure there were no breakages in the file, etc., all files were reinstalled several times and the error is still there

### Platform

```markdown
- Device model: redmi note 12 5g 
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: lastest release
```

### Anything else?

(I used a translator because I don't speak English well (I apologize for any mistakes in the text))

**Comment by ilham577** [comment]
simple thing to fix it, just copy the jar file instead of cut them
