### ISSUE TITLE
1.12.2 forge Game crashes with code -1

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6361]
### Describe the bug

I installed some mods and whenever I try to start the game it crashes, from what I could understand of the textlog(I'm not really good with programing) the problem is a shader although I'm not sure 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18050052/latestlog.txt)

### Steps To Reproduce

```markdown
1. install forge 1.12.2 profile
2. install the mods
3. start and wait
```

### Expected Behavior

I expect it to start normally

### Platform

```markdown
- Device model: samsung SM-M536B
- CPU architecture: arm64
- Android version: 34
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

**Comment by GaucovyAero** [comment]
remove cqrepoured, it contains custom shaders
