### ISSUE TITLE
It keeps on showing "application/game aborted by fatal signal 6"

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#6364]
![latestlog.txt](https://github.com/user-attachments/files/18052278/latestlog.txt)

![IMG-20241208-WA0015.jpg](https://github.com/user-attachments/assets/b58ea06c-9fd1-4676-8034-5c50114fc340)

**Comment by ghost** [comment]
This is happen if you use LTW renderer with 8 render distance and above without sodium mod. Install sodium mod and try again

**Comment by aura123lol** [comment]
> This is happen if you use LTW renderer with 8 render distance and above without sodium mod. Install sodium mod and try again

It is still happening

**Comment by aura123lol** [comment]
> This is happen if you use LTW renderer with 8 render distance and above without sodium mod. Install sodium mod and try again

![latestlog.txt](https://github.com/user-attachments/files/18139939/latestlog.txt)

**Comment by CamoWolf1222** [comment]
This issue was fixed for me by changing the renderer to Vulkan. I also tanked all the settings graphics-wise.

**Comment by aura123lol** [comment]
> This issue was fixed for me by changing the renderer to Vulkan. I also tanked all the settings graphics-wise. 

Can u please tell me what is the problem here ![latestlog.txt](https://github.com/user-attachments/files/18147158/latestlog.txt)

**Comment by CamoWolf1222** [comment]
I am not as well versed in this as others may be, but it seems like a mod is causing issues (idk which one). Most of these errors are "Potentially Dangerous alternative prefix `minecraft` for name... This could be a intended override, but in most cases indicates a broken mod.". A lot of texture and model errors coming up in some of your mods, (they may be outdated). Really sorry I can't help any further, I am not a programmer, and I am not even certain I am giving you correct information. Best to just wait for someone else to help.

**Comment by artdeell** [comment]
> Can u please tell me what is the problem here ![latestlog.txt](https://github.com/user-attachments/files/18147158/latestlog.txt)

Seems like your modpack install might be broken.
