### ISSUE TITLE
??

### ISSUE THREAD

**Issue by aura123lol** [PojavLauncherTeam/PojavLauncher#6365]
![latestlog.txt](https://github.com/user-attachments/files/18052442/latestlog.txt)

What is this unknown error

**Comment by VictorKayne** [comment]
Can you send your mod list?

**Comment by luciito** [comment]
,,🥰

Pada Kam, 12 Des 2024 08.07, VictorKayne ***@***.***> menulis:

**Comment by aura123lol** [comment]
> Can you send your mod list 
I'll try

**Comment by GaucovyAero** [comment]
no info provided
