### ISSUE TITLE
[BUG] blocked fps

### ISSUE THREAD

**Issue by Kahyn9532** [PojavLauncherTeam/PojavLauncher#6366]
###Describe the bug

when i try playing modded minecraft, it start being blocked at 2 fps but only in modded with forge i tried everything but nothing work :(

### The log file and images/videos

can't give any log, optifine won't work and the video is too big

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Use forge 
3. Launch my modpack
4. Start the world 
5. 2 fps
```

### Expected Behavior

it should have around 50~110 fps

### Platform

```markdown
- Device model: Redmi note 12 4G
- CPU architecture: aarch64
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

**Comment by GaucovyAero** [comment]
likely caused by one of your mods
