### ISSUE TITLE
[BUG] <jna 7.0.0 how>

### ISSUE THREAD

**Issue by littleboulderbro** [PojavLauncherTeam/PojavLauncher#6369]
### Describe the bug

It's stuck on 6.1.6 and the arm64 file doesn't exist in the files

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18089298/latestlog.txt)

### Steps To Reproduce

```markdown
Start Minecraft
Falure
```

### Expected Behavior

unable to play Minecraft so I wanna play

### Platform

```markdown
- Device model: fire tablet 11
- CPU architecture: arm64 apperently
- Android version: latest
- PojavLauncher version: the fox glove thing
```

### Anything else?

😭😭😭

**Comment by littleboulderbro** [comment]
Please help me chat I can't fix it 😭

**Comment by cherepavel** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/5634#issuecomment-2413203045

**Comment by littleboulderbro** [comment]
> [#5634 (comment)](https://github.com/PojavLauncherTeam/PojavLauncher/issues/5634#issuecomment-2413203045)

 I already tried that it didn't work

**Comment by GaucovyAero** [comment]
the jna version is likely not even your issue, if you are crashing on world join, try resetting your video settings or use a different renderer

**Comment by littleboulderbro** [comment]
> the jna version is likely not even your issue, if you are crashing on world join, try resetting your video settings or use a different renderer

No I can't even launch pojav I push play then I can't do noin goes tor ed screen and no worky
