### ISSUE TITLE
How to fix texture glitch 

### ISSUE THREAD

**Issue by Renerosal01234** [PojavLauncherTeam/PojavLauncher#6372]
### Describe the bug

Whatever i use any mods I got texture glitch using holygl4es 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Download any mods exa. Dynamic surroundings 
2. Start Pojavlauncher 
3. Create world 
4. Texture glitch in inventory and smoke got texture look like inventory
```

### Expected Behavior

Do you how to fix I try render distance and fast render 

### Platform

```markdown
- Device model: Poco c65 
- CPU architecture: 64
- Android version: 14
- PojavLauncher version: Google play
```

### Anything else?

Pls help

**Comment by GaucovyAero** [comment]
probably out of gpu memory, you gotta use less mods
