### ISSUE TITLE
[BUG] the modded version does'nt work 1.21.4

### ISSUE THREAD

**Issue by Trtryrey** [PojavLauncherTeam/PojavLauncher#6373]
### Describe the bug

When i want to play the moded minecraft optifine.there is a bug were the screen only turn to red and when i click anything its turn to black and there is clicking sound

### The log file and images/videos

And its holy glaes renderer

### Steps To Reproduce

```markdown
Dont know maybe check the renderer
```

### Expected Behavior

I

### Platform

```markdown
- Device model: oppo a95
- CPU architecture: andreno
- Android version: 14
- PojavLauncher version: latest on play store
```

### Anything else?

Nothing

**Comment by GaucovyAero** [comment]
log not provided
