### ISSUE TITLE
[My launcher is clearly tripping because it says its using arm64 but the arm 64 libduhejdhsne file isnt there

### ISSUE THREAD

**Issue by littleboulderbro** [PojavLauncherTeam/PojavLauncher#6374]
### Describe the bug

Won't launch because its like your jna is on 6.1.6 not 7.0.0 grrr

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17916714/latestlog.txt)

### Steps To Reproduce

```markdown
Uhm I kinda just launch the game
```

### Expected Behavior

I expect to get to the loading screen

### Platform

```markdown
- Device model: Fire HD 10
- iOS version: the latest one?
- PojavLauncher version: play store latest one
```

### Anything else?

no

**Comment by kiokori-git** [comment]
dude this is the pojavlauncher ios repo, go [here](https://github.com/PojavLauncherTeam/PojavLauncher/issues) instead 😭🙏

**Comment by littleboulderbro** [comment]
Oh lmao

**Comment by GaucovyAero** [comment]
the fact that jna is outdated is very likely not even your issue
1.21.4 works just fine for me

**Comment by littleboulderbro** [comment]
> the fact that jna is outdated is very likely not even your issue 1.21.4 works just fine for me

Not for me tho do I need to put more memory is 1000mb not enough anymore?
