### ISSUE TITLE
[BUG] Screen Glitch (Full screen to small screen - vice-versa)

### ISSUE THREAD

**Issue by Mahipal23** [PojavLauncherTeam/PojavLauncher#6376]
### Describe the bug

When shift+w is pressed the screen gets smaller and to revert it press the combination again

### The log file and images/videos

https://github.com/user-attachments/assets/6fced16c-af3d-4923-b5a1-43135ed498f2

### Steps To Reproduce

```markdown
1. Launch 1.8.9 (Optifine/Forge)
2. join a world/Server
3. Press shift+w (Screen gets smaller)
4. Press it again (Screen becomes normal)
```

### Expected Behavior

I expect it to not do anything, it's irritating as I do pvp or play any game when I don't want to take knockback so I press shift and w and this happens

### Platform

```markdown
- Device model: Vivo v23 5g
- CPU architecture: i don't know sry
- Android version: 14
- PojavLauncher version: Latest
```

### Anything else?

nope, Thank you

**Comment by Mahipal23** [comment]
Idk but I didnt realise that the 'W' capital form is causing this issue, its not just shift+w , as keeping capslock on and then pressing w will cause the same problem so basically the main problem is the capital w itself.

**Comment by GaucovyAero** [comment]
shift+w is a hardcoded android shortcut to f11, bind fullscreen to something else in minecraft options
