### ISSUE TITLE
[BUG] Fatal error 6

### ISSUE THREAD

**Issue by Zahar2loshara** [PojavLauncherTeam/PojavLauncher#6377]
### Describe the bug

The bug is: i cant enter a minecraft. (with mods but i dont problem in them)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18132528/latestlog.txt)

### Steps To Reproduce

```markdown
I dont really understand why its happening, what im doing is
1. Enter into Pojavlauncher
2. Start Mc (0.16.5 ver of fabric on 1.20.1)
3. Wait for loading...
4. Crash with error
5. Don't understand what does error 6 mean
6. Google it
7. Still dont understand
```

### Expected Behavior

1. Enter normally a game
2. Give me a more information about error

### Platform

```markdown
- Device model: Poco X6 Pro
- CPU architecture: arm64-v8a 
- Android version: "14 UP1A.230905.011" and hyperOS 
version 1.0.13.0.UNLMIXM
- PojavLauncher version: foxglove-20241212-011139d-v3_openjdk
```

### Anything else?

I dunno what to else say rn

**Comment by Xenko007** [comment]
have the Same Issue I don't Have a Clue what's the Issue but it isn't Running Any thing? but it Is trying Probably just a formatting and Loading Bug if i Were to Logically Assume

**Comment by Zahar2loshara** [comment]
Holy shit i somehow did it, ive have things was before change
1. Visualiser: Zink
2. Force vsync with Zink: true
3. Dedicated RAM: 3048 (or smth like that, for context i have 8 gigs)
4. System driver Vulkan: true

And ive changed it to

1. : Holy gl
2. : false
3. : 2040
4. : false
And removed mods: essential, vulkan mod, 1.21.1 fabric api

**Comment by Zahar2loshara** [comment]
I don't really know how it work and how in future will, but rn somehow work for me

**Comment by CamoWolf1222** [comment]
If it is fixed, should we close the issue?

**Comment by Zahar2loshara** [comment]
Probably yeah

**Comment by infinixity** [comment]
I have this issue but I can't seem to fix it, any help? Running Android version on my chromebook (works normally)
