### ISSUE TITLE
Comment on utilise pojavlaucher

### ISSUE THREAD

**Issue by Ryomensukuna3d00993** [PojavLauncherTeam/PojavLauncher#6378]
### Is this request related to a bug?

à chaque fois j'étais entrain de vouloir me connecter mais on me dit qu'il y a un problème 

### Describe the request.

Sa

### Anything else?

Sa m'empêche de jouer

**Comment by NoxlynU** [comment]
Si vous n'avez pas ajouté de compte, vous ne pouvez pas jouer.
Vous devez ajouter un compte et choisir "Microsoft Account" pour connecter votre compte Microsoft (Avec un compte Minecraft Java). Sinon, vous n'avez pas de compte Minecraft, choisissez "Local account" et choissez un nom d'utilisateur.
Si cela ne fonctionne toujours pas, assurez vous d'avoir accès à une connexion internet pour pouvoir vous connecter à votre compte et télécharger les fichiers du jeu. Vérifiez aussi que vous utilisez la dernière version de Pojav Launcher.
Si rien ne marche, essayez de désinstaller et de réinstaller l'application.

J'espère que ça aura pu vous aider.
