### ISSUE TITLE
[BUG] crash

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#638]
**Describe the bug**
App crash when I try to load game. No crash log

**To Reproduce**
1. Start Pojavlauncher
2. Select the any version(I set it with 1.12.2)
3. Try to run
...

**Expected behavior**
I expected it run normally

**Screenshots**
![Screenshot_20210118-080530](https://user-images.githubusercontent.com/39335760/104858622-01661100-5964-11eb-88d8-63ee27fe3fd0.png)
English : App/game has closed.

**Platform:**
 - Device Model : LG Q7
 - CPU architecture : 8x ARM Cortex-A53 @ 1.80 GHz
 - Android Version : 9.0

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
Not anough info

**Comment by ghost** [comment]
Then how can I reproduce it? There is no crash log

**Comment by artdeell** [comment]
You didn't even say the launcher version.

**Comment by ghost** [comment]
Launcher version : 3.3.1

**Comment by ghost** [comment]
Hello? No fixes? Unless I think you have to fix error logging...

**Comment by artdeell** [comment]
send the log

**Comment by artdeell** [comment]
`games/PojavLauncher/.minecraft/latestlog.txt`

**Comment by ghost** [comment]
--------- beggining with launcher debug
Info: LWJGL3 directory: [version, lwjgl-openal.jar, lwjgl-jemalloc.jar, lwjgl-opengl.jar, lwjgl-tinyfd.jar, lwjgl-glfw-classes.jar, lwjgl.jar, jsr305.jar, lwjgl-stb.jar]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms384m -Xmx768m"
Headless version detected! (20170918)
full args: [-cp, /storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-openal.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-jemalloc.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-opengl.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-tinyfd.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-glfw-classes.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/jsr305.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/lwjgl3/lwjgl-stb.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.12.2/1.12.2.jar, net.minecraft.client.main.Main, --username, Seanoo, --version, 1.12.2, --gameDir, /storage/emulated/0/games/PojavLauncher/.minecraft, --assetsDir, /storage/emulated/0/games/PojavLauncher/.minecraft/assets, --assetIndex, 1.12, --uuid, 0, --accessToken, 0, --userType, mojang, --versionType, release, --fullscreen]
--------- beginning of system
--------- beginning of main
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so success
S/LaunchJVM(29596): dlopen libawt.so failed: dlopen failed: library "libawt.so" not found
S/LaunchJVM(29596): dlopen libawt_headless.so failed: dlopen failed: library "libawt_headless.so" not found
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libfreetype.so success
S/LaunchJVM(29596): dlopen libfontmanager.so failed: dlopen failed: library "libfontmanager.so" not found
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libjsig.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/server/libjsig.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libjsound.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/librmi.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libjaas_unix.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libj2pkcs11.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libprefs.so failed: dlopen failed: cannot locate symbol "JNU_GetStringPlatformChars" referenced by "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libprefs.so"...
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libunpack.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libinstrument.so failed: dlopen failed: cannot locate symbol "JLI_ManifestIterate" referenced by "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/libinstrument.so"...
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libjimage.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libawt_xawt.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libzip.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libsunec.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libfreetype.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libjdwp.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libj2gss.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libsctp.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libdt_socket.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libj2pcsc.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libmanagement_agent.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libmanagement_ext.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libmanagement.so success
S/LaunchJVM(29596): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so success
S/LaunchJVM(29596): dlopen /data/app/net.kdt.pojavlaunch-OSUqLTlsLlw8EFge3SQIuQ==/lib/arm/libopenal.so success
S/LaunchJVM(29596): dlopen /data/app/net.kdt.pojavlaunch-OSUqLTlsLlw8EFge3SQIuQ==/lib/arm/libgl04es.so success
S/LaunchJVM(29596): Done processing args
S/LaunchJVM(29596): Found JLI lib
S/LaunchJVM(29596): Calling JLI_Launch
I/jrelog  (29596): [LWJGL] Failed to load a library. Possible solutions:
I/jrelog  (29596): 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
I/jrelog  (29596): 	b) Add the JAR that contains the shared library to the classpath.
I/jrelog  (29596): 
I/jrelog  (29596): [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
I/jrelog  (29596): 
I/jrelog  (29596): [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
I/jrelog  (29596): 
I/jrelog  (29596): [23:05:24] [Client thread/INFO]: Setting user: Seanoo
I/jrelog  (29596): Exception in thread "Client thread" 
I/jrelog  (29596): java.lang.UnsatisfiedLinkError: no awt in java.library.path
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.base/java.lang.System.loadLibrary(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/java.awt.Toolkit$3.run(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/java.awt.Toolkit$3.run(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.base/java.security.AccessController.doPrivileged(Native Method)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/java.awt.Toolkit.loadLibraries(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/java.awt.Toolkit.<clinit>(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/sun.awt.AppContext$2.run(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/sun.awt.AppContext$2.run(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.base/java.security.AccessController.doPrivileged(Native Method)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/sun.awt.AppContext.initMainAppContext(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/sun.awt.AppContext.access$400(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/sun.awt.AppContext$3.run(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/sun.awt.AppContext$3.run(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.base/java.security.AccessController.doPrivileged(Native Method)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/sun.awt.AppContext.getAppContext(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at java.desktop/javax.imageio.ImageIO.<clinit>(Unknown Source)
I/jrelog  (29596): 
I/jrelog  (29596): 	at bib.<init>(SourceFile:390)
I/jrelog  (29596): 
I/jrelog  (29596): 	at net.minecraft.client.main.Main.main(SourceFile:123)
I/jrelog  (29596): 
Java Exit code: 1
S/LaunchJVM(29596): Going to free args
S/LaunchJVM(29596): Free done
read: unexpected EOF!
--------- beginning of main
read: unexpected EOF!
--------- beginning of main

**Comment by khanhduytran0** [comment]
JRE9 will not work correctly. Use JRE8. But currently if you want JRE8 ARM32, no 1.5.2 and below support yet.

**Comment by ghost** [comment]
Ok I redownloaded with JRE8 x86 and this error happened this time
![Screenshot_20210121-072018](https://user-images.githubusercontent.com/39335760/105248080-27382380-5bb9-11eb-954b-7638831475eb.png)
English : ~ is not compatible with ~

Error log : 
java.lang.RuntimeException: Architecture arm/aarch32 은(는) Java Runtime i586에 호환되지 않습니다.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:37)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:877)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2200(BaseMainActivity.java:26)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:673)
	at java.lang.Thread.run(Thread.java:764)

**Comment by khanhduytran0** [comment]
x86 is for Intel CPUs.

**Comment by ghost** [comment]
Ah for 32 bit android is in development.

**Comment by ghost** [comment]
Now it works. Thx
