### ISSUE TITLE
[BUG] <Short description> A lan não aparece nas versões recentes

### ISSUE THREAD

**Issue by NOOREKOO** [PojavLauncherTeam/PojavLauncher#6383]
### Describe the bug

O server lan não aparece mesmo usando a mesma internet ou usando vpn ele só não aparece para entrar ja tentei muitos metodos mas não resolveu ajuda ae man por favor

### The log file and images/videos

Não aparece

### Steps To Reproduce

```markdown
1. Inicie o pojav em dois celulares nas versões recentes
2. Entre no multiplayer
3. No outro celular abra um server lan
```

### Expected Behavior

Queria jogar junto com meu amigo sem usar o aternos

### Platform

```markdown
- Device model: motorola g34
- CPU architecture: adreno
- Android version: 14
- PojavLauncher version: não vi
```

**Comment by GaucovyAero** [comment]
known issue, duplicate of #5493 
create a minecraft server with termux instead or use aternos or something idk
