### ISSUE TITLE
[BUG] <Short description>THE MINECRAFT ACCOUNT BUGG

### ISSUE THREAD

**Issue by NoTygaming** [PojavLauncherTeam/PojavLauncher#6385]
### Describe the bug

I'm having a issue. SO I recently bought my Minecraft account and then after 1 Month it is showing that u do not have a mc account on pojav launcher : it says :  something like this if u have a Xbox (something ) plz logged into mc account and do the process

### The log file and images/videos

I'm having a issue. SO I recently bought my Minecraft account and then after 1 Month it is showing that u do not have a mc account on pojav launcher : it says :  something like this if u have a Xbox (something ) plz logged into mc account and do the process:

### Steps To Reproduce

```markdown
When ever you start your pojav launcher with ur mc account it will say something like this : you don't have a mc account or it will say if u have a Xbox (something) plz do the process on Minecraft.net
```

### Expected Behavior

When ever you start your pojav launcher with ur mc account it will say something like this : you don't have a mc account or it will say if u have a Xbox (something) plz do the process on Minecraft.net 🙏

### Platform

```markdown
- Device model: Redmagic 8s pro
- CPU architecture: idk how to check it
- Android version: 14
- PojavLauncher version: lastest
```

### Anything else?

I'm sad cuz I spend 30$ on it;(
![Screenshot_PojavLauncher (Minecraft_ Java Edition for Android)_20241215_222251](https://github.com/user-attachments/assets/0e752808-9bf0-4a86-ad81-b446e5df2043)

**Comment by kiokori-git** [comment]
does it still happen after deleting the account profile from pojavlauncher, restarting pojavlauncher, and re-login again with your microsoft account?

**Comment by GaucovyAero** [comment]
you gotta log into minecraft.net, this just happens sometimes cause microsoft
