### ISSUE TITLE
[BUG] Black Screen Pojav Launcher 1.12.2 Forge

### ISSUE THREAD

**Issue by Exreizz** [PojavLauncherTeam/PojavLauncher#6387]
### Describe the bug

when i install mod like blockbuster and mclib, my pojav after mojang scene is black, do you guys same, how to fix this, i have my latestlog

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18146108/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install Forge 1.12.2
3. install mod like blockbuster
4. Wait after the mojang screen appear
5. Then the Bug Appear:)
```

### Expected Behavior

The screen is not black

### Platform

```markdown
- Device model: Vivo 1904
- CPU architecture: idk this :v
- Android version: 11
- PojavLauncher version: Latest
```

### Anything else?

pls guys i need help :(

**Comment by GaucovyAero** [comment]
some mod is using shaders that gl4es cant run
