### ISSUE TITLE
[BUG] issue with fabric 1.21.4 lwjgl

### ISSUE THREAD

**Issue by BlueSifn** [PojavLauncherTeam/PojavLauncher#6388]
### Describe the bug

when i open pojav and try to run 1.21.4 fabric it opens and gives me an error also the game not not load 

### The log file and images/videos

There is an incompatible JNA native library installed on this system
Expected: 7.0.2
Found:    6.1.6
(at /data/app/net.kdt.pojavlaunch-xYXiTDW80Jso8iFu2g0Iyg==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]

### Steps To Reproduce

```markdown
open pojav launcher 
run fabric 1.21.4
game does not load though does not crash
```

### Expected Behavior

i just cant seem to make the game qork and am looking for a solution

### Platform

```markdown
- Device model: Samsung S9+
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

thats it

**Comment by Marshall2439** [comment]
send latestlog.txt

**Comment by 1fbw2** [comment]
same issue, any fix?
@Marshall2439 ill send you mine
[latestlog.txt](https://github.com/user-attachments/files/18215935/latestlog.txt)

**Comment by BlueSifn** [comment]
> same issue, any fix? @Marshall2439 ill send you mine [latestlog.txt](https://github.com/user-attachments/files/18215935/latestlog.txt)

i have the same issue and the same log

**Comment by 1fbw2** [comment]
> > same issue, any fix? @Marshall2439 ill send you mine [latestlog.txt](https://github.com/user-attachments/files/18215935/latestlog.txt)
> 
> i have the same issue and the same log

ya got any fix?

**Comment by GaucovyAero** [comment]
```
java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
	at knot//net.minecraft.class_276.method_1239(class_276.java:165)
```

unrelated issue, try using a different renderer

**Comment by 1fbw2** [comment]
wdym unrelated issue
