### ISSUE TITLE
[BUG] Bug Bug Bug please fix

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#639]
Spawn egg and the leaves are white in the player's hand! this does not happen in Java it is not a bug of minecraft itself but of pojav

**Comment by Zeyrox1090** [comment]
hmmm i think its bug from minecraft cuz that happens to me normally on mc java on my computer it happens on mc bedrock too

**Comment by khanhduytran0** [comment]
Switch to GL4ES 1.1.5 by add `-Dorg.lwjgl.opengl.libname=libgl4es_115.so` to JVM arguments will fix this. Note that MC 1.14.4 and below may have some graphical issues on GL4ES 1.1.5.

**Comment by OwzygZawg** [comment]
Okay

**Comment by OwzygZawg** [comment]
-Dorg.lwjgl.opengl.libname=libgl4es_115.so in options, lastelog? Or JVM?

**Comment by khanhduytran0** [comment]
In jvm arguments.

**Comment by OwzygZawg** [comment]
Above or below? when I put it down Minecraft hangs and comes out

**Comment by OwzygZawg** [comment]
above or below?
![Screenshot_20210118-185731_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/104966347-6e5ac480-59bf-11eb-9b61-b38518fdff84.jpg)

**Comment by khanhduytran0** [comment]
Maybe below

**Comment by khanhduytran0** [comment]
Remember to add a space before pasting argument.

**Comment by OwzygZawg** [comment]
Okay thanks!

**Comment by Forever2397** [comment]
there is one problem in PojavLauncher when using the above jvm when I hit the animal it will be black

**Comment by mchnjt** [comment]
> Spawn egg and the leaves are white in the player's hand! this does not happen in Java it is not a bug of minecraft itself but of pojav

Hmm i think you should fill template

**Comment by mchnjt** [comment]
> above or below?
> ![Screenshot_20210118-185731_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/104966347-6e5ac480-59bf-11eb-9b61-b38518fdff84.jpg)
> 

Holy-
