### ISSUE TITLE
Help I can't play BTW 3.0

### ISSUE THREAD

**Issue by takanayun-horny** [PojavLauncherTeam/PojavLauncher#6393]
### Is this request related to a bug?

It is not

### Describe the request.

Just wanna play the newest version of BTW

**Comment by GaucovyAero** [comment]
pls actually give some info about like what you have already tried and stuff

**Comment by GaucovyAero** [comment]
the latest version of BTW is community edition 2.1.4

guide here [INSTALL_BTW_updated_v1.2.pdf](https://github.com/user-attachments/files/18270062/INSTALL_BTW_updated_v1.2.pdf)

**Comment by takanayun-horny** [comment]
> the latest version of BTW is community edition 2.1.4
> 
> guide here [INSTALL_BTW_updated_v1.2.pdf](https://github.com/user-attachments/files/18270062/INSTALL_BTW_updated_v1.2.pdf)

I tried to install btw3.0 by using this guide and replacing the mod file with the 3.0 one
