### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Desko12a31** [PojavLauncherTeam/PojavLauncher#6394]
### Is this request related to a bug?

Www

### Describe the request.

Waw

### Anything else?

Www

**Comment by Desko12a31** [comment]
Q1

**Comment by Desko12a31** [comment]
Aa

**Comment by Desko12a31** [comment]
Q

**Comment by Desko12a31** [comment]
Www

**Comment by Desko12a31** [comment]
- Device model: ? 
- CPU architecture: ?
- Android version: Motorola e13
- PojavLauncher version: v3?

**Comment by Desko12a31** [comment]
Www

**Comment by Desko12a31** [comment]
###

**Comment by Desko12a31** [comment]
[Uploading lom_log.txt…]()

**Comment by Desko12a31** [comment]
Desko12a31

**Comment by MandatoryMacaroni** [comment]
Wtf is this ☠️
