### ISSUE TITLE
[BUG] whenever i launch Fabulously Optimized modpack the main menu buttons are.. gone,.?

### ISSUE THREAD

**Issue by 1fbw2** [PojavLauncherTeam/PojavLauncher#6398]
### Describe the bug

whenever i launch the game, it loads fine and then at the main menu it doesnt display the buttons. they work in some weird way but not as intended. its all a black screen.

i have tried  more ram, less ram, java 8, java 21 (JRE Temurin) and all of the settings in there. it either: crashes or doesnt show menu buttons (current issue)
 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18214779/latestlog.txt)
https://github.com/user-attachments/assets/90bffa05-bad8-469d-86f3-2a9ac46a96d4

### Steps To Reproduce

```markdown
1. Start Minecraft
2. Go to Main menu
```

### Expected Behavior

menu buttons

### Platform

```markdown
- Device model: Xioami Poco F6
- CPU architecture: Snapdragon(R) 8s Gen 3 Mobile Platform Octa-core Max 3.0GHz
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk (Google Play)
```

### Anything else?

i want shader stress test

**Comment by GaucovyAero** [comment]
Added custom env: POJAV_ZINK_PREFER_SYSTEM_DRIVER=1

try turning this setting off in the launcher
