### ISSUE TITLE
Owner can you add opengl 2.0 and optifine fix it

### ISSUE THREAD

**Issue by Dennisken2320** [PojavLauncherTeam/PojavLauncher#64]
Owner is old graphics but you could add it pleasee ok an opengl 2.0 and fix the optifine is error after full loading is double error after close the installer loading is stuck and crashes if before you use optifine version after play is crashed

**Comment by khanhduytran0** [comment]
No, I do not own GL4ES so any fix depending on the owner of GL4ES.

**Comment by artdeell** [comment]
Maybe launcher will support Regal, which is OpenGL 4.4-compartible.

**Comment by Dennisken2320** [comment]
Okkkk

**Comment by Azapru** [comment]
omae wa mou shindeiru

**Comment by Dennisken2320** [comment]
ONANI!

**Comment by khanhduytran0** [comment]
Don't happy early, it is **MAYBE**, not **WILL**.

**Comment by khanhduytran0** [comment]
> Owner is old graphics but you could add it pleasee ok an opengl 2.0...

I fixed OpenGL 2 warning.

> ... and fix the optifine is error after full loading is double error after close the installer loading is stuck and crashes if before you use optifine version after play is crashed

Not sure if I understand.

**Comment by Dennisken2320** [comment]
Maybe?

**Comment by khanhduytran0** [comment]
> Maybe?

Hmm... I'm and @artdeell tried without success, it **fire** too much errors in `glGetError` and undefined function pointer...

**Comment by Dennisken2320** [comment]
Ehh who talking to you?? You said owner

**Comment by khanhduytran0** [comment]
Not sure if something Regal success in the future.
