### ISSUE TITLE
[BUG]Android CI #1395 cannot be installed ? 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#640]
Can't install Android Cl #1395.Error In archive.

**Comment by artdeell** [comment]
Redownload the file

**Comment by ghost** [comment]
Would it work

**Comment by ghost** [comment]
Uploading Screenrecorder-2021-01-18-10-00-11-541.mp4…


Doesn't work

**Comment by khanhduytran0** [comment]
Workflows ran 3 months ago or more will no longer available.

**Comment by ghost** [comment]
Ok
