### ISSUE TITLE
[BUG] Application exited with code 1

### ISSUE THREAD

**Issue by Nathan12e4** [PojavLauncherTeam/PojavLauncher#6402]
### Describe the bug

Every time i open pojavlauncher and play it keeps showing the error i dont know why this kept happening but maybe its due to the mods

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18229707/latestlog.txt)
![Screenshot_2024-12-23-21-08-07-891_net kdt pojavlaunch](https://github.com/user-attachments/assets/3150b046-1c42-420d-ba82-52e863b97a56)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher and click play
2.Wait for this error to show the error
```

### Expected Behavior

I expect to play pojavlauncher along with some performance optimization mods (i double check to see if the mods were supported)

### Platform

```markdown
- Device model: 22120RN86G
- CPU architecture: Mediatek Helio G85 Octa Core Max 2.0 ghz
- Android version: Hyperos 14
- PojavLauncher version: 
Version foxglove-20241124-a5d02c1-v3_openjdk
```

**Comment by GaucovyAero** [comment]
```
Exception in thread "main" java.lang.IllegalArgumentException: 1.0-1.19+: Empty pre-release
	at java.base/java.lang.module.ModuleDescriptor$Version.<init>(ModuleDescriptor.java:1054)
```

most likely not a pojav issue, use a different version of forge
