### ISSUE TITLE
Error -1

### ISSUE THREAD

**Issue by Kapik11992** [PojavLauncherTeam/PojavLauncher#6409]
### Describe the bug

When i launch thunderhack 1.20.4 it crashes with error -1

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18238941/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Launch 1.20.4 fabric with thunderhack and fabric api java 21
3. Get crash with code -1
```

### Expected Behavior

Not crash

### Platform

```markdown
- Device model: Samsung Galaxy A55
- CPU architecture: arm-Cortex-A78
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

**Comment by GaucovyAero** [comment]
i think your hack client tries to show another window, which is not supported

**Comment by Kapik11992** [comment]
okey if i use thunderhack for 1.21 it shows error code 1 error code 1 is
java version not correct but thunderhack requires java 21+ i have cpu
aarch64 but i have java21 for arm64 can i get for aarch64

pt., 27 gru 2024, 15:40 użytkownik GaucovyAero ***@***.***>
napisał:

**Comment by Kapik11992** [comment]
> i think your hack client tries to show another window, which is not supported

okey if i use thunderhack for 1.21 it shows error code 1 error code 1 is java version not correct but thunderhack requires java 21+ i have cpu aarch64 but i have java21 for arm64 can i get for aarch64
