### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by berwulf** [PojavLauncherTeam/PojavLauncher#641]
**Describe the bug**
Crash when downloading 1.16.4 

**To Reproduce**
1. Start PojavLauncher
2. Download 1.16.4
3. Get error message:

java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1087)
	at net.kdt.pojavlaunch.MainActivity.access$3100(MainActivity.java:37)
	at net.kdt.pojavlaunch.MainActivity$14$1.run(MainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at afm.<clinit>(SourceFile:36)
	at afm.a(SourceFile:112)
	at x.a(SourceFile:101)
	at x.<clinit>(SourceFile:63)
	at x.b(SourceFile:89)
	at net.minecraft.client.main.Main.main(SourceFile:64)
	... 5 more

...

**Expected behavior**
I expected the game to open up normally at this point (for some reason i can't download v3.3, it's always stuck at 99%, problem doesn't apply to older versions of the app)

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128] Redmi 9
 - CPU architecture [e.g. aarch64] aarch64 i think since its a 64 bit
 - Android Version [e.g. 10] 10 (MiUi11)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
V2 does not able to run 1.12+. Maybe find a better network and try download v3 anyways?

**Comment by berwulf** [comment]
I think i downloaded v3.0? Lemme check

I'm sure it's not 2 bc i read the bug fixes before tapping assets

**Comment by berwulf** [comment]
Ok wait apaprently its a v2

Idk why it's squeezed between 3.3 and other 3 test versions

**Comment by khanhduytran0** [comment]
You should update to v3.3.1

**Comment by berwulf** [comment]
I cant its still stuck on 99% look
![Uploading Screenshot_2021-01-18-14-23-56-402_com.android.chrome.jpg…]()

**Comment by berwulf** [comment]
![Screenshot_2021-01-18-14-23-56-402_com android chrome](https://user-images.githubusercontent.com/26784016/104879522-f9749400-5998-11eb-8e86-64573eee4e52.jpg)

**Comment by khanhduytran0** [comment]
> look

You are seems too fast. Image was not even done uploaded.

**Comment by berwulf** [comment]
The net speed isnt an issue, otherwise I wouldn't be able to reach 99% in 30 minutes

Its slow but consistent, also my comments here in github get send immediately

**Comment by berwulf** [comment]
> > look
> 
> You are seems too fast. Image was not even done uploaded.

I forgot it needs to load in the chatbar, woops

**Comment by khanhduytran0** [comment]
What about pause and resume?

**Comment by berwulf** [comment]
Yeah i did that already, Still the same
![Screenshot_2021-01-18-14-28-09-282_com android chrome](https://user-images.githubusercontent.com/26784016/104879760-6c7e0a80-5999-11eb-9011-bcfbfc20354a.jpg)

**Comment by berwulf** [comment]
This is the third dl

**Comment by khanhduytran0** [comment]
Try this one https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/492055539
(It's different with one on release)

**Comment by khanhduytran0** [comment]
Maybe try download on different browser?

**Comment by ghost** [comment]
Works fine for me.
![Screenshot_2021-01-18-12-06-23-934_com android chrome](https://user-images.githubusercontent.com/70811047/104880486-a34a2580-5985-11eb-957e-d0de7796a660.jpg)
![Screenshot_2021-01-18-12-06-27-934_com android chrome](https://user-images.githubusercontent.com/70811047/104880491-a7764300-5985-11eb-8867-d49263bb4c58.jpg)

**Comment by ghost** [comment]
Thanks @khanhduytran0 this release versions has optifine 1.16.4 working. Thanks so much

**Comment by berwulf** [comment]
Got any runtime links? The ones i downloaded dont seem to work (i got them from mcinabox) btw ive downloaded that appversion, the only ones i cant download are 3.3 and 3.2 with built in runtime

Also slr i tried restarting my phone whether it's a system issue, as you can see 3.2 also froze at 99% 
![Screenshot_2021-01-18-14-34-50-179_com android chrome](https://user-images.githubusercontent.com/26784016/104883189-5a9f6600-599f-11eb-95ff-6cee42dc5141.jpg)

**Comment by berwulf** [comment]
Redownloading the one you suggested earlier right now

Hope it doesnt get stuck at 71 mb

**Comment by ghost** [comment]
@PixelDigits21 did it stuck?

**Comment by Google61** [comment]
@PixelDigits21 I suggest you to try some download manager, like [this](https://play.google.com/store/apps/details?id=com.dv.adm) one. I use it if I'm unable to download something from Chrome.

**Comment by Mathias-Boulay** [comment]
The google play version doesn't have this issue and won't suffer from download issues.
Closing the issue.
