### ISSUE TITLE
[BUG] Mouse isn't locked in the middle while playing

### ISSUE THREAD

**Issue by mwdsj** [PojavLauncherTeam/PojavLauncher#6410]
### Describe the bug

When I use a external mouse,the mouse cursor isn't locked in the middle.I need to press left mouse button and drag,like touching screen.

### The log file and images/videos

https://github.com/user-attachments/assets/44d462e2-2289-4e81-ab7c-9cc27ca81031

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Enter a game
3.Try to rotate the view
```

### Expected Behavior

The mouse cursor is locked and hidden.

### Platform

```markdown
- Device model: ZTE Pad W201DS
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

-

**Comment by GaucovyAero** [comment]
this is an issue with your device, fixing this on your model might break it on all other devices
