### ISSUE TITLE
Questions regarding LTW renderer

### ISSUE THREAD

**Issue by DRONZER850** [PojavLauncherTeam/PojavLauncher#6414]
### Is this request related to a bug?

No

### Describe the request.

First of all a big thanks to pojav team to give support of sodium using ltw. I know it's not in playstore version but still.

So I just want to ask about the LTW renderer like it is really good in giving performance with support of shaders but without shadows. So in future can we use shaders with shadows on it. Also I want to know that is it the best performance renderer right now or you can add more good renderers. Will you add this in playstore version too. 

### Anything else?

Are there plans to enhance the LTW Renderer for better performance and compatibility?

**Comment by azurawrtata** [comment]
Its kinda impossible to make renderer with shader support that gives huge performance boost compared to vanilla/performance modded vanilla. 

And also there's already LTW build with shadow support , you can ask someone on their discord server.

**Comment by DRONZER850** [comment]
I mean, if it's possible to create a renderer that supports all mods and shaders and gives better performance than vanilla or modded vanilla, that would be amazing. But if that's not achievable, a renderer that delivers the same performance as vanilla while supporting all mods and shaders isn't a bad outcome either.

Also thanks for telling me about the LTW build with shadow support but I joined pojav discord once and they removed me from chat because I don't own Minecraft but I will manage.

**Comment by azurawrtata** [comment]
> I mean, if it's possible to create a renderer that supports all mods and shaders and gives better performance than vanilla or modded vanilla, that would be amazing. But if that's not achievable, a renderer that delivers the same performance as vanilla while supporting all mods and shaders isn't a bad outcome either.
> 
> Also thanks for telling me about the LTW build with shadow support but I joined pojav discord once and they removed me from chat because I don't own Minecraft but I will manage.

All mods and shader? Zink is the answer. But newer Zink compatibility issue on Mediatek devices. For Snapdragon only few affected and since they can install custom drivers , its a win-win situation for them.

**Comment by DRONZER850** [comment]
But isn't Zink an unoptimized renderer as compared to other renderer.

**Comment by azurawrtata** [comment]
> But isn't Zink an unoptimized renderer as compared to other renderer.

It depends on your phone hardware. As far i know the official Pojav on Playstore kinda broken than github version. Some shaders cant be loaded either. I had to change Turnip driver to make it work properly. 

Top is default driver while bottom is custom.


![1000202264](https://github.com/user-attachments/assets/d0fbb7cc-8ced-4d13-bd9c-dfadb0ce7d46)
![1000202265](https://github.com/user-attachments/assets/22babd51-a74a-4180-a059-1d5fa5684956)

**Comment by Kgdjj** [comment]
Hello, how are you Where did you get the app or if there is a link to download it

**Comment by DRONZER850** [comment]
I know it depends upon phone hardware but see it doesn't matches the performance with renderer like LTW and other. Making it decent to play but not good. 

I hope Pojav Team will do something about it. I can only  hope about it cuz I don't know anything much about these coding stuff. 

BTW thank you so much for helping me with my question.

**Comment by Kgdjj** [comment]
Ok, it's a good request for the developers of pojav. I play minecraft on pojav with fabric and sodium, the current versions of sound don't work, the same launcher sends me an alert when I enter a world and kicks me out of the game.

**Comment by azurawrtata** [comment]
> Hello, how are you Where did you get the app or if there is a link to download it
Its from the current github release. Just scroll all the way down.

**Comment by azurawrtata** [comment]
> Hello, how are you Where did you get the app or if there is a link to download it

It's from current github release. Just scroll all the way down

**Comment by azurawrtata** [comment]
> I know it depends upon phone hardware but see it doesn't matches the performance with renderer like LTW and other. Making it decent to play but not good.
> 
> I hope Pojav Team will do something about it. I can only hope about it cuz I don't know anything much about these coding stuff.
> 
> BTW thank you so much for helping me with my question.

Probably because LTW exports OpenGL 3.0 , while Zink OpenGL 4.6. It has more extension thus utilizing it.

**Comment by beta-mango** [comment]
> And also there's already LTW build with shadow support , you can ask someone on their discord server.

Well I asked about that build on pojav discord server and the answer they gave me doesn't make sense. How come you know about that build? Where did you find it? I'm interested because I couldn't find anything related to the LTW build supporting shadows

**Comment by azurawrtata** [comment]
> > And also there's already LTW build with shadow support , you can ask someone on their discord server.
> 
> Well I asked about that build on pojav discord server and the answer they gave me doesn't make sense. How come you know about that build? Where did you find it? I'm interested because I couldn't find anything related to the LTW build supporting shadows

One of the moderator post a picture of BSL with shadow turned on. You can  ask SolDev for it but im not sure if its gonna guarantee you to get it.

**Comment by Kejwjdjjsjdj** [comment]
Hello, I am using Ltw renderer but when I open shader it is like this. If you know the solution, can you tell me? My device is: "Redmagic 9 pro"

![Image](https://github.com/user-attachments/assets/0b120d94-8b2c-4223-8bf8-b8a3a9db6ca7)
