### ISSUE TITLE
[BUG] Texture crash

### ISSUE THREAD

**Issue by xCROYSx** [PojavLauncherTeam/PojavLauncher#6417]
### Describe the bug

Hello!
Textures disappear when a meteorite from ae2 is found, presumably. It only helps to restart on another visualizer and leave the field of view.
Modpack Jacon Ex Machina, downloaded from Curse.
Also in the Clouds of Darkness modpack, also downloaded from Curse, when I install something from ae2, textures disappear. It only helps to restart on another visualizer and remove the supplied block.
 Holy GL4ES visualizer.
There is no such problem on Zink, but it is very slow.

### The log file and images/videos

![Screenshot_20241228_120057_net kdt pojavlaunch](https://github.com/user-attachments/assets/e66a873e-0b95-41b1-98a0-5daff38e2691)

https://github.com/user-attachments/assets/a6c89c2d-87b1-4a82-bf6c-67db54ec489e

[latestlog.txt](https://github.com/user-attachments/files/18267735/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Enter twe world
3. Find a meteorite from AE2 or place a block from AE2
```

### Expected Behavior

I expect my textures not breaking 

### Platform

```markdown
- Device model: Vivo T1
- CPU architecture: Snapdragon 680
- Android version: 14 
- PojavLauncher version: net.kdt.pojavlaunch_foxglove-20241124-a5d02c1-v3_openjdk.apks
```

**Comment by GaucovyAero** [comment]
cant really help here
it says theres a nullpointerexception, so it might not really be a shader issue, dunno
try using zink, if that doesnt work, try using the mod on another mc version

**Comment by GaucovyAero** [comment]
maybe try and see if you can change some shader or visual options in the ae2 config somewhere in .minecraft/config

**Comment by xCROYSx** [comment]
Upgrading AE2 to applicedenergistics2-rv3-beta-6 helped me with Modpack Jason Ex Machina.

**Comment by GaucovyAero** [comment]
good
