### ISSUE TITLE
[BUG] Crash while starting

### ISSUE THREAD

**Issue by hop-kl23** [PojavLauncherTeam/PojavLauncher#6418]
### Describe the bug

When I start pojavlauncher it crashes in 2-3 seconds with code -1 while it is in the "black screen" part.

### The log file and images/videos

![Screenshot_20241229_104746_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/8857a096-c70a-4d7a-b553-bf60ba921a0b)

Log: 
[latestlog.txt](https://github.com/user-attachments/files/18268617/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. It downloads game files
3. Instantly crashes
```

### Expected Behavior

I expect it to work properly till the main menu of the game

### Platform

```markdown
- Device model: Galaxy Tab A7 Lite
- CPU architecture: Octa-Core, 2.3GHz
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

I deleted it for a week and yesterday downloaded it back. I hope the information I gave will help to solve this issue

**Comment by GaucovyAero** [comment]
avoid using custom runtimes and use internal-21 instead
