### ISSUE TITLE
[BUG] Fabric 1.21.4 crashes with code 1

### ISSUE THREAD

**Issue by thecatoutside** [PojavLauncherTeam/PojavLauncher#6419]
### Describe the bug

I tried to launch fabric on the version 1.21.4 with the latest fabric launcher and then it crashed with error code 1.

Steps to reproduce:
Open Pojavlauncher,
Download Fabric for 1.21.4,
Install Mods; (specifically, Sodium, Lambdynamiclights, Clothconfig, MemoryleakFix, Fabric API, Modmenu, Moreculling, Reeses-Sodium-Options, Sodium Extra,)
Play,
Get this error message.

Log File:
[latestlog.txt](https://github.com/user-attachments/files/18268701/latestlog.txt)

It says: Error: Could not find or load main class net.fabricmc.loader.impl.launch.knot.KnotClient
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient

Proof: 

https://github.com/user-attachments/assets/e36e9770-b661-4af6-842b-698c6371fafa

### The log file and images/videos

Screenrecording: https://github.com/user-attachments/assets/e36e9770-b661-4af6-842b-698c6371fafa

Log: [latestlog.txt](https://github.com/user-attachments/files/18268701/latestlog.txt)

### Steps To Reproduce

```markdown
Open Pojavlauncher,
Download Fabric for 1.21.4,
Install Mods; (specifically, Sodium, Lambdynamiclights, Clothconfig, MemoryleakFix, Fabric API, Modmenu, Moreculling, Reeses-Sodium-Options, Sodium Extra,)
Play,
Get this error message.
```

### Expected Behavior

I expected Minecraft to run without any issue

### Platform

```markdown
- Device model: Realme Narzo N53
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

**Comment by GaucovyAero** [comment]
you are missing fabric libraries, try messing with the libraries settings in the launcher, make sure the download source is set to the default one and try reinstalling fabric
worst case scenario reinstall the launcher or get the libraries folder from PC, idk

**Comment by thecatoutside** [comment]
> you are missing fabric libraries, try messing with the libraries settings in the launcher, make sure the download source is set to the default one and try reinstalling fabric worst case scenario reinstall the launcher or get the libraries folder from PC, idk

Library settings are untouched (there isn't that many, library Hash one is on), download source is default, although I haven't reinstalled the launcher yet.

**Comment by open3doled** [comment]
@thecatoutside I have the same issue not with PojavLauncher though just installed via MultiMC did you ever figure out how to fix the issue? Re-installing the launcher isn't working for me.
