### ISSUE TITLE
Application game aborted by fatal signal  6 

### ISSUE THREAD

**Issue by allblue17** [PojavLauncherTeam/PojavLauncher#6420]
### Describe the bug

Shader keep crashing when putting shaders on optifine 1.21.4 (zink render),...  I tried all tutorial but didnt work,...  Its really weird to see this.  Others didnt have this issue.. 

### The log file and images/videos

![Screenshot_20241229-050200_Pojav Glow·Worm](https://github.com/user-attachments/assets/8650c751-f48d-4824-9b53-73dd05bb427c)

### Steps To Reproduce

```markdown
1. Start pojav
2. Open game 
3. Putting shaders
4. Loadig shader 
5. Crash
```

### Expected Behavior

...

### Platform

```markdown
- Device model: oneplus 7T
- CPU architecture: snapdragon 855 plus
- Android version: 15
- PojavLauncher version: lastest
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
try putting 

MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460

into /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt

if it still doesnt work, then you prolly cant do anything about it
i guess you can try older versions of pojav or something idk

**Comment by allblue17** [comment]
It not working too..  Pojav glow worm has this feature on their setting menu,,  i changed everything but always crash..  But yes older version actually work

**Comment by ghost** [comment]
> It not working too.. Pojav glow worm has this feature on their setting menu,, i changed everything but always crash.. But yes older version actually work

Try legacy zink in solcraft launcher or LTW renderer with sodium and iris shaders mod.
