### ISSUE TITLE
[BUG] I cant play with optifine

### ISSUE THREAD

**Issue by Jko4775** [PojavLauncherTeam/PojavLauncher#6421]
### Describe the bug

I dowlond optifine 1.16.5 i join game and chunk not updated and i cant play. I am on android and my phone is samsung galaxy s21 please help me.

### The log file and images/videos

![Screenshot_20241229_113434_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/09f06a54-dff4-4e28-b68d-6fa2f0c320c5)
![Screenshot_20241229_113422_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/87c4477a-088a-41bd-bd66-82e3abd0cb15)

### Steps To Reproduce

```markdown
1.Open Pojavlauncher

2.Dowlond optifine 1.16.5 G8

3.Join game and chunks cant update
```

### Expected Behavior

I want to play with optifine

### Platform

```markdown
- Device model: Samsung Galaxy S21 FE
- CPU architecture: 3x ARM Cortex-A78 @ 2,81 GHz 4x ARM Cortex-A55 @ 2,21 GHz 1x ARM Cortex-X1 @ 2,91 GHz
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

Please help

**Comment by GaucovyAero** [comment]
reset your video settings, make sure render regions is turned off

**Comment by Jko4775** [comment]
how i can turn off render regions

**Comment by Jko4775** [comment]
> reset your video settings, make sure render regions is turned off


 I fix it man Thank you so much Have a good day
