### ISSUE TITLE
[BUG] Adding any mod Fabric makes it not load anymore (mc 1.20.1 fabric 0.16.9)

### ISSUE THREAD

**Issue by TheLegendary2007** [PojavLauncherTeam/PojavLauncher#6422]
### Describe the bug

I want to try a client that uses fabric and it refuses to work when it is placed in the mods folder, same happens when I add a fabric compatible mod like the latest vulkanMod 

### The log file and images/videos

![Screenshot_2024-12-29-16-54-59-997_ru zdevs zarchiver](https://github.com/user-attachments/assets/4f85d3fc-8481-4f13-8e44-cf561b97ba6e)
[latestlog.txt](https://github.com/user-attachments/files/18270027/latestlog.txt)

### Steps To Reproduce

```markdown
Make 1.20.1 with fabric 0.16.9 version
Add mod to mod folder using ZArchiver since Files by Marc does not have access to the data folder
Hit play
Gets stuck on black screen
```

### Expected Behavior

Load in.

### Platform

```markdown
- Device model: Xiaomi 13T Pro 12/512
- CPU architecture: arm (mediatek dimensity 9200+)
- Android version: 15 with hyperos 1.0.4
- PojavLauncher version: latest on Google play at the time of posting (and up to date)
```

### Anything else?

I have already went through other bug posts about this and nothing works from them.
Note: the files attached are:
- Photo log file under the .Minecraft folder
- file is log file of app itself

**Comment by GaucovyAero** [comment]
use files by marc to move the files

**Comment by TheLegendary2007** [comment]
> use files by marc to move the files

It does not work, I have already mentioned that, files by marc doesn't work
