### ISSUE TITLE
[BUG] World keeps crashing

### ISSUE THREAD

**Issue by someone000-eng** [PojavLauncherTeam/PojavLauncher#6423]
### Describe the bug

While making world for friends,i was choosing loot,and i choosed akm with optics and laser with silencer,after pressing "z" button my game crashed,and after joining again it just keep crashing

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18270869/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start Pojava
2.Use optic on some gun
3.Have fun with ruined world
(even playerdata deletion and changing profiles wont save you)
```

### Expected Behavior

I wanted gun with optics,not world that cant join

### Platform

```markdown
- Device model: Infinix X669D
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

Version of minecraft:
1.20.1
using forge for mod
forge version:
47.3.11

**Comment by GaucovyAero** [comment]
your guns mod is loading custom shaders that gl4es cant handle

**Comment by GaucovyAero** [comment]
you gotta remove the mod
