### ISSUE TITLE
Modpack bug

### ISSUE THREAD

**Issue by Geourt7** [PojavLauncherTeam/PojavLauncher#6424]
### Describe the bug

Every time I create a modpack profile and I enter in the modpack it appears a code 1 thing in some modpacks and in some other modpacks it crashes on de mojang screen and in other modpacks when you try to create a world and appears the louding thing it gets me out of pojavlouncher.

### The log file and images/videos

Here is the log file 
[latestlog.txt](https://github.com/user-attachments/files/18271832/latestlog.txt)

### Steps To Reproduce

```markdown
First create a modpack profile and then enter it and then it will happen 1 of those problems that I said
```

### Expected Behavior

I expect it to work

### Platform

```markdown
- Device model: I dont know
- CPU architecture: I think it is arm64
- Android version: 14
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

No thats it

**Comment by GaucovyAero** [comment]
code 1 = mod incompatibility
crashes or the mojang screen or when joining world: out of memory or some mod is using shaders that gl4es cant handle

you gotta remove problematic mods, they are listed on the pojav wiki, keep in mind that not all of them are listed, so you might have to remove more depending on whats your issue

**Comment by Geourt7** [comment]
Thank you
