### ISSUE TITLE
[BUG] <Short description> SHOW RED SCREEN WHEN USE ANGEL RENDER I WANT HELP

### ISSUE THREAD

**Issue by Sksakibul786-pi** [PojavLauncherTeam/PojavLauncher#6425]
### Describe the bug

Red screen show when using angel render 
![Screenshot_2024-12-28-20-49-02-83_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/user-attachments/assets/9f157a0a-1568-468a-a4be-2c8b4c5765ae)

### The log file and images/videos

![Screenshot_2024-12-28-20-49-02-83_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/user-attachments/assets/f02de8be-02a4-4bbc-9457-53c555d15399)

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Select version 1.19.2 forge using angel render 
3. Play 
4. show red screen
```

### Expected Behavior

Working angel render 

### Platform

```markdown
- Device model: realme 11 
- CPU architecture: 64 | dimencity 6100+
- Android version: 14
- PojavLauncher version: latest
```

### Anything else?

I am used custom_env.txt not work so give other suggestions

**Comment by GaucovyAero** [comment]
cant reproduce, update pojav maybe or use gl4es

![Screenshot_20241230-103720_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/user-attachments/assets/ab3ef3a7-c30f-49d1-9cdb-538b69e31524)
