### ISSUE TITLE
[BUG] <Short description> help me fatal crash 1.21

### ISSUE THREAD

**Issue by wayxyz89** [PojavLauncherTeam/PojavLauncher#6426]
### Describe the bug

I join the world and fatal crash

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18273207/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.join world
3.crash
```

### Expected Behavior

-

### Platform

```markdown
- Device model:redmi 
- CPU architecture: 
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
fatal signal 6 just means that some mod is using custom shaders that gl4es cant handle

**Comment by wayxyz89** [comment]
> fatal signal 6 just means that some mod is using custom shaders that gl4es cant handle

Can you tell me what the mods are?
