### ISSUE TITLE
[F-Req] <Please Fix Zink Rendering>

### ISSUE THREAD

**Issue by Nekontod** [PojavLauncherTeam/PojavLauncher#6427]
### Is this request related to a bug?

Please fix zinc rendering 

So this is it. When I use the zinc render I experience a crash before entering the logo that says "Mojang Studios"
I can't take screenshots or videos because I deleted the latest version of Pojavlauncher first :( 

### Describe the request.

Please fix the zinc render so that it can be used on all cellphones, for example, my Mali G57, because most people experience crashes when they want to enter the game when using the zinc render. The problem is that I'm not the only one experiencing this, lots of people are experiencing it. 

### Anything else?

My phone now and this 2024 release

Infinix Smart 8
Ram 4/64
unisocT606
Mali g57
Android 13

Actually, my cellphone can use zinc, but the old zinc is Pojavlauncher zinc. For a long time, I didn't like the lines that appeared when using shaders. That's why I wanted to use it New Zink render but it's not working I hope you can fix it soon. Because I'm also building my Java shader in Pojav because I don't have Money to buy it My PC and laptop only rely on my cellphone

**Comment by Dilen0001** [comment]
.

**Comment by Nekontod** [comment]
Why?

**Comment by GaucovyAero** [comment]
try putting this into /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt

MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460

if that doesnt help, that just means that your gpu is not powerful enough to run it

**Comment by Dilen0001** [comment]
Why When I Run on version 1.12.2 doesn't work

**Comment by Nekontod** [comment]
> coba masukkan ini ke /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/custom_env.txt
> 
> PENGGANTIAN_VERSI_MESA_GL_=4.6 PENGGANTIAN_VERSI_MESA_GLSL_=460
> 
> jika itu tidak membantu, itu artinya GPU Anda tidak cukup kuat untuk menjalankannya

How do you install this?

**Comment by Nekontod** [comment]
@GaucovyAero I don't understand why the latest Zink doesn't work even though the old one only had a line bug when using the old Zink shader, it was very smooth for me to use, but the latest Zink doesn't support it?In fact, the Mesa 23 devel should function like it is not much different from the Mesa 21/22.
