### ISSUE TITLE
Optifine issue

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6429]
### Describe the bug

Bro can anyone explain how this happened, so I installed pojavlauncher in my mobile before 1 month and downloaded 1.21.3 version and used optifine but it was so laggy like fps were high but frames were dropping very frequently even with low settings, so I tried to install sodium, and It only got installed in 1.21 and less, so I installed it in 1.21 and started playing with 150 mods, it was smooth but it too had some frame drops but relatively so much less than optifine, so I started playing survival in pikanetwork server but as sodium isn't supported by pojavlauncher, my game used to crash every half an hour, I beared it but at a point I got so frustrated that I thought to bear the laggy optifine instead of crashy sodium, so I switched to optifine then joined the server and then suddenly I got shocked, literally optifine was running buttery smooth, way way better than sodium like no frame drops at all(very less) so I thought no way how can this happen I thought this could be server optimisation so I tried in single player and the results were same in single player too. So my question is how come this happened, the optifine which was very laggy before 1 month is now very smooth, way smoother than sodium without mods(cuz with mods sodium's performance dropped and one more thing I didn't even update optifine if you are thinking about that, I didn't update anything it's as it before 1 month and now).

### The log file and images/videos

This is not a bug or anything

### Steps To Reproduce

```markdown
I didn't do anything. I don't know how it happened.
```

### Expected Behavior

Solve my doubt how did this happen.

### Platform

```markdown
- Device model: Poco X6
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: playstore latest
```

**Comment by HACKradio** [comment]
Optifine has been bad for me for a while now, it seems to vary from release to release. If you get the LTW version from the actions page here https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/12079825845 you can use sodium all the way up to latest release.

**Comment by GaucovyAero** [comment]
- you might have changed some video settings, its okay
if you use forge, you might get a lot less fps (fabric and quilt dont slow the game down as much as forge)
if you use the optifine profile, some jvm arguments are added by default, that might also be helping you

- **recommended optifine settings for most performance are (video settings -> performance):**
ON: fast render, fast math, smart animations, lazy chunk loading
chunk updates 1, chunk builder threaded
everything else off
(try changing the dynamic updates option if you get frequent lagspikes)

- also you might have changed the ram allocation option, which can make a lot of difference in fps
lower ram allocation might get you a lot more fps compared to high ram allocation
(you gotta figure out what ram allocation for which modpack/mc version is the best for your phone)
