### ISSUE TITLE
[F-REQ] v2 UI

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#643]
I Want This Kind of UI!
THIS IS THE REAL v2 UI!
👇👇👇👇👇👇👇👇👇👇👇👇👇👇

![images](https://user-images.githubusercontent.com/75970303/104885826-a3f1b480-59a3-11eb-9b49-890ec62ea8cb.jpeg)

**Comment by khanhduytran0** [comment]
v3.3.1 implemented **partial**!

**Comment by LANCECRAFT1104** [comment]
What? Plz I want this kind of v2 UI

**Comment by LANCECRAFT1104** [comment]
I Want This UI on Next version

**Comment by Mathias-Boulay** [comment]
Using a layout as complex as the pc version creates problems for smaller screens.
*And this is without accounting for the increased RAM usage it would create*

**Comment by WesleyVanNeck** [comment]
> I Want This Kind of UI!
> THIS IS THE REAL v2 UI!
> 👇👇👇👇👇👇👇👇👇👇👇👇👇👇
> 
> ![images](https://user-images.githubusercontent.com/75970303/104885826-a3f1b480-59a3-11eb-9b49-890ec62ea8cb.jpeg)

Just God dam play on pc we can afford such gui without performance draw backs

**Comment by netkv** [comment]
just make background of that html news computer launcher's background

**Comment by khanhduytran0** [comment]
Html may slow at animation, all uses the interpreted js to anim things.

**Comment by netkv** [comment]
isnt that static image?
i mean that one with steve alex and broken lava in cave

**Comment by Mathias-Boulay** [comment]
> Isn't that static image?
> I mean that one with steve alex and broken lava in cave

It is, but there are a lot of *sub menus* within this interface that we have not.
An example being the profile tabs, with each profile having its own set of parameters

**Comment by netkv** [comment]
oh

**Comment by LANCECRAFT1104** [comment]
Okay

**Comment by LANCECRAFT1104** [comment]
If You Don't Want My v2 UI Request Just Change The Background of Development Console And Crash Log Page Like This.
👇👇👇👇👇👇👇👇👇👇👇👇👇
![images (1)](https://user-images.githubusercontent.com/75970303/104897076-e79fea80-59b2-11eb-9cdf-761eb040bcdf.jpeg)

I Don't Want A Black Background or Make Ligth Theme or Change The Background.

**Comment by LANCECRAFT1104** [comment]
> > I Want This Kind of UI!
> > THIS IS THE REAL v2 UI!
> > 👇👇👇👇👇👇👇👇👇👇👇👇👇👇
> > ![images](https://user-images.githubusercontent.com/75970303/104885826-a3f1b480-59a3-11eb-9b49-890ec62ea8cb.jpeg)
> 
> Just God dam play on pc we can afford such gui without performance draw backs

WE DON'T HAVE PC MEEEEEEN!!!!!!!!!!!!!

**Comment by ChargedHat42838** [comment]
Pojav team is working so hard to make us such a good launcher.
And you mean guy @LANCECRAFT1104 making silly request.!
Bruh don't you have a face

**Comment by netkv** [comment]
~~remove gui, return to commandline ncurses~~

**Comment by ChargedHat42838** [comment]
It's okay to request but u are meaneeee

**Comment by LANCECRAFT1104** [comment]
> just make background of that html news computer launcher's background

Yeah Just Make Background

**Comment by LANCECRAFT1104** [comment]
> Pojav team is working so hard to make us such a good launcher.
> And you mean guy @LANCECRAFT1104 making silly request.!
> Bruh don't you have a face

Just Change The Background Thats Only My Request Men!😞

**Comment by ghost** [comment]
> Just Change The Background Thats Only My Request Men!😞

Sorry 😢

**Comment by LANCECRAFT1104** [comment]
~~I Want This Kind of UI~~
__Or Just Change The Background Like This!
&H__
👇👇👇👇👇👇👇👇👇👇👇👇👇
![images (2)](https://user-images.githubusercontent.com/75970303/104903625-394c7300-59bb-11eb-9e6e-54614376167d.jpeg)

After That Then I Will Close My F-REQ.

**Comment by WesleyVanNeck** [comment]
> > Pojav team is working so hard to make us such a good launcher.
> > And you mean guy @LANCECRAFT1104 making silly request.!
> > Bruh don't you have a face
> 
> Just Change The Background Thats Only My Request Men!😞

No not rn

**Comment by LANCECRAFT1104** [comment]
> > > Pojav team is working so hard to make us such a good launcher.
> > > And you mean guy @LANCECRAFT1104 making silly request.!
> > > Bruh don't you have a face
> > 
> > 
> > Just Change The Background Thats Only My Request Men!😞
> 
> No not rn

Just say you don't want my request

__MY F-REQ CLOSED__

**Comment by WesleyVanNeck** [comment]
@LANCECRAFT1104  read my massage I say not rn as I don't have time for it

**Comment by WesleyVanNeck** [comment]
> > > > Pojav team is working so hard to make us such a good launcher.
> > > > And you mean guy @LANCECRAFT1104 making silly request.!
> > > > Bruh don't you have a face
> > > 
> > > 
> > > Just Change The Background Thats Only My Request Men!😞
> > 
> > 
> > No not rn
> 
> Just say you don't want my request
> 
> **MY F-REQ CLOSED**

Don't be toxic to me as am revamping it soon I will work on you request soon I got also a job this is not my job coding stuff for pojav

**Comment by Mathias-Boulay** [comment]
Such an UI isn't on the roadmap and no need for kids whishing their phone is a pc.
*Although PR improving it are always welcome*
Closing the issue.
