### ISSUE TITLE
My game doesn't see some mods on version 1.21.1 forge

### ISSUE THREAD

**Issue by Its-porodx** [PojavLauncherTeam/PojavLauncher#6431]
### Is this request related to a bug?

This is either a bug in Forge or the launcher itself.

### Describe the request.

I add mods to the mods folder but out of about 50 mods it only makes/downloads 24 mods

### Anything else?

Please help me solve this (and by the way, what should I do if I don't receive messages from GitHub?)

**Comment by Its-porodx** [comment]
I would be very grateful if you could tell me how to fix this.

**Comment by Its-porodx** [comment]
I would be very grateful for your help if you tell me how to fix it.

**Comment by GaucovyAero** [comment]
move the files with files by marc from play store, you might be getting a permission denied error

**Comment by Its-porodx** [comment]
> move the files with files by marc from play store, you might be getting a permission denied error

Sorry, I didn't quite understand what to do, can you write in more detail?
