### ISSUE TITLE
[BUG] Minecraft 1.5.2 and below are not working

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#647]
**Describe the bug**
Minecraft 1.5.2 and below are not working :(

**To Reproduce**
1. Start PojavLauncher
2. Install Minecraft 1.5.2
3. Enjoy an endless gray screen!
...
**Platform:**
 - Device Model: Moto G6 play
 - CPU architecture: aarch32
 - Android Version: 9

**Comment by OksmaWarez** [comment]
Pojavlauncher Version?

**Comment by MateusL13** [comment]
> Pojavlauncher Version?

3.3.1

**Comment by khanhduytran0** [comment]
What about log?

**Comment by MateusL13** [comment]
> What about log?

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5832584/latestlog.txt)

**Comment by khanhduytran0** [comment]
Unfortunately, aarch32 is unsupported to run 1.5.2 and below...

**Comment by MateusL13** [comment]
> Unfortunately, aarch32 is unsupported to run 1.5.2 and below...

ok, thank you, anyway :)

**Comment by MateusL13** [comment]
> Unfortunately, aarch32 is unsupported to run 1.5.2 and below...

Do you know why the bottom left corner is more "visible" than the rest?
![Screenshot_20210118-193954~2](https://user-images.githubusercontent.com/38146322/104968751-7b7ab200-59c5-11eb-9921-0d0b4e3ef33e.png)

**Comment by khanhduytran0** [comment]
I don't know, but I think it's GL4ES bug.

**Comment by MateusL13** [comment]
> I don't know, but I think it's GL4ES bug.

Ok, thank you :D
