### ISSUE TITLE
[BUG] Incoherent scroll behavior across versions

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#648]
**Describe the bug**
Scroll wheel up and down not working

**To Reproduce**
1. Start PojavLauncher
2. Make a custom layout with scrollwheel up or down
3. Start any Minecraft version

**Expected behavior**
I expected the scroll wheel buttons to work

**Screenshots**
![Screenshot_2021-01-18-20-29-55-584_net kdt pojavlaunch](https://user-images.githubusercontent.com/73366837/104960432-1bd3d500-59cc-11eb-8bfc-7523b5e7e8d7.jpg)

**Platform:**
 - Device Model
Xiaomi redmi note 9
 - CPU architecture [e.g. aarch64] 
 - aarch64
 - Android Version [e.g. 10]
 - 10

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
You need move the mouse pointer to scrollable part.

**Comment by ghost** [comment]
> You need move the mouse pointer to scrollable part.

Oh uh wait a minute

**Comment by ghost** [comment]
![Screenshot_2021-01-18-22-27-54-440_net kdt pojavlaunch](https://user-images.githubusercontent.com/73366837/104968163-0024fa80-59dd-11eb-90ce-54fc35762b11.jpg)

**Comment by khanhduytran0** [comment]
So you held scroll up or down?

**Comment by ghost** [comment]
Scroll up

**Comment by khanhduytran0** [comment]
Press scroll up when page is at top?

**Comment by ghost** [comment]
Wait I meant scroll down, it has no effect in game or in settings or creative menu

**Comment by khanhduytran0** [comment]
But why on screenshot likely held scroll up? Did you set scroll key codes?

**Comment by ghost** [comment]
Yeah

**Comment by ghost** [comment]
Actually the button i pressed on that screenshot was labeled scrolldown and it used SPECIAL_SCROLLDOWN

**Comment by LANCECRAFT1104** [comment]
**The Scroll Buttons is USELESS on some MC versions Like version 1.16.5.**

**Comment by khanhduytran0** [comment]
> **The Scroll Buttons is USELESS on some MC versions Like version 1.16.5.**

Ah yeah, on 1.15+ scrolling is done by Arrow up and Arrow down.

**Comment by ghost** [comment]
> **The Scroll Buttons is USELESS on some MC versions Like version 1.16.5.**

I'm using a mod called create and one of its features requires scrollwheel

**Comment by LANCECRAFT1104** [comment]
> **Describe the bug**
> Scroll wheel up and down not working
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Start PojavLauncher
> 2. Make a custom layout with scrollwheel up or down
> 3. Start any Minecraft version
> 
> **Expected behavior**
> I expected the scroll wheel buttons to work
> 
> **Screenshots**
> ![Screenshot_2021-01-18-20-29-55-584_net kdt pojavlaunch](https://user-images.githubusercontent.com/73366837/104960432-1bd3d500-59cc-11eb-8bfc-7523b5e7e8d7.jpg)
> 
> **Platform:**
> 
> * Device Model
>   Xiaomi redmi note 9
> * CPU architecture [e.g. aarch64]
> * aarch64
> * Android Version [e.g. 10]
> * 10
> 
> Additional context

What ui is that I like that kind of ui?

**Comment by WesleyVanNeck** [comment]
> > **Describe the bug**
> > Scroll wheel up and down not working
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Start PojavLauncher
> > 2. Make a custom layout with scrollwheel up or down
> > 3. Start any Minecraft version
> > 
> > **Expected behavior**
> > I expected the scroll wheel buttons to work
> > **Screenshots**
> > ![Screenshot_2021-01-18-20-29-55-584_net kdt pojavlaunch](https://user-images.githubusercontent.com/73366837/104960432-1bd3d500-59cc-11eb-8bfc-7523b5e7e8d7.jpg)
> > **Platform:**
> > 
> > * Device Model
> >   Xiaomi redmi note 9
> > * CPU architecture [e.g. aarch64]
> > * aarch64
> > * Android Version [e.g. 10]
> > * 10
> > 
> > Additional context
> 
> What ui is that I like that kind of ui?

to many items a forge mod

**Comment by Mathias-Boulay** [comment]
I finally fixed this fucker with Control Revision 2.5

**Comment by Mathias-Boulay** [comment]
#2211
