### ISSUE TITLE
[BUG] ACCOUNT!!!

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#649]
![Screenshot_2021-01-19-09-28-41-80](https://user-images.githubusercontent.com/75970303/104976764-f204c780-5a38-11eb-94f9-d6dadf7cfc1d.png)
CAN'T SIGN IN!

**Comment by WesleyVanNeck** [comment]
Dublicated

**Comment by khanhduytran0** [comment]
**@LANCECRAFT1104** buy Minecraft to continue!
