### ISSUE TITLE
Is it possible for versions higher than 1.11 to work?

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#65]
Is it possible for versions higher than 1.11 to work?
For example: 1.13 and 1.15

What is the problem that these versions do not start?

It will be fixed or not?

And what about OpenGL 2.0?

(OpenGL 2.0 says: Omae wa mou Shindeiru)

**Comment by khanhduytran0** [comment]
1.12.x can be run with a condition: the launcher must be compiled with Java8, might *break backwards compatible*.
1.13 and above requires LWJGL 3 which not included in the launcher.

**Comment by pedrosouzabrasil** [comment]
Hi !I have tested boardwalk 2 and only blackscreen...any news..?my device..note 10 android 10..

**Comment by pedrosouzabrasil** [comment]
@khanhduytran0

**Comment by khanhduytran0** [comment]
Get the log at /sdcard/boardwalk/log.txt

**Comment by pedrosouzabrasil** [comment]
The log is empty. I have tested version 1.15.2 and 1.14.2...unfortunely freezes my device.

**Comment by pedrosouzabrasil** [comment]
I will wait for new versions of the pojavlauncher to test...thank you .

**Comment by khanhduytran0** [comment]
V2 is impossible.
