### ISSUE TITLE
[BUG] I can't use the space key to jump.

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#650]
**Describe the bug**
I don't know if it's a bug, but when I try to jump using the space key nothing happens. (When I use another key, like V for example, it's possible to jump)

**To Reproduce**
1. Start PojavLauncher
2. Enter in the game, in a world (using mouse and keyboard)
3. And the bug happens!

**Expected behavior**
I think it should be possible to jump using space Key.

**Platform:**
 - Device Model: Moto G6 play
 - CPU architecture: aarch32
 - Android Version: 9

**Comment by artdeell** [comment]
Known issue for <1.13 versions

**Comment by MateusL13** [comment]
> Known issue for <1.13 versions

Ok, thanks, when fixed, I'll close this.

**Comment by Dimon245** [comment]
Yeah, I also mentioned it in [my issue](https://github.com/PojavLauncherTeam/PojavLauncher/issues/576)

**Comment by MateusL13** [comment]
](url)

**Comment by MateusL13** [comment]
Fixed

**Comment by dhairya597** [comment]
Hi guys I don't know how to use this app but pls tell me in the comments how do I fix my space bar in pojav launcher pls

**Comment by GaucovyAero** [comment]
> Hi guys I don't know how to use this app but pls tell me in the comments how do I fix my space bar in pojav launcher pls

make sure you are using the latest play store version
