### ISSUE TITLE
[BUG]The custom key function is not available 

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#651]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Template isn't filled. Tagging with "invalid"

**Comment by artdeell** [comment]
Waiting for a proper fill.
