### ISSUE TITLE
[BUG]Key failure 

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#652]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Describe it more concisely. Cannot fix something without morre info.

**Comment by T-CATHOME** [comment]
@artdeell Some of the virtual buttons in the game are out of order example, "Gui

**Comment by artdeell** [comment]
Send the screenshot

**Comment by tttghkg** [comment]
@artdeell 
![Uploading IMG_20210119_234502.jpg…]()

**Comment by tttghkg** [comment]
@artdeell 
![Uploading IMG_20210119_234502.jpg…]()

**Comment by T-CATHOME** [comment]
@artdeell 
![Uploading IMG_20210119_234502.jpg…]()

**Comment by artdeell** [comment]
it didn;t upload

**Comment by T-CATHOME** [comment]
@artdeell My network is not good and I can't send it

**Comment by T-CATHOME** [comment]
@artdeell 
![Uploading IMG_20210119_234502.jpg…]()

**Comment by GxmerSam** [comment]
switch to different network

**Comment by artdeell** [comment]
Can you upload it on Google Drive?

**Comment by T-CATHOME** [comment]
@artdeell I can't. mouse, koyboabd, gui, pri, sec,It's not working

**Comment by Zeyrox1090** [comment]
lol
maybe delete default and make a new default lol

**Comment by T-CATHOME** [comment]
@zeyrox1090 The custom key function is not available

**Comment by khanhduytran0** [comment]
@tttghkg **why you open too many duplicate issues??????**

**Comment by Mathias-Boulay** [comment]
Stale issue from an old launcher version, invalid bug reporting anyway.
Closing.
