### ISSUE TITLE
v3.3.1 [bug] old MC versions (all below release 1.6.1) Screen resolution

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [PojavLauncherTeam/PojavLauncher#653]
When you run versions below release 1.6.1 (checked on the phone xiaomi redmi Note 8 pro) Your game screen resolution is much less than the maximum

**Comment by MrMasrozYTLIVE** [comment]
![Screenshot_2021-01-19-23-52-01-480_net kdt pojavlaunch](https://user-images.githubusercontent.com/61359286/105092170-f7522880-5ab1-11eb-9c18-e08381fafaeb.jpg)
Release 1.6.1 and above

**Comment by MrMasrozYTLIVE** [comment]
![Screenshot_2021-01-19-23-51-34-177_net kdt pojavlaunch](https://user-images.githubusercontent.com/61359286/105092211-0507ae00-5ab2-11eb-90db-ca767cdd17f1.jpg)
Release 1.5.2 and below

**Comment by Google61** [comment]
Swipe from right side of the screen and choose "Send custom custom keycode", choose F11

Свайп с правого края экрана, выбери "Отправить", выбери F11

**Comment by artdeell** [comment]
That's the specifics of those old versions. Add the f11 key on your keymap
and press it after starting

вт, 19 янв. 2021 г., 23:57 Andrey (MiTask) <notifications@github.com>:
