### ISSUE TITLE
[BUG] string init Android CI #1837

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#654]
@khanhduytran0 I try Your [MSA] string init
Android CI #1837 I Can't Edit Controls Why?

**Comment by WesleyVanNeck** [comment]
Works fine I can edit controls

**Comment by artdeell** [comment]
disable "Dynamic coordinates" in button options

ср, 20 янв. 2021 г., 10:00 LancEYTStudioZ <notifications@github.com>:
