### ISSUE TITLE
[BUG] The function of the custom control key is invalid ，

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#656]

**Comment by khanhduytran0** [comment]
Duplicate #655

**Comment by LANCECRAFT1104** [comment]
Same issue? Where's the update?

**Comment by khanhduytran0** [comment]
> Same issue? Where's the update?

If you know an update? Go and fix. We don't even know yet.

**Comment by T-CATHOME** [comment]
@khanhduytran0 This bug hasn't been fixed yet

**Comment by khanhduytran0** [comment]
@tttghkg https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/498877588

**Comment by khanhduytran0** [comment]
Fixed https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/500531454

**Comment by LANCECRAFT1104** [comment]
> Fixed https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/500531454

Thank you.
Keep the good work👍👍👍
