### ISSUE TITLE
[BUG] Mouse Not Working

### ISSUE THREAD

**Issue by AliMaazKhan** [PojavLauncherTeam/PojavLauncher#658]
In version 3.3 which is the latest version the virtual mouse is not working and when we try to login in with Microsoft account it says error cant login and the version is nice please find out the problem of the courser (mouse) which is the main problem please do fast thanks for making such nice project

Device:- Samsung J2 core 
Architecture :- arm32

**Comment by artdeell** [comment]
3.3 is old
use 3.3.1
