### ISSUE TITLE
[F-REQ] Please read :)

### ISSUE THREAD

**Issue by Leproromanianman** [PojavLauncherTeam/PojavLauncher#659]
Hello there !!

I really appreciate this minecraft java edition boardwalk launcher ! 

The problem what I want to say is to laggy , I tried MCinabox and it work very well , actually in MCinabox in mc 1.16.5 has 40 fps and you're launcher I have 6 . The think is Pojavlauncher is more complex and more good graphics than MCinabox. 

A clear and concise description of what you want to happen is to optimize the java virtual machine
(I think it's named) or just minecraft to run more better.      One think is I changed in pojav in minecraft the graphics to low and it works bad.

I love you're launcher than other !!!!!!!!! :) Thank you very much if you read my comment :)

**Comment by khanhduytran0** [comment]
- Check JRE version. If it's 9 then it's definitely slow. Use JRE8 for smoother.
- Update to v3.3.1.

**Comment by Leproromanianman** [comment]
> * Check JRE version. If it's 9 then it's definitely slow. Use JRE8 for smoother.
> * Update to v3.3.1.

1I don't know how to see what java has /2I have the v3.3.1

**Comment by Leproromanianman** [comment]
I just found I used all the time Java 9 arm64 !!! LoL I have the java 8 arm , but I have this java from you.

**Comment by khanhduytran0** [comment]
JRE9 is very^10 slow. If your device is 64bit, get 70 mb apk, JRE8 will be auto installed https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/498877588

**Comment by Leproromanianman** [comment]
What means : game exited ? It say that every time and it bring me back to play

**Comment by Leproromanianman** [comment]
This app from this link has a lot of bugs .. https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/498877588. I installed manually java version , AND YES!!! IT WORKS GOOD . THANK YOU HELPED ME !

**Comment by khanhduytran0** [comment]
> a lot of bugs

Maybe try this build? https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/501176591
