### ISSUE TITLE
[BUG]CANT USE TYPE OF THOSE BUTTON

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#660]
I dont know why but everytime I tried to tap type of button like mouse or try to use my keyboard. It did not work... It only give me this

![Screenshot_20210121_091302.jpg](https://user-images.githubusercontent.com/76242887/105260734-4b036580-5bc9-11eb-91fd-634e05a51b34.jpg)

The button like mouse pri sec working but it keep active for a second after I tap it one time.. Like when I tried to remove block so I will tap on pri button and keep removing all the block for a second or I try to place block and I will tap sec button and it keep placing block for a second non stop..

**Platform:**
 - Device Model [Vivo y17 4/64]
 - CPU architecture [aarch64] 
 - Android Version [9]

**Comment by khanhduytran0** [comment]
Duplicate #655!

**Comment by khanhduytran0** [comment]
Disable toggleable

**Comment by khanhduytran0** [comment]
Also, get https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/498877588

**Comment by Adam0530** [comment]
> Disable toggleable

I am already disable toggleable and I am not using toggleable on any of those button that did not work

**Comment by Adam0530** [comment]
> Also, get https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/498877588

I am on this version.. It still did not work

**Comment by Adam0530** [comment]
The other except for those button that has been highlights work really well

**Comment by khanhduytran0** [comment]
Fixed https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/500531454
