### ISSUE TITLE
[BUG]Hello, I have some problems. In your software, because I accidentally deleted the game folder but I downloaded the game again, but the version of my game was the deleted version, and he suddenly crashed and was not deleted. It was normal before, so please fix this error, and hope you add some buttons because of the achievements in the game, I can't move

### ISSUE THREAD

**Issue by West68** [PojavLauncherTeam/PojavLauncher#661]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Zeyrox1090** [comment]
delete pojav launcher folder?
or clear app data?
idk
lol

**Comment by khanhduytran0** [comment]
@jjiibb also the title is not place to write long text.

**Comment by West68** [comment]
I'm a newcomer and I don't know how to use it, so can you solve the problem I said

**Comment by jjiibb** [comment]
Uploading lv_0_20210121194622.mp4…

You see, this is 1.16.5. It was good before deleting the folder, and then it became like this

**Comment by khanhduytran0** [comment]
> crashed

Any log available?

> hope you add some buttons

You can add for yourself. Go to custom controls.

**Comment by West68** [comment]
No, because now he crashed as soon as I entered, and there was no time to check the log. By the way, I downloaded a 1 12 2 version of Forge, but he couldn’t let me play. After he displayed an instruction, click OK to exit Up

**Comment by West68** [comment]
Besides, I have downloaded 1.16.5, 1.12forge, and 11.2forge, as well as the latest snapshot 21w03a, currently only 1.15. 2forge and 21w03a can be used normally, others are not working, and other versions under me cannot be used .

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by West68** [comment]
[Uploading latestlog.txt…]()

**Comment by West68** [comment]
https://www.mediafire.com/file/c78php88ec4iqum/latestlog.txt/file

**Comment by West68** [comment]
Just this, I hope you can find out the mistakes of this game for me, thank you

**Comment by khanhduytran0** [comment]
It's likely that you set too much RAM for game.

**Comment by khanhduytran0** [comment]
> [Uploading latestlog.txt…]()

What you got is incomplete upload. Then why mediafire? Be patience.

**Comment by jjiibb** [comment]
No, no, it's not like that, I tried it again, no matter how I clicked 1.16.5, I always advance and retreat at one point, and the memory is also set too large. I set it to 4096 before I did not delete the folder. It starts normally, but now, I changed it to 1024, but it can’t be opened. What is the problem? Is it a problem with the phone or the launcher?

**Comment by West68** [comment]
No, no, it's not like that, I tried it again, no matter how I clicked 1.16.5, I always advance and retreat at one point, and the memory is not set too large. I used to set 4096 before I deleted the folder. It can start normally, but now, I changed it to 1024 but it can't be opened. What is the problem? Is it a problem with the phone or the launcher?

**Comment by khanhduytran0** [comment]
Where you set is Xmx or Xms? Or both?

**Comment by West68** [comment]
But I think it’s the launcher, not the phone, because it can be launched before, but this time it won’t.

**Comment by West68** [comment]
What is xmx, can you tell me, only if I know what it is, I know where to find it, or is it a folder?

**Comment by West68** [comment]
If it is the file path, it is /storage/emulated/0/games/PojavLauncher/.minecraft/

**Comment by jjiibb** [comment]
To be honest, I hope you can solve this problem for me as soon as possible, because I can't always stay in 1.15.2forge to play, I wish the latest version at night.

**Comment by West68** [comment]
To be honest, I hope you can solve this problem for me quickly, because I can't stay in 1.15.2forge to play, how I want to play the latest official version.

**Comment by West68** [comment]
Can you help me fix this bug? I have placed a 1.16.5 fabric again. It was normal after opening it anyway. After I selected the module, I went in and then flashed back. After restarting the software, it still flashed back. Can you? Help me fix this bug

**Comment by matt995** [comment]
Update the launcher as i had this issue before and got it fixed

**Comment by Mathias-Boulay** [comment]
Stale issue from an old pojav version.
*Also just delete the PojavLauncher folder and restart installing from scratch.*
Closing.

**Comment by Swarajranjandeo** [comment]
you fix this problem in my offline account swaraj_gamer1 this is my account and fix the problem is trying to rest your game and the launcher I am reat my launcher and game but not fix
