### ISSUE TITLE
[F-REQ]Add the ability to remove game versions

### ISSUE THREAD

**Issue by West68** [PojavLauncherTeam/PojavLauncher#662]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
Delete a version will also need to delete it's libraries, but other versions may depends on them. So if delete, user have to redownload them. So if user use mobile data or offline?

**Comment by West68** [comment]
Hello. I’m not using mobile data or offline. I’m using WiFi

**Comment by West68** [comment]
What I want to delete is the version

**Comment by Mathias-Boulay** [comment]
Renaming the issue since we have an integrated runtime now.

**Comment by SprainedSpark89** [comment]
go to pojavlauncher's folder then i think then .minecraft (it has been a long time) then versions then delete the folder you want

**Comment by GaucovyAero** [comment]
this is not possible even on PC launchers

**Comment by TheOneAndOnly-Loup** [comment]
> this is not possible even on PC launchers

That's not true! You can delete snapshots and releases from the Minecraft launcher.
