### ISSUE TITLE
[BUG] Copy paste not working.

### ISSUE THREAD

**Issue by cmy2008** [PojavLauncherTeam/PojavLauncher#663]
**Describe the bug**
USB mouse and keyboard are connected, the right mouse button and the middle mouse button do not work, after ctrl + a and ctrl + v stuck.

**To Reproduce**
1. Start PojavLauncher
2. Run 21w03a
3. connect mouse and keyboard

**Expected behavior**
I expected ... fix this bug 

**Screenshots**
Nothing
**Platform:**
 - Device Model HUAWEI AGS2-W09 (Very old Android Tablet)
 - CPU architecture aarch64 
 - Android Version 9

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
CTRL + V stuck may be a system problem, there is no problem with the log.
</pre>
</details>

**Comment by jjiibb** [comment]
Uploading lv_0_20210121194622.mp4…

You see, this is 1.16.5. It was good before deleting the folder, and then it became like this

**Comment by khanhduytran0** [comment]
> ctrl + v

Currently, copy or paste will crash the game.

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build build
