### ISSUE TITLE
Will I get banned on hypixel for using pojav launcher??

### ISSUE THREAD

**Issue by bubbelbadHD** [PojavLauncherTeam/PojavLauncher#665]
Recently my pc broke so I havey mobile. I searched and fount pojav launcher. Now If I play hypixel on it can I get banned?

**Comment by khanhduytran0** [comment]
This launcher runs vanilla Minecraft, so there will be no reason for Hypixel to ban you.

**Comment by bubbelbadHD** [comment]
Ok thanks khanhduytran0

> This launcher runs vanilla Minecraft, so there will be no reason for Hypixel to ban you.

**Comment by bubbelbadHD** [comment]
No it is not stable when I play bedwars it crashes

**Comment by SafeData5479854** [comment]
I created an online account for pojavlauncher, but I was banned without entering hypixel, what should I do?

**Comment by stacode123** [comment]
security ban u had vpn or proxy.
u could also get hacked

**Comment by bubbelbadHD** [comment]
> I created an online account for pojavlauncher, but I was banned without entering hypixel, what should I do?

Idk why this happened with you but mine was working perfectly fine. It maybe error of packets or proxy or your account was hacked. Try changing the password

**Comment by Mathias-Boulay** [comment]
Question answered, closing the issue.
It's not like people were asking for it once a month in the discord anyway.
