### ISSUE TITLE
Latest Build doesn't work at all. 

### ISSUE THREAD

**Issue by Accountuser99** [PojavLauncherTeam/PojavLauncher#666]
Ever since  you added all of those new options and settings the game cant launch and fails to even get to the Mojang splash screen

**To Reproduce**
1. Start PojavLauncher
2.Launch any version of Minecraft
3.wait 10 to 15 seconds 
4.Game fails to launch and crashes

**Expected behavior**
I expected the game to launch 

**Screenshots**

**Platform:**
 - Device Model [Huawei Y7 2019]
 - CPU architecture [aarch64] 
 - Android Version [MIUI android 8.1.0]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
> I expected the game to launch

Go back to release or suggested build.

**Comment by Accountuser99** [comment]
![Screenshot_20210121-125126](https://user-images.githubusercontent.com/75422794/105353752-8c0a7280-5be7-11eb-8452-b6c4ad37bfcb.jpg)

**Comment by khanhduytran0** [comment]
> Go back to release or suggested build.

Or go back to latest build today.
