### ISSUE TITLE
[BUG] Are Dev Build Working???

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#667]
I Run A Forge With The Latest Dev Build

https://user-images.githubusercontent.com/75970303/105366550-707c8780-5c3a-11eb-9562-151a2fd15108.mp4

What happened on dev build
1st Can't Move and Edit My Controls
2nd Can't Run Forge and Unforge Versions

What is the best dev build or lates release/pre-release??? Huh?

**Comment by WesleyVanNeck** [comment]
stop  spaming the issue tracker dev builds are poeple that are msart anough like devs or people living on cutting edge software and know what they do

**Comment by WesleyVanNeck** [comment]
ask the qeaustions in our discord https://discord.gg/zSyttAMp
