### ISSUE TITLE
[BUG] oi eu tenho um Android 10  celular de 32 bits  A10 gosto muito mas tem um bug quando eu ativo o freeform e eu aperta em jogar aparece uma tela pequena aí quando eu coloco na tela cheia o pojav crasha e os botões fica desorganizado e bagunçados 

### ISSUE THREAD

**Issue by DeltXDev** [PojavLauncherTeam/PojavLauncher#670]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Zeyrox1090** [comment]
english:hi i have an android 10 cell phone 32 bits A10 i like a lot but there is a bug when i activate freeform and i press play a small screen appears there when i put the pojav crasha on the full screen and the buttons are disorganized and messy

**Comment by zeyrox1090** [comment]
idk lol

**Comment by khanhduytran0** [comment]
Disable freeform mode.
