### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by DirectiveTaurus** [PojavLauncherTeam/PojavLauncher#671]
The mouse sec are not working cause my phone can't beike that okay it's not a bug cause it's my phone can you do something that the mouse pointer can be linked to the virtual mouse ? Soo we can have sec button for most of the devices

**Comment by khanhduytran0** [comment]
Use latest build.

**Comment by khanhduytran0** [comment]
Hey. Does it work yet?

**Comment by khanhduytran0** [comment]
So, you are only report issues but does not take care of older issues. Closing. If still bug, reopen.
