### ISSUE TITLE
[BUG] 1.12.2 Mouse Problem🖱️🖱️🖱️

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#676]
**Describe the bug**
The mouse problem on 1.12.2

**To Reproduce**
1. Start PojavLauncher
2. Open Inventory
3. Mouse Problem
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [OPPO A12e/OPPO A3s]
 - CPU architecture [aarch64/32] 
 - Android Version [8.1.0]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by mglovers123** [comment]
Your mouse problem XD

**Comment by AliMaazKhan** [comment]
Yes in my also mouse in not working

**Comment by LANCECRAFT1104** [comment]
Scroll Down/Up NOT WORKING ON MY VERSION!!!!😤 1.16.2, 1.16.3, 1.16.4, 1.16.5

**Comment by Mathias-Boulay** [comment]
The base issue is gone, and the current one is a duplicate from #648
closing the issue.
