### ISSUE TITLE
1.13.2及以上版本的模拟按键鼠标滚轮无法使用

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#678]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by CosineMath** [comment]
我觉得你应该用英文提问（逃

**Comment by artdeell** [comment]
known issue with scroll wheel

**Comment by Mathias-Boulay** [comment]
duplicate from #648 
Closing issue.
