### ISSUE TITLE
IOS version

### ISSUE THREAD

**Issue by pedrosouzabrasil** [PojavLauncherTeam/PojavLauncher#68]
There are some ios emulators for pc...maybe you can try something in the future.https://techonation.com/best-ios-emulators-for-windows-run-ios-apps/

**Comment by khanhduytran0** [comment]
My family has some iPhone devices that I can test with these so I don't need to emulate iOS. A Mac OSX operating system is required to develop iOS app.

**Comment by pedrosouzabrasil** [comment]
Ok..!

**Comment by khanhduytran0** [comment]
Also there's no official way to run iOS natively in Windows ~~expect~~ unless run a Mac OSX virtual machine then install XCode and launch the simulator on it.

**Comment by pedrosouzabrasil** [comment]
Understand...

**Comment by khanhduytran0** [comment]
I have a wrong word.

**Comment by artdeell** [comment]
As soon as we have an LWJGL version that doesn't require X11 libs, we can run it ANYWHERE where OpenGL is supported. Hm, that's an idea: what about a Minecraft launcher for MS-DOS PCs which will look like 3D Shareware snapshot. :)

**Comment by khanhduytran0** [comment]
Already Boardwalk's version disabled X11 symbols.

**Comment by khanhduytran0** [comment]
https://github.com/darlinghq/darling
Found an interesting solution.

Windows WSL -> Linux -> Darling -> XCode

**Comment by khanhduytran0** [comment]
Darling may work in WSL 2 or I will try in chroot Linux Deploy in Android-x86 (still a bit lazy to install triple-boot Ubuntu or something more).

**Comment by khanhduytran0** [comment]
But how will I create a RoboVM project...

**Comment by khanhduytran0** [comment]
This is impossible unless I put anything like libraries and client into a RoboVM project. This violate Minecraft EULA.
