### ISSUE TITLE
[F-REQ]Missing Icon

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#682]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. The Auto RAM Icon

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add Auto RAM Icon

**Describe alternatives you've considered**

**Additional context**
![Screenshot_2021-01-23-15-55-36-06](https://user-images.githubusercontent.com/75970303/105572801-5eaef780-5d94-11eb-874d-8b1d5c9be8a6.png)

![images](https://user-images.githubusercontent.com/75970303/105572817-6e2e4080-5d94-11eb-8d32-80e3deea8dde.png)

**Comment by khanhduytran0** [comment]
It looks incompatible with launcher current theme (it's dark theme currently).

**Comment by LANCECRAFT1104** [comment]
Add Missing Icon "Auto RAM" Like This
![images](https://user-images.githubusercontent.com/75970303/105572854-9cac1b80-5d94-11eb-93e6-e601615651d0.png)
Is this helpful???

**Comment by LANCECRAFT1104** [comment]
> It looks incompatible with launcher current theme (it's dark theme currently).

Ah okay

**Comment by khanhduytran0** [comment]
If background is transparent, a quick fix would be reversing color.

**Comment by LANCECRAFT1104** [comment]
And this one i forgot XD
![Screenshot_2021-01-23-16-12-04-76](https://user-images.githubusercontent.com/75970303/105573065-e47f7280-5d95-11eb-8e73-8eaaf1e6aed8.png)
Resolution Decrease Ratio Icon

**Comment by khanhduytran0** [comment]
Suggested already![image](https://user-images.githubusercontent.com/40482367/105573143-0543ca00-5d8e-11eb-9cbc-9db018d8906b.png)

**Comment by Zeyrox1090** [comment]
ehhh lol i thought you didn't see it

**Comment by Zeyrox1090** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. The Auto RAM Icon
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen. Add Auto RAM Icon
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> ![Screenshot_2021-01-23-15-55-36-06](https://user-images.githubusercontent.com/75970303/105572801-5eaef780-5d94-11eb-874d-8b1d5c9be8a6.png)
> 
> ![images](https://user-images.githubusercontent.com/75970303/105572817-6e2e4080-5d94-11eb-8d32-80e3deea8dde.png)

how about this?
![20210124_220404](https://user-images.githubusercontent.com/73925046/105634247-137e0d00-5e98-11eb-836e-e7b1ec981961.png)

**Comment by Zeyrox1090** [comment]
lol

**Comment by Zeyrox1090** [comment]
lol

**Comment by Mathias-Boulay** [comment]
ram settings now have an icon, closing the issue.
although the icon was pretty user friendly.

Such issues would be better suited as PR though.
