### ISSUE TITLE
HQM mod The text in the task book will become garbled 

### ISSUE THREAD

**Issue by T-CATHOME** [PojavLauncherTeam/PojavLauncher#683]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Please fill the template!

**Comment by T-CATHOME** [comment]
@khanhduytran0 I don't know what to fill in because it seems to be a coding error

**Comment by KorewaLidesu** [comment]
No log available to debug the issue.
Please upload log and things that related to this.
Also try fill the template fully if you want to report this as bug.

**Comment by Mathias-Boulay** [comment]
Stale issue which is most likely due to a lack of VRAM in the device.
Cannot really be fixed by us.
Closing the issue.
