### ISSUE TITLE
[BU1.16.4 unable to detect mod after forge installationG]

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#684]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
i will set invalid plz full the template

**Comment by WesleyVanNeck** [comment]
No response in phew hours
