### ISSUE TITLE
A strange bug

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#685]
When I'm in a world, sometimes the software crashes unexpectedly and doesn't generate a crash-report, and every minecraft version does.

**Comment by khanhduytran0** [comment]
This could be caused by out of memory, when you set maximum RAM more than free RAM.

**Comment by yejunjie10311031** [comment]
I don't think it's a problem with running memory，because I have more than 3GB running memory free,But Pojavlancher only takes up 800 MB of running memory.

**Comment by yejunjie10311031** [comment]
Although it doesn't crash very often, it affects my game experience

**Comment by artdeell** [comment]
Can you send the latestlog.txt from the .minecraft folder? (When the game crashes)

**Comment by yejunjie10311031** [comment]
I checked the latestlog.txt and It ends with "---- beginning of system", but sometimes it doesn't.

**Comment by KorewaLidesu** [comment]
Uncheck auto ram and change on your owns.
Also, did your OS report back about Pojav's crash?

**Comment by KorewaLidesu** [comment]
Also, did your OS report back about app crash?

**Comment by yejunjie10311031** [comment]
I did turn off auto ram and set the running memory to "- xms768m - xmx800m"

**Comment by KorewaLidesu** [comment]
There is no space between - and keyword
Normally should be -Xms768M -Xmx800M

**Comment by yejunjie10311031** [comment]
But my OS never report back any crash when a software crashs.

**Comment by yejunjie10311031** [comment]
@KorewaLidesu ,This is not the problem. The running memory I set in pojavlauncher is -Xms768M -Xmx800M

**Comment by KorewaLidesu** [comment]
Try run without augment.

**Comment by yejunjie10311031** [comment]
@KorewaLidesu  @khanhduytran0 @artdeell ,I guess this may be the background scheduling problem of my system? When pojavlauncher runs, there are two windows, one is the launcher itself, and the other is the game window. When it launches minecraft, it is on the game window. The window of the launcher is hung in the background of the system, while my mobile phone is the Emui system, which will limit the running memory of the background application.

**Comment by khanhduytran0** [comment]
> there are two windows

This is normal, as we intended to make the launcher can run multiple versions (but can't).

**Comment by yejunjie10311031** [comment]
I found that latestlog.txt There is "Can't keep up! Did the system time change, or is the server overloaded? Running 2482ms behind, skipping 49 tick(s)" in the text, does it cause the software crash?

**Comment by khanhduytran0** [comment]
No. It's just lag from server side, when local server processing huge things (such as load chunks).

**Comment by yejunjie10311031** [comment]
Now I feel very strange about this crash problem, because sometimes even if I play for a long time, it doesn't crash, but sometimes it crashes very frequently

**Comment by yejunjie10311031** [comment]
I think it's probably a chunk loading problem, because if I stand still or just walk around, it never crashes，but if I tp to another place or run quickly to another chunk,it crashes often,even sometimes it crashes as soon as I enter a world.But if I walk slowly to the chunk,it won't crash.And I can make sure that is not the performance problem of my device because I can usually run over 200fps when playing Mineceaft.

**Comment by testloldhdid** [comment]
This happens to me and i think i fixed it i think you have to lower your render distance if you have a bigger render distance the game will alocate more ram to loading chunks and less to the stuff happening around you it happen to me i lowerd by render distance and i played for a couple minutes and it didnt crash before i lowerd it i would crash in like 30 seconds

**Comment by testloldhdid** [comment]
Soory for bad english

**Comment by testloldhdid** [comment]
Nvm it just crashed

**Comment by testloldhdid** [comment]
Maybe because of mods this happens to me alot i had 2 mods techguns and optifine i removed optifine and it didnt crash for like 10 minutes or more (whit optifine i would crash in about 1 minute even on low graphics )

**Comment by Mathias-Boulay** [comment]
Device specific issue on an old version.
Closing

**Comment by ghost** [comment]
apps which run in backgound just crashes 
i used to play games while listening to music in spotify or call some friends on whatsapp these apps just keeps on crashing , is there any solutions for this

**Comment by Made0fB1naries** [comment]
You tried allocate your ram too much than what's left...try to allocate under 80% of what you have left

**Comment by Blur360-collab** [comment]
I have 2gb ram it's possible to add 512mb ram without the game crashed
