### ISSUE TITLE
[BUG]BANNER WHITE ISSUE

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#686]
Everytime I play minecraft the banner will become white no mattee what I does to the banner.. The color will never change

![Screenshot_20210123_200303.jpg](https://user-images.githubusercontent.com/76242887/105578945-a21e5b80-5dbe-11eb-89f3-09448554adfb.jpg)

**To Reproduce**
1. Start PojavLauncher
2. Press Play
3. Load to any world
4. Banner white

**Expected behavior**
I did not expected anything I am using 1.16.5 optifine this happen to every version I tested like 1.16.4, 1.12.2

**Platform:**
 - Device Model [Vivo y17 4/64]
 - CPU architecture [aarch64] 
 - Android Version [9]

I am using the latest action build

**Comment by khanhduytran0** [comment]
Similar to **#639**

Switch to GL4ES 1.1.5 by add -Dorg.lwjgl.opengl.libname=libgl4es_115.so to JVM arguments will fix this. Note that MC 1.14.4 and below may have some graphical issues on GL4ES 1.1.5.

**Comment by Adam0530** [comment]
> Similar to **#639**
> 
> Switch to GL4ES 1.1.5 by add -Dorg.lwjgl.opengl.libname=libgl4es_115.so to JVM arguments will fix this. Note that MC 1.14.4 and below may have some graphical issues on GL4ES 1.1.5.

But I want to use auto ram

**Comment by KorewaLidesu** [comment]
Add that won't affect auto ram.

**Comment by khanhduytran0** [comment]
@artdeell does auto ram works with custom arguments?

**Comment by artdeell** [comment]
Auto ram only removes existing -Xmx and -Xms values, and sets its own. Nothing bad should happen.

**Comment by Adam0530** [comment]
> Auto ram only removes existing -Xmx and -Xms values, and sets its own. Nothing bad should happen.

Cool! I try it out later and I will close this issue onlt if this work

**Comment by Adam0530** [comment]
> > Auto ram only removes existing -Xmx and -Xms values, and sets its own. Nothing bad should happen.
> 
> Cool! I will try it out later and I will close this issue onlt if this work

**Comment by Adam0530** [comment]
> > > Auto ram only removes existing -Xmx and -Xms values, and sets its own. Nothing bad should happen.
> > 
> > Cool! I will try it out later and I will close this issue only if this work
> 
>

**Comment by KorewaLidesu** [comment]
Please dont spam quote...

**Comment by Adam0530** [comment]
> Please dont spam quote...

I am sorry.. I am just editing my comment

**Comment by Adam0530** [comment]
It work and it also laggier.. Thanks for helping
