### ISSUE TITLE
1.16.4 forge installation  optifine does not work

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#687]

**Comment by yanluol** [comment]
Installing optifine doesn't work

**Comment by artdeell** [comment]
Does the forge itself work?

**Comment by yanluol** [comment]
Forge can work

**Comment by yanluol** [comment]
Optifine moves into mods folder and does not display when entering the game

**Comment by Mathias-Boulay** [comment]
1.16.4 forge does work with optifine on the google play version, since all graphical options related to it are working.
Closing issue.
