### ISSUE TITLE
[BUG] white banners

### ISSUE THREAD

**Issue by LoneLySTTR** [PojavLauncherTeam/PojavLauncher#688]
**Describe the bug**
White banners

**To Reproduce**
When I enter the world, I put up a banner - it's white

**Comment by sakakibara779** [comment]
If its version 1.15 and above just add this to your jvm lunch arguments in pojav launcher settings
-Dorg.lwjgl.opengl.libname=libgl4es_115.so
May cause issues on version 1.14.4 and below
(Copied from discord)

**Comment by OwzygZawg** [comment]
> If its version 1.15 and above just add this to the end of your jvm lunch arguments in pojav launcher settings:
> -Dorg.lwjgl.opengl.libname=libgl4es_115.so
> May cause issues on version 1.14.4 and below
> (Copied from discord)

![Screenshot_20210123-141636_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/105609179-4e901b80-5d86-11eb-86f0-fb91c91b1fca.jpg)
![Screenshot_20210123-141603_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/105609187-58b21a00-5d86-11eb-86c8-54e1c92c1cd5.jpg)


????

**Comment by OwzygZawg** [comment]
but I'm still in doubt if it's up or down!

**Comment by OwzygZawg** [comment]
Or.....
![Screenshot_20210123-141618_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/75042110/105609214-826b4100-5d86-11eb-82ec-616037e2bc8e.jpg)

**Comment by sakakibara779** [comment]
Does not matter where it is i have mine at the end
![Screenshot_20210123-201112](https://user-images.githubusercontent.com/48034004/105610229-43091880-5db7-11eb-81df-5578fcceab9c.png)

**Comment by sakakibara779** [comment]
Does not matter if its up or down, i have mine at the end.
![Screenshot_20210123-201112~01](https://user-images.githubusercontent.com/48034004/105610263-7c418880-5db7-11eb-8b79-60472e01cc02.png)

**Comment by OwzygZawg** [comment]
> Não importa se é para cima ou para baixo, eu tenho o meu no final.
> ![Screenshot_20210123-201112 ~ 01](https://user-images.githubusercontent.com/48034004/105610263-7c418880-5db7-11eb-8b79-60472e01cc02.png)

when I put it on the bottom, Minecraft came out and I put it on top too! could you give me your lastelog? please

**Comment by OwzygZawg** [comment]
Pls

**Comment by ghost** [comment]
I don't know how this will help you, but sure....
https://justpaste.it/4y3uu

**Comment by OwzygZawg** [comment]
Thanks!

**Comment by khanhduytran0** [comment]
> when I put it on the bottom, Minecraft came out and I put it on top too! could you give me your lastelog? please

Make sure java arguments doesn't contains line break.

**Comment by OwzygZawg** [comment]
> > quando coloquei na parte inferior, o Minecraft saiu e eu coloquei na parte superior também! você poderia me dar seu lastelog? por favor
> 
> Certifique-se de que os argumentos java não contenham quebra de linha.

Could you show a screenshot? I don’t know what position I put it in

**Comment by OwzygZawg** [comment]
Pls

**Comment by khanhduytran0** [comment]
You can put anywhere, but do not use line break/newline to split it.

**Comment by OwzygZawg** [comment]
Oh okay

**Comment by khanhduytran0** [comment]
Also this issue duplicates #686
