### ISSUE TITLE
[BUG] Stretched vanilla textures when galacticraft loaded

### ISSUE THREAD

**Issue by Vesek** [PojavLauncherTeam/PojavLauncher#689]
**Describe the bug**
When i load the three mods to play galacticraft, textures become completely stretched out.

**To Reproduce**
1. Start PojavLauncher
2. Instal Forge 1.12.2
3. Download newest galacticraft and copy it to mods folder
4. Start the game and create a new world.

**Expected behavior**
Textures looking normal

**Screenshots**
![Screenshot_2021-01-23-16-57-04-125_net kdt pojavlaunch](https://user-images.githubusercontent.com/61123478/105606908-2a3f3980-5d9c-11eb-8d74-f6260a4c476f.jpg)

**Platform:**
 - Device Model: Xiaomi POCO X3
 - CPU architecture: aarch64
 - Android Version: 10

**Comment by OwzygZawg** [comment]
it may be that this texture is out of date or check if you are using the texture in a incompatible version!

**Comment by khanhduytran0** [comment]
What about changing mipmap?

**Comment by Vesek** [comment]
Tried none and 4. But that's still a not expected behavior

**Comment by Vesek** [comment]
> it may be that this texture is out of date or check if you are using the texture in a incompatible version!

I use vanilla textures and the same setup on PC works without problem.

**Comment by OwzygZawg** [comment]
> > pode ser que esta textura esteja desatualizada ou verifique se está usando a textura em uma versão incompatível!
> 
> Eu uso texturas vanilla e a mesma configuração no PC funciona sem problemas.

Mipmap 0 maybe? Or mipmap 4?

**Comment by OwzygZawg** [comment]
the problem may be in the mipmap! if the mipmap is in 4 switch to mipmap 0 or 3,2,1

**Comment by Vesek** [comment]
> > > pode ser que esta textura esteja desatualizada ou verifique se está usando a textura em uma versão incompatível!
> > 
> > 
> > Eu uso texturas vanilla e a mesma configuração no PC funciona sem problemas.
> 
> Mipmap 0 maybe? Or mipmap 4?

I tried every mipmap setting and it looks the same.

**Comment by Vesek** [comment]
![Screenshot_2021-01-27-17-04-37-580_net kdt pojavlaunch](https://user-images.githubusercontent.com/61123478/106018812-3a1f8c00-60c2-11eb-89fc-8d544b3def36.jpg)
Even wierder on the moon...

**Comment by OwzygZawg** [comment]
Is bug maybe

Em qua, 27 de jan de 2021 13:09, Vesek <notifications@github.com> escreveu:

**Comment by Mathias-Boulay** [comment]
it is sadly a device specific issue (lack of VRAM) that cannot be fixed.
You can use a lower resolution resource pack
Closing issue since not specific to pojav.
