### ISSUE TITLE
Error? 1.15 ?

### ISSUE THREAD

**Issue by CoderA07** [PojavLauncherTeam/PojavLauncher#69]
Unable to convert library org.lwjgl:lwjgl:3.2.1
processing archive /storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1_orig.jar...
processing META-INF/...
writing META-INF/; size 0...
processing META-INF/INDEX.LIST...
writing META-INF/INDEX.LIST; size 554...
processing META-INF/MANIFEST.MF...
processing META-INF/versions/...
writing META-INF/versions/; size 0...
processing META-INF/versions/10/...
writing META-INF/versions/10/; size 0...
processing META-INF/versions/10/org/...
writing META-INF/versions/10/org/; size 0...
processing META-INF/versions/10/org/lwjgl/...
writing META-INF/versions/10/org/lwjgl/; size 0...
processing META-INF/versions/10/org/lwjgl/system/...
writing META-INF/versions/10/org/lwjgl/system/; size 0...
processing META-INF/versions/10/org/lwjgl/system/MathUtil.class...

PARSE ERROR:
unsupported class file version 54.0
...while parsing META-INF/versions/10/org/lwjgl/system/MathUtil.class
1 error; aborting
Exiting with code 1

**Comment by artdeell** [comment]
1.13 and higher is not supported.

**Comment by CoderA07** [comment]
> 1.13 and higher is not supported.

Sady :( My server owner is live on 1.15.2 version

**Comment by Azapru** [comment]
Omae wa mou Shindeiru

**Comment by artdeell** [comment]
For 1.15 you can try MCinaBox. Its chinese, but it supports all versions up to latest ones.

**Comment by khanhduytran0** [comment]
due to attack of new Boardwalk version, i might spend little time for ios :)

**Comment by gabbosta** [comment]
i'm trying but need a runtime pack and i don't know how to download

**Comment by pedrosouzabrasil** [comment]
@artdeell the apk is unavailable of the chinese launcher at the moment.lets wait for news.

**Comment by khanhduytran0** [comment]
> 1.13 and higher is not supported.

May v3 support these.

**Comment by khanhduytran0** [comment]
`wontfix` in v2.x
