### ISSUE TITLE
[BUG] it doesn't work

### ISSUE THREAD

**Issue by baqarigamer** [PojavLauncherTeam/PojavLauncher#690]
**Describe the bug**
How to install 1.14.4 forge or optifine it doesn't work its  just craching plz help

**Comment by OwzygZawg** [comment]
make sure you are on the latest version 3.3.1! it supports forge 1.14+ and the optifine installer is back, the latest is 3.3.1

**Comment by baqarigamer** [comment]
I have 3.3.1 but it doesn't work plz help how to install

**Comment by OwzygZawg** [comment]
okay I will try to find a video on youtube that can help you! wait a minute

**Comment by baqarigamer** [comment]
Ok

**Comment by OwzygZawg** [comment]
https://youtu.be/I_Mv0aMdr6c

**Comment by OwzygZawg** [comment]
I hope it helps you! that was the only one I found!

**Comment by OwzygZawg** [comment]
mods may not be working properly! this happened to me in forge 36.0 1.16.5

**Comment by baqarigamer** [comment]
Dude no I want 1.14.4 not 1.16.3

**Comment by OwzygZawg** [comment]
Oh sorry!

**Comment by baqarigamer** [comment]
Bruh plz help

**Comment by OwzygZawg** [comment]
The same way as the video to install forge 1.16 is the same way to install forge 1.14.4! mods may not work in any forge at 1.14+

**Comment by baqarigamer** [comment]
What about optifine?

**Comment by OwzygZawg** [comment]
Too!

**Comment by OwzygZawg** [comment]
let's say that optifine works more, it is also the same way of installing a forge in 3.3.1 in the latest one!

**Comment by khanhduytran0** [comment]
Use forge installer not universal.

**Comment by OwzygZawg** [comment]
> Use o instalador do forge não universal.

@baqarigamer look

**Comment by OwzygZawg** [comment]
@khanhduytran0  I think he already understood, now you can close the report?

**Comment by khanhduytran0** [comment]
Maybe
