### ISSUE TITLE
Can we install modpack in pojav? If we can.. How?

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#692]

**Comment by Zeyrox1090** [comment]
open in file manager and find datapacks folder on your world on saves folder

**Comment by Zeyrox1090** [comment]
![Screenshot_2021-01-24-11-21-28-81_846b44643ec609f507828878741e1f9a](https://user-images.githubusercontent.com/73925046/105620316-ab4b0f00-5e36-11eb-941c-0adf8905f682.jpg)

**Comment by Adam0530** [comment]
> open in file manager and find datapacks folder on your world on saves folder
> ![Uploading Screenshot_2021-01-24-11-21-28-81_846b44643ec609f507828878741e1f9a.jpg…]()
> 

Then.. What?

**Comment by Zeyrox1090** [comment]
maybe idk lol

**Comment by Zeyrox1090** [comment]
put the datapack in that folder

**Comment by Adam0530** [comment]
> put the datapack in that folder

did you mean modpack?

**Comment by Zeyrox1090** [comment]
yeah maybe

**Comment by KorewaLidesu** [comment]
You need to install on your owns.
Also, that isn't how to install mods. It is datapack to the world (vanilla usage).

**Comment by KorewaLidesu** [comment]
1. Install Forge/Fabric, run the game first so it will create folder.
2. Download the pack from internet (the fully pack), extract and move folder that need to move into `.minecraft` .
3. Config stuff.
4. Run and have fun.

**Comment by Adam0530** [comment]
> 1. Install Forge/Fabric, run the game first so it will create folder.
> 2. Download the pack from internet (the fully pack), extract and move folder that need to move into `.minecraft` .
> 3. Config stuff.
> 4. Run and have fun.

What do you mean with config stuff? Also, what if I want to change to another modpack?

**Comment by KorewaLidesu** [comment]
Unless Pojav support multiple instances, I dont think you can do it easily.

**Comment by DerpBurberr** [comment]
> Unless Pojav support multiple instances, I dont think you can do it easily.



> 1. Install Forge/Fabric, run the game first so it will create folder.
> 2. Download the pack from internet (the fully pack), extract and move folder that need to move into `.minecraft` .
> 3. Config stuff.
> 4. Run and have fun

How though? I extracted the Modpack and saw some familiar files inside so i pasted all of it in .minecraft. But what do you mean with the config stuff. I still dont know how to use modpacks lol

**Comment by Mathias-Boulay** [comment]
Closing the issue, as it was solved.
*and we can't expect users to check issues for such solutions*

**Comment by honee935** [comment]
Where do I put the Kubejs in?

**Comment by ghost** [comment]
> Closing the issue, as it was solved.
> *and we can't expect users to check issues for such solutions*

How can we use .mrpack file modpack in pojav ?

**Comment by janIpen** [comment]
> Closing the issue, as it was solved.
> *and we can't expect users to check issues for such solutions*

I'm literally on page 2 of google

**Comment by Pearpear43** [comment]
For anyone wondering, in the version Edelweiss and above (android), you can install modpacks from curseforge and modrinth. For the people on iOS, version 2.2 does not support this. You must go to the PojavLauncher iOS github page, then go to the actions tab and download from the most recent upload.
