### ISSUE TITLE
How to install forge 1.12.2 

### ISSUE THREAD

**Issue by Pikajjh05** [PojavLauncherTeam/PojavLauncher#693]
I have been trying to figure out how to install 1.12.2 I have tried disabling the splash screen and installing the installer for it say game exited everytime I try to launch it

**Comment by Adam0530** [comment]
> I have been trying to figure out how to install 1.12.2 I have tried disabling the splash screen and installing the installer for it say game exited everytime I try to launch it

What forge version you use to launch? If you are using 2847... It will never work.. Try using the recommend version.. Also, I am asking about this issue.. So, lets wait

**Comment by Mathias-Boulay** [comment]
Forge 1.12.2 installs and works properly on the latest google play release.
Closing the issue.
