### ISSUE TITLE
[BUG]JVM ARGUMENT DID NOT WORK

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#695]
**Describe the bug**
I add this jvm argument to make chunk loading fastest.. And ir suddenly kuck me out when I just tap on play

JVM Argument:
-d64 -client -XX:+UnlockExperimentalVMOptions  -XX:+AggressiveOpts -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+OptimizeStringConcat -XX:+UseStringDeduplication -XX:+UseFastAccessorMethods

1. Start PojavLauncher
2. Add those JVM Argument
3. Press play
4. Crash

**Platform:**
 - Device Model [Vivo y17 4/64]
 - CPU architecture [aarch64] 
 - Android Version [9]

**Comment by khanhduytran0** [comment]
> **-d64 -client**

Both are bad options, they will just gives crashes.
(`-d64` on 32bit device is bad).

**Comment by WesleyVanNeck** [comment]
java flags use it at own risk and dont use capps
