### ISSUE TITLE
A sudden turn of the head can also lead to crash

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#697]
A sudden turn of the head can also lead to a crash,and there isn't any crash-report.Its situation is the same as https://github.com/PojavLauncherTeam/PojavLauncher/issues/685#issuecomment-766337617_

**Comment by khanhduytran0** [comment]
Add `-Xcheck:jni` to jvm arguments to see what happened on crash.

**Comment by Mathias-Boulay** [comment]
I had the same issue with the default args provided by the launcher, there was a *memory connection overburdened* and then a crash

**Comment by WesleyVanNeck** [comment]
> I had the same issue with the default args provided by the launcher, there was a _memory connection overburdened_ and then a crash

Latest doesn't have Flags other the memory

**Comment by Mathias-Boulay** [comment]
> Latest doesn't have Flags other the memory

I'm aware of that

**Comment by yejunjie10311031** [comment]
It seems that the newest version solved the problem.Thanks a lot.

**Comment by yejunjie10311031** [comment]
Oh no,the latest version also has the problem.

**Comment by yejunjie10311031** [comment]
@khanhduytran0  I have added -Xcheck:jni to jvm arguments,and where I can see the report when it crashes?

**Comment by khanhduytran0** [comment]
It's in the log

**Comment by yejunjie10311031** [comment]
But there is nothing wrong or strange in the latestlog.txt

**Comment by yejunjie10311031** [comment]
@khanhduytran0 Now I know what caused the game to crash.After I added -Xcheck:jni to jvm arguments,whenever the game crashes,there is"Memory connection overburdened"in the latestlog.txt

**Comment by Mathias-Boulay** [comment]
@yejunjie10311031 does the issue still happen with the latest google play release ?

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build build
