### ISSUE TITLE
Test results for 2.4.2 Android 10

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#7]
My results is:
  1.7.10: Works IDEALLY. Chunk loading is fast,
  1.8: Works decently. Lags on chunk loading
  1.9: Works, but it works SLOOWLY in single player world.
  1.10: Same s as 1.9
  1.11: Working. No lags when standing by, but movement is a bit tricky because of lags. Also, the game lags A LOT near world border.
  1.12: Not working.

**Comment by artdeell** [comment]
UPD: 1.12 not works because it needs Java 8, which is disabled for max launcher compartiblity.

**Comment by khanhduytran0** [comment]
Thanks for your test. Updating README.md

**Comment by khanhduytran0** [comment]
Something like Minecraft 1.12 and higher switched to LWJGL3?

**Comment by artdeell** [comment]
> UPD: 1.12 not works because it needs Java 8, which is disabled for max launcher compartiblity.

Nope. Just it's Java 1.8

**Comment by khanhduytran0** [comment]
Minecraft 1.12 error similar to https://stackoverflow.com/questions/54224065/bootstrap-method-returned-null-android-crash-immediately-on-launch

I set `targetSdkVersion 24`. So it might work if I set `targetSdkVersion 26 // android 8`
