### ISSUE TITLE
[F-REQ] Install modpack

### ISSUE THREAD

**Issue by KorewaLidesu** [PojavLauncherTeam/PojavLauncher#701]
**Is your feature request related to a problem? Please describe.**
#692 

**Describe the solution you'd like**
Implement modpack downloader by using API ([Modpacksch for FTB](https://modpacksch.docs.apiary.io/), [TwitchAppAPI](https://twitchappapi.docs.apiary.io/), etc.)

**Additional context**
[MMC](https://github.com/MultiMC/MultiMC5)

**Comment by SprainedSpark89** [comment]
there is a mod installer now

**Comment by tsukasabonk** [comment]
> there is a mod installer now

What where?? u mean in the pojav like inside??

**Comment by GaucovyAero** [comment]
> > there is a mod installer now
> 
> What where?? u mean in the pojav like inside??

in the launcher, not in minecraft

**Comment by tsukasabonk** [comment]
> > > there is a mod installer now
> > 
> > 
> > What where?? u mean in the pojav like inside??
> 
> in the launcher, not in minecraft

Yes I know, what I'm saying is like similar to installing forge/fabric like that? get it??

**Comment by GaucovyAero** [comment]
> > > > there is a mod installer now
> > > 
> > > 
> > > What where?? u mean in the pojav like inside??
> > 
> > 
> > in the launcher, not in minecraft
> 
> Yes I know, what I'm saying is like similar to installing forge/fabric like that? get it??

yep

**Comment by tsukasabonk** [comment]
> > > > > there is a mod installer now
> > > > 
> > > > 
> > > > What where?? u mean in the pojav like inside??
> > > 
> > > 
> > > in the launcher, not in minecraft
> > 
> > 
> > Yes I know, what I'm saying is like similar to installing forge/fabric like that? get it??
> 
> yep

yeah... I tried it.. I didn't work it just crash the launcher. I really needed this modpacks💀

**Comment by GaucovyAero** [comment]
> > > > > > there is a mod installer now
> > > > > 
> > > > > 
> > > > > What where?? u mean in the pojav like inside??
> > > > 
> > > > 
> > > > in the launcher, not in minecraft
> > > 
> > > 
> > > Yes I know, what I'm saying is like similar to installing forge/fabric like that? get it??
> > 
> > 
> > yep
> 
> yeah... I tried it.. I didn't work it just crash the launcher. I really needed this modpacks💀

but you aren't on the latest pojav build, update [here](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

**Comment by tsukasabonk** [comment]
> 

so uhh I'm confused where do I find?? It xD sorry am dumb asf. tell me imma figure it out

**Comment by GaucovyAero** [comment]
> > 
> 
> so uhh I'm confused where do I find?? It xD sorry am dumb asf. tell me imma figure it out

click on anything with a green checkmark on it and download app-debug.zip, then extract the folder and install the apk.

**Comment by tsukasabonk** [comment]
> > > 
> > 
> > 
> > so uhh I'm confused where do I find?? It xD sorry am dumb asf. tell me imma figure it out
> 
> click on anything with a green checkmark on it and download app-debug.zip, then extract the folder and install the apk.

Oh like anything like anything anything?? just have green right? alright

**Comment by KorewaLidesu** [comment]
> there is a mod installer now

Make sure you dont get wrong between install mod and import modpack

**Comment by Mathias-Boulay** [comment]
sadly, the option of going through the API has not been retained, as it undermines the creators revenues
