### ISSUE TITLE
does badlion work now? how?

### ISSUE THREAD

**Issue by luckyrv941** [PojavLauncherTeam/PojavLauncher#702]

**Comment by Adam0530** [comment]
> 

I dont think so.. Cause I have never figured it out how to install it... and its only using exe format to install

**Comment by matt995** [comment]
It could come as badlion has Linux

**Comment by artdeell** [comment]
> It could come as badlion has Linux

it's an appimage compiled for x86

**Comment by Mathias-Boulay** [comment]
Since it is not given as a jar, it won't be possible to make badlion work with pojav.
Closing
