### ISSUE TITLE
[F-REQ] pls add

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#703]
-Dorg.lwjgl.opengl.libname=libgl4es_115.so"      should come along with the JVM arguments in the next Pojav update!

**Comment by OwzygZawg** [comment]
@khanhduytran0  maybe?

**Comment by khanhduytran0** [comment]
No, as I said Minecraft 1.14.4 and below are buggy on new GL4ES, so it could not be default.
