### ISSUE TITLE
[BUG]Why forge mc 1.12.2 - 14.23.5.2847 did not work?

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#705]
**Describe the bug**
So here, everytime I tried to those forge version.. It always the beginning of start and I cant play with that forge version.. Just why?(I have tried other then those version(Recommend version) and it work but this not)

**To Reproduce**
1. Start PojavLauncher
2. Install forge version
3. Press play
4. Wait for download
5. Crash at the beginning of start

**Platform:**
 - Device Model [Vivo y17 4/64]
 - CPU architecture [aarch64] 
 - Android Version [9]

**Comment by khanhduytran0** [comment]
Can you send log?

**Comment by Adam0530** [comment]
> Can you send log?

Nope, I cant.. Everytime I tried to paste it.. It will stuck for a minutes and then crash.. I try to send it 1 by 1 but I keep accidently tap on my back button.. So, I will need to do the same thing.. And it will waste my time.. I also tried to share the file but I dont know how.. Any idea?

**Comment by khanhduytran0** [comment]
Well you can send file instead of the entire text

**Comment by rishi130** [comment]
What forge version you use??????

**Comment by khanhduytran0** [comment]
So, forge problem.
Also you haven't sent latestlog.txt @Adam0530

**Comment by Mathias-Boulay** [comment]
Forge 1.12.2 (14.23.5.2855) works on the latest action build.
I can launch pixelmon+flans and optifine without any issue.
*Also shooting pokemon are fun*

Anyway, closing the issue since it is stale and no logs have been provided.
