### ISSUE TITLE
[F-REQ]Launch a server from the phone.

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#706]
Feature : Add Server Software 

Details  : In Future Can Your Team Create A Server Tool Too For Creating A Server Or To Play With Friends!

Feature : Fix In-Game Commands 

More Details : I Can't Use Even The Common In-Game Commands Like /gamemode  , Please Fix!

**Comment by khanhduytran0** [comment]
> Add Server Software

We may take a look at ability to run Minecraft server then.

> Fix In-Game Commands

You need make sure these things:
- Cheats is enabled
- The keyboard can type commands, can press enter

**Comment by AgaricaGamer** [comment]
But in My phone (Vivo V5) it doesn't work!

**Comment by khanhduytran0** [comment]
Keyboard?

**Comment by AgaricaGamer** [comment]
Is that an system error for keyboard?

**Comment by khanhduytran0** [comment]
@AgaricaGamer use gboard

**Comment by Mathias-Boulay** [comment]
Technically, you can launch a server now 😂 
Closing, as the keyboard issue is fixed and the server thing is far from our roadmap
