### ISSUE TITLE
[F-REQ] Upstream gl4es

### ISSUE THREAD

**Issue by Google61** [PojavLauncherTeam/PojavLauncher#708]
Now PojavLauncher use prebuilt libs while building, but I think we could replace gl4es 115 with upstream repo.
Solution would be to fork gl4es, set up workflow build, then in Android CI add artifact downloading from gl4es fork. After this just merging from master into fork...
One thing is I'm unsure which building method is/what args are correct for gl4es, I've only modified Android.mk to produce shared lib instead of static
My NDK workflow for gl4es https://github.com/Google61/gl4es/blob/master/.github/workflows/android.yml

**Comment by khanhduytran0** [comment]
Good idea. Do you mean: fork gl4es, then modify Android.mk. On PojavLauncher repo side, clone and git pull upstream, then build. Finally copy libs overwrite current one.

**Comment by khanhduytran0** [comment]
Also, setup ndk part is not need. Github actions already has NDK preinstalled.

**Comment by Google61** [comment]
Fork gl4es: after building upload artifact
Pojav: before gradle download artifact from last run in gl4es fork
It's possible by using https://github.com/dawidd6/action-download-artifact
I don't think you want to rebuild gl4es every pojav commit xd
