### ISSUE TITLE
No symbols

### ISSUE THREAD

**Issue by SiergoMakatao** [PojavLauncherTeam/PojavLauncher#709]
there are no such characters as ("* # @ '§) because of this, complex commands cannot be written!

**Comment by artdeell** [comment]
This issue was fixed in 3.3.1.

**Comment by SiergoMakatao** [comment]
> Эта проблема исправлена ​​в версии 3.3.1.

I play the same versions
 Or maybe there is a problem in aarch32

**Comment by artdeell** [comment]
Попробуй установи Gboard как клавиатуру, авось заработает

**Comment by SiergoMakatao** [comment]
> Попробуй установи Gboard как клавиатуру, авось заработает

I've tried both this and that
 What if reinstall Pojav and aarch32

**Comment by SiergoMakatao** [comment]
Where to download the official aarch32 for pojav launcher

**Comment by artdeell** [comment]
Тебе нужно тогда скачивать из GitHub Actions, там встроенная 32-битка

И да, я говорю по-русски

**Comment by SiergoMakatao** [comment]
А ясно сп

**Comment by Mathias-Boulay** [comment]
The issue is solved on the google play release.
Closing issue.
