### ISSUE TITLE
Unable to launch 1.7.10

### ISSUE THREAD

**Issue by GeraldBalingcasag** [PojavLauncherTeam/PojavLauncher#71]
In preview 9b4
I wasn't able to run 1.7.10 and just says an error. Is it because my os version is too high? My android version is 9
Huawei Y6 Pro 2019

**Comment by khanhduytran0** [comment]
Not, seems like Huawei devices can't run...

**Comment by artdeell** [comment]
@khanhduytran0 Huawei Y series are low-end, and contaim MTK CPUs usually. This is the error. I think this is a binary incompartibility.

**Comment by GeraldBalingcasag** [comment]
I was able to run 1.11 pretty smoothly ;-;

**Comment by GeraldBalingcasag** [comment]
Also I managed to download and run 1.7.10 smoothly in the past versions, and after I downloaded 1.11 I couldn't download others, maybe I couldn't download anything anymore because I installed OptiFine

**Comment by khanhduytran0** [comment]
Why can't?

**Comment by GeraldBalingcasag** [comment]
Even in vmos I couldn't run 1.7.10

**Comment by khanhduytran0** [comment]
Try again in other preview.

**Comment by GeraldBalingcasag** [comment]
OK it seems like I have use a specific preview
