### ISSUE TITLE
Cannot set button to "N"

### ISSUE THREAD

**Issue by Pairman** [PojavLauncherTeam/PojavLauncher#710]
Whenever I set a button with key N in the custom control, and reopen the edit interface, the key will return to M. I opened the json and it's code is 77, same as M.
Also, it's nice that if you fix the bug that the scrolling speed is too fast for many interfaces such as inventory, settings and many mod settings. 
Thanks in advance.

**Comment by Pairman** [comment]
I'm using version 3.3.1_rel_20210117

**Comment by Pairman** [comment]
The button ingame is also M

**Comment by artdeell** [comment]
Try this build: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/510022808

**Comment by Pairman** [comment]
@artdeell thanks. the bug is fixed now ☺️
