### ISSUE TITLE
[BUG] incorrect sensor control

### ISSUE THREAD

**Issue by pavel19108** [PojavLauncherTeam/PojavLauncher#714]
**description**
The application has a bug with controls in full screen mode of the game on non-standard screen sizes. The control is shifted by a certain distance, depending on the position of the cursor.

**To Reproduce**
1. Buy any phone with non-standart screen proporions XD. Or just use VMOS.
2. Launch PojavLauncher.
3. Install Minecraft 1.16.4.
4. Launch it.
5. go to any menu and enjoy the PERFECT control (sarcasm).

**Expected behavior**
I found a bug with full screen mode that gets worse with shifting from left to right. On 1.12.2, this problem did not manifest itself, since the game correctly understood the screen resolution. I tried to manually change the resolution in the settings, but it didn't help.

**Screenshots**
1.12.2 (no bugs):
![Screenshot_20210126_064422_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798225-ba4ed000-5fa2-11eb-92d4-ec2d8e472c4c.jpg)
![Screenshot_20210126_064423_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798234-bfac1a80-5fa2-11eb-830f-9a473d927fc3.jpg)
![Screenshot_20210126_064424_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798243-c5a1fb80-5fa2-11eb-9b6e-40a056ee73ad.jpg)![Screenshot_20210126_064425_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798252-c9358280-5fa2-11eb-989d-c090b706838c.jpg)![Screenshot_20210126_064515_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798367-0ef24b00-5fa3-11eb-865d-81edfae5506f.jpg)

1.16.4
![Screenshot_20210126_064445_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798428-31846400-5fa3-11eb-97c6-2e1d0ef4a18d.jpg)![Screenshot_20210126_064451_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798438-3517eb00-5fa3-11eb-9fad-34f19a555142.jpg)![Screenshot_20210126_064456_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798441-36491800-5fa3-11eb-8c0a-5375e6c889c3.jpg)![Screenshot_20210126_064500_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798452-39440880-5fa3-11eb-8ca8-9bfd8fa774a0.jpg)![Screenshot_20210126_064539_com.huawei.himovie.overseas.jpg](https://user-images.githubusercontent.com/77898934/105798460-3d702600-5fa3-11eb-87dc-a3c9dcb1d019.jpg)

main problem due to this part of the screen:
![Screenshot_20210126_065451.jpg](https://user-images.githubusercontent.com/77898934/105798572-845e1b80-5fa3-11eb-9dce-f91096fc5d9c.jpg)

**Platform:**
 - Device Model Honor View 20
 - CPU architecture aarch64
 - Android Version 10
 - Screen size:
    a) full screen size 2310x1080 (19.25/9)
    b) In not fullscreen mode 2091x1080 (17,425/9)

P.s. it's me again and again translated by Google Translator...
P.p.s. I accidentally mixed up the screenshots, the last from each version is the opposite

**Comment by khanhduytran0** [comment]
Wait, if you are from Russia, you could just explain issue on Russian and talk with @artdeell about the problem

About the problem, try switch to (non?)full screen mode.

**Comment by artdeell** [comment]
It's a known issue that Forge screen is always offset on the devices with the navbar. You need to set fullscreen to off in settings to compensate it

**Comment by pavel19108** [comment]
I cannot turn off full-screen mode, because the system does not allow me to change this setting in your application
![Screenshot_20210126_135753_com.android.settings.jpg](https://user-images.githubusercontent.com/77898934/105836865-eab45f80-5fde-11eb-8dd7-bdbc3a7a0225.jpg)
Bridge constructor for example has this setting. ![Screenshot_20210126_135936.jpg](https://user-images.githubusercontent.com/77898934/105836899-f6a02180-5fde-11eb-85c1-81c02f431b42.jpg)

**Comment by pavel19108** [comment]
@artdeell, I accidentally solved 2 errors at once - a bug with the visibility of water through the blocks:
![Screenshot_20210130_185803_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/77898934/106361426-dcdc4280-632e-11eb-8cfd-a912beb9a626.jpg)
and this bug, just restarted (**not disabled**) Options→Video Settings→Other...→Fullscreen

**Comment by pavel19108** [comment]
if translated into English incorrectly somewhere, pls correct me.
