### ISSUE TITLE
[BUG] Seeing Through blocks 

### ISSUE THREAD

**Issue by bonniechica** [PojavLauncherTeam/PojavLauncher#715]
**Describe the bug**
im playing minecraft pixelmon and im getting a see through block thing i can see through almost every block even underground

**To Reproduce**
1. Start PojavLauncher
2. launch forge 1.12.2
3. have gui scale on auto/no full screen/150 res
4. load into server/singleplayer
5. walk around and look for blocks that are see through

**Expected behavior**
I expected that with all the improvements that u all made i can get rid of the one prob but i encounter another 

**Screenshots**
![Screenshot_20210125-205350](https://user-images.githubusercontent.com/20906501/105800790-9325dd80-5f65-11eb-9938-025586f810b6.png)

**Platform:**
 - Device Model [Moto G Power 2020]
 - CPU architecture [aarch64] 
 - Android Version [10]

**Comment by bonniechica** [comment]
and before one of u say change guiscale i tried that

**Comment by khanhduytran0** [comment]
Try to toggle full screen.

**Comment by CosineMath** [comment]
Use fancy F11 key!

**Comment by AstroReality-Li** [comment]
v3  1.14.4也有这样的错误

**Comment by bonniechica** [comment]
if i have full screen i cant use the res part i think ill try it tho if it works ill reply back

**Comment by bonniechica** [comment]
works with 399 res on full screen with small gui but if someone else encounters this can u guys try to fix it for the next update thanks

**Comment by Mathias-Boulay** [comment]
The resolution ratio has been replaced by a resolution scaler instead. Not sure if it will avoid any of the values causing this. @bonniechica

**Comment by bonniechica** [comment]
u mean the scroll part or ?

**Comment by Mathias-Boulay** [comment]
If you mean the seekbar in the settings, yep.

> u mean the scroll part or ?

**Comment by ASGAMING009** [comment]
> u mean the scroll part or ?

Dude did the PC i mean in the game PC works or what WHERE YOU STORE YOUR POKEMON

**Comment by Mathias-Boulay** [comment]
@bonniechica does the issue still occurs with the latest google play release ?

**Comment by Mathias-Boulay** [comment]
Stale issue, no response from the author.
Closing
