### ISSUE TITLE
在文件中无法找到.minecraft文件

### ISSUE THREAD

**Issue by AstroReality-Li** [PojavLauncherTeam/PojavLauncher#719]
**Describe the bug**
在文件中无法找到.minecraft文件，但游戏可正常启动。

**To Reproduce**
1. 启动 PojavLauncher
2.无法找到.minecraft文件，游戏可正常启动
3.是否已储存到云端？

**Platform:**
 - VIVIO S5
 - aarch64
 - Android  10

**Comment by artdeell** [comment]
我们不使用任何云存储，仅使用Mojang的服务器下载游戏。 您需要在文件资源管理器中找到“显示隐藏的文件夹”选项

**Comment by AstroReality-Li** [comment]
谢谢，已找到

**Comment by Mathias-Boulay** [comment]
the issue has been solved, closing it.
