### ISSUE TITLE
Can i fork?

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#72]
@khanhduytran0 can I fork your PojavLauncher's sources to do some testing?
Why I wish to fork PojavLauncher:

- Ready-to-go codebase. Boardwalk, for example, needs to fix many things before giong to work.
- (currently) Faster performance. Compared to Boardwalk and MCinaBox, PojavLauncher is currently fastest
I'm gonna do some experiments with RAM, and with Boardwalk's LWJGL 3 implementation.
I will not leak your sources.

**Comment by khanhduytran0** [comment]
Invited. Seems like might open source if everything OK.

**Comment by khanhduytran0** [comment]
How to fork instead of contribute?

**Comment by khanhduytran0** [comment]
If can't fork, create a new branch for your testing.

**Comment by artdeell** [comment]
I need an app's sources.

**Comment by khanhduytran0** [comment]
Accept to invite you will get to source (collaborator ? Or contributor...).

**Comment by khanhduytran0** [comment]
![_20200408_191241](https://user-images.githubusercontent.com/40482367/78782958-12ddbe00-79cd-11ea-9ba4-3c467e8315b4.jpg)
Not sure if it is ok

**Comment by artdeell** [comment]
Accepted. When I will get to my PC, i will setup Travis or GH Actions.

**Comment by artdeell** [comment]
I will try to get 1.12.2 to work. As i read on somewhere in Android's website, most Java 8 features are available on any API level, but something is only on level 24. So, mow i'm installing Android 5 to AVD to test it.

**Comment by khanhduytran0** [comment]
I see some public repositorys has setup to release to their source. But in this case is auto release from private commit to public bug tracking.

**Comment by pedrosouzabrasil** [comment]
@khanhduytran0 any news for today?new version?

**Comment by pedrosouzabrasil** [comment]
Sorry if this is the wrong topic..

**Comment by pedrosouzabrasil** [comment]
I have high hopes for this project.i am little anxious..but its ok.I know that programming takes time.Everything is gonna be allright..

**Comment by khanhduytran0** [comment]
Some doing:
- Long press on hotbar to drop item.
- Will be custom Forge version (modified and build from source)???
- Regal OpenGL ???

**Comment by khanhduytran0** [comment]
(forked) but privated since I moved all things from `PojavLauncherSource` -> `PojavLauncher` repo.
