### ISSUE TITLE
[BUG] Trying to launch a custom Minecraft version in Pojavlauncher causes a crash.

### ISSUE THREAD

**Issue by OksmaWarez** [PojavLauncherTeam/PojavLauncher#721]
**Describe the bug**
When I tried to launch a custom version using Pojavlauncher, it resulted in a crash.

**To Reproduce**
1. Start PojavLauncher
2. Select any custom version
3. Launch it

**Expected behavior**
I expected the version to launch as usual.

**Screenshots**

**Platform:**
 - Redmi Note 9 64GB (Non-Rooted)
 - aarch64
 - Android 10

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5873223/latestlog.txt)

**Comment by khanhduytran0** [comment]
JVM arguments invalid. They must be splited with a space.
```
-XX:MaxTenuringThreshold=1-Dhttp.proxyHost=betacraft.pl
                      >>> ^ <<< HERE
```
