### ISSUE TITLE
[BUG] The game is crashing when I enter in a server 

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#723]
**Describe the bug**
The game crash when I try to enter in a server, like hypixel for example.

**To Reproduce**
1. Start PojavLauncher v3.3.1.1
2. enter in 1.12.2 optifine G5 (I'm using my original account)
3. and I try to enter in hypixel, but the game crash.
...

**Expected behavior**
I expected that I can play in the server.

**Screenshots**

**Platform:**
 - Device Model: Moto G6 play
 - CPU architecture: aarch32
 - Android Version: 9

**Comment by khanhduytran0** [comment]
What about the log?

**Comment by MateusL13** [comment]
> What about the log?

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5875658/latestlog.txt)

**Comment by MateusL13** [comment]
> What about the log?

The one on top is the correct log?
