### ISSUE TITLE
[BUG] i need help

### ISSUE THREAD

**Issue by baqarigamer** [PojavLauncherTeam/PojavLauncher#725]
Plz tell me how to fix grass block in 1.16 when I hold it it's white from the top plz help

**Comment by LANCECRAFT1104** [comment]
Ahahahhahahahahhahahahah

**Comment by khanhduytran0** [comment]
Maybe try change mipmap?

**Comment by Mathias-Boulay** [comment]
Stale issue, no form filled and no answer from the author.
Closing it.
