### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#726]
enable / disable button left click and right click by tapping / hold tapping on the screen pls

**Comment by khanhduytran0** [comment]
It could be conflicts. Maybe
- hold triggers hold left mouse
- double-tap and hold triggers hold right mouse?

**Comment by Mathias-Boulay** [comment]
Such behavior has been introduced via an option into the google play version.
Closing issue.
