### ISSUE TITLE
[F-REQ] skin installer 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#728]
Add skins installer

**Comment by artdeell** [comment]
You can use minecraft.net for this, why do you need it in Pojav?

**Comment by LANCECRAFT1104** [comment]
> You can use minecraft.net for this, why do you need it in Pojav?

Because we didn't buy the game because i don't have enough money for the game.

**Comment by KorewaLidesu** [comment]
Just install mod....

**Comment by KorewaLidesu** [comment]
This app is intent to be normal launcher. 
If you want skin changer, just implement it on your fork.

**Comment by LANCECRAFT1104** [comment]
https://www.youtube.com/watch?v=UuCVHQzzFMk
Watch it and don't forget to SUBSCRIBE TAP THE BELL also LIKE my Video 👍👍👍👍

**Comment by LANCECRAFT1104** [comment]
> Just install mod....

What mod. MOD OR RESOURCE PACK?
but how to mod it i think.........

**Comment by LANCECRAFT1104** [comment]
> https://www.youtube.com/watch?v=UuCVHQzzFMk
> THIS ONE MAN

and if you watch make sure to SUBSCRIBE TAP THE BELL and LIKE if you want.

**Comment by matt995** [comment]
> > https://www.youtube.com/watch?v=UuCVHQzzFMk
> > THIS ONE MAN
> 
> and if you watch make sure to SUBSCRIBE TAP THE BELL and LIKE if you want.

I dont think github is the place to setup ads..?.

**Comment by AjGamingPHOfficial** [comment]
You cant promote your own channel here.

**Comment by AjGamingPHOfficial** [comment]
You cant promote your own channel here.

**Comment by Mathias-Boulay** [comment]
The dev team decided that it won't be on their roadmap, since the official website exists for that.
Closing the issue.
