### ISSUE TITLE
[bug] Not starting

### ISSUE THREAD

**Issue by harsh-gupta-10** [PojavLauncherTeam/PojavLauncher#729]
**Describe the bug**
when i launched any version it just start and close automatically i tryed this with outher version and different device too but it dont work

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Template is not filled. Please fill the template so that we can better understand the issue.
