### ISSUE TITLE
Add this to your next update

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#73]
-Add A Feature that makes buttons smaller/larger to make a space for new buttons.
-Add A Player Settings.
-Add A Support Full Screen for Launcher. If you had a problem supporting Full Screen, just move the Minecraft Screen to the middle and the buttons move to the black bars on the side as a space. Except for Arrow keys, jump, sneak, place block, and break block.
Example:
![Untitled11_20200409091247](https://user-images.githubusercontent.com/62983424/78847819-8241c500-7a42-11ea-8e01-838893dc349e.png)

**Comment by khanhduytran0** [comment]
> -Add A Feature that makes buttons smaller/larger to make a space for new buttons.

OK

> -Add A Player Settings.

Need more description.

> -Add A Support Full Screen for Launcher. If you had a problem supporting Full Screen, just move the Minecraft Screen to the middle and the buttons move to the black bars on the side as a space. Except for Arrow keys, jump, sneak, place block, and break block.
> Example:
> ![Untitled11_20200409091247](https://user-images.githubusercontent.com/62983424/78847819-8241c500-7a42-11ea-8e01-838893dc349e.png)

This will break the default controls (it is worse than default from Boardwalk)

**Comment by FranzelDamasco909** [comment]
Oh ok this is a bad idea

**Comment by FranzelDamasco909** [comment]
Maybe you can add player settings and button size except that
