### ISSUE TITLE
[BUG] launcher not launching

### ISSUE THREAD

**Issue by harsh-gupta-10** [PojavLauncherTeam/PojavLauncher#730]
when i launched any version it just start and close automatically i tryed this with other version and different device too but it dont work
And it just give a launch id

And one more thing when i go to files games/PojavLauncher/
There were no any father folders even i download 
2 versions of minecraft
![Screenshot_2021-01-26-23-19-54-70](https://user-images.githubusercontent.com/77847454/105883607-0e05fb80-602d-11eb-8982-2dcdc6fbe0a0.png)

Pls fix that think

**Comment by artdeell** [comment]
Enable "Show hidden files" in your file explorer.

**Comment by harsh-gupta-10** [comment]
But what about that launcher problem

**Comment by IzooGGaming** [comment]
> Enable "Show hidden files" in your file explorer.

But what about launcher problem

**Comment by artdeell** [comment]
I can't analyze the problem unless you send the latestlog
> Send the latestlog.txt from games/PojavLauncher/.minecraft

**Comment by harsh-gupta-10** [comment]
> I can't analyze the problem unless you send the latestlog
> 
> > Send the latestlog.txt from games/PojavLauncher/.minecraft

[Uploading latestlog.txt…]()

**Comment by harsh-gupta-10** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5875254/latestlog.txt)

**Comment by harsh-gupta-10** [comment]
> I can't analyze the problem unless you send the latestlog
> 
> > Send the latestlog.txt from games/PojavLauncher/.minecraft

Not working

**Comment by khanhduytran0** [comment]
@IzooGGaming out of memory

**Comment by harsh-gupta-10** [comment]
No i have 17gb empty

**Comment by khanhduytran0** [comment]
I mean RAM not storage

**Comment by harsh-gupta-10** [comment]
2gb ram Is empty

**Comment by khanhduytran0** [comment]
Also your device is 32bit so RAM is limited.

**Comment by Mathias-Boulay** [comment]
Stale issue, and the bug appears not to be from pojav itself.
Closing it.
