### ISSUE TITLE
[F-REQ]Mouse is Too Big

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#731]
**Is your feature request related to a problem? Please describe.**
The mouse is too big man turn it 75% to 50%

**Describe the solution you'd like**
Turn back 25% to 500%

**Describe alternatives you've considered**
Turn back 25% to 500%
![Screenshot_2021-01-27-15-13-02-49](https://user-images.githubusercontent.com/75970303/105956236-73500000-60b2-11eb-82b2-d8449a973032.png)

**Comment by khanhduytran0** [comment]
So, don't set too big.

**Comment by LANCECRAFT1104** [comment]
> So, don't set too big.

Nope

**Comment by LANCECRAFT1104** [comment]
![Screenshot_2021-01-27-15-13-02-49](https://user-images.githubusercontent.com/75970303/105956058-2e2bce00-60b2-11eb-99bf-2370a276df43.png)
Why 100% is the minimum it is too big

**Comment by LightestMC** [comment]
The minimum is 20% for me

**Comment by Mathias-Boulay** [comment]
minimal mouse size option has been lowered.
Closing issue.
