### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mastercraft01** [PojavLauncherTeam/PojavLauncher#733]
**Describe the bug**
hotbar inventory is difficult to press, sometimes you can change items sometimes not

**Screenshots**
if the screenshot is not visible anything but if the video is clear

**Platform:**
 - Device Model [e.g. Oppo a3s 2/16]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 8]

**Comment by Mathias-Boulay** [comment]
This hotbar has been overhauled to support all screen at all GUI scales and custom resolutions on the google play release.
Closing the issue.
