### ISSUE TITLE
[BUG]VIVO手机安卓七点击forge安装器闪退

### ISSUE THREAD

**Issue by jjj273** [PojavLauncherTeam/PojavLauncher#736]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
English please

**Comment by Zeyrox1090** [comment]
VIVO mobile phone Android seven click forge installer crashes

**Comment by Zeyrox1090** [comment]
google translate lol

**Comment by jjj273** [comment]
Can you fix this bug?

**Comment by khanhduytran0** [comment]
@jjj273 we are unable to fix without any further info

**Comment by jjj273** [comment]
Can you add my QQ number, I send you a video to watch, you will know what I want to say.

**Comment by khanhduytran0** [comment]
I don’t use QQ. **I’m not Chinese**.

**Comment by jjj273** [comment]
What should I use?

**Comment by jjj273** [comment]
Do you use bilibili?

**Comment by Mathias-Boulay** [comment]
The google play version now uses a GUI installer, making the current issue useless.
Closing the issue.
