### ISSUE TITLE
[BUG] Black screen when installing Optifine 1.12.2 on PojavLauncher version 3.3.1.1

### ISSUE THREAD

**Issue by hienvanmine25** [PojavLauncherTeam/PojavLauncher#737]
**Describe the bug**
I installed forge 1.12.2 and I played the mod normally but I installed Optifine, then in the game, the screen went black but there was still game music.

**Platform:**
 - Device Model [e.g. OPPO A37fw 2GB Ram]
 - CPU architecture [e.g. aarch32] 
 - Android Version [e.g. 5.1.1]

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by hienvanmine25** [comment]
> Gửi mới nhấtlog.txt

--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms512m -Xmx768m"
Headless version detected! (20200412)
--------- beginning of main
I/jrelog  (23536): Starting logging STDIO as jrelog:V
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libjli.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x39d
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  (23536): WARNING: linker: libverify.so: unused DT entry: type 0x1d
I/jrelog  (23536):  arg 0x478
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): WARNING: linker: libverify.so: unused DT entry: type 0x6ffffffe arg 0xba4
I/jrelog  (23536): WARNING: linker: libverify.so: unused DT entry: type 0x6fffffff arg 0x1
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (23536): WARNING: linker: libjava.so: unused DT entry: type 0x1d arg 0x33c4
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): WARNING: linker: libjava.so: unused DT entry: type 0x6ffffffe arg 0x6308
I/jrelog  (23536): WARNING: linker: libjava.so: unused DT entry: type 0x6fffffff arg 0x2
I/jrelog  (23536): WARNING: linker: libnet.so: unused DT entry: type 0x1d arg 0x1251
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): WARNING: linker: libnet.so: unused DT entry: type 0x6ffffffe arg 0x25cc
I/jrelog  (23536): WARNING: linker: libnet.so: unused DT entry: type 0x6fffffff arg 0x2
I/jrelog  (23536): WARNING: linker: libnio.so: unused DT entry: type 0x1d arg 0x224c
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): WARNING: linker: libnio.so: unused DT entry: type 0x6ffffffe arg 0x4244
I/jrelog  (23536): WARNING: linker: libnio.so: unused DT entry: type 0x6fffffff arg 0x2
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x71ad
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffffe
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0xe0ec
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6fffffff
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x1
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt_headless.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0xa29
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt_headless.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffffe
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x14b0
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt_headless.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6fffffff
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x1
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfreetype.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffef5
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x118
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfreetype.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffffe
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x2dc8
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfreetype.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6fffffff
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x3
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so failed: dlopen failed: empty/missing DT_HASH in "libfreetype.so" (built with --hash-style=gnu?)
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfontmanager.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0xf02
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfontmanager.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffffe
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x1f9c
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfontmanager.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6fffffff
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x1
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so failed: dlopen failed: library "libfreetype.so.6" not found
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjsig.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjsig.so" is too small to be an ELF executable: only found 13 bytes
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt_xawt.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffef5
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x46bc
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt_xawt.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffffe
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x5c74
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libawt_xawt.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6fffffff
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x2
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libdt_socket.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x1ee
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfontmanager.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0xf02
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfontmanager.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffffe
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x1f9c
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libfontmanager.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6fffffff
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x1
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so failed: dlopen failed: library "libfreetype.so.6" not found
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libhprof.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x282
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libinstrument.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x3cd
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libinstrument.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6ffffffe
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x97c
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libinstrument.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x6fffffff
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x1
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): libj2gss.so
I/jrelog  (23536): : unused DT entry: type 
I/jrelog  (23536): 0x1d
I/jrelog  (23536):  arg 
I/jrelog  (23536): 0x6e9
I/jrelog  (23536): WARNING: linker: 
I/jrelog  (23536): Unsupported flags DT_FLAGS_1=
I/jrelog  (23536): 0x81
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success
I/jrelog  (23536): WARNING: linker: libj2pcsc.so: unused DT entry: type 0x1d arg 0x30e
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success
I/jrelog  (23536): WARNING: linker: libj2pkcs11.so: unused DT entry: type 0x1d arg 0xf05
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (23536): WARNING: linker: libjaas_unix.so: unused DT entry: type 0x1d arg 0xdf
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): WARNING: linker: libjava_crw_demo.so: unused DT entry: type 0x1d arg 0x10e
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so failed: dlopen failed: cannot locate symbol "awt_GetComponent" referenced by "libjawt.so"...
I/jrelog  (23536): WARNING: linker: libjawt.so: unused DT entry: type 0x1d arg 0xed
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): WARNING: linker: libjawt.so: unused DT entry: type 0x6ffffffe arg 0x38c
I/jrelog  (23536): WARNING: linker: libjawt.so: unused DT entry: type 0x6fffffff arg 0x1
I/jrelog  (23536): WARNING: linker: libjdwp.so: unused DT entry: type 0x1d arg 0x266
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
I/jrelog  (23536): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
I/jrelog  (23536): WARNING: linker: libjsdt.so: unused DT entry: type 0x1d arg 0x161
I/jrelog  (23536): WARNING: linker: Unsupported flags DT_FLAGS_1=0x81

**Comment by khanhduytran0** [comment]
Bạn ở build nào vậy?

**Comment by hienvanmine25** [comment]
> Bạn ở build nào vậy?

là sao bạn???

**Comment by khanhduytran0** [comment]
Ý mình hỏi phiên bản hiện tại của launcher ấy

**Comment by hienvanmine25** [comment]
> Ý mình hỏi phiên bản hiện tại của launcher ấy
bản v3.3.1.1 bạn.

**Comment by khanhduytran0** [comment]
Bạn thử gỡ runtime cài lại xem

**Comment by hienvanmine25** [comment]
> You try remove runtime reinstalling
ok bạn

**Comment by hienvanmine25** [comment]
> You try remove runtime reinstalling

vẫn bị thôi bạn

**Comment by hienvanmine25** [comment]
> You try remove runtime reinstalling

điện thoại mình 64bit nhưng Pojav lại chỉ được dùng file aarch32 nên mình phải tải bản noruntime

**Comment by khanhduytran0** [comment]
Nếu điện thoại 64bit mà hđh 32bit thì không thể chạy runtime 64bit.

**Comment by hienvanmine25** [comment]
> Nếu điện thoại 64bit mà hđh 32bit thì không thể chạy runtime 64bit.

mình tải bản có runtime thì khi tải phiên bản xong vào game thì bị thoát ra và hiện dòng chữ Launcher Process ID:....
(v3.3.1.1)

**Comment by khanhduytran0** [comment]
> Launcher Process ID

Cái đó là dành cho bên mình gỡ lỗi thôi. Không phải nguyên nhân crash

**Comment by Mathias-Boulay** [comment]
Stale issue that shouldn't happen with the google play release.
Closing the issue.
