### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chrwiss** [PojavLauncherTeam/PojavLauncher#738]
**Describe the bug**
I was playing on forge/optifine 1.12 
With the mod Dynamic Surrounding
Everything is fine but this glitch/bug is occurring with me

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected  it to work

**Screenshots**
![Screenshot_2021-01-27-21-29-38-70_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/78097997/106021728-1886ca80-60eb-11eb-9eb9-fd5c88889699.jpg)

**Platform:**
 - realme 5 pro 8gb variant
 -  aarch64
 - 10

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Try to reload resource or toggle full screen.

**Comment by khanhduytran0** [comment]
@chrwiss please reply?

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer from the author and no logs are provided.
Closing it.
