### ISSUE TITLE
[F-REQ] Read me please 

### ISSUE THREAD

**Issue by Leproromanianman** [PojavLauncherTeam/PojavLauncher#739]
Hi again 😀 my question is why sometimes minecraft is very laggy for no reasons and sometimes it run very well? I have 1600 ram (usable) and normally it runs with 40-30 fps , and says to me Pojavlauncher not respond (actually I click wait and it's not crashing it just continue running) 
AND  to the version 3.3.1.1 in game I literally can't click almost every time lol so I installed again 3.3.1 (older) .   It's funny I have a lot of questions 😃.

**Comment by Leproromanianman** [comment]
![Uploading Screenshot_20210127-203923.png…]()

**Comment by Leproromanianman** [comment]
![Uploading Screenshot_20210127-203923.png…]()

**Comment by khanhduytran0** [comment]
Maybe try decreasing the resolution?

**Comment by EXPress-016** [comment]
> Hi again 😀 my question is why sometimes minecraft is very laggy for no reasons and sometimes it run very well? I have 1600 ram (usable) and normally it runs with 40-30 fps , and says to me Pojavlauncher not respond (actually I click wait and it's not crashing it just continue running)
> AND to the version 3.3.1.1 in game I literally can't click almost every time lol so I installed again 3.3.1 (older) . It's funny I have a lot of questions 😃.

Try this jvm


-Xmx10g -Xms10g -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
