### ISSUE TITLE
Joining Server issue

### ISSUE THREAD

**Issue by Harel3** [PojavLauncherTeam/PojavLauncher#74]
Using Galasy S8 android 9
![Screenshot_20200409-171120_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/63358287/78878805-8e9b4180-7a85-11ea-979a-7503f7b8f822.jpg)
All i get is this im on minecraft 1.8.9
Premium btw

**Comment by khanhduytran0** [comment]
Android 6 or above you will get **Unable to fix RSA Padding** Without fix this, you will unable to join premium servers.

**Comment by WesleyVanNeck** [comment]
when will this be fixed?

**Comment by WesleyVanNeck** [comment]
or how do we fix

**Comment by matteobranchi** [comment]
> Android 6 or above you will get **Unable to fix RSA Padding** Without fix this, you will unable to join premium servers.

Can you join premium server with android 5 via VMOS?

**Comment by khanhduytran0** [comment]
Yes but I didn't test.
