### ISSUE TITLE
[F-REQ] It's just a question/ idea :D

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#740]
It's possible to make a extension on the launcher or even one "mini app" that runs minecraft java server?

**Comment by khanhduytran0** [comment]
Maybe.. or you can extract the app runtime to termux, then set `JAVA_HOME`, `LD_LIBRARY_PATH` then run regular java command and run Minecraft server on

**Comment by MateusL13** [comment]
> Maybe.. or you can extract the app runtime to termux, then set `JAVA_HOME`, `LD_LIBRARY_PATH` then run regular java command and run Minecraft server oso

So... I managed to run Minecraft server on pojav! But is very slow, mainly because my tablet is slow.
