### ISSUE TITLE
Help install Mods.

### ISSUE THREAD

**Issue by VT4LVBro** [PojavLauncherTeam/PojavLauncher#741]
It is not a problem or error, rather I need help to install mods, I have seen on YouTube that some install them as data packages and it would be very helpful if you could help me because I saw a video that uses the "Waila" Mod and also "ModMenu", in addition to the data packages they installed, which is called "RL Craft".

**Comment by khanhduytran0** [comment]
So, which part to help?

**Comment by VT4LVBro** [comment]
Add mods to minecraft, I have seen uni that has the "waila" mod and another
one that is jn datapack "RL Craft". How are the mods and datapacks
installed?

**Comment by matt995** [comment]
Bruh all you have to do is install forge or optifine,
Then move the mods or data packs into
Their folders.

**Comment by Mathias-Boulay** [comment]
Issue not related to pojavLauncher itself, closing it.
*but there are tutorials on youtube*
