### ISSUE TITLE
[BUG] libjvm.so fails to load

### ISSUE THREAD

**Issue by Janrupf** [PojavLauncherTeam/PojavLauncher#742]
**Describe the bug**
The `libjvm.so` fails to load on Android 5.1. Maybe this is due to an incompatible ELF version, in which case you may want to mark this as just not supported.

**To Reproduce**
1. Compile from source
2. Launch
3. Launcher crashes while trying to start the game

**Expected behavior**
The JRE should run fine.

**Platform:**
 - Device Model: Yoga Tablet 1050F
 - CPU architecture: x86_64 (Android x86-uefi)
 - Android Version: 5.1

See log below:
<details> <summary><b>Additional context</b></summary>
<br>
<pre>
I/jrelog: OpenJDK Server VM warning: 
    No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/jrelog: [0128/000358.832424:ERROR:elf_dynamic_array_reader.h(61)] tag not found
    [0128/000358.898211:ERROR:elf_dynamic_array_reader.h(61)] tag not found
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 14278 (Thread-3728)
I/KERNEL: [ 4046.199786] Thread-3728[14278]: segfault at 0 ip 00000000d20b640f sp 00000000d15c4ac0 error 6
     in libjvm.so[d1905000+c24000]
</pre>
</details>

**Comment by khanhduytran0** [comment]
Which component compiled from source?

**Comment by Janrupf** [comment]
Should be only the launcher, I did not manually set up a JVM build. The Android NDK was automatically bumped to revision 21, which worked just fine. If you think this causes the issue, I can try to downgrade it (but please give a bit more detailed instructions, since the suggested r10 can't be added just via gradle)

**Comment by Janrupf** [comment]
I might have also misinterpreted the error message, maybe libjvm.so itself loads correct, it just fails later down the line.

**Comment by khanhduytran0** [comment]
Could you send `/data/tombstone/<latest tombstone file that point to net.kdt.pojavlaunch>`? (If have root) it will contains the entire backtrace of all threads when crashes.

**Comment by Janrupf** [comment]
```
root@YT2:/ # ls /data/tombstone 
/data/tombstone: No such file or directory
```

**Comment by Janrupf** [comment]
Wait a second, missed an `s` there, will generate a new crash and then upload it

**Comment by khanhduytran0** [comment]
Okay, so you got 0x0 hmm

(Oh it's `tombstones`, but not `tombstone`)

**Comment by Janrupf** [comment]
(Had to attach .txt so Github lets me upload it)
[tombstone_00.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5883708/tombstone_00.txt)

**Comment by khanhduytran0** [comment]
Or could you take a try at [Action builds](https://github.com/PojavLauncherTeam/PojavLauncher/actions)?

**Comment by Janrupf** [comment]
I'm unable to get the debug log for the latest action build, attaching a debugger from within IntelliJ does just nothing. But got a tombstone for that one as well.
[tombstone_01.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5883720/tombstone_01.txt)

**Comment by khanhduytran0** [comment]
JVM for i386 is very experimental, no devs tested before, idk why it crashes.

Try to test JVM on command line
```
export JAVA_HOME=/data/data/net.kdt.pojavlaunch/jre_runtime
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/lib/i386/server:$JAVA_HOME/lib/i386/jli:$JAVA_HOME/lib/i386
export PATH=$PATH:$JAVA_HOME/bin
java -version
```
To see if java works?

**Comment by Janrupf** [comment]
That... makes sense:
```
root@YT2:/ # /data/data/net.kdt.pojavlaunch/jre_runtime/bin/java               
error: only position independent executables (PIE) are supported.
```

**Comment by Janrupf** [comment]
I'm not quite sure if the launch error and PIE thing are the same.

As stated in https://source.android.com/security/enhancements/enhancements50, since Android 5.0 every executable needs to be position independent in order to enhance security.

**Comment by Janrupf** [comment]
Managed to fix it to an extend:
```
root@YT2:/ # /data/data/net.kdt.pojavlaunch/jre_runtime/bin/java -version      
OpenJDK Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Segmentation fault 
[1] + Segmentation fault   /data/data/net.kdt.pojavlaunch/jre_runtime/bin/java -version 
```
It at least starts now, see here: https://github.com/Janrupf/android-openjdk-build-multiarch

But well, it still segfaults

**Comment by artdeell** [comment]
Just2Say: x86 (not_64) VM *should* work, but it can only alloczte 128M or less, and no one knows why

**Comment by Janrupf** [comment]
I mean, apparently it doesn't work. The tablet has an x86_64 CPU, but runs x86 Android. I'll need to find a proper way to debug this

**Comment by netkv** [comment]
maybe try install 64bit android if it have 64 bit cpu?

**Comment by Mathias-Boulay** [comment]
Stale issue from an old version, with no update from the author.
Closing

**Comment by Janrupf** [comment]
Oh yeah, for anyone reading through this issue: 
I simply forgot to close it, this bug has been fixed. The changes I made fixing this bug were merged into the JDK Pojav uses

**Comment by CriticalRange** [comment]
Lol I read everything then saw your message 😅
