### ISSUE TITLE
Fix Launchwapper to make Optifine Work

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#75]
Try to fix launchwrapper-of-2.1.jar to make Optifine work so we can't copy paste it anymore (This issue is for the Next Preview for pojavlauncher)

**Comment by khanhduytran0** [comment]
So I will modify this OptiFine LaunchWrapper and put to the launcher?

**Comment by FranzelDamasco909** [comment]
Based on the youtube video you uploaded

**Comment by khanhduytran0** [comment]
And also launcher_profiles.json?

**Comment by FranzelDamasco909** [comment]
Ok maybe that too

**Comment by FranzelDamasco909** [comment]
So if we installed the preview or launcher, we can have the fixed launcher_profiles.json and launchwrapper-of-2.1.jar?

**Comment by khanhduytran0** [comment]
> launchwrapper-of-2.1.jar?

Not added yet but will no longer required to place by hand in v3... (Not tested).

**Comment by FranzelDamasco909** [comment]
okay
