### ISSUE TITLE
[BUG] launcher not working

### ISSUE THREAD

**Issue by harsh-gupta-10** [PojavLauncherTeam/PojavLauncher#750]
When i try to play the launcher is not working it just start and the launcher stop and bring back me to app

https://user-images.githubusercontent.com/77847454/106182202-881cb880-61c4-11eb-8655-2635ffbe1265.mp4
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5889341/latestlog.txt)

Here the clip i recorded and latestlog.txt

I tryed this in different device
Pls fix this i am youtuber just want to play and make vidoes on PojavLauncher :)

**Comment by khanhduytran0** [comment]
Does older minecraft works?

**Comment by harsh-gupta-10** [comment]
> Does older minecraft works?

I tryed it dont work, I have 4gb ram phone

**Comment by khanhduytran0** [comment]
@IzooGGaming send latestlog.txt :eyes:

**Comment by Nishu-max** [comment]
I watched your YouTube videos and I thought you are good at these things but you're a noob.🤣🤣🤣🤣 oh no my device freezed while pojav launcher is running

**Comment by CriticalRange** [comment]
> I watched your YouTube videos and I thought you are good at these things but you're a noob.🤣🤣🤣🤣 oh no my device freezed while pojav launcher is running

Typical noobs

**Comment by mchnjt** [comment]
> I watched your YouTube videos and I thought you are good at these things but you're a noob.🤣🤣🤣🤣 oh no my device freezed while pojav launcher is running

*is this even a joke issue*

**Comment by Mathias-Boulay** [comment]
Stale issue (if we ignore the side chat) from an old version that uses a feature that isn't supported anymore.
Closing the issue.
