### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#752]
Cant Use Mouse!  While Game Starts!

**Comment by AgaricaGamer** [comment]
Uploading Screenrecording_20210129_112330.mp4…

**Comment by AgaricaGamer** [comment]
Cant Use Mouse!

**Comment by WesleyVanNeck** [comment]
more info woeld be nice also follow the template!!

**Comment by Zeyrox1090** [comment]
lol strict grandma

**Comment by Zeyrox1090** [comment]
lol jk sorry
