### ISSUE TITLE
[BUG]VIVO手机安卓七点击forge安装器闪退，我的手机是32位手机 

### ISSUE THREAD

**Issue by jjj273** [PojavLauncherTeam/PojavLauncher#753]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by jjj273** [comment]
Can't install forge, can't play the module, it's hard.

**Comment by artdeell** [comment]
Forge installer always crashes after finishing, it is normal.

**Comment by khanhduytran0** [comment]
Is this duplicates #736?

**Comment by jjj273** [comment]
我不是在完成后崩溃的。我是点击forge安装器闪退，你们根本就不知道我的意思。

**Comment by artdeell** [comment]
因为开发团队中没有人会说中文

**Comment by jjj273** [comment]
What I'm trying to say is that I click on the forge installer and it will flash back. My cell phone is a Vivo cell phone. The android version is 7. A 32-bit cell phone. Other cell phones don't flash back, but mine does. I use my own translation tool to talk to you.

**Comment by artdeell** [comment]
If forge version is older than 1.12, it is normal for it to just flash and crash. You should check your version list after that flash.

**Comment by jjj273** [comment]
pojavLauncher One of the options I clicked on that option. I clicked on the first one, and then I blacked out.You're missing my point.

**Comment by lijinhong11** [comment]
> 因为开发团队中没有人会说中文

那你们是怎么搞出中文的语言文件？翻译吗？

**Comment by jjj273** [comment]
唉

**Comment by CosineMath** [comment]
He means that forge installer will crash.

**Comment by artdeell** [comment]
Forge installer crashes are normal, you just need to check the version list after crash

**Comment by AgaricaGamer** [comment]
I m using the same phone 

Heres A Way It Might Can Get Fixed! 

•Reinstall The App(Make Sure You Delete all The Files Of It From The [Games/.minecraft Directory]

•Clean Some Of Your Storage!

**Comment by Mathias-Boulay** [comment]
Forge is now installed via the GUI installer on the google play release and don't crash like this anymore.
Closing issue
