### ISSUE TITLE
How to install "minecraft_server.jar" on PojavLauncher?

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#754]
**Is your feature request related to a problem? Please describe.**
How can we install "minecraft_server.jar" on PojavLauncher?

**Describe the solution you'd like**
I'd like PojavLauncher Developers to add server installer or anything.

**Describe alternatives you've considered**

**Additional context**

**Comment by LANCECRAFT1104** [comment]
I want to play servers but how to install "minecraft_sever.jar"

**Comment by OksmaWarez** [comment]
You can't. You can run the server.jar on your computer, and join it with the computer's IP.
And to join hypixel, mineberry or other servers, you don't need server.jar

**Comment by Zeyrox1090** [comment]
bruh lol your phone will crash

**Comment by WesleyVanNeck** [comment]
well 1 thing i say just dont

**Comment by MateusL13** [comment]
> **Is your feature request related to a problem? Please describe.**
> How can we install "minecraft_server.jar" on PojavLauncher?
> 
> **Describe the solution you'd like**
> I'd like PojavLauncher Developers to add server installer or anything.
> 
> **Describe alternatives you've considered**
> 
> **Additional context**

I managed to run Minecraft Server on pojav, but is very slow, but you can try!

**Comment by LANCECRAFT1104** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > How can we install "minecraft_server.jar" on PojavLauncher?
> > **Describe the solution you'd like**
> > I'd like PojavLauncher Developers to add server installer or anything.
> > **Describe alternatives you've considered**
> > **Additional context**
> 
> I managed to run Minecraft Server on pojav, but is very slow, but you can try!

@Mateus13000 How???

**Comment by MateusL13** [comment]
> > > **Is your feature request related to a problem? Please describe.**
> > > How can we install "minecraft_server.jar" on PojavLauncher?
> > > **Describe the solution you'd like**
> > > I'd like PojavLauncher Developers to add server installer or anything.
> > > **Describe alternatives you've considered**
> > > **Additional context**
> > 
> > 
> > I managed to run Minecraft Server on pojav, but is very slow, but you can try!
> 
> @Mateus13000 How???

You just have to put the "minecraft_server.jar" file in the .minecraft of the launcher, and when you enter in the launcher choose the mod installer option and go to the .minecraft and choose the minecraft_server.jar file, and your server is running!
I recommend to turn on the log output!!!
All server files will be generated on the .minecraft!!!

**Comment by Zeyrox1090** [comment]
yess slow

**Comment by MateusL13** [comment]
> yess slow

But you can try termux!

**Comment by Zeyrox1090** [comment]
i can host on my pc and play on pojav much more smoother

**Comment by denwahcode** [comment]
Yes ofc u can, but for me i just recommend using paper, or when u have a phone with better spec maybe u can try vanilla or fabric or whatever u want
