### ISSUE TITLE
попытка на русском

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#757]
пожалуйста добавьте переключатель для включения/выключения лкм и пкм с помощью нажатий на экран (не кнопок)

**Comment by Zeyrox1090** [comment]
yes add it cuz i keep placing blocks accidently

**Comment by SiergoMakatao** [comment]
Хорошая идея

**Comment by Zeyrox1090** [comment]
yes good idea

**Comment by ghost** [comment]
> yes add it cuz i keep placing blocks accidently

im tooooo

**Comment by Mathias-Boulay** [comment]
There is a similar behavior implemented through an option on the google play release.
Closing the issue.
