### ISSUE TITLE
v3无法安装forge，但可以正常安装fabric

### ISSUE THREAD

**Issue by AstroReality-Li** [PojavLauncherTeam/PojavLauncher#758]
**Describe the bug**
v3无法安装forge，但可以正常运行fabric

**To Reproduce**
1. 启动PojavLauncher
2. 选择1.12.2forge安装器
3. 进入安装页面不退出
4. 强制退出后应用闪退
5. 版本栏目中出现1.12.2forge版本，但无法运行

**Platform:**
 - Device Model [VIVO S5 8/128]
 - CPU architecture [ aarch64] 
 - Android Version 11

**Comment by Zeyrox1090** [comment]
v3 cannot install forge, but fabric can run normally

To Reproduce
Steps to reproduce the behavior:

Start PojavLauncher
Choose 1.12.2forge installer
Enter the installation page without exiting
App crashes after forced exit
1.12.2forge version appears in the version column, but it cannot run 



thats what he said lol google translated

**Comment by yejunjie10311031** [comment]
你说的“V3”是最新的Pojavlauncher V3.3.1.1还是旧版的V3？

**Comment by yejunjie10311031** [comment]
你在中国，但是Pojavlauncher下载forge资源是从forge官网下载的，forge官网是外国网站，你需要挂vpn，否则你会连接不上导致安装失败。

**Comment by yejunjie10311031** [comment]
你可以参考这个视频。

**Comment by AstroReality-Li** [comment]
> 你在中国，但是Pojavlauncher下载forge资源是从forge官网下载的，forge官网是外国网站，你需要挂vpn，否则你会连接不上导致安装失败。

v3.3.1.1可以安装1.12.2forge，但mod不能加多。
