### ISSUE TITLE
What is the use of "VMOS"???

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#760]
What is the use of VMOS????

**Comment by LANCECRAFT1104** [comment]
Is this like GeForce RTX or something.... Huh it says on YT it reduces the LAG

**Comment by Zeyrox1090** [comment]
bruh not here search on google or ask on discord the issues is not discord you know

**Comment by Zeyrox1090** [comment]
and its not gforce rtx

**Comment by Zeyrox1090** [comment]
ask google

**Comment by Zeyrox1090** [comment]
VMOS is a virtual machine app on Android, that can run another Android OS as the guest operating system. Users can optionally run the guest Android VM as a rooted Android OS. The VMOS guest Android operating system has access to the Google Play Store and other Google apps. VMOS was the first virtual machine for Android to support Google Play services and other Google apps.

**Comment by Zeyrox1090** [comment]
dont ask normal questions here just request or bug not other stuff

**Comment by Zeyrox1090** [comment]
just please request or bug only

**Comment by LANCECRAFT1104** [comment]
> just please request or bug only

Uh this is a question about the VMOS i saw it on PojavLauncher!!!

**Comment by khanhduytran0** [comment]
VMOS is no longer applied.
