### ISSUE TITLE
Can't resolve hostname. 2b2t.

### ISSUE THREAD

**Issue by QuasyStellar** [PojavLauncherTeam/PojavLauncher#764]
Все введено корректно, но все равно не работает. Лицензия куплена, интернет соединение есть, на другие сервера заходит.

**Comment by artdeell** [comment]
Включи точку доступа на мобилке.

**Comment by QuasyStellar** [comment]
> Включи точку доступа на мобилке.

Делал.

**Comment by artdeell** [comment]
Странно, у меня это чинило 2b...

**Comment by QuasyStellar** [comment]
Чел, я посмотрел у тебя на главной странице написано welcum, так и задумaно?

**Comment by stacode123** [comment]
No way u will get a hacked client work

**Comment by QuasyStellar** [comment]
> No way u will get a hacked client work

I install inertia. So i can play and i find error.

**Comment by TSaltedfishKing** [comment]
you must get 2b2t's server port
domain:port
SRV resolution is not supported

**Comment by QuasyStellar** [comment]
> you must get 2b2t's server port
> domain:port
> SRV resolution is not supported

How i can do it?

**Comment by stacode123** [comment]
https://www.site24x7.com/public/t/results-1578784632673.html

**Comment by Mathias-Boulay** [comment]
This issue of SVR support has been fixed on google play release.
Closing the issue.
