### ISSUE TITLE
[F-REQ] Turn back mouse scaling 25% to 250%

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#765]
**Is your feature request related to a problem? Please describe.**
Turn back mouse scaling to 25% to 250%.

**Describe the solution you'd like**
The mouse is too big!

**Describe alternatives you've considered**
Too big mouse can't click small buttons.

**Additional context**
![IMG_20210131_152037](https://user-images.githubusercontent.com/75970303/106377429-d8e30b80-6394-11eb-90b2-d79106740732.jpg)

**Comment by LANCECRAFT1104** [comment]
Hello PojavLauncherTeam turn back the mouse scaling to 25% to 250%.

**Comment by Zeyrox1090** [comment]
close the other one no dupes

**Comment by LANCECRAFT1104** [comment]
> close the other one no dupes

Hey you are you a Developer can you turn back the mouse scaling to 25% to 100% I don't want a big mouse I DONT WANT BIG MOUSE. I want a small mouse. Hey how about you you want a big mouse NO! anybody want a big mouse NO! Even me I don't want a big mouse I want 25% for me.

**Comment by artdeell** [comment]
he is not a dev
also, stop spamming issues

**Comment by Zeyrox1090** [comment]
lol
