### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#766]
**Is your feature request related to a problem? Please describe.**
Turn back mouse scaling to 25% to 250%.

**Describe the solution you'd like**
The mouse is too big!

**Describe alternatives you've considered**
Too big mouse can't click small buttons.

**Additional context**
![IMG_20210131_152037](https://user-images.githubusercontent.com/75970303/106377429-d8e30b80-6394-11eb-90b2-d79106740732.jpg)

**Comment by LANCECRAFT1104** [comment]
Duplicate

**Comment by Zeyrox1090** [comment]
bcuz if they go 99-1 mouse  will be smaller than atom lol

**Comment by LANCECRAFT1104** [comment]
I want 25%
