### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lijinhong11** [PojavLauncherTeam/PojavLauncher#768]
**Describe the bug**
Pojavlauncher 运行1.16.4未响应

**To Reproduce**
1. 打开启动器
2. 版本选择1.16.4(游戏之前已经下载了)
3. 运行游戏

**Screenshots**
没有

**Platform:**
 - Device Model 华为畅享10
 - CPU architecture arm64
 - Android Version 9

**Comment by netkv** [comment]
english please
