### ISSUE TITLE
I can't look while walking at the same time

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#77]
While i was walking, i can't touch look at the same time.

**Comment by khanhduytran0** [comment]
You can't move camera after hold control button. But you can touch camera (look) **first** and then hold control, it will work.

**Comment by FranzelDamasco909** [comment]
Yes i can't hold camera during holding arrow buttons. How to fix it? and how to change skin?

**Comment by khanhduytran0** [comment]
> Yes i can't hold camera during holding arrow buttons. How to fix it?

Release all touch, then hold camera before hold control button (including arrow buttons)

> and how to change skin?

There's no official way to do this. You could edit the jar file and replace skin png with your skin (sometimes it will Steve or Alex skin, it random)

**Comment by FranzelDamasco909** [comment]
ok thank you and the horse texture is not shown

**Comment by khanhduytran0** [comment]
> ok thank you and the horse texture is not shown

Maybe OpenGL or AWT, or unknown reason, banners have not texture too.

**Comment by FranzelDamasco909** [comment]
That banner too

**Comment by FranzelDamasco909** [comment]
how to fix?

**Comment by khanhduytran0** [comment]
Current there's no way to fix.

**Comment by FranzelDamasco909** [comment]
oh ok thank you

**Comment by FranzelDamasco909** [comment]
How to join multiplayer in Minecraft 1.11.2?

**Comment by slatinsky** [comment]
You can currently join online servers only on Android 5/6, "cracked" servers work fine on later Android versions.

**Comment by artdeell** [comment]
> how to fix?



> Current there's no way to fix.

Currently I'm attempting to embed Regal shim, and it may help.

**Comment by khanhduytran0** [comment]
> While i was walking, i can't touch look at the same time.

Check preview11b3
