### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kigbr** [PojavLauncherTeam/PojavLauncher#772]
I'm have a bug, my screen and my virtual mouse don't moving, I searching about this bug but This is very hard.
(Im from Brasil and my english is very bad, so Im sorry.)
HELP ME!!!

**Comment by kigbr** [comment]
help me, this problem is about the screen of the game

**Comment by WesleyVanNeck** [comment]
first of all folow the template also give some more info

**Comment by kigbr** [comment]
Ok, now im following your page?

**Comment by artdeell** [comment]
Can you record a video?

**Comment by WesleyVanNeck** [comment]
yeah maby screen record the issue

**Comment by kigbr** [comment]
Im using a aarch 32 bits..

**Comment by kigbr** [comment]
https://m.youtube.com/watch?v=SLMCQaFGUQM
Im record this video for send for you...

**Comment by khanhduytran0** [comment]
Grab mode broken?

**Comment by pstube** [comment]
I have the same problem.
pojavlauncher 3.3.1 and 3.3.1.1
Teclast M40
1.16.4
1.12.2

**Comment by khanhduytran0** [comment]
@kigbr @pstube Get latest build

**Comment by pstube** [comment]
I used the 5a11ba8  build, but I still have the same problem.

**Comment by Mathias-Boulay** [comment]
Stale issue with an old build and no answers from the author.
Closing it.
