### ISSUE TITLE
tmodloader for terraria on mobile 

### ISSUE THREAD

**Issue by serginfi** [PojavLauncherTeam/PojavLauncher#774]
(En)Please make please mod loader for terraria on android, it will be cool because you and your team make impossible: pc minecraft with PC MODS 
And also it will be more easilly then minecraft because terraria it is 2D game But If you make pc terraria with pc mods it will be soooo awesome
(Rus)Пожалуйста сделай загрузчик модов для террарии на андроид, это будет очень круто, потому что ты и твоя команда сделали невозможное: вы сделали пк майнкрафт с ПК МОДАМИ для андроид и также это будет проще чем делать пк майнкрафт, потому что террария- 2Д игра но если ты все же это сделаешь, тебе будут признательны люди по всему миру

**Comment by WesleyVanNeck** [comment]
no thnx also it sint impasable  playing modpacks

**Comment by artdeell** [comment]
Можно очень серьёзно пострадать, и запустить TML, но это будет ЕЩЁ медленнее. Потому количество измерений не имеет значений.

Алюс, мы изучали майн вдоль и поперёк чтоб это всё реализовать.

**Comment by serginfi** [comment]
Хорошо, спасибо, я понял
