### ISSUE TITLE
я буду добавлять это пока не увидят

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#777]
добавьте переключатель левого клика/правого клика с помощью нажатия на пустое место(не кнопки)

**Comment by ghost** [comment]
поверьте это очень мешает

**Comment by artdeell** [comment]
если будешь спамить мы отправим в блок на репозитории, а кнопки вообще-то можно убрать

**Comment by ghost** [comment]
вы меня не поняли, нажатия не на кнопки а на пустое место

**Comment by PeterScorPioN** [comment]
Да, он говорит про эту фишку, когда в игре, при нажатие на экран как бы срабатывает правый клик, соответственно и зажимая экран игрок начинает ломать блок. Было бы удобно выключать это, согласен.

**Comment by PeterScorPioN** [comment]
Но пожалуйста, без спама. Так тебя никак не услышат

**Comment by ghost** [comment]
а так хочется, я когда на сервере добывал незерит кучу раз умер из за этого

**Comment by Mathias-Boulay** [comment]
Duplicate from his own issue.
Closing it.
