### ISSUE TITLE
Resource pack don't work

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#78]
I was finding low end shaders on the web and i download and move to the file called "resourcepacks' in the launcher files(games>minecraft) and after i moved, i opened the game and i checked the Resource Packs and there was nothing

**Comment by khanhduytran0** [comment]
Shader pack you must put on shader folder instead of resource_packs folder

**Comment by FranzelDamasco909** [comment]
and can i install minecraft 1.12 on Launcher(Android 8.1)

**Comment by khanhduytran0** [comment]
No at the moment.

**Comment by FranzelDamasco909** [comment]
> Shader pack you must put on shader folder instead of resource_packs folder
What's the file path of Shader folder

**Comment by FranzelDamasco909** [comment]
> No at the moment.

Maybe i'm gonna try to increase DX references

**Comment by khanhduytran0** [comment]
/storage/emulated/0/games/minecraft/shaderpacks

**Comment by FranzelDamasco909** [comment]
okay thank you!

**Comment by FranzelDamasco909** [comment]
it still doesn't work

**Comment by khanhduytran0** [comment]
You must install optifine to install shader but optifine reject all shaders due to missing OpenGL 2.0

**Comment by FranzelDamasco909** [comment]
wait can i install Minecraft 1.12 by increasing DX references

**Comment by khanhduytran0** [comment]
You can install but you can't launch.

**Comment by FranzelDamasco909** [comment]
when will it work?

**Comment by khanhduytran0** [comment]
There's no eta for this, it might tomorrow, or some weeks...

**Comment by FranzelDamasco909** [comment]
you said that it will support (Past)-1.12 =_=

**Comment by FranzelDamasco909** [comment]
> There's no eta for this, it might tomorrow, or some weeks...

ok

**Comment by khanhduytran0** [comment]
I recently changed the message.

**Comment by FranzelDamasco909** [comment]
lol ok
