### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kigbr** [PojavLauncherTeam/PojavLauncher#780]
Im sending my bug again...
My screen and the virtual mouse on pojav launcher don't moving...
Video of this bug
https://m.youtube.com/watch?v=SLMCQaFGUQM

**Comment by kigbr** [comment]
Im using a aarch 32 on android 8

**Comment by WesleyVanNeck** [comment]
then dont dont use mouse thing follow the issue template

**Comment by WesleyVanNeck** [comment]
also stop spaming issues

**Comment by WesleyVanNeck** [comment]
dubicated of #772
