### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bakclajv** [PojavLauncherTeam/PojavLauncher#782]
No puedo iniciar versiones superiores a 1.13 me muestra un error que dice que la aplicación/juego ha finalizado con el codigo 

![Screenshot_20210201-140707](https://user-images.githubusercontent.com/78379540/106505891-eed8f500-6496-11eb-8001-cff11f1ff52d.png)

 - Device Model huawei 9 lite
 - CPU architecture kirim 655
 - Android Version 7.0

**Comment by WesleyVanNeck** [comment]
@bakclajv english

**Comment by bakclajv** [comment]
I can't star the game for that error, the error show when i want to play versions aren't 1.13

My english is very bad sorry
