### ISSUE TITLE
[BUG] [1.16.5] Can't move player using Physical keyboard

### ISSUE THREAD

**Issue by F0x06** [PojavLauncherTeam/PojavLauncher#783]
**Describe the bug**
Using WSAD keys on physical keyboard connected via USB doesn't move the player

PojavLauncher version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/527401505

**To Reproduce**
1. Plug a physical keyboard using USB adapter
2. Start the game and load a world
3. Try to move using WSAD

**Expected behavior**
I expect the player to move

**Additional notes**
Some keys like SHIFT (sneak) are working

**Platform:**
 - Device Model Samsung Galaxy Note 9
 - CPU architecture aarch64
 - Android Version 10

**Comment by khanhduytran0** [comment]
Try press “Keyboard” before use keyboard.

**Comment by F0x06** [comment]
> Try press “Keyboard” before use keyboard.

Thanks I'll try that tomorrow :)

**Comment by F0x06** [comment]
Tried just now, same issue, the visual keyboard shows in front of screen and i'm not able to move.

**Comment by F0x06** [comment]
Also tested with Vanilla 1.16.5 exact same issue.

**Comment by khanhduytran0** [comment]
@serpentspirale maybe your cleanup broke them?

**Comment by Mathias-Boulay** [comment]
@khanhduytran0 Let me take a look, pretty sure I did not touch anything related to controls.

**Comment by Mathias-Boulay** [comment]
The issue is here, even before the cleanup 😓 
Tested with this auto build from before the cleanup: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/525690663

**Comment by F0x06** [comment]
Any updates about the issue ?

**Comment by khanhduytran0** [comment]
We can't reproduce your problem. Could you give info about the tested keyboard? Model? Does OTG supported/enabled(?)?

**Comment by Mathias-Boulay** [comment]
@khanhduytran0 I did reproduce the issue with my keyboard though. 🤔 
I just don't know the hell how to fix it.

**Comment by F0x06** [comment]
> We can't reproduce your problem. Could you give info about the tested keyboard? Model? Does OTG supported/enabled(?)?

I tested with a OTG keyboad first time (Logitech G910), tested today with a bluetooth keyboatd (Razer BlackWidow V3 Pro) same issue on the latest CI build 

Keyboard layout used: QWERTZ (FR-CH) Pretty close to US layout

**Comment by artdeell** [comment]
I can say: something's wrong with your device config. Visual keyboard should never show when a hardware keyboard is attached.

**Comment by F0x06** [comment]
> I can say: something's wrong with your device config. Visual keyboard should never show when a hardware keyboard is attached.

It only shows when i click the "Keyboard" button, @serpentspirale do you have the same behavior ?

Edit: Maybe because i use SwiftKey ? In all other apps the keyboard works just fine

**Comment by Mathias-Boulay** [comment]
Aosp keyboard here.
It doesn't show up when I click the keyboard button while having a physical one connected.

**Comment by F0x06** [comment]
So, i tested with my GF Galaxy S8+ (Stock ROM, non-root) exact same issue:
Bluetooth keyboard connected,
Samsung keyboard shows when pressing "Keyboard" button
Not able to move

Keyboard worls fine in other applications.

Edit: Need to test via USB-OTG also.

**Comment by F0x06** [comment]
So, i tested via USB-OTG exact same issue, i tested some other things:

-  Re-mapped WSAD default keys in MC to numpad to move player: **Works**
- I can open the chat and type anything without issues

Also nothd that SPACE key have the same issues as WSAD.

@khanhduytran0 Which firmware/device are you using ? Do you have access to a stock firmware samsung to test for example ? Apparently @serpentspirale has reproduced the issue also.

Question to devs: Do you have any code that relies on WSAD/SPACE key and can interfer with the physical keyboard ? I mean like the GUI buttons code, or maybe on the JNI side ?

**Comment by Toothyy** [comment]
Theory: This is somewhat close to this problem but there is no built in mouse either the its the one built in to your phone could this a reason for this?

**Comment by F0x06** [comment]
> Theory: This is somewhat close to this problem but there is no built in mouse either the its the one built in to your phone could this a reason for this?

I don't really understand what you mean, you said mouse, do you mean keyboard? Can you elaborate? My phone is a tactile one, no physical keyboard by default. And there is no issues with mouse.

**Comment by Toothyy** [comment]
I did mean to say mouse but what I was saying that it is using the built-in mouse on your phone ,my theory was that if you make a mouse and keyboard for the game would it work, not for the gui just for the physical stuff

**Comment by F0x06** [comment]
> I did mean to say mouse but what I was saying that it is using the built-in mouse on your phone ,my theory was that if you make a mouse and keyboard for the game would it work start work not for the gui just for the physical stuff

Tried to connect both mouse and keyboard through USB-OTG, exact same issue, however the mouse works fine.

**Comment by Toothyy** [comment]
Yes I know the only problem I have is that the keyboard doesn't work for me, tried to remap the keybinds to any button and it doesn't work

**Comment by Toothyy** [comment]
Any updates for this keyboard problem?

**Comment by parkerlreed** [comment]
Same here on a Galaxy S9 with Dex. If I use a USB keyboard and mouse separate on a hub I can control Minecraft.

If I use a Bluetooth keyboard or a Logitech on a Unifying dongle, it completely ignores the keyboard input (menus and game). Using the latest 3.x from the releases page.

Minecraft 1.16.2

**Comment by Toothyy** [comment]
Yes there is a problem with otg and Bluetooth at the moment don't know when they'll fix it

**Comment by Toothyy** [comment]
Still not fixed sadge

**Comment by F0x06** [comment]
Still no updated on the issue ? @khanhduytran0 

Thanks.

**Comment by Mathias-Boulay** [comment]
@F0x06 can you test if the issue is still present with latest action builds ?

**Comment by F0x06** [comment]
Yes of course, I'll test that tomorrow, thanks!

**Comment by F0x06** [comment]
> @F0x06 can you test if the issue is still present with latest action builds ?

Which version do you mean exactly by `action builds` ? The CI version or Google Play one ?
I tried with the google play one still having issues

Link me directly an apk, or give me the branch/commit so i can compile the app myself
Thanks

Additional notes: on Google play version using mc 1.7.10, i can only move using WSAD while holding CTRL
On version 1.16.5, it's the same, except W and S are reversed

Tested via Bluetooth and USB

**Comment by Mathias-Boulay** [comment]
@F0x06 only github has action builds, I will link you to one later today.
Thanks for the quick and precise reporting with the google play version though 👍

**Comment by Mathias-Boulay** [comment]
@F0x06 
Here, you can use the build at this link : https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/901821231
Just take the ~60MB apk

**Comment by StarfireHunter** [comment]
> @F0x06
> Here, you can use the build at this link : https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/901821231
> Just take the ~60MB apk

@Mathias-Boulay 
When will this update hit google play? or is there a way to download the apk already? (Im not familiar with github, i apologise)

**Comment by Mathias-Boulay** [comment]
@mastalol when we feel like it is good enough.

@F0x06 so ? 👀

**Comment by F0x06** [comment]
I'll test it today and post the results 👍

**Comment by F0x06** [comment]
> @mastalol when we feel like it is good enough.
> 
> @F0x06 so ? 👀

So,

Tested Both via USB and Bluetooth

1.7.10: Can't move using WSAD, only moving when holding CTRL, for example if i hold `W` with `CTRL` then release `CTRL` the player move endlessly forward (drifting)

1.16.5: Same as 1.7.10 (see above)

Additional notes: I can type without issues in main menu for example World name or using `TAB` key to navigate menus, also ingame inventory key `i` works.

**Comment by StarfireHunter** [comment]
if i may, I removed all the keys that overlay my game, using a microsoft keyboard on a samsung galaxy tab s6 it seems to work without ctrll (when previously it required it)

@F0x06 have you tried removing all the buttons from the screen?

**Comment by F0x06** [comment]
> if i may, I removed all the keys that overlay my game, using a microsoft keyboard on a samsung galaxy tab s6 it seems to work without ctrll (when previously it required it)
> 
> @F0x06 have you tried removing all the buttons from the screen?

Nope, i'll try that now, makes sense, this feels like a key conflict to me

**Comment by F0x06** [comment]
> if i may, I removed all the keys that overlay my game, using a microsoft keyboard on a samsung galaxy tab s6 it seems to work without ctrll (when previously it required it)
> 
> @F0x06 have you tried removing all the buttons from the screen?

Removed all the overlay buttons, same issue for me :/

**Comment by mastalol** [comment]
well if it makes a difference i do have a random error showing in my log
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6630662/latest.log)

**Comment by Mathias-Boulay** [comment]
I'm out of ideas for now, I'll most likely look into this in the future though.

**Comment by StarfireHunter** [comment]
So I had it working perfectly, not sure how, I had to reset my tablet due to an update bug, and when I did, it's back to how the issue is above. I transferred all my stuff from the old pojav launcher mojang installation, so I'm not sure why.

I will keep trying things one by one till I recreate the perfect setup again, I'll report my findings.

**Comment by SPF79** [comment]
Hi guys,

I came across this issue today as well and I noticed a weird effect, which might give you a clue to the root of the problem:

The WASD behaviour is pretty much the same with my BT-keyboard and mouse on my Galaxy Tab G5e, with one anomaly, that has not been mentioned yet. EDIT: I have M$ SwiftKey installed as well btw.

When I press and hold a ctrl- or alt-key everything is pretty much back to normal. Also pressing E for the inventory and shift to duck as well as all function keys are working.

Can somebody confirm it and if yes, can you guys make something out of that?

Cheers

**Comment by Mathias-Boulay** [comment]
Hi @SPF79, thanks for reporting this.
Some people had similar cases to yours, but we have yet to get to the root of the problem.

If this issue still happens with the current dev builds, contact the devs on the official discord server to do some more testing with dedicated debug builds.

**Comment by SPF79** [comment]
Actually, I fixed it for my device. It is most likely not your implementation, but the horrid Samsung OS.

1. I disabled SwiftKey and Google Voice input so that Samsung Keyboard has to be used.
2. I disabled all assistance options in the Samsung Keyboard options.
3. I updated the Accessibility component via Samsung Store to the latest version  and turned off everything that seemed to autonomous / dodgy in this regard.

Result: Perfect keyboard + mouse input to Minecraft via your latest debug release with forge for MC 1.16.5 and OptiForge + half a dozen other mods. FPS after tweaking Optifine and resolution drop by 100 (I guess these are percent) on my Galaxy Tab S5e 20-40 in the mean... :( But it's working and very playable.

EDIT (speed type typo): Thank you for the great work, btw. I really appreciate it.

Cheers from Bremen

**Comment by Mathias-Boulay** [comment]
At this rate, we'll never get a buggy setup to test things on 🤔

**Comment by SPF79** [comment]
Mate, this is the curse of software development. Complexity cannot be reduced. Our kind is doomed to find the needle in the haystack without any efficient approach to deductive logic and reason. Welcome to my world.

Spoken as test manager for combat direction systems.

Hang in there. I love you guys, cause you make the upbringing of my kids a lot more enjoyable.

Cheers

**Comment by Mathias-Boulay** [comment]
@SPF79 About the third step: 
> I updated the Accessibility component via Samsung Store to the latest version and turned off everything that seemed to autonomous / dodgy in this regard.

Can you list or screenshot the said settings ?
It could help us narrowing reproducing a similar setup with some testers 😅

**Comment by SPF79** [comment]
> Can you list or screenshot the said settings ?
> It could help us narrowing reproducing a similar setup with some testers 😅

If I get around to it... (would a brit say).

Sure mate, I'll do my best. Don't get to enthralled in this, though. Which is my professional opinion. Lineage OS (from all that I experiences) would not be a problem in the first instance. Pick your battles.

But yes, of course, I will contribute a screeny of the abysmal Samsung OS "fix".

Cheers

**Comment by CriticalRange** [comment]
I might be in a wrong conversation but
I'm using LineageOS and don't have any problem

**Comment by SPF79** [comment]
Alright, here are the screenshots. Some settings are probably overkill, but that setup works.

![Screenshot_20210811-094222_VLC](https://user-images.githubusercontent.com/39671256/128992551-850d6c4f-df1e-4755-86e4-6eb2908e2d5a.jpg)
![Screenshot_20210811-094245_VLC](https://user-images.githubusercontent.com/39671256/128992666-d1431168-6a93-4c99-8a0d-35d4d264c18b.jpg)
![Screenshot_20210811-094310_VLC](https://user-images.githubusercontent.com/39671256/128992670-ba85fb25-6887-48ca-ab8c-ee8c8e2ca869.jpg)
![Screenshot_20210811-094332_VLC](https://user-images.githubusercontent.com/39671256/128992673-161acb5a-978c-473f-a620-16670d38e19e.jpg)
![Screenshot_20210811-094349_VLC](https://user-images.githubusercontent.com/39671256/128992675-ec8fba9c-337d-47be-ac1f-26afa003c3c5.jpg)
![Screenshot_20210811-094409_VLC](https://user-images.githubusercontent.com/39671256/128992676-d752651e-0243-4373-8266-f85ec824c544.jpg)
![Screenshot_20210811-094537_VLC](https://user-images.githubusercontent.com/39671256/128992677-eb82501e-dc6c-4d80-9d9c-c13b6a3e6dec.jpg)
![Screenshot_20210811-094606_VLC](https://user-images.githubusercontent.com/39671256/128992678-8a343fb7-de31-4502-abe7-b75add704b29.jpg)
![Screenshot_20210811-094647_VLC](https://user-images.githubusercontent.com/39671256/128992679-437ca965-e373-4c44-be96-143df903e2a5.jpg)
![Screenshot_20210811-094711_VLC](https://user-images.githubusercontent.com/39671256/128992680-d1db223c-1e55-4711-bebc-966ff6372fb7.jpg)
![Screenshot_20210811-094731_VLC](https://user-images.githubusercontent.com/39671256/128992685-caa3e0e2-2ad9-4a08-9313-5ff01bab1b31.jpg)
![Screenshot_20210811-094823_VLC](https://user-images.githubusercontent.com/39671256/128992687-7d43fba5-f66b-4776-ad9a-bc27bb933561.jpg)
![Screenshot_20210811-094915_VLC](https://user-images.githubusercontent.com/39671256/128992690-d77b3b2f-035b-4f40-8059-3578fbab0faf.jpg)
![Screenshot_20210811-095058_VLC](https://user-images.githubusercontent.com/39671256/128992691-389016a4-a34b-4928-aa3c-cf0d77795bc3.jpg)
![Screenshot_20210811-095123_VLC](https://user-images.githubusercontent.com/39671256/128992694-526cc552-61b1-4ce3-8a7a-f931dbb1bd82.jpg)

**Comment by Mathias-Boulay** [comment]
Since the crocus update, any bugs that are left keyboard wise cannot be fixed by us since it is device specific.
Closing.

**Comment by Parthissmart** [comment]
My keyboard also wasd keys do not work :/ and also space bar do not work.

Hope u reply

**Comment by SPF79** [comment]
Reply: Please read through the thread.

**Comment by Darkito74** [comment]
For everybody who have the same issue I found the problem and solution.

1-the problem is happening because the input that servers support to move is key code (not text like W) the pojavlauncher is automatically changing your "usb keyboard input texts" to the supported key codes in "single player", but not in the servers because the app can not rewrite the server input software. 

2-you just have to change input settings in your phone from SwiftKey to a custom one (I recommend AOSP Keyboard) just download it, change the settings and connect your usb keyboard. (AOSP KEYBOARD is basically for WiFi keyboards but you can use it with usb ones)

**Comment by artdeell** [comment]
I dunno about the problem because minecraft doesn't split input systems. And, if you looked at the F3 menu, you may havealready noticed that singleplayer is just a server and client looping back onto eachother

**Comment by SPF79** [comment]
It does make sense, because I tried to play, y connecting to my raspbian-based server, to provide a multiplayer experience for my kids. I never tried to play single player.

The second to last post by @Darkito74 semms to be quite likely the explanation.

Can people confirm who didn't have any issues in the first place, that they persude merely single player games?

**Comment by Aboodal7asan** [comment]
I have the same issue with the keyboard but I have another issue with the mouse. The mouse buttons works fine but when I move the camera it moves like the game is running at 3 fps but it's actually above 60 fps. Sorry for that description about the mouse issue but that is the closest thing I can describe.

**Comment by Darkito74** [comment]
What is it?

**Comment by Darkito74** [comment]
When you move mouse in normal phone screen does it move smoothly?

**Comment by Aboodal7asan** [comment]
No it barley moves 
Like it is jumping from place to place 
Making it looks like it's running on 3 FPS

**Comment by Darkito74** [comment]
What about touching does it have the same issue?

**Comment by Aboodal7asan** [comment]
All touch controls works fine

**Comment by Darkito74** [comment]
I mean when you use your fingers to move screen does it work fine?

**Comment by Aboodal7asan** [comment]
Yeah anything touch related works fine

**Comment by Aboodal7asan** [comment]
Someone is having the same issue as me 
https://github.com/PojavLauncherTeam/PojavLauncher/issues/1227
And he Linked a YT video

**Comment by GoneSubject** [comment]
> Someone is having the same issue as me #1227 And he Linked a YT video

they fixed that i think

**Comment by ddmgh** [comment]
For what it’s worth, I had this same issue and it was related to my Tecware keyboard.  Evidently, this is a “feature” of this keyboard.  Fn+W will swap the WASD keys with the arrow keys—and hitting Fn+W will swap them back.

Hope this helps someone!

**Comment by Aboodal7asan** [comment]
Fixed long ago
My default system keyboard was SwiftKey keyboard changing the default system keyboard to Google keyboard fixes the issue
