### ISSUE TITLE
----Minecraft Crash Report----

### ISSUE THREAD

**Issue by 555LPWRCDV** [PojavLauncherTeam/PojavLauncher#784]
// Surprise! Haha. Well, this is awkward.

Time: 2/2/21 2:04 AM
Description: Unexpected error

java.lang.NoSuchMethodError: org.lwjgl.opengl.ARBVertexShader.glVertexAttribPointerARB(IIZZILjava/nio/ShortBuffer;)V
	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
	at bmh.a(Tessellator.java:169)
	at shadersmod.client.Shaders.drawHorizon(Shaders.java:4862)
	at shadersmod.client.Shaders.preSkyList(Shaders.java:4874)
	at bma.a(RenderGlobal.java:1731)
	at blt.a(EntityRenderer.java:1616)
	at blt.b(EntityRenderer.java:1392)
	at bao.ak(SourceFile:801)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
	at bmh.a(Tessellator.java:169)
	at shadersmod.client.Shaders.drawHorizon(Shaders.java:4862)
	at shadersmod.client.Shaders.preSkyList(Shaders.java:4874)
	at bma.a(RenderGlobal.java:1731)
	at blt.a(EntityRenderer.java:1616)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bjk['LancEYTStudioZ'/50, l='MpServer', x=-774.50, y=5.62, z=1502.50]]
	Chunk stats: MultiplayerChunkCache: 25, 34
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-771,4,1505), Chunk: (at 13,0,1 in -49,94; contains blocks -784,0,1504 to -769,255,1519), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Level time: 3 game time, 3 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [bjk['LancEYTStudioZ'/50, l='MpServer', x=-774.50, y=5.62, z=1502.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bjf.a(WorldClient.java:425)
	at bao.b(SourceFile:1972)
	at bao.f(SourceFile:742)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version Android-8.1.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 918067192 bytes (875 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 26 total; -Xmx1G -Xms1G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10 -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/StubDrawGlyphList.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/xml-libs-pack.jar
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Filipino (Pilipinas)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

Filipino: Di pa ata gumagana shaders.
English: I think shaders still not working.

**Comment by 555LPWRCDV** [comment]
Di na nga ako gagamit ng shader

**Comment by LANCECRAFT1104** [comment]
May filipino ba d2 or English lang?

**Comment by Zeyrox1090** [comment]
wala po

**Comment by 555LPWRCDV** [comment]
> wala po

Ikaw

**Comment by 555LPWRCDV** [comment]
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 2/2/21 2:04 AM
> Description: Unexpected error
> 
> java.lang.NoSuchMethodError: org.lwjgl.opengl.ARBVertexShader.glVertexAttribPointerARB(IIZZILjava/nio/ShortBuffer;)V
> at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
> at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
> at bmh.a(Tessellator.java:169)
> at shadersmod.client.Shaders.drawHorizon(Shaders.java:4862)
> at shadersmod.client.Shaders.preSkyList(Shaders.java:4874)
> at bma.a(RenderGlobal.java:1731)
> at blt.a(EntityRenderer.java:1616)
> at blt.b(EntityRenderer.java:1392)
> at bao.ak(SourceFile:801)
> at bao.f(SourceFile:728)
> at net.minecraft.client.main.Main.main(SourceFile:148)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- Head --
> Stacktrace:
> at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
> at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
> at bmh.a(Tessellator.java:169)
> at shadersmod.client.Shaders.drawHorizon(Shaders.java:4862)
> at shadersmod.client.Shaders.preSkyList(Shaders.java:4874)
> at bma.a(RenderGlobal.java:1731)
> at blt.a(EntityRenderer.java:1616)
> 
> -- Affected level --
> Details:
> Level name: MpServer
> All players: 1 total; [bjk['LancEYTStudioZ'/50, l='MpServer', x=-774.50, y=5.62, z=1502.50]]
> Chunk stats: MultiplayerChunkCache: 25, 34
> Level seed: 0
> Level generator: ID 01 - flat, ver 0. Features enabled: false
> Level generator options:
> Level spawn location: World: (-771,4,1505), Chunk: (at 13,0,1 in -49,94; contains blocks -784,0,1504 to -769,255,1519), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
> Level time: 3 game time, 3 day time
> Level dimension: 0
> Level storage version: 0x00000 - Unknown?
> Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> Forced entities: 1 total; [bjk['LancEYTStudioZ'/50, l='MpServer', x=-774.50, y=5.62, z=1502.50]]
> Retry entities: 0 total; []
> Server brand: vanilla
> Server type: Integrated singleplayer server
> Stacktrace:
> at bjf.a(WorldClient.java:425)
> at bao.b(SourceFile:1972)
> at bao.f(SourceFile:742)
> at net.minecraft.client.main.Main.main(SourceFile:148)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> Minecraft Version: 1.7.10
> Operating System: Linux (aarch64) version Android-8.1.0
> Java Version: 1.8.0-internal, Oracle Corporation
> Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
> Memory: 918067192 bytes (875 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
> JVM Flags: 26 total; -Xmx1G -Xms1G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10 -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/StubDrawGlyphList.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/xml-libs-pack.jar
> AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> Launched Version: 1.7.10
> LWJGL: 3.2.3 SNAPSHOT
> OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
> GL Caps: Using GL 1.3 multitexturing.
> Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
> Anisotropic filtering is supported and maximum anisotropy is 16.
> Shaders are available because OpenGL 2.1 is supported.
> 
> ```
> Is Modded: Very likely; Jar signature invalidated
> Type: Client (map_client.txt)
> Resource Packs: []
> Current Language: Filipino (Pilipinas)
> Profiler Position: N/A (disabled)
> Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> Anisotropic Filtering: Off (1)
> ```
> 
> Filipino: Di pa ata gumagana shaders.
> English: I think shaders still not working.

PojavLauncherTeam, Anong Nangyari D2? (What happen?)

**Comment by khanhduytran0** [comment]
Which build??

**Comment by 555LPWRCDV** [comment]
Build??

**Comment by pablodz** [comment]
> Build??

Which release version did you installed ? There are several of them.

**Comment by khanhduytran0** [comment]
Duplicate #642
