### ISSUE TITLE
Tga texture gone white

### ISSUE THREAD

**Issue by Beam195** [PojavLauncherTeam/PojavLauncher#785]
**Describe the bug**
some texture such as sheep tropicalfish grass block gone white.

**To Reproduce**
1. Start PojavLauncher
2. And then their textures are white

**Platform:**
 - Device Model: huawei y9 2019
 - CPU architecture: Hisilicon Kirin 710
 - Android Version 9

**Comment by WesleyVanNeck** [comment]
known issue read the readme

**Comment by WesleyVanNeck** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher#known-issues
