### ISSUE TITLE
[BUG]Error code 1 while booting minecraft

### ISSUE THREAD

**Issue by stacode123** [PojavLauncherTeam/PojavLauncher#788]
**Describe the bug**
Eee when I tried to run 1.12.2 or 1.16.4 both of them just gave an error code 1 with no log

**To Reproduce**
1. Start PojavLauncher
2.run 1.12.2 or 1.16.4 
3. get error codr

...

**Expected behavior**
I expected ...

**Screenshots**
![Screenshot_20210202-203311.jpg](https://user-images.githubusercontent.com/49679054/106653315-e962d400-6596-11eb-9378-de887302ae56.jpg)

**Platform:**
 - Device Model [huawei p10]
 - CPU architecture [dont know how to get it] 
 - Android Version [8]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
launcher version?

**Comment by stacode123** [comment]
> launcher version?

Newest stable
3.3.1.1

**Comment by khanhduytran0** [comment]
What about log?

**Comment by stacode123** [comment]
no came out

**Comment by stacode123** [comment]
after i click ok and check the logs it says no log.
same with crash report

**Comment by khanhduytran0** [comment]
Development console ≠ latestlog.txt

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer from author
Closing
