### ISSUE TITLE
[BUG]Texture Bug

### ISSUE THREAD

**Issue by QingSi180** [PojavLauncherTeam/PojavLauncher#790]
**Describe the bug**
When I play the game,the texture is completely lost,with nothing seen.

**To Reproduce**
1. Start PojavLauncher
2.Start the game
3.The texture is lost.

**Expected behavior**
I expected that the texture can be seen normally.

**Screenshots**
![Screenshot_20210201-093117.jpg](https://user-images.githubusercontent.com/29775473/106705373-ca148700-6628-11eb-845a-18e0b76fad2c.jpg)
**Platform:**
 - Device Model [Oneplus 6T 8/128]
 - CPU architecture [aarch64] 
 - Android Version [9]

**Comment by QingSi180** [comment]
It only happened in First person view.

**Comment by Zeyrox1090** [comment]
maybe its the texture pack problem
not pojav
try removing texture packs

**Comment by QingSi180** [comment]
> maybe its the texture pack problem
> not pojav
> try removing texture packs
> 

I have tried that,but that didn't work.

**Comment by khanhduytran0** [comment]
What about Minecraft version?
What about jvm agruments?

**Comment by QingSi180** [comment]
> What about Minecraft version?
> What about jvm agruments?

The version is 1.12.2
The jvm arguments are -Xms512m -Xmx800m

**Comment by khanhduytran0** [comment]
Hmm. Does vanilla works?

**Comment by QingSi180** [comment]
> Hmm. Does vanilla works?

It doesn't work.The texture is always white…

**Comment by WesleyVanNeck** [comment]
known on modded

**Comment by QingSi180** [comment]
> known on modded 

Could it be fix in the future?

**Comment by Mathias-Boulay** [comment]
Nope, as it is a VRAM specific issue.
Closing the issue, as it isn't pojav fault.
