### ISSUE TITLE
I found a problem, my phone is Vivo Z3 Snapdragon 710 why I play every new integration package, the first time to create the world to play after the exit, the second time to play, can not go into, but also crash, flash back.... There can be a button debugging button can be added up and down around the way to move, otherwise, with the hand is not easy to align the keys look very uncomfortable 😫

### ISSUE THREAD

**Issue by jianlin-15** [PojavLauncherTeam/PojavLauncher#791]

**Comment by OksmaWarez** [comment]
english please

**Comment by jianlin-15** [comment]
I found a problem, my phone is Vivo Z3 Snapdragon 710 why I play every new integration package, the first time to create the world to play after the exit, the second time to play, can not go into, but also crash, flash back.... There can be a button debugging button can be added up and down around the way to move, otherwise, with the hand is not easy to align the keys look very uncomfortable 😫

**Comment by QingSi180** [comment]
这……

**Comment by jianlin-15** [comment]
Sorry, I can't use English very well, I use a translation software, I wonder if you can understand

**Comment by jianlin-15** [comment]
> 这……

额……

**Comment by jianlin-15** [comment]
> 这……

老哥你知道第一次玩整合包进去没事，第二次进去就会崩溃怎么解决吗？😭

**Comment by QingSi180** [comment]
> > 这……
> 
> 老哥你知道第一次玩整合包进去没事，第二次进去就会崩溃怎么解决吗？😭

我用的一加6T，没遇到过啊……

**Comment by jianlin-15** [comment]
> > > 这……
> > 
> > 
> > 老哥你知道第一次玩整合包进去没事，第二次进去就会崩溃怎么解决吗？😭
> 
> 我用的一加6T，没遇到过啊……

> > > 这……
> > 
> > 
> > 老哥你知道第一次玩整合包进去没事，第二次进去就会崩溃怎么解决吗？😭
> 
> 我用的一加6T，没遇到过啊……
是我710不配😅

**Comment by QingSi180** [comment]
> > > > 这……
> > > 
> > > 
> > > 老哥你知道第一次玩整合包进去没事，第二次进去就会崩溃怎么解决吗？😭
> > 
> > 我用的一加6T，没遇到过啊……
> 
> > > > 这……
> > > 
> > > 
> > > 老哥你知道第一次玩整合包进去没事，第二次进去就会崩溃怎么解决吗？😭
> > 
> > 我用的一加6T，没遇到过啊……
> 是我710不配😅

我这连正常显示材质都不配😂

**Comment by WesleyVanNeck** [comment]
use issue teplate
