### ISSUE TITLE
[BUG] I can't get minecraft to work 

### ISSUE THREAD

**Issue by 321goahhhhhhhhhh** [PojavLauncherTeam/PojavLauncher#794]
**Describe the bug**
I was gonna test the newest version (3.3.1.1)
So i login to my account and downloaded the Minecraft version of (1.7.10) then started. But it crash and showed a popup.
**To Reproduce**
1. Start PojavLauncher
2. Download the version (1.7.10)
3. Wait it to downloads 
...

**Expected behavior**
I expected it will run Minecraft normally 

**Screenshots**
N/A Or soon if needed
**Platform:**
 - Device Model: Samsung Galaxy J2 Pirme
 - CPU architecture: (aarch32)
 - Android version: (6.0.1)

**Comment by khanhduytran0** [comment]
Missing log

**Comment by 321goahhhhhhhhhh** [comment]
What does that mean?

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by 321goahhhhhhhhhh** [comment]
K just a sec

**Comment by 321goahhhhhhhhhh** [comment]
Here goodluck reading this


--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms256m -Xmx512m"
Headless version detected! (20140514)
--------- beginning of system
--------- beginning of main
I/jrelog  (23978): Starting logging STDIO as jrelog:V
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x3a8
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so
I/jrelog  (23978): : unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
I/jrelog  (23978): : unused DT entry: type 0x1d arg 0x478
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x34ad
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so: unused DT entry: type 0x1d arg 0x13f9
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so
I/jrelog  (23978): : unused DT entry: type 0x1d
I/jrelog  (23978):  arg 
I/jrelog  (23978): 0x2303
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so: unused DT entry: type 0x1d arg 
I/jrelog  (23978): 0x732a
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so: unused DT entry: type 0x1d arg 0x52e
I/jrelog  (23978): WARNING: linker: 
I/jrelog  (23978): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so: unused DT entry: type 0x1d arg 0x1010
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so: unused DT entry: type 0x1d
I/jrelog  (23978):  arg 0x27f
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so: unused DT entry: type 0x1d arg 0x30e
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so: unused DT entry: type 0x1d arg 
I/jrelog  (23978): 0x1f5
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so: unused DT entry: type 0x1d arg 0x5bb
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so: unused DT entry: type 0x1d arg 0x178c
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so: unused DT entry: type 0x1d
I/jrelog  (23978):  arg 0x66d
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 
I/jrelog  (23978): 0x1df
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so: unused DT entry: type 0x1d
I/jrelog  (23978):  arg 0x161
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0xf42
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x141
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so
I/jrelog  (23978): : unused DT entry: type 0x1d arg 0x6e9
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x400
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x102
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x70a
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x10e
I/jrelog  (23978): WARNING: linker: 
I/jrelog  (23978): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x99f
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so: unused DT entry: type 0x1d arg 0x9f
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0xe1
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so: unused DT entry: type 
I/jrelog  (23978): 0x1d arg 0x6de
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
I/jrelog  (23978): WARNING: linker: 
I/jrelog  (23978): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so: unused DT entry: type 0x1d arg 0x261
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so
I/jrelog  (23978): : unused DT entry: type 0x1d arg 0x415
I/jrelog  (23978): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so: unsupported flags DT_FLAGS_1=
I/jrelog  (23978): 0x81
I/jrelog  (23978): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success
I/jrelog  (23978): dlopen /data/app/net.kdt.pojavlaunch-1/lib/arm/libopenal.so success
I/jrelog  (23978): dlopen /data/app/net.kdt.pojavlaunch-1/lib/arm/libgl04es.so success
I/jrelog  (23978): Done processing args
I/jrelog  (23978): Found JLI lib
I/jrelog  (23978): Calling JLI_Launch
I/jrelog  (23978): OpenJDK Client VM warning: 
I/jrelog  (23978): No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/jrelog  (23978): Error occurred during initialization of VM
I/jrelog  (23978): Could not reserve enough space for 434176KB object heap

**Comment by 321goahhhhhhhhhh** [comment]
Also i don't know all of this so

**Comment by Mathias-Boulay** [comment]
not enough free ram

**Comment by khanhduytran0** [comment]
32bit devices has limited RAM. Disable auto RAM and set Xmx to 256M

**Comment by 321goahhhhhhhhhh** [comment]
Oh ok wait

**Comment by 321goahhhhhhhhhh** [comment]
At all of them?

**Comment by Mathias-Boulay** [comment]
-Xms256m -Xmx256m @321goahhhhhhhhhh

**Comment by 321goahhhhhhhhhh** [comment]
Ok

**Comment by 321goahhhhhhhhhh** [comment]
It worked thank you so much

**Comment by 321goahhhhhhhhhh** [comment]
Also -Xms356 -Xmx356m works for me the best
