### ISSUE TITLE
[BUG]] Error detected on 32-bit devices

### ISSUE THREAD

**Issue by SiergoMakatao** [PojavLauncherTeam/PojavLauncher#795]
**Describe the bug**
Difference between 64 and 32 bit devices

**To Reproduce**
1. Start PojavLauncher
2. For some reason, I have a 32-bit device, although I have a 64-bit device, and because of this, I need to manually install the aarch32 architecture (unlike 64-bit, the architecture is installed automatically!)
3. 32-bit buttons (<- | ->) differ from 64-bit
4. No characters ("'@ # § *) (I discussed this later)

**Expected behavior**
I was expecting to add characters ("'@ # § *).
But because of the 32-bit pojav launcher, they are not written

**Screenshots**

**Platform:**
 - Device Model [Redmi 9C]
 - CPU architecture [e.g. aarch64]
 - Android Version [e.g. 11]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
> **Describe the bug**
> Difference between 64 and 32 bit devices
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Start PojavLauncher
> 2. For some reason, I have a 32-bit device, although I have a 64-bit device, and because of this, I need to manually install the aarch32 architecture (unlike 64-bit, the architecture is installed automatically!)
> 3. 32-bit buttons (<- | ->) differ from 64-bit
> 4. No characters ("'@ # § *) (I discussed this later)
> 
> **Expected behavior**
> I was expecting to add characters ("'@ # § *).
> But because of the 32-bit pojav launcher, they are not written
> 
> **Screenshots**
> 
> **Platform:**
> 
> * Device Model [Redmi 9C]
> * CPU architecture [e.g. aarch64]
> * Android Version [e.g. 11]
> 
> Additional context

First of all i think you have a 32 bit ROM these charecter are nog inplementad

**Comment by WesleyVanNeck** [comment]
I got a redmi Note 9 pro ant i dont have a 32 bit rom

**Comment by SiergoMakatao** [comment]
> > **Опишите ошибку** 
> > Разница между 64- и 32-битными устройствами
> > **Чтобы воспроизвести** 
> > шаги для воспроизведения поведения:
> > 
> > 1. Запустить PojavLauncher
> > 2. По какой-то причине у меня 32-битное устройство, хотя у меня 64-битное устройство, и из-за этого мне нужно вручную установить архитектуру aarch32 (в отличие от 64-битной, архитектура устанавливается автоматически!)
> > 3. 32-битные кнопки (<- | ->) отличаются от 64-битных
> > 4. Без символов ("'@ # § *) (я обсуждал это позже)
> > 
> > **Ожидаемое поведение** 
> > Я ожидал добавить символы ("'@ # § *). 
> > Но из-за 32-разрядной программы запуска pojav они не записываются
> > **Скриншоты**
> > **Платформа:**
> > 
> > * Модель устройства [Redmi 9C]
> > * Архитектура процессора [например, aarch64]
> > * Версия Android [например, 11]
> > 
> > Дополнительный контекст
> 
> Прежде всего, я думаю, что у вас 32-битное ПЗУ, эти символы не добавлены

Why weren't symbols added?

**Comment by Zeyrox1090** [comment]
diko alam

**Comment by khanhduytran0** [comment]
32bit already have builtin runtime since v3.3.1.1
