### ISSUE TITLE
[REQUEST] Controller Support

### ISSUE THREAD

**Issue by Harel3** [PojavLauncherTeam/PojavLauncher#80]
Title should be self explanatory

**Comment by khanhduytran0** [comment]
is it require a mod or Minecraft self-compatible?

**Comment by Harel3** [comment]
There is a few mods for controller support but im thinking if the launcher detects a controller click and turns to a keyboard button (kinda like JoyToKey) or something since minecraft java doesnt have controller support

**Comment by khanhduytran0** [comment]
Mod is not required because I have a keycode map in the launcher, so may easily to map controller keycode.

**Comment by FranzelDamasco909** [comment]
How to use it?

**Comment by khanhduytran0** [comment]
I'm not implemented it yet.

**Comment by khanhduytran0** [comment]
@Harel3 go to Minecraft controls, and try change some controls, some buttons might work...

**Comment by Mathias-Boulay** [comment]
Done.
