### ISSUE TITLE
I run impact installer successfully in VMOS,but there is a problem that the mouse can't move in VMOS.

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#802]
@khanhduytran0 I run it successfully in VMOS,but there is a problem that the mouse can't move in VMOS.Can the problem be fixed?
![Screenshot_20210205_100930_com vmos pro](https://user-images.githubusercontent.com/62139629/106980091-7b193f80-6757-11eb-9382-bbab564449b8.jpg)

_Originally posted by @yejunjie10311031 in https://github.com/PojavLauncherTeam/PojavLauncher/issues/776#issuecomment-773732818_

**Comment by khanhduytran0** [comment]
Are you on latest build?

**Comment by yejunjie10311031** [comment]
@khanhduytran0 Yes,I use the latest version in actions:https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/537935070

**Comment by yejunjie10311031** [comment]
But if I keep pressing a virtual button with one finger and slide the screen with the other finger, the mouse can move normally, but it's very inconvenient.

**Comment by khanhduytran0** [comment]
So you run impact on #804 succeed, closing.
