### ISSUE TITLE
I found that sun.awt.X11FontManager doesn't work on my device.

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#804]
I have added "-Dcacio.font.fontmanager=sun.awt.X11FontManager" to JVM arguments,but if I start Minecraft impact,it will still crash as the same before,but if I run it in VMOS,I can start it successfully.But there is a problem in VMOS:https://github.com/PojavLauncherTeam/PojavLauncher/issues/802
Sorry to trouble you so much,but I really want the problem to be fixed.

**Comment by nedogimov** [comment]
> I have added "-Dcacio.font.fontmanager=sun.awt.X11FontManager" to JVM arguments,but if I start Minecraft impact,it will still crash as the same before,but if I run it in VMOS,I can start it successfully.But there is a problem in VMOS:https://github.com/PojavLauncherTeam/PojavLauncher/issues/802
> Sorry to trouble you so much,but I really want the problem to be fixed.
> 

in the last dev the build does not need to add this argument.

**Comment by yejunjie10311031** [comment]
@nedogimov @khanhduytran0 Thanks a lot!Now I run impact successfully without VMOS.
![Screenshot_20210206_093029_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/107104834-4d95ca00-681b-11eb-9b20-4803081786ad.jpg)
![Screenshot_20210206_093111_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/107104837-51c1e780-681b-11eb-9f80-161a560cdc5a.jpg)
