### ISSUE TITLE
[BUG] blur on the screen.

### ISSUE THREAD

**Issue by MateusL13** [PojavLauncherTeam/PojavLauncher#805]
**Describe the bug**
It's just a shade on the game! Is not a big problem, but is annoying.(Interestingly, this shade does not appear in version 1.5.2 and bellow.)

**To Reproduce**
1. Start PojavLauncher (last action build)
2. Enter on any version (1.5.2 works fine)

**Expected behavior**
I expected a clear vision of the game.

**Screenshots**
![Screenshot_20210205-120043](https://user-images.githubusercontent.com/38146322/107051468-3fa86080-67ab-11eb-94df-e7256edd158a.png)

**Platform:**
 - Device Model: Moto G6 play
 - CPU architecture: aarch32
 - Android Version: 9

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Part of the bottom left corner works perfectly.
</pre>
</details>

**Comment by Mathias-Boulay** [comment]
You mean the white shade on top of almost everything ?
We're working on a fix available here: https://github.com/PojavLauncherTeam/PojavLauncher/suites/1975886507/artifacts/39285879
@Mateus13000

**Comment by MateusL13** [comment]
> You mean the white shade on top of almost everything ?
> We're working on a fix available here: https://github.com/PojavLauncherTeam/PojavLauncher/suites/1975886507/artifacts/39285879
> @Mateus13000

I tested, but still the same :(

**Comment by Mathias-Boulay** [comment]
So this fixed build doesn't worked … Guess I have work to do.
*btw your cpu architecture is described as 64 bits compatible on kimovil*

**Comment by MateusL13** [comment]
> 
> 
> So this fixed build doesn't worked … Guess I have work to do.
> _btw your cpu architecture is described as 64 bits compatible on kimovil_

Yes, my cpu is 64 bits, but my android is not.

**Comment by Mathias-Boulay** [comment]
> Yes, my cpu is 64 bits, but my android is not.

Noted

**Comment by MateusL13** [comment]
> > Yes, my cpu is 64 bits, but my android is not.
> 
> Noted

1.5.2 work just fine (But crash if I enter in a world with a render distance >tiny)
![Screenshot_20210205-141157](https://user-images.githubusercontent.com/38146322/107068280-2c9f8b80-67bf-11eb-9906-e648e3669742.png)

**Comment by Mathias-Boulay** [comment]
@Mateus13000 I tried a new fix that worked for some, care to try ? 
https://github.com/PojavLauncherTeam/PojavLauncher/runs/1840913470

**Comment by MateusL13** [comment]
> @Mateus13000 I tried a new fix that worked for some, care to try ?
> https://github.com/PojavLauncherTeam/PojavLauncher/runs/1840913470

It worked! Thank you very much :D
![Screenshot_20210205-163958](https://user-images.githubusercontent.com/38146322/107081320-41851a80-67d1-11eb-9905-8079f070596c.png)
