### ISSUE TITLE
crashes on chromebook

### ISSUE THREAD

**Issue by arceuss** [PojavLauncherTeam/PojavLauncher#806]
im trying to launch b1.7.3 but the game just crashes and kicks me back to the launcher

**Comment by Mathias-Boulay** [comment]
You need to use the github issue template 
(available at https://github.com/PojavLauncherTeam/PojavLauncher/blob/v3_openjdk/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by arceuss** [comment]
ok

**Comment by WesleyVanNeck** [comment]
It works for me on 1.7.10
