### ISSUE TITLE
[BUG] [Forge] [1.7.10] Forge fails to load some mods

### ISSUE THREAD

**Issue by asdasdasd31** [PojavLauncherTeam/PojavLauncher#814]
**Describe the bug**
Forge fails to load some mods

**To Reproduce**
1. Install Forge 1.7.10 1614
2. Install any core mod i.e CodeChickenCore or bdlib

**Expected behavior**
Working game

**Platform:**
 - Device Model: Samsung Galaxy note 8
 - CPU architecture aarch64
 - Android Version 9

**Log file**
https://pastebin.com/Q7xDX6us
https://pastebin.com/CBUFYfqA

Any mods that don't need any other core mods to work run perfectly fine

EDIT: added newer log file

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
