### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ryzen28** [PojavLauncherTeam/PojavLauncher#815]
I cant click

**Comment by khanhduytran0** [comment]
If you are on 1.14+ try use tab

**Comment by Ryzen28** [comment]
> If you are on 1.14+ try use tab

Do you mean the tab button?
It still doesn't work

**Comment by 321goahhhhhhhhhh** [comment]
What can't you click on?

**Comment by Ryzen28** [comment]
I cant cliick on the screen

**Comment by Mathias-Boulay** [comment]
A video (and the use of the GITHUB ISSUE TEMPLATE)  would help us.

**Comment by Mathias-Boulay** [comment]
Stale issue, and the template isn't filled, yet to have an answer from the author.
Closing the issue.
