### ISSUE TITLE
[BUG] arm emulation of zenfones crashing the app.

### ISSUE THREAD

**Issue by paiSen000** [PojavLauncherTeam/PojavLauncher#816]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**
![Screenshot_20210206-213724](https://user-images.githubusercontent.com/76996485/107119613-cd776f00-68c3-11eb-8d3f-3697d87c289f.jpg)

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - Asus zen fone
 - CPU architecture [e.g. aarch64] 
 - aarch64
 - Android Version [e.g. 10]
 - 5

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Mathias-Boulay** [comment]
Could we have the precise zenphone model by any chance ?

**Comment by paiSen000** [comment]
> Could we have the precise zenphone model by any chance ?
 
Here
Asus Zenfone 2 ZE551ML

**Comment by Mathias-Boulay** [comment]
According to gsmarena, your phone architecture isn't aarch64, it is an x86_64 processor. (Intel Atom Z3580)

**Comment by paiSen000** [comment]
Yes, I was just confused with that. So what should    I do?

**Comment by Mathias-Boulay** [comment]
Pretty sure this architecture isn't properly supported as of right now. 👀 
It really stops like this when trying to enter the app or did you click the play button ?

**Comment by paiSen000** [comment]
I already clicked the play button then few seconds after it exits and shows the "unfortunately... Has stopped"

**Comment by khanhduytran0** [comment]
I think Zenfone x86 handling ARM with x86 incorrectly: it check for ARM binaries first then come to check x86. That's why most Zenfone user get fails on launch...

**Comment by khanhduytran0** [comment]
(I mean, Zenfone has a builtin ARM -> x86 emulator, but why it have to check ARM first? It's a firmware bug)

**Comment by paiSen000** [comment]
Oh... So I can't do anything to fix it?

**Comment by Mathias-Boulay** [comment]
What about checking for x86 before arm ?

**Comment by Mathias-Boulay** [comment]
I'll try something.

**Comment by khanhduytran0** [comment]
> Oh... So I can't do anything to fix it?

The only way is to get rid of ARM/ARM64 native lib use something like Apk editor.

> What about checking for x86 before arm ?

I think it requires a firmware patch

**Comment by Mathias-Boulay** [comment]
> I think it requires a firmware patch

Oh.

**Comment by khanhduytran0** [comment]
> > I think it requires a firmware patch
> 
> Oh.

Or maybe a Xposed/something tweak to do it?

**Comment by Mathias-Boulay** [comment]
I've tried to change the detection method, can you try it ? @paiSen000 
https://gofile.io/d/3q7d3C *(can't upload the whole file on github)*

**Comment by paiSen000** [comment]
It still doesn't work. It still says "Unfortunately... Has stopped."

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by Mathias-Boulay** [comment]
*Gosh*

**Comment by paiSen000** [comment]
> Send latestlog.txt

Where is that?

**Comment by khanhduytran0** [comment]
It's on .minecraft folder

**Comment by paiSen000** [comment]
I can't find it

**Comment by khanhduytran0** [comment]
`/sdcard/games/PojavLauncher/.minecraft/latestlog.txt`
Remember to enable show hidden folder

**Comment by paiSen000** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5937930/latestlog.txt)

**Comment by khanhduytran0** [comment]
Maybe set lower ram?

**Comment by paiSen000** [comment]
> Maybe set lower ram?

How do I do that

**Comment by khanhduytran0** [comment]
Go to jvm arguments and change Xmx and Xms

**Comment by khanhduytran0** [comment]
@paiSen000 please reply

**Comment by paiSen000** [comment]
Oh sorry, where is that?

**Comment by Mathias-Boulay** [comment]
On the google play version, it is a slider that you can set to 300 MB for exemple

**Comment by Mathias-Boulay** [comment]
the new gplay version (crocus) fixes the detection of asus zenfones.
Hope that google does the same for gplay 🤔 
Closing.
