### ISSUE TITLE
Older versions are broken. 

### ISSUE THREAD

**Issue by notfoundname** [PojavLauncherTeam/PojavLauncher#82]
Hello, I noticed that versions below 1.6 are completely broken (well, at least main menu).
I think this bug caused by old... directory system (I mean, they didn't have /versions folder).

**Comment by khanhduytran0** [comment]
MORE -> Send custom keycode -> F11.

**Comment by khanhduytran0** [comment]
This will get to fullscreen mode and solve the issue.

**Comment by khanhduytran0** [comment]
> Send custom keycode

Make sure you have installed preview11 to see the option above.

**Comment by notfoundname** [comment]
Thanks, this worked. But there's no sounds.

**Comment by khanhduytran0** [comment]
because old server no longer contains sound file and Minecraft unable to download.

**Comment by jrxohan** [comment]
> because old server no longer contains sound file and Minecraft unable to download.

Hello, if versions like 1.2.5 and 1.1 can be applied using F11, but what about versions like 1.5.2 or 1.4 or 1.3? I have tried to start it but they do not load. It remains on a gray screen as if it was not executed.  nothing just gray, but why does that happen?  I just want to know or I'm just not informed about this

**Comment by khanhduytran0** [comment]
You can't run 1.3-~~1.6~~ 1.5, yep it's leave gray even with F11. I see in log it initialize a little then nothing more.

**Comment by jrxohan** [comment]
> You can't run 1.3-1.6, yep it's leave gray even with F11. I see in log it initialize a little then nothing more.

Ok thank you, by the way for me they do not work from 1.3 to 1.5 since 1.6 runs quite well although it is an obsolete version

**Comment by khanhduytran0** [comment]
I didn't tested 1.6 sorry

**Comment by artdeell** [comment]
> > You can't run 1.3-1.6, yep it's leave gray even with F11. I see in log it initialize a little then nothing more.
> 
> Ok thank you, by the way for me they do not work from 1.3 to 1.5 since 1.6 runs quite well although it is an obsolete version

1.3 - 1.5 even doesn't run on some PCs.

**Comment by notfoundname** [comment]
Ok. Would be cool if old versions' sounds could be downloaded from some server what has them.
