### ISSUE TITLE
Android ci 2001 "The latest build" i cant find the download thing where u can download version so i think its a bug :(

### ISSUE THREAD

**Issue by Mynameispoop** [PojavLauncherTeam/PojavLauncher#820]

**Comment by WesleyVanNeck** [comment]
follow the issue template

**Comment by Mynameispoop** [comment]
Issue template?

**Comment by Mynameispoop** [comment]
So u mean theres a version downloader

**Comment by Mynameispoop** [comment]
Hey help me where is the version downloader

**Comment by Mynameispoop** [comment]
WHERE CAN I DOWNLOAD THE VEEERRSSIOONSSSS

**Comment by artdeell** [comment]
Bruh, go to the Profiles tab and add a profile with your version

**Comment by artdeell** [comment]
Just like the official MC launcher

**Comment by Mynameispoop** [comment]
Ohh ok

**Comment by Mynameispoop** [comment]
Thanks i guess

**Comment by Mynameispoop** [comment]
> Bruh, go to the Profiles tab and add a profile with your version

U mean i like renamed the default to what ever version i want

**Comment by Mynameispoop** [comment]
It doesn't work pleassee haaalppp

**Comment by Mynameispoop** [comment]
Uploading SVID_20210209_103237_1.mp4…

**Comment by Mynameispoop** [comment]
Uploading SVID_20210209_103237_1.mp4…

**Comment by Mynameispoop** [comment]
CMON HEELPP MEEHH

**Comment by Mynameispoop** [comment]
Never mind i figured it out
