### ISSUE TITLE
[F-REQ] Need Authlib Injector

### ISSUE THREAD

**Issue by coremodmc** [PojavLauncherTeam/PojavLauncher#824]
请求支持由Authlib Injector驱动的外置登录
Request to support external login driven by Authlib Injector
另外请问为什么最新的构建版本没有下载功能
Also, why does the latest build version have no download function?

**Comment by yejunjie10311031** [comment]
你得先在profiles选项里选择版本。

**Comment by yejunjie10311031** [comment]
@BottleAJoB
![Screenshot_20210208_174748_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/107203019-c602b380-69f2-11eb-8578-36c8b4c56d05.jpg)

**Comment by khanhduytran0** [comment]
Injecting authlib will make this launcher become a cracked launcher.

**Comment by zhangjing-GitHub-Code** [comment]
~~The launcher don't have authlib-injector is not a good launcher~~(doge)
So how can I install authlib-injector by my self?

**Comment by zhangjing-GitHub-Code** [comment]
@yejunjie10311031 
__(commented on 8 Feb)__
How can you get this UI?
I'm using __3.3.1.1__, are you building it by your self or using an older version?

**Comment by Mathias-Boulay** [comment]
It is from a custom branch that ended up not being integrated to mainline.

**Comment by lightyisreal** [comment]
If you made it so you need a Microsoft account to add an authlib-injector account, would that make it better? You would technically prove that you have purchased the game, and everyone would be happy.

**Comment by lightyisreal** [comment]
https://github.com/unmojang/FjordLauncher does this already, and it works
