### ISSUE TITLE
IT ALLWAYS KICKING ME OUT

### ISSUE THREAD

**Issue by plsAlow** [PojavLauncherTeam/PojavLauncher#826]
HELP it always kick me out im 32bit what should i used that moded od mcinabox aarch32 runtime for the automatic?

**Comment by khanhduytran0** [comment]
🤦‍♂️ 

We aren't Boat/McinaBox variant. We have our runtime for all architectures inside the `app-debug.apk` (60MB).

**Comment by plsAlow** [comment]
when i run 1.5.2 version it crash pls fix it

**Comment by khanhduytran0** [comment]
Use v3.3.1.1

**Comment by plsAlow** [comment]
i used it

**Comment by khanhduytran0** [comment]
Send the log

**Comment by plsAlow** [comment]
wait

**Comment by plsAlow** [comment]
Here it is 

https://user-images.githubusercontent.com/78732659/107214390-d0e63400-6a44-11eb-87c9-c34f5b9e3830.mp4

**Comment by plsAlow** [comment]
hey can you fix it now

**Comment by Mathias-Boulay** [comment]
That's not the log file.
The log file is located at games>pojavLauncher>.minecraft

**Comment by plsAlow** [comment]
ok what to do?

**Comment by Mathias-Boulay** [comment]
I dunno, maybe send the log file at the previously indicated location ? 🤣

**Comment by plsAlow** [comment]
-_-

**Comment by khanhduytran0** [comment]
Send **latestlog.txt**

**Comment by plsAlow** [comment]
nah im just gonna fix it at my own

**Comment by plsAlow** [comment]
ok

**Comment by plsAlow** [comment]
but how

**Comment by plsAlow** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5943842/latestlog.txt)

**Comment by plsAlow** [comment]
Here ya go

**Comment by khanhduytran0** [comment]
What about your ram?

**Comment by plsAlow** [comment]
2gb ram
Oppo a37
Processor: QualcommMSM8916QuadCore

**Comment by khanhduytran0** [comment]
Maybe set max 512mb?

**Comment by plsAlow** [comment]
Hmmm let me try

**Comment by plsAlow** [comment]
Thank you it work
