### ISSUE TITLE
[BUG] The versions list on offline did not load (PROFILES)

### ISSUE THREAD

**Issue by LanceYTStudioZ** [PojavLauncherTeam/PojavLauncher#827]
![Screenshot_2021-02-08-21-25-05-77](https://user-images.githubusercontent.com/78294173/107225795-38f04680-6a54-11eb-9bba-4b0c36094b1e.png)

No version list on offline mode.

**Comment by LanceYTStudioZ** [comment]
Hello

**Comment by LanceYTStudioZ** [comment]
Did you understand my English?

**Comment by khanhduytran0** [comment]
Do you know what is a WIP?

**Comment by khanhduytran0** [comment]
Was the build you download on v3_openjdk branch?

**Comment by LanceYTStudioZ** [comment]
> Do you know what is a WIP?

What is WIP?

**Comment by LanceYTStudioZ** [comment]
> Was the build you download on v3_openjdk branch?

I'm using profiles build

**Comment by Zeyrox1090** [comment]
dont use profiles build yey its still not done

**Comment by LanceYTStudioZ** [comment]
> dont use profiles build yey its still not done

Ay okay v3_openjdk branch na nga gagamitin ko

**Comment by LanceYTStudioZ** [comment]
Di ako sanay English

**Comment by LanceYTStudioZ** [comment]
> Do you know what is a WIP?

Taena Work in Process pala ngayun alm ko na.

**Comment by Zeyrox1090** [comment]
LOL
