### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by poopipie** [PojavLauncherTeam/PojavLauncher#828]
help me please just asking a question and screaming for help, how to find jvm flags i need to fix the white eggs and banners, please help me, someone please, and there is a problem about fabric sodium there is no sound i tried what i saw on yt but didn't work please help me please just please.

**Comment by Google61** [comment]
`-Dorg.lwjgl.opengl.libname=libgl4es_115.so`

**Comment by WesleyVanNeck** [comment]
Read the read me

**Comment by poopipie** [comment]
where can i finf it?

**Comment by poopipie** [comment]
thanks but i don't know where to put it

**Comment by poopipie** [comment]
where can i put that code tho? can't find java flags
