### ISSUE TITLE
mouse speed Slow on android tablets

### ISSUE THREAD

**Issue by pedrosouzabrasil** [PojavLauncherTeam/PojavLauncher#829]
**Describe the bug**
mouse speed is slow ..when using the interface of the game..maybe add a mouse speed setting(for bigger ui)

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. tab s7 8/256]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by pstube** [comment]
I have the same problem.
pojavlauncher 3.3.1 and 3.3.1.1
Teclast M40
1.16.4
1.12.2

**Comment by Mathias-Boulay** [comment]
The new gplay update has a much better mouse speed on tablets.
Closing
