### ISSUE TITLE
it gets stuck when I walk or run 

### ISSUE THREAD

**Issue by joaquinleiva** [PojavLauncherTeam/PojavLauncher#83]
I have a problem and that is that when I run or walk, the game drops to 1 fps or 5 fps, but when I am still and move the screen it goes to 30 fps
  If you don't understand what I'm saying, it's because I used the Google translator

**Comment by khanhduytran0** [comment]
Can you check renderdistance?

**Comment by joaquinleiva** [comment]
is at a minimum

**Comment by joaquinleiva** [comment]
![Screenshot_20200411-200804](https://user-images.githubusercontent.com/63518975/79056789-3c4a5400-7c30-11ea-9f8d-d51a4b8acec7.png)

**Comment by joaquinleiva** [comment]
I can only play Skyblock or in the flat world

**Comment by khanhduytran0** [comment]
Try set Max FPS to unlimited.

**Comment by khanhduytran0** [comment]
(Max Framerate)

**Comment by joaquinleiva** [comment]
I already did it and the same thing is still happening

**Comment by khanhduytran0** [comment]
What is your CPU and RAM?

**Comment by joaquinleiva** [comment]
I have 3gb of ram and Android 9

**Comment by joaquinleiva** [comment]
have a snapdragon 430 octa-core And today is an Adreno 505

**Comment by joaquinleiva** [comment]
I will have to play Skyblock until they optimize it

**Comment by khanhduytran0** [comment]
There's no way to optimize, I think 1.4Ghz is not enough for smooth playing. Something like overclock might help.

**Comment by joaquinleiva** [comment]
well i'll have to get used to the minecraft pe's se shaders and addons shit

**Comment by joaquinleiva** [comment]
well I will have to get used to the seus shaders of Minecraft pe and the shit of the addons

**Comment by joaquinleiva** [comment]
One more question how can I separate the materials because I want to make sticks and I can't divide them

**Comment by khanhduytran0** [comment]
> well I will have to get used to the seus shaders of Minecraft pe and the shit of the addons

Minecraft Java **use java** and translation of java to native code take a lot slow.

Minecraft PE/BE use C++ which the native code execute directly and faster.

**Comment by khanhduytran0** [comment]
> One more question how can I separate the materials because I want to make sticks and I can't divide them

Idk that happend on me too. Try to drop item and get it split.

**Comment by joaquinleiva** [comment]
well i will try

**Comment by WesleyVanNeck** [comment]
@khanhduytran0 i have same issue on my s9+

**Comment by artdeell** [comment]
> have a snapdragon 430 octa-core And today is an Adreno 505

that's slow

**Comment by WesleyVanNeck** [comment]
> > have a snapdragon 430 octa-core And today is an Adreno 505
> 
> that's slow

well i got samsung Exynos 9 9810 do its not slow just bad drivers

**Comment by WesleyVanNeck** [comment]
i got same issue with oc kernel and without to  do it never deeps below 30 its a stutery mess

**Comment by artdeell** [comment]
> i got same issue with oc kernel and without to  do it never deeps below 30 its a stutery mess

Heh. Ask Samsung about UNOPTIMIZED ART runtime.

**Comment by WesleyVanNeck** [comment]
> > i got same issue with oc kernel and without to  do it never deeps below 30 its a stutery mess
> 
> Heh. Ask Samsung about UNOPTIMIZED ART runtime.

bullshit also why does mcinabox run fine am done tbh with project if your talking like that am going

**Comment by WesleyVanNeck** [comment]
it runs fine o my s7

**Comment by artdeell** [comment]
> > > i got same issue with oc kernel and without to  do it never deeps below 30 its a stutery mess
> > 
> > 
> > Heh. Ask Samsung about UNOPTIMIZED ART runtime.
> 
> bullshit also why does mcinabox run fine am done tbh with project if your talking like that am going

MCinaBox doesn't use ART runtime.

**Comment by joaquinleiva** [comment]
I already solved it, I was testing versions and version 1.8.2 when I walk or run it doesn't get stuck

**Comment by joaquinleiva** [comment]
But when I look at the water the fps drop a little

**Comment by khanhduytran0** [comment]
Try v3 for a lot better performance (use jre8)
