### ISSUE TITLE
keybord bug on nubia 5s device

### ISSUE THREAD

**Issue by pedrosouzabrasil** [PojavLauncherTeam/PojavLauncher#830]
**Describe the bug**
the keyboard is not working inside game..(only using hackers keyboard)(only my device fault..not all devices .

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...working

**Screenshots**

**Platform:**
 - Device Model [e.g. redmagic 5s 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Duplicate #606?

**Comment by pedrosouzabrasil** [comment]
Ok closed
