### ISSUE TITLE
Can you add Javafx？

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#832]
Now I need to install a modpack. I installed java in proot in Termux to run HMCL launcher.jar to install modpack before.And now I tried to use Pojavlauncher's mod installer to launch HMCL launcher to install modpack but it said it required openjfx to run it.(Sorry for bad English)
The HMCL launcher is in https://github.com/huanghongxun/HMCL

**Comment by LanceYTStudioZ** [comment]
What is HMCL launcher.jar???

**Comment by pablodz** [comment]
I think he refers to this https://github.com/Thestarsend/HMCL

**Comment by LanceYTStudioZ** [comment]
> I think he refers to this https://github.com/Thestarsend/HMCL

Is this a minecraft launcher or mod?

**Comment by ghost** [comment]
> > I think he refers to this https://github.com/Thestarsend/HMCL
> 
> Is this a minecraft launcher or mod?

A minecraft launcher

**Comment by Mathias-Boulay** [comment]
Pojav Launcher isn't made to launch launcher, and it really isn't something in our roadmap.
Closing.

**Comment by R0cit** [comment]
Well, in fact, this is quite a shame, because some modpacks require their own launchers to work correctly...
