### ISSUE TITLE
Why when playing Minecraft version 1.8.9 always force close, please fix it, just want to play on the server, it's hard

### ISSUE THREAD

**Issue by aditgamink** [PojavLauncherTeam/PojavLauncher#833]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Nobody know your problem. **No information** was filled.
~~Better change the title to `[BUG]` to match issue template~~

**Comment by plsAlow** [comment]
same that was my problem to

**Comment by khanhduytran0** [comment]
Stills not getting respond from @aditgamink
