### ISSUE TITLE
[NOT A BUG]Pls someone help me how to download version 😢

### ISSUE THREAD

**Issue by Mynameispoop** [PojavLauncherTeam/PojavLauncher#834]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
Smh. Go to the profile tab, select the version, press "Add" and done. You have your version.

**Comment by Zeyrox1090** [comment]
yep profile is confusing

**Comment by Zeyrox1090** [comment]
for me
