### ISSUE TITLE
[Suggestion] Forge icon on Profiles

### ISSUE THREAD

**Issue by LanceYTStudioZ** [PojavLauncherTeam/PojavLauncher#835]
For minecraft forge icon

![Screenshot_2021-02-09-20-24-48-53](https://user-images.githubusercontent.com/78294173/107363645-6224db80-6b15-11eb-9366-97127c1db998.png)
⬇️
![images](https://user-images.githubusercontent.com/78294173/107363706-77016f00-6b15-11eb-89ad-555b6c9891af.jpeg)
Or
![FurnaceNew](https://user-images.githubusercontent.com/78294173/107363914-c5af0900-6b15-11eb-9a21-89bf804265b7.png)
This is perfect man!

**Comment by Zeyrox1090** [comment]
lol 20 sec ago

**Comment by LanceYTStudioZ** [comment]
> lol 20 sec ago

Ano meron na??

**Comment by LanceYTStudioZ** [comment]
@zeyrox1090 translate mo sasabihin ko marunong ka mag tagalog d ba

**Comment by Zeyrox1090** [comment]
ayos sakin
anvil itsura
nasa latest actions bayan?

**Comment by LanceYTStudioZ** [comment]
> ayos sakin
> anvil itsura
> nasa latest actions bayan?

Oo ah men

**Comment by LanceYTStudioZ** [comment]
> ayos sakin
> anvil itsura
> nasa latest actions bayan?

Papaano mo naman napalitan yung icon?

**Comment by khanhduytran0** [comment]
Profiles cancelled.
