### ISSUE TITLE
[BUG] No log output

### ISSUE THREAD

**Issue by LanceYTStudioZ** [PojavLauncherTeam/PojavLauncher#836]
![Screenshot_2021-02-09-19-29-55-16](https://user-images.githubusercontent.com/78294173/107365437-c2b51800-6b17-11eb-97ef-f738d96652ef.png)
 No log output why?

**Comment by LanceYTStudioZ** [comment]
Hello

**Comment by khanhduytran0** [comment]
Known issue on some devices due to android restrict. Nothing inside log file?

**Comment by khanhduytran0** [comment]
@LanceYTStudioZ update to latest build.
