### ISSUE TITLE
[F-REQ] joycon support

### ISSUE THREAD

**Issue by arceuss** [PojavLauncherTeam/PojavLauncher#837]
**Is your feature request related to a problem? Please describe.**
im using pojavlauncher on my hacked switch but joycons dont work ingame

**Describe the solution you'd like**
just add controller support in general i guess

**Describe alternatives you've considered**
using the touch screen

**Comment by matt995** [comment]
I think they are adding controller support soon, for now you can try mapping the buttons that can be mapped

**Comment by Mathias-Boulay** [comment]
Closing as it is a duplicate from #80
