### ISSUE TITLE
I want play on premium server!!!

### ISSUE THREAD

**Issue by ZH-XiJun** [PojavLauncherTeam/PojavLauncher#84]
The Launcher is updated, but I still can't play the premium server. It said "Unable to fix RSAPadding. You can't play premium server" when Minecraft is starting. I think we can fix "RSAPadding" , then we can play on premium server. But how can I fix this issue???

原文：
启动器更新了，可我仍然玩不到正版服务器。程序在Minecraft刚启动的时候说“Unable to fix RSAPadding. You can't play premium server”。我认为我们可以修复的，但是怎么修复呢？？？

**Comment by ZH-XiJun** [comment]
The above sentence is written in my English -8 grade, please forgive me😓😓😓

**Comment by khanhduytran0** [comment]
if you have development and hack skill check it
https://github.com/zhuowei/Boardwalk/blob/master/src/net/zhuoweizhang/boardwalk/MainActivity.java#L558

**Comment by khanhduytran0** [comment]
I'm finding different way to fix premium issue

(yep my English a bit like you but more words pre-learn at home)

**Comment by ZH-XiJun** [comment]
Uhhh...
Can't we connect Mojang's account server?
If the account connected Mojang's server, set the account in online mode, maybe we can pass the online-mode verification

**Comment by ZH-XiJun** [comment]
or we are already connected, but no effect?
maybe it is Boardwalk's issue🤔
(actually, I don't know anything [滑稽] )

**Comment by khanhduytran0** [comment]
the problem is at encryption

**Comment by ZH-XiJun** [comment]
How can I play my server😭😭😭

**Comment by artdeell** [comment]
> How can I play my server😭😭😭

Try to use VMOS, it should be able to run with padding fixes.

**Comment by khanhduytran0** [comment]
I need to get to old patch before you can play.

**Comment by ZH-XiJun** [comment]
> > How can I play my server😭😭😭
> 
> Try to use VMOS, it should be able to run with padding fixes.

Good, I found the site in my country. Let me try it.
And I'm found a new problem, in offline-mode server.

**Comment by ZH-XiJun** [comment]
![5eff2d05fe18aeed995e62f83b969bf](https://user-images.githubusercontent.com/59949135/79092069-3e242c80-7d82-11ea-917f-8c6ddd174d27.jpg)

Let me translate it:
You can't visit the server!
Because we detected the BOT algorithm
Please refresh the server list and try again

**Comment by khanhduytran0** [comment]
Hmm...

**Comment by ZH-XiJun** [comment]
> Hmm...

Can you read it?
What happened?

**Comment by ZH-XiJun** [comment]
Hey guys
I found something in [This code](https://github.com/zhuowei/Boardwalk/blob/45893a80e0d1f89d7aab6e184518dab95fb120bf/src/net/zhuoweizhang/boardwalk/MainActivity.java#L602)
I found spongy.jar. Its path is "/sdcard/boardwalk/spongy.jar", but I can't found this file in my phone.
I don't know if this will help us.

**Comment by khanhduytran0** [comment]
It for developer debugging.

**Comment by khanhduytran0** [comment]
I think

**Comment by ZH-XiJun** [comment]
okay, it does not any help

**Comment by khanhduytran0** [comment]
Sorry, I'm wrong, but code used by spongy has been commented out.

```
/*
		System.out.println("Before: " + KeyFactory.getInstance("RSA") + ":" + KeyFactory.getInstance("RSA").getProvider());	
	DexClassLoader classLoader = new DexClassLoader(spongyFile.getAbsolutePath(),			optDir.getAbsolutePath(), null, MainActivity.class.getClassLoader());	
	Class<?> clazz = classLoader.loadClass("org.spongycastle.jce.provider.BouncyCastleProvider");
		Security.insertProviderAt((Provider) clazz.newInstance(), 1);
		System.out.println("After: " + KeyFactory.getInstance("RSA") + ":" + KeyFactory.getInstance("RSA").getProvider());
*/	
```

**Comment by ZH-XiJun** [comment]
I see

**Comment by ZH-XiJun** [comment]
HEY GUYS
I'm found a new issue, only in China.
Sometimes I can't connect "libraries.minecraft.com", this affect me to download Minecraft. We could change Minecraft download site to other site I can normally connect like BMCLAPI. Or we can have a setting for the download site. that sounds great.
I think this words not really good, I hope you can read them. XD

**Comment by khanhduytran0** [comment]
Maybe...

**Comment by ZH-XiJun** [comment]
Good, I found a new issue.

**Comment by khanhduytran0** [comment]
Try latest v2.5 with VMOS...

**Comment by ZH-XiJun** [comment]
I have no storage space to install VMOS.
And v3 preview can't launch Minecraft (errr, can't convert librrary `net.java.dev.jna` and I can't increase max DX to 8000, because it isn't save the setting, when I open the Launcher option again, it come back to 4095.)

**Comment by ZH-XiJun** [comment]
I know, it is only in test. It can't be perfect now. I hope "Boardwalk", "PojavLauncher" and other based from "boardwalk" app can make better and better!

**Comment by khanhduytran0** [comment]
> And v3 preview can't launch Minecraft (errr, can't convert librrary `net.java.dev.jna` and I can't increase max DX to 8000, because it isn't save the setting

There are removed in v3 (convert and max DX reference) since OpenJDK run Minecraft directly.

**Comment by ZH-XiJun** [comment]
oh
Let me test it (when I launch Minecraft 1.9, I can't convert `net.java.dev.jna` in a V3 version)

**Comment by khanhduytran0** [comment]
> oh
> Let me test it (when I launch Minecraft 1.9, I can't convert `net.java.dev.jna` in a V3 version)

So can you copy error here?

**Comment by ZH-XiJun** [comment]
The big error is I'm stuck here, no error, no fatal, no warns, ONLY STUCK HERE. 
But when my phone is sleeping, it will show the error like here is no response from I / O device, the system stops connecting or can't convert library because delays  is 10000ms

**Comment by khanhduytran0** [comment]
10000ms is delay of https://github.com/khanhduytran0/PojavLauncher/blob/v3_x11_openjdk/app/src/main/java/net/kdt/pojavlaunch/util/DownloadUtils.java#L28

**Comment by khanhduytran0** [comment]
So make sure your internet connection is fine.

**Comment by khanhduytran0** [comment]
> 10000ms is delay of https://github.com/khanhduytran0/PojavLauncher/blob/v3_x11_openjdk/app/src/main/java/net/kdt/pojavlaunch/util/DownloadUtils.java#L28

**Comment by ZH-XiJun** [comment]
sorrrrrrrrrrrrrrrrrry
