### ISSUE TITLE
[BUG] all versions of optifine have environment bugs and Crashes

### ISSUE THREAD

**Issue by NickyisSneaking** [PojavLauncherTeam/PojavLauncher#841]
**Describe the bug**
OptiFine all versions have bug environment black sky on 1.16 optifine and too bright white sky and crashes on 1.14.4

**To Reproduce**
1. Start PojavLauncher  
2.install optifine 

**Expected behavior**
I expect it will never lag its not lagging but have a environment bug on all version of optifine and crashes
**Screenshots**

**Platform:**
 - Device Model [e.g. MRD-LX2 (MRD-L22)]
 - CPU architecture [e.g. aarch32] 
 - Android Version [e.g. 9]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5959947/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
Please, send the latestlog.txt file under games>PojavLauncher>.minecraft
Else, we won't be able to troubleshoot you issue in any shape or form.

**Comment by NickyisSneaking** [comment]
I/jrelog  ( 6634): [16:39:35] [Server thread/INFO]: Changing view distance to 2, from 10
I/jrelog  ( 6634): [16:39:35] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 15464ms or 309 ticks behind
I/jrelog  ( 6634): Feb 10, 2021 4:39:36 PM io.netty.util.internal.MacAddressUtil defaultMachineId
I/jrelog  ( 6634): WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 4a:58:c8:80:21:11:1e:74
I/jrelog  ( 6634): [16:39:39] [Server thread/INFO]: Nicky7470[local:E:a2d55bfc] logged in with entity id 400 at (-209.5, 66.0, 140.5)
I/jrelog  ( 6634): [16:39:39] [Server thread/INFO]: Nicky7470 joined the game
I/jrelog  ( 6634): [16:39:42] [Texture Downloader #1/ERROR]: Couldn't download http texture: java.net.UnknownHostException: s.optifine.net
I/jrelog  ( 6634): [16:39:42] [Server thread/INFO]: Saving and pausing game...
I/jrelog  ( 6634): [16:39:42] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
I/jrelog  ( 6634): [16:39:43] [main/INFO]: Loaded 0 advancements
I/jrelog  ( 6634): [16:39:44] [pool-5-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@15a871b[id=00000000-0000-0000-0000-000000000000,name=Nicky7470,properties={},legacy=false]
I/jrelog  ( 6634): com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
I/jrelog  ( 6634): 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:85) ~[YggdrasilAuthenticationService.class:?]
I/jrelog  ( 6634): 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSe
I/jrelog  ( 6634): ssionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) ~[YggdrasilMinecraftSessionService.class:?]
I/jrelog  ( 6634): 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:60) ~[YggdrasilMinecraftSessionService$1.class:?]
I/jrelog  ( 6634): 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:57) ~[YggdrasilMinecraftSessionService$1.class:?]
I/jrelog  ( 6634): 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(L
I/jrelog  ( 6634): ocalCache.java:3716) ~[guava-21.0.jar:?]
I/jrelog  ( 6634): 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?]
I/jrelog  ( 6634): 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?]
I/jrelog  ( 6634): 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?]
I/jrelog  ( 6634): 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?]
I/jrelog  ( 6634): 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[guava-21.0.jar:?
I/jrelog  ( 6634): ]
I/jrelog  ( 6634): 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[guava-21.0.jar:?]
I/jrelog  ( 6634): 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[guava-21.0.jar:?]
I/jrelog  ( 6634): 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:170) ~[YggdrasilMinecraftSessionService.class:?]
I/jrelog  ( 6634): 	at cfi.C(SourceFile:2058) ~[cfi.class:?]
I/jrelog  ( 6634): 	at ddx.a(SourceFile:111) ~[ddx.class:?]
I/jrelog  ( 6634): 	at java.util.concurrent.Executors$R
I/jrelog  ( 6634): unnableAdapter.call(Executors.java:511) [?:1.8.0-internal]
I/jrelog  ( 6634): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0-internal]
I/jrelog  ( 6634): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0-internal]
I/jrelog  ( 6634): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0-internal]
I/jrelog  ( 6634): 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0-internal]
I/jrelog  ( 6634): Caused by: java.net.UnknownHostException: sessionserver.mojang.com
I/jrelog  ( 6634): 	at java.net.AbstractPlainSocketImpl.c
I/jrelog  ( 6634): onnect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:284) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.http.HttpClient.openServer(HttpClie
I/jrelog  ( 6634): nt.java:558) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.http.HttpURLC
I/jrelog  ( 6634): onnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsU
I/jrelog  ( 6634): RLConnectionImpl.java:268) ~[?:1.8.0-internal]
I/jrelog  ( 6634): 	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:130) ~[HttpAuthenticationService.class:?]
I/jrelog  ( 6634): 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66) ~[YggdrasilAuthenticationService.class:?]
I/jrelog  ( 6634): 	... 19 more

**Comment by Mathias-Boulay** [comment]
Try to play offline to see if it crashes ?

**Comment by NickyisSneaking** [comment]
I'm already playing offline but it is still graphical crashes like leaves doesn't have a right texture and the skies turn black as a void

**Comment by ghost** [comment]
for me not)

**Comment by khanhduytran0** [comment]
Maybe try to play with different optifine?

**Comment by NickyisSneaking** [comment]
I try the 1.16 optifine then I enable shader I found on the sky very dark as a void

**Comment by khanhduytran0** [comment]
> enable shader
bruh phone does not use PC GPU. Get open4es
