### ISSUE TITLE
[F-REQ] подключение к ПК

### ISSUE THREAD

**Issue by pavel19108** [PojavLauncherTeam/PojavLauncher#842]
**Проблема**

Здравствуйте, я столкнулся с проблемой: при попытке игры с другом на ПК через ZeroTier One (аналог Hamachi, только кроссплатформенный) приложение начинает закрываться при подключении (большая сборка модов - 44 штуки) в связи с недостатком оперативной памяти (2 Гб свободного места, 1 Гб - кешированные, их можно удалить для загрузки на сервер). Требуется 2.5 Гб оперативки для подключения, но при этом в данные для удаления входит и ZeroTier, который система считает неважным.

Начало загрузки: ![Screenshot_20210210_222120_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/77898934/107561570-be5c2e00-6bef-11eb-9fca-77f06a0a4b03.jpg)
А становится во время загрузки:![Screenshot_20210210_221513_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/77898934/107561633-d338c180-6bef-11eb-822d-df798e06b5ea.jpg)
(Если не понятно, значок vpn пропал)
Разница во времени из-за того, что это разные заходы были

Потом выдаёт либо ошибку "отключение", либо "программа на вашем хост-компьютере разорвала установленное подключение".

Исключение из автоматического завершения процесса андроидом не помогает.

**ВНИМАНИЕ: для подключения к компьютеру через офлайн учётку надо установить мод "Custom LAN Ports" или "Server Properties" и в нём выключить "online mode"**

**Предлагаемое решение**
Единственное, как можно будет решить данную проблему - совместить лаунчер и кроссплатформенную виртуальную локальную сеть в одном приложении, т.е., грубо говоря, организовать коллаб с тем разработчиком... Да, задача не простая, но, теоретически, решить её возможно...

P.s. Конечно, можно создать на компьютере глобальный сервер, который не потребует дополнительных программ, однако такой вариант сложнее для большинства игроков.

Как думаете, возможно ли это реализовать? Или придётся идти обходным путём для тяжёлых сборок?

**Comment by artdeell** [comment]
Я вот что скажу - майн, очень жручая игра, и единственные два девайса мне известные которые могут держать хоть что-то в фоне вместе с Майном - это мой телефон (8гб ОЗУ) и телефон ЛегасиГеймера (6гб озу)
Коллаб не организуем по причине того, что у нас стек сети Java не изменён, да и его изменение уронило бы производительность ещё сильнее. Да и коммерческим челам писать как-то не хочется.

**Comment by pavel19108** [comment]
У меня 6 Гб + mali-g76 (10 ядер) + Kirin 980 (8 ядер) - не тянет

Точнее, тянет одиночную игру на 100 ФПС 8 чанков (в стандартной игре 150 - основная нагрузка на ГП), но завершение LAN-а этого всё ломает в онлайне на этом индустриальном д***е

**Comment by artdeell** [comment]
Мда
Если это конечно очень надо, то можно
Но я кого-то не хочу на коллаб уговаривать

**Comment by artdeell** [comment]
Возможно остальная команда не согласится

**Comment by pavel19108** [comment]
@artdeell, это всё-таки предложение, а не баг репорт, это не сильно важно)

**Comment by nedogimov** [comment]
> **Проблема**
> 
> Здравствуйте, я столкнулся с проблемой: при попытке игры с другом на ПК через ZeroTier One (аналог Hamachi, только кроссплатформенный) приложение начинает закрываться при подключении (большая сборка модов - 44 штуки) в связи с недостатком оперативной памяти (2 Гб свободного места, 1 Гб - кешированные, их можно удалить для загрузки на сервер). Требуется 2.5 Гб оперативки для подключения, но при этом в данные для удаления входит и ZeroTier, который система считает неважным.
> 
> Начало загрузки: ![Screenshot_20210210_222120_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/77898934/107561570-be5c2e00-6bef-11eb-9fca-77f06a0a4b03.jpg)
> А становится во время загрузки:![Screenshot_20210210_221513_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/77898934/107561633-d338c180-6bef-11eb-822d-df798e06b5ea.jpg)
> (Если не понятно, значок vpn пропал)
> Разница во времени из-за того, что это разные заходы были
> 
> Потом выдаёт либо ошибку "отключение", либо "программа на вашем хост-компьютере разорвала установленное подключение".
> 
> Исключение из автоматического завершения процесса андроидом не помогает.
> 
> **ВНИМАНИЕ: для подключения к компьютеру через офлайн учётку надо установить мод "Custom LAN Ports" или "Server Properties" и в нём выключить "online mode"**
> 
> **Предлагаемое решение**
> Единственное, как можно будет решить данную проблему - совместить лаунчер и кроссплатформенную виртуальную локальную сеть в одном приложении, т.е., грубо говоря, организовать коллаб с тем разработчиком... Да, задача не простая, но, теоретически, решить её возможно...
> 
> P.s. Конечно, можно создать на компьютере глобальный сервер, который не потребует дополнительных программ, однако такой вариант сложнее для большинства игроков.
> 
> Как думаете, возможно ли это реализовать? Или придётся идти обходным путём для тяжёлых сборок?

Проблема в таск-киллере, без рута никак.
На хоноре его получить проблематично

**Comment by pavel19108** [comment]
Наверное всё-таки плохая идея, так что закрываю - реализация этого если и произойдёт, то не раньше выхода в Google play.
