### ISSUE TITLE
[BUG] Version Did Not Load on Offline.

### ISSUE THREAD

**Issue by LanceYTStudioZ** [PojavLauncherTeam/PojavLauncher#843]
**Describe the bug**
The version did not load on offline mode.

**To Reproduce**
1. Start PojavLauncher
2. Go to profiles
3. No versions

**Screenshots**
![Screenshot_2021-02-11-09-13-40-28](https://user-images.githubusercontent.com/78294173/107593098-85e93e00-6c49-11eb-970e-1d825fcf4aa2.png)

**Platform:**
 - CPH1835/OPPO A12e
 - arm64/aarch64
 - Android 8.1.0 Oreo/Go Edition
 - Ram 3GB

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
I want to play 1.16.5 but versions did not load on offline. That's my problem.

**Comment by LanceYTStudioZ** [comment]
Hello

**Comment by AjGamingPHOfficial** [comment]
Ofcourse
Your offline
Bruh

**Comment by khanhduytran0** [comment]
Profiles cancelled.

**Comment by HarvPlayz** [comment]
How to download that
