### ISSUE TITLE
---- Minecraft Crash Report ----

### ISSUE THREAD

**Issue by LanceYTStudioZ** [PojavLauncherTeam/PojavLauncher#844]
// Who set us up the TNT?

Time: 2/11/21 1:58 AM
Description: Initializing game

java.lang.NoClassDefFoundError: com/ibm/icu/text/ArabicShapingException
	at dmv.a(SourceFile:160)
	at djz.<init>(SourceFile:507)
	at net.minecraft.client.main.Main.main(SourceFile:177)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.text.ArabicShapingException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 3 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dmv.a(SourceFile:160)
	at djz.<init>(SourceFile:507)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version Android-8.1.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 798967304 bytes (761 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	CPUs: 8
	JVM Flags: 26 total; -Xmx1G -Xms1G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10 -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: 9x null

**Comment by LanceYTStudioZ** [comment]
Who set up the TNT???

**Comment by khanhduytran0** [comment]
Delete .minecraft/com/ibm/icu and launch again

**Comment by khanhduytran0** [comment]
@LanceYTStudioZ enable libraries checker

**Comment by saksham22918** [comment]
HOW CAN I FIX OPTIFINE V.1.18.1 CRASH TEL ME

**Comment by WesleyVanNeck** [comment]
> HOW CAN I FIX OPTIFINE V.1.18.1 CRASH TEL ME

how about opening a issue and fucking wait patiently

**Comment by rybattousai** [comment]
> Delete .minecraft/com/ibm/icu and launch again

i cant delete it btw im using a chromebook
