### ISSUE TITLE
(БУГ) PojavLauncher Crashes during launch

### ISSUE THREAD

**Issue by FoxEdKr07** [PojavLauncherTeam/PojavLauncher#845]
**Describe the bug**
PojavLauncher takes off during launch 

**To Reproduce**
1. Start PojavLauncher 
...

**Expected behavior**
I was expecting the game to start, not relegation 

**Screenshots**

**Platform:**
 - Device Model [Samsung A21s]
 - CPU architecture [armeabi-v7a, armeabi] 
 - Android Version [10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
launcher version?
game version?
how much ram?
games/pojavlauncher/.minecraft/latestlog.txt?

**Comment by harsh-gupta-10** [comment]
Same happened with me I used latest pojav launcher, I tryed all. Game version

**Comment by fantom12403** [comment]
У меня проблема телефон самсунг галакси а12 при запуске поджава крокуса с модами вылетает и пишите ошибка приложения с кодом 1 уже всё перепробовал и не знаю что делать, подскажите пожалуйста может что то можно ещё сделать.
