### ISSUE TITLE
How To Play On Servers + A Bonus Server

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#846]
To Play On Minecraft Servers 

First

>Create An Account On Here

`tlauncher.org`

>Remember Your Nametag+Account Details

>Login Offline On Pojav 

>Go To Multiplayer, Add Server->Add Any Server You Wish

>Register And Play! 

•••••Remember!!  It Has a 10% chance to get banned!  On cracked Servers! •••••••••

Remember Your Login Info!!!! 

Bonus Server-> play.randomcraft.org

**Comment by artdeell** [comment]
10% chance of getting banned? y tho

**Comment by torfium** [comment]
some servers are not visible to me. Why?

**Comment by AgaricaGamer** [comment]
@artdeell  Maybe Admin Would Not Like That,
So I Recommend To Beware Of Telling This Information To Admins!

**Comment by AgaricaGamer** [comment]
@torfium What Do Mean Tho? 

Can You Send Me a Screenshot?

**Comment by LanceAldrei04** [comment]
> @torfium What Do Mean Tho?
> 
> Can You Send Me a Screenshot?

Use google

**Comment by LanceAldrei04** [comment]
> @torfium What Do Mean Tho?
> 
> Can You Send Me a Screenshot?

Search on google "what is tho"

**Comment by povkheangkh** [comment]
Can you make new update can sign in to tlaunchre pls

**Comment by OksmaWarez** [comment]
@povkheangkh are you dumb?

**Comment by CriticalRange** [comment]
I didn't understand what you meant. You meant login with the account details same as tlauncher but with login offline mode ?

**Comment by tkfmutsu** [comment]
> I didn't understand what you meant. You meant login with the account details same as tlauncher but with login offline mode ?

me too, how we have to sign in with tlauncher acc if we r in "offline mode" .-.?

**Comment by WesleyVanNeck** [comment]
> > I didn't understand what you meant. You meant login with the account details same as tlauncher but with login offline mode ?
> 
> me too, how we have to sign in with tlauncher acc if we r in "offline mode" .-.?

You can't login with a tlauncher login

**Comment by Mathias-Boulay** [comment]
That's not even an issue.
Closing it, I'm trying to reduce issues to only the real ones.
Devs don't need to waste their time on such "issues".
