### ISSUE TITLE
Minecraft (any version) crash after a few minutes.

### ISSUE THREAD

**Issue by HedHogie** [PojavLauncherTeam/PojavLauncher#847]
It crashes, any version I use, even fabric will crash, around 20 minutes into the game it will unexpectedly crash.

1. Start PojavLauncher
2. Run a version (usually 1.16.5)
3. Play for 20 minutes+ 
4. crash.
**Expected behavior**
I expected it to not crash, I tweaked a few things, got some advice from a expert, still not working though

**Screenshots**

**Platform:**
 - Device Model VivoY15
 - CPU architecture aarch64
 - Android Version 9

<details> <summary><b>Additional context</b></summary>
<br>
<pre>

**Comment by artdeell** [comment]
Log?

**Comment by yejunjie10311031** [comment]
It seems the same situation as mine:https://github.com/PojavLauncherTeam/PojavLauncher/issues/838
(Sorry for bad English)

**Comment by Mathias-Boulay** [comment]
Stale issue, no logs provided.
And closing it, as the user mentioned another issue as pretty much a duplicate

**Comment by SatsumaAMP** [comment]
Same issue exept 1.10 optifine usually it crashes when I try and walk or interact with things if I'm lucky I can get Maximum of 30 minutes in a under ground mine or cave
