### ISSUE TITLE
Making me go back to the launcher

### ISSUE THREAD

**Issue by Zaireeee** [PojavLauncherTeam/PojavLauncher#848]
Whenever i try to hit play i can see the controls for split seconds then it will go back to the launcher please help me

**Comment by khanhduytran0** [comment]
- Send the log

**Comment by Zaireeee** [comment]
--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl-openal.jar, lwjgl-glfw-classes.jar, lwjgl-opengl.jar, lwjgl-tinyfd.jar, version, lwjgl-stb.jar, lwjgl.jar, jsr305.jar, lwjgl-jemalloc.jar]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms384m -Xmx768m"
Headless version detected! (20170918)
--------- beginning of system
--------- beginning of main
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  ( 7891): WARNING: linker: 
I/jrelog  ( 7891): "
I/jrelog  ( 7891): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=
I/jrelog  ( 7891): 0x81
I/jrelog  ( 7891): 
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  ( 7891): WARNING: linker: 
I/jrelog  ( 7891): "
I/jrelog  ( 7891): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=
I/jrelog  ( 7891): 0x81
I/jrelog  ( 7891): 
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  ( 7891): WARNING: linker: 
I/jrelog  ( 7891): "
I/jrelog  ( 7891): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=
I/jrelog  ( 7891): 0x81
I/jrelog  ( 7891): 
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  ( 7891): WARNING: linker: 
I/jrelog  ( 7891): "
I/jrelog  ( 7891): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): 
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): WARNING: linker: 
I/jrelog  ( 7891): "
I/jrelog  ( 7891): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=
I/jrelog  ( 7891): 0x81
I/jrelog  ( 7891): 
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
I/jrelog  ( 7891): WARNING: linker: 
I/jrelog  ( 7891): "
I/jrelog  ( 7891): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=
I/jrelog  ( 7891): 0x81
I/jrelog  ( 7891): 
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 7891): 0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 7891): 0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so success
I/jrelog  ( 7891): WARNING: linker: "
I/jrelog  ( 7891): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): 
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so
I/jrelog  ( 7891): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 7891): 0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so success
I/jrelog  ( 7891): WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 7891): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success
I/jrelog  ( 7891): dlopen /data/app/net.kdt.pojavlaunch-7Q-PENl_WKihKt8yCJbtXg==/lib/arm/libopenal.so success
I/jrelog  ( 7891): dlopen /data/app/net.kdt.pojavlaunch-7Q-PENl_WKihKt8yCJbtXg==/lib/arm/libgl04es.so success
I/jrelog  ( 7891): Done processing args
I/jrelog  ( 7891): Found JLI lib
I/jrelog  ( 7891): Calling JLI_Launch
I/jrelog  ( 7891): OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/jrelog  ( 7891): Error occurred during initialization of VM
I/jrelog  ( 7891): Could not reserve enough space for 768000KB object heap
I/jrelog  ( 7891):

**Comment by Zaireeee** [comment]
Soo is it bad?

**Comment by khanhduytran0** [comment]
32bit has limited RAM! Reduce to 512 or 384 and try again.

**Comment by Zaireeee** [comment]
How can i reduce it? I checked the options and settings of the launcher but i didnt see any, only the RAM limiter

**Comment by khanhduytran0** [comment]
Go to jvm arguments, then edit it

**Comment by Zaireeee** [comment]
What am i gonna put in there? Im new to that im really sorry

**Comment by WesleyVanNeck** [comment]
> What am i gonna put in there? Im new to that im really sorry

Set auto ram off and set -xmx512m

**Comment by Zaireeee** [comment]
> > What am i gonna put in there? Im new to that im really sorry
> 
> Set auto ram off and set -xmx512m

It still not working

**Comment by khanhduytran0** [comment]
-X should be uppercase

**Comment by Zaireeee** [comment]
Its ok now thank you, but its really laggy is there a way to increase fps and whats the limit of 32-bit i can set in jvm argument?

**Comment by khanhduytran0** [comment]
It depends on your device. In this case you set max 512mb worked, so 512mb might be max RAM you can set.

**Comment by CriticalRange** [comment]
You can set up to 850 megabytes in 32 bit device and you can use forge or fabric mods to increase performance.

**Comment by Zaireeee** [comment]
Oh thanks and btw my specs are qualcomm snapdragon 435 1.40GHz and i have a 64gb ROM and 4gb RAM i hope my specs can run minecraft java

**Comment by Zaireeee** [comment]
And btw sadly i can only run upto 650 megabytes

**Comment by Zaireeee** [comment]
And btw sadly i can only run upto 650 megabytes

**Comment by Zaireeee** [comment]
And btw sadly i can only run upto 650 megabytes
