### ISSUE TITLE
Key Combination no longer works

### ISSUE THREAD

**Issue by LanceYTStudioZ** [PojavLauncherTeam/PojavLauncher#849]
Hi PojavLauncherTeam bring back the key combination like Pri + LShift, F3 + Q, F3 + F4 and many more.

**Comment by nedogimov** [comment]
> Hi PojavLauncherTeam bring back the key combination like Pri + LShift, F3 + Q, F3 + F4 and many more.

you can create such keyboard shortcuts yourself.

**Comment by kavyansh-glitch** [comment]
How

**Comment by LanceAldrei04** [comment]
> > Hi PojavLauncherTeam bring back the key combination like Pri + LShift, F3 + Q, F3 + F4 and many more.
> 
> you can create such keyboard shortcuts yourself.

Keyboard shortcut?

**Comment by kavyansh-glitch** [comment]
Please its a bug not a enhancement please label it bug

**Comment by LanceAldrei04** [comment]
Bring back key combination like F3 + F4 (Change Game Mode Fast), Shift + Tab (Fast insert items to the chest) and many more.

**Comment by khanhduytran0** [comment]
If you want, come back to v3_openjdk, don't touch to profiles builds branch.

**Comment by khanhduytran0** [comment]
**We are stupid if removes useful features - don't you think it's bugged instead?**

**Comment by khanhduytran0** [comment]
@LanceYTStudioZ Please tell us which build that key combination stopped working.

**Comment by khanhduytran0** [comment]
Profiles cancelled, back to v3 branch.
