### ISSUE TITLE
[Request] Add a File Cleaner (i don't think this is a good idea)

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#85]
Add a file cleaner for not important files because my phone is always keep fulling memory so i need to balance the storage

**Comment by FranzelDamasco909** [comment]
(idk)

**Comment by khanhduytran0** [comment]
This launcher don't have anything to clean unless OptiFine installer converted.

**Comment by FranzelDamasco909** [comment]
ok i knew that this idea is useless, sorry for you interruptions...
