### ISSUE TITLE
вопрос¿

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#850]
что эффективнее "boat app" или "gl4es" для заспуска minecraft je?

**Comment by nedogimov** [comment]
> что эффективнее "boat app" или "gl4es" для заспуска minecraft je?
> 

Скорее gl4es

**Comment by artdeell** [comment]
> что эффективнее "boat app" или "gl4es" для заспуска minecraft je?

это две абсолютно разные вещи
