### ISSUE TITLE
Can someone help me i cant download versions and please dont delete this please help me

### ISSUE THREAD

**Issue by Mynameispoop** [PojavLauncherTeam/PojavLauncher#851]

**Comment by khanhduytran0** [comment]
Are you on profile build?

**Comment by Mynameispoop** [comment]
I cant send the video

**Comment by Mynameispoop** [comment]
> Are you on profile build?

Yes

**Comment by Mynameispoop** [comment]
I keep pressing on 21w06a then clickinh default and renaming it to 21w06a then save then i hit play

**Comment by khanhduytran0** [comment]
Didn't you press new?

**Comment by Mynameispoop** [comment]
Theres no new button

**Comment by Mynameispoop** [comment]
Im so sorry for wasting ur time i didnt realoze that there is a new build im so sorry
