### ISSUE TITLE
[F-REQ] add mod installer not only forge and optifine.

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#853]
Add a mod intaller for all mods not only forge and optifine.

**Comment by nedogimov** [comment]
> Add a mod intaller for all mods not only forge and optifine.

try latest profile branch dev build.

**Comment by khanhduytran0** [comment]
Already functional. Including
- Labymod 
![](https://media.discordapp.net/attachments/755410958100201472/809217154855206923/Screenshot_20210211-081950_PojavLauncher_Minecraft_Java_Edition_for_Android.jpg)

- Impact
![](https://user-images.githubusercontent.com/40482367/106972126-d3b20200-6782-11eb-97c4-3c6691df3067.png)

And more!

**Comment by poopipie** [comment]
it don't work on mine i got stuck at can't get more log and nothing is showing up

**Comment by poopipie** [comment]
> Already functional. Including
> 
> * Labymod
>   ![](https://camo.githubusercontent.com/cca365f2d04e56e8cab0e720d8aa534a602d9375a7eb78e1e037e70f1e05c996/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3735353431303935383130303230313437322f3830393231373135343835353230363932332f53637265656e73686f745f32303231303231312d3038313935305f506f6a61764c61756e636865725f4d696e6563726166745f4a6176615f45646974696f6e5f666f725f416e64726f69642e6a7067)
> * Impact
>   ![](https://user-images.githubusercontent.com/40482367/106972126-d3b20200-6782-11eb-97c4-3c6691df3067.png)
> 
> And more!

help 

> Already functional. Including
> 
> * Labymod
>   ![](https://camo.githubusercontent.com/cca365f2d04e56e8cab0e720d8aa534a602d9375a7eb78e1e037e70f1e05c996/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3735353431303935383130303230313437322f3830393231373135343835353230363932332f53637265656e73686f745f32303231303231312d3038313935305f506f6a61764c61756e636865725f4d696e6563726166745f4a6176615f45646974696f6e5f666f725f416e64726f69642e6a7067)
> * Impact
>   ![](https://user-images.githubusercontent.com/40482367/106972126-d3b20200-6782-11eb-97c4-3c6691df3067.png)
> 
> And more!

help nothing is showing up im using latest profile branch dev build

**Comment by poopipie** [comment]
![Screenshot_20210225_043002_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/78753330/109062003-5430a680-7722-11eb-9a61-a147743063ed.jpg)
![Screenshot_20210225_042952_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/78753330/109062013-585cc400-7722-11eb-9eca-e7a212dc3b38.jpg)
