### ISSUE TITLE
[BUG] I click on the symbol, but it is not inserted in the game (@ "* '§)

### ISSUE THREAD

**Issue by SiergoMakatao** [PojavLauncherTeam/PojavLauncher#854]
And the question is why not entering characters on a 32-bit device, but you can enter unnecessary (× Ωμ ™ ® ©) why?
 Answer?
(translated Google translator)
More details: I click (use GBoard) on a symbol in the game, (symbol @ "* '§)
 As if in GBoard it is pressed but the symbol is not put in the game !!!

**Comment by nedogimov** [comment]
> And the question is why not entering characters on a 32-bit device, but you can enter unnecessary (× Ωμ ™ ® ©) why?
>  Answer?
> (translated Google translator)

GBoard is used?

**Comment by SiergoMakatao** [comment]
Yes

**Comment by ghost** [comment]
я использую gboard, тоже самое

**Comment by nedogimov** [comment]
> я использую gboard, тоже самое

these symbols do not seem to be translate 
with the Russian layout it used to be like that too

**Comment by artdeell** [comment]
старая версия лаунчера
old launcher version

**Comment by Mathias-Boulay** [comment]
Such symbols works now on the google play release.
Closing the issue.
