### ISSUE TITLE
[BUG]forge from 1.7.10 till 1.12 can't install

### ISSUE THREAD

**Issue by notpvpking** [PojavLauncherTeam/PojavLauncher#856]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Are you lazy to fill the template?

**Comment by khanhduytran0** [comment]
@notpvpking ?..

**Comment by khanhduytran0** [comment]
Hmm.. I replied as soon as you submit issue, but stills not get respond.
