### ISSUE TITLE
[force close]

### ISSUE THREAD

**Issue by aditgamink** [PojavLauncherTeam/PojavLauncher#857]
**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Are you too lazy to fill the template please?

**Comment by khanhduytran0** [comment]
Please reply @aditgamink

**Comment by khanhduytran0** [comment]
Hmm.. I replied as soon as you submit issue, but stills not get respond.
