### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by Pxtixnce** [PojavLauncherTeam/PojavLauncher#860]
When I open the app and run 1.7.10(actually it doesn't open any version) it just crashes and it doesn't even show the crash report in the menu.
What I think is that it's using a lot of ram and my mobile can't even run it,what I suggest is to put an option where u can put custom ram so it won't crash any on any mobiles.
My mobile:Moto g5s 4 GB ram 32 GB rom

**Comment by artdeell** [comment]
just edit -Xms and -Xmx yourself

why people are so lazy these days

**Comment by Pxtixnce** [comment]
I tried it but it's not working

**Comment by artdeell** [comment]
then disable auto ram
if it still crashes then you allocated too much

**Comment by Pxtixnce** [comment]
Ok,but I might be wrong so for 4GB how much should I put in -xms and -xmx

**Comment by Pxtixnce** [comment]
So I tweaked around and it worked thank u so much and soo sorry for have
wasted your time
