### ISSUE TITLE
[BUG] idk if this is a bug or not but when i download a version theres no .minecraft to my files i wanted to install optifine but theres no .minecraft on my games file 

### ISSUE THREAD

**Issue by Thein793** [PojavLauncherTeam/PojavLauncher#861]
Hi i just asking why are there no .minecraft on my games files i just want to download optifine thats it:(

<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by artdeell** [comment]
bruh, why y'all using a bug report template

also

enable hidden files in your file explorer
