### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by Pxtixnce** [PojavLauncherTeam/PojavLauncher#862]
I downloaded 1.16 and tried it but when I launch it it says "Application/game exited with code 1" I tried all other versions and they work but all the 1.16 versions don't work.

**Comment by khanhduytran0** [comment]
Please send the latestlog.txt

**Comment by Pxtixnce** [comment]
I have sent it

**Comment by khanhduytran0** [comment]
I didn't see anywhere in this issue.

**Comment by Pxtixnce** [comment]
Please check now.

**Comment by khanhduytran0** [comment]
I didn't see anywhere, **seriously**!

![5CC4EDCC-8204-4A85-ABEF-A85BBF08C117](https://user-images.githubusercontent.com/40482367/107731170-d767fa80-6d27-11eb-84a4-ca457cf48b38.png)

**Comment by Pxtixnce** [comment]
I have sent it to this email
reply@reply.github.com

**Comment by Pxtixnce** [comment]
If you didn't get it the here it is

--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar,
lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar,
lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm/aarch32
Info: Custom Java arguments: "-Xms384m -Xmx450m"
--------- beginning of main
Headless version detected! (20200623)
I/jrelog  (18983): Starting logging STDIO as jrelog:V
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so
success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
I/jrelog  (18983): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so
success
I/jrelog  (18983): dlopen
/data/app/net.kdt.pojavlaunch-HLsyftqJOOt4_GQrmbBIUQ==/lib/arm/libopenal.so
success
I/jrelog  (18983): dlopen
/data/app/net.kdt.pojavlaunch-HLsyftqJOOt4_GQrmbBIUQ==/lib/arm/libgl04es.so
success
I/jrelog  (18983): Done processing args
I/jrelog  (18983): Found JLI lib
I/jrelog  (18983): Calling JLI_Launch
I/jrelog  (18983): Error: Could not create the Java Virtual Machine.
I/jrelog  (18983): Error: A fatal exception has occurred. Program will exit.
I/jrelog  (18983):
I/jrelog  (19935): Starting logging STDIO as jrelog:V
I/jrelog  (19935): WARNING: linker:
I/jrelog  (19935): "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so" has
unsupported flags DT_FLAGS_1=
I/jrelog  (19935): 0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so
success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so
success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so
success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so
success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so
success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so
success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/liblcms.so success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so
success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmanagement.so
success
I/jrelog  (19935): WARNING: linker:
I/jrelog  (19935): "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=
I/jrelog  (19935): 0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so"
has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libmlib_image.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so
success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsunec.so success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libunpack.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so
success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnpt.so success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so
success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libtinyiconv.so
success
I/jrelog  (19935): WARNING: linker:
I/jrelog  (19935):
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libzip.so success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so" has
unsupported flags DT_FLAGS_1=
I/jrelog  (19935): 0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so
I/jrelog  (19935): " has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so
success
I/jrelog  (19935): WARNING: linker:
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libsctp.so success
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so
success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so" has
unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success
I/jrelog  (19935): WARNING: linker: "
I/jrelog  (19935):
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so"
has unsupported flags DT_FLAGS_1=0x81
I/jrelog  (19935): dlopen
/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so
success
I/jrelog  (19935): dlopen
/data/app/net.kdt.pojavlaunch-HLsyftqJOOt4_GQrmbBIUQ==/lib/arm/libopenal.so
success
I/jrelog  (19935): dlopen
/data/app/net.kdt.pojavlaunch-HLsyftqJOOt4_GQrmbBIUQ==/lib/arm/libgl04es.so
success
I/jrelog  (19935): Done processing args
I/jrelog  (19935): Found JLI lib
I/jrelog  (19935): Calling JLI_Launch
I/jrelog  (19935): OpenJDK Client VM warning:
I/jrelog  (19935): No monotonic clock was available - timed services may be
adversely affected if the time-of-day clock changes
I/jrelog  (19935):
I/jrelog  (19935): Exception in thread "main"
I/jrelog  (19935): java.lang.NoClassDefFoundError:
io/netty/util/internal/ThreadLocalRandom
I/jrelog  (19935):
I/jrelog  (19935): at aoe.a(SourceFile:162)
I/jrelog  (19935): at aoi.<clinit>(SourceFile:12)
I/jrelog  (19935): at gl.V(SourceFile:168)
I/jrelog  (19935):
I/jrelog  (19935): at gl.a(SourceFile:220)
I/jrelog  (19935):
I/jrelog  (19935): at
java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
I/jrelog  (19935): at gl.<clinit>(SourceFile:219)
I/jrelog  (19935): at uj.a(SourceFile:41)
I/jrelog  (19935): at net.minecraft.client.main.Main.main(SourceFile:137)
I/jrelog  (19935):
I/jrelog  (19935): Caused by: java.lang.ClassNotFoundException:
io.netty.util.internal.ThreadLocalRandom
I/jrelog  (19935): at
java.net.URLClassLoader.findClass(URLClassLoader.java:382)
I/jrelog  (19935):
I/jrelog  (19935): at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
I/jrelog  (19935):
I/jrelog  (19935): at
sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
I/jrelog  (19935): at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
I/jrelog  (19935): ... 8 more
I/jrelog  (19935):
Java Exit code: 1
I/jrelog  (19935): Going to free args
I/jrelog  (19935): Free done

**Comment by khanhduytran0** [comment]
Delete .minecraft/libraries/io/netty and launch again.
(Seems github reply via email does not support sending files, so plesse come to github web or app to send files)

**Comment by Pxtixnce** [comment]
Will do, thanks!

**Comment by Pxtixnce** [comment]
---- Minecraft Crash Report ----
// You're mean.

Time: 2/12/21 5:07 AM
Description: Initializing game

java.lang.NoClassDefFoundError: com/ibm/icu/text/ArabicShapingException
at dmv.a(SourceFile:160)
at djz.<init>(SourceFile:507)
at net.minecraft.client.main.Main.main(SourceFile:177)
Caused by: java.lang.ClassNotFoundException:
com.ibm.icu.text.ArabicShapingException
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 3 more


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at dmv.a(SourceFile:160)
at djz.<init>(SourceFile:507)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Linux (arm) version Android-8.1.0
Java Version: 1.8.0-internal, Oracle Corporation
Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
Memory: 179642680 bytes (171 MB) / 389349376 bytes (371 MB) up to 456130560
bytes (435 MB)
CPUs: 8
JVM Flags: 2 total; -Xms384m -Xmx450m
Launched Version: 1.16.5
Backend library: LWJGL version 3.2.3 SNAPSHOT
Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
GL Caps: Using framebuffer using ARB_framebuffer_object extension
Using VBOs: Yes
Is Modded: Probably not. Jar signature remains and client brand is
untouched.
Type: Client (map_client.txt)
CPU: 9x ARMv7 Processor rev 4 (v7l)

**Comment by khanhduytran0** [comment]
Delete .minecraft/libraries/com/ibm/icu

**Comment by Pxtixnce** [comment]
Ok will do

**Comment by Pxtixnce** [comment]
OMG IT WORKED!!! THANK YOU SO MUCH
Suggestion:How about adding a button where u can have shortcuts of commands
like mcinabox 0.1.4 p5 so it's makes it much easier to toggle gamemode and
you could put an option where it allows us to put custom commands as
shortcuts.

Once again, THANK YOU SO MUCH AND ALL THE BEST!!

**Comment by Pxtixnce** [comment]
> I didn't see anywhere, **seriously**!
> 
> ![5CC4EDCC-8204-4A85-ABEF-A85BBF08C117](https://user-images.githubusercontent.com/40482367/107731170-d767fa80-6d27-11eb-84a4-ca457cf48b38.png)

I have sent

**Comment by Pxtixnce** [comment]
Thanks again
