### ISSUE TITLE
[BUG] Cant join on servers always saying timed out and disconnected and my wifi is 7ms

### ISSUE THREAD

**Issue by Mynameispoop** [PojavLauncherTeam/PojavLauncher#863]

**Comment by khanhduytran0** [comment]
Make sure you logged in premium account if you play premium server.

**Comment by Mynameispoop** [comment]
Nope i didnt play premium server

**Comment by HedHogie** [comment]
Play on servers like Minemalia,

**Comment by xanning** [comment]
? Why would someone play on different server that doesnt he want because of app bug
Happening to me also
