### ISSUE TITLE
[F-REQ] More Java Options

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#867]
**Is your feature request related to a problem? Please describe.**
Yes, is related to a performance problem and incompatibility with some servers.

**Describe the solution you'd like**
More options for installing other versions of JRE 8 (x32, x64 and x86), JRE 9 and etc
(All packed inside the launcher, to facilitate the change and installation)

**Describe alternatives you've considered**
A configuration to remove and install any version of the Java adapted so far, even if errors and bugs occur.

**Additional context**
Nothing for now

**Comment by WesleyVanNeck** [comment]
All other have versions are slow so no

**Comment by WesleyVanNeck** [comment]
Also size of apk gets to big then

**Comment by ghost** [comment]
So in the future this will need to be some way optimized. There are different types of phones and emulators, okay that for now changing Java version will not improve anything. But the recommended is to use the ideal version for each architecture
My phone for example is x64 and uses the x32 version, don't make much sense. Anyway, thanks for your answer <3

**Comment by artdeell** [comment]
Note: some phones are `64-bit (32-bit mode)`, whish means that they are running a 32-bit OS on a 64-bit CPU. And we can't change that.

**Comment by khanhduytran0** [comment]
> JRE9

You want the slowness of java9?...

**Comment by khanhduytran0** [comment]
Installing other architectures are already completely automatically.

**Comment by khanhduytran0** [comment]
> A configuration to remove and install any version of the Java adapted so far, even if errors and bugs occur.

You want everyone start to submit issue about installing buggy JRE? 👀
Also, Android **is not** a Linux distro, getting a JRE version to run on Android requires a lot of hard work on it, unlike Linux just `apt install java-<version>-openjdk` and go.

**Comment by ghost** [comment]
I didn't stop to think about this all, if the process is already done automatically and most architectures are already supported... I don't see any problems. 

Thank you for your clarification and attention :D
