### ISSUE TITLE
[BUG] Not supports Yandex Keyboard

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#868]
Yandex Keyboard is not working (on phone). I used GBoard and it works. But when i switched to Yandex Keyboard it doesn't work. I can't write anything.

0. Install Yandex Keyboard and turn On it
1. Start PojavLauncher
2. Then start Minecraft
3. Create/Joint the World
4. Open Chat and tap on "Keyboard"
5. Try to write something

 - Device Model: Xiaomi Redmi Note 8 64/4 (64 Bit)
 - Android Version: 10/9 (It can be reproduced on both versions)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
I tested it before Updating system to MIUI 12 (when i have Android 9) and Yandex Keyboard didn't work. After 2 days i Updated my system to MIUI 12 (Android 10 Based) and tested it again, but nothing changed.

_Sorry for bad English._
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
Known use gboard

**Comment by FenixGlobElite** [comment]
**_Note: I am using 3.3.1 Release_**

**Comment by ghost** [comment]
> Known use gboard

Ok, thanks

**Comment by artdeell** [comment]
Yandex keybosrd is supported since 3.3.1.1

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
