### ISSUE TITLE
[F-REQ] Adding PojavLauncher to other android apk service platforms

### ISSUE THREAD

**Issue by CriticalRange** [PojavLauncherTeam/PojavLauncher#869]
**Is your feature request related to a problem? Please describe.**

If it's added it might be cool , like using apk mirror.
More people would find it easier this way, because after runtime added inside the launcher, it become easier. From choosing the runtime, waiting for it to load   to    just downloading the apk then starting to play
**Describe the solution you'd like**

**Describe alternatives you've considered**

https://www.apkmirror.com/apk-upload/

**Additional context**

**Comment by ghost** [comment]
fdroid?

**Comment by CriticalRange** [comment]
Yeah, droid may be too

**Comment by artdeell** [comment]
Pojav won't get on F-Droid because it downloads closed-source binaries (Minecraft)

**Comment by artdeell** [comment]
You can always try though

**Comment by CriticalRange** [comment]
@artdeell Try ? Can we try uploading ?

**Comment by CriticalRange** [comment]
@artdeell Can i try uploading it ? Please answer

**Comment by CriticalRange** [comment]
Oh you said you can always try, sorry for ping

**Comment by CriticalRange** [comment]
Progress on f-droid
![IMG_20210826_170141](https://user-images.githubusercontent.com/29708696/130978488-5bb69fac-a94b-4147-8335-642272a95993.jpg)

**Comment by mutageneral** [comment]
any progress on this getting in fdroid?

**Comment by rscDMTalt** [comment]
:realtroll: ~~wHy fDroId wHen iTs oN pLaYstoRe~~

**Comment by ghost** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1835
Any plans to work on this further in the near future? Having this app available on F-Droid would be very welcome.

**Comment by artdeell** [comment]
> https://gitlab.com/fdroid/rfp/-/issues/1835 Any plans to work on this further in the near future? Having this app available on F-Droid would be very welcome.

F-Droid requires us to add a changelog and do tags, which we don't even for gplay updates. Putting pojav on f-droid with how the dev cycle is right now would be very inefficent (and updates would be very rare)

**Comment by ghost** [comment]
> > https://gitlab.com/fdroid/rfp/-/issues/1835 Any plans to work on this further in the near future? Having this app available on F-Droid would be very welcome.
> 
> F-Droid requires us to add a changelog and do tags, which we don't even for gplay updates. Putting pojav on f-droid with how the dev cycle is right now would be very inefficent (and updates would be very rare)

Darn sucks. I would admit it is still desirable even if it means a delayed amount of updates but thanks for the update.
Does this project by chance accept bounties? Its not much but I'd be willing to put around 10 EUR on this or something

**Comment by CriticalRange** [comment]
> > > https://gitlab.com/fdroid/rfp/-/issues/1835 Any plans to work on this further in the near future? Having this app available on F-Droid would be very welcome.
> > 
> > 
> > F-Droid requires us to add a changelog and do tags, which we don't even for gplay updates. Putting pojav on f-droid with how the dev cycle is right now would be very inefficent (and updates would be very rare)
> 
> Darn sucks. I would admit it is still desirable even if it means a delayed amount of updates but thanks for the update. Does this project by chance accept bounties? Its not much but I'd be willing to put around 10 EUR on this or something

You can always sponsor the project :)

**Comment by NebulaBC** [comment]
> > > > https://gitlab.com/fdroid/rfp/-/issues/1835 Any plans to work on this further in the near future? Having this app available on F-Droid would be very welcome.
> > > 
> > > 
> > > F-Droid requires us to add a changelog and do tags, which we don't even for gplay updates. Putting pojav on f-droid with how the dev cycle is right now would be very inefficent (and updates would be very rare)
> > 
> > 
> > Darn sucks. I would admit it is still desirable even if it means a delayed amount of updates but thanks for the update. Does this project by chance accept bounties? Its not much but I'd be willing to put around 10 EUR on this or something
> 
> You can always sponsor the project :)

I believe he is speaking of a bounty for someone to get this working and submit a PR.

Imo it would be really nice to have Pojav on FDroid, making tags for releases is such a minimal thing, and the changelog could straight up be the autogenerated list of commits or a “bug fixes and features. check github” like plenty of projects do.
