### ISSUE TITLE
Good idea! 

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#87]
Please add option to set max RAM for Minecraft.

And I found a bug: Launcher crashes when I quit from game.

(sorry for bad english)

**Comment by khanhduytran0** [comment]
> Please add option to set max RAM for Minecraft.

There's no way to set max RAM for Minecraft.

> And I found a bug: Launcher crashes when I quit from game.

I may try to fix later.

**Comment by Azapru** [comment]
> There's no way to set max RAM for Minecraft.

Why?

In official launcher this option works.

**Comment by khanhduytran0** [comment]
Official launcher use Java VM/JRE, which easy to change max RAM.
This launcher use ART which hard to set max RAM.

**Comment by Azapru** [comment]
:(
