### ISSUE TITLE
баг в последнем билде

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#870]
не работают комбинации клавиш по типу левыйклик+шифт
**бонус**
символы @"'*§ до сих пор не работают
**Platform:**
 - Device Model [redmi note 8 Pro 6/64]
 - CPU architecture [aarch64] 
 - Android Version [10]

**Comment by nedogimov** [comment]
> не работают комбинации клавиш по типу левыйклик+шифт
> **бонус**
> символы @"'*§ до сих пор не работают
> **Platform:**
>  - Device Model [redmi note 8 Pro 6/64]
>  - CPU architecture [aarch64] 
>  - Android Version [10]
> 
> 

Символы не фиксили ещё.

**Comment by Mathias-Boulay** [comment]
non duplicate issues in this post are fixed.
Closing
