### ISSUE TITLE
[BUG]Hello I can not download forge 1.12.2 gives an error The application/game failed with code 1 pojavlauncher version 3.3.1.1 What should I do?

### ISSUE THREAD

**Issue by Loolgit** [PojavLauncherTeam/PojavLauncher#871]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Honor 7c 3/32]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 8]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Dimon245** [comment]
Honestly, I'd had the same problem on the latest builds, so I just used the older builds to install forge xd

**Comment by khanhduytran0** [comment]
> What should I do?

@Loolgit Fill the **template**! 

> Make sure you have filled this issue template, or this will get rejected.
