### ISSUE TITLE
[F-REQ] NBT explorer.

### ISSUE THREAD

**Issue by AgaricaGamer** [PojavLauncherTeam/PojavLauncher#874]
**Is your feature request related to a problem? Please describe.**

>Some Features Won't Work, Such As The Color And Lore And Its Very Hard For Beginners To Learn Those Tricky Long Commands! 

**Describe the solution you'd like**

>Add An NBT Explorer For Pojav

**Describe alternatives you've considered**

`Create Another App For It`
>I Hope That This Project May Be Started

**Additional context**

**Comment by khanhduytran0** [comment]
For exploring NBT things, you could use other apps on Play Store. This app is only focus for running Minecraft: Java Edition on Android.

**Comment by khanhduytran0** [comment]
Also, we don’t have plan to make NBT explorer, it could postpone the development of this project.

**Comment by AgaricaGamer** [comment]
Ok, thanks for letting me know.

**Comment by Mathias-Boulay** [comment]
Closing the issue as it is neither the intention of the launcher, neither the current plan.
