### ISSUE TITLE
Question: Are you going to update OpenGL? What is needed for this? Why can't we use OpenGL ES 3.2?

### ISSUE THREAD

**Issue by QuasyStellar** [PojavLauncherTeam/PojavLauncher#875]

**Comment by artdeell** [comment]
1. Contact ptitSeb
2. Contact ptitSeb
3. Contact ptitSeb

**Comment by khanhduytran0** [comment]
> Why can't we use OpenGL ES 3.2?

Do you know the difference between Desktop OpenGL and OpenGL ES?

**Comment by QuasyStellar** [comment]
Sadly, no.

**Comment by artdeell** [comment]
There are a LOT of differences

**Comment by artdeell** [comment]
So we use a shim called gl4es made by ptitSeb

**Comment by khanhduytran0** [comment]
Also duplicate your #547
