### ISSUE TITLE
Pojavlauncher successfully load shaders based on opengl es,but there is a bug on Kirin cpu.

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#876]
The shader is made by a friend of mine,and it works well on Snapdragon cpu.But there is a bug on Kirin cpu:The distant scene was shaded.
(Sorry for bad English)
![Screenshot_20210213_220447_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/107852102-b2968480-6e06-11eb-8182-e028d3a49dfd.jpg)
![Screenshot_20210213_220501_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/107852108-b88c6580-6e06-11eb-9724-fd5239b2619d.jpg)
![Screenshot_20210213_220530_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/107852109-ba562900-6e06-11eb-9ada-995db929f9ce.jpg)
![Screenshot_20210213_220545_net kdt pojavlaunch](https://user-images.githubusercontent.com/62139629/107852110-bc1fec80-6e06-11eb-948e-72da477292fc.jpg)

**Comment by QuasyStellar** [comment]
Wow! Link?

**Comment by yejunjie10311031** [comment]
You can get the shader from there ::https://pan.baidu.com/s/1YNNrCLCE6-E7oLa1JMYubQ  Password:3agr
Please don't give the shader to others because the author said it hasn't been finished.

**Comment by QuasyStellar** [comment]
Thx, dont worry. I dont give shaders for other people. Sorry for bad english.

**Comment by yejunjie10311031** [comment]
What's more,the shader only works on Minecraft1.12.2~1.16.5

**Comment by QuasyStellar** [comment]
I think you should delete this comm. Because many people can distribute it.

**Comment by QuasyStellar** [comment]
Creator is shulker? I see his video.

**Comment by yejunjie10311031** [comment]
@kvazar-git Yes,but Shulker is one of the developers.

**Comment by ghost** [comment]
обмен файламм прекращён;(

**Comment by artdeell** [comment]
Open4ES, isn't it?

**Comment by Vindows95** [comment]
Hello yejunjie10311031,you shader is so cool.Can you give me?
I am a middle school student in China,please.

**Comment by yejunjie10311031** [comment]
@Vindows95 Sorry,I only want the development team to fix the shader problem on kirin cpu devices,but not to share it with others.

**Comment by yejunjie10311031** [comment]
@Vindows95 It's not my shader

**Comment by yejunjie10311031** [comment]
@Vindows95 首先，这个光影不能外传，然后，我来告诉pojavlauncher开发团队说pojavlauncher在华为设备上的bug

**Comment by Vindows95** [comment]
我之前看到过你发的百度网盘链接，我没办法直接下载，能不能在QQ上联系？
拜托了，那个光影真的很好看，我保证不会泄露的，我泄露我就是小狗。

**Comment by QuasyStellar** [comment]
Can you help me with wechat reg. I cant install from this site.

**Comment by LanceAldrei04** [comment]
Can i try plz

**Comment by yejunjie10311031** [comment]
@lalalalalalalalalalalalalalalalalala000 I feel sorry that I can't give the shader to you.
First,I have comment the download link yesterday evening but it was deleted by PojavLauncherTeam,so you'd better not talk about the shader again.
Second,the shader is not finished,it has many bugs,but I told the download link to others yesterday,I broke the treaty.
But you can rest assured because the shader will be published to all people when the shader's auther finishes making it.
(Sorry for bad English)

**Comment by yejunjie10311031** [comment]
@artdeell Please don't show the shader to others if you download the shader from the download link which I comment yesterday.Because the shader is in the test phase,it can't be published until the shader's auther finishes making it.

**Comment by QuasyStellar** [comment]
> @artdeell Please don't show the shader to others if you download the shader from the download link which I comment yesterday.Because the shader is in the test phase,it can't be published until the shader's auther finishes making it.

Hi, plz, take a look at the repository " - ".

**Comment by yejunjie10311031** [comment]
It can be closed now.

**Comment by QuasyStellar** [comment]
https://youtu.be/USTLaJ589R8

**Comment by QuasyStellar** [comment]
I want to test it with this texturepack.

**Comment by yejunjie10311031** [comment]
@kvazar-git I really feel sorry,I can't give the shader to others now.Because I told the download link to others yesterday evening,today some people come to find me and said that I broke GPL license(Because I spread it without author's agreement),it really brings a lot of trouble to me.
What's more,I can't tell you my contact information now because it may bring more trouble to me.
But don't be worried,I will tell you my Twitter mailbox and send the shader file to you after the author publishes the shader formally.

**Comment by QuasyStellar** [comment]
Ok.

**Comment by OwzygZawg** [comment]
What name shaders?????

**Comment by yanluol** [comment]
how to install open4es

**Comment by OwzygZawg** [comment]
Please can pass me link shader pls

**Comment by ShulkerSakura** [comment]
你不用一直在这发来发去的告诉Pojav什么的，Pojav开发者artDev就在我们群里一起合作开发，不用你来这里装大头，谢谢。

**Comment by ShulkerSakura** [comment]
而且你根本就不知道手机上怎么渲染的OpenGL画面，手机上渲染用的GL4ES，而且没有调用手机GPU是处理器硬算的和OpenGL ES也没有什么关系，不要在这里不懂装懂了，谢谢，你们文件泄漏已经给我们带来了不小的麻烦。

**Comment by yejunjie10311031** [comment]
@ShulkerSakura 吾辈懂矣，现在请让artdev关掉这个issue.

**Comment by joselito2457** [comment]
> Wow! Link?

Wow link

**Comment by Mizaan859** [comment]
I need shader Link for pojav launcher
