### ISSUE TITLE
[F-REQ] Automatic/Manual JVM Arguments Options

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#877]
**Is your feature request related to a problem? Please describe.**

It's not related to a problem, but focused on optimization and performance. 
The current allocation system is very simple and ineffective

**Describe the solution you'd like**

A way to choose within the launcher which is the best JVM argument, or an automatic system for that. The goal is to use as much RAM as possible according to the limit of each device.

**Describe alternatives you've considered**

An automatic system that detects how much RAM the device have available, and use all this. 

**Additional context**

Some way to optimize CPU/RAM to load mods more faster, it's taking too long.

Note: Load mods in PC with 500MB allocated is very very more faster than load mods in Pojav with 800MB+ allocated. 
We need to find out why this happens, maybe is a JVM argument problem.

**Comment by khanhduytran0** [comment]
You can already toggle “Automatic RAM” for auto RAM, or change manually on “JVM arguments”. Both are on settings.

**Comment by ghost** [comment]
Amost JVM arguments are supported in Pojav too? 
I did some tests trying to allocate more RAM, and the game crashed. And the only way that work if you put ''Automatic RAM'' active, which limit is just 800MB

**Comment by khanhduytran0** [comment]
Note that RAM is **limited on 32bit**, so don't expect too much unless get a 64bit device.
Also, you should not set RAM more that free RAM, it will causes
- System freeze (Android can’t take more memory and crashes or freeze).
- Game random crashes.

**Comment by khanhduytran0** [comment]
Bruh duplicate #867 **your own issue!!!!!!**

**Comment by khanhduytran0** [comment]
It is also related to java options.

**Comment by ghost** [comment]
Thanks for the clarified :D
