### ISSUE TITLE
Error when connecting to a cracked server with cracked account

### ISSUE THREAD

**Issue by mirkokral** [PojavLauncherTeam/PojavLauncher#879]
When joining any server i will get an error saying
`java.net.SocketException: Network is unreachable `

Servers tested:
```
mc.mineland.net
herobrine.org
localhost
```

**Comment by Mathias-Boulay** [comment]
Support for cracked accounts is... Let's say absent.
No logs are provided, and this is a stale issue.
Furthermore, server compatibility has increased on the google play release.
