### ISSUE TITLE
[F-REQ] Adapted Keyboard (Windows-based)

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#880]
**Is your feature request related to a problem? Please describe.**

Kind yes, because some mods needs some specific buttons that don't have on Gboard and in other kb apps.

**Describe the solution you'd like**

A keyboard adapted for the launcher, with the maximum number of buttons of the standard keyboard.

**Describe alternatives you've considered**

Any virtual keyboard with more buttons, just like in Windows is enough.
(F1 until F12, Space, Enter, Esc, Alt, Crtl, Shift, Tab and etc)

**Additional context**

Nothing for now

**Comment by Mathias-Boulay** [comment]
You can already add virtual keys. Options>virtual controls.

**Comment by ghost** [comment]
Yes, the problem is create too many buttons on the screen. You can click by accident, not to mention that can impairs also your vision

**Comment by khanhduytran0** [comment]
Just use [Hacker's keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard)

**Comment by khanhduytran0** [comment]
Also, **Android is not Windows**, so if you even request adding Win key, it’s become invalid.

**Comment by khanhduytran0** [comment]
> Yes, the problem is create too many buttons on the screen. You can click by accident, not to mention that can impairs also your vision

So virtual keyboard does not do same thing?

**Comment by ghost** [comment]
> > Yes, the problem is create too many buttons on the screen. You can click by accident, not to mention that can impairs also your vision
> 
> So virtual keyboard does not do same thing?

Yes, but you can use and then ''disable''

**Comment by Mathias-Boulay** [comment]
Stale issue, and the answer already was to use another keyboard, or to add more buttons.
*Although the keyboard drawer will fix this definitively*
