### ISSUE TITLE
The screen is lighter

### ISSUE THREAD

**Issue by mrredstone1235** [PojavLauncherTeam/PojavLauncher#881]
the game is so bright it hurts my eyes when looking at the game, please tell me how to fix this

the game supposed to look like in the bottom left part of the screen
![Screenshot_2021-02-14-16-17-31-577_net kdt pojavlaunch](https://user-images.githubusercontent.com/72189912/107871891-bd254c80-6ee0-11eb-9dc4-03ddfc2631f1.jpg)

**Comment by 321goahhhhhhhhhh** [comment]
I have this bug too in my infinx hot 8

**Comment by khanhduytran0** [comment]
Which build are you on?

**Comment by 321goahhhhhhhhhh** [comment]
What does that mean

**Comment by Mynameispoop** [comment]
That happened to mine as well but i got rid of it somehow but idk how i got rid of it its really hard to get rid of it u need to wait until it remove by itself

**Comment by mrredstone1235** [comment]
> Which build are you on?

3.3.1.1 latest

**Comment by khanhduytran0** [comment]
@mrredstone1235 update to latest action build
