### ISSUE TITLE
[BUG] I'm not getting any log output

### ISSUE THREAD

**Issue by 321goahhhhhhhhhh** [PojavLauncherTeam/PojavLauncher#882]
**Describe the bug**
This is not a problem but when I start minecraft. There is no log output

**To Reproduce**
1. Start PojavLauncher
2. Swipe your screen to the left
3. Go to log output

**Expected behavior**
I expected ...
That there will be log output
**Screenshots**

**Platform:**
 - Device Model realme C3
 - CPU architecture aarch64
 - Android Version android 10
<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Here is what I got in the file latestlog.txt 

--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms768m -Xmx768m"
Headless version detected! (20200515)
--------- beginning of main
read: unexpected EOF!

Also auto ram is on
</pre>
</details>

**Comment by ghost** [comment]
Same

**Comment by LanceAldrei04** [comment]
Same

**Comment by HedHogie** [comment]
Saamee it's so annoying

**Comment by khanhduytran0** [comment]
Fixed. Use latest build
