### ISSUE TITLE
[F-REQ] Pls add more fps in the game, i cant play properly on the latest version 

### ISSUE THREAD

**Issue by Mynameispoop** [PojavLauncherTeam/PojavLauncher#883]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
Buy a better device to "add more FPS".

**Comment by khanhduytran0** [comment]
Technically, we can't do that, we don't own OpenJDK.

**Comment by QuasyStellar** [comment]
Damn...  Try to install videocard)

**Comment by khanhduytran0** [comment]
> Technically, we can't do that, we don't own OpenJDK.

nor your device GPU source code.

**Comment by yejunjie10311031** [comment]
Are you joking?You only need to buy a better device to get more fps.
If you are not able buy a better device,you can install some mods such as optifine to make your fps higher.
But in fact,Openjdk also cant use all of your performance.

**Comment by QuasyStellar** [comment]
> Are you joking?You only need to buy a better device to get more fps.
> If you are not able buy a better device,you can install some mods such as optifine to make your fps higher.
> But in fact,Openjdk also cant use all of your performance.

How can i chat with you?
