### ISSUE TITLE
[BUG] Forge crashes when loading into world

### ISSUE THREAD

**Issue by MangyCat** [PojavLauncherTeam/PojavLauncher#885]
**Describe the bug**
Forge crashes when I load into a world.

**To Reproduce**
1. Start PojavLauncher
2. Launch forge 1.12.2
3. Load into a world
...

**Expected behavior**
I expected for the world to load like normal, except it crashed

**Platform:**
 - Device Model [Huawei P30 Lite]
 - CPU architecture [aarch64] 
 - Android Version [10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
I did reinstall forge because of the same issue, still no effect.
</pre>
</details>

Log file:
https://pastebin.com/DRQe1Jsa

**Comment by MangyCat** [comment]
It has been a long time.

**Comment by khanhduytran0** [comment]
The log show that you joined world, so we have nothing to do, seems invalid.

**Comment by khanhduytran0** [comment]
Broken mods
- BuildCraft
- futureminecraf

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by Dslwpi** [comment]
I had same problem
