### ISSUE TITLE
[BUG]  Hidden Chat + Possible Solution

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#887]
Problem:

The chat is hidden by the keyboard when you are going to type a message or command. 
Something that really bothers a little, and makes the player waste a lot of time writing and make mistakes.

Possible Solution: 

Some kind of box above the keyboard with the content that you are writing, and a button to transfer to the chat.
Or just a mirror above the keyboard to see what you are writing.

**Comment by ytuy404** [comment]
с первым согласен

**Comment by ghost** [comment]
согласен, идея хороша, реально можно допустить много ошибок не видя текста

**Comment by khanhduytran0** [comment]
Use Gboard floating keyboard while writing chat.

**Comment by khanhduytran0** [comment]
> Some kind of box above the keyboard with the content that you are writing, and a button to transfer to the chat.

But we want to directly transfer every character to Minecraft instantly.

**Comment by Thensi72** [comment]
> > Some kind of box above the keyboard with the content that you are writing, and a button to transf

> Use Gboard floating keyboard while writing chat.

Yeah I use gboard all the time

**Comment by Mathias-Boulay** [comment]
@khanhduytran0 maybe we can add just a textview that could be accessed by the current solution to copy the captured character to the said textview ?

**Comment by Mathias-Boulay** [comment]
The visible textbox approach poses a huge practical issue for editing stuff.
With controls v2.2 the approach for the keyboard dramatically changed under the hood.

With the recently merged control v2.4, the auto-correct is there to help people write in chat easily/ see what they are writing. 😄

Since chat is now easy enough to type on, I'll close the issue.
