### ISSUE TITLE
Apliccation/Game exited with code 1

### ISSUE THREAD

**Issue by mirkokral** [PojavLauncherTeam/PojavLauncher#888]
When i run any modded or vanilla mc 1.16.x i just get "Application/Game exited with code 1"

<h1><b>AND I HATE THIS</b></h1>

**Comment by khanhduytran0** [comment]
![5F9138AC-8E21-49EA-9DF2-E71E43C6BA92](https://user-images.githubusercontent.com/40482367/107878029-911ac300-6f02-11eb-88d7-771052db9e12.jpeg)

**Comment by khanhduytran0** [comment]
@mirkokral

**Comment by khanhduytran0** [comment]
Aren't you going to reply?
> Fill the template.

![4464D8C1-485F-410B-AA98-F70D8CFCA5A2](https://user-images.githubusercontent.com/40482367/107878142-3cc41300-6f03-11eb-8dbb-015f3ee7cf75.jpeg)

**Comment by mirkokral** [comment]
Yes

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by mirkokral** [comment]
I get an crash report now
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 14.2.2021 13:45
Description: Initializing game

java.lang.NoClassDefFoundError: com/ibm/icu/text/ArabicShapingException
	at dms.a(SourceFile:160)
	at djw.<init>(SourceFile:493)
	at net.minecraft.client.main.Main.main(SourceFile:177)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.text.ArabicShapingException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 3 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dms.a(SourceFile:160)
	at djw.<init>(SourceFile:493)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 872140696 bytes (831 MB) / 1479540736 bytes (1411 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms1G -Xmx2G
	Launched Version: 1.16.3
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: 9x null
```

**Comment by khanhduytran0** [comment]
Delete .minecraft/libraries/com/ibm/icu folder and try again

**Comment by mirkokral** [comment]
--------- beggining with launcher debug
Info: LWJGL3 directory: [lwjgl.jar, version, lwjgl-glfw-classes.jar, lwjgl-stb.jar, jsr305.jar, lwjgl-jemalloc.jar, lwjgl-tinyfd.jar, lwjgl-opengl.jar, lwjgl-openal.jar]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms1G -Xmx2G"
Headless version detected! (20210214)
--------- beginning of system
--------- beginning of main
I/jrelog  ( 5610): Starting logging STDIO as jrelog:V
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" unused DT entry: DT_RPATH (type 0xf arg 0x361) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" unused DT entry: DT_RPATH (type 0xf arg 0x450) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  ( 5610): WARNING: linker: 
I/jrelog  ( 5610): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" unused DT entry: DT_RPATH (type 0xf arg 0x33c0) (ignoring)
I/jrelog  ( 5610): WARNING: linker: 
I/jrelog  ( 5610): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
I/jrelog  ( 5610): WARNING: linker: 
I/jrelog  ( 5610): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" unused DT entry: DT_RPATH (type 0xf arg 0x13b8) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 5610):  (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" unused DT entry: DT_RPATH (type 0xf arg 0x2196) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" unused DT entry: DT_RPATH (type 0xf arg 0x6a46) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
I/jrelog  ( 5610): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: DT_RPATH (type 0xf arg 0x4d9) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" unused DT entry: DT_RPATH (type 0xf arg 0xda0) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
I/jrelog  ( 5610): WARNING: linker: 
I/jrelog  ( 5610): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" unused DT entry: DT_RPATH (type 0xf arg 0x158) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" unused DT entry: DT_RPATH (type 0xf arg 0x1d2) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so
I/jrelog  ( 5610): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" unused DT entry: 
I/jrelog  ( 5610): DT_RPATH (type 0xf arg 0x119) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so
I/jrelog  ( 5610): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
I/jrelog  ( 5610): " unused DT entry: DT_RPATH (type 0xf arg 0x16fe) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so
I/jrelog  ( 5610): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsunec.so success
I/jrelog  ( 5610): WARNING: linker: 
I/jrelog  ( 5610): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" unused DT entry: DT_RPATH (type 0xf arg 0xe6) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" unused DT entry: DT_RPATH (type 0xf arg 0x23a) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" unused DT entry: DT_RPATH (type 0xf arg 0x6af) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" unused DT entry: DT_RPATH (type 0xf arg 0x77
I/jrelog  ( 5610): ) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 5610):  (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" unused DT entry: DT_RPATH (type 0xf
I/jrelog  ( 5610):  arg 0x103) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 5610):  (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" unused DT entry: DT_RPATH (type 
I/jrelog  ( 5610): 0xf arg 0x6c1) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 5610):  (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so success
I/jrelog  ( 5610): WARNING: linker: 
I/jrelog  ( 5610): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" unused DT entry: DT_RPATH (type 0xf arg 0x5e6) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" unused DT entry: DT_RPATH (type 
I/jrelog  ( 5610): 0xf arg 0x139) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" unused DT entry: DT_RPATH
I/jrelog  ( 5610):  (type 0xf arg 0x2e6) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so" unused DT entry: DT_RPATH (type 
I/jrelog  ( 5610): 0xf arg 0xd5) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 5610):  (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnpt.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" unused DT entry: DT_RPATH (type 0xf arg 0x3f1) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" unused DT entry: DT_RPATH (type 0xf arg 0x1c7
I/jrelog  ( 5610): ) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
I/jrelog  ( 5610): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so
I/jrelog  ( 5610): " unused DT entry: DT_RPATH (type 0xf arg 0xf13) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=
I/jrelog  ( 5610): 0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" unused DT entry: DT_RPATH
I/jrelog  ( 5610):  (type 0xf arg 0x1c1) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 5610):  (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_xawt.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "
I/jrelog  ( 5610): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" unused DT entry: DT_RPATH (type 0xf arg 0x364) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" has unsupported flags DT_FLAGS_1=0x81
I/jrelog  ( 5610):  (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsig.so success
I/jrelog  ( 5610): WARNING: linker: 
I/jrelog  ( 5610): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" unused DT entry: DT_RPATH (type 0xf arg 0x8ff) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
I/jrelog  ( 5610): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so
I/jrelog  ( 5610): " unused DT entry: DT_RPATH (type 0xf arg 0x3ed) (ignoring)
I/jrelog  ( 5610): WARNING: linker: Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so
I/jrelog  ( 5610): " has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
I/jrelog  ( 5610): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libinstrument.so success
I/jrelog  ( 5610): dlopen /data/app/net.kdt.pojavlaunch-G3DYF6QpjpzQFfE4Vca9XQ==/lib/arm64/libopenal.so success
I/jrelog  ( 5610): dlopen /data/app/net.kdt.pojavlaunch-G3DYF6QpjpzQFfE4Vca9XQ==/lib/arm64/libgl04es.so success
I/jrelog  ( 5610): Done processing args
I/jrelog  ( 5610): Found JLI lib
I/jrelog  ( 5610): Calling JLI_Launch
I/jrelog  ( 5610): OpenJDK 64-Bit Server VM warning: 
I/jrelog  ( 5610): No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/jrelog  ( 5610): [13:49:23] [main/INFO]: Loading for game Minecraft 1.16.3
I/jrelog  ( 5610): [13:49:24] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
I/jrelog  ( 5610): [13:49:24] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
I/jrelog  ( 5610): Exception in thread "main" 
I/jrelog  ( 5610): java.util.concurrent.CompletionException: java.util.zip.ZipError: zip END header not found
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at java.lang.Thread.run(Thread.java:748)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): Caused by: java.util.zip.ZipError: zip END header not found
I/jrelog  ( 5610): 	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1651)
I/jrelog  ( 5610): 	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1040)
I/jrelog  ( 5610): 	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1049)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
I/jrelog  ( 5610): 	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
I/jrelog  ( 5610): 	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at net.fabricmc.tinyremapper.FileSystemHandler.open(FileSystemHandler.java:47)
I/jrelog  ( 5610): 	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:392)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:65)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:364)
I/jrelog  ( 5610): 
I/jrelog  ( 5610): 	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:360)
I/jrelog  ( 5610): 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
I/jrelog  ( 5610): 	... 3 more
Java Exit code: 1
I/jrelog  ( 5610): Going to free args
I/jrelog  ( 5610): Free done

**Comment by mirkokral** [comment]
Ok

**Comment by mirkokral** [comment]
Thanks it worked!
