### ISSUE TITLE
This bug has not yet fixed!

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#89]
When I walk forward, I can't look around.
Can you fix it? Pls (sorry for bad english)

**Comment by khanhduytran0** [comment]
You need hold camera before moving.

**Comment by FranzelDamasco909** [comment]
what if there was a zombies behind me while i was running how can i look and attack it(While running/walking)?

**Comment by FranzelDamasco909** [comment]
and the preview 11b2 has no apk only the files

**Comment by FranzelDamasco909** [comment]
it's hard :(

**Comment by khanhduytran0** [comment]
> what if there was a zombies behind me while i was running how can i look and attack it?

Idk, current I'm unable to fix this.

> and the preview 11b2 has no apk only the files

Because I found a problem after publish first APK, then I removed first APK and build + publish a new one.

**Comment by FranzelDamasco909** [comment]
ok i found it now thank you!

**Comment by FranzelDamasco909** [comment]
is Custom Controls in settings doesn't work?

**Comment by khanhduytran0** [comment]
> is Custom Controls in settings doesn't work?

I disabled it because it is not yet finished.

**Comment by FranzelDamasco909** [comment]
Does it means Custom Controls you can make your own controls by adding buttons by your own?

**Comment by khanhduytran0** [comment]
> Does it means Custom Controls you can make your own controls by adding buttons by your own?

Yes

**Comment by FranzelDamasco909** [comment]
Ah finally, i can make my own controls without giving request to you! thanks you so much! your so cool!

**Comment by FranzelDamasco909** [comment]
like i was playing gameboy on my phone and making my own control buttons

**Comment by FranzelDamasco909** [comment]
I have a question, if i erase the whole Minecraft pe file, where does the launcher files go?

**Comment by khanhduytran0** [comment]
Yes IF you remove `games` folder in sdcard.

**Comment by FranzelDamasco909** [comment]
Yes if i remove the "games" file on my sdcard, where does the Launcher File go?

**Comment by khanhduytran0** [comment]
> Yes if i remove the "games" file on my sdcard, where does the Launcher File go?

Launcher Files going to the void.

But if you remove `games/com.mojang`, no launcher data will be lost.

**Comment by khanhduytran0** [comment]
> When I walk forward, I can't look around.
> Can you fix it? Pls (sorry for bad english) 

Fixed!
