### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#890]
After the release of Pojavlauncher for IOS I saw that the keyboard model is different from Pojavlauncher for Android! and it also comes with a few more buttons: esc, offhand and opti-zoom ... I liked these features a lot more and can they come to Pojavlauncher for Android in the next update? Maybe?

**Comment by OwzygZawg** [comment]
@khanhduytran0 pls look

**Comment by khanhduytran0** [comment]
Are you too lazy to add them on custom controls?...

**Comment by OwzygZawg** [comment]
> Are you too lazy to add them on custom controls?...

Nothing like that! I tried to add more it didn't work the buttons didn't work ... so I think it should come with Pojavlauncher Android, as well as Pojavlauncher for IOS

**Comment by OwzygZawg** [comment]
> Are you too lazy to add them on custom controls?...

And also the style of the IOS control for Pojavlauncher caught my attention, but I don't have an IOS device :(

**Comment by khanhduytran0** [comment]
> And also the style of the IOS control for Pojavlauncher caught my attention, but I don't have an IOS device :(

I already intended to switch to flat button on Android, but some peoples don’t like it or something...

**Comment by khanhduytran0** [comment]
Maybe need add a switch to toggle between Boardwalk style and flat type...

**Comment by OwzygZawg** [comment]
> Maybe need add a switch to toggle between Boardwalk style and flat type...

Yes pls

**Comment by khanhduytran0** [comment]
> Nothing like that! I tried to add more it didn't work the buttons didn't work ... so I think it should come with Pojavlauncher Android, as well as Pojavlauncher for IOS

It just because you didn't apply control after save.

**Comment by khanhduytran0** [comment]
Remember to not save to “default” name

**Comment by OwzygZawg** [comment]
> > Nothing like that! I tried to add more it didn't work the buttons didn't work ... so I think it should come with Pojavlauncher Android, as well as Pojavlauncher for IOS
> 
> It just because you didn't apply control after save.

yes now i'm aware of that! but the style of the IOS Pojavlauncher buttons caught my attention .. I hope that in the next update we can change the style of the buttons would be cool

**Comment by khanhduytran0** [comment]
Done https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/570722465
You can toggle it on settings under name “Flat button style”

**Comment by OwzygZawg** [comment]
Send a screenshot where I can activate it, I don't know how to change it

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/921#issuecomment-782614229
