### ISSUE TITLE
。。

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#892]
Sonic Ether's Unbelievable Shaders (here and hereafter referred to as 'SEUS') are the intellectual property of Cody Darr (here and hereafter referred to as 'Sonic Ether') and the copyright belongs to him.Distributed is the source code of SEUS. You are granted the right to use and modify SEUS and its source for your own personal use.It is, however, interdicted to (re-)distribute SEUS as it is provided or in any modified version in parts or in its entirety in any way without explicit written permission by Sonic Ether. You may ipso facto not create mirrors, use parts of SEUS - including snippets from its source code - in your own work, claim to be the author of SEUS or publish derived shader packs under your own or Sonic Ether's name.You may freely publish Minecraft footage with SEUS installed given that you do not infringe applicable law. If you feature SEUS as the main content, you must provide reference to a description of SEUS as found in the official thread on the Minecraft forums .S

**Comment by netkv** [comment]
i dont get it
