### ISSUE TITLE
[BUG] only black screen appears when trying to play 1.16.5 on android 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#893]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

**Describe the bug**
When trying to play version 1.16.5, only black screen appeard other then gui buttons which were not working and a game exited message. 

**To Reproduce**
1. Start PojavLauncher
2. Select version 1.16.5
3. Download all the files 
4. Hit play button

**Expected behavior**
I expected that game will start normally 

**Screenshots**
![Screenshot_20210215_104132](https://user-images.githubusercontent.com/79072789/107908018-1a6ddc00-6f7b-11eb-8258-8a1bbda29c93.jpg)
![Screenshot_20210215_104217](https://user-images.githubusercontent.com/79072789/107908032-20fc5380-6f7b-11eb-91ab-1585d6123e49.jpg)

**Platform:**
 - Device Model - vivo y81
 - CPU architecture - 8x ARM cortex-a53 @2.00 GHz
 - Android Version - 8.1

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by ghost** [comment]
Where to find it?

**Comment by ghost** [comment]
Nevermind, I reinstalled the app and it worked.
