### ISSUE TITLE
[BUG]WHEN I DOWNLOAD THE MINECRAFT  1.16.5 AFTER GETTING  FULLY DOWNLOADED  WHEN IT STARTS RUNNING AUTOMATICALLY  CLOSES AFTER A SECOND OR TWO  .

### ISSUE THREAD

**Issue by Opdjs** [PojavLauncherTeam/PojavLauncher#894]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
@Opdjs why don't you leave the title as __**BUG**__ instead of changing text???

**Comment by khanhduytran0** [comment]
> Make sure you have filled this issue template, or this will get rejected.
