### ISSUE TITLE
Will my phone run the Open4Es shader?

### ISSUE THREAD

**Issue by PeterScorPioN** [PojavLauncherTeam/PojavLauncher#895]
I have the Xiaomi Pocophone F1, the specs of which are below. I'm interested of how it will run the Open4Es shaders. Will it be stable, or i need a better hardware for this? For now, i don't have this shader, because it's obviously still in closed development, so i wonder if it will be comfortable to play with them in general... If someone has an idea of it, please let me know.

My phone's specs:

OS: Android 10
RAM: 6GB
CPU: Snapdragon 845
GPU: Andreno 630
And i also dedicate 2GB of RAM for Pojav Launcher.

**Comment by artdeell** [comment]
I have Mi 8 which has the same CPU and GPU, and it's playable

**Comment by PeterScorPioN** [comment]
> I have Mi 8 which has the same CPU and GPU, and it's playable

Wait, do you have the shader? How?

**Comment by artdeell** [comment]
I do

**Comment by PeterScorPioN** [comment]
> I do

Is it available somewhere? If it is, i would like to get it, without publishing it anywhere.

**Comment by artdeell** [comment]
It's only available in testers' discord chat

**Comment by PeterScorPioN** [comment]
Also sorry that i made a feature request. I wanted to make a question label, but accidentally did a request...

**Comment by PeterScorPioN** [comment]
> It's only available in testers' discord chat

Can you give me the link to their discord, if it's available and possible?

**Comment by Zeyrox1090** [comment]
> It's only available in testers' discord chat

leak it lmao create alt and leak it

jk

**Comment by AjGamingPHOfficial** [comment]
Good Boy

May jesus take your soul.

**Comment by PeterScorPioN** [comment]
> Good Boy
> 
> May jesus take your soul.

You talk about me? Or....

**Comment by ELECTRO7YT** [comment]
How to download

**Comment by ELECTRO7YT** [comment]
CAN ANYONE GIVE THE SHADER LINK . I WILL NOT GIVE TO ANYONE PLEASE

**Comment by khanhduytran0** [comment]
@ELECTRO7YT join our Zink test branch and maybe get shader works without open4es

**Comment by ELECTRO7YT** [comment]
How to join

**Comment by ENDERMANYK** [comment]
> How to join

Download version have "osmesa-dev-tests" in actions

**Comment by ELECTRO7YT** [comment]
I can't understand tell it properly

**Comment by ENDERMANYK** [comment]
> I can't understand tell it properly

![IMG_20210329_140946](https://user-images.githubusercontent.com/64646658/112793779-7c505400-9098-11eb-906a-2a7790ab3f9f.jpg)
Download this version to join zink test and some PC shader maybe will works on your phone

**Comment by ELECTRO7YT** [comment]
Sorry for disturb you 😞 
Can you give a mediafire link please 😭

**Comment by ENDERMANYK** [comment]
> Sorry for disturb you 😞
> Can you give a mediafire link please 😭

Bro you only need to click actions tab in GitHub and click the first line and you will download the apk

**Comment by PeterScorPioN** [comment]
> > I can't understand tell it properly
> 
> ![IMG_20210329_140946](https://user-images.githubusercontent.com/64646658/112793779-7c505400-9098-11eb-906a-2a7790ab3f9f.jpg)
> Download this version to join zink test and some PC shader maybe will works on your phone

So this build has a "beta zink" inside?

**Comment by ELECTRO7YT** [comment]
![Uploading Screenshot_2021-03-29-12-13-41-55.jpg…]()

**Comment by ENDERMANYK** [comment]
> > > I can't understand tell it properly
> > 
> > 
> > ![IMG_20210329_140946](https://user-images.githubusercontent.com/64646658/112793779-7c505400-9098-11eb-906a-2a7790ab3f9f.jpg)
> > Download this version to join zink test and some PC shader maybe will works on your phone
> 
> So this build has a "beta zink" inside?

All the build have "osmesa-dev-tests" below have the zink

**Comment by ELECTRO7YT** [comment]
Yes I downloaded it now what to do

**Comment by PeterScorPioN** [comment]
I downloaded it too, but i cannot enter any version. I have a very powerful device with SD 845 and Andreno 630. My OpenGl support is 3.2 i think... Maybe it's something, that I didn't count. Can someone help me?

**Comment by PeterScorPioN** [comment]
> I downloaded it too, but i cannot enter any version. I have a good device with SD 845 and Andreno 630. My OpenGl support is 3.2 i think... Maybe it's something, that I didn't count. Can someone help me?

**Comment by khanhduytran0** [comment]
@PeterScorPioN bruh minecraft java does not use **OpenGL ES**

**Comment by ENDERMANYK** [comment]
> I downloaded it too, but i cannot enter any version. I have a very powerful device with SD 845 and Andreno 630. My OpenGl support is 3.2 i think... Maybe it's something, that I didn't count. Can someone help me?

Put this in JVM to get zink works" -Dorg.lwjgl.opengl.libname=libOSMesa_8.so"  what's more your phone doesn't support OpenGL it only support OpenGL ES

**Comment by PeterScorPioN** [comment]
> @PeterScorPioN bruh minecraft java does not use **OpenGL ES**

Bruh, sorry. I am kinda stupid...🤦

**Comment by PeterScorPioN** [comment]
> > I downloaded it too, but i cannot enter any version. I have a very powerful device with SD 845 and Andreno 630. My OpenGl support is 3.2 i think... Maybe it's something, that I didn't count. Can someone help me?
> 
> Put this in JVM to get zink works" -Dorg.lwjgl.opengl.libname=libOSMesa_8.so" what's more your phone doesn't support OpenGL it only support OpenGL ES

Yes, i know this now. I actually want to start understanding how this works, cause i wanna be java programmer...
