### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GeneralPashan** [PojavLauncherTeam/PojavLauncher#896]
When I play with 1.16.4 fabric mod 'sodium' and when I enter the world the game a crashes

**Comment by QuasyStellar** [comment]
Off fog oclusion and vertex format.

**Comment by PeterScorPioN** [comment]
> When I play with 1.16.4 fabric mod 'sodium' and when I enter the world the game a crashes

You should flick some setting, until it works. I had the same problem.

**Comment by MangyCat** [comment]
I have the same problem in 1.12.2, I will try the commenter's solutions.

**Comment by khanhduytran0** [comment]
@MangyCat 1.12.2 does not have sodium fabric

**Comment by MangyCat** [comment]
> @MangyCat 1.12.2 does not have sodium fabric

I crash when joining a server or a world but it's optifine, anyway of fixing that?

**Comment by PeterScorPioN** [comment]
> > @MangyCat 1.12.2 does not have sodium fabric
> 
> I crash when joining a server or a world but it's optifine, anyway of fixing that?

Your phone model?
