### ISSUE TITLE
[BUG]Can't change custom controls

### ISSUE THREAD

**Issue by Dimon245** [PojavLauncherTeam/PojavLauncher#898]
**Describe the bug**
Can't change custom controls due to not being able to swipe because navigation bar won't disappear

**To Reproduce**
1. Start PojavLauncher
2. Go to Custom Controls
3. Not be able to change 'em
4. ???
5. Profit
**Expected behavior**
I expected the navigation bar to disappear after a short while allowing me to swipe right, thus changing custom controls settings

**Screenshots**
https://imgur.com/a/iWXcOi5
**Platform:**
 - Device Model: Samsung S20+
 - CPU architecture: aarch64
 - Android Version: 11

**Comment by Zeyrox1090** [comment]
rotate your phone?

**Comment by Dimon245** [comment]
not possible, I've tried

**Comment by artdeell** [comment]
Click on a button and disable dynamic position

**Comment by artdeell** [comment]
Reopen if it won't work

**Comment by Dimon245** [comment]
> Click on a button and disable dynamic position

Dude, ya still need to fix it, it doesn't work everytime

**Comment by artdeell** [comment]
It works always, but if you don't oress OK, welp, it won't save

**Comment by Dimon245** [comment]
For me it works ~30% of the time, but thanks anyway
