### ISSUE TITLE
[BUG] I cant type . (Dot)

### ISSUE THREAD

**Issue by ILUVCAPS** [PojavLauncherTeam/PojavLauncher#899]
Heres the video

https://user-images.githubusercontent.com/79126475/108016002-7a808300-704c-11eb-867e-855dd6eb2f5b.mp4

**Comment by Zeyrox1090** [comment]
i cant type #@

**Comment by artdeell** [comment]
smh it's not even 3.3.1.1

**Comment by Mathias-Boulay** [comment]
Stale issue on an old version.
Closing.
