### ISSUE TITLE
Reporting the re-uploaders

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#9]
Because your launcher is growing, many people started to violate the re-upload rule for the reviews.
I found one of them. Here's the link: https://www.youtube.com/watch?v=-zAh5ttCfDU
Can you tell me a way to report that guys?

**Comment by khanhduytran0** [comment]
Press three dots button at the top right while in the video then press Report

**Comment by artdeell** [comment]
Also, how did you find my video? DISPOLYMER is my second channel with less views.

**Comment by khanhduytran0** [comment]
Just press to the icon of channel

**Comment by khanhduytran0** [comment]
How to kill app in Aptoide?
https://pojavlauncher-java-edition.es.aptoide.com/app

That guy re-uploaded to Aptoide and Mediafire.
https://youtu.be/dx4Iy-BLx-c
(He is respect a bit, leave credits in description)

**Comment by khanhduytran0** [comment]
Oh yeah, the aptoide link is dead.
