### ISSUE TITLE
Take item in inventory

### ISSUE THREAD

**Issue by GrandMagus99** [PojavLauncherTeam/PojavLauncher#90]
How I can take item in chest? How to wear the equipment?

**Comment by khanhduytran0** [comment]
disable touchscreen mode

**Comment by khanhduytran0** [comment]
Minecraft settings -> controls > Touchscreen mode Toggle to OFF

**Comment by FranzelDamasco909** [comment]
How to divide an item? i was supposed to to craft an item on crafting table, and i can't divide the item i hold

**Comment by khanhduytran0** [comment]
Currebt there's no way to divide item.

**Comment by FranzelDamasco909** [comment]
okay what about when playing in survival mode? how can i craft an axe?

**Comment by khanhduytran0** [comment]
I will fix now.

**Comment by GrandMagus99** [comment]
Tq, i think you should add left click button to divide items,

**Comment by khanhduytran0** [comment]
Left click already in the `PRI` button, meanwhile divide item by right click, default Boardwalk disable right click if not grabbing, so I enable and will release.

**Comment by khanhduytran0** [comment]
Right click by `SEC` button.

**Comment by FranzelDamasco909** [comment]
Thank you so much!

**Comment by khanhduytran0** [comment]
Did you get preview11b3?

**Comment by GrandMagus99** [comment]
Yes, i got it, ty yaaaa... thank for fix that movement and camera

**Comment by FranzelDamasco909** [comment]
i need 1.12

**Comment by khanhduytran0** [comment]
> i need 1.12

I'm unable to make 1.12 working at the moment, however you can check this, wait a bit.

**Comment by khanhduytran0** [comment]
[app-debug.zip](https://github.com/khanhduytran0/PojavLauncher/files/4464273/app-debug.zip)

If you installed 1.12 before, delete ALL versions and libraries and install again.

**Comment by khanhduytran0** [comment]
This is the old one I compiled in Android Studio.

**Comment by FranzelDamasco909** [comment]
what can i do about app-debug.zip?

**Comment by khanhduytran0** [comment]
Extract and get APK inside. This APK may make 1.12 work. But you must do actions as above.

**Comment by FranzelDamasco909** [comment]
Ok thank you!

**Comment by khanhduytran0** [comment]
Is it work for you?

**Comment by FranzelDamasco909** [comment]
wait i was just starting ;-;

**Comment by FranzelDamasco909** [comment]
Still doesn't work ;-;

![Screenshot_2020-04-15-18-54-23-97](https://user-images.githubusercontent.com/62983424/79329623-a81a0e80-7f07-11ea-8332-fc1cd355f90e.png)

**Comment by FranzelDamasco909** [comment]
i followed you but it still doesn't work

**Comment by khanhduytran0** [comment]
Copy error here.

**Comment by FranzelDamasco909** [comment]
what an i going to do with that?

**Comment by khanhduytran0** [comment]
Copy full error here for I check if it is old error.

**Comment by FranzelDamasco909** [comment]
where

**Comment by FranzelDamasco909** [comment]
ok

**Comment by khanhduytran0** [comment]
Show More and Copy

**Comment by FranzelDamasco909** [comment]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:939)
	at net.kdt.pojavlaunch.MainActivity.access$2700(MainActivity.java:40)
	at net.kdt.pojavlaunch.MainActivity$11$1.run(MainActivity.java:628)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
	at bhz.<init>(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: VII.
	... 7 more

**Comment by FranzelDamasco909** [comment]
oh wait i forgot to press show more

**Comment by khanhduytran0** [comment]
So, unfortunately, can't run 1.12 at the moment.

**Comment by FranzelDamasco909** [comment]
ok

**Comment by khanhduytran0** [comment]
> How I can take item in chest? How to wear the equipment? 

If still not fixed reopen.
