### ISSUE TITLE
A small bug with the mouse in 1.12.2

### ISSUE THREAD

**Issue by PeterScorPioN** [PojavLauncherTeam/PojavLauncher#900]
When i play the 1.12.2, a strange thing happens when i have the mouse turned on. If i close the inventory with the mouse on, i tap on the screen to look around and the camera looks to another direction abruptly. This is very uncomfortable and i died a lot of times, because of this. For now i noticed this bug only in 1.12.2, thankfully not in the 1.16+

**Comment by artdeell** [comment]
Known

**Comment by HedHogie** [comment]
This happened to me.

**Comment by Mathias-Boulay** [comment]
Known, and duplicate from other issues with better information provided.
Closing to avoid duplicates.
