### ISSUE TITLE
Skin Settings

### ISSUE THREAD

**Issue by FadingxNesto** [PojavLauncherTeam/PojavLauncher#901]
Add An Skin Settings Where Its Like from Official Minecraft Launcher!

**Comment by mglovers123** [comment]
How change skin in pojav latest

**Comment by LanceAldrei04** [comment]
> How change skin in pojav latest

www.minecraft.net/profile

Buy the game!

**Comment by SabergamingT7** [comment]
Please help me how to change my skin in pojav that is visible to everyone

**Comment by khanhduytran0** [comment]
> Please help me how to change my skin in pojav that is visible to everyone

1. Buy the game
2. Go to https://minecraft.net/en-us/profile/skin

**Comment by ABSTICKER** [comment]
Lol

**Comment by ABSTICKER** [comment]
It's a Mobile launcher not real Minecraft

**Comment by GoneSubject1** [comment]
> It's a Mobile launcher not real Minecraft 

yea 🤣

**Comment by khanhduytran0** [comment]
@ABSTICKER @GoneSubject1 the source code says all <img src="https://cdn.discordapp.com/emojis/886881737349660712.gif?size=20">
- Java from OpenJDK: [jdk8](https://github.com/PojavLauncherTeam/openjdk-multiarch-jdk8u), [jdk8 armv7](https://github.com/PojavLauncherTeam/openjdk-aarch32-jdk8u), [jdk17](https://github.com/PojavLauncherTeam/mobile)
- [LWJGL port](https://github.com/PojavLauncherTeam/lwjgl3)
- OpenGL NOT ES: [gl4es](https://github.com/PojavLauncherTeam/gl4es), [vgpu](https://github.com/PojavLauncherTeam/VGPU), [Mesa3D: zink and virglrenderer](https://github.com/PojavLauncherTeam/mesa), [virglrenderer](https://github.com/PojavLauncherTeam/virglrenderer)
- [Game files are downloaded from Mojang server](https://github.com/PojavLauncherTeam/PojavLauncher/blob/4219779ce44ad566a1d132ea3f1f4119ad3fcdb1/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/prefs/LauncherPreferences.java#L26)

**Comment by khanhduytran0** [comment]
> It's a Mobile launcher not real Minecraft

Why would you need to install Java 17 if we make fake Minecraft 1.18? <img src="https://cdn.discordapp.com/emojis/904591917621321789.png?size=22">

**Comment by mchnjt** [comment]
> It's a Mobile launcher not real Minecraft

FUCK OFF KIDDO
THERE'S LOT OF LAUNCHER OUT THERE SUCH AS BOARDWALK(obsolete), BOAT/MCINABOX(obsolete), TLAUNCHER, MULTIMC, ETC
DOES THAT MEAN THEY HAVE THEIR LAUNCHER-SPECIFIC MINECRAFT CLONE?
SHUT THE FUCK UP
WE WILL NEVER ADD "SKIN CHANGER"
GO TO SCHOOL OR SOMETHING LIKE THAT

**Comment by GoneSubject** [comment]
bruh

**Comment by kaicryptx** [comment]
I like pojavlauncher ❤️

**Comment by GoneSubject** [comment]
> I like pojavlauncher ❤️

ok?

**Comment by VaporeonLover** [comment]
junesshr watch your mouth little boy
