### ISSUE TITLE
[BUG] Can't serialize unregistered packet

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#904]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

**Describe the bug**
Mysterious disconnection when try join a Forge server with mods in MC version 1.12.2

**To Reproduce**
1. Start PojavLauncher
2. Run Forge 1.12.2 (14.23.5.2854)
3. Load all mods
4. Add a server
5. Try connect

**Expected behavior**
That I would join the server and play normally

**Screenshots**
Nothing

**Platform:**
 - Device Model [Xaiomi Redmi]
 - CPU architecture [aarch64] 
 - Android Version [9 Custom Room]

<details> <summary><b>Additional context</b></summary>
<br>
<pre> 
Strange parts of the server log:
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Gig joined the game
[Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Gig lost connection: Disconnected
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Gig left the game
[Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Gig lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Gig left the game
[Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Gig lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Gig left the game
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Gig joined the game
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Gig: Set own game mode to Creative Mode]
[Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Gig lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
</pre>
</details>
My JRE 8 is 32bits and the server 64bits, maybe this is the problem.

Possible solution: https://forums.minecraftforge.net/topic/67450-error-on-join-cant-serialize-unregistered-packet/

**Comment by WesleyVanNeck** [comment]
not a issue from us we dont touch packets

**Comment by ghost** [comment]
Something outdated maybe? I'm here investigating what could be, and so far nothing. I can join the server if I try several times, but the performance is very much lower than offline. Using the same mods sure

**Comment by ghost** [comment]
One user in forge forum with the same problem said that managed to solve the problem by uninstalling Java 32bits and installing 64bits. Would be a server problem then, something related to the 64-Bit Server VM?

**Comment by ghost** [comment]
If this problem only exists with 32-bit JRE users, will be a major limiter. Most servers work in 64 bits, I don't even know how put in 32bits or if exists this possibility

**Comment by artdeell** [comment]
If your device is 2-bits or has a 32-bit OS on top of a 64-bit CPU, you can't really use any 64-bit stuff on it
