### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by myxiaomo** [PojavLauncherTeam/PojavLauncher#905]
I found two serious loopholes in the official website. Those loopholes seem to exist in version 1.7.10. Sometimes when playing, it will suddenly jam and then crash without any error. Another loophole is the Nei item manager. In addition, it and some playability modules (nihilistic world 2, etc.) will crash. If you delete the Nei item manager, there will be no problem There is also my transplanted life adventure. Its Nei item manager can work perfectly. I don't know why. I also hope to change the button map to a circle of color outside and transparent inside. Otherwise, the button is too ugly. I hope the official can greatly beautify the button map and fix the two loopholes I proposed.

**Comment by artdeell** [comment]
latestlog.txt?

**Comment by myxiaomo** [comment]
> 最新日志.txt？

？

**Comment by myxiaomo** [comment]
There are no crash logs

**Comment by artdeell** [comment]
send latestlog.txt from games/PojavLauncher/.minecraft/

**Comment by myxiaomo** [comment]
> 从游戏/PojavLauncher/.minecraft/发送latestlog.txt

How to send it?

**Comment by netkv** [comment]
upload to comment on github it, says how, too hard to read?
![Screenshot_20210217_105206](https://user-images.githubusercontent.com/61617356/108186892-32c23000-710e-11eb-8c68-b6af316ba15d.png)

**Comment by myxiaomo** [comment]
> 

> 上传到github上发表评论，说怎么做，太难读了？
> ![截图_20210217_105206](https://user-images.githubusercontent.com/61617356/108186892-32c23000-710e-11eb-8c68-b6af316ba15d.png)

？？

**Comment by netkv** [comment]
it says how, you just press on text that says:
```
Attach files by dragging & dropping, selecting or pasting them
```
it should open file picker and you will have to select wanted file there

**Comment by myxiaomo** [comment]
> 它说明了如何，您只需按以下文字：
> 
> ```
> Attach files by dragging & dropping, selecting or pasting them
> ```
> 
> 它应该打开文件选择器，您将不得不在其中选择想要的文件

。

**Comment by myxiaomo** [comment]
> > 它说明了如何，您只需按以下文字：
> > ```
> > Attach files by dragging & dropping, selecting or pasting them
> > ```
> > 
> > 
> > 它应该打开文件选择器，您将不得不在其中选择想要的文件
> 
> 。

It's been sent at three o'clock

**Comment by myxiaomo** [comment]
> 它说明了如何，您只需按以下文字：
> 
> ```
> Attach files by dragging & dropping, selecting or pasting them
> ```
> 
> 它应该打开文件选择器，您将不得不在其中选择想要的文件

I've already clicked upload

**Comment by netkv** [comment]
*visible confusion

**Comment by myxiaomo** [comment]
> *明显的混乱

？

**Comment by myxiaomo** [comment]
>
