### ISSUE TITLE
[BUG]"Create" mod not work properly in pojav launcher,can you help me?

### ISSUE THREAD

**Issue by PlayWithMaulana** [PojavLauncherTeam/PojavLauncher#906]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

**Describe the bug**

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...

**Screenshots**

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Fill the template.

**Comment by khanhduytran0** [comment]
Hey @PlayWithMaulana ?

**Comment by PlayWithMaulana** [comment]
https://www.curseforge.com/minecraft/mc-mods/create

**Comment by khanhduytran0** [comment]
At least please send latestlog.txt

**Comment by PlayWithMaulana** [comment]
It not crashing but my screen freezing every 2 second

**Comment by PlayWithMaulana** [comment]
I can record it

**Comment by PlayWithMaulana** [comment]
Wait,the mod just not compatible with optifine I am sorry
