### ISSUE TITLE
Can i import TLauncher modpacks on Pojav Launcher?

### ISSUE THREAD

**Issue by PeterScorPioN** [PojavLauncherTeam/PojavLauncher#907]
I have TLauncher in my laptop, and there's a modpack feature there, where you can put some mods in a different Minecraft version. The fact is that these TLauncher modpacks are not depended on anything. They work as a different version and it contains every needed folder inside the version folder. Whoever had TLauncher, will understand. I tried to run one modpack, but it led to crash, as was expected... So my question is, can i make that thing run on Pojav? I need it a lot, because moving mods from here to there, every time i switch versions isn't that great.

**Comment by ghost** [comment]
yes, you can install it

**Comment by PeterScorPioN** [comment]
> yes, you can install it

Uhm... I told you that i did, but it crashes every time i launch it. May it me a mod?

**Comment by Bur6gerbar9** [comment]
It crashes because of the system permissions it fot some reason doesnt have access to your storage folder even if yoi grant pojav access it still crashes idk tho
