### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by musinnur23** [PojavLauncherTeam/PojavLauncher#910]
Why when I launch Pojav Launcher I get game exited with code 1 this error appears when i run forge, fabric

**Screenshots**
![Screenshot_20210216-104709.png](https://user-images.githubusercontent.com/79198539/108195538-b80f0a00-7139-11eb-8859-4143556dbc29.png)
**Platform:**
 - Device Model PSP7551DUO 2/10
 - CPU architecture aarch64
 - Android Version 7.0

**Comment by ghost** [comment]
You has install??
1.Vanilla
2.Latest Build

**Comment by musinnur23** [comment]
> You has install??
> 1.Vanilla
> 2.Latest Build
> 
> 

Vanila

**Comment by khanhduytran0** [comment]
@musinnur23 ERROR: fill the template
