### ISSUE TITLE
"signal 11 code 0x1caa5724 addr 0x2"lead to a crash.

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#911]
I think I find the reason of the unexpectedly crash which I commented it before(I am on latest build).Whenever the game crashes,the last line in the latestlog.txt is"signal 11 code 0x1caa5724 addr 0x2".

**Comment by artdeell** [comment]
It's a segmentation fault, which is really bad. Do you use GL4ES_115?

**Comment by yejunjie10311031** [comment]
@artdeell The optifine shows that I use 2.1 Gl4ES wrapper1.1.4
![Screenshot_20210217_212549](https://user-images.githubusercontent.com/62139629/108210819-ebdf3500-7123-11eb-9282-08850262fc18.jpg)

**Comment by artdeell** [comment]
Does the crash happen when you enter a world?

**Comment by yejunjie10311031** [comment]
@artdeell Sometimes it crashes as soon as I entre a world,but the time of the crash isn't fixed.Sometimes it doesn't crash even though I play for a long time,but sometimes it crashes in a short time.

**Comment by yejunjie10311031** [comment]
I added "-Dorg.lwjgl.opengl.libname=libgl4es_115.so"to JVM flags just now and the GL4ES wrapper version turned to 1.1.5.But there is also the crash problem.

**Comment by yejunjie10311031** [comment]
What's more,it never crashes on Minecraft1.16 and a1.0.4~a1.2.6.

**Comment by Deactivator** [comment]
![Screenshot_20210216-070740_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/78952909/108215675-97ee4380-7157-11eb-85af-e80bdd13afb8.jpg)
Every day I need to download a mc version and then install optifine again. Plz help me I don't wanna keep downloading the same thing again and again.

**Comment by artdeell** [comment]
> I added "-Dorg.lwjgl.opengl.libname=libgl4es_115.so"to JVM flags just now and the GL4ES wrapper version turned to 1.1.5.But there is also the crash problem.

The problem is: it also happens to me, but not always, and it seems like Android tries to crash the app on its own by sending a fake signal

**Comment by yejunjie10311031** [comment]
@artdeell This time I get more information from the latestlog.txt when the game unexpectedly crashes:
I/jrelog  (24638): signal 11 code 0xe6096852 addr 0x2
I/jrelog  (24638): FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x76d7dfd098)
I/jrelog  (24638): #
I/jrelog  (24638): # A fatal error has been detected by the Java Runtime Environment:
I/jrelog  (24638): #
I/jrelog  (24638): #  SIGSEGV (0xb) at pc=0x0000007637d6b8f0, pid=24638, tid=0x000000761b1d94f0
I/jrelog  (24638): #
I/jrelog  (24638): # JRE version: OpenJDK Runtime Environment (8.0) (build 1.8.0-internal-runner_2021_01_24_23_30-b00)
I/jrelog  (24638): # Java VM: OpenJDK 64-Bit Server VM (25.71-b00 mixed mode linux-aarch64 compressed oops)
I/jrelog  (24638): # Problematic frame:
I/jrelog  (24638): # 
I/jrelog  (24638): C  [libpojavexec.so+0x58f0]
I/jrelog  (24638):   android_sigaction+0x6c
I/jrelog  (24638): #
I/jrelog  (24638): # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
I/jrelog  (24638): #

**Comment by OwzygZawg** [comment]
Before installing Optifine for 1.16.5, make sure you have installed 1.16.5 before!

**Comment by yejunjie10311031** [comment]
There was only "signal 11 code …… addr 0x2" at the last of the latestlog.txt before,but this time I was surprised to find there are some more sentences after "signal 11 code …… addr 0x2",so I think it may help you and I send it to you.

**Comment by khanhduytran0** [comment]
@yejunjie10311031 send hs_err_pid

**Comment by yejunjie10311031** [comment]
@khanhduytran0 There is the hs_err_pid:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000076542264e4, pid=31993, tid=0x000000764e0894f0
#
# JRE version: OpenJDK Runtime Environment (8.0) (build 1.8.0-internal-runner_2021_01_24_23_30-b00)
# Java VM: OpenJDK 64-Bit Server VM (25.71-b00 mixed mode linux-aarch64 compressed oops)
# Problematic frame:
# C  [libart.so+0x2e54e4]  art::AddNativeDebugInfoForJit(void const*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&)+0x170
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000003aa8

Registers:
R0=0x00000075f4a71b70
R1=0x0000000000000000
R2=0x0000000000000000
R3=0xffffffff9fd065d4
R4=0x0009e34ff1000000
R5=0x00000076129f7eb8
R6=0x00000076daf34000
R7=0x00000000018808a8
R8=0x0000000000000000
R9=0x0000000000000c82
R10=0x0000000000000c82
R11=0x0000000000000006
R12=0x0000007654611f48
R13=0x0000000060307f74
R14=0x000a6353770152c7
R15=0x00001864e9ea9aae
R16=0x00000076d546fbd8
R17=0x00000076d5403d48
R18=0x0000000000000000
R19=0x000000765456df08
R20=0x000000009bd6f3a0
R21=0x00000075f4a71b70
R22=0x000000765456a048
R23=0x0000000000000c83
R24=0xb25ec1756f8580f1
R25=0x0000000000000755
R26=0x0000000000000338
R27=0x0000000099d054f4
R28=0x0000000099d054f0
R29=0x000000764e088d00
R30=0x000000765422644c

Top of Stack: (sp=0x000000764e088cc0)
0x000000764e088cc0:   000000765461bcc0 0000000000000000
0x000000764e088cd0:   00000076546af940 000000764e089588
0x000000764e088ce0:   000000764e088e90 0000007627bfc558
0x000000764e088cf0:   00000076546ed500 000000764dc0f000
0x000000764e088d00:   000000764e088dd0 000000764e61eae4
0x000000764e088d10:   0000000000000000 00000076d4f476e0
0x000000764e088d20:   00000000000001f0 0000000000000040
0x000000764e088d30:   000000764e089000 000000764e0890c4
0x000000764e088d40:   00000000005c0000 00000076d4f40178
0x000000764e088d50:   0000007627bfc558 0000000099d054f4
0x000000764e088d60:   0000000099d0552d 0000000099d054f0
0x000000764e088d70:   000000762922dc00 000000762922df38
0x000000764e088d80:   000000762922e000 99527d5de6096852
0x000000764e088d90:   0000000000000000 000000764e089040
0x000000764e088da0:   00000076546af940 00000076d4f401d8
0x000000764e088db0:   000000764e089058 000000009bd6f388
0x000000764e088dc0:   000000764e088e90 0000007627bfc558
0x000000764e088dd0:   000000764e089130 000000764e61e6d8
0x000000764e088de0:   0000000000000000 00000076d4f476e0
0x000000764e088df0:   00000000000001f0 0000000000000040
0x000000764e088e00:   000000764e088e00 000000764e0890c4
0x000000764e088e10:   00000076d547bc00 00000076d4f40178
0x000000764e088e20:   000000001b6b0b00 99527d5de6096852
0x000000764e088e30:   0000007613944000 000800020000488e
0x000000764e088e40:   0000000000000000 0000000000000039
0x000000764e088e50:   000000764c0f0900 000000765461bcc0
0x000000764e088e60:   000000764e089588 00000439d540a9a8
0x000000764e088e70:   0000007638338d4c 000000004e089588
0x000000764e088e80:   00000076546c83a0 99527d5de6096852
0x000000764e088e90:   0000000000000000 0000000000000000
0x000000764e088ea0:   0000000000000000 00000076546c83a0
0x000000764e088eb0:   0000000000000439 000800020000488e 

Instructions: (pc=0x00000076542264e4)
0x00000076542264c4:   c3 00 00 54 08 0b d7 9a 19 e1 17 9b 03 00 00 14
0x00000076542264d4:   23 00 00 14 39 01 18 8a 28 1a 00 f0 08 85 47 f9
0x00000076542264e4:   08 79 79 f8 c8 03 00 b4 08 01 40 f9 88 03 00 b4
0x00000076542264f4:   0a 02 00 b4 09 05 40 f9 3f 01 18 eb e0 00 00 54 

Register to memory mapping:

R0=0x00000075f4a71b70
R1=0x0000000000000000
R2=0x0000000000000000
R3=0xffffffff9fd065d4
R4=0x0009e34ff1000000
R5=0x00000076129f7eb8
R6=0x00000076daf34000
R7=0x00000000018808a8
R8=0x0000000000000000
R9=0x0000000000000c82
R10=0x0000000000000c82
R11=0x0000000000000006
R12=0x0000007654611f48
R13=0x0000000060307f74
R14=0x000a6353770152c7
R15=0x00001864e9ea9aae
R16=0x00000076d546fbd8
R17=0x00000076d5403d48
R18=0x0000000000000000
R19=0x000000765456df08
R20=0x000000009bd6f3a0
R21=0x00000075f4a71b70
R22=0x000000765456a048
R23=0x0000000000000c83
R24=0xb25ec1756f8580f1
R25=0x0000000000000755
R26=0x0000000000000338
R27=0x0000000099d054f4
R28=0x0000000099d054f0
R29=0x000000764e088d00
R30=0x000000765422644c


Stack: [0x000000764df89000,0x000000764e0894f0],  sp=0x000000764e088cc0,  free space=1023k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libart.so+0x2e54e4]  art::AddNativeDebugInfoForJit(void const*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&)+0x170
C  [libart-compiler.so+0x133ae4]  art::OptimizingCompiler::GenerateJitDebugInfo(art::ArtMethod*, art::debug::MethodDebugInfo)+0xa0
C  [libart-compiler.so+0x1336d8]

**Comment by yejunjie10311031** [comment]
@khanhduytran0 I update the latest build now,but there is still the "signal 11" crash problem and there is the hs_err_pid:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000074adb91668, pid=14834, tid=0x0000007550d8b548
#
# JRE version: OpenJDK Runtime Environment (8.0) (build 1.8.0-internal-runner_2021_01_24_23_30-b00)
# Java VM: OpenJDK 64-Bit Server VM (25.71-b00 mixed mode linux-aarch64 compressed oops)
# Problematic frame:
# C  [libpojavexec.so+0x5668]  android_sigaction+0x20
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00000074ca45a800):  JavaThread "Thread-6" daemon [_thread_in_native, id=14834, stack(0x0000007fcb872000,0x0000007fcba72000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00000000000039fa

Registers:
R0=0x0000000000000006
R1=0x0000000000000006
R2=0x0000000000000006
R3=0x0000000000000008
R4=0x0000000000008080
R5=0x0000000000008080
R6=0x0000000000008080
R7=0x0000000000000038
R8=0x00000000000039f2
R9=0x0d69b7e1a99c0a7e
R10=0x0000000000000000
R11=0xfffffffc7ffffbdf
R12=0x0000000000000001
R13=0x00000000603a00c9
R14=0x000ae9ae0dbb3a7c
R15=0x000010e9ef8a9f95
R16=0x000000754f4ef2c0
R17=0x000000754f42de34
R18=0x0000007464fff5d0
R19=0x00000000000039f2
R20=0x00000000000039f2
R21=0x00000075500bfd08
R22=0x0000000000000000
R23=0x00000075500bfcc0
R24=0x0000007550d8b5e0
R25=0x0000000000000000
R26=0x0000000000000001
R27=0x0000000000000000
R28=0x00000074ca4fd7a0
R29=0x0000007fcba69d80
R30=0x0000007550d79694

Top of Stack: (sp=0x0000007fcba69d60)
0x0000007fcba69d60:   000000009bc667d8 0000000000000006
0x0000007fcba69d70:   00000000000039f2 00000006707c82e8
0x0000007fcba69d80:   0000007fcba6afe0 0000007550d79694
0x0000007fcba69d90:   00000000000002d2 0000000000000000
0x0000007fcba69da0:   0000000099c67478 0000000000000000
0x0000007fcba69db0:   0000000099c67334 0000000000000143
0x0000007fcba69dc0:   00000074ca415c00 0000000000000000
0x0000007fcba69dd0:   0000000000000047 0000000000000013
0x0000007fcba69de0:   000000000000000d 000000000000000d
0x0000007fcba69df0:   000000000000005a 0d69b7e1a99c0a7e
0x0000007fcba69e00:   0000007550d8b5e0 0000000000000338
0x0000007fcba69e10:   0000000000000000 0000000000000000
0x0000007fcba69e20:   0000007550d6e000 0000000000000000
0x0000007fcba69e30:   0000000000004000 fffffff87ffbfadf
0x0000007fcba69e40:   0000007fcb000000 0000000000000000
0x0000007fcba69e50:   0000000013298780 000000006fb33710
0x0000007fcba69e60:   0000000000000000 0000000000000018
0x0000007fcba69e70:   0000000100000018 0000000000ef0dea
0x0000007fcba69e80:   0000007fcba69f10 0d69b7e1a99c0a7e
0x0000007fcba69e90:   0000000000000003 0000000000000000
0x0000007fcba69ea0:   0000000099c67424 0d69b7e1a99c0a7e
0x0000007fcba69eb0:   0000000000000000 0000000000000001
0x0000007fcba69ec0:   0000000000000000 0000000000000000
0x0000007fcba69ed0:   00000000000039f2 0000000000000006
0x0000007fcba69ee0:   0000000000000008 0000000000008080
0x0000007fcba69ef0:   0000000000008080 0000000000008080
0x0000007fcba69f00:   0000000000000038 0000000000000083
0x0000007fcba69f10:   0d69b7e1a99c0a7e 0000000000000000
0x0000007fcba69f20:   fffffffc7ffffbdf 0000000000000001
0x0000007fcba69f30:   00000000603a00c9 000ae9ae0dbb3a7c
0x0000007fcba69f40:   000010e9ef8a9f95 000000754f4ef2c0
0x0000007fcba69f50:   000000754f42de34 0000007464fff5d0 

Instructions: (pc=0x00000074adb91668)
0x00000074adb91648:   ff c3 00 d1 fd 7b 02 a9 fd 83 00 91 a0 c3 1f b8
0x00000074adb91658:   e1 0b 00 f9 e2 07 00 f9 a1 c3 5f b8 e8 0b 40 f9
0x00000074adb91668:   02 09 40 b9 e8 0b 40 f9 03 09 40 f9 e0 ff ff b0
0x00000074adb91678:   00 48 33 91 29 03 00 94 a8 c3 9f b8 09 00 00 f0 

Register to memory mapping:

R0=0x0000000000000006
R1=0x0000000000000006
R2=0x0000000000000006
R3=0x0000000000000008
R4=0x0000000000008080
R5=0x0000000000008080
R6=0x0000000000008080
R7=0x0000000000000038
R8=0x00000000000039f2
R9=0x0d69b7e1a99c0a7e
R10=0x0000000000000000
R11=0xfffffffc7ffffbdf
R12=0x0000000000000001
R13=0x00000000603a00c9
R14=0x000ae9ae0dbb3a7c
R15=0x000010e9ef8a9f95
R16=0x000000754f4ef2c0
R17=0x000000754f42de34
R18=0x0000007464fff5d0
R19=0x00000000000039f2
R20=0x00000000000039f2
R21=0x00000075500bfd08
R22=0x0000000000000000
R23=0x00000075500bfcc0
R24=0x0000007550d8b5e0
R25=0x0000000000000000
R26=0x0000000000000001
R27=0x0000000000000000
R28=0x00000074ca4fd7a0
R29=0x0000007fcba69d80
R30=0x0000007550d79694


Stack: [0x0000007fcb872000,0x0000007fcba72000],  sp=0x0000007fcba69d60,  free space=2015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libpojavexec.so+0x5668]  android_sigaction+0x20
C  [[vdso]+0x694]  __kernel_rt_sigreturn+0x0
C  [libc.so+0x22960]  abort+0x4c
C  [libc.so+0x84b58]  pthread_once+0x0
C  [libc.so+0x84254]  NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+0x0
C  [libc.so+0x84108]  pthread_mutex_lock+0xe8
C  [libc++.so+0x99cbc]  std::__1::mutex::lock()+0xc
C  [libminikin.so+0x13090]
C  [libminikin.so+0x12bec]
C  [libminikin.so+0x1297c]
C  [libminikin.so+0x124a8]

**Comment by Mathias-Boulay** [comment]
Stale issue from a really old version.
If such issue still manifests on the crocus update, I'm certain the author will come back to complain.
