### ISSUE TITLE
[BUG] Forge 1.16.4

### ISSUE THREAD

**Issue by Palotops** [PojavLauncherTeam/PojavLauncher#915]
Hi, I'm new to reporting bugs ... I wanted to say I can't install FORGE on Minecraft version 1.16.4, does anybody know how to install it without problems?

**Comment by PeterScorPioN** [comment]
Go to the official Forge site, select the version you want, select the universal package and install it, open Pojav Launcher, tap on settings, select the "Launch a mod installer" and find the package's location, install and play.

**Comment by Mathias-Boulay** [comment]
Isn't the universal installer unsupported ?

**Comment by PeterScorPioN** [comment]
> Isn't the universal installer unsupported ?

No, where did you get that from?

**Comment by artdeell** [comment]
Pojav (unlike Mcinabox) uses "Installer" packages

**Comment by ZeekaBobIs** [comment]
Can confirm this bug, Forge installer jar says it can't be compiled in the app (or something similar, tl;dr can't install forge for 1.16.4)

**Comment by Palotops** [comment]
> Vaya al sitio oficial de Forge, seleccione la versión que desee, seleccione el paquete universal e instálelo, abra Pojav Launcher, toque la configuración, seleccione "Iniciar un instalador de mod" y busque la ubicación del paquete, instálelo y juegue.

I have already done it and it still does not install, in another bug that I will report in the following hours I will send a video of how I install Forge.

**Comment by khanhduytran0** [comment]
@Palotops what about doing same thing as #922?

**Comment by OwzygZawg** [comment]
Lol notifications for me, why?

**Comment by Mathias-Boulay** [comment]
Pojav uses a GUI installer on its google play release.
Making the issue non existent, or at least fairly obvious to spot for the user.
Closing the stale issue.
