### ISSUE TITLE
When i click on the play then for 1 to sec controler page is showing and then it get back to the main page where we select the version

### ISSUE THREAD

**Issue by manangaur04** [PojavLauncherTeam/PojavLauncher#918]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by OskarZyg** [comment]
Same issue here, my stack trace is https://paste.gg/p/anonymous/2390c36e37964de38ada915345d427a9 (from android studio)

**Comment by Tomi321** [comment]
I have the same problem, I hope they will fix it

**Comment by khanhduytran0** [comment]
Nothing is fixed with almost no information provided.

**Comment by khanhduytran0** [comment]
> Add a log file if you want to see your bug fixed !

**Comment by OskarZyg** [comment]
Was the stack trace not sufficient?
