### ISSUE TITLE
[BUG] Launching 1.16.4 Fabric opens the game then immediately exits

### ISSUE THREAD

**Issue by GoldenFurredFox** [PojavLauncherTeam/PojavLauncher#919]
### Describe the bug
Launching 1.16.4 Fabric with mods, the game closes at soon as it opens, and clicking OK on the app prompt closes the app.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Install 1.16.4
3. Install Fabric 0.6.1.51
4. Add Fabric mods to games/pojavlauncher/.minecraft/mods

### Expected behavior:
I expected the game to open without issue

### Screenshots or videos:
![Screenshot_20210218-184800](https://user-images.githubusercontent.com/28793227/108436698-e8c67080-7219-11eb-9a9b-7f40312c16b9.png)

**Platform:**
 - Device Model: Motorola Moto g⁷ Power (moto-g7) [ocean]
 - CPU architecture: aarch64
 - Android Version: 10
 - PojavLauncher Version: Latest Release

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
latestlog.txt included below.
</pre>
</details>

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6006634/latestlog.txt)

**Comment by khanhduytran0** [comment]
Possibility corrupted Fabric installer. Maybe try download again?

**Comment by khanhduytran0** [comment]
@ZeekaBobIs reply?

**Comment by GoldenFurredFox** [comment]
I was away for a bit. I'll try as soon as I can. @khanhduytran0

**Comment by GoldenFurredFox** [comment]
Turns out I just never typed a version number for fabric and that's why it failed.
