### ISSUE TITLE
VMOS not work... 

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#92]
When I start VMOS it freezes and I can't do anything.  What else can I use instead of VMOS?  PS: don't I bother you with these questions? (sorry for bad english, I am from Poland)

**Comment by khanhduytran0** [comment]
You should report at VMOS developer instead of here.

**Comment by Azapru** [comment]
What else can I use instead of VMOS?

**Comment by khanhduytran0** [comment]
Nothing, because only VMOS app run Android on Android.

**Comment by Azapru** [comment]
> Nothing, because only VMOS app run Android on Android.

Ok. I am sad now.
