### ISSUE TITLE
[BUG] MultiModel - FML (Updated)

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#920]
### Describe the bug
The FML stops load the mods and a repeated log keeps showing up, in an infinite loop

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Run Forge 1.12.2
3. Load the mods

### Expected behavior:
I expected that Forge could load all mods successfully

**Platform:**
 - Device Model [Xiaomi Redmi]
 - CPU architecture [armv7] 
 - Android Version [Android 9]
 - PojavLauncher Version [version 3.3.1.1_rel_20210206 ]

[latestlog[1].txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6006874/latestlog.1.txt)

**Comment by khanhduytran0** [comment]
Send the full log instead. Also **#fill-the-template**!

**Comment by ghost** [comment]
Ready

**Comment by khanhduytran0** [comment]
So I see
- Some mods have inalid signature(??): redstoneflux, cofhworld, thermalXXX
- FML has found a non-mod file AutoConfig-1.12.2-1.0.2.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
- Mod "tconstruct" messed up..

**Comment by khanhduytran0** [comment]
- "MultiModel" also messed up

**Comment by ghost** [comment]
Thanks, I will do an investigation about. MultiModel is part of FML/client or part of some mod?

**Comment by ghost** [comment]
AutoConfig-1.12.2-1.0.2.jar is not in my mod folder, maybe is some mod who generate him

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
