### ISSUE TITLE
[F-REQ] Stupid Question Lol




### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#921]
Is it possible to convert Pojavlauncher IOS to Android? I liked his style ... I am not an iOS user this idea was stupid I know Lol

Maybe Buttons?

**Comment by khanhduytran0** [comment]
Get the latest build and enable "Flat button style"

**Comment by OwzygZawg** [comment]
> Get the latest build and enable "Flat button style"

Thank you

**Comment by OwzygZawg** [comment]
> Get the latest build and enable "Flat button style"

But I'm in the most recent

**Comment by OwzygZawg** [comment]
> > Get the latest build and enable "Flat button style"
> 
> But I'm in the most recent

@khanhduytran0 look

**Comment by khanhduytran0** [comment]
@OwzygZawg Look?

**Comment by OwzygZawg** [comment]
> @OwzygZawg Look? 

@khanhduytran0 I'm on the latest version of Pojavlauncher! how am I going to have the buttons flat?

**Comment by khanhduytran0** [comment]
@OwzygZawg latest build ≠ latest version

**Comment by OwzygZawg** [comment]
> @OwzygZawg latest build ≠ latest version 

Ok

**Comment by khanhduytran0** [comment]
I already said on settings
![Screenshot_2021-02-20-18-55-21](https://user-images.githubusercontent.com/40482367/108594576-5bb42080-73ad-11eb-9fc2-01ba3a8039a2.png)
If you ask for location it is 3rd item.
