### ISSUE TITLE
[F-REQ] Play on an Aternos server with PC players

### ISSUE THREAD

**Issue by Palotops** [PojavLauncherTeam/PojavLauncher#923]
Hello, I wanted to know if Pojav players will be able to play with computer players on servers like Aternos in the future.

**Comment by khanhduytran0** [comment]
Aternos IP have some problem. Connect use dynamic ip instead.
Any other servers such as Hypixel should work well.

**Comment by LanceAldrei04** [comment]
> Hello, I wanted to know if Pojav players will be able to play with computer players on servers like Aternos in the future.

Yes I'm playing Aternos. Want to join me?

**Comment by chrisfal10** [comment]
hi did u solve the problem

**Comment by khanhduytran0** [comment]
You can try 
- Update to latest build
if not working
- workaround: use dynamic up instead of domain name on server IP

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
