### ISSUE TITLE
[BUG] No working fabric 1.16.5(How add file?)

### ISSUE THREAD

**Issue by musinnur23** [PojavLauncherTeam/PojavLauncher#924]
**Add a log file if you want to see your bug fixed !**
How add files?

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_20210216-104704.png](https://user-images.githubusercontent.com/79198539/108466721-ed386b00-72a5-11eb-9c23-3953c4d04d79.png)

**Platform:**
 - Device Model PSP7551DUO Prestigio 
 - CPU architecture aarch64
 - Android Version 7.0
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by artdeell** [comment]
Just attach it as a media, to do that click on the tiny "image" button

**Comment by musinnur23** [comment]
пт, 19 февр. 2021 г., 11:35 ArtDev <notifications@github.com>:

**Comment by artdeell** [comment]
You can't send an image using email on githubb

**Comment by musinnur23** [comment]
пт, 19 февр. 2021 г., 11:39 ArtDev <notifications@github.com>:

**Comment by musinnur23** [comment]
> You can't send an image using email on githubb

Writes Unable to read file

**Comment by PeterScorPioN** [comment]
Какие-то моды не совместимы друг с другом. Какие моды ты устанавливал?

**Comment by musinnur23** [comment]
> Какие-то моды не совместимы друг с другом. Какие моды ты устанавливал?

Привет,не устанавливал никаких модов 
Не заходит вообще в игру 
Пишет игра вышла с кодом 1

**Comment by PeterScorPioN** [comment]
> > Какие-то моды не совместимы друг с другом. Какие моды ты устанавливал?
> 
> Привет,не устанавливал никаких модов
> Не заходит вообще в игру
> Пишет игра вышла с кодом 1

Странно. А ты устанавливал саму версию 1.16.5? Потому что если ты не установил обычную версию, то модификация не запустится.

**Comment by musinnur23** [comment]
> > > Какие-то моды не совместимы друг с другом. Какие моды ты устанавливал?
> > 
> > Привет,не устанавливал никаких модов
> > Не заходит вообще в игру
> > Пишет игра вышла с кодом 1
> 
> Странно. А ты устанавливал саму версию 1.16.5? Потому что если ты не установил обычную версию, то модификация не запустится.

Я устанавливал 1.16.5 все равно не работает выдает ошибку ![Screenshot_20210216-104709.png](https://user-images.githubusercontent.com/79198539/108582519-bc177380-7355-11eb-899f-d0b2f99bd91b.png)

**Comment by musinnur23** [comment]
> > > Какие-то моды не совместимы друг с другом. Какие моды ты устанавливал?
> > 
> > Привет,не устанавливал никаких модов
> > Не заходит вообще в игру
> > Пишет игра вышла с кодом 1
> 
> Странно. А ты устанавливал саму версию 1.16.5? Потому что если ты не установил обычную версию, то модификация не запустится.

Ты знаешь как отправлять файлы в GitHub
txt файлы

**Comment by OwzygZawg** [comment]
Before installing Fabric for 1.16.5, make sure you have installed 1.16.5 before!

**Comment by NotStolenTotally** [comment]
> Before installing Fabric for 1.16.5, make sure you have installed 1.16.5 before!

Still the same

**Comment by OwzygZawg** [comment]
> > Before installing Fabric for 1.16.5, make sure you have installed 1.16.5 before!
> 
> Still the same

Yes

**Comment by OwzygZawg** [comment]
> > Before installing Fabric for 1.16.5, make sure you have installed 1.16.5 before!
> 
> Still the same

make sure you are on the latest version 3.3.1.1!

**Comment by Mathias-Boulay** [comment]
fabric works perfectly on the current gplay update
closing
