### ISSUE TITLE
[BUG] impact 1.16+ Crash on mojang screen

### ISSUE THREAD

**Issue by Zeyrox1090** [PojavLauncherTeam/PojavLauncher#925]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
It crashes on mojang screen

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected it to work

### Screenshots or videos:
*hmmmmmmm no.*

**Platform:**
 - Device Model [idk RMX 2020 realme c3]
 - CPU architecture [aarch64] 
 - Android Version [10]
 - PojavLauncher Version [latest actions that is v3_openjdk ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by ItsProfessional** [comment]
Are you using an offline account and using impact nightly? if so then Impact Donator/Nightly versions dont work on offline account (I think).

**Comment by khanhduytran0** [comment]
@zeyrox1090 
> __** Add a log file if you want to see your bug fixed !**__

**Comment by Zeyrox1090** [comment]
yeah yeah i forgot

**Comment by Zeyrox1090** [comment]
[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6014021/latestcrash.txt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6014022/latestlog.txt)

**Comment by OwzygZawg** [comment]
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> <br>
> - Make sure there was not duplicated issues.<br>
> - Make sure you have filled this issue template, or this will get rejected.
> </details>
> 
> ### Describe the bug
> It crashes on mojang screen
> 
> **Add a log file if you want to see your bug fixed !**
> 
> The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> ### To Reproduce:
> Indicate steps to reproduce the buggy behavior:
> 
> 1. Start PojavLauncher
> ... *(your set of actions to reproduce the bug)*
> 
> ### Expected behavior:
> I expected it to work
> 
> ### Screenshots or videos:
> *hmmmmmmm no.*
> 
> **Platform:**
>  - Device Model [idk RMX 2020 realme c3]
>  - CPU architecture [aarch64] 
>  - Android Version [10]
>  - PojavLauncher Version [latest actions that is v3_openjdk ]
> 
> 
> <details> <summary><b>Additional context</b></summary>
> <br>
> <pre>
> Add any other context about the problem here.
> </pre>
> </details>
> 

You Failed

**Comment by Zeyrox1090** [comment]
what do you mean?

**Comment by OwzygZawg** [comment]
> what do you mean? 

a big failure happened

**Comment by Zeyrox1090** [comment]
what failure

**Comment by artdeell** [comment]
To even start Impact 1.16.x, you need to get Impact Premium AND an online account, or it wouldn't work

**Comment by OwzygZawg** [comment]
> To even start Impact 1.16.x, you need to get Impact Premium AND an online account, or it wouldn't work

Yeah

**Comment by Zeyrox1090** [comment]
i used premium acc i use impact nigthly is that wrong?

**Comment by artdeell** [comment]
Did you pay to Impact devs?

**Comment by HedHogie** [comment]
Hey zeyrox :)

**Comment by OwzygZawg** [comment]
> Hey zeyrox :)

Hey HedHogie :)

**Comment by khanhduytran0** [comment]
The log seems empty... Have you rerun before send log? Also maybe send /sdcard/games/PojavLauncher/latestlog.txt instead?

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
