### ISSUE TITLE
[BUG] Issue with hotbar and keybinds

### ISSUE THREAD

**Issue by Zelioz273** [PojavLauncherTeam/PojavLauncher#926]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
If any slot of the hotbar is directly touched, any custom keybinds that trigger a mod's feature stop functioning. And to revert this, i found that the only way was to switch between at least 2 slots using my buttons for 1-9 quickly.

**Add a log file if you want to see your bug fixed !**
I tried attaching it using the media button but chrome kept crashes so if you could tell me another method of attaching it i'll do that.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Use a key that has a custom keybind, such as a button that inputs "z" being keybinded to zoom
3. Press a slot of your hotbar
4. Key doesn't work anymore until you quickly switch between two keys using 1-9 buttons

### Expected behavior:
I expected the key to continue working as normal after pressing a slot on the hotbar.

### Screenshots or videos:
Wasn't sure if the video would really help since u can't see me actually pressing the buttons, but i'll send a video if needed.

**Platform:**
 - Device Model: Samsung Galaxy Note9
 - CPU architecture: aarch64
 - Android Version: 10
 - PojavLauncher Version: Build Android CI #2110

<details> <summary><b>Additional context</b></summary>
<br>
<pre> I'm using fabric 1.16.5 and the keys that were bugging out were y and z which were keybinded to a feature from tweakeroo.
</pre>
</details>

**Comment by Mathias-Boulay** [comment]
*nice title*
I assume this bug doesn't happen in vanilla ?

**Comment by Zelioz273** [comment]
> _nice title_
> I assume this bug doesn't happen in vanilla ?

Whoops let me correct the title, and give me a sec to try it in vanilla.

**Comment by Mathias-Boulay** [comment]
Wait you're using an action build that is not from the v3_openjdk branch 🤔

**Comment by Zelioz273** [comment]
No it doesn't seem to affect vanilla, seems to only affect keybinds to mods(i've had it on minihud and tweakeroo), and should i not be using this build?

**Comment by Mathias-Boulay** [comment]
To be honest the build isn't too far away from the one from the v3_openjdk branch.
*But I guess trying a build from that branch wouldn't hurt*

**Comment by Zelioz273** [comment]
Just tried it in the latest build from the v3_openjdk branch, still the same issue though

**Comment by Mathias-Boulay** [comment]
The crocus update should have fixed this issue, closing.

**Comment by Sfren09** [comment]
Any fix for iOS? Or is it just this

**Comment by Afran777** [comment]
Hotbar blinking problem on 1.18.2

**Comment by Bel69420** [comment]
PowerVR moment

**Comment by Bel69420** [comment]
What's your phone?
