### ISSUE TITLE
[BUG]     -Dorg.lwjgl.opengl.libname=libgl4es_115.so  works only if auto Ram is active! if Auto Ram is disabled, when starting a version the game simply crashes

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#927]
-Dorg.lwjgl.opengl.libname=libgl4es_115.so 

 works only if auto Ram is active! if auto Ram is disabled, when starting a version the game simply crashes

**Comment by Mathias-Boulay** [comment]
You didn't fill the bug template.
Please fill it, else not one can help you.

**Comment by OwzygZawg** [comment]
> You didn't fill the bug template.
> Please fill it, else not one can help you.

OKAY

**Comment by OwzygZawg** [comment]
@khanhduytran0 fix???

**Comment by Mathias-Boulay** [comment]
> @khanhduytran0 fix???

Bug template still not filled.

**Comment by OwzygZawg** [comment]
> > @khanhduytran0 fix???
> 
> Bug template still not filled.

So what am I supposed to do?

**Comment by Mathias-Boulay** [comment]
Fill the bug template: https://github.com/PojavLauncherTeam/PojavLauncher/blob/v3_openjdk/.github/ISSUE_TEMPLATE/bug_report.md
