### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by ukaboga** [PojavLauncherTeam/PojavLauncher#928]
Why can't mods like decocraft and replaymod be used? *Crash*
**Describe the solution you'd like**
-
**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Mathias-Boulay** [comment]
This sounds more like a bug.
In this regard, please fill the bug template instead.
Else no one can help you.

**Comment by Mathias-Boulay** [comment]
Stale issue, no template nor logs.
Decocraft works, and replaymod has a mod specific bug regarding ffmpeg.
Closing the issue
