### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SNOWyeye** [PojavLauncherTeam/PojavLauncher#929]
In the synthesis of materials,i Long time Clicks materials,materials cannot be separated,This brings great difficulties to my survival. I want to ask how to separate the materials and the buttons in the game can only set the attack button and the R button, which is very inconvenient when the keys conflict.I hope you can revise these two issues,very thankful.

**Comment by khanhduytran0** [comment]
You can press keys as same as playing on pc
- Hold + Shift click: split one item
- Right click: split / 2

**Comment by Mathias-Boulay** [comment]
Closing the issue, since the question has been answered. *(and it isn't a real issue)*
