### ISSUE TITLE
Shaders will crash the game

### ISSUE THREAD

**Issue by matteobranchi** [PojavLauncherTeam/PojavLauncher#93]
The game just crashes when I try to load any shader.
(Begin reading the error log from the bottom to the top)

![Screenshot_2020-04-14-22-41-41-942_com miui bugreport~3](https://user-images.githubusercontent.com/58168823/79272319-91d96780-7ea1-11ea-8184-07b7942aed07.jpg)
![Screenshot_2020-04-14-22-41-35-975_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272322-930a9480-7ea1-11ea-9599-7310a72d62ed.jpg)
![Screenshot_2020-04-14-22-41-26-224_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272323-93a32b00-7ea1-11ea-94b9-67a5975f5330.jpg)
![Screenshot_2020-04-14-22-41-31-107_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272324-93a32b00-7ea1-11ea-8e42-d34e2afacdc8.jpg)
![Screenshot_2020-04-14-22-41-18-249_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272325-943bc180-7ea1-11ea-8fb6-479014e7d8a2.jpg)
![Screenshot_2020-04-14-22-41-22-416_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272327-943bc180-7ea1-11ea-8d3d-cce19e68db4f.jpg)
![Screenshot_2020-04-14-22-41-13-473_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272329-94d45800-7ea1-11ea-96da-4dc5591c69c0.jpg)
![Screenshot_2020-04-14-22-41-08-609_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272330-94d45800-7ea1-11ea-8187-c05236dc7c3e.jpg)
![Screenshot_2020-04-14-22-40-55-688_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272333-956cee80-7ea1-11ea-8a57-8bb238675c2d.jpg)
![Screenshot_2020-04-14-22-41-03-781_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272335-96058500-7ea1-11ea-8414-6edb17e71cf5.jpg)
![Screenshot_2020-04-14-22-40-50-729_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272337-96058500-7ea1-11ea-81e6-04ff0ebe6c7d.jpg)
![Screenshot_2020-04-14-22-40-43-446_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79272338-969e1b80-7ea1-11ea-8e93-28018fb642e3.jpg)

**Comment by khanhduytran0** [comment]
I'm getting same crashes, all caused by OpenGL, `glDrawArray` made crash. I can't solve, so wait for new `gl4es` release or `Regal`.

**Comment by khanhduytran0** [comment]
It's non-solvable.
