### ISSUE TITLE
[F-REQ] In the next version, can the controls be changed while in the game?

### ISSUE THREAD

**Issue by hienvanmine25** [PojavLauncherTeam/PojavLauncher#931]
In the next version, can allow to change the controls while in the game? Because when I installed not enough a button I had to log out and reinstall again and my phone was weak so I entered the game for a long time, I hope in the next version will be able to change the buttons while in the game

**Comment by CriticalRange** [comment]
It would be a good feature that may do the work, maybe gui button could be changed too! Or maybe the mouse button, so we can easily see how much ram does minecraft use.

**Comment by hienvanmine25** [comment]
> Nó sẽ là một tính năng tốt có thể hoạt động, có thể nút gui cũng có thể được thay đổi! Hoặc có thể là nút chuột, để chúng ta có thể dễ dàng xem minecraft sử dụng bao nhiêu ram.

Thanks for the feedback!!

**Comment by jan77play** [comment]
Hello.In future versions, the ability to scroll the mouse will be added.Buttons have been added, but the function has not been added??

**Comment by Mathias-Boulay** [comment]
We can now change controls in game, on newer versions.
Closing the issue then 😄
