### ISSUE TITLE
[BUG] Cracked servers not working 

### ISSUE THREAD

**Issue by harsh-gupta-10** [PojavLauncherTeam/PojavLauncher#933]
I have tryed to join cracked servers they are not working and also not showing online

I gave PojavLauncher to my freind they also have same problem
I can join servers like Hypixel, other
But cracked servers are always offline

Platform:
 - Device Model Poco M2 6gb ram
 - CPU architecture 
 - Android Version 10
 - PojavLauncher Version

**Comment by Mathias-Boulay** [comment]
The bug templated isn't filled properly.
*However, checking automatic builds may help with your issue*
Read the README for a link.

**Comment by Slapp13** [comment]
Do you know, how to fix "cant resolve hostname" ?

**Comment by harsh-gupta-10** [comment]
> Do you know, how to fix "cant resolve hostname" ?

Delete the Minecraft account and login again with good Internet it will work 100%

**Comment by AgaricaGamer** [comment]
@IzooGGaming For Playing On Cracked Servers, I recommend you to create an account on here

>tlauncher.org

And Play!

**Comment by harsh-gupta-10** [comment]
OK thx I mostly use premium account

**Comment by khanhduytran0** [comment]
@AgaricaGamer we don't even support login using tlauncher

**Comment by harsh-gupta-10** [comment]
Then how I can play cracked servers

**Comment by AgaricaGamer** [comment]
We Can Login With Tlauncher Account

I m too Using It,

After You Have Created An Account On Tlauncher.org

You Need To Login, To Login Enter The Nametag U Have Used To Register On
Tlauncher And Leave The Password Empty. Select Login Offline And Login


Start Minecraft



Go To Multiplayer Add_Server->Add Any Server Of Your Choice

Ex: top.pika.host


And Play!


Hope This Helps?

**Comment by harsh-gupta-10** [comment]
Thx
