### ISSUE TITLE
[BUG] What should I do? I can't log in to pirate servers in minecraft.

### ISSUE THREAD

**Issue by Loolgit** [PojavLauncherTeam/PojavLauncher#936]
<details> < resume> < b>read before you send< / b>< / resume>
<br>
- Make sure there were no duplicate questions.
- Make sure you fill out this question template, otherwise it will be rejected.
</details>

### Describe the error
Does not connect in to the pirate servers minecraft 1.12.2

### Multiply:
Specify the steps to reproduce the buggy behavior:

1. Launch PojavLauncher
... I chose version 1.12.2
Launched
I selected the server and there was a connection error

### Expected behavior:
I expected it ...

### Screenshots or Videos:
* Upload screenshots or videos of buggy behavior here, if possible.*

**Platform:**
 - Device model [honor 7c]
- Processor architecture [ aarch64] 
 - Android version [, 8]
 - PojavLauncher version [Latest version / / version 3.3.1. 1_rel_20210206 ]

<details> <summary><b>Additional context< / b>< / summary>
<br>
<preliminary>
Add any other context regarding this issue here.

Error:io.netty.channel.ConnectTimeoutExcpetion:connection timed out

**Comment by khanhduytran0** [comment]
Server list?
You may try the latest action build there https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/588895401
