### ISSUE TITLE
[BUG] Replaymod doesn't work

### ISSUE THREAD

**Issue by rojaoo** [PojavLauncherTeam/PojavLauncher#938]
Hello, i'm a Pojav Launcher user, and i tried running Replaymod on it, but it didn't worked. First, also tried with older versions and forge, but i got the same problem, then i tried with the latest version of Minecraft, the mod and fabric. I tried openning a void world and i got this message:
![2021-02-22_13 27 26](https://user-images.githubusercontent.com/67767832/108717022-8f04c580-74fb-11eb-973b-fbc6d57270f0.png)
I got the same with **1.8.9**, **1.9.4** and **1.12.2**. I talked to one of the developers on Discord, and he told me to report this, [Here is exactly what he said](https://discord.com/channels/708304818829262910/709108200632483900/813403407335424021), so, that's what im doing.
If needed, here is the [latest.log](https://github.com/ReplayMod/ReplayMod/files/6022360/latest.log)

**Also, my phone is**
Moto G7 Play
Android 10
2gb RAM
armv7I

**And the game info**
Minecraft 1.16.5
Replaymod 1.16.4-2.5.2
Fabric 0.6.1.51

**Comment by Slapp13** [comment]
Yes, me too. I tried this mod on the 1.16.5, 1.12.2, and 1.8.9 versions and it didn't work.

**Comment by khanhduytran0** [comment]
Edit .minecraft/config/replay.cfg
Replace `./.replay_cache` with `/data/data/net.kdt.pojavlaunch/cache/.replay_cache` and try again.

**Comment by Slapp13** [comment]
![Uploading Screenshot_20210224-223231.png…]()
Thank you so much, it work :DD

**Comment by Slapp13** [comment]
> Edit .minecraft/config/replay.cfg
> Replace `./.replay_cache` with `/data/data/net.kdt.pojavlaunch/cache/.replay_cache` and try again.

Edit on both files, replaymod.cfg and replaymod.json

**Comment by rojaoo** [comment]
I just need to figure out on how to install the ffmpeg

**Comment by Slapp13** [comment]
![Screenshot_20210225-062107](https://user-images.githubusercontent.com/79562074/109079954-4edb5800-7732-11eb-902f-c0848d0e77ea.png)
now the problem is :

**Comment by khanhduytran0** [comment]
Known issue, due to missing component.

**Comment by kedrick021** [comment]
What version of replay mod are you using?

**Comment by kedrick021** [comment]
I don't see my character when I open replay views

**Comment by EnderBrine99FOX** [comment]
> What version of replay mod are you using?

reply mod is working with me (in 1.16.5) but you can extract the video form the launcher but you can record form your device.

**Comment by kedrick021** [comment]
I try 1.12.2 but I don't see my character only blocks placing here self

**Comment by kedrick021** [comment]
When I click replay views not open plsss reply

**Comment by Zelioz273** [comment]
Is there a workaround to using ffmpeg? Or can we just not render for now?

**Comment by khanhduytran0** [comment]
> Is there a workaround to using ffmpeg? Or can we just not render for now?

I’m unsure.

**Comment by ghost** [comment]
I have a idea.
I will try serach file ffmpeg for linux.

**Comment by Mathias-Boulay** [comment]
#1948
