### ISSUE TITLE
[BUG] Sodium not work in Fabric 1.16.5 In 32 bits

1 install fabric 1.16.5
2copy mod sodium in files mods
3 enter in game 
4 Sodium not work 

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#939]
1 install forge 1.16.5
2 copy mod sodium in files mods 
3 enter in game 
4 mod sodium not work

**Comment by Mathias-Boulay** [comment]
The bug template isn't properly filled.
*also, you have to disable some option on sodium to make it work*

**Comment by CriticalRange** [comment]
Be sure you are using latest runtime(or latest version i mean), i had this issue too i have 32bit device

**Comment by OwzygZawg** [comment]
Runtime is JRE2

**Comment by CriticalRange** [comment]
@OwzygZawg runtime is old, please update to the latest one, also 3.3.1.1 version automatically installs runtime so why take risk?

**Comment by OwzygZawg** [comment]
> @OwzygZawg runtime is old, please update to the latest one, also 3.3.1.1 version automatically installs runtime so why take risk?

It's okay But I'm already at 3.3.1.1

**Comment by OwzygZawg** [comment]
Wow bug resolved
