### ISSUE TITLE
The inventory exits while typing/searching an item

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#94]
It exits the inventory while i was searching/typing an item

And does Minecraft 1.12 work now on android 8.1?

**Comment by khanhduytran0** [comment]
> It exits the inventory while i was searching/typing an item

Where you press E?

> And does Minecraft 1.12 work now on android 8.1?

May not, but you can do a test.

**Comment by FranzelDamasco909** [comment]
> Where you press E?

on the search bar

> May not, but you can do a test.

Idk because it gives me insufficient storage and doesn't work

**Comment by FranzelDamasco909** [comment]
try check your codes or something you will might find a problem about launching on 1.12 so it will be fixed

**Comment by FranzelDamasco909** [comment]
idk about coding Java

**Comment by khanhduytran0** [comment]
May have a switch for send keycode or char.

**Comment by FranzelDamasco909** [comment]
Anything for 1.12

**Comment by khanhduytran0** [comment]
Still not working

**Comment by FranzelDamasco909** [comment]
if depends on launching 1.12

**Comment by khanhduytran0** [comment]
React native bootstrap error.

**Comment by FranzelDamasco909** [comment]
> Still not working

Ok thank you! i hope you fix it

**Comment by khanhduytran0** [comment]
Try v3. (That bug may still exists)
