### ISSUE TITLE
What Shaders Are Supported in Optifine PojavLauncher? 

### ISSUE THREAD

**Issue by GeraldAligner** [PojavLauncherTeam/PojavLauncher#941]
I know this isn't a bug report but I really want to use Shaders. 
Even if it's basic I really want to use them. 
And why do most Shaders not work on pojavlauncher?

**Comment by HedHogie** [comment]
Waving plants shader, and the shader that shulker sakura is working on.

**Comment by ikmjssc** [comment]
Shaders use OpenGL, but Android uses OpenGLES. They're not working on Android.

**Comment by AjGamingPHOfficial** [comment]
We are.

**Comment by LanceAldrei04** [comment]
> We are.

Aj can you share us your shader. I will subscribe your YT channel.👍👍👍

**Comment by AjGamingPHOfficial** [comment]
Under development.

**Comment by khanhduytran0** [comment]
Get open4es
