### ISSUE TITLE
[BUG] Hello again, I'm stuck installing forge 1.16.5 in the laste build version of Pojavlauncher!

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#942]
Hello again, I'm stuck installing forge 1.16.5 in the laste build version of Pojavlauncher!![Screenshot_20210223-015855_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/75042110/108804443-11cd6500-757c-11eb-9833-1afbd87d6609.jpg)![Screenshot_20210223-015906_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/75042110/108804452-1560ec00-757c-11eb-9615-9875ff5f01fe.jpg)![Screenshot_20210223-015913_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/75042110/108804460-17c34600-757c-11eb-96d5-608185eccbd0.jpg)![Screenshot_20210223-020646_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/75042110/108804469-1b56cd00-757c-11eb-9005-2d844e79f5a3.jpg)![Screenshot_20210223-020701_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/75042110/108804473-1c87fa00-757c-11eb-8e6f-70c884493c29.jpg)

**Comment by artdeell** [comment]
send latestlog after trying to install

**Comment by khanhduytran0** [comment]
@OwzygZawg **you are the guy who never fill the template**!

**Comment by OwzygZawg** [comment]
> @OwzygZawg **you are the guy who never fill the template**!

Oh sorry

**Comment by OwzygZawg** [comment]
> send latestlog after trying to install

Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=1280x720, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /storage/emulated/0/Download/forge-1.16.5-36.0.42-installer.jar] --------- beginning of main WARNING: linker: " /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so " has unsupported flags DT_FLAGS_1= 0x81 I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libverify.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnet.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libnio.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfreetype.so failed: dlopen failed: library "libpng16.so.16" not found I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so failed: dlopen failed: library "libfreetype.so.6" not found I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjsig.so failed: dlopen failed: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjsig.so" is too small to be an ELF executable: only found 13 bytes I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/client/libjvm.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/jli/libjli.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_headless.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libawt_xawt.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libdt_socket.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so failed: dlopen failed: library "libfreetype.so.6" not found I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libhprof.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libinstrument.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2gss.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pcsc.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libj2pkcs11.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjaas_unix.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjava_crw_demo.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so failed: dlopen failed: cannot locate symbol "awt_GetComponent" referenced by "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjawt.so"... I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjdwp.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjpeg.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsdt.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsig.so success I/jrelog (10724): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libjsound.so success

**Comment by khanhduytran0** [comment]
The log you provided likely cropped out. Please send the file instead of raw text.

**Comment by OwzygZawg** [comment]
> The log you provided likely cropped out. Please send the file instead of raw text.

It was not cut, the file stopped and was stuck on the installation screen! resolved  I will close the report ...
