### ISSUE TITLE
[F-REQ] Could add third-party login?

### ISSUE THREAD

**Issue by wherewhere** [PojavLauncherTeam/PojavLauncher#943]
An other JE Launcher called MCinaBox can add third-party login server. Could you add this feature? 
![Screenshot_20210223-135532](https://user-images.githubusercontent.com/27689196/108807244-d87a1100-75de-11eb-99b6-7630d6b429aa.jpg)

**Comment by CriticalRange** [comment]
There might be a way to do it if you use an hacked client with alt manager

**Comment by matt995** [comment]
Use wurst client it supports alts
