### ISSUE TITLE
[F-REQ] Keyboard layers

### ISSUE THREAD

**Issue by Zelioz273** [PojavLauncherTeam/PojavLauncher#944]
**Is your feature request related to a problem? Please describe.**
I've been adding keys to my keyboard as find more situations, and add on that i play with mods, 8 keys of the left side are already for mod keybinds. So my screen gets pretty crowded.

**Describe the solution you'd like**
A solution i'd like to this is if there could be keyboard layers. My idea would be another special button like gui button that would store a layer value, and when tapped, tany keys with that same layer number would be shown/hidden. And the keys without a layer number would not be affected by this and would just stay shown. I'd also suggest if you could create multiple layer buttons for more than just 1 layer and that the layer buttons would be unhideable like the mouse button is.

I already see i problem that would happen if you tried making two keys on seperate layers that would overlap, so a solution to this could be adding layer functionality to the keyboard editor, so you can edit one layer at a time, or see them all at once using and "all" layer(and either keys with no layer are shown in any layer at the editor, or are only shown in "all" layer).

**Describe alternatives you've considered**
I've managed to add a good amount of keys by making sure i wouldn't tap them while playing normally and making sure they're off to the side as much as possible. But at this point, i'm not really able to add anymore keys without blocking the view or having them accidentally tapped. Another solution to this could be just making another keyboard, but there isn't a way to change keyboards ingame(much less edit keyboards ingame), and it'd be much faster to switch layers with a key, and you could make way better keyboards using layers, without blocking too much of the screen at once.

**Additional context**
![Screenshot_20210223-011402_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/41243839/108808363-7684c180-7574-11eb-9a10-b2da4884bda0.jpg)
This is my keyboard for reference- pretty crowded as i said. I would be able to hide keys i'm not using at the moment using layers. The right/left clicks on the left are for inventory management (I drag with my right thumb while clicking with my left), and the ones on the right are for placing/breaking. The W(togglable), A, and D are for boats which were painful to move using only the left W, A, D. And the hotbar block is well, to block me using the hotbar since tapping the hotbar bugs out my keybinds as i stated in a bug report already.

**Comment by Zelioz273** [comment]
Sorry if that was lengthy. Wanted to make sure i get the idea across fully.

**Comment by Mathias-Boulay** [comment]
The future control update will add a keyboard drawer, which will make the situation better
Also the hotbar works properly on the current google play release of pojav

**Comment by Zelioz273** [comment]
I'll close it since the feature has been added, thank you!

**Comment by shiroicrow973** [comment]
I want to download

**Comment by zmysoficial** [comment]
omg, how to download?

**Comment by TheHunter7304** [comment]
I want the control link
