### ISSUE TITLE
[BUG] Crash, 1.13+ No crash log at all

### ISSUE THREAD

**Issue by HedHogie** [PojavLauncherTeam/PojavLauncher#945]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
When I play minecraft 1.13+ (usually 1.16) I crash after an hour or less
**Add a log file if you want to see your bug fixed !**
No log, the crash log won't appear.
The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:
1. Start PojavLauncher
2. Launch versions 1.13-1.16
3. Play for a few minutes 
4. Game crash, no log whatsoever
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected Minecraft to not crash, I've tried to install the whole minecraft version, still no changes, still crashes

### Screenshots or videos:
No crash log, or anything

**Platform:**
 - Device Model Vivo Y15
 - CPU architecture aarch64
 - Android Version 10
 - PojavLauncher Version version 3.3.1.1_rel_20210206 (really)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Mathias-Boulay** [comment]
Maybe there is a latestlog.txt under the PojavLauncher folder ?
