### ISSUE TITLE
[BUG] Failed to launch TLauncher modpack.

### ISSUE THREAD

**Issue by PeterScorPioN** [PojavLauncherTeam/PojavLauncher#948]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I have TLauncher in my laptop, and there's a modpack feature there, where you can put some mods in a different Minecraft version. The fact is that these TLauncher modpacks are not depended on anything. They work as a different version and it contains every needed folder inside the version folder. Whoever had TLauncher, will understand. So i tried to run one modpack, but it led to crash, as i wasn't expecting... Is something that i do wrong, or running this modpack is impossible for now?

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6036472/latestlog.txt)

### To Reproduce:

1. Start PojavLauncher
2. Launch a modpack from TLauncher
3. See that it crashes

### Expected behavior:
I expected it to work, as it's not something hard for Pojav to launch.

### Screenshots or videos:
There are no screenshots, because i can't take a photo of a crash.

**Platform:**
 - Device Model [Xiaomi Pocophone F1 6/64]
 - CPU architecture [aarch64] 
 - Android Version [10]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
> Sorry, i don't know how to put the log as a file here...

You can just attach it as image (rename to image extension is not required).

**Comment by PeterScorPioN** [comment]
> > Sorry, i don't know how to put the log as a file here...
> 
> You can just attach it as image (rename to image extension is not required).

Ok, done. Thanks for helping.👍🏼

**Comment by Mathias-Boulay** [comment]
#1948
