### ISSUE TITLE
[BUG] Build OpenJDK Aarch32 server error

### ISSUE THREAD

**Issue by fandangos** [PojavLauncherTeam/PojavLauncher#949]
Hey, need some more help.

I'm trying to build your OpenJDK with the build scripts. I have successfully build it for aarch64 server for my project (libbluray bluray menu on Kodi Android).

Now I'm trying to build an aarch32 (arm) version so more people can use it. Many android tv box don't support aarch64. 

But I'm always facing the same error:
```
`cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++

gmake[6]: *** No rule to make target '/home/leviatan/openjdk_debug/openjdk/hotspot/src/cpu/aarch32/vm/aarch32.ad', needed by '../generated/adfiles/linux_aarch32.ad'.  Stop.

gmake[6]: *** Waiting for unfinished jobs....

Compiling /home/leviatan/openjdk_debug/openjdk/hotspot/src/share/vm/adlc/output_h.cpp

cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++

gmake[5]: *** [/home/leviatan/openjdk_debug/openjdk/hotspot/make/linux/makefiles/top.make:91: ad_stuff] Error 2

gmake[4]: *** [/home/leviatan/openjdk_debug/openjdk/hotspot/make/linux/Makefile:284: debug] Error 2

gmake[3]: *** [Makefile:231: generic_build2] Error 2

gmake[2]: *** [Makefile:177: debug] Error 2

gmake[1]: *** [HotspotWrapper.gmk:45: /home/leviatan/openjdk_debug/openjdk/build/linux-aarch32-normal-server-slowdebug/hotspot/_hotspot.timestamp] Error 2

make: *** [/home/leviatan/openjdk_debug/openjdk//make/Main.gmk:110: hotspot-only] Error 2
`
```

any idea how can I solve this to be able to compile?
with JVM_VARIANT set to client instead of server I can compile it without any problem.

**Comment by khanhduytran0** [comment]
Did you got clone to aarch32 port?

**Comment by fandangos** [comment]
> Did you got clone to aarch32 port?

Yes.
I'm editing the clonejdk.sh script with my own fork:
https://github.com/fandangos/openjdk-aarch32-jdk8u
Or
https://github.com/fandangos/openjdk-multiarch-jdk8u

But the same happens with the default one.
I forked it because of 2 small changes to make it work with the android setup of libbluray.
Just disabled the check for Java Home and added android to the fix for libnio.so pre loading bug.

**Comment by khanhduytran0** [comment]
Do you know that OpenJDK for aarch32 does not supports server variant?
