### ISSUE TITLE
[F-REQ]badlion client installer add in 3.1.1.2

### ISSUE THREAD

**Issue by whycantatall** [PojavLauncherTeam/PojavLauncher#952]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
Invalid, Badlion client isn’t even available for Linux yet.

**Comment by terrified9** [comment]
it is now

**Comment by RehanGamer49** [comment]
> it is now

True But its not in the .jar format even if it was it still wont work cause of the launcher

**Comment by KadirBerkPolat** [comment]
Yeter pojav artık salwyr client olmuyo badlion olmuyo siza ricam boyu büyütme küçültmeyi geri getirin ve ekstra client yükleyicisi ekleyim
