### ISSUE TITLE
[BUG] Decocraft 1.12.2 

### ISSUE THREAD

**Issue by ukaboga** [PojavLauncherTeam/PojavLauncher#956]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I installed decocraft in 1.12.2, when I started the game, it was very laggy and took a long time to load the mojang logo 

**Add a log file if you want to see your bug fixed !**https://www.mediafire.com/file/x6ygy6ohelreb78/latestlog.txt/file

https://www.mediafire.com/file/lcaaf2czw2s675p/latest.log/file

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected...Decocraft will work in 1.12.2 and everyone will be helped by the bug fix in decocraft 1.12.2 ... if this is fixed I will be very grateful to the Pojavlauncher team because Everyone's dream will be fulfilled.

### Screenshots or videos:
I can't because it's so laggy

**Platform:**
 - Device Model [e.g. realme 5]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 9]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by ukaboga** [comment]
I hope this can be fixed

**Comment by artdeell** [comment]
Not a bug. our phone is probably too slow.

**Comment by PeterScorPioN** [comment]
> Not a bug. our phone is probably too slow.

As i know, the Realme 5 is a pretty good phone. The problem is that decocraft is one of the biggest mods and it's loading takes a while, whatever phone you have... Now, about the lag... I don't know. I didn't try decocraft myself, as i don't need it. Although it might be that you dedicated less RAM, than the mod needs. As this mod needs a lot of RAM, try putting at least 1800mb, if it's possible.

**Comment by ukaboga** [comment]
> > Not a bug. our phone is probably too slow.
> 
> As i know, the Realme 5 is a pretty good phone. The problem is that decocraft is one of the biggest mods and it's loading takes a while, whatever phone you have... Now, about the lag... I don't know. I didn't try decocraft myself, as i don't need it. Although it might be that you dedicated less RAM, than the mod needs. As this mod needs a lot of RAM, try putting at least 1800mb, if it's possible.

thanks for the suggestion, as well as the explanation

**Comment by WesleyVanNeck** [comment]
is prety slow compared to a redmi note 9s with a snapdragon 720G

**Comment by WesleyVanNeck** [comment]
also 3 to 4gb of ram could be issue

**Comment by WesleyVanNeck** [comment]
https://www.gsmarena.com/realme_5-9802.php

**Comment by Mathias-Boulay** [comment]
Minecraft launches well with the latest forge and decocraft 1.12.2 on the latest google play release.
although it requires a lot of ram.

Closing.
