### ISSUE TITLE
[BUG] <No Sound On The Deepslate Blocks?>

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#957]
In The Latest SnapShot 21w08a New Block Called Deepslate Have Unique Sound, And They Mentioned That In The Official ChangeLog:https://www.mcbedrock.com/2021/02/24/minecraft-1-17-caves-cliffs-snapshot-21w08a-ores-retextured/#tab1

But There Is No Sound Is That From The Game Or Not Cuz I Tried This On Pc And It Have Sound Why? 

https://user-images.githubusercontent.com/79517194/109152673-df3e8a80-777c-11eb-93b6-42a714a37010.mp4

Pojav POV

**Comment by Mathias-Boulay** [comment]
If the game has no sound on your pc either, it isn't a Pojav problem.

**Comment by EnderBrine99FOX** [comment]
> If the game has no sound on your pc either, it isn't a Pojav problem.

It Have Sound On Pc But In Pojav It Doesn't

**Comment by EnderBrine99FOX** [comment]
@Mathias-Boulay

PoJav POV:

https://user-images.githubusercontent.com/79517194/109153334-d4382a00-777d-11eb-9a7b-622015ae52d1.mp4

**Comment by ednellbasilio** [comment]
Mine to no sounds

**Comment by khanhduytran0** [comment]
Did you skip downloading assets?
