### ISSUE TITLE
I have a Question

### ISSUE THREAD

**Issue by baqarigamer** [PojavLauncherTeam/PojavLauncher#958]
1 When is Open4es Shader is gonna release?
2 is there going to be a new pojav update?
3 how to fix labi mod not working it says no mod found 
![Screenshot_2021-02-23-14-29-49-68_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/74422738/109157248-35b2c580-778b-11eb-9102-248e2a09a0fe.jpg)

**Comment by chrisfal10** [comment]
which mod are u installing ?
I guess the mod u are installing requires fabric/forge

**Comment by Mathias-Boulay** [comment]
The shader is now available and that's not a real issue.
Closing.
