### ISSUE TITLE
Add Custom Resolution Scaling

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#959]
Add Custom Resolution Scaling like this 1018 x 480.

**Comment by khanhduytran0** [comment]
It would be buggy to implement, may caused input not working, a bunch of issues about screen messed up, etc... Instead, use resolution downscaler.

**Comment by LanceAldrei04** [comment]
> It would be buggy to implement, may caused input not working, a bunch of issues about screen messed up, etc... Instead, use resolution downscaler.

Ah ok
