### ISSUE TITLE
[F-REQ]modpack installer

### ISSUE THREAD

**Issue by whycantatall** [PojavLauncherTeam/PojavLauncher#961]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
What about installing mod pack manually? In the world of Minecraft mods, every mod pack uses different structure, how can we properly detect every modpack?

**Comment by CriticalRange** [comment]
Aswell as none of the launchers does this afaik
