### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by 2019Z2** [PojavLauncherTeam/PojavLauncher#962]
Some of the languages aren't displayed properly.
In fact, that don't display at all
One of the languages affected are: Hebrew (Israel)
Also, I would like to help translating with crowdin, and I would like to know how

**Comment by Mathias-Boulay** [comment]
Hey @2019Z2, if you want to participate in the translation of the launcher, you have to go here: https://crowdin.com/project/pojavlauncher
