### ISSUE TITLE
When I spam left click and move my camera at the same time it lags fix it

### ISSUE THREAD

**Issue by eeeeepeeee** [PojavLauncherTeam/PojavLauncher#964]
When I spam left click and move my camera at the same time it lags fix it

**Comment by khanhduytran0** [comment]
**bruh** lazy fill the template.

**Comment by ghost** [comment]
Fck what you issue?

**Comment by Mathias-Boulay** [comment]
Stale issue with nothing to help debugging the underlying problem.
Closing the issue.
