### ISSUE TITLE
[BUG] Cannot access Realm when login with Microsoft Account

### ISSUE THREAD

**Issue by MeguMario** [PojavLauncherTeam/PojavLauncher#965]
### Describe the bug
When login with Microsoft Account, upon accessing realm will return the "Invalid session id" error, this is not happened with Mojang account as realm works fine

Private server works, as hypixel and other server work perfectly fine

**Logs:**

Mojang account:
https://files.catbox.moe/2oc5a6.txt

Microsoft account:
https://files.catbox.moe/q4a6lh.txt

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher and login with either Microsoft / Mojang account first
2. start any version that support Minecraft Realm (mine is 1.16.5 with fabric, but this also affect vanilla Minecraft)
3. Click on the Minecraft Realm button
4. Now login with the other account and repeat step 2 and onward.
5. Done

### Expected behavior:
With Microsoft account, "Invalid session id" error should be returned
With Mojang account, everything should work as intended

### Screenshots or videos:
this error is really straightforward, no screenshot is needed to describe this

**Platform:**
 - Device Model: Google Pixel 3 (blueline)
 - CPU architecture: aarch64
 - Android Version: S (Android 12 Developer Preview 1)
 - PojavLauncher Version: Pull Request #908 (the latest automated build)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
nothing else.
</pre>
</details>

**Comment by khanhduytran0** [comment]
You should not download builds from #908 (l30n_v3_openjdk), this branch is just for translation update, but source code did not sync from upstream usually.

**Comment by Mathias-Boulay** [comment]
@MeguMario does the bug still happens with the current google play build ?
If the bug is still present, video footage of it could be nice.

**Comment by grylynebula508** [comment]
Why is he can login in a Microsoft account but me pojavlauncher version 3.3.1.1 i cant log in and i just watch ecosoldiers video and he can login in his Microsoft account

**Comment by khanhduytran0** [comment]
> Why is he can login in a Microsoft account but me pojavlauncher version 3.3.1.1 i cant log in and i just watch ecosoldiers video and he can login in his Microsoft account

@grylynebula508 you can't expect to be able to login without buying Minecraft Java or migrating to.

**Comment by khanhduytran0** [comment]
> ecosoldiers video and he can login in his Microsoft account

Basically he **bought Minecraft** or migrated into his Microsoft account so he was able to login.

**Comment by Mathias-Boulay** [comment]
The issue is still valid on the crocus update.
Tested with my migrated account.

**Comment by Tacosmeow** [comment]
I have the same problem I can't play realms

**Comment by ghost** [comment]
> I have the same problem I can't play realms

devs is still trying to fix the problem so please wait

**Comment by nodex4** [comment]
I have the same problem any fixes yet?

**Comment by GaucovyAero** [comment]
> I have the same problem any fixes yet?

No fix yet, unfortunately.

**Comment by altheawesomeguy** [comment]
Still no fix

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
