### ISSUE TITLE
How to solve rendering problems, such as wool and flags

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#966]

**Comment by AutumnVN** [comment]
-Dorg.lwjgl.opengl.libname=libgl4es_115.so
add this to jvm argument

**Comment by yanluol** [comment]
Where is the path?

**Comment by AutumnVN** [comment]
![Screenshot_2021-02-26-12-48-20-53](https://user-images.githubusercontent.com/77253698/109260564-f0e16a00-7830-11eb-977c-5231e865db40.png)

**Comment by yanluol** [comment]
thanks for your help

**Comment by yanluol** [comment]
Game crash after adding
