### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#967]
Add themes and colors for controls like MCinaBox.

**Comment by LanceAldrei04** [comment]
Try playing MCinaBox. Look at the controls and try to edit.

**Comment by netkv** [comment]
Vram on mobile phones is limited, adding textures to buttons would make eat it more, maybe thats one of reason why mcinabox is slower.

**Comment by LanceAldrei04** [comment]
> Vram on mobile phones is limited, adding textures to buttons would make eat it more, maybe thats one of reason why mcinabox is slower.

Eat more?

**Comment by Zelioz273** [comment]
They're saying if they made it so the buttons had textures, minecraft would be slower, to put it simply.
