### ISSUE TITLE
[Request] New Settings Feature for Launcher

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#97]
Renovate settings by adding more options like:

-Holding time on dropping an item on hotbar

-Import a Resource Pack (Texture packs and Shaders but only if it has Optifine. Idk if it needs Optifine or not)

-Import Custom Skin

-Import Custom Capes (Only for 1.8-1.11.2+)

And that's all .-.

**Comment by khanhduytran0** [comment]
> -Holding time on dropping an item on hotbar

Already added

> -Import a Resource Pack (Texture packs and Shaders but only if it has Optifine. Idk if it needs Optifine or not)

Maybe add later.

> -Import Custom Skin
> -Import Custom Capes (Only for 1.8-1.11.2+)

Not yet planned.

**Comment by khanhduytran0** [comment]
> -Holding time on dropping an item on hotbar

[Are you thinking this?](https://youtu.be/Cg-s4UZq_IE)

**Comment by FranzelDamasco909** [comment]
yes

**Comment by FranzelDamasco909** [comment]
it means the seconds of holding and dropping the item, and that's what i'm thinking about

**Comment by khanhduytran0** [comment]
Second (s) or 2nd?

**Comment by FranzelDamasco909** [comment]
The Seconds

**Comment by khanhduytran0** [comment]
0.5s

**Comment by FranzelDamasco909** [comment]
No i mean the feature that you can customize the seconds of holding and dropping an item

**Comment by khanhduytran0** [comment]
OK, understanded.

**Comment by FranzelDamasco909** [comment]
ok i'm not trying to be bossy i'm just explaining to understand what am i saying

**Comment by khanhduytran0** [comment]
But it is a little hard to understand. Something like **customize how long to hold to drop item**.

**Comment by FranzelDamasco909** [comment]
> Something like customize how long to hold to drop item.

yes that

**Comment by khanhduytran0** [comment]
Check Preview 2.5!
