### ISSUE TITLE
[QUESTION] where is the directory to install mods and how do I go to the menu when in a game

### ISSUE THREAD

**Issue by Arbifoxx** [PojavLauncherTeam/PojavLauncher#970]
I was playing multiplayer and I realized there was no option to go to the menu (I wanted to set sensitivity.) Also I wanted to install Forge. Do I install the forge installer or the actual jar that forge launches. Finally, where is the directory to install mods and import saves and resource packs?

**Comment by NoLegitHere** [comment]
1. Turn on hidden directory in your file manager
2. The back button can be used to acess the options and resources manager(texture packs manager)
3. 3. Download forge in the offical forge website with the version you wanted, choose install a mod loader and select your forge .jar
