### ISSUE TITLE
Would you like to add authlib-injector support for pojav?

### ISSUE THREAD

**Issue by ThreeIce** [PojavLauncherTeam/PojavLauncher#972]
Would you like to add authlib-injector support for pojav?
It's really important to us. Thank you very much

**Comment by LanceAldrei04** [comment]
What is authlib-injector????????????

**Comment by ThreeIce** [comment]
https://github.com/yushijinhun/authlib-injector
It can be used to custom yggdrasil service. It means that we can custom mc login system to insteam Mojang's login system.
HCML launcher has supported it.

**Comment by ThreeIce** [comment]
It changed mojang's yggdrasil url to custom url.

**Comment by ThreeIce** [comment]
https://github.com/huanghongxun/HMCL

**Comment by ThreeIce** [comment]
Would Anyone Like to help me? Really Thanks.

**Comment by khanhduytran0** [comment]
Duplicate #824

Adding 3rd party authlib sounds illegal
