### ISSUE TITLE
[BUG] 1.2.5 Crashes

### ISSUE THREAD

**Issue by NBGReal** [PojavLauncherTeam/PojavLauncher#973]
Playing Minecraft 1.2.5 for +30 Seconds, Crashes the game.
There is no Logs or Crash Reports Created, it Just Takes me Back to The Account Selection Screen.
Is There a Way to Fix This?

**Comment by WesleyVanNeck** [comment]
follow the isue template

**Comment by khanhduytran0** [comment]
@NBGReal
