### ISSUE TITLE
[BUG] Crash Upon Launching Game 1.12.2 [Forge/Vanilla]

### ISSUE THREAD

**Issue by Domin0de** [PojavLauncherTeam/PojavLauncher#974]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
Upon starting any version/type of the Minecraft client, the launcher opens the game, and immediately crashes, returning to the launcher main menu. This has been tested with both Vanilla and Forge releases of the 1.12.2 Minecraft version, with the issue occurring on both releases.

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6053009/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Select a version and press "Play"
3. Wait for the client to open
4. The client crashes, returning to the main menu of the launcher.

### Expected behavior:
I expected the client to open normally and be functional/operational with inputs.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model: Oppo F1s
 - CPU architecture: aarch64
 - Android Version: Lollipop MR1 5.1
 - PojavLauncher Version: version 3.3.1.1_rel_20210125

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
As what I see on log, your current system is aarch32, so 1GB RAM is too high. You may try set less RAM.

**Comment by Domin0de** [comment]
I am using the Auto RAM option, and have also lowered the defined RAM within the JVM arguments after turning it off, but the same issue still occurs, with the same latestlog.txt output.

**Comment by khanhduytran0** [comment]
Could you try to set to 512mb ram?

**Comment by Domin0de** [comment]
That was the lowered RAM value I alluded to in the previous comment, unfortunately that too doesn't seem to work.

**Comment by ghost** [comment]
there is one way, namely "UPDATE TO LATEST BUILD"

**Comment by Domin0de** [comment]
The latest available release which can be found in the [Releases](https://github.com/PojavLauncherTeam/PojavLauncher/releases) page corresponds to "version 3.3.1.1_rel_20210125" which is the version being used by myself? (I have tried "updating" to the latest release, i.e reinstalling, to no avail.)

**Comment by AutumnVN** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk

**Comment by Domin0de** [comment]
I have installed the newest build from the link, but the game continues to crash when opened, returning to the launcher menu. The [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6054119/latestlog.txt) file also slightly differs, no longer ending in the two error messages from before.

**Comment by Domin0de** [comment]
Fixed in latest Google Play Store release.

**Comment by 8eg1ner** [comment]
I want to play Minecraft forge 1.12.2 and i don't know why its always say to check latestlog.txt

**Comment by GaucovyAero** [comment]
> I want to play Minecraft forge 1.12.2 and i don't know why its always say to check latestlog.txt

your game has crashed

**Comment by nickgame-ux** [comment]
java.lang.IllegalArgumentException: You must pass a valid uri and observer
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1231)
	at android.content.ContentResolver.query(ContentResolver.java:1158)
	at android.content.ContentResolver.query(ContentResolver.java:1114)
	at net.kdt.pojavlaunch.Tools.getFileName(Tools.java:852)
	at net.kdt.pojavlaunch.Tools.lambda$launchModInstaller$11(Tools.java:933)
	at net.kdt.pojavlaunch.-$$Lambda$Tools$46FTZmdCg2wQlH_7QdcqTtuXPaI.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
