### ISSUE TITLE
[F-REQ] ffmpeg 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#975]
Hehe

**Comment by RadiatedExodus** [comment]
Uh so mind explaining why do you need ffmpeg ? Do you want to play videos in Minecraft?

**Comment by ghost** [comment]
For rendering in replay mod :v

**Comment by ghost** [comment]
Waiting

**Comment by ghost** [comment]
Ok probably won't be added

**Comment by RadiatedExodus** [comment]
Yeah, currently we're focussing on JRE16 and OpenGL 3/4 support

Edit: for 1.17 support duh

**Comment by ghost** [comment]
Ehe
