### ISSUE TITLE
[BUG] <Fabric 1.16.5 Not work>

### ISSUE THREAD

**Issue by NotStolenTotally** [PojavLauncherTeam/PojavLauncher#977]
### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2.Install Fabric 1.16.5
3.Play
4.Error

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_2021-02-27-17-18-06-81](https://user-images.githubusercontent.com/79393331/109384517-e9e55500-791f-11eb-8f2a-b444ad8d2f2c.png)

**Platform:**
 - Device Model [CPH1801]
 - CPU architecture [aarch64] 
 - Android Version [7.0]
 - PojavLauncher Version [3.1 testing]
 - i dont use 3.3.1.1 because lag even when low setting

**Comment by NotStolenTotally** [comment]
Translate: Application / Game comes out with code 1

**Comment by NotStolenTotally** [comment]
Also i have the same issue with forge

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by chrisfal10** [comment]
this mostly happens when u have not installed properly 
best thing to do is 
1 make sure u have enabled hidden files in ur file  explorer 
2 go to games/Pojavlauncher/.minecraft/version
and delete the folder of fabric 
and then reinstall it 
an while reinstaling make sure u have good internet

**Comment by NotStolenTotally** [comment]
> this mostly happens when u have not installed properly
> best thing to do is
> 1 make sure u have enabled hidden files in ur file explorer
> 2 go to games/Pojavlauncher/.minecraft/version
> and delete the folder of fabric
> and then reinstall it
> an while reinstaling make sure u have good internet

Still same

**Comment by NotStolenTotally** [comment]
> Send latestlog.txt

Hold on

**Comment by NotStolenTotally** [comment]
> Send latestlog.txt

Here
[16:07:43] [main/INFO]: Loading for game Minecraft 1.16.5
[16:07:44] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[16:07:44] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...

**Comment by NotStolenTotally** [comment]
> this mostly happens when u have not installed properly
> best thing to do is
> 1 make sure u have enabled hidden files in ur file explorer
> 2 go to games/Pojavlauncher/.minecraft/version
> and delete the folder of fabric
> and then reinstall it
> an while reinstaling make sure u have good internet

Still same

**Comment by khanhduytran0** [comment]
No, send the whole file, not a part of content. You can send as sending image.

**Comment by NotStolenTotally** [comment]
> No, send the whole file, not a part of content. You can send as sending image.

So send the whole lastest log file? Ok

**Comment by khanhduytran0** [comment]
Note that I don't mean to send screenshot, but the file.

**Comment by NotStolenTotally** [comment]
> Note that I don't mean to send screenshot, but the file.

How i send file?

**Comment by NotStolenTotally** [comment]
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/6056501/latest.log)

**Comment by NotStolenTotally** [comment]
there?

**Comment by khanhduytran0** [comment]
It was not latestlog__.txt__

**Comment by NotStolenTotally** [comment]
> It was not latestlog__.txt__


im very dumbass so uh idk lol

**Comment by NotStolenTotally** [comment]
![Screenshot_2021-02-28-16-38-45-49](https://user-images.githubusercontent.com/79393331/109414066-7b69cb00-79e3-11eb-814b-8938aea0aa93.png)
![Screenshot_2021-02-28-16-38-53-98](https://user-images.githubusercontent.com/79393331/109414070-802e7f00-79e3-11eb-981b-5c1ea1d9793e.png)

**Comment by NotStolenTotally** [comment]
![Uploading Screenshot_2021-02-28-16-38-58-57.png…]()

**Comment by NotStolenTotally** [comment]
![Screenshot_2021-02-28-16-38-58-57](https://user-images.githubusercontent.com/79393331/109414098-a8b67900-79e3-11eb-90fe-ec6f7f896676.png)

**Comment by khanhduytran0** [comment]
On .minecraft folder bruh

**Comment by NotStolenTotally** [comment]
> On .minecraft folder bruh

Brb

**Comment by NotStolenTotally** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6056521/latestlog.txt)

**Comment by khanhduytran0** [comment]
Or on PojavLauncher folder

**Comment by NotStolenTotally** [comment]
There

**Comment by khanhduytran0** [comment]
Wait.. 3.1? Can you give me exact version name?

**Comment by NotStolenTotally** [comment]
> Wait.. 3.1? Can you give me exact version name?

3.1 Testing

**Comment by NotStolenTotally** [comment]
My Phone is just lagged alot if playing it on lastest version of the game

**Comment by khanhduytran0** [comment]
Version is outdated and Fabric was not supported on that version.

**Comment by NotStolenTotally** [comment]
Woops i mean 3.3 testing

**Comment by NotStolenTotally** [comment]
So if its outdated i should download lastest version?

**Comment by NotStolenTotally** [comment]
@khanhduytran0 response?

**Comment by AutumnVN** [comment]
> So if its outdated i should download lastest version?

yes

**Comment by NotStolenTotally** [comment]
> > So if its outdated i should download lastest version?
>
> yes

Oh well here it come Super Lag mode

**Comment by khanhduytran0** [comment]
Ah. You want launch Fabric in laggy mode or want crashes?

**Comment by khanhduytran0** [comment]
Or you are using jre9?
