### ISSUE TITLE
[BUG] Athernos Server 

### ISSUE THREAD

**Issue by chrisfal10** [PojavLauncherTeam/PojavLauncher#978]
First Would Love to Thank The developers Of this super awsome project 
### Describe the bug
Cant Connect to Athernos Sever Shows IO Timeout
![20210227_165507](https://user-images.githubusercontent.com/79748717/109385824-99202d00-791c-11eb-9980-ba7e785e6c7e.jpg)

**Add a log file if you want to 

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Select Multiplayer 
3.Selct the athernos server

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Samung M31S 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by LanceAldrei04** [comment]
Check your Connection

**Comment by chrisfal10** [comment]
my internet is good 
when server is offline it says it offline 
but when its up I can't connect

**Comment by LanceAldrei04** [comment]
> my internet is good
> when server is offline it says it offline
> but when its up I can't connect

Check your IP
The IP should like this: "mcadventurej.aternos.me:28245" this is my server join me

**Comment by ghost** [comment]
I had the same problem, the devs told me that is due the architecture. A 32bits client can't join a server of 62bits

**Comment by ghost** [comment]
Unfortunately seems have no solution

**Comment by chrisfal10** [comment]
ok will try thank you alot

**Comment by chrisfal10** [comment]
@Giga-verse U Have 32 bit phone ?

**Comment by khanhduytran0** [comment]
Duplicates #923. See it for solution.
