### ISSUE TITLE
Stupid bug

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#98]
![Screenshot_20200415_153246_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/79343163-5c2e9000-7f2e-11ea-88b7-bc862854c940.jpg)

![Screenshot_20200415_153249_net kdt pojavlaunch](https://user-images.githubusercontent.com/62551802/79343176-605aad80-7f2e-11ea-9fa5-95150a483999.jpg)

**Comment by Doxelix** [comment]
I have too.

**Comment by FranzelDamasco909** [comment]
I have it too .-.

**Comment by khanhduytran0** [comment]
Just moving to other web

**Comment by khanhduytran0** [comment]
Removed
