### ISSUE TITLE
[BUG] Minecraft launch dont work

### ISSUE THREAD

**Issue by clement2540** [PojavLauncherTeam/PojavLauncher#980]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![image](https://user-images.githubusercontent.com/79758484/109392418-3464d280-791c-11eb-993b-e2429d3dcda4.png)

**Platform:**
 Bluestack Emulator 
- PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by chrisfal10** [comment]
so ur using pc

**Comment by clement2540** [comment]
> so ur using pc

yes I use a PC with bluestack emulator because I don't have a tablet or an android phone

**Comment by khanhduytran0** [comment]
- The dialog above can be ignored, ignore it.
- If you have a pc, why don't you install a Minecraft Launcher directly? Going through emulation would be slower.

**Comment by clement2540** [comment]
> * The dialog above can be ignored, ignore it.
> * If you have a pc, why don't you install a Minecraft Launcher directly? Going through emulation would be slower.

**Comment by artdeell** [comment]
Note: all of these are untelated to Pojav and are caused by a bad firmware
