### ISSUE TITLE
[F-REQ] JVM Arguments different for different profiles

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#981]
**Is your feature request related to a problem? Please describe.**
Please add JVM arguments different for different profiles like on minecraft launcher where u can edit jvm arguments for different profiles.
**Describe the solution you'd like**
It will help because all profile dont support same jvm arguments and it crashes my game and i have to redo the process again.
**Describe alternatives you've considered**

**Additional context**

**Comment by Zelioz273** [comment]
Adding on to this, i don't know if it's possible but different settings entirely for the profiles. Like how it is in the actual java launcher. Mostly just saying this so i can have different file locations for my profiles to have different mods for each.

**Comment by Mathias-Boulay** [comment]
We can now set game directory and the java args per version by long pressing the version slider.

Closing.
