### ISSUE TITLE
[BUG] when I press shift and w on my keyboard (my actual keyboard) it does the f11 thing

### ISSUE THREAD

**Issue by RobTopFreak** [PojavLauncherTeam/PojavLauncher#982]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by lalalalalalalalalalalalalalalalalala000** [comment]
Fill in the template boy

**Comment by LanceAldrei04** [comment]
Fill the template

**Comment by RobTopFreak** [comment]
> Fill the template

Fill what template

**Comment by khanhduytran0** [comment]
> 
> 
> 
> 
> <details> <summary><b>Read before submit</b></summary>
> 
> <br>
> 
> - Make sure there was not duplicated issues.<br>
> 
> - Make sure you have filled this issue template, or this will get rejected.
> 
> </details>
> 
> 
> 
> ### Describe the bug
> 
> A clear and concise description of what the bug is.
> 
> 
> 
> **Add a log file if you want to see your bug fixed !**
> 
> 
> 
> The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
> 
> You may need to activate an option in your file explorer to see hidden files and folders.
> 
> 
> 
> Do NOT paste the whole log text ! Instead, add it as a file on this issue.
> 
> 
> 
> ### To Reproduce:
> 
> Indicate steps to reproduce the buggy behavior:
> 
> 
> 
> 1. Start PojavLauncher
> 
> ... *(your set of actions to reproduce the bug)*
> 
> 
> 
> ### Expected behavior:
> 
> I expected ...
> 
> 
> 
> ### Screenshots or videos:
> 
> *Upload here screenshots or videos of the buggy behavior, if possible.*
> 
> 
> 
> **Platform:**
> 
>  - Device Model [e.g. Mi 8 Pro 8/128]
> 
>  - CPU architecture [e.g. aarch64] 
> 
>  - Android Version [e.g. 10]
> 
>  - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]
> 
> 
> 
> 
> 
> <details> <summary><b>Additional context</b></summary>
> 
> <br>
> 
> <pre>
> 
> Add any other context about the problem here.
> 
> </pre>
> 
> </details>
> 
> 

@RobTopFreak this, bruh

**Comment by Slapp13** [comment]
the solution is, change the full screen (F11) to another key (ex F4)
Go to setting - control, and change f11 key to another.

**Comment by Ahmedjk4** [comment]
how to fix ctrl + space + w stops player?
