### ISSUE TITLE
Pojav launcher crashes on my tablet

### ISSUE THREAD

**Issue by TheControllerOfAUs** [PojavLauncherTeam/PojavLauncher#984]
Tablet OS: 10
Tablet manufacturer: Onn
So whenever I go to start 1.12.2 on my tablet it will immediately crash. 
Any solutions?
Steps
1. Open pojavlauncher 
2. Select 1.12.2 
3. Press play.

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by TheControllerOfAUs** [comment]
[
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6063396/latestlog.txt)
](url)

**Comment by TheControllerOfAUs** [comment]
It's not just forge. It's also the regular version too!

**Comment by artdeell** [comment]
What is your device?

**Comment by TheControllerOfAUs** [comment]
A Onn tablet

**Comment by artdeell** [comment]
Send the full model name

**Comment by TheControllerOfAUs** [comment]
Onn. Tablet Gen 2 with Android Go edition.

**Comment by TheControllerOfAUs** [comment]
Model number in settings is 100015685-A

**Comment by artdeell** [comment]
I have a sneaking suspicion that it's 32-bit
So...
Go to launcher settings, disable Auto RAM
Then go to JRE Arguments
Remove everything from there
And put this:
`-Xmx256M`

**Comment by justinthebergejr** [comment]
Onn is not the best tablet in the world. It might not be powerful enough to even run it.

**Comment by TheControllerOfAUs** [comment]
It worked! Is it possible to play with mods though or do I do something else to do that?

**Comment by justinthebergejr** [comment]
Well, its running at 256mb of ram rn, so maybe?

**Comment by justinthebergejr** [comment]
how much fps do you get?

**Comment by TheControllerOfAUs** [comment]
Don't know but my tablet has at least 1 gig of ram available

**Comment by justinthebergejr** [comment]
is the game playable?

**Comment by TheControllerOfAUs** [comment]
Let me check. I saw the title screen pop up and forgot to make a world!

**Comment by justinthebergejr** [comment]
Try loading in a world

**Comment by TheControllerOfAUs** [comment]
It works as well! I will check to see if forge with optifine and a few mods work as well and let you know about that!

**Comment by justinthebergejr** [comment]
I would recommend trying optifine by itself first, and then move on with forge + optifine

**Comment by TheControllerOfAUs** [comment]
Is there a way to increase the ram it can use?

**Comment by artdeell** [comment]
Try increasing the -Xmx???M value

**Comment by TheControllerOfAUs** [comment]
So no 1G of ram it can use? If not then that's fine!

**Comment by TheControllerOfAUs** [comment]
Whenever i put a number that isn't 256 it crashes but I make sure it is 3 digits

**Comment by TheControllerOfAUs** [comment]
I did optifine and forge with optifine I am checking to see if I can use mods

**Comment by khanhduytran0** [comment]
@bonnetthebunny2 you’ve checked for months, stills no result.

**Comment by SteveAlexM** [comment]
My latest version of Pojav Launcher on android crashes a lot, please tell me how to respond

**Comment by mchnjt** [comment]
Should you be opening an issue rather than commenting?

Anyway. Send your latestlog.txt located in **games>PojavLauncher.**

**Comment by mchnjt** [comment]
Also, if you've seen this in discord, just send the latestlog.txt in **#general-android**, as this issue is 2 months ago. We can also help you there.
