### ISSUE TITLE
I can't launch the game.

### ISSUE THREAD

**Issue by anusthanjoshi** [PojavLauncherTeam/PojavLauncher#985]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:

https://user-images.githubusercontent.com/79819769/109445931-ca0d7880-7a68-11eb-956f-15aaa82ff9ba.mp4

**Platform:**
 - Device Model Moto C Plus
 - CPU architecture [e.g. aarch64] 
 - Android Version 7
 - PojavLauncher Version Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
The video doesn't give us anything useful. @HorizonInDust bruh, fill the template!

**Comment by harsh-gupta-10** [comment]
Same happened with me

**Comment by anusthanjoshi** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6072963/latestlog.txt)

**Comment by anusthanjoshi** [comment]
@khanhduytran0

**Comment by anusthanjoshi** [comment]
Ad you can see in the video my game is automatically crashing after it launches but the launcher is working fine.

**Comment by khanhduytran0** [comment]
32bit only accept less RAM (mostly 256MB)

**Comment by anusthanjoshi** [comment]
It tells 504m ram used or stuff tike that

**Comment by anusthanjoshi** [comment]
Will I be able to run or not?

**Comment by anusthanjoshi** [comment]
> 32bit only accept less RAM (mostly 256MB)

Can I play in my device or not sir!

**Comment by Druxelite** [comment]
> > 32bit only accept less RAM (mostly 256MB)
> 
> Can I play in my device or not sir!

It won't, because you didn't fill the whole form

**Comment by harsh-gupta-10** [comment]
Help me why I cant play, game don't launch everytime
