### ISSUE TITLE
[F-REQ]

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#986]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I'm always frustrated when I forgot to put my resource pack on resourcepack folder so I will go back to ZArchiver then put it on resourcepack folder and launch the game and **I WILL WAIT 5 MINUTES ON LOADING SCREEN!**

**Describe the solution you'd like**
I want a _SIMPLE_ floating file manager.

**Describe alternatives you've considered**
I want when I click on _Open Resource Pack Folder_ automatically open an file manager or Add _Special_File Manager_.
![Screenshot_2021-03-01-12-44-59-99](https://user-images.githubusercontent.com/78906627/109453063-16b67b00-7a8c-11eb-81df-0c15186a87ac.png)
![Screenshot_2021-03-01-12-45-26-68](https://user-images.githubusercontent.com/78906627/109453078-1ddd8900-7a8c-11eb-8676-4fcf2e0e3e71.png)

**Comment by artdeell** [comment]
Just leave the launcher running in the background.

**Comment by Mathias-Boulay** [comment]
As android 11 scoped storage is being enforced on the play store, adding a file manager isn't on the roadmap.
Closing the issue.
