### ISSUE TITLE
[BUG] <theres a lot of cube line around all blocks even in water and when i look closer to any block it seem's moving a little bit, my phone is oppo f3 - aarch64 - android 6 , is my phone was compatible?>

### ISSUE THREAD

**Issue by Vergel09** [PojavLauncherTeam/PojavLauncher#989]
### Describe the bug

theres a lot of cube line arroud all blocks even in water and when i look closer to any block it seem's moving a little bit, my phone is oppo f3 - aarch64 - android 6 , is my phone was compatible?

*Log

I/jrelog  (20733): : unused DT entry: type 0xf arg 0x13b8
I/jrelog  (20733): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (20733): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so: unused DT entry: type 0xf arg 0x2196
I/jrelog  (20733): 
I/jrelog  (20733): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so: unsupported flags DT_FLAGS_1=0x81
I/jrelog  (20733): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so: unused DT entry: type 
I/jrelog  (20733): 0xf arg 0x6a46
I/jrelog  (20733): WARNING: linker: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so: unsupported flags DT_FLAGS_1=0x81

![Screenshot_2021-03-01-16-43-07-52](https://user-images.githubusercontent.com/79831467/109476541-f3c99e00-7a6e-11eb-8841-1f11e192658b.png)

![Screenshot_2021-03-01-16-44-23-57](https://user-images.githubusercontent.com/79831467/109476567-fa581580-7a6e-11eb-9e0b-b8337f181660.png)

1. Start PojavLauncher
When I played my world all of this happened, all of blocks moving a little bit, theres a cube line around the corner of blocks

I expected to fix this

**Platform:**
 - Device Model [oppo f3, 6/64]
 - CPU architecture [aarch64] 
 - Android Version [6]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by Vergel09** [comment]
![Screenshot_2021-03-01-16-43-07-52](https://user-images.githubusercontent.com/79831467/109472726-67b57780-7a6a-11eb-9739-581febcb33ea.png)
![Screenshot_2021-03-01-16-44-23-57](https://user-images.githubusercontent.com/79831467/109472748-6c7a2b80-7a6a-11eb-8c63-5aa2966f46bc.png)

**Comment by khanhduytran0** [comment]
Try to toggle fullscreen

**Comment by Vergel09** [comment]
I toggled it already but nothing happens

**Comment by LanceAldrei04** [comment]
Same

**Comment by NotStolenTotally** [comment]
sorry but uh how do i install Windows JRE8 @khanhduytran0

**Comment by Mathias-Boulay** [comment]
Stale issue from an old version
Closing
