### ISSUE TITLE
[Request] Better versions sorting

### ISSUE THREAD

**Issue by notfoundname** [PojavLauncherTeam/PojavLauncher#99]
Hello, it would be much easier to use launcher if some kind of versions sorting will be added. Example is on my screenshot.
![изображение](https://user-images.githubusercontent.com/48317169/79343302-d24bea80-7f60-11ea-8f58-6b5d0a59c205.png)

**Comment by notfoundname** [comment]
Or, there will be two lists: downloaded and not downloaded versions.

**Comment by khanhduytran0** [comment]
Ok

**Comment by Azapru** [comment]
Yay

**Comment by notfoundname** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.5.0-preview1
