### ISSUE TITLE
[F-REQ] Chat issue

### ISSUE THREAD

**Issue by Zelioz273** [PojavLauncherTeam/PojavLauncher#992]
**Is your feature request related to a problem? Please describe.**
As some people have commented on before, the chat bar is hidden by the keyboard. I've seen that you can use gboard, and i have, but my problem is that i have keys(ctrl, alt, fn keys, and others) i need to use on my normal keyboard("Hacker's Keyboard") that aren't on any floating keyboards that i could find.

**Describe the solution you'd like**
I don't want to be that one mcinabox user- becuase i actually prefer pojavlauncher alot over it, but they solved this by having a pop-up box you could write in and press enter to send it to the chat. I'm thinking maybe have this but as an option, so that gboard users can still just use that fine. 

**Describe alternatives you've considered**
Other options were to decompile minecraft anf change where the chat showed up, use a mod called bedrockify which changed the position of it(but changes a lot of other stuff), and obviously gboard.

**Comment by khanhduytran0** [comment]
> but they solved this by having a pop-up box you could write in and press enter to send it to the chat. I'm thinking maybe have this but as an option, so that gboard users can still just use that fine.

Maybe...

> Other options were to decompile minecraft anf change where the chat showed up

Do you know the amount of Minecraft versions?

**Comment by Zelioz273** [comment]
> Do you know the amount of Minecraft versions?

Yeahh it'd be unreasonable to decompile every single version to change a single thing, i was only proposing that as a alternative one time solution.

**Comment by Warsini974** [comment]
> > but they solved this by having a pop-up box you could write in and press enter to send it to the chat. I'm thinking maybe have this but as an option, so that gboard users can still just use that fine.
> 
> Maybe...
> 
> > Other options were to decompile minecraft anf change where the chat showed up
> 
> Do you know the amount of Minecraft versions?

can't write 👉 '

**Comment by Warsini974** [comment]
In pojav

**Comment by Warsini974** [comment]
@khanhduytran0

**Comment by khanhduytran0** [comment]
> Use gboard

**Comment by Warsini974** [comment]
> > Use gboard

I use gboard

**Comment by khanhduytran0** [comment]
Press keyboard again before type it.

**Comment by Warsini974** [comment]
> Press keyboard again before type it.

Type keyboard 2x?

**Comment by khanhduytran0** [comment]
@Zelioz273 then gboard gloating keyboard?

**Comment by Zelioz273** [comment]
> I've seen that you can use gboard, and i have, but my problem is that i have keys(ctrl, alt, fn keys, and others) i need to use on my normal keyboard("Hacker's Keyboard") that aren't on any floating keyboards that i could find.

Already said why i didn't just use that

**Comment by khanhduytran0** [comment]
> > I've seen that you can use gboard, and i have, but my problem is that i have keys(ctrl, alt, fn keys, and others) i need to use on my normal keyboard("Hacker's Keyboard") that aren't on any floating keyboards that i could find.
> 
> Already said why i didn't just use that

Bruh does chat requires these keys, can’t you switch keyboard ingame?

**Comment by Zelioz273** [comment]
You literally need fn keys, i don't think i need to explain why. Ctrl and alt have special uses for the game like inventory management(eg.: ctrl q drops a stack), and i use ctrl and alt for shortcut keys. Honestly using a seperate app to fix a problem also feels kind of cheap imo

**Comment by Zelioz273** [comment]
How bad would it be to add a pop-up textbox that shows above your keyboard and lets you input stuff to send to the actual chat/sign/commandblock/etc? If it causes any lag for some players, add an option to toggle it in settings

**Comment by Mathias-Boulay** [comment]
The visible textbox approach poses a huge practical issue for editing stuff.
With controls v2.2 the approach for the keyboard dramatically changed under the hood.

With the recently merged control v2.4, the auto-correct is there to help people write in chat easily/ see what they are writing. 😄 

Since chat is now easy enough to type on, I'll close the issue.
