### ISSUE TITLE
[BUG]Select Account issue on my Tablet

### ISSUE THREAD

**Issue by AmadeusDoesStuff** [PojavLauncherTeam/PojavLauncher#993]
When I click select account after I already logged in it just says Select Account. I tried relogging in and it says Error account already signed in.

**Comment by Mathias-Boulay** [comment]
@AmadeusDoesStuff does the issue still happens with the current google play release ?

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer from author
Closing
