### ISSUE TITLE
[Mod not working] The mod works on MCinabox but crashes on Pojav. 

### ISSUE THREAD

**Issue by 10dine** [PojavLauncherTeam/PojavLauncher#995]
<details> 
The mod in question is SanLib. It is a dependency of Claysoldiers mod by SanAndreasP on forge. The main error the crash log shows is "net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SanAndreasPs Mod Library (sanlib)
Caused by: java.lang.NoSuchMethodError: org.lwjgl.opengl.Display.getTitle()Ljava/lang/String;". It does work on MCinabox.
<summary><b>Mod not working because of missing method?</b></summary>
</details>

### Describe the bug
Not much that I understand but I think its because of methods of java apps(?) or maybe java opengl(?) that aren't in the Pojav Java Runtime. 

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Make sure Claysoldiers mod and it dependencies are in mod folder.
2. Start PojavLauncher.
3. Wait for black screen.
4. App crashes and sends user to previous screen (app drawer or home screen)

### Expected behavior:
I expected it to work fine since its working on pc and on MCinabox.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

[]()https://drive.google.com/file/d/13My7i3f4eF8pvcAFUSuRzCTLAtUDEDD_/view?usp=drivesdk 

Sorry I don't know how to upload the crash log on github mobile so this is a link to the crash file.

**Comment by artdeell** [comment]
Fixed in recent builds; download from Actions (not releases) on v3_openjdk branch
