### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by NotStolenTotally** [PojavLauncherTeam/PojavLauncher#998]
How do i Install JRE8 and what Device should i install Windows,Linux,Or macOS?

**Comment by artdeell** [comment]
JRe8 is embedded in the launcher since release 3.3.0, and available for all platforms in release 3.3.1.1

**Comment by NotStolenTotally** [comment]
> JRe8 is embedded in the launcher since release 3.3.0, and available for all platforms in release 3.3.1.1

yeah im using ver 3.3.1.1

**Comment by NotStolenTotally** [comment]
so i uninstall Java Runtime?

**Comment by artdeell** [comment]
If you have 3.3.1.1 release, don't do anything, your JRE is already at version 8

**Comment by NotStolenTotally** [comment]
how bout 3.1 testing? (My friend phone)

**Comment by artdeell** [comment]
Also JRE 8

**Comment by NotStolenTotally** [comment]
Since he had a Kid account so he cant install Newest Version

**Comment by NotStolenTotally** [comment]
oh

**Comment by NotStolenTotally** [comment]
> Also JRE 8

btw last question is there any faster Java runtime? Like my friend lagged alot

**Comment by NotStolenTotally** [comment]
im kinda bad at english so i hope you understand

**Comment by artdeell** [comment]
There are none. JRE9 exists but it's very slow.

**Comment by NotStolenTotally** [comment]
> There are none. JRE9 exists but it's very slow.

oh ok then thanks!
